Allow empty numeric fields if not required
joomla/joomla-cms pull request #11492
Opened 2016-08-06 12:10 UTC by jo-sf

It is currently not possible to save a form (e.g. the global configuration form) with empty numeric fields if these fields are not required and do not have a default value. After applying this PR empty numeric fields will be possible.

#### Testing Instructions

**Status Quo**

* Install #11322 
* Open the file `administrator/components/com_config/model/form/application.xml` with a text editor and remove the line `default="21"` from the definition of the "FTP Port" field (the field name is "ftp_port")
* Save the file
* Open the file `configuration.php` with a text editor, search for "$ftp_port" and change the assignment to this variable into an empty string
* Save the file (since this file is by default write protected you might need to force the saving and/or modify the access rights prior to writing the file)
* Open in the Joomla administration the global configuration form and activate the "Server" tab
* Enable "FTP" such that the "FTP Port" field is shown
* The value in this field should be "1" (the minimum value for this field)
* Remove the value "1" from the field and press the "Save" button
* You should get an error message (Invalid field: FTP Port) and the value in the "FTP Port" field is again "1"
* Leave the global configuration form by means of the "Cancel" button

**Change**

* Now install this PR
* Check that the value for the "$ftp_port" variable in configuration.php is still an empty string, if not change the assignment accordingly and save the file
* Open in the Joomla administration the global configuration form and activate the "Server" tab
* Enable "FTP" such that the "FTP Port" field is shown
* There should be no value in this field except the hint value "21" which vanishes as soon as you type anything into the field
* Press the "Save" button
* The configuration should be saved successfully and the value for "$ftp_port" in configuration.php should still be an empty string, moreover the "FTP Port" field should still only contain the hint "21"
* Write "21" into the "FTP Port" field and press the "Save" button
* Check the configuration.php file, the value for "$ftp_port" should now be "21", moreover the "FTP Port" field should now contain the value "21"
* Clear the "FTP Port" field and press the "Save" button
* Saving the configuration should again succeed, the value for "$ftp_port" should again be an empty string ans the "FTP Port" field should show the hint "21"

2016-08-08 18:55 UTC, andrepereiradasilva commented on libraries/joomla/form/fields/number.php
> +			$value = ($this->required and isset($this->min)) ? $this->min : '';
`and` ?

2016-08-09 07:26 UTC, jo-sf commented on libraries/joomla/form/fields/number.php
> +			$value = ($this->required and isset($this->min)) ? $this->min : '';
Yes - why? Both "and" and "&&" are valid logical operators in PHP - and both are in use in the Joomla sources.

But if there is a coding rule für Joomla development not to use "and" and "or" but instead "&&" and "||" this is easy to change.

2016-08-09 08:44 UTC, andrepereiradasilva commented on libraries/joomla/form/fields/number.php
> +			$value = ($this->required and isset($this->min)) ? $this->min : '';
the coding standards that exist are in https://joomla.github.io/coding-standards/?coding-standards/chapters/php.md

anyway in the code we "almost" always use '&&' so IMO it's better to normalize that.

2016-08-09 09:50 UTC, jo-sf commented on libraries/joomla/form/fields/number.php
> +			$value = ($this->required and isset($this->min)) ? $this->min : '';
Well, the coding standard do not say anything about using "&&" and "||" but not "and" and "or" - or at least I didn't find any hint regarding this. But since you say that you're nearly always use "&&" and "||" I'll change the three files accordingly.

BTW if you open the coding standards page e.g. via the link above you'll get most of the example code messed up. and I've no clue why. Opening another page (e.g. "Basic Guidelines") and then going back to "PHP Code" will fix that. But when you do a page reload (not even a forced reload) the example code is messed up again.

2016-11-09 20:01 UTC, Luchen6 commented
I have tested this item :white_check_mark: successfully on e34a81ed8abef73dc9ae9ef8de410e153e4625ee<br /><br />Tested this successfully according to the instructions.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11492">issues.joomla.org/tracker/joomla-cms/11492</a>.</sub>

2017-01-10 14:48 UTC, franz-wohlkoenig commented
I have tested this item :red_circle: unsuccessfully on e34a81ed8abef73dc9ae9ef8de410e153e4625ee<br /><br />Part "Status Quo": #11322: `No Matching Results` in Patchtester

With and without Patch Field `FTP-Port` is empty in `global configuration` and `configuration.php`. If Field is filled by `21` it's shown in both Places.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11492">issues.joomla.org/tracker/joomla-cms/11492</a>.</sub>

2017-01-10 23:01 UTC, zero-24 commented
@jo-sf as #11322 is closed can you fix the merge conflicts and confirm that it is still working even without the changes from #11322 ?

2017-01-12 19:26 UTC, jo-sf commented
@franz-wohlkoenig @zero-24 I will resolve the merge conflicts asap and then I'll look for another test case since the test instructions given above will no longer work due to PR #11322 having been closed some days ago. My patch should work regardless of #11322 btw. As soon as both tasks (merging and finding a new test case) are complete I'll come back. Hope that's OK.

2017-01-17 19:28 UTC, jo-sf commented
@franz-wohlkoenig @zero-24 I searched for any other form field where this PR might be tested with but there seems to be none within Joomla.

Due to that and because the intention for PR #11322 is IMO good (help administrators in setting up a Joomla installation and try to prevent human errors as much as possible) I copied @andrepereiradasilva 's changes to my PR (hope that's OK @andrepereiradasilva ?). I also found another configuration form where a TCP port is to be configured (LDAP authentication plugin) and I changed that as well.

In checking and changing both XML files I tried to use the same layout (style) for all field definitions even if that resulted in more changed lines than absolutely necessary. It this is not desired I can undo this and only leave the changed field definitions.

2017-01-19 17:18 UTC, franz-wohlkoenig commented
@jo-sf so no more test necessary?

2017-01-20 07:32 UTC, jo-sf commented
@franz-wohlkoenig I don't think you want to merge my PR with the staging code without any successful human test... due to that I assume that someone or better two or more people should test this PR prior to deciding whether it should be merged with the staging code.

2017-01-20 08:56 UTC, franz-wohlkoenig commented
@jo-sf i can test using patchtester on latest nightly, i don't merge pr with staging code;-)

2017-01-20 19:23 UTC, jo-sf commented
@franz-wohlkoenig yes please test with the latest nightly, and I hope it will work without problems.

2017-01-21 12:56 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 46594c78077edddb6a5acfe0c01add75bdb79c83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11492">issues.joomla.org/tracker/joomla-cms/11492</a>.</sub>

2017-01-21 17:52 UTC, zero-24 requested changes

2017-01-21 17:52 UTC, zero-24 commented on libraries/joomla/form/form.php
> +					if (($value === '' || $value === null) && ! $required)
please add a clean line befor the if ;)

2017-01-21 18:21 UTC, zero-24 commented
I have tested this item :red_circle: unsuccessfully on 46594c78077edddb6a5acfe0c01add75bdb79c83<br /><br />There is no hint default value for the LDAP Plugin port and SMTP Port if that is fixed. (Should be just the `hint` attribute in the XML) this is read to merge.

Great work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11492">issues.joomla.org/tracker/joomla-cms/11492</a>.</sub>

2017-01-22 10:00 UTC, jo-sf commented on libraries/joomla/form/form.php
> +					if (($value === '' || $value === null) && ! $required)
clean line added...

2017-01-22 10:30 UTC, jo-sf commented
@zero-24 I added the hint attribute both to the LDAP port and the SMTP port fields.

My suggestion was however (see the recipe for defining numeric fields above) to have either the default or the hint attribute with numeric fields. The idea behind this was that the most common value is used as the default value and that the typical values for this field should be described in the field's description visible if you hover the field name. Both for the LDAP and the SMTP port fields there is no single typical value but the value to use depends upon other settings like the secure SMTP setting (ports can be 25, 465 or 587) or secure LDAP communication via TLS (ports can be 389 for unsecure communication and 636 for TLS secured communication).

Maybe the LDAP port field description should be changed accordingly as is already the case for the SMTP port field description. Currently the LDAP port field description only states that the default port is 389.

2017-01-22 11:43 UTC, zero-24 approved these changes

2017-01-22 11:46 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on 892d4dff2c222672fb364d11ba62017514ca6e49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11492">issues.joomla.org/tracker/joomla-cms/11492</a>.</sub>

2017-01-22 11:47 UTC, zero-24 commented
RTC as after the successful test just cosmetical changes was made. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11492">issues.joomla.org/tracker/joomla-cms/11492</a>.</sub>

2017-01-22 14:58 UTC, merged

2017-01-22 14:58 UTC, wilsonge commented
Merged - thanks!