New Feature, Multilanguage: Add the possibility of displaying associations in article info and in articles list. Replaces #11935
joomla/joomla-cms pull request #12042
Opened 2016-09-15 08:40 UTC by infograf768

Same patch as #11935 but towards 3.7.x
See there for instructions.

2016-09-15 08:46 UTC, brianteeman commented
No problem with the merge now

2016-09-15 08:47 UTC, infograf768 commented
Yeah, was patchtester, as I said. It does not feel well when there is something to correct, even if it is only in an xml...

2016-09-15 08:48 UTC, brianteeman commented
Report it as a bug then

2016-09-15 08:51 UTC, infograf768 commented
Setting back to RTC as it was just a matter of adapting to 3.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12042">issues.joomla.org/joomla-cms/12042</a>.</sub>

2016-09-15 09:06 UTC, Bakual commented on layouts/joomla/content/info_block/associations.php
> +	<?php echo ContentHelperAssociation::displayAssociations($id); ?>
Imho, this JLayout is bad as it is only useable by com_content. Also the JLayout itself is fetching the data which is wrong as well. The JLayout should be reusable across extensions and also only deal with displaying things, not fetching data.
So the data should be already fetched by the view or model and passed to the layout.

2016-09-15 09:09 UTC, Bakual commented on administrator/components/com_content/config.xml
> +			name="flags"
If the JLayout is done properly, you wouldn't even need a parameter here.
Fetch both the data for the language code and the image and pass both to the JLayout. Show the flags in the default JLayout. A template/user can then easily override the JLayout and use the language codes instead.

2016-09-15 09:10 UTC, Bakual commented on components/com_content/helpers/association.php
> +							$flag = JHtml::_('image', 'mod_languages/' . $language->image . '.gif',
Don't return HTML from an non-overrideable helper function.
Instead return the language object and let the JLayout handle the HTML.

2016-09-15 09:11 UTC, Bakual requested changes
Imho, this isn't ready from a code review point of view.

2016-09-15 09:18 UTC, infograf768 commented
The layout is only aimed at articles. Patches welcome...

2016-09-15 11:38 UTC, Bakual commented
See https://github.com/infograf768/joomla-cms/pull/43 for the proposed changes.

2016-09-15 12:55 UTC, mbabker commented
> The layout is only aimed at articles (infoblock and list).

Then put the layout in com_content's folder.  There have already been crap decisions made putting extension specific layouts in the global layouts directory, `JLayout` supports a `layouts` directory at the component level so if it's really that hard locked to a single component that's where it should live.

2016-09-16 05:16 UTC, infograf768 commented
> Then put the layout in com_content's folder. There have already been crap decisions made putting extension specific layouts in the global layouts directory, JLayout supports a layouts directory at the component level so if it's really that hard locked to a single component that's where it should live.

The info_block layout folder is in the global layouts/joomla/content/ folder. Wrong or not, the aim of this PR is not to refactor that part.

2016-09-16 06:57 UTC, infograf768 commented
@Bakual 
Thanks, I used your code and kept the choice between sef label and flags.

This has to be tested again.
@alexgarel
@zero-24 
@alikon

2016-09-16 07:01 UTC, infograf768 commented
Setting back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12042">issues.joomla.org/joomla-cms/12042</a>.</sub>

2016-09-16 07:34 UTC, Bakual commented
> kept the choice between sef label and flags.

Did you try if it works when you add that parameter to menuitem and article as well? In theory it should work and I'm sure the request will come sooner or later.

2016-09-16 08:35 UTC, infograf768 commented
I guess you mean in admin?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12042">issues.joomla.org/joomla-cms/12042</a>.</sub>

2016-09-16 08:52 UTC, infograf768 commented
@Bakual 

In fact I do not understand what you mean.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12042">issues.joomla.org/joomla-cms/12042</a>.</sub>

2016-09-16 09:12 UTC, Bakual commented
You added two new parameters. `show_associations` is added to component config, view (menu item) configs and article options. The other param `flag` you only added to component config. However it should work fine when you add that one to the other places as well.

2016-09-16 09:12 UTC, Bakual approved these changes

2016-09-16 09:16 UTC, Bakual commented on components/com_content/models/articles.php
> +				$item->flag         = $item->params->get('flags');
You don't have to add that line. You check the params in the layout anyway.

2016-09-16 09:17 UTC, Bakual commented on components/com_content/views/article/view.html.php
> +			$item->flag         = $item->params->get('flags');
Same here, line to check the flag param is not needed.

2016-09-16 09:31 UTC, infograf768 commented on components/com_content/views/article/view.html.php
> +			$item->flag         = $item->params->get('flags');
In this case the info-block/ associations should be changed I guess to
`<?php if ($displayData['item']->params->get('flags')) : ?>` 

Right?

2016-09-16 09:32 UTC, infograf768 commented
> You added two new parameters. show_associations is added to component config, view (menu item) configs and article options. The other param flag you only added to component config. However it should work fine when you add that one to the other places as well.

I did do it on purpose. The UI should be consequent: or we use for all or not. Deciding that it would show flags in blogs and sef icon in featured makes no sense imho.

2016-09-16 10:11 UTC, Bakual commented
> I did do it on purpose. 

Ok.

2016-09-16 10:12 UTC, Bakual commented
I have tested this item :white_check_mark: successfully on 66f272bedcb65882b75d07d0691448da9a236fbd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12042">issues.joomla.org/joomla-cms/12042</a>.</sub>

2016-09-16 10:17 UTC, Bakual commented on layouts/joomla/content/info_block/associations.php
> +		<?php if ($displayData['item']->params->get('flags')) : ?>
Sorry for not spotting it before, you forgot to specify the default value here. Since it is 1 in the XML it should be 1 here as well. So use:
<?php if ($displayData['item']->params->get('flags', 1)) : ?>

It doesn't matter in this specific case as we have to save the params to get the associations showing, but it is good practice.
Also it may be useful to add a `sshowon="show_associations:1"`` to this field in the XML. What do you think?

2016-09-16 16:42 UTC, infograf768 commented
@Bakual 
Done.

2016-09-16 18:20 UTC, Bakual commented
Thanks, looks great now. :+1:

2016-09-17 09:31 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 19941bb46c72b4d2083644ebbf850506aba27495<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12042">issues.joomla.org/joomla-cms/12042</a>.</sub>

2016-09-17 09:39 UTC, infograf768 commented
RTC, at last...

@wilsonge You may now merge in 3.7. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12042">issues.joomla.org/joomla-cms/12042</a>.</sub>

2016-09-18 13:39 UTC, merged

2016-09-18 13:40 UTC, wilsonge commented
Thanks JM :)