No lang image
joomla/joomla-cms pull request #12051
Opened 2016-09-16 12:27 UTC by Bakual

Currently in a multilingual site the backend indicates the language in several places using a country flag. Since that is not always an appropriate thing some expressed the wish to hide those flags which is currently not possible.
Based on a discussion in https://github.com/joomla/joomla-cms/pull/12034 and based on some code started by @andrepereiradasilva this is what I came up with.

### Summary of Changes
Basically this adds the possibility to assign no image to a content language. Until now, a flag had to be chosen.
To avoid showing invalid images all over the place, the code had to be adjusted to check the value of the content language image property and fall back to a label or nothing if it wasn't specified.

### Testing Instructions
1. Set up a multilingual site, make sure you have some associations set as well
* Adjust at least one content language so it doesn't have an image assigned. Leave at least one language with a flag so you can test both at the same time :smile: 
* Check the various places where a flag is usually shown;
- [ ] Menu module shows a flag for a menu with a language specific home
- [ ] Menu manager shows the language specific home button as flag
- [ ] Template manager shows the language specific default button as flag
- [ ] Several lists show the language with a preceding flag
- [ ] Associations have a flag in the tooltip
- [ ] In a module edit, the "Menu Assignment" tab shows the language specific home menu items with a flag

A note: This is strictly about backend. As far as I know in frontend the only place the flags are used is the language switcher module, and that one already has a switch to toggle between flags and text.

### Documentation Changes Required
None that I'm aware of.

2016-09-16 21:31 UTC, andrepereiradasilva commented
Nice @Bakual ! Thanks for doing this. Will test tomorrow.

2016-09-16 21:40 UTC, MATsxm commented
Like Andre, great and thanks for this... Hope being able to test it tomorrow.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-09-16 21:47 UTC, zero-24 commented on administrator/components/com_menus/helpers/html/menus.php
> +					if ($item->image)
Please add a clean line here

2016-09-16 21:47 UTC, zero-24 commented on administrator/components/com_menus/helpers/html/menus.php
> +					$tooltipParts[] = $item->title;
Same here

2016-09-16 21:49 UTC, zero-24 commented on administrator/components/com_modules/views/module/tmpl/edit_assignment.php
> +											if ($link->language_image)
Please use opening <?php and closing ?> in this if

2016-09-16 21:50 UTC, zero-24 commented on administrator/components/com_newsfeeds/helpers/html/newsfeed.php
> +					if ($item->image)
A clean line please

2016-09-16 21:50 UTC, zero-24 commented on administrator/components/com_newsfeeds/helpers/html/newsfeed.php
> +					$tooltipParts[] = $item->title;
Same here

2016-09-16 21:53 UTC, zero-24 requested changes
Please fix the comments ;)

2016-09-17 00:42 UTC, MATsxm commented
I have tested this item :red_circle: unsuccessfully on 08b336a19c06d12ac1709e12e2557caf6520d9ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-09-17 00:52 UTC, MATsxm commented
I have tested with 3 languages (en-GB, fr-CA and fr-FR WOITHOUT image)on fresh install and few unexpected behaviors happened.
### All menu items view, it looks fine:
![screen shot 2016-09-16 at 19 45 25](https://issues.joomla.org/uploads/1/09b2a4901fb94a58f25614fcfbcf53ce.png)
### Content languages and templates also:
![screen shot 2016-09-16 at 19 46 33](https://issues.joomla.org/uploads/1/3b037764beeb4063c85cd5a698bd063e.png)
![screen shot 2016-09-16 at 19 48 28](https://issues.joomla.org/uploads/1/03631e49d5dbaad61b174e0c4ae371c2.png)

For other views, nothing seems to appear:
(tested Contact, modules, cat, articles)
![screen shot 2016-09-16 at 19 50 56](https://issues.joomla.org/uploads/1/32695366a5d17d17ca63ee3a7adbbd41.png)
![screen shot 2016-09-16 at 19 51 07](https://issues.joomla.org/uploads/1/e0baf572a675625b3475c00bb6655445.png)
![screen shot 2016-09-16 at 19 51 23](https://issues.joomla.org/uploads/1/fa56799f9c39ed3746bb6a298e87f2f3.png)![screen shot 2016-09-16 at 19 51 32](https://issues.joomla.org/uploads/1/1f0203faeef8bba1af13cd1b36fa9bb5.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-09-17 11:03 UTC, Bakual commented on administrator/components/com_modules/views/module/tmpl/edit_assignment.php
> +											if ($link->language_image)
I used the same as in the line before but I can fix both then :smile:

2016-09-17 11:29 UTC, andrepereiradasilva commented
i tested this. All seems fine except:

1 bug in contacts:
![image](https://cloud.githubusercontent.com/assets/9630530/18607900/3e91f148-7cd2-11e6-8b17-bb55e463324a.png)

Lack of uniformization. Sometime the language code is used, another times the language sef id used.
IMHO the language code should always be used

![image](https://cloud.githubusercontent.com/assets/9630530/18607901/455801d4-7cd2-11e6-842d-8fea5355ab67.png)

![image](https://cloud.githubusercontent.com/assets/9630530/18607904/4ef9b23c-7cd2-11e6-8bb2-7e49b3125c3b.png)

![image](https://cloud.githubusercontent.com/assets/9630530/18607905/52b3221e-7cd2-11e6-957b-3d4975bf66e4.png)

2016-09-17 11:30 UTC, andrepereiradasilva commented
Besides the comments above IMHO the new layout needs to be also applied in com_weblinks repo

2016-09-17 11:30 UTC, Bakual commented
@MATsxm That is strange, it looks like this for me:
![lists](https://cloud.githubusercontent.com/assets/1018684/18607902/a7415992-7cda-11e6-9f87-aa323b161a04.PNG)

Can you try with error reporting enabled? Maybe there is some error hidden there.
And also check if the file /layouts/joomla/content/language.php is present. It should look like this: https://github.com/Bakual/joomla-cms/blob/no-lang-image/layouts/joomla/content/language.php

2016-09-17 11:40 UTC, MATsxm commented
@Bakual 
TBH, I suspect a problem while applying the patch.
I'll try on a new install later today. 
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-09-17 11:40 UTC, Bakual commented
@andrepereiradasilva Yes, if this is merged, the Weblinks should be adjusted as well.
The contacts bug should be fixed now. I missed the helper function there.

As for the inconsistency, the thing is that the language code (`en-GB`) would look very ugly on that "home" button or in the menu because it is much longer. I've also used the same as is already been used in the association labels.
For the association tooltip I have settled for the language code because the SEF code is already present below the tooltip. Changing that to SEF doesn't make sense as it would be redundant information. We could completely remove it if we want.

2016-09-17 11:52 UTC, andrepereiradasilva commented
> As for the inconsistency, the thing is that the language code (en-GB) would look very ugly on that "home" button or in the menu because it is much longer. I've also used the same as is already been used in the association labels.

But if you have a sef 'de' and other 'de-ch' it would look even "uglier".
Also you used the language code in other places
![image](https://cloud.githubusercontent.com/assets/9630530/18608021/7f874448-7cd5-11e6-9983-89fc2ae21eef.png)

I still think is more correct to have the language code than the SEF. The sef can be anything the user wants, the langauge code must respect iso.

> For the association tooltip I have settled for the language code because the SEF code is already present below the tooltip. Changing that to SEF doesn't make sense as it would be redundant information. We could completely remove it if we want.

reggarding association tooltip an idea would be to improve it like we did in GSOC multilingual project. Example:
![image](https://cloud.githubusercontent.com/assets/9630530/18608003/e5a59e2e-7cd4-11e6-9afd-5c820ba99a41.png)

See https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_associations/helpers/associations.php#L498

that way you don't even need to use the language code or sef. in this case we could just add or not the flag if exists as you do in the language columns

2016-09-17 12:29 UTC, Bakual commented
In the module assignment I just went with the data that was available. :smile: 
In the other places I think it makes more sense to use the same code like it is already used for associations. Or we have to change that as well. But I think the additional value is not worth it. To be honest, I think most sites will not have multiple "dialects" of the same language installed.

The suggestion for the association tooltip looks nice. However I'd use a popover there with the language as title. I'll have a look later.

2016-09-17 15:19 UTC, Bakual commented
@andrepereiradasilva What would you say if we do this:
![popover](https://cloud.githubusercontent.com/assets/1018684/18609126/b38258d0-7cfa-11e6-9d18-667294466c39.PNG)

Would be the same with or without flag.

2016-09-17 15:29 UTC, andrepereiradasilva commented
fine by me

2016-09-17 15:34 UTC, jeckodevelopment commented
@Bakual why not using two lines?
`Article (en-GB)
Category (en-GB)` 
and avoid also the double brackets

2016-09-17 15:35 UTC, andrepereiradasilva commented
i would go for 

```
article-title
Category: category-title
```

And i would also make that tooltip a layout that does not depedn on the component helper ...

2016-09-17 16:21 UTC, Bakual commented
Good points 👍

2016-09-17 16:28 UTC, infograf768 commented
Did not we say that it should not impact frontend? 
I.e. again, I would not let a Content Language without an Image.

The way this is done, it does impact when one has chosen to display flags in frontend.
Example: took off the flag for Macedonian language:

![screen shot 2016-09-17 at 18 26 06](https://cloud.githubusercontent.com/assets/869724/18609527/760732b4-7d04-11e6-9ce1-fffaa215ceec.png)

2016-09-17 16:30 UTC, andrepereiradasilva commented
yeah, i guess the language switcher should also check if the image exists.

2016-09-17 17:46 UTC, Bakual commented
From the intial PR description:
> A note: This is strictly about backend. As far as I know in frontend the only place the flags are used is the language switcher module, and that one already has a switch to toggle between flags and text.

If you don't set a flag for a specific language I'm supposing you're not showing the flags in frontend at all. I don't think anyone wants to mix it in frontend.

2016-09-17 18:51 UTC, Bakual commented
> And i would also make that button/tooltip a layout that does not depend on the component helper ...

It already uses a JLayout, but that one isn't done optimal. It expects the link/tooltip/text already present as a string saved in $item->link. The helper class is needed anyway to query the associated items data from the database.

Updated the PR to show a popover as the association tooltip:
![tooltip](https://cloud.githubusercontent.com/assets/1018684/18610291/8012b418-7d18-11e6-89e9-97a34343c486.PNG)

2016-09-17 21:00 UTC, infograf768 commented
> If you don't set a flag for a specific language I'm supposing you're not showing the flags in frontend at all. I don't think anyone wants to mix it in frontend.

we should not suppose. we should make it easier for users. this pr also forces to refactor the lang switcher as no one would understand that opting to display flags may not...

this is exactly why i think this proposal is wrong. in back-end we should have a general parameter concerning all content languages, and still assign a flag/icon to each of them.

this pr would just add confusion.

2016-09-17 21:08 UTC, Bakual commented
> in back-end we should have a general parameter concerning all content languages

That would only be possible as a parameter in the Joomla config (ridiculous) or as a template parameter (using overrides).

> this pr would just add confusion.

Why? If you set the flag to "None", no flag is shown. Quite straight forward imho. And if you set a flag to "None", no flag is shown in frontend as well.
I can adjust the language switcher module to deal with that. It's easy. I would just need to know what it should show instead. For the dropdown I'd say just show the name of the language without any flag, but what should it show in the other mode where only flags are shown? The language name or a label with SEF code? Both alternatives imho look very wrong, that's why I didn't do anything there.

2016-09-17 21:27 UTC, andrepereiradasilva commented
i agree with bakual on this.

> I can adjust the language switcher module to deal with that. It's easy. I would just need to know what it should show instead. For the dropdown I'd say just show the name of the language without any flag

Yes. Makes sense.

> but what should it show in the other mode where only flags are shown? The language name or a label with SEF code? Both alternatives imho look very wrong, that's why I didn't do anything there.

I would a label. Yes it does not look good, but remember this is just a fallback.

2016-09-18 05:17 UTC, infograf768 commented
> That would only be possible as a parameter in the Joomla config (ridiculous) or as a template parameter (using overrides).

The simple solution, as I had suggested, is a new option in com_languages.
Then that param would be fetched in the new layout.

2016-09-18 07:04 UTC, Bakual commented
> The simple solution, as I had suggested, is a new option in com_languages.
Then that param would be fetched in the new layout.

As I said earlier, I will not do that as fetching params from another extension (`com_languages`) imho is a wrong thing to do. Even if it is already done today in the application, I don't think we should start doing that in every component. It just feels very wrong to me.

2016-09-18 14:56 UTC, mbabker commented
Architecturally, global configuration values should NOT be part of an extension of any type.  These are global values and should be part of the global configuration.  We should stop placing values which will affect global behavior at an extension level because it creates a bad understanding of the level of influence of the parameter (something I see in the global configuration will affect the entire site, something I see at an extension level only affects things interacting with that extension).

2016-09-18 15:44 UTC, infograf768 commented
it would not be a global config but a com_languages option, therefore indeed at extension level.

2016-09-18 15:56 UTC, mbabker commented
How is it a com_languages option if it affects behavior in the entire application stack!?  It is not localized to that extension only.

2016-09-19 06:51 UTC, infograf768 commented
Ok, then let's make it an option in the back-end templates. Any Option there changes the display on the whole back-end (Colours for example). And showing icon/flags or Content Language **Title Native** (It should NOT be the Title) should be considered as a design choice...

You understand I still think that letting a Content Language having no image is what bothers me most.

2016-09-19 07:03 UTC, Bakual commented
The language switcher module now can take care of this change.
Dropdown:
![dropdown](https://cloud.githubusercontent.com/assets/1018684/18624422/e1ffe21a-7e47-11e6-8508-262f81b2fb03.PNG)
Inline:
![inline](https://cloud.githubusercontent.com/assets/1018684/18624425/e472ec72-7e47-11e6-89d0-1ce2c537f175.PNG)

2016-09-19 07:06 UTC, Bakual commented
> Ok, then let's make it an option in the back-end templates. Any Option there changes the display on the whole back-end (Colours for example). And showing icon/flags or Content Language Title Native (It should NOT be the Title) should be considered as a design choice...

I made that suggestion way back with my first PR and it was shot down, thus I went with this approach here...

> You understand I still think that letting a Content Language having no image is what bothers me most.

No, I don't really understand what the issue is with that approach. It actually adds flexibility.

2016-09-19 10:36 UTC, andrepereiradasilva commented
found some issues:
- a minor js issue. When you select image as "None" and save. Then edit again and try to change it again to a flag. The flag preview is not there.
- In modules menu assignments you use the langauge code, you use the SEF in all other views, so you should use the SEF here too.

![image](https://cloud.githubusercontent.com/assets/9630530/18629387/0769319a-7e5d-11e6-86c4-44e4fce4a42e.png)

As for the rest all seems to work fine.

2016-09-19 10:40 UTC, andrepereiradasilva commented
also i think it's needed to add the same SEF fallback in recent 3.7.x merge https://github.com/joomla/joomla-cms/pull/12042

2016-09-19 12:46 UTC, Bakual commented
@andrepereiradasilva Fixed the flag preview and using SEF in the module assignment. Had to add it to the MenusHelper first so I have it available in the layout.

2016-09-19 12:51 UTC, Bakual commented
> also i think it's needed to add the same SEF fallback in recent 3.7.x merge #12042

Indeed. Should be easy to do. But changing this PR to be based on 3.7.x means I have to fix some conflicts first. I'd rather first know if it is going to be accepted or not.

2016-09-19 13:26 UTC, andrepereiradasilva commented
I have tested this item :white_check_mark: successfully on 3127eda64834fe7d2371659cd53473451fee3111<br /><br />Workd as described.

Please don't forget to change also in 3.7.x branch com_wweblinks and when/if this merged.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-09-19 13:59 UTC, zero-24 approved these changes

2016-09-19 19:05 UTC, Bakual commented
Rebased to `3.7.x` and fixed the conflicts.

2016-09-20 06:39 UTC, infograf768 commented
👎 
What a great  improvement! I suggest to change the strings in mod_languages. 
I am sure you will like my proposal:

![screen shot 2016-09-20 at 08 37 06](https://cloud.githubusercontent.com/assets/869724/18659856/84032818-7f0d-11e6-842a-1a0929ffb603.png)

---------------
![screen shot 2016-09-20 at 08 37 29](https://cloud.githubusercontent.com/assets/869724/18659860/884cb006-7f0d-11e6-822c-a97a05676f6e.png)

2016-09-20 07:49 UTC, Bakual commented
@infograf768 I think we all know by now that you don't like this proposal....
Also your strings are not correct. For the dropdown it would use the flag if available. There is no "These may not be flags" as it will just be omitted if no flag is selected for that language. For the other mode it doesn't take the native name as fallback, it takes the SEF code.
If you want to change the strings (which I don't think is necessary) just append "... if available".

2016-09-20 11:51 UTC, andrepereiradasilva commented
issue on new feature on 3.7.x branch

![image](https://cloud.githubusercontent.com/assets/9630530/18669032/dc8a23ec-7f30-11e6-82e7-604362d51e71.png)

2016-09-20 13:43 UTC, Bakual commented
Thanks for the reminder. Done now:
![assoc](https://cloud.githubusercontent.com/assets/1018684/18672593/047f0224-7f49-11e6-90ec-1d06de3fe8c8.PNG)

2016-09-20 15:08 UTC, infograf768 commented
> I am sure you will like my proposal:

It was a joke, evidently. Just to show that this is not B/C.

2016-09-20 15:17 UTC, Bakual commented
>  Just to show that this is not B/C.

Sorry but that is just not true.
It is perfectly B/C as nothing changes during an update and even new installations behave exactly the same as today.
Only when the administrator **actively** edits the content language and removes the flag, then it will not show the flag anymore for that language. I'd say that is expected behavior and hasn't anything to do with B/C or not.

2016-09-20 18:19 UTC, andrepereiradasilva commented
@Bakual 3.7.x as also a new modal: the menus modal
this needs to be taken care too

![image](https://cloud.githubusercontent.com/assets/9630530/18683204/23f8d4b8-7f67-11e6-9828-2a1fbec2cc79.png)

2016-09-20 19:47 UTC, Bakual commented
@andrepereiradasilva Good find. Done as well.

2016-09-20 19:50 UTC, andrepereiradasilva commented
I have tested this item :white_check_mark: successfully on d250f247cc838c78c9ef89a10e2e600d3792287f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-09-22 18:11 UTC, Gitjk commented
>Since that is not always an appropriate thing some expressed the wish to hide those flags...

I just can't imagine any case where a language flag is not appropriate. Can somebody enlighten me by giving an example for which this PR makes sense?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-09-22 19:18 UTC, brianteeman commented
Look up what language  they speak in Quebec and you have your answer

2016-09-22 19:31 UTC, Bakual commented
> I just can't imagine any case where a language flag is not appropriate. Can somebody enlighten me by giving an example for which this PR makes sense?

I found this page quite an interesting read: http://www.flagsarenotlanguages.com/blog/
Personal example: I live in Switzerland, a country where there are four (!) official languages. You just can't use the Swiss flag to represent any of the language spoken here.

2016-09-22 20:14 UTC, Gitjk commented
Hmm, I've always looked at the flags as 'language flags', not 'country flags'! So it has always been fine for me to use the british flag for English language content (which is used by English speaking visitors of my site, including for example Britains and Americans, and the German flag for German language content. Site admins could use Quebec's flag if they wish to target citizens of Quebec only. But I doubt that many people associate their flag with French language content.

Link: [Quebec's flag](https://de.wikipedia.org/wiki/Flagge_von_Qu%C3%A9bec#/media/File:Flag_of_Quebec.svg "Quebec's flag")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-09-22 20:19 UTC, Bakual commented
Yeah, that is what is done today. But as said, some don't want that and in some cases (like Switzerland) it just doesn't work at all. That's why this PR wants to make the flags optional in backend as well (in frontend they are already).

2016-09-22 20:35 UTC, Gitjk commented
Ok, I understand that some German speaking Swiss citizens prefer to display 'DE' instead of the German flag :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/joomla-cms/12051</a>.</sub>

2016-10-09 12:22 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on d250f247cc838c78c9ef89a10e2e600d3792287f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/tracker/joomla-cms/12051</a>.</sub>

2016-10-09 12:23 UTC, brianteeman commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12051">issues.joomla.org/tracker/joomla-cms/12051</a>.</sub>

2016-10-11 19:46 UTC, merged