[installation] Clean assets rules in sql files
joomla/joomla-cms pull request #12069
Opened 2016-09-18 18:49 UTC by andrepereiradasilva

### Summary of Changes

This PR cleans all empty rules in the assets in tables in all installation files.

### Testing Instructions

1. Code review
2. Apply patch, delete configuration.php file, refresh page and install joomla
3. Check joomla install files and ACL works fine

### Documentation Changes Required

None.

2016-09-19 22:12 UTC, wilsonge commented
@sanderpotjer can you review this please?

2016-09-19 22:23 UTC, sanderpotjer commented
@wilsonge sure, will do that in detail tomorrow. But can see already one main issue: all "empty" action values are removed, so
```
(18, 1, 41, 86, 1, 'com_modules', 'com_modules', '{"core.admin":{"7":1},"core.manage":[],"core.create":[],"core.delete":[],"core.edit":[],"core.edit.state":[]}'),
```
becomes:
```
(18, 1, 41, 86, 1, 'com_modules', 'com_modules', '{"core.admin":{"7":1}}'),
```
This can cause performance issues on sites with a large nested assets table. From my tests (has been a while ago) it seems better to have the empty actions instead of no actions, so the system at leasts knows what actions are available and that no permission is set for an action. 

@andrepereiradasilva not sure if you have a specific reason for removing the empty values?

2016-09-19 22:28 UTC, ggppdk commented
Will this change trigger these notices ? :
https://github.com/joomla/joomla-cms/pull/10998

2016-09-19 22:45 UTC, andrepereiradasilva commented
i didn't remove any asset just cleaned the empty (nor allow/nor deny) rules.

2016-09-19 23:44 UTC, andrepereiradasilva commented
i made the changes essencially for sql readability and, without testing, i tought them maybe would be slightly faster.

anyway now i did some tests,
```php
$rules = array(
	'com_modules.module.1' => array(
		'old' => '{"core.admin":[],"core.manage":[],"core.create":[],"core.delete":[],"core.edit":[],"core.edit.state":[]}',
		'new' => '{}',
	),
	'com_content.article.1' => array(
		'old' => '{"core.delete":[],"core.edit":[],"core.edit.state":[]}',
		'new' => '{}',
	),
);

foreach ($rules as $assetName => $rule)
{
	!JDEBUG ?: JProfiler::getInstance('Application')->mark('<strong>Testing ' . $assetName . '</strong>');

	// Old method: With empty rules.
	JAccess::clearStatics();
	$query = $db->getQuery(true)->insert('#__assets')->columns('rules')->values($rules[$assetName]['old'])->where('name = ' . $db->q($assetName));
	$db->execute();
	$check = JAccess::check($user->id, 'core.edit', $assetName, true);

	// New method: No empty rules.
	JAccess::clearStatics();
	$query = $db->getQuery(true)->insert('#__assets')->columns('rules')->values($rules[$assetName]['new'])->where('name = ' . $db->q($assetName));
	$db->execute();
	$check = JAccess::check($user->id, 'core.edit', $assetName, true);
}
```

![image](https://cloud.githubusercontent.com/assets/9630530/18652541/28f6103a-7ecb-11e6-8660-8b9b61f263d8.png)


so it actually seems slightly faster.
So, if i'm not missing somthing, it seems to be more or less the same.

2016-11-04 13:33 UTC, sanderpotjer requested changes

2016-11-04 13:33 UTC, sanderpotjer commented on installation/sql/mysql/sample_blog.sql
>  (41, 1, 75, 76, 1, 'com_users.category.10', 'Uncategorised', ''),
Default rules should be `'{}'` instead of `''`

2016-11-04 13:33 UTC, sanderpotjer commented on installation/sql/mysql/sample_learn.sql
>  (169, 24, 335, 336, 2, 'com_users.category.77', 'Uncategorised', ''),
Default rules should be `'{}'` instead of `''`

2016-11-04 13:33 UTC, sanderpotjer commented on installation/sql/mysql/sample_testing.sql
>  (169, 24, 341, 342, 2, 'com_users.category.77', 'Uncategorised', ''),
Default rules should be `'{}'` instead of `''`

2016-11-04 13:33 UTC, sanderpotjer commented on installation/sql/postgresql/sample_learn.sql
>  (169,24,335,336,2,'com_users.category.77','Uncategorised',''),
Default rules should be `'{}'` instead of `''`

2016-11-04 13:33 UTC, sanderpotjer commented on installation/sql/postgresql/sample_testing.sql
>  (169,24,337,338,2,'com_users.category.77','Uncategorised',''),
Default rules should be `'{}'` instead of `''`

2016-11-04 13:42 UTC, sanderpotjer commented
@andrepereiradasilva apologises for the delay in my review! Felt of my radar...

I can't find any performance impact with no values set, so it looks like this has been addressed over the past years, which is good news!

The change looks good to me, just a couple very small changes for the com_users.category.77 asset. So thanks for cleaning up the assets data!

@wilsonge my recommendation would be to merge this pull request after the correction. This DOES NOT mean that the whole assets data is correct after that. I do see several inconsistencies, orphan assets and assets missing (like the asset entries for the modules). But is cleans the data up, and could make it easier to further correct the assets data. 

I'm happy to do another attempt to provide correct asset data, but think we need some coordination on that to prevent it ends up being outdated and causing merge conflicts a few months later.

2016-11-04 14:19 UTC, andrepereiradasilva commented
@sanderpotjer ok all `''` in assets changed to  `'{}'`

2016-11-04 14:39 UTC, sanderpotjer commented
I have tested this item :white_check_mark: successfully on 84abd145cfff2792f5915caaaa3fce8f4e22f957<br /><br />@andrepereiradasilva thanks for the improvements!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12069">issues.joomla.org/tracker/joomla-cms/12069</a>.</sub>

2016-11-04 14:40 UTC, andrepereiradasilva commented
thanks! let's hope this in reviewed/tested/merged faster so i don't need to fix conflicts ...

2016-11-04 14:47 UTC, mbabker commented
One question.  Are these values consistent with what the ACL API saves to the database?  If not, not that I want to discourage this from being merged, but I wouldn't have the base dataset and sample data create records that can't be generated by the API.

2016-11-04 14:56 UTC, andrepereiradasilva commented
@mbabker actually when you create a new article it generates an asset rule in the assets table with the component/category rules.

Example: `{"core.admin":{"7":1},"core.manage":{"6":1},"core.create":{"3":1},"core.delete":[],"core.edit":{"4":1},"core.edit.state":{"5":1},"core.edit.own":[]}`

I'm not sure, maybe @sanderpotjer knows better, but actually this seems an issue to me. Because you are hardcoding the component rules in the item asset, which means that if you change the parent (component) rules they will not propagate to the items,

2016-11-04 15:00 UTC, mbabker commented
If the API isn't traversing the tree to get the permissions from parent items then that would make sense.  It's honestly been a while though since I've done any type of digging into the ACL system though, so I have no idea what it's actually doing.

2016-11-04 15:04 UTC, andrepereiradasilva commented
@mbabker that i know of you create asset rules in 2 scenarios

1. Create a item (press save) you can't change permissions here (because the item is not yet saved ?) so it will inhrit parent rules (why hardcode?)
2. Edit an item that does not have asset in assets table and change permissions via Permission tab, this doesn't hardcode parent rules.

2016-11-04 15:04 UTC, sanderpotjer commented
That is indeed a bug! 

That is something that is probably caused by the introduction of the AJAX-saving of permissions. If a new articles is being created the actions in the actions should be similar to the "article" section of the `access.xml` from com_content, so `core.delete`, `core.edit` and `core.edit.state`.

So the default assets that are currently being saved are definitely not correct, but this is a separate issue.

In line with the pull request the default asset should be `{}` for any new asset, unless permissions are set.

2016-11-04 15:05 UTC, andrepereiradasilva commented
> In line with the pull request the default asset should be {} for any new asset, unless permissions are set.

That is what i though!

2016-11-04 15:42 UTC, euismod2336 commented
I have tested this item :white_check_mark: successfully on 84abd145cfff2792f5915caaaa3fce8f4e22f957<br /><br />ACL works fine after new install. No missing action values found in assets table.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12069">issues.joomla.org/tracker/joomla-cms/12069</a>.</sub>

2016-11-04 19:55 UTC, andrepereiradasilva commented
@brianteeman RTC ?

2016-11-04 21:07 UTC, zero-24 commented
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12069">issues.joomla.org/tracker/joomla-cms/12069</a>.</sub>

2016-11-05 09:21 UTC, merged