XML Codestyle for the file application.xml
joomla/joomla-cms pull request #12080
Opened 2016-09-19 17:38 UTC by zero-24

### Summary of Changes

XML Codestyle for the file `administrator/components/com_config/model/form/application.xml`

### Testing Instructions

- Apply this patch
- go to the global config
- confirm nothing is broken there

### Documentation Changes Required

none

2016-09-19 18:16 UTC, andrepereiradasilva requested changes
if we are doing a full cs review of the xml you should folllow the name, type, labeldescription order as code style rules.

2016-09-19 18:17 UTC, andrepereiradasilva commented on administrator/components/com_config/model/form/application.xml
> +		>
add a tab here

2016-09-19 18:17 UTC, yvesh commented
I have tested this item :white_check_mark: successfully on c3673d28abafe04d835070ef84377f5cd3b608f3<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12080">issues.joomla.org/joomla-cms/12080</a>.</sub>

2016-09-19 18:31 UTC, wojsmol requested changes
See https://joomla.github.io/coding-standards/?coding-standards/chapters/xml.md

2016-09-19 21:54 UTC, wojsmol commented
@zero-24 @andrepereiradasilva  Please see https://github.com/zero-24/joomla-cms/issues/17

2016-09-20 07:01 UTC, zero-24 commented
Looks good just one smal comment in that PR. Thanks @wojsmol :+1:

2016-09-20 11:34 UTC, andrepereiradasilva commented on administrator/components/com_config/model/form/application.xml
> +				<action
why are the  `action` idented with an extra tab? the `option` are not...

2016-09-20 11:34 UTC, andrepereiradasilva requested changes

2016-09-20 13:20 UTC, wojsmol commented on administrator/components/com_config/model/form/application.xml
> +				<action
fixed in https://github.com/joomla/joomla-cms/pull/12080/commits/351db4e4cbe3ca21087213febe9c39a5c0ab8992

2016-09-20 13:21 UTC, zero-24 commented
Thanks @wojsmol

2016-09-20 13:38 UTC, andrepereiradasilva approved these changes

2016-09-20 13:38 UTC, andrepereiradasilva commented
I have tested this item :white_check_mark: successfully on 351db4e4cbe3ca21087213febe9c39a5c0ab8992<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12080">issues.joomla.org/joomla-cms/12080</a>.</sub>

2016-09-20 13:52 UTC, wojsmol commented
cc @JoomliC Please do a code reciew :smile:

2016-10-25 10:18 UTC, zero-24 commented
this is now moved to be against 3.7.x

2016-10-31 12:17 UTC, closed without merging