[JInstaller::parseXMLInstallFile] Parse also metadata section of manifest files
joomla/joomla-cms pull request #12081
Opened 2016-09-19 20:27 UTC by andrepereiradasilva

### Summary of Changes

This PR allow JInstaller::parseXMLInstallFile to also parse the metadata section in xml files (ex: xml language files).

### Testing Instructions

Code review.

- add this to your isis/index.php and refresh the page you will see the array with that xml file.
```php
print_r(JInstaller::parseXMLInstallFile(JPATH_SITE . '/language/en-GB/install.xml'));
```
- Now add this to the end of the en-GB `install.xml` file:
```xml
	[...]
	</files>
	<metadata>
		<name>English (en-GB)</name>
		<tag>en-GB</tag>
		<rtl>0</rtl>
		<locale>en_GB.utf8, en_GB.UTF-8, en_GB, eng_GB, en, english, english-uk, uk, gbr, britain, england, great britain, uk, united kingdom, united-kingdom</locale>
		<firstDay>0</firstDay>
		<weekEnd>0,6</weekEnd>
	</metadata>
	<params />
</extension>
```
- Refresh page.  You will see the metadata section IS NOT there.
- Apply patch.
- Refresh page.  You will see the metadata section IS there.
- Install any extension, language to confirm all installs fine.

### Documentation Changes Required

None.

2016-09-19 20:48 UTC, zero-24 commented on libraries/cms/installer/installer.php
> +			foreach ($xml->metadata->children() as $xmlTag)
can we have a clean line before the `foreach`?

2016-09-19 20:48 UTC, zero-24 requested changes

2016-09-19 20:49 UTC, zero-24 commented
just one smal one ;)

2016-09-20 07:00 UTC, zero-24 approved these changes

2016-09-20 10:25 UTC, zero-24 commented
i'm not sure. But the code gives me the same with and without the patch and anytime without the metadata? I'm confused but maybe i miss something?

2016-09-20 10:53 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on 3b810e0950373ba50d745586cb2d89780529e004<br /><br />works. it was a wrong setup problem here ;) Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12081">issues.joomla.org/joomla-cms/12081</a>.</sub>

2017-05-21 23:41 UTC, mbabker commented
This PR needs a new owner or it will have to be closed as abandoned.

2017-05-22 09:51 UTC, zero-24 commented
The bot is was your friend this day @mbabker ;)

2017-06-22 09:09 UTC, franz-wohlkoenig commented
If this PR get no Response, it will be closed at 23th July 2017.

2017-07-23 08:24 UTC, closed without merging

2017-07-23 08:24 UTC, franz-wohlkoenig commented
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12081">issues.joomla.org/tracker/joomla-cms/12081</a>.</sub>