Performance optimizations #1
joomla/joomla-cms pull request #12171
Opened 2016-09-25 16:18 UTC by frankmayer

Those are some performance optimizations for the libraries/cms folder. If you like those, there are plenty more where those came from.
Since I don't know if you guys are open to these kinds of PR's. I am awaiting the developments of my open PR's before I do more.

2016-09-25 16:35 UTC, zero-24 approved these changes
looks good from here. Thanks!

2016-09-25 16:38 UTC, zero-24 requested changes
Please have a look at: https://travis-ci.org/joomla/joomla-cms/jobs/162592381 It looks like travis is not happy.

2016-09-25 16:39 UTC, zero-24 commented
Travis error is:

```
1) JComponentRouterLegacyTest::testParse
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'option' => 'com_test'
-    42 => 'test-test'
+    42 => 'test:test'
 )
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/cms/component/router/JComponentRouterLegacyTest.php:130
2) JRouterTest::testDecodeSegments with data set #3 (array('42-test', 'testing-this-method'), array('42:test', 'testing:this-method'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => '42:test'
-    1 => 'testing:this-method'
+    1 => 'testing:this:method'
 )
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/cms/router/JRouterTest.php:872
```

https://travis-ci.org/joomla/joomla-cms/jobs/162592381

2016-09-25 16:43 UTC, frankmayer commented
Yes, I noticed... :) Will fix errors.

2016-09-25 16:46 UTC, zero-24 approved these changes

2016-09-25 18:12 UTC, frankmayer commented
on it...

2016-09-25 20:21 UTC, frankmayer commented
That about sums this PR up. No new commits, as far as optimizations are concerned.
Let me know if you need me to change anything.

2016-09-25 21:37 UTC, photodude commented on libraries/cms/application/site.php
> +		return parent::getMenu($name, $options);
I can't find the reference at the moment, but I remember reading something along the lines that storing a function return in a variable and returning that variable in your method is less error prone and faster than directly returning an evaluated function in your method. 

Technically they both work, and off the top of my head I don't think we have a standard on which way to write code.

2016-09-25 22:37 UTC, frankmayer commented on libraries/cms/application/site.php
> +		return parent::getMenu($name, $options);
In my opinion, such kind of variables should not be introduced. 

They serve no practical purpose. And they do actually introduce another unnecessary step in our minds, when we humans read the code - and also when the machine aka the interpreter/compiler reads and processes it. 

Why introduce something whose only purpose is to be returned on the next line, without any further processing?

As for the compiler, I would think modern PHP compilers do this step automatically internally, but they have to do it nevertheless, using cpu and memory, so why not leave it out in the first place?

Just my 2 cents :smile:

2016-09-25 22:47 UTC, mbabker commented on libraries/cms/application/site.php
> +		return parent::getMenu($name, $options);
In terms of code readability I've been leaning toward less creation/assignment of variables that aren't needed than "explicit" structures like this one.  There isn't a standard since both are valid syntax, but unless there is a majorly strong argument (like engine performance) for one over the other, I'd lean toward the readability argument and I find it easier to read one line instead of two code lines and the blank line in the middle.

2016-09-25 23:06 UTC, frankmayer commented on libraries/cms/application/site.php
> +		return parent::getMenu($name, $options);
BTW, there are some interesting numbers [here](http://obrown.io/php/2015/12/19/php-performance-inlining.html) on inlining and redundant variables. These numbers depict different implementations in loops, but you can see the difference, which is even bigger in 7.0 (than even the latest 5.6), when using redundant variables.
Of course, it's not like Joomla is looping several thousands of times through these functions to create some content, but why not save a few bytes on memory and also a few cpu cycles? We can only benefit from it. ... + it's easier to read...

2016-09-25 23:20 UTC, frankmayer commented on libraries/cms/application/site.php
> +		return parent::getMenu($name, $options);
@photodude I think you were possibly referring to this q&a...

2016-09-26 01:01 UTC, photodude commented on libraries/cms/application/site.php
> +		return parent::getMenu($name, $options);
That might have been it, but maybe not. I just checked some of my book references to see if it was in one of those books, and it seems the general consensus in the examples leans towards the inlining the return.

The argument of code readability is a good one. 

It might be one of those specific circumstances things. Like ternary operators are ok in php, unless there is large objects in the variables being passed, then ternary operators in php suck up time and memory due to the copy operation they preform on the variables before evaluating. 

In anycase I can't seem to find the reference at the moment, so Code Readability wins me over.

2016-09-26 09:28 UTC, sovainfo commented
Would you mind motivating the other types of performance improvement as well?

2016-09-26 10:59 UTC, frankmayer commented
@sovainfo I'll gladly point out my motivation for this. 

Generally, all of the improvements are based on modern PHP best practices.

Most of them are dropping function calls in favor of using cheaper (in terms of cpu usage and memory) implementations.

Often, readability is also improved as a welcome side-effect of this.

Other things like the optimized if-conditions, are moving the cheaper conditions to the beginning of the conditions, in order to not invoke more expensive operations, if not necessary.

Of course there are some situations, where optimization is not possible, because of the necessity of maintaining PHP 5.3 compatibility. (Are there really people still running 5.3???)
IMHO, Joomla 4, whenever it comes out, should radically drop the complete 5.* line of PHP and have a minimum of PHP 7.0. Because 5.6 is going into 'security fixes only' mode on 1.1.2017 - [see here](http://php.net/supported-versions.php)

That should about sum it up.

As you have probably noticed, this PR is only focusing on the files in libraries/cms + it's subfolders, as I though it was a good starting point. If you guys are OK with those changes, I'll gladly expand the implementation of that kind of optimizations and cleanup to the whole project.

2016-09-26 11:30 UTC, sovainfo commented
Thanks, was wondering about the optimization of if-conditions. 

The costs of the condition shouldn't be the only factor. Sounds like you want to ignore the likely hood of the conditions, together they should determine the order. 
This assumes it was given thought in the first place.

2016-09-26 12:16 UTC, frankmayer commented
@sovainfo the cost actually isn't the only factor. For that reason, not all if-conditions were touched. I hand-picked only those, were it would not change their semantics. Did you notice some inconsistency after those changes?

2016-09-26 13:05 UTC, photodude commented
Surprisingly almost 14% of submitted user statistics were for PHP 5.3
I personally question how many of those were submitted by developers doing testing
https://developer.joomla.org/about/stats.html

2016-09-26 13:46 UTC, frankmayer commented
@photodude yes, that's a valid question. I too think the developer tests are tinkering with real statistics. I wonder if there should be some kind of 'isDeveloper' switch, which developers could set, in order to not have unwanted side effects like this.

2016-09-26 14:56 UTC, Bakual commented
Personally I think almost no dev tests with 5.3. Devs are the ones with the PHP7 servers :smile: 
But users really **are** still using PHP 5.3. If you ask why, it's because they don't care about underlying systems and just trust their hosters. And thos don't want to risk breaking sites by upgrading the PHP version.

2016-09-26 15:02 UTC, mbabker commented
Part of it is we didn't want to make a distinction between dev and production environments in the statistics.  It honestly doesn't matter to us either (well, that's my opinion anyway, YMMV).  That's in part why you get the nag message versus default enabled (every fresh install I do I immediately hit never on it).  We have provisions in the stats collection making it possible to report things that nobody will be using in production (i.e. our 4.0 branch doesn't get rejected, if you're compiling against PHP master which has a 7.2 version number right now it's accepted, etc.) so that too can skew things because it favors either ambitious or curious folks who want to try things out on bleeding edge technology and that can also be used as an indicator to see what folks are doing.

2016-09-27 03:15 UTC, photodude commented on libraries/cms/application/site.php
> +		return parent::getMenu($name, $options);
@frankmayer I think part of what I remember was something like this comment on the PHP manual
http://php.net/manual/en/function.pg-connect.php#82117
considering that it's 8 years old I'm not sure if it still applies in more modern php

2016-09-27 13:33 UTC, frankmayer commented
@Bakual I don't know about the devs testing with 5.3, but if the number really depicts users still using 5.3, then that's one more reason to require PHP 7.0 for Joomla 4, because if Joomla 4 would be released in 2017, then PHP 5.6 would already be in security only-fixes mode for about a year until its final EOL end of 2018.

This is Joomla's chance to help hosters get rid of old versions and also be able to use the newer technologies and speed provided by the PHP 7 series.

2016-09-27 15:27 UTC, Bakual commented
I don't think it's reasonable to raise the minimum PHP requirement for Joomla 4 to PHP 7, but PHP 5,.6 for sure. If it is released next year that is.
By the same logic you should raise the minimum requirement to PHP 7.1, because security support for PHP 7.0 actually runs out before PHP 5.6 does :smile: 

But it is not up to me to make that decision.

2016-09-27 15:43 UTC, photodude commented
@frankmayer In the past (and currently) there is a dynamic between what hosters are supporting (influenced by what's available and supported in standard distros) vs what developers want. Personally, I would love to see J3.7 drop php5.3 but that likely won't happen. On the other hand J4 is being developed with a php5.6+ design. Sadly most hosters are still hesitant to fully support php 7 even when they offer the option to use php7 (when problems arise they typically tell people to go back to using php5.6, even some developers of extensions tell customers that)

Balancing the hoster support, 3rd party extensions, and platform needs is an unpleasant challenge. IMO php5.6 is a good compromize for J4.

2016-09-27 20:26 UTC, matrikular commented on libraries/cms/application/cms.php
> +		if (null === $this->config->get('session'))
If there there is no reason other than taste, I would propose to flip the expression condition to, in this case; `if ($this->config->get('session') === null)` or, for line 584; `if ($registry !== null)`

2016-09-28 09:01 UTC, frankmayer commented on libraries/cms/application/cms.php
> +		if (null === $this->config->get('session'))
In the past I was writing it that way, but recently I discovered I find it easier to read it this way.
It reads like `null is something`, which personally, I find easier to read and process than `something is null`.
However, if the consensus is against that style, I'll happily flip those cases.

2016-09-28 09:16 UTC, Bakual commented on libraries/cms/application/cms.php
> +		if (null === $this->config->get('session'))
I don't think it is explicitely set in the coding guidelines but it sure is the way we usually write it.  So if you don't mind, please flip it.

2016-09-28 09:22 UTC, frankmayer commented on libraries/cms/application/site.php
> +		return parent::getMenu($name, $options);
@photodude I see what you mean. The case of the comment is partially true (at least with PHP7 which I just tested). In PHP7, it will die() even inline. However, if the returned value is not false, it will return a bool, which automatically will be `true`.
So this is actually a case where caution is advised and those cases should be dealt with, the old way.

2016-09-28 12:00 UTC, matrikular commented on libraries/cms/menu/menu.php
> +			return $this->_items[$id];
@frankmayer was it a conscious decision to "remove" the reference at this point? Maybe someone can shed some light on the old implementation, too.

2016-09-28 18:16 UTC, frankmayer commented on libraries/cms/menu/menu.php
> +			return $this->_items[$id];
Yes if I remember well, it was.
I just checked again and I must have figured that in this case an object would be returned, so I removed the reference, since objects are returned by reference anyways (or in other words, a pointer to the object is returned). 

I remember also seeing other remnants from the PHP4 days like this, but I din't touch these, unless they were part of a wanted change, like the one in question.

2016-09-28 18:16 UTC, frankmayer commented on libraries/cms/application/cms.php
> +		if (null === $this->config->get('session'))
Ok, will do.

2016-09-28 18:33 UTC, frankmayer commented on libraries/cms/application/cms.php
> +		if (null === $this->config->get('session'))
Done.

2016-09-28 20:11 UTC, matrikular commented on libraries/cms/menu/menu.php
> +			return $this->_items[$id];
Thank you for the clarification.

2016-09-28 20:48 UTC, matrikular commented on libraries/cms/helper/media.php
> +			if (false !== stripos($xss_check, '<' . $tag . ' ') || false !== stripos($xss_check, '<' . $tag . '>'))
@frankmayer regarding the flipping (my ocd) this might be changed to ...
`if (stripos($xss_check, '<' . $tag . ' ') !== false [...]`
... as well, if you may.

2016-09-28 20:52 UTC, matrikular commented on libraries/cms/schema/changeitem/postgresql.php
> +					for ($i = 7, $iMax = count($wordArray); $i < $iMax; $i++)
@frankmayer good find.

2016-09-28 21:02 UTC, matrikular commented
From what I could grasp by reviewing the code alone, all looks good.

There are some areas, like database queries without a try / catch block neither before or after the optimisation, but I guess that alone might be a thing for different PR. Anonther thing that caught my attention is [this passage](https://github.com/frankmayer/joomla-cms/blob/062ef22f7608f82d7fe47cfe9f6b20ea13d0e1e1/libraries/cms/application/site.php#L607-L660 "JApplicationSite::initialiseApp") from JApplicationSite::initialiseApp().

Good work, thanks!

2016-09-28 21:04 UTC, frankmayer commented on libraries/cms/helper/media.php
> +			if (false !== stripos($xss_check, '<' . $tag . ' ') || false !== stripos($xss_check, '<' . $tag . '>'))
@matrikular whoops! sorry, those ones slipped through... will do

2016-09-28 21:18 UTC, frankmayer commented
@matrikular You're very welcome! I always wanted to give back to the Joomla project, and decided to give it a try by doing this. And as I mentioned earlier, if you (as the steering users) are OK with those kinds of changes I am open to expand the scope of optimizations to the whole project (minus the vendor imports... as I learned :smile: )

2016-09-28 22:42 UTC, chrisdavenport commented on libraries/cms/html/tabs.php
> +			$opt['useStorage'] = (isset($params['useCookie']) && !$params['useCookie']);
This doesn't look right.  I think you need to do
`$opt['useStorage'] = !(isset($params['useCookie']) && !$params['useCookie']);`

2016-09-28 22:42 UTC, chrisdavenport commented on libraries/cms/installer/adapter/component.php
> +		if (0 !== strpos($element, 'com_'))
I can see what you're getting at, but it looks really ugly (to me).  Is the performance gain really worth it?

2016-09-28 22:42 UTC, chrisdavenport commented on libraries/cms/module/helper.php
> +		if ($result === null && 0 === strpos($name, 'mod_'))
Same here.  Maybe `strpos($name, 'mod_') === 0` will make it look prettier. ;-)

2016-09-28 22:48 UTC, photodude commented on libraries/cms/application/cms.php
> +		if (null === $this->config->get('session'))
Yoda conditionals always look odd to me too.  Maybe it's all of the Left-to-right reading/writing in English that influences that oddness.

2016-09-28 23:03 UTC, frankmayer commented on libraries/cms/html/tabs.php
> +			$opt['useStorage'] = (isset($params['useCookie']) && !$params['useCookie']);
Good catch!! Yes. my bad. will fix. Thanks

2016-09-28 23:09 UTC, frankmayer commented on libraries/cms/installer/adapter/component.php
> +		if (0 !== strpos($element, 'com_'))
That's a big discussion, but IMHO why not do it? It doesn't cost anything.
On the contrary, any gain no matter how big or small will add to the pile and help reduce load on the machine it's running on. What do you think?

2016-09-28 23:10 UTC, frankmayer commented on libraries/cms/module/helper.php
> +		if ($result === null && 0 === strpos($name, 'mod_'))
Yes it will ;)

2016-10-04 02:37 UTC, andrepereiradasilva commented on libraries/cms/helper/route.php
> +						if ($item->language != '*' || !isset(static::$lookup[$language][$view][$item->query['id']]))
missed one !== here

2016-10-04 02:37 UTC, andrepereiradasilva commented on libraries/cms/plugin/plugin.php
> +			if ($dbProperty->isPrivate() === false && $this->db === null)
not sure of this, but couldn't we do it like this
```php
if ($this->db === null && $reflection->getProperty('db')->isPrivate() === false)
```

2016-10-04 02:37 UTC, andrepereiradasilva commented on libraries/cms/plugin/plugin.php
> +			if ($appProperty->isPrivate() === false && $this->app === null)
not sure of this, but couldn't we do it like this
```php
if ($this->app === null && $reflection->getProperty('app')->isPrivate() === false)
```

2016-10-04 02:37 UTC, andrepereiradasilva commented on libraries/cms/search/helper.php
> +			$hits = (int) ($db->loadResult());
can't we remove the parenthisis here?

2016-10-04 02:56 UTC, frankmayer commented on libraries/cms/helper/route.php
> +						if ($item->language != '*' || !isset(static::$lookup[$language][$view][$item->query['id']]))
Missed a lot actually... not sure if I was so eager to include that many changes in that first PR.

2016-10-04 03:40 UTC, frankmayer commented on libraries/cms/plugin/plugin.php
> +			if ($appProperty->isPrivate() === false && $this->app === null)
Should be no problem.

2016-10-04 11:53 UTC, andrepereiradasilva commented
I have tested this item :white_check_mark: successfully on 171f66b0ee535c1103a5e7ee94b58ed8d8082e60<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12171">issues.joomla.org/tracker/joomla-cms/12171</a>.</sub>

2016-12-12 21:58 UTC, frankmayer commented
Fixed some conflicts that had occurred in the meantime. It's essentially ready to be merged, when the team finds the time and PR is OK.

2016-12-12 23:13 UTC, andrepereiradasilva commented
I have tested this item :white_check_mark: successfully on 171f66b0ee535c1103a5e7ee94b58ed8d8082e60<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12171">issues.joomla.org/tracker/joomla-cms/12171</a>.</sub>

2016-12-18 13:06 UTC, andrepereiradasilva commented
conflicts

2016-12-18 13:07 UTC, frankmayer commented
@andrepereiradasilva Yes, but after the referenced open PR's are closed. Don't want to do this three times ;)

2016-12-18 13:09 UTC, andrepereiradasilva commented
right i see

2017-01-06 15:35 UTC, frankmayer commented
Edited initial post to show which sub-PRs still have to go through, in order to make this one easier to digest. 
It would be great if the initial big batch PRs of mine could make it into alpha2. Thanks!

2017-06-13 18:50 UTC, andrepereiradasilva reviewed
some minor comments

2017-06-13 18:50 UTC, andrepereiradasilva commented on libraries/cms/helper/media.php
>  					&& strpos($entry, '.html') === false && strpos($entry, '.php') === false)
IMO `is_file` should be the last check sine it makes I/O call to the filesystem.

2017-06-13 18:50 UTC, andrepereiradasilva commented on libraries/cms/html/tabs.php
> +
please remvoe this extra line

2017-06-13 18:50 UTC, andrepereiradasilva commented on libraries/cms/installer/installer.php
> +		if ($name !== 'extension' && $name !== 'metafile')
cs: add a return before the if statement

2017-06-13 18:50 UTC, andrepereiradasilva commented on libraries/cms/plugin/plugin.php
> +			if ($reflection->getProperty('app')->isPrivate() === false && $this->app === null)
change the order of the contitions?

2017-06-13 18:50 UTC, andrepereiradasilva commented on libraries/cms/plugin/plugin.php
> +			if ($reflection->getProperty('db')->isPrivate() === false && $this->db === null)
change the order of the contitions?

2017-06-13 19:09 UTC, frankmayer commented on libraries/cms/helper/media.php
>  					&& strpos($entry, '.html') === false && strpos($entry, '.php') === false)
Yes, missed that one. Nice catch.

2017-06-13 19:12 UTC, frankmayer commented on libraries/cms/plugin/plugin.php
> +			if ($reflection->getProperty('app')->isPrivate() === false && $this->app === null)
Yep

2017-06-13 19:28 UTC, andrepereiradasilva commented
I have tested this item :white_check_mark: successfully on 171f66b0ee535c1103a5e7ee94b58ed8d8082e60<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12171">issues.joomla.org/tracker/joomla-cms/12171</a>.</sub>

2017-06-13 19:43 UTC, peteruoi commented
Just an idea...
If there is a considerable performance in joomla paging loading maybe a metric could be done with and without all these performance prs and if is enough it could be advertises in joomla 3.8 release campaign?
thanks frankmayer for your work!

2017-06-13 19:58 UTC, frankmayer commented
@peteruoi that is an interesting idea. However I assume that any improvements from all the PRs will vary a lot with mileage. Unfortunately I haven't got the time to set this up and do the tests.
Oh, and a lot of things made it already into 3.7.

Another situation  where I would hope to see some measurable optimization would be, if the indexer performance PR would be merged (see https://github.com/joomla/joomla-cms/pull/13511).
This would of course mostly be measureable with initial (or re-) indexing of a lot of index-able content. 
But I also would like to think that on changing of content, it might work a little bit faster.

2017-06-13 20:01 UTC, frankmayer commented on libraries/cms/html/menu.php
> +				'list.attr' => ($attribs === null ? 'class="inputbox" size="1"' : $attribs),
Yes, that's just the right place ;)

2017-06-13 20:03 UTC, frankmayer commented on libraries/cms/html/menu.php
> +				'list.attr' => ($attribs === null ? 'class="inputbox" size="1"' : $attribs),
Got more? Shall I wait?

2017-06-13 20:04 UTC, Quy commented on libraries/cms/html/menu.php
> +				'list.attr' => ($attribs === null ? 'class="inputbox" size="1"' : $attribs),
Also align `=`

2017-06-13 20:04 UTC, Quy commented on libraries/cms/pagination/pagination.php
> +		$layoutId = ($layoutId === null) ? 'joomla.pagination.links' : $layoutId;
Remove parentheses and more below.

2017-06-13 20:05 UTC, Quy commented on libraries/cms/table/contenthistory.php
> +					$object->$subName = (is_int($subValue) || is_bool($subValue) || $subValue === null) ? (string) $subValue : $subValue;
Remove parentheses

2017-06-13 20:05 UTC, Quy commented on libraries/cms/table/contenthistory.php
> +				$object->$name = (is_int($value) || is_bool($value) || $value === null) ? (string) $value : $value;
Remove parentheses

2017-06-13 20:06 UTC, Quy commented on libraries/cms/html/menu.php
> +				'list.attr' => ($attribs === null ? 'class="inputbox" size="1"' : $attribs),
More reported and I am done for now. :wink:

2017-06-13 20:16 UTC, frankmayer commented on libraries/cms/html/menu.php
> +				'list.attr' => ($attribs === null ? 'class="inputbox" size="1"' : $attribs),
Thanks. Done a few more things I found along the way.

2017-06-13 21:12 UTC, frankmayer commented
Bump @andrepereiradasilva & @Quy Problem solved. Pls test (review changes) to go for RTC

2017-06-13 21:33 UTC, andrepereiradasilva commented
I have tested this item :white_check_mark: successfully on 171f66b0ee535c1103a5e7ee94b58ed8d8082e60<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12171">issues.joomla.org/tracker/joomla-cms/12171</a>.</sub>

2017-06-13 21:44 UTC, andrepereiradasilva commented
@peteruoi when we have levels like Joomla server side performance things are not like 30% Faster in all Pages. Is really relative to each change and to the amount of scenarios that change apllies to
For instance in the past made several changes that boosted performance only in multilingual sites.

Imo the most important performance improvements are the ones done to the critical page that apllies to all pages and also most used parts (com_content, jroute, etc). 
That said general improvements like this set of prs also contribute as a whole.

2017-06-13 21:58 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 171f66b0ee535c1103a5e7ee94b58ed8d8082e60<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12171">issues.joomla.org/tracker/joomla-cms/12171</a>.</sub>

2017-06-14 04:05 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-06-14 12:45 UTC, peteruoi commented
@andrepereiradasilva Even with a 5% percent general it will be awesome news for advertisment for 3.8 campaign. And no one forbids us to say 5% to 20% (at miltilingual for example).
I think it's a pity that the optimization you awesome fellows do and make joomla and the internet faster is not recognized enough :). 
This metric of course it cannot be pr dependent but before release 3.7 vs 3.8 tests and if they are favourite for us we advertise ;)

2017-06-15 06:47 UTC, merged

2017-06-15 08:54 UTC, frankmayer commented
Hooray, this really big chunk was finally merged! Thank you all for your comments and efforts in testing