Performance 3 (layouts)
joomla/joomla-cms pull request #12225
Opened 2016-09-30 11:53 UTC by frankmayer

Performance (and a bit of cleanup) Batch #3

The changes in this batch are all in files under `layouts`.
This PR modifies code to be a bit more performant and also does some cleanup.

I have mostly done work on low hanging fruit. There are still other ways of improving, but whose involve more deep research in the code and probably more drastic changes in order to be implemented.

2016-09-30 14:17 UTC, wilsonge requested changes
This looks largely fine to me. A few things that I'd like to see changed first tho because I think that code readability is largely preferable to the micro-optimisations that you have done here...

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/content/info_block/block.php
> +			<?php if (!empty($displayData['item']->author ) && $displayData['params']->get('show_author')) : ?>
Can we revert this one please. It might be a micro-optimisation but to me from a readability perspective it makes far more sense to check the parameter for display before we check whether the property is empty or not

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/content/info_block/block.php
> +			<?php if (!empty($displayData['item']->parent_slug) && $displayData['params']->get('show_parent_category')) : ?>
Ditto with the check here. I'd rather check the params first from a readability perspective

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/content/info_block/category.php
> +				<?php if ($displayData['item']->catslug && $displayData['params']->get('link_category')) : ?>
Ditto with the check here. I'd rather check the params first from a readability perspective

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/content/info_block/parent_category.php
> +				<?php if (!empty($displayData['item']->parent_slug) && $displayData['params']->get('link_parent_category')) : ?>
Ditto with the check here. I'd rather check the params first from a readability perspective

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/html/formbehavior/chosen.php
> +			jQuery('" . $selector . "').chosen(" . $options_str . ');
This feels super counterintuitive. If we are going to do strings with single quotes then do all the strings in single quotes and use double quote for the jQuery selector. Or just revert this part of the string :/

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/modal/main.php
> +	$script[] = '       });';
Same here - having a bunch of lines of strings with double quotes and then one line of single quotes is pretty counter intuitive!

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/modal/main.php
> +	$script[] = '       if (iframeHeight > maxModalBodyHeight){;';
Same here - having a bunch of lines of strings with double quotes and then one line of single quotes is pretty counter intuitive!

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/modal/main.php
> +	$script[] = '       if (modalHeight > maxModalHeight){;';
Same here - having a bunch of lines of strings with double quotes and then one line of single quotes is pretty counter intuitive!

2016-09-30 14:17 UTC, wilsonge commented on layouts/joomla/modal/main.php
> +$script[] = '});';
Same here - having a bunch of lines of strings with double quotes and then one line of single quotes is pretty counter intuitive!

2016-09-30 14:31 UTC, frankmayer commented on layouts/joomla/content/info_block/block.php
> +			<?php if (!empty($displayData['item']->author ) && $displayData['params']->get('show_author')) : ?>
OK, will change those checks back to the previous way. 
Though I believe that even from a readability standpoint it does make sense. Why check if we want to show something that is not existent?

2016-09-30 14:32 UTC, frankmayer commented on layouts/joomla/html/formbehavior/chosen.php
> +			jQuery('" . $selector . "').chosen(" . $options_str . ');
You're right. Will see what fits best and act appropriately.

2016-09-30 14:42 UTC, mbabker commented on layouts/joomla/content/info_block/block.php
> +			<?php if (!empty($displayData['item']->author ) && $displayData['params']->get('show_author')) : ?>
Different opinions, different workflows.  99% of the time my workflow is checking the parameter before checking if the data exists.

2016-09-30 15:02 UTC, frankmayer commented on layouts/joomla/content/info_block/block.php
> +			<?php if (!empty($displayData['item']->author ) && $displayData['params']->get('show_author')) : ?>
OK :smile: , as I said, I will change those specfic cases in all PR's

2016-09-30 15:37 UTC, wilsonge approved these changes

2016-09-30 15:37 UTC, wilsonge commented
OK. I'll leave this for 3.6.4 just to be safe and as we are in RC anyhow. But this looks fine to me. RTC

2016-09-30 20:09 UTC, frankmayer commented on layouts/joomla/content/info_block/block.php
> +			<?php if (!empty($displayData['item']->author ) && $displayData['params']->get('show_author')) : ?>
While looking over some of the code for other stuff, I noticed that there are a few of those types of conditions out there (where the existence of a value is checked before the parameter to output it). I guess that whoever wrote them, had the same thing in mind as me.
Maybe it's worth giving it a little more thought?
If you think about it, it does make sense to not check for outputting something that is not there...

2016-09-30 20:14 UTC, mbabker commented on layouts/joomla/content/info_block/block.php
> +			<?php if (!empty($displayData['item']->author ) && $displayData['params']->get('show_author')) : ?>
I definitely see where you're going with it, but I don't think we're going to come up with a "this is the preferred way" answer.  I think I've always written code where it checks the parameter then checks for the data, it's just one of those habits.  Same as those who prefer Yoda arguments over the other direction.

Honestly, even if you look throughout much of the project's code repositories, you can somewhat extrapolate who wrote what sections.  One of the devs I work with on the issue tracker prefers Yoda conditionals and shorter line lengths whereas I write them the other way and push the limits of our 150 character line length restrictions.  Both pass the guidelines and are functional, but there isn't anything specifying do it only one way.

2016-10-17 09:23 UTC, brianteeman commented
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

2016-10-17 19:58 UTC, frankmayer commented on layouts/joomla/content/info_block/block.php
> +			<?php if (!empty($displayData['item']->author ) && $displayData['params']->get('show_author')) : ?>
@mbabker sorry, I missed your answer somehow. 
As you might :grin: have noticed, my OCD is with optimizing stuff. 
And in most of these marked cases (and other like those throughout Joomla's codebase), the condition to check if we want to show some parameter data, is 5 to 10 times or even more expensive, than to check first, if it makes any sense to do said check at all (aka: check if there is any data to use). to begin with. And by the looks of it, most of those conditions are often part of a loop, which adds up to even even more wasted cpu power.
So, my argument for that, is "It's not just the __'preferred way'__. It's the __much__ less expensive way.
And while there are arguments that say, the user won't notice it, there are two counterarguments for that:
1. Under extreme load, optimized code most probably will make a difference.
2. When Joomla has several tens of thousands installations, the energy footprint for non-optimized code is huge. That's why it's important to try to apply Green Computing aka Sustainable Software Engineering to our coding styles/principles or whatever one might call it. It might be that Green Computing is not that widely spread, accepted or thought about as "FILL THIS WITH YOUR FAVORITE 
BUZZWORD FLOATING AROUND THE WEB AT THIS TIME", but why not do it anyways and sleep a tiny bit better at night :smile: ... 
.

2016-10-17 20:13 UTC, andrepereiradasilva commented on layouts/joomla/pagination/links.php
>  if ($currentPage >= $step)
just ?
```php
if ($currentPage >= $step)
{
	$range = ceil($currentPage / $step);

	if ($currentPage % $step === 0)
	{
		$range += 1;
	}
}
```

2016-10-17 20:13 UTC, andrepereiradasilva commented on layouts/joomla/content/info_block/author.php
>  	<?php $author = '<span itemprop="name">' . $author . '</span>'; ?>
just?
```php
<?php $author = '<span itemprop="name">' . ($displayData['item']->created_by_alias ?: $displayData['item']->author) . '</span>'; ?>
```

2016-10-17 20:13 UTC, andrepereiradasilva commented
oh this is already RTC forget it

2016-10-18 17:36 UTC, merged