JLayoutFile wrong type hint
joomla/joomla-cms pull request #12231
Opened 2016-09-30 17:23 UTC by izharaazmi

### Summary of Changes
Change type hint to string from object.

### Testing Instructions
None. No code changes.

### Documentation Changes Required
Update argument type for JLayoutFile::sublayout() method

2016-09-30 20:33 UTC, zero-24 requested changes
Can you add a space before the new comment? This way PHPCS should be fine on that

2016-09-30 20:40 UTC, izharaazmi commented
@zero-24  Thanks. And sorry for that silly one. 😊 Fixed.

2016-09-30 20:58 UTC, zero-24 approved these changes

2016-10-17 09:23 UTC, brianteeman commented
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

2016-10-18 17:37 UTC, merged