[j3.7] New Feature Contact editor-xtd plugin
joomla/joomla-cms pull request #12252
Opened 2016-10-02 12:19 UTC by brianteeman

This is a new editor-xtd plugin to allow you to easily insert a link to a contact when using the wysiwyg editor. It works exactly the same way as the insrt article editor-xtd plugin

### Testing Instructions
Easy test - install Joomla using https://github.com/brianteeman/joomla-cms/archive/contact-editorxtd.zip

Slightly harder test - Apply the patch using the com_patchtester. discover to find the plugin and then install AND enable it

![editor](https://cloud.githubusercontent.com/assets/1296369/19020522/d19376b6-88a2-11e6-829f-bea604d2b4bf.gif)

[Note] this editor plugin is available for all wysiwyg editor areas except for com_banners where it will not work as the editor is only for admin display.

2016-10-02 13:34 UTC, zero-24 requested changes

2016-10-02 13:34 UTC, zero-24 commented on administrator/language/en-GB/en-GB.plg_editors-xtd_contact.sys.ini
> +
Can you remove the double clean lines here?

2016-10-02 13:34 UTC, zero-24 commented on plugins/editors-xtd/contact/contact.php
> +	 * @since  3.1
`__DEPLOY_VERSION__`

2016-10-02 13:34 UTC, zero-24 commented on plugins/editors-xtd/contact/contact.php
> +	 * @return array A four element array of (contact_id, contact_title, category_id, object)
That looks wrong to me? We return 6 parameters?

2016-10-02 13:34 UTC, zero-24 commented on plugins/editors-xtd/contact/contact.php
> +	 */
@since  `__DEPLOY_VERSION__` is missing.

2016-10-02 13:34 UTC, zero-24 commented on plugins/editors-xtd/contact/contact.php
> +		$doc->addScriptDeclaration($js);
Why not use `JFactory::getDocument()->addScriptDeclaration($js);`? and remove the `$doc = JFactory::getDocument();` line

2016-10-02 13:34 UTC, zero-24 commented on plugins/editors-xtd/contact/contact.xml
> +		<filename plugin="contact">contact.php</filename>
I'm not sure here. As we have allready a plugin with the same deklaration: https://github.com/joomla/joomla-cms/blob/staging/plugins/content/contact/contact.xml#L13

The reason I'm not sure is that i don't know where this information is used

2016-10-02 13:34 UTC, zero-24 commented on plugins/editors-xtd/contact/contact.php
> +		$button = new JObject;
hmm as `JObject` is deprecated i guess we can use here `$button = new stdClass();`?

2016-10-02 13:35 UTC, zero-24 commented
Also the changes in the com_admin Script PHP is missing. ;)

2016-10-02 13:44 UTC, brianteeman commented on plugins/editors-xtd/contact/contact.php
> +	 * @return array A four element array of (contact_id, contact_title, category_id, object)
Direct copy/paste from the article plugin

2016-10-02 13:47 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_editors-xtd_contact.sys.ini
> +
Direct copy/paste from the article plugin but done:)

2016-10-02 13:49 UTC, brianteeman commented on plugins/editors-xtd/contact/contact.php
> +		$doc->addScriptDeclaration($js);
No idea - direct copy from the article plugin

2016-10-02 13:52 UTC, brianteeman commented on plugins/editors-xtd/contact/contact.xml
> +		<filename plugin="contact">contact.php</filename>
Pretty sure its not an issue as the plugin-type/folder is different. For example We have two content and two contacts

2016-10-02 13:52 UTC, brianteeman commented on plugins/editors-xtd/contact/contact.php
> +	 */
Done

2016-10-02 13:53 UTC, brianteeman commented on plugins/editors-xtd/contact/contact.php
> +		$button = new JObject;
No idea - direct copy from the article plugin

2016-10-02 13:53 UTC, brianteeman commented
admin script changes done

2016-10-02 13:55 UTC, brianteeman commented on plugins/editors-xtd/contact/contact.php
> +	 * @since  3.1
Done

2016-10-02 14:01 UTC, zero-24 commented
Thanks. I can have a look into the source and prepare fixes there that can be aplyed here too. :+1:

2016-10-02 14:02 UTC, brianteeman commented
Yeah - Not a fan of changing the code just here.

2016-10-02 17:17 UTC, zero-24 commented
please see: https://github.com/joomla/joomla-cms/pull/12260 do you want to do it yourself or do you want me to direct correct it?

2016-10-02 17:56 UTC, brianteeman commented
In five minutes I stop work till Wednesday so if you could do it then it
can move forward while I am offline

2016-10-02 21:51 UTC, zero-24 commented on plugins/editors-xtd/contact/contact.xml
> +		<filename plugin="contact">contact.php</filename>
ooops yes you are correct.

2016-10-02 21:52 UTC, zero-24 approved these changes

2016-10-02 22:02 UTC, zero-24 commented
done

2016-10-02 22:37 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on 0622cb79213af5b7e7edeba5c0887ff088579147<br /><br />:+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12252">issues.joomla.org/joomla-cms/12252</a>.</sub>

2016-10-03 07:09 UTC, infograf768 commented
When I made the new editors-xtd menu plugin, I was told to use the prefix `PLG_EDITORS-XTD_MENU_` instead of `PLG_MENU_` to get:
`$button->text    = JText::_('PLG_EDITORS-XTD_MENU_BUTTON_MENU');`

I suggest you do the same for this one.
Instead of `PLG_CONTACT_BUTTON_CONTACT="Contact"`
use
`PLG__EDITORS-XTD_CONTACT_BUTTON_CONTACT="Contact"

2016-10-03 08:11 UTC, brianteeman commented
It is EXACTLY the same as the article plugin

2016-10-03 13:22 UTC, infograf768 commented
that is what i also said at the time. the reply i got was that we should not reiterate the same error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12252">issues.joomla.org/joomla-cms/12252</a>.</sub>

2016-10-03 13:29 UTC, infograf768 commented
see https://github.com/joomla/joomla-cms/pull/11721#r75651403
in fact it was your comment...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12252">issues.joomla.org/joomla-cms/12252</a>.</sub>

2016-10-03 13:46 UTC, zero-24 commented
done @infograf768 @brianteeman

2016-10-03 13:47 UTC, zero-24 commented
Can you test that one @infograf768 ?

2016-10-03 13:51 UTC, zero-24 commented
With the last 3 commit i have just fixed the update sql's

2016-10-04 06:49 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 8191430d4e900e31a9fcf73232ebcca97303fe19<br /><br />Looks OK here.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12252">issues.joomla.org/tracker/joomla-cms/12252</a>.</sub>

2016-10-04 12:20 UTC, ghazal commented
I have tested this item :white_check_mark: successfully on 8191430d4e900e31a9fcf73232ebcca97303fe19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12252">issues.joomla.org/tracker/joomla-cms/12252</a>.</sub>

2016-10-04 12:29 UTC, zero-24 commented
RTC. Thanks!

@rdeutz new stuff for 3.7 :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12252">issues.joomla.org/tracker/joomla-cms/12252</a>.</sub>

2016-10-04 12:39 UTC, merged

2016-10-04 12:44 UTC, brianteeman commented
Thanks