Remove deprecated function
joomla/joomla-cms pull request #12296
Opened 2016-10-03 22:06 UTC by wilsonge

### Summary of Changes
`JViewLegacy::assignRef` has been deprecated for a long long time. This is the last usage of it in the CMS. This paves the way for it's removal in J4 with #12263

### Testing Instructions
Ensure the newsfeed view continues to work as before

### Documentation Changes Required
n/a

2016-10-03 22:09 UTC, andrepereiradasilva requested changes

2016-10-03 22:09 UTC, andrepereiradasilva commented on components/com_newsfeeds/views/newsfeed/view.html.php
> +		$this->state $state;
missing something here ...

2016-10-03 22:09 UTC, andrepereiradasilva commented on components/com_newsfeeds/views/newsfeed/view.html.php
> +		$this->user $user;
missing something here ...

2016-10-03 22:29 UTC, wilsonge commented on components/com_newsfeeds/views/newsfeed/view.html.php
> +		$this->user $user;
Thank you! That will teach me to do two coding tasks on different projects at the same time when I'm tired xD

2016-10-03 22:41 UTC, andrepereiradasilva commented
I have tested this item :white_check_mark: successfully on 41b083fd1be3b7e7f57bd67de98272dedbeb3292<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12296">issues.joomla.org/tracker/joomla-cms/12296</a>.</sub>

2016-10-04 08:28 UTC, zero-24 commented
@wilsonge please have a look into: https://github.com/wilsonge/joomla-cms/pull/29

2016-10-04 09:20 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on 41b083fd1be3b7e7f57bd67de98272dedbeb3292<br /><br />on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12296">issues.joomla.org/tracker/joomla-cms/12296</a>.</sub>

2016-10-04 09:21 UTC, zero-24 commented
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12296">issues.joomla.org/tracker/joomla-cms/12296</a>.</sub>

2016-10-04 09:21 UTC, wilsonge commented
Thankyou for your PR :) I still think it's needed - just not here :)

2016-10-17 09:27 UTC, brianteeman commented
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

2016-10-18 17:39 UTC, merged