3.7 Improve Cache Controller
joomla/joomla-cms pull request #12312
Opened 2016-10-04 18:14 UTC by csthomas

Pull Request for Issue #12133 and other optimizations.

### Summary of Changes
* Deprecate `get` and `store` methods in JCacheController
* Remove `setLifeTime`, `setCaching` from JCacheController because `__call()` method can call it directly on JCache instance.
* Replace operator == to === and etc.
* Do not store if lock can not be locked and loop was performed:
```php
if ($locktest->locked === false && $locktest->locklooped === true)
```
* Deprecate `start` and `end` methods in output controller - probably nobody use it
* Add `get` and `store` method to `JCacheControllerOutput` which is the same as deprecated method `get` and `store` in `JCacheController`. 
* In subclasses of `JCacheController` I did code review on `get` method.
  - move `unlock()` method before unserialize(...)
  - other optimizations

### Testing Instructions

Joomla should work as before.
Code review.

### Documentation Changes Required
None.

2016-12-10 13:24 UTC, csthomas commented
Can I ask you @mbabker for a review?

2016-12-10 16:03 UTC, mbabker requested changes
Looks fine, one PHPCS issue.

2016-12-10 16:03 UTC, mbabker commented on libraries/joomla/cache/controller/callback.php
> +		else {
PHPCS issue.

2016-12-10 16:09 UTC, mbabker approved these changes

2016-12-10 16:18 UTC, csthomas commented
Thanks Michael.

Now I have to wait for 2 successful tests:)

2017-01-11 20:50 UTC, franz-wohlkoenig commented
@csthomas Enable Cache and test if J works as before?

2017-01-11 20:52 UTC, csthomas commented
Yes, be sure that cache works before patch

2017-01-12 08:16 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 87f42d59c69e092b8b45d5bd0589fa5116a4c90e<br /><br />Tested on Articles, Blog, List, Contact, Feed, Search.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12312">issues.joomla.org/tracker/joomla-cms/12312</a>.</sub>

2017-01-27 04:21 UTC, JoshuaLewis commented
I have tested this item :white_check_mark: successfully on 87f42d59c69e092b8b45d5bd0589fa5116a4c90e<br /><br />Logged in, logged out, created article, viewed list, viewed article, changed site settings on frontend, ect. Seems to work great on every view I tested. Successfully tested this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12312">issues.joomla.org/tracker/joomla-cms/12312</a>.</sub>

2017-01-27 18:05 UTC, jeckodevelopment commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12312">issues.joomla.org/tracker/joomla-cms/12312</a>.</sub>

2017-01-27 18:17 UTC, merged