[com_finder] - cast to char before use LIKE operator  on datetime/tim…
joomla/joomla-cms pull request #12348
Opened 2016-10-08 09:11 UTC by alikon

fix for standard SQL
### Summary of Changes
A timestamp/datetime field CANNOT be used with LIKE operator we need to cast to char before in standard SQL
### Testing Instructions
Smart Search: Indexed Content search field   with date work as before

2016-10-08 14:36 UTC, mbabker requested changes

2016-10-08 14:36 UTC, mbabker commented on administrator/components/com_finder/models/index.php
> +				$orSearchSql .= ' OR CAST((' . $db->quoteName('l.indexdate') . ') AS CHAR(19)) LIKE  ' . $search;
Use `$query->castAsChar()` please.  I've also looked and realized we don't have a proper implementation of that for the MySQL drivers (the default implementation just returns the value).

2016-10-11 06:41 UTC, alikon commented on administrator/components/com_finder/models/index.php
> +				$orSearchSql .= ' OR CAST((' . $db->quoteName('l.indexdate') . ') AS CHAR(19)) LIKE  ' . $search;
i've noticed that too, matter for another PR

2016-10-15 06:14 UTC, alikon commented
used `$query->castAsChar()` as requested

2016-10-15 07:34 UTC, alikon commented
@mbabker  i've done something for the CAST implementation can you review #12417 ?

2017-01-12 09:34 UTC, franz-wohlkoenig commented
@alikon ist this PR for testing or waiting on Answer?

2017-01-12 09:50 UTC, alikon commented
Is ready to test thanks

On 12 Jan 2017 10:34 am, "Franz Wohlkönig" <notifications@github.com> wrote:

> @alikon <https://github.com/alikon> ist this PR for testing or waiting on
> Answer?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/12348#issuecomment-272116519>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AALFsTUi5eglrGStHuebm2wp8GJ_udomks5rRfOXgaJpZM4KRqzm>
> .
>

2017-01-12 10:11 UTC, franz-wohlkoenig commented
Searched for "12. 3. 1991" as Part of an Article-Titel in Backend, which is found with and without Patch. 
Searched for same at Frontend which is not found with and without Patch.

2017-01-12 11:30 UTC, alikon commented
@franz-wohlkoenig  this PR is only for backend

2017-01-12 12:23 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 98cf6195f7d3a0a9be953a3c869ea9deef670aa9<br /><br />Searched for "12. 3. 1991" as Part of an Article-Titel in Backend, which is found with and without Patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12348">issues.joomla.org/tracker/joomla-cms/12348</a>.</sub>

2017-02-02 23:58 UTC, csthomas commented
I have tested this item :white_check_mark: successfully on 98cf6195f7d3a0a9be953a3c869ea9deef670aa9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12348">issues.joomla.org/tracker/joomla-cms/12348</a>.</sub>

2017-02-04 17:46 UTC, merged