Use the JHtml::_ function instead of calling functions directly.
joomla/joomla-cms pull request #12546
Opened 2016-10-25 09:03 UTC by okonomiyaki3000

Pull Request for Issue # .

### Summary of Changes
Instead of calling JHtml static functions directly, call them with the underscore function like `JHtml::_('functionname');` so that it's possible to override them. 

### Testing Instructions
The changed files could potentially affect many pages (for example, any list page with a disabled ordering column). You should see no difference before and after applying the patch. 

### Documentation Changes Required
No but, if there is some documentation for developers, it would be a good idea for that documentation to make it clear that `JHtml` static functions should not be called directly but invoked through the `_` function.

2016-10-25 11:57 UTC, mbabker requested changes
Please revert the changes in `JHtmlTest`.  We want to explicitly only test the actual functions there, not that the loader is able to resolve to the correct function as well (we have tests for that part specifically already).

2016-10-25 11:58 UTC, mbabker commented on libraries/cms/html/html.php
> +	 * @see     JHtml::_('stylesheet', )
Can you revert this line too (and if there are any others in doc blocks, those as well)?

2016-11-21 05:52 UTC, okonomiyaki3000 commented
@mbabker tests have been reverted, please check.

2016-11-21 13:20 UTC, mbabker approved these changes

2017-01-12 13:48 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 3973dfb517b6e49fa1d58d009d55fb3b4d62a914<br /><br />Tested on Menu Item `Category List` and hidden `Show Author`. Page display same woth or without PR-<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12546">issues.joomla.org/tracker/joomla-cms/12546</a>.</sub>

2017-01-12 13:49 UTC, dgt41 commented
@okonomiyaki3000 can you update your PR, it's out of sync, Thanks

2017-01-16 08:29 UTC, okonomiyaki3000 commented
Should be in sync now.

2017-02-05 13:42 UTC, ThomasFinnern commented
I have tested this item :white_check_mark: successfully on ae82474492857da4bcfc465777890f27767cd3e6<br /><br />Please check whether the operations performed meet the requirements for this test (newbee on testing)

On new installation PHP7.1.1 and Joomla! 3.7.0-beta2 dev [ Amani ] 2-February-2017 18:53 GMT: 
- Added 5 contacts. Looked at the conact list. Reodered the list, changed the status and reordered it by status
- Applied the patch and did the same steps. No visal changes seen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12546">issues.joomla.org/tracker/joomla-cms/12546</a>.</sub>

2017-02-05 19:07 UTC, zero-24 commented
I have just fixed the conflicts. -> RTC

2017-02-05 22:26 UTC, merged