Use strict mode whenever possible.
joomla/joomla-cms pull request #12604
Opened 2016-10-28 08:28 UTC by okonomiyaki3000

Pull Request for Issue # .

### Summary of Changes
Javscript functions are set to work in strict mode. 
JQuery 'ready' function changed to concise format.
Minify some files that hadn't been minified before.
Other minor cleanup.

### Testing Instructions
These files are used by many admin pages including the global config, various listing and edit pages, permission forms, etc. A few of these files are only used by the `hathor` template. 

Most are included via some `JHtml` function. You can usually find which function by searching for the js filename. You can then find where that is used by searching joomla for 'classSuffix.functionName'. 

### Documentation Changes Required
Nope but it would be great if all future javascript development was required to be in strict mode. Also, if we had some guidelines on minification, that would be great too.

2016-10-28 08:50 UTC, okonomiyaki3000 commented
I believe this is a bad test. It requires that `sendTestMail` be defined on the global scope but there is no reason for that. This is a function that is used only as a handler for a single `click` event. Why make it global?

2016-10-28 08:54 UTC, okonomiyaki3000 commented
But anyway, I'll change it back for now.

2016-10-28 10:55 UTC, zero-24 commented
@yvesh can you take a look into the failing Drone Test?

2016-10-29 12:46 UTC, yvesh commented
@zero-24 @okonomiyaki3000 when we want to use the strict mode, the javascript tests need to be adjusted to that. This should be done **before** merging that PR. 

@okonomiyaki3000 Can you look into fixing the JavaScript tests (we have a documentation on them at docs.joomla.org too)? Ping me when you need any help with that.

2016-10-31 01:00 UTC, okonomiyaki3000 commented
@yvesh I'm not familiar with drone tests and I don't know how to run them locally. Could you point me to more info about that? I couldn't find it on docs.joomla.org.

2016-10-31 01:02 UTC, dgt41 commented
Try https://docs.joomla.org/Running_JavaScript_Tests_for_the_Joomla_CMS

2016-10-31 01:08 UTC, dgrammatiko requested changes

2016-10-31 01:08 UTC, dgt41 commented on media/system/js/sendtestmail-uncompressed.js
`$ = jQuery;`  adding this should fix the tests

2016-10-31 02:26 UTC, okonomiyaki3000 commented on media/system/js/sendtestmail-uncompressed.js
Thanks. It seems I forgot to put this in when I took the function back out of the ready function. Isn't it silly that the tests require this to be in the global scope though? It's kind of nonsense to me.

2016-10-31 05:18 UTC, okonomiyaki3000 commented
So there were basically two problems, one as @dgt41 mentioned and another which required improving the test. The `sendPermissions` function was relying on `this` to supply the id and value it needs. That's a bit risky in the best situations but here it was especially silly since `this` is a select in normal practice but it's `window` during the test. So I changed the test to work a little bit more like a real situation and used `event.target` instead `this`. No more errors.

2017-05-21 23:54 UTC, mbabker commented
What's the status here?

2017-06-22 11:12 UTC, franz-wohlkoenig commented
If this PR get no Response, it will be closed at 23th July 2017.

2017-07-23 08:26 UTC, closed without merging

2017-07-23 08:26 UTC, franz-wohlkoenig commented
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12604">issues.joomla.org/tracker/joomla-cms/12604</a>.</sub>