Replace unnecessary double quotes in administrator #3
joomla/joomla-cms pull request #13295
Opened 2016-12-20 00:16 UTC by frankmayer

### Summary of Changes
- Replace unnecessary double quotes

The changes in this PR should be fairly easy to review. In hope that this will get merged quickly so further work can be done without conflicting with other PRs. ;)

### Testing Instructions

None, should not change behavior

### Documentation Changes Required

None.

2016-12-20 00:24 UTC, andrepereiradasilva approved these changes

2016-12-20 00:24 UTC, andrepereiradasilva commented on administrator/modules/mod_menu/menu.php
> +			echo '<ul ' . $id . ' ' . $class . ">\n";
hum why don't we use PHP_EOL const here ...

2016-12-20 00:24 UTC, andrepereiradasilva commented on administrator/modules/mod_menu/menu.php
> +			echo '<a' . $linkClass . ' ' . $dataToggle . " href=\"" . $this->_current->link . "\" target=\"" . $this->_current->target . "\" >"
why not use it in href and target too and remove the slashes?

2016-12-20 00:24 UTC, andrepereiradasilva commented on administrator/modules/mod_menu/menu.php
> +			echo '<a' . $linkClass . ' ' . $dataToggle . " href=\"" . $this->_current->link . "\">" . $this->_current->title . $dropdownCaret . '</a>';
same as above

2016-12-20 00:24 UTC, andrepereiradasilva commented on administrator/templates/hathor/html/com_postinstall/messages/default.php
> +	'moduleclass_sfx' => ' list-striped');
cs: please move the `);` to the next line.

2016-12-20 00:24 UTC, andrepereiradasilva commented on administrator/templates/isis/error.php
> +<body class="admin <?php echo $option . ' view-' . $view . ' layout-' . $layout . ' task-' . $task . ' ';?>" data-spy="scroll" data-target=".subhead" data-offset="87">
the last space sounds really useful :)

2016-12-20 00:38 UTC, frankmayer commented on administrator/modules/mod_menu/menu.php
> +			echo '<ul ' . $id . ' ' . $class . ">\n";
Depending on OS PHP_EOL sends \n (linux) or \r\n (windows) so unfortunately it's not doable...

2016-12-20 00:39 UTC, frankmayer commented on administrator/modules/mod_menu/menu.php
> +			echo '<a' . $linkClass . ' ' . $dataToggle . " href=\"" . $this->_current->link . "\" target=\"" . $this->_current->target . "\" >"
Wanted to leave that for a rainy day... Want PR's to go through as smoothly as possible ;)

2016-12-20 00:39 UTC, frankmayer commented on administrator/modules/mod_menu/menu.php
> +			echo '<a' . $linkClass . ' ' . $dataToggle . " href=\"" . $this->_current->link . "\">" . $this->_current->title . $dropdownCaret . '</a>';
as above ;)

2016-12-20 00:41 UTC, andrepereiradasilva commented on administrator/modules/mod_menu/menu.php
> +			echo '<ul ' . $id . ' ' . $class . ">\n";
ok

2016-12-20 00:42 UTC, andrepereiradasilva commented on administrator/modules/mod_menu/menu.php
> +			echo '<a' . $linkClass . ' ' . $dataToggle . " href=\"" . $this->_current->link . "\" target=\"" . $this->_current->target . "\" >"
well in this case i think this should be part of this PR. just saying ...

2016-12-20 00:45 UTC, frankmayer commented on administrator/modules/mod_menu/menu.php
> +			echo '<a' . $linkClass . ' ' . $dataToggle . " href=\"" . $this->_current->link . "\" target=\"" . $this->_current->target . "\" >"
Well, ok then.. will do those as well... :)

2016-12-20 01:11 UTC, andrepereiradasilva approved these changes

2016-12-24 10:02 UTC, shur requested changes

2016-12-24 10:02 UTC, shur commented on administrator/includes/toolbar.php
> +		$dhtml = '<button data-toggle="modal" data-target="# ' . $targetModalId . '" class="btn btn-small">
`data-target="# '` - this is not correct, you add an extra space here.

2016-12-24 10:02 UTC, shur commented on administrator/modules/mod_menu/menu.php
> +			echo '<a' . $linkClass . ' ' . $dataToggle . ' href="' . $this->_current->link . '" target="' . $this->_current->target . '" >'
this extra space is not needed 
Please replase `'" >'` to `'">'` as it is done below.

2016-12-24 10:08 UTC, frankmayer commented on administrator/includes/toolbar.php
> +		$dhtml = '<button data-toggle="modal" data-target="# ' . $targetModalId . '" class="btn btn-small">
Whoops! Yes ;)

2016-12-24 10:12 UTC, frankmayer commented on administrator/modules/mod_menu/menu.php
> +			echo '<a' . $linkClass . ' ' . $dataToggle . ' href="' . $this->_current->link . '" target="' . $this->_current->target . '" >'
OK, done.

2016-12-24 10:28 UTC, shur commented
I have tested this item :white_check_mark: successfully on a9cf8ed5f15342f09199dd2a8ff07a522fb48564<br /><br />Now is good!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13295">issues.joomla.org/tracker/joomla-cms/13295</a>.</sub>

2016-12-24 10:37 UTC, shur approved these changes

2016-12-24 12:36 UTC, andrepereiradasilva approved these changes

2016-12-25 20:51 UTC, merged

2016-12-27 08:33 UTC, shur commented
@frankmayer 
**You must see this:** 
https://www.facebook.com/groups/joomlanospam/permalink/10153990199490997/

2016-12-27 11:59 UTC, frankmayer commented
@shur Thank you for the link :) It's very nice to get a personal acknowledgement. But, lets not forget the community effort involved, to get any PR finally merged.

So, thank you team Joomla, for constructive criticism, testing and improving my commits (and me).