Do not include the SQL query in the Exception message
joomla/joomla-cms pull request #13356
Opened 2016-12-23 17:02 UTC by mbabker

### Summary of Changes

Including the SQL query in the Exception message is a mild information disclosure in that it displays to the user the failed SQL query and exposes information about the database structure.  This PR removes the query from the Exception message retaining only the engine's error message.

The `JDatabaseExceptionExecuting` object has a `$query` property (accessible via `getQuery()`) that contains the failed SQL query.  For debugging purposes, if you need access to the failed query, you should extract it from the Exception's property versus relying on the message.

### Testing Instructions

Create a query failure that triggers the error page.  Pre-patch, the error message will contain the query.  Post-patch, it will not.

### Documentation Changes Required

Note that the query is not exposed as part of the Exception message any longer, developers must read it from the `JDatabaseExceptionExecuting` object's `$query` property.

2016-12-23 20:18 UTC, fastslack commented
@test I used a cli script to test this and works as spected using MySQL database.

Executed script before patch:
```
$ ./Issue13356
Unknown column 'noexists' in 'where clause' SQL=SELECT * FROM #__users WHERE noexists = 0
```

Executed script after patch:
```
$ ./Issue13356
Unknown column 'noexists' in 'where clause'
```

Script used here: https://github.com/fastslack/joomla-cli-tools/blob/master/JoomlaTests/issue-13356/Issue13356

2016-12-23 23:14 UTC, bembelimen commented
I have tested this item :white_check_mark: successfully on 65ea823804a0a769654ad73264fa619cd1846fc8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13356">issues.joomla.org/tracker/joomla-cms/13356</a>.</sub>

2016-12-24 06:35 UTC, alikon requested changes

2016-12-24 06:35 UTC, alikon commented on libraries/joomla/database/driver/postgresql.php
> +	protected function getErrorMessage()
as we have removed the `$query` param from `getErrorMessage()`
we don't need to pass when calling that function see

- https://github.com/mbabker/joomla-cms/blob/65ea823804a0a769654ad73264fa619cd1846fc8/libraries/joomla/database/driver/postgresql.php#L754
 
- https://github.com/mbabker/joomla-cms/blob/65ea823804a0a769654ad73264fa619cd1846fc8/libraries/joomla/database/driver/postgresql.php#L739

2016-12-24 06:44 UTC, alikon commented
same as #10949

2016-12-30 13:26 UTC, mbabker commented
Didn't remember that was there.  Either way the change needs to be merged in sooner than later.  I don't know why there's a bad test on that other PR because there is no code change to duplicate the error output.

2016-12-30 16:54 UTC, ralain commented
I have tested this item :white_check_mark: successfully on 5386864dc73a9447f7ff987112ef35c929b450c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13356">issues.joomla.org/tracker/joomla-cms/13356</a>.</sub>

2016-12-30 16:58 UTC, alikon commented
fully agree, i close mine in favour of this one.

p.s.
the bad test on the other one should be  because of the tested query was executed twice

2016-12-30 16:58 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 5386864dc73a9447f7ff987112ef35c929b450c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13356">issues.joomla.org/tracker/joomla-cms/13356</a>.</sub>

2016-12-30 17:02 UTC, jeckodevelopment commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13356">issues.joomla.org/tracker/joomla-cms/13356</a>.</sub>

2017-01-02 00:57 UTC, merged