[com_fields] Custom Fields Media Field if class is empty still class is shown as attribute
joomla/joomla-cms pull request #13462
Opened 2017-01-03 22:03 UTC by zero-24

Pull Request for Issue #13400 

### Summary of Changes

Don't let the class tag alone without content

### Testing Instructions

Create an media field and don´t fill the image class field.

There is an empty class attribute shown in the Source code
![image](https://cloud.githubusercontent.com/assets/828371/21544078/641d240a-cdcc-11e6-93ec-d3e7974cf5e2.png)

Apply the patch and make sure there is no class tag anymore but if you set a class it comes back :smile: 

### Documentation Changes Required

none

2017-01-04 06:42 UTC, laoneo commented
Can we put this one on hold till #13319 is merged. Then this one needs to be redone in the plugin itself. Thanks.

2017-01-10 20:58 UTC, zero-24 commented
@coolcat-creations @laoneo i have updated the PR after the changes in #13319 please review and test here.

2017-01-11 07:28 UTC, laoneo commented
Please use `$fieldParams->get('image_class')` to get the image class. The inheritance from the plugin works.

2017-01-11 07:45 UTC, zero-24 commented
done @laoneo

2017-01-11 08:15 UTC, laoneo commented
Just saw that getting the directory is also wrong, can you change it to `$fieldParams->get('directory', '/')` as well?

2017-01-11 08:21 UTC, zero-24 commented
fixed.

2017-01-12 18:21 UTC, laoneo requested changes
Produces invalid HTML

2017-01-12 18:21 UTC, laoneo commented on plugins/fields/media/tmpl/media.php
>  }
You have a not needed  " at the end of a tag and a space is needed

    $buffer .= '<img src="' . $path . '" ' . $class . '/>';

2017-01-12 18:21 UTC, laoneo commented on plugins/fields/imagelist/tmpl/imagelist.php
>  }
You have a not needed  " at the end of a tag and a space is needed

    . '/' . $path . '" ' . $class . '/>';

2017-01-14 18:03 UTC, franz-wohlkoenig commented
I have tested this item :red_circle: unsuccessfully on f04480476a60a815f6f3b7c79cfd153028aa2af0<br /><br />Before Patch:
```
<dd class="field-entry " id="field-entry-8">
	<span class="field-label">Media: </span>
	<span class="field-value"><img src="/Joomla/images/joomla_black.png" class=""/></span>
</dd>
```
After Patch:
```
<dd class="field-entry " id="field-entry-8">
	<span class="field-label">Media: </span>
	<span class="field-value"><img src="/Joomla/images/joomla_black.png""/></span>
</dd>
</dl>
```
There ist a " to much at `joomla_black.png""`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13462">issues.joomla.org/tracker/joomla-cms/13462</a>.</sub>

2017-01-17 14:32 UTC, zero-24 commented
@laoneo @franz-wohlkoenig the last commits should do it thanks!.

2017-01-17 15:09 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 14c96a662802c96738b0659e0578b883d12c4e0f<br /><br />After PR empty Class is gone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13462">issues.joomla.org/tracker/joomla-cms/13462</a>.</sub>

2017-01-17 15:10 UTC, laoneo requested changes

2017-01-17 15:10 UTC, laoneo commented on plugins/fields/imagelist/tmpl/imagelist.php
>  }
There is still a space here missing.

2017-01-17 15:10 UTC, laoneo commented on plugins/fields/media/tmpl/media.php
>  }
There is still a space here missing.

2017-01-17 15:50 UTC, laoneo approved these changes

2017-01-17 15:51 UTC, laoneo commented on plugins/fields/imagelist/tmpl/imagelist.php
>  }
Fixed with c1f1a4b

2017-01-17 15:51 UTC, laoneo commented on plugins/fields/media/tmpl/media.php
>  }
Fixed with 2a49a4f.

2017-01-17 15:51 UTC, laoneo commented
I have tested this item :white_check_mark: successfully on c1f1a4bdd8a444203422a9345e10ba5fad8b4947<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13462">issues.joomla.org/tracker/joomla-cms/13462</a>.</sub>

2017-01-17 15:52 UTC, laoneo commented
@franz-wohlkoenig please test it with a class and without. For me it worked.

2017-01-26 07:49 UTC, laoneo commented
@franz-wohlkoenig can you retest this one, that we can get it in?

2017-01-26 09:02 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on fd069e6e9832d6f0c5938d0de9baed2ee7dc54af<br /><br />With and without a class (i.e. `span4 offset1`) class isn't shown in source code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13462">issues.joomla.org/tracker/joomla-cms/13462</a>.</sub>

2017-01-26 09:27 UTC, laoneo commented
Ready for commit then, thanks.

2017-01-26 22:33 UTC, jeckodevelopment commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13462">issues.joomla.org/tracker/joomla-cms/13462</a>.</sub>

2017-01-27 18:21 UTC, merged