Normalize finder tables across 3 db systems and add default values
joomla/joomla-cms pull request #13517
Opened 2017-01-08 16:23 UTC by andrepereiradasilva

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/13509 (part) and probably other issues relating finder tables in more strict db systems (which in joomla 4.0 mysql will be also).

### Summary of Changes

Normalize the `#__finder_*` table across db systems.
Only tested in mysql.
@waader please check mssql
@alikon please also check postgresql and mssql.

### Testing Instructions

1. SQL code review 
2. Test update: Apply patch, manually run the sql query for your Db system, confirm db table, confirm all fine
3. Test install: apply patch, delete configuration.php do a normal install, confirm db table, confirm all fine

### Documentation Changes Required

None.

2017-01-08 18:27 UTC, waader commented
Should the alter statements for mssql no be formed like in 3.1.0.sql so we would have for example

ALTER TABLE [#__finder_filters] ADD  DEFAULT ('') FOR [title];

instead of

ALTER TABLE `#__finder_filters` MODIFY `title` varchar(255) NOT NULL DEFAULT '';

2017-01-08 19:55 UTC, andrepereiradasilva commented
don't know the best query in mssql 
if you confirm me that `ALTER TABLE [#__finder_filters] ADD DEFAULT '' FOR [title];` work on mssql i can change.

But there are also cases like removing `NULL`, setting `NOT NULL`and adding `DEFAULT ''` in the same field.
See https://github.com/joomla/joomla-cms/pull/13517/files#diff-1afe140cec5b5f3c972a51ee6b46e110R1216

2017-01-10 08:52 UTC, alikon requested changes

2017-01-10 10:19 UTC, andrepereiradasilva commented on administrator/components/com_admin/sql/updates/mysql/3.7.0-2017-01-10.sql
> +ALTER TABLE `#__finder_tokens_aggregate` MODIFY `term_weight` float unsigned NOT NULL DEFAULT 1;
i followed the default value of other weight field. Nayway yeah, we need to be sure.
@chrisdavenport what do you think?

2017-02-21 17:19 UTC, chrisdavenport commented on administrator/components/com_admin/sql/updates/mysql/3.7.0-2017-01-10.sql
> +ALTER TABLE `#__finder_tokens_aggregate` MODIFY `term_weight` float unsigned NOT NULL DEFAULT 1;
@andrepereiradasilva Default 0 makes slightly more sense (1 is actually quite a high priority), although in theory the default should never be required anyway.

2017-02-23 08:32 UTC, csthomas commented
@andrepereiradasilva Are you available to fix conflict/rebase all and change mssql file.
mssql sql file should be change as @waader say.

Take a look at #14102

About *weight: Current mysql uses 0 as DEFAULT implicitly.

2018-05-21 09:25 UTC, Hackwar commented
Thank you for these optimisations. Considering that there has been no response by @andrepereiradasilva, I will try to create a new PR from this. I also noticed that the language columns are not unified with the rest of the language columns of Joomla. I would aim that new PR against the 4.0-dev branch. Can I be assigned to this issue, so that I don't forget?

2018-05-21 09:32 UTC, brianteeman commented
@Hackwar thanks - @andrepereiradasilva is no longer available and that is why this pr is flagged "needs a new owner"

2018-05-23 21:18 UTC, Hackwar commented
New PR is here: #20561

2018-05-23 21:19 UTC, closed without merging