Adding the Multilanguage Associations Manager
joomla/joomla-cms pull request #13537
Opened 2017-01-10 11:56 UTC by rdeutz

# Executive summary
This PR is a partial rewrite of the com_associations component based ion the work done in the Google Summer of Code Project "Improved Multilingual" (Repo: https://github.com/joomla-projects/gsoc16_improved-multi-lingual)

## Background information
The original concept made a lot of assumptions about fields and extensions and instantiated extensions models to get information about the internal structure. This concept comes with two problems:

1. Guessing can be wrong :-)
2. Instantiate a model can end up in fatal errors and a not working Website when the extension has a bug.  

I removed the guess and model instantiating and replaced it with a help class for extensions. This helper class provides all the needed information.

# Backwards compatibility
It is a new function so no problem here

# Translation impact
Two new language files for com_associations and one new language for any core extension that supports associations.

# Testing instruction 

* clone or get a copy of the staging branch
* setup a multilingual website
* Apply patch
* discover install

You will now find a new extension under components. 
The select box allows to chose an item type.

![ml-pic1](https://cloud.githubusercontent.com/assets/467356/21805300/bdd3ae72-d733-11e6-8500-50e23f11afb9.png)

When you have chosen a type and language, you can see your articles. 

![ml-pic2](https://cloud.githubusercontent.com/assets/467356/21805313/ce25fdf2-d733-11e6-940b-4c3be29143dc.png)

Click on an article (reference) and you will see the reference article on the left side. On the right side you can chose a translation target and translate your article.

![ml-pic3](https://cloud.githubusercontent.com/assets/467356/21805326/dca6b2b8-d733-11e6-8575-71f375cb97b7.png)

If you click on the available translation you get directly the view with two articles side by side.

![ml-pic4](https://cloud.githubusercontent.com/assets/467356/21805337/eaa8791e-d733-11e6-9e87-0675eb454f2d.png)

# Developer documentation
If your extension support association and you will make your extension available in the Associations Manager you have to provide a helper class (we have examples for com_content, com_contact, com_newsfeeds, com_menus, please look at the example implementation for inspiration :-))

You need to create a file "associations.php" in your component admin helper directory. If your component is names foobar the help class must be named as "FoobarAssociationsHelper" and it must extend "JAssociationExtensionHelper". 

Define three protected vars:

$extension = 'com_foobar';
$itemTypes = array('your_itemname', 'category');
$associationsSupport = true;

Define three public functions:

public function getAssociations($typeName, $id)

This function provides an interface the "JLanguageAssociations::getAssociations" and returns an array of associated items 

public function getItem($typeName, $id)

This function should return a JTable Object for the type and id. Don't forget something like "JTable::addIncludePath(__DIR__ . '/../tables')" so that the class can be found 

public function getType($typeName = '')

Here you set up information per type, the function returns an array: 

array(
			'fields'  => $fields,
			'support' => $support,
			'tables'  => $tables,
			'joins'   => $joins,
			'title'   => $title
		);

For fields and support we have a template function that set defaults so the you only have to overwrite what is different in your extension. Make sure that $fields['title'] and $fields['state'] are set right.

We need to write some documentation in JDocs but I think that here should be enough as a start.

# Open Issues
* Ordering not great
* Deal with checkout items  
* Extensions with multiple use of categories (seems a theoretical problem, because we couldn't find an extension using it)

# Final words
I would like to says thanks to the GSOC project members you did most of the work.

2017-01-10 12:07 UTC, infograf768 commented
We do need indeed some inpt to solve the checkedout.
And also the ACL: do we let edit/create associations for items where one has no create/edit ACL, on individual as well as extension level.

2017-01-10 12:41 UTC, laoneo commented
This is a very handy functionality, but should this not being built into the article manager itself, when editing an article? On a first glance it will be difficult to understand why the compare editor is on a completely different place, despite that the association is managed in the article itself.

2017-01-10 13:26 UTC, infograf768 commented
this does not only deals with articles. it is a general interface concerning all associations. here already implemented for core extensions, i.e. articles, menu items, contacts, newsfeeds, and will be for weblinks. we already can deal, article per article, generally speaking with all core extensions, item per item. com_associations is centralising all these (including 3pd if they set it) in a unique interface.

2017-01-10 13:28 UTC, infograf768 commented
@rdeutz 
please add as new feature

2017-01-10 15:32 UTC, laoneo commented
From developer point of view you are absolutely right and all makes sense. But for the end user I think it would be more convenient when you don't have to
1. close the article edit view
2. switch to the associations component
3. select the type
4. select the article
5. select the language
6. click on the article
7. select the target language

before the compare view opens.

Mostly you want to do that when you edit the article directly. Probably a button beside the "Save as copy" button would make sense to switch to the compare view. But I'm more of a developer than UX person so I think would be nice to have some input from UX people as well.

2017-01-10 15:39 UTC, andrepereiradasilva commented
> This is a very handy functionality, but should this not being built into the article manager itself, when editing an article? On a first glance it will be difficult to understand why the compare editor is on a completely different place, despite that the association is managed in the article itself.

@laoneo IMHO, if this componet exist it would be relatively straigh forward to integrate it in the "Associations" Tab "Edit" buttons (or something like it) in the future (excluding ACL checks, basicly should be opening the modal with the com_associations URI, instead of edit URI). Here:
![image](https://cloud.githubusercontent.com/assets/9630530/21812376/a5c85186-d74a-11e6-87b5-bdeffd835bc1.png)

2017-01-10 15:41 UTC, mbabker commented
If I'm not mistaken you'd still be able to set associations from within the article edit view, it just seems like this mainly creates an alternative workflow to set associations and a way to have the content from two associated items open side-by-side instead of needing modals or separate windows.  Just from the screenshots and what little I know of associations since I get chastised whenever I touch content on the one multilingual site I manage I don't see any UX issues with this at the moment.

2017-01-10 17:00 UTC, infograf768 commented
It is not only extremely handy to use it when you create a multilingual site: prepare your site in one language and then do all associations (it includes also create a new one or change the assoc to another item) from the original reference item, but also, alter on when you change some stuff in the "base" item and want to modify the assoc content (what we call the Target item).

2017-01-10 18:44 UTC, infograf768 commented
It took me a few minutes to make an association helper for sermonspeaker:
![screen shot 2017-01-10 at 19 03 51](https://cloud.githubusercontent.com/assets/869724/21818326/429f1210-d75f-11e6-903f-c4eb8c186b0c.png)

@Bakual 
[associations.php.zip](https://github.com/joomla/joomla-cms/files/697014/associations.php.zip)
(Still have an error in side by side with this file though)

+++ a new ini string
COM_SERMONSPEAKER_CATEGORIES="Categories"

2017-01-10 22:34 UTC, zero-24 requested changes

2017-01-10 22:34 UTC, zero-24 commented on administrator/components/com_associations/helpers/associations.php
> +		return $support->get('helper');
I'm not 100% sure can't we change this to: `self::$extensionsSupport[$extensionName]->get('helper');`

2017-01-10 22:34 UTC, zero-24 commented on administrator/components/com_associations/models/associations.php
> +			if (!$user->authorise('core.admin', $extension))
please double check the `$extension` should this not be `$extensionName`

2017-01-10 22:34 UTC, zero-24 commented on administrator/components/com_associations/models/associations.php
> +		if ($extension === 'com_menus')
same here `$extensionName`?

2017-01-10 22:34 UTC, zero-24 commented on administrator/components/com_associations/views/association/view.html.php
> +		JToolbarHelper::help('JGLOBAL_HELP');
I guess this needs to be a todo?

2017-01-10 22:34 UTC, zero-24 commented on administrator/components/com_associations/views/association/view.html.php
> +		JToolbarHelper::help('JGLOBAL_HELP');
as we need to add a help page here?

2017-01-10 22:34 UTC, zero-24 commented on administrator/components/com_associations/views/associations/view.html.php
> +				if (! in_array($extension, array('com_categories', 'com_menus')))
again extension to extensionname?

2017-01-11 07:13 UTC, infograf768 commented on administrator/components/com_associations/models/associations.php
> +		if ($extension === 'com_menus')
Indeed, although that check is a bit useless as these items will never get a language assigned and therefore should never display in the assoc manager.

2017-01-11 07:18 UTC, infograf768 commented on administrator/components/com_associations/views/associations/view.html.php
> +				if (! in_array($extension, array('com_categories', 'com_menus')))
Not in at case imho.
We have above:
`$extension = AssociationsHelper::getSupportedExtension($extensionName);`

2017-01-11 10:09 UTC, infograf768 commented
@Bakual 
Corrected the error in the sermonspeaker helper
[associations.php.zip](https://github.com/joomla/joomla-cms/files/698480/associations.php.zip)

2017-01-11 10:25 UTC, Bakual commented
@infograf768 Didn't have yet time t test anything here, but thanks. I've already added it to my repo :smile: 
https://github.com/Bakual/SermonSpeaker/blob/master/com_sermonspeaker/admin/helpers/associations.php

2017-01-11 10:27 UTC, infograf768 commented
👍  @Bakual 

Eagerly waiting for help from you to solve first the checked_out issue.

2017-01-11 11:21 UTC, AlexRed commented
I have tested this item :white_check_mark: successfully on 7b0b75f2a02b690ef39cc3b3aa5096917cb795a8<br /><br />Ok for me.
But please consider to change the "Clear" button in the Target side in "Delete Associations" to avoid confusion ad help in the translation procedure.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13537">issues.joomla.org/tracker/joomla-cms/13537</a>.</sub>

2017-01-11 11:54 UTC, infograf768 commented
Here is a demo of the checked_out issue.
The item concerned has been checked out by another user.
The user editing has no com_checkin manage permission.

![associationscheckedout](https://cloud.githubusercontent.com/assets/869724/21847600/fb02348e-d7fc-11e6-9314-b7f5e82c7cc4.gif)

2017-01-11 14:46 UTC, Bakual commented
I have tested this item :white_check_mark: successfully on 7b0b75f2a02b690ef39cc3b3aa5096917cb795a8<br /><br />Small thing:
In the "Select Target" modal, the tooltips for the search fields above are hidden behind the modal header. In other similar modals we set the tooltips to go below the field and not on top.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13537">issues.joomla.org/tracker/joomla-cms/13537</a>.</sub>

2017-01-11 14:56 UTC, rdeutz commented on administrator/components/com_associations/views/association/view.html.php
> +		JToolbarHelper::help('JGLOBAL_HELP');
yes is a todo

2017-01-11 14:58 UTC, rdeutz commented on administrator/components/com_associations/views/associations/view.html.php
> +				if (! in_array($extension, array('com_categories', 'com_menus')))
extensionName would be correct

2017-01-11 15:00 UTC, rdeutz commented on administrator/components/com_associations/helpers/associations.php
> +		return $support->get('helper');
should work but I wouldn't change it here

2017-01-11 18:11 UTC, infograf768 commented
For the Select Target Modal tooltip, change in `/administrator/components/com_associations/views/associations/tmpl/modal.php`
`JHtml::_('bootstrap.tooltip');`
to
`JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));`

2017-01-11 18:25 UTC, andrepereiradasilva commented on administrator/components/com_associations/views/associations/view.html.php
> +				if ($extension !== 'com_menu')
`com_menus´?

2017-01-11 18:27 UTC, infograf768 commented on administrator/components/com_associations/views/associations/view.html.php
> +				if ($extension !== 'com_menu')
Agree, that is also a wrong one.

2017-01-11 19:47 UTC, infograf768 commented on administrator/components/com_associations/views/associations/view.html.php
> +				if (! in_array($extension, array('com_categories', 'com_menus')))
oops...

2017-01-12 07:33 UTC, infograf768 commented on administrator/components/com_associations/associations.xml
> +	<creationDate>Januar 2017</creationDate>
`January`

2017-01-12 07:52 UTC, infograf768 commented
Created helper for weblinks.
https://github.com/joomla-extensions/weblinks/pull/294

2017-01-12 08:21 UTC, infograf768 commented on administrator/components/com_associations/views/associations/view.html.php
> +				if ($extensionName !== 'com_menu')
should be `com_menus`

2017-01-12 08:32 UTC, infograf768 commented on administrator/components/com_associations/views/associations/view.html.php
> +				if ($extensionName !== 'com_menu')
Once this is corrected, we do get the `Select Menu` filter
![screen shot 2017-01-12 at 09 30 36](https://cloud.githubusercontent.com/assets/869724/21882230/7b5af14e-d8a1-11e6-8cd1-cd7973c41512.png)

BUT when choosing a menu type, we get a 500
`500 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 'mainmenu-fr-fr' GROUP BY `a`.`id`,`a`.`title`,`a`.`language`,`l`.`title`,`l`.' at line 7 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 'mainmenu-fr-fr' GROUP BY `a`.`id`,`a`.`title`,`a`.`language`,`l`.`title`,`l`.' at line 7 `

2017-01-12 10:12 UTC, infograf768 commented on administrator/components/com_associations/views/associations/view.html.php
> +				if ($extensionName !== 'com_menu')
Found the culprit

2017-01-12 10:20 UTC, infograf768 commented on administrator/components/com_associations/views/associations/view.html.php
> +				if ($extensionName !== 'com_menu')
See patch https://github.com/rdeutz/joomla-cms/pull/8 correcting the menutype.
Still remains to change 'com_menu' to 'com_menus'

2017-01-13 07:59 UTC, infograf768 commented
@rdeutz 
These are ready, correcting com_menus typo, checked_out wrong variable, $cancheckin and menu helper
https://github.com/rdeutz/joomla-cms/pull/11
https://github.com/rdeutz/joomla-cms/pull/10
https://github.com/rdeutz/joomla-cms/pull/9
https://github.com/rdeutz/joomla-cms/pull/8

2017-01-13 10:49 UTC, andrepereiradasilva commented on administrator/language/en-GB/en-GB.com_menus.ini
> -COM_MENUS_LABEL_HIDDEN="Hidden"
why are there removed?

2017-01-13 10:49 UTC, andrepereiradasilva commented on administrator/language/en-GB/en-GB.com_menus.ini
> -COM_MENUS_TYPE_SYSTEM="System Links"
why are this removed?

2017-01-13 10:50 UTC, andrepereiradasilva commented on administrator/components/com_associations/associations.php
> +		throw new Exception(JText::_('COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED') . ' ' . $itemType->realcomponent, 404);
Does `$itemType->realcomponent` exists? or is a leftover?

2017-01-13 15:13 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_menus.ini
> -COM_MENUS_LABEL_HIDDEN="Hidden"
Agree, they should not

2017-01-13 15:13 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_menus.ini
> -COM_MENUS_TYPE_SYSTEM="System Links"
Agree, they should not

2017-01-13 15:24 UTC, infograf768 commented on administrator/components/com_associations/associations.php
> +		throw new Exception(JText::_('COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED') . ' ' . $itemType->realcomponent, 404);
Also, the lang string `COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED` is not present in the ini file.

2017-01-13 15:41 UTC, infograf768 commented on administrator/components/com_associations/associations.php
> +		throw new Exception(JText::_('COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED') . ' ' . $itemType->realcomponent, 404);
Maybe we should have something like:
`throw new Exception(JText::sprintf('COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED', JText::_($extensionName), JText::_($typeName), 404);`

and 
`COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED= "The extension %1$s does not support multilingual associations for the item type %2$s."

2017-01-15 10:40 UTC, rdeutz commented on administrator/language/en-GB/en-GB.com_menus.ini
> -COM_MENUS_TYPE_SYSTEM="System Links"
I didn't remove them I just fixed the alpha ordering

2017-01-15 10:41 UTC, rdeutz commented on administrator/language/en-GB/en-GB.com_menus.ini
> -COM_MENUS_LABEL_HIDDEN="Hidden"
I didn't remove them I just fixed the alpha ordering

2017-01-15 10:49 UTC, rdeutz commented on administrator/components/com_associations/associations.php
> +		throw new Exception(JText::_('COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED') . ' ' . $itemType->realcomponent, 404);
fixed with 406d18d2428a4ea11eb2e80f4f8c997a4cc621e1 thanks!

2017-01-15 13:35 UTC, andrepereiradasilva commented
@rdeutz @infograf768 it seems this PR misses the update (extension + asset) and installation part (extension + asset).

2017-01-15 13:45 UTC, rdeutz commented
@andrepereiradasilva yes I am working on it just at this moment :-)

2017-01-15 20:10 UTC, andrepereiradasilva commented on installation/sql/mysql/joomla.sql
> +(22, 'menu', 'com_associations', 'Multilingual Associations', '', 'Multilingual Associations', 'index.php?option=com_associations', 'component', 1, 1, 1, 28, 0, '0000-00-00 00:00:00', 0, 0, 'class:as
the component id is 34, not 28, see above

2017-01-15 20:10 UTC, andrepereiradasilva commented on installation/sql/postgresql/joomla.sql
> +(33, 'com_associations', 'component', 'com_associations', '', 1, 1, 1, 1, '', '', '', '', 0, '1970-01-01 00:00:00', 0, 0);
should be id 34
missing asset

2017-01-15 20:10 UTC, andrepereiradasilva commented on installation/sql/sqlazure/joomla.sql
> +SELECT 34, 'com_associations', 'component', 'com_associations', '', 1, 1, 1, 0, '', '', '', '', 0, '1900-01-01 00:00:00', 0, 0;
missing asset

2017-01-15 20:38 UTC, rdeutz commented on installation/sql/mysql/joomla.sql
> +(22, 'menu', 'com_associations', 'Multilingual Associations', '', 'Multilingual Associations', 'index.php?option=com_associations', 'component', 1, 1, 1, 28, 0, '0000-00-00 00:00:00', 0, 0, 'class:as
ups wrong file version

2017-01-16 08:52 UTC, infograf768 commented on administrator/components/com_admin/script.php
> +            array('component', 'com_associations', '', 1),
should be tabs instead of spaces and align to the others

2017-01-17 11:46 UTC, merged

2017-01-17 11:46 UTC, wilsonge commented on administrator/components/com_admin/script.php
> +            array('component', 'com_associations', '', 1),
Done

2017-01-17 11:47 UTC, wilsonge commented
Good work to everyone involved. Especially @rdeutz @infograf768 and especially @jreys for getting this started with your gsoc work :)

2017-01-17 15:03 UTC, puneet0191 commented
Thanks guys!  @rdeutz @infograf768 @alikon @andrepereiradasilva and @jreys :+1: and all the testers as well

2017-01-24 00:34 UTC, sloanthrasher commented
Will the side-by-side view be available when editing an article on the front-end?

2017-01-24 06:51 UTC, infograf768 commented
> Will the side-by-side view be available when editing an article on the front-end?

Not in 3.7.0
I am not aware of anybody working on a frontend Interface.

2017-02-11 23:34 UTC, joomleb commented
Hi guys, 
to really be able to manage sites multilanguage sites (quickly and simply) I think 3 things are a must:
1 - A fron-end interface, on normal sites is unthinkable to give translators an administrator access
2 - A layout more simple as possible. This is way I want put in evidence the [Speedy Translate extension](https://www.solidres.com/subscribe/speedy-translate) by Solidres. They found some solutions that in my opinion should be a need on joomla Multilanguage. In first of all I want put in evidence the "Inline Translation" feature. Click on a flag is 1 click, while click on a selector, choose, and select are "3 clicks".
3 - Last but not least, an article a lot of time have to be ready quaickly and it is hard to have all translated well soon. So, a "pre" - "auto-populate" button can be a solution (where clicking all the enabled languages are populated into the articles), as it is running (one by one) the [Translater CKEditor plugin](http://ckeditor.com/addon/xdsofttranslater) .

Many Thanks to all for this great new feature...

2017-02-12 20:50 UTC, Bakual commented
@joomleb This is a closed (merged) PR and thus doesn't get much attention. You would have to create a new issue if you have found a real issue. If you just need assistance with this new feature, feel free to use the forums (http://forum.joomla.org/)