Deprecate PSR-0 class loading
joomla/joomla-cms pull request #13672
Opened 2017-01-21 19:03 UTC by laoneo

As PSR-0 is deprecated, this PR adds a deprecated information that JLoader will be changed in Joomla 4 to PSR-4.

Maintainer review.

Ping @wilsonge

2017-01-21 19:06 UTC, mbabker commented
Why can't both be supported?  True that PSR-0 is deprecated but that doesn't mean it is unusable.  When I see a platform like Composer deprecate/drop PSR-0 support I might find this acceptable but for now I don't see any reason to do anything but add a deprecation notice and leave it be until the greater PHP ecosystem drops it in full.

Also, this change will 100% break the patch tester component because it does use the PSR-0 autoloader as I've namespaced the component classes.  The only way to therefore create a 3.x/4.x compatible build is to ship my own Composer autoloader since there won't be a path that allows me to load namespaced code in JLoader compatible with both versions.

2017-01-21 19:08 UTC, wilsonge commented
You cannot use both PSR-4 and PSR-0 code at the same time. So are we going to be stuck using PSR-0 code for another 5 years until composer removes support?

2017-01-21 19:09 UTC, mbabker commented
You can use both.  Look at our Framework packages as an example.  Are you saying I cannot install `joomla/application` and `joomla/session` together because the former uses PSR-4 and the latter PSR-0?

2017-01-21 19:09 UTC, mbabker commented
What you cannot do is register a path that's designed for PSR-4 support to a PSR-0 autoloader or vice versa.  But you can most assuredly have an autoloader for each variant.

2017-01-21 19:11 UTC, wilsonge commented
No but you must register each namespace with the relevant autoloader. Are we really going to introduce a `registerPSR4Namespace` method to register those namespaces differently.

2017-01-21 19:12 UTC, mbabker commented
I would suggest for 4.0 that you support both.  Otherwise you're making the 4.0 upgrade path more complicated for the sake of it.

2017-01-21 19:14 UTC, mbabker commented
Either way I will now update the patch tester to isolate itself from the core autoloader to prevent possible unneeded breakage either now or in the future.

2017-01-21 19:18 UTC, wilsonge commented
![img_5991](https://cloud.githubusercontent.com/assets/1986000/22177038/5a6cffc6-e00e-11e6-9a9b-0c2ad28111e3.JPG)

Fiiiiine

2017-01-21 19:34 UTC, laoneo commented
When this one will be accepted PR #13673 needs to be adjusted as well.

2017-01-21 20:43 UTC, wilsonge requested changes

2017-01-21 20:43 UTC, wilsonge commented on libraries/loader.php
> +	 * This function will be changed in J4 to support PSR-4 namespace registering.
Can you mark this was `@note` please

2017-01-21 20:43 UTC, wilsonge commented on libraries/loader.php
>  	{
Can we add an `InvalidArgumentException` if the type is not psr0 or psr4 please?

2017-01-21 20:43 UTC, wilsonge commented on libraries/loader.php
>  	{
Can we add an `InvalidArgumentException` if the type is not psr0 or psr4 please?

2017-01-21 20:43 UTC, zero-24 commented on libraries/loader.php
> +			if (strpos($class, $ns) === 0)
Please add a clean line before the if

2017-01-21 20:56 UTC, zero-24 commented on libraries/loader.php
> +		}
Here please too :)

2017-01-21 21:12 UTC, zero-24 reviewed
Here should be a clean line after the closing } and before the return

2017-01-21 21:15 UTC, zero-24 commented
Travis error:

FILE: /home/travis/build/joomla/joomla-cms/libraries/loader.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 391 | ERROR | Parameters must appear immediately after the comment
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

2017-01-22 11:32 UTC, wilsonge approved these changes

2017-01-22 11:33 UTC, wilsonge commented
Merging on review, given this is never going to get tests and we need it to progress in the sprint

2017-01-22 11:33 UTC, merged

2017-01-22 11:41 UTC, zero-24 commented
I have just fixed some smal CS Issues introduced from here ;)
https://github.com/joomla/joomla-cms/commit/f0d927051091a6725cc6bfe1e3b5ba13b81b8b4c

2017-01-22 11:43 UTC, wilsonge commented
Thanks!