Change JLoader to PSR-4 support
joomla/joomla-cms pull request #13673
Opened 2017-01-21 19:04 UTC by laoneo

JLoader supports now to register namespaces the PSR-4 way as PSR-0 is deprecated. Implementation of #13672.

Ping @wilsonge.

2017-01-21 19:28 UTC, zero-24 commented
@laoneo please update your branch that should fix the cs error from travis.

2017-01-22 14:27 UTC, wilsonge requested changes

2017-01-22 14:27 UTC, wilsonge commented on libraries/loader.php
> +	public static function registerNamespace($namespace, $path, $reset = false, $prepend = false)
Let's leave type as an argument here with 'psr4' as the only allowed option (else we throw the exception). This gives us more flexability in the future if we move to another standard

2017-01-25 15:27 UTC, laoneo commented
Closing this as we should probably support PSR-0 throughout 4 as well.

2017-01-25 15:27 UTC, closed without merging