Don't return admin menus
joomla/joomla-cms pull request #13791
Opened 2017-01-28 19:29 UTC by Bakual

Pull Request for Issue #13783.
Replaces #13788 and #13787

### Summary of Changes
Adding `client_id` checks to `MenusHelper::getMenuLinks()` so it returns only menus from frontend.
This method is used in core to fetch the menu items for the module and template "menu assignment" and by the `JFormFieldMenuitem` to get the menu item list.

### Testing Instructions
* Create a custom admin menu
* Edit a module and a template and check the menu assignment tab. The custom admin menu should not appear in the list of menu items
* Edit the "System - Page Cache" plugin and check that the custom admin menu doesn't appear in the "Exclude Menu Items" list.

### Documentation Changes Required
None

2017-01-28 19:41 UTC, izharaazmi requested changes
Imo, we should add this `where` only if the `$menuType` is not specified.

2017-01-28 21:27 UTC, Bakual commented
> Imo, we should add this where only if the $menuType is not specified.

Why? Until now, the method only returned frontend menuitems, the backend wasn't returned (I think because there was no menutype for that menu). This PR keeps the behavior inline with the existing one while keeping the change dead simple.

If there is a need to retrieve backend menuitems in future, this method would need at least a client argument and possibly other adjustments as well. But that is beyong what I try to fix in this PR.

2017-01-28 21:32 UTC, infograf768 commented
wondering if the method will also be used for the pr to come letting choose the components to be displayed/hidden in the container menu item. @izharaazmi

2017-01-28 21:34 UTC, izharaazmi commented
Beyond the scope of this PR... Agreed.

2017-01-28 21:37 UTC, izharaazmi commented
@infograf768 Yes. That's exactly what I did in my current work. PR pending.
When that comes, this may anyway be changed.

2017-01-28 21:40 UTC, Bakual commented
If you plan to use it in backend, I can adjust this PR accordingly of course. I just don't want to invest time into something which then isn't used at all.

I think an added client attribute is actually all it needs and it then should retain all other functionality. Would that be sufficient for your usecase?

2017-01-28 21:44 UTC, izharaazmi commented
Please don't invest any time on this function. I've already coded it. :-)

2017-01-29 06:35 UTC, infograf768 commented
@izharaazmi do i understand well that we should wait your new pr and not merge this one?

2017-01-29 06:59 UTC, izharaazmi commented
Yes, I hope so. I'll send my PR very soon. We can wait a little.

2017-01-29 07:03 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 0c4cbf1a5ce0d7a559853ff43796f44f82642bd8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13791">issues.joomla.org/tracker/joomla-cms/13791</a>.</sub>

2017-01-29 15:31 UTC, Bakual commented
> do i understand well that we should wait your new pr and not merge this one?

This can also be merged and @izharaazmi can solve the merge conflicts afterwards (if any).
The code here needs to go in anyway.

2017-01-30 07:11 UTC, laoneo commented
I have tested this item :white_check_mark: successfully on 0c4cbf1a5ce0d7a559853ff43796f44f82642bd8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13791">issues.joomla.org/tracker/joomla-cms/13791</a>.</sub>

2017-01-30 07:25 UTC, infograf768 commented
@Bakual
To make it easier to @izharaazmi , would not it be better to patch this way?
```php
diff --git a/administrator/components/com_menus/helpers/menus.php b/administrator/components/com_menus/helpers/menus.php
index c15ca1b..a8487e7 100644
--- a/administrator/components/com_menus/helpers/menus.php
+++ b/administrator/components/com_menus/helpers/menus.php
@@ -148,4 +148,8 @@
 	{
 		$db = JFactory::getDbo();
+
+		// Get site menu items per default
+		$clientId = 0;
+
 		$query = $db->getQuery(true)
 			->select('DISTINCT(a.id) AS value,
@@ -159,4 +163,5 @@
 					  a.checked_out,
 					  a.language,
+					  a.client_id,
 					  a.lft')
 			->from('#__menu AS a');
@@ -205,4 +210,5 @@
 
 		$query->where('a.published != -2');
+		$query->where('a.client_id = ' . $db->quote($clientId));
 		$query->order('a.lft ASC');
 
@@ -228,4 +234,5 @@
 				->from('#__menu_types')
 				->where('menutype <> ' . $db->quote(''))
+				->where('client_id = ' . $db->quote($clientId))
 				->order('title, menutype');
 			$db->setQuery($query);

```

2017-01-30 07:28 UTC, izharaazmi commented
@infograf768 Let it be that way. I will resolve any conflicts when
committing. Let's not bother him needlessly :)

2017-01-30 08:09 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 0c4cbf1a5ce0d7a559853ff43796f44f82642bd8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13791">issues.joomla.org/tracker/joomla-cms/13791</a>.</sub>

2017-01-30 08:10 UTC, infograf768 commented
RTC. Thanks.

@rdeutz please merge<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13791">issues.joomla.org/tracker/joomla-cms/13791</a>.</sub>

2017-01-30 08:19 UTC, merged