[4.0] Fix login autofocus in Firefox
joomla/joomla-cms pull request #14081
Opened 2017-02-15 10:15 UTC by C-Lodder

Pull Request for Issue #14071

### Summary of Changes

In Firefox, the backend login form would autofocus because the form was being set to `display:block` using Javascript. This PR removes that JS as there's no reason to hide the login form.

### Testing Instructions

- Apply patch
- Go to the admin login page
- It shoudl autofocus on the "Username" input

2017-02-15 11:37 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 38e7ee12c59502de39c54a23be2a7a4669bc57d3<br /><br />Thanks @C-Lodder <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14081">issues.joomla.org/tracker/joomla-cms/14081</a>.</sub>

2017-02-15 13:48 UTC, dgt41 commented on administrator/templates/atum/login.php
> -		}
This is needed for the browsers that have disabled javascript

2017-02-15 13:50 UTC, C-Lodder commented on administrator/templates/atum/login.php
> -		}
It's 2017. We really shouldn't need to cater for people who have JS disabled.

2017-02-15 13:58 UTC, dgt41 commented on administrator/templates/atum/login.php
> -		}
For this view (is the landing page for admin) is kinda required.

2017-02-15 14:01 UTC, dgt41 commented on administrator/templates/atum/login.php
> -		}
Also it prevents login in with our js:
No js
![screen shot 2017-02-15 at 16 00 44](https://cloud.githubusercontent.com/assets/3889375/22977613/0651a476-f398-11e6-8186-bd32afaf3079.png)

js enabled
![screen shot 2017-02-15 at 16 00 58](https://cloud.githubusercontent.com/assets/3889375/22977623/0f353d5a-f398-11e6-9b35-acb9a60a789a.png)

2017-02-15 14:05 UTC, C-Lodder commented on administrator/templates/atum/login.php
> -		}
Yeah I remember it being added. But do we really need to put a notice there for users who have JS disabled? Surely we're beyond those days now.

2017-02-15 14:06 UTC, dgrammatiko requested changes

2017-02-15 14:06 UTC, dgt41 commented on administrator/templates/atum/login.php
> -	</script>
Also this script is needed to show the form if js is enabled. Basically the changes in this file should be reverted

2017-02-15 14:07 UTC, dgt41 commented on administrator/templates/atum/login.php
> -		}
It's the only possible fallback before you give access to backend to someone that doesn't meet the minimum requirements. (I know it's rare to have js disabled, but better safe than sorry)

2017-02-21 20:28 UTC, wilsonge commented on administrator/templates/atum/login.php
> -		}
Dimitris is right. This one page must be non-js friendly. Same as how our entry php file support php 5.1 and higher - people on awful setups must have a friendly'ish message

2017-02-21 22:56 UTC, C-Lodder commented on administrator/templates/atum/login.php
> -		}
`<noscript>you mad?</noscript>` would suffice imo

2017-02-21 22:57 UTC, mbabker commented on administrator/templates/atum/login.php
> -		}
:trollface:

2017-02-21 23:07 UTC, dgt41 commented on administrator/templates/atum/login.php
> -		}
You might need to style it:
```html
<noscript class="😱">you mad?</noscript>
```

2017-02-22 09:17 UTC, C-Lodder commented
@dgt41 @franz-wohlkoenig re-added the no-js fallback. All working in FF

2017-02-22 10:02 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 4e4cbf440ac8914723894c97abb6ec8fbb0214a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14081">issues.joomla.org/tracker/joomla-cms/14081</a>.</sub>

2017-02-22 10:40 UTC, merged