Use the Archive package from framework and deprecate JArchive
joomla/joomla-cms pull request #14157
Opened 2017-02-20 17:55 UTC by laoneo

Move the framework Archive package.

### Testing instructions
Installer should work as before when installing new extensions.

2017-02-20 21:40 UTC, wilsonge commented
You need to fix tests here

2017-02-21 07:37 UTC, laoneo commented
The problem is that the archive package handles gzip and bzip differently than JArchive. The line here https://github.com/joomla-framework/archive/blob/master/src/Archive.php#L111 has a different logic than the core the equivalent https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/archive/archive.php#L107. 

IMO the core is doing it right. @mbabker I guess fixing that in the 1. series of archive package would be a BC break?

2017-02-21 12:46 UTC, mbabker commented
If you're referring to the use streams thing (why are we passing integers to a boolean parameter anyway!?), to be honest, I have no idea how well that's going to work with the Framework's filesystem package.

To be honest, anything depending on it for much probably needs to be shifted toward the end of this migration process.  Considering the entire thing is static and has no way to inject services, I fear to make things work we're going to end up subclassing things to use the CMS' existing API which still has the FTP layer in it and inherently still hooks into the CMS' configuration (I think the FTP layer support was ripped out of the Framework's version).

2017-02-21 13:43 UTC, laoneo commented
It works with the framework package except the gzip and bzip2 which handle the $extractdir argument differently. The rest is working as expected.

2017-02-24 10:19 UTC, franz-wohlkoenig commented
@laoneo is this for Test?

2017-02-24 13:15 UTC, laoneo commented
Not yet.

2017-04-14 01:34 UTC, mbabker commented
What's the plan here?

2017-04-29 13:32 UTC, laoneo commented
Sorry, missed your question. The problem is that the archive package handles gzip and bzip files differently than JArchive. The line here https://github.com/joomla-framework/archive/blob/master/src/Archive.php#L111 has a different logic than the core the equivalent https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/archive/archive.php#L107.

IMO the core is doing it right. I guess changing that in the 1. series of archive package would be a BC break?

2017-04-29 15:40 UTC, mbabker commented
If you mean supporting streams versus not supporting streams, to be honest because the entirety of our filesystem code is still procedural code, it's really difficult to build the needed dependency (the Stream object) in the Framework whereas the CMS goes through JFactory to create one with the needed configuration.  So we really need to bite the bullet and refactor the filesystem package to be OOP based and come up with a system for injecting dependencies.

2017-04-29 15:45 UTC, laoneo commented
Not stream, about the logic. Please compare the logic of the two links. In the fw package the outside worlds needs to be aware if they are zipped gz files or archives. It is different logic for the extract function. That's why the unit tests in the CMS do fail.

2017-04-29 15:47 UTC, mbabker commented
I'm obviously missing something here.  I'm not seeing why the Framework's way is broken to be honest here.  Ya, they might behave differently internally, but that doesn't make it wrong necessarily.

2017-05-01 09:51 UTC, laoneo commented
I'm not saying that it is broken in the fw, it just has a logic where you need to pass a folder, depending of the input file. For example when you pass a gzip file `/my/path/test.txt.gz`then the extractDir in the fw must be `/my/extract/path/test.txt` whicle in the CMS you have to pass as extractdir parameter `/my/extract/path`. That's why for me the cms lib is more consistent and a 1 to 1 replacement can't be done with the fw package in the core.

2017-06-04 08:31 UTC, laoneo commented
Reopening this one, but first the inconsistency needs to be fixed in the fw package.

2017-06-05 15:41 UTC, laoneo commented
Opened pr as disscused at JAB 17 https://github.com/joomla-framework/archive/pull/12. If that one gets merged, then this one needs to be adapted as well.

2017-06-12 12:01 UTC, wilsonge commented
Just tagged 1.1.5 for you :)

2017-06-12 12:07 UTC, laoneo commented
Composer package updated, guess it is ready for a test.

2017-06-17 01:05 UTC, mbabker commented
I have tested this item :white_check_mark: successfully on f7bceaafe2f813ccc29957756cd3a99579d3ce15<br /><br />Installed com_patchtester ZIP package successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14157">issues.joomla.org/tracker/joomla-cms/14157</a>.</sub>

2017-06-17 07:49 UTC, zero-24 requested changes

2017-06-17 07:49 UTC, zero-24 commented on administrator/components/com_banners/models/tracks.php
> +				if (!$packager = $archive->getAdapter('zip'))
please add a clean line here

2017-06-26 14:49 UTC, merged