[4.0] Move executable code out of index.php files
joomla/joomla-cms pull request #14236
Opened 2017-02-24 17:40 UTC by zero-24

Pull Request for Issue # .

### Summary of Changes

Similar to how we've already restructured the install app, the `administrator/index.php` and `index.php` files should be restructured in a way that allows those files to remain PHP 5.2 friendly while not impeding us using PHP 5.3+ features (like namespaced classes).

### Testing Instructions

- Install 4.0 using this branch (https://github.com/zero-24/joomla-cms/archive/indexphp-40.zip)
- confirm the frontend and backend works.

### Documentation Changes Required

None

2017-02-24 17:47 UTC, zero-24 commented
Drone issues are fixed here: https://github.com/joomla/joomla-cms/pull/14237

2017-02-24 17:47 UTC, mbabker requested changes

2017-02-24 17:47 UTC, mbabker commented on administrator/includes/app.php
> +if (file_exists(__DIR__ . '/defines.php'))
Needs to check `dirname(__DIR__)` otherwise you're looking for `administrator/includes/defines.php` here instead of `administrator/defines.php`.  Same will probably apply to the other one.

2017-02-24 17:47 UTC, mbabker commented on administrator/includes/app.php
> +	define('JPATH_BASE', __DIR__);
`define('JPATH_BASE', dirname(__DIR__));`

2017-02-24 17:47 UTC, mbabker commented on administrator/index.php
> + * define() is used in the installation folder rather than "const" to not error for PHP 5.2 and lower
This isn't the install directory 😉

2017-02-24 17:47 UTC, mbabker commented on installation/index.php
> +require_once dirname(__FILE__) . '/application/app.php';
You'll need to update paths in the moved file as well.

2017-02-24 17:48 UTC, franz-wohlkoenig commented
Got a blank white Screen trying to install.

2017-02-24 17:54 UTC, zero-24 commented on administrator/includes/app.php
> +if (file_exists(__DIR__ . '/defines.php'))
i guess you mean it in reversed order?

As we want to look for `administrator/includes/defines.php` and not `administrator/defines.php`

2017-02-24 17:58 UTC, mbabker commented on administrator/includes/app.php
> +if (file_exists(__DIR__ . '/defines.php'))
No.  This check explicitly supports looking for a custom defines file at `administrator/defines.php`.  The same applies for the frontend and `defines.php`.  If that overrides file does not exist and it does not define the `_JDEFINES` constant then the default file in `(administrator/)includes/defines.php` is loaded.

2017-02-24 18:00 UTC, mbabker commented on installation/application/app.php
> +require_once dirname(__DIR__) . '/defines.php';
Everything in this file except for the `JPATH_BASE` definition can stay as `__DIR__ . '/file.php'`.  Otherwise now you're looking for `installation/defines.php`, `installation/framework.php`, etc.

2017-02-24 18:29 UTC, zero-24 commented on installation/index.php
> +require_once dirname(__FILE__) . '/application/app.php';
should be ok now Thanks.

2017-02-24 18:29 UTC, zero-24 commented
Finally i have got it worked.

2017-02-24 21:25 UTC, zero-24 commented
@mbabker please approve your review or remove it as we still have this PR in the `Changes requested` status.

2017-02-24 21:36 UTC, mbabker approved these changes

2017-02-24 21:37 UTC, zero-24 commented
Thanks.

2017-02-25 00:10 UTC, wilsonge commented
Can you fix the CS in drone please?

2017-02-25 00:44 UTC, zero-24 commented
done @wilsonge

2017-02-25 00:45 UTC, zero-24 commented
btw you can also do that if needed as i have enabled maintainer edit.

2017-02-25 00:46 UTC, wilsonge commented
I know :) but I'm on a train home :p

2017-03-11 23:55 UTC, zero-24 commented
@franz-wohlkoenig it should work now can you retest this please?

2017-03-12 06:32 UTC, franz-wohlkoenig commented
@zero-24 Install works. Test Front- and Backend (any special to look or random click on Menues)?

2017-03-12 10:09 UTC, zero-24 commented
If you can install and access the frontend and backend we are ok. As this code is the starting point into every application :)

2017-03-12 10:31 UTC, dgrammatiko requested changes

2017-03-12 10:31 UTC, dgt41 commented on index.php
> +require_once dirname(__FILE__) . '/includes/app.php';
Can I ask for a custom entry?
```php
if (is_file(JPATH_BASE . '/includes/custom.php'))
{
	require_once JPATH_BASE . '/includes/custom.php';
}
else
{
        require_once dirname(__FILE__) . '/includes/app.php';
}
```

2017-03-12 10:37 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 05a07a3e6e8161878b28e449ab1c2113ca20ed62<br /><br />Installation, access to Back- and Frontend works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14236">issues.joomla.org/tracker/joomla-cms/14236</a>.</sub>

2017-03-12 10:53 UTC, zero-24 commented on index.php
> +require_once dirname(__FILE__) . '/includes/app.php';
@mbabker can we have your input on this? As this would be a new "feature" for the app start. ;)

2017-03-12 15:03 UTC, mbabker commented on index.php
> +require_once dirname(__FILE__) . '/includes/app.php';
1) Outside of scope of this PR.  Do not add it here.

2) What's its purpose?  If you're trying to create your own app versus using the shipped admin, site, and install apps, you should be supplying your own front controller (index.php file).

2017-03-12 15:20 UTC, dgt41 commented on index.php
> +require_once dirname(__FILE__) . '/includes/app.php';
Well there's gonna be only one index.php, in the root...

2017-03-12 15:22 UTC, mbabker commented on index.php
> +require_once dirname(__FILE__) . '/includes/app.php';
I'm missing something here.  Your proposal is basically saying "run my custom application, not the core application".  At that point you should be shipping your own index.php used in a subdirectory (similar to how https://github.com/wilsonge/release-api is done).

I'm not seeing what this is adding.  And again, this is for a separate PR.  Let's keep things scoped to single items please.

2017-03-18 11:30 UTC, merged