An alternative implementation for Component Dispatcher
joomla/joomla-cms pull request #14258
Opened 2017-02-26 10:58 UTC by joomdonation

Pull Request for Issue # .

### Summary of Changes
This PR proposes an alternative implementation of component dispatcher for Joomla 4. It is not for merging, I open it for discussing purpose only. With this implementation (and further works on MVC layer), we can support namespace + HMVC  for our extensions. See https://github.com/joomdonation/joomla-cms/tree/joomla-mvc/administrator/components/com_banners for a basic (already working) component.

#### The component structure
1. The component needs to be restructured so that all (or at least Models, Views, Controllers classes) will ve autoloaded with PSR-4 Autoloader:

- Controller classes will be located inside administrator/components/com_mycom/Controller, components/com_mycom/Controller folders.
- Model classes will be located inside administrator/components/com_mycom/Model, components/com_mycom/Model folders.
- View classes will be located inside administrator/components/com_mycom/View, components/com_mycom/View folders.

2. We need to avoid using JPATH_COMPONENT in component code

3. We must not getting input directly from application object (JFactory::getApplication()->input) on our component/plugins. We need to find a way to pass it from controller to models/views (could it be property of Model/View class?)

#### The Dispatcher concept
In an application (frontend or backend), there would be one instance of dispatcher object for a component. It is created in component entry https://github.com/joomdonation/joomla-cms/blob/joomla-mvc/administrator/components/com_banners/banners.php#L14

```php
\Joomla\Cms\Dispatcher\Dispatcher::getInstance('com_banners')->dispatch();
```
The getInstance method accept two arguments:

1. $option : It is the name of component being executed
2. An optional array $config containing the technical config settings of a component. These config settings will be passed as config variables while creating controllers, Model, View. Table classes for the extension. Basic description of the some of config keys (more will be added while working further on MVC layer) can be found below, if one not passed, default value will be used:

- component_namespace : For Joomla core, it should be something Joomla\Content, Joomla\Contact, Joomla\Banners...
- frontend_namespace: Namespace for frontend classes of component, it should be something like Joomla\Content\Site,  Joomla\Contact\Site
- backend_namespace: Namespace for backend classes of component, it should be something like Joomla\Content\Admin,  Joomla\Contact\Admin
- redirect: Whether we should redirect after component being executed. By default, it is Yes. For an HMVC call (for example, in a module used to display a view in component, it should set to No)
- load_language : Should be false by default. Set it to Yes for an HMVC call
- table_prefix: Prefix of database table name, for core extensions, it usually #__, for custom extensions, it usually be #__COMPONENTNAME_
- template_path
- db

After calling dispatch method for first time, we can call it for second time, passing new input to executing new request of the same component. For example, the code below would get the cached dispatcher object, execute new request to display list of clients records..

```php
$dispatcher = \Joomla\Cms\Dispatcher\Dispatcher::getInstance('com_banners');
$dispatcher->dispatch();

// Passing new input to dispatcher and dispatch again
$oldInput = $dispatcher->setInput(array('view' => 'clients'));
$dispatcher->dispatch();

// Restore old input
$dispatcher->setInput($oldInput);
```
#### Support HMVC would be a nice thing
If we could support HMVC, that would be great. To display a view in an extension in a module or in a Joomla article..., instead of having to write code to get data, render it, we can simply call code something like this:

```php
$config = array(
	'input'         => array(
		'view'               => 'myview',
		'id'                 => '5',
		'other_request_data' => 'data',
	),
	'redirect'      => 'false',
	'load_language' => true
);

\Joomla\Cms\Dispatcher\Dispatcher::getInstance('com_mycom', $config);
	->dispatch();
```

I have done basic work to support this (of course, there are many improvements can be made to the changes it as I only spend litle time working on it until decision is made), if we with any chances, try to go with this direction, we will work further (and there are many questions I have need to be answered/discussed

1. Change to Controller classes https://github.com/joomdonation/joomla-cms/commit/a9bd932089472fe74ebfee2fca4380042a552428

2. Change to Model classes https://github.com/joomdonation/joomla-cms/commit/fa1092533697fb1dec6a13e4bc5c7d7c326ca276

3. Change to View classes (only very small change for now) https://github.com/joomdonation/joomla-cms/commit/ec43627880443311623b58f63e2b3dba706c2d23

2017-02-26 15:04 UTC, joomdonation commented
@wilsonge Thanks for helping :).

2017-02-26 16:29 UTC, mbabker commented
> We need to find a way to pass it from controller to models/views (could it be property of Model/View class?)

No.  In proper MVC architectures the model and view should be unaware of the input.  It's the controller that should be aware of this and be pushing the required information into the model and view.

I'm not seeing why you have a `table_prefix` property on the options array.  This is controlled by the database driver.  And as such, now that the DI package is getting more use in 4.0 in general, a component should be hooking in more with that to have its required dependencies injected in and with the right configuration.

(Note this comment is coming based solely on the PR summary, haven't clicked to code view yet)

2017-02-26 16:31 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	public function __construct(array $config = array())
What is the benefit here to an unkeyed array versus explicitly declared dependencies?

2017-02-26 16:32 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		$app    = \JFactory::getApplication();
This seems like a step backward going from having the app as a class property of the dispatcher to pulling it from the global factory.

2017-02-26 16:33 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		if ($this->config['redirect'])
I'm seeing a lot of uses of keys in this array with no default configuration or isset checks.  You're almost better off going to a `Registry` object here or correctly structuring the merging of the array data with a set of known defaults.

2017-02-26 16:35 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	protected static function normalizeConfig($option, array $config = array())
This normalization should be part of the constructor, not the singleton factory.  You have a public constructor.

2017-02-26 16:59 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	protected static function normalizeConfig($option, array $config = array())
The reason is this https://github.com/joomdonation/joomla-cms/blob/component-dispatcher/libraries/src/Cms/Dispatcher/Dispatcher.php#L74-L79. I want to check to see whether component has dispatcher class or not, if not, then use this default dispatcher. Need to have some config keys available for checking class exists before calling contructor

2017-02-26 17:00 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		if ($this->config['redirect'])
I was thinking about using Registry object before, but I think it is easier (and maybe faster) to write code to populate config data using array than using Registry.

And actually, all use keys are available, it is populated during normalizeConfig method

2017-02-26 17:03 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		if ($this->config['redirect'])
It's not guaranteed right now because `normalizeConfig` isn't run if you direct instantiate the dispatcher, it'll ONLY work correctly right now if going through the factory.

2017-02-26 17:06 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		if ($this->config['redirect'])
ah, I see. Maybe put constructor as protected would solve it?

2017-02-26 17:15 UTC, joomdonation commented
> No. In proper MVC architectures the model and view should be unaware of the input. It's the controller that should be aware of this and be pushing the required information into the model and view.

I see this. However, in scope of a component, it's the controller create the model and view object. So controller can easily pass it's input to model/view. I don't know if a view need to access to input object directly, however, a model needs it:

1. Model needs to populate states base on input data. That can be sorted by calling populateState method directly in the getModel class in controller. 

2. The other case is when model needs to access to Files Upload. At the moment, in current legacy MVC, we only pass validated data (which is an array) to model in save method, so when a model needs to access to files upload, it usually calls JFactory::getApplication()->input to access to input directly, and that's preventing us from having a proper HMVC implement

> I'm not seeing why you have a table_prefix property on the options array

It is not just the database table prefix. It is common preifx of all tables using in the extension, like #__edocman_ , #__osmembership_... I am not sure if it is needed yet, the purpose is that we might use it to guess the table name base on model name and generate the list query in model list automatically....

2017-02-26 17:16 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		if ($this->config['redirect'])
You'd have to make sure that would still work if a subclass has an extended constructor and also marked it protected (a lot of folks are just copying core code and might not understand visibility/scope issues there).  Otherwise that could address it.

2017-02-26 17:19 UTC, mbabker commented
> Model needs to populate states base on input data. That can be sorted by calling populateState method directly in the getModel class in controller.

Models shouldn't be building their own state.  That's part of the problem with our current architecture, and in some ways it hurts their reuse.  State should be injected from the controller (or if you use the model disconnected from MVC architecture like in models that source should be pushing in the state).

> I am not sure if it is needed yet, the purpose is that we might use it to guess the table name base on model name and generate the list query in model list automatically.

For now I'd leave it out of this proposal, even if it has no active use at the moment.  Seems like scope creep, let's focus more on the dispatching concept for now.

2017-02-26 17:21 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		$app    = \JFactory::getApplication();
It is just a matter of what parameter needs to be passed to method getInstance to get a dispatcher object. If we want to has  application object as property here, we would have to change the code in component entry from:

```php
\Joomla\Cms\Dispatcher\Dispatcher::getInstance('com_mycom', $config);
```
To something like

\Joomla\Cms\Dispatcher\Dispatcher::getInstance(JFactory::getApplication(), $config);

Then option can be get directly from $input.

2017-02-26 17:27 UTC, wilsonge commented
No the state should be populated in a controller and injected into the model. Populate state as a concept needs to be deprecated in Joomla 4. There is work in progress on this for all our core components.

The backend frontend namespaces shouldn't be config values. We have a standard for them which is defined in the "Use of namespacing" section here https://volunteers.joomla.org/teams/joomla-4-architecture/reports/115-joomla-4-architecture-sprint-odense-dk 

In terms of injecting the input that does need to be added but that needs to not be a config value but an explicit parameter

All the other config values I don't see as useful. I think having a application and optional input object should be enough for this class

2017-02-26 17:27 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		$app    = \JFactory::getApplication();
Defeats the point of having the factory and dispatcher then if it's going to lock to a single global singleton.

Allow an `app` key in the config array defaulting to what's in `JFactory` if one isn't passed.  It still allows parameter injection with a sensible default.

I'm personally not a fan of using unkeyed arrays for object injection in classes, but that's not a battle I'm ever going to win in Joomla.

2017-02-26 17:28 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		$app    = \JFactory::getApplication();
Also for reference, that (the single global singleton) is in part why at least the controller triad of our MVC is so painful.  It legitimately does not support multiple controller instances at all.

2017-02-26 17:28 UTC, wilsonge commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	protected static function normalizeConfig($option, array $config = array())
No we need to support the old way of not having a dispatcher and including the old class. We deliberately built this into JComponentHelper and as an abstract class here for a reason

2017-02-26 17:30 UTC, joomdonation commented
> The backend frontend namespaces shouldn't be config values.

How about third party extensions? We need to specify the namespace which we want to use for our extensions. Or there is a better way?

2017-02-26 17:33 UTC, joomdonation commented
So there are two main questions here:

1. What's the correct way for model to populate state from input?

2. How model access to files upload (for example, in save method). Our current code only pass the validated data https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/controller/form.php#L744 . Will we need to pass an extra $input parameter?

2017-02-26 17:34 UTC, wilsonge commented
1. The model should NEVER populate state from the input. That is the controllers job 

2. Controllers should pass models the information as part of the mode state....

2017-02-26 17:35 UTC, wilsonge commented
If you're using the Joomla dispatcher information you use the Joomla namespacing default. If you want your own, you use your own dispatcher implementation

2017-02-26 17:36 UTC, mbabker commented
The answer to both of your questions means redefining the MVC relationships.  Models should be request unaware, controllers (or whatever is calling models) should be injecting the required data, whether that be as part of the model's state or as function parameters.  When you stop looking at it as the model should be reading direct from the request (https://github.com/joomla/help.joomla.org or https://github.com/joomla/framework.joomla.org might better demonstrate this, unfortunately we repeated some of these mistakes with the issue tracker), you'll see some of the flaws in the current structure and why we need to revisit the approach.

2017-02-26 17:43 UTC, joomdonation commented
> If you're using the Joomla dispatcher information you use the Joomla namespacing default. If you want your own, you use your own dispatcher implementation

To me, having config option to help saving developers of having to write code would be better. But if you decide that, I can make the change

> The model should NEVER populate state from the input. That is the controllers job
> Models should be request unaware, controllers (or whatever is calling models) should be injecting the required data

Do you have example code which I can look at to understand exactly how to do that?

2017-02-26 17:47 UTC, mbabker commented
You can pass this array into `JModelLegacy::getInstance()`:

```php
$config = [
    'state' => new JObject,
    'ignore_request' => true,
];

$model = JModelLegacy::getInstance('Article', 'ContentModel', $config);`

2017-02-26 17:52 UTC, joomdonation commented
That give me to next question. Look at https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/articles.php#L98 , we have many state variables (not sure what's the correct term for it) like filter.access, fiter.search...., how do controller know about these variables to populate data for all these variables?

2017-02-26 17:55 UTC, mbabker commented
The same way the model knows about them now.  You basically move the bulk of that `populateState` method into the controller.

2017-02-26 17:59 UTC, joomdonation commented
Thanks. Look like it is clear now.

2017-02-26 22:23 UTC, yvesh commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	public static function getInstance($option, array $config = array())
Hmm, what's for you the main advantage in having an getInstance method in the new dispatcher?

2017-02-26 22:25 UTC, yvesh commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$this->setInput(\JFactory::getApplication()->input);
Let's not start that, when we use dispatcher, $config should be required and not optional.. Or is there any valid reason to offer a different way?

2017-02-26 22:26 UTC, yvesh commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		$this->input->def('option', $config['option']);
Really?

2017-02-26 22:28 UTC, yvesh commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$classes[] = $this->config['namespace'] . '\\Controller\\' . ucfirst($format) . '\\' . ucfirst($name);
i am still not a fan of hardcoding this.

2017-02-26 22:31 UTC, yvesh commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$config['backend_namespace'] = $config['component_namespace'] . '\\Admin';
Still not a fan hardcoding it here :-)

2017-02-26 22:37 UTC, wilsonge commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$this->setInput(\JFactory::getApplication()->input);
Yes. Because if you're doing the default component rendering then you want to use the Application Input :)

2017-02-26 22:46 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$this->setInput(\JFactory::getApplication()->input);
To me this part's fine, it lets us inject optional dependencies while having sensible defaults.  Same pattern exists elsewhere.  I just hate the array versus explicit param thing, makes using our DI code harder as it can't just build a usable object on its own using Reflection to resolve the constructors, you have to have defined service callbacks or rely on setter injection.

2017-02-26 23:57 UTC, yvesh commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$this->setInput(\JFactory::getApplication()->input);
@wilsonge sure, but isn't it better when it's always forwarded to the dispatcher? The less coupling the better for me.

2017-02-27 01:13 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		$this->input->def('option', $config['option']);
There was a reason for that. In the current implementation, $option is a required parameter for getInstance method, so that's just easier passing input to dispatcher. Something like this

```php
$config = array(
	'input'         => array(
		'view'               => 'myview',
		'id'                 => '5',
		'other_request_data' => 'data',
	),
	'redirect'      => 'false',
	'load_language' => true
);

\Joomla\Cms\Dispatcher\Dispatcher::getInstance('com_mycom', $config);
	->dispatch();
```
As you can see, in the input passing, I don't have to pass option variable anymore. Just kind of lazy purchase

However, with the suggestions received, $option would be removed from being parameter of getInstance method, thus that code would be removed, too.

2017-02-27 01:14 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$classes[] = $this->config['namespace'] . '\\Controller\\' . ucfirst($format) . '\\' . ucfirst($name);
Could you please explain more details about this? Not very clear to me.

2017-02-27 01:15 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$config['backend_namespace'] = $config['component_namespace'] . '\\Admin';
Could you please explain more details? What's hardcoded here? If you don't pass it to $config array, then we need to use a default value like this.

2017-02-27 01:19 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		$this->input->def('option', $config['option']);
No, `$option` should still be a parameter of `getInstance()`.  Otherwise the concept is completely useless and you might as well not have your singleton logic in the class at all.  Getting the dispatcher for a given component MUST be a configurable parameter.

2017-02-27 01:21 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	public static function getInstance($option, array $config = array())
Two reasons:

1. Caching the dispatcher object. With the ideal of supporting HMVC in new MVC implementation, on page load, there could be multiple requests to the same component, so I think caching the dispatcher to be able to re-use it if needed.  Not sure if it is needed to, I don't know what's the cost of re-creating dispatcher everytime time it is needed vs re-use it from cache

2. About getting class. I want that if component doesn't provider dispatcher class, we can use this default class.

2017-02-27 01:24 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		$this->input->def('option', $config['option']);
If we don't want/ don't have to cache the created dispatcher + force component creating it's own dispatcher class if needed (for example, when component needs to use custom namespace COMPNAY/Comname instead of Joomla/Comname, then we can remove the getInstance method completely

2017-02-27 01:29 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	public static function getInstance($option, array $config = array())
What is the aim for this dispatcher concept first of all?  As it was merged, AND where this is aiming to go?

I don't think this dispatcher concept should be the way to deal with HMVC.  For starters you're working one layer too high in the stack for that.  `JControllerLegacy::getInstance()` still blocks being able to use more than one controller in a request due to its singular singleton logic.  So once you fix that, what is this dispatcher actually accomplishing other than moving a controller's primary entry point from a procedural file to an object oriented approach?

2017-02-27 01:49 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	public static function getInstance($option, array $config = array())
In my point of view, Dispatcher simply receives request, creating and controller, and execute the request. It is more or less, is a replacement for JControllerLegacy::getInstance(), plus, it perform something like load language, decide whether redirection should be made or not after request is being executed. Further more, component dispatcher, if needed, can use it to do anything it wants like requiring additional libraries,... before component / controller is being executed.

2017-02-27 01:54 UTC, mbabker commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	public static function getInstance($option, array $config = array())
I don't see how it's a replacement for `JControllerLegacy::getInstance()`.  To me this dispatcher is replacing the component entry file but not doing anything to improve being able to do HMVC type stuff.  Even if it were a replacement, I'm not sold on why the process should be to use the dispatcher (which probably is going to make an overly broad assumption that it is the component that's been routed to by the request similar to the current manner of doing things) versus direct calling a `JControllerLegacy::getInstance()` that someone has cleaned up to make it capable of loading multiple controllers in one request (same as `JModelLegacy::getInstance()` and loading multiple models).

2017-02-27 02:09 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	public static function getInstance($option, array $config = array())
1. It creates the controller base on the given input, so in Controller class, we don't need JControllerLegacy::getInstance() anymore

2. Yes, it makes the component entry file thin (basically, it will be only one line of code), or can be a replacement

3. It is just a helper for HMVC stuff, load loading language, getting correct controller and execute the request. Image when we want to render a view of a component inside an article, we can call simple code as I wrote somewhere in this PR. Of course, to support HMVC, we need more works on MVC layer.

Without this dispatcher, we can still do it with JControllerLegacy::getInstance(), but before calling it, we would have to loading languages files.., do any initialize process (like requires library...).which the executed component might need.

2017-02-27 06:29 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +	protected static function normalizeConfig($option, array $config = array())
> No we need to support the old way of not having a dispatcher and including the old class. 

I think the old way would still be OK. We just keep the component entry file and in that file, we just call

```php
\Joomla\Cms\Dispatcher\Dispatcher::getInstance('com_mycom')->dispatch();
```
With that, the check in JComponentHelper  could be removed (still use the old code)

2017-02-27 13:27 UTC, joomdonation commented
OK. So base on suggestions, I made some changes to the original implementation:

1. Add two new optional arguments $input, $app to getInstance method so that application and input object can be passed from the code getting dispatcher. Application object now accessed via class property $app instead of calling JFactory::getApplication() directly

2. Remove normalizeConfig method.

3. Look at Controller class again, I see that we need to use Application object in that class, so passing $this->app as a new argument to create controller object code https://github.com/joomla/joomla-cms/pull/14258/files#diff-34e77048ffc88d27c50b168a7c3eb744R248

When you have a moment, could you review it again?

2017-02-27 13:38 UTC, mbabker commented
Since there's little communication or planning in the project's development overall, I still have no general idea what the overall goal is with this component dispatching concept as a whole (as the original PR was merged or this PR in all honesty).  Without knowing what that intent is, I can't really say whether this PR is an improvement or a redefinition of the feature.

So someone make it clear to me.  What is the purpose of the original dispatcher feature as merged?  What is its design goal?  With those answers given, how is this PR either an improvement on or a replacement for the original design?

I'm not buying into the "this can eventually replace `JControllerLegacy::getInstance()`" argument right now.  I see two different architectural concepts here; a dispatcher (with what purpose I'm still not 100% clear) and a controller and one is not a suitable replacement for the other in terms of instantiation logic or general use.

2017-02-27 14:08 UTC, joomdonation commented
@wilsonge and @yvesh would give us the answer about the goad and purpose of the original dispatcher merged PR

For this PR, there are some purposes:

1. Prepare (first step) for supporting namespace, PSR-4 components. 

2. Provide a esier way to support HMVC support for extensions. Image in a module of an extension, we want to display a view of the component of that extension, what would we have to do if we use JControllerLegacy::getInstance() approach:

- Loading component language files
- Require any libraries required by the extension
- Calling JController::getInstance()->setInput($input)->execute();

With this dispatcher concept, I would leave the first two steps above to the dispatcher of the component (I don't have to worry or know what libraries might be using), just call the code below:
\Joomla\Cms\Dispatcher\Dispatcher::getInstance('com_mycom', $config, $input)
	->dispatch()

2017-02-27 14:09 UTC, wilsonge commented
Will respond this evening. Super busy at work today :)

2017-02-27 14:28 UTC, mbabker commented
Part of the issue with the language file loading is that it's already handled by a separate helper (JComponentHelper is handling all of that extra stuff before loading a component's entry file).  Honestly I'm not so sure moving that logic to the dispatcher is a real fix for anything, it just moves that logic into another place but the MVC triad is still unaware if any of its support stuff has been loaded.

The dispatchers can't be ACL aware the same way as the current entry files are.  Imagine trying to proxy a frontend request to a backend controller using the dispatcher or having an admin module trying to proxy to a component that isn't the active one, the dispatcher would be a roadblock to making that work if you one-for-one copy the existing logic.  So we've already got a logic flaw in this new code (talking what's merged now).

I get HMVC is a goal.  But the plan for this all really needs to be laid out (hmm, wasn't one of the first things I groaned to the production department leadership about related to a lack of a cohesive plan?) so we're all on the same page with how we're getting there.  I still don't see how the HMVC goal is tied into this dispatcher concept or how the dispatcher concept addresses the point that there is logic being performed automagically outside of the component that really should exist somewhere closer to the component.  And if that means I have to come across as challenging or asking a lot of questions to make sure that everything is crystal clear on why we're adding a new feature or a new approach to X or making an architectural change, then so be it; hopefully that means everything is well explained and everyone who has a potential to be impacted understands the 5 W's about things.

2017-02-27 14:39 UTC, joomdonation commented
OK. So for this, I will wait to hear from @wilsonge to see whether this is something we can use, if not, I am closing the PR.

2017-02-27 23:16 UTC, wilsonge commented
OK So the dispatcher is a two purpose machine. It has a simple and a slightly more complex purpose:

1. It allows full dependency injection for components. With a mock JApplicationCms (or JApplicationSite/JApplicationAdministrator if you're using those more specific functions), then you probably can unit test the end to end component without the presence of the CMS

2. I want to imagine a light HMVC in the CMS, I wanted this dispatcher to be a light version of the dispatcher in FOF. This means that dispatchers can be used to call components from anywhere with the following uses:

1. Modules loading component views
2. System plugins for the 'loading shit everywhere' behaviour that most extensions love at the moment).
3. Half an eye on a future webservices implementation

This wasn't supposed to be an end product. The next step was to suck up some of the default logic in the component controllers responsible for things like default views, so people don't need to create default component controllers for just setting default views. In terms of specific issues:

The ACL logic is basically a copy of what we have right now in our components. Doesn't make it right. But I wanted something simple based on our existing entry points that we could develop further. 

We were unsure in the sprint how to load components (hence the current JControllerLegacy implementation remained). We were divided between the factory based controller loading and @laoneo 's preferred method of registering controllers into the DIC. But the intention is definitely to move beyond that single `getInstance` method.

2017-02-28 00:20 UTC, mbabker commented
OK, so a few thoughts shooting from the hip.

1. I don't see the need to keep this class abstract.  Even as merged, `BannersDispatcher` is usable with the base implementation without any additional configuration.  So I think for the absolute simplest base use case it should be appropriate to serve an instance of `Joomla\Cms\Dispatcher\Dispatcher` if it hasn't been subclassed.

2. The FOF dispatcher doesn't use singleton instances (its container does).  So I think we need to weigh pros and cons of that.  If we are going to go singleton, I don't know if locking it based on whomever is the first caller to the dispatcher wins the configuration battle is the preferred choice.  Things like the class namespace would stay static, but if our recommended use case is to always pull a dispatcher through the singleton factory versus instantiating a new instance directly, you wouldn't be able to inject a separate app or input object into the dispatcher for separate use cases.  Maybe this is a non-issue, but it does need to be pointed out.

3. Filesystem paths.  This might be an appropriate time to introduce `JPATH_COMPONENTS_SITE` and `JPATH_COMPONENTS_ADMIN`.  I know we're still a long way from it, but part of the logic behind the `JPATH_*` constants is to one day be able to move your filesystem around on the server (i.e. move the components directory outside the webspace).  As the component directories are "critical" paths, the shortcut might make sense here.  Probably outside scope of this PR, but something to consider too.

2017-02-28 00:35 UTC, wilsonge commented
To answer point 1 - the reason for the abstract class is that a component dispatcher must be optional so that we call back to the legacy way of including a component (via the `component_name.php`). To keep it optional I elected to have the default implementation as abstract, then when a component 'opts in' to the dispatcher it creates the concrete (empty) wrapping class

To answer point 2 - I don't think we do need singletons. I agree with the idea here of having an optional input to inject. But I disagree with having a static instance of a dispatcher - I think there needs to be multiple dispatchers for a single component

To answer point 3 - I agree but I don't think it's in scope but would welcome a separate PR to the J4 repo (or maybe even 3.8 repo even if it's unused)

2017-02-28 00:38 UTC, wilsonge commented
Also just an additional point. The intention here was also to add the autoloading as @joomdonation did - but we thought it probably made more sense to store component namespaces in the database (or component xml files) than to try and build them on the fly and allow overrides via config (which ends up with modules/plugins potentially overriding the psr-4 paths) - there should only be a single psr-4 path to load the namespaces.

2017-02-28 01:40 UTC, joomdonation commented
1. I also don't see it need to be abstract class, too. There is no need for components have to implement a blank dispatcher class like that. We can still keep a the component entry file as how it is at the moment, and in that file, just call Joomla\Cms\Dispatcher\Dispatcher. That said, the change to JComponentHelper before to support dispatcher class is unnecessary and can be reverted

2. Singleton could still be useful here (although I don't know how much it is). A page for example, can load several modules of a same component. Each module then can get dispatcher object, set input and dispatch it to display the module https://github.com/akeeba/akeebasubs/blob/development/modules/site/aksubslist/mod_aksubslist.php#L44 (with HMVC concept, we would not have real modules, everything is actually inside component). 

The real usage of HMVC as I can see at the moment, is only in scope of a single application (site or administrator). I don't know how, for example, calling a view from admin app from site app yet

However, as I said, I don't know how much it is useful (saving the creation of several dispatcher objects in a page load), so if you think that it is needed, let's remove it

3. About the additional point @wilsonge mentioned, we can deal with it later.

2017-02-28 11:27 UTC, joomdonation commented
OK. So I made some changes today:

1. Remove singleton

2. Remove the dispatcher exists check implemented before at https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/cms/component/helper.php#L370 . If something like this is accepted, we can still have component entry like how it is at the moment. No need for that kind of check

3. Make sure the component is enabled before dispatching

To be more clear, if we decide to go with this direction, we will end up of having to re-write the current legacy MVC layer to support this concept. That mean, in Joomla 4, we would have two MVCs shipped, the current legacy MVC and the new MVC which will be working on.

2017-02-28 12:03 UTC, Fedik commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		if ($this->config['redirect'])
+1 to use Registry for $config

2017-02-28 12:53 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +		if ($this->config['redirect'])
I will leave it as an array for now. The reason is because use array will help working in the next step (Controller) easier. 

In Controller class, we have getModel() method (same for getView() method...) which create model object. When that method is called, there would be a config array passed from the caller (see https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/controllers/articles.php#L121 for an example) . The controller class will then have to merge the passed config array with the default config array (which is passed to the dispatcher), then pass that merged array to Model constructor.  I know Registry support merge two objects, but the point here is that using array will help it is easier for caller to pass the requested config variables. Abit confusing but it will become clear when we work further on MVC layer (see this line again https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/controllers/articles.php#L121 and you would get the idea)

2017-02-28 15:20 UTC, joomdonation commented
@mbabker @wilsonge Would be great if you could take another look at this

2017-02-28 15:57 UTC, wilsonge commented
I disagree with the approach you took to `JComponentHelper` - I'd much rather have that, move the majority of code in `Dispatcher::getInstance` into the `__construct` method (and maybe even remove the `getInstance` method altogether)

2017-02-28 16:00 UTC, wilsonge requested changes

2017-02-28 16:00 UTC, wilsonge commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$cNamespace = $config['component_namespace'];
Forcing dispatchers to inject a namespace is still a recipe for disaster. Why should modules override a component namespace?

2017-02-28 16:00 UTC, wilsonge commented
This is getting better tho :) don't be discouraged!

2017-02-28 16:02 UTC, joomdonation commented on libraries/src/Cms/Dispatcher/Dispatcher.php
> +			$cNamespace = $config['component_namespace'];
The question is where would we get that namespace setting for now?

2017-02-28 16:14 UTC, joomdonation commented
> I disagree with the approach you took to JComponentHelper

The code in JComponentHelper checking for the file **dispatcher.php** in the root folder of the component  which is not available with new implementation (the file now is Dispatcher.php, and will be placed inside component root folder or inside Dispatcher folder under component root (depends on our decision). That's why I removed it for now. Also, I still think still calling component entry file like how it was before still be OK with this approach

> I'd much rather have that, move the majority of code in Dispatcher::getInstance into the __construct method (and maybe even remove the getInstance method altogether)

We can only do that if you want to force a blank Dispatcher class for every component. To me, I hate having to add a blank class for nothing like this
```php
namespace Joomla\Component\Content\Dispatcher;
class Dispatcher extends \Joomla\Cms\Dispatcher
{
}
```

So I still think that getInstance() is useful in this case

2017-02-28 16:20 UTC, wilsonge commented
Modules are not going to necessarily know of the component namespace. Hence why I prefered a compulsory non-namespaced dispatcher file over an arbitrary namespaced dispatcher file that might not even exist where the module has the ability to overwrite the namespace

2017-02-28 16:23 UTC, mbabker commented
The component manifest is probably going to have to be expanded to include some stuff like a [fof.xml](https://github.com/akeeba/release-system/blob/development/component/backend/fof.xml) file would define, including namespaces.  So the data is extracted from the manifest (by way of either live reading the XML or the manifest cache from the database).

2017-02-28 16:24 UTC, joomdonation commented
Please ignore my last comment about Dispatcher::getInstance. Will think to see whether we can remove it as you suggested or not.

2017-02-28 16:48 UTC, wilsonge commented
In London we considered maybe even a new mysql column (default null) for ultra-optimisation in the extensions table (as it's not just components but plugins and to a lesser extent modules that could also be namespaced). But something like that

2017-02-28 16:51 UTC, mbabker commented
Even as a separate field, ultimately something in the manifest will probably have to define the new data.  Even the branch Allon shared a little bit ago where he's doing a POC on namespacing com_content has some stuff that would arguably be better suited in the dispatcher, it's just a matter of getting that data into it somehow.

2017-03-01 06:34 UTC, laoneo commented
When working on the com_content migration I got the feeling that it is not really necessary to have the namespace in a manifest file or even database. An approach can be to have that support in JLoader to load an extension namespace like [this example](https://github.com/Digital-Peak/joomla-cms/blob/j4/namespace/component/content/administrator/components/com_content/helpers/content.php#L14). If an extension needs something from a different extension, then it will be a one liner to load a different extensions namespace, kind of lazy loading.

For the dispatcher, I'm not sure if it is even needed to have that class namespaced as it is the entry point of the component.

2017-03-01 06:53 UTC, joomdonation commented
OK. So I made another changes to the code as suggested to remove getInstance() method. Now, to create dispatcher object:

1. If one component doesn't have Dispatcher class implemented, it can use Joomla\Cms\Dispatcher\Dispatcher directly

```php
(new Joomla\Cms\Dispatcher\Dispatcher())->dispatch();
```
2. If component has custom dispatcher class implemented, it needs to call that dispatcher class directly
```php
(new Joomla\Content\Admin\Dispatcher\Dispatcher())->dispatch();
```
For now, namespace  can simply be set in $cNamespace property of Dispatcher class, if none is set, Joomla\Component\Comname will be used. In case a component wants to use custom namespace, just create a dispatcher class and set $cNamespace  to the namespace it wants to use. At the moment, it doesn't need to be defined in manifest file or in database yet.

Right now, I still have two questions and looking for advice:

1. Should we introduce a new method initialize() method which will be called at the end of __contructor method ? I have the feeling that the code which registering autoloader or load language file (if needed) should be placed inside that separate method. Plus, it gives component specific dispatcher class init the dispatcher further if needed

2. Since we removed the singleton, I see that the method setInput is less useful now. I could not image a case which we get dispatcher object, dispatch it, then set a new input and dispatch again. So should we remove it?

3. Should we allow override Controller/Model/View classes in our core code if it is needed (same as override template). See http://eventbookingdoc.joomservices.com/developer-documentation/code-customization-override#override-method-in-a-controller-class

Due to my support life as extensions developer, I usually have to customize code in controllers, models, views class to meet customers need, and I see that supporting override is useful. Not sure if it is the same for Joomla core.

2017-03-01 10:44 UTC, yvesh commented
1.) Hmm other extensions can override the constructor and call the parent one, but it could be nice to split the tasks done in the constructor into various methods, like one (protected) loadLanguage(). Not sure if a initialize method is needed, but maybe others prefer it this way ¯\_(ツ)_/¯

2.) Personally i prefer getters and setters for everything, you never knew what ppl come up with..

3.) This is probably out of scope for this PR. Let's first define the basics, we can than extend it.

P.S.: Please call it componentNamespace and not cNamespace ;) The reason having it in the component params is that you can than get the name space from other places, like a second component or module.

2017-03-01 10:55 UTC, joomdonation commented
Thanks @yvesh for your feedback. I will wait for feedback from others before making the changes. If this is the right direction, I can try to start working on base controller class so that we can have a clear picture about how it will work as as a whole

@wilsonge @mbabker Please help looking at this again when you have time

2017-03-01 13:29 UTC, mbabker commented
> If an extension needs something from a different extension, then it will be a one liner to load a different extensions namespace, kind of lazy loading

The extension then has to know internals about the extension it is trying to lookup.  That seems like a bad design pattern.

2017-03-01 13:32 UTC, mbabker commented
> Should we allow override Controller/Model/View classes in our core code if it is needed

The only supported override method should be mangling the autoloader to put a path for a given namespace before the "default".  Nothing more, nothing less.  NEVER should we be designing an API which calls for class overloading as the favored approach, that is what a service driven architecture is for.

2017-03-02 12:18 UTC, joomdonation commented
Thinking more about this Dispatcher class together with MVC layer as a whole, I wonder what would be the right option: Passing an Application object or passing a Container object as property of this class. In case passing Container object, then Container would also be a property of Controller, Model and View classes, too.

The reason I ask this question is because I see that in Model and View classes code, we have to trigger event like this https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Cms/Model/Admin.php#L757. So in case we don't use Container, we would have to call \JFactory::getApplication() to get application object (which as I understand should be avoided?). Thought ?

2017-03-02 13:29 UTC, mbabker commented
The DI container should NEVER be injected as a class property ANYWHERE.  That is the biggest anti-pattern when it comes to dependency injection (and IIRC Symfony is actually making it harder to even do so with their DependencyInjection component).

Yes, it is available right now pretty easily (`JFactory::getApplication()->getContainer()`, `JFactory::getContainer()`, and whatever else we have implementing `ContainerAwareInterface`), but the places where we are explicitly reaching into the container are areas where we have factory methods trying to create service classes.

2017-03-02 13:32 UTC, joomdonation commented
So in case of trigger event in model for example, we will still use JFactory::getApplication()->triggerEvent directly?

2017-03-02 13:40 UTC, mbabker commented
Actually we should have `JModelLegacy` (and anything that's dispatching events) implement `DispatcherAwareInterface` and the dispatcher be a class property of the class for a proper system.  But that's probably not going to happen anytime soon without adding more keys to our options arrays that for some reason we make massive use of as constructors (and the constructors would probably still have to have the call to either the container or application to fetch required dependencies if not pushed in).

2017-03-02 13:55 UTC, joomdonation commented
These concepts are new to me, so to be honest, I don't understand. Thanks for your advice anyway.

2017-03-19 08:18 UTC, closed without merging