Patch 6
joomla/joomla-cms pull request #14250
Opened 2017-02-25 14:37 UTC by joomdonation

Pull Request for Issue # .

### Summary of Changes
Since Joomla 3.6 , JViewLegacy has implemented the method setDocumentTitle https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/view/legacy.php#L854-L873 which is used to set document title base on site configuration. However, in many views in Joomla code base, we still use manual code, repeating code to set page title. This PR solves it

### Testing Instructions
A real test would be check all views changes by this PR and make sure the document title is not changed before and after patch. However, honestly, I don't think we can expect that kind of test here because it would take much time

So I hope developers can help reviewing the code of the PR and confirm that it is expected changes. If you review code, please help reviewing every file carefully.

### Documentation Changes Required
None

2017-02-25 15:02 UTC, zero-24 requested changes
Please remove the tabs and replace it with clean lines.

2017-02-25 15:02 UTC, zero-24 commented on components/com_contact/views/contact/view.html.php
> +
please remove the tabs here and just lets this be a clean line.

2017-02-25 15:11 UTC, joomdonation commented on components/com_contact/views/contact/view.html.php
> +
@zero-24: Could I ask for your help with code style issues here?

2017-02-25 15:19 UTC, zero-24 commented on components/com_contact/views/contact/view.html.php
> +
what kind of help do you need? 😄

2017-02-25 15:21 UTC, joomdonation commented on components/com_contact/views/contact/view.html.php
> +
The issues with code styles if it is possible :)

2017-02-25 15:22 UTC, joomdonation commented on components/com_contact/views/contact/view.html.php
> +
Any of course if you can help reviewing the changes in the code to make sure there are no mistakes, too :)

2017-02-25 15:46 UTC, zero-24 commented on components/com_contact/views/contact/view.html.php
> +
https://github.com/joomdonation/joomla-cms/pull/3

Please try this and than we can look into it again

2017-02-25 15:50 UTC, joomdonation commented on components/com_contact/views/contact/view.html.php
> +
Many thanks for helping.

2017-02-25 15:54 UTC, zero-24 approved these changes

2017-02-25 15:54 UTC, zero-24 commented
looks good now from a cs persprctive 👍

2017-02-25 15:56 UTC, joomdonation commented
Again, many thanks for your help @zero-24. I realize that there are still changes needed to some other files (to remove un-used variables + minor optimization). In case there are CS changes needed, I would love to receive your help again :)

2017-02-25 15:57 UTC, zero-24 commented
no problem just ping me 😄

2017-02-26 04:46 UTC, joomdonation commented
@wilsonge @rdeutz  This PR makes changes to many files, should I spit it into smaller PRs (each PR for one component) for easier code review and we can get human testing, too?

2017-02-26 12:48 UTC, rdeutz commented
if you had 200 than yes but 20 changed files is ok

2017-02-26 12:50 UTC, joomdonation commented
OK. Thanks. I will leave it as how it is, then

2017-03-02 21:26 UTC, n9iels approved these changes

2017-03-02 21:27 UTC, n9iels commented
I have tested this item :white_check_mark: successfully on 823693e9216357c8958560857f6d1a0014e255ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14250">issues.joomla.org/tracker/joomla-cms/14250</a>.</sub>

2017-05-14 01:39 UTC, closed without merging

2017-05-14 12:46 UTC, n9iels commented
@joomdonation What is the reason to close this PR?

2017-05-14 13:13 UTC, joomdonation commented
@n9iels Honestly, a PR which changes multiple files like this would be hard to get testers and proper testings

Also, I was thinking about introduce a new method which set both page title and page meta data (which basically including this block of code as well https://github.com/joomdonation/joomla-cms/blob/0031973e956bc83700140cb905e4a963c195cd45/components/com_content/views/form/view.html.php#L163-L176 )

So I think it is better to close this PR and do proper coding in Joomla 4. Thanks for reviewing the changes though :)