[com_fields] Enable custom fields to be configured to output in different contexts
joomla/joomla-cms pull request #14641
Opened 2017-03-15 13:04 UTC by GeraintEdwards

The custom fields plugin is a welcome addition to Joomla but its usefulness is limited by a lack of configurability.

For instance you can't configure custom fields in com_content, for instance, within the single article view and not in the featured article view.

This PR adds a new config option to config.xml for com_content to allow the site admin user to choose the contexts where they may wish the fields to be available or displayed. The mechanism can easily be extended to other components using the fields plugin.

### Summary of Changes
Summary of Changes

1.     Adds config option to com_content to allow user to select where custom fields should be displayed
2.     Adds com_content helper to use this config option
3.     Adds required language strings 

### Testing Instructions

Open com_content config and on Integrations tab select 'Featured articles view' as one of the output contexts for custom fields and disable 'Single article view'.

### Expected result

Featured articles page will now show custom fields but the article detail view will not.

Similar changes can be added to other components that use custom fields.

2017-03-15 13:06 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FEATURED_VIEW="Featured article view"
For consistency please make this

Featured Article view

2017-03-15 13:11 UTC, GeraintEdwards commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FEATURED_VIEW="Featured article view"
"Featured Articles view" ??

Also should  I have

COM_CONTENT_ARTICLE_VIEW="Single Article view"

2017-03-15 13:13 UTC, mbabker commented on administrator/components/com_content/helpers/content.php
> +			$customFieldsEnabledContexts = $compParams->get('custom_fields_enabled_contexts', '');
If the parameter is storing data as an array, your default value here should also be an array.

2017-03-15 13:15 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FEATURED_VIEW="Featured article view"
Sorry yes it should be plural
and yes the same capitalisation for the Single Article

2017-03-15 13:16 UTC, GeraintEdwards commented on administrator/components/com_content/helpers/content.php
> +			$customFieldsEnabledContexts = $compParams->get('custom_fields_enabled_contexts', '');
Good point.  I'll update the code

2017-03-15 13:16 UTC, mbabker commented
Honestly, I don't think a component level parameter is going to be good enough.  If fields were supported in non-HTML output, I have a use case where we could use fields for the security announcement category on https://developer.joomla.org but not enable fields for any other content.  As is, I would have to have fields enabled for all category and article contexts (granted it's still an improvement that there are a couple of (in this site's case unused) contexts it could be disabled in, but for this to really be beneficial it's going to have to get "smarter" over time.

2017-03-15 13:16 UTC, GeraintEdwards commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FEATURED_VIEW="Featured article view"
Changes on their way - thanks

2017-03-15 13:44 UTC, GeraintEdwards commented
I'm guessing that is a 'Category blog' view limited to a specific category?   If so then you would want the context to be set within the category too.  Then the validateSection method could check the category of the item (using a static instance type field to cache the results) to see if the fields should be output.

Are you using a custom component for the announcements with a different context?  I was working on the contexts available in com_content - I did a search for "onContentPrepare" in the core codebase and that is all I found.

I guess we could set the context parameter field to be one where custom additional contexts could be added like the module position field when editing a module.  May not be very intuitive to normal users though.

2017-03-15 14:02 UTC, mbabker commented
Except for the JoomlaCode issue archive, everything on that site is core (com_content and modules).

On the backend we can set it up just fine.  For the frontend though, because the events aren't triggered outside HTML views (not related to this PR but a general issue with the implementation; it's a roadblock for our use case because of the RSS feed) and because the events will run in full for a view context without being able to filter to a lower level (enable for X category and disable for Y) it makes setting that up for us less appealing.

At work we're doing an upgrade and integrating fields into our site and this current setup (all or nothing) is causing a performance hit.  The expanded context checking would help with that.

2017-03-15 14:23 UTC, GeraintEdwards commented
Once https://github.com/joomla/joomla-cms/pull/14558 is merged I was planning on a new PR that would fetch the fields in one go from the getList method of the mode.  It seems rather pointless to me to generate a complex query to fetch the item ids a second time before getting the field data - why not simply pass the list of ids into a method to fetch the custom fields in one go.

This would require a new plugin hook, e.g. onGetListData (or similar) in the getItems method of the model to be called after the data base been obtained and passing in a reference to the $items and the key variable.  The custom field data would be fetched in a radically simplified means and would be available to your non HTML views (as long as they use the core component model).  

That would then leave the need to control the data fetch based on context and/or category, though it would be a fairly simple single query to fetch the data and so would only have limited impact on performance if the custom field data was not needed by the output.

2017-05-03 10:00 UTC, GeraintEdwards commented
Please can this fix be tested - my previous comment regarding fetching the custom fields in one batch has been largely superseded by changes made in the method of fetching custom fields already merges into the core.

2017-05-03 10:15 UTC, franz-wohlkoenig commented
@GeraintEdwards will have a Look.

2017-05-03 10:56 UTC, franz-wohlkoenig commented
I have tested this item :red_circle: unsuccessfully on 785123173719cd42234dad005e270e6ec6a1dfe1<br /><br />1/3 Set where Custom Field should appear



2/3 Custom Field appear in Featured Article-Menu



3/3 Custom Field appear in Article Detail View<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14641">issues.joomla.org/tracker/joomla-cms/14641</a>.</sub>

2017-05-03 16:27 UTC, GeraintEdwards commented
Thanks for spotting that - I had not returned a null value in the single article view when it was not selected as an option.  I have now corrected this.  See the following screenshots (sorry for the lines on the images - Gimp is playing up :( )

![justarticles-config](https://cloud.githubusercontent.com/assets/839810/25670761/a2cf5234-3025-11e7-9dcd-793840677dd3.png)
![just-article-featured-menu](https://cloud.githubusercontent.com/assets/839810/25670766/a73ce21e-3025-11e7-9892-eb75374b7d69.png)
![just-article-single-article-view](https://cloud.githubusercontent.com/assets/839810/25670770/aa43ccc0-3025-11e7-80cc-a3247c169759.png)

Then the reverse

![featuredarticles-config](https://cloud.githubusercontent.com/assets/839810/25670803/c73ff790-3025-11e7-8622-f7fa769ceb96.png)
![just-featured-featured-menu](https://cloud.githubusercontent.com/assets/839810/25670808/c9e00580-3025-11e7-9b97-64496be4798a.png)
![just-featured-single-article-view](https://cloud.githubusercontent.com/assets/839810/25670811/cd18b986-3025-11e7-89c0-89fe585461c4.png)

2017-05-04 05:48 UTC, franz-wohlkoenig commented
Can't test now cause [Problem](https://github.com/joomla-extensions/patchtester/issues/192)

2017-06-05 13:22 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 9b8db63ac81f12e5ef81cecc0fb72be8e768bde7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14641">issues.joomla.org/tracker/joomla-cms/14641</a>.</sub>

2017-06-05 14:27 UTC, Bakual requested changes
Some remarks about the used default values and there are some unrelated files in this PR.

2017-06-05 14:27 UTC, Bakual commented on administrator/components/com_content/config.xml
> +			default="com_content.article"
By default, it should be show in all places like it does currently. Otherwise behavior changes as soon as the user saves the component options without actively changing anything. Also the default value has to match an actual option otherwise it doesn't work well.

2017-06-05 14:27 UTC, Bakual commented on administrator/components/com_content/helpers/content.php
> +			$customFieldsEnabledContexts = $compParams->get('custom_fields_enabled_contexts', array());
The default value here (`array()`) has to match the default value set in the XML. In our case it has to default to show in all contexts.

2017-06-05 14:27 UTC, Bakual commented on administrator/components/com_fields/helpers/fields.php
> +			    '-2' => 'count_trashed',
wrong alignment

2017-06-05 14:27 UTC, Bakual commented on administrator/templates/isis/error-gwe.php
> +<?php
That file looks unrelated to this PR

2017-06-05 14:27 UTC, Bakual commented on templates/protostar/html/layouts/gwe-com_content/fields/render.php
> +<?php
That file looks unrelated to this PR

2017-06-05 14:27 UTC, Bakual commented on templates/protostar/html/layouts/gwe-com_fields/fields/render.php
> +<?php
That file looks unrelated to this PR

2017-07-08 15:35 UTC, laoneo commented
Would it also be an option to add a new option on the field in which context it should be displayed only?

2017-07-08 18:08 UTC, franz-wohlkoenig commented
+1 @laoneo

2018-04-02 19:38 UTC, tonypartridge commented
@GeraintEdwards  can you see bakual's remarks and fix? Then we can test :-)

2018-06-07 20:10 UTC, pepperstreet commented
@GeraintEdwards and all other testers / contributors
Following… and I just want to express my appreciation for your work on this **important** feature!

2018-07-22 20:41 UTC, roland-d commented
Pinging @GeraintEdwards for a follow-up.

2019-07-01 21:57 UTC, HLeithner commented
thx @GeraintEdwards for your time you invested in creating this PR, it seams you are no longer interested in this PR because there are outstanding requests to clean up this PR.

Anyway if you are still interested to get this feature into Joomla it has to go into J4 because J3.x is in feature freeze. I would really appreciate if you bring this PR to J4 in the meantime I close this PR.

thx for your work on Joomla!

2019-07-01 21:57 UTC, closed without merging