[associations] Plugin link in message
joomla/joomla-cms pull request #14654
Opened 2017-03-15 22:00 UTC by brianteeman

### Summary of Changes
If you go to the Redirects or Smart Search component without the required plugin enabled you will get a message to enable it and the message includes a direct link to the plugin itself. 
<img width="803" alt="screenshotr21-38-40" src="https://cloud.githubusercontent.com/assets/1296369/23972591/4f8053de-09ca-11e7-8870-756eaeb42f55.png">

The new Multilingual Associations component had a similar message but there is no link to the plugin

<img width="835" alt="screenshotr21-39-09" src="https://cloud.githubusercontent.com/assets/1296369/23972621/686b025e-09ca-11e7-95d8-d5ddd59e0c34.png">

After applying this PR the message will change to have a link to the plugin in the message itself. 

<img width="572" alt="screenshotr21-58-35" src="https://cloud.githubusercontent.com/assets/1296369/23972669/8fb30708-09ca-11e7-8134-7a8d39a3c2e0.png">

### Testing Instructions
Make sure that  Items Associations is not enabled in the Language Filter plugin.
Open the Multilingual Associations component
Before the PR the message is just text
After the PR the message includes a link to the Language Filter plugin

### Documentation Changes Required
None

2017-03-16 06:29 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 194204d5f61d403ffd8d49aaecf484c4915baac8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14654">issues.joomla.org/tracker/joomla-cms/14654</a>.</sub>

2017-03-16 06:46 UTC, infograf768 requested changes

2017-03-16 06:46 UTC, infograf768 commented on administrator/components/com_associations/helpers/associations.php
> +	/**
Please add a blank line before the comment

2017-03-16 06:46 UTC, infograf768 commented on administrator/components/com_associations/helpers/associations.php
> +
Please delete the 2 blank lines

2017-03-16 09:05 UTC, brianteeman commented on administrator/components/com_associations/helpers/associations.php
> +	/**
Thanks - done

2017-03-16 09:05 UTC, brianteeman commented on administrator/components/com_associations/helpers/associations.php
> +
Thanks done

2017-03-16 09:39 UTC, alikon requested changes

2017-03-16 09:39 UTC, alikon commented on administrator/components/com_associations/helpers/associations.php
> +		catch (RuntimeException $e)
can you use  proper  exception `JDatabaseExceptionExecuting` instead of `RuntimeException`

2017-03-16 10:04 UTC, brianteeman commented
@alikon i could do but then the code wouldn't be consistent with the two
other uses. If you think it should be changed i think it would be better to
do it in all three places after this pr in a separate pr



On 16 Mar 2017 9:39 a.m., "Nicola Galgano" <notifications@github.com> wrote:

> *@alikon* requested changes on this pull request.
> ------------------------------
>
> In administrator/components/com_associations/helpers/associations.php
> <https://github.com/joomla/joomla-cms/pull/14654#discussion_r106372782>:
>
> > +	 */
> +	public static function getLanguagefilterPluginId()
> +	{
> +		$db    = JFactory::getDbo();
> +		$query = $db->getQuery(true)
> +			->select($db->quoteName('extension_id'))
> +			->from($db->quoteName('#__extensions'))
> +			->where($db->quoteName('folder') . ' = ' . $db->quote('system'))
> +			->where($db->quoteName('element') . ' = ' . $db->quote('languagefilter'));
> +		$db->setQuery($query);
> +
> +		try
> +		{
> +			$result = (int) $db->loadResult();
> +		}
> +		catch (RuntimeException $e)
>
> can you use proper exception JDatabaseExceptionExecuting instead of
> RuntimeException
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/14654#pullrequestreview-27289757>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABPH8cdD7DAO8SXC1zk9Y3RDi-JHw8Blks5rmQNLgaJpZM4MelfG>
> .
>

2017-03-16 10:21 UTC, infograf768 commented on administrator/components/com_associations/helpers/associations.php
> +	 * @since   3.6.0
I guess deploy_version or 3.7.0

2017-03-16 10:24 UTC, alikon commented
i've just looked at file diff, and yes can be made on a separate pr

2017-03-16 10:25 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 356db4f2983311a47a03e2cbe0041fbb15d61c22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14654">issues.joomla.org/tracker/joomla-cms/14654</a>.</sub>

2017-03-16 10:30 UTC, infograf768 commented
don't we have another PR where the same string is changed?
https://github.com/joomla/joomla-cms/pull/14623
which already has conflicts

2017-03-29 08:43 UTC, brianteeman commented
@infograf768 I have added the change to the string from the other PR into this one as well to remove merge conflicts and will remove it from that PR too - so that this one can be merged.

2017-03-30 09:52 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_associations.ini
> +COM_ASSOCIATIONS_ERROR_NO_ASSOC="The Multilingual Associations component can't be used if the site is not set as multilingual and/or Associations is not enabled in the <a href="_QQ_"%s"_QQ_">Language
Please remove extraneous spaces at the end of the string value.
I guess also you can already use `\"` instead of `"_QQ_"` for new strings

2017-04-18 07:09 UTC, infograf768 approved these changes

2017-04-18 10:04 UTC, zero-24 requested changes
Please use since 3.7.1 :) thanks

2017-04-18 10:23 UTC, brianteeman commented
@zero-24 done

2017-04-18 11:32 UTC, zero-24 approved these changes

2017-04-18 11:32 UTC, zero-24 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14654">issues.joomla.org/tracker/joomla-cms/14654</a>.</sub>

2017-05-09 16:55 UTC, jreys commented
I have tested this item :white_check_mark: successfully on 177e1ede2dcc0bf591adbc3004433d8a833179c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14654">issues.joomla.org/tracker/joomla-cms/14654</a>.</sub>

2017-05-09 18:40 UTC, infograf768 commented
it is already rtc for 3.7.2 😄

2017-05-22 18:54 UTC, merged

2017-05-22 18:56 UTC, brianteeman commented
Thanks