Add CSRF token for Ajax
joomla/joomla-cms pull request #14952
Opened 2017-03-28 01:15 UTC by asika32764

### Summary of Changes

An idea inspired by Laravel when I'm writing drag and drop installation in https://github.com/joomla/joomla-cms/pull/14924

Add CSRF token to head as a meta tag, so we can get the value by Javascript.

Use `JHtml::_('form.csrf')` to add `<meta name="csrf-token" content="14044d42e0488e8362c2ee40f3dcf2d1" />` in `<head>`

Then we can select this tag to get value:

``` js
var token = jQuery('meta[csrf-token]').val();
```

Also we can use `X-Csrf-Token: xxx` header to validate token.

`JHtml_('jquery.token')` help us add header to `ajaxSetup` so we can auto inject token in every `$.ajax()` calls.

``` js
;(function ($) {
	$.ajaxSetup({
		headers: {
			'X-Csrf-Token': $('meta[name="csrf-token"]').attr('content')
		}
	});
})(jQuery);
```

### Testing Instructions

I rewrite sendmail test in configuration to use this pattern, just send a test.

![global_configuration_-_joomladev_-_administration](https://cloud.githubusercontent.com/assets/1639206/24384490/c1502b94-1396-11e7-9e77-fccc3c9209cb.jpg)

If we remove `JHtml::_('jquery.token')` in `administrator/components/com_config/view/application/tmpl/default_mail.php`, will get fail result.

![global_configuration_-_joomladev_-_administration](https://cloud.githubusercontent.com/assets/1639206/24384524/fd751904-1396-11e7-8094-a52484ddd334.jpg)

2017-03-28 02:12 UTC, mbabker commented on libraries/joomla/session/session.php
> +		$csrf = isset($_SERVER['HTTP_X_CSRF_TOKEN']) ? $_SERVER['HTTP_X_CSRF_TOKEN'] : null;
`$app->input->server->get()` works here.

2017-03-28 10:39 UTC, dgt41 commented
@asika32764 can you add the post header also to core Joomla.request ?
https://github.com/joomla/joomla-cms/blob/staging/media/system/js/core-uncompressed.js#L792-L888

2017-03-28 10:44 UTC, asika32764 commented
OK, but what class and method should we locate the php code? `JHtmlBehavior` ???

2017-03-28 10:47 UTC, dgt41 commented
`JHtmlForm::csrf()`is fine, you already oded that part

2017-03-28 10:49 UTC, asika32764 commented
I mean, the `core.js` is included by `JHtmlBehavior::core()` but it has no not added CSRF token yet.

Should I call `JHtmlForm::csrf()` also in `JHtmlBehavior::core()` or add a new method `JHtmlBehavior::token()` similar as `JHtmlJquery::token()` which I wrote in this PR?

2017-03-28 10:53 UTC, dgt41 commented
Personally I would extend the `JHtmlBehavior::core()` so everything comes up magically...

2017-03-28 10:56 UTC, asika32764 commented
OK. I just think there may be someone want to use core.js but do not hope CSRF auto inject to `<head>`.

But I will follow your comment first if there has no opinion from others.

2017-03-28 12:02 UTC, asika32764 commented
Done. Please test with this code in console:

``` js
Joomla.request({
  url: '.',
  method: 'POST',
  data: {foo: 'bar'}
});
```

![articles_-_joomladev_-_administration](https://cloud.githubusercontent.com/assets/1639206/24403857/5c1b0432-13f1-11e7-850a-333e3a17df23.jpg)

I'm wonder our `request` method do not support `PUT`, `PATCH` and `DELETE`???

2017-03-28 12:09 UTC, brianteeman commented on media/system/js/core-uncompressed.js
> +					xhr.setRequestHeader('X-Csrf-Token', document.querySelector('meta[name="csrf-token"]').getAttribute('content'));
I am not 100% certain but from what I can see this should be 
'X-CSRF-Token'

Note the capitalisation

2017-03-28 12:57 UTC, dgt41 commented
> I'm wonder that our request method does not support PUT, PATCH and DELETE???

Maybe forcing this behaviour only to POST is not a great idea...

2017-03-28 13:12 UTC, asika32764 commented on media/system/js/core-uncompressed.js
> +					xhr.setRequestHeader('X-Csrf-Token', document.querySelector('meta[name="csrf-token"]').getAttribute('content'));
Yes you're right, since header is case insensitive but It is often use `CSRF` not `Csrf` in header.

2017-03-28 13:18 UTC, asika32764 commented
> Maybe forcing this behaviour only to POST is not a great idea...

I think we can leave this issue for J4 since JInput in J3 is not good at handling pure PUT, PATCH and DELETE data.

2017-03-28 13:39 UTC, mbabker commented
JInput handles them just fine.  The magic getter in JInput looks for superglobals or subclasses, and there isn't something matching that definition for any request method except GET and POST.

2017-03-28 13:56 UTC, asika32764 commented
Maybe I'm miss something but to my knowledge, PUT request data must read by `fopen('php://input')`,  it cannot get from `$_PUT`. But JInput didn't handle it. (I only see `JInputJSON` did it)

2017-03-28 14:02 UTC, mbabker commented
Right, so we already cover that case.  GET and POST requests have corresponding superglobals, the other request types don't, and I don't think we should be changing JInput's magic getter to proxy a request method into another object instance personally.

The thing that falls over is if you blindly try to do `$input->$method->get()` without validating `$method` (which, sadly, core actually does this).  IMO it's not hard to do something like this:

```php

$input = JFactory::getApplication()->input;
$method = $input->getMethod();

if ($method === 'PUT') {
    $data = $input->json->get('foo');
elseif (in_array($method, ['GET', 'POST'])) {
    $data = $input->$method->get('foo');
} else {
    throw new InvalidArgumentException(sprintf('The "%s" request method is not supported by this route, please send a GET, POST, or PUT request.', $method), 405);
}
```

2017-03-28 14:12 UTC, asika32764 commented
Actually I think `$input->put->get()` is a nice pattern since the main subject of `JInput` is to help us integrate all system INPUT in one interface. 

Maybe add a `JinputFormdata` to parse `php://input` instead get value from `$_REQUEST`. [This is what I'm working in my framework](https://github.com/ventoviro/windwalker/blob/master/src/IO/FormDataInput.php#L96-L113)

But I think it is too big subject for this PR, let's leave this issue for the Framework design, not discussion here.

2017-03-29 09:42 UTC, Fedik commented on libraries/cms/html/form.php
> +		$doc->setMetaData($name, JSession::getFormToken());
I think, here we could use the "script options" feature, without extra metatags, and so without extra DOM query,
see [Adding_the_options_to_your_JavaScript_code](https://docs.joomla.org/J3.x:Adding_JavaScript_and_CSS_to_the_page#Adding_the_options_to_your_JavaScript_code)

2017-03-29 09:44 UTC, Fedik commented on media/system/js/core-uncompressed.js
> +				if (document.querySelector('meta[name="csrf-token"]').getAttribute('content')) {
`document.querySelector('meta[name="csrf-token"]')` return `null` when nothing found, and whole code fail

2017-03-29 13:42 UTC, asika32764 commented on libraries/cms/html/form.php
> +		$doc->setMetaData($name, JSession::getFormToken());
It's seems better then Laravel, I will try implement it later.

2017-03-30 00:17 UTC, asika32764 commented
Here I have a security concern, if we auto inject CSRF into all request, can there be a case that developer or 3rd extensions send a request with CSRF token to outside of Joomla without aware?

2017-04-01 06:40 UTC, asika32764 commented
Use script option to handle CSRF

2017-05-27 14:43 UTC, mbabker requested changes

2017-05-27 14:43 UTC, mbabker commented on libraries/cms/html/form.php
> +	public static function token($attribs = null)
`token(array $attribs = array()`

The default value might as well be the correct data type.

2017-05-27 14:43 UTC, mbabker commented on libraries/cms/html/form.php
> +		if (is_array($attribs))
Then this can become a `!empty($attribs)` check

2017-05-27 14:43 UTC, mbabker commented on libraries/cms/html/form.php
> +	 * Add CSRF form token to <head> meta that developers can get it by Javascript.
Since this isn't adding a meta tag anymore the summary can be updated.

2017-05-27 14:52 UTC, mbabker approved these changes

2017-07-29 10:38 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on f9e0372723112010510dd52458c3b1f924e678c1<br /><br />After installing a new site based on that branch here the send mail button still works. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14952">issues.joomla.org/tracker/joomla-cms/14952</a>.</sub>

2017-07-29 11:18 UTC, franz-wohlkoenig commented
@zero-24 can this be local tested (mamp) using Mailer "php Mail"?

2017-07-29 11:25 UTC, zero-24 commented
I don't know about mamp but in xampp there is a folder where all mails get saved. Just check how it works before the patch. As it should work like the same after the patch

2017-07-29 11:32 UTC, franz-wohlkoenig commented
Without Patch using Default-Path "/usr/sbin/sendmail" get after Click on Button "Send Test Mail" `Error Test mail could not be send`.

If i get same Result using PR is this a successfully Test?

2017-07-29 11:36 UTC, zero-24 commented
hmm IMO it would better to do a working test.

2017-07-29 11:37 UTC, franz-wohlkoenig commented
thanks, hopefully another one will test.

2017-07-29 11:38 UTC, asika32764 commented
If you are using MAMP in MacOS, I guess select the `PHP Mail` option may work.

2017-07-29 11:49 UTC, franz-wohlkoenig commented
@asika32764 none of the 3 works, this is from "PHP Mail":
![bildschirmfoto 2017-07-29 um 13 47 55](https://user-images.githubusercontent.com/8235763/28744607-b480ecb2-7464-11e7-89ac-427f5daa0324.jpg)

2017-07-29 16:17 UTC, zero-24 commented
@asika32764 Isn't the above error coming from the local envoirment? As this should have nothing todo with the patch here?

2017-07-29 16:21 UTC, franz-wohlkoenig commented
i haven't applied the PR, so this Notice and Errors don't come from PR.

2017-07-29 16:28 UTC, asika32764 commented
I think

2017-07-29 16:30 UTC, asika32764 commented
A mistake that deleted the branch from forked repo, just restored it.

2017-07-29 16:33 UTC, asika32764 commented
@franz-wohlkoenig Actually I think it is successfully test if it return same message before and after patch.

2017-07-29 16:52 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on f9e0372723112010510dd52458c3b1f924e678c1<br /><br />Got same Messages with PR as without.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14952">issues.joomla.org/tracker/joomla-cms/14952</a>.</sub>

2017-07-29 16:52 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-07-29 16:57 UTC, merged

2018-11-12 10:48 UTC, pawan0446 commented
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14952">issues.joomla.org/tracker/joomla-cms/14952</a>.</sub>