Issue#15189
joomla/joomla-cms pull request #15258
Opened 2017-04-12 14:30 UTC by Supun94

Pull Request for Issue #15189 .

### Summary of Changes
Installation freezing issue happens if user has not enabled InnoDB support in database platform. During the installation time check if InnoDB support is enabled or not. If disabled display an Error message.

### Testing Instructions

- Disable InnoDB support in database platform and try 'Database Configuration' step and test.
- Enable InnoDB support and try the same step. 

### Expected result

- If disabled the InnoDB support you'll get an Error message 'You need to enable default InnoDB support in  your database platform' and stay in the 'Database Configuration' step. 
- If enabled the InnoDB support go to the next page. 

### Actual result
If InnoDB support is disabled in database platform, installation freezing issue (#15189) happened. 

### Documentation Changes Required
None

2017-04-12 14:33 UTC, zero-24 commented
Hi @Supun94 can you take a look into the drone report: http://213.160.72.75/joomla/joomla-cms/2665 ?

2017-04-12 14:35 UTC, alikon commented on installation/model/database.php
> +			$db->setQuery("SELECT SUPPORT FROM INFORMATION_SCHEMA.ENGINES WHERE ENGINE = 'InnoDB'");
this query has no meanings in db's  like postgresql, mssql

2017-04-12 14:35 UTC, mbabker requested changes

2017-04-12 14:35 UTC, mbabker commented on installation/model/database.php
> +			$db->setQuery("SELECT SUPPORT FROM INFORMATION_SCHEMA.ENGINES WHERE ENGINE = 'InnoDB'");
This needs to conditionally run for MySQL engines only.  Otherwise you will break the install for the other supported database engines.

2017-04-12 14:36 UTC, alikon commented on installation/model/database.php
> +			$db->setQuery("SELECT SUPPORT FROM INFORMATION_SCHEMA.ENGINES WHERE ENGINE = 'InnoDB'");
exaclty

2017-04-12 14:39 UTC, brianteeman commented on installation/language/en-GB/en-GB.ini
> +INSTL_DATABASE_ENABLE_INNODB="You need to enable default InnoDB support in  your database platform"
remove the double space and add a period at the end

2017-04-12 15:15 UTC, C-Lodder commented on installation/model/database.php
> +		catch (RuntimeException $e){
The `{` here needs to go on a new line.

2017-04-12 15:21 UTC, Supun94 commented on installation/model/database.php
> +			$db->setQuery("SELECT SUPPORT FROM INFORMATION_SCHEMA.ENGINES WHERE ENGINE = 'InnoDB'");
@mbabker @alikon Done the conditionally check before the query.

2017-04-12 15:22 UTC, Supun94 commented on installation/language/en-GB/en-GB.ini
> +INSTL_DATABASE_ENABLE_INNODB="You need to enable default InnoDB support in  your database platform"
Fixed it @brianteeman

2017-04-12 15:33 UTC, Supun94 commented on installation/model/database.php
> +		catch (RuntimeException $e){
Fixed it @C-Lodder

2017-04-12 15:50 UTC, Supun94 commented
@zero-24 fixed it. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15258">issues.joomla.org/tracker/joomla-cms/15258</a>.</sub>

2017-04-13 13:03 UTC, mbabker approved these changes

2017-04-15 14:51 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on 6da771e8dff6006ee1e7be08c1a2e244331336b8<br /><br />Works good for me.

For anyone who wants to test this to enable myisam e.g. on xampp you need to add `default-storage-engine = myisam` in the mysql configuration file: http://stackoverflow.com/questions/3050492/how-can-i-set-default-storage-engine-used-by-mysql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15258">issues.joomla.org/tracker/joomla-cms/15258</a>.</sub>

2017-04-15 17:54 UTC, csthomas commented
I have tested this item :red_circle: unsuccessfully on 6da771e8dff6006ee1e7be08c1a2e244331336b8<br /><br />Description of PR is OK but php code is wrong.

There is two different things:
- support for innoDB (in general)
- default storage engine as innoDB


I installed Joomla on localhost (mysql 5.7) with `default-storage-engine  = myisam` without patch without any problems.
After patched I can not install Joomla anymore with mentioned configuration.

This PR should check if support for innoDB is enabled but
now php code checks if default storage engine is set as innoDB.

Solution, replace:
`if ($value != 'DEFAULT')`
to:
`if ($value == 'NO')`

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15258">issues.joomla.org/tracker/joomla-cms/15258</a>.</sub>

2017-04-15 17:57 UTC, csthomas commented
Screen-shot:
![obraz](https://cloud.githubusercontent.com/assets/9054379/25065762/7015e006-2215-11e7-8143-c6455e6a4ef0.png)

There is also engine MEMORY which support is required.

2017-04-19 04:10 UTC, Supun94 commented
Thanks @csthomas !! Done the changes.

2017-04-19 07:34 UTC, csthomas commented
I have tested this item :white_check_mark: successfully on b8a0cd7a17c50f1fe1e04c001ff7cec70a197ca5<br /><br />I tested only when InnoDB is supported as not default engine and it is OK.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15258">issues.joomla.org/tracker/joomla-cms/15258</a>.</sub>

2017-05-27 07:36 UTC, franz-wohlkoenig commented
@zero-24 can you please retest?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15258">issues.joomla.org/tracker/joomla-cms/15258</a>.</sub>

2017-08-23 09:45 UTC, csthomas commented
May be there is someone who can do Joomla test installation on mysql with at least InnoDB enabled (by default).

2018-05-08 22:00 UTC, brianteeman commented
I tried to test but I only have mysql 5.7 and it is not possible to disable innodb with 5.7

2018-06-08 15:47 UTC, csthomas commented
@brianteeman IMO is enough to make a review and check if it does not break anything on mysql with enabled InnoDB.

Otherwise, I do not see any future of this PR.

2018-06-08 15:50 UTC, brianteeman commented
Perhaps but I will never personally mark that I have tested something and it is working unless I can replicate  the problem

2018-06-08 15:56 UTC, csthomas commented
On mysql 5.7, it can not be replicated. InnoDB can be disabled on mysql <=5.6.21 only.

https://dev.mysql.com/doc/refman/5.6/en/innodb-turning-off.html

2018-06-08 16:50 UTC, brianteeman commented
and thats exactly why i cannot test it

2019-07-01 22:32 UTC, HLeithner commented
Hi @Supun94,

thanks for the time you invested into this PR but I think there are some flaws in it (ex. works only for mysql driver and not for mysqli and pdo). Anyway in the meantime the mysql version in which you can disable InnoDB is EOL. That means check this makes less sense anymore.
But if you like to bring your PR up to date and support the other mysql drivers we can reevaluate it.

In the meantime I'm closing this PR, you can reopen it anytime.

thx for trying to make Joomla! more robust.

2019-07-01 22:32 UTC, closed without merging