Added Redis session handler support
joomla/joomla-cms pull request #15390
Opened 2017-04-18 18:32 UTC by jdolinski

Pull Request for Issue # .

### Summary of Changes
Added support for Redis session handling.

### Testing Instructions
Modify the configuration.php file and include the following lines:
```
  public $session_redis_server_host = 'redis-server-url';
  public $session_redis_server_port = '6379';
```

### Expected result
Sessions are stored in Redis and slight performance improvement when used in conjunction with Redis Cache.

### Actual result
Session management is done by Redis and will work in a clustered environment without using database session handler.

### Documentation Changes Required
Modify configuration.php
```
  public $session_redis_server_host = 'redis-server-url';
  public $session_redis_server_port = '6379';
```

2017-04-18 18:47 UTC, jdolinski commented
[Database session handling and Redis cache] (https://snag.gy/qiRb5m.jpg)
[Redis session handling and cache] (https://snag.gy/gi6Ih9.jpg)
[Redis session hits, looping 50 users across website pages](https://snag.gy/Ie4x9j.jpg)

2017-07-24 02:49 UTC, mbabker approved these changes

2017-07-29 17:23 UTC, mbabker commented
I have tested this item :white_check_mark: successfully on a05a4e554f068498e47ad4b2b5e65aca64ddc7e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15390">issues.joomla.org/tracker/joomla-cms/15390</a>.</sub>

2017-07-29 17:25 UTC, mbabker commented
If you're a Mac user running Homebrew for PHP, this is actually pretty easy to test.

```sh
brew install redis
brew install phpxx-redis (replace xx with the PHP version you're using)
brew services start redis
```

Then get into global config, change the session handler (default settings are fine), save, and validate that things work using Redis as a session backend.

I'm comfortable merging based on my test, but it'd be nice if someone else could also do so.

2017-07-30 09:34 UTC, alikon requested changes

2017-07-30 09:34 UTC, alikon commented on libraries/joomla/session/storage/redis.php
> +			'port' => $config->get('session_redis_server_port', 11211),
why 11211 ?
shouldn't be 6379

2017-07-30 09:38 UTC, alikon commented
I have tested this item :white_check_mark: successfully on a05a4e554f068498e47ad4b2b5e65aca64ddc7e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15390">issues.joomla.org/tracker/joomla-cms/15390</a>.</sub>

2017-07-30 20:23 UTC, mbabker commented on libraries/joomla/session/storage/redis.php
> +			'port' => $config->get('session_redis_server_port', 11211),
Probably bad copy/paste, I fixed it.

2017-07-30 20:23 UTC, mbabker commented
> but we still need to manage situation like mod_status that directly access to the #__session table

It's fine for now because of the app code that arbitrarily writes stuff to the session table even if the database session handler isn't in use.

2017-07-30 20:46 UTC, merged