[SQL] - remove triplicated index from #__user_keys
joomla/joomla-cms pull request #15509
Opened 2017-04-24 15:19 UTC by alikon

### Summary of Changes
removed not necessary and redundant index from `#__user_keys ` table on field `series`

```
  UNIQUE KEY `series_2` (`series`),
  UNIQUE KEY `series_3` (`series`),
```

2017-04-24 15:32 UTC, zero-24 commented
don't we need to add that to the update scripts too?

2017-04-24 15:37 UTC, alikon commented
yes, i'll add the update script part too when @home ;)

2017-04-24 15:37 UTC, zero-24 commented
:+1:

2017-04-24 19:42 UTC, waader commented on installation/sql/sqlazure/joomla.sql
>  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
Line 2909: there should be a semicolon

2017-04-25 05:52 UTC, alikon commented on installation/sql/sqlazure/joomla.sql
>  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
you are right , fixed
thanks

2017-04-25 10:39 UTC, waader commented
I have tested this item :white_check_mark: successfully on a934f412270804a8d49cf1becef970847215c4f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15509">issues.joomla.org/tracker/joomla-cms/15509</a>.</sub>

2017-05-27 07:34 UTC, franz-wohlkoenig commented
@alikon can you give Test Instructions for non-Technicals or is this PR for Technicals?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15509">issues.joomla.org/tracker/joomla-cms/15509</a>.</sub>

2017-06-07 09:07 UTC, alikon commented
from phpmyadmin look at `#__user_keys` indexes you'll see `series_2, series_2`
apply the patch and reinstall
from phpmyadmin the  `#__user_keys` table have only one index on the field `series`

2017-06-07 09:14 UTC, franz-wohlkoenig commented
thanks @alikon, will look into it.

2017-06-07 09:20 UTC, franz-wohlkoenig commented
how to get `series_2`? Field `series` in Table `#__user_keys` is empty.

2017-06-07 10:28 UTC, Bakual commented
> how to get series_2? Field series in Table #__user_keys is empty.

It's not a field, it's the index of the "series" field.
You can populate the field by logging in while having the "Remember Me" checkbox enabled.

2017-06-07 10:42 UTC, franz-wohlkoenig commented
Thanks @Bakual. With and -out PR and relogin got:
![bildschirmfoto 2017-06-07 um 12 40 55](https://user-images.githubusercontent.com/8235763/26874633-a61ee57a-4b7e-11e7-9353-0a7cb1c20987.jpg)

2017-06-10 18:34 UTC, wojsmol commented
@franz-wohlkoenig Aplly PR then run database  fix and see in phpmyadmin that ypu don't have series_2 and series_3 indexes.

2017-06-11 05:13 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 26b65b9c58eea1c5f6597d8ed1df7ca3e3afa2ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15509">issues.joomla.org/tracker/joomla-cms/15509</a>.</sub>

2017-06-11 05:14 UTC, franz-wohlkoenig commented
@waader can you please retest?

2017-06-28 13:01 UTC, csthomas commented on installation/sql/sqlazure/joomla.sql
> -) ON [PRIMARY];
I tested mysql and postgresql with success (install, upgrade) and mssql upgrade with success too. 

Installation on mssql failed.

Please correct above line.
```
Error
[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot find the object "#__user_keys" because it does not exist or you do not have permissions.
[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near 'PRIMARY'.
```
`) ON [PRIMARY];` - IMO this line should stay.

2017-06-28 16:35 UTC, alikon commented on installation/sql/sqlazure/joomla.sql
> -) ON [PRIMARY];
ops :flushed:
fixed i hope, 
please re-test on mssql :wink:

2017-06-29 20:20 UTC, csthomas commented
I have tested this item :white_check_mark: successfully on eb605bef437c300aea3b4413db09551b99e0d23e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15509">issues.joomla.org/tracker/joomla-cms/15509</a>.</sub>

2017-06-29 20:34 UTC, csthomas commented
I make a mistake when I test. This is still a problem with installation on mssql.

2017-06-29 20:39 UTC, csthomas requested changes

2017-06-29 20:39 UTC, csthomas commented on installation/sql/sqlazure/joomla.sql
> +)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];
Please revert above line.

2017-06-29 20:39 UTC, csthomas commented on installation/sql/sqlazure/joomla.sql
Add to this line:
```) ON [PRIMARY];``` and remove `;` from above

2017-06-30 10:59 UTC, alikon commented
Can you make the sqlrv changes to my branch wich is public, and  i
currently don't have a. sqlsrv instance to test, thanks ;)

On 29 Jun 2017 10:39 pm, "Tomasz Narloch" <notifications@github.com> wrote:

*@csthomas* requested changes on this pull request.
------------------------------

In installation/sql/sqlazure/joomla.sql
<https://github.com/joomla/joomla-cms/pull/15509#discussion_r124906682>:

>
 CREATE NONCLUSTERED INDEX "user_id" ON "#__user_keys"
 (
   "user_id" ASC
-)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
DROP_EXISTING = OFF, ONLINE = OFF);
+)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];

Please revert above line.
------------------------------

In installation/sql/sqlazure/joomla.sql
<https://github.com/joomla/joomla-cms/pull/15509#discussion_r124907076>:

> @@ -2906,21 +2906,12 @@ CREATE TABLE "#__user_keys" (
  CONSTRAINT "#__user_keys$series" UNIQUE NONCLUSTERED
 (
   "series" ASC
-)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY
= OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
- CONSTRAINT "#__user_keys$series_2" UNIQUE NONCLUSTERED
-(
-  "series" ASC
-)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY
= OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
- CONSTRAINT "#__user_keys$series_3" UNIQUE NONCLUSTERED
-(
-  "series" ASC
-)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY
= OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
-) ON [PRIMARY];
+)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY
= OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];


Add to this line:
) ON [PRIMARY]; and remove ; from above

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/pull/15509#pullrequestreview-47244762>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AALFsch2KaLq447xDQrKtLxtN2RuWWs8ks5sJAuagaJpZM4NGUK9>
.

2017-07-01 13:35 UTC, csthomas commented
I have tested this item :white_check_mark: successfully on 9255ee38e54538d0bf6f59e52da8e9d3a595d717<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15509">issues.joomla.org/tracker/joomla-cms/15509</a>.</sub>

2017-08-23 09:35 UTC, csthomas commented
Is there any chance it will be merged? 
It was tested on 3.7.3.
It's trivial but stuck for a long time.

2017-08-23 14:15 UTC, alikon commented
it seems that you still request a change
![test](https://user-images.githubusercontent.com/181681/29620442-37571a7c-881e-11e7-99ef-8e27aaa879dc.PNG)


and it still  have  only 1  test  

> Human Test Results: 1 Successful 0 Failed. 

so don't get the RTC label

2017-08-23 14:21 UTC, csthomas approved these changes

2017-08-23 14:26 UTC, csthomas commented
I did not realize that I should click to approve this, after making changes.

2018-01-08 18:47 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 9255ee38e54538d0bf6f59e52da8e9d3a595d717<br /><br />Tested with MySQL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15509">issues.joomla.org/tracker/joomla-cms/15509</a>.</sub>

2018-01-08 19:18 UTC, alikon commented
can we have an RTC status? 
and 3.8.4 milestone ?

2018-01-08 19:27 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-01-08 19:28 UTC, franz-wohlkoenig commented
@brianteeman can please you set the Milestone?

2018-01-09 00:34 UTC, brianteeman commented
i will leave it to @mbabker to set the milestone as i dont understand it enough to know if it is a bug fix or not

2018-01-15 20:00 UTC, alikon commented
@joomla/cms-maintainers any chance for 3.8.4 ?

2018-01-15 20:18 UTC, mbabker commented
From everything I can tell it's just human error it was triplicated unless someone can find something in https://developer.joomla.org/joomlacode-archive/issue-31561.html https://github.com/joomla/joomla-cms/pull/2101 or https://github.com/joomla/joomla-cms/pull/1745 explaining the triplication (note it's not in the old security tracker either where this was discussed before becoming a public patch).

2018-01-15 21:04 UTC, alikon commented
really curious how the same (triplicated) index can be tied with security :smile:

2018-01-16 22:53 UTC, merged