Fix Language parsing when parse_ini_file disabled
joomla/joomla-cms pull request #15620
Opened 2017-04-27 11:09 UTC by PhilETaylor

closes #15587

Use sensible code available in FOF to process ini files when moronic web hosts disable parse_ini_file in php.ini

Please test

2017-04-27 11:13 UTC, dgt41 commented
@PhilETaylor shouldn't this be conditional, if php_ini_parse not exist then use FOF?

2017-04-27 11:15 UTC, PhilETaylor commented
FOF does that check! 

https://github.com/joomla/joomla-cms/blob/91749f845dcf20e097801ecd75da8e4665075a18/libraries/fof/utils/ini/parser.php#L28

2017-04-27 11:15 UTC, PhilETaylor commented
I know Travis is unhappy, will look at that in a moment, but this fix fixes the brokenness

2017-04-27 11:19 UTC, dgt41 commented
Still, this will be faster (one less file, less memory for the good hosts):
```php
		$isMoronHostFile = !function_exists('parse_ini_file');

		if ($isMoronHostFile)
		{
         		$strings = FOFUtilsIniParser::parse_ini_file($filename, true);
		}
		else
		{
			$strings = @parse_ini_file($filename);
		}
```

2017-04-27 11:55 UTC, zero-24 commented
Should we really create another dependencey to FOF where we try to remove it at other places?

2017-04-27 11:57 UTC, PhilETaylor commented
Unless you want to write your own pure PHP implementation of parse_ini_file quickly to resolve the issue... 

FOFUtilsIniParser is nothing but a wrapper to parse_ini_file_php

There is no point in pulling parse_ini_file_php out into another file, and duplicating code in the core...

2017-04-27 11:59 UTC, PhilETaylor commented
Actually, this is the only place we do a parse_ini_file anyway, let me rework it then...

2017-04-27 12:09 UTC, csthomas commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
Why we can not use the old way before #13407?
```php
return @parse_ini_string(file_get_contents($filename));
```

2017-04-27 12:11 UTC, PhilETaylor commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
No idea - I'm assuming that there was a valid reason that they stopped using parse_ini_string ...

2017-04-27 12:12 UTC, Bakual commented
Using FOF certainly isn't right.

2017-04-27 12:13 UTC, zero-24 commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
As long as we restore:

```
	$contents = file_get_contents($filename);
	$contents = str_replace('_QQ_', '"\""', $contents);
	$strings = @parse_ini_string($contents);
```

That should do the trick.

Maybe add the is_array check too.

2017-04-27 12:15 UTC, PhilETaylor commented
Well it works. If someone cares to lay out exactly what "fix" they would prefer to merge, it can be coded... 

I was not involved with the breaking change, I was just fed up with 60+ comments of people saying "it doesnt work" in #15587 so I looked, and within seconds found a solution... 

How you want that solution cemented into the core, well it appears anyway but the ways I chose..

2017-04-27 12:15 UTC, PhilETaylor commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
but that reverts the whole point of #13407 right?

2017-04-27 12:16 UTC, csthomas commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
IMO the idea was improve performance. Please replace above line as I suggested.

2017-04-27 12:16 UTC, zero-24 commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
No just as fallback when the new code don't work for b/c?

2017-04-27 12:18 UTC, csthomas commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
This `$contents = str_replace('_QQ_', '"\""', $contents);` is not needed. I tested on php7.0

2017-04-27 12:22 UTC, PhilETaylor commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
PR Code updated

2017-04-27 12:25 UTC, zero-24 commented
@PhilETaylor 

> remove QQ replacement (apparently its not needed)

why do you think so?

parse_ini_file can do that: http://php.net/manual/en/function.parse-ini-file.php

> Constants may also be parsed in the ini file so if you define a constant as an ini value before running parse_ini_file(), it will be integrated into the results. 

But i can not find something like that for parse_ini_string: http://php.net/manual/en/function.parse-ini-string.php

I have not tested this yet but maybe you have..

2017-04-27 12:27 UTC, PhilETaylor commented
> why do you think so?

Cause "he said so" :-) https://github.com/joomla/joomla-cms/pull/15620#discussion_r113680858

I can put it back?

2017-04-27 12:28 UTC, Bakual commented on libraries/joomla/language/language.php
> +			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
Obviously just using `parse_ini_file` is simpler than using `parse_ini_string` and `file_get_contents`. That's probably the main reason it has been changed.
And as you can read in that PR, there is some automatic handling of _QQ_

2017-04-27 12:28 UTC, zero-24 commented
As i have said i have not checked it yet and i have not saw that comment above. Needs to be tested.

2017-04-27 12:29 UTC, Bakual commented
Honestly, just revert #13407.

2017-04-27 12:30 UTC, PhilETaylor commented
I think pretty much that is where I have got to :)

2017-04-27 12:30 UTC, zero-24 commented
@Bakual i think the rest (array + renaming a var) can stay from that PR? Just that str_replace needs to be checked i guess.

2017-04-27 12:42 UTC, PhilETaylor commented
@mbabker

2017-04-27 12:43 UTC, PhilETaylor commented
if we are removing the requirement for Joomla to have parse_ini_file enabled, then we can remove this check too ? https://github.com/joomla/joomla-cms/pull/15619/files

2017-04-27 12:49 UTC, brianteeman commented
You absolutely can not remove the qq processing!!

2017-04-27 12:57 UTC, mbabker commented
Do not revert #13407

The only thing you need to do is basically `if parse_ini_file is usable then use it otherwise use our old way which supports broken INI files`

1) We need to stop allowing broken crap to work in our core APIs
2) The simplest option is to use the simplest function if available, since apparently hosts are 3 steps past moronic we can have a sensible fallback (i.e. the old code which has been proven to work with broken files)
3) The fact that this project is still so reluctant to accept valid third party solutions is really getting out of hand.  We don't have the developers to write everything ourselves because we keep chasing everyone with half an ounce of skill away.

2017-04-27 14:45 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on dc00875cdbaa4f13e66a6443c3ef646457a7f731<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15620">issues.joomla.org/tracker/joomla-cms/15620</a>.</sub>

2017-04-27 14:46 UTC, infograf768 commented
For testers:
add 
`disable_functions = parse_ini_file`
on your php.ini file
Stop and restart server.

2017-04-27 14:47 UTC, PhilETaylor commented
> Stop and restart server.

Or your php-fpm process, depending on how you are running PHP :)

2017-04-27 15:10 UTC, csthomas commented
Constants for `parse_ini_string()` are supported in php version 5.3.2.
I have checked it at https://3v4l.org/#preview

Constants are not supported in hhvm 3.19.1 and lower at all for both (`parse_ini_file`, `parse_ini_string`)

I tested with code:
```php
echo phpversion() . "\n";
define('__QQ__', " WORKS ");
print_r(parse_ini_string('A="IT"__QQ__"GREATE!"'));
print_r(parse_ini_file(__DIR__ . '/test.ini'));
```

For hhvm I got:
```
5.6.99-hhvm
Array
(
    [A] => IT__QQ__GREATE!
)
Array
(
    [A] => IT__QQ__GREATE!
)
```

2017-04-27 15:13 UTC, PhilETaylor commented
Does Joomla officially support HHVM ? (https://downloads.joomla.org/technical-requirements)

2017-04-27 15:34 UTC, csthomas commented
If you will add unittest for `__QQ__` then you will have to:)

2017-04-27 15:49 UTC, Bakual commented
Afaik currently unit tests run on HHVM. But the CMS itself not necessary. To my knowledge we don't support it yet officially.

2017-04-27 22:06 UTC, wilsonge requested changes

2017-04-27 22:06 UTC, wilsonge commented on tests/unit/suites/libraries/joomla/language/JLanguageTest.php
> +		 * syntax error, unexpected BOOL_TRUE in
in.........

2017-04-27 22:09 UTC, PhilETaylor commented on tests/unit/suites/libraries/joomla/language/JLanguageTest.php
> +		 * syntax error, unexpected BOOL_TRUE in
in....  whatever file and whatever path you are running the unit testing suite on, the path is different in travis/my machine but basically its because bad.ini has bad ini data in it... which is expected...

2017-04-28 12:38 UTC, csthomas commented on tests/unit/suites/libraries/joomla/language/JLanguageTest.php
> +		 * syntax error, unexpected BOOL_TRUE in
Coluld this https://github.com/PhilETaylor/joomla-cms/pull/1 can be useful?

2017-04-28 12:41 UTC, mbabker commented on tests/unit/suites/libraries/joomla/language/JLanguageTest.php
> +		 * syntax error, unexpected BOOL_TRUE in
TBH, I don't think it's even worth the effort to support HHVM anymore.  Seems it is losing traction with the PHP community and big players are dropping support for it because apparently it doesn't have feature parity with PHP core starting with 5.6.

2017-04-28 12:44 UTC, csthomas commented on tests/unit/suites/libraries/joomla/language/JLanguageTest.php
> +		 * syntax error, unexpected BOOL_TRUE in
I do not care about support HVVM but I want to force unittest for `_QQ_`.

2017-04-28 15:25 UTC, csthomas commented on tests/unit/suites/libraries/joomla/language/JLanguageTest.php
> +		 * syntax error, unexpected BOOL_TRUE in
@mbabker About my proposed changes. Would it be better to remove lines with hhvm support and allow the unit test on hhvm to fail? Or better way is to not add a unit test for `_QQ_` now?

2017-05-02 09:00 UTC, rdeutz commented
Can some test this so that we can get this in 3.7.1?

2017-05-02 09:13 UTC, csthomas commented on libraries/joomla/language/language.php
> +			$strings = array();
@PhilETaylor If you are not convinced about merge my PR can you at least remove a ternary operator from line 857:
```php
return is_array($strings) ? $strings : array();
```

 which is equal to your new code:
```php
if (!is_array($strings))
{
	$strings = array();
}
```

2017-05-02 09:51 UTC, PhilETaylor commented on libraries/joomla/language/language.php
> +			$strings = array();
Done.

2017-05-02 09:52 UTC, PhilETaylor commented on tests/unit/suites/libraries/joomla/language/JLanguageTest.php
> +		 * syntax error, unexpected BOOL_TRUE in
@wilsonge Can you close your review please ;-)

2017-05-02 09:56 UTC, PhilETaylor commented on tests/unit/suites/libraries/joomla/language/JLanguageTest.php
> +		 * syntax error, unexpected BOOL_TRUE in
@csthomas Feel free to propose a PR against joomla-cms/staging with your new unit tests for HHVM

2017-05-02 11:28 UTC, csthomas commented on libraries/joomla/language/language.php
> +			$strings = array();
Thanks

2017-05-02 11:29 UTC, PhilETaylor commented
> Can some test this so that we can get this in 3.7.1?

Please everyone test.

2017-05-02 16:07 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 30e69b3a5fddffb36ebc68d427a3c90c522a1d33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15620">issues.joomla.org/tracker/joomla-cms/15620</a>.</sub>

2017-05-02 16:17 UTC, AlexRed commented
I have tested this item :white_check_mark: successfully on 30e69b3a5fddffb36ebc68d427a3c90c522a1d33<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15620">issues.joomla.org/tracker/joomla-cms/15620</a>.</sub>

2017-05-02 16:25 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-05-03 06:27 UTC, merged

2017-05-12 10:00 UTC, MixingOnBeat commented
Boy, did I also have a rough time with this update from 3.6.5 to 3.7.0.  After the upgrade all the text in the admin panel as well as some text on the public pages were a mess.  I also have a host/server that doesn't allow me to alter php.ini files. :(

I had to revert back my changes (glad I made a backup of the files/database).  I hope you guys find a common ground for 3.7.1.  I read all arguments and though it would be nice that some hosts would not do this, but as long this can be fixed using a bit of code, perhaps this is best for everyone.

2017-05-12 10:12 UTC, wilsonge commented
This patch got merged and we hope that 3.7.1 will drop towards the end of next week with the fix for you in :)

2017-06-01 14:34 UTC, hakanara commented
Hi all, this issue is still existing with a fresh 3.7.2 installation. Shall I open a new issue?

2017-06-01 14:59 UTC, brianteeman commented
Yes please

2017-07-21 08:54 UTC, hakanara commented
Fresh installation or a 3.7.3 upgrade still shows us that moronic hosting issue interferes Joomla and prevents Joomla from rocking. All Joomla loverz, let's unite and let Joomla rock!

2017-07-21 09:02 UTC, hakanara commented
You are all invited to the reopening: #17198