Rewritten part of File Cache Storage Engine
joomla/joomla-cms pull request #15875
Opened 2017-05-07 17:22 UTC by demis-palma

### Definitive solution for “zero length cache file”
that has caused so much troubles in such a short time (and so many problems would have caused in future) https://github.com/joomla/joomla-cms/issues/15544 https://github.com/joomla/joomla-cms/pull/15558 https://github.com/joomla/joomla-cms/pull/15592

The current implementation of file storage makes use of the shutdown function, but it doesn't work in case of software crashes, hardware failure, power blackout, and so on.

## Summary of Changes

1. Don't create empty cache files at all
2. Limit the lock for no longer than is strictly necessary to the write operation
3. Delegated file locking to PHP
4. Addresses and fixes a couple of other latent cache bugs
5. Significant code simplification and major performance improvements.
6. Given resistance and stability against the unlikely event of corrupted cache files

### Here we have all the possible concurrent circumstances, and their consequences before and after this PR.

#### 1. Write followed by a concurrent Write
:anguished: **Before this PR** It depends on how long it takes the first write process. If the first write ends before the second’s time-out, then the concurrent write will be enqueued, otherwise it will be discarded. A big mess.
:heavy_check_mark: **After this PR** The concurrent write will be enqueued to the first write in any case.

#### 2. Write followed by a concurrent Read
:x: **Before this PR** Unserialize error. This also causes a PHP warning, which could possibly disclosure path information.
This happens because the caller expects a valid serialized data or null. It does not expect invalid data.
Unlikely to actually happen? For the “[Infinite monkey theorem](https://en.wikipedia.org/wiki/Infinite_monkey_theorem)” it will almost surely happen and actually happened in past: https://forum.joomla.org/viewtopic.php?t=851183
:heavy_check_mark: **After this PR** No error happens. The cache ensures to always return valid data or null, as the caller expect. This is done by introducing an integrity self check to the cache buffer.

#### 3. Read followed by a concurrent Read
:heavy_check_mark: **Before this PR** No problem
:heavy_check_mark: **After this PR** No problem

#### 4. Read followed by a concurrent Write
:exclamation: **Before this PR** It depends on the file size. The most of the times due to the hard drive buffer, the entire file remains available in the drive cache for the reading process even if it has been already overwritten on the disk.
Otherwise, if the file is bigger than the hard drive cache, the cache buffer gone corrupted and it causes unserialize error (see above).
:heavy_check_mark: **After this PR** The same as before the PR, with the difference that a corrupted file is detected and invalidated by the integrity self check, and it raises no errors continuing the program flux ignoring the cache for the current http request.

#### 5. Write followed by a concurrent Deletion
Quite scary, but no particular problem. It is behaves as case 1. Write followed by a concurrent Write

#### 6. Read followed by a concurrent Deletion
Quite scary, but no particular problem. It is behaves as case 4. Read followed by a concurrent Write

#### 7-8. Deletion followed by a concurrent Read | Write
Deletion is atomic and does not suffer concurrency from Read or Write operations, so the cases Deletion followed by a concurrent Read | Write don’t exist.

## Performance improvements

1. Do not delete anymore expired files before recreate them. Just overwrite them.
2. Do not use anymore the str_replace() function searching for the php die protection heading along the entire cache buffer. Used file offset instead.

## Other changes
Mimic a successful lock and unlock operations to keep compatibility with the previous interfaces, but this storage engine does not need lock / unlock methods

## Testing Instructions
I have stressed my system with 100 concurrent requests a a time, and I got no errors.
At the moment, I've tested on Linux only. Windows and OSX should not reserve surprises, but It's better to do a test drive.

2017-05-07 17:30 UTC, Quy commented on libraries/joomla/cache/storage/file.php
> +	 * Just avoid calculating the lenght of the protection heading over and over at runtime
Typo `lenght`.

2017-05-07 17:32 UTC, Quy commented on libraries/joomla/cache/storage/file.php
> +		// Simulates s successful lock, but actually do nothing,
Change `s` to `a`.

2017-05-07 17:32 UTC, Quy commented on libraries/joomla/cache/storage/file.php
> +		// Simulates s successful unlock, but actually do nothing,
Change `s` to `a`.

2017-05-07 17:50 UTC, brianteeman commented
@demis-palma please look at the travis errors

2017-05-07 18:06 UTC, demis-palma commented on libraries/joomla/cache/storage/file.php
> +	 * Just avoid calculating the lenght of the protection heading over and over at runtime
All corrected, thanks.

2017-05-07 18:07 UTC, demis-palma commented
@brianteeman sure.

2017-05-08 22:37 UTC, Quy commented on tests/unit/suites/libraries/joomla/cache/storage/JCacheStorageFileTest.php
> +		// Decode the data and comare it with the original
Typo `comare`.

2017-05-10 20:42 UTC, csthomas commented
In general it is OK.

Changes in lock/unlock methods may have some B/C issue but I do not protest.
Option from cache `locking` is useless now but is should not be any problem. It should be deprecated.

If this changes can go then other storages can be done in the same way and controllers/adapters can forget about `lock/unlock` cache storages/handlers in `get/store` methods.

2017-05-10 20:46 UTC, csthomas commented on libraries/joomla/cache/storage/file.php
> +			if (is_string($data) && !empty($data))
`if (data)` would be enough.

2017-05-10 20:57 UTC, csthomas commented on libraries/joomla/cache/storage/file.php
> +					return rtrim($data, self::INTEGRITY_DIGIT);
Why not use `substr(data, 0, -1)`?

2017-05-10 20:57 UTC, csthomas commented on tests/unit/suites/libraries/joomla/cache/storage/JCacheStorageFileTest.php
> +		file_put_contents($file_path, JCacheStorageFile::PHP_HEADING_PROTECTION . $testData . JCacheStorageFile::INTEGRITY_DIGIT);
I suggest to use `$this->handler->store($this->id, $this->group, $testData);` to test whether `store` works.

2017-05-17 07:38 UTC, tampe125 commented
I think this is the correct approach to the cache issue. We lock before writing and there is an extensive use of defensive coding.
:+1:

2017-05-17 07:39 UTC, tampe125 commented on libraries/joomla/cache/storage/file.php
> +					return rtrim($data, self::INTEGRITY_DIGIT);
Because it's a completely different function with a completely different behaviour

2017-05-17 11:36 UTC, csthomas commented on libraries/joomla/cache/storage/file.php
> +					return rtrim($data, self::INTEGRITY_DIGIT);
@tampe125 I do not understand your approach. If joomla adds 1 char suffix then it should remove 1 char. What is the issue?
If cached data will contain '\0' at the end of data then `rtrim` could remove too much.

2017-05-30 13:22 UTC, klas requested changes

2017-05-30 13:22 UTC, klas commented on libraries/joomla/cache/storage/file.php
>  	}
This does not seem correct, lock/unlock are there for a reason.

2017-05-30 13:22 UTC, klas commented on libraries/joomla/cache/storage/file.php
>  		return true;
This does not seem correct, lock/unlock are there for a reason and true should be returned only if unlock was sucesfull. Returned value should depend on real state.

2022-03-15 13:48 UTC, HLeithner commented
Similar to #15707 

This PR is outdated and have to be updated to fit in to j3. J4 uses a legacy caching system which should be replaced with a 3rd party library compatible PSR-6 / PSR-16 package see https://github.com/joomla-framework/cache

If you are still interested to bring this to joomla we would be happy if you help us working on the new cache layer or if you like you can bring this PR in Sync for 3.10 but since the focus is J4 it would be better to help use with the caching layer.

thanks I'm closing this for now, feel free to reopen.

2022-03-15 13:48 UTC, closed without merging