Namespace document
joomla/joomla-cms pull request #16367
Opened 2017-05-30 14:27 UTC by fastslack

Namespace for document classes

### Summary of Changes

Move /libraries/joomla/document to /libraries/src/Joomla/CMS/Document

### Testing Instructions

Apply patch and try to create one article

### Expected result

No errors

2017-05-30 15:55 UTC, mbabker commented
This has test issues.

```sh
Error displaying the error page: Application Instantiation Error: include_once(/home/travis/build/joomla/joomla-cms/libraries/joomla/document/html/renderer/component.php): failed to open stream: No such file or directory
```

2017-05-30 16:02 UTC, fastslack commented
@mbabker I removed that files because are duplicated and are not needed any more. Look at the files, there is only mapping to deprecated files.

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/html/renderer/component.php

We can solve compatibilities issues in classmap.php file. 

https://github.com/fastslack/joomla-cms/blob/namespace-document/libraries/classmap.php#L191

Maybe we should remove that tests

2017-05-31 09:19 UTC, mbabker commented
We don't need the format in the short class section for the renderers.  So for example instead of `Joomla\CMS\Document\Renderer\Html\RendererHtmlComponent` we can do something like `Joomla\CMS\Document\Renderer\Html\ComponentRenderer`.

2017-05-31 11:03 UTC, mbabker commented
OK, one more pedantic change, then there's one concern we need to quickly look over.  For the document classes, can you change it to `<format>Document` instead of `Document<format>`?

The concern - we have some files here that have multiple classes in them.  I think this would be a good time to move them out to separate files.

2017-06-05 16:36 UTC, laoneo requested changes

2017-06-05 16:36 UTC, laoneo commented on libraries/src/Joomla/CMS/Document/Document.php
> +					$class = 'DocumentRaw';
Namespace is missing, or?

2017-06-05 16:36 UTC, laoneo commented on libraries/src/Joomla/CMS/Document/Document.php
> +			$class = 'DocumentRenderer' . $type;
Namespace is missing, or?

2017-06-05 16:36 UTC, laoneo commented on libraries/src/Joomla/CMS/Document/OpensearchDocument.php
> +class OpenSearchUrl
This classe should be moved to its own file.

2017-06-05 16:36 UTC, laoneo commented on libraries/src/Joomla/CMS/Document/OpensearchDocument.php
> - * JOpenSearchImage is an internal class that stores Images for the OpenSearch Description
This classe should be moved to its own file.

2017-06-05 16:36 UTC, laoneo commented on libraries/src/Joomla/CMS/Document/OpensearchDocument.php
> -class JOpenSearchImage
This classe should be moved to its own file.

2017-06-05 16:36 UTC, laoneo commented on libraries/src/Joomla/CMS/Document/XmlDocument.php
> +	 * @return  JXmlDocument instance of $this to allow chaining
J needs to be removed.

2017-07-17 15:48 UTC, laoneo commented
Thanks!

2017-07-25 23:09 UTC, mbabker commented on libraries/src/Joomla/CMS/Document/Document.php
> +		$class = __NAMESPACE__ . '\\Renderer\\' . ucfirst($this->getType()) . '\\Renderer' . ucfirst($this->getType()) . ucfirst($type);
If I'm reading this line right it's not building the correct namespaced class names.

2017-07-25 23:10 UTC, mbabker commented on libraries/src/Joomla/CMS/Document/FeedDocument.php
> +class FeedItem
This and the other classes in this file should move to separate files now.

2017-07-28 12:34 UTC, mbabker commented
Fixed the items I pointed out and merged to staging.

2017-07-28 12:34 UTC, closed without merging