Namespace Http classes
joomla/joomla-cms pull request #16445
Opened 2017-06-02 10:27 UTC by fastslack

Namespace Http classes

### Test instructions

After apply this patch, Joomla! should work as usually

2017-06-03 13:38 UTC, mbabker commented
@wilsonge This one could pose a problem, from Travis:

```sh
1) JHttpFactoryTest::testGetHttpTransports
CURL should be the first transport returned.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'curl'
+'CurlTransport'
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/http/JHttpFactoryTest.php:81
```

2017-06-05 16:27 UTC, laoneo requested changes

2017-06-05 16:27 UTC, laoneo commented on libraries/src/Joomla/CMS/Http/HttpFactory.php
> +			$class = __NAMESPACE__ . '\\Transport\\' . ucfirst($adapter) . 'Transport';
We need to support the old protocols as well, otherwise we will have a BC break here. So when the namespaced class is not found, look for the old one.

2017-06-22 12:28 UTC, fastslack commented on libraries/src/Joomla/CMS/Http/HttpFactory.php
> +			$class = __NAMESPACE__ . '\\Transport\\' . ucfirst($adapter) . 'Transport';
@laoneo I dont know how to test this correctly, but i think this https://github.com/joomla/joomla-cms/pull/16445/commits/41757719fb58dd11f60f0ea2e4c4535e22366ad4 patch fix the BC break

2017-06-22 12:31 UTC, mbabker commented on libraries/src/Joomla/CMS/Http/HttpFactory.php
> +			$class = __NAMESPACE__ . '\\Transport\\' . ucfirst($adapter) . 'Transport';
To be completely honest, I don't even think we need that commit.  This factory class is hardcoded to only support looking up adapters in `libraries/joomla/http/transport` (current convention).  It's only a B/C break if developers are adding custom classes to our directory structure.  I would not call that appropriate use of the API.

2017-06-22 12:32 UTC, laoneo commented on libraries/src/Joomla/CMS/Http/HttpFactory.php
> +			$class = __NAMESPACE__ . '\\Transport\\' . ucfirst($adapter) . 'Transport';
We did it the same on other libraries so I would also do it here. Just to stay on the safe side.

2017-06-22 12:37 UTC, mbabker commented on libraries/src/Joomla/CMS/Http/HttpFactory.php
> +			$class = __NAMESPACE__ . '\\Transport\\' . ucfirst($adapter) . 'Transport';
The other libraries we just left the class name lookups using the global namespace classes, IIRC we didn't change the lookups almost anywhere to use namespaced class names.

This factory has a very specific use case and can very specifically only support our core classes.  So it's honestly rather difficult to argue that developers can be using this class, as is, to load custom classes because the only way to do it is to drop files into the filesystem in our core library directory (or heaven forbid they're manipulating the autoloader and using a custom version of the factory, in which case they're already on their own).

2017-07-01 08:10 UTC, laoneo commented
Just stumbled over https://github.com/joomla-framework/http. Should we not try to integrate that package similar to what we did with the archive package in #14157?

2017-07-01 14:46 UTC, mbabker commented
No.  The internals of the transports are handled differently (the CMS' fully reads from `JFactory::getConfig()` whereas the Framework's requires everything to be injected).  The 4.0 branch extends the Framework package to the extent possible, but to me that's as far as we can go with it right now until we make the CMS' `HttpFactory` read and inject all the right parameters.  And that becomes a hard B/C break because it forces everyone to go through the factory to get a properly configured adapter whereas right now it can be done just by calling `new JHttp`.

2017-07-07 12:51 UTC, merged

2017-07-07 13:25 UTC, laoneo commented
Thanks!