Admin Menu custom presets, import/export a preset into/from database driven menu
joomla/joomla-cms pull request #16451
Opened 2017-06-02 17:06 UTC by izharaazmi

### Summary of Changes

As we know that with the release of Joomla 3.7 we have the Admin Menu Manager that lets you customise the administrator menu according to your needs. The backend menu comes in two flavours: **Custom Menu** and **Preset Menu**. You can have as many custom menu each configured in different way as suitable. Or if you do not want to customise then you use the Preset menu.

This PR is indented to extend the features for this Admin Menu Manager as promised in the initial strategy.

### Changes

1. **Custom Presets**: 
If you copy (and modify) one of the existing preset files from `/administrator/com_menus/presets` to `/administrator/templates/{your_template}/html/com_menus/presets` then you can use it as your own custom preset.

2. **Import Preset Menu**: 
If you would like to modify merely one or two things and keep rest of the menu structure the same way as in a preset menu you still need to create all of those links one by one yourself **manually**. After this PR Joomla will allow you to directly import an existing preset (core or custom) into your custom admin menu directly and then you can customise it very quickly. When creating/editing a `Menu` (menutype) you can optionally select a preset that you would like to import.

3. **Export Menu as Preset**: 
You can also export your database driven `custom admin menu` as an a Preset. Just select a Menu in the list and click `Download As Preset` button in the toolbar.

4. **Menu Module Layout Override**: 
The current implementation of the Admin Menu Module has the HTML rendering from within the PHP class `JAdminCssMenu` which does not let you customise the HTML in any way. This PR puts all the HTML output logic into the layout files under `tmpl/` folder as commonly expected. This way you can easily override the layout in your template.

5. **Menu Structure Override**: 
Prior to Joomla 3.7 we could override the menu links using `default_enabled.php` and `default_disabled.php`. After the Menu Manager was introduced this ability was removed. Most likely you would really never need this anymore. It is always better to import a preset in a custom menu and customise it in the Menu Manager instead of messing with any PHP code. However, if you still insist, you can use the **Custom Preset** as discussed above. The naming convention is like `my-custom-menu.xml` becomes `My Custom Menu` (we can improve this later if needed). It is really easy to understand and work with. Give it a try.

### Testing Instructions
1. Create a custom admin menu and set it as your active admin menu in the module settings.
    * It should work correct and show the links based on the appropriate permissions.
    * Notice about missing important menu links (if any) should be displayed as before.
    * Clicking on the Menu Recovery link should enable the recovery mode and you should be able to exit the recovery mode too.
    * Components container should also work correctly like hiding/showing choices as configured.
    * Installing a new component should make the link under the components container menu.
 
1. Try to choose another preset in the module settings. The displayed menu should be updated according the selected preset.
 1. Create a custom preset by copying (as discussed above) and make some changes. Set this custom preset as your active menu. The menu should now load you custom preset.
 1. Create new custom admin menu and choose a preset to import. This should load the menu links and hierarchy from the preset.
 1. From the list view of Menu, select one of your Admin Menus and click on "Download as Preset" button. The XML file should be downloaded correctly and should contain the selected menu links with correct settings.

### Documentation Changes Required
I'd like to write the detailed documentation of the entire Admin Menu Manager. Please advise where should I head towards.

PS: As I am on a vacation this PR was created in hurry. Pardon me for any mistakes and please ask for any kind of clarifications or suggestions. I'll try to respond as quickly as possible.

2017-06-02 18:00 UTC, andrepereiradasilva commented on administrator/components/com_menus/helpers/menus.php
> +			JFactory::getApplication()->enqueueMessage(JText::_('JERROR_AN_ERROR_HAS_OCCURRED'), 'error');
i didn't review the rest of the PR, but just one comment to this line

Why catch the default JDatabase (or Registry) exception and replace it with something called `JERROR_AN_ERROR_HAS_OCCURRED`?

This is more or less the same as saying: *"Joomla knows the system is not working properly but doesn't have idea what happened! All it can say is .. an error has occurred ..."* :smile:

2017-06-02 19:23 UTC, izharaazmi commented on administrator/components/com_menus/helpers/menus.php
> +			JFactory::getApplication()->enqueueMessage(JText::_('JERROR_AN_ERROR_HAS_OCCURRED'), 'error');
You're right. I actually reused the old code as is. I'll fix when I get to steal few minutes. Please review further so I can fix them all at once. Thanks.

2017-06-02 20:19 UTC, izharaazmi commented
@sanderpotjer It would be really great if you could look at this in the light of our disscussion at https://github.com/joomla/joomla-cms/pull/13036#issuecomment-272785924. Thanks.

2017-06-03 10:03 UTC, StefanSTS commented
Hello Izhar,
nice work done with a lot of effort. Thanks.
I am testing and will do some more testing.
I copied the full https://github.com/joomla/joomla-cms/tree/c787b79e6ae7a198087f9c72434856d3b6f63ee3 over an existing J 3.7.2 for testing.
I found an issue if you add a menu item to a new menu that is already existent maybe through automatically added menu or another custom menu. BE ends up white with error 1242.
The error message is: Subquery returns more than 1 row

To avoid this error there might be options like:
- compare the menu items in db before adding a new link and do not allow a second entry or
- query the db in a way that only the corresponding item to the menu is found (maybe by id instead of com_something/menu type).

I got two other error messages after creating a new menu:
Notice: Undefined property: MenusViewMenus::$filterForm in /opt/lampp/htdocs/j36vm32/administrator/components/com_menus/layouts/joomla/searchtools/default/bar.php on line 37
Fatal error: Call to a member function getField() on null in /opt/lampp/htdocs/j36vm32/administrator/components/com_menus/layouts/joomla/searchtools/default/bar.php on line 37
I was distracted by some other work. After reloading the page, I guess, the menu appeared and I could not reproduce this. I will test this further in a while.

2017-06-03 11:24 UTC, StefanSTS commented
**Method of import**
On making a new menu "menunew" I can import the joomla.xml or modern.xml.
_Example:_
I import joomla.xml.
I check the menu, I don't like it.
I import modern.xml.
Now I have all the menu items from both imports.

Iit would be helpful to have an option to either add the new preset to the existing items or replace all existing items. So there is the possibility to add either a preset for only a component or a full menu.

**New presets not showing**
I placed a new XML file into administrator/components/com_menus/presets/, called menunew.xml.
This file is not showing up in my importable xml files in the menu edit. Placed it into the templates override folder like given above, and it also does not show.

**File structure xml vs. php**
One more thing about the new xml file structure. Before it was a php file (default_enabled.php), so template parameters could be imported and used as custom settings.
Template settings like minimal, normal, advanced. The user could choose his preferred way of displaying the menu. Lets say, have 2 menu items, 10 or 24, depending on what he needs for daily work or if he uses a small screen device or a desktop computer. 
I guess with an xml file we could loose this simple way of changing the menu view.

_Suggestion for mobile view_
With an additional parameter viewlevel in the xml this could be done if the menu edit gets this too. 
<menuitem
	type="url"
	target="_blank"
	title="MOD_MENU_HELP_SUPPORT_OFFICIAL_FORUM"
	link="https://forum.joomla.org"
	class="class:help-forum"
	scope="help"
	viewlevel="minimal/normal/advanced" // added attribute
/>

This would be a good feature for people who do a lot of their work with mobile devices. And it would kind of restore a possibility you had with php files before.

2017-06-06 22:09 UTC, izharaazmi commented
@StefanSTS Below are my responses as per my understanding to your inputs:

> It would be helpful to have an option to either add the new preset to the existing items or replace all existing items...

If we replace all the existing menu items during a single click import process it would be an easy **destructive** action. Therefore, I omitted that feature on purpose. The user must "select all" and "delete" all existing menu items if so intended.

> I placed a new XML file into ... not showing up in my importable xml files in the menu edit. Placed it into the templates override folder like given above, and it also does not show.

I tested this and it is working here as expected. I may be missing something, please let me know if you still get this issue.

> File structure xml vs. php

The preset XML files are to represent the menu item definition and hierarchy. Their rendering is still controlled via the layout files in the `mod_menu` layout files/overrides. Layout files are PHP files as usual and the module options are accessible in the code there.

Therefore, you still have all the controls over the rendering while keeping the preset definition as simple and general.

Additionally, I'd like to mention that those `default_enable` and `default_disabled.php` did not give you much control over **rendering** rather only on the hierarchy. The HTML output was hard-coded within the class method which could not be overridden. With this PR you get all that flexibility. Your mobile rendering idea too can work even better by just overriding the layout files appropriately and not modifying the preset XML files at all.

2017-06-07 07:57 UTC, StefanSTS commented
Thanks for your reply, Izhar. I will be testing again when time permits on a fresh installation. This week is a little tight though, not sure if it will fit in.

2017-07-24 12:36 UTC, brianteeman commented
@izharaazmi can you look at the merge conflicts please - then i can test it :)

2017-07-24 12:46 UTC, izharaazmi commented
Sure

2017-07-24 15:40 UTC, izharaazmi commented
@brianteeman I have resolved the conflicts. Travis failure is due to some internal error and not on code.

2017-07-26 06:32 UTC, izharaazmi commented
@brianteeman @andrepereiradasilva It'd be great if we could get this before the 3.8 feature freeze.

2017-07-26 12:06 UTC, brianteeman commented
`Error displaying the error page: Class 'Joomla\CMS\Menu\Tree' not found: Class 'Joomla\CMS\Menu\Tree' not found`

2017-07-26 14:10 UTC, izharaazmi commented
@brianteeman Could not reproduce this anywhere. May be I'm missing somewhere. Can you please guide me the steps through it?

2017-07-26 14:14 UTC, brianteeman commented
I got it immediately after applying the patch will try again later

2017-07-26 14:24 UTC, franz-wohlkoenig commented
Got same Error as @brianteeman wrote.

2017-07-27 07:14 UTC, izharaazmi commented
@brianteeman @franz-wohlkoenig There seems to be some issue with the patch tester applying this patch. Please use the source branch [izharaazmi/joomla-cms/menu-preset-features.zip](https://github.com/izharaazmi/joomla-cms/archive/menu-preset-features.zip) for testing.

I have updated the branch with the latest staging so there should be no conflicts.

2017-07-27 08:34 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 39b96e162253f1b3fc0a0a5ace98d029c046baa2<br /><br />Test:
Created a custom preset (mypreset.xml) in Isis by copying the Modern Preset.
Set a custom menu to use this custom preset.
Set the menu module to also load that preset (**both the module and menutype should be set to use the preset**).
I deleted in that custom preset all <menuitem> related to User.

Works fine here. :smiley: 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16451">issues.joomla.org/tracker/joomla-cms/16451</a>.</sub>

2017-07-28 11:42 UTC, izharaazmi commented
@brianteeman @franz-wohlkoenig Can you try again please! Running out of time for feature freeze.

2017-07-28 19:03 UTC, zafarnayab commented
I have tested this item :white_check_mark: successfully on 39b96e162253f1b3fc0a0a5ace98d029c046baa2<br /><br />Works as described.
Tested custom preset, custom menu, preset import. All good. 👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16451">issues.joomla.org/tracker/joomla-cms/16451</a>.</sub>

2017-07-28 19:27 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-07-29 06:09 UTC, izharaazmi commented
Is this too late for 3.8 feature freeze?

2017-07-29 06:29 UTC, infograf768 commented
@mbabker 
Can we get this in for 3.8.0? Only a few hours late... ;)

2017-07-29 14:42 UTC, mbabker commented on administrator/components/com_admin/script.php
> +			'/administrator/modules/mod_menu/preset/enabled.php',
These can be moved up the list.  There's already a 3.8 section started.

2017-07-29 14:42 UTC, mbabker commented on administrator/components/com_admin/script.php
> +			'/administrator/modules/mod_menu/preset',
Same here.

2017-07-29 14:43 UTC, mbabker requested changes
Several file permissions are changed from 0644 to 0755.  Those need to be fixed.

2017-07-29 14:45 UTC, izharaazmi commented
Fixing both

2017-07-31 11:46 UTC, mbabker approved these changes

2017-07-31 11:46 UTC, merged