[4.0] Fix articles modules
joomla/joomla-cms pull request #16608
Opened 2017-06-10 06:36 UTC by joomdonation

Pull Request for Issue # .

### Summary of Changes
Similar to https://github.com/joomla/joomla-cms/pull/16607, this PR fixes the remaining modules:

- mod_articles_category
- mod_articles_news
- mod_articles_popular

It including calling the namespaced class from com_content + use the namespaced class instead some aliases class

### Testing Instructions
Code review. Maybe @wilsonge  can review and merge it

2017-06-10 06:43 UTC, franz-wohlkoenig commented
I have tested this item :red_circle: unsuccessfully on 63d2a98439f72c5da9729c078d3769e14011fa87<br /><br />index.php/news-flash give 404.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16608">issues.joomla.org/tracker/joomla-cms/16608</a>.</sub>

2017-06-10 07:04 UTC, joomdonation commented
It is actually not related to this PR. It causes by **Content - Page Break** plugin https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/content/pagebreak/pagebreak.php#L81

I haven't read the code of that plugin yet, so we can leave it to next PR

2017-06-10 07:27 UTC, laoneo requested changes

2017-06-10 07:27 UTC, laoneo commented on modules/mod_articles_category/mod_articles_category.php
>  JLoader::register('ModArticlesCategoryHelper', __DIR__ . '/helper.php');
Can this also be namespaced?

2017-06-10 07:27 UTC, laoneo commented on modules/mod_articles_latest/mod_articles_latest.php
>  JLoader::register('ModArticlesLatestHelper', __DIR__ . '/helper.php');
Can this also be namespaced?

2017-06-10 07:27 UTC, laoneo commented on modules/mod_articles_news/mod_articles_news.php
>  JLoader::register('ModArticlesNewsHelper', __DIR__ . '/helper.php');
Can this also be namespaced?

2017-06-10 07:27 UTC, laoneo commented on modules/mod_articles_popular/mod_articles_popular.php
>  JLoader::register('ModArticlesPopularHelper', __DIR__ . '/helper.php');
Can this also be namespaced?

2017-06-10 07:29 UTC, joomdonation commented
OK. So I checked and found that the issue happens with Joomla 3.x as well, so look like a bug from this module

I checked article view, and see that the fourth parameter of onContentPrepare trigger has null as default value. So I changed the parameter value from 1 to 0 on this commit https://github.com/joomla/joomla-cms/pull/16608/commits/2005578cb00a376929635dac15bd1141f3393dff. @wilsonge Please check it to confirm the change is correct.

@franz-wohlkoenig Please test it again

2017-06-10 07:34 UTC, joomdonation commented on modules/mod_articles_category/mod_articles_category.php
>  JLoader::register('ModArticlesCategoryHelper', __DIR__ . '/helper.php');
Yes. I can namespace it. But I need to have final confirm from @wilsonge about whether we want to namespace this helper class. The reason is because recently, the autoload psr4 was merged but only or components

I don't know how he wants to handle namespace for module or if namespace for modules is needed. So lets leave it for the next PR. This PR mostly to fix fatal error in some modules here because it is using old code for calling none-existent model classes

2017-06-10 08:21 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 2005578cb00a376929635dac15bd1141f3393dff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16608">issues.joomla.org/tracker/joomla-cms/16608</a>.</sub>

2017-06-14 16:03 UTC, joomdonation commented
@wilsonge Shouldn't this one be merged? Or you want to have helper file namespaced as Allon mentioned?

2017-06-14 16:09 UTC, merged