Move and namespaces legacy fields
joomla/joomla-cms pull request #17322
Opened 2017-07-28 17:21 UTC by fastslack

### Summary of Changes

This change move legacy form fields to Joomla\CMS\Form\Field directory for namespaces

### Testing Instructions

Use Category , ComponentLayout or ModuleLayout form field and should work as usual

### Expected result

Work as usual

2017-07-28 18:14 UTC, C-Lodder commented on libraries/src/Joomla/CMS/Form/Field/CategoryField.php
> +					if ($user->authorise('core.create', $extension . '.category.' . $option->value) != true)
`!==`

2017-07-28 19:19 UTC, fastslack commented on libraries/src/Joomla/CMS/Form/Field/CategoryField.php
> +					if ($user->authorise('core.create', $extension . '.category.' . $option->value) != true)
done

2017-07-29 14:56 UTC, mbabker requested changes
Needs class mapping.

2017-08-05 11:31 UTC, wilsonge commented
Do we want the category form field to be moved into the category component rather than being a library form field?

2017-08-05 11:33 UTC, wilsonge requested changes

2017-08-05 11:33 UTC, wilsonge commented on libraries/src/Joomla/CMS/Form/Field/ComponentlayoutField.php
> +use Joomla\CMS\Filesystem\Folder;
These haven't been namespaced yet

2017-08-05 11:33 UTC, wilsonge commented on libraries/src/Joomla/CMS/Form/Field/ModulelayoutField.php
> +use Joomla\CMS\Filesystem\Folder;
Same here

2017-11-01 10:06 UTC, franz-wohlkoenig commented
Status is set on "Needs Review".

2017-11-13 18:03 UTC, fastslack commented
Should I do same thing but for 3.9 branch and close this PR?

2019-06-15 14:47 UTC, Quy commented
@wilsonge Close PR?

2021-08-21 00:10 UTC, PhilETaylor commented on libraries/src/Joomla/CMS/Form/Field/CategoryField.php
> + * @copyright  Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:10 UTC, PhilETaylor commented on libraries/src/Joomla/CMS/Form/Field/ComponentlayoutField.php
> + * @copyright  Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:11 UTC, PhilETaylor commented on libraries/src/Joomla/CMS/Form/Field/ModulelayoutField.php
> + * @copyright  Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-03-18 08:19 UTC, laoneo commented
Sorry that it has taken so long to respond to this pull request. We did this change in Joomla 4 already and wont move the files in Joomla 3. So I'm closing this pr. Nevertheless we would like to thank you for your contribution.

2022-03-18 08:19 UTC, closed without merging