[4.0] Refactor com_languages 'override' view
joomla/joomla-cms pull request #17334
Opened 2017-07-29 15:47 UTC by C-Lodder

Pull Request for Issue #17225

### Summary of Changes

- Rewrite all the jQuery in vanilla JS
- Fix the spinner not showing
- Styling improvements

2017-07-29 15:52 UTC, brianteeman commented
Shouldn't this pr also include changes to the unminified permission is file?

2017-07-29 17:38 UTC, C-Lodder commented
@brianteeman reverted it just before your comment

2017-07-29 17:48 UTC, dgrammatiko requested changes

2017-07-29 17:48 UTC, dgt41 commented on media/com_languages/js/overrider.js
> +		method: 'POST',
you can delete the duplicate here

2017-07-29 17:50 UTC, dgrammatiko requested changes

2017-07-29 17:50 UTC, dgt41 commented on media/com_languages/js/overrider.js
> +		for (var i = 0; children.lendth > 0; i++) {
`for (var i = 0, l = children.lendth ; i < l; i++) {`

2017-07-29 18:56 UTC, C-Lodder commented on media/com_languages/js/overrider.js
> +		method: 'POST',
done

2017-07-29 18:56 UTC, C-Lodder commented on media/com_languages/js/overrider.js
> +		for (var i = 0; children.lendth > 0; i++) {
and done

2017-07-29 18:57 UTC, C-Lodder commented on media/com_languages/js/overrider.js
> +		for (var i = 0; children.lendth > 0; i++) {
Glad you spotted this was as I misspelled `length`

2017-07-30 11:29 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on cbc6325ede59dfcaeb2c707c6b316683ed14ce45<br /><br />First search works but any subsequent searches do not<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17334">issues.joomla.org/tracker/joomla-cms/17334</a>.</sub>

2017-07-30 11:32 UTC, brianteeman commented
### before PR
![before](https://user-images.githubusercontent.com/1296369/28752961-0f521f4e-7523-11e7-967f-d44240a56990.gif)

### after pr
![j4](https://user-images.githubusercontent.com/1296369/28752962-0f6d85fe-7523-11e7-81b1-8def81f2d2fd.gif)

2017-07-30 12:05 UTC, dgt41 commented on media/com_languages/js/overrider.js
> +					moreResults.classList.add('show');
we need to hide the results here

2017-07-30 12:50 UTC, C-Lodder commented on media/com_languages/js/overrider.js
> +					moreResults.classList.add('show');
done

2017-07-30 12:53 UTC, C-Lodder commented
@brianteeman - updated/fixed. Would you mind testing again please?

2017-07-30 12:55 UTC, brianteeman commented
Will do after the f1

2017-07-30 13:47 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 8f3cd72945089b869d13586c69bedb68ea2e9a0b<br /><br />all ok now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17334">issues.joomla.org/tracker/joomla-cms/17334</a>.</sub>

2017-07-30 13:47 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 8f3cd72945089b869d13586c69bedb68ea2e9a0b<br /><br />all ok now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17334">issues.joomla.org/tracker/joomla-cms/17334</a>.</sub>

2017-07-30 13:59 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 8f3cd72945089b869d13586c69bedb68ea2e9a0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17334">issues.joomla.org/tracker/joomla-cms/17334</a>.</sub>

2017-07-30 13:59 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-07-30 19:46 UTC, merged