Extension package management enhancement.
joomla/joomla-cms pull request #17585
Opened 2017-08-17 17:19 UTC by brainforgeUK

See issue #17579 - Managing extension packages
https://issues.joomla.org/tracker/joomla-cms/17579

Pull Request for Issue # .

### Summary of Changes
Added -- Select Package -- list to search tool in extension manager
Added links to plugin / template edit in extension manager list display

### Testing Instructions
Goto .../administrator/index.php?option=com_installer&view=manage
Go to Search Tools and Select a Package

### Expected result

### Actual result

### Documentation Changes Required

2017-08-17 17:33 UTC, brianteeman commented on administrator/components/com_installer/models/manage.php
> +		$packageId  = $this->getState('filter.package_id');
Please can you adjust the spaces on the lines above so that all the = are in allignment

2017-08-17 17:37 UTC, zero-24 commented
@brainforgeUK Thanks for your PR. i have just fixed some minor code style issues. I hope i get some time to test this feature too. If you have any questions about the changes I made please feel free to ask me.

2017-08-17 17:42 UTC, brainforgeUK commented on administrator/components/com_installer/models/manage.php
> +		$packageId  = $this->getState('filter.package_id');
Thanks, should have done that earlier.
See zero-24 done it already - got there before me!

2017-08-17 17:46 UTC, Quy commented on administrator/components/com_installer/models/manage.php
> +		$packageId  = $this->getState('filter.package_id');
Remove the extra space before `=`

2017-08-17 17:47 UTC, Quy commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_VALUE_PACKAGE_SELECT="- Select Package -"
Alpha order. Move it after line 264.

2017-08-17 17:49 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +										<?php break; ?>
Indent

2017-08-17 17:50 UTC, Quy commented on administrator/components/com_installer/helpers/installer.php
> +	 * Get a list of filter options for the pakcages.
Spelling `pakcages`

2017-08-17 20:20 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +									<?php break; ?>
Indent this line and dedent the following line.

2017-08-17 20:30 UTC, zero-24 commented on administrator/components/com_installer/views/manage/tmpl/default.php
> -									<?php switch($item->type) :
why did you replace the tabs by spaces?

2017-08-17 20:54 UTC, brainforgeUK commented on administrator/components/com_installer/helpers/installer.php
> +	 * Get a list of filter options for the pakcages.
Changed.

2017-08-17 20:57 UTC, brainforgeUK commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +									<?php break; ?>
My editor setting replaces tabs with spaces.
Seems to be causing confusion!

2017-08-17 20:57 UTC, zero-24 commented
@brainforgeUK it looks like you have mix up tabs and spaces in the last commit again ;)

2017-08-19 07:40 UTC, akritianand commented
Hey! After applying your patch all I see is a blank input field in the search tools. Entering text data does nothing in it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17585">issues.joomla.org/tracker/joomla-cms/17585</a>.</sub>

2017-08-19 07:59 UTC, zero-24 commented
@brainforgeUK i can confirm the result of @akritianand 

To me it looks like this in the backend.
![image](https://user-images.githubusercontent.com/2596554/29484732-132347ea-84c5-11e7-9392-ff08e0422f43.png)

2017-08-19 10:51 UTC, brainforgeUK commented
Fixed - package field class file missing!
New file got left out of git by accident.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17585">issues.joomla.org/tracker/joomla-cms/17585</a>.</sub>

2017-08-19 13:39 UTC, brainforgeUK commented
Be better to change the package field class in package.php into a standard form field.
i.e. move
**from :**
`/administrator/components/com_installer/models/fields/package.php`
**to :**
`/libraries/joomla/form/fields/package.php`

Can then add package as a plugins list search  - it makes sense to distribute several plugins as a package.
`administrator/index.php?option=com_plugins`
Other people may find the same form field useful elsewhere.

Will implement above shortly!

2017-08-20 07:18 UTC, zero-24 commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +              <th>
again tabs and spaces ;)

2017-08-20 07:18 UTC, zero-24 commented on libraries/joomla/form/fields/package.php
> +   * @since  3.8
same in this files. Spaces & Tabs.

please also replace the fixed version numbers with `__DEPLOY_VERSION__` ;)

2017-08-22 13:13 UTC, Heggi93 commented
I have tested this item :white_check_mark: successfully on acb71211a133fed3c1638d6d2c127d4a03dfb71b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17585">issues.joomla.org/tracker/joomla-cms/17585</a>.</sub>

2017-08-31 21:22 UTC, sanderpotjer commented
I have tested this item :red_circle: unsuccessfully on acb71211a133fed3c1638d6d2c127d4a03dfb71b<br /><br />@brainforgeUK nice addition! The functionality is working correctly, but some code style improvements are still needed (tabs & spaces) as commented by others before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17585">issues.joomla.org/tracker/joomla-cms/17585</a>.</sub>

2017-12-01 17:56 UTC, brainforgeUK commented
We seem to have got stuck with this.
Not in Joomla 4.0
How do we move on?

2017-12-03 18:28 UTC, Quy commented
@brainforgeUK Please fix coding style as mentioned previously. Use tabs (not spaces) to indent code.

2017-12-04 16:57 UTC, Quy commented on administrator/components/com_plugins/models/forms/filter_plugins.xml
> +				name="package_id"
lines 41-44 Fix/remove tabs.

2017-12-04 16:59 UTC, Quy commented on libraries/joomla/form/fields/packagelist.php
> +	 * @var    float
wrong type

2017-12-04 16:59 UTC, Quy commented on libraries/joomla/form/fields/packagelist.php
> +	 * @var    float
wrong type

2017-12-04 17:00 UTC, Quy commented on libraries/joomla/form/fields/packagelist.php
> +			$this->extensiontype   = isset($this->element['extensiontype']) ? $this->element['extensiontype'] : null;
lines 69-70 remove extra space before =

2017-12-04 17:03 UTC, Quy commented on libraries/joomla/form/fields/packagelist.php
> +		if (!empty($this->extensiontype)) {
Move { to the next line.

2017-12-04 17:04 UTC, Quy commented on libraries/joomla/form/fields/packagelist.php
> +		if (strlen($this->packageenabled)) {
Move `{` to the next line and add a blank line above `if`.

2017-12-04 17:04 UTC, Quy commented on libraries/joomla/form/fields/packagelist.php
> +		$db->setQuery($query);
Add a blank line above.

2017-12-04 17:07 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							$href='index.php?option=com_installer&view=manage&filter[package_id]=' . $item->extension_id;
Add space before and after `=`

2017-12-04 17:08 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							$href='index.php?option=com_plugins&task=plugin.edit&extension_id=' . $item->extension_id;
Add space before and after `=`

2017-12-04 17:08 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							$href='index.php?option=com_templates&view=template&id=' . $item->extension_id;
Add space before and after `=`

2017-12-04 17:09 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +					if ($href !== null) {
Move `{` to next line.

2017-12-04 17:09 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +					if ($href !== null) {
Move `{` to next line.

2017-12-04 17:10 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +					switch($item->type) {
Add space after `switch` and move `{` to next line.

2017-12-04 17:10 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							if (!empty($item->search_package_id) && $item->search_package_id == $item->extension_id) {
Move `{` to next line.

2017-12-04 17:11 UTC, Quy commented
For your reference on coding style: https://developer.joomla.org/coding-standards/php-code.html

2017-12-05 09:45 UTC, brainforgeUK commented on administrator/components/com_plugins/models/forms/filter_plugins.xml
> +				name="package_id"
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on libraries/joomla/form/fields/packagelist.php
> +	 * @var    float
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on libraries/joomla/form/fields/packagelist.php
> +	 * @var    float
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on libraries/joomla/form/fields/packagelist.php
> +			$this->extensiontype   = isset($this->element['extensiontype']) ? $this->element['extensiontype'] : null;
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on libraries/joomla/form/fields/packagelist.php
> +		if (!empty($this->extensiontype)) {
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on libraries/joomla/form/fields/packagelist.php
> +		if (strlen($this->packageenabled)) {
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on libraries/joomla/form/fields/packagelist.php
> +		$db->setQuery($query);
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							$href='index.php?option=com_installer&view=manage&filter[package_id]=' . $item->extension_id;
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							$href='index.php?option=com_plugins&task=plugin.edit&extension_id=' . $item->extension_id;
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							$href='index.php?option=com_templates&view=template&id=' . $item->extension_id;
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +					if ($href !== null) {
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +					if ($href !== null) {
Changed. Thanks for pointing out.

2017-12-05 09:45 UTC, brainforgeUK commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +					switch($item->type) {
Changed. Thanks for pointing out.

2017-12-05 09:46 UTC, brainforgeUK commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							if (!empty($item->search_package_id) && $item->search_package_id == $item->extension_id) {
Changed. Thanks for pointing out.

2017-12-05 15:52 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +							if (!empty($item->search_package_id) && $item->search_package_id == $item->extension_id) {
Move `{` to next line.

2017-12-05 16:08 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +					$href = null;
lines 104-129 indent. then indent this entire section in the same location as the previous code.

2018-03-20 18:47 UTC, alikon commented
can be a nice addition for 3.9 imo
after a quick test with one of mine  very old package some feedback:
![screenshot from 2018-03-20 19-44-37](https://user-images.githubusercontent.com/181681/37676079-34c1d43e-2c77-11e8-8f36-226844626836.png)

you should add the "linkable" features to modules too

2018-03-20 18:49 UTC, alikon commented on libraries/joomla/form/fields/packagelist.php
> +				'SELECT NULL FROM #__extensions AS b ' .
why not `SELECT 1` instead of `SELECT NULL`

2018-03-21 09:31 UTC, brainforgeUK commented on libraries/joomla/form/fields/packagelist.php
> +				'SELECT NULL FROM #__extensions AS b ' .
Use of NULL - habit! Unaware of any performance or other benefit.
This includes a good explanation - even suggests EXISTS ( SELECT 1/0 FROM MYTABLE ) works!
https://dba.stackexchange.com/questions/159413/exists-select-1-vs-exists-select-one-or-the-other

2018-03-21 12:36 UTC, alikon commented on libraries/joomla/form/fields/packagelist.php
> +				'SELECT NULL FROM #__extensions AS b ' .
yeah personal taste ;)

2018-04-11 20:21 UTC, Quy commented on administrator/components/com_plugins/models/forms/filter_plugins.xml
> +		>
Indent.

2018-04-11 20:22 UTC, Quy commented on administrator/components/com_installer/views/manage/tmpl/default.php
> +												// No link to current search package
Reduce indent.

2018-04-11 20:22 UTC, Quy commented on administrator/components/com_plugins/models/plugins.php
> +		if ($packageId != '')
Add blank line above.

2018-04-11 20:23 UTC, Quy commented on libraries/joomla/form/fields/packagelist.php
> +		$db->setQuery($query);
Add blank line above.

2018-04-11 20:23 UTC, Quy commented on libraries/joomla/form/fields/packagelist.php
> +		foreach ($packages as $package)
Add blank line above.

2018-04-11 20:23 UTC, Quy commented on libraries/src/Model/Form.php
> +		if (strpos($calledClass, 'User') === 0) {
Add blank line above and move `{` to its own next line.

2018-04-11 20:24 UTC, Quy commented on libraries/src/Model/Form.php
> +		// Trigger event name compatible with others in this class
Add blank line above.

2018-04-12 05:49 UTC, laoneo commented
Can you rebase that branch for Joomla 4?

2018-04-12 13:49 UTC, brainforgeUK commented
Joomla 4 - I've tried to do a pull request like this.
https://github.com/joomla/joomla-cms/pull/20152

I'm using PHPStorm, and tried rebasing to Joomla 4 as suggested, but unsuccessful.

2018-08-20 08:48 UTC, brianteeman commented
You have added completely unrelated code3 to this issue

You must use a different branch and create a different pull request for each issue you are trying to resolve

In your git client revert this latest change, commit and push

Then create a NEW branch and pull from staging
Make your new changes, commit and push
go to https://github.com/joomla/joomla-cms and you will see info that you can create a new pull request from your new branch

2018-09-08 10:15 UTC, yvesh commented on administrator/components/com_installer/helpers/installer.php
> +			    ->order('folder');
Any reason for the indentatoin change? (than you have to change others too, like $db..)

2018-09-08 15:05 UTC, ka3media commented
I have tested this item :white_check_mark: successfully on c61135430cd05cb01d659103fd97ec4cb2c28de4<br /><br />Tested on J3.9 alpha

works for me as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17585">issues.joomla.org/tracker/joomla-cms/17585</a>.</sub>

2018-09-08 15:57 UTC, alikon requested changes
use $db->quoteName()

2018-09-08 15:57 UTC, alikon commented on administrator/components/com_installer/helpers/installer.php
> +			->select('extension_id, name')
please use `$db->quotename()`

2018-09-08 15:57 UTC, alikon commented on administrator/components/com_installer/helpers/installer.php
> +			->where('type = ' . $db->quote('package'))
here

2018-09-08 15:57 UTC, alikon commented on administrator/components/com_installer/helpers/installer.php
> +			->order('name');
here

2018-09-08 15:57 UTC, alikon commented on administrator/components/com_installer/models/manage.php
> +			$query->select((int) $packageId . ' AS search_package_id')
here

2018-09-08 15:57 UTC, alikon commented on administrator/components/com_plugins/models/plugins.php
> +			      ->where('package_id = ' . (int) $packageId);
here

2018-09-08 15:57 UTC, alikon commented on libraries/joomla/form/fields/packagelist.php
> +		$query = $db->getQuery(true)
here

2018-09-08 16:48 UTC, BrainforgeUK commented on administrator/components/com_installer/models/manage.php
> +			$query->select((int) $packageId . ' AS search_package_id')
$packageId is a numeric value, not a column name.

2018-09-08 16:49 UTC, BrainforgeUK commented on administrator/components/com_plugins/models/plugins.php
> +			      ->where('package_id = ' . (int) $packageId);
$packageId is a numeric value, not a column name.

2018-09-08 17:02 UTC, BrainforgeUK commented on libraries/joomla/form/fields/packagelist.php
> +		$query = $db->getQuery(true)
Changes made.

2018-09-09 05:39 UTC, alikon commented on administrator/components/com_plugins/models/plugins.php
> +			      ->where('package_id = ' . (int) $packageId);
package_id is a field/column of the #__extensions table

2019-05-15 12:11 UTC, closed without merging

2019-05-15 12:11 UTC, Quy commented
Please rebase for J4. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17585">issues.joomla.org/tracker/joomla-cms/17585</a>.</sub>