Authorization at article level in com_content not always working: Article model
joomla/joomla-cms pull request #17735
Opened 2017-08-27 14:02 UTC by LivioCavallo

### Summary of Changes
Joomla! has a good permissions system that allows fine-grained settings in components, categories till to the article level.
In the major part of cases all these settings are correctly checked and respected but in some circumstancies 'com_content' only checks permissions at component level: article, articles and featured models.

The article model:
- `populateState` function authorises at component level and eventually filters published and archived articles.
A 'TODO' in comments seems to clearly suggest that a different authorisation was intended.
This PR authorises at article level.

- `getItem` function authorises at component level and eventually filters not-expired and not-future articles.
It seems to me that article level authorisation was simply forgotten.
This PR authorises at article level.

### Testing Instructions
Create an unpublished (or expired or pending) TEST article in "Uncategorised" category.
Set permissions in "Uncategorised" category to allow Registered user group to 'edit' and 'edit.state'.
Create e menuitem/single article -> TEST article.
Login in frontend as registered user and navigate to menuitem.

### Expected result
Page is displayed.

### Actual result
Page is NOT displayed. User has not permissions to view article, error 404, article not found.

### Notes
- This PR is related to #17725.

2017-08-27 14:03 UTC, LivioCavallo commented
Should we check for $pk==0 ? I think not, as article model is not used for new article creation (form model is used in that case)

2017-08-27 14:24 UTC, LivioCavallo commented
Why is AppVeyor failing with php7.1?

2017-08-28 06:58 UTC, laoneo requested changes

2017-08-28 06:58 UTC, laoneo commented on components/com_content/models/article.php
> +		if ((!$user->authorise('core.edit.state', 'com_content.article.' . $pk)) && (!$user->authorise('core.edit', 'com_content.' . $pk)))
Second one must also be com_content.article.

2017-08-28 07:00 UTC, laoneo commented
What wonders me if the `$pk` variable is always set. Because when not set , then this checks will always return false for none super admin users as there is no asset `com_content.`.

2017-08-28 07:50 UTC, ggppdk commented
https://github.com/joomla/joomla-cms/pull/17725#issuecomment-325146293

2017-08-28 07:53 UTC, ggppdk commented
It is wrong to check 'com_content.article.' . $pk for new records, but possibly harmless because the record (the article) does not exist yet in the DB

2017-08-28 10:26 UTC, LivioCavallo commented on components/com_content/models/article.php
> +		if ((!$user->authorise('core.edit.state', 'com_content.article.' . $pk)) && (!$user->authorise('core.edit', 'com_content.' . $pk)))
Sure. Damn me and my wrong cut&paste...

2017-08-28 11:36 UTC, LivioCavallo commented
Yes, $pk can be unset, but this is not related to the present problem with authorisation.

In fact you can always browse a malformed url, lacking id in query, and you'll get an error page: index.php?option=com_content&view=article&Itemid=101   won't work.

But this can be the chance to improve this too: I think that the component should work anyway, also when input from user is not correct, if there is a univocal intended behaviour.
In this case, the explicit article id in the url seems redundant: if the user passes a url with a correct Itemid but without an article id, it is quite sure he wants the article contained in the menuitem query string. So we can retrieve the article id from the menuitem.

I added this input check and improvement to present PR.

2017-08-28 11:42 UTC, laoneo commented
I think this was a step into the wrong direction. I would rather do like:

```
$asset = 'com_content';
if ($pk)
{
    $asset = 'com_content.article.' . $pk;
}
f ((!$user->authorise('core.edit.state', $asset))
```

2017-08-28 11:45 UTC, LivioCavallo commented
Why is that direction wrong?
It makes the component more robust, resilent to erroneous user input.

2017-08-28 11:48 UTC, laoneo commented
Because the model should not be aware about any menu. Imagine you use the model in a plugin which gets triggered when displaying a contact, then you will have a menu with a totally wrong id.

2017-08-28 13:33 UTC, LivioCavallo commented
@laoneo: You are right. Thanks. Reverted.

2017-08-28 13:36 UTC, laoneo commented
The second checks needs the same logic, or not?

2017-08-28 13:50 UTC, LivioCavallo commented
I think not, as $pk is already 'sanitized' in getItem at row 79, calling getState('article.id') that default-returns null and is converted to (int) 0.

2017-09-23 23:57 UTC, joomlabeat commented
I ended up here tonight, searching the issues regarding filtering the article model when there is no authorised user. I am working on a plugin and I need to get info for all the articles, disregarding if the user has access to it. Currently it's impossible to get an unpublished or trashed article, as it will result to a 404. 

Does this PR fixes that?

2017-09-24 13:26 UTC, LivioCavallo commented
I'm not sure I understand your question.
With this PR the model will return all and just the articles the user has permissions to edit.
So if the user has permissions on a specifit article to edit it or to edit its state then the model will return that article if it is published, archived, suspended, expired or pending.

2017-09-24 13:55 UTC, joomlabeat commented
@LivioCavallo 

In my system plugin, I am looping over an array of articles id's - trying to gather their data (e.g. catid). But if I request an article that is unpublished from the model with getItem($id) - then the model will throw a 404error. So it's impossible to get such information through the model for unpublished or trashed items.

2017-10-31 14:49 UTC, franz-wohlkoenig commented
@LivioCavallo is this PR on for Test?

2017-11-01 11:00 UTC, LivioCavallo commented
Yes, this PR is ready for Test!
And it solves the problem.

2017-11-05 09:48 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 31a121a1f394f2ad024212342308bfb04f80e7e4<br /><br />Works as expected, test on unpublished, expired and pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17735">issues.joomla.org/tracker/joomla-cms/17735</a>.</sub>

2018-09-23 16:37 UTC, twister65 commented
I have tested this item :white_check_mark: successfully on 31a121a1f394f2ad024212342308bfb04f80e7e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17735">issues.joomla.org/tracker/joomla-cms/17735</a>.</sub>

2018-09-23 16:56 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-09-26 13:54 UTC, Quy commented on components/com_content/models/article.php
> +
Remove tabs

2018-09-26 14:19 UTC, LivioCavallo commented on components/com_content/models/article.php
> +
Really? Why? All other lines in that source file use tabs

2018-09-26 14:22 UTC, mbabker commented on components/com_content/models/article.php
> +
The tabs on the empty line.

2018-09-26 14:22 UTC, brianteeman commented on components/com_content/models/article.php
> +
you have tabs on the empty line 
![image](https://user-images.githubusercontent.com/1296369/46086434-fb9aff00-c19f-11e8-836d-7075eb4c2e26.png)

2018-10-02 16:16 UTC, merged