Delete existing user_keys, if password is changed
joomla/joomla-cms pull request #17827
Opened 2017-09-01 13:30 UTC by schultz-it-solutions

Pull Request for Issue #17825 .

### Summary of Changes
new method 'onUserBeforeSave'
deletes all #__user_keys database records for current user, if he changed his password (and this option is activated in the plugin configuration.

### Testing Instructions
1.   Login on one device with activated "remember-me" checkbox and close the browser again.
2.   Login on another device and change your password here.
3.   Go back to your first device and open the website again.

### Expected result
Website should not allow you to login without providing new password

### Actual result

### Documentation Changes Required

### additional changes in other files:
https://github.com/joomla/joomla-cms/compare/staging...schultz-it-solutions:patch-1 (Plugin XML definition)
https://github.com/joomla/joomla-cms/compare/staging...schultz-it-solutions:patch-3 (Language File)
https://github.com/joomla/joomla-cms/compare/staging...schultz-it-solutions:patch-4 (Language File)

2017-09-01 13:41 UTC, dgrammatiko requested changes

2017-09-01 13:41 UTC, dgt41 commented on plugins/system/remember/remember.php
> +	 * @since   3.1
3.1 has been released few years ago :)
Please change this to `__DEPLOY_VERSION__`

2017-09-01 13:43 UTC, dgt41 commented
The code has some code styling issues:
```
--------------------------------------------------------------------------------
26s
57
FOUND 10 ERROR(S) AND 1 WARNING(S) AFFECTING 8 LINE(S)
26s
58
--------------------------------------------------------------------------------
26s
59
 100 | WARNING | Line exceeds 150 characters; contains 161 characters
26s
60
 115 | ERROR   | Please start your comment with a capital letter; found "//
26s
61
     |         | irelevant on new users"
26s
62
 116 | ERROR   | Expected "if (...)\n"; found "if (...) "
26s
63
 116 | ERROR   | Closing brace must be on a line by itself
26s
64
 117 | ERROR   | Please start your comment with a capital letter; found "//
26s
65
     |         | irelevant, because password was not changed by user"
26s
66
 118 | ERROR   | Expected "if (...)\n"; found "if (...) "
26s
67
 118 | ERROR   | Closing brace must be on a line by itself
26s
68
 119 | ERROR   | Please start your comment with a capital letter; found "//
26s
69
     |         | irelevant, because "resetting on pw change" is not activated"
26s
70
 120 | ERROR   | Expected "if (...)\n"; found "if (...) "
26s
71
 120 | ERROR   | Closing brace must be on a line by itself
26s
72
 149 | ERROR   | Please put a space between the // and the start of comment
26s
73
     |         | text; found "//$this->app->input->cookie->set($cookieName, '',
26s
74
     |         | 1, $this->app->get('cookie_path', '/'),
26s
75
     |         | $this->app->get('cookie_domain', ''));"
26s
76
--------------------------------------------------------------------------------
26s
77
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
26s
78
--------------------------------------------------------------------------------
```

2017-09-01 13:47 UTC, brianteeman commented
please add your other changes to this pr. you can do that by going to this branch in your fork and editing the files there. they will then be added automatically to this pull request

2017-09-01 14:04 UTC, wojsmol commented on plugins/system/remember/remember.php
> +	 * @since   3.7
`@since   __DEPLOY_VERSION__` as mentioned by @dgt41

2017-09-01 14:15 UTC, dgt41 commented on plugins/system/remember/remember.php
> +		/*
new line after `}`

2017-09-01 14:16 UTC, dgt41 commented on plugins/system/remember/remember.php
> +		// Irrelevant, because password was not changed by user
new line after `}`

2017-09-01 14:16 UTC, dgt41 commented on plugins/system/remember/remember.php
> +		// Irrelevant, because "resetting on pw change" is not activated
new line after `}`

2017-09-01 14:16 UTC, dgt41 commented on plugins/system/remember/remember.php
> +		$this->app->enqueueMessage(JText::_('COM_USERS_PROFILE_SAVE_REMEMBERME_USERINFO'), 'notice');
new line after `}`

2017-09-01 15:10 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_system_remember.ini
> +PLG_REMEMBER_RESET_DESC="Should the 'remember-me' functionality be reset (recommended), when a user changes his password? This will render any existing login cookies on other devices useless."
Sort keys in alpha order. 
Remove comma before `when`.
Remove `his` to be gender neutral.

2017-09-01 15:10 UTC, Quy commented on plugins/system/remember/remember.php
> +
Remove blank line.

2017-09-01 15:12 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_system_remember.ini
> +PLG_REMEMBER_RESET_LABEL="reset on password change"
Capitalize each word.

2017-09-01 15:13 UTC, Quy commented on plugins/system/remember/remember.php
> +		return true;
Add a blank before line 163.

2017-09-01 15:14 UTC, mbabker commented on administrator/language/en-GB/en-GB.plg_system_remember.ini
> +PLG_REMEMBER_RESET_DESC="Should the 'remember-me' functionality be reset (recommended), when a user changes his password? This will render any existing login cookies on other devices useless."
Use this string please:

"When enabled, a user's login cookies will be invalidated when their password is reset."

2017-09-01 15:16 UTC, Quy commented
Please follow XML coding style:
https://developer.joomla.org/coding-standards/xml.html

2017-09-01 15:18 UTC, mbabker commented on language/en-GB/en-GB.com_users.ini
> +COM_USERS_PROFILE_SAVE_REMEMBERME_USERINFO="Your password change was successful. For your security, we also deactivated any existing 'remember-me' logins on other devices."
I don't think we actually need to explicitly say "your remember me cookies are invalidated", I can't say I see this come up on other platforms where I have a remember me login in place, the device just knows the next time I use it to access a service I need to reauthenticate (well, the server tells it when it tries to automatically log in, but that's all transparent to the user).

2017-09-01 15:25 UTC, schultz-it-solutions commented on administrator/language/en-GB/en-GB.plg_system_remember.ini
> +PLG_REMEMBER_RESET_DESC="Should the 'remember-me' functionality be reset (recommended), when a user changes his password? This will render any existing login cookies on other devices useless."
done, as per mbabker suggestion

2017-09-01 15:26 UTC, schultz-it-solutions commented on plugins/system/remember/remember.php
> +
done

2017-09-01 15:28 UTC, schultz-it-solutions commented on plugins/system/remember/remember.php
> +		return true;
done

2017-09-01 15:33 UTC, schultz-it-solutions commented on language/en-GB/en-GB.com_users.ini
> +COM_USERS_PROFILE_SAVE_REMEMBERME_USERINFO="Your password change was successful. For your security, we also deactivated any existing 'remember-me' logins on other devices."
This might seem 'over-the-top', but it was intended to 'reassure the user, everything is settled'. We could ignore this message OR (which I would prefer) let the website administrator decide whether to show this message or not (another configuration option in the plugin).

2017-09-01 15:39 UTC, schultz-it-solutions commented on administrator/language/en-GB/en-GB.plg_system_remember.ini
> +PLG_REMEMBER_RESET_LABEL="reset on password change"
not sure about this, I suggest:

Reset on password change

2017-09-01 17:16 UTC, dgt41 commented on language/en-GB/en-GB.com_users.ini
> +COM_USERS_PROFILE_SAVE_REMEMBERME_USERINFO="Your password change was successful. For your security, we also deactivated any existing 'remember-me' logins on other devices."
I'm also in favour of less clutter...

2017-09-01 17:18 UTC, Bakual commented
Do we really need an option for that? I would just go without it.
If you really want that parameter, the default values in code and in XML will have to match to prevent unexpected behavior.

2017-09-01 17:19 UTC, Bakual commented on language/en-GB/en-GB.com_users.ini
> +COM_USERS_PROFILE_SAVE_REMEMBERME_USERINFO="Your password change was successful. For your security, we also deactivated any existing 'remember-me' logins on other devices."
I would also not show the message.

2017-09-01 17:38 UTC, Bakual commented
Another thing to consider: You put the code into the "System - Remember" plugin, but that is actually just a proxy plugin so the real "Authentication - Cookie" plugin can do its work. So this code should go into that authentication plugin instead.

2017-09-01 17:40 UTC, mbabker commented
If we aren't importing authentication plugins in the MVC for CRUD actions then this is the right plugin.

2017-09-01 18:12 UTC, Bakual commented
How about we import the authentication plugins instead? I'd say that should be easy and could be useful for other authentication plugins as well. I don't think it's a good idea to spread the logic of the cookie plugin (again) over multiple ones. If we can, it should be kept within the cookie one.

2017-09-01 18:22 UTC, mbabker commented
The authentication plugins shouldn't be handling CRUD actions (since some people seem to be overly concerned about what tasks specific plugin groups actually listen to, apparently we should have a "User - Remember Me" plugin for this task if you buy into their thinking 😉 ).

The authentication plugins in general aren't treated the same as every other plugin group, there are actually only two places in core where they are actually loaded as "real" plugins otherwise the Authentication class pulls the plugin objects out of the dispatcher and direct calls the methods (so not using the event system).  I would be hesitant to add more plugin based functionality to this plugin group since it is not treated as a correct plugin group (if we want to use it as a real plugin group the authentication system needs to be refactored to use proper events and not the crap logic it has now).

As far as where the code is, things are fine right now.

2017-09-01 18:55 UTC, schultz-it-solutions commented
On the "user message": I may be "over sensible" in this respect, because of the underlying story why this pr exists...
If you think this user message is "clutter", I am not oposing this!

2017-09-01 21:16 UTC, Bakual requested changes

2017-09-01 21:16 UTC, Bakual commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death (see https://www.alicerugglestrust.org )
Please remove this reference to Alice Ruggles and especially also the URL as it serves no purpose within code.

2017-09-01 21:16 UTC, Bakual commented on plugins/system/remember/remember.php
> +		if (!$this->app)
This isn't needed in that event to my knowledge as that event will not be fired **during** an upgrade.

2017-09-01 21:28 UTC, schultz-it-solutions commented on plugins/system/remember/remember.php
> +		if (!$this->app)
done

2017-09-01 21:35 UTC, schultz-it-solutions commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death (see https://www.alicerugglestrust.org )
I removed the URL, but I would rather like to keep the reference, as this is the underlying reason why this functionality is developed in the first place.

2017-09-02 10:02 UTC, Bakual commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death (see https://www.alicerugglestrust.org )
Honestly, I never heard of her and even after reading that she got killed after being stalked I don't get the reference. So it seems quite useless to me.
Also, on the other hand it's quite obvious why we want to invalidate existing remember-me credentials. Personally I would just add a one-line comment like `Invalidate all existing remember-me cookies after a password change`.

2017-09-02 10:03 UTC, zero-24 commented on plugins/system/remember/remember.xml
> +					class="btn-group"
`class="btn-group btn-group-yesno"` please

2017-09-02 10:58 UTC, schultz-it-solutions commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death (see https://www.alicerugglestrust.org )
Nobody expects that any given person "has heard of" each and every stalking victim, this is not the point. However, one major element in this case was that the murderer actually hacked into her online accounts to follow her movements, using exactly this "remember-me" functionality (not on Joomla though).

2017-09-03 08:29 UTC, brianteeman commented on plugins/system/remember/remember.php
>  	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death
While I fully understand and appreciate the circumstances that caused you to create this PR I am not in favour of this comment in the code. There have been other times in the past where something similar could have been done and we have not. The correct place to "note" this issue and Joomla's positive response to it would be in the release notes, wiki, documentation etc but not in the software itself.

2017-09-03 08:31 UTC, brianteeman commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death
While I fully understand and appreciate the circumstances that caused you to create this PR I am not in favour of this comment in the code. There have been other times in the past where something similar could have been done and we have not. The correct place to "note" this issue and Joomla's positive response to it would be in the release notes, wiki, documentation etc but not in the software itself.

2017-09-03 08:50 UTC, schultz-it-solutions commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death
If you suggest we mention this fact in the "release news" of the deployment version, I could agree to this and remove the comment from the code.

2017-09-05 06:29 UTC, schultz-it-solutions commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death
I would classify this PR as a "feature" (rather than a "bug fix", or "security fix"). do you agree?
If so, I suggest the following text in a "feature" section of the release-news
(see e.g.: https://www.joomla.org/announcements/release-news/5710-joomla-3-7-4-release.html )

[] Invalidate all existing remember-me cookies after a password change #17827 
This functionality was sadly inspired by the horrific events around Alice Ruggles' death

Would you agree to this? or should we even make clearer that Joomla! itself was NOT in the center of named events?

2017-09-05 11:28 UTC, mbabker commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death
If anything it would be appropriate to discuss what inspired this change as a community magazine article.  To be honest, though well intended, pointing to this fact "prominently" either in the code or a release announcement is probably not something we really want to be doing.

2017-09-05 14:49 UTC, schultz-it-solutions commented on plugins/system/remember/remember.php
> +	 * This functionality was sadly inspired by the horrific events around Alice Ruggles death
Although I understand your hesitation, it looks to me as if there is no acutal guideline to handle requests for references like this one (more like personal opinons). Maybe this is something the JDT should eventually address...
In order to not further delay this PR, I am (not fully agreeing to your opposition) revoking my request for this reference, even if I still strongly belief this would be appropriate in some (to be agreed on) format.

2017-09-05 20:14 UTC, Bakual commented
Do you guys think we need that option? Is there a reason you **do not** want to reset the cookies after a password change? Imho that "feature" should always be enabled. I don't see why someone would want to disable it. So the option could be removed to make the code simpler.

2017-09-05 21:50 UTC, brianteeman commented
Agreed. Why would you want to enable a bad option

2017-09-06 02:36 UTC, ggppdk commented
> Do you guys think we need that option? Is there a reason you do not want to reset the cookies after a password change? Imho that "feature" should always be enabled. I don't see why someone would want to disable it. So the option could be removed to make the code simpler.

I was reading this from top, and was going to write that a option should not be added, 
this behaviour should not be possible to disable !

2017-09-06 06:32 UTC, Bakual approved these changes

2017-10-24 09:08 UTC, schultz-it-solutions commented
is there anything left to be done before this PR gets merged back?

2017-10-24 09:51 UTC, franz-wohlkoenig commented
@schultz-it-solutions at least it needs 2 successfully Tests.

2017-12-19 15:46 UTC, schultz-it-solutions commented
@Quy , @dgt41 , @ggppdk 
any chance one of you guys can perform another test in order to finalize this pr?

2017-12-19 15:59 UTC, Quy commented on plugins/system/remember/remember.php
> +
Remove tabs.

2017-12-19 15:59 UTC, Quy commented on plugins/system/remember/remember.php
> +
Remove tabs.

2017-12-19 15:59 UTC, Quy commented on plugins/system/remember/remember.php
> +
Remove tabs.

2017-12-19 15:59 UTC, Quy commented on plugins/system/remember/remember.php
> +
Remove tab.

2017-12-19 16:03 UTC, Quy commented on plugins/system/remember/remember.php
> +		*/
Align `*` with the other `*`.

2017-12-19 16:04 UTC, Quy commented on plugins/system/remember/remember.php
> +		}
Remove tabs after `}`.

2017-12-20 19:06 UTC, Quy commented on plugins/system/remember/remember.php
> +
Remove blank line.

2017-12-20 19:08 UTC, Quy commented on plugins/system/remember/remember.php
> +				sprintf('Failed to delete cookie token for user %s with the following error: %s', $results[0]->user_id, $e->getMessage()),
There is no `$results`. Use `$user['username']`.

2017-12-21 11:05 UTC, Quy commented
I have tested this item :white_check_mark: successfully on f226416229b2e3bd01518529265f6ae4cc96b709<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17827">issues.joomla.org/tracker/joomla-cms/17827</a>.</sub>

2018-01-23 08:31 UTC, schultz-it-solutions commented
@dgt41 , @ggppdk
any chance one of you guys can perform another test in order to finalize this pr?

2018-01-23 17:09 UTC, csthomas commented
I have tested this item :white_check_mark: successfully on f226416229b2e3bd01518529265f6ae4cc96b709<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17827">issues.joomla.org/tracker/joomla-cms/17827</a>.</sub>

2018-01-23 17:17 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-02-07 00:33 UTC, zero-24 submitted a review, later dismissed

2018-02-07 00:33 UTC, zero-24 commented on plugins/system/remember/remember.php
> +			->where($db->quoteName('user_id') . ' = ' . $db->quote($user['username']));
hmm how can this work? Isn't the user_id just the ID and not the username?

2018-02-07 00:38 UTC, Quy commented on plugins/system/remember/remember.php
> +			->where($db->quoteName('user_id') . ' = ' . $db->quote($user['username']));
`user_id` is the `username`. The column name is misleading.

2018-02-07 00:39 UTC, Quy commented on plugins/system/remember/remember.php
> +			->where($db->quoteName('user_id') . ' = ' . $db->quote($user['username']));
For reference, I logged in as `admin` and the `user_id` is `admin` in the database.

2018-02-07 00:48 UTC, zero-24 commented on plugins/system/remember/remember.php
> +			->where($db->quoteName('user_id') . ' = ' . $db->quote($user['username']));
Ah got confused by that naming.

2018-02-07 00:49 UTC, merged

2018-02-07 00:49 UTC, zero-24 commented
Merged thanks!