Rewrote hardcoded SQL to query object
joomla/joomla-cms pull request #17921
Opened 2017-09-10 13:51 UTC by pe7er

Rewrote 4 SQL queries to query object format.

2017-09-11 17:35 UTC, alikon requested changes

2017-09-11 17:35 UTC, alikon commented on administrator/components/com_templates/models/style.php
> +			->set('home = 0')
the `home` field is declared as char/varchar in the `#__template_styles` table so should be quoted as a string

2017-09-12 06:49 UTC, pe7er commented
Thanks your correction @alikon !
I've changed it in the SQL.

2017-09-12 07:46 UTC, alikon commented
sorry to be pedantic `$db->quote('0')`   sounds better

2017-09-12 08:31 UTC, pe7er commented
@alikon No worries, you're right! 
Using $db->q() is better. I've corrected it.
Thanks!

2017-09-12 08:39 UTC, alikon approved these changes

2017-09-12 18:09 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 64e9599db1b6c4465523a019a7b9c4ac04d054f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17921">issues.joomla.org/tracker/joomla-cms/17921</a>.</sub>

2017-09-21 23:37 UTC, Quy commented on administrator/components/com_templates/models/style.php
> +			->where('client_id = ' . (int) $style->client_id . ' AND home =  ' . $db->q('1'));
Split this ``home =  ' . $db->q('1')`` into a separate where clause.

2017-10-26 09:40 UTC, franz-wohlkoenig commented
@alikon can you please inform how you have tested so we can get the needed second Test?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17921">issues.joomla.org/tracker/joomla-cms/17921</a>.</sub>

2018-02-14 16:42 UTC, FPerisa commented
I have tested this item :white_check_mark: successfully on 64e9599db1b6c4465523a019a7b9c4ac04d054f1<br /><br />Switching the default template style is working like before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17921">issues.joomla.org/tracker/joomla-cms/17921</a>.</sub>

2018-02-14 17:36 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-03-17 15:12 UTC, merged