[TemplateAdapter.php] Rewrote hardcoded SQL to query object
joomla/joomla-cms pull request #17923
Opened 2017-09-10 14:07 UTC by pe7er

Rewrote 2 SQL queries to query object format.
This code replaces PR #12748 "JInstallerAdapterTemplate - rewrote hardcoded SQL to object"

2017-09-11 17:38 UTC, alikon requested changes

2017-09-11 17:38 UTC, alikon commented on libraries/src/Installer/Adapter/TemplateAdapter.php
> +			->where($db->qn('home') . ' = 1')
same as #17921 
the `home` field is declared as char/varchar in the` #__template_styles` table so should be quoted as a string

2017-09-12 05:19 UTC, franz-wohlkoenig commented
@alikon are this PR and #17921 the same and on should be closed?

2017-09-12 06:51 UTC, pe7er commented
@franz-wohlkoenig It looks similar like #17921 but it's a different file.

2017-09-12 06:55 UTC, pe7er commented
@alikon Thanks your correction!
I've changed the SQL.

2017-09-12 08:26 UTC, pe7er commented
Changed 
->where($db->qn('home') . ' = \'1\' ')
to
->where($db->qn('home') . ' = ' . $db->q('1'))

2017-09-12 08:40 UTC, alikon approved these changes

2017-09-12 18:06 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 7268bdfb23c3742062403181d669c1587736c4d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17923">issues.joomla.org/tracker/joomla-cms/17923</a>.</sub>

2017-09-22 01:38 UTC, Quy commented on libraries/src/Installer/Adapter/TemplateAdapter.php
> +			->where($db->qn('template_style_id') . ' in (' . (string) $subQuery . ')');
Capitalize `in`

2017-09-22 01:39 UTC, Quy commented on libraries/src/Installer/Adapter/TemplateAdapter.php
> +			->from('#__template_styles s')
Change to `->from($db->qn('#__template_styles', 's'))`

2017-09-22 02:03 UTC, Quy commented on libraries/src/Installer/Adapter/TemplateAdapter.php
> +			->where($db->qn('s.client_id') . ' = ' . $db->q($clientId));
Remove `$db->q`

2017-10-26 09:38 UTC, franz-wohlkoenig commented
@alikon can you please describe how you have tested?

2017-10-26 09:51 UTC, alikon commented
install templates

2017-10-26 10:04 UTC, franz-wohlkoenig commented
@alikon install any Template or Core-Template?

2017-10-26 10:16 UTC, alikon commented
any should be enough

2017-10-26 10:25 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 7268bdfb23c3742062403181d669c1587736c4d4<br /><br />Installation of "Free Joomla 3.5 Template – jPeople" (http://www.freshjoomlatemplates.com/free-joomla-3-5-template-jpeople/) works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17923">issues.joomla.org/tracker/joomla-cms/17923</a>.</sub>

2017-10-26 10:25 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-11-01 12:02 UTC, mbabker commented
Has some requested changes that should be implemented before merging.

2018-01-16 10:00 UTC, brianteeman commented
@pe7er could you make the requested changes please so that this can be merged

2018-01-16 10:40 UTC, alikon commented
@pe7er  i've made a pr https://github.com/pe7er/joomla-cms/pull/21 to your branch with the updated requested by @Quy

2018-01-17 10:48 UTC, pe7er commented
Thanks @alikon! 
I've merged your PR into this one

2018-01-17 19:37 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 1169ef4c32bf91dcc4770d9e3022f61d51e0f358<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17923">issues.joomla.org/tracker/joomla-cms/17923</a>.</sub>

2018-01-17 19:39 UTC, alikon commented
can someone remove the RTC, update requested status, and  test

2018-01-17 19:43 UTC, franz-wohlkoenig commented
@alikon set Status back on "Pending" at Issue Tracker but RTC is still shown at Github.

2018-01-17 19:50 UTC, alikon commented
thanks folks, just another one little effort, please test

2018-02-15 12:55 UTC, FPerisa commented
I have tested this item :white_check_mark: successfully on 1169ef4c32bf91dcc4770d9e3022f61d51e0f358<br /><br />**Uninstalling** the template was successful.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17923">issues.joomla.org/tracker/joomla-cms/17923</a>.</sub>

2018-02-15 15:23 UTC, Quy commented
@brianteeman Please remove `Updates Requested` label. Thanks.

2018-02-15 15:31 UTC, brianteeman commented
@quy removed - lets see if the bot puts them back

2018-02-26 03:20 UTC, merged