[New Feature] Schedule featured articles #13596
joomla/joomla-cms pull request #18052
Opened 2017-09-21 21:08 UTC by eshiol

2017-09-21 21:17 UTC, Quy commented on administrator/components/com_content/models/featured.php
> +				'featured_down', 'featured_down',
Add `a.`

2017-09-22 00:50 UTC, Quy commented on components/com_content/models/articles.php
> +			$query->where('(a.featured_up = ' . $nullDate . ' OR a.featured_up <= ' . $nowDate . ')')
Should these lines be after `$query->where('a.featured = 1');`?

2017-09-22 06:09 UTC, eshiol commented on components/com_content/models/articles.php
> +			$query->where('(a.featured_up = ' . $nullDate . ' OR a.featured_up <= ' . $nowDate . ')')
I don't think so. The full plain query could be produced by this piece of code
```
		if ($this->getState('filter.frontpage'))
		{
			// filter only featured articles
			$query->where('a.featured = 1')
				->where('(a.featured_up = ' . $nullDate . ' OR a.featured_up <= ' . $nowDate . ')')
				->where('(a.featured_down = ' . $nullDate . ' OR a.featured_down >= ' . $nowDate . ')');
			// join #__content_frontpage for ordering
			if ($orderby_sec === 'front')
			{
				$query->join('INNER', '#__content_frontpage AS fp ON fp.content_id = a.id');
			}
		}
```		
Articles have a row in the #__content_frontpage only if a.featured = 1, so you can optimize the query
```
		if ($this->getState('filter.frontpage'))
		{
			if ($orderby_sec === 'front')
			{
				$query->join('INNER', '#__content_frontpage AS fp ON fp.content_id = a.id');
			}
			else
			{
				$query->where('a.featured = 1');
			}
			$query->where('(a.featured_up = ' . $nullDate . ' OR a.featured_up <= ' . $nowDate . ')')
				->where('(a.featured_down = ' . $nullDate . ' OR a.featured_down >= ' . $nowDate . ')');
		}
```

2017-09-22 21:51 UTC, Quy commented on administrator/components/com_admin/sql/updates/sqlazure/3.8.0-2017-09-21.sql
> +ALTER TABLE "#__content" ADD "featured_up" datetime2(0) NOT NULL DEFAULT '1900-01-01 00:00:00';
I don't use sqlazure so I don't know which syntax `"` or `[` is correct. 
See anther PR that uses `[`:
https://github.com/joomla/joomla-cms/pull/17709/files#diff-f6d977844dc2f4c65fe3e3262b042bd6

2017-09-22 22:53 UTC, Quy commented
How about changing `End` to `Finish` to be consistent elsewhere like `Finish Publishing`?

2017-09-25 13:40 UTC, WoodyF4u commented
Thanks for working on it to everybody who is joining this issue.
I am not a programmer or developer, so I can only watch and read.
Unfortunately it was not a part of Joomla! 3.8.0, I hope it will be part of one of the first Joomla! 3.8.x releases in the future.

2017-09-25 14:29 UTC, Quy commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +		$icon = $state[0];
Add blank line before and after this line.

2017-09-25 14:29 UTC, Quy commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FIELD_FEATURED_DOWN_LABEL="End Featured"
Change to `Finish`

2017-09-25 14:30 UTC, Quy commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FIELD_FEATURED_DOWN_DESC="An optional date to end the article being featured."
Change to `finish`

2017-09-25 18:25 UTC, Quy commented
In the Featured tooltip, seconds is displayed, but not in the Publishing tooltip. To be consistent, do not display the seconds.

2017-09-25 20:17 UTC, Quy commented
Installation SQLs have to be updated with the new columns.

2017-09-26 14:36 UTC, Quy commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +
Remove tabs.

2017-09-26 14:36 UTC, Quy commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +
Remove tabs.

2017-09-26 14:37 UTC, Quy commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +
Remove tab.

2017-09-26 14:37 UTC, Quy commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +
Remove tab.

2017-09-26 14:38 UTC, Quy commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +
Remove tab.

2017-09-27 06:55 UTC, alikon requested changes
from a data model point of view  these attributes 

- `featured_up`
- `featured_down` 

should belong to the `#__content_frontpage` table and not to the `#__content` table

2017-09-27 07:23 UTC, eshiol commented
Is the `#__content_frontpage` table really needful (performace issues)? Why you don't use the field `#__content.featured` to store the ordering info?

2017-09-27 20:23 UTC, Quy commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +			// Create tip text, only we have publish up or down settings
Change `publish` to `featured`.

2017-09-27 23:59 UTC, Quy commented on administrator/language/en-GB/en-GB.lib_joomla.ini
> +JLIB_HTML_FEATURED_FINISHED="Finished: %s"
Do we need `Finished:` & `Started:`? Under Publishing tooltip, this is not done.

2017-09-29 06:09 UTC, eshiol commented on administrator/language/en-GB/en-GB.lib_joomla.ini
> +JLIB_HTML_FEATURED_FINISHED="Finished: %s"
Under Publishing tooltip, you have `Published and is Current` and `Published, but has Expired`
Under Featured tooltip, you have `Featured` in both cases

2017-09-29 15:02 UTC, Quy commented on administrator/language/en-GB/en-GB.lib_joomla.ini
> +JLIB_HTML_FEATURED_FINISHED="Finished: %s"
OK. I see you indicate its status in the labels vs. in the description with Publishing.

2017-10-19 05:47 UTC, eshiol commented
Please, remove the tag "Test instructions missing"

2017-10-19 06:15 UTC, brianteeman commented
done

2017-10-28 11:08 UTC, franz-wohlkoenig commented
@brianteeman Tag "Test instructions missing" is shown at Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2017-10-28 11:48 UTC, brianteeman commented
@franz-wohlkoenig I only have access to change it on github

2017-10-28 12:41 UTC, franz-wohlkoenig commented
thanks for Info, @brianteeman. As i can't too at Tracker Tag remains.

2017-12-08 10:31 UTC, WoodyF4u commented
Are there plans to introduce this issue to a new release of Joomla! 3.8?
Or will this be developped for a later release like 3.9 or 4?

2017-12-08 10:39 UTC, rdeutz commented
Because it is a new feature it can't go into a 3.8.x release so it has to wait for 3.9. 

I agree with the comment @alikon made, "featured_up" and "featured_down" fields should go into the "#__content_frontpage" table.

2018-03-01 13:11 UTC, ghazal commented
Many people would be happy with this feature.
After installation, I get an error 500 though:

> Unknown column 'a.featured_up' in 'field list'

2018-03-01 13:11 UTC, ghazal commented
I have tested this item :red_circle: unsuccessfully on 40bb8bdec04c0da60d26027da91e3c5f4b0003f8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-03-05 10:20 UTC, eshiol commented
You have to add the two fields `featured_up` and `featured_down` to the table `#__content`

2018-05-17 16:14 UTC, WoodyF4u commented
Hi to all the people who are working for this new feature.
What is the status nbow?
Will this feature be a part of Joomla! 3.9 ?

2018-08-23 14:07 UTC, WoodyF4u commented
Hello, I still hope this new feature will be part of Joomla! soon.
Can anyone tell me the status of developing this?

2018-08-23 14:15 UTC, franz-wohlkoenig commented
@WoodyF4u there is one unsuccessfully Test, but every Pull Request need at least 2 successfully Tests before a Maintainer decide if PR get merged.

2018-08-23 14:15 UTC, brianteeman commented
currently it has no successful tests

2018-08-23 14:22 UTC, ghost commented
>  I am not a programmer or developer, so I can only watch and read.

@WoodyF4u you can test - i'm also no Developer;-)

Edit: [How to test](https://brian.teeman.net/joomla/873-a-dummies-guide-to-joomla-bug-testing)

2018-08-24 10:28 UTC, franz-wohlkoenig commented
I have tested this item :red_circle: unsuccessfully on 4f06f6da4830516d82ca9754d351b306aea3557d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-08-29 19:48 UTC, WoodyF4u commented
Hello,
Today I installed Joomla! 4.0 alpha 5.
I hoped to see the new feature in this release.
But I can set an article as featured, but there are no fields to set the start and stop moments for publishing as featured.

So can anyone tell me how I can
![2018-08-29 2-articles_ edit - joomla40-test-administration](https://user-images.githubusercontent.com/6384416/44811546-3b88b980-abd5-11e8-98b5-b131db275828.png)
 test this new feature>

2018-08-29 19:54 UTC, franz-wohlkoenig commented
@WoodyF4u the Pull Request by @eshiol is for Joomla 3. As you can read above this PR needs  2 successfully Tests as next Step.

2018-08-29 20:01 UTC, franz-wohlkoenig commented
for Test this PR needs also an Update ([Comment](https://github.com/joomla/joomla-cms/pull/18052#issuecomment-415719897))

2018-08-30 08:33 UTC, ghazal commented
at least, 19 files to check if not update.

2018-09-04 10:02 UTC, eshiol commented
The patch tester component doesn't run the update sql files. You have to manually run the file administrator/components/com_admin/sql/updates/<database server type>/3.8.0-2017-09-21.sql to modify the database structure.

2018-09-08 10:21 UTC, crommie commented
I have tested this item :red_circle: unsuccessfully on 4f06f6da4830516d82ca9754d351b306aea3557d<br /><br />Modified database according to instructions.

Tried to apply patch. 

Error: The file marked for modification does not exist: administrator/components/com_content/helpers/html/contentadministrator.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-09-14 10:31 UTC, brianteeman approved these changes
approve language strings

2018-10-08 08:38 UTC, johanpeters commented
hello.. i am looking for this feature.. and hopes its gettings build in the core joomla.
for now i am happy to test this feature.. but tell my what to do...

2018-10-08 09:03 UTC, infograf768 commented
@crommie
You are testing on a 4.0 where that file does not exist indeed.
It does in staging (3.8.x).

2018-10-08 13:25 UTC, ReLater commented
### What you have to do for testing this pr: Testing Instructions.
- Install nightly build of Joomla **3.9** (**Important!**) with testing sample data (I used Learn Joomla)
https://developer.joomla.org/nightly-builds.html
**One can't test with 3.8.12 without additional steps because of changes of the database by other PRs!**
- Install "Joomla Patch Tester" https://github.com/joomla-extensions/patchtester/releases
(I use Patch Tester 3.0.0 Beta 4)
- "Fetch Data" in Joomla Patchtester.
- Search for 18052 and Apply this patch. 

**Before you do anything else:**
- **Go to Extensions > Manage > Database and click the Fix button!**

- Now you can follow the Testing Instructions of first post by @eshiol 

- Be aware of the timezone shift of your server settings that may lead to not displayed articles. Change the hour value of "Start Featured" accordingly.

2018-10-08 14:19 UTC, johanpeters commented
okay.. i followed the steps  using..

1. Install nightly build of Joomla 3.9 (Important!) with testing sample data (I used Learn Joomla)
2. Install "Joomla Patch Tester" https://github.com/joomla-extensions/patchtester/releases
3. "Fetch Data" in Joomla Patchtester.
4. Search for 18052 and Apply this patch.
5. Go to Extensions > Manage > Database and click the Fix button!

6. **Skipped: i did not find the file:** modify the database structure using the file 3.8.0-2017-09-21.sql
7 create 5 articles:
article 1, not featured
article 2, featured, featured_up = null, featured_down = null
article 3, featured, featured_up = tomorrow, featured_down = null
article 4, featured, featured_up = null, featured_down = yesterday
article 5, featured, featured_up = yesterday, featured_down = tomorrow

8. Create an Articles » Featured Articles menu item
Results:
the results are as the discribed.. only 2 documents are published..

2018-10-08 14:31 UTC, ReLater commented
@johanpeters 
Go to patch tester and click the orange button in column "Issue Tracker". There after login:
![08-10-_2018_16-30-28](https://user-images.githubusercontent.com/20780646/46615033-93410b80-cb17-11e8-9637-86dfbd2a2f75.jpg)

2018-10-08 14:37 UTC, johanpeters commented
I have tested this item :white_check_mark: successfully on d079f141a71c232d0f56b7e3558441952ca359f9<br /><br />okay.. i followed the steps using..

Install nightly build of Joomla 3.9 (Important!) with testing sample data (I used Learn Joomla)

Install "Joomla Patch Tester" https://github.com/joomla-extensions/patchtester/releases

"Fetch Data" in Joomla Patchtester.

Search for 18052 and Apply this patch.

Go to Extensions > Manage > Database and click the Fix button!

Skipped: i did not find the file: modify the database structure using the file 3.8.0-2017-09-21.sql
7 create 5 articles:
article 1, not featured
article 2, featured, featured_up = null, featured_down = null
article 3, featured, featured_up = tomorrow, featured_down = null
article 4, featured, featured_up = null, featured_down = yesterday
article 5, featured, featured_up = yesterday, featured_down = tomorrow

Create an Articles » Featured Articles menu item
Results:
the results are as the discribed.. only 2 documents are published..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-08 14:38 UTC, johanpeters commented
@ReLater ..thanks.. i updated and test this.. 
thanks.. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-09 10:03 UTC, johanpeters commented
Functionality works 100% from backend.. frontend is (not) implemented

2018-10-09 12:34 UTC, ReLater commented
> frontend is (not) implemented

Maybe I just don't understand because of the "(not)". I see the new fields in tabulator Publishing of frontend edit view as Super User.

2018-10-09 13:48 UTC, johanpeters commented
On the frontendI do see the default feature option yes/no..But when selecting yes i dont get the xtra start and finish feature publishing date fields.



Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: ReLater <notifications@github.com> Datum: 09-10-18  14:35  (GMT+01:00) Aan: joomla/joomla-cms <joomla-cms@noreply.github.com> Cc: johanpeters <j.peters@itics.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [joomla/joomla-cms] [New Feature] Schedule featured articles #13596 (#18052) 

frontend is (not) implemented

Maybe I just don't understand because of the "(not)". I see the new fields in tabulator Publishing of frontend edit view as Super User.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joomla/joomla-cms","title":"joomla/joomla-cms","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/joomla/joomla-cms"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ReLater in #18052: \u003e frontend is (not) implemented\r\n\r\nMaybe I just don't understand because of the \"(not)\". I see the new fields in tabulator Publishing of frontend edit view as Super User."}],"action":{"name":"View Pull Request","url":"https://github.com/joomla/joomla-cms/pull/18052#issuecomment-428174317"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/joomla/joomla-cms/pull/18052#issuecomment-428174317",
"url": "https://github.com/joomla/joomla-cms/pull/18052#issuecomment-428174317",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [joomla/joomla-cms] [New Feature] Schedule featured articles #13596 (#18052)",
"sections": [
{
"text": "",
"activityTitle": "**ReLater**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ReLater",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"joomla/joomla-cms\",\n\"issueId\": 18052,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"joomla/joomla-cms\",\n\"pullRequestId\": 18052\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/joomla/joomla-cms/pull/18052#issuecomment-428174317"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 260025832\n}"
}
],
"themeColor": "26292E"
}
]

2018-10-09 14:04 UTC, johanpeters commented
![image](https://user-images.githubusercontent.com/1411354/46674643-fa74c380-cbdc-11e8-8c0e-438482f81321.png)

2018-10-09 14:06 UTC, johanpeters commented
i don't see it in frontpage.. seee image.
![screencapture-itics-net-joomladev-index-php-using-joomla-extensions-modules-utility-modules-smart-search-2018-10-09-16_01_01](https://user-images.githubusercontent.com/1411354/46674735-390a7e00-cbdd-11e8-8ba5-17f35c9a661c.png)

2018-10-09 14:42 UTC, ReLater commented
@johanpeters 
My fault. Yes, you're right. You should send an additional unsuccessful test then.

2018-10-09 14:52 UTC, johanpeters commented
If i read the test criteria.. the test passes.Because its completly focused on the backend.
But the feature schould be on the frontend also.. 
Question is.. is frontend included .. en test fail.. or not included and test pass..
Of not oncluded tjen a new version schould be created to enable frontend.. but this can then be implemented as is.. a lot of people are waiting for this feature.. 
Next version include frontend.. And maybe a default to set .. if featured is yes then default 7 days.. or something



Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: ReLater <notifications@github.com> Datum: 09-10-18  16:43  (GMT+01:00) Aan: joomla/joomla-cms <joomla-cms@noreply.github.com> Cc: johanpeters <j.peters@itics.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [joomla/joomla-cms] [New Feature] Schedule featured articles #13596 (#18052) 
@johanpeters

My fault. Yes, you're right. You should send an additional unsuccessful test then.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joomla/joomla-cms","title":"joomla/joomla-cms","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/joomla/joomla-cms"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ReLater in #18052: @johanpeters \r\nMy fault. Yes, you're right. You should send an additional unsuccessful test then."}],"action":{"name":"View Pull Request","url":"https://github.com/joomla/joomla-cms/pull/18052#issuecomment-428219855"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/joomla/joomla-cms/pull/18052#issuecomment-428219855",
"url": "https://github.com/joomla/joomla-cms/pull/18052#issuecomment-428219855",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [joomla/joomla-cms] [New Feature] Schedule featured articles #13596 (#18052)",
"sections": [
{
"text": "",
"activityTitle": "**ReLater**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ReLater",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"joomla/joomla-cms\",\n\"issueId\": 18052,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"joomla/joomla-cms\",\n\"pullRequestId\": 18052\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/joomla/joomla-cms/pull/18052#issuecomment-428219855"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 260025832\n}"
}
],
"themeColor": "26292E"
}
]

2018-10-09 15:00 UTC, ReLater commented
I have tested this item :red_circle: unsuccessfully on d079f141a71c232d0f56b7e3558441952ca359f9<br /><br />New options aren't displayed in front-end even if a Super User is editing an article.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-09 15:28 UTC, johanpeters commented
I have tested this item :red_circle: unsuccessfully on d079f141a71c232d0f56b7e3558441952ca359f9<br /><br />The test for backend is complete succesfully.. 
but when create or edit an article from frontend with super user rights you don't see the start end stop feature date field.
on non features articles and on features articles.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-10 19:50 UTC, johanpeters commented
@eshiol.. was it developed to work on frontend also.. if yes then test failed.
If no.. then test is succesful

2018-10-11 06:29 UTC, eshiol commented
The pull request is not designed to work on the frontend, but I think it should be. I'll write the code as soon as possible.

2018-10-11 06:42 UTC, johanpeters commented
@eshiol Greate.. a frontend integration would be greate.. 
@ReLater 
okay.. than i will change the test results to succes.. it works like design.. 
@ReLater can you change your result also..

2018-10-11 06:43 UTC, johanpeters commented
I have tested this item :white_check_mark: successfully on d079f141a71c232d0f56b7e3558441952ca359f9<br /><br />the current implementation works .. there is no frontend integration build in.. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-12 08:37 UTC, johanpeters approved these changes

2018-10-12 08:38 UTC, johanpeters approved these changes

2018-10-12 08:38 UTC, johanpeters approved these changes

2018-10-12 08:45 UTC, eshiol commented
frontend code added

2018-10-12 09:03 UTC, johanpeters commented
I have tested this item :white_check_mark: successfully on 3cecb32ede66cf3a17b3004ea682a13a10ade105<br /><br />succesfull test incl frontend.. 
request:  on frontend when selecting featured Yes then first the start / end Featured date and below the start/stop publisher date.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-12 09:04 UTC, johanpeters commented
@eshiol .. tested Okay.. can you take a look at my request.. (other order of start/end date fields on frontend).
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-12 09:27 UTC, infograf768 commented
Modifications in `en-GB.lib_joomla.ini` have to be done both in administrator and site files.

2018-10-12 09:33 UTC, infograf768 commented
`administrator/components/com_admin/sql/updates/mysql/3.8.0-2017-09-21.sql` has Windows EOL.
Should be UNIX.

2018-10-12 09:41 UTC, infograf768 requested changes

2018-10-12 09:41 UTC, infograf768 commented on administrator/components/com_content/models/featured.php
> +        'a.created_by, a.featured, a.featured_up, a.featured_down, a.language, a.created_by_alias, a.publish_up, a.publish_down, a.note'
use tab for indent and align to former line.

2018-10-12 09:55 UTC, infograf768 commented
Also, looks like there is an issue with EOLs in
/Applications/MAMP/htdocs/trunkgitnew/tests/unit/schema/sqlsrv.sql
But this could be unrelated to this patch. Has to be corrected imho

2018-10-12 10:00 UTC, eshiol commented
> @eshiol .. tested Okay.. can you take a look at my request.. (other order of start/end date fields on frontend).
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/18052](https://issues.joomla.org/tracker/joomla-cms/18052).

fixed

2018-10-12 10:04 UTC, johanpeters commented
I have tested this item :white_check_mark: successfully on 3cecb32ede66cf3a17b3004ea682a13a10ade105<br /><br />Order frontend checked and okay... 
Greate... i dont see any issues anymore.. so if its on me.. lets go public..

translation in dutch on request.. ;-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-12 10:05 UTC, johanpeters commented
Note: al the test that i did whas without the use of the sql file... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2018-10-12 10:08 UTC, infograf768 commented
@johanpeters 
It is NOT finished. See my comments above.

2018-10-12 10:20 UTC, johanpeters commented
@infograph..
Are you ref. to the sql file issues?.
I have tested it withoud the sql file as part of this patch test describtion because i could not find it.. what schould be the fu tion of the sql file?  The schedule feature works for me as aspected..

2018-10-12 10:25 UTC, eshiol commented
> Modifications in `en-GB.lib_joomla.ini` have to be done both in administrator and site files.

featured up/down is a feature of com_content, I think `en-GB.com_content.ini` is better than `en-GB.lib_joomla.ini`, imho

2018-10-12 10:26 UTC, eshiol commented on administrator/components/com_content/models/featured.php
> +        'a.created_by, a.featured, a.featured_up, a.featured_down, a.language, a.created_by_alias, a.publish_up, a.publish_down, a.note'
fixed

2018-10-12 12:12 UTC, mbabker commented
> I have tested it withoud the sql file as part of this patch test describtion because i could not find it.. what schould be the fu tion of the sql file?

To update the database with the two new columns needed to make this feature work.  In one of your earlier comments, you noted you "Go to Extensions > Manage > Database and click the Fix button!", in which case with the patch applied the relevant SQL file would've been run and you wouldn't need to manually do anything.

As for finding it, if you click the files tab on any GitHub pull request, the list of files and the paths match up exactly to where it should exist in a Joomla site.  So if you had the patch applied and didn't have a `administrator/components/com_admin/sql/updates/<database>/3.8.0-2017-09-21.sql` file in your site when you hit the fix button then the new database columns couldn't have been added to the site and testing the feature wouldn't have worked as you would eventually have run into a SQL error.

2018-10-12 13:13 UTC, johanpeters commented
@mbabker .. thanks for the explanation.. 
in the first installation i did hit the fix Button after installation. If that wil run the sql file than i have used it.. the  tests i did after that the only thing i did was remove the patch and reinstall the latest patch version.. no fix button.. but simple test and check of the function was working incl. the add functionality..

2018-10-12 13:21 UTC, mbabker commented
Because the database columns were still there.  Patch tester doesn't ever touch the database schema and there is no rollback capability for schema changes.

2018-10-12 15:47 UTC, Quy commented on components/com_content/models/articles.php
> +		$nullDate = $db->q($db->getNullDate());
Please change `$db->q` to `$db->quote`

2018-10-13 05:39 UTC, infograf768 commented
@eshiol 
I think you did not understand.

This PR adds strings to https://github.com/joomla/joomla-cms/pull/18052/files#diff-fa3a45e6746f58d4a54e42207ee8f4ad

That is OK as these strings could indeed be used for example for Contacts which has also a featured status.
BUT, therefore, the SAME modifications should be done in the frontend file!
`ROOT/language/en-GB/en-GB.lib_joomla.ini`
as these 2 files should be in sync.

2018-10-13 06:08 UTC, eshiol commented
@infograf768
You are right. Fixed.

2018-10-13 07:01 UTC, infograf768 approved these changes

2018-10-15 19:30 UTC, phproberto commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +	public static function featured($value = 0, $i, $canChange = true, $featured_up = null, $featured_down = null)
Please be consistent with var names in camelCase format. Use`$featuredUp` & `$featuredDown`

2018-10-15 19:35 UTC, phproberto commented on components/com_content/models/articles.php
> +				->where('(a.featured_down = ' . $nullDate . ' OR a.featured_down >= ' . $nowDate . ')');
I know vars are escaped but I recommend you to ALWAYS sanitise vars when using them in the query. With something like:


```php
->where('(a.featured_down = ' . $db->q($nullDate) . ' OR a.featured_down >= ' . $db->q($nowDate) . ')');
```

Benefits:

* It's easy to see the query is secure.
* You can reuse vars to make other calculations like compare dates, etc.
* It's safe for future changes. It prevents someone changing escaped lines and converting a secure query into an insecure query

2018-10-16 06:58 UTC, eshiol commented on administrator/components/com_content/helpers/html/contentadministrator.php
> +	public static function featured($value = 0, $i, $canChange = true, $featured_up = null, $featured_down = null)
fixed

2018-10-16 07:04 UTC, eshiol commented on components/com_content/models/articles.php
> +				->where('(a.featured_down = ' . $nullDate . ' OR a.featured_down >= ' . $nowDate . ')');
You're right, but $nullDate = $db->quote($db->getNullDate()); it is more efficient and you can find it in many pieces of code. I think the issue deserves further study, and the result should be included in the Coding Standards Manual - Joomla! Developer network.

2018-10-16 12:46 UTC, phproberto commented on components/com_content/models/articles.php
> +				->where('(a.featured_down = ' . $nullDate . ' OR a.featured_down >= ' . $nowDate . ')');
It's not `more efficient`. We are talking about escaping a string. Readability + security totally "pay" the change. 

Anyway I was only recommending what I use as standard for dev teams. Your code is totally correct.

Thanks for changing the camelCase vars!

There is still a [code style error](http://ci.joomla.org/joomla/joomla-cms/11563/4):


```
FILE: ...inistrator/components/com_content/helpers/html/contentadministrator.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 101 | ERROR | Expected 2 spaces after the longest variable name
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

You have to remove a space after `$featuredDown` in docblock :

```
* @param   string   $featuredDown   An optional finish featured date.
```

And align the other params descriptions.

2019-01-17 09:07 UTC, johanpeters commented
Hello.. what is the current status of this feature.. when will this be released or build in the core joomla?.. 
i need this feature for multiple website's.. as far as i can see and have tested it it works for me.. 

greetings.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2019-01-17 10:57 UTC, HLeithner commented
@johanpeters 3.x series has a feature freeze, so this PR hast to be ported to J4 and maybe get included in in Joomla 4.0

2019-01-17 11:33 UTC, brianteeman commented
@HLeithner you really need to announce (and define) this feature freeze and then review and update ALL the existing issues and PR.

No point in having open feature PR for the J3 branch
No point in having open feature Issues for the J3 branch

AND ensure that all new PR and Issues for the J3 branch are commented on appropriately - just leaving them there just creates frustration and WASTES TIME for everyone

2019-01-17 11:47 UTC, HLeithner commented
@brianteeman thats not my decision thats from the last Production meeting Report:
https://volunteers.joomla.org/departments/production/reports/936-production-meeting-december-2018

- There was a discussion about . It was voted to reject this and stick to the current plan of having 3.10 as the bridge release for Joomla 4

Also reflected in the Roadmap https://developer.joomla.org/roadmap.html

- Note: Joomla! 3.9 will be the last 3.x release with new features, all new features have to go into Joomla! 4.

I'm not in the position to say that this is valid for all PR's so maybe there are PR's that gets into a patch level which adds a small feature. 

My comment may was not detailed enough, sry for this.

2019-01-17 11:53 UTC, brianteeman commented
There is a missing word or phrase in the minutes that says what the proposal was that was discussed - the community are not mind readers

2019-01-17 11:58 UTC, HLeithner commented
maybe @wilsonge can tell us more about this. I'm not part of the production team atm.

2019-01-17 12:24 UTC, Bakual commented
We discussed this in the last days in the maintainers chat and George wanted to see with Sandra to write something.

2019-01-17 12:29 UTC, brianteeman commented
@bakual thank you - I had given up ever getting a reply from @wilsonge

2019-04-15 10:59 UTC, wilsonge commented
Let's get this rebased onto j4 and get a fresh test. seems like a nice feature :)

2019-05-11 06:23 UTC, alikon commented
As we are in feature freeze
all new features have to go into Joomla! 4.

Please rebase this nice feature in J4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>

2019-08-23 14:49 UTC, closed without merging

2019-08-23 14:50 UTC, Quy commented
PR #25979 rebased for J4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18052">issues.joomla.org/tracker/joomla-cms/18052</a>.</sub>