Datepicker with 12 hour time format midnight error
joomla/joomla-cms pull request #18240
Opened 2017-10-04 23:38 UTC by brianteeman

PR for #17938

Thanks to @gclw for the code and his patience

### Test instructions
in \administrator\components\com_content\models\forms\article.xml
add the following two lines to the "created" field

`timeformat="12"
format="%Y-%m-%d %H:%M:%S"
`
As you set the time in the calendar observe the time in the field. 
1. Set the time to 4pm and the field shows 16:00
2. Now set the time to 12am and the field will show 12:00

This is the bug. It should show 00:00

Apply this PR,clear cache, and it will behave correctly as in the video below

### after PR

![clock](https://user-images.githubusercontent.com/1296369/31204796-750f8dfa-a965-11e7-95f0-e5e94d1ac7de.gif)

2017-10-05 04:15 UTC, ggppdk commented
if i popup calendar in the hour, minute field if i select

10:00 am it shows 10:00
11:00 am it shows 11:00
12:00 am it shows 00:00

10:00 pm it shows 22:00
11:00 pm it shows 23:00
12:00 pm it shows 12:00

i do not say that this change is wrong
it seems correct

but there is an ux problem, that the hours selector 12 is placed after 11,
thus user selecting would expected it to show something bigger right ?

@dgt41 
maybe replace 12 with 00 when calendar is shown in am / pm format , and of course place 00 on top of the hours drop down selector ?

2017-10-05 05:13 UTC, brianteeman commented
That is beyond the scope of this pr

2017-10-05 08:42 UTC, dgrammatiko requested changes

2017-10-05 08:42 UTC, dgt41 commented on media/system/js/fields/calendar.js
> +			} else if (/am/i.test(ampm.value) && hours == 12) {
@brianteeman please revert the strict check

2017-10-05 08:52 UTC, brianteeman commented on media/system/js/fields/calendar.js
> +			} else if (/am/i.test(ampm.value) && hours == 12) {
If I do that then it doesnt work :(

2017-10-05 12:41 UTC, GCLW commented
@ggppdk 
I think it would be wise to keep the hour selector containing only 1-12 in when using the timeformat=12 attribute. Only when the timeformat=24 is used should there be a "00" in the selector. There is no UX problem. it is a logical range 01-12 that stays consistent, the user only selects if it is AM or PM.

I think you are trying to force the logic that if someone were to select 11 PM and changed their mind to make it midnight they would just bump up the 11 to a 12, which effectively now makes it 12 PM (noon). That is not a UX problem. That is 100% user error.

The correct logic by a user would be "I have it set to 11:30pm, but I need to change it to midnight. The user would then change the 11 to a 12 and change PM to AM. That is the user logic.

2017-10-05 12:47 UTC, brianteeman commented
it is out of scope for this Pr anyway

2017-10-05 13:45 UTC, GCLW commented on media/system/js/fields/calendar.js
> +			} else if (/am/i.test(ampm.value) && hours == 12) {
It you want to keep the strict compare "===" you would have to use parseInt(). I think the hours var is being recognized as a string.

`} else if (/am/i.test(ampm.value) && parseInt(hours) === 12) {`

2017-10-28 10:50 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on fae7637162109828f2d8ff897753cdedfc9515e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18240">issues.joomla.org/tracker/joomla-cms/18240</a>.</sub>

2017-11-12 10:05 UTC, franz-wohlkoenig commented
marked as "Easy test".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18240">issues.joomla.org/tracker/joomla-cms/18240</a>.</sub>

2017-11-15 13:19 UTC, FPerisa commented
I have tested this item :white_check_mark: successfully on fae7637162109828f2d8ff897753cdedfc9515e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18240">issues.joomla.org/tracker/joomla-cms/18240</a>.</sub>

2017-11-15 14:22 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-11-18 15:52 UTC, merged