Enhance Content - Contact plugin
joomla/joomla-cms pull request #18258
Opened 2017-10-06 16:39 UTC by mattiaverga

### Summary of Changes
Currently Content - Contact plugin can only link the author name to the internal page of the contact associated to the author of the article.
This PR enhances the plugin with the ability to choose the webpage or the email of the associated contact as link to the author.
An option is added if the admin doesn't want to apply links to the real author when an alias name is used as article author.

### Testing Instructions
Enable "Show author" and "Link author" in global article options, or just in one article; enable Content - Contact plugin; associate a contact to the user who created the article.

### Expected result
When the article is displayed, the author name will be linked to the internal contact page (this is the default and it works like before).
You can change the type of link in the plugin configuration: "website" will link the author name to the website specified in the contact details (if any); "email" will open the default email client to email to the address provided in contact details.

### Actual result
Only the link to the internal contact page is available.

2017-10-08 09:17 UTC, infograf768 commented
This works fine but needs some code improvements.
I modified your xml to fit 
```
<?xml version="1.0" encoding="utf-8"?>
<extension version="3.2" type="plugin" group="content" method="upgrade">
	<name>plg_content_contact</name>
	<author>Joomla! Project</author>
	<creationDate>January 2014</creationDate>
	<copyright>Copyright (C) 2005 - 2017 Open Source Matters. All rights reserved.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<authorEmail>admin@joomla.org</authorEmail>
	<authorUrl>www.joomla.org</authorUrl>
	<version>3.2.2</version>
	<description>PLG_CONTENT_CONTACT_XML_DESCRIPTION</description>
	<files>
		<filename plugin="contact">contact.php</filename>
	</files>
	<languages>
		<language tag="en-GB">en-GB.plg_content_contact.ini</language>
		<language tag="en-GB">en-GB.plg_content_contact.sys.ini</language>
	</languages>
	<config>
		<fields name="params">
			<fieldset name="basic">
				<field
					name="url"
					type="list"
					label="PLG_CONTENT_CONTACT_PARAM_URL_LABEL"
					description="PLG_CONTENT_CONTACT_PARAM_URL_DESCRIPTION"
					default="0"
				>
					<option value="0">PLG_CONTENT_CONTACT_PARAM_URL_0</option>
					<option value="1">PLG_CONTENT_CONTACT_PARAM_URL_1</option>
					<option value="2">PLG_CONTENT_CONTACT_PARAM_URL_2</option>
				</field>

				<field
					name="link_to_alias"
					type="radio"
					label="PLG_CONTENT_CONTACT_PARAM_ALIAS_LABEL"
					description="PLG_CONTENT_CONTACT_PARAM_ALIAS_DESCRIPTION"
					default="0"
					class="btn-group btn-group-yesno"
				>
					<option value="0">JNO</option>
					<option value="1">JYES</option>
				</field>
			</fieldset>
		</fields>
	</config>
</extension>
```
To get:

<img width="727" alt="screen shot 2017-10-08 at 11 02 09" src="https://user-images.githubusercontent.com/869724/31315393-351940f0-ac18-11e7-8577-2894b6015b59.png">

remark that we use JNO and JYES, therefore the strings
```
PLG_CONTENT_CONTACT_PARAM_YES="Yes"
PLG_CONTENT_CONTACT_PARAM_NO="No"
```
should be taken off the ini file.

Also the fields name do not usually use lower characters.
I changed them to 
`url` and `link_to_alias`
Which means they should be changed in code.

Also I would change
`PLG_CONTENT_CONTACT_PARAM_URL_LABEL="URL to link to"`
to maybe a simple
`PLG_CONTENT_CONTACT_PARAM_URL_LABEL="Redirection"`
as obviously an email is not an url :)

Also use lowercase for html tags in text strings, i.e. not `<UL><LI>` but `<ul><li>`

2017-10-08 09:32 UTC, brianteeman commented
@infograf768 the > needs to be indented like this
```
					default="0"
					>
					<option value="0">PLG_CONTENT_CONTACT_PARAM_URL_0</option>
```

2017-10-08 11:26 UTC, mattiaverga commented
Should the version number also be upgraded?

I have another doubt: in the xml the "extension version" is set to 3.2, but in php code the "protected $db;" code says it's available since 3.3...

2017-10-08 14:04 UTC, infograf768 commented
No need to touch the versions.

2017-10-08 14:05 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 569329213f12633132d39234294ab8a98cdd5cc7<br /><br />Works fine here. May need some tweaks to the values of the ini strings. @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18258">issues.joomla.org/tracker/joomla-cms/18258</a>.</sub>

2017-10-09 12:12 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 569329213f12633132d39234294ab8a98cdd5cc7<br /><br />Handy Improvement, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18258">issues.joomla.org/tracker/joomla-cms/18258</a>.</sub>

2017-10-09 12:13 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-11-02 16:11 UTC, infograf768 commented
@mbabker Please decide a milestone for this.

2018-06-02 15:44 UTC, mbabker requested changes

2018-06-02 15:44 UTC, mbabker commented on plugins/content/contact/contact.xml
> +					<option value="0">PLG_CONTENT_CONTACT_PARAM_URL_0</option>
Instead of 0/1/2 for the option values can we use text names so it's clear what each of these options are (so url/webpage/email).

2018-06-03 10:01 UTC, brianteeman approved these changes
approve string changes

2018-06-03 16:00 UTC, mbabker approved these changes

2018-06-12 23:00 UTC, merged