Filter field months
joomla/joomla-cms pull request #18361
Opened 2017-10-18 09:28 UTC by eshiol

### Summary of changes
Added a new filter field: month
### Testing Instructions
Create a new Category List page with Filter Field = Month
![image](https://user-images.githubusercontent.com/12718836/31535483-91ebd7c0-affb-11e7-8086-44c5ff72142c.png)
### Expected result
You can filter the articles by month/year in the front-end
![image](https://user-images.githubusercontent.com/12718836/31427010-0d67967e-ae66-11e7-8da8-faec6d95ec32.png)
in the brackets the number of articles
### Actual result
### System information (as much as possible)
### Additional comments
### Documentation Changes Required

2017-10-18 10:47 UTC, brianteeman commented
In the query instead of Month created i think it should be month published
and in the string it should be clarified eg "Month (published)"

2017-10-18 11:23 UTC, alikon requested changes
`DATE_FORMAT()` is only  MYSQL sql dialect don't work in postgresql nor mssql

2017-10-19 06:53 UTC, infograf768 commented
My test show that unpublished articles are counted and their published month appears in the dropdown.

Example:
![screen shot 2017-10-19 at 08 30 52](https://user-images.githubusercontent.com/869724/31757124-e4d2e78e-b4a7-11e7-9ad2-45133ba16e4a.png)

![screen shot 2017-10-19 at 08 34 44](https://user-images.githubusercontent.com/869724/31757246-699ab992-b4a8-11e7-980a-3ff62c831a33.png)

I guess the query should only return articles which are published or archived.

2017-10-19 06:55 UTC, infograf768 commented
We also get a count of articles which publish date has expired.

2017-10-19 07:05 UTC, infograf768 commented
Using published means changing the query from a.created to a.publish_up

2017-10-19 08:11 UTC, eshiol commented
Fixed

2017-10-19 08:18 UTC, infograf768 commented on administrator/language/en-GB/en-GB.ini
> +JMONTH_PUBLISHED="Month (published)"
I suggest to move both JMONTH and JMONTH_PUBLISHED below JMODIFY to alpha order these strings.

2017-10-19 08:19 UTC, infograf768 commented on components/com_content/models/articles.php
> +			$monthFilter = $filter;
I suggest to align the = signs in these lines

2017-10-19 08:20 UTC, infograf768 commented on components/com_content/models/articles.php
> +	 * @since   3.8.2
Please use `* @since  __DEPLOY_VERSION__` instead of 3.8.2

2017-10-19 08:22 UTC, infograf768 commented on components/com_content/models/articles.php
> +
please take off extraneous tab

2017-10-19 08:26 UTC, eshiol commented on administrator/language/en-GB/en-GB.ini
> +JMONTH_PUBLISHED="Month (published)"
done

2017-10-19 08:26 UTC, infograf768 commented on components/com_content/views/category/tmpl/default_articles.php
> +					<select name="filter-search" id="filter-search" onchange="document.adminForm.submit();" >
No space needed before > lines 51 and 56

2017-10-19 08:28 UTC, eshiol commented on components/com_content/models/articles.php
> +			$monthFilter = $filter;
done

2017-10-19 08:28 UTC, eshiol commented on components/com_content/models/articles.php
> +	 * @since   3.8.2
done

2017-10-19 08:29 UTC, infograf768 commented on libraries/cms/html/content.php
> +	 * @since   3.8.2
same remark as before, use  `__DEPLOY_VERSION__`

2017-10-19 08:29 UTC, eshiol commented on components/com_content/models/articles.php
> +
done

2017-10-19 08:32 UTC, eshiol commented on components/com_content/views/category/tmpl/default_articles.php
> +					<select name="filter-search" id="filter-search" onchange="document.adminForm.submit();" >
done

2017-10-19 08:49 UTC, infograf768 commented on templates/beez3/html/com_content/category/default_articles.php
> +			<select name="filter-search" id="filter-search" onchange="document.adminForm.submit();" >
last ones: space before > lines 54 and 59

2017-10-19 08:52 UTC, eshiol commented on templates/beez3/html/com_content/category/default_articles.php
> +			<select name="filter-search" id="filter-search" onchange="document.adminForm.submit();" >
done

2017-10-19 08:59 UTC, infograf768 commented
Looks OK now here.

2017-10-19 09:04 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 87c704d1892cb01b088e5d6a035a86499ce42394<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18361">issues.joomla.org/tracker/joomla-cms/18361</a>.</sub>

2017-10-19 11:39 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 87c704d1892cb01b088e5d6a035a86499ce42394<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18361">issues.joomla.org/tracker/joomla-cms/18361</a>.</sub>

2017-10-19 11:39 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-10-19 18:06 UTC, alikon commented
@franz-wohlkoenig please remove RTC cause doesn't work on postgresql
![screenshot from 2017-10-19 20-00-37](https://user-images.githubusercontent.com/181681/31786273-3915bd84-b508-11e7-82f1-b1162c2b6a84.png)

@eshiol 
you should use something like 
`$query->year($db->quoteName('field'))`
`$query->month($db->quoteName('field'))`
instead of 
`$query->select("concat(year(publish_up),'-',month(publish_up),'-01') as d")`

2017-10-20 09:39 UTC, infograf768 commented
@alikon please test again as I can't vs postgresql

2017-10-20 10:23 UTC, alikon commented
Sure i'll do

On 20 Oct 2017 11:39 am, "infograf768" <notifications@github.com> wrote:

> @alikon <https://github.com/alikon> please test again as I can't vs
> postgresql
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/18361#issuecomment-338158230>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AALFsdnhx8tVZ2FkRStMBqzLbSvhcAvZks5suGpsgaJpZM4P9axL>
> .
>

2017-10-21 08:42 UTC, alikon commented
still wrong SQL 
![screenshot from 2017-10-21 10-39-01](https://user-images.githubusercontent.com/181681/31850016-1ccf8426-b64c-11e7-81da-7df0cdac12bf.png)

2017-10-23 18:00 UTC, alikon commented
no error on postgresql now 
thanks @eshiol

2017-11-02 16:03 UTC, infograf768 commented
I have not tested this item.<br /><br />Ok too with mysql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18361">issues.joomla.org/tracker/joomla-cms/18361</a>.</sub>

2017-11-02 16:04 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on e3a99a939a3474e66827e650f2a93bbf9b10ea45<br /><br />Ok too with mysql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18361">issues.joomla.org/tracker/joomla-cms/18361</a>.</sub>

2017-11-02 16:05 UTC, infograf768 commented
@mbabker 
can you decide of a milestone for this?

2018-03-17 15:37 UTC, merged