Don't expose LDAP authentication usage.
joomla/joomla-cms pull request #18531
Opened 2017-11-08 13:47 UTC by HLeithner

As discussed in JSST, change translation strings in public tracker. We don't want to expose the usage of LDAP for authentications.

### Summary of Changes
Language file Updates

2017-11-08 13:49 UTC, brianteeman commented
isnt that security through obscurity?

2017-11-08 14:12 UTC, mbabker commented
It is.  But this is one of those cases where the public facing error message probably shouldn't say what authentication source is in use (same logic is already in use with Gmail auth from a cursory glance).

2017-11-08 14:19 UTC, brianteeman commented
No the gmail plugin will error with
https://github.com/joomla/joomla-cms/blob/c4ff5155d2bf6cdfa506061c203e30400b8bb327/plugins/authentication/gmail/gmail.php#L197

where PLG_GMAIL_ERROR_LOCAL_USERNAME_CONFLICT="A local username conflicts with your Gmail username."

2017-11-08 14:53 UTC, mbabker commented
That one's a very specific case.  But the other fail messages are the generic messages.  Unless I misread and the keys actually are referencing strings saying "could not connect to Google to authenticate" basically.

2017-11-09 09:16 UTC, infograf768 commented
these keys are specific to ladp afaik
I suggest, if you do not want in future releases to still show the word `ladp` when a language pack is not up to date, instead of modifying the value, adding new strings where NO is replaced by NOT (for example)
`JGLOBAL_AUTH_NOT_BIND`
Precede the old strings by a comment
`; The following 2 strings are deprecated and will be removed with 4.0.`

2018-04-09 15:37 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 431e5e512aef3a9e13b820447ca23da6cf6b8fe1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18531">issues.joomla.org/tracker/joomla-cms/18531</a>.</sub>

2018-04-27 18:01 UTC, HLeithner commented
I followed @infograf768 suggestion and added 2 new strings.

2018-04-27 18:02 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on 69623e6658976a025d1a3ecf30592bd2f66c6ebc<br /><br />Thanks @HLeithner <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18531">issues.joomla.org/tracker/joomla-cms/18531</a>.</sub>

2018-04-27 18:04 UTC, zero-24 commented
@brianteeman can you please give your ok as code owner for the language files so we can move that one forward into 3.8.8? Thanks.

2018-04-27 19:13 UTC, brianteeman commented
No need to ask me. GitHub tells me but I am in the pub so will check later,

2018-04-27 21:07 UTC, brianteeman requested changes
No point in adding two new strings that are identical

2018-04-27 21:15 UTC, zero-24 commented
Fixed please review again @HLeithner @brianteeman ;)

2018-04-27 21:16 UTC, Quy commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_AUTH_NOT_CONNECT="Unable to connect to authentication service."
Sort in alpha order.

2018-04-27 21:20 UTC, zero-24 commented
done @Quy thanks.

2018-04-27 21:21 UTC, Quy commented
I have tested this item :white_check_mark: successfully on c7c0c4074e14cc97482cfeb8b5dcfcfc76d2d8be<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18531">issues.joomla.org/tracker/joomla-cms/18531</a>.</sub>

2018-04-27 21:25 UTC, brianteeman approved these changes

2018-04-27 21:30 UTC, zero-24 commented
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18531">issues.joomla.org/tracker/joomla-cms/18531</a>.</sub>

2018-04-28 08:56 UTC, HLeithner commented
There is a reason for 2 strings but only for debugging usage so I'm fine with only one string

2018-04-29 14:49 UTC, merged