[com_associations] - use cache for getContentLanguages()
joomla/joomla-cms pull request #18544
Opened 2017-11-09 20:03 UTC by alikon

Pull Request for Issue #15494.

### Summary of Changes
use cache instead of query everytime the available languages

### Testing Instructions
see  #15494

### Expected result
reduce the number of duplicate query

### Actual result
unnecessary duplicate query for get languages

### Additional Comments
reduced this one only
https://github.com/joomla/joomla-cms/issues/15494#issuecomment-343197629

2017-11-09 20:22 UTC, csthomas commented
```php
if (empty(static::$languages))
{
	static::load();
+		{
-		// Get all content languages.
+			$result = static::$languages;
-		$query = $db->getQuery(true)
+		}
-			->select($db->quoteName(array('sef', 'lang_code', 'image', 'title', 'published')))
+		else
-			->from($db->quoteName('#__languages'))
+		{
-			->where($db->quoteName('published') . ' != -2')
+			static::load();
-			->order($db->quoteName('ordering') . ' ASC');
+            		$result = static::$languages;
-
+		}
```

2017-11-09 20:33 UTC, alikon commented
thanks @csthomas   :+1:  more clean now

2017-11-09 20:39 UTC, Quy commented on administrator/components/com_associations/helpers/associations.php
> +
Please remove whitespace.

2017-11-09 20:39 UTC, Quy commented on administrator/components/com_associations/helpers/associations.php
> +   	}
Please fix whitespace.

2017-11-10 07:26 UTC, infograf768 commented
Queries number has reduced a lot: 186 instead of 235.
as you said, some more could be done. Maybe for another PR?

<img width="1033" alt="screen shot 2017-11-10 at 08 23 24" src="https://user-images.githubusercontent.com/869724/32647246-90dfacc0-c5f0-11e7-9c60-cae9bb4b8c8a.png">

I have seen some cs.

2017-11-10 07:31 UTC, infograf768 requested changes

2017-11-10 07:31 UTC, infograf768 commented on administrator/components/com_associations/helpers/associations.php
> +	 * List languages of languages
languages of languages ?

2017-11-10 07:31 UTC, infograf768 commented on administrator/components/com_associations/helpers/associations.php
> +			    ->select($db->quoteName(array('sef', 'lang_code', 'image', 'title', 'published')))
689 and below, replace spaces for indent by tab

2017-11-10 07:31 UTC, infograf768 commented on administrator/components/com_associations/helpers/associations.php
> +    		return true;
Indent: delete spaces

2017-11-10 07:39 UTC, alikon commented
yes matter for another PR..... 
i'll fix the cs glitch....

2017-11-10 17:14 UTC, alikon commented on administrator/components/com_associations/helpers/associations.php
> +	 * List languages of languages
changed

2017-11-10 17:14 UTC, alikon commented on administrator/components/com_associations/helpers/associations.php
> +			    ->select($db->quoteName(array('sef', 'lang_code', 'image', 'title', 'published')))
replaced

2017-11-10 17:15 UTC, alikon commented on administrator/components/com_associations/helpers/associations.php
> +    		return true;
idented

2017-11-10 17:15 UTC, alikon commented
hope cs fixed now

2017-11-10 18:26 UTC, andrepereiradasilva commented
hi guys, just stoped by to say: why not reuse the already available method in the library 
```php
Joomla\CMS\Language\LanguageHelper::getContentLanguages($checkPublished = true, $checkInstalled = true, $pivot = 'lang_code', $orderField = null, $orderDirection = null)
```

See https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Language/LanguageHelper.php#L336

2017-11-10 19:00 UTC, alikon commented
wellcome back @andrepereiradasilva , we are missing you ,

i'll investigate further your suggestion, i hope in the week-end....

2017-11-11 07:22 UTC, infograf768 approved these changes

2017-11-11 08:10 UTC, alikon commented
applyed the tips from @andrepereiradasilva 
please re-test

2017-11-11 08:21 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 6f6c1d329d51a7fb546ca538c05b128eaf5a3e64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-11 08:31 UTC, infograf768 commented
I have tested this item :red_circle: unsuccessfully on 6f6c1d329d51a7fb546ca538c05b128eaf5a3e64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-11 08:45 UTC, infograf768 commented
Changed my test to unsuccessful.

I get an error
`Call to undefined method AssociationsHelper::getContentLanguages()`
when trying to load the face to face page

2017-11-11 08:51 UTC, alikon commented
Silly me, I'll do the needed change later sorry


Il 11 nov 2017 9:45 AM, "infograf768" <notifications@github.com> ha scritto:

> Changed my test to unsuccessful.
>
> I get an error
> Call to undefined method AssociationsHelper::getContentLanguages()
> when trying to load the face to face page
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/18544#issuecomment-343650065>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AALFsfJnFDGi1WH53fV_Sn6pPveR-M7bks5s1V6PgaJpZM4QYkba>
> .
>

2017-11-11 09:43 UTC, alikon commented
re-re-test please

2017-11-11 09:51 UTC, infograf768 commented on administrator/components/com_associations/helpers/associations.php
> +   	}
delete unwanted spaces line 449

2017-11-11 09:52 UTC, infograf768 commented on administrator/components/com_associations/helpers/associations.php
> +   	}
otherwise, pr is fine

2017-11-11 09:56 UTC, alikon commented on administrator/components/com_associations/helpers/associations.php
> +   	}
done

2017-11-11 10:05 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on e935a9d6e1afe2ead3e7962e83cc4273d0b154c5<br /><br />Perfect this time. :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-11 10:18 UTC, alikon commented
perfection is my current challenge, unfortunately i already know that i cant win :smile:

2017-11-12 09:40 UTC, franz-wohlkoenig commented
@alikon can you please give Test Instructions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-12 09:47 UTC, alikon commented
1. start with a multilanguage site with > 5 langauges 
2. add some content in en-GB for example
3. enable debug plugin
4. com_associations  select articles and language en-gb
5. look at database tab of debug plugin and take note of much query are executed and how much are duplicate
6. apply PR
7 redo 4., 5. you should notice less query and less duplicate

2017-11-12 09:55 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on e935a9d6e1afe2ead3e7962e83cc4273d0b154c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-12 09:57 UTC, franz-wohlkoenig commented
RTC after two successful tests.

2017-11-12 10:33 UTC, joomdonation commented
Just want to point out that there is difference between the data returned by old code and new code. With the original code, all content languages (including unpublished) will be returned, with new code, only published content languages will be returned

Also, if we decide to use new code, I think it is better to call the new method directly instead of still calling AssociationsHelper::getContentLanguages (because this method is now basically, an alias of LanguageHelper::getContentLanguages() )

2017-11-12 16:21 UTC, infograf768 commented
@joomdonation 

You are totally correct. I take off RTC.
We should be able to prepare a new Content Language but not put it online until Published.

With this patch, it is now impossible to do anything for such a content language in com_associations.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-12 16:47 UTC, infograf768 commented
In fact I guess the solution is easy
`return LanguageHelper::getContentLanguages(false, true);` is enough.

2017-11-13 10:03 UTC, alikon commented
applyed the tips from @joomdonation

2017-11-13 14:06 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 69d811de89f2d7677b5772b3c92cf46b7bb1ae3b<br /><br />Works fine now even if the Content Language is unpublished.

Only drawback is that it also proposes those which are in the Trash.
That case is not taken care of in `LanguageHelper::getContentLanguages()`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-13 18:24 UTC, andrepereiradasilva commented
@infograf768 reggarding the trashed language, true. the language helper method could be improved (while preserving B/C).

Something like this. Not tested. Replaced $checkPublished (boolean) argument for $publishedStates (array) and using a B/C layer for that parameter.

```php
/**
 * Get a list of content languages.
 *
 * @param   array    $publishedStates  Array with the content language published states. Null or empty array for all.
 * @param   boolean  $checkInstalled   Check if the content language is installed.
 * @param   string   $pivot            The pivot of the returning array.
 * @param   string   $orderField       Field to order the results.
 * @param   string   $orderDirection   Direction to order the results.
 *
 * @return  array  Array of the content languages.
 *
 * @since   3.7.0
 */
public static function getContentLanguages($publishedStates = array(1), $checkInstalled = true, $pivot = 'lang_code', $orderField = null, $orderDirection = null)
{
	// B/C layer. Before __DEPLOY_VERSION__.
	if ($publishedStates === true)
	{
		$publishedStates = array(1);
	}
	elseif ($publishedStates === false)
	{
		$publishedStates = null;
	}

	// [code removed for brevity...]

	// Check if the language is published, if needed.
	if ($publishedStates !== null && $publishedStates !== array())
	{
		foreach ($languages as $key => $language)
		{
			if (in_array((int) $language->published, $publishedStates, true) === false)
			{
				unset($languages[$key]);
			}
		}
	}

	// [code removed for brevity...]
}

```

then, for published/unpublished, you could call it like this 

```php
LanguageHelper::getContentLanguages(array(0, 1), true);
```
BTW @alikon unless things changed recently i don't think it's B/C to completly remove a public method in 3.x, you chould proxy it to languagehelper and them but a deprected 4.0 message.

2017-11-14 10:49 UTC, alikon commented
managed the trashed lanugages

2017-11-14 16:36 UTC, infograf768 commented
Works here

2017-11-15 04:50 UTC, joomdonation commented
@alikon If I am not mistaken, the changes you made to \Joomla\CMS\Language\LanguageHelper::getContentLanguages() will cause B/C issue. Before the change, if someone calls \Joomla\CMS\Language\LanguageHelper::getContentLanguages() , the result will include trashed content languages. After your changes, it won't include trashed content languages anymore.

I think the propose change from @andrepereiradasilva is better. It extends the method to allow us to get content languages we want based on passed publish states. I made a PR to your branch https://github.com/alikon/joomla-cms/pull/38, please review it and if you agree, merge it so that we can have this issue sorted.

2017-11-15 07:33 UTC, alikon commented
thanks folks for teamworking, hope now issues are solved in a B/C way

2017-11-15 07:37 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on e3d1b462947ea45b5263d80c7645249d33a46f2b<br /><br />TBH, folks, I see absolutely no reason why anyone would list Trashed Content Languages.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-15 08:17 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on f438af01ca1a894d0599ff8bb1060f1e7cf27be2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-15 08:24 UTC, franz-wohlkoenig commented
@infograf768 can you please retest?

2017-11-15 08:55 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on f438af01ca1a894d0599ff8bb1060f1e7cf27be2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-15 08:55 UTC, infograf768 commented
RTC. Thanks to all.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18544">issues.joomla.org/tracker/joomla-cms/18544</a>.</sub>

2017-11-18 15:49 UTC, merged