[3.x] Add Progress to Extension Installer and Improve Error Handler
joomla/joomla-cms pull request #18554
Opened 2017-11-11 17:45 UTC by asika32764

Add upload progress so user can see the upload percentage like before.

![p-2017-11-12-002](https://user-images.githubusercontent.com/1639206/32691953-d1e3397a-c74a-11e7-8b30-786bf92181ab.jpg)

Improve error handler so user will get message if PHP raise fatal error without standard JSON format or HTTP error status.

![p-2017-11-12-003](https://user-images.githubusercontent.com/1639206/32691960-eecce3e2-c74a-11e7-95fb-e20d63691421.jpg)

2017-11-11 19:32 UTC, brianteeman commented on plugins/installer/packageinstaller/tmpl/default.php
> +				var message = 'Unknown error.';
shouldnt this  be translatable?

2017-11-11 19:36 UTC, brianteeman commented
It would be nice if this was accessible  there are lots of accessible progress bar examples online

2017-11-11 21:15 UTC, Fedik commented on plugins/installer/packageinstaller/tmpl/default.php
> +				alert(message);
maybe would be better `Joomla.renderMessages()`?

2017-11-12 02:03 UTC, asika32764 commented on plugins/installer/packageinstaller/tmpl/default.php
> +				var message = 'Unknown error.';
Hmm, this is only a fallback default message, should never display. (If this message display, it means en extension is on developing and developer try to make it error with empty or non-JSON output...) 

Do you think it is a good idea to translate a message which may only developers can see? If you think so I can translate it.

2017-11-12 02:12 UTC, asika32764 commented
@brianteeman Add accessible.

@Fedik Use Joomla.renderMessages()

2017-11-12 03:33 UTC, Quy commented on plugins/installer/packageinstaller/tmpl/default.php
> +
Remove tabs in line 72.

2017-11-12 03:33 UTC, Quy commented on plugins/installer/packageinstaller/tmpl/default.php
> +
Remove tabs in line 108.

2017-11-12 03:34 UTC, Quy commented on plugins/installer/packageinstaller/tmpl/default.php
> +
Remove tabs in line 138.

2017-11-12 03:34 UTC, Quy commented on plugins/installer/packageinstaller/tmpl/default.php
> +
Remove tabs in line 153.

2017-11-12 07:27 UTC, alikon commented
I have tested this item :white_check_mark: successfully on b82544e892ba9cb0f2262b33c3f6105499003438<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18554">issues.joomla.org/tracker/joomla-cms/18554</a>.</sub>

2017-11-12 09:37 UTC, franz-wohlkoenig commented
@asika32764 how to get "fatal error without standard JSON format or HTTP error status" to test PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18554">issues.joomla.org/tracker/joomla-cms/18554</a>.</sub>

2017-11-12 14:42 UTC, asika32764 commented
Actually I don't know. Maybe return a XML output. This case should never happened.

In this PR, all response with HTTP 200 will go to `done()` method, but the PHP post_max_size error is unable to catch and returned with JSON and HTTP 200 status:

![p-2017-11-12-005](https://user-images.githubusercontent.com/1639206/32700012-b53253ec-c7f9-11e7-8d77-599efb48e991.jpg)

If jQuery try to parse JSON but fail, it will go to `error()` method. And if response is HTTP 4xx-5xx status will go `error()` too. I handled the `error.responseText` for any PHP fatal error and `error.responseJSON` for standard JSON output, so it should has no other cases we will get.

2017-11-12 14:46 UTC, asika32764 commented
@franz-wohlkoenig Sorry, I misunderstand what you asked. The  "fatal error without standard JSON format or HTTP error status" is the `post_max_size` issue.

Set php.ini post_max_size to a small value and upload a big file, you will get error message. Before this PR, the uploader will die and no response.

2017-11-12 15:41 UTC, Quy commented
This works with drag and drop, but not with `Or browse for file`. Is this intentional?

2017-11-12 17:08 UTC, asika32764 commented
Yes, `Or browse for file` use file input and post form to upload package. While the drag and drop use ajax (because JS cannot insert value to file input).

2017-11-13 09:56 UTC, brianteeman commented on plugins/installer/packageinstaller/tmpl/default.php
> +				var message = 'Unknown error.';
Personally yes i do

2017-11-13 11:51 UTC, asika32764 commented on plugins/installer/packageinstaller/tmpl/default.php
> +				var message = 'Unknown error.';
OK let's translate it.

2017-11-18 18:29 UTC, Quy commented
On a local install, the progress bar moves to 100% very quickly, and then takes about 10 seconds to complete. So this is an upload indicator only and not an installing indicator too?

2017-11-18 19:01 UTC, asika32764 commented
Yes, it is only uploading indicator. Joomla didn't implement the installing indicator interface now.

2017-11-18 22:03 UTC, Quy commented
In Microsoft Edge 41.16299.15.0 on Windows 10, you don't see the progress bar until the very end. Also, should the % be next to the number without the space?

![edge-upload](https://user-images.githubusercontent.com/368084/32985162-1fd82dde-cc69-11e7-84ec-1943f0aab064.gif)

2017-11-18 22:27 UTC, brianteeman commented
good spot. yes it would read better without the space between the number and the &

2017-11-19 04:34 UTC, asika32764 commented
- Removed space
- Added installing progress after uploaded. See:

![up-pro](https://user-images.githubusercontent.com/1639206/32987404-c81c4072-cd25-11e7-8f17-e726e26845f2.gif)

---- 

@Quy About the Edge issue, it is a known bug that MS haven't fixed it. See:

- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12224510/
- https://stackoverflow.com/questions/43942396/ajax-file-upload-progress-upload-event-does-not-fire-in-edge-browser

2017-11-19 16:01 UTC, Quy commented on plugins/installer/packageinstaller/tmpl/default.php
> +
Remove tabs on line 152.

2017-11-19 16:02 UTC, Quy commented on plugins/installer/packageinstaller/tmpl/default.php
> +						aria-valuenow="25"
Should the value be 0?

2017-11-19 17:33 UTC, asika32764 commented on plugins/installer/packageinstaller/tmpl/default.php
> +						aria-valuenow="25"
The `width` value? The initial value should be `0`.

2017-11-19 17:36 UTC, asika32764 commented on plugins/installer/packageinstaller/tmpl/default.php
> +						aria-valuenow="25"
Ah, I know, you mean the `aria-valuenow`

Yes it should be 0. Fixed.

2017-11-19 22:18 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_installer_packageinstaller.ini
>  PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_AND_INSTALL="Upload & Install"
Sorry to nitpick. Please move lines 14-16 below line 11.

2017-11-20 16:17 UTC, Quy commented
I have tested this item :white_check_mark: successfully on a00243c9dba19d6c047c2d24b83b22045d07d739<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18554">issues.joomla.org/tracker/joomla-cms/18554</a>.</sub>

2018-05-08 21:20 UTC, brianteeman requested changes

2018-05-08 21:20 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_installer_packageinstaller.ini
> -PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_AND_INSTALL="Upload & Install"
For silly reasons it is our practice not to remove unused strings. So please put this string back. You can if you want to add a comment above it
;The next line is deprecated and will be removed in J4

2018-05-09 06:09 UTC, asika32764 commented on administrator/language/en-GB/en-GB.plg_installer_packageinstaller.ini
> -PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_AND_INSTALL="Upload & Install"
OK added the deprecated info

2018-05-09 06:39 UTC, brianteeman approved these changes

2018-05-11 01:52 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_installer_packageinstaller.ini
> +PLG_INSTALLER_PACKAGEINSTALLER_INSTALLING="Installing..."
Please add space before `...`

2018-05-11 01:52 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_installer_packageinstaller.ini
> +PLG_INSTALLER_PACKAGEINSTALLER_UPLOADING="Uploading..."
Please add space before `...`

2018-05-11 04:56 UTC, asika32764 commented
ok

2018-07-21 02:51 UTC, mbabker approved these changes

2018-09-23 14:01 UTC, twister65 commented
I have tested this item :red_circle: unsuccessfully on 7b6ed585486c7da22f2b7c0d8930477bd94baff8<br /><br />I do not have an alert popup when the package size exceeds the upload_max_filesize value.
Nothing happening, I have only this message : "No Install Type Found".
This problem is recurring on my host where the upload_max_filesize is set to 2Mo.
Great PR, but it does not work as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18554">issues.joomla.org/tracker/joomla-cms/18554</a>.</sub>

2018-11-20 17:43 UTC, asika32764 commented
@twister65

The test case with error message is `post_max_size`.

PHP won't catch `upload_max_size` error, it will still run process without any uploaded file, so Joomla cannot find extension package file and return a `No Install Type Found` message.

2018-11-20 17:55 UTC, asika32764 commented
At here we use message instead of alert popup.
https://github.com/joomla/joomla-cms/pull/18554#issuecomment-343708464

2018-12-01 17:11 UTC, twister65 commented
@asika32764 , if I set post_max_size to 2 MB, and I upload a file larger than 2 MB. Then the message is "No Install Type Found" and there is no alert popup. This message is not relevant.

2018-12-01 17:15 UTC, asika32764 commented
> Then the message is "No Install Type Found" and there is no alert popup. 

This is expected behavior,the default error message should show as Joomla message, not popup.

This PR try to catch some PHP error which Joomla cannot catch and show as popup to notice user, without this PR, the uploader will only infinite loop without any response. 

> This message is not relevant.

This message is default Joomla install error message, not belongs to this PR.

2018-12-01 21:49 UTC, twister65 commented
I have tested this item :white_check_mark: successfully on 7b6ed585486c7da22f2b7c0d8930477bd94baff8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18554">issues.joomla.org/tracker/joomla-cms/18554</a>.</sub>

2018-12-01 21:56 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18554">issues.joomla.org/tracker/joomla-cms/18554</a>.</sub>

2018-12-02 05:02 UTC, infograf768 commented on plugins/installer/packageinstaller/tmpl/default.php
Maybe delete empty line

2018-12-02 05:14 UTC, asika32764 commented on plugins/installer/packageinstaller/tmpl/default.php
Deleted

2018-12-02 05:16 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 5a68c03c94069f0189d598d5007ad86504a0fd97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18554">issues.joomla.org/tracker/joomla-cms/18554</a>.</sub>

2018-12-02 05:18 UTC, infograf768 commented
As the last change is just cosmetic, let's keep this as RTC.

2018-12-12 05:43 UTC, merged