Fix mail test
joomla/joomla-cms pull request #18821
Opened 2017-11-23 11:19 UTC by asika32764

Pull Request for Issue #18779 .

### Summary of Changes

Fixed the mail test in configuration for https://github.com/joomla/joomla-cms/pull/18779

The change of this PR includes:

- Fixed CSRF for Ajax
- Fixed Ajax error handler
- Use `JsonInput` to get test mail information.
- Use Namespaces.

### Testing Instructions

Click `Send Test Mail`, should display correct message (Success or Error, not CSRF invalid message).

![p-2017-11-23-001](https://user-images.githubusercontent.com/1639206/33170420-35b30dfe-d083-11e7-8719-5436dda69630.jpg)

![p-2017-11-23-002](https://user-images.githubusercontent.com/1639206/33170421-35e1f326-d083-11e7-8319-0de0ed06360c.jpg)

2017-11-23 11:29 UTC, dgrammatiko requested changes

2017-11-23 11:29 UTC, dgt41 commented on media/system/js/fields/sendtestmail.js
>  var sendTestMail = function() {
@asika32764 can you please wrap the code in this file into an IFEE 
```js
(function() {
// code
})();
```

2017-11-23 11:36 UTC, dgrammatiko approved these changes

2017-11-23 12:02 UTC, C-Lodder commented
Please also commit the minified JS files too.

2017-11-23 12:06 UTC, asika32764 commented
Done

2017-11-23 12:47 UTC, Quy commented on administrator/language/en-GB/en-GB.com_config.ini
> +COM_CONFIG_SENDMAIL_METHOD_SENDMAIL="Sendmail"
Alphabetize keys. Move line 173 above line 171. Move lines 171-173 after line 167.

2017-11-23 12:51 UTC, wilsonge commented on libraries/src/Session/Session.php
> +		if ($token === $app->input->server->get('HTTP_X_CSRF_TOKEN', '', 'alnum'))
I think this is bad. This allows you to construct AJAX requests for standard post forms. We should only allow this for the supplied ajax methods imo

2017-11-23 14:03 UTC, asika32764 commented on libraries/src/Session/Session.php
> +		if ($token === $app->input->server->get('HTTP_X_CSRF_TOKEN', '', 'alnum'))
If a request able to send custom headers, I think it will always be AJAX or API call, not a standard form post.

I have no idea how to detect that a request is a form post or AJAX.

2017-11-23 14:08 UTC, asika32764 commented on administrator/language/en-GB/en-GB.com_config.ini
> +COM_CONFIG_SENDMAIL_METHOD_SENDMAIL="Sendmail"
Done

2018-07-22 09:09 UTC, brianteeman commented
It has been a very long time since this PR was submitted and as there has been no response to the comments and no tests I am closing this as an abandoned PR. It can always be reopened if updated

2018-07-22 09:09 UTC, closed without merging