Eliminate crippling performance of  content search plugin for large sites with custom fields
joomla/joomla-cms pull request #18915
Opened 2017-11-29 14:16 UTC by GeraintEdwards

Pull Request for Issue # .

For MySQL based sites with a large number of articles (more than a few hundred) that have custom fields enabled the com_content search plugin ends up being so slow that it can cripple a site completely.  For a test dataset (details below)  of 3,900 articles with 2 custom fields each the database query for a search took between 700,000 and 1,300,000 milliseconds to return a set of search results (on an i7-6700k 4Ghz 8 core processor with 32GB or ram) .  In addition the search results for matching all on a multi-select field incorrectly returns zero results.  

Postgres performs a LOT better (query times in the region of 400 milliseconds)  but the changes described below still cut the query times by 50%.

### Summary of Changes

The plugin has been re-written and rather than joining all the custom fields rows and searching for custom fields at the same time as all the other content fields we now search custom fields and incorporate the results into the main query.  In Postgres this can be done as a subquery but  MySQL treats this independent subquery as a 'dependent subquery' with punishing performance implications.  This may explain in part why MySQL performs so badly with the existing code.

### Testing Instructions

This test requires a large dataset of articles/custom fields to test.  It can be generated using com_overload ( Copyright (C) 2011 Nicholas K. Dionysopoulos) - an updated version is attached below that will work in Joomla 3.8 and that also creates 2 custom fields and populates these with the articles.

You should install this component and view it in the backend.  A decent dataset to test with would use values of 3 categories, 3 levels, 100 articles -> this will give 3900 articles (WARNING this will take several minutes to generate the data) 

This adds a text field with random values of "one" to "seven" as text and a multi-select list field with 2 random values from opt1, opt2. opt3, opt4 and op5.

Then use the search module/com_search in the frontend and search for 

"seven" or "opt1" or "opt1 opt2" etc.

### Expected result

1; The correct set of results within a couple of seconds max.

2. Search for 'opt1 opt2' and match all and it should 

### Actual result

1. Go and make a cup of coffee and then drink it, call your friends, have another cup of coffee - depending on your processor you are likely to be waiting 20 minutes for the results to return.

2. The search for 'opt1 opt2' and match all returns NO values which is NOT correct since there are several hundred matches

If you implement the patch you will get a FAST result for 1. and the correct results for 2.

### Discussion Point ###
I have tested the changes on Postgres and it supports a subquery rather than having a separate list of ids from a different query.  I have not been able to test this on SQL server.

### Documentation Changes Required

None

2017-11-29 14:18 UTC, GeraintEdwards commented
This is version of com_overload that can generate the test data set
[com_overload.zip](https://github.com/joomla/joomla-cms/files/1514069/com_overload.zip)

2017-11-29 18:06 UTC, nibra requested changes
Good approach, actually exactly what I was thinking of. Just a few things:
1. Use Joomla's Code Style (fx, the diff is broken because you're not formatting your code correctly)
2. Remove unused code instead of commenting it out
3. In the cleanup loop, you have all the article ids for the custom fields already, so you could retrieve all of the custom fields at once outside of the loop.

2017-11-29 18:49 UTC, GeraintEdwards commented
Agree entirely about the article ids and fetching the custom fields in one go.  We need to do the same elsewhere in custom fields too.  I'll look at the code formatting - but my IDE is setup to match Joomla's standards already

2017-11-29 18:52 UTC, mbabker commented
> I'll look at the code formatting - but my IDE is setup to match Joomla's standards already

There's an extra indent on the method's code.  Take that out and it should be mostly OK at a cursory glance.

2017-11-29 19:15 UTC, GeraintEdwards commented
Thanks @mbabker  - not sure where the extra tab came from.  That had tidied up the diff a lot. 

Do we really care about aligning assignment operators?  

@nibra I'll do a new PR later to implement the idea of picking up all the field values in one pass.  We need to do the same elsewhere in the core (in my opinion too) instead of duplicated or repetitive queries.

2017-11-29 19:18 UTC, brianteeman commented
> Do we really care about aligning assignment operators?

it does make code more readable

2017-11-29 19:23 UTC, csthomas commented on plugins/search/content/content.php
> +				{
IMO we always should use this variant, means 2 queries. Complex query take up too much memory.

2017-11-29 19:28 UTC, alikon commented
i've made a quick test on mysql  and after apply pr no need to

> make a cup of coffee and then drink it, call your friends, have another cup of coffee

to get results :+1: 

i'll make some test on postgresql too

2017-11-29 19:32 UTC, Quy commented on plugins/search/content/content.php
> +
Remove blank line.

2017-11-29 19:32 UTC, Quy commented on plugins/search/content/content.php
> +
Remove blank line.

2017-11-29 19:32 UTC, Quy commented on plugins/search/content/content.php
> +
Remove blank line.

2017-11-29 19:33 UTC, Quy commented on plugins/search/content/content.php
> +
Remove blank line.

2017-11-29 23:04 UTC, nibra commented on plugins/search/content/content.php
Remove this dead code

2017-11-30 08:08 UTC, angieradtke commented
I tested you changes at a real project: 8 Fields per article within 6000  articles in 4 different languages.
It seems to work .-) 
Thanks Angie

2017-11-30 08:23 UTC, angieradtke commented
One more idea, maybe we should use a param; search in fields as well, so it is more flexible

2017-11-30 08:38 UTC, laoneo commented
Thanks @GeraintEdwards for the proper test instructions. Now I could easily reproduce the issue on my dev server.
But is there really no way to do that server type independent? I tried a different approach in #18929 to split up the queries. What do you guys think?

2017-11-30 10:47 UTC, GeraintEdwards commented on plugins/search/content/content.php
> +				{
In an ideal world the subquery approach should be the fastest since the database engine can do its own optimisations.  Unfortunately MySQL had a bug where the independent sub query is treated as if it were dependent and gets executed once for every article searched (and a ridiculous performance hit).

Postgres treats the query correctly and is about twice as fast as a subquery compared to passing the field ids in as a string.

So its a trade off between easier to read code and a small performance hit in Postgres.

2017-11-30 10:48 UTC, GeraintEdwards commented
Hi Allon - see my comments on your other PR.

Re the server type dependent code - as I explained in my comment in the code  the subquery approach should be the fastest since the database engine can do its own optimisations.  Unfortunately MySQL had a bug where the independent sub query is treated as if it were dependent and gets executed once for every article searched (and a ridiculous performance hit).

Postgres treats the query correctly and is about twice as fast as a subquery compared to passing the field ids in as a string.

So its a trade off between easier to read code and a small performance hit in Postgres.

2017-11-30 11:07 UTC, GeraintEdwards commented
@angieradtke I suppose it does make sense to be able to mark specific fields as 'searchable' and other not.  That would require a new config option for individual fields - @laoneo what do you think?

2017-11-30 11:52 UTC, laoneo commented
What's the reason to not search in a field? If you want such an option, then I would add it as a parameter in the search plugin in which fields to search.

2017-11-30 11:55 UTC, laoneo commented
> So its a trade off between easier to read code and a small performance hit in Postgres.

I'm more worried about other extension developers who want to implement a search plugin. Mostly the content search plugin acts as example. It is already very complex.

2017-11-30 12:10 UTC, GeraintEdwards commented
In general most sites will not want to search for matching text in media fields but I guess some people may want to search for matching image file name?

The setting could be in the plugin but if someone then adds a new field they need to remember to go back to the plugin to change its setting there too.  Seems more natural to have the setting field specific to my mind.

On a related note I guess fields that only display in the backend should not be searched??

2017-11-30 12:14 UTC, angieradtke commented
@GeraintEdwards 
the custom fields can be used for various approaches. You can store article related data there. This is they are developed for. But you can use them as well to add  CSS-Classnames to parts of the page.

For example : You got a three column layout and you want that the last column of one row is larger then the others you can add col-6 col-md-2 to this column using custom fields.  This makes layout styling very flexible.

Such values I don't wanna see in my search results .

2017-11-30 12:33 UTC, alikon commented
i don't think an `if` about dbserver type make the code unreadable, plus as already stated mysql and postgresql do things in a different way so imho is fine to have different behaviuor depending upon dbserver type, and we have the same behaviuor in different place already

this is a really big performance gain, making search  again usable, 
so please can we consider to give this pr  high priority and then do the other related consideration to other future pr's

2017-11-30 12:38 UTC, laoneo commented
@alikon I do not agree. If we can make things less complex, reusable and easy to understand for other extension devs then I think it is worth to give it a try.

2017-11-30 12:56 UTC, nibra commented
The current code is ok - it works and solves a real problem. IMO it should be merged.

@laoneo Your concerns are absolutely valid. The plugin contains a lot of duplicated code which should be avoided. The PR does not make it worse, it just follows the style, the plugin is written in.

Nevertheless, *in a next, separate step*, the code for custom fields integration should be moved to a helper method (or better an event handler / "nested" plugin), that provides the right WHERE clause.

2017-11-30 13:44 UTC, GeraintEdwards commented
I agree with @nibra the search is hitting large sites very badly already and I would suggest merging this PR now and then working on moving the custom code to a helper/model class, taking account of which fields should be searched (as per the valid suggestions from @angieradtke) and incorporating similar changes into the contacts search plugin when that code is ready.  If that can be done in time for 3.8.3 then nothing is lost by merging this change now and a more refined solution later - but I don't think we should risk waiting for a more refined solution that may possibly not be merged in time for 3.8.3.

2017-11-30 15:59 UTC, Quy commented on plugins/search/content/content.php
Do you still need the comment? If yes, `neded` is misspelled.

2017-12-01 06:52 UTC, GeraintEdwards commented
@nibra - I have removed the commented out code and largely restyled the file.  I suggest the field value collection/assignement change is made into another PR since the same changes need to be applied in other parts of the core to eliminate duplicate/repeated queries.

2017-12-01 11:49 UTC, nibra approved these changes
Still a few CS issues, but they're only marginal. So this is ok for me now.

2017-12-01 11:50 UTC, nibra commented
@alikon @angieradtke Could you please re-test? Functionality should not have changed, but just to be on the safe side...

2017-12-01 11:56 UTC, alikon commented
I'll do this weekend

Il 01 dic 2017 12:50 PM, "Niels Braczek" <notifications@github.com> ha
scritto:

@alikon <https://github.com/alikon> @angieradtke
<https://github.com/angieradtke> Could you please re-test? Functionality
should not have changed, but just to be on the safe side...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/pull/18915#issuecomment-348475978>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AALFsQBIW5SWmZAHDXe1yv99oKxXPfTWks5s7-gQgaJpZM4QvB9K>
.

2017-12-01 13:28 UTC, tonypartridge commented
I have tested this item :white_check_mark: successfully on 5eab93c9cb33a4c8f0b4d060e405392b33ad1287<br /><br />This is a massive improvement to Joomla! Performance and is a real leap forward for customfields. I tested using 3 categories and 1500 articles per category = 4500 articles.

Searched for a keyword within most articles. We get a 504 gateway error after around 10 minutes (Local server for testing).

Applied patch, search result returned with page rendered in: 1180.36 ms which is pretty fast given the content being search. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18915">issues.joomla.org/tracker/joomla-cms/18915</a>.</sub>

2017-12-01 15:17 UTC, angieradtke commented
Retested successful. Great job .-)  This is a big step towards the professional usage of the custom_fields.

2017-12-01 15:24 UTC, franz-wohlkoenig commented
Altered test of @angieradtke as successfully.

2017-12-01 15:25 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2017-12-02 08:18 UTC, alikon commented
I have tested this item :red_circle: unsuccessfully on 5eab93c9cb33a4c8f0b4d060e405392b33ad1287<br /><br />on postgresql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18915">issues.joomla.org/tracker/joomla-cms/18915</a>.</sub>

2017-12-02 08:26 UTC, alikon commented
the offending statement is when we have `a.id IN (cfv.item_id)`
cause we are comparing the `id` field of `#__content` table wich is a `SERIAL` with the `item_id` field of `#__fields_values` table wich is a `VARCHAR`

we need an explicit cast 

from
`$wheres2[] = 'a.id IN( ' . (string) $subQuery . ')';`
to
`$wheres2[] = 'CAST(a.id AS VARCHAR) IN(' . (string) $subQuery . ')';`

lines 125,177,216

2017-12-02 08:28 UTC, alikon requested changes
use CAST for postgresql

2017-12-02 08:28 UTC, alikon commented on plugins/search/content/content.php
> +						$wheres[] = 'a.id IN( ' . (string) $subQuery . ')';
use CAST for postgresql

2017-12-02 08:28 UTC, alikon commented on plugins/search/content/content.php
> +							$wheres2[] = 'a.id IN( ' . (string) $subQuery . ')';
use CAST for postgresql

2017-12-02 08:28 UTC, alikon commented on plugins/search/content/content.php
> +						$wheres2[] = 'a.id IN(' . implode(",", $fieldids) . ')';
use CAST for postgresql

2017-12-02 08:30 UTC, alikon commented
with this changes in place even on postgresql the performance are better

2017-12-02 17:14 UTC, wilsonge commented
Removing RTC so we can fix postgres :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18915">issues.joomla.org/tracker/joomla-cms/18915</a>.</sub>

2017-12-03 09:24 UTC, GeraintEdwards commented
Really sorry about the Postgres - I had 2 development sites running and fixed the casting in the postgres version but hadn't committed from there.

p.s. I am using `"CAST(cfv.item_id as integer)"` since JDatabaseQuery doesn't implement castAsInteger.  CAST is supported by Postgres and the code works fine - see 4.2.8 https://www.postgresql.org/docs/8.1/static/sql-expressions.html

2017-12-03 11:19 UTC, alikon commented
> JDatabaseQuery doesn't implement castAsInteger which would be the most efficient casting/matching so I'm using castAsChar or a.id for the match instead.

good catch, i hope #18961 will fill the gap

we should remeber to use it, when and if #18961 will be merged, but for now we should go even without it :heart_eyes:

2017-12-03 11:20 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 351b0c65ac05d5a1e86c6aa1f775371a59b81b96<br /><br />mysql & postrgesql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18915">issues.joomla.org/tracker/joomla-cms/18915</a>.</sub>

2017-12-03 11:50 UTC, nibra commented
@angieradtke, @tonypartridge, could you please re-test?

2017-12-03 14:00 UTC, angieradtke commented
Second retest succesful on a live project .-)

2017-12-03 14:40 UTC, nibra requested changes
Only one CS issue left: Please add spaces around concat operators. Then all checks will pass and this is ready for commit.

2017-12-03 14:40 UTC, nibra commented on plugins/search/content/content.php
> +					$wheres2[] = $subQuery->castAsChar('a.id').' IN( ' . (string) $subQuery . ')';
Please add spaces around concat operator

2017-12-03 14:40 UTC, nibra commented on plugins/search/content/content.php
> +							$wheres2[] = $subQuery->castAsChar('a.id').' IN( ' . (string) $subQuery . ')';
Please add spaces around concat operator

2017-12-03 14:40 UTC, nibra commented on plugins/search/content/content.php
> +						$wheres[] = $subQuery->castAsChar('a.id').' IN( ' . (string) $subQuery . ')';
Please add spaces around concat operator

2017-12-03 14:50 UTC, franz-wohlkoenig commented
@angieradtke please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/18915)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

2017-12-03 16:06 UTC, angieradtke commented
I have tested this item :white_check_mark: successfully on 6e1c8932d75f6ed4bf15ea41373aa5127b57329f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18915">issues.joomla.org/tracker/joomla-cms/18915</a>.</sub>

2017-12-03 16:18 UTC, nibra approved these changes
Thank you!

2017-12-03 16:30 UTC, merged

2017-12-03 16:31 UTC, wilsonge commented
I tweaked a couple of small c/s issues and merged. Thankyou so much for this :)

2018-01-18 20:28 UTC, joomlabeat commented
Do we actually need the GROUP BY statement in the plugin's query? It doesn't seem it's needful here and taking it off it results to an extra ~30% gain in performance.

2018-01-18 21:26 UTC, zero-24 commented
@joomlabeat as you can see this is a old issue / merged PR. Can you please open a new issue linking to this one? Else this get missed fast. Thanks!

2018-01-18 22:43 UTC, nibra commented
Yes, the GROUP BY is required by the SQL standard (MySQL can deal without, others can't). The drivers are AFAIK not building the GROUP BY causes transparently if needed (which is what they *should* do).

2018-01-19 08:06 UTC, csthomas commented
@joomlabeat is right, line 288 can be completely removed. 

There is only (`#__content` INNER JOIN `#__categories`), there are no duplicates and the query has no  aggregate function.