[4.0] [mod_feed] Improvements
joomla/joomla-cms pull request #18939
Opened 2017-12-01 16:28 UTC by C-Lodder

### Summary of Changes

- Use namespaced classes everywhere

2017-12-01 19:34 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 36c425cdc8692ffbc75ffe13792671305a21c48a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18939">issues.joomla.org/tracker/joomla-cms/18939</a>.</sub>

2017-12-02 17:25 UTC, wilsonge commented on administrator/modules/mod_feed/Helper/FeedHelper.php
> -		catch (\Exception $e)
I think this is a bad change. You need to keep this as global namespace

2017-12-02 17:25 UTC, wilsonge requested changes
See comment

2017-12-02 17:28 UTC, C-Lodder commented
@wilsonge - Hmm I don't even remember changing that as I know it shouldn't be done :/

2017-12-02 19:59 UTC, merged