[new feature] Article notes field
joomla/joomla-cms pull request #19134
Opened 2017-12-22 12:24 UTC by brianteeman

We have a note field for com_categories, com_menus and com_modules
This PR adds the functionality to com_content as it has been requested several times and can be very useful

## To test
Apply the pr AND the database fix (we added a new field)
Create an article and on the right, above version note you will see a new field called note
Enter a note and save the article
You can now see the note with the article in the list
You can also search by the note
Check the featured article list
Check the article modal list (article xtd-editor button or from creating a new single article menu)

On the frontend you can also add/edit a note. You will see it on the publishing tab above the version note field

### Bonus
When adding this field to the frontend beez template I spotted that the version note field wasnt shown there either so I added that at the same time

2017-12-22 12:36 UTC, csthomas commented on administrator/components/com_admin/sql/updates/postgresql/3.9.0-2017-12-22.sql
> +
Use '"' (double quote) instead '`'  to escape names in postgresql.

2017-12-22 13:22 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/3.9.0-2017-12-22.sql
> +
thanks - should be ok now

2017-12-22 17:24 UTC, Quy commented on administrator/components/com_content/views/articles/tmpl/modal.php
> +							<span class="small" title="<?php echo $this->escape($item->path); ?>">
Same fix here with the underlined space.

2017-12-22 17:33 UTC, Quy commented on administrator/components/com_content/models/forms/article.xml
> +			class="span12"
change to `inputbox`

2017-12-22 17:35 UTC, Quy commented on administrator/components/com_content/views/articles/tmpl/modal.php
> +							<span class="small" title="<?php echo $this->escape($item->path); ?>">
`PHP Notice:  Undefined property: stdClass::$path in\administrator\components\com_content\views\articles\tmpl\modal.php on line 141`

2017-12-22 17:35 UTC, brianteeman commented on administrator/components/com_content/models/forms/article.xml
> +			class="span12"
Please check the other notes fields in modules and menu. I am sure this si the same

2017-12-22 17:36 UTC, Quy commented on components/com_content/models/forms/article.xml
> +			class="span12"
change to `inputbox`

2017-12-22 17:47 UTC, Quy commented on media/com_wrapper/js/iframe-height.js
> +    var iframe = document.querySelectorAll('*[id^="blockrandom"]');
Should not be in this PR.

2017-12-22 18:49 UTC, Quy commented on templates/beez3/html/com_content/form/edit.php
> +				</div
Add closing `>`

2017-12-22 19:39 UTC, Quy commented
On the frontend, the note field is wider due to the `span12` class.

![note-frontend](https://user-images.githubusercontent.com/368084/34310489-b241c64a-e70c-11e7-9a5e-b17b1c2a1f4f.gif)

2017-12-22 20:36 UTC, Quy commented on administrator/components/com_content/views/articles/tmpl/modal.php
> +							<span class="small">
Add `break-word`?

2017-12-22 21:58 UTC, brianteeman commented on administrator/components/com_content/views/articles/tmpl/modal.php
> +							<span class="small">
might as well - wont do any harm

2017-12-23 06:22 UTC, Quy commented
I have tested this item :white_check_mark: successfully on c78fdf42a375be2187bb3cdc383f34bc02d72de1<br /><br />Tested with MySQL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19134">issues.joomla.org/tracker/joomla-cms/19134</a>.</sub>

2017-12-23 07:19 UTC, alikon requested changes
the update is wrong you need a single quote before the 
`{"common....`. and another one at the end `fulltext"}}`

should be something like 
`
'{"common":{"core_content_item_id":"id","core_title":"title","core_state":"state","core_alias":"alias","core_created_time":"created","core_modified_time":"modified","core_body":"introtext", "core_hits":"hits","core_publish_up":"publish_up","core_publish_down":"publish_down","core_access":"access", "core_params":"attribs", "core_featured":"featured", "core_metadata":"metadata", "core_language":"language", "core_images":"images", "core_urls":"urls", "core_version":"version", "core_ordering":"ordering", "core_metakey":"metakey", "core_metadesc":"metadesc", "core_catid":"catid", "core_xreference":"xreference", "asset_id":"asset_id", "note":"note"}, "special":{"fulltext":"fulltext"}}'`

the same fix on postgresql and mssql

2017-12-23 10:02 UTC, brianteeman commented
@alikon all done - thanks

2017-12-24 08:45 UTC, alikon commented
I have tested this item :white_check_mark: successfully on e67b6035331f09f8c7d7ac1021485f24a8eaa39f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19134">issues.joomla.org/tracker/joomla-cms/19134</a>.</sub>

2017-12-24 08:51 UTC, alikon approved these changes

2017-12-24 09:31 UTC, franz-wohlkoenig commented
@Quy can you please retest?

2017-12-24 15:55 UTC, Quy commented
I have tested this item :white_check_mark: successfully on e67b6035331f09f8c7d7ac1021485f24a8eaa39f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19134">issues.joomla.org/tracker/joomla-cms/19134</a>.</sub>

2017-12-24 17:10 UTC, Quy commented
RTC

2018-05-29 17:05 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19134">issues.joomla.org/tracker/joomla-cms/19134</a>.</sub>

2018-06-02 15:29 UTC, merged

2018-06-02 17:46 UTC, brianteeman commented
Thanks