[4.0] Set default_view base on component name
joomla/joomla-cms pull request #19266
Opened 2018-01-03 08:23 UTC by joomdonation

Pull Request for Issue # .

### Summary of Changes
In Joomla 3, when we don't set value for $default_view property of controller, Joomla will parse class name of controller and use it as default_view (see https://github.com/joomla/joomla-cms/blob/staging/libraries/src/MVC/Controller/BaseController.php#L427 and https://github.com/joomla/joomla-cms/blob/staging/libraries/src/MVC/Controller/BaseController.php#L767)

In Joomla 4, we use namespace for controller class, so the method getName() doesn't return name of component anymore, thus we had to set value manually for $default_value property of every DisplayController

This PR modify code a bit, set default_view property for controller base on component name, and with this small change, we don't have set default_view property anymore (in case default view is the same with component name) like in Joomla 3.

### Testing Instructions
1. Install Joomla 4.

2. Apply patch

3. As the change is the same, you only need to test com_banners. Access to Components -> Banners -> Banners and confirm that it is still working as before.

2018-01-03 09:40 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on b8807945d4a4483d4c145ea82b77d45070cb2023<br /><br />Test: Create a new banner, un/pin it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19266">issues.joomla.org/tracker/joomla-cms/19266</a>.</sub>

2018-01-03 09:42 UTC, joomdonation commented
Thanks for testing. Actually, this only related to banners list, so if you access to banners list and see it is loading OK, then the test is success, no need for add/pin/un pin banners

2018-01-06 16:24 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 5a564d258fee09346f96bebf918f7dc4b5b73b2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19266">issues.joomla.org/tracker/joomla-cms/19266</a>.</sub>

2018-01-29 10:21 UTC, Anu1601CS commented
I have tested this item :white_check_mark: successfully on 5a564d258fee09346f96bebf918f7dc4b5b73b2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19266">issues.joomla.org/tracker/joomla-cms/19266</a>.</sub>

2018-01-29 10:35 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-01-29 11:27 UTC, zero-24 commented
Just to be sure, what happens when you are going to set that value anyway in a 4.0 component maybe with a different name than the component name? Would the new line not override that value set by the component or I'm missing something here?

2018-01-29 11:32 UTC, joomdonation commented
The component can set that the default view which it wants to use via default_view property of the DisplayController (the value defined in default_view property won't be overridden)

2018-01-29 11:33 UTC, zero-24 commented
ok thanks for confirming. 👍

2018-02-01 23:46 UTC, wilsonge commented on libraries/src/MVC/Controller/BaseController.php
> +			if (array_key_exists('default_view', $config))
Can we change this logic back please. Config should override the class property rather than the other way around.

2018-02-01 23:48 UTC, wilsonge requested changes
As per comment unsure about the new change in behaviour

2018-04-03 11:49 UTC, laoneo commented
I have tested this item :red_circle: unsuccessfully on e86029701031c5f438694d0ab390cd7277203029<br /><br />Tested it with com_contact and when I want to open the back end view, it gives me the following error:
`500 Layout default not found. `<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19266">issues.joomla.org/tracker/joomla-cms/19266</a>.</sub>

2018-05-23 11:09 UTC, closed without merging

2018-05-23 11:14 UTC, laoneo commented
Why did you close this one? Would be nice to get rid of the default views? Just revert the changes @wilsonge mentioned and I will test it again.

2018-05-23 11:17 UTC, joomdonation commented
There have been so many changes in 4.0 repo and I haven't had a chance to look at it again yet. I will look at it when again when I have time and address this issue later.