Filesystem namespace
joomla/joomla-cms pull request #19338
Opened 2018-01-08 19:58 UTC by fastslack

## Summary of Changes

Moved all libraries names to use namespace

## Testing Instructions

Use as usual, all should work fine.

## Expected result

No errors

2018-01-09 07:14 UTC, laoneo requested changes

2018-01-09 07:14 UTC, laoneo commented on libraries/src/Filesystem/Streams/String.php
> +namespace Joomla\CMS\Filesystem\Streams;
Namespace declaration must be on top of the file.

2018-01-09 07:14 UTC, laoneo commented on libraries/src/Filesystem/File.php
>  defined('JPATH_PLATFORM') or die;
Put that after the namespace declaration.

2018-01-09 07:14 UTC, laoneo commented on libraries/src/Filesystem/File.php
> +
One blank line too much.

2018-01-09 07:14 UTC, laoneo commented on libraries/src/Filesystem/Folder.php
>  defined('JPATH_PLATFORM') or die;
Move after namespace declaration.

2018-01-09 07:14 UTC, laoneo commented on libraries/src/Filesystem/Patcher.php
> +defined('JPATH_PLATFORM') or die;
Move after namespace declaration.

2018-01-09 07:14 UTC, laoneo commented on libraries/src/Filesystem/Path.php
>  defined('JPATH_PLATFORM') or die;
Move after namespace declaration.

2018-01-09 07:14 UTC, laoneo commented on libraries/src/Filesystem/Stream.php
>  defined('JPATH_PLATFORM') or die;
Move after namespace declaration.

2018-01-09 07:14 UTC, laoneo commented on tests/unit/suites/libraries/joomla/filesystem/JFilesystemHelperTest.php
> +			array('String'),
Should this not be lower case?

2018-01-09 07:14 UTC, laoneo commented on tests/unit/suites/libraries/joomla/filesystem/JFilesystemHelperTest.php
> +			JFilesystemHelper::isJoomlaStream('String')
Should this not be lower case?

2018-01-11 07:20 UTC, laoneo commented
There are still unit tests failing. Can you fix them please.

2018-01-11 14:16 UTC, fastslack commented
@laoneo @mbabker Im still having the same issue. Test fail is

```
1) JFilesystemHelperTest::testGetJStreams
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'string'
+    0 => 'String'
 )
C:\projects\joomla-cms\tests\unit\suites\libraries\joomla\filesystem\JFilesystemHelperTest.php:65
```

But if i change that file, i still having testing issues. Any idea?

2018-02-01 10:38 UTC, laoneo commented
There are some other errors, please apply the patch on your branch. Then the tests should pass and we can get that in.

```
Index: libraries/src/Filesystem/Streams/String.php
===================================================================
--- libraries/src/Filesystem/Streams/String.php	(date 1515624926000)
+++ libraries/src/Filesystem/Streams/StreamString.php	(date 1517480939000)
@@ -290,4 +290,4 @@
 	}
 }
 
-stream_wrapper_register('string', 'StreamString') or die('StreamString Wrapper Registration Failed');
+stream_wrapper_register('string', '\\Joomla\\CMS\\Filesystem\\Streams\\StreamString') or die('StreamString Wrapper Registration Failed');
Index: libraries/src/Filesystem/Support/Stringcontroller.php
===================================================================
--- libraries/src/Filesystem/Support/Stringcontroller.php	(date 1515624926000)
+++ libraries/src/Filesystem/Support/StringController.php	(date 1517480969000)
@@ -15,7 +15,7 @@
  *
  * @since  11.1
  */
-class Stringcontroller
+class StringController
 {
 	/**
 	 * Defines a variable as an array
Index: libraries/src/Filesystem/FilesystemHelper.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- libraries/src/Filesystem/FilesystemHelper.php	(date 1515624926000)
+++ libraries/src/Filesystem/FilesystemHelper.php	(date 1517481315000)
@@ -274,7 +274,7 @@
 					continue;
 				}
 
-				$streams[] = $file->getBasename('.php');
+				$streams[] = str_replace('stream', '', strtolower($file->getBasename('.php')));
 			}
 		}
 
Index: libraries/classmap.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- libraries/classmap.php	(date 1515624926000)
+++ libraries/classmap.php	(date 1517481181000)
@@ -431,6 +431,6 @@
 JLoader::registerAlias('JStream',                           '\\Joomla\\CMS\\Filesystem\\Stream', '5.0');
 JLoader::registerAlias('JStreamString',                     '\\Joomla\\CMS\\Filesystem\\Streams\\StreamString', '5.0');
 JLoader::registerAlias('JStringController',                 '\\Joomla\\CMS\\Filesystem\\Support\\StringController', '5.0');
-JLoader::registerAlias('JFilesystemWrapperFile',            '\\Joomla\\CMS\\Filesystem\\FileWrapper', '5.0');
-JLoader::registerAlias('JFilesystemWrapperFolder',          '\\Joomla\\CMS\\Filesystem\\FolderWrapper', '5.0');
-JLoader::registerAlias('JFilesystemWrapperPath',            '\\Joomla\\CMS\\Filesystem\\PathWrapper', '5.0');
+JLoader::registerAlias('JFilesystemWrapperFile',            '\\Joomla\\CMS\\Filesystem\\Wrapper\\FileWrapper', '5.0');
+JLoader::registerAlias('JFilesystemWrapperFolder',          '\\Joomla\\CMS\\Filesystem\\Wrapper\\FolderWrapper', '5.0');
+JLoader::registerAlias('JFilesystemWrapperPath',            '\\Joomla\\CMS\\Filesystem\\Wrapper\\PathWrapper', '5.0');
```

2018-02-06 17:29 UTC, laoneo commented
Did you mess up the branch?

2018-02-06 17:31 UTC, laoneo commented
@wilsonge can we merge this one? Will fix the tests then in a second step.

2018-03-26 06:35 UTC, laoneo commented
@wilsonge can we merge this one? Will fix the tests then in a second step.

2018-03-27 19:23 UTC, fastslack commented
@laoneo @wilsonge Sorry i tried lot of things to fix this without any result

2018-04-04 06:37 UTC, merged

2018-04-04 06:40 UTC, laoneo commented
Removed invalid file with c9f684903b9f7869e2282c3281d623173bfd6274.

2018-04-04 11:29 UTC, zero-24 commented
@laoneo please use milestones. Thanks 👍

2018-04-04 11:37 UTC, laoneo commented
Will do.