[SQL] - Add primary key
joomla/joomla-cms pull request #19460
Opened 2018-01-26 09:02 UTC by alikon

Pull Request for Issue #19032.

### Summary of Changes
changed from KEY to PRIMARY KEY for the `#__finder_terms_common`
added the PRIMARY KEY for the `#__utf8_conversion`

### Testing Instructions
fresh install should work as before
with mysql group replication  should finish the installation

###TO DO
-  add update
-  add supported db's changes

2018-01-28 10:03 UTC, Twincarb commented on installation/sql/mysql/joomla.sql
> +  PRIMART KEY (`term`,`language`),
Was this intended to be PRIMARY KEY?

2018-01-29 06:12 UTC, alikon commented on installation/sql/mysql/joomla.sql
> +  PRIMART KEY (`term`,`language`),
yes, misstyped

2018-07-21 02:57 UTC, mbabker requested changes
Seems fine to me, update delta?

2018-08-17 04:34 UTC, franz-wohlkoenig commented
> update delta?

@alikon any Comment?

2018-08-17 06:37 UTC, alikon commented
no comment :smiley: 
it simply went out of my radar
now delta are in

2018-08-17 06:57 UTC, franz-wohlkoenig commented
thanks @alikon 

For test: install https://github.com/alikon/joomla-cms/archive/patch-87.zip is clear, but what means " with mysql group replication should finish the installation"? Is it the same as installing  with mysql group replication should finish the installation?

2018-08-17 08:01 UTC, alikon commented
well i'm afraid it is a bit more complex you should have a mysql Group Replication  server
https://dev.mysql.com/doc/refman/5.7/en/group-replication-requirements.html

2018-08-17 08:01 UTC, alikon commented
ping @michifischer  as he was the issue opener

2018-08-17 08:20 UTC, franz-wohlkoenig commented
@alikon thanks for Information.

2018-08-24 11:10 UTC, franz-wohlkoenig commented
reping @michifischer <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19460">issues.joomla.org/tracker/joomla-cms/19460</a>.</sub>

2019-04-21 15:44 UTC, Hackwar commented
Can we close this? Staging does not accept new features at this point in time, the PR would need several changes right now to be applicable (simply with the version numbers) and in 4.0 this has been changed quite a bit, makeing this obsolete.

2019-04-21 15:44 UTC, franz-wohlkoenig commented
Closed as stated above.

2019-04-21 15:44 UTC, closed without merging

2019-04-22 10:28 UTC, alikon commented
btw this is still valid for table `#__utf8_conversion`