[4.0] Split the configuration of the session service on a per-application basis, restructure session GC command
joomla/joomla-cms pull request #19594
Opened 2018-02-07 01:48 UTC by mbabker

### Summary of Changes

This is restructuring the definition of the core session service for 4.0.

Right now we have an issue where the session service is dependent on the application object for some checks and dependencies.  We can loosen that dependency by splitting the definition up on a per-application basis, which as of this PR only leaves the internal dependency in place to get the `Joomla\Input\Input` objects used in the session store (this can be addressed in a later PR much more easily now).

Additionally, this gives a little more flexibility to our `session:gc` command.  Right now there are technically different session stores/configurations for each of the core applications, primarily because of how the default `session_name` configuration value is set when shared sessions is not active.  So now the command can run garbage collection factoring in each application's configuration appropriately, especially as a `session_gc()` call in PHP requires an active session.

### Testing Instructions

This is predominantly code review, but all CMS operations should continue to function as normal too.

2018-02-12 16:46 UTC, mbabker commented
@laoneo Just an FYI a combination of this and that `$container->get('config')` thing I mentioned in https://github.com/joomla/joomla-cms/pull/19531 should in effect let us fully decouple the app and session instantiation so that we shouldn't need `Factory::$application` to have anything set to it before `$container->get('app');` finishes building whatever application is being requested.  So we would need your PR in first, then sort out that config service, then this be rebased on top of all of that.

2018-02-13 15:59 UTC, laoneo commented
For reference, config service provider PR can be found in #19658.

2018-02-16 00:30 UTC, mbabker commented
Rebased after #19658 

So the only app dependencies left to the session provider are to get the `JInput` object (which I usually just make a service in the container on its own) and to register the event listener for the `SessionEvents::START` event (this one's a little trickier in the scope of the CMS, we can't put this to a plugin because plugins aren't loaded until after the session is started since they rely on the active user and their access levels so we still need a separate non-plugin class to do this job and whatever is registering it has to be smart enough to deal with app differences (the install app just sets an internal data registry as a `Registry` object, the other web apps also set a default `User` object to the user key)).

2018-02-19 18:01 UTC, nibra requested changes
Looks good to me (beside the commented things).

2018-02-19 18:01 UTC, nibra commented on cli/joomla.php
> +	->alias(\Joomla\CMS\Session\Session::class, 'session.cli')
I suppose, those two are intermediate until `JSession` and `\Joomla\CMS\Session\Session` are removed.
If so, wouldn't it be better to put them into their own statement with an appropriate comment?

2018-02-19 18:01 UTC, nibra commented on libraries/src/Service/Provider/Session.php
> +	private function buildSessionHandler(Registry $config): HandlerInterface
Would IMHO be cleaner to put this into its own class `SessionHandlerFactory`.

2018-02-19 18:12 UTC, mbabker commented on cli/joomla.php
> +	->alias(\Joomla\CMS\Session\Session::class, 'session.cli')
Since our container supports autowiring we should have keys for aliased class names so that anything using the class aliases gets resolved correctly.  That covers the `JSession` name (and I'll add a comment on that one in particular later today, commenting here while I run a `composer update`).

(The rest of this is off topic of this PR but since it's on my mind now...)

`Joomla\CMS\Session\Session` doesn't have a deprecation plan yet.  In 4.0 it exists for two things:

1) Handling of the legacy/deprecated `$namespace` parameter for the data read/write methods
2) The static CSRF methods (`getFormToken()` to generate and `checkToken()` to validate)

The CSRF stuff just needs a new home.  `getFormToken()` has a method required by `Joomla\Application\AbstractWebApplication` that can be used for that part of things, which leaves `checkToken()` needing a new home.

2018-02-25 15:57 UTC, mbabker commented on libraries/src/Service/Provider/Session.php
> +	private function buildSessionHandler(Registry $config): HandlerInterface
Created a general `SessionFactory` instead.  If we decide to put other logic into it we can have one package factory instead of one factory per package component IMO.

2018-04-13 15:19 UTC, mbabker commented
Rebased.  To be able to clean up service definition a little bit more and move the session event listener out of the application class to a dedicated event listener this PR really should be merged since it's better defining and splitting up the internal configuration of sessions making the other needed changes easier to abstract out.

2018-04-13 15:50 UTC, nibra commented on libraries/src/Service/Provider/Session.php
> +		array $options): SessionInterface
Are sessions really restricted to CMSApplication? I could imagine that they might be useful in CLIApplications, too...

2018-04-13 15:54 UTC, mbabker commented on libraries/src/Service/Provider/Session.php
> +		array $options): SessionInterface
`CMSApplicationInterface` is defining a few methods that our API kind of requires regardless of CLI or web context (hence the reason the interface is typehinted versus the concrete `CMSApplication`).  The [`ConsoleApplication`](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Application/ConsoleApplication.php) working with our new CLI structure does fulfill this interface, so we aren't restricting things here (and actually because of Joomla's tight coupling to a session we pretty much have to have something, even if it is our runtime storage versus a persistent storage object).

2018-04-13 16:44 UTC, nibra commented on libraries/src/Service/Provider/Session.php
> +		array $options): SessionInterface
Ok, great, just wanted to make sure...

2018-07-04 18:44 UTC, mbabker commented
Last attempt at rebasing this.  Either merge it or close it please.

2018-07-16 11:14 UTC, laoneo commented on libraries/src/Service/Provider/Session.php
> +				$lifetime = ($config->get('lifetime')) ? $config->get('lifetime') * 60 : 900;
The surrounding () can be removed.

2018-07-16 11:14 UTC, laoneo commented on libraries/src/Service/Provider/Session.php
> +				$lifetime = ($config->get('lifetime')) ? $config->get('lifetime') * 60 : 900;
The surrounding () can be removed.

2018-07-16 11:14 UTC, laoneo commented on libraries/src/Service/Provider/Session.php
> +				$lifetime = ($config->get('lifetime')) ? $config->get('lifetime') * 60 : 900;
The surrounding () can be removed.

2018-07-16 11:14 UTC, laoneo commented on libraries/src/Service/Provider/Session.php
> +				$lifetime = ($config->get('lifetime')) ? $config->get('lifetime') * 60 : 900;
The surrounding () can be removed.

2018-07-16 11:14 UTC, laoneo approved these changes

2018-07-28 00:54 UTC, mbabker commented on libraries/src/Service/Provider/Session.php
> +				$lifetime = ($config->get('lifetime')) ? $config->get('lifetime') * 60 : 900;
Codestyle fixed.

2018-07-28 00:54 UTC, mbabker commented on libraries/src/Service/Provider/Session.php
> +				$lifetime = ($config->get('lifetime')) ? $config->get('lifetime') * 60 : 900;
Codestyle fixed.

2018-07-28 00:54 UTC, mbabker commented on libraries/src/Service/Provider/Session.php
> +				$lifetime = ($config->get('lifetime')) ? $config->get('lifetime') * 60 : 900;
Codestyle fixed.

2018-07-28 00:54 UTC, mbabker commented on libraries/src/Service/Provider/Session.php
> +				$lifetime = ($config->get('lifetime')) ? $config->get('lifetime') * 60 : 900;
Codestyle fixed.

2018-08-06 11:27 UTC, laoneo commented on libraries/src/Session/SessionFactory.php
> +				return new Handler\MemcachedHandler($memcached, ['ttl' => $lifetime]);
The $lifetime variable is never initialized.

2018-08-06 11:27 UTC, laoneo commented on libraries/src/Session/SessionFactory.php
> +				return new Handler\RedisHandler($redis, ['ttl' => $lifetime]);
The $lifetime variable is never initialized.

2018-08-07 00:10 UTC, mbabker commented on libraries/src/Session/SessionFactory.php
> +				return new Handler\MemcachedHandler($memcached, ['ttl' => $lifetime]);
Addressed.

2018-08-07 00:10 UTC, mbabker commented on libraries/src/Session/SessionFactory.php
> +				return new Handler\RedisHandler($redis, ['ttl' => $lifetime]);
Addressed.

2018-08-07 00:16 UTC, mbabker commented on composer.json
> +        "symfony/options-resolver": "3.4.*",
For reference this was already a transient dependency, but since I am now explicitly using it it's now listed explicitly here.

2018-08-07 05:40 UTC, merged

2018-08-07 05:40 UTC, laoneo commented
Thanks