Pass the configuration tmp_path to the archive package for extension installations
joomla/joomla-cms pull request #19608
Opened 2018-02-08 02:21 UTC by zero-24

Pull Request for Issue #19503

### Summary of Changes

Pass the configuration tmp_path to the archive package for extension installations

### Testing Instructions

Make sure extension installation still works

### Expected result

extension installation uses the joomla temp folder

### Actual result

extension installation uses the system / server temp folder

### Documentation Changes Required

none

2018-02-08 14:13 UTC, waveywhite commented
This patch doesn't work as it stands.
```
PHP Fatal error:  Class 'Joomla\\CMS\\Installer\\JFactory' not found in /var/www/.../httpdocs/libraries/src/Installer/InstallerHelper.php on line 135
```

JFactory needs a "\" before it to set the correct context, like so:
```
		$archive = new Archive(array('tmp_path' => \JFactory::getConfig()->get('tmp_path')));
```

2018-02-08 14:15 UTC, waveywhite requested changes
JFactory must have a forward slash added because it's not in the current name space. Use \JFactory

2018-02-08 14:18 UTC, zero-24 commented
fixed with the last commit thanks @waveywhite

2018-02-11 06:06 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on 4df1ded6df9810bc52a122b1a8deb693954cbfa7<br /><br />Install works OK, the temp file is created in Joomla Temp Folder instead of system temp folder<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19608">issues.joomla.org/tracker/joomla-cms/19608</a>.</sub>

2018-02-13 10:18 UTC, Anu1601CS commented
I have tested this item :white_check_mark: successfully on 4df1ded6df9810bc52a122b1a8deb693954cbfa7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19608">issues.joomla.org/tracker/joomla-cms/19608</a>.</sub>

2018-02-13 11:53 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-02-26 03:15 UTC, merged