[Installer] Fix DB selection.
joomla/joomla-cms pull request #19646
Opened 2018-02-12 04:39 UTC by asika32764

### Summary of Changes

Joomla 4 use framework DB package now, we must use `mysql` instead `pdomysql` as connection name in installer.

### Testing Instructions

Go to installer step2, the mysql type didn't show at the DB select list.

After this patch, you can select MySQL type.

2018-02-12 07:46 UTC, laoneo commented
So if we do not support mysqli anymore, then we also have to migrate the installations of J3 which are on mysqli to mysql during the upgrade to 4?

2018-02-12 13:02 UTC, mbabker requested changes

2018-02-12 13:02 UTC, mbabker commented on installation/forms/setup.xml
> -				supported="mysqli,pdomysql,postgresql"
This should be `mysql,mysqli,pgsql,postgresql`

`mysqli` and `postgresql` are dependent on the native PHP extensions, `mysql` and `pgsql` are PDO drivers.

2018-02-12 13:04 UTC, mbabker commented on installation/forms/setup.xml
> -				supported="mysqli,pdomysql,postgresql"
Essentially should be the same definition as https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/forms/application.xml#L249-L254

2018-02-12 13:05 UTC, mbabker commented on installation/src/Model/DatabaseModel.php
> +		$options = (object) $options;
Why is the typecast required?

2018-02-12 15:50 UTC, asika32764 commented on installation/src/Model/DatabaseModel.php
> +		$options = (object) $options;
This option is get from session `setup.options`.

See 
https://github.com/asika32764/joomla-cms/blob/a21b29fee3a3e8baa12d58b76e6ec44ace78081d/installation/src/Model/SetupModel.php#L48
and 
https://github.com/asika32764/joomla-cms/blob/a21b29fee3a3e8baa12d58b76e6ec44ace78081d/installation/src/Controller/InstallationController.php#L204-L210

In some case it may be NULL or array and break installer without messages.

2018-02-12 15:52 UTC, asika32764 commented on installation/forms/setup.xml
> -				supported="mysqli,pdomysql,postgresql"
Done

2018-02-12 15:53 UTC, mbabker commented on installation/src/Model/DatabaseModel.php
> +		$options = (object) $options;
:eyeroll:

Not for this PR but we really need to make this ONE type, consistently.  We already have enough problems in our API with type inconsistent code...

2018-02-12 15:56 UTC, asika32764 commented on installation/src/Model/DatabaseModel.php
> +		$options = (object) $options;
Yes I aware of that. I can only fix some parts which I meet the error.

2018-02-16 01:02 UTC, mbabker approved these changes

2018-02-16 01:02 UTC, merged

2018-02-25 10:12 UTC, infograf768 commented
See https://github.com/joomla/joomla-cms/issues/19779

2018-03-18 10:51 UTC, kroonsbe commented
For your info only:
Just trying something to get the installation running, but I only get the selection choice of DB(PDO). Trying to install gives (of course) the enclosed example error message.
I tried to change coding on different relevant places to MySQLi but no succes up to now.
Using PHP 7.2.1
MySQL 5.6.37
Apache server 2.4.29
User agent: Chrome/64 (Windows 10)
![error db pdo](https://user-images.githubusercontent.com/24250077/37565075-8d929e08-2aa2-11e8-9f21-b04a2791eec3.PNG)