[4.0][WIP] Move component categories helper to services
joomla/joomla-cms pull request #19667
Opened 2018-02-13 13:33 UTC by laoneo

Pull Request for Issue #19580.

### Summary of Changes
Introduces a boot functionality for components where they can register services in a container instead of providing helper classes which get loaded magically. Consumer of these services can then boot a component first to make sure, that the services are loaded and get an instance of `ComponentContainerInterface`.

This is WIP till @mbabker, @wilsonge  and me do agree about the boot setup and interface definition.

### Testing Instructions
The instructions below do test the old `JCategories::getInstance()` code and the new one by booting the component.

- Create a second category for articles
- Create an article custom field
- Open an article on the front end

### Expected result
All should work as before.

### Actual result
All should work as before.

### Documentation Changes Required
The new service based approach needs to be documented.

2018-02-13 14:29 UTC, wilsonge commented
Honestly I think that we keep ContentCategories here - the purpose of this was to remove guessing of path location - whilst still having the class - not removing the class altogether. So can we add it back for now please? Even if we end up removing it in a future refactor I want to figure out how it looks in this format :)

2018-02-13 14:30 UTC, wilsonge commented on libraries/src/Categories/Categories.php
> +		$categories = ComponentHelper::boot($parts[0])->getCategories(count($parts) > 1 ? $parts[1] : '');
:+1:

2018-02-13 14:31 UTC, wilsonge commented on libraries/src/Component/ComponentContainer.php
> +	public function getCategories($section = ''): Categories
You can't do this return typehint - it needs to be nullable (i.e. `?Categories`) but it's not available in PHP 7.1 http://php.net/manual/en/migration71.new-features.php

2018-02-13 14:36 UTC, laoneo commented
> So can we add it back for now please

You mean in a namespaced way or the old way?

2018-02-13 14:48 UTC, mbabker commented
Well, a component with its own container doesn't have to follow a strict class naming convention (because the container will define where the service lives), whereas stuff using the legacy container would need to follow the old way.  So, I think you could give it a properly namespaced class name since you're creating a container for com_content.

With that said though, since we support options setting in the constructor, we need to ensure the categories service isn't singleton in the container (i.e. it can't be a shared service).  Otherwise you'll always get an object with the first object's options.

2018-02-13 15:23 UTC, laoneo commented
Added a content specific service class in 1a119fdc1ba254cd7dec56802cc431d768451b46.

2018-02-14 07:22 UTC, laoneo commented
I'v added an interface and trait to load the extensions and added it to the application.

2018-02-14 08:00 UTC, laoneo commented
Removed the WIP. Would be good if @mbabker and @wilsonge can review it again. If all ok then I can move to the other services.

2018-02-14 10:53 UTC, brianteeman commented on libraries/src/Categories/Categories.php
> +	 * Sets the options for this service. The given options do overwrite the
pedantic I know but the word "do" should be deleted

2018-02-14 10:53 UTC, brianteeman commented on libraries/src/Categories/Categories.php
> +		// Merge the options to not loose the base config
lose not loose

2018-02-14 14:00 UTC, wilsonge requested changes
There's one more thing to figure out here. Which is what does an extension do if it doesn't support categories. Does it's container `getCategories` method return `null` all the time. Or do we do some sort of `NotSupported` Exception type for these things rather than returning null?

2018-02-14 14:00 UTC, wilsonge commented on libraries/src/Categories/Categories.php
> +	public function setOptions(array $options)
Can we move this back to the constructor please. I know this is a bit simpler to view but I risking people call `setOptions` and reprovisioning just seems vaguely boring. Let's do one risky thing at a time

2018-02-14 14:00 UTC, wilsonge commented on libraries/src/Extension/ExtensionLoader.php
> +	use ContainerAwareTrait;
I *thought* best practice on this stuff was rather explicitly including a trait here was to add an abstract method into the trait and then `ContainerAwareTrait` into the Application thing.

2018-02-14 14:04 UTC, laoneo commented
> Or do we do some sort of NotSupported Exception type for these things rather than returning null?

At the moment it returns null. If we throw an exception, we always have to do a try/catch around it which would be for me overhead. I was even thinking about to return an empty array just to not always write another "if" check around the for loop.

2018-02-14 14:08 UTC, laoneo commented on libraries/src/Categories/Categories.php
> +	public function setOptions(array $options)
I had to do it that way as in the ComponentContainer [here](https://github.com/joomla/joomla-cms/pull/19667/files#diff-1d65d1ae666dcb6bb6ca7dced9a6d247R48) , it is not possible to pass the options. If there is a way to set the options, then I can change it back to the constructor.

2018-02-14 14:49 UTC, wilsonge commented on libraries/src/Categories/Categories.php
> +	public function setOptions(array $options)
You make this an anonymous function like we do in all the service providers for the main DI Container https://github.com/joomla/joomla-cms/pull/19667/files#diff-a56b3bb3afcd610a7b1560ed05d8a146R17

2018-02-16 00:07 UTC, mbabker commented on libraries/src/Extension/ExtensionLoader.php
> +		$path = $extensionPath . '/services/services.php';
Personally I'd suggest a proper PHP class gets used over a procedural file receiving variables from a calling method's scope.

2018-02-16 06:47 UTC, laoneo commented on libraries/src/Extension/ExtensionLoader.php
> +		$path = $extensionPath . '/services/services.php';
The idea behind this is to have something similar like the [service declaration in Symfony](https://symfony.com/doc/current/components/dependency_injection.html#setting-up-the-container-with-configuration-files). At the moment it is PHP only, but perhaps we add later support for service declaration trough YSON or YAML.
Another benefit is that we do not have to do some magic class compiling again. We can then even get rid of the dispatcher file and load the dispatcher trough the component container. That's my next plan when this one gets merged.

2018-02-16 17:07 UTC, mbabker commented on libraries/src/Extension/ExtensionLoader.php
> +		$path = $extensionPath . '/services/services.php';
Symfony has a different style container than we do (they have a compiled container which is cached and built for production using code generators, we have a runtime container built through injected callables, which when they are Closures can't be serialized/cached in any sane way).  So until we move our code to support compiled/cached containers like that, I don't think we need to consider possible support for other formats.

2018-02-17 19:12 UTC, laoneo commented on libraries/src/Extension/ExtensionLoader.php
> +		$path = $extensionPath . '/services/services.php';
For now we should not focus too much on the service loading strategy. We can change that afterwards when I did the Dispatcher service pr. Is the rest ok?

2018-02-18 18:51 UTC, wilsonge requested changes
Just add the dispatcher into this one, then add the service loading logic we discussed in Glip and I'll get it merged

2018-02-19 15:31 UTC, laoneo commented
Changed the service registering to a class. I would like to do the dispatcher in it's own pr.

2018-02-19 23:28 UTC, nibra reviewed
The `ExtensionManager(Interface|Trait)` looks more like a `ComponentFactory` to me...

2018-02-19 23:28 UTC, nibra commented on administrator/components/com_content/services/provider.php
> +
No namespace?

2018-02-19 23:28 UTC, nibra commented on components/com_content/Service/Category.php
> +namespace Joomla\Component\Content\Site\Service;
Services should be application independent. So why `...\Site\...`?

2018-02-19 23:28 UTC, nibra commented on libraries/src/Extension/ExtensionManagerTrait.php
> +	 * @return  mixed  The extension
In `self::bootComponent()` you rely on the return value being a `ComponentInterface`. In general, `mixed` should never be used as return type.

2018-02-21 08:12 UTC, laoneo commented on components/com_content/Service/Category.php
> +namespace Joomla\Component\Content\Site\Service;
It can even be removed, but for now George wants to have it in place, see the [comment](https://github.com/joomla/joomla-cms/pull/19667#issuecomment-365283005).

2018-02-21 08:13 UTC, laoneo commented on libraries/src/Extension/ExtensionManagerTrait.php
> +	 * @return  mixed  The extension
I had an Interface ExtensionInterface before but removed it because it would be more of a marker interface without any function.

2018-02-21 13:45 UTC, nibra commented on libraries/src/Extension/ExtensionManagerTrait.php
> +	 * @return  mixed  The extension
Nevertheless, the return type should be `ComponentInterface` as expected by `bootComponent()`, or you need to ensure the right type in `bootComponent()` - that's the proce of `mixed`.

2018-02-21 13:46 UTC, nibra commented on components/com_content/Service/Category.php
> +namespace Joomla\Component\Content\Site\Service;
I'm fine with the class itself so far - I just don't see, why it is in a namespace that semantically restricts it to 'site'.

2018-02-21 14:07 UTC, mbabker commented on components/com_content/Service/Category.php
> +namespace Joomla\Component\Content\Site\Service;
We don't have application agnostic component code.  So we'd need a solution to that to get around that (mildly important in some ways) semantic detail.

2018-02-21 14:24 UTC, laoneo commented on libraries/src/Extension/ExtensionManagerTrait.php
> +	 * @return  mixed  The extension
On a long therm I have in mind to support multiple extension types. That's why mixed. I understand your argument.

2018-02-21 14:26 UTC, laoneo commented on administrator/components/com_content/services/provider.php
> +
This is the only thing which get loaded without the namespace. In a first version it was just a plain php file which registered services in a container as you can see [here](https://github.com/joomla/joomla-cms/blob/91c907d56f8b5d26521ef8e192e8f1d162ff52bd/administrator/components/com_content/services/services.php).

2018-02-21 15:45 UTC, nibra requested changes
Questions are answered so far, just one thing left.

2018-02-21 15:45 UTC, nibra commented on libraries/src/Extension/ExtensionManagerTrait.php
> +	 * @return  mixed  The extension
If you want to keep `mixed` (which is ok for now), you need to check that you actually got a `ComponentInterface` complying object, like

    public function bootComponent($component): ComponentInterface
    {
        // ...

        $extension = $this->loadExtension('component', $component, $path);

        if ($extension instanceof ComponenInterface)
        {
            return $extension;
        }

        throw new UnexpectedExtensionType("$component is not a component");
    }

2018-02-21 16:23 UTC, laoneo commented on libraries/src/Extension/ExtensionManagerTrait.php
> +	 * @return  mixed  The extension
The return type declaration does it for us ;)

2018-03-01 21:23 UTC, wilsonge commented
I think there's still quite a lot of tweaks to be made here - but this will do as a starting point :)

2018-03-01 21:23 UTC, merged