[4.0]Improve Code: replace DatabaseDriver::q and DatabaseDriver::qn w…
joomla/joomla-cms pull request #20259
Opened 2018-04-30 10:28 UTC by Wang-Yu-Chao

Pull Request for Issue # .

### Summary of Changes

Replace DatabaseDriver::q and DatabaseDriver::qn with complete name DatabaseDriver::quote and DatabaseDriver::quoteName.

### Testing Instructions

Code review.

### Expected result

None

### Actual result

None

### Documentation Changes Required

None

2018-04-30 10:31 UTC, brianteeman commented
What is the reason for this change?
How does it improve the code?
How do you address the issue of thousands of add ons that use q and qn

2018-04-30 10:40 UTC, dgrammatiko commented
> How does it improve the code?

It improves readability of the code

2018-04-30 10:47 UTC, Wang-Yu-Chao commented
@brianteeman A unified naming style may avoid misunderstandings IMHO

2018-04-30 10:49 UTC, zero-24 commented
> How do you address the issue of thousands of add ons that use q and qn

No need to do that as q and qn are still working ;-) and as @dgrammatiko said it improves the readability and where if not in 4.0 should we start with that :-)

2018-04-30 11:08 UTC, brianteeman commented
My mistake in reading the original comment I assumed that you meant you were removing the ability to use q and qn 

So my question now is why is this for J4 and not for staging - there are no backwards compatible changes/breaks

2018-04-30 11:26 UTC, mbabker requested changes

2018-04-30 11:26 UTC, mbabker commented on libraries/vendor/joomla/database/src/DatabaseQuery.php
> +	 * $query->quote('fulltext');
Should be reverted.  Immediately above these code examples the doc block clearly indicates that `q()` is an alias for `quote()` and documents both valid use cases.

2018-04-30 11:26 UTC, mbabker commented on libraries/vendor/joomla/database/src/DatabaseQuery.php
> +	 * $query->quoteName('#__a');
Same as above, this is documenting both use cases.

2018-04-30 11:26 UTC, mbabker commented on libraries/vendor/joomla/database/src/Query/MysqlQueryBuilder.php
> +	 * $query->quote('fulltext');
Same as above, again this is a documentation example.

2018-04-30 20:41 UTC, ReLater commented
> It improves readability of the code

A very subjective opinion in my opinion.

2018-04-30 20:48 UTC, zero-24 commented
> A very subjective opinion in my opinion.

What is your opinion than? ;) The last I was told about function names was that they should speak for itself ;) And In my opinion there `quote` and `quoteName` is better than `q` and `qn` even when they are shorter and you know what that mean. But think of an developer not original comming from joomla? $db->quoute(Name) would be easier to understand than $db->q(n) where you need to check what q / qn does ;)

2018-04-30 20:52 UTC, mbabker commented
>> It improves readability of the code
> 
> A very subjective opinion in my opinion.

There is nothing wrong with using shortcuts, but when working with a large distributed codebase like Joomla's it is better to use the descriptive method names versus shortcuts so people can pick up on things a bit more easily (`$db->e()` isn't really clear without reading the documentation, `$db->escape()` gives some context without having to read the documentation).

If you write your API well you don't even need doc blocks; well written code should be self documenting (to the extent practical with the language) and be able to stand alone from its documentation.  My personal coding style outside Joomla these days is to omit doc blocks unless they add information that isn't already clear from the method signature (i.e. an explanation of the logic or array type information that most PHP documentation parsers and IDEs will help you with that PHP natively doesn't because you don't have typed arrays or generics in the language).

```php
public function escape(string $contents): string;

/**
 * Method to escape a string
 *
 * @param string $contents The string to escape
 *
 * @return string The escaped string
 */
public function escape($contents);
```

2018-05-01 12:45 UTC, HLeithner commented
Changing q() and qn() to quote() and quoteName() would be a performance gain too.

Also it would be nice to change $query->q/qn to $db->q/qn because JDatabaseQuery does an expensive __call magic + switch + function call + $db->quoteName function call

btw. we have a $query->e() function for escape, this should also be rewritten if we use it in the core.
(JDatabaseDriver doesn't have the 'e' alias)

2018-05-01 13:11 UTC, mbabker commented
> Also it would be nice to change $query->q/qn to $db->q/qn because JDatabaseQuery does an expensive __call magic + switch + function call + $db->quoteName function call

Actually that's gone in 4.0 because we weren't dealing with undefined method call errors at all and I thought it was overkill to have a magic `__call` method for 2 aliases, so just made the aliases "real" methods.  So there's still a small performance loss in using `q()` or `qn()` because it still results in 2 method calls, but not as bad as the existing code.

2018-05-01 13:37 UTC, HLeithner commented on administrator/components/com_menus/Model/ItemsModel.php
> +				->select($this->getDbo()->quoteName(array('id', 'menutype')))
> Actually that's gone in 4.0 because we weren't dealing with undefined method call errors at all and I thought it was overkill to have a magic __call method for 2 aliases, so just made the aliases "real" methods. So there's still a small performance loss in using q() or qn() because it still results in 2 method calls, but not as bad as the existing code.

Sounds good, reducing the behavior would be great anyway.

For example this code is a bit silly ;-) but maybe no the object of this PR

2018-05-02 09:15 UTC, izharaazmi commented
I'd much prefer using `$db->q()`, `$db->qn()` and `$db->esc()` .

It doesn't need to explicitly "speak for itself" as its fairly common enough. About the expensive magic call and switch, I already had some discussion in the past with @mbabker that we should instead have a proper declaration of these shortcuts than via magic calls, which he mentioned in a comment above again.

I won't comment about the `$query->q` and `$query->qn` though as I have no opinion as such right now.

2018-05-09 09:35 UTC, brianteeman commented
@Wang-Yu-Chao can you update with the requests from @mbabker and fix the merge conflict please

2018-05-09 18:42 UTC, HLeithner commented
If this PR is accepted we should adjust https://developer.joomla.org/coding-standards/php-code.html too.

2018-06-04 14:16 UTC, HLeithner commented
@Wang-Yu-Chao any chance to get an update on this?

2018-07-24 16:58 UTC, brianteeman commented
@Wang-Yu-Chao Please can you update this to address the issues raised and fix the conflicts

2018-07-24 17:19 UTC, Wang-Yu-Chao commented
Sorry folks I missed this issue. I'm getting on with it now.

2018-08-08 12:07 UTC, brianteeman commented
Sorry it looks like there are conflicts again that need fixing
and you still need to address https://github.com/joomla/joomla-cms/pull/20259#discussion_r184962402

Once thats done we can merge this quiickly before it gets out of sync again

2018-10-15 11:57 UTC, brianteeman commented
Hi - thank you so much for doing this but we didnt want you to have to redo the pr again so it was done in a new pr and merged. Sorry that this didnt get updated to state that

2018-10-15 11:57 UTC, closed without merging