Finally com_mailto allow the usage of a captach by using JForm
joomla/joomla-cms pull request #20265
Opened 2018-04-30 18:57 UTC by zero-24

### Summary of Changes

Finally com_mailto allow the usage of a captach by using JForm 

As discussed with the JSST this is now a public tracker item: cc @SniperSister @mbabker

### Testing Instructions

- apply this patch
- check that the mail to friend feature still works
- configure the captcha
- check that com_mailto now requires the captcha

### Expected result

com_mailto supports captcha's
com_mailto uses JForm

### Actual result

com_mailto don't supports captcha's
com_mailto don't uses JForm

### Documentation Changes Required

none

2018-04-30 19:06 UTC, brianteeman requested changes

2018-04-30 19:06 UTC, brianteeman commented on components/com_mailto/models/mailto.php
> +	 * @param   array    $data      An optional array of data for the form to interogate.
interrogate

2018-04-30 19:10 UTC, zero-24 commented on components/com_mailto/models/mailto.php
> +	 * @param   array    $data      An optional array of data for the form to interogate.
fixed thanks.

2018-04-30 19:19 UTC, brianteeman commented
milestone is set to 3.8.8. but surely this is a new feature according to semver

2018-04-30 19:21 UTC, zero-24 commented
> milestone is set to 3.8.8. but surely this is a new feature according to semver

new feature? Where do you see a new feature? This is a fix for a broken and exploited attack against sites as noted here in public and in private many times. ;)

2018-04-30 19:22 UTC, mbabker commented on components/com_mailto/views/mailto/view.html.php
> +		$this->set('link', urldecode(JFactory::getApplication()->input->get('link', '', 'BASE64')));
`$this->link = ...`

2018-04-30 19:24 UTC, mbabker commented
You technically get a new feature introducing captcha support to the form.  Otherwise it's all just internal refactoring/restructuring.

2018-04-30 19:33 UTC, zero-24 commented
> You technically get a new feature introducing captcha support to the form. 

Correct but this is just a side effect of the refactoring to JForm ;)

2018-04-30 19:49 UTC, brianteeman commented
Adding captcha is a new feature. Semantic versioning is all about technicalities

2018-04-30 20:03 UTC, zero-24 commented
@mbabker do you agree with @brianteeman or can we move forward with that protection against spam in 3.8.8 by allowing that `feature`?

Or do we need to go the hard way in patching the xml lines for the captcha out and explain in a doc page where to add the support for that.?

2018-04-30 20:49 UTC, ot2sen commented
Must be considered a bug at this stage. Captcha has been a core feature by ages so it must be a bug that it didn´t arrive in all contact or form interactions when first added :)

2018-04-30 20:52 UTC, zero-24 commented on components/com_mailto/views/mailto/view.html.php
> +		$this->set('link', urldecode(JFactory::getApplication()->input->get('link', '', 'BASE64')));
Fixed with the last commit. Thanks.

2018-04-30 20:57 UTC, mbabker commented
To be completely honest it's one of those edge cases where you have to outweigh the user benefit with strict adherence to the standard.  At this point we're dealing with a weakness in core that could've legitimately just been committed to 3.8.8 as a security fix without this public item but we collectively decided this doesn't need to be committed with that type of "secrecy" (for a lack of a better term).  So for me, even though a standard says this strictly must trigger a minor version release, I don't think this absolutely must go into 3.9 and not be addressed in a 3.8 release.

2018-04-30 21:12 UTC, brianteeman commented
@mbabker even if it was a security issue it would still require a version bump
@ot2sen that would be perhaps true if it was indeed added to all forms but it still hasnt been

there are a lot more urgent issues which are actually going to b useful that are being held up for 3.9

either we use semver or we dont - its not something that can be done half heartedly

2018-04-30 21:22 UTC, mbabker commented
It's not being done half-heartedly.  The standard is the guiding line and we have to justify deviating from it (which should be an exceptional basis).  It's not "follow the standard when it's convenient".  If we followed the standard that strictly then we would have to version bump when we:

- Run `composer update` and it includes minor version increments (the changes may not all be part of our API but as part of our distributed package it does introduce new features)
- Update any JavaScript library which is a minor version release (CodeMirror being the common one)
- Merge any patch that is not strictly fixing a bug

So we already do it "half heartedly" in some ways.  Considering I can't get good answers on how to handle releases beyond 3.8.x right now the best thing I can do while I'm running releases is use my best judgment on things.  And considering the amount of marketing hype that the project likes to put onto .0 releases (and the amount of annoyance end users have if .0 releases don't have something new and shiny, see 3.4 and 3.5 reactions) I doubt anyone would want us doing "full blown" feature releases every 2-3 months as that's about the cycle we're on for something being merged that is not 100% in line with the SemVer definition of a patch release.

2018-04-30 21:25 UTC, brianteeman commented
guess i am just frustrated that several pr of mine got delayed because of semver and the privacy plugin will be useless by the time it is released

2018-04-30 22:21 UTC, Quy commented
The form no longer fits within the popup window. You have to scroll down to see the buttons.
The email address is not populated.

Before:
![20265-before](https://user-images.githubusercontent.com/368084/39453137-9f195a1e-4c89-11e8-9bfd-4b487f1f0d9a.jpg)

After:
![20265-after](https://user-images.githubusercontent.com/368084/39453153-ab1bb7b2-4c89-11e8-9215-a798fd34d616.jpg)

2018-04-30 22:45 UTC, zero-24 commented
should be fixed now thanks @Quy

2018-04-30 23:11 UTC, brianteeman commented
the last change isnt a good solution. You have hard coded the height of the popup to the height required by the core captcha irrespective of it being enabled or not. In addition the user could be using a different captcha plugin that requires more space. The modal height should be dynamic based on the content and not fixed or at least in a file that the user can override.

2018-04-30 23:43 UTC, zero-24 commented
Still not great but better than nothing.

2018-05-01 00:00 UTC, Quy commented
Without captcha, it should be 500.

2018-05-01 00:42 UTC, brianteeman commented
did the JSST review the changes in this pr - there are issues

2018-05-01 07:56 UTC, brianteeman commented
Note the style changes because the markup is different which  effects the height

### Before PR
<img width="309" alt="chrome_2018-05-01_08-50-38" src="https://user-images.githubusercontent.com/1296369/39465826-72e5a15c-4d1d-11e8-9176-8eeb9954bdc2.png">



### After PR
<img width="304" alt="chrome_2018-05-01_08-52-22" src="https://user-images.githubusercontent.com/1296369/39465829-75aa7c64-4d1d-11e8-96a2-407aa6001455.png">

2018-05-01 08:04 UTC, zero-24 commented
Fixed thanks. @brianteeman

2018-05-01 08:08 UTC, zero-24 commented
> Without captcha, it should be 500.

well with captcha we than have just 50 more than we can just do it 550 for all?

2018-05-01 08:11 UTC, zero-24 commented
> did the JSST review the changes in this pr - there are issues (not for public explanation)

Just to don't let this claim unanswered. We are in 2018 such a check should not be required any more (It seams to be something added in 2006). But I have just added the check back. And for the record I got an review on the code first for sure. Thanks.

2018-05-01 08:11 UTC, brianteeman commented
This PR doesnt "allow" the use of captcha it forces it on unless you turn it off - is that the intended behaviour?

Maybe I am thick but I dont see where the mailto xml options can be accessed

2018-05-01 08:13 UTC, zero-24 commented
> This PR doesnt "allow" the use of captcha it forces it on unless you turn it off - is that the intended behaviour?

Well when you have setup a captcha joomla should use it by default like we did for the registration right?

2018-05-01 08:17 UTC, brianteeman commented
> We are in 2018 such a check should not be required any more (It seams to be something added in 2006)

the issue addressed back then is still a valid issue today so it is still required

2018-05-01 08:18 UTC, zero-24 commented
> the issue addressed back then is still a valid issue today so it is still required

As i said this check was added back. ;)

2018-05-01 08:37 UTC, brianteeman commented
> Maybe I am thick but I dont see where the mailto xml options can be accessed

2018-05-01 11:55 UTC, zero-24 commented
> Maybe I am thick but I dont see where the mailto xml options can be accessed

As there are no options for com_mailto itself no where :P You can enable and disable the mailto link in com_content / global / menu.

2018-05-01 12:04 UTC, brianteeman commented
so why create https://github.com/joomla/joomla-cms/pull/20265/files#diff-01460342ce71aca88928e9c8be184f21

2018-05-01 12:14 UTC, mbabker commented
To render a JForm instance on the frontend it still uses those XML definitions.

2018-05-01 12:15 UTC, mbabker commented
Plus it defines some rules that are used in form validation.  It's not strictly for backend configuration.

2018-05-01 12:24 UTC, brianteeman commented
see told you I was thick. I guess it was an error then that we didnt use an xml before

2018-05-01 12:27 UTC, mbabker commented
Well when you have a half-million line code base and few people looking over and maintaining all aspects of it... 😆

2018-05-01 12:32 UTC, zero-24 commented
> see told you I was thick. I guess it was an error then that we didnt use an xml before

Yes. We didn't needed that xml as before we just did plain html without using jform now with jform the xml is used for the things Michael posted configuration & validation settings. ;)

2018-05-01 13:33 UTC, Quy commented
In Chrome without captcha, there is a vertical scrollbar. 
![20265-chrome](https://user-images.githubusercontent.com/368084/39474543-5146aece-4d09-11e8-8b1a-ddce83bc9d03.jpg)

2018-05-01 13:37 UTC, Quy commented on components/com_mailto/views/mailto/tmpl/default.php
> +		<fieldset>
Missing closing `</fieldset>`

2018-05-01 13:47 UTC, zero-24 commented on components/com_mailto/views/mailto/tmpl/default.php
> +		<fieldset>
should be fixed now. Thanks

2018-05-01 13:48 UTC, zero-24 commented
> In Chrome without captcha, there is a vertical scrollbar.

I have made the frame even a bit more bigger.

2018-05-01 13:49 UTC, zero-24 commented
@brianteeman can you please approve the language changes (adding the string for Captcha) as the requested changes had been implemented. Thanks.

2018-05-01 13:53 UTC, brianteeman approved these changes

2018-05-02 22:00 UTC, Quy commented
Probably beyond the scope of this PR, can we limit the length of subject and sender to curtail spam? Currently, you can submit a paragraph of text/links in the sender field that will be inserted into the body of the email.

2018-05-02 22:11 UTC, zero-24 commented
> Probably beyond the scope of this PR, can we limit the length of subject and sender to curtail spam? Currently, you can submit a paragraph of text/links in the sender field that will be inserted into the body of the email.

Yes i would call that out of scope but i think we can do that in a following PR when this gets merged. Can you open a issue so we can keep track on that?

2018-05-02 23:19 UTC, Quy commented on components/com_mailto/models/mailto.php
> +		$data = array();
Remove since it will be reassigned on line 58.

2018-05-03 03:01 UTC, Quy commented on components/com_content/helpers/icon.php
> +		$status = 'width=400,height=550,menubar=yes,resizable=yes';
Another way to consider:
```
		$height = JFactory::getApplication()->get('captcha', '0') === '0' ? 450 : 550;
		$status = 'width=400,height=' . $height . ',menubar=yes,resizable=yes';
```

2018-05-03 13:53 UTC, Quy commented on components/com_mailto/models/mailto.php
> +		$data['captcha']   = $input->get('captcha', '', 'string');
Remove `$data['captcha']`. Here is a var_dump of `$input`.

```
  ["data":protected]=>
  &array(12) {
    ["task"]=>
    string(4) "send"
    ["emailto"]=>
    string(19) "test@example.com"
    ["sender"]=>
    string(3) "John Doe"
    ["emailfrom"]=>
    string(19) "test@example.com"
    ["subject"]=>
    string(4) "Test"
    ["g-recaptcha-response"]=>
    string(484) "03AJpayVFwI5ojctS5-iOKcPzmEbYu3vMqhLKgpDYwQl00E1I8a2ALO7elw8GU-vMARD7BeQrvFvzoc9VQlJuGXhs7ThW-_lZ5bQzO4ExyKdWNSuVn0Z65qHs58WdVNlulPTi3y0Rr6h9WkJx4dNerSO7e-uRRevtmf264JMUEUUiFFFaXu2nWGuO3J1X3holMHFKxC2dr8kGD_zUPJKPYmJXp2oBGju9H9JH-7fcgRIb-z8qBaovZ4Bf8y-fMO6NNZg1cTnLdR8Agl07RsPUOrZHty4zF4C7YdGer6tgpGbaukGY9uwpfewFIvCuOXWpyaFghlKJE5olc346PTqCaLwrIGhmmJHC_J23KBm96Cllh0w3X7U4YHdmRDKt3xo3nTHRsCd0pM8xW4SiKnFk4CqevseRa59GAQ9Ppu5P5gUwvpxw8rYkPCnerpyu_iSJoinVLgWOJoRefWqzO8mtN_EF2RZ04QZi_0Q"
    ["layout"]=>
    string(7) "default"
    ["option"]=>
    string(10) "com_mailto"
    ["tmpl"]=>
    string(9) "component"
    ["link"]=>
    string(40) "a9738b32019b618d686bd9a69d68c25b1a7b487b"
    ["cebbff4423bc7e9230300bc2d6e82f61"]=>
    string(1) "1"
    ["Itemid"]=>
    NULL
  }
```

2018-05-03 16:44 UTC, zero-24 commented
Fixed thanks @Quy

2018-05-03 17:42 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 65b0c3b7e671b48d55f0e3d67b16f6a358684ea8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20265">issues.joomla.org/tracker/joomla-cms/20265</a>.</sub>

2018-05-03 17:42 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 65b0c3b7e671b48d55f0e3d67b16f6a358684ea8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20265">issues.joomla.org/tracker/joomla-cms/20265</a>.</sub>

2018-05-04 04:26 UTC, laoneo commented on components/com_mailto/views/mailto/tmpl/default.php
> +					<div class="control-group">
Why do you not use $field->renderField (); ?

2018-05-04 06:20 UTC, infograf768 commented
Tested fine here. Will mark test OK after the change suggested by @laoneo

2018-05-04 06:29 UTC, zero-24 commented on components/com_mailto/views/mailto/tmpl/default.php
> +					<div class="control-group">
I'm going to implement that when i got back at home today. Thanks!

2018-05-04 19:19 UTC, laoneo commented on components/com_mailto/views/mailto/tmpl/default.php
> +					<div class="control-group">
👍

2018-05-04 21:40 UTC, zero-24 commented on components/com_mailto/views/mailto/tmpl/default.php
> +					<div class="control-group">
fixed with the last commit. Thanks.

2018-05-05 22:11 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 7e70b615302dccc7cd1697cafdc90db07e8ca50e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20265">issues.joomla.org/tracker/joomla-cms/20265</a>.</sub>

2018-05-10 02:40 UTC, Quy commented
Ping @infograf768 Thanks.

2018-05-16 20:34 UTC, zero-24 commented
@infograf768 as the requested change have been implemented can you please do your test so we can move that into 3.8.8? Thanks!

2018-05-20 19:47 UTC, zero-24 commented
Well this is going to be delayed to 3.8.9. :( @infograf768 can you please mark your test now so we can finally release it in 3.8.9?

2018-05-21 15:45 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 7e70b615302dccc7cd1697cafdc90db07e8ca50e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20265">issues.joomla.org/tracker/joomla-cms/20265</a>.</sub>

2018-05-21 15:46 UTC, infograf768 commented
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20265">issues.joomla.org/tracker/joomla-cms/20265</a>.</sub>

2018-05-21 16:05 UTC, zero-24 commented
Thanks
@brianteeman
@mbabker
@ot2sen
@Quy
@infograf768
@laoneo

2018-05-23 23:53 UTC, merged