[3.9] Make sure the extension install works as expected
joomla/joomla-cms pull request #20330
Opened 2018-05-09 20:47 UTC by zero-24

### Summary of Changes

Only show a message when the verification fails (request by @mbabker )
Remove the check at install time.
Make sure we are using the correct update object and don't do some magic with passing the update xml.

### Testing Instructions

- Install 3.9-dev https://developer.joomla.org/nightlies/Joomla_3.9.0-dev-Development-Full_Package.zip
- Install any outdated extension that do not support hashes yet (well all 3rd party tools)
- notice the message saying that there is no hash provided
- install the update
- notice the message saying that there is no hash provided
- apply this patch
- redo the steps above
- notice that there is no message at all.
- install com_patchtester
- notice there is no message
- apply the update to the latest com_patchtester
- notice there is no message at all.

### Expected result

Only show a message when the verification fails (request by @mbabker )
Remove the check at install time.
Make sure we are using the correct update object and don't do some magic with passing the update xml.

### Documentation Changes Required

None.

2018-05-09 20:49 UTC, zero-24 commented
Tagging @alikon too ;)

2018-05-09 20:54 UTC, brianteeman requested changes

2018-05-09 20:54 UTC, brianteeman commented on administrator/components/com_installer/models/update.php
> +		// The validation was not successful for now just a warning for now.
The validation was not successful. Just a warning for now.

2018-05-09 21:23 UTC, brianteeman approved these changes

2018-05-09 21:30 UTC, Quy commented on libraries/src/Installer/InstallerHelper.php
> +	 * @return  boolean    False in case the validation did not work; true in any other case.
Shouldn't it be `integer`?

2018-05-09 21:33 UTC, zero-24 commented on libraries/src/Installer/InstallerHelper.php
> +	 * @return  boolean    False in case the validation did not work; true in any other case.
thnaks the initial plan was to change the method but i have just reverted that change.

2018-05-10 00:01 UTC, mbabker commented on administrator/components/com_installer/models/update.php
> +		// The validation was not successful. Just a warning for now.
I'd add a TODO here saying that we'll basically restore this switch case in 4.0.  Beyond that PR's good by me.

2018-05-10 03:55 UTC, Quy commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_INSTALL_CHECKSUM_WRONG="The checksum verification failed. Please make sure you are using the correct update server!"
For the second sentence, how about `Be sure to use the correct update server!`?

2018-05-10 06:48 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_INSTALL_CHECKSUM_WRONG="The checksum verification failed. Please make sure you are using the correct update server!"
The current string is fine and is simpler language than the suggestion.

I missed that you have a space at the end before the exclamation mark that should be removed

2018-05-10 16:34 UTC, wilsonge requested changes

2018-05-10 16:34 UTC, wilsonge commented on libraries/src/Installer/InstallerHelper.php
> +	private function isChecksumValid($packagefile, $updateObject)
still public static :P

2018-05-10 16:40 UTC, wilsonge approved these changes

2018-05-11 06:28 UTC, alikon commented
Why remove the check at install time ?

2018-05-11 08:10 UTC, infograf768 commented
Languages install/reinstall/uninstall fine with this patch.

2018-05-16 20:37 UTC, zero-24 commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_INSTALL_CHECKSUM_WRONG="The checksum verification failed. Please make sure you are using the correct update server!"
> I missed that you have a space at the end before the exclamation mark that should be removed

Was this a suggestion for me? As i don't see a space at the end before the exclamation mark?

2018-05-16 20:42 UTC, zero-24 commented on administrator/components/com_installer/models/update.php
> +		// The validation was not successful. Just a warning for now.
George committed the todo just one line below so this is fine ;)

2018-05-16 21:31 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_INSTALL_CHECKSUM_WRONG="The checksum verification failed. Please make sure you are using the correct update server!"
I dont either - I must have been smoking something - all good for me

2018-05-27 09:52 UTC, alikon commented
I have tested this item :white_check_mark: successfully on a6059d5a0462266d4c5d396a9753624b9c5e513a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20330">issues.joomla.org/tracker/joomla-cms/20330</a>.</sub>

2018-05-31 23:04 UTC, brianteeman commented
(updated title to show it is now for 3.10)

2018-06-01 18:18 UTC, closed without merging

2018-06-01 18:18 UTC, zero-24 commented
Moved: https://github.com/joomla/joomla-cms/pull/20646