Give com_modules a service interface so that com_config can integrate
joomla/joomla-cms pull request #20382
Opened 2018-05-13 08:44 UTC by wilsonge

2018-05-13 08:49 UTC, laoneo requested changes

2018-05-13 08:49 UTC, laoneo commented on administrator/components/com_modules/services/provider.php
> + * The content service provider.
Its the module provider

2018-05-13 08:53 UTC, wilsonge commented on administrator/components/com_modules/services/provider.php
> + * The content service provider.
Oops! Caught on my copy pasting :)

2018-05-14 05:55 UTC, infograf768 commented
I have not tested this item.<br /><br />This solves https://github.com/joomla/joomla-cms/issues/20354<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20382">issues.joomla.org/tracker/joomla-cms/20382</a>.</sub>

2018-05-14 05:55 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 422aa35f06ce14984b0daf7080d9d7cfb57de36d<br /><br />This solves https://github.com/joomla/joomla-cms/issues/20354<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20382">issues.joomla.org/tracker/joomla-cms/20382</a>.</sub>

2018-05-14 11:58 UTC, laoneo approved these changes

2018-05-14 11:59 UTC, laoneo approved these changes

2018-05-14 16:04 UTC, laoneo commented
I have tested this item :white_check_mark: successfully on 422aa35f06ce14984b0daf7080d9d7cfb57de36d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20382">issues.joomla.org/tracker/joomla-cms/20382</a>.</sub>

2018-05-14 16:05 UTC, merged