Move javascript to be inline
joomla/joomla-cms pull request #20393
Opened 2018-05-14 09:37 UTC by wilsonge

Move javascript to enqueue through JDocument and convert from jquery to native js (@dgrammatiko i did something maybe good?)

2018-05-14 11:10 UTC, brianteeman commented
updated the title

2018-05-14 12:09 UTC, dgrammatiko approved these changes

2018-05-14 12:12 UTC, dgrammatiko requested changes

2018-05-14 12:12 UTC, dgrammatiko commented on components/com_users/tmpl/profile/edit.php
> +        document.querySelector('#com_users_twofactor_forms_container>div').forEach(function(el) {
[].slice.call(document....).forEach(...)

Ms edge and ie do not support iteration over nodelist so it needs to be converted to an array

2018-05-14 12:13 UTC, dgrammatiko commented on components/com_users/tmpl/profile/edit.php
> +        document.querySelector('#com_users_twofactor_forms_container>div').forEach(function(el) {
And also it’s document.querySelectorAll() to get the nodelist, document.querySelector() returns the first element

2018-05-18 05:57 UTC, laoneo commented
Should this not be moved to a script to remove inline at all? At least that's what we did in the ES6 repo too.

2018-06-02 16:24 UTC, wilsonge commented
It's not a big deal either way. This was the minimum required for the CSP work we were doing at the JSST sprint.

2018-06-09 13:54 UTC, laoneo commented
Still would be good to have it as its own script like we did with others. To keep consistency.

2018-07-02 10:55 UTC, wilsonge commented
OK So I moved it to a standalone file. But looks like there's some sort of bug because the es6 files don't run through babel (I can't see anywhere where the es6 compiler is even called in `build.js`)

2018-07-02 10:55 UTC, wilsonge commented
@dgrammatiko can you please ensure that we are actually running babel on the es6 files - bit of an issue if we are not!

2018-07-02 11:12 UTC, laoneo commented
Commands are in the descriptoin of #20396.

2018-07-02 12:39 UTC, dgrammatiko commented
@wilsonge https://github.com/joomla/joomla-cms/pull/20954 should do that.

There is a #todo for all the commands to become totally async, right now few are synchronous some are using promises and this will bite us at some point

2018-07-02 15:46 UTC, wilsonge commented
I ran that command @laoneo - thats how i got my minified es6 file. it does not generate the es5 files... #20954 looks like the missing part tho!

2018-07-02 18:42 UTC, laoneo commented
Ok, I assume you saw the two commands. Then we need the help of @dgrammatiko.

2018-07-02 21:34 UTC, wilsonge commented
OK got there in the end.

2018-07-02 21:47 UTC, dgrammatiko commented
Javascript is fun! Nobody said that in 2018... 😂

2018-07-02 21:48 UTC, laoneo commented
Are the failing system tests related to this pr?

2018-07-02 22:22 UTC, brianteeman commented
@laoneo I dont think so - I think that has been there since #20841 but I could be very wrong

2018-07-02 22:25 UTC, laoneo commented
Drone was there green.

2018-07-02 22:30 UTC, laoneo commented
I guess it was https://github.com/joomla/joomla-cms/pull/20919.

2018-07-02 22:31 UTC, merged

2018-07-02 22:31 UTC, laoneo commented
So I'm going to merge this one.