Allow Preview to load in new _blank instead of modal
joomla/joomla-cms pull request #20417
Opened 2018-05-15 21:37 UTC by PhilETaylor

Pull Request for Issue #20241 #20240 .

### Summary of Changes

Allow Preview toolbar buttons to be used as a modal or a link to target=_blank

### Testing Instructions

### Expected result

### Actual result

### Documentation Changes Required

2018-05-15 21:41 UTC, Septdir commented
#20241 - about com_content not only about opening preview in a new window
#20240 -  for j3.x Although I will not oppose its closure. If this is realized in j4.   

Need Testing Instructions

2018-05-16 14:34 UTC, Septdir commented
I have tested this item :white_check_mark: successfully on 63edb82b9fb7a55889139591d63f99d27446ab0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20417">issues.joomla.org/tracker/joomla-cms/20417</a>.</sub>

2018-05-17 17:56 UTC, carlitorweb commented
I have tested this item :white_check_mark: successfully on 63edb82b9fb7a55889139591d63f99d27446ab0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20417">issues.joomla.org/tracker/joomla-cms/20417</a>.</sub>

2018-05-17 18:13 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20417">issues.joomla.org/tracker/joomla-cms/20417</a>.</sub>

2018-05-18 15:10 UTC, yvesh commented on libraries/src/Toolbar/CoreButtonsTrait.php
> +		switch ($newWindow)
Does this really have to be a switch? With a boolean? :-)

2018-05-18 15:11 UTC, yvesh requested changes
Can we do a if here? Without else (just return) ;)

2018-05-18 16:13 UTC, PhilETaylor commented
a bit nit picking especially as its RTC already... 

having two return's instead of one is just as bad as using a switch. 

I have pushed a new code flow - hope you like this one.

If it were my code I would have done FALSE === $newWindow instead of $newWindow === false, but I have had my code changed when I correctly do the former before :)

2018-05-18 18:45 UTC, Quy commented
Please retest.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20417">issues.joomla.org/tracker/joomla-cms/20417</a>.</sub>

2018-05-18 19:00 UTC, Septdir commented
I have tested this item :red_circle: unsuccessfully on 163b39647cd0fb98d133dd61d5cf9b2fb6f382cf<br /><br />```
			\JLoader::register('ContentHelperPreview', JPATH_ADMINISTRATOR . '/components/com_content/helpers/preview.php');
				$url = \ContentHelperPreview::url($this->item);
				$toolbar->preview($url, \JText::_('JGLOBAL_PREVIEW'))
					->bodyHeight(80)
					->modalWidth(90);

				$toolbar->preview($url,'New window', true); // NEW- target=_blank link button
				$toolbar->preview($url,'always modal', false); // like its always been = modal
				$toolbar->preview($url,'old'); // like its always been = modal
```

Add two buttons New window (test in com_content)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20417">issues.joomla.org/tracker/joomla-cms/20417</a>.</sub>

2018-05-18 19:03 UTC, Septdir commented
This code 

```
if ($newWindow === true)
		{
			$button = $this->linkButton('link', $text)
				->url($url)
				->attributes(['target' => '_blank'])
				->icon('icon-eye');
		}
		else
		{
			$button = $this->popupButton('preview', $text)
				->url($url)
				->iframeWidth(640)
				->iframeHeight(480)
				->icon('icon-eye');

		}
```

This code will work correctly

2018-05-18 19:20 UTC, PhilETaylor commented
Yup - it seems that calling $this->linkButton and then $this->popupButton causes a duplicate button and therefore demands the needs for a different code flow, so back to a if/else instead of a switch.

Please retest..

2018-05-18 19:29 UTC, Septdir commented
I have tested this item :white_check_mark: successfully on 710e5427bb4328d69b34afb6dc2e5e05b74c0e9d<br /><br />Now work correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20417">issues.joomla.org/tracker/joomla-cms/20417</a>.</sub>

2018-05-18 19:33 UTC, carlitorweb commented
Good catch @Septdir

2018-05-18 19:35 UTC, PhilETaylor commented
> Good catch @Septdir

Yeah sorry about that, I was "supervising" my kid and her friend at the swimming pool, and coding in the heat and humidity of the viewing area of the public swimming pool... I have a lot of test toolbar buttons and so missed the fact that the re-code flow duplicated the first one.

2018-05-18 19:36 UTC, carlitorweb commented
I have tested this item :white_check_mark: successfully on 710e5427bb4328d69b34afb6dc2e5e05b74c0e9d<br /><br />@PhilETaylor  happens to all ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20417">issues.joomla.org/tracker/joomla-cms/20417</a>.</sub>

2018-05-18 20:02 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20417">issues.joomla.org/tracker/joomla-cms/20417</a>.</sub>

2018-05-19 07:49 UTC, yvesh commented
I meant it like that (else is not necessary).. (Just as a note for future PRs)

```php
if ($newWindow === true)
{
	return $this->linkButton('link', $text)
		->url($url)
		->attributes(['target' => '_blank'])
		->icon('icon-eye');
}

return $this->popupButton('preview', $text)
	->url($url)
	->iframeWidth(640)
	->iframeHeight(480)
	->icon('icon-eye');
```

2018-05-19 07:59 UTC, Septdir commented
@yvesh then we can write so

```
return $newWindow === true ? $this->linkButton('link', $text)->url($url)->attributes(['target' => '_blank'])->icon('icon-eye')
	: $this->popupButton('preview', $text)->url($url)->iframeWidth(640)->iframeHeight(480)->icon('icon-eye');
```

P.S personally I do not like very much when return gets a few lines. Or two identical. IMHO It's better to return a variable.

2018-05-19 08:53 UTC, PhilETaylor commented
**This thread sums up why it it is so hard to contribute to this project.**

The problem with all your comments are that they are PERSONAL PREFERENCE and OPINION. 

**There was nothing wrong with the original proposed change. It met all the[ REQUIREMENTS of the Joomla Code Style](https://github.com/joomla/coding-standards/blob/master/manual/php.md), was readable, documents itself, and worked.**

MY PREFERENCE AND OPINIONS were put to one side, to comply with the [Joomla Code Style](https://github.com/joomla/coding-standards/blob/master/manual/php.md).

MY PREFERENCE AND OPINIONS would be NOT to have two return statements in a single function, that should be avoided at all cost. using if/?/: should also be avoid if it is going to create unreadable, long lines of code.  

Using an if/else or a switch both meet the [Joomla Code Style ](https://github.com/joomla/coding-standards/blob/master/manual/php.md) and whereas my PERSONAL PREFERENCE was a switch (as the code layout is nice, and it SELF DOCUMENTS the backward compatibility) I gave way to accept the if/else.

We are not at RTC.. Im not changing the code again.

2018-05-19 09:28 UTC, yvesh commented
@PhilETaylor that's why i wrote "for the next PR" :-) 

And this is not on preference, else is considered bad style when it can be avoided. (Just google avoid else, return early.. thousands of articles on it).

And it is not meant as critics, it was just a well-intentioned suggestion to improve further..

2018-05-19 09:34 UTC, PhilETaylor commented
I dont see why I should code to YOUR preferences for "the next PR" or any PR.

**The Joomla Project has its Code style guidelines - anything that meets them should be acceptable.**

If you dont like the The Joomla Project preferences. then you can propose changes to the guidelines in a PR in the github repo for them, however just because its YOUR preference **doesnt mean everything else is wrong.** 

Just because there are loads of articles in google, doesnt mean those are right, or even compatible with the Joomla guidelines, now, or in the future.

2018-05-19 09:41 UTC, alikon commented
early return as suggested is not a Code Style pratice,  is much more a "tecnique" to write more clean&manageable code "_Object Calisthenics_" ...

2018-05-19 09:48 UTC, PhilETaylor commented
Actually its still personal preference. For as many that advocate return early, there are the same number of people that advocate against it. 

As there is nothing in the Joomla Code Guidelines against or for it, **a PR should not be criticised against your own ideals, personal opinions and code preferences.**  This discourages contribution and also descends a quick fix in to a personal attacks and massive thread of unneeded opinion.

2018-05-19 09:53 UTC, alikon commented
it wasn't my intention to discourage contributions...
i'm sorry if you felt that way

2018-05-19 09:55 UTC, PhilETaylor commented
If you feel strongly on these points then replace the TODO in this file https://github.com/joomla/coding-standards/blob/master/manual/basic-guidelines.md with a PR with "any words of wisdom about PHP best practice, maybe even references for design patterns"

2018-05-19 10:17 UTC, alikon commented
challenge accepted  see https://github.com/joomla/coding-standards/pull/236

2018-05-19 10:23 UTC, PhilETaylor commented
Good luck! Considering there are PRs from 2013 still open in there!

Seems no one actually cares about coding standards anymore.

——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

> On 19 May 2018, at 11:17, Nicola Galgano <notifications@github.com> wrote:
> 
> challenge accepted see joomla/coding-standards#236
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-05-19 10:32 UTC, alikon commented
@PhilETaylor i know what you mean, and i've experienced that feelings quite sometimes, but if all of us give up ?...
at least i can tell that i've tried :smile: 
https://www.youtube.com/watch?v=tCZxGG_4ins

2018-05-19 16:18 UTC, infograf768 commented
I like if/else.much more readable.

2018-06-11 08:13 UTC, merged

2018-06-11 08:14 UTC, laoneo commented
Thanks @PhilETaylor to make J4 great.