[4.0] Use the app response so we get headers sent on error
joomla/joomla-cms pull request #20431
Opened 2018-05-16 18:30 UTC by wilsonge

Send the app response in the exception handler through `$app->respond` as per @mbabker 's suggestion. This means headers are correctly returned for example. This is more than just a subtlety and required to make webservices work (see https://github.com/joomla-projects/gsoc18_webservices/pull/63)

## Testing Instructions
Test that 404 etc pages work

2018-05-16 18:33 UTC, mbabker requested changes

2018-05-16 18:33 UTC, mbabker commented on libraries/src/Exception/ExceptionHandler.php
> +				$app->out($data);
`Joomla\Console\Application` doesn't have this `out` method, so this is only going to work for apps extending from `Joomla\CMS\Application\CliApplication`.  You'll need another if/else here.

2018-05-16 18:40 UTC, franz-wohlkoenig commented
Added "[4.0]" in Title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20431">issues.joomla.org/tracker/joomla-cms/20431</a>.</sub>

2018-05-16 19:05 UTC, wilsonge commented on libraries/src/Exception/ExceptionHandler.php
> +				$app->out($data);
Ok reverted back ye olde way for me

2018-05-16 19:09 UTC, mbabker approved these changes

2018-05-16 21:44 UTC, carlitorweb commented
I have tested this item :white_check_mark: successfully on 2273abab5e590a68bbf5da58a2c7be261a79dc77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20431">issues.joomla.org/tracker/joomla-cms/20431</a>.</sub>

2018-05-18 06:21 UTC, laoneo commented
I have tested this item :white_check_mark: successfully on 2273abab5e590a68bbf5da58a2c7be261a79dc77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20431">issues.joomla.org/tracker/joomla-cms/20431</a>.</sub>

2018-05-18 06:29 UTC, merged

2018-05-18 06:29 UTC, laoneo commented
Thanks!