[com_contenthistory] - fix for not delete keep forever items
joomla/joomla-cms pull request #20430
Opened 2018-05-16 16:25 UTC by alikon

Pull Request for Issue #20365 .

### Summary of Changes
added the missed check

### Testing Instructions
see #20365

### Expected result
not able to delete a keep forever marked content history item

### Actual result
able

2018-05-16 16:28 UTC, brianteeman commented
If you select 5 items - one of which is flagged keep forever - then it prevents you from deleting them all. I expected it to delete 4 items

2018-05-16 16:42 UTC, alikon commented
should be better now, it deletes only what you can delete

2018-05-16 16:44 UTC, Quy commented on administrator/components/com_contenthistory/models/history.php
> +
Delete blank line

2018-05-16 16:55 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 21d69332c7616c589076cedc4159d29331b1aa0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20430">issues.joomla.org/tracker/joomla-cms/20430</a>.</sub>

2018-05-16 17:29 UTC, ggppdk commented
The keep for ever feature is not "prevent user deletion" thing

It is keep a version when it "ages" due to new versions created ...
aka prevent **automatic** deletion of it

That is why the "... forever" thing 
otherwise it would have been called something else "Not deletable" or something

- please see the description of the feature in the language strings

COM_CONTENTHISTORY_BUTTON_KEEP_TOGGLE_OFF="Select to allow this version to be deleted automatically according to the delete schedule."
COM_CONTENTHISTORY_BUTTON_KEEP_TOGGLE_ON="Select to prevent this version being deleted automatically."

There is nothing to be fixed

if you do this change
then you will also need to update language strings and any documentation written for the feature
and also rename the feature

2018-05-16 17:45 UTC, alikon commented
this is outside of the scope of this silly pr, as for my understanding of this feature...
...but i'm open to different opinions...

2018-05-16 17:58 UTC, ggppdk commented
I would have posted to the original issue #20365, but that is now closed

it is not the PR that is wrong, it is the original issue that was wrong

2018-05-16 18:20 UTC, alikon commented
can you show me where/when  this **automatic** deletion happens  :question:

2018-05-16 18:31 UTC, ggppdk commented
When a new version is stored by store() method of ContentHistoryHelper

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Helper/ContentHistoryHelper.php#L147-L163

there is a cleanup of old version to enforce the limit of maximum versions kept

and it calls 
`public function deleteOldVersions($maxVersions)`
of ContentHistory 's Table class

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Table/ContentHistory.php#L179-L200

2018-05-16 18:31 UTC, peteruoi commented
If you keep 5 versions and the first version is marked  keep forever when the 6th version will come it will not delete the first one but the second one and the result will be still 5 versions stored.

2018-05-16 18:46 UTC, alikon commented
ok sorry this  **keep_forever**  feature, then is not clear to me

2018-05-16 18:53 UTC, Quy commented
Closing as expected per `Keep Forever` tooltips:
`Select to allow this version to be deleted automatically according to the delete schedule.`
`Select to prevent this version being deleted automatically.`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20430">issues.joomla.org/tracker/joomla-cms/20430</a>.</sub>

2018-05-16 18:57 UTC, alikon commented
are you so sure ? 
then fine to me

2018-05-16 19:52 UTC, Quy commented
@alikon I thought that too until reading the documentation further:

> Maximum Versions. The maximum number of versions to store for an item. If an item is saved and the maximum number of versions has been reached, the oldest version will be deleted automatically. If set to 0, then versions will never be deleted automatically. Also, specific versions may be flagged as "Keep Forever" and will not be deleted automatically. Note that versions may be deleted manually using the Delete button in the Version History screen.

> Keep On/Off. This button allows you to toggle on or off the Keep Forever feature for a version. Normally, the oldest version of an item will be deleted automatically when the maximum number of versions (set in the Options for the component) has been exceeded. If you set the Keep Forever property for a version, it will never be automatically deleted.

2018-05-16 21:29 UTC, brianteeman commented
The current way keep forever works is that it wont be automatically deleted based on the number of revisions stored. However, and as originally reported, it seems perfectly reasonable to me that you also can not manually delete something marked as keep forever

2018-05-16 21:38 UTC, carlitorweb commented
For me have sense this PR. Mark a version as "Keep Forever" is a way to prevent someone from mistakenly deleting a version that can not be deleted.

2018-05-16 22:12 UTC, Quy commented
@brianteeman Please decide. I tried to reopen it and got this error:

```
422 RuntimeException
Invalid response from GitHub
```

2018-05-16 22:14 UTC, carlitorweb commented
@Quy Maybe because the branch was deleted.

2018-05-16 22:21 UTC, brianteeman commented
I can't reopen it as the branch is deleted

2018-05-16 22:29 UTC, Quy commented
@alikon Please restore the deleted branch. Sorry I made a hasty decision. Thank you!

2018-05-17 03:42 UTC, ggppdk commented
This PR was created to fix a bug
and as detailed explained,
there was no bug to be fixed in the first place

but since majority here, thinks to change existing design
you will also need to
- update language strings and maybe rename it
- update documention
- add some message why the version was not deleted, 

finally people using this so far will have a small surprise when trying to cleanup their keep forever versions because they want to mark some other as keep forever

2018-05-17 04:06 UTC, ggppdk commented
And besides what i mentioned above,
you are not changing the behavior in com_content only

you are changing the behavior in all core and 3rd party extensions that use versions
maybe a confirmation when clicking the delete button would be better: 

Some of the versions selected for deletion are marked as keep-forever, are you sure to delete them ?

2018-05-17 07:19 UTC, brianteeman commented
@ggppdk I dont agree - keep forever should mean exactly that. No need to change the text at all

2018-05-17 07:50 UTC, ggppdk commented
well about **name**, you are propably right, no need to change it
i said, maybe naming needs to be changed

but the description language strings and documentation need to be changed / updated
and the rest i said , do apply

2018-05-17 19:26 UTC, alikon commented
restored
@Quy,  no problem at all :smile:

2018-05-18 18:47 UTC, Quy commented
Reopening for further discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20430">issues.joomla.org/tracker/joomla-cms/20430</a>.</sub>

2018-05-18 19:20 UTC, carlitorweb requested changes

2018-05-18 19:20 UTC, carlitorweb commented on administrator/components/com_contenthistory/models/history.php
> +					continue;
Whitespace at end of the line

2018-05-18 19:30 UTC, carlitorweb commented
Also, I think is good change this string `COM_CONTENTHISTORY_BUTTON_DELETE_DESC` describing that these types of versions cannot be eliminated

2018-05-21 16:25 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 21d69332c7616c589076cedc4159d29331b1aa0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20430">issues.joomla.org/tracker/joomla-cms/20430</a>.</sub>

2018-06-16 15:03 UTC, franz-wohlkoenig commented
@Quy can you please Retest?

2018-06-16 15:16 UTC, carlitorweb commented
I did the test, just as have a CS, I not did the test result, waiting for that. I will do now, no problem

2018-06-16 15:17 UTC, carlitorweb commented
I have tested this item :white_check_mark: successfully on 21d69332c7616c589076cedc4159d29331b1aa0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20430">issues.joomla.org/tracker/joomla-cms/20430</a>.</sub>

2018-06-16 15:51 UTC, franz-wohlkoenig commented
Ready to Commit after 3 successful tests.

2018-06-16 15:54 UTC, alikon commented
sorry @carlitorweb i've losed your comment ...

2018-06-16 15:54 UTC, carlitorweb commented
No problem @alikon

2018-06-18 02:55 UTC, merged