[4.0] httpheaders Implement the suggestion by @brianteeman
joomla/joomla-cms pull request #20491
Opened 2018-05-19 21:03 UTC by zero-24

### Summary of Changes

Implement the list suggested by @brianteeman 

### Testing Instructions

Confirm that the custom headers are working

### Expected result

custom headers are working

### Actual result

custom headers are not working

### Note

@brianteeman please suggest the language changes. Maybe dropping the description completely?

And please tell me which strings from here: https://github.com/joomla/joomla-cms/pull/20459 do you want to keep or change. I'm happy to implement.

2018-05-19 21:06 UTC, zero-24 commented
Ah and @brianteeman do you agree that we don't allow the values to be translated or do you want me to move them to language strings?

2018-05-19 21:45 UTC, brianteeman commented
Correct they don't need to be translated. Not even sure they could be

2018-05-19 21:59 UTC, brianteeman commented
Not sure if its my branch but I am now missing some strings. Can you check please

We don't need the PLG_SYSTEM_HTTPHEADERS_ADDITIONAL_HEADER_DESC anymore and all the strings for the options can go as well as things like X-XSS-Protection should not be translated.

Finally can you change the name to System HTTP Headers - we have a space bar on an english keybard :)

2018-05-20 18:25 UTC, zero-24 commented
> Correct they don't need to be translated. Not even sure they could be

Done also for the referrerpolicy rules.

> Not sure if its my branch but I am now missing some strings. Can you check please

What do you mean? did you pull my branch?

> We don't need the PLG_SYSTEM_HTTPHEADERS_ADDITIONAL_HEADER_DESC anymore and all the strings for the options can go as well as things like X-XSS-Protection should not be translated.

XSS Protection? I guess you mean the referrerpolicy?

> Finally can you change the name to System HTTP Headers - we have a space bar on an english keybard :)

Done. :)

2018-05-20 19:17 UTC, brianteeman commented
I fixed my branch and now this is all good - my concern with the language strings can be illustrated by this string
PLG_SYSTEM_HTTPHEADERS_REFERRERPOLICY="<a href='https://scotthelme.co.uk/a-new-security-header-referrer-policy/' target='_blank'>Referrer-Policy</a>"

I am concerned that "Referrer-Policy" would be translated by the TT and it absolutely must not be. The same applies to all the other headers which must not be translated in the text.

From our experience with the "installation" folder string the TT will ignore any notes we add to the language file not to translate these words and the only solution we found for that one was to remove "installation" from the language file strings and just have a %s 

Its not ideal but i cant think of any other way to prevent these strings from being translated

2018-05-20 19:20 UTC, zero-24 commented
>I am concerned that "Referrer-Policy" would be translated by the TT and it absolutely must not be. The same applies to all the other headers which must not be translated in the text.

Agree my point is that we use to include the link with more infos using that language string. Do you think we should drop them?

2018-05-20 19:23 UTC, brianteeman commented
well its not just there it is also in the post installation message and some of the _DESC

other than the ugly %s i dont know what else to suggest

2018-05-20 19:30 UTC, zero-24 commented
> well its not just there it is also in the post installation message and some of the _DESC

hmm my problem is that i don't know how to append them using %s as the postinstall is hardcoded and the same apply to the xml labels and description.

2018-05-20 19:33 UTC, brianteeman commented
maybe ask the TT Leader for some input?

2018-05-20 19:34 UTC, zero-24 commented
> maybe ask the TT Leader for some input?

@infograf768 can you please take a look here? Thanks!

2018-05-20 19:36 UTC, brianteeman commented
I meant https://volunteers.joomla.org/joomlers/267-ilagnayeru-mig-manickam

2018-05-20 19:48 UTC, zero-24 commented
Ping @imanickam too.

2018-05-21 05:29 UTC, imanickam commented
Good Morning!

Reviewed the xml files and I do agree that the values need not be derived from the language strings.  Whereas, the description text for the options could use language strings (e.g. JYES, JNO).

Brian's concern is very valid that it should not happen just like the word 'installation' has been translated in the installation ini files. However, I feel that this case is slightly different.
  
We can have the policy names (e.g., Referrer-Policy, X-XSS-Protection) as distinct language strings with language constants identifying the policy name so that they are grouped in one place in the language file, and have a comment not to translate the policy names.

Example:
; Please DO NOT TRANSLATE the language values for the language strings starting with PLG_SYSTEM_HTTPHEADERS_POLICY_NAME
PLG_SYSTEM_HTTPHEADERS_POLICY_NAME_REFERRERPOLICY="Referrer-Policy"
PLG_SYSTEM_HTTPHEADERS_POLICY_NAME_XXSSPROTECTION="X-XSS-Protection"

As these language strings would be used for display purpose only, IMHO, it should not affect any outcome.

As for as using placeholders within the language strings of Post Install messages, let me request JM to offer suggestions.

2018-05-21 06:50 UTC, infograf768 commented
Trying to find a solution.

In the mean while, please change EOL from Windows to Unix for the `en-GB.plg_system_httpheaders.ini` file

Also, when debug lang is on, I get these JGLOBAL strings constants for the tabs :
<img width="770" alt="screen shot 2018-05-21 at 08 48 44" src="https://user-images.githubusercontent.com/869724/40293993-d1311a8c-5cd3-11e8-9f01-cc5e666a88ee.png">

2018-05-21 08:07 UTC, infograf768 commented
Some thoughts as they come:

This is a totally new plugin for a new version of Joomla where we will ask TTs to re-apply as TTs and where the packs will be quite different as 90% of the ini files will have to be largely modified. 

Therefore the issue can't be compared with the `installation` issue which was a > 10 years old one. What I mean is that the "new" TTs will be strongly briefed about what should and what should not be translated in these new strings.

NOTE:
For forms (not for postinstall), this shows we could improve the field translations.
What I am thinking of is something like this:
add new $element(s) (or many, incremented) `var-label="MYSTRING_VAR_LABEL"` and `var-description="MYSTRING_VAR_DESC"`
Add these new strings in the ini file concerned. Group them.
Then, when present in the field, translate them with a `JText_::_`
Then, still if present in the field, instead of using a `JText::_` for the label or description, use a `JText::sprintf` adding this new variable (or multi). 
Looks like we could do that in `FormField`

2018-05-21 08:31 UTC, brianteeman commented
> This is a totally new plugin for a new version of Joomla where we will ask TTs to re-apply as TTs and where the packs will be quite different as 90% of the ini files will have to be largely modified.

I was not aware of that so maybe we can manage with just the "do not translate this" comment

2018-05-21 08:37 UTC, infograf768 commented
It would have to be more precise depending on the strings as the words not to translate may be part of stuff which need translating. 
Presenting these words not to translate between quotes helps Translators to understand that they do not need to be translated.

Example:
original string
`PLG_SYSTEM_HTTPHEADERS_XCONTENTTYPEOPTIONS="<a href='https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options' target='_blank'>X-Content-Type-Options</a>"`
could be
`PLG_SYSTEM_HTTPHEADERS_XCONTENTTYPEOPTIONS="<a href='https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options' target='_blank'>\"X-Content-Type-Options\"</a>"`

2018-05-21 08:42 UTC, brianteeman commented
In a sentence then yes it does but where it is the entire label as it is here then it is not correct for the UI

2018-05-21 12:04 UTC, zero-24 commented
Thanks i have just commited the "do not translate" comments & used the JGLOBAL strings as suggested please review. https://github.com/joomla/joomla-cms/pull/20491/commits/38abbbdb13b8e57cc1e039adc53b774abc7d963c

2018-05-21 12:23 UTC, brianteeman commented
@zero-24 its not that simple

"HTTP Header" can not be translated - nor can ANY of the technical terms anywhere

2018-05-21 12:42 UTC, zero-24 commented
> "HTTP Header" can not be translated - nor can ANY of the technical terms anywhere

I have just extended the comments. :)

2018-05-21 12:55 UTC, brianteeman requested changes

2018-05-21 12:55 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
> +; Please do not translate the names of the http headers in the following 2 language strings
copy paste error should be "Content-Security-Policy" not http headers

2018-05-21 12:55 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY_REPORT_ONLY="Report-Only"
do not translate

2018-05-21 12:55 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY_REPORT_ONLY_DESC="This option uses the header 'Content-Security-Policy-Report-Only' instead of 'Content-Security-Policy"
do not translate Content-Security-Policy-Report-Only

2018-05-21 12:55 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
> +; Please do not translate the names of the http headers in the following language string
copy paste error should be "strict transport security" not http headers

2018-05-21 12:55 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_HSTS_MAXAGE_DESC="This option sets the time for 'max-age', it is specified in seconds. The default value is 31536000, which corresponds to one year"
do not translate max-age

2018-05-21 12:55 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_HSTS_PRELOAD_NOTE_DESC="HSTS means that your domain can no longer be called without HTTPS. Once added to the preload list, this is not easy to undo. Domains can be removed, but
do not translate "maximum recording time"

2018-05-21 12:55 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_XML_DESCRIPTION="This Plugin helps you to set the HTTP Security Headers"
do not translate "HTTP Security Headers"

2018-05-21 13:14 UTC, zero-24 commented
Done thanks @brianteeman

2018-05-21 14:14 UTC, infograf768 commented
Is `Maximum recording time` same as `Maximum registration time` ?
if it is let's choose one of them only

2018-05-21 14:50 UTC, infograf768 commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_HSTS_PRELOAD_NOTE_DESC="HSTS means that your domain can no longer be called without HTTPS. Once added to the preload list, this is not easy to undo. Domains can be removed, but
Why not translate that?

2018-05-21 14:51 UTC, infograf768 commented
@brianteeman 
Why `maximum recording time` should not be translated?

2018-05-21 14:52 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_HSTS_MAXAGE_DESC="This option sets the time for 'max-age', it is specified in seconds. The default value is 31536000, which corresponds to one year"
Let's remove `it is specified ` to be `This option sets the time for 'max-age' in seconds.` or `This option sets the time for 'max-age' specified in seconds.`

2018-05-21 15:17 UTC, brianteeman commented
Sorry I might be confusing the maximum recording time - I thought that was the name of the actual attribute. Looking further if i understand the code correctly this refers to the attribute "max-age". That attribute should not be translated AND "maximum recording time" is not a correct description of "max-age"

the attribute "max-age" refers to how long the policy should remain in effect https://tools.ietf.org/html/rfc6797#section-6.1.1 so I am not sure why you have written it as "maximum recording time" 

it should just be the untranslatable "max-age"

2018-05-21 16:04 UTC, zero-24 commented
pushed thanks!

2018-05-21 16:06 UTC, brianteeman approved these changes

2018-05-21 16:06 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 0aecc2f87e58b19ae786aabd08560f71985ec9d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20491">issues.joomla.org/tracker/joomla-cms/20491</a>.</sub>

2018-05-21 20:06 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY_REPORT_ONLY_DESC="This option uses the header 'Content-Security-Policy-Report-Only' instead of 'Content-Security-Policy"
Missing ending `'`

2018-05-21 20:18 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY_VALUES_DIRECTIVE="Policy directive"
Capitalize `d`

2018-05-21 20:20 UTC, Quy commented on plugins/system/httpheaders/subform/customhttpheaders.xml
> +		<option value="x-xss-protection">X-XSS-Protection</option>
https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection has it as `X-Xss-Protection` (not XSS)

2018-05-21 20:28 UTC, zero-24 commented on plugins/system/httpheaders/subform/customhttpheaders.xml
> +		<option value="x-xss-protection">X-XSS-Protection</option>
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

:) So X-XSS is fine :)

2018-05-21 20:28 UTC, zero-24 commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY_VALUES_DIRECTIVE="Policy directive"
fixed

2018-05-21 20:41 UTC, Quy commented on plugins/system/httpheaders/subform/customhttpheaders.xml
> +		default="no-referrer-when-downgrade"
I don't see `no-referrer-when-downgrade` option below.

2018-05-21 20:44 UTC, zero-24 commented on plugins/system/httpheaders/subform/customhttpheaders.xml
> +		default="no-referrer-when-downgrade"
fixed

2018-05-21 22:24 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
>  PLG_SYSTEM_HTTPHEADERS_HSTS_SUBDOMAINS="Also for subdomains"
How about `Include Subdomains`?

2018-05-21 22:27 UTC, Quy commented
I know this is beyond the scope of this PR, how about making `Site`, `Administrator`, `Both ` a dropdown instead radio buttons?

2018-05-22 07:29 UTC, infograf768 commented
@zero-24 
If this https://github.com/joomla/joomla-cms/pull/20525 is merged, we could simplify your strings by grouping the values not to translate in simple strings and then using a placeholder where fit.

2018-05-24 05:01 UTC, infograf768 commented
Even better. Let's take this label
PLG_SYSTEM_HTTPHEADERS_HSTS_MAXAGE="max-age"

we can simply do
PLG_SYSTEM_HTTPHEADERS_HSTS_MAXAGE="%s"
and add in the field xml
varLabel="max-age"
and TTs will never mistake.

2018-05-24 06:56 UTC, brianteeman commented
That only helps where the term is the only thing in the string

2018-05-24 07:36 UTC, infograf768 commented
> That only helps where the term is the only thing in the string

Indeed. It is a bonus. But the feature let's use the variable from another string  as everybody understood... Example:

`PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY="<a href='https://scotthelme.co.uk/content-security-policy-an-introduction' target='_blank'>Content Security Policy (CSP)</a>"` 
can be replaced by
`PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY="<a href='https://scotthelme.co.uk/content-security-policy-an-introduction' target='_blank'>%s</a>"`

and then we use in the field
```
				<field
					name="contentsecuritypolicy"
					type="radio"
					label="PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY"
					description="PLG_SYSTEM_HTTPHEADERS_CONTENTSECURITYPOLICY_DESC"
					class="switcher"
					default="0"
					varLabel="JGLOBAL_FIELDSET_CSP"
					>
					<option value="0">JDISABLED</option>
					<option value="1">JENABLED</option>
				</field>
```
Where `JGLOBAL_FIELDSET_CSP` (already present string) has the value `"Content-Security-Policy (CSP)"`

Same evidently for the description and other strings in the ini files, and not only for this plugin.

2018-05-25 20:22 UTC, zero-24 commented
Until that PR is merged i think we should not block this PR and get some tests + merge? What do you think?

2018-05-26 05:55 UTC, infograf768 commented
As merging https://github.com/joomla/joomla-cms/pull/20525 would imply many changes in the ini strings, not sure we should.
If both people here in favor or immediate merging were just testing 20525, we could get further pretty fast. It is not as we would be in such a hurry that this PR here has to get in at once because of a urgent release.

2018-06-03 10:53 UTC, brianteeman commented
I guess this will need updating when #20525 is merged (it is RTC)

2018-06-20 18:38 UTC, wilsonge commented
Please remove 

```
JGLOBAL_FIELDSET_HSTS="Strict-Transport-Security (HSTS)"
JGLOBAL_FIELDSET_CSP="Content-Security-Policy (CSP)"
```

from the language files and just hardcode them in the XML - if they are standalone strings like this that should not be translated them don't put them in language files.

2018-06-20 18:47 UTC, zero-24 commented
Thanks implemented now @wilsonge 👍

2018-06-20 18:54 UTC, merged

2018-06-21 06:05 UTC, brianteeman commented
CSP is not to be translated - source 
https://developer.mozilla.org/fr/docs/Web/HTTP/CSP

2018-06-21 21:50 UTC, zero-24 commented
> CSP is not to be translated - source
https://developer.mozilla.org/fr/docs/Web/HTTP/CSP

@brianteeman I have just looked at the current strings. ATM we only have one line with `CSP`
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/en-GB.plg_system_httpheaders.ini#L15
=> The complete string is marked as not to be translated.

The others are Hardcoded now in the XML like George suggested. I'm still missing something?

2018-06-22 07:09 UTC, infograf768 commented
@wilsonge 
It is pretty frustrating that https://github.com/joomla/joomla-cms/pull/20525 has been RTC for a while and not merged, which would have simplified this PR here and be quite useful in future other cases.
It would really help volunteers if a decision had been taken about it and not just ignoring it.

2018-06-22 17:30 UTC, zero-24 commented
When #20525 is merged we can do a PR that implements that.

2018-06-22 17:31 UTC, zero-24 commented
This has been merged so we can move forward with the csp integration.