Respect access of editor plugin inside profile form
joomla/joomla-cms pull request #20713
Opened 2018-06-11 07:05 UTC by ggppdk

Pull Request for Issue #20605

### Summary of Changes
1. Add support for option `useaccess="1" ' to form field element 'plugins' (class JFormFieldPlugins)
\libraries\joomla\form\fields\plugins

2. Use the above option in the form XML for profile edit screens
(**frontend**: /components/com_users/models/forms/frontend.xml)
(**backend**: /administrator/components/com_users/models/forms/profile.xml)

### Testing Instructions
After installing patch

1. Set codemirror to access 'Customer Access Level (Example)'
3. Login backend and frontend as super admin (or with some other account that does not have the access level 'Customer ....'
3. Click to "edit account" in backend or "Your profile" menu link in frontend 
4. Go to Basic Settings (Fieldset or Tab) and try to select editor. Verify that codemirror is no longer shown

### Expected result

### Actual result

### Documentation Changes Required
Yes
document new optio here (and elsewhere):
https://docs.joomla.org/Plugins_form_field_type
**useaccess** set to 1 to only list plugins with an allowed access level for current usertext for the form field.

2018-06-11 10:12 UTC, jurihahn commented
I have tested this item :white_check_mark: successfully on f136619179e4f174771af42529c5d36527ee07e1<br /><br />Tested on clean Joomla 3.8.8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20713">issues.joomla.org/tracker/joomla-cms/20713</a>.</sub>

2018-06-15 23:57 UTC, carlitorweb commented
I have tested this item :white_check_mark: successfully on f136619179e4f174771af42529c5d36527ee07e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20713">issues.joomla.org/tracker/joomla-cms/20713</a>.</sub>

2018-06-15 23:58 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20713">issues.joomla.org/tracker/joomla-cms/20713</a>.</sub>

2018-06-16 00:44 UTC, mbabker commented on components/com_users/models/forms/frontend.xml
> +				useaccess="1"
Can we use "true" instead of an integer here?  We aren't gaining much by trying to use numeric values as boolean flags in an XML document.

2018-06-16 04:47 UTC, alikon requested changes

2018-06-16 04:47 UTC, alikon commented on libraries/joomla/form/fields/plugins.php
> +				$query->where('access IN (' . $groups . ')');
please use $db->quoteName()

2018-06-16 05:51 UTC, ggppdk commented on libraries/joomla/form/fields/plugins.php
> +				$query->where('access IN (' . $groups . ')');
The rest of the query is not using it , should i go ahead and quoteName just this one only ?

2018-06-16 09:18 UTC, ggppdk commented on components/com_users/models/forms/frontend.xml
> +				useaccess="1"
@mbabker that would be nicer, and i have thought of it,
but please take at look at existing code for a similar parameter 'useglobal' that uses string value 'true'
the code is inside same file and in other files too

e.g. useglobal="false" **will be interpretted as by existing code** as ... true,
because they are non-zero length strings 
so for useaccess, useglobal, etc one will need to do a thing like
`(string) $this->element['useaccess'] === 'true'`

2018-06-16 13:25 UTC, mbabker commented on components/com_users/models/forms/frontend.xml
> +				useaccess="1"
`*sigh*` so many shortcuts and UX/DX fails...

2018-06-16 13:49 UTC, ggppdk commented on components/com_users/models/forms/frontend.xml
> +				useaccess="1"
@mbabker , done your requested change (to use ="true"),
about how field PHP code checks the string 'true' value i will open a new issue or make some PRs (e.g. useglobal) to make it consistent

2018-06-16 13:51 UTC, ggppdk commented on libraries/joomla/form/fields/plugins.php
> +				$query->where('access IN (' . $groups . ')');
@alikon done

2018-06-18 02:49 UTC, merged