Com_finder meta data
joomla/joomla-cms pull request #20772
Opened 2018-06-15 12:19 UTC by brianteeman

com_finder aka smart search was not following any meta data set in the menu item

#### to test

 - setup and configure smart search
 - create a menu item for smart search and set the meta description and meta keywords
 - open the menu item on the front end - check source and the meta data set in the menu is not present
 - do a search
 - check source and the meta data has been generated from the search

Apply this PR
 - open the menu item on the front end - check source and the meta data set in the menu is present
 - do a search
 - check source and the meta data has been generated from the search

Pull Request for Issue #20737

2018-06-15 12:23 UTC, mbabker commented on components/com_finder/views/search/view.html.php
> +			$author = $this->item->created_by_alias ?: $this->item->author;
You don't have a `$this->item` in this context to set an author meta from.

2018-06-15 22:36 UTC, carlitorweb requested changes

2018-06-15 22:36 UTC, carlitorweb commented on components/com_finder/views/search/view.html.php
>  			$this->document->setMetaData('keywords', implode(', ', $query->highlight));
fix this one too `setMetaData `-to `setMetadata`

2018-06-15 22:41 UTC, brianteeman commented on components/com_finder/views/search/view.html.php
>  			$this->document->setMetaData('keywords', implode(', ', $query->highlight));
No - its correct here (and wrong in some other places)

https://github.com/joomla/joomla-cms/blob/421749c81b15177ed6ea0a1f7256e90d16564f33/libraries/src/Document/Document.php#L433

2018-06-15 22:44 UTC, carlitorweb commented on components/com_finder/views/search/view.html.php
>  			$this->document->setMetaData('keywords', implode(', ', $query->highlight));
True!, sorry for this

2018-06-15 22:48 UTC, brianteeman commented on components/com_finder/views/search/view.html.php
>  			$this->document->setMetaData('keywords', implode(', ', $query->highlight));
No problem

it is used wrongly 80% of the time

2018-06-15 22:51 UTC, carlitorweb commented
I have tested this item :white_check_mark: successfully on 32e23baacda3136ef0f09a64f1df84fbdaa5aeaf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20772">issues.joomla.org/tracker/joomla-cms/20772</a>.</sub>

2018-06-15 23:15 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 32e23baacda3136ef0f09a64f1df84fbdaa5aeaf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20772">issues.joomla.org/tracker/joomla-cms/20772</a>.</sub>

2018-06-15 23:15 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20772">issues.joomla.org/tracker/joomla-cms/20772</a>.</sub>

2018-06-16 00:48 UTC, merged

2018-06-16 01:02 UTC, brianteeman commented
If thabks