Add modules to location in new menu
joomla/joomla-cms pull request #21032
Opened 2018-07-10 09:45 UTC by wilsonge

Adds the menu items for the modules in the menu per the invision specification

2018-07-10 10:06 UTC, brianteeman requested changes

2018-07-10 10:06 UTC, brianteeman commented on administrator/language/en-GB/en-GB.mod_menu.ini
> +MOD_MENU_EXTENSIONS_MODULE_MANAGER_ADMINISTRATOR="Backend Modules"
we have always use site and administrator in the past

2018-07-10 10:06 UTC, brianteeman commented on administrator/components/com_menus/presets/joomla.xml
> +		/>
the tabs on this file are completely off - not just this edit

2018-07-10 10:47 UTC, wilsonge commented on administrator/components/com_menus/presets/joomla.xml
> +		/>
Agreed. Let’s fix in a future PR in one go? This is consistent with test of the file

2018-07-10 23:40 UTC, wilsonge commented on administrator/language/en-GB/en-GB.mod_menu.ini
> +MOD_MENU_EXTENSIONS_MODULE_MANAGER_ADMINISTRATOR="Backend Modules"
i was staying to the designs - but you're right should be done all at once if we're going to

2018-07-11 00:21 UTC, brianteeman commented on administrator/language/en-GB/en-GB.mod_menu.ini
> +MOD_MENU_EXTENSIONS_MODULE_MANAGER_ADMINISTRATOR="Backend Modules"
I am always right - when will you learn that - it will save you so much time

2018-07-11 06:02 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 43077dabb487bcd297c8b5733056ba2a26aba03a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21032">issues.joomla.org/tracker/joomla-cms/21032</a>.</sub>

2018-07-11 06:44 UTC, franz-wohlkoenig commented
Changed Title so ist clear its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21032">issues.joomla.org/tracker/joomla-cms/21032</a>.</sub>

2018-07-11 12:21 UTC, brianteeman approved these changes

2018-07-12 19:21 UTC, merged