Fixed users router 3.x
joomla/joomla-cms pull request #21274
Opened 2018-07-27 16:07 UTC by alexandraciobica

### Summary of Changes
Added checks for the layout in the com_users router because at the moment the router returns the first menu item that has the view that we are searching for, not taking into consideration the layout.

### Testing Instructions

1. Create a menu item for "User profile", another one for "Edit user profile"
2. From "User profile" click "Edit Profile" button, which is redirecting to the edit profile view, having the correct url. (The url was `/alias-of-menu-item/profile?layout=edit`, now it is only `/alias-of-menu-item`)
3. From "edit user profile" click cancel button. Before these changes it redirected to the same page, now it goes to the "user profile" page.

2018-07-31 05:25 UTC, franz-wohlkoenig commented
I have tested this item :red_circle: unsuccessfully on 4d0e9f66e732fed7310d100b2510837d05facca5<br /><br />Patch installed got at click "Edit Profile" button:
`The requested URL /<br /><b>Notice</b>: Undefined index: layout in <b>/url-of-host/components/com_users/helpers/legacyrouter.php</b> on line <b>127</b><br />/index.php/en/user-profile was not found on this server.`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21274">issues.joomla.org/tracker/joomla-cms/21274</a>.</sub>

2018-08-06 11:31 UTC, laoneo commented
@Hackwar can you please review this pr. Thanks.

2018-08-06 19:00 UTC, Hackwar requested changes
I generally don't like modifying the legacyrouters, since the correct answer to an issue with routing should be "use the new router" and not to mess around with this horrible mess that is the legacyrouter. But if you want to modify this, then please see my comments in this review.

2018-08-06 19:00 UTC, Hackwar commented on components/com_users/helpers/legacyrouter.php
> +					{
better use ```!isset()``` instead of comparing to null here.

2018-08-06 19:00 UTC, Hackwar commented on components/com_users/helpers/legacyrouter.php
> +			{
I doubt that we will ever want the edit profile layout to be a default item here. This can be dropped.

2018-08-06 19:00 UTC, Hackwar commented on components/com_users/helpers/legacyrouter.php
> +					$query['Itemid'] = $profile ? $profile : $default;
You have to check if the layout is set and if the layout is ```'edit'``` here and then assign the ```$profileEdit```, else the $profile. The layout can be unset in both cases then. For consistency sake it would be nice to put both ```unset()``` at the bottom of this ```case```.

2018-08-06 19:00 UTC, Hackwar commented on components/com_users/helpers/legacyrouter.php
> +					if ($query['Itemid'] = $profileEdit)
This could be removed, but for the future: You are missing a second = here to not make this an assignment. Right now ever time this gets replaced by $profileEdit.

2018-08-06 19:00 UTC, Hackwar commented on components/com_users/helpers/legacyrouter.php
> +						$profile = $item->id;
Not every site has a profile edit menu item, so you would have to check if $profileEdit is already set and if not, prefill it with $profile.
You also have to declare ```static $profileEdit;``` at the top. That is currently still missing and thus everything that you assign to this, gets lost at the end of the call.

2018-11-16 20:04 UTC, BertaOctech commented
I have tested this item :red_circle: unsuccessfully on 4d0e9f66e732fed7310d100b2510837d05facca5<br /><br />Before installing the patch, 
at user profile url was: 
index.php/user-profile/profile
we clicked edit profile, and on cancel we went back to
index.php/your-profile/profile

When I applied the test, I received the following warnings:
At http://localhost/demo_patches/index.php/edit-user-profile
Notice: Undefined index: layout in components/com_users/helpers/legacyrouter.php on line 131

At http://localhost/demo_patches/index.php/user-profile
 Notice: Undefined index: layout in components/com_users/helpers/legacyrouter.php on line <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21274">issues.joomla.org/tracker/joomla-cms/21274</a>.</sub>

2019-04-28 10:21 UTC, franz-wohlkoenig commented
@alexandraciobica whats the State of this Pull Request?

2019-05-12 06:38 UTC, franz-wohlkoenig commented
I suggest to close this PR due the lack of response by @alexandraciobica. In the meantime i add the label "needs new owner".

2019-05-12 07:03 UTC, infograf768 commented
Closing. Can be reopened if judged necessary.

2019-05-12 07:03 UTC, closed without merging