[4.0] Remove Exception-catching from JMail
joomla/joomla-cms pull request #21320
Opened 2018-07-31 07:51 UTC by jonasgonka

### Summary of Changes
Remove the internal handling of exceptions thrown by the PHPMailer API in JMail based on PR #12179. 

All the proposed changes in that PR were implemented, furthermore we added Exception Handling in the places that use the methods of the JMail class.

### Testing Instructions
Mail sending should still work as intended, and with exceptions turned off all booleans should be handled normally as well.

With exceptions turned on all mail functions should now show appropriate warning messages and/or execute expected error behaviour.

Functionalities updated:
- Notification Email for a direct message
- Admin Mass-Mail
- Joomla! update notification mail (could not be tested)
- Sending a mail through the Contact Form
- Registration Email after a user is created in the backend
- Mailto function of articles (this will not show an error anymore, but will just remain on the sending form, might require more work)
- Remind/Reset emails for the username and password

### Documentation Changes Required
Error handling and throwing behaviour changed.

2018-07-31 07:58 UTC, brianteeman requested changes

2018-07-31 07:58 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_messages.ini
> +COM_MESSAGES_ERROR_MAIL_FAILED="The email message could not be sent."
Can you simplify this to just
"The email could not be sent."

Thanks

2018-07-31 08:07 UTC, brianteeman approved these changes
approve language change

2018-07-31 08:29 UTC, wilsonge approved these changes
Very quick code review looks good to me

2018-08-08 16:14 UTC, merged

2018-08-08 16:14 UTC, wilsonge commented
Awesome. Thanks very much for this!