[New Feature] Multilingual: Propagating existing associations if desired
joomla/joomla-cms pull request #21321
Opened 2018-07-31 09:37 UTC by infograf768

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/21250

### Summary of Changes
This adds a "Propagate" button in the Associations tab when editing a contact, category, article, menu item, newsfeed.
This button will display when an association is selected in a Content Language field, offering the option to Propagate the associations defined for that item to the other Content Languages.

The button will display ONLY when there are more than 2 Content Languages defined for the site.
A message will display with the results obtained.

It is B/C as it will not break anything and one is totally free to choose or not to use the button, thus keeping the possibility to Clear/Select/Create any associations as before.

Using it prevents breaking existing associations when the wrong items are chosen for some fields.

A big thank you to **Robbie Jackson** for the long work to get this new functionality.
Target Milestone: 3.9.0

### Testing Instructions
Create a Multilingual site with 3 or more languages.
Create items in each type: (contact, category, article, menu item, newsfeed) for 2 of these languages and associate them in each case.

Create a new item for each type, select another language than the ones which are already associated.
Save (NOT save and close) this item.
Display the Association tab.

You will see, as usual (here for 4 Content Languages)

<img width="929" alt="screen shot 2018-07-31 at 11 13 04" src="https://user-images.githubusercontent.com/869724/43450317-c48878ea-94b2-11e8-8e4c-5909de16d42e.png">

I do have already associations set for English and French.

I select for English the item which I know is associated.

The button displays (Better tip welcome)

<img width="741" alt="screen shot 2018-07-31 at 11 17 17" src="https://user-images.githubusercontent.com/869724/43450583-52b65e70-94b3-11e8-8f87-1f29fe47479b.png">

Clicking on the button will give

<img width="908" alt="screen shot 2018-07-31 at 11 18 22" src="https://user-images.githubusercontent.com/869724/43450653-773d0258-94b3-11e8-8940-deae7bacc484.png">

Result: the already associated category in French is added in the French field.
As we have no association set for Spanish, the field remains empty.
The message displays (it is the same in all cases except if there is an Ajax error)
`All existing associations have been set. If some are missing you may have to select or create them manually.`

If we have already associated all fields, clicking on Propagate will just display the message.

If we change an association in one of the fields and click Propagate, it is the associations from that language item that will be propagated and therefore replace the ones existing.

### Documentation Changes Required
Yes

2018-07-31 09:41 UTC, infograf768 commented
the json files need corrections for cs. Can be tested and commented nevertheless. ;)

2018-07-31 09:44 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_TIP="Propagates this selected item existing associations."
Please correct to

"Propagates this item's existing associations."

2018-07-31 09:46 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE="All existing associations have been set. If some are missing you may have to select or create them manually."
How likely is it that an association will be missing? Seems odd to me to have that on a success message.

2018-07-31 09:46 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_FAILED="Failed propagating associations. You may have to select or create them manually."
Shouldn't this be "will" not "may"?

2018-07-31 09:50 UTC, infograf768 commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE="All existing associations have been set. If some are missing you may have to select or create them manually."
It will happen when there is no item associated in a specific language. See image above where there is nothing for Spanish

2018-07-31 09:52 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE="All existing associations have been set. If some are missing you may have to select or create them manually."
so in that case nothing is missing as it doesnt exist
The first sentence is more than enough

2018-07-31 09:53 UTC, infograf768 commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_FAILED="Failed propagating associations. You may have to select or create them manually."
Some one may not want to create associations for a specific language.
`If desired, you will have to select or create them manually.`

2018-07-31 09:59 UTC, infograf768 commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE="All existing associations have been set. If some are missing you may have to select or create them manually."
This message is also informing the user that an association for one or more language(s) is missing. It may be what the user wants but it also may not be.
In that case the user can select an item or create one directly in this interface.
This is important.

2018-07-31 10:06 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_FAILED="Failed propagating associations. You may have to select or create them manually."
then they havent failed and this isnt a failure message

2018-07-31 10:06 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE="All existing associations have been set. If some are missing you may have to select or create them manually."
thats not the role of a success message.

2018-07-31 10:08 UTC, infograf768 commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE="All existing associations have been set. If some are missing you may have to select or create them manually."
It is only a success message for what could be propagated.

2018-07-31 10:12 UTC, infograf768 commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_FAILED="Failed propagating associations. You may have to select or create them manually."
Propagate has failed (for an unknown reason. It may be the case for a 3rd party component which is badly coded). It does not mean the user lost the possibility to associate items by selecting/creating them.

I am now waiting for tests. Thank you.

2018-07-31 10:32 UTC, brianteeman commented
Testing this and my only issue is with the messages
The propagate button says
"Propagate this items existing associations"

But you always get this message
> All existing associations have been set. If some are missing you may have to select or create them manually.

The code should check to see if there any associations to propagate and if not then the message should be
"No associations exist to propagate"
And if there are associations to propagate then the message should be
"All existing associations have been set."

2018-07-31 14:37 UTC, infograf768 commented
We will now get 3 types of messages:
JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE_ALL="All existing associations have been set."
JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE_NONE="No associations exist to propagate."
JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE_SOME="Some associations have been set: %s"

JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE_SOME will also display the language where associations have been added.

Example. Here I selected an article for English. It added the French existing association, but as the Spanish one did not exist, it is that message which is used displaying which association was set.
<img width="917" alt="screen shot 2018-07-31 at 16 34 41" src="https://user-images.githubusercontent.com/869724/43466370-abaf5230-94df-11e8-8b64-f967690b69d4.png">

2018-07-31 14:40 UTC, infograf768 commented
Restarted drone who failed on js.

2018-07-31 15:17 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_MESSAGE_SOME="Some associations have been set: %s"
Please change to 
Associations have been set for: %s

2018-07-31 15:18 UTC, brianteeman commented
Much better now. 

I am also getting a missing string JGLOBAL_ASSOCIATIONS_PROPAGATE_TIP

2018-07-31 15:31 UTC, infograf768 commented
done

2018-07-31 15:39 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_PROPAGATE_FAILED="Failed propagating associations. You may have to select or create them manually."
ok change to your suggestion of "If desired, you will have to select or create them manually.

2018-08-01 03:14 UTC, jreys commented
I have tested this item :white_check_mark: successfully on eabc256e01ab0b784a8e101b6a2e8fb05b5e2eb3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21321">issues.joomla.org/tracker/joomla-cms/21321</a>.</sub>

2018-08-01 04:19 UTC, infograf768 commented
One more tester.

2018-08-01 04:27 UTC, Quy commented on administrator/components/com_categories/controllers/ajax.json.php
> +			$message = null;
Remove. Not necessary as it will be assigned later in the if statement.

2018-08-01 04:30 UTC, infograf768 commented on administrator/components/com_categories/controllers/ajax.json.php
> +			$message = null;
Waiting for other comments from you before changing. 👍

2018-08-01 04:38 UTC, Quy commented on administrator/components/com_categories/controllers/ajax.json.php
> +			$message = null;
Repeat this change in the other files.

2018-08-01 04:38 UTC, Quy commented on administrator/components/com_newsfeeds/models/fields/modal/newsfeed.php
> +		// Propagate contact button
Update comment.

2018-08-01 05:59 UTC, infograf768 commented
@Quy 
All done. Thanks.

2018-08-01 14:11 UTC, infograf768 commented
@Quy @franz-wohlkoenig @brianteeman 
Please add your tests.

2018-08-01 14:23 UTC, ghost commented
@infograf768 have read Instructions a few Times but didn't understand really what is to test. So i need Time.

2018-08-02 06:25 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on b902d37eacec211d9b2621241bdf7b8f842d1296<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21321">issues.joomla.org/tracker/joomla-cms/21321</a>.</sub>

2018-08-02 06:25 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-08-02 06:26 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-08-02 07:52 UTC, infograf768 commented
@mbabker 
I have tagged this to 3.9. Can you merge?

2018-08-02 12:16 UTC, mbabker commented on administrator/components/com_categories/views/category/tmpl/edit.php
> +		<?php echo '<input id="token" type="hidden" name="' . JSession::getFormToken() . '" value="1" />'; ?>
This line shouldn't be necessary, this is exactly what the JHtml call immediately below does.

2018-08-02 12:16 UTC, mbabker commented on administrator/components/com_contact/views/contact/tmpl/edit.php
> +	<?php echo '<input id="token" type="hidden" name="' . JSession::getFormToken() . '" value="1" />'; ?>
Same as above.

2018-08-02 12:16 UTC, mbabker commented on administrator/components/com_content/views/article/tmpl/edit.php
> +		<?php echo '<input id="token" type="hidden" name="' . JSession::getFormToken() . '" value="1" />'; ?>
Same as above.

2018-08-02 12:17 UTC, mbabker commented on administrator/components/com_menus/views/item/tmpl/edit.php
> +	<?php echo '<input id="token" type="hidden" name="' . JSession::getFormToken() . '" value="1" />'; ?>
Same as above.

2018-08-02 12:17 UTC, mbabker commented on administrator/components/com_newsfeeds/views/newsfeed/tmpl/edit.php
> +	<?php echo '<input id="token" type="hidden" name="' . JSession::getFormToken() . '" value="1" />'; ?>
Same as above.

2018-08-02 12:20 UTC, mbabker commented on media/system/js/associations-edit-uncompressed.js
> +		var token = jQuery("#token").attr("name");
Instead of finding the token in this way, the API added in https://github.com/joomla/joomla-cms/pull/14952 should be used instead.

2018-08-02 12:38 UTC, infograf768 commented on media/system/js/associations-edit-uncompressed.js
> +		var token = jQuery("#token").attr("name");
You mean using
`var token = jQuery('meta[name=csrf-token]').val();` instead?

2018-08-02 12:43 UTC, infograf768 commented on media/system/js/associations-edit-uncompressed.js
> +		var token = jQuery("#token").attr("name");
hmm, that does not work

2018-08-02 12:46 UTC, mbabker commented on media/system/js/associations-edit-uncompressed.js
> +		var token = jQuery("#token").attr("name");
In the layouts, you have to add a `JHtml::_('jquery.token');` call, then you don't even need to find the token and manually include it when using jQuery.ajax because that PHP call will set up jQuery to include the token automatically.

2018-08-02 12:49 UTC, infograf768 commented on media/system/js/associations-edit-uncompressed.js
> +		var token = jQuery("#token").attr("name");
This works.
var token = Joomla.getOptions('csrf.token', '');

Is that OK, @mbabker ?

2018-08-02 12:50 UTC, mbabker commented on media/system/js/associations-edit-uncompressed.js
> +		var token = jQuery("#token").attr("name");
Yes.

2018-08-02 13:02 UTC, infograf768 commented on media/system/js/associations-edit-uncompressed.js
> +		var token = jQuery("#token").attr("name");
I did not add the JHtml::_('jquery.token');
Just deleted the extraneous lines in the edit.php and used 
var token = Joomla.getOptions('csrf.token', '');

As I did not know what would be the consequences 

Can we go with that?

2018-08-02 13:21 UTC, infograf768 commented
@mbabker 
Do we need new tests?

2018-08-02 14:36 UTC, dgrammatiko requested changes

2018-08-02 14:36 UTC, dgrammatiko commented on media/system/js/associations-edit-uncompressed.js
> +	window.injectAssociations = function(result, callbackFunctionPrefix)
This is really bad. Please name this as `Joomla.injectAssociations`. Global variables, functions etc are as bad in Javascipt as they are in PHP 👎

2018-08-02 16:43 UTC, infograf768 commented on media/system/js/associations-edit-uncompressed.js
> +	window.injectAssociations = function(result, callbackFunctionPrefix)
I guess Robbie used this as we have above existing
window.hideAssociation
and 
window.showAssociationMessage

2018-08-02 16:52 UTC, infograf768 commented on media/system/js/associations-edit-uncompressed.js
> +	window.injectAssociations = function(result, callbackFunctionPrefix)
I guess I found what has to be modifed to fit as both the functions use window.
It is not the purpose of this patch to also correct the existing ones.

2018-08-02 16:55 UTC, infograf768 commented on media/system/js/associations-edit-uncompressed.js
> +	window.injectAssociations = function(result, callbackFunctionPrefix)
@dgrammatiko 
Do you agree with my statement?
If yes, I will do the patch right now

2018-08-03 08:06 UTC, infograf768 commented
@dgrammatiko 
Modified the new js functions name as required.
We can't obviously normalize the others as it would not be B/C.


@franz-wohlkoenig @jreys 
Please test again. :)

2018-08-04 10:12 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 888a2807aeb4373cbab7c1464e035df3df7ce8dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21321">issues.joomla.org/tracker/joomla-cms/21321</a>.</sub>

2018-08-04 14:18 UTC, infograf768 commented
@mbabker Can you now merge?

2018-08-04 15:29 UTC, merged

2018-08-04 15:33 UTC, infograf768 commented
@mbabker 
As it is a new feature, shall not it be merged in 3.9.0 ?

2018-08-04 15:33 UTC, mbabker commented
💩

2018-08-04 15:40 UTC, mbabker commented
Branch merged to 3.9-dev via https://github.com/joomla/joomla-cms/commit/11153f720bad7886e990c3b3af5bbf4ca4cf4c00

2018-08-04 15:40 UTC, infograf768 commented
Thanks.