[4.0] Smart Search: Adding nested taxonomy (POC)
joomla/joomla-cms pull request #21327
Opened 2018-07-31 14:08 UTC by Hackwar

The taxonomy in Smart Search is not bad, but it has issues. One of these issues is, that the hierarchy of the taxonomy entries is lost when indexing. All entries in the taxonomy are stored as a flat list, which isn't really that good for stuff like categories. This PR implements nested taxonomies.

#### This is a proof of concept and is here to have a discussion about this proposal. Do not merge this yet!!

Simply said, I've changed the taxonomy table to a nested set and added new methods to insert nested nodes. For this, there is a new NodeInterface. Classes that implement this, allow us to traverse the tree and thus automatically add parent categories.

2019-01-09 23:06 UTC, Hackwar commented
Right now this depends on #23452 being merged first.

2019-02-17 20:30 UTC, HLeithner requested changes

2019-02-17 20:30 UTC, HLeithner commented on administrator/components/com_finder/helpers/indexer/driver/mysql.php
> +			$db->setQuery('ALTER TABLE ' . $db->quoteName('#__finder_tokens') . ' ENGINE = INNODB');
Comment is wrong

2019-02-17 20:30 UTC, HLeithner commented on administrator/components/com_finder/helpers/indexer/driver/mysql.php
> +			$db->setQuery('ALTER TABLE ' . $db->quoteName('#__finder_tokens_aggregate') . ' ENGINE = INNODB');
Comment is wrong

2019-02-17 20:30 UTC, HLeithner commented on administrator/components/com_finder/tmpl/maps/default.php
> +								/**if (trim($item->parent_title, '**') === 'Language')
Is this needed in the future or whats the reason for commenting it out?

2019-02-17 20:30 UTC, HLeithner commented on plugins/finder/contacts/contacts.php
> +		$categories = jcategories::getInstance('com_contact');
```suggestion
		$categories = JCategories::getInstance('com_contact');
```

2019-02-17 20:30 UTC, HLeithner commented on plugins/finder/content/content.php
> +		$categories = jcategories::getInstance('com_content');
```suggestion
		$categories = JCategories::getInstance('com_content');
```

2019-02-17 20:30 UTC, HLeithner commented on plugins/finder/newsfeeds/newsfeeds.php
> +		$categories = jcategories::getInstance('com_newsfeeds');
```suggestion
		$categories = JCategories::getInstance('com_newsfeeds');
```

2019-02-17 21:17 UTC, HLeithner commented
On index or saving a article I get a fatal error:
```
Fatal error: Cannot use Joomla\CMS\Tree\NodeInterface as NodeInterface because the name is already in use in libraries/src/Categories/CategoryNode.php on line 18
```

2019-02-20 08:24 UTC, Hackwar commented on administrator/components/com_finder/tmpl/maps/default.php
> +								/**if (trim($item->parent_title, '**') === 'Language')
Sorry, fixed that one.

2019-02-20 08:55 UTC, Hackwar commented
I've made all requested changes. Should be good to go. I can't see that the failing system test is related to this.

2019-02-20 11:15 UTC, HLeithner approved these changes

2019-02-28 12:30 UTC, merged

2019-02-28 12:30 UTC, wilsonge commented
Looks like an improvement to me! Thanks!

2019-02-28 13:28 UTC, Hackwar commented
:dancer: :champagne: Thank you!