GSoC 2018 Enhance Users Project
joomla/joomla-cms pull request #21441
Opened 2018-08-07 10:27 UTC by alexandraciobica

### Summary of Changes
All the changes regard the users component.

Site:
 - Added two new views:
   - A view named `users` with a list of users in a user group taking into consideration access levels when displaying 
   - A view named `user` that displays the details of a chosen user, including a contact form similar to the one from contact component.
- Changed the router so that it displays the links for these pages correctly

Admin:
- Added `Access` field to the users list - the value can be changed from `Users: Edit` > `Account Details` tab or using batch processing
- Added Contact form to the user - the options can be changed from `Users: Edit` or global options > `Form` tab
- Created two new menu item types: 
   - one that displays a list of users based on groups
   - one that displays the details view of the selected user

### Testing Instructions

I wrote this JDocs article and I think it explains pretty well how to test everything. https://docs.joomla.org/J4.x:Users_List_and_Details_Views

Mentors: @bembelimen and @laoneo

2018-08-07 13:13 UTC, brianteeman commented
(updated title to show it is for 4.0)

2018-08-07 13:20 UTC, brianteeman requested changes

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +		>
indent one tab

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +		>
indent one tab

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +		>
indent one tab

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +			label="COM_USERS_FIELD_CONFIG_SESSION_CHECK_LABEL"
move label above class

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +		>
indent one tab

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +			label="COM_USERS_CONFIG_FIELD_CUSTOM_REPLY_LABEL"
move label above class

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +		>
indent one tab

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/forms/user.xml
> +					name="show_email_form"
you need to check the tabs on all of this file and consider the previous comments about codestyle

2018-08-07 13:20 UTC, brianteeman commented on administrator/components/com_users/tmpl/users/default.php
> +                                <td class="small d-none d-md-table-cell text-center">
please indent to match the surrounding code

2018-08-07 13:20 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_CONFIG_FIELD_INDIVIDUAL_CONTACT_DESC="These settings apply for single User unless they are changed for a specific User."
That doesn't make sense - /me confused

2018-08-07 13:20 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_users.sys.ini
> +COM_USERS_USER_DETAILS_VIEW_DEFAULT_DESC="Displays the details of the chosen user"
please add a . at the end - all descriptions should be sentences

2018-08-07 14:15 UTC, TobsBobs commented
If this is ready for testing, please give a hint.

2018-08-08 00:18 UTC, Quy commented on administrator/components/com_users/config.xml
> +			class="switcher"
Per [Joomla Coding Standards](https://developer.joomla.org/coding-standards/xml.html):

> The four attributes `name`, `type`, `label` and `description` should be written in this order and at the top of the element definition.

2018-08-08 00:19 UTC, Quy commented on components/com_users/View/User/HtmlView.php
> +
Remove blank line.

2018-08-08 17:17 UTC, Quy commented on administrator/components/com_users/forms/user.xml
> +
Remove blank line.

2018-08-08 17:19 UTC, Quy commented on components/com_users/Controller/UserController.php
> +			$contact_user      = User::getInstance($contact->id);
Align `=`

2018-08-08 17:19 UTC, Quy commented on components/com_users/Model/UserModel.php
> +
Remove blank line

2018-08-08 17:19 UTC, Quy commented on components/com_users/Model/UserModel.php
> +
Remove blank line

2018-08-08 17:21 UTC, Quy commented on components/com_users/layouts/field/render.php
> +	return;
Add blank line above

2018-08-08 17:21 UTC, Quy commented on components/com_users/router.php
> +
Remove blank line

2018-08-08 17:22 UTC, Quy commented on components/com_users/tmpl/users/default.xml
> +			>
Indent

2018-08-08 17:41 UTC, alexandraciobica commented on administrator/components/com_users/tmpl/users/default.php
> +                                <td class="small d-none d-md-table-cell text-center">
This is aligned correctly in my editor, I don't know why here is not..

2018-08-08 17:42 UTC, mbabker commented on administrator/components/com_users/tmpl/users/default.php
> +                                <td class="small d-none d-md-table-cell text-center">
You're using spaces for indents, the rest of the file is using tabs.

2018-08-08 21:43 UTC, brianteeman commented
I am confused by the objectives of this new access column 

- what is the problem that is being solved
- what can I do now I couldn't do before
- what happens with existing users. the column is blank for them
- our access and viewlevels are confusing enough atm and I "think" this makes it worse - for example I can create a new user in the admin and select the access as super users. But that is not the same as changing their group to Super users
<img width="601" alt="chrome_2018-08-08_22-43-14" src="https://user-images.githubusercontent.com/1296369/43866077-7b82c384-9b5c-11e8-858e-c8cfff80c4b1.png">

2018-08-08 21:47 UTC, brianteeman commented
### contact form 

Isn't this duplicating the functionality already possible with the user - contact creator plugin?

2018-08-08 21:51 UTC, brianteeman commented
New menu items

I couldnt test this as the two options were not present in the list of available menu types that can be created

2018-08-09 05:11 UTC, laoneo commented
The goal of this project was to provide front end menu list items for users and a detail page. This solves tow issues:

- The long outstanding problem that the user menu item is not working on the front end
- That we can decouple com_contact as you need com_contact to show a list of users on the front end.

The access flag is a security measure that the admin can define who can see the user on the front end. I was the driver behind that flag and not to have just a yes no button if the user details should be available on the front or not.

2018-08-09 06:18 UTC, SharkyKZ commented
>The access flag is a security measure that the admin can define who can see the user on the front end.

Per-user setting should be set by the user in user profile. Admin could set the global setting in `com_users` to allow/disallow frontend profile viewing. Need to think about this from user perspective too.

2018-08-09 08:44 UTC, brianteeman commented
> The goal of this project was to provide front end menu list items for users and a detail page. 

Why? There are many extensions for that. Is it really something that the majority of websites would want? If not then it doesnt belong in the core

> That we can decouple com_contact as you need com_contact to show a list of users on the front end.

If you need a list at all - see above.. And as I stated this is duplicating functionality available with the contact creator plugin which allows much more advanced use. 

> The access flag is a security measure that the admin can define who can see the user on the front end. I was the driver behind that flag and not to have just a yes no button if the user details should be available on the front or not.

That is completely unclear from the UI. I read it as what is the access of this user. Again completely unnecessary to add to all users when the contacts can be used for this

Sorry but this makes no sense to me at all for a core contribution. It's not about the code but about should it be in the core

2018-08-09 09:27 UTC, laoneo commented
> Is it really something that the majority of websites would want?

Nobody can answer that, not even you.

> And as I stated this is duplicating functionality available with the contact creator plugin

The creator plugin creates a contact when a user is created and has nothing to do with the contact form. Means we have even more bloat, as you have then a contact per user.
I was talking with several people before GsoC started about that project and the contact form is a feature some do need. So the student duplicated that functionality. But this is only till the decoupling is finished.

As I said the overall goal is to be able to decouple com_contact. With custom fields in combination with the user component, this is possible now. Most maintainers do agree that we should slim down the core so this is a step into that direction. If you want to have a contact extension then take one from JED and not the opposite.

2018-08-09 10:07 UTC, brianteeman commented
>> Is it really something that the majority of websites would want?

> Nobody can answer that, not even you.

So go to the joomla showcase site and show me how many sites have a user list and then compare that to how many have a contact list

This is not slimming down the core it is bloating it. Sorry not wasting my words on this any more. It is a useless feature that doesnt belong in core.

2018-08-09 12:36 UTC, mbabker commented
Tend to agree here.  Having a core frontend user profile view IMO is a nice to have capability, but I don't think it needs to come with all the extra stuff being proposed here, especially the bits related to access that just adds even more confusing things to an already confusing management interface.

2018-08-11 17:01 UTC, rdeutz commented
I am sorry but I also don't see this as a needed addition to the core package

2018-08-17 07:58 UTC, laoneo commented
PD (PLT) accepted these projects so I don't see a reason why we are discussing again if this should get into core or not. What we can discus here if the code is correct and all the features are implemented the right way.

@mbabker we went with access levels basically because of security reasons. Like that an admin or the user has then to actively activate a user for front end listing.

2018-08-17 08:12 UTC, brianteeman commented
Sorry but just because a project was chosen shouldn't mean we have to merge the resultant code. That's never been the case before. Surely as a developer you understand that what might appear to be a good idea on paper isn't necessarily a good idea on practice.

2018-08-17 08:21 UTC, ghost commented
@brianteeman that Decision should be made before chose Project.

2018-08-17 08:23 UTC, brianteeman commented
Gsoc is about introducing students to open source.

2018-08-17 08:32 UTC, laoneo commented
This is only part of GsoC. It should also help the open source projects. If we would do something which will not get accepted in core, then there is no reason to ever start that project. It is a big amount of time the student and the mentors do put into that project. And when it gets trashed at the end then it leads to big frustrations. The GsoC admins learned from the past and did put the proposals into Production for voting, that we can add something valuable to the core and not just waste time and energy.

2018-08-17 09:33 UTC, ggppdk commented
This 
unlike other already merge features

1. does not break anything (or at least any breaks / bugs should be easy to fix)
2. does little to complicate common website tasks / UI
3. does little to hurt or compete with 3rd party (i mean 'social' extensions) even if one would create a layout overrides to add more stuff to it, still it will not compete with them ... much
4. will be easy to maintain

Not accepting also considering the above points, is a bad message as @laneo said

I understand the only argument against this (which i admit is a good argument) is that it will be uncommonly useful 
if so the project should not have started at all

I mean the reason for rejecting this was "known" before the project started,
unlike reasons 1, 2, 4 that may have risen after the project completed

2018-08-17 09:52 UTC, brianteeman commented
> A view named users with a list of users in a user group taking into consideration access levels when displaying

I do not see any menu type for this so cannot test

> A view named user that displays the details of a chosen user, including a contact form similar to the one from contact component.

The form is not available until you go into com-users options and save 

The view will not display until you go into com_users user and save every user so that the access field is created. Otherwise you have access denied


The form has no language strings 
<img width="455" alt="chrome_2018-08-17_10-46-57" src="https://user-images.githubusercontent.com/1296369/44260011-19715d80-a20b-11e8-8050-8e42f7f89987.png">

2018-08-17 10:07 UTC, franz-wohlkoenig commented
Applying PR got:

![screen shot 2018-08-17 at 12 06 56](https://user-images.githubusercontent.com/8235763/44260884-26e01500-a216-11e8-80b2-1ae936ada365.jpg)

2018-08-17 11:58 UTC, mbabker commented
> he GsoC admins learned from the past and did put the proposals into Production for voting, that we can add something valuable to the core and not just waste time and energy.

Just because the project proposal was accepted (which at the time was nothing more than a couple paragraph abstract at best) does NOT mean that the resultant code MUST be accepted.  The end result should be evaluated the same as every pull request and not forced through simply because it has the GSoC label on it.

2018-08-17 12:06 UTC, brianteeman commented
And if you could please evaluate the comments about the code and make it work so it can be tested then it would obviously help your case to get this accepted. Right now as I have written twice before there is NO code to display the user list

2018-10-15 12:22 UTC, brianteeman commented
Sorry but I am closing this. There has been no response to requests to at least get it into a testable state

2018-10-15 12:22 UTC, closed without merging

2018-10-15 12:26 UTC, laoneo commented
The student promised to have a look. Perhaps she needs some more time.

2018-10-15 12:28 UTC, brianteeman commented
It can always be re-opened if that ever happens