[4.0] [GSoC 2018] CLI Update Project
joomla/joomla-cms pull request #21452
Opened 2018-08-07 17:23 UTC by bosunski

### Summary of Changes
Added Commands for:
- Checking Updates
- Installing Extension
- Removing Extension
- Listing Extensions with type specification
- Updating Joomla! core
- Installing Joomla! from config file and in an interactive CLI mode
- Setting Configurations with setting multiple Configuration support
- Listing Configurations (includes listing configurations as a group)
- Setting website to offline
- Bringing website online

### Testing Instructions
All testing instruction can be found in the documentation [here](https://docs.joomla.org/J4.x:CLI_Update)

### Documentation
JDocs for this PR is [here](https://docs.joomla.org/J4.x:CLI_Update), It explains everything on how to use the commands
Project Repository is [here](https://github.com/joomla-projects/gsoc18_cli_update/pull/12)
### Mentors
@HLeithner @alikon @marcodings @rjcf18

2018-08-07 17:51 UTC, brianteeman commented on installation/src/Form/Field/Installation/PrefixField.php
> +		if ($size > 10)
Don't know if it really matters but in the web installer the prefix limit is 15 including the closing_

2018-08-07 17:53 UTC, brianteeman commented on libraries/src/Application/ConsoleApplication.php
> +	 * Returns the installed language files in the administrative and frontend area.
Returns the installed language files 
==>
Returns the installed languages

2018-08-07 17:54 UTC, brianteeman commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			$symfonyStyle->warning('We cannot find an update URL ');
remove extra space after URL

2018-08-07 17:57 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +			$this->ioStyle->warning('Some PHP options are not right. Consider making sure all these are OK before proceeding.');
This is the string we use in the web installer. I think its for the same thing
These settings are recommended for PHP to ensure full compatibility with Joomla.

2018-08-07 18:02 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +				Text::sprintf('Cannot connect to database, verify that you specified the correct database details', null),
again in the web installer we use a different string. at a minimum please include the mysql8 part

"Check your database credentials, database type, database name or hostname. If you have MySQL 8 installed then please read https://docs.joomla.org/Joomla_and_MySQL_8#Workaround_to_get_Joomla_working_with_MySQL_8 for more information."

2018-08-07 18:04 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +	 * Handles uninteractive installation
uninteractive is not an english word
usually it would be non-interactive

2018-08-07 18:05 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +			$this->getApplication()->enqueueMessage('Unable to locate file specified', 'error');
Unable to locate file specified
==>
Unable to locate the specified file.

2018-08-07 18:06 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +	 * @param   string  $file  Path fo ini file
Typo ==>
Path to ini file

2018-08-07 18:07 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +				'question'  => "Enter admin email",
To be consistent with later questions this should be Admin not admin

2018-08-07 18:08 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +				'question'  => "Enter Admin username",
change to lowercase admin to be consistent

2018-08-07 18:08 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +				'question'  => "Enter Admin username",
Okay. will update this

2018-08-07 18:08 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +	 * @param   string  $file  Path fo ini file
Oh! Okay

2018-08-07 18:09 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +	 * Handles uninteractive installation
Alright

2018-08-07 18:09 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +				'question'  => "What's your connection type",
==>Select your connection type
or if that's not appropriate
==> What's your connection type?

2018-08-07 18:09 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +				Text::sprintf('Cannot connect to database, verify that you specified the correct database details', null),
Alright

2018-08-07 18:10 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +				'question'      => "What do you want to do about old DB",
==> Remove or backup old database?

2018-08-07 18:10 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +			$this->ioStyle->warning('Some PHP options are not right. Consider making sure all these are OK before proceeding.');
Alright, will update this

2018-08-07 18:10 UTC, bosunski commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			$symfonyStyle->warning('We cannot find an update URL ');
Okay

2018-08-07 18:10 UTC, bosunski commented on libraries/src/Application/ConsoleApplication.php
> +	 * Returns the installed language files in the administrative and frontend area.
Okay

2018-08-07 18:10 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +				'default'   => 'https://joomla.org',
Not sure what url you wasnt to point to but obviously this isnt correct

2018-08-07 18:11 UTC, bosunski commented on installation/src/Form/Field/Installation/PrefixField.php
> +		if ($size > 10)
Hmm, i will look into that

2018-08-07 18:11 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +			'helpurl' => 'https://joomla.org',
see previous comment about the url

2018-08-07 18:12 UTC, brianteeman commented on libraries/src/Console/ExtensionInstallCommand.php
> +			'From where do you want to install? (path OR url)'
==> Where do you want to install from?

2018-08-07 18:13 UTC, brianteeman commented on libraries/src/Console/ExtensionRemoveCommand.php
> + * Console command for checking if there are pending extension updates
copy paste error?

2018-08-07 18:13 UTC, brianteeman commented on libraries/src/Console/ExtensionInstallCommand.php
> + * Console command for checking if there are pending extension updates
Copy paste error?

2018-08-07 18:14 UTC, brianteeman commented on libraries/src/Console/ExtensionsListCommand.php
> + * Console command for checking if there are pending extension updates
Copy paste error?

2018-08-07 18:14 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +				'question'  => "What's your connection type",
Okay

2018-08-07 18:15 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +				'question'      => "What do you want to do about old DB",
Okay

2018-08-07 18:15 UTC, brianteeman commented on libraries/src/Console/UpdateCoreCommand.php
> + * Console command for checking if there are pending extension updates
Copy paste error?

2018-08-07 18:16 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +				'default'   => 'https://joomla.org',
I've been trying to find a default help URL if there is one, I just placed that there as default.
Does joomla have any default in this case?

2018-08-07 18:16 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +			'helpurl' => 'https://joomla.org',
Okay

2018-08-07 18:16 UTC, bosunski commented on libraries/src/Console/ExtensionInstallCommand.php
> +			'From where do you want to install? (path OR url)'
Okay

2018-08-07 18:16 UTC, bosunski commented on libraries/src/Console/ExtensionRemoveCommand.php
> + * Console command for checking if there are pending extension updates
Correct!

2018-08-07 18:17 UTC, bosunski commented on libraries/src/Console/ExtensionInstallCommand.php
> + * Console command for checking if there are pending extension updates
Yes

2018-08-07 18:17 UTC, bosunski commented on libraries/src/Console/ExtensionsListCommand.php
> + * Console command for checking if there are pending extension updates
yes

2018-08-07 18:17 UTC, bosunski commented on libraries/src/Console/UpdateCoreCommand.php
> + * Console command for checking if there are pending extension updates
Yes

2018-08-07 18:19 UTC, brianteeman commented on libraries/src/Console/GetConfigurationCommand.php
> +	 * Handles the command when an single option is requested
typo
when a not when an

2018-08-07 18:26 UTC, brianteeman commented on libraries/src/Console/CoreInstallCommand.php
> +				'default'   => 'https://joomla.org',
I would use this for now
https://docs.joomla.org/Special:MyLanguage/J4.x:Installing_Joomla

2018-08-08 09:54 UTC, wilsonge commented on installation/src/Form/Field/Installation/PrefixField.php
> +		if ($size > 15)
Why has this been increased to 15 from the original 10?

2018-08-08 09:55 UTC, wilsonge commented on installation/src/Form/Field/Installation/PrefixField.php
> -		// Make sure somebody doesn't put in a too large prefix size value.
This check needs to be here instead of the `getPrefix` method - because if the prefix is in the session this check is going to be skipped

2018-08-08 09:57 UTC, brianteeman commented on installation/src/Form/Field/Installation/PrefixField.php
> +		if ($size > 15)
My fault ;)

The web installer is set at 15 so I suggested that both used the same value AND the same check used in the web installer for 15 is used in the libraries/src/Console/CoreInstallCommand.php

2018-08-08 09:58 UTC, wilsonge commented on libraries/src/Factory.php
> +		if (php_sapi_name() !== 'cli')
Why is this required. In the console application you should be using the RuntimeStorage https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Service/Provider/Session.php#L178 and therefore this should be ok

2018-08-08 11:54 UTC, mbabker commented on includes/framework.php
> -	if (file_exists(JPATH_INSTALLATION . '/index.php'))
This check is still required before registering the namespace and trying to do something.  For stable releases, the `installation` directory is removed from a site after Joomla has been installed.  Therefore, altering the behavior based on the active SAPI must still account for the production filesystem structure and issue appropriate warnings if not available.

2018-08-08 11:55 UTC, mbabker commented on installation/src/Model/DatabaseModel.php
> +			$db = $this->initialise();
The options should always be passed forward, we shouldn't be omitting parameters based on the active SAPI.

2018-08-08 11:57 UTC, mbabker commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$app = Factory::getApplication();
`$this->getApplication()`

2018-08-08 11:58 UTC, mbabker commented on libraries/src/Console/CoreInstallCommand.php
> +		}
There needs to be a check here ensuring the installation directory exists and exiting if not available.

2018-08-08 12:01 UTC, mbabker commented on libraries/src/Console/ExtensionInstallCommand.php
> +			exit(2);
Do not exit within commands, always return an exit code.

2018-08-08 12:03 UTC, HLeithner commented on libraries/src/Console/ExtensionInstallCommand.php
> +			exit(2);
In this case also convert the number to a constant

2018-08-08 16:31 UTC, bosunski commented on installation/src/Form/Field/Installation/PrefixField.php
> +		if ($size > 15)
hmmm, so should I go by the 10 or the 15?
Or we can just let it be the same with the web installer? @wilsonge

2018-08-08 18:38 UTC, rdeutz commented
1) Tests are no longer part of the main repository
2) You can remove them entirely, you are testing if help gives you output. When you write tests you should test functionality.

2018-08-09 01:20 UTC, bosunski commented
Tests removed from here @rdeutz , but where are they meant to go?

2018-08-09 01:20 UTC, bosunski commented on libraries/src/Console/ExtensionInstallCommand.php
> +			exit(2);
Okay

2018-08-09 01:20 UTC, bosunski commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$app = Factory::getApplication();
Okay

2018-08-09 03:11 UTC, bosunski commented on libraries/src/Factory.php
> +		if (php_sapi_name() !== 'cli')
Okay

2018-08-09 03:16 UTC, bosunski commented on installation/src/Model/DatabaseModel.php
> +			$db = $this->initialise();
I don't understand what you meant by "forward" @mbabker

2018-08-09 11:16 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +		}
Okay

2018-08-09 11:53 UTC, bosunski commented on libraries/src/Console/CoreInstallCommand.php
> +		}
Done

2018-08-09 12:07 UTC, mbabker commented on installation/src/Model/DatabaseModel.php
> +			$db = $this->initialise();
When not on the CLI SAPI, you aren't passing any parameters into this `initialise()` method.  When you are on the CLI SAPI, you are passing parameters into this `initialise()` method.  That's inconsistent for no good reason, the active SAPI shouldn't decide whether parameters are passed forward into another method.

2018-08-09 12:56 UTC, HLeithner commented
Please create or reuse a result constants
.
Maybe it would be better to define the constants (at least the generic one) in AbstractCommand.
for example:
```
class AbstractCommand {
  /**
   * Command executed successful
   */
  const RESULT_SUCCESS = 0:

  /**
   * Generic command error
   */
  const RESULT_ERROR = 1;

}
```

And define the command specific error to the command class starting with 2. Any opinions?

2018-08-09 13:04 UTC, bosunski commented
It's a good idea!

2018-08-12 15:48 UTC, bosunski commented
So, I attempted to implement the result constants inside `AbstractCommand`, I figured out that it's part of the Joomla framework, i.e a package installed inside `libraries/vendors/joomla/console/AbstractCommand.php`.
It's not on this repository.

2018-08-13 19:48 UTC, rdeutz commented
You shoudn't have a package-lock.json in your PR

2018-08-14 21:40 UTC, bosunski commented on installation/src/Model/DatabaseModel.php
> +			$db = $this->initialise();
Done

2018-08-15 11:20 UTC, bosunski commented on includes/framework.php
> -	if (file_exists(JPATH_INSTALLATION . '/index.php'))
I added [this](https://github.com/joomla/joomla-cms/pull/21452/commits/1605298f6d924c02203f5b0a6de27d203a4cbbf4) and also I have [this](https://github.com/joomla/joomla-cms/blob/1605298f6d924c02203f5b0a6de27d203a4cbbf4/libraries/src/Console/CoreInstallCommand.php#L173) check for the installation directory, I think that is already accounted for, if I'm correct? @mbabker

2018-08-15 11:27 UTC, bosunski commented on installation/src/Form/Field/Installation/PrefixField.php
> -		// Make sure somebody doesn't put in a too large prefix size value.
@wilsonge please check [this](https://github.com/joomla/joomla-cms/pull/21452/commits/ad2a45f1884f5ba8d6543d444b196b18b5881583) commit, is that what you meant?

2018-09-04 15:07 UTC, HLeithner commented
@wilsonge @mbabker can we get a review and maybe a merge before pbf? would be really helpful.

2018-09-07 17:03 UTC, alikon commented
or maybe PBF  can help us  on having more tests and/or feedback :ok:

2018-11-02 18:14 UTC, astridx commented
I am not very experienced (I use the cli the first time), so I write in detail what I have tested. 

I made a new installation and run `php cli/joomla.php ` in the Joomla Root. I saw this error.

```
php cli/joomla.php 
PHP Notice:  Undefined index: REQUEST_URI in /var/www/html/joomla-cms/includes/framework.php on line 21
PHP Stack trace:
PHP   1. {main}() /var/www/html/joomla-cms/cli/joomla.php:0
PHP   2. require_once() /var/www/html/joomla-cms/cli/joomla.php:35
PHP Notice:  Undefined index: REQUEST_URI in /var/www/html/joomla-cms/includes/framework.php on line 21
PHP Stack trace:
PHP   1. {main}() /var/www/html/joomla-cms/cli/joomla.php:0
PHP   2. require_once() /var/www/html/joomla-cms/cli/joomla.php:35

```

Then I applied this path via `git fetch origin pull/21452/head:m1_copy` and `git checkout m1_copy`. After that this command looks fine.

```
php cli/joomla.php 
Joomla! 4.0.0-alpha5-dev

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display the help information
  -q, --quiet           Flag indicating that all output should be silenced
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Flag to disable interacting with the user
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  check-updates                   Checks for Joomla updates
  help                            Show the help for a command
  list                            List the application's available commands
 cache
  cache:clean                     Cleans expired cache entries
 config
  config:get                      Displays the current value of a configuration option
  config:set                      Sets a value for a configuration option
 core
  core:install                    Sets up the Joomla! CMS.
  core:update                     Updates joomla core
 extension
  extension:install               Installs an extension from a URL or from a Path.
  extension:list                  List installed extensions
  extension:remove                Removes an extension
 session
  session:gc                      Performs session garbage collection
  session:metadata:gc             Performs session metadata garbage collection
 site
  site:down                       Puts the site into offline mode
  site:up                         Puts the site into online mode
 update
  update:extensions:check         Checks for pending extension updates
  update:joomla:remove-old-files  Removes old system files

```
After that I tested the different commands. but I see errors. For example:
```

php cli/joomla.php extension:list
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception, instance of Error given in /var/www/html/joomla-cms/libraries/vendor/symfony/debug/ExceptionHandler.php:106
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ExceptionHandler->handle(Object(Error))
#1 {main}
  thrown in /var/www/html/joomla-cms/libraries/vendor/symfony/debug/ExceptionHandler.php on line 106

```
Am I doing something wrong?





I have one note. If Joomla is not already installed, you will see the following error message, which might be more accurate.

```
php cli/joomla.php extension:list

                                                                                              
  [Joomla\Database\Exception\ConnectionFailureException]                                      
  Could not connect to MySQL: Access denied for user 'root'@'localhost' (using password: NO)  
                                                                                              

extension:list [--type TYPE]
```

2018-11-02 19:43 UTC, bosunski commented
@astridx Thanks for the feedback, i will look into this as soon as possible so you can test again.

2018-11-06 10:02 UTC, bosunski commented
@astridx I have seen the error and got if fixed now, it happened that the `getClientId` method is required by `Plgsystemdebug` on this [Line](https://github.com/joomla/joomla-cms/blob/c092ab6c9ad2d9ad6100837407ef78d33709c2b2/plugins/system/debug/debug.php#L174).

That's the reason for the error. I have pushed the little change I made to this branch, when you update your local branch with this branch it should be fixed now.

@wilsonge @mbabker please review this commit - it's the fix for the error encountered above by @astridx , I want to know if it's done appropriately.

2018-11-06 16:14 UTC, anibalsanchez commented
Great PR! I wish I could have it now on my servers.

These are the results of simple tests on J4 A5:

- check-updates, ERROR

    [Symfony\Component\Debug\Exception\FatalThrowableError]       
    Call to undefined method Joomla\CMS\Extension\MVCComponent::createMVCFactory() 

- help, ERROR

  [Symfony\Component\Debug\Exception\FatalThrowableError]      
  Type error: Argument 1 passed to Joomla\Console\Application::getCommand() must be of the type string, null given, called in /app/www/libraries/vendor/joomla/console/src/Command/HelpCommand.php on line 32  

- list, OK         
- cache:clean, OK  
- config:get, OK   
- config:set, OK   
- core:install, OK 
- core:update, ERROR

  [Symfony\Component\Debug\Exception\FatalThrowableError]       
  Call to undefined method Joomla\CMS\Extension\MVCComponent::createMVCFactory() 

- extension:install, ERROR  

  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'JNamespacePsr4Map' not found

- extension:list, OK
- extension:remove, ERROR

  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'JNamespacePsr4Map' not found
- session:gc, ERROR   

 [ERROR] Garbage collection was not completed. Either the operation ERRORed or is not supported on your platform.

- session:metadata:gc, OK
- site:down, OK    
- site:up, OK      
- update:extensions:check, OK      
- update:joomla:remove-old-files, OK

2018-11-06 20:08 UTC, astridx commented
@bosunski 
Thank you very much for checking. Now I could run `extension:list`

But

```
php cli/joomla.php check-updates

                                                                               
  [Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Call to undefined method Joomla\CMS\Extension\MVCComponent::createMVCFactor  
  y()                                                               
```

2018-11-06 21:23 UTC, bosunski commented
Thanks @anibalsanchez and @astrid for the test, I will look into the errors and get you updated once resolved.

I think some changes in J4 A5 core seems to be affecting this PR as it depends on some components in the core, i will see that everything works perfect.

2018-11-19 18:42 UTC, bosunski commented
@astridx and @anibalsanchez you can test again now, issues have been fixed. Others can also test too.

@mbabker @wilsonge I will like to know what's left for this PR to be merged and will be glad to work on it.

2018-11-19 18:55 UTC, Quy commented on installation/src/Model/DatabaseModel.php
> +
Revert blank line.

2018-11-19 18:55 UTC, Quy commented on installation/src/Model/DatabaseModel.php
> +
Revert blank line.

2018-11-19 18:56 UTC, Quy commented on libraries/src/Application/ConsoleApplication.php
> +use Joomla\Database\DatabaseInterface;
Please sort in alpha order.

2018-11-19 18:58 UTC, Quy commented on libraries/src/Console/ExtensionRemoveCommand.php
> +				if ($result)
```suggestion

				if ($result)
```

2018-11-19 18:58 UTC, Quy commented on libraries/src/Console/ExtensionRemoveCommand.php
> +			return 0;
```suggestion

			return 0;
```

2018-11-19 18:58 UTC, Quy commented on libraries/src/Console/ExtensionRemoveCommand.php
> +			return 2;
```suggestion

			return 2;
```

2018-11-19 18:58 UTC, Quy commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		return 0;
```suggestion

		return 0;
```

2018-11-19 18:59 UTC, Quy commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		$row       = Table::getInstance('extension');
No need for the variable. Combine the 2 lines.

2018-11-19 19:00 UTC, Quy commented on libraries/src/Console/ExtensionsListCommand.php
> +use Joomla\CMS\Factory;
Sort in alpha order.

2018-11-19 19:00 UTC, Quy commented on libraries/src/Console/ExtensionsListCommand.php
> +		if ($type)
```suggestion

		if ($type)
```

2018-11-19 19:00 UTC, Quy commented on libraries/src/Console/ExtensionsListCommand.php
> +			return 0;
```suggestion

			return 0;
```

2018-11-19 19:00 UTC, Quy commented on libraries/src/Console/ExtensionsListCommand.php
> +		return 0;
```suggestion

		return 0;
```

2018-11-19 19:01 UTC, Quy commented on libraries/src/Console/ExtensionsListCommand.php
> +		return $this->extensions;
```suggestion

		return $this->extensions;
```

2018-11-19 19:01 UTC, Quy commented on libraries/src/Console/ExtensionsListCommand.php
> +		foreach ($extensions as $key => $extension)
```suggestion

		foreach ($extensions as $key => $extension)
```

2018-11-19 19:02 UTC, Quy commented on libraries/src/Console/SetConfigurationCommand.php
> +
Remove extra blank line.

2018-11-19 19:03 UTC, Quy commented on libraries/src/Console/SiteDownCommand.php
> +
Remove extra blank line.

2018-11-19 19:03 UTC, Quy commented on libraries/src/Console/SiteUpCommand.php
> +
Remove extra blank line.

2018-11-19 19:03 UTC, Quy commented on libraries/src/Console/UpdateCoreCommand.php
> +
Remove extra blank line.

2018-11-19 19:14 UTC, bosunski commented
Thanks, @Quy for the review, I will make corrections.

2018-12-08 18:45 UTC, astridx commented
I just want to test this branch. 
I applied it like in this comment and I run `composer update` and `npm install`.

Then I `php cli/joomla.php ` run and I get the message

`$ php cli/joomla.php 
PHP Warning:  Declaration of Joomla\Event\DispatcherAwareTrait::setDispatcher(Joomla\Event\DispatcherInterface $dispatcher) should be compatible with Symfony\Component\Console\Application::setDispatcher(Symfony\Component\EventDispatcher\EventDispatcherInterface $dispatcher) in /var/www/html/joomla-cms4/libraries/src/Application/ConsoleApplication.php on line 37
PHP Stack trace:
PHP   1. {main}() /var/www/html/joomla-cms4/cli/joomla.php:0
PHP   2. Joomla\DI\Container->get() /var/www/html/joomla-cms4/cli/joomla.php:79
PHP   3. Joomla\DI\Resource->getInstance() /var/www/html/joomla-cms4/libraries/vendor/joomla/di/src/Container.php:96
PHP   4. Joomla\CMS\Service\Provider\Application->Joomla\CMS\Service\Provider\{closure}() /var/www/html/joomla-cms4/libraries/vendor/joomla/di/src/Resource.php:175
PHP   5. spl_autoload_call() /var/www/html/joomla-cms4/libraries/src/Service/Provider/Application.php:96
PHP   6. JClassLoader->loadClass() /var/www/html/joomla-cms4/libraries/src/Service/Provider/Application.php:96
PHP   7. Composer\Autoload\ClassLoader->loadClass() /var/www/html/joomla-cms4/libraries/cms/class/loader.php:55
PHP   8. Composer\Autoload\includeFile() /var/www/html/joomla-cms4/libraries/vendor/composer/ClassLoader.php:322
PHP   9. include() /var/www/html/joomla-cms4/libraries/vendor/composer/ClassLoader.php:444
PHP Fatal error:  Class Joomla\CMS\Application\ConsoleApplication contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Joomla\CMS\Application\ConsoleApplication::getLogger) in /var/www/html/joomla-cms4/libraries/src/Application/ConsoleApplication.php on line 37
PHP Stack trace:
PHP   1. {main}() /var/www/html/joomla-cms4/cli/joomla.php:0
PHP   2. Joomla\DI\Container->get() /var/www/html/joomla-cms4/cli/joomla.php:79
PHP   3. Joomla\DI\Resource->getInstance() /var/www/html/joomla-cms4/libraries/vendor/joomla/di/src/Container.php:96
PHP   4. Joomla\CMS\Service\Provider\Application->Joomla\CMS\Service\Provider\{closure}() /var/www/html/joomla-cms4/libraries/vendor/joomla/di/src/Resource.php:175
PHP   5. spl_autoload_call() /var/www/html/joomla-cms4/libraries/src/Service/Provider/Application.php:96
PHP   6. JClassLoader->loadClass() /var/www/html/joomla-cms4/libraries/src/Service/Provider/Application.php:96
PHP   7. Composer\Autoload\ClassLoader->loadClass() /var/www/html/joomla-cms4/libraries/cms/class/loader.php:55
PHP   8. Composer\Autoload\includeFile() /var/www/html/joomla-cms4/libraries/vendor/composer/ClassLoader.php:322
PHP   9. include() /var/www/html/joomla-cms4/libraries/vendor/composer/ClassLoader.php:444
`

2018-12-08 18:57 UTC, mbabker commented
Use `composer install`, not `composer update`.

2018-12-08 20:21 UTC, astridx commented
OK. I now used composer install but it does not change my result.

2018-12-08 20:35 UTC, mbabker commented
If you ran `composer install` after `composer update` that would be expected because `composer update` updates the `composer.lock` file whereas `composer install` installs dependencies based on what is in the lock file.

Long and short, NEVER run `composer update` or `npm update` unless you are truly aiming to update your dependencies.  ALWAYS run the `install` commands to grab the dependencies in the state set by the lock file.

2018-12-08 21:10 UTC, bosunski commented
Tried what @mbabker said, it's very true @astridx , `composer update` breaks the code.
You need to revert the changes made to `composer.lock` before `composer install` will work again.
You can then delete the `libraries/vendor` folder and run `composer install` again, the error will go that way.

Thanks @mbabker .

2018-12-08 21:20 UTC, bosunski commented
@mbabker Do you think there is a neater way to do [this](https://github.com/joomla/joomla-cms/pull/21452/commits/9ece94341fa0d5517d437cd3eb9cce20ab45ceb7)?

2018-12-09 11:04 UTC, astridx commented
Thank you for helping me with composer. I forgot, that only `composer install` ensures the same dependencies are used in my test as in development of this PR.

# php cli/joomla.php
`php cli/joomla.php` command worked as expected.

# site

`site:down `and site:up worked fine.

# cache

`cache:clean` worked without failure although I had an issue: https://github.com/joomla/joomla-cms/issues/23250

```
php cli/joomla.php cache:clean

Cleaning System Cache
=====================

                                                                                                        
 [OK] Cache cleaned                                                                                     
                      
```

# php cli/joomla.php debug

Here I was confused about the text `value not set` I expected `false` or `0`. 
```
php cli/joomla.php config:set debug=true

                                                                                
 [OK] Configuration set                                                         
                                                                                

$ php cli/joomla.php config:get debug
 -------- ------- 
  Option   Value  
 -------- ------- 
  debug    1      
 -------- ------- 

$ php cli/joomla.php config:set debug=false

                                                                                
 [OK] Configuration set                                                         
                                                                                

$ php cli/joomla.php config:get debug
 -------- --------- 
  Option   Value    
 -------- --------- 
  debug    Not set  
 -------- --------- 
```

# extension

`extension:list` and `extension:install` worked fine. 

**But:** when I searched for an update, I get no message, that an update is found. I only see a message, that the command was executed correct. In the backend I could see that update. And the remove did not work correct. The extension was installed, although I saw a message, that let me think, that everything is uninstalled correctly.

![extensions update test administration 1](https://user-images.githubusercontent.com/9974686/49696461-3b239580-fbaa-11e8-980b-22f270394223.png)
 

```
$ php cli/joomla.php extension:list

Installed extensions.
=====================

 -------------------------------- -------------- ------------------ ----------- -------- 
  Name                             Extension ID   Version            Type        Active  
 -------------------------------- -------------- ------------------ ----------- -------- 
  com_mailto                       1              4.0.0              component   Yes     
  com_wrapper                      2              4.0.0              component   Yes     
  com_admin                        3              4.0.0              component   Yes     
  com_banners                      4              4.0.0              component   Yes     
  com_cache                        5              4.0.0              component   Yes     
  com_categories                   6              4.0.0              component   Yes     
  com_checkin                      7              4.0.0              component   Yes     
  com_contact                      8              4.0.0              component   Yes     
  com_cpanel                       9              4.0.0              component   Yes     
  com_installer                    10             4.0.0              component   Yes     
  com_languages                    11             4.0.0              component   Yes     
  com_login                        12             4.0.0              component   Yes     
  com_media                        13             3.0.0              component   Yes     
  com_menus                        14             4.0.0              component   Yes     
  com_messages                     15             4.0.0              component   Yes     
  com_modules                      16             4.0.0              component   Yes     
  com_newsfeeds                    17             4.0.0              component   Yes     
  com_plugins                      18             4.0.0              component   Yes     
  com_search                       19             4.0.0              component   Yes     
  com_templates                    20             4.0.0              component   Yes     
  com_content                      22             4.0.0              component   Yes     
  com_config                       23             4.0.0              component   Yes     
  com_redirect                     24             4.0.0              component   Yes     
  com_users                        25             4.0.0              component   Yes     
  com_finder                       27             4.0.0              component   Yes     
  com_joomlaupdate                 28             4.0.0              component   Yes     
  com_tags                         29             4.0.0              component   Yes     
  com_contenthistory               30             4.0.0              component   Yes     
  com_ajax                         31             4.0.0              component   Yes     
  com_postinstall                  32             4.0.0              component   Yes     
  com_fields                       33             4.0.0              component   Yes     
  com_associations                 34             4.0.0              component   Yes     
  com_workflow                     35             4.0.0              component   Yes     
  com_csp                          36             4.0.0              component   Yes     
  lib_joomla                       103            13.1               library     Yes     
  lib_phpass                       106            0.3                library     Yes     
  mod_articles_archive             200            3.0.0              module      Yes     
  mod_articles_latest              201            3.0.0              module      Yes     
  mod_articles_popular             202            3.0.0              module      Yes     
  mod_banners                      203            3.0.0              module      Yes     
  mod_breadcrumbs                  204            3.0.0              module      Yes     
  mod_custom                       205            3.0.0              module      Yes     
  mod_feed                         206            3.0.0              module      Yes     
  mod_footer                       207            3.0.0              module      Yes     
  mod_login                        208            3.0.0              module      Yes     
  mod_menu                         209            3.0.0              module      Yes     
  mod_articles_news                210            3.0.0              module      Yes     
  mod_random_image                 211            3.0.0              module      Yes     
  mod_related_items                212            3.0.0              module      Yes     
  mod_search                       213            3.0.0              module      Yes     
  mod_stats                        214            3.0.0              module      Yes     
  mod_syndicate                    215            3.0.0              module      Yes     
  mod_users_latest                 216            3.0.0              module      Yes     
  mod_whosonline                   218            3.0.0              module      Yes     
  mod_wrapper                      219            3.0.0              module      Yes     
  mod_articles_category            220            3.0.0              module      Yes     
  mod_articles_categories          221            3.0.0              module      Yes     
  mod_languages                    222            3.5.0              module      Yes     
  mod_finder                       223            3.0.0              module      Yes     
  mod_custom                       300            3.0.0              module      Yes     
  mo [...]

2018-12-14 08:14 UTC, bosunski commented
@astridx the ID of the extension is what should be used as an argument when running `extension:remove` command instead of the name.
In this case, it will be:

`$ php cli/joomla.php extension:remove 10006`

Instead of:

`$ php cli/joomla.php extension:remove mod_agosm`

I have updated the code to show error notification when it's not the  ID that is passed as the argument.

Thanks for testing. 🙂

2018-12-14 12:47 UTC, Quy commented on includes/framework.php
> +	elseif (file_exists(JPATH_INSTALLATION . '/index.php') && php_sapi_name() !== 'cli')
Remove `&& php_sapi_name() !== 'cli'` since this check is already done in the if statement.

2018-12-14 12:49 UTC, Quy commented on installation/src/Form/Field/Installation/PrefixField.php
> +		$size = $this->element['size'] ? abs((int) $this->element['size']) : 5;
Revert to align `=` with the other `=`s.

2018-12-14 12:50 UTC, Quy commented on libraries/src/Application/ConsoleApplication.php
> +use Joomla\CMS\Version;
Move after line 19

2018-12-14 12:53 UTC, Quy commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			$symfonyStyle->note('New Joomla Version ' . $data['latest'] . ' is available.');
This does not need to be in an else clause.

2018-12-14 12:55 UTC, Quy commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +			return $this->updateInfo;
Move this line out of the if clause and remove the else clause.

2018-12-14 12:55 UTC, Quy commented on libraries/src/Console/ExtensionInstallCommand.php
> +use Joomla\CMS\Installer\InstallerHelper;
Sort in alpha order.

2018-12-14 12:59 UTC, Quy commented on libraries/src/Console/UpdateCoreCommand.php
> +
Remove extra blank line.

2018-12-14 13:03 UTC, Quy commented on libraries/src/Console/UpdateCoreCommand.php
> +			$this->progressBar->finish();
Move lines 181-184 out of the else clause.

2018-12-14 13:06 UTC, Quy commented
Why is `.htacess` deleted and included in pr.

2018-12-14 16:04 UTC, Quy commented on libraries/src/Console/ExtensionInstallCommand.php
> +		$tmp_path     = $tmp_path . '/' . basename($path);
Align `=`

2018-12-16 20:09 UTC, bosunski commented
> Why is `.htacess` deleted and included in pr.

I don't know why yet, I'm still trying to find out how it got there.

2018-12-17 06:44 UTC, Quy commented on libraries/src/Console/CoreInstallCommand.php
> +
Remove blank line.

2018-12-17 06:44 UTC, Quy commented on libraries/src/Console/CoreInstallCommand.php
> +
Remove blank line.

2018-12-17 06:46 UTC, Quy commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		return 0;
Remove since it will not reach here.

2019-02-20 12:11 UTC, dneukirchen commented
what is blocking this?
@bosunski can you sync the pr with the latest dev and fix the code styles issues?
i would love to see this in the core and will test it as soon as you updated the pr. 
we need to test if this pr still works after #23847 
if you need any help dont hesitate to ask.

2019-02-20 13:52 UTC, HLeithner commented
@bosunski I merged the #23847 can you adjust your PR?

@mbabker do we still habe a problem merging this (except the conflict)?

2019-02-20 13:55 UTC, bosunski commented
Okay, I will get on this now.

Thanks, @HLeithner and @dneukirchen

2019-02-20 14:06 UTC, bosunski commented
Accidentally closed this!

2019-02-20 16:36 UTC, alikon commented
thanks @bosunski  for the quick response ...
 please fix the CS issues, maybe we can have a new chance for being merged now

2019-02-20 17:30 UTC, bosunski commented
Already doing that @alikon

2019-02-20 17:31 UTC, bosunski commented
..

2019-02-20 19:40 UTC, bosunski commented
Code updated. @HLeithner @dneukirchen @alikon @mbabker

2019-02-21 08:33 UTC, dneukirchen reviewed
I will review the commands later.

2019-02-21 08:33 UTC, dneukirchen commented on libraries/src/Application/ConsoleApplication.php
> +		$langfiles = array();
I know this code is copied from Install Application, but we can improve the code in the Console Application
Code Style Suggestion: use [] syntax

2019-02-21 08:33 UTC, dneukirchen commented on libraries/src/Application/ConsoleApplication.php
> +				foreach ($language as $languageCode => $lang)
var $languageCode is never used: change to foreach($languages as $language)

2019-02-21 08:33 UTC, dneukirchen commented on libraries/src/Application/ConsoleApplication.php
> +			foreach (LanguageHelper::getInstalledLanguages() as $clientId => $language)
Code Style Suggestion: var $language contains multiple languages. Kindly rename it to $languages.

2019-02-21 08:33 UTC, dneukirchen commented on libraries/src/Application/ConsoleApplication.php
> +		else
Code Style Suggestion: skip this else block and use early return

```
if($db) {
  $langFiles = [];
  foreach() {
    ...
  }
  return $langFiles.
}

return [
    'site' => ...,
    'admin' => ...
]
```

2019-02-21 08:33 UTC, dneukirchen commented on cli/joomla.php
> +$extensionPsr4Loader->load();
Should we register the namespacemap here? this can be done in the Application using the ExtensionNamespaceMapper trait.

2019-02-21 08:33 UTC, dneukirchen commented on includes/framework.php
> +	elseif (file_exists(JPATH_INSTALLATION . '/index.php'))
Code Style Suggestion: You dont need elseif when your return in the first if block

2019-02-21 08:33 UTC, dneukirchen commented on libraries/vendor/.htaccess
> -# Apache 2.4+
Why was this removed?

2019-02-21 08:33 UTC, dneukirchen commented on libraries/src/Factory.php
> +			if (!isset($instance) || !($instance instanceof User))
why is this additional check needed?

2019-02-21 08:33 UTC, dneukirchen commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$symfonyStyle = new SymfonyStyle($this->getApplication()->getConsoleInput(), $this->getApplication()->getConsoleOutput());
Why do you get input and output from app and not using method params?

2019-02-21 09:02 UTC, dneukirchen commented on libraries/src/Application/ConsoleApplication.php
> +	public function getLocaliseAdmin(DatabaseInterface $db = null)
This method is used in the DatabaseModel, but is not part of the application interface. Its only used by the installer app and now the console app. Imo it does not belong in the app itself. Instead we should remove it from installer application and console application and move it to the DatabaseModel or LanguageHelper

2019-03-17 17:59 UTC, mbabker requested changes
In addition to the inline feedback, all output should be reviewed by the en-GB team.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +	protected $clientId = null;
This property should be initialized with an appropriate value, not left as null.  I believe 4 is the next unused value after the API app was merged.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +		if (file_exists(JPATH_CONFIGURATION . '/configuration.php'))
A comment indicating why this check is necessary should be left.  And I would suggest this check should not be necessary, the plugin helper should deal with issues stemming from the database connection being unavailable if really necessary.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\UpdateCoreCommand,
There is a measurable performance hit by instantiating all of these classes every time the console application class is created.  All of these commands should be moved to [the Console service provider](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Service/Provider/Console.php) and lazy loaded within [the command loader](https://github.com/joomla/joomla-cms/blob/204944255cf6cbc08358625e541e0acccf64aa10/libraries/src/Service/Provider/Application.php#L116-L129).

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +	 * @since 4.0
PHPCS - The order of tags should be `@param`, `@return`, `@since`, and if used `@throws`.  I don't think there is a formal spec on any other optional tags and how they should be ordered.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/CoreInstallCommand.php
> +			Factory::getApplication()->enqueueMessage(Text::_('INSTL_DATABASE_INVALID_TYPE'), 'warning');
Within a command, there should never be a call to `Factory::getApplication()`.  It should ALWAYS use `$this->getApplication()` to use the injected application.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/CoreInstallCommand.php
> +			exit;
There should not be any exit calls in commands.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/CoreInstallCommand.php
> +	public function getDummyOptions()
Please use more appropriate naming.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/CoreInstallCommand.php
> +			Factory::getSession()->set('setup.options', $options);
Always use `$this->getApplication()->getSession()` if you're really going to use session logic in commands.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/ExtensionInstallCommand.php
> +		$help = "The <info>%command.name%</info> is used for installing extensions \n
Use heredoc syntax if you are writing multi-line help text.  See https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Console/CleanCacheCommand.php for an example.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/ExtensionInstallCommand.php
> +		$jInstaller = Installer::getInstance();
Do not use `Installer::getInstance()`, run `new Installer` instead.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/ExtensionInstallCommand.php
> +				$this->ioStyle->error('Unable to install extension');
These error outputs indicate the command should return a non-zero exit code.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/SetConfigurationCommand.php
> +			file_put_contents($path, $buffer);
All of the filesystem interaction in this class (and any others if present) should use the `Joomla\CMS\Filesystem` API.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/SiteDownCommand.php
> +		$command->setOptions('offline=true');
This is the wrong way to pass options into another CLI class.  You should be creating a new InputInterface object with the arguments and/or options you'll be passing into it.  See [this block](https://github.com/joomla/framework.joomla.org/blob/c52a48250f9d8e1d1dd9bc4c90efde5ee745fdb7/src/Command/UpdateCommand.php#L92-L100) as an example of the correct way to do this.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/UpdateCoreCommand.php
> +		unset($this->updateModel);
1) Do not unset a class member variable
2) If you're needing to do this, this is indicative of another code problem that should be resolved

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Console/UpdateCoreCommand.php
> +		$db = Factory::getDbo();
Once all commands are moved to be container services, things like the database driver should be injected into the class through the constructor instead of pulled out of a static factory.

2019-03-17 17:59 UTC, mbabker commented on libraries/src/Factory.php
> +			$instance = User::getInstance();
This change should be reverted and proposed as a separate pull request with a better explanation of why it's necessary.

2019-03-17 20:11 UTC, brianteeman commented
From reading the documentation there are some inconsistencies in how you use this

```
php cli/joomla.php extension:list --type=language
php cli/joomla.php extension:install url --url=https://.......
```

I would have expected both of these to be constructed in the same way so they would be like this
```
php cli/joomla.php extension:list --type=language
php cli/joomla.php extension:install --url=https://.......
```

2019-03-27 14:09 UTC, bosunski commented
@mbabker Thanks for the reviews!

Notice: In [this](https://github.com/joomla/joomla-cms/blob/5d85b08cbb599679713a07c2fb4796a8e64e2d1f/libraries/src/Plugin/PluginHelper.php#L294), `Factory::getUser()` returns null after updating this PR with merges from `4.0-dev`, and it breaks the CLI app.

However, if we change [this](https://github.com/joomla/joomla-cms/blob/5d85b08cbb599679713a07c2fb4796a8e64e2d1f/libraries/src/Plugin/PluginHelper.php#L294) to `Factory::getApplication()->getIdentity()->getAuthorisedViewLevels()` and then Update the `getIdentity` method inside `IdentityAware` Trait to call `loadIdentity` like this:

```
public function getIdentity()
{
    $this->loadIdentity();
    return $this->identity;
}
```

Everything Works fine.

Is this supposed to be? Or what am I missing? Should the `PluginHelper` be updated maybe with another PR?

We need to find a solution as it prevents the whole `CLI App` from running.

2019-03-27 14:16 UTC, mbabker commented
`getIdentity` should not also be arbitrarily loading anything so that's not a viable option.

This PR still has changes in `Factory::getUser()` in comparison to the main 4.0 branch.  Revert those changes too then see what happens.

2019-03-27 14:25 UTC, bosunski commented
It's still the same thing. The issue still persists after reverting changes compared to `4.0-dev`.

2019-03-27 15:33 UTC, bosunski commented
> From reading the documentation there are some inconsistencies in how you use this
> 
> ```
> php cli/joomla.php extension:list --type=language
> php cli/joomla.php extension:install url --url=https://.......
> ```
> I would have expected both of these to be constructed in the same way so they would be like this
> 
> ```
> php cli/joomla.php extension:list --type=language
> php cli/joomla.php extension:install --url=https://.......
> ```

@brianteeman you can install an extension in 2 ways - from a remote `url` or from a local `path`, the processes to install either is different, in other to differentiate what process we're using, that's why I added the argument. That is why something like this is done:

```
php cli/joomla.php extension:install url --url=https://.......
```
For the case of a Path, you do this:

```
php cli/joomla.php extension:install path --path=/var/www/...
```

2019-03-27 15:56 UTC, mbabker commented
You shouldn't need both an argument and an option.  The command should have checks to ensure that at least one of the options is set and raise an error if they're both missing or both set.

2019-03-27 16:02 UTC, mbabker commented
So either the command has two arguments (install type, one of "path" or "url" (though this should probably also support the plugin driven approach introduced to the component) and the address for that type), or a single argument (the install type) and an option for the address (path/URL/whatever), or two options (`--type=<foo> --address=<bar>`).  But it should not end up as it is now where you have an argument specifying the type AND an option specifying the type.  Or, if the command is built in a way where it supports multiple installs, then you would omit the type argument completely and your options would turn into something that can exist multiple times (`InputOption::VALUE_IS_ARRAY` instead of one of the other `VALUE_*` constants) then you'd have something like `extension:install --path=/var/www/path1 --path=/var/www/path2 --url=https://www.example.com` which turns into an array in the PHP code.

2019-03-27 16:12 UTC, brianteeman commented
Why not
Install --url=Https://example.com
Install --path=/path/to/extension.zip

On Wed, 27 Mar 2019, 17:33 bosunski, <notifications@github.com> wrote:

> From reading the documentation there are some inconsistencies in how you
> use this
>
> php cli/joomla.php extension:list --type=language
> php cli/joomla.php extension:install url --url=https://.......
>
> I would have expected both of these to be constructed in the same way so
> they would be like this
>
> php cli/joomla.php extension:list --type=language
> php cli/joomla.php extension:install --url=https://.......
>
> @brianteeman <https://github.com/brianteeman> you can install an
> extension in 2 ways - from a remote url or from a local path, the
> processes to install either is different, in other to differentiate what
> process we're using, that's why I added the argument. That is why something
> like this is done:
>
> php cli/joomla.php extension:install url --url=https://.......
>
> For the case of a Path, you do this:
>
> php cli/joomla.php extension:install path --path=/var/www/...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/21452#issuecomment-477211847>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABPH8U4rfur4Lqzd0cC-seoaOLJLJsH1ks5va48wgaJpZM4VykbL>
> .
>

2019-03-27 18:19 UTC, mbabker commented
What part of the CLI application is not running without your modifications to how the User object is loaded?  Last I checked the 4.0 branch, the CLI commands were all running correctly, which means there is a change introduced into this PR that is causing your issues.  If you really need whatever change I said to back out, then it needs to be clearly documented why it exists because in a pull request whose job is to add some console commands a change at that part of the architecture seems wrong without some additional context.

2019-03-27 18:21 UTC, mbabker commented on cli/joomla.php
> +// Registers the Installation namespace
So, looking at this again it really seems like this file should not be arbitrarily loading the installation directory into the autoloader, but something deeper into the architecture (something in the includes directory or libraries/bootstrap.php) should be doing this.

2019-03-27 18:21 UTC, mbabker commented on includes/framework.php
> +	// Prevents the script from exiting in the CLI mode
This comment should be expanded upon to explain why this is needed.

2019-03-27 18:23 UTC, mbabker commented on installation/src/Form/Field/Installation/PrefixField.php
> +	public function getPrefix()
This change just feels all sorts of wrong, and you are misusing a form field in other classes as a result.  This method seems like it should be moved to its own helper somewhere, say in some `Joomla\CMS\Database` helper class and the CLI commands using this method updated accordingly.

2019-03-27 18:24 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +		if (file_exists(JPATH_CONFIGURATION . '/configuration.php'))
This comment still needs to be addressed.

2019-03-27 18:24 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +		return parent::getDefaultCommands();
You can remove this method completely if all it is doing is calling the method from the parent class.

2019-03-27 18:30 UTC, mbabker commented on libraries/src/Console/CheckJoomlaUpdatesCommand.php
> +		$help = "The <info>%command.name%</info> Checks for Joomla updates.\n Usage: <info>php %command.full_name%</info>";
```suggestion
		$help = <<<'EOF'
The <info>%command.name%</info> Checks for Joomla updates.

  <info>php %command.full_name%</info>
EOF
		;
```

2019-03-27 18:33 UTC, mbabker commented on libraries/src/Console/CoreInstallCommand.php
> +		$help = "The <info>%command.name%</info> is used for setting up the Joomla! CMS \n
Please do not try to use stylized double quoted strings, use heredoc syntax.

```php
$help = <<<'EOF'
The <info>%command.name%</info> is used for setting up the Joomla! CMS

  <info>php %command.full_name%</info>

To set up Joomla! using an existing configuration file, use the <info>--file</info> option. This may be either a JSON or INI file.

  <info>php %command.full_name% --file=<path></info>
EOF
;
```

2019-03-27 18:37 UTC, mbabker commented on libraries/src/Console/ExtensionInstallCommand.php
> +		$this->setHelp(<<<EOF
Same thing here.

```php
$this->setHelp(<<<'EOF'
The <info>%command.name%</info> is used to install extensions

  <info>php %command.full_name%</info>

You must provide one of the following options to the command:

  --path: The path on your local filesystem to the install package
  --url: The URL from where the install package should be downloaded

  <info>php %command.full_name% --path=<path_to_file></info>
  <info>php %command.full_name% --url=<url_to_file></info>
EOF
);
```

Basically, run `cli/joomla.php extension:install --help` and make sure your output looks correct and doesn't have issues like 3 tabs worth of indention.

2019-03-27 18:39 UTC, mbabker commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		$help = "The <info>%command.name%</info> Removes an extension \n <info>php %command.full_name%</info>";
```php
$this->setHelp(<<<'EOF'
The <info>%command.name%</info> is used to uninstall extensions.  The command requires one argument, the ID of the extension to uninstall.  You may find this ID by running the <info>extension:list</info> command.

  <info>php %command.full_name% <extension_id></info>
EOF
);
```

2019-03-27 18:40 UTC, mbabker commented on libraries/src/Console/ExtensionsListCommand.php
> +		$help = "The <info>%command.name%</info> List all currently installed extensions
```php
$this->setHelp(<<<'EOF'
The <info>%command.name%</info> is used to list all extensions installed on your site.

  <info>php %command.full_name% <extension_id></info>

You may filter on the type of extension (component, module, plugin, etc.) using the <info>--type</info> option:

  <info>php %command.full_name% --type=<type></info>
EOF
);
```

2019-03-27 18:42 UTC, mbabker commented on libraries/src/Console/SiteDownCommand.php
> +		$help = "The <info>%command.name%</info> Puts the site into offline mode
```php
$this->setHelp(<<<'EOF'
The <info>%command.name%</info> is used to place the site offline.

  <info>php %command.full_name%</info>
EOF
);
```

2019-03-27 18:42 UTC, mbabker commented on libraries/src/Console/UpdateCoreCommand.php
> +		$help = "The <info>%command.name%</info> Updates the Joomla core \n <info>php %command.full_name%</info>";
```php
$this->setHelp(<<<'EOF'
The <info>%command.name%</info> is used to update Joomla.

  <info>php %command.full_name%</info>
EOF
);
```

2019-03-27 18:45 UTC, mbabker commented on libraries/src/Service/Provider/Console.php
> +	 * Gets available command names
This should be better documented.  As is, it reads like it should retrieve a list of all of the command class names that the core application provides.  The reality is this is a list of commands that do not have constructor dependencies and you're using this to lazily create services for 12 classes without explicitly creating the container definitions for each of them.  This makes it too easy for someone to mess up in adding more commands later.

2019-06-08 14:28 UTC, SniperSister commented on includes/framework.php
> +		define('JDEBUG', true);
This change would force the debug mode being enabled if the framework is loaded in a CLI context, right? Why no defining it as false instead?

2019-06-08 16:35 UTC, Quy commented on includes/framework.php
> +		// This is been defined because some core scripts needs it defined.
```suggestion
		// This has been defined because some core scripts needs it defined.
```

2019-06-08 16:36 UTC, Quy commented on includes/framework.php
> +		// We pass control back to the calling scrip - joomla.php to allow commands like core:install to run
```suggestion
		// We pass control back to the calling script - joomla.php to allow commands like core:install to run
```

2019-06-08 16:36 UTC, Quy commented on installation/src/Helper/DatabaseHelper.php
> +	 * @param   int  $size  SIze of the Prefix
```suggestion
	 * @param   int  $size  Size of the Prefix
```

2019-06-08 16:36 UTC, Quy commented on installation/src/Helper/DatabaseHelper.php
> +		// We want the fist character to be a random letter.
```suggestion
		// We want the first character to be a random letter.
```

2019-06-09 09:34 UTC, bosunski commented on includes/framework.php
> +		define('JDEBUG', true);
oh! I will change that to false now. Thanks.

2019-08-31 20:50 UTC, roland-d commented
@HLeithner What is the status of this PR? Can the conflicts be fixed and tested?

2019-09-02 10:27 UTC, HLeithner commented
@bosunski could fix the conflicts?

2019-09-03 13:05 UTC, bosunski commented
yes ... I'll see to that @HLeithner

2019-10-02 13:36 UTC, roland-d commented
Thank you for updating this.

2019-10-02 13:36 UTC, bosunski commented
@HLeithner and @roland-d, I ran into this issue after updating the PR. 
<img width="741" alt="Screenshot 2019-09-21 at 12 40 37 PM" src="https://user-images.githubusercontent.com/15146515/66048766-0cecb900-e522-11e9-9d73-a0f358f8ea21.png">

2019-10-02 13:37 UTC, bosunski commented
The part saying `Class Joomla\Component\Acyionlogs\... Not found`

2019-10-02 13:41 UTC, bosunski commented
The error shows when I run `php cli/joomla.php`. I manage do to some debugging to get the exception you're seeing above up.
However, commenting out `PluginHelper::importPlugin('system');` as shown in the image below inside `ConsoleApplication.php` makes running the command work without an issue.
<img width="1680" alt="Screenshot 2019-10-02 at 14 38 24" src="https://user-images.githubusercontent.com/15146515/66049076-a1571b80-e522-11e9-869f-fe8719156bfe.png">

2019-10-02 14:14 UTC, mbabker commented
`rm libraries/autoload_psr4.php` and try again

2019-10-02 14:15 UTC, mbabker commented on includes/framework.php
> +		define('JDEBUG', false);
The `JDEBUG` constant should still be set true/false based on the configuration.  It should not be arbitrarily set to false for all CLI scripts.

2019-10-02 14:18 UTC, bosunski commented
> `rm libraries/autoload_psr4.php` and try again

<img width="1532" alt="Screenshot 2019-10-02 at 15 17 32" src="https://user-images.githubusercontent.com/15146515/66052024-cef29380-e527-11e9-8546-b2f52009352f.png">

This is the result I got after running this.

2019-10-02 14:23 UTC, mbabker commented
Then you're still getting an exception in booting up the framework/application.  Dump the exception in `libraries/vendor/symfony/debug/ExceptionHandler.php`, inside the `handle()` method, and go from there.

2019-10-02 14:27 UTC, mbabker commented
```sh
Michaels-Mac-mini:joomla-cms mbabker$ git checkout pr-21452
Switched to branch 'pr-21452'
Michaels-Mac-mini:joomla-cms mbabker$ php cli/joomla.php 

Fatal error: Declaration of Joomla\CMS\Console\SiteDownCommand::configure() must be compatible with Joomla\Console\Command\AbstractCommand::configure(): void in /Users/mbabker/Sites/joomla-cms/libraries/src/Console/SiteDownCommand.php on line 115
```

Check your command class method signatures again.  Presumably they weren't updated after the console application was updated to a PHP 7.2 minimum, which included adding some void return types in places they didn't exist before.

2019-10-02 14:29 UTC, bosunski commented
> Then you're still getting an exception in booting up the framework/application. Dump the exception in `libraries/vendor/symfony/debug/ExceptionHandler.php`, inside the `handle()` method, and go from there.

I got this when I dumped the exception message`"Failed to start application"`.

2019-10-02 14:34 UTC, bosunski commented
> ```shell
> Joomla\Console\Command\AbstractCommand
> ```

As for this, I just pushed some changes correcting those. **But the initial issue still persists**. If you update the PR now, you should see the command Classes updated.

2019-10-02 15:12 UTC, mbabker commented
Well I don't know what to tell you right now but for me none of the applications are working now, everything is failing trying to write the `libraries/autoload_psr4.php` file to disk.

Just for the sake of testing, I made this change (which should not be applied, but will bypass the "failed to start application" error in a janky way):

```diff
diff --git a/libraries/src/Filesystem/File.php b/libraries/src/Filesystem/File.php
index 4ff6c73203..c64a240855 100644
--- a/libraries/src/Filesystem/File.php
+++ b/libraries/src/Filesystem/File.php
@@ -351,7 +351,7 @@ class File
                }
                else
                {
-                       $FTPOptions = ClientHelper::getCredentials('ftp');
+                       $FTPOptions = ['enabled' => 0] /*ClientHelper::getCredentials('ftp')*/;
 
                        if ($FTPOptions['enabled'] == 1)
                        {
```

After that, things are working fine for me (the default `list` command shows everything, the `extension:list`, `config:get`, and `user:list` commands dump their info, and `site:down` and `site:up` updates the config appropriately).

2019-10-02 15:18 UTC, bosunski commented
> Well I don't know what to tell you right now but for me none of the applications are working now, everything is failing trying to write the `libraries/autoload_psr4.php` file to disk.
> 
> Just for the sake of testing, I made this change (which should not be applied, but will bypass the "failed to start application" error in a janky way):
> 
> ```diff
> diff --git a/libraries/src/Filesystem/File.php b/libraries/src/Filesystem/File.php
> index 4ff6c73203..c64a240855 100644
> --- a/libraries/src/Filesystem/File.php
> +++ b/libraries/src/Filesystem/File.php
> @@ -351,7 +351,7 @@ class File
>                 }
>                 else
>                 {
> -                       $FTPOptions = ClientHelper::getCredentials('ftp');
> +                       $FTPOptions = ['enabled' => 0] /*ClientHelper::getCredentials('ftp')*/;
>  
>                         if ($FTPOptions['enabled'] == 1)
>                         {
> ```
> 
> After that, things are working fine for me (the default `list` command shows everything, the `extension:list`, `config:get`, and `user:list` commands dump their info, and `site:down` and `site:up` updates the config appropriately).

Thanks for taking the time to look into this!

What would you recommend I do to fix this issue?

2019-12-02 20:22 UTC, Quy commented on installation/src/Helper/DatabaseHelper.php
> +		$prefix  = '';
```suggestion
```

2019-12-02 20:22 UTC, Quy commented on installation/src/Helper/DatabaseHelper.php
> +		$prefix .= $chars[0];
```suggestion
		$prefix = $chars[0];
```

2019-12-03 00:04 UTC, bosunski commented
Thanks @Quy

2019-12-03 16:49 UTC, Quy commented on libraries/src/Console/ExtensionInstallCommand.php
> +			else
Lines 204-209 do not need to be in an else statement.

2019-12-03 16:50 UTC, Quy commented on libraries/src/Console/ExtensionInstallCommand.php
> +			else
Lines 221-226 do not need to be in an else statement.

2019-12-03 16:50 UTC, Quy commented on libraries/src/Console/ExtensionInstallCommand.php
> +		else
Lines 228-233 do not need to be in an else statement.

2019-12-03 16:51 UTC, Quy commented on libraries/src/Console/ExtensionRemoveCommand.php
> +		else
Lines 149-154 do not need to be in an else statement.

2019-12-03 16:52 UTC, Quy commented on libraries/src/Console/GetConfigurationCommand.php
> +		foreach ($configs as $key => $config)
```suggestion

		foreach ($configs as $key => $config)
```

2019-12-03 16:53 UTC, Quy commented on libraries/src/Console/GetConfigurationCommand.php
> +			return "false";
```suggestion
			return 'false';
```

2019-12-03 16:53 UTC, Quy commented on libraries/src/Console/GetConfigurationCommand.php
> +			return "Not Set";
```suggestion
			return 'Not Set';
```

2019-12-03 16:54 UTC, Quy commented on libraries/src/Console/SetConfigurationCommand.php
> +
```suggestion
```

2019-12-03 16:55 UTC, Quy commented on libraries/src/Service/Provider/Application.php
> +			SessionGcCommand::getDefaultName()         		=> SessionGcCommand::class,
Please align `=>`

2019-12-03 16:57 UTC, Quy commented on libraries/src/Console/GetConfigurationCommand.php
> +				self::DB_GROUP,
Reduce indentation.

2019-12-03 16:57 UTC, Quy commented on libraries/src/Console/GetConfigurationCommand.php
> +				'name' => 'mail',
Reduce indentation.

2019-12-03 19:12 UTC, alikon commented
thanks @bosunski to be still on it :+1:

2020-01-17 18:06 UTC, roland-d commented
@bosunski Could you please fix the merge conflict? Thank you.

2020-01-18 16:14 UTC, wilsonge commented
OK So I've always been nervy about this because of the changes required to base files for the installation part. As a result I'm more than happy to merge the CLI for the non-installer. And I'd like to see the installation in a separate PR that can be audited properly by our security team etc.

2020-02-21 10:15 UTC, HLeithner commented
@bosunski is it possible for you to remove the installation part of this PR so we can merge the rest?, as george said we would like to have a seperate jcli script for installation and maybe as wrapper for joomla.php

@wilsonge Should we preserve the changes needed for the installer to make it easier to create a jcli script?

2020-02-21 11:07 UTC, wilsonge commented
No the changes to includes etc are exactly the reason why we separate out this part.

2020-02-22 15:24 UTC, bosunski commented
> @bosunski is it possible for you to remove the installation part of this PR so we can merge the rest?, as george said we would like to have a seperate jcli script for installation and maybe as wrapper for joomla.php
> 
> @wilsonge Should we preserve the changes needed for the installer to make it easier to create a jcli script?

@HLeithner, Do you mean the part that lets you set up the new Joomla application?

2020-02-22 17:38 UTC, HLeithner commented
@bosunski exactly, we want to remove all the modifications you have to add to the framework to install joomla.

The reason is that installation is the only part that doesn't need a proper setup joomla installation, doing the installation in a separate cli script without booting the framework is maybe a better approach .

2020-02-23 16:47 UTC, bosunski commented
Ok. I'll start work on separating it out.

2020-03-12 13:55 UTC, bosunski commented
@HLeithner @wilsonge is it possible to help with identifying files that changed because of installation ALONE? I've been having a hard time figuring out all changes (that happened because of the installation feature) apart from the command class.

2020-03-13 15:14 UTC, HLeithner commented
> @HLeithner @wilsonge is it possible to help with identifying files that changed because of installation ALONE? I've been having a hard time figuring out all changes (that happened because of the installation feature) apart from the command class.

I would follow your installation function and remove all parts that are not longer needed based on the function calls.

2020-04-15 06:59 UTC, alikon commented
@bosunski please kindly review/test https://github.com/joomla/joomla-cms/pull/28666

2020-05-03 07:41 UTC, alikon commented
thank you @bosunski for your hard work on this, now it is finally into the core, installation apart

2020-05-03 07:41 UTC, closed without merging