Translate states via language files
joomla/joomla-cms pull request #21506
Opened 2018-08-09 19:14 UTC by bembelimen

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/21476#issuecomment-411694584.

### Summary of Changes
Now one can use languages constants to have multilingual states

### Testing Instructions
Create a state called "JPUBLISHED" and check it everywhere in the system (state list, article edit form, article list, transition edit form, ...)

### Expected result
The language constant will be translated

### Actual result
No translation at all

2018-08-09 19:18 UTC, brianteeman commented on administrator/components/com_workflow/tmpl/states/default.php
> +use Joomla\CMS\Factory;
Factory already exists a few lines down. Adding it twice will fail.

2018-08-09 19:21 UTC, bembelimen commented on administrator/components/com_workflow/tmpl/states/default.php
> +use Joomla\CMS\Factory;
Strange, I thought I solved it with the conflict, thanks for the pointer!

2018-08-10 06:10 UTC, infograf768 commented on administrator/components/com_workflow/tmpl/states/default.php
>  											<a href="<?php echo $edit; ?>" title="<?php echo Text::_('JACTION_EDIT'); ?> <?php echo $this->escape(addslashes($item->title)); ?>">
need also a Text:: for the title
<?php echo $this->escape(addslashes($item->title))
to
<?php echo $this->escape(addslashes(Text::_($item->title)))

2018-08-10 07:21 UTC, infograf768 commented
Also:
same corrections should be done for Transitions
Using maybe the existing strings
JTOOLBAR_UNPUBLISH, etc. or new specific COM_WORKFLOW strings

To obtain (here for French. just modified for unpublished)

<img width="883" alt="screen shot 2018-08-10 at 09 02 43" src="https://user-images.githubusercontent.com/869724/43943545-3a92ab20-9c7c-11e8-9591-956c6eb61d6f.png">

In both cases `Modifier Non Publié` for the title is not very nice phrasing. Maybe add a : between.

2018-08-10 10:40 UTC, bembelimen commented
@infograf768 I'll create a new PR for this, but thanks for the suggestion!

2018-08-13 15:36 UTC, infograf768 commented
Can conflicts be solved?

2018-08-13 15:37 UTC, bembelimen commented
Sure, I waited for #21566

2018-08-13 15:39 UTC, infograf768 commented
I think that also `Joomla! Default` should be a string btw.

2018-08-14 10:23 UTC, infograf768 commented on libraries/src/Form/Field/WorkflowStageField.php
> +			$workflowStates[$workflowStateKey][] = HTMLHelper::_('select.option', $state->workflow_stage_id, Text::_($state->workflow_stage_title));
$state or $stage?

2018-08-14 10:24 UTC, infograf768 commented
Also conflict with new file name.

2018-08-14 10:30 UTC, infograf768 commented
And I foresee issues with https://github.com/joomla/joomla-cms/pull/21520 as the sql does not use string constants.

2018-08-17 20:31 UTC, Joomv commented on libraries/src/Form/Field/TransitionField.php
> +use Joomla\CMS\Form\Field\ListField;
You don't need to import this as it's in the same namespace

2018-08-17 20:32 UTC, Joomv commented on libraries/src/Form/Field/WorkflowStageField.php
> +			$workflowStates[$workflowStateKey][] = HTMLHelper::_('select.option', $state->workflow_stage_id, Text::_($state->workflow_stage_title));
Should be $stage

2018-08-17 20:32 UTC, Joomv commented on administrator/components/com_workflow/tmpl/stages/default.php
> +$lang		= Factory::getLanguage();
You aren't using this property

2018-08-17 20:33 UTC, Joomv requested changes
Also requires conflicts fixing as well as comments

Deleted useless hashtag here... (JM)

2018-08-17 22:03 UTC, bembelimen commented on libraries/src/Form/Field/WorkflowStageField.php
> +			$workflowStates[$workflowStateKey][] = HTMLHelper::_('select.option', $state->workflow_stage_id, Text::_($state->workflow_stage_title));
I'll create a new PR (after this PR is merged), because that is another context

2018-08-23 15:32 UTC, infograf768 commented
Missing Text:: line 118 of tmpl/transitions/default.php to get
`											<a href="<?php echo $edit; ?>" title="<?php echo Text::_('JACTION_EDIT'); ?> <?php echo Text::_($this->escape(addslashes($item->title))); ?>">
`

Otherwise good first step me

2018-08-23 15:38 UTC, Fedik commented on administrator/components/com_content/tmpl/articles/default.php
> +										<div class="mr-auto"><?php echo Text::_($this->escape($item->stage_title)); ?></div>
I think correct would be do `escape()` after translation, not before :wink:

2018-08-23 19:57 UTC, bembelimen commented on administrator/components/com_content/tmpl/articles/default.php
> +										<div class="mr-auto"><?php echo Text::_($this->escape($item->stage_title)); ?></div>
You're right, thx

2018-08-23 19:59 UTC, bembelimen commented
Thanks @infograf768

2018-08-24 05:01 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 9d0ba736eb75e0142a719a7b5605fd7cbe153507<br /><br />Let's advance with this.

One more tester, if possible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21506">issues.joomla.org/tracker/joomla-cms/21506</a>.</sub>

2018-08-24 05:15 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on 9d0ba736eb75e0142a719a7b5605fd7cbe153507<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21506">issues.joomla.org/tracker/joomla-cms/21506</a>.</sub>

2018-08-24 05:16 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-08-24 05:17 UTC, alikon commented
https://github.com/joomla/joomla-cms/pull/21506/files#diff-135c6f58583408312a709459b19594c7
it lacks the upgrade path and obviously postgresql

2018-08-24 05:19 UTC, alikon commented
question:
should we do the same on the `#__workflow_transitions` ?

2018-08-24 05:20 UTC, ghost commented
Status back on "Pending".

2018-08-24 05:27 UTC, infograf768 commented
@alikon 
I thought we could do that after the follow-up on this.
I explain:

We also need to translate the transitions. I.e. enter in db some string for the actions
Unpublish, Publish, etc.
Then translate the titles in transitions Manager with something like
```
										<?php echo $editIcon; ?><?php echo Text::_($item->title); ?>
											</a>
										<?php else: ?>
											<?php echo Text::_($item->title); ?>
										<?php endif; ?>
```
so basically we would have something like
```
INSERT INTO `#__workflow_transitions` (`id`, `asset_id`, `published`, `ordering`, `workflow_id`, `title`, `description`, `from_stage_id`, `to_stage_id`) VALUES
(1, 0, 1, 1, 1, 'JUNPUBLISH', '', -1, 1),
(2, 0, 1, 2, 1, 'JPUBLISH', '', -1, 2),
(3, 0, 1, 3, 1, 'JTRASH', '', -1, 3),
(4, 0, 1, 4, 1, 'JARCHIVE', '', -1, 4);
```
Is it worth chaning now db or do it in the next PR?

2018-08-24 05:27 UTC, infograf768 commented
Or do it in this PR?

2018-08-24 05:56 UTC, alikon commented
Yes we can do in a next PR,

Il ven 24 ago 2018, 07:28 infograf768 <notifications@github.com> ha scritto:

> Or do it in this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/21506#issuecomment-415655091>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AALFsUncU2NFikLUdWpf3BuGOLrdUC2Gks5uT47fgaJpZM4V2Qbn>
> .
>

2018-08-24 05:59 UTC, infograf768 commented
@bembelimen 
Your decision. If you do transitions in next PR, let's not forget @alikon necessary updated patch.

2018-08-24 22:50 UTC, bembelimen commented
Thanks @alikon for the PR

I would do the translation in a new PR, so we have small code changes.

2018-08-25 09:05 UTC, infograf768 commented
Drone error is unrelated to this PR.

@wilsonge Please merge.

2018-08-25 09:06 UTC, infograf768 commented
rtc
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21506">issues.joomla.org/tracker/joomla-cms/21506</a>.</sub>

2018-08-25 09:08 UTC, brianteeman commented
Whoever merges can you directly fix the drone error

2018-08-31 20:02 UTC, merged

2018-08-31 20:03 UTC, wilsonge commented
Thanks guys!