State to stage
joomla/joomla-cms pull request #21544
Opened 2018-08-10 18:41 UTC by chmst

Pull Request for Issue 21472.

### Summary of Changes
As the term "state" in the workflow is in conflict with the old "state" I have changed this term. 
This means a consequent renaming - Database table and columns, classes, views, comments, Language Keys and Strings, Fields, Plugins. 

The many changes need a good review and require a new installation of the test application due to database changes. Com_content craves special attention.

2018-08-10 18:53 UTC, brianteeman requested changes

2018-08-10 18:53 UTC, brianteeman commented on administrator/components/com_workflow/Model/TransitionModel.php
> +			$this->setError(Text::_('COM_WORKFLOW_MSG_FROM_TO_STAGE'));
You have correctly changed this hard coded english to a string but I dont see this string in the language file

2018-08-10 18:53 UTC, brianteeman commented on layouts/joomla/html/batch/workflowstage.php
> +<label id="batch-workflowstage-lbl" for="batch-workflowstage-id" class="modalTooltip" title="<?php echo JHtml::_('tooltipText', 'JLIB_HTML_BATCH_WORKFLOW_STAGE_LABEL', 'JLIB_HTML_BATCH_WORKFLOW_STAGE
you have changed the jlib strings but you havent changed them in the language fille

2018-08-10 18:53 UTC, brianteeman commented on plugins/content/joomla/joomla.php
> +	 * Change the stage in core_content if the stage in a table is changed
i assume that this was supposed to be com_content and not core_

2018-08-10 18:59 UTC, chmst commented on administrator/components/com_workflow/Model/TransitionModel.php
> +			$this->setError(Text::_('COM_WORKFLOW_MSG_FROM_TO_STAGE'));
It is in the language file, line 51

2018-08-10 19:02 UTC, brianteeman commented on administrator/components/com_workflow/Model/TransitionModel.php
> +			$this->setError(Text::_('COM_WORKFLOW_MSG_FROM_TO_STAGE'));
i need new glasses

2018-08-10 19:10 UTC, chmst commented on layouts/joomla/html/batch/workflowstage.php
> +<label id="batch-workflowstage-lbl" for="batch-workflowstage-id" class="modalTooltip" title="<?php echo JHtml::_('tooltipText', 'JLIB_HTML_BATCH_WORKFLOW_STAGE_LABEL', 'JLIB_HTML_BATCH_WORKFLOW_STAGE
touchée ;)

2018-08-10 19:15 UTC, brianteeman approved these changes
approve language string changes

2018-08-10 19:22 UTC, chmst commented on plugins/content/joomla/joomla.php
> +	 * Change the stage in core_content if the stage in a table is changed
I think it is the ucm_content table. Here we need tests, I am not sure about this.

2018-08-10 19:34 UTC, Quy commented on administrator/components/com_workflow/Controller/TransitionsController.php
> + * Workflow Transitions controler
Spelling `controler`

2018-08-10 19:34 UTC, Quy commented on administrator/components/com_workflow/Controller/WorkflowController.php
> + * Workflow controler
Spelling `controler`

2018-08-10 19:35 UTC, Quy commented on administrator/components/com_workflow/Controller/WorkflowsController.php
> + * Workflows controler
Spelling `controler`

2018-08-10 20:45 UTC, Quy commented on administrator/components/com_content/forms/filter_articles.xml
>  				label="COM_CONTENT_STATES"
Rename?

2018-08-10 20:45 UTC, Quy commented on administrator/components/com_content/forms/filter_featured.xml
>  				label="COM_CONTENT_STATES"
Rename?

2018-08-10 20:45 UTC, Quy commented on administrator/components/com_workflow/Controller/TransitionController.php
> +	 * The workflow where the transion takes place
spelling `transion`

2018-08-10 20:47 UTC, Quy commented on administrator/components/com_workflow/Table/StageTable.php
> +			$query = $db->getQuestage_idry(true)
`getQuestage_idry`??

2018-08-10 20:48 UTC, Quy commented on administrator/components/com_workflow/View/Stages/HtmlView.php
> +
Remove tab

2018-08-10 20:50 UTC, Quy commented on administrator/components/com_workflow/View/Stages/HtmlView.php
> +		ToolbarHelper::help('JHELP_WORKFLOW_STAGES_LIST');
Checking if this has been changed elsewhere since it is not in this PR.

2018-08-10 20:51 UTC, Quy commented on administrator/components/com_workflow/forms/filter_transitions.xml
> +			sql_select="id as value, title as from_staGe"
lowercase `from_staGe`

2018-08-10 20:51 UTC, Quy commented on administrator/components/com_workflow/forms/filter_transitions.xml
> +			sql_from="#__workflow_staGes"
lowercase `#__workflow_staGes`

2018-08-10 20:53 UTC, Quy commented on administrator/components/com_workflow/tmpl/workflows/default.php
> +									<a class="badge <?php echo ($item->count_states > 0) ? 'badge-warning' : 'badge-secondary'; ?>" title="<?php echo Text::_('COM_WORKFLOW_COUNT_STATES'); ?>" href="<?php echo Route::_('index.p
Change `COM_WORKFLOW_COUNT_STATES`

2018-08-11 18:57 UTC, wilsonge commented
@brianteeman is this approved language wise with the last fix?

2018-08-11 19:10 UTC, brianteeman commented
for now yes but dont want to spend too much time on it right now as so much will change - i hope

2018-08-11 22:47 UTC, merged

2018-08-11 22:47 UTC, wilsonge commented
Thanks!

2018-08-12 07:17 UTC, alikon commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +INSERT INTO `#__extensions` (`extension_id`, `package_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `checked_out`, `checked_out_
Why this change ??? on the extensions table

2018-08-12 07:25 UTC, infograf768 commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +INSERT INTO `#__extensions` (`extension_id`, `package_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `checked_out`, `checked_out_
Please revert this merge or correct at once.

@wilsonge 
PLEASE, PLEASE, PLEASE
STOP merging anything workflow related until the code is heavily corrected to take at least into account the "Enable workflows" parameter!!!

2018-08-12 07:36 UTC, richard67 reviewed
The change in line 117 of  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql is obviously wrong. There is no such change in the installation joomla.sql, and there are no such changes in the postgresql scripts.

2018-08-12 07:36 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +INSERT INTO `#__extensions` (`extension_id`, `package_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `checked_out`, `checked_out_
Yes, this field (table column) name in the extensions table is definitely wrong.