[4.0][WORKFLOW] POC fixing multilingual sample data
joomla/joomla-cms pull request #21553
Opened 2018-08-11 09:42 UTC by infograf768

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/21548

### Summary of Changes
Adapting multilingual sample data to workflow

### Testing Instructions
Patch tester should be OK.
Just do as usual, i.e. install some languages (French, German, Persian) and click install in CPanel

### Why is it a POC?

For the simple reason that the default workflow may have been changed or the "Joomla! Default" one in core (WHICH BTW should have as title a translatable language constant) modified, thus state 2 could be anything instead of "Published".

@bembelimen 
@franz-wohlkoenig

2018-08-11 10:09 UTC, franz-wohlkoenig commented
will test Today.

2018-08-11 10:32 UTC, franz-wohlkoenig commented
I have tested this item :white_check_mark: successfully on b1776f3c96a58f711a140a9c7c35d2dc69eebbf6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21553">issues.joomla.org/tracker/joomla-cms/21553</a>.</sub>

2018-08-11 10:37 UTC, bembelimen requested changes

2018-08-11 10:37 UTC, bembelimen commented on plugins/sampledata/multilang/multilang.php
> +			->where($db->quoteName('title') . ' = ' . $db->quote('Joomla! Default'));
I would not check for the ```title``` of the workflow but for the column ```default```, so you get a default workflow, when the user changes it. But you don't need any workflow ID in the category itself (which I wouldn't set), because the ```default``` is always the fallback.

2018-08-11 10:37 UTC, bembelimen commented on plugins/sampledata/multilang/multilang.php
> +			'params'          => '{"target":"","image":"", "workflow_id":"' . $workflowId . '"}',
I wouldn't set the workflow_id here. Just let it away, so the default will be used.

2018-08-11 10:37 UTC, bembelimen commented on plugins/sampledata/multilang/multilang.php
> +			->values($newId . ', 2,' . $db->quote('com_content'));
You should not use ```2``` as hardcode value, but you should take the ```default``` state (it's a column, too) from the pool of states which are part of the default-workflow (from above)

2018-08-11 16:16 UTC, infograf768 commented on plugins/sampledata/multilang/multilang.php
> +			->where($db->quoteName('title') . ' = ' . $db->quote('Joomla! Default'));
Ok, if I choose the column `default` and it is not containing the `published` state as I wish, what can I do?

2018-08-11 16:16 UTC, infograf768 commented on plugins/sampledata/multilang/multilang.php
> +			->values($newId . ', 2,' . $db->quote('com_content'));
what if that default state is NOT "published"?

2018-08-11 16:32 UTC, infograf768 commented on plugins/sampledata/multilang/multilang.php
> +			->values($newId . ', 2,' . $db->quote('com_content'));
looks like we have first to find which workflow is the default, and then which states are proposed by this default workflow, and then the correct condition "2" from which we have to find the id to use.

2018-08-12 05:51 UTC, infograf768 commented
+ evidently first check is workflows are Enabled...

2018-08-12 06:40 UTC, infograf768 commented on plugins/sampledata/multilang/multilang.php
> +			'params'          => '{"target":"","image":"", "workflow_id":"' . $workflowId . '"}',
If I do not need the workflow id, then I do not need either the query as its only purpose is to get that id.
What I need here is definitely to set the articles to Published, and set the category to use the correct workflow id where Published is the default or can be obtained.

But what if another workflow is set as default and it is not using Published as its default state?
![screen shot 2018-08-12 at 08 28 11](https://user-images.githubusercontent.com/869724/43999278-bcac1e46-9e09-11e8-9017-3fb9456d93e1.png)

That one has Unpublished as default state
![screen shot 2018-08-12 at 08 30 39](https://user-images.githubusercontent.com/869724/43999297-0d9724fe-9e0a-11e8-88c7-4458fcaa7942.png)

Therefore, basically, IF workflows IS enabled, I want to force using the default Joomla defaults which should NEVER be modifed or deleted. But we get there into other issues as we do not want save2copy to autopublish the copies, etc. which means Joomla Default workflow is not fit for save2copy....
A vicious circle...

2018-08-12 09:37 UTC, brianteeman commented
There is NO option to disable/enable workflows. You have no choice - this workflows pr completely replaces the current working system. 

That is why I am so insistent that the code is correct. The only reason that the current/previous states still exist in the com-content table is for b/c with extensions eg content-modules. Although that is not true either as it will only write published/unpublished/trashed into that table and will not write archived.

The option that you are thinking of works the same as the one for custom fields. ie it hides/shows the menu admin links. The logic being that once you have workflows setup then you don't need to see it again. Yes the language string for both needs to be improved.

If people spent the time to truly test this workflows stuff in a real world scenario they would see why it is not ready at all and will require fundamental changes before it can even be considered. The fact that it ignores the ACL is the most critical to me.

2018-08-12 10:17 UTC, alikon commented
after applying this pr still issues
![screenshot from 2018-08-12 12-16-59](https://user-images.githubusercontent.com/181681/44000976-b1f26f8a-9e29-11e8-9f6c-08a8ab87d85c.png)

2018-08-12 10:31 UTC, chmst commented
I had this too until I have  deleted the autoload file and repeated the composer / npm stuff.

2018-08-12 10:35 UTC, alikon commented
i've used nigthly build too..... so....there should be no need to run composer ect .i'm afraid something  is still  wrong after #21544

2018-08-12 11:51 UTC, Bakual commented
> There is NO option to disable/enable workflows. You have no choice - this workflows pr completely replaces the current working system.

There is an option in the com_content options. But all it does is hiding the workflow menuitem. Unfortunately, it doesn't disable workflows itself.

2018-08-12 11:57 UTC, brianteeman commented
We were told at jab that out of the box it would work the same as the status quo. Sadly that is clearly not the case at all especially with it ignoring the ACL

2018-08-12 14:21 UTC, Bakual commented
> with it ignoring the ACL

I brings its own ACL in the workflow and the transitions, making the ACL in the component itself quite redundant. Good luck with finding why someone suddenly can't publish thought.

2018-08-12 14:29 UTC, infograf768 commented
@alikon 
See https://github.com/joomla/joomla-cms/pull/21566 for new fixes...

2018-08-24 10:37 UTC, franz-wohlkoenig commented
is this PR waiting for a second Test or something else?

2018-08-25 09:14 UTC, infograf768 commented
> is this PR waiting for a second Test or something else?

Responsible for 4.0 development should decide.

I personally think we should wait a general solution to workflow.
For example: what happens if a workflow, including the default one, has been deleted?

2018-10-13 09:31 UTC, infograf768 commented
Closing as another code has taken care of this.

2018-10-13 09:31 UTC, closed without merging