State to stage fixes
joomla/joomla-cms pull request #21566
Opened 2018-08-12 13:35 UTC by chmst

Pull Request for Issue https://github.com/joomla/joomla-cms/pull/21553#issuecomment-412333785

### Summary of Changes
Some more fixes in this renaming task.
Rename the Field WorkfileState to Workfilestage

Thank you for all hints and for testing.

2018-08-12 16:25 UTC, HLeithner commented
There is a typo at
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_workflow/Model/TransitionsModel.php#L143-L144

The semicolon show be in the second line

2018-08-12 16:27 UTC, HLeithner commented
Also there seams to be missing string translations/renamings in transition
![image](https://user-images.githubusercontent.com/1497730/44004127-5467f91e-9e5d-11e8-86eb-9776238f801f.png)

2018-08-12 16:52 UTC, HLeithner commented
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_workflow/Table/StageTable.php#L69
should be $stage

2018-08-12 16:58 UTC, jeckodevelopment requested changes

2018-08-12 16:58 UTC, jeckodevelopment commented on modules/mod_articles_archive/mod_articles_archive.xml
>  					label="MOD_ARTICLES_ARCHIVE_CHOOSE_STATE"
`MOD_ARTICLES_ARCHIVE_CHOOSE_STATE` should be `MOD_ARTICLES_ARCHIVE_CHOOSE_STAGE`

2018-08-12 17:41 UTC, chmst commented on modules/mod_articles_archive/mod_articles_archive.xml
>  					label="MOD_ARTICLES_ARCHIVE_CHOOSE_STATE"
thx

2018-08-12 19:18 UTC, HLeithner commented
In the SQL update script you changed the last line

```sql
SELECT `id`, CASE WHEN `stage` = -2 THEN 3 WHEN `stage` = 0 THEN 1 WHEN `stage` = 2 THEN 4 ELSE 2 END, 'com_content' FROM `#__content`;
```

The stage column here references the state column in #__content so it have to stay `state`

2018-08-12 19:27 UTC, HLeithner commented
JHtmlWorkflowStage is missing, file and class is in lib/cms/html/workflowstate.php

2018-08-12 19:30 UTC, HLeithner commented
oh lib/cms/html/workflowstate.php only got converted partly.

In line 62 wrong name
```php
		$workflowStates = array();
```
in line 70 the first variable is wrong
```php
			if (!array_key_exists($workflowStateKey, $workflowStages))
```

2018-08-12 19:40 UTC, chmst commented
This file should have been replaced already by workflowstage. I'll Repeating the changes. Thank you.

2018-08-12 20:07 UTC, HLeithner commented
libraries/src/Form/Field/TransitionField.php

workflow_state is wrong, also in the query some lines later
```php
$workflowState = $this->element['workflow_state'] ? (int) $this->element['workflow_state'] : (int) $jinput->getInt('id', 0);
```

2018-08-12 20:10 UTC, HLeithner commented
administrator/components/com_content/Model/ArticleModel.php line 545 is crying Notice: Undefined property: stdClass::$state_id 

also it sets 'workflow_state' not sure if this is correct but I don't think so.

2018-08-12 20:20 UTC, HLeithner commented
administrator/components/com_content/Model/ArticleModel.php:827

```php
					->where($db->quoteName('wt.to_state_id') . ' = ' . $db->quoteName('ws.id'))
```
is wrong

2018-08-12 20:25 UTC, HLeithner commented
administrator/components/com_content/Model/ArticleModel.php:913
```
					$stateId = (int) $workflow->state_id;
```

administrator/components/com_content/Model/ArticleModel.php:1222
```
					->select($db->quoteName('ws.id', 'state_id'))
```

2018-08-13 00:30 UTC, wilsonge commented
You still can't save an article with this PR on :)

2018-08-13 02:58 UTC, infograf768 commented
Indeed
`Call to undefined method stdClass::createAssociation()`

2018-08-13 03:37 UTC, infograf768 commented
Checked: remain many occurences of $workflowState instead of $workflowStage, including the name of the file
`/libraries/cms/html/workflowstate.php` instead of `workflowstage.php`

Also `$stateId` instead of `$stageId`

After correcting these I can save articles here.

2018-08-13 04:36 UTC, infograf768 commented
This may help correcting $workflowState
```
/administrator/components/com_content/Model/ArticlesModel.php:322: 		$workflowState = (string) $this->getState('filter.state');
/administrator/components/com_content/Model/ArticlesModel.php:324: 		if (is_numeric($workflowState))
/administrator/components/com_content/Model/ArticlesModel.php:326: 			$query->where('wa.stage_id = ' . (int) $workflowState);
/administrator/components/com_content/Model/ArticlesModel.php:341: 		elseif (!is_numeric($workflowState))
/administrator/components/com_content/Model/FeaturedModel.php:160: 		$workflowState = (string) $this->getState('filter.state');
/administrator/components/com_content/Model/FeaturedModel.php:162: 		if (is_numeric($workflowState))
/administrator/components/com_content/Model/FeaturedModel.php:164: 			$query->where('wa.stage_id = ' . (int) $workflowState);
/administrator/components/com_content/Model/FeaturedModel.php:173: 		elseif (!is_numeric($workflowState))
```
and for `$stateId`
```
/administrator/components/com_content/Model/ArticleModel.php:891: 			if (empty($stateId))
/administrator/components/com_content/Model/ArticleModel.php:924: 				$workflow->createAssociation($this->getState($this->getName() . '.id'), (int) $stateId);
```

2018-08-13 11:29 UTC, infograf768 commented on administrator/components/com_content/Model/FeaturedModel.php
> +		$workflowStage = (string) $this->getStage('filter.state');
getStage ?

2018-08-13 11:38 UTC, chmst commented on administrator/components/com_content/Model/FeaturedModel.php
> +		$workflowStage = (string) $this->getStage('filter.state');
oops

2018-08-13 15:05 UTC, infograf768 commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +INSERT INTO `#__workflow_associations` (`item_id`, `state_id`, `extension`)
I guess it is `stage_id`

2018-08-13 15:11 UTC, chmst commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +INSERT INTO `#__workflow_associations` (`item_id`, `state_id`, `extension`)
thx

2018-08-13 15:20 UTC, infograf768 commented
Are Default transitions supposed to be this?
<img width="1507" alt="screen shot 2018-08-13 at 17 16 47" src="https://user-images.githubusercontent.com/869724/44041045-212d829c-9f1d-11e8-82b6-ae4149fa2828.png">

If yes, this PR is fine for me (have not tested all possibilities, but no major error.)

2018-08-13 15:26 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 9d4458c9100afa7a785189c61415eeb60898ea3d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21566">issues.joomla.org/tracker/joomla-cms/21566</a>.</sub>

2018-08-13 15:30 UTC, merged

2018-08-13 15:30 UTC, wilsonge commented
Thanks for all the great collaboration here guys :) much appreciated!

2018-08-13 15:47 UTC, HLeithner commented
I have tested this item :white_check_mark: successfully on 9d4458c9100afa7a785189c61415eeb60898ea3d<br /><br />No errors found so far.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21566">issues.joomla.org/tracker/joomla-cms/21566</a>.</sub>

2018-08-13 18:13 UTC, brianteeman commented
complete failure for me with 500 error as soon as you save an article

2018-08-13 18:16 UTC, HLeithner commented
do you have more debug information? for me this works perfectly :-(

2018-08-13 18:21 UTC, brianteeman commented
As soon as you create an article you get this everytime you try to go to 
administrator/index.php?option=com_content

Error 500:  JHtml workflowstage not found.
```

# | Function | Location
-- | -- | --
1 | () | JROOT\libraries\src\HTML\HTMLHelper.php:164
2 | Joomla\CMS\HTML\HTMLHelper::_() | JROOT\layouts\joomla\html\batch\workflowstage.php:31
3 | include() | JROOT\libraries\src\Layout\FileLayout.php:127
4 | Joomla\CMS\Layout\FileLayout->render() | JROOT\libraries\src\Layout\LayoutHelper.php:73
5 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT\administrator\components\com_content\tmpl\articles\default_batch_body.php:49
6 | include() | JROOT\libraries\src\MVC\View\HtmlView.php:386
7 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT\administrator\components\com_content\tmpl\articles\default.php:338
8 | include() | JROOT\libraries\src\MVC\View\HtmlView.php:386
9 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT\libraries\src\MVC\View\HtmlView.php:191
10 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT\administrator\components\com_content\View\Articles\HtmlView.php:149
11 | Joomla\Component\Content\Administrator\View\Articles\HtmlView->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:679
12 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\administrator\components\com_content\Controller\DisplayController.php:59
13 | Joomla\Component\Content\Administrator\Controller\DisplayController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:717
14 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\Dispatcher.php:162
15 | Joomla\CMS\Dispatcher\Dispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:354
16 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:111
17 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:154
18 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:242
19 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
20 | require_once() | JROOT\administrator\index.php:36


```

2018-08-13 18:28 UTC, mbabker commented
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/cms/html/workflowstage.php

This is environmentally broken.

Because this uses the Joomla autoloader, which is based on camel casing of class names, the class name MUST be `JHtmlWorkflowstage` otherwise it will NOT work consistently across environments.

OR, to keep the class casing the way it is, you must place the file at `libraries/cms/html/workflow/stage.php`.

2018-08-13 18:48 UTC, HLeithner commented
@mbabker but this doesn't seams to be the problem because the file called JHtml key is 'workflowstage.existing' and the file is also lowercase only the class is SnakeCase so whats the reason it works for me and not for brian?

2018-08-13 19:08 UTC, mbabker commented
And when (both of) you step through all the autoloaders and whatnot what path and class name are trying to be resolved?  This is PHP here, it is very well possible for the right file to be loaded in but the class still be considered missing (which is basically what this error is) because the JHtml library is expecting to find `JHtmlWorkflowstage` and the class is declared `JHtmlWorkflowStage`.

2018-08-13 19:36 UTC, HLeithner commented
So this should be fixed by this https://github.com/joomla/joomla-cms/pull/21597 PR.