[4.0] Layout systeminfo - improve accessibility
joomla/joomla-cms pull request #21628
Opened 2018-08-15 12:12 UTC by chmst

JAT has found several a11y issues in the SystemInformation View:

### Summary of Changes
Remove the <form> tag, as this is not a form.
Remove empty Table Footers
Replace the <fieldset> Tag by <div>
Replace the <legend> by Table <caption>

### Testing Instructions
There should be no visible difference in the View System Information before and after patch.

Test of accessibility with screenreader is required.

2018-08-15 12:30 UTC, brianteeman commented
> There should be no visible difference in the View System Information before and after patch.

unfortunately thats not correct - without some markup for the caption element the caption is displayed in muted text at the bottom of the screen. 
I would create a new sscss file here administrator\templates\atum\scss\pages\_com_admin.scss and add the markup there.

This will add the caption to the top - then you just need to address the font-size and wieght
```
caption {
  caption-side: top;
}
```

The rest looks good

2018-08-15 12:37 UTC, chmst commented
Thank ou @brianteeman. What do you think about adding the "caption-side: top" into one of the general scss files? If there are more tables, not only in com_admin, they all could have captions.

2018-08-15 12:47 UTC, brianteeman commented
Sure. That would work as well

2018-08-15 12:50 UTC, brianteeman commented
Correction to my last comment - 

although confusingly named 
`atum\scss\vendor\bootstrap 
`
is not their code it is our overrides of their code. So I would put it in the _table.scss file

2018-08-15 13:09 UTC, brianteeman reviewed
don't you think it needs some formatting eg bold etc

2018-08-15 13:18 UTC, chmst commented
To say the thruth: I think it does not need a caption or headline at all in this screen. The caption repeats the name of the tab and gives no information.

2018-08-15 14:39 UTC, Quy commented on administrator/components/com_admin/tmpl/sysinfo/default_phpinfo.php
>  	<legend><?php echo Text::_('COM_ADMIN_PHP_INFORMATION'); ?></legend>
There is no `fieldset` for this `legend`.

2018-08-15 15:08 UTC, brianteeman commented
> To say the thruth: I think it does not need a caption or headline at all in this screen. The caption repeats the name of the tab and gives no information.

Just checked other tabbed interfaces in joomla and they dont have titles either so you are correct

2018-08-16 10:51 UTC, brianteeman commented
If those strings are only.used here then they can be removed from the language files

2018-08-16 12:23 UTC, chmst commented
This are the Tab names. They were repeated in the Headline / caption.

2018-08-16 12:28 UTC, brianteeman commented
ok

2018-08-16 12:29 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 343c43f2d8bbaa13ee1fa104d2ab1729ac4d5ec3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21628">issues.joomla.org/tracker/joomla-cms/21628</a>.</sub>

2018-08-16 12:30 UTC, dgrammatiko requested changes

2018-08-16 12:30 UTC, dgrammatiko commented on administrator/components/com_admin/tmpl/sysinfo/default.php
> +		<?php echo HTMLHelper::_('bootstrap.addTab', 'myTab', 'site', Text::_('COM_ADMIN_SYSTEM_INFORMATION')); ?>
can you drop the bootstrap here and use the new one?

2018-08-16 12:30 UTC, dgrammatiko commented on administrator/components/com_admin/tmpl/sysinfo/default.php
> +		<?php echo HTMLHelper::_('bootstrap.addTab', 'myTab', 'site', Text::_('COM_ADMIN_SYSTEM_INFORMATION')); ?>
Also once you do this you can drop the tabstate at the begining

2018-08-16 12:31 UTC, brianteeman commented on administrator/components/com_admin/tmpl/sysinfo/default.php
> +		<?php echo HTMLHelper::_('bootstrap.addTab', 'myTab', 'site', Text::_('COM_ADMIN_SYSTEM_INFORMATION')); ?>
Lets leave that to a specific pr to remove the bs tabs everywhere please. 

One pr for one task

2018-08-19 14:47 UTC, closed without merging

2018-08-19 14:47 UTC, franz-wohlkoenig commented
closed as requested at #21724<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21628">issues.joomla.org/tracker/joomla-cms/21628</a>.</sub>