[4.0][Workflow] Remove com_content defaults from workflow code
joomla/joomla-cms pull request #21641
Opened 2018-08-16 12:42 UTC by HLeithner

This is a cleanup PR to remove com_content references

### Summary of Changes
Remove all 'com_content' constants from workflow code.

### Testing Instructions

Create, Delete, Edit

for  com_content
* articles

for com_workflow
* stages
* transitions
* workflows

### Expected result
All works fine

2018-08-16 13:10 UTC, HLeithner commented
This PR is based on https://github.com/joomla/joomla-cms/pull/21585

2018-08-16 13:27 UTC, brianteeman commented
I thought it looks familiar - so can you close that one please

2018-08-16 13:28 UTC, brianteeman commented on administrator/components/com_content/Model/FeaturedModel.php
> +use Joomla\Component\Content\Administrator\Extension\ContentComponent;
Please alphas sort

2018-08-16 13:35 UTC, brianteeman commented on libraries/src/Form/Field/WorkflowconditionField.php
> + *
please update the @package @subpackage

2018-08-16 13:37 UTC, brianteeman commented on libraries/src/Form/Field/WorkflowconditionField.php
> +	 * The extension where we're
please correct to we are

2018-08-16 13:54 UTC, HLeithner commented on libraries/src/Form/Field/WorkflowconditionField.php
> + *
Do we sill have this header? because all other Fields doen't have it. Anyway would be part of the other PR.

2018-08-16 13:57 UTC, mbabker commented on libraries/src/Form/Field/WorkflowconditionField.php
> + *
If you're adding a new file (as the GitHub diff seems to imply here) then the header really should be correct from the beginning.

2018-08-16 14:03 UTC, HLeithner commented on libraries/src/Form/Field/WorkflowconditionField.php
> +	 * The extension where we're
Change in Update in https://github.com/joomla/joomla-cms/pull/21585

2018-08-16 14:03 UTC, HLeithner commented on administrator/components/com_content/Model/FeaturedModel.php
> +use Joomla\Component\Content\Administrator\Extension\ContentComponent;
Change in Update in https://github.com/joomla/joomla-cms/pull/21585

2018-08-16 14:03 UTC, HLeithner commented on libraries/src/Form/Field/WorkflowconditionField.php
> + *
Change in Update in https://github.com/joomla/joomla-cms/pull/21585

2018-08-17 06:28 UTC, laoneo requested changes

2018-08-17 06:28 UTC, laoneo commented on administrator/components/com_content/Extension/ContentComponent.php
>  	public function countItems(array $items, string $section)
Will this code be the same for every extension which want's to implement workflow? If yes, please move it either to the CategoriesServiceTrait or the WorkflowServiceTrait. Otherwise every component needs to copy the same code.

2018-08-17 08:28 UTC, HLeithner commented on administrator/components/com_content/Extension/ContentComponent.php
>  	public function countItems(array $items, string $section)
This function exists already in several components in joomla it is/was in the helper class (com_fields-> FieldsHelper, com_contact ->ContactHelper, com_newsfeeds -> NewsfeedsHelper) also it was in the com_content helper and has been moved here by the parent PR https://github.com/joomla/joomla-cms/pull/21585

All countItems functions are different, countItems() is already implemented in CategoriesServiceTrait, but can't handle workflow conditions at the moment.

If its ok for you I would create a new PR to migrate all existing function to the component container and try to remove redundancy.

2018-08-17 08:40 UTC, laoneo commented on administrator/components/com_content/Extension/ContentComponent.php
>  	public function countItems(array $items, string $section)
Actually just look on com_content (or banners) as the others have not being migrated because of some open pull requests which would lead to conflicts. But they will use the CategoriesTrait as the countItems code is the same on all of them, except the table name. No need to copy things over and over again.

> All countItems functions are different

What is the difference? I mean all workflow related extensions will have the same code, except column and row names, or not?

2018-08-17 08:46 UTC, HLeithner commented on administrator/components/com_content/Extension/ContentComponent.php
>  	public function countItems(array $items, string $section)
I only skimmed the functions and the looked a bit different that's the reason why I would like to do this a separate PR for all components. I will do it after https://github.com/joomla/joomla-cms/pull/21585 is merged.

In the end hopefully all component uses the traits function

2018-08-17 08:59 UTC, laoneo commented on administrator/components/com_content/Extension/ContentComponent.php
>  	public function countItems(array $items, string $section)
When #20693 gets merged then I will do com_contact and com_newsfeeds. com_banners is already done and com_fields doesn't use categories at all.

2018-08-17 09:11 UTC, HLeithner commented on administrator/components/com_content/Extension/ContentComponent.php
>  	public function countItems(array $items, string $section)
com_workflow also have countItems but this does something different then the other components.

If com_fields doesn't use why we have the function in 
administrator/components/com_fields/helpers/fields.php:560

2018-08-17 09:15 UTC, laoneo commented on administrator/components/com_content/Extension/ContentComponent.php
>  	public function countItems(array $items, string $section)
It is dead code, should be removed as we have now groups.

2018-08-17 09:20 UTC, laoneo commented on administrator/components/com_content/Extension/ContentComponent.php
>  	public function countItems(array $items, string $section)
See #21663.

2018-08-17 12:41 UTC, HLeithner commented
So https://github.com/joomla/joomla-cms/pull/21585 is merged now this PR much smaller maybe I we get some testers here?

The countItems function rewrite @laoneo mentioned will get it's own PR.

2018-08-17 13:14 UTC, franz-wohlkoenig commented
I have tested this item :red_circle: unsuccessfully on 76535dc11b7522c924c23edcee091ceedfd68a84<br /><br />Delete an Stage got Error (Screenshot follows), but Stage is trashed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21641">issues.joomla.org/tracker/joomla-cms/21641</a>.</sub>

2018-08-17 13:29 UTC, HLeithner commented
> Delete an Stage got Error (see Screenshot), but Stage is trashed.

Not sure if this is related, does this not happen with the dev-4.0 branch?

2018-08-17 13:31 UTC, franz-wohlkoenig commented
it happen with applied Pull Request.

2018-08-17 13:51 UTC, HLeithner commented
This is unrelated seams to be a problem with state->stage renaming please open a new issue.

2018-08-17 15:52 UTC, wilsonge commented on libraries/src/Form/Field/TransitionField.php
> +	protected $workflowStage;
doc block for this please

2018-08-18 00:16 UTC, bembelimen commented
Not sure about this PR, the idea was to use com_content as fallback like in categories. If we remove this fallback (which is OK with me), we have to add checks and throw an error if extension is missing.

2018-08-18 07:51 UTC, HLeithner commented
There is ni reason to let com content be the fallback, this only makes it more error prone.

I found 3 places where a 3rd party component would fail to use the workflow because com_content was hardcoded or the default fallback.

In my opinion the same should be done for categories.

2018-08-18 12:33 UTC, wilsonge commented
I agree with this PR - we should remove com_content as the default but @bembelimen is correct we should probably hard bail if we can't find an extension.

2018-08-18 14:45 UTC, HLeithner commented
Sure it should have correct amd useful error messages I will adopt this PR

2018-08-23 08:50 UTC, wilsonge commented on administrator/components/com_workflow/Controller/StagesController.php
> +	public function __construct($config = array(), MVCFactoryInterface $factory = null, $app = null, $input = null)
why remove the array typehint?

2018-08-23 08:51 UTC, wilsonge commented on administrator/components/com_workflow/Controller/StagesController.php
> +				. $extensionURL . '&workflow_id=' . $this->workflowId, false
You just deleted `$extensionURL`

2018-09-08 09:10 UTC, HLeithner commented on administrator/components/com_workflow/Controller/StagesController.php
> +	public function __construct($config = array(), MVCFactoryInterface $factory = null, $app = null, $input = null)
phpstorm 1 me 0

2018-09-08 09:10 UTC, HLeithner commented on administrator/components/com_workflow/Controller/StagesController.php
> +				. $extensionURL . '&workflow_id=' . $this->workflowId, false
$extensionURL will be removed

2018-09-08 09:58 UTC, merged

2018-09-08 09:58 UTC, wilsonge commented
LGTM!

2018-09-08 10:41 UTC, HLeithner commented
that was a bit too early... I create a new PR fixing 2 things