Adaptive Image Plugin : New Media Manager
joomla/joomla-cms pull request #21775
Opened 2018-08-21 02:00 UTC by proman24

### Summary of Changes
The main objective of this extension is to preserve the important message associated with the image, by providing the user a way to add the focus area for the image. Images are being made responsive with the help of this extension.

#### Features

- Provided a focus editor for taking in the focus information from the author, in a more intuitive manner.
- Auto-Cropping of the images according to the viewport of the client device.
- The cropping is done around the focus area selected by the author.
- Author can select particular widths for which the images need to be cropped.
- Author can select different focus for different devices.
- Author can also remove all the resized images and the previous set focus points for a particular image from the focus editor.
- If an author deletes the original image from the media manager, its resized image and the focus points would be deleted too.

[Demo Video](https://www.youtube.com/watch?v=xOi37m3jwWw)
[Documentation](https://docs.joomla.org/J4.x:Adaptive_Images_for_Media_Manager)

**Note : This features can not be tested now because of [this](https://github.com/joomla-projects/media-manager-improvement/issues/577) issue.**

But after this got resolved one can test this feature by following these simple steps 

### Testing Instructions

1. After pulling this PR to the local repository, Fresh install Joomla (Just delete ```configuration.php```) or you can discover and enable the following plugin in the system through plugin extension manager:

	- Focus (Media-Action Plugin)
	- adaptiveimage (Content Plugin)

2. After the setup go to Media-Manager --> Edit any Image --> Go to focus tab.

3. Here you need to select a focus area for the image .

4. After selecting focus area Just hit *Save and Close*.

5. Finally, add that image to the article.

6. Then, Go to that article in the front-end and try changing the window size for the article.

### Expected result

The cropped and smaller images around the focus area would be shown for  smaller view ports.

**More Information about the features and instruction to use them for this plugin is given in documentation [here](https://docs.joomla.org/J4.x:Adaptive_Images_for_Media_Manager)**

2018-08-21 02:47 UTC, kasvith commented
@laoneo @dneukirchen @dgrammatiko @ciar4n it would be great if you guys do some review

2018-08-21 07:26 UTC, brianteeman commented
@kasvith kind of hard to test because as @proman24 days it cant be tested because of https://github.com/joomla-projects/media-manager-improvement/issues/577

2018-08-21 07:27 UTC, brianteeman commented on .gitignore
> +/plugins/media-action/focus/data/*
Why is this folder in the gitignore?

2018-08-21 07:27 UTC, brianteeman commented on administrator/components/com_media/src/Controller/AdaptiveImageController.php
> +use Joomla\CMS\Uri\Uri;
Please alpha sort these use statements

2018-08-21 07:29 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_content_adaptiveimage.ini
> +
did you mean to commit thiis without any strings?

2018-08-21 07:29 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_media-action_focus.sys.ini
> +PLG_MEDIA-ACTION_FOCUS_FIELD-SET_DESCRIPTION="Resizes images to these widths, setting them to the default"
Please add a . to the end

2018-08-21 07:30 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_media-action_focus.sys.ini
> +PLG_MEDIA-ACTION_FOCUS_XML_DESCRIPTION="Plugin which automatically resize and crop the images in the responsive environment"
==> resizes
==> crops
in the ==> in a ??

Please alpha sort these use statements

2018-08-21 07:31 UTC, brianteeman commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> + * @subpackage  com_media
package and subpackage need updating

2018-08-21 07:31 UTC, brianteeman commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> +	 * Pubic function for storeing the focus points
==>storing

2018-08-21 07:32 UTC, brianteeman commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> +	 * Function for removeing the focus points for all widths
==>removing

2018-08-21 07:32 UTC, brianteeman commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> +	 * Function for removeing all the associated resized images
==>removing

2018-08-21 07:32 UTC, brianteeman commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> + * @subpackage  com_media
package and subpackage need updating

2018-08-21 07:33 UTC, brianteeman commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
add a new line

2018-08-21 07:33 UTC, brianteeman commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * Function for removeing the focus points for all widths
removing

2018-08-21 07:34 UTC, brianteeman commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * Function for removeing all the associated resized images
removing

2018-08-21 07:34 UTC, brianteeman commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * Check whether the file exist
exists

2018-08-21 07:34 UTC, brianteeman commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * Fine the max value of all the focus area selected
Find
areas

2018-08-21 07:35 UTC, brianteeman commented on libraries/src/AdaptiveImage/SmartCrop.php
> + * @subpackage  com_media
package and subpackage need updating

2018-08-21 07:37 UTC, brianteeman commented on libraries/src/AdaptiveImage/SmartCrop.php
> +			mkdir($this->dataLocation, 0777);
This is wrong and must be changed

2018-08-21 07:38 UTC, brianteeman commented on media/plg_media-action_focus/js/focus.js
> +	// Saveing the focus points to the storage
saving

2018-08-21 07:39 UTC, brianteeman commented on plugins/content/adaptiveimage/adaptiveimage.php
> +
Please alpha sort the use statements

2018-08-21 07:40 UTC, brianteeman commented on plugins/content/adaptiveimage/adaptiveimage.php
> +	/**
add new line

2018-08-21 07:40 UTC, brianteeman commented on plugins/content/adaptiveimage/adaptiveimage.php
> +		// Add ResponsifyJS into the client page
I assume this comment is out of date

2018-08-21 07:41 UTC, brianteeman commented on plugins/content/adaptiveimage/adaptiveimage.php
> +			// Arrangeing widths in the order
arranging

2018-08-21 07:42 UTC, brianteeman commented on plugins/content/adaptiveimage/adaptiveimage.php
> +			// Skiping if no resized images are present
skipping

2018-08-21 07:42 UTC, brianteeman commented on plugins/content/adaptiveimage/adaptiveimage.php
> +			// Replaceing the previous tag with new one in the article.
replacing

2018-08-21 07:43 UTC, brianteeman commented on plugins/media-action/focus/focus.php
> +use Joomla\CMS\Factory;
Please alpha sort thee use statements

2018-08-21 07:44 UTC, brianteeman commented on plugins/media-action/focus/focus.php
> +		\JHtml::_(
Shouldnt this be HTMLHelper::

2018-08-21 07:44 UTC, brianteeman commented on plugins/media-action/focus/focus.php
> +		\JHtml::_(
Shouldnt this be HTMLHelper::

2018-08-21 07:44 UTC, brianteeman commented on plugins/media-action/focus/focus.xml
> +        <!--folder>responsifyjs</folder-->
please remove this commented code

2018-08-21 07:48 UTC, brianteeman commented on plugins/media-action/focus/form/focus.xml
> +			pattern="\d*\.?\d*"
When you have a pattern you should have associated message so that a user will know why it didnt validate eg 	`validationtext="PLG_MEDIA-ACTION_FOCUS_PARAM_X_ERRO`R"

2018-08-21 07:49 UTC, brianteeman commented on plugins/media-action/focus/form/focus.xml
> +			pattern="\d*\.?\d*"
And the same for everywhere you use a patterrn

2018-08-21 08:24 UTC, ghost commented
Error on installing PR: `The file marked for modification does not exist: package-lock.json`

2018-08-21 09:14 UTC, proman24 commented
@franz-wohlkoenig just pushed a commit, that might solve the issue

2018-08-21 09:17 UTC, proman24 commented on .gitignore
> +/plugins/media-action/focus/data/*
This folder stores the cache / cropped images.

2018-08-21 09:25 UTC, brianteeman commented on .gitignore
> +/plugins/media-action/focus/data/*
I thought that might be the case - which means it is in the wrong place and should be a subfolder of  /media

2018-08-21 09:32 UTC, proman24 commented on .gitignore
> +/plugins/media-action/focus/data/*
Sorry, wrongly said.... *Cache / Cropped images are stored in ```/media/focus/*```*
Actually this folder contains the data-focus points associated with the images in JSON format. Currently we are using file-system to store the mapping of focus points and the images.

2018-08-21 09:32 UTC, franz-wohlkoenig commented
@proman24 no change, same Error. Maybe it depends that Test using Patchtester didn't work in this Case too.

2018-08-21 09:36 UTC, brianteeman commented on .gitignore
> +/plugins/media-action/focus/data/*
we still shouldnt be storing user created anything in this location

2018-08-21 09:49 UTC, wojsmol commented
@franz-wohlkoenig This PR is bot passible to test on nightly builds because `package-lock.json` is excluded from builds

2018-08-21 10:57 UTC, proman24 commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> + * @subpackage  com_media
package  =>  Joomla
subpackage  => AdaptiveImage ??

2018-08-21 11:04 UTC, brianteeman commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> + * @subpackage  com_media
actually both can be removed

2018-08-21 11:14 UTC, proman24 commented on libraries/src/AdaptiveImage/SmartCrop.php
> +			mkdir($this->dataLocation, 0777);
Is there any inbuilt function for performing this operation?

2018-08-21 11:29 UTC, brianteeman commented on libraries/src/AdaptiveImage/SmartCrop.php
> +			mkdir($this->dataLocation, 0777);
Take a look at how folders are created elsewhere such as the template manager. Your mentor really should have spotted this 0777 permission and advised you.

2018-08-21 22:59 UTC, Anu1601CS commented on media/com_media/js/edit-images.js
> +/**
Move `js` file according to #21328

2018-08-21 23:00 UTC, Anu1601CS commented on media/com_media/js/edit-images.min.js
> +Joomla=window.Joomla||{},Joomla.MediaManager=Joomla.MediaManager||{},function(){"use strict";var e=Joomla.getOptions("com_media",{});if(!e)throw new Error('Initialization error "edit-images.js"');Joo
Same here.

2018-08-21 23:00 UTC, Anu1601CS commented on media/plg_media-action_focus/css/focus.css
> +/* This is the CSS File for Smart Crop */
Same here

2018-08-21 23:01 UTC, Anu1601CS commented on media/plg_media-action_focus/css/focus.min.css
> +#attrib-smartcrop{overflow-y:auto}
Same here

2018-08-21 23:01 UTC, Anu1601CS commented on media/plg_media-action_focus/js/focus.js
> +/**
Same here

2018-08-21 23:04 UTC, Anu1601CS commented
@proman24 Great work :)  Check few comments I left. And, its good   if you can create `.es6.js` version of `js` file.

2018-08-22 03:55 UTC, proman24 commented
Thank you @Anu1601CS for reviewing, I'll do the changes ASAP.

2018-08-22 07:52 UTC, proman24 commented on media/com_media/js/edit-images.js
> +/**
Ok this may be removed, as it is already present in ```build/media_src/com_media/js/edit-images.es6.js```

2018-08-22 12:49 UTC, Anu1601CS commented on media/com_media/js/edit-images.js
> +/**
@proman24 I would so then.

2018-08-25 18:29 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
CS, one more line.

2018-08-25 18:29 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	}
CS, one more line.

2018-08-25 18:29 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
CS, one more line.

2018-08-25 18:29 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
CS, one more line.

2018-08-25 18:29 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
CS, one more line.

2018-08-25 18:30 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +}
CS, one more line.

2018-08-25 18:30 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/SmartCrop.php
> +	/**
CS, one more line.

2018-08-25 18:30 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/SmartCrop.php
> +	public $image;
CS, one more line.

2018-08-25 18:32 UTC, Anu1601CS commented on plugins/content/adaptiveimage/adaptiveimage.php
> +	/**
CS, one more line.

2018-08-25 19:23 UTC, Quy commented on administrator/components/com_media/src/Controller/AdaptiveImageController.php
> +
Remove tabs. Repeat in other locations/files.

2018-08-26 21:40 UTC, Anu1601CS commented on package-lock.json
> +    "uglify-js": {
@proman24 Are you using this package in your project?

2018-08-26 21:43 UTC, Anu1601CS commented
@dgrammatiko Changes in `administrator/components/com_media/package-lock.json` is correct ?

@proman24 Why changes occurs ? in  `administrator/components/com_media/package-lock.json`

2018-08-26 21:50 UTC, Anu1601CS commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +			file_put_contents(static::$dataLocation, json_encode($newEntry));
Can we use `File::write` core API for this ?

2018-08-27 02:14 UTC, proman24 commented on package-lock.json
> +    "uglify-js": {
No, I am not using this one.

2018-08-27 02:18 UTC, geetanshu-m commented
@Anu1601CS  No idea why ```administrator/components/com_media/package-lock.json``` is changing, I have not used any NPM packages in the plugin.

2018-08-27 02:20 UTC, geetanshu-m commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +			file_put_contents(static::$dataLocation, json_encode($newEntry));
Will update this one 💯

2018-08-27 03:46 UTC, Anu1601CS commented
>  @Anu1601CS No idea why administrator/components/com_media/package-lock.json is changing, I have not used any NPM packages in the plugin.

Then better to revert the changes you have not done!

2018-08-27 05:10 UTC, kasvith commented on package-lock.json
> +    "uglify-js": {
this PR also contains changes from the upstream i guess

2018-08-27 18:46 UTC, Anu1601CS commented on package-lock.json
> +    "uglify-js": {
@kasvith Upstream mean media manager repo?

2018-08-27 18:53 UTC, kasvith commented on package-lock.json
> +    "uglify-js": {
No this one, @proman24 you reverted changes and pulled from this repo right? it seems pakacge-lock.json is excluded from builds, maybe @proman24 can pull again

2018-09-08 10:59 UTC, coolcat-creations commented
I have tested this item :red_circle: unsuccessfully on 494e1d79ea95bd74da5e49523df98a54c3b36c12<br /><br />- Loading time is quite long
- Focus is not respected at resizing.
But very very cool feature!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21775">issues.joomla.org/tracker/joomla-cms/21775</a>.</sub>

2018-09-08 11:17 UTC, ka3media commented
Tested on alpha5.

Don't work for me neither. As long as I'm on the "focus" tab, "save" or "save and close" do not work.

2018-09-08 11:44 UTC, franz-wohlkoenig commented
@ka3media please mark your Test as unsuccessfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/21775)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as unsuccessfully
- hit "submit test result"

2018-09-08 11:47 UTC, ka3media commented
I have tested this item :red_circle: unsuccessfully on 494e1d79ea95bd74da5e49523df98a54c3b36c12<br /><br />Tested on alpha5.

Don't work for me neither. As long as I'm on the "focus" tab, "save" or "save and close" do not work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21775">issues.joomla.org/tracker/joomla-cms/21775</a>.</sub>

2018-09-08 20:30 UTC, Anu1601CS commented
@proman24 It's good if you can give small time here in your project PR :)

2018-09-08 20:43 UTC, coolcat-creations commented
It would be really a great and professional feature!

2018-09-09 06:23 UTC, geetanshu-m commented
Thanks for testing @coolcat-creations @ka3media. :-)
Feature is not functional now on this branch because of [this](https://github.com/joomla-projects/media-manager-improvement/issues/577) issue. 
But, you can check out the working feature at [this](https://github.com/proman24/gsoc18_adaptive_images) repo **master** branch. 
Would be correcting the issues with this PR once the [template issue](https://github.com/joomla-projects/media-manager-improvement/issues/577) is resolved, cause as of now I am able to test the integrations.

2018-12-03 20:34 UTC, micker commented
impressive feature !!!! hope will be added !

2019-10-01 16:37 UTC, simbus82 commented
Hi guys... this is probably one of most important features for let J4 be adopted by more "admin users", copywriters, website managers, etc.

> Would be correcting the issues with this PR once the [template issue](https://github.com/joomla-projects/media-manager-improvement/issues/577) is resolved, cause as of now I am able to test the integrations.

I hope @proman24 can check if the problem was solved ...

2019-10-19 11:36 UTC, uglyeoin commented
@proman24 what is the status of this PR?  It's a great feature, I'm here to test for you.

2019-10-19 11:46 UTC, uglyeoin commented
@proman24 I cannot replicate https://github.com/joomla-projects/media-manager-improvement/issues/577 which may mean it has been resolved somewhere.

2019-10-19 11:51 UTC, uglyeoin commented
@proman24 using patch tester I have added this patch and it does not show me the additional tab that you mention.  As you have mentioned there is no requirement for NPM I will need further instructions.  Thanks so much for this really nice addition to Joomla.  Tag me and I will test it again when I have further information.

2019-10-19 11:52 UTC, uglyeoin commented
I have tested this item :red_circle: unsuccessfully on 494e1d79ea95bd74da5e49523df98a54c3b36c12<br /><br />Applying the patch did not bring this tab up.  So test failed.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21775">issues.joomla.org/tracker/joomla-cms/21775</a>.</sub>

2019-10-20 08:56 UTC, proman24 commented
@uglyeoin thanks for testing this PR and verifying other issues too[which was affecting this PR]. I am looking into this PR and resolving the issues with it.

2019-10-20 12:19 UTC, uglyeoin commented
@proman24 you the man, I can't wait to test it again.

2019-10-24 18:00 UTC, proman24 commented
@uglyeoin just pushed some commits, can you please test the PR. Thanks!

2019-10-24 18:26 UTC, dgrammatiko requested changes

2019-10-24 18:26 UTC, dgrammatiko commented on media/com_media/js/edit-images.js
> +/**
This is not resolved. Same goes for the other js file

2019-10-25 18:26 UTC, uglyeoin commented
@proman24 I applied the patch in patch tester and I did not see the tab in media manager when editing and image.  Do I need to run NPM?

2019-10-25 18:42 UTC, proman24 commented
GOTO Administrator->System->Install->Discover

Install 
- Adaptive image content plugin 
- Media action focus

2019-10-26 14:29 UTC, uglyeoin commented
I did that, I found both and installed both.  I still don't see the focus tab.  
![image](https://user-images.githubusercontent.com/4665225/67621142-61274800-f805-11e9-9784-7e2334942f45.png)

2019-10-26 14:31 UTC, uglyeoin commented
Ignore that I published the plugins now too

2019-10-26 14:36 UTC, uglyeoin commented
If I may make a suggestion.  It is only possible to have the focus in a rectangle.  Possibly because of the original shape of my image.  One of the great features of the <picture> element is that you can change the art direction.  Which may mean that on mobile for example I do not want a landscape rectangle but instead a portrait image.  Does that make sense?

2019-10-26 14:37 UTC, uglyeoin commented
I have tested this item :white_check_mark: successfully on cfa97a1eca668d7c207a5c0b2df64aac00930763<br /><br />It works but I have suggested an improvement.  I have tested on the front end and the back end.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21775">issues.joomla.org/tracker/joomla-cms/21775</a>.</sub>

2019-10-26 14:42 UTC, uglyeoin commented
I don't know if this should be part of this pull request or not, I suspect not.  But another great benefit of the `<picture>` element is that you can use fallback images, such as WebP.  I have no idea how you would achieve that with the media manager but in the long run I think that's the direction we should be taking.  You can see an example we made here: https://dev.joomlalondon.co.uk/ (site isn't finished yet).

2019-10-26 15:00 UTC, Quy commented on administrator/components/com_media/src/Controller/AdaptiveImageController.php
> +		return true;
```suggestion

		return true;
```

2019-10-26 15:01 UTC, Quy commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
```suggestion

	/**
```

2019-10-26 15:01 UTC, Quy commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
```suggestion

	/**
```

2019-10-26 15:01 UTC, Quy commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +		return true;
```suggestion

		return true;
```

2019-10-26 15:02 UTC, Quy commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
```suggestion

	/**
```

2019-10-26 15:02 UTC, Quy commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +		return $maxFocus;
```suggestion

		return $maxFocus;
```

2019-10-26 15:02 UTC, Quy commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	/**
```suggestion

	/**
```

2019-10-26 15:02 UTC, Quy commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +		return true;
```suggestion

		return true;
```

2019-10-26 15:03 UTC, Quy commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +		$maxFocus = array(
```suggestion

		$maxFocus = array(
```

2019-10-26 15:03 UTC, Quy commented on libraries/src/AdaptiveImage/SmartCrop.php
> +defined('_JEXEC') or die;
```suggestion

defined('_JEXEC') or die;
```

2019-10-26 15:03 UTC, Quy commented on libraries/src/AdaptiveImage/SmartCrop.php
> +/**
```suggestion

/**
```

2019-10-28 13:08 UTC, uglyeoin commented
@proman24 great work, let me know when you need me to test again.

2020-04-11 12:19 UTC, uglyeoin commented
@proman24 is this ready to test?

2020-04-11 14:52 UTC, uglyeoin commented
@proman24 when I use this I can change the focus but it always needs to be at the same aspect ratio as the original.  So if it's a landscape image it needs to remain landscape, but on a phone I would often want the image to be portrait.  Is there a way to change that?

2020-04-11 18:31 UTC, proman24 commented
@uglyeoin plugin was working as expected, as tested on 8c2afdb. @Quy @brianteeman can you please review the code so that It can be merged.

2020-04-11 18:40 UTC, proman24 commented
@uglyeoin In ```SmartCrop.php``` in compute function, I am taking the required width as the parameter, and cropping the image according to their original aspect ratio, another parameter -- like aspect ratio can be passed in this function to satisfy this requirement. Also, some minor changes in the content plugin can be done to judge whether to show landscape / mobile cropped images.

2020-04-11 18:48 UTC, alikon commented
on a 1st look you need to add the relative installation & update sql files for these plugins

2020-04-11 18:56 UTC, dgrammatiko commented
> on a 1st look you need to add the relative installation & update sql files for these plugins

There are few of my comments that are not addressed: 
- The js files are in the wrong place `media/com_media/js/edit-images.js`
- with wrong ext  `.es6.js`
- same for css...

But on a quick glance this is totally useless:
- The ux is not 2020 (upload the file, then go select the file apply the crop... WTF???), actually the ux is not even considered...
- Although it is built upon my code: https://github.com/ttc-freebies/plugin-responsive-images this is seriously not the ideal plugin for the core implementation of srcsets.
- The JSON file as a storage is a no-no from anyone that did anything that was supposed to sustain a load (some 10000 of files in this case)


In sort this is not FIT or either not production READY.

There you have it, someone said it...

2020-04-11 19:23 UTC, uglyeoin commented
@dgrammatiko thank you for your feedback.  I accept you as an authoritative voice, but perhaps the voice could have been slightly gentler.  Let's try to offer solutions as well as problems and be mindful that someone has put a lot of work and time into this.  

I don't think the UX is perfect either, but I don't have a suggestion on how to improve it which is why I have not mentioned this.  Do we have a UX team?

I personally believe we should be using `<picture>` not `srcsets` as `<picture>` can incorporate `srcsets` as well as cropping and also offering other image formats such as `webp` with `jpeg` as a fallback.  

I don't think we can use the current system - one image to serve all viewports - so we do need a solution if we are to be a modern CMS.

2020-04-11 19:34 UTC, dgrammatiko commented
> I personally believe we should be using <picture> not srcsets as <picture> can incorporate srcsets as well as cropping and also offering other image formats such as webp with jpeg as a fallback.

That's implementation detail, yes picture elements are better nowadays

> I don't think we can use the current system - one image to serve all viewports - so we do need a solution if we are to be a modern CMS.

Yes the CMS needs a way to have thumbnails or sets of images per given breakpoints (srcsets). What the CMS doesn't have to provide as it's a way to niche solution (very few will actually either use it) is a cropped thumbs per breakpoint (eg this is providing only one cropped version, someone could argue why not have an individually cropped image per breakpoint?). See my point?

> I don't think the UX is perfect either, but I don't have a suggestion on how to improve it which is why I have not mentioned this. 

Well it's easy: instead of waiting the user to come back for this functionality provide it whenever there is an upload. Simple as that...

> but perhaps the voice could have been slightly gentler.

Sorry not sorry for expressing honest opinion here. Truth hurts sometimes...

2020-04-13 15:56 UTC, uglyeoin commented
> Sorry not sorry for expressing honest opinion here. Truth hurts sometimes...
I didn't say don't express an opinion, they are vital for driving the project forwards.  I just implied it could be expressed in a more considerate way.  Your original post reads as this is dead wood and should not be worked on.  

Simply by suggesting in more detail what the issues are and how they may be overcome is a lot more objective.  

By saying "if this was offered on file upload it would be a better implementation" it would be taken less badly than "sorry this is totally useless".  Someone spent time on this, we should be grateful, even if we don't use it.  If there are better solutions, suggest them as options, an objective way.

2020-04-13 17:01 UTC, dgrammatiko commented
> Your original post reads as this is dead wood and should not be worked on.

Not "as if this is dead", I say it very clearly!!!

Let me explain:
- Architecturally: it fails, not fixable unless rewritten
- UX: it fails, not fixable unless rewritten
- A11y: it fails, removes blindly the alt attributes (actually will remove any attributes except the src)...

It's pretty straight forward: this is not for Prime time...

2020-04-14 11:44 UTC, uglyeoin commented
It would be better to say things objectively is my only point.  If code doesn't fit the requirements the project should not be obliged to accept it.  By explaining what would make it acceptable the original author or someone else may decide to take the job on.  Without that clarity, strong statements such as "this is totally useless" demoralise people who have taken time to contribute.

It is still currently better than nothing, albeit I'm not a fan of accepting things for that reason.  So many would say it is not **totally** useless, or even useless.

Your "do it on upload" solution brings with it the problem of needing to change media queries or edit crops when a template changes (or for any other reason), so we still need another way to edit things if we take that route forward.

UX should not be the opinion of one person, it should be a data driven, testable process.  

In any case, people have written code & documentation, we can still be grateful to the original author for his work (thank you @proman24 ).  To avoid wasting people's time, we should get an overriding decision on how to move forwards.  I don't know who is in charge of that. It would also be good to define tasks better up front rather than afterwards if that is at all possible.

2020-04-14 11:55 UTC, dgrammatiko commented
> It is still currently better than nothing, albeit I'm not a fan of accepting things for that reason. So many would say it is not totally useless, or even useless.

And this is how Joomla end it up where it is now, by accepting code that should have been rejected

FWIW I've helped the author of this PR to complete his GSOC task but I wasn't his mentor neither I was involved in the architectural, design or UX decisions. In sort there are things that could be salvaged and then there are things that would take far less time to be done from clean sheet. This in my humble opinion is falling to the second category, it's far easier to write a proper thingy than try to make this work properly...

My 2c and I'm off this thread...

2020-04-14 22:42 UTC, proman24 commented
> The ux is not 2020 (upload the file, then go select the file apply the crop... WTF???), actually the ux is not even considered...

Without giving a way to users to select the focus area how are we taking in the focus? I don't think of any other way. Also, this is not mandatory for all the images only those which author required, just like other tabs in the modal, crop/rotate.

> Although it is built upon my code: https://github.com/ttc-freebies/plugin-responsive-images

Totaly no clue about this thing. And I strongly disagree with this false accusation of plagiarism, anyways.

> The JSON file as storage is a no-no from anyone that did anything that was supposed to sustain a load (some 10000 of files in this case)

At the time of development, the media-manager was not using any database, so upon discussion, we decided to go with a JSON store. So that after this thing is functional, DB class can be written in the near future.

> Well it's easy: instead of waiting the user to come back for this functionality provide it whenever there is an upload. Simple as that...

The main idea was to provide the user with a way to set the focus of the image, and process image according to the focus area

> Yes the CMS needs a way to have thumbnails or sets of images per given breakpoints (srcsets). What the CMS doesn't have to provide as it's a way to niche solution (very few will actually either use it) is a cropped thumbs per breakpoint (eg this is providing only one cropped version, someone could argue why not have an individually cropped image per breakpoint?). See my point?

I not getting what are you trying to say here, In this plugin, we are cropping the image for individual breakpoints around the focus defined by the user.

Everything was very well discussed and iteratively developed, under the mentorship of @nibra  @kasvith, So, giving conclusive statement like the whole design of the plugin is wrong, would not be fair-- ``` it's far easier to write a proper thingy than try to make this work properly```, ``` a quick glance this is totally useless```,```this is not FIT or either not production READY``` . I believe that there might be some holes in the plugin which could be filled up but claiming it to be wholly wrong doesn't seem to be worthy for the time and efforts put in by me and the mentors.


@dgrammatiko  after your comment on the [first evaluation blog](https://twitter.com/Joomla_GSoC/status/1011580292715302912), I messaged you directly for knowing where is this thing going wrong. But that was a very short and discontinued discussion.

There were some delays in testing and getting the PR merged in 2018 because of some other underlying issue which I stated in the description of the PR. But **I am more than interested in getting this PR merged in Joomla** not only because I have spent more than 4 months in the development of this plugin, but also I believe that this is a really good add-on to Joomla's core. 

It would be great if someone can help me in figuring out what exactly are the changes needs to be done (rather than saying architecturally wrong) and what can be done in this plugin for making it production-ready.

Also, before continuing with the development we should get the vote weather to continue developing this plugin the way it is defined in this PR. Or there is some better way to achieve the objective. If yes, then it would be a good idea to close this PR.

@laoneo @brianteeman @ciar4n @Quy @nibra @kasvith @dneukirchen

2020-08-01 15:51 UTC, roland-d commented
@wilsonge Any use in continuing development of this feature?

2020-10-17 16:54 UTC, wilsonge commented
Yes I definitely would like to see a version of this make it in - clearly needs some work though. So as a starting point would be good to merge in latest 4.0-dev and move the media folders into the build/media_source directory. I'm just spinning this up locally now to do some testing and figure out the next steps beyond that.

2020-10-20 08:39 UTC, kasvith commented
As @proman24 mentioned the plugin uses JSON store because NMM did not use any database at that time. But the plugin itself does not care what is the storage system for these data. It can be MySQL, Firebase, Postgres whatever we want if we have a need in future. Also IMHO since there arent any frequent updates JSON still fits pretty fine there(we can introduce a new storage system if we getting issues after releasing to beta).

As @nibra and I can clearly say, @proman24 has put a great effort into this project. Let's not waste his effort. 

- If this is not good in UI/UX it's better to do a proper redesign and make this plugin work as UI/UX report suggests. 
- About A11y, I'm sure we can add that somehow(sorry I don't remember much coz it was like 2yrs ago).

I would suggest resolving this matter and move forward, and not to close PR.

2020-11-13 22:50 UTC, N6REJ commented
please don't enable this by default.  As a photographer and sometime site dev I dang sure don't want some piece of software changing images I spent time to create.

2020-11-13 23:13 UTC, brianteeman commented
@N6REJ Nothing is done to your image unless you tell it to be done by setting a focus.

2021-03-15 10:26 UTC, rdeutz commented
I am moving this to 4.1, we are in beta and this is a new feature with need some more work.

2021-08-21 00:03 UTC, PhilETaylor commented on administrator/components/com_media/src/Controller/AdaptiveImageController.php
> + * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:03 UTC, PhilETaylor commented on administrator/components/com_media/src/Controller/AdaptiveImageController.php
> + * @since  4.0.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:03 UTC, PhilETaylor commented on administrator/components/com_media/src/Controller/AdaptiveImageController.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:03 UTC, PhilETaylor commented on administrator/components/com_media/src/Controller/AdaptiveImageController.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:03 UTC, PhilETaylor commented on administrator/language/en-GB/en-GB.plg_content_adaptiveimage.sys.ini
> +; Copyright (C) 2005 - 2018 Open Source Matters. All rights reserved.
```suggestion
; Copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:03 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> + * @copyright  Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:03 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> + * @since  4.0.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:03 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:04 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:04 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:04 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/FocusStoreInterface.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:04 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> + * @copyright  Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:04 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> + * @since  4.0.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:04 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:04 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:04 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/JSONFocusStore.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/SmartCrop.php
> + * @copyright  Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:05 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/SmartCrop.php
> + * @since  4.0.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:06 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/SmartCrop.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:06 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/SmartCrop.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:06 UTC, PhilETaylor commented on libraries/src/AdaptiveImage/SmartCrop.php
> +	 * @since 4.0.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-21 00:06 UTC, PhilETaylor commented on media/com_media/js/edit-images.js
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:06 UTC, PhilETaylor commented on plugins/content/adaptiveimage/adaptiveimage.php
> + * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:07 UTC, PhilETaylor commented on plugins/content/adaptiveimage/adaptiveimage.php
> + * @since  4.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:07 UTC, PhilETaylor commented on plugins/content/adaptiveimage/adaptiveimage.php
> +	 * @since  4.0.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:07 UTC, PhilETaylor commented on plugins/content/adaptiveimage/adaptiveimage.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:07 UTC, PhilETaylor commented on plugins/media-action/focus/focus.php
> + * @since  4.0.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:07 UTC, PhilETaylor commented on plugins/media-action/focus/focus.php
> +	 * @since  4.0.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:07 UTC, PhilETaylor commented on plugins/media-action/focus/focus.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:07 UTC, PhilETaylor commented on plugins/media-action/focus/focus.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:08 UTC, PhilETaylor commented on plugins/media-action/focus/focus.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:08 UTC, PhilETaylor commented on plugins/media-action/focus/focus.xml
> +    <version>4.0.0</version>
```suggestion
    <version> __DEPLOY_VERSION__ </version>
```

2022-01-20 03:37 UTC, bembelimen commented
@proman24 is there any interest to work through the feedback and make this PR mergable?

2022-06-27 13:09 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2022-07-13 07:42 UTC, alikon commented
closed, because has been taken over by another person   #38264

2022-07-13 07:42 UTC, closed without merging