[4.0] Update the com_content manifest file
joomla/joomla-cms pull request #21817
Opened 2018-08-23 06:11 UTC by laoneo

Pull Request for pr #21790.

### Summary of Changes
As #21790 revealed, the manifest files in core are out of sync. Before I'm going to fix all of them I would like to get some feedback what all needs to be adapted.

Beside the folders I would also change the compatibility version and the version of the extension itself. Anything else?

2018-08-23 07:41 UTC, brianteeman commented on administrator/components/com_content/content.xml
> +			<folder>Controller</folder>
missing 
filename content.xml

2018-08-23 07:42 UTC, brianteeman commented
other than the missing file it looks ok to me

would be good to get another check though

2018-08-23 17:16 UTC, alikon commented on administrator/components/com_content/content.xml
> +		<folder>Table</folder>
if i'm not wrong there is no Table folder

2018-08-24 07:46 UTC, laoneo commented
Added also media folder.

2018-08-28 21:17 UTC, brianteeman commented
I am wondering if we even need these manifest files for core components and with the move of media files if they should be in the manifest either

2018-08-28 21:23 UTC, mbabker commented
Yes the extension manifests should be in place.  Technically, we don't need them, but the core package shouldn't be taking liberties as it relates to extension structure that a distributed extension can't.

2018-08-28 21:36 UTC, brianteeman commented
And the media folder? The same?

@laoneo did you have to create this manually - if so I am happy to takeover so you can concentrate on developer stuff

2018-08-28 23:12 UTC, wilsonge requested changes
I don't think we need the media tag - we aren't shipping a media folder with the extension as it's all baked into core (especially now with the es6 stuff) - so I'd leave that as it is. Otherwise LGTM

2018-08-29 06:12 UTC, laoneo commented
For me it reflects the installed state of an extension which includes the media folder and com_content has a media folder. From my understanding an extension dev should be able to take it as example and the manifest with the media folder is part of it.

I can remove it if you really want but I think it is not a bad idea to leave it in.

@brianteeman yes I'm doing them by hand. If you want you can take over the task when we get this one merged. But I would wait about the agreement of the media folder.

2018-08-29 10:25 UTC, brianteeman commented
When you decide on media let me know and i can get this done

2018-09-10 10:39 UTC, merged

2018-09-10 10:39 UTC, wilsonge commented
Not convinced about the media tag - but not sceptical enough to block progress here