[4.0] Multilingual : Correcting info-block category and parent category urls
joomla/joomla-cms pull request #21916
Opened 2018-08-30 10:24 UTC by infograf768

Problem: on a multilingual site, when displaying the info-block for articles in frontend , the urls of the category and parent category are real bad.

### Summary of Changes
1. `ContentHelperRoute::getCategoryRoute()` should ALWAYS contain the `$language` variable.
This PR adds it wherever necessary, including in `layouts/joomla/content/info-block/ `corresponding files. Queries are modified to also select the category language. The language is also added in data.

2. `com_content/helpers/route.php` should cope with categories set to ALL languages
The code is modified to take this into account as, in this case, the language to use in the url should be the language of the UI content language.

3. `com_content/helpers/route.php` should not add for example `&layout=cassiopeamyblog` to the end of the sef url when such a specific `html/com_content/category/myblog.etc` menu item type is present in the template.
To solve this, I had to revert https://github.com/joomla/joomla-cms/pull/19681

### Testing Instructions
Install a multilingual site with 2 content languages.
Tests can be done on a single language. Choose en-GB for example as it is easier.

Create some categories and articles in these categories both tagged to the same language [CATen-GB, CATfr-FR].
Create a home blog menu item for each content language to display one CATen-GB and one CATfr-FR
Make sure you create a (hidden or not) `List All Categories` menu item tagged to en-GB in mainmenu en-GB.
=> This is important as any category which has no specific menu item will still get a nice sef url.

Create also a Category set to ALL language and a child category of that category (tagged to ALL or to en-GB). Add to the child category an article tagged to en-GB ("Articletest").
Create a single menu item in mainmenu en-GB to display the "articletest" article.

Now, the second part of the test concerns the revert of the layout code in route.php.
To test this, it is necessary to add a new menu item type.
Find here a .zip of the files to add in `/templates/cassiopeia/html/com_content/category/`
[myblog.zip](https://github.com/joomla/joomla-cms/files/2335647/myblog.zip)

Create a menu item using this type in mainmenu en-GB to display any category not yet displayed by the former menu items.

In Articles Options, make sure show category and link as well as show Parent category and link are set to yes.
Make sure all your menu items use these global settings

### Expected result
When clicking on the Category or Parent category links you should get nice urls 
not containing some stuff like 
`?view=category&id=18`
or
`&layout=cassiopeamyblog` when using the custom menu item type

Instead one may get for example when no menu item for the category 
`/en/allcategories-en-gb/category-all` (here set to ALL)
or
`/en/allcategories-en-gb/category-all/othercaten-gb` (category set to en-GB)

and same for the custom menu item type (myblog menu item type)
![screen shot 2018-08-30 at 12 20 50](https://user-images.githubusercontent.com/869724/44845952-3bc59b00-ac4f-11e8-9266-ca22b1116708.png)

### Note A
Reverting https://github.com/joomla/joomla-cms/pull/19681 is necessary.
We should look for another way to implement this feature.

### Note B
The modifications concerning getCategoryRoute() and route.php should also be done for other components using this method.

@alikon @Hackwar @csthomas

2018-08-30 14:13 UTC, Quy commented on components/com_content/View/Archive/HtmlView.php
> +				$item->parent_slug    = null;
Why the extra spaces?

2018-08-30 14:15 UTC, Hackwar requested changes
We need these changs for the other core components, too.

2018-08-30 14:15 UTC, Hackwar commented on components/com_content/View/Archive/HtmlView.php
> +			$item->parentlanguage = $item->parent_language;
Why are you adding these attributes again here? We don't need to duplicate these attributes.

2018-08-30 14:15 UTC, Hackwar commented on components/com_content/View/Archive/HtmlView.php
> +			$item->parentlanguage = $item->parent_language;
We also don't need the slugs for the categories. For the categories we only need the ID.

2018-08-30 14:15 UTC, Hackwar commented on components/com_content/View/Archive/HtmlView.php
> +				$item->parent_slug    = null;
Can you revert this change here? Don't want to have unnecessary changes...

2018-08-30 14:15 UTC, Hackwar commented on components/com_content/View/Article/HtmlView.php
> +		$item->parentlanguage = $item->parent_language;
Again, don't duplicate the attributes and we don't need the slugs.

2018-08-30 14:15 UTC, Hackwar commented on components/com_content/View/Category/HtmlView.php
> +			$item->parentlanguage = $item->parent_language;
Again, don't duplicate the attributes and we don't need the slug.

2018-08-30 14:15 UTC, Hackwar commented on components/com_content/View/Featured/HtmlView.php
> +			$item->parentlanguage = $item->parent_language;
See comment above...

2018-08-30 14:15 UTC, Hackwar commented on components/com_content/helpers/route.php
> +				}
The $lang changes should not be necessary. It defaults to the current language if no language is given. Did you check if this is necessary? The $layout is indeed wrong here. In any case, you should change the fingerprint of these methods to not have the $language (and also the $catid) be optional anymore. These are always required.

2018-08-30 15:25 UTC, infograf768 commented on components/com_content/helpers/route.php
> +				}
> The $lang changes should not be necessary. It defaults to the current language if no language is given. Did you check if this is necessary? 

Alas it is. Tested that. Specially for the info-block at least.

2018-08-30 15:25 UTC, infograf768 commented on components/com_content/View/Archive/HtmlView.php
> +				$item->parent_slug    = null;
sure

2018-08-30 15:31 UTC, infograf768 commented on components/com_content/View/Archive/HtmlView.php
> +			$item->parentlanguage = $item->parent_language;
> Why are you adding these attributes again here? We don't need to duplicate these attributes.

Looks like they are needed for the info-block JLayout

> We also don't need the slugs for the categories. For the categories we only need the ID.

I was adapting to the info-block layout which uses slugs.

2018-08-30 15:32 UTC, infograf768 commented on components/com_content/helpers/route.php
> +				}
> In any case, you should change the fingerprint of these methods to not have the $language (and also the $catid) be optional anymore. These are always required.

Any hint how to do that? And would it be B/C ?

2018-08-31 05:04 UTC, infograf768 commented
On it for most parts except the fingerprint of the method

2018-08-31 06:56 UTC, infograf768 commented
@Hackwar 
Got rid of slugs for category and parent category. Modified info-block to fit.
Did not modify getCategoryRoute() method. I guess this can/should be done in another PR.

After merge, will work on other components.

2018-08-31 10:00 UTC, Hackwar commented on components/com_content/helpers/route.php
> +				}
Simply remove the optional parameter stuff here. So from
```
 	public static function getCategoryRoute($catid, $language = 0)
```
to
```
 	public static function getCategoryRoute($catid, $language)
```

This is not B/C, but we are talking about Joomla 4.0 here, where we can break B/C and this is a case where we have to break it, to clear up this longlasting bug.

2018-08-31 10:06 UTC, Hackwar commented on components/com_content/helpers/route.php
> +				}
Also, please remove the $lang changes. We should never have to add something if the language is *. If this currently is necessary, we have to fix this in another place, but not here. Not only because it is wrong, but also because this method is just an amenity, not a necessity. These methods only concatenate a string, nothing more, they don't look up anything. People can also just hand in their own handcrafted URL into the router, which could not contain the language parameter. So we have to see what the issue is here in the router and fix that and not hand in fake parameters. This code has to go.

2018-08-31 10:18 UTC, infograf768 commented on components/com_content/helpers/route.php
> +				}
> Also, please remove the $lang changes.
My problem here is that if I remove it, full tests can't be done on this PR as soon as we have a category set to ALL languages.

> This is not B/C, but we are talking about Joomla 4.0 here, where we can break B/C and this is a case where we have to break it, to clear up this longlasting bug.

I am not opposed to it. Need OK from
@wilsonge @mbabker

2018-08-31 13:11 UTC, infograf768 commented on components/com_content/helpers/route.php
> +				}
I have a solution for the $lang stuff. Will add later on.

2018-08-31 15:12 UTC, infograf768 commented
@Hackwar 
Set the $language to $active->language when multilang and item tagged to ALL in the Router, therefore getting rid of $lang in route.

2018-08-31 15:51 UTC, csthomas commented on components/com_content/helpers/route.php
> +				}
Can you undo changes that do not do anything in this file, I mean just delete the part with the layout.

2018-08-31 17:00 UTC, infograf768 commented on components/com_content/helpers/route.php
> +				}
will do

2018-08-31 17:02 UTC, infograf768 commented
after some further tests, i think my changes in menurules are not enough.

2018-09-01 09:02 UTC, csthomas commented on libraries/src/Component/Router/Rules/MenuRules.php
> +			$language = Factory::getLanguage()->getTag();
This should work too `$language = $this->router->app->get('language');`

2018-09-01 14:57 UTC, infograf768 commented on libraries/src/Component/Router/Rules/MenuRules.php
> +			$language = Factory::getLanguage()->getTag();
It does indeed. More in the style of that file than the present code. Changing now. :)

2018-09-01 15:05 UTC, infograf768 commented
restarted drone as non-related error

2018-09-01 19:49 UTC, csthomas commented
The code is OK. I wonder if issue occurs on J3?

2018-09-01 20:07 UTC, csthomas commented
I have tested this item :white_check_mark: successfully on e06a014348c9af5f1c132f727bc4bd4d5d01afa5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21916">issues.joomla.org/tracker/joomla-cms/21916</a>.</sub>

2018-09-04 18:57 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on e06a014348c9af5f1c132f727bc4bd4d5d01afa5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21916">issues.joomla.org/tracker/joomla-cms/21916</a>.</sub>

2018-09-06 05:56 UTC, merged

2018-09-06 05:56 UTC, laoneo commented
Thanks