Translate workflow via language file
joomla/joomla-cms pull request #21939
Opened 2018-08-31 23:33 UTC by bembelimen

### Summary of Changes
After #21506 now translate the workflows themselves via language files

### Testing Instructions
Check the "Joomla! Default"-Workflow, rename it to "COM_WORKFLOW_DEFAULT_WORKFLOW".

### Expected result
The workflow should be translated everywhere

### Actual result
Workflow not translated

@infograf768

2018-08-31 23:46 UTC, brianteeman requested changes

2018-08-31 23:46 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_workflow.ini
> +COM_WORKFLOW_USE_DEFAULT_WORKFLOW="Use default (%s)"
pleaase alpha sort

2018-08-31 23:46 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +(1, 0, 1, 'COM_WORKFLOW_DEFAULT_WORKFLOW', '', 'com_content', 1, 1, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0);
It would be better if you did the update as a NEW file so that people can upgrade their earlier j4 sites - this is a change from practice in j3

2018-08-31 23:50 UTC, bembelimen commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +(1, 0, 1, 'COM_WORKFLOW_DEFAULT_WORKFLOW', '', 'com_content', 1, 1, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0);
I'm not sure, if this is valid within J!4 alpha or only between "regular" versions?

2018-08-31 23:55 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +(1, 0, 1, 'COM_WORKFLOW_DEFAULT_WORKFLOW', '', 'com_content', 1, 1, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0);
As I said this is a change and makes it easier for people to "upgrade" a site from alpha 4 to alpha 5 etc

I thought it had been decided but it looks like as usual no one wants to make the final decision https://github.com/joomla/joomla-cms/issues/21024

2018-09-01 06:31 UTC, infograf768 commented
Code works fine.
Next step will be adding everywhere we use Constants the translation below the title as we do for custom admin menus.
See https://github.com/joomla/joomla-cms/pull/19916

2018-09-08 08:09 UTC, infograf768 commented
Conflicts have to be resolved here.

2018-09-08 08:15 UTC, brianteeman commented
Workflows all resolved

2018-09-08 08:53 UTC, f-hamel commented
I have tested this item :red_circle: unsuccessfully on 7c2fdfcadaf4534574210ddee4aa933081b23cd6<br /><br />Hi can't apply patch because there seem to conflicts in the language file with #21579 
```
The patch could not be applied because it conflicts with a previously applied patch: administrator/language/en-GB/en-GB.com_workflow.ini

```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21939">issues.joomla.org/tracker/joomla-cms/21939</a>.</sub>

2018-09-08 09:21 UTC, HRIT-Florian commented
I have tested this item :white_check_mark: successfully on 7c2fdfcadaf4534574210ddee4aa933081b23cd6<br /><br />Can't reproduce any conflicts in the language file with #21579 by applying the patch to the current nightly build!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21939">issues.joomla.org/tracker/joomla-cms/21939</a>.</sub>

2018-09-08 09:49 UTC, infograf768 commented on administrator/components/com_content/Helper/ContentHelper.php
> +		Factory::getLanguage()->load('com_workflow');
path is not specified for the ini file to load. I guess that it should be here `Factory::getLanguage()->load('com_workflow', JPATH_ADMINISTRATOR);`

2018-09-08 10:25 UTC, infograf768 commented on administrator/components/com_workflow/tmpl/workflows/default.php
>  										<a href="<?php echo $edit; ?>" title="<?php echo Text::_('JACTION_EDIT'); ?> <?php echo $this->escape(addslashes($item->title)); ?>">
Missing Text:: to translate `<?php echo $this->escape(addslashes($item->title)); ?>`

2018-09-08 11:46 UTC, gorgonz commented
I have tested this item :white_check_mark: successfully on 7c2fdfcadaf4534574210ddee4aa933081b23cd6<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21939">issues.joomla.org/tracker/joomla-cms/21939</a>.</sub>

2018-09-08 11:47 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-09-08 13:18 UTC, ghost commented
I have tested this item :red_circle: unsuccessfully on 7c2fdfcadaf4534574210ddee4aa933081b23cd6<br /><br />Before Patch the renaming works successfully.
After Patch it doesn't work anymore.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21939">issues.joomla.org/tracker/joomla-cms/21939</a>.</sub>

2018-09-09 23:59 UTC, wilsonge commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
> +(1, 0, 1, 'COM_WORKFLOW_DEFAULT_WORKFLOW', '', 'com_content', 1, 1, '0000-00-00 00:00:00', 0, '0000-00-00 00:00:00', 0);
Even on that PR michaels proposal is only doing that from beta. this is fine.

2018-09-10 00:16 UTC, merged