[3.9] Adjustments for upcoming Install from Web plugin update
joomla/joomla-cms pull request #21950
Opened 2018-09-01 17:51 UTC by mbabker

### Summary of Changes

In preparation for the [upcoming Install from Web update](https://github.com/joomla-extensions/install-from-web-client/releases/tag/2.0.0-alpha) there are language string changes needed, and since the language file is in this repo and not distributed as part of the plugin, the updates must be made here.

In short, this:

- Marks strings being removed deprecated, they have to stay here since the language file will be used for any IFW plugin release
- Adds new strings replacing hardcoded English, similar to the changes in 4.0
- Adds the media path to `.gitignore`

### Testing Instructions

Install IFW plugin update, apply this patch.  Without it you're going to have untranslated strings in a couple JavaScript actions.

2018-09-01 18:06 UTC, zero-24 commented on administrator/language/en-GB/en-GB.plg_installer_webinstaller.ini
>  PLG_INSTALLER_WEBINSTALLER_LOAD_APPS="Display the extensions"
can't we drop that string than when it is not used in the 1.x version too?

2018-09-01 18:09 UTC, mbabker commented on administrator/language/en-GB/en-GB.plg_installer_webinstaller.ini
>  PLG_INSTALLER_WEBINSTALLER_LOAD_APPS="Display the extensions"
Strings in this repo can only be deprecated to be removed at the next major version.

2018-09-01 18:13 UTC, zero-24 commented on administrator/language/en-GB/en-GB.plg_installer_webinstaller.ini
>  PLG_INSTALLER_WEBINSTALLER_LOAD_APPS="Display the extensions"
Fine for me.

2018-09-01 19:05 UTC, brianteeman requested changes

2018-09-01 19:05 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_installer_webinstaller.ini
> +PLG_INSTALLER_WEBINSTALLER_ERROR_PLUGIN_INCLUDED_IN_CORE="Plugin install aborted, the Install from Web plugin is included in core as of Joomla! 4.0."
Plugin installation has been aborted. The ..

2018-09-01 19:05 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_installer_webinstaller.ini
> +PLG_INSTALLER_WEBINSTALLER_CANNOT_INSTALL_EXTENSION_IN_PLUGIN="This extension cannot be installed via the install from web system. Please visit the developer's website to purchase/download."
Using not via

2018-09-01 19:08 UTC, mbabker commented on administrator/language/en-GB/en-GB.plg_installer_webinstaller.ini
> +PLG_INSTALLER_WEBINSTALLER_ERROR_PLUGIN_INCLUDED_IN_CORE="Plugin install aborted, the Install from Web plugin is included in core as of Joomla! 4.0."
Changed

2018-09-01 19:08 UTC, mbabker commented on administrator/language/en-GB/en-GB.plg_installer_webinstaller.ini
> +PLG_INSTALLER_WEBINSTALLER_CANNOT_INSTALL_EXTENSION_IN_PLUGIN="This extension cannot be installed via the install from web system. Please visit the developer's website to purchase/download."
Changed

2018-09-01 20:11 UTC, brianteeman approved these changes

2018-09-01 20:11 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 073db4badaea4c762f5d0b45071016501bfb42fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21950">issues.joomla.org/tracker/joomla-cms/21950</a>.</sub>

2018-09-02 11:13 UTC, zero-24 commented
Merging. Thanks!

2018-09-02 11:13 UTC, merged