[3.9] Add privacy note to the new captcha plugin
joomla/joomla-cms pull request #21962
Opened 2018-09-02 15:40 UTC by zero-24

### Summary of Changes

Add privacy note to the new captcha plugin

### Testing Instructions

- apply this patch
- notice the privacy notice in the backend

### Expected result

There is also a privacy notice for this plugin the backend

### Actual result

There is NO privacy notice for this plugin the backend

### Documentation Changes Required

None

2018-09-02 15:44 UTC, brianteeman requested changes

2018-09-02 15:44 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.ini
> +PLG_RECAPTCHA_INVISIBLE_PRIVACY_CAPABILITY_IP_ADDRESS="The Invisible reCAPTCHA plugin integrates with Google's reCAPTCHA system as a spam protection service. As part of this service, the IP of the us
Please make it IP address not just IP

2018-09-02 15:48 UTC, zero-24 commented
fixed here and in the original place.

2018-09-02 15:50 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_captcha_recaptcha.ini
> +PLG_RECAPTCHA_PRIVACY_CAPABILITY_IP_ADDRESS="The reCAPTCHA plugin integrates with Google's reCAPTCHA system as a spam protection service. As part of this service, the IP address of the user who is an
Remove `who is` since you have 2 `is`.

2018-09-02 15:51 UTC, zero-24 commented
pushed.

2018-09-02 16:38 UTC, infograf768 commented
This is a totally new plugin in J. Please alpha order all the strings.

2018-09-02 17:14 UTC, brianteeman commented
@zero-24 thanks for making the change. I missed it in the other file. All good for merging

2018-09-02 17:15 UTC, brianteeman approved these changes
Approve changes

2018-09-02 17:17 UTC, zero-24 commented
@infograf768 should be alpha ordernd now. please confirm and set RTC so someone can hit the green button ;)

thanks @brianteeman

2018-09-02 17:31 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.ini
>  PLG_RECAPTCHA_INVISIBLE_BADGE_BOTTOMRIGHT="Bottom right"
Alpha order

2018-09-02 17:32 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.ini
>  PLG_RECAPTCHA_INVISIBLE_EXPIRED_CALLBACK_LABEL="Expired callback"
Alpha order

2018-09-02 17:32 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.ini
>  PLG_RECAPTCHA_INVISIBLE_ERROR_CALLBACK_LABEL="Error callback"
Alpha order

2018-09-02 17:36 UTC, zero-24 commented
Do i still miss one @Quy ?

2018-09-03 04:18 UTC, infograf768 requested changes

2018-09-03 04:18 UTC, infograf768 commented on administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.ini
>  PLG_RECAPTCHA_INVISIBLE_ERROR_CALLBACK_DESC="(Optional) JavaScript callback, executed when the reCAPTCHA encounters an error"
ERROR comes before EXPIRED

2018-09-03 04:18 UTC, infograf768 commented on administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.ini
>  PLG_RECAPTCHA_INVISIBLE_BADGE_INLINE="Inline"
MOve on top of PLG_RECAPTCHA_INVISIBLE_BADGE_LABEL

2018-09-03 08:54 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on a4ae5e6eea20865a7410c8657d95003a58db3073<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21962">issues.joomla.org/tracker/joomla-cms/21962</a>.</sub>

2018-09-03 09:06 UTC, wojsmol commented
@infograf768 Please accept changes on github.

2018-09-03 09:07 UTC, infograf768 approved these changes

2018-09-03 09:35 UTC, infograf768 commented
@mbabker 
Please merge as some of us are already working on 3.9 translations.
Thanks

2018-09-03 14:45 UTC, merged