[3.9][com_actionlogs] Move log notification option to own table
joomla/joomla-cms pull request #21983
Opened 2018-09-04 08:42 UTC by SharkyKZ

Pull Request for Issue https://github.com/joomla-projects/privacy-framework/issues/201.

### Summary of Changes

This moves action log user notification option to separate table. It is a performance improvement on larger sites and shouldn't affect existing behavior. Except when going from 3.9-alpha as existing preference will be nullified in this case.

### Testing Instructions

Test that user settings in `User Actions Log Options` tab continue to be saved properly and that `Send notifications for User Actions Log` continues to be respected.

### Expected result

### Actual result

### Documentation Changes Required
Database changes, plugin field names changed.

2018-09-08 11:58 UTC, pjasmits commented
patch is not working. After logout I get the following error:

0 syntax error, unexpected '')'' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')'

2018-09-08 12:01 UTC, BurtNL commented
I have tested this item :red_circle: unsuccessfully on 1ad00d8a0ff6501f334ff3b71ed2d686ae05eadf<br /><br />Applied the patch, but unsuccessful. New table '#__action_logs_users' is not created and log out is not possible. On log out an error is shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-09-08 12:35 UTC, franz-wohlkoenig commented
@pjasmits please mark your Test as unsuccessfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/21983)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as unsuccessfully
- hit "submit test result"

2018-09-08 12:44 UTC, SharkyKZ commented
@pjasmits The error should be fixed now.

@BurtNL it's best to test by downloading the package (https://github.com/SharkyKZ/joomla-cms/archive/comActionlogsPerf_1.zip) and doing a fresh install. Alternatively, you can execute Database Fix to install missing tables. I'll update testing instructions.

2018-09-08 12:51 UTC, pjasmits commented
I have tested this item :red_circle: unsuccessfully on 2b561eec304b72472009e70caffba7ee1304d842<br /><br />patch gives error on logout<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-09-08 14:34 UTC, BurtNL commented
Thanks SharkyKZ, I used 'Fix database', which solved the log out problem. I will do some additional testing on this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-09-08 15:01 UTC, BurtNL commented
I have tested this item :white_check_mark: successfully on 2b561eec304b72472009e70caffba7ee1304d842<br /><br />Tested successfully on Joomla 3.9.0-alpha2-dev, on a fresh install, applied the patch, run the Fix Datase.
The new table has been created and contains content. Log out working proberly as well.
Patch works as intended by submitter, needs further testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-09-09 06:30 UTC, alikon requested changes
use PRIMARY KEY

2018-09-09 06:30 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-09-04.sql
> +  "user_id" serial NOT NULL,
these fields must be declared not  `serial`  instead shoud be `integer`

2018-09-09 06:30 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-09-04.sql
> +  CONSTRAINT "#__action_logs_user_idx_user_id" UNIQUE ("user_id")
use `PRIMARY KEY ("user_id")`

2018-09-09 06:30 UTC, alikon commented on administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-09-04.sql
> +  UNIQUE KEY `idx_user_id` (`user_id`),
please use PRIMARY KEY ("user_id")

2018-09-09 09:14 UTC, alikon commented on administrator/components/com_actionlogs/models/actionlog.php
> +			->where($db->quoteName('id') . ' IN (' . $subQuery . ')');
can you share some performance reports that can justify is better to use a subquery instead of a join ?

2018-09-10 06:13 UTC, SharkyKZ commented on administrator/components/com_actionlogs/models/actionlog.php
> +			->where($db->quoteName('id') . ' IN (' . $subQuery . ')');
Performance difference is minimal. Either query is fine. Actually I would prefer to move all params added by the plugin to this table so they're all in the same place (which means using a join in the end).

2018-09-15 11:57 UTC, SharkyKZ commented
Latest commits move other params to the table. @BurtNL @pjasmits could you re-test this with the latest changes?

2018-09-18 13:43 UTC, Quy commented on plugins/system/actionlogs/actionlogs.php
> +		// Clear access rights in case user groups were changes.
Change to `changed`

2018-09-18 13:58 UTC, infograf768 commented
If this is merged, let's not forget to correct the absence of `_LABEL` for the constants in the xml concerned.

@mbabker  When tested, do you intend to merge this proposal?

2018-09-18 16:39 UTC, ReLater commented on plugins/system/actionlogs/actionlogs.php
> +		$data->actionlogs->actionlogsNotify     = $values->notify;
Create a new Super User and save it. After saving user again I see:
Warning: Creating default object from empty value in /plugins/system/actionlogs/actionlogs.php on line 171

2018-09-18 16:57 UTC, SharkyKZ commented on plugins/system/actionlogs/actionlogs.php
> +		$data->actionlogs->actionlogsNotify     = $values->notify;
Fixed. Thanks.

2018-09-18 19:12 UTC, ReLater commented
I have tested this item :white_check_mark: successfully on b66a904030a73fa303628a1825b99b88b8c20faa<br /><br />Updated 2 or 3 days old nightly 3.9.
Applied patch and fixed database.
Saved all existing "Super Users" (!!!!). Have now rows in #__action_logs_users. Received or not emails according user settings.
Created new "Super Users" and some with other groups. Only "Super Users" see Acions Log tabulator after first saving. Other groups never see it.
Switched groups of users and deleted "Super Users". Rows in #__action_logs_users correctly deleted or created (after additional saving).
Don't receive emails anymore if disabled or not "Super User".

Don't forget to remove and apply patch newly if you upgrade nightly 3.9 with "Upload&Update"!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-09-19 05:19 UTC, ghost commented
@BurtNL can you please retest?

2018-09-19 12:47 UTC, ReLater commented
@SharkyKZ 
Please have a look on https://github.com/joomla/joomla-cms/pull/22250 concerning possible conflicts.

2018-09-19 20:49 UTC, BurtNL commented
I have tested this item :red_circle: unsuccessfully on b66a904030a73fa303628a1825b99b88b8c20faa<br /><br />Fresh install of Joomla_3.9.0-beta2-dev-Development-Full_Package, applied the patch, fixed the database.
Test with change options of User Actions Log failed.
When all 'Events to log' are not selected then all events will be selected again after 'Save'.
Changing individual events seems to work fine.

And when should the table '#action_logs_users' be filled?
What do I need to test to trigger the creation of records in that table?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-09-19 21:09 UTC, Quy commented
> When all 'Events to log' are not selected then all events will be selected again after 'Save'.

This is the default behavior and not related to this PR. Unselecting all would defeat the purpose of logging.

> And when should the table '#action_logs_users' be filled?

Edit your account and update `User Actions Log Options`.
Use phpMyAdmin and view `action_logs_users' table for your saved settings.

2018-09-19 21:12 UTC, ReLater commented
> When all 'Events to log' are not selected then all events will be selected again after 'Save'.

I can't confirm your
![19-09-_2018_23-10-50](https://user-images.githubusercontent.com/20780646/45781788-58a72a00-bc61-11e8-8ee3-2033eee89b30.jpg)
 find.

![19-09-_2018_23-02-17](https://user-images.githubusercontent.com/20780646/45781403-25b06680-bc60-11e8-8761-e8dd4149aa92.jpg)

> And when should the table '#action_logs_users' be filled?

- Whenever you save a "Super User" after the "User Actions Log Options" is shown.
- When you change/add the group of an existing user to "Super User"
- If you delete a "Super User" or remove the "Super User" group of an user the according row should be deleted.

2018-09-19 21:17 UTC, ReLater commented
> This is the default behavior

> I can't confirm your find.

Maybe we're using completely different Joomlas ? ;-) I've installed mine (nightly) some hours ago. And with the older version I also could save without any selected box.

2018-09-19 23:23 UTC, Quy commented
> When all 'Events to log' are not selected then all events will be selected again after 'Save'.

I stated incorrectly in my previous reply.

In PHP error log file, when no checkboxes selected:
```
PHP Notice:  Undefined index: actionlogsExtensions in \plugins\system\actionlogs\actionlogs.php on line 342
```

2018-09-20 06:56 UTC, SharkyKZ commented
@BurtNL this can be reproduced without patch (try fresh 3.9.0 Beta 2) too. If you deselect all options on first save, no value is saved to database but form shows all options as selected (this is what the field defaults to). You would have to save again (with all or some options selected) to have the options stored.

Scenario # 2: select some options. Save. Deselect all options. Save again. The data still contains previously selected options. So, yes, you can't deselect all options.

Updating this so it works like without patch.

2018-09-20 07:00 UTC, SharkyKZ commented
Alternatively, we could just add `required` attribute to the field...

2018-09-20 09:32 UTC, BurtNL commented
@ReLater I'm using a new nightly build, but we are on different pages.
I'm on the Options page, you are on a user profile page.


![screen shot 2018-09-20 at 09 32 25](https://issues.joomla.org/uploads/1/136d564798f993a6be9118a268666359.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-09-20 09:42 UTC, BurtNL commented
@SharkyKZ Yes, you are right, I'm sorry about that. 
I just run a test again and with or without the patch the behaviour is the same, so not related to the patch.

I agree with you to add the required attribute, because now the behaviour is a bit odd, to my opinion.
Later today I will have a look at the other test instructions about how to get some entries into one of the tables.

Wouldn't it be nice to have the 'Yes/No' switches instead of the select boxes in the Option page? 
Like on the other pages in the admin interface.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-09-20 10:15 UTC, SharkyKZ commented
@BurtNL I see what you mean now. This PR is for user settings added by `System - User Action Logs` plugin, not for settings in `User Action Logs` component. To test you need to edit a user profile.

2018-10-09 17:21 UTC, SharkyKZ commented
@BurtNL @ReLater @pjasmits can you re-test this please?

2018-10-10 15:36 UTC, BurtNL commented
I have tested this item :white_check_mark: successfully on bb11b72bc025e53d03a2b636b27e3b4051a7c974<br /><br />Did a fresh install of Joomla_3.9.0-rc2-dev, applied the patch, fixed the database and tested the User Actions Log Options.
Looks good!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-10-17 04:07 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on bb11b72bc025e53d03a2b636b27e3b4051a7c974<br /><br />This has solved https://github.com/joomla/joomla-cms/issues/22662<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-10-17 04:28 UTC, infograf768 commented
RTC

@mbabker 
Please merge as this corrects important bugs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21983">issues.joomla.org/tracker/joomla-cms/21983</a>.</sub>

2018-10-17 12:00 UTC, merged