Create AwareModel.php (#1)
joomla/joomla-cms pull request #22030
Opened 2018-09-06 20:01 UTC by grillkoning

Pull Request for Issue # 21867.

Summary of Changes
to make joomla's admin model aware of subforms so you can actually handle them in seperate tables with their corresponding model

Testing Instructions
use a subform to add a row

Expected result
some DB-table has a row added which is handled by default CMS functions

Actual result
the row gets stashed away in a json field making it unpractical for sorting, searching, ACL, and just about anything

Documentation Changes Required
tbd

2018-09-07 05:12 UTC, franz-wohlkoenig commented
@grillkoning i changed your Comment to be more readable and linked to Issue.

2018-09-07 06:47 UTC, jeckodevelopment requested changes

2018-09-07 06:47 UTC, jeckodevelopment commented on libraries/src/MVC/Model/AwareModel.php
> + * @copyright Copyright (C) 2005 - 2018 Chris Rutten. All rights reserved.
Generally files in the CMS (unless they are from vendor) have this copyright note:

`@copyright  Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.`

2018-09-07 06:47 UTC, jeckodevelopment commented on libraries/src/MVC/Model/AwareModel.php
> + * @subpackage amber
Where does this subpackage name comes from?

2018-09-07 06:47 UTC, jeckodevelopment commented on libraries/src/MVC/Model/AwareModel.php
> + *
Generally CMS files have this note at row 3:

` * Joomla! Content Management System`

2018-09-07 06:47 UTC, jeckodevelopment commented on libraries/src/MVC/Model/AwareModel.php
> + *          Purpose: to make joomla's admin model aware of subforms so you can
Joomla with capital J

2018-09-07 07:21 UTC, zero-24 commented on libraries/src/MVC/Model/AwareModel.php
> + * @subpackage amber
subpackage is not used anymore in the CMS codebase but was used in the past so can be removed

2018-09-07 07:23 UTC, zero-24 commented
@grillkoning please take a look into the drone / PHPCS reports: http://ci.joomla.org/joomla/joomla-cms/9814/4

2018-09-07 08:45 UTC, brianteeman commented on libraries/src/MVC/Model/AwareModel.php
> + * @subpackage amber
@zero-24 are you sure about that - i think you are confused :)

2018-09-07 09:19 UTC, zero-24 commented on libraries/src/MVC/Model/AwareModel.php
> + * @subpackage amber
There are no subpackage tags in namespaced classes see:
https://github.com/joomla/joomla-cms/blob/920c42921c72745746d1537ca97027a27efdfca3/libraries/src/MVC/Model/AdminModel.php#L1-L22

2018-09-07 09:19 UTC, zero-24 commented on libraries/src/MVC/Model/AwareModel.php
> + *          Purpose: to make joomla's admin model aware of subforms so you can
I would actually move this content to a docs page.

2018-09-07 20:40 UTC, brianteeman commented on libraries/src/MVC/Model/AwareModel.php
> + * @subpackage amber
ah i see - just in components etc not libraries

2018-09-11 12:40 UTC, laoneo commented
Can you extend the description of this pr what you have in mind with it and a code example? It will be then easier to review.

2018-09-11 14:09 UTC, grillkoning commented
thanks to all of you for your comments and attention. hopefully this will grow to be a useful feature to many.

2018-09-13 20:59 UTC, grillkoning commented on libraries/src/MVC/Model/AwareModel.php
> + *
thanks for the pointer; I have restyled the code

2018-09-14 08:33 UTC, grillkoning reviewed
thanks for the pointer; I have restyled the code

2021-08-20 23:59 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> + * @since  3.9
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:59 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> + * @copyright  Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-21 00:00 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +/**
```suggestion
namespace Joomla\CMS\MVC\Model;

defined('_JEXEC') or die('Restricted access');

use Joomla\CMS\Table\Table;
use Joomla\CMS\Factory;
use Joomla\CMS\Form\Form;

/**
```

2021-08-21 00:00 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since  3.9
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:00 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since  3.9
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:00 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since  3.9
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:00 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since  3.9
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-21 00:00 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:00 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:01 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:02 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * Retreives an array with all the subforms in this form
```suggestion
	 * Retrieves an array with all the subforms in this form
```

2021-08-21 00:02 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   3.9
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:02 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   1.6
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-21 00:02 UTC, PhilETaylor commented on libraries/src/MVC/Model/AwareModel.php
> +	 * @since   1.6
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2022-03-28 06:27 UTC, laoneo commented
Sorry it took so long to respond. As this is a nice addition for the MVC API, it is a new feature which should be adapted Joomla 4. Can you rebase the pr to the 4.2-dev branch? In the meantime I'm closing the pr, when ready please reopen again so we can leave feedback. Thank you very much for your contribution and help making Joomla better.

2022-03-28 06:27 UTC, closed without merging