Add the possibility to have a custom login logo
joomla/joomla-cms pull request #22084
Opened 2018-09-08 14:33 UTC by coolcat-creations

This PR Adds an Option in the Backend Template to customize the Login Logo. If no Login Logo is set, the Sitename is displayed. 

<img width="1428" alt="grafik" src="https://user-images.githubusercontent.com/828371/45255288-85676180-b384-11e8-8538-6d855bc6fb6b.png">

Test Instructions:
1) Apply the patch
2) add your desired Logo in the Template Style Settings
<img width="1073" alt="grafik" src="https://user-images.githubusercontent.com/828371/45255302-b2b40f80-b384-11e8-8954-82add36b2bf8.png">
3) logout of the backend
4) Login page should show your desired logo
5) Login, remove the logo and logout
6) The login page should show the sitename again

2018-09-08 14:36 UTC, farrelljsec commented
I have tested this item :white_check_mark: successfully on 3280db029531c0b49ff4ec685c9f38278c8b0ad1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22084">issues.joomla.org/tracker/joomla-cms/22084</a>.</sub>

2018-09-08 14:38 UTC, brianteeman commented on administrator/templates/atum/templateDetails.xml
> +	</config>
please follow the code style
https://developer.joomla.org/coding-standards/xml.html

2018-09-08 14:40 UTC, brianteeman commented
The accessibility team have requested that this page has an H1 title - this PR removes that
also any image must have an alt description OR if it is purely decorative then it must have `alt=""`

2018-09-08 14:40 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on d53bda4d5e9ca4ea94e97b10dfeceb84d318ff73<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22084">issues.joomla.org/tracker/joomla-cms/22084</a>.</sub>

2018-09-08 14:48 UTC, coolcat-creations commented
Changed to adding the custom logo if exists

2018-09-08 14:50 UTC, brianteeman commented on administrator/templates/atum/login.php
> +						<img src="<?php echo JURI::root() . '/' . $loginLogo; ?>" class="img-fluid my-2" alt="<?php echo $sitename; ?>">
is $sitename really an appropriate description of the image?

2018-09-08 14:50 UTC, coolcat-creations commented on administrator/templates/atum/login.php
> +						<img src="<?php echo JURI::root() . '/' . $loginLogo; ?>" class="img-fluid my-2" alt="<?php echo $sitename; ?>">
What do you suggest?

2018-09-08 14:53 UTC, brianteeman commented on administrator/templates/atum/login.php
> +						<img src="<?php echo JURI::root() . '/' . $loginLogo; ?>" class="img-fluid my-2" alt="<?php echo $sitename; ?>">
You either have to add a field to the xml (which still needs fixing) for the alt description or

>  if it is purely decorative then it must have alt=""

2018-09-08 14:59 UTC, coolcat-creations commented
Hm I copied a field from isis template, seems no code style is followed there, thats where the mistake came from.

2018-09-08 15:04 UTC, brianteeman commented
dont see any issue in isis or i would fix it

```
				<field 
					name="loginLogoFile" 
					type="media" 
					label="TPL_ISIS_LOGIN_LOGO_LABEL"
					description="TPL_ISIS_LOGIN_LOGO_DESC"
					class="" 
					default=""
				 />
```
https://github.com/joomla/joomla-cms/blob/eb68e01fada0ceac8695c386c9f9ac143db2f079/administrator/templates/isis/templateDetails.xml#L109

2018-09-08 15:04 UTC, crommie commented
I have tested this item :white_check_mark: successfully on ba2709d9369d5784669ae80f8829f255f0ebd1b6<br /><br />Followed instructions. Result as expected. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22084">issues.joomla.org/tracker/joomla-cms/22084</a>.</sub>

2018-09-08 15:11 UTC, coolcat-creations commented
@brianteeman 
<img width="983" alt="grafik" src="https://user-images.githubusercontent.com/828371/45255666-2b699a80-b38a-11e8-8ecf-d7567a458540.png">

2018-09-08 15:16 UTC, brianteeman commented
no idea what you have on your computer but it is not the same code we have in github
https://github.com/joomla/joomla-cms/blob/eb68e01fada0ceac8695c386c9f9ac143db2f079/administrator/templates/isis/templateDetails.xml#L51

2018-09-08 15:40 UTC, brianteeman approved these changes
approve language change

2018-09-08 20:17 UTC, SharkyKZ commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_ATUM_LOGINLOGO_LABEL="Login Logo"
Sort keys alphabetically.

2018-09-08 20:18 UTC, SharkyKZ commented on administrator/templates/atum/login.php
> +						<img src="<?php echo JURI::root() . '/' . $loginLogo; ?>" class="img-fluid my-2" alt="">
Indent. Change `JURI` to `Uri`. Remove slash afterwards.

2018-09-08 20:24 UTC, coolcat-creations commented
> Perhaps keep site title when logo is not specified?
Sitetitle is now always kept because of a11y issues @brianteeman mentioned.

2018-09-08 20:33 UTC, SharkyKZ commented
@coolcat-creations oops, I meant to say remove if specified.

I think @brianteeman means that image alt could be added as another param.

2018-09-08 20:42 UTC, coolcat-creations commented
@SharkyKZ as far I understood he said to keep the h1 title for a11y.

2018-09-08 20:44 UTC, brianteeman commented
BTW the xml you copied came from a very very old version of joomla - thats why you had the problem

2018-09-09 16:28 UTC, tonypartridge commented
@coolcat-creations can we add a toggle for the Page heading? Default on of course.

2018-09-09 17:33 UTC, coolcat-creations commented
@tonypartridge if it’s an accessibility thing I rather would not add an option to remove it. Only thing is that I do not understand why the sitename increases the accessibility- I rather see here then a title that explains where I am. Something like „Joomla Backend Login Page“ - this can be written in small letters and below / sitename or Logo or both.

2018-09-09 17:38 UTC, tonypartridge commented
But to me there are cases where design wins over accessibility. In terms of a company which has no employee with accessibility needs, so a customising toggle to put a logo in and hide H1 tag would be much more beneficial.   
  

  
For a11y I would have thought it would need an Administrator string attached so they know they are in the backend?   
  

  

  

  
  

  
  
>   
> On Sep 9, 2018 at 6:33 pm,  <Elisa Foltyn (mailto:notifications@github.com)>  wrote:
>   
>   
>   
>
> @tonypartridge (https://github.com/tonypartridge)  if it’s an accessibility thing I rather would not add an option to remove it. Only thing is that I do not understand why the sitename increases the accessibility- I rather see here then a title that explains where I am. Something like „Joomla Backend Login Page“ - this can be written in small letters and below / sitename or Logo or both.
>
>   
>
> —
>  You are receiving this because you were mentioned.
>  Reply to this email directly,   view it on GitHub (https://github.com/joomla/joomla-cms/pull/22084#issuecomment-419731637), or   mute the thread (https://github.com/notifications/unsubscribe-auth/ABVglkDweYD_rT3tmVRKnpunj8BfuNzBks5uZVD9gaJpZM4Wf5Nw).
>
>     
>

2018-09-09 19:01 UTC, coolcat-creations commented
Yes I have the similar thought about that it makes more sense to tell people where they are instead of output of the sitename. Doesn’t make sense to me regarding a11y. I will have a thought about how to solve your request and remain a11y compliant :)

2018-09-11 11:27 UTC, coolcat-creations commented
@tonypartridge I added the functionality to show the sitename or not and added the A11y h1 with the information where the User is at...

What I will have to do in another PR is to refactor the whole login page because it has a lot of useless additional classes and is not using the BS4 that is already providing those classes.

2018-09-11 11:33 UTC, coolcat-creations commented
Testing Instructions and PR Description is updated.

2018-09-11 13:00 UTC, brianteeman commented
I am not in favour of this change. If a site builder wants to customise the login page they should create an override

2018-09-11 13:04 UTC, tonypartridge commented
I have to disagree with your @brianteeman  this is a nice and easy way to provide some basic branding to the admin area for the clients. 

You shouldn't need complex template overrides to give a basic style to the backend login page which this does nicely.

2018-09-11 13:16 UTC, coolcat-creations commented
I agree to @tonypartridge 
1) Easy Layout adjustments should be able to be done with few clicks - I would even add a few more (Background Color and Image) - as well as changes for the backend colors. (like described in the backend concept - Please read the concept for that)
2) There is no possibility to override a core template. If so, then I missed possibly a huge feature. You can only copy and assign the copy and then some day you will be completely out-of-date with your copy. 
3) Override of a core template would be great, for that we would need to define where the overrides will be stored. I can try to add this feature so that we have basic options in the template and advanced options per override.

2018-09-11 13:16 UTC, tonypartridge commented
I have tested this item :white_check_mark: successfully on 57a1839b4f227799cb7c614e87bb14aebf1b5c0a<br /><br />Tested working as desired.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22084">issues.joomla.org/tracker/joomla-cms/22084</a>.</sub>

2018-09-11 13:18 UTC, coolcat-creations commented
@SharkyKZ can you retest? If this is merged I will work on the other mentioned points in seperate PRs

2018-09-11 13:20 UTC, tonypartridge commented
@coolcat-creations just to add something else to your list... we could do with enhancing the note field to be 100% width, the label jumps onto another line at present. Maybe an if only label and no description fill 100% like if we set hr="true"

2018-09-11 13:23 UTC, crommie commented
I have tested this item :white_check_mark: successfully on 57a1839b4f227799cb7c614e87bb14aebf1b5c0a<br /><br />Installed patch. Added logo. Set Show site name to no. Logo shown, sitename not shown.
Set Show site name to yes. Logo and sitename shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22084">issues.joomla.org/tracker/joomla-cms/22084</a>.</sub>

2018-09-11 13:26 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-09-11 13:27 UTC, coolcat-creations commented
@tony and @crommie thank you for testing and the suggestions.
I will create another PR with some general code improvements on the login view. This is independant of this PR and I will do it as soon as this is merged.

2018-09-11 13:28 UTC, mbabker commented
> Override of a core template would be great, for that we would need to define where the overrides will be stored. I can try to add this feature so that we have basic options in the template and advanced options per override.

No.  Just, no.  The template is the primary source of truth for all things markup.  If we start introducing systems where template markup can be overridden, it will make things even more complicated than they are.

> You shouldn't need complex template overrides to give a basic style to the backend login page which this does nicely.

What defines "basic" options and what defines options that are best suited as a new template?  By your logic, almost everything that is controlled with some form of CSS variable (default font size, font family, color schemes of every element, etc.) could be considered "basic" and next thing you know it the template style edit page for the backend template has about 300 options.

> You can only copy and assign the copy and then some day you will be completely out-of-date with your copy.

If you are copying a template, you are in essence forking it.  Why does it matter if the source template continues to evolve after you've copied the template?  At the point you copied the template it is your's to customize however you please, which includes the maintenance work of synchronizing changes from the source template if you so desire.

2018-09-11 13:28 UTC, SharkyKZ commented
@coolcat-creations code should be cleaned before merging.

2018-09-11 13:30 UTC, coolcat-creations commented
>>     Override of a core template would be great, for that we would need to define where the overrides will be stored. I can try to add this feature so that we have basic options in the template and advanced options per override.

> No. Just, no. The template is the primary source of truth for all things markup. If we start introducing systems where template markup can be overridden, it will make things even more complicated than they are.

I am ok with your no. I just was trying to fulful something @brianteeman suggested as solution.

2018-09-11 13:32 UTC, mbabker requested changes

2018-09-11 13:32 UTC, mbabker commented on administrator/templates/atum/templateDetails.xml
> +				<field
This field should be the fieldset's description or something, this is major misuse of fields to create a heading/description for a fieldset/tab.

2018-09-11 13:32 UTC, mbabker commented on administrator/templates/atum/templateDetails.xml
> +						name="showSitename"
Codestyle - One indent for each line (there are two here and in follow on lines)

2018-09-11 13:32 UTC, mbabker commented on administrator/templates/atum/login.php
> +
Codestyle - Too many blank lines

2018-09-11 13:32 UTC, mbabker commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_ATUM_BACKEND_LOGIN="Joomla Administrator Loginpage"
"Loginpage" is not a word.

2018-09-11 13:33 UTC, coolcat-creations commented
>> You shouldn't need complex template overrides to give a basic style to the backend login page which this does nicely.

> What defines "basic" options and what defines options that are best suited as a new template? By your logic, almost everything that is controlled with some form of CSS variable (default font size, font family, color schemes of every element, etc.) could be considered "basic" and next thing you know it the template style edit page for the backend template has about 300 options.

Basic is defined by how you can adjust the backend to a customer or site integrator. This was defined and agreed by the marketing department to increase the possibilities to add the own branding into the template. Basic Options IMHO are: Logo and Colorscheme.

2018-09-11 13:34 UTC, coolcat-creations commented
>>    You can only copy and assign the copy and then some day you will be completely out-of-date with your copy.

> If you are copying a template, you are in essence forking it. Why does it matter if the source template continues to evolve after you've copied the template? At the point you copied the template it is your's to customize however you please, which includes the maintenance work of synchronizing changes from the source template if you so desire.

Thats the reason why a core template should have some basic options. Why should I fork the template just because I want to change the displayed logo. Does not make any sense and is an overkill in managing that.

2018-09-11 13:36 UTC, coolcat-creations commented
> @coolcat-creations code should be cleaned before merging.

The code cleanup will be done in a seperate PR because the whole classes of the login page have to be rewritten. There is so much unneeded additional classes there...

The scope of the PR was to add the options as successfuly tested, and I will create a new PR so change the markup afterwards.

2018-09-11 13:38 UTC, mbabker commented
"Basic Options" is still an arbitrary measure, and that's kind of my point.  It's not that the options are bad necessarily, but different viewpoints are going to suggest that different customizations should be offered through the template style edit page and not require custom CSS or whatnot.  If there is an agreed upon list of changes that will be supported through the template style edit page, that's fine, I just don't want us entertaining options for too many elements personally.

2018-09-11 13:46 UTC, coolcat-creations commented
@mbabker 

Login Page: Vendor Logo, Show/hide sitename, background color, background image
Backend: Setup colors

For more changes:
Maybe a possibility to add custom.scss

For (even) more changes:
Admin has to create a fork...

Ok?

2018-09-11 13:51 UTC, coolcat-creations commented
@mbabker thank you - done - I planned to have all settings on one tab in future thats why I used the spacer, but changed it now to own tab

2018-09-11 14:40 UTC, brianteeman reviewed
Please do not merge yet. The language strings are not correct. I won't get a chance to review until tomorrow.

2018-09-11 14:44 UTC, mbabker submitted a review, later dismissed

2018-09-11 14:45 UTC, mbabker commented
(Marking my requested changes as completed, not that PR is 100% "good")

2018-09-11 14:49 UTC, Quy commented on administrator/templates/atum/templateDetails.xml
> +				>
Indent

2018-09-11 14:54 UTC, coolcat-creations commented on administrator/templates/atum/templateDetails.xml
> +				>
@Quy you mean that the whole config block has to have an indent generally?

2018-09-11 15:03 UTC, SharkyKZ commented on administrator/templates/atum/templateDetails.xml
> +				>
Just line 58. `>` has to align with `<` of `<option>` on the next line.

2018-09-11 15:06 UTC, franz-wohlkoenig commented
> The language strings are not correct.

@brianteeman should RTC set back on Pending?

2018-09-11 15:08 UTC, coolcat-creations commented on administrator/templates/atum/templateDetails.xml
> +				>
Thank you

2018-09-12 07:33 UTC, brianteeman commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_ATUM_BACKEND_LOGIN="Joomla Administrator login"
Please capitalise all words as it is a label

2018-09-12 07:33 UTC, brianteeman commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_ATUM_LOGINLOGO_LABEL="Login Logo"
For readability can you change this to LOGIN_LOGO and then re-alphasort

2018-09-12 07:34 UTC, brianteeman commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_ATUM_SHOWSITENAME_LABEL="Show site name"
Please capitalise all words as it is a label
Shouldnt the label key be simply TPL_ATUM_SITENAME_LABEL

2018-09-12 07:34 UTC, brianteeman commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_BACK_TO_CONTROL_PANEL="Back to Control Panel"
Please put this line back where it was so that the strings are alpha sorted

2018-09-12 07:35 UTC, brianteeman commented on administrator/templates/atum/login.php
> +
remove blank line

2018-09-12 07:36 UTC, brianteeman commented on administrator/templates/atum/login.php
> +
remove blank line

2018-09-12 07:36 UTC, brianteeman commented on administrator/templates/atum/login.php
> +
remove blank line

2018-09-12 07:36 UTC, brianteeman commented on administrator/templates/atum/login.php
> +
remove blank line

2018-09-12 07:36 UTC, brianteeman commented on administrator/templates/atum/login.php
> +
remove blank line

2018-09-12 07:38 UTC, brianteeman commented on administrator/templates/atum/templateDetails.xml
> +					class="btn-group btn-group-yesno"
In J4 this should be 
`			class="switcher"
`

2018-09-12 07:44 UTC, brianteeman commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_ATUM_SHOWSITENAME_LABEL="Show site name"
And as we no longer use words like show in the label please just make it "Site Name"

2018-09-12 07:44 UTC, brianteeman commented on administrator/templates/atum/templateDetails.xml
> +					<option value="1">JYES</option>
As we no longer use words like Show in the label this should be JSHOW and JHIDE

2018-09-12 07:47 UTC, brianteeman commented
Please set back to pending

2018-09-12 10:23 UTC, ghost commented
Status back on Pending as requested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22084">issues.joomla.org/tracker/joomla-cms/22084</a>.</sub>

2018-09-12 23:32 UTC, coolcat-creations commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_BACK_TO_CONTROL_PANEL="Back to Control Panel"
I dont' understand, I put it at the top because it starts with A... where do you want me to put it?

2018-09-13 05:42 UTC, SharkyKZ commented on administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
> +TPL_BACK_TO_CONTROL_PANEL="Back to Control Panel"
`TPL_BACK_TO_CONTROL_PANEL` should be at the bottom.

2018-09-13 05:49 UTC, SharkyKZ commented
Last commit broke codestyle in `login.php`.

2018-09-14 16:43 UTC, brianteeman requested changes

2018-09-14 16:43 UTC, brianteeman commented on administrator/templates/atum/templateDetails.xml
> +					type="switcher"
You must have misunderstood my comment here https://github.com/joomla/joomla-cms/pull/22084#discussion_r216925365 and then not tested it

The type is still radio but the class should be switcher

2018-09-17 11:52 UTC, merged

2018-09-17 11:52 UTC, wilsonge commented
Thanks guys!