[com_modules] Wrong module selected after Save & New
joomla/joomla-cms pull request #22156
Opened 2018-09-13 06:39 UTC by SharkyKZ

Pull Request for Issue # .

### Summary of Changes

This fixes the issue of site version of a module being created when using `Save & New` in administrator module form.

### Testing Instructions

Go to module list.
Filter by `Administrator` client.
Create and save `mod_login`, `mod_custom` or `mod_feed` module for administrator.
Click `Save & New`

### Expected result

New form opens with the same type of administrator module selected.

### Actual result

New form opens with site version of the module selected.

### Documentation Changes Required
No.

2018-09-13 07:01 UTC, alikon requested changes
use $db->quoteName()

2018-09-13 07:01 UTC, alikon commented on administrator/components/com_modules/models/module.php
> +			->join('LEFT', '#__modules AS m ON e.client_id = ' . (int) $table->client_id . ' AND e.element = m.module')
please use `$db->quoteName()`

2018-09-13 13:33 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 8cad12e0215356880dbeb951551accea88643723<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22156">issues.joomla.org/tracker/joomla-cms/22156</a>.</sub>

2018-09-16 16:22 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 8cad12e0215356880dbeb951551accea88643723<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22156">issues.joomla.org/tracker/joomla-cms/22156</a>.</sub>

2018-09-16 16:27 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22156">issues.joomla.org/tracker/joomla-cms/22156</a>.</sub>

2018-09-18 01:25 UTC, merged