Separate columns for group and permissions button
joomla/joomla-cms pull request #22190
Opened 2018-09-15 08:16 UTC by chmst

### Summary of Changes
In user groups list view: Bring the "advanced permission" link to an own column.

![usergroups](https://user-images.githubusercontent.com/1035262/45584229-319ed000-b8d0-11e8-9c12-4dc573a8b1da.PNG)

### Documentation Changes Required
yes

2018-09-15 08:19 UTC, chmst commented
I would like to have another icon for "get a permission report" - but not sure what could be a good visualisation. Maybe the eye?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22190">issues.joomla.org/tracker/joomla-cms/22190</a>.</sub>

2018-09-15 09:05 UTC, brianteeman commented
I wouldn't use the eye as we use that for revealing a password - I actually thought the icon you chose was perfect. I can't think of another really suitable one. 

I really like this PR

2018-09-15 09:46 UTC, chmst commented
Thank you. So I let this icon. It is also a a11y improvement for people with spastics (and without ... )

2018-09-15 11:26 UTC, brianteeman commented
Off topic. In the UK the word spastic although technically correct has become a very offensive word and we don't use it.

2018-09-15 11:38 UTC, chmst commented
Thank you @brianteeman. How embarassing. It was not my intention

2018-09-15 12:01 UTC, brianteeman commented
i was sure it wasn't

2018-09-15 12:23 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 60914a43fa69707ab63c83695beef18c2cd7171f<br /><br />Have tested patch successfully. OT: As my patchtester doesn't work at the moment, I changed the file: administrator/components/com_users/tmpl/groups/default.php accordingly. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22190">issues.joomla.org/tracker/joomla-cms/22190</a>.</sub>

2018-09-15 12:25 UTC, brianteeman commented
What do you think about removing the word "advanced" from the heading. Its a pretty long heading in english and possibly even longer in other languages

2018-09-15 12:25 UTC, ChristineWk commented
OT: As my patchtester doesn't work at the moment, I changed the file: administrator/components/com_users/tmpl/groups/default.php accordingly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22190">issues.joomla.org/tracker/joomla-cms/22190</a>.</sub>

2018-09-15 12:33 UTC, chmst commented
I'd like to remove the "advanecd". It has not information, because no "not advanced" report exists. 
Can you do it?

2018-09-15 12:33 UTC, brianteeman commented
just add the change to this pr

2018-09-15 12:41 UTC, brianteeman approved these changes
approve language changes

2018-09-15 12:43 UTC, chmst commented
The "Advanced" is still in some Texts. Not sure what it exactly means, so I did not change it for other language keys.

2018-09-15 13:23 UTC, brianteeman commented
Will you be making a similar change to the users view?

2018-09-15 13:31 UTC, chmst commented
The change itself is easy and I will do it. Let's see ifthere is sufficient place in the table head

2018-09-15 13:35 UTC, brianteeman commented
we might be able to just use "permissions" in the head

2018-09-15 14:07 UTC, chmst commented
I've lost my struggle with github, wanted to make a new PR but now it is here

2018-09-15 14:11 UTC, brianteeman requested changes
Make the header text the same on both for consistency. Permissions on its own looks fine to me

2018-09-15 14:14 UTC, brianteeman commented
And what to do you think about removing the ability to conditionally display this column. I only did it that way in j3 to avoid any discussion about it being a b/c change. Personally I would remove the condition but I'm ok if you want to keep it

2018-09-15 14:20 UTC, chmst commented
I agree to remove it. Who can see users and usergroups can also see the permissions. I did not know the reason for the condition. When I leaned 1.6.. 2.5, the permissions were only visible in debug mode, maybe for performance?

2018-09-15 14:22 UTC, brianteeman commented
Iirc they were an afterthought. Let's remove them for J4 and move forward. Thanks for doing this.

2018-09-15 14:23 UTC, chmst commented
There are params in the "Advanced Tab".  Kind of "hidden secrets" :)

2018-09-15 15:01 UTC, Quy commented on administrator/components/com_users/tmpl/groups/default.php
> +									<th style="width:10%" class="text-center">
Add `scope="col"`

2018-09-15 15:05 UTC, Quy commented on administrator/components/com_users/tmpl/groups/default.php
> +								<?php endif;?>
Add space after `;`

2018-09-15 15:05 UTC, Quy commented on administrator/components/com_users/tmpl/users/default.php
> +								<?php endif;?>
Add space after `;`

2018-09-15 15:06 UTC, Quy commented on administrator/components/com_users/tmpl/users/default.php
> +									<th sclass="text-center">
Add `scope="col"`

2018-09-15 15:14 UTC, brianteeman commented
Yes. it was me that put them there. They can go now as well.

2018-09-15 21:13 UTC, brianteeman commented
Now that we have changed the title to just "Permissions" can you update the following as well please for consistency
```
COM_USERS_VIEW_DEBUG_GROUP_TITLE="Advanced Permissions Report for Group #%d, %s"
COM_USERS_VIEW_DEBUG_USER_TITLE="Advanced Permissions Report for User #%d, %s"
```

Then it's all good to go for me.

2018-09-16 08:30 UTC, brianteeman approved these changes
approve language changes

2018-09-16 08:30 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 4cbbe993128c98858c8c5adf334abd5622d4d32d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22190">issues.joomla.org/tracker/joomla-cms/22190</a>.</sub>

2018-09-16 08:45 UTC, brianteeman commented
thanks @chmst great improvement

2018-09-16 08:53 UTC, alikon commented
yes indeed
can be backported on 3.X too ? @chmst

2018-09-16 08:57 UTC, brianteeman commented
@alikon if backported it would need to keep the conditional display of the column

2018-09-16 09:02 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 4cbbe993128c98858c8c5adf334abd5622d4d32d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22190">issues.joomla.org/tracker/joomla-cms/22190</a>.</sub>

2018-09-16 09:04 UTC, alikon commented
@brianteeman  even if

2018-09-16 09:11 UTC, chmst commented
I'll do it ;) because every times when I'm in the userr administration I click the wrong link

2018-09-16 10:29 UTC, chmst commented
@brianteeman @alikon what do you think? for staging or for 3.9?

2018-09-16 11:05 UTC, brianteeman commented
staging

2018-09-16 16:09 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22190">issues.joomla.org/tracker/joomla-cms/22190</a>.</sub>

2018-09-17 05:55 UTC, merged

2018-09-17 05:55 UTC, laoneo commented
Thanks

2018-09-17 17:12 UTC, PhilETaylor commented
While this is a **million times better than before,** Im not convinced its the right place for it. 

I think the notes and the APR should be tabs in the Edit User view instead as thats the more logical place for them

The Add Notes is an action, so could also have been in the actions menu button. (which I dont see in these screenshots, darn admin template strikes again)

2018-09-17 22:13 UTC, chmst commented
I think it is a grea idea to have the permissions also in a tab in the edit screen.

But when I am working with ACL, I use to check the permissions of users one by one in the list view and compare if it is right. It would cost me more time to go to the edit screen for every user. So I think it is all right to have the links on the list view.

2018-09-17 22:20 UTC, brianteeman commented
moving add a note to the toolbar is a good idea