Separate columns for name and link to permission
joomla/joomla-cms pull request #22209
Opened 2018-09-16 13:36 UTC by chmst

### Summary of Changes
In Users and Usergroups: Make an extra column for the permissions report. 

### Testing Instructions
See https://github.com/joomla/joomla-cms/pull/22190 

Compare The list views of user groups before and after patch. 
Check if the links call the appropriate permissions. 

### Documentation Changes Required
lyouts have changed a littel bit

2018-09-16 16:35 UTC, Quy commented on administrator/components/com_users/views/users/tmpl/default.php
> +									<span class="icon-list hasTooltip" aria-hidden="true" title="<?php echo JText::_('COM_USERS_DEBUG_USER'); ?>"></span>
Use `COM_USERS_DEBUG_USERS_DESC`

2018-09-16 16:35 UTC, Quy commented on administrator/components/com_users/views/groups/tmpl/default.php
> +									<span class="icon-list hasTooltip" aria-hidden="true" title="<?php echo JText::_('COM_USERS_DEBUG_GROUPS_DESC'); ?>"></span>
Add `<span class="element-invisible"><?php echo JText::_('COM_USERS_DEBUG_GROUPS_DESC'); ?></span>`

2018-09-16 20:19 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 6c179a553c04daf4b3ac8e5c9b84c38fbd2c1079<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22209">issues.joomla.org/tracker/joomla-cms/22209</a>.</sub>

2018-09-17 13:41 UTC, Quy commented on administrator/components/com_users/views/users/tmpl/default.php
> +							<th width="5%" class="nowrap">
Add class `center`

2018-09-17 13:41 UTC, Quy commented on administrator/components/com_users/views/groups/tmpl/default.php
> +							<td class="center btns" >
Remove space after `"`

2018-09-17 13:42 UTC, Quy commented on administrator/components/com_users/views/users/tmpl/default.php
> +							<td class="center">
Add `btns` to be consistent with the same column in Groups?

2018-09-18 08:30 UTC, brianteeman approved these changes
approve language changes

2018-09-18 12:52 UTC, Quy commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_DEBUG_GROUP="Permissions "
Remove space before `"`

2018-09-18 15:31 UTC, Quy commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_DEBUG_GROUPS_LABEL="Group Permissions"
Should this be `Groups`?

2018-09-18 16:23 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_DEBUG_GROUPS_LABEL="Groups Permissions"
In this context I would stick with group

2018-09-18 17:06 UTC, chmst commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_DEBUG_GROUPS_LABEL="Groups Permissions"
Sry, I do not understand. You think it is better Group (singular?) We have also Users (Plural).
It is your decision - but better do use the same form for both?

2018-10-17 15:59 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_DEBUG_GROUPS_LABEL="Group Permissions"
No. If anything it would be Groups' but thats hard to read. On the basis of improved readability this is fine

2018-11-28 16:25 UTC, lavipr commented
I have tested this item :white_check_mark: successfully on 0be456a530465202339cc87ef7d07ac568abc315<br /><br />Compared the list views of user groups before and after patch.
Checked if the links call the appropriate permissions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22209">issues.joomla.org/tracker/joomla-cms/22209</a>.</sub>

2018-11-29 07:15 UTC, infograf768 requested changes

2018-11-29 07:15 UTC, infograf768 commented on administrator/components/com_users/views/groups/tmpl/default.php
> +							<th width="10%" class="nowrap center">
Please delete all tabs after `class="nowrap center">`

2018-11-29 07:15 UTC, infograf768 commented on administrator/components/com_users/views/users/tmpl/default.php
> +							<th width="5%" class="nowrap center">
Please delete all tabs after `class="nowrap center">`

2018-11-29 07:15 UTC, infograf768 commented on administrator/components/com_users/views/users/tmpl/default.php
> +							<td class="center btns">
Please delete tabs and space after `<td class="center btns">`

2018-11-29 07:18 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_DEBUG_DESC="Display the Permission."
Should be a plural:
`COM_USERS_DEBUG_DESC="Display the Permissions"

2018-12-18 05:19 UTC, Quy commented on administrator/components/com_users/views/groups/tmpl/default.php
> +							<th width="10%" class="nowrap center">
```suggestion
							<th width="10%" class="nowrap center">
```

2018-12-18 05:19 UTC, Quy commented on administrator/components/com_users/views/users/tmpl/default.php
> +							<th width="5%" class="nowrap center">
```suggestion
							<th width="5%" class="nowrap center">
```

2018-12-18 05:19 UTC, Quy commented on administrator/components/com_users/views/users/tmpl/default.php
> +							<td class="center btns">
```suggestion
							<td class="center btns">
```

2018-12-18 05:20 UTC, Quy commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_DEBUG_DESC="Display the Permission."
```suggestion
COM_USERS_DEBUG_DESC="Display the Permissions."
```

2019-04-26 12:06 UTC, franz-wohlkoenig commented
Can this be closed as #22190 is merged in J4?

2019-04-26 18:24 UTC, closed without merging