Workflow article buttons
joomla/joomla-cms pull request #22393
Opened 2018-09-26 22:18 UTC by bembelimen

Pull Request for Issue #21818 #21708 #21527 .

### Summary of Changes
Based on the PR #21247 the action buttons (publish, unpublish, archive, trash) are readded and grouped.

First we need this PR to have all buttons in place: #21532 so perhaps someone could reactivate it. 

Thanks to @lavipr for the JS code and @ciar4n for the main idea.

### Testing Instructions
1. Create several workflows
2. Create articles
3. Try out the differnt buttons

### Expected result
Articles change stage by pressing the buttons

2018-09-26 22:55 UTC, brianteeman commented
CSS should not be committed only scss please

2018-09-27 04:34 UTC, ggppdk commented on administrator/components/com_content/Model/ArticleModel.php
> +					Log::add(Text::_('JLIB_APPLICATION_ERROR_EDITSTATE_NOT_PERMITTED'), Log::WARNING, 'jerror');
This message is the exactly the same for all records,
either (outside of the loop) add a total count of records not permitted
or add some more information to like the record ID to every message

Furthermore the JTable name is missing from the error message making it rather unusable for someone looking at the log

2018-09-27 09:38 UTC, bembelimen commented on administrator/components/com_content/Model/ArticleModel.php
> +					Log::add(Text::_('JLIB_APPLICATION_ERROR_EDITSTATE_NOT_PERMITTED'), Log::WARNING, 'jerror');
Hi @ggppdk thanks for your idea, yes you're right, there should be more information regarding the "broken" item. At the moment only one message will be generated, because afterwards the method returns.
The message is the default message from Joomla! I'm happy to add more information, should the default be changed @brianteeman ?

2018-09-27 11:43 UTC, brianteeman requested changes
sorry - forgot to press submit

2018-09-27 11:43 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_ERROR_CANNOT_ARCHIVE="One or more of the selected articles cannot set to archived."
Can't be not cannot

2018-09-27 11:43 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_ERROR_CANNOT_ARCHIVE="One or more of the selected articles cannot set to archived."
And the strings below

2018-09-27 11:43 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%s <small>(ID: %s)</small>"
We must avoid meaningless language strings like this.

2018-09-27 11:43 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_CHANGE_STAGE_AMBIGUOUS_TRANSITIONS="Some transitions are ambiguous for this condition. Please select your prefered transition and proceed."
Preferred

2018-09-27 12:12 UTC, bembelimen commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%s <small>(ID: %s)</small>"
Here the "idea" was to support rtl languages...not sure, how I should solve this?

2018-09-27 12:46 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%s <small>(ID: %s)</small>"
If you meant the two %s to be different then your string is wrong see the docs  https://docs.joomla.org/Formatted_fields_in_language_translation_strings as translators wouldn't know which variable is which to get them in the correct order of parts in their language

2018-09-27 13:24 UTC, bembelimen commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%s <small>(ID: %s)</small>"
Thx

2018-09-27 13:32 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
The code is correct now - but it is still impossible for a translator to understand what to do here. Remember most translation takes place outside of joomla. 

I will check out this pr later today and see what I can suggest

2018-09-27 13:56 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
sorry I am a bit lost when is this string used

2018-09-27 13:56 UTC, brianteeman commented
first impressions very nice

2018-09-27 15:34 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
What can be done is adding a comment above the string. No blank line.
; In the string below, %1$s represents the title of the article

2018-09-27 20:07 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
unfortunately we know most translators dont read those comments. :(

I am still trying to work out when this string is used so we can look at making it usable

2018-09-28 07:16 UTC, bembelimen commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
Create another stage in teh default workflow called "Publish 2" with the condition "published". Create a transition "All => Publish 2". Unpublish an article and then publish it with the button.

2018-09-28 07:58 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
> unfortunately we know most translators dont read those comments. :(

Indeed crowdin does not display them but If they use com_localise they will:
<img width="1422" alt="screen shot 2018-09-28 at 09 45 39" src="https://user-images.githubusercontent.com/869724/46195132-b263c000-c303-11e8-8a25-54b9d1bc735b.png">

2018-09-28 08:41 UTC, brianteeman commented
Since applying this pr and running npm i I am missing various icons
![image](https://user-images.githubusercontent.com/1296369/46197731-83008380-c302-11e8-8e78-ccdd47ed4e84.png)
![image](https://user-images.githubusercontent.com/1296369/46197760-927fcc80-c302-11e8-9958-6e6c0e0fe55c.png)


Where the icon is missing - clicking on them gives a javascript error
```
Uncaught TypeError: Cannot read property '10' of null
    at Object.e.listItemTask (core.min.js?8be5a883767042ad65bf41d1f0f59c51:1)
    at HTMLAnchorElement.onclick (index.php?option=com_workflow&view=workflows&extension=com_content:436)
e.listItemTask @ core.min.js?8be5a883767042ad65bf41d1f0f59c51:1
onclick @ index.php?option=com_workflow&view=workflows&extension=com_content:436
```

2018-09-28 08:44 UTC, brianteeman commented
Dropdown styling consistency

This is the current styling for the save menu with dropdown - note the icons are mono and the hover matches the button colour
![image](https://user-images.githubusercontent.com/1296369/46197876-e985a180-c302-11e8-9223-e521ef638c18.png)

The new dropdown for change status uses coloured icons and the hover highlight is a very pale grey which is hard to see
![image](https://user-images.githubusercontent.com/1296369/46197930-120d9b80-c303-11e8-9f06-b13f779fc2ea.png)

2018-09-28 08:49 UTC, bembelimen commented
> Since applying this pr and running npm i I am missing various icons

This is an issue in J! 4.0 in general, I think it could have to do something with: https://github.com/joomla/joomla-cms/pull/22349/files
@chmst is investigating atm.

2018-09-28 09:00 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
@bembelimen sorry I still dont see it

2018-09-28 09:57 UTC, chmst commented
@bembelimen please test this: https://github.com/joomla/joomla-cms/pull/22424

2018-09-28 13:26 UTC, bembelimen commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
![articles](https://user-images.githubusercontent.com/1229869/46210995-a9d6ae00-c332-11e8-9b6e-e11ceb6e8790.gif)

I hope it's readable...

2018-09-28 13:36 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
Thanks will check again soon

2018-09-28 14:33 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
OK I got it now - thanks for your patience - I think it would be clearer with something like
![image](https://user-images.githubusercontent.com/1296369/46214836-dc34db00-c333-11e8-9e66-3e871f164f6f.png)

2018-09-28 14:38 UTC, brianteeman commented on build/media_src/com_content/js/admin-articles-workflow-buttons.es6.js
> +            html += `<label for="">${articles[`article-${id}`]}</label>`;
To add the value for the label (which we need for a11y) change this line to
html += `<label for="publish_transitions[${id}]">${articles[`article-${id}`]}</label>`;

2018-09-28 14:40 UTC, brianteeman commented on build/media_src/com_content/js/admin-articles-workflow-buttons.es6.js
> +            html += `<select class="custom-select" name="publish_transitions[${id}]">`;
now we need to give this an id so that the label is associated with it
``` html += `<select class="custom-select" name="publish_transitions[${id}]" id="publish_transitions[${id}]">`;```

2018-09-28 14:42 UTC, brianteeman commented
commented on the code to improvements needed to the js for accessibility

2018-09-29 23:02 UTC, bembelimen commented on build/media_src/com_content/js/admin-articles-workflow-buttons.es6.js
> +            html += `<select class="custom-select" name="publish_transitions[${id}]">`;
Thx

2018-09-30 01:55 UTC, brianteeman approved these changes

2018-09-30 08:07 UTC, brianteeman commented
Thanks for the accessibility fixes. Just need the CSS to be fixed now and it's good to go

2018-10-03 21:35 UTC, bembelimen commented
Hi @brianteeman I got an update from @lavipr for the dropdown, is this the requested solution?

2018-10-04 07:04 UTC, brianteeman commented
I am not seeing any changes in the dropdown

2018-10-04 09:43 UTC, bembelimen commented
It should look like that:
![grafik](https://user-images.githubusercontent.com/1229869/46466119-b5125980-c7ca-11e8-9270-4028eccf97ca.png)

2018-10-04 09:56 UTC, brianteeman commented
I will check again later when my pc finishes updating. I still think that the icons should be mono to match the mono icons in the save drop-down as shown in the image above but I am not a designer.

2018-10-04 09:58 UTC, bembelimen commented
@lavipr is working on it.

2018-10-04 14:54 UTC, brianteeman commented
@bembelimen please post when it is ready to test

2018-10-04 14:58 UTC, bembelimen commented
Now :D sorry, only "not implemented change" is the language change...not sure about it, because we're at the article view...so they are all articles...

2018-10-04 15:00 UTC, brianteeman commented
I thought it was ready so I tested it but still dont see any change in the dropdown

2018-10-04 15:03 UTC, Quy commented on administrator/components/com_content/tmpl/articles/default_stage_footer.php
> +<button id='stage-submit-button-id' class="btn btn-success" type="submit" data-submit-task='articles.publish'>
You have a mix of single quote and double quote. Use double quote.

2018-10-04 15:05 UTC, Quy commented on administrator/components/com_content/Model/ArticleModel.php
> +		$select = $db->quoteName(
Why not make this a single line?

2018-10-04 15:06 UTC, Quy commented on administrator/components/com_content/View/Articles/HtmlView.php
> +
Remove extra blank line.

2018-10-04 15:15 UTC, bembelimen commented
Mhh @brianteeman that's strange. I just checked the branch out again and did npm, the "hover" if the elements in the dropdown are now colorful + the icons are dark.

![grafik](https://user-images.githubusercontent.com/1229869/46483977-210bb680-c7f9-11e8-9681-7fa110736db6.png)

2018-10-04 15:33 UTC, brianteeman commented
ok got it working now - I was in the wrong branch. It does what you say. 

can you remind me what is the language issue please

2018-10-04 15:47 UTC, bembelimen commented
This one: https://github.com/joomla/joomla-cms/pull/22393#pullrequestreview-159446532

2018-10-04 16:01 UTC, brianteeman commented
> not sure about it, because we're at the article view...so they are all articles...

Thats true but presumably we will be using this dropdown throughout joomla so in those cases it would says something else.

2018-10-10 15:16 UTC, uglyeoin commented
Just a suggestion, but could the dropdown match the width of the parent button (as a minimum).  Just my opinion, happy if it doesn't get implemented but I think it would look better. I also think it would look nice if it touched the border, but I think that would cause some issue in terms of hovering on it potentially.

2018-10-10 15:23 UTC, brianteeman commented
It could only be a minimum width as the text may be longer in non English lamguages

2018-10-10 17:42 UTC, uglyeoin commented
> It could only be a minimum width as the text may be longer in non English lamguages

of course and a new option could potentially be added in the future.

2018-10-18 08:31 UTC, laoneo commented
@bembelimen can you make the dog happy and then it would be good to have a successful test here.

2018-10-27 09:45 UTC, bembelimen commented
@laoneo the dog is happy now :)

2018-11-08 09:46 UTC, C-Lodder commented on administrator/components/com_content/Model/ArticleModel.php
> +		\JPluginHelper::importPlugin($this->events_map['change_state']);
`\JPluginHelper` > `PluginHelper`

2018-11-08 09:54 UTC, C-Lodder commented on build/media/webcomponents/js/toolbar-button/toolbar-button.js
> +          if (this.buttonElement.nodeName === 'BUTTON') {
use `tagName` instead of `nodeName`

2018-11-08 09:54 UTC, C-Lodder commented on build/media/webcomponents/js/toolbar-button/toolbar-button.js
> +          if (this.buttonElement.nodeName === 'BUTTON') {
use `tagName` instead of `nodeName`

2018-11-15 08:59 UTC, bembelimen commented on build/media/webcomponents/js/toolbar-button/toolbar-button.js
> +          if (this.buttonElement.nodeName === 'BUTTON') {
Could you elaborate, why? (https://stackoverflow.com/a/4878522)

2018-11-15 09:03 UTC, C-Lodder commented on build/media/webcomponents/js/toolbar-button/toolbar-button.js
> +          if (this.buttonElement.nodeName === 'BUTTON') {
@bembelimen It's faster

2018-11-15 09:05 UTC, bembelimen commented on administrator/components/com_content/Model/ArticleModel.php
> +		\JPluginHelper::importPlugin($this->events_map['change_state']);
Thx

2018-11-15 13:12 UTC, chmst commented
I have tested this item :white_check_mark: successfully on aacb27f932284e3c8c2fdfc15a1011751e900c58<br /><br />I have tested this item successfully on the latest v4.0. dev. (After npm install).
With different combinations and different workflows - also featured and non-featured and checke_out articles. Everything works as expected and really like this.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22393">issues.joomla.org/tracker/joomla-cms/22393</a>.</sub>

2018-11-28 16:19 UTC, fancyFranci commented
I have tested this item :white_check_mark: successfully on aacb27f932284e3c8c2fdfc15a1011751e900c58<br /><br />Tested with different stages and transitions and the patch worked as expected, with some grey status and helpful messages.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22393">issues.joomla.org/tracker/joomla-cms/22393</a>.</sub>

2018-11-28 17:16 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22393">issues.joomla.org/tracker/joomla-cms/22393</a>.</sub>

2018-12-25 22:00 UTC, merged

2018-12-25 22:01 UTC, wilsonge commented
Thanks

2018-12-26 10:10 UTC, bembelimen commented
Thanks @wilsonge now we need this PR reopened to remove the unnecessary trash button: https://github.com/joomla/joomla-cms/pull/21532