Option to disable save article hits
joomla/joomla-cms pull request #22413
Opened 2018-09-27 20:12 UTC by jurihahn

Pull Request for Issue #22406 .

### Summary of Changes
Option for Disable Hits counter increment

### Testing Instructions
1. Open an article and check if the hits do increase
2. Go to content options and Set "Save Hits" to "NO"
3. Open an article and check if the hits do not increase

### Expected result
If disabled, article hits do not increase

### Actual result
article hits do not increase always

### Documentation Changes Required
no?

2018-09-27 20:30 UTC, brianteeman requested changes

2018-09-27 20:30 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FIELD_SAVEHITS_LABEL="Save Hits"
==>
"Record Hits"

2018-09-27 20:30 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FIELD_SAVEHITS_DESC="If you want to display the hits, then select YES to save the number of hits."
its not display its record so

==>
"Record the number of hits."

2018-09-28 03:43 UTC, effrit commented
Cool, thanks! Tested successfully. What need to do to approve testing?

2018-09-28 04:08 UTC, ggppdk commented on administrator/language/en-GB/en-GB.com_content.ini
> +COM_CONTENT_FIELD_SAVEHITS_LABEL="Save Hits"
Is "Count hits" a better term ?
as this feature does not keep "records" of the hits ?

2018-09-28 04:48 UTC, jurihahn commented
@effrit go to Joomla Issue Tracker and click "Test this"
https://issues.joomla.org/tracker/joomla-cms/22413

2018-09-28 05:05 UTC, franz-wohlkoenig commented
@effrit if needed:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/22413)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

2018-09-28 05:08 UTC, effrit commented
I have tested this item :white_check_mark: successfully on ea5a30869ee9686c35a96629725c64c7669e5aa0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-09-28 05:52 UTC, SharkyKZ commented
If accepted, shouldn't this be done for all items using hits functionality?

2018-09-28 06:24 UTC, jurihahn commented
@SharkyKZ i can do this in future PR's

2018-09-28 06:46 UTC, effrit commented
@SharkyKZ, which one? Examples?

2018-09-28 07:05 UTC, SharkyKZ commented
Contacts, newsfeeds and tags. Categories also have code for hit functionality but it doesn't seem to get executed. Was thinking that, if this is added to categories, the strings should differentiate between content types. But if not, they should be made global.

Also realized hitcounts can be easily controlled by a plugin. This is already done with vote plugin to prevent increasing count when voting. That said, does an option really needs to be added? Plugin could give more control such as suggested in the forum https://forum.joomla.org/viewtopic.php?f=706&t=965788.

2018-09-28 07:19 UTC, effrit commented
@SharkyKZ, it must be plugin AFTER this implementation done. So u will can use this BD field without standard mad increment. 
And read about others request - about DB cache. With this implementations they also will be satisfied.
So this modifications is simple and useful solution for 2 issues.

2018-09-28 07:29 UTC, SharkyKZ commented
@effrit No, the plugin can easily disable hitcount by setting `hitcount` var to 0:

https://github.com/joomla/joomla-cms/blob/c31ff5105085ce6d3bde3ea7dea96dd538bc6fd6/components/com_content/models/article.php#L241-L256

This allows manipulation requested in the forum thread. E.g. to prevent same user from increasing the count twice or to disable robot hits.

2018-09-28 07:41 UTC, effrit commented
@SharkyKZ, even so, why i need install the plugin if i just dont need this counter?
i guess i am not only one who never use it.

2018-09-28 09:35 UTC, dmitrystas commented
I have tested this item :white_check_mark: successfully on ea5a30869ee9686c35a96629725c64c7669e5aa0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-09-28 12:53 UTC, franz-wohlkoenig commented
Ready to Commit after two successful tests.

2018-09-28 13:44 UTC, Quy commented on components/com_content/controller.php
> +				$config   = ComponentHelper::getParams('com_content');
Lines 111-112 can be combined `if (ComponentHelper::getParams('com_content')->get('save_hits', 1) == 1)`

2018-09-28 13:47 UTC, Quy commented on administrator/components/com_content/config.xml
> +			label="COM_CONTENT_FIELD_SAVEHITS_LABEL"
Change `save_hits` to `record_hits`?
Change `SAVE` to `RECORD` in the language keys?

2018-09-28 19:11 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 19dfbb3a03e9dc1db3116925e4a8bd3b08a8b5a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-09-28 20:26 UTC, effrit commented
I have tested this item :white_check_mark: successfully on 19dfbb3a03e9dc1db3116925e4a8bd3b08a8b5a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-09-28 20:28 UTC, dmitrystas commented
I have tested this item :white_check_mark: successfully on 19dfbb3a03e9dc1db3116925e4a8bd3b08a8b5a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-09-29 09:49 UTC, effrit commented
Hey, what else we need to do?
Who must implement changes requested by brianteeman?

2018-09-29 10:13 UTC, infograf768 commented
The PR is RTC. The changes were done. Nothing else to do than wait for @mbabker to merge. :)

2018-09-29 10:17 UTC, alikon commented on components/com_content/controller.php
> +				if (ComponentHelper::getParams('com_content')->get('record_hits', 1) == 1)
===
shouldn't be better ?

2018-09-29 10:33 UTC, jurihahn commented on components/com_content/controller.php
> +				if (ComponentHelper::getParams('com_content')->get('record_hits', 1) == 1)
Why? Type is not important.

2018-09-29 10:41 UTC, alikon commented on components/com_content/controller.php
> +				if (ComponentHelper::getParams('com_content')->get('record_hits', 1) == 1)
standard maybe ?

2018-09-29 11:18 UTC, SharkyKZ commented
Last commit (69ea8a2205f21e2a13461ef790b528decdc0be0d) doesn't work right. If you want to use type-safe comparison, add filter to form field or at least cast value as integer.

Also, since string remains generic can you move it to global language files?

2018-09-29 15:23 UTC, infograf768 commented
Set back to pending until tested new code<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-09-29 16:32 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 22c8e61b443509e6621d13165768908c101497aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-09-29 16:41 UTC, dmitrystas commented
I have tested this item :white_check_mark: successfully on 22c8e61b443509e6621d13165768908c101497aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-09-29 16:42 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22413">issues.joomla.org/tracker/joomla-cms/22413</a>.</sub>

2018-10-02 16:12 UTC, merged