[4.0][RFC]  Elephant can manage assets also. The WebAssetRegistry class to manage assets and it`s dependacies
joomla/joomla-cms pull request #22435
Opened 2018-09-30 10:40 UTC by Fedik

Pull Request for Issue #12402, improved version of #8913 .

### Summary of Changes
The patch introduce new class `WebAssetRegistry` to manage the assets, and it's dependencies.
**The assets** - > read as CSS/JS library.

#### How it works
All registry information stored in a registry file, a simple `json` file called `joomla.asset.json`.
I made an example for `media/vendor/joomla.asset.json`, `media/system/joomla.asset.json`, and for each template `atum/joomla.asset.json`, `cassiopeia/joomla.asset.json`.

The Registry file are for:
 * The registry file contain an information about provided assets. 
 * Each asset provide dependencies, and js/css files which be attached to the Document on header rendering event.
 * Each asset can be overridden by another registry file (take a look in `atum/joomla.asset.json` where overridden `bootstrap.css`, and `font-awesome`).

**To add your registry file:**
```php
Factory::getContainer()->get('webasset')
  ->addRegistryFile('media/blabla/path/joomla.asset.json')
```

**How to use, enable/disable assets:**
```php
/** @var Joomla\CMS\WebAsset\WebAssetRegistry $wa */
$wa = Factory::getContainer()->get('webasset');

// Enable Core asset
$wa->enableAsset('core');
// If the asset do not exists, then Exception will be thrown

// Disable Bootstrap CSS
$wa->disableAsset('bootstrap.css'); 
// bootstrap.css - is an asset name, not a file name !!!
// look in media/vendor/joomla.asset.json to see why
```

**NOTE:** Method `enableAsset()` / `disableAsset()` do NOT add anything to the document. It just change the asset state. The files of all active assets will be attached to the Document on before header rendering.

By default `WebAssetRegistry` use a "lazy loading" of assets.
The registry file parsed only when `WebAssetRegistry` requested for new asset.
All dependencies will be resolved while attaching WebAssetRegistry to the document. See `WebAssetRegistry::attach()`

Also I have made an example in `behavior.core`, `bootstrap.framework`.

### Further changes/ideas
Allow custom class per asset, that can handle stuff like in 'behavior.core':
```php
function onBeforeAtach() {
  $doc->addScriptOptions('system.paths', [
	'root' => Uri::root(true),
	'rootFull' => Uri::root(),
	'base' => Uri::base(true),
  ]);
}
```
In theory, this allow to clean up JHtml from adding a scripts.

For now feedback are welcome! :neckbeard: 

### Documentation Changes Required
yes, if it will be accepted

ping @wilsonge @mbabker @dgrammatiko @C-Lodder @laoneo 
also everyone else who doing frondend stuff

2018-09-30 11:22 UTC, ggppdk commented
Looks very nice, 

is there some debugging (implemented already) ? or can such debugging be added ? 

- what the following call will register to be added to the document (later by `WebAssetRegistry::attach()`) ?

```php
$wa->enableAsset('template.atum.' . ($this->direction === 'rtl' ? 'rtl' : 'ltr'));
```
- what has already been registered for added by some previous call and by who 

i mean without looking and figuring out ourselves dependencies out of the json files
but also to help verify what we put inside the json file is correct

2018-09-30 11:31 UTC, Fedik commented
> is there some debugging (implemented already) ? or can such debugging be added ?

sure, `WebAssetRegistry::getActiveAssets()`, `WebAssetRegistry::getAssetsByState()`
and small debuging method I made for temporary `WebAssetRegistry::debugAssets()`

also can do: 
```php
$asset = $WebAssetRegistry->getAsset('blabla');
if ($asset && $asset->isActive())
{
  echo "it alive!!! (:";
}
```

2018-09-30 11:56 UTC, brianteeman commented
There appears to be inconsistent use of the minified files

2018-09-30 11:59 UTC, Fedik commented
> There appears to be inconsistent use of the minified files

where the inconsistent?

2018-09-30 12:19 UTC, brianteeman requested changes

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetItem.php
> +	 * List of JavaScript files, ant it's attributes.
And not ant :)

2018-09-30 12:19 UTC, brianteeman commented on build/build-modules-js/update.js
> +          // Check if there any attribute to this file, then update the path
there are any

2018-09-30 12:19 UTC, brianteeman commented on build/build-modules-js/update.js
> +          // Check if there any attribute to this file, then update the path
there are any

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetItem.php
> +	 * List of StyleSheet files, ant it's attributes
and not ant

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetItem.php
> +	 * @param   boolean  $resolvePath  Whether need to search for real path
whether we need to

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	 * Mark a broken/not-existing registry file
non-existing

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	 * Weight of the most heavier and active asset
Weight off the heaviest and most active asset

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetRegistry.php
> +		// Check if there any new file was added
Check if any new file was added

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	 * Attach an active assets to the Document
Attach active assets to the document

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetRegistry.php
> +		// Attach an active assets do the document
Attach active assets to the document

2018-09-30 12:19 UTC, brianteeman commented on libraries/src/WebAsset/WebAssetRegistry.php
> +			// Prevent duplicated work if Dependency already was activated
was already activated

2018-09-30 12:24 UTC, brianteeman commented
in   build/build-modules-js/settings.json
I assume they should all be minified - they're  not

2018-09-30 13:17 UTC, Quy commented on libraries/src/WebAsset/WebAssetItem.php
> +	 * List of JavaScript files, ant it's attributes.
Change `it's` to `its`

2018-09-30 15:32 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function __construct()
The logic in this constructor should honestly be in the service provider, or some other place external to the class.  This constructor shouldn't be arbitrarily trying to load files, and it especially shouldn't have differing behavior based on the request.

(Not to mention if you insist on using the constructor you should dependency inject the application instead of getting it from the static factory)

2018-09-30 15:36 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function attach(Document $doc)
`attach` as a method name is too vague.  With PHP 7, you really should strive to create self documenting method signatures (function name, typehinted parameters, and a return typehint) so that you don't have to rely on the doc block to actually tell you what the method is doing.  Outside this class, `$registry->attach($doc);` isn't clear.  Am I attaching a document to the registry?  Am I attaching something from the registry to the document?

2018-09-30 15:41 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +		// Add for active component
The more I read this diff, the more I'm honestly not a fan of this constructor arbitrarily handling the component or template registration.  For the component that really should be done in their dispatcher.  Templates, as we don't have anything like that yet, I'm not sure where this belongs (maybe in `$app->dispatch()` before the component is dispatched?), but this kind of automagic resolution of request dependent features really doesn't feel right in a service registry.

2018-09-30 15:42 UTC, mbabker commented on templates/cassiopeia/index.php
> +$wa   = Factory::getContainer()->get('webasset');
TBH this really should be a property of the `Joomla\CMS\Document\HtmlDocument` instance (if not part of the root Document class).  We should not need to fetch this out of the container, especially in a template.

2018-09-30 15:46 UTC, dgrammatiko commented on build/build-modules-js/settings.json
> +            "name": null,
@Fedik this should be `awesomplete` or will it work with the actual name of the parent object?

2018-09-30 15:49 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
Something feels weird about the use of enable/disable in this API.

Using WordPress terminology here, their [dependencies API](https://developer.wordpress.org/reference/classes/wp_dependencies/) has two primary responsibilities as it relates to asset management:

- Register assets (add/remove, basically determines whether the asset is actually known to the manager)
- Scheduling assets for inclusion in the document (enqueue/dequeue)

So something just feels weird about enable/disable naming.

2018-09-30 15:51 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
There should be some type of safety in here to ensure that an asset that is a dependency of something else can't be disabled.  What happens if you disable jQuery but are still using Bootstrap?

2018-09-30 15:52 UTC, mbabker commented on libraries/src/Service/Provider/WebAsset.php
> +			->alias('WebAsset', WebAssetRegistry::class)
You only need the "webasset" and `WebAssetRegistry::class` names as container keys.  No need in having several aliased names.

2018-09-30 15:52 UTC, mbabker commented on libraries/src/WebAsset/WebAssetItem.php
> +	public function __construct($name, array $data = [])
Use scalar typehinting.

```php
public function __construct(string $name, array $data = [])
```

2018-09-30 15:53 UTC, mbabker commented on libraries/src/WebAsset/WebAssetItem.php
> +	public function getName()
Use return types

```php
public function getName(): string
```

2018-09-30 15:53 UTC, mbabker commented on libraries/src/WebAsset/WebAssetItem.php
> +	public function setState($state)
Use scalar typehinting and return types, remove type cast in the method.

```php
public function setState(int $state): self
{
    $this->state = $state;

    return $this;
}
```

2018-09-30 16:00 UTC, mbabker commented
Personally, I'd rather all new events have their own Event subclasses versus everything being dispatched with the generic event class.

```php
public function onWebAssetStateChanged(Event $event): void
{
    $asset = $event->getArgument('asset');
}
```

versus

```php
public function onWebAssetStateChanged(WebAssetStateChangedEvent $event): void
{
    $asset = $event->getAsset();
}
```

You get a better self-documenting API versus having to find the triggering source code to see exactly what arguments are available.

2018-09-30 16:01 UTC, dgrammatiko commented
@Fedik nice to see that you're pushing this idea (I was always counting that you will come up with such a PR, thus I never actually deleted the assets lines in the build tools 😉 ).

There are some consideration that the production team should consider here:
- Everything in the Javascript world is becoming a module, so I guess there should be a way to manage modules along the old es5 scripts. (small explanation here: if you have a `<script type="module" src="blabla.js">` by default this script is *deferred* and scoped differently than a normal es6 script. This obviously imposes some challenges with jQuery scripts and the order of execution but it's another talk altogether). 

- I would expect J4 to be able to handle critical/lazy-loaded assets, at the end of the day these are the current best practices...

- If you keep `JHtml::script`, `JHtml::stylesheet`, `addScript`, `addStylesheet` then there will be way too many options to handle assets which obviously will make the dev life more complicated instead of simplifying things. So the question (this goes to the production team) is: are you willing to break the current status quo?

2018-09-30 16:26 UTC, Fedik commented on libraries/src/WebAsset/WebAssetItem.php
> +	 * List of JavaScript files, ant it's attributes.
or bug? :smile:

2018-09-30 18:17 UTC, Fedik commented
> in build/build-modules-js/settings.json
> I assume they should all be minified - they're not

@brianteeman there a sources, they will be minified and moved to /media while run `npm install`.
btw, thanks for English corrections, I will fix it

2018-09-30 18:19 UTC, Fedik commented on build/build-modules-js/settings.json
> +            "name": null,
yeap, it will take a name of the parent if it is empty here, 
I made `name:null` just to show that the name can be specified here also, when need different name

2018-09-30 18:27 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function __construct()
This was a quick solution, the first idea use `glob('media/*/joomla.json')` :smile: 
For a note: call of `addRegistryFile()` do not parse the file, it just check that file exists, and that all.

Parsing goes at first call of `getAsset()`.

2018-09-30 18:34 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +		// Add for active component
I also not sure where this belong. I can move it everywhere, just need to find a good place.

The thing, is ordering. The files should be added in specific order, because each next file will override assets from previous file, if there are the same assets.

The idea that first goes:
 - core assets
 - component assets
 - template assets

So I assume that the Core assets should be added immediately after `new WebAssetRegistry`.
All else, maybe you are right, I try in `$app->dispatch()`

2018-09-30 18:38 UTC, Fedik commented on templates/cassiopeia/index.php
> +$wa   = Factory::getContainer()->get('webasset');
hmhm, you suggest something like `$doc->getWebAsset()`?
I tried make it stand alone, so humans who like to add own asset `onAfterInitialisation` event, can do it safely :)

I can move it to the Document, no problem, I just not sure what is better here.

2018-09-30 18:43 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
I did not digging in wordpress api in detail, 
It looks close to their "enqueue/dequeue", but my logic is different, final dependencies resolution goes on `attach()`, based on which assets enabled.

call it *lazy dependency resolution* :smile:

2018-09-30 18:49 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
you cannot disable something esier :smirk: 

when you call `setAssetState()` it actually does nothing advanced, just chnage `WebAssetItem->state` property.

All dependacy calculation goes on `attach()`

so example, you enable **Bootstrap**, this will NOT enable **jQuery** instantly, so you cannot disable what is not enabled :wink: 
the **jQuery** will be enabled while call of `attach()`, 
see `WebAssetRegistry::attach()` and `WebAssetRegistry::resolveDependency()`

2018-09-30 18:51 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
you can remove asset via `removeAsset('jquery')`, but then `WebAssetRegistry::setAssetState()` will throw an Exception

2018-09-30 18:51 UTC, Fedik commented on libraries/src/Service/Provider/WebAsset.php
> +			->alias('WebAsset', WebAssetRegistry::class)
okay, I will remove it

2018-09-30 18:58 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function __construct()
Great that the actual parsing is deferred, but still doesn’t address that architecturally this is the wrong spot to do this but of logic.

A constructor should really only do what it takes to get the class to a serviceable state.  This is doing a lot more.  This class could not be unit tested without mocking global dependencies.  As a registry, there is no real reason to have this kind of dependency.

So architecturally it is correct that these load statements be moved elsewhere.  Yes, load order is important and must be considered too.

2018-09-30 18:58 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function attach(Document $doc)
maybe something like `attachAssetsToDocument()` or just `attachToDocument()`?
okay

2018-09-30 19:01 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
Lazy or not, it’s still rather ambiguous what “WebAsset is enabled” means.

- Does that mean the asset is known to the registry and available for use?
- Does that mean the asset is known to the registry and not available for use?
- Does that mean the asset is known to the registry and scheduled for inclusion in the document?
- Does that mean the asset is known to the registry and not scheduled for inclusion in the document?

Simple enable/disable isn’t enough here since you essentially have a registry with two separate purposes (track known assets and schedule them for inclusion in the document) and both purposes can be “enabled or disabled”.

2018-09-30 19:03 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
That seems a bit backwards to me.  If I enable an asset with dependencies I expect the dependencies to be enabled as well.  Otherwise, there’s no point in declaring and tracking dependencies.

2018-09-30 19:06 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
Things can be lazy loaded, resolved “just in time”, and whatnot, but if I put Bootstrap (the full build, not select components) into the registry and its dependencies don’t get included as well that effectively leaves the registry in an invalid state until you “attach” it to the document.

2018-09-30 19:29 UTC, Fedik commented
@dgrammatiko I think you a bit misunderstood the idea of having modules in JavaScript, or I misunderstood :neckbeard: 

The module is like a library, which doing nothing itself, no interaction with outside word, it even static.
So use a module definition for regular scripts (which doing DOM manipulation etc.) is wrong.

Also in current state, the module cannot easily live in dynamic app like CMS,
because limitation of `import`. Even when dynamical import (http://2ality.com/2017/01/import-operator.html) will be supported by all browsers, it still a question, how it can work in context of CMS. 

For my understanding CMS require a customizable loader, like `require.js`.

BUT, we still can use `defer` for regular scripts.
And I think for J4, we can do, force every script to be `defer`, and if there at least 1 inline script, we switch off the `defer` mode. 
I think it already can be done on scripts rendering.
I use similar approach in my "optimization plugin", I force every script to `defer`, and if there are inline code exist then just disabled `defer`, works fine for couple years :smiley: 

> I would expect J4 to be able to handle critical/lazy-loaded assets, at the end of the day these are the current best practices

I heard about it, but I have no idea, how it can live here :smile: 

 > JHtml::script, JHtml::stylesheet, addScript, addStylesheet

Well, they do not conflict, they are complement each other. But there huge misunderstanding what they doing.
TBH, I have no idea what we can do here.

Technically in the asset you can define any path, so you can even copy whole `/node_modules/` to your template, then define every *node_module* as asset in JSON file, and it will work. 
So yes it removes a limitation that you must place the CSS file in /css folder to make `JHtml::stylesheet` override to work.

2018-09-30 19:33 UTC, mbabker commented
> > JHtml::script, JHtml::stylesheet, addScript, addStylesheet
> 
> Well, they do not conflict, they are complement each other. But there huge misunderstanding what they doing.
> TBH, I have no idea what we can do here.
> 
> Technically in the asset you can define any path, so you can even copy whole `/node_modules/` to your template, then define every _node_module_ as asset in JSON file, and it will work.
> So yes it removes a limitation that you must place the CSS file in /css folder to make `JHtml::stylesheet` override to work.

The directory based override convention works great for end users who just need to copy a file and tweak something.  If we move to a system where you have to modify manifest files or use plugins to re-register an asset's path that's adding a bit of complexity to what has previously been a rather simple system.  So just keep that in mind.

2018-09-30 19:41 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
well, there 2 more methods:
`addAsset()` - add new asset to registry, programaticaly
`removeAsset()` - remove asset from registry, so it will gone forever, and call of `enableAsset()` will throw an exception.
and `addRegistryFile()` to add new file at any time, the file will be parsed at next call of `getAsset()` which follow after `enableAsset()`

hm hm, the Registry holds all known/available assets, User cannot enable/disable non existing, 
to do it User have to add a path to registry file or add the asset programaticaly via `addAsset()`.

what naming of this methods would be more clear? for now it is not a problem to rename

2018-09-30 19:44 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
but from other side, it protects from the case described in your first example "you disable jQuery but are still using Bootstrap" :wink:

2018-09-30 19:47 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function __construct()
yeah, I will move it to ServiceProvider

2018-09-30 19:50 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
I don't know what a "good" name is yet, but I do know that enable/disable just doesn't feel right.

2018-09-30 19:53 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
Which then gets back into my last point about the registry effectively being in an invalid state until it is attached to the document.  You pretty much can't accurately snapshot the registry internals until the `onBeforeCompileHead` event is dispatched without calling `attach()` with a fake Document object to force all the lazy loading or resolving behaviors to trigger.

2018-09-30 19:56 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +				$doc->addStyleSheet($path, ['version' => 'auto'], $attr);
Version needs to be a configurable attribute.  Not everything should use the CMS' random hash for a query string version, there is no issue with using the version string of the libraries in use (and if you're really one of those paranoid people who have issues with a version string in a URL you're really going to hate some of the file headers on assets and you can deal with changing the query string on your own).

2018-09-30 20:00 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
Maybe because of Wordpress :wink: 
For me, I know that the registry already take care of loading known assets, and holds all of them already (not like wordpress) but disabled by default, 
so for me it logical just to enable/disable them.

2018-09-30 20:08 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
hm hm, maybe registry wrong name? originally I called it *factory* :)

well, can make a `resolveDependency()` public,
then `$registry->resolveDependency()->getActiveAssets()` if need to get a snapshot.
but this can break some stuff :smile: 

need to think

2018-09-30 20:13 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +				$doc->addStyleSheet($path, ['version' => 'auto'], $attr);
I thought to use `$asset->getVersion()`, but then made `auto`, to be safe and easy,
will see

2018-09-30 20:28 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
Enable/Disable doesn't really communicate any context or meaning though beyond "the registry considers this asset enabled".  How does enabled/disabled translate outside of this class?  If it's supposed to mean "this asset will be rendered in the document" (in effect the same as `$doc->addScript()`, it's enqueued in the context of the WordPress API.

Enable/Disable is just too generic for me at this level.

2018-09-30 20:31 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function setAssetState($name, $state = WebAssetItem::ASSET_STATE_ACTIVE)
Registry, Factory, Builder, IMO it's still conceptually wrong if the only time you can actually debug it is when you've rendered the HTML document.

This might be a case of trying to be too lazy.  It's fine to defer parsing the JSON files until you actually start adding `WebAssetItem` entries to the internal store, but once you start populating `WebAssetRegistry::$assets` with objects it should always contain the full resource tree.  It really shouldn't be a partial snapshot.

2018-09-30 20:35 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +				$doc->addStyleSheet($path, ['version' => 'auto'], $attr);
I'd go for this.

If `$asset->getVersion()` has any non-empty value, use it (knowing full well "auto" is a special case inside the Document API).

Have an attribute on the registry to decide whether unversioned assets ($asset->getVersion === '') should be auto-versioned (the `['version' => 'auto']` bit that's here now) or left unversioned.  Default it to true, let someone turn it off if they choose to.

2018-10-01 17:58 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function __construct()
moved to ServiceProvider and $app->dispatch

2018-10-01 18:00 UTC, Fedik commented on templates/cassiopeia/index.php
> +$wa   = Factory::getContainer()->get('webasset');
I made it as `Document->getWebAssetManager()`

2018-10-01 18:04 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
Couple more suggestions:
activate / deactivate
activateKnownAsset / deactivateKnownAsset
makeActive / makeInactive

I would be fine with just `on`/`off` :smile: 

Here is do not need to add anything, just need to "turn on"/ "turn off" existing stuff. 
It hard to compare with wordpress and `$doc->addScript()`, where you actually should add something.

2018-10-01 18:13 UTC, mbabker commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
None of that helps any.  What does an enabled asset in the registry actually mean?  Maybe if that can be explained it can be turned into something with a more clear name.  But enabling/disabling an asset, or activating/deactivating, or turning an asset on or off doesn't mean squat.  If I am calling `$registry->enableAsset()`, what exactly am I doing?  Am I saying the asset can be used on the site (so a call to `$doc->addAsset($asset)` would actually add it to the document, or whatever the `$registry->attach($doc)` stuff actually does)?  Am I saying that the asset will be rendered on the site (meaning it is comparable to `$doc->addScript()`)?

2018-10-01 18:58 UTC, Fedik commented on libraries/src/WebAsset/WebAssetRegistry.php
> +	public function enableAsset($name)
Initially `$registry->assets` property holds all assets. All has `$state = STATE_INACTIVE`.
That means no one of it will be added to Document.

Call of `enableAsset()` doing `$state = STATE_ACTIVE`, so the files (js/css) from the Asset item will be added to the document, later, at call of attach().

Full example: 
You added a registry file, that describe 2 asset "jquery" and "bootstrap".
After parsing this file  `$registry->assets` will hold these 2 asset with `$state = STATE_INACTIVE`.
Call of `$registry->attach($document)` will ignore them.

Then you do `$registry->enableAsset('bootstrap')`, at this point the WebAssetRegistry will change state of "bootstrap" to `$state = STATE_ACTIVE`.
Call of `$registry->attach($document)` will add the files from Bootstrap asset to document.

2018-10-01 18:59 UTC, dgrammatiko commented
> If we move to a system where you have to modify manifest files or use plugins to re-register an asset's path that's adding a bit of complexity to what has previously been a rather simple system

You should be able to do `HTMLHelper::script` or `HTMLHelper::stylesheet` just before adding the assets to the document->_scripts or _stylesheets. That will keep the same old functionality intact. But is it wise to have multiple methods for adding assets into a page?

@Fedik you're quite right modules are best fit for declarative scripts not imperative (most of the Dom things in Joomla). Also modules make sense if you are going to do some tree shaking and that requires node and that's also a dead end...
So from all this part of the modules comment just keep, as you already did, the part that **every script tag** needs to have a defer attribute
Also big thumbs up for require.js but I guess this idea won't anywhere...

2018-10-01 19:01 UTC, Fedik commented
> Also big thumbs up for require.js but I guess this idea won't anywhere...

maybe in someday, in the galaxy far far far far away ... :smile:

2018-10-01 19:20 UTC, mbabker commented
The problem is not with require.js or any of that tooling.  The problem is you are in an environment where there is an end user facing feature for runtime resolution of assets that enables end users to create overrides.  You aren't working in a purely compiled environment, you aren't working in an environment where all the paths are going to be static.

If the JavaScript and browser tooling reach a point where the capabilities that Joomla has can be emulated in a way other than what JHtml does to resolve paths at runtime, that can be considered.  Until then, talking down on the project because it doesn't push for a compiled build environment that only "real" developers can use does nothing but make people feel alienated.

2018-10-01 19:48 UTC, dgrammatiko commented
> you aren't working in an environment where all the paths are going to be static

require.js can handle this in the same manner script tags are appended in the html.

> talking down on the project because it doesn't push for a compiled build environment

You got me wrong, all I said was that you should try to ease the path for modules (by forcing defer) not actually implement it right now (yes till dynamic imports are supported everywhere there's no point even trying to do it)

2018-10-01 20:22 UTC, Fedik commented
>  The problem is you are in an environment where there is an end user facing feature for runtime resolution of assets that enables end users to create overrides. 

After some tweaks WebAssetRegistry allow to generate a config for require.js, which can be used as script/module loader. 

but all this not in current PR

2018-10-02 08:30 UTC, Fedik commented
@mbabker Here another example about what is doing enable/disable and add/remove methods:
```php
// Empty asset registry
$wa = new WebAssetRegistry;

// Add some assets
$wa->addAsset(new WebAssetItem("🍻"));
$wa->addAsset(new WebAssetItem("🐘"));

// At this point we have 2 asset in registry, with STATE_INACTIVE
// So nothing will be added to Document
$wa->attachActiveAssetsToDocument($document); // Will do nothing, because all assets is inactive

// Enable asset
$wa->enableAsset("🐘");

// At this ponit we still have 2 assets, but only 1 is Active
$wa->attachActiveAssetsToDocument($document); // Will add files from "🐘" asset to Document

// Try to enable not-existing asset
$wa->enableAsset("🐛"); // Will throw Exception

```

And use of RegistryFile just doing `addAsset()` for you, all you need is just enable/disable existing.
Of course you still can do `$wa->addAsset(new WebAssetItem("🍪"))->enableAsset("🍪")`, if need.

2018-10-14 21:49 UTC, merged

2018-10-14 21:49 UTC, wilsonge commented
Let's take this as a first pass. I'm pretty sure there's some improvements to be made here - but I'm happy with this as the base concept

2018-10-15 08:35 UTC, Fedik commented
oh, that was fast :smile: 

for note, one issue left:

> @mbabker : If I enable an asset with dependencies I expect the dependencies to be enabled as well.

> This might be a case of trying to be too lazy. It's fine to defer parsing the JSON files until you actually start adding WebAssetItem entries to the internal store, but once you start populating WebAssetRegistry::$assets with objects it should always contain the full resource tree. It really shouldn't be a partial snapshot.

I think it is pretty important.
I will try to fix it, in one of next pull request.

2019-03-19 12:14 UTC, wilsonge commented
I've started working on docs for this feature https://docs.joomla.org/J4.x:Web_Assets Any help is always appreciated!