[4.0] Use non deprecated code in core extensions
joomla/joomla-cms pull request #22442
Opened 2018-10-01 11:57 UTC by laoneo

### Summary of Changes
Remove deprecated code usage in core extensions.

### Testing Instructions
- Enable debug in the joomla configuration
- Open the debug plugin
- Set "Log Deprecated API" to yes
- Save the plugin configuration

### Expected result
In the debug bar should the "Deprecated" tab be empty.

### Actual result
In the debug bar is the "Deprecated" tab not empty.

2018-10-01 15:09 UTC, SharkyKZ commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		$query->setLimit(0, $params->get('count', 5));
Switch argument order.

2018-10-01 19:52 UTC, wilsonge commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		if ($query instanceof LimitableInterface)
Is there a reason to add a level of complexity here with the interface check rather than using `setQuery` as we did before?

2018-10-01 19:53 UTC, wilsonge requested changes
Looks good to me other than the `setQuery` change

2018-10-01 20:12 UTC, mbabker commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		if ($query instanceof LimitableInterface)
Technically `$db->getQuery()` doesn't guarantee a return of a `QueryInterface` object that also implements `LimitableInterface`.  https://github.com/joomla-framework/database/issues/133 had no feedback so I just closed it out, but really it's just having `QueryInterface` extend `LimitableInterface` for 2.0 and 3.0 dropping `LimitableInterface`.

2018-10-01 20:21 UTC, mbabker commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		if ($query instanceof LimitableInterface)
Also, it would be pretty damn wrong to only make limitable queries if the query object implements the interface for the sake of avoiding deprecated code.  Yeah, we should avoid using deprecated code where practical in core, but if it's going to break features then that's a no-go.

2018-10-02 06:04 UTC, laoneo commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		if ($query instanceof LimitableInterface)
So are we going to change the query in the database package? Because I really don't want to revert to the deprecated code usage.

2018-10-02 12:03 UTC, mbabker commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		if ($query instanceof LimitableInterface)
You need to keep the deprecated code usage until the database package is updated.  Otherwise right now by your logic you can't limit the number of returned results from a query without this conditional check, and that's not an acceptable approach.

2018-10-02 12:10 UTC, laoneo commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		if ($query instanceof LimitableInterface)
That's exactly my question. Will the database package get an update?

2018-10-02 12:14 UTC, mbabker commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		if ($query instanceof LimitableInterface)
I had an issue open.  It got no response.  I closed it.  I commented above exactly what needs to happen.  If someone wants to tackle it, go for it, but I decided to not waste my time on things that aren't going to get feedback in any form.

2018-10-02 12:59 UTC, laoneo commented on administrator/modules/mod_logged/Helper/LoggedHelper.php
> +		if ($query instanceof LimitableInterface)
Here we go https://github.com/joomla-framework/database/pull/139

2018-10-03 19:42 UTC, laoneo commented
As the query implements now the `LimitableInterface` interface since https://github.com/joomla-framework/database/pull/139 got merged and composer is updated. This pr should be fine now.

2018-10-14 21:38 UTC, merged

2018-10-14 21:38 UTC, wilsonge commented
LGTM!