Drop checked_out capability in com_privacy
joomla/joomla-cms pull request #22748
Opened 2018-10-20 15:53 UTC by mbabker

Pull Request for Issue #22722

### Summary of Changes

Privacy requests ended up not having a notion of editing that works with the checkout system.  So, drop the checkout related data.

### Testing Instructions

Apply patch, ensure columns removed, ensure things work.

2018-10-21 06:00 UTC, alikon requested changes

2018-10-21 06:00 UTC, alikon commented on installation/sql/mysql/joomla.sql
>    KEY `idx_checkout` (`checked_out`)
remove index if you removed the field from the table
```suggestion

```

2018-10-21 14:58 UTC, mbabker commented on installation/sql/mysql/joomla.sql
>    KEY `idx_checkout` (`checked_out`)
Indexes removed

2018-10-22 05:22 UTC, alikon commented
Tested successfully even if not reported from issues

2018-10-22 05:30 UTC, alikon commented
Tested successfully even if not reported from issues

2018-10-22 07:53 UTC, alikon commented
tested successfully

2018-10-23 14:53 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 7226a2bce8bd08947453be145126e759580147ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22748">issues.joomla.org/tracker/joomla-cms/22748</a>.</sub>

2018-10-23 14:54 UTC, infograf768 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22748">issues.joomla.org/tracker/joomla-cms/22748</a>.</sub>

2018-10-23 19:44 UTC, merged