Improved extension update error message.
joomla/joomla-cms pull request #22763
Opened 2018-10-22 17:22 UTC by BrainforgeUK

Pull Request for Issue ##22762.

### Summary of Changes

Improved error messages when the manifest retrieves and invalid manifest file.

### Testing Instructions

Get update site to include an invalid download URL - or get a valid one to fail.
For example.
<downloadurl type="full" format="">http://thisisinvalid/donotuse.zip</downloadurl>

### Expected result

Get sensible message pointing to problem.

### Actual result

Currently get message
Error updating COM_INSTALLER_TYPE_TYPE_.

### Documentation Changes Required

None

2018-10-22 17:36 UTC, Quy commented on administrator/components/com_installer/models/update.php
> +		if (!isset($package['type']))
Add blank line above.

2018-10-22 17:49 UTC, mbabker requested changes

2018-10-22 17:49 UTC, mbabker commented on administrator/components/com_installer/models/update.php
> +		if (!isset($package['type']))
If you're really going to make this check you need to check for several possibilities:

- Whether `$package === false` (because it is not being specified that the method should always return an array, gotta love mixed return types)
- Whether `$package['type']` is set
- Whether `$package['type'] === false`

2018-10-22 18:40 UTC, brianteeman reviewed
please update the string

2018-10-22 18:40 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_MSG_UPDATE_INVALID_PKG="Invalid package : '%s'"
```suggestion
COM_INSTALLER_MSG_UPDATE_INVALID_PKG="Invalid package: %s"
```

2018-10-22 20:45 UTC, brianteeman requested changes
My requested change also removed the single quotes around the %s

2018-10-23 06:22 UTC, brianteeman approved these changes
approve language strings

2019-04-24 11:24 UTC, franz-wohlkoenig commented
I have tested this item :red_circle: unsuccessfully on 27a4c54c8bcdc80c9574ec3ac9c1291d83a49884<br /><br />Details coming ...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22763">issues.joomla.org/tracker/joomla-cms/22763</a>.</sub>

2019-05-15 03:33 UTC, closed without merging

2019-05-15 03:33 UTC, Quy commented
Replaced by #24905 for J4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22763">issues.joomla.org/tracker/joomla-cms/22763</a>.</sub>