[4.0] Fix JS error in searchtools
joomla/joomla-cms pull request #22810
Opened 2018-10-24 07:24 UTC by C-Lodder

Pull Request for Issue #22784

### Summary of Changes

Only perform actions on the `#sort` element if it exists

### Testing Instructions

Refer to issue

### Expected result

No JS error

2018-10-24 12:13 UTC, dgrammatiko requested changes

2018-10-24 12:13 UTC, dgrammatiko commented on build/media_src/system/js/searchtools.es6.js
> +      if (sort.hasAttribute('data-caption')) {
`if (sort && sort.hasAttribute('data-caption')) {`
It's a one liner one if statement same result

2018-10-24 12:14 UTC, dgrammatiko requested changes

2018-10-24 12:14 UTC, dgrammatiko commented on build/media_src/system/js/searchtools.es6.js
> +      if (sort.hasAttribute('data-sort')) {
Same here:
` if (sort && sort.hasAttribute('data-sort')) {`

2018-10-24 12:27 UTC, C-Lodder commented on build/media_src/system/js/searchtools.es6.js
> +      if (sort.hasAttribute('data-sort')) {
Makes no odds really, wrapping it all in 1 conditional statement or using it twice in each statement.

2018-10-26 06:53 UTC, merged

2018-10-26 06:53 UTC, laoneo commented
Thanks