[3.9] Make sure the reset token is invalidated when the email is changed and an token exists
joomla/joomla-cms pull request #22843
Opened 2018-10-28 11:48 UTC by zero-24

### Summary of Changes

With this change we make sure the reset token is invalidated (set to another value) when the account mail is changed.

### Testing Instructions

- Create an new user.
- request an PW reset
- check that the mail got out
- login (without resetting the PW)
- change the email (Frontend or Backend)
- try to reset the PW with the reset token send to the old mail

### Expected result

With this patch this is not possible any more as the token has been changed at the time the mail has been changed

### Actual result

Without this patch the old token still works.

### Documentation Changes Required

none.

### Other notes

This issue has been reported to the JSST by Ramesh From J2store but the JSST decided to fix this in the public tracker. Thanks!

cc @joomla/security @SniperSister @mbabker

2018-10-28 15:36 UTC, Quy commented on administrator/components/com_users/models/user.php
> +		// Make sure the activation / reset token is invalidated when the account mail is changed and an token exists.
```suggestion
		// Make sure the activation / reset token is invalidated when the account mail is changed and a token exists.
```

2018-10-28 15:36 UTC, Quy commented on components/com_users/models/profile.php
> +		// Make sure the activation / reset token is invalidated when the account mail is changed and an token exists.
```suggestion
		// Make sure the activation / reset token is invalidated when the account mail is changed and a token exists.
```

2018-10-28 15:53 UTC, mbabker commented
You might as well just blank out the token.  Unless you're sending the new token to the user it's unusable anyway.

2018-10-28 16:00 UTC, zero-24 commented
> You might as well just blank out the token. Unless you're sending the new token to the user it's unusable anyway.

Well this token / activation field also applys to the "Activation" 
![image](https://user-images.githubusercontent.com/2596554/47618389-d5d08500-dad2-11e8-9e16-647e1e6a60f5.png)

When we have an empty field this is marked as "Activated". I'm happy to apply any code just wanted to make sure the UI thing is not changed at all.

2018-10-28 16:06 UTC, mbabker commented
If the UI is solely relying on "token field is empty" IMO that's an issue too.

The problem you're running into now is you're changing the activation token and not giving the new token to the user.  So if they try to activate the account with the token they already have, they won't be able to actually activate the account.

2018-10-28 16:12 UTC, zero-24 commented
> The problem you're running into now is you're changing the activation token and not giving the new token to the user. So if they try to activate the account with the token they already have, they won't be able to actually activate the account.

Wich is exactly what is expected ;) But I'm happy to empty the token too.

2018-10-28 16:15 UTC, mbabker commented
I get the intent.  But the user has no idea that changing their email is invalidating that token and they need a new one to finish the activation step.  That's the issue I'm raising, without providing the new token it is now impossible for a user to activate their own account in this scenario.

2019-03-25 18:58 UTC, zero-24 commented
@mbabker With the latest commit (https://github.com/joomla/joomla-cms/pull/22843/commits/e446cd385ca779ae582ba4979fdffe91ff884b38) I have implemented an user notification feature is this something you where looking for? Basically restarting the verification process including sending mails etc.

2019-03-25 19:03 UTC, mbabker requested changes

2019-03-25 19:03 UTC, mbabker commented on administrator/components/com_users/models/user.php
> +		if ($user->email != $data['email'] && $userId != 0 && !empty($user->activation))
You don't have a `$userId` var defined here, are you intending to use the `$pk`?  You could also use `$user->id`.

2019-03-25 19:03 UTC, mbabker commented on administrator/components/com_users/models/user.php
> +			$data = JFactory::getUser($userId)->getProperties();
You can't just use the `$user` you've already retrieved?

2019-03-25 19:03 UTC, mbabker commented on components/com_users/models/profile.php
> +			$data = JFactory::getUser($userId)->getProperties();
Again, you could use the `$user` instance you've already got a few lines above.

2019-03-25 19:10 UTC, zero-24 commented
thanks @mbabker your comments have been adressed by the last commit. So you generally agree with the concept and I can ask Brian to take a look over my new strings?

2019-03-25 19:11 UTC, zero-24 commented on administrator/components/com_users/models/user.php
> +		if ($user->email != $data['email'] && $userId != 0 && !empty($user->activation))
fixed thanks.

2019-03-25 19:14 UTC, mbabker commented
Looks fine to me.

2019-03-25 19:15 UTC, zero-24 commented
thanks 👍 

@brianteeman can you please give me feedback about the new strings I added here to be send as mail to the users when the mail has been changed:
```
COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be verified before you can use it.\nBefore the latest confirmation the account mail has been changed so we need you to confirm the new mail please select the following link or copy-paste it in your browser:\n %s \n\nAfter verification an administrator will be notified to activate your account. You'll receive a confirmation when it's done.\nOnce that account has been activated you may login to %s using the following username and the password you entered during registration:\n\nUsername: %s"
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest confirmation the account mail has been changed so we need you to confirm the new mail please select the following link or copy-paste it in your browser:\n%s \n\nAfter activation you may login to %s using the following username and the password you entered during registration:\n\nUsername: %s"
```

2019-03-25 19:19 UTC, brianteeman commented
If I understand this correctly every time you say "mail" you should say "email address"

2019-03-25 19:30 UTC, zero-24 commented
Thanks just pushed the fix 👍

2019-03-25 19:34 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be verified before you can use it.\nBefore the lates
```suggestion
COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be verified before you can use it.\nBefore the latest confirmation the account email address has been changed so we need you to confirm the new email address. Please select the following link or copy-paste it in your browser:\n %s \n\nAfter verification an administrator will be notified to activate your account. You'll receive a confirmation when it's done.\nOnce that account has been activated you may login to %s using the following username and the password you entered during registration:\n\nUsername: %s"
```

2019-03-25 19:34 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest con
```suggestion
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest confirmation the account email address has been changed so we need you to confirm the new email address. Please select the following link or copy-paste it in your browser:\n%s \n\nAfter activation you may login to %s using the following username and the password you entered during registration:\n\nUsername: %s"
```

2019-03-25 19:35 UTC, brianteeman commented on language/en-GB/en-GB.com_users.ini
> +COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest con
```suggestion
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest confirmation the account email address has been changed so we need you to confirm the new email address Please select the following link or copy-paste it in your browser:\n%s \n\nAfter activation you may login to %s using the following username and the password you entered during registration:\n\nUsername: %s"
```

2019-03-25 19:35 UTC, brianteeman commented on language/en-GB/en-GB.com_users.ini
> +COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be verified before you can use it.\nBefore the lates
```suggestion
COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be verified before you can use it.\nBefore the latest confirmation the account email address has been changed so we need you to confirm the new email address. Please select the following link or copy-paste it in your browser:\n %s \n\nAfter verification an administrator will be notified to activate your account. You'll receive a confirmation when it's done.\nOnce that account has been activated you may login to %s using the following username and the password you entered during registration:\n\nUsername: %s"
```

2019-03-25 19:39 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest con
```suggestion
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest confirmation the account email address has been changed so we need you to confirm the new email address. Please select the following link or copy-paste it in your browser:\n%s \n\nAfter activation you may login to %s using the following username and the password you entered during registration:\n\nUsername: %s"
```

2019-03-26 09:51 UTC, zero-24 commented
Thanks @brianteeman This is ready now for testing 👍

2019-03-27 00:45 UTC, Quy commented on administrator/components/com_users/models/user.php
> +
Remove tabs

2019-03-27 00:45 UTC, Quy commented on components/com_users/models/profile.php
> +
Remove tabs

2019-03-27 00:45 UTC, Quy commented on components/com_users/models/profile.php
> +
Remove tabs

2019-03-27 00:48 UTC, Quy commented on components/com_users/models/profile.php
> +			$emailBodyLanguageString = 'COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_CHANGED_MAIL_BODY';
Change to `COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY`?

2019-03-27 00:49 UTC, Quy commented on components/com_users/models/profile.php
> +			$emailBodyLanguageString = 'COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_CHANGED_MAIL_BODY';
```suggestion
			$emailBodyLanguageString = 'COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY';
```

2019-03-27 00:49 UTC, Quy commented on components/com_users/models/profile.php
> +				$emailBodyLanguageString = 'COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_CHANGED_MAIL_BODY';
```suggestion
				$emailBodyLanguageString = 'COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY';
```

2019-03-27 11:57 UTC, zero-24 commented
@Quy can you please double check but the strings should be correct now. Thanks for your review.

2019-03-27 14:35 UTC, Quy commented on administrator/components/com_users/models/user.php
> +
Remove tabs. (I would submit a PR via Github, but it removes the line instead of just the tabs.)

2019-03-27 20:04 UTC, zero-24 commented on administrator/components/com_users/models/user.php
> +
Fixed thanks 👍

2019-03-28 03:24 UTC, Quy commented on language/en-GB/en-GB.com_users.ini
> +COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest con
```suggestion
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest confirmation the account email address has been changed so we need you to confirm the new email address. Please select the following link or copy-paste it in your browser:\n%s \n\nAfter activation you may login to %s using the following username and the password you entered during registration:\n\nUsername: %s"
```

2019-03-28 03:24 UTC, Quy commented on components/com_users/models/profile.php
> +				// Wait we have useractivation use the correct string than
```suggestion
				// Wait we have useractivation use the correct string then
```

2019-03-28 03:24 UTC, Quy commented on administrator/components/com_users/models/user.php
> +				// Wait we have useractivation use the correct string than
```suggestion
				// Wait we have useractivation use the correct string then
```

2019-04-17 11:16 UTC, ReLater commented
Because I had some problems to understand the new procedure yesterday ("in a terribly tired mood"): Are the testing instructions still correct after additional commits? I had some problems to test this pr. When I tried to change the email I got a message like "Change your password, too" but when I tried that, I couldn't save the profile and saw the same message.
![17-04-_2019_13-00-50](https://user-images.githubusercontent.com/20780646/56283132-1ff50380-6111-11e9-9bc1-87e46757644d.jpg)

It looks like, that after any attempt to save the profile a new activation email is sent but the page doesn't inform the user accordingly. I've found these emails this morning.

I tested again today. > I get the activation email and cllick the link after steps above and get:
![17-04-_2019_13-11-32](https://user-images.githubusercontent.com/20780646/56283596-89c1dd00-6112-11e9-91f5-d7e0230efee9.jpg)

I don't know if relevant: My settings:

![17-04-_2019_12-53-40](https://user-images.githubusercontent.com/20780646/56283641-a3fbbb00-6112-11e9-80f5-738105f9abf6.jpg)

2019-04-26 10:25 UTC, alikon requested changes

2019-04-26 10:25 UTC, alikon commented on administrator/components/com_users/models/user.php
> +			$linkMode = $app->get('force_ssl', 0) == 2 ? 1 : -1;
should'nt we need to use something like `Route::TLS_FORCE` , `Route::TLS_IGNORE`; instead of  1, -1 to increase readability

2019-04-26 10:35 UTC, HLeithner commented on administrator/components/com_users/models/user.php
> +			$linkMode = $app->get('force_ssl', 0) == 2 ? 1 : -1;
This constants don't exist yet, it will be introduced in PR https://github.com/joomla/joomla-cms/pull/24089

2019-04-26 10:37 UTC, alikon commented on administrator/components/com_users/models/user.php
> +			$linkMode = $app->get('force_ssl', 0) == 2 ? 1 : -1;
ouch, i was testing #24089 so i've made a silly 1+1 :smiley:

2019-04-27 08:16 UTC, gwsdesk commented
This is not working for me. Patched J3.9.5 with Michael's baby. Steps taken for testing as described above. PW request has been send and is received by new user. Logging in on frontened, changing email in the profile and trying to save gives 
> Warning
> Profile could not be saved: Could not bind profile data: Passwords do not match. Please re-enter password.
If in the user manager keep using the old email and try to safe (after the patch) gives

> Error
> Save failed with the following error: You can't reuse your current password, please enter a new password.

Trying to do the same in the user manager in the backend gives

> Error
> Save failed with the following error: Passwords do not match. Please re-enter password.

2019-04-27 08:38 UTC, gwsdesk commented
I have tested this item :red_circle: unsuccessfully on a876bd88a14fd68383280433490f45d12b004e35<br /><br />see my comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22843">issues.joomla.org/tracker/joomla-cms/22843</a>.</sub>

2019-05-11 19:28 UTC, zero-24 commented
thanks @ReLater and @gwsdesk the issue should be gone now by the latest commit.

2019-05-21 01:39 UTC, Quy commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_CHANGED_MAIL_BODY="Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nBefore the latest con
Sort in alpha order.

2019-05-24 12:12 UTC, Milglius commented
Why drone pr is failing?

2019-05-24 17:03 UTC, zero-24 commented
It seams the JavaScript tests are having problems. Drone has been rebooted: https://ci.joomla.org/joomla/joomla-cms/18687

2019-06-12 07:33 UTC, AndySDH commented
Milestone for this should now be changed to 3.9.9

2019-06-16 12:51 UTC, zero-24 commented
@ReLater @gwsdesk can I ask you to take a look here again as the reported issues should be fixed now. Thanks

2019-06-23 02:29 UTC, Quy commented on administrator/components/com_users/models/user.php
> +			$linkMode = $app->get('force_ssl', 0) == 2 ? 1 : -1;
Use constants now?

2019-06-23 16:12 UTC, zero-24 commented on administrator/components/com_users/models/user.php
> +			$linkMode = $app->get('force_ssl', 0) == 2 ? 1 : -1;
Should be done here: https://github.com/joomla/joomla-cms/pull/22843/commits/e75e846ba9e765395554d762b839a837edbb2c5f

Can this be tested now? ;)

2019-06-28 12:34 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on 60c4553217035372817d6dac84eaf66b430cced7<br /><br />I've tested this issue successfully with 3.9.8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22843">issues.joomla.org/tracker/joomla-cms/22843</a>.</sub>

2019-07-02 09:19 UTC, bembelimen commented on components/com_users/models/profile.php
> +		if ($user->email != $data['email'] && $userId != 0 && !empty($user->activation))
In frontend it's not needed to send an email (and makes imho not much sense). There are two scenarios:
- user is not activated yet (=> also blocked) => he/she/it can't change the email at all
- user is already activated but has a hash (due PW reset) => sp it makes no sense to send a activation reminder + it makes no sense to reset the hash, because if he/she/it can change the email, he/she/it knows the PW.

2019-07-02 09:27 UTC, bembelimen commented on administrator/components/com_users/models/user.php
> +			if (JComponentHelper::getParams('com_users')->get('useractivation') === 1)
What about if user has hash but the admin changes this parameter to "0" (=> no activation needed)?

2019-07-02 09:32 UTC, bembelimen commented on administrator/components/com_users/models/user.php
> +		if ($user->email != $data['email'] && $pk != 0 && !empty($user->activation))
We shouldn't send activation emails if the user is already activated (!= blocked)

2019-07-03 19:09 UTC, zero-24 commented on components/com_users/models/profile.php
> +		if ($user->email != $data['email'] && $userId != 0 && !empty($user->activation))
agree removed the checks there.

2019-07-03 19:09 UTC, zero-24 commented on administrator/components/com_users/models/user.php
> +			if (JComponentHelper::getParams('com_users')->get('useractivation') === 1)
now we use the same string as self activation. As I would not like to flat out remove the activation token.

2019-07-03 19:10 UTC, zero-24 commented on administrator/components/com_users/models/user.php
> +		if ($user->email != $data['email'] && $pk != 0 && !empty($user->activation))
Just to be sure. You suggest an if like this:

````
if ($user->email != $data['email'] && $pk != 0 && !empty($user->activation) && $user->block ===1)
```

right?

2019-07-20 14:23 UTC, zero-24 commented on administrator/components/com_users/models/user.php
> +		if ($user->email != $data['email'] && $pk != 0 && !empty($user->activation))
@bembelimen can you take a look in my question?

2019-08-05 18:08 UTC, zero-24 commented
Any update here @bembelimen ?

2019-10-28 21:21 UTC, zero-24 commented
Any update here @bembelimen ?

2020-01-13 13:01 UTC, zero-24 commented
Any update here @bembelimen ?

2020-02-12 00:46 UTC, bembelimen commented on administrator/components/com_users/models/user.php
> +		if ($user->email != $data['email'] && $pk != 0 && !empty($user->activation))
TBH, I have no idea what I ment.
Probably a check for ```!$user->block```

2020-02-17 10:25 UTC, wilsonge commented on components/com_users/models/profile.php
> +use Joomla\CMS\Router\Route;
Guess this can be removed?

2020-02-17 10:27 UTC, wilsonge commented
@zero-24  let's add the check for the user blocked status ben proposed and then get some testing. This is well overdue going in

2020-02-18 19:01 UTC, zero-24 commented
Done thanks @wilsonge @bembelimen ready for testing again :)

2020-02-18 19:03 UTC, wilsonge commented
@joomla/security  can you please do some testing here

2020-03-29 15:47 UTC, Quy commented on administrator/components/com_users/models/user.php
> +				 * Or we have a rare case that the parameter has been set to 0 (None) after the user registed but not activated the account
```suggestion
				 * Or we have a rare case that the parameter has been set to 0 (None) after the user registered but not activated the account
```

2020-03-29 23:38 UTC, ReLater commented
One issue found. **Perhaps it's just a Route class problem and not related to this pr!!**:
- Super User creates account (Registered). back-end
- Registered User gets welcome email and logs in. front-end
- Registered User requests password reset and got email.
- Super User changes email address. back-end

- Registered User gets the following email text to the new email address with incomplete URL (domain missing).

![30-03-_2020_01-23-20](https://user-images.githubusercontent.com/20780646/77863789-234fa500-7225-11ea-8fb3-36c9018a44cf.jpg)

What's relevant here is that I have not activated SSL in Joomla but on host side.

user.php line 206 and 207:
```
$linkMode = (int) $app->get('force_ssl', 0) == 2 ? Route::TLS_FORCE : Route::TLS_IGNORE;

$data['activate'] = Route::link('site', 'index.php?option=com_users&task=registration.activate&token=' . $data['activation'], false, $linkMode);
```
When I use hard coded:
```
$linkMode = Route::TLS_FORCE;
```
The `$data['activate']` URL is correct (with domain part).

2020-03-29 23:52 UTC, ReLater commented
> The $data['activate'] URL is correct (with domain part).

but it leads to a 403 page

![30-03-_2020_01-51-40](https://user-images.githubusercontent.com/20780646/77864498-1c2a9600-7229-11ea-9c07-37fed6672c5f.jpg)

2020-03-30 11:52 UTC, HLeithner commented on administrator/components/com_users/models/user.php
> +			$data['activate'] = Route::link('site', 'index.php?option=com_users&task=registration.activate&token=' . $data['activation'], false, $linkMode);
```suggestion
			$data['activate'] = Route::link('site', 'index.php?option=com_users&task=registration.activate&token=' . $data['activation'], false, $linkMode, true);
```
This addresses the problem found by @ReLater

2020-03-30 12:11 UTC, zero-24 commented
Thanks @HLeithner

2020-05-10 22:24 UTC, zero-24 commented
@ReLater can you give this one a second test round after the patch for the issue?

2020-10-17 09:43 UTC, zero-24 commented
Hmm I'm not sure whats up with AppVeyor but this PR is up-to-date with staging now.

2020-10-27 19:33 UTC, Quy commented
Please fix phpcs.

2021-04-07 17:19 UTC, closed without merging