Privacy dashboard: direct access to the privacy consent plugin
joomla/joomla-cms pull request #22888
Opened 2018-10-31 11:15 UTC by infograf768

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/22869

### Summary of Changes
Adds direct link to the privacy consent plugin when there is no Privacy policy article defined.

### Testing Instructions
make sure no article is defined in the Privacy Consent System plugin parameters

### Before patch
No link to the plugin (and no idea what to do when getting The "Not available" button...)

### After patch
<img width="418" alt="screen shot 2018-10-31 at 12 13 02" src="https://user-images.githubusercontent.com/869724/47784612-66db7200-dd06-11e8-8e4c-757c49643d89.png">

The only other check that "could" be used is one to the Global Configuration for `mailonline`, but this is rather obvious.
Can be added though if judged necessary in another PR.

2018-10-31 11:54 UTC, brianteeman commented
Not everything should have a link. The similar module for mutilingual status does not.

2018-10-31 18:00 UTC, PhilETaylor commented
> Not everything should have a link.

There is no reason why all 4 options cannot have a link to aid the user to fix the issues.

> The similar module for mutilingual status does not.

Then maybe that too should be improved. Not all Joomla users are as close to the project as you, Some need help and guidance along the way. Not everything should be a million clicks away from something else.

2018-10-31 18:59 UTC, alikon commented
not so bad imo to guide more  newbie's....
already collected similar question's

2018-10-31 19:29 UTC, PhilETaylor commented
Why was this closed?
This issue refers to FOUR items and the PR is for a single item!




> On 31 Oct 2018, at 12:27, Brian Teeman <notifications@github.com> wrote:
> 
> Closed #22888.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-10-31 19:44 UTC, Bakual commented
Reopening as I also don't see a reason to close this. I guess it was by accident.

2018-10-31 20:17 UTC, brianteeman commented
Sorry it was closed by accident

2018-11-01 05:14 UTC, infograf768 commented
@PhilETaylor 
I reopened https://github.com/joomla/joomla-cms/issues/22869 as we need to discuss there what we do for the other checks.
I propose we treat this one separately, get it tested (please do) and merged in the mean while.

2018-11-02 09:09 UTC, infograf768 commented
https://github.com/joomla/joomla-cms/pull/22909
is a totally independant PR to correct the `Published Request Form Menu Item` url in multilang

2019-01-08 20:35 UTC, alikon requested changes

2019-01-08 20:35 UTC, alikon commented on administrator/components/com_privacy/helpers/privacy.php
> +		$db    = JFactory::getDbo();
can you please use namespaced version here and where needed

2019-01-09 07:40 UTC, infograf768 commented on administrator/components/com_privacy/helpers/privacy.php
> +		$db    = JFactory::getDbo();
@alikon 
done. Please test.

2019-01-09 18:42 UTC, alikon commented
I have tested this item :white_check_mark: successfully on d618c8c6fcd999fcbf175e4cfac470ffd58afbbf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22888">issues.joomla.org/tracker/joomla-cms/22888</a>.</sub>

2019-01-09 18:43 UTC, alikon commented on administrator/components/com_privacy/helpers/privacy.php
> +		$db    = JFactory::getDbo();
thx @infograf768

2019-01-10 11:45 UTC, chmst commented
I have tested this item :white_check_mark: successfully on d618c8c6fcd999fcbf175e4cfac470ffd58afbbf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22888">issues.joomla.org/tracker/joomla-cms/22888</a>.</sub>

2019-01-10 13:44 UTC, infograf768 commented
rtc
tks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22888">issues.joomla.org/tracker/joomla-cms/22888</a>.</sub>

2019-01-10 16:32 UTC, infograf768 commented
@mbabker 
I leave this as RTC as the last change was just a missing `s` in the lang string.
(Tks Mig for finding this typo)

2019-01-11 12:42 UTC, merged