[3.9] Move confirm consent to use the bs modal vs mootools
joomla/joomla-cms pull request #22926
Opened 2018-11-02 21:41 UTC by zero-24

Partial Pull Request for Issue #22908

### Summary of Changes

This replaces the Mootools modal vs a bootstrap modal

### Testing Instructions

- Install 3.9.0
- enable the `Content - ConfirmConsent` Plugin
- configure this plugin to point to a article
- open a contact page on the website
- make sure the title is clickable and opens an modal
- apply this patch
- make sure it is still opening a modal this time it should be a bs modal

### Expected result

bs modal

### Actual result

mootools modal

### Documentation Changes Required

none.

### Additional Information

When this here gets approved & tested I can apply similar code to the other places where we use the old mootools modal:
- TOS Field: https://github.com/joomla/joomla-cms/blob/90078118c3d262d4e21dcd1dbe5ad290297ee5ee/plugins/user/profile/field/tos.php#L83
- Privacy Field: https://github.com/joomla/joomla-cms/blob/40dcca879db47fd28dadf25ee09df3b37f0c4e85/plugins/system/privacyconsent/field/privacy.php#L101
- Terms Field: https://github.com/joomla/joomla-cms/blob/40dcca879db47fd28dadf25ee09df3b37f0c4e85/plugins/user/terms/field/terms.php#L101

cc @brianteeman as he is the original author of the modal things in this plugin touched here.

2018-11-02 22:07 UTC, dgrammatiko commented
@zero-24 please use a layout, do not do html markup inside the plugin!

2018-11-02 22:13 UTC, zero-24 commented
Can you please let me know what you want to change? As beyond the (already hardcoded) hight and width I did not add any extensive new HTML part in that plugin right? Or is there something special you want me to change?

2018-11-02 22:19 UTC, dgrammatiko commented
There should be a tmpl folder with a layout (default.php or whatever) so people **could** actually do whatever they want in the front end, in other words, separate concerns. Check the https://github.com/joomla/joomla-cms/tree/staging/plugins/system/stats which was done correctly. This thing right now is hardcoded you cannot override anything unless you rewrite the whole plugin...

2018-11-02 22:20 UTC, brianteeman commented on plugins/content/confirmconsent/confirmconsent.php
> +		// When we have a article lets add the modal and make the title clickable
```suggestion
		// When we have a article let's add the modal and make the title clickable
```

2018-11-02 22:21 UTC, brianteeman commented on plugins/content/confirmconsent/confirmconsent.php
> +		// When we have a article lets add the modal and make the title clickable
typo

2018-11-03 10:58 UTC, Bakual commented
While it is true that using a layout is better, this PR is valid by itself. Moving the thing to a layout can be done easily in a separate PR as well and is actually preferred. Since it makes the PRs more atomic and easier to test and review.

2018-11-03 12:48 UTC, SharkyKZ requested changes

2018-11-03 12:48 UTC, SharkyKZ commented on plugins/content/confirmconsent/confirmconsent.php
> +			echo HTMLHelper::_('bootstrap.renderModal', 'modal-' . $modalName, $modalParams);
You can't output content here.

2018-11-03 15:32 UTC, dgrammatiko commented
> While it is true that using a layout is better

I'll say that it's mandatory, not better. You're not in Joomla 1.5 designers and site builders need to have the ability to override the output without rewriting the plugin! My 2c anyways

2018-11-03 16:25 UTC, mbabker commented
It should be a separate pull request for exactly the reasons @Bakual already stated.  Nobody is saying not to move the code to layouts but when you start adding all sorts of extras onto pull requests they end up being too complex to properly test and review and people either ignore them or they end up getting merged while being completely broken.

2018-11-03 17:16 UTC, ReLater commented
I have tested this item :white_check_mark: successfully on c7ac385d9a0f48ca4afb1f0ca5ce34d176d5e8f8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22926">issues.joomla.org/tracker/joomla-cms/22926</a>.</sub>

2018-11-13 20:31 UTC, drmenzelit commented
I have tested this item :white_check_mark: successfully on c7ac385d9a0f48ca4afb1f0ca5ce34d176d5e8f8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22926">issues.joomla.org/tracker/joomla-cms/22926</a>.</sub>

2018-11-13 20:34 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22926">issues.joomla.org/tracker/joomla-cms/22926</a>.</sub>

2018-11-13 20:54 UTC, SharkyKZ commented on plugins/content/confirmconsent/confirmconsent.php
> +			echo HTMLHelper::_('bootstrap.renderModal', 'modal-' . $modalName, $modalParams);
@zero-24 reminder, this needs to be fixed before merging. Can't output content in `onContentPrepareForm()`.

2018-11-13 21:04 UTC, merged