[libraries][installer] - ModuleAdapter
joomla/joomla-cms pull request #22984
Opened 2018-11-09 18:30 UTC by alikon

Pull Request for a partial fix to  Issue #22949 .

### Summary of Changes
cast to int for postgresql

### Testing Instructions
see  #22949

2018-11-09 19:42 UTC, twister65 commented
It fixes plugin update issue.
Very strange, the changes are in ModuleAdapter.
The module update issue is still there.

2018-11-09 20:14 UTC, twister65 commented
Please, replace `$db->quote` by `$db->quoteName`
https://github.com/joomla/joomla-cms/blob/1ea6ca65586baf0608027d87cde9c23a67495ed2/libraries/src/Installer/Adapter/ModuleAdapter.php#L705
`->where($db->quoteName('client_id') . ' = ' . (int) $this->extension->client_id);`

2018-11-09 20:21 UTC, Quy commented on libraries/src/Installer/Adapter/ModuleAdapter.php
> +			->where($db->quote('client_id') . ' = ' . (int) $this->extension->client_id);
```suggestion
			->where($db->quoteName('client_id') . ' = ' . (int) $this->extension->client_id);
```

2018-11-09 21:12 UTC, twister65 requested changes
I think, this line :
joomla-cms/libraries/src/Installer/Adapter/ModuleAdapter.php

Line 701 in 1ea6ca6

 		$this->extension->delete($this->extension->extension_id); 

should be placed after the query (line 717), when we have finished using it.
It is better to delete the object, when we no longer need it.

2018-11-09 21:42 UTC, mbabker commented
@twister65 That should really be a separate pull request instead of lumped in with another unrelated change.

2018-11-10 03:32 UTC, twister65 commented
See (test) PR #22993 please.

2018-12-03 15:57 UTC, csthomas commented
I have tested this item :white_check_mark: successfully on 3617699a41effc0448f75335ceb34fe96925cb2f<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22984">issues.joomla.org/tracker/joomla-cms/22984</a>.</sub>

2018-12-03 16:34 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 3617699a41effc0448f75335ceb34fe96925cb2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22984">issues.joomla.org/tracker/joomla-cms/22984</a>.</sub>

2018-12-03 16:35 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22984">issues.joomla.org/tracker/joomla-cms/22984</a>.</sub>

2018-12-05 00:34 UTC, merged