[4.0] RFC Quickicons Joomla and Extensions updates
joomla/joomla-cms pull request #23095
Opened 2018-11-16 10:52 UTC by infograf768

Replaces and complete https://github.com/joomla/joomla-cms/pull/23061 (for what concerns Joomla Update).

Implement NOTE in https://github.com/joomla/joomla-cms/pull/23061#issuecomment-438581619

### Summary of Changes
1. Adding Joomla Version
2. Change icon color to `warning` when an update is available as `danger` is used in case of error.
3. Place the `Update Now` and `View Updates` buttons to the bottom right of the Message, centering the rest of the message.
4. Adapt Atum CSS concerned to RTL, including the `joomla-alert`
5. Correct unnecessary `,` and `:` in the language strings
5. Correct `Text::script` to `false` by default to let single quotes in language strings to display unescaped instead of `\'`

### Testing Instructions
_To test on 4.0-dev branch_

**Concerning joomlaupdate:**
Modify version.php line 63 to const EXTRA_VERSION = 'alpha4-dev';
Go to database and Fix database.
Then in JoomlaUpdate Options choose Custom URL and add this link (Thanks Tobias) :
https://update.joomla.org/core/nightlies/next_major_list.xml
Save Options.
Display Control Panel.

**Concerning extensions update:**
Install an older language pack in order to get a warning for an update.
[fr-FR_joomla_lang_full_3.9.0v1.zip](https://github.com/joomla/joomla-cms/files/2570924/fr-FR_joomla_lang_full_3.9.0v1.zip)

in both cases, test also RTL by installing and switching to Persian language.

Test before patch, then run npm ci

### Expected result
<img width="500" alt="screen shot 2018-11-16 at 11 22 24" src="https://user-images.githubusercontent.com/869724/48616602-61338c80-e994-11e8-96f9-185e30713108.png">
<img width="401" alt="screen shot 2018-11-16 at 09 31 19" src="https://user-images.githubusercontent.com/869724/48616603-61338c80-e994-11e8-9127-da4ac265e7b9.png">
<img width="476" alt="screen shot 2018-11-16 at 09 30 00" src="https://user-images.githubusercontent.com/869724/48616604-61cc2300-e994-11e8-9b7e-57b8426de777.png">
<img width="442" alt="screen shot 2018-11-16 at 11 45 28" src="https://user-images.githubusercontent.com/869724/48616889-30a02280-e995-11e8-955f-606a54572336.png">

@tuum @wilsonge

2018-11-16 10:55 UTC, brianteeman commented on administrator/templates/atum/scss/template-rtl.scss
> +  text-align: left !important;
surely there is a way to do this without using !important

2018-11-16 11:01 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_quickicon_joomlaupdate.ini
> +PLG_QUICKICON_JOOMLAUPDATE_UPDATEFOUND_MESSAGE="Joomla %s is available"
This is now a sentence so should end with a full stop.

```suggestion
PLG_QUICKICON_JOOMLAUPDATE_UPDATEFOUND_MESSAGE="Joomla %s is available."
```

2018-11-16 11:01 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_quickicon_extensionupdate.ini
> +PLG_QUICKICON_EXTENSIONUPDATE_UPDATEFOUND_MESSAGE="%s Extension Update(s) are available"
This is now a sentence so should end with a full stop.

```suggestion
PLG_QUICKICON_JOOMLAUPDATE_UPDATEFOUND_MESSAGE="Joomla %s is available."
```

2018-11-16 11:02 UTC, brianteeman requested changes
punctuation as commented inline

2018-11-16 11:03 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +  text-align: left !important;
This is what is used in node_modules:
```
@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    .text#{$infix}-left   { text-align: left !important; }
    .text#{$infix}-right  { text-align: right !important; }
    .text#{$infix}-center { text-align: center !important; }
  }
}
```
and ported to `/administrator/templates/atum/css/bootstrap.css` once npm ci has run:
```
.text-left {
  text-align: left !important; }

.text-right {
  text-align: right !important; }

.text-center {
  text-align: center !important; }
```

2018-11-16 11:39 UTC, brianteeman approved these changes
approve language strings

2018-11-16 16:49 UTC, Quy commented on administrator/templates/atum/scss/template-rtl.scss
> +    right: 0;
Use 2 spaces to indent.

2018-11-17 06:39 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +    right: 0;
done.

2018-11-17 10:33 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on a41940342df38346ee358f349e4c513e8af1e995<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23095">issues.joomla.org/tracker/joomla-cms/23095</a>.</sub>

2018-11-18 09:44 UTC, infograf768 commented
Note: furher PR will correct RTL for the J version

2018-11-18 10:16 UTC, infograf768 commented
@richard67 
I need to update this now for RTL version but also for another js issue.
Please test again after I updated.

2018-11-18 10:56 UTC, infograf768 commented
@richard67 
OK, you can test again now.
The modifications concern the version in RTL (Test by using Persian), as well as showing the Joomlaupdate Quickicon in Green when there is no Update available.

<img width="376" alt="screen shot 2018-11-18 at 11 40 31" src="https://user-images.githubusercontent.com/869724/48671458-dd5ed900-eb28-11e8-86f4-5ad120e1bd3d.png">
<img width="522" alt="screen shot 2018-11-18 at 11 48 41" src="https://user-images.githubusercontent.com/869724/48671460-e354ba00-eb28-11e8-89df-3c316b9a8d2f.png">

2018-11-18 11:40 UTC, richard67 commented
@infograf768 I don't see any difference in the Persian screenshots. What has changed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23095">issues.joomla.org/tracker/joomla-cms/23095</a>.</sub>

2018-11-18 11:45 UTC, infograf768 commented
formerly (see on top), the version read alpha6-dev etc.
it now displays correctly 4.0.0-alpha etc, i.e. the version is ltr in a rtl lang string

2018-11-18 11:46 UTC, richard67 commented
I see now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23095">issues.joomla.org/tracker/joomla-cms/23095</a>.</sub>

2018-11-18 11:58 UTC, richard67 commented
@infograf768 Now I tested and it seemed ok. But after switching back the Joomla update channel to "Default" and changing back Version.php and fixing the database, I get a javascript error from the Joomla update check, and the update check does not finish:
![screen shot 2018-11-18 at 11 55 18](https://issues.joomla.org/uploads/1/13a9093a913833f3e493d049f78f037c.png)
Reverting the PR and running "npm ci" does not fix that, so I am not sure if related to this PR or not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23095">issues.joomla.org/tracker/joomla-cms/23095</a>.</sub>

2018-11-18 12:13 UTC, richard67 commented
@infograf768 I've started again with clean 4.0-dev, installed patch tester, applied your patch, run "npm ci", switched on system debugging in global settings so uncompressed js is used.
The js error is in jupdatecheck.js, row 32, column 11, which is statement "if (updateInfo.version === options.version) {", and sais "TypeError: updateInfo is undefined".
This seems to come from your last change.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23095">issues.joomla.org/tracker/joomla-cms/23095</a>.</sub>

2018-11-18 12:17 UTC, richard67 commented
@infograf768 It seems that the "if (updateInfoList.length === 0) {" you've removed with your last change was not there for no reason.

2018-11-18 12:39 UTC, infograf768 commented
on ipad now. will look later. the issue was to get the ‘success’ class instead of only ‘pulse’. we may have to define as var and empty the ‘updateinfo.version’ first.

2018-11-18 13:01 UTC, richard67 commented
@infograf768 Can you check if my PR [https://github.com/infograf768/joomla-cms/pull/50](https://github.com/infograf768/joomla-cms/pull/50) against your branch is the right thing to correct it and get what you want with the success class?

2018-11-18 13:30 UTC, richard67 commented
@infograf768 I've just tested my changes from [https://github.com/infograf768/joomla-cms/pull/50](https://github.com/infograf768/joomla-cms/pull/50), applied to this PR here, and it works. Javascript error is gone, and Joomla Update is green.

2018-11-18 15:48 UTC, infograf768 commented
Thanks @richard67 
I mark your test Ok again.

2018-11-18 16:04 UTC, richard67 commented
Yes, I've just tested again, works all well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23095">issues.joomla.org/tracker/joomla-cms/23095</a>.</sub>

2018-11-19 21:45 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +joomla-alert .joomla-alert--close, joomla-alert .joomla-alert-button--close {
Alerts are not part of the template. please put RTL CSS in the custom element file

2018-11-20 06:43 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +joomla-alert .joomla-alert--close, joomla-alert .joomla-alert-button--close {
@C-Lodder
This is an override for RTL.
The scss for alert is in `/node_modules/joomla-ui-custom-elements/src/scss/alert/alert.scss`

There is no provisions done for RTL in custom-elements which means we would have to use `html[dir=rtl] `(which is not a problem I guess).

Also it means that until someone merges a possible pull request in https://github.com/joomla-projects/custom-elements/blob/master/dist/css/joomla-alert.css and possibly https://github.com/joomla-projects/custom-elements/blob/master/dist/css/joomla-alert.min.css, this PR would not correct by itself the RTL display issue with alerts.

The other solution I see is to add these (with `html[dir=rtl] `), in the `atum/scss/blocks/_alert.scss` and also in Cassiopea equivalent file —which means that every 3rd party template will necessarily have to do that to be rtl compatible.

Just let me know what is the way to go.
calling @wilsonge as he has the hand on merging stuff in https://github.com/joomla-projects/custom-elements

2018-11-20 16:55 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +joomla-alert .joomla-alert--close, joomla-alert .joomla-alert-button--close {
@C-Lodder 
ping 😄

2018-11-21 16:53 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +joomla-alert .joomla-alert--close, joomla-alert .joomla-alert-button--close {
After discussion with @wilsonge will make PR towards https://github.com/joomla-projects/custom-elements/blob/master/src/scss/alert/alert.scss
and delete the same in template-rtl.scss>

We will have to wait the PR is merged and compile is done to see the rtl results here.

2018-11-23 09:14 UTC, infograf768 commented
RTL can now be tested fully as alert has been updated.
One has to use present 4.0.0-dev branch, patch and run npm ci.

Result:
<img width="420" alt="screen shot 2018-11-23 at 10 12 00" src="https://user-images.githubusercontent.com/869724/48935602-76feff80-ef08-11e8-99c7-5a04bd1eed10.png">

@richard67

2018-11-24 09:27 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 4ed7a1bc0d797c4491e1c95d6a680770bb4b2f01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23095">issues.joomla.org/tracker/joomla-cms/23095</a>.</sub>

2018-11-24 16:13 UTC, infograf768 commented
@wilsonge
same comment as in the other PR.
RTL testers are a rare category... ;)

2018-11-28 11:45 UTC, merged

2018-11-28 11:45 UTC, wilsonge commented
Thanks JM!

2018-11-28 11:48 UTC, infograf768 commented
and @richard67  ;)