[4.0] Implementing RTL for admin menus
joomla/joomla-cms pull request #23143
Opened 2018-11-22 17:19 UTC by infograf768

### Summary of Changes
Adding css in Atum template-rtl.scss

### Testing Instructions
Test by modifying `<rtl` tag in en-GB.xml. 
No need in this case to use Persian to test.

Use npm ci

### Reference
The menu as we get it for LTR
<img width="267" alt="screen shot 2018-11-22 at 17 46 05" src="https://user-images.githubusercontent.com/869724/48916474-c26eca80-ee82-11e8-843e-b8e5bda9603a.png">

### Before PR in RTL
<img width="296" alt="screen shot 2018-11-22 at 18 02 36" src="https://user-images.githubusercontent.com/869724/48916485-cc90c900-ee82-11e8-95f0-73d341854a72.png">

### After PR in RTL
<img width="271" alt="screen shot 2018-11-22 at 17 48 06" src="https://user-images.githubusercontent.com/869724/48916495-d87c8b00-ee82-11e8-999f-a37ece137b06.png">

@C-Lodder @Quy @wilsonge

2018-11-22 17:31 UTC, Quy commented on administrator/templates/atum/scss/template-rtl.scss
> +    right:18px;
```suggestion
    right: 18px;
```

2018-11-22 17:31 UTC, Quy commented on administrator/templates/atum/scss/template-rtl.scss
> +    right:inherit;
```suggestion
    right: inherit;
```

2018-11-23 07:09 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +    right:18px;
done

2018-11-23 07:09 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +    right:inherit;
done

2018-11-24 17:40 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 1e7874dfcd74a9f27bf4a5f2087921faaac1e39b<br /><br />Tested with Persian language.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23143">issues.joomla.org/tracker/joomla-cms/23143</a>.</sub>

2018-11-25 07:20 UTC, infograf768 commented
Thanks for testing. need one more.

2018-11-26 03:31 UTC, Quy commented
`Joomla! Update`, `Multilingual Associations` and `Post-Installation Messages` don't align with the other menus that have submenus.

2018-11-26 07:53 UTC, infograf768 commented
@Quy @richard67 
You are correct. Fine tuned these alignment.
Please test again 

We should now get:
<img width="296" alt="screen shot 2018-11-26 at 08 52 34" src="https://user-images.githubusercontent.com/869724/49000041-b4f26280-f158-11e8-89e5-3491c90e1f73.png">

2018-11-26 15:47 UTC, Quy commented
For the submenus, move to the right slightly.

2018-11-27 06:30 UTC, infograf768 commented
@Quy 
moved 2px to the right

<img width="463" alt="screen shot 2018-11-27 at 07 29 34" src="https://user-images.githubusercontent.com/869724/49063025-4e337e80-f216-11e8-87c2-73ed695beba8.png">

2018-11-27 07:20 UTC, infograf768 commented
Note to @Quy : we can play forever with slight modifications for these margins. The results are somehow a bit different when using Persian, Arabic or Hebrew as my experience shows it may depend on the font used.

2018-11-27 16:24 UTC, Quy commented
I have tested this item :white_check_mark: successfully on ba1a189614bfad702f98733ee2eb8a9382753fee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23143">issues.joomla.org/tracker/joomla-cms/23143</a>.</sub>

2018-11-27 16:52 UTC, C-Lodder requested changes

2018-11-27 16:52 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +    -webkit-transform: rotate(135deg) translate(0,-50%);
Don't use vendor prefixes. Autoprefix will take care of this

2018-11-27 16:57 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +    -webkit-transform: rotate(135deg) translate(0,-50%);
Sorry, I do not understand what you mean.

2018-11-27 17:02 UTC, mbabker commented on administrator/templates/atum/scss/template-rtl.scss
> +    -webkit-transform: rotate(135deg) translate(0,-50%);
You don't need to include vendor prefixed CSS rules in the SCSS files (i.e. the `-webkit-` stuff).  When the files are compiled to CSS, there is a package (autoprefixer) which handles adding these to the CSS as needed based on the supported browser rules.

2018-11-27 17:03 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +    -webkit-transform: rotate(135deg) translate(0,-50%);
should it just be
`transform: rotate(135deg) translate(0,-50%);`
once ?

2018-11-27 17:04 UTC, mbabker commented on administrator/templates/atum/scss/template-rtl.scss
> +    -webkit-transform: rotate(135deg) translate(0,-50%);
Yes.

2018-11-28 05:57 UTC, infograf768 commented on administrator/templates/atum/scss/template-rtl.scss
> +    -webkit-transform: rotate(135deg) translate(0,-50%);
done

2018-11-29 17:41 UTC, merged