Update Installer.php
joomla/joomla-cms pull request #23160
Opened 2018-11-24 20:57 UTC by eshiol

Pull Request for Issue # .

### Summary of Changes
Fixes a bug in the class Joomla\CMS\Installer\Installer

### Testing Instructions

### Expected result

### Actual result

### Documentation Changes Required

2018-11-25 00:56 UTC, zero-24 commented on libraries/src/Installer/Installer.php
> +			foreach ($custom as $name)
hmm can we please keep the variable name `$customAdapter` and replace $name with this?

2018-11-25 00:56 UTC, zero-24 requested changes
As noted inline

2018-12-03 12:46 UTC, wilsonge approved these changes

2018-12-03 14:52 UTC, infograf768 commented
May we know which bug this is supposed to solve? And how to reproduce that bug?

2019-04-24 10:22 UTC, franz-wohlkoenig commented
closing due the lack of response.

2019-04-24 10:22 UTC, closed without merging