Improve Update Message, remember Users to make a backup
joomla/joomla-cms pull request #23229
Opened 2018-12-04 21:55 UTC by chmst

Pull Request for Issue #23225 .

### Summary of Changes
Improve messages. Remember users to make backup before Updating

![updatemessage](https://user-images.githubusercontent.com/1035262/49475411-72dfb580-f817-11e8-864b-dac73085c77a.PNG)

### Documentation Changes Required
no

2018-12-04 21:57 UTC, brianteeman commented
i would encourage people to always take a backup before updating - not just if they are unsure about extensions

2018-12-04 22:22 UTC, chmst commented
You are strongly advised to make a <strong>backup</strong> of your installation before you start updating

Sounds somehow harsh. Maybe better

Please remember to make ...  

@brianteeman What do you think?

2018-12-04 22:33 UTC, mbabker commented
It's not harsh, it's a best practice of software management in general.  Any time you make a major change to the software platform, you should make a backup so if something goes wrong you can quickly get yourself going again.  This applies to everything; CMS', databases, web server software, programming language binaries (PHP, Node, etc.), operating systems, you name it.

2018-12-05 07:16 UTC, infograf768 commented
Also, why not change it to a Warning instead of a simple Notice?
<img width="685" alt="screen shot 2018-12-05 at 08 14 32" src="https://user-images.githubusercontent.com/869724/49496338-fcb66f80-f865-11e8-96da-f170a6ed581c.png">

2018-12-06 08:47 UTC, Didldu-Florian commented
I have tested this item :white_check_mark: successfully on a75664893488b961f0bf47b42fe62acb1eb81985<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23229">issues.joomla.org/tracker/joomla-cms/23229</a>.</sub>

2018-12-06 12:43 UTC, ReLater commented
I have tested this item :white_check_mark: successfully on a75664893488b961f0bf47b42fe62acb1eb81985<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23229">issues.joomla.org/tracker/joomla-cms/23229</a>.</sub>

2018-12-06 16:19 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23229">issues.joomla.org/tracker/joomla-cms/23229</a>.</sub>

2018-12-07 16:25 UTC, mbabker requested changes

2018-12-07 16:25 UTC, mbabker commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_MSG_WARNINGS_UPDATE_WARNING="Before updating ensure that the update is compatible with your Joomla! installation. <br>You are strongly advised to make a <strong>backup</strong> of your
The language key names can't be changed (B/C thing), this needs to be changed back

2018-12-07 16:37 UTC, infograf768 commented
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23229">issues.joomla.org/tracker/joomla-cms/23229</a>.</sub>

2018-12-07 19:43 UTC, chmst commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_MSG_WARNINGS_UPDATE_WARNING="Before updating ensure that the update is compatible with your Joomla! installation. <br>You are strongly advised to make a <strong>backup</strong> of your
Change reverted; Not quite consistent now as the _NOTICE now is displayed as a warning. Maybe a hint for forming Language Keys in the future.

2018-12-07 20:25 UTC, mbabker commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_MSG_WARNINGS_UPDATE_WARNING="Before updating ensure that the update is compatible with your Joomla! installation. <br>You are strongly advised to make a <strong>backup</strong> of your
You need to fix the other files too.

2018-12-07 20:29 UTC, chmst commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_MSG_WARNINGS_UPDATE_WARNING="Before updating ensure that the update is compatible with your Joomla! installation. <br>You are strongly advised to make a <strong>backup</strong> of your
Which files? you want to have reverted all changes except the language string?

2018-12-07 21:13 UTC, mbabker commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_MSG_WARNINGS_UPDATE_WARNING="Before updating ensure that the update is compatible with your Joomla! installation. <br>You are strongly advised to make a <strong>backup</strong> of your
Right.  The language key in both files should be back to having `_NOTICE` suffixes, then the two PHP files you updated should go back to having `_NOTICE` instead of `_WARNING`.

2018-12-08 06:30 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_installer.ini
> +COM_INSTALLER_MSG_WARNINGS_UPDATE_WARNING="Before updating ensure that the update is compatible with your Joomla! installation. <br>You are strongly advised to make a <strong>backup</strong> of your
What should be done is to keep the php code to show a warning instead of the Notice, i.e
`JFactory::getApplication()->enqueueMessage(JText::_('WHATEVER'), 'warning'); `
and revert there AND AS WELL in the ini files, instead of `WHATEVER`  the constant to the former one used, i.e. ending with`_NOTICE`.

This because, as I posted above, it is important enough to be a Warning and not just a Notice, and we should keep for B/C the former constant used.

Diff:
```
diff --git a/administrator/components/com_installer/views/update/view.html.php b/administrator/components/com_installer/views/update/view.html.php
index d5ee00be10ab..6cc57f863922 100644
--- a/administrator/components/com_installer/views/update/view.html.php
+++ b/administrator/components/com_installer/views/update/view.html.php
@@ -64,7 +64,7 @@ public function display($tpl = null)
 
 		if (count($this->items) > 0)
 		{
-			JFactory::getApplication()->enqueueMessage(JText::_('COM_INSTALLER_MSG_WARNINGS_UPDATE_NOTICE'), 'notice');
+			JFactory::getApplication()->enqueueMessage(JText::_('COM_INSTALLER_MSG_WARNINGS_UPDATE_NOTICE'), 'warning');
 		}
 
 		parent::display($tpl);
diff --git a/administrator/components/com_joomlaupdate/views/default/view.html.php b/administrator/components/com_joomlaupdate/views/default/view.html.php
index bf818032ed2b..19566fa45193 100644
--- a/administrator/components/com_joomlaupdate/views/default/view.html.php
+++ b/administrator/components/com_joomlaupdate/views/default/view.html.php
@@ -88,7 +88,7 @@ public function display($tpl = null)
 		if (!is_null($this->updateInfo['object']))
 		{
 			// Show the message if an update is found.
-			JFactory::getApplication()->enqueueMessage(JText::_('COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATE_NOTICE'), 'notice');
+			JFactory::getApplication()->enqueueMessage(JText::_('COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATE_NOTICE'), 'warning');
 		}
 
 		$this->ftpFieldsDisplay = $this->ftp['enabled'] ? '' : 'style = "display: none"';
diff --git a/administrator/language/en-GB/en-GB.com_installer.ini b/administrator/language/en-GB/en-GB.com_installer.ini
index 57855ee63434..543ee5017abc 100644
--- a/administrator/language/en-GB/en-GB.com_installer.ini
+++ b/administrator/language/en-GB/en-GB.com_installer.ini
@@ -177,7 +177,7 @@ COM_INSTALLER_MSG_WARNINGS_SMALLPOSTSIZE="Small PHP maximum POST size."
 COM_INSTALLER_MSG_WARNINGS_SMALLPOSTSIZEDESC="The maximum POST size sets the most amount of data that can be sent via POST to the server. This includes form submissions for articles, media (images, videos) and packages. This value is less than 8MB which may impact on uploading large packages. This is set in the php.ini under post_max_size."
 COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZE="Maximum PHP file upload size is too small: This is set in php.ini in both upload_max_filesize and post_max_size settings of your PHP settings (located in php.ini and/or .htaccess file)."
 COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZEDESC="The maximum file size for uploads is set to less than 8MB which may impact on uploading large packages."
-COM_INSTALLER_MSG_WARNINGS_UPDATE_NOTICE="Before updating ensure that the update is compatible with your Joomla! installation."
+COM_INSTALLER_MSG_WARNINGS_UPDATE_NOTICE="Before updating ensure that the update is compatible with your Joomla! installation. <br>You are strongly advised to make a <strong>backup</strong> of your installation before you start updating."
 COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOST="PHP Upload Size bigger than POST size."
 COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOSTDESC="The value of the upload_max_filesize in the php.ini file is greater than the post_max_size variable. The post_max_size variable will take precedence and block requests larger than it. This is generally a server misconfiguration when trying to increase upload sizes. Please increase the upload_max_filesize to at least match the post_max_size variable or vice versa."
 COM_INSTALLER_N_EXTENSIONS_PUBLISHED="%d extensions enabled."
diff --git a/administrator/language/en-GB/en-GB.com_joomlaupdate.ini b/administrator/language/en-GB/en-GB.com_joomlaupdate.ini
index fe42f2da9cb0..724ce9ad1ae2 100644
--- a/administrator/language/en-GB/en-GB.com_joomlaupdate.ini
+++ b/administrator/language/en-GB/en-GB.com_joomlaupdate.ini
@@ -58,7 +58,7 @@ COM_JOOMLAUPDATE_VIEW_DEFAULT_PACKAGE="Update package URL"
 COM_JOOMLAUPDATE_VIEW_DEFAULT_PACKAGE_REINSTALL="Reinstall package URL"
 COM_JOOMLAUPDATE_VIEW_DEFAULT_TAB_ONLINE="Live Update"
 COM_JOOMLAUPDATE_VIEW_DEFAULT_TAB_UPLOAD="Upload & Update"
-COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATE_NOTICE="Before you update Joomla, ensure that the installed extensions are available for the new Joomla version."
+COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATE_NOTICE="Before you update Joomla, ensure that the installed extensions are available for the new Joomla version. <br>You are strongly advised to make a <strong>backup</strong> of your installation before you start updating."
 COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATEFOUND="A Joomla update was found."
 COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_CUSTOM="You are on the &quot;%s&quot; update channel. This is not an official Joomla update channel."
 COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_DEFAULT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (3.x)"

```

2018-12-08 11:34 UTC, ReLater commented
I have tested this item :white_check_mark: successfully on 0e01ac1303114c4468e61158f3c3521c863ba5c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23229">issues.joomla.org/tracker/joomla-cms/23229</a>.</sub>

2018-12-08 17:39 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 0e01ac1303114c4468e61158f3c3521c863ba5c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23229">issues.joomla.org/tracker/joomla-cms/23229</a>.</sub>

2018-12-08 17:40 UTC, infograf768 commented
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23229">issues.joomla.org/tracker/joomla-cms/23229</a>.</sub>

2018-12-12 05:37 UTC, merged