com_media: normalizing file names
joomla/joomla-cms pull request #23259
Opened 2018-12-10 18:20 UTC by infograf768

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23249

### Summary of Changes
Adding hyphens to permitted characters in file names uploaded by drag and drop in TinyMCE.

Normalizing file names in direct com_media upload files to fit with the drag and drop format:

1. the name of a file should not contain any period `.` before the extension.
(real original name of these files are of the type: `Screen Shot 2018-12-09 at 07.43.58.png` on my Mac)
This is nicely taken care of when drag and drop as periods are replaced by nothing (after adding the hyphen in the code above).
`Screen_Shot_2018-12-09_at_075108.png`
BUT not in normal upload where I get:
`Screen-Shot-2018-12-10-at-09.29.49.png`

2. Also, spaces are replaced by hyphens in one case and by underscores in the other.

### Testing Instructions
Upload a file (usually an image) containing spaces and periods in other place than before the extension, both using com_media and drag and drop.

### After patch
An image which name on the desktop is
`Screen Shot 2018-12-09 at 07.43.58.png`

will be uploaded to Joomla as
`Screen_Shot_2018-12-09_at_074358.png`

2018-12-10 19:09 UTC, Quy commented on administrator/components/com_media/controllers/file.php
> +			$tempExt = (!empty($fileparts['extension'])) ? strtolower($fileparts['extension']) : '';
```suggestion
			$tempExt = !empty($fileparts['extension']) ? strtolower($fileparts['extension']) : '';
```

2018-12-10 19:38 UTC, dgrammatiko requested changes

2018-12-10 19:38 UTC, dgrammatiko commented on administrator/components/com_media/controllers/file.json.php
> +			$safeFileName = preg_replace(array("/[\\s]/", '/[^a-zA-Z0-9_\-]/'), array('_', ''), $fileparts['filename']) . '.' . $tempExt;
Can we allow the character `@` also? Eg `'/[^a-zA-Z0-9_\-@]/'` should be ok. Reason: it's quite common for responsive images or images for different pixel density

2018-12-11 07:10 UTC, infograf768 commented on administrator/components/com_media/controllers/file.json.php
> +			$safeFileName = preg_replace(array("/[\\s]/", '/[^a-zA-Z0-9_\-]/'), array('_', ''), $fileparts['filename']) . '.' . $tempExt;
This would require modifying the library `makeSafe()` method.

IMHO, this should be considered for another patch.

2018-12-11 07:12 UTC, infograf768 commented on administrator/components/com_media/controllers/file.php
> +			$tempExt = (!empty($fileparts['extension'])) ? strtolower($fileparts['extension']) : '';
tks, Done and also in the json file.

2018-12-13 18:43 UTC, Quy commented on administrator/components/com_media/controllers/file.json.php
> +			$safeFileName = preg_replace(array("/[\\s]/", '/[^a-zA-Z0-9_\-]/'), array('_', ''), $fileparts['filename']) . '.' . $tempExt;
```suggestion
			$safeFileName = preg_replace(array("/[\\s]/", '/[^a-zA-Z0-9_-]/'), array('_', ''), $fileparts['filename']) . '.' . $tempExt;
```
No need to escape the hyphen.

2018-12-13 18:44 UTC, Quy commented on administrator/components/com_media/controllers/file.php
> +			$safeFileName = preg_replace(array("/[\\s]/", '/[^a-zA-Z0-9_\-]/'), array('_', ''), $fileparts['filename']) . '.' . $tempExt;
```suggestion
			$safeFileName = preg_replace(array("/[\\s]/", '/[^a-zA-Z0-9_-]/'), array('_', ''), $fileparts['filename']) . '.' . $tempExt;
```

2018-12-20 19:33 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 36ec8ea614fa65416928069a284399fb3d21e354<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23259">issues.joomla.org/tracker/joomla-cms/23259</a>.</sub>

2018-12-24 07:51 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 36ec8ea614fa65416928069a284399fb3d21e354<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23259">issues.joomla.org/tracker/joomla-cms/23259</a>.</sub>

2018-12-24 07:53 UTC, infograf768 commented
Thanks for testing. RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23259">issues.joomla.org/tracker/joomla-cms/23259</a>.</sub>

2018-12-27 19:02 UTC, merged