[com_actionlogs] - log checkin actions
joomla/joomla-cms pull request #23526
Opened 2019-01-13 09:21 UTC by alikon

### Summary of Changes
keep track of check-in actions  (redo of #22530)

### Testing Instructions
-  Maintenance: Global Check-in
- Check-in a checked out item

### Expected result

![screenshot from 2018-10-07 13-12-47](https://user-images.githubusercontent.com/181681/46581122-c2ca1800-ca32-11e8-9273-9bda53ed595b.png)

### Actual result
not logged

### Documentation Changes Required

2019-01-13 10:45 UTC, twister65 commented
With Joomla! Patch Tester, database (postgresql) is not updated.
`com_checkin` is missing in `#__action_logs_extensions` table.

2019-01-13 16:22 UTC, mbabker commented
As has always been noted, com_patchtester cannot and does not automatically apply SQL changes (it only applies filesystem diffs and there is no logic in place to be able to reverse a SQL change from a patch).

2019-01-14 16:28 UTC, twister65 requested changes

2019-01-14 16:28 UTC, twister65 commented on administrator/components/com_admin/sql/updates/postgresql/3.9.3-2019-01-12.sql
> +INSERT INTO "#__action_logs_extensions" ("id","extensions") VALUES
```suggestion
INSERT INTO "#__action_logs_extensions" ("id","extension") VALUES
```

2019-01-14 16:28 UTC, twister65 commented on administrator/components/com_admin/sql/updates/mysql/3.9.3-2019-01-12.sql
> +INSERT INTO `#__action_logs_extensions` (`id`,`extensions`) VALUES
```suggestion
INSERT INTO `#__action_logs_extensions` (`id`,`extension`) VALUES
```

2019-01-14 16:28 UTC, twister65 commented on administrator/components/com_admin/sql/updates/sqlazure/3.9.3-2019-01-12.sql
> +INSERT INTO "#__action_logs_extensions" ("id","extensions") VALUES
```suggestion
INSERT INTO "#__action_logs_extensions" ("id","extension") VALUES
```

2019-01-14 16:38 UTC, mbabker commented on administrator/components/com_admin/sql/updates/mysql/3.9.3-2019-01-12.sql
> +INSERT INTO `#__action_logs_extensions` (`id`,`extensions`) VALUES
This insert (and similar for other drivers) can be done without the ID as well.  Otherwise, this can conflict with any extensions which have added support for the action log component and added their own rows to this table.

2019-01-15 18:43 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/3.9.3-2019-01-12.sql
> +INSERT INTO "#__action_logs_extensions" ("id","extensions") VALUES
done thx

2019-01-15 18:43 UTC, alikon commented on administrator/components/com_admin/sql/updates/mysql/3.9.3-2019-01-12.sql
> +INSERT INTO `#__action_logs_extensions` (`id`,`extensions`) VALUES
done

2019-01-15 18:43 UTC, alikon commented on administrator/components/com_admin/sql/updates/sqlazure/3.9.3-2019-01-12.sql
> +INSERT INTO "#__action_logs_extensions" ("id","extensions") VALUES
done

2019-01-15 19:22 UTC, twister65 commented
I have tested this item :white_check_mark: successfully on c2614e2d7fb28997588d2506c815fcaced97de32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23526">issues.joomla.org/tracker/joomla-cms/23526</a>.</sub>

2019-01-16 18:40 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on c2614e2d7fb28997588d2506c815fcaced97de32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23526">issues.joomla.org/tracker/joomla-cms/23526</a>.</sub>

2019-01-16 18:48 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23526">issues.joomla.org/tracker/joomla-cms/23526</a>.</sub>

2019-01-19 08:23 UTC, merged

2019-02-17 15:42 UTC, twister65 commented
I'm sorry, but there is a postgreSQL issue with this PR. I did my test with a fresh installation but not with the update script. The update to Joomla 3.9.3 now fails with a postgreSQL database. This PR should not be merged, too late ...

2019-02-17 15:45 UTC, twister65 reviewed
https://github.com/alikon/joomla-cms/blob/c2614e2d7fb28997588d2506c815fcaced97de32/administrator/components/com_admin/sql/updates/postgresql/3.9.3-2019-01-12.sql#L8
`SELECT setval('#__action_logs_extensions_id_seq', max(id)+1, false) FROM "#__action_logs_extensions";`

2019-02-17 15:51 UTC, twister65 commented
Also, I do not know why, but the action_log and privacy sequences are missing in my postgresql database. The update to Joomla 3.9.0 creates only the tables but not the sequences. This script fixes this problem:
[3.9.4-2019-02-17.txt](https://github.com/joomla/joomla-cms/files/2873116/3.9.4-2019-02-17.txt)