mod_articles_news - Exclude current article
joomla/joomla-cms pull request #23575
Opened 2019-01-17 12:10 UTC by pe7er

This PR adds in the **Latest News Module** (mod_articles_news) an option **exclude the current article** to filter the current article from displaying in the module.

### Summary of Changes
If you configure the Latest News Module to display Articles from Category "A",
and the Module is displayed on an Article page (that is also in Category "A"),
the Article is displayed on the page and in the Module.

- This  PR adds an option in the Latest News Module to exclude the current article.
- The option is OFF by default (so the current behavior before installing the patch is default)
- It also checks for com_content being active to prevent that other components that use an "id" might interfere with the Latest News Module output.

### Testing Instructions

- Create  a Category "A"
- Add 5 different articles with different titles
- Create a menu item for Category blog and another for Single Article
- Assign the "Latest News" Module to the two pages, configure display title and change the limit to 5.
- If you are on an Article page, the com_content component article view will display the article, but it is also visible in the "Latest News" Module output.
- In the parameters of "Latest News" Module, switch on "Exclude current Article" and check the page again.

![mod_articles_news-exclude-article](https://user-images.githubusercontent.com/1217850/51317873-0a603700-1a59-11e9-8a93-0e97ee002413.png)

2019-01-17 19:26 UTC, Quy commented on modules/mod_articles_news/helper.php
>  		// Filer by tag
```suggestion
		// Filter by tag
```

2019-01-17 19:27 UTC, Quy commented on modules/mod_articles_news/mod_articles_news.xml
> +				>
```suggestion
					>
```

2019-01-17 19:27 UTC, Quy commented on modules/mod_articles_news/mod_articles_news.xml
> +						name="exclude_current"
Reduce lines 190-196 by one tab.

2019-01-17 19:27 UTC, Quy commented on language/en-GB/en-GB.mod_articles_news.ini
> +MOD_ARTICLES_NEWS_FIELD_EXCLUDE_CURRENT_LABEL="Exclude current Article"
```suggestion
MOD_ARTICLES_NEWS_FIELD_EXCLUDE_CURRENT_LABEL="Exclude Current Article"
```

2019-01-31 20:55 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on 1da3533d19edbb6e6383ca355053ddb9b87e05c1<br /><br />I have tested this successfully on Joomla! 3.9.2.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23575">issues.joomla.org/tracker/joomla-cms/23575</a>.</sub>

2019-02-03 21:30 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 1da3533d19edbb6e6383ca355053ddb9b87e05c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23575">issues.joomla.org/tracker/joomla-cms/23575</a>.</sub>

2019-02-03 22:17 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23575">issues.joomla.org/tracker/joomla-cms/23575</a>.</sub>

2019-02-09 16:33 UTC, HLeithner requested changes

2019-02-09 16:33 UTC, HLeithner commented on language/en-GB/en-GB.mod_articles_news.ini
> +MOD_ARTICLES_NEWS_FIELD_EXCLUDE_CURRENT_LABEL="Exclude current Article"
@brianteeman lower case is correct or?

2019-02-09 16:33 UTC, HLeithner commented on modules/mod_articles_news/mod_articles_news.xml
> +						name="exclude_current"
@pe7er can you please fix cs

2019-04-20 22:26 UTC, brianteeman commented
this should not be rtc

2019-04-21 20:33 UTC, pe7er commented
Thank you all for testing!
This PR was for Joomla 3.x but won't be added in that series anymore.
I've redone this PR for Joomla 4: https://github.com/joomla/joomla-cms/pull/24672
Closing this PR...

2019-04-21 20:33 UTC, closed without merging