Fixed the bottom-top icon on multiple footer elements(Ref #23457)
joomla/joomla-cms pull request #23606
Opened 2019-01-20 19:04 UTC by yellowwoods12

Pull Request for Issue #23457 

### Summary of Changes

Modified the index.php and added a new css file according to the instructions provided in the issue.

### Testing Instructions

### Expected result

### Actual result

### Documentation Changes Required

2019-01-20 20:14 UTC, dgrammatiko requested changes

2019-01-20 20:14 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +      </div>
This needs to go after the `</footer>`

2019-01-20 20:14 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +  <div class="site-grid site position-relative">
Adding a container is wrong, it shows a lack of understanding grid layout and flex box. This can be done differently without adding more useless divs in the markup

2019-01-20 20:58 UTC, yellowwoods12 commented on templates/cassiopeia/index.php
> +  <div class="site-grid site position-relative">
@dgrammatiko how else can I tackle this?

2019-01-20 20:58 UTC, yellowwoods12 commented on templates/cassiopeia/index.php
> +      </div>
@dgrammatiko done.

2019-01-20 21:02 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +  <div class="site-grid site position-relative">
Check the grid code.
Probably add one more line to accommodate the arrow.
Restore the grid in the body
Then the markup after the footer (as is right now) should work:
```html
  <div class="gotop">
		   <a href="#top" id="back-top" class="back-top" title="<?php echo Text::_('TPL_CASSIOPEIA_BACKTOTOP'); ?>"><span class="icon-arrow-up-4" aria-hidden="true"></span></a>
		   </div>
	
   </div>
```

2019-01-20 21:03 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +  <div class="site-grid site position-relative">
The grid is here: https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/blocks/_css-grid.scss

2019-01-21 09:20 UTC, ciar4n commented
As mentioned, I don't believe there is a need for the extra div inside the body.

Firstly move the following outside of the `footer`.. https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/blocks/_footer.scss#L5-L10 Add your absolute positioning and set the `body` position to relative (https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/blocks/_global.scss#L8).

2019-01-21 09:26 UTC, C-Lodder commented
Do you not think it would be best to make the "Back to Top" a custom module and add the markup in there?

This way the user can easily disable it without affecting the footer module and the HTML is decoupld from the `index.php`

If I rightly remember, this was our objective a couple of years back, e.g the footer, logo, etc..

2019-01-21 09:51 UTC, infograf768 commented
> Do you not think it would be best to make the "Back to Top" a custom module and add the markup in there?

Why not, as long as RTL is taken care of, which is also not done in this PR.
I had proposed in the original issue if we keep the new `<div>`, i.e. if we have that part in index.php
```
+		<div class="gotop">
+			<a href="#top" id="back-top" class="back-top" title="<?php echo Text::_('TPL_CASSIOPEIA_BACKTOTOP'); ?>"><span class="icon-arrow-up-4" aria-hidden="true"></span></a>
+		</div>
```
The following css
```
diff --git a/templates/cassiopeia/scss/blocks/_footer.scss b/templates/cassiopeia/scss/blocks/_footer.scss
index 60642d0..a3cc206 100644
--- a/templates/cassiopeia/scss/blocks/_footer.scss
+++ b/templates/cassiopeia/scss/blocks/_footer.scss
@@ -1,12 +1,21 @@
-// Footer
+// Footer back to top
 
-.footer {
-
-  .back-top {
-    padding: 8px 11px;
-    color: #fff;
-    background: $cassiopeia-template-color;
-    border-radius: 3px;
-  }
-
+.gotop {
+  position: absolute; 
+  width: 38px; 
+  height: 34px; 
+  padding: 7px 12px; 
+  border-radius: 3px; 
+  bottom: -24px; 
+  right: 10px; 
+  background-color: $cassiopeia-template-color;
+  z-index: 999;
 }
+
+.back-top {
+  color: white;
+}
+
+.back-top:hover {
+  color: #A1A0BB;
+}
\ No newline at end of file
diff --git a/templates/cassiopeia/scss/template-rtl.scss b/templates/cassiopeia/scss/template-rtl.scss
index dc4944a..f737aa7 100644
--- a/templates/cassiopeia/scss/template-rtl.scss
+++ b/templates/cassiopeia/scss/template-rtl.scss
@@ -57,2 +57,7 @@
   padding-right: 0;
 }
+
+.gotop { 
+  right: auto;
+  left: 10px;
+}
```

2019-01-22 02:14 UTC, yellowwoods12 commented on templates/cassiopeia/index.php
> +  <div class="site-grid site position-relative">
@dgrammatiko please review and give your feedback.

2019-01-22 02:17 UTC, yellowwoods12 commented
@infograf768 how can I resolve the RTL thing?

2019-01-22 09:26 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +<body class="site-grid site<?php echo $option
Restore the space here

2019-01-22 09:27 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +
Code style, eg tabs instead of spaces

2019-01-22 09:27 UTC, dgrammatiko commented on templates/cassiopeia/js/template.js
> +})(Joomla, document);
Please undo the changes here

2019-01-22 09:28 UTC, dgrammatiko commented on templates/system/build_incomplete.html
>    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Yo don; t have to commit this file

2019-01-22 09:28 UTC, dgrammatiko commented on templates/system/incompatible.html
> +  <script>window.errorLocale = {"en-GB":{"language":"English GB","header":"Sorry, your PHP version is not supported","text1":"Your host needs to use PHP version {{phpversion}} or newer to run this ve
Yo don; t have to commit this file

2019-01-22 09:29 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +  <div class="site-grid site position-relative">
Looking good, some small details and then couple tests and you're good to go!

2019-01-22 10:00 UTC, ciar4n commented on templates/cassiopeia/scss/blocks/_css-grid.scss
> +      ". footer footer footer gotop ."
I can't see this working. Firstly you need to define your `gotop` element as a template area here... https://github.com/joomla/joomla-cms/blob/f89bdb6f6f8f887ff2be4304eb06aea7d6473a32/templates/cassiopeia/scss/blocks/_css-grid.scss#L105

Secondly you have applied a position fixed to your element which just takes it back out of the grid you are attempting to add it to.

It is up to you but if it was me I would do as suggested here.. https://github.com/joomla/joomla-cms/pull/23606#issuecomment-456001905

If you wish to switch the position of your element on RTL (I am not even sure this is a RTL requirement as its not a text base element), add as suggested to the template_rtl.scss

```css
.whatever {
  left: 10px;
  right: auto;
}
```

2019-01-22 10:08 UTC, infograf768 commented
> how can I resolve the RTL thing?

The css I posted above explain it.

I still do not agree concerning size and color of the icon. It should imho be smaller and use the template color
I also question the creation of `user.css` in `templates/system/css/` instead of using  `_footer.scss` or a new `_whatever-scss` file in Cassiopeia scss/blocks folder as this ONLY concerns Cassiopeia template.

If footer.scss is not used anymore, it should be deleted and `@import "blocks/footer";` also in template.scss.

2019-04-09 06:40 UTC, C-Lodder requested changes

2019-04-09 06:40 UTC, C-Lodder commented on templates/cassiopeia/index.php
> +<body class="site-grid site<?php echo $option
Space still hasnt been restored

2019-04-09 06:40 UTC, C-Lodder commented on templates/system/css/user.css
> +  color: white;
Please use an CSS variable

2019-04-09 06:40 UTC, C-Lodder commented on templates/system/css/user.css
> +  color: #A1A0BB;
Same applies here and also use lowercase characters

2019-04-09 06:41 UTC, C-Lodder requested changes

2019-04-09 06:41 UTC, C-Lodder commented on templates/system/css/user.css
> +  background-color: rgba(67, 76, 120, 0.75);
Please use a CSS variable

2019-06-16 19:16 UTC, closed without merging

2019-06-16 19:16 UTC, Quy commented
Closing as this is not the proper fix. Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23606">issues.joomla.org/tracker/joomla-cms/23606</a>.</sub>