Add layouts to plg_system_privacyconsent
joomla/joomla-cms pull request #23660
Opened 2019-01-24 17:13 UTC by Ruud68

Pull Request for Issue # n/a.

### Summary of Changes
the layouts for plg_system_privacyconsent (label and privacynote) are hardcoded into the field and cannot be overwritten by a template override
This PR adds layouts for both the label and for the privacynote (message). these layouts can be overwritten via template overrides.

### Testing Instructions
1. enable the privacyconsent system plugin
2. set a joomla article as privacy article in the plugin
on the front-end user registration page the privacyconsent box should show

Apply this PR

[test] on the front-end user regsitration page the privacyconsent box should be exactly the same as without this PR.

3. create a template override via the template (e.g. protostar):
-> tab Create Overrides
-> column Layouts
-> select plugins > system (new!)

Edit the created override file: ./templates/protostar/html/layouts/plugins/system/privacyconsent/message.php
4. change the class from alert-info to alert-warning

[Result 1] refresh on the front-end the new user registration form

Edit the created override file: ./templates/protostar/html/layouts/plugins/system/privacyconsent/label.php
5. change ```<span class="star">&#160;*</span></label>``` to ```<span class="star">&copy;*</span></label>```

[Result 2] refresh on the front-end the new user registration form

### New result
![image](https://user-images.githubusercontent.com/2733197/51695148-a2829100-2002-11e9-86ea-72e267cbc5c3.png)

### Actual result
Make sure that after applying the PR everything works as before.

### Documentation Changes Required

2019-01-24 17:27 UTC, Quy commented on plugins/system/privacyconsent/field/privacy.php
> +	 * @since ___VERSION___
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2019-01-24 17:28 UTC, Quy commented on layouts/plugins/system/privacyconsent/label.php
> +//~ $privacyArticle = $this->element['article'] > 0 ? (int) $this->element['article'] : 0;
Remove comment

2019-01-25 07:47 UTC, Ruud68 commented on layouts/plugins/system/privacyconsent/label.php
> +//~ $privacyArticle = $this->element['article'] > 0 ? (int) $this->element['article'] : 0;
Thanks @Quy !

2019-01-27 13:57 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 2c75abde0227b446aa7cb3a956064d03ffa00229<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23660">issues.joomla.org/tracker/joomla-cms/23660</a>.</sub>

2019-01-27 14:28 UTC, Ruud68 commented
Thanks for testing @viocassel

2019-02-03 11:57 UTC, wilsonge commented
Please fix the file permissions on the privacy field

2019-02-03 14:20 UTC, Ruud68 commented
@wilsonge thanks, not sure where that happened... anyway: fixed :)
Once this PR is approved I will also do the same for the user terms plugin (same 'issue', same solution)

2019-02-06 13:49 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on fa7b390ef7fd2058915a8b49762a860a86f6d3e4<br /><br />I have tested this item successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23660">issues.joomla.org/tracker/joomla-cms/23660</a>.</sub>

2019-02-06 13:51 UTC, tecpromotion commented
> @wilsonge thanks, not sure where that happened... anyway: fixed :)
> Once this PR is approved I will also do the same for the user terms plugin (same 'issue', same solution)

That sounds really great when all the privacy suite codes are overwritable. Thank you @Ruud68

2019-02-06 14:11 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23660">issues.joomla.org/tracker/joomla-cms/23660</a>.</sub>

2019-02-07 16:57 UTC, Ruud68 commented
same change for plg_user_terms: https://issues.joomla.org/tracker/joomla-cms/23787<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23660">issues.joomla.org/tracker/joomla-cms/23660</a>.</sub>

2019-02-08 09:43 UTC, SharkyKZ requested changes

2019-02-08 09:43 UTC, SharkyKZ commented on layouts/plugins/system/privacyconsent/label.php
> +	$db    = Factory::getDbo();
Database queries should remain in the field class.

2019-02-08 10:34 UTC, Ruud68 commented on layouts/plugins/system/privacyconsent/label.php
> +	$db    = Factory::getDbo();
Thanks @SharkyKZ

2019-02-08 10:34 UTC, Ruud68 commented
@Quy please remove RTC as this needs retesting

2019-02-18 21:25 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on f0491e4a3d3318c09d0e9f1d3ee11d94446129fe<br /><br />I have tested this item successfully on 3.9.3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23660">issues.joomla.org/tracker/joomla-cms/23660</a>.</sub>

2019-02-18 21:39 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on f0491e4a3d3318c09d0e9f1d3ee11d94446129fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23660">issues.joomla.org/tracker/joomla-cms/23660</a>.</sub>

2019-02-19 15:05 UTC, merged

2019-02-19 15:05 UTC, HLeithner commented
thx