[4.0] FIX SQL int default value to  numeric
joomla/joomla-cms pull request #23669
Opened 2019-01-25 18:55 UTC by amitranjan2

Pull Request for Issue #23668

### Summary of Changes

INT DEFAULT value changed to numeric from char 

### Expected result
same as before

### Actual result

same as before 

### Documentation Changes Required
NO

2019-01-27 09:02 UTC, alikon requested changes

2019-01-27 09:02 UTC, alikon commented on build/media/com_menus/css/admin-item-edit_modules.css
> +
why this file in the PR ?

2019-01-27 10:21 UTC, amitranjan2 commented on build/media/com_menus/css/admin-item-edit_modules.css
> +
I removed

2019-01-27 10:23 UTC, alikon commented
don't forget to take care of postgresql too
for example https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/postgresql/joomla.sql#L757

2019-01-27 11:37 UTC, amitranjan2 commented
Done

2019-01-28 07:00 UTC, amitranjan2 commented
@alikon  I think it's fine now, please review this

2019-01-28 09:56 UTC, alikon commented
I have tested this item :white_check_mark: successfully on d69fbaec6f419c6b471677ad7843107753c13c0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23669">issues.joomla.org/tracker/joomla-cms/23669</a>.</sub>

2019-01-31 17:03 UTC, Anu1601CS commented
I have tested this item :white_check_mark: successfully on 15d77e6f007d0745743aeda0f7331c82b7e3e19b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23669">issues.joomla.org/tracker/joomla-cms/23669</a>.</sub>

2019-01-31 17:05 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23669">issues.joomla.org/tracker/joomla-cms/23669</a>.</sub>

2019-02-04 23:47 UTC, merged

2019-02-04 23:48 UTC, wilsonge commented
Thankyou very much for your first contribution! Much appreciated!

2019-02-05 09:09 UTC, amitranjan2 commented
Thanks a lot