[4.0] FIX Unreliable way of loading ServiceProviderInterface class in ExtensionManagerTrait.php
joomla/joomla-cms pull request #23667
Opened 2019-01-25 13:58 UTC by joeforjoomla

Pull Request for Issue #22825 .

### Summary of Changes
Use the Factory to cache loaded extensions throughout different Application instances

### Testing Instructions
See previous PR https://github.com/joomla/joomla-cms/pull/22825

### Expected result
Loaded extensions from the cache are always correct

### Actual result
Loaded extensions from the cache are always correct

2019-01-27 15:39 UTC, laoneo commented
If you want to make a cache, then better to use the ExtensionHelper class inszead of the already polluted Factory.

2019-01-29 10:37 UTC, joeforjoomla commented
I agree @laoneo this PR has been modified to properly implement an extensions cache using the ExtensionHelper class. 
Please test.

2019-01-29 13:28 UTC, laoneo requested changes

2019-01-29 13:28 UTC, laoneo commented on libraries/src/Extension/ExtensionHelper.php
> +	 * @var    CMSApplicationInterface
This type here is wrong

2019-01-30 09:34 UTC, joeforjoomla commented on libraries/src/Extension/ExtensionHelper.php
> +	 * @var    CMSApplicationInterface
Fixed type to array.

2019-02-05 13:18 UTC, laoneo approved these changes

2019-03-11 20:51 UTC, joeforjoomla commented
Can this PR be tested and merged ASAP? Otherwise it's difficult to fully test extensions everytime that a new alpha version is released. Pinging @wilsonge here, thanks!

2019-03-15 10:49 UTC, wilsonge commented
Thanks for the ping - sorry I missed this - LGTM!

2019-03-15 11:09 UTC, merged

2019-03-15 14:55 UTC, joeforjoomla commented
Thanks @wilsonge ! You are the best :)