[4.0] WebAssetManager: Speed up enable/disable asset
joomla/joomla-cms pull request #23713
Opened 2019-01-29 17:29 UTC by Fedik

### Summary of Changes

WebAssetManager calculate dependencies on "request" (when it really need) instead of each call of `enableAsset`/`disableAsset`.
This will speed up operations like:
```php
$wa->enableAsset('foo')
  ->enableAsset('bar')
  ->disableAsset('bear')
  ->enableAsset('beer');
```

Additionally I have updated a comment for a Manager interface, added missed throws tags.

### Testing Instructions
Apply the patch and make sure everything still work :wink: 

ping @wilsonge 

for reference #22435

2019-01-29 17:36 UTC, Fedik commented
I think I am banned to see ci.joomla.org, so cannot help with Drone, sorry :smile:

2019-01-29 18:42 UTC, dgrammatiko commented
@Fedik here is the failure:
```
FILE: ...github.com/joomla/joomla-cms/libraries/src/WebAsset/WebAssetManager.php
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
 91 | ERROR | Expected 1 blank line before member var; 2 found
```

2019-01-29 18:43 UTC, Fedik commented
@dgrammatiko thanks!

2019-01-29 18:44 UTC, dgrammatiko requested changes

2019-01-29 18:44 UTC, dgrammatiko commented on libraries/src/WebAsset/WebAssetManager.php
> +
remove empty line

2019-01-29 19:11 UTC, Fedik commented on libraries/src/WebAsset/WebAssetManager.php
> +
ok now

2019-05-05 20:52 UTC, merged

2019-05-05 20:52 UTC, wilsonge commented
Thanks!