Ce permissions
joomla/joomla-cms pull request #23729
Opened 2019-01-31 13:32 UTC by C-Lodder

### Summary of Changes

Rework the Permissions Custom Element

- Cache variables in the constructor
- Decouple FontAwesome
- Make use of identical operators
- Eslint fixes

### Testing Instructions

1. To go the `permissions` tab in Global Configuration
2. Change the permission for different actions

### Expected result

- Refresh and ensure the permission you selected is still set
- Ensure the icons are visible

2019-01-31 13:39 UTC, dgrammatiko requested changes

2019-01-31 13:39 UTC, dgrammatiko commented on build/media/webcomponents/js/field-permissions/field-permissions.js
> +  }
Can you add also the disconnectedCallback like:
```js
          /**
	   * Lifecycle
	   */
	  disconnectedCallback() {
	    if (this.buttons) {
	      this.buttons.forEach((button) => {
	        button.removeEventListener('change', this.onDropdownChange);
	      });
	    }
	  }
```

2019-01-31 13:46 UTC, C-Lodder commented on build/media/webcomponents/js/field-permissions/field-permissions.js
> +  }
oops, forgot about that. done

2019-01-31 16:34 UTC, brianteeman commented
Shouldnt these be done upstream in the webcomponents repo?

2019-01-31 16:59 UTC, C-Lodder commented
@brianteeman As far as I know there are 2 types of custom element. Those that are replacements for Bootstrap components and live in a standalone repo, and those that are part of Joomla core that live in this repo.

2019-01-31 17:16 UTC, brianteeman commented
Thanks for the clarification

2019-01-31 17:17 UTC, Anu1601CS commented
I have tested this item :white_check_mark: successfully on 20feb78d40b75711b9ac96dcce615e1c93e455fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23729">issues.joomla.org/tracker/joomla-cms/23729</a>.</sub>

2019-02-23 16:27 UTC, merged

2019-02-23 16:27 UTC, wilsonge commented
Thanks!