Add layouts to plg_user_terms
joomla/joomla-cms pull request #23787
Opened 2019-02-07 16:55 UTC by Ruud68

Pull Request for Issue # n/a.

### Summary of Changes
the layouts for plg_user_terms (label and termsnote) are hardcoded into the field and cannot be overwritten by a template override
This PR adds layouts for both the label and for the termsnote (message). these layouts can be overwritten via template overrides.

### Testing Instructions
1. enable the terms userm plugin
2. set a joomla article as terms article in the plugin
on the front-end user registration page the terms box should show

Apply this PR

[test] on the front-end user regsitration page the terms box should be exactly the same as without this PR.

3. create a template override via the template (e.g. protostar):
-> tab Create Overrides
-> column Layouts
-> select plugins > user

Edit the created override file: ./templates/protostar/html/layouts/plugins/user/terms/message.php
4. change the class from alert-info to alert-warning

[Result 1] refresh on the front-end the new user registration form

Edit the created override file: ./templates/protostar/html/layouts/plugins/user/terms/label.php
5. change ```<span class="star">&#160;*</span></label>``` to ```<span class="star">&copy;*</span></label>```

[Result 2] refresh on the front-end the new user registration form
 

### New result
![image](https://user-images.githubusercontent.com/2733197/52428045-789c9480-2b01-11e9-8504-bc26d78818c8.png)

### Actual result
Make sure that after applying the PR everything works as before.

### Documentation Changes Required

2019-02-07 17:00 UTC, dgrammatiko requested changes

2019-02-07 17:00 UTC, dgrammatiko commented on layouts/plugins/user/terms/label.php
> +	$attribs['rel']   = '{handler: \'iframe\', size: {x:800, y:500}}';
Can you please move this to use Bootstrap Modal instead of the Mootools?

2019-02-08 07:52 UTC, Ruud68 commented on layouts/plugins/user/terms/label.php
> +	$attribs['rel']   = '{handler: \'iframe\', size: {x:800, y:500}}';
no, my aim is to do one change a time. The aim of this PR is to add layout overrides for this plugin, just as I did for the plg_system_privacyconsent, not to change the logic.

2019-02-08 09:18 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on c56805fdfa046b1d89527aa50662aa0ed079da2a<br /><br />I have tested this item successfully on 3.9.2.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23787">issues.joomla.org/tracker/joomla-cms/23787</a>.</sub>

2019-02-08 09:20 UTC, Ruud68 commented
Thanks for testing @tecpromotion :) Appreciate it!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23787">issues.joomla.org/tracker/joomla-cms/23787</a>.</sub>

2019-02-08 09:45 UTC, SharkyKZ requested changes

2019-02-08 09:45 UTC, SharkyKZ commented on layouts/plugins/user/terms/label.php
> +	$db    = Factory::getDbo();
Database queries should remain in the field class.

2019-02-08 10:24 UTC, Ruud68 commented on layouts/plugins/user/terms/label.php
> +	$db    = Factory::getDbo();
done :)

2019-02-08 12:11 UTC, SharkyKZ commented on layouts/plugins/user/terms/label.php
> +	if (Associations::isEnabled())
Most of the code for generating the link would also be better left in the field class. Just need to have `$url` value in layout. Assign it to `$article->link` perhaps since article is being passed anyways?

2019-02-08 13:04 UTC, Ruud68 commented on layouts/plugins/user/terms/label.php
> +	if (Associations::isEnabled())
was already on it :)

2019-02-09 09:25 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 13a711488323e03ae0b9e9da5a39211c46dec7ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23787">issues.joomla.org/tracker/joomla-cms/23787</a>.</sub>

2019-02-09 09:37 UTC, Ruud68 commented
Thanks for testing @viocassel

2019-02-14 13:18 UTC, Ruud68 commented
@Quy  I see two successful tests, only one is counted? Do you know why and what is needed for this to go RTC?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23787">issues.joomla.org/tracker/joomla-cms/23787</a>.</sub>

2019-02-14 13:21 UTC, dgrammatiko commented on layouts/plugins/user/terms/label.php
> +	$attribs['rel']   = '{handler: \'iframe\', size: {x:800, y:500}}';
It's 2019, we shouldn't use Mootools.-

2019-02-14 13:24 UTC, Ruud68 commented on layouts/plugins/user/terms/label.php
> +	$attribs['rel']   = '{handler: \'iframe\', size: {x:800, y:500}}';
what is the code change needed for switching from mootools to bootstrap modal?

2019-02-14 13:27 UTC, mbabker commented on layouts/plugins/user/terms/label.php
> +	$attribs['rel']   = '{handler: \'iframe\', size: {x:800, y:500}}';
See https://github.com/joomla/joomla-cms/pull/22926 for an example.

Converting from MooTools to Bootstrap is a change for another PR.  Please do not include it here.

2019-02-14 14:19 UTC, Ruud68 commented on layouts/plugins/user/terms/label.php
> +	$attribs['rel']   = '{handler: \'iframe\', size: {x:800, y:500}}';
Thanks @mbabker and agree

2019-02-14 14:26 UTC, Bakual commented
When a new commit is made after a test, you need to retest it. The old tests don't count anymore.

2019-02-14 14:28 UTC, Ruud68 commented
@Bakual which is strange, because the one counted as successful is the one before the last change? anyway @viocassel  and @tecpromotion just to make sure, can you both (re) test #please :)

2019-02-14 14:57 UTC, Bakual commented
It shows the one from Vio as successful one. The first one from Stefan is discarded since you did two commits afterwards.
![image](https://user-images.githubusercontent.com/1018684/52794864-f1a36b00-3070-11e9-8e93-41e0b540031e.png)
So @tecpromotion or someone else has to test (again).

2019-02-18 21:19 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on 7ff2f05347800f73ae6aae8c1a80e1b229315225<br /><br />I have tested this item successfully on 3.9.3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23787">issues.joomla.org/tracker/joomla-cms/23787</a>.</sub>

2019-02-18 21:40 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 7ff2f05347800f73ae6aae8c1a80e1b229315225<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23787">issues.joomla.org/tracker/joomla-cms/23787</a>.</sub>

2019-02-19 09:38 UTC, merged

2019-02-19 09:38 UTC, HLeithner commented
thx