[4.0] contrast improved
joomla/joomla-cms pull request #23931
Opened 2019-02-18 09:35 UTC by puneeth2001

Pull Request for Issue # 23863

### Summary of Changes
Contrast has been improved for field labels

### Testing Instructions

### Expected result

### Actual result

### Documentation Changes Required

2019-02-18 10:51 UTC, C-Lodder requested changes

2019-02-18 10:51 UTC, C-Lodder commented on build/media_source/system/scss/fields/joomla-field-switcher.scss
> +      color: (--dark);
`var(--dark)`

2019-02-18 11:30 UTC, puneeth2001 commented on build/media_source/system/scss/fields/joomla-field-switcher.scss
> +      color: (--dark);
sorry for this silly mistake

2019-02-18 15:31 UTC, puneeth2001 commented
@C-Lodder please review this

2019-02-18 15:36 UTC, C-Lodder approved these changes

2019-03-06 03:14 UTC, puneeth2001 commented
@wilsonge can you please review this.

2019-03-06 03:15 UTC, puneeth2001 commented
sorry by closed by mistake.

2019-03-17 23:58 UTC, merged

2019-03-17 23:58 UTC, wilsonge commented
Thanks!