[4.0][a11y] 'Cancel' button changes from an anchor tag to a button tag
joomla/joomla-cms pull request #24007
Opened 2019-02-25 08:53 UTC by tarot-ray

For A11Y reasons, this should be a button tag, not a styled anchor tag.

Pull Request for Issue # .

### Summary of Changes

'Cancel' button is changed to a button tag from an anchor tag, to improved A11Y

### Testing Instructions

Check that the 'Cancel' button is seen correctly by a screenreader.

### Expected result

Improved A11Y.

### Actual result

### Documentation Changes Required

2019-02-25 09:22 UTC, SharkyKZ commented
This doesn't work. Button with `type="button"` needs some JS code to do anything. `href` is not a valid attribute for element `button`. If this really needs to be a button it should submit the form with cancel task.

2019-02-27 13:06 UTC, wilsonge commented on components/com_users/tmpl/profile/edit.php
> -				<a class="btn btn-danger" href="<?php echo Route::_('index.php?option=com_users&view=profile'); ?>" title="<?php echo Text::_('JCANCEL'); ?>"><?php echo Text::_('JCANCEL'); ?></a>
We still need the classes here

2019-02-27 13:07 UTC, wilsonge requested changes
As per the comments

2019-02-27 13:08 UTC, wilsonge commented
I have tested this item :red_circle: unsuccessfully on 9ce88b685e30ebab5e4fec15da83dc79fd8698ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24007">issues.joomla.org/tracker/joomla-cms/24007</a>.</sub>

2019-02-27 13:39 UTC, tarot-ray commented on components/com_users/tmpl/profile/edit.php
> -				<a class="btn btn-danger" href="<?php echo Route::_('index.php?option=com_users&view=profile'); ?>" title="<?php echo Text::_('JCANCEL'); ?>"><?php echo Text::_('JCANCEL'); ?></a>
Done.

2019-02-27 13:56 UTC, wilsonge commented
You still need to address the comments from @SharkyKZ

2019-02-27 14:29 UTC, wilsonge approved these changes

2019-02-27 14:29 UTC, wilsonge commented
I have tested this item :white_check_mark: successfully on 0b3c29fb929d0a6c184b01132ebcf2e4afdd5ade<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24007">issues.joomla.org/tracker/joomla-cms/24007</a>.</sub>

2019-02-27 14:30 UTC, wilsonge commented
@tarot-ray almost there - in the latest commit you've accidentally removed the classes again :)

2019-02-27 14:34 UTC, zwiastunsw commented
Add: `class="btn btn-danger"`

2019-02-27 14:47 UTC, tarot-ray commented
So, further changes have been made to the PR to make the line absolutely correct and perfectly A11Y compatible. Please, review.

2019-02-27 14:47 UTC, zwiastunsw commented
I have tested this item :white_check_mark: successfully on 74c891e5d33e05df813e26a45a894e697d8087fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24007">issues.joomla.org/tracker/joomla-cms/24007</a>.</sub>

2019-02-27 14:47 UTC, wilsonge commented
LGTM!

2019-02-27 14:47 UTC, wilsonge commented
I have tested this item :white_check_mark: successfully on 30dd62a410e3e7a070aa713aab417b592152c119<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24007">issues.joomla.org/tracker/joomla-cms/24007</a>.</sub>

2019-02-27 14:48 UTC, wilsonge commented
Just whitespace changes between the last two tests so RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24007">issues.joomla.org/tracker/joomla-cms/24007</a>.</sub>

2019-02-27 15:04 UTC, SharkyKZ commented
What exactly is the point of changing anchor to a button that does exactly the same but with JS dependency?

2019-02-27 15:21 UTC, wilsonge commented
@zwiastunsw Actually in this specific case thinking about it - I think a link was the correct choice because this is a redirect to another page. From http://web-accessibility.carnegiemuseums.org/content/buttons/ 

```
Navigation: If you want a user to navigate to a new page or to a different target on the same page, use an anchor element <a>.
```

2019-02-27 15:33 UTC, zwiastunsw commented
@SharkyKZ , @wilsonge :
It's a bit more complicated. In this case, Cancel will actually redirect to another page. But the essence of this control is  is to cancel the action and not to move it to another page.
In this and other similar cases, Cancel cancels actions you have performed. 
This is not just a tag problem. If you use tag a, make it look like a link and not like a button. Because it's confusing for keyboard users. I run the link with the Enter key, the button I run with the Enter or Space keys.

2019-03-04 20:57 UTC, SharkyKZ commented
See #24088 for potential alternative please.

2019-03-05 06:12 UTC, franz-wohlkoenig commented
@wilsonge can this PR be closed?

2019-03-21 13:00 UTC, wilsonge commented
I've merged https://github.com/joomla/joomla-cms/pull/24088 so closing this

2019-03-21 13:00 UTC, closed without merging