[4.0]added rss feed func
joomla/joomla-cms pull request #24028
Opened 2019-02-26 21:45 UTC by bahl24

Pull Request for Issue - Syndication Module in frontend not working .

### Testing Instructions
![screenshot from 2019-02-27 03-13-06](https://user-images.githubusercontent.com/36095178/53448518-98a6e000-3a3d-11e9-8fd3-17827466789a.png)
Click on any RSS button to get an error

### Expected result
![screenshot from 2019-02-27 03-14-42](https://user-images.githubusercontent.com/36095178/53448601-d146b980-3a3d-11e9-8dba-ac7521586a8d.png)
XML version

### Actual result
Error

2019-02-27 09:01 UTC, infograf768 commented
This is only broken for the featured view with error
`Call to undefined method Joomla\Component\Content\Site\View\Featured\FeedView::escape()`
Due to the fact that `escape()` is not present in `AbstractView` while it is present in `HtmView`.

I tested this OK and also if I replace the line by
`$title = htmlspecialchars($row->title, ENT_QUOTES, 'UTF-8');`

Note that feedview for a category (blog) is extending `HtmlView` where we do have `$title = $this->escape($item->$titleField);`

No idea for if the correct solution is to mimick `CategoryFeedView` for featured view or not.

2019-02-27 13:03 UTC, bahl24 commented
@infograf768 I have made the changes you suggested and

2019-02-27 13:15 UTC, alikon requested changes

2019-02-27 13:15 UTC, alikon commented on components/com_content/View/Featured/FeedView.php
> +			$title = $title = htmlspecialchars($row->title, ENT_QUOTES, 'UTF-8');
one `$title` is enough

2019-02-27 13:24 UTC, bahl24 commented on components/com_content/View/Featured/FeedView.php
> +			$title = $title = htmlspecialchars($row->title, ENT_QUOTES, 'UTF-8');
Yes there is no difference between the two, `$title = htmlspecialchars($row->title, ENT_QUOTES, 'UTF-8');` should stay or the other one?

2019-02-27 13:26 UTC, alikon commented on components/com_content/View/Featured/FeedView.php
> +			$title = $title = htmlspecialchars($row->title, ENT_QUOTES, 'UTF-8');
i mean
`$title = $title = htmlspecialchars($row->title, ENT_QUOTES, 'UTF-8'); `
should be
`$title = htmlspecialchars($row->title, ENT_QUOTES, 'UTF-8'); `

2019-02-27 13:27 UTC, bahl24 commented on components/com_content/View/Featured/FeedView.php
> +			$title = $title = htmlspecialchars($row->title, ENT_QUOTES, 'UTF-8');
oh, my mistake.

2019-02-27 20:48 UTC, bahl24 commented
@alikon Kindly test this

2019-03-01 09:27 UTC, bahl24 commented
@infograf768 Kindly test this

2019-03-01 17:20 UTC, infograf768 commented
Restarted drone

2019-03-01 18:42 UTC, bahl24 commented
@infograf768 I think there is some issue in 4.0 branch itself as build of many PR is failing.

2019-03-06 19:20 UTC, bahl24 commented
@infograf768 @alikon Restarted as drone is back on track,kindly test

2019-03-09 23:12 UTC, bahl24 commented
@infograf768 Kindly test this, I think the changes have been finalised

2019-03-10 07:51 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 41c00b83f128911091b34536dcaed61ea6e4e0b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24028">issues.joomla.org/tracker/joomla-cms/24028</a>.</sub>

2019-03-15 18:48 UTC, bahl24 commented
@Quy Kindly test

2019-03-28 06:32 UTC, bahl24 commented
@Quy @alikon  Kindly test

2019-08-09 05:50 UTC, SharkyKZ commented
I have tested this item :white_check_mark: successfully on 540dd2f8954c497404b9897bbffbb7e5533213b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24028">issues.joomla.org/tracker/joomla-cms/24028</a>.</sub>

2019-08-09 06:01 UTC, franz-wohlkoenig commented
@infograf768 can you please retest?

2019-08-10 13:48 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24028">issues.joomla.org/tracker/joomla-cms/24028</a>.</sub>

2019-08-18 23:30 UTC, merged

2019-08-18 23:31 UTC, wilsonge commented
Thanks!