[4.0] Show changelog - GSoC Expand Extensions Manager #17536 redo
joomla/joomla-cms pull request #24026
Opened 2019-02-26 19:49 UTC by roland-d

## Redo
This is a continuation of issue #17536 as I can no longer push to that repo, starting a new PR.

### Introduction

At this time, users have to look for external sources of information about changes in an extension, when they are going to update their extensions. In most cases, users install an extension without checking the changelog due to the difficulty to find the associated changelog. With this new feature, users can review the changelog of the extensions when they are about to install an update (granted that the changelog is provided by the extension's developer), and after the extension is installed.

### Summary of Changes

Added a new parameter on the xml updateserver files 'changelogurl' and adding it to #__updates table.

### Testing Instructions

I made some changes in the core databases so before testing you should fix your database:

![screenshot from 2017-07-24 21-36-09](https://user-images.githubusercontent.com/20955884/28543880-43171938-70b9-11e7-9248-e3eff8b422d4.png)

Extensions -> Database -> Fix
Extensions -> Updates -> Find Updates

 **Update View** 

Install my component: https://github.com/NunoLopes96/component_joomla 
By default you will have always an update from 0.0.2 to 4.0.0 just for testing

If the changelog is not available it will show N/A like in the Folder column

![screenshot from 2017-05-23 18-28-40](https://cloud.githubusercontent.com/assets/20955884/26367191/ade139c4-3fe5-11e7-822f-345a2ab7ef34.png)

It will open a modal with an iframe of the changelogurl in the body.
The title of the modal is version ' - ' component_name

![screenshot from 2017-05-17 19-54-50](https://cloud.githubusercontent.com/assets/20955884/26170842/ba92eece-3b3a-11e7-8014-98ad32222650.png)

**Manage View**

The changelogurl is supported for Components, Libraries, Modules, Plugins and Packages, you just need to add <changelogurl> tags in your instalation xml with a valid url inside.

To test this you can use these modified packages:

(To test Package, Component, Module, Plugin)
[pkg_weblinks_3.4.1-changelog.zip](https://github.com/joomla-projects/gsoc17_expand_extension_manager/files/1127690/pkg_weblinks_3.4.1-changelog.zip)
![screenshot from 2017-07-06 12-34-02](https://user-images.githubusercontent.com/20955884/27909224-99574708-6247-11e7-9dc3-6071b909fd31.png)

(To test Libraries)
[lib_fof30-3.1.0-changelog.zip](https://github.com/joomla-projects/gsoc17_expand_extension_manager/files/1127689/lib_fof30-3.1.0-changelog.zip)
![screenshot from 2017-07-06 12-34-49](https://user-images.githubusercontent.com/20955884/27909264-cac5ff96-6247-11e7-8c23-936779591e82.png)

(To test languages)
The language installer its diferent from the others so you may want to test 2 cases:
1-Install without having it already in your extensions
2-Install without changelogurl and then install again with a changelogurl

This happens because it has 1 function to install and another one to update ( they are similar )

[admin_pt-PT.zip](https://github.com/joomla-projects/gsoc17_expand_extension_manager/files/1128171/admin_pt-PT.zip)
Extension name: Português (pt-PT)

(To test templates)
[et_kidtoy_joomla_template_install_package_free.zip](https://github.com/joomla-projects/gsoc17_expand_extension_manager/files/1128256/et_kidtoy_joomla_template_install_package_free.zip)
Extension name: etkidtoy

(To test Files)
[cli2zoombie.zip](https://github.com/joomla-projects/gsoc17_expand_extension_manager/files/1130860/cli2zoombie.zip)
Extension name: Zoombie - CLI Application

### Expected result

In Updates View you will have a new column that will show a changelog button to open a modal if there is a changelogurl in the #__updates table.
In Manage View you will have an <a> tag in the version with a info icon on the right side if your extension has a changelogurl in the #__extensions table.

### Documentation Changes Required

Add changelogurl parameter on updatesite information and in extension

2019-02-26 20:55 UTC, mbabker commented
I still think this is best suited as an XML schema that is parsed into the modal instead of iframing an external page in (https://github.com/joomla/joomla-cms/pull/17536#issuecomment-322228872).

2019-02-26 20:57 UTC, roland-d commented
@mbabker Since I am not spending my time on this, I will move forward with the XML approach. Any guidelines of how the XML format should look like are welcome.

2019-02-26 21:08 UTC, mbabker commented
What you had in https://github.com/joomla/joomla-cms/pull/17536#issuecomment-401633079 looks OK to me.

2019-02-27 00:43 UTC, ciar4n commented
@roland-d I'm been hit with he following when attempting to find updates...

`Update: Could not open update site #4 "My Extension's Updates", URL: https://www.jah-tz.de/downloads/core/gsoc17/extension.xml`

2019-02-27 06:05 UTC, roland-d commented
@ciar4n Thank you for already checking it. I will prepare a new test setup, since this is also a few years old. I will do that after reworking the code to use the XML setup.

Yes, I am still looking for styling help, as I can barely float 2 divs :)

2019-03-04 20:34 UTC, roland-d commented
@ciar4n I have updated the PR and the majority of the work is done as far as I am concerned. Could you apply the needed styling on the file `layouts/joomla/installer/changelog.php` ? You can see the current layout in the opening post screenshots. Thank you.

2019-03-05 01:23 UTC, ciar4n commented
Sure. Give me a couple days and i will take a look!

2019-03-07 09:51 UTC, ciar4n commented
Updated styling...

![image](https://user-images.githubusercontent.com/2803503/53947873-8a506800-40be-11e9-901d-7197b4973a48.png)

2019-03-14 19:09 UTC, roland-d commented
@wilsonge Is there any desire to merge this or should it just be closed?

2019-03-14 21:45 UTC, wilsonge commented
There is desire! I'm trying to merge quite a lot of 3.9.0 over the next few nights as my girlfriend is out the country. please don't hesitate to ping me after the weekend is over to come back to this!

@mbabker if you could confirm the xml schema changes you were after had been made it would save me from doing so much code review

Also a testable component here would be ideal - appreciate providing a sample component is hard - but i'm really trying not introduce anymore broken features in the 4.0 branch. More than happy to be the one that actually does the testing however if no one steps up

2019-03-14 21:49 UTC, roland-d commented
@wilsonge A testable extension is provided, see step 5 of the test instructions.

Enjoy the alone time :)

2019-03-14 21:49 UTC, brianteeman commented
> The title of the modal is version ' - ' component_name

The modal must have a title - I would suggest Changelog - component_name

For the title it is better to present the component_name before the version number

2019-03-20 09:43 UTC, wilsonge commented
@roland-d i'm done with merge conflicts for a bit so coming back to this. Can you fix the conflict here and address the a11y point raised by brian and i'll try and get this tested :)

2019-03-21 20:34 UTC, roland-d commented
@wilsonge All updated and modal title changed as well. I have kept the version number though, I do think this is useful information. As such it now looks like this:

![image](https://user-images.githubusercontent.com/359377/54783226-19ae5d00-4c21-11e9-86cc-41cfc764ed35.png)

The title is a language string now, so it can be translated as people wish.

2019-03-21 21:08 UTC, ciar4n commented
@roland-d I created https://github.com/roland-d/joomla-cms/pull/13 which makes the modal responsive. Feel free to close if you believe it outside the scope of this PR.

2019-03-21 21:14 UTC, roland-d commented
@ciar4n I think it looks great. Thank you.

2019-03-22 11:28 UTC, wilsonge commented
Javascript code style issues to solve

2019-03-23 07:10 UTC, roland-d commented
@wilsonge Yay, all green :)

2019-03-23 07:56 UTC, alikon requested changes

2019-03-23 07:56 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2017-06-03.sql
> +ALTER TABLE "#__extensions" ADD COLUMN "changelogurl" text AFTER "element";
please remove 
```sql

AFTER "element" 
AFTER `infourl` 
```

2019-03-23 08:44 UTC, roland-d commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2017-06-03.sql
> +ALTER TABLE "#__extensions" ADD COLUMN "changelogurl" text AFTER "element";
Done.

2019-03-23 09:19 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 775e102474fd105761ccd2d96e545045c26407a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24026">issues.joomla.org/tracker/joomla-cms/24026</a>.</sub>

2019-03-25 11:28 UTC, merged

2019-03-25 11:29 UTC, wilsonge commented
There's a test and there's a merge :) Thanks @roland-d and @NunoLopes96 for all the hard work on this!

2019-03-26 16:57 UTC, Quy commented
@roland-d Please investigate issue #24360. Thanks.

`PHP Notice:  Undefined index: namespace in \libraries\src\Installer\Adapter\ComponentAdapter.php on line 1423`

2019-05-27 11:51 UTC, hgh-esn commented
@roland-d

I tested your nice extension, while working on updates to J4 for my plugin: stophitcounts.
In the plugin-manage-view I get the modal-window when clicking to the "changelog-version-item-link"
<img width="957" alt="2019-05-27_13h43_22" src="https://user-images.githubusercontent.com/5299726/58417593-8a408280-8085-11e9-93b9-ae2edd61b497.png">

In the extension-update-listview I get no "changelog-version-item-link". Instead of this, I see **N/A** or in German: **Unbekannt** 

<img width="650" alt="2019-05-27_13h49_31" src="https://user-images.githubusercontent.com/5299726/58417878-7b0e0480-8086-11e9-9c06-d867ef650f5a.png">

2019-05-27 17:09 UTC, wilsonge commented
Rolands written docs for this here https://docs.joomla.org/Adding_changelog_to_your_manifest_file so removing the docs required tag