[4.0] Multilingual status: adding more infos and clarifying some
joomla/joomla-cms pull request #24062
Opened 2019-03-02 17:52 UTC by infograf768

### Summary of Changes
This PR adds a Notice and displays the language concerned when the Content Language for that language has been deleted and remains in the site an orphan home page while the site language is published.
It also adds a Notice when a Content Language is in the trash.

It also reinstate all states of a content language to display the correct icons.
published = 1
publsihed = 0
published = -2 (i.e. trash) and for this one displays the trash icon

### Testing Instructions
Install a multilingual site with all languages available to install
French fr-FR
German de-DE
Persian fa-IR

Then use the Cpanel Multilingual Sample Data module to create a basic.

First test:
Display the Content languages Manager
Trash AND delete the fa-IR Persian content language.

You should get this when displaying the multilingual status module

<img width="1464" alt="screen shot 2019-03-02 at 18 25 09" src="https://user-images.githubusercontent.com/869724/53685264-a3e95c80-3d18-11e9-9722-8e0f1c2d1e62.png">

Then unpublish the French fr-FR Content Language.
And trash (do NOT delete) the German de-DE Content language.
I.e. Manager should look like this
<img width="671" alt="screen shot 2019-03-02 at 18 28 10" src="https://user-images.githubusercontent.com/869724/53685300-03476c80-3d19-11e9-84bc-7b05a02f92bc.png">

You should get this when displaying the multilingual status module
<img width="1486" alt="screen shot 2019-03-02 at 18 44 18" src="https://user-images.githubusercontent.com/869724/53685466-4e627f00-3d1b-11e9-9ac4-5bba6921afc8.png">

2019-03-02 18:37 UTC, Quy commented on administrator/components/com_languages/tmpl/multilangstatus/default.php
> +				<?php if ($status->lang_code && $status->published == 1) : ?>
Change it similar to lines 289 - 300 where all the if statements are inside one `<td class="text-center">` and `</td>`.

2019-03-03 07:16 UTC, infograf768 commented on administrator/components/com_languages/tmpl/multilangstatus/default.php
> +				<?php if ($status->lang_code && $status->published == 1) : ?>
Makes sense. Will do.
Just found out some issues I have to solve also. So this is still WIP.

2019-03-03 09:29 UTC, infograf768 commented
@Quy 
Modification done.
Added new Notice when both Content Language and Home page are unpublished.

We should now get in that case:

<img width="1286" alt="screen shot 2019-03-03 at 10 22 15" src="https://user-images.githubusercontent.com/869724/53693319-24eb3700-3d9f-11e9-9c3e-28000bfcd3e9.png">

can be fully tested now.

2019-03-04 06:34 UTC, Quy commented
This is not working for me. The `Published Default Home pages` has all checks even though all pages are unpublished.

`Added new Notice when both Content Language and Home page are unpublished.`

2019-03-04 06:35 UTC, Quy commented on administrator/components/com_languages/tmpl/multilangstatus/default.php
> +$notice_switchers       = !$this->switchers && ($this->homes > 1 || $this->language_filter);
Remove extra spaces before `=`.

2019-03-04 06:36 UTC, Quy commented on administrator/components/com_languages/tmpl/multilangstatus/default.php
> +			<?php if ($status->lang_code && $status->published == 0 && !$status->home_language) : ?>
Can this section be combined with the above loop?

2019-03-04 07:04 UTC, infograf768 commented on administrator/components/com_languages/tmpl/multilangstatus/default.php
> +$notice_switchers       = !$this->switchers && ($this->homes > 1 || $this->language_filter);
will do

2019-03-04 07:04 UTC, infograf768 commented on administrator/components/com_languages/tmpl/multilangstatus/default.php
> +			<?php if ($status->lang_code && $status->published == 0 && !$status->home_language) : ?>
I guess so. On it.

2019-03-04 07:06 UTC, infograf768 commented
>> Added new Notice when both Content Language and Home page are unpublished.

> The Published Default Home pages has all checks even though all pages are unpublished.

I do not understand this comment.

2019-03-04 07:12 UTC, Quy commented
I don’t get the same result in your last screenshot.

2019-03-04 07:16 UTC, infograf768 commented
> I don’t get the same result in your last screenshot.

Please explain with more details. 
The exact settings you have for each language and the resulting screenshot.

2019-03-04 07:17 UTC, Quy commented on administrator/components/com_languages/tmpl/multilangstatus/default.php
> +$notice_switchers       = !$this->switchers && ($this->homes > 1 || $this->language_filter);
Do the same for above.

2019-03-04 07:18 UTC, Quy commented
I am no longer at my computer so

2019-03-04 07:20 UTC, infograf768 commented on administrator/components/com_languages/tmpl/multilangstatus/default.php
> +$notice_switchers       = !$this->switchers && ($this->homes > 1 || $this->language_filter);
done

2019-03-04 07:35 UTC, infograf768 commented
I may have forgotten to ask testing by unpublishing the French Home page AND its content language, in order to get the Notice and the right icons.
The order of the Notices may also have  changed. One has to test multiple cases.

2019-03-04 07:42 UTC, infograf768 commented
We may need though another Notice when site language is enabled, content language is published and home page is unpublished.

I.e. this case for French and German
<img width="1368" alt="screen shot 2019-03-04 at 08 41 19" src="https://user-images.githubusercontent.com/869724/53717735-6213ff80-3e59-11e9-82a6-b89142a1c80a.png">


On it.

2019-03-04 11:40 UTC, infograf768 commented
Added notice when both content language and home page missing. added trash icon when home page is in the trash.

We now get in these cases:

<img width="1466" alt="screen shot 2019-03-04 at 12 40 18" src="https://user-images.githubusercontent.com/869724/53731340-be3b4b80-3e7a-11e9-996a-d914b053d918.png">

2019-03-04 11:57 UTC, infograf768 commented
Added warning icon when home page does not exist.
<img width="1505" alt="screen shot 2019-03-04 at 12 56 37" src="https://user-images.githubusercontent.com/869724/53732061-ffccf600-3e7c-11e9-9c11-af880e58f3b7.png">

2019-03-21 11:52 UTC, infograf768 commented
@alikon

2019-03-21 11:55 UTC, alikon requested changes

2019-03-21 11:55 UTC, alikon commented on administrator/components/com_languages/Helper/MultilangstatusHelper.php
> +			->join('LEFT', '#__menu AS l ON l.language = a.lang_code AND l.home=1 AND l.language <> \'*\'')
please use `quoteName()`

2019-03-21 12:00 UTC, infograf768 commented on administrator/components/com_languages/Helper/MultilangstatusHelper.php
> +			->join('LEFT', '#__menu AS l ON l.language = a.lang_code AND l.home=1 AND l.language <> \'*\'')
There are many places in this helper where we should use `quoteName()`
Shall we not reserve this for another specific patch ?

2019-03-21 12:02 UTC, infograf768 commented on administrator/components/com_languages/Helper/MultilangstatusHelper.php
> +			->join('LEFT', '#__menu AS l ON l.language = a.lang_code AND l.home=1 AND l.language <> \'*\'')
and also `db->quote()`

2019-11-27 21:37 UTC, Quy commented
Please fix conflicts.

2019-11-28 07:31 UTC, infograf768 commented
@Quy 
This needs a lot of work to solve the conflicts and also update the queries.
I may have to create a new PR
Will try when I have time.

2019-11-30 07:48 UTC, infograf768 commented
I am afraid this branch is dead. Please test this new PR
https://github.com/joomla/joomla-cms/pull/27184

Clocing

2019-11-30 07:48 UTC, closed without merging