[com_user] - case insesitive check for email address
joomla/joomla-cms pull request #24117
Opened 2019-03-07 18:22 UTC by alikon

Pull Request for Issue #24095 .

### Summary of Changes
use lower() to check user email

### Testing Instructions
see #24095

### Expected result
test@test.fr  and  Test@test.fr must be detected as the same email address even on db's like Postgresql

### Actual result
detected as the different  email address even on db's like Postgresql

### to do
change the email index

2019-03-08 09:45 UTC, mdaoudi123 commented
Thanks a lot for your help.

But There is also another file where exists a email comparaison:
- components/com_users/models/reset.php => function **processResetConfirm**
- components/com_users/models/remind.php => function **processRemindRequest**
- ...
and into other files..... (search for "**$db->quoteName('email')**")

Could you please add the correction to thoses files @alikon

2019-03-08 12:25 UTC, Quy commented on components/com_users/models/reset.php
> +		        ->where('LOWER(' . $db->quoteName('email') . ') = LOWER(' . $db->quote($data['email']) . ')');
```suggestion
			->where('LOWER(' . $db->quoteName('email') . ') = LOWER(' . $db->quote($data['email']) . ')');
```

2019-03-09 11:20 UTC, SharkyKZ commented on installation/model/configuration.php
> +				->set($db->quoteName('email') . ' = LOWER(' . $db->quote($options->admin_email) . ')')
IMO, this should be reverted. Shouldn't force emails to be stored as lowercase.

2019-03-09 11:20 UTC, SharkyKZ commented on installation/model/configuration.php
> +					'LOWER(' . $db->quote($options->admin_email) . '), ' . $db->quote($cryptpass) . ', ' .
Same as above.

2019-03-10 07:46 UTC, alikon commented on installation/model/configuration.php
> +				->set($db->quoteName('email') . ' = LOWER(' . $db->quote($options->admin_email) . ')')
make sense

2019-03-10 07:46 UTC, alikon commented on installation/model/configuration.php
> +					'LOWER(' . $db->quote($options->admin_email) . '), ' . $db->quote($cryptpass) . ', ' .
make sense

2019-03-22 13:05 UTC, mdaoudi123 commented
Can i download the new patch some where?

Thanks

2019-03-22 13:21 UTC, alikon commented
you can test with  https://docs.joomla.org/Component_Patchtester_for_Testers

2019-03-25 15:51 UTC, mdaoudi123 commented
Hello,
Thanks for the patchTester,
I tested the patch and it's OK.
Could you merge this branch and build a new patch?

2019-03-25 17:52 UTC, Quy commented on plugins/system/updatenotification/updatenotification.php
> +						$separator,
Reduce indentation.

2019-03-25 17:57 UTC, alikon commented on plugins/system/updatenotification/updatenotification.php
> +						$separator,
oops

2019-03-25 18:12 UTC, alikon commented
@mdaoudi123 please mark as tested on https://issues.joomla.org/tracker/joomla-cms/24117
this should be carefully tested on mysql side too....and mssql also i'm afraid

2019-03-26 07:20 UTC, mdaoudi123 commented
Hello, 
im going to test it into POSTGRES too, 
can you tell me how to mark this post as tested?
Thanks

2019-03-26 07:32 UTC, alikon commented
see https://docs.joomla.org/Testing_Joomla!_patches

2019-03-26 09:24 UTC, mdaoudi123 commented
I have tested this item :white_check_mark: successfully on a7c980e248f0d06bab1ee2262b06d03ad213817d<br /><br />Tested Successfully on Mysql and Postgres databases.

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24117">issues.joomla.org/tracker/joomla-cms/24117</a>.</sub>

2019-04-01 09:35 UTC, mdaoudi123 commented
Hello,
I have already tested this feature.
Could you please creat a new patch @alikon <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24117">issues.joomla.org/tracker/joomla-cms/24117</a>.</sub>

2019-04-01 09:48 UTC, alikon commented
one test is not enough, we need at least two, before this pr can be considered by the maintaners

2019-04-01 10:25 UTC, mdaoudi123 commented
There is an error into the continuous-integration/drone/p

The problem is the phpcs confirmation

@alikon

2019-04-30 08:53 UTC, mdaoudi123 commented
There is an error into the continuous-integration/drone/p

The problem is the phpcs confirmation

Could do you check whats happening please

@alikon

2019-05-01 09:00 UTC, alikon commented
sorry but really don't know how to fix CS for an inline function

2019-05-01 09:06 UTC, HLeithner commented
I just wanted to say that the local part of an email is case sensitive, it's ok for me to ignore this because it's common practice to handle email addresses case insensitive.

2019-06-19 08:23 UTC, mdaoudi123 commented
@HLeithner @alikon 
please there is news for this fix?
When this patch will be available?

Please Help

2019-06-19 08:24 UTC, mdaoudi123 commented
please could you fix the phpcsfixer warning

2019-06-19 08:25 UTC, mdaoudi123 commented
Any one can help me please

2019-06-19 08:28 UTC, franz-wohlkoenig commented
> one test is not enough, we need at least two, before this pr can be considered by the maintaners

@mdaoudi123

2019-06-19 08:32 UTC, mdaoudi123 commented
I tedted the fix. but who can test it another time to deblock the situation
Anyone can test please

2019-06-19 08:33 UTC, mdaoudi123 commented
Im waiting since 3 months

2019-06-19 08:56 UTC, infograf768 commented on plugins/system/updatenotification/updatenotification.php
> +	private function implode_callback($array, $separator = '', $callback = false)
Needs function comments

2019-06-19 08:57 UTC, mdaoudi123 commented on plugins/system/updatenotification/updatenotification.php
> +	private function implode_callback($array, $separator = '', $callback = false)
@alikon could you please add a comment for this function?
Thanks

2019-06-19 09:31 UTC, infograf768 commented on administrator/components/com_privacy/models/export.php
> +				->where('LOWER(' . $db->quoteName('email') . ') = LOWER(' . $db->quote($table->email) . ')'),
@alikon
Would that work?
```
			if (!empty($emails))
			{
				$lowerEmail =  function($x) {
					return "LOWER($x)";
				};

				$query->where('LOWER(' . $db->qn('email') . ') IN(' . $this->implode_callback($emails, ', ', $lowerEmail) . ')');
			}
```

2019-06-19 09:33 UTC, infograf768 commented on plugins/system/updatenotification/updatenotification.php
> +				$query->where('LOWER(' . $db->qn('email') . ') IN(' . $this->implode_callback($emails, ', ', function($x) { return "LOWER($x)"; } ) . ')');
@alikon 
would that work?
```
			if (!empty($emails))
			{
				$lowerEmail =  function($x) {
					return "LOWER($x)";
				};

				$query->where('LOWER(' . $db->qn('email') . ') IN(' . $this->implode_callback($emails, ', ', $lowerEmail) . ')');
			}
```

2019-07-20 08:14 UTC, franz-wohlkoenig commented
@richard67 you use Postgresql? Can you please look at this PR?

2019-07-20 09:41 UTC, richard67 commented
@franz-wohlkoenig Today I have a full schedule. I will try to find a time slot, but it might be tomorrow until I can do something. I do not really use postgresql, I just have it for testing.

2019-07-21 09:47 UTC, richard67 commented
@alikon @franz-wohlkoenig This PR will not work as it is. In the schema update, the index is dropped and then added back with same name. This is valid SQL, but the database schema checker can't handle that due to its bad design, so it will end in a toggle of reported database error "index missing but should exist" and "index existing but it should not". The only thing you can do is to add it back with other name, but the for consistency it might be necessary to change index name for MySQL, too.

2019-07-21 09:56 UTC, alikon commented
thanks @richard67 
btw,i don't think we need to do something  on mysql side

2019-07-21 10:00 UTC, richard67 requested changes

2019-07-21 10:00 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/3.9.5-2019-03-24.sql
> +DROP INDEX "#__users_email";
```suggestion
```
I suggest to leave the old index where it is and just add the new one.

2019-07-21 10:00 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
> -CREATE INDEX "#__users_email" ON "#__users" ("email");
I suggest not to delete this line, i.e. leave the old index where it is and just add the new one.

2019-07-21 10:00 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
> +CREATE UNIQUE INDEX "#__users_email" ON "#__users" ((lower("email")));
```suggestion
CREATE UNIQUE INDEX "#__users_email_lower" ON "#__users" ((lower("email")));
```

2019-07-21 10:00 UTC, richard67 commented on plugins/system/updatenotification/updatenotification.php
> +	private function implode_callback($array, $separator = '', $callback = false)
I agree with JM, it needs function comments.

2019-07-21 10:01 UTC, alikon commented on installation/sql/postgresql/joomla.sql
> -CREATE INDEX "#__users_email" ON "#__users" ("email");
Why ?

2019-07-21 10:02 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
> +CREATE UNIQUE INDEX "#__users_email" ON "#__users" ((lower("email")));
Index name in joomla.sql and schema update have to be consistent.

2019-07-21 10:03 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
> -CREATE INDEX "#__users_email" ON "#__users" ("email");
Because consistency with MySQL, because less impact/change on update, because it still might be useful when query with where without upper() ...
But that's not crucial, you also can delete it.

2019-07-21 10:05 UTC, richard67 commented
@alikon Did you test if update notification emails are still working with your change (which I don't fully understand and so I have same question as JM had).

2019-07-21 10:08 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
> -CREATE INDEX "#__users_email" ON "#__users" ("email");
Other question: Does it really need the new index? We also don't have it on MySQL, so it seems to work without.

2019-07-21 10:08 UTC, alikon commented on installation/sql/postgresql/joomla.sql
> -CREATE INDEX "#__users_email" ON "#__users" ("email");
I hope no one will  query that table/fleld without upper() else all this pr is wrong

2019-07-21 10:10 UTC, alikon commented on plugins/system/updatenotification/updatenotification.php
> +	private function implode_callback($array, $separator = '', $callback = false)
i'm not able to write comment , always got cs error.....

2019-07-21 10:27 UTC, richard67 commented on plugins/system/updatenotification/updatenotification.php
> +	private function implode_callback($array, $separator = '', $callback = false)
Maybe you missunderstand. I am working on a PR against your branch for CS and function comment, you will then have to complete the function comment.

2019-07-21 10:49 UTC, richard67 commented
@alikon I've made a PR adding the missing function comment which has to be completed by you, and which fixes a few of the code style issues. But I still do not understand why it needs that call back function stuff. Why don't you just make a local copy of the emails array, lowercase it, and use that for the query? It would not need this inline function and not need this new function and so no need for new function comments and all codestyle could be fine. Can you explain me why it needs to be done in that way with the callback?

2019-07-21 10:56 UTC, alikon commented
ouch i've to admit that i don't remember why i've done that, in that way maybe in that period i worked at the office "complicate simple thing"  :smile: .... hope i'll find free time to rethink soon

2019-07-21 10:57 UTC, richard67 commented
@alikon As long as you rethink that, ignore my PR against your branch of this PR. I think about it, too, and maybe come with new PR for your branch.

2019-07-21 11:05 UTC, richard67 commented
@alikon I see another problem with the new unique index on postgresql (and later in 4.0-dev where we have MySQL >= 5.7 on MySQL, too, if we add the same index then):

When users do an update of their Joomla and have duplicate lowercase emails in their users table database, like "gaga@blabla.de" and "GaGa@blabla.de", the unique index adding will fail.

It would require to clean existing data by duplicate records. We once had the same problem when we wanted to change collations of com_finder tables in MySQL from general to unicode, because that change would have caused duplicate values, and so we gave that up and remained com_finder tables with general collations.

If you want to keep that new index for performance reasons, then make it non-unique, i.e. just an index.

Or you don't add that new index.

Of course this would not be a problem if we could be sure that the PHP code of the CMS never allowed to add users having same lowercase email address. But I am pretty sure even if that was the case, we could not 100% rely on it over all the history of Joomla version in the update history of a web site.

So I suggest to make the new index non-unique or leave it away.

2019-07-21 11:07 UTC, richard67 commented
@alikon P.S. to my previous post: I think @mdaoudi123 did not have that problem during his test because either he did not have duplicate records, or he did not run the schema update sql (which patchtester will also not do) and so he tested only the changes in PHP but not the database change.

2019-07-21 11:50 UTC, richard67 commented
@alikon My PR [https://github.com/alikon/joomla-cms/pull/55](https://github.com/alikon/joomla-cms/pull/55) replaces the callback stuff by easier solution and so fixes all cs issues. What remains to be thought about is not to add the new index as unique because it may break update of sites with existing duplicate lowercase email addresses in their data.

2019-07-21 12:27 UTC, richard67 commented
@alikon My PR [https://github.com/alikon/joomla-cms/pull/56](https://github.com/alikon/joomla-cms/pull/56) handles the index problems and renames the schema update according to latest releases.

So if you accept my 2 PRs and update yours here with latest staging we can test yours.

2019-07-21 14:24 UTC, alikon commented
thanks @richard67

2019-07-21 14:35 UTC, richard67 commented
Drone failure is not related to this PR, is javascript stuff. PHPCS is ok now.

2019-07-21 14:37 UTC, richard67 commented
@mdaoudi123 Sorry for the inconvenience and the long waiting time. Could you test this PR again with its latest changes?

2019-07-21 14:59 UTC, richard67 commented
@alikon Could you synch this PR with staging by using that button in GitHub at the bottom of your PR?

2019-07-21 15:07 UTC, brianteeman commented
Unless there are conflicts there is no benefit

2019-07-21 15:08 UTC, richard67 commented
Yes but looks less scary for beginner testers.

2019-07-21 15:46 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on a8c025be41688fa5a5c1d7463bda7ec0f2c59681<br /><br />Tested on MySQL and PostgreSQL.

On MySQL it does not break anything.

On PostgreSQL it checks now for present email address in case-insensitive way without touching existing user data.

Tested as follows:

1. Without this PR applied, have super admin email address be like e.g. "test@test.local".
2. Create another user with email address be like e.g. "Test@test.local", i.e. same as 1st one but different case.
Result: User is created.
3. Apply this PR.
4. Go to "Extensions -> Manage -> Database" and fix the database error to apply the schema update sql of this PR.
Result: Database upt to date.
5. Create another user with email address be like e.g. "tEst@test.local", i.e. same as 1st and 2nd one but different case.
Result: User is not created because email address already exists.
6. Edit the 2nd user but do not change email address and try to save.
Result: User can't be saved because email address already exists.
7. Exit user edit without saving.
8. Work a bit in backend with user-related functions like privacy requests or other stuff related to files changed by this PR.
Result: You can't add new users or change users so more than one user has same email address, case-independent, but the existing 2 users with same case-independent email addresses do not make problems.

@alikon Could you update your testing instructions to what I wrote here above so other users can test more easily?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24117">issues.joomla.org/tracker/joomla-cms/24117</a>.</sub>

2019-08-03 10:14 UTC, richard67 commented
@alikon why closing this?

2019-08-03 17:39 UTC, richard67 commented
@alikon Did you maybe accidently hit the wrong button, close instead of rebase?

2019-08-04 10:46 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 27d35198f7939e5d2c39bfd41251d2cfe3e98501<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24117">issues.joomla.org/tracker/joomla-cms/24117</a>.</sub>

2019-08-04 10:48 UTC, richard67 commented
@mdaoudi123 Sorry for the inconvenience.

Could you test this PR again with its latest changes?

And then mark your test result at the issue tracker here [https://issues.joomla.org/tracker/joomla-cms/24117](https://issues.joomla.org/tracker/joomla-cms/24117), using the "Test this" button at the top left corner? Then just select the appropriate result and submitt.

2020-01-07 02:00 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 27d35198f7939e5d2c39bfd41251d2cfe3e98501<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24117">issues.joomla.org/tracker/joomla-cms/24117</a>.</sub>

2020-01-07 07:50 UTC, SharkyKZ commented
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24117">issues.joomla.org/tracker/joomla-cms/24117</a>.</sub>

2020-01-07 09:15 UTC, mdaoudi123 commented
Thank's a lot.

2020-01-07 09:16 UTC, mdaoudi123 commented
This correction will be available into the new joomla release?.

regards

2020-01-07 09:32 UTC, alikon commented
it's up to the maintainers/release lead to decide if and when

2020-01-08 12:48 UTC, HLeithner commented
Can you please rename the sql file to 3.9.15 then I will merge this.

2020-01-08 13:00 UTC, alikon commented
renamed

2020-01-08 13:13 UTC, merged

2020-01-08 13:13 UTC, HLeithner commented
I'm not the biggest fan this PR but think it solves more problems then it creates.

Thanks