Added patch for connecting to AD-server with self-signed certificates.
joomla/joomla-cms pull request #24115
Opened 2019-03-07 16:13 UTC by rickyosser

Pull Request for Issue # .

### Summary of Changes
Added patches for connecting to AD-server with self-signed certificates.

### Testing Instructions
Just install and enable the Ignore Certificate option.

### Expected result
Working authentication using TLS/LDAPS with servers that are configured with self-signed certificates. For example recent SAMBA4.

### Actual result
Working authentication using TLS/LDAPS with servers that are configured with self-signed certificates. For example recent SAMBA4.

### Documentation Changes Required
Option:
"Ignore Certificate"
Desc:
When enabled ignore the server certificate, this is useful when running for example Samba 4 with a self-signed certificate.

2019-03-07 18:37 UTC, Quy commented on libraries/vendor/joomla/ldap/src/LdapClient.php
> +
Remove tabs.

2019-03-07 23:52 UTC, rickyosser commented on libraries/vendor/joomla/ldap/src/LdapClient.php
> +
I removed the spaces.
Hmm, emacs acting up. php-mode seems to default to PEAR-style. Which uses spaces.

2019-03-08 07:23 UTC, HLeithner requested changes
Please change the language keys to match the field name, atm the key says the opposite then the description.

2019-03-08 07:23 UTC, HLeithner commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_REQCERT_DESC="When enabled ignore the server certificate, this is useful when running for example Samba 4 with a self-signed certificate."
```suggestion
PLG_LDAP_FIELD_IGNORE_REQCERT_TLS_DESC="When enabled ignore the server certificate, this is useful when running for example Samba 4 with a self-signed certificate."
```

2019-03-08 07:23 UTC, HLeithner commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_REQCERT_LABEL="Ignore Certificate"
```suggestion
PLG_LDAP_FIELD_IGNORE_REQCERT_TLS_LABEL="Ignore Certificate"
```

2019-03-08 07:23 UTC, HLeithner commented on plugins/authentication/ldap/ldap.xml
> +					label="PLG_LDAP_FIELD_REQCERT_LABEL"
```suggestion
					label="PLG_LDAP_FIELD_IGNORE_REQCERT_TLS_LABEL"
```

2019-03-08 07:23 UTC, HLeithner commented on plugins/authentication/ldap/ldap.xml
> +					description="PLG_LDAP_FIELD_REQCERT_DESC"
```suggestion
					description="PLG_LDAP_FIELD_IGNORE_REQCERT_TLS_DESC"
```

2019-03-08 09:38 UTC, rickyosser commented on plugins/authentication/ldap/ldap.xml
> +					description="PLG_LDAP_FIELD_REQCERT_DESC"
Hi!

This is fixed.

2019-03-08 09:38 UTC, rickyosser commented on plugins/authentication/ldap/ldap.xml
> +					label="PLG_LDAP_FIELD_REQCERT_LABEL"
This is fixed.

2019-03-08 09:38 UTC, rickyosser commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_REQCERT_LABEL="Ignore Certificate"
Fixed!

2019-03-08 09:39 UTC, rickyosser commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_REQCERT_DESC="When enabled ignore the server certificate, this is useful when running for example Samba 4 with a self-signed certificate."
Fixed!

2019-03-08 09:50 UTC, HLeithner approved these changes

2019-03-08 09:50 UTC, HLeithner commented
Now we need 2 testers...

2019-03-08 10:18 UTC, brianteeman commented
@HLeithner it is very unlikely that we will get 2 testers for this as it is very specialised and not used often. I suspect the only option is to code review

2019-03-08 10:21 UTC, HLeithner commented
Yeah I have the same feeling

2019-03-08 10:22 UTC, HLeithner commented
Would you at least test if the plugin screen doesn't break?

2019-03-08 10:27 UTC, brianteeman commented
Tested and the screen doesnt break. Not sure if debug should be the very first option. But I have never used LDAP authentication so dont know if it is important or not

2019-03-08 10:37 UTC, HLeithner commented
It's the first? request for this feature ;-) so properly the first position is not perfect....

I would suggest moving debug to the last option and the tls thing before debug.

2019-03-08 12:29 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_LDAPDEBUG_DESC="Enables debug hardcoded to level 7"
Please sort keys in alpha order.

2019-03-08 12:31 UTC, Quy commented on libraries/vendor/joomla/ldap/src/LdapClient.php
> +         * @since  1.0
```suggestion
         * @since  __DEPLOY_VERSION__
```

2019-03-08 12:31 UTC, Quy commented on libraries/vendor/joomla/ldap/src/LdapClient.php
> +         * @since  1.0
```suggestion
         * @since  __DEPLOY_VERSION__
```

2019-03-08 13:32 UTC, mbabker commented
A Composer dependency is changed without having updated the lock file.  That should be a red flag to somebody...

2019-03-08 13:47 UTC, HLeithner commented
So good that you are here^^

@rickyosser parts of the PR have to be made against https://github.com/joomla-framework/ldap/blob/master/src/LdapClient.php

2019-03-09 23:40 UTC, rickyosser commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_LDAPDEBUG_DESC="Enables debug hardcoded to level 7"
> It's the first? request for this feature ;-) so properly the first position is not perfect....
> 
> I would suggest moving debug to the last option and the tls thing before debug.

I moved the debug option to last but the Ignore certificate is closely connected to enabling TLS and thus should be the next option.

2019-03-09 23:40 UTC, rickyosser commented on libraries/vendor/joomla/ldap/src/LdapClient.php
> +         * @since  1.0
Fixed

2019-03-09 23:41 UTC, rickyosser commented on libraries/vendor/joomla/ldap/src/LdapClient.php
> +         * @since  1.0
Fixed

2019-03-09 23:43 UTC, rickyosser commented
> A Composer dependency is changed without having updated the lock file. That should be a red flag to somebody...

Can you please point to where the composer dependency would change, I'm looking at the diff-file I originally created and it closeley looks like the git PR I'm trying to create. It only touches 3 files and none of them is a Composer control-file.

2019-03-09 23:54 UTC, brianteeman commented
It is this file  libraries/vendor/joomla/ldap/src/LdapClient.php
which should be made against  https://github.com/joomla-framework/ldap/blob/master/src/LdapClient.php

2019-03-10 00:06 UTC, rickyosser commented
> So good that you are here^^
> 
> @rickyosser parts of the PR have to be made against https://github.com/joomla-framework/ldap/blob/master/src/LdapClient.php

#brianteeman and #HLeithner, I've created a pull request in the LDAP tree for the changes in that file.

2019-03-10 19:52 UTC, rickyosser commented
My PR [](https://github.com/joomla-framework/ldap/commit/c7e30cea0859d977ec2e098ec3cf1c1347539eec) has been accepted in joomla-framework/ldap, what do you need me to do here now?

2019-03-10 20:17 UTC, HLeithner commented
Remove the changes in the ldapclient file, I will update the lib after release 3.9.4.

2019-03-10 21:51 UTC, rickyosser commented
> Remove the changes in the ldapclient file, I will update the lib after releasing 3.9.4.

@HLeithner, the file is now reverted.

2019-03-10 22:09 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_LDAPDEBUG_DESC="Enables debug hardcoded to level 7"
It should still be sorted in alpha order.

2019-03-10 22:36 UTC, rickyosser commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_LDAPDEBUG_DESC="Enables debug hardcoded to level 7"
Check the file after last nights commit 224ec418abeb9637c2352547b1fb22f312ba8d2d, the file is in order.

2019-04-11 14:18 UTC, Quy commented on administrator/language/en-GB/en-GB.plg_authentication_ldap.ini
> +PLG_LDAP_FIELD_IGNORE_REQCERT_TLS_DESC="When enabled ignore the server certificate, this is useful when running for example Samba 4 with a self-signed certificate."
Move lines 15-16 after line 18.

2019-04-23 17:00 UTC, merged

2019-04-23 17:00 UTC, HLeithner commented
thx