Add basic contact api
joomla/joomla-cms pull request #24134
Opened 2019-03-08 22:54 UTC by wilsonge

Add a basic API plugin and related classes for com_contact. This is an example of what integration with the API is going to be like for 3rd party components too

2019-03-08 23:30 UTC, brianteeman requested changes
just reviewing mainly copy paste errors

less haste more speed ;)

2019-03-08 23:30 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-05.sql
> +(496, 0, 'plg_webservices_contact', 'plugin', 'contact', 'webservices', 0, 1, 1, 0, '', '{}', 0, '0000-00-00 00:00:00', 0, 0),
1970 on pgsql

2019-03-08 23:30 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_webservices_contact.ini
> +PLG_WEBSERVICES_CATEGORIES="Web Services - Contacts"
CATEGORIES ???

2019-03-08 23:30 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_webservices_contact.sys.ini
> +PLG_WEBSERVICES_CATEGORIES="Web Services - Contacts"
CATEGORIES??

2019-03-08 23:30 UTC, brianteeman commented on api/components/com_contact/Controller/ContactsController.php
> + * @subpackage  com_content
shouldnt that be com_contact

2019-03-08 23:30 UTC, brianteeman commented on api/components/com_contact/View/Contacts/JsonapiView.php
> + * @subpackage  com_content
contact?

2019-03-08 23:30 UTC, brianteeman commented on api/components/com_contact/Controller/ContactsController.php
> + * The category controller
contacts

2019-03-08 23:30 UTC, brianteeman commented on api/components/com_contact/View/Contacts/JsonapiView.php
> + * The article controller
contacts

2019-03-08 23:30 UTC, brianteeman commented on installation/sql/postgresql/joomla.sql
> +(496, 0, 'plg_webservices_contact', 'plugin', 'contact', 'webservices', 0, 1, 1, 0, '', '{}', 0, '0000-00-00 00:00:00', 0, 0),
1970

2019-03-08 23:30 UTC, brianteeman commented on plugins/webservices/contact/contact.php
> + * @subpackage  Webservices.Content
contact

2019-03-08 23:30 UTC, brianteeman commented on plugins/webservices/contact/contact.php
> + * Web Services adapter for com_categories.
com_categorues?

2019-03-08 23:30 UTC, brianteeman commented on plugins/webservices/contact/contact.php
> +	 * Registers com_categories's API's routes in the application
com_categories?

2019-03-08 23:30 UTC, brianteeman commented on plugins/webservices/contact/contact.xml
> +	<creationDate>August 2017</creationDate>
are we going back in time

2019-03-09 13:30 UTC, wilsonge commented
Whoops - thanks. I initially wrote a categories implementation then changed my mind as it’s more complicated (should it be child endpoints of categories etc.). So swapped to contacts. Apparently badly :)

2019-03-09 14:13 UTC, brianteeman commented
Confirming that the changes I requested have all been made.

However I dont have the skillset to test the actual code :(

2019-03-09 17:40 UTC, astridx commented
Could it be that we have to change lines 23 and 24 in the file 
`libraries/src/Router/ApiRouter.php `
to 
```
use Joomla\CMS\Router\Router;
use Joomla\CMS\Router\Route;
```
(we have to add the `CMS`)
https://github.com/joomla/joomla-cms/blob/3084b818100d3972f76eba6d2d68fb99f890c075/libraries/src/Router/ApiRouter.php#L15

2019-03-10 15:57 UTC, mbabker commented
@astridx see https://github.com/joomla/joomla-cms/pull/24135 - TL;DR, it's right as is

2019-03-24 11:17 UTC, alikon commented
- `curl -X GET -H 'Authorization: Basic YWRtaW46YWRtaW4=' -i 'http://localhost/quattro/api/index.php/v1/contact'`
-  ok
- `curl -X GET -H 'Authorization: Basic YWRtaW46YWRtaW4=' -i 'http://localhost/quattro/api/index.php/v1/contact/1'`
- ok

- `curl -X DELETE -H 'Authorization: Basic YWRtaW46YWRtaW4=' -i 'http://localhost/quattro/api/index.php/v1/contacts/1'`
-  KO  `{"errors":[{"code":500,"title":"Internal server error"}]}`

2019-07-29 12:53 UTC, wilsonge commented
Closing as this has been integrated into the GSOC webservices project

2019-07-29 12:53 UTC, closed without merging