[4.0] [a11y] Add SkipTo Navigation plugin
joomla/joomla-cms pull request #24142
Opened 2019-03-09 20:11 UTC by brianteeman

Integration of the great accessibility plugin by PayPal Accessibility Team and University of Illinois

SkipTo is a replacement for your old classic "Skipnav" link, (so please use it as such)! The SkipTo script creates a drop-down menu consisting of the links to the important places on a given web page. Once installed and configured, the menu makes it easier for keyboard and screen reader users to quickly jump to the desired location by simply choosing it from the list of options.

### How it works
The SkipTo menu becomes visible the first time the user tabs into the page.
Once the keyboard focus is on the menu, pressing the ENTER or the SPACEBAR key will pull down the list of high-level headings and landmarks on the current page.
Use arrow keys to select your choice and press ENTER to skip to it.
If you decide to reach the menu again, simply press the built-in access key (0 by default).

### Joomla options
Obviously added the ability for the strings to be translated
In the plugin you have the option to enable this navigation aid on Site/Administrator/Both - The default is admin

### SkipTo options
By default, SkipTo menu will include the following places on the page:

Heading (e.g h1, h2, h3 and h4 elements).
ARIA landmarks (e.g. banner, navigation, main and search).
HTML5 Section Elements (e.g. main, section[aria-label], section[aria-labelledby]
The “access key” is set to 0.
The menu is set not to wrap.
The menu is visible on keyboard focus only

The above are configurable but I have not exposed the configuration to Joomla - but can do. I just think the complicate things and the defaults are fine

#### Testing
Testing will require a full npm install

![skipto](https://user-images.githubusercontent.com/1296369/54076806-6d2abd80-42a7-11e9-98af-f291b52562f9.gif)

Thanks to @wilsonge for getting me over the final hurdles

2019-03-09 20:21 UTC, Quy commented on installation/sql/mysql/joomla.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto',	'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, '0000-00-00 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, '0000-00-00 00:00:00', 0, 0),
```

2019-03-09 20:21 UTC, Quy commented on installation/sql/postgresql/joomla.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto',	'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, 'q970-01-01 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, 'q970-01-01 00:00:00', 0, 0),
```

2019-03-09 20:22 UTC, Quy commented on installation/sql/mysql/joomla.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto',	'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, '0000-00-00 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}', 0, '0000-00-00 00:00:00', 0, 0),
```

2019-03-09 20:22 UTC, Quy commented on installation/sql/postgresql/joomla.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto',	'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, 'q970-01-01 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}', 0, 'q970-01-01 00:00:00', 0, 0),
```

2019-03-09 20:22 UTC, Quy commented on installation/sql/postgresql/joomla.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto',	'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, 'q970-01-01 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}', 0, '1970-01-01 00:00:00', 0, 0),
```

2019-03-09 20:23 UTC, Quy commented on plugins/system/skipto/skipto.php
> +		if (!($current_section & $section))
```suggestion
		if (!($current_section && $section))
```

2019-03-09 20:23 UTC, Quy commented on plugins/system/skipto/skipto.php
> +							'menuLabel'			=> Text::_('PLG_SYSTEM_SKIPTO_SKIP_TO_AND_PAGE_OUTLINE'),
```suggestion
							'menuLabel'		=> Text::_('PLG_SYSTEM_SKIPTO_SKIP_TO_AND_PAGE_OUTLINE'),
```

2019-03-09 20:25 UTC, brianteeman commented on plugins/system/skipto/skipto.php
> +		if (!($current_section & $section))
This code is a direct copy paste from the yubikey plugin

2019-03-09 20:26 UTC, brianteeman commented on plugins/system/skipto/skipto.php
> +							'menuLabel'			=> Text::_('PLG_SYSTEM_SKIPTO_SKIP_TO_AND_PAGE_OUTLINE'),
grrh this one is perfect in my ide

2019-03-09 20:34 UTC, SharkyKZ commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-09.sql
> +INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out
Missing `package_id` column after `extension_id`. `custom_data` and `system_data` columns do not exist.

2019-03-09 20:35 UTC, SharkyKZ commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
> +INSERT INTO "#__extensions" ("extension_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "manifest_cache", "params", "custom_data", "system_data", "checked_out
Same as above.

2019-03-09 20:38 UTC, SharkyKZ commented on installation/sql/postgresql/joomla.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, 'q970-01-01 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, '1970-01-01 00:00:00', 0, 0),
```

2019-03-09 20:45 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-09.sql
> +INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out
This is a direct copy of https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-01-05.sql

2019-03-09 20:45 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
> +INSERT INTO "#__extensions" ("extension_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "manifest_cache", "params", "custom_data", "system_data", "checked_out
This is a direct copy of https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-01-05.sql

2019-03-09 20:51 UTC, SharkyKZ commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
> +INSERT INTO "#__extensions" ("extension_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "manifest_cache", "params", "custom_data", "system_data", "checked_out
This needs fixing too.

2019-03-09 21:13 UTC, SharkyKZ commented
@brianteeman see https://github.com/brianteeman/joomla-cms/pull/78 for SQL fixes.

2019-03-09 22:35 UTC, Quy commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
> +INSERT INTO "#__extensions" ("extension_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "manifest_cache", "params", "custom_data", "system_data", "checked_out
There are 2 `INSERT INTO`.

2019-03-10 12:40 UTC, astridx commented
Thank you for this plugin. I just tested it. I noticed the following:

1. After discovering I saw two new plugins. I ignored `API Authentication - Basic Auth`. I installed `System - Skip-To Navigation`.
![Extensions  Discover   Test   Administration(1)](https://user-images.githubusercontent.com/9974686/54085021-18d01e00-4339-11e9-8e7e-7fec2c66df96.png)
2. After click on one entry in the `SkipTo menu `, I get this error.
![Bildschirmfoto von 2019-03-10 13-35-51](https://user-images.githubusercontent.com/9974686/54085059-89773a80-4339-11e9-8e91-a360dd2db03a.png)
3. I do not understand, which links are included in the `SkipTo menu `. Here I find, that `h4` should be included. But `Most read Posts `are not included in the next picture.
![Home(2)](https://user-images.githubusercontent.com/9974686/54085106-00143800-433a-11e9-9426-907eedd94e13.png)

2019-03-10 13:05 UTC, brianteeman commented
Sorry my original post is incorrect - the default settings are h1, h2, h3
We can add h4 if we want to

2019-03-10 13:40 UTC, SharkyKZ requested changes
SQL please.

2019-03-10 13:40 UTC, SharkyKZ commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-09.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, '0000-00-00 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{}',  0, '0000-00-00 00:00:00', 0, 0),
```

2019-03-10 13:40 UTC, SharkyKZ commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
> +INSERT INTO "#__extensions" ("extension_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "manifest_cache", "params", "custom_data", "system_data", "checked_out
```suggestion
INSERT INTO "#__extensions" ("extension_id", "package_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "manifest_cache", "params", "checked_out", "checked_out_time", "ordering", "state") VALUES
```

2019-03-10 13:40 UTC, SharkyKZ commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, '1970-01-01 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{}',  0, '1970-01-01 00:00:00', 0, 0),
```

2019-03-10 13:40 UTC, SharkyKZ commented on installation/sql/mysql/joomla.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, '0000-00-00 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{}',  0, '0000-00-00 00:00:00', 0, 0),
```

2019-03-10 13:40 UTC, SharkyKZ commented on installation/sql/postgresql/joomla.sql
> +(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{"section_skipto":"2"}',  0, '1970-01-01 00:00:00', 0, 0),
```suggestion
(496, 0, 'plg_system_skipto', 'plugin', 'skipto', 'system', 0, 1, 1, 0, '', '{}',  0, '1970-01-01 00:00:00', 0, 0),
```

2019-03-10 13:50 UTC, brianteeman commented
@SharkyKZ Why. I thought we were supposed to set the default values in the sql

2019-03-10 13:56 UTC, SharkyKZ commented
Based on https://github.com/joomla/joomla-cms/issues/20563#issuecomment-395749662, no. As long as you set them in the plugin code.

2019-03-11 13:33 UTC, SharkyKZ requested changes
SQL still not fixed.

2019-03-11 13:33 UTC, SharkyKZ commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
> +INSERT INTO "#__extensions" ("extension_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "manifest_cache", "params", "custom_data", "system_data", "checked_out
```suggestion
INSERT INTO "#__extensions" ("extension_id", "package_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "manifest_cache", "params", "checked_out", "checked_out_time", "ordering", "state") VALUES
```

2019-03-11 13:54 UTC, brianteeman commented
Thanks @SharkyKZ should be fixed now

2019-03-11 13:57 UTC, SharkyKZ commented
Thanks, now the review starts 😁.

2019-03-11 13:58 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +	protected $autoloadLanguage = true;
Remove this since language is loaded conditionally on line 80.

2019-03-11 13:58 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +			return false;
```suggestion
			return;
```

2019-03-11 13:59 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +		{
Remove brackets here and on line 104.

2019-03-11 14:00 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +		Factory::getDocument()->addScriptOptions(
```suggestion
		$document->addScriptOptions(
```

2019-03-11 14:03 UTC, SharkyKZ requested changes
Use injected application.

2019-03-11 14:03 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +		$document = Factory::getDocument();
```suggestion
		$document = $this->app->getDocument();
```

2019-03-11 14:03 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +			$app = Factory::getApplication();
Remove this. Use `$this->app`.

2019-03-11 14:03 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +			if ($app->isClient('administrator'))
```suggestion
			if ($this->app->isClient('administrator'))
```

2019-03-11 14:03 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +			elseif ($app->isClient('site'))
```suggestion
			elseif ($this->app->isClient('site'))
```

2019-03-11 14:03 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +use Joomla\CMS\Factory;
Remove this. It's not needed once other changes are implemented.

2019-03-11 14:15 UTC, brianteeman commented
@SharkyKZ the code in skipto.php to select site or admin etc is a direct copy of the code in the tfa plugin so I am not going to change it in this pr.

2019-03-11 16:11 UTC, SharkyKZ commented
Just asking that you fix copypasta errors. Can't return `false` here because `onBeforeCompileHead()` has `void` return type. This is a PHPCS error (Drone is sleeping). Application object is available as class property (but not in TFA plugins) so no need to fetch it the second time.

2019-03-12 01:05 UTC, zwiastunsw commented
1. SkipTo menu is the navigation area. Use the `nav` tag to mark it as a landmark.
2. The attribute: `role="complementary"` is not correct. Use the `navigation` role.    
3. On the front page the skipTo menu appears below the banner landmark:
![skipto](https://user-images.githubusercontent.com/29527200/54167276-49af7080-4469-11e9-84ae-a910a5fd751f.png)
In the source code is located directly behind the body tag, so correctly. I think this is a template issue.

2019-03-12 01:31 UTC, brianteeman commented
1,2,3 come directly from the script by the experts at PayPal Accessibility Team and University of Illinois

4 is a template issue and nothing to do with the plugin

2019-03-12 01:35 UTC, zwiastunsw commented
> 1,2,3 come directly from the script by the experts at PayPal Accessibility Team and University of Illinois

Does this mean that these elements cannot be improved?

2019-03-12 01:57 UTC, brianteeman commented
If you disagree with them then submit an issue to their GitHub repository

2019-03-12 02:14 UTC, zwiastunsw commented
Not only do I disagree. In 2017 [PR was reported](https://github.com/paypal/skipto/pull/38), which added the possibility of configuring the attributes of `role` and `aria-label`. 
The attributes: `roles`, `aria-label`, `title` are configurable. There is no need to change the script. Just change the configuration.

2019-03-13 11:05 UTC, zwiastunsw commented
Next steps? Are you planning to enrich your plugin with configuration options? Are you waiting for tests? 
The plugin works according to the following assumptions.

2019-03-15 11:30 UTC, wilsonge commented on plugins/system/skipto/skipto.php
> +		if (!($current_section & $section))
Pretty sure we don't mean to do this http://www.php.net/manual/en/language.operators.bitwise.php - even if it does work. I'd change yubikey to match what @Quy is suggesting

2019-03-15 11:32 UTC, wilsonge commented on plugins/system/skipto/skipto.php
> +	protected $autoloadLanguage = true;
If anyone has an idea why line 80 is required by the way I'll buy them a beer. Because for the life of me I don't understand why the variable here isn't working properly

2019-03-15 11:41 UTC, HLeithner commented on plugins/system/skipto/skipto.php
> +	protected $autoloadLanguage = true;
line 80 should not be necessary, because autloadLanguage does exactly the same only in the constructor...

2019-03-15 11:44 UTC, brianteeman commented on plugins/system/skipto/skipto.php
> +	protected $autoloadLanguage = true;
Well there is a bug somewhere

2019-03-15 11:49 UTC, wilsonge commented on plugins/system/skipto/skipto.php
> +	protected $autoloadLanguage = true;
There's definitely a bug somewhere. I just didn't have the time/energy to debug it at 1am (i put about 15 minutes into it and succeeded in being very confused :) - only about half the system plugins language files were actually being loaded)

2019-03-15 19:42 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +		if (!($current_section & $section))
It does work. The suggestion above does not.

2019-03-17 23:24 UTC, wilsonge commented
@brianteeman Given the options do seem to already be there as @zwiastunsw points out shall we get them included in here

2019-03-18 08:08 UTC, brianteeman commented
when i get the chance to I will add support for all configurable options

2019-03-18 17:21 UTC, brianteeman commented
@sharkykz I have made all the changes you requested except for the language one which is there because of a bug elsewhere in core so I added a todo

@zwiastunsw 
role is now navigation
title is removed
aria-label is used instead of title

I am not sure I understand what you are looking for with 
> SkipTo menu is the navigation area. Use the nav tag to mark it as a landmark.

2019-03-18 17:31 UTC, Quy commented on plugins/system/skipto/skipto.php
> +
Remove tabs.

2019-03-18 17:34 UTC, brianteeman commented
I can't decide if we should expose the ability to allow the user to edit the following

Heading (e.g h1, h2, h3 and h4 elements).
ARIA landmarks (e.g. banner, navigation, main and search).
HTML5 Section Elements (e.g. main, section[aria-label], section[aria-labelledby]
The “access key” is set to 0.

2019-03-18 17:36 UTC, Quy commented on plugins/system/skipto/skipto.php
> +
Remove one more tab.

2019-03-18 19:17 UTC, brianteeman commented
appveyor failed with
 > fatal: unable to access 'https://github.com/joomla/joomla-cms.git/': Could not resolve host: github.com

2019-03-19 09:12 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +			$app = $this->app;
Remove this line.

2019-03-19 09:13 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +		if (!($current_section && $section))
```suggestion
		if (!($current_section & $section))
```

2019-03-19 09:15 UTC, SharkyKZ commented on plugins/system/skipto/skipto.php
> +		$this->loadLanguage();
Personally, I would keep this and remove `$autoloadLanguage` instead. There's no need to load language files in backend if the plugin runs only in frontend, and vice versa.

2019-03-19 12:50 UTC, brianteeman commented on plugins/system/skipto/skipto.php
> +		if (!($current_section && $section))
Can a maintainer please make a decision. Using a single & is what I had originally and is the code used in the yubikey plugin but now @quy and @wilsonge saaid to change it to &&

2019-03-19 13:19 UTC, brianteeman commented on plugins/system/skipto/skipto.php
> +			$app = $this->app;
You told me to put it in https://github.com/joomla/joomla-cms/pull/24142#discussion_r264245532

2019-03-21 19:59 UTC, dgrammatiko commented
@wilsonge fwiw if was still the JS leader I wouldnt accept this skipto script to enter the project's dependencies

2019-03-21 22:47 UTC, brianteeman commented
are you going to say why?

2019-03-21 23:19 UTC, dgrammatiko commented
> are you going to say why?

- Search for `//IE8 fix:`
- The dropdown is totally useless and complete bloated code as we already have our own implementation, @C-Lodder mentioned that already.
The very obvious ones but there are more about that code. Not everything that works is also fit for the job...

2019-03-21 23:25 UTC, brianteeman commented
1. I was told NOT to change the code
2. The dropdown is separate code and if someone wants to integrate a different dropdown script then great. You know my skill set.

2019-03-21 23:38 UTC, dgrammatiko commented
> I was told NOT to change the code

That's then the reason you're looking for. You're simply adding technical debt here which is totally unneeded. We don't care for IE < 11 we shouldn't drag scripts that patch things for dead browsers...
Also, the fact that almost all functions have a patch for IE8 indicates clearly that this script is not up to date or maintained or what is my point of view that it will be maintained for the next 4-5 years that Joomla 4 will be out there...

All and all I am not against a skipto but let's do it properly, at the end of the day all there is here are some DOM manipulations nothing that even a JS noobie can't do...

2019-03-22 00:10 UTC, brianteeman commented
I would rather use working code (that can always be improved later) than wait for someone with JavaScript skills write a working solution.

You might find JavaScript easy to write. I certainly don't or I would have fixed the password strength and switcher js which are totally not accessible.

2019-03-22 00:17 UTC, dgrammatiko commented
> I would rather use working code 

That's why Joomla is a mess, everything is important and needs to be implemented right now, no matter what the technical debt that it introduces. Sorry I totally disagree here... 

> I would have fixed the password strength 

Well, I had a PR standing there for 3 months and finally, @wilsonge said "no new custom elements". I'm not a magician, I do my best but I can't fix something if people don't merge my stupid code...

2019-03-25 10:49 UTC, wilsonge commented
@zwiastunsw Can you retest this please

2019-03-26 09:23 UTC, zwiastunsw commented
I have tested this item :white_check_mark: successfully on 44775ee8a645e259aff619fcf86517cce703774b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24142">issues.joomla.org/tracker/joomla-cms/24142</a>.</sub>

2019-03-26 09:37 UTC, zwiastunsw commented
> I can't decide if we should expose the ability to allow the user to edit the following ....

In my opinion it is not necessary. Theplugin has to do exactly what it does. Adding configuration options will only make the system operation more complicated.

2019-03-26 10:34 UTC, merged

2019-03-26 10:34 UTC, wilsonge commented
Thanks guys!

2019-03-26 21:06 UTC, brianteeman commented
Thanks for testing and merging. If we ever get a new admin template this will be essential for testing it