Fix QR-Code for 2FA
joomla/joomla-cms pull request #24255
Opened 2019-03-20 00:19 UTC by bembelimen

Pull Request for Issue #24252 .

### Summary of Changes
Implements an internal QR-Code generator instead of the google charts.

### Testing Instructions
Activate the Google Authenticator 2FA plugin and set up 2FA for one user.

### Expected result
QR-Code visible

### Actual result
QR-Code broken

2019-03-20 00:23 UTC, brianteeman commented
Thank you for such a speedy response. I will test his in the morning

2019-03-20 01:16 UTC, ReLater commented
I have tested this item :white_check_mark: successfully on 550ddf2703e540a94addd9bed25b504be2ec388c<br /><br />Before patch: No QR code.
After patch: QR code created.

I could not test if QR code is scannable and/or correct. Decide yourself if that's a successful test!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24255">issues.joomla.org/tracker/joomla-cms/24255</a>.</sub>

2019-03-20 01:29 UTC, Quy commented on plugins/twofactorauth/totp/tmpl/form.php
> +HTMLHelper::_('script', 'plg_twofactorauth_totp/qrcode.min.js', ['relative' => true, 'version' => 'auto']);
```suggestion
HTMLHelper::_('script', 'plg_twofactorauth_totp/qrcode.min.js', array('version' => 'auto', 'relative' => true));
```

2019-03-20 02:32 UTC, mbabker commented on plugins/twofactorauth/totp/tmpl/form.php
> +})(jQuery);
Nothing inside this function needs jQuery, so the reason you're making the function dependent on it is?

2019-03-20 12:52 UTC, C-Lodder requested changes

2019-03-20 12:52 UTC, C-Lodder commented on plugins/twofactorauth/totp/tmpl/form.php
> +$js = "
Can you not put this in a separate file in the `media` directory so it doesn't need to be done for J4?

2019-03-20 12:54 UTC, HLeithner commented on plugins/twofactorauth/totp/tmpl/form.php
> +$js = "
Joomla 4 should get a webcomponent for displaying qrcodes.

2019-03-20 13:07 UTC, C-Lodder commented on plugins/twofactorauth/totp/tmpl/form.php
> +$js = "
Even if that's the case, any new additional JS for J3 should be whacked in a separate file so that it makes the migration a lot easier

2019-03-20 13:32 UTC, HLeithner commented on plugins/twofactorauth/totp/tmpl/form.php
> +$js = "
Github fools me... you mean the inline js should be moved. ok that makes sense

2019-03-20 13:44 UTC, C-Lodder commented on plugins/twofactorauth/totp/tmpl/form.php
> +$js = "
sorry, I probably should be moved my comment down a couple more lines :)

2019-04-02 11:27 UTC, wilsonge commented
For my own reference when it comes to J4 the library is https://github.com/kazuhikoarase/qrcode-generator/blob/master/js/package.json#L2

2019-04-02 11:28 UTC, wilsonge approved these changes

2019-04-02 14:59 UTC, merged

2019-04-02 14:59 UTC, HLeithner commented
thx

2019-04-09 16:58 UTC, deroderuiter commented
I installed 3.9.5 but the fix for the QR-Code for 2FA still does not work on my Joomla installation. Do I have do to something special to get it working again?

2019-04-09 17:46 UTC, HLeithner commented
@deroderuiter strange I tested it again and it works for me, do you have a screenshot and could you create a new issue.

2019-04-09 18:12 UTC, deroderuiter commented
There is not much to show. In edit profile I choose the tab Two Factor Authentication, I scan the QR code with the Google Authenticator App on my smartphone and fill in the code and save the page. No error is displayed but the tow factor authentication is not activated.

2019-04-09 18:17 UTC, deroderuiter commented
I saw I remark of Phil Taylor that Google no longer provides a chart API for QR Code. It was actually deprecated in 2012 and **turned off Completely on March 18,2019**
My English i not so good and I don't know if I understood this correctly and if it is correct it could explain why 2FA doesn't work anymore.

2019-04-09 18:20 UTC, brianteeman commented
if you see the qr code then the issue you refer to above is resolved as the qr code has been generated by different code

2019-04-09 18:43 UTC, deroderuiter commented
So probably I have an other problem?