Feature/users api
joomla/joomla-cms pull request #24257
Opened 2019-03-20 06:40 UTC by Oracions2410

Add Basic users api

2019-03-20 07:21 UTC, alikon requested changes

2019-03-20 07:21 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-05.sql
> +(498, 0, 'plg_webservices_users', 'plugin', 'users', 'webservices', 0, 1, 1, 0, '', '{}', 0, '0000-00-00 00:00:00', 0, 0),
please use default date for postgresql `'1970-01-01 00:00:00'`

2019-03-20 07:21 UTC, alikon commented on installation/sql/postgresql/joomla.sql
> +(498, 0, 'plg_webservices_users', 'plugin', 'users', 'webservices', 0, 1, 1, 0, '', '{}', 0, '0000-00-00 00:00:00', 0, 0),
please use default date for postgresql `'1970-01-01 00:00:00'`

2019-03-20 10:19 UTC, Oracions2410 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-05.sql
> +(498, 0, 'plg_webservices_users', 'plugin', 'users', 'webservices', 0, 1, 1, 0, '', '{}', 0, '0000-00-00 00:00:00', 0, 0),
@alikon Okay ! Thank you

2019-03-20 11:35 UTC, SharkyKZ commented on installation/sql/mysql/joomla.sql
> -(481, 0, 'plg_system_userlogs', 'plugin', 'userlogs', 'system', 0, 1, 1, 0, '', '{"logDeletePeriod":"0","ip_logging":"1","loggable_extensions":["com_banners","com_cache","com_categories","com_config"
Why is `plg_system_userlogs` being deleted?

2019-08-28 10:06 UTC, franz-wohlkoenig commented
closed in favor of #26002

2019-08-28 10:06 UTC, closed without merging