[4.0] Change foreground color
joomla/joomla-cms pull request #24265
Opened 2019-03-20 16:00 UTC by hardik-codes

Pull Request for Issue #24261 

### Testing Instructions

Test the administrator login page using the following tool http://aka.ms/AccessibilityInsights.

### Expected result
No contrast error

### Actual result
contrast error

### Documentation Changes Required
None

2019-03-20 16:11 UTC, C-Lodder requested changes

2019-03-20 16:11 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_login.scss
> +        color: #CBD8E1;
Please add this to the `variables.scss` and make the hex all lowercase

2019-03-20 16:13 UTC, hardik-codes commented on administrator/templates/atum/scss/blocks/_login.scss
> +        color: #CBD8E1;
@C-Lodder in which line should I add the variable for this color?

2019-03-20 16:27 UTC, hardik-codes commented
@C-Lodder Now have a look

2019-03-20 17:04 UTC, C-Lodder approved these changes

2019-03-21 13:41 UTC, merged

2019-03-21 13:41 UTC, wilsonge commented
Thanks!