[4.0] Adding frontend edit for com_contact
joomla/joomla-cms pull request #24311
Opened 2019-03-22 10:14 UTC by Bakual

This PR is a rebase of https://github.com/joomla/joomla-cms/pull/22735 for 4.0

This PR adds frontend editing to com_contact.

### Summary of Changes
Adding form view and accompagning controller and model to com_contact frontend

### Testing Instructions
* Test adding and editing contacts from frontend. If the user is authorised, he should see an edit link in the category view and contact view. The category view additionaly has a "New" button.
The featured view doesn't have any such links.
There is a menuitem to point to create new contacts.

* Test that data doesn't get lost when saving (especially data not available to edit in frontend vs backend).

* Test especially also ACL. JSST should look over it for possible security issues.

### Expected result
Works

### Actual result
Frontend editing not possible.

### Documentation Changes Required
A new help page will be needed. Possibly also other doc pages.

2019-03-22 10:17 UTC, Bakual commented
Some testing was already be done in the original PR. But this needs to be properly retested since there are a lot of differences (not a simple rebase).

There were two issues raised by @kofaysi which I have looked at now:
* Cache: Cache will now be disabled if a user is logged in. This behavior is similar to com_content.
* Duplicate Alias will not be resolved automatically. While com_content does that by appending a number, it's something that is done in com_content both in front- and backend. One can add this in com_contact as well, but it's out of scope fro this PR. For now frontend behavior will be same as backend.

2019-03-22 10:36 UTC, brianteeman commented on administrator/components/com_contact/Service/HTML/Icon.php
> +		$contactUrl = \Joomla\Component\Contact\Site\Helper\Route::getContactRoute($contact->slug, $contact->catid, $contact->language);
why not just Route::?

2019-03-22 10:41 UTC, brianteeman commented
In Joomla 4 we are really trying not to have useless _DESC strings unless they are absolutely necessary - they dont appear to be here

2019-03-22 11:11 UTC, Bakual commented
> In Joomla 4 we are really trying not to have useless _DESC strings unless they are absolutely necessary - they dont appear to be here

True. Forgot that those were removed in 4.0 when I rebased the PR.
Should I just remove all of them or is there one which needs to stay?

2019-03-22 11:21 UTC, Bakual commented on administrator/components/com_contact/Service/HTML/Icon.php
> +		$contactUrl = \Joomla\Component\Contact\Site\Helper\Route::getContactRoute($contact->slug, $contact->catid, $contact->language);
Because `Route` already is used for \Joomla\CMS\Router\Route`. I could create an alias, but since it's only used once in thsi class this works as well.

2019-03-22 12:02 UTC, brianteeman commented
Thanks @Bakual

2019-03-25 07:06 UTC, infograf768 commented
@Bakual 
Please correct the contact admin model to include a similar code to what we have for com_content
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/Model/ArticleModel.php#L632-L649

Also, we just added in 3.9 this
https://github.com/joomla/joomla-cms/pull/24216
and I guess  we should o the same for contact.

2019-03-25 09:27 UTC, Bakual commented
@infograf768 First one is code in the administrator model. Which means that bug already exists in com_contact backend form. So it's unrelated to this PR and can be done in a separate one.

The second one I don't understand the issue it tries to solve. I could change categories just fine in frontend and don't see a reason to prevent this.
Is this related to workflows? If so then it doesn't apply to contacts as it doesn't use workflows.

2019-03-25 12:02 UTC, Bakual commented
@infograf768 As discussed in Glip I added code to prevent changing the language of already associated contacts.
I've not touched anything related to categories. That should be done in separate PRs if needed (I don't see the need yet).

2019-03-26 14:45 UTC, infograf768 commented on components/com_contact/forms/form.xml
> +			addfieldpath="/administrator/components/com_categories/models/fields"
no use in 4.0

2019-03-26 14:49 UTC, Bakual commented on components/com_contact/forms/form.xml
> +			addfieldpath="/administrator/components/com_categories/models/fields"
Thanks, will remove.

2019-10-19 09:28 UTC, jduerscheid commented
There is some additional styling necessary<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24311">issues.joomla.org/tracker/joomla-cms/24311</a>.</sub>

2019-10-19 10:25 UTC, jduerscheid commented
Screenshots to the Styling![screen shot 2019-10-19 at 10 25 40](https://issues.joomla.org/uploads/1/fcc60b20b9157bbd4af975824278db56.png)![screen shot 2019-10-19 at 10 25 41](https://issues.joomla.org/uploads/1/14ef62b6258f83c526fa8eb34e00c541.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24311">issues.joomla.org/tracker/joomla-cms/24311</a>.</sub>

2019-10-19 10:54 UTC, Bakual commented
Can you check if this styling issue specific to the contact edit form? I'd expect it to be the same as in the article edit form. If the same issue exists there as well, it's out of scope of this PR.

2019-10-19 11:00 UTC, jduerscheid commented
> Can you check if this styling issue specific to the contact edit form? I'd expect it to be the same as in the article edit form. If the same issue exists there as well, it's out of scope of this PR.

The styling in the editform is correct. But not in the list view of the Category

2019-10-19 18:45 UTC, Bakual commented
I'm currently unable to check this myself as my 4.0 installation is broken. If someone can check why that is, I'm more than happy.

2019-12-04 19:49 UTC, Bakual commented
Merged 4.0-dev so it's up to date again.
Adjusted the icons so they match the changes in template. Eg using Font Awesome class now.

Should be testable again.

2019-12-05 10:06 UTC, infograf768 commented
test on multilingual site, frontend

Creating a new contact in frontend by super user or author
Impossible to choose category (No field). Selecting language works fine.
Error displays
<img width="947" alt="Screen Shot 2019-12-05 at 10 42 15" src="https://user-images.githubusercontent.com/869724/70224441-92246200-174d-11ea-8704-8c680192ec04.png">
In backend we can see the new contact is created in the Uncategorised category.


Editing an existing contact in frontend (as super User)
Category should display as greyed (but field is not present), possible to change contact language although it should also be greyed.

Please look how we do for articles creation and edit.

2019-12-05 16:08 UTC, Bakual commented
When I try to create a new contact, I can select the category just fine from any available category, be it specific to a language or "All". The field is under "Publishing", same place it is for articles.

I'm also able to change language and category of a contact as I would expect.

As I wrote before, I don't understand the category issue and thus if something needs to be fixed it has to be done separately.

I've tested with articles, and it is broken there. So I surely will not do like there 😄

2019-12-07 06:49 UTC, infograf768 commented
Now saw the category field...
Will try asap to explain again the issue in multilingual concerning contacts assigned to a specific user.

2020-01-13 14:26 UTC, johnnydevs commented
Will this feature be available in Joomla 4? Currently using 3.9.14 and I think it would be very useful!

2020-01-13 17:40 UTC, Bakual commented
@johnnydevs Only if enough people successfully test it.

2020-01-14 09:00 UTC, johnnydevs commented
@Bakual I think it would be a great feature, I'm willing to test it also :)

2020-01-14 10:14 UTC, Bakual commented
@johnnydevs See https://docs.joomla.org/Testing_Joomla!_patches on how you can help.

2020-01-25 19:18 UTC, Quy commented on components/com_contact/forms/form.xml
> +				name="id"
Reduce indentation.

2020-01-25 19:28 UTC, Bakual commented
Resolved conflicts and did some codestyle. Testable again.

2020-02-02 12:47 UTC, astridx commented
I get this error:
` 0 Class 'Joomla\Component\Contact\Site\Helper\Route' not found `
![Error  0](https://user-images.githubusercontent.com/9974686/73608297-9a6c1280-45c1-11ea-97bb-1f6b5a643351.png)
Please see my PR to your branch.

2020-02-02 13:34 UTC, Bakual commented
Good find, that is because of the renaming in https://github.com/joomla/joomla-cms/pull/27510
Thanks for your PR, I've already merged it.

2020-02-02 17:04 UTC, astridx commented
I checked a contact front end. I do not see the icon for editing, although I logged in as super user.
![contact test](https://user-images.githubusercontent.com/9974686/73611769-95b95580-45e5-11ea-8bca-9450fedf63e5.png)

After applying this patch i could add a menu item for creating a contact.
![Menus  Edit Item   test   Administration](https://user-images.githubusercontent.com/9974686/73611768-95b95580-45e5-11ea-89fb-90084c3625f4.png)

I created the menu item.
![create contact](https://user-images.githubusercontent.com/9974686/73611767-95b95580-45e5-11ea-849e-39ad99bc4935.png)

I checked, if I see the edit icon with a already existing contact, when I log in as super user.
![Single Contact](https://user-images.githubusercontent.com/9974686/73611766-9520bf00-45e5-11ea-9b79-24bbafe4d18a.png)

I was able to edit the already existing contact.
![Single Contact(1)](https://user-images.githubusercontent.com/9974686/73611765-9520bf00-45e5-11ea-9b0b-357ba88e1833.png)

I could submit a new contact.
![Single Contact(2)](https://user-images.githubusercontent.com/9974686/73611764-9520bf00-45e5-11ea-9b5b-aa35f93b42c5.png)

If I do not explicitly click on a category, this message appears when I create a contact. In my opinion, this is not an error. You could only make it more user-friendly.
![Single Contact(3)](https://user-images.githubusercontent.com/9974686/73611762-94882880-45e5-11ea-81b9-9763a58a5b00.png)

2020-02-02 17:06 UTC, astridx commented
I have tested this item :white_check_mark: successfully on 94bb7622bebe2abe76e04ceddeb484697b9c3a95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24311">issues.joomla.org/tracker/joomla-cms/24311</a>.</sub>

2020-02-02 20:04 UTC, Bakual commented
> If I do not explicitly click on a category, this message appears when I create a contact. In my opinion, this is not an error. You could only make it more user-friendly.

I'd like to follow the behavior of com_content here. But haven't tested this exact behavior so can't say how it is done for articles.
Anyway, it would be easy to do afterwards as well. Would be great if this could be merged into 4.0 so it's part of beta.

2020-02-02 22:18 UTC, richard67 commented
@Bakual @astridx I get the error alert "Category not found" if I select a category, regardless if the selected language for the contact is "all" or one of the installed languages, and regardless if this selection matches to the category's language or not. Is this expected? Everythins erlse seems to work, including ACL. So shall I give it a good test or wait for some changes? Not sure now, am open for opinions and advise.

2020-02-05 20:33 UTC, richard67 commented
@Bakual Could you solve conflict in file `components/com_contact/tmpl/contact/default.php` and update to 4.0-dev base branch?

And due to recently merged PR #27657 , there was a change of the fontawesome so-called style prefix. It's not really a prefix, it is the first css class used for the style, solid (fas), regular (far), brand (fab), and refers to the package where it's in. Not to be mixed up with the "fa-" prefix at the beginning of the icon name, this stays the same. Could you update your icons? I think they all belong to "fas", but am not 100% sure. Maybe @N3REJ can check. If you don't have time for that, he or me can make a PR to your branch for this PR so you can merge with 1 click. But before that you should update with the base branch (4.0-dev) e.g. by using the button here at the bottom.

Regarding my test I am a bit uncertain: I had the red error alert shown in Astrid's screenshot also when selecting an existing category. With com_content, when creating a new article in frontend, this doesn't happen in any of these 2 cases. I really would like to see this in beta but would feel more comfortable with givign a good test when this error alert would not be there :-)

2020-02-05 21:46 UTC, Bakual commented
Updated branch and adjusted the FA icons.
I'm looking into that category thing if I can reproduce and tackle it

2020-02-05 21:55 UTC, Bakual commented
I can't reproduce the "Category not found" thing. Do you know where it is coming from? Maybe related to menuitems?

2020-02-05 22:00 UTC, richard67 commented
@Bakual Will check tomorrow after work. But PHP logfile or MySQL logfile didn't show anything special.

2020-02-05 22:18 UTC, richard67 commented
@Bakual Strange .. now I can't reproduce it either. I've did (almost) same as last time when I've checked. New clean current 4.0-dev install, one new administrator user (not super user, just admin) created, no categories for contacts created, logged in on frontend as the new admin user and created the contact. No issue. Is late now, have to continue tomorrow.

One question: Is it correct that the frontend editing form doesn't show a field to assign a user to the contact? Or is it a mistake? Or did I just not see it?

2020-02-05 22:20 UTC, richard67 commented
@astridx Could you test this again? Am curious if you get the error alert about category not found again. This time I didn't get it, last time I did.

2020-02-05 22:24 UTC, richard67 commented
Maybe the last update to latest 4.0-dev base branch solved it? Maybe was something not ok in 4.0-dev when it was pulled in last time? Have to test more tomorrow.

2020-02-05 22:34 UTC, Bakual commented
> One question: Is it correct that the frontend editing form doesn't show a field to assign a user to the contact? Or is it a mistake? Or did I just not see it?

From memory, which may serve me wrong at this time: In frontend, the user select field can't be used for security reasons. Since you would see a list of all users. So I didn't include that one.
You also can't change the author of an article for that same reason (I believe) in frontend.

2020-02-05 22:35 UTC, richard67 commented
>In frontend, the user select field can't be used for security reasons. Since you would see a list of all users.

Oh yes, that makes pretty much sense!

2020-02-05 23:00 UTC, richard67 requested changes

2020-02-05 23:00 UTC, richard67 commented on administrator/components/com_contact/Extension/ContactComponent.php
> +		if (Factory::getApplication()->isClient('site') && ($section == 'category' || $section == 'form'))
```suggestion
		if (Factory::getApplication()->isClient('site') && ($section === 'category' || $section === 'form'))
```

2020-02-05 23:00 UTC, richard67 commented on administrator/components/com_contact/Service/HTML/Icon.php
> +		if ($contact->published == 0)
```suggestion
		if ($contact->published === 0)
```

2020-02-05 23:00 UTC, richard67 commented on components/com_contact/Controller/ContactController.php
> +				return ($record->created_by == $user->id);
```suggestion
				return ($record->created_by === $user->id);
```

2020-02-05 23:00 UTC, richard67 commented on components/com_contact/View/Form/HtmlView.php
> +			$authorised = $canDo->get('core.edit') || ($canDo->get('core.edit.own') && $this->item->created_by == $user->id);
```suggestion
			$authorised = $canDo->get('core.edit') || ($canDo->get('core.edit.own') && $this->item->created_by === $user->id);
```

2020-02-05 23:00 UTC, richard67 commented on components/com_contact/View/Form/HtmlView.php
> +		if ($app->get('sitename_pagetitles', 0) == 1)
```suggestion
		if ($app->get('sitename_pagetitles', 0) === 1)
```

2020-02-05 23:00 UTC, richard67 commented on components/com_contact/tmpl/category/default_items.php
> +						<?php if ($canEdit || ($canDo->get('core.edit.own') && $item->created_by == $userId)) : ?>
```suggestion
						<?php if ($canEdit || ($canDo->get('core.edit.own') && $item->created_by === $userId)) : ?>
```

2020-02-05 23:00 UTC, richard67 commented on components/com_contact/tmpl/contact/default.php
> +$canEdit = $canDo->get('core.edit') || ($canDo->get('core.edit.own') && $this->item->created_by == Factory::getUser()->id);
```suggestion
$canEdit = $canDo->get('core.edit') || ($canDo->get('core.edit.own') && $this->item->created_by === Factory::getUser()->id);
```

2020-02-05 23:00 UTC, richard67 commented on administrator/components/com_contact/Service/HTML/Icon.php
> +			&& $contact->checked_out != $user->get('id'))
```suggestion
			&& $contact->checked_out !== $user->get('id'))
```

2020-02-05 23:00 UTC, richard67 commented on administrator/components/com_contact/Service/HTML/Icon.php
> +			|| ((strtotime($contact->publish_down) < strtotime(Factory::getDate())) && $contact->publish_down != Factory::getDbo()->getNullDate()))
```suggestion
			|| ($contact->publish_down !== null && (strtotime($contact->publish_down) < strtotime(Factory::getDate())))
```

2020-02-05 23:00 UTC, richard67 commented on administrator/components/com_contact/Service/HTML/Icon.php
> +		if (strtotime($contact->publish_up) > strtotime(Factory::getDate())
```suggestion
		if ($contact->publish_up !== null && (strtotime($contact->publish_up) > strtotime(Factory::getDate()))
```

2020-02-06 07:03 UTC, Bakual commented on administrator/components/com_contact/Extension/ContactComponent.php
> +		if (Factory::getApplication()->isClient('site') && ($section == 'category' || $section == 'form'))
I'd prefer to make such changes for the whole file, not just for a subset. Eg `$section == 'contact'` a few lines above would need the same change. But then it's out of scope of this PR to make CS changes to unrelated code.

2020-02-06 07:18 UTC, Bakual commented on administrator/components/com_contact/Extension/ContactComponent.php
> +		if (Factory::getApplication()->isClient('site') && ($section == 'category' || $section == 'form'))
NM, I just commit this as well :)

2020-02-06 09:40 UTC, richard67 commented
Regarding my suggested change for check if published: we meanwhile have real null values for published up and down in J4 and don’t use the old nulldates anymore. I have to check tonight after work if my suggestion was correct or needs a fix maybe. If you are faster you can look up in com_content Frontensegeln editing how it is done there.

2020-02-06 17:48 UTC, Bakual commented
I did look up how it is done in com_content before I merged it 😄

2020-02-06 17:54 UTC, richard67 commented
@Bakual In J3? Or in J4 but before November 2019? In end of 2019 we have changed the nulldate stuff.

2020-02-06 19:00 UTC, richard67 commented
@Bakual Can it be you once gave me write permission for your repository? I wanted to make a PR for your branch. Normally I do this by edfiting a file of the "victim" (=you) and then cancel. Then I have a branch in my repo based on the "victim's" branch, then I pull that and edit locally. But because I have write access it doesn't work like that, it edits directly in your repo. Because I don't have much time I've committed now directly to your branch.

I've changed the check for publish up and down times so it is like we have it here since the nulldate changes end of last year: [https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/content/icons/edit.php#L36-L41](https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/content/icons/edit.php#L36-L41).

If possible, could you revoke my write permission to your repo? I don't feel comfortable with having that permission on other people's repo.

2020-02-06 19:01 UTC, richard67 commented
@Bakual P.S.: If one of my previous change suggestions was for a part of code which hadn't been touched by your PR before that, then it was a mistake, not by purpose. I wanted to change only those which you had touched.

2020-02-06 19:03 UTC, richard67 commented on components/com_contact/View/Form/HtmlView.php
> +		elseif ($app->get('sitename_pagetitles', 0) == 2)
Was this the wrong suggestion for changing code which you hadn't touched? If so, please just mark the conversation as resolved.

2020-02-06 19:47 UTC, Bakual commented
>  Can it be you once gave me write permission for your repository?

That's because you're now a maintainer. When creating a PR I can set a checkbox to allow edits from maintainers.
That doesn't mean you have write permissions to my repo, just to that particular branch. Which is fine for me 👍

2020-02-06 19:49 UTC, richard67 commented
@Bakual Well thanks god it is possible to undo commits with git. Just in case I edit someone's PR and fall asleep because so late and then my forehead hits the keyboard ;-)

2020-02-09 17:05 UTC, richard67 approved these changes

2020-02-09 17:51 UTC, astridx commented
> @richard67 @astridx Could you test this again? Am curious if you get the error alert about category not found again. This time I didn't get it, last time I did.

I have repeated my test. I did **not** get the error alert about "category not found" again.

2020-02-09 17:52 UTC, richard67 commented
@astridx Is the test good enough to set a good result in the issue tracker? If so, pls. do.

2020-02-09 17:52 UTC, astridx commented
I have tested this item :white_check_mark: successfully on 8f01ab1d889f3da3f1884ceca40ee91c9c849e15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24311">issues.joomla.org/tracker/joomla-cms/24311</a>.</sub>

2020-02-09 17:52 UTC, astridx commented
I have tested this item :white_check_mark: successfully on 8f01ab1d889f3da3f1884ceca40ee91c9c849e15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24311">issues.joomla.org/tracker/joomla-cms/24311</a>.</sub>

2020-02-09 17:53 UTC, richard67 commented
ah i was just a bit too impatient ;-)

2020-02-09 17:54 UTC, astridx commented
@richard67 Since something similar has happened to me today, it may also be that I am too slow.

2020-02-09 17:56 UTC, richard67 commented
@infograf768 Do you think you have time to test this, too? I am sure if there is a multilanguage issue we have not seen, you would see it.

2020-02-09 18:20 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 8f01ab1d889f3da3f1884ceca40ee91c9c849e15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24311">issues.joomla.org/tracker/joomla-cms/24311</a>.</sub>

2020-02-09 18:20 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24311">issues.joomla.org/tracker/joomla-cms/24311</a>.</sub>

2020-02-11 10:09 UTC, merged