[4.0]fixed toggle checkboxes
joomla/joomla-cms pull request #24335
Opened 2019-03-24 12:39 UTC by bahl24

Pull Request for Issue #23801 .
Opened again as #23844 is not working.

### Summary of Changes
Used JS to fix functions of toggle checkboxes. Avoided JQuery as pointed out in https://github.com/joomla/joomla-cms/pull/24100#issuecomment-469784555

### Testing Instructions
Template(Styles) -> Menu Assignment -> 'Toggle Selection' buttons

### Expected result
Toggle buttons work

### Actual result
Toggle buttons work only for 1st element. Also, doesn't work if class/alias name starts with number eg `1author-menu`

### Documentation Changes Required
None

2019-03-24 12:51 UTC, brianteeman commented
cannot comment on the code but i can confirm it works

2019-03-24 12:52 UTC, roland-d commented on administrator/components/com_templates/tmpl/style/edit_assignment.php
> +		var value = document.querySelectorAll('.chk-menulink')[0].checked;
Please use `let` instead of `var` in all the JavaScript code.

2019-03-24 13:04 UTC, bahl24 commented on administrator/components/com_templates/tmpl/style/edit_assignment.php
> +		var value = document.querySelectorAll('.chk-menulink')[0].checked;
Done

2019-03-24 13:16 UTC, roland-d commented on administrator/components/com_templates/tmpl/style/edit_assignment.php
> +		}
Isn't it more efficient to do something like this:
```js
let checkBoxes = document.querySelectorAll('.chk-menulink'),
value = checkBoxes[0].checked;
		for(let count=0; count < checkBoxes.length; count++){
			checkBoxes[count].checked = !value;
		}
```

2019-03-24 13:46 UTC, dgrammatiko requested changes

2019-03-24 13:46 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/style/edit_assignment.php
> +		}
There quite some problems here:
- Don't inline so much JS. Create a file with a function and just call that function on the onclick attribute;
- You **cannot** use ES2015+ code directly, the code needs to be transpiled so it can work on IE11
- Don't use `for` instead do `const checkBoxes = [].slice.call(document.querySelectorAll('.chk-menulink'));` and `checkBoxes .forEach(checkBox => { /* Your logic here */ }); `

2019-03-27 10:43 UTC, bahl24 commented on administrator/components/com_templates/tmpl/style/edit_assignment.php
> +		}
@dgrammatiko Should I create a separate file or enclose the function in the script tag in php file?

2019-03-27 11:47 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/style/edit_assignment.php
> +		}
Never, ever use `<script>` tags directly. This is a huge anti-pattern that so many extensions fail badly!!! So please **don't do that in the Joomla core**

You can either 
- use `Factory::getDocument()->addScriptDeclaration('script contents here')
- create an es6 file in the `build/media_source/com_tempates`

I would always recommend the second approach as you will be able to use ES6 code and the build tools will do the transpiling, minification, etc

2019-03-27 14:02 UTC, bahl24 commented on administrator/components/com_templates/tmpl/style/edit_assignment.php
> +		}
I was able to implement 1st option but I am facing some errors and working on the 2nd option

2019-06-10 08:19 UTC, franz-wohlkoenig commented
Closed as replaced by #25155. Thanks for Pull Request @bahl24

2019-06-10 08:19 UTC, closed without merging