Fix Issue #24114
joomla/joomla-cms pull request #24336
Opened 2019-03-24 14:51 UTC by Arpit-24

Pull Request for Issue #24114 .

### Summary of Changes

Overflow is made visible for the ul element wrapping the datepicker

### Testing Instructions

go to administrator=>content=>articles=>new=>publish tab
set width of tab less than 920 pixel
open the first calender

### Expected result

Full Accessible Calender

### Actual result

Partially accessible calender is now fixed

### Documentation Changes Required

None

![Screenshot (1229)](https://user-images.githubusercontent.com/26358271/54881099-57ee8b00-4e72-11e9-8c5b-c5da9b0e190f.png)

After this change

2019-03-25 08:00 UTC, infograf768 commented
Not sure I understand this patch

`.mce-fullscreen`
is specific to TinyMCE and, **if necessary**,  should be added in `atum/scss/vendor/_tinymce.scss`

> Overflow is made visible for the ul element wrapping the datepicker

As far as I know, the calendar has a `<div>` container, not a `<ul>`

can you explain better?

2019-03-25 08:56 UTC, infograf768 commented
concerning the `mce-fullscreen`  it looks like some mixup with https://github.com/joomla/joomla-cms/pull/24334

2019-03-25 09:07 UTC, Arpit-24 commented
> concerning the `mce-fullscreen` it looks like some mixup with #24334

Yes, It was a mix with another issue fix. Apologies for the mistake.

And regarding why making overflow visible fixes the issue is. In the joomla-custom-elements.
The style for joomla-tab > ul is set to overflow-y:hidden which causes it to hide elements that exceed its bound.

In lower screen sizes the date picker element the div itself is going out of the size defined by ul element for its children thus causing it to be hidden.

2019-03-25 09:14 UTC, infograf768 commented
This is not working here:
<img width="748" alt="Screen Shot 2019-03-25 at 10 13 40" src="https://user-images.githubusercontent.com/869724/54907827-c53c0380-4ee6-11e9-9c59-14c69b418d8b.png">

2019-03-25 12:09 UTC, C-Lodder commented
The calendar z-index also needs changing

2019-03-25 15:03 UTC, Arpit-24 commented
> The calendar z-index also needs changing.
> 
> Please don't add your code to the `template.scss`. This file is supposed to be used as the base for importing all sub-scss files

Updated the commit to _form.scss file

2019-03-25 15:07 UTC, Arpit-24 commented
> This is not working here:
> <img alt="Screen Shot 2019-03-25 at 10 13 40" width="748" src="https://user-images.githubusercontent.com/869724/54907827-c53c0380-4ee6-11e9-9c59-14c69b418d8b.png">

I was unable to replicate the issue. Could you give me some more details? It seems fixed for me.

My Configuration :
Windows 10 x64
Google Chrome Version 73.0.3683.86

2019-03-27 06:49 UTC, franz-wohlkoenig commented
@Puneet-Jain-18 please test.

2019-03-27 10:39 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on b15ad3c9273e31f0a4fee33355ae52b0379d7ee6<br /><br />I tested the display of the calendar and it is now OK.

Remains an issue here when the window is small enough forces scroll bars to display (Firefox)
In that case we may need to scroll to see the calendar fully, BUT clicking on the scroll bars closes the calendar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24336">issues.joomla.org/tracker/joomla-cms/24336</a>.</sub>

2019-03-27 10:44 UTC, infograf768 commented
![scollbars_calendar](https://user-images.githubusercontent.com/869724/55070034-aaec5c00-5085-11e9-9cd4-55db32f3d249.gif)

2019-04-03 21:34 UTC, Arpit-24 commented
> Remains an issue here when the window is small enough forces scroll bars to display (Firefox)
> In that case we may need to scroll to see the calendar fully, BUT clicking on the scroll bars closes the calendar.

Eliminated the need for horizontal scrolling. For vertical scrolling in mobiles if we scroll normally using touch then it doesn't close as emulated by chrome, but yes clicking the scrollbar will close it as is the expected browser behavior of taking the focus away from all the elements and giving the focus to body tag, and loosing focus from the input field will close the calendar picker.

2019-04-03 21:56 UTC, C-Lodder requested changes

2019-04-03 21:56 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_form.scss
> +@media screen and (max-width: 484px) {
Please use the appropriate variables for the media query

2019-04-03 22:20 UTC, Arpit-24 commented on administrator/templates/atum/scss/blocks/_form.scss
> +@media screen and (max-width: 484px) {
I tried using variables but as of now it seems that media queries don't support variables.

I tried using both var(--breakpoint-sm) as well as calc(var(--breakpoint-sm)) but none of them worked.

2019-04-04 06:31 UTC, C-Lodder commented
I mean a SCSS variable (should already be defined), not CSS variables

2019-04-04 10:00 UTC, Arpit-24 commented
> I mean a SCSS variable (should already be defined), not CSS variables

Unfortunately, I couldn't find an already defined scss variable to use in the _variables.scss file. created a new one for use.

2019-04-04 11:49 UTC, C-Lodder commented
We use the following breakpoints:

```
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
);
```

So you'll want to use:

```
@include media-breakpoint-up(sm) {
  .js-calendar {
    right: 0;
  }
}
```

2019-04-04 14:34 UTC, Arpit-24 commented
> We use the following breakpoints:
> 
> ```
> $grid-breakpoints: (
>   xs: 0,
>   sm: 576px,
>   md: 768px,
>   lg: 992px,
>   xl: 1200px
> );
> ```
> So you'll want to use:
> 
> ```
> @include media-breakpoint-down(sm) {
>   .js-calendar {
>     right: 0;
>   }
> }
> ```

Updated

2019-04-19 16:33 UTC, Puneet-Jain-18 commented
I have tested this item :white_check_mark: successfully on e8acf35022cf906f93e361553ff87c991121b059<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24336">issues.joomla.org/tracker/joomla-cms/24336</a>.</sub>

2019-04-19 16:39 UTC, franz-wohlkoenig commented
@infograf768 please retest

2019-10-19 10:11 UTC, tushar33 commented
I have tested this item :red_circle: unsuccessfully on 4fd3b6cb6627f17351cef541d98bddf07ef6e7e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24336">issues.joomla.org/tracker/joomla-cms/24336</a>.</sub>

2019-10-19 10:12 UTC, tushar33 commented
I have tested this item :red_circle: unsuccessfully on 4fd3b6cb6627f17351cef541d98bddf07ef6e7e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24336">issues.joomla.org/tracker/joomla-cms/24336</a>.</sub>

2020-08-03 12:02 UTC, yasin-96 commented
I have tested this item :white_check_mark: successfully on 4fd3b6cb6627f17351cef541d98bddf07ef6e7e0<br /><br />After following the testing instructions I can confirm that the calender is full accessible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24336">issues.joomla.org/tracker/joomla-cms/24336</a>.</sub>

2020-08-03 13:10 UTC, johndeutesfeld commented
I have tested this item :white_check_mark: successfully on 4fd3b6cb6627f17351cef541d98bddf07ef6e7e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24336">issues.joomla.org/tracker/joomla-cms/24336</a>.</sub>

2020-08-03 16:43 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24336">issues.joomla.org/tracker/joomla-cms/24336</a>.</sub>

2020-08-04 05:36 UTC, roland-d commented
@Arpit-24 While checking this issue I think the problem is already fixed without your changes. Can you check?

This is what I see without your changes:
![image](https://user-images.githubusercontent.com/359377/89256770-24567000-d625-11ea-87ca-7c334b3db045.png)

2020-08-04 05:39 UTC, roland-d commented
@Arpit-24 Never mind, I see the issue in fullscreen mode.

2020-08-04 05:42 UTC, roland-d commented
@Arpit-24 Must have been cache because I cannot reproduce the issue again. So can you check if your change is still necessary?

2020-08-04 05:50 UTC, infograf768 commented
I agree with @roland-d 
I cannot reproduce the issue here in 4.0-dev

taking off rtc

2020-08-04 05:50 UTC, infograf768 commented
Moving to discussion<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24336">issues.joomla.org/tracker/joomla-cms/24336</a>.</sub>

2020-08-04 06:09 UTC, infograf768 commented
In fact calendar.js has been modified since April 2019.
I guess this can be closed.

2020-08-04 06:26 UTC, roland-d commented
@Arpit-24 Thank you for your contribution, if this issue still exists, feel free re-open the issue and we can check again.

2020-08-04 06:26 UTC, closed without merging