[4.0] com _CSP Options help link
joomla/joomla-cms pull request #24347
Opened 2019-03-25 20:02 UTC by brianteeman

The string that will generate the correct link for the help button on the CSP Reports Options page was missing

This PR fixes that.

The actual help page doesnt exist yet but now the link exists

2019-03-25 20:41 UTC, Quy commented on administrator/language/en-GB/en-GB.ini
> +JHELP_COMPONENTS_COM_CSP_OPTIONS="Components_CSP_Reports_Options"
The following has `Csp` and with this PR `CSP`. They should be consistent.

`JHELP_COMPONENTS_CSP_REPORTS="Components_Csp_Reports"`

2019-03-26 09:58 UTC, zero-24 commented on administrator/language/en-GB/en-GB.ini
> +JHELP_COMPONENTS_COM_CSP_OPTIONS="Components_CSP_Reports_Options"
```suggestion
JHELP_COMPONENTS_COM_CSP_OPTIONS="Components_Csp_Reports_Options"
```

2019-03-26 09:59 UTC, zero-24 requested changes
As suggested inline we should make it consistent. After that fine for me.

2019-03-26 21:10 UTC, brianteeman commented
changed as requested to be consistent

2019-03-26 21:28 UTC, zero-24 commented
@brianteeman can you please double check? It looks like nothing new has been commited?

2019-03-26 21:38 UTC, zero-24 approved these changes

2019-03-26 21:38 UTC, zero-24 commented
Dine for me thanks @brianteeman

2019-03-26 21:52 UTC, Quy commented
I have tested this item :white_check_mark: successfully on c14f24f9e497435f991b517d48722fd12b6777dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24347">issues.joomla.org/tracker/joomla-cms/24347</a>.</sub>

2019-03-26 22:44 UTC, merged

2019-03-26 22:44 UTC, zero-24 commented
Merged thanks.

2019-03-27 05:26 UTC, brianteeman commented
thanks