defer/async load of reCaptcha external script
joomla/joomla-cms pull request #24403
Opened 2019-03-29 11:09 UTC by acs-ferreira

### Summary of Changes

Load external script with async/defer (as invisble reCaptcha already does):

https://github.com/joomla/joomla-cms/blob/staging/plugins/captcha/recaptcha_invisible/recaptcha_invisible.php#L84

2019-03-29 14:44 UTC, C-Lodder commented
defer **and** async?

Are you sure you know what these attributes do?

2019-03-29 14:49 UTC, acs-ferreira commented
https://www.w3.org/TR/2011/WD-html5-20110525/scripting-1.html#attr-script-async

> The defer attribute may be specified even if the async attribute is specified, to cause legacy Web browsers that only support defer (and not async) to fall back to the defer behavior instead of the synchronous blocking behavior that is the default.

2019-03-29 15:10 UTC, C-Lodder commented
@acs-ferreira Last I heard, `async` has a higher priority than `defer` so it would always be used instead. Then `defer` would be used if the browser didn't support `async`

2019-03-29 15:12 UTC, acs-ferreira commented
@C-Lodder agree. And it seems that W3C also agrees on that! So we both agree 🎉 💃

2019-04-02 10:16 UTC, HLeithner commented
Can you please rebase this PR on j4 branch.

2019-04-14 14:11 UTC, twister65 commented
Please, can you also modify recaptcha invisible (as you have done in this PR):
https://github.com/joomla/joomla-cms/blob/a81ada410a5bf6b700a79d432fc5926146ac9f94/plugins/captcha/recaptcha_invisible/recaptcha_invisible.php#L72
by
`array('async' => true, 'defer' => true)`

and

https://github.com/joomla/joomla-cms/blob/a81ada410a5bf6b700a79d432fc5926146ac9f94/plugins/captcha/recaptcha_invisible/recaptcha_invisible.php#L84
by
`array('async' => true, 'defer' => true)`

2019-04-14 14:51 UTC, twister65 commented
When you want to validate an ajax form with a 3rd-party extension, recaptcha is not loaded at all.
Defers activation of the recaptcha widget to the behavior should resolve that. See:
https://www.drupal.org/project/recaptcha/issues/2493183

2019-04-14 16:18 UTC, twister65 requested changes
> Load external script with async/defer (as invisble reCaptcha already does).

2019-04-14 16:18 UTC, twister65 commented on plugins/captcha/recaptcha/recaptcha.php
> +					'defer' => true,
`'defer' => 'defer',`

2019-04-14 16:18 UTC, twister65 commented on plugins/captcha/recaptcha/recaptcha.php
> +					'async' => true
`'async' => 'async'`

2019-04-14 16:18 UTC, twister65 commented on plugins/captcha/recaptcha/recaptcha.php
> +					'defer' => true,
`'defer' => 'defer',`

2019-04-14 16:18 UTC, twister65 commented on plugins/captcha/recaptcha/recaptcha.php
> +					'async' => true
`'async' => 'async'`

2019-04-14 16:58 UTC, hardik-codes commented
> Can you please rebase this PR on j4 branch.

@HLeithner may I do a separate PR for J4?

2019-04-14 19:48 UTC, HLeithner commented
> > Can you please rebase this PR on j4 branch.
> 
> @HLeithner may I do a separate PR for J4?

yes a new pr would work better for you

2019-04-14 20:24 UTC, brianteeman commented
Pretty sure that the reason for asking if it could be a separate PR was so that this one could also be merged in j3

2019-04-14 20:36 UTC, HLeithner commented
oh, if this is the case no, because commits to j3 get merged to j4 by george at the moment.

2019-04-14 20:39 UTC, brianteeman commented
which is why I didnt understand the request to rebase

2019-04-14 20:42 UTC, hardik-codes commented
@brianteeman @HLeithner is a separate PR needed?

2019-04-14 20:48 UTC, HLeithner commented
I missed that this is a bug fix and not a "feature". @hardik-codes forget the rebase or another pr we only need 2 successful tests and I can merge it.

2019-04-14 20:50 UTC, hardik-codes commented
Ok
Thanks for the info

2019-04-24 06:38 UTC, ghost commented
@acs-ferreira can you please give Test Instructions in first Comment? Maybe we get then Tests.

2019-04-25 03:35 UTC, twister65 requested changes

2019-04-25 03:35 UTC, twister65 commented on plugins/captcha/recaptcha/recaptcha.php
> +			JHtml::_('script', $file, array(), array('defer' => true, 'async' => true));
`JHtml::_('script',` $file, array('async' => 'async', 'defer' => 'defer'));
As:
https://github.com/joomla/joomla-cms/blob/e7582660d8c160bd842a96841757924e9d0016fa/plugins/captcha/recaptcha_invisible/recaptcha_invisible.php#L84

2019-07-20 08:04 UTC, franz-wohlkoenig commented
> @acs-ferreira can you please give Test Instructions in first Comment? Maybe we get then Tests.

closed due the lack of response.

2019-07-20 08:04 UTC, closed without merging