[SQL ] fix field home of  #__template_styles table
joomla/joomla-cms pull request #24595
Opened 2019-04-15 18:50 UTC by alikon

Pull Request for Issue #23188.

### Summary of Changes
respect docs & logic 
https://docs.joomla.org/Tables/template_styles

2019-04-15 18:53 UTC, franz-wohlkoenig commented
@GarryMoveOut please test.

2019-04-15 21:11 UTC, Quy commented on administrator/components/com_admin/sql/updates/mysql/3.9.6-2019-04-15.sql
> +ALTER TABLE `#__template_styles` ADD UNIQUE `idx_home` ( `home` );
Don't make it unique per the installation script.

```CREATE TABLE IF NOT EXISTS `#__template_styles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `template` varchar(50) NOT NULL DEFAULT '',
  `client_id` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `home` char(7) NOT NULL DEFAULT 0,
  `title` varchar(255) NOT NULL DEFAULT '',
  `params` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_template` (`template`),
  KEY `idx_home` (`home`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=9;
```

2019-04-16 06:50 UTC, alikon commented on administrator/components/com_admin/sql/updates/mysql/3.9.6-2019-04-15.sql
> +ALTER TABLE `#__template_styles` ADD UNIQUE `idx_home` ( `home` );
fixed, thanks

2019-04-16 15:37 UTC, Quy commented on installation/sql/mysql/joomla.sql
> +  `home` tinyint(1) NOT NULL DEFAULT 0,
```suggestion
  `home` tinyint(1) unsigned NOT NULL DEFAULT 0,
```

2019-04-16 15:38 UTC, Quy commented on administrator/components/com_admin/sql/updates/mysql/3.9.6-2019-04-15.sql
> +ALTER TABLE `#__template_styles` ADD INDEX `idx_home` ( `home` );
```suggestion
ALTER TABLE `#__template_styles` ADD INDEX `idx_home` (`home`);
```

2019-04-17 01:58 UTC, Quy commented on administrator/components/com_admin/sql/updates/mysql/3.9.6-2019-04-15.sql
> +ALTER TABLE `#__template_styles` MODIFY `home` tinyint(1) unsigned DEFAULT 0;
```suggestion
ALTER TABLE `#__template_styles` MODIFY `home` tinyint(1) unsigned NOT NULL DEFAULT 0;
```

2019-04-17 03:45 UTC, Quy commented
Maybe the following is an issue when using PatchTester.

Run the Database fix the first time:
```
    Database schema version (3.9.3-2019-02-07) does not match CMS version (3.9.6-2019-04-15).
    Table 'nu7mb_template_styles' should not have index 'idx_home'. (From file 3.9.6-2019-04-15.sql.)
    Table 'nu7mb_template_styles' has the wrong type or attributes for column 'home' with type tinyint(1) unsigned. (From file 3.9.6-2019-04-15.sql.)
``
Then the result, but `idx_home` is not created.
```
Table 'nu7mb_template_styles' does not have index 'idx_home'. (From file 3.9.6-2019-04-15.sql.)
```
Run the Database fix again, then `idx_home` is created, however, this message remains:
```
Table 'nu7mb_template_styles' does not have index 'idx_home'. (From file 3.9.6-2019-04-15.sql.)
```

2019-04-17 06:22 UTC, alikon commented
ummm maybe splitting the last "CREATE INDEX"  in a new file .... i'll give it a try

2019-04-18 13:53 UTC, twister65 requested changes

2019-04-18 13:53 UTC, twister65 commented on administrator/components/com_admin/sql/updates/postgresql/3.9.6-2019-04-15.sql
> +DROP INDEX "#__template_styles_idx_home";
This index did not exist in the Joomla PostgreSQL database, I have this error when I apply this patch (I think this is another issue):

> ERROR: relation "gvcms_template_style" does not exist

I suggest this change:
`DROP INDEX IF EXISTS "#__template_styles_idx_home";`

2019-04-18 16:26 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/3.9.6-2019-04-15.sql
> +DROP INDEX "#__template_styles_idx_home";
that index exists https://github.com/joomla/joomla-cms/blob/staging/installation/sql/postgresql/joomla.sql#L1809

2019-04-18 16:58 UTC, twister65 commented on administrator/components/com_admin/sql/updates/postgresql/3.9.6-2019-04-15.sql
> +DROP INDEX "#__template_styles_idx_home";
I can not find `#__template_styles_idx_home` nor `#__template_styles_idx_template` in the update folder:
https://github.com/joomla/joomla-cms/tree/staging/administrator/components/com_admin/sql/updates/postgresql
These indexes are only created in the installation script.

2019-04-18 17:15 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/3.9.6-2019-04-15.sql
> +DROP INDEX "#__template_styles_idx_home";
even then, they are not removed, so we need to drop old index 
did you test with `IF EXISTS` clause on postgresql ?

2019-04-18 17:24 UTC, twister65 commented on administrator/components/com_admin/sql/updates/postgresql/3.9.6-2019-04-15.sql
> +DROP INDEX "#__template_styles_idx_home";
Yes, my suggestion works well, I tested it successfully.

2019-04-18 17:29 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/3.9.6-2019-04-15.sql
> +DROP INDEX "#__template_styles_idx_home";
thanks @twister65

2019-04-18 18:47 UTC, twister65 commented
I have tested this item :white_check_mark: successfully on 2572ae5e0f7290b0fad25a18460f87ec0e787734<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24595">issues.joomla.org/tracker/joomla-cms/24595</a>.</sub>

2019-04-24 06:16 UTC, franz-wohlkoenig commented
@GarryMoveOut please test > https://docs.joomla.org/Testing_Joomla!_patches

2019-04-24 10:06 UTC, GarryMoveOut commented
Sorry for not responding for long time. I didn't have time. I will test soon, maybe this in week.

2019-06-15 14:59 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 1116780337f55822c58e3e7245cb6884c6644c9a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24595">issues.joomla.org/tracker/joomla-cms/24595</a>.</sub>

2019-06-15 14:59 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24595">issues.joomla.org/tracker/joomla-cms/24595</a>.</sub>

2019-06-16 10:23 UTC, merged

2019-06-16 10:23 UTC, HLeithner commented
thx

2019-06-23 12:52 UTC, richard67 commented
This PR had errors which are fixed now in PR #25299 . Please test.