[4.0] Menu Items overview - Filter on Component
joomla/joomla-cms pull request #24665
Opened 2019-04-21 15:09 UTC by pe7er

Pull Request to add a **Component filter** to the "**Menus: Items**" **overview**.
It's PR #23566 re-done for Joomla 4.

### Summary of Changes
This PR adds a Component filter to the menu items overview so that you can filter on specific Components.
**Before Patch**

![menu-component-filter-before](https://user-images.githubusercontent.com/1217850/56471817-54d9c100-6457-11e9-88a4-40cf29119167.png)

### Testing Instructions
- Install the PR.
- Open the Menus: All Menu Items page (Menus > All Menu Items)
- Create a menu item of type Contact - Single Contact
- Click on "Search Tools",
- Select a component (e.g. Contacts)

### Expected result
The list of menu items should be filtered to only show menu items to views of that selected Component.

![menu-component-filter-after](https://user-images.githubusercontent.com/1217850/56471816-54d9c100-6457-11e9-9d3c-8b39210049ab.png)

2019-04-21 15:13 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on ac6b7ec597a93ebf562de143b4d2254fef8f8dac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-04-21 15:14 UTC, pe7er commented
btw: @Tchangue created a similar PR: [4.0] Implementation of feature 'filter menu items by component' #21358

2019-04-21 15:21 UTC, franz-wohlkoenig commented
@pe7er closing #21358?

2019-04-21 15:35 UTC, brianteeman commented
Yes close #21358 as it has clearly been abandoned

2019-04-21 15:36 UTC, Quy commented on administrator/components/com_menus/forms/filter_items.xml
> +			description="COM_MENUS_FILTER_COMPONENT_DESC"
```suggestion
```

2019-04-21 19:31 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 43bb5c1ef5ad57916121ae88cee324567e22a8ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-04-22 06:23 UTC, infograf768 commented
`COM_MENUS_FILTER_COMPONENT_LABEL` ini string missing.

2019-04-22 06:55 UTC, alikon requested changes

2019-04-22 06:55 UTC, alikon commented on administrator/components/com_menus/Model/ItemsModel.php
> +			$query->where('e.name = ' . $db->quote($componentName));
should be full quoted
```suggestion
			$query->where($db->quoteName('e.name') . ' = ' . $db->quote($componentName));
```

2019-04-22 10:00 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on f57ee0e9a7699e39d250d976656ec8ba55a1a0a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-04-22 10:01 UTC, brianteeman commented
> COM_MENUS_FILTER_COMPONENT_LABEL ini string missing.

No it's not - the string didn't need to be added to this PR as it already existed.

![image](https://user-images.githubusercontent.com/1296369/56495536-fc093780-64ed-11e9-8e24-c42787324fb9.png)

2019-04-22 10:09 UTC, richard67 commented
Hmm, I can't find the string "COM_MENUS_FILTER_COMPONENT_LABEL" in any language file.

When searching for "- Select Component -", I find:

> administrator\language\en-GB\en-GB.com_menus.ini:COM_MENUS_OPTION_SELECT_COMPONENT="- Select Component -"
> administrator\language\en-GB\en-GB.com_users.ini:COM_USERS_OPTION_SELECT_COMPONENT="- Select Component -"

2019-04-22 10:12 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on f57ee0e9a7699e39d250d976656ec8ba55a1a0a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-04-22 10:13 UTC, brianteeman commented
oops - my apologies. The label is indeed missing. I need more coffee

2019-04-22 10:14 UTC, richard67 commented
Same for me, more coffee ;-)

2019-04-22 10:14 UTC, richard67 commented
But why did everything look ok then when teesting it?

2019-04-22 10:15 UTC, richard67 commented
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-04-22 10:20 UTC, brianteeman commented
@richard67 View the source. The label is only visible for screen readers

2019-04-22 10:24 UTC, richard67 commented
@brianteeman And what would be the right change? Add the missing text "COM_MENUS_FILTER_COMPONENT_LABEL" to the language file? Or use another already existing text with the same content, i.e. "COM_MENUS_OPTION_SELECT_COMPONENT"?

2019-04-22 14:13 UTC, infograf768 commented
just compare with the other similar filters label in the ini files

2019-04-23 09:50 UTC, pe7er commented
I've made the suggested corrections.
Thank you all for the corrections and for testing!

2019-04-23 16:26 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 7c6176b0e7514d4a0e37970a15520a7240adecd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-04-23 16:34 UTC, franz-wohlkoenig commented
@brianteeman can you please retest?

2019-05-04 15:11 UTC, sanderpotjer commented
I have tested this item :white_check_mark: successfully on 6bad4082cbb54cb6fa642163e6663998c6a3cbac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-05-04 16:24 UTC, franz-wohlkoenig commented
@richard67 can you please retest?

2019-05-05 05:52 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 6bad4082cbb54cb6fa642163e6663998c6a3cbac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-05-05 05:52 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-05-05 07:55 UTC, pe7er commented
Thanks for testing @sanderpotjer @alikon

2019-05-18 08:33 UTC, richard67 commented
@franz-wohlkoenig Any reason why this is not merged? Has 2 good tests, has RTC, drone and appveyor failures seem not to be related to this PR. Only thing is it needs a "rebase" (i.e. merge from 4.0-dev).

2019-05-18 09:07 UTC, infograf768 commented
@richard67 
Please ping @wilsonge when you want to get attention for 4.0 merging.

2019-05-18 09:09 UTC, richard67 commented
@wilsonge Any reason why this is not merged? Has 2 good tests, has RTC, drone and appveyor failures seem not to be related to this PR. Only problem is that "rebase" merge commits kill the test results in the issue tracker. Bul last "rebase" was clean, so test results are still valid.

2019-05-18 09:11 UTC, infograf768 commented
Looks like we have an issue with drone. Informed maintainers.

2019-05-18 09:12 UTC, richard67 commented
@infograf768 Thanks, and thanks for helping me with pinging the right people.

2019-05-18 10:43 UTC, franz-wohlkoenig commented
@richard67 mergin j3 is @HLeithner j4 @wilsonge. i'm only managing at a low level ;-)

2019-05-18 10:49 UTC, richard67 commented
@franz-wohlkoenig Yes, JM meanwhile englighted me that I was pinging the wrong people.

2019-05-19 06:40 UTC, roland-d commented on administrator/components/com_menus/Model/ItemsModel.php
> +				'e.name', 'componentName'
Please switch these two arguments as all other arguments have name and then column name.

2019-05-19 06:40 UTC, roland-d commented on administrator/components/com_menus/forms/filter_items.xml
> +			type="componentscategory"
Please use the namespaced name here `ComponentsCategory`

2019-05-19 06:45 UTC, roland-d commented
@pe7er I have removed the RTC because I am failing to make this work.

The component filter works fine for me on the `All Menu Items` but when I go to the `Main menu`, the filter won't be applied nor will it stick as selected.

This works:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/359377/57978650-0990df00-7a12-11e9-86bf-4252dd9bccfe.png">

This `does not` work:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/359377/57978660-20373600-7a12-11e9-9eb4-50aa81f2aa6e.png">

As you can see my selection is not there.

Another issue is, when I do select a filter on the `All Menu Items` and I go to `Main Menu`, the filter cannot be reset. The screen will be stuck to this:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/359377/57978697-4c52b700-7a12-11e9-94bd-51f62cead61e.png">

Finally, I am missing this code in the `populateState` function:
```
$componentName = $this->getUserStateFromRequest($this->context . '.filter.componentName', 'filter_componentName');
		$this->setState('filter.componentName', $componentName);
```

2019-05-19 06:46 UTC, infograf768 commented on administrator/components/com_menus/forms/filter_items.xml
> +			type="componentscategory"
Sorry, I see no reason why. We do not use namespace for type in any xml in j4.
We already have 2 places where `type="componentscategory"` is used in core.

2019-05-19 06:47 UTC, franz-wohlkoenig commented
@roland-d RTC is set.

2019-05-19 06:48 UTC, roland-d commented on administrator/components/com_menus/forms/filter_items.xml
> +			type="componentscategory"
The reason why is we should start being consistent. Just because in another place it is not yet done, we should not start doing it somewhere else. Otherwise we might as well stop cleaning code everywhere.

2019-05-19 06:49 UTC, roland-d commented
I have tested this item :red_circle: unsuccessfully on bb364f8a394915f3ebfb85a0860711cac83ee1f3<br /><br />The filter is not working on all pages. See my comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-05-19 06:49 UTC, infograf768 commented
Testing now

2019-05-19 06:50 UTC, roland-d commented
@franz-wohlkoenig It was the bot, I now marked my test as unsuccessful, hopefully that will stop it :)

2019-05-19 06:50 UTC, roland-d commented
I am powerless to the bot 😄

2019-05-19 06:57 UTC, infograf768 commented
Agree with @roland-d findings. Same errors here.

2019-05-19 07:12 UTC, alikon commented
back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-05-19 08:08 UTC, brianteeman commented
@roland-d I haven't tested it as I am still traveling but won't namespacing the XML type cause issues with the way that custom elements are used?

2019-05-19 08:48 UTC, roland-d commented
It is not about the file itself but just the field name. Perhaps I should have used the word camel case instead of namespace as that seems to be a loaded word :stuck_out_tongue_winking_eye:

2019-10-19 09:27 UTC, uthorat commented
I have tested this item :white_check_mark: successfully on bb364f8a394915f3ebfb85a0860711cac83ee1f3<br /><br />Able to select the menu from all menu & main menu section as per component selection Also able to reset the filters.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-10-19 10:59 UTC, Neppert commented
I have tested this item :red_circle: unsuccessfully on bb364f8a394915f3ebfb85a0860711cac83ee1f3<br /><br />The result was not quite negative, because in the test installation on joomlapbf.com no component was found connected to the menu data - so there could not be displayed a data list of components to filter. I just saw a void input field.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-10-19 11:04 UTC, deepa-g commented
I have tested this item :red_circle: unsuccessfully on bb364f8a394915f3ebfb85a0860711cac83ee1f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-10-19 12:05 UTC, nadjak77 commented
I have tested this item :white_check_mark: successfully on bb364f8a394915f3ebfb85a0860711cac83ee1f3<br /><br />works like subscriped<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-10-19 12:06 UTC, neotrendch commented
I have tested this item :red_circle: unsuccessfully on bb364f8a394915f3ebfb85a0860711cac83ee1f3<br /><br />tested unsuccessfully, 5th field is not a dropdown, but a text input field<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-10-19 12:10 UTC, adiheutschi commented
I have tested this item :red_circle: unsuccessfully on bb364f8a394915f3ebfb85a0860711cac83ee1f3<br /><br />For me, only a text box appears

Printscreen

[Printscreen](https://prnt.sc/plgk7w "https://prnt.sc/plgk7w")

Setting	Value
PHP Built On	Linux server2.adiheutschi.ch 3.10.0-962.3.2.lve1.5.24.9.el7.x86_64 #1 SMP Wed Feb 13 08:24:50 EST 2019 x86_64
Database Type	mysql
Database Version	10.2.27-MariaDB
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.3.10
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-10-19 12:11 UTC, idefax commented
I have tested this item :red_circle: unsuccessfully on bb364f8a394915f3ebfb85a0860711cac83ee1f3<br /><br />It does not work. It adds a textfield with no value instead of a dropdown.

![Screenshot](https://prnt.sc/plgkjq "Screenshot")


PHP Version 	7.3.8
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24665">issues.joomla.org/tracker/joomla-cms/24665</a>.</sub>

2019-10-19 12:24 UTC, berndkohlen commented
Does not work with "Contacts". Needs the component name "com_contact".
![grafik](https://user-images.githubusercontent.com/56753499/67144863-142ef900-f27c-11e9-8f70-6ffa2f5609da.png)

2020-04-27 12:27 UTC, pe7er commented on administrator/components/com_menus/Model/ItemsModel.php
> +				'e.name', 'componentName'
thanks

2020-04-27 12:28 UTC, pe7er commented on administrator/components/com_menus/forms/filter_items.xml
> +			type="componentscategory"
done, thanks!

2020-04-27 12:48 UTC, pe7er commented
Thank you all for testing & your suggestions for improvements!

As I did not have the branch for this PR in my local git repo (hence it says "from unknown repository"),
I redid the PR with the suggested improvements.

New PR: #28832

I'm closing this one...

2020-04-27 12:48 UTC, closed without merging