Add Count items to Tags Overview - J4
joomla/joomla-cms pull request #24663
Opened 2019-04-21 14:42 UTC by pe7er

Pull Request to **improve** the **Tags** component by adding a **new "Tagged Items" column** that shows a **counter** to offer an insight in how often certain tags are used. The column is sortable so you can easily get an overview about the most or less used tags.
It's PR https://github.com/joomla/joomla-cms/pull/23562 re-done for Joomla 4. 

### Summary of Changes
In the Back-end under Components > Tags you'll see an overview of all created Tags.
However, you don't have any information which tags are actually used, and how often.

![tagged-items-before](https://user-images.githubusercontent.com/1217850/56471497-af711e00-6453-11e9-9708-8b31b41131f7.png)

### Testing Instructions
-  Add some tags to some items (Articles or other items).
-  Check the Components > Tags overview
-  Install the patch
-  Check again the Components > Tags overview

### Expected result
A new column "**Tagged Items**" is available. You can **click** on the "Tagged Items" header **to order** the column. You can select the order also via the "Sort Table By:" dropdown on the top right.

![tagged-items-after](https://user-images.githubusercontent.com/1217850/56471498-af711e00-6453-11e9-9331-d2018c435b53.png)

2019-04-21 14:56 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 12f4d7b2a8e897fe2424f2ffaff1c95ac560ea7e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24663">issues.joomla.org/tracker/joomla-cms/24663</a>.</sub>

2019-04-21 15:00 UTC, ghazal commented
I have tested this item :white_check_mark: successfully on 12f4d7b2a8e897fe2424f2ffaff1c95ac560ea7e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24663">issues.joomla.org/tracker/joomla-cms/24663</a>.</sub>

2019-04-21 15:01 UTC, franz-wohlkoenig commented
Status "Ready To Commit".

2019-04-21 17:29 UTC, wilsonge commented on administrator/components/com_tags/Model/TagsModel.php
> +		$query->select('(' . $subQueryCountTaggedItems->__toString() . ') AS countTaggedItems');
You shouldn't ever call the magic method `__toString()`. Just typehint it with `(string) $subQueryCountTaggedItems`

2019-04-21 19:09 UTC, pe7er commented on administrator/components/com_tags/Model/TagsModel.php
> +		$query->select('(' . $subQueryCountTaggedItems->__toString() . ') AS countTaggedItems');
@wilsonge Ok, thanks for the warning. I'll correct it!

2019-04-21 19:13 UTC, pe7er commented
@wilsonge Could you please check if I fixed " magic method __toString() to typehint (string)" correctly in 
administrator/components/com_tags/Model/TagsModel.php ?

2019-04-21 19:18 UTC, pe7er commented
@brianteeman + @ghazal Thanks for testing!

2019-04-21 19:25 UTC, zero-24 requested changes

2019-04-21 19:25 UTC, zero-24 commented on administrator/components/com_tags/tmpl/tags/default.php
> +                        <th scope="col" style="width:10%" class="d-none d-md-table-cell text-center">
spaces to tabs please

2019-04-21 19:25 UTC, zero-24 commented on administrator/components/com_tags/tmpl/tags/default.php
> +                        <td class="small d-none d-md-table-cell text-center">
spaces to tabs please

2019-04-21 20:52 UTC, pe7er commented on administrator/components/com_tags/tmpl/tags/default.php
> +                        <th scope="col" style="width:10%" class="d-none d-md-table-cell text-center">
@zero-24 Sorry... I fixed it!

2019-04-21 20:52 UTC, pe7er commented on administrator/components/com_tags/tmpl/tags/default.php
> +                        <td class="small d-none d-md-table-cell text-center">
Fixed!

2019-04-21 21:37 UTC, zero-24 approved these changes

2019-04-22 08:09 UTC, ghazal commented
I have tested this item :white_check_mark: successfully on 9f32ae16191069a224b212da04612490c6d9f9c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24663">issues.joomla.org/tracker/joomla-cms/24663</a>.</sub>

2019-04-22 11:18 UTC, wilsonge commented
Looks better!

2019-05-29 20:12 UTC, roland-d commented on administrator/components/com_tags/Model/TagsModel.php
> +			->where($db->quoteName('tag_map.tag_id') . '= ' . $db->quoteName('a.id'));
Space before `=`

2019-05-29 20:12 UTC, roland-d commented on administrator/components/com_tags/Model/TagsModel.php
> +		$query->select('(' . (string) $subQueryCountTaggedItems . ') AS countTaggedItems');
Quote name `countTaggedItems`

2019-06-08 00:16 UTC, Quy commented on administrator/components/com_tags/Model/TagsModel.php
> +			->where($db->quoteName('tag_map.tag_id') . '= ' . $db->quoteName('a.id'));
```suggestion
			->where($db->quoteName('tag_map.tag_id') . ' = ' . $db->quoteName('a.id'));
```

2019-06-14 18:50 UTC, roland-d commented
Removing RTC until issues are resolved

2019-10-19 09:09 UTC, pranotiTechjoomla commented
I have tested this item :white_check_mark: successfully on 9c9a8de54744a482d5e61ef782635495ee8599d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24663">issues.joomla.org/tracker/joomla-cms/24663</a>.</sub>

2019-10-19 12:19 UTC, ttplpoojak commented
I have tested this item :white_check_mark: successfully on d795774844def2d2e6b500b9a866138e6f0f0a0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24663">issues.joomla.org/tracker/joomla-cms/24663</a>.</sub>

2019-10-19 14:17 UTC, joeykrop commented
I have tested this item :white_check_mark: successfully on d795774844def2d2e6b500b9a866138e6f0f0a0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24663">issues.joomla.org/tracker/joomla-cms/24663</a>.</sub>

2019-10-20 14:43 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24663">issues.joomla.org/tracker/joomla-cms/24663</a>.</sub>

2019-10-20 14:44 UTC, Quy commented
There are coding style changes.

2019-10-23 12:49 UTC, zero-24 commented
Back to Pending until @pe7er found to time to fix the issues mention above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24663">issues.joomla.org/tracker/joomla-cms/24663</a>.</sub>

2020-04-27 12:18 UTC, pe7er commented
Thank you all for testing & your suggestions for improvements!
 
As I did not have the branch for this PR in my local git repo (hence it says "from unknown repository"),
I redid the PR with the suggested improvements.

New PR: https://github.com/joomla/joomla-cms/pull/28831

I'm closing this one...

2020-04-27 12:18 UTC, closed without merging