[4.0] Module 'Articles - Newsflash' - exclude current article
joomla/joomla-cms pull request #24672
Opened 2019-04-21 20:31 UTC by pe7er

This PR adds in the **Module Articles - Newsflash** (mod_articles_news) an option exclude the current article to filter the current article from displaying in the newsflash module..
It's PR #23575 "Exclude current article"  re-done for Joomla 4. 

### Summary of Changes
The **Module Articles - Newsflash** can display the same article as the article currently displayed on the page.

- This  PR adds an option in the Latest News Module to exclude the current article.
- The option is OFF by default (so the current behavior before installing the patch is default)
- It also checks for com_content being active to prevent that other components that use an "id" might interfere with the Latest News Module output.

### Testing Instructions
- Create a **Module Articles - Newsflash**, choose Category :Blog", assign the module to position "sidebar-right" and assign the module to display "On all pages". 
- Go to a page that displays an article, for example index.php/blog/3-welcome-to-your-blog
- Refresh the page a couple of times to see that the Newsflash Module might display the same article text.

![mod_articles_newsflash-before-frontend](https://user-images.githubusercontent.com/1217850/56475143-a2b8ee00-6484-11e9-9ca2-4e6a70100ba3.png)

### Expected result
Before installing this PR, the following options are available:

![mod_articles_newsflash-before-backend](https://user-images.githubusercontent.com/1217850/56475140-a2b8ee00-6484-11e9-9d36-fda63e9a2645.png)

After installing this PR, there's a new option available: "Exclude current Article" that is set to "No" by default.

![mod_articles_newsflash-after-no](https://user-images.githubusercontent.com/1217850/56475142-a2b8ee00-6484-11e9-8ed6-daf078aaa75a.png)

After configuring the "Exclude current Article" to "Yes", the module should not display the same article anymore.

![mod_articles_newsflash-after-yes](https://user-images.githubusercontent.com/1217850/56475141-a2b8ee00-6484-11e9-843d-da4e1227e8a4.png)

2019-04-21 21:00 UTC, brianteeman requested changes

2019-04-21 21:00 UTC, brianteeman commented on language/en-GB/en-GB.mod_articles_news.ini
> +MOD_ARTICLES_NEWS_FIELD_EXCLUDE_CURRENT_DESC="Exclude the current article from displaying in the module."
Please delete the desc - the label is obvious what it does

2019-04-21 21:00 UTC, brianteeman commented on language/en-GB/en-GB.mod_articles_news.ini
> +MOD_ARTICLES_NEWS_FIELD_EXCLUDE_CURRENT_LABEL="Exclude current Article"
As it's a label please capitalise all the words

2019-04-21 21:00 UTC, brianteeman commented on modules/mod_articles_news/mod_articles_news.xml
> +					description="MOD_ARTICLES_NEWS_FIELD_EXCLUDE_CURRENT_DESC"
As commented before you don't need this

2019-04-21 21:00 UTC, brianteeman commented on modules/mod_articles_news/mod_articles_news.xml
> +					class="btn-group btn-group-yesno"
change this to class="switcher" to get the much nicer switcher for the field

2019-04-21 21:00 UTC, brianteeman commented on modules/mod_articles_news/mod_articles_news.xml
> +					<option value="1">JYES</option>
When you apply the switcher option please reverse the order here so that jyes will get the green

2019-04-22 06:42 UTC, HLeithner commented on modules/mod_articles_news/Helper/ArticlesNewsHelper.php
> +			$model->setState('filter.article_id', $app->input->get('id'));
Please add the 'UINT' filter

2019-04-22 06:43 UTC, HLeithner commented on modules/mod_articles_news/Helper/ArticlesNewsHelper.php
> +		if ($app->input->get('option') === 'com_content' && $params->get('exclude_current', false))
I would switch the order for logical reasons, is active and then the external dependencies.

2019-04-23 09:57 UTC, pe7er commented on modules/mod_articles_news/mod_articles_news.xml
> +					class="btn-group btn-group-yesno"
Thanks! I reused my code for the 3.9 version. I did not know this new class. Looks much better now...

2019-04-23 09:59 UTC, pe7er commented on modules/mod_articles_news/mod_articles_news.xml
> +					<option value="1">JYES</option>
thanks!

2019-04-23 10:07 UTC, pe7er commented on modules/mod_articles_news/Helper/ArticlesNewsHelper.php
> +			$model->setState('filter.article_id', $app->input->get('id'));
Ok!

2019-04-23 10:08 UTC, pe7er commented on modules/mod_articles_news/Helper/ArticlesNewsHelper.php
> +		if ($app->input->get('option') === 'com_content' && $params->get('exclude_current', false))
Thanks! Good point!

2019-04-23 10:13 UTC, pe7er commented
Thanks for your improvements @brianteeman and @HLeithner 
I've added them to this PR, and updated it also with the 4.0-dev branch

2019-04-24 05:37 UTC, SharkyKZ commented on modules/mod_articles_news/Helper/ArticlesNewsHelper.php
> +		// Filter by tag
Remove this comment or replace it with comment from line 93?

2019-04-24 05:39 UTC, SharkyKZ commented on modules/mod_articles_news/Helper/ArticlesNewsHelper.php
> +		if ($params->get('exclude_current', false) && $app->input->get('option') === 'com_content')
Also add a check for article view. Otherwise, an article could be excluded on category view if it has the same ID as the category.

2019-04-24 05:42 UTC, SharkyKZ commented on modules/mod_articles_news/mod_articles_news.xml
> +					default="1"
Should this by enabled by default? In the code it's disabled https://github.com/joomla/joomla-cms/pull/24672/files#diff-a39c20f4b8d196b2b4744e1f6a46e657R91

2019-04-24 09:49 UTC, pe7er commented on modules/mod_articles_news/Helper/ArticlesNewsHelper.php
> +		// Filter by tag
yes, thanks. I'll do so

2019-04-24 09:55 UTC, pe7er commented on modules/mod_articles_news/mod_articles_news.xml
> +					default="1"
Yes, you are right.
I'll change the default for exclude_current to: 
```params->get('exclude_current', true)```

2019-04-24 09:55 UTC, infograf768 commented
In certain conditions (specific category with only one item set to not display), the module will display its title without any articles.

2019-04-24 10:33 UTC, pe7er commented on modules/mod_articles_news/Helper/ArticlesNewsHelper.php
> +		if ($params->get('exclude_current', false) && $app->input->get('option') === 'com_content')
@SharkyKZ Yes, thank you

2019-04-24 10:36 UTC, pe7er commented
Thanks for your improvements @SharkyKZ 

@infograf768 Thanks, you are right. I might write another patch for that...

2019-05-04 13:09 UTC, sanderpotjer commented
I have tested this item :white_check_mark: successfully on afd2862c8fe4cbc6a2750e8d2f6cf678f98a3cb4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24672">issues.joomla.org/tracker/joomla-cms/24672</a>.</sub>

2019-07-13 09:42 UTC, tonypartridge commented
I have tested this item :white_check_mark: successfully on afd2862c8fe4cbc6a2750e8d2f6cf678f98a3cb4<br /><br />Great addition, thanks pe7er! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24672">issues.joomla.org/tracker/joomla-cms/24672</a>.</sub>

2019-07-13 11:47 UTC, franz-wohlkoenig commented
Status "Ready To Commit".

2019-07-15 08:05 UTC, merged

2019-07-15 08:05 UTC, wilsonge commented
Nice touch! Thanks!