[4.0] com_action_logs options
joomla/joomla-cms pull request #24671
Opened 2019-04-21 19:29 UTC by brianteeman

Simple pr to change the IP logging option to use the switcher instead of the old style yes/no

### Before
![image](https://user-images.githubusercontent.com/1296369/56474623-1d2d4200-6474-11e9-9169-10c11c4a6623.png)

### After
![image](https://user-images.githubusercontent.com/1296369/56474615-10a8e980-6474-11e9-950d-b8161c87c1d1.png)

2019-04-21 19:35 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on cbe44c3e7743fb7a51d29e66030037a86c6bb6c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24671">issues.joomla.org/tracker/joomla-cms/24671</a>.</sub>

2019-04-22 04:00 UTC, Quy commented
I have tested this item :white_check_mark: successfully on cbe44c3e7743fb7a51d29e66030037a86c6bb6c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24671">issues.joomla.org/tracker/joomla-cms/24671</a>.</sub>

2019-04-22 04:00 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24671">issues.joomla.org/tracker/joomla-cms/24671</a>.</sub>

2019-04-22 09:28 UTC, wilsonge commented on administrator/components/com_actionlogs/config.xml
> -			filter="integer"
We still should have the filter here

2019-04-22 09:34 UTC, brianteeman commented on administrator/components/com_actionlogs/config.xml
> -			filter="integer"
Why? Please educate me

2019-04-22 09:57 UTC, brianteeman commented on administrator/components/com_actionlogs/config.xml
> -			filter="integer"
I don't understand the need if there is only two options, but will happily put it back if required

2019-04-22 10:54 UTC, wilsonge commented on administrator/components/com_actionlogs/config.xml
> -			filter="integer"
It’s required. Ideally pretty much all the xml fields should have basic validation. It helps prevent against anyone submitting dodgy data (as we move towards web services this becomes higher risk than when it was simply the admin interface)

2019-04-22 11:12 UTC, brianteeman commented on administrator/components/com_actionlogs/config.xml
> -			filter="integer"
Ok thanks

2019-04-22 12:20 UTC, mbabker commented on administrator/components/com_actionlogs/config.xml
> -			filter="integer"
The filters will also force data to be saved in the correct type, here you actually want to save an integer and not a numeric string (well actually you'd want it to be boolean true/false but somewhere between the Form API and MVC library things just blow up so integer's second best choice) so the integer filter will both make the data the appropriate type and offer some basic protection against someone trying something funny with either DOM manipulation or a web services API.

2019-04-22 12:25 UTC, richard67 requested changes

2019-04-22 12:25 UTC, richard67 commented on administrator/components/com_actionlogs/config.xml
> +		       >
Line 12 use tabs before `>`.

2019-04-22 12:29 UTC, brianteeman commented on administrator/components/com_actionlogs/config.xml
> -			filter="integer"
thanks

2019-04-22 12:34 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 02c78e228c12790790ac2db164cd061637cbfa0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24671">issues.joomla.org/tracker/joomla-cms/24671</a>.</sub>

2019-04-22 13:10 UTC, richard67 approved these changes

2019-04-22 22:15 UTC, merged

2019-04-22 22:15 UTC, wilsonge commented
Thanks!

2019-04-22 22:27 UTC, brianteeman commented
Thanks