batch copy permission on module
joomla/joomla-cms pull request #24737
Opened 2019-04-27 10:10 UTC by alikon

follow up #24730 for module batch copy.

### Summary of Changes
let's copy permission too

### Testing Instructions

-   Create/edit a module.
-   Go to its permission tab and make a change. (e.g registered->allow creating)
-   Go to Batch and Copy it somewhere else.

### Expected result
the permission are copyied too

### Actual result
permission are not copied

2019-04-27 10:15 UTC, richard67 requested changes

2019-04-27 10:15 UTC, richard67 commented on administrator/components/com_modules/models/module.php
> +					 ' ON ' . $db->quoteName('s.id') . ' = ' . $oldAssetId
Drone says there is a space instead of a tab in line 212.

2019-04-27 10:35 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 8f074f3c2dc0a5d4badbf148470e6579b1f2cc3b<br /><br />I've tested with 2 modules which had differenc ACL modifications.
Both modules copied together in 1 batch action.
Before patch: Copied modules have ACL like in new modules.
After patch: Each of the module copies has ACL like the particular copy source module.

Drone error (javascript) seems not to be related to this PR. Code style is ok.

@HLeithner and @wilsonge Release leads please check as also with PR #24730 and PR #24736 if this is a bug fix so it goes into 3.9.next or a new feature for 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24737">issues.joomla.org/tracker/joomla-cms/24737</a>.</sub>

2019-04-27 10:36 UTC, alikon commented on administrator/components/com_modules/models/module.php
> +					 ' ON ' . $db->quoteName('s.id') . ' = ' . $oldAssetId
should be fixed now
now drone complain about javascript :no_good_man:

2019-04-27 10:38 UTC, richard67 approved these changes

2019-04-27 10:39 UTC, richard67 commented on administrator/components/com_modules/models/module.php
> +					 ' ON ' . $db->quoteName('s.id') . ' = ' . $oldAssetId
Drone error now seems to me to be not to be related to this PR.

2019-04-27 11:16 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 8f074f3c2dc0a5d4badbf148470e6579b1f2cc3b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24737">issues.joomla.org/tracker/joomla-cms/24737</a>.</sub>

2019-04-27 11:22 UTC, franz-wohlkoenig commented
Status "Ready To Commit".

2019-04-27 17:20 UTC, infograf768 commented
relaunch drone

2019-05-18 08:40 UTC, richard67 commented
@franz-wohlkoenig Any reason why this is not merged? Has 2 good tests, has RTC. Only thing is it needs a "rebase" (i.e. merge from staging).

2019-05-18 09:09 UTC, infograf768 commented
Rebased. @HLeithner please decide if merging in 3.9

2019-05-18 12:24 UTC, merged

2023-04-17 01:03 UTC, getimo commented
Any progress on that?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24737">issues.joomla.org/tracker/joomla-cms/24737</a>.</sub>