[4.0] Remove dependency on phpunit/dbunit
joomla/joomla-cms pull request #24873
Opened 2019-05-12 21:50 UTC by Hackwar

I don't see where this is used anymore, thus removing this. Also because it is not maintained anymore. If the tests don't fail, we can remove this.

2019-05-12 23:28 UTC, wilsonge commented on composer.lock
> -        {
You've removed system tests and api tests here...

2019-05-12 23:30 UTC, wilsonge commented
We aren't using them in the limited tests here. We are using it extensively in the integration tests https://github.com/joomla/test-integration

2019-05-12 23:30 UTC, wilsonge requested changes
Per comment on composer.lock

2019-05-13 05:14 UTC, Hackwar commented on composer.lock
> -        {
Yes, because we moved them to the main repo in #24808.

2019-05-13 05:18 UTC, Hackwar commented
We might be using them in the integration tests, but we are not using the integration tests. And since the integration tests are completely and hopelessly broken in 4.0 and need a complete rewrite, we might as well find a better solution then or add it back in. But right now this is just dead code and I'd rather prevent all the questions about "It says we shouldn't use it. Should I remove it?" and the additional download time (as little as that may be).

2019-05-13 09:11 UTC, wilsonge commented
That's fine. I have no issue with that. But you still need to fix the composer.lock file :)

2019-05-13 09:11 UTC, merged

2019-05-13 09:12 UTC, wilsonge commented
I'm aware that we don't need them here. I'm just saying why they were in the file