Move changelog JS to it's own file
joomla/joomla-cms pull request #24890
Opened 2019-05-13 18:12 UTC by roland-d

Pull Request for Issue #24849

Here goes my first try at some modular JS

### Summary of Changes
Fixed the missing modal IDs in the link
Moved all changelog related JavaScript to it's own file

### Testing Instructions
1. Apply this pull request
2. Run npm run build:js
3. Install the test extension from https://github.com/roland-d/component_joomla/releases/tag/v0.0.2
4. Go to Manage
5. Filter the list on List of Students
6. Click on the version number 0.0.2
7. A modal shows up with the changelog as shown below under Manage View
8. Go to Update
9. Click on Find Updates
10. The update is shown and click on the Changelog button
11. A modal shows up with the changelog as shown below under Update View

### Expected result
There is no JavaScript error in Update view
Specific changelog JavaScript is used

### Actual result
There is a JavaScript error in Update view
Core Joomla JavaScript is used

### Documentation Changes Required
None

Please review:
@euismod2336 @C-Lodder

2019-05-14 08:29 UTC, wilsonge approved these changes
Looks good to me.

2019-05-14 09:06 UTC, C-Lodder requested changes

2019-05-14 09:06 UTC, C-Lodder commented on build/media_source/com_installer/js/changelog.es6.js
> +        document.querySelectorAll(`#changelogModal${extensionId} .modal-body`)[0].innerHTML = result.data;
No need to use `querySelectorAll` here. Just do:

```
document.querySelector(`#changelogModal${extensionId} .modal-body`).innerHTML = result.data;
```

2019-05-14 09:12 UTC, roland-d commented on build/media_source/com_installer/js/changelog.es6.js
> +        document.querySelectorAll(`#changelogModal${extensionId} .modal-body`)[0].innerHTML = result.data;
Thanks. Done.

2019-05-14 10:15 UTC, euismod2336 commented on build/media_source/com_installer/js/changelog.es6.js
> +        const result = JSON.parse(response);
Please add some error handling, to check if the response is what we expect it to be

2019-05-14 10:16 UTC, euismod2336 commented on build/media_source/com_installer/js/changelog.es6.js
> +    });
We don't need handling in case of status code != 200?

2019-05-14 12:31 UTC, ghazal commented
I have tested this item :white_check_mark: successfully on 50951c0a76357925169ea21a11dfeb04fd0bfc06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24890">issues.joomla.org/tracker/joomla-cms/24890</a>.</sub>

2019-05-17 09:00 UTC, roland-d commented on build/media_source/com_installer/js/changelog.es6.js
> +        const result = JSON.parse(response);
Done

2019-05-17 09:00 UTC, roland-d commented on build/media_source/com_installer/js/changelog.es6.js
> +    });
Done

2019-05-17 14:48 UTC, euismod2336 commented
I have tested this item :white_check_mark: successfully on 3672c3ac4d59f2d23d843491143f6ac464d5f02f<br /><br />works as advertised<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24890">issues.joomla.org/tracker/joomla-cms/24890</a>.</sub>

2019-05-17 14:48 UTC, euismod2336 commented
thnx @roland-d

2019-05-18 12:55 UTC, roland-d commented
@ghazal Could you please test again? Thank you.

2019-05-18 18:30 UTC, ghazal commented
I have tested this item :white_check_mark: successfully on c31d4af67e814f6595650e745578c893f449c459<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24890">issues.joomla.org/tracker/joomla-cms/24890</a>.</sub>

2019-05-18 19:12 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24890">issues.joomla.org/tracker/joomla-cms/24890</a>.</sub>

2019-05-30 12:13 UTC, roland-d commented
pinging @wilsonge for merge

2019-05-30 12:16 UTC, merged

2019-05-30 12:16 UTC, HLeithner commented
thx

2019-05-30 12:16 UTC, roland-d commented
Thank you