[imp] Throw exception instead of returning false when uploading file
joomla/joomla-cms pull request #24894
Opened 2019-05-14 09:16 UTC by olleharstedt

Pull Request for Issue #24887.

### Summary of Changes

Throw exception instead of returning false.

### Testing Instructions

### Expected result

### Actual result

### Documentation Changes Required

2019-05-14 09:18 UTC, olleharstedt commented
Two issues:

1) All exceptions have the same error code. If you want, I can make the error code different for each exception, making it possible for client code to react differently.

2) This change should be applied to ALL methods in the File class.

2019-05-14 09:23 UTC, HLeithner requested changes
Does Joomla core handle these exception? If not please also adapt core files.

2019-05-14 09:23 UTC, HLeithner commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
Why don't you use the language constant?
-1 is not a good value for an error code, it its a user error it should be 4xx and if its a server error it should be 5xx

2019-05-14 09:23 UTC, HLeithner commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException('JFile::upload: ' . $stream->getError(), -1);
Same as above

2019-05-14 09:23 UTC, HLeithner commented on libraries/src/Filesystem/File.php
> +					throw new \RuntimeException(Text::sprintf('Warning: Failed to move file: %1$s to %2$s', $src, $dest), -1);
Same as above.

2019-05-14 09:23 UTC, HLeithner commented on libraries/src/Filesystem/File.php
> +						throw new \RuntimeException('Warning: Failed to change file permissions!', -1);
Language constant and error code

2019-05-14 09:23 UTC, HLeithner commented on libraries/src/Filesystem/File.php
> +					throw new \RuntimeException(Text::sprintf('Warning: Failed to move file: %1$s to %2$s', $src, $dest), -1);
Langeuage constant and error code

2019-05-14 09:30 UTC, olleharstedt commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
I compare with the Folder::copy, where all exception uses hard-coded language and -1 as error code. Is that wrong?

2019-05-14 09:31 UTC, olleharstedt commented
> Does Joomla core handle these exception? If not please also adapt core files.

Not sure what you mean here. Adapt how? With try-catch blocks?

2019-05-14 09:36 UTC, HLeithner commented
> > Does Joomla core handle these exception? If not please also adapt core files.
> 
> Not sure what you mean here. Adapt how? With try-catch blocks?

It depends on the case if it suites to catch the exception and handle the return better then do nothing then yes.

2019-05-14 09:38 UTC, HLeithner commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
In my opinion yes, we have language strings and should use them. 
Using different return codes make sense too

2019-05-14 09:45 UTC, olleharstedt commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
OK, will fix.

2019-05-14 09:45 UTC, infograf768 commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
> I compared with the Folder::copy, where all exceptions use hard-coded language

Alas yes. One could argue we have no lang strings for these. At least we have them in the case here.
Would be a good idea imho to create the strings and use them for Folder::Copy

2019-05-14 09:57 UTC, olleharstedt commented
> It depends on the case if it suites to catch the exception and handle the return better then do nothing then yes.

I have honestly no idea on which change would be accepted here: https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Installer/Installer.php#L1718

Is there a try-catch at the top? Should I catch it and ignore the error message in the exception? Should the installer be changed also to throw exceptions at failure instead of returning false?

2019-05-14 12:15 UTC, mbabker commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
Exceptions generally should not have translated text.  Exception messages can range from simple notices (i.e. ACL failures) to messages which are technical in nature, which if not properly translated would make troubleshooting that Exception more complicated because its message was lost in translation.

In a properly built application, the Exceptions would be caught and if need be transformed into something else that the end user would see.  That application is not Joomla, therefore the sub-par practice of translated Exception messages is used instead.

2019-05-14 12:17 UTC, mbabker commented
Instead of consistently re-using the SPL Exceptions, core really needs to get better about introducing Exception subclasses that makes it easier to catch specific error types.  A try/catch around a RuntimeException is honestly too vague because so many of the SPL Exceptions are subclasses of that, as well as many of the (albeit limited) Joomla Exception classes.

2019-05-14 12:20 UTC, HLeithner commented
> Instead of consistently re-using the SPL Exceptions, core really needs to get better about introducing Exception subclasses that makes it easier to catch specific error types. A try/catch around a RuntimeException is honestly too vague because so many of the SPL Exceptions are subclasses of that, as well as many of the (albeit limited) Joomla Exception classes.

iirc many Joomla specific exception classes get removed lately ymmv

2019-05-14 12:22 UTC, mbabker commented
Not that I'm aware of?  JException was removed, maybe the database exceptions since the Framework package is in use (which also has its own Exception subclasses), that's all I can think of off hand.

2019-05-14 12:23 UTC, HLeithner commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
> Exceptions generally should not have translated text. Exception messages can range from simple notices (i.e. ACL failures) to messages which are technical in nature, which if not properly translated would make troubleshooting that Exception more complicated because its message was lost in translation.
> 
> In a properly built application, the Exceptions would be caught and if need be transformed into something else that the end user would see. That application is not Joomla, therefore the sub-par practice of translated Exception messages is used instead.

Not translating them or at least return the language string would result in much more work for each case this method is used, because you have to catch each error and decide if we should show it to the user or not and if we show it to the user we have to translate the error message.

In this case the catch block has to detect the real error (maybe based on the text or the number) and create a translation for it.

2019-05-14 12:24 UTC, HLeithner commented
> Not that I'm aware of? JException was removed, maybe the database exceptions since the Framework package is in use (which also has its own Exception subclasses), that's all I can think of off hand.

ok I thought there was more then the JException class.

2019-05-14 12:30 UTC, mbabker commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
> because you have to catch each error and decide if we should show it to the user or not and if we show it to the user we have to translate the error message

That's exactly the point, that is proper error handling.  Not every thrown exception must cause the request execution to be aborted, and not every thrown exception must result in a message bubbling up to the UI.  Case and point, check for the places I added exception handling where the cache API is used; if the cache API throws a cache related exception, certain operations will try to fetch the needed data from the uncached source and if that succeeds then things go on like normal and nobody will know that the cache read/write operation failed (well technically that exception should at least be logged but Joomla sucks at logging things consistently).

The problem is core, and by proxy the extension ecosystem, has very minimal error handling code.  This results in a lot more exceptions bubbling up and triggering an error page than really should.  And with a lot of error templates (including those in core), the message shown on the error page is going to include the message from the Exception object.  Because it gets shown to the end user, it was decided to translate things.  So yes, it's easy to just throw Exceptions with translated text and be done with it, and yes for a number of Exception subclasses or error conditions this may be OK, but in general this is not the suggested practice; the best practice is to implement error handling code, catch the error, decide if something needs to be shown to the user and craft an appropriate message for the user, then decide if that is a "critical" failure or one that can be worked around and move forward as such.

2019-05-14 12:36 UTC, olleharstedt commented
There are 12 try-catch blocks in the joomla-cms repo right now. 9 of them are in the Crypto class, the other in Sniffs (phpcs). With this lack of precedence, I have low confidence that I can manage to write something that will be accepted.

2019-05-14 12:36 UTC, mbabker commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
Even using this specific example, explain to me why an Exception thrown from `Joomla\CMS\Filesystem\File::upload()` should go uncaught by a component or library and trigger an unrecoverable error page.  Calling code should be catching these exceptions, transforming the message into a "this file could not be uploaded" message, and adding that transformed/translated message into the message queue.

You want to make Exception messages useful for developers to debug issues.  In the case of filesystem related exceptions, this often includes the potential for security leaks (i.e. full path disclosure).  So your options are to either cripple your exception's info by writing the message assuming that will be displayed to every website visitor whose action triggers the error condition, or implement proper error handling and convert what may be a "sensitive" exception message into a user appropriate message.

2019-05-14 12:37 UTC, HLeithner commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
I agree with that but it shouldn't be harder for the developer as it is, adding proper error messages that can be displayed to the user shouldn't be a bad thing.

Also it would make sense to differ in error classes like http is doing with 4xx and 5xx errors. For this example it should always makes sense to show the 4xx error message to the user (because its a user error) and if it's a 5xx error the application should try to solve it or fail.

More or less the same you described.

In addition it would make sense to create exception classes that reflects 4xx and 5xx errors so it's easier to catch them?

2019-05-14 12:45 UTC, mbabker commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
> In addition it would make sense to create exception classes that reflects 4xx and 5xx errors so it's easier to catch them?

Bingo.

You want to enable developers to be able to catch and handle specific error conditions while letting other error conditions bubble up.  So a try/catch block for certain classes (RuntimeException or the base Exception class) are things I consider code smells because that probably means that block is catching too many errors (in the 3.x code a try/catch for RuntimeException around a database query would catch a RuntimeException thrown by the logging API in the right conditions).

And ultimately, it's up to the developer to decide whether in each scenario an error condition is something fatal that should trigger a 500 response (basically hit our global Exception handler) or if it is something that can be worked around with more grace (go back to the cache example for one case where error handling introduces a fallback path; for upload failures you'd want to catch those, add a message for the user, then redirect back to the page the form was on instead of letting it go uncaught and trigger the error page).

2019-05-14 19:43 UTC, olleharstedt commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
May I just point out that there are alternatives to exception that might be easier to integrate in Joomla's code base, like return codes (my first suggestion) and returning an array like `[$result, $errorMessage]`. I feel like both those alternatives will have a lesser impact with regard to coding style, than to try to implement an exception hierarchy, placing try-catch blocks at proper places, etc.

2019-05-14 19:50 UTC, mbabker commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
A "return code" or Result object concept (which personally I am not a fan of in APIs for communicating a success/fail state, this is exactly what boolean true/false or Exceptions are designed to communicate without littering global or object state like the MVC `getError` and `setError` methods do) still requires just as much change in calling code as try/catch blocks would.  You'd still have to check the result key, then decide if it's a success or fail, then decide what to do in the fail case.  It actually gets a little worse because you can ignore the return from the method and blissfully assume every call will succeed, exceptions do a bit more to force you to act on the error state.

2019-05-14 19:54 UTC, mbabker commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
Plus, a "return code" or Result object return at this point is a worse B/C break than eliminating the boolean false returns in favor of exceptions.  Any code that's doing `if (!File::upload()) {}` now assumes every return is a success state because an object or array will be loosely converted to boolean true.  Any code that's doing `if (File::upload() !== true) {}` would also be broken because an object or array won't be converted to boolean in a strict check.

2019-05-14 21:56 UTC, olleharstedt commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
Just NB, a result object is not a global object, it's just a return value. `$result = new Result(); $result->success = true; return $result;`

2019-05-14 22:46 UTC, mbabker commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
Yes I am quite aware of what a DTO is, I have a rather large library of them in my projects to deal with complex result sets from write operations.

Nonetheless, a DTO in the context of the filesystem API is overkill as you are truly dealing with a boolean flag.  The aim here is to try and get the reason for the false side of the boolean out of the black box of the API and to the developer so they can do something useful with it.

Changing the return type from a boolean result to a DTO is a worse B/C break than changing the false return scenarios to throwing exceptions, you're just flat out changing the return data in an incompatible manner.  Switching to exceptions for errors results in more verbose code because of the try/catch, but it is perfectly suited for this use case.

```php
try {
    File::upload($source, $destination);
} catch (FileNotFoundException $e) {
    // The source file doesn't exist, handle the error
} catch (FilesystemException $e) {
    // General filesystem error, let's see if the error code matches a scenario we want to process
    switch ($e->getCode()) {
        case FilesystemErrors::UNWRITABLE_FILE:
            // Destination file path couldn't be written to, handle the error
            break;

        default:
            // Not an error we have a specific handler for, let's rethrow since we aren't expecting it
            throw $e;
    }
}
```

The only difference between that and a DTO return is one level of indention on the main method call, everything else is going to be at least at the same level of indention in the error handling path unless you use an early return on success.  And personally, I feel that flows rather naturally.

2019-05-15 08:29 UTC, olleharstedt commented on libraries/src/Filesystem/File.php
> +				throw new \RuntimeException(Text::sprintf('Warning: File %s not uploaded for security reasons!', $dest), -1);
Do you have a process within the Joomla team where you make such decisions? It's a big style change.

2020-08-04 13:32 UTC, robinstern commented
I have tested this item :red_circle: unsuccessfully on 21c0408cc2d2bc5a7bf98c90794b1c63ff2c08c4<br /><br />Tested unsuccessfully!

Exception doesn´t show up, when uploading file!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24894">issues.joomla.org/tracker/joomla-cms/24894</a>.</sub>

2022-06-27 13:09 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2022-07-11 12:50 UTC, closed without merging