Added event onContentValidateData replacing onUserBeforeDataValidatio…
joomla/joomla-cms pull request #24902
Opened 2019-05-14 21:26 UTC by BrainforgeUK

Pull Request for Issue #19584 .
Summary of Changes

Added event onContentValidateData
Testing Instructions

Create a field plugin which implements onContentValidateData function like this...
public function onContentValidateData($form, &$data) {
// Change the data in some way
}
Expected result

The data get's changed.
Actual result

The data get's changed.
Documentation Changes Required

Add documentation for onContentValidateData event.
Add documentation for the existing, but undocumented and now deprecated, onUserBeforeDataValidation event.
This event will only get triggered when validate() overridden by a user component model.

2019-05-15 07:47 UTC, laoneo requested changes

2019-05-15 07:47 UTC, laoneo commented on libraries/src/MVC/Model/FormModel.php
> +			JFactory::getApplication()->triggerEvent('onUserBeforeDataValidation', array($form, &$data));
Can you use here Factory please.

2019-05-15 07:47 UTC, laoneo commented on libraries/src/MVC/Model/FormModel.php
> +		JFactory::getApplication()->triggerEvent('onContentValidateData', array($form, &$data));
Can you use here Factory please.

2019-05-16 16:52 UTC, BrainforgeUK commented
Superceded.

2019-05-16 16:52 UTC, closed without merging

2019-05-17 07:01 UTC, laoneo commented
You can just commit and push to the same branch and then the pr gets updated. No need to open a new pr.