[4.0.] Remove obsolete and outdated trigger
joomla/joomla-cms pull request #24941
Opened 2019-05-18 09:32 UTC by roland-d

### Summary of Changes
This removes the outdated and obsolete trigger. The correct trigger happens the line above.

### Testing Instructions
1. Go to Systems
2. Go to Plugins
3. Open plugin `Action Log - Joomla`
4. Click on `Save`
5. Notice you get the following error:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/359377/57967519-6e8bfc80-7960-11e9-94b5-17f640a2ad3c.png">
6. Apply the patch
7. Reload the page
8. Click on `Save`
9. Plugin is now saved

### Expected result
Plugin is saved

### Actual result
Class 'JEventDispatcher' not found error

### Documentation Changes Required
None

2019-05-18 09:45 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on f2d08b1754eb4490f1a9056d9f2ee2fc02fb2087<br /><br />Note: The testing instructions only tell 1 example when that error happens. It happens also with other actions like e.g. enable/disable plugin with button in list view. This PR fixes all of them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24941">issues.joomla.org/tracker/joomla-cms/24941</a>.</sub>

2019-05-18 10:20 UTC, alikon requested changes

2019-05-18 10:20 UTC, alikon commented on libraries/src/Table/Table.php
> -		$dispatcher = \JEventDispatcher::getInstance();
i don't think it is correct, in this way you don't track anymore the `onAfterCheckin` event
should be coverted in j4 style
 ```php
Factory::getApplication()->triggerEvent('onAfterCheckin', array($this->_tbl));
```

2019-05-18 10:26 UTC, richard67 commented on libraries/src/Table/Table.php
> -		$dispatcher = \JEventDispatcher::getInstance();
Yes, that works, too, I've just tested. Error also disappears when replacing lines 1323 and 1324 in the unpatched file by the line which @alikon suggests. So I think he is right.

2019-05-18 10:28 UTC, richard67 commented
@roland-d I think @alikon is right: Instead of removing lines 1323 and 1324, you should replace those 2 lines by the one line
`Factory::getApplication()->triggerEvent('onAfterCheckin', array($this->_tbl));`
like he suggests.

2019-05-18 10:30 UTC, alikon commented on libraries/src/Table/Table.php
> -		$dispatcher = \JEventDispatcher::getInstance();
maybe the confusion arise cause there 2 event : 

1. `onAfterCheckin `used by actionlog
2. `onTableAfterCheckin` unused by core

2019-05-18 10:31 UTC, richard67 commented
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24941">issues.joomla.org/tracker/joomla-cms/24941</a>.</sub>

2019-05-18 10:34 UTC, roland-d commented
@alikon There is definitely a confusion with 2 triggers with basically the same name. What is the difference between them? One is J4 and the other is for J3?

@richard67 I have added the trigger as suggested

2019-05-18 10:35 UTC, richard67 commented
Would be confusing me if the was no confusion in J4 ;-) (joke)

2019-05-18 10:37 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 485f9850673db0880d9188716308b1a9296684bf<br /><br />Note: The testing instructions only tell 1 example when that error happens. It happens also with other actions like e.g. enable/disable any plugin with the button in the plugins list view. This PR fixes all of them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24941">issues.joomla.org/tracker/joomla-cms/24941</a>.</sub>

2019-05-18 10:46 UTC, alikon commented
`onAfterCheckin` is worked by the  actionlog joomla plugin https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/actionlog/joomla/joomla.php#L924

2019-05-18 10:46 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 485f9850673db0880d9188716308b1a9296684bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24941">issues.joomla.org/tracker/joomla-cms/24941</a>.</sub>

2019-05-18 10:47 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24941">issues.joomla.org/tracker/joomla-cms/24941</a>.</sub>

2019-05-19 06:17 UTC, infograf768 commented
FYI, there are other places where the error happens: for example when playing with custom admin menus.

2019-05-19 06:29 UTC, merged

2019-05-19 06:29 UTC, infograf768 commented
Thanks.

2019-05-19 06:30 UTC, roland-d commented
Thank you