Pg schema
joomla/joomla-cms pull request #24999
Opened 2019-05-24 09:11 UTC by softarius

Pull Request for Issue #24998 .

### Summary of Changes
 Method getTableColumns of JDatabaseDriverPostgresql class

### Testing Instructions
- install Joomla with PostgreSQL driver.
- create a new schema (for example 'test')
- create a new table in this schema

```
CREATE TABLE test.customer (
  id SERIAL,
  name VARCHAR(100),
  PRIMARY KEY(id)
) 
WITH (oids = false);
```
- in code call getTableColumns for this table

```
$db = JFactory::getDBO();
$custfields=$db->getTableColumns('test.customer'); 
```

### Expected result
Array with fields of a table

### Actual result
Array with fields of a table. 

### Documentation Changes Required

Added to param $table  
For PostgreSQL may starting with a schema

2019-05-24 09:20 UTC, richard67 commented
@alikon Do you think this is a new feature for 4.0, or is it a bug fix for 3.9?

2019-05-24 09:23 UTC, alikon commented
quite a greyzone it dependes on how you feel that, so up to the Production Lead

2019-05-24 09:32 UTC, richard67 requested changes

2019-05-24 09:32 UTC, richard67 commented on schema.php
> +<?php
Please remove this file from your PR since it is only for testing this PR, so it should not be checked into the Joomla CMS source code. You have that code already in the testing instructions.

2019-05-24 09:32 UTC, richard67 commented on libraries/joomla/database/driver/postgresql.php
> +	        $fn = explode('.', $tableSub);
Code style error reported by Drone for lines 409 to 413: Tabs must be used to indent lines; spaces are not allowed

2019-05-24 09:32 UTC, richard67 commented on libraries/joomla/database/driver/postgresql.php
> +        	if (count($fn) == 2) {
Mind the Joomla CMS code style rules or check the Drone report.
An "if" with "else" should look as follows, where "..." means the code for each condition:

> if (...)
> {
> 	...
> }
> else
> {
> 	...
> }

Please correct that to make Drone happy.

2019-05-24 09:32 UTC, richard67 commented on libraries/joomla/database/driver/postgresql.php
> +        	if (count($fn) == 2) {
P.S. And indent the `...` code by tabs

2019-05-24 09:38 UTC, richard67 commented
@HLeithner Do you think this PR is a bug fix for 3.9 or a new feature for 4.0? From my point of view it is a bug fix since it is not good practice to use the public schema for everything in PostgreSQL, as far as I know, like it has to be without this PR. But I might be wrong, so I'd like to know your opinion, and @alikon 's, too, because he is doing much with PostgreSQL.

2019-05-24 09:42 UTC, HLeithner commented on schema.php
> +<?php
It would be better to convert it into a real test and integrated it into the test suite.

2019-05-24 09:44 UTC, richard67 commented on schema.php
> +<?php
Sure, that would be best. If the author of this PR feels not being able to do that, we can do that later with a new PR or help him here. But anyway this files as it is should be removed from this PR.

2019-05-24 09:46 UTC, HLeithner commented on libraries/joomla/database/driver/postgresql.php
> +					nspname = \'' . $schema . '\')
Use $this->quote() for quoting please.

2019-05-24 09:46 UTC, HLeithner commented
> @HLeithner Do you think this PR is a bug fix for 3.9 or a new feature for 4.0? From my point of view it is a bug fix since it is not good practice to use the public schema for everything in PostgreSQL, as far as I know, like it has to be without this PR. But I might be wrong, so I'd like to know your opinion, and @alikon 's, too, because he is doing much with PostgreSQL.

It's a bugfix.

2019-05-24 09:51 UTC, alikon commented
to me too it's a bugfix

2019-05-24 09:58 UTC, franz-wohlkoenig commented
@pviolette-fr please test > https://docs.joomla.org/Testing_Joomla!_patches

2019-05-24 10:17 UTC, softarius commented on schema.php
> +<?php
Now file 'schema.php' simply deleted

2019-05-24 10:32 UTC, softarius commented on libraries/joomla/database/driver/postgresql.php
> +					nspname = \'' . $schema . '\')
Fixed

2019-05-24 10:32 UTC, softarius commented on libraries/joomla/database/driver/postgresql.php
> +        	if (count($fn) == 2) {
Fixed

2019-05-24 10:32 UTC, softarius commented on libraries/joomla/database/driver/postgresql.php
> +	        $fn = explode('.', $tableSub);
fixed

2019-05-24 11:08 UTC, softarius commented
> @HLeithner Do you think this PR is a bug fix for 3.9 or a new feature for 4.0? From my point of view it is a bug fix since it is not good practice to use the public schema for everything in PostgreSQL, as far as I know, like it has to be without this PR. But I might be wrong, so I'd like to know your opinion, and @alikon 's, too, because he is doing much with PostgreSQL.

My PR isn't only bug-fix. It's a feature request for a future version of Joomla.
Best practice for PostgresSQL is using different schemas for logical subsystems into a database.
Proof - https://www.postgresql.org/docs/10/ddl-schemas.html#DDL-SCHEMAS-PATTERNS
Simple RDBS (not supported schemas, such as MySQL) use surrogate solving with a prefix for tables.
When I write a new component for Joomla with PostgreSQL, I wont to use for this separate schema.
In another side, in big and complex system Joomla could use schema. called other than "public".  But Joomla can't do it.
Third, with good schemas supporting Joomla could switching between schemas just different databases.

2019-05-24 11:18 UTC, HLeithner commented
I'm not sure what you mean with "Simple RDBS (not supported schemas, such as MySQL)" is the schema support of MySQL different then the support form PostgresSQL?

2019-05-24 12:23 UTC, softarius commented
> I'm not sure what you mean with "Simple RDBS (not supported schemas, such as MySQL)" is the schema support of MySQL different then the support form PostgresSQL?

Using the term 'schema' completely different in other systems.
In MySQL and Firebird command CREATE SCHEMA is a synonym for CREATE DATABASE - 

- https://dev.mysql.com/doc/refman/8.0/en/create-database.html
- https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-ddl-db.html

In more powerful RDBMS (Oracle, SQL Server, PostgreSQL ) a schema is essentially a namespace.
Proofs:

- https://www.postgresql.org/docs/11/sql-createschema.html
- https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_6014.htm#SQLRF01313
- https://docs.microsoft.com/ru-RU/sql/t-sql/statements/create-schema-transact-sql?view=aps-pdw-2016

2019-05-24 12:26 UTC, Quy commented on libraries/joomla/database/driver/postgresql.php
> +		if (count($fn) == 2)
```suggestion

		if (count($fn) == 2) 
```

2019-05-24 12:27 UTC, Quy commented on libraries/joomla/database/driver/postgresql.php
> +		$schema = $fn[0];
Indent lines 411, 412, and 416.

2019-05-24 12:28 UTC, Quy commented on libraries/joomla/database/driver/postgresql.php
> +	 * @param   string   $table     The name of the database table. For PostgreSQL may starting with a schema
```suggestion
	 * @param   string   $table     The name of the database table. For PostgreSQL may start with a schema.
```

2019-05-24 12:31 UTC, softarius commented on libraries/joomla/database/driver/postgresql.php
> +		$schema = $fn[0];
Fixed

2019-05-24 12:32 UTC, softarius commented on libraries/joomla/database/driver/postgresql.php
> +	 * @param   string   $table     The name of the database table. For PostgreSQL may starting with a schema
Fixed

2019-05-24 12:35 UTC, HLeithner commented
> > I'm not sure what you mean with "Simple RDBS (not supported schemas, such as MySQL)" is the schema support of MySQL different then the support form PostgresSQL?
> 
> Using the term 'schema' completely different in other systems.
> In MySQL and Firebird command CREATE SCHEMA is a synonym for CREATE DATABASE -
> 

ok thx, anyway in this case it's only a bugfix because it's should handle this and don't break.

2019-05-24 12:35 UTC, softarius commented on libraries/joomla/database/driver/postgresql.php
> +		if (count($fn) == 2)
fixed

2019-05-24 17:04 UTC, alikon commented
I have tested this item :white_check_mark: successfully on d16b754466a79813efaf4ebf1577f264971cf902<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24999">issues.joomla.org/tracker/joomla-cms/24999</a>.</sub>

2019-05-25 10:00 UTC, richard67 commented
@softarius I've changed the "Actual result" in your testing instructions to the value from the issue. I guess that was a copy and paste thing from "Expected result", so it was the same as that, and in the issue it was correct, right?

2019-05-25 10:02 UTC, richard67 commented
@HLeithner I can fully confirm @softarius 's explanations above.

2019-05-25 10:32 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on d16b754466a79813efaf4ebf1577f264971cf902<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24999">issues.joomla.org/tracker/joomla-cms/24999</a>.</sub>

2019-05-25 10:33 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24999">issues.joomla.org/tracker/joomla-cms/24999</a>.</sub>

2019-05-25 10:35 UTC, richard67 commented
@alikon Have there ever been discussions in past about full db schema support in Joomla, i.e. you can specify a schema like you can specify user and database names when installing on PostgreSQL, so Joomla can be installed using a different schema than "Public"? If so, what was the result of these discussions?

2019-05-25 10:36 UTC, richard67 commented
For the one who will merge: Drone failure is not related to this PR.

2019-05-25 19:20 UTC, softarius commented
> @softarius I've changed the "Actual result" in your testing instructions to the value from the issue. I guess that was a copy and paste thing from "Expected result", so it was the same as that, and in the issue it was correct, right?

Yes.

2019-05-26 11:42 UTC, SharkyKZ commented on libraries/joomla/database/driver/postgresql.php
> +		if (count($fn) == 2)
```suggestion
		if (count($fn) === 2) 
```

2019-05-27 06:41 UTC, alikon commented
@richard67 

> Have there ever been discussions in past about full db schema support in Joomla

not that i'm aware of

2019-05-30 09:12 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 3da16d1aebf5db2ae9fd7fd680f7214d1028d5d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24999">issues.joomla.org/tracker/joomla-cms/24999</a>.</sub>

2019-06-05 15:46 UTC, merged

2019-06-05 15:46 UTC, HLeithner commented
thx