[4.0] Try and fix asset table
joomla/joomla-cms pull request #25004
Opened 2019-05-25 01:17 UTC by wilsonge

Tries to fix the asset table in j4 as i know it became broken with the addition of the new j4 extensions and the conflicts from the privacy suite in j3

For those wondering I've tried using https://gist.github.com/alexgarel/b4e4a2e3160d3b0e8559 to implement this (amending the base lft value to be 0 instead of 1 on line 64)

2019-05-25 09:28 UTC, wilsonge commented
@alikon can you test this on postgres. the system tests are always failing after this. so i assume this breaks something

2019-05-25 11:16 UTC, richard67 requested changes

2019-05-25 11:16 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
>  SELECT setval('#__assets_id_seq', 69, false);
Should be `SELECT setval('#__assets_id_seq', 71, false);`

2019-05-25 11:20 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
>  SELECT setval('#__assets_id_seq', 69, false);
71 because it should be last id + 1. Was 69 before because last id was 68 before this PR.

2019-05-25 11:21 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
>  SELECT setval('#__assets_id_seq', 69, false);
@wilsonge Change this, and I am sure tests will pass because this is reason why creating new menu fails.

2019-05-25 11:23 UTC, richard67 commented
@alikon No need to check, I already found the problem for which @wilsonge has pinged you.

2019-05-25 11:28 UTC, wilsonge commented on installation/sql/postgresql/joomla.sql
>  SELECT setval('#__assets_id_seq', 69, false);
Doh! Nice spot - thanks!

2019-05-25 11:29 UTC, richard67 approved these changes

2019-05-25 11:31 UTC, richard67 commented on installation/sql/postgresql/joomla.sql
>  SELECT setval('#__assets_id_seq', 69, false);
Welcome. Am sure tests will pass now. Was the creating of new menu which failed because of duplicate primary key `id`. The sequence value defines which new if to use when inserting new records. Is same as an auto increment in MySQL but needs an extra sequence in PostgreSQL.

2019-05-25 11:44 UTC, wilsonge commented on installation/sql/postgresql/joomla.sql
>  SELECT setval('#__assets_id_seq', 69, false);
Yah I knew what it was - just totally forgot to update it :)

2019-05-25 12:59 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 203fa705a2564d1b74393b440fc1bb4d55a4302f<br /><br />Code review including analysis of lft and rgt values with respect to parent ids and levels.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25004">issues.joomla.org/tracker/joomla-cms/25004</a>.</sub>

2019-05-27 07:26 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 203fa705a2564d1b74393b440fc1bb4d55a4302f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25004">issues.joomla.org/tracker/joomla-cms/25004</a>.</sub>

2019-05-27 07:27 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25004">issues.joomla.org/tracker/joomla-cms/25004</a>.</sub>

2019-05-28 12:30 UTC, wilsonge commented
I realised like com_categories has no assets neither has workflows so re-removed it. Merging now.

2019-05-28 12:30 UTC, merged