[4.0][wip] poor cron
joomla/joomla-cms pull request #25022
Opened 2019-05-27 17:03 UTC by alikon

porting #22310 to 4.x

### Summary of Changes

### Testing Instructions

### Expected result

### Actual result

### Documentation Changes Required

2019-05-27 17:32 UTC, brianteeman commented
Thanks very much for this PR

2019-05-28 02:21 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +use Symfony\Component\Console\Input\InputOption;
Sort alpha order.

2019-05-28 02:21 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +
```suggestion
```

2019-05-28 02:23 UTC, Quy commented on libraries/src/Plugin/PluginHelper.php
> +
```suggestion
```

2019-05-28 02:24 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +
```suggestion
```

2019-05-28 02:24 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +			return 0;
```suggestion

			return 0;
```

2019-05-28 02:24 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +
```suggestion
```

2019-05-28 02:25 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +			$symfonyStyle->note('Executed: ' . $run);
```suggestion

			$symfonyStyle->note('Executed: ' . $run);
```

2019-05-28 02:25 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +
```suggestion
```

2019-05-28 02:25 UTC, Quy commented on libraries/src/Plugin/PluginHelper.php
> +			return false;
```suggestion

			return false;
```

2019-05-28 02:26 UTC, Quy commented on libraries/src/Plugin/PluginHelper.php
> +		if ($result === 0)
```suggestion

		if ($result === 0)
```

2019-05-28 02:26 UTC, Quy commented on plugins/system/scheduler/scheduler.php
> +
```suggestion
```

2019-05-28 02:27 UTC, Quy commented on plugins/system/scheduler/scheduler.php
> +	}
```suggestion
	}
```

2019-05-28 02:27 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +
```suggestion
```

2019-05-28 02:28 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +		//var_dump($db);
```suggestion
```

2019-05-28 02:28 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +
```suggestion
```

2019-05-28 02:29 UTC, Quy commented on libraries/src/Plugin/PluginHelper.php
> +		$now           = time();
Align `=`

2019-05-28 02:31 UTC, Quy commented on plugins/system/scheduler/scheduler.xml
> +					class="btn-group btn-group-yesno"
```suggestion
					class="switcher"
```

2019-05-28 02:31 UTC, Quy commented on plugins/system/scheduler/scheduler.xml
> +					<option value="1">JYES</option>
Swap lines 44-45.

2019-05-28 06:36 UTC, alikon commented on libraries/src/Plugin/PluginHelper.php
> +		$now           = time();
done

2019-05-28 08:35 UTC, alikon commented on plugins/system/scheduler/scheduler.xml
> +					<option value="1">JYES</option>
done

2019-05-28 08:36 UTC, alikon commented on libraries/src/Console/SchedulerCommand.php
> +use Symfony\Component\Console\Input\InputOption;
done

2019-05-28 10:55 UTC, Quy commented on plugins/system/scheduler/scheduler.xml
> +					default="mywebcronactiovationkey"
```suggestion
					default="mywebcronactivationkey"
```

2019-05-28 10:55 UTC, Quy commented on plugins/system/scheduler/scheduler.xml
> +	<version>3.9.0</version>
Update?

2019-05-28 10:57 UTC, Quy commented on libraries/src/Plugin/PluginHelper.php
> +
```suggestion
```

2019-05-28 10:59 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +					$nextrun = ", next run will be after " . abs($now - $lastrun - $timeout);
```suggestion
					$nextrun = ‘, next run will be after ‘ . abs($now - $lastrun - $timeout);
```

2019-05-28 11:02 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +					$nextrun = ", next run will be after " . abs($now - $lastrun - $timeout);
```suggestion
					$nextrun = ', next run will be after ' . abs($now - $lastrun - $timeout);
```

2019-05-28 16:30 UTC, alikon commented on plugins/system/scheduler/scheduler.xml
> +	<version>3.9.0</version>
did you mean 4.0.0 instead of 3.9.0 ?

2019-05-28 16:33 UTC, Quy commented on plugins/system/scheduler/scheduler.xml
> +	<version>3.9.0</version>
Yes

2019-05-28 16:49 UTC, alikon commented on plugins/system/scheduler/scheduler.xml
> +	<version>3.9.0</version>
done
i want to be optimist  
`<creationDate>July 2019</creationDate>`
:smile:

2019-05-29 03:20 UTC, mbabker commented on libraries/src/Console/SchedulerCommand.php
> +		if ($input->getOption('jobs'))
Everything in this block should really be another command.  This command looks more like a "run what's in the queue" command, and this if block looks like a "show what's in the queue" command.

2019-05-29 03:20 UTC, mbabker commented on libraries/src/Console/SchedulerCommand.php
> +		return Factory::getApplication()->triggerEvent('onExecuteScheduledTask', array());
`$this->getApplication()`

The command class has the application within scope, no reason to go to the static factory.

2019-05-29 03:21 UTC, mbabker commented on libraries/src/Console/SchedulerCommand.php
> +	public static function listJobs(string $folder = 'job', string $type = 'plugin')
Static because?

2019-05-29 03:21 UTC, mbabker commented on libraries/src/Console/SchedulerCommand.php
> +		$db = Factory::getDbo();
Once the static keyword is removed, use dependency injection for the database driver.  You're already injecting it in the service provider class, you just need to add the constructor to receive it in this class.

2019-05-29 03:22 UTC, mbabker commented on libraries/src/Console/SchedulerCommand.php
> +			return false;
Either return an array or don't catch this exception, I'd lean toward not catching it and letting the exception bubble up here.

2019-05-29 04:11 UTC, Quy commented on libraries/src/Plugin/PluginHelper.php
> +		}
```suggestion
		}
```

2019-05-29 04:12 UTC, Quy commented on plugins/system/scheduler/scheduler.php
> +
Remove tabs.

2019-05-29 06:38 UTC, alikon commented on libraries/src/Console/SchedulerCommand.php
> +		if ($input->getOption('jobs'))
yes exactly,  imo is an option to the same command, but, i like your pov too, 2 different commands
added to my to-do list

2019-05-29 06:43 UTC, alikon commented on libraries/src/Console/SchedulerCommand.php
> +		return Factory::getApplication()->triggerEvent('onExecuteScheduledTask', array());
ok

2019-05-29 06:44 UTC, alikon commented on libraries/src/Console/SchedulerCommand.php
> +	public static function listJobs(string $folder = 'job', string $type = 'plugin')
my mistake

2019-05-29 06:54 UTC, alikon commented on libraries/src/Console/SchedulerCommand.php
> +		$db = Factory::getDbo();
i've forgot about this when i've converted from  3.x 🤕

2019-05-29 07:01 UTC, alikon commented on libraries/src/Console/SchedulerCommand.php
> +			return false;
ok no catch

2019-05-29 07:11 UTC, alikon commented on plugins/system/scheduler/scheduler.php
> +
done

2019-05-29 08:09 UTC, HLeithner commented on libraries/src/Plugin/PluginHelper.php
> +		$query->bind(':checked_out_time', $lockdate)
Please move the bind methods to the end of the chain.
Bind returns a PreparableInterface and not a QueryInterface, a static code analyzer will raise an error here.

2019-05-29 08:09 UTC, HLeithner commented on libraries/src/Plugin/PluginHelper.php
> +			->set($db->qn('checked_out_time') . ' = :checked_out_time')
```suggestion
			->set($db->quoteName('checked_out_time') . ' = :checked_out_time')
```

2019-05-29 08:09 UTC, HLeithner commented on libraries/src/Plugin/PluginHelper.php
> +		$query->bind(':checked_out_time', $lockdate)
Same as above.

2019-05-29 08:09 UTC, HLeithner commented on libraries/src/Plugin/PluginHelper.php
> +			$query->bind(':params', $jsonparam)
Same as above.

2019-05-29 08:09 UTC, HLeithner commented on libraries/src/Plugin/PluginHelper.php
> +				->set($db->qn('checked_out_time') . ' = :checked_out_time')
```suggestion
				->set($db->quoteName('checked_out_time') . ' = :checked_out_time')
```

2019-05-29 08:09 UTC, HLeithner commented on libraries/src/Plugin/PluginHelper.php
> +				->set($db->qn('checked_out_time') . ' = :checked_out_time')
```suggestion
				->set($db->quoteName('checked_out_time') . ' = :checked_out_time')
```

2019-05-29 15:25 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +	}
```suggestion
	}

```

2019-05-29 15:26 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +
```suggestion
```

2019-05-29 17:23 UTC, alikon commented on libraries/src/Plugin/PluginHelper.php
> +		$query->bind(':checked_out_time', $lockdate)
recheck please

2019-05-29 17:24 UTC, HLeithner commented on libraries/src/Plugin/PluginHelper.php
> +		$query->bind(':checked_out_time', $lockdate)
looks better now thx

2019-05-30 07:14 UTC, alikon commented on libraries/src/Console/SchedulerCommand.php
> +		if ($input->getOption('jobs'))
now we have:

-  run what's in the queue command 
-  show what's in the queue command

2019-05-30 18:41 UTC, Quy commented on libraries/src/Console/JobListCommand.php
> +
Remove tabs

2019-05-30 18:42 UTC, Quy commented on libraries/src/Console/JobListCommand.php
> +
Remove tab

2019-05-30 18:42 UTC, Quy commented on libraries/src/Console/JobListCommand.php
> +
Remove tabs

2019-05-30 18:42 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +
Remove tabs

2019-05-30 18:43 UTC, Quy commented on libraries/src/Plugin/PluginHelper.php
> +
```suggestion
```

2019-07-16 18:47 UTC, richard67 commented
@alikon Do you plan to add the SQL for inserting the new system plugin into the `#__extensions` table to joomla.sql scripts and add schema updates for the same thing?

2019-07-17 06:24 UTC, alikon commented
yes, if i only got some feedback before....it seems lack of interest as for now

2019-07-26 17:26 UTC, f-hamel commented
Hey. This is a great PR and something people at managed and shared hosting provider need.
Trust me I know working for year at web hosting company. Most of them just give them an interface to create something like pseudo cronjobs. And on the other hand most users are not familiar with managing a server and cronjobs. So this would be a nice addon to help them.

And I really want to test this, but at the moment it's not possible because the Commands compatible with the `Joomla\Console\Command\AbstractCommand::configure()`. 

I guess at least the return type declaration is missing.
https://github.com/joomla/joomla-cms/blob/6afec30d3b7305a7cd8a1f388c8c3e518986d32f/libraries/src/Console/JobListCommand.php#L142

This should be look like this:
```suggestion
	protected function configure(): void
```

2019-07-27 08:07 UTC, alikon commented
@f-hamel  should be ready for test
@richard67  sql added

2019-07-29 12:01 UTC, f-hamel commented
At the Moment. The CLI seems to be broken by this PR.
```bash

php joomla.php list
cli 4.0.0-alpha11-dev

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display the help information
  -q, --quiet           Flag indicating that all output should be silenced
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Flag to disable interacting with the user
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

```


The command list is missing.



Also

```bash
php joomla.php job:run
```

returns nothing at the moment on console. So there is no output.
I don't know if there is maybe any php or mysql error. Because my error reporting is broken at the moment. Maybe some else who test this will have more information or will test this successful.

2019-08-02 17:38 UTC, alikon commented
ok, you are right the CLI part needs some more refactoring. meanwhile, can we test the no-CLI side ?

2019-08-21 09:19 UTC, alikon commented
@f-hamel previous reported issues fixed, can you retest ?

2019-08-21 18:19 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
These should be lazy commands in the command loader, not instantiated by default.  Actually, I'd say everything here really just needs to be moved to the command loader.  Every command in this method gets instantiated on every run of the console application, that's not what you want.  I put the first couple of commands here because they had no dependencies and instantiating them had low cost, I haven't looked at the user command group but the commit where you moved the database driver from constructor injection (as it should be) to using `Joomla\CMS\Factory::getDbo()` raised the red flag that something was wrong.

2019-09-03 08:50 UTC, bees4ever commented
I have tested this item :white_check_mark: successfully on 4d0589f3c0a971cf3b637f76db6e0594a13f91de<br /><br />It is a very great and usefull PR. It worked for me, but I noticed two things, what I want to ask here. 

I installed the schedule and the two job plugins. Where plugin one runs every 10 minute and the second one every second minute. When I change some settings in the scheduler, the job queue is kind of resetted, so that both jobs starts again, even if there was some minute to the 10 minute waiting time of job one. But I think this is known and ok.

Then I tested the web cron trigger url. It worked as expected, so that the `onExecuteScheduledTask` is triggered the same as the web page reload. But maybe something is wrong, because if I open / curl this link index.php?webcronkey=mywebcronactivationkey just the home page is loaded, it doesnt matter if the key is right or not, of course it is working, but I am not sure if this is expected.

I hope @alikon understand my explaination :see_no_evil:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2019-09-08 09:59 UTC, alikon commented
thanks for testing

when the webcron option is setted if the activation key is wrong  the scheduled job's are not executed, even if the page is rendered

when you change  scheduler or job settings  this could  affect the next job execution time
there is an hidden param that holds the last run time so the next run is expected based to that last rum time + the new setting

2019-09-10 18:48 UTC, alikon commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
sorry for my lazyness & dumbness, i've tryed the lazy load way, but i've failed, so i've preferred to switch back to  a silly & workable pattern....  any help to follow the right way is warmly wellcommed... i'm quite lost on the the lazy commands ....help please :face_with_head_bandage:

2019-09-10 19:46 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
Revert https://github.com/joomla/joomla-cms/pull/25022/commits/5e32f19aa5eaf849165b3fbf9ec461a5d063a4d1 and https://github.com/joomla/joomla-cms/pull/25022/commits/81b9f34027557928075b0c3c0fba692aefb471fe and that puts the commands back into being defined as services which makes them lazy loaded.  Then revert https://github.com/joomla/joomla-cms/pull/25022/commits/70af1e51af0f4c66529e57ae7a240ec57a5599bd which puts the constructor injection back in the `JobListCommand`.

I don't know why you had to make all those changes, but what you had there should have been working.

2019-09-10 19:51 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
There are a couple of things to keep in mind in general (not just this PR):

- Every command class in `getDefaultCommands` gets instantiated every time the console application is run; this has performance related consequences
    - And as a result, very few commands should actually be added to this list as it should basically be "critical" commands only (and since they are closely tied into the main application, the `list` and `help` commands fit that description), the container should be the preferable way of adding commands in general
- Anything registered into the command loader only gets instantiated when it is needed (so the default `list` and `help` commands, and when the command is actually run)
- Commands defined as services support dependency injection, meaning they absolutely should not call `Factory::get*()` ever, everything they need can be correctly injected into the classes

2019-09-11 18:05 UTC, alikon commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
thanks for your tips ... very appreciated...  but i still need more help
i'm still in deep shit  :smile: 

> Revert [5e32f19](https://github.com/joomla/joomla-cms/commit/5e32f19aa5eaf849165b3fbf9ec461a5d063a4d1) and [81b9f34](https://github.com/joomla/joomla-cms/commit/81b9f34027557928075b0c3c0fba692aefb471fe) and that puts the commands back into being defined as services which makes them lazy loaded. Then revert [70af1e5](https://github.com/joomla/joomla-cms/commit/70af1e51af0f4c66529e57ae7a240ec57a5599bd) which puts the constructor injection back in the `JobListCommand`.
> 
> I don't know why you had to make all those changes, but what you had there should have been working.

OK ..... let's do it
reverted for `JobListCommand` only,   just to go with  1 little step at time

- 5e32f19 
- 81b9f34
- 70af1e5

if i run php `cli/joomla.php`
![Screenshot from 2019-09-11 19-50-44](https://user-images.githubusercontent.com/181681/64721818-8702c280-d4cd-11e9-9192-582b1f984e9c.png)


as you can notice `job:list ` command  suddenly  just disappear

surely i'm doing something wrong but till now i'm unable to solve/understand  ...

help :pray:

2019-09-11 18:12 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
Without cloning your branch I couldn't tell you what the issue is that's causing it to not show on the command listing.  But the fix is most assuredly not to move the command into the default list, that's a huge red flag.  I can tell you with absolute certainty though that the code you removed in those 3 commits is written correctly (compare with https://github.com/joomla/statistics-server/blob/master/src/Providers/ConsoleServiceProvider.php which is more or less structured the same way and you'll see it is all right).

2019-09-11 18:21 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
OK, I cloned it, reverted those 3 commits, then ran into 2 issues:

1) The `SchedulerCommand` class needed a constructor restored
2) The `JobListCommand` was missing a use statement for the `Joomla\Database\DatabaseInterface` import

Once I sorted those two issues out...

![Screen Shot 2019-09-11 at 1 21 32 PM](https://user-images.githubusercontent.com/368545/64723942-16d94a00-d497-11e9-95af-4e4e28e6afd1.png)

2019-09-11 18:38 UTC, alikon commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
sure, 
you are right "as usual" :smile:
...... let me play a little bit more with my silly faults.... 
just to not bother you too much...(but i'm quite sure near...i'll ask you to clone my branch)

2019-09-11 18:48 UTC, alikon commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
i hope you can send a fix pr to my shitty branch then ....which is open to all 
men/women/whatever  of good will  :smile: 

p.s.
i'm too curious to discover what it is under my eyes, but i'm too blind to saw it
....

2019-09-11 18:51 UTC, mbabker commented on libraries/src/Application/ConsoleApplication.php
> +				new Console\SchedulerCommand,
1) Revert those 3 commits
2) Apply this diff:

```diff
diff --git a/libraries/src/Application/ConsoleApplication.php b/libraries/src/Application/ConsoleApplication.php
index 942d1198d3..40ee06578c 100644
--- a/libraries/src/Application/ConsoleApplication.php
+++ b/libraries/src/Application/ConsoleApplication.php
@@ -222,8 +222,6 @@ class ConsoleApplication extends Application implements DispatcherAwareInterface
                                new Console\DeleteUserCommand,
                                new Console\ChangeUserPasswordCommand,
                                new Console\ListUserCommand,
-                               new Console\JobListCommand,
-                               new Console\SchedulerCommand,
                        ]
                );
        }
diff --git a/libraries/src/Console/JobListCommand.php b/libraries/src/Console/JobListCommand.php
index f9e1155847..541c892293 100644
--- a/libraries/src/Console/JobListCommand.php
+++ b/libraries/src/Console/JobListCommand.php
@@ -12,6 +12,7 @@ defined('JPATH_PLATFORM') or die;
 
 use Joomla\CMS\Factory;
 use Joomla\Console\Command\AbstractCommand;
+use Joomla\Database\DatabaseInterface;
 use Symfony\Component\Console\Input\InputInterface;
 use Symfony\Component\Console\Output\OutputInterface;
 use Symfony\Component\Console\Style\SymfonyStyle;
diff --git a/libraries/src/Service/Provider/Console.php b/libraries/src/Service/Provider/Console.php
index 0086450c09..0a11749608 100644
--- a/libraries/src/Service/Provider/Console.php
+++ b/libraries/src/Service/Provider/Console.php
@@ -86,7 +86,7 @@ class Console implements ServiceProviderInterface
                        SchedulerCommand::class,
                        function (Container $container)
                        {
-                               return new SchedulerCommand($container->get('db'));
+                               return new SchedulerCommand;
                        },
                        true
                );
```

3) Profit

2019-10-19 10:04 UTC, jaydevingawale commented
I have tested this item :white_check_mark: successfully on 4d0589f3c0a971cf3b637f76db6e0594a13f91de<br /><br />I have tested this and its working perfectly, it only created the log file to mysite/logs/joomla_web.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2019-10-19 10:04 UTC, jaydevingawale commented
I have tested this item :white_check_mark: successfully on 4d0589f3c0a971cf3b637f76db6e0594a13f91de<br /><br />I have tested this and its working perfectly, it only created the log file to mysite/logs/joomla_web.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2019-10-19 13:40 UTC, ladyjer commented
Hi, I've tested "php joomla.php job:run" without success.
I get this console error:

    ladyj@jarvis:~/Area51/Projects/Web/area51.ladyj.eu/joomla-cms-4/cli$ php joomla.php job:run
    PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of  Exception, instance of ParseError given in /home/ladyj/Area51/Projects/Web/area51.ladyj.eu/joomla-cms-4/libraries/vendor/symfony/debug/ExceptionHandler.php:118
    Stack trace:
    #0 [internal function]: Symfony\Component\Debug\ExceptionHandler->handle(Object(ParseError))
    #1 {main}
    thrown in /home/ladyj/Area51/Projects/Web/area51.ladyj.eu/joomla-cms-4/libraries/vendor/symfony/debug/ExceptionHandler.php on line 118

I get the same error with: "php joomla.php database:export".

    ladyj@jarvis:~/Area51/Projects/Web/area51.ladyj.eu/joomla-cms-4/cli$ php joomla.php database:export
    PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception, instance of ParseError given in /home/ladyj/Area51/Projects/Web/area51.ladyj.eu/joomla-cms-4/libraries/vendor/symfony/debug/ExceptionHandler.php:118
    Stack trace:
    #0 [internal function]: Symfony\Component\Debug\ExceptionHandler->handle(Object(ParseError))
    #1 {main}
    thrown in /home/ladyj/Area51/Projects/Web/area51.ladyj.eu/joomla-cms-4/libraries/vendor/symfony/debug/ExceptionHandler.php on line 118

@mbabker could it be due to something wrong on my environment?



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2019-10-19 15:59 UTC, webfeuerflo commented
I have tested this item :white_check_mark: successfully on 4d0589f3c0a971cf3b637f76db6e0594a13f91de<br /><br />the two provdided test jobs are running. Missing language strings in job2 plugin for minutes and hours<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2019-10-19 22:26 UTC, eshiol commented on libraries/src/Console/JobListCommand.php
> +	**
```suggestion
	/**
```

2019-10-22 07:29 UTC, alikon commented
@ladyjer  there was a silly error in the opening of the comment https://github.com/joomla/joomla-cms/pull/25022#pullrequestreview-304233597  fixed by https://github.com/joomla/joomla-cms/pull/25022/commits/099c26bb8469e8ce5d2e326b2251edced28caa9a
so nothing wrong with your environment
the CLI side is ready to be tested....

2020-02-01 13:11 UTC, richard67 commented
@alikon I've just created updated versions of your 2 test plugins so they use language file names without the "en-GB." at the beginning, like we do it in core now. You can find them here:
- [https://test5.richard-fath.de/plg_job_one.zip](https://test5.richard-fath.de/plg_job_one.zip)
- [https://test5.richard-fath.de/plg_job_two.zip](https://test5.richard-fath.de/plg_job_two.zip)
Please download and check and if ok, either replace your downloads by these or change the links in your testing instructions so they point to my links.

2020-02-02 11:57 UTC, richard67 requested changes

2020-02-02 11:57 UTC, richard67 commented on libraries/src/Console/JobListCommand.php
> +			$symfonyStyle->note('Job: ' . $job->element . ' runned ' . $runned . ' times' . $nextrun);
```suggestion
			$symfonyStyle->note('Job: ' . $job->element . ' has run ' . $runned . ' times' . $nextrun);
```
"Run" is irregular verb, past particple is "run" and not "runned". Here to use past perfect because action has started in past and finished in past, therefore "has run".

2020-02-02 11:57 UTC, richard67 commented on libraries/src/Console/JobListCommand.php
> +			$runned     = $taskParams['taskid'];
Suggest to rename that to something else, e.g. "$lastcount" or so, because "runned" does not exist in English language, see review of language string below.

2020-02-02 11:57 UTC, richard67 commented on libraries/src/Console/JobListCommand.php
> +			$symfonyStyle->note('Job: ' . $job->element . ' runned ' . $runned . ' times' . $nextrun);
@brianteeman Please confirm.

2020-02-02 12:02 UTC, richard67 commented
@alikon Beside the language string and variable name I've mentioned in my previous review I've found following when testing CLI:
![test-poor-mans-cron_1](https://user-images.githubusercontent.com/7413183/73607866-1c593d00-45bc-11ea-89df-1bd9dbe1b7c9.png)

I.e. "job:list" works well, "job:run" works too but shows the PHP notice (same notice 2 times) about `Undefined index: REMOTE_ADDR in /libraries/vendor/joomla/utilities/src/IpHelper.php on line 488`. Am trying to find reason, but maybe @SharkyKZ has an idea?

2020-02-02 12:17 UTC, richard67 requested changes

2020-02-02 12:17 UTC, richard67 commented on libraries/src/Console/JobListCommand.php
> +			$runned     = $taskParams['taskid'];
```suggestion
			$lastcount  = $taskParams['taskid'];
```
See my comment above.

2020-02-02 12:18 UTC, richard67 commented on libraries/src/Console/JobListCommand.php
> +			$runned     = $taskParams['taskid'];
For change see nexct suggested review below.

2020-02-02 12:25 UTC, richard67 commented on libraries/src/Plugin/PluginHelper.php
> +		$lockdate = '1918-01-01 00:00:00';
'1918-01-01 00:00:00' ... Will that work on Postgres, too?

2020-02-02 12:25 UTC, richard67 commented on libraries/src/Plugin/PluginHelper.php
> +		$lockdate = '1918-01-01 00:00:00';
'1918-01-01 00:00:00' ... Will that work on Postgres, too?

2020-02-02 12:28 UTC, richard67 commented
@alikon Another thing I just see is that the scheduler plugin still uses old style language file names starting with "en-GB.". Should I make a PR for your branch so you can apply all my suggested changes from review plus the language file name change with one click?

2020-02-02 12:47 UTC, richard67 commented
@alikon Made [https://github.com/alikon/joomla-cms/pull/64](https://github.com/alikon/joomla-cms/pull/64) to save you some work. Contains all changes in my above reviews, too.

2020-02-02 12:52 UTC, richard67 commented
The PHP notice on CLI mentioned in one of my comments above seems really to be an error in the IpHelper. It doesn't check if the array key 'REMOTE_ADDR' exists before checking it in line 488. So this seems not to be a mistake in this PR here.

2020-02-02 12:57 UTC, SharkyKZ commented
IMO, changes do not belong in `Joomla\CMS\Plugin\PluginHelper`.

2020-02-02 13:00 UTC, richard67 commented
@SharkyKZ Which ones you mean? The "1918" date correction I've suggested above? If you mean that, let me know where else to change them. Or do you mean the PHP notice in CLI? This should already be solved in the utilities package with your PR [https://github.com/joomla-framework/utilities/pull/23](https://github.com/joomla-framework/utilities/pull/23), I have to check if it has been merged into the 2.0-dev branch there. If so, we maybe just have to update the utilities package in the cms.

2020-02-02 13:08 UTC, SharkyKZ commented
I mean any code added to `PluginHelper` class. At least currently the code is called only by Scheduler plugin so it's more suitable for the code to be contained in the plugin. But I'm not sure what the intention here is.

2020-02-02 13:09 UTC, SharkyKZ commented
I'm also not sure how correct is the use of `checked_out_time` property here.

2020-02-02 13:11 UTC, richard67 commented
@SharkyKZ Well I can't say if it's right to add code there or not, but that was then done by this PR and not by my suggested changes. Regarding the "abuse" of the checked out time column: Yes, I agree, it looks a bit like a hack to me. But I could live with that.

2020-02-02 20:43 UTC, richard67 commented
Corrected path to logs folder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2020-02-02 21:27 UTC, richard67 commented
@alikon So, now I've tested again, and it works for me as described (web, webcron and cli).

What remains to be clarified is the architectural question raised by @SharkyKZ if the `PluginHelper` class is the right place to add the new stuff, and his and my concern if the usage of the `checked_out_time` column is suitable for that. For me it works and I'm ok with it, but maybe it can be improved.

I'll wait for some info before I mark my test result with success. Maybe there will be some changes. Just ping me when all is ok or when I shall test again. Now that I know how it works I can do it more quickly.

2020-02-02 21:36 UTC, alikon commented
i'm open to hear all the feedback, and i'm really happy  that we have some feedback now

- for the `checked_out_time` column usage

yes it seems like an hack, but my goal was that, i didn't want to add another column, 
i've written this for j3 and then ported on j4 cause it was too late for j3

- for the `PluginHelper` code

i'm open to listen a better way to do it

2020-02-04 18:38 UTC, richard67 commented
@alikon The clean solution would be to create a new class for the new function, if necessary a child class of the plugin helper (@SharkyKZ what do you think?) and to create a new table for the jobs.

@wilsonge Any suggestions?

2020-02-13 07:45 UTC, alikon commented
let's give this a nth attempt

2020-02-14 14:36 UTC, astridx commented
I have tested this:

1. git fetch origin pull/25022/head:patch-81
2. git checkout patch-81 
3. New installation because of database changes
4. npm ci is not needed but I did it
5. System panel -> discover -> I found no new system plugin scheduler, but I realize, that it is installed :)


![Plugins  System   Job Scheduler   admin   Administration](https://user-images.githubusercontent.com/9974686/74539418-4a386d00-4f3e-11ea-992f-dfe92f77b7c3.png)

![Plugins   admin   Administration](https://user-images.githubusercontent.com/9974686/74539415-49074000-4f3e-11ea-8615-d7ceb946fb0c.png)


**Testing web**

1. I set the options 

2. I installed the two jobs via System extension Upload package and enabled them.

![Extensions  Install   admin   Administration](https://user-images.githubusercontent.com/9974686/74539419-4ad10380-4f3e-11ea-89bc-c69d61d27555.png)

![Plugins   admin   Administration(1)](https://user-images.githubusercontent.com/9974686/74539421-4b699a00-4f3e-11ea-8fd0-ab2d1cbfed99.png)

3. I set the options (In job2 are not language strings but this is not part of this pr)

4. i wait a short time and see this output in the log file.

```
#
#<?php die('Forbidden.'); ?>
#Date: 2020-02-14 13:45:14 UTC
#Software: Joomla! 4.0.0-beta1-dev Development [ Mañana ] 17-October-2019 20:21 GMT

#Fields: datetime	priority clientip	category	message
2020-02-14T13:45:14+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:45:14+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#1 Total Processing Time: 0.01 seconds.
2020-02-14T13:45:48+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:45:48+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#1 Total Processing Time: 0.01 seconds.
2020-02-14T13:47:43+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:47:43+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#2 Total Processing Time: 0.01 seconds.
2020-02-14T13:48:18+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:18+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#3 Total Processing Time: 0.01 seconds.
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#4 Total Processing Time: 0.02 seconds.
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#5 Total Processing Time: 0.02 seconds.
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#6 Total Processing Time: 0.01 seconds.
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#7 Total Processing Time: 0.03 seconds.
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#8 Total Processing Time: 0.02 seconds.
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:19+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#9 Total Processing Time: 0.01 seconds.
2020-02-14T13:48:24+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:24+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#10 Total Processing Time: 0.01 seconds.
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#11 Total Processing Time: 0.01 seconds.
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#12 Total Processing Time: 0.01 seconds.
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#13 Total Processing Time: 0.02 seconds.
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#14 Total Processing Time: 0.02 seconds.
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#15 Total Processing Time: 0.02 seconds.
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#16 Total Processing Time: 0.01 seconds.
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:32+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#17 Total Processing Time: 0.02 seconds.
2020-02-14T13:48:34+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:48:34+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#18 Total Processing Time: 0.01 seconds.
2020-02-14T13:49:02+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:49:02+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#19 Total Processing Time: 0.01 seconds.
2020-02-14T13:49:10+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:49:10+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#20 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:05+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:05+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#21 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#22 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#23 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#24 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#25 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#26 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:06+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#27 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:08+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:08+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#28 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:09+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:09+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#29 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:22+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:22+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#30 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:27+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:27+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#31 Total Processing Time: 0.01 seconds.
2020-02-14T13:50:38+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:39+00:00	INFO 127.0.0.1	scheduler	Job>jobone Task#1 Processing Time: 1.11 seconds.
2020-02-14T13:50:42+00:00	INFO 127.0.0.1	scheduler	Job>jobtwo Task#1 Processing Time: 3.01 seconds.
2020-02-14T13:50:42+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#32 Total Processing Time: 4.14 seconds.
2020-02-14T13:50:45+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:45+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#33 Total Processing Time: 0.03 seconds.
2020-02-14T13:50:50+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:51+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#34 Total Processing Time: 0.03 seconds.
2020-02-14T13:50:53+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2020-02-14T13:50:53+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#35 Total Processing Time: 0.02 seconds.
2020-02-14T13:51:36+00:00	INFO 127.0.0.1	sch [...]

2020-02-14 14:37 UTC, astridx commented
I have tested this item :white_check_mark: successfully on 4d0589f3c0a971cf3b637f76db6e0594a13f91de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2020-02-14 14:37 UTC, astridx commented
I have tested this item :white_check_mark: successfully on 4d0589f3c0a971cf3b637f76db6e0594a13f91de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2020-02-14 18:25 UTC, alikon commented
thanks for testing
the PHP notice about the REMOTE_ADDR it has been already solved here : 
https://github.com/joomla-framework/utilities/pull/23
but that framework version of the utilities package it is still not in J4

2020-02-14 18:32 UTC, richard67 commented
@alikon Meanwhile https://github.com/joomla-framework/utilities/pull/23 is available in the 2.0-dev branch of the framework package, too, so yes, the package can be fetched to J4. 2 weeks ago that wasn't the case yet, there it was only in the master branch there.

2020-02-16 15:27 UTC, wilsonge commented
Merged in the update to 4.0-dev. I haven't taken any time to look through this yet - to be honest there's nothing in here b/c breaking so I'm not going to prioritise this either over the other beta blocking issues - if it has to go to 4.1 - it is what it is. But I will try and do an initial review as well over the next few days and give some opinions.

2020-02-22 14:02 UTC, twister65 commented
> the PHP notice about the REMOTE_ADDR it has been already solved here :
> [joomla-framework/utilities#23](https://github.com/joomla-framework/utilities/pull/23)
> but that framework version of the utilities package it is still not in J4

Please, test PR #27996

2020-02-22 20:32 UTC, twister65 commented
Export database job plugin:
[plg_job_exportdb.zip](https://github.com/joomla/joomla-cms/files/4239884/plg_job_exportdb.zip)

2020-02-22 20:32 UTC, twister65 commented
I have tested this item :white_check_mark: successfully on 4d0589f3c0a971cf3b637f76db6e0594a13f91de<br /><br />with the export database job plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25022">issues.joomla.org/tracker/joomla-cms/25022</a>.</sub>

2020-06-13 08:31 UTC, alikon commented
redone in  #29592

2020-06-13 08:31 UTC, closed without merging