Add prepared statements for plg_authentication_cookie
joomla/joomla-cms pull request #25048
Opened 2019-05-29 20:02 UTC by HLeithner

### Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions

**This PR affect the Joomla Authentication System - handle with care**

Use the plugin in all ways you can think of.

* Login
* Logout
* use remember me
* close/open browser
* try with and without force password reset

### Expected result
Nothing changed.

2019-05-29 20:45 UTC, Quy commented on plugins/authentication/cookie/cookie.php
>  			->where($this->db->quoteName('series') . ' = ' . $this->db->quote($series))
Bind.

2019-05-30 22:42 UTC, Quy commented on plugins/authentication/cookie/cookie.php
>  			->delete('#__user_keys')
Apply `$db->quoteName`

2019-06-06 07:25 UTC, alikon requested changes

2019-06-06 07:25 UTC, alikon commented on plugins/authentication/cookie/cookie.php
> +				->bind(':userid', $results[0]->user_id, ParameterType::INTEGER);
` user_id varchar(150) NOT NULL,`
```suggestion
				->bind(':userid', $results[0]->user_id);
```

2019-06-11 12:54 UTC, alikon commented on plugins/authentication/cookie/cookie.php
> +			->bind(':now', time(), ParameterType::INTEGER);
` 'time' varchar(200) NOT NULL,`
```suggestion
			->bind(':now', time());
```

2019-07-02 23:51 UTC, Quy commented on plugins/authentication/cookie/cookie.php
> +use Joomla\Database\ParameterType;
```suggestion
```

2019-07-09 08:36 UTC, SharkyKZ commented on plugins/authentication/cookie/cookie.php
> +			->bind(':now', time());
>Notice: Only variables should be passed by reference

Assign `time()` to a variable.

2019-07-09 08:39 UTC, HLeithner commented on plugins/authentication/cookie/cookie.php
> +			->bind(':now', time());
would sql NOW() work?

2019-07-09 08:45 UTC, SharkyKZ commented on plugins/authentication/cookie/cookie.php
> +			->bind(':now', time());
No, it's not the same.

2019-07-10 18:31 UTC, HLeithner commented on plugins/authentication/cookie/cookie.php
> +			->bind(':now', time());
ok

2019-07-17 08:28 UTC, SharkyKZ commented
I have tested this item :white_check_mark: successfully on 494697c99aad24873f49c54f13530b91559ab28c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25048">issues.joomla.org/tracker/joomla-cms/25048</a>.</sub>

2019-07-18 22:14 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 494697c99aad24873f49c54f13530b91559ab28c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25048">issues.joomla.org/tracker/joomla-cms/25048</a>.</sub>

2019-07-18 22:14 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25048">issues.joomla.org/tracker/joomla-cms/25048</a>.</sub>

2019-07-23 18:21 UTC, merged

2019-07-23 18:21 UTC, wilsonge commented
Thanks!