Add prepared statements for plg_content_contact
joomla/joomla-cms pull request #25052
Opened 2019-05-29 20:04 UTC by HLeithner

### Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Use the plugin in all ways you can think of.

* Create users
* Create contacts linked to the users
* Create articles linked to different users
* Contact should be shown at the article
* use different settings in the plugin

### Expected result
Nothing changed.

2019-05-29 23:29 UTC, Quy commented on plugins/content/joomla/joomla.php
> +				->bind(':stageid', $stageId);
```suggestion
				->bind(':stageid', $stageId, ParameterType::INTEGER));
```

2019-05-31 01:56 UTC, Quy commented on plugins/content/joomla/joomla.php
>  				->where($db->quoteName('t.published') . '= 1')
```suggestion
				->where($db->quoteName('t.published') . ' = 1')
```

2019-05-31 01:57 UTC, Quy commented on plugins/content/joomla/joomla.php
>  				->where($db->quoteName('s.published') . '= 1')
```suggestion
				->where($db->quoteName('s.published') . ' = 1')
```

2019-05-31 13:47 UTC, Quy commented on plugins/content/contact/contact.php
> +		$userid = (int) $created_by;
Is this variable necessary? Just add it directly to the bind statement?

2019-05-31 13:48 UTC, Quy commented on plugins/content/joomla/joomla.php
> +			->from($query->quoteName('#__workflow_stages', 's'))
There is a mix of `$query->` and `$db->`. Pick one?

2019-05-31 13:58 UTC, HLeithner commented on plugins/content/contact/contact.php
> +		$userid = (int) $created_by;
Yes it's not needed.

2019-05-31 13:59 UTC, HLeithner commented on plugins/content/joomla/joomla.php
> +			->from($query->quoteName('#__workflow_stages', 's'))
That file was in the wrong PR and has been removed.

2019-06-06 07:17 UTC, alikon commented on plugins/content/contact/contact.php
> +			$query->where('(' . $db->quoteName('contact.language') . ' IN ('
use `whereIn()`

2019-06-06 07:17 UTC, alikon requested changes

2019-06-06 07:17 UTC, alikon commented on plugins/content/contact/contact.php
> +			->bind(':createdby', (int) $created_by, ParameterType::INTEGER);
```suggestion
			->bind(':createdby', $created_by, ParameterType::INTEGER);
```

2019-06-09 17:38 UTC, HLeithner commented on plugins/content/contact/contact.php
> +			$query->where('(' . $db->quoteName('contact.language') . ' IN ('
Thats not possible because we have a OR clause to the whereIn clause... or do you have a better way?

2019-07-03 07:30 UTC, SharkyKZ commented on plugins/content/contact/contact.php
> +				$db->quoteName(['contact.alias', 'contact.catid', 'contact.webpage', 'contact.email_to'])
This is failing due to nested array. Something like this works:

    ->select('MAX(' . $db->quoteName('contact.id') . ') AS contactid')
    ->select($db->quoteName(['contact.alias', 'contact.catid', 'contact.webpage', 'contact.email_to']))

2019-07-11 04:05 UTC, Quy commented on plugins/content/contact/contact.php
>  		$this->db->setQuery($query);
```suggestion
		$db->setQuery($query);
```

2019-10-09 22:22 UTC, wilsonge commented
Conflicts please

2019-10-18 14:15 UTC, HLeithner commented
@wilsonge conflicts solved

2019-10-18 15:26 UTC, waader commented
With "Link to Author's Contact Page" set to yes I get the following error in frontend:

1140 In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'joomla_db40.contact.alias'; this is incompatible with sql_mode=only_full_group_by 

I am using a bitnami package with mysql 8.0.17 and I don´t know whether this sql_mode configuration is exotic.

2019-10-19 23:17 UTC, wilsonge commented
@richard67 or @alikon i suspect this means we have an issue here in postgresql too. Can either of you too take a look?

2019-10-19 23:21 UTC, richard67 commented
> I am using a bitnami package with mysql 8.0.17 and I don´t know whether this sql_mode configuration is exotic.

No, is not more exotic, is more standard conmforming. We have to check, but today is too late for me now.

2019-10-19 23:23 UTC, richard67 commented
@wilsonge @HLeithner In drone I only see PHPCS errors.

2019-10-19 23:27 UTC, richard67 commented
@wilsonge What I can see in code looks as if this group by error was there also before this PR.

@HLeithner In general wgen you have a select statement which contains aggregate functions like MAX() and some other columns not being aggregated in the select list, then the statement has to be grouped by there other columns.

E.g. `SELECT MAX(thiscolumn), thatcolumn FROM sometable`=> error in oracle or postgres or any other normal database, and since mysql 8 with new defaults also there.

`SELECT MAX(thiscolumn), thatcolumn FROM sometable GROUP BY thatcolumn` => correct.

As I said, to me it seems this was also wrong before this PR.

2019-10-20 10:24 UTC, richard67 commented
@wilsonge The error has definitely been there long before this PR, and to add group by is not the right solution. The right way is to get the MAX(contact.id) in a separate query, either a subquery of or a join to a 2nd query, which then gets the other columns for that particular contact.id. Subqueries normally shall be avoided and joins shall be used if possible for performance reasons, at least that's what I've learned in my Oracle expert trainings.

It is definitely wrong SQL like it is done now, and the only reason why it worked was that some server variable was set to allow that and automatically add a group by (which is wrong anyway) for compatibility with older MySQL versions.

I'll try to fix that today but it is not easy for me as being used to Oracle SQL, where syntax for joins is a bit different to what we have in MySQL or PG. So I might need reviewers and testers later.

I think we may have this error at several other places, too, not sure if I can find time to find them all.

2019-10-20 11:16 UTC, richard67 commented
@HLeithner @wilsonge Please check [https://github.com/HLeithner/joomla-cms/pull/28]( https://github.com/HLeithner/joomla-cms/pull/28).

2019-10-20 13:02 UTC, richard67 commented
All tests passed in Drone, including all mysql8 and postgresql related :smile:

2019-10-20 13:08 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on c2760adef4bcff2e6bf6e91272335a497adee021<br /><br />Tested with MySQL 5.7 and PostgreSQL 10.10.

@waader Could you test this PR again and see if you still have this issue you've mentioned in your comment https://github.com/joomla/joomla-cms/pull/25052#issuecomment-543796749[https://github.com/joomla/joomla-cms/pull/25052#issuecomment-543796749](https://github.com/joomla/joomla-cms/pull/25052#issuecomment-543796749 "https://github.com/joomla/joomla-cms/pull/25052#issuecomment-543796749")? It should be fixed now. The server variable setiing is not exotic, it is more standard. Before MySQL 8, the default value was for compatibility with older MySQL versions, but with MySQL 8 they want to have default settings closed to standards, that's why issues appear more with 8. I would be happy if you could find some time for a test. Thanks in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25052">issues.joomla.org/tracker/joomla-cms/25052</a>.</sub>

2019-10-20 15:32 UTC, waader commented
The error message changed a little bit to:
1140 In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'joomla4.contact_2.alias'; this is incompatible with sql_mode=only_full_group_by

Tested with mysql 8.0.17

2019-10-20 15:38 UTC, richard67 commented
@waader @HLeithner @wilsonge Hmm, it seems then I have to change it to use a subquery. Stay tuned, it may take a while because have other stuff to do right now.

2019-10-20 16:34 UTC, richard67 commented
@SharkyKZ Do you have an idea how to change the SQL statement handled with this PR to using a subquery in an elegant way?

2019-10-20 17:12 UTC, SharkyKZ commented
We don't support `ONLY_FULL_GROUP_BY`. See #12494 for reference.

2019-10-20 17:31 UTC, richard67 commented
But I think we could fix it here at least by using a subquery for the "contact_1" part in that statement.

2019-10-20 17:34 UTC, SharkyKZ commented
I think `MAX()` can be removed. Instead order by ID descending and set 1 limit.

2019-10-20 17:37 UTC, richard67 commented
> 
> 
> I think `MAX()` can be removed. Instead order by ID descending and set 1 limit.

@SharkyKZ Good idea. Could you make a code proposal here as comment or a PR against Harald's branch? That would be fastest solution. I would have to look that up, limit and so on.

2019-10-20 17:47 UTC, SharkyKZ commented
OK, I will. This will also correct the issue where data from different contacts is being selected. I think the idea here was to use the newest contact.

2019-10-20 17:59 UTC, SharkyKZ commented
Submitted https://github.com/HLeithner/joomla-cms/pull/30.

2019-10-21 05:17 UTC, SharkyKZ commented on plugins/content/contact/contact.php
> +		$query->select($db->quoteName('contact.id', 'contactid'))
This is actually doing the opposite of reducing function calls. `Joomla\Database\DatabaseDriver::quoteName()` is written in a recursive manner. If array is passed, it runs additional checks and then calls `quoteName()` again for each array element.

2019-10-21 18:28 UTC, richard67 commented
@waader Sorry to bother you again. Could you test this PR again? With the last change it should work now. I will test, too, but because I don't have MySQL 8 I could not reproduce the issue you had.

2019-10-21 18:35 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on acbbd4e94d73e43d45281dd1a14df5669e198ca8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25052">issues.joomla.org/tracker/joomla-cms/25052</a>.</sub>

2019-10-21 19:32 UTC, waader commented
I have tested this item :white_check_mark: successfully on acbbd4e94d73e43d45281dd1a14df5669e198ca8<br /><br />Works now for mysql8 and postgresql. Thank you Richard et al.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25052">issues.joomla.org/tracker/joomla-cms/25052</a>.</sub>

2019-10-21 19:34 UTC, richard67 commented
Thanks to @HLeithner and @SharkyKZ , they fixed it. I've only tried and failed.

2019-10-21 19:50 UTC, SharkyKZ commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25052">issues.joomla.org/tracker/joomla-cms/25052</a>.</sub>

2019-10-21 20:46 UTC, merged

2019-10-21 20:46 UTC, wilsonge commented
Good teamwork guys and thanks for the test spotting this @waader !

2019-10-21 20:47 UTC, HLeithner commented on plugins/content/contact/contact.php
> +		$query->select($db->quoteName('contact.id', 'contactid'))
> This is actually doing the opposite of reducing function calls. `Joomla\Database\DatabaseDriver::quoteName()` is written in a recursive manner. If array is passed, it runs additional checks and then calls `quoteName()` again for each array element.

You are right but I think the quoteName function should be optimized.

2019-10-21 20:47 UTC, HLeithner commented
thx for testing and fixing!