Add prepared statements for plg_fields_sql
joomla/joomla-cms pull request #25056
Opened 2019-05-29 20:07 UTC by HLeithner

This PR tries to move the SQL custom field into a prepared statement, at least for the values part.

### Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions

* Create a SQL custom field
* Use several SQL queries in the custom field
* check the frontend if the expected result could be found.

### Expected result
Nothing changed.

2019-06-06 07:03 UTC, alikon requested changes

2019-06-06 07:03 UTC, alikon commented on plugins/fields/sql/tmpl/sql.php
> +$sql .= ' HAVING VALUE IN (' . implode(bindNames) . ')';
`$sql .= ' HAVING VALUE IN (' . implode(bindNames) . ')'`   need 1 dollar ($) before bindNames :smile

2019-06-10 06:25 UTC, alikon approved these changes

2019-07-10 06:58 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
> +$query->setQuery($sql);
```suggestion
$db->setQuery($sql);
```

2019-07-10 07:05 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
> +$query->setQuery($sql);
Move this inside `try`.

2019-07-10 08:03 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
>  try
```suggestion
try
{
	$db->setQuery($query);
```

2019-07-10 08:05 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
> +$sql .= ' HAVING VALUE IN (' . implode($bindNames) . ')';
```suggestion
$sql .= ' HAVING ' . $db->quoteName('value') . ' IN (' . implode(',', $bindNames) . ')';
```
(value is the column alias in this case).

2019-07-10 08:06 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
> +$bindNames = $query->bindArray((array) $value, ParameterType::INTEGER);
Don't assume integer.

2019-07-10 08:08 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
> -$value     = (array) $value;
Revert this. It's used in `in_array()` at the bottom.

2019-07-10 08:10 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
>  try
Inside `catch` change `$query` to the original query (`$fieldParams->get('query', '')`).

2019-07-10 18:21 UTC, HLeithner commented on plugins/fields/sql/tmpl/sql.php
> +$bindNames = $query->bindArray((array) $value, ParameterType::INTEGER);
In this case I think it should be string even if integer. The complete field is dangerous...

2019-07-11 05:35 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
>  try
Still need to make the proposed change. Otherwise it's running an empty query.

2019-07-11 05:39 UTC, SharkyKZ commented on plugins/fields/sql/tmpl/sql.php
> +	$query->setQuery($fieldParams->get('query', ''));
You can remove this and just do $db->setQuery($fieldParams->get('query', ''))` below. Otherwise this  should be a new query object without bindings.

2019-07-11 19:22 UTC, HLeithner commented
Hope it's ok now @shanginn

2019-07-15 07:58 UTC, SharkyKZ commented
It's still running an empty query.

2019-12-27 22:48 UTC, HLeithner commented on plugins/fields/sql/tmpl/sql.php
>  try
I changed this as you wish but this doesn't make any different because $query already got the $sql by ->setQuery()...

Anyway it's now more readable.

2019-12-27 22:54 UTC, HLeithner commented
I found another problem, if $db->setQuery($query) is not in the try catch construct and the sql query is broken (for example $value is 0 which is not possible any longer) then joomla raise an exception on setQuery because we do a Driver->prepareStatement() in this function.

This is already true for the current implementation...

Also I'm not sure how the query with the HAVING clause could fail and the original query would work.

if you have a query

```select id as value, title as text from #__content```

then the having variant will always work

```select id as value, title as text from #__content HAVING VALUE IN ('1');```

if the query fails because no value column exists it will also fail without the having clause because we expect a value column...

What do I miss?

2019-12-30 06:52 UTC, SharkyKZ commented
We don't know what kind of query is entered so adding anything could break it. For example if entered query ends in `;` the code already fails as it results in this:

    select id as value, title as text from #__content; HAVING VALUE IN ('1');

Another case, the query could already have a `HAVING` clause.

2019-12-30 06:59 UTC, SharkyKZ commented
We could avoid the first scenario by loading SQL into the query object and using the API to build having clause instead of directly manipulating SQL.

2019-12-30 09:17 UTC, HLeithner commented
> We could avoid the first scenario by loading SQL into the query object and using the API to build having clause instead of directly manipulating SQL.

Jquery doesn't split the query into parts.

So we should keep it this way until someone builds the ultimate query builder ;)

2019-12-31 08:27 UTC, SharkyKZ commented
Hm, you're right. Although we could still use query methods for HAVING clause. But it's fine either way. Just lowercase and quote `value` please because it's a column name.

2020-01-03 22:51 UTC, SharkyKZ commented
I have tested this item :white_check_mark: successfully on a952aed30b21dbe9e3c5ea531508fcd2b48791ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25056">issues.joomla.org/tracker/joomla-cms/25056</a>.</sub>

2020-01-04 03:08 UTC, Quy commented
I have tested this item :white_check_mark: successfully on a952aed30b21dbe9e3c5ea531508fcd2b48791ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25056">issues.joomla.org/tracker/joomla-cms/25056</a>.</sub>

2020-01-04 03:08 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25056">issues.joomla.org/tracker/joomla-cms/25056</a>.</sub>

2020-01-04 14:14 UTC, merged