Add prepared statements for plg_finder_categories
joomla/joomla-cms pull request #25057
Opened 2019-05-29 20:08 UTC by HLeithner

### Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Use the plugin in all ways you can think of.

This plugin index the categories in smart search.

* Activate smart search
* Create categories
* Change the category text
* Delete categories
* Check the index of smart search in the backend and frontend or tables-

### Expected result
Nothing changed.

2019-05-29 21:08 UTC, Quy commented on plugins/finder/categories/categories.php
> +					->bind(':plgFinderCategoriesId', (int) $pk);
Add ParameterType.

2019-05-30 23:16 UTC, Quy commented on plugins/finder/categories/categories.php
> +
```suggestion
```

2019-05-31 13:43 UTC, Quy commented on plugins/finder/categories/categories.php
> +						$query->quoteName('#__categories', 'c') .
```suggestion
						$query->quoteName('#__categories', 'c'),
```

2019-05-31 13:43 UTC, Quy commented on plugins/finder/categories/categories.php
> +						' ON ' . $query->quoteName('c.id') . ' = ' . $query->quoteName('a.parent_id')
```suggestion
						$query->quoteName('c.id') . ' = ' . $query->quoteName('a.parent_id')
```

2019-06-01 10:07 UTC, Quy commented on plugins/finder/categories/categories.php
> +					->bind(':plgFinderCategoriesId', (int) $pk, ParameterType::INTEGER);
Is `(int)` still required now that `ParameterType::INTEGER` is specified?

2019-06-02 14:56 UTC, HLeithner commented on plugins/finder/categories/categories.php
> +					->bind(':plgFinderCategoriesId', (int) $pk, ParameterType::INTEGER);
Sadly yes, most driver don't care about the paramtertype, but I would like to validate atleast integer type in our database laye. There is a discussion about performance hit if we validate each data type.

2019-06-05 06:32 UTC, alikon requested changes

2019-06-05 06:32 UTC, alikon commented on plugins/finder/categories/categories.php
> +			->from($db->quoteName('#__categories', 'a'))
there is not need of an alias `a`

2019-06-05 10:06 UTC, HLeithner commented on plugins/finder/categories/categories.php
> +			->from($db->quoteName('#__categories', 'a'))
? there are many uses of the alias in the query. 

Rewriting the query is not part of the PR series.

2019-06-06 07:00 UTC, alikon commented on plugins/finder/categories/categories.php
> +					->bind(':plgFinderCategoriesId', (int) $pk, ParameterType::INTEGER);
```suggestion
					->bind(':plgFinderCategoriesId', $pk, ParameterType::INTEGER);
```

2019-06-10 06:24 UTC, alikon approved these changes

2019-06-11 09:49 UTC, merged

2019-06-11 09:49 UTC, wilsonge commented
Thanks!