Add prepared statements for plg_installer_override
joomla/joomla-cms pull request #25058
Opened 2019-05-29 20:09 UTC by HLeithner

### Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Test instruction could be found in the original PR:
https://github.com/joomla/joomla-cms/pull/21851

> Video: https://www.youtube.com/watch?v=l0_jFjswObI
For this, you need an extension which has an update with new changes in extension files.
So,
You can use these components
com_helloworld.0.0.1 https://www.dropbox.com/s/106cgn1lclp9dxm/com_helloworld.0.0.1.zip?dl=0
com_helloworld.0.0.2 https://www.dropbox.com/s/xhl8p0nz3wdvapj/com_helloworld.0.0.2.zip?dl=0
Download this branch/PR then install fresh Joomla using this branch/PR.
Go to the template manager.
Create an override of that extension before the update.
See the diff view of that file by using a toggle button in the top right corner. ** Expected:** No difference.
Now update your extension. ** Expected:** If your created override file got any update in core you can see notification message number of files updated.
Go to template manager check new tab you can see which files are updated.
Click on the name of the file you will get redirect to edit view of that file.
Now you can see the changes in diff view.
Adjust your override file if you want and then you can delete that file list history or mark as checked.

### Expected result
Nothing changed.

2019-05-29 21:12 UTC, Quy commented on plugins/installer/override/override.php
> +							$db->quoteName('modified_date') . ' = :$modifiedDate',
```suggestion
							$db->quoteName('modified_date') . ' = :modifiedDate',
```

2019-05-29 21:12 UTC, Quy commented on plugins/installer/override/override.php
> +			$bindArray = \array_merge(
```suggestion
			$bindArray = array_merge(
```

2019-05-29 21:23 UTC, mbabker commented on plugins/installer/override/override.php
> +			$bindArray = \array_merge(
Since we're talking about a non-namespaced file, this change is fine, but...

Depending on the coding style rules in place and the preferences of the developer, there are a bunch of optimized functions in PHP that it is better to import (either with `use function array_merge;` or `\array_merge();`) than to let PHP first try to find that function in the current namespace then fall back into the global namespace.  If you grasp enough C code, look into `zend_try_compile_special_func` in the PHP source code for this list of functions ([this method](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.15.0/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php#L346) in PHP-CS-Fixer has that same list; I've run an opinionated PHP-CS-Fixer definition over the Framework files which included this rule).

2019-05-30 08:19 UTC, HLeithner commented on plugins/installer/override/override.php
> +			$bindArray = \array_merge(
Do our coding style guide has a definition for this?

Should every PHP function call that isn't in this list be called directly from the global namespace?

```php
            // @see https://github.com/php/php-src/blob/PHP-7.4/Zend/zend_compile.c "zend_try_compile_special_func"
            'array_key_exists',
            'array_slice',
            'assert',
            'boolval',
            'call_user_func',
            'call_user_func_array',
            'chr',
            'count',
            'defined',
            'doubleval',
            'floatval',
            'func_get_args',
            'func_num_args',
            'get_called_class',
            'get_class',
            'gettype',
            'in_array',
            'intval',
            'is_array',
            'is_bool',
            'is_double',
            'is_float',
            'is_int',
            'is_integer',
            'is_long',
            'is_null',
            'is_object',
            'is_real',
            'is_resource',
            'is_string',
            'ord',
            'strlen',
            'strval',
            // @see https://github.com/php/php-src/blob/php-7.2.6/ext/opcache/Optimizer/pass1_5.c
            'constant',
            'define',
            'dirname',
            'extension_loaded',
            'function_exists',
            'is_callable',
```

2019-05-30 12:45 UTC, mbabker commented on plugins/installer/override/override.php
> +			$bindArray = \array_merge(
The functions in that list should be called from the global namespace, the rest of the functions it doesn't necessarily matter as much since those aren't optimized.  Some coding standards have taken it to the point that every function is imported from the global namespace and not "only" the optimized function list.

No, there isn't a Joomla PHPCS enforced rule for this.

2019-05-30 13:22 UTC, HLeithner commented on plugins/installer/override/override.php
> +			$bindArray = \array_merge(
ok in this case it's more or less useless because the file is not namespaced and it's not an optimized function that require a the global namespace or fully-qualified call.

If I understand this article correct, the function list above needs to be called fully-qualified to get the optimisation.
https://phpinternals.net/articles/optimising_internal_functions_via_new_opcode_instructions#optimising-the-ord-function

2019-05-30 13:22 UTC, HLeithner commented on plugins/installer/override/override.php
> +			$bindArray = \array_merge(
So we should add this to our code style.

2019-06-05 06:26 UTC, alikon requested changes

2019-06-05 06:26 UTC, alikon commented on plugins/installer/override/override.php
> +					$pk->id,
this smells wrong to me `$pk->id` is not `ParameterType::STRING`

2019-06-06 06:56 UTC, alikon requested changes

2019-06-06 06:56 UTC, alikon commented on plugins/installer/override/override.php
> +			->where($db->quoteName('hash_id') . ' = :id')
`hash_id varchar(255) NOT NULL DEFAULT '', `   so don't need ParameterType::INTEGER

2019-06-10 06:23 UTC, alikon approved these changes

2019-06-11 09:49 UTC, merged

2019-06-11 09:49 UTC, wilsonge commented
Thanks!