[3.9.7] Fixing a mistake made with PR #24397 + fixing setting description for clarity
joomla/joomla-cms pull request #25062
Opened 2019-05-30 08:18 UTC by AndySDH

Pull Request for Issue #24754 

### Summary of Changes

PR #24397, introduced in Joomla 3.9.5, added a check to display the custom field on the frontend based on a parameter that was meant to be a check for the edit form, and not for the frontend display.

The author of that PR said I should create another PR myself so here it is.

As explained in this comment https://github.com/joomla/joomla-cms/issues/24754#issuecomment-496509135 - there already is another setting that controls whether a custom field should be displayed in the frontend or not.

That "Show on" setting has always been for controlling where the field can be edited, not displayed. It just has a bad/label description.

With this PR I will also take care of improving the description and label of that setting so that it causes no confusion on what it's actually doing and supposed to do.

### Testing Instructions

- Create a Custom Field
- Set the "Can be edited in" paramater to "Administrator"
- Assign a value to it in an article

### Current 3.9.6 result

- The field is not displayed on the frontend article either

### Expected result with this PR

- The field should be displayed on the frontend article, but not on the frontend editing form.

### Documentation Changes Required
Yes.
The label and description of the setting should be changed accordingly also here:
https://docs.joomla.org/J3.x:Adding_custom_fields/Parameters_for_all_Custom_Fields

2019-05-30 09:48 UTC, richard67 commented
@joomlahenk Please test

2019-05-30 10:06 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 7e7571c07fa4a830cf3383036bcd211d20daff83<br /><br />I've tested it with an extended test compared to the testing instructions in the description:
- Created 2 fields, one with "Can be edited in" (or "Showon" without this PR) set to "Administrator" and the other set to "Site".
- Checked that when editing the article with both fields having assigned a value, the 1st field is editable in tab "Fields" in the artricle edit view in the backend and the 2nd field is not, and for frontend editing it is vice versa.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25062">issues.joomla.org/tracker/joomla-cms/25062</a>.</sub>

2019-05-30 10:40 UTC, Quy commented on administrator/language/en-GB/en-GB.com_fields.ini
> +COM_FIELDS_FIELD_SHOW_ON_LABEL="Can be edited in"
Capitalize first letter of each word since it is a label. Would this be better `Editable In`?

2019-05-30 10:44 UTC, richard67 commented on administrator/language/en-GB/en-GB.com_fields.ini
> +COM_FIELDS_FIELD_SHOW_ON_LABEL="Can be edited in"
`Editable In` looks good to me, too.

2019-05-30 11:03 UTC, AndySDH commented on administrator/language/en-GB/en-GB.com_fields.ini
> +COM_FIELDS_FIELD_SHOW_ON_LABEL="Can be edited in"
Sure why not.

2019-05-30 11:10 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on a4947b412633b10d65d469bff8c81d000d9782a5<br /><br />I've tested it with an extended test compared to the testing instructions in the description:
- Created 2 fields, one with "Can be edited in" (or "Showon" without this PR) set to "Administrator" and the other set to "Site".
- Checked that when editing the article with both fields having assigned a value, the 1st field is editable in tab "Fields" in the artricle edit view in the backend and the 2nd field is not, and for frontend editing it is vice versa.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25062">issues.joomla.org/tracker/joomla-cms/25062</a>.</sub>

2019-05-30 11:12 UTC, Quy commented
I have tested this item :white_check_mark: successfully on a4947b412633b10d65d469bff8c81d000d9782a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25062">issues.joomla.org/tracker/joomla-cms/25062</a>.</sub>

2019-05-30 11:13 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25062">issues.joomla.org/tracker/joomla-cms/25062</a>.</sub>

2019-05-30 11:16 UTC, AndySDH commented
By the way, I noticed that the documentation here https://docs.joomla.org/J3.x:Adding_custom_fields/Parameters_for_all_Custom_Fields is outdated beyond this PR.
Joomla 3.9 changed the way Custom Field options are arranged and it was not reflected in the documentation there

2019-05-30 12:10 UTC, alikon requested changes

2019-05-30 12:10 UTC, alikon commented on administrator/language/en-GB/en-GB.com_fields.ini
> +COM_FIELDS_FIELD_SHOW_ON_DESC="On which part of the site should the field be editable?"
`COM_FIELDS_FIELD_SHOW_ON_LABEL` and `COM_FIELDS_FIELD_SHOW_ON_DESC`  should be changed as well to reflect the change

2019-05-30 12:38 UTC, AndySDH commented on administrator/language/en-GB/en-GB.com_fields.ini
> +COM_FIELDS_FIELD_SHOW_ON_DESC="On which part of the site should the field be editable?"
What you mean?

2019-05-30 12:50 UTC, alikon commented on administrator/language/en-GB/en-GB.com_fields.ini
> +COM_FIELDS_FIELD_SHOW_ON_DESC="On which part of the site should the field be editable?"
the "show" is different from "edit" in my humble english knowledge

we have a language key string `(COM_FIELDS_FIELD_SHOW_ON_LABEL)` that not reflect the translation "Editable In"

2019-05-30 14:13 UTC, AndySDH commented on administrator/language/en-GB/en-GB.com_fields.ini
> +COM_FIELDS_FIELD_SHOW_ON_DESC="On which part of the site should the field be editable?"
Oh you mean the key string itself. No big deal but ok I will fix that too then.

2019-05-30 15:13 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 6e5a160c6de6d1f603d6c478928527e61e513adf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25062">issues.joomla.org/tracker/joomla-cms/25062</a>.</sub>

2019-05-30 15:50 UTC, HLeithner commented
@brianteeman would you like to check the language strings before I merge this PR?

2019-06-05 15:37 UTC, merged

2019-06-05 15:37 UTC, HLeithner commented
thx

2019-07-11 11:46 UTC, AndySDH commented
@HLeithner Was this somehow undone by recent changes? This seems to have reverted to "Show On" currently in Joomla! 3.9.10.

![image](https://user-images.githubusercontent.com/25923699/61048502-44940b00-a3e2-11e9-993d-3c164d5718b9.png)

2019-07-11 11:57 UTC, AndySDH commented
Nevermind, ignore, my bad