Added event onContentValidateData
joomla/joomla-cms pull request #25103
Opened 2019-06-03 11:03 UTC by BrainforgeUK

Pull Request for Issue # 24901.

Summary of Changes

Added event onContentValidateData
Event onUserBeforeDataValidation now depracted
Testing Instructions

Create a field plugin which implements onContentValidateData function like this...
public function onContentValidateData($form, &$data) {
// Change the data in some way
}
Expected result

The data get's changed.
Actual result

The data get's changed.
Documentation Changes Required

Add documentation for onContentValidateData event.
Add documentation for the existing, but undocumented and now deprecated, onUserBeforeDataValidation event.

2019-06-03 11:05 UTC, BrainforgeUK commented
Replaces pull request 24925

2020-02-13 14:54 UTC, sakiss commented
I cannot understand the usefulness of that change.
Seems like a rename of an event for the shake of renaming it.

2020-02-13 16:07 UTC, BrainforgeUK commented
The event name onUserBeforeDataValidation implies it is only for user validation.
Changing to a generic event means reading the code makes a lot more sense when using the event in other extensions.

2020-02-13 21:01 UTC, sakiss requested changes

2020-02-13 21:01 UTC, sakiss commented on libraries/src/MVC/Model/FormModel.php
> +		Factory::getApplication()->triggerEvent('onContentValidateData', array($form, &$data));
To be consistent with the other events (using before/after) something like `onBeforeDataValidation` possibly would be better

2020-02-13 21:13 UTC, sakiss commented on libraries/src/MVC/Model/FormModel.php
> -		Factory::getApplication()->triggerEvent('onUserBeforeDataValidation', array($form, &$data));
I would prefer first checking if the new trigger exist and if not (else) call the old one. Now both (old  and new) could be called, which can cause confusion.

2020-02-13 21:19 UTC, BrainforgeUK commented
My main point in raising / proposing this is to replace the event name with something more meaningful when using it outside of user validation - code easier to read / search.

It occurs during validation so an On... name places it within validation while OnBefore... would imply it is outside validation.

A quick code search shows other **OnContent...** events including **onContentBeforeDelete** and **onContentAfterDelete** so naming it **onContentValidateData** looks like it fits in with previously used naming conventions.

2020-02-13 21:35 UTC, sakiss commented
> My main point in raising / proposing this is to replace the event name with something more meaningful when using it outside of user validation - code easier to read / search.
> 
> It occurs during validation so an On... name places it within validation while OnBefore... would imply it is outside validation.
> 
> A quick code search shows other **OnContent...** events including **onContentBeforeDelete** and **onContentAfterDelete** so naming it **onContentValidateData** looks like it fits in with previously used naming conventions.

The event is triggered before the validation logic. It is important to clarify if it is called before or after, to be clear what actions could be carried out through that.

2020-02-19 14:02 UTC, SharkyKZ commented on libraries/src/MVC/Model/FormModel.php
> -		Factory::getApplication()->triggerEvent('onUserBeforeDataValidation', array($form, &$data));
Both events need to be triggered so existing plugins with `onUserBeforeDataValidation` continue working.

2020-04-01 18:52 UTC, merged

2020-04-01 18:52 UTC, wilsonge commented
Thanks!