Distinct position check
joomla/joomla-cms pull request #25131
Opened 2019-06-06 07:58 UTC by softarius

### Summary of Changes
Method  _getListCount of class BaseDatabaseModel select query with keyword "distinct"

### Testing Instructions
- insert into any table repeated values
- create a model extends ListModel
- in method getListQuery  write SQL query for getting "dictionary" like "select distinct field1 from table1"
- write view and layout with pagination for getting a table this dictionary 
I wrote a component (only PostgreSQL supported) for demonstrating (attached).
Use URL `joomlasite/index.php?option=com_person&view=names`

[com_person.zip](https://github.com/joomla/joomla-cms/files/3260519/com_person.zip)

### Expected result
Correct pagination
![espected](https://user-images.githubusercontent.com/7361866/59016074-2702dd00-8849-11e9-8bb8-90426ab9aaa5.PNG)

### Actual result
Pagination with the wrong page counting, because distinct practically ignored
![actual](https://user-images.githubusercontent.com/7361866/59016049-1a7e8480-8849-11e9-9584-653cfb99549b.PNG)

### Documentation Changes Required
Nothing

2019-06-06 08:03 UTC, franz-wohlkoenig commented
If this is a new Feature please rebaso on J4 as J3 is only Bug-Fixing.

2019-06-06 08:17 UTC, alikon commented
@franz-wohlkoenig 
sounds like a bug to me

2019-08-18 14:17 UTC, zero-24 requested changes

2019-08-18 14:17 UTC, zero-24 commented on libraries/src/MVC/Model/BaseDatabaseModel.php
> +			&& stripos((string) $query, 'distinct') === false)
```suggestion
			&& stripos((string) strtolower($query), 'distinct') === false)
```

hmm should't we do a strtolower($query) here too as i could also write that key word in all upper case.

2019-08-19 10:18 UTC, HLeithner commented on libraries/src/MVC/Model/BaseDatabaseModel.php
> +			&& stripos((string) $query, 'distinct') === false)
stripos is already case insensitive no need to change this.

2019-08-20 00:47 UTC, zero-24 approved these changes

2019-08-20 11:43 UTC, HLeithner commented
It's a bug but should test all core components list views.

2019-09-18 16:28 UTC, SharkyKZ commented
Did anyone read the note?

>Note: Current implementation of this method assumes that getListQuery() returns a set of unique rows,
	 * thus it uses SELECT COUNT(*) to count the rows. In cases that getListQuery() uses DISTINCT
	 * then either this method must be overriden by a custom implementation at the derived Model Class
	 * or a GROUP BY clause should be used to make the set unique.

2019-09-19 06:36 UTC, softarius commented
> Did anyone read the note?
> 
> https://github.com/joomla/joomla-cms/blob/7bc411dc2e99ce15713a31b8e6f1d7ba64d229c7/libraries/src/MVC/Model/BaseDatabaseModel.php#L314-L317

I have read this note. The phrase about "must be overridden" similar to the description of the bug. Let's just fix it. 
The main idea of this fix - not use count(*) if distinct exists. It's all.

2019-09-22 12:26 UTC, SharkyKZ commented
There is no bug if you follow the documentation. You have to override the method in your model. And you should do that not just to get the correct result count but also to improve performance. That fallback method is extremely slow and should be avoided.

Furthermore, simple string manipulation like this is going to cause the slow query to run more often than it should, i.e. whenever anything contains the string `distinct`. This could be a table name, a column, a keyword or anything else. So at least, if maintainers don't mind, we should add distinct capability to Database API to correctly detect where distinct is actually used or not.

2019-12-27 16:54 UTC, richard67 commented
@SharkyKZ So should this PR be closed according to your previous comment?
@softarius If @SharkyKZ 's answer is yes, would you agree?

2019-12-30 06:41 UTC, SharkyKZ commented
It's up to maintainers to decide.

2019-12-30 11:50 UTC, HLeithner commented
I think you are right it brings more harm and the dev should do it right as in the description.

@softarius thanks anyway for your contribution.

2019-12-30 11:50 UTC, closed without merging