[4.0] Resolve LDAP Plugin Error
joomla/joomla-cms pull request #25191
Opened 2019-06-13 04:01 UTC by travisrisner

Pull Request for Issue #25180 .

### Summary of Changes
Ensure the username and email fields are using the 0 array key returned from the LDAP Symfony Package, otherwise. I tested this against an LDAP server I had setup.

I am unsure at this time how to write a test for this, but am reading up on it. If there's a specific team that needs to handle that, just let me know.

2019-06-13 05:10 UTC, richard67 requested changes

2019-06-13 05:10 UTC, richard67 commented on plugins/authentication/ldap/ldap.php
>  		$response->fullname = $entry->getAttribute($ldap_fullname) ?: $credentials['username'];
```suggestion
		$response->fullname = $entry->getAttribute($ldap_fullname)[0] ?? $credentials['username'];
```

Or maybe better some additional test so that `$credentials['username']` is used when `$entry->getAttribute($ldap_fullname)[0]` is an empty string? Or even when `trim($entry->getAttribute($ldap_fullname)[0])` is an empty string?

But so or so you have to use an array key also here.

2019-06-13 13:59 UTC, travisrisner commented
@richard67  what about something like that?

2019-06-13 16:23 UTC, richard67 commented
@travisrisner Looks good to me, elegant solution with the "&&" operator. Works for J4 because minimum PHP version for J4 is 7.something.

Unfortunately I need to set up an Ldap server before I can test, so it might be weekend then. Do you know if there is some kind of public Ldap test server web site available for testing?

2019-06-13 16:24 UTC, richard67 approved these changes

2019-06-13 16:29 UTC, richard67 commented
@HLeithner Is that PR sufficient, or does it also need to implement some unit test?

As far as I could see (am not 100% sure if I found all), there is no unit test yet for the ldap plugin, so it would need to write some kind of a stub for the ldap server, as long as the automated testing team has not developed a solution for testing against a real Ldap server.

As this PR really fixes a bug, we should not hold it back just because it does not implement a test which was not implemented before.

@mbabker What do you think about that?

2019-06-13 16:34 UTC, richard67 commented
Found some public ldap server for testing, see [https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/](https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/).

2019-06-13 16:39 UTC, mbabker commented
There's a reason I said the test team needs to work on that and not "this issue needs an accompanying test case"...

2019-06-13 16:42 UTC, richard67 commented
@mbabker I know, and I understood. I asked in order to be sure that it is ok because @HLeithner wrote about a test in the original issue #25180 . So this PR is ok?

2019-06-13 17:21 UTC, richard67 commented
Hmm, it seems the ldap test server I found still uses protocol version1, so it can't be used.

2019-06-13 19:37 UTC, richard67 requested changes

2019-06-13 19:37 UTC, richard67 commented on plugins/authentication/ldap/ldap.php
> +		$response->fullname = $entry->getAttribute($ldap_fullname)[0] ?? trim($entry->geAttribute($ldap_fullname)) ?: $credentials['username'];
```suggestion
		$response->fullname = $entry->getAttribute($ldap_fullname)[0] ?? trim($entry->geAttribute($ldap_fullname)[0]) ?: $credentials['username'];
```

Sorry I oversaw that before.

2019-06-13 19:50 UTC, richard67 approved these changes

2019-06-15 10:02 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 33c619c1d255672b5f622ac9903d213cdee13f8c<br /><br />Finally I've managed to configure the ldap plugin to use the public ldap test server ldap.forumsys.com.

Was a bit tricky, description for other testers will follow in a comment below.

Then I was able to reproduce the error from issue #25180 and verify that this PR here solves it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25191">issues.joomla.org/tracker/joomla-cms/25191</a>.</sub>

2019-06-15 10:16 UTC, richard67 commented
I've used following settings in the plugin for the test:

> Host:				ldap.forumsys.com
> Port:				389 (= default)
> LDAP V3:			Yes
> Negotiate TLS:		No
> Follow Referrals:		No
> Authorisation Method:	Bind and Search
> Base DN:			dc=example,dc=com
> Search String:		uid=[search]
> User's DN:			uid=[username],dc=example,dc=com
> Connect Username:	rieman
> Connect Password:	see [https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/](https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/)
> Map: Full Name:		cn
> Map: Email:			mail
> Map: User ID:		uid
> 

The `User's DN` parameter I had to fill in even if the help text says it is only used for direct bind. Same error I had with J3 (staging).

The direct bind method I did not get working, maybe the J4 plugin has other errors. With J3 (staging) I got both working.

User `gauss` is the one who logs in, password see [https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/](https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/). For this one, an exquivalent Joomla user exists.

User `riemann` does not exist in Joomla and is used only for ldap bind and lookup.

2019-06-15 10:23 UTC, richard67 commented
@travisrisner I've updated the description by some testing instructions in order to find some 2nd tester more easily.

2019-06-15 22:48 UTC, merged

2019-06-15 22:49 UTC, wilsonge commented
Merging on good test + code review. thanks!

2021-05-19 22:36 UTC, PhilETaylor commented
everyone missed the typo of the method name here ;-) 

`geAttribute` :-)