[4.0] - fix for current release text
joomla/joomla-cms pull request #25350
Opened 2019-06-27 17:41 UTC by alikon

#21994 # Summary of Changes
from
... `you'll receive notifications for all updates of the current Joomla release (3.x)`....
to 
... `you'll receive notifications for all updates of the current Joomla release (4.x)`....

### Testing Instructions
on review  or visit `com_joomlaupdate`

2019-06-27 17:54 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on f2b8b056fe19ee02d6a6a26d12da7c5813374285<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25350">issues.joomla.org/tracker/joomla-cms/25350</a>.</sub>

2019-06-27 17:55 UTC, Quy commented
I have tested this item :white_check_mark: successfully on f2b8b056fe19ee02d6a6a26d12da7c5813374285<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25350">issues.joomla.org/tracker/joomla-cms/25350</a>.</sub>

2019-06-27 17:55 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25350">issues.joomla.org/tracker/joomla-cms/25350</a>.</sub>

2019-06-27 18:32 UTC, richard67 requested changes

2019-06-27 18:32 UTC, richard67 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) and you will also be notified when the future major release (5.x) will be available. Before upgrading to 5.x you'll need to assess its compatibility with your environment."
```

2019-06-27 18:33 UTC, richard67 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
If you change current release to 4.0, you have to change future release to 5.0, too.

2019-06-27 18:41 UTC, alikon commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
sure if i will be still around when 5.x :smile

2019-06-27 18:43 UTC, richard67 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
Now with your changes the text does not make sense, because it speaks about 4.0 as current version and also as next major version (from the 4.0 point of view). So if you don't want to change like I suggested, then you have to remove that part about the future version completely. As it is now, it makes no sense!

2019-06-27 18:44 UTC, richard67 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
@brianteeman Please check if my comment above is right or wrong. Please check the complete language string and not just the begining.

2019-06-27 18:46 UTC, alikon commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
tbh, the better thing should be to re-phrase that sentence...
but i'm not the right one

2019-06-27 18:47 UTC, richard67 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
That's why I pinged a native speaker, too.

2019-06-28 11:30 UTC, wilsonge commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
Richard's changes are correct

2019-06-28 11:45 UTC, alikon commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
applied

2019-06-28 11:58 UTC, richard67 approved these changes

2019-06-28 15:48 UTC, richard67 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) an
@wilsonge Sure I am right. I am German, we are always right (except maybe when starting world wars 😄 ).

2019-06-28 21:51 UTC, merged

2019-06-28 21:51 UTC, wilsonge commented
Thanks!