[4.0] New Feature: add a global master language for Multilingual Associations
joomla/joomla-cms pull request #25403
Opened 2019-07-02 11:05 UTC by lavipr

This adds an optional global master language for the multilingual associations. The topic that had its beginnings in the two PR's #17881 and #17802 was tackled from scratch.

This gives each association a "Master-Child" relationship. This means that an associated item set with the master language is set as master and the items in the other languages are set as children.
This makes it possible to add new association statuses to the already existing 'not associated' and 'associated' ones: the 'outdated' and 'up-to-date' status. These new statuses maintain the child elements in relation to their master. 
When associations are created, the children are given up-to-date status. If the master item is changed, the children will be set to outdated (if they were up-to-date until then). A distinction is made between whether the content history is enabled or not. The difference: content history only saves entries in which changes are really made. 
In the Associations List View a new filter for the Association States has been added.

To update an outdated child to up-to-date a new edit view is called, in which it is only possible to save and update the target (i.e. the outdated child). 
Here, too, a distinction is made between whether the content history is activated or not. If content history is activated, a customized Compare View of contenthistory is displayed. The changes of the master are displayed since the moment the child was set to outdated and to the current master.
If it is content history disabled, the normal edit view of the reference/master is displayed. The user has to determine whether there are changes to the master or not. Advantage over before: by the status outdated you at least know that someone has saved the master.

### Summary of Changes
- The Associations List View is the only List View in the backend that has the behavior that no content is displayed the first time this view is called. This is confusing, especially for users who have not yet spent long time with associations. To adapt this list view to the others so that a more uniform behavior is achieved in the backend, the filters for itemtype and language are filled with default values. This means that the two buttons 'delete all associations' and 'delete orphans' must always be displayed accordingly (otherwise they were hidden as soon as a list appears - see #21869). Delete All Associations no longer deletes all associations, but all associations with matching context.
- The colors for the association states 'associated' and 'not associated' have now changed everywhere: gray for 'not associated' and green for associated and 'up-to-date'.  Orange now stands for 'outdated'.
- The option to set the global master language has been added to the languagefilter plugin.
- New columns in #__associations: 
    - master_id' in which the ID of the master item is stored for the child items otherwise 0 for the master item itself and 
    - 'master_date' where either the modified date or the save date of the history table of the master item is stored. The child item gets the same master date as its master item if they are newly associated or when the child item gets updated. 
- Fix bug where newsfeeds and contacts get the same assoc key. 
To prevent associations from receiving the same association key, since id and language can be the same in different contexts, the context is also added as differentiation. 
As the bug appears only after my new queries (key query only), this is fixed here.
- For the masterlanguage see above.

### Testing Instructions
- Install a new instance because there are changes in the sql.
- Install at least two languages. For example, install the multilingual sample data and then the normal sample data (so there is sample data for associated and non-associated items).
- Now no global master language is set yet. The behaviour of the associations should be the same as before. Only the colors have changed. 
No empty list appears in the Associations List View and the delete buttons are now always displayed.
- Go to the Languagefilter plugin and activate a global master language.
Go back to the Associations List View. A new filter appears and the associations are displayed differently, also in other List Views with associations. 
- Change a master item. With versions enabled (default) you need to really make changes and save the master in order to check if children gets 'outdated'. 
Update a child element. 

### Expected result
- Associations List View without a global Master Language:
![image](https://user-images.githubusercontent.com/31204883/60507515-9cd35a80-9cc8-11e9-86f4-b2d55433723e.png)
- Articles List View without a global Master Language:
![image](https://user-images.githubusercontent.com/31204883/60507613-d906bb00-9cc8-11e9-8632-8af9180d449c.png)

- Set a global Master Language in the Languagefilter Plugin:
![SetGlobalMaster](https://user-images.githubusercontent.com/31204883/60506941-474a7e00-9cc7-11e9-9e07-e8bd7758ca06.gif)
- Associations List View with Global Master Language:
![image](https://user-images.githubusercontent.com/31204883/60507255-056e0780-9cc8-11e9-9cf4-730836e4d2b9.png)
- Articles List View with Global Master Language:
![image](https://user-images.githubusercontent.com/31204883/60507319-2cc4d480-9cc8-11e9-9b25-3ba5d8549e4d.png)
- New Update/Edit View for outdated items with versions enabled:
![image](https://user-images.githubusercontent.com/31204883/60507807-487caa80-9cc9-11e9-998a-db5e3d86da0e.png)

### Actual result
- No global Master Language Setting in the Languagefilter Plugin.
- No 'outdated' or 'up-to-date' association states.
- Associations List View:
![FirstEntryAssociations](https://user-images.githubusercontent.com/31204883/60507394-58e05580-9cc8-11e9-9b2f-2a53be154cf3.gif)
- Articles List View:
![image](https://user-images.githubusercontent.com/31204883/60507569-bffe0a00-9cc8-11e9-9cac-ceb4ee3e46d4.png)

### Documentation Changes Required
Yes

2019-07-02 12:30 UTC, brianteeman commented on administrator/components/com_associations/Field/ContentmasterlanguageField.php
> +use Joomla\CMS\Language\LanguageHelper;
These need to be alpha sorted so move LanguageHelper above Text

2019-07-02 12:33 UTC, brianteeman commented on administrator/components/com_associations/Helper/AssociationsHelper.php
> +								When versions are disabled than the modified date is used for the master item.
```suggestion
								When versions are disabled then the modified date is used for the master item.
```

2019-07-02 12:35 UTC, brianteeman commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +	 * Method to get the latest modified date of an master item
```suggestion
	 * Method to get the latest modified date of a master item
```

2019-07-02 12:35 UTC, brianteeman commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +			// If versions are enabled get the save_data of the master item from history table
```suggestion
			// If versions are enabled get the save_date of the master item from history table
```

2019-07-02 12:38 UTC, brianteeman commented on administrator/components/com_associations/Model/AssociationsModel.php
> +		// Set language select box to default site language or if set to the master language as default.
```suggestion
		// Set language select box to default site language or if set to, to the master language as default.
```

2019-07-02 12:38 UTC, brianteeman commented on administrator/components/com_associations/Model/AssociationsModel.php
> +				// Join over associations where id does not exists
```suggestion
				// Join over associations where id does not exist
```

2019-07-02 12:41 UTC, SharkyKZ commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +	public static function addNotAssociatedMasterLink($globalMasterLang, $itemId, $itemType)
HTML output should be overrideable. This either needs to be a HTML service or use layouts. See related issue #14662.

2019-07-02 12:42 UTC, SharkyKZ commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +	public static function setMasterAndChildInfos($itemId, $items, $key, $item, $globalMasterLang, $isMaster, $masterId, $assocMasterDates, $saveHistory)
HTML output should be overrideable.

2019-07-02 12:42 UTC, brianteeman commented on administrator/components/com_associations/forms/filter_associations.xml
> +	>
```suggestion
		>
```

2019-07-02 12:44 UTC, brianteeman commented on administrator/components/com_associations/forms/filter_associations.xml
> +		<option value="" disabled="true">COM_ASSOCIATIONS_FILTER_SELECT_ITEM_TYPE</option>
is there a reason for this to be disabled. We usually dont do that for filters

2019-07-02 12:45 UTC, brianteeman commented on administrator/components/com_associations/forms/filter_associations.xml
> +		<option disabled="true">COM_ASSOCIATIONS_FILTER_SELECT_ASSOCIATION_STATE</option>
is there a reason for this to be disabled. We usually dont do that for filters just `value=''`

2019-07-02 12:46 UTC, brianteeman commented on administrator/components/com_associations/tmpl/association/update.php
> +//HTMLHelper::_('script', 'com_associations/sidebyside.js', ['version' => 'auto', 'relative' => true]);
just delete this if its not used

2019-07-02 12:46 UTC, SharkyKZ commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +		$url = Route::_('index.php?' . http_build_query($options));
Remove `Route::_()` call and add it to the layout instead.

2019-07-02 12:48 UTC, brianteeman commented on administrator/components/com_categories/Model/CategoryModel.php
> +				// If there is an association item with the globalMasterLanguage, then get his id
```suggestion
				// If there is an association item with the globalMasterLanguage, then get its id
```

2019-07-02 12:48 UTC, brianteeman commented on administrator/components/com_categories/Service/HTML/AdministratorService.php
> +				// Check if there is a master item in the association and get his id if so.
```suggestion
				// Check if there is a master item in the association and get its id if so.
```

2019-07-02 12:50 UTC, brianteeman commented on administrator/components/com_contact/Service/HTML/AdministratorService.php
> +				// Check if there is a master item in the association and get his id if so.
```suggestion
				// Check if there is a master item in the association and get its id if so.
```

2019-07-02 12:50 UTC, richard67 commented
@lavipr Looks good at a first look. But new schema update SQL scripts (name e.g. `4.0.0-2019-07-02.sql`) below folder `administrator/components/com_admin/sql/updates` are missing for the database changes in joomla.sql. Will you add them later? Or do you need some help or advise with that?

2019-07-02 12:50 UTC, brianteeman commented on administrator/components/com_content/Service/HTML/AdministratorService.php
> +				// Check if there is a master item in the association and get his id if so
```suggestion
				// Check if there is a master item in the association and get its id if so
```

2019-07-02 12:53 UTC, brianteeman commented on administrator/components/com_contenthistory/tmpl/compare/compareMaster.php
> +<fieldset>
A table should not be wrapped in a fieldset

2019-07-02 12:54 UTC, brianteeman commented on administrator/components/com_menus/Service/HTML/Menus.php
> +				// Check if there is a master item in the association and get his id if so
```suggestion
				// Check if there is a master item in the association and get its id if so
```

2019-07-02 12:54 UTC, brianteeman commented on administrator/components/com_contenthistory/tmpl/compare/compareMaster.php
> +</fieldset>
dont wrap a table in a fieldset

2019-07-02 12:55 UTC, lavipr commented
> @lavipr Looks good at a first look. But new schema update SQL scripts (name e.g. `4.0.0-2019-07-02.sql`) below folder `administrator/components/com_admin/sql/updates` are missing for the database changes in joomla.sql. Will you add them later? Or do you need some help or advise with that?

@richard67 Thank you. Indeed I need help or advice. That would be very helpful. I wasn't aware of that.

2019-07-02 12:55 UTC, brianteeman commented on administrator/components/com_newsfeeds/Service/HTML/AdministratorService.php
> +				// Check if there is a master item in the association and get his id if so.
```suggestion
				// Check if there is a master item in the association and get its id if so.
```

2019-07-02 12:56 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_associations.ini
> +COM_ASSOCIATIONS_UPDATE_ASSOCIATION="Update association"
```suggestion
COM_ASSOCIATIONS_UPDATE_ASSOCIATION="Update Association"
```

2019-07-02 12:57 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_STATE_MIGHT_BE_OUTDATED_DESC="This item might be outdated with the master article."
```suggestion
JGLOBAL_ASSOCIATIONS_STATE_MIGHT_BE_OUTDATED_DESC="This item might be out of date with the master article."
```

2019-07-02 12:57 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_STATE_OUTDATED_DESC="This item is outdated with the master item."
```suggestion
JGLOBAL_ASSOCIATIONS_STATE_OUTDATED_DESC="This item is out of date with the master item."
```

2019-07-02 13:00 UTC, lavipr commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_STATE_OUTDATED_DESC="This item is outdated with the master item."
Thank you very much for your code review! I appreciate that.
Just so I know better, I found both possibilities as translation. Is there a linguistic difference?

2019-07-02 13:00 UTC, brianteeman commented on installation/src/Model/LanguagesModel.php
> +			// If there is an association item with the globalMasterLanguage, get his id.
```suggestion
			// If there is an association item with the globalMasterLanguage, get its id.
```

2019-07-02 13:00 UTC, richard67 commented
@lavipr I can make a PR for the schema updates against your branch, which you then can merge so it goes into this PR. Is that ok for you?

2019-07-02 13:01 UTC, brianteeman commented on libraries/src/MVC/Model/AdminModel.php
> +				// If there is an association item with the globalMasterLanguage, then get his id
```suggestion
				// If there is an association item with the globalMasterLanguage, then get its id
```

2019-07-02 13:03 UTC, brianteeman commented on plugins/system/languagefilter/Field/ContentsitelanguageField.php
> +use Joomla\CMS\Language\Text;
swap the order of lines 17 and 18 to alphasort

2019-07-02 13:04 UTC, lavipr commented on administrator/components/com_associations/forms/filter_associations.xml
> +		<option disabled="true">COM_ASSOCIATIONS_FILTER_SELECT_ASSOCIATION_STATE</option>
My thoughts were that I wanted only display this as information, but that the possibility of choosing nothing should not be possible. But if it's not usually applied that way, I'll rework the filter.

2019-07-02 13:04 UTC, brianteeman commented on plugins/system/languagefilter/languagefilter.xml
> +				>
```suggestion
					>
```

2019-07-02 13:06 UTC, lavipr commented
> @lavipr I can make a PR for the schema updates against your branch, which you then can merge so it goes into this PR. Is that ok for you?

@richard67 That would be great! Thank you.

2019-07-02 13:08 UTC, brianteeman commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_STATE_OUTDATED_DESC="This item is outdated with the master item."
English is hard :(

There is a difference. You can say
- This item is outdated  eg the shirt is very outdated fashion
- This item is out of date eg the milk is sour, it is out of date

But when you add a comparison eg with the master then you can only use the second

2019-07-02 13:08 UTC, brianteeman commented
This looks like a lot of work - thanks

I will try to find some time tomorrow to do a real test

2019-07-02 13:10 UTC, lavipr commented
@brianteeman Thank you for your code review and your test.

2019-07-02 13:14 UTC, lavipr commented on administrator/language/en-GB/en-GB.ini
> +JGLOBAL_ASSOCIATIONS_STATE_OUTDATED_DESC="This item is outdated with the master item."
Thanks for the explanation!

2019-07-02 13:23 UTC, richard67 commented
@lavipr Before I make any schema update: Why did you use data type `text` for the `master_date` column? I would have expected `date` for MySQL and `timestamp without time zone` for postgresql if it really is a date. If you save there the string representation of a date, then it needs to check your code it that string representation will always be of same format, regardless of current language.

2019-07-02 13:29 UTC, richard67 commented
@lavipr In addition to my comment above about format of `master_date` column, I see that you use `string` data type in your PHP functions for that master date value. And in PHP code you build SQL queries with master date comparisons in the where clauses. Such comparisons for smaller or larger (`<`, `>`) and so on work with string representations of dates and time only when format is always so that alphabetical order is always equal to numerical order, like it is e.g. for format `YYYY-MM-DD hh:mm:ss` with `hh`= 24 hour format.

2019-07-02 13:31 UTC, richard67 commented
@lavipr I strongly recommend to use date and time formats for dates and time in PHP and also in SQL and not string formats. Or do you have a really good reason why you did it differently?

2019-07-02 13:33 UTC, lavipr commented
> @lavipr Before I make any schema update: Why did you use data type `text` for the `master_date` column? I would have expected `date` for MySQL and `timestamp without time zone` for postgresql if it really is a date. If you save there the string representation of a date, then it needs to check your code it that string representation will always be of same format, regardless of current language.

@richard67 You are right. I'll change it. Thanks for your explanation.

2019-07-02 13:34 UTC, richard67 commented
@lavipr Ok, I'll wait with the schema updates. Ping me here when ready.

2019-07-02 14:05 UTC, SharkyKZ commented
We currently don't support uppercase letters in layouts (IDK if there's a reason for this). So `administrator/components/com_contenthistory/tmpl/compare/compareMaster.php` needs to be renamed.

2019-07-02 14:19 UTC, infograf768 commented
Eager to test, but atm just a question: is it necessary to define the master/reference language in the language filter plugin, instead of com_associations Options?

2019-07-02 14:23 UTC, bembelimen commented
I really like the idea of a master language and this whole PR is an awesome piece of code. Thanks for that!

But now the "but": I would really like to see this going further. Not one global master language but unlimited local master languages. Every item decides "automatically" their own master language (probably via parameter). Because I think on big news portals different languages could be the master language depending on the article (one original article is French, so French would be master here, other is English etc.).

So tl;tr: Don't stop here, but go deeper on item level for a more flexible approach!

2019-07-02 14:26 UTC, lavipr commented
> Eager to test, but atm just a question: is it necessary to define the master/reference language in the language filter plugin, instead of com_associations Options?

@infograf768 The idea was that because the master language depends on the fact that item_associations is set, this can be also done there.

2019-07-02 14:42 UTC, infograf768 commented
I would prefer as it is anyway impossible to use com_associations if items associations is not set.

2019-07-02 14:46 UTC, infograf768 commented
> Not one global master language but unlimited local master languages

Beware as this is what blocked the gsoc project as it is extremely complex and confusing...

2019-07-02 14:47 UTC, SharkyKZ commented on plugins/sampledata/multilang/multilang.php
> +					. '"user_master_language":"0",'
```suggestion
					. '"use_master_language":"0",'
```

2019-07-02 14:54 UTC, SharkyKZ commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +				if ($tableName === '#__categories')
Since this is using Content Types already, use modified field defined in `#__content_types` table.

2019-07-02 15:01 UTC, SharkyKZ commented on plugins/system/languagefilter/languagefilter.xml
> +						default="0"
```suggestion
						default="0"
						filter="integer"
```

2019-07-02 15:01 UTC, SharkyKZ commented on plugins/sampledata/multilang/multilang.php
> +					. '"use_master_language":"0",'
```suggestion
					. '"use_master_language":0,'
```

2019-07-02 15:01 UTC, SharkyKZ commented on plugins/system/languagefilter/languagefilter.php
> +			$params->global_master_language = ($params->use_master_language === '1')
```suggestion
			$params->global_master_language = ($params->use_master_language === 1)
```

2019-07-02 16:37 UTC, lavipr commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +				if ($tableName === '#__categories')
@SharkyKZ Could you please have a look if it is ok like this? 439c6ad

2019-07-02 16:50 UTC, lavipr commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +		$url = Route::_('index.php?' . http_build_query($options));
@SharkyKZ For a better understanding: So here I should return the $options instead and call this line e.g. in \com_newsfeeds\Service\HTML\AdministratorService.php after calling this function?

2019-07-02 18:08 UTC, SharkyKZ commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +		$url = Route::_('index.php?' . http_build_query($options));
Here return `'index.php?' . http_build_query($options)`. Run the returned URL through `Route::_()` after calling this function like in the mentioned file.

2019-07-02 18:46 UTC, HLeithner requested changes
I really appreciate this PR, I think that could be a great extension to Joomla Multilang system.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +		$query = $db->getQuery(true)
Could you please convert this to prepared statements and proper escaping
```php
$query->select($db->quoteName(['title', 'sef']);
// same for ->from
$query->where($db->quoteName('lang_code') . ' = :lang')
  ->bind(':lang', $globalMasterLang);
```

Something like this.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +				->select($db->quoteName('master_date'))
Could you please convert this to prepared statements
```php
$query->where([
  $db->quoteName('id') . ' = :id',
  $db->quoteName('context') . ' = :context'
  ])
  ->bind(':id', $id, ParameterType::Integer) // you need to import the namespace for this
  ->bind(':context', $context;
```

Something like this.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +			->where($db->quoteName('type_id') . ' = ' . $db->quote($typeId));
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +					->where($db->quoteName('id') . ' = ' . $db->quote($masterId));
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationMasterModel.php
> +			->where($db->quoteName('id') . ' = ' . $db->quote($masterId))
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationMasterModel.php
> +			->set($db->quoteName('master_date') . ' = ' . $db->quote($masterModified))
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationModel.php
> +		$masterQuery = $db->getQuery(true)
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationModel.php
> +			->select($db->quoteName('version_id'))
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationModel.php
> +			->select($db->quoteName('master_date'))
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationModel.php
> +			->select($db->quoteName('version_id'))
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
>  				'LEFT',
please use leftJoin and prepared parameter for $assocContextName

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
>  			->join('LEFT', $db->quoteName('#__associations', 'asso2') . ' ON ' . $db->quoteName('asso2.key') . ' = ' . $db->quoteName('asso.key'));
leftJoin please

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +				$query->where('((' . $db->quoteName('asso.id') . ' IS NULL )'
Convert to prepared statements please and maybe use orWhere, maybe whereIn is also possible

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->where($db->quoteName('extension') . ' = ' . $db->quote($extensionName));
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +				$query->where($db->quoteName('context') . ' = ' . $db->quote($extensionName . '.item'));
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_categories/Service/HTML/AdministratorService.php
> +				->where('c.id IN (' . implode(',', array_values($associations)) . ')');
please rewrite the complete query with proper syntax (quoteName, whereIn, leftJoin, prepared parameters)

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_contact/Service/HTML/AdministratorService.php
> +			$query->join('LEFT', '#__languages as l ON c.language=l.lang_code')
please rewrite the complete query with proper syntax (quoteName, whereIn, leftJoin, prepared parameters)

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_categories/Model/CategoryModel.php
> +					$query->values(
Convert to prepared statements please.

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_content/Service/HTML/AdministratorService.php
>  				->join('LEFT', '#__categories as cat ON cat.id=c.catid')
please rewrite the complete query with proper syntax (quoteName, whereIn, leftJoin, prepared parameters)

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_menus/Model/ItemModel.php
> +					$query->values(
prepared statements please

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_menus/Service/HTML/Menus.php
> +				->where('m.id IN (' . implode(',', array_values($associations)) . ')');
please rewrite the complete query with proper syntax (quoteName, whereIn, leftJoin, prepared parameters)

2019-07-02 18:46 UTC, HLeithner commented on administrator/components/com_newsfeeds/Service/HTML/AdministratorService.php
> +			$query->join('LEFT', '#__languages as l ON c.language=l.lang_code')
please rewrite the complete query with proper syntax (quoteName, whereIn, leftJoin, prepared parameters)

2019-07-02 18:46 UTC, HLeithner commented on installation/src/Model/LanguagesModel.php
> +				$query->values(((int) $id) . ',' . $db->quote($context) . ',' . $db->quote($key) . ',' . $db->quote($masterIdValue) . ',' . $db->quote(''));
please rewrite the complete query with proper syntax (quoteName, prepared parameters)

2019-07-02 18:46 UTC, HLeithner commented on libraries/src/MVC/Model/AdminModel.php
> +						((int) $id) . ',' . $db->quote($this->associationsContext) . ',' . $db->quote($key)
please use prepared parameters

2019-07-02 18:46 UTC, HLeithner commented on plugins/sampledata/multilang/multilang.php
> +				$query->values(((int) $id) . ',' . $db->quote($context) . ',' . $db->quote($key) . ',' . $db->quote('-1') . ',' . $db->quote(''));
please prepared parameters

2019-07-02 18:46 UTC, HLeithner commented on plugins/system/languagefilter/languagefilter.php
> +					->where($db->quoteName('key') . ' = ' . $db->quote($value));
use prepared parameter

2019-07-02 18:46 UTC, HLeithner commented on plugins/system/languagefilter/languagefilter.php
> +					->from('#__associations')
quoteName

2019-07-02 18:46 UTC, HLeithner commented on plugins/system/languagefilter/languagefilter.php
> +					->where($db->quoteName('key') . ' = ' . $db->quote($value));
prepared parameter please

2019-07-02 18:46 UTC, HLeithner commented on plugins/system/languagefilter/languagefilter.php
> +							->where($db->quoteName('id') . ' = ' . $db->quote($masterId));
plz use prepared parameter

2019-07-02 18:46 UTC, HLeithner commented on plugins/system/languagefilter/languagefilter.php
> +					->set($db->quoteName('master_id') . ' = ' . $db->quote($masterId))
Convert to prepared statement plz

2019-07-02 19:07 UTC, lavipr commented
> @lavipr Ok, I'll wait with the schema updates. Ping me here when ready.

Could you please have a look to my database changes: 5c321cb ? Thanks!

2019-07-02 19:10 UTC, richard67 commented
@lavipr Data type in database looks ok now. I will make the PR for the schema updates in a minute or two. But still in PHP you use string data type. How it should be done you can look up in other PHP code dealing with date/timestamp columns, like e.g. columns `published_up` in several db tables.

2019-07-02 19:15 UTC, lavipr commented
> @lavipr Data type in database looks ok now. I will make the PR for the schema updates in a minute or two. But still in PHP you use string data type. How it should be done you can look up in other PHP code dealing with date/timestamp columns, like e.g. columns `published_up` in several db tables.

@richard67 I also added update sqls.

2019-07-02 19:20 UTC, richard67 commented
@lavipr Hmm, just right now I have finished the update sqls, see [https://github.com/lavipr/joomla-cms/pull/6](https://github.com/lavipr/joomla-cms/pull/6)

2019-07-02 19:30 UTC, lavipr commented
> @lavipr Hmm, just right now I have finished the update sqls, see [lavipr#6](https://github.com/lavipr/joomla-cms/pull/6)

Ah I forgot to add the new files to git... So I merged your PR. Thank you very much.

2019-07-02 19:33 UTC, richard67 commented
Welcome. I always try to help when desired. Now you have a lot to do with this prepared statement stuff from Harald, but I am sure you will manage that, too.

2019-07-02 19:37 UTC, alikon commented
thank you for this big enhancement..and if you need any help on prepared statements, don't hesitate to ping me

2019-07-02 19:39 UTC, richard67 commented
Ah, and I forgot the PHP changes for datetime data type. Still a bit work, but on a good way.

2019-07-02 19:40 UTC, lavipr commented
Thank you!

2019-07-02 20:40 UTC, lavipr commented
> thank you for this big enhancement..and if you need any help on prepared statements, don't hesitate to ping me

@alikon In fact, I would need help with the prepared statements. I'm trying to use them, but I always get an error when using ParameterType::Integer: _'Undefined class constant 'Integer'_. I don't understand what the problem is.
I did import `use Joomla\Database\ParameterType;`
And used it like this for example:
`$query = $db->getQuery(true)`
 `->select($db->quoteName('master_date'))`
`->from($db->quoteName('#__associations'))`
`->where($db->quoteName('id') . ' = :id')`
`->where($db->quoteName('context') . ' = :context')`
`->bind(':id', $id, ParameterType::Integer)`
`->bind(':context', $context);`
`$db->setQuery($query);`

2019-07-02 20:43 UTC, richard67 commented
@lavipr You have to use `ParameterType::INTEGER`, i.e. the `INTEGER` in capital letters..
See an example PR for the change to prepared statements here: [https://github.com/joomla/joomla-cms/pull/25386](https://github.com/joomla/joomla-cms/pull/25386).

2019-07-02 20:46 UTC, lavipr commented
> @lavipr You have to use `ParameterType::INTEGER`, i.e. the `INTEGER` in capital letters..
> See an example PR for the change to prepared statements here: #25386.

Oh my bad... I think I've seen enough code today :D Thanks.

2019-07-02 20:47 UTC, richard67 commented
@lavipr No, not your bad, Harald's bad ;-) He gave you the example.

2019-07-03 08:07 UTC, C-Lodder commented on administrator/components/com_associations/forms/filter_associations.xml
> +		<option value="" disabled="true">COM_ASSOCIATIONS_FILTER_SELECT_ITEM_TYPE</option>
Either way, `true` is not a valid value for the `disabled` attribute. Simply use `<option value="" disabled>`

2019-07-03 08:08 UTC, C-Lodder commented on administrator/components/com_associations/forms/filter_associations.xml
> +		<option disabled="true">COM_ASSOCIATIONS_FILTER_SELECT_ASSOCIATION_STATE</option>
`true` is not a valid value for the `disabled` attribute. Simply use:
`<option value="" disabled>`

2019-07-03 08:14 UTC, infograf768 commented
TEST:
Lets take as example Articles > Categories
4 languages installed: en-GB, fr-FR, de-DE, fa-IR
_I will use here the term "Language" but it means "Content Language"_

Site default language is en-GB.
Global Master set to site language i.e. en-GB

Associations are set for this category:

<img width="878" alt="Screen Shot 2019-07-03 at 08 30 19" src="https://user-images.githubusercontent.com/869724/60568335-d8bffb80-9d6c-11e9-9378-592dfc61ceda.png">

The Category (en-gb) has never been modified therefore No Version history.

Now lets load com_associations.

This is what I get when the language filter is set to the site language-> English (en-GB) Master:

<img width="1430" alt="Screen Shot 2019-07-03 at 08 32 46" src="https://user-images.githubusercontent.com/869724/60568479-40764680-9d6d-11e9-8629-30fbf8b41385.png">

Clicking on the lang associations icon -but not yet on the "EN" icon- or on the item itself works as before this patch. 
Editing can be done using the sidebyside for both target and reference and we can switch to any existing language.

**We have an important difference** though with former behavior as "EN" is displayed and clicking on it will obtain the same result as clicking on the original/reference/item (Target is empty until language selected). 
This means the UI has changed and now displays all existing lang associations including the one which is filtered by.
I can live with this as the side by side is working fine.

<img width="1427" alt="Screen Shot 2019-07-03 at 08 47 07" src="https://user-images.githubusercontent.com/869724/60569267-335a5700-9d6f-11e9-946e-503ac7914a3c.png">

-------------------

Now lets switch the language in the filter, for example to French.
Now we only get in the Associations column both the "EN" and "FR".  **German and Persian are no more present.**

<img width="1400" alt="Screen Shot 2019-07-03 at 08 51 50" src="https://user-images.githubusercontent.com/869724/60569501-d7440280-9d6f-11e9-9281-cc1f4329bb32.png">

The behavior is totally different.
1. Clicking on the Title of the item "Catégorie (fr-fr)" displays the usual side by side where the Select Target Language only presents the Global Master choice.

<img width="1422" alt="Screen Shot 2019-07-03 at 09 06 57" src="https://user-images.githubusercontent.com/869724/60570545-183d1680-9d72-11e9-94a8-6d4ac42fa3f0.png">

2. If we click on any of the lang icons (EN or FR),  the side by side is no more presenting the selected item (here "Catégorie (fr-fr)" as reference, but as target and all existing languages are still presented as possible in the Select Target Language.

<img width="1424" alt="Screen Shot 2019-07-03 at 09 13 19" src="https://user-images.githubusercontent.com/869724/60570922-d95b9080-9d72-11e9-9074-463a7bdafbe9.png">

-------------
Now, let's modify the Category (en-gb) item to get a new version. Added some text in the description.

If the modification is done while being in an already displayed side by side, nothing special happens.
If it has been done in the side by side and Reference saved or in the original item in `index.php?option=com_categories&view=categories&extension=com_content` then we get

1. In the Categories Manager

When NOT filtering by language

<img width="1150" alt="Screen Shot 2019-07-03 at 09 25 10" src="https://user-images.githubusercontent.com/869724/60571783-82ef5180-9d74-11e9-9edc-7d4799cd4036.png">

We already see the issue as we get the same result as in com_ associations : only the master and language of the item which is not tagged to the Global Master language are displayed. 

Ths is even more prominent when filtering by a language which is NOT the Global Master one:

<img width="1256" alt="Screen Shot 2019-07-03 at 09 29 36" src="https://user-images.githubusercontent.com/869724/60572078-1c1e6800-9d75-11e9-80b9-d03290541a06.png">

Basically, at looking at the manager we have no idea if the item is already associated to the other languages used by the site. **This should be corrected imho.**

Also the icons behave differently in the sense that the EN (Global here) is displaying the usual sidebyside with the Global while the red icon is opening the new update side by side.

2. In com_associations
Similar behavior depending on the settings of the Language filter field.

------
**BUG**
Modifying the Content Category set to the Global Master language provokes modifications for the articles belonging to this category by creating new version history for the articles.

We get

<img width="1209" alt="Screen Shot 2019-07-03 at 09 54 23" src="https://user-images.githubusercontent.com/869724/60573743-92709980-9d78-11e9-8632-6f04f996e254.png">

If we thereafter click on the red icon for an article not set to Global Master language, i.e.

<img width="1151" alt="Screen Shot 2019-07-03 at 09 56 25" src="https://user-images.githubusercontent.com/869724/60573929-e0859d00-9d78-11e9-81b7-06e361c91e8d.png">

We get, when we are lucky 

<img width="1400" alt="Screen Shot 2019-07-03 at 10 00 26" src="https://user-images.githubusercontent.com/869724/60574333-b97b9b00-9d79-11e9-8731-d3adc380b31a.png">

or sometimes
<img width="1394" alt="Screen Shot 2019-07-03 at 10 06 08" src="https://user-images.githubusercontent.com/869724/60574706-53434800-9d7a-11e9-928a-fdfaec987470.png">
js error:
`TypeError: b.querySelector(...) is null sidebysideupdate.min.js:1:884`
which is `sidebysideupdate.js:52:16` in the uncompressed js.

Looking at the modifed date of these articles: it is empty.

----------------

NOTE: Independant from this PR as it was also the case before: Checkin is broken for com_associations.

Hope this helps.

2019-07-03 09:31 UTC, infograf768 commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +	public static function getMasterModifiedDate($masterId, $tableName, $typeAlias)
PHP Deprecated:  Non-static method Joomla\CMS\Helper\ContentHistoryHelper::getHistory() should not be called statically in /Applications/MAMP/htdocs/newfolder/joomla40/administrator/components/com_associations/Helper/MasterAssociationsHelper.php on line 179

2019-07-03 10:11 UTC, lavipr commented
Thanks @infograf768 for testing! I'll answer you later.

2019-07-03 12:00 UTC, infograf768 commented
There is a possibility that the js error be related to the multiple tests I did on the same item, thus introducing an unwanted cache pb.

2019-07-03 12:01 UTC, infograf768 commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +	public static function getMasterModifiedDate($masterId, $tableName, $typeAlias)
same error with other methods in this file using ContentHistoryHelper

2019-07-03 18:02 UTC, lavipr commented
I would like to try to explain my concept in more detail:
 
By introducing the Master language, a relationship is established between the Master and his children. This also means that there shouldn't be a direct relationship from child to child. 
For the behaviour this will then consequently work:  A Master Element is shown all its associated children. If a child is displayed in the list, only the relationship to his master is displayed, since there is no longer a direct relationship to the other child languages.

The purpose of using a master language is as follows: In a company, for example, articles are usually written in one language. And, by default, "translations" are created from that language. Until now, it was practically irrelevant which order one used. Let's take the three languages English, French, German. So it was possible to associate English->French->German with each other. 
Now the difference with a master language: This should be associated with English->French and English->German. (so of course all three are still linked in the association table, but the individual relationships are determined by the master language (child<->master)). 

For the representation and the opening of the sidebyside view this is done: In the best case, the master is displayed as a reference (which works from the association column if a master is present). It does not work in two situations: There may not be a master item in the associations: This will open the child ( named child because it is not in the master language) as a reference and the user is practically forced to associate it with a master element. And it doesn't work if you click directly on the item in the list (maybe the link should be changed?) and also there he can only see the master (like in the list views).

If you want to know all the languages being associated, you have to filter by the master language. 
I think otherwise the master language has little sense, apart from the out of date or up-to-date information.

I hope I could make my concept a little more understandable.

Apart from that the bug needs of course to be fixed.

2019-07-03 18:36 UTC, brianteeman commented
Thanks for the detailed explanation. All makes sense to mr

2019-07-03 18:39 UTC, richard67 commented
Data types still have to be fixed. Currently this PR uses strings for datetimes in all the PHP code.
I don't want to make pressure, I only want to mention it here again so other reviewers and potential testers take notice of that.

2019-07-04 06:52 UTC, infograf768 commented
@lavipr
Thanks. Yep I had understood the concept. The UI is not obvious and we may want to clarify it in a way or another. Let's first solve the bugs indeed.
Note: I still get a weird behavior with the js. Works once and then breaks again (Firefox).

2019-07-04 07:41 UTC, infograf768 commented
Note: 
Using Version History is essential here. Therefore modifying a Master menu item parameters is not considered as a modification for the associated menu items.

It is a special case: shall we/can we deal with it? 
Maybe by comparing dates (needs adding a Modified date in the #_menus + in #_associations) and showing a message in the side by side? Although we would not know what was modified.
We could also totally ignore it as modifying menu items is reserved to users with specific access to com_menus and they should know the changes to do or not in the associated menu items .

No preconceived idea here.

2019-07-04 08:59 UTC, HLeithner commented
Without wanting to be over-correct, perhaps we should not use the term "master"

https://en.wikipedia.org/wiki/Master/slave_(technology)#Terminology_concerns

2019-07-04 09:15 UTC, infograf768 commented
I suggested in former occasions the term "Reference Language" as field label.
In classes and generally in methods and variables, it could be `GlobalRefLang`

2019-07-04 09:54 UTC, infograf768 commented
Note:
Versioning should be enabled for each component for this to totally work as intended.

I disabled it for articles: the red icon is still displayed. Clicking on it: the changes are not highlighted as it is the sidebyside manager which is used (Not the Update one) [+ the same js error... grrr].
That is fine I guess.

Looks related to the date entered in the `master_date` column in the #_associations table.
Maybe we should use that aspect of the code for Menu Items by also entering a date in the `master_date` column? We would not get details of the changes, but at least a sign something has been modified.

2019-07-04 11:28 UTC, lavipr commented
Thanks for your input! I will start to improve the code step by step with regard to the comments and fix the bugs.

2019-07-08 12:02 UTC, lavipr commented on administrator/components/com_associations/forms/filter_associations.xml
> +		<option value="" disabled="true">COM_ASSOCIATIONS_FILTER_SELECT_ITEM_TYPE</option>
Thanks. I removed disabled from filters, see de8a1b1.

2019-07-08 12:03 UTC, lavipr commented on administrator/components/com_associations/forms/filter_associations.xml
> +		<option disabled="true">COM_ASSOCIATIONS_FILTER_SELECT_ASSOCIATION_STATE</option>
Thanks. I removed this disabled option for association state, see de8a1b1.

2019-07-08 12:06 UTC, lavipr commented on administrator/components/com_associations/Helper/MasterAssociationsHelper.php
> +		$url = Route::_('index.php?' . http_build_query($options));
Thanks. I moved the Route::_() call to the layout.

2019-07-21 22:48 UTC, lavipr commented
I would like to talk about the correct naming of the _'global master language'_ or the respective _'master'_ of a link. In order to avoid more confusion, the old term will be used here for the moment.

I'm not really happy about naming it as a global reference language and then consequently the master as a reference, because the term reference is already in use and for users this always means the left side of the edit view to which they are oriented. 
In my concept the '_master item_' should always appear as a reference, but there are cases where it is not possible. For example, there is no 'master item' for an association yet. Then an existing entry in another language will be the reference and a new target in the _global master language_ will be created.

Therefore I would like to suggest for the global language and the item in the global language either 'global source language' or 'global original language' and 'source item' or 'original (item)'.

I would be pleased about your opinions.

2019-07-21 22:56 UTC, brianteeman commented
Does "default language" and "parent" work?

2019-07-21 23:12 UTC, lavipr commented
Indeed "parent" would work.
I think 'default' might be too unspecific. 
For example, in the list view the info 'Master' is displayed next to the set global master language, so that a user can immediately see which one is set. If there were now for example 'English Default', this could possibly mean anything. 
Maybe an additional info, something like default association language? Where 'default' could also suggest that this is not a global setting?

2019-07-21 23:17 UTC, brianteeman commented
What's the difference between global master language and default association language

2019-08-03 19:21 UTC, Sandra97 commented
Most of the time we have the same content for each language but it also happens that you need a different content per language (which doesn't mean that articles won't be associated - same subject but different content), as you may need to communicate differently to a French audience or to an American one. So it's not because the default/master language (I don't know the difference) is updated that it means the other language needs to be updated too. 
Also, you don't necessarily update first the default language, but another one (it happens to my clients often: main language is set up to US but they update 1st the FR version).     
What will happen in these cases? 
Will this feature be optional?

2019-08-03 19:47 UTC, lavipr commented
@Sandra97, yes this feature is optional.

2019-08-07 13:39 UTC, HLeithner commented
thx lavi for the master rewrite.

2019-08-21 13:42 UTC, lavipr commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
@HLeithner While rewriting and testing prepared statements, it does not seem possible to use prepared statements here.

2019-08-21 13:47 UTC, lavipr commented on administrator/components/com_associations/Model/AssociationsModel.php
> +				$query->where('((' . $db->quoteName('asso.id') . ' IS NULL )'
@HLeithner Here I could not use prepared statement successfully. It probably doesn't work without further ado within "IN". The rewriting to "orWhere" and "whereIn" does not seem possible here, because the enclosing brackets at the beginning of "where" are essential.

2019-08-21 13:49 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
@alikon is it possible that we can't use parepared parameters in having?

2019-08-21 13:56 UTC, lavipr commented on administrator/components/com_associations/Model/DefaultAssocLangModel.php
> +			->bind(':parent_date', $parentModified = Factory::getDate($parentModified)->toSql())
@richard67 Could you please take another look at parent_date? Is this the right solution to store it as date in the database?

2019-08-21 16:56 UTC, richard67 commented on administrator/components/com_associations/Model/DefaultAssocLangModel.php
> +			->bind(':parent_date', $parentModified = Factory::getDate($parentModified)->toSql())
@lavipr Looks correct at a first view. A complete review and a test I can do on weekend, during the week I am currently so fucked up from my daily job that I need to relax in the evenings (German time zone). Is that sufficient? I will for sure test on weekend if still necessary then.

By the way: Will you be at the JoomlaDay in Gießen in September?

2019-08-22 10:21 UTC, lavipr commented on administrator/components/com_associations/Model/DefaultAssocLangModel.php
> +			->bind(':parent_date', $parentModified = Factory::getDate($parentModified)->toSql())
@richard67 I'd appreciate it if you could review and test it this weekend.

I won't be participating in Joomla Day this time.

2019-08-22 16:47 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
I tested this with a similar query and it worked... strange
May test query:
```php

$db = JFactory::getDbo();
$query = $db->getQuery(true);
$count = 1;
$query->select('id')
    ->from('#__content')
    ->group('title')
    ->having('count(*) > :count')
    ->bind(':count', $count);

$db->setQuery($query);

var_dump($db->loadObjectList());
```

can you please post your code or error message?

2019-08-22 16:49 UTC, richard67 commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
@HLeithner Does it also work with PostgreSQL? I can test, but not before weekend.

2019-08-22 17:02 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
Sadly I don't have an installation ready to go... would be great if you can test it.

2019-08-22 17:04 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					. ' OR ( ' . $db->quoteName('asso2.parent_id') . ' = ' . $db->quote('-1') . ')'
You don't need to quote integer constants. Simple add it to the query.
```suggestion
					. ' OR ( ' . $db->quoteName('asso2.parent_id') . ' = -1)'
```

2019-08-22 17:04 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +						AND ' . $db->quoteName('asso.parent_id') . ' = ' . $db->quote('0') . ')'
```suggestion
						AND ' . $db->quoteName('asso.parent_id') . ' = 0)'
```

2019-08-22 17:39 UTC, lavipr commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
For errors in prepared statements, there is only an empty message, but the PrepareStatementFailureException is called.

So my code:
```
$languageQuery = $db->getQuery(true)
					->select('COUNT(*)')
					->from($db->quoteName('#__languages'));
				$db->setQuery($languageQuery);
				$countLanguages = $db->loadResult();
```

				// Get all keys where not all languages are associated.
				$assocQuery = $db->getQuery(true)
					->select($db->quoteName('key'))
					->from($db->quoteName('#__associations'))
					->group($db->quoteName('key'))
					->having('COUNT(*) < :count')
					->bind(':count', $countLanguages, ParameterType::INTEGER);

2019-08-22 18:03 UTC, richard67 commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
Maybe it helps if you cast the result of the first query to integer?
$countLanguages = (int)$db->loadResult();

2019-08-22 18:12 UTC, lavipr commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
I have tried it, but no change.

2019-08-22 18:19 UTC, richard67 commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
@lavipr Ok, was just an idea.

@HLeithner From my point of view, prepared statement is not necessary here. The count returned by the first query will always be an integer, no way to inject anything else, except if someone modifies the 1st query so it does not select COUNT(*) anymore. It would be something else if the parameter came from some user input, but that's not the case.

@alikon Am I right, or am I wrong?

2019-08-22 18:45 UTC, lavipr commented
@infograf768 

> BUG
> Modifying the Content Category set to the Global Master language provokes modifications for the articles belonging to this category but also for articles belonging to any associated category, by creating new version history for the articles.
> 
I can't reproduce the error. I changed a category to the global master language (now the default association language), the children of this association change to 'out-of-date'. The articles belonging to this category do not change their association status.

> js error:
> TypeError: b.querySelector(...) is null sidebysideupdate.min.js:1:884
> which is sidebysideupdate.js:52:16 in the uncompressed js.

The cause of the js error was the opening of a checked out item in the edit view. Meanwhile the check-in problem seems to have improved significantly. I can't reproduce this weird behaviour anymore (described at the end of https://github.com/joomla/joomla-cms/pull/25403#issuecomment-507990097).

I' d be very happy if you could test it again. :)

2019-08-23 07:24 UTC, alikon commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
@HLeithner , @richard67 , @lavipr 
1.  we can use  prepared statement in `HAVING` clause  and it woks even in Postgresql
here is a working snippet  : 
```php
use Joomla\CMS\Factory;
use Joomla\Database\ParameterType;
$db = Factory::getDbo();
$languageQuery = $db->getQuery(true)
	->select('COUNT(*)')
	->from($db->quoteName('#__languages'));
$db->setQuery($languageQuery);
$countLanguages = $db->loadResult();
// Get all keys where not all languages are associated.
$assocQuery = $db->getQuery(true)
	->select($db->quoteName('key'))
	->from($db->quoteName('#__associations'))
	->group($db->quoteName('key'))
	->having('COUNT(*) < :count')
	->bind(':count', $countLanguages, ParameterType::INTEGER);
$db->setQuery($assocQuery);
var_dump($db->loadObjectList());
```
2. and yes could be not necessary here, I agree
3.  i don't understand the logic of the 1st `COUNT(*)` query without at least a where condition  on the `published` field , but that's me

2019-08-23 07:48 UTC, SharkyKZ commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
This could be converted to a single query using subquery.
```
->having('COUNT(*) < (' . $languageQuery . ')');
```
But there's already a method for getting content languages: `Joomla\CMS\Language\LanguageHelper::getContentLanguages()` so why not use it to get language count.

2019-08-23 08:16 UTC, lavipr commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
Thanks! 
I use now the method for getting content languages and count it.

Maybe my problem here with the prepared statements is not the problem at this point, but when I use $assocQuery in the next step, as it is not working.

2019-08-23 08:21 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
thanks Nicola for testing this.
@SharkyKZ using getContentLanguages would make sense because the query is cached

you can use, I think we don't need the installed check and a indexed version for the language count
```
LanguageHelper::getContentLanguages([0,1], false, null);
```

Also in this helper is a AssociationsHelper::getContentLanguages function that is not used anywhere do we still need it?

2019-08-23 08:28 UTC, HLeithner commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					->having('COUNT(*) < ' . $countLanguages);
oh yes the $assocQuery will be converted to a string and the bind variable is lost. you have to bind the variable to the main $query.

2019-08-23 08:29 UTC, lavipr commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					. ' OR ( ' . $db->quoteName('asso.key') . '  IN (' . $assocQuery . ')
Thank you! Now that I've added the getContentLanguages function to count languages, I guess I've removed our previous conversation. I would like to continue it here. 
I think the problem is no longer in the prepared statement in $assocQuery, but probably here in the usage. Because filtering doesn't work.

2019-08-23 08:51 UTC, lavipr commented on administrator/components/com_associations/Model/AssociationsModel.php
> +					. ' OR ( ' . $db->quoteName('asso.key') . '  IN (' . $assocQuery . ')
@HLeithner thanks for the hint to bind the variable to the main query!

2019-08-24 13:27 UTC, richard67 requested changes

2019-08-24 13:27 UTC, richard67 commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> +		return $parentDates;
I get a PHP notice about undefined variable `parentDates` for this line 99 here.

Maybe change to `return $parentDates ?? [];` to return an empty array in case of no associations, or change to `return $parentDates ?? null;` to return null for that case?

No idea what is better. Maybe you know.

2019-08-24 13:33 UTC, SharkyKZ commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> +		return $parentDates;
`$parentDates` should be declared before running the loop. BUT please do not run database queries in a loop unless really necessary.

2019-08-24 14:01 UTC, lavipr commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> +		return $parentDates;
Thanks!

2019-08-24 16:06 UTC, richard67 commented
@lavipr Now when I proceed according to your testing instructions, i.e. new install, then install several languages, then install multilingual sample data and then install blog sample data, the installation of blog sample data stops after step 2 (menus), and I get many many PHP notices in my PHP error log, which are sequences of following 4 notices:

> PHP Notice:  Undefined property: Joomla\\CMS\\Table\\Module::$element in /test-1/plugins/system/languagefilter/languagefilter.php on line 987
> PHP Notice:  Undefined property: Joomla\\CMS\\Table\\Module::$enabled in /test-1/plugins/system/languagefilter/languagefilter.php on line 988
> PHP Notice:  Undefined property: stdClass::$item_associations in /test-1/plugins/system/languagefilter/languagefilter.php on line 989
> PHP Notice:  Undefined property: Joomla\\CMS\\Table\\Module::$element in /test-1/plugins/system/languagefilter/languagefilter.php on line 1031
> 

On a clean 4.0-dev without your PR this does not happen.

2019-08-24 16:08 UTC, richard67 commented
@SharkyKZ Could you advise regarding my previous comment about PHP notices? I will check, too, but you are better in PHP than I am.

2019-08-24 16:19 UTC, SharkyKZ commented
@richard67 Move context check before using `$table` here https://github.com/joomla/joomla-cms/pull/25403/files#diff-9a4ee24a09bcef172864692ed05135caR991

2019-08-24 16:20 UTC, richard67 commented
@SharkyKZ Before where? Your link shows the complete diff for all changed files, no certain line highlighted.

2019-08-24 16:22 UTC, richard67 commented
@SharkyKZ E.g. like that?

> 		// Get the parameters which are to be saved.
> 		$tableElement    = $table->element;
> 
> 		if ($context != 'com_plugins.plugin' && $tableElement != 'languagefilter')
> 		{
> 			return true;
> 		}
> 
> 		$params          = json_decode($table->params);
> 		$pluginStatus    = $table->enabled;
> 		$itemAssocStatus = $params->item_associations ?? false;
>

2019-08-24 16:25 UTC, richard67 commented
@SharkyKZ or maybe even like that?

> 		if ($context !== 'com_plugins.plugin')
> 		{
> 			return true;
> 		}
> 
> 		// Get the parameters which are to be saved.
> 		$tableElement = $table->element;
> 
> 		if ($tableElement !== 'languagefilter')
> 		{
> 			return true;
> 		}
> 
> 		$params          = json_decode($table->params);
> 		$pluginStatus    = $table->enabled;
> 		$itemAssocStatus = $params->item_associations ?? false;
>

2019-08-24 16:29 UTC, richard67 requested changes

2019-08-24 16:29 UTC, richard67 commented on plugins/system/languagefilter/languagefilter.php
> +		$itemAssocStatus = $params->item_associations;
```suggestion
		$itemAssocStatus = $params->item_associations ?? false;
```

Fix PHP Notice: Undefined property: stdClass::$item_associations in /plugins/system/languagefilter/languagefilter.php on line 989

2019-08-24 16:32 UTC, richard67 commented on plugins/system/languagefilter/languagefilter.php
> +		$itemAssocStatus = $params->item_associations;
@lavipr Ignore this suggestion, it should be made different, like @SharkyKZ suggests.

2019-08-24 16:32 UTC, richard67 commented on plugins/system/languagefilter/languagefilter.php
> +		$itemAssocStatus = $params->item_associations;
ah too late. well it does not do harm.

2019-08-24 16:33 UTC, lavipr commented on plugins/system/languagefilter/languagefilter.php
> +		$itemAssocStatus = $params->item_associations;
Thank you for testing and helping :)

2019-08-24 16:34 UTC, richard67 commented
@lavipr Do you already know how to fix the other PHP notices? If not: Shall I continue to help, or do you want to find out alone?

2019-08-24 16:41 UTC, infograf768 commented
> I' d be very happy if you could test it again. :)

@lavipr 
I will take time to test thoroughly again during this next week.

2019-08-24 16:52 UTC, richard67 commented
@lavipr See [https://github.com/lavipr/joomla-cms/pull/7](https://github.com/lavipr/joomla-cms/pull/7) for fix of remaining notices which I've mentioned above.

2019-08-24 17:38 UTC, richard67 commented
@lavipr Now I get 2 times following 2 PHP notices when initially setting `
Set a Default Association Language?` to `Yes` in the language filter plugin and saving the plugin:

PHP Notice:  Only variables should be passed by reference in /plugins/system/languagefilter/languagefilter.php on line 1202
PHP Notice:  Only variables should be passed by reference in /plugins/system/languagefilter/languagefilter.php on line 1238

2019-08-24 17:50 UTC, lavipr commented
> @lavipr Now I get 2 times following 2 PHP notices when initially setting ` Set a Default Association Language?` to `Yes` in the language filter plugin and saving the plugin:
> 
> PHP Notice: Only variables should be passed by reference in /plugins/system/languagefilter/languagefilter.php on line 1202
> PHP Notice: Only variables should be passed by reference in /plugins/system/languagefilter/languagefilter.php on line 1238

thanks. I will fix that.

2019-08-24 17:51 UTC, richard67 commented
@lavipr Oh, I've already made a PR.

2019-08-24 17:57 UTC, lavipr commented
> @lavipr Oh, I've already made a PR.

thank you!

2019-08-24 18:35 UTC, richard67 commented
@lavipr Now after having enabled the Default Assiciation Language in the plugin, I've modified an article in the master language, then went to the new side by side edit view and clicked the "Update Target and Close" button. The I got:

![Unbenannt](https://user-images.githubusercontent.com/7413183/63641430-76b9ad80-c6ae-11e9-8354-3cee63e9739c.png)

PHP error log shows nothing, so no idea where is the mistake.

Do you think you can find out yourself? If not, we could ping SharkyKZ, am sure he will find it.

2019-08-24 18:48 UTC, lavipr commented
@richard67 hm now I can't reproduce your error. Which browser are you using?

2019-08-24 18:50 UTC, richard67 commented
@lavipr Firefox 68.0.2 (64-Bit).

2019-08-24 18:53 UTC, lavipr commented
Weird. Can't reproduce the error here either.

But I notice the problem with the check-in again more frequently...

2019-08-24 18:53 UTC, richard67 commented
I click the icon marked with red frame in the following screnshot in the multilingual associations list view for the master article, then I get a js error `TypeError: b.querySelector(...) is null` in file `sidebysideupdate.min.js`:

![Unbenannt](https://user-images.githubusercontent.com/7413183/63641600-34de3680-c6b1-11e9-824f-5c2e56763ebf.png)

Will switch on debug so the unminified js is used, then I can tell more.

2019-08-24 18:54 UTC, richard67 commented
When after that I save the target as described before, then I get that controller name thing.

2019-08-24 18:56 UTC, richard67 commented
sidebysideupdate.js:52:16:
`target.querySelector('#jform_language').setAttribute('disabled', '');`
It seems the query selector does not find what it looks for.

2019-08-24 18:57 UTC, lavipr commented
> I click the icon marked with red frame in the following screnshot in the multilingual associations list view for the master article, then I get a js error `TypeError: b.querySelector(...) is null` in file `sidebysideupdate.min.js`:
> 
> ![Unbenannt](https://user-images.githubusercontent.com/7413183/63641600-34de3680-c6b1-11e9-824f-5c2e56763ebf.png)
> 
> Will switch on debug so the unminified js is used, then I can tell more.

Ok, yes that is the problem when the target item is checked out.

2019-08-24 18:57 UTC, richard67 commented
Ah, so you can reproduce it?

But I am not sure if that js error is then later the reason for the controller name thing when saving the target.

2019-08-24 19:03 UTC, lavipr commented
No, I haven't. Only once the unloaded element. But after saving the thing with the controller name didn't show up.  I'm trying to get the problem again that the target can't open the checked out item. But it doesn't show up as often as it used to.

2019-08-24 19:12 UTC, richard67 commented
@lavipr Are you testing on Windows or on Linux? I have my Joomla installation on Linux. Maybe the controller name issue comes from some inconsistency in upper or lower case of some source file name and the corresponding class name, and maybe on Windows where file names are case-insensitive that problem does not happen?

2019-08-24 19:13 UTC, lavipr commented
> @lavipr Are you testing on Windows or on Linux? I have my Joomla installation on Linux. Maybe the controller name issue comes from some inconsistency in upper or lower case of some source file name and the corresponding class name, and maybe on Windows where file names are case-insensitive that problem does not happen?

Indeed, I'm testing on Windows....

2019-08-24 19:14 UTC, richard67 commented
@Sharky Any idea regarding [https://github.com/joomla/joomla-cms/pull/25403#issuecomment-524571900](https://github.com/joomla/joomla-cms/pull/25403#issuecomment-524571900) and [https://github.com/joomla/joomla-cms/pull/25403#issuecomment-524574140](https://github.com/joomla/joomla-cms/pull/25403#issuecomment-524574140)?

2019-08-24 19:28 UTC, SharkyKZ commented
@richard67 Yes, that's the issue. Namespaced classes are case sensitive on case sensitive filesystems.

2019-08-24 19:49 UTC, richard67 commented
@SharkyKZ I don't find the mistake.

2019-08-24 20:13 UTC, SharkyKZ commented
Controller name here needs to have correct casing.

https://github.com/joomla/joomla-cms/pull/25403/files#diff-c5890c27f645fcb19937caa120a99a4dR248
https://github.com/joomla/joomla-cms/pull/25403/files#diff-005714eb814c240817bbd105353cf0acR19

2019-08-24 20:14 UTC, richard67 commented
Ahh, I see. @lavipr Can you correct that? 

> Controller name here needs to have correct casing.
> 
> https://github.com/joomla/joomla-cms/pull/25403/files#diff-c5890c27f645fcb19937caa120a99a4dR248
> https://github.com/joomla/joomla-cms/pull/25403/files#diff-005714eb814c240817bbd105353cf0acR19

2019-08-24 20:15 UTC, richard67 commented
@SharkyKZ Thanks a lot.

2019-08-24 20:58 UTC, lavipr commented
@SharkyKZ and @richard67 thanks!

2019-08-24 21:10 UTC, richard67 commented
@lavipr Now the controller name issue is solved. But it seems we have other issues still. I will continue to test tomorrow. Have a good night.

2019-08-24 21:26 UTC, richard67 commented
@lavipr It seems you also have to align case-sensitive names of models, e.g. here:

[https://github.com/joomla/joomla-cms/pull/25403/files#diff-842fb355510d470fa074b046ef1e190fR37](https://github.com/joomla/joomla-cms/pull/25403/files#diff-842fb355510d470fa074b046ef1e190fR37).

For this example I get this error:

![Unbenannt-2](https://user-images.githubusercontent.com/7413183/63642871-804f0f80-c6c6-11e9-8856-5a54e7e3d4ee.png)

There might be other places where names of models has to be aligned with the file names.

Could you check and correct?

2019-08-24 21:55 UTC, richard67 commented
@lavipr Now correct, but then appears new PHP notice. Fixed in [https://github.com/lavipr/joomla-cms/pull/9](https://github.com/lavipr/joomla-cms/pull/9).

2019-08-25 18:37 UTC, richard67 commented
@lavipr Now everything works regarding starting conditions. But as soon as I've edited an article in master language (EN) and then click to ther icon e.g. for French I get following:

![snap-1](https://user-images.githubusercontent.com/7413183/63654209-b39da700-c777-11e9-909d-8a9d7f803a02.png)

After I click close (without save), the english article is checked out.

There is no PHP error or warning or notice, only the JS error that the selector has not found any item mentioned in previous discussions.

2019-08-25 18:45 UTC, lavipr commented
Thanks for testing @richard67 . As I said, there is a problem with check-in and check-out. If you change the language before editing, you will see for this target that it is checked out. I need to figure out how it works with check-in/check-out, as that causes the problem.

2020-01-10 01:34 UTC, Quy commented
Shall this be closed?

2020-01-10 08:45 UTC, HLeithner commented
> Shall this be closed?

I would like to see this finished and in Joomla, hopefully @lavipr finish this PR

2020-08-01 17:48 UTC, roland-d commented
This can be closed and picked up in another PR if someone is interested as topic starter is no longer available.

2021-03-15 10:23 UTC, rdeutz commented
I am moving this to 4.1, we are in beta and this is a new feature and far from ready to merge.

2021-08-20 23:28 UTC, PhilETaylor commented on administrator/components/com_associations/Controller/DefaultAssocLangController.php
> + * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-20 23:28 UTC, PhilETaylor commented on administrator/components/com_associations/Controller/DefaultAssocLangController.php
> + * @since  4.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:28 UTC, PhilETaylor commented on administrator/components/com_associations/Controller/DefaultAssocLangController.php
> +	 * @since  4.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:28 UTC, PhilETaylor commented on administrator/components/com_associations/Field/ContentdefaultassoclangField.php
> + * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-20 23:29 UTC, PhilETaylor commented on administrator/components/com_associations/Field/ContentdefaultassoclangField.php
> + * @since  4.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:29 UTC, PhilETaylor commented on administrator/components/com_associations/Field/ContentdefaultassoclangField.php
> +	 * @since  4.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:29 UTC, PhilETaylor commented on administrator/components/com_associations/Field/ContentdefaultassoclangField.php
> +	 * @since   4.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-20 23:30 UTC, PhilETaylor commented on administrator/components/com_associations/Helper/AssociationsHelper.php
> +								*/
https://developer.joomla.org/coding-standards/inline-code-comments.html
```suggestion
								/**
								 * When versions are disabled then the modified date is used for the parent.
								 * That means that when no changes were made and the parent has been saved the modified date has been changed.
								 * So the out-of-date state means in that case there might have been made changes and it is necessary to check manually and update the target.
								 */
```

2021-08-20 23:30 UTC, PhilETaylor commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> + * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-20 23:30 UTC, PhilETaylor commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> + * @since  4.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:31 UTC, PhilETaylor commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> +	 * @return  string  the link for the not associated parent
```suggestion
	 * @param   string   $itemType          The item type
	 *
	 * @since __DEPLOY_VERSION__
	 *
	 * @return  string  the link for the not associated parent
```

2021-08-20 23:31 UTC, PhilETaylor commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> +	 */
```suggestion
	 *
	 * @since __DEPLOY_VERSION__
	 *
	 * @return  array  association with parent dates
	 */
```

2021-08-20 23:31 UTC, PhilETaylor commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> +	 */
```suggestion
	 *
	 * @since __DEPLOY_VERSION__
	 *
	 * @return  array    parent id and parent dates for an associated item
	 */
```

2021-08-20 23:32 UTC, PhilETaylor commented on administrator/components/com_associations/Helper/DefaultAssocLangHelper.php
> +				// Set always the last modified date
```suggestion
				// Always set the last modified date.
```

2021-08-20 23:32 UTC, PhilETaylor commented on administrator/components/com_associations/Model/DefaultAssocLangModel.php
> + * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-20 23:32 UTC, PhilETaylor commented on administrator/components/com_associations/Model/DefaultAssocLangModel.php
> + * @since  4.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:32 UTC, PhilETaylor commented on administrator/components/com_associations/Model/DefaultAssocLangModel.php
> +	 * @since  4.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:33 UTC, PhilETaylor commented on administrator/components/com_associations/View/Association/HtmlView.php
> +			// Get version ids of the parent, when versions are enabled.
https://developer.joomla.org/coding-standards/inline-code-comments.html
```suggestion
			/** 
			 * The update layout can only be set when a default association language is used.
			 * Get version ids of the parent, when versions are enabled.
			 */
```

2021-08-20 23:33 UTC, PhilETaylor commented on administrator/components/com_associations/tmpl/association/update.php
> + * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-20 23:34 UTC, PhilETaylor commented on administrator/components/com_associations/tmpl/association/update.php
> +
```suggestion
 * 
 * @since __DEPLOY_VERSION__
 */

```

2021-08-20 23:34 UTC, PhilETaylor commented on administrator/components/com_contenthistory/tmpl/compare/compareassocparent.php
> + * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-20 23:35 UTC, PhilETaylor commented on plugins/system/languagefilter/Field/ContentsitelanguageField.php
> + * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-08-20 23:35 UTC, PhilETaylor commented on plugins/system/languagefilter/Field/ContentsitelanguageField.php
> + * @since  4.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:35 UTC, PhilETaylor commented on plugins/system/languagefilter/Field/ContentsitelanguageField.php
> +	 * @since  4.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-20 23:35 UTC, PhilETaylor commented on plugins/system/languagefilter/Field/ContentsitelanguageField.php
> +	 * @since   4.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-20 23:36 UTC, PhilETaylor commented on plugins/system/languagefilter/languagefilter.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-20 23:36 UTC, PhilETaylor commented on plugins/system/languagefilter/languagefilter.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-20 23:36 UTC, PhilETaylor commented on plugins/system/languagefilter/languagefilter.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2022-04-15 15:05 UTC, laoneo commented
Sorry that it took so long to respond. This has a big potential it would be a nice addition for Joomla. Unfortunately it never came out of the draft state and has currently a lot of conflicts, so I'm going to close this. If you are willing to drive it further, please fix the conflicts and rebase it to the 4.2-dev branch so we can help you get it into a testable state. Thanks for your help making Joomla better.

2022-04-15 21:05 UTC, bembelimen commented
As mentioned, it's a feature which is useful and if possible should make it into the core. So to not lose it between thousands of closed PRs, it should stay as a draft for a future rework.

2022-06-27 13:09 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2023-09-30 22:52 UTC, HLeithner commented
This pull request has been automatically rebased to 5.1-dev.

2023-10-02 23:49 UTC, joomleb commented
Hi guys, 
working on this would be good to pay attention at #19807

2024-08-24 10:42 UTC, coolcat-creations commented
Is this still in development?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25403">issues.joomla.org/tracker/joomla-cms/25403</a>.</sub>

2024-08-24 10:46 UTC, richard67 commented
> Is this still in development?
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/25403](https://issues.joomla.org/tracker/joomla-cms/25403).

@coolcat-creations I think currently not. And it has a lot of conflicting files as you can see on GitHub at the bottom of the PR, so I think it cannot even tested.

2024-08-24 11:43 UTC, coolcat-creations commented
Is there a place we could move abandoned PRs to? Instead of closing them, looking for new parents? :-)

2024-08-24 11:45 UTC, richard67 commented
> Is there a place we could move abandoned PRs to? Instead of closing them, looking for new parents? :-)

@coolcat-creations We have the "Ready to take over" label for this purpose, which is already set for this PR.

2024-08-24 11:46 UTC, coolcat-creations commented
Thank you, did not notice this

2025-08-31 12:01 UTC, HLeithner commented
This pull request has been automatically rebased to 6.1-dev.

2026-03-17 09:33 UTC, HLeithner commented
This pull request has been automatically rebased to 6.2-dev.

2026-08-22 15:13 UTC, bembelimen commented
Closing in favour of: https://github.com/joomla/joomla-cms/pull/48287

2026-08-22 15:13 UTC, closed without merging