[plg_sampledata_multilang] Convert to prepared statement
joomla/joomla-cms pull request #25433
Opened 2019-07-04 22:43 UTC by HLeithner

# Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Use the plugin in all ways you can think of.

Install multilang sampledata

### Expected result
Nothing changed.

2019-07-04 23:46 UTC, Quy commented on plugins/sampledata/multilang/multilang.php
> +			->bind(':pluginname',$pluginName);
```suggestion
			->bind(':pluginname', $pluginName);
```

2019-07-05 00:04 UTC, Quy commented on plugins/sampledata/multilang/multilang.php
> +			->columns([$db->quoteName('moduleid'), $db->quoteName('menuid')])
```suggestion
			->columns($db->quoteName(['moduleid', 'menuid']))
```

2019-07-05 15:12 UTC, brianteeman commented
again - looks like two unrelated files here

2019-07-07 15:34 UTC, Quy commented
1st attempt:
> There is an error in a sample data plugin. Response is invalid.

2nd attempt:
> Step 4: Failed creating the Main menu (en-GB).

Nothing in PHP error log.

2019-07-07 15:56 UTC, HLeithner commented
This requires https://github.com/joomla-framework/database/pull/162 too... maybe this is the problem.

2019-07-08 11:36 UTC, HLeithner commented
@Quy can you try it again with the database Pr applied because I can't find a reason why it shouldn't work. Did it work without the PR?.

2019-07-08 14:11 UTC, Quy commented
Works without the PR.

How to apply the database PR?

Here is step 4 which corresponds with the code that uses `bindArray`.
> Step 4: Specific Main Menus have been created as well as associated 'List All Categories' menu items!

2019-07-08 14:21 UTC, HLeithner commented
Apply this file https://github.com/joomla-framework/database/pull/162.diff to the libaries/vendor folder should do it

2019-07-09 08:47 UTC, infograf768 commented
@HLeithner
Using https://github.com/joomla-framework/database/pull/162.diff solves issues here (tested with mysqli)

2019-07-09 09:04 UTC, infograf768 commented
@Quy
I modified the .diff to be correctly applied locally.

[database_patch.txt](https://github.com/joomla/joomla-cms/files/3372137/database_patch.txt)

2019-07-19 06:04 UTC, SharkyKZ commented on plugins/sampledata/multilang/multilang.php
> +					$db->quoteName('position') . ' = ' . $db->quote('sidebar-right')
```suggestion
					$db->quoteName('position') . ' = ' . $db->quote('sidebar-right'),
```

2019-07-19 06:05 UTC, SharkyKZ commented on plugins/sampledata/multilang/multilang.php
> +						$key
```suggestion
						$key,
```

2019-07-19 06:06 UTC, SharkyKZ commented on plugins/sampledata/multilang/multilang.php
> +					$db->quoteName('client_id') . ' = :clientid'
```suggestion
					$db->quoteName('client_id') . ' = :clientid',
```

2019-07-19 12:45 UTC, Quy commented on plugins/sampledata/multilang/multilang.php
> +			->bind(':clientid', $client_id);
```suggestion
			->bind(':clientid', $client_id, ParameterType::INTEGER);
```

2019-08-21 14:45 UTC, SharkyKZ commented
I have tested this item :white_check_mark: successfully on 0b6957412d7170f631ebf83bf34bc8c3a507014a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25433">issues.joomla.org/tracker/joomla-cms/25433</a>.</sub>

2019-08-24 03:05 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 0b6957412d7170f631ebf83bf34bc8c3a507014a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25433">issues.joomla.org/tracker/joomla-cms/25433</a>.</sub>

2019-08-24 03:06 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25433">issues.joomla.org/tracker/joomla-cms/25433</a>.</sub>

2019-08-24 12:48 UTC, zero-24 commented
```
FILE: /********/src/plugins/sampledata/multilang/multilang.php
38 | ----------------------------------------------------------------------
39 | FOUND 3 ERRORS AFFECTING 2 LINES
40 | ----------------------------------------------------------------------
41 | 926 \| ERROR \| [x] Multi-line function call not indented correctly;
42 | \| \| expected 20 spaces but found 16. Note: the
43 | \| \| autofixer will convert spaces to tabs
44 | \| \| (PEAR.Functions.FunctionCallSignature.Indent)
45 | 926 \| ERROR \| [x] Multi-line function call not indented correctly;
46 | \| \| expected 20 spaces but found 16. Note: the
47 | \| \| autofixer will convert spaces to tabs
48 | \| \| (PEAR.Functions.FunctionCallSignature.Indent)
49 | 927 \| ERROR \| [x] Closing parenthesis of a multi-line function call
50 | \| \| must be on a line by itself
51 | \| \| (PEAR.Functions.FunctionCallSignature.CloseBracketLine)
52 | ----------------------------------------------------------------------
53 | PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
54 | ----------------------------------------------------------------------
55


```

2019-08-27 07:13 UTC, alikon requested changes

2019-08-27 07:13 UTC, alikon commented on plugins/sampledata/multilang/multilang.php
>  			->values($moduleId . ', 0');
shouldn't `$moduleId` be bounded as well ?

2019-08-27 07:17 UTC, HLeithner commented on plugins/sampledata/multilang/multilang.php
>  			->values($moduleId . ', 0');
true, thx

2019-08-27 11:38 UTC, HLeithner commented
We need a new test here please.

2019-08-27 13:00 UTC, Quy commented
I have tested this item :white_check_mark: successfully on f1c7ccd3656d98015d6bd9e548196aff3f34328f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25433">issues.joomla.org/tracker/joomla-cms/25433</a>.</sub>

2019-08-27 15:23 UTC, merged