[4.0] Correcting massmail js
joomla/joomla-cms pull request #25517
Opened 2019-07-11 10:00 UTC by infograf768

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/25509

### Summary of Changes
Corrected deprecated function and implemented joomla-alert

### Testing Instructions
Try to send a mail via massmail
1. Without subject
2. Without text

### After patch
Correct alerts.
No console error.

2019-07-11 10:09 UTC, C-Lodder requested changes

2019-07-11 10:09 UTC, C-Lodder commented on build/media_source/com_users/js/admin-users-mail.es6.js
> +        html.innerHTML = Joomla.JText._('COM_USERS_MAIL_PLEASE_FILL_IN_THE_SUBJECT');
Please replace `html.innerHTML` with `html.innerText`

2019-07-11 10:09 UTC, C-Lodder commented on build/media_source/com_users/js/admin-users-mail.es6.js
> +        html.innerHTML = Joomla.JText._('COM_USERS_MAIL_PLEASE_SELECT_A_GROUP');
and here

2019-07-11 10:09 UTC, C-Lodder commented on build/media_source/com_users/js/admin-users-mail.es6.js
> +        html.innerHTML = Joomla.JText._('COM_USERS_MAIL_PLEASE_FILL_IN_THE_MESSAGE');
and here

2019-07-11 10:19 UTC, infograf768 commented
@C-Lodder
done

2019-07-11 22:09 UTC, wilsonge commented on build/media_source/com_users/js/admin-users-mail.es6.js
> +      } else if (form.jform_group.value < 0) {
Shouldn't this be less than or equal to 0?

2019-07-12 08:14 UTC, infograf768 commented on build/media_source/com_users/js/admin-users-mail.es6.js
> +      } else if (form.jform_group.value < 0) {
If it is equal to zero, we should not have any alert as 0 means All User Groups
```
		<field 
			name="group" 
			type="usergrouplist"
			label="COM_USERS_MAIL_FIELD_GROUP_LABEL"
			default="0"
			size="1"
			>
			<option value="0">COM_USERS_MAIL_FIELD_VALUE_ALL_USERS_GROUPS</option>
		</field>
```
btw, I wonder why we even have this alert at all as it looks impossible to get a negative value.
I see it is already present in 3.0, 2.5 and 1.6 although not in a separate js
```
$script .= "\t\t".'} else if (getSelectedValue(\'adminForm\',\'jform[group]\') < 0){'."\n";
$script .= "\t\t\t".'alert("'.JText::_('COM_USERS_MAIL_PLEASE_SELECT_A_GROUP', true).'");'."\n";
```

2019-07-12 08:30 UTC, infograf768 commented
Drone failure looks unrelated to this PR.

2019-07-12 13:12 UTC, merged

2019-07-12 13:12 UTC, wilsonge commented
Thanks