[4.0] Convert plugin system privacyconsent to prepared statements
joomla/joomla-cms pull request #25540
Opened 2019-07-12 21:35 UTC by HLeithner

# Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Use the plugin in all ways you can think of.

Create a privacy consent form and test if it works.

### Expected result
Nothing changed.

2019-07-13 05:04 UTC, Quy commented on plugins/system/privacyconsent/privacyconsent.php
> +			->where($query->dateAdd(':now', $period, 'DAY') . ' > ' . $db->quoteName('created'))
Bind `$period` like here? https://github.com/joomla/joomla-cms/pull/25503/files#diff-bbf838ec8885d4ea43274f7b94e17808R302

2019-07-13 05:04 UTC, Quy commented on plugins/system/privacyconsent/privacyconsent.php
> +			->where($query->dateAdd(':now', $period, 'DAY') . ' > ' . $db->quoteName('created'))
Bind `$period` like here? https://github.com/joomla/joomla-cms/pull/25503/files#diff-bbf838ec8885d4ea43274f7b94e17808R302

2019-07-13 21:26 UTC, Quy commented on plugins/system/privacyconsent/privacyconsent.php
> +			&&in_array($task, ['registration.register', 'profile.save'])
```suggestion
			&& in_array($task, ['registration.register', 'profile.save'])
```

2019-08-03 00:46 UTC, Quy commented on plugins/system/privacyconsent/privacyconsent.php
> +				->bind(':userid', $userId);
```suggestion
				->bind(':userid', $userId, ParameterType::INTEGER);
```

2019-09-18 07:01 UTC, SharkyKZ commented on plugins/system/privacyconsent/privacyconsent.php
> +			->bind([':now', ':period'], [$now, $period], [ParameterType::STRING, ParameterType::INTEGER]);
Use separate `bind()` calls or assign `[$now, $period]` to a variable.

And this is failing on PostgreSQL:

    SQLSTATE[HY093]: Invalid parameter number: :period

2019-10-19 15:36 UTC, HLeithner commented on plugins/system/privacyconsent/privacyconsent.php
> +			->bind([':now', ':period'], [$now, $period], [ParameterType::STRING, ParameterType::INTEGER]);
Fixed thanks

2019-10-20 12:09 UTC, waader commented
I have tested this item :red_circle: unsuccessfully on df9ea6f3de6cf9c1f2508ff221abf876c57e44b4<br /><br />I logged in on frontend an when submitting the profil page with the privacy consent I get the error: 0 Class 'ArrayHelper' not found

Tested with postgresql.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25540">issues.joomla.org/tracker/joomla-cms/25540</a>.</sub>

2019-11-01 10:58 UTC, richard67 requested changes

2019-11-01 10:58 UTC, richard67 commented on plugins/system/privacyconsent/privacyconsent.php
> -use Joomla\Utilities\ArrayHelper;
This line "use Joomla\Utilities\ArrayHelper;" should not be removed because the array helper is still used when this PR is applied. It explains waader's bad test.

2019-11-01 10:59 UTC, richard67 commented on plugins/system/privacyconsent/privacyconsent.php
> -use Joomla\Utilities\ArrayHelper;
E.g. in routine "onUserBeforeSave": "$userId = ArrayHelper::getValue($user, 'id', 0, 'int');".

2019-11-03 13:25 UTC, HLeithner commented on plugins/system/privacyconsent/privacyconsent.php
> -use Joomla\Utilities\ArrayHelper;
ArrayHelper added and Table removed because not used in this file.

2019-11-03 13:29 UTC, richard67 commented
@waader Good find. Error has been corrected here meanwhile. Could you test again? Thanks in advance.

2019-11-03 13:57 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 72a763b7218684907e8993ae03f983fbfded1e5b<br /><br />Hint for other testers: Untranslated language strings are not related to or subject of this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25540">issues.joomla.org/tracker/joomla-cms/25540</a>.</sub>

2019-11-03 17:35 UTC, waader commented
I have tested this item :white_check_mark: successfully on 72a763b7218684907e8993ae03f983fbfded1e5b<br /><br />The error has gone!

I noticed that the request for information deletion as well as export is send twice to the user. This has probably nothing to do with the work done here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25540">issues.joomla.org/tracker/joomla-cms/25540</a>.</sub>

2019-11-03 17:49 UTC, richard67 commented
@waader I don't think it is related to this PR.

2019-11-03 17:50 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25540">issues.joomla.org/tracker/joomla-cms/25540</a>.</sub>

2019-11-05 16:54 UTC, merged

2019-11-05 16:54 UTC, wilsonge commented
Thanks!

2019-11-05 16:54 UTC, wilsonge commented
@waader can you send a separate issue in for the double email sending please?