[4.0] Convert plugin system updatenotification to prepared statements
joomla/joomla-cms pull request #25542
Opened 2019-07-12 21:36 UTC by HLeithner

# Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Use the plugin in all ways you can think of.

Check for update and try an older version of J4.

### Expected result
Nothing changed.

2019-07-13 04:35 UTC, Quy commented on plugins/system/updatenotification/updatenotification.php
>  			if (empty($rawUserIDs))
```suggestion
			if (empty($userIDs))
```

2019-07-16 14:43 UTC, zero-24 commented on plugins/system/updatenotification/updatenotification.php
> +		$paramsJson = $this->params->toString('JSON');
is there a reason we write the params to a variable we only use once? ;)

2019-07-16 14:44 UTC, zero-24 commented on plugins/system/updatenotification/updatenotification.php
> +		$db         = $this->db;
maybe I'm missing something but what is the benefit of using $db over $this->db?

2019-07-16 14:45 UTC, zero-24 requested changes
as noted inline

2019-07-16 14:47 UTC, Quy commented on plugins/system/updatenotification/updatenotification.php
> +		$db         = $this->db;
Shorter notation.

> `>where($this->db->quoteName('type') . ' = ' . $this->db->quote('plugin'))

vs.

> ->where($db->quoteName('type') . ' = ' . $db->quote('plugin'))

2019-07-16 14:54 UTC, zero-24 commented on plugins/system/updatenotification/updatenotification.php
> +		$db         = $this->db;
hmm I personally would still prefer the $this-> syntax and don't write it to just another variable to save a few chars.

2019-07-17 08:06 UTC, SharkyKZ commented on plugins/system/updatenotification/updatenotification.php
> +		$paramsJson = $this->params->toString('JSON');
Yes, we need a variable. Otherwise we get `Only variables should be passed by reference` notices.

2019-07-17 18:24 UTC, HLeithner commented on plugins/system/updatenotification/updatenotification.php
> +		$db         = $this->db;
Sorry, I will not change this.

2019-07-17 19:14 UTC, zero-24 commented on plugins/system/updatenotification/updatenotification.php
> +		$db         = $this->db;
Well than I need to follow that executive decision. :(

2019-07-17 20:17 UTC, HLeithner commented on plugins/system/updatenotification/updatenotification.php
> +		$db         = $this->db;
The reason is only a handful of the plugins uses this syntax so I converted it to the same codestyle.

2019-07-18 05:05 UTC, zero-24 approved these changes

2019-07-18 05:23 UTC, SharkyKZ commented on plugins/system/updatenotification/updatenotification.php
> +		$db         = $this->db;
It's only because not all plugins using injected DB object yet.

2019-08-19 07:17 UTC, alikon commented
I have tested this item :white_check_mark: successfully on ffd3aacd771eb87bf3399e8032ea6c668f3e2d56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25542">issues.joomla.org/tracker/joomla-cms/25542</a>.</sub>

2019-08-21 14:56 UTC, SharkyKZ commented
I have tested this item :white_check_mark: successfully on ffd3aacd771eb87bf3399e8032ea6c668f3e2d56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25542">issues.joomla.org/tracker/joomla-cms/25542</a>.</sub>

2019-08-21 16:36 UTC, franz-wohlkoenig commented
Status "Ready To Commit".

2019-08-23 13:49 UTC, merged