[4.0] Backend template
joomla/joomla-cms pull request #25570
Opened 2019-07-15 12:59 UTC by bembelimen

### Summary of Changes
Based on the design from @coolcat-creations and @svom this PR is the next milestone of the backend template "atum" for Joomla! 4. (see first PR here: #21006)

Team members:
@coolcat-creations, @svom, @chmst , @Hackwar, @nadjak77, @fancyFranci, @lavipr and @karo3 

Special thanks to @brianteeman for a lot of valuable feedback and fixes.

### New features
- Rebuild the login layout including a new AJAX login
- New dashboard functionality: com_cpanel now offers dashboards for every kind of extension where modules can be placed, e.g. com_content: ```administrator/index.php?option=com_cpanel&view=cpanel&dashboard=content```.
- Improvement of the menu with direkt dashboard and creation links.
- New quickicons on the main dashboard
- Filters in list views
- Improved edit screen
- Auto-calculation of the template color based on the template parameters
- extended colorpicker
- a lot of small improvements

Extra ping: @wilsonge

2019-07-15 13:13 UTC, C-Lodder commented on administrator/templates/atum/scss/_mixin.scss
> +  @-webkit-keyframes fadeout {
Remove vendor prefixes

2019-07-15 13:13 UTC, C-Lodder commented on administrator/templates/atum/scss/_mixin.scss
> +  @-webkit-keyframes fadein {
Remove vendor prefixes

2019-07-15 13:14 UTC, C-Lodder commented on administrator/templates/atum/scss/_variables.scss
> +$color-0:                          adjust-color($color-60, $hue: -5%, $saturation: -100%, $lightness: +71.4%);
What is `$color-xx`? Naming convention means nothing to developers

2019-07-15 13:16 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_global.scss
> +.btn-primary:hover {
Wrong place to be doing this

2019-07-15 13:17 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_global.scss
> +    fill: var(--atum-text-dark);
I think this should go inline with the SVG. If the image is changed, then this could effect it

2019-07-15 13:19 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_global.scss
> +  &:before, &:after {
Pseudo elements should contain two `::`

2019-07-15 13:19 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_global.scss
> +  &:after {
Pseudo elements should contain two `::`

2019-07-15 13:19 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_global.scss
> +a[target="_blank"]:before {
Pseudo elements should contain two `::`

2019-07-15 13:20 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_header.scss
> +      &:after {
Pseudo elements should contain two `::`

2019-07-15 13:20 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-joomla:before {
Pseudo elements should contain two `::`

2019-07-15 13:20 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-shield-alt:before {
Pseudo elements should contain two `::`

2019-07-15 13:20 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-user-lock:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-users-cog:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-envelope-open-text:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-map-signs:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-rss:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-language:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-paint-brush:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.info-circle:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-images:before {
Pseudo elements should contain two `::`

2019-07-15 13:21 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_icons.scss
> +.icon-address-book:before {
Pseudo elements should contain two `::`

2019-07-15 13:23 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +      -ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=1)";
Vendor prefixes are not required

2019-07-15 13:24 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +/*mobil*/
`// Mobile`

2019-07-15 13:24 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +  fill: var(--atum-bg-dark);
Don't fill SVG's in the CSS incase users decide to use their own

2019-07-15 13:25 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_tabs.scss
> +				&:after {
Pseudo elements should contain two `::`

2019-07-15 13:25 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_tabs.scss
> +					&:after {
Pseudo elements should contain two `::`

2019-07-15 13:26 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +  >*{
Careful with wildcard selectors in CSS. They bad for performance.

2019-07-15 13:27 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_utilities.scss
> +.com_templates {
This is not a utility

2019-07-15 13:28 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/_bootstrap.scss
> +@import "../../../../../media/vendor/bootstrap/scss/carousel";
Don't import files you're not using.

2019-07-15 13:29 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/_choicesjs.scss
> +	&:after {
Pseudo elements should contain two `::`

2019-07-15 13:29 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/_tinymce.scss
> +		&:before {
Pseudo elements should contain two `::`

2019-07-15 13:32 UTC, C-Lodder commented on build/media_source/com_cpanel/js/admin-add_module.es6.js
> +      const elements = [].slice.call(document.querySelectorAll('#moduleDashboardAddModal .modal-footer .btn.hidden'));
Don't need `[].slice.call(...)`

2019-07-15 13:32 UTC, C-Lodder commented on build/media_source/com_cpanel/js/admin-add_module.es6.js
> +    const buttons = [].slice.call(document.querySelectorAll('#moduleDashboardAddModal .modal-footer .btn'));
Don't need `[].slice.call(...)`

2019-07-15 13:34 UTC, C-Lodder commented on build/media_source/com_cpanel/js/admin-system-loader.es6.js
> + * @copyright  Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
2019

2019-07-15 13:34 UTC, C-Lodder commented on build/media_source/com_modules/js/admin-modules-modal.es6.js
> +    const buttons = [].slice.call(document.querySelectorAll('#moduleDashboardAddModal .modal-footer .btn'));
Don't need `[].slice.call(...)`

2019-07-15 13:37 UTC, C-Lodder commented on build/media_source/com_modules/js/admin-select-modal.es6.js
> +    const elems = [].slice.call(document.querySelectorAll('#new-modules-list a.select-link'));
Don't need `[].slice.call(...)`

2019-07-15 13:37 UTC, C-Lodder commented on build/media_source/mod_menu/js/admin-menu.es6.js
> +    const allLinks = [].slice.call(wrapper.querySelectorAll('a.no-dropdown, a.collapse-arrow, .menu-dashboard > a'));
Don't need `[].slice.call(...)`

2019-07-15 13:38 UTC, C-Lodder commented on build/media_source/mod_quickicon/js/quickicon.es6.js
> +    Array.prototype.forEach.call(document.querySelectorAll('.quickicon'), (quickicon) => {
Don't need `Array.prototype.forEach.call()`

2019-07-15 13:39 UTC, C-Lodder commented on build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
> +    const quickicon = document.querySelector('#plg_quickicon_privacycheck');
Use `document.getElementById('plg_quickicon_privacycheck')`

2019-07-15 14:27 UTC, infograf768 commented
Can we start discussing some UI aspects of this proposal?

2019-07-15 14:35 UTC, brianteeman commented on administrator/templates/atum/scss/vendor/_choicesjs.scss
> +	&:after {
Note: As a rule, double colons (::) should be used instead of a single colon (:). This distinguishes pseudo-classes from pseudo-elements. However, since this distinction was not present in older versions of the W3C spec, most browsers support both syntaxes for the original pseudo-elements.
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements

2019-07-15 14:36 UTC, wilsonge commented
Largely the time to discuss the UI was when the design proposals got released nearly 18 months ago in December 2017. So basically no unless it's minor things.

2019-07-15 14:38 UTC, mbabker commented
It should also be noted that the installation template was updated.  This is not just the administrative interface.

Changes requested in installation template:

1) Use a different icon for the "Select Installation Language" box, at the scale the current icons are rendered at it doesn't really look like a text character as intended.

![Screen Shot 2019-07-15 at 9 30 11 AM](https://user-images.githubusercontent.com/368545/61224297-f59ced00-a6e3-11e9-8faf-5a451bea53dc.png)

2) Use a different icon for the "Login Data" box, a user icon is more appropriate in this context than a heart.

![Screen Shot 2019-07-15 at 9 30 39 AM](https://user-images.githubusercontent.com/368545/61224412-24b35e80-a6e4-11e9-89f0-7f3123255d46.png)

3) The "Select the database type" field lacks any indication it is a select field.
 
![Screen Shot 2019-07-15 at 9 30 53 AM](https://user-images.githubusercontent.com/368545/61224424-2c730300-a6e4-11e9-91e5-85a85316682e.png)

2019-07-15 14:41 UTC, bembelimen commented
> 
> 
> It should also be noted that the installation template was updated. This is not just the administrative interface.

Ahh, yes, I updated the intro post. The installation template is heavily dependend on the backend template (sharing the same CSS), so we had to take care of both.

2019-07-15 14:46 UTC, mbabker commented
Actually using this template now, the concerns that have been raised in the past about the reorganized content structure really need to be vetted and discussed.  This new system dashboard is an information overload screen and users are losing the ability to navigate to key sections of the administrative area without going through it.  Yes, it might have been link overload to have direct links to every area in the admin menu previously, but it kept the entire admin accessible with ease to end users.  Now, a number of areas are buried away (minus select links on the "Home Dashboard").  You don't feel the change when looking at it solely as mockups, but spending practical time on a functional version of the template makes this shift much more evident.

2019-07-15 14:46 UTC, C-Lodder commented on build/media_source/templates/atum/js/template.es6.js
> +    const logoImgs = [].slice.call(document.querySelectorAll('.logo img'));
Don't need `[].slice.call(...)`

2019-07-15 14:48 UTC, C-Lodder commented on build/media_source/templates/atum/js/template.es6.js
> +      contentChildren[i].classList.add(`load-fade${fadeAction}`);
Do you really want to loop through all child nodes of the content container and sidebar? Can you not just apply this to the parent element?

2019-07-15 14:49 UTC, C-Lodder commented on build/media_source/templates/atum/js/template.es6.js
> +      const headerMoreItems = [].slice.call(headerMore.querySelectorAll('.header-item'));
Don't need `[].slice.call(...)`

2019-07-15 14:49 UTC, C-Lodder commented on installation/template/images/joomla-pattern.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Please minify SVG's

2019-07-15 14:50 UTC, C-Lodder commented on installation/template/images/logo-joomla-blue.svg
> +<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
Please minify SVG's

2019-07-15 14:50 UTC, brianteeman commented on administrator/templates/atum/templateDetails.xml
> +						name="hue"
this block is indented one tab too many

2019-07-15 14:51 UTC, C-Lodder commented on installation/template/index.php
> +						<img src="<?php echo $this->baseurl; ?>/template/images/logo-joomla-blue.svg" alt=""/>
Slash not required on void elements in HTML5

2019-07-15 14:52 UTC, brianteeman commented
It should be pointed out that both @zwiastunsw and myself have expressed several accessibility concerns with the quickicons on the home dashboard

2019-07-15 14:52 UTC, C-Lodder commented on layouts/joomla/form/field/color/slider.php
> +		/>
Slash not required on void elements in HTML5

2019-07-15 14:52 UTC, C-Lodder commented on layouts/joomla/form/field/color/slider.php
> +		/>
Slash not required on void elements in HTML5

2019-07-15 14:52 UTC, C-Lodder commented on layouts/joomla/form/field/color/slider.php
> +		/>
Slash not required on void elements in HTML5

2019-07-15 14:52 UTC, C-Lodder commented on layouts/joomla/form/field/color/slider.php
> +		/>
Slash not required on void elements in HTML5

2019-07-15 14:53 UTC, C-Lodder commented on layouts/joomla/form/field/color/slider.php
> +	/>
Slash not required on void elements in HTML5

2019-07-15 14:53 UTC, C-Lodder commented on layouts/joomla/form/field/color/slider.php
> +	/>
Slash not required on void elements in HTML5

2019-07-15 14:53 UTC, brianteeman commented on administrator/components/com_associations/layouts/joomla/searchtools/default.php
> + * @package     Joomla.Site
please revert this change

2019-07-15 14:56 UTC, C-Lodder commented on installation/template/scss/template.scss
> +.badge-warning {
Why is this here?

2019-07-15 14:56 UTC, mbabker commented
The following CSS has broken the Bootstrap `.btn-outline-*` classes:

```css
.btn {
    border-radius: 0;
    border: none;
}
```

(I do not have the time at the moment to scan through your SCSS files to find the offending lines)

The 4.0 version of the Install from Web layouts presently uses the `btn-outline-secondary` class on its appended search buttons, because of this over-eager rule there are no borders forcibly placed on all button classes.  The template should correctly support the `btn-outline-*` variants as documented in https://getbootstrap.com/docs/4.3/components/buttons/#outline-buttons, otherwise you end up with random floating icons or text (in the case of buttons appended to an input there's no visual connection until you hover, and in the case of standalone use there is no styling at all).

![Screen Shot 2019-07-15 at 9 50 02 AM](https://user-images.githubusercontent.com/368545/61225410-18c89c00-a6e6-11e9-9673-f51255d118c4.png)

2019-07-15 14:56 UTC, brianteeman commented on administrator/components/com_cache/Controller/DisplayController.php
> +	public function getQuickiconContent()
I still say that displaying the size of the cache is meaningless. Depending on the site a size of 100Mb might be large or small. If there is no meaning it should not be there

2019-07-15 14:58 UTC, brianteeman commented on administrator/components/com_checkin/tmpl/checkin/default.xml
> +			>
```suggestion
				>
```

2019-07-15 15:01 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
>  				>
```suggestion
					>
```

2019-07-15 15:01 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
>  				>
```suggestion
					>
```

2019-07-15 15:01 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
>  				>
```suggestion
					>
```

2019-07-15 15:03 UTC, brianteeman commented on administrator/components/com_contact/tmpl/contact/edit_associations.php
> +$hasAssoc = !($this->form->getValue('language', null, '*') === '*');
The changes made here are the same as in other edit_associations.php files
Shouldnt they be made in the layout itself?

2019-07-15 15:04 UTC, brianteeman commented on administrator/components/com_contact/tmpl/contacts/default.php
> +		<?php if (!empty($this->sidebar)) : ?>
please revert this change tat puts the empty sidebar back - it was removed on purpose

2019-07-15 15:05 UTC, brianteeman commented on administrator/components/com_content/config.xml
> +			>
```suggestion
				>
```

2019-07-15 15:07 UTC, mbabker commented
1) The sidebar does not correct extend down the page height on the Install from Web layout the same way it does in other areas (this was checked against the admin modules screen which is large enough to force a scroll)

2) To me it seems like the main header should also be sticky on page scroll and not only the toolbar container

![Screen Shot 2019-07-15 at 10 04 54 AM](https://user-images.githubusercontent.com/368545/61226469-16674180-a6e8-11e9-84bb-06e88bf6b51d.png)

2019-07-15 15:08 UTC, brianteeman commented on administrator/components/com_fields/forms/field.xml
>  				>
```suggestion
					>
```

2019-07-15 15:09 UTC, mbabker commented
I'm going to assume some merge went bad as there are untranslated strings on one of the edit module screens.

![Screen Shot 2019-07-15 at 10 09 03 AM](https://user-images.githubusercontent.com/368545/61226744-9d1c1e80-a6e8-11e9-8ba6-15e625ba16f5.png)

2019-07-15 15:10 UTC, brianteeman commented on administrator/components/com_installer/tmpl/database/default.xml
> +					name="ajax-badge"
```suggestion
				name="ajax-badge"
```

2019-07-15 15:11 UTC, brianteeman commented on administrator/components/com_installer/tmpl/database/default.xml
> +					type="radio"
```suggestion
				type="radio"
```

2019-07-15 15:11 UTC, brianteeman commented on administrator/components/com_installer/tmpl/database/default.xml
> +					class="switcher"
```suggestion
				class="switcher"
```

2019-07-15 15:11 UTC, brianteeman commented on administrator/components/com_installer/tmpl/database/default.xml
> +					label="COM_INSTALLER_DATABASE_VIEW_DISPLAY_BADGE"
```suggestion
				label="COM_INSTALLER_DATABASE_VIEW_DISPLAY_BADGE"
```

2019-07-15 15:12 UTC, brianteeman commented on administrator/components/com_installer/tmpl/database/default.xml
> +					default=""
```suggestion
				default=""
```

2019-07-15 15:12 UTC, mbabker commented
While I get the intent behind https://github.com/joomla/backend-template/pull/393 IMO that should be reverted.  The com_privacy dashboard isn't intended to be something that is user customizable in the same way other dashboards are (it's not really a dashboard in the sense of how you're using them in this template either).

2019-07-15 15:12 UTC, brianteeman commented on administrator/components/com_installer/tmpl/database/default.xml
> +			>
```suggestion
				>
```

2019-07-15 15:12 UTC, brianteeman commented on administrator/components/com_installer/tmpl/discover/default.xml
> +			<field
remove one tab from this block

2019-07-15 15:12 UTC, brianteeman commented on administrator/components/com_installer/tmpl/discover/default.xml
> +			>
```suggestion
				>
```

2019-07-15 15:13 UTC, brianteeman commented on administrator/components/com_installer/tmpl/update/default.xml
> +					name="ajax-badge"
remove one tab from this block

2019-07-15 15:13 UTC, mbabker commented
`administrator/index.php?option=com_cpanel&view=cpanel&dashboard=help` has all sorts of untranslated strings.

2019-07-15 15:13 UTC, brianteeman commented on administrator/components/com_installer/tmpl/update/default.xml
> +			>
```suggestion
				>
```

2019-07-15 15:13 UTC, brianteeman commented on administrator/components/com_installer/tmpl/warnings/default.xml
> +					name="ajax-badge"
remove one tab from this block

2019-07-15 15:13 UTC, brianteeman commented on administrator/components/com_installer/tmpl/warnings/default.xml
> +			>
```suggestion
				>
```

2019-07-15 15:14 UTC, brianteeman commented on administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default.xml
> +					name="ajax-badge"
remove one tab from this block

2019-07-15 15:14 UTC, brianteeman commented on administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default.xml
> +			>
```suggestion
				>
```

2019-07-15 15:15 UTC, infograf768 commented
I consider this Home Dashboard as a full mess. Is that out of debate?
For example:
Update Checks should always be prominent and, if any one really wants to add the redundant icons through the same parameters available in the 3 different modules (Site, System, Update Checks ) Update Checks should always be on top.

IMHO, Update Checks should just be alone, with the real Updates and nothing else. Its default order should be first among position icon.

2019-07-15 15:16 UTC, mbabker commented
1) The word "Joomla" is potentially redundant on the status bar, and when non-stable versions are present this causes truncated text.  Maybe just show the version string.

2) What is this "Accessibility Settings" item in the User Menu supposed to be, aside from the dead link it is now?

![Screen Shot 2019-07-15 at 10 14 19 AM](https://user-images.githubusercontent.com/368545/61227203-7f02ee00-a6e9-11e9-91f9-606fcdf46e57.png)

2019-07-15 15:17 UTC, brianteeman commented on administrator/components/com_menus/layouts/joomla/searchtools/default.php
> + * @package     Joomla.Site
Please revert this change
```suggestion
 * @package     Joomla.Administrator
```

2019-07-15 15:19 UTC, brianteeman commented on administrator/components/com_menus/presets/help.xml
> +	<menuitem
I still say that these are not help items and do not belong in the ui
https://github.com/joomla/backend-template/issues/259

2019-07-15 15:21 UTC, mbabker commented
The current structure of the post-install dropdown is a bit confusing to me.

1) There is no "view all messages" link

2) The way each individual item is linked to me implies you'll be taken to a page with that message individually rendered, instead they all link to the same dashboard page.

IMO either have one "view all" link and not link each message individually or improve the postinstall component to allow a single message to be viewed at once and have each message's link go to that page.

![Screen Shot 2019-07-15 at 10 17 29 AM](https://user-images.githubusercontent.com/368545/61227373-cb4e2e00-a6e9-11e9-8057-99a53a996be6.png)

2019-07-15 15:21 UTC, brianteeman commented on administrator/components/com_menus/tmpl/items/default.php
> +				<?php if (!empty($this->items)) : ?>
What is the logic behind making this change. Surely we want to display the message that this removes

2019-07-15 15:25 UTC, brianteeman commented on administrator/components/com_newsfeeds/forms/filter_newsfeeds.xml
> +			multiple="true"
please move this line. the codestyle is name, type, label....

2019-07-15 15:26 UTC, brianteeman commented on administrator/components/com_postinstall/tmpl/messages/default.xml
> +			>
```suggestion
				>
```

2019-07-15 15:27 UTC, brianteeman commented on administrator/components/com_postinstall/tmpl/messages/default.xml
> +					name="ajax-badge"
please remove one tab on this block

2019-07-15 15:28 UTC, TobsBobs commented
Where can I find an installable version?

2019-07-15 15:29 UTC, brianteeman commented on administrator/components/com_tags/forms/tag.xml
>  				>
```suggestion
					>
```

2019-07-15 15:29 UTC, brianteeman commented on administrator/components/com_tags/forms/tag.xml
>  				>
```suggestion
					>
```

2019-07-15 15:30 UTC, mbabker commented
Double labels?

![Screen Shot 2019-07-15 at 10 30 25 AM](https://user-images.githubusercontent.com/368545/61228292-9ba02580-a6eb-11e9-9bd7-7a78ed375228.png)

2019-07-15 15:32 UTC, brianteeman commented on administrator/components/com_userlogs/views/userlogs/tmpl/default.php
> +<?php
there is no component called com_userlogs

2019-07-15 15:34 UTC, mbabker commented
User status on edit user seems a little backwards.

![Screen Shot 2019-07-15 at 10 33 39 AM](https://user-images.githubusercontent.com/368545/61228549-179a6d80-a6ec-11e9-9e6c-1ae1f693db57.png)
![Screen Shot 2019-07-15 at 10 33 49 AM](https://user-images.githubusercontent.com/368545/61228553-19fcc780-a6ec-11e9-94ed-c6c7468305b8.png)

2019-07-15 15:36 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_installer.sys.ini
> +COM_INSTALLER_DATABASE_VIEW_DISPLAY_BADGE="Display Badge"
delete this line - it is a duplicate of line 12

2019-07-15 15:36 UTC, mbabker commented
z-index issue with modals

![Screen Shot 2019-07-15 at 10 35 57 AM](https://user-images.githubusercontent.com/368545/61228678-5f20f980-a6ec-11e9-9e61-bb5d654a4277.png)

2019-07-15 15:38 UTC, mbabker commented
No active state for sidebars?

![Screen Shot 2019-07-15 at 10 37 23 AM](https://user-images.githubusercontent.com/368545/61228807-9a232d00-a6ec-11e9-8ad9-6b421f992ca1.png)

2019-07-15 15:39 UTC, mbabker commented
There is a lot of padding on the permissions widget.

![Screen Shot 2019-07-15 at 10 39 00 AM](https://user-images.githubusercontent.com/368545/61228919-cc348f00-a6ec-11e9-8831-7b021854459a.png)

2019-07-15 15:40 UTC, wilsonge commented on build/media_source/com_cpanel/js/admin-system-loader.es6.js
> + * @copyright  Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
This will be covered automatically whenever the release script gets run

2019-07-15 15:43 UTC, franz-wohlkoenig commented
> Where can I find an installable version?

@TobsBobs Download:
![Screen Shot 2019-07-15 at 17 42 46](https://user-images.githubusercontent.com/8235763/61229182-01aa9e00-a728-11e9-93fe-cf6b03ea3052.png)

2019-07-15 15:45 UTC, infograf768 commented
@franz-wohlkoenig
https://github.com/bembelimen/joomla-cms/tree/backend-template

2019-07-15 15:47 UTC, infograf768 commented
`+ Module` quickicon loads the Select module page depending on the filter state in the modules Manager, therefore can display Admin modules when the common use would be Site Modules
<img width="334" alt="Screen Shot 2019-07-15 at 17 42 55" src="https://user-images.githubusercontent.com/869724/61229521-a331ef80-a728-11e9-8c31-db77c149fbc9.png">

2019-07-15 15:48 UTC, mbabker commented
That's not downloadable, it misses Composer and NPM.  The backend template should have been hooked up to CI from the first day and offered as a nightly build or with a dedicated build the same way we did the com_privacy package before it was merged to 3.9.

2019-07-15 15:54 UTC, brianteeman commented
Monochrome option in the template does not work https://github.com/joomla/backend-template/issues/348

2019-07-15 15:55 UTC, brianteeman commented
Keyboard navigation of search tools does not follow expected path - this is an a11y fail
https://github.com/joomla/backend-template/issues/310

2019-07-15 15:56 UTC, brianteeman commented
@infograf768 re the quickicons - you are not alone. they really are a clusterf....  of usability and accessability See https://github.com/joomla/backend-template/issues/115

2019-07-15 16:00 UTC, mbabker commented
No idea if this is an emulator problem or if everything has not been thoroughly tested at mobile sizes, but it's impossible to fully scroll the menu when it expands beyond the size of the screen (you have to collapse elements to get it back to under the screen size to make it work).

![Screen Shot 2019-07-15 at 10 59 09 AM](https://user-images.githubusercontent.com/368545/61230418-9e9d1500-a6ef-11e9-9fb7-4f8499e83792.png)

2019-07-15 16:01 UTC, mbabker commented
Content overflow

![Screen Shot 2019-07-15 at 11 01 00 AM](https://user-images.githubusercontent.com/368545/61230567-e02dc000-a6ef-11e9-9d83-43d043837ae9.png)

2019-07-15 16:02 UTC, mbabker commented
Actually, don't bother with mobile, as it's now evident to me this hasn't been tested beyond desktop displays.

![Screen Shot 2019-07-15 at 11 01 40 AM](https://user-images.githubusercontent.com/368545/61230631-03f10600-a6f0-11e9-94a8-e4769d626126.png)

2019-07-15 16:17 UTC, brianteeman commented on administrator/components/com_categories/forms/filter_categories.xml
> +			multiple="true"
please move this down one line. the codestyle should be name, type, label ....

2019-07-15 16:21 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
> +					class="chzn-color"
```suggestion
					class="custom-select-color"
```

Please undo this revert

2019-07-15 16:22 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
> +					class="chzn-color"
```suggestion
				class="custom-select-color"
```
Please undo this revert

2019-07-15 16:22 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
> +					class="chzn-color"
```suggestion
				class="custom-select-color"
```
Please undo this revert

2019-07-15 16:23 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
> +					class="chzn-color"
```suggestion
				class="custom-select-color"
```
Please undo this revert

2019-07-15 16:23 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
>  				size="30"
```suggestion
					size="30"
```

2019-07-15 16:24 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
>  				>
```suggestion
					>
```

2019-07-15 16:25 UTC, brianteeman commented on administrator/components/com_contact/tmpl/contact/edit_metadata.php
> +<fieldset id="fieldset-metadata" class="options-fieldset option-fieldset-full">
The changes made here are the same as in other edit_metadata.php files
Shouldnt they be made in the layout itself?

2019-07-15 16:31 UTC, brianteeman commented on administrator/components/com_cpanel/tmpl/cpanel/default.php
> +		'footer'      => '<button type="button" class="button-cancel  btn btn-sm btn-danger" data-dismiss="modal" data-target="#closeBtn" aria-hidden="true"><span class="icon-cancel" aria-hidden="true"></s
```suggestion
		'footer'      => '<button type="button" class="button-cancel btn btn-sm btn-danger" data-dismiss="modal" data-target="#closeBtn" aria-hidden="true"><span class="icon-cancel" aria-hidden="true"></span>'
```

2019-07-15 16:32 UTC, brianteeman commented on administrator/components/com_cpanel/tmpl/cpanel/default.php
> +			. '<button type="button" class="button-save  btn btn-sm btn-success hidden" data-target="#saveBtn" aria-hidden="true"><span class="icon-save" aria-hidden="true"></span>'
``
```suggestion
			. '<button type="button" class="button-save btn btn-sm btn-success hidden" data-target="#saveBtn" aria-hidden="true"><span class="icon-save" aria-hidden="true"></span>'
```

2019-07-15 16:38 UTC, brianteeman commented on administrator/components/com_languages/tmpl/language/edit.php
> +			<fieldset  id="fieldset-details" class="options-fieldset">
```suggestion
			<fieldset id="fieldset-details" class="options-fieldset">
```

2019-07-15 16:55 UTC, brianteeman commented
Repeating it here because it will be lost on the other repo.
Most of the changes in this PR were committed directly in to the template repo without any usable commit message and zero testing .
Thats why there have already been so many correction comments

There are also a number of changes here that are not template related and as many/most of them were committed directly it is going to be challenging to test them all. Especially critical things such as login

2019-07-15 18:26 UTC, brianteeman commented
> User status on edit user seems a little backwards.
> 

That was nothing to do with this PR - created a fix here #25575

2019-07-15 18:34 UTC, brianteeman commented
> Largely the time to discuss the UI was when the design proposals got released nearly 18 months ago in December 2017. So basically no unless it's minor things.

Except that there are many aspects of this code that do NOT match the design proposals - in fact I find only **one** image from the proposal https://magazine.joomla.org/issues/issue-nov-2017/item/3289-episode-iv-a-new-user-interface-for-the-joomla-backend that matches

2019-07-15 22:20 UTC, brianteeman commented
> Largely the time to discuss the UI was when the design proposals got released nearly 18 months ago in December 2017. So basically no unless it's minor things.

As you can see taking this one example. There was considerable objection to the "marketing" in the help screen. So there was discussion it was just ignored
https://github.com/joomla/joomla-cms/issues/21990

2019-07-15 23:40 UTC, wilsonge commented
https://developer.joomla.org/backend-template/ Nightly builds for the backend template

2019-07-16 06:27 UTC, SharkyKZ commented on libraries/namespacemap.php
> +				&& strpos($extension, 'atum') !== 0
Why is atum hardcoded here?

2019-07-16 06:31 UTC, alikon requested changes

2019-07-16 06:31 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('System Submenu', '', NULL, 1, 'cpanel-system', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"system","layout":"_:default
the default null date for postgresql is `1970-01-01 00:00:00`  and not `0000-00-00 00:00:00`
please change

2019-07-16 06:53 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('System Submenu', '', NULL, 1, 'cpanel-system', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"system","layout":"_:default
```suggestion
('System Submenu', '', NULL, 1, 'cpanel-system', 0, '1970-01-01 00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"system","layout":"_:default","moduleclass_sfx":"","module_tag":"div","bootstrap_size":"12","header_tag":"h3","header_class":"","style":"System-none"}', 1, '*')
```

2019-07-16 06:54 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('Content Submenu', '', NULL, 1, 'cpanel-content', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"content","layout":"_:defa
```suggestion
('Content Submenu', '', NULL, 1, 'cpanel-content', 0, '1970-01-01 00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"content","layout":"_:default","moduleclass_sfx":"","module_tag":"div","bootstrap_size":"3","header_tag":"h3","header_class":"","style":"System-none"}', 1, '*')
```

2019-07-16 06:54 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('Menus Submenu', '', NULL, 1, 'cpanel-menus', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"menus","layout":"_:default","
```suggestion
('Menus Submenu', '', NULL, 1, 'cpanel-menus', 0, '1970-01-01 00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"menus","layout":"_:default","moduleclass_sfx":"","module_tag":"div","bootstrap_size":"6","header_tag":"h3","header_class":"","style":"System-none"}', 1, '*')
```

2019-07-16 06:54 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('Components Submenu', '', NULL, 1, 'cpanel-components', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"components","layout
```suggestion
('Components Submenu', '', NULL, 1, 'cpanel-components', 0, '1970-01-01 00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"components","layout":"_:default","moduleclass_sfx":"","module_tag":"div","bootstrap_size":"12","header_tag":"h3","header_class":"","style":"System-none"}', 1, '*')
```

2019-07-16 06:55 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('Users Submenu', '', NULL, 1, 'cpanel-content', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"users","layout":"_:default"
```suggestion
('Users Submenu', '', NULL, 1, 'cpanel-content', 0, 1970-01-01 00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00', 1, 'mod_submenu', 1, 0, '{"menutype":"*","preset":"users","layout":"_:default","moduleclass_sfx":"","module_tag":"div","bootstrap_size":"6","header_tag":"h3","header_class":"","style":"System-none"}', 1, '*')
```

2019-07-16 06:56 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('Popular Articles', '', '', 3, 'cpanel-content', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_popular', 3, 1, '{"count":"5","catid":"","user_id":"0","layout":"_:de
```suggestion
('Popular Articles', '', '', 3, 'cpanel-content', 0, '1970-01-01 00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00', 1, 'mod_popular', 3, 1, '{"count":"5","catid":"","user_id":"0","layout":"_:default","moduleclass_sfx":"","cache":"0", "bootstrap_size": "6"}', 1, '*');
```

2019-07-16 06:56 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('Recently Added Articles', '', '', 4, 'cpanel-content', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_latest', 3, 1, '{"count":"5","ordering":"c_dsc","catid":"","us
```suggestion
('Recently Added Articles', '', '', 4, 'cpanel-content', 0, '1970-01-01 00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00', 1, 'mod_latest', 3, 1, '{"count":"5","ordering":"c_dsc","catid":"","user_id":"0","layout":"_:default","moduleclass_sfx":"","cache":"0", "bootstrap_size": "6"}', 1, '*');
```

2019-07-16 06:56 UTC, brianteeman commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
> +('Logged-in Users', '', '', 2, 'cpanel-users', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_logged', 3, 1, '{"count":"5","name":"1","layout":"_:default","moduleclas
```suggestion
('Logged-in Users', '', '', 2, 'cpanel-users', 0, '1970-01-01 00:00:00', '1970-01-01 00:00:00', '1970-01-01 00:00:00', 1, 'mod_logged', 3, 1, '{"count":"5","name":"1","layout":"_:default","moduleclass_sfx":"","cache":"0", "bootstrap_size": "6"}', 1, '*');
```

2019-07-16 06:57 UTC, brianteeman commented on administrator/components/com_associations/layouts/joomla/searchtools/default.php
> + * @package     Joomla.Site
```suggestion
 * @package     Joomla.Administrator
```

2019-07-16 07:21 UTC, micker commented
as i can test changing bootstrap grid for dashboard module doesn't works :
1 edit  quickicon module 
2 set bootstrap size to 12
=> no change module is display in 1/2

2019-07-16 09:18 UTC, astridx commented
I like the view and the behavior of the new template very well. Thank you for this.

I just installed the nightly build. 

What I noticed is:

The options tab are broken in my case:
![Articles  Options   test   Administration(3)](https://user-images.githubusercontent.com/9974686/61281576-23ecfc00-a7ba-11e9-84fc-aef8732a7817.png)
![Articles  Options   test   Administration(2)](https://user-images.githubusercontent.com/9974686/61281577-23ecfc00-a7ba-11e9-84f6-2d6d751b6fca.png)

This issues still exist in my case:
https://github.com/joomla/backend-template/issues/302
https://github.com/joomla/backend-template/issues/332
Screenshots from the nightly build.
![Articles  New   test   Administration](https://user-images.githubusercontent.com/9974686/61282319-6f53da00-a7bb-11e9-8544-79cdf80247b9.png)
![Extensions  Discover   test   Administration](https://user-images.githubusercontent.com/9974686/61282320-6f53da00-a7bb-11e9-91d9-e722a79e6f9f.png)
![Control Panel   test   Administration(2)](https://user-images.githubusercontent.com/9974686/61282321-6f53da00-a7bb-11e9-9f42-f3e92e0081b9.png)



I tested it on ubunut 18.04 in Firefox on a notebook with the resolution 1366x768

2019-07-16 12:09 UTC, micker commented
### What needs to be fixed
the logo for login page have an heigh
![2019-07-16_14h02_34](https://user-images.githubusercontent.com/2539440/61292873-abdf0000-a7d2-11e9-92aa-43a2a0a5e6be.png)


### Why this should be fixed
disable height is better
![2019-07-16_14h05_06](https://user-images.githubusercontent.com/2539440/61292922-c2855700-a7d2-11e9-9f50-27dabc85c6c4.png)

2019-07-16 12:10 UTC, micker commented
### Steps to reproduce the issue
Edit atum primary color like 105
Save and reload
![2019-07-16_12h02_40](https://user-images.githubusercontent.com/2539440/61285658-a0cfa400-a7c1-11e9-8d50-960efda05ecd.png)

### Expected result
color seating need be 105


### Actual result
color setting is always 207

2019-07-16 12:11 UTC, micker commented
https://github.com/joomla/joomla-cms/issues/25579

2019-07-16 12:20 UTC, micker commented
### What needs to be fixed
new dashboard add 2 buttons 
1 for list
1 for add
but i think the design isn't good because too many button in same zone, different size, different design ...
![2019-07-16_09h24_10](https://user-images.githubusercontent.com/2539440/61274152-7a9f0980-a7ab-11e9-8e6d-802c99c535b4.png)
### Why this should be fixed
Maybe when have more consistent design to use same systeme like media manager

![2019-07-16_09h28_40](https://user-images.githubusercontent.com/2539440/61274455-247e9600-a7ac-11e9-9efa-05305a19987b.png)

Need to check if accessibility is good .. 

=> i do it with simple css modfication (i am not great css writter i didn't push code) no html change ..
for me have 2 same labels for each button isn't good for acessibility. ex users button to user list and an other button user to add isn't consistent..
its a detail but its the first screen for every user
maybe this can be better
![2019-07-16_11h02_04](https://user-images.githubusercontent.com/2539440/61281007-2d299900-a7b9-11e9-8430-8077e644613c.png)
@coolcat-creations @bembelimen  what do you think ?

2019-07-16 12:39 UTC, micker commented
### What needs to be fixed
hello i like new administration template it realy good first step !!!
i like the idea that joomla will be more simple and usefull  (group button, group action)

### Why this should be fixed
i think we can do more with filter and search ... many time user doesn't use it realy i think. It a big block for nothing at first
![2019-07-16_11h44_03](https://user-images.githubusercontent.com/2539440/61284331-05d5ca80-a7bf-11e9-88dd-2915e4f2ed85.png)

### How would you fix it
Maybe we can move this bar in  action zone hide search input
![2019-07-16_11h46_58](https://user-images.githubusercontent.com/2539440/61284528-6e24ac00-a7bf-11e9-8485-07cbd7a0234b.png)

or maybe more 
put all in a search and filter button
![image](https://user-images.githubusercontent.com/2539440/61284760-f3a85c00-a7bf-11e9-8dee-04cef1b1297c.png)

2019-07-16 12:43 UTC, coolcat-creations commented
@micker I can only speak for myself that I and my customers use the searchbox a lot - usertesting could reveal if thats generally the case.

2019-07-16 12:48 UTC, micker commented
@coolcat-creations i didn't the global answer ... lol 
maybe we can group number + order in filtering zone for me its a filtering take search outside
we will win space, more usuable admin i think

2019-07-16 12:54 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_header.scss
> +      }
Add for .joomlaversion `direction: ltr;` for RTL reasons

2019-07-16 13:05 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_header.scss
> +      }
`direction: ltr;` is default so strange it would need it

2019-07-16 13:09 UTC, brianteeman commented on administrator/templates/atum/scss/blocks/_header.scss
> +      }
it is so that the number is still displayed as LTR when the language is RTL

2019-07-16 19:58 UTC, richard67 commented
@alikon You mentioned the default null date for postgresql in your review. But how about MySQL? In the code of this PR here '0000-00-00 00:00:00' is used everywhere for MySQL, but hasn't that changed to '1001-00-00 00:00:00' with some MySQL version lower than the minimum for 4.0?

2019-07-17 05:59 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_header.scss
> +      }
In fact not exactly the number, but the whole phrase, i.e a mix of numbers, latin glyphs and exclamation mark ` Joomla! 4.0.0-alpha11-dev `
This is mostly due in this specific case to the use of `text-overflow: ellipsis;`
<img width="166" alt="Screen Shot 2019-07-17 at 07 38 52" src="https://user-images.githubusercontent.com/869724/61349877-f8275000-a865-11e9-9f77-64160bdf2f25.png">

2019-07-17 06:28 UTC, alikon commented
@richard67  should be better to start in 4.x with `'1001-01-01 00:00:00'`  imho  that's why i've made #25461, but seems few people care about db's stuff

2019-07-17 07:18 UTC, chmst commented on administrator/templates/atum/scss/blocks/_header.scss
> +      }
Normal releases will have a number like Joomla! 4.0.2 where no ellipsis occours.

2019-07-17 08:43 UTC, micker commented
other return :
**1 logo**
when we use custom logo in admin, joomla logo is changed that cool but when we collaps the left menu this logo is change for joomla! logo. In fact its a good idea to change but for user it's not very good. Old user already know that joomla logo go to principal dashboard but new user need to understand ... it can be good to use an home or dashboard icon ?

**Dashboard**
its realy a good adding dashboard and subdashoard, the adding button on bottom is pretty cool ! but we have an no finished function... did you plan to add drag and drop ordering and rezize width ?

Thanks for team works

2019-07-17 09:11 UTC, brianteeman commented
@micker there are THREE logo fields in the template style to give you maximum flexibility and to fix your problems

2019-07-17 09:24 UTC, micker commented
@brianteeman .. ahh i forgot we arlready have 3 fileds ? maybe its not realy necessary because need to create a very small logo but you are right its the most flexible

2019-07-17 10:19 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_header.scss
> +      }
As far as I know, for 4.0 we will be available to update to non stable releases.
Better be safe than sorry... Adding that is not a big deal...

2019-07-17 12:36 UTC, mbabker commented on administrator/templates/atum/scss/blocks/_header.scss
> +      }
That's why in https://github.com/joomla/joomla-cms/pull/25570#issuecomment-511444917 (buried between 100 codestyle comments) I suggested perhaps the word "Joomla" might not be needed here.  We should be making every effort to show the full version string, not just a partial string.

2019-07-17 15:48 UTC, brianteeman commented
The reason that rows have borders is to help with the readability. They prevent your eyes from wandering on to a different line when you scan from left to right etc.

If you look at the border on the new template admin modules it is so light that it might as well not be there and the extra white space due to the increased row height and reduced font size make it so much harder to read.

### Current Template
![image](https://user-images.githubusercontent.com/1296369/61390112-14e97500-a8b2-11e9-9f74-c090689e44ec.png)

### New Template
![image](https://user-images.githubusercontent.com/1296369/61390079-01d6a500-a8b2-11e9-8f92-f4afc3ba30d6.png)

It is even worse on full width list views that do not have a lot of columns
![image](https://user-images.githubusercontent.com/1296369/61390358-8f19f980-a8b2-11e9-9c4b-feeb7640ace3.png)

![image](https://user-images.githubusercontent.com/1296369/61390420-ab1d9b00-a8b2-11e9-9225-fbdc997c7dcc.png)

2019-07-17 16:20 UTC, coolcat-creations commented
https://alistapart.com/article/web-typography-tables/

> "Designing Tables to be Read, Not Looked At" Avoid using row or column borders unless the data alignment, spacing and grouping are not sufficient to guide your reader’s eye. If you do need to use rules for this purpose, use them in one direction only and employ a lighter colour to reduce the impact of the lines: you are making a distinction, not constructing a barricade.

2019-07-17 16:22 UTC, brianteeman commented
Thank you for confirming exactly what I said

2019-07-17 16:27 UTC, coolcat-creations commented
I actually did not confirm it, the article says to avoid using borders.
The change was made due to users feedback. Just saying.

2019-07-17 16:32 UTC, coolcat-creations commented
https://design-tips.caneco.xyz/
https://design-tips.caneco.xyz/20170816/

2019-07-17 16:35 UTC, brianteeman commented
> unless the data alignment, spacing and grouping are not sufficient to guide your reader’s eye. If

2019-07-17 16:41 UTC, coolcat-creations commented
IMHO this layout is completely sufficient to lead a readers eye - its more calm, has more spacing, less clutter, much easier to read and less disturbing. Only way to find out the truth is to do some user testing with a significant large group and A/B tests.

2019-07-17 16:50 UTC, mbabker commented
1) I'm highly curious why the `--toolbar-bg` CSS variable is being misused for more elements than the toolbar background (like the table borders or the backgrounds for the quickicons).

2) Try `#e8e8e8` or `#ebebeb` for the border color (basically 3-4% darker than the current `#f5f5f5`).  It's still light enough it's not a distraction but for my eyes darkens the borders just enough they're usable.

2019-07-17 16:51 UTC, mbabker commented
The border weight is just inconsistent in general between element types too.

Compare the sample data module (using the Bootstrap list group) with anything else (which are just tables).

![Screen Shot 2019-07-17 at 11 50 40 AM](https://user-images.githubusercontent.com/368545/61394619-279b8400-a889-11e9-8233-e84361128fa2.png)

2019-07-17 17:02 UTC, richard67 commented
> 
> 
> @richard67 should be better to start in 4.x with `'1001-01-01 00:00:00'` imho that's why i've made #25461, but seems few people care about db's stuff

@mbabker Why were you confused about this? Is it wrong?

2019-07-17 17:03 UTC, mbabker commented
No, just the closest icon to the look I had on my face in agreement about people not caring about things.

2019-07-17 20:31 UTC, rdeutz commented
Lets merge it and work from this point, with such a bit PR (change) we can discuss to the end of the world or later.

2019-07-17 20:36 UTC, brianteeman commented
@rdeutz that goes against everything you said when the private repo was created.

2019-07-17 20:40 UTC, richard67 commented
If you merge, please merge with 1 commit only. If you merge the complete commit history, our CI tests with be busy for the next 100 years ;-)

2019-07-17 20:43 UTC, rdeutz commented
> @rdeutz that goes against everything you said when the private repo was created.

no

2019-07-17 20:45 UTC, rdeutz commented
@richard67 we squash PR's usually

2019-07-17 20:51 UTC, brianteeman commented
> This work will at one point be made available to the public and also be open for criticism and after another (hopefully short) round of iterations, can be accepted into the Joomla project as the finished Joomla 4.0 backend template.

So you propose merging this template (that does not match the original design proposal) as is without comment or iteration :(

2019-07-17 20:58 UTC, coolcat-creations commented
It was available to the public for a long time now before the PR was created....?

2019-07-17 20:59 UTC, rdeutz commented
@brianteeman as long there is no more than border colors to discuss I am for merging it. And btw. this is now for months publicly available.

2019-07-17 21:01 UTC, Hackwar commented
> 
> 
> If you merge, please merge with 1 commit only. If you merge the complete commit history, our CI tests will be busy for the next 100 years ;-)

This would be exactly one build. The builds are not run for every single commit, but per push.

2019-07-17 21:07 UTC, richard67 commented
There are lots of review comments and they do not all deal only with code style. It is a bit work to click the "Load more ..." button so often and then go through all of it.

Especially the review comments from @C-Lodder were not dealing with border color stuff only.

None of these review was corrected or even answered here up to now.

2019-07-17 21:16 UTC, mbabker commented
> Lets merge it and work from this point, with such a bit PR (change) we can discuss to the end of the world or later.

Why bother with pull requests and community feedback and review if you're just going to shove something in?  You're basically saying everyone who has invested any time reviewing this pull request has wasted their time, in typical Joomla manner being disrespectful toward those who do put forth some effort to contribute to the project.

As for the commentary about "this has been public for some time", if you remember the repository started as private because quite frankly you did not want ongoing feedback and review from people qualified to do so.  And if it weren't for George acknowledging it in a PM to me the other evening, I honestly felt like I had wasted my time doing any testing and review of the template (and now this "rush it in" comment only seems to further validate feedback really isn't wanted here).

2019-07-17 21:25 UTC, rdeutz commented
@richard67 I see this from a practical point of view, we can now spend time on fixing merge conflicts or say comments are vaild lets work on smaller PR to sort things out.  

> if you remember the repository started as private because quite frankly you did not want ongoing feedback and review from people qualified to do so. 

No I don't remember because this was not the reason. What I wanted was a save evenvioment for a new team to work together and not to be in cross fire from people who are always in the frontline when it comes to share opinions in the most friendly way possible.

2019-07-17 21:30 UTC, mbabker commented
Translation, you didn't want Brian or myself touching the damn thing so you could work in an echo chamber without anyone challenging the work.  And yet, if you look at that repository or this pull request, we have two of the most consistently helpful sets of reviews.  You know I'm blunt, you don't have to pull any punches when it comes to communicating with me.  Just flat out say you didn't want us involved and for the first time all year I'll have finally heard a dead ass honest response from a leader in Joomla.

2019-07-17 21:33 UTC, richard67 commented
@rdeutz Then I was working in the wrong way all the time. I got used to the practice that we review a PR, test it when ready for test, and then merge it when all good. Now it seems to become different.

To be honest, I am not sure if anybody will check any old comment here when this PR is merged, and so the issues will come up slowly one by one. And we will make then 20 new small pr, need to review, test again, and so on, and maybe the one or other issue will be forgotten and not be handled.

I've heard we wanna go beta soon. If you have 20 or 30 additional testers then ok, let's go, let's merge this and proceed as desired.

Have you seen how few people we are here who are regularly testing?

Check the people's activity in the issue tracker menu.

I think it would save us time if the people from the template team go through the reviews here and fix them. And then we test this, and then it can be merged. But maybe I am just too old-fashioned.

2019-07-17 21:35 UTC, Hackwar commented
First of all thank you all for your comments. There are a lot of them valid and we will try to respond and fix as many as possible. I also want to thank people that you all stayed rather civil and I personally have expected a much worse discussion. ;-)

If you look higher up, a few of the review comments have already been fixed in the code. Please give us some more time to address more and to mark them in this thread accordingly. The people doing this currently have personal commitments, but will get back to this as soon as possible.

The backend template team has no interest in merging this prematurely.

2019-07-17 21:44 UTC, SharkyKZ commented
Unless there's intention to remove copy template function, template namespacing here is completely broken.

2019-07-17 21:46 UTC, brianteeman commented
@rdeutz @coolcat-creations I am well aware that the repository was open (if not publicised) as I created 83 bug reports, 16 pull requests and countless tests and code corrections and if you notice I am thanked in the initial post here.. But I guess that was while you were both absent from the repo. So before attacking people it would make sense to get your facts right. 

@Hackwar Thanks - we can always count on you for a sensible comment

@all If this proposal was what was actually proposed originally then there would be little need for comment and it could simply have been reviewed for code quality. Sadly thats not the case at all.

2019-07-17 21:49 UTC, brianteeman commented
Final comment - the objections of the accessibility team leader have also been ignored/rejected

2019-07-18 06:09 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_header.scss
> +      }
We still need to make a modif if we take away the term `Joomla!`
Without it we get in RTL:
<img width="130" alt="Screen Shot 2019-07-18 at 07 59 02" src="https://user-images.githubusercontent.com/869724/61432894-1eb2bd00-a932-11e9-8ece-e31629d05ec3.png">
This due to the use of latin characters in non stable version.
FYI, I have already corrected that everywhere where it was an issue in the existing template.

We can do
```
	public static function getVersion()
	{
		$version = new Version;

		return '&#x200E;' . $version->getShortVersion();   /// i.e. adding '&#x200E;'
	}
```
That will take care of it.
<img width="172" alt="Screen Shot 2019-07-18 at 08 08 39" src="https://user-images.githubusercontent.com/869724/61433317-49514580-a933-11e9-83e4-180fef79ff0a.png">

2019-07-18 06:53 UTC, marcodings commented
Not code related but not less heartfelt @bembelimen @coolcat-creations, @svom, @chmst , @Hackwar, @nadjak77, @fancyFranci, @lavipr, @rdeutz and @karo3 thank you very much for your great effort in making this happen

2019-07-18 11:52 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
>        display: flex;
`form-control-feedback` div moved to absolute positioning so this `display:flex` and related properties `align-items` & `justify-content` can be removed

2019-07-18 12:01 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +    align-self: flex-start;
On the containing div there are utility classes to center the login box vertically however here you override it. I suggest use one or the other. My preference would be center depending on screen size. The method here is a bit static.

2019-07-18 12:10 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +      display: flex;
I can't see any need to apply flex and related properties here.

2019-07-18 12:14 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
>    .login-bg-grad {
Considering you have removed the `login-bg-grad` div, this entire rule is no longer needed.

2019-07-18 12:17 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +    box-shadow: 0 0 10px 0 #ccc;
For the sake of consistency in box-shadows across the template, I would suggest creating and using a box-shadow variable. I presume one already exists somewhere.

2019-07-18 12:25 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +        &.text-right {
This class is not in the source of the login page. Possibly removed so therefore not needed here.

2019-07-18 12:27 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_login.scss
> +        &.text-right {
It's also a native Bootstrap class so no need to redefine anyway

2019-07-18 12:29 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_login.scss
> +        &.text-right {
It's also a Bootstrap class so assigning a colour and font-size is not good.

2019-07-18 12:32 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +    #btn-login-submit {
This styling is already defined by the `btn-primary` so no need to redefine here.

2019-07-18 12:33 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +    #form-login {
As a rule I would suggest not using IDs in CSS. Add a class if none already exists.

2019-07-18 12:36 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
>    .login-box {
This class appears to be no longer present in the markup.

2019-07-18 12:43 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +  color: var(--atum-text-light);
Already defined under `.view-login h1`

2019-07-18 12:43 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +  text-align: center;
Already defined under `.view-login h1`

2019-07-18 12:45 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +.com_login .sidebar-wrapper .main-brand h1,
Any particular reason for using com_login as a parent selector here and `view-login` elsewhere? If not I would suggest sticking with one.

2019-07-18 12:48 UTC, ciar4n commented on administrator/templates/atum/scss/blocks/_login.scss
> +        display:flex !important;
Apply `display:flex` to a `display:flex` utility classes? Something wrong here.

2019-07-18 12:56 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_form.scss
> +  .switcher__legend {
The switcher is a custom element. Shouldn't this be move to the CSS of the custom elements repo?

2019-07-18 13:06 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_header.scss
> +@import "../variables";
You shouldn't need to import this in ever single SCSS file.

2019-07-18 13:07 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_header.scss
> +    .d-flex:last-child {
Don't target Bootstrap utility classes like this. Use a custom class

2019-07-18 13:16 UTC, bembelimen commented on administrator/templates/atum/scss/_variables.scss
> +$color-0:                          adjust-color($color-60, $hue: -5%, $saturation: -100%, $lightness: +71.4%);
I added a comment at the top of it.
The naming structure is a bit inspired by the bootstrap gray gradients:
```
$gray-100: #f8f9fa !default;
$gray-200: #e9ecef !default;
$gray-300: #dee2e6 !default;
$gray-400: #ced4da !default;
$gray-500: #adb5bd !default;
$gray-600: #6c757d !default;
$gray-700: #495057 !default;
$gray-800: #343a40 !default;
$gray-900: #212529 !default;
```

2019-07-18 13:17 UTC, bembelimen commented on administrator/templates/atum/scss/vendor/_bootstrap.scss
> +@import "../../../../../media/vendor/bootstrap/scss/carousel";
This is more a "service" for the user. So one could e.g. use carousel in a backend module.

2019-07-18 13:26 UTC, C-Lodder commented on administrator/templates/atum/scss/_variables.scss
> +$color-0:                          adjust-color($color-60, $hue: -5%, $saturation: -100%, $lightness: +71.4%);
Yes, but `gray-xx` clearly means shade of grey.

`color-xx` means absolutely nothing, especially when the value is `adjust-color($color-60, $hue: -6%, $saturation: -85%, $lightness: +65.1%);`.

Nobody will understand this.

2019-07-18 13:28 UTC, C-Lodder commented
Not sure why the Hound bot isn't doing its job properly. Doesn't seem to be detecting any code style issues in the SCSS

2019-07-18 13:46 UTC, lavipr commented on administrator/templates/atum/scss/blocks/_global.scss
> +    fill: var(--atum-text-dark);
I had problems loading css variables in SVG, so I added this here in scss instead.

2019-07-18 13:51 UTC, bembelimen commented on administrator/templates/atum/scss/blocks/_global.scss
> +    fill: var(--atum-text-dark);
The idea behind this code is, that changing the template color also changes the icon color. But we're open for a better implementation.

2019-07-18 14:11 UTC, infograf768 commented
@bembelimen
Please modify administrator mod_version VersionHelper
Use
```
abstract class VersionHelper
{
	/**
	 * Get the Joomla version number.
	 *
	 * @return  string  String containing the current Joomla version.
	 */
	public static function getVersion()
	{
		$version = new Version;

		return '&#x200E;' . $version->getShortVersion();
	}
}
```
This will solve the redundant `Joomla!` as @mbabker remarked above and also RTL
We should get this in LTR and RTL
<img width="172" alt="Screen Shot 2019-07-18 at 08 08 39" src="https://user-images.githubusercontent.com/869724/61464484-9c002100-a976-11e9-8aac-3c24a7972d1d.png">

2019-07-18 14:17 UTC, mbabker commented
I won't claim to be an accessibility expert, so I may be talking out my backside here.  But, if omitting the word "Joomla" from that spot causes issues, it might be a good idea to add screenreader text (aria attribute or hidden span or whatever is the recommended way) on the Joomla icon so that it still gets read as "Joomla `<version>`" by assistive technologies.  If it's not needed, then everything's good, but figured I'd point out the potential issue now.

2019-07-18 14:33 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_global.scss
> +    fill: var(--atum-text-dark);
So what happens to clients who want to use their own SVG logo? This will affect them.
You'd be best off providing an inverted colour version of the Joomla logo.

2019-07-18 14:46 UTC, dgrammatiko commented
Fetching those 2 images on each window resize is probably dumb... Also because I'm totaly stupid, can somebody explain me the benefits of using AJAX for the login form? Lastly, did anyone actually reviewed that script from a security point of view?
<img width="1677" alt="Screenshot 2019-07-18 at 16 36 00" src="https://user-images.githubusercontent.com/3889375/61466524-55142a80-a97a-11e9-9d96-6155e9b2649f.png">

Why is there an embedded delay of 300ms on each page rendering? This is against common sense, people try to create fast responding UI's not delaying the loading of **every** page on purpose...
<img width="286" alt="Screenshot 2019-07-18 at 16 34 21" src="https://user-images.githubusercontent.com/3889375/61466732-b89e5800-a97a-11e9-94f9-530bcf199c9e.png">

2019-07-18 17:02 UTC, dgrammatiko commented
All right, one last comment here...

The performance of the new template is really disapointing:
<img width="1680" alt="Screenshot 2019-07-18 at 17 12 20" src="https://user-images.githubusercontent.com/3889375/61476627-cad5c180-a98d-11e9-993f-9de71a07269d.png">

Comparing to the current one:
<img width="1680" alt="Screenshot 2019-07-18 at 17 20 26" src="https://user-images.githubusercontent.com/3889375/61476700-ec36ad80-a98d-11e9-9ebf-ab62ea9139b4.png">

So I did some digging and found out that this:
<img width="1269" alt="Screenshot 2019-07-18 at 18 15 10" src="https://user-images.githubusercontent.com/3889375/61476740-fe185080-a98d-11e9-81b7-87eeb63fdc47.png">
is the bottleneck.

As a minimum action, this code (the helper + all the libraries) should be removed and reimplemented in a more static fashion (eg create the css vars as a static css file on style save or something similar).
@wilsonge this should be considered a **merge blocking** issue (IMHO)

2019-07-18 21:47 UTC, Hackwar commented on installation/template/index.php
> +						<img src="<?php echo $this->baseurl; ?>/template/images/logo-joomla-blue.svg" alt=""/>
Yes, not required, but also not forbidden. In case of doubt, I would err on the side of XML conformity.

2019-07-18 21:48 UTC, Hackwar commented on layouts/joomla/form/field/color/slider.php
> +		/>
As above: Yes, not required, but also not forbidden. In case of doubt, I would err on the side of XML conformity.

2019-07-18 21:48 UTC, Hackwar commented on layouts/joomla/form/field/color/slider.php
> +		/>
As above: Yes, not required, but also not forbidden. In case of doubt, I would err on the side of XML conformity.

2019-07-18 21:48 UTC, Hackwar commented on layouts/joomla/form/field/color/slider.php
> +		/>
As above: Yes, not required, but also not forbidden. In case of doubt, I would err on the side of XML conformity.

2019-07-18 21:48 UTC, Hackwar commented on layouts/joomla/form/field/color/slider.php
> +		/>
As above: Yes, not required, but also not forbidden. In case of doubt, I would err on the side of XML conformity.

2019-07-18 21:48 UTC, Hackwar commented on layouts/joomla/form/field/color/slider.php
> +	/>
As above: Yes, not required, but also not forbidden. In case of doubt, I would err on the side of XML conformity.

2019-07-18 21:48 UTC, Hackwar commented on layouts/joomla/form/field/color/slider.php
> +	/>
As above: Yes, not required, but also not forbidden. In case of doubt, I would err on the side of XML conformity.

2019-07-18 21:56 UTC, Hackwar commented on administrator/components/com_menus/tmpl/items/default.php
> +				<?php if (!empty($this->items)) : ?>
There is a feature in the searchtools layout that adds this in automatically. That feature is apparently around 3 years old. @bembelimen thought this was a new feature and was supposed to be added, but we both currently don't really know what we want to see there. What is the oppinion of the others here about this?

2019-07-19 06:15 UTC, infograf768 commented
@bembelimen
Keeping `$version::PRODUCT` does not solve the issue in RTL by just adding the indicator....
It gives
<img width="173" alt="Screen Shot 2019-07-19 at 08 04 56" src="https://user-images.githubusercontent.com/869724/61513008-f8595400-a9fb-11e9-8072-0ec50421dca0.png">

If you absolutely want to keep the term Joomla! then, as I have explained in details above (so far above I can't find it anymore), you need to modify the _header.scss

```
      .joomlaversion {
        min-width: 6.6rem;
      }
```
to
```
      .joomlaversion {
        min-width: 6.6rem;
        direction: ltr;
      }
```
One will get:
<img width="182" alt="Screen Shot 2019-07-19 at 08 08 59" src="https://user-images.githubusercontent.com/869724/61513321-08bdfe80-a9fd-11e9-8748-7292bdfd6917.png">

Evidently, no use to modify anymore the VersionHelper when the css is corrected.

2019-07-19 06:29 UTC, bembelimen commented
@dgrammatiko could you please verify that you NOT had throttling activated for the new backend template and NO throttling for the old one?

2019-07-19 06:46 UTC, C-Lodder commented
@bembelimen I assume it was on a simulated 3G connection which is what we do all of our performance tests on

2019-07-19 06:52 UTC, bembelimen commented
> @bembelimen I assume it was on a simulated 3G connection which is what we do all of our performance tests on.
> 
> That is what you should be aiming for

Yes, ofc, but my suspicion is: one test was made with throttling on the other with throttling off...

2019-07-19 07:23 UTC, C-Lodder commented
@bembelimen I doubt it. The first thing i did when viewing the new template was to run a performance test compared to the current template. Results are pretty much the same....give or take 1-2%

2019-07-19 07:25 UTC, SharkyKZ commented
Why is FontAwesome and Bootstrap included in template.css?

2019-07-19 07:28 UTC, SharkyKZ commented
Copied template is broken:

![Screen Shot 2019-07-19 at 10 27 26](https://user-images.githubusercontent.com/7325021/61517444-f0a3aa80-aa0f-11e9-831c-73623a48d704.png)

2019-07-19 08:02 UTC, nadjak77 commented on administrator/templates/atum/scss/_variables.scss
> +$color-0:                          adjust-color($color-60, $hue: -5%, $saturation: -100%, $lightness: +71.4%);
The calculation for the colors is based on https://codepen.io/jonrohan/pen/NNGaBO.
The calculation is done here : https://www.colorbox.io/#steps=10#hue_start=201#hue_end=216#hue_curve=easeInQuad#sat_start=0#sat_end=90#sat_curve=easeOutQuad#sat_rate=130#lum_start=98#lum_end=4#lum_curve=easeOutQuad#lock_hex=#1a466b#minor_steps_map=5
Perhaps the basecolor changed a litte bit, so it can be, that this values do not correspond to the template colors. But the caculation is based on this.

2019-07-19 08:16 UTC, dgrammatiko commented
@bembelimen it's a standard process on chrome/edge(beta) without me playing around with the settings. Also, I suspect I'm one of the lucky ones to have the lastest and greatest Mackbook Pro. So...

Anyways, please undo the animation part for the wrapper, etc and roll back this colour helper with all the external libraries introduced as a minimum to bring back the performance to acceptable levels

2019-07-19 14:54 UTC, Hackwar commented
> 
> 
> All right, one last comment here...
> 
> The performance of the new template is really disapointing:
> 
> Comparing to the current one:

I can not replicate this. I've now run ~30 of these audit runs (to prevent any issues with load on my machine, etc.), 10 on the current 4.0-dev template, 10 on this PR, 10 on this PR with the helpers commented. I checked this on the home dashboard on new, clean installations.

The results were always the same: There is a slight difference (nearly in the range of measuring error) between the old and the new template, but none when commenting those helper files (and thus disabling the animation) and leaving them in.

In my tests right now, this template performs better than what we currently have in 4.0-dev. This is not a merge blocker. You maybe should check your tests again.

2019-07-19 14:59 UTC, dgrammatiko commented
> You maybe should check your tests again.

Sure, just make sure you use Simulated Fast 3G, 4x CPU Slowdown and most importantly **enable** Clear Storage. It goes without saying that in the Network tab you have checked the Disable caching...

2019-07-19 15:01 UTC, Hackwar commented
> 
> 
> > You maybe should check your tests again.
> 
> Sure, just make sure you use Simulated Fast 3G, 4x CPU Slowdown and most importantly **enable** Clear Storage. It goes without saying that in the Network tab you have checked the Disable caching...

Yes, I did.

2019-07-19 15:03 UTC, Hackwar commented
I mean, do you think I can't see the difference between the template having animations during the tests and **not** having animations?

2019-07-19 15:09 UTC, dgrammatiko commented
@bembelimen @Hackwar @wilsonge you know what? Just ignore me and **ship it!**

2019-07-19 15:11 UTC, mbabker commented
I'm with @dgrammatiko on this one as far as the performance goes.  Not as bad as his report, but it's still a pretty low score.  Main dashboard after logging in, pretty consistent across 5 runs.  This is on my Late 2014 Mac Mini.

![Screen Shot 2019-07-19 at 10 09 48 AM](https://user-images.githubusercontent.com/368545/61545584-665a4700-aa0d-11e9-9250-15fb2c4ef4cc.png)

2019-07-19 15:13 UTC, dgrammatiko commented
@mbabker but I was testing on article edit and also you have to make sure that all caching serverside (opcode or whatever) and clientside (browser) is disabled. I get consistently 2x slower responses

2019-07-19 15:14 UTC, mbabker commented
I noticed after the fact.  Just ran 3 runs on that screen, consistently close to this.

![Screen Shot 2019-07-19 at 10 13 50 AM](https://user-images.githubusercontent.com/368545/61545826-f7312280-aa0d-11e9-88f7-82c52e463cc3.png)

2019-07-19 15:15 UTC, Hackwar commented
@mbabker The question is, if this is related to the helpers and animation, as @dgrammatiko claims and I can't replicate that. There is **no** difference at all with and without the animations (and the helpers).

Also please be aware that the default dashboard has different loads in 4.0-dev and this PR.

2019-07-19 15:17 UTC, mbabker commented
I'm not doing a comparison between current branch and this pull request, I'm strictly running this pull request.  The point here though is there is a performance concern based on these benchmarks.  I don't have the time to do any other experiments, but I can confirm @dgrammatiko results on my system.

2019-07-19 15:19 UTC, dgrammatiko commented
@mbabker can you please mute the 2 lines in the index.php for the color helper and rerun the tests?

2019-07-19 15:23 UTC, mbabker commented
No change basically (I really do need to be going now, the unit test run I was waiting on finished up so back to work I go).

2019-07-19 15:26 UTC, bembelimen commented
> 
> 
> I'm not doing a comparison between current branch and this pull request, I'm strictly running this pull request. The point here though is there is a performance concern based on these benchmarks. I don't have the time to do any other experiments, but I can confirm @dgrammatiko results on my system.

Hello @mbabker thanks for looking into this PR. Just two comment why I think your "tests" are not valid.
First, as @Hackwar mentioned, the discussion is not about if the edit screen is slow but if the slowness is caused by this helper file (and as we have no 3 proves: no it's not => so @dgrammatiko tests are wrong).

The second question is now: is the edit screen slower than before?
And comparing the old template (in current 4.0-dev) and the one from this PR I also can say: no difference. On both templates the edit screens are slow.

So my conclusion is: the new template is not significant slower than the old one....but the edit screen should perhaps be tackled in another PR (independend from the template).

2019-07-19 15:30 UTC, mbabker commented
If you're saying that https://github.com/joomla/joomla-cms/pull/25570#issuecomment-512902578 is not accurate, then sure, you can go with the "this iteration of the template is not faster nor slower than what is presently in the 4.0 branch" argument.  Otherwise, if a major performance regression can be proven, that needs to be addressed before this is merged.  If you're looking strictly at your network waterfall and the response times there, then you may be right there is minimal difference, but additional benchmarking tools need to be used beyond that one (there are at least 3 at your disposal; the core debug plugin to benchmark PHP performance, the network tab on your browser to benchmark number of requests and response times, and the Lighthouse tools in Chrome).  Either way, a 3 score is flat out garbage.

2019-07-19 15:35 UTC, mbabker commented
> so @dgrammatiko tests are wrong

Just so everyone is on the same page, what is considered a "right" test in your book?  Considering I've done nothing more than boot my AMP stack to PHP 7.2, log into a Joomla installation with this pull request applied, navigate to the article edit page, and run the Lighthouse tool, that should represent a "right" test.

2019-07-19 15:40 UTC, bembelimen commented
Sorry @mbabker do you really want to talk on this level? As stated above: I agree with: "the edit screen is slow", no questions here, this should be fixed, but not in this template PR, because the problem is not releated to the template, as assumed. So commenting out the helper file does NOT solve the slow edit screen, so the tests which "proves" that everything is the helpers files fault is wrong.

2019-07-19 15:44 UTC, mbabker commented
Last comment then I'm unsubscribing since it now seems you want to go out of your way to discredit myself and @dgrammatiko.

As I said, I did not do any major experiments with disabling features added to the template.  I simply ran the Lighthouse test and validated @dgrammatiko results in that the performance is below acceptable, a test report which it seems people want to write off as invalid.  I do not know if this is a regression from the current version of the template, and unless someone is going to pay my company's hourly fee for consulting services I am not doing any more testing of this template thanks to the attitude in this pull request.  I tried to do the one thing nobody would when I wanted to get 3.9 released, test the major feature, and you all want to basically say "thanks but you're wrong".  So, yeah, I'm done here.

2019-07-19 17:44 UTC, Bakual commented
Regardless if there is a measurable performance penalty or not, it would make sense to look into creating a static templatestyle specific CSS file during templatestyle save and load that during pageload.
I do that already in J3 for my own template (using a system plugin on the onExtensionAfterSave event). I think it should be reasonably simple to add that technic to core.

2019-07-19 18:25 UTC, brianteeman commented
1. I have been unable to replicate the test findings. Perhaps some difference in the LAMP stack - I dont know but there is clearly something causing those test findings. The only other explanation is that the images are fake and obviously thats not the case.
2. The color functionality really doesnt work well. I have already commented several times that the monochrome option does **not** make it monochrome but I now see that other settings such as hue do **not** truly apply a hue to the site.

2019-07-19 19:00 UTC, ciar4n commented
Maybe I am missing something here but if the color helper only deals with hue and monochrome, would this not be best done with brightness() and saturation() CSS functions?

https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/brightness
https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/saturate

2019-07-22 08:17 UTC, C-Lodder commented
Thought I'd share my research on this too.

- Windows 10
- Chrome 75.0.3770.142 (Incognito mode and no 3rd party extensions)
- Wampserver

## Dashboard
![dashboard-2](https://user-images.githubusercontent.com/2019801/61615721-a9f7bf80-ac5e-11e9-9b78-ca39475503cc.png)

## List view
![list-view](https://user-images.githubusercontent.com/2019801/61615484-073f4100-ac5e-11e9-9595-d8a5ff1518c1.png)

## Edit view
![edit-view](https://user-images.githubusercontent.com/2019801/61615486-09a19b00-ac5e-11e9-9adf-cec74374c79b.png)

In my opinion, none of these are acceptable.

Just by moving 2 single lines:
```
<jdoc:include type="styles" />
<jdoc:include type="scripts" />
```
to just before the closing `</body>` tag, I was getting **80**.

Things I'd suggest to be changed:

1. Move CSS/JS to before the closing body tag or truely async load it (by this I do not mean add the `async` attribute)
2. Use SVG's for icons as opposed to Font Awesome
3. Remove the poorly performing code that changes the opacity pretty much all nodes on the page (here: https://github.com/joomla/joomla-cms/pull/25570/files#diff-8fcf842cab1f27e713458dd9d3890954R67 and here: https://github.com/joomla/joomla-cms/pull/25570/files#diff-1cc50e9b809f51e446bac57823e7b08cR42)
4. I commented above about importing SCSS files for the sake of it and the reply was `This is more a "service" for the user. So one could e.g. use carousel in a backend module.`. If this is the case, it should be split into separate CSS files and developers can use `JHtml` which will load the necessary files. The killer for unused CSS in Bootstrap is the utility classes (about 5k lines of CSS). I would seriously suggest looking into this.

2019-07-22 08:30 UTC, brianteeman commented
@C-Lodder what score do you get on the current template in the edit view

2019-07-22 08:50 UTC, C-Lodder commented
@brianteeman 

- Dashboard: 72%
- List view: 54%
- Edit view: 16%
  - Edit view (codemirror): 35%
  - Edit view (no editor): 54%

2019-07-22 08:58 UTC, Fedik commented
> If this is the case, it should be split into separate CSS files and developers can use JHtml which will load the necessary files.

Just for note. How it can be done.
The asset manager allow to organise the CSS with dependencies, so it could be a help,
A big css can be split to chunks:
```json
...
"assets": [
    {
      "name": "bootstrap.css.base",
      "css": ["media/vendor/bootstrap/css/bootstrap.base.css"]
    },
    {
      "name": "bootstrap.css.carousel",
      "dependencies": ["bootstrap.css.base"],
      "css": ["media/vendor/bootstrap/css/bootstrap.carousel.css"]
    },
    {
      "name": "bootstrap.css.foobar",
      "dependencies": ["bootstrap.css.base"],
      "css": ["media/vendor/bootstrap/css/bootstrap.foobar.css"]
    },
]
...
```

Then when extension enable "bootstrap.css.carousel", it will be loaded correctly after "bootstrap.css.base"

Also I think, Performance problem can be moved to another issue, because it not a simple task, to fix in one run.

2019-07-22 10:19 UTC, bembelimen commented on build/media_source/templates/atum/js/template.es6.js
> +      contentChildren[i].classList.add(`load-fade${fadeAction}`);
The number of child nodes is 2, so I guess it's OK. At the end of the day, only 3 elements will be faded (content area, sidebar area and the floating alert box, if available)
If we apply it to the parent elements, then the structure (colors) will not be visible.

2019-07-22 10:30 UTC, bembelimen commented
@C-Lodder I like the idea of the splitted CSS. Would you support us in creating this strucutre?

2019-07-22 10:39 UTC, C-Lodder commented
@bembelimen I'll submit a some commits today if I have time

2019-07-22 10:48 UTC, bembelimen commented
> 
> 
> @bembelimen I'll submit a some commits today if I have time

Thank you very much!


> Just by moving 2 single lines:
> 
> ```
> <jdoc:include type="styles" />
> <jdoc:include type="scripts" />
> ```
> 
> to just before the closing `</body>` tag, I was getting **80**.
> 
> Things I'd suggest to be changed:
> 
>     1. Move CSS/JS to before the closing body tag or truely async load it (by this I do not mean add the `async` attribute)

I moved the scripts to the bottom. I'm honestly not sure about the styles. Because then the DOM will be generated without styling and we have "jumpings" on the page. Perhaps your solution with splitting the CSS could lead to this change, so a base CSS is ("hardcoded") in the head and all the other stuff is in the footer.

2019-07-22 10:48 UTC, brianteeman commented
This isnt going to work as any inline scripts or scripts added to the head will fail if they are dependent on any of the scripts now loaded at the bottom

2019-07-22 10:51 UTC, C-Lodder commented
@brianteeman If they use `addScriptDeclaration()` it will work just fine. It's only an issue if they use their own `<script>` tags

2019-07-22 10:53 UTC, brianteeman commented
thats what I meant just expressed badly

2019-07-22 10:58 UTC, brianteeman commented
and even with this change all the JS for the custom elements etc are still loaded in the head

![image](https://user-images.githubusercontent.com/1296369/61627573-0c10ee80-ac78-11e9-9768-f3ba6e1f55a7.png)

2019-07-22 11:34 UTC, dgrammatiko commented
@brianteeman sorry you’re wrong about the custom elements, these are the only scripts that are lazily loaded (if you check the page source you’ll see that those scripts do not exist in the server response, they are populated by JavaScript, also called progressive enhancement)

2019-07-22 11:40 UTC, brianteeman commented
ok thats good to know

2019-07-22 12:32 UTC, micker commented
hello i check 75d4e11 but seems doesn't work

2019-07-22 13:04 UTC, bembelimen commented
@dgrammatiko and @mbabker one thing I want to clearify (which seems to be missunderstood, because of my bad English or because I hadn't enough time to formulate it clearly): I didn't want to discredit you or your tests, they are absolute valid and have to be tackled. What I wanted to say is, that the helper (in my opinion) isn't the cause of the slowness but the system itself.
So I'm very sorry if you felt offended or insulted by me, that was not my intention.

2019-07-22 13:32 UTC, brianteeman commented
@bembelimen as the monochrome option doesnt work (as previously explained) and the HLS option does not work everywhere that it should maybe just drop it.

2019-07-22 21:47 UTC, bembelimen commented
@brianteeman the color selector concept is similar to the one in the J! 3 backend template. You can colors for specific areas and they will change, but not all areas. Important things like some buttons etc. will not change.

Could you show me an example where the Hue value fails please? Thx.

2019-07-22 21:49 UTC, bembelimen commented
@micker thanks for your tests.

> hello i check [75d4e11](https://github.com/joomla/joomla-cms/commit/75d4e1118a871c912d770b756a419ce496fbd573) but seems doesn't work

Could you elaborate a bit more, what you tests, what's the result and what's the expected result? Thx.

2019-07-22 21:56 UTC, brianteeman commented
The individual colour options are fine - its the hue and monochrome that dont work.

### HUE test
![image](https://user-images.githubusercontent.com/1296369/61667996-62f7e180-acd3-11e9-9231-de60ddd7e4b9.png)
![image](https://user-images.githubusercontent.com/1296369/61668058-9b97bb00-acd3-11e9-8ab9-09847ceb8f2a.png)

![image](https://user-images.githubusercontent.com/1296369/61668149-cb46c300-acd3-11e9-85c1-d3153d90acb2.png)
![image](https://user-images.githubusercontent.com/1296369/61668190-eb768200-acd3-11e9-8da6-ac9be2fd1da6.png)

### Monochrome test

2019-07-22 21:58 UTC, brianteeman commented
@bembelimen and see this issue for more information about the monochrome option https://github.com/joomla/backend-template/issues/348

2019-07-23 06:33 UTC, micker commented
@bembelimen sorry its about save principal color after save color return to 207 all the time

2019-07-23 07:36 UTC, ciar4n commented
Applying `filter:grayscale(1);` to the body tag will convert everything to monochrome.

2019-07-23 10:31 UTC, bembelimen commented
@micker this [should be already fixed](https://github.com/joomla/joomla-cms/pull/25570/commits/6038e7914997b9df8b5a4a7b85dcbe5b3e12e22d).

2019-07-23 10:39 UTC, micker commented
i add last patch via patch tester i didn't see any change maybe i do a mistake

2019-07-23 21:34 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
>  				class="custom-select-color"
```suggestion
					class="custom-select-color"
```

2019-07-23 21:36 UTC, richard67 commented
@micker Patchtester is not enough, since this PR also contains SQL update scripts. And running the database fixer will also not help because the SQL is DML (data manipulation language), which is not handled by the database fixer. What you should do is

1. Pull latest changes from 4.0-dev.
2. Run `composer install` to fetch external PHP stuff.
3. Run `npm install` to fetch external js stuff and build and copy js and css.
4. Apply patch e.g. with patchtester.
5. Run the SQL schema update scripts `4.0.0-2019-05-05.sql` and `4.0.0-2019-07-13.sql` added by this PR in exactly the mentioned order (old before young). Depending on your database type use the script from the right folder.
5. Run again `npm install` to build and copy js and css changed by this PR.

This requires of course composer and npm. For setting up a testing environment see [https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment/en](https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment/en). That document is also available in other languages, at least partly translated.

@bembelimen I hope I explained everything right.

2019-07-23 21:36 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
>  				class="custom-select-color"
```suggestion
					class="custom-select-color"
```

2019-07-23 21:36 UTC, brianteeman commented on administrator/components/com_contact/forms/contact.xml
>  				class="custom-select-color"
```suggestion
				class="custom-select-color"
```
```suggestion
					class="custom-select-color"
```

2019-07-23 23:10 UTC, astridx commented
@micker Or you can use a nightly build. See test instructions. @richard67 Please correct me if this is not correct.

2019-07-24 05:23 UTC, richard67 commented
@astridx well it needs a development environment as far as I know to run ‘npm install’. And it needs to run the Schema update sql scripts in SQL. I’ve reduced my testing instructions to a link to the doc for J4. Later me or someone else can provide instructions for the rest. It needs 2 test scenarios: 1. New install of the CM/S including the new template stuff, and 2. Update CMS with running, the Schema update SQL. Will be long testing instructions if described with every step.

2019-07-24 05:27 UTC, richard67 commented
@astridx I just see you meant nightly build of the template’s repo.  No idea if this is up to date with latest changes in 4.0-dev.

2019-07-24 08:55 UTC, Hackwar commented
Regarding the monochrome/hue feature:
Yes, the feature is supposed to color (almost) everything in the given colors. There are however certain exceptions, like signal colors for important messages or for buttons with irreversible actions. That is why some buttons are not also monochrome, like the delete button in your screenshot or the messages. It would be pretty strange if a success message had a red color, just because the current color scheme is red. So keeping certain colors in certain areas is a conscious decision and right now the feature works as it is supposed to.

2019-07-24 09:00 UTC, brianteeman commented
> So keeping certain colors in certain areas is a conscious decision and right now the feature works as it is supposed to.

Then sorry to say but it is wrong.

2019-07-24 09:33 UTC, ciar4n commented
The monochrome feature seems completely over-engineered considering it can be implemented with a single CSS property. A CSS approach would convert everything to monochrome. It would also allow you to re-define some of the color variables to better contrasting monochrome shades. The current red and green in monochome are indistinguishable from each other.

2019-07-24 09:40 UTC, brianteeman commented
it is over-engineered because _mistakenly_ they don't want to apply it everywhere

2019-07-24 10:59 UTC, ghazal commented
@micker 
I made a tut in french on how to test J4 and its dependencies
https://github.com/ghazal/tester-joomla-4

2019-07-25 06:24 UTC, brianteeman commented
As it seems I need to provide more reasons why changing the hue of the template or making it monochrome should apply globally and not keep red/green buttons try this.

Filters clarify the digital world for the colorblind - https://community.windows.com/en-us/stories/color-filter

**If the use case for these features is to improve accessibility then it fails**

2019-07-25 06:59 UTC, chmst commented
I agree  with you for red/green buttons, but we have made every effort to make sure, that every information is visible indpendent from colours. If you find an element which has information only with colours and has no text and/or icon, please let us know.

2019-07-25 10:31 UTC, micker commented
@bembelimen  for color save is fixed #25570
size of login logo not
![image](https://user-images.githubusercontent.com/2539440/61867504-aa4ebf80-aed7-11e9-9765-0bca27e38de0.png)
width of dashboard module not (set size 12 for icon button, no effect)
small  behavior in dropdown button in chrome
![2019-07-25_12h29_55](https://user-images.githubusercontent.com/2539440/61867657-fb5eb380-aed7-11e9-8b35-cdd61c95698f.png)
thanks your works

2019-07-25 11:45 UTC, micker commented
just a question to understand some choice ... why did we have full with input its realy strange for eyes ...
for exemple in media manager the deplacement for understand value is realy long
![image](https://user-images.githubusercontent.com/2539440/61871975-76c56280-aee2-11e9-83fc-6dc3b47b3c58.png)

![image](https://user-images.githubusercontent.com/2539440/61871960-6f05be00-aee2-11e9-819a-55b3ac923b5b.png)
its for acessibility ?

2019-07-25 11:52 UTC, brianteeman commented
It is terrible for accessibility especially if you have reduced motion or are using a screen magnifier

2019-07-25 11:58 UTC, C-Lodder commented
@micker @brianteeman Cause of this: https://github.com/joomla/joomla-cms/pull/25570/files#diff-4fb62b8a0eddc5883b2258f9cc6fbf1dL68

2019-07-25 12:30 UTC, micker commented
@brianteeman @C-Lodder sorry i am not sure to understand that necessay or need find an other way ?
because if we need to reduce motion need to reduce size ..

2019-07-25 12:46 UTC, C-Lodder commented
@micker 

> administrator/templates/atum/scss/_variables.scss (line 68)

```
$input-max-width: 240px;
```

was replaced with:

```
$input-max-width: 100%;
```

The 100% is causing the problem with the long input widths. It was set to `240px` for this specific reason :)

2019-07-25 12:54 UTC, bembelimen commented
> **If the use case for these features is to improve accessibility then it fails**

It's not, it's just to color different area. But probably we should convert the monochrome option to a A11y feature. So having it off => just color different aspects, switching it on => do the full page in monochrome.
Is setting this CSS filter enough to fullfill the monochrome A11y requirements?

2019-07-25 12:59 UTC, bembelimen commented
> 
> 
> @bembelimen for color save is fixed #25570
> size of login logo not

Yep logo is not solved yet, but we have it on the list.

Thanks for reporting.

2019-07-25 18:55 UTC, brianteeman commented
grrh. computer crashed in the heat right in the middle of a long reply. Not going to type it again. Summary was.
Just drop the library and go with @ciar4n suggestion. It is the correct way to do it. it gives the user the expected experience. it doesnt introduce a11y issues and its more performant

2019-07-26 17:21 UTC, chmst commented on administrator/components/com_cache/Controller/DisplayController.php
> +	public function getQuickiconContent()
https://github.com/joomla/backend-template/pull/400

2019-07-27 07:48 UTC, brianteeman commented
Thanks for making the monochrome change
We still have the same situation with the HUE settings not being applied to everything. It should be applied globally just like monochrome.

2019-07-27 08:15 UTC, brianteeman commented
The changes https://github.com/joomla/joomla-cms/pull/25708 are creating conflicts here. The changes here should have been made in the layout and not in the template files as previously commented

2019-07-27 11:32 UTC, bembelimen commented
> Thanks for making the monochrome change
> We still have the same situation with the HUE settings not being applied to everything. It should be applied globally just like monochrome.

No, we don't have. Hue is not for changing every aspect of the page but just explicit ones.

2019-07-27 12:04 UTC, brianteeman commented
Explicit as per the code but NOT explicit as for the UI.

2019-07-29 17:13 UTC, wilsonge commented
So the colour options here are supposed to theme the backend template rather than provide an accessibility hue option for the site - so the backend matches the branding of companies. So probably what we need here is to rename the tab to theme settings (or similar). if we additionally want to add hue options for individual users for a11y per the a11y plugin @brianteeman has suggested we can then do that.

2019-07-29 17:23 UTC, brianteeman commented
@wilsonge The hue option is still wrong. Even with your comment that its to match the branding of a company.
1. As already stated by others it applies to the logo if that is svg
2. It is not applied consistently to UI elements eg
Help button - hue applied
Save buttons - hue not applied
etc
I would expect it to be at least consistent
![image](https://user-images.githubusercontent.com/1296369/62068370-c6cb5e80-b22d-11e9-8908-64cbfdf51862.png)
![image](https://user-images.githubusercontent.com/1296369/62068418-de0a4c00-b22d-11e9-9d56-ca82079243c5.png)
![image](https://user-images.githubusercontent.com/1296369/62068438-ebbfd180-b22d-11e9-8c2f-7890723548c3.png)

2019-07-29 17:42 UTC, wilsonge commented
OK logo i agree it's a simple fix. 

Buttons in the toolbar I can see your point but seems more complicated. How do we expect these to act. Because the buttons aren't all a uniform colour. And I don't think we can have a dozen colour inputs to determine the style of each one. Having colour options for our templates existed in J3 and I think the same issue exists there? https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/templateDetails.xml#L50-L98 (or at least something quite similar) and this to me is an improvement because we get a11y optimised schemes (usually using the library) for the template rather than people manually selected each section to be give or take the same colour.

2019-07-29 17:45 UTC, brianteeman commented
> Having colour options for our templates existed in J3 and I think the same issue exists there?

No because they 
1. Only apply to elements that have colour for decorative purposes
2. Are specific colours not a global hue. Much easier to match your brand that way ;)

2019-07-29 17:46 UTC, brianteeman commented
At the end of the day - the HUE stuff is the least of the issues with the template style

2019-07-29 18:13 UTC, wilsonge commented
> At the end of the day - the HUE stuff is the least of the issues with the template style

OK So what issues are left here - as I see it there:
1. The quickicon issues have largely been addressed - there's some arguments over whether there should be so many - but the numbers have been removed largely and the mobile fixes are nearly finished (and I believe will be fixed soon)
2. There's some arguments over whether the performance should be fixed too now or whether it's something that can be left until later (fwiw whether i disabled the lines @dgrammatiko mentioned i got 0 differences on my lighthouse report although the performance was bad before and after - but according to lighthouse was dominated by the time of the CSS to load)

I can't see anything else that's been mentioned here that hasn't been addressed and is a serious blocker to merge at this point (i think even the majority of the comments that people have deleted in the post have been addressed at this point)

2019-07-29 18:15 UTC, richard67 commented
@wilsonge It would need some test for updating the CMS to see if the schema updates work, but that could also be done later after merge ... I have the feeling anyway that we need to clean up the schema updates a bit before going beta.

2019-07-29 18:16 UTC, richard67 commented
If someone would fix the 1 conflicting file we would have a new nightly buld of the template repo tomorrow and could test installing and updating the CMS on MySQL and PostgreSQL to see if all SQL is ok.

2019-07-29 19:26 UTC, dgrammatiko commented
@wilsonge since you've mentioned me a couple of things here:
- The test I conducted gave me the impression that the colour thingy was the bottleneck (since the only thing was added in the iterated template was the colour thingy I wrongly pointed to that).
- That doesn't mean that as a developer I'm not irritated by seeing this solution as the one that was acceptable. 
- How about doing the **whole** bloody work on the client-side and save the values in the template params? That way you have 0, yes **0** performance penalty and still have the functionality you wanted. Eg https://github.com/bgrins/TinyColor has all the function people used in PHP with exactly the same names, who would have thought that...

@bembelimen apparently, I still didn't get an answer for my 2 other questions:
- What problem are you solving with the ajax login?
- On what facts/metrics/articles/books did you based the 300ms delay on the main content (I mean the useless fade-in animation)?

2019-07-29 19:26 UTC, brianteeman commented
- [ ] What is $color-xx? - https://github.com/joomla/joomla-cms/pull/25570#discussion_r303428104
- [ ] Remode the sidebar - https://github.com/joomla/joomla-cms/pull/25570#discussion_r303484460
- [ ] Help links - https://github.com/joomla/backend-template/issues/259
- [ ] Help links - https://github.com/joomla/joomla-cms/issues/21990
- [ ] Empty lists - https://github.com/joomla/joomla-cms/pull/25570#discussion_r303493650
- [ ] Add module client - https://github.com/joomla/joomla-cms/pull/25570#issuecomment-511457848
- [ ] Filter navigation - https://github.com/joomla/backend-template/issues/310
- [ ] codestyle - https://github.com/joomla/joomla-cms/pull/25570#discussion_r303526500
- [ ] codestyle - https://github.com/joomla/joomla-cms/pull/25570#discussion_r303526642
- [ ] codestyle - https://github.com/joomla/joomla-cms/pull/25570#discussion_r303529277
- [ ] quickicon module size https://github.com/joomla/joomla-cms/pull/25570#issuecomment-511698133
- [ ] row borders https://github.com/joomla/joomla-cms/pull/25570#issuecomment-512339231
- [ ] login css review https://github.com/joomla/joomla-cms/pull/25570#discussion_r304874131
- [ ] import scss https://github.com/joomla/joomla-cms/pull/25570#discussion_r304905660
- [ ] joomla version https://github.com/joomla/joomla-cms/pull/25570#issuecomment-512832722
- [ ] full width fields https://github.com/joomla/joomla-cms/pull/25570#issuecomment-515011922
- [ ] quick icon a11y https://github.com/joomla/backend-template/issues/115

2019-07-30 11:12 UTC, brianteeman commented
I remember discussing this in the template repo but can't find the link now.

When you add a module to any admin dashboard by clicking in the  add dashboard module area the newly added module is **not** displayed until you have refreshed the page. It should be displayed as soon as the user saves the new module

2019-07-30 11:20 UTC, dgrammatiko commented
@brianteeman that's an easy fix: trigger a page reload on the modal close. What is interesting though is that people treat Joomla as a Single Page Application (or as a client-side app). It's not (except the media manager and that without the edit page). Thus the animation part on the main content is wrong: **you're not replacing parts of a page, you are always loading again the whole page**

2019-07-31 12:38 UTC, Magnytu2 commented
Hello everyone, I am writing to you here because I am angry and I am not proud of Joomla! 

First of all, who I am. I'm not a professional. I use Joomla! out of love for this CMS, out of conviction. I have about ten sites that I have created and that I manage free of charge for friends or associations. I do this out of pleasure, out of a desire to use Joomla! And today it's no longer the case.

You present us these last few days a third template of the Joomla administrator! 4. To my God it's ugly! I understand that it is to make Joomla! compatible with standards. I understand that Joomla! is aimed at professionals. But now I say stop. Joomla! 4 makes me nauseous running around, clicking and clicking. The colours are unbearable. We are attacked, even violated by the disproportion of the buttons.

You are apparently taking the direction of a professional use, or even integrator or developer. If this were the case, you would have started by integrating a backup system, a use or even a configuration of the SEO. You would have long ago set up a complete media manager, with the creation of views of different image sizes for articles, with the creation of image names in relation to the title of the article. You would have integrated a basic social network management system. Without social networks, there is no visible site. You would have allowed multi-category for articles. You would have set up an article template manager based on categories. 

You have chosen a direction to attract professionals. But if Wordpress occupies 30% of the net, it is precisely because it is used by professionals. The trend is towards soft, slightly round templates with coloured tips, and a dark mode. Look at Joomlart's new T4. Look around you. There will be no success if the product is not attractive. It can have all the functions of the world. Aesthetics, pleasure and essential on the rest. With this template we have the impression to go back in 2012 with the first version of Windows 8.

I sound an alarm bell here, a cry from the heart, because I am sad to see my CMS become a soulless and heartless gas plant.

2019-07-31 15:03 UTC, chmst commented
@Magnytu2 I think this is the wrong place for your complait. This PR is about forms and colours of the template, nothing else.

2019-07-31 15:16 UTC, Magnytu2 commented
Hello then, I suspected a little, but where can I scream my pain so that it affects the makers of Joomla?

2019-07-31 16:23 UTC, C-Lodder commented
Twitter seems to be a good place these days

2019-07-31 16:38 UTC, mbabker commented
> Twitter seems to be a good place these days

Nah, that's ignored too.

2019-07-31 16:40 UTC, Magnytu2 commented
Apparently it is not obvious to attract the attention of the makers of Joomla! 4

2019-07-31 16:56 UTC, marcodings commented
> Apparently it is not obvious to attract the attention of the makers of Joomla! 4
There is no such things as "the makers", anybody can participate. Anyhow i wonder how it is the project missed reaching those of you with other/alternative idea's. The basic design idea's were presented years ago and the repository is public for a more than 4months.
What could the project have done to get your feedback and involvement earlier. Note that i'm not trying to assign blame, i'm trying to understand how it could improve

2019-07-31 17:08 UTC, Magnytu2 commented
I am the project Joomla! 4 from the beginning. I am perhaps the first to have it installed in France. And the first template was fine. The second asked me questions. But the third, sorry, is the symbol of what not to do. Why not use Joomla 3.9 updates to send messages to users and ask their opinion? I am sorry to express myself here. but I use Google translate and Github and a digital border that is difficult to understand for someone who does not develop. I just want to shout at you my misunderstanding!

2019-07-31 17:23 UTC, marcodings commented
I think we discussed this on face-book. Constructive criticism is always welcomed. It should however be precise and actionable.
And unfortunately with a big project like this not everybody can get his/her way

2019-07-31 21:48 UTC, Magnytu2 commented
Hello and sorry, I do not want to be disrespectful. I respect most of all, all the people who give for Joomla.
I just want to say that if for 7 years I'm proud of Joomla, and that for 7 years I speak Joomla to my friends. Today this is no longer the case. I have no pleasure to use, to discover Joomla! 4. Until now I was like a little boy in front of his package Christmas presents, before each evolution of the CMS.
Today this is no longer the case.
The community lives on the love of CMS Joomla! If there is no more love, there will be no more community!

2019-08-01 04:59 UTC, TobsBobs commented
Hello, I think @Magnytu2 is right here. Beautiful is the new template not. The proposal from Elisa was nice but nothing is left of it. Nevertheless, thanks to all who worked so hard on it.

2019-08-04 14:45 UTC, richard67 commented
@brianteeman Could you mark the 3 codestyle items in your to-do list as done? I just checked, they have been solved with last 3 commits by bembelimen.

2019-08-06 12:12 UTC, bembelimen commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +  fill: var(--atum-bg-dark);
Is removed, thx.

2019-08-06 14:45 UTC, Scrabble96 commented
The system message in the backend template editor is rather large:
![System-message-#1](https://user-images.githubusercontent.com/36987494/62549480-7f158a00-b860-11e9-9819-a46c017a20cb.jpg)

A few CSS tweaks would make it look something like this:
![System-message-#2](https://user-images.githubusercontent.com/36987494/62549806-0531d080-b861-11e9-82c3-ee58b884a88a.jpg)

Before I go through the trouble of raising an issue or PR for this, does anyone else agree with this and, if so, raised an issue/PR? Thanks.

2019-08-06 14:59 UTC, Scrabble96 commented
In the template editor, the folder icons are not clickable, only the names, i.e. 'assets', 'css', 'html', 'images', etc., even though the icons change to black from blue when you hover over them. They are clickable in J3.9.10.

Also, in J3.9.10 the file icons are white, which makes them more easily distinguishable from the blue folder icons.

2019-08-06 16:50 UTC, richard67 commented
It seems it needs to copy [brianteeman 's checklist](https://github.com/joomla/joomla-cms/pull/25570#issuecomment-516128747) down here because on deskop it disappears again in the long history, if you don't use the "Show more" button several times.

2019-08-07 11:00 UTC, wilsonge commented on administrator/components/com_menus/tmpl/items/default.php
> +				<?php if (!empty($this->items)) : ?>
Can confirm this is implemented in search tools here https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/searchtools/default.php#L104

2019-08-09 10:57 UTC, C-Lodder commented on tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
> +		$I->wantToTest('that it is possible to delete a Multiple file.');
> that it is possible to delete multiple files.

2019-08-10 00:28 UTC, bembelimen commented on tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
> +		$I->wantToTest('that it is possible to delete a Multiple file.');
Thx.

2019-08-10 08:55 UTC, richard67 commented on tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
> +		$I->wantToTest('that it is possible to delete a multiple file.');
```suggestion
		$I->wantToTest('that it is possible to delete multiple files.');
```

2019-08-10 09:16 UTC, richard67 commented
@bembelimen Am just preparing a PR against this repo for SQL stuff. Stay tuned.

2019-08-10 10:16 UTC, richard67 commented
Sorry for the conflicts, my fault: #25805 . I've noticed too late that this PR here fixes that already. Resolve should be easy because source = target.

2019-08-10 10:49 UTC, wilsonge commented
So at this point all items on @brianteeman 's summary list have been fixed with 3 exceptions

- Help buttons (both links were effectively the same issue so I've closed the one in the template repo https://github.com/joomla/backend-template/issues/259 in favour of https://github.com/joomla/joomla-cms/issues/21990 ) and will bring this up in a vote at the next Production meeting (cc @HLeithner )
- Quick icon module size https://github.com/joomla/joomla-cms/pull/25570#issuecomment-511698133 - this is definitely a user bug but is kind of expected as we've moved the dashboard onto CSS Grid (as a result for obvious reason the bootstrap classes don't work). Obviously this needs solving - but I'm happy to open that up as a release blocking issue rather than trying to solve it here
- https://github.com/joomla/backend-template/issues/310 the keyboard navigation of the filters - this is something again I'm going to open here as a release blocking issue. This just needs some javascript to deal with moving the tabindex around - I don't think it's a major issue to solve - although is of course important to solve for our a11y requirements
- performance - Actually once you use the gzipped version of the CSS then performance increases quite a lot in lighthouse. plus in my personal opinion whilst we of course want to optimise the backend template as best we can (and we can do things that @dgrammatiko has recommended like preloading fonts and maybe the template css in future PRs) we don't need to optimise it to the extent of the frontend template either - we're not looking to get a top google rated backend template 🙂 

I've also asked some people from the backend template team to look into your comment about the template edit view @Scrabble96 you mentioned here https://github.com/joomla/joomla-cms/pull/25570#issuecomment-518707948

At this point unless any major new issues arise before next wednesday I will look to merge this and immediately tag a new alpha of Joomla 4

We are aware that once this is merged more people will be testing it and new issues will be discovered. That doesn't mean it's buggy or poor quality - it's just an acknowledgement that this was and still is a huge task and it's not possible for a small group of people to test, discover and fix everything

2019-08-10 11:33 UTC, dgrammatiko commented
> we don't need to optimise it to the extent of the frontend template either - we're not looking to get a top google rated backend template

Performance is not about satisfying some results from a stupid tool! It's **all about User Experience**. Actually, it's fundamental to UX, because quite simple people -that's all of us- we are impatient, so it's engraved in our DNA. Also since Joomla is an App that actually depends on the network (speed, availability, etc) the performance will always fluctuate, at times getting even worse than the bad scenario that the performance tools set as the bottom line. Also, performance is about being inclusive: wp's edit page will never function at an acceptable level in low powered machines (eg low price android tablets) due to the number of scripts that need to run (hello React!). Keeping an eye at the performance means you care for your users. Also means that you don't consider "potential users" only people from the first world...

@wilsonge please also take care of:
- the useless animation in the main content
- the colorpicker field

You know the drill

2019-08-10 11:43 UTC, richard67 commented
Well, regarding animation I agree with @dgrammatiko : It is not something to have in backend.

Maybe I am not really neutral at this point because my job is related to software for controlling enegry transmission and distibution networks, and we never would lose time with animation in such a critical application.

But here I think we can fix that later.

2019-08-10 11:47 UTC, richard67 commented
I think now we should wait for the next nightly build on [https://developer.joomla.org/backend-template/](https://developer.joomla.org/backend-template/) which will include the latest changes and then text new installations and updates on MySQL and PostgreSQL in order to see if there are serious issues to be fixed. Other small stuff can be fixed later. Just let's make sure nothing will be forgotten.

2019-08-10 12:01 UTC, richard67 commented
Hmm, I just see there is only a nightly build for new install, no update package.

2019-08-10 12:01 UTC, wilsonge commented
I ran the job manually after I posted that comment by now the nightly build should have that stuff in

2019-08-10 12:06 UTC, richard67 commented
@wilsonge Could you provide update package, too? It needs to test updates from 3.9.10, too.

2019-08-10 12:20 UTC, wilsonge commented
No longer at my machine I’m afraid so no. I’m happy to test the update scripts after this gets merged if required though. If I find time this weekend I’ll get them uploaded. But as it’s the second-last week of gsoc my priority this weekend is now to focus on getting my student ready for the google evaluations

2019-08-10 12:23 UTC, richard67 commented
I will see if I can make a patched update package based on 4.0-dev nightly builds. If so, I will provide a link.

2019-08-10 12:43 UTC, astridx commented
@richard67 
Is it possible to test an update from 3.9.10 to 4.0 by using the component Joomla Update and uploading the Nightly Build here?

2019-08-10 12:45 UTC, rdeutz approved these changes

2019-08-10 12:57 UTC, franz-wohlkoenig commented
Update is planned from 3.10 > 4.0

2019-08-10 13:03 UTC, brianteeman commented
@astridx not at this time

2019-08-10 13:39 UTC, bembelimen commented
> @wilsonge please also take care of:
> 
>     * the useless animation in the main content
> 
>     * the colorpicker field
> 
> 
> You know the drill

Pardon? I think your remark is very impertinent. George is neither your slave nor is this the place to make any demands. If you want to have something change, please feel free to create a PR against my branch.

I agree, that we can remove the animation, please make a PR which removes it + all implications and I will happily merge it.

What exactly is the current problem with the colorpicker field? After we agreed, that the performance issues are not from the helper I don't see any problems here? (I would claim, that there is no mensurable impact).

2019-08-10 13:52 UTC, dgrammatiko commented
@bembelimen dude, please take it easy, will you? I'm referring to George because we had a discussion on these issues, he knows what I'm talking about.

> About the colorpicker:
- Joomla has already 2 of them, one based on jQuery and totally inaccessible
- There is an open PR for another one
- This PR is introducing also another one, globally and also some composer dependencies. 

I think we can do better than that, that's all...

2019-08-10 14:04 UTC, richard67 commented
@astridx and others: No, you can't update with the nightly build linked above because that only offers a full install package. But you can find an update package here, I've just built that: [https://test5.richard-fath.de/Joomla_4.0.0-alpha11-dev-Development-Update_Package_2019-08-10__backend-template.zip](https://test5.richard-fath.de/Joomla_4.0.0-alpha11-dev-Development-Update_Package_2019-08-10__backend-template.zip).

2019-08-10 14:08 UTC, bembelimen commented
Thanks for the explaination, I see the problem you mention.

First of all we had the challange, that we need some hue selection. What we did was: we used the existing [colour picker field](https://github.com/joomla/joomla-cms/pull/25570/files#diff-0335cb151b76f5facab785e514627759) and extended its functionallit by adding a new layout (not a complet new field). But you're right we have to many colour picker in the system.

TBH I really don't want to lose the color changing functionallity, because it was a great feature in J! 3. So I would rather like to see a improvement of the current implementation instead of a complet removal.

But as I said, I have no feelings for the animation, please feel free to remove it.

2019-08-10 14:13 UTC, bembelimen commented
And sorry @dgrammatiko that I took your comment the wrong way.

2019-08-10 18:41 UTC, Quy commented
The shadow of the alert does not clear after dismissing it using Firefox Quantum v68.0.1. Windows 10.

![alert](https://user-images.githubusercontent.com/368084/62825602-88a23900-bb63-11e9-8b89-82776828762f.jpg)

2019-08-10 20:00 UTC, richard67 commented
I found some smaller issues, too:

1. Some of the language strings in the help screen seem to be missing, see red frames in following screen shot.

![snap-4](https://user-images.githubusercontent.com/7413183/62826277-fe84bf80-bbb8-11e9-8c94-7f86dee5d8b4.png)

2. When clicking the "Accessibility Settings" link in the User Menu at the top right corner, nothing happens except that the browser console shows an error "Empty string passed to getElementById" for file skipTo.js, line 455, column 28. This does not happen with other links in backend.

3. The link of that "Accessibility Settings" item in the User Menu is just the top of the actual page, don't know if that is by purpose.

![snap-1](https://user-images.githubusercontent.com/7413183/62826316-bd40df80-bbb9-11e9-834f-bb1d7981cdd9.png)

2019-08-11 10:01 UTC, richard67 commented
@Quy Do you mean that statistics dialog which is shown at the first login to the backend? Or any other alert? I want to try to reproduce that.

2019-08-11 10:10 UTC, infograf768 commented
Specifying an image for the custom admin menu menu items does not work (did not find a way to make it work).

Also UI is broken depending on screen size.

Nice

<img width="869" alt="Screen Shot 2019-08-11 at 12 01 25" src="https://user-images.githubusercontent.com/869724/62832518-14819700-bc30-11e9-84f9-e32983b41aba.png">

Not nice

<img width="1131" alt="Screen Shot 2019-08-11 at 12 01 44" src="https://user-images.githubusercontent.com/869724/62832524-22371c80-bc30-11e9-9e43-bdaa56403ce6.png">

Note: not speaking here of the remaining issue with tabs/accordion which is not fixed.

2019-08-11 10:20 UTC, brianteeman commented
> Specifying an image for the custom admin menu menu items does not work (did not find a way to make it work).


Are you sure it works without this template

2019-08-11 10:37 UTC, infograf768 commented
> Are you sure it works without this template

It does not either. But as other stuff has been fixed (we can now create a custom admin template), I was expecting some changes.

In any case, the important stuff here (for now) is **UI is broken depending on screen size.** which depends totally on the js/css of the template.

2019-08-11 10:52 UTC, richard67 commented
@Quy I can't reproduce the alert shadow issue with Firefox Quantum v68.0.1 64 bit on Windows 10. Could you check again with cache cleared and if still having that issue provide some detail about how to reproduce?

2019-08-11 10:54 UTC, richard67 commented
@infograf768 "UI is broken depending on screen size": Isn't that the case with current 4.0-dev, too?

2019-08-11 11:09 UTC, brianteeman commented
PLEASE only report issues here that are specific to this template. IE if it doesn't work without this PR applied either then report it as its own issue

2019-08-11 12:14 UTC, ciar4n commented
> So at this point all items on @brianteeman 's summary list have been fixed with 3 exceptions

@wilsonge 

The following still not addressed..

https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263601096
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263605234
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263609434
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263611454
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263612884
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263616540
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263620496
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263620984
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263622751
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263626478
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263626536
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263628289
https://github.com/joomla/joomla-cms/pull/25570#pullrequestreview-263629895

These are a review of the login scss. I havent checked the rest.

2019-08-11 16:00 UTC, Quy commented
@richard67 All alerts. Probably duplicate of #21803, but visibly more prominent with this template.

2019-08-11 17:47 UTC, richard67 commented
@bembelimen If you merge my 4 PR's against your repo, updating from staging (or any other previous version) to 4.0-dev will work with the new template with MySQL and PostgreSQL. Otherwise it does not work on both DB's.

2019-08-11 20:03 UTC, richard67 commented
@Quy Strange, can't reproduce that, neither on new install of the nightly build of the backend-template repository nor with an staging updated to 4.0-alpha11-dev with a modified update package. Do you have 32 or 64 bit Firefox?

2019-08-11 20:18 UTC, Quy commented
64 bit.  Tested with nightly and 4.0-dev branch.  Duplicate issues #21803 #23425

2019-08-11 20:20 UTC, richard67 commented
@Quy Then it's a 4.0-dev issue, with or without the new template?

2019-08-11 20:24 UTC, Quy commented
@richard67 Yes.

2019-08-12 06:18 UTC, infograf768 commented
> @infograf768 "UI is broken depending on screen size": Isn't that the case with current 4.0-dev, too?

Nope.

> PLEASE only report issues here that are specific to this template. IE if it doesn't work without this PR applied either then report it as its own issue

It IS specific to this PR! Testing before posting is helpful.

This is what we get for the current template: we do NOT have this issue:

<img width="1184" alt="Screen Shot 2019-08-12 at 08 14 31" src="https://user-images.githubusercontent.com/869724/62847959-6a5e4980-bcd9-11e9-91a9-31cc6df3d514.png">

2019-08-13 17:16 UTC, Scrabble96 commented
Good to have the 'real' name requested when installing Joomla, but could this say 'display name' instead?

2019-08-13 17:19 UTC, richard67 commented
@Scrabble96 The "real name" to be entered at installation has nothing to do with the new template and so nothing to do with this PR. It was a change made in 4.0-dev with Pull Request (PR) #25774 and came to the backend template by merging in latest 4.0-dev changes. So if you like to change that, make a new issue for 4.0-dev branch.

2019-08-14 08:51 UTC, wilsonge commented on administrator/templates/atum/scss/blocks/_login.scss
> +      display: flex;
It's allowing the centering of the login container-main block somehow (i just disabled the styles and the box left-aligns)

2019-08-15 09:04 UTC, wilsonge commented
Thank you everyone who was involved here. @ciar4n i'm working on your sass changes at the moment and will do a PR to fix them over the next day or so (unfortunately a bit swamped with real life work at the moment). I know there are some issues raised in here that still aren't fixed but I don't believe these issues to be blocking the merge at this time either so that we have the unified code base and more people can explore and contribute towards this template.

I'd also like to reiterate the below comment I made 
> We are aware that once this is merged more people will be testing it and new issues will be discovered. That doesn't mean it's buggy or poor quality - it's just an acknowledgement that this was and still is a huge task and it's not possible for a small group of people to test, discover and fix everything

2019-08-15 09:04 UTC, merged