[4.0][com_actionlogs] convert to prepared sql
joomla/joomla-cms pull request #25671
Opened 2019-07-21 06:25 UTC by alikon

### Summary of Changes
use prepared statement for SQL

### Testing Instructions
test com_actionlogs

### Expected result

work as before

### Actual result
N/A

2019-07-21 14:25 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on ff662ca4d0155dd463879a1ee16f8422b3b9b3fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-21 14:49 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +					' AND ' . $db->quoteName('a.log_date') . ' <= :dnow'
Split into 2 `where` statements?

2019-07-21 14:50 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
>  			->from('#__action_logs AS a')
```suggestion
			->from($db->quoteName('#__action_logs', 'a')
```

2019-07-21 14:51 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
>  			->innerJoin('#__users AS u ON a.user_id = u.id')
Use join and apply $db->quoteName.

2019-07-21 14:51 UTC, richard67 commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +					' AND ' . $db->quoteName('a.log_date') . ' <= :dnow'
Maybe even better `$db->quoteName('a.log_date') . ' BETWEEN :dstart AND :dnow'`, could also gain a bit performance theoretically.

2019-07-21 14:51 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
>  			->select('a.*, u.name')
```suggestion
			->select('a.*', $db->quoteName('u.name'))
```

2019-07-21 14:57 UTC, richard67 requested changes

2019-07-21 14:57 UTC, richard67 commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +					$db->quoteName('a.log_date') . ' >= :dstart' .
Replace lines 158 and 159 by this one line:
`$db->quoteName('a.log_date') . ' BETWEEN :dstart AND :dnow'`

2019-07-21 14:57 UTC, richard67 commented
I have not tested this item.<br /><br />Will test later again after code review changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-21 15:03 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
>  			->from('#__action_logs AS a')
```suggestion
			->from($db->quoteName('#__action_logs', 'a'))
```

2019-07-21 17:11 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
>  			->select('a.*, u.name')
```suggestion
			->select('a.*', $db->quoteName('u.name'))
```

2019-07-22 06:30 UTC, alikon commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +					' AND ' . $db->quoteName('a.log_date') . ' <= :dnow'
used between

2019-07-22 06:31 UTC, alikon commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
>  			->innerJoin('#__users AS u ON a.user_id = u.id')
done

2019-07-22 06:31 UTC, alikon commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +					$db->quoteName('a.log_date') . ' >= :dstart' .
done

2019-07-22 16:55 UTC, richard67 requested changes
Please fix syntax errors.

2019-07-22 16:55 UTC, richard67 commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +			->join('INNER', $db->quoteName('#__users', 'u') . ' ON ' . $db->quoteName('a.user_id') . ' = ' . $db->quoteName('u.id))
```suggestion
			->join('INNER', $db->quoteName('#__users', 'u') . ' ON ' . $db->quoteName('a.user_id') . ' = ' . $db->quoteName('u.id'))
```

2019-07-22 16:55 UTC, richard67 commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +			->join('INNER', $db->quoteName('#__users', 'u') . ' ON ' . $db->quoteName('a.user_id') . ' = ' . $db->quoteName('u.id));
```suggestion
			->join('INNER', $db->quoteName('#__users', 'u') . ' ON ' . $db->quoteName('a.user_id') . ' = ' . $db->quoteName('u.id'));
```

2019-07-22 17:06 UTC, richard67 commented
@alikon I get a PHP notice as follows when testing your PR now:

> [Mon Jul 22 19:02:51.665201 2019] [php7:notice] [pid 933] [client 192.168.98.1:50765] PHP Notice:  Undefined property: stdClass::$name in /home/richard/lamp/public_html/joomla-cms-4.0-dev/administrator/components/com_actionlogs/Helper/ActionlogsHelper.php on line 66, referer: https://www.joomla-40-dev.vmnet2.local/administrator/index.php?option=com_actionlogs&view=actionlogs

I will update my 4.0-dev branch to latest changes and set up my testing environment from scratch and test again.

2019-07-22 17:15 UTC, alikon commented
Sorry folks for all the issues my pr's raise, I will learn a more user
friendly way to make pr's to lower my shit and reduce the community
efforts, but thanks for your efforts to help


Il lun 22 lug 2019, 19:06 Richard Fath <notifications@github.com> ha
scritto:

> @alikon <https://github.com/alikon> I get a PHP notice as follows when
> testing your PR now:
>
> [Mon Jul 22 19:02:51.665201 2019] [php7:notice] [pid 933] [client
> 192.168.98.1:50765] PHP Notice: Undefined property: stdClass::$name in
> /home/richard/lamp/public_html/joomla-cms-4.0-dev/administrator/components/com_actionlogs/Helper/ActionlogsHelper.php
> on line 66, referer:
> https://www.joomla-40-dev.vmnet2.local/administrator/index.php?option=com_actionlogs&view=actionlogs
>
> I will update my 4.0-dev branch to latest changes and set up my testing
> environment from scratch and test again.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/25671?email_source=notifications&email_token=AABMLMKNHZVFFAXAX4XVVZTQAXSJZA5CNFSM4IFQ7H6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2QQSNA#issuecomment-513870132>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABMLMPTIK3E53NLSWS36W3QAXSJZANCNFSM4IFQ7H6A>
> .
>

2019-07-22 17:18 UTC, richard67 commented
Just don't code in trains ... especially not in Italian ones :tongue: ... joking ... German trains are even worse ... so I would recommend to use Swiss trains ;-) Ah, and maybe more important: Never code on mobile phone, I never would do that, never. It is simply too small for such works.

2019-07-22 17:25 UTC, richard67 commented
I have tested this item :red_circle: unsuccessfully on 25c3a3eeae95da7f9cbc3865ccf0acdce5a46f28<br /><br />When doing CSV export of all action log entries, I get a PHP warning as follows:

> PHP Notice:  Undefined property: stdClass::$name in /home/richard/lamp/public_html/joomla-cms-4.0-dev/administrator/components/com_actionlogs/Helper/ActionlogsHelper.php on line 66, referer: https://www.joomla-40-dev.vmnet2.local/administrator/index.php?option=com_actionlogs&view=actionlogs

Without this PR I don't get that.

From reading code I did not find the reason for that yet. Will continue to try to find it, but maybe someone else is faster.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-22 18:39 UTC, richard67 commented
@alikon Beside the PHP notice for which I haven't found the reason yet: Is there any reason why you haven't converted the query here to prepared?
[https://github.com/joomla/joomla-cms/blob/25c3a3eeae95da7f9cbc3865ccf0acdce5a46f28/administrator/components/com_actionlogs/Model/ActionlogsModel.php#L108](https://github.com/joomla/joomla-cms/blob/25c3a3eeae95da7f9cbc3865ccf0acdce5a46f28/administrator/components/com_actionlogs/Model/ActionlogsModel.php#L108)

2019-07-22 18:56 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +
```suggestion
```

2019-07-22 19:19 UTC, richard67 commented
@SharkyKZ I tried to test this PR but got a PHP notice, details see my test result above. I've tried to find the reason, but I was not successful. Maybe you can have a look?

2019-07-22 19:49 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +
```suggestion
```

2019-07-23 06:28 UTC, alikon commented
@richard67  there is nothing to be prepared there https://github.com/joomla/joomla-cms/blob/25c3a3eeae95da7f9cbc3865ccf0acdce5a46f28/administrator/components/com_actionlogs/Model/ActionlogsModel.php#L108  (i.e. there are no variables to be binded)

2019-07-23 08:36 UTC, richard67 commented
Sorry, check line 111 3 lines below the one l’ve linked.

2019-07-23 08:43 UTC, alikon commented
if  you mean this `->leftJoin('#__users AS u ON a.user_id = u.id');`  previuos answer is still  valid, maybe you can argue that should be `->join('LEFT`'  and `quoteName` 'd

2019-07-23 09:01 UTC, HLeithner commented
I think I mean
```
			->select('a.*, u.name')
			->from('#__action_logs AS a')
			->leftJoin('#__users AS u ON a.user_id = u.id');
		// Get ordering
		$fullorderCol = $this->state->get('list.fullordering', 'a.id DESC');
```
to
```
			->select('a.*,' . $db->quoteName('u.name'))
			->from($db->quoteName('#__action_logs', 'a'))
			->leftJoin($db->quoteName('#__users', 'u'), $db->quoteName('a.user_id') .' = ' . $db->quoteName('u.id'));
		// Get ordering
		$fullorderCol = $this->state->get('list.fullordering', $db->quoteName('a.id') . ' DESC');
```

2019-07-23 10:11 UTC, richard67 commented
@alikon You are right, nothing to be prepared statement there. My mistake. But as Harald said, quoting would be nice.

2019-07-23 17:53 UTC, alikon commented
@richard67  can you confirm that https://github.com/joomla/joomla-cms/pull/25671#issuecomment-513876879  has been fixed by my last commit......  if so i'll update your last cs comment accordindlngly

2019-07-23 17:58 UTC, richard67 commented
@alikon I will test a bit later after eating. What do you mean with my last cs comment?

2019-07-23 18:00 UTC, alikon commented
_buon appetito_
this one https://github.com/joomla/joomla-cms/pull/25671#issuecomment-514146954

2019-07-23 18:25 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 82894972e3e6aa7975032e718b4e5bc5d1562534<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-23 18:27 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 82894972e3e6aa7975032e718b4e5bc5d1562534<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-23 18:27 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-23 18:30 UTC, alikon commented
pleas  wait 1 sec

2019-07-23 18:36 UTC, alikon commented
please a quick retest when you can, updated with the last discover

2019-07-23 18:36 UTC, Quy commented on administrator/components/com_actionlogs/Model/ActionlogsModel.php
> +
```suggestion
```

2019-07-23 18:53 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 5125c15f6c2c5010536ba8b4628a809f5a49ada6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-23 19:04 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 4bf53242f30185a77d4086f9d31dc0cee6d4879e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-23 19:06 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25671">issues.joomla.org/tracker/joomla-cms/25671</a>.</sub>

2019-07-24 12:38 UTC, merged

2019-07-24 12:38 UTC, wilsonge commented
Thanks!