[4.0] [plg_system_httpheaders] Add filters and validation to manifest file
joomla/joomla-cms pull request #25689
Opened 2019-07-22 16:22 UTC by SharkyKZ

Pull Request for Issue # .

### Summary of Changes

Adds filters and validation to manifest and subform.

### Testing Instructions

Apply patch.
Save plugin configuration if this previously saved.

### Expected result

Plugin should work like before.

### Documentation Changes Required

No.

2019-07-22 17:04 UTC, zero-24 requested changes
as noted inline

2019-07-22 17:04 UTC, zero-24 commented on plugins/system/httpheaders/httpheaders.php
> +		$hstsOptions[] = 'max-age=' . $this->params->get('hsts_maxage', 31536000);
please add the cast to integer back here.

2019-07-22 17:07 UTC, SharkyKZ commented on plugins/system/httpheaders/httpheaders.php
> +		$hstsOptions[] = 'max-age=' . $this->params->get('hsts_maxage', 31536000);
Why tho? It's now filtered in plugin configuration form.

2019-07-22 17:11 UTC, Quy commented on plugins/system/httpheaders/httpheaders.php
>  		if ($this->params->get('hsts_subdomains', 0))
Make the same change to lines 307 & 312.

2019-07-22 23:17 UTC, SharkyKZ commented on plugins/system/httpheaders/httpheaders.php
>  		if ($this->params->get('hsts_subdomains', 0))
Which change?

2019-07-22 23:19 UTC, Quy commented on plugins/system/httpheaders/httpheaders.php
>  		if ($this->params->get('hsts_subdomains', 0))
```suggestion
		if ($this->params->get('hsts_subdomains', 0) === 1)
```

2019-07-23 17:30 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 7d86048913a5cda21a011c15e23a429e3b5ca67c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25689">issues.joomla.org/tracker/joomla-cms/25689</a>.</sub>

2020-01-14 02:21 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 3696f474121aac957d01cd98e7f73fe8594956a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25689">issues.joomla.org/tracker/joomla-cms/25689</a>.</sub>

2020-01-14 06:40 UTC, SharkyKZ commented on plugins/system/httpheaders/httpheaders.php
> +		$hstsOptions[] = 'max-age=' . $this->params->get('hsts_maxage', 31536000);
Reverted.

2020-01-14 19:30 UTC, zero-24 approved these changes
LGTM

2020-01-16 11:26 UTC, merged

2020-01-16 11:26 UTC, HLeithner commented
Thanks