[4.0] Searchtools problems Fix for #21676
joomla/joomla-cms pull request #25697
Opened 2019-07-23 19:17 UTC by schnuti

Pull Request for Issue #2176 .

### Summary of Changes
The "default value" for list limit moved out of the list-container. The default value  comes from the Javascript and not from the filter-form. I'm not quite happy with this solution because it makes it impossible to exclude the list values from being cleared. (sorting and number of items). To achieve that a change of HTML-code and CSS-styling would be neccessary . I know now why CSS-styling shouldn't use the Javascript selectors.

### Testing Instructions
see issue 2176
A Javascript rebuild needed.

### Expected result
A Clear should list 20 items and not all.

### Actual result
Shows all items.

### Documentation Changes Required
No

2019-07-23 19:36 UTC, richard67 requested changes

2019-07-23 19:36 UTC, richard67 commented on build/media_source/system/js/searchtools.es6.js
> +          self.getListFields().forEach(i => {
```suggestion
          self.getListFields().forEach((i) => {
```

2019-07-23 19:40 UTC, richard67 commented on build/media_source/system/js/searchtools.es6.js
> +          self.getListFields().forEach(i => {
Plus fix all the other stuff hound reported.

2019-07-23 19:47 UTC, schnuti commented on build/media_source/system/js/searchtools.es6.js
> +          self.getListFields().forEach(i => {
Maybe it would be better to wait a few minutes?

2019-07-23 19:47 UTC, richard67 requested changes

2019-07-23 19:47 UTC, richard67 commented on build/media_source/system/js/searchtools.es6.js
> +        });
Why that `});` in line 285? It is just the closing `}` of the `if (self.getListFields()) {` in line 276 necessary here in line 285.

The `self.getListFields().forEach((i) => {` is already closed in line 280.

Or am I wrong?

2019-07-23 19:48 UTC, richard67 commented on build/media_source/system/js/searchtools.es6.js
> +          self.getListFields().forEach(i => {
Ah sorry, ok.

2019-07-23 19:52 UTC, schnuti commented on build/media_source/system/js/searchtools.es6.js
> +        });
You are right. To fast change. Thanks!

2019-07-23 20:02 UTC, richard67 approved these changes

2019-07-23 20:08 UTC, richard67 commented
@schnuti I applied this PR with patch tester on current 4.0-dev, then did `npm install`, but behavior is still the same as described in the issue. Did I do something wrong?

2019-07-23 20:13 UTC, schnuti commented
@richard67 In what view did you test? I'll test that myself.

2019-07-23 20:14 UTC, richard67 requested changes

2019-07-23 20:14 UTC, richard67 commented on build/media_source/system/js/searchtools.es6.js
> +            window.jQuery('#list_limit').trigger('chosen:updated');
```suggestion
            document.querySelector('#list_limit').trigger('chosen:updated');
```

2019-07-23 20:15 UTC, richard67 commented
@schnuti In the plugins view. With the change I've just suggested it works.

2019-07-23 20:19 UTC, schnuti commented on build/media_source/system/js/searchtools.es6.js
> +            window.jQuery('#list_limit').trigger('chosen:updated');
Copy - Paste. That's the way I have it for test.

2019-07-23 20:21 UTC, richard67 approved these changes

2019-07-23 20:21 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 5cc29eba85e066b679136785f3a6c357d9438bbf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25697">issues.joomla.org/tracker/joomla-cms/25697</a>.</sub>

2019-07-23 20:23 UTC, schnuti commented
@richard67 Thanks!

2019-07-23 20:25 UTC, richard67 commented
@schnuti Thanks for the PR.

2019-07-23 20:34 UTC, brianteeman commented on build/media_source/system/js/searchtools.es6.js
>          if (window.jQuery && window.jQuery.chosen) {
any chance of re-writing this to get rid of jquery. 

its got to be done at some point

2019-07-23 20:40 UTC, schnuti commented on build/media_source/system/js/searchtools.es6.js
>          if (window.jQuery && window.jQuery.chosen) {
@brianteeman As I wrote - I'm not a Javascript guru. I can search the web if I can find some replacement for this chosen thing. But it's not directly related to the problem.

2019-07-23 20:42 UTC, richard67 commented on build/media_source/system/js/searchtools.es6.js
>          if (window.jQuery && window.jQuery.chosen) {
And I do not even know javascript.

2019-07-23 20:45 UTC, brianteeman commented on build/media_source/system/js/searchtools.es6.js
>          if (window.jQuery && window.jQuery.chosen) {
it's the window.jquery that will need to be changed not the chosen part ;)

2019-07-23 21:25 UTC, schnuti commented on build/media_source/system/js/searchtools.es6.js
>          if (window.jQuery && window.jQuery.chosen) {
Isn't chosen built on JQuery? as most alternatives.

2019-07-23 22:37 UTC, dgrammatiko commented on build/media_source/system/js/searchtools.es6.js
>          if (window.jQuery && window.jQuery.chosen) {
You can safely remove all instances of this:
```js
        // Trigger the chosen update
        if (window.jQuery && window.jQuery.chosen) {
          //////// Some code
        }
```

2019-07-23 22:47 UTC, brianteeman commented on build/media_source/system/js/searchtools.es6.js
>          if (window.jQuery && window.jQuery.chosen) {
oops my mistake - its choices we use now not chosen

2019-07-23 23:00 UTC, dgrammatiko commented on build/media_source/system/js/searchtools.es6.js
> +            document.querySelector('#list_limit').trigger('chosen:updated');
Native elements **do not** have a trigger function. To trigger an event the process is different, but anyway, this whole section is totally useless as J4 doesn't use chosen anymore. So just remove this (and maybe all the rest similar lines form this script)

2019-07-24 06:03 UTC, schnuti commented on build/media_source/system/js/searchtools.es6.js
> +            document.querySelector('#list_limit').trigger('chosen:updated');
I removed all jQuery - trigger sections

2019-07-24 06:23 UTC, schnuti commented
@dgrammatiko 
Do you know if the code for the list-container Is needed for alternative layouts? It's not used in the core layout.
As I wrote: This fix always clears the No Items to the "default" value if it's present.

2019-07-24 08:45 UTC, dgrammatiko commented
@schnuti unfortunately I cannot answer this question without looking at all the possible implementations

2019-07-24 18:28 UTC, richard67 commented
@schnuti Is it ready for test?

2019-07-24 20:53 UTC, schnuti commented
@richard67 and all
Ready for test. jQuery was removed after your test. That should not change anything.

2019-07-24 21:12 UTC, richard67 commented
@schnuti I've tested and it changed something: The PR does not fix the issue anymore, behavior with and without PR is the same. Tested as before with applying patch, running `npm install`, testing in plugins list.

2019-07-24 21:29 UTC, richard67 commented
@schnuti Sorry, false alarm. Forget my previous comment, all ok.

2019-07-24 21:34 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 3722b413d5765ee5c90503c2bd7655288ae5978d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25697">issues.joomla.org/tracker/joomla-cms/25697</a>.</sub>

2019-07-25 06:25 UTC, schnuti commented
Do you want me to add a fix for the Number of Items to this PR?
The priority would be 1. from the view, 2. from the filter-form 3. from global parameter, 4. fixed 20
As is the 2. is missing. I was wrong about this value coming fixed from the Javascript where 20 is predefined.
I'm picking around a bit trying to find a better way to handle the merged list- and filter-values. That would be a new PR if I'm able to come up with an idea.

2019-07-25 16:56 UTC, richard67 commented
@schnuti Did you ask me in your previous comment? If so, I have no idea what you mean.

2019-07-25 19:37 UTC, schnuti commented
@richard67 
It was a general question if it's preferred to include a second issue or not.
To better understand what I mean, you can edit a filter form and set the limit to e.g. 5.
Better with the first fix installed.
e.g. in administrator/components/com_plugins/forms/filter_plugins.xml
Change line 78 to default="5"
Go to Plugin List. Check the list limit (=5)
Click on Clear button.
I expect the list limit to be 5.
What is it.
(personally I would prefer a No Change but that's another issue.)

2019-07-25 19:41 UTC, richard67 commented
@schnuti And now with this PR included it is 20? I don't remember the test right now.

I am not sure what is better: Make a new PR or do it in this PR here.

If you can fix it soon I would say do it in this one here, but if it takes longer I would say make new issue, so this PR here gets tested and merged soon.

2019-07-25 21:26 UTC, schnuti commented
I have a working solution for the list limit value but have to do some tests on fictive cases.
The code looks a bit weird because of those other cases.

2019-07-25 21:28 UTC, richard67 commented
Let us know when ready so we don't test while still in progress.

2019-07-26 12:42 UTC, richard67 commented
@schnuti Let us know if you wanna fix that in this PR so a 2nd tester waits with testing or if you make a new one so we quickly get a 2nd tester for this one for RTC. By the way I am happy to see you contributing to Joomla and would of course be happy if it would be more :smile:

2019-07-26 13:24 UTC, schnuti commented
@richard67 
You'll have it in a few hours. The extra tests worked fine for me.

2019-07-26 14:31 UTC, schnuti commented
Ready for test if the checks go through.
Do you need some test instructions?

2019-07-26 15:25 UTC, richard67 commented
> Do you need some test instructions?

Would be helpful, yes.

2019-07-26 15:59 UTC, schnuti commented
Test instructions added on the top.

2019-07-26 16:01 UTC, richard67 commented
I will test tomorrow, today am busy for the rest of the day.

2019-07-26 19:21 UTC, richard67 commented
@schnuti Test with changed default value in XML works only when default value in XML is a multiple of 5, e.g. with 5 or 10 or 15 ... => OK, but when e.g. 13: List shows all plugins, list limit in filter field shows 5 => Strange, but maybe desired behavior because limits shall be multiple of 5.

But then it should be fixed by either validating the value, or integer division by 5 in code or round in code, or at least leave a comment in the xml. I am for integer division, i.e. e.g. 13 results in 10.

Can you fix that?

2019-07-26 19:39 UTC, schnuti commented
@richard67 
Is it when you click Clear or when you first start the list?
The changed scripts do not manipulate the values but perhaps the field type.
I'll have a look tomorrow.

2019-07-26 19:41 UTC, richard67 commented
@schnuti When I clear. I think (not tested yet) it is the same without your PR.

2019-07-26 19:46 UTC, schnuti commented
Without my PR part 2 the XML value is not used as default in the Javascript.

2019-07-26 19:48 UTC, richard67 commented
Yes, I know. I mean when you change soomewhere else the value to e.g. 13 you will have the problems without your PR, too.

2019-07-26 19:51 UTC, schnuti commented
Maybee try to set the Global list limit to 13 without PR II.

2019-07-26 19:52 UTC, richard67 commented
I will try tomorrow.

2019-07-26 21:41 UTC, schnuti commented
@richard67 
I added a check for allowed values. It's not bullet prof if someone somehow sets custom values.
The problem is probably that when the JS writes to the "Choices" list, the value isn't there.
Maybe the check could be done against the DOM within the JS instead? I do not know.exactly how to do that. Is it worth it?

2019-07-26 21:43 UTC, richard67 commented
I also don't know exactly how to do that. No idea if it is necessary or worth it. Will test tomorrow. Good night.

2019-07-27 09:55 UTC, richard67 commented
@schnuti The more I think it over, the more I am not sure if your last change is really needed. I think old code also relies on the default value in the XML being set in the right way. I suggest just undo that last commit, update your testing instructions to use values which are multiple of 5, and then we test again with success and get this PR RTC so the original problem is fixed.

2019-07-27 11:39 UTC, schnuti commented
@richard67 
The default value for Clear is not from the filter-form XML
I will revert the check for the values. It has no relation to a multiple of 5 as far as I can see.
A developer not using a standard value as default has to add it to the XML.
Like so:
append="33"
default="33"
I'm not sure yet that the start value 33 is accepted by the field type. That could be left to another issue.

2019-07-27 11:48 UTC, schnuti commented
Check for limit values removed!
Added to test instructions
append="33"
default="33"

2019-07-27 12:01 UTC, schnuti commented
@richard67 
An idea: The start value problem could be related to the language string. In the example above with 33 the shown value is J33 as it's not translated. But keep it out of this PR.

It should be tested as it is now.

2019-07-27 12:03 UTC, richard67 commented
Ok, makes sense. Will test later today.

2019-07-27 18:02 UTC, richard67 commented
@schnuti I've tested again and think the behavior might be a bit confusing: After new installation plus your patch, when I go to the pligins list for the very first time, then then list limit is 20, even if in the XML during installation it was 10. When I then click the reset button, the list limit is the 10 from the XML. Is that desired or a mistake?

2019-07-27 18:16 UTC, richard67 requested changes
We should make the defaults in code same as in XML. Maybe that will even solve the behavior I've mentioned in my last comment.

2019-07-27 18:16 UTC, richard67 commented on layouts/joomla/searchtools/default.php
> +	$listLimit = $data['view']->filterForm->getFieldAttribute('limit', 'default', 20, 'list');
```suggestion
	$listLimit = $data['view']->filterForm->getFieldAttribute('limit', 'default', 25, 'list');
```

2019-07-27 18:16 UTC, richard67 commented on layouts/joomla/searchtools/default.php
> +	$listLimit = $data['options']['defaultLimit'] ?? Factory::getApplication()->get('list_limit', 20);
```suggestion
	$listLimit = $data['options']['defaultLimit'] ?? Factory::getApplication()->get('list_limit', 25);
```

2019-07-27 18:40 UTC, schnuti commented
Do you agree that the value should come from the XML?
Unfortunaly - the first time it comes from the global list setting. When you send a search request (change a value or click the search button) the value comes from the XML. It's then also set to session.
At the moment I'm editing one of my own models to handle that.

2019-07-27 18:44 UTC, schnuti commented
I meant the value set in the limit field will be stored in the session.
I'll be back tomorrow - not more today.

2019-07-27 18:45 UTC, richard67 commented
Ok, have a nice evening.

2019-07-27 18:45 UTC, richard67 commented
I agree it should come from the XML.

2019-07-27 19:03 UTC, schnuti commented
A last thing for today.
That it works for ordering and direction is bacause you set default values for those in the model.
Try to change the XML with another default ordering.
i.e. one quick and dirty solution would be to set a default limit value in the model as well. I don't know if the parent model handle it without changes..

2019-07-28 10:24 UTC, schnuti commented
@richard67 
I've found a work around for my own model that can't be an alternative for core.
In the populateState method I set a custom value
$app->setUserState('global.list.limit', 10);
and reset it afterwards
$app->setUserState('global.list.limit', $app->get('list_limit'));

Do we keep part two of this PR or should I revert it to use the default limit value from the global setting? Both can be confusing :(

2019-07-28 11:13 UTC, richard67 commented
Well is just my opinion: Maybe really better revert all additional parts of this PR so it fixes only the original problem. I wish someone else who has a better idea of how it was intended to work would comment here, too. I leave it up to you how you decide, just let me know later when ready for test again, and please keep the testing instructions up to date if you change something.

2019-07-28 13:23 UTC, schnuti commented
My opinion is to keep it but it doesn't matter. I'll use some override anyway. The new layout in J4 that clears ordering and limit leads to a lot more clicks when in list view. The J3 layout was better for me. The new backend multiplies the number of clicks needed in a work day anyway.

2019-07-28 14:04 UTC, richard67 commented
So shall this PR here tested like it is now? Or shall I wait for changes?

2019-07-28 14:53 UTC, schnuti commented
I think you have tested.
I'll make changes if it's decided.

2019-07-28 15:25 UTC, brianteeman commented
this is a good example of why a PR should only address one issue

2019-07-28 15:25 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on a767cdd261490a5851ebc58fd19e4c0447b24581<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25697">issues.joomla.org/tracker/joomla-cms/25697</a>.</sub>

2019-07-28 15:26 UTC, richard67 commented
I've tested all, including the extra test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25697">issues.joomla.org/tracker/joomla-cms/25697</a>.</sub>

2019-08-31 07:48 UTC, schnuti commented
As the filter + sorting was reverted to the J3 solution this problem became obsolete.

2019-08-31 07:48 UTC, closed without merging