[4.0] use standard SQL - fix errors on postgresql
joomla/joomla-cms pull request #25724
Opened 2019-07-28 08:34 UTC by alikon

Pull Request for Issue 
use standard SQL

### Summary of Changes
rewrite query in standard SQL instead of mysql dialect
- correct JOIN   for syntax error at or near "WHERE" 
- ERROR: CASE types character varying and numeric cannot be matched

### Testing Instructions

Install latest staging and populate data with sample testing plugin
go on frontpage

### Expected result

see articles even in postgresql 

### Actual result
errors with postgresql

2019-07-28 08:38 UTC, richard67 commented
Testing instructions say “install latest staging” but I guess you mean “install latest 4.0-dev” since this PR is for 4.0-dev. If I am right, please correct.

2019-07-28 08:38 UTC, alikon commented
yes latest 4.0

2019-07-28 08:40 UTC, richard67 commented
Will test later in the afternoon CEST time.

2019-07-28 12:20 UTC, richard67 requested changes
Fix PHPCS errors reported by drone.

2019-07-28 12:20 UTC, richard67 commented on plugins/content/pagenavigation/pagenavigation.php
> +				. ' ELSE '. $query->castAsChar('a.id') . ' END AS slug';
```suggestion
				. ' ELSE ' . $query->castAsChar('a.id') . ' END AS slug';
```

2019-07-28 12:20 UTC, richard67 commented on plugins/content/pagenavigation/pagenavigation.php
> +				. ' ELSE '. $query->castAsChar('cc.id') . ' END AS catslug';
```suggestion
				. ' ELSE ' . $query->castAsChar('cc.id') . ' END AS catslug';
```

2019-07-29 18:04 UTC, richard67 commented
@alikon If you find time, please fix the drone PCPCS errors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25724">issues.joomla.org/tracker/joomla-cms/25724</a>.</sub>

2019-07-30 08:18 UTC, alikon commented
@richard67 cs fixed..... when you have time...

2019-07-30 17:22 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 356f56fb3934d789c2433a730b2613be3e3e853f<br /><br />There are still errors with testing sample data on PostgreSQL, but they are not related to this PR, i.e. the errors are there with and without this PR:

1. On MySQL, the article with title "Joomla! Testing" as 4 tags assigned, tags "2", "3", "4" and "5", but on PostgreSQL the same article has only 1 assigned, which is tag "2".
2. When editing any article, a red popup alert "Error" is shown, telling only "An error has occurred.".
3. When trying to save a new article, an SQL errors about null value for column with not null constraint is shown.

As I said, it seems not to be related to this PR.

I will make new issues for that, except @alikon tells me before that he wants to fix the one or other thing here in this PR, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25724">issues.joomla.org/tracker/joomla-cms/25724</a>.</sub>

2019-07-30 18:02 UTC, alikon commented
@richard67  thanks for testing
it should be always better to have 1 pr for 1 issue as a main rule
so i will be happy if free time permits me, to make a pr for any issue postgresql related (even not) that you'll submit  (you know my mantra is to close issues as many as possible :smile: )

2019-07-30 19:46 UTC, richard67 commented
@alikon Could you check issue #25747 ? It seems to be related to SQL in testing sample data, too, so maybe this PR here would be the right place so fix that.

2019-07-31 19:01 UTC, merged

2019-07-31 19:01 UTC, wilsonge commented
Thanks!