[4.0][com_finder] wrong encoding for bytea postgresql
joomla/joomla-cms pull request #25884
Opened 2019-08-16 06:05 UTC by alikon

### Summary of Changes
wrong encoding for bytea
wrong inner join update syntax

### Testing Instructions
on postgresql
enable smart search plugin
edit & save a tag

### Expected result
tag is saved
works as before on mysql

### Actual result
multiple errors

2019-08-16 07:44 UTC, HLeithner commented
All new pr should use prepared statements, could you update this pr?

2019-08-16 07:56 UTC, alikon commented
well yes, i could, but atm with this silly PR i just want to give to the few postgresql users the opportunity to play a little bit with j4, and help us to discover more bugs.....prepared statement conversion should be matter for another pr imho

2019-08-16 09:11 UTC, HLeithner commented
At the moment only you and me did prepared statement conversion it should be a strict requirement on all pr touching a sql statement to convert it to use prepared statements.
There was a PLT motion about this topic:

https://volunteers.joomla.org/departments/production/reports/1013-production-dept-meeting-may-07-and-may-14-2019

If we don't required this we will still get new non prepared queries in patches.

2019-08-16 09:28 UTC, alikon commented
i'd be more than happy if this motion have been taken in serious count before merging  all & more,
but honestly this has not been happened....

2019-08-16 12:27 UTC, mbabker commented
> At the moment only you and me did prepared statement conversion it should be a strict requirement on all pr touching a sql statement to convert it to use prepared statements.

Forcing unrelated changes into pull requests is exactly how you end up making pull requests more complex to review and more error prone.  Converting existing queries should be pull requests of their own, writing new queries it is fine to mandate this.  "You touched it so you need to change it" isn't a good workflow.  Same goes with the random unrelated code style fixes that are commonly requested.

2019-08-16 12:38 UTC, HLeithner commented
> Forcing unrelated changes into pull requests is exactly how you end up making pull requests more complex to review and more error prone. Converting existing queries should be pull requests of their own, writing new queries it is fine to mandate this. "You touched it so you need to change it" isn't a good workflow. Same goes with the random unrelated code style fixes that are commonly requested.

This is partly true, but whats the better way? If no queries get updated to PS only if we find more then 2 people to do this job we will never finish this task.

Anyway I don't request to update all queries in this file only the one that get touched and tested afterwards. In a perfect would we would have tests at the same time, or the PR includes a test if non exists but as we all know tests are still missing all over the place. 

It's ok for me if at least new queries use PS...

2019-08-17 06:41 UTC, Hackwar requested changes

2019-08-17 06:41 UTC, Hackwar commented on administrator/components/com_finder/Indexer/Driver/Postgresql.php
>  			->where($db->quoteName('link_id') . ' = ' . $db->quote($linkId));
This is not a string. Utf8_encode is wrong here.

2019-08-17 06:41 UTC, Hackwar commented on administrator/components/com_finder/Indexer/Driver/Postgresql.php
>  		}
This is also not correct. The string should already be utf8. If it isn't, there is an issue further up in the code.

2019-08-17 10:31 UTC, richard67 commented
@alikon Will you work on this, make Harald happy with just changing those queries to PS which you have modified, and handle Hannes‘ comments? If so, ping me when ready for tests. But if you have little time: Shall I help with picking up that work and making PR for your repo so you just can merge with 1 click? If so, ping me and I will do later today.

2019-08-18 07:26 UTC, alikon commented on administrator/components/com_finder/Indexer/Driver/Postgresql.php
>  		}
used pg_escape_bytea instead

2019-08-18 07:27 UTC, alikon commented on administrator/components/com_finder/Indexer/Driver/Postgresql.php
>  			->where($db->quoteName('link_id') . ' = ' . $db->quote($linkId));
used pg_escape_bytea instead

2019-08-18 14:36 UTC, zero-24 approved these changes
I can not acutally check on postgresql but on review it looks good to me.

2019-08-18 15:26 UTC, richard67 commented
@Hackwar Could you check if it ok now?

2019-09-15 14:24 UTC, twister65 commented
I have tested this item :white_check_mark: successfully on c484f45da677d3b848053fbe6050f0201da09252<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25884">issues.joomla.org/tracker/joomla-cms/25884</a>.</sub>

2019-09-15 15:16 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on c484f45da677d3b848053fbe6050f0201da09252<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25884">issues.joomla.org/tracker/joomla-cms/25884</a>.</sub>

2019-09-15 15:25 UTC, richard67 commented
@Quy RTC please :smile:

2019-09-15 15:27 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25884">issues.joomla.org/tracker/joomla-cms/25884</a>.</sub>

2019-09-16 20:21 UTC, wilsonge commented on administrator/components/com_finder/Indexer/Indexer.php
> +			->where($db->quoteName('m.link_id') . ' = :linkid')
If we're parameterzing this shouldn't we do all the queries using it below this? Also do we not want to keep the `(int) $linkId` part?

2019-09-17 06:20 UTC, alikon commented on administrator/components/com_finder/Indexer/Indexer.php
> +			->where($db->quoteName('m.link_id') . ' = :linkid')
done

2019-09-17 08:47 UTC, merged

2019-09-17 08:47 UTC, wilsonge commented
Thanks!