[4.0] Schedule featured articles
joomla/joomla-cms pull request #25979
Opened 2019-08-22 21:05 UTC by eshiol

Pull Request for Issue #13596.
J4 rebased PR #18052

### Summary of Changes
Added two fields in the article editor featured_up (Start Featured) and featured_down (End Featured)
![Cattura](https://user-images.githubusercontent.com/12718836/63549617-10f3e700-c531-11e9-8efa-0756adaf115d.PNG)
An article is featured if featured is yes and (featured_up is null or is less than or is equal to now) and (featured_down is null or is greater than or is equal to now)

### Testing Instructions
Create 5 articles:
1. not featured
2. featured, featured_up = null, featured_down = null
3. featured, featured_up = tomorrow, featured_down = null
4. featured, featured_up = null, featured_down = yesterday
5. featured, featured_up = yesterday, featured_down = tomorrow
Create an Articles » Featured Articles menu item
Create a News Flash module and set the option Featured Articles to Only show Featured Articles.
### Expected result
Only the articles 2 and 5 will be shown in the Articles » Featured Articles menu item and in the News Flash module.
### Actual result
### Documentation Changes Required

2019-08-23 22:42 UTC, brianteeman commented
In joomla 4 we are trying to avoid useless descruiptions on fields so you can just delete the _DESC strings

2019-08-24 11:26 UTC, richard67 requested changes
Fix PHP code style errors repored by Drone PHPCS here: [https://ci.joomla.org/joomla/joomla-cms/22504/1/9](https://ci.joomla.org/joomla/joomla-cms/22504/1/9)

2019-08-24 11:26 UTC, richard67 commented on libraries/src/Button/FeaturedButton.php
> +	 * @param   mixed        $value        Current value of this item.
```suggestion
	 * @param   mixed        $value         Current value of this item.
```

2019-08-24 11:26 UTC, richard67 commented on libraries/src/Button/FeaturedButton.php
> +	 * @param   string       $row          The row number of this item.
```suggestion
	 * @param   string       $row           The row number of this item.
```

2019-08-24 11:26 UTC, richard67 commented on libraries/src/Button/FeaturedButton.php
> +	 * @param   array        $options      The options to override group options.
```suggestion
	 * @param   array        $options       The options to override group options.
```

2019-08-24 11:26 UTC, richard67 commented on components/com_content/Model/ArticlesModel.php
>  			}
```suggestion
			}

```

2019-08-24 13:15 UTC, impressionestudio commented
I tested it. The result was successful.

2019-08-24 13:50 UTC, franz-wohlkoenig commented
@impressionestudio please mark your test as successfully (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)

2019-08-24 14:05 UTC, richard67 commented
@franz-wohlkoenig This PR has PHPCS errors, I've reviewed accordingly.

2019-08-24 15:15 UTC, impressionestudio commented
> @impressionestudio please mark your test as successfully (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)

I installed Joomla Patch Tester, applied the patch and then the page crashed with errors like:
- Unknown column 'a.featured_up' in 'field list' Unknown column 'a.featured_up' in 'where clause'
- Warning: Invalid argument supplied for foreach() in D:\Localhost\joomla4\components\com_content\Model\ArticlesModel.php on line 628
- Warning: Invalid argument supplied for foreach() in D:\Localhost\joomla4\modules\mod_articles_news\Helper\ArticlesNewsHelper.php on line 121

2019-08-24 15:30 UTC, franz-wohlkoenig commented
@impressionestudio apologies, i didn't thought that j4 can't be testet by patchtester – @richard67 can you please advise @impressionestudio?

2019-08-24 15:37 UTC, richard67 commented
@impressionestudio Patchtester has to be latest version 3.0.0-beta4.

After having applied the patch, you have to run the SQL statements in file `administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-08-20.sql` or `administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-08-20.sql` in PhpMyAdmin or PhpPgAdmin, depending on which database you use. You have to replace the `#__` with your database prefix (including the `_` at the end).

Or if you are on a testing environment where you can do that, also apply the patch, then delete all tables from your database, remove configuration.php and makle a clean new installation.

2019-08-24 16:10 UTC, Quy commented on libraries/src/Button/FeaturedButton.php
> +			$nowDate = Factory::getDate()->toUnix();
```suggestion
			$nowDate  = Factory::getDate()->toUnix();
```

2019-08-24 16:10 UTC, Quy commented on libraries/src/Button/FeaturedButton.php
> +				$tips = array();
```suggestion
				$tips = [];
```

2019-08-24 16:25 UTC, Quy commented
See PR #25760 to see how to convert datetime to null value.

2019-08-24 17:52 UTC, impressionestudio commented
@richard67 thank you for the instructions and @franz-wohlkoenig for the answers. 

I have installed the latest version 3.0.0-beta4.
But the problem is that I am not keen to Github. Also all these actions are too much for me.
I thought that testing would be easier. I wanted to help but it seems I am not able to do it and I want to tire you more.

2019-08-24 18:05 UTC, franz-wohlkoenig commented
@impressionestudio there's a plan to make patchtester ready fpr j4 – which also would help me to test :-). 

> "Joomla 4 has steps to compile assets (composer and npm) and the Patchtester component does not support that (yet). The idea is, that our CI system is compiling these assets and provides them via some API to the Patchtester component."

 from https://volunteers.joomla.org/teams/automated-tests-working-group/reports/1080-meeting-report-2019-08-05

2019-08-24 18:12 UTC, richard67 commented
I will test this PR after @Quy 's suggestions will be implemented.

2019-08-25 01:37 UTC, Quy commented on libraries/src/Button/FeaturedButton.php
> +			$default  = $this->getState($value) ? : $this->getState('_default');
```suggestion
			$default  = $this->getState($value) ?: $this->getState('_default');
```

2019-08-25 09:54 UTC, richard67 commented
@Quy Is there something to be done with datetime null values in this PR? I see your comment above but can‘t see to what in the code it is related.

2019-08-25 09:59 UTC, richard67 commented
@franz-wohlkoenig The patch tester component never did run the schema updates (these are those sql scripts with date and version in theor name) because if he would do that, it would also need a kind of undo script to revert the changes. This was always the case and is same for J3 and J4, so you always have to run the SQL manually. Only difference on J4 is that when a PR changes js or (s)css, you have to run `npm install` after applying the patch and then again after reverting it after test.

2019-08-25 10:12 UTC, alikon commented
as already reported on the original pr for j3 here https://github.com/joomla/joomla-cms/pull/18052#pullrequestreview-65442059 and here https://github.com/joomla/joomla-cms/pull/18052#issuecomment-350231866

 "`featured_up`" and "`featured_down`" fields should go into the "`#__content_frontpage`" table and not in the `#__content` table....

2019-08-25 15:49 UTC, Quy commented
@richard67 In the sql files, remove ` NOT NULL DEFAULT '0000-00-00 00:00:00'` and `DEFAULT '1970-01-01 00:00:00' NOT NULL`.

In the queries, use `isNullDatetime`. 

Replace `getNullDate()` with `null`.

2019-08-25 15:52 UTC, richard67 commented
> In the sql files, remove ` NOT NULL DEFAULT '0000-00-00 00:00:00'` and `DEFAULT '1970-01-01 00:00:00' NOT NULL`.
> 
> In the queries, use `isNullDatetime`.
> 
> Replace `getNullDate()` with `null`.

@eshiol Could you implement those suggestions by @Quy ? And move "featured_up" and "featured_down" fields to the "#__content_frontpage" table as suggested by @alikon ?

2019-08-29 17:40 UTC, eshiol commented
I did it

2019-09-01 16:04 UTC, WoodyF4u commented
Dear developers,
Is my question still in progress?
Or is it closed again?

I don't understand the status in:
Closed:
https://github.com/joomla/joomla-cms/issues/25439
https://github.com/joomla/joomla-cms/pull/18052

Open PR:
https://github.com/joomla/joomla-cms/pull/25979
Or is this losed tooo?

At the moment it is not yet in Alpha 10.
I realy hope it is still on the list for Joomla! 4.0

2019-09-01 16:25 UTC, richard67 commented
@WoodyF4u This is open and waits for testers. Unfortunately I have no time to test right now. Could you test?

2019-09-02 00:00 UTC, WoodyF4u commented
Hi Richard,
Of course I can test it.
But yesterday I istalled a fresh J4.0 Alpha 10, but in that release I can not find this new feature.
What can I do to find this feature?

2019-09-08 20:06 UTC, richard67 commented
@WoodyF4u Since this PR here which implements this new feature is still open and waits to be tested, it can't be already part of some 4.0 Alpha or nightly build. It needs to test this PR here.

2019-09-11 12:47 UTC, WoodyF4u commented
@richard67 OK I understand it can not be a part of an Alpha-release.
But I am a simple Joomla user and not a developer.
How can I test this new feature in a latest 4 Alpha?

2019-09-11 13:04 UTC, brianteeman commented
@WoodyF4u follow the guide here https://brian.teeman.net/joomla/873-a-dummies-guide-to-joomla-bug-testing

Obviously with joomla 4 alpha not joomla 3 but otherwise the instructions are the same

2019-09-29 14:16 UTC, WoodyF4u commented
Hi Brian,
I just installed e fresh Joomla! 4 Alpha 11 and after that I installed The Joomla! Patch Tester.
When I go to Componnts and select the Joomla! Patch Tester I receive this error: 	
Class '\PatchTester\Controller\DisplayController' not found 

Are you sure this component is ready for Joomla! 4 ?

2019-09-30 06:43 UTC, alikon commented
Patch Teste works well on j4 https://github.com/joomla-extensions/patchtester/releases/tag/3.0.0-beta4

2019-09-30 10:47 UTC, WoodyF4u commented
Thanks. I was using Patch Tester 2.0.0
Now with the 3.0.0 it runs great.
So I added the patch to Joomla! 4.0 Alpha 11 now.
And I tried to add a new article with scheduling the featured options.
Iadded a start date and time and I added a stop date and time.
Then I would save the article but received this error:

> 1054 Unknown column 'featured_up' in 'field list' 
I hope someone can fix it so I can do a new test.

2019-09-30 10:52 UTC, alikon commented
you need to run manually in phpmyadmin the sql script provided here https://github.com/joomla/joomla-cms/pull/25979/files#diff-258e43a1cdbb61e7a9ba5fccd61a692e
  
```sql
ALTER TABLE `#__content_frontpage` ADD COLUMN `featured_up` datetime;
ALTER TABLE `#__content_frontpage` ADD COLUMN `featured_down` datetime;
```
remember to change #__  with you table prefix

2019-09-30 17:38 UTC, WoodyF4u commented
Hi Nicola,
I addedd the columns to he database.
Now I can add an article to the Joomla 4 test site.
I can set it featured.
But as soon as I set a start date and timne and a stop date and time.
The featured article at the home page is no longer visible there.
So dor as far as I can test it now, the fields "Start featured" and "Finish featured" do'n't do what it need o do.

2019-10-01 05:32 UTC, richard67 commented
@WoodyF4u Maybe you have to specify times in UTC? I’ve noticed that bug at other places in past. It could be that you enter a time for featured up of which you think it comes in 5 minutes but when you are in time zone UTC+2 you might have to wait 2 hours and 5 minutes. Could you check that and report back the result here? I currently can’t test that myself.

2019-10-01 07:36 UTC, WoodyF4u commented
Hi Richard,
Clever!
I changed the time setting in the Global configuration to Amsterdam.
Now it works great.
So for now I am very happy with this.

One issue:
When I set a Finish time before the Start time, it is possible to save the article.
It would be nice when there will be a message popup when this is detected.

2019-10-18 18:54 UTC, WoodyF4u commented
Is there someone with developer knowledge here who can continue this request?
I realy hope this feature will be part of Joomla 4.0 soon.

2019-10-18 20:15 UTC, ot2sen commented
I have tested this item :red_circle: unsuccessfully on 7b025d948f2b3410f1e57beb2fe2c324ea361b60<br /><br />The timed Featured seems to work, but the articles themselves get an 'Expired' tag at all times after having added the sql

ALTER TABLE `myprefix_content_frontpage` ADD COLUMN `featured_up` datetime;
ALTER TABLE `myprefix_content_frontpage` ADD COLUMN `featured_down` datetime;

Feeling uncertain whether to mark as successful or unsuccessful, chose the latter.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-18 20:16 UTC, ot2sen commented
For reference for the "unsuccessful" test:

![screen shot 2019-10-18 at 20 16 25](https://issues.joomla.org/uploads/1/25020a0642186d9f743d80b85681c5a7.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-18 20:17 UTC, richard67 commented
@ot2sen The reason is that this PR has not been adapted to latest changes in 4.0-dev regarding null values for datetime database columns, and it also has merge conflicts as you can see at the bottom.

2019-10-18 20:19 UTC, ot2sen commented
@richard67 Thanks Richard, makes sense.
The scheduling part worked fine. The expired tags were extra :)

2019-10-18 20:35 UTC, ot2sen commented
I have tested this item :white_check_mark: successfully on 7b025d948f2b3410f1e57beb2fe2c324ea361b60<br /><br />Marking as successful as the timed featured works well<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-18 20:36 UTC, ot2sen commented
@WoodyF4u better mark your test successful at top.

This gives it a chance to get included :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-18 20:38 UTC, richard67 commented
It has merge conflicts which have to be solved by the author. If it then breaks something else, it has to be fixed. Tomorrow or Sunday I could help with the latter. But just because the desired function change works to give a good test when it is obvious that it breaks something else is not good.

2019-10-18 20:46 UTC, ot2sen commented
Obviously, you´re right @richard67 :) Quality control matter.
Pushing to wake up @eshiol so we can get the nice work included. I know of more people who have requested this feature

2019-10-18 22:21 UTC, Quy commented on administrator/components/com_content/Model/ArticleModel.php
> +	public function featured($pks, $value = 0, $featuredUp = null, $featuredDown = null)
Add params to docblock.

2019-10-18 22:31 UTC, Quy commented on components/com_content/Model/ArticlesModel.php
> +			$query->where('(' . $query->isNullDatetime('fp.featured_up') . ' OR fp.featured_up <= ' . $db->quote($now) . ')');
@richard67 OK here?

2019-10-19 06:33 UTC, opn365 commented
I have tested this item :red_circle: unsuccessfully on 6c727cd2c270974f131ecc6efc53faef692d2dfd<br /><br />after applying patch and click content> articles
An error has occurred.
500 Unknown column 'fp.featured_up' in 'field list' Unknown column 'fp.featured_up' in 'field list'

Setting	Value
PHP Built On	Linux joomlapbf.directrouter.com 2.6.32-754.3.5.el6.x86_64 #1 SMP Tue Aug 14 20:46:41 UTC 2018 x86_64
Database Type	mysql
Database Version	10.2.27-MariaDB
Database Collation	utf8mb4_unicode_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.2.23
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-19 06:36 UTC, opn365 commented
I have tested this item :red_circle: unsuccessfully on 6c727cd2c270974f131ecc6efc53faef692d2dfd<br /><br />after applying patch and click content> articles ( the menu link )
An error has occurred.
500 Unknown column 'fp.featured_up' in 'field list' Unknown column 'fp.featured_up' in 'field list'

However
after applying patch and click content> then the plus icon beside articles then i can create an article
 



Setting	Value
PHP Built On	Linux joomlapbf.directrouter.com 2.6.32-754.3.5.el6.x86_64 #1 SMP Tue Aug 14 20:46:41 UTC 2018 x86_64
Database Type	mysql
Database Version	10.2.27-MariaDB
Database Collation	utf8mb4_unicode_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.2.23
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-19 07:28 UTC, TobsBobs commented
I think you must manually install the needed columns in your database table.

2019-10-19 07:29 UTC, richard67 commented
Exactly, patchtester does not run the update sql, and the database fix button in extensions - manage - database would only run the schema changes but not the insert/update/delete statements.

2019-10-19 07:29 UTC, TobsBobs commented
see here:

administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-08-20.sql

2019-10-19 07:42 UTC, richard67 requested changes

2019-10-19 07:42 UTC, richard67 commented on administrator/components/com_content/Model/ArticlesModel.php
> +				'DISTINCT a.id, a.asset_id, a.title, a.alias, a.checked_out, a.checked_out_time, a.catid' .
```suggestion
				'a.id, a.asset_id, a.title, a.alias, a.checked_out, a.checked_out_time, a.catid' .
```
The distinct has recently been removed in 4.0-dev branch, together with changing the subquery. @SharkyKZ is that correct?

2019-10-19 07:42 UTC, richard67 commented on administrator/components/com_content/Model/FeaturedModel.php
> +				'a.created_by, a.featured, a.featured, fp.featured_up, fp.featured_down, a.language, a.created_by_alias, a.publish_up, a.publish_down, a.note'
```suggestion
				'a.created_by, a.featured, fp.featured_up, fp.featured_down, a.language, a.created_by_alias, a.publish_up, a.publish_down, a.note'
```
One time `a.featured` should be enough ;-)

2019-10-19 07:42 UTC, richard67 commented on components/com_content/Model/ArticlesModel.php
> +			$query->where('(' . $query->isNullDatetime('fp.featured_up') . ' OR fp.featured_up <= ' . $db->quote($now) . ')');
```suggestion
			$query->where('(' . $db->quoteName('fp.featured_up') . ' IS NULL OR fp.featured_up <= ' . $db->quote($now) . ')');
```

2019-10-19 07:42 UTC, richard67 commented on components/com_content/Model/ArticlesModel.php
> +			$query->where('(' . $query->isNullDatetime('fp.featured_down') . ' OR fp.featured_down >= ' . $db->quote($now) . ')');
```suggestion
			$query->where('(' . $db->quoteName('fp.featured_down') . ' IS NULL OR fp.featured_down >= ' . $db->quote($now) . ')');
```

2019-10-19 07:42 UTC, richard67 commented on components/com_content/Model/ArticlesModel.php
> +				$query->where('(' . $query->isNullDatetime('fp.featured_up') . ' OR fp.featured_up <= ' . $db->quote($now) . ')');
```suggestion
				$query->where('(' . $query->quoteName('fp.featured_up') . ' IS NULL OR fp.featured_up <= ' . $db->quote($now) . ')');
```

2019-10-19 07:42 UTC, richard67 commented on components/com_content/Model/ArticlesModel.php
> +				$query->where('(' . $query->isNullDatetime('fp.featured_down') . ' OR fp.featured_down >= ' . $db->quote($now) . ')');
```suggestion
				$query->where('(' . $query->quoteName('fp.featured_down') . ' IS NULL OR fp.featured_down >= ' . $db->quote($now) . ')');
```

2019-10-19 07:42 UTC, richard67 commented on libraries/src/Table/Content.php
> +		if ($this->featured_down && ($this->featured_down < $this->featured_up))
```suggestion
		if ($this->featured_up && $this->featured_down && $this->featured_down < $this->featured_up)
```

2019-10-19 08:23 UTC, eshiol commented on components/com_content/Model/ArticlesModel.php
> +			$query->where('(' . $query->isNullDatetime('fp.featured_up') . ' OR fp.featured_up <= ' . $db->quote($now) . ')');
Are you sure? You have told me to use isNullDatetime on 25 Aug as @Quy suggested.

2019-10-19 08:45 UTC, richard67 commented on components/com_content/Model/ArticlesModel.php
> +			$query->where('(' . $query->isNullDatetime('fp.featured_up') . ' OR fp.featured_up <= ' . $db->quote($now) . ')');
Yes, that was before I have started my recent works on database to allow null values for particular datetime columns. You can see it a bit below in the aricles model file, e.g. here: [https://github.com/joomla/joomla-cms/blob/6c727cd2c270974f131ecc6efc53faef692d2dfd/components/com_content/Model/ArticlesModel.php#L482](https://github.com/joomla/joomla-cms/blob/6c727cd2c270974f131ecc6efc53faef692d2dfd/components/com_content/Model/ArticlesModel.php#L482).

2019-10-19 08:50 UTC, richard67 commented on components/com_content/Model/ArticlesModel.php
> +			$query->where('(' . $query->isNullDatetime('fp.featured_up') . ' OR fp.featured_up <= ' . $db->quote($now) . ')');
Sorry if that causes inconveniences now, but these database changes were necessary for MySQL 8, because in 8 they force more standard conforming server settings and so not allow '0000-00-00 00:00:00' anymore. So I had a bit work in recent 2 months and now much has changed in db regarding datetimes. You could leave the isnulldatetime here, it would work, too, but it is not really necessary anymore. The most important thing is that you PR has to store NULL now in db instead of these old (pseudo-)nulldates. As far as I could see up to now by review, this is the case, so it seems to be good. I will try to find time later today or tomorrow to test your PR, and if necessary I can help with necessary changes, if some.

2019-10-19 10:13 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 04dd1eaf7cca1926600ef8b64bc1bbd8823014a6<br /><br />#pbf19 #jd19it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-19 10:15 UTC, TobsBobs commented
I have tested this item :white_check_mark: successfully on 04dd1eaf7cca1926600ef8b64bc1bbd8823014a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-19 10:16 UTC, TobsBobs commented
This is a nice feature! :)

2019-10-19 10:18 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-19 10:19 UTC, richard67 approved these changes

2019-10-19 10:31 UTC, neotrendch commented
I have tested this item :white_check_mark: successfully on 04dd1eaf7cca1926600ef8b64bc1bbd8823014a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-19 11:06 UTC, ot2sen commented
I have tested this item :white_check_mark: successfully on 04dd1eaf7cca1926600ef8b64bc1bbd8823014a6<br /><br />Retested with the corrections and now the expired gone too. Works well :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-19 14:20 UTC, rmittl commented
I have tested this item :red_circle: unsuccessfully on 04dd1eaf7cca1926600ef8b64bc1bbd8823014a6<br /><br />After applying test patch tester following error appeared in articles view
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-19 14:21 UTC, rmittl commented
![Screenshot 2019-10-19 at 16 15 45](https://user-images.githubusercontent.com/4217742/67146547-6bd56080-f28c-11e9-9624-a71e214d96af.png)

2019-10-19 14:24 UTC, richard67 commented
@rmittl The reason is that this Pull Request contains SQL changes, and the Patchtester does not run those changes. You have to apply the SQL from the update sql script manually e.g. in PypMyAdmin.

See the following comments above:

[https://github.com/joomla/joomla-cms/pull/25979#issuecomment-544110536](https://github.com/joomla/joomla-cms/pull/25979#issuecomment-544110536)
[https://github.com/joomla/joomla-cms/pull/25979#issuecomment-544110620](https://github.com/joomla/joomla-cms/pull/25979#issuecomment-544110620)
[https://github.com/joomla/joomla-cms/pull/25979#issuecomment-544110625](https://github.com/joomla/joomla-cms/pull/25979#issuecomment-544110625)

So please either set your test result back to "I have not tested this item" in the issue tracker, or test again in the right way, e.g. including manual execution of the SQL changes, and set then the appropriate test result in the tracker.

2019-10-19 14:31 UTC, rmittl commented
I have tested this item :white_check_mark: successfully on 04dd1eaf7cca1926600ef8b64bc1bbd8823014a6<br /><br />After apply the database changes, test runs successful.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25979">issues.joomla.org/tracker/joomla-cms/25979</a>.</sub>

2019-10-25 22:43 UTC, wilsonge commented
Thanks for your patience on this over the last 2 years!

2019-10-25 22:43 UTC, merged

2019-10-26 09:32 UTC, WoodyF4u commented
Thanks to everybody who helped to create this feature.
The only thing I have to wait for is the 4.0-Stable.
Then I can use this feature.

2019-10-26 13:01 UTC, richard67 commented
@wilsonge It seems there is an issue, #26829 , related to this PR. When checking the changed files here, I see stuff for handling featureed up and down times to the content table class, but during development of this PR, the 2 new columns have been moved to the `#__content_frontpage`. I can see there is something for reading from this table added to the core content table class, routine load(), but I see nothing for writing these columns back to `#__content_frontpage`. Instead of it I see the handling of the new columns in the check routine as if they would belong to the `#__content` table. Am I blind or do I understand something wrong? Please check and advise.

2020-07-14 13:16 UTC, WoodyF4u commented
Today, I installed Joomla 4.0 beta 2.
There is stuill no option to use the scheduled featured articles.
Is it still nessesary to install that manually or should this be a part of this Beta 2 already?

2020-07-14 14:17 UTC, SharkyKZ commented
@WoodyF4u The feature is already present. But it might be difficult to find. It's in `Publishing` tab. Maybe we should move these fields right under `Featured` field.

2020-07-14 16:41 UTC, brianteeman commented
@SharkyKZ by that logic the start publishing dates should be moved as well

2020-07-14 18:23 UTC, WoodyF4u commented
@SharkyKZ  Thanks for pointing me to the Publishing tab.
I have tested it, but when I add a date and time for Start Featured and Finish Featured and click Save, both fields are empty.
So there is nothing saved and the article will not change in the featured state.
Is it possible that someone else can test it?

2020-07-14 18:25 UTC, WoodyF4u commented
@brianteeman Yes, I think it is fine when the fields are in the Publishing tab.
But it must work and now it doesn't.

2020-07-14 18:32 UTC, brianteeman commented
@WoodyF4u and I forgot that I discovered that the other day and raised an issue #29942

2020-07-14 18:36 UTC, richard67 commented
@WoodyF4u You first have to change the featured state to "Featured". Then you can set the start and end times (featured up and featured down). Then the times are respected when showing it on a featured page. Published up and down should work in the same way, by the way.

2020-07-14 19:16 UTC, WoodyF4u commented
@riochard67 Thanks. That works!
In case you have to set Featured to ON firsat, it would be better when the options for Start Featured and Finish Featured will be vbelow the Featured switch.
Cause there is not any warning that tells the user to switch the Featured state first.

2020-07-14 20:09 UTC, richard67 commented
Yes, it's not very intuitive how it works. Could be really improved.

2020-08-08 10:32 UTC, WoodyF4u commented
Please look at the first screenshpot of this PR. There you see the Featured ON-OFF switch.
When Featured is ON, the two extra fields for scheduling will be visible.
I think that will be the best place for the scheduling option of the Featured articles.

I am not a developer, but I hope someone can fix this for he next beta so we can test it again and maybe approve it for Joomla! 4.