[4.0] Backend - Fix buttons
joomla/joomla-cms pull request #26070
Opened 2019-08-29 18:45 UTC by coolcat-creations

This PR is about to fix the styling of the buttons for rtl and ltr. But it cannot be tested yet because there is some wrong code in the backend which needs to be fixed first.

LTR, regular Bootstrap without icons inside:
![grafik](https://user-images.githubusercontent.com/828371/63966827-69306900-ca9c-11e9-94d2-a27196a81e2d.png)

RTL, regular Bootstrap without icons inside:
![grafik](https://user-images.githubusercontent.com/828371/63966939-a694f680-ca9c-11e9-81f0-12d4db517fc3.png)

Problems appear here:
The Action Button is broken although it should have the same appeareance like the save and close button:
![grafik](https://user-images.githubusercontent.com/828371/63967028-d2b07780-ca9c-11e9-83ae-ff2d49a10557.png)
![grafik](https://user-images.githubusercontent.com/828371/63967047-e065fd00-ca9c-11e9-8e52-7fe94e17a062.png)

The reason for it, is that the Action Button has a completely different semantic than the save and close button. It should be fixed in the code first.

Next Problem appear here:
![grafik](https://user-images.githubusercontent.com/828371/63967150-13a88c00-ca9d-11e9-8a4d-0e0cd8da4d7a.png)
There are 3 Buttons bigger than the other ones. The simple reason is, that ones are using btn-sm class and the others not. The classes should be unified to make the buttons appear the same. It does not make sense to make big buttons smaller or small buttons bigger just to fix this. They should have the same button size class.

This PR unifies the styling of all buttons accross the backend:
- when they use standard bootstrap classes OR
- at least one standard of Joomla Button Code Style 

![grafik](https://user-images.githubusercontent.com/828371/63967333-80bc2180-ca9d-11e9-8ef7-709bee4d59f3.png)

Buttons that stil appear different have to be fixed from a technical perspektive.

After the code part is fixed it may be that this PR needs some small refinement, but first the code needs to be fixed.

2019-08-29 19:32 UTC, Quy commented
Please commit to `4.0-dev` branch.

2019-08-29 19:44 UTC, zero-24 commented
@coolcat-creations I have just moved the branch against 4.0-dev instead of staging so this can actually be merged ;)

2019-08-29 19:59 UTC, coolcat-creations commented
@zero-24 thank you - but first the button-code needs to be fixed somehow...

2019-08-29 20:05 UTC, C-Lodder requested changes

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +  padding: 0.1rem 2.9rem 0.1rem 0.5rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +    padding: 0.3rem 3.2rem 0.3rem 0.8rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +    font-size: 1.3rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +    padding: 0rem 2.5rem 0rem 0.3rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      background: var(--success);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      background: -webkit-linear-gradient(right, var(--success) 0, var(--success) 2rem, #ffffff 2.01rem, #ffffff 100%);
You don't need to use vendor prefixes, this is dealt with automatically by the `autoprefixer` package!!!!

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +        background: var(--success);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +        color: var(--atum-text-dark);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      background: var(--danger);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      background: -webkit-linear-gradient(right, var(--danger) 0, var(--danger) 2rem, #ffffff 2.01rem, #ffffff 100%);
You don't need to use vendor prefixes, this is dealt with automatically by the autoprefixer package!!!!

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +        background: var(--danger);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +        color: var(--atum-text-dark);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      &:after {
`::`

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      &.dropdown-toggle:after {
`::`

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +  &.btn-success {
Duplicate CSS?

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +    background: var(--atum-link-color);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +    background: -webkit-linear-gradient(right, var(--atum-link-color) 0, var(--atum-link-color) 2.4rem, #ffffff 2.401rem, #ffffff 100%);
Stop using vendor prefixes

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      background: var(--atum-link-color);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      color: var(--atum-link-color);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +      color: var(--atum-text-dark);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +  background: var(--atum-bg-light);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +  border: 1px solid $gray-500;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +  color: var(--atum-text-dark);
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +  padding: 0.1rem 0.6rem 0.1rem 3rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +  font-size: 1rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +  line-height: $atum-toolbar-line-height;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    padding: 0rem 0.3rem 0rem 2.5rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    padding: 0.3rem 0.9rem 0.3rem 3.3rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    font-size: 1.3rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    font-size: 0.8rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    height: 2.2rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    line-height: 2.2rem;
Use variables

2019-08-29 20:05 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    span[class*="icon-"]:not(.input-group-text), span[class^="icon-"]:not(.input-group-text),
On second thoughts, please just remove this entire file and start overriding the variables properly

2019-08-29 20:09 UTC, brianteeman commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +          /* margin-right: auto !important;
is this intended to be commented out?

2019-08-29 20:11 UTC, brianteeman commented on administrator/templates/atum/scss/template-rtl.scss
> +        background: linear-gradient(to left, var(--success) 0, var(--success) 2rem, #ffffff 2.01rem, #ffffff 100%);
vendor prefixes ;)

2019-08-29 20:14 UTC, brianteeman commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +      padding: 0rem 0.8rem;
no need to put the unit when it is a zero

2019-08-29 20:15 UTC, C-Lodder requested changes

2019-08-29 20:15 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +    bottom: .85rem;
What are you trying to do here? Vertically align the icon to the middle of the button? If so, then use flexbox

2019-08-29 20:15 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_global.scss
> +.btn-primary:hover {
Why is this here?

2019-08-29 20:17 UTC, brianteeman commented on administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
> +  [class*=' icon-'] {
Why have you removed the class=fa lines?

2019-08-29 20:31 UTC, coolcat-creations commented on administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
> +  [class*=' icon-'] {
I can add them back, I restored code from May which had been deleted so maybe some things need refinement as stated in the description of the PR.

2019-08-29 20:31 UTC, coolcat-creations commented on administrator/templates/atum/scss/blocks/_global.scss
> +.btn-primary:hover {
Will remove it, thanks

2019-08-29 20:32 UTC, coolcat-creations commented on administrator/templates/atum/scss/template-rtl.scss
> +    bottom: .85rem;
The icon should be left center (ltr)  or right center aligned to the button, I will try with flex, but the code of the buttons has to be adjusted anyway before, thank you

2019-08-29 20:33 UTC, coolcat-creations commented on administrator/templates/atum/scss/template-rtl.scss
> +        background: linear-gradient(to left, var(--success) 0, var(--success) 2rem, #ffffff 2.01rem, #ffffff 100%);
what do you mean by that?

2019-08-29 20:33 UTC, coolcat-creations commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +          /* margin-right: auto !important;
thank you will remove

2019-08-29 20:34 UTC, coolcat-creations commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    span[class*="icon-"]:not(.input-group-text), span[class^="icon-"]:not(.input-group-text),
How do you mean?

2019-08-29 20:35 UTC, coolcat-creations reviewed
Thank you for all the comments, before refining the code and fixing the mentioned issues it would be great if the Button code would be fixed, then it's easier to test this PR.

2019-08-29 20:37 UTC, brianteeman commented on administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
> +  [class*=' icon-'] {
well that meant that PR since the merge of the template were lost. This one I knew because I wrote it the other day to fix a bug

2019-08-29 20:38 UTC, brianteeman commented
would be better for you to create issues for the buttons that need fixing

2019-08-29 20:51 UTC, C-Lodder commented on administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss
> +    span[class*="icon-"]:not(.input-group-text), span[class^="icon-"]:not(.input-group-text),
You're pretty much redefining the CSS for the button component. For the majority of it, you only need to override the Bootstrap variables.

2019-08-29 20:52 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +        background: linear-gradient(to left, var(--success) 0, var(--success) 2rem, #ffffff 2.01rem, #ffffff 100%);
@coolcat-creations Remove the vendor prefixes

2019-08-29 20:53 UTC, C-Lodder commented on administrator/templates/atum/scss/template-rtl.scss
> +    bottom: .85rem;
To vertically align something, never use a single `bottom` property, else if the height of the button changes, you will also need to update the `bottom` value. Using flexbox will automatically align it at any height

2019-08-29 20:56 UTC, coolcat-creations commented on administrator/templates/atum/scss/template-rtl.scss
> +    bottom: .85rem;
Thank you Charlie, maybe you can help me to do it better when the button code is fixed? Would be much appreciated.

2019-08-29 20:57 UTC, Hackwar commented
Can you please elaborate what you mean with buttons being broken? Looking at the code, the buttons are pretty much identical, except that the dropdown buttons are wrapped in a div...

2019-08-29 21:26 UTC, coolcat-creations commented
> Can you please elaborate what you mean with buttons being broken? Looking at the code, the buttons are pretty much identical, except that the dropdown buttons are wrapped in a div...

Well I wrote it in the PR at the top... I added it also the the issue, hope that helps. 
The Action Drop Down and the Module dropdown are different from save and close

![grafik](https://user-images.githubusercontent.com/828371/63977464-35613d80-cab4-11e9-8036-6cb207dafb5f.png)

vs 
![grafik](https://user-images.githubusercontent.com/828371/63977520-54f86600-cab4-11e9-95a7-e25e2d8099b6.png)

2019-08-29 21:30 UTC, brianteeman commented
All these buttons have to have an icon?

2019-08-29 21:33 UTC, coolcat-creations commented
> All these buttons have to have an icon?

no they don't have to have an icon, but the install buttons on the control panel have so I suppose to be consistent in the types of buttons. If there is a save button with an icon, all save buttons should have this icon. If the install button has one, all install buttons should have the same. That UX...

2019-08-29 21:41 UTC, brianteeman commented
> If there is a save button with an icon, all save buttons should have this icon. If the install button has one, all install buttons should have the same. That UX...

Of course that is good ux but we have to be able to support extensions that may not have defined an icon for everything. And in many places there is no need for an icon - example the Comment button here on github, the login button in the joomla admin, the documentation link in template styles.

I dont see any solid colour buttons in your first post. So there are no button styles that can be used. You have to have a button in white with a colour bar with an icon. This was **not** part of your design proposal

2019-08-29 21:44 UTC, coolcat-creations commented
This is how regular bs buttons look like, they always look according to the style of the Joomla Buttons. Does not matter that they dont have icons. If they have Icons, the icons will appear in the squared colored area of the button. If there are no icons these squares a empty. this will unify the style of the template. 
![grafik](https://user-images.githubusercontent.com/828371/63978562-e963c800-cab6-11e9-8ccc-ef29d3e7051e.png)

2019-08-29 22:01 UTC, mbabker commented
It’s only unifying the button component use if every button has an icon though.  Otherwise, to me all of those buttons look broken as if something is missing.  If this is the design team coming down with a mandate that every button will have an icon, then so be it, just another decision people are going to either live with or hack around.

Consistency is good, but I feel like there needs to be two supported variations with this design; a button with an icon (which is what the current style is and fits the majority of use cases), and a “plain” style which is the “classic” full color buttons.

2019-08-29 22:08 UTC, brianteeman commented
> This is how regular bs buttons look like, 

No they have no icons and coloured backgrounds not empty squares

> This was not part of your design proposal

2019-08-29 22:09 UTC, coolcat-creations commented
Ok, waiting then for the decision from the design team. I think it looks too colorful and chaotic when all those different button styles are used. Also the current ones (in the plain variation) don't work with icons inside.
![grafik](https://user-images.githubusercontent.com/828371/63979944-7a886e00-caba-11e9-9eac-50d03d852574.png)

2019-08-29 22:10 UTC, brianteeman commented
> Also the current ones (in the plain variation) don't work with icons inside.

Not true

2019-08-29 22:11 UTC, coolcat-creations commented
> No they have no icons and coloured backgrounds not empty squares

There is a misunderstanding. I meant how they look like with this PR. Without this PR they are solid colored and that does not fit to the template. But ok, who is in charge of design currently, maybe we can ask the design team?

2019-08-29 22:12 UTC, coolcat-creations commented
> > Also the current ones (in the plain variation) don't work with icons inside.
> 
> Not true

See my screenshot, thats not how it looks nice...

2019-08-29 22:13 UTC, brianteeman commented
>  Without this PR they are solid colored and that does not fit to the template.

What do you mean by does not fit the template - thats what they were in your design proposal

2019-08-29 22:15 UTC, coolcat-creations commented
And if they have an icon

> > Without this PR they are solid colored and that does not fit to the template.
> 
> What do you mean by does not fit the template - thats what they were in your design proposal

Due to user feedback they were made less bold / screaming than in the design proposal from 2 years ago... so the style should be unified through the template.

2019-08-29 22:23 UTC, brianteeman commented
And where is this feedback. You keep mentioning it but I don't believe it has ever been made public.

2019-08-29 22:26 UTC, mbabker commented
Maybe I’m as blind as I’m considered a troll, but in all honesty the buttons in your screenshot look broken without icons to me.  That button style comes across as needing an icon to make it look right, it all looks off to me with the empty squares.

Defaulting to the icon style is OK.  Add a `btn-noicon-*` variant that takes buttons back to the default full color design (the same way Bootstrap ships the `btn-outline-*` variant) that way someone has to put in the extra effort to use that style but it’s still supported.  I do think the icon style is going to be the primarily used style but I don’t think the icon style needs to be hardcoded and unavoidable.  That’s my only concern with this, not that the design is bad but that it’s forcing specific design elements to always be used when they aren’t needed.

2019-08-30 06:57 UTC, C-Lodder commented
One thing that also caught my eye was that the:

1. Warning / Danger button colours look similar
2. Primary / Secondary colours look very similar

With that in mind, you may as well remove them from the colour array map. Or make them more distinguishable.

2019-08-30 08:25 UTC, coolcat-creations commented
@C-Lodder I'd wait for a suggestion from the design team @brianteeman mentioned. IMHO all the Buttons in backend should follow an equal styling. Not some solid, some white with square color field at the front and others again different. Closing this PR for now until we have a design decision. The issue connected to this should stay open because it's about different markups and this should definetly be fixed.

2019-08-30 08:25 UTC, closed without merging

2019-08-30 10:55 UTC, brianteeman commented
Pretty sure I never said anything about a design team as I have no knowledge of one

2019-08-30 10:56 UTC, coolcat-creations commented
Sorry, was a mistake, @mbabker mentioned a design team.