4.0-dev Implement time field
joomla/joomla-cms pull request #26184
Opened 2019-09-06 08:40 UTC by VladikB

Pull Request for Issue #22140  .

### Summary of Changes

I created new files to rectify the missing of input type="time" with a typical time field. Since IE and Safari don't support this inpit type, on these brwosers it goes to inpu type="text"

### Testing Instructions

a) 1. Go to  administrator\components\com_users\forms. Edit the first field of user.xml file to 

```
name="name"
type="time"
label="COM_USERS_USER_FIELD_NAME_LABEL"
required="true"
size="30"
```
2. Go to Joomla-Backend -> Users ->Manage -> Click on Your User -> try to change it

b) 1. Go to  administrator\components\com_users\forms. Edit the first field of user.xml file to 

```
name="name"
type="time"
label="COM_USERS_USER_FIELD_NAME_LABEL"
required="true"
size="30"
min="08:00"
max="15:00"
```
2. Go to Joomla-Backend -> Users ->Manage -> Click on Your User-> try to change it

c) 1. Go to  administrator\components\com_users\forms. Edit the first field of user.xml file to 

```
name="name"
type="time"
label="COM_USERS_USER_FIELD_NAME_LABEL"
required="true"
size="30"
step="3"
```
2. Go to Joomla-Backend -> Users ->Manage -> Click on Your User-> try to change it

### Expected result

a) The Name field is a time field with hh:mm
b) The Name field is a time field with hh:mm that goes from 08:00 to 15:00
c) The Name field is a time field with hh:mm:ss and seconds can be changed in step of three seconds

### Documentation Changes Required

If this works, I am going to write a documentation since it is a new field type.

2019-09-06 14:29 UTC, roland-d commented
@VladikB Please fix the codestyle issues:

![image](https://user-images.githubusercontent.com/359377/64435855-8203d480-d0c3-11e9-9077-7bc7c1bcb7d0.png)

2019-09-06 15:09 UTC, hans2103 commented
I have tested this item ✅ successfully with Chrome browser
It works as described.

2019-09-06 16:26 UTC, zero-24 requested changes
Some inline coments and most of it are just the since tags 👍

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> + * @since  1.7.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since  1.7.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since  3.2
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since  3.2
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since  3.2
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * Input addon before
Looks like this comment can be removed?

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since  3.7
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since   3.2
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +
please remove this empty line :)

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since   3.2
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since   3.2
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since   1.7.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2019-09-06 16:26 UTC, zero-24 commented on libraries/src/Form/Field/TimeField.php
> +	 * @since 3.7
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2019-09-08 13:23 UTC, coolcat-creations commented
Nice Feature, thank you!!!

2019-09-08 22:27 UTC, dgrammatiko commented
Sorry to ruin the party but this cannot be accepted because it's not supported by the minimum browser compatibility for J4: https://caniuse.com/#feat=input-datetime

2019-09-09 07:06 UTC, roland-d commented
@dgrammatiko The problem being that a text field is not supported?

2019-09-09 07:31 UTC, dgrammatiko commented
@roland-d no the problem is that you cannot rely on the fallback type of text **wihout** some client side validation. Also I think that there should be also a server side validation (input filter).

2019-09-09 08:01 UTC, VladikB commented
"Since IE and Safari don't support this inpit type, on these brwosers it goes to inpu type="text""

2019-09-09 08:18 UTC, dgrammatiko commented
> "Since IE and Safari don't support this input type, on these browsers it goes to input type="text""

So I can then type: `This sucks!` and it will be valid time because there is no client side or server side validation. In other words you're proposing something that in it's current form **is broken**. 
Great, ship it!

2019-09-09 08:21 UTC, dgrammatiko commented
Basically you need this: https://github.com/Dan503/time-input-polyfill

2019-09-09 08:22 UTC, coolcat-creations commented
Would be so great, if we would appreciate new contributions and find ways to make it work instead of shouting at each other and beeing such aggressive.

2019-09-09 08:27 UTC, dgrammatiko commented
@coolcat-creations so, explaining that something is not acceptable in the current state is aggressive?

2019-09-09 08:32 UTC, coolcat-creations commented
It's not what you say, but how you say it @dgrammatiko 
"This sucks!" and "Great, ship it!" ... We are here to create a great product with each other, not to be mad ;-)

2019-09-09 08:44 UTC, brianteeman commented
You should find everything you need to know about the time input and any issues you need to watch out for here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

2019-09-11 08:40 UTC, VladikB commented
@brianteeman Can You please check the language strings?

2019-09-11 08:40 UTC, VladikB commented
@wilsonge Is the added time rule OK like that?

2019-09-11 09:38 UTC, brianteeman commented
> @brianteeman Can You please check the language strings?

Do we even need language strings? Don't the browsers have their own native strings for this?

2019-09-11 10:22 UTC, VladikB commented
> > @brianteeman Can You please check the language strings?
> 
> Do we even need language strings? Don't the browsers have their own native strings for this?

I have no idea

2019-09-11 10:25 UTC, brianteeman commented
create a time field and see what happens when validation is on

2019-09-11 10:35 UTC, VladikB commented
The language strings are primary for the browsers that don't support input type=time. So that if You enter a random text or a false time it won't be accepted and gives the message back.
in browsers that support time You just can't input wrong data.

2019-09-11 10:44 UTC, brianteeman commented
Sorry if I wasnt clear.

Use a browser which supports time and copy the error messages from there to be used in the other browsers

2019-09-11 11:31 UTC, roland-d commented
There is something going sideways here. The language changes are not in relation to what browsers show but these are the message after the server-side validation is done. In case a validation fails, one of these messages are shown.

2019-09-11 11:37 UTC, brianteeman commented
OK here you go and sorry for the confusion and please make sure they are the same frontend and admin

```
JLIB_FORM_FIELD_INVALID_MIN_TIME="The time you entered is before the minimum time."
JLIB_FORM_FIELD_INVALID_MAX_TIME="The time you entered is after the maximum time."
JLIB_FORM_FIELD_INVALID_TIME_INPUT="Invalid time format. Please use hh:mm."
JLIB_FORM_FIELD_INVALID_TIME_INPUT_SECONDS="Invalid time format. Please use hh:mm:ss"
```

2019-09-11 16:41 UTC, infograf768 commented
Tested with the simple example proposed by OP

This is not very useful for language/countries where AM/PM is not used as one has to add these values in the field. One can't enter 13:30 for example, but 01:30 PM
So, not only it is restricted to some browsers but it is also restricted to people familiar with AM/PM

![Screen Shot 2019-09-11 at 18 35 16](https://user-images.githubusercontent.com/869724/64716608-f58e5300-d4c2-11e9-97bb-bf814222bcfb.png)


See: https://www.timeanddate.com/time/am-and-pm.html

> Where Is the 12-Hour Format Used?
> 
> Most countries around the world today use the 24-hour system. However, the 12-hour format, including am and pm, is officially used in a number of countries, including the United States, Canada (except Québec), Australia, New Zealand, and the Philippines.

The fact that it is changed to a text field in Safari for example let's enter anything in that field. No error. No indication of the real format to use, etc.

2019-09-11 16:49 UTC, brianteeman commented on administrator/language/en-GB/en-GB.lib_joomla.ini
> +JLIB_FORM_FIELD_INVALID_TIME_INPUT_SECONDS="Invalid time format. Please use hh:mm:ss"
```suggestion
JLIB_FORM_FIELD_INVALID_TIME_INPUT_SECONDS="Invalid time format. Please use hh:mm:ss."
```

2019-09-11 16:50 UTC, brianteeman commented on language/en-GB/en-GB.lib_joomla.ini
> +JLIB_FORM_FIELD_INVALID_TIME_INPUT_SECONDS="Invalid time format. Please use hh:mm:ss"
```suggestion
JLIB_FORM_FIELD_INVALID_TIME_INPUT_SECONDS="Invalid time format. Please use hh:mm:ss."
```

2019-09-11 16:56 UTC, Quy commented on layouts/joomla/form/field/time.php
> +$attributes = array(
```suggestion
$attributes = [
```

2019-09-11 16:56 UTC, Quy commented on layouts/joomla/form/field/time.php
> +);
```suggestion
];
```

2019-09-11 16:59 UTC, brianteeman commented
> So, not only it is restricted to some browsers but it is also restricted to people familiar with AM/PM

The browsers take the time format from the operating system locale

> The fact that it is changed to a text field in Safari for example let's enter anything in that field. No error. No indication of the real format to use, etc.

Thats easily resolved by adding a pattern in the xml of the field definition. The time input wont use it but the fallback text input will

>            pattern="[0-9]{2}:[0-9]{2}">

https://codepen.io/brianteeman/pen/xxKjPgz

2019-09-11 18:16 UTC, roland-d commented
> No error. No indication of the real format to use, etc.
@infograf768 The test instructions were missing the latest change, so I updated them. Add the `validate="time"` and you will get error messages depending on your error.

2019-09-12 06:44 UTC, infograf768 commented
> The browsers take the time format from the operating system locale

Not so obvious. Here on Macintosh, these are my settings:

<img width="738" alt="Screen Shot 2019-09-12 at 08 26 51" src="https://user-images.githubusercontent.com/869724/64759344-2314e400-d537-11e9-94b2-24299c913c78.png">

I checked my system ocale here.  It is
```
imac-2:~ mac$ defaults read NSGlobalDomain AppleLocale
en_FR
```

Therefore I should get a 24 h for the time field.
It simply does not.

2019-09-12 06:53 UTC, roland-d commented
@infograf768 Which browser are you using? I want to see what I get here.

2019-09-12 06:55 UTC, infograf768 commented
I found the only way to get a 24h time field
I have to set up my Mac as:
<img width="689" alt="Screen Shot 2019-09-12 at 08 52 36" src="https://user-images.githubusercontent.com/869724/64760819-ed71fa00-d53a-11e9-9760-966946d7a36c.png">

Which I don't like as I am used to an English Interface for more than 30 years...

2019-09-12 07:03 UTC, roland-d commented
These are my settings, being Dutch I like it in English as well.
![image](https://user-images.githubusercontent.com/359377/64761135-a89a9300-d53b-11e9-9150-14f8335febeb.png)

This is what I see in Firefox:
![image](https://user-images.githubusercontent.com/359377/64761317-18108280-d53c-11e9-8532-d8b236706053.png)

2019-09-12 07:10 UTC, infograf768 commented
Lucky you... I use Sierra 12.10.6

Concerning validation. I added validate="time" in the xml for user name.
I do  get a warning indeed in Safari, but it flashes so fast I can't even read it.

![error_timefield](https://user-images.githubusercontent.com/869724/64761537-966d2480-d53c-11e9-8db0-44fa3411b183.gif)

2019-09-12 07:13 UTC, roland-d commented
@infograf768 That flashing message is unrelated to this PR. The message is just added the message queue of Joomla.

However for me nothing flashes, all Joomla generated messages stay on screen until I close the message.

2019-09-12 07:15 UTC, VladikB commented
![Time fieldt](https://user-images.githubusercontent.com/45699656/64762094-ccf76f00-d53d-11e9-9efc-b8e2fa7c900b.PNG)

2019-09-12 07:15 UTC, infograf768 commented
@roland-d 
> However for me nothing flashes, all Joomla generated messages stay on screen until I close the message.

Lucky you. I tested other messages in Safari and they do stay on screen until I close, but not this one.

2019-09-12 07:20 UTC, infograf768 commented
@VladikB 
I understand how it behaves in Firefox.
My issue here is with the locale.

2019-09-12 07:29 UTC, roland-d commented
@infograf768 I was testing in Firefox. Doing the same test in Safari, there the message flashes indeed. However it doesn't fully disappear:
![image](https://user-images.githubusercontent.com/359377/64762307-34152380-d53e-11e9-8e50-ce99b27a084e.png)

There are more issues in Safari. When I go to the System dashboard it loads like this:
![image](https://user-images.githubusercontent.com/359377/64762716-f5339d80-d53e-11e9-9bee-a5c938027633.png)

a second later it looks like this:
![image](https://user-images.githubusercontent.com/359377/64762655-d6350b80-d53e-11e9-850a-bbec5107b164.png)

I would say we move the Safari rendering to another discussion as this is not related to the time field.

As for the locale issue, I don't see how we can do something about that because it is browser that acts upon the time input field. To rule anything Joomla out, what shows up if you create a plain html file with just this field? Attached is a zip file with the HTML file with just the input.

[time.zip](https://github.com/joomla/joomla-cms/files/3604224/time.zip)

2019-09-12 07:46 UTC, brianteeman commented
Or test with the codepen I posted yesterday https://codepen.io/brianteeman/pen/xxKjPgz

2019-09-12 08:13 UTC, infograf768 commented
@roland-d 
Joomla is not at stake.
I still get the field with AM/PM with your html in Firefox as it really depends on my Mac settings.

Concerning Safari, I confirm your findings for some of the quickicons modules and agree it may have to be solved separately.

@brianteeman 
Looks like your solution would help entering something which makes sense in the field in Safari, forcing 24h. Evidently the Label needs to be very informative, which may be confusing when the browser displays the time field as one, for example, would not be able to enter `17:00` in your proposal, but `05:00 PM`

![Screen Shot 2019-09-12 at 10 10 29](https://user-images.githubusercontent.com/869724/64766011-958cc080-d545-11e9-9276-8b0edc75e0ba.png)


Note: When one gets the AM/PM field display in Firefox it shows like this:

![Screen Shot 2019-09-12 at 10 06 37](https://user-images.githubusercontent.com/869724/64765775-0c758980-d545-11e9-8a9d-3588a709d9fd.png)

It is not obvious that the last 2 `--` mean entering AM or PM

2019-09-12 08:43 UTC, roland-d commented
The problem of all the dashes can simply be dealt with by providing a default value.

2019-09-12 08:47 UTC, infograf768 commented
> The problem of all the dashes can simply be dealt with by providing a default value.

Would not you need one when the time field is using AM/PM, one when using 24h + one when the time field is a text field?   ;)

2019-09-12 09:11 UTC, roland-d commented
I think you only need 1 default value.

2019-09-13 14:06 UTC, wilsonge commented
This will do as a starting point. I don't think we need the polyfill and the validation looks good. As this is a browser native field I don't think there is much we can be doing to work around the differences - even if there are issues. We can consider trying to normalise in the future i guess. But i don't see this being much different to things like when we added the number field etc way back.

2019-09-13 14:06 UTC, merged

2019-09-13 14:25 UTC, wilsonge commented
@infograf768 i agree btw that before this is used in core we need to evaluate the lack of consistency. However I think allowing people to use native browser fields is a good idea