Enforce2fa
joomla/joomla-cms pull request #26253
Opened 2019-09-10 11:28 UTC by AlexKirndoerfer

### Summary of Changes
Added Enforce Two Factor Authentication as a core plugin.

This plugin is supposed to force the user both in Back- and or Frontend to first setup their Two Factor Authentication before being able to proceed.
The enforcement triggers when the user tries to navigate somewhere else or the page is being reloaded.

### Testing Instructions
1. Setup Joomla! 4.0-dev build
2. In the menu go the System 
3. Click on Plugins
4. Then search for Two Factor Authentication 
5. Enable the Plugin Enforce Two Factor Authentication
6. Enable Two Factor Authentication Plugin of your choice
![image](https://user-images.githubusercontent.com/54268350/64609961-6f90e000-d3ce-11e9-983e-51e38c9871b3.png)

7. Edit the Two Factor Authentication Methode that you choose
8. Select where the Authentication should be enabled Front- or Backend or Both (default is both Front- and Backend)
9. After that click save & close
10. In the menu now go again to System
11. Click on Global Configuration
12. Under the tab Site there should be a button with the label Enforce Two Factor Authentication, enable it
13. Select now where Two Factor Authentication is enforced, note it should be the same setting as in point 8
![image](https://user-images.githubusercontent.com/54268350/64609754-eaa5c680-d3cd-11e9-8b89-f0edc3f05cc6.png)

14. After that click save & close.
15. Now depending on your settings go to the Frontend and log in or try to navigate somewhere else.

### Expected result
You will be redirected to your user edit page until you finished successfully setting up Two Factor Authentication.

### Documentation Changes Required
Description of the feature in the documentation, hence it is a core feature

2019-09-10 11:49 UTC, SharkyKZ commented
Why are plugin options in Global Configuration?

2019-09-10 11:50 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +	private function loadLanguageEnforce2fa(): void
Probably don't need this. Use `$this->loadLanguage()`.

2019-09-10 11:56 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +				switch ($section)
This is not safe. Section values are not meant to be used outside of plugin context and can be anything.

2019-09-10 12:10 UTC, AlexKirndoerfer commented on plugins/system/enforce2fa/enforce2fa.php
> +				switch ($section)
I currently use section to get the parameters from the Two Factor Authentication Plugins which determine whether they are enabled for Front- or Backend or both. True, section could be named anything. Do you have any recommendations how I get those parameters in a different way?

2019-09-10 12:17 UTC, AlexKirndoerfer commented on plugins/system/enforce2fa/enforce2fa.php
> +	private function loadLanguageEnforce2fa(): void
resolved

2019-09-10 17:04 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +				switch ($section)
Not sure, maybe another event could be used to collect plugin options.

2019-09-10 17:41 UTC, Quy commented on administrator/components/com_config/forms/application.xml
> +		>
```suggestion
			>
```

2019-09-10 17:42 UTC, Quy commented on administrator/components/com_config/forms/application.xml
> +		>
```suggestion
			>
```

2019-09-11 04:19 UTC, wilsonge commented
> Why are plugin options in Global Configuration?

I think it maybe makes more sense to put it in User Manager but this is a case where I don't think it necessarily makes sense to have them in the plugin. The plugin exists to force a redirect on every page but it's more like an extension to com_users than it is something truly independent

2019-09-11 04:20 UTC, wilsonge commented on administrator/language/en-GB/en-GB.plg_system_enforce2fa.sys.ini
> +; Enforce2fa language file
Please put the correct headers in this file and the main ini file (see any other file in this directory for an example)

2019-09-11 04:24 UTC, wilsonge commented on plugins/system/enforce2fa/enforce2fa.php
> +				switch ($section)
It's possible the parameter also just doesn't exist. I found this one on JED https://github.com/twizoapi/plugin-verification-joomla/blob/master/TwizoTwoFactorAuth/twizoTwoFactorAuth.xml as an example

2019-09-11 05:21 UTC, SharkyKZ commented
If the redirect is performed by the plugin (it is), the configuration options should be in the plugin. No need to couple it with anything here.

2019-09-11 05:22 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +	protected $autoloadLanguage = true;
This is no longer needed since `$this->loadLanguage()` is used.

2019-09-11 05:23 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +		$id = Factory::getUser()->id;
```suggestion
		$id = $this->app->getIdentity()->id;
```

2019-09-11 05:24 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +		$userId                     = $this->app->getIdentity()->id;
Already have user ID on line 129.

2019-09-11 05:35 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +		$this->loadLanguage('plg_system_enforce2fa', JPATH_ADMINISTRATOR);
```suggestion
		$this->loadLanguage();
```

2019-09-11 05:35 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +			$userId = Factory::getUser()->id;
```suggestion
			$userId = $this->app->getIdentity()->id;
```

2019-09-11 05:36 UTC, SharkyKZ commented on plugins/system/enforce2fa/enforce2fa.php
> +	public function onAfterRoute(): void
It's currently not safe to typehint core events.

2019-09-11 06:57 UTC, roland-d commented on plugins/system/enforce2fa/enforce2fa.php
> +				switch ($section)
So we need to come up with a way to see if any 2FA plugin is enabled for site/admin/both. Can't we enforce `section` as this is what is used in core?

2019-09-11 06:59 UTC, roland-d commented
> If the redirect is performed by the plugin (it is), the configuration options should be in the plugin.

We are doing the same thing with the Recaptcha.

2019-09-11 07:01 UTC, roland-d commented
> Why are plugin options in Global Configuration?

They are not really the plugin options, someone can provide another plugin to enforce 2FA. Just as we do with reCaptcha.

2019-09-11 07:11 UTC, SharkyKZ commented
>They are not really the plugin options, someone can provide another plugin to enforce 2FA. Just as we do with reCaptcha.

Not a valid comparison. Captcha is a plugin group. This is a single system plugin. Unless you want to add `enforce2fa` plugin group and add selector for choosing which plugin from the group to use (please don't), the options should really be in the plugin.

2019-09-11 07:13 UTC, roland-d commented
Looking at how the plugin is now, we might as well move the code into the core and out of the plugin. How is that for an idea?

2019-09-11 08:08 UTC, brianteeman commented on administrator/components/com_config/forms/application.xml
> +		</field>
does it really need two fields. can it not just be one field with options
JNO
COM_CONFIG_FIELD_SITE_ENFORCE_2FA_FIELD_SITE
COM_CONFIG_FIELD_SITE_ENFORCE_2FA_FIELD_ADMIN
COM_CONFIG_FIELD_SITE_ENFORCE_2FA_FIELD_BOTH

2019-09-11 08:15 UTC, brianteeman commented
> Looking at how the plugin is now, we might as well move the code into the core and out of the plugin. How is that for an idea?

I dont see this as functionally any different to the password requirements code which is just part of core without a plugin 

(not comparing the aims etc of the code just the method of implementation)

2019-09-11 08:24 UTC, SharkyKZ commented
>Looking at how the plugin is now, we might as well move the code into the core and out of the plugin. How is that for an idea?

That would work, if you actually want TFA coupled with the application. Looking at existing TFA code I can't really tell whether it's hardcoded intentionally or because our login forms don't support plugins.

2019-09-11 11:27 UTC, AlexKirndoerfer commented
Moved enforce2fa to the core and updated the initial comment

2019-09-11 13:53 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +	 * if so returns ture
```suggestion
	 * if so returns true
```

2019-09-11 13:56 UTC, Quy commented on administrator/components/com_config/forms/application.xml
> +			default="3"
Should be `0`?

2019-09-11 13:57 UTC, roland-d commented on administrator/components/com_config/forms/application.xml
> +			default="3"
Yes it should be :)

2019-09-11 15:30 UTC, mbabker requested changes
There are several architectural concerns with this pull request that should be addressed, even if it works there are things that just look wrong.  This is the type of review that should be made on pull requests, not just commenting on code style issues.

2019-09-11 15:30 UTC, mbabker commented on administrator/components/com_config/forms/application.xml
> +			name="enforce_2fa_options"
This should be an option in com_users, not the global configuration.

2019-09-11 15:30 UTC, mbabker commented on libraries/src/Application/CMSApplication.php
> +	protected function enforce2FA(): bool
Use better method naming.  This implies it is enforcing a 2FA requirement, in fact it is checking if it is required.  So maybe `isTwoFactorAuthenticationRequired()` (avoiding the acronym).

2019-09-11 15:30 UTC, mbabker commented on libraries/src/Application/CMSApplication.php
> +	protected function redirectEnforce2fa(): void
Again, better method naming.  `redirectIfTwoFactorAuthenticationRequired()`

2019-09-11 15:30 UTC, mbabker commented on libraries/src/Application/CMSApplication.php
> +	private function checkUserSetup2FA(int $userId): bool
`hasUserConfiguredTwoFactorAuthentication()`

2019-09-11 15:30 UTC, mbabker commented on libraries/src/Application/CMSApplication.php
> +	private function get2FA(int $userId): ?\stdClass
Shouldn't the 2FA fields be accessible through the `User` object already?

2019-09-11 15:30 UTC, mbabker commented on libraries/src/Application/CMSApplication.php
> +	private function checkEnabled2FAPlugins(): bool
It seems like there should be something in the `PluginHelper` class to determine this, this type of query should not exist as part of the application class.

2019-09-11 15:30 UTC, mbabker commented on libraries/src/Application/CMSApplication.php
> +	private function getPluginParams(): ?array
Again, something that should be done with the `PluginHelper` class.

2019-09-11 16:21 UTC, infograf768 commented on administrator/language/en-GB/en-GB.ini
> +JENFORCE_2FA_REDIRECT_MESSAGE="You were redirected because you are required to set up Two Factor Authentication to continue"
needs period at end of value

2019-09-11 16:21 UTC, infograf768 commented on language/en-GB/en-GB.ini
> +JENFORCE_2FA_REDIRECT_MESSAGE="You were redirected because you are required to set up Two Factor Authentication to continue"
needs period at end of value

2019-09-12 07:40 UTC, AlexKirndoerfer commented on libraries/src/Application/CMSApplication.php
> +	private function checkEnabled2FAPlugins(): bool
So do I understand that right that you want me to move the database checks to the PluginHelper class?

2019-09-12 07:59 UTC, SharkyKZ commented on libraries/src/Application/CMSApplication.php
> +	private function checkEnabled2FAPlugins(): bool
No, you don't need to write queries. You can remove the whole method and use  `PluginHelper::isEnabled('twofactorauth')` instead.

2019-09-12 08:20 UTC, AlexKirndoerfer commented on libraries/src/Application/CMSApplication.php
> +	private function getPluginParams(): ?array
Since in this case I get specific parameters of how the plugins are setup, is there a way to get those with the PluginHelper class as well? Or should I continue to use a database request and move the method to the PluginHelper class?

2019-09-12 08:33 UTC, SharkyKZ commented on libraries/src/Application/CMSApplication.php
> +	private function getPluginParams(): ?array
You can use `PluginHelper::getPlugin('twofactorauth)` to get an array of plugin objects and use their `params` property.

2019-09-12 08:35 UTC, SharkyKZ commented on libraries/src/Application/CMSApplication.php
> +	private function getPluginParams(): ?array
But I still think this is a bad idea (https://github.com/joomla/joomla-cms/pull/26253#discussion_r322699251).

2019-09-12 08:37 UTC, SharkyKZ commented on libraries/src/Application/CMSApplication.php
> +	private function checkEnabled2FAPlugins(): bool
IMO this proxy method is not needed.

2019-09-12 08:53 UTC, wilsonge commented on plugins/system/enforce2fa/enforce2fa.php
> +				switch ($section)
I'm happy to enforce section as the name for this. However if section doesn't exist them we should assume that it's acting across both applications

2019-09-12 09:00 UTC, SharkyKZ commented on libraries/src/Application/CMSApplication.php
> +		$this->loadLanguage();
This is not needed anymore.

2019-09-12 13:53 UTC, Quy commented on administrator/components/com_users/config.xml
> +		>
```suggestion
			>
```

2019-09-12 13:57 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +	 * if so returns true
Combine lines 1163 & 1164 and append to line 1166.

2019-09-12 13:58 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +	 * if any one is empty returns false
Combine lines 1285 & 11286 and append to line 1288.

2019-09-12 22:41 UTC, wilsonge commented on libraries/src/Application/CMSApplication.php
> +		$user = Factory::getApplication()->getIdentity();
you're in the application here. `$this->getIdentity()`

2019-09-13 13:41 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +		if ($option === 'com_users' && in_array($task, array('profile.save', 'profile.apply', 'user.logout', 'user.menulogout'))
```suggestion
		if ($option === 'com_users' && in_array($task, ['profile.save', 'profile.apply', 'user.logout', 'user.menulogout'])
```

2019-09-13 14:32 UTC, wilsonge commented
Cache the result of the plugins in the session so that it's only done on the first page load per user being checked. Should reduce the performance hit.

2019-09-13 14:57 UTC, Quy commented on administrator/language/en-GB/en-GB.com_users.ini
> +COM_USERS_CONFIG_FIELD_ENFORCE_2FA_LABEL="Enforce Two Factor Authentication"
```suggestion
```

2019-09-13 15:02 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +			if (in_array($enforce2faOptions, [1, 3]))
```suggestion
			if (\in_array($enforce2faOptions, [1, 3]))
```

2019-09-13 15:03 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +			if (in_array($enforce2faOptions, [2, 3]))
```suggestion
			if (\in_array($enforce2faOptions, [2, 3]))
```

2019-09-13 15:03 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +		if ($option === 'com_users' && in_array($task, array('profile.save', 'profile.apply', 'user.logout', 'user.menulogout'))
```suggestion
		if ($option === 'com_users' && \in_array($task, ['profile.save', 'profile.apply', 'user.logout', 'user.menulogout'])
```

2019-09-13 15:03 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +			|| ($option === 'com_users' && in_array($task, ['user.save', 'user.edit', 'user.apply', 'user.logout', 'user.menulogout']))
```suggestion
			|| ($option === 'com_users' && \in_array($task, ['user.save', 'user.edit', 'user.apply', 'user.logout', 'user.menulogout']))
```

2019-09-13 15:04 UTC, Quy commented on libraries/src/Application/CMSApplication.php
> +			|| ($option === 'com_login' && in_array($task, ['save', 'edit', 'apply', 'logout', 'menulogout'])))
```suggestion
			|| ($option === 'com_login' && \in_array($task, ['save', 'edit', 'apply', 'logout', 'menulogout'])))
```

2019-09-14 10:23 UTC, AlexKirndoerfer commented
added the use of sessions to determine whether the user has already setup 2fa

2019-10-19 06:39 UTC, ahghatol commented
I have tested this :white_check_mark: successfully on 78df304fbd

2019-10-19 09:59 UTC, fotisoikonomou commented
Issue #26253 was replicated until step 11.
2fa label does not appears at all (step 12) in the system>global configurations> users as expected

![εικόνα](https://user-images.githubusercontent.com/17083807/67143079-302c9d80-f270-11e9-8c03-8abb65359c2a.png)

![εικόνα](https://user-images.githubusercontent.com/17083807/67143092-4a667b80-f270-11e9-83c1-3834128a44b5.png)

2019-10-19 10:12 UTC, tushar33 commented
I have tested this item :white_check_mark: successfully on 3d053939ce91fd7c6bc6e9cd2254ce6122696cd4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26253">issues.joomla.org/tracker/joomla-cms/26253</a>.</sub>

2019-10-19 10:17 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26253">issues.joomla.org/tracker/joomla-cms/26253</a>.</sub>

2019-10-19 21:49 UTC, merged

2019-10-19 21:50 UTC, wilsonge commented
Thankyou again for coding this!

2019-10-19 22:13 UTC, SharkyKZ commented
Still think it's bad idea to use plugin params like this.

2019-10-19 22:21 UTC, wilsonge commented
I'm happy to see us find a way to improve that if we can find something straightforward