[4.0] Installation fixes
joomla/joomla-cms pull request #26265
Opened 2019-09-11 15:03 UTC by wilsonge

Successor PR to https://github.com/joomla/joomla-cms/pull/26250 

- Moves to promises per TODO
- Fixes bug where if token check failed the request still proceeded
- Simplifies installation logic
- Moves to promises/fetch in part of the installer (supported by all required browsers)

### Testing Instructions
Start a joomla 4 installation
In the "databse configuration"-tab enter incorrect database credentials
Click on the "Setup Database Connection" button
Now you should get a view, similar to the screenshot above
Now apply my patch
Retry the installation with incorrect database credentials
Now you should get a view where only the "Database Configuration"-Tab is shown

### Expected result
Only database tab shown for corrections

### Actual result
All installation Tabs are shown. (See screenshot above in PR #26250)

### Documentation Changes Required
None

2019-09-11 17:42 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 6db2cdd0727d323accd1d635a9402a32fcea1dab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26265">issues.joomla.org/tracker/joomla-cms/26265</a>.</sub>

2019-09-11 17:43 UTC, C-Lodder commented
If I rightly remember, Babel doesn't transpile promises.

2019-09-11 17:47 UTC, richard67 commented
@C-Lodder Is `installation/template/js/setup.js` transpiled, too? I've never noticed that.

2019-09-11 17:54 UTC, richard67 commented
As far as I can see, only stuff below `build/media_source` is transpiled, to which the installation setup.js does not belong. So for this PR here it seems to be ok.

2019-09-11 18:08 UTC, C-Lodder commented
@richard67 I think it's separate, but @wilsonge requested that ES2013 JS stayed as part of the CMS to support IE11, and Promises are not part of that spec

2019-09-11 18:09 UTC, richard67 commented
@C-Lodder I see. Well, maybe George changed opinion ;-) But good that you remind him.

2019-09-11 18:12 UTC, richard67 commented
@C-Lodder Well, I just remember IE11 stuff mainly should be kept for 3rd party devs, not for core install, so maybe that's the reason why he uses the promises here.

But I think it could be dangerous: Some people might see it as example which could be used anywhere else and then use it where it should not be used. No idea what's the result if such thing is then transpiled, best would be to have an error, worst would be that it just does nothing.

So I think it is good that you mentioned it here.

2019-09-12 21:00 UTC, wilsonge commented
I dunno. I mean I hadn’t considered whether the installation should work on IE11 if I’m brutally honest. My gut is it shouldn’t. I’m mostly caring about the front end templates (not even the backend). But willing to listen as to if we should just blanket require Babel (currently we aren’t even running Babel or scss on the installer)

2019-09-12 22:27 UTC, brianteeman commented
It probably should work just enough to get to a page that says you cant use ie11 and you need to use one of the other browsers that you have on your machine - and not end up like the login screen which is just blank

2019-09-13 06:47 UTC, C-Lodder commented
Ok. In which case you just need to fix the code style

2019-09-16 08:45 UTC, C-Lodder requested changes

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +        var loaderElement = document.querySelector('joomla-core-loader');
`document.querySelector('joomla-core-loader').remove();`

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +Joomla.checkDbCredentials = function(form) {
Fat arrows

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +        {
code style.

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +      .then(responseData => {
Wrap `responseData` in braces if you're doing it everywhere else

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +      .then(response => response.json())
Wrap `response` in braces if you're doing it everywhere else

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +  var fetchData = {
`const`

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +        {
code style

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +  var form = document.getElementById('adminForm');
`const`

2019-09-16 08:45 UTC, C-Lodder commented on installation/template/js/setup.js
> +  return fetch(Joomla.installationBaseUrl + '?task=installation.dbcheck&format=json', fetchData)
Use string literals

2019-09-20 08:28 UTC, C-Lodder requested changes

2019-09-20 08:28 UTC, C-Lodder commented on installation/template/js/setup.js
> +        var loaderElement = document.querySelector('joomla-core-loader');
```suggestion
        document.querySelector('joomla-core-loader').remove();
```

2019-09-20 08:34 UTC, C-Lodder requested changes

2019-09-20 08:34 UTC, C-Lodder commented on installation/template/js/setup.js
> +        loaderElement.parentNode.removeChild(loaderElement);
```suggestion
```

2019-09-20 08:34 UTC, C-Lodder commented on installation/template/js/setup.js
> +        if (!result)
```suggestion
        if (!result) {
```

2019-09-20 08:34 UTC, C-Lodder commented on installation/template/js/setup.js
> +        if (Joomla.checkFormField(['#jform_db_type', '#jform_db_host', '#jform_db_user', '#jform_db_name']))
```suggestion
        if (Joomla.checkFormField(['#jform_db_type', '#jform_db_host', '#jform_db_user', '#jform_db_name'])) {
```

2019-09-28 01:07 UTC, wilsonge commented on installation/template/js/setup.js
> +        var loaderElement = document.querySelector('joomla-core-loader');
Do we get away without doing `.parent.remove()`?

2019-09-28 08:56 UTC, C-Lodder commented on installation/template/js/setup.js
> +        var loaderElement = document.querySelector('joomla-core-loader');
`parentNode.removeChild` was for older browsers that did not support the `remove()` method on direct elements

2019-10-19 09:23 UTC, nadjak77 commented
after applying the patch I cannot install joomla.
I have the following error :
![image](https://user-images.githubusercontent.com/37655645/67141919-d5407980-f262-11e9-9522-dcd20edcdce8.png)

2019-10-19 09:40 UTC, fotisoikonomou commented
Issue #26265 is not resolved.
Applying wrong database credentials does not appears the expected error message.
Instead, it proceeds with the validation of the database and the installation process.

![#26265 instawrong](https://user-images.githubusercontent.com/17083807/67142820-8c41f280-f26d-11e9-8e38-3f67700c3303.PNG)

2019-10-19 10:17 UTC, richard67 commented
@fotisoikonomou Did you test with the right order of processing? You first have to apply this patch on a 4.0-dev branch of a git clone, or you have to apply it on a 4.0-alpha-12 or nightly build installation, then delete configuration.php and all database tables using PhpMyAdmin or whatever else, then make a new installation with the patched code.

2019-10-19 15:02 UTC, webfeuerflo commented
I have tested this item :white_check_mark: successfully on ca6a552b669221aafcd6a91afc86ca38dafd5e08<br /><br />After adding the missing { in setup.js the patch works and I can only see the db connection tab to correct the connection<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26265">issues.joomla.org/tracker/joomla-cms/26265</a>.</sub>

2020-08-01 17:50 UTC, roland-d commented
@wilsonge Please fix the conflicts

2022-04-06 13:27 UTC, laoneo commented
@wilsonge can you have a look on the conflicts?

2022-06-20 22:34 UTC, closed without merging

2022-06-20 22:35 UTC, wilsonge commented
These conflicts are basically unfixible. If someone wants to pick this up then I'm happy with it