[4.0] Fixed delete installation folder function
joomla/joomla-cms pull request #26276
Opened 2019-09-12 11:34 UTC by Schmidie64

Fixes https://github.com/joomla/joomla-cms/issues/18765 and https://github.com/joomla/joomla-cms/issues/25610

## Summary of Changes
Fixed the remove installation folder function and change the checkbox for removing the folder to an button.
![pr_remove_install_folder](https://user-images.githubusercontent.com/20770106/64780852-bf53e080-d561-11e9-8352-cb8f8be22c08.png)

### Testing Instructions
1. Start the installation of Joomla 4 
2. finish the installation
3. On the "Congratulations"-Page, you can find a Box with the title "We detected development mode" in this box you should see a checkbox where you can select that the installation folder should be deleted after the installation
4. Now check that button and click the "Complete & Open Site / Admin"
5. If you now check your filesystem, the installation folder should still be there.

6. Now remove in your Joomla directory the configuration.php file
7. Now apply my patch
8. Redo the test instructions 
9. Now you should see a button instead of a checkbox.
10. Now click on the button
11. An "alert"-window should now open where you have to confirm that you wanna remove the installation folder
12. Confirm that
13. Now check your filesystem again
14. The installation folder should now be removed.

### Expected result
Installation Folder should be remove if checkbox is "checked"

### Actual result
Installation Folder is not removed.

### Documentation Changes Required
Maybe not sure :)

@roland-d @wilsonge

2019-09-12 11:39 UTC, brianteeman commented on installation/language/en-GB/en-GB.ini
> +INSTL_REMOVE_INST_FOLDER="Are you absolutely sure you want to delete the installation folder? The folder cannot be restored afterwards!"
let's be consistent with other similar strings please

```suggestion
INSTL_REMOVE_INST_FOLDER="Are you sure you want to delete? Confirming will permanently delete the installation folder"
```

2019-09-12 11:41 UTC, brianteeman commented on installation/tmpl/remove/default.php
> +						<strong><?php echo Text::_('INSTL_SITE_DEVMODE_LABEL'); ?></strong><br>
please use css instead of strong and br

2019-09-12 11:41 UTC, brianteeman commented on installation/tmpl/remove/default.php
> +                        <button id="removeInstallationFolder" class="btn btn-danger">Remove installation folder</button><br>
please use css instead of br

2019-09-12 12:08 UTC, Schmidie64 commented
I change the styling from html elements to css style and change the language value you mentioned.

2019-09-12 13:16 UTC, C-Lodder commented on installation/template/js/remove.js
> +			let confirm = window.confirm(Joomla.Text._('INSTL_REMOVE_INST_FOLDER'));
I would refrain from using `windows.confirm` to ask for confirmation. Users can prevent alerts like these from displaying.
Use a custom confirmation modal

2019-09-12 13:21 UTC, C-Lodder commented on installation/template/js/remove.js
> +							document.getElementById('customInstallation').remove();
`.remove()` is part of the DOM, so once the installation gets transpiled, Babel won't do anything with this.
Please use:

```
const customInstallation = document.getElementById('customInstallation');
customInstallation.parentNode.removeChild(customInstallation);
```

2019-09-12 13:22 UTC, C-Lodder commented on installation/template/js/remove.js
> +							document.getElementById('removeInstallationTab').remove();
Same as comment above

2019-09-12 13:22 UTC, C-Lodder commented on installation/tmpl/remove/default.php
> +						<span style="font-weight: bold; margin-bottom: 1em"><?php echo Text::_('INSTL_SITE_DEVMODE_LABEL'); ?></span>
Please don't use inline styling

2019-09-12 13:22 UTC, C-Lodder commented on installation/tmpl/remove/default.php
> +                        <button id="removeInstallationFolder" class="btn btn-danger" style="margin-bottom: 1em">Remove installation folder</button>
Please don't use inline styling

2019-09-12 13:23 UTC, C-Lodder commented on robots.txt.dist
> -# If the Joomla site is installed within a folder
Why is this file being removed?

2019-09-12 13:24 UTC, C-Lodder commented on installation/template/js/remove.js
> +					onSuccess: function (response, xhr) {
No need to pass function parameters if you're not using them

2019-09-12 13:45 UTC, Schmidie64 commented on robots.txt.dist
> -# If the Joomla site is installed within a folder
The file got accident in a previous commit.

2019-09-12 14:05 UTC, C-Lodder commented on installation/template/js/remove.js
> +						console.log(xhr);
Display an alert of some sort. A non technical user won't know to check their browser console

2019-09-12 14:05 UTC, C-Lodder commented on installation/template/js/remove.js
>  	document.getElementById('installLanguagesButton').addEventListener('click', function(e) {
Use fat arrows

2019-09-12 14:05 UTC, C-Lodder commented on installation/template/js/remove.js
> +					onError: function (xhr) {
Use fat arrows

2019-09-12 14:06 UTC, C-Lodder commented on installation/template/js/remove.js
> +					onSuccess: function (response, xhr) {
Also, use fat arrows

2019-09-12 14:06 UTC, C-Lodder commented on installation/template/js/remove.js
> +		.addEventListener('click', function (e) {
Use fat arrows

2019-09-12 14:09 UTC, C-Lodder commented on installation/template/scss/template.scss
> +#removeInstallationFolder{
You can probably just use the `mb-1` and `text-bold` classes instead of this SCSS

2019-09-12 14:10 UTC, C-Lodder commented on installation/template/js/remove.js
> +					onSuccess: function () {
Use fat arrows

2019-09-12 15:42 UTC, brianteeman commented on installation/template/js/remove.js
> +			let confirm = window.confirm(Joomla.Text._('INSTL_REMOVE_INST_FOLDER'));
We use window.confirm in lots of places in Joomla - this is fine

2019-09-12 16:13 UTC, C-Lodder commented on installation/template/js/remove.js
> +			let confirm = window.confirm(Joomla.Text._('INSTL_REMOVE_INST_FOLDER'));
@brianteeman fair enough, but it's bad practice

2019-09-12 22:28 UTC, wilsonge commented on installation/template/js/remove.js
> +		.addEventListener('click', function (e) {
As you pointed out in my installation PR we're not bablifying these PRs so not using fat arrows is fine for now. If we decide to move to es6 in these files we can do it in a subsequent PR

2019-09-12 22:30 UTC, wilsonge commented on robots.txt.dist
> -# If the Joomla site is installed within a folder
This one is needed - let's add it back please

2019-09-12 22:33 UTC, brianteeman commented on installation/language/en-GB/en-GB.ini
> +INSTL_REMOVE_INST_FOLDER="Are you sure you want to delete? Confirming will permanently delete the installation folder"
```suggestion
INSTL_REMOVE_INST_FOLDER="Are you sure you want to delete? Confirming will permanently delete the installation folder."
```

2019-09-12 22:35 UTC, brianteeman commented on installation/template/scss/template.scss
> +  font-weight: bold;
you really should be using classes not ids if at all possible and I'm pretty sure it is here

2019-09-13 06:52 UTC, C-Lodder commented on installation/template/js/remove.js
> +		.addEventListener('click', function (e) {
The installation is already half ES5 and half ES6

2019-09-13 06:53 UTC, C-Lodder commented on installation/template/js/remove.js
> +							document.getElementById('customInstallation').remove();
Can be reverted as other PR's are using ES6 featires

2019-09-14 19:57 UTC, brianteeman commented on installation/tmpl/remove/default.php
>  						<div class="form-check">
As you have removed the checkbox this entire div can be removed as can the language string as its not relevant any more

2019-09-14 20:03 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on 70ccd45b7c8fbac471fee34673a983b2b2ce2291<br /><br />The removal begins and the contents of installation/src are removed and the a 500 error appears<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26276">issues.joomla.org/tracker/joomla-cms/26276</a>.</sub>

2019-09-15 14:30 UTC, Schmidie64 commented
@brianteeman i think i fixed your mentioned error.

2019-09-15 19:32 UTC, richard67 commented on robots.txt.dist
> -# If the Joomla site is installed within a folder
@Schmidie64 Please add back the robots.txt.dist file. It should not be deleted.

2019-09-15 19:33 UTC, richard67 reviewed
Please add back the robots.txt.dist file. It should not be deleted.

2019-09-15 19:39 UTC, Schmidie64 commented
The robots.txt.dist should be in my pr. I commited the File in one of my Last commits.

2019-09-15 19:48 UTC, richard67 commented
@Schmidie64 Go to [https://github.com/joomla/joomla-cms/pull/26276/files](https://github.com/joomla/joomla-cms/pull/26276/files)

![snap-1](https://user-images.githubusercontent.com/7413183/64926811-6787d480-d802-11e9-9cb4-12b1dc94dc29.png)

and scroll down:

![snap-2](https://user-images.githubusercontent.com/7413183/64926812-6e164c00-d802-11e9-8ed8-d0a6ece1c204.png)

You will see the file is still deleted by your PR, the merge of the 4.0-dev branch into yours did not help. You have to explicitely add it back in your branch.

2019-09-15 19:59 UTC, Schmidie64 commented
Now the robots.txt.dist is definitely inside my branch.

2019-09-15 20:02 UTC, richard67 commented
@Schmidie64 Correct, looks good now.
@C-Lodder Could you check if your remarks have been resolved, too?

2019-09-15 20:05 UTC, richard67 requested changes
Code style: Fix indentation.

2019-09-15 20:05 UTC, richard67 commented on installation/tmpl/remove/default.php
> +                        <button class="btn btn-danger mb-1" id="removeInstallationFolder">Remove installation folder</button>
```suggestion
					<button class="btn btn-danger mb-1" id="removeInstallationFolder">Remove installation folder</button>
```

2019-09-15 20:05 UTC, richard67 commented on installation/tmpl/remove/default.php
> +						<span class="mb-1 font-weight-bold"><?php echo Text::_('INSTL_SITE_DEVMODE_LABEL'); ?></span>
```suggestion
					<span class="mb-1 font-weight-bold"><?php echo Text::_('INSTL_SITE_DEVMODE_LABEL'); ?></span>
```

2019-09-15 20:25 UTC, richard67 commented on installation/tmpl/remove/default.php
> +                        <button class="btn btn-danger mb-1" id="removeInstallationFolder">Remove installation folder</button>
And now this one :smile:

2019-09-15 20:31 UTC, richard67 commented
@wilsonge It could be that the changes in this PR require also changes in system tests, file `tests/Codeception/acceptance/install/InstallCest.php`. At least drone log says installation with removal of the installation folder fails in mysql system test. Could you check that? Maybe it has other reasons than this PR?

2019-09-15 21:24 UTC, richard67 commented on installation/tmpl/remove/default.php
> +                        <button class="btn btn-danger mb-1" id="removeInstallationFolder">Remove installation folder</button>
@Schmidie64 Seems you missed this one. Maybe my fault because I proposed my changes in the wrong order.

2019-09-15 21:44 UTC, richard67 reviewed
In the american language file is missing language string `INSTL_REMOVE_INST_FOLDER`, which is present in the English file, see here [https://github.com/joomla/joomla-cms/blob/0beac2c50e1fcdb2babe048126fe830a5852b583/installation/language/en-US/en-US.ini#L112](https://github.com/joomla/joomla-cms/blob/0beac2c50e1fcdb2babe048126fe830a5852b583/installation/language/en-US/en-US.ini#L112) for the American and here [https://github.com/joomla/joomla-cms/blob/0beac2c50e1fcdb2babe048126fe830a5852b583/installation/language/en-GB/en-GB.ini#L112](https://github.com/joomla/joomla-cms/blob/0beac2c50e1fcdb2babe048126fe830a5852b583/installation/language/en-GB/en-GB.ini#L112) for the English file.

Which one is correct?

And there is still a code stype change (indention) left from my previous review.

2019-09-16 06:23 UTC, Schmidie64 commented
Now the language string is also in the en-US Language file.

2019-09-16 16:44 UTC, richard67 requested changes
Sorry, my mistake: When I suggested code style change for correct indentation in file `installation/tmpl/remove/default.php`, I had not noticed that the span and the button are inside a div, so I suggested 1 tab less than needed for lines 88 and 89. Could you fix that? Again sorry because my mistake. I promise to test this PR later.

2019-09-16 16:44 UTC, richard67 commented on installation/tmpl/remove/default.php
> +					<span class="mb-1 font-weight-bold"><?php echo Text::_('INSTL_SITE_DEVMODE_LABEL'); ?></span>
```suggestion
						<span class="mb-1 font-weight-bold"><?php echo Text::_('INSTL_SITE_DEVMODE_LABEL'); ?></span>
```

2019-09-16 16:44 UTC, richard67 commented on installation/tmpl/remove/default.php
> +					<button class="btn btn-danger mb-1" id="removeInstallationFolder">Remove installation folder</button>
```suggestion
						<button class="btn btn-danger mb-1" id="removeInstallationFolder">Remove installation folder</button>
```

2019-09-16 17:04 UTC, Quy commented on installation/tmpl/remove/default.php
> +					<button class="btn btn-danger mb-1" id="removeInstallationFolder">Remove installation folder</button>
Please use language string `Remove installation folder`.

2019-09-16 17:48 UTC, richard67 commented on installation/tmpl/remove/default.php
> +					<button class="btn btn-danger mb-1" id="removeInstallationFolder">Remove installation folder</button>
That's right, it should be a translatable language string. Pity I haven't seen that before (blush).

2019-09-17 15:24 UTC, Quy commented on installation/tmpl/remove/default.php
> +					<button class="btn btn-danger mb-1" id="removeInstallationFolder"><?php echo Text::_('INSTL_SITE_REMOVE_BUTTON')?></button>
```suggestion
					<button class="btn btn-danger mb-1" id="removeInstallationFolder"><?php echo Text::_('INSTL_SITE_REMOVE_BUTTON'); ?></button>
```

2019-09-17 16:38 UTC, richard67 reviewed
1 tab more indentation because button is inside the div. Same for the span in previous line.

2019-09-17 16:38 UTC, richard67 commented on installation/tmpl/remove/default.php
> +					<button class="btn btn-danger mb-1" id="removeInstallationFolder"><?php echo Text::_('INSTL_SITE_REMOVE_BUTTON'); ?></button>
```suggestion
						<button class="btn btn-danger mb-1" id="removeInstallationFolder"><?php echo Text::_('INSTL_SITE_REMOVE_BUTTON'); ?></button>
```

2019-09-17 16:52 UTC, richard67 requested changes

2019-09-17 16:52 UTC, richard67 commented on installation/tmpl/remove/default.php
> +					<span class="mb-1 font-weight-bold"><?php echo Text::_('INSTL_SITE_DEVMODE_LABEL'); ?></span>
@Schmidie64 This one you have forgotten, it seems.

2019-09-17 17:06 UTC, richard67 reviewed
Now it looks nice. I hope I did not miss something. Will test tonight.

2019-09-17 17:59 UTC, wilsonge commented
Correct system tests will need amending

2019-09-17 18:02 UTC, richard67 requested changes

2019-09-17 18:02 UTC, richard67 commented on installation/template/js/remove.js
> +if (document.getElementById('removeInstallationFolder')) {
Ah, I forgot something: Empty line before the "if" which was deleted should be added back. Code style.

```suggestion

if (document.getElementById('removeInstallationFolder')) {
```

2019-09-17 18:06 UTC, richard67 commented
> 
> 
> Correct system tests will need amending

@wilsonge And that means? Amending by who and when? Now by author of this PR, or later by whomever? I ask because I have tested this PR now with success, but not sure if I shall give a good test result because the PR might break the system test. On the other hand I think we should not bother contributors with the tests if it is too comlicated. Please decide if my good test is valid or not.

2019-09-17 18:07 UTC, richard67 approved these changes

2019-09-17 18:09 UTC, Schmidie64 commented
The continuous-integration test is not failing because of this pr. In the file /administrator/components/com_finder/Indexer/Indexer.php is a phpdoc error but i don't think that this pr should fix this. Because it's a completely different part of Joomla.

2019-09-17 18:15 UTC, alikon commented
this drone issues is biting us today  more than legit and have nothing to do with this pr 
the starting cause is my CS fault with this pr #25884 for which there is already a pr #26346
so simply ignore this "silly drone "

2019-09-17 18:32 UTC, richard67 commented
The current drone error is code style fixed by PR #26346 , I know that.

But yesterday or Sunday there was not this code style error but a system test which looked related. Am not good enough in system tests to judge that. Anyway, I am sure when I give good test result and it is wrong, George will tell us.

2019-09-17 18:39 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on ac209a380b343b80086f4ce7527600df4770add6<br /><br />Test 1: As described in the instructions => OK, installation folder deleted with this PR and not deleted without this PR.
Test 2: Same as before, but in the confirmation dialog chosen "Cancel" => OK, installation folder not deleted.

If there is something to be fixed in system tests because check box has changed to button, it should be done with another PR. @wilsonge please protest if I'm wrong with that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26276">issues.joomla.org/tracker/joomla-cms/26276</a>.</sub>

2019-09-17 18:42 UTC, brianteeman commented
https://github.com/joomla/joomla-cms/blob/4.0-dev/tests/Codeception/acceptance/install/InstallCest.php

2019-09-17 19:03 UTC, richard67 commented
@brianteeman Yes, I saw that, that's why I got curious about the tests.

I saw now the test is defined here: [https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php#L350](https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php#L350). It seems at least the comment in that test is wrong because it already speaks about a button but seems to be older than this PR here.

Brian, what do you think? This PR is good as it is?

2019-09-17 19:08 UTC, brianteeman commented
As @wilsonge said - the tests need to be fixed

2019-09-17 19:13 UTC, richard67 commented
@brianteeman Yes, I did read it, but it was not clear to me if someone shall do that later or if the author of this PR should do it, and if it is a requirement for giving this PR a good test. So I am really not sure if I could give it a good test like I did, or if I shouldn't have done that.

2019-09-17 19:19 UTC, Quy commented on installation/language/en-GB/en-GB.ini
> +INSTL_SITE_REMOVE_BUTTON="Remove installation folder"
Let's use this existing language string instead of adding a new one. 
`INSTL_COMPLETE_REMOVE_FOLDER`

2019-09-17 19:49 UTC, Quy commented on installation/src/Controller/InstallationController.php
> +use Joomla\CMS\Factory;
```suggestion
```

2019-09-17 19:49 UTC, Quy commented on installation/src/Controller/InstallationController.php
> +use Joomla\CMS\Factory;
```suggestion
```

2019-09-17 19:52 UTC, Quy commented on installation/template/index.php
> +Text::script('INSTL_REMOVE_INST_FOLDER');
These 2 entries should not be here as they are not applicable with the comment. Add below in their own section.

2019-09-17 20:00 UTC, richard67 commented
I have not tested this item.<br /><br />Due to valid review comments by @Quy which require further changes I set back my test result to not tested. Later when review comments have been applied and it is clarified what to do with the system test I will test again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26276">issues.joomla.org/tracker/joomla-cms/26276</a>.</sub>

2019-09-18 20:25 UTC, richard67 requested changes

2019-09-18 20:25 UTC, richard67 commented on installation/tmpl/remove/default.php
> +						<button class="btn btn-danger mb-1" id="removeInstallationFolder"><?php echo Text::_('INSTL_SITE_REMOVE_BUTTON'); ?></button>
```suggestion
						<button class="btn btn-danger mb-1" id="removeInstallationFolder"><?php echo Text::_('INSTL_COMPLETE_REMOVE_FOLDER'); ?></button>
```

2019-09-19 08:12 UTC, infograf768 commented on installation/template/index.php
> +// Load strings for frontend translations
Frontend?

2019-09-19 16:16 UTC, merged

2019-09-19 16:16 UTC, wilsonge commented
Thanks!

2019-09-21 20:08 UTC, richard67 commented
@Schmidie64 Thanks for the nice button :-) I hope our reviews and all that have not been too much for you. But if there is something we could improve on that, let us know. You can e.g. get my website in my GitHub profile and there use the contact form if you have suggestions. I'll forward that to the JBS (Joomla Bug Squad) Team.

Thanks for your PR, and hope to see you contributing again from time to time. Ah and if nothing else to do and a bit bored: We always need testers for other PRs, it just needs to use Joomla for that ;-)