[4.0] Separate core.js into multiple files
joomla/joomla-cms pull request #26300
Opened 2019-09-14 13:05 UTC by HLeithner

There are 2 reasons for this PR. First get core.js more module and split into multiple files for better maintainability. The second is a copyright issue reported by @brianteeman for the webcomponents part of the core.js

### Summary of Changes
Make it possible to split concat javascript files into a main file based on the directory name.
Add change history in git commits to preserve copyright and change information.

### Testing Instructions
you need to run npm install,
test Joomla core functionality like
* javascript translations
* check error  messages creation in forms / ajax forms
* check webcomponents loaded correctly  

### Expected result
works

### Actual result
works

2019-09-14 13:12 UTC, brianteeman commented
Thanks for dealing with this.

2019-09-14 13:24 UTC, C-Lodder commented on build/media_source/system/js/core.es6/message.es6
> +        [].slice.call(Object.keys(messages)).forEach((type) => {
Probably a copy and paste but `[].slice.call` isnt needed here as Object.keys() already returns an array

2019-09-14 13:36 UTC, HLeithner commented on build/media_source/system/js/core.es6/message.es6
> +        [].slice.call(Object.keys(messages)).forEach((type) => {
It's copy paste and I would like to keep this PR only for this split and copyright issue. We can create a new PR afterwards.

2019-09-14 15:32 UTC, dgrammatiko commented on build/media_source/system/js/core.es6/message.es6
> +  Joomla.ajaxErrorsMessages = (xhr, textStatus) => {
@HLeithner this doesn't belong here but rather in the Ajax.es6

2019-09-14 18:32 UTC, dgrammatiko commented on build/media_source/system/js/core.es6/customevent.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
The copyright here is wrong. The code belongs to Mozilla as it is noted in line 9

2019-09-14 18:35 UTC, dgrammatiko commented
I think you are also missing this:
```js
       // Only define the Joomla namespace if not defined.
	window.Joomla = window.Joomla || {};
```

2019-09-14 18:38 UTC, brianteeman commented on build/media_source/system/js/core.es6/customevent.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
Yikes - if that is how you have been commenting that code is copyright someone else then @HLeithner and myself have to conduct an even bigger review to make sure we are not abusing someones copyright.

Luckily in this specific case the copyright statement is correct. 

All code samples on mdn are public domain 

> Code samples added on or after August 20, 2010 are in the public domain (CC0). No licensing notice is necessary, 

And it is changed significantly to add our own copyright

2019-09-14 21:39 UTC, dgrammatiko commented on build/media_source/system/js/core.es6/customevent.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
> And it is changed significantly to add our own copyright

No, the code was copy/paste. It's one of the countless polyfills than MDN has on their site (provided by **ALL** the browser vendors (thus the public domain)

2019-09-14 21:50 UTC, brianteeman commented on build/media_source/system/js/core.es6/customevent.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
I assume you are referring to this exact polyfill 
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill

Maybe you copy & pasted it but it is significantly changed

2019-09-15 12:45 UTC, HLeithner commented on build/media_source/system/js/core.es6/message.es6
> +  Joomla.ajaxErrorsMessages = (xhr, textStatus) => {
I moved it thx

2019-09-15 12:47 UTC, HLeithner commented on build/media_source/system/js/core.es6/customevent.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
Brian has more knowledge about this copyright thing then me so I trust him and keep it the way it is. thx

2019-09-15 12:51 UTC, HLeithner commented
> I think you are also missing this:
> 
> ```js
>        // Only define the Joomla namespace if not defined.
> 	window.Joomla = window.Joomla || {};
> ```

This is in the core.es6.js file in line 7.

2019-09-16 08:38 UTC, C-Lodder commented on build/media_source/system/js/core.es6/customevent.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
Code snippets from MDN after Aug 2010 are licensed under CC0 (https://creativecommons.org/publicdomain/zero/1.0/)

2019-09-17 12:58 UTC, HLeithner commented on build/media_source/system/js/core.es6/customevent.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
---
Do I have to attribute the person who applied CC0 to their work?

No, there is no legal requirement that you attribute the affirmer, only an expectation that you will voluntarily do so if requested. The CC0 deed provides HTML code that can be copy and pasted into your webpage to easily cite the author and the work, if that information has been provided by the affirmer.
---

So this is resolved, thx

2020-01-09 20:21 UTC, brianteeman commented
@HLeithner can you resolve the conflicts so we can get this merged and resolve the copyright issue please

2020-01-10 09:24 UTC, HLeithner commented
I will try to resolve this when I have time... it's a bit more work then expected...

2020-02-09 17:02 UTC, wilsonge commented
@HLeithner friendly reminder on this one

2020-02-14 18:27 UTC, brianteeman commented
@HLeithner could you resolve the conflicts please so that we can get this merged and resolve the copyright issue asap

2020-04-12 17:36 UTC, brianteeman commented
@HLeithner @wilsonge I am marking this as a beta blocker because of the copyright issue

2020-04-18 17:35 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on dac63318a6c42b1d326a13273c753817499854dd<br /><br />Functionality works as expected after applying the PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26300">issues.joomla.org/tracker/joomla-cms/26300</a>.</sub>

2020-04-18 17:36 UTC, jwaisner commented
@HLeithner Drone is failing in MySQL and JS. Can you take a look to see if it is related to your PR?

2020-04-18 17:50 UTC, C-Lodder requested changes

2020-04-18 17:50 UTC, C-Lodder commented on build/media_source/system/js/core.es6.js
>  ((Joomla, document) => {
```suggestion
((Joomla) => {
```

2020-04-18 17:50 UTC, C-Lodder commented on build/media_source/system/js/core.es6.js
```suggestion
```

2020-04-19 06:11 UTC, HLeithner commented on build/media_source/system/js/core.es6.js
>  ((Joomla, document) => {
In the last line we call `})(Joomla, document);` document should be removed there too?

2020-04-19 07:02 UTC, C-Lodder commented on build/media_source/system/js/core.es6.js
>  ((Joomla, document) => {
yup

2020-04-20 15:26 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on bbe016c34977e22981defcd3b5f8fee9e91308cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26300">issues.joomla.org/tracker/joomla-cms/26300</a>.</sub>

2020-04-21 13:27 UTC, infograf768 commented on build/media_source/system/js/core.es6/ajax.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
I guess 2020 in all files concerned

2020-04-21 13:31 UTC, HLeithner commented on build/media_source/system/js/core.es6/ajax.es6
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
This will be updated automatically while building the release

2020-04-21 20:18 UTC, chmst commented
I have tested this item :white_check_mark: successfully on bbe016c34977e22981defcd3b5f8fee9e91308cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26300">issues.joomla.org/tracker/joomla-cms/26300</a>.</sub>

2020-04-21 20:20 UTC, jwaisner commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26300">issues.joomla.org/tracker/joomla-cms/26300</a>.</sub>

2020-04-26 13:41 UTC, merged

2020-04-26 13:41 UTC, wilsonge commented
Thankyou for dealing with this @HLeithner !

2020-04-26 17:18 UTC, HLeithner commented
Finally YaY thanks!