[4.0] [WiP] [com_redirect] Fix default value for not nullable datetime columns
joomla/joomla-cms pull request #26381
Opened 2019-09-22 20:36 UTC by richard67

Pull Request for Issue # .

### Summary of Changes

This PR fixes all datetime columns of the `#__redirect_links` database table so there will not be any `Invalid value '0000-00-00 00:00:00' for datetime` error anymore on MySQL 5.7 or later when strict mode is enabled.

Currently this table only contains 2 datetime columns, `created`and `modified`. Those will be handled like the same columns of the `#__banners` table in PR #26372 , i.e. they will get default value = `CURRENT_TIMESTAMP`.

The default value is only used when inserting new records without specifying values for that particular column. For the not nullable columns mentioned above we can use `CURRENT_TIMESTAMP` for both kinds of databases. It will be the timestamp in session time zone (which we set to UTC so all is ok) at beginning of a transaction, i.e. if we insert a new record into the `#__redirect_links` without specifying `created` and `modified`, both will be set to the same point of time. We already do that in PHP so modified is always equal to created when never modified.

When updating old records with pseudo-null datetimes '0000-00-00 00:00:00' on mySQL or the minimum timestamp value '1970-01-01 00:00:00' which we abused as a kind of a pseudo null date on PostgreSQL, the update sql modified by this PR will

1. Set created time to a fixed time later than the date mentioned here if it has that date ('0000-00-00 00:00:00' on mySQL '1970-01-01 00:00:00' on PostgreSQL). This PR uses the **Birthday of Joomla** as this constant value, i.e. '2005-08-17 00:00:00'. **Feel free to make other suggestions**, but I think there will not be any redirect link or article or whatever in Joomla which has been created before Joomla was born .. or do we have to support updates from Mambo still? ;-)
2. After that, set the modified time to the value of the created time. This makes sure that modified time is equal to created time if the redirect link has never been modified.

### Testing Instructions

Please wait with testing until title does not contain "[WiP]" (work in progress) anymore, and status on GitHub is not draft anymore.

I want to wait with this PR here until review of PR #26372 has confirmed that we will handle the `created` and `modified` columns of whatever tables in this way.

Testers please report back the database kind (MySQL or PostgreSQL) on which you have tested.

If you have both MySQL and PostgreSQL, please test on both if possible.

**Test 1: New installation**

1. Apply the patch on a clean 4.0-dev branch using git or merging manually, or apply it on an installation of current 4.0-dev using patchtester.
2. If used patchtester on an existing installation in step 1, delete file `configuration.php` and delete all Joomla database tables in PhpMyAdmin or PhpPgAdmin (depending on your database type).
3. Do a new installation, login to backend, confirm the statistics dialog, go to global config and set error reporting to maximum or development in server settings.
4. Play around with com_redirect, create some links, modify some, ...
5. After any action, check in your database the relevant `datetime`/`timestamp without timezone` columns.

Result: See section "Expected result" below.

**Test 2: Update sql script**

1. Install a clean clean 4.0-dev, login to backend, confirm the statistics dialog, go to global config and set error reporting to maximum or development in server settings.
2. Apply the changes from this PR e.g. manually or with patch tester.
3. Open PhpMyAdmin or PhpPgAdmin (depending on your database type), select your database and then go to the SQL command input.
4. On MySQL copy the first line of file `installation/sql/mysql/joomla.sql` into the SQL command window but don't execute the commands yet:
```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
```
This switches off strict mode to the SQL will run on MySQL 5.7 or later.

5. Copy the content of file `administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-23.sql` or `administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql` (depending on your database type) into the SQL command window, in case of MySQL below the previously pasted commands, but don't execute the commands yet.
7. Replace `#__` by your database prefix in the SQL statements pasted before in the SQL input window.
6. Put the cursor to the beginning of the 1st SQL statement in the SQL input window and now execute all SQL commands.
7. Play around with com_redirect, create some links, modify some, ...
8. After any action, check in your database the relevant `datetime`/`timestamp without timezone` columns.

Result: See section "Expected result" below.

### Expected result

The Redirect component works as well as before. In database there are no columns of type `datetime` (MySQL) or `timestamp without time zone` (PostgreSQL) having value '0000-00-00 00:00:00' (MySQL) or '1970-01-01 00:00:00' (PostgreSQL).

### Actual result

The Redirect component works. In database there might be columns of type `datetime` (MySQL) or `timestamp without time zone` (PostgreSQL) having value '0000-00-00 00:00:00' (MySQL) or '1970-01-01 00:00:00' (PostgreSQL).

### Documentation Changes Required

Don't think so.

2019-09-28 13:54 UTC, richard67 commented
Ready for review and test.
@wilsonge Please review.

2019-09-28 22:07 UTC, wilsonge commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql
> +ALTER TABLE "#__redirect_links" ALTER COLUMN "modified_date" DROP DEFAULT;
Your missing updating the modified date here

2019-09-28 22:07 UTC, wilsonge requested changes
Just needs the postgres update

2019-09-28 22:09 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql
> +ALTER TABLE "#__redirect_links" ALTER COLUMN "modified_date" DROP DEFAULT;
Haven't we said we don't do this on posgresql because there is no 0000-00-00... ? In the banners PR I did that update for modified to created value also on yfor MySQL IIRC. Will check.

2019-09-28 22:11 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql
> +ALTER TABLE "#__redirect_links" ALTER COLUMN "modified_date" DROP DEFAULT;
@wilsonge See e.g. here for banners, also no update for modified on pg: [https://github.com/joomla/joomla-cms/pull/26372/files#diff-c4bcedf439207fb5236cc01598c81636](https://github.com/joomla/joomla-cms/pull/26372/files#diff-c4bcedf439207fb5236cc01598c81636).

2019-09-28 22:17 UTC, richard67 commented
@wilsonge I thought we don't do this for PostgreSQL, only for MySQL, that's why I haven't done that also in my other PR's for PostgreSQL. See e.g. here for banners, also no update for modified on pg: [https://github.com/joomla/joomla-cms/pull/26372/files#diff-c4bcedf439207fb5236cc01598c81636](https://github.com/joomla/joomla-cms/pull/26372/files#diff-c4bcedf439207fb5236cc01598c81636).

2019-09-28 22:23 UTC, wilsonge commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql
> +ALTER TABLE "#__redirect_links" ALTER COLUMN "modified_date" DROP DEFAULT;
Isn't banners also going to have a null date tho? We should have similar behaviour in the databases. So if there's a null date it should be changed to the created date (although in postgres it would be 1970....). Because we're removing the check in the frontend for modified date being null when filtering

2019-09-28 22:25 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql
> +ALTER TABLE "#__redirect_links" ALTER COLUMN "modified_date" DROP DEFAULT;
Then I have to update my other PRs, too. The open one which you have approved, not the merged ones, those were ok.

2019-09-28 22:26 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql
> +ALTER TABLE "#__redirect_links" ALTER COLUMN "modified_date" DROP DEFAULT;
same for your pr for com content. shall i make pr to your branch?

2019-09-28 22:28 UTC, wilsonge commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql
> +ALTER TABLE "#__redirect_links" ALTER COLUMN "modified_date" DROP DEFAULT;
Yes please

2019-09-28 22:50 UTC, richard67 commented
@wilsonge Done here and for the other PRs, too.

2019-09-28 23:04 UTC, richard67 commented
@alikon Could you test?

2019-09-29 09:56 UTC, alikon commented
played for a while ....nothing strange happened (beside some strange things like you need  to spent sometimes to discover where the link is ...not in the left menu.... and some other glitches but unrelated to this PR)

2019-09-29 09:57 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 4a9b4ffb80f6391603059c7952ae8dc3bc0c7816<br /><br />on postgresql 11.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26381">issues.joomla.org/tracker/joomla-cms/26381</a>.</sub>

2019-09-29 09:58 UTC, richard67 commented
@wilsonge Could you redo your review? I've applied the changes and have set the discussion to resolved, but still see in red color the "... requested changes ..." thing on GH.

2019-10-03 04:19 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 4a9b4ffb80f6391603059c7952ae8dc3bc0c7816<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26381">issues.joomla.org/tracker/joomla-cms/26381</a>.</sub>

2019-10-03 04:20 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26381">issues.joomla.org/tracker/joomla-cms/26381</a>.</sub>

2019-10-03 15:17 UTC, merged

2019-10-03 15:17 UTC, wilsonge commented
Thanks!