[4.0][plugin][httpheaders] - array to string conversion
joomla/joomla-cms pull request #26505
Opened 2019-10-07 09:29 UTC by alikon

Pull Request for Issue #26501 .

### Summary of Changes
converted array to string

### Testing Instructions
see #26501

### Expected result

no more warning

2019-10-07 11:22 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on f2440d683068b16f40426a6a4bb5a2a7fd1640a6<br /><br />Confirm before Patch:
Warning: hash() expects parameter 2 to be string, array given in \plugins\system\httpheaders\httpheaders.php on line 161
Warning: hash() expects parameter 2 to be string, array given in \plugins\system\httpheaders\httpheaders.php on line 172
After Patch: Warnings has gone.

OT: Which Mode should be use?
Custom / Detect or Automatic?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-07 13:18 UTC, SharkyKZ commented
Since #25357 scripts/styles are stored as array. So this isn't right, the hash is being generated based on first script/style only.

2019-10-07 14:45 UTC, wilsonge commented
@SharkyKZ is right - we probably need to implode to comma separated rather than doing `array_shift`

2019-10-07 15:06 UTC, SharkyKZ commented
Maybe we can use existing MD5 hashes?

2019-10-07 16:35 UTC, alikon commented
used implode and the md5 value....

2019-10-07 17:32 UTC, SharkyKZ commented
No, not like that. I was thinking we could reuse MD5 hashes but says here it's not recommended https://www.w3.org/TR/SRI/#cryptographic-hash-functions.

2019-10-07 17:39 UTC, alikon commented
back to implode

2019-10-07 19:49 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on c50cddb6fd2ab7cede6ad4d7b9d8dee80aaf1ef1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-07 20:08 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on c50cddb6fd2ab7cede6ad4d7b9d8dee80aaf1ef1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-07 20:24 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-07 20:25 UTC, SharkyKZ commented
I don't think this is right. @zero-24 can you take a look at this?

2019-10-07 20:53 UTC, SharkyKZ commented
This doesn't work. Each script/style tag needs to have its own hash. And the hash must be based on the content exactly as it appears on on the page. The content from head data does not not contain formatting added by styles renderer.

2019-10-07 21:16 UTC, richard67 commented
I have not tested this item.<br /><br />Setting to not tested until clarifications and reviews finished.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-07 21:50 UTC, ChristineWk commented
I have not tested this item.<br /><br />OK, I did also set to "Not tested" now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-07 22:06 UTC, brianteeman commented
Please provide real testing instructions - not just see that the warning has gone

2019-10-08 18:09 UTC, zero-24 commented on plugins/system/httpheaders/httpheaders.php
>  			}
```suggestion
			foreach ($inlineScripts as $type => $scriptArray)
			{
				foreach ($scriptArray as $hash => $scriptContent)
				{
					$scriptHashes[] = "'sha256-" . base64_encode(hash('sha256', $scriptContent, true)) . "'";
				}
			}
```

2019-10-08 18:09 UTC, zero-24 commented on plugins/system/httpheaders/httpheaders.php
>  			}
new code
```
			foreach ($inlineScripts as $type => $scriptArray)
			{
				foreach ($scriptArray as $hash => $scriptContent)
				{
					$scriptHashes[] = "'sha256-" . base64_encode(hash('sha256', $scriptContent, true)) . "'";
				}
			}
```

2019-10-08 18:10 UTC, zero-24 commented on plugins/system/httpheaders/httpheaders.php
> +				$styleHashes[] = "'sha256-" . base64_encode(hash('sha256', implode(',', $styleContent), true)) . "'";
```
			foreach ($inlineStyles as $type => $styleArray)
			{
				foreach ($styleArray as $hash => $styleContent)
				{
					$styleHashes[] = "'sha256-" . base64_encode(hash('sha256', $styleContent, true)) . "'";
				}
			}
```

2019-10-08 18:10 UTC, zero-24 requested changes
Please see the inline comments

2019-10-08 18:22 UTC, alikon commented
thanks @zero24 & @SharkyKZ

2019-10-19 07:30 UTC, PoojaPatil1997 commented
I have tested this item :white_check_mark: successfully on 53ff2c4b5b1be01af11e1e5d177b291af307264d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-19 09:41 UTC, crommie commented
I have tested this item :white_check_mark: successfully on 53ff2c4b5b1be01af11e1e5d177b291af307264d<br /><br />As expected: warning without the patch, no warning after applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-19 09:42 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26505">issues.joomla.org/tracker/joomla-cms/26505</a>.</sub>

2019-10-19 10:02 UTC, SharkyKZ commented
This hides the notice but the code is still broken.

2019-10-19 10:14 UTC, zero-24 commented
The code is still broken? Can you explain a bit more? As with https://github.com/joomla/joomla-cms/pull/26505/commits/3ae3bcc2c57e10213a140c351ba9e6aea7ff2413 the actual issue should be fixed or do i miss something?

2019-10-19 10:29 UTC, SharkyKZ commented
Since https://github.com/joomla/joomla-cms/pull/25357 rendered scripts/styles have formatting added to them. But the hash is generated from scripts/styles without formatting. So the hashes don't match scripts/styles that appear on the page.

Assuming SRI works on pages with MIME type other than `text/html`, this was actually broken since the beginning because we wrap code in CDATA: https://github.com/joomla/joomla-cms/blob/56d8a357c2a54656fea36ac7e2ec9f20a715c425/libraries/src/Document/Renderer/Html/HeadRenderer.php#L231

2019-10-19 10:34 UTC, zero-24 commented
Ah ok I get the point now.

2020-02-01 10:52 UTC, closed without merging