[WIP][4.0] add fields items to contact menu
joomla/joomla-cms pull request #26540
Opened 2019-10-10 17:10 UTC by alikon

Pull Request for replace #23366 .

### Summary of Changes
recalc of lft.rgt for the missing com_fields menu items for contact 

### Testing Instructions

### Expected result

### Actual result

### Documentation Changes Required

2019-10-10 17:55 UTC, richard67 commented
I think it will need some update sql script for that, too. If there is some 4.0-*.sql already existing which deals with these menu items, this one can be modified before we are in beta, otherwise or if you are not sure, make a new one. I can help with that on weekend.

2019-10-10 18:06 UTC, alikon commented
we need to deeply review how we provide  updates ---- if we are talking about sql
maybe i'm a dumb 
...but it has  been quite hard 4 me to to deliver this PR .... 
update path without a stored procedure  could be full of issues.... when you are talking about nested set tables, then cannot be a matter for easy/silly update  .... but... maybe i'm too silly :smile:

2019-10-10 18:21 UTC, brianteeman commented
That's why I asked someone else to do it :)

2019-10-10 18:25 UTC, richard67 commented
Hmm, thinking more about it: If it is really ok in 3.9 and not ok in 4.0, maybe there is already some 4.0.0-*.sql update script which removes those menu items? If this is the case, then this update script has to be changed. I can check that on weekend, but tonight and tomorrow night I won't have time.

2019-10-10 18:28 UTC, richard67 commented
Well, I just checked: Seems there is no 4.0 update sql deleting those menu items, so everything should be ok, no update sql needed.

2019-10-10 18:29 UTC, alikon commented
let me clarify...
no better
let me try to explain myself as better as I can ..
when nested set tables are in play..
imho  there are no static script that can save your ass

2019-10-10 18:31 UTC, richard67 commented
Correct.

2019-10-10 18:34 UTC, alikon commented
you cannot guess what are the different lft,rgt values for all installation--- so
the update path should be at least careafully considered those different situation
my answer ----maybe we should consider a stored procedure......or 
i'm open to feedaback

2019-10-10 18:34 UTC, richard67 commented
but shouldn't the "rebuild" button do that after an update?

2019-10-10 18:39 UTC, alikon commented
are you talking about menus table only ?
i'm talking about the whole update process----  i.e assets table .... etc
better ... i'm talking about an update path  where nested set table are deeply involved
and unfortunately .... just not considered
... all is good .... mantra

2019-10-10 18:41 UTC, richard67 commented
Well I did not wanna speak against it, I only asked for my better understanding.

2019-10-10 18:44 UTC, alikon commented
i hope i've at least instilled some grams of  curiosity :smiley:

2019-10-10 20:57 UTC, brianteeman commented
its also why I would not have had any 4.0sql update files at all and just done them all at once when we get to beta. just creates a lot of useless files that will be deleted

2019-10-11 14:30 UTC, Quy commented
Add a separator between `Categories` and `Fields`.

2019-10-11 16:49 UTC, alikon commented
after a more proof review of 3.x we still need an update sql .... i was wrong

2019-10-13 08:58 UTC, richard67 requested changes

2019-10-13 08:58 UTC, richard67 commented on administrator/components/com_admin/script.php
> +			// Bind the data.
```suggestion

			// Bind the data.
```

2019-10-13 09:01 UTC, alikon commented
the needed update is made now with PHP :heart_eyes:

2019-10-13 10:22 UTC, richard67 requested changes
One last PHPCS error.

2019-10-13 10:22 UTC, richard67 commented on administrator/components/com_admin/script.php
> +			$newTableItem   = new \Joomla\Component\Menus\Administrator\Table\MenuTable($db);
```suggestion

			$newTableItem   = new \Joomla\Component\Menus\Administrator\Table\MenuTable($db);
```

2019-10-13 11:15 UTC, SniperSister commented
Postgres System Test is failing:
https://ci.joomla.org:444/artifacts/joomla/joomla-cms/4.0-dev/26540/system-tests/24688/InstallCest.installJoomla.postgres.fail.png

2019-10-13 11:18 UTC, richard67 commented
@SniperSister @alikon and me know about this. I've made a PR to his branch to fix it, he will merge as soon as lunch finished, I think.

2019-10-13 15:27 UTC, richard67 commented
@SniperSister Tests are passing here now.

2019-10-13 15:48 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 661f93b6993241b3ba0f27d4b3b3131f36bcf147<br /><br />Test 1 new installation - MySQL 5.7: OK.
Test 1 new installation - PostgreSQL 10.10: OK.
Test 2 update - MySQL 5.7: OK.
Test 2 update  - PostgreSQL 10.10: OK.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26540">issues.joomla.org/tracker/joomla-cms/26540</a>.</sub>

2019-10-13 15:51 UTC, richard67 commented
@brianteeman Could you test this, too? I've helped with updating testing instructions and making a zip package for an update test because Nicola is a bit busy with preparing for JoomlaDay Italy, so see the updated instructions for details.

2019-10-13 18:17 UTC, Quy commented on administrator/components/com_admin/script.php
> +	 * @since   3.7.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2019-10-14 10:30 UTC, infograf768 commented
Installed on a 3.9.12
After some messages about non available template, I get
<img width="817" alt="Screen Shot 2019-10-14 at 12 18 20" src="https://user-images.githubusercontent.com/869724/66744488-d5b0cd00-ee7c-11e9-854b-8469732bc793.png">

and 
` Notice: Trying to get property 'version' of non-object in /Applications/MAMP/htdocs/trunkgitnew/administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1357`

Contacts have no fields
<img width="292" alt="Screen Shot 2019-10-14 at 12 21 32" src="https://user-images.githubusercontent.com/869724/66744620-34764680-ee7d-11e9-899d-0ff6e849716f.png">
All dashboards are empty. No way to access to database page.

No way to save the administrator menu to use `Alternate preset` in order to access database page
`Save failed with the following error: Column 'publish_down' cannot be null`

used directly the link
`administrator/index.php?option=com_installer&view=database`

2 problems for database
Used `Update structure` button. 
1 problem remains and the button is no more displayed. Menus disappear.

2019-10-14 10:43 UTC, richard67 commented
@infograf768 The first message about template not available is normal after the update but should disappear and not come again after having liogged in to backend for the first time and then having navigated 1 time withint the backend.

The 2nd message should be fixed when my database null date works will be finished. It normally does not appear on a pre 8.0 MySQL with normal configuration regarding session parameters and server variables, e.g. for strict mode. Did you test this on MySQL 8?

The SQL error and empty dashboards ... maybe I've made a mistake when packing the update zip package which is linked in the testing instructions for test 2? I have to check that tonight after work (German time).

2019-10-14 12:28 UTC, infograf768 commented
> Did you test this on MySQL 8?

Nope.

2019-10-19 07:46 UTC, nadjak77 commented
I have tested this item :red_circle: unsuccessfully on 4f755bc69dc09cbec6576669b4f561cff7b74261<br /><br />Deleted configuration.php and databasetables
new installation 
applied patch
deleted browsercache and reload site
the two menue items for "fields" and "fields groups" do not appear<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26540">issues.joomla.org/tracker/joomla-cms/26540</a>.</sub>

2019-10-19 07:50 UTC, richard67 commented
@nadjak77 Wrong order of processing. It has to be
1. Apply patch on a 4.0-dev or alpha-12. This applies the changes to joomla.sql.
2. Remove configuration.php and clear database.
3. Run new installation. This will use the changed joomla.sql.
4. Check backend menu.

You have done the new installation and then applied the patch but then have not done new installation again, so your database did not include the changes here.

2019-10-19 08:09 UTC, richard67 commented
I've just updated the update package for Test 2 to latest nightly build of today.

Testers please follow exactly the testing instructions given in the description of this PR.

2019-10-19 08:11 UTC, richard67 commented
@nadjak77 Please change back your testing result to "not tested" in the issue tracker. The test failed because you did not follow exactly the testing instructions. And if you have enough time, please test again in the right way, that would be very appreciated. Anyway thanks for testing, even if wrong now, because we need volunteers who help with testing.

2019-10-19 08:16 UTC, nadjak77 commented
I have tested this item :white_check_mark: successfully on 4f755bc69dc09cbec6576669b4f561cff7b74261<br /><br />thank you @richard67 
I tried it again:
apply patch
delete configuration.php and database
reinstall joomla
the new items appear under contact<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26540">issues.joomla.org/tracker/joomla-cms/26540</a>.</sub>

2019-10-19 09:26 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on 4f755bc69dc09cbec6576669b4f561cff7b74261<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26540">issues.joomla.org/tracker/joomla-cms/26540</a>.</sub>

2019-10-19 09:53 UTC, uthorat commented
I have tested this item :white_check_mark: successfully on 4f755bc69dc09cbec6576669b4f561cff7b74261<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26540">issues.joomla.org/tracker/joomla-cms/26540</a>.</sub>

2019-10-19 09:58 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26540">issues.joomla.org/tracker/joomla-cms/26540</a>.</sub>

2019-10-19 21:45 UTC, merged

2019-10-19 21:45 UTC, wilsonge commented
Thanks!

2019-10-20 09:03 UTC, astridx commented
Thank you for making the custom fields usable again. 
Now I'm wondering: how should third party developers integrate custom fields in Joomla 4? Is it recommended that you also change the table `#__menu`, or should you continue to use a sub menu?

2019-11-09 11:02 UTC, alikon commented
> Now I'm wondering: how should third party developers integrate custom fields in Joomla 4? Is it recommended that you also change the table #__menu, or should you continue to use a sub menu?

imo is matter of personal taste / consistency