[4.0] User Disable Action Log
joomla/joomla-cms pull request #26688
Opened 2019-10-19 12:02 UTC by sudhir-j-sapkal

### Summary of Changes
If user is blocked , Logout activity should not be logged.

### Testing Instructions
Login to Joomla Backend with Superuser access

Go to Users => Manage
Disable any user
Go to Users => Users Action Log
See the latest activity. "User vjtest logged out from admin"

### Expected result

The logout entry for blocked user should not be logged, It should only log user is updated by Super user.

### Actual result

There were two activities 
1. For update of user by super user.
2. User is logged out from system.

![screenshot-vijayktest joomla com-2019 10 19-17_27_56](https://user-images.githubusercontent.com/17097405/67144636-4d746280-f296-11e9-89e2-275884140d48.png)
![screenshot-vijayktest joomla com-2019 10 19-17_26_53 (1)](https://user-images.githubusercontent.com/17097405/67144637-4d746280-f296-11e9-88cb-5a8c9dfd52aa.png)

### Documentation Changes Required
No

2019-10-19 12:05 UTC, manojLondhe requested changes

2019-10-19 12:05 UTC, manojLondhe commented on plugins/actionlog/joomla/joomla.php
>  		$loggedOutUser      = User::getInstance($user['id']);
change as

```
		$loggedOutUser = User::getInstance($user['id']);
		
		if ($loggedOutUser->block)
		{
			return;
		}

		$messageLanguageKey = 'PLG_ACTIONLOG_JOOMLA_USER_LOGGED_OUT';
```

2019-10-19 12:06 UTC, sudhir-j-sapkal commented on plugins/actionlog/joomla/joomla.php
>  		$loggedOutUser      = User::getInstance($user['id']);
@manojLondhe DONE

2019-10-19 12:42 UTC, patjun commented
I have tested this item :white_check_mark: successfully on e6655ea2cfe5376e72fc45c27313d3c565e010b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26688">issues.joomla.org/tracker/joomla-cms/26688</a>.</sub>

2019-10-19 12:49 UTC, brianteeman commented
Why should this not be logged. It seems sensible to me that this is logged

2019-10-19 12:51 UTC, karo3 commented
I have tested this item :white_check_mark: successfully on e6655ea2cfe5376e72fc45c27313d3c565e010b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26688">issues.joomla.org/tracker/joomla-cms/26688</a>.</sub>

2019-10-19 12:56 UTC, karo3 commented
It's only happens when you block him from the table but not when you do it in the edit view.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26688">issues.joomla.org/tracker/joomla-cms/26688</a>.</sub>

2019-10-19 17:29 UTC, uglyeoin commented
@karo3 this should not be a successful test then

2019-11-02 04:29 UTC, vijaykhollam commented
I have tested this item :white_check_mark: successfully on e6655ea2cfe5376e72fc45c27313d3c565e010b2<br /><br />Given logged out activity should not be logged when the user is not logged in frontend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26688">issues.joomla.org/tracker/joomla-cms/26688</a>.</sub>

2019-11-02 04:53 UTC, sudhir-j-sapkal commented
@brianteeman - It should log the activity of User Logged out only when user is log-ed in front end and Admin is blocking him from back-end.

2019-11-02 05:28 UTC, tushar33 commented
I have tested this item :white_check_mark: successfully on e6655ea2cfe5376e72fc45c27313d3c565e010b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26688">issues.joomla.org/tracker/joomla-cms/26688</a>.</sub>

2019-11-06 15:04 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26688">issues.joomla.org/tracker/joomla-cms/26688</a>.</sub>

2019-11-06 15:06 UTC, brianteeman commented
@sudhir-j-sapkal sorry but I stilll dont understand why this is needed

2019-11-06 15:26 UTC, mbabker commented
It seems like there should be a more appropriate "Blocked user X tried to log in" log message, not no log message at all.  I'm with Brian here, I don't get what cognitive benefit this change is adding.

2020-01-03 14:10 UTC, Quy commented
Closing for reason stated.

2020-01-03 14:10 UTC, closed without merging