[4.0] Fixing Installing Multilingual sample data
joomla/joomla-cms pull request #26832
Opened 2019-10-26 16:32 UTC by infograf768

### Summary of Changes
Adapting the code to the new `featured_down` and `featured_up` columns in `_content_frontpage` table.

### Testing Instructions
Install a brand new 4.0-dev.
Install some languages (French fr-FR, German de-DE)
Use the `Multilingual Sample Data ` installation in Control Panel

### Before patch
The installation stops at step 6

### After patch
All is fine

<img width="524" alt="Screen Shot 2019-10-26 at 18 30 41" src="https://user-images.githubusercontent.com/869724/67622846-d2bfc000-f81e-11e9-9f89-5bae285b07e5.png">

2019-10-26 17:02 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 0e026193b3c640dd0180415c52f859a0becd671d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26832">issues.joomla.org/tracker/joomla-cms/26832</a>.</sub>

2019-10-26 17:33 UTC, richard67 requested changes

2019-10-26 17:33 UTC, richard67 commented on plugins/sampledata/multilang/multilang.php
> +			->values($newId . ', 0, null, null');
```suggestion
			->values($newId . ', 0, NULL, NULL');
```
Is SQL NULL, not PHP null, so it should be uppercase.

2019-10-26 17:39 UTC, richard67 commented
@infograf768 @Quy I get here on a current 4.0-dev with the patch applied after a new installation and then having installed German (DE) and French following PHP notice 2 times, and the multilingaul sample data still stops at step 6:

> PHP Notice:  Undefined property: Joomla\\Component\\Content\\Administrator\\Table\\ArticleTable::$featured_up in /home/richard/lamp/public_html/joomla-cms-4.0-dev/libraries/src/Table/Content.php on line 278

2019-10-26 17:49 UTC, Quy commented
I forgot to mention I had to install your PR #26829 first applying this PR.

2019-10-26 17:52 UTC, richard67 commented
Ah, I see. Will do so, too.

2019-10-26 17:55 UTC, richard67 commented
@infograf768 @Quy Wouldn't it be safer to include this change here into my PR #26829 ? It could be a problem if this one here gets merged long before #26829 .

2019-10-26 17:58 UTC, Quy commented
Good idea!

2019-10-26 18:02 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 0e026193b3c640dd0180415c52f859a0becd671d<br /><br />Requires PR #26829 to be applied, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26832">issues.joomla.org/tracker/joomla-cms/26832</a>.</sub>

2019-10-26 19:08 UTC, richard67 approved these changes

2019-10-26 19:12 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 098800eb51b7fbf330216521054ac2bebb6d3855<br /><br />Requires PR #26829 to be applied, too, and requires that PR to be merged before this here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26832">issues.joomla.org/tracker/joomla-cms/26832</a>.</sub>

2019-10-27 05:27 UTC, infograf768 commented
When i tested (and I did it again a minute ago), I did not have https://github.com/joomla/joomla-cms/pull/26829 applied and the patch worked fine.

2019-10-27 05:28 UTC, infograf768 commented
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26832">issues.joomla.org/tracker/joomla-cms/26832</a>.</sub>

2019-10-27 22:02 UTC, merged

2019-10-27 22:02 UTC, wilsonge commented
Thanks!