[4.0] [com_contact] Missing parameterized queries, fixed double quoting
joomla/joomla-cms pull request #27012
Opened 2019-11-07 09:25 UTC by SharkyKZ

### Summary of Changes

Adds some missing parameterized queries and fixes possible double quoting.

### Testing Instructions

On multilingual site create some contacts with associations.
View contact list, check that associations appear like before.
View feature view in frontend.
Changes in `components/com_contact/Service/Route.php` can be tested by code review. Not sure if it's actually used anywhere.

### Expected result

Works.

### Documentation Changes Required

No.

2019-11-07 15:33 UTC, Quy commented on components/com_contact/Model/FeaturedModel.php
> +			$nowDate = Factory::getDate()->toSql();
Remove double quoting on line 135?

2019-11-07 15:51 UTC, SharkyKZ commented on components/com_contact/Model/FeaturedModel.php
> +			$nowDate = Factory::getDate()->toSql();
Removed.

2019-11-07 18:04 UTC, alikon requested changes

2019-11-07 18:04 UTC, alikon commented on administrator/components/com_contact/Service/HTML/AdministratorService.php
> +				->whereIn($db->quoteName('c.id'), array_values($associations), ParameterType::STRING)
that's weird the field `id` of `#__contact_details` table is a SERIAL at least on postgresql should be binded to an INTEGER imo

2019-11-07 18:09 UTC, alikon requested changes

2019-11-07 18:09 UTC, alikon commented on components/com_contact/Model/FeaturedModel.php
>  			$query->whereIn($db->quoteName('a.language'), $language);
```suggestion
			$query->whereIn($db->quoteName('a.language'), $language, ParameterType::STRING);
```

2019-11-07 19:29 UTC, SharkyKZ commented on administrator/components/com_contact/Service/HTML/AdministratorService.php
> +				->whereIn($db->quoteName('c.id'), array_values($associations), ParameterType::STRING)
Yes.

2019-11-08 03:23 UTC, Quy commented
I have tested this item :white_check_mark: successfully on ded480ca3513ac57749779bf724c7fb83b41f263<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27012">issues.joomla.org/tracker/joomla-cms/27012</a>.</sub>

2019-11-08 07:16 UTC, alikon commented
I have tested this item :white_check_mark: successfully on ded480ca3513ac57749779bf724c7fb83b41f263<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27012">issues.joomla.org/tracker/joomla-cms/27012</a>.</sub>

2019-11-08 07:17 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27012">issues.joomla.org/tracker/joomla-cms/27012</a>.</sub>

2019-11-08 12:15 UTC, merged

2019-11-08 12:15 UTC, wilsonge commented
Thanks!

2019-11-08 12:15 UTC, wilsonge commented
Thanks!