[4.0] Move Private Messages to Users
joomla/joomla-cms pull request #27096
Opened 2019-11-17 13:21 UTC by brianteeman

As the component menu is now used for components that create some form of site content this Pr moves the private messages component from the Component menu to the users menu.

When testing simply applying the patch will only add the messages menu items to the users menu. It will not remove it from the component menu. As the sql change is data and not structure you cannot use the database fix either. It will have to be a direct update in the sql using phpmyadmin or similar

2019-11-17 21:02 UTC, Quy commented
Add module to the Users Dashboard.

![27096](https://user-images.githubusercontent.com/368084/69013943-2747ee00-093a-11ea-82c6-609ad01b7ab8.jpg)

2019-11-17 21:42 UTC, brianteeman commented
@quy that is beyond the scope of this PR as it doesn't currently exist and there are other things missing from the dashboard

2019-11-17 21:42 UTC, brianteeman commented
@SniperSister @zero-24 could you look at rips please

2019-11-18 19:06 UTC, zero-24 commented
hmm drone seams to fail on system-tests-mysql not rips: https://ci.joomla.org/joomla/joomla-cms/26172 ;)

2019-11-18 19:18 UTC, brianteeman commented
This was the failure https://ci.joomla.org/joomla/joomla-cms/26146 @zero-24

2019-11-18 19:44 UTC, zero-24 commented
Was an false positive it is passing now.

2019-11-30 22:39 UTC, brianteeman commented
Conflicts resolved

2019-12-11 09:08 UTC, brianteeman commented
Updated branch to kickstart drone

2020-01-04 04:02 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on ec0c5731000801be2267e467b3c13bed1d279116<br /><br />New messaging menu items appear in the users menu and function as expected. As mentioned, it is also still located in components.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27096">issues.joomla.org/tracker/joomla-cms/27096</a>.</sub>

2020-01-04 04:43 UTC, Quy commented on installation/sql/mysql/joomla.sql
> +SELECT 11, 'main', 'com_newsfeeds_feeds', 'Feeds', '', 'News Feeds/Feeds', 'index.php?option=com_newsfeeds&view=newsfeeds', 'component', 1, 12, 2, `extension_id`, 0, NULL, 0, 0, 'class:newsfeeds', 0,
Please check as there are no menu items under News Feeds.

2020-01-04 18:05 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on cc6474d12aa1646ca539aebdc3f25bc32f4fc4d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27096">issues.joomla.org/tracker/joomla-cms/27096</a>.</sub>

2020-01-05 16:29 UTC, Quy commented on installation/sql/mysql/joomla.sql
> +SELECT 11, 'main', 'com_newsfeeds_feeds', 'Feeds', '', 'News Feeds/Feeds', 'index.php?option=com_newsfeeds&view=newsfeeds', 'component', 1, 12, 2, `extension_id`, 0, NULL, 0, 0, 'class:newsfeeds', 0,
```suggestion
SELECT 11, 'main', 'com_newsfeeds_feeds', 'Feeds', '', 'News Feeds/Feeds', 'index.php?option=com_newsfeeds&view=newsfeeds', 'component', 1, 10, 2, `extension_id`, 0, NULL, 0, 0, 'class:newsfeeds', 0, '', 26, 27, 0, '*', 1, NULL, NULL FROM `#__extensions` WHERE `name` = 'com_newsfeeds';
```

2020-01-05 16:29 UTC, Quy commented on installation/sql/mysql/joomla.sql
> +SELECT 12, 'main', 'com_newsfeeds_categories', 'Categories', '', 'News Feeds/Categories', 'index.php?option=com_categories&view=categories&extension=com_newsfeeds', 'component', 1, 12, 2, `extension_
```suggestion
SELECT 12, 'main', 'com_newsfeeds_categories', 'Categories', '', 'News Feeds/Categories', 'index.php?option=com_categories&view=categories&extension=com_newsfeeds', 'component', 1, 10, 2, `extension_id`, 0, NULL, 0, 0, 'class:newsfeeds-cat', 0, '', 24, 25, 0, '*', 1, NULL, NULL FROM `#__extensions` WHERE `name` = 'com_categories';
```

2020-01-05 16:29 UTC, Quy commented on installation/sql/postgresql/joomla.sql
> +SELECT 11, 'main', 'com_newsfeeds_feeds', 'Feeds', '', 'News Feeds/Feeds', 'index.php?option=com_newsfeeds&view=newsfeeds', 'component', 1, 12, 2, "extension_id", 0, NULL, 0, 0, 'class:newsfeeds', 0,
```suggestion
SELECT 11, 'main', 'com_newsfeeds_feeds', 'Feeds', '', 'News Feeds/Feeds', 'index.php?option=com_newsfeeds&view=newsfeeds', 'component', 1, 10, 2, "extension_id", 0, NULL, 0, 0, 'class:newsfeeds', 0, '', 26, 27, 0, '*', 1, NULL, NULL FROM "#__extensions" WHERE "name" = 'com_newsfeeds';
```

2020-01-05 16:30 UTC, Quy commented on installation/sql/postgresql/joomla.sql
> +SELECT 12, 'main', 'com_newsfeeds_categories', 'Categories', '', 'News Feeds/Categories', 'index.php?option=com_categories&view=categories&extension=com_newsfeeds', 'component', 1, 12, 2, "extension_
```suggestion
SELECT 12, 'main', 'com_newsfeeds_categories', 'Categories', '', 'News Feeds/Categories', 'index.php?option=com_categories&view=categories&extension=com_newsfeeds', 'component', 1, 10, 2, "extension_id", 0, NULL, 0, 0, 'class:newsfeeds-cat', 0, '', 28, 29, 0, '*', 1, NULL, NULL FROM "#__extensions" WHERE "name" = 'com_categories';
```

2020-01-05 18:44 UTC, brianteeman commented
I have committed your changes @Quy 

I will now leave contributing to joomla 4 until it is clear what is happening with the other template. If that proceeds the way that they want then any change here is a complete waste of all of our time

2020-01-06 01:11 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 8084ec73f03e936e4d79f2ad8168200ca2ab306d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27096">issues.joomla.org/tracker/joomla-cms/27096</a>.</sub>

2020-01-06 10:53 UTC, infograf768 commented
Looks like the change is not done for the alternate preset

2020-01-06 11:03 UTC, brianteeman commented
Until a decision is made https://github.com/joomla/joomla-cms/pull/27096#issuecomment-570936724 I am not wasting my time

2020-01-06 13:56 UTC, marcodings commented
> I will now leave contributing to joomla 4 until it is clear what is happening with the other template. If that proceeds the way that they want then any change here is a complete waste of all of our time

@brianteeman , i to understand what is unclear. The read-me for Khonsu is perfectly clear and has been discussed also with you.

The Khonsu community initiative is intended to be an alternate/alternative template, J4 is NOT waiting for Khonsu, Khonsu will have to live up to the same standards as other contributions. If and only if all these requirements are met it will be considered.

2020-01-06 14:04 UTC, brianteeman commented
@marcodings I know we have discussed it before and I know you have stated that before. But I guess you need to tell the people on the Khonsu repository that then. They are definitely still of the opinion that they are building a replacement template. 

See https://github.com/joomla-projects/j4adminui/issues/184#issuecomment-570926024

> Well, Joomla should not have any alternative admin templates. I talked to Marco on this few days back. We have to make our mind fixed. Choose Atum or Khonsu but not both. As an extension developer, I can guarantee you that multiple templates will ruin everything.

>  Keeping backward compatibility with Atum has nothing to do with the requirements. Atum is not a standard.

2020-01-06 21:20 UTC, brianteeman commented
> Looks like the change is not done for the alternate preset
@infograf768 

I really don't understand that code. Can you either do a pr to my branch for that or create a separate PR just for that

2020-01-07 11:04 UTC, infograf768 commented
@brianteeman 
> I really don't understand that code. Can you either do a pr to my branch for that or create a separate PR just for that.

Can do a PR after this one is merged.

2020-01-07 11:28 UTC, infograf768 commented
Or you can use this .diff in your PR

[messaging.diff.zip](https://github.com/joomla/joomla-cms/files/4030359/messaging.diff.zip)

2020-01-07 11:38 UTC, brianteeman commented
Thanks @infograf768 I have applied your patch

2020-01-07 20:38 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 85e17585bf5748973b24dccb84c405c00aeadd0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27096">issues.joomla.org/tracker/joomla-cms/27096</a>.</sub>

2020-02-03 14:12 UTC, brianteeman commented
I will try to get the conflicts resolved tonight


> @brianteeman , i to understand what is unclear. The read-me for Khonsu is perfectly clear and has been discussed also with you.

Guess that wasn't the case after all. ;)

2020-02-04 09:03 UTC, brianteeman commented
@richard67 if you are able to help resolving the conflicts with the sql I would appreciate it. I always mess up on this part.

2020-02-04 11:19 UTC, richard67 commented
@brianteeman Tonight after work I can have a look on it if nobody else was faster.

2020-02-04 11:35 UTC, brianteeman commented
@richard67 greatly appreciated

2020-02-04 18:44 UTC, richard67 commented
@brianteeman Am on it, stay tuned.

2020-02-04 19:52 UTC, richard67 commented
@brianteeman Please check [https://github.com/brianteeman/joomla-cms/pull/95](https://github.com/brianteeman/joomla-cms/pull/95), especially the instructions in description, and let me know if you have questions. Btw. is there a way to contact you elsewhere, e.g. on Glip, in case if we have to solve things together and discussion on GH would be uncomfortable?

2020-02-04 20:52 UTC, richard67 commented
@brianteeman It looks as if lft and rgt were messed up even before. Am just looking and working on fixing them.

2020-02-04 21:06 UTC, richard67 commented
@brianteeman I have it, lft and rgt, will make PR for you in a bit, stay tuned. Am doing it in the manual way, like learned on German Joomla Day last year.

2020-02-04 21:57 UTC, richard67 commented
@brianteeman Delet statements from update SQL script executed in PhpMyAdmin don't delete the old records. Must be something wrong with the where clause. Am checking.

2020-02-04 22:00 UTC, richard67 commented
@brianteeman It is the 'index.php?' missing at the beginning of the link in the where clause of the update sql script which makes deletion fail.

2020-02-04 22:21 UTC, brianteeman commented
oops

2020-02-04 22:42 UTC, richard67 requested changes
Final one I think.

2020-02-04 22:42 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-11-19.sql
> +DELETE FROM `#__menu` WHERE `link` = 'index.php?option=com_messages&&task=message.add' AND `menutype` = 'main';
```suggestion
DELETE FROM `#__menu` WHERE `link` = 'index.php?option=com_messages&task=message.add' AND `menutype` = 'main';
```

2020-02-04 22:42 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-11-19.sql
> +DELETE FROM "#__menu" WHERE "link" = 'index.php?option=com_messages&&task=message.add' AND "menutype" = 'main';
```suggestion
DELETE FROM "#__menu" WHERE "link" = 'index.php?option=com_messages&task=message.add' AND "menutype" = 'main';
```

2020-02-04 22:45 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on f2a3ccf473a9710289f1a4daaf3098b5a4ab03d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27096">issues.joomla.org/tracker/joomla-cms/27096</a>.</sub>

2020-02-04 22:47 UTC, richard67 commented
Tested new install and statements from update sql scripts on MySQL and PostgreSQL. Tested applying the patch on MySQL.

2020-02-05 19:12 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on f2a3ccf473a9710289f1a4daaf3098b5a4ab03d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27096">issues.joomla.org/tracker/joomla-cms/27096</a>.</sub>

2020-02-05 19:13 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27096">issues.joomla.org/tracker/joomla-cms/27096</a>.</sub>

2020-02-06 08:17 UTC, merged

2020-02-06 08:28 UTC, brianteeman commented
thanks all