Allow jForm to support data attribute
joomla/joomla-cms pull request #27212
Opened 2019-12-05 13:47 UTC by twsvaishali

Pull Request for Issue #16034
Summary of Changes

    HTML5 is designed with extensibility in mind for data that should be associated with a particular element but need not have any defined meaning. data-* attributes allow us to store extra information on the standard, semantic HTML elements without other hacks such as non-standard attributes, extra properties on DOM.

    However, custom attributes have no special meaning generally and are only special to the owner's application. They can be used to simplify an application's logic. By allowing JForm to support data attributes, it can be greatly aid development of extensions both core and third party.

2019-12-05 13:50 UTC, alikon requested changes

2019-12-05 13:50 UTC, alikon commented on libraries/src/Form/FormField.php
> +						\JLog::add("Cannot access protected / private property $name of " . __CLASS__);
```suggestion
						Log::add("Cannot access protected / private property $name of " . __CLASS__);
```

2019-12-05 14:00 UTC, alikon commented
is this a work in progress ?
as example this one has not been added 
https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/form/field/color/advanced.php

2019-12-05 14:02 UTC, Quy commented on layouts/joomla/form/field/calendar.php
> +foreach ($dataAttributes as $key => $attrValue)
```suggestion

foreach ($dataAttributes as $key => $attrValue)
```

Repeat with other instances.

2019-12-05 14:03 UTC, dgrammatiko commented
@twsvaishali please extend this for `aria-*`

2019-12-06 09:21 UTC, twsvaishali commented
> is this a work in progress ?
> as example this one has not been added from #16141
> https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/form/field/color/advanced.php

Have added remaining fields in latest commits. Please check.

2019-12-06 09:23 UTC, twsvaishali commented
> @twsvaishali please extend this for `aria-*`

Can we start new PR for this?

2019-12-06 10:43 UTC, alikon commented
> Have added remaining fields in latest commits. Please check.

seems fine now thanks

yes maybe another PR  for the `aria-*`

2019-12-06 12:45 UTC, dgrammatiko commented
@alikon @twsvaishali for the `aria-*` all is needed is a var ariaAttributes
and adding 
```php
				// Check for aria attribute
 				if (strpos($name, "aria-") === 0 && array_key_exists($name, $this->ariaAttributes))
 				{
 					return $this->ariaAttributes[$name];
 				}
```
in the main class and some minor adjustments in the layouts. Of course it can be done in another PR to make things easier for testing. I just had to mention that, since a11y is always an afterthought...

2019-12-06 12:51 UTC, dgrammatiko commented
@twsvaishali since you're redoing this maybe we could change the layouts logic to:
```php
if (!empty($dataAttributes)) {
	// Data attributes - data-*
	$dataAttribute = '';

	foreach ($dataAttributes as $key => $attrValue)
	{
		$dataAttribute .= ' ' . $key . '="' . htmlspecialchars($attrValue, ENT_COMPAT, 'UTF-8') . '"';
	}
}
```

In essence the loop will execute **only** if there are any `data-*` attributes defined.
Micro optimisation? Maybe, maybe not, I haven't benchmarked the code but this seems reasonable...

2019-12-06 12:51 UTC, twsvaishali commented
@dgrammatiko Yes. Will start another PR  for the aria-* once this is tested and merged. Also I am actually not sure if all fields will have area attribute.

2019-12-07 01:27 UTC, Quy commented on layouts/joomla/form/field/calendar.php
> +// Data attributes - data-*
I would remove the comment as it is mentioned in the doc block.

2019-12-07 01:31 UTC, Quy commented on layouts/joomla/form/field/password.php
> +	$dataAttribute
```suggestion
	$dataAttribute,
```

2019-12-07 01:32 UTC, Quy commented on layouts/joomla/form/field/text.php
> +foreach ($dataAttributes as $key => $attrValue)
```suggestion

foreach ($dataAttributes as $key => $attrValue)
```

2019-12-07 01:32 UTC, Quy commented on layouts/joomla/form/field/time.php
> +	$dataAttribute
```suggestion
	$dataAttribute,
```

2019-12-07 01:38 UTC, Quy commented on layouts/joomla/form/field/moduleorder.php
> +$dataAttribute = '';
Variable not used.

2019-12-07 10:27 UTC, SharkyKZ commented on layouts/joomla/form/field/calendar.php
> + * @var   array    $dataAttribute   Miscellaneous data attribute for eg, data-*.
This should be variable from extracted data. So `$dataAttributes` not `$dataAttribute`. Same in other fields.

2019-12-07 12:25 UTC, twsvaishali commented on layouts/joomla/form/field/calendar.php
> + * @var   array    $dataAttribute   Miscellaneous data attribute for eg, data-*.
done. Changes committed.

2019-12-07 12:25 UTC, twsvaishali commented on layouts/joomla/form/field/moduleorder.php
> +$dataAttribute = '';
done. Changes committed.

2019-12-07 12:26 UTC, twsvaishali commented on layouts/joomla/form/field/time.php
> +	$dataAttribute
done. Changes committed.

2019-12-07 14:01 UTC, Quy commented on libraries/src/Form/FormField.php
> +			if (strpos($key, "data-") === 0)
```suggestion
			if (strpos($key, 'data-') === 0)
```

2019-12-07 14:02 UTC, Quy commented on libraries/src/Form/FormField.php
> +				if (strpos($name, "data-") === 0)
```suggestion
				if (strpos($name, 'data-') === 0)
```

2019-12-08 01:06 UTC, Quy commented on layouts/joomla/form/field/combo.php
> +	"<?php echo $dataAttribute; ?>"
```suggestion
	<?php echo $dataAttribute; ?>
```

2019-12-08 01:08 UTC, Quy commented on libraries/src/Form/FormField.php
> +				if (strpos($name, "data-") === 0 && array_key_exists($name, $this->dataAttributes))
```suggestion
				if (strpos($name, 'data-') === 0 && array_key_exists($name, $this->dataAttributes))
```

2019-12-16 22:24 UTC, Quy commented on layouts/joomla/form/field/email.php
> + * @var   array    $dataAttributes   Miscellaneous data attribute for eg, data-*.
```suggestion
 * @var   array    $dataAttributes  Miscellaneous data attribute for eg, data-*.
```

2020-02-16 14:44 UTC, wilsonge commented
Rebased this. Anyone able to test this?

2020-03-24 03:57 UTC, Quy commented on layouts/joomla/form/field/user.php
> +		$inputAttributes[$key] .= htmlspecialchars($attrValue, ENT_COMPAT, 'UTF-8');
```suggestion
		$inputAttributes[$key] = htmlspecialchars($attrValue, ENT_COMPAT, 'UTF-8');
```

2020-05-27 17:34 UTC, richard67 commented on layouts/joomla/form/field/user.php
> +		$inputAttributes[$key] .= htmlspecialchars($attrValue, ENT_COMPAT, 'UTF-8');
@wilsonge Shall we just commit this suggestion by @Quy ? Or ask the author of this PR to do it?

2020-05-27 18:36 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on d46baf19504b0463f348218b9a5656dd73c61891<br /><br />Works so far.

Maybe some fields are missing because they did not exist (yet) when this PR was made.

It needs someone who checks for completeness and if necessary makes a new PR.

Same with the idea to do the same for "aria-" attributes, this should be done in another PR, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27212">issues.joomla.org/tracker/joomla-cms/27212</a>.</sub>

2020-05-27 18:46 UTC, Quy commented
I have tested this item :white_check_mark: successfully on d46baf19504b0463f348218b9a5656dd73c61891<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27212">issues.joomla.org/tracker/joomla-cms/27212</a>.</sub>

2020-05-27 18:46 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27212">issues.joomla.org/tracker/joomla-cms/27212</a>.</sub>

2020-05-28 08:07 UTC, richard67 commented
@wilsonge @Quy What about the following field layouts? They are not touched by this PR. Shall they be done, too?
- checkboxes.php
- color/slider.php
- contenthistory.php
- radio/buttons.php
- radio/switcher.php
- tag.php

2020-05-28 18:42 UTC, merged

2020-05-28 18:42 UTC, HLeithner commented
Thanks all!