[4.0] Associations tooltip id accessibility
joomla/joomla-cms pull request #27370
Opened 2019-12-29 11:50 UTC by brianteeman

On a multilingual site with more than two languages the language indicators have a div for displaying the _tooltip_

The way the id for the div was generated it might not be unique. This PR ensures that it is unique.

Applied to menus, categories, content, contacts, newsfeeds (don't think there is anywhere else?)

![image](https://user-images.githubusercontent.com/1296369/71556496-51102c80-2a31-11ea-9c84-87d965071fd5.png)

2019-12-29 17:05 UTC, Quy commented on administrator/components/com_content/Service/HTML/AdministratorService.php
> -
Revert

2019-12-29 19:51 UTC, Quy commented
I have tested this item :white_check_mark: successfully on d5faf059de09ad6a2bfa73ea136b5839996461c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27370">issues.joomla.org/tracker/joomla-cms/27370</a>.</sub>

2019-12-31 17:38 UTC, Quy commented
Please confirm that the title attribute should be removed since there is a tooltip for it. I will do a separate a PR.

![27370](https://user-images.githubusercontent.com/368084/71629209-1fbe6a80-2bb1-11ea-9d90-84317ac6dd17.jpg)

2020-01-03 11:54 UTC, astridx commented
If tested this successful.

I did the following:

1. I had checked the background for the Post Installation Hint
![Control Panel   Test   Administration](https://user-images.githubusercontent.com/9974686/71722033-bc8a3d80-2e27-11ea-88a1-9ff7cfbdc097.png)
 It was

`#f9acaa;`

```
.badge-danger {
    color: 
#3b0d0c;
background-color:
#f9acaa;
border: 1px solid
    #ba2926;
}
```
2. I run `git fetch origin pull/27357/head:qicon` and changed to `qicon` branch.

3. I run `npm i`

4. After reloading the site I did not realize a change. But in CSS I see the new background color.
`#f5b9b7;`
```
.badge-danger {
    color: 
#3b0d0c;
background-color:
#f5b9b7;
border: 1px solid
    #ba2926;
}
```

2020-01-03 11:55 UTC, astridx commented
I have tested this item :white_check_mark: successfully on ab43a1ee84e307bc14d04d3fa2cd89d63862b29f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27370">issues.joomla.org/tracker/joomla-cms/27370</a>.</sub>

2020-01-03 11:55 UTC, astridx commented
I have tested this item :white_check_mark: successfully on ab43a1ee84e307bc14d04d3fa2cd89d63862b29f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27370">issues.joomla.org/tracker/joomla-cms/27370</a>.</sub>

2020-01-03 12:36 UTC, HLeithner requested changes
In you case it possible to have cat id 1 and language 11 which would be tip111 but it's possible that you have cat id 11 and language 1 which would be 111 as well. Adding dashes changes this to tip-1-11 or tip-11-1

2020-01-03 12:36 UTC, HLeithner commented on administrator/components/com_categories/Service/HTML/AdministratorService.php
> +							. '<div role="tooltip" id="tip' . (int) $catid . (int) $item->id . '">' . $tooltip . '</div>';
It's possible that this is not a unique string, you have to add a separator between the numbers like a dash.
```suggestion
							. '<div role="tooltip" id="tip-' . (int) $catid . '-' . (int) $item->id . '">' . $tooltip . '</div>';
```

2020-01-03 12:36 UTC, HLeithner commented on administrator/components/com_contact/Service/HTML/AdministratorService.php
> +							. '<div role="tooltip" id="tip' . (int) $contactid . (int) $item->id . '">' . $tooltip . '</div>';
```suggestion
							. '<div role="tooltip" id="tip-' . (int) $contactid . '-' . (int) $item->id . '">' . $tooltip . '</div>';
```

2020-01-03 12:36 UTC, HLeithner commented on administrator/components/com_content/Service/HTML/AdministratorService.php
> +							. '<div role="tooltip" id="tip' . (int) $articleid . (int) $item->id . '">' . $tooltip . '</div>';
```suggestion
							. '<div role="tooltip" id="tip-' . (int) $articleid . '-' . (int) $item->id . '">' . $tooltip . '</div>';
```

2020-01-03 12:36 UTC, HLeithner commented on administrator/components/com_menus/Service/HTML/Menus.php
> +							. '<div role="tooltip" id="tip' . (int) $itemid . (int) $item->id . '">' . $tooltip . '</div>';
```suggestion
							. '<div role="tooltip" id="tip-' . (int) $itemid . '-' . (int) $item->id . '">' . $tooltip . '</div>';
```

2020-01-03 12:36 UTC, HLeithner commented on administrator/components/com_newsfeeds/Service/HTML/AdministratorService.php
> +							. '<div role="tooltip" id="tip' . (int) $newsfeedid . (int) $item->id . '">' . $tooltip . '</div>';
```suggestion
							. '<div role="tooltip" id="tip-' . (int) $newsfeedid . '-' . (int) $item->id . '">' . $tooltip . '</div>';
```

2020-01-03 12:54 UTC, astridx commented
I did the following:

1. I run `git fetch origin pull/27370/head:associationdiv` 
2. After that I installed French and German language and activated the `language filter` plugin.
3. I created a French a German and an English article and set up the associations.
4. I debug and checked the id [here](https://github.com/joomla/joomla-cms/blob/f51e6a73790221656815d8f937492bb536a9d768/administrator/components/com_content/Service/HTML/AdministratorService.php#L91).
5. I checked out the branch `associationdiv`
6. I run debugger again an see, that the ID [here](https://github.com/joomla/joomla-cms/blob/f51e6a73790221656815d8f937492bb536a9d768/administrator/components/com_content/Service/HTML/AdministratorService.php#L91) was correctly changed.

2020-01-03 13:03 UTC, brianteeman commented
Good spot @HLeithner I have applied those changes

2020-01-03 13:05 UTC, HLeithner commented
@brianteeman you missed a button^^

2020-01-04 01:10 UTC, brianteeman commented
@HLeithner I was on my phone :(

2020-01-04 04:50 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 6d21ea210b125660db3963735c760a947875d279<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27370">issues.joomla.org/tracker/joomla-cms/27370</a>.</sub>

2020-01-04 11:12 UTC, astridx commented
I have tested this item :white_check_mark: successfully on 6d21ea210b125660db3963735c760a947875d279<br /><br />I did 'git pull origin pull/27370/head:associationdiv' and repeated my test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27370">issues.joomla.org/tracker/joomla-cms/27370</a>.</sub>

2020-01-04 15:32 UTC, merged

2020-01-04 15:32 UTC, HLeithner commented
Thanks

2020-01-04 15:51 UTC, brianteeman commented
Thanks