Pagination seo friendly
joomla/joomla-cms pull request #27489
Opened 2020-01-12 04:31 UTC by rajkumaar23

Pull Request for Issue #26881 

### Summary of Changes
- Appends a `page` param to the action on pagination links

### Testing Instructions
- Ensure the pagination doesn't break with this PR.
- Verify if `page` param is appended & modified while paginating.

### Expected result

### Actual result

### Documentation Changes Required
NIL

2020-01-12 05:03 UTC, Quy commented
Please revert coding style changes per [Joomla! Coding Standards](https://developer.joomla.org/coding-standards/html.html).

2020-01-12 05:05 UTC, rajkumaar23 commented
> Please revert coding style changes per [Joomla! Coding Standards](https://developer.joomla.org/coding-standards/html.html).

Okay sure, Can you let me know how to populate the pages that use pagination? Because I don’t seem to have enough data to paginate.

2020-01-12 05:11 UTC, Quy commented
Try installing `Testing Sample Data'. Then do a search on the frontend.

2020-01-12 05:32 UTC, rajkumaar23 commented
> Try installing `Testing Sample Data`. Then do a search on the frontend.

Thanks @Quy ! I was able tot test with the dummy data and I've reverted as per coding standards and fixed another bug in the PR too.

2020-01-12 06:19 UTC, rajkumaar23 commented
Thanks @Quy ! I was able to test with the dummy data and I've reverted as per coding standards and fixed another bug in the PR too.

2020-01-12 06:45 UTC, rajkumaar23 commented
@Quy Could you please review this PR ?

2020-01-12 17:43 UTC, ChristineWk commented
I have tested this item :red_circle: unsuccessfully on 81a7296c146a10982e01d857470335ea61c2771b<br /><br />When going to i.e. page 2 (on pagination link) I get error 404.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27489">issues.joomla.org/tracker/joomla-cms/27489</a>.</sub>

2020-01-12 17:57 UTC, rajkumaar23 commented
@ChristineWk Can you please check now ?

2020-01-12 18:16 UTC, ChristineWk commented
I have tested this item :red_circle: unsuccessfully on e3a52e5514ca7dba479c17a653905932fee700af<br /><br />Error 404 has gone. On 2nd page > in address bar I see: blog?limitstart=5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27489">issues.joomla.org/tracker/joomla-cms/27489</a>.</sub>

2020-01-12 18:17 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on e3a52e5514ca7dba479c17a653905932fee700af<br /><br />Error 404 has gone. On 2nd page > in address bar I see: blog?limitstart=5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27489">issues.joomla.org/tracker/joomla-cms/27489</a>.</sub>

2020-01-12 19:25 UTC, Quy commented on layouts/joomla/pagination/link.php
> +    	   				  var separator = uri.indexOf('?') !== -1 ? '&' : '?';
Please use tabs and not spaces for indentation.

2020-01-12 19:37 UTC, rajkumaar23 commented on layouts/joomla/pagination/link.php
> +    	   				  var separator = uri.indexOf('?') !== -1 ? '&' : '?';
Okay, sure.

2020-01-12 20:49 UTC, Hackwar commented
I agree that the initial issue is a bug, but I don't understand why the method from J3 isn't still used. Can someone please explain why we should do it this way?

2020-01-12 21:01 UTC, Fedik commented
I am sorry to say, but the fix are wrong, such JavaScript hacking not acceptable

2020-01-13 02:41 UTC, rajkumaar23 commented
> I am sorry to say, but the fix are wrong, such JavaScript hacking not acceptable

Since the pagination itself is done via Javascript, I couldn’t think of any other way to update the URL with the limitstart value. Could you suggest a better idea?

2020-01-13 02:43 UTC, rajkumaar23 commented
> I agree that the initial issue is a bug, but I don't understand why the method from J3 isn't still used. Can someone please explain why we should do it this way?

Can you please let me know how it was done in J3 ? I’m new to Joomla! and I checked the branches here, and everywhere it’s done in JavaScript only.

2020-01-13 03:00 UTC, rajkumaar23 commented on layouts/joomla/pagination/link.php
> +    	   				  var separator = uri.indexOf('?') !== -1 ? '&' : '?';
@Quy I have updated.

2020-01-13 06:48 UTC, SharkyKZ commented
In J3 frontend template had an override without JS in it.

Maybe in 4.0 we could do the other way around, make it JS-free by default and add an override for backend template instead.

2020-01-13 06:54 UTC, rajkumaar23 commented
I guess then the complete pagination code has to change if it has to be no-JS. All I’ve done is append the limitstart param to the form action, added to the already existing JS code that modifies the hidden ‘limitstart’ field in the form and triggers it. As far as this issue is concerned, the task was to make different URLs render different content.

2020-01-13 08:48 UTC, Fedik commented
You put all your "multi-line" javascript code in to oneclick attribute, do not do this ever.
Also please check how the `form` element works, you no need javascript to append a value that already there (use appropriate submit method GET/POST)

About correct fix, the pagination need to be a list of links, for frontend.
That @SharkyKZ already said

2020-01-13 08:58 UTC, rajkumaar23 commented
@Fedik I'm sorry, but I couldn't understand what you're trying to say. If I'm not wrong, do you mean all this pagination forms has to be GET, so the URL will have `limitstart` appended automatically ?

2020-01-13 09:07 UTC, Fedik commented
Pagination should be a list of links, without javascript, without form.

2020-01-13 09:09 UTC, rajkumaar23 commented
> Pagination should be a list of links, without javascript, without form.

@Fedik Okay, so you mean to say the current implementation for pagination has to be changed to links. I thought that was out of scope for the related issue. I'll check how to do it.

2020-01-13 09:15 UTC, Fedik commented
Check @SharkyKZ comment, it should be changed only for the site, and stay unchanged for administrator.

2020-01-13 09:17 UTC, rajkumaar23 commented
> Check @SharkyKZ comment, it should be changed only for the site, and stay unchanged for administrator.

Sorry! I'm new to Joomla! Can I get some guidance on what's the `override` he was talking about ?

2020-01-13 09:21 UTC, Fedik commented
I think these 2 links

https://docs.joomla.org/Layout_Overrides_in_Joomla#JLayout_Micro-Layout_Overrides
https://docs.joomla.org/J3.x:Sharing_layouts_across_views_or_extensions_with_JLayout

2020-01-13 09:24 UTC, SharkyKZ commented
Templates support layout overrides. You can copy `layouts/joomla/pagination/link.php` to `templates/cassiopeia/html/layouts/joomla/pagination/link.php` to create an override for frontend template and remove JS code there.

Or the other way around, copy the file as-is to backend template: `administrator/templates/atum/html/layouts/joomla/pagination/link.php` and then edit original file to remove JS code.

There are other alternatives to consider like creating multiple standard layouts and making them configurable in pagination calls.

2020-01-13 10:13 UTC, rajkumaar23 commented
@SharkyKZ Can you please check my latest commit if I've correctly understood what you told ?

2020-01-13 10:17 UTC, zero-24 requested changes

2020-01-13 10:17 UTC, zero-24 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$currentURL = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
hmm we should not hardcode http here we might should also better use `JUri` / `\Joomla\CMS\Uri\Uri`

2020-01-13 10:18 UTC, rajkumaar23 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$currentURL = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
Sure, thanks.

2020-01-13 10:33 UTC, rajkumaar23 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$currentURL = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
Is it fine now?

2020-01-13 11:11 UTC, Fedik commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$updatedURL = http_build_url($urlParts);
why you doing this?

2020-01-13 11:12 UTC, rajkumaar23 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$updatedURL = http_build_url($urlParts);
How else would I navigate to the next `page` without `limitstart` ?

2020-01-13 11:14 UTC, Fedik commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$updatedURL = http_build_url($urlParts);
use `href="<?php echo $item->link; ?>"` it already contain all you need

2020-01-13 11:16 UTC, rajkumaar23 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$updatedURL = http_build_url($urlParts);
I did var_dump on `$item->link` when I was on `/article-category-list` page, but the value was not current URL.

2020-01-13 11:19 UTC, Fedik commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$updatedURL = http_build_url($urlParts);
what URL was in your var_dump?
the `$item->link` contain a correct link for every pagination item, you no need to modify it, it already prepared in `Pagination` class

2020-01-13 11:21 UTC, rajkumaar23 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$updatedURL = http_build_url($urlParts);
I think I did a var_dump($item) in administrator page, and received different `link`. Thanks, will use that here.

2020-01-13 11:34 UTC, rajkumaar23 commented
@Fedik I think now everything is sorted.

2020-01-13 11:37 UTC, rajkumaar23 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +$updatedURL = http_build_url($urlParts);
Sorry, that was my mistake. I have used it now, thanks :)

2020-01-13 11:46 UTC, Fedik commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +	if ($item->base > 0)
you can remove this section, it was need for javascript

2020-01-13 11:46 UTC, Fedik commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +	$onClick = 'document.adminForm.' . $item->prefix . $limit . '; Joomla.submitform();return false;';
and this also not need anymore

2020-01-13 11:53 UTC, rajkumaar23 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +	$onClick = 'document.adminForm.' . $item->prefix . $limit . '; Joomla.submitform();return false;';
Done :+1: Removed.

2020-01-13 12:08 UTC, Fedik commented
Now it looks much better than first version of it :smiley: 
Left only a testing, I guess.

2020-01-13 12:11 UTC, rajkumaar23 commented
> Now it looks much better than first version of it smiley
> Left only a testing, I guess.

Haha. This is my first PR with so many comments. OpenSource contributions are indeed best in learning. Thanks! 🔥️

2020-01-13 18:30 UTC, Quy commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +	case $item->text === Text::_('JPREV') :
```suggestion
	case Text::_('JPREV') :
```

2020-01-13 18:37 UTC, rajkumaar23 commented on templates/cassiopeia/html/layouts/joomla/pagination/link.php
> +	case $item->text === Text::_('JPREV') :
Done.

2020-01-13 19:00 UTC, brianteeman commented
I am coming to this late but to me it is crazy that we need to create an override. If we can't make the core work with the default templates that it ships with there is something very wrong

2020-01-13 19:03 UTC, rajkumaar23 commented
> I am coming to this late but to me it is crazy that we need to create an override. If we can't make the core work with the default templates that it ships with there is something very wrong
Alright then, does having the start param in URL on administrator routes cause any issue? If not, I don’t think this override is required. I can edit the original link.php, but as I was told in this thread that only frontend needs to have that param in the URL, override was the only possible way

2020-01-13 19:05 UTC, brianteeman commented
Why does it have to be the same layout for both site and admin?

2020-01-13 19:07 UTC, rajkumaar23 commented
I didn’t get you @brianteeman :(

2020-01-13 20:37 UTC, Fedik commented
@brianteeman there was comment @SharkyKZ suggested to make "this" as default, and then make override for admin template (should be simple), or make them configurable in pagination calls to use different layout depend from needs (this more advanced topic).

Admin use different pagination to keep adminForm "state". The form has extra fields, like CSR token, option, view etc, and can have more depend from component. As far as I know.

2020-01-13 22:53 UTC, brianteeman commented
My view is that it should be
> or make them configurable in pagination calls to use different layout depend from needs

2020-01-14 10:09 UTC, rajkumaar23 commented
@Fedik What do you think could I possibly do to fix this ?

2020-01-14 13:10 UTC, Fedik commented
It is good as it is for now, it fixes the issue.

What was suggested is much complex work to do, and can be done any time later.

2020-01-14 13:27 UTC, rajkumaar23 commented
> It is good as it is for now, it fixes the issue.
> 
> What was suggested is much complex work to do, and can be done any time later.

Can someone test this ?

2020-01-14 13:29 UTC, brianteeman commented
Unless I am very much mistaken it is not complex at all
See #27516 for a very quick example

2020-01-14 14:12 UTC, Fedik commented
I think we have a different look on what is "configurable pagination" :wink: 

With your suggestion it still not possible to use simple links in backend, or javascript version on front end. It hardly can call "configurable".

The Pagination class allow to specify the layout, that allow to have 2 (an more) different layout at same time
https://github.com/joomla/joomla-cms/blob/4779815c0346c1ba273a6cac4b6d346771f1c8ba/libraries/src/Pagination/Pagination.php#L436-L442

A complexity here is to check all call of `$pagination->getPaginationLinks()` (both admin/site side) and adjust it to use specific layout, and make sure all works.

2020-01-14 14:29 UTC, brianteeman commented
> I think we have a different look on what is "configurable pagination" 😉

Maybe so but my PR resolves the issue in the original report without creating template overrides

2020-01-14 14:30 UTC, Fedik commented
yeap, that also ok, I don't mind

2020-01-14 14:41 UTC, brianteeman commented
as i said before 
> I am coming to this late but to me it is crazy that we need to create an override. If we can't make the core work with the default templates that it ships with there is something very wrong

2020-01-14 14:51 UTC, closed without merging