[4.0] Namespace FinderIndexerResponse
joomla/joomla-cms pull request #27591
Opened 2020-01-21 20:56 UTC by SharkyKZ

Pull Request for Issue # .

### Summary of Changes

Moves `FinderIndexerResponse` into its own file.

### Testing Instructions

Run Smart Search indexer.
Inspect the information in the modal.

### Expected result

Works like before.

### Documentation Changes Required

IDK.

2020-01-21 22:35 UTC, mbabker requested changes

2020-01-21 22:35 UTC, mbabker commented on libraries/extensions.classmap.php
> +JLoader::registerAlias('FinderIndexerResponse', '\\Joomla\\Component\\Finder\\Administrator\\Indexer\\Response', '5.0');
You shouldn't need this one in the mapping array, this response class is internal to the component and not something intended for use outside of the one controller the code was present in.

2020-01-21 22:35 UTC, mbabker commented on administrator/components/com_finder/Indexer/Response.php
> +namespace Joomla\Component\Finder\Administrator\Indexer;
I'd actually not put this class in the same namespace as the rest of the indexer.  The indexer namespace should be the code that's actually doing the indexing and should be considered library level API meant for extensions to build on and use, this class definitely doesn't fall in that category.

2020-01-22 03:20 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 9bf102867cd629eab7ac87a4a674a595e4cb82ad<br /><br />Test successful. Deleted index and re-indexed content, created new content and re-indexed, and confirmed that statistics still pull data correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27591">issues.joomla.org/tracker/joomla-cms/27591</a>.</sub>

2020-01-22 06:25 UTC, SharkyKZ commented on libraries/extensions.classmap.php
> +JLoader::registerAlias('FinderIndexerResponse', '\\Joomla\\Component\\Finder\\Administrator\\Indexer\\Response', '5.0');
Removed.

2020-01-22 06:25 UTC, SharkyKZ commented on administrator/components/com_finder/Indexer/Response.php
> +namespace Joomla\Component\Finder\Administrator\Indexer;
Moved to a helper class. Is that OK?

2020-01-22 14:34 UTC, mbabker commented on administrator/components/com_finder/Indexer/Response.php
> +namespace Joomla\Component\Finder\Administrator\Indexer;
Better than being in the indexer namespace.  Truthfully if you are insistent upon putting it in a namespace it is better off in a `Response` namespace, not a `Helper` namespace (unless there is some mandate that the only namespaces a component can use are Controller, Model, Table, View, Helper, and maybe Form; the entire point of namespaces is to organize and structure your code, there should not be a mandate to throw classes in existing namespaces if none of the existing make sense).

2020-01-22 15:49 UTC, SharkyKZ commented on administrator/components/com_finder/Indexer/Response.php
> +namespace Joomla\Component\Finder\Administrator\Indexer;
Moved to `Response` namespace.

2020-01-22 22:20 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 1bb0e235bebfdea86cda87e197f04a9af13246c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27591">issues.joomla.org/tracker/joomla-cms/27591</a>.</sub>

2020-01-24 11:34 UTC, merged

2020-01-24 11:34 UTC, wilsonge commented
Thanks!