[4.0 dev] fixed toolbar and toggler
joomla/joomla-cms pull request #27705
Opened 2020-01-29 10:54 UTC by ravisaxena23

Pull Request for Issue #27699

### Summary of Changes
Fixed CSS issue as shown in.
### Testing Instructions
open alert it can be closed easily
navbar icon show both cross and hamburger icon at respective time.

### Problem statement
![Screenshot (29)](https://user-images.githubusercontent.com/44205807/73349790-d6e1fa80-42b1-11ea-9679-c566bdad2082.png)
![Screenshot (30)](https://user-images.githubusercontent.com/44205807/73349810-dfd2cc00-42b1-11ea-90fc-c921281b3489.png)
### Expected result
![Screenshot (31)](https://user-images.githubusercontent.com/44205807/73349827-e82b0700-42b1-11ea-8fa7-f7e43502472a.png)

### Actual result
Same as Expected result.

### Documentation Changes Required

no change required.

2020-01-29 13:31 UTC, richard67 requested changes

2020-01-29 13:31 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +    }
```suggestion
    }
```
Please remove the trailing space after the closing curly bracket here.  You can just click the button to accept my suggested change to do so.

2020-01-29 13:31 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +
```suggestion

```
Please remove spaces from empty line here. You can just click the button to accept my suggested change to do so.

2020-01-29 14:10 UTC, ravisaxena23 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +    }
Done sir please review again

2020-01-29 16:08 UTC, richard67 commented
@ravisaxena23 Sorry, I can review only code style. That looks good to me right now. If the scss is right I can't really say, I'm not an scss expert. Maybe @brianteeman can review, or @C-Lodder ? And by the way, no need to call me "sir". Just say "Richard" ;-)

2020-01-29 16:10 UTC, richard67 reviewed
Code style and syntax look good to me. If the change of the CSS class "mm-collapsed" to "collapsed" is right or not I can't say.

2020-01-29 16:30 UTC, ravisaxena23 commented
Sure sir 😜

2020-01-29 20:33 UTC, richard67 commented
To be honest, I'm in doubt if the change of the CSS class from "mm-collapsed" to "collapsed" is right. As far as I know we use metismenu in J4 backend, and the "mm-" class prefix belongs to that. @brianteeman Could you check this?

2020-01-29 21:23 UTC, brianteeman commented
Will need checking carefully as we do indeed use mm- for Metis menu

2020-01-29 21:25 UTC, richard67 commented
@ravisaxena23 Meanwhile I've tested this PR, and it works.

Also I know meanwhile that the change of class "mm-collapsed" to "collapsed" is correct. The metismenu js (or any other js?) adds and removes the "collapsed" class when toggling the button.

The PR fixes the error that the lower button always shows the cross icon and not burger or cross depending on if collapsed or expanded.

Also an alert can be closed now.

So this PR does what it promised.

**But:** If the screen is really small enough that the button to close an alert is hidden by the top button (gears icon if collapsed) whithout this PR, then with this PR some text of the alert message is hidden by the button:

![pr-27705](https://user-images.githubusercontent.com/7413183/73398511-ed09ae00-42e5-11ea-9c7c-01a17652f9ea.png)

Not sure if this is acceptable. Maybe it would be better to change z-index of the alert so it comes in front of the gears button? Or change the z-index of the geard button so it comes behing the alert?

@brianteeman What do you think?

2020-01-29 21:52 UTC, richard67 commented
Hmm, the metismenu js seems to use "mm-collapsed" at least here:

![metismenu-js_1](https://user-images.githubusercontent.com/7413183/73400376-46bfa780-42e9-11ea-821b-71b96372e29a.png).

And when searching our sources for "mm-collapsed" I find:

```
./media/mod_menu/js/admin-menu.js:106:      sidebar.querySelector('.mm-collapse').classList.remove('mm-collapsed');
./media/mod_menu/js/admin-menu.es6.js:106:      sidebar.querySelector('.mm-collapse').classList.remove('mm-collapsed');
./media/vendor/metismenujs/js/metismenujs.js:50:        COLLAPSED: "mm-collapsed",
```

Am confused now why the icon toggling of the burger button doesn't work without this PR and works with it, while for the gears button nothing changes.

There must be sonething else wrong in our code, but I haven't found it yet and have to finish for today, is late here.

2020-01-29 22:02 UTC, brianteeman commented
check the code that I added for the gear button. I probably broke it all there

2020-01-29 22:05 UTC, richard67 commented
@brianteeman You remember which PR it was, or key words I could search? Or where code to check?

2020-01-30 09:14 UTC, brianteeman commented
I think it was #26513

2020-01-30 10:51 UTC, ravisaxena23 commented
@brianteeman @richard67 what if we decrease the size of gear button. Therefore it won't hide alert and modals text with full functionality can we do that should I try? @brianteeman @richard67 sir i had a question how yo test PR without accepting how anyone can do that?

2020-01-30 11:05 UTC, richard67 commented
> sir i had a question how yo test PR without accepting how anyone can do that?

@ravisaxena23 Sorry, I don't understand what you mean with that.

2020-01-30 11:42 UTC, ravisaxena23 commented
@richard67 I'm Saying can we do it? as you told earlier something can be done with z index. i had created a new css for gear button now it can look like this. it will not harm burger button as it has its own css after my new code update it will look like this should I update code or revert the changes done in gear button?
![Screenshot (33)](https://user-images.githubusercontent.com/44205807/73446749-57246080-4383-11ea-8f48-94597d0de0c8.png)

2020-01-30 11:48 UTC, ravisaxena23 commented
@richard67 I was asking how to test PRs without accepting there changes.

2020-01-30 12:04 UTC, richard67 commented
> @richard67 I'm Saying can we do it? as you told earlier something can be done with z index. i had created a new css for gear button now it can look like this. it will not harm burger button as it has its own css after my new code update it will look like this should I update code or revert the changes done in gear button?

The result look good, but I don't know how it is achieved when not seeing the code. Maybe you can paste it into a comment so we can see and tell our opinion? Or commit the changes to this PR and then we review it.

2020-01-30 12:14 UTC, richard67 commented
> @richard67 I was asking how to test PRs without accepting there changes.

I'm still not sure if I understand. When a PR is made, we first look on it and the changes it makes, and if necessary we comment it. That's review and that's what we are doing now.

Then for testing it we apply the changes in our local Joomla testing environment. this can be done with different tools, e.g. tortoise git, or with the Joomla patchtester in some case.

Then if necessary we use npm to compile the scss files into css. And then we test the PR. I've done that yesterday, and I saw need for discussion so I did not give a bad test result due to the button overlapping the alert text.

After test we mark the test result in the Joomla CMS issue tracker [https://issues.joomla.org/](https://issues.joomla.org/) . If the result is good, we mark it as success, and if the result is not as expected or the PR breaks something else, we mark it as not successful.

Then when a PR has at least 2 successful tests, we mark it with label "RTC", which means "ready to commit".

Peridocially our maintainers (I am not one, I am only a contributor like you are) check if there are PRs having RTC. They normally check it again with review, and if it looks good it is merged.

After merge the changes of the PR have been applied to the CMS code, and with the next release the changes will be available to all end users when they update their CMS.

Did you mean that with "accepting there changes", how a PR will go into the CMS finally? If not, please explain in other words or more precisely what you mean.

We have documentation available on https://docs.joomla.org for that (testing PRs), especially in 4.0 where you need composer and npm, but I'm at work now so don't have the time to search the links to particular docs. If you still have question let us know, then me or someone else who has time can later paste a few more links to documentation.

2020-01-30 14:54 UTC, ravisaxena23 commented
@richard67 @brianteeman after latest changes mobile view is updated and it don't hide any text or closing button please review
![Screenshot (34)](https://user-images.githubusercontent.com/44205807/73460371-61a02380-439e-11ea-9bd7-e2e384b6c00d.png)

2020-01-30 14:57 UTC, ravisaxena23 commented
> > @richard67 I was asking how to test PRs without accepting there changes.
> 
> I'm still not sure if I understand. When a PR is made, we first look on it and the changes it makes, and if necessary we comment it. That's review and that's what we are doing now.
> 
> Then for testing it we apply the changes in our local Joomla testing environment. this can be done with different tools, e.g. tortoise git, or with the Joomla patchtester in some case.
> 
> Then if necessary we use npm to compile the scss files into css. And then we test the PR. I've done that yesterday, and I saw need for discussion so I did not give a bad test result due to the button overlapping the alert text.
> 
> After test we mark the test result in the Joomla CMS issue tracker https://issues.joomla.org/ . If the result is good, we mark it as success, and if the result is not as expected or the PR breaks something else, we mark it as not successful.
> 
> Then when a PR has at least 2 successful tests, we mark it with label "RTC", which means "ready to commit".
> 
> Peridocially our maintainers (I am not one, I am only a contributor like you are) check if there are PRs having RTC. They normally check it again with review, and if it looks good it is merged.
> 
> After merge the changes of the PR have been applied to the CMS code, and with the next release the changes will be available to all end users when they update their CMS.
> 
> Did you mean that with "accepting there changes", how a PR will go into the CMS finally? If not, please explain in other words or more precisely what you mean.
> 
> We have documentation available on https://docs.joomla.org for that (testing PRs), especially in 4.0 where you need composer and npm, but I'm at work now so don't have the time to search the links to particular docs. If you still have question let us know, then me or someone else who has time can later paste a few more links to documentation.

@richard67 thank you sir for explaining the whole process."my English is weak"  you understood it and give me the answer it will help me a lot.

2020-01-30 14:59 UTC, ravisaxena23 commented
> > @richard67 I'm Saying can we do it? as you told earlier something can be done with z index. i had created a new css for gear button now it can look like this. it will not harm burger button as it has its own css after my new code update it will look like this should I update code or revert the changes done in gear button?
> 
> The result look good, but I don't know how it is achieved when not seeing the code. Maybe you can paste it into a comment so we can see and tell our opinion? Or commit the changes to this PR and then we review it.

I have commited boss please suggest me I just want to learn more and more ; )

2020-01-30 15:15 UTC, richard67 commented
> I just want to learn more and more ; )

Then the first thing you should learn is that we don't have any "boss" here.

2020-01-30 17:08 UTC, ravisaxena23 commented
> > I just want to learn more and more ; )
> 
> Then the first thing you should learn is that we don't have any "boss" here.

@richard67 okay please review code.

2020-01-30 18:15 UTC, richard67 commented
@ravisaxena23 I am the wrong guy to review (s)css because I'm not an expert in it. Maybe @C-Lodder can have a look?

2020-01-30 18:17 UTC, ravisaxena23 commented
> @ravisaxena23 I am the wrong guy to review (s)css because I'm not an expert in it. Maybe @C-Lodder can have a look?

okay

2020-01-30 18:17 UTC, richard67 reviewed
As said in my comment above I am the wrong guy to review scss. For example I don't know if we should use a variable for the z-index.

@C-Lodder I've pinged you because I know you know our (s)css well. The author of the PR seems to be a new contributor, so we should not discourage him.

2020-01-30 18:20 UTC, richard67 commented
@ravisaxena23 But of course I want to help, so if someone who knows our scss better than me has made a review and then (maybe after some corrections due to the review) you need tests, I promise I will test your PR.

2020-01-30 18:25 UTC, ravisaxena23 commented
@richard67 thank you you are great help how can I contact you or shall I ask my doubts in PR i will always create a PR for your guidance :stuck_out_tongue_winking_eye: haha

2020-01-30 18:38 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +    z-index: 1030;
I would say use one of these variables (https://github.com/joomla/joomla-cms/blob/7e0e9dc11f874655c17af339126651e3d71cdb36/administrator/templates/atum/scss/_variables.scss#L251), but the naming conventions don't really match.

2020-01-30 18:39 UTC, C-Lodder commented
SCSS properties are in the wrong order but Hound should be picking up on this.
Not sure why Hound is so temprimental

Other than that, code looks fine

2020-01-30 18:42 UTC, richard67 commented
> SCSS properties are in the wrong order but Hound should be picking up on this.
> Not sure why Hound is so temprimental

What would be the right order?

2020-01-30 18:53 UTC, C-Lodder commented
@richard67 Based on the current linter (https://github.com/joomla/joomla-cms/blob/4.0-dev/scss-lint.yml):
```
.toggler-toolbar {
  position: fixed;
  top: 20px;
  right: 10px;
  bottom: 20px;
  z-index: 1030;
  display: block;
  width: 70px;
  height: 70px;
  background: var(--atum-link-color);
  border: 8px solid var(--atum-bg-light);
  border-radius: 40px;
}
```

2020-01-30 18:56 UTC, richard67 commented
@C-Lodder Thanks.

@ravisaxena23 Could you impement C-Lodder's suggestions?

- Use a variable for the z-index, see [https://github.com/joomla/joomla-cms/pull/27705#discussion_r373122523](https://github.com/joomla/joomla-cms/pull/27705#discussion_r373122523)
- Change order of SCSS properties, see [https://github.com/joomla/joomla-cms/pull/27705#issuecomment-580400320](https://github.com/joomla/joomla-cms/pull/27705#issuecomment-580400320)

Thanks in advance.

2020-01-30 19:00 UTC, ravisaxena23 commented
Sure

2020-01-31 02:35 UTC, ravisaxena23 commented
@richard67 @C-Lodder  done that

2020-01-31 16:36 UTC, ravisaxena23 commented
@richard67 please review!

2020-01-31 16:39 UTC, richard67 approved these changes

2020-01-31 16:40 UTC, richard67 commented
Suggested changes have been implemented.

Now it needs 2 good tests, then all is fine. Will test later today or tomorrow. Am busy with something else now.

2020-02-01 11:06 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 811a47355fe009c047f2a6366b60a1630f085b8b<br /><br />Testing instructions:

1. Go to global configuration in backend and reduce screen width to the minimum possible.
2. Toggle the bottom round blue button with cross icon (should be a burger icon instead).
Result: Icon is always cross, does not change depending on expanded status of the admin menu at the bottom.
3. Provoke an alert to be shown, e.g. by entering invalid database name and trying to save.
Result: Alert is shown, but button to close it is hidden by the "gears" button.
4. Apply the patch of this PR and then run "npm i".
5. Clear broswer cache.
6. Repeat steps 1 to 3.
Results: The icon of the "burger" button changes as expected when toggling the button. It shows a cross icon to collapse the menu when the menu is expanded, and a burger icon when the menu is collapsed. The alert comes in front of the "gears" button so the cross button to close the alert is not hidden anymore.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-01 13:47 UTC, Quy commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> -
Revert.

2020-02-01 13:47 UTC, Quy commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> -
Revert

2020-02-01 14:30 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> -
@Quy Maybe you can propose code here and below so the author can apply your suggestions with 1 click? Or shall I do that?

2020-02-01 15:08 UTC, Quy commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> -
It won’t let me do it here inline. Please go for it.

2020-02-01 15:09 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> -
Me neither.

2020-02-01 15:10 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> -
Ah we have to select the line above!

2020-02-01 15:13 UTC, richard67 requested changes

2020-02-01 15:13 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
>      z-index: $zindex-mobile-toggle;
```suggestion
    z-index: $zindex-mobile-toggle;

```

2020-02-01 15:13 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
>      }
```suggestion
    }

```

2020-02-02 07:14 UTC, ravisaxena23 commented on administrator/templates/atum/scss/blocks/_sidebar.scss
>      }
done

2020-02-02 09:59 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on a7c26c232e9e067db96549ed44cceb2f4a1ebaee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 10:00 UTC, richard67 commented
Last 2 commits were only code style, so my previous test is still valid.

Hint for other testers: More detailed testing instructions than in the description see [my previous test result above](https://github.com/joomla/joomla-cms/pull/27705#issuecomment-581019024).

2020-02-02 14:11 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 74581950971c25418f0390da8a79038ad6235b6d<br /><br />Previous test is still valid, last merge was just a clean update to the base branch.

Hint for other testers: More detailed testing instructions than in the description see [my previous test result above](https://github.com/joomla/joomla-cms/pull/27705#issuecomment-581019024).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 16:42 UTC, drmenzelit commented
I have tested this item :white_check_mark: successfully on 74581950971c25418f0390da8a79038ad6235b6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 16:44 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 17:26 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +    right: 10px;
Does that work with rtl? Will test tomorrow. Please do not merge until tested.

2020-02-02 17:27 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +    right: 10px;
Ok, will remove RTC for the meantime.

2020-02-02 17:28 UTC, richard67 commented
I have not tested this item.<br /><br />Sorry, haven't tested with RTL languages. Will do so soon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 17:51 UTC, richard67 commented
@infograf768 You are right, it breaks RTL.

Before PR it is ok:
![test-pr-27705-rtl-before-patch](https://user-images.githubusercontent.com/7413183/73612528-dbc5e780-45ec-11ea-87f3-4cf9fe118a5d.png)

After PR the gears button is broken, i.e. still at the right hand side:
![test-pr-27705-rtl](https://user-images.githubusercontent.com/7413183/73612537-eb453080-45ec-11ea-8cbc-0e5e86695f77.png)

2020-02-02 17:52 UTC, richard67 commented
I have tested this item :red_circle: unsuccessfully on 74581950971c25418f0390da8a79038ad6235b6d<br /><br />For LTR it is ok, bit RTL is broken for the gears button, see screenshots in my previous comment.

@ravisaxena23 Do you think you can fix that?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 18:10 UTC, ravisaxena23 commented
> I have tested this item 🔴 unsuccessfully on [7458195](https://github.com/joomla/joomla-cms/commit/74581950971c25418f0390da8a79038ad6235b6d)
> 
> For LTR it is ok, but RTL is broken for the gears button, see screenshots in my previous comment.
> 
> @ravisaxena23 Do you think you can fix that?
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/27705](https://issues.joomla.org/tracker/joomla-cms/27705).

@richard67  I hope I have corrected RTL issue  please test again.

2020-02-02 18:11 UTC, infograf768 commented
Code would be
```
@include media-breakpoint-down(xs) {
  .toggler-toolbar {
    position: fixed;
    top: 20px;
    bottom: 20px;
    z-index: $zindex-alerts;
    display: block;
    width: 70px;
    height: 70px;
    background: var(--atum-link-color);
    border: 8px solid var(--atum-bg-light);
    border-radius: 40px;

    [dir=ltr] & {
      right: 10px;
    }
 
    [dir=rtl] & {
      left: 10px;
    }

```

to get
<img width="440" alt="Screen Shot 2020-02-02 at 19 06 26" src="https://user-images.githubusercontent.com/869724/73612799-4415c880-45ef-11ea-978b-ba15d375880a.png">

2020-02-02 18:12 UTC, ravisaxena23 commented
> [dir=ltr] & {
>       right: 10px;
>     }
>  
>     [dir=rtl] & {
>       left: 10px;
>     }

it was working fine whit LTR so i jus added code for RTL should i add code for ltr too?

2020-02-02 18:14 UTC, infograf768 commented
@ravisaxena23

It is better in that case and more legible to add both the ltr and rtl separated as it concerns only one aspect, so one line change instead of using auto.

2020-02-02 18:15 UTC, ravisaxena23 commented
> @ravisaxena23
> 
> It is better in that case and more legible to add both the ltr and rtl separated as it concerns only one aspect, so one line change instead of using auto.

@infograf768  Done it Please check.

2020-02-02 18:16 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +    [dir=ltr] & {
Please add a blank line before `[dir=ltr] & {`

2020-02-02 18:19 UTC, ravisaxena23 commented
> @ravisaxena23
> 
> It is better in that case and more legible to add both the ltr and rtl separated as it concerns only one aspect, so one line change instead of using auto.

@infograf768 done that

2020-02-02 18:21 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +
Looks like there are spaces to take off in this blank line. :) You are getting there.

2020-02-02 18:24 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +
In fact you deleted the blank line. Please add it back without spaces.

2020-02-02 18:26 UTC, ravisaxena23 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +
why spaces become issue? what problem they cause? @infograf768 please explain and Check Pr again

2020-02-02 18:26 UTC, ravisaxena23 commented
why spaces become issue? what problem they cause? @infograf768 please explain and Check Pr again

2020-02-02 18:28 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +    right: 10px;
Take it off. It is now in the `[dir=ltr] & {`

2020-02-02 18:31 UTC, infograf768 commented
> why spaces become issue? what problem they cause?

No issue, just code style. A blank line is blank, no tabs no spaces.

2020-02-02 18:32 UTC, ravisaxena23 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +    right: 10px;
I'm sorry I m not understanding please help me out.

2020-02-02 18:36 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +    right: 10px;
The code should be exactly as I pasted above.
```
@include media-breakpoint-down(xs) {
  .toggler-toolbar {
    position: fixed;
    top: 20px;
  // NO MORE right: 10px; as it is taken care below
    bottom: 20px;
    z-index: $zindex-alerts;
    display: block;
    width: 70px;
    height: 70px;
    background: var(--atum-link-color);
    border: 8px solid var(--atum-bg-light);
    border-radius: 40px;

    [dir=ltr] & {
      right: 10px;
    }
 
    [dir=rtl] & {
      left: 10px;
    }
```

2020-02-02 18:38 UTC, ravisaxena23 commented
> > why spaces become issue? what problem they cause?
> 
> No issue, just code style. A blank line is blank, no tabs no spaces.

@infograf768 please review again. and please help me out I'm unable to see space in my VS Code. also i was thinking to add prettier as a script it can format code then we dont have to bother for spaces but it may change all code format present right now. how is the idea? can we work on it?

2020-02-02 18:43 UTC, richard67 requested changes

2020-02-02 18:43 UTC, richard67 commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +    right: 10px;
```suggestion
```
@infograf768 means that you shall remove this line as suggested here because the same "right: 10px;" is done later below in the "[dir=ltr]" section.

2020-02-02 18:49 UTC, ravisaxena23 commented
@infograf768 done that too. sorry  forget we don't need it anymore after rtl and ltr

2020-02-02 19:00 UTC, richard67 commented
Looks good now, will test again after dinner. Here is 8 PM now ;-)

2020-02-02 19:41 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on a85c4c1404f052a2e53ba67a94c67aa6ce9eb531<br /><br />RTL working now, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 19:42 UTC, richard67 commented
@drmenzelit Could you test again, for LTR and also for RTL? For RTL you can use Persian language.

2020-02-02 19:49 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on a85c4c1404f052a2e53ba67a94c67aa6ce9eb531<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 19:51 UTC, infograf768 commented
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27705">issues.joomla.org/tracker/joomla-cms/27705</a>.</sub>

2020-02-02 19:54 UTC, richard67 commented
@ravisaxena23 Congratulations, your PR is ready to commit (RTC) now. Now you better just wait and don't touch it. A maintainer will merge it when appropriate. Only when we ping you here for soling conflicts, which may happen when someone else meanwhile changes a file which you have changed, too, and that other change is committed before yours, then this can happen. But as long as it's not the case, leave things as they are now. All fine and well done finally.

2020-02-02 20:05 UTC, merged

2020-02-02 20:06 UTC, infograf768 commented
Merged. thanks.

2020-02-04 22:18 UTC, brianteeman commented
Sorry but this is not correct - see #27805