#27744 allow showing ucm_content items with core_access=0. Similar fi…
joomla/joomla-cms pull request #27745
Opened 2020-01-31 20:39 UTC by svenbluege

…x for the similar tags module: https://github.com/joomla/joomla-cms/pull/996/commits/04161600e69ebed68ffcc6fa5619dc249323cc0e

Pull Request for Issue #27744 

### Summary of Changes

Allow displaying items with core_access=0 from _ucm_content in the Popular Tags module. The zero value is the result if a component does not use an access column.

### Testing Instructions

- create the popular tags module
- create an article
- create a content tag
- assign that tag to the article
- change the core_access value for the article representation in _ucm_content to 0

### Expected result
I see my tag in the popular tags module.

### Actual result
I don't see my tag in the popular tags module.

### Documentation Changes Required
No.

2020-02-02 14:40 UTC, richard67 requested changes

2020-02-02 14:40 UTC, richard67 commented on modules/mod_tags_popular/helper.php
> +			->where('(' . $db->quoteName('c.core_access') . ' IN (' . $groups . ') OR c.core_access = 0)')
```suggestion
			->where('(' . $db->quoteName('c.core_access') . ' IN (' . $groups . ') OR ' . $db->quoteName('c.core_access') . ' = 0)')
```

2020-02-02 14:45 UTC, richard67 commented
Will test later today.

2020-02-02 15:44 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 99ce3c3473f740916e28fe3c8897e9703b7344e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27745">issues.joomla.org/tracker/joomla-cms/27745</a>.</sub>

2020-02-02 18:45 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 99ce3c3473f740916e28fe3c8897e9703b7344e7<br /><br />The PR works as described, therefore the test is successful. 
But a question: When is core_access set to 0? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27745">issues.joomla.org/tracker/joomla-cms/27745</a>.</sub>

2020-02-02 18:47 UTC, richard67 commented
@chmst Is explained in the issue #27744 . There may be 3rd party components using an own acl handling and not the core one. We already have the same change as done here in the similar tags module, was once made by @Bakual . So it is ok.

2020-02-05 20:25 UTC, SharkyKZ commented
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27745">issues.joomla.org/tracker/joomla-cms/27745</a>.</sub>

2020-02-06 08:07 UTC, merged