fix change undefined $cspValue to $row in method compileAutomaticCspH…
joomla/joomla-cms pull request #27835
Opened 2020-02-07 06:07 UTC by nielsnuebel

This PR solves the problem of an undefined variable $cspValue copied from the method setCspHeader to compileAutomaticCspHeaderRules.

2020-02-07 15:14 UTC, jwaisner commented
@nielsnuebel Please provide test instructions for your PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27835">issues.joomla.org/tracker/joomla-cms/27835</a>.</sub>

2020-02-08 11:01 UTC, zero-24 requested changes
hmm row is only valid here: https://github.com/joomla/joomla-cms/pull/27835/files#diff-0ea3df9101b205d7c283ccf8ef68d621R359-R381 everything outside this is not correct. I agree that the current is wrong to.

2020-02-08 17:11 UTC, wilsonge commented on plugins/system/httpheaders/httpheaders.php
> +			if ($scriptHashesEnabled && strpos($row->directive, 'script-src') === 0)
I think this is supposed to be `$cspHeaderValue`

2020-02-11 14:28 UTC, richard67 commented
@nielsnuebel Could you check @wilsonge 's comment above and implement the suggested change, i.e. change `$row->directive` to `$cspHeaderValue->directive` in lines 412 and 418? This should then also solve @zero-24 ' review comment.

2020-02-12 05:07 UTC, nielsnuebel commented on plugins/system/httpheaders/httpheaders.php
> +			if ($scriptHashesEnabled && strpos($row->directive, 'script-src') === 0)
We may have to adjust the following line for a better name. https://github.com/joomla/joomla-cms/pull/27835/files#diff-0ea3df9101b205d7c283ccf8ef68d621L359 

@wilsonge no it is not. It runs to the following errors when I change it to $cspHeaderValue.
![image](https://user-images.githubusercontent.com/3214077/74304647-e9ead500-4d5d-11ea-895f-d875d541c315.png)

2020-02-12 05:17 UTC, nielsnuebel commented
testing instructions:

1. go to backend -> system -> Content Security Policy -> Options -> enabled CSP, Mode = Detect
2. go to site and CSP will be created
3. go back to backend -> system -> Content Security Policy -> Options -> enabled CSP, Mode = Automatic
![image](https://user-images.githubusercontent.com/3214077/74305043-0a675f00-4d5f-11ea-8111-835a9f532df5.png)
4. go to -> system -> Content Security Policy -> change an item status to published for Example 
![image](https://user-images.githubusercontent.com/3214077/74304951-cc6a3b00-4d5e-11ea-9575-8e18d17ccccd.png)
5. Set in Global Configuration error_reporting to development and now you will get some errors on frotend and one in the Backend depends https://github.com/joomla/joomla-cms/pull/26505

2020-02-13 23:39 UTC, Quy commented
Here is var_dump `$cspHeaderCollection`:
```
array(3) {
  ["default-src"]=>
  string(64) " 'unsafe-inline' 'unsafe-inline' 'unsafe-inline' 'unsafe-inline'"
  ["script-src"]=>
  string(0) ""
  ["style-src"]=>
  string(0) ""
}
```
and var_dump `$cspHeaderkey`:
```
string(11) "default-src"
```

Thus, one can assume `$cspValue->directive` should be `$cspHeaderkey`

2020-02-14 15:57 UTC, Quy commented on plugins/system/httpheaders/httpheaders.php
> +			if ($scriptHashesEnabled && strpos($row->directive, 'script-src') === 0)
```suggestion
			if ($scriptHashesEnabled && strpos($cspHeaderkey, 'script-src') === 0)
```

2020-02-14 15:57 UTC, Quy commented on plugins/system/httpheaders/httpheaders.php
> +			if ($styleHashesEnabled && strpos($row->directive, 'style-src') === 0)
```suggestion
			if ($styleHashesEnabled && strpos($cspHeaderkey, 'style-src') === 0)
```

2020-03-11 19:46 UTC, Quy commented
Closing in favor of #28318

2020-03-11 19:46 UTC, closed without merging