[4.0] User Menu heaader
joomla/joomla-cms pull request #27893
Opened 2020-02-11 10:06 UTC by brianteeman

The display of the user name in the user dropdown menu looks a little off due to lack of styling.

This add an icon before the username and the text "signed in as " as a prefix. (The text is as used on github)

There are css changes so npm i or node buuld.js --compile-css

### Before
![image](https://user-images.githubusercontent.com/1296369/74227320-206d1500-4cb6-11ea-8b05-997d73f43942.png)

### After
![image](https://user-images.githubusercontent.com/1296369/74227284-0a5f5480-4cb6-11ea-8c91-a4a3f17cf58d.png)

Apologies to @chmst I think you suggested somethign like this before and I was not in favour - I was wrong.

2020-02-11 10:11 UTC, Quy commented on administrator/modules/mod_user/tmpl/default.php
> +			<span class="fas fa-user-circle" aria-hidden="true"></span>
```suggestion
			<span class="fas fa-fw fa-user-circle" aria-hidden="true"></span>
```

2020-02-11 10:39 UTC, brianteeman commented on administrator/modules/mod_user/tmpl/default.php
> +			<span class="fas fa-user-circle" aria-hidden="true"></span>
why?

2020-02-11 10:47 UTC, Quy commented on administrator/modules/mod_user/tmpl/default.php
> +			<span class="fas fa-user-circle" aria-hidden="true"></span>
To make the icons/text line up. I assume the added CSS is to do that but I can’t tell from the screenshots.

2020-02-11 10:50 UTC, brianteeman commented on administrator/modules/mod_user/tmpl/default.php
> +			<span class="fas fa-user-circle" aria-hidden="true"></span>
doh - my fault - I was thinking fa-fw was white not wide.

2020-02-11 10:57 UTC, Quy commented
Is the added css still required?

2020-02-11 10:58 UTC, brianteeman commented
yes because thats the same css as on the items below the header

2020-02-11 11:00 UTC, Quy commented on administrator/templates/atum/scss/blocks/_header.scss
> +        [dire=rtl] & {
```suggestion
        [dir=rtl] & {
```

2020-02-11 11:01 UTC, brianteeman commented on administrator/templates/atum/scss/blocks/_header.scss
> +        [dire=rtl] & {
grrrh - too early and I need more coffee

2020-02-11 11:33 UTC, brianteeman commented
drone failures are the usual

2020-02-11 16:14 UTC, SharkyKZ requested changes
Please use variable in language string.

2020-02-11 16:14 UTC, SharkyKZ commented on administrator/language/en-GB/mod_user.ini
> +MOD_USER_TITLE="Signed in as"
```suggestion
MOD_USER_TITLE="Signed in as %s"
```

2020-02-11 16:14 UTC, SharkyKZ commented on administrator/modules/mod_user/tmpl/default.php
> +			<?php echo Text::_('MOD_USER_TITLE'); ?> <?php echo $user->name; ?>
```suggestion
			<?php echo Text::sprintf('MOD_USER_TITLE', $user->name); ?>
```

2020-02-11 16:37 UTC, brianteeman commented
@SharkyKZ thanks - wasn't thinking correctly this morning obviously

2020-02-11 16:39 UTC, Quy commented on administrator/language/en-GB/mod_user.ini
> +MOD_USER_TITLE="Signed in as"
@brianteeman Commit this too.

2020-02-11 17:05 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 5f0b3234a927512bba7195667829be22ce63c30c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27893">issues.joomla.org/tracker/joomla-cms/27893</a>.</sub>

2020-02-11 17:30 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 5f0b3234a927512bba7195667829be22ce63c30c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27893">issues.joomla.org/tracker/joomla-cms/27893</a>.</sub>

2020-02-11 17:30 UTC, jwaisner commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27893">issues.joomla.org/tracker/joomla-cms/27893</a>.</sub>

2020-02-12 08:19 UTC, merged

2020-02-12 08:20 UTC, brianteeman commented
thanks