[4.0] UX improvements admintemplate
joomla/joomla-cms pull request #27918
Opened 2020-02-13 12:37 UTC by angieradtke

### Summary of Changes
First step of  visuell cleaning up admin template. Changes (colours, spaces, font-sizes, ...) in scss for a better UX of the template. 
Not finished yet. Lack of hover-colors etc. 
Most changes made in the edit-article-view and at the sidenav.

### Testing Instructions
Just check and report back if you find problem in the listed areas.

### Expected result
Happy users

2020-02-13 12:38 UTC, brianteeman commented
Thanks so much for taking this on.

2020-02-13 12:43 UTC, angieradtke commented
@dgrammatiko @Hackwar @wilsonge @HLeithner more conversation here :-)

2020-02-13 12:45 UTC, rdeutz commented
Welcome and congratulations for your first PR :-)

2020-02-13 12:47 UTC, brianteeman commented
.com_login .sidebar-wrapper .main-brand

change from atum-text-light

2020-02-13 12:48 UTC, brianteeman commented
.quick-icons .quickicon a.success

change from color: fff

2020-02-13 12:50 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/74437011-513c7e00-4e5f-11ea-91a0-b9fd2928749d.png)

.header .fa-angle-down ==> increase margin-left

2020-02-13 12:52 UTC, angieradtke commented
Stop Brian, it is work in progress. Robert told me I have to make that pull-request now. I'm not finished.
Please take an  overview first and tell me if I go in the right direction

2020-02-13 12:53 UTC, brianteeman commented
OK. will do
Looks awesome so far - I am only seeing very minor tweaks

2020-02-13 12:58 UTC, brianteeman commented
So the only real things that are not "tweaks" would be the box-shadow on the inputs and the delay on the transitions for the buttons - see below - otherwise keep up the good work

### Now
![image](https://user-images.githubusercontent.com/1296369/74437513-24d53180-4e60-11ea-8f7c-221754617b4f.png)

### Better???
![image](https://user-images.githubusercontent.com/1296369/74437622-54843980-4e60-11ea-8a0d-98032bfd8975.png)


Animation/hover looks off - maybe the icon and the button should change at the same time

![anguie](https://user-images.githubusercontent.com/1296369/74437717-80072400-4e60-11ea-9be4-410fcd120319.gif)

2020-02-13 13:01 UTC, bembelimen commented
Thank you @angieradtke for your work.

2020-02-13 13:05 UTC, angieradtke commented
The width of the input fields border is important for accessibillty.  Shall we make them and the boxshadow configurable? Can be  a nice accessibility-feature with less  effort.

2020-02-13 13:11 UTC, dgrammatiko commented
> Animation/hover looks off - maybe the icon and the button should change at the same time

Transitions should have the same value, something like:
```css
  transition: opacity 0.2s ease;
```

Another trick I do on the clickable items is:
```css
/* Normal state */
  transform: scale(1);

/* Clicked state */
  transform: scale(0.95);
```

2020-02-13 13:25 UTC, brianteeman commented
> The width of the input fields border is important for accessibillty. Shall we make them and the boxshadow configurable? Can be a nice accessibility-feature with less effort.

I agree when you have focus on the input that it should have some clear highlighting but I dont see the need for it on everything all the time. Plus currently the shadow changes from blue to grey on focus so that is failing a11y ;)

2020-02-13 13:45 UTC, angieradtke commented
Do we need the sidebar on the login-screen?

2020-02-13 13:51 UTC, brianteeman commented
Personally not and the links are silly. But others were very insistent on that

2020-02-13 13:54 UTC, angieradtke commented
> 
> 
> Personally not and the links are silly. But others were very insistent on that

I think  we shouldn't give  more infos as needed at that place, because it could be seen by not authorized persons

2020-02-13 13:55 UTC, angieradtke commented
Where can I fix  the missing cancel  button at the new -article- view?

2020-02-13 13:56 UTC, dgrammatiko commented
> Do we need the sidebar on the login-screen?

Her's an idea:
- since for whatever reasons some people need those links add them in a detail element with a title Help or something similar after the login button. Clean approach

2020-02-13 13:58 UTC, brianteeman commented
> Where can I fix the missing cancel button at the new -article- view?

You put it in the "existing records" part of the if/else checking for new items

2020-02-13 13:58 UTC, dgrammatiko commented
> Do we need the sidebar on the login-screen?
It's the if/else that needs patching 

https://github.com/joomla/joomla-cms/blob/92727dd90a8604bfcd12b5fba81d54bc168799e2/administrator/components/com_content/src/View/Article/HtmlView.php#L222

2020-02-13 18:44 UTC, richard67 commented on administrator/components/com_content/View/Article/HtmlView.php
> +			$toolbar->cancel('article.cancel', 'JTOOLBAR_CLOSE');
```suggestion

			$toolbar->cancel('article.cancel', 'JTOOLBAR_CLOSE');
```

2020-02-13 18:47 UTC, richard67 commented
@angieradtke In future when we have to make a new admin template for J5, can we order that directly from you? That would save us a lot of time ;-)

2020-02-13 18:58 UTC, richard67 commented
@angieradtke Since PR #27687 has been merged, some files have moved to other place (subdirectory "src"), e.g. file `administrator/components/com_content/View/Article/HtmlView.php` has bee moved to `administrator/components/com_content/src/View/Article/HtmlView.php`. So this PR here can't be easily applied on the current 4.0-dev branch.

Do you think you can fix that? It might not be easy due to merge conflicts. In this case let us know here and I am sure everybody who is able to and reads it and has a bit time will do all to suport you.

2020-02-13 19:40 UTC, angieradtke commented
> Do you think you can fix that? It might not be easy due to merge conflicts. In this case let us know here and I am sure everybody who is able to and reads it and has a bit time will do all to suport you.

Tomorrow Robert will help me to make all these fixes, so that I have more time to care about the things I know about  .-) For every help I'm thankful

2020-02-13 19:43 UTC, richard67 commented
We have to be thankful to you.

2020-02-13 19:47 UTC, angieradtke commented
![filter](https://user-images.githubusercontent.com/1172403/74472305-fd06bd80-4ea1-11ea-92cd-8009f6bc0671.png)

Where can I move  the filter options in front of the search?

2020-02-13 20:19 UTC, dgrammatiko commented
> Where can I move the filter options in front of the search?

Either 
https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/searchtools/default.php
or any of the files in the subdirectory (don't remember from head)

2020-02-14 08:09 UTC, angieradtke commented
What do you think?

![switcher](https://user-images.githubusercontent.com/1172403/74512894-8ef5e100-4f09-11ea-9909-be7a26d5da05.png)

and where to change  if you like  System-Template or Autum?

2020-02-14 09:08 UTC, astridx commented
@angieradtke Do you mean adding `&tmpl=component` to the url?

2020-02-14 10:51 UTC, angieradtke commented
@astridx 
no we can change it here:  \build\media_source\system\scss\fields\switcher.scss 
or override this in the template

2020-02-14 11:08 UTC, angieradtke commented
@astridx sorry I'm taking about the switcher

2020-02-14 12:31 UTC, rdeutz commented
If we agree to use it anywhere than it should be changed in  \build\media_source\system\scss\fields\switcher.scss maybe make a seperate PR for this change

2020-02-14 16:21 UTC, brianteeman commented
https://github.com/joomla/joomla-cms/pull/27926#issuecomment-586359559

2020-02-15 23:30 UTC, korenevskiy commented
@angieradtke see this my sketch sketches.
![Joomla 4 Editor 2](https://user-images.githubusercontent.com/6898474/74596717-34bd6300-5064-11ea-96a4-e7327441040e.png)
![Joomla 4 Editor](https://user-images.githubusercontent.com/6898474/74596718-39821700-5064-11ea-97e6-aa8162af3962.png)
![Joomla 4 Articles](https://user-images.githubusercontent.com/6898474/74596721-3c7d0780-5064-11ea-9ecb-306098cb034e.png)

2020-02-16 00:50 UTC, korenevskiy commented
I also suggest making switches
![J4 publish-+](https://user-images.githubusercontent.com/6898474/74597321-a39fb980-506e-11ea-885e-ffbf62b6a503.png)
I absolutely agree that the top status bar should be blue.
My drafts are slightly different. Since all the styles I did in the Internet browser panel. After changing the status, the page reloads to the default styles and my modifications disappear. 
I don't know how to use SASS, I can offer my own styles in CSS.

2020-02-16 09:30 UTC, bembelimen commented
> 
> 
> Do we need the sidebar on the login-screen?

> 
> 
> Personally not and the links are silly. But others were very insistent on that

For example me :) The sidebar is not about the links, it's about the possibility to add content there. Giving advices for your customers etc. The links are just placeholders so to speak (which could help anyways)

2020-02-16 09:34 UTC, bembelimen commented
> 
> 
> I also suggest making switches (Yes/No)
> ![GIF Вс 16 02 2020 4-12-07](https://user-images.githubusercontent.com/6898474/74597572-9ab0e700-5072-11ea-958e-7710dc8048ea.gif)

The problem with included texts (which was a benefit from, I guess Brian did it, the current solution) is, that you're very limited in text length.

2020-02-16 09:46 UTC, Bakual commented
> The problem with included texts (which was a benefit from, I guess Brian did it, the current solution) is, that you're very limited in text length.

The button itself should not have long texts anyway. The "what" should be in the label, the button should be simple "yes/no".

2020-02-16 09:48 UTC, brianteeman commented
Included texts is not going to be realistically possible in a multilanguage system. It places too great a restriction on the use.

2020-02-16 09:50 UTC, richard67 commented
In the example above I would make a group with label "Notify before" and then for the particular buttons use lables "day", "5 days" and so on, and use yes no for the values.

The values should be so that not only the color gives the information if on or off but also some text. The position of the handle left or right is in my opinion also not enough info in addition to the color. I.e. if in the example above you are color blind and don't know about the meaning of the position of the handle, you don't know if it is on or off.

2020-02-16 10:49 UTC, brianteeman commented
"Notify before" would not be a label - it would be part of a sentence. That is not good

Your comments about the use of color to convey meaning are also correct. We should not.

2020-02-16 10:52 UTC, richard67 commented
@brianteeman 
```
Notify before ...
... day:
... 5 days:
```
would complete the sentence.

But I agree, it's not nice.

2020-02-16 10:53 UTC, brianteeman commented
which does not work if you are using a screen reader - therefore it is wrong ;)

2020-02-16 13:17 UTC, Bakual commented
Before making changes to the switcher to make it look like button groups, we could as well just use button groups: https://github.com/joomla/joomla-cms/pull/27952 😄

2020-02-16 13:19 UTC, brianteeman commented
https://github.com/joomla/joomla-cms/pull/27918#issuecomment-586360460

2020-02-16 13:27 UTC, angieradtke commented
> 
> 
> @angieradtke see this my sketch sketches.
> ![Joomla 4 Editor 2](https://user-images.githubusercontent.com/6898474/74596717-34bd6300-5064-11ea-96a4-e7327441040e.png)
> ![Joomla 4 Editor](https://user-images.githubusercontent.com/6898474/74596718-39821700-5064-11ea-97e6-aa8162af3962.png)
> ![Joomla 4 Articles](https://user-images.githubusercontent.com/6898474/74596721-3c7d0780-5064-11ea-9ecb-306098cb034e.png)

the border-radius ist located in a variable and so easy to change  .-)

2020-02-16 14:12 UTC, richard67 commented
@angieradtke I've just made PR [https://github.com/angieradtke/joomla-cms/pull/1](https://github.com/angieradtke/joomla-cms/pull/1) to your repo to update this branch to latest 4.0-dev including solve merge conflicts. Check the description and my comment there about how to proceed. If all ok, merge, else ping me here or in that PR there or by email.

2020-02-16 14:41 UTC, richard67 commented
@brianteeman I have helped @angieradtke with solving merge conflicts to 4.0-dev so this PR is up to date now. One of these conflicts was between changes for a[role=tab] and those your recently merged PR #27860 in file `administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss`. Could you check if I have solved this conflict in the right way, i.e. if this PR here is right now or if your change from #27860 has to be applied again, and if necessary make a PR to Angie's branch of this PR? Thanks in advance for helping.

2020-02-16 14:42 UTC, richard67 commented
@infograf768 I have helped @angieradtke with solving merge conflicts to 4.0-dev so this PR is up to date now. One of these conflicts was between changes for `.custom-select` and those your recently merged PR #27864 in file `administrator/templates/atum/scss/vendor/bootstrap/_custom-forms.scss`. Could you check if I have solved this conflict in the right way, i.e. if this PR here is right now or if your change from #27864 has to be applied again, and if necessary make a PR to Angie's branch of this PR? Thanks in advance for helping.

2020-02-16 15:18 UTC, richard67 commented
@angieradtke The font size of the Update Check quick-icons on the admin panel is too big for the button and also too big compared with the other icons, e.g. System icons at the top:

![angieradtke-admintemplate-quickicons-font-size](https://user-images.githubusercontent.com/7413183/74607243-79cead00-50d7-11ea-9383-5f40debb2603.png)

Maybe some selector needs to be modified in file `administrator/templates/atum/scss/blocks/_quickicons.scss` to get the sasme, smaller `.875rem` font size (I think its variable value `$quickicon-icon-size`), but I haven't already found the right one.

Do you think you can fix that?

2020-02-16 16:23 UTC, brianteeman commented
@richard67 This is a proof of concept - work in progress and as stated
> Most changes made in the edit-article-view and at the sidenav.

So please help @angieradtke out by not commenting on anything other than that she asks for feedback on

2020-02-16 16:36 UTC, angieradtke commented
  Thanks a lot guys  .-)
   At the moment 'm fighting with my local installation. It is broken 
after I  took the pull request.

Error: Class 'Joomla\Module\Menu\Site\Helper\MenuHelper' not found: 
Class 'Joomla\Component\Actionlogs\Administrator\Plugin\ActionLogPlugin' 
not found

I'm not sure what  to do best  solve this issue issue.


Am 16.02.2020 um 17:23 schrieb Brian Teeman:
>
> @richard67 <https://github.com/richard67> This is a proof of concept - 
> work in progress and as stated
>
>     Most changes made in the edit-article-view and at the sidenav.
>
> So please help @angieradtke <https://github.com/angieradtke> out by 
> not commenting on anything other than that she asks for feedback on
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/joomla/joomla-cms/pull/27918?email_source=notifications&email_token=AAI6HMYIYEEUFJK7BNH5JXDRDFR7TA5CNFSM4KURTI42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4LN2Y#issuecomment-586725099>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAI6HMZJHSBWWAJQMZOPOCLRDFR7TANCNFSM4KURTI4Q>.
>

2020-02-16 16:39 UTC, brianteeman commented
go to the libraries folder  and delete autoload_psr4.php

Then refresh and it will be rebuilt

2020-02-16 16:39 UTC, richard67 commented
> go to the libraries folder and delete autoload_psr4.php
> 
> Then refresh and it will be rebuilt

Confirmed. Brian was just 10 seconds faster than me.

2020-02-16 16:44 UTC, angieradtke commented
Hallelujah .-)  thank you  Brian .-)

Am 16.02.2020 um 17:39 schrieb Brian Teeman:
>
> go to the libraries folder and delete autoload_psr4.php
>
> Then refresh and it will be rebuilt
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/joomla/joomla-cms/pull/27918?email_source=notifications&email_token=AAI6HMZI5NZQMQAKXOUKLELRDFT2VA5CNFSM4KURTI42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4LZLI#issuecomment-586726573>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAI6HM3Q7ICZQBAMBKW3MPTRDFT2VANCNFSM4KURTI4Q>.
>

2020-02-16 16:49 UTC, angieradtke commented
![edit](https://user-images.githubusercontent.com/1172403/74608828-a0dfab80-50e4-11ea-81bb-83e4fc773cad.png)

is your article-edit Layout broken as well?

2020-02-16 17:04 UTC, SharkyKZ commented
Run `npm i`.

2020-02-16 17:58 UTC, richard67 commented
@angieradtke If Sharky's tip in previous comment is not eniugh let me know, then I can provide more steps to clean up.

2020-02-16 18:12 UTC, angieradtke commented
supi, thank you  it works .-)

Time for CSS .-)

Am 16.02.2020 um 18:04 schrieb SharkyKZ:
>
> Run |npm i|.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/joomla/joomla-cms/pull/27918?email_source=notifications&email_token=AAI6HM73S3VFE3KUGE5MSGLRDFWYXA5CNFSM4KURTI42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4MNEI#issuecomment-586729105>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAI6HM27LOY3YQUEBGXNG7TRDFWYXANCNFSM4KURTI4Q>.
>

2020-02-17 07:29 UTC, infograf768 commented
@angieradtke 
please correct atum template-rtl.scss

It should be
```
    [class*=' fa-'],
    [class^='fa-'],
    [class^='icon-'],
    [class*=' icon-'],
    [class^='#{$fa-css-prefix}-'],
    [class*=' #{$fa-css-prefix}-'] {
      margin: 0 -1.625rem 0 1rem;
    }
```
instead of
```
    [class*=' fa-'],
    [class^='fa-'],
    [class^='icon-'],
    [class*=' icon-'],
    [class^='#{$fa-css-prefix}-'],
    [class*=' #{$fa-css-prefix}-'] {
      margin: 0 -27px 0 27px;
    }
```
This will correct the Help and Options buttons (as well as other similar type of buttons)
from

<img width="929" alt="Screen Shot 2020-02-17 at 07 29 03" src="https://user-images.githubusercontent.com/869724/74630514-08d0d900-515b-11ea-9700-08a8b5489806.png">


to

<img width="541" alt="Screen Shot 2020-02-17 at 07 57 10" src="https://user-images.githubusercontent.com/869724/74630585-2bfb8880-515b-11ea-94b6-9f3b0eb154f7.png">

Also, please modify _header.scss to 
```
  .badge {
    position: absolute;
    top: 0.4rem;

    [dir=ltr] & {
      left: 50%;
      margin-left: 0.8rem;
    }

    [dir=rtl] & {
      right: 50%;
      margin-right: 0.8rem;
    }
  }

  .fa-angle-down {
    position: absolute;
    top: 0.9rem;

    [dir=ltr] & {
      left: 50%;
      margin-left: -1.8rem;
    }

    [dir=rtl] & {
      right: 50%;
      margin-right: -1.8rem;
    }
  }
```

in order to separate more the angle-down icon from the related icon and correct RTL

Before change

<img width="93" alt="Screen Shot 2020-02-17 at 08 24 34" src="https://user-images.githubusercontent.com/869724/74632166-0a040500-515f-11ea-9360-31ab4fece5f6.png">

after change we will get for LTR

<img width="476" alt="Screen Shot 2020-02-17 at 08 18 04" src="https://user-images.githubusercontent.com/869724/74631901-77fbfc80-515e-11ea-9e17-ae52d068bdd7.png">

for RTL

<img width="587" alt="Screen Shot 2020-02-17 at 08 17 40" src="https://user-images.githubusercontent.com/869724/74631924-84805500-515e-11ea-9ed4-06e212e06985.png">

2020-02-17 08:00 UTC, angieradtke commented
Hi JM,

still the master of RTL .-)

  done - thank you .-)

Am 17.02.2020 um 08:29 schrieb infograf768:
>
> @angieradtke <https://github.com/angieradtke>
> please correct atum template-rtl.scss
>
> It should be
>
> |[class*=' fa-'], [class^='fa-'], [class^='icon-'], [class*=' icon-'], 
> [class^='#{$fa-css-prefix}-'], [class*=' #{$fa-css-prefix}-'] { 
> margin: 0 -1.625rem 0 1rem; } |
>
> instead of
>
> |[class*=' fa-'], [class^='fa-'], [class^='icon-'], [class*=' icon-'], 
> [class^='#{$fa-css-prefix}-'], [class*=' #{$fa-css-prefix}-'] { 
> margin: 0 -27px 0 27px; } |
>
> This will correct the Help and Options buttons (as well as other 
> similar type of buttons)
> from
>
> Screen Shot 2020-02-17 at 07 29 03 
> <https://user-images.githubusercontent.com/869724/74630514-08d0d900-515b-11ea-9700-08a8b5489806.png>
>
> to
>
> Screen Shot 2020-02-17 at 07 57 10 
> <https://user-images.githubusercontent.com/869724/74630585-2bfb8880-515b-11ea-94b6-9f3b0eb154f7.png>
>
> Also, please modify _header.scss to
>
> |.badge { position: absolute; top: 0.4rem; [dir=ltr] & { left: 50%; 
> margin-left: 0.8rem; } [dir=rtl] & { right: 50%; margin-right: 0.8rem; 
> } } .fa-angle-down { position: absolute; top: 0.9rem; [dir=ltr] & { 
> left: 50%; margin-left: -1.8rem; } [dir=rtl] & { right: 50%; 
> margin-right: -1.8rem; } } |
>
> in order to separate more the angle-down icon from the related icon 
> and correct RTL
>
> Before change
>
> Screen Shot 2020-02-17 at 08 24 34 
> <https://user-images.githubusercontent.com/869724/74632166-0a040500-515f-11ea-9360-31ab4fece5f6.png>
>
> after change we will get for LTR
>
> Screen Shot 2020-02-17 at 08 18 04 
> <https://user-images.githubusercontent.com/869724/74631901-77fbfc80-515e-11ea-9e17-ae52d068bdd7.png>
>
> for RTL
>
> Screen Shot 2020-02-17 at 08 17 40 
> <https://user-images.githubusercontent.com/869724/74631924-84805500-515e-11ea-9ed4-06e212e06985.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/joomla/joomla-cms/pull/27918?email_source=notifications&email_token=AAI6HMZ6VGWE3ZNTRTD2BDLRDI4FTA5CNFSM4KURTI42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL5KWJA#issuecomment-586853156>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAI6HM44UAJ6FBKGXLOIV5LRDI4FTANCNFSM4KURTI4Q>.
>

2020-02-17 08:06 UTC, infograf768 commented
👍

2020-02-17 12:29 UTC, angieradtke commented
adding gradients to the quickicons 
![gradients](https://user-images.githubusercontent.com/1172403/74653901-74319f80-5189-11ea-8d51-1700c89ec1a3.png)

2020-02-17 14:04 UTC, angieradtke commented
changed side-nav
![sidenav](https://user-images.githubusercontent.com/1172403/74660605-b8776c80-5196-11ea-9b30-67ee31f05255.png)

2020-02-17 15:32 UTC, angieradtke commented
![error](https://user-images.githubusercontent.com/1172403/74667107-04301300-51a3-11ea-893e-5260e36bde59.png)

2020-02-17 15:33 UTC, brianteeman commented
Probably not - what error are you getting

2020-02-17 15:43 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_quickicons.scss
> +      font-size:.875rem;
space after :

2020-02-17 15:43 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_sidebar-nav.scss
> +  background:var(--atum-sidebar-bg) !important;
space after :

2020-02-17 15:44 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_sidebar-nav.scss
> +    border-bottom:solid 1px var(--atum-bg-light);
space after :

2020-02-17 15:44 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_sidebar-nav.scss
> +      display:block;
space after:

2020-02-17 15:45 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_sidebar-nav.scss
> +      padding:  0.35rem 0.35rem 0.35rem 1.2rem;
one space too much after :

2020-02-17 15:45 UTC, brianteeman commented
@infograf768 please let @angieradtke work on the template and leave the comments about code style until she is finished and then they can all be fixed in one go. Many automatically by the lint

2020-02-17 15:47 UTC, infograf768 commented on administrator/templates/atum/scss/blocks/_sidebar-nav.scss
> +        top:0.75rem;
line 40, 44, 45, 46 space after :

2020-02-18 10:09 UTC, brianteeman commented
Could you take a look at all the instances of transitions like `.2s ease-in-out` on the icons please

I find it very distracting that icons change on hover at a different time to the associated text. Either there should be no transition or the transition should be applied to the text as well as the icon

## current 
![with](https://user-images.githubusercontent.com/1296369/74725884-6b4ad780-5236-11ea-8e27-91932849e95e.gif)

## without any transition
![none](https://user-images.githubusercontent.com/1296369/74726013-a5b47480-5236-11ea-9eba-a562ae9d6d50.gif)

2020-02-18 12:15 UTC, brianteeman commented
That's great - thanks - can you look at the toolbar buttons as well please

![toolbar](https://user-images.githubusercontent.com/1296369/74735321-59723000-5248-11ea-91a6-6d7859739b69.gif)

2020-02-18 15:16 UTC, N6REJ commented
@angieradtke to help make it clearer for people it's a draft you might change your title to 
[4.0] [DRAFT] UX improvements admintemplate

2020-02-18 16:11 UTC, brianteeman commented
thx @angieradtke

2020-02-19 08:47 UTC, angieradtke commented
I spent a week working intensively with the autum-template.
At the beginning I  had to understand the basic structure and setup. 
 I'm not very familiar with Git and I certainly made a lot of code style mistakes.
But I still hope that I could help.

I think the basis of the template is quite good, otherwise I wouldn't have been able to make so many adjustments so quickly. 

I would like to finish this pull request by now, because otherwise it gets too big and I don't know if I marched in the right direction at all.

This is primarily a proposal for the visual design
There are still many views to be edited and adjusted. 

It is certainly important for many uninvolved people to know that the color  is controlled by variables and  therefore customisable. The color of the header can be changed as well as the color of all links. etc. This should be communicated to steer the discussions about colors in the right direction.

It is important now to  decide together on a basic colour concept that creates the broadest possible consensus.  I think blue is always good.
However, when choosing the colour shade, we have to keep the colour contrasts ( Accessibilty) in mind. I have now made a proposal here, which is to be checked for approval.
 
When designing the input fields, I am not sure about the choice of borders and boxshadows. We need a good balance between lightness and enough contrast.  
It's not that simple. To keep us flexible here, we find both values as variables. 

I couldn't take a look at al views yet and have worked on the top level first. What bothers me now is the unsightly display of the error messages. But this can be changed first when the HTML output is unified.  Sometimes the code comes from the php-File sometimes from the JS.
I would like the surrounding <html> elements to be unified and only output when they are needed.  Afterwards I think it would be very important to revise the media manager. 

Basically all files should be checked for missing or unnecessary variables. This can become quite complex. I hope I could help for now and thank Brian for his input.

2020-02-19 08:56 UTC, richard67 reviewed
Tabs, not spaces

2020-02-19 08:56 UTC, richard67 commented on layouts/joomla/searchtools/default/bar.php
> +	    <div>
```suggestion
		<div>
```

2020-02-19 10:35 UTC, rdeutz commented
I want to merge this PR as fast as possible, I know there are issues and we might break things on other plances, but I do think that we can work better parallel when we merge the state we have now. So if someone sees big show stopper, we have to fix before I merge this, please let me know.  

In the meantime I will have a look why the test are failing.

2020-02-19 10:42 UTC, brianteeman commented
>  if someone sees big show stopper, we have to fix before I merge this, please let me know.

I am still not in favour of changing the switcher back to two buttons. I would be much happier if that was removed from here and dealt with as a separate issue.

2020-02-19 11:04 UTC, ciar4n commented
> I want to merge this PR as fast as possible, I know there are issues and we might break things on other plances, but I do think that we can work better parallel when we merge the state we have now. So if someone sees big show stopper, we have to fix before I merge this, please let me know.

The same was done with the last major update of this template. Atum CSS is full of redundant rules, with every iteration just adding more CSS with little consideration for the CSS codebase as a whole. I'm not saying this PR is the same but I know in the last major PR, a fraction of these made redundant rules were pointed out. The PR was merged regardless, using the same excuse, them same redundant rules are still there.

2020-02-19 11:09 UTC, angieradtke commented
> them same redundant rules are still there.

 I wrote that as well and everybody would be thankful if you can clean it up with your expertise

2020-02-19 11:10 UTC, brianteeman commented on administrator/components/com_content/tmpl/article/edit.php
> +				<div class="">
looks like an error to me

2020-02-19 11:11 UTC, brianteeman commented on layouts/joomla/searchtools/default/bar.php
> +		<div>
looks like this div is not required

2020-02-19 11:13 UTC, brianteeman commented
As this template PR is 99% scss and not rewriting the php (again) there really isn't such a big rush to merge it. Anyone can take @angieradtke branch and submit pull requests there so that it is really great when it is merged here. (I know that's what I have been doing)

2020-02-19 11:17 UTC, angieradtke commented
this <div> grouped the elements inside, because  of  the flexbox -usage  
of the wrapping element .

Am 19.02.2020 um 12:11 schrieb Brian Teeman:
>
> *@brianteeman* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In layouts/joomla/searchtools/default/bar.php 
> <https://github.com/joomla/joomla-cms/pull/27918#discussion_r381226534>:
>
> >  $filters = $data['view']->filterForm->getGroup('filter');
>   ?>
>   
>   <?php if (!empty($filters['filter_search'])) : ?>
>   	<?php if ($searchButton) : ?>
> -		<div class="btn-group mr-2">
> +		<div>
>
> looks like this div is not required
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/joomla/joomla-cms/pull/27918?email_source=notifications&email_token=AAI6HM2EXSHUI5CD5VZSGTLRDUHVZA5CNFSM4KURTI42YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCWCNG5I#pullrequestreview-361026421>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAI6HM3YXBJRVURE4Z4R5YDRDUHVZANCNFSM4KURTI4Q>.
>

2020-02-19 11:20 UTC, infograf768 commented
RTL bug:
The `select-bg.svg` has been modified, but not the `select-bg-rtl.svg` one.

Therefore we get for LTR

<img width="1426" alt="Screen Shot 2020-02-19 at 12 15 35" src="https://user-images.githubusercontent.com/869724/74829671-d74e3e00-5311-11ea-8138-1b1283e98c8f.png">

and for RTL

<img width="1415" alt="Screen Shot 2020-02-19 at 12 15 04" src="https://user-images.githubusercontent.com/869724/74829730-f8169380-5311-11ea-8fd9-c5eb0f3592f3.png">

2020-02-19 11:35 UTC, infograf768 commented
Here is a corrected rtl file

[select-bg-rtl.svg.zip](https://github.com/joomla/joomla-cms/files/4224815/select-bg-rtl.svg.zip)

2020-02-19 11:40 UTC, infograf768 commented
we could add to the rtl.svg the code `preserveAspectRatio="xMinYMin meet"` which I forgot in the file above.

2020-02-19 11:42 UTC, angieradtke commented
@infograf768 @brianteeman now I did something wrong merged what I don't want merge????

2020-02-19 11:50 UTC, angieradtke commented on administrator/components/com_content/tmpl/article/edit.php
> +				<div class="">
I removed the class because I don't want the box-shadow there

2020-02-19 12:35 UTC, brianteeman commented on administrator/components/com_content/tmpl/article/edit.php
> +				<div class="">
then you should just have a plain `<div>` and not the empty `class=""`

2020-02-19 13:13 UTC, rdeutz commented
> As this template PR is 99% scss and not rewriting the php (again) there really isn't such a big rush to merge it. Anyone can take @angieradtke branch and submit pull requests there so that it is really great when it is merged here. (I know that's what I have been doing)

I want to allow to work in parallel and not let anyone work on this branch, smaller changes are better to discuss and I belive we would processing faster.

2020-02-19 13:20 UTC, brianteeman commented
All of that can be done on a different branch or on angie's fork

2020-02-20 17:20 UTC, Quy commented
Not aligned.

![filter](https://user-images.githubusercontent.com/368084/74960996-3075aa80-53c2-11ea-9fd3-ed0fb5eaa55c.jpg)

2020-02-20 17:45 UTC, brianteeman commented
its the padding on the selects being different when it is using choices.js

2020-02-23 12:08 UTC, angieradtke commented
Hi Guys,

I don't know what do do now, waiting  .....

2020-02-23 12:20 UTC, TobsBobs commented
Should we test this PR or will it merged direclty?

2020-02-23 12:22 UTC, richard67 commented
@angieradtke You mean you have finished works? If so, just remove the "[WIP]" from the title of this PR and post back here that it is ready for test, and then we test it.

Or is there still something to do and you wait for advise?

2020-02-23 12:23 UTC, richard67 commented
Ah and @rdeutz wanted to have a look why Drone tests are failing.

2020-02-23 12:34 UTC, rdeutz commented
We talked about this PR in a meeeting about the Beta blockers and we decided to pull some things out of this PR, fix testing and merge it then. Plan is to do this over the weekend.

2020-02-23 12:39 UTC, richard67 commented
@rdeutz This weekend or next weekend?

2020-02-23 12:50 UTC, rdeutz commented
this, so today or at least tomorrow

2020-02-23 13:03 UTC, HLeithner commented
> this, so today or at least tomorrow

Roberts weekend starts on Friday and ends on Monday ;-)

2020-02-23 13:53 UTC, richard67 requested changes
@rdeutz The changes of `fas` to `fa` class prefix for fontawesome should be reverted, see PR #27657 .

2020-02-23 13:53 UTC, richard67 commented on administrator/components/com_content/tmpl/articles/default.php
> +						<span class="fa fa-info-circle" aria-hidden="true"></span><span class="sr-only"><?php echo Text::_('INFO'); ?></span>
```suggestion
						<span class="fas fa-info-circle" aria-hidden="true"></span><span class="sr-only"><?php echo Text::_('INFO'); ?></span>
```

2020-02-23 13:53 UTC, richard67 commented on administrator/components/com_content/tmpl/articles/default.php
> +										<span class="fa fa-ellipsis-v" aria-hidden="true"></span>
```suggestion
										<span class="fas fa-ellipsis-v" aria-hidden="true"></span>
```

2020-02-23 14:11 UTC, richard67 approved these changes

2020-02-23 14:43 UTC, merged

2020-02-23 14:48 UTC, brianteeman commented
woohooo

2020-02-23 15:02 UTC, Hackwar commented
👍

2020-02-23 16:41 UTC, ciar4n commented
No tests required anymore?

2020-02-23 16:52 UTC, N6REJ commented
> @rdeutz The changes of `fas` to `fa` class prefix for fontawesome should be reverted, see PR #27657 .

oh gawd PLEASE don't undo what I've started

2020-02-23 18:24 UTC, HLeithner commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +          /*  background-color: var(--atum-bg-dark-80); */
Please remove code that is no longer used.

2020-02-23 18:25 UTC, HLeithner commented
> > @rdeutz The changes of `fas` to `fa` class prefix for fontawesome should be reverted, see PR #27657 .
> 
> oh gawd PLEASE don't undo what I've started

Could you point me to the change? didn't found it at a quick look

2020-02-23 18:26 UTC, astridx commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +          /*  background-color: var(--atum-bg-dark-80); */
Please see https://github.com/joomla/joomla-cms/pull/28035

2020-02-23 18:29 UTC, HLeithner commented on administrator/templates/atum/scss/blocks/_sidebar.scss
> +          /*  background-color: var(--atum-bg-dark-80); */
thanks

2020-02-23 18:30 UTC, richard67 commented
> > > @rdeutz The changes of `fas` to `fa` class prefix for fontawesome should be reverted, see PR #27657 .
> > 
> > 
> > oh gawd PLEASE don't undo what I've started
> 
> Could you point me to the change? didn't found it at a quick look

@HLeithner Is resolved since a while.

2020-02-23 18:31 UTC, HLeithner commented
Then I'm late to the party^^ thx richard

2020-02-23 22:04 UTC, C-Lodder commented
Why does the core backend template have template overrides? Surely the is the road towards a maintainers nightmare?

2020-02-23 22:10 UTC, brianteeman commented
it is - and it really shouldnt - the searchtools one has already been pulled

2020-02-24 09:04 UTC, brianteeman commented
@C-Lodder see #28052