fixed error of js errors in console
joomla/joomla-cms pull request #27938
Opened 2020-02-15 16:04 UTC by Subhang23

Pull Request for Issue #27606 .

### Summary of Changes

Since the the eventListener might be used later I have wrapped it in a try catch block

### Testing Instructions

### Expected result
There to be no error in the console

### Actual result

### Documentation Changes Required

2020-02-15 16:07 UTC, Subhang23 commented
@Quy is this what was intended?

2020-02-16 10:12 UTC, Fedik commented
sorry, the fix are wrong,
to make a correct fix you have to analyse what cause an error, first

2020-02-16 16:42 UTC, dgrammatiko requested changes

2020-02-16 16:42 UTC, dgrammatiko commented on build/media_source/layouts/js/joomla/html/batch/batch-language.es6.js
> -      batchSelector.addEventListener('change', onChange);
```js
if (batchCopyMove && batchSelector) {
```

2020-02-16 17:15 UTC, SharkyKZ commented
Fields have their own batch script https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/com_fields/js/admin-fields-default-batch.es6.js. We can either move relevant part of the code to `batch-language.js` and remove that script or start loading `batch-language.js` only where it's actually used.

2020-12-28 19:45 UTC, Quy commented
Please test PR #31791

2020-12-28 19:45 UTC, closed without merging