[4.0] Update UCM component table classes
joomla/joomla-cms pull request #27992
Opened 2020-02-20 08:47 UTC by SharkyKZ

### Summary of Changes

This updates entries in `#__content_types` table to include new fully qualified table class names.
Components that use core table classes that use `JTable` prefixed classes are currently not included but maybe the should be. Looking for feedback on this.

### Testing Instructions

This will need to be tested both for new installations and for upgrades from 3.10.
Create a contact, a newsfeed, a tag, a banner, a banner client and a user note.
Make some edits and save.
In the form, click `Versions` button and check whether the current version is marked with a star.

### Expected result

Marked.

### Actual result

Not marked.

### Documentation Changes Required

No.

2020-02-20 12:18 UTC, richard67 commented
@SharkyKZ In the **update sql script for postgresql** in the alter table statements you can't use `varchar`, you have to use `character varying` because our database checker is so silly. In create table statements in update sql it doesn't mater because for these it doesn't check particular columns. See `4.0.0-2018-07-29.sql` or `4.0.0-2019-05-20.sql` for examples on usage of `character varying`.

2020-02-20 12:50 UTC, richard67 requested changes

2020-02-20 12:50 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-02-20.sql
> +ALTER TABLE "#__content_types" ALTER COLUMN "table" TYPE varchar(2048);
```suggestion
ALTER TABLE "#__content_types" ALTER COLUMN "table" TYPE character varying(2048);
```
Has to be done like this because our database checker is so silly, see [https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Schema/ChangeItem/PostgresqlChangeItem.php#L146](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Schema/ChangeItem/PostgresqlChangeItem.php#L146).

2020-02-20 15:10 UTC, richard67 approved these changes

2020-02-23 16:59 UTC, astridx commented
I have tested this
1. git fetch origin pull/27992/head:j4/ucm/getContentTable
2. git checkout j4/ucm/getContentTable
3. I made a new installation 
4. npm or composer is not needed.
5. First I checked my mysql database. The changes are made.

[new.txt](https://github.com/joomla/joomla-cms/files/4241726/new.txt)
[old.txt](https://github.com/joomla/joomla-cms/files/4241727/old.txt)

**6. Then I created a Tag, edited the Tag. But I could not see a Star. I think it is because the Table is not named `TagsTable`. The class is named `TagTable` (without the `s`),**
7. I could see the star when I tried it with a Banner, a Contact and a Newsfeed.

2020-02-23 17:56 UTC, SharkyKZ commented
@astridx Should be fixed now.

2020-03-12 16:38 UTC, merged

2020-03-12 16:38 UTC, wilsonge commented
Thanks!

2020-03-12 16:38 UTC, wilsonge commented
> Components that use JTable prefixed core classes are currently not included but maybe they should be. Looking for feedback on this.

I think they probably should be

2020-03-12 20:06 UTC, SharkyKZ commented
Should we use the core classes or classes from components, e.g. `Joomla\CMS\Table\Content` or `Joomla\Component\Content\Administrator\Table\ArticleTable`. Asking this because I see both used throughout the CMS and not sure which one is the right way.

2020-03-13 10:18 UTC, wilsonge commented
If there’s a component specific one use it.

I think I want to end up with components managing these things long terms anyhow so we can use the bootComponent methods for access anyhow.