[4.0] Allow 3rd party components to easily create the dashboard menu module
joomla/joomla-cms pull request #28027
Opened 2020-02-23 13:10 UTC by Bakual

Pull Request for Issue #27765

When a 3rd party component wants to use the dashboard, they would have to manually create the submenu module and assign the preset and all the needed parameters.
This PR tries to make that simpler by providing a function in the InstallerScript which can be called.

### Summary of Changes
Adds the method `addDashboardMenu` to the InstallerScript

To use it, an extension can simply call `$this->addDashboardMenu('foo', 'bar');` in it's custom install script. The first argument is the dashboard name as declared in the component adminmenu structure (see https://github.com/joomla/joomla-cms/pull/27849), the second argument is the name of the preset the submenu module should load.

### Testing Instructions
Eitehr adjust a 3rd party component to use a dashboard, or use my component where I added those calls for testing.
[com_sermonspeaker.zip](https://github.com/joomla/joomla-cms/files/4241262/com_sermonspeaker.zip)

Click on the dashboard icon next to the component name (or wherever you added the dashboard menuitem). In my component it is here:
![image](https://user-images.githubusercontent.com/1018684/75112621-d08f3600-5645-11ea-8b63-7f760b457e91.png)

Note: If you install my component more than once, you will get multiple menu modules. This is not a bug in this PR but one in my component script.

### Expected result
The dashboard has the dashboard menu with the correct preset loaded.

### Actual result
The dashboard is empty

### Documentation Changes Required
Dashboard related stuff needs to be documented in general.

2020-02-23 13:15 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on c8f1e4862591558e3e1436f4c349b444a65ff49c<br /><br />great stuff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28027">issues.joomla.org/tracker/joomla-cms/28027</a>.</sub>

2020-02-23 15:36 UTC, mbabker commented
There isn't a way to do this without introducing an architectural coupling between the installer library API and com_modules?  The libraries API packages really should not have dependencies to components.

2020-02-23 20:08 UTC, Bakual commented
> There isn't a way to do this without introducing an architectural coupling between the installer library API and com_modules?

I thought quite a bit for a more elegant solution and didn't get further than that.
I think the InstallerScript is a special case anyway. I see it more as a collection of methods to help extension developers. So they don't have to invent the wheel themself.

2020-02-29 23:38 UTC, wilsonge requested changes

2020-02-29 23:38 UTC, wilsonge commented on libraries/src/Installer/InstallerScript.php
> +		$model  = new ModuleModel;
```suggestion
		$model = JFactory::getApplication()->bootComponent('com_modules')->getMVCFactory()->createModel('Module', 'Administrator', ['ignore_request' => true]);
```

2020-02-29 23:38 UTC, wilsonge commented on libraries/src/Installer/InstallerScript.php
> +use Joomla\Component\Modules\Administrator\Model\ModuleModel;
```suggestion

```

2020-02-29 23:38 UTC, wilsonge commented on libraries/src/Installer/InstallerScript.php
> +			Factory::getApplication()->enqueueMessage($model->getError());
Rather than a raw error let's display something more user friendly here - add a string "Failed to create extension dashboard %s" and we can just log the error

2020-02-29 23:38 UTC, wilsonge commented
> I think the InstallerScript is a special case anyway. I see it more as a collection of methods to help extension developers

That's pretty much how I see it too. I'd agree with Michael as a more general case though

2020-03-01 17:41 UTC, astridx commented
I tested this PR with and without George's suggestions. It was successful both times.

@Bakual If you like I submitted my changes as a PR.

![Control Panel   test   Administration(1)](https://user-images.githubusercontent.com/9974686/75630574-32bedc80-5bec-11ea-89cd-bb2415c1e92b.png)

2020-03-01 17:42 UTC, astridx commented
I have tested this item :white_check_mark: successfully on c8f1e4862591558e3e1436f4c349b444a65ff49c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28027">issues.joomla.org/tracker/joomla-cms/28027</a>.</sub>

2020-03-01 18:32 UTC, Bakual commented on libraries/src/Installer/InstallerScript.php
> +		$model  = new ModuleModel;
Looks ugly as hell but removes the dependency, so I guess it's preferred 😄

2020-03-01 18:51 UTC, Bakual commented on libraries/src/Installer/InstallerScript.php
> +			Factory::getApplication()->enqueueMessage($model->getError());
Done

2020-03-01 22:56 UTC, astridx commented
I have tested this item :white_check_mark: successfully on 41230aafa425f4a55a9d7290de7e9f4402b9009f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28027">issues.joomla.org/tracker/joomla-cms/28027</a>.</sub>

2020-03-02 08:58 UTC, merged