WebAuthn Passwordless Authentication – Reloaded
joomla/joomla-cms pull request #28094
Opened 2020-02-26 14:20 UTC by nikosdion

Pull Request for **new feature**: **passwordless authentication with W3C Web Authentication (WebAuthn)**

This PR replaces the ill-fated PR gh-25797 and comes with the following changes:

1. **The EcmaScript 6 files (SHOULD!) now pass code style validation**. On top of that, we have verbally agreed with @wilsonge and @HLeithner to merge even if the ES6 needs a bit of love and refactoring since this can be fixed even post-beta without adverse effects to backwards compatibility.
1. **Updated backend**. I have update the WebAuthn library to version 2.1. We'll stick with this version because the third-party library introduces b/c breaks in minor versions :(

## Summary of Changes

This PR adds support for WebAuthn (W3C Web Authentication). This is a W3C standard made official in March 2019.

WebAuthn allows users to authenticate (log in) securely into a site without using a password. Instead it uses authenticators. An authenticator is either a discrete hardware device or a Trusted Platform Module (TPM) / Secure Enclave built into your device. Moreover, it only works under HTTPS. By using secure hardware and secure transport it makes sure that the authentication is resistant to eavesdropping, phishing, brute-force and other attack modes associated with fixed passwords.

Before continuing please take a minute to [learn more about WebAuthn and play with it](https://webauthn.io/).

## Notes about preparing and installing Joomla 4

The following is a collection of errata for the Joomla 4 build process which have nothing to do with this PR but may get in your way while testing. I wasted time so here's my distilled experience so you don't have to suffer :)

After merging this PR to your local 4.0-dev branch (or cloning the repo it pulls from) you need to run `composer install` and `npm install`. If you fail to do that there will be missing PHP dependencies and JS files and the whole thing will fail.

If `npm install` fails you need to delete the folders `node_modules` and `administrator/components/com_media/node_modules`. Then you can run `npm install` again.

Joomla will fail to load after installing when you run `composer install`. You'll get some cryptic error about Atum missing assets and / or missing classes. That's not a bug in this PR, it's a "feature" of Joomla 4's build process. You need to delete the `libraries/autoload_psr4.php` file. Your site will magically work.

FWIW, these issues are currently being fixed by someone else.

If you are applying this PR on an existing Joomla 4 development site please remember to not only do the steps above but _also_ go to System, Fix Database. Then check that the System - Web Authentication plugin is enabled.

## Testing Instructions

**i. Requirements**

**Your site must be using HTTPS** with a certificate your browser recognizes as valid. For simplicity's sake, please use a live server with a valid SSL certificate, e.g. one issued by Let's Encrypt.

**An authenticator**. A FIDO or FIDO 2 compatible hardware key is the best. You may also use a software FIDO key such as [Krypton](https://krypt.co/). I have tested this PR with a YubiKey Neo (FIDO over USB and NFC), a Security Key NFC by Yubico (FIDO 2 over USB and NFC) and Krypton (FIDO over Bluetooth / browser extension).

**WebAuthn compatible browser**. Not all browser versions are compatible with WebAuthn. If unsure, check if you can use the WebAuthn.io site with it BEFORE trying to test this PR. At the time of this writing no browser on iOS will work with WebAuthn, Safari is mostly broken and Chromium-based browsers (except Chrome itself) do not work with Touch ID on macOS. Your best bet is Google Chrome and Firefox on desktop operating systems or Android.

**ii. Enabling the plugin**

Go to Plugins and enable the “System - WebAuthn Passwordless Login” plugin.

**iii. Perform basic tests**

Please conduct the following tests in the following order. If something doesn't work please first read the FAQs below.

If your solution is not there first check if the same combination of operating system, browser and authentication work with the webauthn.io site. If not, the problem is between your OS, browser and authenticator. It is not a bug in the plugin and cannot be magically fixed.

If you could not find an answer in the FAQs and your authenticator worked with webauthn.io please provide the following information:

* URL to your site, including the scheme. Example: https://www.example.com
* Database type and version. Example: MySQL 5.7.26
* Your username. Example: foo_Bar
* Operating system and version. Examples: macOS 10.14.5, iOS 12.1, Ubuntu Linux 18.04.01
* Browser make and exact version. Example: Safari 12.1.1 (14607.2.6.1.1)
* Authenticator used. Example: YubiKey 4
* Authenticator connection method. Examples: USB-A, USB-C, USB-A with Lightning-to-USB adapter, Bluetooth, software
* Does the same combination of operating system, browser and authentication work with the webauthn.io site? If not please do not file a failed test report; the problem is somewhere between your OS, browser and authenticator, not Joomla itself.

### Test 1: Login Buttons

Log out from your site's frontend and backend.

Go to your site's frontend home page and look at the login module. You should see a “Web Authentication” button under the Remember Me checkbox.

Go to your site's frontend user page (`/index.php/component/users/login`). You should see a “Web Authentication” button under the Remember Me checkbox.

Go to your site's backend page (`/administrator/index.php`). You should see a “Web Authentication” button under the Remember Me checkbox.

### Test 2: WebAuthn can't be used if you haven't registered an authenticator

Log out from your site's frontend and backend.

Go to your site's frontend home page and locate the login module.

Type your username but NOT your password.

Click on the “Web Authentication” button.

**Expected**: an error message that the username does not exist or is not linked to WebAuthn.

### Test 3: Register an authenticator from the backend

Log in to your site's backend using your username and password.

Go to Users, Manage and click on your username.

Click on the “W3C Web Authentication (WebAuthn) Login” tab.

Click on the big, green “+ Add New Authenticator” button and interact with your authenticator. Please note that the prompt to interact with your authenticator is specific to and rendered by your browser.

**Expected**: You see a new authenticator appearing on the list above the green button. There is no need to click on “Save & Close”; the authenticator assignment is (and has to be, for seriosu security reasons) saved during the previous interaction.

### Test 4: Rename an authenticator

Log in to your site's backend using your username and password.

Go to Users, Manage and click on your username.

Click on the “W3C Web Authentication (WebAuthn) Login” tab.

Find the authenticator you created before and click the “Edit Name” button next to it.

**Expected**: The name becomes and editable text field with a Save and Cancel button next to it.

Click on “Cancel” next to the text field.

**Expected**: the old name remains.

Click the “Edit Name” button again. This time enter a new name and click on “Save” next to the text field.

**Expected**: the new name sticks.

### Test 5: Delete and authenticator

Log in to your site's backend using your username and password.

Go to Users, Manage and click on your username.

Click on the “W3C Web Authentication (WebAuthn) Login” tab.

Find the authenticator you created before and click the “Remove” button next to it.

**Expected**: the authenticator is gone.

Also repeat test 2 and make sure you still get the expected message.

### Test 6: Repeat tests 3, 4 and 5 for the frontend

Log in to your site's frontend using your username and password.

Go to the user profile editor page (`/index.php?option=com_users&view=profile`). Please note that if you try using Joomla's sample data menu items such as Your Profile i [...]

2020-02-26 14:52 UTC, zero-24 commented
This looks awesome thanks for your work on this @nikosdion I really love to see this as a feature for 4.0 👍 

I have just added it to my list, to test this in full in the coming days.

Just one organisational question how do you want us to contribute and fix things we found? Maybe as PR against this branch or do you like to merge after the functional tests and adjust that kind of things after merge with individual PRs? cc @HLeithner @wilsonge ?

2020-02-26 14:57 UTC, nikosdion commented
@zero-24 Thank you! You can make PRs against my repo.

The biggest concern right now is that the violations reported by Hound are NOT reported by ESlint (e.g. `npm run js:lint`) on the repo. If I "fix" what Hound reports ESlint complains and vice versa. It'd be comical if it wasn't an automatic merge blocker.

Either ESlint is configured wrong on the repo or Hound is configured wrong. I can't tell which is the case. Any help most welcome.

2020-02-26 15:00 UTC, C-Lodder commented
@nikosdion Thanks so much for this! I look forward to testing soon.

The only thing that stood out was the use of PHP short tags.

2020-02-26 15:01 UTC, brianteeman commented on .gitignore
> +!/build/media_source/plg_system_webauthn/js/*.es6.js
am I missing something for the reason to have this in the gitignore

2020-02-26 15:02 UTC, richard67 commented
> If you are applying this PR on an existing Joomla 4 development site please remember to not only do the steps above but also go to System, Fix Database. Then check that the System - Web Authentication plugin is enabled.

This is not enough because the database fixer only runs DDl (data definition language), i.e. the "create table" statement, but it doesn't run DML (data manipulation language), i.e. the "insert into #__extensions" statements are not run. So the plucin will not be installed.

It requires either to have an own installation.sql script for the plugin, like we have them for other extensions, so the plugin can be installed with the "Discover" functionality, or it needs to run the "insert" statements from the schema update sql "manually" e.g. in PhpMyAdmin.

2020-02-26 15:03 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_MSG_SAVED_LABEL="The label has been saved successfully."
can you remove the word "successfully" please. Here and on the next line. You can only save successfully so we have removed all redundant words.

2020-02-26 15:05 UTC, nikosdion commented
@C-Lodder I understand your confusion but they are not, in fact, short PHP tags. Since PHP 5.4 the short **echo** tags are always enabled, regardless of PHP's short tags toggle. Rasmus Lerdorf said that PHP developers _should_ actually use them to make the code easier to read. Since we're targeting at least 7.2 I think it's safe to say that we can use them.

2020-02-26 15:05 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_ERR_NO_BROWSER_SUPPORT="Sorry, your browser does not support the W3C Web Authentication standard for passwordless logins or you are not using HTTPS with a valid, signed certificat
"you are not using HTTPS "

Shouldn't this be "the site is not using HTTPS" as we have switched from talking about the user's web browser to the site's certificate

2020-02-26 15:05 UTC, C-Lodder commented
I'll look into the JS linter this evening after work.

2020-02-26 15:06 UTC, nikosdion commented
@richard67 You are right. I suppose that Discover would, however, let you install the missing plugin. Right?

2020-02-26 15:06 UTC, nikosdion commented on administrator/language/en-GB/en-GB.plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_ERR_NO_BROWSER_SUPPORT="Sorry, your browser does not support the W3C Web Authentication standard for passwordless logins or you are not using HTTPS with a valid, signed certificat
Fair enough. Let me make a quick change.

2020-02-26 15:07 UTC, brianteeman commented on build/media_source/plg_system_webauthn/js/login.es6.js
> + * Find a form field described the CSS selector fieldSelector. The field must be inside a <form>
```suggestion
 * Find a form field described by the CSS selector fieldSelector. The field must be inside a <form>
```

2020-02-26 15:10 UTC, nikosdion commented on administrator/language/en-GB/en-GB.plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_MSG_SAVED_LABEL="The label has been saved successfully."
Right. It's not like back in the days of Windows XP with the infamous "The task failed successfully" messages. Fixed.

2020-02-26 15:10 UTC, brianteeman commented on layouts/plugins/system/webauthn/manage.php
> + * Note about the use of short echo tags.
surely this is a codestyle issue?

2020-02-26 15:12 UTC, brianteeman commented on layouts/plugins/system/webauthn/manage.php
> +                        <span class="icon-edit icon-white"></span>
Please update for accessibility all icons following this example

```suggestion
                        <span class="icon-edit icon-white" aria-hidden="true"></span>
```

2020-02-26 15:12 UTC, nikosdion commented on layouts/plugins/system/webauthn/manage.php
> + * Note about the use of short echo tags.
No, it's not. It was an attempt to preempt commits like @C-Lodder's above. It's always valid (and recommended!) syntax since PHP 5.4 but most developers, including core Joomla developers, are oblivious to it. I educate through comments.

2020-02-26 15:13 UTC, richard67 commented
> I suppose that Discover would, however, let you install the missing plugin. Right?

@nikosdion Not sure, it needs to try. Am not at my desk here so can't try. But this is relevant only for testing, and people could run also the sql manually for testing. When updating, the installer runs the complete update sql, so the inserts would take place.

2020-02-26 15:14 UTC, brianteeman commented on libraries/src/Plugin/CMSPlugin.php
> +use Joomla\CMS\Language\Text;
This change is not required

2020-02-26 15:14 UTC, nikosdion commented on .gitignore
> +!/build/media_source/plg_system_webauthn/js/*.es6.js
That's a leftover from the previous PR from 6 months ago (I started this PR by merging 4.0-dev to the old branch). The .gitignore used to include the entire `build` folder which meant I couldn't commit my files unless I added that line. I am removing it now since it is no longer necessary. Thanks for pointing it out.

2020-02-26 15:16 UTC, nikosdion commented on layouts/plugins/system/webauthn/manage.php
> +                        <span class="icon-edit icon-white"></span>
Thank you, I am applying this to all icons now.

2020-02-26 15:17 UTC, brianteeman commented on layouts/plugins/system/webauthn/manage.php
> + * Note about the use of short echo tags.
I understand what you wrote perfectly.  Personally I find that a consistent codestyle is more beneficial

2020-02-26 15:17 UTC, nikosdion commented on libraries/src/Plugin/CMSPlugin.php
> +use Joomla\CMS\Language\Text;
No, it's not. That looks like a leftover from a merge before I started the first PR.

2020-02-26 15:24 UTC, nikosdion commented on layouts/plugins/system/webauthn/manage.php
> + * Note about the use of short echo tags.
Here's the thing, Brian. I'm most definitely not violating the Joomla coding style, neither the documented one nor its machine-readable expression as enforced by PHP-CS. If you want to change the code style talk to the production department or whatever it's called these days. What I do here is 100% within the rules I am told I need to follow for my PR to be accepted.

2020-02-26 15:25 UTC, nikosdion commented
@richard67 I updated the PR text to include the note about Discover as well.

2020-02-26 15:27 UTC, nikosdion commented
@C-Lodder Thank you! Let me know if the linter in the repo needed an update so I can go back to phpStorm and fix the ES6 files (again).

2020-02-26 15:38 UTC, richard67 commented
@rdeutz Can it be that there is missing some PHP extension in our ci test docker images for this PR? At least the "composer" step of the drone log reads like this, see [https://ci.joomla.org/joomla/joomla-cms/29618/1/8](https://ci.joomla.org/joomla/joomla-cms/29618/1/8) .

2020-02-26 15:39 UTC, nikosdion commented
@rdeutz @richard67  It looks like Drone is failing because the WebAuthn library requires spomky-labs/cbor-php which requires **the gmp PHP extension**. Since our Composer task uses the joomlaprojects/docker-images:php7.3-composer image to which I do not have edit / build privileges I cannot fix it. Any chance of updating this Docker image?

2020-02-26 15:41 UTC, richard67 commented
@nikosdion I don't have these privileges either, and if I had them I would still not have the necessary knowledge ... let's hope for Robert to help.

2020-02-26 16:24 UTC, nikosdion commented on layouts/plugins/system/webauthn/manage.php
> + * Note about the use of short echo tags.
Apparently PHP-CS will shout at you even if you use a standard `<?php if ($condition): ?>` in a view template. Here's the code with a code formatting that makes no sense to humans but keeps machines happy. I give up.

2020-02-26 16:33 UTC, nikosdion commented
@richard67 I have the knowledge, but I don't have the power to fix what needs fixing. Dang.

@rdeutz I created an issue with a proposed patch to address the Drone issue, see https://github.com/joomla-projects/docker-images/issues/15

2020-02-26 19:08 UTC, bembelimen commented
Thank you @nikosdion for your work! Really appreciate, that you built this functionallity.

2020-02-26 19:27 UTC, rdeutz commented
@nikosdion I fixed the docker image issue for drone and appveyor. For appveyor you have to include my PR #28099 or wait till it is merged and update to dev

2020-02-26 19:41 UTC, brianteeman commented
I cloned your branch
cloned your branch
sql updated
composer install
npm i
del autoload

`Fatal error: Class Joomla\CMS\Application\SiteApplication contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Joomla\CMS\Application\CMSApplicationInterface::getSession) in C:\htdocs\joomla-cms\libraries\src\Application\SiteApplication.php on line 34
`

What did I miss

2020-02-26 19:58 UTC, mbabker commented
> What did I miss

Looks like a full `composer update` was done, which as pointed out in https://github.com/joomla/joomla-cms/pull/27996 and https://github.com/joomla/joomla-cms/issues/27997 is a bit problematic right now.

The quickest solution I can think of here is to reset `composer.lock` so it matches the current 4.0 branch state, `composer install` to get the local environment back to the right state, then run `composer update web-auth/webauthn-lib ramsey/uuid` which should only update those two packages without touching the rest of the dependency tree.

2020-02-26 20:00 UTC, brianteeman commented
that would explain it

2020-02-26 20:02 UTC, richard67 commented
The brute force solution to clean up a 4.0-dev branch (requires a remote named "upstream" pointing to the cms repo):

```
git checkout 4.0-dev
git remote update
git clean -d -x -f
git reset --hard upstream/4.0-dev
git push origin +4.0-dev
```

This will make your 4.0-dev branch (locally and in your repo) be exactly same as 4.0-dev branch of the CMS repo.

After that, `composer install` and `npm ci` and all should be fine.

2020-02-26 20:04 UTC, C-Lodder commented
@nikosdion I've had a look into the eslint stuff. I've managed to get Hound and local linting to match, however the rules seem to have differed. Hound uses `eslint 4.19.1` by default, so I've bumped all eslint deps to their respective latest version

Now, I'm only getting two of the following

```
error  Expected parentheses around arrow function argument       arrow-parens
```

I've tried moving from Hound to Github Actions and still getting the same thing.

2020-02-26 20:50 UTC, C-Lodder commented
Anyway, I've raised an issue: https://github.com/joomla/joomla-cms/issues/28100

2020-02-26 21:03 UTC, richard67 commented
@nikosdion The hound is happy now, but we have PHP a few small code style errors reported by drone. Shall I fix them for you so you can focus on the real stuff?

2020-02-26 21:09 UTC, nikosdion commented
@wilsonge @mbabker I would say that the current situation means that Joomla is using Composer the wrong way. If a library should be bound to a specific version it should be in composer.json, not some arcane, undocumented knowledge. Otherwise why the fsck do we use Composer instead of copying files around like cavemen? :)

IMHO it would be far better to tag a 2.0.0.a1 release in the Joomla Framework repos from the commits that Joomla CMS' 4.0-dev branch is using and update composer.json.

The current situation is unworkable since we can't update dev dependencies which means that anyone using PHP 7.4, i.e. me, can't safely run the dev tools such as PHP-CS which is a damn shame. I'll have to do weird things to get phpStorm showing me code-style issues again. Not how I envisioned spending my night at 11 pm.

@richard67 The solution to hard reset to 4.0-dev is not viable because it would undo the PR as far as I can tell. Instead, I switched composer.lock back to 4.0-dev and used `composer require web-auth/webauthn-lib "2.1.*"` to install my dependencies. Apparently we no longer need to require ramsey/uuid because the library finally does that automatically.

Regarding PHP-CS issues, sure, I'll fix them as soon as I can see them in phpStorm :D

@C-Lodder I understood the part about the versions being different. The points made in your issue is above my pay grade. I can work miracles on PHP but when it comes to JS and its automation I'm still a little more than a caveman.

@brianteeman Everything should be in working order now. Pull the changes, delete the libraries/vendor folder, do composer install and npm install, delete libraries/autoload_psr4.php and you should be ready. Hopefully. At least that's how it worked for me.

2020-02-26 21:33 UTC, nikosdion commented
@richard67 I gave in and selectively update the Joomla code style standard in the repo as there was no other way to stop it breaking PHP-CS with PHP 7.4. I also used a globally installed, up to date copy of PHP-CS which is compatible with PHP 7.4. Good news is that worked. I was able to update the three small code style issues: a missing line, a missing docblock and PHP-CS getting a stroke when there's an inline array in a function call.

@HLeithner @wilsonge @C-Lodder I will ignore the Hound's recommendations. ESlint on the repo says it's all good, I'm gonna go with that _since it's an up-to-date version, whereas Hound's is not_.

Let the functional, manual testing begin.

2020-02-26 21:50 UTC, richard67 commented
@nikosdion Well I would not care about PHPCS but it somes so early in the drone test sequence and when it fails, all the other more interesting tests are not run, that's why I asked for fixing. So or so thanks a lot for your work here, and I hope to find time on weekend for testing ... have to get som key first ;-)

2020-02-26 22:37 UTC, mbabker commented
> I would say that the current situation means that Joomla is using Composer the wrong way. If a library should be bound to a specific version it should be in composer.json, not some arcane, undocumented knowledge. Otherwise why the fsck do we use Composer instead of copying files around like cavemen? :)
> 
> IMHO it would be far better to tag a 2.0.0.a1 release in the Joomla Framework repos from the commits that Joomla CMS' 4.0-dev branch is using and update composer.json.

I haven't touched things in a long time, but it's not so much that the CMS repo relies on some random commit from the various Framework repos, it's more that `composer update` hasn't been regularly run on most packages and there are a couple of changes from the Application package (well, most specifically https://github.com/joomla-framework/application/pull/88 and moving the `$input` property from the root application class down to the web application class since the console application doesn't use that at all) that effectively block running a full update on all packages here until that change is dealt with in the context of the CMS.  So it might make sense to pin those 4 packages to the specific commit they're at now so updates can be run in a more safe manner, but things are not totally FUBAR'd in the Composer stack right now (I hope).

2020-02-26 22:52 UTC, HLeithner commented
> nikosdion Well I would not care about PHPCS but it somes so early in the drone test sequence and when it fails, all the other more interesting tests are not run, that's why I asked for fixing. So or so thanks a lot for your work here, and I hope to find time on weekend for testing ... have to get some key first ;-)

@richard67 phpcs is already happy, it's hound complaining about js and scss and if I see it correctly @C-Lodder already is trying to solve this.

2020-02-27 13:25 UTC, wilsonge commented
Updated hound Eslint version to match that in our package lock file. Nice catch there

2020-02-27 13:36 UTC, C-Lodder commented
@wilsonge Still doesn't match the local linter version

2020-02-27 14:18 UTC, wilsonge commented
> @wilsonge Still doesn't match the local linter version

Can you be more specific by "local linter version"?

2020-02-27 14:27 UTC, C-Lodder commented
https://github.com/joomla/joomla-cms/blob/4.0-dev/package.json#L81

https://github.com/joomla/joomla-cms/blob/4.0-dev/.hound.yml#L11

2020-02-27 14:27 UTC, C-Lodder commented
https://github.com/joomla/joomla-cms/blob/4.0-dev/package.json#L81

https://github.com/joomla/joomla-cms/blob/4.0-dev/.hound.yml#L11

2020-02-27 15:28 UTC, wilsonge commented
The package.json is kinda irrelevant for this. What counts is what's in the package-lock.json at the given time. That's what needs to be kept in sync with hound - we can't run hound against a loose version constraint. Currently it's https://github.com/joomla/joomla-cms/blob/4.0-dev/package-lock.json#L4970 which matches what i wrote in the hound file. This is also why we tell people to use `npm ci` ;)

2020-02-27 18:11 UTC, brianteeman commented
> This is also why we tell people to use npm ci ;)

Where? The readme just says "npm install" which is "npm i" not "npm ci"

2020-02-27 19:10 UTC, wilsonge commented
the docs https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment#Steps_to_Setup_the_Local_Environment - missed the readme didn't match - will fix that now

2020-02-27 19:14 UTC, brianteeman commented
the readme is the only place most people would see

2020-02-27 22:21 UTC, HLeithner commented
I have tested this item :white_check_mark: successfully on d081d0b306fb5174fd6cee782d0654192faf5ad0<br /><br />I tested all given tests on an updated j4 installation in windows 10 with Firefox and vivaldi authendicating with a Yubico YubiKey 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28094">issues.joomla.org/tracker/joomla-cms/28094</a>.</sub>

2020-02-27 22:37 UTC, brianteeman commented
While testing on a non-https site and clicking on Add new Authenticator for an existing SuperUser
![image](https://user-images.githubusercontent.com/1296369/75493295-7b3e8600-59b1-11ea-8ef5-04e57a6ccb59.png)

I get the following error
![image](https://user-images.githubusercontent.com/1296369/75493335-8db8bf80-59b1-11ea-8505-3092fea7e8e4.png)

Googling on the message took me to https://github.com/pypa/warehouse/issues/6343
Reading the comments and subsequent PR to address this it would appear to be the same issue

2020-02-27 22:42 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_MANAGE_FIELD_KEYLABEL_LABEL="Authenticator name"
```suggestion
PLG_SYSTEM_WEBAUTHN_MANAGE_FIELD_KEYLABEL_LABEL="Authenticator Name"
```

See [style guide](https://developer.joomla.org/en-gb-user-interface-text-guidelines/capitalisation.html)

2020-02-27 22:42 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_MANAGE_BTN_EDIT_LABEL="Edit name"
```suggestion
PLG_SYSTEM_WEBAUTHN_MANAGE_BTN_EDIT_LABEL="Edit Name"
```

See [style guide](https://developer.joomla.org/en-gb-user-interface-text-guidelines/capitalisation.html)

2020-02-27 22:42 UTC, brianteeman commented on administrator/language/en-GB/en-GB.plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_MANAGE_BTN_ADD_LABEL="Add new authenticator"
```suggestion
PLG_SYSTEM_WEBAUTHN_MANAGE_BTN_ADD_LABEL="Add New Authenticator"
```

See [style guide](https://developer.joomla.org/en-gb-user-interface-text-guidelines/capitalisation.html)

2020-02-28 06:05 UTC, nikosdion commented
@brianteeman 

You said:

> While testing on a non-https site and clicking on Add new Authenticator

But I have explicitly stated:

> Testing Instructions
>
> i. Requirements
> 
> **Your site must be using HTTPS with a certificate your browser recognizes as valid**. For simplicity's sake, please use a live server with a valid SSL certificate, e.g. one issued by Let's Encrypt.

Even if I pass an HTTPS URL for the icon it will **still** fail to work because browsers disable WebAuthn for insecure sites. In this context "insecure" means any site which is not being accessed over HTTPS or whose TLS certificate is not trusted by the browser.

I'll have to run a few checks. When Joomla reports the protocol as HTTP I should be hiding the WebAuthn login buttons and the tab from the user profile editor. If I am not I have either forgotten to implement what I documented or I screwed up. I'll get back to you on that.

2020-02-28 06:46 UTC, brianteeman commented
Yes I realised you said https but there was no check for https and the software loaded and then i got the unfriendly message. This was a stupid user test

2020-02-28 08:33 UTC, HLeithner commented
@nikosdion could you merge latest 4.0 branch, after this we should have successful tests.

I think the plugin should only run if https site is loaded and add a warning like on smart search and the content plugin.

![image](https://user-images.githubusercontent.com/1497730/75523937-4102d200-5a0d-11ea-86a3-5da12c9d957c.png)

Or we only allow to activate this plugin if the site is "https only" in our options (basically the same as the browser does)

2020-02-28 08:44 UTC, nikosdion commented
@brianteeman I most definitely don't disagree with you. There were two parts in my previous reply.

First part: No, the issue you experienced is not the same as the PyPI issue you referenced. Their problem was that they were creating HTTP avatar URLs on an HTTPS site when setting up WebAuthn. The issue **you** experienced is that you were allowed to access the WebAuthn set up page on HTTP at all.

Second part: You shouldn't be allowed to access that tab because I know it can't possibly work. I also know that my _intention_ when writing the plugin was to automatically prevent its buttons and tab from showing at all if the site is not HTTPS (see note below). So I told you I needed to run further checks. The idea is that either I forgot to do something or your server environment is reporting the wrong URL to Joomla.

Now that I've run the further checks I can tell you that I forgot to disable the tab on HTTP sites. I only prevent the login buttons from showing. I fixed that. Thank you for the bug report!

Note: You might wonder, why only hide the buttons and tabs on HTTP sites when I said that they won't work when the **browser** doesn't trust your TLS certificate? The answer is that I cannot tell from the server side if your _browser_ trusts your TLS certificate or not. A naive soul might think that we can get the server TLS certificate and check its validity server-side. That would be slow, precarious (loopback connections are disallowed on many shared hosts) and ultimately wrong. "Wrong? Why?" I hear some of you asking. Well, we don't have the _browser's_ CA trust database on server-side, we only have cacert.pem which includes the default CA trust db of Mozilla. In _enterprise_ deployments it's not unheard of having an organization-wide root CA which signs certificates used by internal sites. These are client-side and most assuredly not in our cacert.pem. So, lest we ask Joomla enterprise users to hack core as standard practice, we can't plausibly check the validity of TLS certificates server-side. The client-side failure mode in this case is far less confusing than what Brian experienced. The user will be told that their browser doesn't support WebAuthn or that their site is not using a valid, signed TLS certificate. So as far as I'm concerned, only checking for availability of HTTPS is a pragmatic approach. Sorry for the egregiously long paragraph; I really needed to document a development decision that would have otherwise been lost in Joomla arcana like so many other things.

2020-02-28 08:45 UTC, brianteeman commented
thanks 

PS why had I never heard of krypton before - it is awesome!!!!

2020-02-28 08:48 UTC, nikosdion commented
@HLeithner I am going to merge 4.0-dev, don't worry. I was working on that.

Regarding the plugin, it is now changed to not load (most of) its features when the site is not running under HTTPS. The plugin still needs to load because `onUserAfterDelete` still needs to delete the now unnecessary credentials of a user we just removed. 

Regarding showing a warning, I think we shouldn't do that. It is not very good UX since the fix is not "click here to fix it" but "do something outside of Joomla and then go back and do something to Joomla and then come back here". This sounds more like a side quest given to you by an elf in an RPG game than a pragmatic solution for people who don't already know what HTTPS is ;)

2020-02-28 08:50 UTC, nikosdion commented
@brianteeman Krypton is really cool but keep in mind that I would only use it for medium trust sites. It's a software implementation of FIDO over Bluetooth. Between CPU and Bluetooth security issues discovered over the last two years I don't consider this kind of implementation very secure. 

That said, considering the main target audience of Joomla, yes, it's secure enough for their use case. It's something you can plausibly install on your clients' mobile devices and teach them how to securely log into their sites without having to carry around yet another piece of expensive hardware they might lose. That's why I mentioned it in the PR ;)

2020-02-28 08:51 UTC, HLeithner commented
I like side quests ;-) but yes maybe not ideal. Anyway we should at least mention it on the plugin config site. 

Because now I have no chance to know why it's not showing.

2020-02-28 09:10 UTC, Quy commented
Please remove prefix `en-GB.` from language file names.

2020-02-28 09:39 UTC, nikosdion commented
@HLeithner I merged 4.0-dev and updated the plugin description per your request.

@Quy I renamed the language files. You might want to check the XML files of all other core extensions; they still reference the old-style filenames which might be confusing for developers without prior Joomla experience.

2020-02-28 10:17 UTC, brianteeman commented
@nikosdion @quy there is an outstanding PR for that waiting to be merged

2020-02-28 11:20 UTC, HLeithner commented
@nikosdion latest 4.0-dev should fix appveyor too

2020-02-28 11:28 UTC, alikon commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-07-02.sql
> +(0, 'plg_system_webauthn', 'plugin', 'webauthn', 'system', 0, 1, 1, 0, '', '{}', 0, '0000-00-00 00:00:00', 0, 0);
```suggestion
(0, 'plg_system_webauthn', 'plugin', 'webauthn', 'system', 0, 1, 1, 0, '', '{}', 0, NULL, 0, 0);
```

2020-02-28 11:28 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-02.sql
> +(0, 'plg_system_webauthn', 'plugin', 'webauthn', 'system', 0, 1, 1, 0, '', '{}', 0, '1970-01-01 00:00:00', 8, 0);
```suggestion
(0, 'plg_system_webauthn', 'plugin', 'webauthn', 'system', 0, 1, 1, 0, '', '{}', 0, NULL, 8, 0);
```

2020-02-28 11:28 UTC, alikon commented on installation/sql/mysql/joomla.sql
> +(0, 'plg_system_webauthn', 'plugin', 'webauthn', 'system', 0, 1, 1, 0, '', '{}', 0, '0000-00-00 00:00:00', 0, 0);
```suggestion
(0, 'plg_system_webauthn', 'plugin', 'webauthn', 'system', 0, 1, 1, 0, '', '{}', 0, NULL, 0, 0);
```

2020-02-28 11:29 UTC, alikon commented on installation/sql/postgresql/joomla.sql
> +(0, 'plg_system_webauthn', 'plugin', 'webauthn', 'system', 0, 1, 1, 0, '', '{}', 0, '1970-01-01 00:00:00', 8, 0);
```suggestion
(0, 'plg_system_webauthn', 'plugin', 'webauthn', 'system', 0, 1, 1, 0, '', '{}', 0, NULL, 8, 0);
```

2020-03-01 12:56 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on d081d0b306fb5174fd6cee782d0654192faf5ad0<br /><br />Works great. I have tested it with the Google Titan Security Key and Google Chrome. Epic. :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28094">issues.joomla.org/tracker/joomla-cms/28094</a>.</sub>

2020-03-01 12:58 UTC, richard67 commented
@HLeithner Could you test again?

2020-03-01 13:09 UTC, zero-24 commented
I have just added the docs required label to be sure we don't miss to add the docs as mention in the intial post.

2020-03-01 17:23 UTC, HLeithner requested changes

2020-03-01 17:23 UTC, HLeithner commented on layouts/plugins/system/webauthn/manage.php
> +
Missing JEXEC DIE

2020-03-01 17:23 UTC, HLeithner commented on plugins/system/webauthn/Webauthn/Helper/CredentialsCreation.php
> +
Missing JEXEC DIE

2020-03-01 17:23 UTC, HLeithner commented on plugins/system/webauthn/webauthn.xml
> +				<!-- TODO Select a preset image -->
Are there things missing?

2020-03-02 18:24 UTC, nikosdion commented on layouts/plugins/system/webauthn/manage.php
> +
Creating a commit to address all JEXEC issues now.

2020-03-02 18:24 UTC, nikosdion commented on plugins/system/webauthn/webauthn.xml
> +				<!-- TODO Select a preset image -->
These are not minimum viable product. They were ideas I had about customizing the login buttons. I'll remove them.

2020-03-03 18:36 UTC, karo3 commented
I have tested this item :white_check_mark: successfully on d081d0b306fb5174fd6cee782d0654192faf5ad0<br /><br />Great instructions! Did all 10 tests. Everything works as desired.
Small note: I would write the following URL in Test 8 /index.php?option=com_users&view=login<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28094">issues.joomla.org/tracker/joomla-cms/28094</a>.</sub>

2020-03-03 18:48 UTC, richard67 commented
@wilsonge Is there anything which should keep us from RTC? It has 2 good tests but I thought I ask you before I give RTC.

2020-03-03 18:54 UTC, wilsonge commented
Nope RTC. Although it does require @rdeutz to get the appveyor tests working finally before it can be merged (i believe as things stand we're not loading the right version (i.e. the windows one) of the file for things to pass)

2020-03-03 18:56 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28094">issues.joomla.org/tracker/joomla-cms/28094</a>.</sub>

2020-03-03 18:57 UTC, richard67 commented
@HLeithner As far as I could see your requested changes have all been implemented.

@rdeutz Reminder to pimp the Appveyor tests for this PR before merging ;-)

2020-03-04 08:33 UTC, HLeithner approved these changes
Waiting only for robert with appveyor

2020-03-05 09:54 UTC, HLeithner commented
@nikosdion finally if you merge 4.0-dev into this pr appveyor should be solved and we can merge this.

2020-03-05 13:01 UTC, nikosdion commented
Yup, Appveyor worked after merging 4.0-dev. Drone will take a little bit but I don't expect any problems there.

2020-03-05 13:24 UTC, HLeithner commented
Finally thanks for your time creating this awesome feature. I'm pretty sure there will be some cleanups but basically it's working fine. Also a thank you on all testers and commentators.

2020-03-05 13:24 UTC, merged

2020-03-05 13:42 UTC, nikosdion commented
Thank you for the merge!

2022-03-04 13:45 UTC, ceford commented
Documentation: I found a very short, incomplete proto-document and expanded it on the basis of my own experience and the PR description above. It is here:

https://docs.joomla.org/WebAuthn_Passwordless_Login

It may not be good enough! A week ago I had no clue how to use WebAuthn or even what a hardware device looked like.

2022-03-04 15:43 UTC, nikosdion commented
@ceford This is good and I can tell you how we can expand the authenticator information even more.

Any FIDO2 authenticator device will do e.g. https://www.amazon.com/s?k=FIDO2&crid=3VRB2JJME0KF3&sprefix=fid%2Caps%2C185&ref=nb_sb_noss_2

Many devices have built-in FIDO2-compliant authentication:
* Windows 10 and 11 have [Windows Hello](https://support.microsoft.com/en-us/windows/learn-about-windows-hello-and-set-it-up-dae28983-8242-bb2a-d3d1-87c9d265a5f0) as long as the device has or is attached to a fingerprint scanner or facial recognition camera.
* macOS has TouchID on all laptops with the T2 chipset, all laptops based on Apple Silicon, as well as Apple Silicon–based Mac mini and iMac devices using the new Apple Aluminium keyboard which has a fingerprint scanner.
* iOS / iPadOS has TouchID on all devices with a fingerprint scanner and FaceID on all newer devices with a FaceID infrared dot projection camera
* Some Android devices have a fingerprint scanner or a face recognition camera. These can also work as FIDO2 authenticators, I _think_ on Android 9 or later using Google Chrome at least (can't find any information and my test Android phone nearly caught fire due to a bloated battery; don't ask!)

We must definitely note that this feature **requires** HTTPS. It's been a major caveat during early development and testing.

Maybe in the developer docs we should link back to this PR so anyone curious enough can see my more detailed and more technical notes? Speaking of which, I think it's a good idea to do that as a minimum for new features where there's a main PR tracking them with an updated description that includes documentation.

2022-03-04 15:47 UTC, brianteeman commented
> Some Android devices have a fingerprint scanner
Works on my pixel 5 - now with android 12 but worked with 10 at least before that

2022-03-04 15:50 UTC, nikosdion commented
@brianteeman Thanks! I know 100% it works on Android 10. I am not sure if it works on Android 9. My old Nokia which only upgraded to 9 got a bloated battery and had to retire it. The battery got so bloated it broke the screen and cracked the back case. It was very close to getting ruptured and becoming an incendiary grenade 😱 If you have anyone still stuck on 9 with a phone that has a fingerprint scanner please do ask them to give it a go. Thanks!

2022-03-04 16:31 UTC, brianteeman commented
A phone with a fingerprint scan is high end so it's very unlikely to find one that has not been updated

2022-03-04 16:35 UTC, nikosdion commented
I was hoping someone with an older Xperia phone. Sony's the only manufacturer I know which only pushes updates for the Android version which was current at release and the next version but not anything beyond that (yeah, barely 18 months of updates for flagship phones, made the mistake once and never again).

2022-03-04 16:44 UTC, brianteeman commented
I have one of those in my collection but it's been updated

2022-03-04 21:20 UTC, brianteeman commented
And another way to do it is to use caBLE https://groups.google.com/a/fidoalliance.org/g/fido-dev/c/go6GoFW27Dw/m/9flCLR5pBQAJ?pli=1

2022-03-05 00:17 UTC, kitepascal commented
Hello, 

I had no idea of that outstanding WebAuthn Feature.

I will submit 2 Language overrides making things clearer...


One thing in question - on Windows 11 I cannot use the PIN Option (only Webcam or Fingerprint Scanner).

But on https://webauthn.io/ tests I can also use the Windows PIN. Is that an option, to enable also PIN for users that do not own a face recognition camera or fingerprint reader?

2022-03-05 00:49 UTC, kitepascal commented
https://github.com/joomla/joomla-cms/pull/37203/files

2022-03-05 02:37 UTC, ceford commented
I have incorporated the comments from @nikosdion and @brianteeman into the documentation.

2022-03-05 07:48 UTC, nikosdion commented
@kitepascal That's a good question. According to Microsoft, Windows Hello with a PIN [should have been supported since 2018](https://blogs.windows.com/msedgedev/2018/07/30/introducing-web-authentication-microsoft-edge/). On our end, we do tell the browser to let the user use either a roaming authenticator (USB key, Bluetooth key, ...) or a platform (built-in) authenticator which on Windows translates to Windows Hello. We don't have any further control I can see.

This weekend I'll be installing Windows 11 on my tertiary computer so I can test further.

2022-03-05 08:01 UTC, brianteeman commented
Just checked my windows 11 and I was  only offered

![image](https://user-images.githubusercontent.com/1296369/156874352-f98be60f-54c2-4473-8148-dfd5b7b34b88.png)

Gmail offered
![image](https://user-images.githubusercontent.com/1296369/156874410-f116b399-8523-4639-bbba-7b0240ec6296.png)

2022-03-05 11:40 UTC, nikosdion commented
So, I found out why Windows Hello doesn't offer PIN authentication with Joomla.

Apparently, Microsoft chose to only support RSASSA-PKCS1-v1_5 (RFC8017, article 8.1) public key signing and only with with SHA-256 as the hashing function for Windows Hello when using PIN authentication. [Thisis not considered a very secure signing method](https://crypto.stackexchange.com/questions/48407/should-i-be-using-pkcs1-v1-5-or-pss-for-rsa-signatures), since it can be cracked if collisions against SHA-256 are found (right now SHA-1 is broken and we can't expect SHA-256 to hold up much longer).

For this reason I had not added this algorithm in the WebAuthn implementation for Joomla. Instead, I had only added Edwards-curve Digital Signature Algorithm (EdDSA; only if libsodium is supported on the server); Elliptic Curve Cryptography with NIST P-521, P-384 or P-256; RSASSA-PSS with SHA-512, SHA-384 and SHA-256; Shared secret w/ HKDF and SHA-512; and Shared secret w/ AES-MAC 256-bit key. The algorithms I had added are the only truly secure ones based on what we currently know.

Why Microsoft chose to only implement the weaker version of RSASSA signing, especially when they have suffered from it in the past (Stuxnet), is beyond me. It would have made sense if it was a limitation in Windows Hello, yet its biometric authentication does support the more secure signing algorithms. Huh.

Anyway, for the _average user_ using Windows Hello with a PIN should still be secure enough for all practical purposes, at least until the day comes when collisions against SHA-256 become computationally efficient. So, yeah, we can add support for it.

The good news is that adding RSASSA-PKCS1-v1_5 support is as easy as adding three lines of code. I will make a PR later today after some further testing.

2022-03-05 12:01 UTC, kitepascal commented
Nice. I also checked some secure (Joomla maintenance) Services with WebAuthn - PIN option offered there but not Android biometrics yet (yesterday). @PhilETaylor 

That you get "Pixel 5" as an option on Windows 11 is an exciting  thing. I try to link my Samsung S21 to my Desktop Windows auth today. 
That could be another addition to the documentation. 

The more options enabled the better. More easy - more secure - crispy documented straight in Backend and detailed explanations in the wiki.
I think ~1% WebAuthn users will raise to at least ~15% 😉

2022-03-05 12:43 UTC, brianteeman commented
> So, I found out why Windows Hello doesn't offer PIN authentication with Joomla.

it also doesnt offer biometric and yet github does (weird)

2022-03-05 12:52 UTC, nikosdion commented
@brianteeman Yeah, I noticed that the code that actually went into Joomla only supports ECDSA with NIST P-256. This won't work for biometric authentication on Windows 11 or TouchID/FaceID on Apple devices. Grumble.

I am working on the PR right now, transferring the (very few and backwards compatible) changes I had already done in LoginGuard to support these features.

2022-03-05 13:17 UTC, nikosdion commented
Please try https://github.com/joomla/joomla-cms/pull/37205

I am very interested in the environments I do not have:
* Windows Hello with biometrics (not just PIN, the PIN works now, I have tested it myself).
* Android with biometrics.
* Browsers other than Edge, Chrome and other Chromium-based browsers on any platform OTHER than iOS/iPadOS (all browsers are Safari with a custom skin, nothing to change the functionality) and macOS (my primary OS, I know how browsers work there). To the best of my knowledge, Windows Hello and Android with biometrics will only work on Chromium-based browsers