[4.0] WebAuth improvements
joomla/joomla-cms pull request #28241
Opened 2020-03-05 17:02 UTC by C-Lodder

### Summary of Changes

1. Wrap JS inside IIFE
2. Namespace methods with `Joomla.` prefix
3. Move event listeners to JS (remove button `onclick` attributes)
4. Remove `backend.css` import, which doesn't seem to be part of Joomla

### Testing Instructions

https://github.com/joomla/joomla-cms/pull/28094#issue-380300939

### Expected result

WebAuth feature works same as before, without any JS errors.

2020-03-05 17:16 UTC, nikosdion commented
One very important correction. You removed the `onclick` element from the array that builds the button. **Please do NOT do that! ** This is meant to be usable by third party plugins which implement non-password logins such as but limited to Single Sign-On with external SSO servers (e.g. Amazon AWS SSO), Single Sign-On with JavaScript-based login (e.g. Synology SSO), social network logins (e.g. Login with Facebook) and future-proofing Joomla for similar core solutions to WebAuthn without the need to change the core in a backwards incompatible manner.

2020-03-05 17:22 UTC, C-Lodder commented
@nikosdion So shall I just use `$onClick = ''`?

2020-03-05 17:29 UTC, nikosdion requested changes
I can't comment on the ES6 implementation; as I said it's not my cup of tea and I only know enough of it to be dangerous 😆 

The CSS comment is more of a question than a request for change. If there is a reason you removed the management CSS please let me know; maybe we can remove that file altogether.

The thing about onclick is the most important thing I'd like to revert, though. Your solution works great and looks great but I'm afraid it is prone to misleading core and third party developers, undermining the grander vision of Joomla providing core support for non-password logins. I am relying on this feature's existence in 4.0 to implement free plugins for Synology SSO, possibly Amazon AWS SSO and definitely social logins. I'd even contribute these plugins if it wasn't for Joomla not allowing core contributions to only target specific third party products which are not web standards, i.e. the reason my older U2F TFA plugin never made it to the core back in 2013.

2020-03-05 17:29 UTC, nikosdion commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> -				'onclick' => $onClick,
There is a reason why I want the `onclick` element here which I kinda touched in my main comment on your PR.

The changes I made to `mod_login` are meant to allow third party plugins to implement non-password login options. However, if we don't demonstrate the use of `onclick` in the core we have the following problems:
1. Future core developers might consider the `onclick` feature unnecessary and remove it form future versions of Joomla, making it difficult for third party developers or breaking their existing plugins. Yeah, sure, we'll document it but my experience is that core contributors don't read the docs – can't blame them, they are hard to find!
1. Third party template developers might consider it an unnecessary option and not implement it in their core overrides.
1. Third party plugin developers might think that the only way to implement a login button is to either load a JS file or inline some JavaScript, even if their non-password login requires redirection to a component or running a third party JS event. This will lead to performance issues.

Yes, your solution looks better but the risks associated with streamlining the core code far outweigh the cosmetic benefits.

2020-03-05 17:29 UTC, nikosdion commented on layouts/plugins/system/webauthn/manage.php
> -HTMLHelper::_('stylesheet', 'plg_system_webauthn/backend.css', ['relative' => true]);
Why did you remove the stylesheet?

2020-03-05 17:34 UTC, nikosdion commented
@C-Lodder I explained it more in depth in my code review. It's not about WebAuthn working – your solution works great – but making it possible for third parties to be able to reliably implement non-password logins. Single Sign-On is an essential enterprise / corporate feature and there _is_ active interest in it; people have approached me asking to implement that in Joomla 3 on the basis that it's similar to what I'm doing with SocialLogin.

My feeling from Forum For The Future in Spain earlier this year is that Joomla is trying to be friendlier to enterprise users (makes sense; that's where the money, therefore the corporate volunteer time, will come from). So these 30 or so characters can make a big difference for our future.

2020-03-05 17:47 UTC, C-Lodder commented on layouts/plugins/system/webauthn/manage.php
> -HTMLHelper::_('stylesheet', 'plg_system_webauthn/backend.css', ['relative' => true]);
Because there is no `backend.css` being generated after `npm i`. The only CSS file generated for this plugin is `button.css`. Maybe is was just a mistake in that line of code?

2020-03-05 17:50 UTC, C-Lodder commented
@nikosdion Sorry, only just saw your actual code review comments now. I've reverted the main `onclick` removal which generated the login buttons. I'll keep the other ones in the layouts (edit/delete label) removed unless you feel they need to be reverted too.

2020-03-05 19:25 UTC, nikosdion commented on layouts/plugins/system/webauthn/manage.php
> -HTMLHelper::_('stylesheet', 'plg_system_webauthn/backend.css', ['relative' => true]);
Doh! I had already removed that CSS file myself months ago. You're right.

2020-03-06 09:07 UTC, nikosdion commented
@C-Lodder Your change is good. That's the only place I think needed change. Backend code is fully owned by the plugin, there's no link to the changes in mod_login. I'm happy :)

2020-03-06 12:05 UTC, wilsonge commented
Looks good at a quick review. Can someone just do a quick test of functionality and good to merge

2020-03-06 12:11 UTC, HLeithner commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
I know for what this is but shoudn't this be avoid in this why and done with a addEventListner?

2020-03-06 12:17 UTC, C-Lodder commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
@HLeithner This was discussed above and in other review comments.

2020-03-06 12:19 UTC, HLeithner commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
Yes I have seen it but with this option we have problems with CSP iirc and the correct way todo this is using addEventListner isn't it?

2020-03-06 12:21 UTC, C-Lodder commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
The correct way would be with the event listener in JS and I'm pro this approach. For now, I'm sticking with @nikosdion's suggestion. Or if the maintainers want come to a consensus, they can.

2020-03-06 12:40 UTC, nikosdion commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
How would you have a problem with CSP? This is always going to be same origin.

2020-03-06 12:58 UTC, HLeithner commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
src="javascript:" and on click handlers requests csp 'unsafe-inline' option which should be avoided for this we have com_csp which signs <script> tags.

Why doesn't the solution of @C-Lodder work? Or better how would another "non-password login" implementation look like? Maybe we can address it now with a click queue or something like this?

2020-03-06 15:11 UTC, dgrammatiko commented on build/media_source/plg_system_webauthn/js/login.es6.js
> +      alert(Joomla.JText._('PLG_SYSTEM_WEBAUTHN_ERR_EMPTY_USERNAME'));
Don't use alerts, use the API here

2020-03-06 15:13 UTC, dgrammatiko commented on build/media_source/plg_system_webauthn/js/login.es6.js
> +  Joomla.plgSystemWebauthnInterpolateParameters = (object, thisParamIsThePrefix) => {
I haven't saw the code but please expose only the needed functions and please use some sorter names eg: `Joomla.WebAuthParams` or similar as is right now is not even readable

2020-03-06 15:18 UTC, dgrammatiko commented on build/media_source/plg_system_webauthn/js/login.es6.js
> +    Joomla.request({
You can safely use `fetch` here instead of the callback based XHR. There is no browser with support for this feature that doesn't already support Promises and fetch. Also since fetch is thenable the code will immediately be easier to reason/read

2020-03-06 15:18 UTC, dgrammatiko commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
I'm strongly against passing JS functions in the markup. We can do better than that, a simple API (just an object like the one we use for the editors is all is needed here) So you still keep the devs ability to do custom things and do JS right

2020-03-06 15:26 UTC, C-Lodder commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
I'll let the maintainers decide on this one

2020-03-06 15:27 UTC, C-Lodder commented on build/media_source/plg_system_webauthn/js/login.es6.js
> +    Joomla.request({
I dont think a mass PR to move all XHR to fetch would be better...don't you?

2020-03-06 15:34 UTC, dgrammatiko commented on build/media_source/plg_system_webauthn/js/login.es6.js
> +    Joomla.request({
At some point I said that all these wrappers in core.js needed to go (XHR, Events). I think people are still seeing those things as helpful utilities although the platform has better implementations right now. Meh, whatever, for me this is useless code that needs to be transferred/parsed and executed for no other reason than what people falsely claim as B/C breaks...
Would be nice if someone could move the status quo to 2020. Also do the `type="module", nomodule` because the es6 files right now are serving no purpose...

2020-03-06 15:40 UTC, C-Lodder commented on build/media_source/plg_system_webauthn/js/login.es6.js
> +  Joomla.plgSystemWebauthnInterpolateParameters = (object, thisParamIsThePrefix) => {
done

2020-03-06 15:46 UTC, C-Lodder commented on build/media_source/plg_system_webauthn/js/login.es6.js
> +      alert(Joomla.JText._('PLG_SYSTEM_WEBAUTHN_ERR_EMPTY_USERNAME'));
done

2020-03-06 15:53 UTC, dgrammatiko commented on layouts/plugins/system/webauthn/manage.php
> -					<button onclick="return plgSystemWebauthnEditLabel(this, '<?php echo $randomId ?>');"
I think this will not work as expected. The original code will pass the new hash in the onClick, the new one will not not. The easier way out here is instead of using the `addScriptOptions` (couple lines above) is to use a data-attr here to pass the hash and collect it in JS. If I understand correctly the code, this piece of markup will be replaced with AJAX therefor @nikosdion used the onClick way but `addscriptOptions` will do exactly nothing in an AJAX call, therefor the `data-attr` proposal.

2020-03-06 16:15 UTC, nikosdion commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
@HLeithner You mean the `system/httpheaders` plugin signing the script tags (com_csp doesn't sign anything)? That's the first time I've heard of this behavior or the fact that unsafe-inline will be excluded by default. This is very surprising given that it's a major change that will break all third party extensions. I would publicize this important change now. I have a use case for onclick in the backend. This change means I need to rewrite the entire Configuration page of Akeeba Backup from scratch which is a major undertaking that takes months and I'd have loved to be able to schedule, gee, dunno, about a year in advance of the beta?!

Anyway. Considering that you intend on removing unsafe-inline by default in Joomla 4 then, yes, I agree that you should move the click handler in the JS. Also remove the onclick feature from the additional buttons in mod_login. 

Regarding non-password logins, example: https://github.com/akeeba/sociallogin/  (yes, I don't use onclick but I'm not sure a third party implementing a social network login / SSO would be so discriminate).

Optional: I would also add a comment in the WebAuthn plugin where the button is created explaining where the click event handler is set up **and why**. IMHO core code should not just follow best practices, it should also explain what and why they are best practices.

2020-03-06 16:23 UTC, HLeithner commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
iirc com_csp manage the white listing and it can be disabled of course but core will likely be shipped with no unsafe-inline js. I think we will see at a later stage if this is possible or not.

so @dgrammatiko had a suggestion to solve the onclick problem maybe he can do more specific suggestion?

2020-03-06 16:38 UTC, nikosdion commented on layouts/plugins/system/webauthn/manage.php
> -					<button onclick="return plgSystemWebauthnEditLabel(this, '<?php echo $randomId ?>');"
I thought about this after reading your comment and there is a way to write it better. The random ID can be a data attribute to the button and plgSystemWebauthnEditLabel can read it from there instead of expecting it as a second argument.

This would also demonstrate a good pattern for dealing with this kind of dynamic changing parameters without relying on a PHP helper.

2020-03-06 16:40 UTC, nikosdion commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
I made one. I was thinking about his comment and I was thinking about how I am using the same code pattern e.g. to download backup archives. Unless I am missing something glaringly obvious, data attributes would allow a click handler to retrieve this kind of dynamic parameters without having to rely on a PHP helper to pass script parameters (something which is not convenient when you have an arbitrary number of elements OR if you expect your content to be replaced e.g. by XHR OR if your click targets are generated dynamically, client-side).

2020-03-06 16:45 UTC, nikosdion commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
Since I'm the one who wrote that code: remove it. I realize now that if it's used you need to add 'unsafe-inline' to CSP which might be problematic if our objective with that core change is adding resilience against XSS. Upon thinking about it some more I believe that using Joomla's Document to push inline JavaScript or a custom JS file (whichever method offers best performance for the use case) is the way to go. My concern about dynamic parameters necessary for some SSO / non-password logins may be invalid given that all the browsers we are targeting with J4 allow accessing data attributes – I believe we are not dealing with IE9 anymore which is a bear when it comes to data attributes.

2020-03-06 17:04 UTC, C-Lodder commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
So are we using data attributes or `addScriptionOptions()`?

2020-03-06 17:07 UTC, nikosdion commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
Please use data attributes. I suspect `addScriptOptions` will fail miserably if you have multiple login areas on the page (think about a login module in the sidebar while displaying the com_users login page).

2020-03-06 17:26 UTC, dgrammatiko commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
> Upon thinking about it some more I believe that using Joomla's Document to push inline JavaScript or a custom JS file (whichever method offers best performance for the use case) is the way to go. 

Unfortunately this is falling sort on expectations. Yes inline scripts might be faster (less http requests, kinda irrelevant with h2) but the downside is more severe: you can only target the older js incarnation, that is es5! So all possible gains by creating js on the fly will always be subpar to a dedicated file (which can be properly minified and processed by some node apps eg webpack or roll up). I’ll still support my old idea that js should always be considered as static files by the cms

2020-03-06 18:31 UTC, nikosdion commented on plugins/system/webauthn/Webauthn/PluginTraits/AdditionalLoginButtons.php
> +				'onclick' => $onClick,
We do NOT disagree on principle.

> (less http requests, kinda irrelevant with h2)

No, it's not, unless you are talking about server push which is currently not available in Joomla. In its absence, even HTTP/2 has almost the same performance issues as HTTP/1.1 because you need to do the whole roundtrip to the server for each file you are downloading. The only saving grace for HTTP/2 is you don't have to suffer the TCP/IP and TLS handshake for every file (HTTP/1.0) / every 4-8 files (HTTP/1.1). But without server push the number of files is still relevant, I'm afraid 😞 

If we implement server push ([naive example](https://blog.cloudflare.com/using-http-2-server-push-with-php/)) in the Joomla core I have absolutely no qualms on advocating the proliferation of ES6/JS files!

So, to put it clearly:

Do you have a one-liner just to attach a click handler and nothing more? Inline JS **unless** Joomla implements HTTP/2 server push (and we magically only ever run on HTTP/2-capable web servers).

Do you have anything more substantial than that? JS / ES6 file.

Do you have dynamic data generated server-side to pass? Use addScriptOptions _or_ data attributes, based on your use case.

Did you try inlining the whole JS just because you had script options to pass? BZZT! Wrong. Start over.

Does that sound reasonable to you?

> you can only target the older js incarnation, that is es5!

I am talking ONLY about registering a click handler. Using ES5 or ES6 is largely irrelevant in this very narrow use case.

> I’ll still support my old idea that js should always be considered as static files by the cms

You know what's really funny? Your "old idea" has been our constant point of disagreement but it's not wrong _on principle_. It's the way you articulate it that ticks people off.

May I try to articulate it as a less combative axiom?

A developer should aim for the ideal situation where the entire client-side logic is embedded in static EcmaScript files which can be optimized and combined as needed. Dynamic data, generated server-side, should ideally be provided as data attributes in applicable elements or retrieved through AJAX, depending on security, performance and operational parameters. When this is not possible or practical, the absolute minimum possible amount of inline JS should be written. 

Is this basically what you have in mind? Have we been in agreement this entire time?

2020-03-06 22:48 UTC, C-Lodder commented
@nikosdion @dgrammatiko Data attribute are now in place

2020-03-07 16:14 UTC, dgrammatiko commented
Since I was mentioned here I guess I need to provide some answers, so:
@nikosdion you're right I'm thick on my approach about communicating the messages but this was on purpose: *the more severe the comment, more chances people will react on it*. The only problem with that approach was that I was getting the wrong reactions, people just commented on the messenger without paying attention to the actual message. Nevertheless it worked out in some occasions: CSP, Accessibility, etc, but it failed miserable on others: modularity, decoupling, etc...

@HLeithner you are right about CSP and that was one of the driving forces to remove all the inline listeners but there is one more reason: reducing the vector for XSS attacks. I'm not sure if this was ever written in any of the production team meetings but there was a consensus on that some years ago IIRC.

And now the part that @C-Lodder will gonna hate me for 😂, couple more suggestions:
- According to https://caniuse.com/#search=webauthn WebAuthn is relatively new (the newest browser that added support for it was Android Browser, late Feb 2020) so it will be wise to have some feature detection here, eg: https://stackoverflow.com/questions/55866575/how-to-detect-if-the-browser-has-support-for-webauthn
- Also another fact is that there won't be support for webAuthn without support for ES Modules. This give us some flexibility, so we can just load the ES6 **ONLY** file with a tag `type=module`. Also doing it so we can remove the document listener for `DOMContentReady` as **all** modules are deferred **by default**.
- Finally to cater for the older browsers, or the evergreen without support I propose to go the `progressive enhancement` way here. Plain English: in the (front end facing) layouts add by default an attribute `disable` on the button and then in the ES6 file, once we executed the feature detection part and we're sure that the feature is available remove it (eg `btn.removeAttribute('disable')`. This will also take care of the users that have disabled JS, so for all these the button **will not be clickable**. This can be enhanced even more with some message, but I think in order to do so we need to do some work on the build tools. Right now they just transpile every ES6 file, in this case this is not what we want (there is no reason to deliver the full script as it will never be executed in a legacy browser). To remedy this I think we need to introduce something in the settings.json, an array for excluding files from been transpiled to ES5. Once that is in place we can add an .es5.js that will just append/unveil  the message (eg webAuthn is not available in you dinosaur, use a modern browser)

2020-03-11 23:53 UTC, brianteeman commented
can you fix the conflicting file please

2020-03-19 16:21 UTC, wilsonge commented
I'm not against what @dgrammatiko said actually - i'm definitely in favour of progressive enhancement - but I'd like to see this merged as a first step on the path to greatness :) - this es6 refactor is required either way (even if it can be cleaned up a bit further when we move to modules) So that being said can we please test this?

2020-04-10 08:58 UTC, C-Lodder commented
Conflicts resolved

2020-05-26 09:19 UTC, C-Lodder commented
Is this going anywhere?

2020-05-26 09:54 UTC, dgrammatiko commented
@C-Lodder please don't close this, it's highly needed to be merged

2020-05-26 09:59 UTC, brianteeman commented on modules/mod_login/tmpl/default.php
> +						data-webauthn-url="<?= $button['data-webauthn-url'] ?>"
```suggestion
					data-webauthn-url="<?= $button['data-webauthn-url'] ?>"
```

2020-05-26 10:00 UTC, brianteeman commented
(sorry I can't test right now)

2020-05-28 18:39 UTC, merged

2020-05-28 18:39 UTC, wilsonge commented
I feel a bit un-easy merging this without tests - but I guess there's a better chance of testing if it's in core :/