[4.0] WebAuthn Improve new SQL, INI and XML files
joomla/joomla-cms pull request #28254
Opened 2020-03-06 18:49 UTC by zero-24

### Summary of Changes

WebAuth Improve SQL, INI and XML files:
- Reorder XML files
- Alpha order new language strings
- cleanup SQl files and rename the update files to the actual merge date

### Testing Instructions

Same as: https://github.com/joomla/joomla-cms/pull/28094

### Expected result

WebAuthn still works

### Documentation Changes Required

none

2020-03-06 22:12 UTC, brianteeman commented on administrator/language/en-GB/plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_ERR_CANNOT_FIND_USERNAME="Cannot find the username field in the login module. Sorry, Passwordless authentication will not work on this site unless you use a different login module
```suggestion
PLG_SYSTEM_WEBAUTHN_ERR_CANNOT_FIND_USERNAME="Can't find the username field in the login module. Sorry, passwordless authentication will not work on this site unless you use a different login module."
```

2020-03-10 05:27 UTC, wilsonge requested changes

2020-03-10 05:27 UTC, wilsonge commented on plugins/system/webauthn/webauthn.xml
> +	<creationDate>July 2019</creationDate>
If you’re changing sql dates guess this should change too

2020-03-10 08:59 UTC, alikon commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-03-05.sql
> +  PRIMARY KEY (`id`,
```suggestion
   PRIMARY KEY (`id`(100)),
```

2020-03-10 09:00 UTC, alikon commented on installation/sql/mysql/joomla.sql
> +  PRIMARY KEY (`id`),
```suggestion
   PRIMARY KEY (`id`(100)),
```

2020-03-15 14:26 UTC, zero-24 commented on plugins/system/webauthn/webauthn.xml
> +	<creationDate>July 2019</creationDate>
Done.

2020-03-15 14:31 UTC, closed without merging