Change `defined('JPATH_BASE') or die;` into `defined('_JEXEC') or die;` for layout folder
joomla/joomla-cms pull request #28416
Opened 2020-03-21 09:38 UTC by astridx

# Summary of Changes
Because I think it is a bug i changed 
`defined('JPATH_BASE') or die;`
into
`defined('_JEXEC') or die;`

### Testing Instructions
Code review.

2020-03-21 21:57 UTC, chmst commented on layouts/joomla/content/full_image.php
> +defined('_JEXEC') or die;
Addan empty line?

2020-03-21 22:00 UTC, chmst commented on layouts/joomla/content/intro_image.php
> +defined('_JEXEC') or die;
Add empty line?

2020-03-21 22:01 UTC, chmst commented on layouts/joomla/edit/item_title.php
> +defined('_JEXEC') or die;
Add empty line?

2020-03-21 22:51 UTC, ReLater commented
I don't know what's wrong or right. Probably just for reference ;-)
https://github.com/joomla/joomla-cms/pull/8398

2020-03-22 07:34 UTC, Bakual commented
Since I merged the referenced one back then: I think I merged it just so we use the same in all layouts. This doesn't necessary mean it's "right".
Maybe @zero-24 remembers why we used `JPATH_BASE` then? Personally I don't see a reason to use a different constant than `_JEXEC` anywhere. So this PR would be fine.

2020-03-22 08:03 UTC, zero-24 commented
hmm I said back then JPATH_BASE is the correct one but i can't remember why. I'm sure it was a thing we discussed in the maintainers chat back then and we maybe did it because the most where jPath_base in the first place. Maybe @phproberto has an idea on this?

2020-03-22 08:09 UTC, chmst commented
The only what I remember is, that there is a difference between backend and frontend. They are applications of their own. Maybe this makes a difference?

2020-03-22 08:30 UTC, astridx commented on layouts/joomla/content/full_image.php
> +defined('_JEXEC') or die;
Done

2020-03-22 08:30 UTC, astridx commented on layouts/joomla/content/intro_image.php
> +defined('_JEXEC') or die;
Done

2020-03-22 08:31 UTC, astridx commented on layouts/joomla/edit/item_title.php
> +defined('_JEXEC') or die;
Done

2020-03-22 08:51 UTC, astridx commented
> @ReLater I don't know what's wrong or right. 

I also don't know what's wrong or right.
I think that `JPATH_BASE` is also set everywhere. But: I once learned that `_JEXEC` has the function to mark a secure entry point into Joomla (https://docs.joomla.org/JEXEC). That's why I find it confusing when something else is used.

`JPATH_BASE` actually has a different function (The path to the installed Joomla! site, or JPATH_ROOT/administrator if executed from the backend; https://docs.joomla.org/Constants). 

It could also lead to errors. For example, `_JEXEC` is set in the tests (https://github.com/joomla/joomla-cms/blob/e381b1af9decd5b670e5d67a14a81a9d11ab1bfc/tests/unit/bootstrap.php#L26). `JPATH_BASE` is also set here . But for another reason.

But maybe I'm missing something?

2020-03-24 08:45 UTC, phproberto commented
I think using `_JEXEC` is fine and better. I think the initial JLayout included the `JPAH_BASE` and then it was spread. 

I think `_JEXEC` is better because it's what is already being used and requested to extension developers in modules, views, etc. Same rule applied everywhere and less confusing.

Layout tests should be ok because both constants exist in the test suite.

It's a :+1: from me.

Thanks everybody for your time on this!

2020-03-24 09:44 UTC, zero-24 commented
Awesome thanks for the quick feedback on this one @phproberto

2020-03-24 10:40 UTC, ReLater commented
I have tested this item :white_check_mark: successfully on 4c90028c34b532d228d172d221626ab7d9775c1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28416">issues.joomla.org/tracker/joomla-cms/28416</a>.</sub>

2020-03-24 11:15 UTC, zero-24 requested changes
Just a few empty line suggestions ;)

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/content/info_block/associations.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/content/options_default.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/content/text_filters.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/links/groupclose.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/links/groupopen.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/links/groupsclose.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/links/groupseparator.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/links/groupsopen.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/toolbar/base.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/toolbar/containerclose.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/toolbar/containeropen.php
>  ?>
```suggestion

?>
```

2020-03-24 11:15 UTC, zero-24 commented on layouts/joomla/toolbar/iconclass.php
>  ?>
```suggestion

?>
```

2020-03-24 18:18 UTC, astridx reviewed
Done

2020-03-24 20:00 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 70da436623f8754c73810a119b81dead4b135fc5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28416">issues.joomla.org/tracker/joomla-cms/28416</a>.</sub>

2020-03-24 22:22 UTC, zero-24 commented
merging thanks @astridx  👍

2020-03-24 22:22 UTC, merged

2020-05-04 19:13 UTC, Paladin commented
As an Old Phart (tm) my memory may not be the most reliable, but to chime in on @zero-24's comment I think this dates back into the dawning ages of the layouts. The discussion he almost remembers, I think, was over differentiating between the different purposes of the two constants, JEXEC marking the full CMS was present and executing, while JPATH_BASE merely indicating the Joomla files were present and available, not necessarily the CMS, thus enabling the layouts to work in applications outside of the CMS.

That doesn't seem to be an important consideration these days, and this isn't tossed in to say the change is wrong. I'm just contributing some extra memories so something else doesn't get completely lost in the haze of the past.

2020-05-04 19:15 UTC, brianteeman commented
Institutional memory is very important

2020-05-04 19:15 UTC, zero-24 commented
Thanks for your input @Paladin :-)