[4.0] Fix deleting user groups
joomla/joomla-cms pull request #28687
Opened 2020-04-15 08:28 UTC by SharkyKZ

Fixes https://github.com/joomla/joomla-cms/issues/28522.

### Summary of Changes

Fixes query when deleting user groups.

### Testing Instructions

Delete `Manager` user group.

### Expected result

Group deleted and site continues to work.

### Actual result

Group deleted but site is broken, modules are missing;

> ![screen shot 2020-03-31 at 08 49 09](https://camo.githubusercontent.com/271f05701c37bb7bf7f6b539ab307ad136be0082/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f38656333383736363265346337643764643765363061323562376637363437382e6a7067)
### Documentation Changes Required

No.

2020-04-15 09:28 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on baa3012e493de7e834888477b8ace69875bb85e6<br /><br />Tested with MySQL 8.0.19 (both MySQLi and PDO) and PosgreSQL 11. All fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28687">issues.joomla.org/tracker/joomla-cms/28687</a>.</sub>

2020-04-15 09:32 UTC, alikon requested changes

2020-04-15 09:32 UTC, alikon commented on libraries/src/Table/Usergroup.php
> +				->set($db->quoteName('rules') . ' = ' . str_repeat('REPLACE(', 4 * \count($ids)) . $db->quoteName('rules') . implode(')', $replace) . ')')
we are loosing the prepared bind in this way

2020-04-15 09:34 UTC, richard67 commented on libraries/src/Table/Usergroup.php
> +				->set($db->quoteName('rules') . ' = ' . str_repeat('REPLACE(', 4 * \count($ids)) . $db->quoteName('rules') . implode(')', $replace) . ')')
It is safe, there is no user input involved, and it makes it work. So I am ok with it. Just my 5 cent.

2020-04-15 09:44 UTC, chmst commented on libraries/src/Table/Usergroup.php
> +				->set($db->quoteName('rules') . ' = ' . str_repeat('REPLACE(', 4 * \count($ids)) . $db->quoteName('rules') . implode(')', $replace) . ')')
The only other way I found is a foreach over all  records with updating every item. Ir does no harm, because there are not many viewlevels, but as @richard67 says, this is safe.

2020-04-15 11:32 UTC, chmst commented
I have tested this item :white_check_mark: successfully on baa3012e493de7e834888477b8ace69875bb85e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28687">issues.joomla.org/tracker/joomla-cms/28687</a>.</sub>

2020-04-15 11:52 UTC, richard67 commented on libraries/src/Table/Usergroup.php
> +				->set($db->quoteName('rules') . ' = ' . str_repeat('REPLACE(', 4 * \count($ids)) . $db->quoteName('rules') . implode(')', $replace) . ')')
@alikon Are you convinced? May I set it RTC? Or do you want to discuss that with @SharkyKZ ?

2020-04-15 11:58 UTC, alikon commented on libraries/src/Table/Usergroup.php
> +				->set($db->quoteName('rules') . ' = ' . str_repeat('REPLACE(', 4 * \count($ids)) . $db->quoteName('rules') . implode(')', $replace) . ')')
no i'm not, but that don't prevent to set this as RTC cause there are 2 tests
imho despite  there are no clear user input, but there are variables then they should be validated on the server side like any other variable parameters

2020-04-15 12:01 UTC, richard67 commented on libraries/src/Table/Usergroup.php
> +				->set($db->quoteName('rules') . ' = ' . str_repeat('REPLACE(', 4 * \count($ids)) . $db->quoteName('rules') . implode(')', $replace) . ')')
@SharkyKZ Was the problem in the wrong `')'` at the end of each of these `$replace[] =` statements? Or was it in the prepared statement below? Maybe it can be changed bacl to prepared statement?

2020-04-15 13:24 UTC, SharkyKZ commented on libraries/src/Table/Usergroup.php
> +				->set($db->quoteName('rules') . ' = ' . str_repeat('REPLACE(', 4 * \count($ids)) . $db->quoteName('rules') . implode(')', $replace) . ')')
Because of prepared statement. It's possible to keep prepared statement but there's not much point as you've already noticed.

2020-04-15 13:26 UTC, richard67 commented on libraries/src/Table/Usergroup.php
> +				->set($db->quoteName('rules') . ' = ' . str_repeat('REPLACE(', 4 * \count($ids)) . $db->quoteName('rules') . implode(')', $replace) . ')')
I set it to RTC, we can later optimize that again if we want. Now it fixes a really ugly bug.

2020-04-15 13:27 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28687">issues.joomla.org/tracker/joomla-cms/28687</a>.</sub>

2020-04-15 13:43 UTC, adj9 commented
I have tested this item :white_check_mark: successfully on baa3012e493de7e834888477b8ace69875bb85e6<br /><br />I confirm, the site still works ... it has no interruptions. Even with a logout and subsequent login.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28687">issues.joomla.org/tracker/joomla-cms/28687</a>.</sub>

2020-04-17 08:40 UTC, merged

2020-04-17 08:40 UTC, wilsonge commented
Thanks!