Fix Colorscheme
joomla/joomla-cms pull request #28788
Opened 2020-04-25 11:35 UTC by coolcat-creations

Pull request for https://github.com/joomla/joomla-cms/issues/28215

List of changes:
- Changed Button Color in Login to Link color scheme like used in logged in backend
- Changed Border Color and box shadows of inputs to a neutral color (not blue-ish) to fit to custom schemes
- Adjusted Joomla login image to inherit the dark background color
- Adjusted logo heading h1 to take the dark background color
- adjusted logo heading h2 to take the dark text color
- fixed quick Icons gradient colors 
- fixed text muted - everyone forgive me the !important but I could not find where the important was set before.
- added parameter for sidebar link color because this var was used in scss
- changed toolbar options and help icon and hover appearance color according to default setting

### Testing Instructions
Go into atum template style options and chose different colors in every field (this pr does not fix logo issues!)
Check if the template looks nice 

### Expected result

If you change the colors you should be happy with the result somehow :-) 

![Bildschirmfoto 2020-04-25 um 13 29 20](https://user-images.githubusercontent.com/828371/80278790-66ece000-86f9-11ea-88a1-c2b8f50cd87b.png)

![Bildschirmfoto 2020-04-25 um 13 29 37](https://user-images.githubusercontent.com/828371/80278787-62c0c280-86f9-11ea-9a07-6de6aea91830.png)

### Actual result
See issue https://github.com/joomla/joomla-cms/issues/28215

### Documentation Changes Required
Added Sidebar Link Colour parameter

2020-04-25 11:38 UTC, brianteeman commented on administrator/templates/atum/templateDetails.xml
> +				/>
```suggestion
				<field
					name="sidebar-link-color"
					type="color"
					label="TPL_ATUM_COLORS_SETTINGS_LINK_SIDEBAR_COLOR_LABEL"
					default="#3b4a5c"
					filter="color"
				/>
```

2020-04-25 11:39 UTC, coolcat-creations reviewed
Thank you

2020-04-25 11:53 UTC, brianteeman commented
My test did not produce the same screenshots as you. The sidebar on the login and admin screens are no longer full height<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28788">issues.joomla.org/tracker/joomla-cms/28788</a>.</sub>

2020-04-25 11:56 UTC, coolcat-creations commented
@brianteeman that's strange because I did not change anything about the sidebar heights at all. Is the issue gone when you revert the patch?

2020-04-25 12:25 UTC, brianteeman commented
> Changed Border Color and box shadows of inputs to a neutral color (not blue-ish) to fit to custom schemes

I am not a fan of this change. They exist because we have no outline and serve as the focus indicator which is fairly universally a blue.

For example here on github
```
.form-control.focus, .form-control:focus, .form-select.focus, .form-select:focus {
    border-color: #2188ff;
    outline: none;
    box-shadow: inset 0 1px 2px rgba(27,31,35,.075), 0 0 0 0.2em rgba(3,102,214,.3);
}
```

2020-04-25 12:52 UTC, coolcat-creations commented
@brianteeman  I only desaturated the box shadow it was very light before - In terms of accessibility it's only slighty recognizeable that it changed - it makes the scheme more harmonic as before. 

I did not change the focus border btw, if thats your concern, only the light shadow.

2020-04-25 12:57 UTC, faustonenci commented
I have tested this item :red_circle: unsuccessfully on f0120abce8f1f3433a3bc186357cf43a3168b7ff<br /><br />the patch not produce the same screenshots as you

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28788">issues.joomla.org/tracker/joomla-cms/28788</a>.</sub>

2020-04-25 12:59 UTC, coolcat-creations commented
@faustonenci  I used my own colors - your screenshots should not match to mine but have better results like in the posted issue: https://github.com/joomla/joomla-cms/issues/28215

2020-04-25 13:08 UTC, brianteeman commented
the sidebar was an unrelated issue

2020-04-25 13:10 UTC, faustonenci commented
![template color change2](https://user-images.githubusercontent.com/11662263/80280819-e7fea400-8706-11ea-9062-38f6bae63d04.PNG)
I used random colors, and after cleaning the browser chache the only problem remains in the joomla version logo

2020-04-25 13:11 UTC, coolcat-creations commented
@faustonenci can you retest now ?
Please revert the patch, fetch new, apply again and clear the browser cache

2020-04-25 13:54 UTC, faustonenci commented
I restored all the site and the fatches, I applied the patch again, I only see a problem with the joomla version logo which unlike the other logos uses this style class
.text-muted {
    color: # 6c757d! important;
}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28788">issues.joomla.org/tracker/joomla-cms/28788</a>.</sub>

2020-04-25 14:03 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_login.scss
> +    svg.joomla-logo {
I've raised this before. You should not be targetting SVG's like this in the template SCSS. Dimensions should be done directly within the logo SVG

2020-04-25 14:04 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_login.scss
> +      path {
same as above. Put the fill within the SVG

2020-04-25 14:06 UTC, coolcat-creations commented on administrator/templates/atum/scss/blocks/_login.scss
> +      path {
Then I need to create another image for the login view, yes?

2020-04-25 14:08 UTC, C-Lodder commented on administrator/templates/atum/scss/blocks/_login.scss
> +      path {
I thought this was already targetting the login logo, see as the code is in `_login.scss`

2020-04-25 14:10 UTC, coolcat-creations commented
> I restored all the site and the fatches, I applied the patch again, I only see a problem with the joomla version logo which unlike the other logos uses this style class
> .text-muted {
> color: # 6c757d! important;
> }
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/28788](https://issues.joomla.org/tracker/joomla-cms/28788).

Yes but I actually overwrote it in header, thats why I thought it's a cache issue :-( Anyone else has the same issue?

2020-04-25 14:15 UTC, coolcat-creations commented on administrator/templates/atum/scss/blocks/_login.scss
> +      path {
Yes but the login logo is the same as used at other places, when I change the size inside the svg then I need to create a seperate svg only for login. You agree?

2020-04-25 14:19 UTC, Razzo1987 commented
See:
![immagine](https://user-images.githubusercontent.com/906604/80282194-63b11e80-8710-11ea-8be8-0ddfb0a0cd26.png)

I done a PR in your branch: https://github.com/Razzo1987/joomla-cms/commit/2bb7a62d10435ceac87d25e5869fc19022b85c05

2020-04-25 14:26 UTC, coolcat-creations commented
@Razzo1987 but you removed text-muted, I think it should be muted when the header is disabled?

2020-04-25 14:32 UTC, Razzo1987 commented
@coolcat-creations Bootsrap 4 text-muted color is "var(--atum-text-light) !important"
If think it is correct because .text-muted is grey.
If you wont the color of the icon the same of other icons you must remove it or add a more "important" definition of .text-muted in the topbar

2020-04-25 14:34 UTC, coolcat-creations commented
@Razzo1987 yes I added the definition for header - it's in the _header.scss file. You don't see the changes either?

2020-04-25 14:43 UTC, Razzo1987 commented
I'm not understanding the problem compared to the screen:
https://github.com/joomla/joomla-cms/pull/28788#issuecomment-619377517
I have the same color set and the same result with the code you described.

But the result is different from the request:
https://user-images.githubusercontent.com/2539440/75856202-260cd500-5df4-11ea-9f15-3a7c48398b84.png

What is the desired result?
Gray or white icon fot joomla version?

2020-04-25 14:58 UTC, coolcat-creations commented
@Razzo1987 - I have an idea, can you change light text value in your settings to #ffffff and see if it works then? if yes I know what to check again.

because you see I defined the muted-text in the top bar:
![grafik](https://user-images.githubusercontent.com/828371/80283122-c3f68f00-8715-11ea-88e1-640bb9784d5c.png)

2020-04-25 14:58 UTC, Razzo1987 commented
Also:
![immagine](https://user-images.githubusercontent.com/906604/80282957-a96fe600-8714-11ea-9067-eb5248100188.png)

![immagine](https://user-images.githubusercontent.com/906604/80282977-cf958600-8714-11ea-919c-29772862bdce.png)

Not muted: #fff instead `var(--atum-text-light)`
I think:

```
.header .header-item .header-item-content > :first-child  {
color: var(--atum-text-light) !important;
}
.header .header-item .header-item-content .text-muted {
color: var(--atum-text-light) !important;
opacity: .6;
}
```

instead `$white` try to insert` var(--atum-text-light) !important`

2020-04-25 15:04 UTC, Razzo1987 commented
> 
> 
> @Razzo1987 - I have an idea, can you change light text value in your settings to #ffffff and see if it works then? if yes I know what to check again.

![immagine](https://user-images.githubusercontent.com/906604/80283234-4e3ef300-8716-11ea-87cb-ff055ec0b5ef.png)

Yes is good,
but in this way the icons can't change the color, so if you use a a dark color for Light Text:

![immagine](https://user-images.githubusercontent.com/906604/80283293-bee60f80-8716-11ea-9f76-8d058749a760.png)
![immagine](https://user-images.githubusercontent.com/906604/80283296-c86f7780-8716-11ea-91dc-30da7e6a3890.png)

2020-04-25 15:04 UTC, coolcat-creations commented
Now I understand where all the confusion comes from- the other buttons stay white while they should change to the var(--atum-text-light) - or second possibility the Joomla Logo should be white - I think you are right, it should be all set to white in the header then like the other elements. Sorry I misunderstood the issues :-)

2020-04-25 15:10 UTC, coolcat-creations commented on administrator/templates/atum/scss/blocks/_login.scss
> +      path {
Can we exclude this logo code issue in another issue? Because I think there is more stuff to change there, we have different logo-blue, joomla-logo-blue and things flying around, I need to change also behaviour when a custom logo is added...

I will clean this up in a seperate PR ok?

2020-04-25 15:10 UTC, coolcat-creations commented
@Razzo1987 and @faustonenci you can retest now if you want :-)

2020-04-25 15:40 UTC, Razzo1987 commented
![immagine](https://user-images.githubusercontent.com/906604/80283899-5cdbd900-871b-11ea-8725-5338ba68bcd5.png)

![immagine](https://user-images.githubusercontent.com/906604/80283921-7715b700-871b-11ea-9686-1b296457f17e.png)

See https://github.com/joomla/joomla-cms/pull/28788/files/8b66259a66106dafd2654a801a1176b14d094819..fa6f6e854999cab3cd0f7701d15a32f1467980a6#diff-fab202d130ff6570c9e945edeed1ffe6

2020-04-25 15:41 UTC, Razzo1987 requested changes

2020-04-25 15:41 UTC, Razzo1987 commented on administrator/templates/atum/scss/blocks/_header.scss
>        .text-muted {
.text-muted, .disabled

2020-04-25 17:05 UTC, coolcat-creations commented
Thank you @Razzo1987 and @faustonenci now it should be finally fine :-)

2020-04-25 20:42 UTC, Quy commented on administrator/templates/atum/scss/blocks/_toolbar.scss
> +        color:  var(--atum-text-light);
```suggestion
        color: var(--atum-text-light);
```

2020-04-25 20:42 UTC, Quy commented on administrator/templates/atum/scss/blocks/_header.scss
> +        color: #fff!important;
```suggestion
        color: #fff !important;
```

2020-04-26 08:13 UTC, faustonenci commented
I have tested this item :white_check_mark: successfully on 5c207ec9c808ca7050875351b49bfc840d50cf45<br /><br />good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28788">issues.joomla.org/tracker/joomla-cms/28788</a>.</sub>

2020-04-26 08:39 UTC, Razzo1987 commented
@coolcat-creations  :hover :( (see image 3)

![immagine](https://user-images.githubusercontent.com/906604/80302369-ef2abe00-87a9-11ea-9628-74964f8ef59b.png)

![immagine](https://user-images.githubusercontent.com/906604/80302390-049fe800-87aa-11ea-8dd4-6edd4c6ad1a2.png)

![immagine](https://user-images.githubusercontent.com/906604/80302406-2600d400-87aa-11ea-8e60-4eb7c48e71ed.png)

2020-04-26 09:28 UTC, Razzo1987 commented
Also.... What do you think about:

![immagine](https://user-images.githubusercontent.com/906604/80303525-11740a00-87b1-11ea-862f-7663d567676d.png)

2020-04-26 11:15 UTC, coolcat-creations commented
@Razzo1987 
The hover color is the link color, I think that's "ok" - or we need to open a seperate issue and discuss the hover-color there.

Thank you for your idea about the colorslider - I honestly consider to remove the hue slider for the dark color at all and want to open a RFC issue for it - the hue slider was formaly there to satisfy the needs for the former dark sidebar and different color shades there. now we actually don't need this anymore. I don't know... Anyway this would be a separate issue too. Please let's go forward with this in small steps :-) 

This PR does not make everything perfect but moves it forward at least.

2020-04-26 12:53 UTC, Quy commented on administrator/templates/atum/scss/blocks/_global.scss
> +  color: var(--atum-text-dark)!important;
```suggestion
  color: var(--atum-text-dark) !important;
```

2020-04-27 06:53 UTC, micker commented
sorry for delay test ✅

2020-04-27 08:34 UTC, Razzo1987 commented
I have tested this item :white_check_mark: successfully on d5825c824f9bb37c989a6f34b7311cc237a36530<br /><br />OK: It works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28788">issues.joomla.org/tracker/joomla-cms/28788</a>.</sub>

2020-04-27 09:33 UTC, coolcat-creations commented
Last change was CS... @richard67 can I ask for RTC? :-)

2020-04-27 09:36 UTC, richard67 commented
@coolcat-creations Has the discussion with @C-Lodder been resolved?

2020-04-27 09:43 UTC, coolcat-creations commented
@richard67 Regarding the Logo: No but thats a completely new PR / Issue to work on which I will do as next. We need to clean up and rename the used .svg Logos. They are not named properly, they are not used properly and the custom logos are not described good enough so that a user can change it in the way he/she wants. I would open the Issue directly afterwards.

2020-04-27 09:46 UTC, richard67 commented
Last change was just CS. I've set back the test restults.
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28788">issues.joomla.org/tracker/joomla-cms/28788</a>.</sub>

2020-04-29 16:40 UTC, Quy commented
Please fix conflicts.

2020-05-02 10:52 UTC, merged

2020-05-02 10:53 UTC, wilsonge commented
Thankyou  for working on this @coolcat-creations ! Much appreciated!

2020-05-02 15:14 UTC, richard67 commented
Was the change described in issue #28906 intended?