Atum - Accessibility - Change Font Size - Why only 18px
joomla/joomla-cms pull request #28841
Opened 2020-04-27 20:17 UTC by PhocaCz

This may not be the right pull request, maybe just an idea. If it is incorrect due to my ignorance of the system, then I apologize.

I just didn't find a way to decrease the font size in the Atum template parameters. Then I found, there is a way to increase the font size in Joomla! 4 Accessibility Settings. The question is, why there is YES/NO option only and why not use this parameter and not add more options? I can imagine, for a lot of people current font size is too large and they want to decrease it. For another group, 18px is not enough (please ignore the fact that this can be done per browser, the parameter just exists so this PR just extends it). Of course, it can be somehow in conflict with another parts of CSS features which I don't know (so in this case, CSS developers should make a statement to this PR).

### Summary of Changes
I just added some more values to parameter **Increase Font Size**, so user will be able to change font size to: 80%, 90%, 110%, 125% (of course, values can be extended).

![Increase Font Size](https://i.imgur.com/GTV0Jqr.png)

Of course, ideally, the parameter name should also change (from Increase to Increase/Decrease ...)

### Testing Instructions
Install the patch and just go to Accessibility Settings and switch the font size. (SCSS file _global.scss was changed - for now I have no information if patch tester is able to compile scss or it needs to be done manually.)

### Expected result
You will be able to increase/decrease font size of Atum - backend template.

90%:
![90%](https://i.imgur.com/PClnspn.png)

125%:
![125%](https://i.imgur.com/3k8knQF.png)

Jan

2020-04-27 20:24 UTC, brianteeman commented
It's a valid accessibility to add a % increase
I can't imagine any accessibility case for decreasing the font size

That's not saying there isnt a case for setting the font size just that accessibility options is not the correct place to set a decrease

2020-04-27 20:27 UTC, coolcat-creations commented
I agree to the decrease like @brianteeman said - Can we have a value slider or a num field to set the increase, then you would not need to add severall percentages? Or is the dropdown more accessible?

2020-04-27 20:30 UTC, brianteeman commented
any of those can be accessible

2020-04-27 20:37 UTC, chmst commented
> I can't imagine any accessibility case for decreasing the font size

There is a use case. Unfortunately I cannot describe it in English and dn't have the ophthalmologist vocabulary. There are people who can see only a small area like at the end of a tunnel. They try to make fonts small so that they see more in the small area they can see.

2020-04-27 20:43 UTC, PhocaCz commented
> I can't imagine any accessibility case for decreasing the font size

I understand but why not use this parameter? Why to add another one (in case, there is a demand for such feature) . You can add new feature (decreasing) with only adding new values to current parameter.

Having smaller font size means for somebody displaying more content on screen (without scrolling, moving, etc).

2020-04-27 20:48 UTC, PhocaCz commented
> There is a use case. Unfortunately I cannot describe it in English and dn't have the ophthalmologist vocabulary. There are people who can see only a small area like at the end of a tunnel. They try to make fonts small so that they see more in the small area they can see.

Yes, and I don't think, extending plus values by minus values is something complicated and may bother someone.

2020-04-27 20:49 UTC, coolcat-creations commented
So what about a num field for percentage input? It's probably most flexible?

2020-04-27 20:51 UTC, PhocaCz commented
> So what about a num field for percentage input? It's probably most flexible?

There is a range form field in Joomla! (HTML) but it does not display values:

![range](https://i.imgur.com/XUCwVrr.png)

2020-04-27 20:51 UTC, brianteeman commented
@chmst valid point

2020-04-27 20:53 UTC, PhocaCz commented
> So what about a num field for percentage input? It's probably most flexible?

You can even add own values (text form field), but then you need to completely overwrite this feature, because there is no option to add own values to static CSS file.

2020-04-27 21:00 UTC, C-Lodder commented
I'm a little confused as to why this is a com_users option but the styling is part of the template. Either this option should be moved to the template or the styling should go in a core SCSS file and be imported via the template

2020-04-27 21:01 UTC, coolcat-creations commented
> I'm a little confused as to why this is a com_users option but the styling is part of the template. Either this option should be moved to the template or the styling should go in a core SCSS file and be imported via the template

It's because it's user specific style change for accessibility.

2020-04-27 21:04 UTC, C-Lodder commented
That's fair enough. But then if I install a 3rd party backend template, this setting will most likely not work unless the developer uses the same CSS.

2020-04-27 21:17 UTC, PhocaCz commented
> I'm a little confused as to why this is a com_users option but the styling is part of the template. Either this option should be moved to the template or the styling should go in a core SCSS file and be imported via the template

Hmmm, I think, a strategic decision must be made here. Will all accessibility parameters be bound to the template? If yes, parameters should be moved to template. If no, even if it's technically bad (affecting the template by the component), it should stay where it is for now.

2020-04-27 21:35 UTC, coolcat-creations commented
What about a Template style select in User settings and the possibility to add a new template style easily from there? For this every backend user would need to have the rights to create a new style. It would not be a11y settings but style settings in general but solve the need for customisation?

2020-04-28 15:21 UTC, SharkyKZ commented
Any comments on how these settings compare to Accessibility plugin? Do we need both?

2020-04-28 15:49 UTC, PhocaCz commented
> Any comments on how these settings compare to Accessibility plugin? Do we need both?

In fact, I don't know, the purpose of this PR was just extend current existing parameter "increase font size" by more options (instead of YES/NO)

Why there are two accessibility settings (one core in user profile, second plugin), hard to say.

![Accessibility](https://i.imgur.com/If6uuDO.png)

In fact, if there will be not the core option, this PR does not make any sense more.

2020-04-29 14:18 UTC, carcam commented
We have discussed this at JAT and we think the option to reduce the font size is not needed. The font size is small enough so that the case of people with tunnel vision does not apply here. Also there is a browser mechanism that allows you to freely adjust the font size. Also after checking, this is not required by any success criterion as there is no such requirement in Functional Performance Criteria.

2020-04-29 14:24 UTC, PhocaCz commented
> We have discussed this at JAT and we think the option to reduce the font size is not needed. The font size is small enough so that the case of people with tunnel vision does not apply here. Also there is a browser mechanism that allows you to freely adjust the font size. Also after checking, this is not required by any success criterion as there is no such requirement in Functional Performance Criteria.

Does this mean, decreasing text size will even be removed from Accessibility plugin?

2020-04-29 16:42 UTC, brianteeman commented
> We have discussed this at JAT and we think the option to reduce the font size is not needed. The font size is small enough so that the case of people with tunnel vision does not apply here. Also there is a browser mechanism that allows you to freely adjust the font size. Also after checking, this is not required by any success criterion as there is no such requirement in Functional Performance Criteria.

The accessibility rule is that a user should be able to resize the text. Although it doesnt specifically state decrease in size in the techniques for satisfying the criteria it states a button to increase and decrease. In the additional document Accessibility Requirements for People with Low Vision it does explicitly state the need to reduce the text size.

> The font size is small enough so that the case of people with tunnel vision does not apply here

Wow - I didn't know we had medical experts on the JAT - thats an awesome improvement. Seriously I am sure in the cold light of day reading what you wrote again you will realise that was a _silly_ statement.

> there is a browser mechanism that allows you to freely adjust the font size

 A browser mechanism is not an accepted method for passing any criteria.

2020-04-29 20:42 UTC, richard67 commented
The technical issue mentioned by @C-Lodder also applies to the one font size which can be set right now without this PR, that it's a user setting which is wort nothing if a 3rd party template doesn't support it. This PR here doesn't change that, and it doesn't make anything worse in this aspect.

Regarding accessibility: I am not an accessibility expert, but I don't think that there are rules telling we have to use only a normal and a large size like now, but are not allowed to have more choices like this PR adds with a small and easy code change. And for me it is perfect for accessibility if that can be adjusted on user level. So to me this PR seems to be an improvement.

If there is anything wrong with accessibility settings on user level in J4, then it is wrong with and without this PR.

So I see no reason to block this PR with a discussion which leads far away from what this PR does.

2020-04-29 20:44 UTC, chmst commented
Decreasing font size is not required by WCAG, this is true.  And I surely will not decrease font sizes with my old eyes :).  

But - why do we name these settings "Personal settings". We could do here so many things, it must not be for disabled. So everyone could set font size as he/she likes and it does not matter if it is set due to disabilities or personal preferences.

2020-04-29 20:51 UTC, richard67 requested changes
Fix PHPCS

2020-04-29 20:51 UTC, richard67 commented on administrator/templates/atum/index.php
> +<html lang="<?php echo $this->language; ?>" dir="<?php echo $this->direction; ?>"<?php echo (int)$a11y_font != 100 ? ' class="a11y_font_'.(int)$a11y_font.'"' : ''; ?>>
```suggestion
<html lang="<?php echo $this->language; ?>" dir="<?php echo $this->direction; ?>"<?php echo (int) $a11y_font != 100 ? ' class="a11y_font_' . (int) $a11y_font . '"' : ''; ?>>
```

2020-04-29 21:07 UTC, PhocaCz commented
BTW the purpose of this PR/idea is to somehow improve the potential of one parameter. The parameter itself just sets the font size to 18px which is really absurd. If we already have such a parameter, why not use more values. Because parameters are here to allow different settings. Limiting them to only one value does not make sense.

2020-04-29 21:14 UTC, Quy commented on administrator/templates/atum/index.php
> +$a11y_font      = $app->getIdentity()->getParam('a11y_font', 100);
Cast to `int` here. Then you need to do it later 2 times.

2020-04-29 21:36 UTC, richard67 commented on administrator/templates/atum/index.php
> +$a11y_font      = $app->getIdentity()->getParam('a11y_font', 100);
I guess you mean "Then you **_don't_** need to do it later 2 times."

2020-04-29 21:38 UTC, Quy commented on administrator/templates/atum/index.php
> +$a11y_font      = $app->getIdentity()->getParam('a11y_font', 100);
Yes. Fingers fast than brain.

2020-04-29 22:23 UTC, brianteeman commented
> But - why don't we name these settings "Personal settings".

Removing the words accessibility is fine by me. But if we do that as we already have a tab called basic settings how about either calling it advanced settings or merging the fields into that tab

2020-04-29 22:28 UTC, brianteeman commented
> Limiting them to only one value does not make sense.

I have no idea why I originally wrote this feature with that font setting - there must have been some document I was following but I don't remember and now it doesn't seem logical

2020-04-30 09:17 UTC, PhocaCz commented
> I have no idea why I originally wrote this feature with that font setting - there must have been some document I was following but I don't remember and now it doesn't seem logical

So, if you are the author of the original parameter, you are the only one here who can say:
a) Yes, it can be extended because it does not break the original function
b) or No, it cannot be extended because it breaks the original function

:-)

2020-04-30 09:39 UTC, chmst commented
I like the idea of integrating the accessible settings into the basic settings. And removing the accessibility .. . Some people like monochrome - but not due to a disability. So this seems better "inclusive".

2020-04-30 09:46 UTC, richard67 commented on administrator/templates/atum/index.php
> +<html lang="<?php echo $this->language; ?>" dir="<?php echo $this->direction; ?>"<?php echo (int)$a11y_font != 100 ? ' class="a11y_font_'.(int)$a11y_font.'"' : ''; ?>>
@PhocaCz I'd really like to merge it as it is, but even if I was allowed to without tests, I couldn't because it fails the PHPCS test in drone. You should either implement my suggested changes to fix that, or even better implement @Quy 's suggestion below for the "(int)" type cast so you remove the cast here (which fill also fix CS error about missing space between the type cast and the variable), and ideally just adding a space before and after the concatenation dots as I suggested here.

2020-04-30 09:48 UTC, richard67 commented on administrator/templates/atum/index.php
> +$a11y_font      = $app->getIdentity()->getParam('a11y_font', 100);
@PhocaCz I agree with @Quy , one type cast here and then no two typecasts needed below in the lines referred to by my suggestion above. Just put a space between the type cast and the variable when implementing Quy's suggestion, then PHPCS will be happy, too.

2020-04-30 10:15 UTC, coolcat-creations commented
So how about having a Template style setting in the User Settings?

2020-05-08 18:42 UTC, SharkyKZ commented
There's already an option for that (only for backend though).

2020-05-08 18:47 UTC, SharkyKZ commented
If these options are kept, they'll have to be moved to Atum's accompanying plugin.

2020-05-08 18:58 UTC, brianteeman commented
What plugin?

2020-05-08 19:40 UTC, coolcat-creations commented
> If these options are kept, they'll have to be moved to Atum's accompanying plugin.

Yes you are right, so it would be good to make it more userfriendly to create a personal style and save it directly in the profile. Actually some less clicks than clicking on: system, template styles, copy style, set up, user profile, select style

2022-01-22 09:50 UTC, bembelimen commented
Hi @PhocaCz thank you for your idea.

As the branch is deleted and the approach should be a more comprehensive enhancement, I'll close it here.

But probably you could open a discussion here to get something going?

2022-01-22 09:50 UTC, closed without merging