Backport jQuery 3.5 security fixes
joomla/joomla-cms pull request #28948
Opened 2020-05-05 17:03 UTC by SniperSister

The recently released JQuery 3.5.x has fixed two XSS issues. As we can't upgrade to a newer jQuery version in 3.x for BC reasons, the security team suggest to manually patch our jQuery.

As this change might have unexpected b/c implications and the vulnerability already is public and well documented, I'm opening this ticket on the public tracker.

### Summary of Changes
Backported jQuery 3.5 security fixes.

### Testing Instructions
Apply patch, browse various parts of the site and make sure that no JS errors show up in the browser console.

2020-05-06 08:57 UTC, SniperSister commented
There's a potential breaking change in the handling of self-closing tags, see:
https://jquery.com/upgrade-guide/3.5/

2020-05-08 23:09 UTC, wilsonge commented
I assume backporting the associated jQuery Migrate fix is beyond us? Because if so we need to really scream about this in the release notes and ideally on social media to extension devs too

2020-05-09 06:18 UTC, SniperSister commented
If I understand the JQuery notes correctly, the backport of the compatibility layer re-introduces the issue.

2020-05-11 00:53 UTC, zero-24 commented
I have just navigated the backend with latest Chrome, Edge and IE11 and also the emulated IE9. Is there anything we should test here? Do we even use that function patched in core?

2020-05-11 13:05 UTC, SniperSister commented
> Do we even use that function patched in core?

That function is used everywhere because it's part of the DOM manipulation library

2020-05-22 07:43 UTC, SniperSister commented
@wilsonge I have updated the PR with the "pre-fix-behavior" backport that Drupal published

2020-05-22 08:30 UTC, zero-24 requested changes

2020-05-22 08:30 UTC, zero-24 commented on media/jui/js/jquery.js
> + * Modified by Joomla: Mitigate possible XSS vulnerability CVE-2020-11022 and CVE-2020-11023, CMS Issue; https://github.com/DanielRuf/snyk-js-jquery-565129
Should't we update this to the drupal soure?

2020-05-22 08:30 UTC, zero-24 commented on media/jui/js/jquery.js
> + * Modified by Joomla: Mitigate possible XSS vulnerability CVE-2020-11022 and CVE-2020-11023, CMS Issue; https://github.com/DanielRuf/snyk-js-jquery-565129
Or atleast add it somewhere.

2020-05-22 13:33 UTC, SniperSister commented on media/jui/js/jquery.js
> + * Modified by Joomla: Mitigate possible XSS vulnerability CVE-2020-11022 and CVE-2020-11023, CMS Issue; https://github.com/DanielRuf/snyk-js-jquery-565129
done

2020-05-23 18:28 UTC, zero-24 commented
I have tested this item :white_check_mark: successfully on 4be8cd72c3e8f34924b203876e433e9859fd3aee<br /><br />As mention in the Testing Instructions i have applied the patch, navigated the backend and have not noticed any error message form the browser console. Thanks @SniperSister <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28948">issues.joomla.org/tracker/joomla-cms/28948</a>.</sub>

2020-05-24 15:13 UTC, pmleconte commented
I have tested this item :white_check_mark: successfully on 4be8cd72c3e8f34924b203876e433e9859fd3aee<br /><br />Just tested it using Chrome. 

I did not see any difference front-end/back-end in browser console.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28948">issues.joomla.org/tracker/joomla-cms/28948</a>.</sub>

2020-05-24 15:26 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28948">issues.joomla.org/tracker/joomla-cms/28948</a>.</sub>

2020-05-25 08:09 UTC, HLeithner commented
Awesome job thanks

2020-05-25 08:09 UTC, merged

2020-06-04 16:15 UTC, Webmaster-2020 commented
Bonjour tout le monde,

Est ce que c'est normale de trouver l'ancienne version de JQuery même après la mise à jour de JOOmla 3.9.19 ?

Merci d'avance

2020-06-04 16:27 UTC, conseilgouz commented
Bonjour,

En anglais SVP. Messages should be written in english.
Is it normal to still have old version of jQuery after 3.9.19 update ?

The answer is Yes. If you take a look at the header of media/jui/js/jquery.js file, you'll find a comment talking about CVE-2020-11022 which is "the patch". 

Jquery version is now v1.12.4-joomla.

2020-06-05 07:43 UTC, Webmaster-2020 commented
@pmleconte 
thank you very much for your answer.