[4.0] Option to use a menu item for privacy policy.
joomla/joomla-cms pull request #29024
Opened 2020-05-10 13:00 UTC by Harmageddon

This PR is based on a feature request brought up by user fire67 on the German forum: https://forum.joomla.de/thread/11738-plugin-inhalt-datenschutzerkl%C3%A4rung/

Apparently, some page builders like SP PageBuilder don't register their "articles" as real Joomla! articles. If you create your privacy policy using such a page builder (might apply to some CCK extensions, too), you can't choose it in the privacy consent plugin, because there, only articles are available.

### Summary of Changes
This PR adds a menu item parameter to plg_system_privacyconsent that can be used instead of the article parameter, and a parameter to choose between the two.

### Testing Instructions
At least one test on a multilingual site would be very welcome. I replicated the mechanism that chooses the associated article in the respective language, for menu items. It works on my small local setup. But as I'm no expert in multilingual sites, I'd be happy if someone with more expertise could check if it works as expected.

1. Enable the Plugin "System - Privacy Consent".
2. Select an article for your privacy policy.
3. In frontend, navigate to the registration form and make sure that the modal box for the privacy policy works as expected (in all languages).
4. Apply this PR.
5. Make sure everything still works like before.
6. In the plugin config, switch "Privacy Type" to "Menu Item" and select a menu item. To make sure that there is a difference, maybe select a category blog or something else, but not the menu item for the privacy article you used before.
7. Repeat step 3.
8. Switch the type back to "Article" and make sure it works as before.

### Documentation Changes Required
Should be documented at https://docs.joomla.org/J3.x:Privacy (or the J4 version of that?).

### Additional Notes
I noticed that the full `$article` object including link, alias, id, catid and language, is passed to the layout, but only the link is used there (at least in core). Should I do the same for the menu item, so overrides could access further information or leave it as it is?

2020-05-10 17:36 UTC, Harmageddon commented
Apparently, this is not the only privacy consent plugin. I'm going to provide an analogous implementation for the content plugin for contact forms tomorrow.
Thanks to @ChristineWk for pointing me there. ;-)

2020-05-11 16:30 UTC, Harmageddon commented
Updated with the according changes to Content - Confirm Consent. 

Stupid question here: Why do we have two plugins for almost the same thing, including two similar, but still different implementations for the form field that displays the modal?

2020-05-11 19:22 UTC, Quy commented on plugins/content/confirmconsent/confirmconsent.xml
> +				>
```suggestion
					>
```

2020-05-11 20:11 UTC, SharkyKZ commented on plugins/content/confirmconsent/confirmconsent.xml
> +					filter="options"
```suggestion
					validate="options"
```

2020-05-15 13:10 UTC, Quy commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +	 * @return  integer
```suggestion
	 * @return  string
```

2020-05-15 13:12 UTC, Quy commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +	 * current language, ID of the associated menu item will be returned.
```suggestion
	 * current language, URL of the associated menu item will be returned.
```

2020-05-15 14:52 UTC, Harmageddon commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +	 * current language, ID of the associated menu item will be returned.
Good spot, thank you!

2020-05-15 20:17 UTC, ChristineWk commented
@Harmageddon 
Some test-results:

a) System - Privacy Consent (registration form) > there is no switch to "Menu Item".

b) Content - Confirm Consent (contact form) > successful. See screenshots

![content_confirm_consent](https://user-images.githubusercontent.com/15275917/82092487-ace60400-96f9-11ea-8e9e-9525e5dd05b3.png)

![content_confirm_consent_menue](https://user-images.githubusercontent.com/15275917/82092518-ba02f300-96f9-11ea-909f-e26b7b154ff3.JPG)

2020-05-15 20:53 UTC, ChristineWk commented
Now I got a) also. It wasn't there before. 

![system_privacy_consent_frontend](https://user-images.githubusercontent.com/15275917/82095122-b32aaf00-96fe-11ea-8093-dd68b17b9f5e.JPG)

2020-05-15 21:13 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on ea4abe91e8248d3de5f5f48610ef15fff40614e3<br /><br />but not tested multilingual site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-05-21 15:35 UTC, carcam commented
I have tested this item :white_check_mark: successfully on ea4abe91e8248d3de5f5f48610ef15fff40614e3<br /><br />I have tetsed this successfully:

1. Added German language to the site
2. Added German menu item for blog: "Das Blog" associated with "Blog" menu item
3. Enable plugin "privacy - consent" and changed to "Privacy Type -> menu item"
4. Set Privacy Menu Item to "Blog" (English menu item)
5. When checked the privacy consent link I see the menu item for English blog when in English language and the link for Das Blog when in German language<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-05-21 15:37 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-05-23 22:24 UTC, zero-24 requested changes

2020-05-23 22:24 UTC, zero-24 commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +	 * @since  4.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2020-05-23 22:24 UTC, zero-24 commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +	 * @since  4.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2020-05-23 22:24 UTC, zero-24 commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +	 * @since   4.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-05-23 22:24 UTC, zero-24 commented on plugins/system/privacyconsent/privacyconsent.php
> +	 * @since   4.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-05-24 13:20 UTC, Harmageddon commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +	 * @since  4.0
Right, sorry. Forgot about this again. Thank you! :-)

2020-05-24 13:25 UTC, richard67 commented
Previous test results are still valid, because the change after the test was only in doc blocks. I've restored the test results in the tracker so the count there and here is correct again.

2020-05-24 13:25 UTC, richard67 commented
RTC status is also still valid, see my previous comment.

2020-05-27 03:42 UTC, Quy commented on administrator/language/en-GB/plg_content_confirmconsent.ini
> +PLG_CONTENT_CONFIRMCONSENT_FIELD_MENU_ITEM_DESC="Select the privacy item that leads to the privacy policy."
Remove description as the label is self explanatory.

2020-05-27 03:42 UTC, Quy commented on administrator/language/en-GB/plg_content_confirmconsent.ini
> +PLG_CONTENT_CONFIRMCONSENT_FIELD_TYPE_DESC="Select whether the privacy policy is an article or a menu item."
Remove description as the label and options are self explanatory.

2020-05-30 11:28 UTC, Harmageddon commented on administrator/language/en-GB/plg_content_confirmconsent.ini
> +PLG_CONTENT_CONFIRMCONSENT_FIELD_TYPE_DESC="Select whether the privacy policy is an article or a menu item."
I'm a bit hesitant to merge this, because things that seem self-explanatory to us as experienced users or developers are often not self-explanatory to users. Maybe there is a better description than what I provided, but I don't like options without any explanation.

2020-05-30 11:58 UTC, wilsonge commented on administrator/language/en-GB/plg_content_confirmconsent.ini
> +PLG_CONTENT_CONFIRMCONSENT_FIELD_TYPE_DESC="Select whether the privacy policy is an article or a menu item."
Well what wording here gives new insight? Your labels already specify menu item and article. The field label specifies it's relating to the privacy policy. If this gives extra information it's fine to have a description - but right now I don't see this providing extra value. And if it's doesn't produce value then it's clutter which will confuse the user

2020-06-07 11:05 UTC, Harmageddon commented on administrator/language/en-GB/plg_content_confirmconsent.ini
> +PLG_CONTENT_CONFIRMCONSENT_FIELD_TYPE_DESC="Select whether the privacy policy is an article or a menu item."
Alright, as you prefer.

2020-06-07 12:39 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on ae56966b6887a9569d09ea5ba4113deafed6415f<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-06-10 10:54 UTC, ceford commented
I have tested this item :red_circle: unsuccessfully on ae56966b6887a9569d09ea5ba4113deafed6415f<br /><br />I am using J4 Beta 2-Dev nightly build from last night. I installed the multi-lingual test data and created a Privacy Policy article in English, French and German. In the login form I see the Privacy box and Terms and Conditions box. However, with the patch applied with the Patch Tester the Privacy Plugin doe not have a switch and I can't find anything in the Contact configuration. So it does nothing. But it does not break anything either. How do I check whether the Patch Tester is actually working?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-06-10 12:00 UTC, Harmageddon commented
@ceford Can you post a screenshot of the plugin configuration? I just tested it with the current nightly and patchtester 4.0.0 RC2 and it works for me. Which plugin did you edit?

2020-06-10 12:31 UTC, ceford commented
This is the only item I can find that matches the Test Instructions:

![image](https://user-images.githubusercontent.com/1560390/84267567-2c5ecb80-ab1e-11ea-9859-1b1d4b7a1945.png)

In the front end there is no modal box for the Privacy Policy. If I click the menu item I get the Article. I guess I must be doing something wrong. Is there a step missing from the instructions?

2020-06-10 12:32 UTC, SharkyKZ commented
@ceford the plugin to configure is `System - Privacy Consent`. It's disabled by default.

2020-06-10 12:35 UTC, Harmageddon commented
I see. You have to check the Plugins "Content - Confirm Consent" for the contact form, and "System - Privacy Consent" for the registration form. It's a bit confusing, I had the same difficulties finding the differences.

2020-06-10 13:15 UTC, ceford commented
I had the Content - Confirm Consent enabled but neglected to select the Article option. So now I have this:

![image](https://user-images.githubusercontent.com/1560390/84271205-bc534400-ab23-11ea-8f88-56b12dd75c9e.png)
 But still nothing to select in the Privacy - Consents plugin and still no sign of a modal in the front end. Which has this at the foot of the Registration form:

![image](https://user-images.githubusercontent.com/1560390/84271628-40a5c700-ab24-11ea-9da2-6da6779b9026.png)

I have the Privacy Policy article in English, French and German as Associations. Is the modal present in J4?

2020-06-10 13:18 UTC, Harmageddon commented
@ceford For the registration form, you have to look at "System - Privacy Consent" **without an S** at the end. As I mentioned above, "Content - Confirm Consent" is for the contact form (i.e. if you have a menu item of type Single Contact with a form).

2020-06-10 13:44 UTC, ceford commented
Argh! I did not notice the **Privacy Policy** just above **I agree** and **No** is a link. Tired old eyes? Or poor accessibility design?

2020-06-10 13:46 UTC, richard67 commented
I'd say poor accessibility design ;-)

2020-06-10 14:34 UTC, ceford commented
I can confirm that this patch works with two side effects:

The modal body needs some padding. 

In a multilingual site, if the System - Privacy Consent is set to an Article in English and without associations in French and German, then in either of those two languages the modal box is a Search form:
![image](https://user-images.githubusercontent.com/1560390/84280385-20c7d080-ab2f-11ea-8aac-f4bf53e69a2d.png)
I guess fixing that may be lilly guilding.

I can take care of the documentation update - right now!

2020-06-12 08:27 UTC, Harmageddon commented
Good spot! I'll try to look into the situation when there is no equivalent menu item for the language on the weekend. Please don't merge this PR before. 
The padding thing is something I noticed, too, but needs to be fixed in another PR.

2020-06-12 11:14 UTC, richard67 commented
> Good spot! I'll try to look into the situation when there is no equivalent menu item for the language on the weekend. Please don't merge this PR before.

Ok, will remove RTC to avoid the merge.

2020-06-12 11:16 UTC, richard67 commented
Removing RTC since the author wants to add some correction/enhancement, see his comment above: [https://github.com/joomla/joomla-cms/pull/29024#issuecomment-643145085](https://github.com/joomla/joomla-cms/pull/29024#issuecomment-643145085 "https://github.com/joomla/joomla-cms/pull/29024#issuecomment-643145085")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-06-13 13:50 UTC, Harmageddon commented
If there is no associated menu item, the link should now fall back to the one selected in the plugin configuration, like it is for the article option.
@ceford Can you please test if it works for you? Thank you again for finding this error! :-)

2020-06-13 16:54 UTC, ceford commented
I reloaded the Patch Tester Data and applied the patch. A wee box below the View buttons says **Applied Commit SHA: 1c1c740e17**. I see no change from the previous incarnation. 

With all languages pointing to associated articles in different languages I noticed that the modal box does not contain the article content:

![image](https://user-images.githubusercontent.com/1560390/84574426-49093680-ad9e-11ea-869a-e1b4e7ce828b.png)

With the English article pointing to something not associated I get a Search form in the French and German modal boxes.

2020-06-14 14:32 UTC, Harmageddon commented
> I reloaded the Patch Tester Data and applied the patch. A wee box below the View buttons says **Applied Commit SHA: [1c1c740](https://github.com/joomla/joomla-cms/commit/1c1c740e179c167f49bf473ecefecbc2eef44b94)**. I see no change from the previous incarnation.

That's a commit from a different PR (#29592). Is it possible that you mixed these up / re-installed that one instead of this here? For this PR here, it should give you "Applied Commit SHA: e56f4753cb".

> With all languages pointing to associated articles in different languages I noticed that the modal box does not contain the article content:

As far as I see, this is not a result of this PR, but was like this already before. So it should be fixed in a different PR as well, because it's another bug unrelated to this feature here.

2020-06-14 20:02 UTC, ceford commented
I reloaded patch tester data again and I now seem to have the correct patch:  Applied Commit SHA: e56f4753cb. It works in all languages when an article or menu item are associated in all languages. The problem I see is when the privacy article or menu does not exist in all languages. I have experience of this with a custom component on a J3 site - there if a none-English item does not exist we display the English version because that is deemed the legal version.

Where I previously said the modal box does not contain the article content, as illustrated on my previous screen shot, I did not notice that the modal box has a vertical scroll - the content is all there. I think the modal box needs to be a tad longer. And where I previously said it contains a search from if the none-English version is missing, it actually contains page content, including left and right side bars:
![image](https://user-images.githubusercontent.com/1560390/84602716-492e3280-ae81-11ea-92c5-4e0375a266c7.png)
I can think of instances where an article/menu item is created in several languages and another language is added later. Is there a technical solution? Or do we rely on Administrator education?

2020-06-15 16:54 UTC, Harmageddon commented
There should definitely be a solution for this. I'm just wondering because I intended to fix this with e56f475. So I don't understand why it's still the same like before on your site. 

My approach is: I create three languages, en-GB, de-DE and fr-FR. Create a menu item in two of them (en-GB and de-DE), but not in fr-FR. In the plugin options, I select one of these two menu items. Now when I go to a registration or contact form, if I am in de-DE or en-GB, it shows me the respective page inside the modal. If I'm on fr-FR, the modal opens the menu item I selected in the plugin (which will be en-GB or de-DE, depending which one I selected there).

Is this at any point different to your setting? Can you maybe check if the patch has been applied correctly, i.e. if for example the file `plugins/system/privacyconsent/src/Field/PrivacyField.php` contains the following on lines 106f: 

https://github.com/joomla/joomla-cms/blob/e56f4753cbf207924f87f1804f5e60043cb138b0/plugins/system/privacyconsent/src/Field/PrivacyField.php#L106-L118

Or maybe revert the patch and apply it again?

2020-06-15 19:32 UTC, ceford commented
I followed your instructions and it worked as you described. **Except** - if the French menu item is unpublished rather than trashed and deleted. In which case - the French version displays a French Not Found page.

2020-06-15 19:40 UTC, Harmageddon commented
Ohhh... I only tested with the french item not existing. But I can imagine that trashed/unpublished might break this. Will look into it tomorrow. Thank you!

2020-06-17 17:22 UTC, Harmageddon commented
So it works if the item doesn't exist at all / has been properly deleted (also removed from trash)?

I reviewed this edge case now. So, to summarize, in this case, you have three menu items for three languages:
- de-DE (published)
- en-GB (published)
- fr-FR (unpublished or trashed)
All of them are associated to each other.

I see no simple fix to this besides doing another query on the menu items just to avoid this situation. I'm not sure if this situation is wanted in any scenario. It will give you problems on several other levels. I just tested this situation and for example, in the language switcher module, all three flags appear, but the french one falls back to the home page instead of the unpublished menu item. So as far as I see, if you have associated menu items, they should all be published (or restricted on base of user groups, but this wouldn't make much sense either for a privacy policy).

So I'm not in big favor of adding a database query that will run without any effect for all pages besides very few that are oddly configured.

2020-06-29 14:00 UTC, Harmageddon commented
@ceford Could you clarify if I understood the situation correctly in my comment above or if I missed something?

2020-06-29 17:16 UTC, ceford commented
I tried another test to remind myself of the issue. Right now, with the patch applied, and with a de/en/fr switcher, if I select a menu item that points to an Article in English for which no translations exist, the Privacy Policy link invokes the modal dialog with Page not Found content in French or German, as in my previous illustration. I think this is a new test.

In my previous test I had a Privacy Policy in English associated with one in German and French. But I only had menu items for the English and German versions. That caused the the French Privacy dialog to display the English privacy content, which is good.

If fixing this problem is not practicable we will need to rely on education / documentation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-06-29 17:19 UTC, Harmageddon commented
Thank you for your response! To make sure, so I can reproduce your test case: Is the language for the menu item set to English, too? Or to all languages?

So:
* Menu item: English, not associated to anything
* Article: English, not associated to anything

Or how is the situation?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-06-29 17:38 UTC, ceford commented
The language of the menu item is English and has de-DE as an association.

2020-06-29 17:44 UTC, Harmageddon commented
And where is the de-DE menu item pointing to? A german article?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-06-29 20:01 UTC, ceford commented
The de-DE menu item is pointing the privacy article in German associated with the privacy article in English.

2020-06-29 20:48 UTC, Harmageddon commented
I'm not sure if I understand you correctly. You said:

> if I select a menu item that points to an Article in English for which no translations exist, the Privacy Policy link invokes the modal dialog with Page not Found content in French or German, as in my previous illustration. I think this is a new test.

So only an article and a menu item in English? But now you have both in German as well? And does it work or not?

2020-06-30 03:39 UTC, ceford commented
This is a concise summary of my tests. Hope it is clearer.

Set up - Associated Articles - Privacy Policy == Privacy Policy in French == Privacy Policy in German
Set up - Associated menu items - Privacy Policy == Privacy Policy in German
Set up - SomeOtherArticle and SomeOtherArticleMenuItem
Apply Patch
Test 1:
Set - Privacy Type - Menu Item - Privacy Policy
Select language and then Privacy Policy link:
English - Privacy Policy in English
German - Privacy Policy in German
French - Privacy Policy in English
Result - Good - what I want / expect
Test 2:
Set - Privacy Type - Menu Item - SomeOtherArticleMenuItem (no French or German Association)
Select language and then Privacy Policy link:
English - SomeOtherArticle content
French - Page not Found content in French (as illustrated previously)
German - Page not Found content in German
Result - Bad - Should be SomeOtherArticle content in English OR some simple error message.

2020-06-30 16:49 UTC, Harmageddon commented
Test 1 is exactly what I would expect and how I wanted this to work: If there is no entry in the according language, fall back to that one selected in the plugin.

For Test 2, I'm still struggling to replicate. I have: 
- Article "SomeOtherArticle" (en), not associated to anything
- Menu Item "SomeOtherArticleMenuItem" (en), not associated to anything

This leads me to the English article in all three languages.

The only case when I get a 404 there is, when the menu item "SomeOtherArticleMenuItem" is set to all languages, not to English. But if I see it correctly, this is not a valid configuration, as I get a 404 then when clicking on the menu item in a normal menu as well.

2020-06-30 18:53 UTC, ceford commented
I did have the menu item SomeOtherArticleMenuItem set to All. Setting that to English I get the English Privacy message in all languages as you described. And the direct menu link only appears in the English page. Back to All languages and the direct menu link leads to the Not Found page in French and German. The Article itself is set to English. 

So this is really a problem of making sure the Article and Menu Item have compatible language settings and is nothing to do with Privacy Policy.

2020-07-01 09:50 UTC, Harmageddon commented
@ceford Thank you for the clarification! So is this a successful test from your side or do you see any remaining issues with this PR?

2020-07-01 11:08 UTC, ceford commented
Yes - Pass.

2020-07-01 11:41 UTC, richard67 commented
@ceford Does your previous mean you have tested this PR completely with success? If so, please mark the test result again at the issue tracker because your previous result has been reset with the last commit.

2020-07-01 11:42 UTC, richard67 commented
@zero-24 GH still shows changes requested by your review, but the review comments have been solved. Maybe you can just pass again a neutral review to reset this?

2020-07-01 11:59 UTC, zero-24 commented
Should be gone now

2020-07-01 12:01 UTC, richard67 commented
@zero-24 No, is still there in the box at the bottom.

2020-07-01 12:10 UTC, zero-24 approved these changes
Should be gone now

2020-07-01 16:30 UTC, ceford commented
I have tested this item :red_circle: unsuccessfully on e56f4753cbf207924f87f1804f5e60043cb138b0<br /><br />I selected a menu item for the Privacy Policy and that worked fine. I went back and selected Privacy Type: Article; Privacy Article: Select brought up a list to select from. But the links are dead and I see javascript:void() at the bottom left of the screen. I am now on Beta-3 Dev. Is there a Javascript issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-07-02 09:59 UTC, ChristineWk commented
https://github.com/joomla/joomla-cms/issues/29897<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-07-02 10:44 UTC, Harmageddon commented
The bug you mentioned has been fixed in #29860, merged a few minutes ago. As mentioned there, it was introduced in #29464, which has been merged into 4.0-dev just before the release of beta2. So the bug came with beta2 and was fixed after the release of beta2. I'd therefore ask you to test with beta1 or a current version (nightly starting from **tomorrow, Fr 03 July** or git from right now).

Thank you @ChristineWk for pointing this out!

2020-07-03 09:06 UTC, ceford commented
If I pick an article in English that has no associations in French and German then I get that Article in English in the Privacy Policy dialog in all three languages. Good!

If I pick the menu item that points to that article, also without associations in French and German, then I only get that Article in English in the Privacy Policy dialog. In French and German I get the dialog with a 404 not found page. And it is a big page with all of the modules in left and right columns. I accept that that could be left as a User education problem but it would be better if there were a technical solution.

Otherwise the normal behaviour works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-07-03 09:15 UTC, Harmageddon commented
Like I mentioned above, the menu item should be set to English in your second case as well. Is this the case?

2020-07-03 09:49 UTC, ceford commented
Yes, it works properly with the menu item set to English.

One more question: why is this plugin in the System group instead of the Privacy group? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-07-03 10:34 UTC, ceford commented
I have tested this item :white_check_mark: successfully on e56f4753cbf207924f87f1804f5e60043cb138b0<br /><br />With the small proviso I mentioned previously I think this is OK. I have documented the changes in the Help screen:

https://docs.joomla.org/Chunk4x:Extensions_Plugin_Manager_Edit_System_Group#System_-_Privacy_Consent

And there drawn attention to multilingual associations.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-07-03 11:50 UTC, Harmageddon commented
Thank you for your tests and the effort on the documentation! :-)

2020-07-06 11:25 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on dc39f39603590978236bb5b68587fab028376dbd<br /><br />Version 4.0.0-beta3-dev Jul6th2020 new Installation<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-07-06 18:42 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on dc39f39603590978236bb5b68587fab028376dbd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-07-06 18:42 UTC, jwaisner commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29024">issues.joomla.org/tracker/joomla-cms/29024</a>.</sub>

2020-09-22 19:24 UTC, richard67 commented
@wilsonge Anything which keeps this RTC PR from being merged? Does it count as "new feauture" and so has to go into 4.1?

2020-09-22 20:20 UTC, Quy commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +			'privacyType' => (integer) $this->privacyType,
integer or string?

2020-09-23 09:35 UTC, Harmageddon commented on plugins/content/confirmconsent/src/Field/ConsentBoxField.php
> +			'privacyType' => (integer) $this->privacyType,
You're absolutely right, thank you!

2020-10-16 11:27 UTC, merged