[com_content] Undefined property with read more when params are missing
joomla/joomla-cms pull request #29061
Opened 2020-05-14 07:01 UTC by SharkyKZ

### Summary of Changes

Fixes a rare case of undefined property.
Removes unreachable elseif/else conditions.

### Testing Instructions

Create an article with intro/full text and registered access level. In `#__content` table set article `attribs` to empty JSON object: `{}`.
View the article in frontend.

### Expected result

No notices

### Actual result

Notice:

>Undefined property: stdClass::$alternative_readmore in components\com_content\views\article\tmpl\default.php on line 147

### Documentation Changes Required

No.

2020-06-01 08:23 UTC, bonzani commented
I have tested this item :white_check_mark: successfully on 5445737df1783806cac624fd167031c2238d8e20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29061">issues.joomla.org/tracker/joomla-cms/29061</a>.</sub>

2020-06-04 21:41 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 5445737df1783806cac624fd167031c2238d8e20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29061">issues.joomla.org/tracker/joomla-cms/29061</a>.</sub>

2020-06-04 21:42 UTC, jwaisner commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29061">issues.joomla.org/tracker/joomla-cms/29061</a>.</sub>

2020-06-28 19:07 UTC, zero-24 requested changes
As mention inline we might better check for empty?

2020-06-28 19:07 UTC, zero-24 commented on components/com_content/views/article/tmpl/default.php
> +			<?php if ($params->get('alternative_readmore', '') === '') : ?>
Better check for empty here?

2020-06-29 05:18 UTC, SharkyKZ commented on components/com_content/views/article/tmpl/default.php
> +			<?php if ($params->get('alternative_readmore', '') === '') : ?>
Why?

2020-06-29 05:31 UTC, zero-24 commented on components/com_content/views/article/tmpl/default.php
> +			<?php if ($params->get('alternative_readmore', '') === '') : ?>
As we are checkinf for an empty string right?

2020-06-29 05:45 UTC, SharkyKZ commented on components/com_content/views/article/tmpl/default.php
> +			<?php if ($params->get('alternative_readmore', '') === '') : ?>
Right. `empty()` generally should not be used for checking content. `0` is a valid string in this case but `empty()` wouldn't allow it.

2020-06-29 06:00 UTC, zero-24 commented on components/com_content/views/article/tmpl/default.php
> +			<?php if ($params->get('alternative_readmore', '') === '') : ?>
Right makes sense

2020-06-29 06:00 UTC, merged

2020-06-29 06:00 UTC, zero-24 commented
Merged