[4.0] [com_finder] Disable search statistics by default
joomla/joomla-cms pull request #29164
Opened 2020-05-20 07:21 UTC by SharkyKZ

### Summary of Changes

In the administrator part of Smart Search, search statistics option appears to be disabled but in frontend statistics are still gathered. This changes default value of statistics option in frontend to disabled.

### Testing Instructions

In backend go to Components -> Smart Search -> Statistics.
Notice the warning:

>Gathering of statistics is disabled. Enable it in the Options.

Go to frontend. Perform a search using Smart Search.
Go back to statistics page.

### Expected result

No entries logged.

### Actual result

Search entry logged.

### Documentation Changes Required

No.

2020-05-20 13:55 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 3b275519f3c0a8008754b65f1e27eb5d184d0592<br /><br />Tested successfully in Nightly Build of May 20.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29164">issues.joomla.org/tracker/joomla-cms/29164</a>.</sub>

2020-05-20 16:04 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 3b275519f3c0a8008754b65f1e27eb5d184d0592<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29164">issues.joomla.org/tracker/joomla-cms/29164</a>.</sub>

2020-05-20 16:04 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29164">issues.joomla.org/tracker/joomla-cms/29164</a>.</sub>

2020-05-21 16:24 UTC, richard67 commented
@SharkyKZ Could you update the branch of this PR to latest 4.0-dev of the CMS? It needs to do that in order to make drone pass, and this is needed for merging (except someone merges who has permission to force merge, which I haven't).

2020-05-23 22:19 UTC, zero-24 requested changes

2020-05-23 22:19 UTC, zero-24 commented on components/com_finder/src/Helper/FinderHelper.php
> +		$enable_log_searches = ComponentHelper::getParams('com_finder')->get('gather_search_statistics', 0);
should't we update the variable names than too?

2020-05-24 09:26 UTC, SharkyKZ commented on components/com_finder/src/Helper/FinderHelper.php
> +		$enable_log_searches = ComponentHelper::getParams('com_finder')->get('gather_search_statistics', 0);
Makes no difference. But this one can be removed.

2020-05-24 09:31 UTC, zero-24 commented
Merging thanks @SharkyKZ

2020-05-24 09:31 UTC, merged