[4.0] Refactoring Content Versioning
joomla/joomla-cms pull request #29217
Opened 2020-05-25 20:38 UTC by Hackwar

This is a redo of #23432.

The content versioning in Joomla is a rather obscure feature. Parts of it run/are available for every extension that uses the base classes, others you have to specifically add to your code. There isn't really a way to not use that system. It is also tied into the UCM system and is unnecessarily complex. This PR tries to improve on that in a few ways. This does not claim to be the perfect solution (there is a lot of stuff to do in the future), but it is hopefully a step around the backwards compatibility issues that we would have if we want to work on this in 4.1 or later.

### What does this PR do?
- Decoupling of the versioning system from the UCM.
- Simplifying code
- Moving all versioning code to interfaces and traits
- Instead of using magic fields/attributes, the support of versioning is clearly signaled by interfaces
- Moved all the necessary code to a proper subfolder...

### What did I do?
I changed the name of the history table from `#__ucm_history` to `#__history`, dropped the `ucm_type_id` column and changed the `ucm_item_id` column to a varchar and changed how it is used. That column now contains keys of the type `<component>.<type>.<id>`, which is also what is used everywhere to identify the content item to edit. By this, you don't need to read the content types table first to get the right item type ID. But more importantly for me, you can now look into the table and read what type of data a row is. I consider that a better solution for debugging and better than a composite key out of 2 columns.

### Status
This PR is ready for testing. However, while migrating this code to the current 4.0-dev, several bugs in the 4.0-dev codebase have surfaced, which need to be fixed beforehand. I will report back here regarding those bugs.

### How to test
1. Apply the PR
2. Apply the database changes of this PR
3. Go to a core component that supports versioning, com_content for example, and create a content item. Save the item and edit it again, changing something. Saving again should create a new version. Editing again and saving without any changes shouldn't create a new version.
4. In the edit view, click on the versions toolbar button and see that 2 versions have been created (Notice that the edit without a change does not show up here)
5. Compare 2 versions and restore an older one. All of this should work.

2020-05-25 21:08 UTC, SharkyKZ commented on plugins/behaviour/versionable/versionable.php
> +		if (isset($jform['version_note']))
Any way to hardcode control group and fields? This like the opposite of:

>Instead of using magic fields/attributes, the support of versioning is clearly signaled by interfaces

2020-05-25 21:10 UTC, SharkyKZ commented on plugins/behaviour/versionable/versionable.php
> +		if (!(isset($aliasParts[0]) && ComponentHelper::getParams($aliasParts[0])->get('save_history', 0)))
`$aliasParts[0]` is never `null`, but it can be empty string. The check for `save_history` should be reversed?

2020-05-25 21:29 UTC, wilsonge commented on plugins/behaviour/versionable/versionable.php
> +		$input = Factory::getApplication()->input;
```suggestion
		$input = $this->app->input;
```

2020-05-25 21:33 UTC, Hackwar commented on plugins/behaviour/versionable/versionable.php
> +		$input = Factory::getApplication()->input;
The plugin doesn't have an $app attribute (yet).

2020-05-25 21:35 UTC, Hackwar commented on plugins/behaviour/versionable/versionable.php
> +		if (!(isset($aliasParts[0]) && ComponentHelper::getParams($aliasParts[0])->get('save_history', 0)))
I expect a developer to make sure that an object that implements the interface that the method returns the right data... Or is that asking to much?

save_history in 3.x is off by default. Should we enable this by default?

2020-05-25 21:36 UTC, Hackwar commented on plugins/behaviour/versionable/versionable.php
> +		if (isset($jform['version_note']))
I've taken a lot of existing code and didn't rewrite everything. If you have a better solution, I'm all ears.

2020-05-25 21:40 UTC, wilsonge commented on plugins/behaviour/versionable/versionable.php
> +		if (!(isset($aliasParts[0]) && ComponentHelper::getParams($aliasParts[0])->get('save_history', 0)))
I'd add the sanity check just to be safe. I'd never trust anyone not to do something stupid :D

2020-05-25 21:41 UTC, wilsonge commented on plugins/behaviour/versionable/versionable.php
> +		if (!(isset($aliasParts[0]) && ComponentHelper::getParams($aliasParts[0])->get('save_history', 0)))
I also wouldn't enable by default.

2020-05-25 21:49 UTC, brianteeman commented on plugins/behaviour/versionable/versionable.php
> +		if (!(isset($aliasParts[0]) && ComponentHelper::getParams($aliasParts[0])->get('save_history', 0)))
As long as there is also a sensible maximum versions then why not enable by default?

2020-05-25 21:51 UTC, SharkyKZ commented on plugins/behaviour/versionable/versionable.php
> +		if (!(isset($aliasParts[0]) && ComponentHelper::getParams($aliasParts[0])->get('save_history', 0)))
The logic should be reversed like this:

```suggestion
		if ($aliasParts[0] === '' || !ComponentHelper::getParams($aliasParts[0])->get('save_history', 0)))
```

2020-05-25 21:58 UTC, SharkyKZ commented on plugins/behaviour/versionable/versionable.php
> +		if (isset($jform['version_note']))
Not at the moment. But would be great to stop relying on input. This breaks when editing items programmatically.

2020-05-25 23:28 UTC, wilsonge commented on plugins/behaviour/versionable/versionable.php
> +		if (isset($jform['version_note']))
Ahh this is a good point. By now having this in a plugin is it going to cause issues with the API?

2020-05-29 07:01 UTC, alikon requested changes

2020-05-29 07:01 UTC, alikon commented on libraries/src/Table/ContentHistory.php
> +			->bind(':item_id', $itemId, ParameterType::INTEGER)
`item_id` is declared as a varchar in the ` '#__history'` table

2020-05-29 07:01 UTC, alikon commented on libraries/src/Versioning/Versioning.php
> +		$query->select($db->quoteName('h.version_note') . ',' . $db->quoteName('h.save_date') . ',' . $db->quoteName('u.name'))
please use prepared statements

2020-05-29 07:01 UTC, alikon commented on libraries/src/Versioning/Versioning.php
> +		$query = $db->getQuery(true);
please use prepared statements

2020-05-29 11:03 UTC, Hackwar commented on plugins/behaviour/versionable/versionable.php
> +		if (isset($jform['version_note']))
Considering the time pressure, can we fix this in another PR and merge this one for the time being?

2020-05-29 11:36 UTC, Hackwar commented
All fixed. Can we merge this now? Given the current time pressure. ;-)

2020-05-29 11:36 UTC, HLeithner commented on libraries/src/Versioning/Versioning.php
>  			->from($db->quoteName('#__history') . ' AS h ')
```suggestion
			->from($db->quoteName('#__history', 'h'))
```

2020-05-29 11:36 UTC, HLeithner commented on libraries/src/Versioning/Versioning.php
>  			->leftJoin($db->quoteName('#__users') . ' AS u ON ' . $db->quoteName('u.id') . ' = ' . $db->quoteName('h.editor_user_id'))
```suggestion
			->from($db->quoteName('#__history') . ' AS h ')
			->leftJoin($db->quoteName('#__users', 'u'), $db->quoteName('u.id') . ' = ' . $db->quoteName('h.editor_user_id'))
```
I think that's the proper syntax

2020-05-29 13:17 UTC, wilsonge commented on libraries/src/Versioning/Versioning.php
>  			->leftJoin($db->quoteName('#__users') . ' AS u ON ' . $db->quoteName('u.id') . ' = ' . $db->quoteName('h.editor_user_id'))
Your suggestion now conflicts xD can you make it again

2020-05-29 13:21 UTC, HLeithner commented on libraries/src/Versioning/Versioning.php
>  			->leftJoin($db->quoteName('#__users') . ' AS u ON ' . $db->quoteName('u.id') . ' = ' . $db->quoteName('h.editor_user_id'))
```suggestion
			->leftJoin($db->quoteName('#__users', 'u'), $db->quoteName('u.id') . ' = ' . $db->quoteName('h.editor_user_id'))
```

2020-05-29 23:40 UTC, merged

2020-05-29 23:40 UTC, wilsonge commented
Thanks!