[4.0] Add support for TinyMCE content_css
joomla/joomla-cms pull request #29257
Opened 2020-05-29 10:56 UTC by C-Lodder

### Summary of Changes

TinyMCE has the ability to set the editor theme, however there are 2 parts to this:

1. The editor wrapper (skin)
2. The content itself

Until now, Joomla has only supported setting the Skin and has included its own `editor.css` file.

What this PR does is:

- Remove the old **Template CSS Classes** parameter.
- Adds 2 new parameters (site/admin) to set the Content CSS.
- Maintains support for using a `editor.css` file, only if specified.

### Testing Instructions

1. Open TinyMCE in your Plugin Manager
2. Click on the `Set 0` tab
3. Set the `Site/Administrator Content CSS` option to `dark`

### Actual result

The whole editor is now a dark theme:

![screeny](https://user-images.githubusercontent.com/2019801/83252567-5cfc4800-a1a3-11ea-9d61-2be2740fe845.png)

2020-05-29 11:27 UTC, dgrammatiko commented
This is wrong, the tinyMCE theming should follow the regular Joomla overriding way, eg to override a theme you should just place the new theme in the template `css/vendor/...blabla`. No options needed also it's the expected way. Let's do this properly not introducing exceptions. It's my fault I should have done this the right way many years ago when I introduced the theming option.BTW the code already exists here: https://github.com/joomla/joomla-cms/pull/14510

2020-05-29 17:17 UTC, brianteeman commented
Doesnt this prevent a template from shipping an editor.css file ?

2020-05-29 17:28 UTC, C-Lodder commented
@brianteeman Technically no, but you would have to explicitly set the `Custom CSS Classes` option to `editor.css` if you wanted to use it. Could re-add the auto detection, but will close in favour of: https://github.com/joomla/joomla-cms/pull/29259

2020-05-29 17:29 UTC, brianteeman commented
as its closed its not an issue any more as that pr doesnt change template css

2020-05-29 17:32 UTC, dgrammatiko commented
@C-Lodder please reopen this one, it covers other aspects and features that are not accessible right now. Just fix it so it will pick up editor.css automatically and we're good

2020-05-30 08:08 UTC, C-Lodder commented
@dgrammatiko I'll wait until this is merged

2020-06-01 17:01 UTC, Quy commented
@C-Lodder Please reopen. Thanks.

2020-10-17 05:01 UTC, opn365 commented
I have tested this item :white_check_mark: successfully on 2c8c33257e8511580ede30b9208ab2190041f38f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29257">issues.joomla.org/tracker/joomla-cms/29257</a>.</sub>

2020-10-17 05:40 UTC, gostn commented
I have tested this item :white_check_mark: successfully on 2c8c33257e8511580ede30b9208ab2190041f38f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29257">issues.joomla.org/tracker/joomla-cms/29257</a>.</sub>

2020-10-17 07:08 UTC, richard67 commented
Unfortunately the pull request here shows a conflict for the `administrator/language/en-GB/plg_editors_tinymce.ini`, so it shouldn't be set RTC (ready to commit) even if it has 2 good tests.

I'll try to solve the conflict later if @C-Lodder wasn't faster.

2020-10-17 07:56 UTC, richard67 commented
I've solved the conflict. It was just in the language strings so previous tests are still valid.

2020-10-17 08:07 UTC, richard67 commented
Will set it RTC as soon as I can see the automated tests are passing.

2020-10-17 08:14 UTC, C-Lodder commented
Richard, this currently breaks B/C a little

2020-10-17 08:15 UTC, richard67 commented
> Richard, this currently breaks B/C a little

@C-Lodder What? The PR? Or how I solved the conflict? And what shall we do now?

2020-10-17 08:38 UTC, softforge commented
I have tested this item :white_check_mark: successfully on f406d88657fbfad9c28a62fd838a7bbe77eeb6ea<br /><br />I was testing as well but other tester had not filled in in the sheet so its for extra tests!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29257">issues.joomla.org/tracker/joomla-cms/29257</a>.</sub>

2020-10-17 08:55 UTC, C-Lodder commented
@richard67 see this https://github.com/joomla/joomla-cms/pull/29257#issuecomment-636092789

Let me revisit it this weekend

2020-10-17 08:59 UTC, richard67 commented
> @richard67 see this [#29257 (comment)](https://github.com/joomla/joomla-cms/pull/29257#issuecomment-636092789)
> 
> Let me revisit it this weekend

@C-Lodder Ok, thanks in advance. I'll set the "Updates Requested" label so nobody sets RTC. Let me know when I shall remove that label.

2020-10-17 09:22 UTC, dgrammatiko requested changes

2020-10-17 09:22 UTC, dgrammatiko commented on plugins/editors/tinymce/tinymce.php
> +				$content_css    = Uri::root(true) . '/templates/' . $template . '/css/' . $content_css_custom;
@C-Lodder this needs update to support the new template mode (child templates) where the assets are moved to `media/templates/site|administrator/templateName/css`

2020-10-18 15:31 UTC, C-Lodder commented
I'm going to close this as it's been too long since I last worked on it, and I'm too burned out to continue the thought process.

Will leave the branch open it anyone wants to continue with it.

2020-10-18 15:31 UTC, closed without merging