[4.0] Adding modal with progress to installation
joomla/joomla-cms pull request #29376
Opened 2020-06-01 23:06 UTC by Hackwar

This adds a modal with progress indicators to the installation. This is a fugly implementation. It uses jQuery, calls are at the wrong place in the code, it looks ugly, etc., but I wanted to show how I think the installation could be improved.

This adds a modal with the different steps which are going to happen next, when clicking on "Install Joomla". Then there are spinners and checkmarks next to it when they are processed. I invite others to improve this PR.

2020-10-20 16:13 UTC, brianteeman commented on installation/language/en-GB/joomla.ini
> +INSTL_PROGRESS_STEP_CONFIG="Saving configuration and clean-up"
```suggestion
INSTL_PROGRESS_STEP_CONFIG="Saving configuration and cleaning up"
```

Otherwise it suggests that it is saving a clean-up

2020-10-20 16:14 UTC, brianteeman commented on installation/language/en-GB/joomla.ini
> +INSTL_PROGRESS_STEP_DBCHECK="Check DB credentials"
```suggestion
INSTL_PROGRESS_STEP_DBCHECK="Checking DB credentials"
```

2020-10-20 16:14 UTC, brianteeman commented on installation/language/en-GB/joomla.ini
> +INSTL_PROGRESS_STEP_CONFIG="Saving configuration and clean-up"
```suggestion
INSTL_PROGRESS_STEP_DBCHECK="Checking DB credentials"
INSTL_PROGRESS_STEP_CREATE="Checking system configuration"
INSTL_PROGRESS_STEP_POPULATE1="Installing basic database tables"
INSTL_PROGRESS_STEP_POPULATE2="Installing support database tables"
INSTL_PROGRESS_STEP_POPULATE3="Installing extensions tables"
INSTL_PROGRESS_STEP_CUSTOM1="Installing localisations"
INSTL_PROGRESS_STEP_CUSTOM2="Installing customisations"
INSTL_PROGRESS_STEP_CONFIG="Saving configuration and clean-up"
```

2020-10-20 16:15 UTC, brianteeman commented on installation/template/index.php
> +									<i class="fa fa-spinner fa-spin text-white"></i>
please dont use `<i`

2021-01-05 09:27 UTC, Hackwar commented on installation/template/index.php
> +									<i class="fa fa-spinner fa-spin text-white"></i>
fixed

2021-01-05 09:31 UTC, Hackwar commented
So this code isn't perfect, but I can't get anyone to look at it and improve it and I wouldn't know how to make it better either. At the same time, I think this is a necessary feature and needs to be added to 4.0, which is why I'm marking this as ready for review now. I'd rather merge this imperfect code, than to have the mess we have so far.

2021-01-05 09:36 UTC, brianteeman commented
How can we test it. As far as I can recall no one was previously able to setup an environment where the ftp install would be triggered. Did you find a way?

2021-01-05 09:38 UTC, Hackwar commented
@brianteeman 😉 
I would appreciate your comment on this issue as well. 😃

2021-01-05 09:40 UTC, brianteeman commented
@hackwar I am looking

2021-01-05 09:48 UTC, brianteeman commented
it works, its an improvement, it is fugly which for a first impression of joomla is not good.
 
The main problems are that it is completely inaccessible (suggestions coming) and that the popup closes before I have the time to read it.

2021-01-05 09:51 UTC, brianteeman commented
Can you not use the joomla-alert in the same way that you did in the sample data installer? That immediately solves a lot of issues.

2021-01-05 09:52 UTC, brianteeman commented on installation/language/en-GB/joomla.ini
> +INSTL_PROGRESS_STEP_DBCHECK="Checking DB credentials"
```suggestion
INSTL_PROGRESS_STEP_DBCHECK="Checking database credentials"
```

consistency ;)

2021-01-05 09:52 UTC, brianteeman commented on installation/language/en-GB/joomla.ini
> +INSTL_PROGRESS_STEP_POPULATE3="Installing extensions tables"
```suggestion
INSTL_PROGRESS_STEP_POPULATE3="Installing extensions database tables"
```

consistency ;)

2021-01-05 09:56 UTC, brianteeman commented on installation/template/index.php
> +							<h5 class="modal-title"><?php echo Text::_('INSTL_PROGRESS_MODAL'); ?></h5>
You are using h5 as a means of controlling the font size. This is obviously wrong. Headings levels should be contiguous so you can't have an h5 if there is no h2,h3,h4 etc

2021-01-05 09:58 UTC, brianteeman commented on installation/language/en-GB/joomla.ini
> +; Installation progress modal
Please alpha sort this block of strings

2021-01-05 09:58 UTC, bembelimen commented on installation/template/index.php
> +							<h5 class="modal-title"><?php echo Text::_('INSTL_PROGRESS_MODAL'); ?></h5>
You can use the class ".h5" to style it like a "h5" tag.

2021-01-05 09:59 UTC, brianteeman commented on installation/template/index.php
> +HTMLHelper::_('bootstrap.framework');
it seems a bit excessive to load bootstrap here for this modal. What is the reason?

2021-01-05 10:02 UTC, brianteeman commented
Not going to comment further for now as those comments would be made irrelevant if you use joomla-alert

2021-01-05 10:19 UTC, Hackwar commented
> it works, its an improvement, it is fugly which for a first impression of joomla is not good.

I'm open for improvements. I've been asking around a bit in the last months and people frankly have let me down. I'm not exactly creative enough to make it look nicer. For example the progress icon in front of the lists are hidden by setting them to white. I know that is a really ugly way, but I'm a backend dev mainly...

> The main problems are that it is completely inaccessible (suggestions coming) and that the popup closes before I have the time to read it.

The popup is not really meant for people like you with a quick database/server, but for those with slow systems to give them an indication of progress. I had a misconfiguration on my system some time ago and that resulted in the database population step taking several minutes. A time in which you have no idea what is happening, where it is failing, etc.

> Can you not use the joomla-alert in the same way that you did in the sample data installer? That immediately solves a lot of issues.

I think that would not be the best approach. First of all, the content has to show up above that spinner/loader/whatever thing and thus I would expect a modal. We also need a way to block the interaction with the previous form, so the overlay of the spinner and modal are good. At the same time I don't want the steps to show up one after the other, but to have them visible all at the same time, so that you can see how much still has to happen...

2021-01-05 10:19 UTC, Hackwar commented on installation/template/index.php
> +HTMLHelper::_('bootstrap.framework');
I've not seen a Joomla 4 modal solution besides the bootstrap one...

2021-01-05 10:27 UTC, brianteeman commented
joomla -alert is the way to go - it solves your real problems

2021-01-07 00:43 UTC, Hackwar commented
I've checked joomla-alert and it definitely is not the way to go. It is the wrong UI element for this task. However I've looked over my implementation and improved it a bit and hopefully this https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions is correct and thus this should now be more accessible.

This does contain one issue and that is it is only looking for mysql custom SQL files and not postgres. Do we want to catch that case as well or do we put the burden for that on the one adding one of those custom SQL files?

2021-01-07 01:09 UTC, brianteeman commented
On my phone so can't check right now but the aria live element must be in the page before the message is created. Usually you would achieve that in the html not the js. See https://bitsofco.de/using-aria-live/

2021-01-07 08:19 UTC, brianteeman commented
Confirmed my suspicion from last night.

2021-01-07 09:05 UTC, Hackwar commented
Changed.

2021-01-07 09:06 UTC, brianteeman commented on installation/template/js/setup.js
> +  modalel.setAttribute('aria-live', 'polite');
This line won't do what you expect. The aria-live has to be in the pageon load.

2021-01-07 09:08 UTC, brianteeman commented on installation/template/index.php
> +			<div id="installationProgress" class="modal" tabindex="-1" style="z-index:10050;">
aria-lve should be added to this div here

2021-01-07 09:13 UTC, brianteeman commented on installation/template/index.php
> +			<div id="installationProgress" class="modal" tabindex="-1" style="z-index:10050;">
And it needs to be assertive not polite

2021-01-07 09:14 UTC, brianteeman commented on installation/template/index.php
> +			<div id="installationProgress" class="modal" tabindex="-1" aria-live="polite" role="region" style="z-index:10050;">
Sorry I was still typing while you updated. This needs to be assertive.

If you turn on the builtin screenreader on your computer you can test this

2021-01-07 13:34 UTC, Hackwar commented on installation/language/en-GB/joomla.ini
> +; Installation progress modal
Done

2021-01-07 13:35 UTC, Hackwar commented on installation/template/index.php
> +			<div id="installationProgress" class="modal" tabindex="-1" aria-live="polite" role="region" style="z-index:10050;">
Done.

2021-01-07 13:35 UTC, Hackwar commented on installation/template/index.php
> +			<div id="installationProgress" class="modal" tabindex="-1" style="z-index:10050;">
done.

2021-01-07 13:35 UTC, Hackwar commented on installation/template/js/setup.js
> +  modalel.setAttribute('aria-live', 'polite');
has already been fixed.

2021-01-07 13:36 UTC, Hackwar commented
Would you sign off on this this way? Then we could move forward with this whole thing.

2021-01-07 14:12 UTC, brianteeman commented
its an improvement. not perfect but can be improved in another pr.
not for me to approve anything

2021-01-07 14:20 UTC, Hackwar commented
The main question was, if you would sign off on the accessible part of this PR. Thanks for your support.

2021-01-07 16:01 UTC, HLeithner commented
Hi,

nice progressbar, sorry for no feedback didn't see the pr in june

Found a small problem in case of an error

https://user-images.githubusercontent.com/1497730/103914159-b3ead800-5109-11eb-86f8-734f3bbd466d.mp4

and could you fix the cs errors please

The check marks may could have a lighter green but I don't know if this is our default green.

2021-01-07 16:22 UTC, brianteeman commented
> The main question was, if you would sign off on the accessible part of this PR. Thanks for your support.

Still not for me to do that. That would be the role of the accessibility team

2021-01-07 16:35 UTC, Hackwar commented
CS errors are not from this PR, but currently part of the 4.0-dev branch. Fix is here #31879

The check mark is the default color that we use. 

I'll fix the error handling.

2021-01-07 19:06 UTC, Hackwar commented
All changes incorporated. Please test and lets see if we can merge this quickly.

2021-01-07 19:43 UTC, brianteeman commented
I  still don't understand why this is a modal

2021-01-07 21:56 UTC, Hackwar commented
Then tell me how else you would display this information. With all steps-to-be-processed visible from the start, returnable to the previous screen, updating the existing data, etc.

2022-01-20 03:56 UTC, bembelimen commented
I think this feature would be a nice addition, but I have to agree, it shouldn't be a modal.

I think this should me incooperated into a bigger improvement project for the installer (there are many flaws which should be fixed) and at the end a solution could be, that we hide (not just gray out via overlay) the installation form and show only the installation progress (+ valid return when failed, not just the whole form).

To not forget about this idea, I set it to draft.

2022-06-27 13:09 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2022-08-30 10:23 UTC, HLeithner commented
![image](https://user-images.githubusercontent.com/1497730/187413283-d58dd8d5-6fce-45ee-bd9b-6a35ab10164a.png)

Can we maybe get some space between the progressbar and the checkbox list?
Rest looks great.

2022-08-30 10:23 UTC, HLeithner commented on installation/tmpl/setup/default.php
> +}
```suggestion
if (is_file(JPATH_INSTALLATION . '/sql/mysql/localise.sql')) :
    $steps++;
endif

if (is_file(JPATH_INSTALLATION . '/sql/mysql/custom.sql')) :
    $steps++;
endif
```

2022-08-30 10:35 UTC, brianteeman commented on installation/language/en-GB/joomla.ini
> +INSTL_PROGRESS_STEP_POPULATE1="Installing basic database tables"
Base not basic

2022-08-30 10:39 UTC, Hackwar commented on installation/language/en-GB/joomla.ini
> +INSTL_PROGRESS_STEP_POPULATE1="Installing basic database tables"
Done.

2022-08-30 10:39 UTC, Hackwar commented
> ![image](https://user-images.githubusercontent.com/1497730/187413283-d58dd8d5-6fce-45ee-bd9b-6a35ab10164a.png)
> 
> Can we maybe get some space between the progressbar and the checkbox list? Rest looks great.

Done.

2022-08-30 10:41 UTC, brianteeman commented on installation/tmpl/setup/default.php
> +endif
missing ;

2022-08-30 10:41 UTC, brianteeman commented on installation/tmpl/setup/default.php
> +endif
missing ;

2022-08-30 10:44 UTC, brianteeman commented
Does it really still need the joomla spinner at the end?

2022-08-30 10:46 UTC, brianteeman commented
This completely fails accessibility. Nothing is announced at all. There is just complete silence and a user would not know that anything is happening

2022-08-30 10:51 UTC, Hackwar commented
> Does it really still need the joomla spinner at the end?

I don't need it. However I would leave the review of stuff like this to someone else.

2022-08-30 10:52 UTC, Hackwar commented
> This completely fails accessibility. Nothing is announced at all. There is just complete silence and a user would not know that anything is happening

Unfortunately I don't know enough about accessibility to get this right. I would need your help and the help from @chmst and @drmenzelit. I'm open for what needs to be done to get this right.

2022-08-30 10:54 UTC, Hackwar commented
I refactored the whole PR to not use a modal, but to show an additional step in the normal installation process. Please review this PR again, so that we hopefully can add this to Joomla 4.3.

2022-08-30 10:59 UTC, brianteeman commented
You will probably need to use aria-live 

https://cccaccessibility.org/web-1/web-developer-tutorials/using-aria-live

2022-09-11 09:56 UTC, brianteeman commented
needs to be checked by the JAT @chmst

2022-09-11 10:32 UTC, drmenzelit commented
> needs to be checked by the JAT @chmst

we are on it

2022-09-11 14:58 UTC, chmst commented
We made a few tests and the result is:

The progress bar is a nice enhancement and is accessible as all the update - progress bars in com_installer.  
The indication of percentage  seems to be not correct, maybe due to rounding errors. Steps could be a better solution. 

The display of steps however as text is not accessible, neither for sighted nor for blind users and should be hidden.
Joomla provides a very  fast installation and no reader can read all the information in a few seconds. 

On the other hand, it is useful to see where the process stopped, if there is an issue. 
Maybe the texts can be hidden and only if there is no progress for 10or 20 seconds, the texts of performed steps are made visilbe.

2022-09-11 15:21 UTC, brianteeman commented
> The display of steps as text however is not accessible, neither for sighted nor for blind users and should be hidden.
Joomla provides a very fast installation and no reader can read all the information in a few seconds.

If you do that then currently there is no way to know that anything is happeninbg

> Joomla provides a very fast installation and no reader can read all the information in a few seconds.

Instead of going to the next page automatically you can provide a next button. This allows everyone, sighted or not, to read the text

2022-09-11 15:35 UTC, chmst commented
I personally don't want to know what's happening if an installation runs, but am glad to do and to see nothing than the "congratulations" message. I like the progress bar in the updater. Only if something goes wrong, I want fo know where and why. 

It would be great if we could get a progress bar in 4.3. The bar in the updater seems to be globally accepted.  Then as @bembelimen wrote, a new concept could be made for future.

2022-09-12 02:21 UTC, N6REJ commented
> You will probably need to use aria-live
> 
> https://cccaccessibility.org/web-1/web-developer-tutorials/using-aria-live

It specifically states that it should not be used in this case
>Section three-- avoid misuse.
>
>The aria-live attribute should not be used for dynamic content that's not critical. This just adds noise, literally, for assistive technologies.`

2022-09-12 05:52 UTC, brianteeman commented
By your interpretation of that then this entire PR should be rejected

2022-09-12 09:30 UTC, N6REJ commented
Thats for JAT @chmst to decide not me.

2022-09-29 16:15 UTC, bembelimen commented
For me, this looks good to go :+1: 
Also the aria-live="polite" is from my understanding correct.
@brianteeman do you have the capability to check with a screen reader if the behaviour is the expected one? If yes I would reactivate this PR for testers.

2022-09-29 17:13 UTC, brianteeman commented
> @brianteeman do you have the capability to check with a screen reader if the behaviour is the expected one? If yes I would reactivate this PR for testers.

yes - of course - and so does every windows and mac user as they have a screen reader with their os.

However this is something that you should be asking the JAT and not me. @chmst as leader of the JAT think its better to have a long period of silence while the instllation takes place. JAT should be the ones making decisions on ccessibility not me

2022-09-29 19:55 UTC, brianteeman commented
... and as this PR has the a11y tag it must be approved by the JAT and so far they _mistakenly_ do not approve

2022-09-30 06:48 UTC, alikon requested changes

2022-09-30 06:48 UTC, alikon commented on installation/tmpl/setup/default.php
> +if (is_file(JPATH_INSTALLATION . '/sql/mysql/localise.sql')) :
and if postgres ?

2022-09-30 08:10 UTC, Hackwar commented on installation/tmpl/setup/default.php
> +if (is_file(JPATH_INSTALLATION . '/sql/mysql/localise.sql')) :
I added that as well now.

2022-09-30 08:13 UTC, alikon commented on installation/tmpl/setup/default.php
> +                    <?php if (is_file('sql/mysql/localise.sql')) : ?>
if postgres ?

2022-09-30 08:13 UTC, alikon commented on installation/tmpl/setup/default.php
> +                    <?php if (is_file('sql/mysql/custom.sql')) : ?>
if postgres ?

2022-10-02 11:44 UTC, drmenzelit commented
I have not enough experience using screen readers, so my results are maybe not 100% correct. First thing I notified: using NVDA I get different results in Chrome and Firefox (Chrome seems to be more verbose). What I tested:
- removed `aria-live=polite` from the `<div> `and `role=status` from the `<ul>`, added `aria-live=polite` to each `<li>`
- removed `aria-live=polite` from the `<div> `and `role=status` from the `<ul>`, added `role=status` to each `<li>`
- rewrote the code to use readonly checkboxes instead of a list, ticked each checkbox using Javascript after the step is completed, tried aria-live and change of focus...

Conclusion: the installation is too fast and the screen reader is not able to announce the steps correctly (too fast, too verbose). The advantage of checkboxes is that the user can tab though them and get the information, but here is also the problem that the process is too fast, before you get tabbed through the steps, the installation is finished and you get the next screen.

I think the steps should stay hidden (visually and for screen readers), so that they can be used for the automated tests Hannes is working on. In case of an error an alert should be visible and audible, so the user knows what went wrong. It would be nice to get an announcement at the end that the installation is complete.

Other ideas are most welcome.

2022-10-02 12:13 UTC, brianteeman commented
The container with aria-live must exist on the page load. It cannot be added by the message.

It is not for a non-screen reader to determine if the information is too fast. Regular users know far more about using and controlling the screen reader.

If you consider it too fast for a screen 
reader then it should also be removed visibly. You can not have one without the other.

The code in this pr is technically correct and should be accepted

2022-10-02 12:26 UTC, drmenzelit commented
> The container with aria-live must exist on the page load. It cannot be added by the message.

As it is now, it was ok in my test with NVDA and Firefox, in Chrome NVDA started reading from the first step again and again

 
> It is not for a non-screen reader to determine if the information is too fast. Regular users know far more about using and controlling the screen reader.

Yes, and that is why it is not so easy to test, we need a real screen reader user...
 
> If you consider it too fast for a screen reader then it should also be removed visibly. You can not have one without the other.

That is our suggestion too
 
> The code in this pr is technically correct and should be accepted

Yes, it is technically correct, but we have to make sure that the user experience of screen reader users is good.

Another thing I noticed is that the progress bar was completely ignored by NVDA. Using a screen reader add-on in Chrome the percentage was announced, but at the end was more than 100% 😅

2022-10-02 12:36 UTC, brianteeman commented
Grrrh. The JAT should be enhancing accessibility not diminishing it.

2022-10-02 12:42 UTC, drmenzelit commented
> Grrrh. The JAT should be enhancing accessibility not diminishing it.

That is not fair. We are trying to improve the code to offer the best possible user experience. Which of our comments let you to the conclusion we are diminishing accessibility?

2022-10-02 13:08 UTC, brianteeman commented
Screen readers have the ability to change the speed at which text is read. Most programs can vary the speed between 60 to 400 words per minute

In English, the typical read speed ranges between 120 to 150 words per minute, where advanced and fast screen reader users can understand content being read at a speed of even 450 words per minute. Even if most screen reader users don’t require such high speed, it is still common for them to use higher rates than that of typical spoken language. It is important to keep in mind that the first impression that long-to-read content slows down the user can be deceptive as when set at high reading speed rates, it is being read blazingly fast. Remember, don’t worry too much about long descriptions.

Basing your decision as a non experienced user to remove both visual and auditory feedback is degrading the accessibility. Clicking a button and then not getting any feedback for 10-20 seconds is not acceptable.

2022-10-02 13:41 UTC, drmenzelit commented
It is not the read speed of a screen reader, but the speed of the installation... the screen reader says: checking data.. (interrupted, because the next step is already finished), and the next step the same, and depending on your system maybe starting with reading the first step again... maybe an experienced screen reader user can sort that kind of issue, but I don't see what the improvement in user experience should be...

Your words: 
>If you consider it too fast for a screen reader then it should also be removed visibly. You can not have one without the other.

And I don't know how we are diminishing accessibility on something we don't had all the years before...

2022-10-02 15:21 UTC, brianteeman commented
I give up trying to explain - you're clearly not listening and as the JAT knows best I will finish.

2022-10-02 15:30 UTC, bembelimen commented
Sorry @brianteeman first you asked for the @joomla/joomla-accessibility-team-jat and know you're complaining if they give feedback, that is kindergarden.

After reading the explanation, I still think in theory, that aria-live is a possible solution here but in real world just outputting everything from the progress is not reasonable (and like @drmenzelit wrote, the installation process is too fast to cover the full text). The steps itself (when they're successful) do not give any benefit when announced, the only thing which is really important is the message if the installation was successful (we could discuss this, too) or if it failed.

2022-10-02 16:00 UTC, brianteeman commented
You dont get it. Let me try one last time without the personal comments which are beneath you.

The purpose of this PR is to add a feedback of the completion of each stage of the installation. If that is to be accepted then it must be done in such a way that it is accessible to everyone. Just like every other piece of code.

Rejecting the addition of aria-live  because a non-screen reader user says that they cannot hear all the text being read is not a good reason. As I already pointed out, a regular screen reader user will almost certainly have the text speed greatly increased etc. and there are other assistive technologies that make use of the aria-live messages which are not influenced by speed at all.

If it is determined that the display of the texts is of zero value then they should be removed from this PR. Personally I find them a useful addition and similar to a lot of other software.

The suggestion that 10 - 20 seconds of silence is acceptable really is not and shouldnt even be considered as a serious comment which sadly is true with the current installation process

2022-10-02 17:23 UTC, angieradtke commented
It would be nice if we could make all content equally accessible to all people.  Unfortunately, that doesn't always work out.
From a technical point of view, this improvement is certainly useful for developers. They can see where there might be problems with the installation.
 But usually the installation goes smoothly.  Most people, even sighted ones, will pay less attention to the messages as long as everything runs well.
They don't need to look if they don't care. Screenreader users don't have that choice when we are working with a live region. You are certainly right when you say that most screen reader users run their speech output at a pace where we can't understand anything. But still, there are beginners there too. 

Besides, we have checkpoint 2.2 in the WCAG, automatic output without prompting is not an option. https://www.w3.org/TR/WCAG22/#enough-time

Splitting the installation into individual steps that are continued by clicking a button would be the only accessible solution. But I think this is nonsense.  @brianteeman If you have a solution that works for everyone, we would be really happy.

2022-10-02 17:45 UTC, brianteeman commented
Well as you have brought up  https://www.w3.org/TR/WCAG22/#enough-time then this PR will have to be adjusted to remove all off the progress messages

2022-10-03 12:58 UTC, angieradtke commented
can you please test this: http://der-auftritt.de/tests/progress.html

2022-10-03 13:36 UTC, chmst commented
> The purpose of this PR is to add a feedback of the completion of each stage of the installation. If that is to be accepted then it must be done in such a way that it is accessible to everyone. Just like every other piece of code.

Not every piece of code is accessible to users - all the debuginformation is not accessible. If the purpose of the PR is providing information for tests, then no user must see or hear an information. If the information is hidden for everyone then everyone has the same information, only the testing machine has more.

Question @brianteeman - you know the progress bars in update screens. I personally like them. They also run fast and I never had a situation where such a bar stopped.  No clue what happens in such a case. Are these progressbars  accessible in your opinion?

2022-10-03 17:37 UTC, drmenzelit commented
> can you please test this: http://der-auftritt.de/tests/progress.html

The demo was updated and tested with NVDA and VoiceOver. Angie uses here the native html progress element, it has to be tested if the Bootstrap progress bar also works as expected adding aria-label to it.
The list of steps can be hidden (to avoid flashing text and no enough time to interact with - as Angie already posted), but in case of an error an alert has to be visible and audible.

2022-10-03 18:22 UTC, brianteeman commented
Thanks for creating that @angieradtke. This has the same issues that were objected to with @Hackwar code in this pr. But for different reasons. This code uses assertive instead of polite. Assertive means that it always interupts whatever the screenreader is doing. So as the screenreader tries to read out the text messages it is interupted with the content fo the assertive statement from the progress bar.

Not sure at all what you meant by testing it with nvda and narrator

> Not every piece of code is accessible to users - all the debuginformation is not accessible. 

True but it should be if we can make it. Also this is one of the very first things a user is presented with and if we say J is accessible and one of the very first screens is not then it doesnt create a good impression.

2022-10-04 06:40 UTC, angieradtke commented
This is not the final solution yet. There are some  general problem issues. But we are on the right track. I am glad that blind experts are helping us right now.  The issue of "polite"  is secondary for the moment.  However, I think assertive is still right here. The problem  is rather the inconsistent of  of screen reader handling.  Jaws on Firefox remains mute. At the moment we don't know why. Jaws on Chrome works. NVDA and voiceover work as well.

2022-10-04 06:45 UTC, brianteeman commented
Don't waste time on the Firefox issue as screen readers do not work consistently across all browsers.

2022-10-04 06:48 UTC, angieradtke commented
We need  a bulletproof solution working  as a blueprint for other apps as well

2022-10-04 06:59 UTC, brianteeman commented
> We need a bulletproof solution working as a blueprint for other apps as well

there is no such thing - sadly

https://www.powermapper.com/tests/screen-readers/

2022-10-04 07:10 UTC, angieradtke commented
here are no tests  width progress:
https://www.powermapper.com/tests/screen-readers/ua/ua-jaws-ff/

So we should test. I hope we can find a solution.

2022-10-04 07:12 UTC, brianteeman commented
My point in sharing that link was to show the evidence to support my statement that screen readers do not work consistently across all browsers. 

Forgive me for trying to stop you wasting your time chasing the pot of the gold at the end of the rainbow.

2022-10-04 07:20 UTC, angieradtke commented
So it works with:

- Narrator in Edge. 
- Jaws and Chrome
- NVDA in Chrome and Firefox.
- Voiceover 

Leonie told me to stay with assertive.

There is only the jaws in Firefox issue.

2022-10-04 07:27 UTC, angieradtke commented
@brianteeman You know, curiosity is one of my bad qualities.

2022-10-04 08:04 UTC, angieradtke commented
@brianteeman changed the code to pure HTML http://der-auftritt.de/tests/progress2.html;
Please retest

2022-10-22 11:35 UTC, Hackwar commented on installation/tmpl/setup/default.php
> +                    <?php if (is_file('sql/mysql/custom.sql')) : ?>
This is now outdated.

2022-10-22 11:36 UTC, Hackwar commented on installation/tmpl/setup/default.php
> +                    <?php if (is_file('sql/mysql/localise.sql')) : ?>
This is now outdated.

2022-10-22 11:43 UTC, Hackwar commented
First of all big thanks to the Joomla Accessibility Team. Numerous (disabled) people have tested this PR and given feedback and the overall consensus was, that the text below the progressbar was just clutter and not helpfull. My initial motivation was to have some output for debugging purposes and with the text that went a bit to far. The progressbar would already be enough for that purpose and at the same time it would provide a usefull response to endusers - with and without disabilities.

One feedback was to use a proper progressbar element. Another feedback from a blind user was to use the progressbar from the joomla updater. Since my code used that already, I didn't change that now.

Would that now be acceptable to be merged?

2022-10-23 09:55 UTC, angieradtke commented
Not at all.  Last checks are needed . We have to talk about the persentations of  errors as well.
The displayed steps and ariavaluenow does not fit to each other. 
 At the end you have  ariavaluenow="7"  but your code says you have $steps = 6; 
 This is a small issue with great impact.

I built a summary for screenreader-tests here:
https://der-auftritt.de/tests/progress.html

If we have Feedback from Julian we can go forward.

2022-10-23 10:37 UTC, brianteeman commented
Which of @angieradtke versions is this using. /me confused

2022-10-23 10:45 UTC, angieradtke commented
@brianteeman  the first one is closest to Hannes 
 Native Version 1 is the cleanest

2022-10-23 12:14 UTC, brianteeman commented
so why isnt it using native version 1 - if your tests said that was the best?

similar example with full documentation from deque
https://dequeuniversity.com/library/aria/progress-bar-bounded

2022-10-23 12:43 UTC, Hackwar commented
Because two equally qualified experts told me 2 differing solutions. One said to use the native progressbar, the other to use the one from bootstrap.

2022-10-23 12:59 UTC, chmst commented
Both solutions seem to work - with differences which don't affect the function as a whole. I suggest to use the same everywhere in Joomla.

2022-10-23 13:23 UTC, angieradtke commented
> similar example with full documentation from deque
https://dequeuniversity.com/library/aria/progress-bar-bounded

similar, but here a native progress bar also gets Aria attributes. This is kind of duplicative.
I suspect this code is from times when the native element was not well supported.
I hope the native element will pass the sceenreader tests, that's my favorite because it's native and thus robust.
But let's wait and see what Julian says.  If the screenreader support is not there, the nice code won't help us either.

2022-10-26 09:38 UTC, angieradtke commented
Dear Hannes , dear Team,

sorry, it took a while, but here you can find the best practise example, including error messages.

https://der-auftritt.de/tests/final.htm

 Leather we are not finished yet. We want to use this example as a component,  so we can use it everywhere. ( Finder index/update)

So we  should  rewrite the used javascript @dgrammatiko  into a generic working variant ( including variable messages)
and place it where it has to go.

The CSS  has to be added  at the appropriate place using the color variables as well

2022-10-26 09:40 UTC, brianteeman commented
@angieradtke that rocks!!

2022-11-09 11:11 UTC, Hackwar commented
I've adapted the proposal from @angieradtke as good as possible. Please have a look and test if this is correct now.

2022-11-13 09:38 UTC, angieradtke commented
Hi Hannes,  found some issues:

**1.** The text of the label should be only "Installation" before the installation  starts.
And only when the  installation  is really running it should be changed to "Installation running".  

In the screenshot  you can see that the displayed information can't be true.

![hannes](https://user-images.githubusercontent.com/1172403/201514000-5dd46d7f-b1c7-4c70-9f75-2748b01d5a82.png)



 <label class="progresslabel text-center">
                    <progress class="progressbar" id="progressbar" value="0" max="8"></progress>
	                <span id="progress-text" role="status"><?php echo Text::_('INSTL_IN_PROGRESS'); ?></span>
                </label>

change  language string to  echo Text::_('INSTL'); 

```
 <label class="progresslabel text-center">
                    <progress class="progressbar" id="progressbar" value="0" max="8"></progress>
	                <span id="progress-text" role="status"><?php echo Text::_('INSTL'); ?></span>
                </label>
```





**2**. How Many steps has the installation?
  At the end you have the code as follows:

```
<label class="progresslabel text-center">
                    <progress class="progressbar" id="progressbar" value="7" max="8"></progress>
                    <span id="progress-text" role="status">Installation running</span>
                </label>
```


I'm not really sure. After the installation  there is a fast redirect , so that I don't get the the information  "Installation finished"
It would  be better to set a timeout of a few seconds, so the user know that  everthing is fine.

**3.**  I  took a look at  the js-files. I didn't get all the way through it because things related to the progressbar are spread across both JS files.  I couldn't find a loop where " installation running"  per step is ejected.  
It almost looks to me like this is only set at the beginning and the end. Maybe I just haven't found that either or I did not understand the code.

4. How can I simulate an error in the middle of the installation progress?
I do not know that, so I could not see if everything is correct with the JS Error handling.

2022-11-13 13:02 UTC, wilsonge commented on installation/template/scss/template.scss
> +progress::-webkit-progress-bar {
You shouldn't need to add all the browser specific things. They will be added automatically by the build tooling on compile based on the supported browser lists

2022-11-14 07:53 UTC, angieradtke commented
Hannes , maybe helpful: https://der-auftritt.de/en/insights/progress-en.html

2022-11-14 09:18 UTC, Hackwar commented on installation/template/scss/template.scss
> +progress::-webkit-progress-bar {
I removed it again.

2022-11-14 09:24 UTC, Hackwar commented
@angieradtke 
1. Fixed this.
2. I added a delay of 2 seconds at the end. The bar actually goes to 8 out of 8, but afterwards immediately does a redirect. This has been fixed as well.
3. I indeed only set that once. I'm now setting it after each step.
4. To generate an error, you can go to /installation/src/Model/DatabaseModel.php and in line 422 insert `throw new Exception('404', 'Error');` to generate an error upon installation.

2022-11-17 11:19 UTC, MacJoom commented
I have tested this PR and i suggest to add a message below a possible error what to do next: 
Something like: "Please refresh this page to start over"

2022-11-17 11:23 UTC, brianteeman commented
@MacJoom That message would not be correct - depending on when the error occurred

2022-11-17 11:24 UTC, MacJoom commented
![Screenshot 2022-11-17 at 12-07-34 Joomla Installer](https://user-images.githubusercontent.com/6154099/202433273-04782d21-9c7b-4648-8a8b-5da5d61af595.png)
In my case this message is not wrong but misleading - the database was created before but the database name entered was wrong. So this case should be mentioned too - "the database name is wrong"

2022-11-17 11:28 UTC, MacJoom commented
> @MacJoom That message would not be correct - depending on when the error occurred
I understand - but i think we need to help the user in a way or another - best would be a button...

2022-11-17 11:35 UTC, angieradtke commented
I see that is not easy to understand.  

We have two issues :  


- The JS is not working correct we need **a loop** and an error function
- The language strings should be well translated  to make  sence

2022-11-17 15:27 UTC, Hackwar commented
You are free to improve the error handling of the installation and be my guest when it comes to refactoring the installation, however that is outside of the scope of this PR. I will not start refactoring the whole installation on a PR with already 3 years of work on it. This already is a gigantic improvement, since users now at least get the feedback that there was an error, compared to before, where they had an eternal "loading" screen.

2022-11-17 17:27 UTC, chmst commented
@MacJoom  thank you for testing. 
As others wrote already, changes in messages or in the installation process are out of scope on this PR.  This  PR has a long and interesting a11y story - worth to be published outside github.

Improving messages could go to another issue or PR.

2022-11-17 17:29 UTC, MacJoom commented
Yes I see that this PR is a huge improvement to the installation routine. And i really would like to see this merged for 4.3  Messages can be adapted later...

2022-11-17 17:37 UTC, MacJoom commented
I have tested this item :white_check_mark: successfully on 2e7fbe21a40c9125e72123bb9ce0df693c93ce8c<br /><br />4.3-dev/PHP 8.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2022-11-22 01:47 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 2e7fbe21a40c9125e72123bb9ce0df693c93ce8c<br /><br />Great improvement! Thanks @Hackwar! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2022-11-22 01:48 UTC, jwaisner commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2022-11-23 10:22 UTC, laoneo commented
WhenI enter a wrong DB information, I just see the following screen:
![image](https://user-images.githubusercontent.com/251072/203522925-b6d9f6d6-51cf-4d85-8c96-88198a494c23.png)

There is no way for me to renter the database credentials again. The back button is not working.

2022-11-29 11:18 UTC, Hackwar commented
The requested changes from @laoneo have been made.

2022-11-30 08:39 UTC, laoneo commented
Back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2022-12-06 12:12 UTC, Hackwar commented
@jwaisner @MacJoom could you test this again?

2022-12-06 13:31 UTC, MacJoom commented
I have tested this item :white_check_mark: successfully on 2e7fbe21a40c9125e72123bb9ce0df693c93ce8c<br /><br />Tested successfully - all sorts of wrong input on database credentials tested. Back button works to retry <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2023-01-09 13:00 UTC, HLeithner commented
I have tested this item :white_check_mark: successfully on 2e7fbe21a40c9125e72123bb9ce0df693c93ce8c<br /><br />Maybe unrelated but I wasn't able to install any additional language.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2023-01-09 13:39 UTC, laoneo commented
There is still no way to get back for me when an error happens:
![image](https://user-images.githubusercontent.com/251072/211320866-0453a56f-018e-4ebd-9a39-b727f6a22ac9.png)

@MacJoom how could you go back?

2023-01-09 13:44 UTC, dgrammatiko commented on installation/template/js/setup.js
> +        progress_text.setAttribute('role', 'alert');
To fix the error reported by @laoneo I guess this code is needed here:

```js
        document.getElementById('installStep1').classList.add('active');
         document.getElementById('installStep2').classList.add('active');
         document.getElementById('installStep3').classList.add('active');
         document.getElementById('installStep4').classList.remove('active');
```

2023-01-09 13:45 UTC, dgrammatiko commented on installation/template/js/setup.js
> +        progress_text.setAttribute('role', 'alert');
@laoneo can you confirm that it actually solves the problem?

2023-01-09 13:48 UTC, Hackwar commented on installation/template/js/setup.js
> +        progress_text.setAttribute('role', 'alert');
That code is run 16 lines further down.

2023-01-09 14:19 UTC, dgrammatiko commented on installation/template/js/setup.js
> +        progress_text.setAttribute('role', 'alert');
Nope, that code is behind an if statement, anyways, here's the code that fixes it:

<details>
<summary>setup.js</summary>

```js
/**
 * @package     Joomla.Installation
 * @copyright   (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

/**
 * Method to set the language for the installation UI via AJAX
 *
 * @return {Boolean}
 */
Joomla.setlanguage = function(form) {
  Joomla.removeMessages();
  document.body.appendChild(document.createElement('joomla-core-loader'));

  Joomla.request({
    url: Joomla.baseUrl,
    method: 'POST',
    data: new URLSearchParams(new FormData(form)),
    perform: true,
    onSuccess: function(response, xhr){
      response = JSON.parse(response);
      Joomla.replaceTokens(response.token);
      var loaderElement = document.querySelector('joomla-core-loader');

      if (response.messages) {
        Joomla.renderMessages(response.messages);
      }

      if (response.error) {
        loaderElement.parentNode.removeChild(loaderElement);
        Joomla.renderMessages({'error': [response.message]});
      } else {
        loaderElement.parentNode.removeChild(loaderElement);
        Joomla.goToPage(response.data.view, true);
      }
    },
    onError:   function(xhr){
      var loaderElement = document.querySelector('joomla-core-loader');
      loaderElement.parentNode.removeChild(loaderElement);
      try {
        var r = JSON.parse(xhr.responseText);
        Joomla.replaceTokens(r.token);
        alert(r.message);
      } catch (e) {}
    }
  });

  return false;
};

Joomla.checkInputs = function() {
  document.getElementById('jform_admin_password2').value = document.getElementById('jform_admin_password').value;

  var inputs = [].slice.call(document.querySelectorAll('input[type="password"], input[type="text"], input[type="email"], select')),
    state = true;
  inputs.forEach(function(item) {
    if (!item.valid) state = false;
  });
  document.getElementById('progress-text').classList.remove('error');
  document.getElementById('progress-text').setAttribute('role', 'status');
  document.getElementById('progress-text').innerText = Joomla.Text._('INSTL_IN_PROGRESS');
  document.getElementById('progressbar').setAttribute('value', 0);

  // Reveal everything
  document.getElementById('installStep1').classList.add('active');
  document.getElementById('installStep2').classList.add('active');
  document.getElementById('installStep3').classList.add('active');

  if (Joomla.checkFormField(['#jform_site_name', '#jform_admin_user', '#jform_admin_email', '#jform_admin_password', '#jform_db_type', '#jform_db_host', '#jform_db_user', '#jform_db_name'])) {
    Joomla.checkDbCredentials();
  }
};

Joomla.checkDbCredentials = function() {
  const progress = document.getElementById('progressbar');
  const progress_text = document.getElementById('progress-text');
  var form = document.getElementById('adminForm');

  function revealBtns(taskNo) {
    for (let i = 1; i <= taskNo; i++) {
      document.getElementById(`installStep${i}`).classList.add('active');
    }
  }
  // Reveal everything
  revealBtns(4);
  progress_text.innerText = Joomla.Text._('INSTL_IN_PROGRESS');

  Joomla.request({
    method: "POST",
    url : Joomla.installationBaseUrl + '?task=installation.dbcheck&format=json',
    data: new URLSearchParams(new FormData(form)),
    perform: true,
    headers: {'Content-Type': 'application/x-www-form-urlencoded'},
    onSuccess: function(response, xhr){
      try {
        response = JSON.parse(response);
      } catch (e) {
        revealBtns(4);
        progress_text.setAttribute('role', 'alert');
        progress_text.classList.add('error');
        progress_text.innerText = response;
        console.error('Error in DB Check Endpoint');
        console.error(response);
        Joomla.renderMessages({'error': [Joomla.Text._('INSTL_DATABASE_RESPONSE_ERROR')]});

        return false;
      }

      if (response.messages) {
        Joomla.renderMessages(response.messages);
      }

      Joomla.replaceTokens(response.token);

      if (response.error) {
        revealBtns(4);
        progress_text.innerText = Joomla.Text._('INSTL');
        Joomla.renderMessages({'error': [response.message]});
      } else if (response.data && response.data.validated === true) {
        // Run the installer - we let this handle the redirect for now
        // @todo: Convert to promises
        progress.setAttribute('value', parseInt(progress.getAttribute('value')) + 1);
        progress_text.innerText = Joomla.Text._('INSTL_IN_PROGRESS');
        Joomla.install(['create', 'populate1', 'populate2', 'populate3', 'custom1', 'custom2', 'config'], form);
      }
    },
    onError:   function(xhr){
      Joomla.renderMessages([['', Joomla.Text._('JLIB_DATABASE_ERROR_DATABASE_CONNECT', 'A Database error occurred.')]]);
      progress_text.setAttribute('role', 'alert');
      progress_text.classList.add('error');
      progress_text.innerText = response.message;
      //Install.goToPage('summary');

      try {
        var r = JSON.parse(xhr.responseText);
        Joomla.replaceTokens(r.token);
        alert(r.message);
      } catch (e) {
      }
      revealBtns(4);
    }
  });
};


(function() {
  // Merge options from the session storage
  if (sessionStorage && sessionStorage.getItem('installation-data')) {
    Joomla.extend(this.options, sessionStorage.getItem('installation-data'));
  }

  Joomla.pageInit();
  var el = document.querySelector('.nav-steps.hidden');
  if (el) {
    el.classList.remove('hidden');
  }

  // Focus to the next field
  if (document.getElementById('jform_site_name')) {
    document.getElementById('jform_site_name').focus();
  }

  // Select language
  var languageEl = document.getElementById('jform_language');

  if (languageEl) {
    languageEl.addEventListener('change', function(e) {
      var form = document.getElementById('languageForm');
      Joomla.setlanguage(form)
    })
  }

  if (document.getElementById('step1')) {
    document.getElementById('step1').addEventListener('click', function(e) {
      e.preventDefault();
      if (Joomla.checkFormField(['#jform_site_name'])) {
        if (document.getElementById('languageForm')) {
          document.getElementById('languageForm').classList.add('hidden');
        }
        if (document.getElementById('installStep2')) {
          document.getElementById('installStep2').classList.add('active');
          document.getElementById('installStep1').classList.remove('active');

          // Focus to the next field
          if (document.getElementById('jform_admin_user')) {
            document.getElementById('jform_admin_user').focus();
          }
        }
      }
    })
  }

  if (document.getElementById('step2')) {
    document.getElementById('step2').addEventListener('click', function(e) {
      e.preventDefault();
      if (Joomla.checkFormField(['#jform_admin_user', '#jform_admin_email', '#jform_admin_password'])) {
        if (document.getElementById('installStep3')) {
          document.getElementById('installStep3').classList.add('active');
          document.getElementById('installStep2').classList.remove('active');
          document.getElementById('setupButton').classList.remove('hidden');

          Joomla.makeRandomDbPrefix();

          // Focus to the next field
          if (document.getElementById('jform_db_type')) {
            document.getElementById('jform_db_type').focus();
          }
        }
      }
    });

    document.getElementById('setupButton').addEventListener('click', function(e) {
      e.preventDefault();
      e.stopPropagation();
      Joomla.checkInputs();
    })
  }
})();

```
</details>

<summary>template.js</summary>

```js
/**
 * @package     Joomla.Installation
 * @copyright   (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
(function() {
  // M [...]

2023-01-09 14:21 UTC, MacJoom commented
> There is still no way to get back for me when an error happens: ![image](https://user-images.githubusercontent.com/251072/211320866-0453a56f-018e-4ebd-9a39-b727f6a22ac9.png)
> 
> @MacJoom how could you go back?

Back Button worked for me (Firefox 108, Windows 10)

2023-01-09 14:30 UTC, laoneo commented
When I open directly the installation screen, then the back button in the browser is greyed out. I guess we have to wait for the suggestion from @dgrammatiko.

2023-01-09 14:31 UTC, dgrammatiko commented
@laoneo can you try this: https://github.com/joomla/joomla-cms/pull/29376?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDkwNjQxMjg1NTozODg5Mzc1#discussion_r1064690554

2023-01-09 14:45 UTC, MacJoom commented
I now did some tests with the latest j4installimprove, npm ci done - and now the back button does not work anymore (i was sure it worked before)
However the reload button works...

2023-01-09 14:50 UTC, dgrammatiko commented on installation/template/js/setup.js
> +        progress_text.setAttribute('role', 'alert');
@Hackwar check https://github.com/Hackwar/joomla-cms/pull/57

2023-01-09 20:31 UTC, Hackwar commented on installation/template/js/setup.js
> +        progress_text.setAttribute('role', 'alert');
Thanks. Do I have to do more than merging?

2023-01-09 20:32 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 2e7fbe21a40c9125e72123bb9ce0df693c93ce8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2023-01-09 20:37 UTC, dgrammatiko commented on installation/template/js/setup.js
> +        progress_text.setAttribute('role', 'alert');
@Hackwar you're welcome. I think the only thing needed are couple tests here, maybe @laoneo and @MacJoom ?

2023-01-10 06:56 UTC, laoneo commented
Now the progress bar is not appearing at all anymore. After I entered the credentials, the whole form is displayed and then comes the spinning wheel.

2023-01-10 08:28 UTC, MacJoom commented
Same with me ... - if i enter wrong db credentials  the error message comes in the alert area on the top of the window but the user is at the bottom of the page so he usually doesn't see the message and thinks that nothing happened until he eventually scrolls up. On correct credentials the progress is not shown anymore, just the joomla logo for a short time and the end message.

2023-01-10 08:30 UTC, dgrammatiko commented
> After I entered the credentials, the whole form is displayed and then comes the spinning wheel.

That shouldn't happen, I'll have a look later today

2023-01-10 09:06 UTC, angieradtke commented
Hello together,

maybe it is helpful to read again what was important to us ( A11y-Team) : 
https://der-auftritt.de/en/insights/progress-en.html

I think I had already written somewhere that it would be better to add the installation steps not hardcoded  in an array. (I can't find that anymore.) Then we have  control over the error messages  in one place/ function . This makes the code less and easier to maintain and debug. 

Wouldn't that be possible? @dgrammatiko

2023-01-10 09:51 UTC, Hackwar commented
I reverted the changes from @dgrammatiko and did some more fixes... Regarding @angieradtke, we discussed that and solved the topic.

Please check again. It should now work as expected.

2023-01-10 10:14 UTC, laoneo commented
Looks ok now, guess we have to wait for another test

2023-01-10 10:15 UTC, laoneo commented on installation/src/Controller/InstallationController.php
> +        else {
```suggestion
        } else {
```

2023-01-10 11:07 UTC, MacJoom commented
Tested OK now - but i got the same problem as Harald within "Installing Additional Language" the "install selected language" button does not work and throws `template.js?2866e0b7fb3eead87f64538845ad119e:206 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at onSuccess (template.js?2866e0b7fb3eead87f64538845ad119e:206:18)
    at n.onreadystatechange (core.min.js?2866e0b7fb3eead87f64538845ad119e:1:6213)`

I tried with a fresh checkout of 4.3-dev (jinstall done) - and did not have this problem

2023-01-15 21:43 UTC, Hackwar commented
Indeed, @MacJoom & @HLeithner there was an issue with language installation. I fixed the code. So we need yet another round of tests. ***sigh***

2023-01-16 11:16 UTC, MacJoom commented
@Hackwar - Thank you for your work! - Tested "better" now - the "install selected language" button works now, but there is delay for a few seconds after clicking the  "install selected language" button where it seems that nothing happens - i guess the installation is done in this time - then the joomla logo overlay comes up for a very short time - and then the installation is complete. It's a detail and i hope it's an easy fix.
crosschecked with 4.3-dev: the joomla logo overlay comes right after clicking the button and stays during installation.

2023-04-04 09:06 UTC, HLeithner commented
Can you please rebase this on 5.0, I know it's annoying, but better have it better tested in a major release then less tested in a minor...

On my other wish list for the installer would be that the error handling needs to be much better/userfriendly :-(

2023-08-26 09:54 UTC, fancyFranci commented
Its working, but when there was an error message before, it appears for a second above the progress bar. Like documented in my video. Would be nice if its not visible, because at first I thought the installation would progress despite the error. 

![screen shot 2023-08-26 at 09 53 32](https://issues.joomla.org/uploads/1/f2666d73385bafc27ecf7c078cb93c0d.gif)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2023-08-26 10:04 UTC, fancyFranci commented
Ok I forgot to build js and css, but even after that the error still appears. The progress bar is just prettier.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2023-08-26 10:46 UTC, HLeithner commented
did you used the prebuilt zip files? @fancyFranci

2023-08-26 11:03 UTC, HLeithner commented
@fancyFranci can't replicate your issue

2023-08-26 11:05 UTC, HLeithner commented
I have tested this item :white_check_mark: successfully on 2e7fbe21a40c9125e72123bb9ce0df693c93ce8c<br /><br />still works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29376">issues.joomla.org/tracker/joomla-cms/29376</a>.</sub>

2023-08-26 11:08 UTC, fancyFranci commented
I can try again, but maybe that helps for replicating the issue: First I wrote a wrong database username like "rootz" and tried to install. Normal error message appears. I go back, fix it to "root" and install again. Then I have the behavirour like in my video.

2023-09-02 19:05 UTC, merged

2023-09-02 19:06 UTC, HLeithner commented
Tested it successfully with the download, in web and cli incl. language installation. I think we will get more tests with beta1

2023-09-02 19:06 UTC, HLeithner commented
thanks hannes