[4.0] poor man’s cron 3rd attempt
joomla/joomla-cms pull request #29592
Opened 2020-06-13 08:31 UTC by alikon

The last iteration of #25022, porting #22310 to 4.x

### Goal
a way to run scheduled "quick" tasks in approximately regular intervals

### Summary of Changes
- a new system plugin scheduler
- two new console command 

### How it works
In a normal hosting situation that would be job for cron, but if your hosting doesn’t offer cron, then a common solution in these cases is “poor man’s cron:” on every page load (`onAfterRespond`) the scheduler system plugin check if itself  is expected to run and  then trigger a new event `onExecuteScheduledTask`  then any job plugin wich listen to that event  check if itself  is expected to run and if so execute his task.  

### Testing Instructions (web)

- apply PR 
- System panel -> discover -> you'll find a new system plugin scheduler
- install it 
- set options, publish the plugin and save
for test only
Frequency (in minutes) set = 0 mean run every (`onAfterRespond`)

![Screenshot from 2019-05-28 18-55-57](https://user-images.githubusercontent.com/181681/58496527-5e52f900-817a-11e9-9aec-3e96347fd91c.png)

- install these 2 silly job plugin:
[plg_job_jobthree.zip](https://github.com/joomla/joomla-cms/files/4774301/plg_job_jobthree.zip)
[plg_job_jobone.zip](https://github.com/joomla/joomla-cms/files/4774283/plg_job_jobone.zip)

-  this one is an example on how to schedule an sql export
[plg_job_jobexportdb.zip](https://github.com/joomla/joomla-cms/files/4774291/plg_job_jobexportdb.zip)

-  job one simply sleep for 1 seconds		
-  job two simply sleep for 3 seconds

- set options, publish the plugin and save plugin ONE
Frequency (in unit) set 1
Unit of time set minute

 means that this plugin run 1xminute = every minute 
if `onExecuteScheduledTask`  has been triggered 

![Screenshot from 2019-05-30 18-55-18](https://user-images.githubusercontent.com/181681/58649498-896d5200-830c-11e9-823f-40c06f2d31f2.png)

- set options, publish the plugin and save plugin TWO
maybe use different  settings than ONE

### Expected result
depending on your (plugins) settings 
take a coffe/smoke/whatever :smile: 
randomly click a couple of  frontend pages
check the log file at  `yoursite/administrator/logs/joomla_web.php`
you'll see something like this 
```php
#
#<?php die('Forbidden.'); ?>
#Date: 2019-05-30 17:24:39 UTC
#Software: Joomla! 4.0.0-alpha10-dev Development [ Amani ] 16-May-2019 19:22 GMT

#Fields: datetime	priority clientip	category	message
2019-05-30T17:24:39+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2019-05-30T17:24:40+00:00	INFO 127.0.0.1	scheduler	Job>jobone Task#221 Processing Time: 1.01 seconds.
2019-05-30T17:24:43+00:00	INFO 127.0.0.1	scheduler	Job>jobtwo Task#166 Processing Time: 3.01 seconds.
2019-05-30T17:24:43+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#1564 Total Processing Time: 4.04 seconds.
2019-05-30T17:24:47+00:00	INFO 127.0.0.1	scheduler	Scheduler>start
2019-05-30T17:24:47+00:00	INFO 127.0.0.1	scheduler	Scheduler>stop>task#1565 Total Processing Time: 0.04 seconds.
```

 **1st run** 
the scheduler plugin (wich runs always frequency=0) trigger the `onExecuteScheduledTask` event
so plugin ONE and plugin TWO  are executed (cause no previous run)

**2nd  run**
the scheduler plugin (wich runs always frequency=0) trigger the `onExecuteScheduledTask` event
but this time both plugin have an expected scheduled time (for example ONE each 1min TWO each 5min) 
the 2nd run was at 17:24:47+00:00	
the 1st run was at 17:24:43+00:00
they have only 4 seconds of difference form the previous execution so both plugin are not expected to run

**3rd  run** 
it depends on how fast you click & settings

### Testing Instructions (webcron)
on scheduler system plugin
set Webcron to yes/enable 
set Key to mywebcronactivationkey
then use `yoursiteurl/index.php?webcronkey=mywebcronactivationkey` as the url for webcron services to be triggred

### Testing Instructions (cli/cron)
Go to the cli folder of your website and run
`php joomla.php job:run` 
`php joomla.php job:list`
![Screenshot from 2019-05-30 20-03-51](https://user-images.githubusercontent.com/181681/58653556-3f896980-8316-11e9-89aa-f8c3607ae779.png)

check the log file at yoursite/administrator/logs/joomla_cli.php

### Actual result
N/A

### Additional comments

it can be used for tasks like:

- deleteExpiredConsents
- remindExpiringConsents
- logRotation
- updateNotifications
- sessionGC
- etc...

### Documentation Changes Required
yes

2020-06-13 09:48 UTC, ceford commented
I am getting this in the joomla_web.php log:
#
#<?php die('Forbidden.'); ?>
#Date: 2020-06-13 09:28:59 UTC
#Software: Joomla! 4.0.0-beta2-dev Development [ Mañana ] 30-May-2020 21:13 GMT

#Fields: datetime	priority clientip	category	message
2020-06-13T09:28:59+00:00	INFO ::1	scheduler	PLG_SYSTEM_SCHEDULER_LOCKED
2020-06-13T09:30:05+00:00	INFO ::1	scheduler	PLG_SYSTEM_SCHEDULER_LOCKED
2020-06-13T09:32:07+00:00	INFO ::1	scheduler	PLG_SYSTEM_SCHEDULER_LOCKED
2020-06-13T09:36:45+00:00	INFO ::1	scheduler	PLG_SYSTEM_SCHEDULER_LOCKED

The CLI gives this:

Scheduler
=========
Scheduler started
 * Job: jobthree In Error
 * Job: jobone In Error
 * Job: jobexportdb In Error                                                                        
 [OK] Scheduler finished in 0.009                                               
                                                                                
joomla_cli.php log has this:
#
#<?php die('Forbidden.'); ?>
#Date: 2020-06-13 09:38:03 UTC
#Software: Joomla! 4.0.0-beta2-dev Development [ Mañana ] 30-May-2020 21:13 GMT

#Fields: datetime	priority clientip	category	message
2020-06-13T09:38:03+00:00	INFO -	scheduler	Scheduler started
2020-06-13T09:38:03+00:00	INFO -	scheduler	Scheduler tooks:0.008

My System - Job Scheduler plugin is showing Yes/No radio buttons, not a slider as in your screen grab. So has this mornings Nightly Build update not worked properly for me?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-13 09:52 UTC, alikon commented
@ceford  most probably i've messed up something making the pr....let me check/re-check , and sorry for the extra work

2020-06-13 10:30 UTC, richard67 commented
Update SQL script for adding the new table seems to be missing.

2020-06-13 10:51 UTC, alikon commented
are this https://github.com/joomla/joomla-cms/pull/29592/files#diff-fedf44f6151687d314fc4f3cab068494 not enough

2020-06-13 12:00 UTC, richard67 commented
@alikon Yes, seems I've missed them when checking on smartphone. But the insert statements into the extensions table are missing the meanwhile (since your last version of the PR) invented new column "locked". Could you check and if necessary correct?

2020-06-13 12:56 UTC, richard67 commented
@alikon See [https://github.com/alikon/joomla-cms/pull/69](https://github.com/alikon/joomla-cms/pull/69).

2020-06-13 15:08 UTC, particthistle commented
I have tested this item :white_check_mark: successfully on 1c1c740e179c167f49bf473ecefecbc2eef44b94<br /><br />**Tested web version**. Had to apply database fix using System > Database first.

Changed the frequency to 5 min on Job 3 to test the frequency cycle, and sleep time to 10 seconds, which is why the figures for Job>jobthree Task#3 is delayed compared to the other instances.

Refreshed page a few times a few minutes apart. Log shown below.

```
#Date: 2020-06-13 14:47:47 UTC
#Software: Joomla! 4.0.0-beta2-dev Development [ Ma単ana ] 30-May-2020 21:13 GMT

#Fields: datetime	priority clientip	category	message
2020-06-13T14:47:47+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:47:52+00:00	INFO 101.116.160.42	scheduler	Job>jobthree Task#1 Return Code is: 0 Processing Time: 5.06 seconds.
2020-06-13T14:47:53+00:00	INFO 101.116.160.42	scheduler	Job>jobone Task#1 Return Code is: 0 Processing Time: 1.06 seconds.
2020-06-13T14:47:53+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 6.17 seconds.
2020-06-13T14:48:05+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:48:05+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 0.03 seconds.
2020-06-13T14:48:57+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:49:01+00:00	INFO 101.116.160.42	scheduler	PLG_SYSTEM_SCHEDULER_LOCKED
2020-06-13T14:49:02+00:00	INFO 101.116.160.42	scheduler	Job>jobthree Task#2 Return Code is: 0 Processing Time: 5.03 seconds.
2020-06-13T14:49:03+00:00	INFO 101.116.160.42	scheduler	Job>jobone Task#2 Return Code is: 0 Processing Time: 1.04 seconds.
2020-06-13T14:49:03+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 6.11 seconds.
2020-06-13T14:49:05+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:49:05+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 0.04 seconds.
2020-06-13T14:50:42+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:50:43+00:00	INFO 101.116.160.42	scheduler	Job>jobone Task#3 Return Code is: 0 Processing Time: 1.02 seconds.
2020-06-13T14:50:43+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 1.05 seconds.
2020-06-13T14:51:42+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:51:42+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 0.06 seconds.
2020-06-13T14:51:56+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:51:57+00:00	INFO 101.116.160.42	scheduler	Job>jobone Task#4 Return Code is: 0 Processing Time: 1.04 seconds.
2020-06-13T14:51:57+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 1.07 seconds.
2020-06-13T14:53:40+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:53:41+00:00	INFO 101.116.160.42	scheduler	Job>jobone Task#5 Return Code is: 0 Processing Time: 1.05 seconds.
2020-06-13T14:53:41+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 1.11 seconds.
2020-06-13T14:59:30+00:00	INFO 101.116.160.42	scheduler	Starting Scheduler
2020-06-13T14:59:40+00:00	INFO 101.116.160.42	scheduler	Job>jobthree Task#3 Return Code is: 0 Processing Time: 10.03 seconds.
2020-06-13T14:59:41+00:00	INFO 101.116.160.42	scheduler	Job>jobone Task#6 Return Code is: 0 Processing Time: 1.02 seconds.
2020-06-13T14:59:41+00:00	INFO 101.116.160.42	scheduler	Scheduler tooks 11.10 seconds.
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-13 17:34 UTC, Quy commented on administrator/language/en-GB/plg_system_scheduler.ini
> +PLG_SYSTEM_SCHEDULER_TIMEOUT_DESC="How often should the scheduler run."
Remove description. Provides no additional information.

2020-06-13 17:34 UTC, Quy commented on administrator/language/en-GB/plg_system_scheduler.ini
> +PLG_SYSTEM_SCHEDULER_WEBCRON_DESC="Webcron services enable"
Remove description. Provides no additional information.

2020-06-13 17:34 UTC, Quy commented on administrator/language/en-GB/plg_system_scheduler.ini
> +PLG_SYSTEM_SCHEDULER_WEBCRONKEY_DESC="Webcron service activation key"
Remove description. Provides no additional information.

2020-06-13 17:34 UTC, Quy commented on administrator/language/en-GB/plg_system_scheduler.ini
> +PLG_SYSTEM_SCHEDULER_WEBCRON_LABEL="Webcron"
```suggestion
PLG_SYSTEM_SCHEDULER_WEBCRON_LABEL="Webcron Activation Key"
```

2020-06-13 19:42 UTC, ceford commented
I have tested this item :red_circle: unsuccessfully on 7d32bd5fc58450a5fb7c98c076452e728070490a<br /><br />Took the tip and updated the database before installing patch. Ran a few tests and got sensible output. joomla_cli.php:

2020-06-13T19:22:53+00:00	INFO -	scheduler	Scheduler started
2020-06-13T19:22:53+00:00	INFO -	scheduler	Scheduler tooks:0.008
2020-06-13T19:24:07+00:00	INFO -	scheduler	Scheduler started
2020-06-13T19:24:08+00:00	INFO -	scheduler	Job>jobone Task#3 Return Code is: 0 Processing Time: 1.02 seconds.
2020-06-13T19:24:08+00:00	INFO -	scheduler	Scheduler tooks:1.026
2020-06-13T19:24:40+00:00	INFO -	scheduler	Scheduler started
2020-06-13T19:24:45+00:00	INFO -	scheduler	Job>jobthree Task#2 Return Code is: 0 Processing Time: 5.03 seconds.
2020-06-13T19:24:45+00:00	INFO -	scheduler	Scheduler tooks:5.036
2020-06-13T19:29:52+00:00	INFO -	scheduler	Scheduler started
2020-06-13T19:29:57+00:00	INFO -	scheduler	Job>jobthree Task#3 Return Code is: 0 Processing Time: 5.03 seconds.
2020-06-13T19:29:58+00:00	INFO -	scheduler	Job>jobone Task#4 Return Code is: 0 Processing Time: 1.01 seconds.
2020-06-13T19:30:01+00:00	INFO -	scheduler	Job>jobexportdb Task#2 Return Code is: 0 Processing Time: 3.65 seconds.
2020-06-13T19:30:01+00:00	INFO -	scheduler	Scheduler tooks:9.708

Click Tested successfully - but one last rerun of CLI ended up with a long stack trace. Looks as though it is trying to write a db.zip file to somewhere without write access. Here is the first part:

Scheduler
=========

Scheduler started

PHP Notice:  Undefined variable: directory in /Users/ceford/Sites/j4beta2/plugins/job/jobexportdb/jobexportdb.php on line 120
PHP Stack trace:
PHP   1. {main}() /Users/ceford/Sites/j4beta2/cli/joomla.php:0
PHP   2. Joomla\CMS\Application\ConsoleApplication->execute() /Users/ceford/Sites/j4beta2/cli/joomla.php:69
PHP   3. Joomla\CMS\Application\ConsoleApplication->execute() /Users/ceford/Sites/j4beta2/libraries/src/Application/ConsoleApplication.php:227
PHP   4. Joomla\CMS\Application\ConsoleApplication->doExecute() /Users/ceford/Sites/j4beta2/libraries/vendor/joomla/console/src/Application.php:438
PHP   5. Joomla\CMS\Application\ConsoleApplication->doExecute() /Users/ceford/Sites/j4beta2/libraries/src/Application/ConsoleApplication.php:184
PHP   6. Joomla\CMS\Application\ConsoleApplication->runCommand() /Users/ceford/Sites/j4beta2/libraries/vendor/joomla/console/src/Application.php:393
PHP   7. Joomla\CMS\Console\SchedulerCommand->execute() /Users/ceford/Sites/j4beta2/libraries/vendor/joomla/console/src/Application.php:1165
PHP   8. Joomla\CMS\Console\SchedulerCommand->doExecute() /Users/ceford/Sites/j4beta2/libraries/vendor/joomla/console/src/Command/AbstractCommand.php:235
PHP   9. Joomla\CMS\Console\SchedulerCommand->triggerJobs() /Users/ceford/Sites/j4beta2/libraries/src/Console/SchedulerCommand.php:94
PHP  10. Joomla\CMS\Application\ConsoleApplication->triggerEvent() /Users/ceford/Sites/j4beta2/libraries/src/Console/SchedulerCommand.php:142
PHP  11. Joomla\Event\Dispatcher->dispatch() /Users/ceford/Sites/j4beta2/libraries/src/Application/EventAware.php:111
PHP  12. PlgJobJobexportdb->Joomla\CMS\Plugin\{closure:/Users/ceford/Sites/j4beta2/libraries/src/Plugin/CMSPlugin.php:267-290}() /Users/ceford/Sites/j4beta2/libraries/vendor/joomla/event/src/Dispatcher.php:495
PHP  13. PlgJobJobexportdb->onExecuteScheduledTask() /Users/ceford/Sites/j4beta2/libraries/src/Plugin/CMSPlugin.php:285
PHP  14. PlgJobJobexportdb->jobexportdbTask() /Users/ceford/Sites/j4beta2/plugins/job/jobexportdb/jobexportdb.php:85
PHP Warning:  file_put_contents(/j4-beta_DB_2020-06-13T19-29-58.zip): failed to open stream: Read-only file system in /Users/ceford/Sites/j4beta2/libraries/vendor/joomla/filesystem/src/File.php on line 232
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-14 06:12 UTC, alikon commented
@ceford  there was a silly error on the exportdb demo plugin fixed now 
[plg_job_jobexportdb.zip](https://github.com/joomla/joomla-cms/files/4775938/plg_job_jobexportdb.zip)

2020-06-14 06:28 UTC, alikon commented on administrator/language/en-GB/plg_system_scheduler.ini
> +PLG_SYSTEM_SCHEDULER_TIMEOUT_DESC="How often should the scheduler run."
done

2020-06-14 06:29 UTC, alikon commented on administrator/language/en-GB/plg_system_scheduler.ini
> +PLG_SYSTEM_SCHEDULER_WEBCRON_DESC="Webcron services enable"
done

2020-06-14 06:29 UTC, alikon commented on administrator/language/en-GB/plg_system_scheduler.ini
> +PLG_SYSTEM_SCHEDULER_WEBCRONKEY_DESC="Webcron service activation key"
done

2020-06-14 07:29 UTC, ceford commented
I have tested this item :white_check_mark: successfully on 4b5150514f5adc70aa16add19b70716981fb7d64<br /><br />A few comments
1 The web log is OK:
2020-06-14T06:54:36+00:00	INFO ::1	scheduler	Starting Scheduler
2020-06-14T06:54:41+00:00	INFO ::1	scheduler	Job>jobthree Task#7 Return Code is: 0 Processing Time: 5.08 seconds.
2020-06-14T06:54:42+00:00	INFO ::1	scheduler	Job>jobone Task#10 Return Code is: 0 Processing Time: 1.08 seconds.
2020-06-14T06:54:45+00:00	INFO ::1	scheduler	Job>jobexportdb Task#5 Return Code is: 0 Processing Time: 2.93 seconds.
2020-06-14T06:54:45+00:00	INFO ::1	scheduler	Scheduler tooks 9.14 seconds.
**Except** that tooks should be took.
2. The cli log is missing seconds:
2020-06-14T06:38:07+00:00	INFO -	scheduler	Scheduler started
2020-06-14T06:38:12+00:00	INFO -	scheduler	Job>jobthree Task#6 Return Code is: 0 Processing Time: 5.01 seconds.
2020-06-14T06:38:13+00:00	INFO -	scheduler	Job>jobone Task#9 Return Code is: 0 Processing Time: 1.02 seconds.
2020-06-14T06:38:16+00:00	INFO -	scheduler	Job>jobexportdb Task#4 Return Code is: 0 Processing Time: 2.59 seconds.
2020-06-14T06:38:16+00:00	INFO -	scheduler	Scheduler tooks:8.628
3. On documentation
I have been revising Help screens recently and this has reminded me that plugins still need some work. At the moment all plugins share the same Help screen URL. I pulled out the list of 92 plugins into a separate chunk but that is still too long and does not yet have J4 images. The best solution is a separate chunk for each plugin. Another week locked down/up could swing it. But where would the cli documentation be located?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-14 07:58 UTC, alikon commented
should be here https://docs.joomla.org/Category:Joomla_CLI

2020-06-14 13:47 UTC, Quy commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +	public const JOB_KO_RUN = 3;
Should `KO` be `NO`?

2020-06-14 13:55 UTC, Quy commented on administrator/language/en-GB/plg_actionlog_joomla.ini
> +PLG_ACTIONLOG_JOOMLA_PLUGIN_JOB="Executed the <a href='index.php?option=com_plugins&task=plugin.edit&extension_id={eid}'> {job}</a> in {duration} with  return code {status}"
```suggestion
PLG_ACTIONLOG_JOOMLA_PLUGIN_JOB="Executed the <a href='index.php?option=com_plugins&task=plugin.edit&extension_id={eid}'> {job}</a> in {duration} with return code {status}"
```

2020-06-14 14:42 UTC, richard67 commented
@alikon Your PR got conflicts, very likely due to a recent merge in 4.0-dev. Can you solve them? Let me know if you need some help with that. Thanks in advance.

2020-06-14 14:44 UTC, alikon commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +	public const JOB_KO_RUN = 3;
matter of taste

2020-06-14 14:46 UTC, richard67 commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +	public const JOB_KO_RUN = 3;
But it should be consistent, or not? The others are `JOB_NO_...`.

2020-06-14 14:47 UTC, alikon commented
conflict solved

2020-06-14 15:13 UTC, alikon commented
That constant doesn't mean no execution but means execution ko is with
errors

Il dom 14 giu 2020, 16:47 Richard Fath <notifications@github.com> ha
scritto:

> *@richard67* commented on this pull request.
> ------------------------------
>
> In administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> <https://github.com/joomla/joomla-cms/pull/29592#discussion_r439837201>:
>
> > +	 * Exit Code For no time to run
> +	 * @since
> +	 */
> +	public const JOB_NO_TIME = 1;
> +
> +	/**
> +	 * Exit Code For lock failure
> +	 * @since
> +	 */
> +	public const JOB_NO_LOCK = 2;
> +
> +	/**
> +	 * Exit Code For execution failure
> +	 * @since
> +	 */
> +	public const JOB_KO_RUN = 3;
>
> But it should be consistent, or not? The others are JOB_NO_....
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/29592#discussion_r439837201>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABMLMOZVTACMX5BZH3PRPLRWTPGVANCNFSM4N44RQ3Q>
> .
>

2020-06-14 15:24 UTC, richard67 commented
I see .. well it looks like a typo if you don't know that.

2020-06-14 16:13 UTC, Quy commented on administrator/language/en-GB/plg_system_scheduler.ini
> +PLG_SYSTEM_SCHEDULER_WEBCRONKEY_LABEL="Key"
```suggestion
PLG_SYSTEM_SCHEDULER_WEBCRON_LABEL="Webcron"
PLG_SYSTEM_SCHEDULER_WEBCRONKEY_LABEL="Activation Key"
```

2020-06-14 16:16 UTC, Quy commented on plugins/system/scheduler/scheduler.xml
> +					class="switcher"
```suggestion
					layout="joomla.form.field.radio.switcher"
```

2020-06-14 16:31 UTC, Quy commented on plugins/system/scheduler/scheduler.xml
> +					name="timeout"
Should this be added `showon="webcron:1"` and move it after activation key field?

2020-06-14 16:33 UTC, Quy commented
Add to the list of core extensions.

2020-06-14 16:38 UTC, alikon commented on plugins/system/scheduler/scheduler.xml
> +					name="timeout"
No this not depend on webcron

2020-06-14 16:45 UTC, alikon commented
> Add to the list of core extensions.

Done

2020-06-14 17:08 UTC, Quy commented on administrator/components/com_actionlogs/config.xml
> +			label="COM_ACTIONLOGS_JOB_LOGGING_LABEL"
Missing language string.

2020-06-14 19:02 UTC, alikon commented on administrator/components/com_actionlogs/config.xml
> +			label="COM_ACTIONLOGS_JOB_LOGGING_LABEL"
oops

2020-06-14 19:06 UTC, richard67 commented on administrator/language/en-GB/com_actionlogs.ini
> +COM_ACTIONLOGS_JOB_LOGGING_LABEL="Log jobs"
Please alpha order ... "J" comes after "I".

2020-06-15 07:12 UTC, toivo commented
I have tested this item :white_check_mark: successfully on d5d517d644dbcdd3ab8b7368e99019cb0e248d40<br /><br />Tested successfully in Beta2-dev of 15 May.
Test environment:  Wampserver 3.2.2 Apache 2.4.43a MySQL 8.0.20 PHP 7.4.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-16 20:56 UTC, Quy commented on plugins/system/scheduler/scheduler.php
> +				Text::_('PLG_SYSTEM_SCHEDULER_LOCKED'),
Missing language string.

2020-06-16 20:58 UTC, Quy commented on administrator/language/en-GB/com_actionlogs.ini
> +COM_ACTIONLOGS_JOB_LOGGING_LABEL="Log jobs"
```suggestion
COM_ACTIONLOGS_JOB_LOGGING_LABEL="Log Jobs"
```

2020-06-16 21:01 UTC, Quy commented on libraries/src/Console/SchedulerCommand.php
> +			'Scheduler took:' . round(microtime(true) - $this->time, 3), Log::INFO, 'scheduler'
```suggestion
			'Scheduler took: ' . round(microtime(true) - $this->time, 3), Log::INFO, 'scheduler'
```

2020-06-16 21:03 UTC, brianteeman commented on administrator/language/en-GB/com_actionlogs.ini
> +COM_ACTIONLOGS_JOB_LOGGING_LABEL="Log jobs"
I havent checked the code but based on the string above shouldn't this be Job Logs

2020-06-16 21:05 UTC, Quy commented on administrator/language/en-GB/com_actionlogs.ini
> +COM_ACTIONLOGS_JOB_LOGGING_LABEL="Log jobs"
Same 

![29592](https://user-images.githubusercontent.com/368084/84828102-5d397780-afda-11ea-8b8e-dbd14a60af62.png)

2020-06-20 19:30 UTC, richard67 commented
@alikon Could you check Quy‘s review comments?

2020-06-21 08:43 UTC, alikon commented on administrator/language/en-GB/com_actionlogs.ini
> +COM_ACTIONLOGS_JOB_LOGGING_LABEL="Log jobs"
changed to "_Job Logs_"

2020-06-21 08:46 UTC, alikon commented on plugins/system/scheduler/scheduler.php
> +				Text::_('PLG_SYSTEM_SCHEDULER_LOCKED'),
added

2020-06-21 08:47 UTC, alikon commented
@richard67 done

2020-06-21 15:19 UTC, richard67 commented
@toivo Could you repeat your test? Thanks in advance.

2020-06-21 15:19 UTC, richard67 commented
@ceford Could you repeat your test? Thanks in advance.

2020-06-21 15:32 UTC, richard67 commented
@alikon When having applied the patch and the update SQL so that the new plugin is enabled and configured, but not having installed any of the jobs plugins yet, and am using the cli, then I get following for the `job:run` command:

![j4-pr-29592_cli-error](https://user-images.githubusercontent.com/7413183/85228665-fefb0300-b3e4-11ea-974c-177a987ffde5.png)

The `jobs:list` command works well, it lists no jobs, which is correct.

@ceford @toivo Please wait with testing, there might be some correction necessary.

2020-06-21 15:36 UTC, richard67 commented
@alikon If you add one line `$text = [];` before the `foreach ($results as $run)`, and of course one empty line between those for CS, then it works. Could you fix that?

2020-06-21 15:37 UTC, richard67 commented on libraries/src/Console/SchedulerCommand.php
> +		foreach ($results as $run)
```suggestion
		$text = [];

		foreach ($results as $run)
```

2020-06-22 17:41 UTC, richard67 commented
@ceford @toivo Could you test again now after last correction? Thanks in advance.

2020-06-22 19:15 UTC, ceford commented
I have tested this item :white_check_mark: successfully on d5d517d644dbcdd3ab8b7368e99019cb0e248d40<br /><br />Worked as described. Here is my log:

2020-06-22T18:59:16+00:00	INFO ::1	scheduler	Starting Scheduler
2020-06-22T18:59:22+00:00	INFO ::1	scheduler	Job>jobthree Task#8 Return Code is: 0 Processing Time: 5.08 seconds.
2020-06-22T18:59:23+00:00	INFO ::1	scheduler	Job>jobone Task#11 Return Code is: 0 Processing Time: 1.08 seconds.
2020-06-22T18:59:26+00:00	INFO ::1	scheduler	Job>jobexportdb Task#6 Return Code is: 0 Processing Time: 3.08 seconds.
2020-06-22T18:59:26+00:00	INFO ::1	scheduler	Scheduler took 9.31 seconds.
2020-06-22T18:59:29+00:00	INFO ::1	scheduler	Starting Scheduler
2020-06-22T18:59:29+00:00	INFO ::1	scheduler	Scheduler took 0.02 seconds.
2020-06-22T18:59:31+00:00	INFO ::1	scheduler	Starting Scheduler
2020-06-22T18:59:31+00:00	INFO ::1	scheduler	Scheduler took 0.02 seconds.
2020-06-22T19:04:27+00:00	INFO ::1	scheduler	Starting Scheduler
2020-06-22T19:04:32+00:00	INFO ::1	scheduler	Job>jobthree Task#9 Return Code is: 0 Processing Time: 5.08 seconds.
2020-06-22T19:04:33+00:00	INFO ::1	scheduler	Job>jobone Task#12 Return Code is: 0 Processing Time: 1.08 seconds.
2020-06-22T19:04:33+00:00	INFO ::1	scheduler	Scheduler took 6.19 seconds.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-22 20:19 UTC, ceford commented
On documentation: I added a section to the System Plugin Help screen: 

https://docs.joomla.org/Chunk4x:Extensions_Plugin_Manager_Edit_System_Group

That will get into the Help screen when the /en version gets regenerated.

There is a link to a Tutorial on Writing A CLI Application.  Now looking for a tutorial on how to write a Job Plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-23 03:18 UTC, toivo commented
I have tested this item :white_check_mark: successfully on d5d517d644dbcdd3ab8b7368e99019cb0e248d40<br /><br />Tested successfully in Beta2-dev of 23 June.  The scheduler, webcron and cli/cron worked as expected. 

Here is the log file from webcron, joomla_web.php:
#
#<?php die('Forbidden.'); ?>
#Date: 2020-06-23 03:12:48 UTC
#Software: Joomla! 4.0.0-beta2-dev Development [ Mañana ] 30-May-2020 21:13 GMT

#Fields: datetime	priority clientip	category	message
2020-06-23T03:12:48+00:00	INFO 127.0.0.1	scheduler	Starting Scheduler
2020-06-23T03:12:49+00:00	INFO 127.0.0.1	scheduler	Job>jobexportdb Task#3 Return Code is: 0 Processing Time: 1.59 seconds.
2020-06-23T03:12:50+00:00	INFO 127.0.0.1	scheduler	Job>jobone Task#10 Return Code is: 0 Processing Time: 1.01 seconds.
2020-06-23T03:12:52+00:00	INFO 127.0.0.1	scheduler	Job>jobthree Task#4 Return Code is: 3 Processing Time: 2.01 seconds.
2020-06-23T03:12:52+00:00	INFO 127.0.0.1	scheduler	Scheduler took 4.64 seconds.
2020-06-23T03:13:13+00:00	INFO 127.0.0.1	scheduler	Starting Scheduler
2020-06-23T03:13:13+00:00	INFO 127.0.0.1	scheduler	Scheduler took 0.01 seconds.

Here is the log file from cli/cron, joomla_cli.php:
#
#<?php die('Forbidden.'); ?>
#Date: 2020-06-23 02:59:51 UTC
#Software: Joomla! 4.0.0-beta2-dev Development [ Mañana ] 30-May-2020 21:13 GMT

#Fields: datetime	priority clientip	category	message
2020-06-23T02:59:51+00:00	INFO -	scheduler	Scheduler started
2020-06-23T02:59:52+00:00	INFO -	scheduler	Job>jobexportdb Task#2 Return Code is: 0 Processing Time: 1.45 seconds.
2020-06-23T02:59:53+00:00	INFO -	scheduler	Job>jobone Task#9 Return Code is: 0 Processing Time: 1.03 seconds.
2020-06-23T02:59:55+00:00	INFO -	scheduler	Job>jobthree Task#3 Return Code is: 3 Processing Time: 2.01 seconds.
2020-06-23T02:59:55+00:00	INFO -	scheduler	Scheduler took: 4.52
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-23 06:35 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-06-23 06:37 UTC, alikon commented
thanks for the doc part

2020-06-23 13:29 UTC, Quy commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +use Joomla\CMS\Form\FormHelper;
```suggestion
use Joomla\CMS\Factory;
use Joomla\CMS\Form\Form;
use Joomla\CMS\Form\FormHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Log\Log;
use Joomla\CMS\Plugin\CMSPlugin;
use Joomla\CMS\Plugin\PluginHelper;
use Joomla\Registry\Registry;
```

2020-06-23 13:31 UTC, Quy commented on libraries/src/Service/Provider/Application.php
> +use Joomla\CMS\Console\JobListCommand;
```suggestion
use Joomla\CMS\Console\JobListCommand;
use Joomla\CMS\Console\Loader\WritableContainerLoader;
use Joomla\CMS\Console\Loader\WritableLoaderInterface;
```

2020-09-29 16:13 UTC, zero-24 requested changes
Please see the inline comments.

- update to use `__DEPLOY_VERSION__`.
- remove the hardcoded default `password` and make sure an empty key does not execute anything
-

2020-09-29 16:13 UTC, zero-24 commented on administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-06-13.sql
> +(0, 'plg_system_scheduler', 'plugin', 'scheduler', 'system', 0, 1, 1, 0, 1, '', '{"timeout":"3","webcron":"0","webcronkey":"mywebcronactivationkey","lastrun":"0","unit":"60","taskid":"0"}', 0, 0, '')
```suggestion
(0, 'plg_system_scheduler', 'plugin', 'scheduler', 'system', 0, 1, 1, 0, 1, '', '{"timeout":"3","webcron":"0","webcronkey":"","lastrun":"0","unit":"60","taskid":"0"}', 0, 0, '');
```

2020-09-29 16:13 UTC, zero-24 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-06-13.sql
> +(0, 'plg_system_scheduler', 'plugin', 'scheduler', 'system', 0, 1, 1, 0, 1, '', '{"timeout":"3","webcron":"0","webcronkey":"mywebcronactivationkey","lastrun":"0","unit":"60","taskid":"0"}', 0, 0, '')
```suggestion
(0, 'plg_system_scheduler', 'plugin', 'scheduler', 'system', 0, 1, 1, 0, 1, '', '{"timeout":"3","webcron":"0","webcronkey":"","lastrun":"0","unit":"60","taskid":"0"}', 0, 0, '');
```

2020-09-29 16:13 UTC, zero-24 commented on installation/sql/mysql/base.sql
> +(0, 'plg_system_scheduler', 'plugin', 'scheduler', 'system', 0, 1, 1, 0, 1, '', '{"timeout":"3","webcron":"0","webcronkey":"mywebcronactivationkey","lastrun":"0","unit":"60","taskid":"0"}', '', 0, 0)
```suggestion
(0, 'plg_system_scheduler', 'plugin', 'scheduler', 'system', 0, 1, 1, 0, 1, '', '{"timeout":"3","webcron":"0","webcronkey":"","lastrun":"0","unit":"60","taskid":"0"}', '', 0, 0);
```

2020-09-29 16:13 UTC, zero-24 commented on installation/sql/postgresql/base.sql
> +(0, 'plg_system_scheduler', 'plugin', 'scheduler', 'system', 0, 1, 1, 0, 1, '', '{"timeout":"3","webcron":"0","webcronkey":"mywebcronactivationkey","lastrun":"0","unit":"60","taskid":"0"}', '', 0, 0)
```suggestion
(0, 'plg_system_scheduler', 'plugin', 'scheduler', 'system', 0, 1, 1, 0, 1, '', '{"timeout":"3","webcron":"0","webcronkey":"","lastrun":"0","unit":"60","taskid":"0"}', '', 0, 0);
```

2020-09-29 16:13 UTC, zero-24 commented on plugins/system/scheduler/scheduler.php
> +			if ($webcronkey !== $this->params->get('webcronkey', ''))
```suggestion
			if (empty($webcronkey) || $webcronkey !== $this->params->get('webcronkey', ''))
```

2020-09-29 16:13 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +	<version>4.0.0</version>
```suggestion
	<version>4.1.0</version>
```

2020-09-29 16:13 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +<extension version="4.0" type="plugin" group="system" method="upgrade">
```suggestion
<extension version="4.1" type="plugin" group="system" method="upgrade">
```

2020-09-29 16:13 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +					default="mywebcronactivationkey"
```suggestion
					default=""
```

2020-09-29 16:13 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +	<copyright>Copyright (C) 2005 - 2019 Open Source Matters. All rights reserved.</copyright>
```suggestion
	<copyright>Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.</copyright>
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/JobListCommand.php
> + * @since  4.0.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/JobListCommand.php
> +	 * @since  4.0.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/JobListCommand.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/JobListCommand.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/JobListCommand.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/JobListCommand.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/SchedulerCommand.php
> + * @since  4.0.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/SchedulerCommand.php
> +	 * @since  4.0.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/SchedulerCommand.php
> +	 * @since 4.0
```suggestion
	 *
	 * @since __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/SchedulerCommand.php
> +	 * @var InputInterface
```suggestion
	 *
	 * @var InputInterface
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/SchedulerCommand.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-09-29 16:13 UTC, zero-24 commented on libraries/src/Console/SchedulerCommand.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-09-29 16:15 UTC, zero-24 commented
Also one more. Why do we use `onExecuteScheduledTask` and `onAfterJob` as plugin events?

Why not
`onExecuteScheduledTask` & `onAfterScheduledTask`
or
`onBeforeJob` & `onAfterJob`

I personally would choose the first one but I would not mix it

2020-09-29 16:17 UTC, zero-24 commented
Taking of RTC until the comments are adressed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29592">issues.joomla.org/tracker/joomla-cms/29592</a>.</sub>

2020-09-29 16:33 UTC, alikon commented
this pr was born for 3.9...... then has been decided it was late for 3.9..... so supposed to be in 4.0, then yet again  has been decided it was late for 4.0
.... i really hope that it still can have a chance to to land in 4.1

2020-09-29 16:38 UTC, zero-24 commented
> .... i really hope that it still can have a chance to to land in 4.1

Sure lets move it forward and get it merged for 4.1 :)

2020-09-29 16:51 UTC, zero-24 commented
@alikon any update on https://github.com/joomla/joomla-cms/pull/29592#issuecomment-700813804 and can you please update the updatesql files to 4.1.0 too?

2020-09-29 16:55 UTC, alikon commented
well mostly matter of taste or english mistake from myside.... i've no preference as i'm an english dumb....

2020-09-29 17:13 UTC, alikon commented
In the hope that all  remarks has been addressed at least for now ....

2020-10-01 07:19 UTC, zero-24 requested changes
Sorry found some more CS stuff on a seccond review. But other than it looks fine to me.

2020-10-01 07:19 UTC, zero-24 commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +	 * @since
```suggestion
	 *
	 * @since  __DEPLOY_VERSION__
```

2020-10-01 07:19 UTC, zero-24 commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +	 * @since
```suggestion
	 *
	 * @since  __DEPLOY_VERSION__
```

2020-10-01 07:19 UTC, zero-24 commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +	 * @since
```suggestion
	 *
	 * @since  __DEPLOY_VERSION__
```

2020-10-01 07:19 UTC, zero-24 commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +	 * @since
```suggestion
	 *
	 * @since  __DEPLOY_VERSION__
```

2020-10-01 07:19 UTC, zero-24 commented on administrator/components/com_plugins/src/Jobs/JobsPlugin.php
> +	 * @since  3.9.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2020-10-01 07:19 UTC, zero-24 commented on administrator/language/en-GB/plg_system_scheduler.ini
> +; Copyright (C) 2005 - 2019 Open Source Matters. All rights reserved.
```suggestion
; Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.
```

2020-10-01 07:19 UTC, zero-24 commented on administrator/language/en-GB/plg_system_scheduler.sys.ini
> +; Copyright (C) 2005 - 2019 Open Source Matters. All rights reserved.
```suggestion
; Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.
```

2020-10-01 07:19 UTC, zero-24 commented on libraries/src/Console/JobListCommand.php
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
```

2020-10-01 07:19 UTC, zero-24 commented on libraries/src/Console/JobListCommand.php
> +			$nextrun    = ' the next run will be asap';
```suggestion
			$nextrun    = ' the next run will be as soon as possible';
```

2020-10-01 07:19 UTC, zero-24 commented on libraries/src/Console/SchedulerCommand.php
> + * @copyright  Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright  Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
```

2020-10-01 07:19 UTC, zero-24 commented on plugins/actionlog/joomla/joomla.php
> +
```suggestion
```

2020-10-01 07:19 UTC, zero-24 commented on plugins/actionlog/joomla/joomla.php
> +		$this->addLog(array($message), 'PLG_ACTIONLOG_JOOMLA_PLUGIN_JOB', 'job', 0);
```suggestion

		$this->addLog(array($message), 'PLG_ACTIONLOG_JOOMLA_PLUGIN_JOB', 'job', 0);
```

2020-10-01 07:19 UTC, zero-24 commented on plugins/system/scheduler/scheduler.php
> + * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
```

2020-10-01 07:19 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +	<creationDate>July 2019</creationDate>
```suggestion
	<creationDate>October 2020</creationDate>
```

2020-10-01 07:21 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +					type="text"
we might make this better a password field? Using that we could enforce basic length rules? what do you think @alikon ?

2020-10-01 07:28 UTC, alikon commented on plugins/system/scheduler/scheduler.xml
> +					type="text"
I haven't  done a research recently about the webcron services actually available......
but it could be done even in a next pr

2020-10-01 07:39 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +					type="text"
```suggestion
					type="password"
```

2020-10-01 07:39 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +					type="text"
That should do the trick

2020-10-01 07:41 UTC, zero-24 commented on plugins/system/scheduler/scheduler.xml
> +					type="text"
Lets keep it out for now. passowrd fields are hidden by default. This can be done in a follow up PR as you said.

2020-10-01 07:42 UTC, zero-24 approved these changes
Looks fine to me. Now we have to get two tests so this can be finally merged.

2020-10-01 07:49 UTC, zero-24 commented
I have just updated 4.1-dev with 4.0 and updated this PR acordingly so once drone is happy this can be fully tested :)

2020-10-01 16:08 UTC, alikon commented
the "Download — Prebuilt packages are available for download." is missing from the 4.1-dev pipeline ?

2020-11-05 09:30 UTC, bembelimen commented
I really like the idea of having a Cron fallback in the Joomla! and it's also a feature on the roadmap, so really thank you for bringing this code in.

As we have still some time for Joomla! 4.1 I really would love to see to go a few steps further, so that we get a solution where the end user can manage crons over an interface and at the end the entries will be saved in a cron tab like way in the database.

It would also be great if cron is available on the server there could be some integration.
Also a CLI functionality and some API (helper?) would really be great.

Last but not least probably we should also take care of the user executing the Cron. In the worse case it's a user who has not the privileges.

(Thanks to @nibra and @HLeithner for a lot of valuable feedback here)

tl;the; I really like what you did but I think more is possible, would you be up to spend some more time and enhance your great start to bring it on the next level?

2020-11-11 13:41 UTC, alikon commented
> I think more is possible

of course,

but what we have now in this pr is a good start.....

the 1st step when and if  this pr will be merged  should be to use  the poor man cron's for  tasks like : 

- deleteExpiredConsents
- remindExpiringConsents
- logRotation
- updateNotifications
- sessionGC
- etc...


but i'll not spent more time on this, if this pr will not be merged (i've proposed this before 3.9 goes stable)

p.s
you don't need to manage complex crontab entry
something like this is enough

`* * * * * /usr/local/bin/php /shared/httpd/j4/htdocs/cli/joomla.php job:run >> /shared/httpd/cron.log`

2021-06-26 08:08 UTC, closed without merging

2021-06-26 11:43 UTC, alikon commented
if there is still someone interested i've decoupled it to be an external component https://github.com/alikon/testcom

2021-06-26 14:00 UTC, bembelimen commented
Would it be possible that you recover the branch for a few days, so I can copy it into my repository? I still like the base idea and implementation.

2021-07-01 19:59 UTC, PhilETaylor commented
> I still like the base idea and implementation.

So much so that you farmed it out to a "Student" to complete? https://summer.iscas.ac.cn/#/org/prodetail/210880722?lang=en