Converted copyright statement to standard format
joomla/joomla-cms pull request #29689
Opened 2020-06-18 14:47 UTC by nibra

Pull Request for Issue # .

### Summary of Changes

All copyright statements have been changed to the standard format
`© YEAR OWNER <CONTACT>`
as discussed and decided in the Production Department meeting at June 2nd, 2020:
"The 3.10 and 4.x, framework repos. Introduce into 3.10 and merge into 4.0 and then do missing files for 4 beta2. Niels in charge."

### Testing Instructions

No functionality has been touched

### Expected result

Everything works like before

### Actual result

Everything works like before

### Documentation Changes Required

NO

2020-06-18 14:53 UTC, brianteeman commented
How have you calculated the year to be used?

I thought perhaps it was the year the file was added to joomla but that can't be the case as for example with com_actionlogs which was a brand new component I would expect all those files to have the same year. But they are a mix of 2005, 2016, 2018,

2020-06-18 14:57 UTC, brianteeman commented
Another example is joomla-cms/administrator/components/com_admin/postinstall/htaccess.php

This file was introduced in joomla 3.4 and the first git commit was Oct 17, 2014 but you are setting the copyright year to 2005

2020-06-18 14:58 UTC, nibra commented
It is the first commit date according to `git`, following moves and renames, retrieved with the command

`git log --follow --date=format:%Y --pretty=format:"%cd" --diff-filter=A --find-renames=40% "${FILE}" | tail -n 1`

2020-06-18 15:03 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on 573b075f63e6aff773da7c7b932eb194e2217a8f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29689">issues.joomla.org/tracker/joomla-cms/29689</a>.</sub>

2020-06-18 15:06 UTC, brianteeman commented
There is no way that these are correct. Either your query is wrong or I dont know but I only checked the first few and they are not the date of creation for the code - therefore the copyright is wrong.

I am not against this pointless change but if its going to be done then it should be correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29689">issues.joomla.org/tracker/joomla-cms/29689</a>.</sub>

2020-06-18 15:25 UTC, nibra commented
Apparently `joomla-cms/administrator/components/com_admin/postinstall/htaccess.php` has been copied and renamed from a file from 2005; removing the `--find-renames` option results in 2014.

2020-06-18 15:29 UTC, brianteeman commented
I am sure that the same will be true for the other files that I saw were wrong

2020-06-18 15:30 UTC, nibra commented
Likely... I'm re-doing the change without that option. Will take a while.

2020-06-18 17:43 UTC, mbabker commented on README.md
> -* Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.
Keep as 2005, the date Joomla was forked.  Same for other README or LICENSE files as they will be project wide references and not file references.

2020-06-18 17:45 UTC, mbabker commented on README.md
> -* Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.
Also, if there is going to be a link to an external source in the context of the copyright line, it should really be a link to either the copyright holder's site (in this case, `opensourcematters.org` or a dedicated copyright page (if someone creates it, `joomla.org/copyright.html`), using the chosen link really comes across as kind of a marketing push for people to contribute.

2020-06-18 17:52 UTC, brianteeman commented
seems a lot of work for no benefit

2020-06-18 18:00 UTC, infograf768 commented on README.md
> -* Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.
Agree

2020-06-18 18:09 UTC, infograf768 commented
Also, adding « Inc. » means all sites using Joomla in their site name would have to modify their disclaimer.  Plus headers in lang packs, 3rd party extensions, etc.

Is that decision a requirement by our lawyers?

Imho, the Production Department should better concentrate on other more important matters.

2020-06-18 18:20 UTC, mbabker commented
> Also, adding « Inc. » means all sites using Joomla in their site name would have to modify their disclaimer. Plus headers in lang packs, 3rd party extensions, etc.

The legal entity name is "Open Source Matters, Inc.", so I would suggest that the copyright statement not using the full legal name is incorrect.

As for the date change in copyright statements...

This might come across as a pointless change, but the other pointless change is modifying every file in every Joomla owned repository in January to amend the ending date of the copyright claim.  Additionally, a copyright claim is being made on every file in most every Joomla owned repository of a copyright dating back to 2005, which is clearly not factual.

During my term on the BoD, my question (which was never answered regardless of number of requests) was "why does every file in the repository need a year range in the copyright statement", because my desire for "pointless change" was to remove the year range from everywhere except the LICENSE file (making this procedural change allows for the generated patch packages to stop bloating when their diff includes the commit making that change).  I would still advocate for that to be the ultimate end result, but if that is not allowable for some reason, then the changes Niels is making which removes the ending date is a move in the right direction.

2020-06-18 18:33 UTC, alikon commented
> Imho, the Production Department should better concentrate on other more important matters.
fully agree

2020-06-18 18:34 UTC, brianteeman commented
from the osm report

[Copyright Statement] Following Hugh’s request, Luca asked the Open Source Initiative for advice and they suggested this page that includes the clarifications on how to write an effective copyright statement: https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code . Summarizing the copyright statement should be formulated as follows:
© {$year_of_file_creation} {$name_of_copyright_holder} <{$contact}>

2020-06-18 21:37 UTC, brianteeman commented
@nibra I can see some improvements but there are still some very obvious errors. I really don't think this is something you can automate accurately

For example here we have a creation date 3 years before the copyright date

![image](https://user-images.githubusercontent.com/1296369/85074254-30d95300-b1b4-11ea-9510-aea67af7ba45.png)

2020-06-18 21:38 UTC, nibra commented
> seems a lot of work for no benefit

It's more about waiting for the computer do be done with it. Actally it is running a script and tweak the READMEs afterwards.

2020-06-18 21:43 UTC, brianteeman commented
And in some of the files the changes break the code style rules - no idea why drone doesnt pick that up

![image](https://user-images.githubusercontent.com/1296369/85074851-25d2f280-b1b5-11ea-9d95-85d542a74e04.png)

2020-06-18 22:08 UTC, mbabker commented
@nibra you're probably going to have to do this in two runs, one without rename history and one with rename history.

With the namespacing work in 3.8, hundreds of files were renamed.  So the copyright claim on the bulk of the `Joomla\CMS` namespace is now 2017 even though a fair share of the library API is going to date back to 3.0 (2012) or 1.6 (mostly likely committed in 2009 or 2010).  So for things in `libraries/(cms|joomla|legacy|src)` there's a pretty good chance that doing whatever you're doing with rename history will be pretty accurate.  Extensions are definitely pretty hard to get right though with an automated pass because of the murky commit history in places (especially when you get back to the "import the new trunk" commit somewhere between 1.5 and 1.6 since IIRC that essentially blanked and reimported the old SVN trunk) and the fact that a lot of files are copied from somewhere else in the repo with minor adjustments.

![Screen Shot 2020-06-18 at 5 01 34 PM](https://user-images.githubusercontent.com/368545/85076335-8813ff00-b185-11ea-975f-2227b6f9c44f.png)

2020-06-18 22:24 UTC, nibra commented
> And in some of the files the changes break the code style rules

Which file?

2020-06-18 22:25 UTC, nibra commented
> you're probably going to have to do this in two runs, one without rename history and one with rename history

I'll give it a try...

2020-06-18 22:41 UTC, brianteeman commented
https://github.com/joomla/joomla-cms/pull/29689#issuecomment-646335464

It was in the screenshot. The ones I saw were all css

2020-06-19 07:25 UTC, infograf768 commented
> The legal entity name is "Open Source Matters, Inc.", so I would suggest that the copyright statement not using the full legal name is incorrect.

This is totally stupid and typical US picky legalese. We have been using "Open Source Matters" for 15 years and it never has been an issue for establishing our trademark (we had other issues that were unrelated to that naming).
It is again one these useless changes which, if they were proposed by a politician, could be understood as a way to distract the attention of the voters from a real problem.

Now, as some want to be picky, let's be fully too and do the right thing:

The Berne Convention: http://www.copyright.fr/hypertext/berne1.htm (in French) https://wipolex.wipo.int/en/text/283698 (in English), signed by all countries including the USA, defines the copyright laws.

The display of the copyright was already defined by the http://portal.unesco.org/en/ev.php-URL_ID=15381&URL_DO=DO_TOPIC&URL_SECTION=201.html (Convention Universelle sur le Droit d’Auteur (Universal Copyright Convention), 1952, revised 1971)

> Article III
>1. Any Contracting 'State which, under its domestic law, requires as a condition of copyright, compliance with formalities such as deposit, registration, notice, notarial certificates, payment of fees or manufacture or publication in that Contracting State, shall regard these requirements as satisfied with respect to all works protected in accordance with this Convention and first published outside its territory and the author of which is not one of its nationals, if from the time of the first publication all the copies of the work published with the authority of the author or other copyright proprietor bear **the symbol © accompanied by the name of the copyright proprietor and the year of first publication** placed in such manner and location as to give reasonable notice of claim of copyright. 

i.e.
`© [Name of company] [year-of-first-publication]`
in that order.

Any other way of display it is just incorrect.

2020-06-19 13:26 UTC, nibra commented
> Also, adding « Inc. »

The 'Inc.' has always been there:
"Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved."

2020-06-19 13:28 UTC, nibra commented
> `© [Name of company] [year-of-first-publication]`
> in that order.

"accompanied by" does not imply an order.

2020-06-19 13:33 UTC, nibra commented
> you're probably going to have to do this in two runs, one without rename history and one with rename history.

I just wrote my own 'rename-tracing' algorithm according to [IntelliJ's 'Show History' implementation](https://github.com/JetBrains/intellij-community/blob/ea20241265f9fb956c5a99b1023765aa0e941979/plugins/git4idea/src/git4idea/history/GitFileHistory.java) to circumvent a bug in the `--follow` option of `git log`. Results look promising so far...

2020-06-19 13:50 UTC, nibra commented
> And in some of the files the changes break the code style rules - no idea why drone doesnt pick that up

Actually not - the CSS files (in Hathor) have tab characters between tag and message (which is wrong, but not caused by this change), so the indentation depends on your individual tab width settings.

2020-06-19 15:05 UTC, infograf768 commented
> The 'Inc.' has always been there

not for language files and readme, certainly others.

concerning the order, it is quite obvious: the copyright is given TO an entity, the date being a simple supplementary info.

In any case, do whatever you want. Even discussing it is a loss of time.

2020-06-20 15:07 UTC, nibra commented
This version was created using a different algorithm to follow renames, since the `--follow` option of `git log` seems to be buggy.
README files and SQL files were tweaked manually.

2020-06-20 15:44 UTC, brianteeman commented
https://github.com/joomla/joomla-cms/pull/29689#discussion_r442398145

2020-06-20 15:47 UTC, nibra commented
It was discussed in PD, considering what people expect to find when following the link. Thus the choice fell on joomla.org.

2020-06-20 17:04 UTC, brianteeman commented
Obviously I was not aware of that decision.

2020-06-20 17:08 UTC, brianteeman commented
You also need to update the bump script or your changes will be replaced when the next version is released

2020-07-03 15:31 UTC, nibra commented
@laoneo @rdeutz @wilsonge @zero-24 Please review, so there's a chance to propagate it to 4.0

2020-07-03 15:32 UTC, zero-24 commented
Why do we require an test to be changed when we just update the copyright here?

2020-07-03 15:33 UTC, brianteeman commented
Surely changing tests to match your code can not be correct. What's the point in tests if thats what happens 

/me confused

2020-07-03 15:33 UTC, nibra commented
Because otherwise Travis failes...

2020-07-03 15:35 UTC, brianteeman commented
surely that means that the code is wrong. tests are supposed to make stuff fail if they are wrong.

2020-07-03 15:36 UTC, nibra commented
> Surely changing tests to match your code can not be correct. What's the point in tests if thats what happens

There's a convention to have a newline character at the end of a file. The tests were expecting `layouts/libraries/cms/html/bootstrap/endtabset.php` and `layouts/libraries/cms/html/bootstrap/endtab.php` to not follow that convention without any reason. So I chose to fix the test instead of the files.

2020-07-03 15:42 UTC, brianteeman commented
That is all kinds of wrong.  If anything the changes to the test should be in a completely separate PR and not _hidden_ inside a pr that changed 4000 files

2020-07-03 16:09 UTC, wilsonge commented on administrator/components/com_admin/sql/updates/mysql/2.5.1-2012-01-26.sql
> +(314, 'mod_version', 'module', 'mod_version', '', 1, 1, 1, 0, '{"legacy":false,"name":"mod_version","type":"module","creationDate":"January 2012","author":"Joomla! Project","copyright":"© 2012 Open S
I don't think you can insert a raw copyright symbol here. Even if we can we should leave this lone and do it in an independent file so we can guarantee it runs on all hosts

2020-07-03 16:10 UTC, zero-24 requested changes

2020-07-03 16:10 UTC, zero-24 commented on build/bump.php
> +	$fileContents = preg_replace("#EXTRA_VERSION\s*=\s*'[^']*'#", "EXTRA_VERSION = '" . $version['extra'] . "'", $fileContents);
Why do we touch that code here?

2020-07-03 16:10 UTC, zero-24 commented on build/bump.php
>   * @license    GNU General Public License version 2 or later; see LICENSE.txt
just check one line above (can't comment there) this has not been updated.

2020-07-03 16:10 UTC, zero-24 commented on composer.json
> -        "php": ">=5.3.10",
i don't think this is a correct change

2020-07-03 16:10 UTC, zero-24 commented on installation/language/en-AU/en-AU.ini
> -; IMPORTANT NOTE FOR TRANSLATORS: Do not literally translate this line, instead add the localised name of the language. For example Spanish will be Espa�ol
Seems something got wrong here.

2020-07-03 16:10 UTC, zero-24 commented on installation/language/en-CA/en-CA.ini
> -; IMPORTANT NOTE FOR TRANSLATORS: Do not literally translate this line, instead add the localised name of the language. For example Spanish will be Espa�ol
Same here

2020-07-03 16:10 UTC, zero-24 commented on installation/language/en-NZ/en-NZ.ini
> -; IMPORTANT NOTE FOR TRANSLATORS: Do not literally translate this line, instead add the localised name of the language. For example Spanish will be Espa�ol
and here

2020-07-03 16:10 UTC, zero-24 commented on installation/language/en-US/en-US.ini
> -; IMPORTANT NOTE FOR TRANSLATORS: Do not literally translate this line, instead add the localized name of the language. For example Spanish will be Espa�ol
ok seems all files are affected by this.

2020-07-03 16:10 UTC, zero-24 commented on libraries/fof/input/jinput/cookie.php
> + * @copyright   © 2016 Open Source Matters, Inc. <https://www.joomla.org>
This does not seem to be correct. As fof is an external lib right?

2020-07-03 16:10 UTC, zero-24 commented on libraries/src/Version.php
> -	const COPYRIGHT = 'Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.';
That is intentional changed?

2020-07-03 16:12 UTC, zero-24 commented
> There's a convention to have a newline character at the end of a file. The tests were expecting layouts/libraries/cms/html/bootstrap/endtabset.php and layouts/libraries/cms/html/bootstrap/endtab.php to not follow that convention without any reason. So I chose to fix the test instead of the files.

Can we move that CS changes out of that PR that would make review easier and the test can be fixed in a seperat PR too.

2020-07-03 16:12 UTC, zero-24 commented on libraries/fof/input/jinput/cookie.php
> + * @copyright   © 2016 Open Source Matters, Inc. <https://www.joomla.org>
(same is true for the other files from fof changed in that PR)

2020-07-03 16:14 UTC, zero-24 commented on administrator/components/com_admin/sql/updates/mysql/2.5.1-2012-01-26.sql
> +(314, 'mod_version', 'module', 'mod_version', '', 1, 1, 1, 0, '{"legacy":false,"name":"mod_version","type":"module","creationDate":"January 2012","author":"Joomla! Project","copyright":"© 2012 Open S
Maybe we keep the `Copyright` as word for the XML files and so the database SQL's?

2020-07-03 16:14 UTC, zero-24 commented on administrator/components/com_admin/sql/updates/mysql/2.5.1-2012-01-26.sql
> +(314, 'mod_version', 'module', 'mod_version', '', 1, 1, 1, 0, '{"legacy":false,"name":"mod_version","type":"module","creationDate":"January 2012","author":"Joomla! Project","copyright":"© 2012 Open S
As i guess an manifest refresh that happen on all updates would / could fail on that symbol too.

2020-07-03 16:23 UTC, zero-24 commented
Additionally to the things mention above:

- [ ] All files from the build folder still have the old copyright
- [ ] /instation/language/sw-KE/sw-KW.ini is missing
- [ ] installation\language\eo-XX\eo-XX.xml not using the correct copy right
- [ ] some files are missing the changes see:
![image](https://user-images.githubusercontent.com/2596554/86485877-298c7a80-bd5a-11ea-9639-96aeb8e77fca.png)

2020-07-03 16:27 UTC, zero-24 commented on libraries/fof/input/jinput/cookie.php
> + * @copyright   © 2016 Open Source Matters, Inc. <https://www.joomla.org>
https://github.com/joomla/joomla-cms/tree/c46f9567d66ed5e3bc7c350a8a504d5a7ede5ea6/libraries/fof/input/jinput seems to be that folder

2020-07-03 16:39 UTC, wilsonge commented on administrator/components/com_admin/sql/updates/mysql/2.5.1-2012-01-26.sql
> +(314, 'mod_version', 'module', 'mod_version', '', 1, 1, 1, 0, '{"legacy":false,"name":"mod_version","type":"module","creationDate":"January 2012","author":"Joomla! Project","copyright":"© 2012 Open S
Probably

2020-07-03 16:43 UTC, brianteeman commented on administrator/components/com_admin/admin.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says it was created in 2006

2020-07-03 16:44 UTC, brianteeman commented on administrator/components/com_banners/banners.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in april 2006

2020-07-03 16:44 UTC, brianteeman commented on administrator/components/com_cache/cache.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:45 UTC, brianteeman commented on administrator/components/com_categories/categories.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created inDecember 2007

2020-07-03 16:45 UTC, brianteeman commented on administrator/components/com_checkin/checkin.xml
> +	<copyright>© 2008 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:45 UTC, brianteeman commented on administrator/components/com_config/config.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:46 UTC, brianteeman commented on administrator/components/com_contact/contact.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:46 UTC, brianteeman commented on administrator/components/com_content/content.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:46 UTC, brianteeman commented on administrator/components/com_cpanel/cpanel.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:47 UTC, brianteeman commented on administrator/components/com_installer/installer.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:47 UTC, brianteeman commented on administrator/components/com_languages/languages.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:47 UTC, brianteeman commented on administrator/components/com_login/login.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:47 UTC, brianteeman commented on administrator/components/com_media/media.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:48 UTC, brianteeman commented on administrator/components/com_menus/menus.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:48 UTC, brianteeman commented on administrator/components/com_messages/messages.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:48 UTC, brianteeman commented on administrator/components/com_modules/modules.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:48 UTC, brianteeman commented on administrator/components/com_newsfeeds/newsfeeds.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:49 UTC, brianteeman commented on administrator/components/com_plugins/plugins.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:49 UTC, brianteeman commented on administrator/components/com_redirect/redirect.xml
> +	<copyright>© 2009 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:50 UTC, brianteeman commented on administrator/components/com_search/search.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:50 UTC, brianteeman commented on administrator/components/com_templates/templates.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:51 UTC, brianteeman commented on administrator/components/com_users/users.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in April 2006

2020-07-03 16:53 UTC, brianteeman commented on administrator/manifests/packages/pkg_weblinks.xml
> +	<copyright>© 2014 Open Source Matters, Inc.</copyright>
Two lines above says created in December 2012

2020-07-03 16:53 UTC, brianteeman commented on administrator/modules/mod_custom/mod_custom.xml
> +	<copyright>© 2006 Open Source Matters, Inc.</copyright>
The line above says created in July 2004

2020-07-03 16:54 UTC, brianteeman commented on administrator/modules/mod_feed/mod_feed.xml
> +	<copyright>© 2006 Open Source Matters, Inc.</copyright>
The line above says created in July 2005

2020-07-03 16:54 UTC, brianteeman commented on administrator/modules/mod_latest/mod_latest.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The line above says created in July 2004

2020-07-03 16:58 UTC, brianteeman commented
I just tested about 70% of the xml files. I am not saying the date you have used is wrong or right but it doesn't make sense to have a copyright date that is different to a created date. Of the files that I checked the majority of them have conflicting dates.

As I said before you can't automate this sort of thing correctly. If there was ever a copyright issue then these conflicting dates would be a problem. Certainly more of a problem than this PR is supposed to resolve

2020-07-03 19:53 UTC, mbabker commented on administrator/modules/mod_latest/mod_latest.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
For all the extensions that came from the fork, change the creation dates to match the 1.0.0 release date?

2020-07-03 19:55 UTC, mbabker commented on administrator/components/com_admin/sql/updates/mysql/2.5.1-2012-01-26.sql
> +(314, 'mod_version', 'module', 'mod_version', '', 1, 1, 1, 0, '{"legacy":false,"name":"mod_version","type":"module","creationDate":"January 2012","author":"Joomla! Project","copyright":"© 2012 Open S
Manifest caches shouldn't exist in newer SQL changes, or the default install SQLs.  Since the older files are being touched, maybe just take the column completely out now?

2020-07-03 21:33 UTC, zero-24 commented on administrator/components/com_admin/sql/updates/mysql/2.5.1-2012-01-26.sql
> +(314, 'mod_version', 'module', 'mod_version', '', 1, 1, 1, 0, '{"legacy":false,"name":"mod_version","type":"module","creationDate":"January 2012","author":"Joomla! Project","copyright":"© 2012 Open S
I'm not talking about SQL files in this case but the manifest refresh that takes the now changed XML strings and throw that in the database.

2020-07-04 15:20 UTC, zero-24 commented
@nibra 

> Exchanged copyright sign with '(C)' in SQL files

This has to be done for the XML files than too.

2020-07-04 15:21 UTC, nibra commented on README.md
> -* Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.
Linking to joomla.org as decided by PD.

2020-07-04 15:26 UTC, nibra commented on administrator/components/com_admin/sql/updates/mysql/2.5.1-2012-01-26.sql
> +(314, 'mod_version', 'module', 'mod_version', '', 1, 1, 1, 0, '{"legacy":false,"name":"mod_version","type":"module","creationDate":"January 2012","author":"Joomla! Project","copyright":"© 2012 Open S
> I don't think you can insert a raw copyright symbol here
It's just a UTF-8 character, so it should not do any harm...  however, I changed it to its ASCII transscription (C) for SQL files.

2020-07-04 15:28 UTC, nibra commented on build/bump.php
> +	$fileContents = preg_replace("#EXTRA_VERSION\s*=\s*'[^']*'#", "EXTRA_VERSION = '" . $version['extra'] . "'", $fileContents);
That was the scout effect - reverted.

2020-07-04 15:28 UTC, nibra commented on build/bump.php
>   * @license    GNU General Public License version 2 or later; see LICENSE.txt
Fixed manually.

2020-07-04 15:30 UTC, nibra commented on composer.json
> -        "php": ">=5.3.10",
Seems like the IDE did that behind the scenes - reverted

2020-07-04 15:33 UTC, nibra commented on installation/language/en-AU/en-AU.ini
> -; IMPORTANT NOTE FOR TRANSLATORS: Do not literally translate this line, instead add the localised name of the language. For example Spanish will be Espa�ol
That exsists in 3.10-dev already...

2020-07-04 15:35 UTC, nibra commented on libraries/fof/input/jinput/cookie.php
> + * @copyright   © 2016 Open Source Matters, Inc. <https://www.joomla.org>
libraries/fof and libraries/joomla should not have been touched (external resources).- reverted

2020-07-04 15:38 UTC, nibra commented on libraries/src/Version.php
> -	const COPYRIGHT = 'Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.';
Yes

2020-07-04 15:39 UTC, zero-24 commented on installation/language/en-AU/en-AU.ini
> -; IMPORTANT NOTE FOR TRANSLATORS: Do not literally translate this line, instead add the localised name of the language. For example Spanish will be Espa�ol
https://github.com/joomla/joomla-cms/blob/3.10-dev/installation/language/en-AU/en-AU.ini#L185

Looks good in 3.10-dev

``Espa�ol`` vs ``Español``

2020-07-04 15:41 UTC, nibra commented
> Can we move that CS changes out of that PR that would make review easier

Yes, of course, reverted (hopefully all) unrelated changes introduced by the IDE.

2020-07-04 15:43 UTC, zero-24 commented
> Yes, of course, reverted (hopefully all) unrelated changes introduced by the IDE.

Awesome.

The build folder still seems to be missing the changes.

2020-07-04 15:52 UTC, nibra commented
> All files from the build folder still have the old copyright

That directory was skipped intentionally, but I can include it, if it makes sense. IIRC, it is not part of the distribution...

> /instation/language/sw-KE/sw-KW.ini is missing

Fixed manually (upcoming commit)

> installation\language\eo-XX\eo-XX.xml not using the correct copy right

Yes, 'Kopirajto (C) 2005 - 2019 Open Source Matters. Ĉiuj rajtoj rezervitaj.' was not recognised by the pattern. Fixed manually.

> some files are missing the changes see:

Yes, libraries/joomla is considered to be external; the changes should (will) be made in their respective repository.

2020-07-04 15:58 UTC, nibra commented on administrator/components/com_admin/admin.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
In a lot of XML files (especially the language XML), the creation date was updated on each change. Some differ because of difference between creation and first commit. Iwent through all XML files manually to remove inconsistencies.

2020-07-04 15:58 UTC, nibra commented on administrator/components/com_cache/cache.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 15:58 UTC, nibra commented on administrator/components/com_banners/banners.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 15:59 UTC, nibra commented on administrator/components/com_categories/categories.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 15:59 UTC, nibra commented on administrator/components/com_config/config.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 15:59 UTC, nibra commented on administrator/components/com_checkin/checkin.xml
> +	<copyright>© 2008 Open Source Matters, Inc.</copyright>
See above

2020-07-04 15:59 UTC, nibra commented on administrator/components/com_contact/contact.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 15:59 UTC, nibra commented on administrator/components/com_content/content.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 15:59 UTC, nibra commented on administrator/components/com_cpanel/cpanel.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:00 UTC, nibra commented on administrator/components/com_installer/installer.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:00 UTC, nibra commented on administrator/components/com_languages/languages.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:00 UTC, nibra commented on administrator/components/com_login/login.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:00 UTC, nibra commented on administrator/components/com_media/media.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:00 UTC, nibra commented on administrator/components/com_menus/menus.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:00 UTC, nibra commented on administrator/components/com_messages/messages.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:01 UTC, brianteeman commented on administrator/components/com_categories/categories.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
see what?

2020-07-04 16:01 UTC, nibra commented on administrator/components/com_modules/modules.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:01 UTC, nibra commented on administrator/components/com_newsfeeds/newsfeeds.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:01 UTC, nibra commented on administrator/components/com_plugins/plugins.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:01 UTC, nibra commented on administrator/components/com_plugins/plugins.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:01 UTC, nibra commented on administrator/components/com_redirect/redirect.xml
> +	<copyright>© 2009 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:02 UTC, nibra commented on administrator/components/com_search/search.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:02 UTC, nibra commented on administrator/components/com_templates/templates.xml
> +	<copyright>© 2007 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:02 UTC, nibra commented on administrator/components/com_users/users.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:02 UTC, zero-24 commented
> That directory was skipped intentionally, but I can include it, if it makes sense. IIRC, it is not part of the distribution...

well it is part of the repo and not external so i would include it

> Fixed manually (upcoming commit)

👍 

> Yes, 'Kopirajto (C) 2005 - 2019 Open Source Matters. Ĉiuj rajtoj rezervitaj.' was not recognised by the pattern. Fixed manually.

Sure i just wanted to point that out thanks for fixing ;)

> Yes, libraries/joomla is considered to be external; the changes should (will) be made in their respective repository.

libraries/joomla is external? only libraries/vendor/joomla are the framework packages right or I'm missing something?

2020-07-04 16:02 UTC, nibra commented on administrator/manifests/packages/pkg_weblinks.xml
> +	<copyright>© 2014 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:02 UTC, nibra commented on administrator/modules/mod_custom/mod_custom.xml
> +	<copyright>© 2006 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:02 UTC, nibra commented on administrator/modules/mod_feed/mod_feed.xml
> +	<copyright>© 2006 Open Source Matters, Inc.</copyright>
See above

2020-07-04 16:03 UTC, nibra commented on administrator/modules/mod_latest/mod_latest.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
Set 2005 for files from before the fork.

2020-07-04 16:33 UTC, nibra commented
Ok, will process `build/` and `libraries/joomla/` as well... may take a while

2020-07-04 18:00 UTC, brianteeman commented
I feel sorry for @wilsonge who is going to have to review everyone of these again when he merges up to joomla 4 and then repeat this futile exercise for all the new files

2020-07-04 22:20 UTC, nibra commented
@zero-24 Fixed the language files ('Español'); the files had a wrong encoding

2020-07-04 22:23 UTC, nibra commented on administrator/components/com_categories/categories.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
The first similar issue with the same 'The line above says ...', which has a comment that also applies to this... Thought it was obvious.

2020-07-04 22:28 UTC, nibra commented
> I feel sorry for @wilsonge who is going to have to review everyone of these again when he merges up to joomla 4 and then repeat this futile exercise for all the new files

@brianteeman You may feel sorry for me as well - I was 'volunteered' to do this (also for J4, once this is merged into 3.10 and then into 4.0.

2020-07-04 22:43 UTC, brianteeman commented on administrator/components/com_categories/categories.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
Not when here are 4000 files and when github "collapses" any comments if the file is updated

2020-07-05 00:00 UTC, zero-24 commented
> @zero-24 Fixed the language files ('Español'); the files had a wrong encoding

Awesome thanks! Will give this another review soon.

2020-07-05 00:52 UTC, nibra commented on administrator/components/com_categories/categories.xml
> +	<copyright>© 2005 Open Source Matters, Inc.</copyright>
Sorry then...

2020-07-05 05:07 UTC, zero-24 commented
> I was 'volunteered' to do this (also for J4, once this is merged into 3.10 and then into 4.0.

I would suggest to do a staging -> 3.10 -> 4.0 branch upgrade upfront. So all the "simple" stuff is fixed already right?

Also can you please post the final command used to extract that copyright updates? This can be added to the first post so everyone can find it easily :)

2020-07-05 05:09 UTC, zero-24 approved these changes
The changes here now LTGM

We have to trust your algo for the years for sure i have just picked a few and checked the data and that looked good but lets add that final command used to the inital post.

There are some file still doing minor CS stuff but this is fine for me.

2020-07-05 05:10 UTC, zero-24 commented
@infograf768 @imanickam Can you please coordinate the changed things about the not changing of the creation date and the updated copyright statment with the TT Teams?

2020-07-05 06:54 UTC, infograf768 commented
I am totally confused about what has been done for language files...
Here for example why has the date 2011 been chosen? By who?

The first Estonian installation was
<img width="685" alt="Screen Shot 2020-07-05 at 08 51 05" src="https://user-images.githubusercontent.com/869724/86527184-c7885e00-be9c-11ea-89ba-de3d92e53887.png">


```
diff --git a/installation/language/et-EE/et-EE.ini b/installation/language/et-EE/et-EE.ini
index 67a98b1a7d1d..2d2a24fe535a 100644
--- a/installation/language/et-EE/et-EE.ini
+++ b/installation/language/et-EE/et-EE.ini
@@ -1,5 +1,5 @@
 ; Joomla! Project
-; Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.
+; © 2011 Open Source Matters, Inc. <https://www.joomla.org>
 ; License GNU General Public License version 2 or later; see LICENSE.txt
 ; Note : All ini files need to be saved as UTF-8
 
diff --git a/installation/language/et-EE/et-EE.xml b/installation/language/et-EE/et-EE.xml
index 3672909ad002..07c46cab10d4 100644
--- a/installation/language/et-EE/et-EE.xml
+++ b/installation/language/et-EE/et-EE.xml
@@ -4,9 +4,9 @@
 	client="installation">
 	<name>Estonian</name>
 	<version>3.6.3</version>
-	<creationDate>2016-09-16</creationDate>
+	<creationDate>Jan 2011</creationDate>
 	<author>Joomla! Project</author>
-	<copyright>Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.</copyright>
+	<copyright>(C) 2011 Open Source Matters, Inc.</copyright>
 	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
 	<files>
 		<filename>et-EE.ini</filename>
```
Why is the copyright format different in ini and xml?
`; © 2011 Open Source Matters, Inc. <https://www.joomla.org>` vs `<copyright>(C) 2011 Open Source Matters, Inc.</copyright>`

Also, which date should be chosen for the 3.10 language packs ?

2020-07-05 07:14 UTC, infograf768 commented
Also, while we are at it:
It was decided to change the date format to `xxxx-xx-xx` (which has not been done yet for many languages)
This PR formats it `month year` like `<creationDate>Jan 2011</creationDate>`

Also this `<creationDate>` (for the lang packs as it is never displayed for the installation files except in com_localise) is only displayed in the Installed languages and Extensions Manager interfaces and is useless as `Creation`. It should rather be considered as an `updatedDate` to serve a purpose. Which means it should not be a fixed date.

2020-07-05 07:32 UTC, zero-24 commented
> Why is the copyright format different in ini and xml?

As that value gets pushed to the database and there could be instances running that break over that symbol.

> Here for example why has the date 2011 been chosen? By who?

By that script based on the git history: https://github.com/joomla/joomla-cms/commits/staging/installation/language/et-EE/et-EE.ini

2020-07-05 07:46 UTC, infograf768 commented
1. The script is wrong as I demonstrated. Use a fixed copyright date for all installation and xml ini file is the thing to do. Use 2005 is the simplest as they are all based on en-GB.
2. Then chose (C) all over instead of © to normalize stuff. Why adding an url in one case and not the other? Why make it complicated when it can be simple? 

3. Still remains the Date format and using a fixed date for what should be understood as an `updatedDate`

2020-07-05 08:47 UTC, zero-24 commented
> The script is wrong as I demonstrated. Use a fixed copyright date for all installation and xml ini file is the thing to do. Use 2005 is the simplest as they are all based on en-GB.

The srcript is right the file history is wrong but i get your point :D

 > Then chose (C) all over instead of © to normalize stuff. Why adding an url in one case and not the other? Why make it complicated when it can be simple?

Fine for me.

> Also this <creationDate> (for the lang packs as it is never displayed for the installation files except in com_localise) is only displayed in the Installed languages and Extensions Manager interfaces and is useless as Creation. It should rather be considered as an updatedDate to serve a purpose. Which means it should not be a fixed date.
> Still remains the Date format and using a fixed date for what should be understood as an updatedDate

Ok makes sense.

> It was decided to change the date format to xxxx-xx-xx (which has not been done yet for many languages)
This PR formats it month year like <creationDate>Jan 2011</creationDate>

Ok so this can be updated with the date of the latest change to that file for now with that format and will be updated by the TT's right?

2020-07-05 09:15 UTC, infograf768 commented
> Ok so this can be updated with the date of the latest change to that file for now with that format and will be updated by the TT's right?

Yes, that would make sense. When we ask for new installation .ini in 3.10.x (and therefore the .xml), xx-XX.xml —plus, if changes to language packs install.xml and pkg_xx-XX.xml—, the `<creationDate>` should be updated by TTs at the same time as the <version>. [in J4 it will be langmetadata.xml instead of xx-XX.xml].

We will have to be extra careful about this before merging new installation lang files.
I have not checked yet if we have new installation lang strings for 3.10 vs 3.9.20-dev

2020-07-05 09:24 UTC, zero-24 commented
> I have not checked yet if we have new installation lang strings for 3.10 vs 3.9.20-dev

Not that I'm aware of.

2020-07-05 09:25 UTC, brianteeman commented
That means that creation date is used to mean something different in language files to elsewhere

2020-07-05 09:43 UTC, nibra commented
> I am totally confused about what has been done for language files...
> Here for example why has the date 2011 been chosen? By who?

History for et-EE.xml says

`Jean-Marie Simonet  07.01.2011, 12:53  $ Adding sk-SK, be-BY, lv-LV, et-EE, ro-Ro, ml-BE, lt-LT, aa-AA, no-NO in installation`

2020-07-05 10:19 UTC, nibra commented
> It should rather be considered as an `updatedDate` to serve a purpose. Which means it should not be a fixed date.

Then either the field should be renamed to 'updateDate' or an 'updateDate' field should be added. It is confusing if semantics are 'misused'.

2020-07-05 10:20 UTC, nibra commented
>     Then chose (C) all over instead of © to normalize stuff.

Done

2020-07-05 10:36 UTC, nibra commented
> can you please post the final command used to extract that copyright updates? This can be added to the first post so everyone can find it easily

Done. The pair of scripts does the heavy lifting, the result might need some manual polishing, as
in some files (README, SQL data), the copyright year does not necessarily mean the creation year of that specific *file*.

2020-07-05 11:00 UTC, nibra commented
> Why is the copyright format different in ini and xml?
> `; © 2011 Open Source Matters, Inc. <https://www.joomla.org>` vs `<copyright>(C) 2011 Open Source Matters, Inc.</copyright>`

The '©' sign has been replaced with '(C)' in all copyright statements now. The contact information `<https://www.joomla.org>` is not used in XML files, because a) it would break the file syntactically and b) the contact information is contained in the XML file already.

2020-07-05 16:47 UTC, infograf768 commented
@nibra 

Heard about fighting against wind-mills?

> History for et-EE.xml says
> Jean-Marie Simonet 07.01.2011, 12:53 $ Adding sk-SK, be-BY, lv-LV, et-EE, ro-Ro, ml-BE, lt-LT, aa-AA, no-NO in installation

The real history, once more, if not in git!! See again
<img width="685" alt="Screen Shot 2020-07-05 at 08 51 05" src="https://user-images.githubusercontent.com/869724/86527184-c7885e00-be9c-11ea-89ba-de3d92e53887.png">

It makes no sense to define a different copyright year for these language files. Please use 2005.

Also, I repeat: it was asked to TTs to use the xxxx-xx-xx (year-month-day as figures for the date and you still keep a different format.

2020-07-05 21:21 UTC, nibra commented
@infograf768 

> The real history, once more, if not in git!! See again

If you provide the data, I'm happy to integrate them manually.

2020-07-06 14:53 UTC, infograf768 commented
As proposed, just use 2005 for all. It is unecessary to use any other date for the copyright.

2020-07-06 18:33 UTC, nibra commented
@infograf768 

> As proposed, just use 2005 for all. It is unecessary to use any other date for the copyright.

That would be 'more wrong' than the git history's first commit date, as the date documents *when the file was introduced* to the codebase. However, I went through all installation language files and reconstructed the creation date where possible using JoomlaCode and the original content of the file. The commit date is now only used where neither JoomlaCode nor the file content provided sufficient data. It's IMO not possible to get closer to the truth.

2020-07-07 11:27 UTC, nibra commented
PD decisions about installation language files:

**Copyright:** Follow the legal advice and state the year of creation/initial commit of the file (package), so the copyright years stay as they are now.

**<creationDate>:** It is ok to use it as creation date of "this specific version" to accommodate Translation Team's needs.

2020-07-08 05:48 UTC, Bakual commented
Honestly, just take a year and be done with it. It doesn't matter at all as nobody will ever claim copyright for language files anyway.

2020-07-08 12:27 UTC, nibra commented
> Honestly, just take a year and be done with it. It doesn't matter at all as nobody will ever claim copyright for language files anyway.

The years are as correct as determinable now.

2020-07-08 13:01 UTC, infograf768 commented
Language packs are not PRs. What remains of the TT coordination is not going to check each language pack for the « correct » copyright date.
The PD, as it is so much concerned, will now take care of it.

2020-07-08 23:46 UTC, Llewellynvdm commented
@nibra  looking an the following file: [installation/language/ckb-IQ/ckb-IQ.ini](url)
![image](https://user-images.githubusercontent.com/5607939/86979250-1f66e380-c181-11ea-95b6-c697ecf9f37b.png)

The scripts force the whole file to update instead of just the Copyright notice:
![image](https://user-images.githubusercontent.com/5607939/86979332-53420900-c181-11ea-84e2-517d0ce77aa2.png)

Is there away to avoid this? or is this just git being unable to tell the difference.

Then I see many database copyright updates and I am not able to validate those changes, it is hard to make out what has changed, since git is again unable to isolate the lines that were changed but just highlights the whole block.
![image](https://user-images.githubusercontent.com/5607939/86979945-ddd73800-c182-11ea-991a-bedcc9858823.png)

Yet for the most part the **changes look correct, and consistent** @nibra great Job!!
![image](https://user-images.githubusercontent.com/5607939/86979741-5a1d4b80-c182-11ea-8636-65a396fbda00.png)

![quick_over_view](https://user-images.githubusercontent.com/5607939/86980828-30b1ef00-c185-11ea-8488-adf51e056840.gif)
When looking at the large volume of changes being made, and knowing PHP and BASH well enough I know you must have worked on this for days. So I just want to thank you for this tremendous effort! Even though not everyone is to existed about this update, since it does not directly befit the code, @nibra you have saved the community many many hours. Thank you!

2020-07-08 23:49 UTC, Llewellynvdm approved these changes

2020-07-11 10:21 UTC, nibra commented
> The scripts force the whole file to update instead of just the Copyright notice:
> Is there away to avoid this? or is this just git being unable to tell the difference.

It is your diff viewer; PhpStorm will tell you very precisely, as will the diff view here on GitHub (although GitHub is not very user friendly when diffing ~4000 files). Only apperances of the copyright pattern were touched, wherever they were found in a file.

> Then I see many database copyright updates and I am not able to validate those changes,

Those dates are hard to validate. In SQL statements, the year was changed to be *consistent*, as those entries just are cached results from the manifest files and have no legal implications.

2020-08-11 17:37 UTC, zero-24 commented
@nibra please fix the conflicts than I will take the green button to merge this here in. When I got the initial post correct you are doing a PR against 4.x after that here is merged too?

2020-08-11 17:41 UTC, nibra commented
> When I got the initial post correct you are doing a PR against 4.x after that here is merged too?

Yes, that's the plan...

2020-08-11 17:43 UTC, zero-24 commented on libraries/src/MVC/Factory/LegacyFactory.php
> - * @copyright  (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
Is that here an intended change? Should be back to 2017 right?

2020-08-11 17:44 UTC, zero-24 commented on libraries/src/MVC/Factory/LegacyFactory.php
> + * @copyright  Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
Is that here an intended change? Should be back to 2017 right?

2020-08-11 18:52 UTC, nibra commented on libraries/src/MVC/Factory/LegacyFactory.php
> + * @copyright  Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
Fixed

2020-08-12 15:57 UTC, merged

2020-08-12 15:58 UTC, zero-24 commented
Just merged here. Thanks @nibra and all others involved.

2020-08-12 17:30 UTC, nibra commented
Thank you! How do I know, when 3.10-dev is pulled into 4.0 (without polling all the day)?

2020-08-12 21:02 UTC, zero-24 commented
Up to @wilsonge i guess.

2020-08-14 08:39 UTC, richard67 commented
This PR has broken updating from 3.10-dev to 4.0-dev by brsking the closing tag of the copyright tag here:

https://github.com/joomla/joomla-cms/pull/29689/files#diff-e31554228f84f75c239c66e5645e9e8fR7

The update component uses that file to get the version from.

I am preparing a PR to fix that.