Email Fails HTML Validation as uses text/javascript
joomla/joomla-cms pull request #29857
Opened 2020-06-30 15:19 UTC by iamrobert

If scripts have  type='text/javascript' in it - it triggers a warning in html5 validation:

`Warning: The type attribute is unnecessary for JavaScript resources.`

In our templates we can set $doc->setHtml5(true) to remove type='text/javascript' from script.
But in the email.php its hard coded - so it doesn't seem to work.

Is there away to do this?

Pull Request for Issue # .

### Summary of Changes
Remove type='text/javascript' to pass html5 validation

### Testing Instructions

### Actual result BEFORE applying this Pull Request

<script type='text/javascript'>

### Expected result AFTER applying this Pull Request

<script>

### Documentation Changes Required

2020-06-30 16:51 UTC, Quy commented on libraries/cms/html/email.php
> +		$inlineScript = "<script>" . $script . "</script>";
```suggestion
		$inlineScript = '<script>' . $script . '</script>';
```

2020-06-30 18:49 UTC, SharkyKZ commented
We shouldn't change this in J3 because non-HTML5 documents are supported. Or at least this should be conditional based on document type. Personally, I wouldn't bother with this. This doesn't causes any issues and is already fixed in J4.

2020-07-04 15:54 UTC, degobbis requested changes
Could that possibly solve the problem?

2020-07-04 15:54 UTC, degobbis commented on libraries/cms/html/email.php
```suggestion

		$scriptType = '';
		$isHtml5    = JFactory::getDocument()->isHtml5();

		if(!$isHtml5)
		{
			$scriptType = ' type="text/javascript"';
		}
		
```

2020-07-04 15:57 UTC, degobbis requested changes

2020-07-04 15:57 UTC, degobbis commented on libraries/cms/html/email.php
>  		// TODO: Use inline script for now
```suggestion
				$scriptType = '';
		$isHtml5    = JFactory::getDocument()->isHtml5();

		if(!$isHtml5)
		{
			$scriptType = ' type="text/javascript"';
		}

		// TODO: Use inline script for now
```

2020-07-04 15:57 UTC, degobbis commented on libraries/cms/html/email.php
> +		$inlineScript = '<script>' . $script . '</script>';
```suggestion
		$inlineScript = '<script' . $scriptType . '>' . $script . '</script>';
```

2020-07-04 17:09 UTC, mbabker commented
This doesn't work efficiently, that's why it is honestly better to just leave it alone for 3.x.

Unless you have a system plugin calling `$doc->setHtml5(true);` very early in the process, these HTML helpers are still going to print the HTML4 compatible syntax.  Your template's `index.php` file is not actually executed until after components are processed but before modules are processed, so setting the mode in the template makes no difference.

This should just be closed.  Yes, it generates an annoying warning in an HTML5 validator because HTML5 allows you to omit attributes where the value matches the default in some circumstances, but it is not breaking any functionality to keep it.

BTW, to properly fix this and other potential mixed HTML4/HTML5/XHTML issues so that all locations "respect" the template option, you would have to rewrite Joomla's execution cycle to allow the template to make system changes much sooner in the process.  That is quite a major change just to silence a type attribute on `<script>` tags.

2020-07-04 18:05 UTC, Quy commented
Closing for stated reason. Thanks.

2020-07-04 18:05 UTC, closed without merging