[4.0] Fix for wrond site title by using ToobarHelper in frontend
joomla/joomla-cms pull request #30025
Opened 2020-07-06 09:40 UTC by Didldu-Florian

### Summary of Changes

Site title  "- Administration" should only be added at administrator.
This happens when component developers use the toolbar helper in the frontend

### Testing Instructions
Using Toolbar Helper in a Frontend Compoennt and check the site title.

### Actual result BEFORE applying this Pull Request

The site title ist looking like these at frontend:

`<title>Home - JADMINISTRATION</title>`

### Expected result AFTER applying this Pull Request

`<title>Home</title>`

The Problem is also that the language key JADMINISTRATION is not translated either.
So finaly we should not add "- JADMINISTRATION" at frontend.

This fix does this

2020-07-06 09:46 UTC, infograf768 commented on libraries/src/Toolbar/ToolbarHelper.php
> +                $title = strip_tags($title) . ' - ' . $app->get('sitename');
CS for use of tabs and spaces
correct code should be
<img width="888" alt="Screen Shot 2020-07-06 at 11 44 40" src="https://user-images.githubusercontent.com/869724/86579918-3db0c180-bf7e-11ea-8803-1ffb31d314bf.png">

2020-07-06 09:52 UTC, Didldu-Florian commented on libraries/src/Toolbar/ToolbarHelper.php
> +                $title = strip_tags($title) . ' - ' . $app->get('sitename');
@infograf768 check again please

2020-07-06 13:18 UTC, richard67 commented on libraries/src/Toolbar/ToolbarHelper.php
> +
```suggestion

```

2020-07-06 13:18 UTC, richard67 commented on libraries/src/Toolbar/ToolbarHelper.php
> +
```suggestion

```

2020-07-06 13:19 UTC, richard67 commented on libraries/src/Toolbar/ToolbarHelper.php
> +
```suggestion

```

2020-07-06 14:20 UTC, richard67 requested changes
Please fix again code style errors reported by Drone: https://ci.joomla.org/joomla/joomla-cms/33784/1/9

2020-07-06 14:20 UTC, richard67 commented on libraries/src/Toolbar/ToolbarHelper.php
> +		if ($app->isClient('administrator'))
```suggestion

		if ($app->isClient('administrator'))
```
See [https://ci.joomla.org/joomla/joomla-cms/33784/1/9](https://ci.joomla.org/joomla/joomla-cms/33784/1/9)

2020-07-06 14:20 UTC, richard67 commented on libraries/src/Toolbar/ToolbarHelper.php
> +		Factory::getDocument()->setTitle($title);
```suggestion

		Factory::getDocument()->setTitle($title);
```
See https://ci.joomla.org/joomla/joomla-cms/33784/1/9

2020-07-06 14:25 UTC, Didldu-Florian commented
> 
> 
> Please fix again code style errors reported by Drone: https://ci.joomla.org/joomla/joomla-cms/33784/1/9

It's fixed

2020-07-06 14:26 UTC, richard67 commented
> It's fixed

@Didldu-Florian Yes, I've noticed. Do we have some component in core we can use for testing? Or do you have some 3rd party component you can tell?

2020-07-06 14:27 UTC, richard67 approved these changes

2020-07-06 14:34 UTC, Didldu-Florian commented
@richard67 in core not, but you can test it by by changing article view

https://github.com/joomla/joomla-cms/compare/4.0-dev...Didldu-Florian:patch-6

Open then an article in frontend, you will see then the problem in the <title>

2020-07-06 14:39 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on d34f0262324f7133d548aced572e3bee2d9a9de1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30025">issues.joomla.org/tracker/joomla-cms/30025</a>.</sub>

2020-07-06 14:50 UTC, Quy commented
@richard67 See link on to do multi-line comments/edits: https://twitter.com/github/status/1179101186437324801

2020-07-06 14:54 UTC, richard67 commented
@Quy Yes, but that is just comment, not changes suggestions.

2020-07-06 14:57 UTC, Quy commented
It is an outdated post, but applies to suggestions too. I have done it. Give it a try and you will se.

2020-07-09 15:28 UTC, pabloarias commented
I have tested this item :white_check_mark: successfully on d34f0262324f7133d548aced572e3bee2d9a9de1<br /><br />I've added the code in com_content and see JADMINISTRATOR in title. After apply the path I don't see that word in title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30025">issues.joomla.org/tracker/joomla-cms/30025</a>.</sub>

2020-07-09 15:43 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30025">issues.joomla.org/tracker/joomla-cms/30025</a>.</sub>

2020-07-10 16:10 UTC, merged

2020-07-10 16:10 UTC, infograf768 commented
Tks.