[3.10] Switcher field transition, from j3.10 to j4
joomla/joomla-cms pull request #30078
Opened 2020-07-12 08:53 UTC by Fedik

Pull Request for Issue #29885 
Redo of #30070

### Summary of Changes

The patch allows to transition from "btn-group" to "switcher" field more transparent.
The developer only need to add the layout attribute `layout="joomla.form.field.radio.switcher"` to the field xml.

### Testing Instructions

 * Apply the patch.
 * Create a "btn-group" field, somewhere, example in Custom HTML module:
```xml
<field
	name="switchertest"
	type="radio"
	label="switcher test"
	class="btn-group btn-group-yesno"
	layout="joomla.form.field.radio.switcher"
	default="1"
>
	<option value="1">JYES</option>
	<option value="0">JNO</option>
</field>
```

### Actual result BEFORE applying this Pull Request
The field are empty

### Expected result AFTER applying this Pull Request
The field rendered as "btn-group"

Also try testing Instructions from #29885 pull.

### Documentation Changes Required
I guess, maybe some explanation about transition to Joomla! 4

2020-07-12 09:49 UTC, degobbis commented
I have tested this item :white_check_mark: successfully on 747bb84556fab15bedbf7f5841d911fcc8e6609c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30078">issues.joomla.org/tracker/joomla-cms/30078</a>.</sub>

2020-07-12 11:14 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 747bb84556fab15bedbf7f5841d911fcc8e6609c<br /><br />Tested both the suggested code and the plugin from PR #29885 . Works both as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30078">issues.joomla.org/tracker/joomla-cms/30078</a>.</sub>

2020-07-12 11:17 UTC, richard67 commented
The Appveyor failure for PHP 5.6 is not related to this PR. It seems for this target the composer installation fails in general on the 3.10-dev branch. => @zero-24 @HLeithner @wilsonge Is it a know problem?

2020-07-12 11:17 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30078">issues.joomla.org/tracker/joomla-cms/30078</a>.</sub>

2020-07-12 11:23 UTC, richard67 commented
@brianteeman Could you review this code comment here regarding proper English? Thanks in advance. https://github.com/joomla/joomla-cms/pull/30078/files#diff-3515fd3cec8ce68eb4b8ec2cbd518dcbR14

2020-07-12 11:31 UTC, brianteeman requested changes

2020-07-12 11:31 UTC, brianteeman commented on layouts/joomla/form/field/radio/switcher.php
> +// The layout need for transition from "btn-group" in Joomla! 3.10 to "switcher" field in Joomla! 4
```
The layout is needed.... to the "switcher"...
```

2020-07-12 11:33 UTC, richard67 commented on layouts/joomla/form/field/radio/switcher.php
> +// The layout need for transition from "btn-group" in Joomla! 3.10 to "switcher" field in Joomla! 4
@Fedik Could you change that comment as suggested by Brian? It will not change RTC status of the PR. Thanks in advance.

2020-07-12 12:23 UTC, Fedik commented on layouts/joomla/form/field/radio/switcher.php
> +// The layout need for transition from "btn-group" in Joomla! 3.10 to "switcher" field in Joomla! 4
done

2020-07-12 12:26 UTC, richard67 commented
Previous tests and RTC status are still valid since last change was only in a code comment. Thanks @brianteeman for the review.

2020-07-12 13:13 UTC, richard67 commented
As before: The Appveyor failure for PHP 5.6 is not related to this PR.

2020-07-12 19:59 UTC, zero-24 commented
Merging into 3.10 thanks :)

2020-07-12 19:59 UTC, merged

2020-07-12 21:01 UTC, Fedik commented
And the note for @wilsonge : do not merge it to 4.0-dev :wink:

2020-09-29 15:08 UTC, zero-24 commented
This has been documented here: https://docs.joomla.org/J3.x:Joomla_3.10_Backports

2021-10-12 10:11 UTC, cyrez commented
@Fedik Not sure if it's "normal", but using `list` type instead of `radio`, and you get a list in versions prior to 3.10 (not the empty control) without the need of the switcher layout, and switcher as well on J4.
Maybe a way for developer who needs to support Joomla version prior to 3.10?

```
<field
	name="switchertest"
	type="list"
	label="switcher test"
	class="btn-group btn-group-yesno"
	layout="joomla.form.field.radio.switcher"
	default="1"
>
	<option value="1">JYES</option>
	<option value="0">JNO</option>
</field>
```

2021-10-12 10:26 UTC, Fedik commented
yes it "normal", however your usage is weird :)
 `list` field in Joomla 3 does not support custom layout, and so this attribute is ignored.
In Joomla 4 `list` field support custom layout, and so it will render any layout that in `layout` attribute.

2021-10-12 13:32 UTC, cyrez commented
> yes it "normal", however your usage is weird :)

I don't use it this way ;-)
But i was just wondering if a possible "hack" for some if needed...