[4.0] fix Templates : Edit style - unsaved menu assignments
joomla/joomla-cms pull request #30183
Opened 2020-07-24 16:15 UTC by shim-sao

Pull Request for Issue # .

### Summary of Changes

### Testing Instructions

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Documentation Changes Required

2020-07-24 16:35 UTC, shim-sao reviewed
#30182

2020-07-24 16:37 UTC, alikon commented
@shim-sao  did you close this by mistake ?

2020-07-24 16:46 UTC, shim-sao commented
It is my first PR with fork. I don't really know how it work :(

2020-07-24 16:50 UTC, alikon commented
no problem at all , all of us have started this way... :smiley: 

but please write 

- Testing Instructions
- Actual result BEFORE applying this Pull Request
- Expected result AFTER applying this Pull Request

2020-07-24 17:34 UTC, shim-sao commented
It is attached to an issues but I don't know how vhere do this.

2020-07-24 19:04 UTC, SharkyKZ commented on administrator/components/com_templates/src/Model/StyleModel.php
> +					->where($db->quoteName('checked_out') .' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid')
```suggestion
					->where('(' . $db->quoteName('checked_out') .' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid)')
```

2020-07-24 19:04 UTC, SharkyKZ commented on administrator/components/com_templates/src/Model/StyleModel.php
> +				->where($db->quoteName('checked_out') .' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid')
```suggestion
				->where('(' . $db->quoteName('checked_out') .' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid)')
```

2020-07-26 12:57 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 26d4f967f1c87ab0df11d44eb088ff8914cf0f66<br /><br />1. Code-review: The change is correct.
2. Real test: Successful, i.e. without that patch, the menu assignments are not saved, and with the patch they are saved. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30183">issues.joomla.org/tracker/joomla-cms/30183</a>.</sub>

2020-07-26 12:58 UTC, richard67 commented
@SharkyKZ If you have a bit time, could you test, too? Thanks in advance.

2020-07-26 16:20 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 26d4f967f1c87ab0df11d44eb088ff8914cf0f66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30183">issues.joomla.org/tracker/joomla-cms/30183</a>.</sub>

2020-07-26 16:21 UTC, alikon commented
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30183">issues.joomla.org/tracker/joomla-cms/30183</a>.</sub>

2020-07-26 16:56 UTC, infograf768 commented
Do we still have a cs?
We have
`->where('(' . $db->quoteName('checked_out') .' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid)')`
Should not we have 
`->where('(' . $db->quoteName('checked_out') . ' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid)')`

i.e. a space missing between the period and the singlequote?

2020-07-26 17:06 UTC, richard67 requested changes

2020-07-26 17:06 UTC, richard67 commented on administrator/components/com_templates/src/Model/StyleModel.php
> +					->where('(' . $db->quoteName('checked_out') .' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid)')
```suggestion
					->where('(' . $db->quoteName('checked_out') . ' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid)')
```

2020-07-26 17:06 UTC, richard67 commented on administrator/components/com_templates/src/Model/StyleModel.php
> +				->where('(' . $db->quoteName('checked_out') .' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid)')
```suggestion
				->where('(' . $db->quoteName('checked_out') . ' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid)')
```

2020-07-26 17:08 UTC, richard67 commented
Back to pending. @shim-sao please apply the suggested changes to fix PHP code style.

@infograf768 You are right. No idea though why the PHPCS check by drone didn't find it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30183">issues.joomla.org/tracker/joomla-cms/30183</a>.</sub>

2020-07-27 09:44 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 39e1640987aed287ba4140a9ec2ef18592e27769<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30183">issues.joomla.org/tracker/joomla-cms/30183</a>.</sub>

2020-07-27 09:45 UTC, richard67 commented
Changes after last 2 successful tests were only code style, so these tests are still valid => RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30183">issues.joomla.org/tracker/joomla-cms/30183</a>.</sub>

2020-07-27 09:46 UTC, richard67 approved these changes

2020-07-27 15:03 UTC, merged

2020-07-27 15:03 UTC, Quy commented
Thanks