[4.0] Fix debug logging. Move loging to application
joomla/joomla-cms pull request #30317
Opened 2020-08-08 10:15 UTC by Fedik

This is try to fix  Release Blocker #25675 .

### Summary of Changes

This will move logging set up to application level. The plugin used only for display them.
One of new feature here, that the logging may be enabled even when the debugging is Off.

### Testing Instructions

Be aware: there a thousands of Deprecated entries, if you have a slow PC / server, be patient.

Apply patch. Go to Global Configuration and enable Debug, also enable Log Deprecated API.
Enable System Debug plugin, and set "Show logs" in the plugin.

In the debugger toolbar you should be able to see much of entries of Deprecated call.

### Actual result BEFORE applying this Pull Request

No Deprecated entries, or only few of them.

### Expected result AFTER applying this Pull Request

A loot of entries

### Documentation Changes Required

Yes I guess. Logging moved to Global configuration, and can be enabled there.

2020-08-08 10:52 UTC, brianteeman commented on administrator/components/com_config/forms/application.xml
> +				size="50"
```suggestion
			name="log_path"
			type="text"
			label="COM_CONFIG_FIELD_LOG_PATH_LABEL"
			required="true"
			filter="string"
			size="50"
```

2020-08-08 10:53 UTC, brianteeman commented on administrator/components/com_config/forms/application.xml
> +				filter="integer"
```suggestion
			name="log_everything"
			type="radio"
			label="COM_CONFIG_FIELD_LOG_EVERYTHING_LABEL"
			description="COM_CONFIG_FIELD_LOG_EVERYTHING_DESC"
			layout="joomla.form.field.radio.switcher"
			default="0"
			filter="integer"
```

2020-08-08 10:53 UTC, brianteeman commented on administrator/components/com_config/forms/application.xml
> +		>
```suggestion
			>
```

2020-08-08 10:54 UTC, brianteeman commented on administrator/components/com_config/forms/application.xml
> +		>
```suggestion
			name="log_deprecated"
			type="radio"
			label="COM_CONFIG_FIELD_LOG_DEPRECATED_LABEL"
			layout="joomla.form.field.radio.switcher"
			default="0"
			filter="integer"
			>
```

2020-08-08 10:54 UTC, brianteeman commented on administrator/components/com_config/forms/application.xml
> +		>
```suggestion
			name="log_priorities"
			type="list"
			label="COM_CONFIG_FIELD_LOG_PRIORITIES_LABEL"
			multiple="true"
			layout="joomla.form.field.list-fancy-select"
			default="all"
			validate="options"
			>
```

2020-08-08 10:55 UTC, brianteeman commented on administrator/components/com_config/forms/application.xml
> +				default=""
```suggestion
			name="log_categories"
			type="text"
			label="COM_CONFIG_FIELD_LOG_CATEGORIES_LABEL"
			description="COM_CONFIG_FIELD_LOG_CATEGORIES_DESC"
			size="60"
			default=""
```

2020-08-08 10:55 UTC, brianteeman commented on administrator/components/com_config/forms/application.xml
> +		>
```suggestion
			name="log_category_mode"
			type="radio"
			label="COM_CONFIG_FIELD_LOG_CATEGORY_MODE_LABEL"
			layout="joomla.form.field.radio.switcher"
			default="0"
			filter="integer"
			>
```

2020-08-08 10:57 UTC, brianteeman commented on libraries/src/Log/Logger/InMemoryLogger.php
> + * Logger class that keep all entries in memory
```suggestion
 * Logger class that keeps all entries in memory
```

2020-08-09 01:09 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 0275ab9e9b6ae8a2d038686d9824ca894776e031<br /><br />Tested successfully in Beta4-dev of 5 August on Wampserver 3.2.2 using PHP 7.4.8.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30317">issues.joomla.org/tracker/joomla-cms/30317</a>.</sub>

2020-08-09 14:11 UTC, richard67 requested changes

2020-08-09 14:11 UTC, richard67 commented on administrator/language/en-GB/com_config.ini
> +COM_CONFIG_FIELD_LOG_EVERYTHING_LABEL="Log Almost Everythin"
```suggestion
COM_CONFIG_FIELD_LOG_EVERYTHING_LABEL="Log Almost Everything"
```

2020-08-09 14:13 UTC, richard67 approved these changes

2020-08-09 14:15 UTC, richard67 commented
Previous test by @toivo is still valid because last change only was a typo correction in a language string. I've restored the test result in the issue tracker.

2020-08-09 14:15 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 31e7e7764bb1489a0fd5b52aa53d6836d096ae4e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30317">issues.joomla.org/tracker/joomla-cms/30317</a>.</sub>

2020-08-09 14:16 UTC, richard67 commented
@Fedik To save you time, I've allowed myself to commit the typo correction for the language string directly to your branch. I hope you are ok with that. If not, let me know and I'll never do it again.

2020-08-09 14:17 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30317">issues.joomla.org/tracker/joomla-cms/30317</a>.</sub>

2020-08-11 11:55 UTC, ohrionmartin commented
I have tested this item :white_check_mark: successfully on 31e7e7764bb1489a0fd5b52aa53d6836d096ae4e<br /><br />System Information
=============
php: Linux lamp121.cloudaccess.net 2.6.32-673.8.1.lve1.4.3.1.el6.x86_64 #1 SMP Thu May 5 16:06:47 EDT 2016 x86_64
dbserver: mysql
dbversion: 5.7.29-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.19
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30317">issues.joomla.org/tracker/joomla-cms/30317</a>.</sub>

2020-09-22 19:37 UTC, richard67 commented
@wilsonge Anything keeps this from being merged?

2020-09-29 15:55 UTC, zero-24 commented on libraries/src/Application/CMSApplication.php
> +	 * @since 4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-10-16 11:25 UTC, merged