[4.0] [Cassiopea] Implementing Password length/meter
joomla/joomla-cms pull request #30437
Opened 2020-08-21 10:04 UTC by infograf768

### Summary of Changes
As title says.

### Testing Instructions
Allow user registration in Users Options
Register in frontend Cassiopea

Uses npm after patch

### Actual result BEFORE applying this Pull Request
<img width="943" alt="Screen Shot 2020-08-20 at 07 45 32" src="https://user-images.githubusercontent.com/869724/90723095-64bc1c00-e2bc-11ea-862f-2284d50ed3fb.png">

### Expected result AFTER applying this Pull Request

This will work better (length) if https://github.com/joomla/joomla-cms/pull/30424 is already merged in the testing branch.

<img width="1079" alt="Screen Shot 2020-08-21 at 11 53 40" src="https://user-images.githubusercontent.com/869724/90878532-ed62b700-e3a5-11ea-9f04-b3e03697cfd4.png">

There may be some cs. tbs after drone first pass.

2020-08-21 10:58 UTC, Magnytu2 commented
the graph is very small on Safari as on Chrome
![Créer_un_compte-2](https://user-images.githubusercontent.com/26197929/90883356-ef307880-e3ad-11ea-925d-311468d8fad5.jpg)

2020-08-21 11:01 UTC, infograf768 commented
This PR needs npm to add the class:
```
meter {
  width: 100%;
}
```
can't be tested with patch tester.
Also to get good results for the color bar, the test site must already contain https://github.com/joomla/joomla-cms/pull/30424

2020-08-21 13:06 UTC, Magnytu2 commented
I tried on my site with the PR 30424, but it is still small.

2020-08-21 14:14 UTC, infograf768 commented
both prs need npm to compile the scss.

2020-08-21 16:27 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 9697d5bb20a65d9e6a1a1bcedcd57478c5a7320e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30437">issues.joomla.org/tracker/joomla-cms/30437</a>.</sub>

2020-08-21 17:09 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 9697d5bb20a65d9e6a1a1bcedcd57478c5a7320e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30437">issues.joomla.org/tracker/joomla-cms/30437</a>.</sub>

2020-08-21 17:09 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30437">issues.joomla.org/tracker/joomla-cms/30437</a>.</sub>

2020-08-22 08:04 UTC, zero-24 requested changes

2020-08-22 08:04 UTC, zero-24 commented on language/en-GB/com_users.ini
> +COM_USERS_PASSWORD_LENGTH="Enter at least 12 characters."
That value is not hardcoded so i'm not sure whether we should hardcode it into a language string.

2020-08-22 08:25 UTC, infograf768 commented on language/en-GB/com_users.ini
> +COM_USERS_PASSWORD_LENGTH="Enter at least 12 characters."
Is'nt it hardcoded
`$this->minLength    = 12;`
`$this->minLength    = (int) ComponentHelper::getParams('com_users')->get('minimum_length', 12);`

or is it only for installation?

2020-08-22 08:30 UTC, infograf768 commented on language/en-GB/com_users.ini
> +COM_USERS_PASSWORD_LENGTH="Enter at least 12 characters."
We could fetch the value from the Options here and add a variable in the string.
True minimum is 8 indeed.

What do you think?

2020-08-22 08:40 UTC, zero-24 commented on language/en-GB/com_users.ini
> +COM_USERS_PASSWORD_LENGTH="Enter at least 12 characters."
As mention in the maintainers chat already.

There is just the default to be 12 chars an no complexity rules.

Administrators can choose to enforce complxity rules including lower or higher limits in characters as well as minimum integer etc.

The core by default just have that 12 char rule that is also used in the installer as no other config is aviable at that point.

But when you want to do such string we might have to mention all configured complexity rules and not just the char count.

2020-08-22 08:51 UTC, infograf768 commented on language/en-GB/com_users.ini
> +COM_USERS_PASSWORD_LENGTH="Enter at least 12 characters."
OK. Let's take off the desc for now to get this in and then look later at a way to display by a specific icon the rules defined by the Options.

2020-08-22 09:21 UTC, infograf768 commented
Thanks @zero-24 
Took off description. We have to implement another PR to display all the minimum rules defined in the Options.

We will not just get
<img width="877" alt="Screen Shot 2020-08-22 at 11 18 07" src="https://user-images.githubusercontent.com/869724/90953186-93c3c080-e469-11ea-84bd-6ce917356bb5.png">

Folks, please test again

2020-08-22 09:22 UTC, infograf768 commented
Back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30437">issues.joomla.org/tracker/joomla-cms/30437</a>.</sub>

2020-08-22 10:54 UTC, richard67 commented
@zero-24 Could you update your review so that the "Changes requested" disappears? I think it needs to approve the changes of this for that, marking conversation as revolved will not be enough, as far as I remember.

2020-08-22 11:01 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on cfced3641349636b9893e96ae71fbfa98c117f23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30437">issues.joomla.org/tracker/joomla-cms/30437</a>.</sub>

2020-08-22 14:44 UTC, Quy commented
I have tested this item :white_check_mark: successfully on cfced3641349636b9893e96ae71fbfa98c117f23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30437">issues.joomla.org/tracker/joomla-cms/30437</a>.</sub>

2020-08-22 14:44 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30437">issues.joomla.org/tracker/joomla-cms/30437</a>.</sub>

2020-08-23 11:34 UTC, merged