[4.0] Messages/Alerts: using icons instead of text as heading
joomla/joomla-cms pull request #30516
Opened 2020-08-30 07:40 UTC by infograf768

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/30404

### Summary of Changes
As title says, replacing text by icons in Alerts

### Testing Instructions
Add to Atum and Cassiopea index.php

```
Factory::getApplication()->enqueueMessage('error message','error');
Factory::getApplication()->enqueueMessage('another long error message','error');
Factory::getApplication()->enqueueMessage('a danger message','danger');
Factory::getApplication()->enqueueMessage('warning message','warning');;
Factory::getApplication()->enqueueMessage('notice message','notice');
Factory::getApplication()->enqueueMessage('info message','info');
Factory::getApplication()->enqueueMessage('success message','success');
Factory::getApplication()->enqueueMessage('message no type');
```
in order to test all kinds of messages

Patch, Run NPM CI

### Actual result BEFORE applying this Pull Request

<img width="1239" alt="Screen Shot 2020-08-30 at 09 38 28" src="https://user-images.githubusercontent.com/869724/91653880-a9a63680-eaa4-11ea-9be7-bc630cbb8032.png">

### Expected result AFTER applying this Pull Request
Cassiopea

<img width="883" alt="Screen Shot 2020-08-30 at 09 23 41" src="https://user-images.githubusercontent.com/869724/91653807-2684e080-eaa4-11ea-835b-fa80e3319fa7.png">

Atum

<img width="1238" alt="Screen Shot 2020-08-30 at 09 23 22" src="https://user-images.githubusercontent.com/869724/91653809-28e73a80-eaa4-11ea-834f-12e2d87c560a.png">

### Documentation Changes Required

2020-08-30 08:32 UTC, brianteeman commented
Not got time to check properly but this looks ok for accessibility at first glance. Needs to be reviewed by the accessibility team though.

2020-08-30 09:29 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on dce6e70204bf5fcd2f541b1ef878301c81436ac3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30516">issues.joomla.org/tracker/joomla-cms/30516</a>.</sub>

2020-08-30 09:30 UTC, brianteeman commented
After applying the patch and rebuilding npm the pr itself works great but it has a knock on impact elsewhere

### before
![image](https://user-images.githubusercontent.com/1296369/91655857-e164ac80-eaab-11ea-9664-54632a838f25.png)

### after
![image](https://user-images.githubusercontent.com/1296369/91655848-d01ba000-eaab-11ea-8848-1e7cb8579214.png)

2020-08-30 09:37 UTC, infograf768 commented
> After applying the patch and rebuilding npm the pr itself works great but it has a knock on impact elsewhere

Yep, we saw that a bit ago.
Changing to draft.

2020-08-30 11:09 UTC, infograf768 commented
icomoon stuff was loaded, creating the issue with the featured columns icon.
It is now solved, but we have another issue:
The icons are very slow to load, including for all the other icons than the alerts ones.

Maybe this is due to the use of `@extend` in, for example
```
    .error,
    .danger {
      @extend .fas;
      @extend .fa-times-circle;
    }
```
and the fact that it is necessary if we use `@extend` to import fontawesome in joomla-alert.scss


We may have use a simpler
```
.error,
.danger {
      &::before {
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
        content: "\f057";
      }
```
etc.

2020-08-30 11:37 UTC, ReLater commented
Before this PR I had the possibility to use custom language strings for custom message types
`Factory::getApplication()->enqueueMessage('message my type', 'blah');`

After this PR not.
---------------
both template.scss are importing already fontawesome. Why twice with this pr?

https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/template.scss#L15-L18

2020-08-30 15:09 UTC, infograf768 commented
@ReLater 
> both template.scss are importing already fontawesome. Why twice with this pr?

My test with `@extend` created errors when compiling as `@extend` can only work with selectors.
To solve this I had to load again fontawesome in the file where `@extend` is used.
This is why I need help from a scss expert. Will test without `@extend` to see how it behaves.

> Before this PR I had the possibility to use custom language strings for custom message types

I guess you were always getting an info type message (blue background), with `blah` translated in the heading. 

Here we use icons related to core types.
As `blah` is not a specific type, it will show without a specific icon, unless you define a css for an icon in your template css.
But the text will be correctly translated.

Example:
`Factory::getApplication()->enqueueMessage('message with blah as type', 'blah');`

`BLAH="My custom heading text"`

<img width="701" alt="Screen Shot 2020-08-30 at 16 55 20" src="https://user-images.githubusercontent.com/869724/91662316-f0fee800-eae1-11ea-9c1c-a2acc1b8af63.png">

2020-08-30 21:13 UTC, N6REJ commented
This brings up an important issue I have had with the way icons are currently handled.  Which me'n hans are working on.  Give me 24hrs to sort this out for the best solution.  One thing we don't need/want is to load fa set twice.

2020-08-30 22:56 UTC, dgrammatiko commented
@infograf768 for the love of god please don't mix Fontawesome with the alerts. They are and supposed to be universal (eg no dependencies and work well with any front end stack). Just copy paste these few lines of CSS from this comment: https://github.com/joomla-projects/custom-elements/issues/99#issuecomment-423287233

2020-08-31 06:39 UTC, infograf768 commented
@dgrammatiko 
I understand it should not be done this way as anyway the icons loading time is a no no.
But I am not sure how to apply your suggestion here.

2020-08-31 07:27 UTC, infograf768 commented
Obvioulsy, it is possible to solve the issue for the layout, using a simple code similar to the one used in https://github.com/brianteeman/joomla-cms/commit/8f6c3f97b35de5245b35886814ebabdb9b01c94a
This because we do not use the `h4` anymore.

i.e. adding
```
$icon = [
		CMSApplication::MSG_EMERGENCY => 'fas fa-times-circle',
		CMSApplication::MSG_ALERT     => 'fas fa-times-circle',
		CMSApplication::MSG_CRITICAL  => 'fas fa-times-circle',
		CMSApplication::MSG_ERROR     => 'fas fa-times-circle',
		CMSApplication::MSG_WARNING   => 'fas fa-exclamation-triangle',
		CMSApplication::MSG_NOTICE    => 'fas fa-info-circle',
		CMSApplication::MSG_INFO      => 'fas fa-info-circle',
		CMSApplication::MSG_DEBUG     => 'fas fa-info-circle',
		'message'                     => 'fas fa-check-circle',
		'success'                     => 'fas fa-check-circle',
		'danger'                      => 'fas fa-times-circle',
];
```
and then
```
<span class="<?php echo $icon[$type]; ?>" aria-hidden="true"></span>
```

But the problem remains for the js as I guess it is not a good idea to hardcode there these classes.

2020-08-31 07:30 UTC, brianteeman commented
That is not correct for the reasons stated in that pr when it was closed

2020-08-31 08:00 UTC, infograf768 commented
I think I understood Dimitris proposal. On it now.

2020-08-31 08:04 UTC, dgrammatiko commented
> I think I understood Dimitris proposal. On it now.

The same approach SHOULD be applied also to all the fields. Fields should be coded in such a way that Bootstrap/jQuery or Font Awesome is not a dependency... (eg icons should be a css baground-image property if you want the CMS to remain relative in terms of performance)

2020-08-31 11:37 UTC, infograf768 commented
@dgrammatiko @brianteeman 
Modified to use svg. No more issue loading time.

We now get

<img width="329" alt="Screen Shot 2020-08-31 at 13 36 35" src="https://user-images.githubusercontent.com/869724/91716004-11d14700-eb8f-11ea-88f8-da45e638a81e.png">

2020-08-31 11:44 UTC, infograf768 commented
Have to correct a lot of scss cs, does not prevent from testing ;)

2020-08-31 11:46 UTC, dgrammatiko requested changes

2020-08-31 11:46 UTC, dgrammatiko commented on build/media_source/system/js/core.es6/message.es6
> +        titleWrapper.innerHTML = `<span class="${type}" aria-hidden ="true"></span><span class="sr-only">${Joomla.Text._(type) ? Joomla.Text._(type) : type}</span>`;
You don't need `aria-hidden ="true"` anymore as the icons are background images and will never be announced from screen readers

2020-08-31 11:48 UTC, dgrammatiko commented on build/media_source/system/js/core.es6/message.es6
> +        titleWrapper.innerHTML = `<span class="${type}" aria-hidden ="true"></span><span class="sr-only">${Joomla.Text._(type) ? Joomla.Text._(type) : type}</span>`;
Also there is a typo there, the equal has space before which probably will be ignored by browsers

2020-08-31 11:57 UTC, infograf768 commented on build/media_source/system/js/core.es6/message.es6
> +        titleWrapper.innerHTML = `<span class="${type}" aria-hidden ="true"></span><span class="sr-only">${Joomla.Text._(type) ? Joomla.Text._(type) : type}</span>`;
took off aria-hidden from both the js and the layout

2020-08-31 15:36 UTC, N6REJ commented
why is the background size so big?
```css
background-image:url('data:image/svg+xml;utf8,<svg width="1792" height="1792" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path fill="rgba(255, 255, 255, .95)" d="M1299 813l-422 422q-19 19-45 19t-45-19l-294-294q-19-19-19-45t19-45l102-102q19-19 45-19t45 19l147 147 275-275q19-19 45-19t45 19l102 102q19 19 19 45t-19 45zm141 83q0-148-73-273t-198-198-273-73-273 73-198 198-73 273 73 273 198 198 273 73 273-73 198-198 73-273zm224 0q0 209-103 385.5t-279.5 279.5-385.5 103-385.5-103-279.5-279.5-103-385.5 103-385.5 279.5-279.5 385.5-103 385.5 103 279.5 279.5 103 385.5z"/></svg>');
```

2020-08-31 15:42 UTC, Quy commented
![30516](https://user-images.githubusercontent.com/368084/91738795-e38b4180-eb65-11ea-97aa-71e1d8328ec9.png)

2020-08-31 15:50 UTC, infograf768 commented
@Quy 
On it.

2020-08-31 16:37 UTC, infograf768 commented
@Quy
Should be OK now.

@N6REJ 
> why is the background size so big?

I picked 2 of these at https://github.com/joomla-projects/custom-elements/issues/99#issuecomment-423287233
Then  I got the others from fontawesome svg and a bit mimicked code.

2020-08-31 23:08 UTC, Quy commented on layouts/joomla/system/message.php
> +							<span class="<?php echo $type; ?>"></span>
```suggestion
							<span class="<?php echo $type; ?>" aria-hidden="true"></span>
```

2020-08-31 23:08 UTC, Quy commented on build/media_source/system/js/core.es6/message.es6
> +        titleWrapper.innerHTML = `<span class="${type}"></span><span class="sr-only">${Joomla.Text._(type) ? Joomla.Text._(type) : type}</span>`;
```suggestion
        titleWrapper.innerHTML = `<span class="${type}" aria-hidden="true"></span><span class="sr-only">${Joomla.Text._(type) ? Joomla.Text._(type) : type}</span>`;
```

2020-08-31 23:12 UTC, dgrammatiko commented on layouts/joomla/system/message.php
> +							<span class="<?php echo $type; ?>"></span>
@Quy aria-hidden is not needed here, the icon is a background image and thus will never be announced by a screen reader, https://github.com/joomla/joomla-cms/pull/30516#discussion_r480076023

2020-08-31 23:14 UTC, Quy commented on layouts/joomla/system/message.php
> +							<span class="<?php echo $type; ?>"></span>
Of course,..thanks!

2020-09-01 08:40 UTC, chmst commented
I have tested this item :white_check_mark: successfully on c39992ef2fd865aae6e84f0f17dc380a93cba50f<br /><br />Tested on win10 with FF and Edged. Just a hint for other testers: my cache was stubborn for these changes, so using a new instance of browsers is agood idea.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30516">issues.joomla.org/tracker/joomla-cms/30516</a>.</sub>

2020-09-01 19:22 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on c39992ef2fd865aae6e84f0f17dc380a93cba50f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30516">issues.joomla.org/tracker/joomla-cms/30516</a>.</sub>

2020-09-01 19:24 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30516">issues.joomla.org/tracker/joomla-cms/30516</a>.</sub>

2020-09-01 20:45 UTC, merged

2020-09-01 20:45 UTC, HLeithner commented
Thanks