[3.x-4.0] enable install in a dedicated schema on PostgreSQL databases
joomla/joomla-cms pull request #30570
Opened 2020-09-04 14:21 UTC by Skrol29

Pull Request for Issue # .

### Summary of Changes

The installation of Joomla in a PostgreSQL database is nowadays limited to the schema named "public".
This limitation is the due to only one line of code in the PostgreSQL (PDO) driver : this is in the function getTableColumns()
where a search for columns is made explicitly in the "public" schema.

The changes of this Pull Request make the function getTableColumns() to search columns in the default schema of the connection instead of the "public" schema.
This goes with a new private function named getDefaultSchema(), which could be used for future coding when we need to now the default schema in PostgreSQL.

The ability to install Joomla in a dedicated schema is more comfortable, opened, et secured.

### Testing Instructions

1) 
Create a PostgreSQL schema dedicated to your Joomla application.
Also create a user dedicated for your Joomla application connection.

SQL instruction :
```
-- create a schema dedicated to your Joomla application
CREATE SCHEMA schema_joomla_app;

-- create a user dedicated to your Joomla application connection
CREATE ROLE user_joomla_app WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'xxxxxxxx';

-- limit the user permissions to the dedicated schema
GRANT ALL ON SCHEMA schema_joomla_app TO user_joomla_app WITH GRANT OPTION;

-- set the default schema for the user
ALTER ROLE user_joomla_app IN DATABASE my_test_db SET search_path TO schema_joomla_app;
```
2) Start a fresh new Joomla installation,  at the Database configuration step, choose the Database type : "PostgreSQL (PDO)", and continue the installation process using your user and database connection.

### Actual result BEFORE applying this Pull Request

At the last step of the installation, the process never ends (test on Joomla 3.9.21) because a silent error as occurred: one Ajax response hold the error message : "No columns found for #__extensions table".

In the database, all Joomla tables seems to be correctly created.

If you restart the installation from the previous step, the the same error occurs.

### Expected result AFTER applying this Pull Request

The installation ends without error.
Joomla is functional.

### Documentation Changes Required

No

2020-09-18 10:23 UTC, richard67 commented
@wilsonge Should this be fixed upstream in the framework package, too?

2020-09-18 12:30 UTC, Skrol29 commented
> 
> 
> @wilsonge Should this be fixed upstream in the framework package, too?

Yes, but I cannot test yet.
The code is nearly the same in https://github.com/joomla-framework/database/blob/master/src/Pgsql/PgsqlDriver.php

2020-09-19 14:49 UTC, richard67 commented
@Skrol29 Your PR here changes the PDO driver for PostgreSQL. But on 3.9.x we still have to support the native PostgreSQL driver, too.

Could you do the same changes in file [https://github.com/Skrol29/fork-joomla-cms/blob/pgsql-support/libraries/joomla/database/driver/postgresql.php](https://github.com/Skrol29/fork-joomla-cms/blob/pgsql-support/libraries/joomla/database/driver/postgresql.php) ?

Just edit that file in the branch of this PR and commit the changes so that change will be part of this PR here, too.

Let me know if you need advise with that.

After this PR will be tested with success and finally be merged into the staging branch here, I will take care of bringing up the change to the upstream repository in the framework and to bring it into the 2.0 branch of the framework database package so the correction will at the end also arrive in Joomla 4.

2020-09-20 07:16 UTC, alikon commented
i've made a test on PDO and it works

@Skrol29 
so i've made a PR to you branch for Postgresql https://github.com/Skrol29/fork-joomla-cms/pull/1

2020-09-20 20:18 UTC, Quy commented on libraries/joomla/database/driver/postgresql.php
> +	}
```suggestion
	 * Internal function to get the name of the default schema for the current PostgreSQL connection.
	 * That is the schema where tables are created by Joomla.
	 *
	 * @return  string
	 *
	 * @since   __DEPLOY_VERSION__
	 */
	private function getDefaultSchema()
	{
		// Supported since PostgreSQL 7.3
		$this->setQuery('SELECT (current_schemas(false))[1]');

		return $this->loadResult();
	}
```

2020-09-20 20:59 UTC, Skrol29 commented on libraries/joomla/database/driver/postgresql.php
> +	}
If we have a look other functions such as getCollation(), getTableList(), getTableSequences(), ... the extra line break is not always practiced. It seems to be a simple way to make big query more readable. Any advice from a dev team member ?

2020-09-21 07:17 UTC, Skrol29 commented
The _continuous-integration/drone/pr_ has failed on the Codequality / Javascript test. This seems mis relevant. Can somebody help on this or restart the check ?

2020-09-21 07:35 UTC, richard67 commented
Restarted the check, maybe we are more lucky this time.

2020-09-24 10:54 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 40a5784edf2885d497e27ee80ace73a2c564944c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30570">issues.joomla.org/tracker/joomla-cms/30570</a>.</sub>

2020-10-12 14:44 UTC, Skrol29 commented
Can someone else with permissions add a Human Test ? So the Pull Request could goes one...

2020-10-12 14:49 UTC, richard67 commented on libraries/joomla/database/driver/pgsql.php
> +	 * @since   3.9.21
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-10-12 14:52 UTC, richard67 commented on libraries/joomla/database/driver/pgsql.php
> +	 * @since   3.9.21
@Skrol29 Please fix the since version here. It will not invalidate the previous test, I'll add back the test result as soon as you have applied this change here. You can use a button on GitHub to do that. Thanks in advance.

2020-10-13 07:57 UTC, richard67 commented
@alikon Regarding your previous test: Have you tested only the PDO driver, or both PDO and the native PostgreSQL driver? And have you also tested if it works like before when not using a different default scheme but the public scheme, i.e. the usual way?

2020-11-02 08:53 UTC, N6REJ commented
@Skrol29 please correct the conflicts

2020-11-03 09:17 UTC, richard67 commented
@Skrol29 It seems with resolving the conflict you have removed the definition of function `getDefaultSchema` from file `libraries/joomla/database/driver/postgresql.php`.

2020-11-03 10:47 UTC, richard67 approved these changes

2020-11-20 10:45 UTC, Skrol29 commented
What is the next step for a RTC (Ready To Commit) ? Does it need a second approval ?
If the Pull Request is accepted, do I need another one for Joomla 4 ?

2020-11-20 10:49 UTC, richard67 commented
> What is the next step for a RTC (Ready To Commit) ? Does it need a second approval ?

No, but it needs a second human test.

> If the Pull Request is accepted, do I need another one for Joomla 4 ?

No, when it has been merged into the staging branch, it will sooner or later arrive in the 3.10-dev branch, too. For 4.0-dev it would need to make a pull request for the 2.0-dev branch of the database package in the framework here: [https://github.com/joomla-framework/database](https://github.com/joomla-framework/database).

2020-11-20 10:51 UTC, richard67 commented
P.S.: @alikon Could you test again, if possible with both the native PostgreSQL driver and the PDO driver? Thanks in advance.

2020-11-22 08:45 UTC, alikon commented
I have tested this item :white_check_mark: successfully on b6fc4386e3192ad4b0c5acef526a8919bd875e35<br /><br />i've tested both with pdo/postgresql  with public/default schema and works as before
i've tested both with pdo/postgresql  with dedicated schema and works 
postgresql 11.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30570">issues.joomla.org/tracker/joomla-cms/30570</a>.</sub>

2020-11-22 08:46 UTC, alikon approved these changes

2020-11-24 12:33 UTC, gostn commented
I have tested this item :white_check_mark: successfully on b6fc4386e3192ad4b0c5acef526a8919bd875e35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30570">issues.joomla.org/tracker/joomla-cms/30570</a>.</sub>

2020-11-24 12:34 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30570">issues.joomla.org/tracker/joomla-cms/30570</a>.</sub>

2020-11-24 12:56 UTC, richard67 commented
@wilsonge I will care for porting this up to the framework (master and 2.0-dev).

2020-11-24 13:15 UTC, richard67 commented
@wilsonge PR for the framework is https://github.com/joomla-framework/database/pull/217 .

2020-11-26 18:18 UTC, richard67 requested changes

2020-11-26 18:18 UTC, richard67 commented on libraries/joomla/database/driver/pgsql.php
> +	 * Internal function to get the name of the default schema for the current PostgreSQL connexion.
```suggestion
	 * Internal function to get the name of the default schema for the current PostgreSQL connection.
```
We use English, not French in comments ;-)

2020-11-26 18:18 UTC, richard67 commented on libraries/joomla/database/driver/postgresql.php
> +	 * Internal function to get the name of the default schema for the current PostgreSQL connexion.
```suggestion
	 * Internal function to get the name of the default schema for the current PostgreSQL connection.
```
We use English, not French in comments ;-)

2020-11-26 18:21 UTC, richard67 approved these changes

2020-12-04 13:45 UTC, richard67 commented
Previous tests and RTC status are still valid. Last 2 commits by me only corrected 2 code comments. I've restored the test results so they are properly counted.

2020-12-14 18:39 UTC, merged

2020-12-14 18:39 UTC, wilsonge commented
Thankyou @Skrol29 !

2020-12-14 21:09 UTC, Skrol29 commented
> 
> 
> Thankyou @Skrol29 !

Thanks to all of you :-)