Fix color field attributes onchange and required.
joomla/joomla-cms pull request #30743
Opened 2020-09-23 10:49 UTC by Harmageddon

### Summary of Changes
- Fixed the attributes `onchange` and `required` for the color form field.
- Improved the documentation in the layout files.

### Testing Instructions
1. In some kind of form, create or edit a form field of `type="color"`. Add the attributes `required` and/or `onchange`. Test with both color field layouts (`control="simple"` for the simple version).
Alternatively, you can use the demo plugin at https://github.com/Harmageddon/plg_demo_colorfield
2. Open the form. 
3. Test the `required` attribute: Try saving the form without entering a value in the required color field.
4. Test the `onchange` attribute: Select a value for the field that has the `onchange` attribute and see whether the JavaScript handler is called.
5. Check the HTML source of the form for validity.

### Actual result BEFORE applying this Pull Request
The values for the two attributes are printed directly in the source code, leading to invalid HTML like:
```HTML
<input type="text" name="jform[params][color2]" id="jform_params_color2" value="none" placeholder="#rrggbb" class="minicolors hex" data-position="default" data-control="hue"alert('New value: ' + this.value); data-format="hex"/>
```
The onchange handler is not executed.

Required fields don't get the `required` attribute, neither the `aria-required="true"` attribute.

### Expected result AFTER applying this Pull Request
Onchange handlers are executed correctly. Required fields get the `required` attribute.

### Documentation Changes Required
The documentation of the color form field is very rudimentary and doesn't mention most of the available attributes. It should be improved overall.

### Open Issues
- The `required` attribute still has no effect for the simple color picker variant. The reason is that the empty value is not an empty string, but `'none'`, which counts as a value both for server-side and client-side validation. I'm not sure how to fix this.
- I also fixed the documentation in the PHP code of the layouts files. For `$control` and `$position`, the original description was copy-pasted, so it should be changed to something more meaningful. However, I'm not sure about a good description here. Maybe @dgrammatiko can help here, as you created these layouts?

2020-09-23 16:17 UTC, dgrammatiko commented
> Maybe @dgrammatiko can help here, as you created these layouts

You can never escape git blame 😔.

I really don't remember what these 2 attributes are doing but the script docs gives some hints:
- control: has a 'hue', so it should be the color selection part (the vertical one)
- position: has a 'bottom left' so I guess it controls where the pop up will be positioned (relative to the input)

Please check the docs, I might got it wrong https://labs.abeautifulsite.net/jquery-minicolors/#settings

2020-09-23 16:28 UTC, Quy commented on layouts/joomla/form/field/color/advanced.php
>  defined('_JEXEC') or die;
```suggestion
defined('_JEXEC') or die;

use Joomla\CMS\Language\Language;
```

2020-09-23 18:09 UTC, Harmageddon commented
@dgrammatiko Okay, thank you! I'll look into it tomorrow.

2020-09-24 09:23 UTC, Harmageddon commented
Updated the docblock accordingly. The other open issue (`required` validation for the simple color picker) remains, but I'd regard it as separate from this PR. If this is regarded as a bug, it should be fixed in another PR.

2021-09-02 14:59 UTC, thednp commented on layouts/joomla/form/field/color/simple.php
> +$required = $required ? ' required aria-required="true"' : '';
The `aria-required="true"` attribute is no longer required.

2021-09-02 15:00 UTC, thednp commented on layouts/joomla/form/field/color/advanced.php
> +$required     = $required ? ' required aria-required="true"' : '';
The `aria-required="true"` attribute is no longer required.

2021-09-02 15:01 UTC, dgrammatiko commented
@thednp hey, quick question: did you manage to get that wasm scss compiler working?

2021-09-02 15:04 UTC, thednp requested changes
Some cleanup needed. I hope devs push this to J4.x as well.

2021-09-02 15:05 UTC, thednp commented
> 
> 
> @thednp hey, quick question: did you manage to get that wasm scss compiler working?

Yes man, thank you for asking. It was a lot of PHP "autoresolve" work.

2021-09-02 15:13 UTC, dgrammatiko commented
> Yes man, thank you for asking. It was a lot of PHP "autoresolve" work.

The reason I asked you was a recent discussion at https://github.com/joomla/joomla-cms/pull/35403 
Glad to hear that you've figured it out 👍

2021-09-02 15:14 UTC, dgrammatiko commented
> Some cleanup needed. I hope devs push this to J4.x as well.

Once you're ready let me know and I'll give it a test

2021-09-02 15:18 UTC, thednp commented
> 
> 
> > Yes man, thank you for asking. It was a lot of PHP "autoresolve" work.
> 
> The reason I asked you was a recent discussion at #35403
> Glad to hear that you've figured it out 👍

I'm using your sass.js implementation with a custom script to run via a blank custom field and works excellent, the only caveat is file names: if multiple files in multiple locations have same name, it might skip some of them in the auto-resolve process, other than that, it's alright.

So yea, I'm not going for the scssphp implementation any time soon, as you nicely advised (thanks).

2021-09-02 15:28 UTC, Quy commented
> Some cleanup needed. I hope devs push this to J4.x as well.

@thednp Is this PR okay other than your suggested changes? Changes in v3.10 will be upmerged into v4.

2021-09-02 15:33 UTC, thednp commented on layouts/joomla/form/field/color/simple.php
>  JHtml::_('jquery.framework');
`JHtml::_('jquery.framework');`

This is surely different in J4.0

2021-09-02 15:33 UTC, thednp commented on layouts/joomla/form/field/color/advanced.php
> +use Joomla\CMS\Language\Language;
Why add this here? I don't think it's used anyway.

2021-09-02 15:36 UTC, dgrammatiko commented on layouts/joomla/form/field/color/advanced.php
> +use Joomla\CMS\Language\Language;
I guess it was autamatically added by the IDE due to 

```php
 * @var   Language  $lang            Language that is active on the site.
 ```

2021-09-02 15:37 UTC, thednp commented
@Quy if my concerns get resolved, all should be fine, I even tested the changes in regards to "onchange", successfully.

2021-09-02 15:45 UTC, Quy commented
@thednp The author appears to be inactive on GitHub so if no response in a few days, then I will make the changes. Thank you so much for your feedback!!

2021-09-08 16:40 UTC, thednp commented
@dgrammatiko do you think dart.sass would work instead of sass.js by medialize?

In my initial impression, I might need some webpack action to create a bundle similar to the one by medialize. Your thoughts?

2021-09-08 17:11 UTC, dgrammatiko commented
@thednp it should, but I haven't tried it. And yes you will need some sort of bundler (I'm in favor of Rollup as their docs are way more approachable and also it's a better bundler for most use cases)

2021-09-09 15:22 UTC, thednp commented
> 
> 
> @thednp it should, but I haven't tried it. And yes you will need some sort of bundler (I'm in favor of Rollup as their docs are way more approachable and also it's a better bundler for most use cases)

I've done some tests into it and haven't managed to get to "consume" the node modules and expose them for web, I used the ESM (`nppm install esm`) which aims to bridge the node and ES APIs, so I'm open to any suggestion you might have.

2021-09-09 15:38 UTC, dgrammatiko commented
@thednp I think it's dart sass is not yet ready for the browser: https://github.com/sass/dart-sass/issues/25#issuecomment-771119524 so for the time stay with sass.js: https://github.com/medialize/sass.js/issues/135

Also, there are some other side projects from the (dart) team so it might be a browser-ready version there, check their repo's and their branches...

2021-09-09 17:01 UTC, thednp commented
I already checked that (sass/dart-sass#25 (comment)), however, even if I change files manually and replace all `require()` instances with their module code I'm still getting tons of errors.

I actually don't know how to bundle npm modules together the way I manage to do with ES6+ modules.

2022-06-12 18:15 UTC, zero-24 commented
@dgrammatiko @thednp can you please confirm what the status here is and whether it should be better closed here and moved to j4 as mentiond inline there are some changes between j3 and j4 already.

2022-07-21 17:11 UTC, zero-24 commented
Will close here for now. Thanks for the work done here :)

2022-07-21 17:11 UTC, closed without merging