Created a HTMLHelper to render an icon
joomla/joomla-cms pull request #30792
Opened 2020-09-28 07:55 UTC by hans2103

Pull Request for Issue # .

### Summary of Changes

This PR will make it possible to use a HTMLHelper to place an icon. 
Just like there is a HTMLHelper to place an anchor and an image. 
- anchor => https://github.com/joomla/joomla-cms/blob/b2e4bf0bd26ab2bb718148459284242bcce8bc56/libraries/src/HTML/HTMLHelper.php#L253
- image => https://github.com/joomla/joomla-cms/blob/b2e4bf0bd26ab2bb718148459284242bcce8bc56/libraries/src/HTML/HTMLHelper.php#L574

### Testing Instructions

- Joomla 4
- See the icon next to the title in the Toolbar
- Apply patch
- See the icon next to the title in the Toolbar ... it is still the same. Only to be implemented by the HTMLHelper now

### Actual result BEFORE applying this Pull Request

placing an icon would be: 

```
<span class="icon-joomla" aria-hidden="true"></span>
<span class="icon-joomla icon-white" aria-hidden="true"></span>
<span class="icon-joomla icon-white" aria-hidden="true" tabindex="0" title="Hello World"></span>
icon-joomla
<span class="fab fa-joomla" aria-hidden="true"></span>
```
### Expected result AFTER applying this Pull Request

```
echo HTMLHelper::icon('joomla');
echo HTMLHelper::icon('joomla', $iconSuffix = 'icon-white');
echo HTMLHelper::icon('joomla', ['tabindex' => 0, 'title' => TEXT::_('HELLO_WORLD')] $iconSuffix = 'icon-white');
echo HTMLHelper::icon('joomla', html = false);
echo HTMLHelper::icon('joomla', $iconPrefix = 'fab fa-');
```

### Documentation Changes Required

most likely...

2020-09-28 08:46 UTC, SharkyKZ commented
This looks pointless and counter-intuitive.

2020-09-28 10:04 UTC, Fedik commented on layouts/joomla/toolbar/title.php
> +	<?php echo HTMLHelper::icon($icon); ?>
Correct use is `HTMLHelper::_('icon', $icon)`

2020-09-28 11:22 UTC, hans2103 commented on layouts/joomla/toolbar/title.php
> +	<?php echo HTMLHelper::icon($icon); ?>
@Fedik Both ways (`HTMLHelper::_('icon'` and `HTMLHelper::icon(`) seem to work.

2020-09-28 11:28 UTC, SharkyKZ commented on layouts/joomla/toolbar/title.php
> +	<?php echo HTMLHelper::icon($icon); ?>
Underscore method is the correct way. This way the method can be overridden by plugins.

2020-09-28 11:30 UTC, richard67 commented on libraries/src/HTML/HTMLHelper.php
> +		$attribs['class'] =  $iconPrefix . $icon;
```suggestion
		$attribs['class'] = $iconPrefix . $icon;
```
Fix PHP code style errors reported by Drone here https://ci.joomla.org/joomla/joomla-cms/35832/1/8

2020-09-28 11:31 UTC, richard67 commented on libraries/src/HTML/HTMLHelper.php
> +			$attribs =  trim(ArrayHelper::toString($attribs));
```suggestion
			$attribs = trim(ArrayHelper::toString($attribs));
```
Fix PHP code style errors reported by Drone here https://ci.joomla.org/joomla/joomla-cms/35832/1/8

2020-09-28 11:31 UTC, hans2103 commented on layouts/joomla/toolbar/title.php
> +	<?php echo HTMLHelper::icon($icon); ?>
adjusted with pr https://github.com/joomla/joomla-cms/pull/30792#pullrequestreview-497366479

2020-09-28 11:43 UTC, HLeithner commented
Can you please remove ` $iconPrefix = 'icon-', $iconSuffix = null, $html = true, $elem = 'span',`

* We shoudn't support custom prefixes (make no sense)
* Don't know why the suffix should be an extra parameter, also php should not be used for styling
* html parameter makes no sense if you supply the complete icon "class" (without icon-)
* $elem should not be provided by php because it's a design/template decision, if I override the icon function because I want to use svg I have a problem if someone provides an unexpected markup.
* Children, don't know if this is a good idea, this would limit us by changing the iconmark to another format (which maybe can't support child elements)

2020-09-28 13:28 UTC, dgrammatiko commented
@hans2103 If you want to introduce a helper to render an icon then you should probably render the icon as an SVG image instead of the outdated, inefficient and mostly inaccessible font Icon. BTW there was a PR doing exactly that some time ago: https://github.com/joomla/joomla-cms/pull/28351

2020-09-28 13:36 UTC, HLeithner commented
@dgrammatiko if I'm write there is no way to use svg and icon fonts at the same time (override each other with css) at least I didn't find a html markup for such a case.

Using SVG sprites doesn't seem to work or only works if the svg is inline? Loading 30 svg separated doesn't seems to be the best way.

Your PR uses inline SVG sprites right and build the svg dynamically right? doesn't sound like a smart way

2020-09-28 13:40 UTC, dgrammatiko commented
> Loading 30 svg separated doesn't seems to be the best way.

There aren't extra Http requests, th icons are inland in the html output, read the code/comments there

2020-09-28 13:47 UTC, HLeithner commented
> > Loading 30 svg separated doesn't seems to be the best way.
> 
> There aren't extra Http requests, th icons are inland in the html output, read the code/comments there

That's what I mean with 'inline SVG sprites' you create a svg on the fly and reference them in another svg at the icon position.

That doesn't sound efficient at least you disable any caching

2020-09-28 14:05 UTC, dgrammatiko commented
> That doesn't sound efficient at least you disable any caching

Caching is useless if your rendering of a page is extremely slow but sequential loads are faster (generally speaking, for some sites this might be tolerated, eg all content is behind a login)

Anyways there are ways to do the API so you can have Icon fonts and SVG, a great example is Typo3: 
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Icon/Index.html

2020-09-30 22:17 UTC, hans2103 commented
> Can you please remove ` $iconPrefix = 'icon-', $iconSuffix = null, $html = true, $elem = 'span',`
> 
> * We shoudn't support custom prefixes (make no sense)

We are working towards action named icons. An icon should be named `save`. When using this HTMLHelper it needs the icon_prefix/iconPrefix. Akeeba adds a ToolbarTitleIcon with name = akeeba. The iconPrefix is needed. 

> * Don't know why the suffix should be an extra parameter, also php should not be used for styling

Currently Joomla core has multiple implementations of extra parameters in the icon. Think about icon-spin, to let the icon-spinner icon animate and rotate. Think about icon-fw to give an icon a specific width. 

> * html parameter makes no sense if you supply the complete icon "class" (without icon-)

I agree and will remove the `$html`

> * $elem should not be provided by php because it's a design/template decision, if I override the icon function because I want to use svg I have a problem if someone provides an unexpected markup.

I agree and will remove the `$elem`

> * Children, don't know if this is a good idea, this would limit us by changing the iconmark to another format (which maybe can't support child elements)

I agree and will remove the `$children`

2020-10-01 06:29 UTC, hans2103 commented
@dgrammatiko I prefer using svg icons too... but first things first... a HTMLHelper for the icon. Adjusting the HTMLHelper to use svg is a next step I think. The impact of this PR would be too big I think.

Looking at a11y perspective an icon should always have a text. This can be a styled label or this can be a piece of text hidden from sighted people. With the last example I mean `<span class="sr-only"></span>`.
With commit https://github.com/joomla/joomla-cms/pull/30792/commits/a3d7b64d48fca86a4d93aba9e7d68d453aa3b9f4 I have added the ability to add both icon and hidden text. Example implementation can be seen on https://github.com/joomla/joomla-cms/pull/30792/commits/3babe70869078af06e9871f3a470aa3966c30aec

2020-10-01 07:32 UTC, brianteeman commented
> Looking at a11y perspective an icon should always have a text.

Like all blanket statements this is not correct

2020-10-01 07:52 UTC, hans2103 commented
> > Looking at a11y perspective an icon should always have a text.
> 
> Like all blanket statements this is not correct

thank you for your comment. Can you rewrite it so it is correct?

2020-10-01 10:01 UTC, dgrammatiko commented
> but first things first... a HTMLHelper for the icon

Again IF you're about to introduce an new API endpoint make sure that 
- The arguments coulee expanded if needed (eg `icon($name = 'default', $options = [])`
- Properly deal with the static files, icons (either svg or font) are not responsibility of the template, should be handled here in this API

2020-10-01 11:19 UTC, hans2103 commented
> This is a remedy. A class that hides the icon for anyone using an screen reader is a hack, svg icons don't need that and thus it's the de facto best practice for 5 or so years...

Take a look at the code please. I'm not hiding the icon, I am adding a `<span class="sr-only">some text here that is not visible for sighted people, but is for screenreaders</span>`
Even svg icons need text. How often do I see that svg icons are optimized so much that the title element with a descriptive text has been removed from the svg. In our current Joomla code we accompany an icon with a sr-only span with the descriptive text. 

> The arguments could be expanded if needed (eg `icon($name = 'default', $options = []`)

@dgrammatiko am I not doing that with `$attribs = []`?

> Properly deal with the static files, icons (either svg or font) are not responsibility of the template, should be handled here in this API

can you give me an example how this should be done properly?

> Move the code in https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/HTML/Helpers/Icons.php or create a new file icon.php

that sounds good... I was not aware of the existence of this file.

2020-10-01 11:25 UTC, dgrammatiko commented
> @dgrammatiko am I not doing that with $attribs = []?

Read again my first comment, you **should not** spread a bunch of arguments in the function, use just 2: the icon name and then the params (an array with anything associated to with the icon you want to present). I already provided a link that explains very nicely why this is the right way...

> can you give me an example how this should be done properly?

Will do

2020-10-01 11:29 UTC, HLeithner commented
> I already provided a link that explains very nicely why this is the right way...

Maybe I missed it why is this the right why? for every static code analyser it's a pain because it can not check if a parameter is valid or not and since PHP 8.0 has named parameters this shouldn't be a problem at all. But maybe I'm wrong.

And why is it not the job of the template if the icon is a svg or an icon? I mean it's easy to override this icon function with your own and replace all icon fonts with svg icons (not possible with only the template you need a plugin). But I think it's not the decision of the component if the icon is a svg icon or a font.

2020-10-01 11:36 UTC, dgrammatiko commented
> Maybe I missed it why is this the right why? 

Argue with Uncle Bob (his book clean code is a must read for every dev): https://www.matheus.ro/2018/01/29/clean-code-avoid-many-arguments-functions/

> And why is it not the job of the template if the icon is a svg or an icon?

Simply because the icons are mostly existing in layouts and layouts should take care of their dependencies (proper modularisation). Template is essentially the orchestrator, echoing the layouts in the right order, it doesn't need to have knowledge of the specifics of every or any layout. If it does it means it is enforcing things to layouts, which is not good (a very good example is https://github.com/joomla/joomla-cms/pull/23742 )

2020-10-01 12:05 UTC, HLeithner commented
> Argue with Uncle Bob (his book clean code is a must read for every dev): https://www.matheus.ro/2018/01/29/clean-code-avoid-many-arguments-functions/

So my conclusion from this text is, that I did it right ;-) I requested to reduce the parameter count (see $html and so on). But it seems you missed the important part, if i'm not wrong he uses Java as an example in refactoring "name, phone, street..." to an Object. Your suggest was to add it to an assoc array that's not the same and error prone. The Object he created is "Address" which likely knows exactly at compile time which parameters can be added. We can do the same by creating an class "iconObject" which hold the needed information so the runtime or a static code analyzer can print an error if you have a typo. Which is not so easy to do with an assoc array.

And I think for this utility functions is a bigger pain to have an object instead of 2 additional parameters (which I would remove anyway, still don't understand why we have a suffix)

> Simply because the icons are mostly existing in layouts and layouts should take care of their dependencies (proper modularisation). Template is essentially the orchestrator, echoing the layouts in the right order, it doesn't need to have knowledge of the specifics of every or any layout. If it does it means it is enforcing things to layouts, which is not good (a very good example is #23742 )

so what's the suggestion on this? I have the "idea" or some thoughts that if this PR is finished and the icon pr is finished (and if it will be merged) we should be possible to simply switch all (at least core icons) simple to svgs (which a variant of your last pr).

2020-10-01 14:14 UTC, dgrammatiko commented
>  we should be possible to simply switch all (at least core icons) simple to svgs 

That would be the perfect scenario, if we can agree on that and write some code to get us there 😉

2020-10-01 14:32 UTC, hans2103 commented
@dgrammatiko and @HLeithner I like both of your suggestions and I look forward to the moment we can use svg instead of fonts. 
Can you make a PR on my PR with your suggestions? Doing so we can all work towards a nice solution.
https://github.com/hans2103/joomla-cms/tree/htmlhelper-for-an-icon

2020-10-01 14:54 UTC, HLeithner commented
@hans2103 small steps as you say ;-) and please move the pr to the icons htmlhelper class.

I think dimitris suggest in his edit and original PR is a bit to over-engineered, I think we don't need to add the provider i'm thinking the other way around (mainly for core), we as core provide x icon functions. If you want to use them you can use it, if you need another one you have to do your own inclusion/registration what ever. Also setting the "type" (svg/font) at the layout level is wrong and you can't override it in a template.

And if all our icons have to use such a method we hit the most complexity possible.

```php
<?php echo HTMLHelper::_('icon.icon', 'info', 'svg', ['provider' => 'fontawesome-free', 'group' => 'solid', 'classes' => ['fa', 'demo-class'], 'attributes' => ['data-foo' => 'bar', 'id' => 'foobar']], 'sr-text' => Text::_('INFO')]); ?>
```
I mean nobody will use this.

2020-10-01 14:57 UTC, dgrammatiko commented
@HLeithner actually if someone is using Fontawesome (due to the defaults) the code will be way simpler:

```php
<?php echo HTMLHelper::_('icon.icon', 'info', 'svg', [ 'classes' => ['fa', 'demo-class'], ''sr-text' => Text::_('INFO')]); ?>
```

2020-10-01 15:04 UTC, hans2103 commented
The expected output is 
```
<span class="fa fas-info"></span>
<span class="sr-only"><?php echo Text::_('INFO')]); ?></span>
```

the already existing styling for sr-only is
```
.sr-only {
    border: 0;
    clip: rect(0,0,0,0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
    white-space: nowrap;
}
```

This piece of styling reduces the element to a non-visible but still existing element. 
Combining `sr-only` with the icon will result in a non-visible icon. 

Dinner now... will check on your suggestions later today or tomorrow morning. Thank you for your effort.

2020-10-01 15:07 UTC, dgrammatiko commented
> Combining sr-only with the icon will result in a non-visible icon.

Then the code becomes even simpler:

```php
<?php echo HTMLHelper::_('icon.icon', 'info', 'font'); ?>
// 2 Arguments: Name of the icon, expected format
```

2020-10-02 07:24 UTC, hans2103 commented
as a frontend developer I stumble upon my lack of decent PHP knowledge to create the content of the new /icon.php file. 
@dgrammatiko and / or @HLeithner can you create a PR on this PR with your suggested /Icon.php file?

2020-10-02 09:31 UTC, Fedik commented
just put your `function icon(...) ...` code in to this one https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/HTML/Helpers/Icons.php
and then can call as 
```
echo HTMLHelper::_('icons.icon', ....
```

2020-10-02 09:33 UTC, dgrammatiko commented
> can you create a PR on this PR with your suggested /Icon.php file

I need to do some research on the FA css/fonts, probably this weekend

2020-10-02 18:01 UTC, hans2103 commented
as suggested.. I've moved the function to libraries/src/HTML/Helpers/Icons.php
and adjusted the call with `HTMLHelper::_('icons.icon'....`

2020-10-02 18:08 UTC, hans2103 commented
if the output is:
```
<span class="fa fas-info"></span>
<span class="sr-only"><?php echo Text::_('INFO')]); ?></span>
```

and the input is
```
<?php echo HTMLHelper::_('icons.icon', 'info', 'font', [  'sr-text' => Text::_('INFO'), ]); ?>
```


should we add a JLayout too where icon-prefix, extra classNames are handled?

2020-10-02 18:11 UTC, dgrammatiko commented
> should we add a JLayout too where icon-prefix, extra classNames are handled?

The second argument can have prefix suffix or am I getting something wrong (eg `foo-icon` or `icon-bar`)

2020-10-03 14:03 UTC, hans2103 commented
> > should we add a JLayout too where icon-prefix, extra classNames are handled?
> 
> The second argument can have prefix suffix or am I getting something wrong (eg `foo-icon` or `icon-bar`)

What do you think about not handling the icon-prefix over here in the HTMLHelper, but set it using the JLayout?
That way this HTMLHelper stays a functional thing forwarding some stuff and let the JLayout handle the HTML .

2020-10-17 18:49 UTC, degobbis commented
Here my 2 cents, if relevant.
I also think the parameters `$iconPrefix` and `$iconSuffix` are not needed.

Let's take the change from `layouts/joomla/searchtools/default/noitems.php`:
The expected output for the icon is `<span class="fas fa-info-circle" aria-hidden="true"></span>`, but if we use your code now, we get `<span class="icon-icon-fas fa-info-circle" aria-hidden="true"></span>`.

This results because the prefix is defined by default and also set for a second time in `$attribs['class'] = $iconPrefix . $icon;`.

So if the prefix is not set by default, a developer has to consider this individually, then he can write it directly into the actual class and the parameters become unneeded. The same applies to the suffix.

2020-10-21 07:34 UTC, hans2103 commented
Updated implementation:

```
<?php echo HTMLHelper::_('icons.icon', 'fas fa-info-circle', Text::_('INFO')); ?>
```

after merge of #30707 this has to change to:
```
<?php echo HTMLHelper::_('icons.icon', 'icon-info-circle', Text::_('INFO')); ?>
```

Method for implementation has been simplified to:
(asa @dgrammatiko suggested in https://github.com/joomla/joomla-cms/pull/30792#issuecomment-702028859)
```
	/**
	 * Method to write a `<span>` element for an icon
	 *
	 * @param   string        $icon        The funcitonal name for an icon.
	 * @param   string        $srOnly      Screen Reader text if no visible text is placed
	 * @param   array         $attribs     Attributes to be added to the wrapping element
	 *
	 *
	 * @return  string
	 *
	 * @since   4.0
	 */
	public static function icon($icon = 'default', $srOnly = null, $attribs = [])
	{
		if (isset($attribs['class']))
		{
			$icon = $icon . ' ' . $attribs['class'];
		}

		$attribs['class'] = $icon;

		if (!isset($attribs['aria-hidden']))
		{
			$attribs['aria-hidden'] = 'true';
		}

		if (isset($srOnly))
		{
			$text = htmlspecialchars($srOnly, ENT_COMPAT, 'UTF-8');
			$srOnly = '<span class="sr-only">' . $text . '</span>';
		}

		return '<span ' . trim(ArrayHelper::toString($attribs)) . '></span>' . $srOnly;
	}
```

2020-10-21 18:36 UTC, Quy commented on libraries/src/HTML/Helpers/Icons.php
> +	 * @param   string        $icon        The funcitonal name for an icon.
Per Joomla! Coding Standards:

> Commonly a line after the tag @param consists of the following three parts in order of appearance:
> 
> * variable type (There must be 3 spaces before variable type.)
> * variable name (There must be 2 spaces after the longest type.)
> * variable description (There must be 2 spaces after the longest variable name.)
> 
> If there are more than one @param the type, names and description have to be aligned.

Typo `funcitonal`

2020-10-21 18:41 UTC, Quy commented on libraries/src/HTML/Helpers/Icons.php
> +	 * @since   4.0
```suggestion
	 *
	 * @return  string
	 *
	 * @since   __DEPLOY_VERSION__
```

2020-10-21 21:01 UTC, Quy commented on libraries/src/HTML/Helpers/Icons.php
> +			$icon = $icon . ' ' . $attribs['class'];
```suggestion
			$icon .= ' ' . $attribs['class'];
```

2020-10-21 22:21 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +	 * @param   string        $icon        The funcitonal name for an icon.
fixed suggestions in commit https://github.com/joomla/joomla-cms/pull/30792/commits/1a950bfabc28767c52d00b1b7d1bb9bf10a35bcc

2020-10-21 22:49 UTC, Quy commented on libraries/src/HTML/Helpers/Icons.php
> +		if (isset($srOnly) && !empty($srOnly))
```suggestion
		if (!empty($srOnly))
```

2020-10-22 06:19 UTC, SharkyKZ commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon($icon = 'default', $srOnly = '', $attribs = [])
```suggestion
	public static function icon(string $icon = 'default', string $srOnly = '', array $attribs = [])
```

2020-10-22 06:20 UTC, SharkyKZ commented on libraries/src/HTML/Helpers/Icons.php
> +		if (!empty($srOnly))
```suggestion
		if ($srOnly !== '')
```

2020-10-22 17:39 UTC, Quy commented on libraries/src/HTML/Helpers/Icons.php
> +		return '<span ' . trim(ArrayHelper::toString($attribs)) . '></span>' . $srOnly;
Is is necessary to apply `trim`?

2020-10-22 17:48 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +		return '<span ' . trim(ArrayHelper::toString($attribs)) . '></span>' . $srOnly;
@quy I think I've added it because I saw obsolete spacing at the end.

2020-10-22 17:52 UTC, Quy commented on libraries/src/HTML/Helpers/Icons.php
> +		return '<span ' . trim(ArrayHelper::toString($attribs)) . '></span>' . $srOnly;
Here is a var_dump on `ArrayHelper::toString($attribs)` without `trim` and the result:

> string(63) "class="fas fa-fas fa-home cpanel icon-white" aria-hidden="true""

2020-10-22 18:59 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +		return '<span ' . trim(ArrayHelper::toString($attribs)) . '></span>' . $srOnly;
removed in commit a414b8467f8d47dffe4992316154510b04467ecd

2020-10-22 19:24 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 846466f5bc47c80e876825cc9b82b968010abb74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30792">issues.joomla.org/tracker/joomla-cms/30792</a>.</sub>

2020-10-22 19:32 UTC, SharkyKZ commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon(string $icon = 'fas fa-default', string $srOnly = '', array $attribs = [])
There is no `fas fa-default` icon. Why even add a default here?

2020-10-23 07:06 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon(string $icon = 'fas fa-default', string $srOnly = '', array $attribs = [])
adding a default saves me from adding a check if the icon is set or not. 
I will add the check and return null if no icon is set.

2020-10-23 07:09 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon(string $icon = 'fas fa-default', string $srOnly = '', array $attribs = [])
see commit 62c833c2ddd83d17bb8582fcf2cc33726b1a3aed

2020-10-23 15:21 UTC, SharkyKZ commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon(string $icon = '', string $srOnly = '', array $attribs = [])
Icon should not be optional.

```suggestion
	public static function icon(string $icon, string $srOnly = '', array $attribs = [])
```

2020-10-23 15:23 UTC, SharkyKZ commented on libraries/src/HTML/Helpers/Icons.php
> +			return '';
Maybe overkill but do you want to throw an exception here?

2020-10-24 15:01 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +			return '';
I never implemented an exception. Can you create a PR on mine, so I can learn from it?

2020-10-26 08:55 UTC, SharkyKZ commented on libraries/src/HTML/Helpers/Icons.php
> +			return '';
Change return to `throw new \InvalidArgumentException('error message here'); and document with `@throws`.

Again, I'm not sure if this is not overkill. I see only one instance of exception being thrown in HTML helpers. But maybe that's because we have poor sanity checks in general.

2020-10-26 09:57 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +			return '';
@SharkyKZ implemented with commit https://github.com/joomla/joomla-cms/pull/30792/commits/04c3854357a557020e9d7bf5e11a1a4ddb1ba862

2020-10-26 14:08 UTC, Quy commented on administrator/language/en-GB/lib_joomla.ini
> +JLIB_HTML_ICONS_NO_ICON="No icon provided
```suggestion
JLIB_HTML_ICONS_NO_ICON="No icon provided"
```

2020-10-26 14:11 UTC, Quy commented on administrator/language/en-GB/lib_joomla.ini
> +JLIB_HTML_ICONS_NO_ICON="No icon provided
```suggestion
JLIB_HTML_ICONS_NO_ICON="No icon provided."
```

2020-10-26 15:44 UTC, SharkyKZ commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon(string $icon, string $srOnly = '', array $attribs = [])
```suggestion
	public static function icon(string $icon, string $srOnly = '', array $attribs = []): string
```

2020-10-26 16:40 UTC, N6REJ commented
@hans2103 you might find https://github.com/joomla/joomla-cms/pull/31190 interesting.

2020-10-26 17:42 UTC, hans2103 commented
> @hans2103 you might find #31190 interesting.

Can your svg improvement be merged with this PR?

2020-10-26 20:17 UTC, Quy commented
I have tested this item :white_check_mark: successfully on b1660ab4e5e736a123061bccd9df953dc79ffc50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30792">issues.joomla.org/tracker/joomla-cms/30792</a>.</sub>

2020-10-27 06:59 UTC, N6REJ commented
> > @hans2103 you might find #31190 interesting.
> 
> Can your svg improvement be merged with this PR?

baby steps.. mine seems to be up for debate as always.

2020-10-27 07:14 UTC, infograf768 commented
Please, when modifying the lib_joomla.ini file, modify both files (admin and site).
Can't be merged until done.

2020-10-27 08:00 UTC, hans2103 commented
@infograf768 just added the language string to the fronted with commit https://github.com/joomla/joomla-cms/pull/30792/commits/631ab068f081f727295aa4dc1bedbb8dd2a26a35

2020-10-27 08:38 UTC, infograf768 commented on language/en-GB/lib_joomla.ini
>  JLIB_HTML_GOTO_POSITION="Go to %s page"
Missing period

2020-10-27 10:34 UTC, hans2103 commented on language/en-GB/lib_joomla.ini
>  JLIB_HTML_GOTO_POSITION="Go to %s page"
removed period in admin lib_joomla.ini with commit cb05e071b6f364dc7f3f5241ec0084fef2ee8dad
Is out of scope for this PR.

2020-10-28 22:52 UTC, Quy commented
I have tested this item :white_check_mark: successfully on b1660ab4e5e736a123061bccd9df953dc79ffc50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30792">issues.joomla.org/tracker/joomla-cms/30792</a>.</sub>

2020-10-30 22:47 UTC, N6REJ commented
I have tested this item :white_check_mark: successfully on b1660ab4e5e736a123061bccd9df953dc79ffc50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30792">issues.joomla.org/tracker/joomla-cms/30792</a>.</sub>

2020-10-31 00:49 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30792">issues.joomla.org/tracker/joomla-cms/30792</a>.</sub>

2020-10-31 08:16 UTC, dgrammatiko commented
@quy please remove Rtc from this there are a number of issues I pointed in my comments that are not addressed yet

2020-10-31 09:43 UTC, hans2103 commented
@dgrammatiko please describe them again. 
Or can they be fixed in a new PR?

2020-10-31 09:46 UTC, dgrammatiko commented
It's really bad idea to merge a half done API so it cannot be done in a new pr, needs to be fixed here. Read my comment about handling the related assets and also the api needs to be able to either echo font icon or svg icon html

2020-10-31 10:13 UTC, hans2103 commented
@dgrammatiko 
do you mean this part of the comment copied from https://github.com/joomla/joomla-cms/pull/30792#issuecomment-700006784
> - Since you're introducing an API for icons it seems that you're missing the most important aspect: decouple the assets. Right now template are dictating the behaviour (eg loading the font always) which -A. it's not template'e responsibility -B. the API should load any assets required. Eg. If my landing page doesn't have any icons why does the template should enforce the loading of unneeded css and fonts? (the template has no clue what each layout is using thus the only safe place to add assets in in the layouts NOT IN the template as these are globally loaded [monolithic approach, really outdated])

2020-11-26 10:31 UTC, hans2103 commented
Adjusted `icons.icon` to get triggered by `type = svg`
Added the FontAwesome SVG icons

But... help needed to call for the FontAwesome SVG icons. 

Should a reference to /media/vendor/fortawesome-free/svgs/regular be made within the function icon? => I hope not... it is not up to this function to know where the svg icons are. 
Or should this be done via a JLayout where an easy override can be chosen for another library? => makes sense to me.

2020-11-26 10:33 UTC, dgrammatiko requested changes

2020-11-26 10:33 UTC, dgrammatiko commented on build/build-modules-js/settings.json
> +          "svgs": "svgs",
This needs to be`"svgs": "images",`

2020-11-26 10:33 UTC, dgrammatiko commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon(string $icon, string $srOnly = '', string $type = '', array $attribs = []): string
Please remove the srOnly or move it as a param to attribute. Actually please bring the logic from my PR https://github.com/joomla/joomla-cms/pull/28351/files#diff-1f3d4b0ff411d275d94c1538ef487ef75d4450d772ad2cf712b5796467917f6dR214-R246
That allows any type of attributes to be attached to the inserted svg...

2020-11-26 10:35 UTC, hans2103 commented on build/build-modules-js/settings.json
> +          "svgs": "svgs",
solved in commit 83551d9a7076d514fb4c193773c11f2cb94c74e0

2020-11-26 11:26 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon(string $icon, string $srOnly = '', string $type = '', array $attribs = []): string
applied your changes... some of them. 
I don't want to use svg-sprite at this moment... out of scope for this change. 

But.. I need some help to get provide the correct path to the function `icons.svg`

suggestions?

2020-11-26 11:36 UTC, dgrammatiko commented on libraries/src/HTML/Helpers/Icons.php
> +	public static function icon(string $icon, string $srOnly = '', string $type = '', array $attribs = []): string
> I don't want to use svg-sprite at this moment... out of scope for this change.

You're missing the point my friend, if you're not controlling the output (eg current implementation) you're essentially allowing broken HTML to be applied in any page. Let me explain: the svg helper will echo each fragment every time you call it, meaning it can inflate the output but worse than that it could echo multiple svgs with the same id which is invalid HTML. Unfortunately if you want to do SVGs correctly you need somehow to take control of the fragments you're inserting or the API you're introducing is prone to undesired side effects

2020-11-26 11:52 UTC, SharkyKZ commented
This PR makes even less sense now.

2020-11-26 12:14 UTC, brianteeman commented on libraries/src/HTML/Helpers/Icons.php
> +		}
It wouldnt make sense to have sr-only text if for some reason aria-hidden is not true

2020-11-26 12:16 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +		}
Attribute `aria-hidden` is always true, unless it is set otherwise. 
Do you mean that if it is set otherwise, the span element with className `sr-only` should not be set?

2020-11-26 12:19 UTC, hans2103 commented
@SharkyKZ 
> This PR makes even less sense now.

could you explain me why?

2020-11-26 12:41 UTC, brianteeman commented on libraries/src/HTML/Helpers/Icons.php
> +		}
yes

2020-11-26 12:45 UTC, hans2103 commented on libraries/src/HTML/Helpers/Icons.php
> +		}
solved in commit 4a765c547bdf4761538a8ab3b8f0044f4ce616d2

2021-05-11 06:47 UTC, hans2103 commented
closing this for now... will create a new PR when time feels good, wind is blowing from the right direction, sun is shining and such. :-)

2021-05-11 06:47 UTC, closed without merging