[4.0] Fix icon to display adjacent to field
joomla/joomla-cms pull request #30897
Opened 2020-10-02 23:00 UTC by Quy

Pull Request for Issue #29742.

### Testing Instructions
Edit the login module
Set `Display Labels` = text
Go to front end

### Actual result BEFORE applying this Pull Request
<img width="311" alt="29742-before" src="https://user-images.githubusercontent.com/368084/94975920-0f347b00-04c8-11eb-9404-c9d5e9dd94d5.png">

### Expected result AFTER applying this Pull Request
![29742-after](https://user-images.githubusercontent.com/368084/94975942-21161e00-04c8-11eb-9ccc-53680e965c21.png)

2020-10-02 23:21 UTC, brianteeman commented
using title to display help text is not only ugly but its not accessible

2020-10-03 09:16 UTC, particthistle commented
I have tested this item :white_check_mark: successfully on f3b42c18682af840670e57f51c835804aa246756<br /><br />Layout issue that the PR is designed to resolve is corrected by the PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30897">issues.joomla.org/tracker/joomla-cms/30897</a>.</sub>

2020-10-03 09:53 UTC, chmst commented
I agree with @brianteeman that the title attribute is contra a11y. You can add a tooltip instead.

2020-10-03 16:40 UTC, adj9 commented
I have tested this item :white_check_mark: successfully on f3b42c18682af840670e57f51c835804aa246756<br /><br />Done :)
OK! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30897">issues.joomla.org/tracker/joomla-cms/30897</a>.</sub>

2020-10-04 11:16 UTC, Scrabble96 commented
> 
> 
>  You can add a tooltip instead.

Tooltips don't show on iPad Safari and probably not on Android devices not using a mouse, either.

2020-10-17 08:05 UTC, ChrisHoefliger commented
Tested successfully

2020-10-17 16:47 UTC, richard67 commented
> I agree with @brianteeman that the title attribute is contra a11y. You can add a tooltip instead.

@brianteeman @chmst Does it mean we should not set this PR to RTC? Or does it mean it should be changed with another, future PR?

2020-10-30 06:24 UTC, gostn commented
need label:"Information Required"

2020-10-30 13:43 UTC, N6REJ requested changes
`fas fa-question fa-fw` should be `icon-question icon-fw`

2020-12-01 07:35 UTC, gostn commented
who care on drafts having two successfully test?

2020-12-01 07:36 UTC, richard67 commented
@gostn It's the author who decides if a PR is draft or not.

2020-12-01 07:40 UTC, gostn commented
@Quy what now, test are wastet time?

2020-12-01 09:50 UTC, HLeithner commented
> Quy what now, test are wastet time?

@gostn claim down, PRs may involve over time and if Quy founds something that's not right or have to be changed because of other PRs are merged in the meantime it's good that the PR opener sets the PR to draft.

2020-12-01 10:45 UTC, gostn commented
i dont make pressure, but at issutracker i list pr having 2 successfully test but not rtc – draft isnt shown in this list:

![Screen Shot 2020-12-01 at 11 43 20](https://user-images.githubusercontent.com/71960554/100730560-8011e980-33ca-11eb-9cbb-096804049f26.png)

2020-12-01 16:02 UTC, Quy commented
Sorry I don't have much time these days to contribute.

@gostn Accessibility to be fixed per Brian https://github.com/joomla/joomla-cms/pull/30897#issuecomment-702997741
See https://github.com/joomla-extensions/patchtester/issues/286 regarding Draft status.

2020-12-03 02:58 UTC, N6REJ commented on modules/mod_login/tmpl/default.php
> +								<span class="fas fa-question fa-fw" aria-hidden="true"></span>
<span class="fas fa-question fa-fw" aria-hidden="true"></span> should be
<span class="icon-question icon-fw" aria-hidden="true"></span>

2020-12-03 02:59 UTC, N6REJ requested changes
`<span class="fas fa-question fa-fw" aria-hidden="true"></span>` should be
`<span class="icon-question icon-fw" aria-hidden="true"></span>`

2020-12-03 15:34 UTC, Quy commented on modules/mod_login/tmpl/default.php
> +								<span class="fas fa-question fa-fw" aria-hidden="true"></span>
```suggestion
								<span class="icon-question icon-fw" aria-hidden="true"></span>
```

2020-12-03 15:35 UTC, Quy commented on modules/mod_login/tmpl/default.php
> +								<span class="fas fa-question fa-fw" aria-hidden="true"></span>
```suggestion
								<span class="icon-question icon-fw" aria-hidden="true"></span>
```

2020-12-04 08:29 UTC, infograf768 commented
conflicts

2020-12-04 08:42 UTC, infograf768 commented
If I choose icons instead of display text (after correcting conflicts), I get
![Screen Shot 2020-12-04 at 09 41 29](https://user-images.githubusercontent.com/869724/101141691-f144dd00-3614-11eb-8c5c-78589af60a92.png)

Is that intended?

2020-12-05 08:05 UTC, ashvini77 commented
I have tested this item :white_check_mark: successfully on 13dbfa615e4c8acb3f93de3db7a623c70815070d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30897">issues.joomla.org/tracker/joomla-cms/30897</a>.</sub>

2020-12-05 11:03 UTC, Scrabble96 commented
When the Cassiopeia updates were proposed in PR #31520 there was a comment (I can't find it now) suggesting that the checkbox size (next to 'remember me') was enlarged. I suggested the following code and now also include the RTL version. Perhaps this could be included with this PR if suitable?

`/* ltr */`
`.com-users-login fieldset .control-label {  margin-left: 2rem; }`
`.com-users-login fieldset input[type="checkbox"].inputbox { position: relative; transform: scale(1.5);  top: -2rem; }`

`/* rtl */`
`.com-users-login fieldset .control-label {  margin-right: 2rem; }`

2020-12-06 07:11 UTC, gostn commented
I have tested this item :white_check_mark: successfully on 13dbfa615e4c8acb3f93de3db7a623c70815070d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30897">issues.joomla.org/tracker/joomla-cms/30897</a>.</sub>

2020-12-06 17:44 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30897">issues.joomla.org/tracker/joomla-cms/30897</a>.</sub>

2020-12-06 17:46 UTC, Quy commented
@Scrabble96 Thank you for the code. It should be done in a separate PR since it is not related.

This PR fixes the alignment only. Let's fix the ay11 issue in a separate PR.

2020-12-06 19:20 UTC, merged

2020-12-06 19:20 UTC, drmenzelit commented
Thanks