[4.0] MultilangstatusAdminHelper performance
joomla/joomla-cms pull request #31111
Opened 2020-10-16 11:20 UTC by Denitz

### Summary of Changes

Minimize the DB queries in MultilangstatusAdminHelper

### Testing Instructions

Enable multilang plugin and browser backend.

### Actual result BEFORE applying this Pull Request

See that each admin page always has 3 queries:

```
SELECT `enabled`
FROM `jos_extensions`
WHERE `type` = 'module' AND `element` = 'mod_multilangstatus'
\administrator\modules\mod_multilangstatus\src\Helper\MultilangstatusAdminHelper.php:46

SELECT `published`
FROM `jos_modules`
WHERE `module` = 'mod_multilangstatus'
\administrator\modules\mod_multilangstatus\src\Helper\MultilangstatusAdminHelper.php:76

UPDATE `jos_modules`
SET `published` = 1
WHERE `module` = 'mod_multilangstatus'
\administrator\modules\mod_multilangstatus\src\Helper\MultilangstatusAdminHelper.php:111
```
Cache is not cleaned after the module state is auto-changed.

### Expected result AFTER applying this Pull Request

Only a single first query is left.

Cache is cleaned after the module state is auto-changed.

### Documentation Changes Required

No.

2020-10-17 06:29 UTC, ceford commented
For me there are always two queries left after applying the patch. The one left out is the Update query which I guess should only be called if the published state is changed. Typo: in instructions I think browser should be browse - it made me wonder if there was a browser plugin. My mod_multilangstatus is unpublished.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31111">issues.joomla.org/tracker/joomla-cms/31111</a>.</sub>

2020-10-17 08:59 UTC, Denitz commented
@ceford I re-tested the patch and definitely see that only single first query is left:

```
SELECT `enabled`
FROM `jos_extensions`
WHERE `type` = 'module' AND `element` = 'mod_multilangstatus'
```

If "System - Language Filter" plugin is disabled, we have two queries one time (select enabled + updated published to 1) and next only single query again on the further page loads.

2020-10-17 10:52 UTC, ceford commented
I have tested this item :white_check_mark: successfully on e014072219cdc563e4eb6fb628515045d435b0ec<br /><br />I can now confirm that the System Language Filter plugin needs to be enable and then on the second and subsequent page loads there is only one query.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31111">issues.joomla.org/tracker/joomla-cms/31111</a>.</sub>

2020-10-17 13:49 UTC, chmst commented
I have tested this item :white_check_mark: successfully on e014072219cdc563e4eb6fb628515045d435b0ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31111">issues.joomla.org/tracker/joomla-cms/31111</a>.</sub>

2020-10-17 16:44 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31111">issues.joomla.org/tracker/joomla-cms/31111</a>.</sub>

2020-10-17 17:20 UTC, HLeithner requested changes

2020-10-17 17:20 UTC, HLeithner commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		return isset($result) ? (bool) $result : null;
Why are you returning null if the query fails? I mean if this query fails the rest of joomla fail too. 
Anyway returning `null` in this case make no sense. if you like to keep it return false in the catch block and cast the `$result` to boolean.

2020-10-17 17:20 UTC, HLeithner commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		return isset($result) ? (int) $result : null;
same as above without the `int` cast, makes no sense to return `NULL`

2020-10-17 17:20 UTC, HLeithner commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		if ($state == -2 || $state === null)
please use type safe operators
```suggestion
		if ($state === -2 || $state === null)
```

2020-10-17 17:20 UTC, HLeithner commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +			if ($state != 1)
```suggestion
			if ($state !== 1)
```

2020-10-17 17:20 UTC, HLeithner commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		elseif ($state != 0)
```suggestion
		elseif ($state !== 0)
```

2020-10-17 17:20 UTC, HLeithner commented on administrator/modules/mod_user/mod_user.php
> +if (class_exists(MultilangstatusAdminHelper::class) && (null !== MultilangstatusAdminHelper::isEnabled($app, $db)))
If I'm not wrong this changes the behavior completely.

` (null !== MultilangstatusAdminHelper::isEnabled($app, $db))`
This part will always be true except if the database query is broken and raises an exception. I don't think that this is expected.

2020-10-17 17:20 UTC, HLeithner commented on libraries/src/Cache/CacheController.php
> + * @mixin Cache Proxy all CacheController absent method calls to Cache
cs
```suggestion
 * @mixin  Cache Proxy all CacheController absent method calls to Cache
```

But if I'm not wrong you have to list all classes that are mixin?

2020-10-17 17:26 UTC, richard67 commented
Back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31111">issues.joomla.org/tracker/joomla-cms/31111</a>.</sub>

2020-10-17 20:27 UTC, richard67 commented
There are review comments. Unfortunately they are not visible in the issue tracker, only on GitHub, so I add this comment here to enable issue tracker readers at least to see what's the reason why the PR doesn't have RTC.

2020-10-18 07:23 UTC, Denitz commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		return isset($result) ? (bool) $result : null;
Boolean true/false indicates isEnabled status. If not extension is not installed, we don't know the status, it's not false.

2020-10-18 07:24 UTC, Denitz commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		return isset($result) ? (int) $result : null;
Same, we should know the state of extension. It can't be false if extension is not found!

2020-10-18 07:25 UTC, Denitz commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		if ($state == -2 || $state === null)
Not my code...

2020-10-18 07:36 UTC, Denitz commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		return isset($result) ? (bool) $result : null;
Sorry, the current code catches exception, I didn't change it. I assume that the expected behavior was not raise error.

2020-10-18 07:37 UTC, Denitz commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		elseif ($state != 0)
Agree

2020-10-18 07:38 UTC, Denitz commented on administrator/modules/mod_user/mod_user.php
> +if (class_exists(MultilangstatusAdminHelper::class) && (null !== MultilangstatusAdminHelper::isEnabled($app, $db)))
No. If module is not installed, the code is not executed.

2020-10-18 07:39 UTC, Denitz commented on libraries/src/Cache/CacheController.php
> + * @mixin Cache Proxy all CacheController absent method calls to Cache
No. CacheController proxifies only Cache methods via __call. This comment helps with IDE.

2020-10-18 10:08 UTC, richard67 commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		return isset($result) ? (bool) $result : null;
> If an extension is not installed

In J4 we can be more or less sure that it is installed because it has the (new in J4) locked status, so it can't be uninstalled.

2020-10-18 10:09 UTC, richard67 commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		return isset($result) ? (int) $result : null;
Same as above.

2020-10-18 10:09 UTC, richard67 commented on administrator/modules/mod_user/mod_user.php
> +if (class_exists(MultilangstatusAdminHelper::class) && (null !== MultilangstatusAdminHelper::isEnabled($app, $db)))
Same as above: The module is locked in J4 so it can't be uninstalled with "normal" methods.

2020-10-18 10:50 UTC, richard67 commented on administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
> +		return isset($result) ? (bool) $result : null;
Hmm, wait, but the module can be trashed and deleted ... the lock helps only with the extension table .. forget my comment.

2020-10-18 10:52 UTC, richard67 commented on administrator/modules/mod_user/mod_user.php
> +if (class_exists(MultilangstatusAdminHelper::class) && (null !== MultilangstatusAdminHelper::isEnabled($app, $db)))
Hmm, I was wrong, the module can't be uninstalled as an extension, that's what the lock does, but it can be trashed and deleted as a module, and the MultilangstatusAdminHelper checks the module table.

2020-10-18 10:58 UTC, HLeithner commented
I looked at the reason why this code is called and it's completely wrong in my opinion.

mod_user calls this on every page load only to magically activate/deactivate this module based on the languagefilter plugin...

I would suggest so remove this functionality:
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_user/mod_user.php#L22-L33

And this magical helper too.

If someone thinks it's really needed to display this module for multilingual sites (which I don't think it's needed) @bembelimen suggest to always activate the module and return "" if the multilingual functionality is disabled.

2020-10-19 05:56 UTC, Denitz commented
@HLeithner I totally agree that it's better to remove this code completely. Who can make the final decision?

2020-10-19 06:19 UTC, HLeithner commented
in this case @wilsonge but I'm pretty sure @infograf768 want to look at this

2020-10-19 09:31 UTC, infograf768 commented
If anyone cares about my comment, displaying the multilangstatus module when languagefilter is on is a really nice new feature in J4. I don't know how many ms are concerned but if we could keep it, it would be good for our users.

I don't really understand why that code is in mod_user (could not get the history in github as the file name was changed) instead of the languagefilter plugin itself, therefore being used only when the plugin is enabled/disabled.

2020-10-19 09:37 UTC, richard67 commented
> I don't really understand why that code is in mod_user (could not get the history in github as the file name was changed)

I think it was mod_status before.

2020-10-19 09:49 UTC, infograf768 commented
It was in  a new module: mod_status_user.php
https://github.com/joomla/joomla-cms/commit/36fd27114d005951c42988a9af2ff95e7f67d1c0#diff-fdad49126781a103f20288ca4be07c78b271d19c893db36c51cf391ca6e7e578
<img width="773" alt="Screen Shot 2020-10-19 at 11 45 22" src="https://user-images.githubusercontent.com/869724/96429076-d05d2f80-1200-11eb-901b-81acea96849f.png">

2020-10-19 09:58 UTC, HLeithner commented
Ok I would like to suggest the following solution and I hope @Denitz can implement it.

* Remove the `MultilangstatusAdminHelper` (if it's only function is to activate the module).
* Remove the related code from `mod_user` 
* Activate the `mod_multilangstatus` per default on new installations
* Check in `mod_multilangstatus` if multilanguage is active and if not return without any output.

2020-10-19 10:04 UTC, infograf768 commented
> Check in mod_multilangstatus if multilanguage is active and if not return without any output.

We check that already in the module code...

<img width="485" alt="Screen Shot 2020-10-19 at 12 01 17" src="https://user-images.githubusercontent.com/869724/96430755-dbb15a80-1202-11eb-9988-9f9a1715f141.png">

2020-10-19 10:07 UTC, richard67 commented
>     * Activate the `mod_multilangstatus` per default on new installations

That's to be done here

https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/base.sql#L585

and here

https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/postgresql/base.sql#L610

by changing `NULL, NULL, 0` to `NULL, NULL, 1`.

2020-10-19 10:59 UTC, HLeithner commented
> > Check in mod_multilangstatus if multilanguage is active and if not return without any output.
> 
> We check that already in the module code...
> 
> <img alt="Screen Shot 2020-10-19 at 12 01 17" width="485" src="https://user-images.githubusercontent.com/869724/96430755-dbb15a80-1202-11eb-9988-9f9a1715f141.png">

Yes I know but most of the joomla sites are not multilingual and always showing the icon in the upper right corner makes no sense to me. I personally wouldn't activate it by default, but only showing the content if multi language is active is a compromise (even if I have to disable the module anyway because I don't use the standard joomla multi language system as it is intended)

2020-11-02 07:43 UTC, Denitz commented
> Remove the MultilangstatusAdminHelper (if it's only function is to activate the module).
> Remove the related code from mod_user
> Activate the mod_multilangstatus per default on new installations
> Check in mod_multilangstatus if multilanguage is active and if not return without any output.

@HLeithner Done.

2020-11-02 07:51 UTC, alikon commented
please add the update .sql too

2020-11-02 07:54 UTC, richard67 commented
> please add the update .sql too

@alikon As far as I could see, @HLeithner has requested that only for new installations, not for updates, so it should not need any update sql script. @HLeithner Correct me if I'm wrong.

2020-11-02 08:14 UTC, HLeithner commented
richard is right, I think for websites that already exists have it already activated or are not multilingual. ymmv

2020-11-02 08:16 UTC, HLeithner approved these changes

2020-11-07 12:29 UTC, HLeithner commented
@Denitz I'm sorry I missed the exact same PR by @SharkyKZ #30113 I'm closing this one and merge the other one, thanks for your engagement.

2020-11-07 12:29 UTC, closed without merging