Set alt-text for the feed-image if no other text is displayed (a11y)
joomla/joomla-cms pull request #31180
Opened 2020-10-21 07:32 UTC by chmst

Pull Request for Issue # .

### Summary of Changes
As title says

### Testing Instructions
Make a module syndication feeds. 
Try different variants: 

- Display text yes, and enter a text
- Display text yes, but let the text empty
- Display text no

Inspect the code for the image and see which alt text is displayed.

### Actual result BEFORE applying this Pull Request
The image always has a hard coded alt-text. 

### Expected result AFTER applying this Pull Request
If the feed image is displayed with a text, then it has alt="", 
otherwise it has a translated text "feed entries"

### Documentation Changes Required
no

2020-10-21 07:41 UTC, hans2103 requested changes

2020-10-21 07:41 UTC, hans2103 commented on modules/mod_syndicate/tmpl/default.php
> + * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
I don't think this change is needed

2020-10-21 07:41 UTC, hans2103 commented on modules/mod_syndicate/tmpl/default.php
> +$alt = (!$params->get('display_text', 1) && empty($text)) ? JText::_('MOD_SYNDICATE_DEFAULT_FEED_ENTRIES') : '';
Please replace `JText` by `Text`and call for `use Joomla\CMS\Language\Text;`

2020-10-21 07:41 UTC, hans2103 commented on modules/mod_syndicate/tmpl/default.php
> +	<?php echo JHtml::_('image', 'system/livemarks.png', $alt, null, true); ?>
Please replace `JHtml` by `HTMLHelper` and call for use `Joomla\CMS\HTML\HTMLHelper;`

2020-10-21 07:55 UTC, chmst commented on modules/mod_syndicate/tmpl/default.php
> +$alt = (!$params->get('display_text', 1) && empty($text)) ? JText::_('MOD_SYNDICATE_DEFAULT_FEED_ENTRIES') : '';
thank you, fixed

2020-10-21 07:56 UTC, chmst commented on modules/mod_syndicate/tmpl/default.php
> +	<?php echo JHtml::_('image', 'system/livemarks.png', $alt, null, true); ?>
This is staging and must not be changed.

2020-10-21 07:57 UTC, hans2103 approved these changes
namespacing is J4. My bad. Sorry

2020-10-21 07:57 UTC, hans2103 commented
I have tested this item :white_check_mark: successfully on dfcd22fd28bd59c8a1106b2f672148bb49208a15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31180">issues.joomla.org/tracker/joomla-cms/31180</a>.</sub>

2020-10-21 10:55 UTC, adj9 commented
I have tested this item :white_check_mark: successfully on dfcd22fd28bd59c8a1106b2f672148bb49208a15<br /><br />done

HTML inspect:

with lable = n 

with confirmed lable but = ""<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31180">issues.joomla.org/tracker/joomla-cms/31180</a>.</sub>

2020-10-21 15:32 UTC, chmst commented
@adj9 you have made yor test on J4 :) 

It works on both versions, but the JText_:: (in 3.9) and TEXT::_  are different<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31180">issues.joomla.org/tracker/joomla-cms/31180</a>.</sub>

2020-10-21 15:54 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on dfcd22fd28bd59c8a1106b2f672148bb49208a15<br /><br />The test for empty text is not correct. 

To replicate the error first create a module with display text set to yes and a value in feed entries
Save and check it - all good

Now change the module to display text no - save and check
Now we do not get an alt text because there is a value for $text saved in the module<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31180">issues.joomla.org/tracker/joomla-cms/31180</a>.</sub>

2020-11-27 07:16 UTC, gostn commented
@chmst ?

2020-11-27 12:36 UTC, chmst commented
Thank you for remembering me. Fixed now. Could you please re-test?

2021-03-12 10:26 UTC, chmst commented
Fixed in J4, no need to change something in J3.

2021-03-12 10:26 UTC, closed without merging