Pre-Upgrade Compatibility Check on Plugins That Could Kill Joomla Upgrade
joomla/joomla-cms pull request #31200
Opened 2020-10-22 08:34 UTC by GeraintEdwards

Pull Request for Issue #31042  .

### Summary of Changes
New method in JoomlaupdateModelDefault -> getNonCorePlugins which fetches a list of plugins filtered by optional list of plugin folders.  The returning array excludes core Joomla plugins.
PreUpdate Check now fetches a list of 'system','user','authentication','actionlog' and 'twofactorauth' plugins that could, conceviably, break a Joomla upgrade if they contain code that isn't compatible with the targetted Joomla version
The PreUpdateChecker javascript now:

1. Disables the live update submit button until the update checker has finished or the user checks a checkbox to confirm they understand the risks of upgrading without performing appropriate checks/system changes
2. Checks the list of nonCorePlugins (mentioned above) to see if they are 'compatible' with the Joomla upgrade (or are part of a 'compatible' package).  Note that 'compatible' is based on results from the extension update server.
3. After the update check has run if there are no potential incompatible plugins the confirmation checkbox is removed
4. Additionally we now report results from failed requests to update servers (timeouts, 403, 500 errors etc.) separately

The messages displayed are changed as the update checker is run.

### Testing Instructions

In a J3.10 dev site install some extensions that are NOT compatible with Joomla 4 - at least one out of date version of an extension and one where there is no published J4 compatible version. Ideally you should have one with an invalid update server entry too.

Then open Joomla Updater component and observe the pre-update checker tab and the live update tab - as the update checker is running and after it has completed

### Actual result BEFORE applying this Pull Request

You would be able to upgrade Joomla with an incompatible plugin installed that could 'brick' (i.e. kill) your Joomla installation which would involve a lot of work to resolve.

### Expected result AFTER applying this Pull Request

The modified update checker will stop you from performing the upgrade unless you have no incompatble plugins OR you click a checkbox to say you know what you are doing.

### Documentation Changes Required

Once the  PR is finalised the update checker and update process pages will need to be updated.

2020-10-24 16:24 UTC, Quy commented on administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
> +				<div class="alert ">
```suggestion
				<div class="alert">
```

2020-10-24 16:50 UTC, zero-24 commented
hmm seems I'm missing something? I have installed the demo extensions as mention above + this plugin of my own: https://github.com/zero-24/plg_system_advancedredirect/releases/tag/1.0.3 (it does not yet have a 4.x compatible version via the update.xml)

That extensions are also correctly listed here:
![image](https://user-images.githubusercontent.com/2596554/97087239-e61b8c00-1628-11eb-9d78-8456b9435be8.png)

But the Live Updater still looks the same and does not mention the plugins?
![image](https://user-images.githubusercontent.com/2596554/97087350-aef9aa80-1629-11eb-82ba-4c6105c571b5.png)

2020-10-24 17:46 UTC, GeraintEdwards commented
You installed the packages from above and enabled their system plugins?

2020-10-24 17:53 UTC, zero-24 commented
Ah i have just installed that plugins without enableing them. Once enable they show up as expected 👍

2020-10-24 18:12 UTC, zero-24 requested changes, later dismissed

2020-10-24 18:12 UTC, zero-24 commented on administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
> +				foreach ($this->nonCoreCriticalPlugins as $nonCoreCriticalPlugin)
please use

```php
					<?php foreach ($this->nonCoreCriticalPlugins as $nonCoreCriticalPlugin) : ?>
						<tr id='plg_<?php echo $nonCoreCriticalPlugin->extension_id ?>'>
						<td>
							<?php echo JText::_($nonCoreCriticalPlugin->name); ?>
						</td>
						<?php if ($nonCoreCriticalPlugin->package_id > 0) : ?>
							<?php foreach ($this->nonCoreExtensions as $nonCoreExtension) : ?>
								<?php if ($nonCoreCriticalPlugin->package_id == $nonCoreExtension->extension_id) : ?>
									<td>
										<?php echo $nonCoreExtension->name; ?>
									</td>
								<?php endif; ?>
							<?php endforeach; ?>
						<?php else : ?>
							<td/>
						<?php endif; ?>
						</tr>
					<?php endforeach; ?>
```

2020-10-24 18:12 UTC, zero-24 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_PRE_UPDATE_CHECKS_FAILED_NOTES="It was not possible to check the compatibility of these plugins.  The request to the update server either timed out or returne
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_PRE_UPDATE_CHECKS_FAILED_NOTES="It was not possible to check the compatibility of these plugins. The request to the update server either timed out or returned an error"
```

2020-10-24 18:12 UTC, zero-24 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_DESC="The extension includes a plugin that could cause your upgrade to fail.<br><br>To perform the Joomla upgrade safely you should either u
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_DESC="This extension includes a plugin that could cause your upgrade to fail.<br><br>To perform the Joomla upgrade safely you should either upgrade this extension to a version compatible with your target version of Joomla or disable the relevant plugin(s) and check again.<br><br>For more information about the relevant plugins please check the 'Live Update' tab."
```

2020-10-24 18:12 UTC, zero-24 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_LIST="These plugins you could cause problems during the upgrade"
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_LIST="The following plugins you could cause problems during the upgrade"
```

2020-10-24 18:12 UTC, zero-24 commented on media/com_joomlaupdate/js/default.js
> +        // simulate failure or timeout
Please remove this debug code here

2020-10-24 18:12 UTC, zero-24 commented on administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
> +					<h4 class="alert-heading"><?php echo JText::_('WARNING'); ?></h4>
```suggestion
					<h4 class="alert-heading">
						<?php echo JText::_('WARNING'); ?>
					</h4>
```

2020-10-24 18:12 UTC, zero-24 commented on administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
> +						<div class="preupdateCheckIncomplete"><?php echo JText::_('COM_JOOMLAUPDATE_PREUPDATE_CHECK_NOT_COMPLETE'); ?></div>
```suggestion
						<div class="preupdateCheckIncomplete">
							<?php echo JText::_('COM_JOOMLAUPDATE_PREUPDATE_CHECK_NOT_COMPLETE'); ?>
						</div>
```

2020-10-24 18:12 UTC, zero-24 commented on administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
> +					<h4 class="alert-heading"><?php echo JText::_('WARNING'); ?></h4>
```suggestion
					<h4 class="alert-heading">
						<?php echo JText::_('WARNING'); ?>
					</h4>
```

2020-10-24 18:12 UTC, zero-24 commented on administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
> +						<div class="preupdateCheckComplete"><?php echo JText::_('COM_JOOMLAUPDATE_PREUPDATE_CHECK_COMPLETED_YOU_HAVE_DANGEROUS_PLUGINS'); ?></div>
```suggestion
						<div class="preupdateCheckComplete">
							<?php echo JText::_('COM_JOOMLAUPDATE_PREUPDATE_CHECK_COMPLETED_YOU_HAVE_DANGEROUS_PLUGINS'); ?>
						</div>
```

2020-10-24 18:12 UTC, zero-24 commented on administrator/components/com_joomlaupdate/models/default.php
> +
```suggestion
```

2020-10-24 18:12 UTC, zero-24 commented on administrator/components/com_joomlaupdate/models/default.php
> +	 * @since   3.10.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2020-10-24 18:14 UTC, zero-24 commented
@brianteeman can we please get your feedback on the new process + the texts proposed here? Thanks!

2020-10-24 18:23 UTC, zero-24 commented
@GeraintEdwards Thanks for that PR i think this is a good step forward.

What do you think about the idea to allow the plugins to be disable on the `Live Update` tab similiar to the RFC that Brian did?

The basic idea would be to change the table you did here:
![image](https://user-images.githubusercontent.com/2596554/97089110-e706ea80-1635-11eb-8660-e245a7e66eb1.png)

To something like this (sorry very bad paint skills on my side)
![Screenshot 2020-10-24 201736](https://user-images.githubusercontent.com/2596554/97089172-6399c900-1636-11eb-8931-ffc924102535.png)

And all plugins checked there get logged & disabled as first step here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/controllers/update.php#L107

2020-10-25 05:43 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_PRE_UPDATE_CHECKS_FAILED_NOTES="It was not possible to check the compatibility of these plugins.  The request to the update server either timed out or returne
rather: It was impossible etc.

2020-10-25 05:44 UTC, infograf768 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_LIST="These plugins you could cause problems during the upgrade"
`you` ?

2020-10-25 06:30 UTC, zero-24 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_PRE_UPDATE_CHECKS_FAILED_NOTES="It was not possible to check the compatibility of these plugins.  The request to the update server either timed out or returne
Updated thanks

2020-10-25 06:41 UTC, zero-24 commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_LIST="These plugins you could cause problems during the upgrade"
Fixed thanks JM

2020-10-25 14:18 UTC, GeraintEdwards commented
The idea of disabling selected plugins is good but there are potential downsides:
- We would need to distinguish between plugins to disable temporarily (with the session, if the session data is safe??) to be re-enabled on completion and those that should be disabled permanently.
- The user may not realise that disabling a plugin could have unforseen consequences - the site may be inaccessible after the upgrade completes.
- Is it possible that disabling the plugins at the start of the upgrade process could cause the site to die?? Not sure as I've not checked which plugin triggers are fired after this point?  onAfterRender etc??

Language comments-

- Some good catches.  Thanks
- 'impossible' vs 'not possible'.  To me 'impossible' has an air of permanence where, in reality, simply trying again could resolve the issue (e.g. problem was caused a timeout).  Happy to go with the majority view though.

2020-10-25 15:12 UTC, zero-24 commented
> The idea of disabling selected plugins is good but there are potential downsides:
> - We would need to distinguish between plugins to disable temporarily (with the session, if the session data is safe??) to be re-enabled on completion and those that should be disabled permanently.

Anything checked here should be disabled permanently. As we can not be sure that the session is passed over.

> - The user may not realise that disabling a plugin could have unforseen consequences - the site may be inaccessible after the upgrade completes.

Well he accepted that but now the upgraded site is not bricked so he can come back and fix the issues. And I'm sure that when someone has a that critical plugin installed they check that upfront. I'm not sure whether we can do much more at this point.

> - Is it possible that disabling the plugins at the start of the upgrade process could cause the site to die?? Not sure as I've not checked which plugin triggers are fired after this point?  onAfterRender etc??

At that point where i suggested to disable the plugins that system events where executed already but all within the 3.x code so all should be fine. The problem is when they are expecuted in the middel of the upgrade process but at that time they are no longer active when checked.

> Language comments-
> 
> - Some good catches.  Thanks
> - 'impossible' vs 'not possible'.  To me 'impossible' has an air of permanence where, in reality, simply trying again could resolve the issue (e.g. problem was caused a timeout).  Happy to go with the majority view though.

Same for me. I have mention brian above so we can get his view on that strings form a native speaker perspective.

2020-10-27 09:37 UTC, GeraintEdwards commented on administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
> +				foreach ($this->nonCoreCriticalPlugins as $nonCoreCriticalPlugin)
Personally I can't stand 

if : 
else :
endif;

to me it makes code far less easy to scan read.

2020-10-27 09:43 UTC, zero-24 commented on administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
> +				foreach ($this->nonCoreCriticalPlugins as $nonCoreCriticalPlugin)
It is just used in layout files to make it easier to understand and change for people who want to override that view.

2020-10-30 21:43 UTC, brianteeman commented
Geraint is correct.

2020-10-31 12:15 UTC, brianteeman commented
We need to switch the extension checks and the system checks around or move extensions to its own tab because as it is right now anyone using a screen with <900px approx may not even know there is the extension section

![image](https://user-images.githubusercontent.com/1296369/97778940-ad246f80-1b72-11eb-8300-4170ac9945fa.png)

2020-10-31 12:26 UTC, brianteeman commented
It was only because I was looking for some strings that I see in the code that I realised that there was a popover

![image](https://user-images.githubusercontent.com/1296369/97779030-684d0880-1b73-11eb-8d5a-93e3195b3642.png)




### Suggestion
Can we add a button please or something to make it absolutely blatantly in your face obvious. Perhaps
![image](https://user-images.githubusercontent.com/1296369/97779154-3ab48f00-1b74-11eb-8994-d7ca855d85e9.png)

2020-10-31 12:31 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_PREUPDATE_CHECK_NOT_COMPLETE="Pre-Update checks have not been completed yet - please wait"
```suggestion
COM_JOOMLAUPDATE_PREUPDATE_CHECK_NOT_COMPLETE="Pre-Update checks have not been completed yet - please wait."
```

2020-10-31 12:32 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_PRE_UPDATE_CHECKS_FAILED_NOTES="It was not possible to check the compatibility of these plugins.  The request to the update server either timed out or returne
impossible is not correct. it is not the same as saying something was not possible.

2020-10-31 12:33 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_PRE_UPDATE_CHECKS_FAILED_NOTES="It was not possible to check the compatibility of these plugins.  The request to the update server either timed out or returne
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_PRE_UPDATE_CHECKS_FAILED_NOTES="It was not possible to check the compatibility of these plugins. The request to the update server either timed out or returned an error."
```

remove double space and add full stop

2020-10-31 12:36 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_NON_CORE_PLUGIN_BEING_CHECKED="The system is currently checking these plugins to see if they could cause problems during the upgrade.<br>Please be patient while the chec
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_NON_CORE_PLUGIN_BEING_CHECKED="Checking these plugins to see if they could cause problems during the upgrade.<br>Please be patient while the checks are completed."
```
Not really sure when this is displayed as I couldnt see it BUT need to be change the language or it might be interpreted as saying that joomla is checking the code in the plugins

2020-10-31 12:37 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_NON_CORE_PLUGIN_CONFIRMATION="Do you wish to ignore the warnings about potentially incompatible plugins and to proceed with the upgrade"
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_NON_CORE_PLUGIN_CONFIRMATION="Do you wish to ignore the warnings about potentially incompatible plugins and to proceed with the upgrade?"
```

2020-10-31 12:38 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_CONFIRM_MESSAGE="Are you sure you wish to proceed with the upgrade and ignore the warnings about potentially incompatible plugins?"
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_CONFIRM_MESSAGE="Are you sure you want to ignore the warnings about potentially incompatible plugins and proceed with the upgrade?"
```

puts the important part of the message first

2020-10-31 12:39 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_DESC="This extension includes a plugin that could cause your upgrade to fail.<br><br>To perform the Joomla upgrade safely you should either
```suggestion
COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_DESC="This extension includes a plugin that could cause the upgrade to fail.<br><br>To perform the Joomla upgrade safely you should either upgrade this extension to a version compatible with your target version of Joomla or disable the relevant plugin(s) and check again.<br><br>For more information about the relevant plugins please check the 'Live Update' tab."
```

2020-10-31 12:40 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_DESC="This extension includes a plugin that could cause your upgrade to fail.<br><br>To perform the Joomla upgrade safely you should either
>> For more information about the relevant plugins please check the 'Live Update' tab.

Can we not display this on the same page?

2020-10-31 12:41 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_PREUPDATE_CHECK_COMPLETED_YOU_HAVE_DANGEROUS_PLUGINS="You have plugins installed and enabled that could interfere with the Joomla upgrade and could result in an upgrade failure that
```suggestion
COM_JOOMLAUPDATE_PREUPDATE_CHECK_COMPLETED_YOU_HAVE_DANGEROUS_PLUGINS="There are plugins installed and enabled that could interfere with the Joomla upgrade and result in a failed upgrade that leaves the site inaccessible.<br><br>You are strongly advised to upgrade, disable or uninstall these plugins before upgrading."
```

2020-10-31 12:43 UTC, brianteeman commented
general comment on strings. some people might prefer to use "may" instead of "could" - i have no preference

if possible we should talk about the website and not your site

2020-11-02 11:42 UTC, GeraintEdwards commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_NON_CORE_PLUGIN_BEING_CHECKED="The system is currently checking these plugins to see if they could cause problems during the upgrade.<br>Please be patient while the chec
If you switch to the 'live update' tab as soon as you load the update page then its shown next to the list of plugins.  

It only really shows up if the update checks are being slow and is mean to encourage patience!  'The system is currently checking' was meant to convey that the website is doing something right now and the user needs to wait.

2020-11-02 11:44 UTC, GeraintEdwards commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_PRE_UPDATE_CHECKS_FAILED_NOTES="It was not possible to check the compatibility of these plugins.  The request to the update server either timed out or returne
I'm an old fashioned typist and old habits like 2 spaces after a full stop are difficult to kick

2020-11-02 11:49 UTC, GeraintEdwards commented
> We need to switch the extension checks and the system checks around or move extensions to its own tab because as it is right now anyone using a screen with <900px approx may not even know there is the extension section
re switching the ordering of the sections what about using 'More Detail' 

e.g. 
"Required PHP & Database Settings"  Passed [More Detail]
"Recommended PHP Settings" Warning [More Detail]
the warning could highlight that output buffering is enabled

2020-11-02 11:50 UTC, GeraintEdwards commented on administrator/language/en-GB/en-GB.com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_DESC="This extension includes a plugin that could cause your upgrade to fail.<br><br>To perform the Joomla upgrade safely you should either
I placed the information directly above the "submit" button to make it really obvious to the user.  The downside, as you point out, is the information in 2 different places.

2020-11-02 11:51 UTC, brianteeman commented
That could work as well

2020-11-02 11:53 UTC, GeraintEdwards commented
> It was only because I was looking for some strings that I see in the code that I realised that there was a popover
> 
> ![image](https://user-images.githubusercontent.com/1296369/97779030-684d0880-1b73-11eb-8d5a-93e3195b3642.png)
> ### Suggestion
> 
> Can we add a button please or something to make it absolutely blatantly in your face obvious. Perhaps
> ![image](https://user-images.githubusercontent.com/1296369/97779154-3ab48f00-1b74-11eb-8994-d7ca855d85e9.png)
Good idea
On a separate note I think Joomla needs a 'house style' for 'information available' or 'action required' icons/buttons etc.  As you say avilability of  popovers/tooltips is not always obvious!

2020-11-04 12:01 UTC, GeraintEdwards commented
@brianteeman I've updated the code now.

1. I'm not happy with the 'more information' icon/button - I think it would be cleaner to indication within the yellow warning that some more information is available  Not sure the best way for this to be clear and to look good
2. The chevron in the php settings is not rendered properly straightaway - This could be fixed by causing the preupdate checker to wait for DOMContentReady before starting.  This is probably a good idea and will only delay things by a fraction of a second.

@zero-24 and @brianteeman 

Any thoughts on the layout of the list of plugins and their packages on the 'live update' tab - we could try to present information about the author of the extension to display here and a link to the site (if available).  Anything else?

2020-11-04 22:32 UTC, zero-24 commented
> Any thoughts on the layout of the list of plugins and their packages on the 'live update' tab - we could try to present information about the author of the extension to display here and a link to the site (if available). Anything else?

Yes I would propose to link the authorUrl / packagerUrl (for packages) with the author / packager (for packages). When there is no link than just the name, when there is no name but a link maybe fallback to "Developers website" with the URL when nothing is aviabe show that we have no information about the developer.

2020-11-05 10:04 UTC, GeraintEdwards commented
> > Any thoughts on the layout of the list of plugins and their packages on the 'live update' tab - we could try to present information about the author of the extension to display here and a link to the site (if available). Anything else?
> 
> Yes I would propose to link the authorUrl / packagerUrl (for packages) with the author / packager (for packages). When there is no link than just the name, when there is no name but a link maybe fallback to "Developers website" with the URL when nothing is aviabe show that we have no information about the developer.

I've done this now.  It outputs the author and the authorUrl from the plugin manifest and if not available the equivalent values from  the package manifest.

2020-11-14 11:03 UTC, adj9 commented
Start with J!3.10
- Install all plugin 
- Enable plg

### Before apply PR
![Schermata 2020-11-14 alle 11 47 42](https://user-images.githubusercontent.com/5918444/99145686-16c37400-2671-11eb-9422-9a805fc2cbc7.png)
### After apply PR
![Schermata 2020-11-14 alle 11 58 34](https://user-images.githubusercontent.com/5918444/99145699-365a9c80-2671-11eb-94a3-bfcc42a35cda.png)
![Schermata 2020-11-14 alle 11 58 50](https://user-images.githubusercontent.com/5918444/99145702-3c507d80-2671-11eb-9ae8-aea5a4f55219.png)
The plg are confermed but there are 2 allert red & 1 orange.

2020-11-14 12:27 UTC, particthistle commented
@GeraintEdwards taking a look at this today following your mention in BF@H channel.

_When this is finally merged, please advise (if I don't spot it first) as I've added this to the Joomla 4 JCM series, and will also help with documenting the process on JDOCS._

I'm testing 3.10 on the skeleton build I use for implementing new sites (and my, there's a lot of extensions needing update compatibility information added) so it's got a considerable list of 405 extensions in the Manage list.

So performance issues aside, here's some feedback on what I've seen going through the comment history above.

- The "Update Required" section I think should come first in the list - Extensions identified as Update Required really should be updated first, as it's possible the update contains the Update Information, and they should be ideally updated regardless of what the Update Information availability is returned as).

- [More Detail >] was previously positioned to the right which I think looks better. Otherwise, it should go under the section title if not back on the right.

- With 405 extensions checked (less core) the groupings are quite lengthy. Would it be better to put each section in an accordion slider, so that then the results are presented in groups with the description for that section visible, and then an expand button to then open up the list?

- Is hiding the information that is displayed when you click on [More Detail >] worth hiding (is there history behind it?)

- Should the columns read left to right: Extension Name, Installed Version, Extension Type, Update Compatible Version, Currently Compatible Version, Update Compatible Version

- "Update Compatible Version" and "Currently Compatible Version" - compatible to what? Do we need to perhaps make these language strings more specific if this is what they actually refer to?
Currently Compatible Version = Version compatible with Joomla 3.x
Update Compatible Version = Version compatible with Joomla 4.x

On applying the current version of the patch, but before trying to install a test extension:
- the [More Detail >] links are no longer clickable.
- the Extensions Pre-Update Check did not automatically start when the patch was applied

I've then installed the test extensions, but as the pre-update check did not trigger, and could not be manually triggered, I couldn't see the results for the 6 test packages yet.

2020-11-14 15:35 UTC, GeraintEdwards commented
> Start with J!3.10 alpha4-dev
> ...
> The plg are confermed but there are 2 allert red & 1 orange.

Somehow the auto-running of the PreUpdateChecker was broken in my last commit :(  This is now working

2020-11-14 15:43 UTC, GeraintEdwards commented
Thanks @particthistle 
 
>     * The "Update Required" section I think should come first in the list - Extensions identified as Update Required really should be updated first, as it's possible the update contains the Update Information, and they should be ideally updated regardless of what the Update Information availability is returned as).
 
>     * [More Detail >] was previously positioned to the right which I think looks better. Otherwise, it should go under the section title if not back on the right.
I had broken the auto-running of the checker - I have corrected this now and the [More Detail >] is back where is should be!
 
>     * With 405 extensions checked (less core) the groupings are quite lengthy. Would it be better to put each section in an accordion slider, so that then the results are presented in groups with the description for that section visible, and then an expand button to then open up the list?

I'm open to this idea or a toggle to minimise each block but I think they should be fully visible initially·   What do you think?

>     * Is hiding the information that is displayed when you click on [More Detail >] worth hiding (is there history behind it?)

My initial thought was to have it all visible but it was suggested this could make it overwhelming to some users.

Is there a way to do a vote on this type of question in GitHub??

>     * Should the columns read left to right: Extension Name, Installed Version, Extension Type, Update Compatible Version, Currently Compatible Version, Update Compatible Version

Or 
"Extension Name, Extension Type, Installed Version, Update Compatible Version, Currently Compatible Version" ?

Again how do we ascertain consensus?

>     * "Update Compatible Version" and "Currently Compatible Version" - compatible to what? Do we need to perhaps make these language strings more specific if this is what they actually refer to?
>       Currently Compatible Version = Version compatible with Joomla 3.x
>       Update Compatible Version = Version compatible with Joomla 4.x

A good idea - but we need concise headings too.  So 'Joomla 3.x Compatible Version' etc.

The number values should not be hard coded as 4.x etc. since the check will work with whatever the target Joomla version is e.g. "4.0.0 beta 5" of "4.1.0 RC2" etc.

The descriptors then get a bit long

2020-12-19 09:59 UTC, richard67 commented
@zero-24 How do we continue with this PR? It shows that you have requested changes during a review. I've gone through the history to see if that meanwhile has been resolved, but I could not really find the details. Could you check and if ok just give again a review with approval so the change request will disappear at the bottom of the PR?

2020-12-19 10:06 UTC, zero-24 commented
I would say you can remove my review given that they are indeed solved. The next steps here would be testing i would say.

2020-12-19 11:06 UTC, richard67 commented
@adj9 @particthistle Could you test this PR again after it has received changes? Thanks in advance.

2020-12-23 09:24 UTC, GeraintEdwards commented
In addition to testing @particthistle bumping questions from https://github.com/joomla/joomla-cms/pull/31200#issuecomment-727225267 please

2021-01-19 00:59 UTC, zero-24 commented
I'm sorry that it took that long to get back into this. I have just tested the process and I think this is a good step in the right direction.

@GeraintEdwards 
While i was testing i have "just" installed the extensions you have provided here in the inital issue but i have not enabled any additional extension. While at this point no "brick my site" plugin was active it seems the headers for the table was still rendered.  I would say lets just remove the table in that case.

![image](https://user-images.githubusercontent.com/2596554/104975075-ef36b200-59f9-11eb-8440-5489dd17c745.png)

The other case I have tested is an 3.10 without any extension installed:
![image](https://user-images.githubusercontent.com/2596554/104974847-6a4b9880-59f9-11eb-8301-083166040365.png)

The `Live Update` screen claims to still checking while the pre Upgrade checker already issued that no extension is installed. So in this case i would propose to remove the warning as well as the table header etc too.

A tip for all testers go to the disabled extensions and enabled them to get plugins that are not compatible.

2021-01-31 11:59 UTC, GeraintEdwards commented
@zero-24 I have updated the JS to hide the table headings when there are no problem plugins and to do so as soon as the list has been cleared (as opposed to waiting for the full checks to complete)

@particthistle I have re-ordered the output columns and updated the labels to show the current Joomla version and target version which should make them easier to interpret.

I think this PR is ready for final testing now.

2021-02-01 21:07 UTC, zero-24 commented
@GeraintEdwards the first issue mentind is fixed now Thanks! But the seccond one is still there.

When you have zero extensions installed the `live update` claims to `Pre-Update checks have not been completed yet - please wait.` But when checking the `Pre-Update check` it correctly states `No extensions installed.`.

![image](https://user-images.githubusercontent.com/2596554/106518187-d0481d80-64d9-11eb-8bd9-fb4d4d054877.png)

![image](https://user-images.githubusercontent.com/2596554/106518229-dc33df80-64d9-11eb-8fef-8c432bbbbad6.png)

2021-02-02 11:37 UTC, GeraintEdwards commented
Good catch on the no-extensions and no non-core critical plugins installed scenarios.  I have amended the javascript to reflect these situations now.

2021-03-15 17:33 UTC, alikon commented
I have tested this item :white_check_mark: successfully on b3e691aebdb5d6b4f288aadef6aece6b0cbc356a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31200">issues.joomla.org/tracker/joomla-cms/31200</a>.</sub>

2021-03-16 01:41 UTC, particthistle commented
I have tested this item :red_circle: unsuccessfully on b3e691aebdb5d6b4f288aadef6aece6b0cbc356a<br /><br />Sorry @GeraintEdwards - will chat more at JUGL on this. Apologies for delay looking at it after changes back in December. I've now adjusted my Github notifications so they appear somewhere I see them when I'm not on Github.

Testing unsuccessfully based on the UX more than the functionality (also reviewing [my comment from last year](#event-569289)).

The "check" process appears to work fine, albeit that the bulk of extensions returning Update Information Unavailable (@Llewellynvdm - a discussion JED need to have with developers to onboard them to this process)

I've recorded a screencast to show where the bugs lie: https://www.screencast.com/t/VygEBpCvR721
- Accordions for information blocks are not toggling (tested in both Firefox and Chrome on Windows)
- Language strings in the process do not indicate anywhere that the Pre-Update Check is actually checking everything in preparation of installing Joomla 4.
- Link to JDOCs page on "pre-update check documentation" should open in a new tab/window.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31200">issues.joomla.org/tracker/joomla-cms/31200</a>.</sub>

2021-03-16 02:01 UTC, particthistle commented
The issue with the toggles looks to be string that's not defined (my JQuery skills are not good enough to suggest a fix).

![image](https://user-images.githubusercontent.com/5515866/111244721-93825100-8657-11eb-8614-f4af3c064fcf.png)

2021-03-16 08:24 UTC, zero-24 commented
> Language strings in the process do not indicate anywhere that the Pre-Update Check is actually checking everything in preparation of installing Joomla 4.

That has been patched outside of this PR: https://github.com/joomla/joomla-cms/pull/32098

Given that the pre Upgrade checker does not always check against Joomla 4 but the next target version provided by the updater.

2021-03-16 08:27 UTC, richard67 commented
> > Language strings in the process do not indicate anywhere that the Pre-Update Check is actually checking everything in preparation of installing Joomla 4.
> 
> That has been patched outside of this PR: #32098

Then it would maybe be good to update this PR to latest 3.10-dev so it contains this change, i.e. merge the 3.10-dev branch from upstream into the branch for this PR here.

@GeraintEdwards Let us know when you need help with that.

2021-03-16 14:42 UTC, GeraintEdwards commented
@particthistle 
> The issue with the toggles looks to be string that's not defined (my JQuery skills are not good enough to suggest a fix).> 
> ![image](https://user-images.githubusercontent.com/5515866/111244721-93825100-8657-11eb-8614-f4af3c064fcf.png)
This is a strange error as these variables are declared in default_preupdatecheck.php and I don't see this error arising.  Viewing the web page source I can see them defined.

The only 2 possible explanations I can think of for you seeing these problems is that:
1. You have some sort or plugin that defers the execution of 'inline' javascript code so that the update check starts before these variables are parsed ??
2. The sheer number of extensions you have is causing an issue in some way

2021-03-16 14:46 UTC, GeraintEdwards commented
@richard67 
> > > Language strings in the process do not indicate anywhere that the Pre-Update Check is actually checking everything in preparation of installing Joomla 4.
> > 
> > 
> > That has been patched outside of this PR: #32098

This has been merged so I see the changes here too.

2021-03-23 19:02 UTC, chmst commented
I have tested this item :white_check_mark: successfully on b3e691aebdb5d6b4f288aadef6aece6b0cbc356a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31200">issues.joomla.org/tracker/joomla-cms/31200</a>.</sub>

2021-03-23 19:23 UTC, alikon commented
from my understanding this can go RTC
up to RL now :smile:

2021-03-23 19:24 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31200">issues.joomla.org/tracker/joomla-cms/31200</a>.</sub>

2021-03-26 20:41 UTC, zero-24 commented
I'm now finally going to merge this here into 3.10. I would like to issue a massive thanks to @GeraintEdwards who did a great job with this PR and all the testers who tested and gave feedback.

Just to make things clear. The Pre Upgrade Checker itself is one of the main features of 3.10 and this here is an great extension to the existing tool. I'm happy to hear, read, review and accept additional improvments on this tool. So I would like to encurage everyone who has additional feedback on this tool please step up and lets discuss now what can be improved and how. Feel free to report issues or provide PRs here. But please feel also free to contact me via mail (tobias.zulauf[at]community.joomla.org) or Glip. Thanks!

2021-03-26 20:41 UTC, merged

2021-03-27 10:51 UTC, richard67 commented
@GeraintEdwards @zero-24 Is it by purpose that the minified js is deleted by this PR now in the 3.10-dev branch?

![2021-03-27_01](https://user-images.githubusercontent.com/7413183/112718374-cb5c8480-8ef2-11eb-86d8-b4b30a8c2341.png)

2021-03-27 12:00 UTC, richard67 commented
See PR #32883 .

2021-03-27 16:12 UTC, zero-24 commented
Will take a closer look over the weekend

2021-03-28 15:07 UTC, richard67 commented
@zero-24 Not sure what closer look it needs. If you check the folder where the missing minified script which will be added with my PR #32883 is located, you will see that for the other js files minified versions are there, only not for that one handled with my PR and mentioned in my above comment.

2021-03-28 17:22 UTC, zero-24 commented
Yes but when its about JS i always have to take a soccond look when at my desk, because its JS ;-)

2021-03-29 08:35 UTC, GeraintEdwards commented
I can confirm this minified file was accidentally removed #6c00eec7a69df98a730ea71f17d891fb33f5533e on 31/01/2021

The issue with developing/debugging JS in Joomla is that you can't debug unless you enable Joomla debug mode and then Joomla forces a new version of the file on the browser each time you refresh the page (through the 'getMediaVersion query string) so all your JS breakpoints are lost.  An easy workaround for this is to temporarily rename the min.js file .  I must have accidentally let it slip through the commit :(

2021-03-30 22:24 UTC, zero-24 commented
The docs page has been updated: https://docs.joomla.org/Pre-Update_Check