Adds \ to all defines
joomla/joomla-cms pull request #31293
Opened 2020-11-01 21:12 UTC by N6REJ

Pull Request for Issue # .

### Summary of Changes
using \define speeds things up.
several places were missing the \  This corrects that.

### Testing Instructions
make sure J! still runs.
code review?

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Documentation Changes Required

2020-11-01 21:23 UTC, SharkyKZ commented
This only makes a difference in namespaced files.

2020-11-01 22:09 UTC, brianteeman commented
Any PR that touches over a 1000 files is impossible to test

2020-11-02 15:44 UTC, Quy commented on administrator/components/com_categories/tmpl/categories/default_batch_body.php
> +\defined('_JEXEC') or die;
Revert

2020-11-02 15:44 UTC, Quy commented on administrator/components/com_categories/tmpl/categories/default_batch_footer.php
> +\defined('_JEXEC') or die;
Revert

2020-11-02 15:45 UTC, Quy commented on administrator/components/com_config/tmpl/application/default_cache.php
> +\defined('_JEXEC') or die;
Revert

2020-11-02 15:45 UTC, Quy commented on administrator/components/com_categories/tmpl/categories/default_batch_body.php
> +\defined('_JEXEC') or die;
There are more files to revert.

2020-11-02 16:43 UTC, brianteeman commented on administrator/components/com_categories/tmpl/categories/default_batch_body.php
> +\defined('_JEXEC') or die;
and thats why global search and replace can be so dangerous

2020-11-02 19:36 UTC, N6REJ commented on administrator/components/com_categories/tmpl/categories/default_batch_body.php
> +\defined('_JEXEC') or die;
done https://github.com/joomla/joomla-cms/pull/31293/commits/1b336fceebd5acb68e588842372915a6aa0998a3

2020-11-02 20:00 UTC, richard67 commented
@N6REJ It seems when you have reverted some of the changes for the non-namespaced files, you have also removed indentation, see e.g. here:

https://github.com/joomla/joomla-cms/pull/31293/files#diff-a225d694617c9bd244487ecd686306d39cde6f74cc6bd5f2203fb64735db62f6R37

Drone reports a bunch of them here: https://ci.joomla.org/joomla/joomla-cms/37307/1/6

2020-11-02 21:06 UTC, N6REJ commented
looks like we got everything.

2020-11-02 21:08 UTC, Quy commented on api/includes/app.php
> +if (!\defined('_JDEFINES'))
Revert

2020-11-02 21:08 UTC, Quy commented on api/includes/defines.php
> +\define('JPATH_ROOT',          implode(DIRECTORY_SEPARATOR, $parts));
Revert

2020-11-02 21:08 UTC, Quy commented on api/includes/framework.php
> +\define('JDEBUG', $config->debug);
Revert

2020-11-03 02:12 UTC, N6REJ commented on api/includes/app.php
> +if (!\defined('_JDEFINES'))
done

2020-11-03 02:13 UTC, N6REJ commented on api/includes/defines.php
> +\define('JPATH_ROOT',          implode(DIRECTORY_SEPARATOR, $parts));
done

2020-11-03 02:14 UTC, N6REJ commented on api/includes/framework.php
> +\define('JDEBUG', $config->debug);
done

2020-11-03 17:00 UTC, Quy commented on api/includes/app.php
> +	\define('JPATH_BASE', dirname(__DIR__));
Revert

2020-11-03 20:33 UTC, N6REJ commented on api/includes/app.php
> +	\define('JPATH_BASE', dirname(__DIR__));
done

2020-11-03 22:49 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 60f8acf52d4802f0fbee8960dff1ee5b7961ec7c<br /><br />Tested new Joomla installation. Navigated to all possible portions of the website. Added and removed content as well as tested caching and no issues found from a functionality standpoint.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31293">issues.joomla.org/tracker/joomla-cms/31293</a>.</sub>

2020-11-05 17:10 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 60f8acf52d4802f0fbee8960dff1ee5b7961ec7c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31293">issues.joomla.org/tracker/joomla-cms/31293</a>.</sub>

2020-11-05 17:10 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31293">issues.joomla.org/tracker/joomla-cms/31293</a>.</sub>

2020-11-06 14:05 UTC, HLeithner requested changes

2020-11-06 14:05 UTC, HLeithner commented on administrator/components/com_installer/tmpl/installer/default_message.php
> +	</div>
Unrelated change...

2020-11-06 14:05 UTC, HLeithner commented on administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
> +		$data = "<?php\n\defined('_AKEEBA_RESTORATION') or die('Restricted access');\n";
please revert this, it would expect that this code will not be executed in a namespaced context.

2020-11-06 14:05 UTC, HLeithner commented on administrator/components/com_newsfeeds/tmpl/newsfeeds/default_batch_body.php
> +</div>
unrelated

2020-11-06 14:05 UTC, HLeithner commented on administrator/components/com_redirect/tmpl/links/default_addform.php
> +			</div>
unrelated

2020-11-06 14:05 UTC, HLeithner commented on administrator/components/com_tags/tmpl/tags/default_batch_body.php
> +</div>
unrelated

2020-11-06 14:05 UTC, HLeithner commented on layouts/joomla/edit/title_alias.php
> +</div>
unrelated

2020-11-06 14:05 UTC, HLeithner commented on layouts/joomla/tinymce/textarea.php
> +</textarea>
unrelated

2020-11-06 14:05 UTC, HLeithner commented on layouts/libraries/cms/html/bootstrap/endtab.php
> +</div>
unrelated

2020-11-06 14:05 UTC, HLeithner commented on layouts/libraries/cms/html/bootstrap/endtabset.php
> +</div>
unrelated

2020-11-06 14:05 UTC, HLeithner commented on layouts/libraries/cms/html/bootstrap/starttabset.php
> +<div class="tab-content" id="<?php echo $selector; ?>Content">
unrelated

2020-11-06 14:05 UTC, HLeithner commented on libraries/src/HTML/Helpers/FormBehavior.php
> -		$options_str = json_encode($options, ($debug && defined('JSON_PRETTY_PRINT') ? JSON_PRETTY_PRINT : false));
if you already change the line you could add the \ to json_encode too

2020-11-06 19:18 UTC, N6REJ commented on layouts/libraries/cms/html/bootstrap/starttabset.php
> +<div class="tab-content" id="<?php echo $selector; ?>Content">
need me to roll these back?  I"m not sure where they came from.

2020-11-07 12:41 UTC, HLeithner commented on layouts/libraries/cms/html/bootstrap/starttabset.php
> +<div class="tab-content" id="<?php echo $selector; ?>Content">
Your IDE added a linebreak to the end, you should be able to rollback this backin your ide.

2020-11-08 17:04 UTC, N6REJ commented on layouts/libraries/cms/html/bootstrap/starttabset.php
> +<div class="tab-content" id="<?php echo $selector; ?>Content">
@HLeithner according to our standards a blank line is required at the end of a php file.
https://developer.joomla.org/coding-standards/php-code.html
thats why it was added.

2020-11-08 17:13 UTC, N6REJ commented on libraries/src/HTML/Helpers/FormBehavior.php
> -		$options_str = json_encode($options, ($debug && defined('JSON_PRETTY_PRINT') ? JSON_PRETTY_PRINT : false));
done

2020-11-08 17:14 UTC, N6REJ commented on layouts/libraries/cms/html/bootstrap/endtabset.php
> +</div>
blank line added

2020-11-08 17:15 UTC, N6REJ commented on layouts/libraries/cms/html/bootstrap/endtab.php
> +</div>
blank line added

2020-11-08 17:15 UTC, N6REJ commented on layouts/joomla/tinymce/textarea.php
> +</textarea>
blank line added

2020-11-08 17:16 UTC, N6REJ commented on administrator/components/com_tags/tmpl/tags/default_batch_body.php
> +</div>
blank line added

2020-11-08 17:18 UTC, N6REJ commented on administrator/components/com_redirect/tmpl/links/default_addform.php
> +			</div>
spaces removed

2020-11-08 17:22 UTC, N6REJ commented on administrator/components/com_installer/tmpl/installer/default_message.php
> +	</div>
phpcs fixes
![image](https://user-images.githubusercontent.com/1850089/98471841-9dc9a580-21b4-11eb-8c17-591998008477.png)

2020-11-08 17:23 UTC, N6REJ commented on administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
> +		$data = "<?php\n\defined('_AKEEBA_RESTORATION') or die('Restricted access');\n";
done

2020-11-08 17:23 UTC, N6REJ commented on administrator/components/com_newsfeeds/tmpl/newsfeeds/default_batch_body.php
> +</div>
phpcs fix

2020-11-08 17:25 UTC, N6REJ commented on layouts/joomla/edit/title_alias.php
> +</div>
phpcs fix

2020-11-08 17:34 UTC, merged

2020-11-08 17:35 UTC, HLeithner commented
Thanks