[4.0] [Backend] In Banners: Clients details page Contact column is di…
joomla/joomla-cms pull request #31354
Opened 2020-11-07 13:20 UTC by MeghaBiranje

…splaying blank value

Pull Request for Issue # .

### Summary of Changes

### Testing Instructions

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Documentation Changes Required

2020-11-07 14:28 UTC, adj9 commented
I have tested this item :white_check_mark: successfully on f94cf99620d9ab11a38c662ed55e9a1e85898e9b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31354">issues.joomla.org/tracker/joomla-cms/31354</a>.</sub>

2020-11-07 15:07 UTC, SharkyKZ commented
This removes HTML filtering.

2020-11-08 07:18 UTC, ceford commented
I do not see the problem described. And the test by @adj9 does not show the Clients screen. This is my screen grab without the patch applied:

![screen shot 2020-11-08 at 07 15 49](https://issues.joomla.org/uploads/1/a4003a569a3d3f463f2fffbf350e3b4b.png)

I have not looked at the trim filter but I would expect that to remove leading and trailing white space only.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31354">issues.joomla.org/tracker/joomla-cms/31354</a>.</sub>

2020-11-08 07:54 UTC, brianteeman commented
@ceford to replicate the issue you need to **only** put spaces in the field

2020-11-08 08:57 UTC, ceford commented
> @ceford to replicate the issue you need to **only** put spaces in the field

I started with just a space in "John Doe" and that name appears in the Contact column without the patch. The screen grab by @adj9 looks like the Banners list but even there I see the client name. It is not empty. So for me the issue described does not exist.

2020-11-08 09:12 UTC, brianteeman commented
ONLY put spaces and see what happens
Then try to create an article with a title containing ONLY spaces

2020-11-08 09:50 UTC, richard67 commented
@MeghaBiranje Is this pull request made for solving your issue #31355 ? If yes: Why haven't you referenced that issue by using the "Pull Request for Issue # ." at the top of the description? It just need to change it to "Pull Request for Issue #31355 ." Or at least leave in the issue a comment referring to this PR, or whatever else way to show the PR belongs to that issue. You can't expect maintainers to do a forensic research to find out which of YOUR pull requests solves which of YOUR issues.

2020-11-08 10:06 UTC, ceford commented
I have tested this item :white_check_mark: successfully on f94cf99620d9ab11a38c662ed55e9a1e85898e9b<br /><br />Thanks @brianteeman I see it now. Seems to me this was an ambiguous pr with no Before and After descriptions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31354">issues.joomla.org/tracker/joomla-cms/31354</a>.</sub>

2020-11-08 10:08 UTC, richard67 commented
What about @SharkyKZ 's comment above that this PR removed HTML filtering because using the TRIM filter now?

2020-11-08 12:02 UTC, ceford commented
I have deleted my Pass test. With the patch applied I can include html tags, such as <h1>, that are evident in the list view. That is an undesirable side effect.

2020-11-08 12:05 UTC, richard67 commented
@ceford It was not enough to delete the test comment. You should have used again the "Test this" button and then select the "I have not texted" (or so) test result. I've done that for you now, I've reset your test result so it isn't counted by the tracker and in the test on GitHub.

2020-11-08 12:06 UTC, richard67 commented
@ceford It's not only an undesirable side effect, it justifies a negative test result (failed test).

2020-11-08 19:44 UTC, ceford commented
@richard67 thank you for the tips - it seems I am learning the hard way. 

Related: is there a case for trimming string input by default?

I was looking for documentation on TRIM and concluded that all of the tutorials I could find are a bit dated. The code in InputFilter.php seemed the best place to look.

2020-11-09 09:28 UTC, infograf768 commented
The problem here is that the ClientTable does not have its own `check()` method where we could check that the text entered is empty after a code similar to
```
if (trim($this->contact)) === '')
		{
			$this->setError(Text::_('COM_BANNERS_PROVIDE_VALID_CONTACT'));

			return false;
		}
```

2020-11-09 15:04 UTC, infograf768 commented
Needs 
use Joomla\CMS\Language\Text;

on top of file

2020-11-09 15:05 UTC, infograf768 commented on administrator/components/com_banners/src/Table/ClientTable.php
> +		if (trim($this->name) == '')
can use ===

2020-11-09 15:10 UTC, infograf768 commented on administrator/components/com_banners/src/Table/ClientTable.php
> +	 * @since   {
use

* @since   __DEPLOY_VERSION__

2020-11-09 16:07 UTC, MeghaBiranje commented on administrator/components/com_banners/src/Table/ClientTable.php
> +		if (trim($this->name) == '')
Yes updated.

2020-11-09 16:08 UTC, MeghaBiranje commented on administrator/components/com_banners/src/Table/ClientTable.php
> +	 * @since   {
Done.

2020-11-10 06:24 UTC, infograf768 commented on administrator/components/com_banners/src/Table/ClientTable.php
> +	 * @since   DEPLOY_VERSION
`__DEPLOY_VERSION__`

2020-11-10 06:25 UTC, infograf768 requested changes

2020-11-10 06:25 UTC, infograf768 commented on administrator/language/en-GB/com_banners.ini
> +COM_BANNERS_PROVIDE_VALID_CONTACT="Please provide a valid, non-blank contact name"
Please alpha order strings

2020-11-10 18:33 UTC, MeghaBiranje commented on administrator/components/com_banners/src/Table/ClientTable.php
> +	 * @since   DEPLOY_VERSION
done

2020-11-10 18:33 UTC, MeghaBiranje commented on administrator/language/en-GB/com_banners.ini
> +COM_BANNERS_PROVIDE_VALID_CONTACT="Please provide a valid, non-blank contact name"
done

2020-11-16 10:43 UTC, infograf768 commented
I have tested this item :white_check_mark: successfully on 743573948eb890581f1ce7dfcd86fa16554174d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31354">issues.joomla.org/tracker/joomla-cms/31354</a>.</sub>

2020-11-16 11:56 UTC, gostn commented
I have tested this item :white_check_mark: successfully on 743573948eb890581f1ce7dfcd86fa16554174d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31354">issues.joomla.org/tracker/joomla-cms/31354</a>.</sub>

2020-11-16 12:01 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31354">issues.joomla.org/tracker/joomla-cms/31354</a>.</sub>

2020-11-16 12:03 UTC, richard67 commented
@infograf768 Could you approve the code on GitHub so the "Changes requested" disappears at the bottom of the PR which currently still is shown due to your previews review with change requests?

2020-11-16 19:41 UTC, Quy commented on administrator/components/com_banners/src/Table/ClientTable.php
> +use Joomla\CMS\Language\Text;
```suggestion
use Joomla\CMS\Language\Text;
use Joomla\CMS\Table\Table;
```

2020-11-19 08:57 UTC, infograf768 approved these changes

2020-11-19 09:01 UTC, infograf768 commented
Applied @Quy suggestion in https://github.com/joomla/joomla-cms/pull/31354#discussion_r524526185 . 
No change for tests. Keeping RTC.

2020-11-22 08:52 UTC, merged

2020-11-22 08:52 UTC, infograf768 commented
tks