[4.0] Don't display hidden menu items at all.
joomla/joomla-cms pull request #31443
Opened 2020-11-20 18:19 UTC by Harmageddon

### Summary of Changes
If an item is set to hidden / not show, it doesn't make any sense to display an empty `<li>` item.

### Testing Instructions
Because it is a backend module, this is a bit tricky.
1. At Menus - Manage, select "Administrator" and create a new menu.
2. In this new administrator menu, create one basis menu item on the top level, and at least three menu items that are children to this basis menu item.
3. For one of these child items, under "Link Type", set "Display in Menu: No".
4. Go to the Home Dashboard.
5. Click on "Add Module to the Dashboard".
  - Type: "Administrator Dashboard Menu"
  - Menu: select your previously created menu
  - Enter a module title and save the module.
6. Look at the newly created module.

### Actual result BEFORE applying this Pull Request
At the place, where the hidden item would be, there is an empty `<li></li>` tag, which is displayed as empty space between two lines.
![Screenshot_2020-11-20 Home Dashboard - Joomla 4 Test Site - Administration 2](https://user-images.githubusercontent.com/1410135/99835534-088bc100-2b65-11eb-8991-e200b783cd5a.png)

### Expected result AFTER applying this Pull Request
Only the items that are not hidden are displayed.
![Screenshot_2020-11-20 Home Dashboard - Joomla 4 Test Site - Administration](https://user-images.githubusercontent.com/1410135/99835528-075a9400-2b65-11eb-9766-78a66aa4379e.png)

### Documentation Changes Required
None

2020-11-20 21:15 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 873693de0f7c9a08b888e4b9371e42cfd4c95789<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31443">issues.joomla.org/tracker/joomla-cms/31443</a>.</sub>

2020-11-20 22:45 UTC, brianteeman requested changes
just code style for readability and consistency

2020-11-20 22:45 UTC, brianteeman commented on administrator/modules/mod_submenu/tmpl/default.php
> +						<?php // Only if Menu-show = true
```suggestion
						<?php // Only if Menu-show = true ?>
```

2020-11-20 22:45 UTC, brianteeman commented on administrator/modules/mod_submenu/tmpl/default.php
> +						if ($params->get('menu_show', 1)) : ?>
```suggestion
						<?php if ($params->get('menu_show', 1)) : ?>
```

2020-11-21 08:16 UTC, chmst commented
I have tested this item :white_check_mark: successfully on a8ba893ec9d0dd173c48c22d8082a9ae21390541<br /><br />On Code inspect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31443">issues.joomla.org/tracker/joomla-cms/31443</a>.</sub>

2020-11-21 08:26 UTC, gostn commented
I have tested this item :white_check_mark: successfully on a8ba893ec9d0dd173c48c22d8082a9ae21390541<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31443">issues.joomla.org/tracker/joomla-cms/31443</a>.</sub>

2020-11-21 08:48 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31443">issues.joomla.org/tracker/joomla-cms/31443</a>.</sub>

2020-11-21 10:02 UTC, merged

2020-11-21 10:02 UTC, infograf768 commented
Tks.

2020-11-21 10:09 UTC, adj9 commented
I have not tested this item.<br /><br />I have no possibility to select the menu.

In Administrator Dashboard Menu I don't have the created menu items.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31443">issues.joomla.org/tracker/joomla-cms/31443</a>.</sub>

2020-11-21 11:06 UTC, Harmageddon commented
@adj9 How does your menu structure look? Do you have one parent menu item and several sub-menu items? Because this module only displays submenus, not entire menus. So the structure of "Test Menu" should look like this:

- Menu Item Lvl 1
  - Subitem 1
  - Subitem 2 (hidden)
  - Subitem 3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31443">issues.joomla.org/tracker/joomla-cms/31443</a>.</sub>