[4.0][CLI] Add a task to discover extensions
joomla/joomla-cms pull request #31524
Opened 2020-11-29 08:39 UTC by astridx

### Summary of Changes

i added a CLI task to discover extensions. I took https://github.com/joomla/joomla-cms/pull/28666 as an example

### Testing Instructions
1. Apply this PR
2. Copy or symlink an extension to your Joomla installation
3. Run ` php ./cli/joomla.php extension:discover --eid=122` for discovering the extension with the ID 122 
or 
Run the command without a parameter (like this `php ./cli/joomla.php extension:discover`) for discovering all extensions, that are copied to Joomla but not installed.

### Documentation Changes Required
I would add it here: https://docs.joomla.org/J4.x:CLI_Update

2020-11-29 11:36 UTC, richard67 commented
@astridx Could you check and fix PHP code style errors reported by drone here [https://ci.joomla.org/joomla/joomla-cms/37913/1/6](https://ci.joomla.org/joomla/joomla-cms/37913/1/6)? Thanks in advance

2020-11-29 13:11 UTC, laoneo commented on libraries/src/Console/ExtensionDiscoverCommand.php
> +		\n  --extension: The ID of the extension
Must this be here eid?

2020-11-29 13:11 UTC, laoneo commented on libraries/src/Console/ExtensionDiscoverCommand.php
> +	 * @param   string  $path  Path to the extension zip file
here also $eid

2020-11-29 16:44 UTC, astridx commented
@laoneo @richard67 Thank you. I fixed the copy and pasted mistakes.

2020-11-29 16:47 UTC, richard67 commented
@astridx Thanks. It might be that system tests are failing in drone for your PR, but this is very likely unrelated. But if you want to have it nice, you can update your branch to latest 4.0-dev of the CMS, then the system tests will pass and all will be green, which looks nicer ;-)

2020-11-29 17:22 UTC, astridx commented
Now it is nice and green :)

2020-11-29 17:26 UTC, brianteeman commented on libraries/src/Console/ExtensionDiscoverCommand.php
> + * @copyright  Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
```suggestion
 * @copyright   (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
```

2020-11-29 19:12 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 4a1e74f4f1efbd6567d752a2b72f93a6422abf11<br /><br />Tested successfully in Beta6-dev of 29 November<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31524">issues.joomla.org/tracker/joomla-cms/31524</a>.</sub>

2020-11-29 19:22 UTC, brianteeman commented
Does this find the extensions or does it install them?

2020-11-30 08:39 UTC, alikon requested changes

2020-11-30 08:39 UTC, alikon commented on libraries/src/Service/Provider/Console.php
> +				return new ExtensionDiscoverCommand;
you should pass the db here
`return new ExtensionDiscoverCommand($container->get('db'));`

see https://github.com/astridx/joomla-cms/pull/2

2020-11-30 08:45 UTC, laoneo commented on libraries/src/Service/Provider/Console.php
> +				return new ExtensionDiscoverCommand;
Nice proposal. If you start to inject stuff, then you can also inject the installer as well :smirk:

2020-11-30 12:38 UTC, wilsonge commented
@brianteeman is right - can we name this to discover install - because we should add a separate discover task which covers the 'refresh' task in github https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/controllers/discover.php#L26-L33

2020-11-30 12:50 UTC, toivo commented
I have tested this item :white_check_mark: successfully on b4ffab65728fc1c62d1e85804be4aefc8a879d2a<br /><br />Tested successfully in Beta6-dev and PHP 8.0.  

Copied the following free 3rd party extensions to modules and the PR detected and installed them:
Mini Frontpage from https://extensions.joomla.org/extension/news-display/articles-display/mini-frontpage/
Rapid Contact from https://extensions.joomla.org/extension/contacts-and-feedback/contact-forms/rapid-contact/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31524">issues.joomla.org/tracker/joomla-cms/31524</a>.</sub>

2020-11-30 13:03 UTC, laoneo commented on libraries/src/Console/ExtensionDiscoverCommand.php
> +		$jInstaller = new Installer;
Can you also inject the installer the same way as the database.

2020-12-01 02:50 UTC, wilsonge commented on libraries/src/Console/ExtensionDiscoverCommand.php
> +		$jInstaller = new Installer;
Installer isn’t available in the container. So I think we should make it optionally injectable in the constructor for testing. But still fine to run the init in the constructor if nothing is passed in

2020-12-01 06:45 UTC, laoneo commented on libraries/src/Console/ExtensionDiscoverCommand.php
> +		$jInstaller = new Installer;
You can create the instance in the serviceprovider

2020-12-01 08:52 UTC, astridx commented on libraries/src/Console/ExtensionDiscoverCommand.php
> +		$jInstaller = new Installer;
@laoneo @wilsonge
I would like to leave it that way in this PR because it is implemented in the same way in other places. 
For example here: https://github.com/joomla/joomla-cms/blob/fc55f96768c9e7cfd09e6f043161ee49e9e2a6da/libraries/src/Console/ExtensionInstallCommand.php#L132

I think it is confusing when things are different in a CMS. I agree with you that it should be changed. But then in all places. I would do this in a separate PR.

2020-12-01 09:16 UTC, astridx commented
> @brianteeman is right - can we name this to discover install - because we should add a separate discover task which covers the 'refresh' task in github https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/controllers/discover.php#L26-L33

@wilsonge  I don't understand what you mean with this.

2020-12-01 12:32 UTC, laoneo commented on libraries/src/Console/ExtensionDiscoverCommand.php
> +		$jInstaller = new Installer;
Ok, I can do then a followup pr.

2020-12-12 19:50 UTC, laoneo commented
I guess he means to rename the class to ExtensionDiscoverInstallCommand.

2020-12-22 12:32 UTC, laoneo commented
Renamed the classes, can be tested now.

2020-12-22 14:04 UTC, HLeithner commented
Joomla 4.0 is in feature freeze can you please rebase this on j4.1 or I can do this for you, thanks

2020-12-22 14:10 UTC, laoneo commented
This is not a feature, it is an enhancement. And I need it for testing extensions in j4. So no way to rebase to 4.1.

2020-12-22 14:18 UTC, HLeithner commented
And I need joomla 4 ready to ship

2020-12-22 17:57 UTC, laoneo commented
And postponing this to 4.1 will help?

2020-12-22 18:10 UTC, laoneo commented
Ok, I give up. Do whatever you want with it. I'm building it on my own

2020-12-23 07:19 UTC, alikon commented
after the latest commit this is needed ExtensionDiscoverInstall renamed to ExtensionDiscoverInstallCommand
see https://github.com/astridx/joomla-cms/pull/3

2020-12-23 09:10 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 13819427f9e999b3bd081f6d7f2a3698b85a9d34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31524">issues.joomla.org/tracker/joomla-cms/31524</a>.</sub>

2021-03-18 09:33 UTC, merged

2021-03-18 09:35 UTC, HLeithner commented
thanks and sorry