[4.0] check for libxml
joomla/joomla-cms pull request #31735
Opened 2020-12-20 14:26 UTC by brianteeman

PR for #29425

This is a real edge case discovered by @fedik https://github.com/joomla/joomla-cms/issues/29425#issuecomment-640010134

libxml is enabled by default when compiling php and it cannot be disabled etc in a php.ini

The check I have put in place is the same one that myBB uses for the same issue.

The only questions are
1. Did I put the check early enough
2. Do we really need it for such an edge case

2020-12-20 14:49 UTC, dgrammatiko commented
@brianteeman although this would work I think that the check needs to be in the Initial checks (compatibility layer): https://github.com/joomla/joomla-cms/blob/77bcd7198380ea033c77eecfd07ceb839805fe5f/installation/src/Model/ChecksModel.php#L66

Also that would result to a better error view

2020-12-20 14:49 UTC, HLeithner commented
@brianteeman can you fix the cs plz

2020-12-20 14:54 UTC, Fedik commented
maybe better to place it in `installation/includes/app.php` or even `installation/includes/index.php`

with some nice message like:
https://github.com/joomla/joomla-cms/blob/77bcd7198380ea033c77eecfd07ceb839805fe5f/installation/index.php#L20-L26

> I think that the check needs to be in the Initial checks (compatibility layer)

The problem the App does not even start if `xml` not available ;)

2020-12-20 14:57 UTC, dgrammatiko commented
> maybe better to place it in installation/includes/app.php or even installation/index.php

Since all the checks from the Model could end up being foobar if any of these fail I guess beefing up these files is a more realistic approach. Yeah I know the code will end up being god awful but functional code is better than beautiful non functional code.

My 2c

2020-12-20 23:17 UTC, dgrammatiko requested changes

2020-12-20 23:17 UTC, dgrammatiko commented on installation/src/Application/InstallationApplication.php
> +			if (file_exists($template ))
`if (file_exists($template))`

2020-12-21 11:01 UTC, dgrammatiko requested changes

2020-12-21 11:01 UTC, dgrammatiko commented on installation/src/Application/InstallationApplication.php
> +			$template = JPATH_ROOT . '/media/system/noxml.html';
```suggestion
			$template = JPATH_ROOT . '/media/system/html/noxml.html';
```

2021-02-03 19:31 UTC, closed without merging