Fix comments
joomla/joomla-cms pull request #31784
Opened 2020-12-26 16:25 UTC by chmst

Pull Request for Issue #22776 .

### Summary of Changes
Fix comments and add a comment for a unclear line

### Testing Instructions
Code review

2020-12-26 17:08 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on fce37e6a53da34a2afb114d0106c025f0f1158a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31784">issues.joomla.org/tracker/joomla-cms/31784</a>.</sub>

2020-12-26 17:51 UTC, gostn commented
I have tested this item :white_check_mark: successfully on fce37e6a53da34a2afb114d0106c025f0f1158a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31784">issues.joomla.org/tracker/joomla-cms/31784</a>.</sub>

2020-12-26 18:12 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31784">issues.joomla.org/tracker/joomla-cms/31784</a>.</sub>

2020-12-26 21:44 UTC, richard67 commented
@Quy Wrong milestone and label? The PR is for staging, not 4.0-dev.

2020-12-26 21:47 UTC, richard67 requested changes

2020-12-26 21:47 UTC, richard67 commented on plugins/actionlog/joomla/joomla.php
> +		// Override context (com_users.group) with the component context (com_users) to pass the chekLoggable
```suggestion
		// Override context (com_users.group) with the component context (com_users) to pass the checkLoggable
```

2020-12-27 10:25 UTC, richard67 commented on plugins/actionlog/joomla/joomla.php
> +		// Override context (com_users.group) with the component context (com_users) to pass the chekLoggable
Please fix that typo.

2020-12-27 19:45 UTC, richard67 approved these changes

2020-12-27 19:45 UTC, chmst commented
Thank you @richard67 and @Quy this is for stable, but the fix is valid also in J4

2020-12-27 22:20 UTC, merged

2020-12-27 22:20 UTC, wilsonge commented
As this is just code comments merging this during the RC Window