[4.0] Showon init only once, public method Joomla.Showon.initilise()
joomla/joomla-cms pull request #32069
Opened 2021-01-17 11:13 UTC by Fedik

### Summary of Changes
Same as #32061
The code make sure that showon initialised only once, no mater how often Joomla.Showon.initilise was called.
Also add public `Joomla.Showon.initilise` (to be in sync with 3.10)

### Testing Instructions

Apply path, run `npm install`
Make sure `showon` still works.

Example, go to global config change "Debug Language" on/off, should downup/hides "Language Display" field.
Also the field "Language Display"  will have extra attribute `data-showon-initialised`

### Actual result BEFORE applying this Pull Request
showon works,
the showon field do not have `data-showon-initialised`

### Expected result AFTER applying this Pull Request
showon works,
the showon field do have `data-showon-initialised` attribute

2021-01-17 11:18 UTC, dgrammatiko requested changes

2021-01-17 11:18 UTC, dgrammatiko commented on build/media_source/system/js/showon.es6.js
> +          if (field.hasAttribute('data-showon-initialised')) {
Can we change this to `field.dataset.hasOwnProperty('showonInitialised')`

2021-01-17 11:20 UTC, Fedik commented on build/media_source/system/js/showon.es6.js
> +          if (field.hasAttribute('data-showon-initialised')) {
in the end it the same, but use the attribute is more clear for "visual debuging" ;)

2021-01-17 11:21 UTC, dgrammatiko commented on build/media_source/system/js/showon.es6.js
> +          field.setAttribute('data-showon-initialised', '');
`field.dataset.showonInitialised = '';`

2021-01-17 15:25 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 1e2b0ddf9921f552c4c291f2884a80ad56c6e6e8<br /><br />@wilsonge this can be merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32069">issues.joomla.org/tracker/joomla-cms/32069</a>.</sub>

2021-01-18 12:59 UTC, HLeithner commented
@Fedik please fix cs https://ci.joomla.org/joomla/joomla-cms/39281

2021-01-18 13:43 UTC, Fedik commented
done

2021-01-25 17:54 UTC, ceford commented
I have tested this item :white_check_mark: successfully on e28aae07b0849cf48ed2a8deaa101777b54d2bb8<br /><br />To be clear: it is the control-group div that contains data-showon-initialised.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32069">issues.joomla.org/tracker/joomla-cms/32069</a>.</sub>

2021-01-27 22:47 UTC, merged

2021-01-27 22:47 UTC, wilsonge commented
Thanks!