Adding color-picker to Joomla piece by piece
joomla/joomla-cms pull request #32510
Opened 2021-02-24 19:06 UTC by thednp

2021-02-24 19:20 UTC, thednp commented
@dgrammatiko I completed what I said, I think the build fails to find the `tinycolor` becase we gave it a wrong path? perhaps the name you suggested wasn't correct?

2021-02-24 19:24 UTC, dgrammatiko commented
> @dgrammatiko I completed what I said, I think the build fails to find the tinycolor becase we gave it a wrong path? perhaps the file name you suggested wasn't correct?

You have to run `npm install @ctrl/tinycolor -S` to bring the asset in the dependencies. This will update the package.json and the package.json.lock. Right now you're referring to a file that is not existing nowhere.

2021-02-24 19:27 UTC, thednp commented
Hold on, I think I get it, I'm checking out this on my machine and try there to install and commit back to git.

2021-02-24 19:36 UTC, dgrammatiko commented
> Hold on, I think I get it, I'm checking out this on my machine and try there to install and commit back to git.

Exactly, and once yo'll there run also `npm run lint:js` to make sure the js is following the Code Style of the project

2021-02-24 19:38 UTC, thednp commented
I'm now cleaning up everything minicolors, hold on.

2021-02-24 19:40 UTC, thednp commented
What's this for `administrator\components\com_admin\script.php` it mentions minicolors and I just found it out.

2021-02-24 19:41 UTC, dgrammatiko commented
You have to add there the files you're deleting (media/vendor/minicolors... )

2021-02-24 19:48 UTC, thednp commented
I will update that in the next commit to my repo, I'm now going to lint and build again.

Note: on install I got some minor error with dependencies. Probably there need to be some cleanup there.

2021-02-24 19:56 UTC, thednp commented
@dgrammatiko I'm getting this error on `npm run build:js`

```
Error: ENOENT: no such file or directory, open '\Joomla SVN\media\system\css\joomla-toolbar-button.css'
```

right after 

```
Transpiling Web Component file: \Joomla SVN\build\media_source\system\js\fields\tinycolor.w-c.es6.js
```

ideas?

2021-02-24 19:57 UTC, thednp commented
Anyways, I've updated the `package.json` I should try and commit see what the online tools get, ei?

2021-02-24 20:39 UTC, thednp commented
I'm still getting the same error (posted above) trying to do build locally. The online `continuous-integration` says something about `[Error: ENOENT: no such file or directory, stat '/********/src/node_modules/@ctrl/tinycolor/tinycolor.js']` probably it's looking for a fie that doesn't exist.

So yea, I don't know how to fix this. This is beyond me.

2021-02-24 20:41 UTC, dgrammatiko commented
> So yea, I don't know how to fix this. This is beyond me.

Follow the path, you should find a `dist` folder with the file that you need. Point the settings.json to the right path

2021-02-24 20:42 UTC, thednp commented
Reminder: tinycolor is Typescript sourced. How can we set the build script to not look for a source and just use our source that I've uploaded.

2021-02-24 20:44 UTC, dgrammatiko commented
@thednp please check `node_modules/@ctrl/tinycolor/dist`. The JS ecosytem works like that for a decade...

2021-02-24 21:25 UTC, thednp commented
Yes, that is true, however, perhaps I'm burned out working since Monday non-stop on this trying to finish it, I'm soo tired I can't figure out what to do. I appreciate any hint or suggestion.

2021-02-24 21:32 UTC, thednp commented
`build/build-modules-js/settings.json`

```json
      "@ctrl/tinycolor": {
        "name": "tinycolor",
        "js": {
          "dist/index.js": "js/tinycolor.js" 
        },
        "dependencies": [],
        "provideAssets": [
          {
            "name": "tinycolor",
            "type": "script",
            "uri": "dist/index.js",
            "attributes": {
              "defer": true
            }
          },
          {
            "name": "tinycolor",
            "type": "preset",
            "dependencies": [
              "tinycolor#script"
            ]
          }
        ],
        "licenseFilename": "LICENSE.md"
      },
```

`dist/index.js` is actually the path to `node_modules/@ctrl/tinycolor/dist/index.js`

2021-02-24 21:41 UTC, dgrammatiko commented
Run `eslint --config build/.eslintrc --ignore-pattern '/media/' --fix --ext .es6.js,.es6,.vue .` to fix most of the Code Style errors

2021-02-24 22:11 UTC, Quy commented on administrator/language/en-GB/joomla.ini
> +JFIELD_COLOR_ADVANCED_FORMAT_HEX="HEX colour format"
Please sort keys in alpha order.

2021-02-24 23:05 UTC, thednp commented
Seems I need to do some lint work, I will get back to it tomorrow.

Thanks guys.

2021-02-25 00:22 UTC, thednp commented
This commit validates npm but not JS

`708:4  error  'TinyColor' is not defined  no-undef` 

I've been looking into other files and they all do fine with `Choices.js` and such cannot figure it out.

ideas?

2021-02-25 10:55 UTC, thednp commented
@dgrammatiko @Quy finally done solving all eslint errors, please proceed with your test.

2021-02-25 11:41 UTC, thednp commented
@dgrammatiko please how can I solve the `build/build-modules-js/settings.json` to make it compile `TinyColor ` and to properly update the `media/system/joomla.asset.json`?

2021-02-25 12:28 UTC, brianteeman commented
Do you still need help on that or did you just work it out?

2021-02-25 12:31 UTC, thednp commented
@brianteeman yes, I need help.

2021-02-25 12:36 UTC, brianteeman commented on build/build-modules-js/settings.json
>          "licenseFilename": "LICENSE.md"
This needs to be changed 

```suggestion
        "licenseFilename": "LICENSE"
```

2021-02-25 12:43 UTC, thednp commented
In my local version those lines are not present.

2021-02-25 12:48 UTC, brianteeman commented
Then you have a problem in your local branch

2021-02-25 13:00 UTC, brianteeman commented
I _think_ the problem you are having with minification is that the compilejs script does not look in the /media folder to find files to compress. @dgrammatiko should be able to help more on that as its above my payscale

2021-02-25 13:04 UTC, dgrammatiko commented
This needs to await for https://github.com/joomla/joomla-cms/pull/32315 to be merged and then do the simillar changes as the ones done in that PR for `punycode`

2021-02-25 13:14 UTC, thednp commented
> 
> 
> This needs to await for #32315 to be merged and then do the simillar changes as the ones done in that PR for `punycode` and `build/media_source/system/js/fields/validate.es6.js`

That would hopefully help solve this

```
/********/src/build/media_source/system/js/fields/joomla-field-color-picker.es6.js
```

2021-02-25 13:17 UTC, dgrammatiko commented
> 737:20  error  'TinyColor' is not defined  no-und

Yes but you have to revert the change were you deleted the `import ...`

2021-02-25 13:18 UTC, thednp commented
So `import` is there to stay?

2021-02-25 13:20 UTC, dgrammatiko commented
Yes, but right now the build tools cannot resolve imports, they have to wait for #32315  to be merged

2021-02-25 20:17 UTC, thednp commented
@dgrammatiko what about including some conversion functions within color-picker? We can have it fully support RGB(a), HSL(a), HEX without TinyColor, perhaps not 100% the best solution, but it will work and will be alot faster.

2021-02-25 20:20 UTC, dgrammatiko commented
> IE10+ supported.

Joomla 4 will NOT support IE10

> @dgrammatiko what about including some conversion functions within color-picker

No. In general things that are widely available should be brought to the project through NPM. There's no reason for the project to support code that can just be imported. Just test the other PR and wait till ot gets merged

2021-02-26 04:47 UTC, thednp commented
@dgrammatiko if `import` is there to stay, then on compile it will include TinyColor into color-picker bundle and will no longer be required in both `build/build-modules-js/settings.json` and `build\media_source\system\joomla.asset.json`. Then the PHP layout file will just `->useScript()` instead of `->usePreset()->useScript()`.

On another note, I've been thinking about developing on the `$keywords`, by default it would have `inherit, currentColor, transparent` as default values, but devs can set `keywords="false"` to disable and explicitly ask from the user a real color to be used, as I explained above. Devs can set a plethora of keywords, TinyColor should work fine with all web safe colors EG: `navy`, `lime`, etc (256 of them I think).

This means that our color picker will have 2 dropdowns: one for color-dropdown (the picker itself) and one for `keyword` colors. You did mention something about buttons and stuff.

Let me know what you think.

2021-02-26 11:05 UTC, dgrammatiko requested changes

2021-02-26 11:05 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -((customElements, TinyColor, Joomla) => {
Please remove the iife here

2021-02-26 11:05 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +((customElements, Joomla) => {
Please remove the iife here

2021-02-26 11:05 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +})(customElements, Joomla);
Please remove the iife, this is a legacy thing but the actual core in this file is module

2021-02-26 11:10 UTC, dgrammatiko requested changes

2021-02-26 11:10 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  <label for="${pickerID}" class="visually-hidden">${Joomla.Text._('JFIELD_COLOR_SELECT', 'Select a colour')}</label>
Please remove the `Joomla.Text._('JFIELD_COLOR_SELECT', 'Select a colour')`. Use an attribute in the Web Component and just `this.getAttribute('some-text')`. Pass the value from the PHP world like `<color-picker some-text="<?php echo Text::_('SOME_TEXT')"`

2021-02-26 11:13 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  <label for="${pickerID}" class="visually-hidden">${Joomla.Text._('JFIELD_COLOR_SELECT', 'Select a colour')}</label>
Alright. I'm on it, what do you think about my above suggestions? Also please check the `settings.json` in this branch.

2021-02-26 11:25 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  <label for="${pickerID}" class="visually-hidden">${Joomla.Text._('JFIELD_COLOR_SELECT', 'Select a colour')}</label>
Some time ago I wrote https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/fields/joomla-field-simple-color.w-c.es6.js which I think can be reused with a list of defined colours here. Probably I'll have to refactor couple of things but most of the code there solves this (I think the only thing needed is provide some meaningful backgrounds for the buttons for colours like inherit, currentcolor, etc so should be an easy patch)

2021-02-26 11:44 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  <label for="${pickerID}" class="visually-hidden">${Joomla.Text._('JFIELD_COLOR_SELECT', 'Select a colour')}</label>
About the `Joomla.Text._()` tags, I was only following other fields' code ideas. was trying to "fix" the EsLint for `TinyColor not defined`. But I hope your commit gets approved soon.

2021-02-26 11:46 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  <label for="${pickerID}" class="visually-hidden">${Joomla.Text._('JFIELD_COLOR_SELECT', 'Select a colour')}</label>
The usage of the Joomla object within a Web Component is an antipattern but I know we have a few of them in the repo

2021-02-26 19:18 UTC, thednp commented
I'm implementing $keyworks, here's a sneak peek

![image](https://user-images.githubusercontent.com/6761246/109345037-741db280-7867-11eb-93d1-b21b8a35ed9f.png)

2021-02-27 07:39 UTC, thednp commented
@dgrammatiko as to your concerns, here is my proposal for keywords:

![color-menu](https://user-images.githubusercontent.com/6761246/109380124-43bd2f00-78ce-11eb-90f4-7d7782c69933.png)

As shown in the image:

* When you set `currentColor` / `transparent` / `inherit`, color-picker will use `white` for the displayed chosen color, but the inputs will use the chosen keyword. This keyword value is NOT to be used in SCSS transformations like `darken()`, `desaturate()`, etc.

* When keywords are set by devs, TinyColor kicks in and replace for instance `navy` with the appropriate `rgb(0,0,128)`. These keywords are "safe" for SCSS transformations.

@brianteeman your input?

2021-02-28 16:39 UTC, brianteeman commented
It is not normal practice in Joomla to introduce any file that is not copyright Joomla or GPL licenced if it is not a vendor supplied file and stored in a /vendor folder

2021-02-28 16:54 UTC, thednp commented
You suggest we should rename License to GPL 2.0?

2021-02-28 16:59 UTC, thednp commented
With that last commit, color-picker is pretty much complete, should I attempt to write a documentation draft?

Also, @dgrammatiko what's up with the other layouts of the Color field? Pretty much unusable on my end.

2021-02-28 18:38 UTC, brianteeman commented
If the file is part of core and dnot vendor then it should be copyright joomla and gpl

2021-02-28 18:45 UTC, dgrammatiko commented
> If the file is part of core and dnot vendor then it should be copyright joomla and gpl

That's not true, there are several places where the code was committed with the original docblocks...

2021-02-28 18:46 UTC, thednp commented
I did what I've been instructed, I only added my name next to the original file author's name. I don't mind either way as long as it's all good for the community.

2021-02-28 20:02 UTC, thednp commented
@dgrammatiko do you want to publish this to npm as a 3rd party source?

2021-02-28 20:06 UTC, dgrammatiko commented
@thednp I can't publish your code, if you want to do that you have every right. As is the code is fine as you attribute both the other 2 other authors. Also it should be fine for Joomla as is because there are other instances with similar docblocks

2021-02-28 20:30 UTC, thednp commented
It's fine for me man, just let me know what needs to be changed.

2021-03-01 10:43 UTC, thednp commented
@brianteeman I've updated the file header as discussed, and the above section to include a documentation draft, but there are a few things that might need clarification for the `simple` and `slider` control. Also I've added some additional testing instructions.

Important:  There are also some inconsistencies in the `libraries\src\Form\Field\ColorField.php` that seem to be disconnected from the layouts, for instance:

* line 39 `protected $control = 'hue';` but only works with 'simple', 'slider' and 'advanced';
* you cannot set "layout" property for the `<field type="Color">` since the `ColorField` sets it based on the `control` property.

@dgrammatiko as I've provided a documentation draft in the head of this thread, your supervision is required. I also have to point out there are some issues with the other layouts that need to be solved.

2021-03-01 10:47 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
I'm not ok with this. This could be called plagiarism

2021-03-01 10:49 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
So we move it to vendor folder?

2021-03-01 10:49 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
No, but you have to attribute both me and the other Author that you based your code on.

2021-03-01 10:53 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
To be clear here, If I was committing my own code to Joomla then I don't expect my name to be on the license, although Joomla still treats some devs differently (there are cases that people have their names on Files). But if I used some code from some other dev then I have to at least mention that otherwise, it's plain plagiarism.

2021-03-01 10:57 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
Come on man, talk to me.

2021-03-01 11:12 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
The copyright notice of that file is only mentioning the authors of the file: you the original author, and me, the one who completed it.

2021-03-01 11:23 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
So what next?

2021-03-01 11:42 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
Ah yes, I found this `media\system\js\fields\joomla-field-simple-color.js`

```js
/**
 * Based on:
 * Very simple jQuery Color Picker
 * Copyright (C) 2012 Tanguy Krotoff
 * Licensed under the MIT license
 *
 * ADAPTED BY: Dimitris Grammatikogiannis
 *
 * MIT License
 * /
```

2021-03-01 11:44 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
You just need the `Based on ` part also you don't have to put my name you can put there the link to codepen

2021-03-01 12:00 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
So this I guess is going to be

Now include the link to your pen or mine, which is close to this version I'm about to commit?

```js
/**
* Implements TinyColor https://github.com/scttcper/tinycolor
*
* BASED ON: https://codepen.io/dgrammatiko/pen/zLvXwR?editors=1010
*
* Example
* <joomla-field-color-picker>
*   <input type="hidden">
* </joomla-field-color-picker>
*/
```

2021-03-01 12:04 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
> `Implements TinyColor https://github.com/scttcper/tinycolor`

You don't need this line as once you run the `npm run build:js` the `import TinyColor from '@ctrl/tinycolor';` will be replaced with the actual code of tinycolor which already has the license there 😉

2021-03-01 12:06 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
ALright, also link to your original codepen or mine, modified?

2021-03-01 12:15 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> -* Copyright Dimitris Grammatikogiannis & Dan Partac
Whatever, I'm just gonna use both.

2021-03-01 13:43 UTC, thednp commented
@dgrammatiko I'm sorry to bother you, where can I talk to you without upsetting Brian again, I need to ask you about SCSS compile stuff.

2021-03-01 13:44 UTC, dgrammatiko commented
twitter DM @ dgrammatiko

2021-03-01 14:07 UTC, thednp commented
@dgrammatiko I've followed you @ dnp_theme

2021-03-01 18:45 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +((customElements, Joomla) => {
You mean remove the (() => {}()) wrapper?

2021-03-01 19:40 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +((customElements, Joomla) => {
If that is what you meant, issue is resolved. (Couldn't reach you Twitter, you probably busy)

2021-03-01 20:20 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +})(customElements, Joomla);
Done.

2021-03-06 06:51 UTC, thednp commented
@dgrammatiko @brianteeman and anyone following this development.
I've been thinking about integrating `$colors` into our color picker, make it have all possible features in one place, the `advanced` layout can actually become the default and only layout for the `ColorField`. What do you say?

@Quy / @brianteeman 
I've added a documentation draft at the top of the page, please update PR tags.

2021-03-06 06:58 UTC, thednp commented
@richard67 we have a minor conflict here.

2021-03-06 09:49 UTC, richard67 commented
@thednp It seems to be an easy conflict so GitHub shows a button "Resolve conflicts" at the bottom of the PR. If you use that button, the same will happen here on GitHub in their web UI as what would happen if you do on your local environment a merge of the 4.0-dev branch of the CMS repo (upstream) into your branch for this PR. It will show the same conflict for that file.

If you then edit the file (either online by using their button or locally after starting the merge), you will see that conflicts are marked in a special way, e.g. here now:

```
<<<<<<< patch-1
			// Joomla 4.0 Beta 8
			'administrator/templates/atum/scss/vendor/minicolors/minicolors.scss',
			'templates/cassiopeia/scss/vendor/_minicolors.scss',
=======
			// Joomla 4.0 Beta 7
			'/media/vendor/skipto/js/dropMenu.js',
			'/media/vendor/skipto/css/SkipTo.css',
>>>>>>> 4.0-dev
```

In very rare cases it is easy and you either take your part (between `<<<<<<< patch-1` and `=======`) or "their" part (between `=======` and `>>>>>>> 4.0-dev`), and often you have such options to take "yours" or "theirs" in IDEs or Git clients with GUI. Bit in most cases that's not right, and you have to resolve the conflict with a manual edit.

For the conflict here that would be:

```
			// Joomla 4.0 Beta 7
			'/media/vendor/skipto/js/dropMenu.js',
			'/media/vendor/skipto/css/SkipTo.css',
			// Joomla 4.0 Beta 8
			'administrator/templates/atum/scss/vendor/minicolors/minicolors.scss',
			'templates/cassiopeia/scss/vendor/_minicolors.scss',
```

I could solve that here, but I thought I explain you a bit so maybe you can learn that. Handling conflicts in software development is a useful knowledge (as long as you not always only develop alone on only one thing).

Let me know if I shall fix it for you, or if you prefer to try it yourself.

2021-03-06 09:54 UTC, richard67 commented
@thednp See also:
- https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-merge-conflicts
- https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github
- https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

2021-03-06 10:27 UTC, thednp commented
Thanks @richard67 I think I managed.

2021-03-06 10:29 UTC, richard67 commented on administrator/components/com_admin/script.php
> +      '/administrator/templates/atum/scss/vendor/minicolors'
```suggestion
			// Joomla 4.0 Beta 8
			'/administrator/templates/atum/scss/vendor/minicolors'
```
And again the spaces versus tabs thing ;-)

2021-03-06 10:33 UTC, richard67 commented
@thednp Well done. Next conflict of the same kind will come when PR #31838 will be merged before this one. Then you can just solve it in the same way.

2021-03-06 11:26 UTC, richard67 commented on administrator/components/com_admin/script.php
> +			'/templates/cassiopeia/scss/vendor/_minicolors.scss'
```suggestion
			'/templates/cassiopeia/scss/vendor/_minicolors.scss',
```
You have to add back the commas at the end of the last array element. We do that because PHP allows it and it makes maintenance of the array easier, i.e. if people add new stuff to the end, they don't have to add a comma to the last line before that place.

2021-03-06 11:26 UTC, richard67 commented on administrator/components/com_admin/script.php
> +			'/administrator/templates/atum/scss/vendor/minicolors'
```suggestion
			'/administrator/templates/atum/scss/vendor/minicolors',
```
You have to add back the commas at the end of the last array element. We do that because PHP allows it and it makes maintenance of the array easier, i.e. if people add new stuff to the end, they don't have to add a comma to the last line before that place.

2021-03-06 11:35 UTC, dgrammatiko commented
> I've been thinking about integrating $colors into our color picker,

Please don't do that, smaller scripts solving particular problems are more efficient and maintainable than monolithic cover all cases scripts. Obviously, the Unix philosophy is proven to be the best one (small apps that do 1 thing ONLY) against the Windows philosophy one script that does gazzilion of things.

2021-03-06 11:41 UTC, dgrammatiko requested changes

2021-03-06 11:41 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +    if (window.TinyColor || document.readyState === 'complete') {
Please replace the content of connectedCallback() with just `this.doConnect();`. 
Reasons:
- window.TinyColor is already loaded in the import, if not the script won;t execute
- the DOMContentLoaded is covered by the `type=module`

2021-03-06 11:57 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +    if (window.TinyColor || document.readyState === 'complete') {
There is a reason for that particular structure. If I do that, it will crash on window resize, that's why I put it there, besides other customElement based fields do that.

2021-03-06 12:00 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +    if (window.TinyColor || document.readyState === 'complete') {
Did you know the slider layout breaks on window resize?

2021-03-06 12:01 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +    if (window.TinyColor || document.readyState === 'complete') {
I will look for a solution to solve your above issue.

2021-03-06 12:29 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
There is no need to do custom events here. All we gotta do is

```js
this.input.dispatchEvent(new Event('change'));
```

With this, it will work with `onchange` like a breeze, in fact I'm on my way to change all this because onchange was missing from the original `advanced` layout.

2021-03-06 12:34 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
The idea is that THE ELEMENT (eg the `<joomla-picker>` fires the event and not some inner input. This is not friendly for the devs as they have to know the internals. The event name still needs to be `change` but the thrower should be the custom element, not something internal (eg a hidden input)

2021-03-06 15:33 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
Yes, I confirm `this.dispatchEvent(new Event('change'));` works, I don't know how the `onchange` gets its value since `<color-picker>` isn't having one, probably from its internal input.

2021-03-06 15:56 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
Correction: `this` does have a value.

2021-03-07 06:15 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
I don't think dispatching the change event on the `<color-picker>` element is a good idea and let me explain why: I'm implementing the color picker with `onchange` and I need access to the ID of the form field, which is carried by 

```markup
<joomla-field-color-picker>
  #shadowRoot
  <input type="hidden" id="field_ID" value="#000"> <--- `this.input` in joomla-field-color-picker.js
</joomla-field-color-picker>
```

..which is also the input with the value that gets saved to the db. This is where we disconnect, because the `<joomla-field-fancy-select>` is also doing it right, which by the way has a similar structure:

```markup
<joomla-field-fancy-select>
  <select id="field_ID"></select> <--- `this.select` in joomla-field-fancy-select.js
</joomla-field-fancy-select>
```

So I have this color field:

```markup
<field 
      name="fill"
      type="Color"
      control="advanced"
      label="Background Fill"
      format="rgb"
      default="rgb(0, 102, 153)"
      onchange="doMyThing(this)" <-- this must never be <color-picker>, see below
/>
```

Now the `doMyThing(input)` function checks the id & tagname to determine a very specific case, because color picker will trigger a ton of `change`, we don't want to break anything.

```javascript
function doMyThing(input){
  if (input.tagName === 'INPUT' && input.id === 'myID') {
    // find some use for input.value
    // don't crash my app because we're in the right context
  }
```

So what you suggest is in fact producing more confusion to the developer, who will expect a similar design with fancy-select, which is out there already. To be able to handle what you suggest, I will have to add the fieldID to the `<color-picker>` which is only a wrapper for the real form field we need to interact with, but won't make sense to have two elements with the same ID, would it?

@brianteeman ?

2021-03-07 08:07 UTC, brianteeman commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
There is no need to tag me.

2021-03-07 09:10 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +    if (window.TinyColor || document.readyState === 'complete') {
You are correct, the `if (this.color)` check inside `doConnect()` will make sure the script won't crash on `resize` or `onDisconnectedCallback`. Thanks

2021-03-07 09:11 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
So?

2021-03-07 09:47 UTC, thednp commented
With that last commit and last update to the PR info, this baby is ready to test and hopefully RTC next week.

Have a good one.

2021-03-07 11:05 UTC, dgrammatiko commented
I'm unsubscribing here, as all my comments are ignored

2021-03-07 11:20 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
So you ARE DOING IT VERY WRONG! The id needs to be on the web component the hidden input doesn't need an ID. The reason that you're way wrong here is that web components will BE part of a form in the near future (the PR in the platform is named`attachInternals`) so in that case you will have a mess that will be impossible to fix WITHOUT B/C breaks. When others tell you to do something in a particular way probably is better to ask why instead of trying to be clever and insist on your approach.  Ref https://web.dev/more-capable-form-controls/

2021-03-07 12:45 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
Sorry was away. 

So why didn't you say so in the first place? I didn't know that, really. I only considered what works for me in my setup, I didn't expect there is a much broader scope. This means all web components will get a rework then. 

OK Let me try that first before anything.

You don't have to unsubscribe, you're a co-author.

2021-03-07 13:17 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
@dgrammatiko 

I just tested without `<input type="hidden">` the value won't be saved in the database. I'm working on attaching additional methods mentioned in the page you linked.

2021-03-07 13:19 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
I NEVER said remove the hidden input, I said remove the ID from the hidden input

2021-03-07 13:22 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
Ok, please calm down and lay out a plan.  Try and stick to it.

2021-03-07 13:30 UTC, dgrammatiko commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
Dude, I proposed you something many days before https://github.com/joomla/joomla-cms/issues/32494#issuecomment-784294659, you gloriously ignored it, you did your own thing which IS TOTALLY WORNG but you still somehow I still have to help you get out of your own mess. Not very productive if I just wasting my time commenting on something that will be essentially ignored

2021-03-07 13:37 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
Sorry man, was NOT intended. I just forgot, got busy with something else, really.

2021-03-07 13:41 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
I will implement that and let you know once ready.

2021-03-08 06:24 UTC, thednp commented on build/media_source/system/js/fields/joomla-field-color-picker.es6.js
> +  dispatchCustomEvent(eventName) {
OK now. You can have a look.

2021-03-10 18:50 UTC, dgrammatiko commented
@thednp since the other PR was merged please do the following changes here:
- rename the file to `build/media_source/system/js/fields/joomla-field-color-picker.w-c.es6.js`
- copy the contents of the `<style>` to a new file `build/media_source/system/scss/fields/joomla-field-color-picker.scss`
- replace the `<style>` tag with `<style>{{CSS_CONTENTS_PLACEHOLDER}}</style>`


The content of the new file `build/media_source/system/scss/fields/joomla-field-color-picker.scss` should be:
```css
:host {
   position: relative;
   display: flex
 }
 .color-dropdown {
   width: 100%;
   max-width: calc(100% - 1rem);
   background: rgba(0,0,0,0.75);
   color: rgba(255,255,255,0.8);
   box-shadow: 0 6px 12px rgba(0, 0, 0, 0.4);
   position: absolute;
   padding: 0.5rem;
   border-radius: 0.5rem;
   display: none;
   left:0;
   z-index: 50
 }
 .color-dropdown.show {
   top: calc(100% + 5px);
   display: block
 }
 .color-dropdown.show-top {
   bottom: calc(100% + 5px);
   display: block;
   top: auto
 }
 .color-controls {
   display: none;
   flex-wrap: wrap;
   justify-content: space-between;  
 }
 .color-preview {
   border: 0;
   outline: none;
   box-shadow: 0 0 1px 1px rgba(120,120,120,0.33) inset;
   line-height: 1.5;
   font-size: 1rem;
   border-radius: 0.25rem;
   appearance: none;
   width: 100%;
   height: 1.5rem;
   padding: 0.6rem 1rem;
   direction: ltr; /* color value can never be rtl */
 }
 .color-preview.dark {
   color: rgba(255,255,255,0.8);
 }
 .color-preview.dark::placeholder {
   color: rgba(255,255,255,0.6);
 }
 .color-preview.light {
   color: rgba(0,0,0,0.8);
 }
 .color-preview.light::placeholder {
   color: rgba(0,0,0,0.6);
 }
 .menu-toggle {
   position: absolute;
   height: 100%; width: 3rem;
   top: 0; right: 0;
   background: none;
   display: flex;
   border: 0;
   outline: none;
   border-radius: 0 .25rem .25rem 0;
   transition: all 0.33s ease;
   cursor: pointer
 }
 .color-preview.light + .menu-toggle {
   background: rgba(0,0,0,0.5);
 }
 .color-preview.dark + .menu-toggle {
   background: rgba(255,255,255,0.33);
 }
 .menu-toggle svg {
   width: auto;
   height: 100%
 }
 .color-menu {
   list-style: none;
   padding-inline: 0;
   margin: 0;
   flex-wrap: wrap;
   flex-flow: column;
   display: none;
   max-height: 160px;
   overflow-y: auto
 }
 .color-menu::-webkit-scrollbar {
   width: 10px;
 }
 .color-menu::-webkit-scrollbar-track {
   background-color: transparent;
 }
 .color-menu::-webkit-scrollbar-thumb {
   background-color: transparent;
   border-radius: 10px;
   border: 0;
   background-clip: content-box;
 }
 .color-menu:hover::-webkit-scrollbar-thumb {
   background-color: rgba(255,255,255,0.2);
 }
 .color-menu::-webkit-scrollbar-thumb:hover {
   background-color: #fff;
 }
 .color-dropdown.menu .color-menu,
 .color-dropdown.picker .color-controls {
   display: flex
 }
 li {
   padding: 0.25rem 0.5rem;
   cursor: pointer
 }
 li:hover {
   background: #fff;
   color: #000
 }
 .color-form {
   font: 12px Arial;
   display: flex;
   flex-wrap: wrap;
   flex-direction: inherit;
   width: 100%;
   align-items: center;
   padding: 0.25rem 0
 }
 .color-form > * {
   flex: 1 0 0%;
   max-width: 17.5%;
   width: 17.5%
 }
 .color-form label {
   text-align: center;
   max-width: 7.5%;
   width: 7.5%
 }
 label.hex-label {
   max-width: 12.5%;
   width: 12.5%
 }
 input.color-input-hex {
   max-width: 87.5%;
   width: 87.5%
 }
 .color-input {
   background: transparent;
   border: 1px solid rgba(255,255,255,0.15);
   text-align: right;
   outline: none;
   color: inherit
 }
 .color-input:active,
 .color-input:focus {
   background: rgba(0,0,0,0.25);
   border: 1px solid rgba(255,255,255,0.33);
 }
 .color-control1 {
   cursor: crosshair;
 }
 .color-control2,
 .color-control3 {
   cursor: ns-resize;
 }
 .color-control {
   position:relative;
   display: inline-block
 }
 .color-control:focus canvas:active {
   cursor: none;
 }
 .color-pointer,
 .color-slider {
   position:absolute;
   background: #000;
   border: 1px solid #fff;
   height: 5px;
   cursor: inherit;
   user-select: none;
   pointer-events: none
 }
 .color-pointer {
   width: 5px;
   border-radius: 5px
 }
 .color-slider {
   left: 0;
   width: calc(100% - 2px);
 }
 .visually-hidden { display: none }
 :host([dir="rtl"]) .color-preview { text-align: right }
 :host([dir="rtl"]) .menu-toggle {
   right: auto;
   left: 0
 }
 :host([dir="rtl"]) .menu-toggle {
   border-radius: .25rem 0 0 .25rem;
 }
```

The tools will do the rest.

2021-03-10 18:57 UTC, thednp commented
Sweet. Thanks @dgrammatiko I'm going to update my local repo, I have some accessibility updates for the color-picker.

Congrats on a well done job.

2021-03-10 19:37 UTC, thednp commented
@dgrammatiko is there a `--fix` option for CSS lint?

2021-03-10 19:40 UTC, dgrammatiko commented
try `stylelint --config build/.stylelintrc.json -s scss "build/media_source/**/*.scss" --fix` (although I have no clue if stylelint supports it)

2021-03-10 19:49 UTC, thednp commented
Thanks man, check back in a couple minutes.

2021-03-10 20:38 UTC, thednp commented
@dgrammatiko for some reason the js is loaded, looks good, but it doesn't work.

2021-03-10 20:41 UTC, thednp commented
Ah it's a module, forgot to change that.

2021-03-10 20:51 UTC, dgrammatiko commented
The joomla.asset.json should look like: 

```json
  {
       "name": "field.color-picker-es5",
       "type": "script",
       "uri": "system/fields/joomla-field-color-picker-es5.min.js",
       "attributes": {
         "nomodule": true,
         "defer": true
       },
       "dependencies": [
         "wcpolyfill"
       ]
     },
  {
       "name": "field.color-picker",
       "type": "script",
       "uri": "system/fields/joomla-field-color-picker.min.js",
       "attributes": {
         "type": "module"
       },
       "dependencies": [
         "field.color-picker-es5"
       ]
     },
```

Check some other field

2021-03-11 05:32 UTC, thednp commented
@dgrammatiko now that we're "done" would you care to provide some feedback on how it actually works as implemented as well as for the documentation draft I posted.

I'm interested to know your take on how the dropdown is resizing to full width, IMO, it's great to have all the accuracy possible, but on wide screens with one column options page it looks a bit silly.

@Fedik this thing is ready for you.

2021-03-13 07:40 UTC, thednp commented
Which color-picker is this?

![cp](https://user-images.githubusercontent.com/6761246/111023163-5ad04680-83cf-11eb-88f6-ed4807ea57b6.png)

2021-03-15 16:33 UTC, thednp commented
@richard67 sorry to bother, we have a conflict here which I'm not sure I can 100% manage.

Also guys, is there any chance we can get this to next J4.0 beta release please?

2021-03-15 16:44 UTC, rdeutz commented
> Also guys, is there any chance we can get this to next J4.0 beta release please?

I don't think this will make it into 4.0, but finally it is not my decision

2021-03-15 16:46 UTC, richard67 commented
> @richard67 sorry to bother, we have a conflict here which I'm not sure I can 100% manage.

Too much even for me now. @dgrammatiko can you advise what he shall do with his package-lock.json?

> Also guys, is there any chance we can get this to next J4.0 beta release please?

@rdeutz Is this here a new feature so it has to be moved to 4.1?

2021-03-15 16:48 UTC, thednp commented
@rdeutz this isn't a new feature per say, it's a replacement for minicolors.

2021-03-15 16:50 UTC, dgrammatiko commented
@thednp probably this is a naive way of solving the conflict but try copying the contents of `package-lock.json` from the 4.0-dev repo into your local file, then run `npm install` so the file gets the updates for the resources you added. Then push that and hopefully, everything will be in-sync again. btw this is not the proper way to deal with conflicts...

2021-03-15 17:39 UTC, thednp commented
Conflict solved. Guys what do we need to get this through?

2021-03-15 17:45 UTC, richard67 commented
@thednp Why are you asking if you know the answer? A PR needs at least 2 successful tests before it can be RTC.

2021-03-15 18:00 UTC, thednp commented
@richard67 because nobody is testing, providing any feedback, like people think this is WIP/draft or are undecided if we push it to 4.0 or 4.1. Maybe people think this needs more polish. I don't know anything.

2021-03-15 21:45 UTC, brianteeman commented
please fix code style here with the indentions

![image](https://user-images.githubusercontent.com/1296369/111225401-ac4b2200-85d7-11eb-93be-761b5be51e02.png)

2021-03-15 21:48 UTC, brianteeman commented
Copyright and license

I note that there is neither of these in the main js file. The only thing is a reference to two codepens both of which are MIT licenced

2021-03-15 22:05 UTC, brianteeman commented
This is a really unusual UI - not sure its intuitive at all

![color](https://user-images.githubusercontent.com/1296369/111227469-84a98900-85da-11eb-8f94-8b544ec75a68.gif)

2021-03-15 22:14 UTC, brianteeman commented
From an accessibility perspective this is worse than the field it is replacing.

The screenreader does not announce the field label. 
The screenreader does not announce the (crazyUI) dropdown menu

All you hear is the "#f66e55# which is meaningless

2021-03-15 22:15 UTC, brianteeman commented
This is invalid markup. You are creating a list but you have no list items

![image](https://user-images.githubusercontent.com/1296369/111228295-e0c0dd00-85db-11eb-90a9-fcd382dc052e.png)

2021-03-15 22:20 UTC, brianteeman commented
What are inputlabels and inputlabel? I dont recognise these attributes or see where they are used

![image](https://user-images.githubusercontent.com/1296369/111228757-a572de00-85dc-11eb-8ded-7cd4807bc835.png)

2021-03-15 22:34 UTC, brianteeman commented
ah - i see what they are for now. unfortunately they do not work

![image](https://user-images.githubusercontent.com/1296369/111229876-9b51df00-85de-11eb-8af7-99841168cc14.png)

2021-03-15 22:41 UTC, brianteeman commented
All the above comments were for the advance (default) layout

2021-03-15 22:41 UTC, brianteeman commented
Testing the simple layout now.
Thankfully this is fairly accessible.

But do you really think that it is obvious what to do here
![image](https://user-images.githubusercontent.com/1296369/111230512-a35e4e80-85df-11eb-9fcb-3db6f8a0bdb0.png)

2021-03-15 22:55 UTC, brianteeman commented
Something wrong with the close button as shown below

![image](https://user-images.githubusercontent.com/1296369/111231622-81fe6200-85e1-11eb-9c12-6c61d80477e0.png)

2021-03-15 22:56 UTC, dgrammatiko commented
Brian the simple layout was done by me and you some years ago, it’s not part of this pr😉

2021-03-15 22:59 UTC, brianteeman commented
@dgrammatiko yes I was just about to type that this was not part of this PR - wasnt obvious until I dug into the code. The example documentation gave e the wrong impression. PS where did we define which colours were used in that

2021-03-15 23:03 UTC, dgrammatiko commented
There should be an attribute in the xml and should be on the docs (we just rewrote the code to be a11y)

2021-03-15 23:05 UTC, brianteeman commented
I will dig into that tomorrow and create a new issue so as not to pollute this one. There are enough issues with this advanced picker

2021-03-16 05:17 UTC, thednp commented
Finally! Thanks.

@brianteeman `inputLabel` was used in a previous version for the visible input inside the ShadowRoot, I will bring it back.

> 
> 
> There should be an attribute in the xml and should be on the docs (we just rewrote the code to be a11y)

@dgrammatiko to which attribute you are referring to?

I will update the code base and make all adjustments today.

2021-03-16 08:08 UTC, dgrammatiko commented
It s named colors https://github.com/joomla/joomla-cms/blob/3b82bf129322cf473f10a1856d4ec385895ff1ad/libraries/src/Form/Field/ColorField.php#L324

2021-03-16 08:16 UTC, thednp commented
Which is something we discussed not to include in the advanced layout.

2021-03-16 08:41 UTC, thednp commented
Brian, I have no idea why the screen readers won't read the visually-hidden labels, I'm thinking its because we're not using [delegatesFocus](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus), (which is not supported on Safari).

```markup
<label for="rgb_color_red">R: <span class="visually-hidden">RGB colour format - Red component</span></label>
<input id="rgb_color_red" name="rgb_color_red" value="0" type="number" placeholder="[0-255]" min="0" max="255">
```

I have to admit accessibility isn't my sharpest blade, I'm open to your accessibility team suggestions. I'm investigating all other options meanwhile.

2021-03-16 09:19 UTC, brianteeman commented
I am not on the accessibility team.

There are lots of articles online about the issues with accessibility and the shadow dom

2021-03-16 09:24 UTC, thednp commented
Yes, it seems our component will require additional Language strings.

2021-03-16 09:41 UTC, brianteeman commented
It needs a lot of work

2021-03-16 11:33 UTC, thednp commented
Eh I was using the incorrect `visually-hidden` style. Now the screen reader will read everything.

I only have to handle the placeholders and other non-form elements.

2021-03-17 06:12 UTC, thednp commented
Listening to the screen reader trying to pronounce `hsla` or `rgba` is hilarious. I'm going to feed it a custom `aria-label` for almost every visible element of the color picker. According to my research on a general [WAI-ARIA](https://www.w3.org/WAI/tutorials/forms/) guideline, it will go like this:

* The `<joomla-field-color-picker>` element will use `aria-labelledby` -> the field label and `aria-describedby` -> the field description
* The visible input will use a special set of aria attributes inspired by [Radial Color Picker](https://radial-color-picker.github.io/vue-color-picker/examples.html#accessibility) as well as `aria-expanded`
* While for controls like Alpha or (HSL) - Saturation we could normally use an `<input type="slider">`, we don't have anything for the first control, where we would need a 2D slider which doesn't exist yet. So the canvas elements will have an `aria-label` each, as follows: `Lightness and Saturation Control`, `Hue Control` for HEX + `Alpha Control` for RGB(a) OR `Hue and Lightness Control`, `Saturation Control` and `Alpha Control` for HSL(a) format, good enough to understand that they serve as a graphical representation of the colour's properties (hue, lightness, etc) .
* the button toggling the `$keywords` menu will have an `aria-labelledby` -> span.id -> `Colour presets` and `aria-expanded` -> true/false
* the `$keywords` menu itself will be separate, will no longer share same wrapper with the color picker and will use its own set of aria attributes.
* As for the other inputs of the color picker, the `aria-hidden` and the fixed `visually-hidden` will do the job.

Click LIKE if you agree.

2021-03-17 08:15 UTC, thednp commented
Alright Brian, what would you like to object?

2021-03-17 09:04 UTC, brianteeman commented
> Listening to the screen reader trying to pronounce `hsla` or `rgba` is hilarious. 

That is not for a non-screen reader user to decide. Every screen reader is different.


> I'm going to feed it a custom `aria-label` for almost every visible element of the color picker. According to my research on a general [WAI-ARIA](https://www.w3.org/WAI/tutorials/forms/) guideline, it will go like this:

[The first rule of Aria is not to use Aria.](https://www.google.com/search?q=first+rule%20of%20aria)

> 
> * The `<joomla-field-color-picker>` element will use `aria-labelledby` -> the field label and `aria-describedby` -> the field description

There is no field description currently so there is no need for the aria-describedby

> * The visible input will use a special set of aria attributes inspired by [Radial Color Picker](https://radial-color-picker.github.io/vue-color-picker/examples.html#accessibility) as well as `aria-expanded`

That might appear to be good but as it announces the same colour name for a wide range of colours it is not helpful at all. For example you would never be able to be sure you have the correct green

> * While for controls like Alpha or (HSL) - Saturation we could normally use an `<input type="slider">`, we don't have anything for the first control, where we would need a 2D slider which doesn't exist yet. So the canvas elements will have an `aria-label` each, as follows: `Lightness and Saturation Control`, `Hue Control` for HEX + `Alpha Control` for RGB(a) OR `Hue and Lightness Control`, `Saturation Control` and `Alpha Control` for HSL(a) format, good enough to understand that they serve as a graphical representation of the colour's properties (hue, lightness, etc) .
> * the button toggling the `$keywords` menu will have an `aria-labelledby` -> span.id -> `Colour presets` and `aria-expanded` -> true/false
> * the `$keywords` menu itself will be separate, will no longer share same wrapper with the color picker and will use its own set of aria attributes.
> * As for the other inputs of the color picker, the `aria-hidden` and the fixed `visually-hidden` will do the job.

fixed??

> 
> Click LIKE if you agree.

2021-03-17 09:28 UTC, thednp commented
Brian, don't worry about it. The final version will be 100% accessibility valid. Now back to work.

2021-03-17 09:30 UTC, brianteeman commented
So why waste my time asking for an opinion 😠

2021-03-17 09:34 UTC, thednp commented
Your feedback provides clarity and confirmation for my development plan and I thank you.

2021-03-18 13:05 UTC, thednp commented
@dgrammatiko quick question: can I send the color-picker attribute values with JSON data for strings? Or via JavaScript options?

My current comma separated strings just won't do.

2021-03-18 13:09 UTC, dgrammatiko commented
I don't really understand the question but in general custom elements get their inputs from attributes and in general attributes are strings. You could expect JSON but there need to be checks and fallbacks

2021-03-18 13:11 UTC, thednp commented
For instance, currently we have

```php
	$inputLabels = Text::_('JFIELD_COLOR_ADVANCED_FORMAT_HSL_HUE_INPUT_LABEL');
	$inputLabels .= ',' . Text::_('JFIELD_COLOR_ADVANCED_FORMAT_HSL_SATURATION_INPUT_LABEL');
	$inputLabels .= ',' . Text::_('JFIELD_COLOR_ADVANCED_FORMAT_HSL_LIGHTNESS_INPUT_LABEL');
	$inputLabels .= ',' . Text::_('JFIELD_COLOR_ADVANCED_ALPHA_INPUT_LABEL');
```

I want to make an array and add it to the attributes list as `json_decode($that_array)`.

2021-03-18 13:12 UTC, thednp commented
Or more like `$this->escape(json_decode($that_array))`.

2021-03-18 13:15 UTC, dgrammatiko commented
> Is this allowed?

Technically yes but it's a really bad implementation, use the attributes and have a setter/getter

2021-03-18 13:19 UTC, dgrammatiko commented
btw I just checked your template inside the web component and realised that the label of the color field is not in there. That will never work, either include the label in the webomponent (shadow root) or use a custom element (no shadow root)

2021-03-18 13:26 UTC, thednp commented
In my local WIP version I already took care of that since Brian exploded with feedback.

2021-03-18 13:29 UTC, dgrammatiko commented
> In my local WIP version I already took care of that since Brian exploded with feedback.

The expected behaviour of a label is: on click it should focus the input element. Since `joomla-color` is not a field (according to form children) this is broken and unfixable unless if the label is part of shadow root or the custom element doesn't have shadow dom so the linking between label and input is not broken

2021-03-18 13:31 UTC, thednp commented
That behavior is already "handled" if you check the current version online (equivalent with the one in my fork repo) https://codepen.io/thednp/pen/yLVzZzW

2021-03-18 23:19 UTC, thednp commented
![image](https://user-images.githubusercontent.com/6761246/111708940-aacf6300-883e-11eb-9161-c9975381e965.png)

The following is a sample markup of the new color-picker version

```html
<joomla-field-color-picker name="jform[params][advanced-color-rgb]" id="jform_params_advanced_color_rgb" value="rgb(49, 49, 173)" class="required dark open" format="rgb" required="" autocomplete="off" alphalabel="Alpha" hexlabel="Hexadecimal" redlabel="Red" greenlabel="Green" bluelabel="Blue" huelabel="Hue" saturationlabel="Saturation" lightnesslabel="Lightness" formatlabel="RGB format" redinputlabel="Set Red level" greeninputlabel="Set Green level" blueinputlabel="Set Blue level" control1label="The Saturation and the Lightness of the current colour." control2label="The Hue of the current colour." alphainputlabel="Set Alpha level" control3label="The alpha transparency of the current colour." togglelabel="Colour presets" menulabel="Choose colour preset:" inputlabel="Set a colour by typing a value or by using the color picker" dialoglabel="Color Picker" keywords="navy,lime,crimson,chocolate" spellcheck="1" tabindex="0" role="button" aria-expanded="true" aria-haspopup="true" aria-labelledby="jform_params_advanced_color_rgb-lbl">

<SHADOWROOT>
<label for="color-input" class="visually-hidden">Set a colour by typing a value or by using the color picker</label>
<input id="color-input" name="color-input" type="text" class="color-preview" autocomplete="off" spellcheck="false" required="true" style="background-color: rgb(49, 49, 173);">
<div class="color-dropdown picker show" role="dialog" aria-labelledby="dialog-label format-label">
  <label id="dialog-label" class="visually-hidden">Color Picker</label>
  <span id="format-label" class="visually-hidden">RGB format</span>
  <div class="color-controls">
    <div class="color-control">
  <canvas class="color-control1" height="230" width="373" role="presentation" aria-label="The Saturation and the Lightness of the current colour." tabindex="-1"></canvas>
  <label id="control1-lbl" class="visually-hidden">Red Green &amp; Blue</label>
  <div class="color-pointer" role="slider" aria-labelledby="control1-lbl" tabindex="0" aria-live="polite" aria-valuetext="Red 49, Green 49 &amp;amp; Blue 173" style="transform: translate3d(264.353px, 70.9608px, 0px);"></div>
</div>
<div class="color-control">
  <canvas class="color-control2" height="230" width="21" role="presentation" aria-label="The Hue of the current colour." tabindex="-1"></canvas>
  <label id="control2-lbl" class="visually-hidden">Hue</label>
  <div class="color-slider" role="slider" aria-labelledby="control2-lbl" tabindex="0" aria-live="polite" aria-valuetext="240°" style="transform: translate3d(0px, 150.333px, 0px);"></div>
</div>
<div class="color-control">
  <canvas class="color-control3" height="230" width="21" role="presentation" aria-label="The alpha transparency of the current colour." tabindex="-1"></canvas>
  <label id="control3-lbl" class="visually-hidden">Alpha</label>
  <div class="color-slider" role="slider" aria-labelledby="control3-lbl" tabindex="0" aria-live="polite" aria-valuetext="100%" style="transform: translate3d(0px, -3px, 0px);"></div>
</div>
  </div>
  <div class="color-form">
    <label for="rgb_color_red"><span aria-hidden="true">R:</span><span class="visually-hidden">Set Red level</span></label>
<input id="rgb_color_red" name="rgb_color_red" value="0" class="color-input" type="number" min="0" max="255" autocomplete="off" spellcheck="false">

<label for="rgb_color_green"><span aria-hidden="true">G:</span><span class="visually-hidden">Set Green level</span></label>
<input id="rgb_color_green" name="rgb_color_green" value="0" class="color-input" type="number" min="0" max="255" autocomplete="off" spellcheck="false">

<label for="rgb_color_blue"><span aria-hidden="true">B:</span><span class="visually-hidden">Set Blue level</span></label>
<input id="rgb_color_blue" name="rgb_color_blue" value="0" class="color-input" type="number" min="0" max="255" autocomplete="off" spellcheck="false">

<label for="rgb_color_alpha"><span aria-hidden="true">A:</span><span class="visually-hidden">Set Alpha level</span></label>
<input id="rgb_color_alpha" name="rgb_color_alpha" value="1" class="color-input" type="number" min="0" max="1" step="0.01" autocomplete="off" spellcheck="false">
  </div>
</div>

<button id="presets-btn" class="menu-toggle" aria-labelledby="presets-btn-label" aria-expanded="false" aria-haspopup="true">
  <span id="presets-btn-label" class="visually-hidden">Colour presets</span>
</button>
<div class="color-dropdown menu">
  <span id="presets-label" class="visually-hidden">Choose colour preset:</span>
  <ul aria-labelledby="presets-label" class="color-menu" role="listbox">
    <li role="option" tabindex="0" value="navy">navy</li>
    <li role="option" tabindex="0" value="lime">lime</li>
  </ul>
</div>
</SHADOWROOT>
	<input type="hidden">
</joomla-field-color-picker>
```

Will commit changes tomorrow, feel free to comment.

2021-03-18 23:29 UTC, brianteeman commented
> Will commit changes tomorrow, feel free to comment.

Can't comment until you do ;)

2021-03-20 22:05 UTC, brianteeman commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  top: 0; right: 0;
```suggestion
  top: 0; 
  right: 0;

```

2021-03-20 22:05 UTC, thednp commented
There you go. Have fun :)

2021-03-20 22:06 UTC, brianteeman commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  font: 12px Arial;
Arial ??

2021-03-20 22:06 UTC, thednp commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  font: 12px Arial;
What's the problem with that?

2021-03-20 22:09 UTC, brianteeman commented on layouts/joomla/form/field/color/advanced.php
> +
Please fix the code indention
![image](https://user-images.githubusercontent.com/1296369/111886859-f150c900-89c8-11eb-997b-2ad67d2b943c.png)

2021-03-20 22:11 UTC, brianteeman commented on layouts/joomla/form/field/color/advanced.php
> +$wa->->useScript('field.color-picker');
```suggestion
$wa->useScript('field.color-picker');
```

2021-03-20 22:14 UTC, brianteeman commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  font: 12px Arial;
not available on all computers and no fallback defined

2021-03-20 22:17 UTC, thednp commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  font: 12px Arial;
Arial is most readable at 12px. I consider this a non-issue.

2021-03-20 22:19 UTC, richard67 commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  font: 12px Arial;
As Brian correctly mentioned, Arial is not available on all computers, and you don't provide a fallback. That has nothing to do with readability at 12 px.

2021-03-20 22:20 UTC, thednp commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  font: 12px Arial;
Ok, "12px sans" works?

2021-03-20 22:21 UTC, thednp commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  font: 12px Arial;
"12px sans-serif"

2021-03-20 22:55 UTC, brianteeman commented
Still not accessible to keyboard users using a screen reader. For example a button must be able to be activated using both the space bar and the enter key. So you can't even find out what the already selected colour is

2021-03-20 22:56 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on 0e7cc53e80475c1e1f15021cf89f36fc9a882673<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32510">issues.joomla.org/tracker/joomla-cms/32510</a>.</sub>

2021-03-20 22:59 UTC, thednp commented
Is that the only problem?

2021-03-20 23:16 UTC, brianteeman commented
I doubt it is an easy fix but good luck

2021-03-21 20:16 UTC, thednp commented
That was so easy fix, I took some time for polish.

2021-03-21 20:24 UTC, brianteeman commented on build/media_source/system/scss/fields/joomla-field-color-picker.scss
> +  top: 0; right: 0;
you've marked it as resolved but not changed dit

2021-03-21 23:28 UTC, brianteeman commented
Using a keyboard how are you expected to select an item in the dropdown menu

Sorry but this is full of accessibility errors. I'm afraid I just dont have the time or patience to test this any further. Perhaps @chmst will be able to help. 

Turn on a screen reader and listen as you tab around both this picker and the previous one in the admin template style page

For example the previous one will will immediately announce "Dark Text and then the color"
This one  only announces "Dark Text, menu item, collapsed"

2021-03-21 23:33 UTC, brianteeman commented
for a keyboard user its also about 8 key presses to move to the next field

2021-03-22 05:26 UTC, thednp commented
Brian, these things are little fixes, far from "full of accessibility problems". My most concern is the fact that until the script satisfies all accessibility, which it will, in a matter of minutes thanks to your feedback, I will have to deal with the conflicting `package-lock.json` again, over and over.

2021-03-22 07:56 UTC, brianteeman commented
> This form field layout uses shadowRoot. for which every property and functionality has to be coded to behave like a form field.

Just one of the many reasons that this approach is non sustainable (if you ever test it before asking others to)

2021-03-22 10:09 UTC, brianteeman commented
>My most concern is the fact that until the script satisfies all accessibility, which it will, in a matter of minutes thanks to your feedback, I will have to deal with the conflicting package-lock.json again, over and over. I don't afford that time.

Retested. Issues reported are not resolved.

2021-03-22 10:13 UTC, thednp commented
Sorry Brian, I haven't completed the requests you made yet, the above commits were about solving the `package-lock.json` conflict.

I will let you know when I'm done, thanks for sticking to it.

2021-03-22 11:36 UTC, thednp commented
Brian, some notes:
* you can now navigate between fields freely without getting inside the shadowRoot elements, but if you open the colorPicker, you will go there first;
* the field label now has a human understandable label, the screen readers will read exactly what is what, all translatable.
* We need someone to fix the `package-lock.json` file according to my version of the `package.json` which was updated this morning; perhaps @richard67 can lay a hand here I hope.

2021-03-22 12:05 UTC, thednp commented
Brian, please check the above, and also: should I attempt to fix the `package-lock.json` again? There seem to be some more changes.

2021-03-22 12:24 UTC, richard67 commented
@thednp Your PR deletes the packages lock, and that's definitely not the right way:

![2021-03-22_01](https://user-images.githubusercontent.com/7413183/111989349-ef465180-8b11-11eb-928b-dc22683e3959.png)

Please revert that deletion before you try to solve it.

2021-03-22 12:26 UTC, thednp commented
Should I add a 4.0-dev version there?

2021-03-22 12:27 UTC, richard67 commented
revert the deletions by using revert this commit

2021-03-22 12:36 UTC, thednp commented
Cannot do that, will attempt to add mine again.

2021-03-22 12:42 UTC, thednp commented
Brian, build ready to test.

2021-03-22 14:39 UTC, richard67 commented
@thednp These should be alphabetically sorted:

https://github.com/joomla/joomla-cms/pull/32510/files#diff-db7eb77540ff419bd7e6557d2779f4cf1e31158c20cb4b63dbbe8d6c426385adR5051-R5055

I.e. wrong sorted

```
			// Joomla 4.0 Beta 8
			'/administrator/templates/atum/scss/vendor/minicolors/minicolors.scss',
			'/templates/cassiopeia/scss/vendor/_minicolors.scss',
			'/administrator/components/com_admin/postinstall/htaccess.php',
			'/administrator/components/com_admin/postinstall/updatedefaultsettings.php',
```

should be changed to

```
			// Joomla 4.0 Beta 8
			'/administrator/components/com_admin/postinstall/htaccess.php',
			'/administrator/components/com_admin/postinstall/updatedefaultsettings.php',
			'/administrator/templates/atum/scss/vendor/minicolors/minicolors.scss',
			'/templates/cassiopeia/scss/vendor/_minicolors.scss',
```

Beside this, please don't ask me for a review if it's related to javascript.

2021-03-22 14:44 UTC, brianteeman commented
> Brian, build ready to test.

It is now not possible to access the color picker using the keyboard. **Please** test your changes before asking others to test

2021-03-22 14:46 UTC, brianteeman commented
https://github.com/joomla/joomla-cms/pull/32510/files#r598165347

You have marked this as resolved but you have not corrected it

2021-03-22 15:47 UTC, thednp commented
Brian, this is a test with #32510 using the keyboard navigation.
* Google Chrome Canary latest
* Windows 10 latest

Can somebody else please confirm this test. @dgrammatiko ?

https://user-images.githubusercontent.com/6761246/112017489-92549680-8b25-11eb-9617-87b9d5ba6acf.mp4

2021-03-22 16:02 UTC, thednp commented
This is using the keyboard to change control sliders:


https://user-images.githubusercontent.com/6761246/112020195-0c861a80-8b28-11eb-84d8-2d3fe179cec6.mp4

2021-03-22 16:16 UTC, thednp commented
You testing with Safari on MAC? It doesn't support `event.which` I will correct that.

2021-03-22 16:55 UTC, thednp commented
Brian, I don't have a MAC or a Safari browser, but I'm sure this build works.

I've updated the testing methodology.

2021-03-22 18:15 UTC, brianteeman commented
I am testing on chrome with windows.

I can see now what the problem is but I'm afraid I have no idea what the fix is. It is almost certainly related to javascript emulating keys instead of using native behaviour.

When you navigate to the input field with your keyboard and press the enter key then the options open - exactly as you showed in your recording.

However when I have a screen reader enabled and I navigate to the same input then no keypress will open the options. I have tested this with both Navigator (built in to windows 10) and NVDA which is probably the most common screen reader for windows users (free and open source from https://www.nvaccess.org/)

2021-03-22 18:21 UTC, thednp commented
If you press ALT+SPACE or ALT+ENTER on the `<joomla-filed-color-picker>` while the NVDA screen reader is active, the dropdown will show up.

2021-03-22 18:35 UTC, brianteeman commented
Thats because you are not changing the mode of the screenreader https://tink.uk/understanding-screen-reader-interaction-modes/

2021-03-22 19:12 UTC, thednp commented
If it's a JavaScript issue, I'm gonna nail it down. If it's a NVDA + customElements issue, we gonna have to find some workaround.

I'm going to do some research maybe I can come up with something.

2021-03-22 19:14 UTC, brianteeman commented
The answer/explanation was in the post I linked to

2021-03-23 08:07 UTC, thednp commented
I've tested other form fields and came to the realization that most of them are an accessibility disaster.
* the fancy select layout, radio buttons, checkboxes, the `simple` and `slider` controls of the `Color` field, probably others too, they don't expose to NVDA **any** field name, you're presented with "Yes, one of two, selected", no context, no aria, no idea what's what and what is for.
* only fields using native `<input type="text">` and `<select>` are working properly as far as I tested.
* everything has to be reworked from an accessibility point of view, all fields need to check to have correct `<label for="field_name">` .

In my little project here, I have some options:
* Since the color-dropdown is already `role="application"` I can just inform the keyboard user to use ALT key to change knobs or ALT + SPACE to open color picker,  makes total sense to a user listening to NVDA instructions because it's an application and properly announced so. This is probably not the best solution, but it would make sense on an ever evolving web.
* I can just replace all interactive elements with `<button>` or `<input type="range">`, `<a>`, it doesn't matter if it's inside the shadowRoot or not, they always work natively with keyboard events.
* I can have the `<joomla-field-color-picker>` element store all values, instance object, event handling & delegation, but only work with a markup outside shadowroot (something that would simplify the styling, a lot of the code base and @dgrammatiko would not approve of this), the focus is that we need to easily multiply the instance for repeatable fields more or less.

I would go for the second option, but time is ticking, I need to know what's your take on it before I go any further.

2021-03-23 11:09 UTC, dgrammatiko commented
> I can have the <joomla-field-color-picker> element store all values, instance object, event handling & delegation, but only work with a markup outside shadowroot (something that would simplify the styling, a lot of the code base and @dgrammatiko would not approve of this), the focus is that we need to easily multiply the instance for repeatable fields more or less.

Didn't I just propose you **to do exactly that** but then you went your own way and doing this weird dropdown?

2021-03-23 11:21 UTC, thednp commented
Probably you did and I didn't understand, you wanted to have the `form.onsubmit` handler for a `hiddenInput` that I forgot about later on, something that won't make sense with markup outside the shadowroot. 

No matter what, I'm going to make it work, I'm still experimenting to find the best there is to improve accessibility.

2021-03-24 12:57 UTC, thednp commented
Brian, this is a demo with keyboard navigation and screen reader turned ON.
* the `<color-picker>` element is no longer a button, there is a native `<button>` to toggle the color picker visibility;
* as of now, screen readers and keyboard navigation do not 100% support control for elements with these attributes `<div role="slider" aria-min="0" aria-max="360" aria-valuetext="360 degrees">` except if you interact with the ALT key, but even then, the narator focus will jump all over the place, so I've disabled the `tabindex` attribute for those elements and the associated keyboard events listeners, however they are still controllable via mouse; this behavior is the same regardless if the elements are inside shadowRoot or not.

https://user-images.githubusercontent.com/6761246/112312975-49285200-8c9f-11eb-9a4d-b374e1cacb1d.mp4

I will prepare the files and commit as soon as I can.

2021-03-24 13:02 UTC, brianteeman commented
> so I've disabled the tabindex attribute for those elements and the associated keyboard events listeners

From my perspective thats a fail

2021-03-24 13:10 UTC, thednp commented
Please explain.

2021-03-24 13:29 UTC, thednp commented
You think I should revert that change? It's easy to put back.

2021-03-24 14:41 UTC, brianteeman commented
> From my research: it's not recommended to detect screen readers or to code around them, 

quite correct.

please remember my comments are just that, my own. If anyone else bothers to test this PR they may have other different views

2021-03-24 15:11 UTC, thednp commented
From your point of view do we need anything else for this PR to get RTC?

2021-03-24 15:59 UTC, thednp commented
Some note from my experience working on this, I tried to replace all possible focusable elements with native elements:
[x] buttons can toggle things, natively, they only need to know what to execute;
[ ] to enable native slider behavior I tried replacing slider knobs with actual sliders but there is no such thing in the current draft to enable double value sliders (vertical + horizontal);
[ ] also about replacing knobs with native sliders, there are multiple concerns against vertical orientation sliders (not standardized across IE, Mozilla, Safari, Chromium), also screen readers won't be able to maintain focus on the thumb;
* not even `<input type="number">` can handle the screen reader focus behavior, which is very strange.

2021-03-24 18:08 UTC, alikon commented
don't get me wrong..
but this pr should be postponed to 4.0.x

2021-03-24 18:15 UTC, brianteeman commented
What was the intention of adding aria-live=offf

As aria-live="off" is the assumed default for elements, it should not be necessary to set this explicitly, unless you're trying to suppress the announcement of elements which have an implicit live region role (such as role="alert").

2021-03-24 18:37 UTC, thednp commented
The idea is that the reader is babbling when you change values, I'm still not 100% sure which methods is best.

2021-03-24 18:44 UTC, brianteeman commented
Then you are definitely wrong and it must be polite

2021-03-24 18:52 UTC, thednp commented
Cool, updating as soon as I get to my PC, thanks.

2021-03-24 19:04 UTC, brianteeman commented
> Thanks Brian.
> 
> From your point of view do we need anything else for this PR to get RTC?

As with all PR it needs at least two good tests. Personally I will not be marking a negative or positive test as I am not convinced it is an improvement on the current code which amongst other things doesnt need a degree in javascript to understand

2021-03-24 19:07 UTC, thednp commented
Fair enough, I thank you for the assist regardless.

2021-03-25 16:32 UTC, thednp commented
Kind reminder: today I've resolved a quick and easy new `package.json` conflict.

Please test, RTC and merge somewhere, I cannot allocate any more time into this.

2021-05-10 12:27 UTC, PhilETaylor commented
This branch has conflicts that must be resolved

Conflicting files
administrator/components/com_admin/script.php
build/media_source/system/scss/_jquery-minicolors.scss
package-lock.json

2021-05-10 12:49 UTC, richard67 commented
I think it should be moved to 4.1.

2021-05-10 14:22 UTC, thednp commented
Yea. Call me when we're at 4.1 RC, I will revise the PR for hopefully last time.

2021-07-02 08:03 UTC, brianteeman commented
This has been tagged milestone 4.0.1
It should be milestone 4.1

2021-09-21 15:21 UTC, thednp commented
I'm closing this down, preparing a new PR. in the 4.1 branch.

2021-09-21 15:21 UTC, closed without merging