Updating all views to use H1 for Component Title when Menu Title hidden
joomla/joomla-cms pull request #32525
Opened 2021-02-26 11:50 UTC by AndySDH

Follow-up Pull Request after #32448

### Summary of Changes

After updating the article view with the above-mentioned PR, this PR updates all the other views as well to show the component title as H1 when the Menu Title is hidden.

In particular this updates the following views:

In addition, when doing this, I stumbled upon an unused page_subheading param that was present in the 'featured' views and the 'category blog' views. This looks to be an outdated and out of place parameter that was present just in those two views and nowhere else.

So this also addresses issue #29586, removing the page_subheading parameter in those views, making them consistent with all the other views as well.

### Actual result BEFORE applying this Pull Request

Components title is H2.

### Expected result AFTER applying this Pull Request

Components title is H1 when Menu Title is hidden.

2021-02-26 11:55 UTC, richard67 commented
@AndySDH So this PR solves that issue #29586 ?

2021-02-26 11:56 UTC, AndySDH commented
Please test @laoneo @bembelimen @brianteeman @simbus82 @Quy
Thanks!

2021-02-26 11:57 UTC, richard67 commented on components/com_tags/src/View/Tag/HtmlView.php
```suggestion
```
Please remove this line, too, so the PHP code style linter is happy: https://ci.joomla.org/joomla/joomla-cms/40397/1/6

2021-02-26 11:58 UTC, AndySDH commented
> Please test @laoneo @bembelimen @brianteeman @simbus82 @Quy
> Thanks!

> @AndySDH So this PR solves that issue #29586 ?

Yeah, addresses that too as explained above :)

2021-02-26 12:00 UTC, richard67 commented
> Yeah, addresses that too as explained above :)

@AndySDH Yes, but to address and to solve it is not 100 % the same thing, so I asked to be sure. Thanks for reporting back, and thanks for your contributions so far, it's really appreciated.

2021-02-26 17:09 UTC, Quy commented on components/com_content/tmpl/featured/default.xml
> -				label="JGLOBAL_SUBHEADING_LABEL"
Delete language strings.

2021-02-26 17:27 UTC, AndySDH commented on components/com_content/tmpl/featured/default.xml
> -				label="JGLOBAL_SUBHEADING_LABEL"
Done, thanks!

2021-02-28 12:10 UTC, himanshu007-creator commented
I have tested this item :white_check_mark: successfully on 970c03dd9ad8416daa13eb57a1f455533236700b<br /><br />I opened the Contact default view. Before applying the patch title was having **h2** tag, after patch, it was **h1**.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32525">issues.joomla.org/tracker/joomla-cms/32525</a>.</sub>

2021-03-01 06:35 UTC, particthistle commented
I have tested this item :red_circle: unsuccessfully on 970c03dd9ad8416daa13eb57a1f455533236700b<br /><br />See next comment and review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32525">issues.joomla.org/tracker/joomla-cms/32525</a>.</sub>

2021-03-01 06:38 UTC, particthistle requested changes
@AndySDH - working through testing all the scenarios (@himanshu007-creator - will chat in Glip about improving the level of detail for your testing) and found a syntax error that breaks the Blog Category Layout when the patch is applied.

Aside from that, all the other scenarios look to have worked correctly, so will be able to retest quickly when this has been fixed up as I've got all the menu items for the different scenarios saved and ready to go.

2021-03-01 06:38 UTC, particthistle commented on components/com_content/tmpl/category/blog.php
> +	<?php if ($this->params->get('show_category_title', 1): ?>
PR breaks for Category Blog page due to missing )

Line should be:

`<?php if ($this->params->get('show_category_title', 1)): ?>`

2021-03-01 09:07 UTC, infograf768 commented
This one also needs changes:

https://github.com/joomla/joomla-cms/blob/90ab8c02dbb9a0763e9b8bb91bfea690cbc1dd44/plugins/sampledata/multilang/multilang.php#L856-L869

would also be modified to include the changes as done in https://github.com/joomla/joomla-cms/pull/32550

2021-03-01 13:30 UTC, AndySDH commented
> @AndySDH - working through testing all the scenarios (@himanshu007-creator - will chat in Glip about improving the level of detail for your testing) and found a syntax error that breaks the Blog Category Layout when the patch is applied.
> 
> Aside from that, all the other scenarios look to have worked correctly, so will be able to retest quickly when this has been fixed up as I've got all the menu items for the different scenarios saved and ready to go.

Whoops, sorry, thanks for reporting this! It's now fixed.

How did the auto-check not automatically spot this?

2021-03-01 13:33 UTC, AndySDH commented on components/com_content/tmpl/category/blog.php
> +	<?php if ($this->params->get('show_category_title', 1): ?>
Fixed, thanks!

2021-03-01 23:10 UTC, particthistle commented
@AndySDH, take a look at @infograf768 suggest change needed for the sample data.

#32550 is being worked on concurrently, but it's taking care of the default install. The Sample Data has the same problem that PR is looking to fix, which is that the sample data has J3 parameters not J4 parameters. Just going to see if I can work out what needs to go in there quickly to speed up the change for you.

Once that's also fixed I'll then retest also with a new install + sample data install.

2021-03-01 23:46 UTC, particthistle requested changes
Changes to match up #32550. Part 1.

2021-03-01 23:46 UTC, particthistle commented on plugins/sampledata/multilang/multilang.php
>  				. '"show_no_articles":"","show_subcat_desc":"","show_cat_num_articles":"","show_cat_tags":"",'
To correct this data in regards to #32550 another parameter needs to be added before num_leading_articles:
Add before line 859:
`. '"blog_class_leading":"","blog_class":"",'`

2021-03-01 23:46 UTC, particthistle commented on plugins/sampledata/multilang/multilang.php
>  				. '"num_links":"0","show_subcategory_content":"","orderby_pri":"",'
Addition for #32550
Line 860 - extra parameter link_intro_image
`. '"num_links":"","show_subcategory_content":"","link_intro_image":"","orderby_pri":"",'`

2021-03-01 23:46 UTC, particthistle commented on plugins/sampledata/multilang/multilang.php
>  				. '"show_featured":"","show_title":"","link_titles":"","show_intro":"","info_block_position":"",'
Addition for #32550
Line 862 - extra parameter article_layout
`. '"show_featured":"","article_layout":"_:default","show_title":"","link_titles":"","show_intro":"","info_block_position":"",'`

2021-03-01 23:51 UTC, particthistle commented
Changes to match up #32550. Part 2.

It stopped letting me add reviews to the code after line 862 for some reason. There's one more line needing adjustment to match up the changes outlined in #32550.

Line 864 - remove show_associations parameter: New line:
`. '"link_parent_category":"","show_author":"","link_author":"",'`

2021-03-02 10:13 UTC, infograf768 commented
`show_associations` should stay as it is a blog parameter (Options).

<img width="651" alt="Screen Shot 2021-03-02 at 11 10 03" src="https://user-images.githubusercontent.com/869724/109633038-f5b36000-7b47-11eb-8991-85b3c80d1446.png">

2021-03-03 13:46 UTC, AndySDH commented
Thanks for the feedback, I'll wait for #32550 to be finalized and merged, and once that's merged, I'll make sure to have the same version of the multilang.php file in this PR as well.

2021-03-10 10:41 UTC, ceford commented
#32550 is marked as merged - so is this ready for testing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32525">issues.joomla.org/tracker/joomla-cms/32525</a>.</sub>

2021-03-10 10:43 UTC, richard67 commented
@ceford I think maybe @AndySDH wants to update his branch first to latest 4.0-dev so it contains the changes from the merged PR, too. Let's see what he replies.

2021-03-10 15:45 UTC, AndySDH commented
Resolved conflicts with #32550 :)

2021-03-15 03:12 UTC, particthistle commented
I have tested this item :red_circle: unsuccessfully on 0f22848e688e6f2e5e8c8c6ce12d552d45dbcd43<br /><br />1. Syntax error with Blog Category Layout fixed from previous test, so this part was successful.

2. Additional changes were suggested for plugins/sampledata/multilang/multilang.php but have not been applied, so the parameters don't match #32550.

https://github.com/joomla/joomla-cms/pull/32525#discussion_r585126993 - Add `. '"blog_class_leading":"","blog_class":"",'` before line 859.
https://github.com/joomla/joomla-cms/pull/32525#discussion_r585128962 - Add `"link_intro_image":"",` at 860
https://github.com/joomla/joomla-cms/pull/32525#discussion_r585129380 - Add `"article_layout":"_:default",` at 862


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32525">issues.joomla.org/tracker/joomla-cms/32525</a>.</sub>

2021-03-15 08:15 UTC, AndySDH commented
@particthistle Done, thanks!

2021-03-16 03:02 UTC, particthistle commented
I have tested this item :white_check_mark: successfully on e94a87a0611b4f0023d28207c799616240cd6a37<br /><br />Thanks @AndySDH 

- H1 settings all working.

- Changes to related items identified in the multi-language sample data identified in #32550 also now applying successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32525">issues.joomla.org/tracker/joomla-cms/32525</a>.</sub>

2021-03-21 14:03 UTC, chmst commented
Concerning subheading: It was used in 3.9 https://issues.joomla.org/tracker/joomla-cms/30422<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32525">issues.joomla.org/tracker/joomla-cms/32525</a>.</sub>

2021-03-21 14:14 UTC, AndySDH commented
> Concerning subheading: It was used in 3.9 https://issues.joomla.org/tracker/joomla-cms/30422
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/32525](https://issues.joomla.org/tracker/joomla-cms/32525).

I'm aware but it was used present only in 1 view (2 views, actually), and absent in all the others. It was wildly inconsistent and I felt it served not much of a purpose. So I thought it made it sense to clean it up and remove it.

2021-03-22 05:14 UTC, particthistle commented
Subheading removal: Should it go ahead (I don't know anyone using it, but I'm sure there may be) do we just need to make sure it's listed here: https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4

If so, add Documentation Required tag for follow up.

2021-04-17 14:21 UTC, himanshu007-creator commented
I have tested this item :white_check_mark: successfully on e94a87a0611b4f0023d28207c799616240cd6a37<br /><br />Tested the behavior on all mentioned categories. Thanks @particthistle for helping out earlier.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32525">issues.joomla.org/tracker/joomla-cms/32525</a>.</sub>

2021-04-17 14:32 UTC, richard67 commented
I've allowed myself to solve the merged conflict and restored the previous test results because the merge after that for resolving the merge conflict was only a code style change.

2021-04-17 14:32 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32525">issues.joomla.org/tracker/joomla-cms/32525</a>.</sub>

2021-04-17 14:40 UTC, AndySDH commented
Thanks @richard67

2021-04-17 15:19 UTC, merged

2021-04-17 15:19 UTC, chmst commented
Thanks!