Make fontawesome+icomoon mapping available as Joomla asset
joomla/joomla-cms pull request #32541
Opened 2021-02-27 14:41 UTC by drmenzelit

First step to make fontawesome available as web asset.
At the moment Cassiopeia delivers an own fontawesome.css file that is the result of importing fontawesome files from the media/vendor folder combined with the icomoon B/C mapping file (stored in media/system). 
Since the fontawesome file can be also useful as a web asset in other parts of Joomla (e.g. frontend editing) or for 3rd party extensions / templates developers, it is better to have it in the media folder.

### Summary of Changes
Removed fontawesome.scss from Cassiopeia.
Changed the joomla.asset.json in Cassiopeia to load fontawesome from media folder.
Added a joomla-fontawesome.scss file in media/system.

### Testing Instructions
Apply the patch, run npm run build:css
Load the website using Cassiopeia as template.

### Actual result BEFORE applying this Pull Request
Fontawesome icons are present (e.g. search symbol, chevron in readmore button). Fontawesome is loaded as  templates/cassiopeia/css/vendor/fontawesome-free/fontawesome.min.css

### Expected result AFTER applying this Pull Request
Fontawesome icons are still present. Fontawesome is loaded as media/system/css/joomla-fontawesome.min.css

### Documentation Changes Required

2021-02-27 17:39 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 1b4894dce4e2039cbdad86d84854d4bf64afefc9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32541">issues.joomla.org/tracker/joomla-cms/32541</a>.</sub>

2021-02-27 18:27 UTC, Fedik commented
It does no need, there already fontawesome asset, in `media/vendor/joomla.asset.json`
And a fix for font-face files in #31364

2021-02-27 18:32 UTC, Fedik commented
hm I have missed "icomoon" changes.
if someone need "icomoon" then ignore my previous comment :wink:

2021-02-27 18:57 UTC, brianteeman commented
I would expect the fontawesome css to be the same just in a different location etc. But

![image](https://user-images.githubusercontent.com/1296369/109397219-9974f400-792d-11eb-8dc1-60a21224893b.png)

2021-02-27 19:15 UTC, drmenzelit commented
> It does no need, there already fontawesome asset, in `media/vendor/joomla.asset.json`
> And a fix for font-face files in #31364

I didn't see your PR before I did mine... And I was not aware of fontawesome as an asset in the `media/vendor/joomla.asset.json` file :-( 
As I understand the icomoon file contains a mapping old icomoon => new fontawesome. I think it is important to include.

2021-02-27 19:15 UTC, drmenzelit commented
@brianteeman the code in your screenshot is included in Autum but not in Cassiopeia

2021-02-28 13:25 UTC, Fedik commented
I think here some confusion, 
Cassiopeia already have `templates/cassiopeia/scss/vendor/fontawesome-free/fontawesome.scss`  that holds `fontawesome` and `icomoon`.

And `media/vendor/joomla.asset.json` already holds `fontawesome` Asset.

The final file `templates/cassiopeia/css/vendor/fontawesome-free/fontawesome.css`  overrides file from `media/vendor/fontawesome-free/fontawesome.css`, and so `fontawesome` Asset uses `fontawesome.css` provided by Cassiopeia.

All is working good already, you do not need to fix anything :wink:

2021-02-28 14:29 UTC, drmenzelit commented
I'm developing a J4 template without Bootstrap and with a parameter to switch fontawesome on / off. It works good. But if I want to use frontend editing, I need fontawesome (or I have to re-define the icons). I don't want to deliver an own version of fontawesome with the template (and Cassiopiea shouldn't do either), I want to load what Joomla already has in core. And I want to be able to load fontawesome only in component.php for the frontend editing. If the version of fontawesome in Joomla core doesn't include the font-face and the icons mapping, it will not work.

2021-02-28 14:29 UTC, brianteeman commented
@Fedik The problem being solved is that a template might not use fontawesome but when you open an edit form on the front end then you will need to load fontawesome. So by making it available as an asset it can be added into the edit forms

When I write fontawesome I mean the fontawesome WITH iconmoon conversion file

2021-02-28 15:30 UTC, Fedik commented
> So by making it available as an asset it can be added into the edit forms

As I already noted before: the `fontawesome` already provided by `media/vendor/joomla.asset.json`. 
`media/vendor/joomla.asset.json` always loaded, and available for all extensions.

> I'm developing a J4 template without Bootstrap and with a parameter to switch fontawesome on / off.

if you doing it in your personal template then all you need is something like:
```php
if ($needToEnableFont) 
{
  $wa->useStyle('fontawesome');
}
```

If you want this in Cassiopiea, then you have tor remove these dependencies from Cassiopiea `joomla.asset.json`:

https://github.com/joomla/joomla-cms/blob/9ca4e5672c82839f0e7933452cd4ea0085f33a4c/templates/cassiopeia/joomla.asset.json#L12-L15

https://github.com/joomla/joomla-cms/blob/9ca4e5672c82839f0e7933452cd4ea0085f33a4c/templates/cassiopeia/joomla.asset.json#L21-L24

And then use in PHP:
```php
if ($needToEnableFont) 
{
  $wa->useStyle('fontawesome');
}
```

2021-02-28 15:38 UTC, Fedik commented
> If the version of fontawesome in Joomla core doesn't include the font-face and the icons mapping, it will not work.

The `fontawesome` in Joomla core  contains only original fontawesome style and icons, without mapping to Joomla icons.
These mapping done by the template itself (eg `templates/cassiopeia/scss/vendor/fontawesome-free/fontawesome.scss`).

If people want to have Joomla icons Independently from the template, then we probably need to re-compile fontawesome in media/vendor. But this is totally different topic.

2021-02-28 15:52 UTC, Fedik commented
hm, sorry, I think I am Turtle :smile: 

I finally understood what you tries to do, it a bit in confusing way, but it is okay.

The PR is okay for its purpose.

Sorry again :wink:

2021-03-02 18:05 UTC, dgrammatiko commented on templates/cassiopeia/joomla.asset.json
> +      "uri": "media/system/css/joomla-fontawesome.min.css"
Please use the relative path here so that the asset could be automatically overridden in the template

```
"uri": "system/joomla-fontawesome.min.css"
```

2021-03-02 18:09 UTC, dgrammatiko commented
Also, another comment here: ALL the fields should use SVG icons either as HTML or as css background so that the front end WILL BE font awesome free. Icon fonts are really deprecated and should be considered HARMFUL as their killing performance metrics but also have serious caveats for visually impaired people.

2021-03-02 18:22 UTC, drmenzelit commented on templates/cassiopeia/joomla.asset.json
> +      "uri": "media/system/css/joomla-fontawesome.min.css"
Done

2021-03-02 18:23 UTC, dgrammatiko requested changes

2021-03-02 18:23 UTC, dgrammatiko commented on templates/cassiopeia/joomla.asset.json
> +      "uri": "system/css/joomla-fontawesome.min.css"
Almost, you need to remove also the `/css` part

2021-03-02 18:55 UTC, drmenzelit commented on templates/cassiopeia/joomla.asset.json
> +      "uri": "system/css/joomla-fontawesome.min.css"
I see... thank you for the help

2021-03-02 18:57 UTC, brianteeman commented
> also have serious caveats for visually impaired people.

They are no better and no worse than svg. Its all down to how they are used.

2021-03-02 19:02 UTC, dgrammatiko commented
> They are no better and no worse than svg. Its all down to how they are used.

I suspect if everyone else dropped already font icons there are obvious drawbacks. Basically abusing Fonts for enhancing style was once an option (no SVG support in IE, etc) but those reasons have been eliminated since IE which basically it's like a decade ago. Time to move to something more in line with the actual web devs practices. My 2c anyways...

2021-03-02 19:07 UTC, brianteeman commented
> there are obvious drawbacks

I am only commenting on the repeated statement that they are not bad for **accessibility** or that SVG are good for **accessibility**

2021-03-02 19:14 UTC, dgrammatiko commented
> I am only commenting on the repeated statement that they are not bad for accessibility or that SVG are good for accessibility

SVG's (depending also on how you're using them) could be better one at least one case: if the network fails to deliver either the css or the actual font then the icons will not be displayed. Inlining (obviously cleverly, without blowing up the document size) eliminates this case. If you have the document you already have the icons 😉. Anyways, there are more cases that fonts fall short for this particular usage but accessibility wise you can end up messing either. I never suggested that SVGs are by default accessible and icons are not but maybe the path to making something accessible could be easier with SVGs (purely because you will end up calling some PHP function that will do the right thing, instead of manually inserting HTML tags/attributes)

2021-03-20 14:06 UTC, Mrs-Jaydot commented
May I ask a question here?
I'm just a user, not a coder, but I don't know where else to ask.
I've made a test site with Beta8, and was happy to find FontAwesome installed locally.
However: I cannot use the brand icons (facebook, linkedin). Miscellaneous icons (bicycle, camera) display just fine.
Is there a reason for this?
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32541">issues.joomla.org/tracker/joomla-cms/32541</a>.</sub>

2021-03-20 14:08 UTC, sandramay0905 commented
@Mrs-Jaydot Questions on https://forum.joomla.org/

2021-03-20 14:16 UTC, Mrs-Jaydot commented
@sandramay0905 Thanks, I know, but no-one there has any idea. The only answer I got was "I don't think Joomla uses Font Awesome...".

2021-03-20 14:17 UTC, drmenzelit commented
> 
> 
> @sandramay0905 Thanks, I know, but no-one there has any idea. The only answer I got was "I don't think Joomla uses Font Awesome...".

Are you using Cassiopeia or an own template?

2021-03-20 14:18 UTC, Mrs-Jaydot commented
@drmenzelit Cassiopeia.

2021-03-20 14:22 UTC, brianteeman commented
There are multiple font files for fontawesome. Not all are free etc

2021-03-20 14:24 UTC, drmenzelit commented
> 
> 
> @drmenzelit Cassiopeia.

`<i class="fab fa-facebook"></i>` should work (fab is for brands)

2021-03-20 14:24 UTC, dgrammatiko commented
brands need a `fab` class, eg `<i class="fab fa-facebook-f"></i>` 
`fab` === brands
`far` === regurlar
`fas` === solid

In short there are 3 fonts

2021-03-20 14:31 UTC, Mrs-Jaydot commented
@brianteeman I know, but FA4 is free for download, and it contains brand icons.
@drmenzelit Thank you!! Works! I didn't know about the faB.
@Fedik Thank you for responding and explaining, I didn't know it worked that way.
Many thanks to all of you.
I will now move back to forum.org, where I belong :).

2021-07-28 13:41 UTC, RickR2H commented
Do we have to test this patch?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32541">issues.joomla.org/tracker/joomla-cms/32541</a>.</sub>

2021-07-28 13:44 UTC, richard67 commented
> Do we have to test this patch?

@RickR2H In general yes, every PR needs 2 tests, but is currently has a conflict in file `templates/cassiopeia/scss/vendor/fontawesome-free/fontawesome.scss`, so better wait until that has been resolved.

@drmenzelit Is the PR still relevant? If yes, could you solve the conflict? Let me know if you need help with that. Thanks in advance.

2021-07-28 15:03 UTC, drmenzelit commented
The discussion was long, I got lost at some point... and it seems my approach is not clear for everyone, so I think it is up to @wilsonge to decide what to do with it

2021-08-08 15:51 UTC, richard67 commented
@ChristineWk Could you test again with the new packages for this PR? Thanks in advance.

2021-08-08 15:58 UTC, richard67 commented on build/media_source/system/scss/joomla-fontawesome.scss
> +@import "../../../../media/vendor/fontawesome-free/scss/brands";
Are you sure that these import paths are right? In line 2 above it is one time "../" less to the media folder than it is here.

2021-08-08 16:01 UTC, richard67 commented on build/media_source/system/scss/joomla-fontawesome.scss
> +@import "../../../../media/vendor/fontawesome-free/scss/brands";
And line 2 is right I think.

2021-08-08 16:05 UTC, richard67 commented on build/media_source/system/scss/joomla-fontawesome.scss
> +@import "../../../../media/vendor/fontawesome-free/scss/brands";
Why don't you just use "../../vendor/" instead of "../../../media/vendor"?

2021-08-08 16:19 UTC, richard67 commented on build/media_source/system/scss/joomla-fontawesome.scss
> +@import "../../../../media/vendor/fontawesome-free/scss/brands";
Hmm I just see I might be wrong .. so I assume this here is right and hope there will be careful tests.

2021-08-08 16:41 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 5b1a08de59d76d51cd2f345aedded15365599474<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32541">issues.joomla.org/tracker/joomla-cms/32541</a>.</sub>

2021-08-08 16:58 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 5b1a08de59d76d51cd2f345aedded15365599474<br /><br />Hv this (if it's OK):
/*!
 * Font Awesome Free 5.15.3 by @fontawesome - https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
 */<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32541">issues.joomla.org/tracker/joomla-cms/32541</a>.</sub>

2021-08-08 17:08 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32541">issues.joomla.org/tracker/joomla-cms/32541</a>.</sub>

2021-08-08 17:08 UTC, N6REJ commented
we created a auto .fa to .iconmoon conversion system long ago.  idky it needs to be done in another way yet again.

2021-08-08 17:10 UTC, richard67 commented
> we created a auto .fa to .iconmoon conversion system long ago. idky it needs to be done in another way yet again.

@N6REJ This PR here doesn't change anything on the mapping, it just moves scss to another place and makes it available as template-independent asset.

2021-08-08 17:20 UTC, brianteeman commented
Its not being done in a different way its just putting the files in the correct place

2021-08-08 17:33 UTC, richard67 commented
> Its not being done in a different way its just putting the files in the correct place

That's what I've said, too.

2021-08-08 18:36 UTC, brianteeman commented
github cache sucks sometimes

2021-08-09 09:44 UTC, N6REJ commented
Thanks guys, I was about to say, danggggg after all that work LOL

2021-08-09 10:47 UTC, merged

2021-08-09 10:47 UTC, wilsonge commented
Thanks!