Migrate data for repeatable fields
joomla/joomla-cms pull request #32611
Opened 2021-03-08 08:54 UTC by joomdonation

Pull Request for Issue #30556.

### Summary of Changes
This PR solves the Release Blocker issue #30556. It convert data of repeatable fields to the format accepted by subfield.

### Testing Instructions
1. Install Joomla 3.10.0
2. Create one or two repeatable field for articles
3. Create one or two articles, enter data for the created custom fields
4. Upgrade your site to latest Joomla 4.0-dev package (generate for this PR). Link will be provided later when build process completed
5. Check the articles on upgraded site, edit these article, check and make sure data in Fields tab is there

### Actual result BEFORE applying this Pull Request
Data for repeatable fields not being migrated

### Expected result AFTER applying this Pull Request
Data for repeatable fields are migrated properly

2021-03-11 16:41 UTC, Quy commented on administrator/components/com_admin/script.php
> +					->where('field_id = ' . $row->id);
Please use prepared statement.

https://www.techfry.com/joomla/prepared-statements-in-joomla-4

2021-03-12 01:18 UTC, joomdonation commented on administrator/components/com_admin/script.php
> +					->where('field_id = ' . $row->id);
@Quy I think this is not needed as we just do data migration, not process any input from end-users (other code from same method does not use prepared statement, too). So for this, I think we can leave the code as how it is.

2021-03-21 23:28 UTC, wilsonge commented on administrator/components/com_admin/script.php
> +					->where('field_id = ' . $row->id);
Probably here it's fine. I'm not sure in the upgrade script whether we'll have the new or old database package anyhow. So probably safer to use something that's compatible with the 3.x database package anyhow

2021-03-25 22:39 UTC, Quy commented
@AndySDH Please consider testing. Thanks!

2021-03-26 15:41 UTC, obuisard commented
I have tested this item :red_circle: unsuccessfully on 237dc74d452bb54a4bb409e3d5f2ffa9e66d2cda<br /><br />After update to Joomla 4, the Joomla 4 dashboard became unusable. The errors hint to the fact that the database was not updated in the process.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-03-26 15:43 UTC, joomdonation commented
Hmm. Without this PR, does the update works well for you?

2021-03-26 15:44 UTC, obuisard commented
I have to try it out. Will keep you posted<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-03-26 15:45 UTC, joomdonation commented
OK. Thanks @obuisard

2021-03-26 16:00 UTC, obuisard commented
I can confirm: the error does not come from the PR, the update from 3.10 alpha 6 dev to Joomla 4 beta 8 dev (update package) fails.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-03-26 16:04 UTC, joomdonation commented
@obuisard Maybe you can raise a new issue for that? If you can let us know step by step what you did and got that error, that would help us to check to see why it happens and get it sorted

2021-03-26 16:24 UTC, obuisard commented
I followed the exact test instructions. 
Except that upon update, the files are updated, not the database.
In the console, I get 1093 You can't specify target table 'y2jza_template_styles' for update in FROM clause 
When I look at the database, the template_styles table has not been updated.
I will test with 'official' releases, not the nightlies to see if that is inherent to the fact that they are nightlies (and may be unstable).
If updating from 3.10 alpha 5 to Joomla 4 beta 7 fails, I will open a new bug issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-03-26 16:46 UTC, sksuryan commented
I faced a similar issue that @obuisard mentioned with the 4.0-dev nightly package without the PR as well as with the PR. Although, the article section in the one without the PR seems to be usable now, I don't know how that happened. Sadly, I can't say the same about the one with PR because I deleted that installation.

Since then, I have created two new fresh installations with the PR and tested both of them successfully(one on Microsoft Edge, other on Firefox Private Window).

2021-03-26 16:47 UTC, sksuryan commented
I have tested this item :white_check_mark: successfully on 237dc74d452bb54a4bb409e3d5f2ffa9e66d2cda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-03-27 13:45 UTC, RickR2H commented
I have tested this item :red_circle: unsuccessfully on 237dc74d452bb54a4bb409e3d5f2ffa9e66d2cda<br /><br />Using the provided files the update works but, the Joomla article layout is missing all settings tabs. This was before and after the patch after update to J4! So in both situations I couldn't check if the fields are there or not. I can confirm that the custom fields values are present in the DB after upgrade.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-03-27 13:58 UTC, joomdonation commented
@RickR2H This PR just do the data migration, so the issue with Joomla articles layout might be un-related. After the update, could you please update your site to latest Joomla 4 nightly build package which can be downloaded here https://developer.joomla.org/nightly-builds.html , then check it again to see if articles layout is sorted?

2021-03-27 16:04 UTC, obuisard commented
No matter what I have tried, I was unable to successfully update from 3.9.10 Alpha 5 or 6-dev to 4.0 beta8-dev or 4.0 beta8-dev with the patch. I am going to file a bug report or is Joomla 3.10 not even ready for a direct update to Joomla 4?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-03-27 16:08 UTC, richard67 commented
> No matter what I have tried, I was unable to successfully update from 3.9.10 Alpha 5 or 6-dev to 4.0 beta8-dev or 4.0 beta8-dev with the patch. I am going to file a bug report or is Joomla 3.10 not even ready for a direct update to Joomla 4?

@obuisard Updating 3.9.10 Alpha 5 to 4.0 beta8-dev should work. If not, open an issue please. Thanks in advance.

2021-04-02 05:46 UTC, joomdonation commented
Today, I synchronize this branch with latest 4.0-dev. Tested it again and it worked. Update went well, data is migrated properly. Could you please help testing again one more time?

2021-04-02 06:36 UTC, alikon requested changes

2021-04-02 06:36 UTC, alikon commented on administrator/components/com_admin/script.php
> +					->from('#__fields_values')
please use `$db->quoteName()`

2021-04-02 08:59 UTC, alikon commented
.. update works but, the  article layout is missing all settings tabs. (only in the artcile that have had repeteable before migration)

2021-04-02 09:01 UTC, joomdonation commented
Could you show me a screenshot? Strange it is working well for me

2021-04-02 09:05 UTC, alikon commented
sure
 this is when edit the article that have fields before migration   no tabs
![Screenshot from 2021-04-02 11-02-16](https://user-images.githubusercontent.com/181681/113401044-11a65d80-93a3-11eb-8d61-2272df5c8c5b.png)

 this is when edit the article with no fields before migration tabs

![Screenshot from 2021-04-02 11-04-57](https://user-images.githubusercontent.com/181681/113401217-5205db80-93a3-11eb-9e5e-a66bff8e775a.png)

2021-04-02 09:11 UTC, joomdonation commented
I have no idea. Maybe I should setup test articles with and without fields and testing again. Or maybe you can send export and send database of the updated site to me for debugging purpose? I sent you a message via Glip

2021-04-02 09:27 UTC, alikon commented
weird
![Screenshot from 2021-04-02 11-26-29](https://user-images.githubusercontent.com/181681/113403052-597ab400-93a6-11eb-919c-4269e595f5ca.png)

2021-04-02 11:17 UTC, joomdonation commented
Strange, too. I use your database and here is the article screenshot, no error like in your test. Maybe the difference is I'm using Window ?

How did you perform updating? I download the package here https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/32611/downloads/41493/Joomla_4.0.0-beta8-dev+pr.32611-Development-Update_Package.zip, then go to Components -> Joomla Update, Upload & Update tab to upload the package and update

![article](https://user-images.githubusercontent.com/977664/113411271-88f9e280-93df-11eb-8b14-046653ced28a.png)

2021-04-02 12:00 UTC, astridx commented
I have the same error like @alikon on Ubuntu. [systeminfo-2021-04-02T13 54 44+02 00.txt](https://github.com/joomla/joomla-cms/files/6249394/systeminfo-2021-04-02T13.54.44%2B02.00.txt)


![Articles Fields test Administration](https://user-images.githubusercontent.com/9974686/113413593-4f16e500-93bb-11eb-945f-75b979388fde.png)

![Articles New test Administration](https://user-images.githubusercontent.com/9974686/113413592-4f16e500-93bb-11eb-8886-64fb3a31ea52.png)

![Joomla Update test Administration](https://user-images.githubusercontent.com/9974686/113413590-4e7e4e80-93bb-11eb-853f-c43c9245e9f6.png)

![Articles Edit test Administration](https://user-images.githubusercontent.com/9974686/113413589-4d4d2180-93bb-11eb-9b3b-492d16837e46.png)

2021-04-02 12:18 UTC, joomdonation commented
@astridx I'm unsure what's wrong with the update as when I use the database from @alikon , import it to my site, the article is working well. Maybe you can confirm that by configure your fresh Joomla 4 installation to use the migrated database?

I mean the data migration process works OK, I just don't know what part of the update process causing that error (the js error from browser console looks strange to me)

2021-04-02 12:22 UTC, richard67 commented
Our updates currently are missing the deletion of this or that file or folder on update, i.e. after an update there might be files still present which should be removed. It's the usual thing with the files and folders deletion in com_admin's script.php not being up to date. It's a work in progress to improve that maintenance task and automate it as much as possible. It's just my guess that something like that might cause the issues.

2021-04-02 12:47 UTC, astridx commented
> @astridx I'm unsure what's wrong with the update as when I use the database from @alikon , import it to my site, the article is working well. Maybe you can confirm that by configure your fresh Joomla 4 installation to use the migrated database?
> 
> I mean the data migration process works OK, I just don't know what part of the update process causing that error (the js error from browser console looks strange to me)

I can confirm this. I just cloned a new 4.0-dev branch and copied the configuration.php from the failed test.
Now I can edit all tabs of the article.

2021-04-02 13:04 UTC, joomdonation commented
If so, please check the migrated data. If the migrated data for repeatable form fields is OK, I would say that this is a successful test.

The error which you are having here could cause by some files left during update (as explained by @richard67) and it is unrelated to this PR. This PR just focus on data migration only

2021-04-02 13:07 UTC, astridx commented
The data was correct, there were only two text fields with simple texts.

2021-04-02 13:09 UTC, joomdonation commented
If so, I would say that it is a successful test?

2021-04-02 13:33 UTC, alikon commented
yes for me

2021-04-02 13:34 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 5af3c9aef97cf92490cd6e25e34b2dc127f0a37a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-04-02 16:01 UTC, richard67 commented
@astridx Would you say your test was successful? If yes, please mark your test result. Thanks in advance.

2021-04-09 16:17 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32611">issues.joomla.org/tracker/joomla-cms/32611</a>.</sub>

2021-04-09 16:18 UTC, richard67 commented
I've restored @sksuryan 's successful test in the tracker so it's properly counted. The changes after that test which have invalidated the test result was only code style and quote names added.

2021-04-09 18:06 UTC, merged

2021-04-09 18:06 UTC, wilsonge commented
OK let's get this in. Thanks!

2021-04-09 21:37 UTC, HLeithner commented
I tested this and it looks ok only error message I get which I'm not sure if it's related after update for a media file:

`<b>Warning</b>:  Illegal string offset 'imagefile' in <b>/plugins/fields/media/tmpl/media.php</b> on line <b>31</b><br />`
 

2021-04-10 06:37 UTC, joomdonation commented
@HLeithner : Does the media file a part of repeatble field which we are migrating data to SubField?

2021-04-10 10:54 UTC, HLeithner commented
@joomdonation yes

2021-04-10 10:57 UTC, joomdonation commented
@HLeithner Could you send me a copy of the migrated database (maybe via Glip) so that I can debug?

2021-04-10 12:09 UTC, HLeithner commented
sure

2021-04-10 16:34 UTC, joomdonation commented
@HLeithner I can confirm the issue with media field type. The reason is because in Joomla 3, data for the field is stored in string format (something like **images\powered_by.png**) but in Joomla 4, we store it in JSON format (something like **{"imagefile":"images\/powered_by.png","alt_text":""}**

Look like when media field is used alone, the plugin do that conversion itself https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/fields/media/media.php#L78-L88 . But when the field is used in subfields, it is not converted yet

Not sure if we can do that conversion somehow when media is used on subfields? Do you have any idea ? Or maybe @laoneo know a way?

Of course we can do that format conversion in the migration code but I'm unsure if that's the right away?

One more thing, we might have problem with media field (uses alone, not related to this PR). In Joomla 3, we just store path to the image but in Joomla 4, it also store size of the image **{"imagefile":"images\/joomla_black.png?joomla_image_width=225&joomla_image_height=50","alt_text":""}** . From my quick test, without joomla_image_width and joomla_image_height, the image is not being displayed (with and height of the img tag set to 0 for some reasons)

2021-04-10 21:37 UTC, HLeithner commented
I think that was a @dgrammatiko thing for lazyloading, maybe he can help us here.

2021-04-10 21:52 UTC, dgrammatiko commented
> I think that was a @dgrammatiko thing for lazyloading, maybe he can help us here.

As I read the comment I think this has nothing to do with lazyloading but rather the fact that the particular custom field now stores also the `alt` data. The lazyloading is still done with a string (appending some query params, which was hugely controvesial and there were arguments) but we kept it as a string for the shake of B/C.  I guess Brian could have some insights on the implementation of the alt attribute (I don't think I was involved in that)

2021-04-10 21:58 UTC, dgrammatiko commented
> From my quick test, without joomla_image_width and joomla_image_height, the image is not being displayed (with and height of the img tag set to 0 for some reasons)

The image needs to be processed with https://github.com/joomla/joomla-cms/blob/f4ac18829fad6eadd7260ac2f951aca0c7da459b/libraries/src/HTML/HTMLHelper.php#L671 and if there are width and hight set the lazyloading tag, etc. I thought I already did that https://github.com/joomla/joomla-cms/blob/f4ac18829fad6eadd7260ac2f951aca0c7da459b/plugins/fields/media/tmpl/media.php#L31

2021-04-11 04:19 UTC, joomdonation commented
@HLeithner The warning should be solved by PR https://github.com/joomla/joomla-cms/pull/33094 , could you please take a look at it?