[4.0] fixes absence of actions in batch selection of Users
joomla/joomla-cms pull request #32749
Opened 2021-03-19 16:49 UTC by sksuryan

Pull Request for Issue #32735.

### Summary of Changes
This pull request fixes the absence of actions in batch selections of Users.

### Testing Instructions
- Login to administrator
- Go to users => Manage
- Select a user
- Select actions => Batch

### Actual result BEFORE applying this Pull Request
![image](https://user-images.githubusercontent.com/42460131/111814785-e5013900-8900-11eb-8be0-1078261b7ad7.png)

### Expected result AFTER applying this Pull Request
![image](https://user-images.githubusercontent.com/42460131/111814683-c4d17a00-8900-11eb-83a7-06417e056bc2.png)

PS: credits to @joomdonation for suggesting the changes.

2021-03-19 16:51 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on d85718c6e494541d1701a121e48172412aa55f13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32749">issues.joomla.org/tracker/joomla-cms/32749</a>.</sub>

2021-03-19 17:29 UTC, alikon requested changes

2021-03-19 17:29 UTC, alikon commented on administrator/components/com_users/tmpl/users/default_batch_body.php
> +			<div class="control-group radio">
please change with
```php
<div class="control-group radio">
	<?php echo HTMLHelper::_('select.radiolist', $options, 'batch[group_action]', '', 'value', 'text', 'add'); ?>
</div>
```

dunno if `class="control-group radio"` is correct in J4

2021-03-19 17:42 UTC, sksuryan commented on administrator/components/com_users/tmpl/users/default_batch_body.php
> +			<div class="control-group radio">
oh wait a second, it should be `form-group` right? As far as I remember, Bootstrap 4 uses it.

2021-03-19 17:47 UTC, drmenzelit commented on administrator/components/com_users/tmpl/users/default_batch_body.php
> +			<div class="control-group radio">
Joomla is using Bootstrap 5 now

2021-03-19 17:49 UTC, alikon commented on administrator/components/com_users/tmpl/users/default_batch_body.php
> +			<div class="control-group radio">
https://developer.joomla.org/news/839-joomla-4-0-will-ship-with-bootstrap-5.html

2021-03-19 18:03 UTC, chmst commented
Good work! But there are a few thing for accessibility.

The whole thing (group select and radiobuttons) should be wrapped within a fieldset.

We could refine this later, at the moment it solves a real bug.

2021-03-19 18:05 UTC, sksuryan commented on administrator/components/com_users/tmpl/users/default_batch_body.php
> +			<div class="control-group radio">
Oh I was asking this because I saw it's usage in the code, and I couldn't really find something on Bootstrap5 docs. I'll change it to `form-group` and push the changes because it's being used at other places too.

2021-03-19 18:07 UTC, Quy commented on administrator/components/com_users/tmpl/users/default_batch_body.php
> +			<div class="control-group radio">
See #31218

2021-03-19 18:07 UTC, alikon commented on administrator/components/com_users/tmpl/users/default_batch_body.php
> +			<div class="control-group radio">
we could refine this later

2021-03-19 18:11 UTC, sksuryan commented on administrator/components/com_users/tmpl/users/default_batch_body.php
> +			<div class="control-group radio">
> 
> 
> See #31218

yes, that's what I was talking about, I remembered I read it somewhere.

2021-03-19 18:18 UTC, brianteeman commented
Please add a legend

2021-03-19 18:42 UTC, sksuryan commented
![image](https://user-images.githubusercontent.com/42460131/111828200-f4887e00-8910-11eb-83e1-44ce903f1d5f.png)

@brianteeman @chmst both fieldset and legend have been added.

2021-03-19 18:44 UTC, alikon approved these changes
php side ok 4 me

2021-03-19 18:59 UTC, Quy commented on administrator/language/en-GB/com_users.ini
> +COM_USERS_BATCH_ACTIONS="Select Action"
```suggestion
COM_USERS_BATCH_ACTIONS="Select Action"
COM_USERS_BATCH_ADD="Add To Group"
COM_USERS_BATCH_DELETE="Delete From Group"
COM_USERS_BATCH_GROUP="Select Group"
```

2021-03-19 19:15 UTC, sksuryan commented on administrator/language/en-GB/com_users.ini
> +COM_USERS_BATCH_ACTIONS="Select Action"
oh okay, it's in alphabetical order.

2021-03-20 11:04 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on cf3bac74be58ce6e8c1d635f7c8958d3e6f59ed2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32749">issues.joomla.org/tracker/joomla-cms/32749</a>.</sub>

2021-03-21 17:22 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on cf3bac74be58ce6e8c1d635f7c8958d3e6f59ed2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32749">issues.joomla.org/tracker/joomla-cms/32749</a>.</sub>

2021-03-21 17:23 UTC, jwaisner commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32749">issues.joomla.org/tracker/joomla-cms/32749</a>.</sub>

2021-03-22 06:21 UTC, merged