[4.0] Better css for fronntend edit buttons
joomla/joomla-cms pull request #32757
Opened 2021-03-20 11:30 UTC by rdeutz

Pull Request for Issue #32170 .

### Summary of Changes

A bit better css for the edit buttons,  I made the background half transparent and made the "Edit" text sr-only.

### Testing Instructions

* apply patch
*  node build/build.js --compile-css templates/cassiopeia/scss

### Actual result BEFORE applying this Pull Request
![grafik](https://user-images.githubusercontent.com/467356/111868006-d86bf780-8977-11eb-8c73-88e7183d6cdc.png)

### Expected result AFTER applying this Pull Request
![grafik](https://user-images.githubusercontent.com/467356/111868015-e15cc900-8977-11eb-8a96-7795a48afa19.png)

### Documentation Changes Required

2021-03-20 11:36 UTC, astridx commented
Are you sure that `sr-only` is correct? 
I think in Boostrap 5 we should use `visually-hidden`
https://getbootstrap.com/docs/5.0/getting-started/accessibility/

2021-03-20 11:54 UTC, drmenzelit requested changes
<span class="icon-edit" aria-hidden="true"></span><span class="vissually-hidden">' . Text::_('JGLOBAL_EDIT') . '</span></a>

2021-03-20 12:11 UTC, brianteeman commented on layouts/joomla/edit/frontediting_modules.php
> +	<span class="icon-edit" aria-hidden="true"></span><span class="sr-only">' . Text::_('JGLOBAL_EDIT') . '</span></a>
Please use visually-hidden instead

2021-03-20 12:12 UTC, brianteeman commented on templates/cassiopeia/scss/blocks/_frontend-edit.scss
> +  top:0;
```suggestion
  top: 0;
```

2021-03-20 12:12 UTC, brianteeman commented on templates/cassiopeia/scss/blocks/_frontend-edit.scss
>  a.jmenuedit {
might as well delete the class if it is empty

2021-03-20 12:19 UTC, brianteeman commented
It's a bit hard to tell from your screenshots but it looks like the issue with the placement of the breadcrumbs module edit link is not resolved. 

In screenshot 1 it is in the wrong place on the far right
In screenshot 2 I cant see it at all

2021-03-20 12:20 UTC, brianteeman commented
PS I had been thinking of a different approach but I havent had the time to go further with it and I doubt I will for some time.

Instead of the links/buttons being visible all the time we have a toggle button to display them. A bit like the accessibility plugin

2021-03-20 12:43 UTC, infograf768 commented
rtl

2021-03-20 14:23 UTC, rdeutz commented
@infograf768 can you have a look at the rtl if my change does the trick, I don't have a site with rtl languages, seems they are all not ready for 4

2021-03-20 14:25 UTC, rdeutz commented
> It's a bit hard to tell from your screenshots but it looks like the issue with the placement of the breadcrumbs module edit link is not resolved.

It's not, it is in the top right corner. Don't seen atm how we can fix this with css.

2021-03-20 14:25 UTC, drmenzelit approved these changes

2021-03-20 14:27 UTC, brianteeman commented
> @infograf768 can you have a look at the rtl if my change does the trick, I don't have a site with rtl languages, seems they are all not ready for 4

Persian is ready. Or just set change <rtl>0</rtl> in the active langmetadat.xml

2021-03-21 12:11 UTC, rdeutz commented
Ready to test, should now work.

2021-03-21 12:25 UTC, brianteeman commented
Nearly there.

Tested with the sample data (not the testing data)

- Breadcrumbs is now in the correct place
- Link in the top right - expected it to be the search module. It was actually the bottom menu module. Looks to be caused by the absolute positioning.
- The edit link for the search module is actually underneath (and therefore not selectable) the bottom menu module link. Again because of the absolute positioning

2021-03-21 12:38 UTC, rdeutz commented
> Link in the top right - expected it to be the search module. It was actually the bottom menu module. Looks to be caused by the absolute positioning.

fixed

> The edit link for the search module is actually underneath (and therefore not selectable) the bottom menu module link. Again because of the absolute positioning

fixed

2021-03-21 14:02 UTC, brianteeman commented
Lastest articles is still top right (and the tooltip is bottom right)

![image](https://user-images.githubusercontent.com/1296369/111907615-0b80ba80-8a4e-11eb-8597-9b84b7ff6a4e.png)

2021-03-21 14:03 UTC, brianteeman commented
mod_custom is also hidden in the top right

2021-03-21 15:37 UTC, rdeutz commented
Next iteration to catch all modules.

2021-03-22 06:46 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 62908f6b7cc19abcaa3f29063cdd44e13a23f5de<br /><br />Looks much better now. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32757">issues.joomla.org/tracker/joomla-cms/32757</a>.</sub>

2021-03-22 13:23 UTC, drmenzelit commented
I have tested this item :white_check_mark: successfully on 62908f6b7cc19abcaa3f29063cdd44e13a23f5de<br /><br />Tested with blog sample data.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32757">issues.joomla.org/tracker/joomla-cms/32757</a>.</sub>

2021-03-22 13:31 UTC, rdeutz commented
Set to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32757">issues.joomla.org/tracker/joomla-cms/32757</a>.</sub>

2021-03-22 13:34 UTC, merged

2021-03-22 13:34 UTC, drmenzelit commented
Thanks