checkbox placed inline with the label in login model
joomla/joomla-cms pull request #32764
Opened 2021-03-20 14:00 UTC by rjharishabh

### Summary of Changes

Checkbox placed inline with the label in login model

### Testing Instructions
Chrome  and  Firefox  on  windows 10

### Actual result BEFORE applying this Pull Request
![check_old](https://user-images.githubusercontent.com/61203226/111871906-8399a280-89b2-11eb-97e2-eac4d700cd7b.JPG)

### Expected result AFTER applying this Pull Request
![check_new](https://user-images.githubusercontent.com/61203226/111871912-8b594700-89b2-11eb-9795-c00f8ee802a3.JPG)

2021-03-20 14:25 UTC, brianteeman commented
This is a valid issue but the proposal is obviously not correct as the classes are not applied correctlty

2021-03-20 14:34 UTC, rjharishabh commented
> This is a valid issue but the proposal is obviously not correct as the classes are not applied correctlty

are you talking about 'controls' class

2021-03-20 23:03 UTC, saumyasarkar11 commented
> > This is a valid issue but the proposal is obviously not correct as the classes are not applied correctlty
> 
> are you talking about 'controls' class

Remove the checkbox from the div with class "contents-label" and create a specific div for it with class ''controls" and then wrap both the divs in one row. Should be alright.

2021-03-21 04:49 UTC, rjharishabh commented
> Remove the checkbox from the div with class "contents-label" and create a specific div for it with class ''controls" and then wrap both the divs in one row. Should be alright.

can I use span instead of div

2021-03-21 06:06 UTC, saumyasarkar11 commented
> > Remove the checkbox from the div with class "contents-label" and create a specific div for it with class ''controls" and then wrap both the divs in one row. Should be alright.
> 
> can I use span instead of div

It's better to keep the code as original as possible. Avoid using span

2021-03-21 06:41 UTC, saumyasarkar11 requested changes
I tried to apply this patch but it said : The patch could not be applied because it conflicts with a previously applied patch: components/com_users/tmpl/login/default_login.php

2021-03-21 07:39 UTC, rjharishabh commented
> I tried to apply this patch but it said : The patch could not be applied because it conflicts with a previously applied patch: components/com_users/tmpl/login/default_login.php

can you please tell me more about it

2021-03-21 10:28 UTC, drmenzelit commented
Keep it simple with correct HTML structure. Probably you don't need a div nor a span element. The `control` classes are remains from Bootstrap 2 used in Joomla 3.

2021-03-21 12:17 UTC, rjharishabh commented
> Keep it simple with correct HTML structure. Probably you don't need a div nor a span element. The `control` classes are remains from Bootstrap 2 used in Joomla 3.

Thanks

2021-03-22 02:09 UTC, saumyasarkar11 commented
I think you should create an issue first regarding this. What say? @rjharishabh

2021-03-22 04:07 UTC, rjharishabh commented
> I think you should create an issue first regarding this. What say? @rjharishabh

Yes sure, I will create an issue for this.

2021-03-22 04:07 UTC, closed without merging

2021-03-22 08:56 UTC, drmenzelit commented
You don't need to create an issue, you can make a PR directly