[4.0] Allow Managers to edit account via com_users
joomla/joomla-cms pull request #32771
Opened 2021-03-21 10:03 UTC by joomdonation

Pull Request for Issue # .

### Summary of Changes
This is my quick PR try to solve https://github.com/joomla/joomla-cms/issues/30217. The main change here is it allows user to edit his own account without having to belong to a user group which is having **Access Administration Interface** permission (right now, we have to use com_admin to allow them to do that).

I just do this quickly to get feedback, so please do not test it yet.

2021-03-21 10:15 UTC, brianteeman commented
In principle yes this is how I see it being done

2021-03-21 10:20 UTC, joomdonation commented
brianteeman Could you please try it quickly to see what is missing or still need to be addressed?

2021-03-21 10:33 UTC, brianteeman commented
From my quick test with both a manager and super administrator account this PR works correctly and is how it should have been done from the beginning without all the duplication of code in com_admin

2021-03-21 10:56 UTC, richard67 commented
@joomdonation Event if it’s draft status you should fix the PHPCS (code style) errors reported by drone, because only if these pass the system tests will be run, and those would show if there was a mistake.

2021-03-21 13:30 UTC, richard67 commented
> The main change here is it allows user to edit his own account ... 

@joomdonation Should the title of the PR be changed from "[4.0] Allow Managers to edit account via com_users" to "[4.0] Allow Managers to edit **_own_** account via com_users"?

2021-03-21 13:49 UTC, joomdonation commented
@richard67 Yes. I changed it to a better title (describe exactly what PR does)

2021-03-21 13:55 UTC, richard67 commented
@joomdonation Your last commit changed the since tag at the wrong place. the old function should remain 1.6 and the new one should get deploy version, but you did it vice versa ;-)

2021-03-21 13:55 UTC, richard67 commented on administrator/components/com_users/src/Controller/UserController.php
> +	 * @since   __DEPLOY_VERSION__
```suggestion
	 * @since   1.6
```

2021-03-21 13:56 UTC, richard67 commented on administrator/components/com_users/src/Controller/UserController.php
> +	 * @since   1.6
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-03-21 13:56 UTC, richard67 commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> + * @since  4.0.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2021-03-21 13:59 UTC, richard67 commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> + * @since  4.0.0
This one is still to be changed.

2021-03-21 14:09 UTC, joomdonation commented
Thanks @richard67. Hope it is all OK now. On top of my head, this PR is now ready for reviewing and testing. Hopefully we can close the release blocker issue https://github.com/joomla/joomla-cms/issues/30217

2021-03-21 14:11 UTC, richard67 commented
@joomdonation 

> Hope it is all OK now.

Yes, code looks ok and clean to me.

> Hopefully we can close the release blocker issue #30217

You mean this PR solves it? If you confirm, I will close it.

2021-03-21 14:12 UTC, richard67 commented
Added the release blocker label as inherited from the issue.

2021-03-21 14:13 UTC, joomdonation commented
@richard67 Yes, I think we can close that issue. Even if this PR is not accepted, I think most users can agree that it is not release blocker anymore (the problem right now is just duplication code which is solved if this PR is accepted)

2021-03-21 14:16 UTC, richard67 commented
> 
> 
> Even if this PR is not accepted, I think most users can agree that it is not release blocker anymore (the problem right now is just duplication code which is solved if this PR is accepted)

@joomdonation You mean I should remove the release blocker label from this PR?

2021-03-21 14:17 UTC, joomdonation commented
> @joomdonation You mean I should remove the release blocker label from this PR?

For now, we can leave it as how it is.

2021-03-21 23:25 UTC, wilsonge commented
To me the thing I'd like to do before 4.0 ships is remove com_admin. Whilst we don't guarantee full b/c on extensions - I would rather just remove com_admin now before 4.0 ships and not have any issues.

2021-03-21 23:29 UTC, brianteeman commented
Removing com_admin completely? It does a lot more than what this PR is correctly removing

2021-03-21 23:40 UTC, wilsonge commented
Sorry to be clear the profile view that we added back in https://github.com/joomla/joomla-cms/pull/29251 - I don't want to remove the rest of it

2021-03-22 07:43 UTC, brianteeman commented
OK - we're all on the same page then

2021-03-22 17:06 UTC, Quy commented on administrator/components/com_users/src/Controller/UserController.php
> +		// Allow user to edit his profile
```suggestion
		// Allow user to edit their profile
```
```suggestion
		// Allow user to edit his profile
```

2021-03-22 17:06 UTC, Quy commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> +		// Allow user to edit data from his own account
```suggestion
		// Allow user to edit data from their own account
```
```suggestion
		// Allow user to edit data from his own account
```

2021-03-22 23:41 UTC, joomdonation commented on administrator/components/com_users/src/Controller/UserController.php
> +		// Allow user to edit his profile
@Quy How about change all of these to **Allow users to edit their own account?**?

2021-03-23 01:00 UTC, Quy commented on administrator/components/com_users/src/Controller/UserController.php
> +		// Allow user to edit his profile
Yes please.

2021-03-23 20:11 UTC, brianteeman commented
Will you be removing the now useless code in com_admin in this PR

2021-03-23 20:13 UTC, rdeutz commented
> Will you be removing the now useless code in com_admin in this PR

Let's get that in, removal can be done in another PR.

2021-03-23 20:20 UTC, brianteeman commented
I just asked so I knew if to mark this as good test or not

2021-03-23 20:24 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 9b3a9b84ed6e8fa9b75e431f0f34bc94da7efdf1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-23 21:09 UTC, HLeithner commented on administrator/components/com_users/src/Controller/UserController.php
> +		if (isset($data[$key]) && $this->app->getIdentity()->id == $data[$key])
is there a reason for the weak comparison?

2021-03-23 21:09 UTC, HLeithner commented on administrator/components/com_users/src/Controller/UserController.php
> +		$task  = $this->getTask();
do you expect that this function is called with another task?

btw. cs should be fixed here

2021-03-23 21:09 UTC, HLeithner commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> +			if ($user->id == $id)
Reason for the weak comparison?

2021-03-24 01:53 UTC, joomdonation commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> +			if ($user->id == $id)
To be honest, I don't know if **$user->id** always return data in **int** data type, and that's the reason I use weak comparison here.

2021-03-24 01:57 UTC, joomdonation commented on administrator/components/com_users/src/Controller/UserController.php
> +		if (isset($data[$key]) && $this->app->getIdentity()->id == $data[$key])
Same as other place, I'm unsure if **$this->app->getIdentity()->id** is always int data type. If you can confirm that it is akways int data type, I will modify code here to use strict comparison (need int type casting for data[$key] here, I think).

2021-03-24 02:09 UTC, joomdonation commented on administrator/components/com_users/src/Controller/UserController.php
> +		$task  = $this->getTask();
Yes, user can press different buttons (so different tasks) to save the account data but we only have to redirect them to previous page when Save & Close button is clicked (task = save). So this code is fine as it is. Could you please let me know about the cs issue here? No complain from our system, so I don't know what should be changed? Maybe remove blank like before 

```php
$task  = $this->getTask();
```
?

2021-03-24 07:10 UTC, rdeutz commented
I tied to reproduce the error with current dev and it seems to be fixed magically. Can anyone confirm?

2021-03-24 07:16 UTC, joomdonation commented
> I tied to reproduce the error with current dev and it seems to be fixed magically. Can anyone confirm?

You mean you logged in using a manager account and can still edit the account? Maybe you still use the old link (which is linked to com_admin which should be removed if this PR is accepted)

2021-03-24 07:25 UTC, rdeutz commented
I followed the instructions you gave and yes it is a link to com_admin. When I apply your patch then it still works but com_user is used. 

Please change the testing instructions

2021-03-24 07:28 UTC, joomdonation commented
Ah, Yes, sorry. The testing instructions need to be updated. I will do that.

2021-03-24 07:34 UTC, rdeutz commented
I have tested this item :white_check_mark: successfully on 9b3a9b84ed6e8fa9b75e431f0f34bc94da7efdf1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 07:37 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 07:41 UTC, zero-24 requested changes, later dismissed

2021-03-24 07:41 UTC, zero-24 commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> + * @copyright   (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
Should be 2021 right?


```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-03-24 07:43 UTC, zero-24 commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> +	 * @return  void
```suggestion
	 * @return  void
  *
  * @since  __DEPLOY_VERSION__
```

2021-03-24 07:45 UTC, zero-24 commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> +			if ($user->id == $id)
```suggestion
			if ($user->id === $id)
```

2021-03-24 07:45 UTC, zero-24 commented on administrator/components/com_users/src/Controller/UserController.php
> +		if (isset($data[$key]) && $this->app->getIdentity()->id == $data[$key])
```suggestion
		if (isset($data[$key]) && $this->app->getIdentity()->id === (int) $data[$key])
```

2021-03-24 07:45 UTC, joomdonation commented
Thanks Tobias. Committed the CS changes.

2021-03-24 07:48 UTC, joomdonation commented on administrator/components/com_users/src/Controller/UserController.php
> +		if (isset($data[$key]) && $this->app->getIdentity()->id == $data[$key])
Thanks for these suggestions. If you can confirm that $user->id is always return int as I asked before, I will commit these changes (I tested and it seems OK, just wanted to wait for HLeithner to confirm)

2021-03-24 07:49 UTC, richard67 commented
Up to now it was code style only changed after the tests, but if the above suggestions (type safe comparison, cast to int) will committed, too, then it will need new tests since these changes might change "behaviour" of the code.

2021-03-24 07:54 UTC, richard67 commented
Back to pending. Please test again. Thanks in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 07:56 UTC, rdeutz commented
I have tested this item :white_check_mark: successfully on 2e92be8bd6ee04d386f470166884e8e85d978d0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 15:11 UTC, Quy commented on administrator/components/com_users/src/Controller/UserController.php
> +		$task  = $this->getTask();
```suggestion
		$task   = $this->getTask();
```

2021-03-24 15:16 UTC, richard67 commented
Previous test by @rdeutz is still valid because the commit after that was just a small code style change. I've restored the result in the issue tracker so it's correctly counted there and here.

2021-03-24 17:00 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 688f66a57ad9dab25d64364bf0ca17e23e67e63b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 17:00 UTC, jwaisner commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 17:11 UTC, SharkyKZ commented
I have tested this item :red_circle: unsuccessfully on 688f66a57ad9dab25d64364bf0ca17e23e67e63b<br /><br />Doesn't work with PDO.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 17:50 UTC, richard67 commented
Back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 18:00 UTC, alikon commented
setting back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-24 18:02 UTC, alikon commented
got this on pdo with 8.0.23
![Screenshot from 2021-03-24 19-01-11](https://user-images.githubusercontent.com/181681/112361135-5c551500-8cd3-11eb-81ea-370e992a0c38.png)

2021-03-24 19:44 UTC, rdeutz commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> +			if ($user->id === $id)
change to (int $user->id === $id) should fix the PDO problem

2021-03-24 19:44 UTC, HLeithner commented on administrator/components/com_users/src/Dispatcher/Dispatcher.php
> +		if (in_array($task, $allowedTasks) || ($view === 'user' && $layout == 'edit'))
```suggestion
		if (in_array($task, $allowedTasks, true) || ($view === 'user' && $layout === 'edit'))
```

2021-03-25 05:03 UTC, joomdonation commented
So the problem is that PDO return **string data type** for User ID but MySQLi return **int data type** . I was not sure about it and that was the reason I used weak comparison at the begininging

I made modification as suggested. I tested it myself with both PDO and MySQLi, it is working well now. Please test it again. Thanks all for reviewing and testing and sorry for taking so much time from you for this PR.

2021-03-25 08:48 UTC, rdeutz commented
I have tested this item :white_check_mark: successfully on f47df469e716d3a35210955746e6e9eaea5a8095<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-25 09:36 UTC, joomdonation commented
@brianteeman Could you please re-test this PR?

2021-03-25 20:59 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on f47df469e716d3a35210955746e6e9eaea5a8095<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-25 21:00 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32771">issues.joomla.org/tracker/joomla-cms/32771</a>.</sub>

2021-03-26 00:01 UTC, wilsonge commented
Thankyou so much guys. Much appreciated!

2021-03-26 00:02 UTC, merged