Ensure template logo has relative links regardless of SEF Settings
joomla/joomla-cms pull request #32822
Opened 2021-03-23 11:43 UTC by PhilETaylor

Pull Request for Issue Closes #31989
Replacement PR for https://github.com/joomla/joomla-cms/pull/32714

### Summary of Changes

Prepend templatePath with Uri:root to Ensure templatePath is always absolute and not a broken relative url

### Testing Instructions

See #31989

Visit frontend **, click a menu link in the left menu to get to an article**
Note that the CASSIOPEIA logo (white text on blue background) is present

In Joomla Admin disable the "System - SEF" plugin

Refresh your article page on the frontend

Note the logo is now a broken image

### Actual result BEFORE applying this Pull Request

paths are relative, and therefore image doesn't display when non-SEF mode and not at / (ie. in a sub folder or not on the home page where url contains /index.php/path/to  like http://127.0.0.1:4444/index.php/component/users/reset?Itemid=101)

### Expected result AFTER applying this Pull Request

regardless of SEF plugin status, the image and assets loaded from $templatePath load correctly. 

### Documentation Changes Required

none

2021-03-23 13:03 UTC, dgrammatiko requested changes

2021-03-23 13:03 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +	$logo = '<img src="' . Uri::root(true) . '/' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
Actually, there's an API for this:
```php

$logo = HTMLHelper::_('image', 'logo.svg', $sitename, ['class' => 'logo d-inline-block'], true, -1);
```

2021-03-24 02:04 UTC, joomdonation commented on templates/cassiopeia/index.php
> +	$logo = '<img src="' . Uri::root(true) . '/' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
@dgrammatiko Do we really need to use API for this? I think the code is fine as it is now. It works and save the system from having to find the logo from multiple places.

2021-03-24 02:10 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +	$logo = '<img src="' . Uri::root(true) . '/' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
No, but it will be easier if we ever want to transition this template to the new mode, child templates

2021-03-24 02:14 UTC, joomdonation commented on templates/cassiopeia/index.php
> +	$logo = '<img src="' . Uri::root(true) . '/' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
Hmm, I don't know about child templates yet, so I will leave it to @PhilETaylor for making the suggested change or not.

2021-03-24 02:14 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +	$logo = '<img src="' . Uri::root(true) . '/' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
Also due to reverse order (template wins) I think there are no extra lookups ( although I might be wrong on this one, it’s been some time since I looked at that code)

2021-03-24 02:18 UTC, joomdonation commented on templates/cassiopeia/index.php
> +	$logo = '<img src="' . Uri::root(true) . '/' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
I haven't looked carefully enough, too. But since the template wins logic, I see no benefit for making API call and would leave it as how it is now (except something effect child templates logic as you mentioned)

2021-03-24 02:26 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +	$logo = '<img src="' . Uri::root(true) . '/' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
The point is that if we ever convert this to inheritable (eg support child templates) the hardcoded path will be broken, but thus my comment in the first place

2021-03-24 19:59 UTC, PhilETaylor commented
Switched to Joomla API with preceding `/` to make it actually work.

2021-03-24 20:15 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +	$logo = HTMLHelper::_('image', '/' . $templatePath . '/images/logo.svg', $sitename, ['class' => 'logo d-inline-block'], true, -1);
This part `'/' . $templatePath . '/images/logo.svg'` should be the same as `'logo.svg'` but for that to work the last argument needs to switch from `-1` to `0`

2021-03-24 20:19 UTC, PhilETaylor commented on templates/cassiopeia/index.php
> +	$logo = HTMLHelper::_('image', '/' . $templatePath . '/images/logo.svg', $sitename, ['class' => 'logo d-inline-block'], true, -1);
Done.

2021-03-24 20:22 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 2898ee997616ab017c81873fc2ac0f338b401096<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32822">issues.joomla.org/tracker/joomla-cms/32822</a>.</sub>

2021-03-24 20:23 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +	$logo = HTMLHelper::_('image', '/' . $templatePath . '/images/logo.svg', $sitename, ['class' => 'logo d-inline-block'], true, -1);
Thanks

2021-03-24 21:20 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 2898ee997616ab017c81873fc2ac0f338b401096<br /><br />Tested successfully in Beta8-dev of 24 March in Wampserver 3.2.4 using PHP 8.0.2.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32822">issues.joomla.org/tracker/joomla-cms/32822</a>.</sub>

2021-03-24 21:37 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32822">issues.joomla.org/tracker/joomla-cms/32822</a>.</sub>

2021-03-25 09:34 UTC, merged

2021-03-25 09:34 UTC, drmenzelit commented
Thanks!