[4.0] Moving menu lookup for tags from Router helper to actual router
joomla/joomla-cms pull request #33208
Opened 2021-04-20 20:38 UTC by Hackwar

### Summary of Changes
This moves the menu lookup for tags from the router helper to the actual router. This improves the tag routing a little bit, especially allowing for menu items with more than one tag. However lookup of multi-level tags still doesn't work and would require something like the CategoryNode class for tags, which we don't have and wont have for 4.0. 

### Testing Instructions
After applying this PR, the generated URLs shouldn't have changed.

2021-04-20 20:46 UTC, richard67 commented
Failing unit tests in drone and appveyor are not related to this PR but to the 4.0-dev branch at the time when this PR was created based on it. It will be fixed in the 40-dev branch with #33207 and if that is merged, this PR should be updated to that so we can see if unit tests pass here.

2021-04-25 10:56 UTC, joomdonation commented
I have tested this item :red_circle: unsuccessfully on cb9b7604aae4610dc58102fa050fd45134e06796<br /><br />I tested this using sample blog data. Link to a tag has this format http://localhost/joomla4/index.php/component/tags/millions?Itemid=101 and it causes the error (something like NomenuRules which you fixed sometime ago)

I wonder why we could not use same Router structure with other extensions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33208">issues.joomla.org/tracker/joomla-cms/33208</a>.</sub>

2021-04-25 12:15 UTC, Hackwar commented
The problem is, that the tags don't use simple IDs, but also arrays of IDs. There is actually a chunk of issues here, but unfortunately out of scope for 4.0.

2021-04-25 12:20 UTC, joomdonation commented
@Hackwar So what we can do with this PR ? Close it now and re-visit it later? Or leave it open and you will find a solution for this later?

2021-04-25 17:25 UTC, Hackwar commented
I'll have another look at this. If it is not merged into J4, we will have to look if we can do this in a b/c way in 4.1 or similar.

2021-08-17 10:07 UTC, Babofett commented on components/com_tags/src/Service/Router.php
> +			$component  = ComponentHelper::getComponent('com_tags');
You forgot to refer to the ComponentHelper.
e.g. Line 21 `use Joomla\CMS\Component\ComponentHelper;`

2021-08-17 10:10 UTC, Babofett requested changes
You need to refer to the ComponentHelper in Router.php
e.g. Line 21 `use Joomla\CMS\Component\ComponentHelper;`

2021-08-19 19:42 UTC, PhilETaylor commented on components/com_tags/src/Service/Router.php
> +	 * @since 4.1
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-08-19 19:42 UTC, PhilETaylor commented on components/com_tags/src/Service/Router.php
> +	 * @since  4.0
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-08-19 19:43 UTC, PhilETaylor commented on components/com_tags/src/Service/Router.php
> +	 * @since   4.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-19 19:43 UTC, PhilETaylor commented on components/com_tags/src/Service/Router.php
> +	 * @since   4.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-26 14:47 UTC, joomdonation commented
I just tested it quickly to see if it solves the issue https://github.com/joomla/joomla-cms/issues/35382 but it is still not working yet.

2021-09-19 19:22 UTC, DonPedro34 commented
Any hope that this will be fixed soon?
https://issues.joomla.org/tracker/joomla-cms/35382

2022-06-27 13:08 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2022-10-21 09:25 UTC, closed without merging

2022-10-21 09:26 UTC, Hackwar commented
This isn't going anywhere. I'm closing this one and will maybe start over sometime soon... or something like that...