[4] Empty state for com_redirect
joomla/joomla-cms pull request #33384
Opened 2021-04-27 20:00 UTC by PhilETaylor

### Summary of Changes

Slightly different this time as this one needs a NEW and a BULK IMPORT action in the toolbar, the latter requiring a modal

<img width="1053" alt="Screenshot 2021-04-27 at 20 57 54" src="https://user-images.githubusercontent.com/400092/116305345-8fd80300-a79b-11eb-9d40-f214fef7b40a.png">

### Testing Instructions

Also test that bulk import still works please. (It "Works on my computer")

2021-04-27 21:48 UTC, Quy commented on administrator/language/en-GB/com_redirect.ini
> +COM_REDIRECT_EMPTYSTATE_BUTTON_ADD="Add new Link"
```suggestion
COM_REDIRECT_EMPTYSTATE_BUTTON_ADD="Add new link"
COM_REDIRECT_EMPTYSTATE_CONTENT="This component is used for redirecting URLs for web pages that no longer exist on your website to web pages that are working."
COM_REDIRECT_EMPTYSTATE_TITLE="Redirects: Links"
```

2021-04-28 00:46 UTC, Quy commented on administrator/language/en-GB/com_redirect.ini
> +COM_REDIRECT_EMPTYSTATE_CONTENT="This component is used for redirecting URLs for web pages that no longer exist on your website to web pages that are working."
```suggestion
COM_REDIRECT_EMPTYSTATE_CONTENT="Redirect URLs for web pages that no longer exist on your website to web pages that are working."
```
Simplify?

2021-04-28 02:56 UTC, PhilETaylor commented on administrator/language/en-GB/com_redirect.ini
> +COM_REDIRECT_EMPTYSTATE_CONTENT="This component is used for redirecting URLs for web pages that no longer exist on your website to web pages that are working."
I just copied and pasted from docs.Joomla.org haha

2021-04-28 16:19 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 9d2f350c1e79036e0b9127c46e8dbf9a779ddb88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33384">issues.joomla.org/tracker/joomla-cms/33384</a>.</sub>

2021-04-28 17:36 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 9d2f350c1e79036e0b9127c46e8dbf9a779ddb88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33384">issues.joomla.org/tracker/joomla-cms/33384</a>.</sub>

2021-04-28 17:37 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33384">issues.joomla.org/tracker/joomla-cms/33384</a>.</sub>

2021-04-28 17:54 UTC, brianteeman requested changes

2021-04-28 17:54 UTC, brianteeman commented on administrator/components/com_redirect/tmpl/links/emptystate.php
> + * @subpackage  com_checkin
```suggestion
 * @subpackage  com_redirect
```

2021-04-30 08:39 UTC, merged

2021-04-30 08:39 UTC, drmenzelit commented
Thanks