Empty State for System-> Discover
joomla/joomla-cms pull request #33400
Opened 2021-04-28 22:48 UTC by PhilETaylor

Pull Request for Issue # .

### Summary of Changes

Empty state for when no extensions are discovered.

MOST OF THE TIME you will expect to see the Empty State. Its rare to see extensions needing discovering. This is the opposite of most components in Joomla admin. 

### Testing Instructions

Apply PR

Load System -> discover,

See Empty State 

click discover... or the button in the middle

Note new message. Nothing found. 

upload a plugin/extension manually into its right place using FTP (or copy and paste on your local machine) 

Load System -> discover, click discover... 

See you see the old screen where you can install the extension

### Actual result BEFORE applying this Pull Request

<img width="1600" alt="Screenshot 2021-04-28 at 23 46 50" src="https://user-images.githubusercontent.com/400092/116481896-05b39b80-a87c-11eb-99dd-88b6395a89c6.png">

### Expected result AFTER applying this Pull Request

<img width="1329" alt="Screenshot 2021-04-28 at 23 43 50" src="https://user-images.githubusercontent.com/400092/116481837-e6b50980-a87b-11eb-8117-f48042a29ca8.png">

When you click either discover button you get a new message, or redirected to the list of discovered extensions to install (as normal) 

<img width="1341" alt="Screenshot 2021-04-28 at 23 43 56" src="https://user-images.githubusercontent.com/400092/116481838-e87ecd00-a87b-11eb-9e2b-7ece2371a4be.png">

### Documentation Changes Required

none

2021-04-28 22:49 UTC, PhilETaylor commented
And yes I hate the title and sentences - please suggestion new ones if you dont like them too. I'll not be offended.

2021-04-28 23:02 UTC, Quy commented on administrator/language/en-GB/com_installer.ini
> +COM_INSTALLER_EMPTYSTATE_TITLE="You have no discovered extensions to install"
```suggestion
COM_INSTALLER_EMPTYSTATE_TITLE="You have no discovered extensions to install."
```

2021-04-29 00:16 UTC, Quy commented on administrator/components/com_installer/src/View/Discover/HtmlView.php
> +	public $isEmptyState = false;
```suggestion
	private $isEmptyState = false;
```

2021-04-29 09:29 UTC, brianteeman requested changes

2021-04-29 09:29 UTC, brianteeman commented on administrator/language/en-GB/com_installer.ini
> +COM_INSTALLER_EMPTYSTATE_CONTENT="We have not found any extension on your site, that have not gone through the normal installation process."
```suggestion
COM_INSTALLER_EMPTYSTATE_CONTENT="We have not found any extensions on your site that have not gone through the normal installation process."
```

pluralise and remove comma

Not sure about the "We .." as that is not consistent with any other message on the site. Who is we?

2021-04-29 09:38 UTC, PhilETaylor commented on administrator/language/en-GB/com_installer.ini
> +COM_INSTALLER_EMPTYSTATE_CONTENT="We have not found any extension on your site, that have not gone through the normal installation process."
[Like I said](https://github.com/joomla/joomla-cms/pull/33400#issuecomment-828831156) "And yes I hate the title and sentences too! - please suggestion new ones if you dont like them too. I'll not be offended."

2021-04-29 14:39 UTC, Quy commented on administrator/components/com_installer/tmpl/discover/emptystate.php
> +$user = Factory::getApplication()->getIdentity();
Delete?

2021-04-29 14:39 UTC, Quy commented on administrator/components/com_installer/tmpl/discover/emptystate.php
> +$displayData['createURL'] = 'index.php?option=com_installer&task=discover.refresh&' . Session::getFormToken() . '=1';
Combine with the above array?

2021-04-29 14:41 UTC, PhilETaylor commented on administrator/components/com_installer/tmpl/discover/emptystate.php
> +$displayData['createURL'] = 'index.php?option=com_installer&task=discover.refresh&' . Session::getFormToken() . '=1';
done

2021-04-29 14:41 UTC, PhilETaylor commented on administrator/components/com_installer/tmpl/discover/emptystate.php
> +$user = Factory::getApplication()->getIdentity();
done

2021-04-29 16:41 UTC, Quy commented on administrator/language/en-GB/com_installer.ini
> +COM_INSTALLER_EMPTYSTATE_CONTENT="We have not found any extensions on your site that have not gone through the normal installation process."
The title states that there are no discovered extensions to install. There is no need to repeat it. Let's reuse the text from this string.

> COM_INSTALLER_MSG_DISCOVER_DESCRIPTION="Discover extensions that have not gone through the normal installation process."

2021-04-29 16:46 UTC, PhilETaylor commented on administrator/language/en-GB/com_installer.ini
> +COM_INSTALLER_EMPTYSTATE_CONTENT="We have not found any extensions on your site that have not gone through the normal installation process."
Done

2021-04-29 17:04 UTC, Quy commented on administrator/components/com_installer/src/Model/DiscoverModel.php
> +		$sql->where($this->_db->quoteName('state') . ' = ' . $this->_db->quote('-1'));
```suggestion
		$sql->where($this->_db->quoteName('state') . ' = -1'));
```

2021-04-29 17:09 UTC, Quy commented on administrator/components/com_installer/src/Model/DiscoverModel.php
> +		$sql->where($this->_db->quoteName('state') . ' = -1'));
```suggestion
		$sql->where($this->_db->quoteName('state') . ' = -1')));
```

2021-04-29 17:10 UTC, PhilETaylor commented on administrator/components/com_installer/src/Model/DiscoverModel.php
> +		$sql->where($this->_db->quoteName('state') . ' = -1'));
nope - other way - needs less :)

2021-04-29 17:10 UTC, Quy commented on administrator/components/com_installer/src/Model/DiscoverModel.php
> +		$sql->where($this->_db->quoteName('state') . ' = -1')));
```suggestion
		$sql->where($this->_db->quoteName('state') . ' = -1');
```

2021-04-29 17:22 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 68479a232edd7d7e8638c143395249b21043bbee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33400">issues.joomla.org/tracker/joomla-cms/33400</a>.</sub>

2021-05-03 12:59 UTC, drmenzelit commented
I have tested this item :white_check_mark: successfully on 68479a232edd7d7e8638c143395249b21043bbee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33400">issues.joomla.org/tracker/joomla-cms/33400</a>.</sub>

2021-05-03 13:45 UTC, PhilETaylor commented
This has conflicts (because com_installer has multiple empty states, and thus has language string conflicts) and cannot be merged just yet - I'll fix it once enough coffee has been injected into my veins.

2021-05-03 17:12 UTC, PhilETaylor commented
Conflicts resolved, merged in from 4.0-dev and ready for testing again. Thanks.

2021-05-07 09:40 UTC, PhilETaylor commented
Hey @wilsonge If you are thinking of cutting another Joomla 4 beta very shortly can we quickly get this one and the other one I'll ping you merged, these are the last 2 Empty States and without them the feature is not yet fully implemented :-) Thanks.

2021-05-07 09:50 UTC, alikon commented
missed from my radar  ... due to the  storm :smile:

2021-05-07 09:51 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 2b9078b2bbfa49cf7bfe4a698103b274028a7dd0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33400">issues.joomla.org/tracker/joomla-cms/33400</a>.</sub>

2021-05-07 09:54 UTC, alikon commented
fields and field groups are in your radar @PhilETaylor  ??

2021-05-07 09:58 UTC, PhilETaylor commented
> fields and field groups are in your radar @PhilETaylor ??

They are hard, due to the additional context and dropdown needed to make it make sense as an empty state

2021-05-07 09:59 UTC, PhilETaylor commented
>  ... due to the storm

We had the french try to invade our island yesterday.. such fun...

2021-05-07 13:51 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 2b9078b2bbfa49cf7bfe4a698103b274028a7dd0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33400">issues.joomla.org/tracker/joomla-cms/33400</a>.</sub>

2021-05-07 13:51 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33400">issues.joomla.org/tracker/joomla-cms/33400</a>.</sub>

2021-05-07 14:05 UTC, merged

2021-05-07 14:05 UTC, Quy commented
Thanks you!!!