[4.0] Smart Search: Adding index to taxonomy table
joomla/joomla-cms pull request #33746
Opened 2021-05-10 15:44 UTC by Hackwar

During some testing, the taxonomy table of the Smart Search component showed to be a performance problem, especially on sites with lots of taxonomies. The index being added in here improves this performance enormously. There isn't really any way to test this for the regular users. This needs a codereviews.

2021-05-23 23:00 UTC, richard67 requested changes

2021-05-23 23:00 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-05-10.sql
> +CREATE INDEX "#__finder_taxonomy_idx_level" on "#__finder_taxonomy" ("level");
```suggestion
CREATE INDEX "#__finder_taxonomy_level" on "#__finder_taxonomy" ("level");
```
The index name in the update SQL script has to be the same as in the extension.sql for new installations, otherwise you get an endless loop of DB errors fo be fixed in the database checker.

2021-05-24 09:13 UTC, richard67 approved these changes

2021-05-24 09:23 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 0a63748349720380128903fc0f75ae16072acd27<br /><br />Code review is not enough. I tested also that updating a current 4.0-dev to the custom update URL built by drone for this PR works without SQL errors and that the index has been created, on both MySQL and PostgreSQL. The reason is that we don't have automated tests for that yet. That the SQL for new installations doesn't have syntax errors is already checked with the automated system tests.

I did not test if the new index improves performance, but I think it will do that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33746">issues.joomla.org/tracker/joomla-cms/33746</a>.</sub>

2021-05-24 18:40 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 0a63748349720380128903fc0f75ae16072acd27<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33746">issues.joomla.org/tracker/joomla-cms/33746</a>.</sub>

2021-05-24 18:41 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33746">issues.joomla.org/tracker/joomla-cms/33746</a>.</sub>

2021-05-24 18:41 UTC, alikon commented
i'll let someonelse to set rtc 
...if my code review still value :rofl:

2021-05-26 11:55 UTC, merged