Difference in height of visibility button and password input #33823
joomla/joomla-cms pull request #33824
Opened 2021-05-12 15:34 UTC by deveshprasad

Pull Request for Issue #33823 

### Summary of Changes

Difference in the height of input and visibility button
Solved by adding a bootstrap bottom margin to 0.

### Testing Instructions

Go to the main joomla web page and view it on mobile view.

`<button type="button" class="btn btn-primary js-pstats-btn-allow-always m-1"><?php echo Text::_('PLG_SYSTEM_STATS_BTN_SEND_ALWAYS'); ?></button> <button type="button" class="btn btn-primary js-pstats-btn-allow-once m-1"><?php echo Text::_('PLG_SYSTEM_STATS_BTN_SEND_NOW'); ?></button> <button type="button" class="btn btn-primary js-pstats-btn-allow-never m-1" style="margin:0px"><?php echo Text::_('PLG_SYSTEM_STATS_BTN_NEVER_SEND'); ?></button>`

### Actual result BEFORE applying this Pull Request

![10 05 2021_20 55 28_REC](https://user-images.githubusercontent.com/63739986/118001860-bd5ca900-b364-11eb-8445-9e68e34553d8.png)

### Expected result AFTER applying this Pull Request

![11 05 2021_21 10 38_REC](https://user-images.githubusercontent.com/63739986/118001802-b170e700-b364-11eb-9c96-ca7610d1a2b3.png)

### Documentation Changes Required

No changes in the documentation.

2021-05-12 15:55 UTC, rjharishabh commented
I have tested this item :red_circle: unsuccessfully on 48a28941bd8e2998b334a0291873f7a69da954cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33824">issues.joomla.org/tracker/joomla-cms/33824</a>.</sub>

2021-05-12 15:57 UTC, rjharishabh commented
It's the same as before 
![erro](https://user-images.githubusercontent.com/61203226/118006124-a029d980-b368-11eb-9e4f-149da1544332.JPG)

And please change your branch to something other, not 4.0-dev

2021-05-12 16:51 UTC, rjharishabh requested changes
Please change bottom-margin to 0
See below comment

2021-05-12 16:51 UTC, brianteeman commented
The problem is caused by
```
@media (max-width: 767.98px)
.btn {
    margin-bottom: .25rem;
}
```

2021-05-12 17:51 UTC, rjharishabh approved these changes

2021-05-12 18:39 UTC, rjharishabh commented
Sorry, it's by mistake approved, 
So, please don't consider these changes approved

2021-05-12 19:54 UTC, deveshprasad commented
I followed the GSOC guidelines to change the branch to 4.0-dev, so which branch should I choose?

2021-05-12 20:27 UTC, richard67 commented
> I followed the GSOC guidelines to change the branch to 4.0-dev, so which branch should I choose?

@deveshprasad The branch is ok. It would have been better if you had created a new, extra branch for this PR based on the 4.0-dev branch, but as long as you don't make other PR's for other issues, it works like now, using your 4.0-dev branch.

Later when this PR is ok and tested and merged, the best is you delete your 4.0-dev branch and create it again based on the 4.0-dev branch of the CMS. Otherwise, if you don't do that and later create another PR based on your 4.0-dev branch which still contains your changes from this PR here, the other, future PR will be wrong.

But for now that should not be a problem.

2021-05-12 21:05 UTC, rjharishabh commented
Here you should change margin-bottom to 0

https://github.com/joomla/joomla-cms/blob/9653158d1eb14190f66f68233fc44763dd67d884/templates/cassiopeia/scss/vendor/bootstrap/_buttons.scss#L52

2021-05-12 21:12 UTC, brianteeman commented
> Here you should change margin-bottom to 0

1. If the intent is to remove the margin-bottom at that size then you should just remove the entire class not set it to 0
2. Whenever you remove something you should see why it was there in the first place. Everything has a purpose so you wouldnt want to break that with a change

The PR that introduced that code was #32697

2021-05-12 21:13 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on 48a28941bd8e2998b334a0291873f7a69da954cb<br /><br />Breaks all buttons see comments<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33824">issues.joomla.org/tracker/joomla-cms/33824</a>.</sub>

2021-05-12 21:31 UTC, rjharishabh commented
Then it can be corrected by add `mb-0` to it's markup. 
That's in password. php file.

2021-05-12 21:44 UTC, brianteeman commented
That would set a margin bottom at all screen sizes. Is that what you want to do?

2021-05-13 09:58 UTC, deveshprasad commented
So if the bootstrap margin is not the correct way and we should remove the entire class, and should directly set it to 0.
I tried applying bootstrap margin individually ( .btn) so that it won't affect the other buttons. But this is still not the correct way, 
so can we add a new class on this button and which has its margin in the CSS files equal to 0?

I have a similar issue which I solved with help of bootstrap, but if m-1 is not the correct way as it works on all responsive screens
then can I add a new class because removing the current one will remove all those styling related with that class.

Similar issue:

![1](https://user-images.githubusercontent.com/63739986/118110185-bb93f380-b3ff-11eb-9e98-4674be7701e5.png)

2021-05-13 10:50 UTC, rjharishabh commented
Same issue at the change password page in the frontend.
![change-pass](https://user-images.githubusercontent.com/61203226/118115626-d322aa80-b406-11eb-8194-5966175745b6.JPG)

If we add `mb-0` to this line then both problem will be solved, It's not affecting other screen sizes

https://github.com/joomla/joomla-cms/blob/85d42d25279aac2cfbe2d69a7568234d04c6a40b/layouts/joomla/form/field/password.php#L156

2021-05-13 20:42 UTC, deveshprasad commented
![13 05 2021_15 45 42_REC](https://user-images.githubusercontent.com/63739986/118184496-0e4dc980-b459-11eb-870d-165e354d4121.png)
![13 05 2021_20 50 17_REC](https://user-images.githubusercontent.com/63739986/118184510-1148ba00-b459-11eb-9e2f-d49bf7110bc6.png)


Similar issue  on mobile view .
If we want to target one particular screen without affecting other screen size, and by using bootstrap we can use 
mb-md-0 for the previous issue and mt-md-1 for this issue ?

2021-05-15 10:55 UTC, closed without merging