[4.0] download key tip
joomla/joomla-cms pull request #34419
Opened 2021-06-05 14:30 UTC by brianteeman

A tooltip is displayed for a missing download key that is not correct.

### Testing Instructions
Install this fake [ "paid download" ](http://updates.myoldsite.com/file_null-1.0.zip)extension Null file. Thanks @nikosdion for the file.

Go to System > Update > Extensions

Observe the alert and the tooltip

![image](https://user-images.githubusercontent.com/1296369/120894928-b4cd5a80-c612-11eb-92b8-8a13abac695d.png)

The tooltip should not be displayed here as its the tooltip for the update sites view and the instructions will not work on this page.

This PR removes the tooltip from this page. I chose not to add a new tooltip with the correct information as it would just be a duplicate of the alert.

2021-06-05 14:44 UTC, nikosdion commented
Or we could simply add `data-bs-placement="bottom"` to have the popover appear below the Badge.

The point of the popover is that newcomers to Joomla do not understand that the Download Key is required to install the update. Yeah, sure there's the warning at the top but experience says they don't ever read it. The point of the popover is that they are far more likely to move their pointer over the red text than look somewhere else on the page to understand what the heck is that message.

I also stand by my statement nearly 2 years prior that the Update Site edit page should allow developers to display a custom message (via a translation screen) to direct the user as to where their Download Key can be found. The Joomla interface, as it is implemented right now, expect the user to _know_ things. My experience doing support with paying customers is that they do not understand the relation between purchasing something and having to not only install it but also type something somewhere for updates to work. Even more so when they've hired a site integrator to build their site and 6 to 12 months later they try to take over maintenance of the site and have no idea what is going on. Giving folks some hints about what they need to do helps A LOT. I observed an ~80% reduction in support tickets regarding download keys and failed updates when I started nagging people to enter their Download IDs and told them where to find them on my site.

2021-06-05 15:03 UTC, brianteeman commented
Nik

read the tooltip. on this **update extensions** page the text is not correct. it is correct on the **update sites** page where it is also displayed.

It says click on the update sites title. This view does not have an update site title or anything that is clickable
![image](https://user-images.githubusercontent.com/1296369/120895967-3c1ccd00-c617-11eb-97c0-2edb2b35b57d.png)

The alert that is displayed on this page contains a link that takes you to the update sites page where the update site title exists and is clickable.

Happy to have a tooltip on this page but the text I am deleting actually creates issues instead of your intention of solving them

2021-06-05 15:28 UTC, nikosdion commented
You make a very fair point that the tooltip content is misleading and its placement is awkward. I agree. You can have a different tooltip content there, e.g. “Updates for this extension will not work until you enter its Download Key in the Update Sites page. Please check the message above the list of updates for instructions.”

However, the tooltip and its content are implementation details which are up for discussion. Let's first focus on why a tooltip is there in the first place.

Joomla's extensions update process is idiosyncratic. It diverges from both update models users are familiar with: update in the software (everything is managed in the software being updated) and updates as part of a centralised software management facility / App Store (where the user needs to do nothing and updates appear “automatically”). It is very reasonable that the average user who's not overly familiar with Joomla's update model can't make the connection between the badge, the top of the page, the Update Sites page, the Download Key and something on my or any other 3PD's site. This makes updates look scary, opaque and burdensome. We need to hold the user's hand and walk them through the process.

Here's how I envisioned it about two years ago:

* The badge is strategically placed in proximity to the checkbox they need to click to update the software. It also stands out.
* They will very likely hover over the badge because it's a Red Angry Thing. The tooltip will tell them to look at the top of the page.
* The top of the page tells them to enter the Download Key and has a link. Hopefully, they click on it.
* They see the list of update sites which don't have a Download Key. If they're lost, they will hover over the Red Angry Thing there.
* That tooltip tells them to click on the Update Site title and enter the Download Key.
* (missing step) The Update Site edit page tells them where to get the Download Key from.
* They paste the Download Key and click on Save & Close.
* Now they can start over the update process.

This process is multistep but the steps lead from one to the next. This makes people think it's easy since, as you know, clarity is what people prefer over brevity.

I am not particularly attached to having a tooltip. If there's another way, e.g. making the Red Angry Thing a link, I actually prefer it; tooltips require interaction which poses a discoverability issue. They are also not very accessible which is another problem. The point is, how can we hold the user by the hand and help them navigate a scary and unfamiliar process? I am open to suggestions as long as it doesn't require the user to magically make a connection between two unrelated parts of the page because I know they won't and that will be a problem I will have to provide support for 😉

2021-06-05 15:32 UTC, brianteeman commented
the angry red text can easily be a link if thats what you want. I just wanted to remove the incorrect instructions in the tooltip

2021-06-05 15:35 UTC, nikosdion commented
I'd prefer it a link, if it shows up legible. I believe the link should have the `text-decoration-none` class as well to prevent the entire badge from becoming underlined and hard to read. I can't remember if two years ago I didn't know about this class or if it didn't exist in BS4.

2021-06-05 15:40 UTC, brianteeman commented
easy enough - almost done

2021-06-05 15:51 UTC, brianteeman commented
Changed to a link **but** need a little assistance making the link work and not give a direct access is not allowed

2021-06-05 22:59 UTC, brianteeman commented
All changes made as requested - please test

2021-06-06 04:04 UTC, Abernyte-Git commented
I have tested this item :white_check_mark: successfully on 8f1ecdd371baa7d5f2c48c4f3d49149796ec1b2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-06-06 05:16 UTC, nikosdion requested changes
One minor change and we're good to go!

2021-06-06 05:16 UTC, nikosdion commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
Please change that to `$url = \Joomla\CMS\Router\Route::_('index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id);`. All administrator URLs in Joomla 4 are going through the URL router which addresses some issues with less common server setups and/or accidental redirections to the site's front-end. In the future we might even see SEF URLs in the backend.

2021-06-06 05:36 UTC, joomdonation commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
Actually, it could be shorter because we have `use Joomla\CMS\Router\Route;` at the top already

```php
$url = Route::_('index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id);
```

However, we should only display the link it the current user has edit permission instead of always displaying it like currently. I think you can copy this block of code (contains permission check) https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/tmpl/updatesites/default.php#L94-L104 and adjust it to have it works with your PR.

2021-06-06 05:51 UTC, nikosdion commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
It's not necessary. Only Super Users can install extensions — including updates — which means that they already have all permissions. 

We had changed that sometime around 2.5 if I recall correctly because installing extensions is a privileged operation with security repercussions. Back in the Joomla 1.5 days even Administrators could install extensions. I had demonstrated that I could create a "fake" component package which would create a Super User account under my control and then uninstall itself, leaving no trace (except the Super User). Using the same method I could also change an existing Super User and block all other Super Users, essentially performing a hostile takeover. This led to extensions being installable only by Super Users, the most trusted tier with absolute site access.

2021-06-06 06:35 UTC, joomdonation commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
@nikosdion As of right now, I can see that permission is configurable, so we can still configure permission to allow administrator to do anything.
![permission](https://user-images.githubusercontent.com/977664/120915062-e6eec300-c6cb-11eb-816e-fbe0f2ce6440.png)

But yes, the default permission when we install Joomla is that only Super Users can do these tasks.

2021-06-06 07:04 UTC, nikosdion commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
I can confirm that the hardcoded ACL checks have been removed and we now do regular ACL checks. I'll report this to the JSST. It's a major security issue.

2021-06-06 07:06 UTC, brianteeman commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
I will leave that to them and declare it out of scope for this PR

2021-06-06 08:34 UTC, brianteeman commented
This is ready for testing. The security comment is out of scope for this pr

2021-06-06 08:57 UTC, joomdonation commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
Could you please at least move the url inside the `Route::_`  call like this https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/tmpl/updatesites/default.php#L96 ? We do not want to define an one time use variable (the $url variable in this case).

2021-06-06 09:05 UTC, brianteeman commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
@joomdonation this is no different to lots of other code and it is much more readable

2021-06-06 09:12 UTC, joomdonation commented on administrator/components/com_installer/tmpl/update/default.php
> +											<?php $url = 'index.php?option=com_installer&task=updatesite.edit&update_site_id=' . (int) $item->update_site_id; ?>
I don't know if we code guideline but I'm sure we advice to not define onetime use variable on other PRs before. For readable, the code like this https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/tmpl/updatesites/default.php#L95-L101 looks good to me. But, that's personal preference.

2021-06-06 13:07 UTC, ChristineWk commented
Have the following current state (see screenshots).
Patch is enabled - Joomla 4.0.0-rc2-dev from today:

![screen shot 2021-06-06 at 13 05 51](https://issues.joomla.org/uploads/1/b9dd0d046606fdc314ca229795502bdd.jpg)

![screen shot 2021-06-06 at 13 06 06](https://issues.joomla.org/uploads/1/4eecca8883c52350d49006481968cbd7.jpg)

![screen shot 2021-06-06 at 13 06 24](https://issues.joomla.org/uploads/1/87e7d81fb48a448bd3a61a495b0cc264.png)


 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-06-06 14:36 UTC, brianteeman commented
something not right there as you are displaying a tooltip that has been removed

2021-06-06 14:46 UTC, Quy commented
Go to Update Sites to see tooltip.

2021-06-06 15:00 UTC, Abernyte-Git commented
I get the tooltip no longer showing as per expected at Update-Extension: Update but it does show at Extensions: Update Sites.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-06-14 10:24 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on 46ae40adede3046ca1c6b741bafd6e886d8ccddf<br /><br />Works like described! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-06-15 09:39 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 46ae40adede3046ca1c6b741bafd6e886d8ccddf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-06-15 09:39 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-06-15 09:41 UTC, richard67 commented
@joomdonation Setting RTC here because it does what it says. If you want, make a PR later with your suggested change after that one got merged.

2021-06-24 09:38 UTC, brianteeman commented
Updated to convert the tooltip on the update sites page

2021-06-25 15:08 UTC, Quy commented on administrator/components/com_installer/tmpl/updatesites/default.php
> +										<div role="tooltip" id="tip<?php echo $i; ?>">
See line 130. Duplicate `id`.

2021-07-07 11:04 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on c7d6deca113e025c2aa240db1224c8cb4602d112<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-07-13 06:00 UTC, brianteeman commented
would be great if this could get merged today before the language freeze

2021-08-09 17:17 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on c7d6deca113e025c2aa240db1224c8cb4602d112<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-08-09 17:18 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34419">issues.joomla.org/tracker/joomla-cms/34419</a>.</sub>

2021-08-09 17:19 UTC, richard67 commented
> would be great if this could get merged today before the language freeze

The PR doesn't have a language change anymore after it had been changed.

2021-08-25 20:18 UTC, merged

2021-08-25 20:18 UTC, Quy commented
Thanks!

2021-08-25 20:25 UTC, brianteeman commented
finally