[4.0] Replace double quote with single quote
joomla/joomla-cms pull request #34452
Opened 2021-06-07 16:54 UTC by Quy

### Summary of Changes
For consistency, replace double quote with singe quote.

### Testing Instructions
Code review.

2021-06-07 17:03 UTC, brianteeman commented on layouts/joomla/form/field/contenthistory.php
> +			. Text::_('JLIB_HTML_BEHAVIOR_CLOSE') . '</button>'
pretty sure that wont work

2021-06-07 17:16 UTC, alikon commented
what it is supposed to be standard? if there is 1

2021-06-07 17:19 UTC, chmst commented
In this case it is inside of a single quote and breaks it. A variable wich concatenated strings would be better than nested strings.

2021-06-07 17:31 UTC, Bakual commented on layouts/joomla/form/field/contenthistory.php
> +			. Text::_('JLIB_HTML_BEHAVIOR_CLOSE') . '</button>'
Why shouldn't it?

2021-06-07 17:31 UTC, Bakual commented
> what it is supposed to be standard? if there is 1

There is no official standard. 😄

2021-06-07 17:34 UTC, brianteeman commented on layouts/joomla/form/field/contenthistory.php
> +			. Text::_('JLIB_HTML_BEHAVIOR_CLOSE') . '</button>'
because its already inside a single quote isnt it?

2021-06-07 17:35 UTC, HLeithner commented
Always use single quote except you want to use fast rope which is faster but personally I don't variables within a text block, it's less readable without a syntax highlighter.

2021-06-07 17:45 UTC, richard67 commented on layouts/joomla/form/field/contenthistory.php
> +			. Text::_('JLIB_HTML_BEHAVIOR_CLOSE') . '</button>'
No. The previous row ends with a single quote and then the line changed here is appended to that with the dot at the beginning of the line.

2021-06-07 17:57 UTC, brianteeman commented on layouts/joomla/form/field/contenthistory.php
> +			. Text::_('JLIB_HTML_BEHAVIOR_CLOSE') . '</button>'
grrh github preview :(

2021-06-07 18:33 UTC, Bakual commented on layouts/joomla/form/field/contenthistory.php
> +			. Text::_('JLIB_HTML_BEHAVIOR_CLOSE') . '</button>'
Sometimes it's a bit tricky to read 😃

2021-06-08 06:05 UTC, alikon requested changes

2021-06-08 06:05 UTC, alikon commented on components/com_content/tmpl/article/default_links.php
> +										. \Joomla\CMS\Language\Text::_('JLIB_HTML_BEHAVIOR_CLOSE') . '</button>'
why not 
`use Joomla\CMS\Language\Text;`
and 
`Text::_('JLIB_HTML_BEHAVIOR_CLOSE')`

2021-06-08 07:08 UTC, Bakual commented on components/com_content/tmpl/article/default_links.php
> +										. \Joomla\CMS\Language\Text::_('JLIB_HTML_BEHAVIOR_CLOSE') . '</button>'
Because it's out of scope of this PR. Scope is "Replace double quote with single quote".

2021-06-08 19:45 UTC, alikon commented
I have tested this item :white_check_mark: successfully on e299c59bd9cc59f4b7a1411543fd7582b379bdc4<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34452">issues.joomla.org/tracker/joomla-cms/34452</a>.</sub>

2021-06-09 06:51 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on e299c59bd9cc59f4b7a1411543fd7582b379bdc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34452">issues.joomla.org/tracker/joomla-cms/34452</a>.</sub>

2021-06-09 06:52 UTC, joomdonation commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34452">issues.joomla.org/tracker/joomla-cms/34452</a>.</sub>

2021-06-09 07:17 UTC, merged

2021-06-09 07:17 UTC, drmenzelit commented
Thanks