[4.0] Crowdin comments
joomla/joomla-cms pull request #34671
Opened 2021-06-30 20:38 UTC by brianteeman

This PR updates the comments in language strings to a format that crowdin understands as requested by @conconnl https://github.com/joomla/core-translations/issues/1

Basically comments are moved to the end of the line in the *.ini

Note comments which are not for translators such as a comment used to indicate a grooup of strings have not been changed

2021-06-30 20:40 UTC, conconnl commented
@HLeithner & @zero-24 Please look at it and merge.

2021-06-30 22:43 UTC, HLeithner requested changes
Rest looks good

2021-06-30 22:43 UTC, HLeithner commented on administrator/language/en-GB/joomla.ini
> +JERROR_PARSING_LANGUAGE_FILE="&#160;: error(s) in line(s) %s" ; Keep this string on top
Don't think that makes sense for crowdin, it's more important that it's above the string  for developer

2021-06-30 22:43 UTC, HLeithner commented on administrator/language/en-GB/lib_joomla.ini
> +JERROR_PARSING_LANGUAGE_FILE="&#160;: error(s) in line(s) %s" ; Keep this string on top
Don't think that makes sense for crowdin, it's more important that it's above the string  for developer

2021-06-30 22:43 UTC, HLeithner commented on api/language/en-GB/joomla.ini
> +JERROR_PARSING_LANGUAGE_FILE="&#160;: error(s) in line(s) %s" ; Keep this string on top
Don't think that makes sense for crowdin, it's more important that it's above the string  for developer

2021-06-30 22:43 UTC, HLeithner commented on language/en-GB/joomla.ini
> +JERROR_PARSING_LANGUAGE_FILE="&#160;: error(s) in line(s) %s" ; Keep this string on top
Don't think that makes sense for crowdin, it's more important that it's above the string  for developer

2021-06-30 22:43 UTC, HLeithner commented on language/en-GB/lib_joomla.ini
> +JERROR_PARSING_LANGUAGE_FILE="&#160;: error(s) in line(s) %s" ; Keep this string on top
Don't think that makes sense for crowdin, it's more important that it's above the string  for developer

2021-07-01 05:21 UTC, brianteeman commented
Thanks for checking @HLeithner - perfectly correct and updated

2021-07-01 06:22 UTC, HLeithner requested changes

2021-07-01 06:22 UTC, HLeithner commented on administrator/language/en-GB/lib_joomla.ini
> + JERROR_PARSING_LANGUAGE_FILE="&#160;: error(s) in line(s) %s"
```suggestion
JERROR_PARSING_LANGUAGE_FILE="&#160;: error(s) in line(s) %s"
```

2021-07-01 14:46 UTC, Bakual commented
I think we looked into this already years ago and I know it didn't work at that time. I don't exactly remember the reasons however.
One was certainly that com_localise doesn't recognise those comments, but I think at that time Joomla couldn't handle them (language files broke I think). So please make sure everything related to language handling works when having the comments at the end (eg debugging languages)

2021-07-01 17:43 UTC, brianteeman commented
I'm just doing the work that was requested - no need for the thumbs

2021-07-02 07:54 UTC, brianteeman commented
> So please make sure everything related to language handling works when having the comments at the end (eg debugging languages)

Already tested before submitting a pr

2021-07-02 08:05 UTC, HLeithner approved these changes

2021-07-02 08:36 UTC, richard67 commented on language/en-GB/mod_footer.ini
> +MOD_FOOTER_LINE1="Copyright &#169; %date% %sitename%. All Rights Reserved." ; Note : %date% will be auto replaced by current year !Don't translate
Doesn't the same apply also on `%sitename%`?

2021-07-02 08:41 UTC, brianteeman commented on language/en-GB/mod_footer.ini
> +MOD_FOOTER_LINE1="Copyright &#169; %date% %sitename%. All Rights Reserved." ; Note : %date% will be auto replaced by current year !Don't translate
Probably - but beyond the scope of this PR which is just about changing where the existing comments are

2021-07-06 06:46 UTC, brianteeman commented
conflicts resolved

2021-07-09 23:32 UTC, obuisard commented
I have tested this item :white_check_mark: successfully on e56f3e427621926949fdc2d7ea2a1e99a16eb151<br /><br />The changes have no incidence in the outputs (like, for instance, creating an instance of the footer module)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34671">issues.joomla.org/tracker/joomla-cms/34671</a>.</sub>

2021-07-12 19:34 UTC, brianteeman commented
Conflicts resolved again.

Please either merge this PR **before the freeze** that was requested by the language co-ordinators or close it. Not wasting my time any more

2021-07-12 20:07 UTC, merged

2021-07-12 20:08 UTC, HLeithner commented
If tools around this PR breaks, we have to fix them or retire them if no longer used. Crowdin is our current translation platform and we should support it as good as we can.

2021-07-12 20:56 UTC, brianteeman commented
Thanks @HLeithner 

over to you now @conconnl