[4.0] Fix image previous for media form field
joomla/joomla-cms pull request #34833
Opened 2021-07-19 05:20 UTC by joomdonation

Pull Request for Issue #34810.

### Summary of Changes
The value stored in media form field (at least for image) contains adapter information (for example, images/headers/blue-flower.jpg#joomlaImage://local-images/headers/blue-flower.jpg?width=700&height=180), thus file_exist checks on this line https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/form/field/media.php#L77 return false and it results in preview image is not being displayed properly as described in the issue https://github.com/joomla/joomla-cms/issues/34810

This PR solves it by clean the value (removes adapter information) before file_exists check. A new method is added to MediaHelper class so that we can use on other places when it is needed (or even could be used by third party extensions developer - for example, we need to check and make sure the selected image is valid before resizing...)

### Testing Instructions
1. Look at https://github.com/joomla/joomla-cms/issues/34810, confirm the issue
2. Apply patch, confirm that the issue is sorted.

2021-07-19 05:58 UTC, richard67 commented
@joomdonation I guess it was the auto correct by the spell checker which changed „preview“ to „previous“ if the title here.

2021-07-19 06:00 UTC, joomdonation commented
@richard67 Thanks. Maybe it was a typo.

2021-07-19 07:35 UTC, dgrammatiko requested changes

2021-07-19 07:35 UTC, dgrammatiko commented on layouts/joomla/form/field/media.php
> +		$src = Uri::root() . $cleanValue;
```suggestion
		$src = Uri::root() . $value;
```

I would prefer if we keep the original value here, eg: `$src = Uri::root() . $value;` to. match the rendered preview source from JS land. Check my images in your issue

2021-07-19 07:37 UTC, joomdonation commented
@dgrammatiko Thanks. I didn't know that you need full value for preview

2021-07-19 07:42 UTC, dgrammatiko commented
>  I didn't know that you need full value for preview

Actually, we don't, but changing the $src in that point changes also the value in the input (and I guess we need the full value there). Basically edit a banner select a new image, save close, reopen and save (you lose the extra bits), this is what the proposed change prevents (I have no clue if it will be a problem, just did run the code in my head, so I might be wrong)

2021-07-19 07:45 UTC, joomdonation commented
>Actually, we don't, but changing the $src in that point changes also the value in the input 

Hmm. Change the $src variable won't change the value displaying in the input. The value in the input is still taken from $value variable, I think.

2021-07-19 07:46 UTC, dgrammatiko commented
> Hmm. Change the $src variable won't change the value displaying in the input. The value in the input is still taken from $value variable, I think.

You're right, I need more coffee, sorry

2021-07-19 07:50 UTC, joomdonation commented
Hmm. Somehow, the src of the preview image still use the unclean value. Maybe you set it automatically base on the value from input in the JS code?

2021-07-19 07:58 UTC, dgrammatiko commented
> Hmm. Somehow, the src of the preview image still use the unclean value. Maybe you set it automatically base on the value from input in the JS code?

Yes, the preview src is just the source + `Uri:root(true)`

https://github.com/joomla/joomla-cms/blob/703484715a3de6fff26a7566e1ff779b99fc4dab/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js#L212

Now that I think about it it's good to have the same URL both from PHP and JS otherwise there will be 2 downloads for the same image

2021-07-19 08:01 UTC, joomdonation commented
Main question here is we have source from php, then why do we need to calculate src js again?

2021-07-19 08:08 UTC, dgrammatiko commented
> Main question here is we have source from php, then why do we need to calculate src js again?

The update of the preview happens as part of the field's custom element initialization (`connectedCallback()`) and I guess the idea was to resolve external adapters here (but I doubt that the code does that). Anyways the line for triggering the JS resetting the preview html is here: 
https://github.com/joomla/joomla-cms/blob/703484715a3de6fff26a7566e1ff779b99fc4dab/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js#L126

2021-07-21 09:50 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on e904530b42eb40605f3acfe5f75578bf340db23d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34833">issues.joomla.org/tracker/joomla-cms/34833</a>.</sub>

2021-07-21 16:02 UTC, Quy commented on libraries/src/Helper/MediaHelper.php
> +	 * @since   __DEPLOY_VERSION
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-07-21 16:04 UTC, richard67 commented
I've restored the previous test result since the change after that was only in a comment.

2021-07-22 23:52 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 88d662abd52414e97fedc13c90463abea334f372<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34833">issues.joomla.org/tracker/joomla-cms/34833</a>.</sub>

2021-07-22 23:52 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34833">issues.joomla.org/tracker/joomla-cms/34833</a>.</sub>

2021-07-23 21:32 UTC, merged

2021-07-23 21:33 UTC, wilsonge commented
Thanks!