After Switching Admin Language, in the message displayed, show Native Title instead of Title [in English]
joomla/joomla-cms pull request #34884
Opened 2021-07-23 16:29 UTC by imanickam

Pull Request for Issue # .

It is not an issue; but, an improvement.

### Summary of Changes

For example, if German is Switched as the back-end Administrator language, following message is displayed:
Die Administrationssprache wurde auf "German (Germany)" geändert. 

With the change proposed, the following message would be displayed:
Die Administrationssprache wurde auf "Deutsch (Deutschland)" geändert.

When the message is displayed in the native language (e.g., German), it would be nice/better to show the language's Native Name/Title instead of the Name/Title in English.

### Testing Instructions

1. Log into Joomla! 4's back-end (_site-url/administrator_) with an account that has Super User privileges
2. Install the German language by going to the screen "Extensions: Languages" (System => Install -> Languages)
3. Go to the screen "Languages: Installed (Site)" (System => Manage -> Languages)
4. Choose "Administrator" from the dropdown (that show the client) - The screen "Languages: Installed (Administrator)" would be shown and the list of languages installed that has Administrator pack would be shown
5. Choose the language German and click on the button "Switch Language"

Now the German language would be the back-end administrator language.  Also, a message confirming the language switch would be displayed as shown below in the German language.

`Die Administrationssprache wurde auf "German (Germany)" geändert. `

Notice that even though the message is in German, the language name shown is in English.

NOW, APPLY THE PATCH WITH THE CHANGE PROPOSED AND REPEAT THE TEST STEPS 1 TO 5 AS LISTED ABOVE.

After, German language is made as the back-end administrator language, following message would be displayed confirming the language switch.

`Die Administrationssprache wurde auf "Deutsch (Deutschland)" geändert.
`

**Notice the difference in the name of the language displayed between the messages before and after the change.**

### Actual result BEFORE applying this Pull Request

Notice that the message is in the native language (e.g, German) whereas the language name shown is in English.

![Original_Language_Title_Shown](https://user-images.githubusercontent.com/4947580/126809525-151709de-cee7-4798-aeb0-4233083e0b2e.jpg)

### Expected result AFTER applying this Pull Request

Notice that the message is in the native language (e.g., German) and the language name shown is also in the native language (e.g., German).

![Revised_Language_Native-Title_Shown](https://user-images.githubusercontent.com/4947580/126809574-bde08590-b37f-4060-9789-f4606518db1e.jpg)

### Documentation Changes Required

Probably Joomla! 4 documentation screenshot in case if the switching message is shown in the screenshot.

2021-07-24 10:32 UTC, richard67 commented
Can we be sure that all language packs provide the `nativeName` in their XML?

2021-07-24 11:08 UTC, richard67 commented on administrator/components/com_languages/src/Controller/InstalledController.php
> +		$languageName = $info['nativeName'];
```suggestion
		$info         = LanguageHelper::parseXMLLanguageFile($file);
		$languageName = $info['nativeName'] ?? $info['name'];
```
1. Restore the alignment of "=" like it was before.
2. To me it seems that we can't rely on the nativeName always being defined, see e.g. this code here: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Language/LanguageHelper.php#L52

2021-07-24 11:21 UTC, richard67 requested changes, later dismissed
See comment below my review suggestion.

2021-07-24 11:31 UTC, Bakual commented
In J4, you can assume `nativeName` to be always present. In J3 there can be old packs which don't have it (it was added in a J3 release) but it's a required field since quite some time.
So if it's missing, it's a bug in the language pack.

2021-07-24 11:31 UTC, richard67 commented on administrator/components/com_languages/src/Controller/InstalledController.php
> +		$languageName = $info['nativeName'];
Hmm I'm just told that the nativeName is a required field in XML of J4 languages, so this PR might be ok as it is (except maybe the small code style change).

2021-07-24 11:34 UTC, richard67 commented on administrator/components/com_languages/src/Controller/InstalledController.php
> +		$info = LanguageHelper::parseXMLLanguageFile($file);
```suggestion
		$info         = LanguageHelper::parseXMLLanguageFile($file);
```
Align "=" with the one in the row below.

2021-07-24 11:44 UTC, imanickam reviewed
Aligned the = sign as suggested.

2021-07-24 11:45 UTC, imanickam commented on administrator/components/com_languages/src/Controller/InstalledController.php
> +		$info = LanguageHelper::parseXMLLanguageFile($file);
Aligned the "=" as suggested.

2021-07-24 12:17 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 800730dca386a95d176a53121d8c701f46efef51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34884">issues.joomla.org/tracker/joomla-cms/34884</a>.</sub>

2021-07-24 12:20 UTC, richard67 commented
I've tested with all currently available J4 languages, which currently are:

![2021-07-24_Language-switching_languages-available](https://user-images.githubusercontent.com/7413183/126868168-fcd33c70-1496-462d-8fab-19a1743f9192.png)

It seems the Portuguese language pack uses wrong "_QQ_" in the language string for the message:

![2021-07-24_Language-switching-errors_pt-PT](https://user-images.githubusercontent.com/7413183/126868220-718adcf4-6217-4bb4-b3f7-60bc595bae45.png)

I'll see if I can report it to the translation team.

2021-07-24 13:05 UTC, ceford commented
I have tested this item :white_check_mark: successfully on 800730dca386a95d176a53121d8c701f46efef51<br /><br />Works with German, French and Persion<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34884">issues.joomla.org/tracker/joomla-cms/34884</a>.</sub>

2021-07-24 13:06 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34884">issues.joomla.org/tracker/joomla-cms/34884</a>.</sub>

2021-07-24 13:17 UTC, brianteeman commented
surely the native title for french is wrong and still in english

2021-07-24 13:17 UTC, brianteeman commented
and welsh

2021-07-24 13:18 UTC, richard67 commented
Yes ... they have to fix that in their translation packages.

2021-07-26 19:34 UTC, merged

2021-07-26 19:34 UTC, wilsonge commented
Thanks!