[4.0] Updating or uninstalling one library no longer removes another when both belong to same vendor.
joomla/joomla-cms pull request #34954
Opened 2021-07-28 12:19 UTC by BrainforgeUK

Pull Request for Issue # .
#34910

### Summary of Changes

Check if there are any other children before removing vendor folder.

### Testing Instructions

As described in #34910

### Actual result BEFORE applying this Pull Request

Updating or uninstalling one library removes another when both belong to same vendor.

### Expected result AFTER applying this Pull Request

Updating or uninstalling one library no longer removes another when both belong to same vendor.

### Documentation Changes Required

Check if using library names like these is documented.

<libraryname>mycompany/mylibrary1</libraryname>

<libraryname>mycompany/mylibrary2</libraryname>

2021-07-28 12:24 UTC, joomdonation commented
@BrainforgeUK Could you please give two sample libraries so that we can use it for testing?

2021-07-28 13:05 UTC, brianteeman requested changes

2021-07-28 13:05 UTC, brianteeman commented on libraries/src/Installer/Adapter/LibraryAdapter.php
> +			if (empty($folders))
```suggestion
			$folders = Folder::folders(JPATH_PLATFORM . '/' . $elementParts[0], '.', false, true, array(), array());

			if (empty($folders))
```

2021-07-28 13:08 UTC, BrainforgeUK commented
[lib_bftest1.zip](https://github.com/joomla/joomla-cms/files/6893195/lib_bftest1.zip)
[lib_bftest2.zip](https://github.com/joomla/joomla-cms/files/6893207/lib_bftest2.zip)
[lib_bftest3.zip](https://github.com/joomla/joomla-cms/files/6893208/lib_bftest3.zip)

**With J4 RC5**
Install the 3 extensions 1,2,3 - installed OK.
Folders .../libraries/brainforgeuk/test[123] exist OK.
Install lib_bftest2 again (do not remove it - pretend its and update).
Admin Extensions Manage page shows all 3 installed.
Folder .../libraries/brainforgeuk/test2 exists, the others have been removed!

**With Change**
Install the 3 extensions 1,2,3 - installed OK.
Folders .../libraries/brainforgeuk/test[123] exist OK.
Install lib_bftest2 again (do not remove it - pretend its and update).
Admin Extensions Manage page shows all 3 installed.
Folder .../libraries/brainforgeuk/test[123] exist OK.

In admin Extensions Manage page unininstall  lib_bftest3 OK, folders for test1 and test2 still exist.
In admin Extensions Manage page unininstall  lib_bftest1 OK, folder for test2 still exists.
In admin Extensions Manage page unininstall  lib_bftest2 OK, folder brainforgeuk removed.

2021-07-28 13:24 UTC, richard67 commented on libraries/src/Installer/Adapter/LibraryAdapter.php
> +			if (empty($folders))
@BrainforgeUK Please apply Brian's suggested change because that will fix the PHP code style error in drone, which currently keeps other tests like e.g. system tests from being run. Thanks in advance.

2021-07-29 05:20 UTC, joomdonation commented on libraries/src/Installer/Adapter/LibraryAdapter.php
> +			$folders = Folder::folders(JPATH_PLATFORM . '/' . $elementParts[0], '.', false, true, array(), array());
The only thing is you can omit the optional parameters in this code, simplify it to:

```php
$folders = Folder::folders(JPATH_PLATFORM . '/' . $elementParts[0]);
```

and it should be fine. I tested it.

2021-07-30 16:59 UTC, maikol-ortigueira commented
I have tested this item :white_check_mark: successfully on 6b2c94b77ccbc800c3d0959edbce92b493dc5fc6<br /><br />I have tested this issue successfully, and for this I have made use of the files you provide.

PHP version : 7.4
Joomla Version: 4.0.0-rc5
OS: Ubuntu 20.04.2 LTS

Thank you!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34954">issues.joomla.org/tracker/joomla-cms/34954</a>.</sub>

2021-07-30 17:14 UTC, pabloarias commented
Tested with Devilbox and library packages provided.

PHP 7.4.20
Joomla! 4.0.0-rc6-dev

Thank very much!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34954">issues.joomla.org/tracker/joomla-cms/34954</a>.</sub>

2021-07-30 17:14 UTC, pabloarias commented
I have tested this item :white_check_mark: successfully on 6b2c94b77ccbc800c3d0959edbce92b493dc5fc6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34954">issues.joomla.org/tracker/joomla-cms/34954</a>.</sub>

2021-07-30 17:21 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34954">issues.joomla.org/tracker/joomla-cms/34954</a>.</sub>

2021-07-30 17:22 UTC, alikon commented
happy to see yet another one Devilbox https://github.com/cytopia/devilbox/ user

2021-07-30 17:22 UTC, richard67 commented
@BrainforgeUK Could you implement @joomdonation ' suggestion above - see https://github.com/joomla/joomla-cms/pull/34954#discussion_r678832433 - and remove the empty arrays for the last 2 parameters so the defaults are used? I will then help to get testers again. Thanks in advance.

2021-07-30 17:23 UTC, alikon commented
back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34954">issues.joomla.org/tracker/joomla-cms/34954</a>.</sub>

2021-07-30 18:34 UTC, BrainforgeUK commented
Removed the empty arrays, as requested,

2021-07-30 18:42 UTC, richard67 commented
Thanks

2021-07-30 18:45 UTC, richard67 commented on libraries/src/Installer/Adapter/LibraryAdapter.php
> +			$folders = Folder::folders(JPATH_PLATFORM . '/' . $elementParts[0], '.', false, true, array(), array());
@joomdonation The booleans should still be needed because the last one differs from the default, if I remember right now.

2021-07-30 18:52 UTC, richard67 commented
@maikol-ortigueira @pabloarias Could you test again? There has been made a change. Thanks in advance.

2021-07-31 09:57 UTC, richard67 commented
@BrainforgeUK Sorry I have to bother you again. My mistake, I promose it's the last time. Could you also remove the optional two boolean parameters which now are the last two, so only `$folders = Folder::folders(JPATH_PLATFORM . '/' . $elementParts[0], '.');` remains? Thanks in advance.

@joomdonation is right, we don't need to use absolute path here, so the last 2 could be "false, false" and so equal to the defaults instead of "false, true".

2021-07-31 10:19 UTC, richard67 commented
@BrainforgeUK Thanks a lot, very appreciated. Will prepare to test now.

2021-07-31 10:22 UTC, BrainforgeUK commented
Also removed the filter parameter as the default is the same.
Ok challenging me on this ... spend to much time on DIY!
Maybe might be able to usefully contribute again another time.

2021-07-31 10:32 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 19ba82c297aa502f6602f9905bb5038c48bf2945<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34954">issues.joomla.org/tracker/joomla-cms/34954</a>.</sub>

2021-07-31 10:35 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on 19ba82c297aa502f6602f9905bb5038c48bf2945<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34954">issues.joomla.org/tracker/joomla-cms/34954</a>.</sub>

2021-07-31 10:36 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34954">issues.joomla.org/tracker/joomla-cms/34954</a>.</sub>

2021-07-31 10:37 UTC, richard67 commented
@wilsonge Because it's a fix for the installer, I'd like to have that in 4.0, so I've set the 4.0 milestone. Feel free to change if not ok.

2021-08-02 09:35 UTC, merged

2021-08-02 09:35 UTC, wilsonge commented
Thanks!