Push footer to bottom and fix content vertically centered
joomla/joomla-cms pull request #35012
Opened 2021-08-01 14:02 UTC by RickR2H

Pull Request for Issue #35003 and replacement of PR #35004

### Summary of Changes
Added holy grail layout to the Cassiopeia template. That way the footer can be pushed to the bottom if there is less content then the screen height.

### Testing Instructions
See issue #35003 and description of PR #34849
Please test with and without modules and content and in different display sizes. Also test with short content and some module in footer position.

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Documentation Changes Required

2021-08-01 14:05 UTC, RickR2H commented
@drmenzelit @hans2103 @dgrammatiko @richard67 please review / test.

2021-08-01 14:08 UTC, richard67 commented on templates/cassiopeia/index.php
> +    <div class="site-grid">
```suggestion
	<div class="site-grid">
```
Fix code style error which causes drone to fail.

Please use tabs and not spaces to indent PHP code.

2021-08-01 14:11 UTC, hans2103 commented
@RickR2H can you move the fix for scroll-to-top to another PR or adjust the description and title of this PR?
You're changing more than you describe.

2021-08-01 14:13 UTC, RickR2H commented on templates/cassiopeia/index.php
> +    <div class="site-grid">
@richard67 sorry. Pushed fix.

2021-08-01 14:17 UTC, RickR2H commented
@hans2103 All changes are connected, so I changed the title and description.

2021-08-01 14:21 UTC, hans2103 commented
please adjust the following: 
```
templates/cassiopeia/scss/blocks/_back-to-top.scss
7:3  ✖  Expected "position" to come before "opacity"     order/properties-order
9:3  ✖  Expected "right" to come before "bottom"         order/properties-order
17:3  ✖  Expected "z-index" to come before "transition"   order/properties-order
```


that's why the build fails

2021-08-01 14:22 UTC, richard67 commented
@RickR2H Regarding your review request: I think I'm not the right guy to review since my knowledge on CSS and JS is too little.

2021-08-01 14:25 UTC, RickR2H commented
> please adjust the following:
> 
> ```
> templates/cassiopeia/scss/blocks/_back-to-top.scss
> 7:3  ✖  Expected "position" to come before "opacity"     order/properties-order
> 9:3  ✖  Expected "right" to come before "bottom"         order/properties-order
> 17:3  ✖  Expected "z-index" to come before "transition"   order/properties-order
> ```
> 
> that's why the build fails

Thanks Hans. Pushed new commit

2021-08-01 14:26 UTC, richard67 commented
Just wanted to post but Hans was faster.

2021-08-01 14:33 UTC, hans2103 commented
@RickR2H onwards to solve the next check. 
```
	templates/cassiopeia/scss/blocks/_back-to-top.scss
8	  8:3  ✖  Expected "right" to come before "opacity"           order/properties-order
9	 16:3  ✖  Expected "z-index" to come before "border-radius"   order/properties-order
```

2021-08-01 14:37 UTC, richard67 commented
@RickR2H You can use following commands to check code style on the command line if you have npm:

`npm run lint:css`

`npm run lint:js'

2021-08-01 15:19 UTC, RickR2H commented
> npm run lint:css

Thanks Richard! I'll do that next time!

2021-08-02 09:43 UTC, hans2103 commented
@RickR2H I see a lot of spacing added... is that correct?
https://github.com/joomla/joomla-cms/pull/35012/files
![Schermafbeelding 2021-08-02 om 11 42 42](https://user-images.githubusercontent.com/639822/127840863-70c2884b-8d3b-4945-974b-28ce5ca75c47.png)

2021-08-02 09:47 UTC, RickR2H commented
Mmmm that's look like something is, wrong with the indentation. I'll try to fix today.

2021-08-02 10:26 UTC, RickR2H commented
@hans2103 Did a review of the whole index.php to make indentation more structured. To review the indentations, please take a look at the whole file instead of looking at only the changes in Git. Hope these changes are more appealing to the eye 😉

2021-08-02 10:27 UTC, brianteeman commented
Something still not correct

https://github.com/joomla/joomla-cms/blob/78f11a01f2fb09bb0b534e54476f2e452556bd1b/templates/cassiopeia/index.php

2021-08-02 10:37 UTC, RickR2H commented
@brianteeman @hans2103 Is it a better option to remove the empty lines

please review https://github.com/joomla/joomla-cms/blob/d374cbdb98bdca5e6869d6120c8140d6e34f9a62/templates/cassiopeia/index.php

2021-08-02 11:01 UTC, dgrammatiko commented
@RickR2H please remove the `.gz` file

2021-08-02 13:16 UTC, hans2103 requested changes
@RickR2H You're removing dir=ltr from the back-to-top-wrapper but not implementing it back to back-to-top-link. I think you should add it to back-to-top-link too

2021-08-02 13:16 UTC, hans2103 commented on templates/cassiopeia/scss/blocks/_back-to-top.scss
> -  [dir=rtl] & {
@RickR2H I think this part should be added to className .back-to-top-link too

2021-08-02 13:17 UTC, RickR2H commented on templates/cassiopeia/scss/blocks/_back-to-top.scss
> -  [dir=rtl] & {
Good catch! Forgot that part...

2021-08-02 13:37 UTC, RickR2H commented on templates/cassiopeia/scss/blocks/_back-to-top.scss
> -  [dir=rtl] & {
Commit added

2021-08-02 13:46 UTC, hans2103 approved these changes

2021-08-02 14:04 UTC, hans2103 commented
I have tested this item :white_check_mark: successfully on daf07c2c83e692c3417b6a1c12aa0fc9ffd00de0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35012">issues.joomla.org/tracker/joomla-cms/35012</a>.</sub>

2021-08-02 14:41 UTC, drmenzelit commented
I have tested this item :white_check_mark: successfully on daf07c2c83e692c3417b6a1c12aa0fc9ffd00de0<br /><br />Tested with and without content, with and without back-to-top, with and without modules on the sidebar, in rtl and in different display sizes.

The case with very short content and some modules in bottom positions is a very edge case I guess, so I can live with bottom modules not being at the very bottom of the page ;-)

Thank you @RickR2H  for your work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35012">issues.joomla.org/tracker/joomla-cms/35012</a>.</sub>

2021-08-02 14:42 UTC, RickR2H commented
@drmenzelit @hans2103 thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35012">issues.joomla.org/tracker/joomla-cms/35012</a>.</sub>

2021-08-02 14:45 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35012">issues.joomla.org/tracker/joomla-cms/35012</a>.</sub>

2021-08-14 12:14 UTC, RickR2H commented
@wilsonge dm on Glip

2021-08-16 21:08 UTC, PhilETaylor commented
@wilsonge This works and fixes #35119. LGTM :)

2021-08-16 21:12 UTC, PhilETaylor commented
Actually... while this fixes the immediate issue of #25119 enough to launch Joomla 4, the 403 error page is screwed up and the footer appears above the content

<img width="1491" alt="Screenshot 2021-08-16 at 22 11 30" src="https://user-images.githubusercontent.com/400092/129630052-73eb4c7d-ab94-4740-bdcf-6e5f14a66831.png">

2021-08-16 21:14 UTC, softforge commented
I have tested this item :white_check_mark: successfully on daf07c2c83e692c3417b6a1c12aa0fc9ffd00de0<br /><br />Further tests on this and still its working fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35012">issues.joomla.org/tracker/joomla-cms/35012</a>.</sub>

2021-08-16 21:15 UTC, PhilETaylor commented
> Further tests on this and still its working fine 

Except its not though.  Test the error page. The 404 page. The 403 error page.

2021-08-16 21:19 UTC, RickR2H commented
@PhilETaylor I can check if this can be fixed really quickly...

2021-08-16 21:22 UTC, PhilETaylor commented on templates/cassiopeia/js/template.js
> +        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
Just being picky but no body needs a "back to top" link box after just 20 pixels of scrolling ! haha

2021-08-16 21:22 UTC, brianteeman commented on templates/cassiopeia/js/template.js
> +        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
and thats why its optional ;)

2021-08-16 21:23 UTC, richard67 commented on templates/cassiopeia/js/template.js
> +        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
I'm pretty sure we will get some issues "just because" ;-)

2021-08-16 21:24 UTC, PhilETaylor commented on templates/cassiopeia/js/template.js
> +        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
At least make it when the height of the viewport +1pixel... else its meaningless... no one needs to click a link to view the first 20 pixels of  screen then just scrolled down 20px on...

2021-08-16 21:26 UTC, PhilETaylor commented
also if you have a named link fragment like 

```html
<a href="#top"......
```

but there is no named anchor for `top`, is that even valid? Probably valid HTML but still not perfect right? 

Yes i know JS is doing the "actual" `window.scrollTo` but there should be a named anchor for completeness right?

2021-08-16 21:28 UTC, PhilETaylor commented
Also - is it meant to smooth scroll still? because it doesnt, it jumps instantly when clicked.

2021-08-16 21:29 UTC, PhilETaylor commented
> Also - is it meant to smooth scroll still? because it doesnt, it jumps instantly when clicked.

Ignore that - Safari on mac doesnt like smooth scroll apparently. Works in google chrome... yet another difference with Joomla and Safari :(

2021-08-16 21:34 UTC, RickR2H commented
@PhilETaylor the error page is fixed...

2021-08-16 21:35 UTC, RickR2H commented
Problem now is that is need two tests to pass

2021-08-16 21:36 UTC, richard67 commented
@RickR2H Could you update your testing instructions by adding a short hint to check also the error page? Thanks in advance.

2021-08-16 21:39 UTC, PhilETaylor commented
> @PhilETaylor the error page is fixed...

Yes I can confirm its working for me too now - thanks for quickly fixing this. Ive not comprehensively tested the rest of the PR, apart from it fixes my reported issue in #35119 and now fixes the error page too.

@richard67 @wilsonge Im happy if you are, the other tests are valid still I think because the changes only changed the error.php files.

2021-08-16 21:42 UTC, richard67 commented
@PhilETaylor If you mark your test result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/35012 and @softforge or one of the other previous testers is available to test again, that would be fine.

2021-08-16 21:43 UTC, PhilETaylor commented
I have tested this item :white_check_mark: successfully on ec7881f66ec52e806d976500bfc36fff9ee20ade<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35012">issues.joomla.org/tracker/joomla-cms/35012</a>.</sub>

2021-08-16 21:43 UTC, RickR2H commented
Updated the test instructions as mentioned

2021-08-16 21:46 UTC, RickR2H commented
@richard67 we still need one more test to pass 😉

2021-08-16 22:09 UTC, softforge commented
I have tested this item :white_check_mark: successfully on ec7881f66ec52e806d976500bfc36fff9ee20ade<br /><br />Had server errors on. Switched off and could confirm Phil T issue. Updated to the latest build and confirm the footer switched position to the correct position on 404 and 403.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35012">issues.joomla.org/tracker/joomla-cms/35012</a>.</sub>

2021-08-16 22:10 UTC, merged

2021-08-16 22:10 UTC, wilsonge commented
Thanks!

2021-08-16 22:10 UTC, richard67 commented
Has anyone tested RTL?

2021-08-16 22:11 UTC, richard67 commented
I am just testing, too, and just wanted to.

2021-08-16 22:11 UTC, PhilETaylor commented
> Has anyone tested RTL?

I cant even spell my name backward. So no.

2021-08-16 22:11 UTC, RickR2H commented
Will check now...

2021-08-16 22:15 UTC, richard67 commented
RTL looked ok here, the rest too.

I've noticed that the error page doesn't respect the "Sticky Header" option of the template style settings, but that might also have been the case without this PR. am just checking that.

2021-08-16 22:16 UTC, richard67 commented
Yes, was also case before this PR. So I have not found any issues, all ok.

Now let's hope nobody of us missed anything ;-)

2021-08-16 22:22 UTC, RickR2H commented
@richard67 RTL works! Also tested the error page. Thanks to all!