[4.1] [SOC 21] Add a Cronjobs Infrastructure to Joomla
joomla/joomla-cms pull request #35143
Opened 2021-08-15 17:15 UTC by ditsuke

## Introduction

Many web hosting services do not offer access to the native UNIX cron. A popular solution to scheduling tasks with such servers is using a pseudo-cron. Many major projects like Drupal and Wordpress already offer some form of pseudo-cron functionality.

However, there is currently no standard way to schedule tasks in the Joomla core. There is also no way to integrate native cron with Joomla if the server offers access to this functionality.

This PR introduces a Cronjobs infrastructure into Joomla! At the time of writing, this infrastructure includes a Cronjobs component and a Cronjobs system plugin as implemented in the first half of my work under SOC '21.' Also included is a test job plugin along with 2 functional job plugins:
- Plugin *Requests* offers a GET Request job with the ability to set authorization headers and a timeout.
- Plugin *Toggle Offline* offers jobs to change the site's offline status. This can be very useful with say a Cron-style execution rule, so it can be used to turn a site offline for a specific timeframe.

There are plans to also develop plugins for script execution along with other tasks found in `/cli` pre-J4.x.

## Summary of Changes

1. **Cronjobs Component:** The component provides the infrastructure for Cronjobs as implemented here. This includes the MVC to manage jobs, the plugin API necessary for plugins to advertise and run jobs, a helper for execution rules (currently supported: intervals and cron-style expressions), and a trait for job supporting plugins.
2. **Cronjobs System Plugin:** Subscribes to the `onAfterResponse` event, and executes for now at most a single scheduled job per request. The job execution status is logged to the `joomla_cronjobs.php` log file.
3. **Requests Job Plugin:** Offers a GET Request job with support for auth headers and request timeout.
4. **Toggle Offline Job Plugin:** Offers jobs to change the site offline status.
5. **Database:**
  - Adds a `#__cronjobs` database table.
  - Adds `com_cronjobs` as an `#__assets` entry.
  - Adds `#__extensions` entries for `com_cronjobs`, `plg_system_cronjobs`, `plg_job_testjob`, `plg_job_requests`, `plg_job_toggleoffline`.
6. **System Dashboard:** Adds the Cronjobs Manager under the Manage module.
  

## Planned Work
Right now, the major planned milestones include:
- Joomla Console commands to add, run, list and delete jobs,
- Joomla API MVC,
- Integration with native Cron if it is available,
- A visit count based rule for execution (this is under review),
- A plugin for script or arbitrary command execution,
- Plugin(s) for maintenence tasks corresponding to the scripts under the pre-J4.x `/cli` path.

## Testing Instructions

### Management Workflow
For testing, a fresh installation/config is important. Steps:
1. Go to the System Dashboard.
2. Go to the Cronjobs Manager through the link under the Manage module.

![image](https://user-images.githubusercontent.com/72784348/129484740-9a9b86a3-b9e0-40b9-8e66-308be209bfe8.png)

3. Click on the button to add a new Cronjob.

![image](https://user-images.githubusercontent.com/72784348/129485544-b8ae5e56-3279-4826-bd9d-51e1f018c52f.png)

4. Select the job type. At the time of writing, *Toggle Offline* jobs, *GET Request* and two dummy "test" jobs are available.

![image](https://user-images.githubusercontent.com/72784348/129484933-7c47bf4f-2785-40d0-b309-3df7e04c66fb.png)

5. Configure the execution rules. We have two distinct options: interval based rules and a "custom" cron-style rule.

![image](https://user-images.githubusercontent.com/72784348/129485315-44b77875-1d7b-4073-9508-efb66a1340e1.png)

6. Save the form. Load a page on the site when you expect the job to execute.

![image](https://user-images.githubusercontent.com/72784348/129485353-d566bdcd-6bf6-4830-8595-10ea445b853d.png)

7. The job should execute and it should appear in the `joomla_cronjobs.php` log file.

The log should look like this:
```
#Fields: datetime   priority clientip  category   message  
2021-08-15T04:31:11+00:00  INFO 127.0.0.1 cronjobs   Running  job#03 'Test Cronjobs!'.  
2021-08-15T04:31:13+00:00  INFO 127.0.0.1 cronjobs   Job> Request response code was: 200  
2021-08-15T04:31:13+00:00  INFO 127.0.0.1 cronjobs   Job> GET return code is: 0. Processing Time: 1.85 seconds  
2021-08-15T04:31:13+00:00  INFO 127.0.0.1 cronjobs   Finished job#03 in 2.01 seconds with exit code 0.  
2021-08-15T04:39:20+00:00  INFO 127.0.0.1 cronjobs   Running  job#03 'Test Cronjobs!'.  
2021-08-15T04:39:22+00:00  INFO 127.0.0.1 cronjobs   Job> Request response code was: 200  
2021-08-15T04:39:22+00:00  INFO 127.0.0.1 cronjobs   Job> GET return code is: 0. Processing Time: 1.61 seconds  
2021-08-15T04:39:22+00:00  INFO 127.0.0.1 cronjobs   Finished job#03 in 2.09 seconds with exit code 0.  
2021-08-15T04:45:16+00:00  INFO 127.0.0.1 cronjobs   Running  job#03 'Test Cronjobs!'.  
2021-08-15T04:45:17+00:00  INFO 127.0.0.1 cronjobs   Job> Request response code was: 200  
2021-08-15T04:45:17+00:00  INFO 127.0.0.1 cronjobs   Job> GET return code is: 0. Processing Time: 1.58 seconds  
2021-08-15T04:45:17+00:00  INFO 127.0.0.1 cronjobs   Finished job#03 in 2.27 seconds with exit code 0.
```

**A walk-through:** 
<video src="https://user-images.githubusercontent.com/72784348/129485478-c705080d-8016-450a-b14e-4b9e6e63a2c6.mp4"/>

---
### Toggle Offline Jobs

1. Set up one of the jobs, say "Get Set Online".
![image](https://user-images.githubusercontent.com/72784348/129486361-ed8b97b1-8a1f-4f21-9404-e503f1d5dd29.png)

2. Set the site to offline in global configuration settings
![image](https://user-images.githubusercontent.com/72784348/129486539-76512241-ba8e-4758-b605-eb52a44824e5.png)

3. Load a site page when you expect the job to run.

4. Reload the page. The site should be back online.

5. The log should look like this:
```
2021-08-15T06:03:25+00:00	INFO 127.0.0.1	cronjobs	Running  job#05 'Online1M'.
2021-08-15T06:03:25+00:00	INFO 127.0.0.1	cronjobs	Job> Site was offline, is now online.
2021-08-15T06:03:25+00:00	INFO 127.0.0.1	cronjobs	Job> SetOnline return code is: 0. Processing Time: 0.01 seconds.
2021-08-15T06:03:25+00:00	INFO 127.0.0.1	cronjobs	Finished job#05 in 0.03 seconds with exit code 0.
```

## Documentation Changes Required

TODO

## Acknowledgements

I would like to give a special thanks to @alikon for their work on #29592. I have and continue to draw much inspiration from their ideas, many of which I've indirectly or directly used from the very nascent stages of development to now especially with the system plugin and the console commands in development.

I also owe much gratitude to my mentor @bembelimen who is always there to help me with things even at the oddest of times. A special mention also to our team lead @shivamdiehard who makes sure things go over smoothly.

2021-08-15 17:40 UTC, brianteeman commented
Please review and correct the codestyle used in all the xml

2021-08-15 20:51 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-04.sql
> +VALUES (0, 'com_cronjobs', 'component', 'com_cronjobs', 1, 1, 1, 1, 0, 1, '', '', '');
```suggestion
INSERT INTO `#__extensions` (`package_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`,
							 `protected`, `locked`, `manifest_cache`, `params`, `custom_data`)
VALUES (0, 'com_cronjobs', 'component', 'com_cronjobs', 1, 1, 1, 1, 0, 1, '', '', '');
```
```suggestion
INSERT INTO `#__extensions` (`package_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`,
							 `protected`, `locked`, `manifest_cache`, `params`, `custom_data`)
VALUES (0, 'com_cronjobs', 'component', 'com_cronjobs', '', 1, 1, 1, 0, 1, '', '', '');
```
This SQL statement will fail with an SQL error because the columns list includes the `folder` column, but the values list provides not an empty string like it should be but a number.

2021-08-15 20:52 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.1.0-2021-08-04.sql
> +VALUES (0, 'com_cronjobs', 'component', 'com_cronjobs', 1, 1, 1, 1, 0, 1, '', '{}', '', 0, 0);
```suggestion
INSERT INTO "#__extensions" ("package_id", "name", "type", "element", "folder", "client_id", "enabled", "access",
							 "protected", "locked", "manifest_cache", "params", "custom_data", "ordering", "state")
VALUES (0, 'com_cronjobs', 'component', 'com_cronjobs', '', 1, 1, 1, 0, 1, '', '{}', '', 0, 0);
```
This SQL statement is wrong because the columns list includes the `folder` column, but the values list provides not an empty string like it should be but a number for that column.

2021-08-15 22:25 UTC, ditsuke commented on administrator/components/com_admin/sql/updates/postgresql/4.1.0-2021-08-04.sql
> +VALUES (0, 'com_cronjobs', 'component', 'com_cronjobs', 1, 1, 1, 1, 0, 1, '', '{}', '', 0, 0);
Thank you for reviewing!

2021-08-15 22:37 UTC, ditsuke commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-04.sql
> +VALUES (0, 'com_cronjobs', 'component', 'com_cronjobs', 1, 1, 1, 1, 0, 1, '', '', '');
I've committed the suggestions. Thank you!

2021-08-16 06:51 UTC, brianteeman commented
Looking at the language file I can see a lot of values which could be replaced with existing strings from global language files. This will reduce the workload on translators and also ensure a more consistent ui.

For example COM_CRONJOBS_FIELDSET_RULES is the string used to display a fieldset called JCONFIG_PERMISSIONS_LABEL

2021-08-16 12:05 UTC, scout507 commented
The feature seems to work just fine and is easy to use. The only issue I encountered has to do with the input fields on the 'new crownjob' page:

- negative input in the interval field leads to an error
- if you fill in all the necessary fields, but one with an illegal input, the 'Job Parameters' fields go missing:
![Screenshot 2021-08-16 123820](https://user-images.githubusercontent.com/70096457/129560132-42ebadc0-5648-4438-aac1-26059a10591e.png)

Also, if you trash an existing crownjob, it will still apear in the crownjob list. Not sure if this is intended, but it's not realy clear where the diffrence between trashing and disabling is.

2021-08-16 13:16 UTC, socke300 commented
## First of all

Hey, die Cronjob funktionieren gut und das UI sind einfach und intutive zu verwenden. 



## That's how I tested it

I went through the different cronjobs, created some and checked afterwards if they work. I also tested different inputs for the input options, for example the intervals.



## This is what I found

Like the previous speaker, I noticed the inputs. There is also an error here if the inputs are too long for the intervals or if they contain a point/comma. In general, I think the times should not be written with a comma, there should be a separate field for seconds/minutes/hours or you can specify a format, for example day:hour:minute:second. Otherwise you could not, for example, enter 1:30 hours/minutes as a time period. I also noticed an unimportant detail in the UI, when you create a new cronejob, the plus becomes white, this should perhaps be blue or something. (But that's not important) 

![grafik](https://user-images.githubusercontent.com/60921761/129569261-291a79d3-6157-4b41-9d81-8f23cb6ab48b.png)
This happened when the input was too long.
![grafik](https://user-images.githubusercontent.com/60921761/129569381-d1c1ce6e-1e5c-4612-bb3a-978a4f0a35d8.png)

This happened when entering a certain length.

## Result

All in all, the feature is very nice and it works very well despite the little things. (They were really only small things)

2021-08-16 13:36 UTC, PhilETaylor commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-08.sql
> +CREATE TABLE IF NOT EXISTS `#__cronjobs` (
This table needs some indexes.

2021-08-16 13:36 UTC, PhilETaylor commented on administrator/components/com_admin/sql/updates/postgresql/4.1.0-2021-08-08.sql
> +CREATE TABLE IF NOT EXISTS "#__cronjobs"
This table needs some indexes.

2021-08-16 13:36 UTC, PhilETaylor commented on administrator/components/com_cronjobs/cronjobs.xml
> +	<license>GPL v3</license>
GPL v3? really?

2021-08-16 13:37 UTC, PhilETaylor commented on administrator/components/com_cronjobs/layouts/Joomla/form/field/interval.php
> + * @license       GPL v3
GPL v3? really?

2021-08-16 13:38 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:38 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> + * The CronjobModel controller.
copy and paste comment... not needed here

2021-08-16 13:38 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> +		/**@var AdministratorApplication $app */
```suggestion
		/** @var AdministratorApplication $app */
```

2021-08-16 13:39 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> +		// TODO : Parameter array handling below?
```suggestion
		// @todo Parameter array handling below?
```

2021-08-16 13:40 UTC, brianteeman commented
Please ask your mentors how to format and indent the xml files.

2021-08-16 13:40 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> +	 * @param   null  $key  Primary key from the URL param
null is just one of the types that `$key` could be... maybe this should be `null|string` ?

2021-08-16 13:40 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> +		// TODO: Change the autogenerated stub
```suggestion
		// @todo Change the autogenerated stub
```

2021-08-16 13:41 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> +		// TODO: Change or remove
```suggestion
		// @todo Change or remove
```

The `@todo` tag is parsed by static analysing tools and IDE's better than just `TODO`

2021-08-16 13:43 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobsController.php
> + * The CronjobsModel controller.
Not needed, also wrong as this is a controller not a model

2021-08-16 13:43 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/DisplayController.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:44 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Cronjobs/CronOption.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:44 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Cronjobs/CronOption.php
> +
No Restrict direct access check?

```
// Restrict direct access
 defined('_JEXEC') or die;
```

2021-08-16 13:45 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Cronjobs/CronOptions.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:45 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Event/CronRunEvent.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:45 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Event/CronRunEvent.php
> +	 * @since   4.0.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-08-16 13:46 UTC, ditsuke commented on administrator/components/com_cronjobs/cronjobs.xml
> +	<license>GPL v3</license>
I'll update the headers!

2021-08-16 13:47 UTC, ditsuke commented on administrator/components/com_admin/sql/updates/postgresql/4.1.0-2021-08-08.sql
> +CREATE TABLE IF NOT EXISTS "#__cronjobs"
Noted!

2021-08-16 13:47 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Field/CronField.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:48 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Field/CronField.php
> +	private const PREPARED_RESPONSE_LABELS = [
Has consideration been given to translating these correctly?

2021-08-16 13:48 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Field/ExecutionRuleField.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:49 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Field/IntervalField.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:49 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Field/JobTypeField.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:49 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Helper/CronjobsHelper.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:49 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Helper/ExecRuleHelper.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:50 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Model/CronjobModel.php
> + * @license       GPL v3
GPL v3? Really?

2021-08-16 13:53 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Model/CronjobsModel.php
> +				$searchStr = "%${searchStr}%";
You dont need curly brackets if your are using double quotes around your string. 

```suggestion
				$searchStr = "%$searchStr%";
```

2021-08-16 13:57 UTC, PhilETaylor commented
JForm is @deprecated 5.0 Use Joomla\CMS\Form\Form instead.
JObject @deprecated 5.0 Use Joomla\CMS\Object\CMSObject instead (Although that class is also deprecated 4.0.0 apparently!)
getDBO is deprecated use `$app->getContainer()->get('DatabaseDriver')` instead

2021-08-16 13:58 UTC, ditsuke commented on administrator/components/com_cronjobs/src/Field/CronField.php
> +	private const PREPARED_RESPONSE_LABELS = [
I believe we're doing that here

https://github.com/joomla/joomla-cms/blob/8f3c3cba967578b5a32809288744970f3da15065/administrator/components/com_cronjobs/src/Field/CronField.php#L164-L172

2021-08-16 13:58 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Controller/CronjobsController.php
> +use Joomla\Component\Cronjobs\Administrator\Model\CronjobModel;
Can be deleted

```suggestion

```

2021-08-16 13:58 UTC, PhilETaylor commented on administrator/components/com_cronjobs/tmpl/cronjobs/default.php
> +use Joomla\CMS\Language\Multilanguage;
Can be deleted - not used

```suggestion

```

2021-08-16 13:59 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Field/ExecutionRuleField.php
> +use Joomla\CMS\Language\Text;
4 Can be deleted

```suggestion
use Joomla\CMS\Form\Field\PredefinedlistField;
```

2021-08-16 14:00 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/View/Cronjob/HtmlView.php
> +		/** @noinspection SpellCheckingInspection */
Please dont do this ;) add the spelling to your own custom dictionary :)

2021-08-16 14:01 UTC, PhilETaylor commented on administrator/components/com_cronjobs/src/Field/CronField.php
> +	private const PREPARED_RESPONSE_LABELS = [
Awesome.

2021-08-16 14:03 UTC, PhilETaylor commented
Also needs to have triggers to the User Action Log - because adding/editing/deleting of cron jobs is an action that should be logged - and therefore can be alerted on (Especially if you are going to allow crobjobs that can make external requests ... cause hackers going to love adding those kind of corncobs ;-))

2021-08-16 14:04 UTC, PhilETaylor commented
Also should dispatch events in the case of success/failure of the running of a cronjob.

2021-08-16 14:05 UTC, PhilETaylor commented
It also 100% MUST allow input of the cron expression using standard notation 5 digits `* * * * *`

2021-08-16 14:16 UTC, ditsuke commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> +		// TODO: Change or remove
Thank you for this suggestion!

2021-08-16 14:22 UTC, PhilETaylor commented
Also I wonder if this feature should even be named "cronjobs" at all as they are NOT cron jobs.... they are just scheduled tasks, that are not even (optionally) run by any cron system at a operating system level. 

Cron jobs are tasks added to a crontab on a unix based machine. 

Cron is a technical term that probably not all Joomla users are familiar with. Something like "Scheduled Tasks" everyone can understand.

2021-08-16 14:27 UTC, brianteeman commented
@PhilETaylor I have been pondering that myself and browsing the web looking at examples. The best I have seen to date was using "Cron Jobs, "Cron Tasks" as two separate words. But I wasn't happy that it provided the required clarity when I saw that in action in this PR.

Your suggestion, and reasoning, for "Scheduled Tasks" is much better.

Then the collective name could be simply Schedule and the individual name is Task.

Example
A new feature in 4.1 is the ability to Schedule new Tasks. You can add as many tasks as you want to the Schedule and each task can have its own time interval.

2021-08-16 14:35 UTC, PhilETaylor commented
> You can add as many tasks as you want 

A nightmare scenario to handle with a web based pseudo cron... 

> each task can have its own time interval

Yes, but there is no forking of processes, so each still has to wait for the last to finish,

2021-08-16 14:35 UTC, PhilETaylor commented
getDueJobs loads ALL jobs, but then executeDueJob only picks [0] from the array to run on onAfterRespond.. would be more performant to return only a single job and not all getItems.

2021-08-16 14:36 UTC, PhilETaylor commented
```
// We only act on site requests
		if (!$this->app->isClient('site'))
		{
			return;
		}
```

Why? Why not run on /administrator/ as well? as there performance issues could better be tolerated.

2021-08-16 14:39 UTC, brianteeman commented
> > You can add as many tasks as you want
> 
> A nightmare scenario to handle with a web based pseudo cron...
> 
> > each task can have its own time interval
> 
> Yes, but there is no forking of processes, so each still has to wait for the last to finish,

It was an example of how the term could be used in text and nothing more. You were supposed to be commenting "that is so much clearer and easier to understand than using the word cron and cronjobs" ;)

2021-08-16 14:39 UTC, ditsuke commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-08.sql
> +CREATE TABLE IF NOT EXISTS `#__cronjobs` (
Left it out too long, noted!

2021-08-16 14:44 UTC, PhilETaylor commented
I may or may not have considerable experience in creating multiple web based cron systems ;-) 

<img width="1359" alt="Screenshot 2021-08-16 at 15 44 59" src="https://user-images.githubusercontent.com/400092/129582480-10b4b50d-e634-4ea2-91e4-4e684d66a04a.png">

<img width="1518" alt="Screenshot 2021-08-16 at 15 41 50" src="https://user-images.githubusercontent.com/400092/129582297-73bfddc6-2032-4608-9b1c-6c0dffb2bdee.png">

2021-08-16 14:46 UTC, PhilETaylor commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-08.sql
> +	`ordering` int NOT NULL DEFAULT 0 COMMENT 'Configurable list ordering',
Although ordering is used in Joomla to display a list, Cron Jobs need a PRIORITY... somethings need to run before others, somethings are more "important" than others and should be at the top of the list when it comes to pulling overdue cronjobs from the list to run.

2021-08-16 14:47 UTC, PhilETaylor commented
Each cronjob should be capable of logging to its OWN log file and not just the central log of all cronjobs... makes debugging and also documenting each job easier.

2021-08-17 00:31 UTC, dgrammatiko commented on media/com_cronjobs/css/admin-view-cronjob.css
> +.match-custom .control-group .control-label {
move the file to `build/media_source/com_cronjobs/css/admin-plg-job.css`

This is wrong the media folder is generated not the source

2021-08-17 00:32 UTC, dgrammatiko commented on media/com_cronjobs/joomla.asset.json
> +{
move the file to `build/media_source/com_cronjobs/joomla.asset.json `

This is wrong the media folder is generated not the source

2021-08-17 00:34 UTC, dgrammatiko commented on media/com_cronjobs/js/admin-plg-job-search.js
> +/**
move the file to build/media_source/com_cronjobs/js/admin-plg-job-search-es6.js

This is wrong the media folder is generated not the source

Also you need to refactor this file to ES6+

2021-08-17 00:35 UTC, dgrammatiko commented on media/com_cronjobs/js/admin-plg-job-search-es5.js
> +(function () {
move the file to `build/media_source/com_cronjobs/joomla.asset.json `

This is wrong the media folder is generated not the source

2021-08-18 04:39 UTC, ditsuke commented
@PhilETaylor 

> 
> 
> ```
> // We only act on site requests
> 		if (!$this->app->isClient('site'))
> 		{
> 			return;
> 		}
> ```
> 
> Why? Why not run on /administrator/ as well? as there performance issues could better be tolerated.

That's a great point I didn't consider before. If I remember right that's what the scheduler from #29592 did, so not sure if there was some reason but it made for easier testing. I can allow admin requests if there's no drawbacks.




> 
> 
> Each cronjob should be capable of logging to its OWN log file and not just the central log of all cronjobs... makes debugging and also documenting each job easier.

Agreed, Do you think a per-job toggle for a standalone log file (besides the main log) should do?




> 
> 
> getDueJobs loads ALL jobs, but then executeDueJob only picks [0] from the array to run on onAfterRespond.. would be more performant to return only a single job and not all getItems.

Good point! Right now its due a refactor as we move to the Console Commands (I'm thinking of moving some of the code to the component namespace or some other way it can be shared), so I'll have the fetching be more efficient when we get to that.




> 
> 
> It also 100% MUST allow input of the cron expression using standard notation 5 digits `* * * * *`

This is planned as suggested by @bembelimen. We might end up completely replacing the multi-select style input with clear inputs as you described. What form design do you prefer for your web-based Cron systems?



> 
> 
> Also should dispatch events in the case of success/failure of the running of a cronjob.

Noted!



> 
> 
> Also needs to have triggers to the User Action Log - because adding/editing/deleting of cron jobs is an action that should be logged - and therefore can be alerted on (Especially if you are going to allow crobjobs that can make external requests ... cause hackers going to love adding those kind of corncobs ;-))

This will be done when we visit the manager next :)



> 
> 
> JForm is @deprecated 5.0 Use Joomla\CMS\Form\Form instead.
> JObject @deprecated 5.0 Use Joomla\CMS\Object\CMSObject instead (Although that class is also deprecated 4.0.0 apparently!)
> getDBO is deprecated use `$app->getContainer()->get('DatabaseDriver')` instead

Thank you for the DBO thing, I believe we also had a todo for that. I've been curious why `CMSObject` is deprecated, it can be handy. 🤔



Thank you again for reviewing the code and the suggestions. I've been a little slow going through them while cleaning things up; adding the suggestions to our roadmap.

2021-08-18 04:43 UTC, ditsuke commented on media/com_cronjobs/joomla.asset.json
> +{
Thank you for identifying this issue! I'll move the files and refactor as suggested.

2021-08-18 04:49 UTC, ditsuke commented
@brianteeman
> 
> 
> Looking at the language file I can see a lot of values which could be replaced with existing strings from global language files. This will reduce the workload on translators and also ensure a more consistent ui.
> 
> For example COM_CRONJOBS_FIELDSET_RULES is the string used to display a fieldset called JCONFIG_PERMISSIONS_LABEL

Thank you for this review! I've identified the strings that have a global equivalent and will be replacing them soon.

2021-08-18 05:00 UTC, ditsuke commented
@scout507 @socke300 

Thank you for the review on the form. I'll work on fixing the discovered issues soon when we revisit management.


> * if you fill in all the necessary fields, but one with an illegal input, the 'Job Parameters' fields go missing:
>       ![Screenshot 2021-08-16 123820](https://user-images.githubusercontent.com/70096457/129560132-42ebadc0-5648-4438-aac1-26059a10591e.png)
> 
> 

@scout507 would you mind filing an issue for this over on the project repository?
 [joomla-projects/soc21_website-cronjob](https://github.com/joomla-projects/soc21_website-cronjob/issues)

2021-08-18 05:11 UTC, ditsuke commented
@PhilETaylor 
> 
> 
> Also I wonder if this feature should even be named "cronjobs" at all as they are NOT cron jobs.... they are just scheduled tasks, that are not even (optionally) run by any cron system at a operating system level.
> 
> Cron jobs are tasks added to a crontab on a unix based machine.
> 
> Cron is a technical term that probably not all Joomla users are familiar with. Something like "Scheduled Tasks" everyone can understand.
<br>

@brianteeman 
> 
> 
> @\PhilETaylor I have been pondering that myself and browsing the web looking at examples. The best I have seen to date was using "Cron Jobs, "Cron Tasks" as two separate words. But I wasn't happy that it provided the required clarity when I saw that in action in this PR.
> 
> Your suggestion, and reasoning, for "Scheduled Tasks" is much better.
> 
> Then the collective name could be simply Schedule and the individual name is Task.
> 
> Example
> A new feature in 4.1 is the ability to Schedule new Tasks. You can add as many tasks as you want to the Schedule and each task can have its own time interval.

Thank you for bringing this up! I agree with that the cron term is perhaps not correct and too technical for effective marketing. My mentor and I are open to the [*rebranding*] in the future 😄

2021-08-18 07:47 UTC, scout507 commented
@ditsuke 
> @scout507 would you mind filing an issue for this over on the project repository?
> [joomla-projects/soc21_website-cronjob](https://github.com/joomla-projects/soc21_website-cronjob/issues)

Done. https://github.com/joomla-projects/soc21_website-cronjob/issues/11

2021-08-19 02:30 UTC, ditsuke commented on administrator/components/com_cronjobs/src/Field/CronField.php
> + * @license       GPL v3
Thank you for isolating this issue, I've fixed the license headers with recent commits.

2021-08-19 14:21 UTC, ditsuke commented on media/com_cronjobs/js/admin-plg-job-search.js
> +/**
I think 38ac6568e0181f96f54d060f97f97e0858e8d988 and fa1e39b009d32b47a7ebae4fa645c4bde45a7876 resolve this. Thank you again for this review!

2021-08-19 14:50 UTC, ditsuke commented on administrator/components/com_cronjobs/src/Controller/CronjobController.php
> +		// TODO: Change or remove
Resolved by 62deeb495cc69eb6f820751cbb816ed7bb8a7cd8. Thank you!

2021-08-19 14:55 UTC, ditsuke commented
> @\brianteeman
> 
> > Looking at the language file I can see a lot of values which could be replaced with existing strings from global language files. This will reduce the workload on translators and also ensure a more consistent ui.
> > For example COM_CRONJOBS_FIELDSET_RULES is the string used to display a fieldset called JCONFIG_PERMISSIONS_LABEL
> 
> Thank you for this review! I've identified the strings that have a global equivalent and will be replacing them soon.

This should be resolved with 101a03d14f5f020c4cb4e144eac8e5537ddd64bb, which removes and replaces usages of all redundant strings I could identify.

2021-08-19 21:11 UTC, bembelimen commented
I'm writing it here, but it counts for all GSoC/SoC PR thank you @brianteeman , @dgrammatiko and @PhilETaylor for the feedback, it's really appreciated!

2021-08-25 14:49 UTC, bembelimen commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-08.sql
> +	`ordering` int NOT NULL DEFAULT 0 COMMENT 'Configurable list ordering',
Hi @PhilETaylor currently the overdue cronjobs are managed on a first in, first out base, otherwise it could be, that high priority crons block out the low priority ones.

I see your point in priorisize some but with the current very serial implementation I see a very big chance, that people crash it.

2021-08-25 14:57 UTC, PhilETaylor commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-08.sql
> +	`ordering` int NOT NULL DEFAULT 0 COMMENT 'Configurable list ordering',
> otherwise it could be, that high priority crons block out the low priority ones.

This is literally the whole point of having a priority! A database backup is more important than sending a welcome email for example.

2021-08-25 16:41 UTC, ditsuke commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-08.sql
> +	`ordering` int NOT NULL DEFAULT 0 COMMENT 'Configurable list ordering',
> This is literally the whole point of having a priority! A database backup is more important than sending a welcome email for example.

I see your point. An idea we just discussed are "Low, Normal, High" priorities, and in the form it goes with warnings so we let the user know things can go wrong. 

Also since you mentioned you have worked on cron managers before, maybe you could share your experience with the form and options?

2021-08-28 17:37 UTC, brianteeman commented on administrator/components/com_menus/presets/system.xml
> +		/>
```suggestion
		<menuitem
			title="MOD_MENU_MANAGE_SCHEDULED_TASKS"
			type="component"
			element="com_scheduler"
			link="index.php?option=com_scheduler&amp;view=tasks"
			permission="core.manage;com_scheduler"
		/>
```

2021-08-28 17:39 UTC, brianteeman commented on administrator/components/com_scheduler/forms/task.xml
> +		/>
```suggestion
		<field 
			 name="title"
			 type="text"
			 label="JGLOBAL_TITLE"
			 size="40"
			 maxlength="100"
			 required="true"
		/>
```

2021-08-28 17:39 UTC, brianteeman commented on administrator/components/com_scheduler/forms/task.xml
> +				>
```suggestion
			<field 
				 name="trigger"
				 type="list"
				 label="COM_SCHEDULER_SELECT_TRIGGER"
				 validate="options"
				 required="true"
				>
```

2021-08-28 17:40 UTC, brianteeman commented on administrator/components/com_scheduler/forms/task.xml
> +				readonly="true"
how can it be both required and readonly

2021-08-28 17:41 UTC, brianteeman commented on administrator/components/com_scheduler/forms/task.xml
> +				name="asset_id" type="hidden" filter="unset"
```suggestion
				name="asset_id" 
				type="hidden" 
				filter="unset"
```

2021-08-28 17:46 UTC, brianteeman commented on plugins/system/schedulerunner/schedulerunner.xml
> +		<language tag="en-GB">en-GB.plg_system_schedulerunner.ini</language>
This filename is wrong. See administrator/components/com_scheduler/scheduler.xml for the structure etc and update here and rename the files

2021-08-28 17:46 UTC, brianteeman commented on plugins/task/requests/requests.xml
> +		<language tag="en-GB">en-GB.plg_task_requests.ini</language>
This filename is wrong. See administrator/components/com_scheduler/scheduler.xml for the structure etc and update here and rename the files

2021-08-28 17:47 UTC, brianteeman commented on plugins/task/testtasks/testtasks.xml
> +		<language tag="en-GB">en-GB.plg_task_testtasks.ini</language>
This filename is wrong. See administrator/components/com_scheduler/scheduler.xml for the structure etc and update here and rename the files

2021-08-28 17:47 UTC, brianteeman commented on plugins/task/toggleoffline/toggleoffline.xml
> +		<language tag="en-GB">en-GB.plg_task_toggleoffline.ini</language>
This filename is wrong. See administrator/components/com_scheduler/scheduler.xml for the structure etc and update here and rename the files

2021-08-28 17:50 UTC, brianteeman commented on administrator/components/com_scheduler/scheduler.xml
> +	<version>4.1.0</version>
Please review this and all the similar files with your mentors to ensure that they are consistent with similar core xml

2021-08-28 17:53 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.ini
> +
```suggestion
; Joomla! Project
; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

```

Please update all language files with the correct copyright header as shown above

2021-08-28 18:00 UTC, brianteeman commented on administrator/components/com_scheduler/layouts/Joomla/form/field/interval.php
> +<?php
This file should be in a folder called joomla not Joomla

2021-08-28 18:05 UTC, ditsuke commented on administrator/components/com_scheduler/forms/task.xml
> +				readonly="true"
I believe readonly disables the field but it can still be submitted.

2021-08-28 18:07 UTC, brianteeman commented on administrator/components/com_scheduler/tmpl/tasks/default_batch_body.php
> +				<?php echo LayoutHelper::render('joomla.html.batch.language', []); ?>
did you test this? tasks dont have a language do they?

2021-08-28 18:10 UTC, brianteeman commented on administrator/components/com_scheduler/tmpl/tasks/default_batch_body.php
> +				<?php echo LayoutHelper::render('joomla.html.batch.access', []); ?>
did you test this? taks dont have an access do they?

2021-08-28 18:20 UTC, ditsuke commented on administrator/components/com_scheduler/tmpl/tasks/default_batch_body.php
> +				<?php echo LayoutHelper::render('joomla.html.batch.language', []); ?>
This wasn't tested. Thank you! 😅

2021-08-30 13:52 UTC, ditsuke commented
@brianteeman 
Thank you for the review! I've tried to address all issues in the latest series of commits.

2021-09-01 12:13 UTC, ditsuke commented
Hello everyone! It's now been around 15 days since I opened this PR. I've addressed and continue to work on the feedback from the community. A basic overview for this can be had from the tasks list in the PR body. 

With this, my mentor and I would now like to announce the completion of the first phase of this project. We're grateful for everyone who gave their feedback and took time to review the code. The feedback has helped a lot in ironing out many of the inconsistencies, bugs and deficiencies and we hope it continues to go that way. A special thanks to @PhilETaylor and @brianteeman who helped me clean up much of my mess and came up with the idea for the rebranding to _Scheduled Tasks_ !  ♥

While there's still much to do in order to meet the project goals, the core goal and the supporting infrastructure has been solidified. Having said that, I stay committed to seeing this project through as a part of Joomla! core and _strongly_ encourage **further feedback, testing and ideas for _task plugins_**.

To plugin developers, I encourage you have a look at what we have to offer. For an idea of how task plugins work, you can have a look at the existing `demotasks` plugin or the other task plugins that have more functionality.

This PR will continue to be regularly updated with the state of the `dcon` development branch from the [project repository](https://github.com/joomla-projects/soc21_website-cronjob). Visitors are welcome and encouraged! 😃

2021-09-01 13:17 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_FIELD_LABEL_INDIVIDUAL_LOG="Standalone Log"
```suggestion
COM_SCHEDULER_FIELD_LABEL_INDIVIDUAL_LOG="Individual Task Logs"
```

2021-09-01 13:17 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_FIELD_HINT_LOG_FILE_AUTO="auto"
this hint should be more meaningful

2021-09-01 13:22 UTC, brianteeman commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> + * Declares the MVC controller for TaskModel.
please move this comment block to after the copyright block

2021-09-01 13:23 UTC, brianteeman commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> + * Declares the ExecuteTaskEvent Event.
Please move this comment to its own comment after the copyright block

2021-09-01 13:23 UTC, brianteeman commented on administrator/components/com_scheduler/src/Field/TaskStateField.php
> + * Declares a list field with all possible states for a (cron)job entry.
Please move this comment to its own comment after the copyright block

2021-09-01 13:24 UTC, brianteeman commented on administrator/components/com_scheduler/src/Field/TaskTypeField.php
> + * Declares the JobTypeField for listing all available job types.
Please move this comment to its own comment after the copyright block

2021-09-01 13:24 UTC, brianteeman commented on administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
> + * Declares the helper class ExecRuleHelper.
Please move this comment to its own comment after the copyright block

2021-09-01 13:24 UTC, brianteeman commented on administrator/components/com_scheduler/src/Model/SelectModel.php
> + * Declares the SelectModel MVC Model.
Please move this comment to its own comment after the copyright block

2021-09-01 13:26 UTC, brianteeman commented on administrator/components/com_scheduler/src/Task/Status.php
> + * @subpackage      sub
Please complete the values

2021-09-01 13:28 UTC, brianteeman commented on administrator/components/com_scheduler/forms/filter_tasks.xml
> +			<option value="j.type_title DESC">COM_SCHEDULER_TASK_TYPE_DESC</option>
The order that these are listed in should match (where possible) the order of the columns in the table

2021-09-01 15:46 UTC, ditsuke commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_FIELD_HINT_LOG_FILE_AUTO="auto"
Done!

2021-09-01 15:47 UTC, ditsuke commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_FIELD_LABEL_INDIVIDUAL_LOG="Standalone Log"
Thanks!

2021-09-01 15:47 UTC, ditsuke commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> + * Declares the MVC controller for TaskModel.
Whoops! Fixed for all files.

2021-09-01 15:48 UTC, ditsuke commented on administrator/components/com_scheduler/src/Task/Status.php
> + * @subpackage      sub
Thanks, good spot! 😅

2021-09-01 15:48 UTC, ditsuke commented on administrator/components/com_scheduler/forms/filter_tasks.xml
> +			<option value="j.type_title DESC">COM_SCHEDULER_TASK_TYPE_DESC</option>
Much better, done!

2021-09-02 08:59 UTC, Denitz commented on administrator/components/com_scheduler/tmpl/select/default.php
> +			<?php foreach ($this->items as &$item) : ?>
What for do we use reference here?

2021-09-02 09:00 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +	private function attachTaskOptions(array &$items): void
Why do we have pass-by-reference here?

2021-09-02 09:02 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		) use ($query, &$filterCount) {
Why do we have pass-by-reference here?

2021-09-02 09:04 UTC, Denitz commented on administrator/components/com_scheduler/src/Field/CronField.php
> +				function (string $string): string {
Static closure can be used.

2021-09-02 09:06 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +				function (string $x): int {
Static closure can be used.

2021-09-02 09:06 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		$extendWhereIfFiltered = function (
Static closure can be used.

2021-09-02 09:06 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +				function (array $arr) {
Static closure can be used.

2021-09-02 09:07 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +					function (object $c) use ($filterOrphaned) {
Static closure can be used.

2021-09-02 09:08 UTC, Denitz commented on administrator/components/com_scheduler/src/Task/Task.php
> +				'eventClass'      => 'Joomla\Component\Scheduler\Administrator\Event\ExecuteTaskEvent',
Why not `'eventClass'      => ExecuteTaskEvent::class,` ?

2021-09-02 09:13 UTC, Denitz commented on administrator/components/com_scheduler/src/Field/CronField.php
> +		$subtype = (string) $element['subtype'] ?? null;
It will never be NULL on missed attribute, consider smth like `(string) $element['subtype'] ?: null;` or use parenthesis.

2021-09-02 09:14 UTC, Denitz commented on administrator/components/com_scheduler/src/Field/CronField.php
> +		$wildcard = (string) $element['wildcard'] ?? false;
It will never be FALSE on missed attribute.

2021-09-02 09:14 UTC, Denitz commented on administrator/components/com_scheduler/src/Field/CronField.php
> +		$onlyNumericLabels = (string) $element['onlyNumericLabels'] ?? false;
It will never be FALSE on missed attribute.

2021-09-02 09:14 UTC, Denitz commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +		$subtype = (string) $element['subtype'] ?? null;
It will never be NULL on missed attribute.

2021-09-02 09:15 UTC, Denitz commented on administrator/components/com_scheduler/src/View/Task/HtmlView.php
> +		if ($isNew && $canDo->get('core.create') || !$isNew && $canDo->get('core.edit'))
Add parenthesis

2021-09-02 09:16 UTC, Denitz commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +		$recordId = (int) $data[$key] ?? 0;
`$recordId = (int) $data[$key];` is enough

2021-09-02 09:17 UTC, Denitz commented on administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
> +			? (object) json_decode($rule)
`json_decode($rule)` will always return object, isn't it?

2021-09-02 09:18 UTC, Denitz commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +	protected static $taskOptionsCache = null;
`protected static $taskOptionsCache;`

2021-09-02 09:19 UTC, Denitz commented on administrator/components/com_scheduler/src/Table/TaskTable.php
> +	protected $_supportNullValue = false;
Parent class already declares `protected $_supportNullValue = false;`

2021-09-02 09:20 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +	public function getItems()
?????

2021-09-02 09:26 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +			if (!$id = $data->id ?? 0)
Unused variable `$id`

2021-09-02 09:27 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +		$field = null;
Unused variable

2021-09-02 09:27 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +			$field = $this->getItem($data['id']);
Unused variable

2021-09-02 09:28 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		$user = Factory::getApplication()->getIdentity();
Unused variable

2021-09-02 09:28 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		if ($customObj = $this->getState('list.customClass'))
Unused variable

2021-09-02 09:29 UTC, Denitz commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +	 * @param   string            $group     The field name group control value. This acts as as an array container for the field.
as as

2021-09-02 09:29 UTC, Denitz commented on administrator/components/com_scheduler/src/Field/CronField.php
> +	 * @param   string            $group     The field name group control value. This acts as as an array container for the field.
as as

2021-09-02 09:32 UTC, Denitz commented
@ditsuke 

1. Why postgres schema of `#__scheduler_tasks` has `"id" int GENERATED ALWAYS AS IDENTITY,`?

Shouldn't it be `"id" serial NOT NULL,` with `PRIMARY KEY ("id")` as a common case for all tables in installation sql?

2. Why mysql schema has \`title\` varchar(128) NOT NULL UNIQUE` ?

We can safely use \`title\` varchar(255) NOT NULL DEFAULT '', as in other tables.

3. Missing multiple edit block via `checked_out` and `checked_out_time`

4. I am afraid of scheduler system plugin `PlgSystemSchedulerunner` will still attach events via `getSubscribedEvents` method even though `com_scheduler` is not enabled.

5. `PlgSystemSchedulerunner` actually doesn't use own language strings, what for it auto-loads language?

6. If the component name is `com_scheduler`, isn't it more informative to have the plugin group `scheduler` but not `task`? Even `tasks` is plural is better.

7. Added some comments in PR.

2021-09-02 09:33 UTC, Denitz commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +final class SchedulerHelper
Why final? What if a developer wants to create own custom helper extending this one?

2021-09-02 09:38 UTC, Denitz commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +final class SchedulerHelper
Why final? What if a developer wants to create own custom helper extending this one?

2021-09-02 10:40 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		) use ($query, &$filterCount) {
If I'm not wrong, we need to pass by reference to the `use` construct so the closure is aware of updates on `$filterCount` in the function body.

2021-09-02 11:40 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +	private function attachTaskOptions(array &$items): void
Thanks, now that I think of it we don't need to! 😅

2021-09-02 11:44 UTC, ditsuke commented on administrator/components/com_scheduler/src/Task/Task.php
> +				'eventClass'      => 'Joomla\Component\Scheduler\Administrator\Event\ExecuteTaskEvent',
I believe something went wrong back when I tried. I'll give it a try and report back!

2021-09-02 11:45 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/CronField.php
> +		$subtype = (string) $element['subtype'] ?? null;
Thanks for finding these troublesome casts!

2021-09-02 11:46 UTC, ditsuke commented on administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
> +			? (object) json_decode($rule)
Whoops! A little mixup some commits back.

2021-09-02 11:49 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +	public function getItems()
I don't understand, what's the problem here?

2021-09-02 11:49 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +	 * @param   string            $group     The field name group control value. This acts as as an array container for the field.
Gave me a check, thanks! 😄

2021-09-02 12:14 UTC, ditsuke commented
@Denitz

Thank you for the suggestions and the in-depth review. I'll work on addressing all of the issues in time.
> 
> 
> @ditsuke
> 
> 1. Why postgres schema of `#__scheduler_tasks` has `"id" int GENERATED ALWAYS AS IDENTITY,`?
> 
> 
> Shouldn't it be `"id" serial NOT NULL,` with `PRIMARY KEY ("id")` as a common case for all tables in installation sql?
> 
> 1. Why mysql schema has `title` varchar(128) NOT NULL UNIQUE` ?
> 
> 
> We can safely use `title` varchar(255) NOT NULL DEFAULT '', as in other tables.
> 

Agreed, I'll alter the DDL as suggested!

> 1. Missing multiple edit block via `checked_out` and `checked_out_time`
> 

I'm not sure if we need these in the context of tasks. Opinions?

> 2. I am afraid of scheduler system plugin `PlgSystemSchedulerunner` will still attach events via `getSubscribedEvents` method even though `com_scheduler` is not enabled.
> 

I'll investigate and address this soon.

> 3. `PlgSystemSchedulerunner` actually doesn't use own language strings, what for it auto-loads language?
> 

Good eye! It's a remnant from back when it did a lot more.

> 4. If the component name is `com_scheduler`, isn't it more informative to have the plugin group `scheduler` but not `task`? Even `tasks` is plural is better.
> 

I'm note sure, since I observed we're using singulars in all other plugin groups. I'm a bit against 'scheduler' since in theory tasks can be unscheduled (single use and such).

> 5. Huge issue: the component will query `#__scheduler_tasks` on each page load, should be optimized somehow.
> 

Good point! I'll talk about this with me mentor so we can think of a possible solution. Do you have any suggestions?

2021-09-02 15:16 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		) use ($query, &$filterCount) {
Passing by reference is required if `$filterCount` is changed in the closure body and this change should be reflected in the upper scope. Here, the closure body doesn't modify `$filterCount` value.

2021-09-02 15:21 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +	public function getItems()
@ditsuke The method `getItems` only calls the parent one, there is no purpose for this method in this class.

2021-09-02 15:41 UTC, Denitz commented
Multiple edit block via `checked_out` and `checked_out_time` - this feature is common in Joomla, we 100% should have it for core component!

In any case it's easier to spot that plugins of group `scheduler` belong to `com_scheduler`! `finder` group for `com_finder`, `workflow` - `com_workflow` etc., please don't break the logic.

Limiting the database query to load tasks on each page load - I guess the component should pre-compile possible execute time and date options and store them as a component param (re-compile on each task edit/create/delete/state-changed), hence it will be available via component params without extra load. Next initially we should check the available special patterns using the current date and time if the moment has come etc.
It's the complex problem, requires days... Especially problematic is handling the expired tasks.

Or just an idea: assuming that the number of tasks is not high, at least maybe we can store the TaskId=>NextExecutionUtcTimestamp in the component params (re-compile as noted above) and just check these timestamps against current `time()` - sounds good and easier for me.

Besides, I didn't check how the task is actually executed, but I guess it's not queued and executed within the current request - it's weird. Maybe a separate ajax call should be scheduled first for the page load which has triggered the task, next this separate call sets the task flag 'In Progress', hashes are updated to not trigger the race condition (at least to minimize it) and only next the task is actually executed with ignoring user abort on request, setting time limit to 0 etc.

Btw what if the task was expired but didn't run in time? Will it be executed later on the first next page load?

2021-09-02 17:04 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		) use ($query, &$filterCount) {
So I'm reporting after just having tested this again and confirming passing by value breaks filtering. It appears pass by reference is required when reading inside of the closure a value we expect to be updated outside after the closure declaration. I assume this is because the `use` construct binds the variable to the closure on declaration so if we pass by value it would mean the closure has its own copy and any changes made afterwards in the original scope of `$filterCount` do not reflect inside of the closure.

2021-09-02 17:08 UTC, ditsuke commented on administrator/components/com_scheduler/src/Task/Task.php
> +				'eventClass'      => 'Joomla\Component\Scheduler\Administrator\Event\ExecuteTaskEvent',
Thanks, this worked out!

2021-09-03 08:27 UTC, Denitz commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		) use ($query, &$filterCount) {
Reference is required if closure code changes the variable and these changes should be reflected in the variable used after the closure execution. The code of this closure doesn't change variable, only compares its value. Please correct me if I missed smth. It's not the serious issue, but just a note.

2021-09-11 15:45 UTC, ditsuke commented
> Multiple edit block via `checked_out` and `checked_out_time` - this feature is common in Joomla, we 100% should have it for core component!
> 

These have been added to the table now.

> In any case it's easier to spot that plugins of group `scheduler` belong to `com_scheduler`! `finder` group for `com_finder`, `workflow` - `com_workflow` etc., please don't break the logic.
> 

We'll likely make this switch :)

> Limiting the database query to load tasks on each page load - I guess the component should pre-compile possible execute time and date options and store them as a component param (re-compile on each task edit/create/delete/state-changed), hence it will be available via component params without extra load. Next initially we should check the available special patterns using the current date and time if the moment has come etc.
> It's the complex problem, requires days... Especially problematic is handling the expired tasks. In any case, it's not the trivial select->foreach->echo coding!
> 
> Or just an idea: assuming that the number of tasks is not high, at least maybe we can store the TaskId=>NextExecutionUtcTimestamp in the component params (re-compile as noted above) and just check these timestamps against current `time()` - sounds good and easier for me.
> 

So the way we're handling task execution right now is we load only a single entry from the database on each load. This is made possible because pre-compute the next execution each time a task is executed, so then we only have to rely on a simple logic to check if the task is due and then get queue-like behavior by sorting on basis of priority and how far back the execution was supposed to happen. We are open to considering a more performant solution but this might just be good enough.

> Besides, I didn't check how the task is actually executed, but I guess it's not queued and executed within the current request - it's weird. Maybe a separate ajax call should be scheduled first for the page load which has triggered the task, next this separate call sets the task flag 'In Progress', hashes are updated to not trigger the race condition (at least to minimize it) and only next the task is actually executed with ignoring user abort on request, setting time limit to 0 etc.
> 

I really like the AJAX idea! Indeed right now we execute it within the current request, but I think once we have the Scheduler API extension ready we can work on an alternative AJAX solution. I'll discuss this with my mentor when we get to this. 

> Btw what if the task was expired but didn't run in time? Will it be executed later on the first next page load?

That's right, expired or overdue tasks are executed lazily. We use a queue like behavior that takes into account task priority + (planned) execution time if multiple tasks are queued. This is all done within the database query (the [Scheduler](https://github.com/joomla-projects/soc21_website-cronjob/blob/dcon/administrator/components/com_scheduler/src/Scheduler/Scheduler.php#L161) class for reference).

2021-09-11 15:59 UTC, ditsuke commented on administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-08-08.sql
> +	`ordering` int NOT NULL DEFAULT 0 COMMENT 'Configurable list ordering',
A task priority has been implemented now. Thank you for bringing up this suggestion.

2021-09-11 16:02 UTC, ditsuke commented on administrator/components/com_scheduler/tmpl/select/default.php
> +			<?php foreach ($this->items as &$item) : ?>
Redundant reference passes have been resolved!

2021-09-11 16:02 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +				function (string $x): int {
Done

2021-09-11 16:04 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/CronField.php
> +		$subtype = (string) $element['subtype'] ?? null;
I've resolved these casts with the latest commits. Although if some of them went by undetected, they'll have to wait 😄

2021-09-11 16:07 UTC, ditsuke commented on administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
> +			? (object) json_decode($rule)
Finally revisiting this, appears it might not always be the case like if the string is [deformed](https://www.php.net/manual/en/function.json-decode.php#refsect1-function.json-decode-returnvalues).

2021-09-11 16:07 UTC, ditsuke commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +	protected static $taskOptionsCache = null;
thanks!

2021-09-11 16:08 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +	 * @param   string            $group     The field name group control value. This acts as as an array container for the field.
Resolved

2021-09-17 11:53 UTC, brianteeman commented on libraries/src/Console/TasksListCommand.php
> +				// phpcs:ignore
red flag

2021-09-17 11:55 UTC, PhilETaylor commented on libraries/src/Console/TasksListCommand.php
> + */
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
 * @license       GNU General Public License version 2 or later; see LICENSE.txt
 */
```

2021-09-17 11:56 UTC, brianteeman commented on libraries/src/Service/Provider/Application.php
> +					$debug = $config->get('debug_lang');
please revert this change

2021-09-17 11:59 UTC, PhilETaylor commented on administrator/components/com_modules/tmpl/select/default.php
> + * phpcs:ignoreFile
please remove

2021-09-17 12:01 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +/** Implements the default controller (DisplayController) for com_scheduler */
```suggestion
```

2021-09-17 12:03 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +use function defined;
I dont think this level of include is required in Joomla.

2021-09-17 12:05 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +final class SchedulerHelper
Why are you using final? this prevents other developers extending classes.

2021-09-17 12:06 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +	 * Private constructor to prevent instantiation
Im not sure what others will say, but providing a Private constructor to prevent instantiation is a really really tacky want to code :(

2021-09-18 07:08 UTC, ditsuke commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +final class SchedulerHelper
I see your point, I failed see the need before.

2021-09-18 07:09 UTC, ditsuke commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +	 * Private constructor to prevent instantiation
Since we're removing the `final`, making it abstract should now be possible 🙂

2021-09-18 09:01 UTC, ditsuke commented on administrator/components/com_modules/tmpl/select/default.php
> + * phpcs:ignoreFile
phpcs is never happy with template files :(

2021-09-18 09:02 UTC, ditsuke commented on libraries/src/Console/TasksListCommand.php
> +				// phpcs:ignore
Its only there because of the `_` in task->next_execution

2021-09-18 09:03 UTC, ditsuke commented on libraries/src/Service/Provider/Application.php
> +					$debug = $config->get('debug_lang');
will do :)

2021-09-18 14:11 UTC, brianteeman commented on administrator/components/com_scheduler/forms/filter_tasks.xml
> +			<option value="">JGLOBAL_SORT_BY</option>
This list should be sorted to match the order of the displayed columns

2021-09-18 14:12 UTC, brianteeman commented on administrator/components/com_scheduler/forms/task.xml
> +<!-- @todo : Replace all labels with translatable strings. -->
please remove this todo

2021-09-18 14:12 UTC, brianteeman commented on administrator/components/com_scheduler/forms/task.xml
> +			<!-- @todo remove this! -->
??

2021-09-18 14:20 UTC, brianteeman commented on administrator/components/com_scheduler/src/Field/CronField.php
> +	private const OPTIONS_RANGE = [
These should be inheriting the date settings in the language xml file.

2021-09-18 14:22 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_NO_NOTE=""
??

2021-09-18 14:22 UTC, nibra commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> + */
This kind of comment does not serve any purpose - it's neither file nor class comment. If you want to keep relevant information, move it to the class docblock.

2021-09-18 14:23 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_LABEL_NOTES="Notes"
```suggestion
COM_SCHEDULER_LABEL_NOTES="Note"
```

2021-09-18 14:25 UTC, nibra commented on administrator/components/com_scheduler/src/Controller/TasksController.php
> +use function defined;
Don't import native global functions or classes. Use `\defined` inline instead.

2021-09-18 14:26 UTC, nibra commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> +/** Implements the ExecuteTaskEvent Event. */
This information is already part of the class declaration.

2021-09-18 14:27 UTC, nibra commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> +		if ($snapshot)
`$snapshot` is an array, not a boolean. What are you intending to test?

2021-09-18 14:28 UTC, nibra commented on administrator/components/com_scheduler/src/Extension/SchedulerComponent.php
> +		// Pass
You could setup the Logger here, retrieving it from the container

2021-09-18 14:38 UTC, nibra commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +		if (!($subtype && array_key_exists($subtype, self::SUBTYPES)))
`$subtype` is a string or null, not a boolean. What do you intend to test here?

2021-09-18 14:43 UTC, nibra commented on administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
> +				$lastExec = Factory::getDate($basisNow ? 'now' : $this->getFromTask('last_execution'), 'GMT');
Should either be `UTC` or the server's timezone instead of `GMT`

2021-09-18 14:46 UTC, nibra commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +final class SchedulerHelper
`final` must only be used on classes that solely implement interfaces. Otherwise, it is not possible to create test doubles.

2021-09-18 14:47 UTC, nibra commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +	 * Private constructor to prevent instantiation
Yes `abstract` is the way to go

2021-09-18 14:52 UTC, nibra commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +		return true;
Line 312-317 can be shortened to `return parent::save($data);`

2021-09-18 14:54 UTC, nibra commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +	private function processExecutionRules(array &$data): void
I'd prefer to return the modified `$data` instead of modifying them in-place.

2021-09-18 14:59 UTC, nibra commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		) use ($query, &$filterCount) {
Inherited variable's (those in `use()`) value is from when the function is defined, not when called

2021-09-18 15:01 UTC, nibra commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		if (is_numeric($due = $this->getState('filter.due')) && $due != 0)
Separate assignment and test into two statements.

2021-09-18 15:05 UTC, nibra commented on administrator/components/com_scheduler/src/Scheduler/Scheduler.php
> +		if (!$record)
`if ($record !== null)`, I guess...

2021-09-18 15:06 UTC, nibra commented on administrator/components/com_scheduler/src/Scheduler/Scheduler.php
> +		if ($id)
`if ($id !== 0)`

2021-09-18 15:06 UTC, nibra commented on administrator/components/com_scheduler/src/Scheduler/Scheduler.php
> +		elseif ($title)
`elseif ($title !== '')`

2021-09-18 15:08 UTC, nibra commented on administrator/components/com_scheduler/src/Task/Task.php
> +			Log::addLogger($options, Log::ALL, [$this->logCategory]);
Use the logger provided in the container.

2021-09-18 15:12 UTC, nibra commented on administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
> +		Log::add(Text::_('COM_SCHEDULER_ROUTINE_LOG_PREFIX') . $message, $priorityMap[$priority] ?? Log::INFO, $category);
Use logger from container

2021-09-18 15:16 UTC, nibra commented on administrator/components/com_scheduler/tmpl/select/default.php
> +				<!-- The task card ends here -->
Since `$item` is a reference, you need to unset it here.

2021-09-18 15:20 UTC, nibra commented on administrator/components/com_scheduler/tmpl/select/default.php
> +				<!-- The task card begins -->
This comment (and the corresponding end comment) tells you that you want to extract this block into its own method `renderTaskCard($name, $desc, $link, $function)` or `renderTaskCard($item, $function)`.

2021-09-18 15:23 UTC, nibra commented on administrator/components/com_scheduler/tmpl/tasks/default.php
> +
Although static analysis (by the IDE) sees a problem here, this check is not necessary; execution will not get here, if the application is not set.

2021-09-18 15:30 UTC, nibra commented on libraries/src/Console/TasksListCommand.php
> +				// phpcs:ignore
So why isn't it `$task->nextExecution`?

2021-09-18 15:30 UTC, nibra commented on libraries/src/Console/TasksListCommand.php
> +				$nextExec = Factory::getDate($task->next_execution, 'GMT');
Should be `UTC` or server time zone instead of `GMT`

2021-09-18 15:33 UTC, nibra commented on plugins/system/schedulerunner/schedulerunner.php
> +	public function __construct(&$subject, $config = [])
Objects are *always* passed by reference, so `&` is wrong.

2021-09-18 15:35 UTC, nibra commented on plugins/system/tasknotification/tasknotification.php
> +		$uFactory = Factory::getContainer()->get('user.factory');
Don't abbreviate. It is `$userFactory`.

2021-09-18 15:36 UTC, nibra commented on plugins/task/checkfiles/checkfiles.php
> +/** A task plugin with routines to make HTTP requests. */
A left-over from copy&paste?

2021-09-18 15:37 UTC, nibra commented on plugins/task/checkfiles/checkfiles.php
> +	public function makeRequest(ExecuteTaskEvent $event): void
Is `makeRequest` a proper name here?

2021-09-18 15:41 UTC, nibra requested changes
In a quick review, I found a few little things. What I really still miss are automated tests.

2021-09-18 20:36 UTC, HLeithner commented on plugins/system/schedulerunner/schedulerunner.php
> +			'onBeforeRender' => ['registerRunner', PHP_INT_MAX]
Nice try, but please use the allowed definitions
```suggestion
			'onBeforeRender' => ['registerRunner', \Joomla\Event\Priority::MAX]
```

2021-09-19 21:30 UTC, ditsuke commented on plugins/system/tasknotification/tasknotification.php
> +		$uFactory = Factory::getContainer()->get('user.factory');
No idea why I did this!

2021-09-19 21:31 UTC, ditsuke commented on administrator/components/com_scheduler/tmpl/select/default.php
> +				<!-- The task card begins -->
Love this idea :)

2021-09-19 21:32 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		if (is_numeric($due = $this->getState('filter.due')) && $due != 0)
Will do!

2021-09-19 21:32 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +	private function processExecutionRules(array &$data): void
Now that I think, I'd prefer that too 😃

2021-09-19 21:32 UTC, ditsuke commented on administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
> +				$lastExec = Factory::getDate($basisNow ? 'now' : $this->getFromTask('last_execution'), 'GMT');
Noted!

2021-09-19 21:37 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +		if (!($subtype && array_key_exists($subtype, self::SUBTYPES)))
`$subtype` is not null and that it exists in `self::SUBTYPES`. null and an empty string should evaluate to false so we don't call `array_key_exists` (I'm not sure of the behavior with a null call)

2021-09-19 21:38 UTC, ditsuke commented on administrator/components/com_scheduler/src/Extension/SchedulerComponent.php
> +		// Pass
Great idea! Might reach out if I need help with that 🙂

2021-09-19 21:41 UTC, ditsuke commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> +		if ($snapshot)
Empty array should evaluate to false, though now I think we should have a better test instead or maybe enforce an object.

2021-09-19 21:42 UTC, ditsuke commented on administrator/components/com_scheduler/src/Controller/TasksController.php
> +use function defined;
I think I've done this all over, might need a while to fix. Is there any automated way to go about this? 😥

2021-09-19 21:44 UTC, ditsuke commented on administrator/components/com_scheduler/forms/task.xml
> +			<!-- @todo remove this! -->
Need to remove this column from the db and the form, rather hasty job at covering up! 😅

2021-09-19 21:47 UTC, ditsuke commented on plugins/task/checkfiles/checkfiles.php
> +	public function makeRequest(ExecuteTaskEvent $event): void
Definitely not! Hacked this together the day before shouldn't have been merged into the PR yet 😃

2021-09-19 21:47 UTC, ditsuke commented on plugins/task/checkfiles/checkfiles.php
> +/** A task plugin with routines to make HTTP requests. */
Yes and yes!

2021-09-19 21:57 UTC, ditsuke commented on plugins/system/schedulerunner/schedulerunner.php
> +			'onBeforeRender' => ['registerRunner', PHP_INT_MAX]
Neat, will do! 😃

2021-09-19 22:12 UTC, ditsuke commented
@nibra
> In a quick review, I found a few little things. What I really still miss are automated tests.

Thank you for the review! I also feel we can use tests, much helpful here with how much things have grown. Will try my hands at them when possible. 🙂

2021-09-20 09:45 UTC, nibra commented on administrator/components/com_scheduler/src/Controller/TasksController.php
> +use function defined;
I'm not aware of an automated way. I'd just remove the `use` declarations and add the backslash where the IDE complains.

2021-09-20 09:47 UTC, nibra commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> +		if ($snapshot)
Always test, what you really want to test. Never rely on hidden casts, they might change.

2021-09-20 09:49 UTC, nibra commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +		if (!($subtype && array_key_exists($subtype, self::SUBTYPES)))
So you want to know, if $subtype` is `empty()`...

2021-09-20 15:25 UTC, ditsuke commented on administrator/components/com_scheduler/src/Controller/TasksController.php
> +use function defined;
Noted, will work on getting this done gradually!

2021-09-20 15:26 UTC, ditsuke commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> +		if ($snapshot)
I see your point, will switch things over to this approach as we do some refactoring.

2021-09-22 15:18 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +		if (!($subtype && array_key_exists($subtype, self::SUBTYPES)))
That does it, thank you 🙂

2021-09-22 15:22 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +		return true;
Good eye! done and done

2021-09-23 10:41 UTC, ditsuke commented on plugins/system/schedulerunner/schedulerunner.php
> +	public function __construct(&$subject, $config = [])
I guess then this needs to be resolved here
https://github.com/ditsuke/joomla-cms/blob/dcon/libraries/src/Plugin/CMSPlugin.php#L88

2021-09-23 12:34 UTC, nibra commented on plugins/system/schedulerunner/schedulerunner.php
> +	public function __construct(&$subject, $config = [])
Yes, you're right. So you need to leave it as is, since you're not allowed to change signature in derived classes. :(

2021-09-23 19:47 UTC, ditsuke commented on libraries/src/Console/TasksListCommand.php
> +				// phpcs:ignore
Because it's a row from `#__scheduler_tasks` 🙁

2021-09-23 20:44 UTC, ditsuke commented on administrator/components/com_scheduler/src/Extension/SchedulerComponent.php
> +		// Pass
Hi Niels, getting the logger from the Container (`container->get('logger')`) returns an instance of `DelegatingPsrLogger` which hides the actual `Log` instance as a protected member.

What should be the right way with this to add log routers like with `Log::addLogger()` ?

2021-09-23 21:47 UTC, nibra commented on administrator/components/com_scheduler/src/Extension/SchedulerComponent.php
> +		// Pass
So, what's the problem? You don't need access to the decorated logger. Just send your log messages to whatever logger you get. It will implement the LoggerInterface, so you know how to talk to it.

2021-09-29 20:53 UTC, PhilETaylor commented on administrator/components/com_modules/tmpl/select/default.php
> + * phpcs:ignoreFile
This still needs removing and the code style in the file fixing.

2021-09-29 20:55 UTC, PhilETaylor commented on administrator/components/com_scheduler/scheduler.xml
> +	<media destination=">" folder="media">
I have never seen a `destination=">"` before - is it correct?

2021-09-29 20:55 UTC, PhilETaylor commented on administrator/components/com_scheduler/services/provider.php
> +/** Returns the service provider class for com_scheduler. */
Joomla doesnt put file comments at the top of files like this, if needed it can be merged to the class comment block

2021-09-29 20:56 UTC, PhilETaylor commented on administrator/components/com_scheduler/services/provider.php
> +		*/
```suggestion
		/**
		 * Register the MVCFactory and ComponentDispatcherFactory providers to map
		 * 'MVCFactoryInterface' and 'ComponentDispatcherFactoryInterface' to their
		 * initializers and register them with the component's DI container.
		 */
```

2021-09-29 20:57 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +/** Implements the default controller (DisplayController) for com_scheduler */
This still needs doing, but you make it as resolved, all the file comments in all PHP files should be removed, and if needed, merged into the Class documentation blocks.

2021-09-29 20:58 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +use function defined;
Dont do this :) just namespace these method calls

2021-09-29 20:58 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 20:59 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +	 * @since  __DEPLOY_VERSION__
`@thows` should be after `@since` - see documentation on Class Method DocBlocks and Functions DocBlocks at https://developer.joomla.org/coding-standards/docblocks.html

2021-09-29 21:05 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +		$isValid = true;
No need for a local variable, just return true/false.

2021-09-29 21:06 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +		switch ($layout)
There is no need for a switch if you only have one thing to switch on, cleaner to use an if statement and implement return early.

2021-09-29 21:06 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:07 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +use function defined;
You marked this as resolved but its not

2021-09-29 21:07 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:07 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +	 * @since  __DEPLOY_VERSION__
`@thows` should be after `@since` - see documentation on Class Method DocBlocks and Functions DocBlocks at https://developer.joomla.org/coding-standards/docblocks.html and there should be blank lines between each

2021-09-29 21:11 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +		*/
```suggestion
		/**
		 * Zero record (id:0), return component edit permission by calling parent controller method
		 * ? : Is this the right way to do this?
		 */
```

2021-09-29 21:11 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TasksController.php
> + * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright       (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:11 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TasksController.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:11 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TasksController.php
> +use function defined;
```suggestion
```

2021-09-29 21:12 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:12 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:12 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> +		if (! ($arguments['subject'] ?? null) instanceof Task)
```suggestion
		if (!($arguments['subject'] ?? null) instanceof Task)
```

2021-09-29 21:12 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Event/ExecuteTaskEvent.php
> +	 */
```suggestion
	/**
	 * @return integer  The task's taskId.
	 *
	 * @since  __DEPLOY_VERSION__
	 */
```

2021-09-29 21:12 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Extension/SchedulerComponent.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:13 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Extension/SchedulerComponent.php
> +use function defined;
```suggestion
```

2021-09-29 21:13 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Extension/SchedulerComponent.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:13 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:13 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:13 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +use function range;
```suggestion
```

2021-09-29 21:14 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +	 * @since  __DEPLOY_VERSION__
```suggestion
	 * @var string[]
	 *
	 * @since  __DEPLOY_VERSION__
```

2021-09-29 21:14 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +	 * @since  __DEPLOY_VERSION__
```suggestion
	 * Count of predefined options for each subtype
	 *
	 * @var int[][]
	 *
	 * @since  __DEPLOY_VERSION__
```

2021-09-29 21:14 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +	 * @since  __DEPLOY_VERSION__
```suggestion
	 * @var    string
	 *
	 * @since  __DEPLOY_VERSION__
```

2021-09-29 21:14 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +	 * @since  __DEPLOY_VERSION__
repeat adding these lines to all property docblocks

2021-09-29 21:15 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +		if (!($subtype && in_array($subtype, self::SUBTYPES)))
```suggestion
		if (!($subtype && \in_array($subtype, self::SUBTYPES)))
```

2021-09-29 21:15 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +		if (!in_array($subtype, self::SUBTYPES))
```suggestion
		if (!\in_array($subtype, self::SUBTYPES))
```

2021-09-29 21:15 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +			$labels = range(... self::OPTIONS_RANGE[$subtype]);
```suggestion
			$labels = \range(... self::OPTIONS_RANGE[$subtype]);
```

2021-09-29 21:15 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/ExecutionRuleField.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:15 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/ExecutionRuleField.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:16 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/ExecutionRuleField.php
> +	 * @since  __DEPLOY_VERSION__
```suggestion
	 * @var    string
	 *
	 * @since  __DEPLOY_VERSION__
```

2021-09-29 21:16 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/ExecutionRuleField.php
> +	 * @since  __DEPLOY_VERSION__
```suggestion
	 * @var string[]
	 *
	 * @since  __DEPLOY_VERSION__
```

2021-09-29 21:17 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/ExecutionRuleField.php
> +		'custom' => 'COM_SCHEDULER_OPTION_INTERVAL_CUSTOM'
as per https://developer.joomla.org/coding-standards/php-code.html arrays should have trailing commas

```
 When splitting array definitions onto several lines, the last value should also have a trailing comma. This is valid PHP syntax and helps to keep code diffs minimal.
```


```suggestion
		'custom' => 'COM_SCHEDULER_OPTION_INTERVAL_CUSTOM',
```

2021-09-29 21:18 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:18 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:18 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/IntervalField.php
> +	 * @since  3.2
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-09-29 21:18 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/TaskStateField.php
> + * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright       (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:18 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/TaskStateField.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:19 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/TaskStateField.php
> +		'*' => 'JALL'
Arrays should have trailing commas https://developer.joomla.org/coding-standards/php-code.html

```suggestion
		'*' => 'JALL',
```

2021-09-29 21:19 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/TaskTypeField.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:21 UTC, PhilETaylor commented
@ditsuke Im not sure if you are aware, but for 99% of the suggested changes I and other make, when a suggestion is given as a code diff, you can simply go to the PR list of files here: https://github.com/joomla/joomla-cms/pull/35143/files and click `Apply Suggestion` next to them, and then do a git pull to get those changes into your local repo. 

Its much easier that way to merge the million small changes and not lose them. Just a tip.

2021-09-29 21:28 UTC, brianteeman commented on administrator/components/com_scheduler/scheduler.xml
> +	<media destination=">" folder="media">
it should be in the format
	`<media destination="templates/site/cassy" folder="assets">`

2021-09-29 21:32 UTC, PhilETaylor commented on plugins/task/requests/requests.php
> +			return TaskStatus::TIMEOUT;
Need to log that the task failed due to an exception.

Are there other exceptions that could be caught apart from Timeout? If so they should each be correctly caught and handled.

2021-09-29 21:34 UTC, PhilETaylor commented on plugins/task/requests/requests.php
> +		$options->set('Content-Type', 'application/json');
You cant set a `application/json` on a GET request as you are sending no body?!

2021-09-29 21:35 UTC, PhilETaylor commented on plugins/task/demotasks/demotasks.php
> +			'form'            => 'testTaskForm'
```suggestion
			'form'            => 'testTaskForm',
```

2021-09-29 21:35 UTC, PhilETaylor commented on plugins/task/demotasks/demotasks.php
> +			'call'            => 'stressMemory'
```suggestion
			'call'            => 'stressMemory',
```

2021-09-29 21:35 UTC, PhilETaylor commented on plugins/task/demotasks/demotasks.php
> +			'call'            => 'stressMemoryRemoveLimit'
```suggestion
			'call'            => 'stressMemoryRemoveLimit',
```

2021-09-29 21:35 UTC, PhilETaylor commented on plugins/task/demotasks/demotasks.php
> +		'com_scheduler.task'
```suggestion
		'com_scheduler.task',
```

2021-09-29 21:36 UTC, PhilETaylor commented on plugins/task/demotasks/demotasks.php
> +	 * @since __DEPLOY__
```suggestion
	 * @since __DEPLOY_VERSION__
```

2021-09-29 21:36 UTC, PhilETaylor commented on plugins/task/demotasks/demotasks.php
> +	 * @since  __DEPLOY_VERSION
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-09-29 21:36 UTC, PhilETaylor commented on plugins/task/demotasks/demotasks.php
> +	 * @throws  Exception
Throws should come after Since

2021-09-29 21:37 UTC, PhilETaylor commented on plugins/task/demotasks/demotasks.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:37 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:38 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> +	 */
```suggestion
	/**
	 * @var string[]
	 *
	 * @since __DEPLOY_VERSION__
	 */
```

2021-09-29 21:38 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> +			'call'            => 'checkImages'
```suggestion
			'call'            => 'checkImages',
```

2021-09-29 21:38 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> +		'com_scheduler.task'
```suggestion
		'com_scheduler.task',
```

2021-09-29 21:38 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> +			'onContentPrepareForm' => 'enhanceForm'
```suggestion
			'onContentPrepareForm' => 'enhanceForm',
```

2021-09-29 21:38 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> +	 * @since __DEPLOY_VERSION__
Throws should come after Since and there should be a line between them

2021-09-29 21:39 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> +			$this->addTaskLog('Image path does not exist!', 'warning');
Can this be moved to a language file or reuse one of the existing language strings we have?

2021-09-29 21:40 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> +			$imageFile->resize($newWidth, $newHeight)->toFile($image, $type);
This can and will throw exceptions that need to be caught like `LogicException`

2021-09-29 21:41 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> +			$resize = $properties->$dimension > $limit;
Is `>` ok here or should it be `>=` ?

2021-09-29 21:44 UTC, PhilETaylor commented on plugins/system/tasknotification/tasknotification.php
> +			return;
if you are going to log PLG_SYSTEM_TASK_NOTIFICATION_NOTIFY_SEND_EMAIL_FAIL if a mail doesnt get sent, then you should probably log something here to say there are no users to email.

2021-09-29 21:49 UTC, PhilETaylor commented on plugins/system/tasknotification/tasknotification.php
> +		// Get all admin users
This query doesnt get all the admin users like this comment says, it gets users that have the legacy sendEmail flag on

2021-09-29 21:49 UTC, PhilETaylor commented on plugins/system/tasknotification/tasknotification.php
> +			'EXEC_DATE_TIME' => $lockOrExecTime
```suggestion
			'EXEC_DATE_TIME' => $lockOrExecTime,
```

2021-09-29 21:49 UTC, PhilETaylor commented on plugins/system/tasknotification/tasknotification.php
> +			'onTaskRecoverFailure'  => 'notifyFatalRecovery'
```suggestion
			'onTaskRecoverFailure'  => 'notifyFatalRecovery',
```

2021-09-29 21:50 UTC, PhilETaylor commented on libraries/src/Service/Provider/Application.php
> + * @license         GNU General Public License version 2 or later; see LICENSE.txt
This change needs reverting.

2021-09-29 21:59 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright     (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-09-29 21:59 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +defined('_JEXEC') or die;
```suggestion
\defined('_JEXEC') or die;
```

2021-09-29 21:59 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +use function sort;
```suggestion
```

2021-09-29 22:00 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +		'trashed' => -2
```suggestion
		'trashed' => -2,
```

2021-09-29 22:00 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +			$config['events_map']
```suggestion
			$config['events_map'],
```

2021-09-29 22:00 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +		*/
```suggestion
		/**
		 *  loadForm() (defined by FormBehaviourTrait) also loads the form data by calling
		 *  loadFormData() : $data [implemented here] and binds it to the form by calling
		 *  $form->bind($data).
		 */
```

2021-09-29 22:01 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +			/** @var CMSObject $data */
`CMSObject` is already deprecated. Use \stdClass or \Joomla\Registry\Registry instead.

2021-10-01 15:08 UTC, ditsuke commented on administrator/components/com_scheduler/scheduler.xml
> +	<media destination=">" folder="media">
This was definitely not correct! Fixed with https://github.com/ditsuke/joomla-cms/commit/f2c1b3d8a4a1cf7ae87efff263299a9a6c5cac7a

2021-10-01 15:40 UTC, ditsuke commented on administrator/components/com_scheduler/services/provider.php
> +/** Returns the service provider class for com_scheduler. */
Duly noted

2021-10-01 15:40 UTC, ditsuke commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +use function defined;
In the process of progressively phasing these out as I touch each file :)

2021-10-01 15:40 UTC, ditsuke commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +	 * @since  __DEPLOY_VERSION__
Thanks, I didn't realize! We probably have some violations in existing code, can't we have php-cs check for this?
https://github.com/joomla/joomla-cms/blob/4ee06a1fc3222f1c09ad5db37ebfe87deb7d40a8/libraries/src/WebAsset/WebAssetManagerInterface.php#L48-L50

2021-10-01 15:44 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/DisplayController.php
> +	 * @since  __DEPLOY_VERSION__
Joomla historically has not taken CodeStyle (ESPECIALLY COMMENTS) seriously enough and the php-cs rules run in drone are not covering even the basics of the Joomla Coding Standards, as evidenced here. Multiple attempts to propose and enforce stricter standards for existing code have failed to be approved and merged, and so all we can do is hope that new PR's get held to a higher standard and we resolve code style issues before they are actually merged, and clean up the other files one by one over the next decade. Search GitHub if you want to see the heated debates on this.

2021-10-01 16:28 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/CronField.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
Hi Phil, I can't get PHPStorm to align the (C) as part of the comments. Do you know of some way this can be accomplished?

2021-10-01 16:35 UTC, ditsuke commented on plugins/task/checkfiles/checkfiles.php
> +			$resize = $properties->$dimension > $limit;
I believe `>` should be okay, so we only touch files with dimension strictly greater than `$limit`.

2021-10-01 16:44 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
in phpStorm Preferences check that in Editor -> Code Style the "Enable EditorConfig support" is enabled - this should then read the `.editorconfig` file in the root for its code style settings then make sure you use spaces in comments (Like the headers) and tabs in PHP code. A tab is 4 spaces.

2021-10-01 18:28 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/CronField.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
I think I have this stuff set up fine, the problem is with the formatter configured to align comments after doc tags, it disregards the (C) and aligns comments to the part that comes after:

![image](https://user-images.githubusercontent.com/72784348/135668958-477bf2f6-60ee-482e-a0af-0c4e39f5ded7.png)

I think this might be desirable behavior but I imagine there should be a way to disable it.
Here's my PHPDoc code style config: https://imgur.com/a/ltwXZbU

2021-10-01 18:53 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> + * @copyright (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
It seems to be the option "Align Tag Comments" coupled with the fact the C is in brackets, disable that feature

2021-10-02 06:37 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/CronField.php
> +	 * @since  __DEPLOY_VERSION__
Do we have this spacing elsewhere for property docblocks?

2021-10-02 06:40 UTC, PhilETaylor commented
Read The Joomla! coding standards document


> On 2 Oct 2021, at 07:37, Tushar ***@***.***> wrote:
> 
> ﻿
> @ditsuke commented on this pull request.
> 
> In administrator/components/com_scheduler/src/Field/CronField.php:
> 
> > +	 * @var string[]
> +	 * @since  __DEPLOY_VERSION__
> Do we have this spacing elsewhere for property docblocks?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-10-31 20:52 UTC, ditsuke commented on plugins/system/tasknotification/tasknotification.php
> +		// Get all admin users
Hi Phil, finally getting back to going through some of the review - I was just updating this plugin incl the comment. Should I not be using the `sendEmail` flag and is there an alternative?

2021-10-31 22:57 UTC, ditsuke commented
Hello everyone, I'm glad to announce that the Scheduler is now open for testers and that at last this PR has graduated from its Draft status!

In the months since the opening of this PR, we have gone through a lot of code review, community discussions and brainstormed over what we need to get in first and the things that need to be fixed. While we have added a lot of functionality and refined yet more thanks all the generous code review, here's some notable features that are relatively new: 
1. Client-side AJAX based lazy runner so we no longer have to give visitors a bad experience, 
2. Email notifications (configurable on a per-task basis), 
3. Manual "play" button for tasks in the admin backend, 
4. CLI commands to trigger and list tasks (we still need creation and deletion!), 
5. Webcron functionality, i.e., an endpoint (not quite API) that can be enabled, protected and used to trigger tasks from an external service, 
6. Extensive component configuration options - so you get to choose to enable lazy scheduling, or to rely on native cron, and some granular control on the client-side scheduler trigger, 
.. and many other improvements/features.

While there's still some unresolved feedback and much more cool features I wish we'll implement in time, the Scheduler now needs testers so we can find bugs and deficiencies where they matter most. More code review and PRs are welcome so we can get the Scheduler and the Task infrastructure at the best place possible in time for 4.1.

2021-10-31 23:03 UTC, brianteeman commented on administrator/components/com_scheduler/access.xml
> +		<action name="core.testrun" title="COM_SCHEDULER_PERMISSION_TESTRUN"/>
```suggestion
		<action name="core.admin" title="JACTION_ADMIN" />
		<action name="core.options" title="JACTION_OPTIONS" />
		<action name="core.manage" title="JACTION_MANAGE" />
		<action name="core.create" title="JACTION_CREATE" />
		<action name="core.delete" title="JACTION_DELETE" />
		<action name="core.edit" title="JACTION_EDIT" />
		<action name="core.edit.state" title="JACTION_EDITSTATE" />
		<action name="core.testrun" title="COM_SCHEDULER_PERMISSION_TESTRUN" />
```

2021-10-31 23:03 UTC, brianteeman commented on administrator/components/com_scheduler/access.xml
> +		<action name="core.testrun" title="COM_SCHEDULER_PERMISSION_TESTRUN"/>
```suggestion
		<action name="core.delete" title="JACTION_DELETE" />
		<action name="core.edit" title="JACTION_EDIT" />
		<action name="core.edit.state" title="JACTION_EDITSTATE" />
		<action name="core.testrun" title="COM_SCHEDULER_PERMISSION_TESTRUN" />
```

2021-10-31 23:05 UTC, brianteeman commented on administrator/components/com_scheduler/config.xml
> +						addfieldprefix="Joomla\Component\Scheduler\Administrator\Field">
```suggestion
		<fields name="webcron" addfieldprefix="Joomla\Component\Scheduler\Administrator\Field">
```

2021-10-31 23:07 UTC, brianteeman commented on administrator/components/com_scheduler/layouts/form/field/webcron_link.php
> + * @copyright   (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

2021-10-31 23:07 UTC, brianteeman commented on administrator/components/com_scheduler/layouts/form/field/webcron_link.php
> +			value="<?php echo htmlspecialchars($value, ENT_COMPAT, 'UTF-8'); ?>"
```suggestion
		type="text"
		class="form-control"
		name="<?php echo $name; ?>"
		id="<?php echo $id; ?>"
		readonly
		value="<?php echo htmlspecialchars($value, ENT_COMPAT, 'UTF-8'); ?>"
```

2021-10-31 23:08 UTC, brianteeman commented on administrator/components/com_scheduler/layouts/form/field/webcron_link.php
> +			title="<?php echo Text::_('COM_SCHEDULER_CONFIG_WEBCRON_LINK_COPY_DESC'); ?>"><?php echo Text::_('JLIB_HTML_BATCH_COPY'); ?>
```suggestion
		class="btn btn-primary"
		type="button"
		id="link-copy"
		title="<?php echo Text::_('COM_SCHEDULER_CONFIG_WEBCRON_LINK_COPY_DESC'); ?>"><?php echo Text::_('JLIB_HTML_BATCH_COPY'); ?>
```

2021-10-31 23:11 UTC, brianteeman commented on administrator/components/com_scheduler/src/Model/SelectModel.php
> +	 * @param   ?MVCFactoryInterface  $factory  The factory.
```suggestion
	 * @param   MVCFactoryInterface  $factory  The factory.
```

2021-10-31 23:12 UTC, bembelimen commented
> While there's still some unresolved feedback and much more cool features I wish we'll implement in time, the Scheduler now needs testers so we can find bugs and deficiencies where they matter most. More code review and PRs are welcome so we can get the Scheduler and the Task infrastructure at the best place possible in time for 4.1.

Thank you very much @ditsuke for your superb effort to bring it on this state. And thanks for all the helper so far. Now the final spurt starts, ironing out things, make it stable and the target should be to get it merged for the Alpha 3 (November 23th) to have more than 2 month to work with it in core.

2021-10-31 23:17 UTC, brianteeman commented on administrator/components/com_scheduler/tmpl/tasks/default.php
> +									<span class="icon-ellipsis-v"></span>
```suggestion
									<span class="icon-ellipsis-v" aria-hidden="true"></span>
```

2021-10-31 23:19 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_DESCRIPTION_TASK_PRIORITY="⚠ This is an advanced option. Higher priority tasks can potentially block out lower priority tasks."
```suggestion
COM_SCHEDULER_DESCRIPTION_TASK_PRIORITY="This is an advanced option. Higher priority tasks can potentially block lower priority tasks."
```

best not to use emoji in language files

2021-10-31 23:20 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.sys.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Component for managing scheduled tasks and cronjobs (if supported by the server)"
```suggestion
COM_SCHEDULER_XML_DESCRIPTION="Component for managing scheduled tasks and cronjobs (if supported by the server)."
```

2021-10-31 23:21 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_XML_DESCRIPTION="Component for managing scheduled tasks and cronjobs (if supported by the server)"
```suggestion
COM_SCHEDULER_XML_DESCRIPTION="Component for managing scheduled tasks and cronjobs (if supported by the server)."
```

2021-10-31 23:23 UTC, brianteeman commented on libraries/src/Console/TasksListCommand.php
> +				$enabled = $task->state === 1;
```suggestion
				$enabled  = $task->state === 1;
```

2021-10-31 23:23 UTC, brianteeman commented on libraries/src/Console/TasksListCommand.php
> +	 * Returns an stdClass object array of scheduled tasks.
```suggestion
	 * Returns a stdClass object array of scheduled tasks.
```

2021-10-31 23:25 UTC, brianteeman commented on plugins/system/schedulerunner/language/en-GB/plg_system.schedulerunner.sys.ini
> +PLG_SYSTEM_SCHEDULE_RUNNER_XML_DESCRIPTION="This plugin lazily runs due tasks, managed through com_scheduler"
```suggestion
PLG_SYSTEM_SCHEDULE_RUNNER_XML_DESCRIPTION="This plugin lazily runs due tasks, managed through com_scheduler."
```

2021-10-31 23:25 UTC, brianteeman commented on plugins/system/schedulerunner/language/en-GB/plg_system_schedulerunner.ini
> +PLG_SYSTEM_SCHEDULE_RUNNER_XML_DESCRIPTION="This plugin lazily runs due tasks, managed through com_scheduler"
```suggestion
PLG_SYSTEM_SCHEDULE_RUNNER_XML_DESCRIPTION="This plugin lazily runs due tasks, managed through com_scheduler."
```

2021-10-31 23:26 UTC, brianteeman commented on plugins/task/demotasks/language/en-GB/plg_task_demotasks.ini
> +PLG_TASK_DEMO_TASKS_XML_DESCRIPTION="This is a demo plugin for the development of Joomla! Scheduled Tasks"
```suggestion
PLG_TASK_DEMO_TASKS_XML_DESCRIPTION="This is a demo plugin for the development of Joomla! Scheduled Tasks."
```

2021-10-31 23:26 UTC, brianteeman commented on plugins/task/demotasks/language/en-GB/plg_task_demotasks.sys.ini
> +PLG_TASK_DEMO_TASKS_XML_DESCRIPTION="This is a demo plugin for the development of Joomla! Scheduled Tasks"
```suggestion
PLG_TASK_DEMO_TASKS_XML_DESCRIPTION="This is a demo plugin for the development of Joomla! Scheduled Tasks."
```

2021-10-31 23:27 UTC, brianteeman commented on plugins/task/sitestatus/language/en-GB/plg_task_sitestatus.ini
> +PLG_TASK_SITE_STATUS_SET_OFFLINE_TITLE="Get Site Offline."
```suggestion
PLG_TASK_SITE_STATUS_SET_OFFLINE_TITLE="Set Site Offline."
```

2021-10-31 23:27 UTC, brianteeman commented on plugins/task/sitestatus/language/en-GB/plg_task_sitestatus.ini
> +PLG_TASK_SITE_STATUS_SET_ONLINE_TITLE="Get Site Online."
```suggestion
PLG_TASK_SITE_STATUS_SET_ONLINE_TITLE="Set Site Online."
```

2021-11-01 05:09 UTC, ditsuke commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_DESCRIPTION_TASK_PRIORITY="⚠ This is an advanced option. Higher priority tasks can potentially block out lower priority tasks."
Thanks 😅

2021-11-01 05:13 UTC, ditsuke commented on plugins/system/schedulerunner/language/en-GB/plg_system.schedulerunner.sys.ini
> +PLG_SYSTEM_SCHEDULE_RUNNER_XML_DESCRIPTION="This plugin lazily runs due tasks, managed through com_scheduler"
Reminder to myself: need to update this string as the plugin does more now.

2021-11-01 05:15 UTC, ditsuke commented on plugins/system/tasknotification/tasknotification.php
> +			return;
We log this now :)

2021-11-01 05:20 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/SelectModel.php
> +	 * @param   ?MVCFactoryInterface  $factory  The factory.
Shouldn't this stay as $factory is nullable?

2021-11-01 05:37 UTC, ditsuke commented on plugins/system/schedulerunner/language/en-GB/plg_system.schedulerunner.sys.ini
> +PLG_SYSTEM_SCHEDULE_RUNNER_XML_DESCRIPTION="This plugin lazily runs due tasks, managed through com_scheduler"
all done :)

2021-11-05 21:28 UTC, roland-d commented
@ditsuke I applied the files and in Discover I see an untranslated string for 1 plugin
![image](https://user-images.githubusercontent.com/359377/140580640-15313d53-e859-4416-8005-3cf104843009.png)

All the other plugins show the full description.

2021-11-05 21:32 UTC, roland-d commented
@ditsuke After installing via Discover I go to Scheduled tasks and see this error:
```
Table 'joomla4_db.e0f7f_scheduler_tasks' doesn't exist Table 'joomla4_db.e0f7f_scheduler_tasks' doesn't exist 
```

I then went to System -> Database and tried to update structure but it does not fix it either. The table is not created.

2021-11-05 21:44 UTC, roland-d commented
@ditsuke My final error, as I will stop now, I click on Create a new task and I am greeted by:
```
There is no "com_scheduler.admin-view-select-task-css" asset of a "style" type in the registry. 
```

2021-11-05 22:04 UTC, chmst commented
![image](https://user-images.githubusercontent.com/1035262/140583573-8c1a087f-3821-4026-a90e-f3b53f0323c2.png)

I suggest a description or expanded label here. What is the value? second, minute, hour?

2021-11-05 22:25 UTC, ditsuke commented
@roland-d 

> @ditsuke After installing via Discover I go to Scheduled tasks and see this error:
> 
> ```
> Table 'joomla4_db.e0f7f_scheduler_tasks' doesn't exist 
> ```
> 
> I then went to System -> Database and tried to update structure but it does not fix it either. The table is not created. So I tried to create the table myself but I see the following DB error:
> 
> ```
> Specified key was too long; max key length is 3072 bytes
> ```
> 
> I am running MySQL 5.7.29

Thank you for taking the time to debug this issue. I think I have now a good idea what's causing this. Will try a fix soon 🙂


> @ditsuke My final error, as I will stop now, I click on Create a new task and I am greeted by:
> 
> ```
> There is no "com_scheduler.admin-view-select-task-css" asset of a "style" type in the registry. 
> ```

This is a media asset that needs to be built first with the build tools. I'm not sure, how does the patchtester (i'm assuming) handle these?

2021-11-05 23:33 UTC, ditsuke commented
> ![image](https://user-images.githubusercontent.com/1035262/140583573-8c1a087f-3821-4026-a90e-f3b53f0323c2.png)
> 
> I suggest a description or expanded label here. What is the value? second, minute, hour?

Thanks. I think an expanded label should do. Does this work?

![image](https://user-images.githubusercontent.com/72784348/140589123-3344c54e-cee0-457d-9b1e-1da8ba72e9da.png)

2021-11-06 14:23 UTC, richard67 commented
@roland-d Installing with discovery installation would require that the component does not only provide SQL statements in the core scripts for new installation (e.g. base.sql) and update SQL scripts but also a component set of SQL scripts like we have them for historic reasons for some components and which people always forget to maintain. As we have stopped to provide them for our core extensions because there is no need to discover them under normal conditions, I think it is not needed to add them here.

Instead of testing with discovery installation I suggest to test with updating a clean 4.1-dev or latest 4.1 nightly to the patched update package or custom update URL created by drone for this PR.

2021-11-13 16:12 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +	 * @return boolean True if user is allowed to edit record
spaces needed

2021-11-13 16:14 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/CronField.php
> +			$labels = \range(... self::OPTIONS_RANGE[$subtype]);
```suggestion
			$labels = \range(...self::OPTIONS_RANGE[$subtype]);
```

2021-11-13 16:16 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
Something not right here? maybe you mean array merge and not `+` ?

2021-11-13 16:17 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
> +	 * @throws  \Exception
add new lines between each

2021-11-13 16:17 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/SelectModel.php
> +	 * @param   ?MVCFactoryInterface  $factory  The factory.
It should stay. Its correct.

2021-11-13 16:18 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +	 * @param   FormFactoryInterface|null  $formFactory  The form factory [?]
```suggestion
	 * @param   MVCFactoryInterface|null   $factory      The factory
	 * @param   FormFactoryInterface|null  $formFactory  The form factory
```

2021-11-13 16:18 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +	 * @param   FormFactoryInterface|null  $formFactory  The form factory [?]
```suggestion
	 * @param   ?MVCFactoryInterface|null   $factory      The factory [?]
	 * @param   ?FormFactoryInterface|null  $formFactory  The form factory [?]
```

2021-11-13 16:18 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +			// No "hacking" ._.
```suggestion
			// No "hacking"
```

2021-11-13 16:19 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +			// phpcs:ignore -- row from table
```suggestion
```

2021-11-13 16:21 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		/*
```suggestion
		/**
```

2021-11-13 16:21 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +	 * phpcs:disable
```suggestion
```

2021-11-13 16:22 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +		// phpcs:enable
```suggestion
```

2021-11-13 16:22 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TasksModel.php
> +	 * @param   ?string  $direction  Direction in which to sort list
```suggestion
	 * @param   string  $ordering   Field to order/sort list by
	 * @param   string  $direction  Direction in which to sort list
```

2021-11-13 16:23 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Scheduler/Scheduler.php
> + * @todo  A global instance?
```suggestion
```

2021-11-13 16:24 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Task/Task.php
> +	 * @var   []
```suggestion
	 * @var   array
```

2021-11-13 16:24 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Task/Task.php
> +	protected const EVENTS_MAP = [
add docblock

2021-11-13 16:25 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Task/Task.php
> +		// Hack because Registry dumps private properties otherwise
Don't use word "hack" as many scanners and audit tools will flag this as a hacked file. "Hacked by..." etc.

2021-11-13 16:25 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Task/Task.php
> +		*/
```suggestion
		/**
		 * Dispatch event if task lock is not released (NULL). This only happens if the task execution
		 * was interrupted by a fatal failure.
		 */
```

2021-11-13 16:30 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
> +	 *
```suggestion
```

2021-11-13 16:31 UTC, PhilETaylor commented on administrator/components/com_scheduler/tmpl/select/default.php
> +// $function  = $app->getInput()->get('function');
```suggestion
```

2021-11-13 16:31 UTC, PhilETaylor commented on administrator/components/com_scheduler/tmpl/select/default.php
> + * endif;*/
```suggestion
```

2021-11-13 16:34 UTC, PhilETaylor commented on plugins/system/schedulerunner/schedulerunner.php
> +	 *
```suggestion
```

2021-11-13 16:35 UTC, PhilETaylor commented on plugins/task/checkfiles/checkfiles.php
> + * Task plugin with routines that offer checks on files.<br/>
```suggestion
 * Task plugin with routines that offer checks on files.
```

2021-11-13 19:42 UTC, HLeithner commented
Hmm, I updated from a 4.0 installation and got some errors 

and autoload_psr4.php is not updated on joomla update (unreleated to this pr)
`0 Class "Joomla\Component\Scheduler\Administrator\Extension\SchedulerComponent" not found`

after recreating the autoloader I get this error message on openening the tasks view
`0 count(): Argument #1 ($value) must be of type Countable|array, bool given`

the db fixer tells me:
`Table 'vi3ow_scheduler_tasks' does not exist. (From file 4.1.0-2021-08-08.sql.)`

reason for this is that the table couldn't be created because the index is too long.
type has 1024 characters which is with utf8_mb4 4096 bytes, allowed is 767, I didn't looked at the code yet but don't understand way a unique key have to be 1024 chars long when UUID has only 36 chars.

Creating a key for the webcron didn't worked, at least it didn't created a key when I saved the configuration.

I created a test cron and executed it manually, seems to work but doesn't updated the "last run" information.

2021-11-15 17:47 UTC, ditsuke commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +	 * @param   FormFactoryInterface|null  $formFactory  The form factory [?]
Shouldn't the `|null` be removed then?

2021-11-15 17:58 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
no, I meant `+` it does the same job here, i think.

2021-11-15 17:59 UTC, ditsuke commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +	 * @return boolean True if user is allowed to edit record
I don't understand :confused:

2021-11-15 18:01 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +	 * @return boolean True if user is allowed to edit record
```
Commonly a line after the tag @param consists of the following three parts in order of appearance:

variable type (There must be 3 spaces before variable type.)
variable name (There must be 2 spaces after the longest type.)
variable description (There must be 2 spaces after the longest variable name.)
```

https://developer.joomla.org/coding-standards/docblocks.html

2021-11-15 18:02 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Model/TaskModel.php
> +	 * @param   FormFactoryInterface|null  $formFactory  The form factory [?]
either or :) seems most editors are going for the ? syntax instead of the |null nowadays but I guess both are correct :)

2021-11-15 18:23 UTC, PhilETaylor commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
I cannot believe that. see https://3v4l.org/Z7NsK

2021-11-15 19:18 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
Both sides to the `+` here are arrays, that seems to work fine?

2021-11-15 19:22 UTC, ditsuke commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +	 * @return boolean True if user is allowed to edit record
I understand, but don't we have the required number of spaces + alignment here?

2021-11-15 19:25 UTC, richard67 commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
@ditsuke In the online example which Phil has linked, the `var_dump($arr1 + $arr2);` would work if the output would be `['a','b','c', 'd','e','f']`, but that`s not the case. In fact when looking in PHP documentation I don't see how a `+` can be used to join or merge array together.

2021-11-15 19:28 UTC, richard67 commented on administrator/components/com_scheduler/src/Controller/TaskController.php
> +	 * @return boolean True if user is allowed to edit record
Between `@return` and `boolean` it needs 1 spaces, and between `boolean` and `True if user is allowed to edit record` it needs 2 spaces, too,

2021-11-15 21:02 UTC, ditsuke commented on administrator/components/com_scheduler/src/Task/Task.php
> +		// Hack because Registry dumps private properties otherwise
resolved, now using "workaround"

2021-11-20 10:41 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
@richard67 usage of the `+` union operator for arrays has been documented here
https://www.php.net/manual/en/function.array-merge.php

2021-11-20 10:43 UTC, richard67 commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
@ditsuke I see. It just needs to scroll a bit down on that page to find it. So I've learned something new now, thanks.

2021-11-20 10:44 UTC, richard67 commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
But why doesn't it work on https://3v4l.org/Z7NsK ?

2021-11-20 11:06 UTC, ditsuke commented on administrator/components/com_scheduler/src/Field/WebcronLinkField.php
> +			] + parent::getLayoutPaths();
Sorry, I was assuming this was the behavior for non-numeric indices but I realize now the issue that for conflicting indices the left hand side is overriding the right side here too. We'll need a merge here. I'll push a fix 😅

2021-11-20 11:55 UTC, richard67 commented
@ditsuke After your commit to merge the update SQL scripts, I still see 2 for each database type, "4.1.0-2021-08-04.sql" and "4.1.0-2021-08-08.sql". Please combine these, too, and maybe give them a younger date, i.e.
- Rename "4.1.0-2021-08-08.sql" to "4.1.0-2021-11-20.sql" for each database type with one commit.
- Then copy content of "4.1.0-2021-08-04.sql" into "4.1.0-2021-11-20.sql" and remove the "4.1.0-2021-08-04.sql" for each database type with another commit.

To have separate commits for rename and content change makes GitHub show the history right and not show it as a deleted and another created file.

2021-11-21 14:53 UTC, richard67 commented
More SQL fixes see https://github.com/joomla-projects/soc21_website-cronjob/pull/49 .

2021-11-21 17:59 UTC, richard67 commented
When updating from a clean 4.1-dev installation to a patched update package which contains the changes from this PR plus my corrections on the SQL scripts from https://github.com/joomla-projects/soc21_website-cronjob/pull/49 , it ends with following:

![2021-11-21_1](https://user-images.githubusercontent.com/7413183/142773507-aa7c8617-301b-4cc2-9757-b6a19c4dad44.png)

During the update there are no SQL errors, so I think the SQL is ok for at least MySQL (I haven't tested PostgreSQL yet).

2021-11-21 18:16 UTC, richard67 commented
See https://github.com/joomla-projects/soc21_website-cronjob/pull/50 for updating the list of core extensions in the extensions helper so that on update of the core. the manifest cache is updated for the new core extensions.

2021-11-22 08:25 UTC, ditsuke commented
@richard67 

> When updating from a clean 4.1-dev installation to a patched update package which contains the changes from this PR plus my corrections on the SQL scripts from [joomla-projects/soc21_website-cronjob#49](https://github.com/joomla-projects/soc21_website-cronjob/pull/49) , it ends with following:
> 
> ![2021-11-21_1](https://user-images.githubusercontent.com/7413183/142773507-aa7c8617-301b-4cc2-9757-b6a19c4dad44.png)
> 
> During the update there are no SQL errors, so I think the SQL is ok for at least MySQL (I haven't tested PostgreSQL yet).



> See [joomla-projects/soc21_website-cronjob#50](https://github.com/joomla-projects/soc21_website-cronjob/pull/50) for updating the list of core extensions in the extensions helper so that on update of the core. the manifest cache is updated for the new core extensions.
> 
> It does **_not_** solve the above issue but is required, too.

Thanks for the fixes on the SQL. 

It appears the issue appears because the autoload file (`JOOMLA_ROOT/administrator/cache/autoload_psr4.php`) is not refreshed. Shouldn't it be deleted by default by the update script, or do we need something else so its done?

2021-11-22 08:29 UTC, richard67 commented
> Shouldn't it be deleted by default by the update script, or do we need something else so its done?

@ditsuke I have no idea. Maybe @bembelimen knows, or knows who knows?

2021-11-22 17:05 UTC, bembelimen commented
> > Shouldn't it be deleted by default by the update script, or do we need something else so its done?
> 
> @ditsuke I have no idea. Maybe @bembelimen knows, or knows who knows?

So talking with the maintanier team, this is not an issue of this PR but a general issue in Joomla! (this one was just the unlucky one to discover it). We'll take care of it.

2021-11-22 18:29 UTC, bembelimen commented
So as we have the issue with the update from 4.0, I'll not merge this PR now but for beta 1, so we have enough time to implement a proper fix (independend from this PR).

2021-11-23 10:46 UTC, alikon commented
made a quick test  from CLI

![image](https://user-images.githubusercontent.com/181681/143010737-92b00584-4fc1-4d59-84d5-e677da6943d6.png)

2021-11-23 13:49 UTC, Krshivam25 commented
I have tested this item :white_check_mark: successfully on d77353ded28c4382ab4b4d7ab2452da02fa35231<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35143">issues.joomla.org/tracker/joomla-cms/35143</a>.</sub>

2021-11-23 22:48 UTC, bembelimen commented
> made a quick test from CLI
> 
> ![image](https://user-images.githubusercontent.com/181681/143010737-92b00584-4fc1-4d59-84d5-e677da6943d6.png)

@alikon we tried to reproduce the issue, but so far no success, could you share the options you set for the task?

2021-11-24 07:32 UTC, alikon commented
this is my task a GET one
![image](https://user-images.githubusercontent.com/181681/143194222-165e81c8-6148-4d07-a391-8e51f21ce295.png)
...

![image](https://user-images.githubusercontent.com/181681/143194282-16e534f6-de1c-4b8e-872d-dd2c6d4bc16c.png)

2021-11-24 07:36 UTC, alikon commented
changing the state from CLI  doesn't work
![image](https://user-images.githubusercontent.com/181681/143194852-09ac7c65-2756-4581-bc8b-8957eb2062d4.png)

2021-11-24 07:40 UTC, alikon commented
running the test task from admin 
![image](https://user-images.githubusercontent.com/181681/143195268-37f8aeb1-ef29-4671-80ca-d1e3819a0103.png)

Last run not updated it is expected ?

2021-11-26 11:42 UTC, merged

2021-11-26 11:44 UTC, bembelimen commented
Thank you @ditsuke , @brianteeman , @PhilETaylor , @richard67 , @HLeithner , @Denitz , @alikon  , @dgrammatiko , @nibra , @chmst , @softforge (and many more) who made this possible and happen.

2021-11-26 17:24 UTC, alikon commented
from when a pr it's merged without 2 test
...really surprised..