[4.1] Images in the Smart Search results
joomla/joomla-cms pull request #35612
Opened 2021-09-20 12:20 UTC by sakiss

### Summary of Changes
The PR allows the use of images in the finder's results.

A new setting was added named "Result Image" both in the com_finder's (aka Smart Search) configuration and it's respective "search" menu item.

### Testing Instructions
1. Go to the "Smart Search" component, press the "Clear Index" button and then the "Index".
2. Press the "Options" button to load the configuration and enable the "Result Image" setting.
3. Use the smart search in the site's front-end and check the returned articles that have "Intro Image" set.

### Actual result BEFORE applying this Pull Request
![result_w_images](https://user-images.githubusercontent.com/1838041/133997102-2a4879eb-9a12-474f-b842-18e0fe6402ef.png)

### Expected result AFTER applying this Pull Request
![result_images](https://user-images.githubusercontent.com/1838041/134001105-e524cb89-15cb-48e9-8df5-9c69323085e4.png)

### Sidenotes

Atm only the _com_content_ finder plugin uses the images API function. Support for the rest plugins will be added in a next PR.

There are **3 new settings** both in Smart Search Configuration and in Smart Search results menu item:
![result_images_params](https://user-images.githubusercontent.com/1838041/134000935-97d9877f-ec9c-4fdc-a8bc-f4d08d463d27.png)

1.  Result Image  > Shows or hides the image in the results.
2.  Image Class > Adds a class to the figure html element. The same that happens with the "_Intro Image Class_" in com_content.
3.  Linked Image  > Creates an anchor for the image.  The same that happens with the "_Linked Intro Image_" in com_content.

### Documentation Changes Required
DKN

2021-09-21 19:09 UTC, brianteeman commented on administrator/components/com_finder/config.xml
> +		>
```suggestion
		<field
			name="link_image"
			type="radio"
			label="COM_FINDER_CONFIG_LINKED_IMAGE_LABEL"
			layout="joomla.form.field.radio.switcher"
			default="0"
			showon="show_image:1"
		>
```

2021-09-21 19:11 UTC, brianteeman commented on components/com_finder/tmpl/search/default.xml
> +			/>
```suggestion
			<field
				name="image_class"
				type="text"
				label="COM_FINDER_CONFIG_IMAGE_CLASS_LABEL"
				default=""
				useglobal="true"
				validate="CssIdentifier"
				showon="show_image!:0"
			/>
```

2021-09-21 19:12 UTC, brianteeman commented on components/com_finder/tmpl/search/default.xml
> +			>
```suggestion
			<field
				name="link_image"
				type="list"
				label="COM_FINDER_CONFIG_LINKED_IMAGE_LABEL"
				default=""
				useglobal="true"
				class="form-select-color-state"
				validate="options"
				showon="show_image!:0"
				>
```

2021-09-23 11:44 UTC, Fedik commented
@sakiss please remove all your changes from `administrator/components/com_finder/src/Indexer/Result.php`,
Rest is good to go.

2021-09-23 11:46 UTC, Fedik commented on plugins/finder/content/content.php
> +		if (!empty($images) && $images->image_intro)
`if (!empty($images->image_intro))`

2021-09-23 11:46 UTC, Fedik commented on plugins/finder/content/content.php
> +		$images = json_decode($item->images);
`$images = $item->images ? json_decode($item->images) : false;`

2021-09-23 19:41 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Result.php
> +	 * @since __DEPLOY_VERSION__
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-09-23 19:41 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Result.php
> +	 * @since __DEPLOY_VERSION__
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-09-23 19:42 UTC, PhilETaylor commented on components/com_finder/tmpl/search/default.xml
> +					showon="show_image!:0"
remove one indent

2021-09-23 19:47 UTC, PhilETaylor commented on components/com_finder/tmpl/search/default_result.php
>  $user = Factory::getUser();
```suggestion
$user = Factory::getApplication()->getIdentity();
```

2021-09-30 16:20 UTC, mateoAdi commented
I have tested this item :white_check_mark: successfully on a22bd5190c8be6c005487b38fe0a74d0559d99a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35612">issues.joomla.org/tracker/joomla-cms/35612</a>.</sub>

2021-10-04 17:39 UTC, Fedik requested changes
This still need to be fixed https://github.com/joomla/joomla-cms/pull/35612#issuecomment-925735253

2021-10-07 11:15 UTC, sakiss commented
@Fedik Done. Plz remove the "Change Requested" label. 
Let's hope that this gets 1 more test and finally got merged.

2021-10-07 11:32 UTC, Fedik approved these changes
Looks much better, thanks

2021-10-10 17:08 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on a22bd5190c8be6c005487b38fe0a74d0559d99a3<br /><br />Nice addition to the result page!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35612">issues.joomla.org/tracker/joomla-cms/35612</a>.</sub>

2021-10-10 17:08 UTC, RickR2H commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35612">issues.joomla.org/tracker/joomla-cms/35612</a>.</sub>

2021-10-22 09:35 UTC, sakiss commented
RTC?

2021-10-22 09:46 UTC, RickR2H commented
Hey Sakis, RTC means Ready To Commit. Next it is up to the release lead to decide if it's a good addition to the platform. If so, they will merge the PR. @bembelimen could you take a look at this PR?

2021-10-22 16:50 UTC, sakiss commented
@RickR2H the question goes to the release leader

2021-10-22 20:56 UTC, RickR2H commented
RL is tagged and PR has been noted!

2021-10-24 19:36 UTC, merged

2021-10-24 19:36 UTC, bembelimen commented
Thx

2021-10-25 09:01 UTC, sakiss commented
Thanks!

2022-04-01 14:21 UTC, brianteeman commented
Can someone please reconfirm that this functionality works as I cant get it show any images at all