[4.0] Invalid timings in debug plugin
joomla/joomla-cms pull request #35655
Opened 2021-09-24 08:20 UTC by Denitz

### Summary of Changes

The time and memory displayed in debug bar (right position) incorrectly includes the usage of debug plugin itself: it's always much bigger than the sum of all timings in Profile tab.

We can't measure 100% correctly but at least should get closer: the most recent profile mark should have right border as closer to right as possible.

See that `afterRender` profile mark is not close the the right, hence we have incorrectly logged total time: it includes the time spent in debug plugin itself and we don't see the real state of page generation.

1. Debug plugin refactored to `Joomla\Event\SubscriberInterface`
2. Fixed problem with the time spent for `onAfterRespond` event is not counted.
3. Added `afterRespond` profiler mark.
4. Fixed problem with the time spent in `onAfterDisconnect` event by debug plugin is included in request time.
5. Remove unused `PlgSystemDebug::$totalQueries` variable
6. Change `PlgSystemDebug::sqlShowProfiles` to local variable because it's the only usage.

### Testing Instructions

Apply patch, see more accurate timings in debug. Profile tab marks are now more proportionally to the 100% width.

### Actual result BEFORE applying this Pull Request

See issues in Changes above.

### Expected result AFTER applying this Pull Request

See issues in Changes above.

### Documentation Changes Required
No.

2021-09-24 08:39 UTC, brianteeman commented on plugins/system/debug/debug.php
> + * @license         GNU General Public License version 2 or later; see LICENSE.txt
please revert these changes

2021-09-24 08:40 UTC, brianteeman commented on plugins/system/debug/debug.php
> +	 * @since       3.1
please revert this change

2021-09-24 08:41 UTC, brianteeman commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> + * @license        For the full copyright and license information, please view the LICENSE
please revert this change

2021-09-24 09:57 UTC, PhilETaylor commented on plugins/system/cache/cache.php
> +				Profiler::getInstance('Application')->mark('afterRespond');
```suggestion
				$profilerApp = Profiler::getInstance('Application');
				$profilerApp->mark('afterCache');
				$this->app->triggerEvent('onAfterRespond');

				$profilerApp->mark('afterRespond');
```

2021-09-24 09:59 UTC, PhilETaylor commented on plugins/system/debug/debug.php
> +	 * @since   3.0
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-09-24 10:00 UTC, PhilETaylor commented on plugins/system/debug/src/DataCollector/MemoryCollector.php
> + *             file that was distributed with this source code.
A note should be inserted to say that this file has been forked and modified since released by the upstream project.

2021-09-24 10:00 UTC, PhilETaylor commented on plugins/system/debug/src/DataCollector/MemoryCollector.php
> +	 *
Useless comment 

```suggestion
```

2021-09-24 10:02 UTC, PhilETaylor commented on plugins/system/debug/src/DataCollector/MemoryCollector.php
> +	 * @param boolean     $realUsage
Spaces as per https://developer.joomla.org/coding-standards/docblocks.html

```
variable type (There must be 3 spaces before variable type.)
variable name (There must be 2 spaces after the longest type.)
variable description (There must be 2 spaces after the longest variable name.)
```


```suggestion
	 * @param   Registry  $params Parameters.
	 * @param   float     $peakUsage
	 * @param   boolean   $realUsage
```

2021-09-24 10:03 UTC, Denitz commented on plugins/system/debug/debug.php
> +	 * @since   3.0
Hm... but `PlgSystemDebug::isAuthorisedDisplayDebug()` really exists since 3.0

2021-09-24 10:04 UTC, PhilETaylor commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> +	public function __construct(Registry $params, $requestStartTime = null, $requestEndTime = null)
Are we allowed to change class signatures in a minor version?

2021-09-24 10:05 UTC, PhilETaylor commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> +	 * @since  4.0.0
https://developer.joomla.org/coding-standards/docblocks.html

```
@return (required, followed by a blank line)
```

```suggestion
	 * @return void
	 *
	 * @since  4.0.0
```

2021-09-24 10:06 UTC, Denitz commented on plugins/system/debug/src/DataCollector/MemoryCollector.php
> + *             file that was distributed with this source code.
@PhilETaylor I copied the desc from ProfileCollector, actually it's the only our collector which has this.
All other collectors have 
```
/**
 * @package     Joomla.Plugin
 * @subpackage  System.Debug
 *
 * @copyright   (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
```
So, what should we use for all of our collectors?

2021-09-24 10:06 UTC, PhilETaylor commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> +	 * @since  4.0.0
https://developer.joomla.org/coding-standards/docblocks.html
correct order and blank lines needed.
```
@return (required, followed by a blank line)
@SInCE (required, followed by a blank line if there are additional tags)
@throws (required if method or function arguments throws a specific type of exception)
```
```suggestion
	 * @return void
	 *
	 * @since  4.0.0
	 *
	 * @throws DebugBarException
```

2021-09-24 10:06 UTC, PhilETaylor commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> +	 * @since  4.0.0
apple the ordering and blank lines referenced here https://github.com/joomla/joomla-cms/pull/35655/files#r715486122 throughout

2021-09-24 10:07 UTC, Denitz commented on plugins/system/debug/src/DataCollector/MemoryCollector.php
> +	 * @param boolean     $realUsage
@PhilETaylor Thanks, it's always a pain, I set the PHPStorm code style "From Joomla" and it looks like either outdated or incorrect.

2021-09-24 10:08 UTC, PhilETaylor commented on plugins/system/debug/debug.php
> +	 * @since   3.0
ok cool.

2021-09-24 10:09 UTC, Denitz commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> +	public function __construct(Registry $params, $requestStartTime = null, $requestEndTime = null)
@PhilETaylor This is non-breaking change, and it's just a debug plugin :)

2021-09-24 10:10 UTC, PhilETaylor commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> +	public function __construct(Registry $params, $requestStartTime = null, $requestEndTime = null)
does that even matter? its a change to the constructor of a class, I might be wrong, but I dont think you are allowed to do that in a minor version in SemVer... Ive not had a coffee yet, I might be wrong on that.

2021-09-27 12:42 UTC, bembelimen commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> +	public function __construct(Registry $params, $requestStartTime = null, $requestEndTime = null)
See: https://github.com/joomla/joomla-cms/pull/35476#issuecomment-914301986 so can only happen in 5.0

2021-09-27 13:01 UTC, Denitz commented on plugins/system/debug/src/DataCollector/ProfileCollector.php
> +	public function __construct(Registry $params, $requestStartTime = null, $requestEndTime = null)
@PhilETaylor @bembelimen I've reverted the constructor of ProfileCollector and just added `setRequestEndTime()` method.

2022-02-22 06:14 UTC, Denitz commented
@brianteeman @PhilETaylor Sorry, any news?

2022-02-22 09:50 UTC, Fedik commented on libraries/src/Application/CMSApplication.php
> +		JDEBUG ? $this->profiler->mark('afterRespond') : null;
Does it really work?
From what I see, it will not, because Debug plugin doing "data collection" `onAfterRespond`, so this Profiler point will be lost.

2022-02-22 09:51 UTC, Fedik commented on plugins/system/debug/debug.php
> +		$this->showLogs = (bool) $this->params->get('logs', false);
Please revert it, in the form default is `1`, so should be `true` here.

2022-02-22 09:54 UTC, Fedik requested changes
Please restore original positions of onAjaxDebug, isAuthorisedDisplayDebug methods in the file.
So it no looks like "new code", and will be more easy to review and see what was changed.

2022-02-22 10:03 UTC, Fedik commented on plugins/system/debug/debug.php
> +		];
Please also add
```
ApplicationEvents::AFTER_RESPOND =>[ 'onAfterRespond', Priority::MIN] 
```
We will be able to collect data after redirects, trigerred by `AbstractWebApplication::redirect`.
I wanted to make a PR, but you already started with `SubscriberInterface` :)

2022-02-22 10:13 UTC, Fedik commented on plugins/system/debug/debug.php
> +		];
Well, no, ignore this comment, I will make it separately, later. 
There need to test some more things for it

2022-02-23 07:39 UTC, Denitz commented on libraries/src/Application/CMSApplication.php
> +		JDEBUG ? $this->profiler->mark('afterRespond') : null;
Good catch, I moved `'afterRespond'` mark into the plugin's `onAfterRespond` event which is now executed as last via `PHP_INT_MIN` priority.

2022-02-23 07:39 UTC, Denitz commented on plugins/system/debug/debug.php
> +		$this->showLogs = (bool) $this->params->get('logs', false);
Done.

2022-02-23 07:40 UTC, Denitz commented
@Fedik I restored original positions of onAjaxDebug, isAuthorisedDisplayDebug methods in the file.

2022-02-23 08:44 UTC, Fedik commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
Better keep it in Application, as you did before.  But in correct order:

```php
// Mark afterRespond in the profiler.
JDEBUG ? $this->profiler->mark('afterRespond') : null;

// Trigger the onAfterRespond event.
$this->getDispatcher()->dispatch('onAfterRespond');
```

So other custom plugins can access to this data.

2022-02-23 09:55 UTC, Denitz commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
I disagree, `afterRespond` profiling mark should be set after `onAfterRespond` event is executed, otherwise we don't catch the time of plugins subscribed to `onAfterRespond` event.

Debug plugin listens to `onAfterRespond` event last in the queue, hence it's quite correct to count `afterRespond` mark in its handler.

2022-02-23 10:35 UTC, Fedik commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
We will not get 100% accurate timing for afterRespond anyway.
There may be more onAfterRespond listeners, that will run after debug plugin.

But by placing mark('afterRespond') in our debug plugin we limit other custom debug plugins to do the same, that not right. It should be generic.

2022-02-23 13:00 UTC, Denitz commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
OK, what is the purpose of `afterRespond` mark in this case? It won't be visible in debug profile timings. I guess it's better to remove it completely in this case.
But, I can apply register_shutdown_function and process the debug code info after the `afterRespond` mark was added in app, do you agree with this solution?

2022-02-23 13:14 UTC, Fedik commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
> It won't be visible in debug profile timings.

Why? if you do in this order, it wil be in debug plugin:
```php
// Mark afterRespond in the profiler.
JDEBUG ? $this->profiler->mark('afterRespond') : null;

// Trigger the onAfterRespond event.
$this->getDispatcher()->dispatch('onAfterRespond');
```

> I can apply register_shutdown_function 

I do not think that it need

2022-02-24 05:42 UTC, Denitz commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
A mark before executing `onAfterRespond` event should be `beforeRespond` in this case, but not `afterRespond`.
Imho, as a developer, I am interested in `afterRespond` mark which provide the timing AFTER executing `onAfterRespond` event and delivers the info about possible issues with plugins subscribed on `onAfterRespond` event.

2022-02-24 08:38 UTC, Fedik commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
I understood what you wanted.
Here we talking about App respond, not really about whole respond, it not possible to track 100% anyway.
Moving  `mark('afterRespond')`  to plugin does not help much, so better keep it consistent on App level.

2022-02-24 11:48 UTC, Denitz commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
Let's get rid of this `afterRespond` mark in this case because it's useless. Please confirm.

2022-02-24 12:52 UTC, Fedik commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
yeah, can remove it :)

2022-02-25 14:51 UTC, Denitz commented on plugins/system/debug/debug.php
> +		JDEBUG ? Profiler::getInstance('Application')->mark('afterRespond') : null;
@Fedik Removed.

2022-02-25 16:41 UTC, Fedik approved these changes

2022-06-27 13:07 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2022-10-21 16:25 UTC, laoneo commented on plugins/system/debug/debug.php
> +            && stripos($_SERVER['HTTP_USER_AGENT'] ?? '', 'webkit') !== false
Guess this change should be reverted to stay on the safe side.

2022-10-21 16:25 UTC, laoneo commented on plugins/system/debug/src/DataCollector/MemoryCollector.php
> +class MemoryCollector extends AbstractDataCollector
Can you not extend from DebugBar\DataCollector\MemoryCollector instead of copying the whole file?

2023-03-27 05:58 UTC, Denitz commented on plugins/system/debug/src/DataCollector/MemoryCollector.php
> +class MemoryCollector extends AbstractDataCollector
A separate collector, what's wrong here?

2023-06-09 06:20 UTC, laoneo commented
Can you fix the conflicts here?

2023-06-16 06:30 UTC, Denitz commented
@laoneo Please restart drone, smth is wrong with the tests and I can't find any relationship with the code itself.

2023-08-17 11:04 UTC, Denitz commented
Sorry, still weird issue with databases in drone

2023-09-11 06:56 UTC, merged