Enhance build tools doc
joomla/joomla-cms pull request #35736
Opened 2021-10-03 11:20 UTC by ditsuke

### Summary of Changes
Update `build/README.md` with better grammar.

### Testing Instructions
Read the build doc.

### Documentation Changes Required
None

2021-10-08 00:41 UTC, jwaisner commented on build/README.md
> +For some of these operations, some conventions were established to simplify and speed up the process.
```suggestion
For some of these operations, conventions were established to simplify and speed up the process.
```

2021-10-08 00:42 UTC, jwaisner commented on build/README.md
> +- Transform any modern JS to both ES2017 and transpile it to ES5.
```suggestion
- Transform any modern JS to ES2017 and transpile it to ES5.
```

2021-10-08 01:22 UTC, jwaisner requested changes
Just a few tweaks if you want to accept them.

2021-10-08 04:08 UTC, ditsuke commented
> 
> 
> Just a few tweaks if you want to accept them.

Thanks, applied. :)

2021-10-08 15:58 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 75b7573da8dcc7e174903e6b1639f789b665dc08<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35736">issues.joomla.org/tracker/joomla-cms/35736</a>.</sub>

2021-11-11 22:19 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on 75b7573da8dcc7e174903e6b1639f789b665dc08<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35736">issues.joomla.org/tracker/joomla-cms/35736</a>.</sub>

2021-11-11 22:20 UTC, RickR2H commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35736">issues.joomla.org/tracker/joomla-cms/35736</a>.</sub>

2021-11-12 07:23 UTC, merged

2021-11-12 07:23 UTC, HLeithner commented
Thanks