[4.0] php memory limit
joomla/joomla-cms pull request #35854
Opened 2021-10-19 07:53 UTC by brianteeman

It is possible to set the memory limit in php to -1 which means unlimited memory.

Unfortunately this was not accounted for in the maths to check if a file could be uploaded.

To test you will need to change the value in your php.ini to `memory_limit = -1` and restart the web server.

Then try to upload any file in the media manager and you will see an error message that the file is too large.

Apply this PR and the upload will be successful.

PR for #35853

2021-10-25 11:53 UTC, rjharishabh commented
I have tested this item :white_check_mark: successfully on 43ccd32de4e78fc4fd03dd5d54f89c189f9ee219<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35854">issues.joomla.org/tracker/joomla-cms/35854</a>.</sub>

2021-10-26 08:42 UTC, laoneo commented on administrator/components/com_media/src/Controller/ApiController.php
> +			|| $serverlength > $helper->toBytes(ini_get('memory_limit')) && $helper->toBytes(ini_get('memory_limit')) != -1)
```suggestion
			|| ($serverlength > $helper->toBytes(ini_get('memory_limit')) && $helper->toBytes(ini_get('memory_limit')) != -1))
```

2021-10-26 08:46 UTC, laoneo commented on administrator/components/com_media/src/Controller/ApiController.php
> +			|| $serverlength > $helper->toBytes(ini_get('memory_limit')) && $helper->toBytes(ini_get('memory_limit')) != -1)
Better to enclose the condition, it is easier to read. I'm also not sure if it would end up otherwise in evaluation by the PHP interpreter as that the whole block must have a memory_limit != -1

2021-10-26 09:35 UTC, brianteeman commented on administrator/components/com_media/src/Controller/ApiController.php
> +			|| $serverlength > $helper->toBytes(ini_get('memory_limit')) && $helper->toBytes(ini_get('memory_limit')) != -1)
but none of the others are?

2021-10-26 11:13 UTC, laoneo commented on administrator/components/com_media/src/Controller/ApiController.php
> +			|| $serverlength > $helper->toBytes(ini_get('memory_limit')) && $helper->toBytes(ini_get('memory_limit')) != -1)
This one here is too `($params->get('upload_maxsize', 0) > 0 && $serverlength > ($params->get('upload_maxsize', 0) * 1024 * 1024))`

`$serverlength > $helper->toBytes(ini_get('post_max_size'))` is only one condition

2021-10-26 11:14 UTC, brianteeman commented on administrator/components/com_media/src/Controller/ApiController.php
> +			|| $serverlength > $helper->toBytes(ini_get('memory_limit')) && $helper->toBytes(ini_get('memory_limit')) != -1)
gotya. will change to make you happy ;)

2021-10-26 11:53 UTC, laoneo commented on administrator/components/com_media/src/Controller/ApiController.php
> +			|| $serverlength > $helper->toBytes(ini_get('memory_limit')) && $helper->toBytes(ini_get('memory_limit')) != -1)
I guess it will not throw an exception when `$serverlength > $helper->toBytes(ini_get('upload_max_filesize'))` is true and you set memory_limit to -1.

So you will make a whole community happy :-)

2021-11-01 11:58 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 6f3416235d8e57de68aaafb785bd3e5895b44a97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35854">issues.joomla.org/tracker/joomla-cms/35854</a>.</sub>

2021-11-01 11:58 UTC, richard67 commented
@rjharishabh Could you test again? Thanks in advance.

2021-11-01 12:32 UTC, rjharishabh commented
I have tested this item :white_check_mark: successfully on 6f3416235d8e57de68aaafb785bd3e5895b44a97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35854">issues.joomla.org/tracker/joomla-cms/35854</a>.</sub>

2021-11-01 12:39 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35854">issues.joomla.org/tracker/joomla-cms/35854</a>.</sub>

2021-11-03 08:56 UTC, bembelimen commented on administrator/components/com_installer/src/Model/WarningsModel.php
> +		if ($post_max_size < $minMemory && $memory_limit != -1)
Is this check correct? Does unlimited memory_limit make PHP to ignore post_max_size & upload_max_filesize?

2021-11-03 09:50 UTC, brianteeman commented on administrator/components/com_installer/src/Model/WarningsModel.php
> +		if ($post_max_size < $minMemory && $memory_limit != -1)
it is the same as other checks in the same file - it was just missing here

2021-11-03 12:53 UTC, bembelimen commented on administrator/components/com_installer/src/Model/WarningsModel.php
> +		if ($post_max_size < $minMemory && $memory_limit != -1)
If I see it correct, they are different checks, the other which exist looking for the ```memory_limit```, the two you changed are checking the `` post_max_size``` and ```upload_max_size```

2021-11-03 13:09 UTC, brianteeman commented on administrator/components/com_installer/src/Model/WarningsModel.php
> +		if ($post_max_size < $minMemory && $memory_limit != -1)
All I can say is that I replicated the reported problem and this change resolved the reported problem

2021-11-13 13:39 UTC, richard67 commented on administrator/components/com_installer/src/Model/WarningsModel.php
> +		if ($post_max_size < $minMemory && $memory_limit != -1)
Sure it was the changes in this file here which solved it, i.e. the change in the other file below was not enough?

2021-11-13 21:12 UTC, HLeithner requested changes
Check upload, post and memory limit if set to unlimited

2021-11-13 21:26 UTC, HLeithner commented
> Check upload, post and memory limit if set to unlimited

I tried visual code on github and completely failed... so I write it down here.

Benjamin is right your changes to $post_max_size and $upload_max_filesize is wrong, you have to check this 2 variables to be bigger then 0 (not -1).

also you have to add this check to the ApiController, because it's possible to set the upload size and post size to -1 or 0 (both unlimit)

2021-11-13 21:27 UTC, closed without merging

2021-11-13 21:30 UTC, richard67 commented
I’ve re-opened the issue.