[4.1] Simplify statistic plugin
joomla/joomla-cms pull request #35983
Opened 2021-11-07 02:26 UTC by bembelimen

Based on the [minutes from 19th October 2021](https://volunteers.joomla.org/departments/production/reports/1652-production-dept-meeting-minutes-october-19-2021) I recreated the statistic plugin:
- Removed the "once" button, as this option is not really useful for the statistics.
- Made more clear which data are sent (made the link to open up information more prominent)
- Pointed out, that the data are anonymous

## Before
![grafik](https://user-images.githubusercontent.com/1229869/140630014-3cb95888-1b1a-422f-9a99-16c113426f68.png)

## Now
![grafik](https://user-images.githubusercontent.com/1229869/140630018-38ebca17-887b-4f19-94a8-4622ff4ab846.png)

2021-11-07 16:10 UTC, Quy commented on administrator/language/en-GB/plg_system_stats.ini
>  PLG_SYSTEM_STATS_BTN_SEND_NOW="Once"
```suggestion
PLG_SYSTEM_STATS_BTN_SEND_ALWAYS="Yes, I'll help Joomla!"
```

2021-11-07 18:06 UTC, Kubik-Rubik requested changes
Please also update the JavaScript code (_media/plg_system_stats/js_) of this plugin to reflect the "once" removal.

2021-11-08 11:35 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 669cf528408efc48c780d3fed1c4da35988308f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35983">issues.joomla.org/tracker/joomla-cms/35983</a>.</sub>

2021-11-08 12:09 UTC, bembelimen commented
> 
> 
> Please also update the JavaScript code (_media/plg_system_stats/js_) of this plugin to reflect the "once" removal.

Good find, thx, is fixed.

2021-11-08 12:09 UTC, bembelimen commented on administrator/language/en-GB/plg_system_stats.ini
>  PLG_SYSTEM_STATS_BTN_SEND_NOW="Once"
I think we should not remove existing language strings in a minor version

2021-11-08 12:10 UTC, brianteeman commented
The english changes here are not very good and they are sending the wrong message. I agree about removing the send once but the rest is not correct. Also it is not clear what happens to sites that have previously said "once" when the plugin is updated.

2021-11-08 12:39 UTC, bembelimen commented
> 
> The english changes here are not very good and they are sending the wrong message.

thanks for the feedback, could you elaborate on that? What would you change?

>
> Also it is not clear what happens to sites that have previously said "once" when the plugin is updated.

Nothing, as they sent it already and now the plugin is disabled.

2021-11-08 12:46 UTC, brianteeman commented
>>Also it is not clear what happens to sites that have previously said "once" when the plugin is updated.

>Nothing, as they sent it already and now the plugin is disabled.

then the quality of the stats will not improve

2021-11-08 13:24 UTC, bembelimen commented
> 
> then the quality of the stats will not improve

Not for the old one, but for the new one. It's all about sending regular data. "Once" is a "no" for regular data. I personaly would have prefered a opt-out solution and collecting more (anonymous) data, but this was just not possible. So the solution is to get more people clicking on "yes" by being more detailed.

2021-11-08 15:05 UTC, brianteeman commented
Honestly its a waste of time. This will have minimal impact on improving the statistics and their usefulness. **More people will not be clicking on yes because the majority of people will never see it.** The only way to do that would be to reset the plugin status when this new version is installed and ask EVERYONE the question.

2021-11-13 11:35 UTC, Shubhamverma2796 commented
I have tested this item :white_check_mark: successfully on 40ee732c445a7db9e92b7712d5a2300c6e93005c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35983">issues.joomla.org/tracker/joomla-cms/35983</a>.</sub>

2021-11-13 20:09 UTC, HLeithner commented
> Honestly its a waste of time. This will have minimal impact on improving the statistics and their usefulness. **More people will not be clicking on yes because the majority of people will never see it.** The only way to do that would be to reset the plugin status when this new version is installed and ask EVERYONE the question.

I like the idea to reset the current status of the plugin if it is set to "once".

2021-11-25 11:01 UTC, chmst commented
My2cent:  2 buttons, left no, right yes are a good solution.

Eyes (in ltr countries) go from left to right and stay on the most right button. This is why all consent messages have the "yes" button right. So I think that changing the order of buttons will have an impact. 

Deciding between 2 alternatives is easy, 3 options make the user think.  A normal user cannot know what's the difference between options always and once. What means "once"?

2021-11-25 11:01 UTC, Krshivam25 commented
I have tested this item :white_check_mark: successfully on 40ee732c445a7db9e92b7712d5a2300c6e93005c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35983">issues.joomla.org/tracker/joomla-cms/35983</a>.</sub>

2021-11-25 11:54 UTC, zero-24 commented on administrator/language/en-GB/plg_system_stats.ini
> +PLG_SYSTEM_STATS_BTN_SEND_ALWAYS="Yes, I'll help Joomla!"
```suggestion
PLG_SYSTEM_STATS_BTN_SEND_ALWAYS="Yes, I'll send statistics"
```

2021-11-25 12:00 UTC, HLeithner commented
I'm I the only one that would the yes button expect on the left side? Maybe I'm brain washed by windows but the primary button is always left (on windows) I think mac is diffrent?

2021-11-25 12:02 UTC, brianteeman commented
Its all irrelevant if we dont reset the plugin

2021-11-25 12:18 UTC, zero-24 commented
> I'm I the only one that would the yes button expect on the left side? Maybe I'm brain washed by windows but the primary button is always left (on windows) I think mac is diffrent?

Thats another argumend raised by me on the discussion before so its not just you...

2021-11-25 12:24 UTC, zero-24 commented
> Its all irrelevant if we dont reset the plugin

Do we have the right to reset such thing? The decison to only send them once (while it does not make much sense) is a decision we have to respect right? Now its gone and the most accurate replacement is the new "no" option, IMO we should have disabled the plugin on the "no" and "only once" button click in the first place to be correct so here just reset the thing.

If we want to I would say the only thing we should do would be to ask for a new decision on the "only once" users but keep the "no" decision intact.

2021-11-25 12:27 UTC, zero-24 commented on administrator/language/en-GB/plg_system_stats.ini
> +PLG_SYSTEM_STATS_MSG_WHAT_DATA_WILL_BE_SENT="No identifying data is captured at any point. Select here to review."
You know that atleast in germany the IP is interpreted as identifying data so just tell them that technically we collect the IP but do not use that.

2021-11-25 12:29 UTC, zero-24 commented
And as noted above the "no" button should go and disable the plugin all together there is no point in running that plugin all the time when its not sending anything at all.

2021-11-25 12:39 UTC, HLeithner commented
I think the plugin should use the task scheduler... ok sorry a bit offtopic^^

Resetting "only once" should be ok, because  this options doesn't exists anymore. The other options should be as they are now. On the other side you can argument that "only once" means for us "no" after this... don't care if it's only for new installation it's fine for me too.

2021-11-25 12:46 UTC, brianteeman commented
The IP of the server is not PII just the users internet connection IP

2021-11-25 12:53 UTC, zero-24 commented
> The IP of the server is not PII just the users internet connection IP

Right even when that IP is used I would still communicate to be transparent and not hidde that information and exactly point this out.

2021-11-25 12:56 UTC, bembelimen commented
> On the other side you can argument that "only once" means for us "no" after this...

That's why it is the way it is now. If we reset "only once" (which means once then never), we could reactivate all plugins ... Which means we have to republish it and set the parameter.

I have no feelings about this additional step, if someone delivers the code.

2021-11-25 12:58 UTC, brianteeman commented
Where is it sending the IP - it is not shown in the list of information that is sent

![image](https://user-images.githubusercontent.com/1296369/143445854-9261c2ca-df3c-444a-92bc-4996bc840aae.png)

2021-11-25 12:59 UTC, brianteeman commented
> > On the other side you can argument that "only once" means for us "no" after this...
> 
> That's why it is the way it is now. If we reset "only once" (which means once then never), we could reactivate all plugins ... Which means we have to republish it and set the parameter.
> 
> I have no feelings about this additional step, if someone delivers the code.

If we don't reset then we will not get any improved stats and this PR is pointless. 

I see no issue in doing this. It will not break the site.

2021-11-25 13:04 UTC, zero-24 commented
> Where is it sending the IP - it is not shown in the list of information that is sent

Its in the logs as the site connects to a server owned by Joomla. And yes its not transparent and thats what I'm asking that to be changed. :)

2021-11-25 14:44 UTC, brianteeman commented
The server logs or the stats logs

2021-11-25 15:45 UTC, richard67 commented
@bembelimen Strange, the issue tracker shows 2 successful tests, but @chmst has tested before the last commit which removed unused JS. Shall I set RTC anyway, or is there some discussion ongoing and changes expected .e.g. on language strings?

2021-11-28 10:47 UTC, richard67 commented
@Shubhamverma2796 I can see a positive test from you counted for this pull request, but it seems you have not used the "Test this" button in the issue tracker to submit your test result, you have used the "Alter test" button, so we can see that only in the issue tracker but not on GitHub.

![2021-11-28_pr-35983-test-item-change](https://user-images.githubusercontent.com/7413183/143764629-30733135-fd17-4bb0-8abc-943a9ad3cce6.png)

If you have really tested this PR, then please use the "Test this" button in the issue tracker https://issues.joomla.org/tracker/joomla-cms/35983 to submit your test result.

In the issue tracker and on GitHub you will see than a comment like this:

![2021-11-28_pr-35983-test-item-submitted](https://user-images.githubusercontent.com/7413183/143764712-3e1f1555-d909-4d9c-a998-dd47b313a08f.png)

The "alter test" button is meant to correct a previously submitted test result, e.g. in case if you have forgotten to select the appropriate result before submitting.

Thanks in advance.

2022-01-08 09:30 UTC, ditsuke commented
I have tested this item :white_check_mark: successfully on 236b5ebfc3fbcb5afbadff32f50cc79fd2f7a93c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35983">issues.joomla.org/tracker/joomla-cms/35983</a>.</sub>

2022-01-08 10:34 UTC, softforge commented
I have tested this item :white_check_mark: successfully on 236b5ebfc3fbcb5afbadff32f50cc79fd2f7a93c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35983">issues.joomla.org/tracker/joomla-cms/35983</a>.</sub>

2022-01-08 10:36 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35983">issues.joomla.org/tracker/joomla-cms/35983</a>.</sub>

2022-01-08 12:24 UTC, brianteeman commented
> > > On the other side you can argument that "only once" means for us "no" after this...
> > 
> > 
> > That's why it is the way it is now. If we reset "only once" (which means once then never), we could reactivate all plugins ... Which means we have to republish it and set the parameter.
> > I have no feelings about this additional step, if someone delivers the code.
> 
> If we don't reset then we will not get any improved stats and this PR is pointless.
> 
> I see no issue in doing this. It will not break the site.

2022-01-14 20:54 UTC, bembelimen commented
So I thought a lot over if we should reset the decisions the user made (at least for "once") or not.
At the end I think, that the "once" was a decision of the user to not send regular data, so we should respect it. Also was the idea of the PR only to improve the text.

So I will go with the current version.

2022-01-14 20:54 UTC, merged

2022-01-14 20:56 UTC, brianteeman commented
Your choice of course but the plugin is still producing (or more accurately not producing) any usable statistics

2022-01-15 15:41 UTC, bembelimen commented
> Your choice of course but the plugin is still producing (or more accurately not producing) any usable statistics

I don't disagree, but that was not the intention of this PR. Probably for 4.2 a complete rewrite could happen. @fancyFranci @roland-d

2022-01-15 15:47 UTC, roland-d commented
A rewrite is fine but first we need a description of what it should be doing, otherwise there is no use doing a rewrite. We need to have a list of requirements that the plugin should fulfill. If we do that, are we actually using the data collected...

2022-01-15 19:42 UTC, zero-24 commented
I still disagree with the texts using suggestive language, its a bad sign to me that we think we have to use such suggestive language to gather questionable statistics.. :(

2022-01-20 21:43 UTC, brianteeman commented
Just to point out that while the joomla stats only show 3% on j4.
Stats from akeeba show ten times that number.

2022-01-20 21:57 UTC, zero-24 commented
Jup but that is not fixed by just changing the language and removing the once option. And as mentiond by Nic the serverside (of our statistics) have to be changed too like invalidate old reports etc.

And we have to keep in mind that even when its widly used akeeba is not installed on all sites but maybe more specificly used on well maintained sites.

2022-01-20 22:03 UTC, brianteeman commented
I've not said remove the once option. Just that we should ask again (even if they said once in the past) for a major new release.

I thought the serverside part of the stats had been updated sometime ago to invalidate any reports from more than x ago

Of course akeeba stats will be skewed towards the higher end. But its a good indicator that the stats we have and supposedly use to determine various things are way off

2022-01-20 22:09 UTC, zero-24 commented
I'm not aware of any such change on the serverside but lucky me not everything goes via my desk. :-D

By the commit logs we only had php and joomla version changes latly.

2022-01-20 22:14 UTC, brianteeman commented
I must have been thinking of this https://github.com/joomla/statistics-server/issues/60

2022-01-20 22:20 UTC, zero-24 commented
Possibly :-)

2022-02-05 00:30 UTC, cyrezdev commented
I agree with @brianteeman about reset for all, as the plugin will be changed. If the message is clear about why Joomla needs stats, it will have more effect, and some may say yes when they click no by the past.
In case of update, it would need maybe an additionnal information message (alert) to inform why we ask again.