[4.0] Clear search when a directory is changed in media manager
joomla/joomla-cms pull request #35989
Opened 2021-11-08 08:05 UTC by laoneo

Pull Request for discussion https://github.com/joomla/joomla-cms/pull/35453#issuecomment-916261168.

### Summary of Changes
Clears the search in media manager when folder is changed. Similar to a file browser on desktop computer.

@wilsonge and @bembelimen I leave that up to you guys if it should be added to 4.0 or 4.1.

### Testing Instructions
- Open the media manager
- Search for banners
- Double click on the banners folder
- Search input field should be cleared

### Actual result BEFORE applying this Pull Request
Search remains and banners folder is empty.

### Expected result AFTER applying this Pull Request
Search input field is cleared and all items are shown.

2021-11-11 15:01 UTC, PhilETaylor commented on tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
> +	 * @throws Exception
`@since` should be the last as per https://developer.joomla.org/coding-standards/docblocks.html

2021-11-11 15:01 UTC, PhilETaylor requested changes

2021-11-11 15:01 UTC, PhilETaylor commented on tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
> +	 * @throws Exception
`@since` should be the last as per https://developer.joomla.org/coding-standards/docblocks.html

2021-11-24 12:02 UTC, ceford commented
I have tested this item :white_check_mark: successfully on 7dc55e1d148171a44347578c22b48a61dda40e5d<br /><br />Works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35989">issues.joomla.org/tracker/joomla-cms/35989</a>.</sub>

2021-12-02 17:53 UTC, pritam825 commented
@ceford  can you please test again, because when I applied patch it didn't getting me the output as expected, may be I am wrong, so can you please test once more, Thanks:)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35989">issues.joomla.org/tracker/joomla-cms/35989</a>.</sub>

2021-12-02 20:45 UTC, ceford commented
For me it works exactly as described in the testing instructions. Did you run npm ci ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35989">issues.joomla.org/tracker/joomla-cms/35989</a>.</sub>

2021-12-03 06:31 UTC, laoneo commented
@pritam825 did you run `npm ci` after you have applied the patch?

2021-12-13 15:51 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 7dc55e1d148171a44347578c22b48a61dda40e5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35989">issues.joomla.org/tracker/joomla-cms/35989</a>.</sub>

2021-12-13 15:51 UTC, jwaisner commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35989">issues.joomla.org/tracker/joomla-cms/35989</a>.</sub>

2021-12-15 15:31 UTC, pritam825 commented
@laoneo sorry, I forgot to run npm ci , now it's fine

2021-12-15 15:37 UTC, pritam825 commented
I have tested this item :white_check_mark: successfully on 7dc55e1d148171a44347578c22b48a61dda40e5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35989">issues.joomla.org/tracker/joomla-cms/35989</a>.</sub>

2021-12-23 23:40 UTC, merged

2021-12-23 23:40 UTC, wilsonge commented
Thanks!