[4.1][WIP] Child templates 2/2 [clean]
joomla/joomla-cms pull request #35998
Opened 2021-11-09 15:12 UTC by dgrammatiko

Pull Request for Issue # .

# WIP

### Summary of Changes

### Testing Instructions

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Documentation Changes Required

2021-11-09 17:11 UTC, brianteeman commented on administrator/components/com_templates/src/Service/HTML/Templates.php
> +	 * @since   1.6
copy paste error?

2021-11-09 17:13 UTC, brianteeman requested changes

2021-11-09 17:13 UTC, brianteeman commented on build/media_source/system/images/template_thumb.svg
> +		<polygon fill="#020202" points="99.842,403.98 135.257,439.396 88.128,451.109 41,462.822 52.712,415.691 64.425,368.563 		"/>
```suggestion
		<polygon fill="#020202" points="99.842,403.98 135.257,439.396 88.128,451.109 41,462.822 52.712,415.691 64.425,368.563 "/>

```

2021-11-09 17:13 UTC, brianteeman commented on build/media_source/system/images/template_thumb.svg
> +			146.689,428.859 391.471,184.079 		"/>
```suggestion
			146.689,428.859 391.471,184.079 "/>

```

2021-11-09 17:13 UTC, brianteeman commented on libraries/src/Installer/Installer.php
> +		// Child templates specific fields.
```suggestion
		// Child template specific fields.
```

2021-11-09 17:14 UTC, dgrammatiko commented on administrator/components/com_templates/src/Service/HTML/Templates.php
> +	 * @since   1.6
Yup. Fixed, thanks

2021-11-09 17:16 UTC, dgrammatiko commented on build/media_source/system/images/template_thumb.svg
> +		<polygon fill="#020202" points="99.842,403.98 135.257,439.396 88.128,451.109 41,462.822 52.712,415.691 64.425,368.563 		"/>
This is temporary till we get the actual image.  @bembelimen already has assigned this task to some people/group afaik

2021-11-13 22:55 UTC, dgrammatiko commented
@brianteeman do you know if the `aria-setsize`, `aria-posinset` and `aria-level` are fully supported on all evergreen browsers? Ref: https://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1b.html

2021-11-13 22:58 UTC, brianteeman commented
Sorry I don't know. I will do some research tomorrow. Caveat a lot of the examples on that site are not very good

2021-11-13 23:00 UTC, dgrammatiko commented
Do you have a solid example for tree view? I use some of the links from https://github.com/w3c/aria/issues/1311

2021-11-13 23:09 UTC, brianteeman commented
Not at my pc but the link I shared the other day in the media manager pr looked good

2021-11-13 23:22 UTC, dgrammatiko commented
> Not at my pc but the link I shared the other day in the media manager pr looked good

It's sharing the same code as https://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1b.html
Anyways I will code something and we can improve/iterate...

2021-11-18 14:22 UTC, brianteeman commented on administrator/components/com_templates/tmpl/template/default_modal_child_body.php
> + * @copyright   (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

it is a new file

2021-11-18 14:22 UTC, brianteeman commented on administrator/components/com_templates/tmpl/template/default_modal_child_footer.php
> + * @copyright   (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

it is a new file

2021-11-18 14:24 UTC, brianteeman commented on administrator/components/com_templates/tmpl/template/default_modal_child_body.php
> +					</small>
Do you really mean to display the same text twice?

2021-11-18 14:25 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/template/default_modal_child_body.php
> +					</small>
Nope, the string is wrong

2021-11-18 14:27 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/template/default_modal_child_body.php
> +					</small>
Good catch, https://github.com/joomla/joomla-cms/pull/35998/commits/e5a4b0b34224ec903040b9ce829ba60c1d793f6b should fix that

2021-11-18 14:43 UTC, brianteeman commented on administrator/components/com_templates/tmpl/template/default_media_folders.php
> + * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

it is a new file

2021-11-18 14:44 UTC, brianteeman commented on administrator/components/com_templates/tmpl/template/default_tree_media.php
> + * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```

it is a new file

2021-11-18 14:44 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/template/default_tree_media.php
> + * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
Thanks

2021-11-18 14:45 UTC, brianteeman commented on administrator/components/com_templates/tmpl/template/default_modal_child_body.php
> +					</small>
the new string does not exist

2021-11-18 14:47 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/template/default_modal_child_body.php
> +					</small>
It should, it's used in the copy modal

2021-11-18 14:51 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/template/default_modal_child_body.php
> +					</small>
![Screenshot 2021-11-18 at 15 50 56](https://user-images.githubusercontent.com/3889375/142438380-17a56232-ed40-4958-9100-6441861652c5.png)

2021-11-19 11:23 UTC, brianteeman commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +			$base = $this->getBasePath();
```suggestion
			$base   = $this->getBasePath();
```

2021-11-19 11:24 UTC, brianteeman commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +		}
```suggestion
		if (!isset($template->xmldata)) 
		{
			$template->xmldata = TemplatesHelper::parseXMLTemplateFile($template->client_id === 0 ? JPATH_ROOT : JPATH_ROOT . '/administrator', $template->name);
		}
```

2021-11-19 11:24 UTC, brianteeman commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +		}
```suggestion
		if (!is_writable($path)) 
		{
			$app->enqueueMessage(Text::_('COM_TEMPLATES_DIRECTORY_NOT_WRITABLE'), 'error');
		}
```

2021-11-19 11:26 UTC, dgrammatiko commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +		}
Thanks

2021-11-19 11:27 UTC, brianteeman commented on administrator/components/com_templates/src/View/Template/HtmlView.php
> +		$app              = Factory::getApplication();
```suggestion
		$app               = Factory::getApplication();
```

2021-11-19 16:25 UTC, Quy commented on administrator/components/com_templates/src/Service/HTML/Templates.php
> +		$client = ApplicationHelper::getClientInfo($template->client_id);
```suggestion
		$client = ApplicationHelper::getClientInfo($template->client_id);
```

2021-11-21 10:44 UTC, bembelimen commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		if (strlen($newName) > 0)
Could we convert this to an early return?
```
    if (!strlen($newName))
    {
        $this->setMessage(Text::sprintf('COM_TEMPLATES_ERROR_INVALID_TEMPLATE_NAME'), 'error');

        return false;
    }
```

2021-11-21 10:44 UTC, bembelimen commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +				// User is not authorised to delete
```suggestion
				// User is not authorised to create
```

2021-11-21 10:49 UTC, dgrammatiko commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		if (strlen($newName) > 0)
Sure, fwiw this method should be almost identical to the `copy()` one. Will fix this later on today

2021-11-22 20:46 UTC, RickR2H commented
@dgrammatiko I checked out the PR but I got a some warnings in the template view.
![warnings-2](https://user-images.githubusercontent.com/5610413/142932854-3cb8fa42-a34b-474f-ba49-7a5a02c4eb96.jpg)

2021-11-22 20:55 UTC, dgrammatiko commented
>  @dgrammatiko I checked out the PR but I got a some warnings in the template view.

@RickR2H good catch, should be fine now

2021-11-22 21:01 UTC, RickR2H commented
The default thumb isn't working ;)
![Image 3](https://user-images.githubusercontent.com/5610413/142934702-8662bfc0-c98f-425b-b3a3-17c67e516031.jpg)

2021-11-22 21:05 UTC, RickR2H commented
Some warnings still appear:

Warning: Undefined variable $key in C:\wamp64\www\testing\administrator\components\com_templates\tmpl\template\default.php on line 91 Call Stack #TimeMemoryFunctionLocation 10.0002366680{main}( )...\index.php:0 20.0003367448require_once( 'C:\wamp64\www\testing\administrator\includes\app.php )...\index.php:32 30.01661276768Joomla\CMS\Application\CMSApplication->execute( )...\app.php:63 40.01711359128Joomla\CMS\Application\AdministratorApplication->doExecute( )...\CMSApplication.php:278 50.07222317544Joomla\CMS\Application\AdministratorApplication->dispatch( $component = ??? )...\AdministratorApplication.php:186 60.07732448944Joomla\CMS\Component\ComponentHelper::renderComponent( $option = 'com_templates', $params = ??? )...\AdministratorApplication.php:143 70.08122511504Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch( )...\ComponentHelper.php:389 80.08182522928Joomla\CMS\MVC\Controller\BaseController->execute( $task = 'display' )...\ComponentDispatcher.php:146 90.08182522928Joomla\Component\Templates\Administrator\Controller\DisplayController->display( $cachable = ???, $urlparams = ??? )...\BaseController.php:730 100.08192522928Joomla\CMS\MVC\Controller\BaseController->display( $cachable = ???, $urlparams = ??? )...\DisplayController.php:67 110.08372620904Joomla\Component\Templates\Administrator\View\Template\HtmlView->display( $tpl = ??? )...\BaseController.php:692 120.12822878352Joomla\CMS\MVC\View\HtmlView->display( $tpl = NULL )...\HtmlView.php:230 130.12842880096Joomla\CMS\MVC\View\HtmlView->loadTemplate( $tpl = NULL )...\HtmlView.php:221 140.12962901864include( 'C:\wamp64\www\testing\administrator\components\com_templates\tmpl\template\default.php )...\HtmlView.php:432 " href=""> 

Warning: Undefined property: Joomla\CMS\Object\CMSObject::$inheritable in C:\wamp64\www\testing\administrator\components\com_templates\tmpl\template\default.php on line 379

2021-11-22 21:18 UTC, RickR2H commented
full path is added to the folder structure in the explorer on the left.
![Image-1](https://user-images.githubusercontent.com/5610413/142936583-f0565f35-fbdc-4761-bb86-6c6dd0a6e105.jpg)

2021-11-22 21:22 UTC, dgrammatiko commented
> full path is added to the folder structure in the explorer on the left.

That's a winDOS thing. I have to check where that FS fails

2021-11-22 21:29 UTC, RickR2H commented
> > full path is added to the folder structure in the explorer on the left.
> 
> That's a winDOS thing. I have to check where that FS fails

That explains why the links are all failing. Clicking the files in the tree results in a "File not found" error and a lot of warnings. Let me know if you need more info. We can use Glip if you want, so we don't spam the Git stream to much.

Keep me posted!

2021-11-22 21:31 UTC, dgrammatiko commented
Did https://github.com/joomla/joomla-cms/pull/35998/commits/411a9f57f97282cffb161be0fa0b52b9e852fc8c fixed the full path? Also you should have proper thumbs now

2021-11-22 21:38 UTC, RickR2H commented
Folders and files work. One thing I noticed is that the folders now haven an additional "/"

![image](https://user-images.githubusercontent.com/5610413/142938862-1d74c055-7b98-414c-80b6-8e2df2f0eadf.png)

2021-11-22 21:44 UTC, RickR2H commented
Installing the Cassy template worked. Creating the child worked too. On opening the child I get notices:

![image](https://user-images.githubusercontent.com/5610413/142939585-ce3b6b5a-5878-46b6-9cfa-c75cb52b9528.png)

2021-11-22 21:48 UTC, RickR2H commented
Is it correct that a child template folder only has a templateDetails.xml to start with?

2021-11-22 22:04 UTC, dgrammatiko commented
> On opening the child I get notices:

Should be ok now. You will need to manually uninstall the child and recreate it

2021-11-23 20:57 UTC, PhilETaylor commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +	 * @return  boolean     true on success, false otherwise
```suggestion
	 * @return  boolean   true on success, false otherwise
```

2021-11-23 20:58 UTC, PhilETaylor commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		if (!$this->allowEdit())
Access check should come right after checkToken - should be the first things done

2021-11-23 20:59 UTC, PhilETaylor commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		}
All of the `if` statements need opening brace on their own line

```suggestion
		if (!$fromName) 
		{
			$this->setMessage(Text::_('COM_TEMPLATES_ERROR_INVALID_FROM_NAME'), 'error');

			return false;
		}
```

2021-11-23 21:01 UTC, PhilETaylor commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +			// Include the extension plugins for the save events.
I think this is a mistake indentation?

2021-11-23 21:01 UTC, PhilETaylor commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +		$result = array();
Its 2021.
```suggestion
		$result = [];
```

2021-11-23 21:02 UTC, PhilETaylor commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +			return [];
reuse `$result` which is a blank array already.

```suggestion
			return $result;
```

2021-11-23 21:02 UTC, PhilETaylor commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +		return $result;
reuse `$result` which is a blank array already.

```suggestion
		if (is_dir($path)) {
			$result = $this->getDirectoryTree($path);
		}

		return $result;
```

2021-11-23 21:03 UTC, PhilETaylor commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +	 * @since	__DEPLOY_VERSION__
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2021-11-23 21:04 UTC, PhilETaylor commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +					file_put_contents(JPATH_ROOT . '/media/templates/' . ($template->client_id === 0 ? 'site' : 'administrator') . '/' . $template->element . '_' . $newName . '/index.json', '{}');
You should never be using `file_put_contents` but using the `File::write` API as that clears opcache IIRC. Nothing should directly write to files except through Joomla's File/Folder API.

2021-11-23 21:05 UTC, PhilETaylor commented on administrator/components/com_templates/src/View/Template/HtmlView.php
> +	 * @since   3.2
```suggestion
	 * @since   __DEPLOY_VERSION__
```

2021-11-23 21:05 UTC, PhilETaylor commented on administrator/components/com_templates/tmpl/template/default.php
> +
revert

```suggestion
```

2021-11-23 21:06 UTC, PhilETaylor commented on administrator/components/com_templates/tmpl/template/default.php
> +if ($this->type == 'image') {
revert all IF statements in this file, the opening brace should be on a line by itself.

2021-11-23 21:07 UTC, PhilETaylor commented on administrator/components/com_templates/tmpl/template/default_media_folders.php
> +
```suggestion
```

2021-11-23 21:07 UTC, PhilETaylor commented on administrator/components/com_templates/tmpl/template/default_modal_file_body.php
> +
```suggestion
```

2021-11-23 21:07 UTC, PhilETaylor commented on administrator/components/com_templates/tmpl/template/default_modal_folder_body.php
> +
```suggestion
```

2021-11-23 21:33 UTC, dgrammatiko commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +					file_put_contents(JPATH_ROOT . '/media/templates/' . ($template->client_id === 0 ? 'site' : 'administrator') . '/' . $template->element . '_' . $newName . '/index.json', '{}');
I was trying to find what I did in the other pr which wasn’t such a hack but I also wanted Rick to be able to test the rest. I will remove this part as it’s a cheap hack and do it the right way…

2021-11-23 21:35 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/template/default.php
> +if ($this->type == 'image') {
Thanks, somehow my vscode doesn’t like the Joomla’s cs. I will fix them asap

2021-11-23 22:25 UTC, dgrammatiko commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		if (!$this->allowEdit())
done

2021-11-23 22:26 UTC, dgrammatiko commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +			// Include the extension plugins for the save events.
yes, fixed

2021-11-23 22:26 UTC, dgrammatiko commented on administrator/components/com_templates/src/Model/TemplateModel.php
> +					file_put_contents(JPATH_ROOT . '/media/templates/' . ($template->client_id === 0 ? 'site' : 'administrator') . '/' . $template->element . '_' . $newName . '/index.json', '{}');
Fixed without hacks

2021-11-23 22:26 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/template/default.php
> +if ($this->type == 'image') {
done

2021-11-25 19:06 UTC, coolcat-creations commented
![grafik](https://user-images.githubusercontent.com/828371/143490850-f13b636b-266b-4cbd-a2ec-011a6432725f.png)

Thank you @dgrammatiko  for this nice feature!!! 

I started to test and my main concern is, that the folder structure change is quite confusing and not a nice change for a user.

I understood that this way it's more secure and I am gonna live with tha ;-). 

But the folder structure display is very confusing. It does not display the "reality"
So to make it clear where the files are flying around, it would be good to clarify to the user in the folder structure images what happens. 

Maybe something like that:

![grafik](https://user-images.githubusercontent.com/828371/143490952-3ded374a-0943-4697-9614-55669c7bb373.png)

2021-11-25 19:10 UTC, coolcat-creations commented
At the overrides tab, shouldn't be there also the files from the parent template to click on?

![grafik](https://user-images.githubusercontent.com/828371/143491555-2ad316f5-1a10-4e47-a77b-32e95a9388ff.png)

2021-11-25 19:11 UTC, coolcat-creations commented
I made an override of index.php, and afterwards I made a change in the main template index.php but the changes have not been recognized.
![grafik](https://user-images.githubusercontent.com/828371/143491692-2b3f1a5e-6341-4d6a-ad48-e7feecb13b9b.png)

2021-11-25 19:17 UTC, coolcat-creations commented
I created a .js file in the media js folder, clicked on delete, i got a success message but the file is still there:

![grafik](https://user-images.githubusercontent.com/828371/143492131-e30f948b-9649-4057-bb24-4b2c53593ef1.png)

2021-11-25 19:31 UTC, coolcat-creations commented
Template Overview:
The **Override Files** information is wrong here too (because the index.php is behind the parent version) and it would be great if the childtemplates would be little bit intended so that its better recognizeable that they are childs.
At the create child process it would be great if it takes the username in the author column and the current date. 
Additionally,  if possible, the version could be increased by every change - but I see that there are issues finding the right versioning pattern.

![grafik](https://user-images.githubusercontent.com/828371/143492897-9f827a48-c282-4e2b-b4de-f8752fb93885.png)

2021-11-25 19:36 UTC, chmst commented
@coolcat-creations Agree with indenting child templates. But I think layout improvements can be added also after merge. 

About the update notification: As much as I know, this function observes only the overrides in html.

2021-11-25 19:37 UTC, dgrammatiko commented
> But the folder structure display is very confusing. It does not display the "reality"

The reason I didn't wrote some extensive testing instructions on these PRs was to get such valuable responses. If I had verbally explained the UI you might have thought "ah, that makes sense" but that would be cheating. Thanks! Will add the paths (easy one)

> I made an override of index.php, and afterwards I made a change in the main template index.php but the changes have not been recognized.

That's normal, the update files work only on layout overrides. The logic hasn't changed but the question is should it also include the parent template files? (btw I don't know if that is even possible, templates could have any filename as their entry point: index, component, error, 404, dimitris...) @bembelimen any input here?

> I created a .js file in the media js folder, clicked on delete, i got a success message but the file is still there:

Ok, that's a bug

> At the overrides tab, shouldn't be there also the files from the parent template to click on?

Good question. Fwiw I'm still in favour of https://user-images.githubusercontent.com/3889375/132101328-be1643c8-e9af-4b75-8645-a9162d554214.mp4 and the https://github.com/joomla/joomla-cms/pull/32896 in general but that won't happen in 4.x

> At the create child process it would be great if it takes the username in the author column and the current date.

Easily doable

> if the childtemplates would be little bit intended so that its better recognizeable that they are childs.

I'm not sure how this would look like. The infos are in a table cell

Please keep reporting anything that you feel it's not good, so I could try to fix it. 👍

2021-11-25 19:53 UTC, chmst commented
> I'm not sure how this would look like. The infos are in a table cell

Maybe a fa-angle-right before can do it  (in ltr languages).

2021-11-25 19:58 UTC, dgrammatiko commented
> Maybe a fa-angle-right before can do it (in ltr languages).

What about rtl? Will `fa-angle-left` be ok?

2021-11-25 20:05 UTC, chmst commented
@dgrammatiko  I think so. I will need a test with ltr language. No clue atm how the table looks like in rtl

2021-11-25 20:22 UTC, coolcat-creations commented
Wow, thank you @dgrammatiko for the fast response and fixes!

For:
> > I made an override of index.php, and afterwards I made a change in the main template index.php but the changes have not been recognized.
> 
> That's normal, the update files work only on layout overrides. The logic hasn't changed but the question is should it also include the parent template files? (btw I don't know if that is even possible, templates could have any filename as their entry point: index, component, error, 404, dimitris...) @bembelimen any input here?

For me a childtemplate is basically an override if not it should be clarified to the user. Comparing between the parent template and the childtemplate is very very important I think... 

> Please keep reporting anything that you feel it's not good, so I could try to fix it. 👍

Thank you! I will test tomorrow again :-)

2021-11-26 10:10 UTC, coolcat-creations commented
@bembelimen any feedback about the override-check issue? I think it's one very important thing to have here - its basically the first questions someone has when doing changes on templates "How to recognize changes that have been done to the main template by updates"

2021-11-26 11:08 UTC, bembelimen commented
> @bembelimen any feedback about the override-check issue? I think it's one very important thing to have here - its basically the first questions someone has when doing changes on templates "How to recognize changes that have been done to the main template by updates"

Yes, but not in this PR please. Otherwise we kill ourself (mostly @dgrammatiko ) and never get it done in a first version.
It would be a very nice feature, but is not a "must have or we'll all die" thing.

2021-11-26 11:11 UTC, bembelimen commented
> That's normal, the update files work only on layout overrides. The logic hasn't changed but the question is should it also include the parent template files? (btw I don't know if that is even possible, templates could have any filename as their entry point: index, component, error, 404, dimitris...) @bembelimen any input here?

Yes, it should be possible, but also not in this PR. I think that needs some more thoughts, like see the parent files in a different color and when you edit them in the child, the changes will be copied to the child.

I also see a compare function in the future....but not now.

2021-11-26 11:17 UTC, chmst commented
@dgrammatiko  a agle-left is ok

![image](https://user-images.githubusercontent.com/1035262/143572956-c25227c0-bc6e-406c-a418-ebd9bce5ce1a.png)

2021-11-26 11:22 UTC, dgrammatiko commented
@chmst I added a badge so the view is more like
![Screenshot 2021-11-26 at 12 19 51](https://user-images.githubusercontent.com/3889375/143573356-aed98f90-9560-43f9-8512-8b2335bb45d6.png)
Should I also add the angle icon to signify the child template?

2021-11-26 11:24 UTC, chmst commented
> Should I also add the angle icon to signify the child template?

Not for me

2021-11-26 11:56 UTC, coolcat-creations commented
the badge is nice! Like it :-)

2021-11-27 02:34 UTC, Quy commented on administrator/components/com_templates/tmpl/template/default_modal_file_body.php
> +							<a class="folder-url" data-id="<?php echo base64_encode($key); ?>" href="" data-base="template">
`PHP Notice:  Undefined variable: key`

2021-11-27 02:40 UTC, Quy commented
![35998-templates](https://user-images.githubusercontent.com/368084/143665607-7fc8ba57-e2ba-4f00-9e5d-9793fddd7db6.jpg)

Please match the button icon to the quick icon.

![35998](https://user-images.githubusercontent.com/368084/143665591-c7762c64-0861-40d7-ae28-bad88b0b6cad.jpg)

2021-11-27 06:50 UTC, brianteeman commented
@quy the icon is unrelated to this pr. It was _wrong_ before

2021-11-27 09:04 UTC, dgrammatiko commented on administrator/components/com_templates/tmpl/template/default_modal_file_body.php
> +							<a class="folder-url" data-id="<?php echo base64_encode($key); ?>" href="" data-base="template">
Fixed with 0f35de4

2021-11-27 10:53 UTC, richard67 commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		$file . '&isMedia=' . $isMedia;
Where is the `$isMedia` defined and set?

2021-11-27 10:54 UTC, richard67 commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		$file . '&isMedia=' . $isMedia;
Where is the `$isMedia` defined and set?

2021-11-27 10:59 UTC, dgrammatiko commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		$file . '&isMedia=' . $isMedia;
Do a quick search for `isMedia` in the `administrator/components/com_templates/tmpl/template`. There are many forms to point them here. Also in a couple cases (modals iirc) this is set using JS

2021-11-27 11:46 UTC, dgrammatiko commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		$file . '&isMedia=' . $isMedia;
Good catch

2021-11-27 11:47 UTC, dgrammatiko commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		$file . '&isMedia=' . $isMedia;
Obviously, I misunderstood the comments...
Good catch

2021-11-27 12:07 UTC, richard67 commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		$file . '&isMedia=' . $this->input->getInt('isMedia', 0);
```suggestion
			$file . '&isMedia=' . $this->input->getInt('isMedia', 0);
```

2021-11-27 12:07 UTC, richard67 commented on administrator/components/com_templates/src/Controller/TemplateController.php
> +		$file . '&isMedia=' . $this->input->getInt('isMedia', 0);
```suggestion
			$file . '&isMedia=' . $this->input->getInt('isMedia', 0);
```

2021-11-27 13:35 UTC, chmst commented
Updated a fresh 4.1 with the update file and installed cassy. 
When editing a file, the file name should be visible. Here I have the number "226" for all files: 
![image](https://user-images.githubusercontent.com/1035262/143683610-c3ae538e-de00-4c8b-bae9-c74865adcb04.png)

2021-11-27 13:53 UTC, dgrammatiko commented
> Here I have the number "226" for all files

Fixed with https://github.com/joomla/joomla-cms/pull/35998/commits/b962afbb44aebf032bb59a97f596966b128f0e9a

2021-11-27 14:26 UTC, dgrammatiko commented
@chmst could you try https://github.com/joomla/joomla-cms/pull/35998/commits/bfe1eb6b4b2cce7682314a47d9e573ddb25c3447 It should use `/` for all the directory seperators. Unfortunatelly this affects windows users and I can't test it here

2021-11-27 14:34 UTC, chmst commented
![image](https://user-images.githubusercontent.com/1035262/143685719-535f3d03-c9dc-4d71-a6a7-67eee487164b.png)

Ok for the slashes. 

It remains the "226" instead filename.

2021-11-27 14:40 UTC, brianteeman commented
> Ok for the slashes.

There is an extra slash in the editing file part

2021-11-27 15:10 UTC, chmst commented
I need new glasses

2021-11-27 15:28 UTC, dgrammatiko commented
@chmst did https://github.com/joomla/joomla-cms/pull/35998/commits/4e76c7b4d2ab161f8efb9cf6f6544c13f32b2e02 fixed the double `//`?

2021-11-27 15:38 UTC, chmst commented
Actual result. 
![image](https://user-images.githubusercontent.com/1035262/143687682-0aa33e1d-1221-47ca-b797-64825f21763f.png)

2021-11-27 15:39 UTC, dgrammatiko commented
@chmst is there anything left here that's not fixed?

2021-11-27 15:46 UTC, brianteeman commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_CHILD_SUCCESS="Child template succesfully created."
kill the successfully - it is redundant (and spelt wrong)

```suggestion
COM_TEMPLATES_CHILD_SUCCESS="Child template created."
```

2021-11-27 15:47 UTC, brianteeman commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_TEMPLATE_IS_CHILD_OF="Child of <b class="text-capitalize text-light">%s</b>"
b ?

2021-11-27 15:48 UTC, dgrammatiko commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_TEMPLATE_IS_CHILD_OF="Child of <b class="text-capitalize text-light">%s</b>"
bold?

2021-11-27 15:50 UTC, chmst commented
I found double slashes also here:
![image](https://user-images.githubusercontent.com/1035262/143688067-16100b2a-7d8f-44d6-a10f-c4d62e761859.png)

2021-11-27 15:52 UTC, brianteeman commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_TEMPLATE_IS_CHILD_OF="Child of <b class="text-capitalize text-light">%s</b>"
Not any more -its now called the "bring attention to" element. You probably should use strong as we do everywhere else.

2021-11-27 15:55 UTC, dgrammatiko commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_TEMPLATE_IS_CHILD_OF="Child of <b class="text-capitalize text-light">%s</b>"
Ok done

2021-11-27 15:55 UTC, dgrammatiko commented
>  found double slashes also here:

Should be fixed with https://github.com/joomla/joomla-cms/pull/35998/commits/2359e7f1cf53d9ccc6db6aa3166d8d91293d31d3

2021-11-27 15:57 UTC, chmst commented
Same in rename file modal ;)

2021-11-27 16:00 UTC, richard67 commented
@dgrammatiko Do the testing instructions already include the changes from merging in #36011 ? Or is there something missing?

2021-11-27 16:02 UTC, dgrammatiko commented
> Or is there something missing?

No, the instructions need update. I'm on it

2021-11-27 16:07 UTC, chmst commented
Slashes in Foldernames seem to be ok now.

2021-11-27 16:54 UTC, Quy commented on administrator/components/com_templates/tmpl/template/default_tree_media.php
> +				<a class="file" href='<?php echo Route::_('index.php?option=com_templates&view=template&id=' . $this->id . '&file=' . $value->id . '&isMedia=1'); ?>'>
```suggestion
				<a class="file" href="<?php echo Route::_('index.php?option=com_templates&view=template&id=' . $this->id . '&file=' . $value->id . '&isMedia=1'); ?>">
```

2021-11-27 16:58 UTC, Quy commented on plugins/editors/tinymce/tinymce.php
> +		}
```suggestion
			if (JDEBUG && is_file($nonMinifiedPath))
			{
				return Uri::root(true) . str_replace(JPATH_ROOT, '', $nonMinifiedPath);
			}

			if (is_file($minifiedPath))
			{
				return Uri::root(true) . str_replace(JPATH_ROOT, '', $minifiedPath);
			}

			return '';
		}

		$minifiedPath = pathinfo($path, PATHINFO_DIRNAME) . '/' . pathinfo($path, PATHINFO_FILENAME) . '.min.' . pathinfo($path, PATHINFO_EXTENSION);

		if (JDEBUG && is_file($path))
		{
			return Uri::root(true) . str_replace(JPATH_ROOT, '', $path);
		}

		if (is_file($minifiedPath))
		{
			return Uri::root(true) . str_replace(JPATH_ROOT, '', $minifiedPath);
		}

		return '';
```

2021-11-28 04:47 UTC, Quy commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_TEMPLATE_CHILD_NAME_LABEL="Name of the child template"
```suggestion
COM_TEMPLATES_TEMPLATE_CHILD_NAME_LABEL="Child Template Name"
```

2021-11-28 05:42 UTC, Quy commented on administrator/components/com_templates/src/View/Styles/HtmlView.php
>  		if ((int) $this->get('State')->get('client_id') === 1)
```suggestion
		if ($clientId === 1)
```

2021-11-28 05:43 UTC, Quy commented on plugins/editors/tinymce/src/Field/TemplateslistField.php
> +    $return = parent::setup($element, $value, $group);
Please use tab.

2021-11-28 05:44 UTC, Quy commented on plugins/editors/tinymce/tinymce.php
> +		$template  = $this->getActiveSiteTemplate();
```suggestion
		$fallback = Uri::root(true) . '/media/system/css/editor' . (JDEBUG ? '' : '.min') . '.css';
		$template = $this->getActiveSiteTemplate();
```

2021-11-28 05:44 UTC, Quy commented on administrator/language/en-GB/com_templates.ini
>  COM_TEMPLATES_MANAGER_STYLES_ADMIN="Templates: Styles (Administrator)"
```suggestion
COM_TEMPLATES_MANAGER_STYLES_ADMIN="Templates: Styles (Administrator)"
COM_TEMPLATES_MANAGER_STYLES_BUTTON="Styles"
```

2021-11-28 20:36 UTC, richard67 commented
@dgrammatiko I have created a child template of the Cassy which I had installed before on a 4.1-dev with this PR applied. After that, each time when I edit and save parameters of the template style of that child, I get 3 PHP notices in my PHP error log:

```
Notice:  Trying to get property 'parent' of non-object in /joomla-cms-4.1-dev/administrator/components/com_templates/src/Model/StyleModel.php on line 422, referer: https://www.joomla-41-dev.vmubu01.vmnet2.local/administrator/index.php?option=com_templates&view=style&layout=edit&id=14
PHP Notice:  Trying to get property 'parent' of non-object in /joomla-cms-4.1-dev/administrator/components/com_templates/src/Model/StyleModel.php on line 423, referer: https://www.joomla-41-dev.vmubu01.vmnet2.local/administrator/index.php?option=com_templates&view=style&layout=edit&id=14
PHP Notice:  Trying to get property 'parent' of non-object in/joomla-cms-4.1-dev/administrator/components/com_templates/src/Model/StyleModel.php on line 423, referer: https://www.joomla-41-dev.vmubu01.vmnet2.local/administrator/index.php?option=com_templates&view=style&layout=edit&id=14
```

Could you check that?

Besides this, things seem to work ok so far.

2021-11-28 20:40 UTC, richard67 commented
P.S.: The PHP notices reported above happen only when saving the parameters of a child template's template style (Cassy in this case). They don't happen when editing the parameters of a normal (or copy of a normal) template's template style.

2021-11-28 20:47 UTC, dgrammatiko commented
@richard67 what's the data in the ``#__template_styles`? Are the parent columns filled for the child?

2021-11-28 20:52 UTC, richard67 commented
![2021-11-28_pr-35998](https://user-images.githubusercontent.com/7413183/143785471-3e2a8821-5f2e-4cc0-bf2d-b2b4fb6fa517.png)

@dgrammatiko Looks ok to me. But can it be that more than one template style for a child template is not supported?

When I make the template style of the child template be the default, I get no CSS from the parent loaded.

![2021-11-28_pr-35998_2](https://user-images.githubusercontent.com/7413183/143785555-93e56d01-c583-4371-bfce-202dc470ff38.png)

Backend template styles:

![2021-11-28_pr-35998_3](https://user-images.githubusercontent.com/7413183/143785568-d0094419-366a-4b5a-8d16-652819bc14b6.png)

2021-11-28 21:02 UTC, dgrammatiko commented
The names for your child templates are off, should be `cassy_child*` instead of `cassy_cassy*` Althought this shouldn't be the problem.

> But can it be that more than one template style for a child template is not supported?

No, styles are just the JSON blob from the db so there shouldn't be a limit on the copies...

> When I make the template style of the child template be the default, I get no CSS from the parent loaded.

Does the folders `media/templates/site/cassy/...` exist? This is weird...

2021-11-28 21:08 UTC, richard67 commented
> Does the folders `media/templates/site/cassy/...` exist? This is weird...

@dgrammatiko Yes, it exists. I've created another child with a more suitable name but that did not help.

Another thing I have noticed is that I can created new child templates, but I cannot delete them. Is that by design or will the delete come later with another PR?

2021-11-28 21:13 UTC, richard67 commented
@dgrammatiko It seems it loads the template css files from the media/templates/site/cassy/css folder, but stuff from sub-folders "global", "system" and "vendor" is not included.

2021-11-28 21:14 UTC, richard67 commented
> @dgrammatiko It seems it loads the template css files from the media/templates/site/cassy/css folder, but stuff from sub-folders "global", "system" and "vendor" is not included.

P.S. Could that be an issue of the Cassy template?

2021-11-28 21:15 UTC, dgrammatiko commented
> Another thing I have noticed is that I can created new child templates, but I cannot delete them. Is that by design or will the delete come later with another PR?

Actually, you can already, got to System->Extentions, select templates in the filters and then delete any child template (probably not the most intuitive workflow)...

By the way, can you remove all the preexisted templates and try again your tests, something seems awfully wrong but I can't pinpoint what it is...

2021-11-28 21:27 UTC, richard67 commented
@dgrammatiko I've tried again from scratch with a new installation of this branch. This time only one language, no template style copies, nothing special. I only installed the Cassy template and made it's template style the default. That worked, i.e. frontend looked ok. Then I have created a child template named "Child_1", so the generated name at the end was "Cassy_cild_1"- That worked. But then I make the template style of this child be the default, the frontpage looks like in my screenshot, i.e. some but not all CSS seems not to be loaded.

2021-11-28 21:30 UTC, richard67 commented
@dgrammatiko Is it possible to test with both PRs #35874 and this here together? Or do they conflict somehow?

2021-11-28 21:36 UTC, dgrammatiko commented
> ut then I make the template style of this child be the default, the frontpage looks like in my screenshot, i.e. some but not all CSS seems not to be loaded.

Yeah there was something off in the cassy template, try this [Cassy_new.zip](https://github.com/joomla/joomla-cms/files/7614418/Cassy_new.zip)

> Is it possible to test with both PRs #35874 and this here together? Or do they conflict somehow?

I think there is nothing that conflicts, so they could be tested together. Remember to apply the db changes...

2021-11-28 21:38 UTC, richard67 commented
@dgrammatiko I have just tested now with the both PR's merged together in a branch. I don't have the probklem when creating a child template of the (now inheritable) Cassiopeia and then make the template style of that child be the default.

So it either is an issue with Cassy or it needs both PR's together.

2021-11-28 22:02 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 7a95857e955f7debeee31ef58b0b43d13e85e00f<br /><br />Template manager works well with inheritable and not inheritable templates and with child templates of inheritable templates.

The right editor.css is included when editing with TinyMCE in backend, regardless if the default template style is one of an inheritable or a not inheritable template or the child template of an inheritable template.

I've tested this PR alone with the core templates being not inheritable and the inheritable Cassy template installed (fixed version), and I also have texted it in combination with PR #35874 so the core templates were inheritable.

Both worked.

If there are minor glitches which I've missed in my tests, I think they can be fixed later.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35998">issues.joomla.org/tracker/joomla-cms/35998</a>.</sub>

2021-11-28 22:13 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 7a95857e955f7debeee31ef58b0b43d13e85e00f<br /><br />Did all what I can imagine for child template and using templates and template styles - all went well. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35998">issues.joomla.org/tracker/joomla-cms/35998</a>.</sub>

2021-11-28 22:15 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35998">issues.joomla.org/tracker/joomla-cms/35998</a>.</sub>

2021-11-29 03:45 UTC, Quy commented on administrator/components/com_templates/tmpl/template/default_folders.php
>  ksort($this->files, SORT_STRING);
```suggestion
defined('_JEXEC') or die;

ksort($this->files, SORT_STRING);
```

2021-11-29 07:59 UTC, richard67 commented on administrator/components/com_templates/tmpl/template/default_folders.php
>  ksort($this->files, SORT_STRING);
@dgrammatiko Applying @Quy 's suggestion here will not change RTC status. I confirm that the "use" is obsolete and will add back test results in the tracker when applied.

2021-11-29 09:47 UTC, richard67 commented
I've added back the previous test results in the issue tracker since the last commit was just the removal of an obsolete "use" statement.

2021-11-29 22:29 UTC, Quy commented on plugins/editors/tinymce/tinymce.php
> -					$msg = sprintf(Text::_('PLG_TINY_ERR_CUSTOMCSSFILENOTPRESENT'), $content_css_custom);
Remove language string?

2021-11-30 01:53 UTC, merged

2021-11-30 01:53 UTC, bembelimen commented
Thank you!