[4.1] Smart Search Sorting Drop-Down
joomla/joomla-cms pull request #35993
Opened 2021-11-08 16:15 UTC by sakiss

### Summary of Changes
Adds a user defined sorting/ordering capability to the front-end of the Smart Search results.
It does that by adding a sorting drop-down above the results.

### Testing Instructions
1. Visit a Smart Search menu item.
2. Under the "Advanced" tab, enable the "Show Sort Fields".
3. Select the "Shown Sort Fields".
4. In the front-end search for a term that return results. You should see a sorting drop-down with the fields you set.
5. Play with the drop-down to change the sorting.

### Actual result BEFORE applying this Pull Request
No front-end sorting.

### Expected result AFTER applying this Pull Request
Front-end sorting

### Documentation Changes Required
DKN

2021-11-08 16:28 UTC, brianteeman commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
this makes no sense. What were you trying to do?

2021-11-08 16:32 UTC, sakiss commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
Are you referring to the `<p class="visually-hidden"`?
This is pretty much the same way as the language module implements a bootstrap drop-down.

You are welcome to suggest a better way.

2021-11-08 16:34 UTC, brianteeman commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
a better way for what? what are you trying to achieve?

2021-11-08 16:40 UTC, sakiss commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
Can you become more specific?

2021-11-08 16:44 UTC, brianteeman commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
no - thats why i am asking

2021-11-09 19:03 UTC, RickR2H commented
I can imagine some use cases in which controlling the sort order in the frontend can be really helpful. Maybe it's a good idea to add a background hover to the dropdown. 

@sakiss better keep your branch up to date ;)

2021-11-09 19:09 UTC, RickR2H commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
@brianteeman please be constructive, Saying something makes nos sense, makes no sense too :smile:

2021-11-09 19:14 UTC, RickR2H commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
@sakiss may it's a good idea use a dropdown instead of a button. Just look at the default implementation of the dropdowns in the advanced search.
![image](https://user-images.githubusercontent.com/5610413/140989558-bf2afe6a-5523-44f1-9087-886e37347c7e.png)

2021-11-09 21:15 UTC, brianteeman commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
What are you trying to do with this line of code? I can't possibly say if its correct or to suggest improvements without knowing what the intention of the line is. As it is right now adding some text that says "Sort by" and then hiding it makes no sense. I can make a guess what you think it does and you would be wrong that it doesnt do that but I don't like to make guesses and assumptions which is why I have asked you three times what is it you are trying to do.

2021-11-09 21:31 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on 139672a41ded5c90c28f77b373f45455b6f1742d<br /><br />As well as the unanswered comment this PR can be marked as unsuccessful as you can not sort by relevance descending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-11-10 10:36 UTC, sakiss commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
@brianteeman Well. Your question was very vague along with a multi-line code snippet.
When someone asks for clarification, probably he is not in a position to answer your question, unless you provide one.

Thanks for clarifying!
Well the line 19 	`<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>` is used as an aria-label by the button see line 27

@RickR2H No. We are dealing with urls/links. If we use select/drop-downs we have to use javascript to achieve that. An extra step of reductant complexity. Also this drop-down is much easier to customize.

2021-11-10 10:38 UTC, sakiss commented
> I can imagine some use cases in which controlling the sort order in the frontend can be really helpful. Maybe it's a good idea to add a background hover to the dropdown.
> 
> @sakiss better keep your branch up to date ;)

The drop-down follows the styling and markup of the language module (possibly another elsewhere too).

2021-11-10 10:46 UTC, brianteeman commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
So then you have a label for screenreader users and a meaningless dropdown floating randomly on the page

2021-11-10 11:06 UTC, sakiss commented on components/com_finder/tmpl/search/default_sorting.php
> +	<p class="visually-hidden" id="finder_sorting_desc"><?php echo Text::_('COM_FINDER_SORT_BY'); ?></p>
> So then you have a label for screenreader users and a meaningless dropdown floating randomly on the page
Really now?

2021-11-11 14:57 UTC, PhilETaylor commented on components/com_finder/src/Model/SearchModel.php
> +		'price.desc' => 'COM_FINDER_SORT_BY_PRICE_DESC'
Multiline array should have a trailing comma on last item in the array

```suggestion
		'price.desc' => 'COM_FINDER_SORT_BY_PRICE_DESC',
```

2021-11-11 14:58 UTC, PhilETaylor requested changes

2021-11-11 14:58 UTC, PhilETaylor commented on components/com_finder/src/Model/SearchModel.php
> +	 * @since __DEPLOY_VERSION__
```suggestion
	 * @var string[]
	 *
	 * @since __DEPLOY_VERSION__
```

2021-11-11 14:58 UTC, PhilETaylor commented on components/com_finder/src/Model/SearchModel.php
> +	 * @since   __DEPLOY_VERSION__
```suggestion
	 * @throws  \Exception
	 *
	 * @since   __DEPLOY_VERSION__
```

2021-11-11 14:59 UTC, PhilETaylor requested changes

2021-11-11 14:59 UTC, PhilETaylor commented on components/com_finder/src/Model/SearchModel.php
> +		$app->triggerEvent('onFinderSortOrderFields', array(&$sortOrderFields));
```suggestion
		$app->triggerEvent('onFinderSortOrderFields', [&$sortOrderFields]);
```

2021-11-11 14:59 UTC, PhilETaylor commented on components/com_finder/src/Model/SearchModel.php
> +	 * @since   __DEPLOY_VERSION__
```suggestion
	 * @throws  \Exception
	 *
	 * @since   __DEPLOY_VERSION__
```

2021-11-19 09:09 UTC, ricardo1709 commented
I have tested this item :white_check_mark: successfully on 4302393300b72020d60dab5f18f54a90b4eb4c83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-11-22 22:03 UTC, RickR2H commented
@sakiss Is it correct that "Relevance" only has "descending"? All the other options have both.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-11-23 10:47 UTC, sakiss commented
@RickR2H Yes it is how it is designed (see description).
I cannot think of a case that a reasonable user sorts the items by "relevance ascending".
So this will only be displayed if  "relevance ascending" is the default sorting option.

2021-11-23 10:48 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on 4302393300b72020d60dab5f18f54a90b4eb4c83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-11-23 10:49 UTC, RickR2H commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-11-23 11:11 UTC, brianteeman commented
This is not correct and should not be rtc https://github.com/joomla/joomla-cms/pull/35993#discussion_r746468229

2021-11-23 12:25 UTC, sakiss commented
@brianteeman what exactly is not correct? Plz be clear.

2021-11-23 14:09 UTC, brianteeman commented
1. Should not be possible to display a dropdwon when you have no shown fields

![image](https://user-images.githubusercontent.com/1296369/143036623-36b699dd-f97d-48ae-8850-038983ffa14f.png)

![image](https://user-images.githubusercontent.com/1296369/143036636-337c3cd2-1361-4868-bbdc-a19c3c42a7f3.png)

2. Should not display fields you have not selected

![image](https://user-images.githubusercontent.com/1296369/143036947-6116859b-a522-410f-9cf6-05490cc1e86c.png)

![image](https://user-images.githubusercontent.com/1296369/143036956-31fe4aee-2a0f-45b0-ab68-4c59e7457c9e.png)

3. No label on the field to tell you what it is - instead of floating randomly on the page

![image](https://user-images.githubusercontent.com/1296369/143037424-de72e8ac-ee57-438a-ad2f-dea4cf226c77.png)

![image](https://user-images.githubusercontent.com/1296369/143037475-db362fc5-aa1e-4b98-bc0e-3782074b425d.png)

4. Relevance

Makes no sense that you can sort by relevance ascending with these options

![image](https://user-images.githubusercontent.com/1296369/143038008-3b262447-6aeb-4f9e-913f-9eb79b1238ac.png)

![image](https://user-images.githubusercontent.com/1296369/143038037-bf2a9ab3-3120-4b2b-8c73-db04f4167572.png)

But not with these options

![image](https://user-images.githubusercontent.com/1296369/143038149-a15511aa-25af-4f7e-995e-5fde486c3c87.png)

![image](https://user-images.githubusercontent.com/1296369/143038186-82eb474a-be02-461a-8416-2312402ccf5f.png)

2021-11-23 16:31 UTC, sakiss commented
1, 2. The default value is always added to the drop-down because otherwise the shown/default selection will be irrelevant/out of context.
3. Added
4. I cannot think of any case that sorting by relevance ascending would make any sense. This is why it is shown only if is set as default in the backend.
6. That would be great and was the 1st thing i developed. 
Unfortunately it turns out that parameters with arrays are not inherited properly. Instead of showing the selected values shows an "Array" string.

2021-11-25 09:27 UTC, bembelimen commented
Revert RTC as it needs some rework<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-11-26 11:28 UTC, sakiss commented
Changes applied

2021-11-26 11:54 UTC, brianteeman commented on components/com_finder/src/Model/SearchModel.php
> +		$params               = $app->getParams();
Could also just be
`$params = Factory::getApplication()->getParams();`

2021-11-26 12:01 UTC, brianteeman commented
I still think its wrong that you can have a field shown in the dropdown that is not in the list of fields you mark as shown fields

![image](https://user-images.githubusercontent.com/1296369/143577932-600da6b9-c3a7-4f6a-870d-d12142c280d1.png)

![image](https://user-images.githubusercontent.com/1296369/143577943-d7001ce7-b6d4-4b1e-8d8a-e1583b12e115.png)

2021-11-26 12:03 UTC, brianteeman commented
>> No label on the field to tell you what it is - instead of floating randomly on the page

> Added

Still dont see it

2021-11-26 14:58 UTC, sakiss commented
> I still think its wrong that you can have a field shown in the dropdown that is not in the list of fields you mark as shown fields
Lets say that we are not including the default field in the 'shown fields' and then perform a search. You will notice the following:
1. What you get as the selected sorting field does not match the actual one.
2. Changing the sorting field to one of the shown does not let us go back to the default.

> Still dont see it
check bf29cb2c85cc9ff4151067a6274cb5924d0b751d

2021-11-26 15:04 UTC, sakiss commented on components/com_finder/src/Model/SearchModel.php
> +		$params               = $app->getParams();
We use the $app again in line 393. 
Hence we either have to duplicate the function call or the variable. I find the later shorter and more elegant.

2021-11-26 15:50 UTC, brianteeman commented on components/com_finder/src/Model/SearchModel.php
> +		$params               = $app->getParams();
sorry i missed the second usage you are correct

2021-11-26 15:57 UTC, brianteeman commented
Weirdly when I check out your branch it doesnt show that commit. Anyway I can see it here and it looks ok now - thanks

2021-11-26 16:01 UTC, brianteeman commented
> In short using a field without displaying it as an option seems a bit dissonant from the user point of view.

Perhaps but at the same time it is called "Shown Fields" and you are showing a field that is not there.

User has three fields as shown. They remove one and they still see three in the frontend. 

Makes logical sense to a developer but not to a user

2021-11-26 16:44 UTC, sakiss commented
> Perhaps but at the same time it is called "Shown Fields" and you are showing a field that is not there.
> User has three fields as shown. They remove one and they still see three in the frontend.
> Makes logical sense to a developer but not to a user

I agree, that it can be confusing for the admin.
But what about the end user? 
He will get something that seems buggy and partially functional.

@bembelimen could possibly decide on that.

2021-11-26 16:46 UTC, brianteeman commented
Two options

1. Whatever you select in the "show field" is automatically added to the "shown field"
2. Change the text to "Additional sort fields"

2021-11-26 16:52 UTC, sakiss commented
I would prefer the 1 but seems that needs work, way beyond that PR.
2 can be confusing too. Someone anticipates another "Shown field".

What about adding a description to the field that informs the admin that the default is always there?

2021-11-30 11:51 UTC, sakiss commented
What about renaming the field to "Sort Fields". 
Given that it shows only after the "Show Sort Fields" is enabled, becomes quite evident what is it about.
Also the default field is named "Sort Field", hence aggregating them seems valid.

I would appreciate your prompt feedback to catch up the feature freeze.

2021-11-30 12:04 UTC, brianteeman commented
No. Thats the whole point of my comment. You have fields in the dropdown that are not in the selected field

2021-11-30 12:08 UTC, sakiss commented
Fine. I will go on by changing the label to "Additional Sort Fields".
Can we go on with that?

2021-11-30 12:15 UTC, brianteeman commented
>Fine. I will go on by changing the label to "Additional Sort Fields".
Can we go on with that?

I wouldnt have suggested it otherwise ;)

2021-11-30 12:30 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on c072ff171deb092463b2e058f801703a0fcf6ee9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-11-30 13:04 UTC, sakiss commented
@ricardo1709 and @RickR2H Could you please test again?

2021-11-30 13:25 UTC, ricardo1709 commented
I have tested this item :white_check_mark: successfully on c072ff171deb092463b2e058f801703a0fcf6ee9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-11-30 13:27 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-12-02 17:34 UTC, pritam825 commented
I have tested this item :white_check_mark: successfully on c072ff171deb092463b2e058f801703a0fcf6ee9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2021-12-06 14:43 UTC, sakiss commented
@bembelimen do you consider merging that? Thanks

2021-12-06 14:51 UTC, bembelimen commented
It's on the list, we just have to finish the current releases coming the next days.

2021-12-07 11:26 UTC, bembelimen commented
So I checked this PR, the following things did I discover:
- Dropdown items do not use the "[dropdown-item](https://getbootstrap.com/docs/5.1/components/dropdowns/)" class. (Then you don't need all this styling)
- The sort (in my opinion) still is "flying around" without any structure and in my opinion it should be above the filter:
![grafik](https://user-images.githubusercontent.com/1229869/145019839-16e207f3-8be0-455e-9645-5c7831c4cf35.png)
- I wonder if "list_price" is ever used (I guess it's a placeholder for e.g. shops?). But when ordering by it, probably it should be displayed at the item?

2021-12-08 12:19 UTC, sakiss commented
> Dropdown items do not use the "dropdown-item" class. (Then you don't need all this styling)

I can do that but there will be small styling differences between that and other bs drop-downs e.g. the languages module.

> The sort (in my opinion) still is "flying around" without any structure and in my opinion it should be above the filter:

IMO should be as close to the results as possible. The usual workflow is to be used after a search is performed.
Btw. This is the place where almost all major search engines and sites are using it.

> I wonder if "list_price" is ever used (I guess it's a placeholder for e.g. shops?). But when ordering by it, probably it should be displayed at the item?

Yes i think they are placeholders for other types of content.
But sorting should not get confused with what is getting displayed in the results.
Also the results can be of different contexts and display different fields.

2021-12-10 12:44 UTC, sakiss commented
@bembelimen plz let me know your thoughts on that

2021-12-15 15:25 UTC, sakiss commented
Sorry to be persistent but is there an interest on that?

2021-12-16 06:00 UTC, bembelimen commented
> @bembelimen plz let me know your thoughts on that

I gave you my thoughts:
- use default styling
- don't let it fly around (of there is no other way than that, do it above the filters)
- if using list_price then also use sale_price, too

2021-12-22 13:53 UTC, sakiss commented
1. Use bootstrap "dropdown-item" class.
2. Moved the drop-down inside the results area.
3. The scope of that PR, is to let the user set the ordering based on the already used sort field options (see "sort field" param). 
I suggest adding additional fields in a separate PR.

2022-01-16 15:04 UTC, RickR2H commented
@bembelimen Could you please update the status on this PR? Is RTC still valid?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2022-02-14 11:05 UTC, woluweb commented
Hi there.
In 2 days I am making a presentation about customizing the Smart Search (Joomla NEXT session organized by Techjoomla).

I saw that the other PR (adding the possibility to add the Intro Image in the Smart Search Results Page) is indeed visible in J4.1-rc4.

But I did not see the current PR :)

Will it not be merged for 4.1?
I had the impression it was ready.
Txs

2022-02-14 12:39 UTC, RickR2H commented
Unfortunately It's nod merged so it has to wait until 4.2 I guess...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2022-02-21 15:22 UTC, sakiss commented
@roland-d Are you interested in merging that in J4.2?

2022-02-21 16:05 UTC, woluweb commented
Speaking about Sorting, it could also be an opportunity to investigate further this "sort by List Price" which has been there since 2.5 but does not do anything apparently. See https://issues.joomla.org/tracker/joomla-cms/37112

2022-02-21 16:40 UTC, sakiss commented
@woluweb Since Finder is component agnostic, allows the use of other possible variables that could be used by 3rd parties. Such variable is the "List Price", which i suppose can be utilized by e-commerce related extensions.

2022-02-21 20:00 UTC, roland-d commented
@sakiss I am interested to include this in 4.2 but I do have the same reservations as Benjamin:
- Move the filter to the top of the page
![image](https://user-images.githubusercontent.com/359377/155018804-85f38d83-0a6b-4ece-a8b1-6e87fa29fff0.png)

   Like here is what I mean:
   ![image](https://user-images.githubusercontent.com/359377/155018947-09ee5df8-f6d0-4d0b-9b05-0a0ceb87da1a.png)
- The `sale_price` needs to be added if you are adding the `list_price`. We can add these fields even if they are odd. Users won't use them but since they are in core who wants to use them can.

2022-02-23 11:54 UTC, sakiss commented
Hey @roland-d thanks for looking at that.

1. In most cases, the sorting field is placed below the search/filters and above the results. 
You can see that in all major e-commerce sites (amazon, ebay) and in blogs.
If i am not mistaken, the same applies in your screenshot.

2. I used the existing sorting fields. The PR just intends to provide sorting functionality to the front-end using the fields that Joomla already uses. I find adding extra beyond the scope of the PR but if you find it crucial i can add them.

2022-03-07 22:25 UTC, roland-d commented
Hey @sakiss 
1. You are right, my screenshots are confusing. The arrow is wrong, too high. However the filter is now floating to the right and is not below the search field. Can you fix that?
2. I do want the `sale_price` added as well as it is a small change but will be consistent with the fields that exist.

2022-03-11 11:40 UTC, sakiss commented
thanks @roland-d 

1. Could you please indicate me how you would like this to be? Btw. It is at the top-end of the results where you will find it in most apps/sites. Consider that this is a tool for the results themselves and should not be confused with the filters.
2. Ok i can do that. Do note that the `sales_price` does not exist and never existed in any Joomla setting. It only resides in the database.

2022-03-11 12:35 UTC, woluweb commented
My 2cents: `sale_price` is not used anywhere.
It is only visible in the backend so, somehow, it was not causing any harm bc nobody would see it.

But if we start showing this in the front-end, then please tell also how to hide it after!
This field seems to be there "in case some 3rd party extension would decide to use it".
I definitely don't want (nobody wants) to see "sale_price" if it does not exist: the visitors would get completely lost :D

2022-03-12 08:17 UTC, roland-d commented
@woluweb We will not be showing it in the front-end by default. The user has to specifically select that field to make it show up in the front-end.

@sakiss 

1. I am thinking like this. That is how I see it on the major ecommerce sites you mentioned.
![image](https://user-images.githubusercontent.com/359377/158009988-3801ae16-422d-484a-83a3-c04ad3e35d89.png)

2. I am aware of that but what is important to me is that we offer the use of this field and if someone uses this field, they cannot select it.

2022-03-12 17:12 UTC, sakiss commented
@roland-d
1. Are you ok if we put it below the "Assuming abc ..."?
I think it should be close to the results.

2. What if i create another PR for that?
Among others we will not have to ask for re-testing which is done several times already.

2022-03-12 17:49 UTC, roland-d commented
@sakiss 
1. That is fine by me
2. This needs retesting anyway as the sale_price still needs to be added. Let's make these 2 changes and after that it can be tested and merged.

2022-06-09 10:28 UTC, sakiss commented
@roland-d What's your intention on that?

2022-06-12 07:43 UTC, roland-d commented
@sakiss This PR looks fine to me now.
@Hackwar Can you give this a check to see if it is OK?

2022-09-26 09:18 UTC, woluweb commented
Hi,
This week-end I was at JoomlaDay D-A-CH and made my presentation about "customizing the Smart Search Results Page".
Actually I was convinced that the current PR had been merged with J4.2...
But when I came to the topic here https://slides.woluweb.be/smartsearch/smartsearch.html#5-2-in-the-front-end I realized that it had not yet been merged :D

I don't think that there is any more reason to wait.
Could we please merge this PR so that we finally get it in J4.3?
Txs for your feedback/approval @roland-d @Hackwar @obuisard :)

And txs again @sakiss -who was also present at #jd22dach- for writing this PR! (and for the other ones related to Smart Search like adding the Image etc).

2022-09-26 09:22 UTC, laoneo commented on administrator/components/com_finder/config.xml
> +			<option value="sale_price">COM_FINDER_CONFIG_SORT_OPTION_SALES_PRICE</option>
What does a sales price option have to do in core?

2022-09-26 09:26 UTC, woluweb commented on administrator/components/com_finder/config.xml
> +			<option value="sale_price">COM_FINDER_CONFIG_SORT_OPTION_SALES_PRICE</option>
Indeed @laoneo :)
See all the informations I could gather about this "list price" here:
https://slides.woluweb.be/smartsearch/smartsearch.html#par_51

2022-09-26 09:31 UTC, RickR2H commented
@sakiss did you added the changes and is the PR ready? @roland-d Do we have to reset the tests?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2022-09-26 10:54 UTC, ghost commented on administrator/components/com_finder/config.xml
> +			<option value="sale_price">COM_FINDER_CONFIG_SORT_OPTION_SALES_PRICE</option>
https://github.com/joomla/joomla-cms/issues/37112#issuecomment-1078441393: "Yes, the price field currently is not used, but we have it and it would allow shops to use smart search as well. I don't think we want to remove that." (Hackwar)

2022-09-27 17:12 UTC, roland-d commented
@woluweb This also fell off my radar but has to be rebased to 4.3 so @obuisard can pick it up and merge. The tests should be reset @RickR2H as you have a new base and it will be good to get things tested just to be sure. If nothing comes up, it would be easy tests.

2022-09-28 06:18 UTC, RickR2H commented
@roland-d can you set the unresolved conversation to resolved? Tests are reset, @ricardo1709 @woluweb please test again.

2022-09-28 14:31 UTC, obuisard commented on administrator/components/com_finder/config.xml
> +			<option value="sale_price">COM_FINDER_CONFIG_SORT_OPTION_SALES_PRICE</option>
Those fields have been in place for so many years (at least 9 !), they could be used by third party extensions by now. The debate to remove them has been going on for years and no step has been taken to do anything about it. We have no clue if they are being used 'in the wild'. Therefore they have to stay IMO.

2022-09-28 14:33 UTC, obuisard commented
Thank you all for the follow ups, I moved it to 4.3.

2022-10-20 07:51 UTC, woluweb commented
I have tested this item :white_check_mark: successfully on c072ff171deb092463b2e058f801703a0fcf6ee9<br /><br />Excellent!
Works fine (see the demo here https://subform.joomlacustomfields.org/search?q=lorem)
It is very nice that you can select the Fields that you want (or not) in the dropdown, namely
- Title
- Relevance
- Date
- List price
- Sales price<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2022-10-20 09:58 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on c072ff171deb092463b2e058f801703a0fcf6ee9<br /><br />Filters work as expected!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2022-10-20 09:58 UTC, RickR2H commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35993">issues.joomla.org/tracker/joomla-cms/35993</a>.</sub>

2022-10-21 21:32 UTC, obuisard commented
Thank you for this PR, could you please document the new options (I believe this page is appropriate: https://docs.joomla.org/Help310:Menus_Menu_Item_Finder_Search)

2022-12-17 11:25 UTC, obuisard commented
Hello Sakis @sakiss, do you need help with documentation? Would love to see this PR merged soon for public testing.

2022-12-19 16:15 UTC, sakiss commented
Hi @obuisard . The page you mention is for J3. If you indicate the page and how to add the changes, i am keen to do it.

2022-12-24 17:30 UTC, sakiss commented
@obuisard Plz let me know if this can be merged or otherwise what else should be done.

2022-12-24 17:34 UTC, obuisard commented
> @obuisard Plz let me know if this can be merged or otherwise what else should be done.

Hi Sakis @sakiss, I have requested some help to better assist you with user documentation. I am waiting on a reply. I will let you know what can be done with documentation once I have proper information. Thank you for your patience and have great holidays 🎄

2022-12-30 11:32 UTC, brianteeman commented
This is the correct page to update 
https://docs.joomla.org/Help4.x:Menus_Menu_Item_Search_Results

2023-01-06 16:47 UTC, obuisard commented
I have involved the documentation team for the PRs that require user documentation, as it needs approval for editing the wiki, which is a road block for now.

2023-01-07 13:10 UTC, ceford commented
Why is the sort order not being appended to the search bar as in all backend search bars?

2023-01-07 13:25 UTC, ceford commented
> 

That page is for the old Search component. It is not present in J4. There is no Help page for frontend results.

2023-01-07 21:26 UTC, obuisard commented
> That page is for the old Search component. It is not present in J4. There is no Help page for frontend results.

The only corresponding page I could find is https://docs.joomla.org/Special:MyLanguage/Help4.x:Menus_Menu_Item_Finder_Search

2023-01-08 19:01 UTC, ceford commented
> > That page is for the old Search component. It is not present in J4. There is no Help page for frontend results.
> 
> The only corresponding page I could find is https://docs.joomla.org/Help4.x:Menus_Menu_Item_Finder_Search
> 
> The explanation for frontend results needs to be put on that page, like it was done for https://docs.joomla.org/Help310:Menus_Menu_Item_Search_Results

Actually, the corresponding page is https://docs.joomla.org/Help310:Menus_Menu_Item_Finder_Search and that does not mention a frontend view. Such a view would be useful. But, I think this requirement to have documentation in place before merging a pull request is unworkable. I have an idea for how to do something about it but it is not ready yet.

2023-01-10 17:59 UTC, carlitorweb commented
Changes already document at https://docs.joomla.org/Help4.x:Menus_Menu_Item_Search_Results

2023-01-10 18:20 UTC, ceford commented
> Changes already document at https://docs.joomla.org/Help4.x:Menus_Menu_Item_Search_Results

That file is not used in Joomla 4 (I should have made that clearer previously). This is the file used for the Smart Search menu item:

https://docs.joomla.org/Help4.x:Menu_Item:_Search

2023-01-10 20:35 UTC, obuisard commented
> > Changes already document at https://docs.joomla.org/Help4.x:Menus_Menu_Item_Search_Results
> 
> That file is not used in Joomla 4 (I should have made that clearer previously). This is the file used for the Smart Search menu item:
> 
> https://docs.joomla.org/Help4.x:Menu_Item:_Search

[https://docs.joomla.org/Help4.x:Menus_Menu_Item_Finder_Search](https://docs.joomla.org/Help4.x:Menus_Menu_Item_Finder_Search) and https://docs.joomla.org/Help4.x:Menu_Item:_Search is the same page

2023-01-11 19:57 UTC, carlitorweb commented
Okay, now we got the right doc (Chunk) to override: https://docs.joomla.org/Chunk4x:Help_screen_column_header_Sort_Field

Documentation added ✔️

2023-01-11 23:02 UTC, merged

2023-01-11 23:02 UTC, obuisard commented
Thank you Sakis @sakiss for this PR!

2023-05-16 12:38 UTC, Kostelano commented
@sakiss, could you take a couple of minutes of your time and explain what is the fundamental difference between **Sales price** and **List price**? I am engaged in translation and have not even figured out yet how best to translate it so that it is understandable to users. Thank you.

2023-05-16 13:10 UTC, woluweb commented
> @sakiss, could you take a couple of minutes of your time and explain what is the fundamental difference between **Sales price** and **List price**? I am engaged in translation and have not even figured out yet how best to translate it so that it is understandable to users. Thank you.
> 
> In the context of the search )) Of course, the translation without the search is understandable.

This is a Joomla string which has been there "forever".
See here the information I could gather about that: https://slides.woluweb.be/smartsearch/smartsearch.html#par_51

2023-05-16 14:12 UTC, Kostelano commented
@woluweb Thanks for the hint, now it's clearer that the parameter means nothing )). Of course, this is a success: to add SOMETHING for user management that cannot and could not work, but only confuses.

2023-05-16 20:25 UTC, RickR2H commented
Settings are still there due to backwards compatibility. They can be removed in J5.

2023-05-17 10:53 UTC, sakiss commented
@Kostelano keep in mind that the Smart Search is designed to work with different types of content (not just articles)