[4.1] Tags module limit
joomla/joomla-cms pull request #36019
Opened 2021-11-12 10:52 UTC by chmst

Pull Request for Issue #36016.

### Summary of Changes
As title says. For both tag modules. 

### Testing Instructions
Use more than 20 tags to yor articles, 
Set the maximum to a number > 20 and make sure that the tags are displayed corrctly in frontend

### Actual result BEFORE applying this Pull Request
see #36016

### Expected result AFTER applying this Pull Request
Any number is possible 

### Documentation Changes Required

2021-11-12 11:09 UTC, HLeithner commented
if you do it this way you have to modify the php code to allow "0" as no limit option.

2021-11-12 14:28 UTC, Shubhamverma2796 commented
Before: 
![screen shot 2021-11-12 at 14 24 55](https://issues.joomla.org/uploads/1/5fc097aea873606b354892598f60db83.png)

Clearly visible that the maximum count is 20

After:

![screen shot 2021-11-12 at 14 28 02](https://issues.joomla.org/uploads/1/9177c6e01e6494b333e2a9933f6f7e09.png)

Now user can set the value of the maximum count.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36019">issues.joomla.org/tracker/joomla-cms/36019</a>.</sub>

2021-11-12 14:28 UTC, Shubhamverma2796 commented
I have tested this item :white_check_mark: successfully on 38eb9e9e927a202c9b8aac40a4f547e40cf2ccd8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36019">issues.joomla.org/tracker/joomla-cms/36019</a>.</sub>

2021-11-12 16:45 UTC, BertaOctech commented
I have tested this item :white_check_mark: successfully on 38eb9e9e927a202c9b8aac40a4f547e40cf2ccd8<br /><br />I followed the test instructions and the patch worked as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36019">issues.joomla.org/tracker/joomla-cms/36019</a>.</sub>

2021-11-12 17:56 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36019">issues.joomla.org/tracker/joomla-cms/36019</a>.</sub>

2021-11-12 18:04 UTC, brianteeman commented
@HLeithner requested valid changes. please remove RTC

2021-11-12 18:06 UTC, alikon commented
oops missed that

2021-11-12 19:21 UTC, chmst commented
@HLeithner  default is 5 as in other modlules. The value 0 is not really useful, of course, as the result then would be empty, but for mysql this is not a  problem. 
If I change it here ( 0 = all), we must change it in all other modules too.

2021-11-13 10:12 UTC, HLeithner commented
> @HLeithner default is 5 as in other modules. The value 0 is not really useful, of course, as the result then would be empty, but for mysql this is not a problem. If I change it here ( 0 = all), we must change it in all other modules too.

That's the reason I requested the implementation for this case in php (check for 0 and remove the setlimit call)

2021-11-14 08:23 UTC, chmst commented
Made the changes as requested by @HLeithner . Only if the input is > 0, the maximum number is set as limit. Could you please re-test? @BertaOctech  @Shubhamverma2796 ? Thanks!

2021-11-14 08:32 UTC, richard67 commented
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36019">issues.joomla.org/tracker/joomla-cms/36019</a>.</sub>

2021-11-14 08:33 UTC, HLeithner requested changes

2021-11-14 08:33 UTC, HLeithner commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($params->get('maximum','5') > 0)
```suggestion
		if ((int) $params->get('maximum', 5) > 0)
```

2021-11-14 08:33 UTC, HLeithner commented on modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
> +		if ($params->get('maximum','5') > 0)
```suggestion
		if ((int) $params->get('maximum', 5) > 0)
```

2021-11-14 08:34 UTC, richard67 commented on modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
> +		if ($params->get('maximum','5') > 0)
```suggestion
		if ($params->get('maximum', '5') > 0)
```
Fix PHP CS for drone.

2021-11-14 08:45 UTC, richard67 commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($params->get('maximum','5') > 0)
Why not use $maximum here? It is set at the beginning here https://github.com/joomla/joomla-cms/blob/14166af1d561ef33887d0ce6aebea01b854b52e9/modules/mod_tags_popular/src/Helper/TagsPopularHelper.php#L41 and now unused after these changes.

We could change that line 41 to `$maximum = (int) $params->get('maximum', 5);`, i.e. add the type cast to integer, and then here and below use `if ($maximum > 0)`.

2021-11-14 08:47 UTC, richard67 commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($params->get('maximum','5') > 0)
Or do as suggested by Harald and remove line 41.

2021-11-14 10:39 UTC, HLeithner commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($params->get('maximum','5') > 0)
of course use $maximum from line 41 (cast it to int first please) and for get this suggestion

2021-11-14 13:33 UTC, Shubhamverma2796 commented
@chmst I applied the path and here are the results:

![Screenshot (272)](https://user-images.githubusercontent.com/54266411/141683296-3b500911-2d60-46fb-8ae3-3251f1e2229c.png)

As you can clearly see the maximum tag value can be set as negative too.  I think you should set the lower limit to  0 because obviously there is no point in setting -ve values.

2021-11-14 17:10 UTC, HLeithner requested changes
Add a Minimum auf 0 items

2021-11-14 17:10 UTC, HLeithner commented on modules/mod_tags_popular/mod_tags_popular.xml
>  					filter="integer"
```suggestion
					filter="integer"
					min="0"
```

2021-11-14 17:10 UTC, HLeithner commented on modules/mod_tags_similar/mod_tags_similar.xml
>  					filter="integer"
```suggestion
					filter="integer"
					min="0"
```

2021-11-14 17:57 UTC, richard67 commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($params->get('maximum','5') > 0)
@chmst This one here is not done yet.

2021-11-16 17:08 UTC, chmst commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($params->get('maximum','5') > 0)
done

2021-11-16 17:10 UTC, chmst commented
The min attribute in the number field is not validated. Also with min=0 it is possible to enter every negative value. This is not in scope of this PR.

2021-11-16 17:16 UTC, richard67 commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +			$query->setLimit((int) $params->get('maximum'));
```suggestion
			$query->setLimit($maximum);
```

2021-11-16 17:49 UTC, closed without merging

2021-11-16 18:04 UTC, richard67 commented
@chmst Why closed?

2021-11-16 21:36 UTC, chmst commented
@Shubhamverma2796 would you like to open an issue for the bug you found  in joomla? https://github.com/joomla/joomla-cms/pull/36019#issuecomment-968291979
Maybe you also find a solution ;)

2021-11-17 13:38 UTC, Shubhamverma2796 commented
@chmst  How can I open an issue because this PR is closed before getting merged, and the hard limit is still 20. Please correct me if I'm wrong.

2021-11-17 13:45 UTC, chmst commented
The hard limit is independent from this. You found out, that it is possible to enter a negative value into a field of type="number" , also when the attribute min="0" is set. The field does not validate the input. 

You can open a new issue here 
![image](https://user-images.githubusercontent.com/1035262/142212051-aadfea2f-81c5-44cb-8559-fac93cf80e6e.png)

and write a bug report. If you want ;)

2021-11-19 12:35 UTC, Shubhamverma2796 commented
https://user-images.githubusercontent.com/54266411/142622699-797fae8a-e78c-41d2-9019-63fd18c862c2.mp4

@chmst  In the above video, you can see that I've fixed the issue; whenever the user tries to input any -ve value, the value automatically gets changed to 0. In this way, we can easily prevent the user from entering any negative value. 
The problem is I am new here and not well-versed with the file and code structure of Joomla. Therefore, I cannot figure out where(in which file or folder) I should put the function written by me so that everything works fine. If anyone can guide me, then it would be my pleasure. 
Thanks 

[Link to the function](https://jsfiddle.net/4qju780h/)

2021-11-19 12:47 UTC, brianteeman commented
@Shubhamverma2796 javascript is not the solution

2021-11-20 16:14 UTC, brianteeman commented
> The min attribute in the number field is not validated. Also with min=0 it is possible to enter every negative value. This is not in scope of this PR.

Just add validate="number" and this will ensure that the min=0 is validated

2021-11-22 12:41 UTC, Shubhamverma2796 commented
@chmst  should I open a new pr for #36016 or will you re-open this pr itself?