Fix Codemirror behind tabs
joomla/joomla-cms pull request #36140
Opened 2021-11-28 13:44 UTC by Fedik

Pull Request for Issue #35096 .

### Summary of Changes
Use IntersectionObserver to refresh Codemirror when it become visible

### Testing Instructions

Apply patch, run `npm install`.
Add editor somewhere in hidden tab, example to Custom HTML module :
```xml
<field type="editor" name="editor_test" editor="codemirror" label="editor test" default="I am a text!"/>
```

Visit the module form, and click on tab with this editor.

### Actual result BEFORE applying this Pull Request
Editor is empty

### Expected result AFTER applying this Pull Request
Editor should display a default text.

### Documentation Changes Required
none

2021-11-28 14:54 UTC, dgrammatiko requested changes

2021-11-28 14:54 UTC, dgrammatiko commented on build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
> +    this.intersectionObserver = new IntersectionObserver((entries) => {
@Fedik please do a simple check that the browser actually support `IntersectionObserver` before calling it

ie 
```js
if ('IntersectionObserver' in window) {
// ...
}
```

2021-11-28 14:54 UTC, dgrammatiko commented on build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
> +    this.intersectionObserver.observe(this);
Similar here:

ie 
```js
if (this.intersectionObserver) {
 this.intersectionObserver.observe(this);
}
```

2021-11-28 14:54 UTC, dgrammatiko commented on build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
> +    this.intersectionObserver.unobserve(this);
And here:

```js
if (this.intersectionObserver) {
 this.intersectionObserver.unobserve(this);
}
```

2021-11-28 17:52 UTC, Fedik commented on build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
> +    this.intersectionObserver = new IntersectionObserver((entries) => {
but support seems okay, or? https://caniuse.com/?search=IntersectionObserver

2021-11-29 18:08 UTC, ceford commented
I inserted the field in Advanced tab of mod_custon.xml, went to Modules / New / Custom Html and the field is there with the default content. If I follow the instructions in #35096 i get the editor field with line number but not the default content. The gutter is wide and the typed text appears in the correct place. So, just the default text is missing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36140">issues.joomla.org/tracker/joomla-cms/36140</a>.</sub>

2021-11-29 18:46 UTC, Fedik commented
That is correct, instruction from #35096  does not have default value, there should be just an editor.

2021-12-15 18:57 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on 4a9e06f51571261ef9027094a37c3a595acae6b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36140">issues.joomla.org/tracker/joomla-cms/36140</a>.</sub>

2021-12-15 19:01 UTC, RickR2H commented
Make sure to refresh the browser cache when testing!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36140">issues.joomla.org/tracker/joomla-cms/36140</a>.</sub>

2021-12-15 21:03 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 4a9e06f51571261ef9027094a37c3a595acae6b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36140">issues.joomla.org/tracker/joomla-cms/36140</a>.</sub>

2021-12-16 08:18 UTC, ricardo1709 commented
I have tested this item :white_check_mark: successfully on 4a9e06f51571261ef9027094a37c3a595acae6b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36140">issues.joomla.org/tracker/joomla-cms/36140</a>.</sub>

2021-12-16 08:19 UTC, RickR2H commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36140">issues.joomla.org/tracker/joomla-cms/36140</a>.</sub>

2022-01-04 00:52 UTC, merged

2022-01-04 00:52 UTC, wilsonge commented
Thanks!