WIP [4.1]  Joomla-Accessibility Checker (jooa11y).
joomla/joomla-cms pull request #36190
Opened 2021-12-03 15:48 UTC by brianteeman

Jooa11y is an accessibility and quality assurance tool that visually highlights common accessibility and usability issues.

Geared towards content authors, Jooa11y identifies many errors or warnings and provides guidance on on how to fix them. Jooa11y is not a comprehensive code analysis tool - it exclusively highlights content issues.

To see all the features of jooa11y you should visit https://joomla-projects.github.io/joomla-a11y-checker/  and see the examples and tests.

This PR is **only for** the implementation of the new Joomla-Accessibility Checker (jooa11y) in core. Any issue, bug or question about the actual accessibility checks **_must_** be made at https://github.com/joomla-projects/joomla-a11y-checker/issues

### This PR is still a Work In Progress as

1. Need to determine the best way to handle translations and none are loaded at this time in the plugin. Perhaps we go down the same path a tinymce? Suggestions welcome.

2. There are currently three different ways of activating the checker (see the tests below). Too many? Bad code? Better code? More options? Less options?

### NOTES
- As the objective of the checker is only to check the content that an author can reasonably be expected to be able to correct the check only runs on the main landmark on the page (`<main>`). This can be changed in the plugin to any other landmark/region
- The drone npm error is a known issue #36160

## Testing
- Checkout this branch
- npm i
- discover the plugin
- enable the plugin

### Test 1. 
- open an existing article and see the new toolbar button
- Click on the button in the preview window to open

![image](https://user-images.githubusercontent.com/1296369/144630160-21dd0ab2-d7cd-4a3f-b99b-1483ad62d085.png)

_**Just like the existing preview button the button is not available until the article is saved**_

### Test 2.
- Go to the plugin settings and enable the first option
- Go to the front end of the site and you can now see the plugin on every page

![image](https://user-images.githubusercontent.com/1296369/144630508-e55a09b2-39b1-46ad-9555-13504bf6d2cc.png)

### Test 3.
- Go back to the plugin settings and disable the first option
- Go to the front end of the site and add ?jooa11y=1 to the url
--	(if the url already has a ? add &jooa11y=1 instead)
- You can now see the plugin on just this page
	

The inclusion of this checker is a result of the research carried out by the EU funded We4authorsCluster accessibility project that I participated in.

This PR is the result of the combined work of @brianteeman, @bembelimen, @fedik, @chmst, @carcam

2021-12-03 19:27 UTC, PhilETaylor commented on libraries/src/Toolbar/ToolbarHelper.php
> +		// Add a button.
```suggestion
```

2021-12-03 19:28 UTC, PhilETaylor commented on plugins/system/jooa11y/jooa11y.php
> +		// @todo Text::script(...);
todo?

2021-12-03 19:29 UTC, PhilETaylor requested changes

2021-12-03 19:29 UTC, PhilETaylor commented on templates/system/build_incomplete.html
> +	<style>html{background:#ee2a00;background:radial-gradient(ellipse at center,#f1f1f1 0,#ee2a00 100%);background-attachment:fixed;background-repeat:no-repeat}body{background-color:transparent;color:#5
unrelated change to PR?

2021-12-03 19:44 UTC, dgrammatiko commented
@brianteeman please don't add for a second time popper.js. The project already has one copy in the folder`media/vendor/bootstrap`

2021-12-03 20:17 UTC, brianteeman commented on plugins/system/jooa11y/jooa11y.php
> +		// @todo Text::script(...);
Please read the PR description

2021-12-03 20:18 UTC, brianteeman commented on libraries/src/Toolbar/ToolbarHelper.php
> +		// Add a button.
Same as all the other functions so will not change. If you want to remove it then please create a pr for the entire file

2021-12-03 20:19 UTC, brianteeman commented
@dgrammatiko not my code but anyway isnt it better to be direct from upstream than inside another ?

2021-12-03 20:28 UTC, dgrammatiko commented
> but anyway isnt it better to be direct from upstream than inside another?

Having it as an individual script theoretically is better, but Bootstrap is expecting an ESM module but the dist of popper is providing an UMD and a CJS (both not suitable for the ESM Bootstrap). Also if it is a different dependency someone needs to check that the versions of BS and popper are compatible (B/C breaks are way too often...). Anyways I did a PR upstream which could go either way and then somehow align or not Bootstrap depending on the decision.

2021-12-03 20:33 UTC, brianteeman commented
Thanks for the explanation and contribution

2021-12-04 17:57 UTC, PhilETaylor commented on libraries/src/Toolbar/ToolbarHelper.php
> +		// Add a button.
Yeah that's right - keep adding the crap by copy and pasting the crap... that's how we got here in the first place. Pathetic. 

This is new code. It should be held to the correct standard. No a historic standard.

2021-12-04 17:58 UTC, PhilETaylor commented on plugins/system/jooa11y/jooa11y.php
> +		// @todo Text::script(...);
If a PR is not complete and ready for testing and merging then it should be set as draft and not proposed as a Pull Request for others to test. 

Non-draft PR's should not contain "@todo" tags.

2021-12-04 18:09 UTC, PhilETaylor commented on administrator/language/en-GB/plg_system_jooa11y.ini
> +PLG_SYSTEM_JOOA11Y_FIELD_READABILITY_ROOT_DESC="Aria Landmark on the page that will be checked for readbility. The default setting is <strong>main</strong>."
s/readbility/readability

```suggestion
PLG_SYSTEM_JOOA11Y_FIELD_READABILITY_ROOT_DESC="Aria Landmark on the page that will be checked for readability. The default setting is <strong>main</strong>."
```

2021-12-07 21:33 UTC, Quy commented on installation/sql/mysql/base.sql
> +(0, 'plg_system_jooa11y', 'plugin', 'jooa11y', 'system', 0, 1, 1, 0, 1, '', '', 8, 0),
```suggestion
(0, 'plg_system_jooa11y', 'plugin', 'jooa11y', 'system', 0, 1, 1, 0, 1, '', '', '', 8, 0),
```

2021-12-07 21:33 UTC, Quy commented on installation/sql/postgresql/base.sql
> +(0, 'plg_system_jooa11y', 'plugin', 'jooa11y', 'system', 0, 1, 1, 0, 1, '', '', 8, 0),
```suggestion
(0, 'plg_system_jooa11y', 'plugin', 'jooa11y', 'system', 0, 1, 1, 0, 1, '', '', '', 8, 0),
```

2021-12-08 18:05 UTC, Quy commented on administrator/language/en-GB/plg_system_jooa11y.ini
> +PLG_SYSTEM_JOOA11Y_FIELD_LINK_IGNORE_DESC="Ignore specific links. eg xxxxx. Use commas to seperate links."
```suggestion
PLG_SYSTEM_JOOA11Y_FIELD_CONTAINER_IGNORE_DESC="Ignore specific regions within the Content Container. Use commas to separate classes or elements."
PLG_SYSTEM_JOOA11Y_FIELD_HEADER_IGNORE="Ignore Headers"
PLG_SYSTEM_JOOA11Y_FIELD_HEADER_IGNORE_DESC="Ignore specific headings. eg 'h1.jumbotron-heading'. Use commas to separate classes."
PLG_SYSTEM_JOOA11Y_FIELD_IMAGE_IGNORE="Ignore Images"
PLG_SYSTEM_JOOA11Y_FIELD_IMAGE_IGNORE_DESC="Ignore specific images. eg 'spacer.gif'. Use commas to separate images."
PLG_SYSTEM_JOOA11Y_FIELD_LINKS_TO_FLAG="Flag Links"
PLG_SYSTEM_JOOA11Y_FIELD_LINKS_TO_FLAG_DESC="Highlight links you don't want your content editors pointing to (eg development environments, localhost etc)."
PLG_SYSTEM_JOOA11Y_FIELD_LINK_IGNORE="Ignore Links"
PLG_SYSTEM_JOOA11Y_FIELD_LINK_IGNORE_DESC="Ignore specific links. eg xxxxx. Use commas to separate links."
```

2021-12-08 23:17 UTC, Quy commented on plugins/system/jooa11y/jooa11y.php
> +	}
```suggestion
		$wa->usePreset('plg_system_jooa11y.jooa11y');
	}
```

2021-12-08 23:19 UTC, Quy commented on plugins/system/jooa11y/jooa11y.xml
> +					label="PLG_SYSTEM_JOOA11Y_FIELD_PREF_CONTRAST"
```suggestion
					label="PLG_SYSTEM_JOOA11Y_FIELD_PREF_CONTRAST"
					layout="joomla.form.field.radio.switcher"
```
Please repeat below.

2021-12-10 13:30 UTC, PhilETaylor commented on plugins/system/jooa11y/jooa11y.php
> +				return $result;
```suggestion
				return false;
```

2021-12-10 13:31 UTC, PhilETaylor commented on plugins/system/jooa11y/jooa11y.php
> +		/** @var Joomla\CMS\WebAsset\WebAssetManager $wa*/
```suggestion
		/** @var Joomla\CMS\WebAsset\WebAssetManager $wa */
```

2021-12-12 09:51 UTC, HLeithner commented
@brianteeman can you allow maintainers to push to this PR , I would like to fix the npm issue

2021-12-12 09:53 UTC, brianteeman commented
should be ok now

2021-12-12 10:19 UTC, dgrammatiko commented
@brianteeman I can't PR some changes at your fork. Anyways here are the changes https://github.com/dgrammatiko/joomla-cms/commit/9b9c1eab80b6f9009323418cd3e7d1c2ece4a5fb Basically align the code here with the changes in the joomla-projects repo

![Screenshot 2021-12-12 at 11 02 13](https://user-images.githubusercontent.com/3889375/145708592-44bc57d6-74ca-4807-83fa-d52993d9ac13.png)

2021-12-12 10:27 UTC, HLeithner commented
@dgrammatiko can you have a look at https://ci.joomla.org/joomla/joomla-cms/49185/1/21 please?

2021-12-12 10:41 UTC, brianteeman commented
@dgrammatiko done

2021-12-12 10:48 UTC, dgrammatiko commented
@HLeithner can you bump `    "eslint-plugin-vue": "^7.9.0",` to `    "eslint-plugin-vue": "^8.2.0",`?

2021-12-12 11:08 UTC, dgrammatiko commented
@brianteeman https://github.com/brianteeman/joomla-cms/pull/135

2021-12-13 12:14 UTC, brianteeman commented
Thanks @HLeithner

2021-12-13 13:47 UTC, Fedik commented on build/media_source/plg_system_jooa11y/js/jooa11y.es6.js
> +import { Jooa11y /* , Lang */ } from 'joomla-a11y-checker/dist/js/joomla-a11y-checker.esm.js';
After this https://github.com/joomla-projects/joomla-a11y-checker/pull/24, please uncomment `Lang`:
```
import { Jooa11y , Lang } from .....
```

2021-12-13 13:49 UTC, Fedik commented on build/media_source/plg_system_jooa11y/js/jooa11y.es6.js
> +
Adn add here:
```javascript
const stringPrefix = 'JOOMLA_A11Y_CHECKER_';
Lang.translate = (string) => {
      return Joomla.Text._(stringPrefix + string, string);
};
```

Where `JOOMLA_A11Y_CHECKER_` is prefix used in INI file, you can change it to another if you like.

2021-12-13 15:44 UTC, dgrammatiko commented
@brianteeman could you run `npm install` and commit back the package-lock.json

2021-12-13 15:50 UTC, Fedik commented on build/media_source/plg_system_jooa11y/js/jooa11y.es6.js
> +};
Please change this part to:
```javascript
const stringPrefix = 'PLG_SYSTEM_JOOA11Y_';
Lang.translate = (string) => {
  return Joomla.Text._(stringPrefix + string, string);
};
```
so `const stringPrefix =...` is outside

2021-12-13 15:57 UTC, brianteeman commented
@dgrammatiko I would if I wasnt getting an eintegrity error

2021-12-13 16:02 UTC, dgrammatiko commented
>I would if I wasn't getting an integrity error

I thought that the `npm ci` will only have this problem...

2021-12-13 22:07 UTC, brianteeman commented
thanks @dgrammatiko a combination of many of the things on that link and it seems ok now

2021-12-14 18:10 UTC, Quy commented on administrator/components/com_content/src/View/Article/HtmlView.php
> +					$toolbar->jooa11y($url . '&jooa11y=1', 'JGLOBAL_JOOA11Y')
```suggestion
					$toolbar->jooa11y($url . '?jooa11y=1', 'JGLOBAL_JOOA11Y')
```

2021-12-14 18:20 UTC, brianteeman commented on administrator/components/com_content/src/View/Article/HtmlView.php
> +					$toolbar->jooa11y($url . '&jooa11y=1', 'JGLOBAL_JOOA11Y')
Your suggestion does not work with sef urls OFF
The current code does not work with sef urls ON

I guess it needs a conditional check for sef

2021-12-14 19:20 UTC, dgrammatiko commented on package.json
> -    "@popperjs/core": "^2.9.2",
`"@popperjs/core": "^2.9.2",`

This should be added back or Bootstrap will be broken. My bad, sorry

2021-12-14 22:12 UTC, Quy commented on administrator/components/com_content/src/View/Article/HtmlView.php
> +					$query = (Factory::getApplication()->getConfig()->get('sef')) ? "?" : "&";
```suggestion
					$query = Factory::getApplication()->getConfig()->get('sef') ? '?' : '&';
```

2021-12-15 08:13 UTC, HLeithner commented on administrator/components/com_content/src/View/Article/HtmlView.php
> +					$query = (Factory::getApplication()->getConfig()->get('sef')) ? "?" : "&";
from my point of view there are 2 better approaches. 
1. split the Route::link into 2 calls and concat the jolly parameter directly to the `getArticleRoute()` result for the the plugin
2. as alternative you can make a `strpos('?', $url) !== false`

the first is the better solution, you shouldn't care about sef here

2021-12-15 08:35 UTC, brianteeman commented on administrator/components/com_content/src/View/Article/HtmlView.php
> +					$query = (Factory::getApplication()->getConfig()->get('sef')) ? "?" : "&";
I'd be happy to accept a pull request for either of those

2021-12-15 11:58 UTC, HLeithner commented
@brianteeman when you update https://github.com/joomla-projects/joomla-a11y-checkerhttps://github.com/joomla-projects/joomla-a11y-checker you have to run `npm update joomlüa-a11y-checker` for this pullrequest too.

if you don't do this, npm install (and tests) will fail because of the wrong signature.

2021-12-15 12:04 UTC, HLeithner commented
@brianteeman I directly pushed the preview url changes, hope that was ok.

2021-12-15 12:08 UTC, brianteeman commented
> you have to run npm update joomlüa-a11y-checker for this pullrequest too.

oops - thanks

> I directly pushed the preview url changes, hope that was ok.

Thanks for the code.

In future I would prefer if you did it as a pr on my branch as its easier to check/approve and doesnt break my workflow

2021-12-15 12:11 UTC, HLeithner commented
@dgrammatiko can you have a look at https://ci.joomla.org/joomla/joomla-cms/49265/1/21

@brianteeman will do

2021-12-15 12:13 UTC, dgrammatiko commented
> @dgrammatiko can you have a look at https://ci.joomla.org/joomla/joomla-cms/49265/1/21

@HLeithner I have a PR that updates many of the tools to their current versions: https://github.com/joomla/joomla-cms/pull/36295

Let's get that merged in 4.0 and then fetch the changes here instead of patching things here

2021-12-15 18:14 UTC, drmenzelit commented
I really like the plugin! Thank you all for the hard work.

Doing some tests now and it not clear to me what I should enter in the different fields in the advanced parameters of the plugin.
With trial and error I found out that in Ignore Regions I have to enter the class with the dot too: `.ignore` or `div.ignore` but only `ignore` doesn't work
I'm not sure how to test Ignore Headers
Ignore Images: if I enter the name of an image like `nasa2-1200.jpg` that has no alt text in the blog samples I still get the warning. If I write `'nasa2-1200.jpg'` I get a Javascript error on the browser
Ignore Links and Flag Links are not clear to me, tested different ways and got Javascript errors.

Ignore Classes withing Links worked both if I enter the class `ignore` with or without dot. The link <a` href="#"><span class="ignore">read more</span></a>` is ignored in the test.

2021-12-15 18:27 UTC, hans2103 commented
I have tested this item :white_check_mark: successfully on 6d25a63b699b2cfb17645f7c0357c1e4c014c3da<br /><br />Great job! I like it a lot.
Can't wait for J4.1 to be released!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36190">issues.joomla.org/tracker/joomla-cms/36190</a>.</sub>

2021-12-15 18:31 UTC, hans2103 commented
# Test instruction to ignore a region
- Open plugin
- Go To tab Advanced
- add `.blog` to _Ignore Regions_

## Before
![Schermafbeelding 2021-12-15 om 19 30 55](https://user-images.githubusercontent.com/639822/146244638-1d11c884-524f-4eb4-a31a-dcf5170f9731.png)

## After
![Schermafbeelding 2021-12-15 om 19 29 48](https://user-images.githubusercontent.com/639822/146244654-837e6b34-ee2d-40e2-92a8-43e6fd7aaa92.png)



Seems to work as expected

2021-12-15 18:33 UTC, hans2103 commented
# Question

- Open plugin
- Go To tab Advanced

What should be added to field _Outline Panel_?
Should this be a radio with YES / NO ?
![Schermafbeelding 2021-12-15 om 19 32 41](https://user-images.githubusercontent.com/639822/146244886-744f297e-8a95-44ca-b33d-2f1835b29af0.png)

2021-12-15 18:35 UTC, Fedik commented
> With trial and error I found out that in Ignore Regions I have to enter the class with the dot too: .ignore or div.ignore but only ignore doesn't work

@brianteeman maybe it a good idea to improve description, that these fields should contain CSS selectors

> Ignore Images: if I enter the name of an image like nasa2-1200.jpg that has no alt text in the blog samples I still get the warning.

This also, should contain CSS selector, eg `.image-class-to-ignore` or `[src$="nasa2-1200.jpg"]` (elements with a "src" ending "nasa2-1200.jpg")

2021-12-15 18:35 UTC, chmst commented
I too have tested advanced params

![image](https://user-images.githubusercontent.com/1035262/146245199-2f21d05b-c239-4417-88c8-b4b97da4ed8c.png)

And get this error

![image](https://user-images.githubusercontent.com/1035262/146244730-60aec2f9-30c0-4a63-b60a-81e95b4b5e2f.png)

As a consequence, no test was made for the whole content.

2021-12-15 18:37 UTC, Fedik commented
`linkIgnore` also should contain CSS selector, not a RAW link

2021-12-15 18:39 UTC, hans2103 commented
> > Ignore Images: if I enter the name of an image like nasa2-1200.jpg that has no alt text in the blog samples I still get the warning.
> 
> This also, should contain CSS selector, eg `.image-class-to-ignore` or `[src$="nasa2-1200.jpg"]` (elements with a "src" ending "nasa2-1200.jpg")

I don't think we can ask the Joomla users to add some code like `[src$="nasa2-1200.jpg"]` 
`nasa-2-1200.jpg` should be accepted as well. The code behind it should convert it to `[src$="nasa2-1200.jpg"]`

2021-12-15 18:44 UTC, hans2103 commented
The plugin itself works fine. 
Extra explanation is needed on the _Advanced_ tab though
Good job!

2021-12-15 18:59 UTC, brianteeman commented
Quick reply (I have a meeting)

Thanks for your testing and feedback. I will look at it all and either improve the code or the hints as appropriate

2021-12-15 22:13 UTC, brianteeman commented
Having looked more closely at the uses for the advanced options I have decided that they are very use case specific and we don't need to confuse people by adding them. So I have removed all the advanced options apart from the container ignore which is now on the first tab and with a better description.

Thanks for testing so far!!

2021-12-16 06:27 UTC, hans2103 commented
Goor call @brianteeman 
Those options can be added later too.

2021-12-16 09:00 UTC, hans2103 approved these changes

2021-12-16 09:03 UTC, hans2103 commented
I have tested this item :white_check_mark: successfully on 6d25a63b699b2cfb17645f7c0357c1e4c014c3da<br /><br />Testing again without the advanced tab and successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36190">issues.joomla.org/tracker/joomla-cms/36190</a>.</sub>

2021-12-16 10:18 UTC, chmst commented
Re-tested. No problems with removed params.

A new test found 2 errors, as expected. Bad contrast in headline and image without description but the counter is 1. 

![image](https://user-images.githubusercontent.com/1035262/146352546-0c89867b-c707-480d-9245-6b59d5bb65e4.png)

2021-12-16 17:20 UTC, Quy commented on plugins/system/jooa11y/jooa11y.php
> +				'linksToFlag'     => $this->params->get('linkIgnore'),
```suggestion
				'outlineIgnore'   => $this->params->get('outlineIgnore'),
				'headerIgnore'    => $this->params->get('headerIgnore'),
				'imageIgnore'     => $this->params->get('imageIgnore'),
				'linkIgnore'      => $this->params->get('linkIgnore'),
				'linkIgnoreSpan'  => $this->params->get('linkIgnore'),
				'linksToFlag'     => $this->params->get('linkIgnore'),
```
Remove?

2021-12-16 17:35 UTC, Quy commented on plugins/system/jooa11y/jooa11y.php
> +		return true;
> * @return  void

2021-12-16 22:42 UTC, Quy commented
The preferences settings in the plug don't appear to be in effect. How to test them?

2021-12-17 07:55 UTC, chmst commented
@quy the preferences are visible here. 
![image](https://user-images.githubusercontent.com/1035262/146509012-bd28dcde-fcff-4d33-94aa-c93a09cb2d28.png)

In fact, I could test only Contrast and Dark Mode, both are fine.

2021-12-17 13:47 UTC, Quy commented
@chmst Enabled preferences in the plugin don't reflect in the frontend. For example, dark mode is enabled in the plugin but in the frontend, dark mode is not enabled in the preferences.

2021-12-17 13:53 UTC, brianteeman commented
expected behaviour as it remembers the last setting you made when using it

2021-12-17 13:54 UTC, dgrammatiko commented
@Quy can you cast the value as a boolean here: https://github.com/joomla/joomla-cms/pull/36190/files#diff-3edb923b7235d9158b9a218b987f0623a2d5b7ceae263abd98e26cb3cfe82bd1R142

Eg `'darkmode' => (bool) $this->params->get('darkmode'),`

2021-12-17 14:11 UTC, Quy commented
@dgrammatiko Same as before with the casting.

@brianteeman So these preferences in the plugin are pointless after changing on the frontend? I will have to retest on a new install but I don't think these preferences were in effect before using it.

2021-12-17 14:13 UTC, dgrammatiko commented
@Quy you can delete the local storage to reset the state

2021-12-17 14:21 UTC, Quy commented
@dgrammatiko 
Deleted local storage. 
Enabled all preferences in plugin.
Go to the frontend. 
Clicked on the accessibility icon.
Clicked Show Settings.
All preferences are disabled.

2021-12-19 13:29 UTC, dgrammatiko commented
@brianteeman @Fedik please undo the removal of the parser line in the eslintrc file, you are excluding vue files. The problem is the outdated eslint itself, it's a couple of major versions behind. There's a PR fixing this properly: https://github.com/joomla/joomla-cms/pull/36295

2021-12-19 15:17 UTC, Fedik commented
@dgrammatiko check that comment https://github.com/vuejs/eslint-plugin-vue/issues/30#issuecomment-311177513

2021-12-19 15:41 UTC, dgrammatiko commented
@Fedik yes you're right, this is one of the changes that we should have done when we moved the code from vue v2 to v3. I already removed the line in the other PR

2021-12-20 13:24 UTC, brianteeman commented
@quy I found the error with the options. The intended behaviour was that the plugin options would set the defaults and then any change you make when the plugin is running will be saved in local storage. In otherwords the plugin options only exist to set the site defaults and then each user is able to set/change their own options. 

My mistake for not checking but there is NO code in the js to use the options that are coming from the plugin

2021-12-20 13:44 UTC, Fedik commented
> My mistake for not checking but there is NO code in the js to use the options that are coming from the plugin

This is the code that use plugin options: https://github.com/joomla/joomla-cms/blob/4c361aa9168de4aad626812bd129e2e67090487a/build/media_source/plg_system_jooa11y/js/jooa11y.es6.js#L11

The plugin options: https://github.com/joomla/joomla-cms/blob/4c361aa9168de4aad626812bd129e2e67090487a/plugins/system/jooa11y/jooa11y.php#L127-L144

2021-12-20 16:42 UTC, brianteeman commented
that's the code where they are called but where is the code that uses these values

2021-12-20 17:01 UTC, Fedik commented
Couple lines down: `new Jooa11y(options);` 

https://github.com/joomla/joomla-cms/blob/4c361aa9168de4aad626812bd129e2e67090487a/build/media_source/plg_system_jooa11y/js/jooa11y.es6.js#L11-L15

2021-12-20 17:04 UTC, Fedik commented
Ah, you mean `// Start up preferences` section,
well, you are right, nowhere, it even not configurable on `Jooa11y` side

2021-12-20 17:24 UTC, brianteeman commented
I would prefer to fix the code

2021-12-20 18:28 UTC, Fedik commented
> I would prefer to fix the code

It not really "a fix", it need to implement ;)

2021-12-20 18:37 UTC, dgrammatiko commented
Should be a 1 liner : https://github.com/joomla-projects/joomla-a11y-checker/blob/9fae16a7ca57c434809d9db634eee568eec0e23b/src/js/jooa11y.js#L184

```js
// from 
const options = customOptions ? Object.assign(defaultOptions, customOptions) : defaultOptions;

// To
const options = {...defaultOptions, ...customOptions};

```

Unless the data coming from the PHP is not in the same format, same keys, etc...

2021-12-20 19:31 UTC, Fedik commented
@dgrammatiko no, that code works fine, there a different issue

2021-12-21 14:41 UTC, angieradtke commented
Hello Together , 
first of all - cool tool. Developers who do not deal with the accessibilty are so pushed on it. 
I have looked at the script and was quite flashed - so much work. I haven't tested everything yet,
 spontaneously I noticed that the contrast of the switcher to the white background #21b5ff (settings) is too low. But this is only a var. I'll keep looking now.

2021-12-21 14:51 UTC, brianteeman commented
@angieradtke This PR is only for the implementation of the new Joomla-Accessibility Checker (jooa11y) in core. Any issue, bug or question about the actual accessibility checks must be made at https://github.com/joomla-projects/joomla-a11y-checker/issues

2021-12-21 15:09 UTC, angieradtke commented
@brianteeman I love your grumbeling.   .-)
I was asked to look and I looked. I think the thing is cool.  But thanks for the advice  anyway. .-)

2021-12-21 15:23 UTC, brianteeman commented
Not grumbling or complaining - just pointing out the correct places to report anything to save you time

2021-12-28 09:08 UTC, nikosdion commented
Cannot build. `npm ci` returns:

```
npm WARN tarball tarball data for joomla-a11y-checker@https://github.com/joomla-projects/joomla-a11y-checker/tarball/joomla (sha512-nyuFDEkkRBcpV7/QQnjup/sPuDr944HFlSpZ8fbPoHgv0pf0HljPKMxX1bw9SxSpoh1KAByYdrFu3RtIaz6X7w==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-nyuFDEkkRBcpV7/QQnjup/sPuDr944HFlSpZ8fbPoHgv0pf0HljPKMxX1bw9SxSpoh1KAByYdrFu3RtIaz6X7w== integrity checksum failed when using sha512: wanted sha512-nyuFDEkkRBcpV7/QQnjup/sPuDr944HFlSpZ8fbPoHgv0pf0HljPKMxX1bw9SxSpoh1KAByYdrFu3RtIaz6X7w== but got sha512-E08QHQBpwkvzSsMweQlO9GmVNkP3dyarJ+bWTXkMDObeqUxAJTZOHZ7o7sQstmWLlJg/Q46OB4Ki76UMaFXzFg==. (3714448 bytes)
```

2021-12-28 09:16 UTC, brianteeman commented
I know and I dont seem able to reliably resolve it. Trying again this morning

2021-12-28 09:26 UTC, brianteeman commented
@nikosdion the change I made last night didnt work. made the same change this morning and it has worked

2021-12-28 10:44 UTC, drmenzelit commented
I have tested this item :white_check_mark: successfully on 6d25a63b699b2cfb17645f7c0357c1e4c014c3da<br /><br />All 3 tests described worked as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36190">issues.joomla.org/tracker/joomla-cms/36190</a>.</sub>

2021-12-28 10:58 UTC, hans2103 commented
I have tested this item :white_check_mark: successfully on 6d25a63b699b2cfb17645f7c0357c1e4c014c3da<br /><br />again... All tests described worked as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36190">issues.joomla.org/tracker/joomla-cms/36190</a>.</sub>

2021-12-29 07:50 UTC, crystalenka commented
I have tested this item :white_check_mark: successfully on 6d25a63b699b2cfb17645f7c0357c1e4c014c3da<br /><br />All three tests passed successfully. I cannot WAIT for this to be implemented. Thank you for all your hard work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36190">issues.joomla.org/tracker/joomla-cms/36190</a>.</sub>

2021-12-29 07:57 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36190">issues.joomla.org/tracker/joomla-cms/36190</a>.</sub>

2021-12-29 09:39 UTC, merged

2021-12-29 09:39 UTC, bembelimen commented
Thx, awesome work!

2021-12-29 09:40 UTC, brianteeman commented
Thank you everyone #we4authors

2021-12-29 10:24 UTC, dgrammatiko commented
Congrats to everyone involved in this one, great stuff.

One little request: can someone with access to the passwords vault do a proper `npm publish` on the other repo?
[I think, might be wrong here as I didn't test it, the versioning part of the build tools need an actual version in the form of Major-Minor-Patch, but regardless publishing it on NPM is a good thing, the wider web community could use the tool]

2021-12-29 10:30 UTC, HLeithner commented
Thanks all for this nice feature!

@dgrammatiko I hope @wilsonge will do this soon.

2021-12-29 10:33 UTC, brianteeman commented
yes it should be published on npm and then installed correctly

2021-12-29 12:17 UTC, richard67 commented
The update SQL scripts use value zero instead of NULL for the checked_out column.

This results in the extension being shown as checked out after an update to the next 4.1 version which will include this change.

The reason might be that the SQL statement has been inspired by one in an older SQL script which came in history before the change of the checked_out column to real NULL values has been made.

For new installations it is not a problem because in that SQL we don't specify that column so the default NULL is used.

As this change here hasn't been released yet and is not even in a nightly build yet, we don't need a new update SQL script for the fix but can safely change the one added by this PR here.

I will make a PR in a few minutes.

2021-12-29 12:24 UTC, richard67 commented
In addition, since we already have beta releases between which we want people to be able to update for testing purpose, it needs to change the name of the update SQL script to a later date so it runs when people update a beta 2 to the next beta 3.

2021-12-29 12:28 UTC, brianteeman commented
> , it needs to change the name of the update SQL script to a later date so it runs when people update a beta 2 to the next beta 3.

really? whenever i have said that the update scripts should be immutable you have always said it doesnt matter as they all get checked

2021-12-29 12:30 UTC, richard67 commented
@brianteeman It has nothing to do with the database checker. It is about the installer only running those update SQL script which have a version in their name which is newer than the schema version saved in database.

2021-12-29 12:30 UTC, richard67 commented
P.S. and your files have a date older than the ones which have been added by other extensions and are already released.

2021-12-29 12:32 UTC, richard67 commented
P.P.S.: Child templates was 4.1.0-2021-11-28.sql, so that will be the schema version in db for a 4.1-beta2.

2021-12-29 12:33 UTC, richard67 commented
P.P.P.S: So scripts 4.1.0-2021-11-26.sql will not be run when updating a beta 2 to a beta 3.

2021-12-29 12:33 UTC, richard67 commented
Clear now?

2021-12-29 12:33 UTC, brianteeman commented
even more proof that the sql located in com_admin must be immutable

2021-12-29 12:35 UTC, richard67 commented
> even more proof that the sql located in com_admin must be immutable

It seems you still do not understand how the updater works and how the db checker works. Anyway, I won't waste anymore time to try to explain it to you again and again. I will fix the issue instead.

2021-12-29 12:37 UTC, richard67 commented
P.S.: This "immutable" discussion has absolutely nothing to do with the issue because as I clearly explained, your scripts haven't been released yet and haven't been evene included in a nightly build yet, so they are definitely not immutable and can and should be changed.

2021-12-29 12:45 UTC, nikosdion commented
@brianteeman The **CONTENT** of the update SQL scripts is immutable. However, this has nothing to do with what @richard67 is telling you.

The **NAMES** of the update SQL files are _versions_. Joomla stores the name of the last update file applies for an extension in the `#__schemas` table. That's the “schema version” for that extensions. When you install update to that extension only update files whose name is a later version than the schema version of the extension will be executed. This is determined by using PHP's [version_compare() function](https://www.php.net/version_compare) with two arguments: the filename (without the path and the `.sql` extension) and the stored schema version. If you read that page you will understand why Joomla's convention of using the next version and a dash followed by the date and time in YYYYMMDDHHmmSS (e.g. 20211229124300) format works.

This is a very important feature in Joomla and the reason why updates actually work in the first place! If this was not the case all SQL update files would execute on every update and we could no longer have immutable update file contents.

Do keep in mind that Joomla does list itself as a `file` type extension exactly so that core update as possible.

The names of the update SQL files you used are an older version than those which have already been installed by current beta releases. As a result, Joomla will skip over them and jooa11y won't appear installed in the database. So, yes, @richard67 is absolutely correct. 

I've had to do the same in some of my PRs when the PR was far removed temporary from the merge time and other SQL updates had already been _published_. In most of my PRs I did not have to do that, even though other updates with later versions were already merged, because there was no _officially published_ version of Joomla which was using these newer version SQL files.

2021-12-29 12:47 UTC, richard67 commented
PR is #36475 (I have to fix the title in a minute). Please test.

2021-12-29 12:48 UTC, brianteeman commented
@nikosdion I understand exactly what Richard is saying. My point (which is kind of off topic) is that I have repeatedly been told that the content of those update scripts is NOT immutable and there are regular pull requests which change the content of those scripts

2021-12-29 12:51 UTC, richard67 commented
The content is not immutable because for example if we had added an index in past and later had removed it, it was not possible to add back that index with the same name, and there is no alter index rename command, what a pity.

So there were cases in past when we HAD TO comment out lines in old update SQL scripts.

I have explained that so often that I am sick of it.

We can agree that it would be good if they were immutable.

But with our current database checker that simply is not possible.

And again, all that has absolutely nothing to do with what I am doing with my PR.

2021-12-29 12:55 UTC, brianteeman commented
this pr should not have been merged without this being changed and hopefully the people who have merge access are more careful to check for this in the future.

Yes the immutable comment is off-topic but important. So it is interesting that @nikosdion says the content is immutable and you say the opposite

2021-12-29 13:00 UTC, richard67 commented
You can find lots of examples in J3 when we had to disable statements in old update SQL scripts:

```
richard@vmubu01:~/lamp/public_html/joomla-cms-3.10-dev/administrator/components/com_admin/sql/updates$ find ./ -type f -name "*\.sql" -exec grep -Hn "\-- The following" {} \;
./sqlazure/3.4.0-2014-09-16.sql:3:-- The following statement has to be disabled because it conflicts with
./sqlazure/3.5.0-2016-03-01.sql:5:-- The following statement had to be modified for 3.6.0 by removing the
./postgresql/3.4.0-2014-09-16.sql:3:-- The following statement has to be disabled because it conflicts with
./postgresql/3.6.3-2016-10-04.sql:4:-- The following statement has to be disabled because it conflicts with
./postgresql/3.7.0-2017-01-09.sql:4:-- The following statement has to be disabled because it conflicts with
./postgresql/3.1.0.sql:4:-- The following statement has to be disabled because it conflicts with
./postgresql/3.1.0.sql:9:-- The following statement has to be disabled because it conflicts with
./postgresql/3.7.0-2017-01-08.sql:5:-- The following statements have to be disabled because they conflict with
./mysql/3.4.0-2014-09-16.sql:3:-- The following statement has to be disabled because it conflicts with
./mysql/3.5.0-2016-03-01.sql:5:-- The following statement had to be modified for 3.6.0 by removing the
./mysql/2.5.0-2011-12-24.sql:4:-- The following statment had to be modified for utf8mb4 in Joomla! 3.5.1, changing
richard@vmubu01:~/lamp/public_html/joomla-cms-3.10-dev/administrator/components/com_admin/sql/updates$
```

2021-12-29 13:02 UTC, richard67 commented
@brianteeman It is interesting that after all those years now in which I have proven that I never have broken any update or other SQL stuff with my activities but only fixed things which others had broken, you still don't trust me and talk with me as if I was somebody who has no idea about all that stuff or who always messes up things.

2021-12-29 13:09 UTC, dgrammatiko commented
@richard67 a simple action could be the answer here. Check if the PR has any new update SQL files and rename them to the current date. Let computers deal with it instead of us fighting over and over (this is the second time we got the dates mismatch in the last 4 weeks)...

2021-12-29 13:11 UTC, brianteeman commented
Richard you are misunderstanding me

2021-12-29 13:12 UTC, richard67 commented
> @richard67 a simple Github action could be the answer here. Check if the PR has any new update SQL files and rename them to the current date. Let computers deal with it instead of us fighting over and over (this is the second time we got the dates mismatch in the last 4 weeks)...

@dgrammatiko Yes, that's a good idea.

2021-12-29 13:16 UTC, nikosdion commented
@richard67 @dgrammatiko I would be all for making that the default workflow on merging PRs.

2021-12-29 13:29 UTC, richard67 commented
@dgrammatiko @nikosdion Sometimes PRs were rebased e.g. from 4.0-dev to 4.1-dev, so it would be good to adjust not only the date but also the version part of the file name. But that should not be a problem.

Version should be taken from target branch of the merge, and date should be the actual date of the merge plus a check if there is already a file with that name and adding a day until no file found, or something like that. Sometimes maintainers are not lazy and merge more than one PR at a day 😄 , and sometimes more than one of these PRs adds an update SQL.

Another thing is that sometimes PRs add more than one because they are new features e.g. from GSoC or other SoC projects and during review nobody has said "Please combine the scripts into one". Maybe that should be handled, too, somehow.

2021-12-29 14:09 UTC, richard67 commented
@dgrammatiko Maybe that will be my next project. Currently I'm working on automation of the deleted files and folders lists updates, and am close to finishing it.

2022-02-13 08:43 UTC, infograf768 commented
There are useless escape characters before single quotes in 3 strings.

```
administrator/language/en-GB/plg_system_jooa11y.ini:63: PLG_SYSTEM_JOOA11Y_PANEL_STATUS_12="The item you are trying to view is not visible; it may be hidden or inside of an accordion or tab component. Here\'s a preview="
administrator/language/en-GB/plg_system_jooa11y.ini:83: PLG_SYSTEM_JOOA11Y_LINK_URL="Longer, less intelligible URLs used as link text might be difficult to listen to with assistive technology. In most cases, it is better to use human-readable text instead of the URL. Short URLs (such as a site\'s homepage) are okay."
administrator/language/en-GB/plg_system_jooa11y.ini:91: PLG_SYSTEM_JOOA11Y_NEW_TAB_WARNING="Link opens in a new tab or window without warning. Doing so can be disorienting, especially for people who have difficulty perceiving visual content. Secondly, it is not always a good practice to control someone\'s experience or make decisions for them. Indicate that the link opens in a new window within the link text."

```

2022-02-14 08:40 UTC, infograf768 commented
PR here

https://github.com/joomla/joomla-cms/pull/37025<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36190">issues.joomla.org/tracker/joomla-cms/36190</a>.</sub>