Remove hard-limit of 20 to the Module Tags
joomla/joomla-cms pull request #36261
Opened 2021-12-08 10:41 UTC by Shubhamverma2796

Pull Request for Issue #36016.

### Summary of Changes

Removed the hard limit for Module Tags-Popular and Module Tags-Similar.

### Testing Instructions
1. Site modules--> New-->Tags-Popular.
2. Set the maximum tags to a number > 20 and make sure that the tags are displayed correctly in the frontend.

### Actual result BEFORE applying this Pull Request
see #36016

### Expected result AFTER applying this Pull Request
Any number is possible.

### Documentation Changes Required

2021-12-08 10:55 UTC, brianteeman commented on modules/mod_tags_popular/mod_tags_popular.xml
> +					min="0"
Why would you ever have 0?

2021-12-08 10:57 UTC, Shubhamverma2796 commented on modules/mod_tags_popular/mod_tags_popular.xml
> +					min="0"
So should i change it to 1?

2021-12-08 11:14 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 9118237f519a59268d5b7d965cbe1d9574f13ef4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-08 11:20 UTC, Ravi-chandra69 commented
I have tested this item :white_check_mark: successfully on 9118237f519a59268d5b7d965cbe1d9574f13ef4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-08 11:30 UTC, ChristineWk commented on modules/mod_tags_popular/mod_tags_popular.xml
> +					min="0"
i saw above code change just now. (not before under pr-issue view). should I revert test result?

2021-12-08 11:58 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 3d9114a2e10e4e679bf528c3b92e887b7be27099<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-08 13:27 UTC, richard67 commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		$maximum     =(int) $params->get('maximum', 5);
```suggestion
		$maximum     = (int) $params->get('maximum', 5);
```
Please fix this code style error. Thanks in advance.

2021-12-08 15:05 UTC, Shubhamverma2796 commented
@richard67 I've made the required changes but still, the build is failing by saying white space found at the end of the line. But 163 is an empty line. Please help me to resolve this issue.

2021-12-08 15:05 UTC, richard67 commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +
Please remove white space from line 163 but keep the empty line.

2021-12-08 15:06 UTC, richard67 commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +
The line is not empty, it contains spaces.

2021-12-08 15:53 UTC, Shubhamverma2796 commented
@ChristineWk @Ravi-chandra69  Finally the build is successful. Could you guys please test it again? Sorry for the repetitive work and thanks in advance.

2021-12-08 16:02 UTC, Ravi-chandra69 commented
I have tested this item :white_check_mark: successfully on 1809e6a049080d7f2327a71d1994359e0d52ce5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-08 16:44 UTC, ChristineWk commented
even after re-fetching data, then applied again with patchtester, got response: 
The patch could not be applied because it conflicts with a previously applied patch: modules/mod_tags_popular/mod_tags_popular.xml
maybe I could try on another test-site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-08 16:51 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 1809e6a049080d7f2327a71d1994359e0d52ce5b<br /><br />on another site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-08 18:40 UTC, HLeithner commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($maximum > 0)
This will always be true since you set a minimum value of 1 in the xml.

2021-12-08 18:41 UTC, HLeithner commented on modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
> +		if ((int) $params->get('maximum', 5) > 0)
please use a variable like in the other module

2021-12-09 06:48 UTC, laoneo commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($maximum > 0)
I would leave it as also extensions do use the tags helper where there can be a different setup.

2021-12-09 07:07 UTC, HLeithner commented on modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
> +		if ($maximum > 0)
what I wanted to say is the he should please set the min attribute in the XML to 0 not to remove this if. Sorry for not being more specific.

2021-12-09 07:37 UTC, Shubhamverma2796 commented on modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
> +		if ((int) $params->get('maximum', 5) > 0)
can you please explain? I am unable to get what you are trying to point out

2021-12-09 07:39 UTC, Shubhamverma2796 commented on modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
> +		if ((int) $params->get('maximum', 5) > 0)
can you please explain? I am unable to get what you are trying to point out

2021-12-10 12:51 UTC, HLeithner commented on modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
> +			$query->setLimit((int) $params->get('maximum'));
```suggestion
		$maximum = (int) $params->get('maximum', 5)
		if ($maximum > 0)
		{
			$query->setLimit($maximum);
```

2021-12-10 12:51 UTC, HLeithner commented on modules/mod_tags_popular/mod_tags_popular.xml
> +					min="1"
```suggestion
					min="0"
```

2021-12-10 13:26 UTC, richard67 commented on modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
> +		if ($maximum > 0)
```suggestion

		if ($maximum > 0)
```
Empty line before "if" to fix code style error.

2021-12-10 14:43 UTC, Ravi-chandra69 commented
I have tested this item :white_check_mark: successfully on 9b31347c809c8921d5be3f5818fa1fa6ba679fdd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-10 17:13 UTC, pabloarias commented
I have tested this item :red_circle: unsuccessfully on 9b31347c809c8921d5be3f5818fa1fa6ba679fdd<br /><br />Hello:

I've tested the path in Joomla 4.0.5-rc4, PHP version 8.0.

When I apply the path, it breaks the entire site: "The requested page can't be found". Here it gives a clue:

call_user_func_array(): Argument #1 ($function) must be a valid callback, class "Joomla\Module\TagsSimilar\Site\Helper\TagsSimilarHelper" not found <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-10 19:20 UTC, chmst commented
@pabloarias I can test the patch without errors. This times I used the patchtester component. 

How did you apply the patch? Could you please set debug-modus on and error-reporting maximum?

2021-12-12 07:34 UTC, N6REJ commented
> I have tested this item 🔴 unsuccessfully on [9b31347](https://github.com/joomla/joomla-cms/commit/9b31347c809c8921d5be3f5818fa1fa6ba679fdd)Hello:
> 
> I've tested the path in Joomla 4.0.5-rc4, PHP version 8.0.
> 
> When I apply the path, it breaks the entire site: "The requested page can't be found". Here it gives a clue:
> 
> call_user_func_array(): Argument #1 ($function) must be a valid callback, class "Joomla\Module\TagsSimilar\Site\Helper\TagsSimilarHelper" not found
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/36261](https://issues.joomla.org/tracker/joomla-cms/36261).

If your going to test with php 8 please make sure its 8.0.13
or newer

2021-12-12 09:07 UTC, infograf768 commented
php 8.0.8 is fine here.

2021-12-12 22:37 UTC, N6REJ commented
> php 8.0.8 is fine here.

thanks jm.. I knew php 8.0.0 had issues but the only other one "I" have is 8.0.13
Glad to see you again.  Merry Christmas

2021-12-13 04:59 UTC, pabloarias commented
Oops, I tested it with PHP version 8.0.7.

I used Path Tester too to apply the path.

2021-12-13 05:29 UTC, N6REJ commented
> Oops, I tested it with PHP version 8.0.7.
> 
> I used Path Tester too to apply the path.

do you actually have 21 or more tags?

2021-12-13 05:31 UTC, pabloarias commented
Yes. I installed blog example content and created more than 21 tags to test this path.

2021-12-13 06:39 UTC, N6REJ commented
I have tested this item :red_circle: unsuccessfully on 9b31347c809c8921d5be3f5818fa1fa6ba679fdd<br /><br />failed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2021-12-13 07:09 UTC, richard67 commented
@N6REJ The left and right values in your insert statements are all the same. Maybe this causes the problems in your tests? The tags table is a nested set table where the lft and rgt values form a hierarchical tree, like in categories or menus or assets tables.

2021-12-22 13:51 UTC, Shubhamverma2796 commented
@richard67  I am not unable to find the reason why the patch is failing for some people. Please help.

2021-12-22 13:53 UTC, richard67 commented
> @richard67 I am not unable to find the reason why the patch is failing for some people. Please help.

@Shubhamverma2796 "not unable"? I guess you mean either "not able" or "unable".

I don't think I can help much here.

2021-12-22 14:28 UTC, Shubhamverma2796 commented
> > @richard67 I am not unable to find the reason why the patch is failing for some people. Please help.
> 
> @Shubhamverma2796 "not unable"? I guess you mean either "not able" or "unable".
> 
> I don't think I can help much here.

it was a typing mistake. I will try to find the solution.

2022-01-04 05:59 UTC, ditsuke requested changes

2022-01-04 05:59 UTC, ditsuke commented on modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
> +		$maximum = (int) $params->get('maximum', 5)
```suggestion
		$maximum = (int) $params->get('maximum', 5);
```

This should fix the failing tests

2022-01-04 06:18 UTC, ditsuke commented
I have tested this item :white_check_mark: successfully on f9516bbac4b993d210386fd1e262ef8888bddc65<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2022-01-04 06:37 UTC, Shubhamverma2796 commented
@pabloarias Can you please test it again? Thanks in advance.

2022-01-14 19:43 UTC, pabloarias commented
Hello:

I've updated PHP to version 8.0.10. It was not easy inside Devilbox but... trying to install the path with Path Tester 4.1.0 I obtain this message:

The patch could not be applied because the repository is missing.

Do you know why?

Thank you and best regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36261">issues.joomla.org/tracker/joomla-cms/36261</a>.</sub>

2022-01-14 19:48 UTC, richard67 commented
> The patch could not be applied because the repository is missing.
> 
> Do you know why?

It seems @Shubhamverma2796 has deleted his fork or his branch.

2022-01-14 20:13 UTC, Shubhamverma2796 commented
Sorry for the inconvenience everyone. I am closing this pr and I will make a new pr. I deleted the branch by mistake.

2022-01-15 19:11 UTC, ditsuke commented
> Sorry for the inconvenience everyone. I am closing this pr and I will make a new pr. I deleted the branch by mistake.

@Shubhamverma2796 you can recover your branch and let this PR stay

2022-01-18 13:47 UTC, Shubhamverma2796 commented
please test #36732. I'm closing this pr.

2022-01-18 13:47 UTC, closed without merging