Issiu #36166
joomla/joomla-cms pull request #36269
Opened 2021-12-08 20:34 UTC by LukasHH

Pull Request for Issue # .

### Summary of Changes
**Changes to the content plugin emailcloak.php**
- Changes in the respective $replacement specifications
- A change in the last pattern-string

**Changes to the file joomla-hidden-mail.js under media/system/js**
Reason: When setting the tag "joomla-hidden-mail" the class and style attributes are duplicated. Therefore I have them both removed from the tag.

**A change to the core.js file**
Here is the function sanitizeHtml. This had prevented that style specifications are not taken over with images. The attribute "style" was added to the allow list.

### Testing Instructions
Include any of the following content with an email in an article. Examples are also in the source code of the "emailcloak" plugin
```
<p><a href="http://mce_host/ourdirectory/email@example.org" class="btn btn-danger" style="border: 2px solid #f00;">email@example.org</a></p>
<p><a href="http://mce_host/ourdirectory/email@example.org" class="btn btn-danger" style="border: 2px solid #f00;">anytext</a></p>
<p><a href="mailto:email@example.org" class="btn btn-danger" style="border: 2px solid #f00;">email@example.org</a></p>
<p><a href="mailto:email@example.org" class="btn btn-danger" style="border: 2px solid #f00;"><span class="test" style="text-transform: uppercase;">email@example.org</span></a></p>
<p><a href="mailto:email@example.org" class="btn btn-danger" style="border: 2px solid #f00;"><span class="test" style="text-transform: uppercase;">anytext</span></a></p>
<p><a href="mailto:email@example.org" class="btn btn-danger" style="border: 2px solid #f00;">anytext</a></p>
<p><a href="mailto:email@example.org" class="btn btn-danger" style="border: 2px solid #f00;"><img src="images/joomla_black.png" alt="" class="img-thumbnail" style="border: 1px solid #00f;" /></a></p>
<p><a href="mailto:email@example.org" class="btn btn-danger" style="border: 2px solid #f00;"><img src="images/joomla_black.png" alt="" class="img-thumbnail" style="border: 1px solid #00f;" />email@example.org</a></p>
<p><a href="mailto:email@example.org" class="btn btn-danger" style="border: 2px solid #f00;"><img src="images/joomla_black.png" alt="" class="img-thumbnail" style="border: 1px solid #00f;" />any text</a></p>
<p><a href="mailto:email@example.org?subject=Text" class="btn btn-danger" style="border: 2px solid #f00;">email@example.org</a></p>
<p><a href="mailto:email@example.org?subject=Text" class="btn btn-danger" style="border: 2px solid #f00;">anytext</a></p>
<p><a href="mailto:email@example.org?subject= Text" class="btn btn-danger" style="border: 2px solid #f00;"><span class="test" style="text-transform: uppercase;">email@example.org</span></a></p>
<p><a href="mailto:email@example.org?subject= Text" class="btn btn-danger" style="border: 2px solid #f00;"><span class="test" style="text-transform: uppercase;">anytext</span></a></p>
<p><a href="mailto:email@example.org?subject=Text" class="btn btn-danger" style="border: 2px solid #f00;"><img src="images/joomla_black.png" alt="" class="img-thumbnail" style="border: 1px solid #00f;" /></a></p>
<p><a href="mailto:email@example.org?subject=Text" class="btn btn-danger" style="border: 2px solid #f00;"><img src="images/joomla_black.png" alt="" class="img-thumbnail" style="border: 1px solid #00f;" />email@example.org</a></p>
<p><a href="mailto:email@example.org?subject=Text" class="btn btn-danger" style="border: 2px solid #f00;"><img src="images/joomla_black.png" alt="" class="img-thumbnail" style="border: 1px solid #00f;" />any text</a></p>
<p><img src="images/joomla_black.png" alt="" class="img-thumbnail" style="border: 1px solid #00f;" title="email@example.org" /></p>
<p><input type="text" placeholder="email@example.org" /></p>
```

### Actual result BEFORE applying this Pull Request
![image](https://user-images.githubusercontent.com/31522294/145278486-6047b28f-1690-4e83-8eb4-ea84cfe79092.png)
![image](https://user-images.githubusercontent.com/31522294/145278585-bee2df37-f414-4091-8755-ee856cafc1fb.png)
![image](https://user-images.githubusercontent.com/31522294/145278690-82fe50c6-ece3-4159-9e1e-759d01481ff2.png)

### Expected result AFTER applying this Pull Request
![image](https://user-images.githubusercontent.com/31522294/145278878-ab4cf10a-5cab-476e-a072-7e7b02d3be9e.png)
![image](https://user-images.githubusercontent.com/31522294/145278989-81ac8ce0-2e6b-47df-a0ea-7216db4d2ecb.png)
![image](https://user-images.githubusercontent.com/31522294/145279084-c72a64ef-5560-48f6-97dd-7366882a28e2.png)
![image](https://user-images.githubusercontent.com/31522294/145279167-e69d2ea3-6ebd-421b-a4c7-205de59b8a9a.png)

### Documentation Changes Required
no changes

2021-12-08 21:16 UTC, richard67 commented on plugins/content/emailcloak/emailcloak.php
> +		$pattern = '~<[^<]*(?<!\/)>(*SKIP)(*F)|(<\w.*\"'.$searchEmail.'\".*\/\>)~i';
```suggestion
		$pattern = '~<[^<]*(?<!\/)>(*SKIP)(*F)|(<\w.*\"' . $searchEmail . '\".*\/\>)~i';
```
Please fix code style error. Thanks in advance.

2021-12-08 21:19 UTC, dgrammatiko requested changes

2021-12-08 21:19 UTC, dgrammatiko commented on build/media_source/system/js/core.es6.js
> +  '*': ['class', 'dir', 'id', 'lang', 'role','style', ARIA_ATTRIBUTE_PATTERN, DATA_ATTRIBUTE_PATTERN],
Please don't add styles to the allowed list because it shouldn't be allowed as it is a possible attack vector.

2021-12-08 22:33 UTC, LukasHH commented on build/media_source/system/js/core.es6.js
> +  '*': ['class', 'dir', 'id', 'lang', 'role','style', ARIA_ATTRIBUTE_PATTERN, DATA_ATTRIBUTE_PATTERN],
OK - should style specifications generally not be allowed in img-tags?

2021-12-08 22:37 UTC, dgrammatiko commented on build/media_source/system/js/core.es6.js
> +  '*': ['class', 'dir', 'id', 'lang', 'role','style', ARIA_ATTRIBUTE_PATTERN, DATA_ATTRIBUTE_PATTERN],
> OK - should style specifications generally not be allowed in img-tags?

No, the thing is that these styles are been injected with JS and thus there are exploits, it's specific to the current use case. What you can do is at line 51 od the js script instead of `Joomla.sanitizeHtml(innerStr);` you can pass the tag and allow the style there, eg: `Joomla.sanitizeHtml(innerStr, {img: ['style', /*more things...*/ ]);`

2021-12-08 22:38 UTC, dgrammatiko commented on build/media_source/system/js/core.es6.js
> +  '*': ['class', 'dir', 'id', 'lang', 'role','style', ARIA_ATTRIBUTE_PATTERN, DATA_ATTRIBUTE_PATTERN],
Anyhow consult the Security Team for this one

2021-12-08 22:39 UTC, LukasHH commented on plugins/content/emailcloak/emailcloak.php
> +		$pattern = '~<[^<]*(?<!\/)>(*SKIP)(*F)|(<\w.*\"'.$searchEmail.'\".*\/\>)~i';
i have fix the code style error. Thanks

2021-12-08 22:49 UTC, LukasHH commented on build/media_source/system/js/core.es6.js
> +  '*': ['class', 'dir', 'id', 'lang', 'role','style', ARIA_ATTRIBUTE_PATTERN, DATA_ATTRIBUTE_PATTERN],
I think that this can be neglected. The style changes can also be made on the basis of classes.

2021-12-09 08:49 UTC, SniperSister commented on build/media_source/system/js/core.es6.js
> +  '*': ['class', 'dir', 'id', 'lang', 'role','style', ARIA_ATTRIBUTE_PATTERN, DATA_ATTRIBUTE_PATTERN],
> Anyhow consult the Security Team for this one

No objections from my side, however I agree with:

> I think that this can be neglected. The style changes can also be made on the basis of classes.

2021-12-09 08:55 UTC, richard67 commented on build/media_source/system/js/core.es6.js
> +  '*': ['class', 'dir', 'id', 'lang', 'role','style', ARIA_ATTRIBUTE_PATTERN, DATA_ATTRIBUTE_PATTERN],
As far as I can see this has been fixed with commit https://github.com/joomla/joomla-cms/pull/36269/commits/d8e4e77c75ee2fc410301b3e155f3d335a7b5f15 , so I mark this review conversation as resolved.

2021-12-09 09:03 UTC, HLeithner commented on plugins/content/emailcloak/emailcloak.php
> +			$replacement = HTMLHelper::_('email.cloak', $mail, $mode, $mailText, 1, $regs[1][0], $regs[4][0]);
please use meaning full variables names for like `$mailText` above.

2021-12-09 09:37 UTC, LukasHH commented on plugins/content/emailcloak/emailcloak.php
> +			$replacement = HTMLHelper::_('email.cloak', $mail, $mode, $mailText, 1, $regs[1][0], $regs[4][0]);
Hello Harald,
do you mean implement in this form?

```
$mail = $regs[3][0];
$mailText = $regs[5][0];
$attribsBefore = $regs[1][0];
$attribsAfter = $regs[4][0];

// Check to see if mail text is different from mail addy
$replacement = HTMLHelper::_('email.cloak', $mail, $mode, $mailText,1,$attribsBefore, $attribsAfter);
```

2021-12-09 22:30 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 152b089b2429880165e5fc2914d9bdaefd8e17b8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36269">issues.joomla.org/tracker/joomla-cms/36269</a>.</sub>

2021-12-10 11:45 UTC, ChristineWk commented
@LukasHH 
thanks for your examples.backend: OK.
wanted to test for frontend with prebuilt package. unfortunately can't reach github view (404) for installing prebuilt-package.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36269">issues.joomla.org/tracker/joomla-cms/36269</a>.</sub>

2021-12-10 11:55 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 152b089b2429880165e5fc2914d9bdaefd8e17b8<br /><br />OK, with automatic e-mail, I got now the prebuilt package via github.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36269">issues.joomla.org/tracker/joomla-cms/36269</a>.</sub>

2021-12-10 11:57 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36269">issues.joomla.org/tracker/joomla-cms/36269</a>.</sub>

2021-12-10 12:33 UTC, nikzolahr commented
Works for me! Great work, thanks! 😊

2021-12-14 12:08 UTC, khu5h1 commented
I have tested this item :white_check_mark: successfully on 152b089b2429880165e5fc2914d9bdaefd8e17b8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36269">issues.joomla.org/tracker/joomla-cms/36269</a>.</sub>

2022-03-17 19:27 UTC, bembelimen commented
For me this solves a lot of problems but the first example is broken. It should NOT display the email address at all, even though there is a link around. The email address has to be "cloaked" there too (without a mailto link)

2022-06-27 13:06 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2022-10-21 16:16 UTC, bembelimen commented
@LukasHH would you mind looking into this PR and fix the last issue?

2022-10-23 17:44 UTC, LukasHH commented
@bembelimen I will see that I can fix the last problem.

2022-11-26 22:52 UTC, richard67 commented
@chmst @ChristineWk @khu5h1 Could you test again? The PR has received some change due to a review comment. Thanks in advance.

2022-11-27 12:44 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 35f0e39c699cecc34ac6a641a28783046322f167<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36269">issues.joomla.org/tracker/joomla-cms/36269</a>.</sub>

2022-11-27 17:56 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 35f0e39c699cecc34ac6a641a28783046322f167<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36269">issues.joomla.org/tracker/joomla-cms/36269</a>.</sub>

2022-11-27 18:00 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36269">issues.joomla.org/tracker/joomla-cms/36269</a>.</sub>

2022-11-29 21:39 UTC, merged

2022-11-29 21:40 UTC, fancyFranci commented
Thank you  very much @LukasHH !