[4.1] Unification of the language com_scheduler, part 3
joomla/joomla-cms pull request #36297
Opened 2021-12-12 14:50 UTC by tecpromotion

### Summary of Changes

During the translation into German and testing, an error occurred in the display of the duration time.

This PR shows the correct output.

### Testing Instructions

create a new taks an click Run Test.

### Actual result BEFORE applying this Pull Request

![2021-12-12_15-46-24](https://user-images.githubusercontent.com/1752513/145717163-f968eaf5-15d4-447f-b221-f768eade6c46.jpg)

### Expected result AFTER applying this Pull Request

![2021-12-12_15-46-53](https://user-images.githubusercontent.com/1752513/145717169-947a5b5d-a83f-42c9-9233-784977228f19.jpg)

### Documentation Changes Required

.

2021-12-12 14:51 UTC, brianteeman commented
ouch - I made that change and none of the testers spotted it

2021-12-12 14:53 UTC, tecpromotion commented
> ouch - I made that change and none of the testers spotted it

yes, unfortunately i didn't test that enough with my team when beta1 was released. but we should test it thoroughly again before the stable release.

2021-12-13 13:19 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 8474a84ccf820579dbb3f20014758fdaf0278a8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36297">issues.joomla.org/tracker/joomla-cms/36297</a>.</sub>

2021-12-13 13:20 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36297">issues.joomla.org/tracker/joomla-cms/36297</a>.</sub>

2021-12-13 13:26 UTC, alikon requested changes

2021-12-13 13:26 UTC, alikon commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_TEST_RUN_DURATION="Duration: %s seconds"
it seems wrong to me `%s`  it should be `%d` - Signed decimal number (negative, zero or positive) we are talking of seconds

2021-12-13 13:45 UTC, wojsmol commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_TEST_RUN_DURATION="Duration: %s seconds"
@alikon Please see screenshots in PR description.

2021-12-14 12:03 UTC, khu5h1 commented
I have tested this item :white_check_mark: successfully on 8474a84ccf820579dbb3f20014758fdaf0278a8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36297">issues.joomla.org/tracker/joomla-cms/36297</a>.</sub>

2021-12-16 09:59 UTC, bembelimen commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_TEST_RUN_DURATION="Duration: %s seconds"
Probably it should be ```%f```?

2021-12-22 13:33 UTC, Shubhamverma2796 commented
I have tested this item :white_check_mark: successfully on 8474a84ccf820579dbb3f20014758fdaf0278a8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36297">issues.joomla.org/tracker/joomla-cms/36297</a>.</sub>

2021-12-22 13:44 UTC, wojsmol commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_TEST_RUN_DURATION="Duration: %s seconds"
@bembelimen `%f` should be ok.

2021-12-22 13:46 UTC, wojsmol commented
@tecpromotion Please use `%f` instead.

2021-12-30 09:23 UTC, richard67 commented
@tecpromotion Could you have a look on the review suggestions and check if "%f" works, and if so, change to that? I'd like to come forward here, but I'm a bit reluctant to set RTC as long as there are open review discussions.

2021-12-30 10:26 UTC, tecpromotion commented
> @tecpromotion Could you have a look on the review suggestions and check if "%f" works, and if so, change to that? I'd like to come forward here, but I'm a bit reluctant to set RTC as long as there are open review discussions.

I can check this later.

2021-12-30 17:49 UTC, tecpromotion commented
> @tecpromotion Please use `%f` instead.

@wojsmol Sorry but '%f' does not work here.

https://github.com/joomla/joomla-cms/blob/b76ec5536e2719fa46d89a4c4363c9b185d9fd39/build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js#L60
Here a '%s' is searched for and replaced.

2021-12-30 19:07 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36297">issues.joomla.org/tracker/joomla-cms/36297</a>.</sub>

2021-12-31 12:55 UTC, merged

2021-12-31 12:55 UTC, bembelimen commented
Thx

2021-12-31 16:43 UTC, alikon commented
merged ? !!!!
why ? :face_with_head_bandage: 
evidently feedback from some are not welcomed

2021-12-31 16:48 UTC, richard67 commented
@alikon Why ignored? @tecpromotion has checked with "%s" as requested and has reported back why we can't do that with the js as it is now.

2021-12-31 16:52 UTC, alikon commented
this doesn't prove it's correct

2022-01-05 13:27 UTC, tecpromotion commented
> this doesn't prove it's correct

You're absolutely right, but that doesn't solve the problem.
A developer has to sit down and fix it everywhere.
Now there is an output and no more error.