s/$presetButtonClases/$presetButtonClasses
joomla/joomla-cms pull request #36336
Opened 2021-12-17 15:41 UTC by PhilETaylor

code review 

s/$presetButtonClases/$presetButtonClasses

2021-12-17 15:42 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 2a8f7eeca01cbc3227f24d70917844f98a229175<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36336">issues.joomla.org/tracker/joomla-cms/36336</a>.</sub>

2021-12-17 15:47 UTC, alikon requested changes

2021-12-17 15:47 UTC, alikon commented on layouts/plugins/editors/tinymce/field/tinymcebuilder.php
> +						$presetButtonClasses = array(
shouldn't this become `[]` instead of `array()`

2021-12-17 15:48 UTC, PhilETaylor commented on layouts/plugins/editors/tinymce/field/tinymcebuilder.php
> +						$presetButtonClasses = array(
Correct.

2021-12-17 15:48 UTC, PhilETaylor commented on layouts/plugins/editors/tinymce/field/tinymcebuilder.php
> +						$presetButtonClasses = array(
The joy of creating PRs in iOS Github App :-(

2021-12-17 16:17 UTC, alikon approved these changes

2021-12-17 16:18 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 196f4ecc0dac4a4f02e8d365efeb25d9ae1d1538<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36336">issues.joomla.org/tracker/joomla-cms/36336</a>.</sub>

2021-12-17 16:24 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36336">issues.joomla.org/tracker/joomla-cms/36336</a>.</sub>

2021-12-18 14:05 UTC, merged

2021-12-18 14:06 UTC, bembelimen commented
Thx