[4.0] PHP 8.1 deprecation notices administrator/components
joomla/joomla-cms pull request #36360
Opened 2021-12-20 16:08 UTC by frostmakk

Pull Request for Issue # .

### Summary of Changes
Patching PHP 8.1 deprecation notices where null is provided instead of 'something'.

### Testing Instructions
Code review or checking logs.

### Actual result BEFORE applying this Pull Request
Deprecation notices

### Expected result AFTER applying this Pull Request
No deprecation notices from these files.

### Documentation Changes Required
Probably not.

2021-12-22 18:11 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 9137ca6c1bbf42ccab78789f4da71c06e76e69bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36360">issues.joomla.org/tracker/joomla-cms/36360</a>.</sub>

2021-12-22 21:26 UTC, HLeithner requested changes

2021-12-22 21:26 UTC, HLeithner commented on administrator/components/com_mails/src/Model/TemplateModel.php
> +		if ($params->get('attachment_folder') === null)
I would expect that `$params` is a `JRegistry` and the `get` method expects a "default" parameter.

2021-12-22 21:26 UTC, HLeithner commented on administrator/components/com_menus/tmpl/items/default_batch_body.php
> +	<?php if (strlen($menuType ?? '') && $menuType != '*') : ?>
`getUserState` accepts a second parameter for the default value

2021-12-22 21:26 UTC, HLeithner commented on administrator/components/com_menus/tmpl/items/default_batch_footer.php
> +<?php if ((strlen($menuType ?? '') && $menuType != '*' && $clientId == 0) || ($published > 0 && $clientId == 1)): ?>
same here add a second parameter to the `getUserState` call

2021-12-22 22:41 UTC, frostmakk commented on administrator/components/com_mails/src/Model/TemplateModel.php
> +		if ($params->get('attachment_folder') === null)
Since the if statement is negated, wouldn't that resolve to false and the program going in the wrong direction?

2021-12-23 08:55 UTC, HLeithner commented on administrator/components/com_mails/src/Model/TemplateModel.php
> +		if ($params->get('attachment_folder') === null)
sure

2021-12-23 08:56 UTC, HLeithner commented on administrator/components/com_mails/src/Model/TemplateModel.php
> +		if ($params->get('attachment_folder') === null)
it's even simpler 
```suggestion
		if (!trim($params->get('attachment_folder', ''))
```
and remove the else block please

2021-12-23 15:22 UTC, frostmakk commented on administrator/components/com_mails/src/Model/TemplateModel.php
> +		if ($params->get('attachment_folder') === null)
I don't get it. Isn't this originally a null trap? 
If the attachment_folder params does not exist it result in a negated false, and the form field is removed.
If we put in a default value, would this not resolve to false, and the form field not being removed?
Or have I stared myselves blind?

2021-12-28 17:51 UTC, merged

2021-12-28 17:51 UTC, wilsonge commented
Thanks!