Ensure returned getAuthorisedViewLevels array has only unique values
joomla/joomla-cms pull request #36432
Opened 2021-12-27 12:02 UTC by aDaneInSpain

I stumbled over this on a site I was debugging. The system sends the following query:

```
SELECT `folder` AS `type`,`element` AS `name`,`params` AS `params`,`extension_id` AS `id`

  FROM #__extensions

  WHERE enabled = 1 
  AND type = 'plugin' 
  AND state IN (0,1) 
  AND access IN (1,1,5)

  ORDER BY ordering
```

Notice the ```AND access IN (1,1,5)``` the extra 1 comes from the fact that this method hardcodes the 1 on line 1027 and then later also finds in the database. This does not really break anything but is just proper data management. For instance if someone wanted to could how many groups have access to something and used this method and counted the entries would get the answer 3 and not 2. It also leads to "wasted" time with developers who are curious where this comes from and spends time hunting down the source.

Pull Request for Issue # .

### Summary of Changes

### Testing Instructions

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Documentation Changes Required

2021-12-29 20:11 UTC, dgrammatiko requested changes

2021-12-29 20:11 UTC, dgrammatiko commented on libraries/src/Access/Access.php
> +
Can you combine these 2 line into one? Like `return array_unique($authorised);`

Same couple lines above

2021-12-30 09:33 UTC, aDaneInSpain commented on libraries/src/Access/Access.php
> +
Sure. I was not a 100% sure if the coding standards prohibited modifying a variable on the return line as some coding standards goes against this.

2021-12-30 22:59 UTC, wilsonge approved these changes
Makes sense to me

2022-01-10 23:39 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 474b76c809c02bccbdc81627db3cabdc6af8d468<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36432">issues.joomla.org/tracker/joomla-cms/36432</a>.</sub>

2022-01-11 11:39 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 474b76c809c02bccbdc81627db3cabdc6af8d468<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36432">issues.joomla.org/tracker/joomla-cms/36432</a>.</sub>

2022-01-11 12:55 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36432">issues.joomla.org/tracker/joomla-cms/36432</a>.</sub>

2022-01-21 13:01 UTC, merged

2022-01-21 13:02 UTC, bembelimen commented
Thx