[4][com_finder] - php 8.1 serializable-deprecated
joomla/joomla-cms pull request #36482
Opened 2021-12-29 16:17 UTC by PhilETaylor

replacement of https://github.com/joomla/joomla-cms/pull/36473 with Unit tests that run before and after with success (although correctly, before this PR the unit test has the deprecation warning.

@richard67 @alikon 

### Summary of Changes

added magic method

### Testing Instructions

php 8.1
on frontend do a search
check the log

### Actual result BEFORE applying this Pull Request

PHP Deprecated: The Serializable interface is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

### Expected result AFTER applying this Pull Request

no more deprecation

2021-12-29 16:21 UTC, PhilETaylor commented
Strange but probably @HLeithner was doing, the Drone PHP 8.1 unit tests are being run by PHP 8.0 at the moment... 

However, this new Unit test passes :) 
<img width="1175" alt="Screenshot 2021-12-29 at 16 20 30" src="https://user-images.githubusercontent.com/400092/147682667-26f40dab-76d7-4a8e-94fe-6cd86bf4018e.png">

2021-12-29 16:30 UTC, PhilETaylor commented
Drone failure unrelated to PR content.

2021-12-30 09:44 UTC, alikon requested changes

2021-12-30 09:44 UTC, alikon commented on administrator/components/com_finder/src/Indexer/Result.php
> +	 * Magic method used for serializing.
sorry to be pedantic...
but shouldn't need to be added `@return`

2021-12-30 09:44 UTC, alikon commented on administrator/components/com_finder/src/Indexer/Result.php
> +	 * Magic method used for unserializing.
but shouldn't need to be added `@return`  & `@param`

2021-12-30 09:48 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 50e03bd378cfc6c9ad034956238658ce83d3a961<br /><br />on php 7.4 and php 8.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36482">issues.joomla.org/tracker/joomla-cms/36482</a>.</sub>

2021-12-30 10:02 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Result.php
> +	 * Magic method used for unserializing.
Joomla coding standards- all methods to be documented regardless

2021-12-30 13:38 UTC, HLeithner commented
Can you make an update to the branch to retrigger drone (emojis in the description... I think I have to check drone why this happens maybe mb4 on mysql)

2021-12-30 13:40 UTC, PhilETaylor commented
wow - welcome to 2022 where emoji's still break things.

2021-12-30 14:12 UTC, PhilETaylor commented
Drone seems to have flagged this PR as passed now, even though some of the suites fail for unrelated reasons.

2021-12-30 14:13 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Result.php
> +	 * Magic method used for unserializing.
And to be honest, in a PHP 8+ world, I agree with you! All my static cleanup tools now will remove docblock type hints if the type hint is in the PHP code as a typehinted param, or type hinted return type. But, Joomla is still a decade behind everyone else when it comes to this stuff.

2021-12-30 15:04 UTC, HLeithner commented
> Drone seems to have flagged this PR as passed now, even though some of the suites fail for unrelated reasons.

That's ok, all php8+ system tests are allowed to fail and 8.1 unit tests too, also postgres system tests

2021-12-30 22:04 UTC, wilsonge commented on administrator/components/com_finder/src/Indexer/Result.php
> +		foreach ($properties as $k => $v)
$properties isn't a key value array. Something's not right here

2021-12-30 22:07 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Result.php
> +		foreach ($properties as $k => $v)
Not my code - I just moved it

2021-12-30 22:10 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Result.php
> +		foreach ($properties as $k => $v)
hmm  maybe I did... checking

2021-12-30 22:17 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Result.php
> +		foreach ($properties as $k => $v)
No this code is correct and works (should not have doubted myself, the unit test proves it) 

The $k is the index 0,1,2,3,4,5,6... etc 
The $v is the property name as a string
The $serialized array is INDEXed and not a k=>v array

Therefore it "magically" correctly matches the correct key with the correct property  :)

2021-12-30 23:01 UTC, wilsonge commented on administrator/components/com_finder/src/Indexer/Result.php
> +		foreach ($properties as $k => $v)
Ahh yeah i did wonder how the test worked. That makes sense to me

2021-12-30 23:09 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Result.php
> +		foreach ($properties as $k => $v)
I have added a note with 10f7fe1 - basically as long as you serialise in the same order as you deserialise then it works...

2021-12-30 23:14 UTC, wilsonge approved these changes

2022-01-08 19:42 UTC, wilsonge commented on tests/Unit/CMS/administrator/components/com_finder/src/Indexer/ResultTest.php
> +namespace Joomla\Component\Finder\Administrator\Indexer;
I don't see how this is every being namespace autoloaded when the code is in this directory? Feels very wrong somehow. Are we sure this test is actually being run?

2022-01-08 19:44 UTC, PhilETaylor commented on tests/Unit/CMS/administrator/components/com_finder/src/Indexer/ResultTest.php
> +namespace Joomla\Component\Finder\Administrator\Indexer;
Does phpunit use namespace loading? I think it just iterates all folders looking for *Test.php 

feel free to update the namespace if you think its wrong. Im knee deep in another project right now.

2022-01-09 15:34 UTC, PhilETaylor commented on tests/Unit/CMS/administrator/components/com_finder/src/Indexer/ResultTest.php
> +namespace Joomla\Component\Finder\Administrator\Indexer;
So I have looked into this.

PHPUnit is not loading the class using autoloading, its, as I guessed, just scanning for the *Test.php named files. 

The namespace can be literally anything and the test will still load and run as evidenced by running in debug mode you can see the test in yellow here. 

<img width="1260" alt="Screenshot 2022-01-09 at 15 30 42" src="https://user-images.githubusercontent.com/400092/148689146-3ede5f81-ba24-4e46-9342-e423235cc9ec.png">

I have changed the namespace anyway to be 

`namespace Joomla\Tests\Unit\Administrator\Components\Finder\Indexer;`

and I have imported the Result class (as its no longer in the same namespace) and the tests still pass

<img width="1609" alt="Screenshot 2022-01-09 at 15 30 13" src="https://user-images.githubusercontent.com/400092/148689181-2e73e94d-c9a4-48b6-ba51-a7b644a8f425.png">

I'll merge these changes and push to the PR now.

2022-03-07 18:34 UTC, closed without merging