Improved media view by adding position:sticky in .media-toolbar
joomla/joomla-cms pull request #36658
Opened 2022-01-12 15:42 UTC by Shubhamverma2796

Pull Request for Issue #36545

### Summary of Changes
Improved media view by adding position:sticky in .media-toolbar and in .media-drive. Also added the z-index so that the elements does not overlap. 

### Testing Instructions

Go to media--> Upload more than 20(or any big number) images. After uploading, scroll down, in case of the long list of media files the search and change folder options are not visible on scrolling down. we need may scroll up down for many action :

- change folder
- search
- change view

See #36545 

### Actual result BEFORE applying this Pull Request

![Screenshot (322)](https://user-images.githubusercontent.com/54266411/149171941-f250812b-a1d5-4cf1-96b7-0ad197890eb3.png)

### Expected result AFTER applying this Pull Request
![Screenshot (323)](https://user-images.githubusercontent.com/54266411/149172464-6c087351-95dc-4334-b29e-185ce53f8280.png)

Search and folder structure visible on scrolling down also so there is no need to scroll up.

### Documentation Changes Required

2022-01-12 16:52 UTC, pritam825 commented
I have tested this item :white_check_mark: successfully on f0cb7e0ea227ef9ee1c7754f036d6e460b4aa4cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36658">issues.joomla.org/tracker/joomla-cms/36658</a>.</sub>

2022-01-12 17:16 UTC, Ravi-chandra69 commented
I have tested this item :white_check_mark: successfully on f0cb7e0ea227ef9ee1c7754f036d6e460b4aa4cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36658">issues.joomla.org/tracker/joomla-cms/36658</a>.</sub>

2022-01-12 17:28 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on f0cb7e0ea227ef9ee1c7754f036d6e460b4aa4cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36658">issues.joomla.org/tracker/joomla-cms/36658</a>.</sub>

2022-01-12 17:32 UTC, Shubhamverma2796 commented
@brianteeman why unsuccessful?

2022-01-12 17:37 UTC, brianteeman commented
The position fixed is on the wrong element. As a result if you have more than one filesystem set up they are both displayed on top of each other.

Also your screenshot shows the title being with the tree. But thats not what is happening because the title is not fixed.

And the media-disk shouldnt be left floating and should be at the etop when scrolled

![image](https://user-images.githubusercontent.com/1296369/149192637-088383d8-d52e-4c8f-bb3e-132bd4480ab5.png)

Probably you should change the fixed from the media-drive class to the media-disk or media-sidebar (not tested)

2022-01-12 18:23 UTC, micker commented
@Shubhamverma2796 same as @brianteeman 
maybe for left we need to add a js for a topfixed class ?

2022-01-12 18:28 UTC, brianteeman commented
sorry no idea

2022-01-12 18:50 UTC, Shubhamverma2796 commented
@micker  I'm not sure about js but adding sticky to media-disk or media-sidebar is not working, the element still keeps floating. Let me know if you have any solution

2022-01-12 19:02 UTC, micker commented
As i Say i think the solution IS a script like topfixed toolbar in admin but i dont know how .. i will search

2022-01-12 20:01 UTC, dgrammatiko requested changes

2022-01-12 20:01 UTC, dgrammatiko commented on build/media_source/com_media/scss/components/_media-toolbar.scss
> +  top: 67px;
Hardcoded values don't really work...

2022-01-12 20:11 UTC, Shubhamverma2796 commented on build/media_source/com_media/scss/components/_media-toolbar.scss
> +  top: 67px;
What am I supposed to do then?

2022-01-12 20:14 UTC, dgrammatiko commented on build/media_source/com_media/scss/components/_media-toolbar.scss
> +  top: 67px;
Probably this value needs to be set in the js because the toolbar above this element that you are hard coding here could be less or more than 67px

2022-01-12 20:14 UTC, dgrammatiko commented on build/media_source/com_media/scss/components/_media-toolbar.scss
> +  top: 67px;
Did you tested it in a mobile/tablet view?

2022-01-12 20:17 UTC, micker commented on build/media_source/com_media/scss/components/_media-toolbar.scss
> +  top: 67px;
@dgrammatiko can you help for js like tool bar stiky funtion ?

2022-01-12 20:20 UTC, micker commented
@Shubhamverma2796 can you add
thead.media-browser-table-head { position: sticky; top: 124px; z-index: 1; }
that add stiky to table header in list view ?

2022-01-12 20:23 UTC, Shubhamverma2796 commented
> @Shubhamverma2796 can you add thead.media-browser-table-head { position: sticky; top: 124px; z-index: 1; } that add stiky to table header in list view ?

in the media-tree.scss file?

2022-01-12 20:24 UTC, dgrammatiko commented on build/media_source/com_media/scss/components/_media-toolbar.scss
> +  top: 67px;
Something like https://github.com/joomla/joomla-cms/blob/e46fc6489451b334aae863b99189c51a76c3da01/administrator/templates/isis/js/template.js#L254-L268 but without the jQuery dependency should do it. Btw set a css var and use the css var instead of setting the style top directly

2022-01-12 20:34 UTC, micker commented
@Shubhamverma2796 no i didn't find any reference i find here https://github.com/joomla/joomla-cms/blob/4ee06a1fc3222f1c09ad5db37ebfe87deb7d40a8/build/media_source/com_media/scss/components/_media-browser.scss#L284

2022-01-12 20:42 UTC, micker commented
i think we need to add a class in scss
.media-drive.fixed
.media-toolbar.fixed
.media-browser-table-head.fixed
And add a js script like @dgrammatiko said to hadd fixed class on scroll down ...
but i didn't have the skill for

2022-01-12 20:45 UTC, Shubhamverma2796 commented
> @Shubhamverma2796 no i didn't find any reference i find here
> 
> https://github.com/joomla/joomla-cms/blob/4ee06a1fc3222f1c09ad5db37ebfe87deb7d40a8/build/media_source/com_media/scss/components/_media-browser.scss#L284

it is of no use. And I'm not skilled enough to add a js script

2022-03-25 14:53 UTC, Quy commented
@Shubhamverma2796 Please advise status. If you are unable to solve it, please close in order to reopen the issue so someone else can give it a go. thanks.

2022-03-25 14:55 UTC, closed without merging