fix joomla/joomla-cms#36669
joomla/joomla-cms pull request #36685
Opened 2022-01-14 17:24 UTC by costafrancesco94

Pull Request for Issue #36669 .

### Summary of Changes
Remove JPATH_ROOT from absolute file path only if JPATH_ROOT is at beginning of string

### Testing Instructions
Every asset loaded with HTMLHelper::_ is affected

### Actual result BEFORE applying this Pull Request
If JPATH_ROOT is repeated inside file names, resources are not getting loaded.

Example:
`JPATH_ROOT = '/joomla'`
`$path = '/joomla/media/system/images/joomla-favicon.svg'`
Wrong output before: `/media/system/images-favicon.svg`

Another less unusual example:
`JPATH_ROOT = '/app/html`
`$path = '/app/html/media/com_something/js/app/html_custom.js'`
Wrong output before: `/media/com_something/js_custom.js`

### Expected result AFTER applying this Pull Request
If `JPATH_ROOT` is present 2 times in the $path, it will be removed only if at beginning (where it should be)

Example:
`JPATH_ROOT = '/joomla'`
`$path = '/joomla/media/system/images/joomla-favicon.svg'`
Correct output with patch: `/media/system/images/joomla-favicon.svg`

Another less unusual example:
`JPATH_ROOT = '/app/html`
`$path = '/app/html/media/com_something/js/app/html_custom.js'`
Wrong output before: `/media/com_something/js/app/html_custom.js`

### Documentation Changes Required

Problem was not declared anywhere else

Code run as before (JPATH_ROOT is not supposed to be in the middle of the $path if not for casuality)

2022-01-14 17:53 UTC, dgrammatiko requested changes

2022-01-14 17:53 UTC, dgrammatiko commented on libraries/src/HTML/HTMLHelper.php
> +
```suggestion
 			$path = strpos($path, JPATH_ROOT) === 0 ? substr_replace($path, '', 0, strlen(JPATH_ROOT)) : $path;
```

You can write it as a one line (using the elvis operator)

2022-01-14 18:00 UTC, costafrancesco94 commented on libraries/src/HTML/HTMLHelper.php
> +
A lot cooler this way!

2022-01-14 18:03 UTC, dgrammatiko commented on libraries/src/HTML/HTMLHelper.php
> +		if (strpos($path, JPATH_ROOT) === 0)
You need to remove this part though:
```js
if (strpos($path, JPATH_ROOT) === 0)
{
   $path = substr_replace($path, '', 0, strlen(JPATH_ROOT));
}
```

2022-01-14 18:18 UTC, costafrancesco94 commented on libraries/src/HTML/HTMLHelper.php
> +		if (strpos($path, JPATH_ROOT) === 0)
Sorry it's the first time I use github PR

2022-01-14 18:21 UTC, dgrammatiko commented on libraries/src/HTML/HTMLHelper.php
> +		if (strpos($path, JPATH_ROOT) === 0)
You're doing fine

2022-01-14 18:23 UTC, richard67 commented on libraries/src/HTML/HTMLHelper.php
> +
@dgrammatiko I's a normal ternary operator, not Elvis. Elvis would be `?:`.

2022-01-14 20:19 UTC, dgrammatiko commented on libraries/src/HTML/HTMLHelper.php
> +
Yes, that was a ternary...

2022-06-27 13:06 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2023-05-02 16:30 UTC, HLeithner commented
This pull request has been automatically rebased to 4.3-dev.

2023-09-30 22:45 UTC, HLeithner commented
This pull request has been automatically rebased to 4.4-dev.

2024-11-15 13:22 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2025-01-18 08:55 UTC, joomdonation commented on libraries/src/HTML/HTMLHelper.php
> +        $path = strpos($path, JPATH_ROOT) === 0 ? substr_replace($path, '', 0, \strlen(JPATH_ROOT)) : $path;
The code is not valid anymore because we now use `JPATH_PUBLIC`, not `JPATH_ROOT` as in the past. I think code could be changed to, but no clue how to really test it:

```php
$path = \str_starts_with($path, JPATH_PUBLIC) ? \substr_replace($path, '', 0, \strlen(JPATH_PUBLIC)) : $path;
```

2025-01-18 08:58 UTC, fgsw commented
@costafrancesco94 Can the titel be changed to a more meaningful?

2025-01-19 09:03 UTC, joomdonation commented on libraries/src/HTML/HTMLHelper.php
> +        // Remove JPATH_ROOT only if it is at beginning of full path
```suggestion
        // Remove JPATH_PUBLIC only if it is at beginning of full path
```

2025-01-19 09:03 UTC, joomdonation commented on libraries/src/HTML/HTMLHelper.php
> +        $path = strpos($path, JPATH_ROOT) === 0 ? substr_replace($path, '', 0, \strlen(JPATH_ROOT)) : $path;
```suggestion
        $path = \str_starts_with($path, JPATH_PUBLIC) ? \substr_replace($path, '', 0, \strlen(JPATH_PUBLIC)) : $path;
```

2025-01-19 09:24 UTC, richard67 commented on libraries/src/HTML/HTMLHelper.php
> +        $path = \str_starts_with($path, JPATH_PUBLIC) ? \substr_replace($path, '', 0, \strlen(JPATH_PUBLIC)) : $path;
```suggestion
        $path = str_starts_with($path, JPATH_PUBLIC) ? substr_replace($path, '', 0, \strlen(JPATH_PUBLIC)) : $path;
```

2025-01-19 09:38 UTC, rdeutz commented
Added testimng instructions and tested successfully

2025-01-19 09:39 UTC, rdeutz commented
I have tested this item :white_check_mark: successfully on d47f76c798623072847d63c0817543a8c6e74798<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36685">issues.joomla.org/tracker/joomla-cms/36685</a>.</sub>

2025-01-19 09:41 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on d47f76c798623072847d63c0817543a8c6e74798<br /><br />On windows, it's hard to follow the instructions. But I reviewed code, also tried to using media manager, navigate to different pages and do not see any error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36685">issues.joomla.org/tracker/joomla-cms/36685</a>.</sub>

2025-01-19 09:41 UTC, joomdonation commented
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36685">issues.joomla.org/tracker/joomla-cms/36685</a>.</sub>

2025-01-19 11:33 UTC, merged

2025-11-20 11:48 UTC, michaelmaass commented
I have tested this item :white_check_mark: successfully on 61863c92b35c714821857e407cdd5778124379da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36685">issues.joomla.org/tracker/joomla-cms/36685</a>.</sub>

2025-11-20 11:50 UTC, richard67 commented
@michaelmaass Hmm, it doesn't make much sense to test a pull request which was merged long time ago and so is included since Joomla 5.2. Are you sure you marked the right one?

2025-11-20 11:57 UTC, michaelmaass commented
> @michaelmaass Hmm, it doesn't make much sense to test a pull request which was merged long time ago and so is included since Joomla 5.2. Are you sure you marked the right one?

Yes, sorry for the confusion. 

I **had** tested it quite a long time ago but only now learned how to correctly create the appropriate response ... and clearly missed the boat.