[4.1 ScheduledTasks] changes
joomla/joomla-cms pull request #36698
Opened 2022-01-15 18:54 UTC by niharikamahajan02

Pull Request for Issue #36453  .

2022-01-15 19:16 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/149634978-0cb6e979-8b29-4a43-b7da-7830d3e080ee.png)

2022-01-15 20:23 UTC, tecpromotion commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_TASK_TYPE_ASC="Task Type ascending"
```suggestion
COM_SCHEDULER_TASK_TYPE_ASC="Task type ascending"
```

2022-01-15 20:23 UTC, tecpromotion commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_TASK_TYPE_DESC="Task Type descending"
```suggestion
COM_SCHEDULER_TASK_TYPE_DESC="Task type descending"
```

2022-01-15 20:24 UTC, tecpromotion commented on administrator/language/en-GB/com_scheduler.ini
>  COM_SCHEDULER_TASK_TYPE="Task Type"
```suggestion
COM_SCHEDULER_TASK_TYPE="Task type"
```

2022-01-15 20:26 UTC, tecpromotion commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_TASK_TYPE_ASC="Task Type ascending"
```suggestion
```

2022-01-15 20:26 UTC, tecpromotion commented on administrator/language/en-GB/com_scheduler.ini
> +COM_SCHEDULER_TASK_TYPE_DESC="Task Type descending"
```suggestion
```

2022-01-15 20:26 UTC, tecpromotion commented on administrator/language/en-GB/com_scheduler.ini
> +
```suggestion
```

2022-01-15 20:28 UTC, tecpromotion commented on administrator/components/com_scheduler/tmpl/tasks/default.php
>  							<button type="button" class="btn btn-sm btn-warning" <?php echo $item->state < 0 ? 'disabled' : ''; ?> data-id="<?php echo (int) $item->id; ?>" data-title="<?php echo htmlspecialchars($item->t
```suggestion
							<button type="button" class="btn btn-sm btn-warning" <?php echo $item->state < 0 ? 'disabled' : ''; ?> data-id="<?php echo (int) $item->id; ?>" data-title="<?php echo htmlspecialchars($item->title); ?>" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#scheduler-task-modal">
```

2022-01-15 20:29 UTC, tecpromotion commented on administrator/components/com_scheduler/tmpl/tasks/default.php
>  							<button type="button" class="btn btn-sm btn-warning" <?php echo $item->state < 0 ? 'disabled' : ''; ?> data-id="<?php echo (int) $item->id; ?>" data-title="<?php echo htmlspecialchars($item->t
Please check if this works

2022-01-15 20:29 UTC, brianteeman commented on administrator/language/en-GB/com_scheduler.ini
>  COM_SCHEDULER_TASK_TYPE="Task Type"
Task Type is correct in the same way as we have Task Priority

2022-01-15 20:30 UTC, tecpromotion commented on composer.json
> +
```suggestion
```

2022-01-15 20:32 UTC, tecpromotion commented on administrator/components/com_scheduler/access.xml
> +		<action name="core.runtask" title="COM_SCHEDULER_PERMISSION_RUN_TASK" />
Please check https://github.com/joomla/joomla-cms/blob/53544c6a58778cfe9e338d0ba80149c67bb5452d/plugins/system/schedulerunner/schedulerunner.php#L267

2022-01-15 20:37 UTC, tecpromotion commented on administrator/components/com_scheduler/tmpl/tasks/default.php
>  							<button type="button" class="btn btn-sm btn-warning" <?php echo $item->state < 0 ? 'disabled' : ''; ?> data-id="<?php echo (int) $item->id; ?>" data-title="<?php echo htmlspecialchars($item->t
Please check

https://github.com/joomla/joomla-cms/blob/53544c6a58778cfe9e338d0ba80149c67bb5452d/build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js#L22
and
https://github.com/joomla/joomla-cms/blob/53544c6a58778cfe9e338d0ba80149c67bb5452d/administrator/components/com_scheduler/tmpl/tasks/default.php#L253

2022-01-15 20:38 UTC, tecpromotion requested changes
Please check my comments @niharikamahajan02

2022-01-16 00:52 UTC, PhilETaylor commented on build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js
> +
This should fix the drone complaining 

```suggestion
    modal.querySelector('.modal-title').innerHTML = Joomla.Text._('COM_SCHEDULER_RUN_TASK_TITLE').replace('%d', id.toString());

```

2022-01-16 14:47 UTC, richard67 commented
@niharikamahajan02 The branch for this PR meanwhile has conflicts due to recent changes in the 4.1-dev branch. You can try to solve the conflicts, but maybe it's easier to make a new PR. In both cases you should update your 4.1-dev branch to the same branch of the upstream repository so it is up to date. Let us know if you need help or advise.

2022-01-16 15:29 UTC, niharikamahajan02 commented
Ok, I will make a new PR then. Thanks

2022-01-16 18:43 UTC, tecpromotion commented
And please look for any occurrences of old strings. I have found a few more. 

e.g.

media/com_scheduler/js/admin-view-run-test-task.js
media/com_scheduler/js/admin-view-run-test-task-es5.js

2022-01-16 18:44 UTC, tecpromotion commented on administrator/language/en-GB/com_scheduler.ini
>  COM_SCHEDULER_TEST_TASK="Test Task"
```suggestion
```

2022-01-17 03:04 UTC, niharikamahajan02 commented
> And please look for any occurrences of old strings. I have found a few more.
> 
> e.g.
> 
> media/com_scheduler/js/admin-view-run-test-task.js media/com_scheduler/js/admin-view-run-test-task-es5.js

Ok sir.

2022-01-17 08:38 UTC, niharikamahajan02 commented
> And please look for any occurrences of old strings. I have found a few more.
> 
> e.g.
> 
> media/com_scheduler/js/admin-view-run-test-task.js media/com_scheduler/js/admin-view-run-test-task-es5.js

I tried changing all the constants in -

media/com_scheduler/js/admin-view-run-test-task.js
media/com_scheduler/js/admin-view-run-test-task-es5.js

and also in other files , but one problem is that even after changing constants in minified js also (in my code editor)  that change is not getting reflected in 
[media/com_scheduler/js/admin-view-run-test-task.min.js](http://localhost/joomla/joomla-cms/media/com_scheduler/js/admin-view-run-test-task-es5.min.js?6281cc2e15f16e34efa477c4e29c4976)   like
![image](https://user-images.githubusercontent.com/72392580/149735535-52c92d27-f5df-407c-b033-5f9badc79611.png)

2022-01-17 08:46 UTC, brianteeman commented
Do not touch anything in the /media folder

The changes must be made in /build/media-source

Then you run the npm task to rebuild the /media folder (`npm run build:js`)

2022-01-17 08:47 UTC, richard67 commented
See also https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment

2022-01-17 09:09 UTC, niharikamahajan02 commented
Okay, thanks!

2022-01-17 12:59 UTC, niharikamahajan02 commented
Yes , the problem is now fixed I'll just submit a new PR now.

2022-01-18 03:39 UTC, closed without merging