[4.1 ScheduledTasks]Edits for run task
joomla/joomla-cms pull request #36725
Opened 2022-01-18 03:38 UTC by niharikamahajan02

Pull Request for Issue #36453 .

### Summary of Changes
Edits for run task.

2022-01-20 16:19 UTC, niharikamahajan02 commented
Please review. Thanks

2022-01-22 08:43 UTC, tecpromotion commented
> Please review. Thanks

Please check whether you have taken over all comments from your previous PRs.
Furthermore, I have the impression, but still have to test it, that again not all occurrences have been renamed.
Please also check this with a full text search over the whole repo.
And please keep the code up to date.

2022-01-22 13:04 UTC, niharikamahajan02 commented
But sir , it is working fine after running the command (npm run build:js )
![image](https://user-images.githubusercontent.com/72392580/150639625-1ade3d75-0300-46d3-86e2-9098143c8c72.png)

2022-01-22 16:46 UTC, tecpromotion commented on administrator/language/en-GB/com_scheduler.ini
>  COM_SCHEDULER_PERMISSION_TESTRUN="Test task"
```suggestion
COM_SCHEDULER_PERMISSION_RUN_TASK="Run task"
```

@niharikamahajan02 please check this constant and the string. You have already renamed it in the access.xml.

2022-01-22 16:50 UTC, tecpromotion commented
Should this also be adapted?

https://github.com/joomla/joomla-cms/blob/838845941106a2b93eed1d304ad97f3d152cb3a9/plugins/system/schedulerunner/schedulerunner.php#L92

and 

https://github.com/joomla/joomla-cms/blob/838845941106a2b93eed1d304ad97f3d152cb3a9/plugins/system/schedulerunner/schedulerunner.php#L255

2022-01-22 16:54 UTC, tecpromotion commented
And maybe also replace **onAjaxRunSchedulerTest** with **onAjaxRunSchedulerTask**?

@ditsuke what do you think about this improvements?

2022-01-22 17:02 UTC, tecpromotion commented on build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js
>    const uri = `${paths ? `${paths.base}/index.php` : window.location.pathname}?option=com_ajax&format=json&plugin=RunSchedulerTest&group=system&id=%d${token ? `&${token}=1` : ''}`;
```suggestion
  const uri = `${paths ? `${paths.base}/index.php` : window.location.pathname}?option=com_ajax&format=json&plugin=RunSchedulerTask&group=system&id=%d${token ? `&${token}=1` : ''}`;
```

2022-01-22 17:02 UTC, tecpromotion commented on plugins/system/schedulerunner/schedulerunner.php
> +				$mapping['onAjaxRunSchedulerTask'] = 'runTaskCron';
onAjaxRunSchedulerTask must also be fixed in the js files.
please check.

2022-01-22 17:03 UTC, niharikamahajan02 commented on plugins/system/schedulerunner/schedulerunner.php
> +				$mapping['onAjaxRunSchedulerTask'] = 'runTaskCron';
Ohh yes okk

2022-01-22 18:59 UTC, tecpromotion commented
Please check this two code comments.

https://github.com/joomla/joomla-cms/blob/42f7f89788384ca08ec3a43d46a7e736a2777a48/plugins/system/schedulerunner/schedulerunner.php#L243

https://github.com/joomla/joomla-cms/blob/42f7f89788384ca08ec3a43d46a7e736a2777a48/plugins/system/schedulerunner/schedulerunner.php#L297

2022-01-22 19:06 UTC, tecpromotion commented
Also, please check the occurrences of '**test-task**'.
This concerns file names, function calls and declarations.

@niharikamahajan02 sorry for all the comments but it's best to clean it straight away.

2022-01-23 09:25 UTC, niharikamahajan02 commented
> Also, please check the occurrences of '**test-task**'. This concerns file names, function calls and declarations.
> 
> @niharikamahajan02 sorry for all the comments but it's best to clean it straight away.

No problem sir 😄 and yes it's better to clean them straight away now

2022-01-23 09:27 UTC, niharikamahajan02 commented
Yes ,I would rename the file names, function calls and declarations also 👍

2022-01-23 12:27 UTC, niharikamahajan02 commented
Please suggest if something needs to be updated now . Thanks

2022-01-23 12:54 UTC, ditsuke commented
@tecpromotion 

> @ditsuke what do you think about this improvements?

Thanks for tagging! I really like the changes so far.

2022-01-23 13:13 UTC, ditsuke requested changes

2022-01-23 13:13 UTC, ditsuke commented on build/media_source/com_scheduler/joomla.asset.json
> -      "uri": "com_scheduler/admin-view-run-test-task-es5.js",
Please rename file `build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js` => `build/media_source/com_scheduler/js/admin-view-run-task.es6.js`

2022-01-23 13:13 UTC, ditsuke commented on build/media_source/com_scheduler/joomla.asset.json
> +      "uri": "com_scheduler/admin-view-run-run-task-es5.js",
```suggestion
      "uri": "com_scheduler/admin-view-run-task-es5.js",
```

2022-01-23 13:13 UTC, ditsuke commented on build/media_source/com_scheduler/joomla.asset.json
> +      "uri": "com_scheduler/admin-view-run-run-task.js",
```suggestion
      "uri": "com_scheduler/admin-view-run-task-es5.js",
```

2022-01-23 13:22 UTC, niharikamahajan02 commented
Yes sir , changed the file name now.

2022-01-23 13:28 UTC, ditsuke commented
@niharikamahajan02 

> Yes sir , changed the file name now.

Nicely done! You can resolve the suggestions I left above from your end.

2022-01-23 17:48 UTC, niharikamahajan02 commented
Ok sir , thanks!

2022-02-13 08:45 UTC, niharikamahajan02 commented
Actually for resolving the conflict I am doing git pull, and it's saying already up to date.
Even after that new changes made in administrator/components/com_scheduler/tmpl/tasks/default.php( which is causing conflict ) are not getting reflected.

2022-02-13 09:46 UTC, ditsuke commented
> Actually for resolving the conflict I am doing git pull, and it's saying already up to date. Even after that new changes made in administrator/components/com_scheduler/tmpl/tasks/default.php( which is causing conflict ) are not getting reflected.

I've opened a PR to update your branch to `4.1-dev` and resolve conflicts. 
PTAL https://github.com/niharikamahajan02/joomla-cms/pull/1.

2022-02-13 09:55 UTC, niharikamahajan02 commented
Ok , so do I need to do something for now?

2022-02-13 09:56 UTC, ditsuke commented
> Ok , so do I need to do something for now?

Please merge the PR. It's on your fork.

2022-02-13 10:01 UTC, niharikamahajan02 commented
ok ,done

2022-06-27 13:06 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2022-06-27 17:45 UTC, richard67 commented
I've allowed myself to solve the conflicting files.

2023-04-07 06:46 UTC, HLeithner commented
I rebased the PR and added back removed language strings and deprecated them.

2023-09-30 22:52 UTC, HLeithner commented
This pull request has been automatically rebased to 5.1-dev.

2023-12-19 14:21 UTC, hans2103 commented
@niharikamahajan02 please solve the unresolved conversations of this PR. I would like to see this merged into a following Joomla version, while _Run Test_ is the correct name for the action the button is doing

2023-12-22 12:41 UTC, niharikamahajan02 commented
please review it once , I think there are some changes to be done

2023-12-22 12:45 UTC, richard67 commented
> please review it once , I think there are some changes to be done

@niharikamahajan02 It needs to resolve merge conflicts in files `build/media_source/com_scheduler/joomla.asset.json` and `plugins/system/schedulerunner/schedulerunner.php`. Maybe just use the clean files from the 5.1-dev branch and apply your changes again on them.

2023-12-22 13:17 UTC, niharikamahajan02 commented
but they are already having "run test" in 5.1-dev

2023-12-22 13:19 UTC, richard67 commented
> but they are already having "run test" in 5.1-dev

@niharikamahajan02 What do you mean? Drone tests are failing, and if you go to the bottom of this PR on GitHub you clearly see there are the 2 mentioned files which have merge conflicts. If you don't know how to solve them we can help, but maybe you can try it yourself first like I have described.

2024-04-24 09:09 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2024-07-07 17:53 UTC, brbrbr commented
I was pointed to this PR after a comment of mine on  https://github.com/joomla/joomla-cms/issues/43665#issuecomment-2212483646


1.  looks like the Commits on Dec 22, 2023 reverted all the changes, I see 'TEST_RUN' all over the place and no 'RUN TASK.
2. breaks the site(UserFactoryAwareTrait not found), seems that some of the merges of branches failed. (tried gh pr checkout 36725 and git fetch upstream pull/36725/head:run-task). 
3. there are some merge issues with #43491

2024-08-24 15:01 UTC, bascherz commented
I have tested this item :red_circle: unsuccessfully on 688088497c2ae4c212c02129b5a866fd2a74550f<br /><br />Could not apply the patch, so could not test. This was done on a fresh 5.2.0-beta1 site.

ERROR MESSAGE:
The file marked for modification does not exist: plugins/system/schedulerunner/schedulerunner.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36725">issues.joomla.org/tracker/joomla-cms/36725</a>.</sub>

2024-08-24 15:03 UTC, richard67 commented
> I have tested this item 🔴 unsuccessfully on [6880884](https://github.com/joomla/joomla-cms/commit/688088497c2ae4c212c02129b5a866fd2a74550f)Could not apply the patch, so could not test. This was done on a fresh 5.2.0-beta1 site.
> 
> ERROR MESSAGE: The file marked for modification does not exist: plugins/system/schedulerunner/schedulerunner.php
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/36725](https://issues.joomla.org/tracker/joomla-cms/36725).

@bascherz If you go to this PR on GitHub and scroll to the bottom you will see that this PR has conflicting files, so I cannot really be tested.

2024-09-02 08:54 UTC, HLeithner commented
This pull request has been automatically rebased to 5.3-dev.

2025-03-04 17:23 UTC, HLeithner commented
This pull request has been automatically rebased to 6.0-dev.

2025-04-24 21:08 UTC, brianteeman commented
Please close in favour of #45313

2025-04-24 21:23 UTC, closed without merging