[4.2] Smart Search: Allow fuzzy word matching
joomla/joomla-cms pull request #36752
Opened 2022-01-20 07:50 UTC by Hackwar

### Summary of Changes
A regular request was to be able to also find compoung words. Smart Search right now matches the words exactly, even though it uses a stemmer to find common roots for a word. However those stemmers can only work on single words and "fail" on compound words, like they are very common in for example the german language. This PR allows to switch the matching method between exact matches, matching words starting with the given term and matching words which just contain the term in a random position. I was hoping that there would be a way to automatically split compound words in their different parts and to also index those, however I couldn't find a solution which could be used with justifiable effort. So this is the next best solution as it seems.

### Testing Instructions
1. Apply this PR to your Joomla installation.
2. Go to the configuration of Smart Search and set the "Word Match" to your prefered setting.
3. Test searching in the frontend with parts of compound words. No reindexing needed.

### Notes
1. Since 4.1 is in RC, this will have to go into 4.2. Since there is no 4.2-dev branch yet, I'm pointing this towards 4.1-dev for now.

2022-01-20 07:59 UTC, brianteeman commented on administrator/components/com_finder/config.xml
> +		</field>
```suggestion
		<field
			name="word_match"
			type="list"
			label="COM_FINDER_CONFIG_WORD_MATCH_LABEL"
			description="COM_FINDER_CONFIG_WORD_MATCH_DESC"
			default="0"
			>
			<option value="0">COM_FINDER_CONFIG_WORD_MATCH_OPTION_EXACT</option>
			<option value="1">COM_FINDER_CONFIG_WORD_MATCH_OPTION_BEGIN</option>
			<option value="2">COM_FINDER_CONFIG_WORD_MATCH_OPTION_FUZZY</option>
		</field>
```

2022-01-20 08:00 UTC, brianteeman commented on administrator/components/com_finder/src/Indexer/Query.php
> +	 * @since  4.2
```suggestion
	 * @since  __DEPLOY_VERSION__
```

2022-01-20 08:00 UTC, brianteeman commented on administrator/components/com_finder/src/Indexer/Query.php
> +					// Todo: The previous function call may return an array, which seems not to be handled by the next one, which expects an object
Please revert this change

2022-01-20 11:50 UTC, HLeithner commented
please don't introduce magic numbers, define "words" in the xml and add constants to the class for matching the value.

2022-01-20 11:55 UTC, HLeithner commented on administrator/components/com_finder/src/Indexer/Query.php
> +			$query->where('t.phrase = 0')
beside the constant use please already mentioned I would use less copy paste.

```suggestion

			$searchTerm = $token->term;
			$searchStem = $token->stem;
			
			if ($this->wordmode == 1)
			{
				$searchTerm .= '%';
				$searchStem .= '%';
			}
			elseif ($this->wordmode == 2)
			{
				$searchTerm = '% . $searchTerm . '%';
				$searchStem = '% . $searchStem . '%';
			}
			
			$query->where('(t.term = ' . $db->quote($searchTerm) . ' OR t.stem = ' . $db->quote($searchStem) . ')');
			$query->where('t.phrase = 0')
```

beside this, when you touch it it would make sense to convert it to use perpared statements

2022-01-26 22:56 UTC, Quy commented on administrator/components/com_finder/config.xml
> +			default="0"
```suggestion
			default="exact"
```

2022-01-27 09:22 UTC, brianteeman commented on administrator/language/en-GB/com_finder.ini
> +COM_FINDER_CONFIG_WORD_MATCH_OPTION_FUZZY="Match words containing the search term anywhere"
```suggestion
COM_FINDER_CONFIG_WORD_MATCH_OPTION_BEGIN="Also match words beginning with the search term"
COM_FINDER_CONFIG_WORD_MATCH_OPTION_EXACT="Match exactly"
COM_FINDER_CONFIG_WORD_MATCH_OPTION_FUZZY="Match words containing the search term anywhere"
```

2022-01-27 09:23 UTC, brianteeman commented on administrator/language/en-GB/com_finder.ini
> +COM_FINDER_FIELDSET_INDEX_OPTIONS_DESCRIPTION="These options influence how the content is indexed. After changing settings here, the index needs to be rebuild."
```suggestion
COM_FINDER_FIELDSET_INDEX_OPTIONS_DESCRIPTION="These options influence how the content is indexed. After changing settings here, the index needs to be rebuilt."
```

2022-01-28 08:24 UTC, SniperSister commented on administrator/components/com_finder/src/Indexer/Query.php
> +			if ($this->wordmode == 'begin')
Use a strict compare with ===

2022-01-28 08:24 UTC, SniperSister commented on administrator/components/com_finder/src/Indexer/Query.php
> +			elseif ($this->wordmode == 'fuzzy')
Use a strict compare with ===

2022-02-05 15:51 UTC, Quy commented on administrator/language/en-GB/com_finder.ini
> +COM_FINDER_CONFIG_WORD_MATCH_DESC="This option allows to set how search terms are matched in the index. By default a word is matched exactly, but when a language supports compound words, this allows
```suggestion
COM_FINDER_CONFIG_WORD_MATCH_DESC="Set how search terms are matched in the index. By default a word is matched exactly, but when a language supports compound words, this allows to match the search term to the beginning or in a random place inside of words in the index."
```

2022-02-05 15:52 UTC, Quy commented on administrator/language/en-GB/com_finder.ini
> +COM_FINDER_CONFIG_WORD_MATCH_OPTION_BEGIN="Also match words beginning with the search term"
```suggestion
COM_FINDER_CONFIG_WORD_MATCH_OPTION_BEGIN="Match words beginning with the search term"
```
?

2022-04-03 10:21 UTC, superknutsel commented
I have tested this item :red_circle: unsuccessfully on 7e56d0bde46f58e7afbf3baae87f25dea01fd122<br /><br />I found that when searching for a partial or complete word the suggestion showed the result but after hitting enter there were no results show. When I revert the patch I get results for complete words when I do this, not for partial search terms.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36752">issues.joomla.org/tracker/joomla-cms/36752</a>.</sub>

2022-05-17 11:35 UTC, Hackwar commented
Thank you, @superknutsel. There was indeed a bug in the code. Can you test this again?

2022-05-17 12:04 UTC, superknutsel commented
I have tested this item :white_check_mark: successfully on a1d1b4fec01b677f4c554e5a8845833e5ad88b09<br /><br />Hi @Hackwar I tested again and now it's working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36752">issues.joomla.org/tracker/joomla-cms/36752</a>.</sub>

2022-05-17 12:05 UTC, Hackwar commented
Thank you very much.

2022-05-19 20:46 UTC, webnet-assmann commented
I have tested this item :white_check_mark: successfully on a1d1b4fec01b677f4c554e5a8845833e5ad88b09<br /><br />Tested it with all settings of Word Match and it's working.
Thank you Hannes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36752">issues.joomla.org/tracker/joomla-cms/36752</a>.</sub>

2022-05-20 06:20 UTC, alikon requested changes

2022-05-20 06:20 UTC, alikon commented on administrator/components/com_finder/src/Indexer/Query.php
> +				$query->where('(t.term LIKE ' . $db->quote($searchTerm) . ' OR t.stem LIKE ' . $db->quote($searchStem) . ')');
please use prepared statements & quoteName()

2022-05-20 09:45 UTC, Hackwar commented on administrator/components/com_finder/src/Indexer/Query.php
> +				$query->where('(t.term LIKE ' . $db->quote($searchTerm) . ' OR t.stem LIKE ' . $db->quote($searchStem) . ')');
done

2022-06-02 11:47 UTC, merged

2022-06-02 11:47 UTC, HLeithner commented
Thanks