[4.2] Smart Search: Add debugging features
joomla/joomla-cms pull request #36753
Opened 2022-01-20 07:51 UTC by Hackwar

### Summary of Changes
In order to gain wider adoption from third party developers, we need to provide them with improved development tools. This PR implements a few features, which become visible when the debug mode is enabled.

#### Display indexed item
First of all we want to be able to see what has been indexed for an item. When you enable debugging, the list of entries in the index will now be linked and clicking on such an entry will give you a view which displays the common data from indexed items, the type specific items, the indexed terms and the associated taxonomies. This allows you to understand if the content was indexed the way you expected it, as well as with the weighing you expected.

#### Debug indexing of one specific item
Again, when debugging is enabled, a new dropdown button in the index view appears with "Index debugging". This button goes to a new view, where you can select a finder plugin and type in an ID to index and it will then run that plugin for that ID. It will then either return what has been prepared to be indexed by the indexer in the result object or whatever output the plugin generated. This should allow a developer to better write a new finder plugin to index their content.

### Testing Instructions
1. Install Joomla and provide some sample data. Please note that this PR requires "npm i" to be run again after it has been applied!
2. Enable debugging mode in global configuration
3. Go to Smart Search and click on an entry in the list to display the data in the index for this item
4. Click on "Index > Index debugging" and select a finder plugin from the list.
5. Type in an ID, for example "60" in case you are using the testing sample data, and click on "Index"

### Notes
1. The dropdown button seems to have a styling error when using a modal button as first entry. The spacing is wrong and I couldn't find out why.
2. I'm open for better language strings. 
3. Since 4.1 is in RC, this will have to go into 4.2. Since there is no 4.2-dev branch yet, I'm pointing this towards 4.1-dev for now.

2022-01-20 07:58 UTC, brianteeman commented on administrator/components/com_finder/forms/indexer.xml
> +		/>
```suggestion
		<field
			name="plugin"
			type="plugins"
			label="COM_FINDER_FIELD_FINDER_PLUGIN_LABEL"
			folder="finder"
			required="true"
		/>

		<field
			name="id"
			type="text"
			label="JGLOBAL_FIELD_ID_LABEL"
			required="true"
		/>
```

2022-01-20 17:25 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +	 * @since   4.1
```suggestion
	 * @since   ___DEPLOY_VERSION__
```

2022-01-20 17:26 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +	 * @throws  Exception on database error.
An abstract function cannot throw an Exception

2022-01-20 17:26 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +	 * @param   integer  $id  The ID of the item to reindex.
```suggestion
	 * @param   int  $id  The ID of the item to reindex.
```

Param uses short version, return uses long version

2022-01-20 17:26 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +	 * @throws  Exception on database error.
Abstract method cannot throw an exception

2022-01-20 17:29 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +	 * @throws  Exception on database error.
Are all these "Exception on error" docs saying an exception of type `\Exception` is expected on error, or are they just commentary? If they are the latter they should be removed or correctly explain what type of exceptions are thrown. Throughout this PR.

2022-01-20 17:29 UTC, PhilETaylor commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +	 * @param   mixed  $query  A QueryInterface object. [optional]
If its nullable then the docs should state that correctly as a type. 

```suggestion
	 * @param   mixed|null  $query  A QueryInterface object
```

2022-01-20 17:31 UTC, PhilETaylor commented on administrator/components/com_finder/src/Model/IndexerModel.php
> +	public function getForm($data = array(), $loadData = true)
Use short array syntax throughout

```suggestion
	public function getForm($data = [], $loadData = true)
```

2022-01-20 17:31 UTC, PhilETaylor commented on administrator/components/com_finder/src/Model/ItemModel.php
> +	 * @return  object[]
```suggestion
	 * @return  \stdClass[]
```

2022-01-20 17:31 UTC, PhilETaylor commented on administrator/components/com_finder/src/View/Indexer/HtmlView.php
> +	 * @var Form $form
```suggestion
	 * @var   Form  $form
```

2022-01-20 17:32 UTC, PhilETaylor commented on administrator/components/com_finder/src/View/Indexer/HtmlView.php
> +		// Get the toolbar object instance
```suggestion
```

2022-01-20 17:32 UTC, PhilETaylor commented on build/media_source/com_finder/js/debug.es6.js
> + * @copyright  (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright  (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-01-24 20:25 UTC, Hackwar commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +	 * @throws  Exception on database error.
PHPStorm added this automatically. I will remove all of this.

2022-01-27 01:01 UTC, Quy commented
Please change branch. Thanks.

2022-01-27 01:05 UTC, Hackwar commented
Hmm, that was a failure...

2022-01-27 09:11 UTC, Hackwar commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +	 * @throws  Exception on database error.
Ok, no, PHPStorm did not add all of this automatically. These are part of the original Adapter class already. Since I just copied this over, I wouldn't want to change it further than necessary. removing all those unnecessary tags should be done in another PR.

2022-01-27 09:13 UTC, brianteeman commented
Please update the markup of the table to follow the accessibility standards used on every table in the admin

2022-01-27 09:19 UTC, brianteeman commented on .drone.yml
> +#  - name: php81-unit
is this change intentional?

2022-01-27 09:19 UTC, Hackwar commented on .drone.yml
> +#  - name: php81-unit
No, this happened when switching the branch this was based on. I still need to fix this.

2022-01-27 09:21 UTC, brianteeman commented on administrator/components/com_finder/tmpl/item/default.php
> +			<tr>
Please update this table to use the accessibility standards used in all other tables

2022-02-01 11:49 UTC, richard67 commented on .drone.yml
> +#  - name: php81-unit
I've allowed myself to update the branch, so this is fixed.

2022-02-03 11:14 UTC, Hackwar commented on administrator/components/com_finder/tmpl/item/default.php
> +			<tr>
I've added the scop="col" attributes. Is it necessary to add an additional caption, when there is a caption for the fieldset right above it?

2022-02-03 11:21 UTC, brianteeman commented on administrator/components/com_finder/tmpl/item/default.php
> +			<tr>
take a look at any admin table and you will see exactly what is needed

2022-02-03 20:44 UTC, Hackwar commented on administrator/components/com_finder/tmpl/item/default.php
> +			<tr>
I'm sorry, but I looked at all of this extensively and what I could find was the hidden caption and spans in the head of the tables. However since there is a visible caption above each table and these tables are neither sortable nor filterable (and it also is unnecessary to have this) I'm fine with the way it is now. I'm not really happy to copy this over, creating duplicate content on the page, just for the sake of having this the same everywhere. I'd rather not start a cargo cult here.

If I missed something besides this, please help me out here.

2022-02-03 21:25 UTC, brianteeman commented on administrator/components/com_finder/tmpl/item/default.php
> +			<tr>
the <caption> element must be the first child of its parent [<table>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table) element.

2022-02-03 21:27 UTC, brianteeman commented on administrator/components/com_finder/tmpl/item/default.php
> +		<caption><?php echo Text::_('COM_FINDER_ITEM_FIELDSET_ITEM_TITLE'); ?></caption>
for a fieldset it should be a legend not a caption
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend

2022-02-03 21:28 UTC, brianteeman commented on administrator/components/com_finder/tmpl/item/default.php
> +	<fieldset>
Is this really a fieldset?

2022-02-03 21:30 UTC, brianteeman commented on administrator/components/com_finder/tmpl/item/default.php
> +		<caption><?php echo Text::_('COM_FINDER_ITEM_FIELDSET_ITEM_TITLE'); ?></caption>
but none of this on this page should be a fieldset.

The < fieldset > [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to group several controls as well as labels ([<label>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)) within a

2022-02-03 21:31 UTC, brianteeman commented on administrator/components/com_finder/tmpl/item/default.php
> +					<td><?php echo $term->term_id; ?></td>
If one of the cells in a row is the main indicator (which I am guessing is the term) then it should also be a th with a scope =row

2022-04-22 11:03 UTC, richard67 commented
@Hackwar Do you think you can implement @brianteeman 's suggestions?

2022-05-17 08:41 UTC, Hackwar commented
@brianteeman can you have a look if the changes which I made would be acceptable?

2022-05-17 10:48 UTC, brianteeman commented
The tables still do not have a caption. This is essential.

2022-05-17 10:54 UTC, Hackwar commented
I kept the caption short. Fine like so? Can you mark those conversations then as resolved?

2022-05-17 10:59 UTC, brianteeman commented
I need to review it in the browser. Which I will di in the next day or so

2022-05-17 20:37 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/168905728-69c9e2bf-a3ef-453b-8afd-6469cf1918c5.png)

2022-05-17 20:40 UTC, brianteeman commented
> I kept the caption short. Fine like so? Can you mark those conversations then as resolved?

i do nnot have the access to mark the 3 a11y issues as resolved but they as far as i am concerned

2022-05-17 20:48 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/168907282-ab04743f-917a-452d-b142-c809885ccacc.png)


For toolback please use the same icon and code as seen in com_workflows transitions

![image](https://user-images.githubusercontent.com/1296369/168907369-c3635866-a85c-42f0-b84a-53148e6d840e.png)

2022-05-18 08:33 UTC, Hackwar commented
> ![image](https://user-images.githubusercontent.com/1296369/168907282-ab04743f-917a-452d-b142-c809885ccacc.png)
> 
> For toolback please use the same icon and code as seen in com_workflows transitions
> 
> ![image](https://user-images.githubusercontent.com/1296369/168907369-c3635866-a85c-42f0-b84a-53148e6d840e.png)

I don't know how you got that, but my button already looks like the correct one.

2022-05-18 08:33 UTC, Hackwar commented
> ![image](https://user-images.githubusercontent.com/1296369/168905728-69c9e2bf-a3ef-453b-8afd-6469cf1918c5.png)
> 
> width issues

fixed.

2022-05-18 08:51 UTC, brianteeman commented
this is what I am seeing 
![image](https://user-images.githubusercontent.com/1296369/168998772-ae2ad643-7caa-4a95-a9a4-f0f6a353020a.png)

![image](https://user-images.githubusercontent.com/1296369/168998865-871f479b-51ad-4771-8507-d60d54098fdb.png)

2022-05-18 10:51 UTC, Hackwar commented
It is just ToolbarHelper::back() and that is returning different code here. Maybe you got some other stuff in your codebase interfering there? That is just not what is in the code and what is being returned on my end. And comparing this with our current 4.2-dev, my version and 4.2-dev agree with each other.

2022-05-18 17:03 UTC, brianteeman commented
@Hackwar I have verified once again my previous findings by building a completely new site on a new server using the pre-built package for this PR. I will submit a PR to your branch to fix that

2022-05-18 17:06 UTC, brianteeman commented
https://github.com/Hackwar/joomla-cms/pull/53

2022-05-18 17:08 UTC, Hackwar commented
done

2022-05-18 17:16 UTC, alikon requested changes

2022-05-18 17:16 UTC, alikon commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->where($db->quoteName('l.link_id') . ' = ' . $link_id);
please use prepared statements

2022-05-18 17:16 UTC, alikon commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->where($db->quoteName('l.link_id') . ' = ' . $link_id)
please use prepared statements & quotename

2022-05-18 17:16 UTC, alikon commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->where($db->quoteName('m.link_id') . ' = ' . $link_id)
++

2022-05-18 17:25 UTC, Hackwar commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->where($db->quoteName('l.link_id') . ' = ' . $link_id);
done

2022-05-18 17:25 UTC, Hackwar commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->where($db->quoteName('l.link_id') . ' = ' . $link_id)
done

2022-05-18 17:25 UTC, Hackwar commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->where($db->quoteName('m.link_id') . ' = ' . $link_id)
done

2022-05-19 11:52 UTC, Quy commented on administrator/components/com_finder/src/Model/ItemModel.php
> +use Joomla\CMS\MVC\Model\BaseDatabaseModel;
```suggestion
use Joomla\CMS\MVC\Model\BaseDatabaseModel;
use Joomla\Database\ParameterType;
```

2022-05-19 11:53 UTC, Quy commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->bind(':link_id', $link_id);
```suggestion
			->bind(':link_id', $link_id, ParameterType::INTEGER);
```

2022-05-19 11:53 UTC, Quy commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->bind(':link_id', $link_id);
```suggestion
			->bind(':link_id', $link_id, ParameterType::INTEGER);
```

2022-05-19 11:53 UTC, Quy commented on administrator/components/com_finder/src/Model/ItemModel.php
> +			->bind(':link_id', $link_id);
```suggestion
			->bind(':link_id', $link_id, ParameterType::INTEGER);
```

2022-06-21 08:37 UTC, laoneo commented on administrator/components/com_finder/src/Controller/IndexerController.php
> +			require_once JPATH_ADMINISTRATOR . '/components/com_finder/src/Indexer/Debugadapter.php';
Is this really needed?

2022-06-21 08:37 UTC, laoneo commented on administrator/components/com_finder/src/Controller/IndexerController.php
> +			$output .= '<fieldset><legend>' . Text::_('COM_FINDER_INDEXER_FIELDSET_ATTRIBUTES') . '</legend>';
This output stuff should be in a layout.

2022-06-21 08:37 UTC, laoneo commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +		$this->db = Factory::getDbo();
Please use the databaseaware trait.

2022-06-21 08:37 UTC, laoneo commented on administrator/components/com_finder/src/Model/ItemModel.php
> +		$db = $this->getDbo();
Use $this->getDatabase()

2022-06-21 08:41 UTC, Hackwar commented on administrator/components/com_finder/src/Controller/IndexerController.php
> +			require_once JPATH_ADMINISTRATOR . '/components/com_finder/src/Indexer/Debugadapter.php';
Yes, since we can't override the original class and the debug feature has no business in the original class, this is necessary.

2022-06-21 08:43 UTC, Hackwar commented on administrator/components/com_finder/src/Controller/IndexerController.php
> +			$output .= '<fieldset><legend>' . Text::_('COM_FINDER_INDEXER_FIELDSET_ATTRIBUTES') . '</legend>';
I disagree here. This is not something that can be used in production anywhere and should never be modified. This is debug code, similar to the debug plugin, which doesn't have layouts either.

2022-06-21 08:54 UTC, Hackwar commented on administrator/components/com_finder/src/Model/ItemModel.php
> +		$db = $this->getDbo();
done

2022-06-21 08:54 UTC, Hackwar commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +		$this->db = Factory::getDbo();
fixed.

2022-06-21 09:04 UTC, nibra commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +abstract class Adapter extends CMSPlugin
Should be `DebugAdapter` (and the filename `DebugAdapter.php`) to support PSR-4

2022-06-21 09:07 UTC, nibra commented on administrator/components/com_finder/src/Indexer/Debugindexer.php
> +class Debugindexer extends Indexer
`DebugIndexer` (`DebugIndexer.php`)

2022-06-21 09:08 UTC, Hackwar commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +abstract class Adapter extends CMSPlugin
This is NOT supposed to be autoloaded. The decisions for the file- and classname were deliberate. Again, it is debug code, supposed to inject itself into existing code without breaking it, not meant for production, but for people to debug their finder plugins.

2022-06-21 10:24 UTC, nibra commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +abstract class Adapter extends CMSPlugin
Nevertheless should names follow the naming convention. Both files and classes.

2022-06-23 22:32 UTC, chmst commented
I am confused. 

I expected that I can select an item in the overview
then click on the debug action
then cone to the checker view where the Id and  type of the plugin are already known from the list view
and there is no need for input (can be disabled)

As it is now, I would not know how to find the Id (of course it is in the slug, but mybe users don't know that.

2022-07-04 15:37 UTC, Hackwar commented on administrator/components/com_finder/src/Indexer/Debugindexer.php
> +class Debugindexer extends Indexer
Done.

2022-07-04 15:42 UTC, Hackwar commented on administrator/components/com_finder/src/Indexer/Debugadapter.php
> +abstract class Adapter extends CMSPlugin
I changed this and it should be better now.

2022-07-04 15:44 UTC, Hackwar commented on administrator/components/com_finder/src/Controller/IndexerController.php
> +			require_once JPATH_ADMINISTRATOR . '/components/com_finder/src/Indexer/Debugadapter.php';
Actually, this is not necessary and I fixed it. Thanks.

2022-07-04 15:56 UTC, Hackwar commented on administrator/components/com_finder/src/Controller/IndexerController.php
> +			$output .= '<fieldset><legend>' . Text::_('COM_FINDER_INDEXER_FIELDSET_ATTRIBUTES') . '</legend>';
As I wrote, this is just for debugging purposes, thus the output here is okay.

2023-02-01 19:22 UTC, Quy commented
Leave ID blank or enter a non-existing ID.

![36753](https://user-images.githubusercontent.com/368084/216141986-86b351c2-5608-4fb9-8f3f-8f62e2a4088a.jpg)

2023-03-06 13:47 UTC, carlitorweb commented
@Hackwar can you fix the conflicting file here, to give a test

2023-03-28 07:58 UTC, laoneo commented
Thank you for your contribution, unfortunately the 4.4-dev branch doesn't get new features. When #40181 is merged this pr should be rebased to 5.0-dev. Thanks for understanding.

2023-04-03 09:57 UTC, HLeithner commented
I would mark all debuging functions/class "@internal" since it's not intended to be used by 3rd party developer.

2023-04-07 13:20 UTC, HLeithner requested changes
I would like to merge this in to j5 do we already have documentation?

2023-04-07 13:20 UTC, HLeithner commented on administrator/components/com_finder/src/Controller/IndexerController.php
> +     * @since   __DEPLOY_VERSION__
```suggestion
     * @since   __DEPLOY_VERSION__
     * @internal
```

2023-04-07 13:20 UTC, HLeithner commented on administrator/components/com_finder/src/Indexer/DebugAdapter.php
> + * @since  __DEPLOY_VERSION__
```suggestion
 * @since  __DEPLOY_VERSION__
 * @internal
```

2023-04-07 13:20 UTC, HLeithner commented on administrator/components/com_finder/src/Indexer/DebugIndexer.php
> + * @since  __DEPLOY_VERSION__
```suggestion
 * @since  __DEPLOY_VERSION__
 * @internal
```

2023-04-17 09:59 UTC, Hackwar commented
> I would like to merge this in to j5 do we already have documentation?

No, I need to write the complete documentation for Smart Search still.

2023-05-29 08:16 UTC, merged

2023-05-29 08:16 UTC, HLeithner commented
Thanks