[4.1] Remove FLoC
joomla/joomla-cms pull request #36855
Opened 2022-01-26 10:19 UTC by brianteeman

Pull Request for Issue #36853 

Remove useless code

2022-01-26 11:10 UTC, nikosdion requested changes
Just a small change necessary to remove the Post-Installation Message on existing sites which already have the message installed. Otherwise resetting the messages would show two problem language strings.

2022-01-26 11:10 UTC, nikosdion commented on installation/sql/mysql/supports.sql
> -SELECT `extension_id`, 'COM_ADMIN_POSTINSTALL_MSG_FLOC_BLOCKER_TITLE', 'COM_ADMIN_POSTINSTALL_MSG_FLOC_BLOCKER_DESCRIPTION', '', 'com_admin', 1, 'message', '', '', '', '', '3.9.27', 1 FROM `#__extens
We should add a DELETE FROM in a new SQL update file for existing sites which already have the post–installation message.

2022-01-26 11:11 UTC, brianteeman commented on installation/sql/mysql/supports.sql
> -SELECT `extension_id`, 'COM_ADMIN_POSTINSTALL_MSG_FLOC_BLOCKER_TITLE', 'COM_ADMIN_POSTINSTALL_MSG_FLOC_BLOCKER_DESCRIPTION', '', 'com_admin', 1, 'message', '', '', '', '', '3.9.27', 1 FROM `#__extens
i already did

2022-01-26 11:12 UTC, brianteeman commented on installation/sql/mysql/supports.sql
> -SELECT `extension_id`, 'COM_ADMIN_POSTINSTALL_MSG_FLOC_BLOCKER_TITLE', 'COM_ADMIN_POSTINSTALL_MSG_FLOC_BLOCKER_DESCRIPTION', '', 'com_admin', 1, 'message', '', '', '', '', '3.9.27', 1 FROM `#__extens
I just forgot to commit the new files

2022-01-26 13:22 UTC, richard67 commented on installation/sql/mysql/supports.sql
> -SELECT `extension_id`, 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_TITLE', 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_BODY', 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_ACTION', 'plg_
Why are line 281 and 282 deleted here?

2022-01-26 13:28 UTC, Hackwar commented on htaccess.txt
> -</IfModule>
I doubt that this line should be removed as well. 😃

2022-01-26 13:40 UTC, nikosdion commented on installation/sql/mysql/supports.sql
> -SELECT `extension_id`, 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_TITLE', 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_BODY', 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_ACTION', 'plg_
I think @brianteeman got confused here. The HTTP Headers plugin is unrelated to Block FLoC.

The thing is that this Global Configuration (application level!) option is implemented in that _optional_ system plugin (defying all logic) which is probably what led to the confusion here.

2022-01-26 13:42 UTC, richard67 commented on installation/sql/mysql/supports.sql
> -SELECT `extension_id`, 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_TITLE', 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_BODY', 'PLG_SYSTEM_HTTPHEADERS_POSTINSTALL_INTRODUCTION_ACTION', 'plg_
I think he just accidentally removed those rows.

2022-01-26 14:03 UTC, richard67 approved these changes

2022-01-26 14:28 UTC, wilsonge approved these changes

2022-01-26 14:37 UTC, brianteeman commented
@zero-24 should I also backport this to j3?

2022-01-26 19:35 UTC, zero-24 commented
Yes please, from my understanding it should be merged up from 3.10-dev anyway.

2022-01-26 20:00 UTC, brianteeman commented
I will do a pr for 3.10 as well. Its a different pr so merging up wouldnt really help

2022-01-26 20:05 UTC, zero-24 commented
Thanks :)

2022-01-27 16:33 UTC, Quy commented
I have tested this item :white_check_mark: successfully on ff448095933099aa369c1321cafb4d5743d1f236<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36855">issues.joomla.org/tracker/joomla-cms/36855</a>.</sub>

2022-01-29 07:36 UTC, alikon commented
I have tested this item :white_check_mark: successfully on ff448095933099aa369c1321cafb4d5743d1f236<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36855">issues.joomla.org/tracker/joomla-cms/36855</a>.</sub>

2022-01-29 07:36 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36855">issues.joomla.org/tracker/joomla-cms/36855</a>.</sub>

2022-02-20 20:44 UTC, bembelimen commented
I've used the upmerged fix in #37104 
Thanks for the removal!

2022-02-20 20:44 UTC, closed without merging