Fix#36881
joomla/joomla-cms pull request #36892
Opened 2022-01-30 08:06 UTC by akshitrattan

Pull Request for Issue #36881 .

### Summary of Changes
Made the create-new-folder modal in the media managern keyboard focussed

### Testing Instructions
open the media manager and try pressing tab or shift+tab the focus doesn't shift to the backdrop and stays in the modal

### Actual result BEFORE applying this Pull Request
on pressing tab the keyboard focus instead of remaining in the modal shifts to the modal backdrop decreasing its accessibilty

### Expected result AFTER applying this Pull Request
the keyboard focus remains in the modal

### Documentation Changes Required
no changes required
P.S.- This might have solved the same problem with other modals as I made the changes in administrator/components/com_media/resources/scripts/components/modals/modal.vue

2022-01-30 09:40 UTC, brianteeman commented
Please update with a meaningful title

2022-01-30 09:52 UTC, akshitrattan commented
> Please update with a meaningful title

I changed the title, could you please check and confirm whether the title is appropriate

2022-01-30 09:56 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on 5351f6d801dcc23943c5e167e78e15d36306064e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36892">issues.joomla.org/tracker/joomla-cms/36892</a>.</sub>

2022-01-30 09:58 UTC, brianteeman commented
The new title is better - thanks

unfortunately my tests do not match your gif and there are two problems.

1. Focus should not be moved to the X close
2. Can never reach the Create button

![media](https://user-images.githubusercontent.com/1296369/151695078-3af50213-2695-4977-a03e-0e7d97673eaf.gif)

2022-01-30 10:01 UTC, akshitrattan commented
> The new title is better - thanks
> 
> unfortunately my tests do not match your gif and there are two problems.
> 
> 1. Focus should not be moved to the X close
> 2. Can never reach the Create button
> 
> ![media](https://user-images.githubusercontent.com/1296369/151695078-3af50213-2695-4977-a03e-0e7d97673eaf.gif)

I can solve the first problem, but i want a clarification that when the modal opens, do you want the focus to be at folder name input and not the close button

2022-01-30 10:04 UTC, akshitrattan commented
> The new title is better - thanks
> 
> unfortunately my tests do not match your gif and there are two problems.
> 
> 1. Focus should not be moved to the X close
> 2. Can never reach the Create button
> 
> ![media](https://user-images.githubusercontent.com/1296369/151695078-3af50213-2695-4977-a03e-0e7d97673eaf.gif)

the second problem is mainly becuase in the variable 'focusableElements' the button:not([disabled]) is there, this means that when the we enter something in the folder name input, the DOM is updated and the button is enabled however, the funtion i created is called before the DOM is updated and thus it is not able to catch the updated DOM

2022-01-30 10:16 UTC, brianteeman commented
> I can solve the first problem, but i want a clarification that when the modal opens, do you want the focus to be at folder name input and not the close button

If I remember correctly you do NOT need to do anything to set the focus on load at all.

2022-01-30 10:18 UTC, akshitrattan commented
> Member

It was necessary to put the focus on the modal explicitly once it is opened because otherwise focus was set to backdrop buttons

2022-01-30 10:20 UTC, brianteeman commented
Then you should look at how other (not com_media) modals behave

2022-01-30 10:25 UTC, akshitrattan commented
> Then you should look at how other (not com_media) modals behave

I did that is why i made the changes in the modal.vue and not create-folder-modal.vue particulary 
If you could test the functionality with other modals then it would be great help, as it would tell whether the changes were applied to all the modals or just the create-folder-modal

2022-01-30 10:32 UTC, brianteeman commented
I meant look at modals in other joomla components

2022-01-30 10:36 UTC, akshitrattan commented
> I meant look at modals in other joomla components
oh sorry, my bad!
@dgrammatiko provided certain links to code snippets of joomla modal component in the comments of the issue,  the code I wrote is in a way inspired from that code snippet, as in they work the same

2022-01-30 10:39 UTC, akshitrattan commented
when in folder name input section, if we press the enter key it automatically shifts to the create button and the folder is created

2022-01-30 10:55 UTC, dgrammatiko requested changes

2022-01-30 10:55 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
This will be a memory leak. You need to create another method before opened, let's name it `onKeyPress` like: 

``js
onKeyPress(e) {
const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
     if (!isTabPressed) {
       return;
     }
     if (e.shiftKey) { // if shift key pressed for shift + tab combination
       if (document.activeElement === firstFocusableElement) {
         lastFocusableElement.focus(); // add focus for the last focusable element
         e.preventDefault();
       }
     } else if (document.activeElement === lastFocusableElement) {
       firstFocusableElement.focus();
       e.preventDefault();
     }
}```

and change this line to `document.addEventListener('keydown', this.onKEyPress);`

Also you need to add after `mounted` a method `unmounted` and remove the listener like `document.removeEventListener('keydown', this.onKEyPress);`

Also combine the keydown and onKeyPress

2022-01-30 10:58 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
okay, thank you, I'll try implementing the changes and then get back to you

2022-01-30 11:06 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
could you please elaborate, on what you mean by "combining keydown and onKeyPress"

2022-01-30 11:08 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
Check line 113: 

```js
    /* Handle keydown events */
    onKeyDown(event) {
      if (event.keyCode === 27) {
        this.close();
      }
    },
```

You can add this to the new method onKeyPress...

2022-01-30 11:15 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
also what if i add a 
`@keydown.shift.tab.prevent=""` 
to the header attribute  and 
`@keydown.tab.exact.prevent=""`

2022-01-30 11:35 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
@dgrammatiko the changes don't work the media manger goes to its initial state, that is the modal gets out of focus again

2022-01-30 16:55 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
it is not working because the onKeyPress() function cannot access the variables 'focusableElements' , 'firstfocusableElement' etc as they are out of scope

2022-01-30 17:00 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
`const focusableElements` -> `this.focusableElements` ...

2022-02-01 06:54 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +        document.addEventListener('keydown', (e) => {
changes still don't work

2022-02-01 18:56 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +          }
`this.removeEventListener('keydown', arguments.callee);`
@dgrammatiko can this be a viable option to solve the memory leak problem, the code works fine on compilation with this extra line

2022-02-01 19:13 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +          }
Nope: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee

2022-02-01 19:15 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +          }
You can check this https://github.com/bootstrap-vue/bootstrap-vue/tree/dev/src/components/modal for some inspiration

2022-02-03 11:26 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +          }
I tried a few things and what I realised is that the problem is coming while declaring global variables, as such there is no error on compilation but when I run the program nothing seems to work, and the only changes I made in my previous code is that, declaring global variables under data() and then using the 'this' keyword to access them

2022-02-03 15:29 UTC, akshitrattan commented
@brianteeman @dgrammatiko I have solved all the issues with the PR

2022-02-09 14:50 UTC, HarshJaiswani commented
I have tested this item :white_check_mark: successfully on 20be5684e8520216745f479f406d88468be143a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36892">issues.joomla.org/tracker/joomla-cms/36892</a>.</sub>

2022-02-11 16:10 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on 20be5684e8520216745f479f406d88468be143a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36892">issues.joomla.org/tracker/joomla-cms/36892</a>.</sub>

2022-02-11 16:11 UTC, RickR2H commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36892">issues.joomla.org/tracker/joomla-cms/36892</a>.</sub>

2022-02-11 16:38 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +      const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
This code
```js
      const focusableElements = 'button:not([disabled]), [href], input:not([disabled]), select, textarea, [tabindex]:not([tabindex="-1"])';
       const modal = document.querySelector('.modal-content');
       const firstFocusableElement = modal.querySelectorAll(focusableElements)[0];
       const focusableContent = modal.querySelectorAll(focusableElements);
       const lastFocusableElement = focusableContent[focusableContent.length - 1];
```
is running on each keypress and it's extremely unoptimised. Few lines above on the `mounted` method those variables are evaluated but wrong stored as `const` instead of `this.` so they could be reused on the `onKeyPress` method...

2022-02-12 08:41 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +      const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
I'm working on it

2022-02-12 17:02 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +      const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
I tried declaring the variables using the `this` keyword in the `mounted` method and completely removed the variables declared in the `onKeyPress` method and everything seems to work fine, but the previous problem of the focus specifically not shifting to the 'create' option persists

2022-02-12 17:10 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +      const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
You have couple options: https://stackoverflow.com/questions/38148297/in-vue-js-can-a-component-detect-when-the-slot-content-changes

2022-02-12 17:17 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +      const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
thanks, i'll try implementing these

2022-02-12 17:22 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +          }
There are NO global variables here, everything is scoped. Once the slotted components initialise you have to redeclare the variables, thus I gave you the link above which explains how that could be done

2022-02-13 08:19 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +      const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
> You have couple options: https://stackoverflow.com/questions/38148297/in-vue-js-can-a-component-detect-when-the-slot-content-changes

do we have the mutation observer API in the projects npm modules I couldn't find it when I ran `npm list` in the project directory

2022-02-13 13:35 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +      const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

2022-02-16 07:42 UTC, akshitrattan commented on administrator/components/com_media/resources/scripts/components/modals/modal.vue
> +      const isTabPressed = e.key === 'Tab' || e.keyCode === 9;
<img width="1309" alt="Screenshot 2022-02-16 at 1 11 31 PM" src="https://user-images.githubusercontent.com/78909027/154218378-fb376cf8-4f45-4c07-ab96-193bde3f4ab5.png">
I am using this code in the mounted method could you cross if I'm doing something wrong because the  problem persists

2022-02-16 12:18 UTC, akshitrattan commented
@dgrammatiko I updated the PR

2022-02-22 14:41 UTC, drmenzelit commented
@akshitrattan can you please check your PR? It is out-of-date

2022-02-22 14:42 UTC, akshitrattan commented
> @akshitrattan can you please check your PR? It is out-of-date

Done!!

2022-02-22 16:06 UTC, drmenzelit commented
@akshitrattan it seems you have some code style problems on your Javascript, the build of the package is failing with this errors: https://ci.joomla.org/joomla/joomla-cms/51921/1/25

2022-02-22 16:11 UTC, akshitrattan commented
> @akshitrattan it seems you have some code style problems on your Javascript, the build of the package is failing with this errors: https://ci.joomla.org/joomla/joomla-cms/51921/1/25

yeah, I am working on those issues, and I did solve a few of them, but there is a particular issue regarding the usage of destructured arrays that I can't seem to solve because I'm not gonna lie, I am a bit unfamiliar with that concept, but I am under the process of researching about it and solving the issue, I hope that works fine?

2022-02-22 17:13 UTC, akshitrattan commented
@drmenzelit I have removed all the javascript errors

2022-05-18 13:44 UTC, akshitrattan commented
@drmenzelit @dgrammatiko I have successfully solved the issue!!

2022-06-27 13:06 UTC, HLeithner commented
This pull request has automatically rebased to 4.2-dev.

2022-06-28 08:54 UTC, drmenzelit commented
@akshitrattan @dgrammatiko if the vue code is now ok, please mark the conversation as resolved

2022-10-23 09:34 UTC, drmenzelit commented
Closing this in favor of https://github.com/joomla/joomla-cms/pull/39042

2022-10-23 09:34 UTC, closed without merging