WebAuthn hints
joomla/joomla-cms pull request #37203
Opened 2022-03-05 00:47 UTC by kitepascal

Pull Request for Issue # .

### Summary of Changes

### Testing Instructions

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Documentation Changes Required

2022-03-05 06:35 UTC, brianteeman commented on administrator/language/en-GB/plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_FIELD_DESC="Lets you manage passwordless login methods using the W3C Web Authentication standard. You need a supported browser and authenticator (eg Google Chrome or Firefox with
Please change to just `<br>` and end the text with a period

2022-03-05 07:33 UTC, tecpromotion commented on administrator/language/en-GB/plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_FIELD_DESC="Lets you manage passwordless login methods using the W3C Web Authentication standard. You need a supported browser and authenticator (eg Google Chrome or Firefox with
Perhaps also replace Apple as the manufacturer with the name of the operating system "iOS".
Should Linux be named?

2022-03-05 12:19 UTC, kitepascal commented
Lets wait for @nikosdion s PR and some more tests.

Joomlas language override fields convert <br> to <br /> on save/reload, so I accepted that.

Should we also link @ceford s detail-documentation directly from PLG_SYSTEM_WEBAUTHN_FIELD_DESC ?

2022-03-05 12:40 UTC, brianteeman commented
> Joomlas language override fields convert < br > to < br /> on save/reload, so I accepted that.


That's a bug which hopefully will get fixed. Please make the requested chanage

2022-03-05 13:06 UTC, kitepascal reviewed
![image](https://user-images.githubusercontent.com/23017542/156884346-4e243d56-6adc-4058-bea6-b1cc07ab87b2.png)

2022-03-05 13:34 UTC, tecpromotion commented
There are unnecessary spaces before and after <br>. Please delete.

Furthermore, I see no need for the last sentence and the link here.

2022-03-05 13:58 UTC, kitepascal commented
I got used to add EOL spaces for anti-glued sentences if somehow line breaks get lost.

Unlikely here, so I will remove them (cannot hurt anyway).

For the "read more" link, last sentence - I think it is good and very, very useful to have them in scope, like "read more" in frontend. Its just following the intro/short form.

The top right help button is not really in scope and that last sentence with link does not hurt anything/anybody - rather the opposite.
The translations (+ possibly link(s)) and also the help button contents have to be updated anyway, if core Strings get improved for usability.

Maybe theres another 3rd party opinion on that - updated PR will follow.

2022-03-05 19:05 UTC, tecpromotion requested changes

2022-03-05 19:05 UTC, tecpromotion commented on administrator/language/en-GB/plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_FIELD_DESC="Lets you manage passwordless login methods using the W3C Web Authentication standard. You need a supported browser and authenticator (eg Google Chrome or Firefox with
```suggestion
PLG_SYSTEM_WEBAUTHN_FIELD_DESC="Lets you manage passwordless login methods using the W3C Web Authentication standard. You need a supported browser and authenticator (eg Google Chrome or Firefox with a FIDO2 certified security key).<br><br><strong>MacOS/iOS/watchOS:</strong> Touch/Face ID.<br><strong>Windows:</strong> Hello (Fingerprint / Facial Recognition / PIN).<br><strong>Android:</strong> Biometric screen lock.<br><br>You can find more details in the <a href='https://docs.joomla.org/Special:MyLanguage/WebAuthn_Passwordless_Login' target='_blank' rel='noopener noreferrer'>WebAuthn Passwordless Login documentation</a>."
```

2022-03-05 19:05 UTC, tecpromotion commented on administrator/language/en-GB/plg_system_webauthn.sys.ini
> +PLG_SYSTEM_WEBAUTHN_DESCRIPTION="Enables passwordless authentication using Apple Touch/Face ID, Windows Hello, biometric screen lock on Android or other WebAuthn-compatible devices. Please note that
```suggestion
PLG_SYSTEM_WEBAUTHN_DESCRIPTION="Enables passwordless authentication using the W3C Web Authentication (WebAuthn) API. Please note that the WebAuthn tab in the user profile editor and the WebAuthn login buttons will only be displayed if the user is accessing the site over HTTPS. Furthermore, registering WebAuthn authenticators and using them to log into your site will only work when your site is using a valid certificate, signed by a Certificate Authority the user's browser trusts."
```

2022-03-06 00:03 UTC, kitepascal commented
Thx @tecpromotion - to change only the one string makes sense to save the translators crowd from unnecessary work (y)

2022-03-06 00:25 UTC, Quy commented on administrator/language/en-GB/plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_FIELD_DESC="Lets you manage passwordless login methods using the W3C Web Authentication standard. You need a supported browser and authenticator (eg Google Chrome or Firefox with
```suggestion
PLG_SYSTEM_WEBAUTHN_FIELD_DESC="Lets you manage passwordless login methods using the W3C Web Authentication standard. You need a supported browser and authenticator (eg Google Chrome or Firefox with a FIDO2 certified security key).<br><br><strong>MacOS/iOS/watchOS:</strong> Touch/Face ID.<br><strong>Windows:</strong> Hello (Fingerprint / Facial Recognition / PIN).<br><strong>Android:</strong> Biometric screen lock.<br><br>You can read about more possibilities and get detailed explanations in our Wiki:<br><a href=\"https://docs.joomla.org/Special:MyLanguage/WebAuthn_Passwordless_Login\" title=\"How to use WebAuthn Passwordless Login\" target=\"_blank\"  rel=\"noopener noreferrer\">https://docs.joomla.org/Special:MyLanguage/WebAuthn_Passwordless_Login</a>."
```

2022-03-06 09:54 UTC, tecpromotion approved these changes
thanks @kitepascal

2022-03-06 09:54 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on a4a2140fca76d957e5fffdf76aad931c29136dec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37203">issues.joomla.org/tracker/joomla-cms/37203</a>.</sub>

2022-03-06 10:13 UTC, RickR2H commented
I have tested this item :white_check_mark: successfully on a4a2140fca76d957e5fffdf76aad931c29136dec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37203">issues.joomla.org/tracker/joomla-cms/37203</a>.</sub>

2022-03-06 10:13 UTC, RickR2H commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37203">issues.joomla.org/tracker/joomla-cms/37203</a>.</sub>

2022-03-12 10:38 UTC, merged

2022-03-12 10:38 UTC, bembelimen commented
Thx