[4] scheduler action log
joomla/joomla-cms pull request #37484
Opened 2022-04-04 15:26 UTC by alikon

### Summary of Changes
Added action log entry  when a task is executed 

### Testing Instructions
enable log schedualer
run some tasks 

### Actual result BEFORE applying this Pull Request
N/A

### Expected result AFTER applying this Pull Request
![image](https://user-images.githubusercontent.com/181681/161579004-7b249418-2548-4393-a614-c75b50416ec5.png)

2022-04-04 16:28 UTC, Kostelano commented
Action outcome events must also be translated into other languages.

2022-04-04 16:53 UTC, alikon commented
sure good spot

2022-04-04 19:06 UTC, Kostelano requested changes

2022-04-04 19:06 UTC, Kostelano commented on administrator/language/en-GB/plg_actionlog_joomla.ini
> +PLG_ACTIONLOG_JOOMLA_TASK="Task <a href='{tasklink}'>{taskname}</a> #{times} runned for {duration} seconds <span class='badge bg-success'>{action}</span>"
```suggestion
PLG_ACTIONLOG_JOOMLA_TASK_COMPLETED="Task <a href='{tasklink}'>{taskname}</a> #{times} runned for {duration} seconds <span class='badge bg-success'>{action}</span>"
```

2022-04-04 19:06 UTC, Kostelano commented on plugins/actionlog/joomla/joomla.php
> +		$this->addLog([$message], 'PLG_ACTIONLOG_JOOMLA_TASK', $context, $user->id);
```suggestion
		$this->addLog([$message], 'PLG_ACTIONLOG_JOOMLA_TASK_COMPLETED', $context, $user->id);
```

2022-04-09 17:00 UTC, Quy commented
Create a task.
Click `Run Test` button.

> Argument 1 passed to PlgActionlogJoomla::onTaskExecuteSuccess() must be an instance of Task, instance of Joomla\Component\Scheduler\Administrator\Task\Task given, called in \libraries\src\Plugin\CMSPlugin.php on line 285

2022-04-10 03:14 UTC, Quy commented on administrator/language/en-GB/plg_actionlog_joomla.ini
> +PLG_ACTIONLOG_JOOMLA_TASK_KO="Failure"
```suggestion
PLG_ACTIONLOG_JOOMLA_TASK_COMPLETED="Task <a href='{tasklink}'>{taskname}</a> #{times} executed for {duration} seconds <span class='badge bg-success'>{action}</span>"
PLG_ACTIONLOG_JOOMLA_TASK_FAIL="Failed"
PLG_ACTIONLOG_JOOMLA_TASK_FAILURE="Task <a href='{tasklink}'>{taskname}</a> #{times} executed for {duration} seconds <span class='badge bg-danger'>{action}</span>"
PLG_ACTIONLOG_JOOMLA_TASK_RESUME="Task <a href='{tasklink}'>{taskname}</a> #{times} executed for {duration} seconds <span class='badge bg-secondary'>{action}</span>"
PLG_ACTIONLOG_JOOMLA_TASK_SUCCESS="Completed"
```

2022-04-10 13:17 UTC, ditsuke commented
This is something we've needed for a long time now, but something feels off about logging scheduler events to the "User Action Log". In my opinion these logs shouldn't come under user actions since the actions are being performed automatically by the Scheduler, instead they should go under a separate space for automated system actions unless the task is being executed manually.

2022-05-25 11:47 UTC, closed without merging