Fix mismatch in column and sort table
joomla/joomla-cms pull request #37527
Opened 2022-04-10 11:20 UTC by shazmasiddiqui

Changes filter name to 'Title' to match with the column name
PARTIAL Pull Request for Issue https://github.com/joomla/joomla-cms/issues/37499 .

### Before
![before](https://user-images.githubusercontent.com/43249198/162615560-1c912b16-7635-47fd-868e-08046f1f9f5f.png)

### After
![after](https://user-images.githubusercontent.com/43249198/162615574-ce513ea3-2ebd-466e-b8fd-1d1cc217ab8c.png)

2022-04-10 11:54 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 346f733ea34906b10dce20c6076a3917598409a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37527">issues.joomla.org/tracker/joomla-cms/37527</a>.</sub>

2022-04-10 14:35 UTC, Kostelano requested changes

2022-04-10 14:35 UTC, Kostelano commented on administrator/language/en-GB/com_languages.ini
>  COM_LANGUAGES_HEADING_LANGUAGE_DESC="Language descending"
```suggestion
```

2022-04-10 14:36 UTC, Kostelano commented on administrator/language/en-GB/com_languages.ini
>  COM_LANGUAGES_HEADING_LANGUAGE_DESC="Language descending"
These constants are no longer used

2022-04-11 13:41 UTC, Quy commented
I have tested this item :white_check_mark: successfully on ecad4ed990f275a404d2cb38b88642395bc694ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37527">issues.joomla.org/tracker/joomla-cms/37527</a>.</sub>

2022-04-11 14:41 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on ecad4ed990f275a404d2cb38b88642395bc694ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37527">issues.joomla.org/tracker/joomla-cms/37527</a>.</sub>

2022-04-11 14:44 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37527">issues.joomla.org/tracker/joomla-cms/37527</a>.</sub>

2022-04-12 01:24 UTC, merged

2022-04-12 01:24 UTC, bembelimen commented
Thx