Require custom task cron execution rules to be filled out
joomla/joomla-cms pull request #37536
Opened 2022-04-11 18:54 UTC by MagnusSinger

Pull Request for Issue #37313

### Summary of Changes
When you create a new scheduled task and select custom execution rules, and you don't specify a execution time, you can't save it now

### Testing Instructions
Create Demo Task - Sleep
Select Cron Expression Advanced as Execution Rule
Do not select all values in area Cron match
Try to save, Joomla will show you that you still have empty fields

### Actual result BEFORE applying this Pull Request
You were able to click save, but then ran into an error

### Expected result AFTER applying this Pull Request
You see that there are required fields left and you cannot save

### Documentation Changes Required
None

2022-04-11 19:11 UTC, richard67 commented
@MagnusSinger My comment from another, closed PR for the same issue also applies here, see https://github.com/joomla/joomla-cms/pull/37350#issuecomment-1075529830 .

Also the testing instructions should include a test that nothingness broken for other kinds of execution rules that the advanced cron expression .

2022-04-11 19:57 UTC, MagnusSinger commented
@richard67 thanks for the hint, I'll have a look at it

2022-04-12 09:49 UTC, bembelimen commented
See: https://github.com/joomla/joomla-cms/pull/37537#issuecomment-1096275706

2022-04-12 19:53 UTC, MagnusSinger commented
@bembelimen @richard67 I tried to control it now via JS, please let me know if this is okay

2022-04-12 19:55 UTC, brianteeman commented on build/media_source/com_scheduler/js/admin-view-config-helper.es6.js
> + * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

its a new file

2022-04-14 12:09 UTC, richard67 commented
@dgrammatiko Could you do a quick review on the JS in this PR? To me it looks good, but I am not really a JS expert. Thanks in advance.

2022-04-14 12:12 UTC, richard67 commented
@MagnusSinger Could you extend your testing instructions by a test if other execution rules than advanced cron expressions don't require the cron parameters (i.e. mainly a test for your last change)? Thanks in advance. In general it's important that testing instructions don't cover only the test for the fixed issue but also the test that other behaviour of the changed code is not broken.

2022-04-14 12:17 UTC, bembelimen commented
We need for sure also a server side validation for this (e.g. in the models validate method)

2023-04-25 21:04 UTC, dgrammatiko requested changes, later dismissed

2023-04-25 21:04 UTC, dgrammatiko commented on build/media_source/com_scheduler/js/admin-view-config-helper.es6.js
> +/**
can we replace the JS with this:

```js
/**
 * @copyright   (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

if (!window.Joomla) {
  throw new Error('Joomla API was not properly initialised!');
}

const ruleTypesElement = document.querySelector('#jform_execution_rules_rule_type');

if (!ruleTypesElement) {
  return;
}

const elements = [
  '#jform_execution_rules_cron_expression_minutes',
  '#jform_execution_rules_cron_expression_hours',
  '#jform_execution_rules_cron_expression_days_month',
  '#jform_execution_rules_cron_expression_months',
  '#jform_execution_rules_cron_expression_days_week'
];

function toggleRequired(elements, process = 'add') {
  if (!['add', 'remove'].contains(process)) {
    return;
  }

  elements.forEach(elementSelector => {
    const element = document.querySelector(elementSelector);
    if (!element) {
      return;
    }
    const label = document.querySelector(`${elementSelector}-lbl`);
    if (process === 'add') {
      element.setAttribute('required', '');
      element.classList.add('required');
      if (label) {
        label.classList.add('required');
      }
    } else {
      element.setAttribute('required', '');
      element.classList.remove('required');
      if (label) {
        label.classList.remove('required');
      }
    }

  });
}

if (ruleTypesElement.value === 'cron-expression') {
  toggleRequired(elements, 'add');
} else {
  toggleRequired(elements, 'remove');
}

ruleTypesElement.addEventListener('change', (e) => {
  const selectValue = e.target.value;
  if (selectValue === 'cron-expression') {
    toggleRequired(elements, 'add');
  } else {
    toggleRequired(elements, 'remove');
  }
});
```

Thanks

2023-04-26 12:37 UTC, MagnusSinger commented on build/media_source/com_scheduler/js/admin-view-config-helper.es6.js
> +/**
Sure, I'll have a look at it and change it soon

2023-05-02 16:30 UTC, HLeithner commented
This pull request has been automatically rebased to 4.3-dev.

2023-05-06 21:09 UTC, MagnusSinger commented on build/media_source/com_scheduler/js/admin-view-config-helper.es6.js
> +/**
Okay, so I reviewed your code and added it, thanks!

2023-09-30 22:45 UTC, HLeithner commented
This pull request has been automatically rebased to 4.4-dev.

2024-02-23 17:54 UTC, n3t commented on build/media_source/com_scheduler/js/admin-view-config-helper.es6.js
> +  if (!['add', 'remove'].contains(process)) {
Shouldn't be be includes instead of contains?

2024-02-23 18:35 UTC, magnussinger commented on build/media_source/com_scheduler/js/admin-view-config-helper.es6.js
> +  if (!['add', 'remove'].contains(process)) {
Yes I think you're right

2024-10-21 15:29 UTC, Jan-at-tetronik commented
This issue still persists even in version 5.2. The "Cron Expression (Advanced)" option remains virtually unusable that way.

2025-01-16 08:58 UTC, Hackwar commented
@magnussinger Can you please fix the conflicts?

2025-04-15 16:17 UTC, HLeithner commented
This pull request has been automatically rebased to 5.3-dev.

2025-10-15 17:05 UTC, HLeithner commented
This pull request has been automatically rebased to 5.4-dev.

2025-10-23 15:05 UTC, richard67 commented
I've allowed myself to fix the merge conflict coming from the removal of the es5 scripts in the base branch.

@magnussinger Could you check @n3t 's [review comment](https://github.com/joomla/joomla-cms/pull/37536#discussion_r1500999233)? Is there something to be changed in this PR?

2025-10-23 15:17 UTC, n3t commented
There is no function Array.contains in Javascript, only Array.includes, therefore instead of 
`['add', 'remove'].contains(process)` should be `['add', 'remove'].includes(process)`...

2025-10-23 15:30 UTC, richard67 commented on build/media_source/com_scheduler/js/admin-view-config-helper.es6.js
> +  if (!['add', 'remove'].contains(process)) {
```suggestion
  if (!['add', 'remove'].includes(process)) {
```
Add suggestion by @n3t .

2025-10-23 15:41 UTC, richard67 commented
> There is no function Array.contains in Javascript, only Array.includes, therefore instead of `['add', 'remove'].contains(process)` should be `['add', 'remove'].includes(process)`...

@n3t Thanks. I have fixed that.

2025-10-24 14:59 UTC, muhme commented
I tried to reproduce the problem, but the error from the issue https://github.com/joomla/joomla-cms/issues/37313 was no more seen. If the cron fields are not selected there is a clear error message without this PR:
<img width="480" height="139" alt="before_PR" src="https://github.com/user-attachments/assets/2fffdb3b-9dea-4521-af3d-bd5fa78b54ba" />

@astridx Could you please try by your own with 5.4?

With this PR there are the individual error messages: 
<img width="1302" height="399" alt="with_PR" src="https://github.com/user-attachments/assets/67cff75c-fe08-4a0c-ba6c-ade570d94ed1" />

If everything works, shall we use standard error handling to standardise the user experience and reduce the code, and close this PR?

2025-10-30 09:52 UTC, richard67 commented
@astridx As the issue #37313 which this PR claims to solve was reported by you: Can you still reproduce the issue on Joomla 5.4? It seems that has been fixed meanwhile so this PR here would not be needed anymore.

2025-11-28 14:28 UTC, muhme commented
Dear @magnussinger and @astridx We would kindly suggest closing this pull request, as it seems that the issue no longer occurs in Joomla 5.4. When you have a moment, could you please confirm this on your side? We would greatly appreciate your feedback. If we do not hear back from you, we will proceed to close this pull request in one week.

2025-11-28 14:38 UTC, magnussinger commented
Hi @muhme yep that's right, I'll close the PR now. Thanks for the heads up!

2025-11-28 14:38 UTC, closed without merging