[4.2] Action Logs Enabled
joomla/joomla-cms pull request #37571
Opened 2022-04-17 16:07 UTC by brianteeman

This PR adds a check to the action logs component to determine if the plugin is enabled and if not theen it providees a modal link to enable thee modal. Exactly the same as in com_redirects

### Testing Instructions
Disable the plugin  "Action Logs - Joomla"

### Actual result BEFORE applying this Pull Request
![image](https://user-images.githubusercontent.com/1296369/163722774-5630ae2a-23ad-40f5-8eff-8f64660bfdcb.png)

### Expected result AFTER applying this Pull Request

![image](https://user-images.githubusercontent.com/1296369/163722817-34b5db37-3aee-419e-8c45-a9ea21c66a9d.png)

![image](https://user-images.githubusercontent.com/1296369/163722819-0e979d49-7884-49ee-a52d-57052d8bbbca.png)

### Documentation Changes Required

none

2022-04-17 16:41 UTC, Kostelano requested changes

2022-04-17 16:41 UTC, Kostelano commented on administrator/language/en-GB/com_actionlogs.ini
> +COM_ACTIONLOGS_EDIT_PLUGIN_SETTINGS="Edit Plugin Seeettings"
```suggestion
COM_ACTIONLOGS_EDIT_PLUGIN_SETTINGS="Edit Plugin Settings"
```

2022-04-17 17:14 UTC, brianteeman commented on administrator/language/en-GB/com_actionlogs.ini
> +COM_ACTIONLOGS_EDIT_PLUGIN_SETTINGS="Edit Plugin Seeettings"
obviously my keyboard is having problems. thanks

2022-04-17 17:58 UTC, Quy commented on administrator/components/com_actionlogs/src/Controller/DisplayController.php
> +use Joomla\CMS\HTML\HTMLHelper;
```suggestion
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\MVC\Controller\BaseController;
use Joomla\CMS\Plugin\PluginHelper;
use Joomla\Component\Actionlogs\Administrator\Helper\ActionlogsHelper;
```

2022-04-17 17:59 UTC, Quy commented on administrator/components/com_actionlogs/src/Controller/DisplayController.php
> +		}
```suggestion
			}
		}
```

2022-04-17 19:11 UTC, richard67 commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +			->from($db->quoteName('#__extensions'))
I‘d add a condition for type = ‘plugin’ to the query.

2022-04-17 19:12 UTC, richard67 commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +			->from($db->quoteName('#__extensions'))
… and also for the client_id.

2022-04-17 19:23 UTC, brianteeman commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +			->from($db->quoteName('#__extensions'))
https://github.com/joomla/joomla-cms/blob/bcd54b6c14a0441458a606b31903f60745c6c7d7/administrator/components/com_redirect/src/Helper/RedirectHelper.php#L60-L68

2022-04-17 19:32 UTC, richard67 commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +			->from($db->quoteName('#__extensions'))
Should be fixed there, too. A plugin is identified by the combination of type, folder, element and client_id, and another kind of extension by the combination of type, element and client_id. Leaving away any of these and you cannot be sure to get the right extension.

2022-04-17 19:49 UTC, brianteeman commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +			->from($db->quoteName('#__extensions'))
> A plugin is identified by the combination of type, folder, element and client_id

A plugin always has client_id 0

2022-04-17 19:52 UTC, richard67 commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +			->from($db->quoteName('#__extensions'))
Then you still need to include the type in the query, otherwise you can’t be sure it’s a plugin. The folder not being an empty string is in my opinion not a valid criterion. But it seems we have that mess elsewhere so I don’t insist it to be changed in this PR. Shall other maintainers review it.

2022-04-17 19:54 UTC, brianteeman commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +			->from($db->quoteName('#__extensions'))
Not disagreeing with you - just pointing out that it is this way for many similar queries. I suggest that any refactoring is done at once in another pr

2022-04-17 19:57 UTC, richard67 commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +			->from($db->quoteName('#__extensions'))
Well I hope we won’t forget about it … am just too lazy to open an issue now. But feel free to mark the conversation as resolved so it doesn’t bloat your PR.

2022-04-18 01:45 UTC, toivo commented
I have tested this item :red_circle: unsuccessfully on 72abefbfc89f42aec4ce57323a422af318c8d628<br /><br />Tested in Joomla 4.1.3-dev of 17 April in Wampserver using PHP 8.0.15.
The error notice was displayed but when clicking the link 'Action Log - Joomla Plugin', nothing happened.  The page has the following error that is not displayed if the patch is reverted:

An error has occurred.
0 There is no "table.columns" asset of a "script" type in the registry.
Call stack
#	Function	Location
1	()	JROOT\libraries\src\WebAsset\WebAssetRegistry.php:132
2	Joomla\CMS\WebAsset\WebAssetRegistry->get()	JROOT\libraries\src\WebAsset\WebAssetManager.php:277
3	Joomla\CMS\WebAsset\WebAssetManager->useAsset()	JROOT\libraries\src\WebAsset\WebAssetManager.php:201
4	Joomla\CMS\WebAsset\WebAssetManager->__call()	JROOT\administrator\components\com_actionlogs\tmpl\actionlogs\default.php:27
5	include()	JROOT\libraries\src\MVC\View\HtmlView.php:436
6	Joomla\CMS\MVC\View\HtmlView->loadTemplate()	JROOT\libraries\src\MVC\View\HtmlView.php:220
7	Joomla\CMS\MVC\View\HtmlView->display()	JROOT\administrator\components\com_actionlogs\src\View\Actionlogs\HtmlView.php:137
8	Joomla\Component\Actionlogs\Administrator\View\Actionlogs\HtmlView->display()	JROOT\libraries\src\MVC\Controller\BaseController.php:697
9	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT\administrator\components\com_actionlogs\src\Controller\DisplayController.php:69
10	Joomla\Component\Actionlogs\Administrator\Controller\DisplayController->display()	JROOT\libraries\src\MVC\Controller\BaseController.php:735
11	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:146
12	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT\libraries\src\Component\ComponentHelper.php:389
13	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT\libraries\src\Application\AdministratorApplication.php:143
14	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT\libraries\src\Application\AdministratorApplication.php:186
15	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT\libraries\src\Application\CMSApplication.php:278
16	Joomla\CMS\Application\CMSApplication->execute()	JROOT\administrator\includes\app.php:63
17	require_once()	JROOT\administrator\index.php:32

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37571">issues.joomla.org/tracker/joomla-cms/37571</a>.</sub>

2022-04-18 01:46 UTC, toivo commented
Sorry, wrong dev version!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37571">issues.joomla.org/tracker/joomla-cms/37571</a>.</sub>

2022-04-18 10:42 UTC, richard67 commented
@toivo I've altered your test result to "Not tested" in the issue tracker due to your last comment. When you want to correct a previous test result you can do that also yourself just by using again the "Test this" button in the issue tracker and then selecting the new test result, in this case "I've not tested this item" (or so).

2022-04-18 15:09 UTC, sandewt commented on administrator/components/com_actionlogs/src/Controller/DisplayController.php
> +		$layout = $this->input->get('layout', 'default');
`$layout` and `$id` are unused

2022-04-18 20:54 UTC, toivo commented
@richard67 thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37571">issues.joomla.org/tracker/joomla-cms/37571</a>.</sub>

2022-04-20 08:07 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 72abefbfc89f42aec4ce57323a422af318c8d628<br /><br />Tested successfully in Joomla 4.2.0-alpha2-dev of 20 April in Wampserver using PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37571">issues.joomla.org/tracker/joomla-cms/37571</a>.</sub>

2022-04-20 08:22 UTC, laoneo requested changes

2022-04-20 08:22 UTC, laoneo commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +	public static function getActionlogPluginId()
This method needs to be moved to the model as there you have the database object available.

2022-04-20 08:34 UTC, brianteeman commented on administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
> +	public static function getActionlogPluginId()
fix the exact same code used in multiple places in core then.

Really frustrating to copy paste code from one component to another and be told its wrong.

As you know core is wrong I now expect that you will fix it

2022-04-20 08:35 UTC, brianteeman commented
Really frustrating to copy paste code from one component to another and be told its wrong.

As you know core is wrong I now expect that you will fix it.

2022-04-20 08:35 UTC, closed without merging

2022-04-20 08:43 UTC, laoneo commented
I'm on it https://github.com/joomla/joomla-cms/pull/37097, but stuff needs to be tested.