[4.2] Improving javascript validation of package installer
joomla/joomla-cms pull request #37601
Opened 2022-04-22 04:21 UTC by vorayash

Pull Request for Issue #37575.

### Summary of Changes
Added validation for non zip files in 'build\media_source\plg_installer_packageinstaller\js\packageinstaller.es6.js'

### Testing Instructions
Try to upload an extension in the "upload package file".

### Actual result BEFORE applying this Pull Request
The error was showing just red colored error bar without any content.
![image](https://user-images.githubusercontent.com/72155000/164530114-c7409abd-00f9-4823-a402-616ca7d93b18.png)

### Expected result AFTER applying this Pull Request
![image](https://user-images.githubusercontent.com/72155000/164530313-a5a0f4e6-44fe-45cb-af9a-dbf1818b1ba9.png)

2022-04-22 05:58 UTC, laoneo commented
I would more ask why is there no message in the alert. I think it would be better to serve a proper message from the server why the installation failed. Did you figure out where this empty error comes from?

2022-04-22 14:47 UTC, dgrammatiko requested changes

2022-04-22 14:47 UTC, dgrammatiko commented on build/media_source/plg_installer_packageinstaller/js/packageinstaller.es6.js
> +      if (file.name.split('.').pop() !== "zip") {
You shouldn't really rely on the extension (for security reasons) on any file check in the web. A better approach is to check the mime type, something like: `file.type !== 'application/zip'`. In sort the extension should NEVER be used to sniff the type of file

2022-04-23 08:28 UTC, vorayash commented
> I would more ask why is there no message in the alert. I think it would be better to serve a proper message from the server why the installation failed. Did you figure out where this empty error comes from?

When we send folder as data, xhr readystate changes to 4 and status to 0. It means request is failed. When request fails, value of xhr.statusText changes into empty string(""). 

![image](https://user-images.githubusercontent.com/72155000/164885897-b65ad58d-f4d5-4336-9c6b-9170d3edb323.png)

xhr.statusText is a string so it will satisfy below-pointed condition and empty message will be shown.

![image](https://user-images.githubusercontent.com/72155000/164886284-36990a6a-83e2-4d95-8ff0-92acaca35b9c.png)

I tried xhr request on my local machine and found that when we send folder as data, request fails. So I think sending folder is not allowed in xmlhttprequest.

2022-04-23 08:39 UTC, vorayash commented on build/media_source/plg_installer_packageinstaller/js/packageinstaller.es6.js
> +      if (file.name.split('.').pop() !== "zip") {
👍

2022-04-23 08:58 UTC, laoneo commented
So it means the request never arrives on the server?

2022-04-23 10:39 UTC, vorayash commented
Yes

2022-04-23 10:57 UTC, Fedik commented
It should be fixed the empty message, instead.
Server already doing validation.

2022-05-03 08:07 UTC, closed without merging