Inject the database into the installer
joomla/joomla-cms pull request #37625
Opened 2022-04-23 12:49 UTC by laoneo

### Summary of Changes
Standardizes the database access in the installer library. This is a preparation to load the installer through a service provider.

### Testing Instructions
- Install Joomla
- Discover extension
- Install any kind of extension, for example the [free version of DPCalendar](https://joomla.digital-peak.com/download/dpcalendar) which contains a package, component, modules and plugins
- Uninstall these extensions

### Actual result BEFORE applying this Pull Request
All is working as before.

### Expected result AFTER applying this Pull Request
All is working as before.

2022-06-18 18:28 UTC, roland-d requested changes, later dismissed

2022-06-18 18:28 UTC, roland-d commented on installation/src/Application/InstallationApplication.php
> +		$factory = new MVCFactory('Joomla\\CMS', $this);
@laoneo The `MVCFactory` class only takes 1 argument.

2022-06-18 21:25 UTC, laoneo commented on installation/src/Application/InstallationApplication.php
> +		$factory = new MVCFactory('Joomla\\CMS', $this);
good catch

2022-06-20 14:24 UTC, merged

2022-06-20 14:25 UTC, roland-d commented
Thank you