[4.2] Inject the database into workflow
joomla/joomla-cms pull request #37628
Opened 2022-04-23 17:15 UTC by laoneo

### Summary of Changes
Ongoing effort to inject the database into components and get rid of the deprecated Factory::getDbo(); calls. As workflow offers already the possibility to inject the database, this pr changes the usages where a workflow is instantiated to inject the dependencies. Additionally it deprecates the usage of null dependencies and removes some dead code.

### Testing Instructions
- Enable workflow in the articles manager
- Open the article form

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

2022-06-18 18:42 UTC, roland-d requested changes

2022-06-18 18:42 UTC, roland-d commented on libraries/src/MVC/Model/WorkflowBehaviorTrait.php
> +		$this->workflow = new Workflow($extension, Factory::getApplication(), $db);
@laoneo PhpStorm gives me the warning `Expected parameter of type '\Joomla\CMS\Application\CMSApplication|void', '\Joomla\CMS\Application\CMSApplicationInterface' provided ` Is it something that could potentially cause a problem?

2022-06-18 21:28 UTC, laoneo commented on libraries/src/MVC/Model/WorkflowBehaviorTrait.php
> +		$this->workflow = new Workflow($extension, Factory::getApplication(), $db);
Not really, we try to do as much as possible with the interface. So this should be fine as the CMS app is implementing the interface.

2022-06-20 18:59 UTC, roland-d approved these changes

2023-01-19 07:19 UTC, laoneo commented
Doc article is here https://github.com/joomla/Manual/pull/79

2023-01-19 20:29 UTC, merged

2023-01-19 20:30 UTC, obuisard commented
Thank you Allon @laoneo !