[4.x] Fields - Empty trash
joomla/joomla-cms pull request #37650
Opened 2022-04-25 08:41 UTC by brianteeman

Everywhere that we have an empty trash button it asks you to confirm before the trash is emptied as this is a destructive change.

Fields was missing this.

### Testing Instructions
Create and trash a field
Filter the fields by status trashed
select the field
click on empty trash inn the toolbar

### Actual result BEFORE applying this Pull Request
fields are immediately deleted

### Expected result AFTER applying this Pull Request
popup message is displayed to confirm before deletion

### Documentation Changes Required

2022-04-25 09:26 UTC, richard67 commented
@brianteeman The system tests are failing for this PR, and I think it could be related to your changes so the tests might need some changes, too. See the log here https://ci.joomla.org/joomla/joomla-cms/53603/1/30 :

```
 I delete field "Field title","Field deleted"
   I am on page "/administrator/index.php?option=com_fie..."
  [GET] http://localhost/mysql/administrator/index.php?option=com_fields&view=fields&context=com_content.article
   I get config "timeout"
   I wait for element {"id":"filter_search"},90
   I execute js "[].forEach.call(document.querySelectorA..."
   I select option "//*[@id="filter_state"]","-2"
   I wait 2
   I fill field {"id":"filter_search"},"Field title"
   I click {"id":"filter_search"}
   I check all results 
  Selecting Checkall button
   I wait 2
   I click toolbar button "Empty trash"
   I get config "timeout"
   I wait for text "Field deleted",90,{"id":"system-mess...}
  Screenshot and page source were saved into '/********/src/tests/Codeception/_output/' dir
 ERROR 
```

The screenshot then looks like this: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.1-dev/37650/system-tests/53603/ContentFieldListCest.Field.mysql.fail.png

2022-04-25 09:27 UTC, richard67 commented
Will try to get someone to advise with the system tests.

2022-04-25 09:49 UTC, laoneo commented
The system test needs to be adapted of fields. Something like here shuould probably work https://github.com/joomla/joomla-cms/blob/4.1-dev/tests/Codeception/_support/Step/Acceptance/Administrator/Content.php#L229.

2022-04-25 10:36 UTC, brianteeman commented
will take a look this afternoon

2022-04-25 10:45 UTC, richard67 commented
@brianteeman I think it need to replace this line here 

https://github.com/joomla/joomla-cms/blob/4.1-dev/tests/Codeception/_support/Step/Acceptance/Administrator/Field.php#L121

by these 2 lines:

```
$I->wait(2);
$I->acceptPopup();
```

2022-04-25 12:14 UTC, richard67 commented
It seems to work.

2022-04-25 12:19 UTC, laoneo requested changes

2022-04-25 12:19 UTC, laoneo commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
Please do not remove the assert. This is needed as it actually tests if the message is correct. You should just add the accept popup code.

2022-04-25 12:21 UTC, richard67 commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
> You should just add the accept popup code.

@laoneo Before or after the `$I->assertSuccessMessage($message);`?

2022-04-25 12:21 UTC, laoneo commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
Before

2022-04-25 12:22 UTC, richard67 commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
But here we do not have the assert: https://github.com/joomla/joomla-cms/blob/4.1-dev/tests/Codeception/_support/Step/Acceptance/Administrator/Content.php#L229

2022-04-25 12:32 UTC, laoneo commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
Because this implementation of a step is wrong. A step should just have reusable code which can be used in different tests to eliminate duplicate code, but should not do any assert. So this needs to be fixed in a different pr. For now just add the wait and popup before the assert.

2022-04-25 12:34 UTC, richard67 commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
@laoneo Should there maybe be another wait between the acceptPopup and the assert?

2022-04-25 12:40 UTC, laoneo commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
Waits should be avoided whenever possible. Mostly Codeception waits till either the element appears or it runs in into a timeout. In this case it waits for the text here https://github.com/joomla/joomla-cms/blob/4.1-dev/tests/Codeception/_support/Step/Acceptance/Administrator/Field.php#L57-L61

2022-04-25 12:41 UTC, richard67 commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
I see. Thanks.

2022-04-25 14:14 UTC, brianteeman commented
This PR brings the behaviour of Empty Trash in Fields to be consistent with all other uses. The test has also been updated to be consistent with all the other tests for Empty Trash.

If the test is incomplete then it is incomplete eveyrwhere and should be updated in its own pull request.

2022-04-25 14:17 UTC, richard67 commented
> This PR brings the behaviour of Empty Trash in Fields to be consistent with all other uses. The test has also been updated to be consistent with all the other tests for Empty Trash.
> 
> If the test is incomplete then it is incomplete eveyrwhere and should be updated in its own pull request.

I would be ok with that.

2022-04-25 20:27 UTC, laoneo commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
This is not resolved, please add again `$I->assertSuccessMessage($message);` code.

2022-04-25 21:14 UTC, brianteeman commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> -		$I->assertSuccessMessage($message);
Please make up your mind.

2022-04-26 00:29 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 36524df7974444596b9a4c16645db4936ca0e6d6<br /><br />Tested successfully in Joomla 4.1.3-dev of 25 April.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37650">issues.joomla.org/tracker/joomla-cms/37650</a>.</sub>

2022-04-26 13:06 UTC, beefcakefu commented
I have tested this item :white_check_mark: successfully on 36524df7974444596b9a4c16645db4936ca0e6d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37650">issues.joomla.org/tracker/joomla-cms/37650</a>.</sub>

2022-04-26 18:04 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37650">issues.joomla.org/tracker/joomla-cms/37650</a>.</sub>

2022-04-29 10:58 UTC, richard67 commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> +		$I->acceptPopup();
```suggestion
		$I->acceptPopup();
		$I->assertSuccessMessage($message);
```
@brianteeman Could you apply this change so the old behaviour of this test is restored? Otherwise, without that line, the `$message` parameter would be useless here: https://github.com/joomla/joomla-cms/blob/36524df7974444596b9a4c16645db4936ca0e6d6/tests/Codeception/_support/Step/Acceptance/Administrator/Field.php#L102

I agree with you that we should check the same method at other places and if necessary fix them, too.

2022-04-29 10:59 UTC, richard67 commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> +		$I->acceptPopup();
P.S.: It will not need new human tests after this change will be applied.

2022-04-29 11:02 UTC, brianteeman commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> +		$I->acceptPopup();
i will commit the suggestion as yu asked nicely. i still believe it to be wrong to do it in this pr but ...

2022-04-29 11:20 UTC, richard67 commented on tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
> +		$I->acceptPopup();
Thanks. Much appreciated. I agree with you at least to a large part but wanted to avoid arguments with other maintainers 😉 .

2022-04-29 11:21 UTC, richard67 commented
@laoneo Now as your suggested change has been implemented, please approve the changes on GitHub so the it does not show any requested changes anymore. Thanks in advance.

2022-04-29 11:24 UTC, richard67 commented
Previous human test results and RTC status are still valid since the commit after that only changed the system tests, which are still passing.

2022-04-29 11:34 UTC, laoneo approved these changes

2022-04-30 02:51 UTC, merged

2022-04-30 02:51 UTC, bembelimen commented
Thx

2022-04-30 05:36 UTC, brianteeman commented
thanks