Make the Tags RouteHelper language aware
joomla/joomla-cms pull request #37721
Opened 2022-05-02 14:09 UTC by roland-d

### Summary of Changes
While building a multi-lingual site with tags we found out that the mod_tags_popular module was not producing SEF URLs due to missing the language string. When the menu items had their language set to All (*) it worked fine but when changing them to English (en-GB) and Dutch (nl-NL) the links are no longer working. After some investigation I found out that the Tags RouteHelper does not take the current language into account. This fix resolves that.

### Testing Instructions
1. Create a Joomla site with 2 languages (here I assume EN and NL)
2. Create some Tags associated with the English language
3. Create some Tags associated with the Dutch language
4. Create some Articles associated with the English language and select some English Tags
5. Create some Articles associated with the Dutch language and select some Dutch Tags
6. In the English Home menu create a menu entry of the type `List All Tags` and set the language to English
7. In the English Home menu create a menu entry of the type `Compact List of Tagged Items` and set the language to English, select a tag used by the English articles and set `Content Type` to `Articles`
8. In the Dutch Home menu create a menu entry of the type `List All Tags` and set the language to Dutch
9. In the Dutch Home menu create a menu entry of the type `Compact List of Tagged Items` and set the language to Dutch, select a tag used by the Dutch articles and set `Content Type` to `Articles`
10. Create a front-end module of the type `Tags Popular` and set the language to English and assign it to a menu item that is set in step 7
11. Create a front-end module of the type `Tags Popular` and set the language to Dutch and assign it to a menu item that is set in step 9
12. Go the URL that links to the menu item created in step 7
13. Click on an article shown there
14. You should see the module from step 10 on this page
15. Notice that the links in the module are not as expected but they contain `component/tags/tag`
16. Go the URL that links to the menu item created in step 9
17. Click on an article shown there
18. You should see the module from step 11 on this page
19. Notice that the links in the module are not as expected but they contain `component/tags/tag`
20. Apply the patch
21. Redo step 12 - 14
22. You should see the correct URL in the module
23. Redo step 16 - 18
24. You should see the correct URL in the module

### Actual result BEFORE applying this Pull Request
The URLs in the module do not show the correct SEF URL but instead contain `component/tags/tag`

### Expected result AFTER applying this Pull Request
The URLs in the module do show the correct SEF URL according to their menu item

### Documentation Changes Required
None

2022-05-03 10:38 UTC, wilsonge commented
LGTM overall.

In terms of the b/c. what's the change of `*` compared to the query not existing before (i.e. if people in the JLayout don't update their template override is there a behaviour change?)

2022-05-03 12:19 UTC, roland-d commented
@wilsonge There is no b/c break here because the default value mimics the old behavior. So by not specifying the language the function works like it currently does.

2022-05-05 01:15 UTC, Quy commented
Fixes #31530 #31754 ?

2022-05-05 08:05 UTC, roland-d commented
It sounds like it, they should test this

2022-05-14 21:35 UTC, Quy commented on components/com_tags/src/Helper/RouteHelper.php
> +	 * @param   integer  $id        The ID of the tag
```suggestion
	 * @param   integer  $id        The ID of the tag
	 * @param   string   $language  The language of the tag
```

2022-05-17 08:05 UTC, wilsonge approved these changes

2022-05-18 15:24 UTC, Quy commented on components/com_tags/src/Helper/RouteHelper.php
> +			'language' => $language
```suggestion
			'language' => $language,
```

2022-05-23 12:35 UTC, joomdonation commented on modules/mod_tags_popular/tmpl/cloud.php
> +			<a class="tag-name" style="font-size: <?php echo $fontsize . 'em'; ?>" href="<?php echo Route::_(RouteHelper::getTagRoute($item->tag_id . ':' . $item->alias, $module->language)); ?>">
Could you explain why you are using module language for routing instead of the tag's language?

2022-05-23 13:22 UTC, roland-d commented on modules/mod_tags_popular/tmpl/cloud.php
> +			<a class="tag-name" style="font-size: <?php echo $fontsize . 'em'; ?>" href="<?php echo Route::_(RouteHelper::getTagRoute($item->tag_id . ':' . $item->alias, $module->language)); ?>">
@joomdonation I am using the module language here because it is the module being rendered and this way the tag adheres to the module language.

2022-05-23 14:04 UTC, joomdonation commented on modules/mod_tags_popular/tmpl/cloud.php
> +			<a class="tag-name" style="font-size: <?php echo $fontsize . 'em'; ?>" href="<?php echo Route::_(RouteHelper::getTagRoute($item->tag_id . ':' . $item->alias, $module->language)); ?>">
I'm unsure that is the right behavior. By default, the module display tags from all languages. So for example:

- A site has two languages English and German
- Create an instance of Popular Tags module, assign it to English language
- The module (by default) display tags from all languages. If a tag is assigned to German language, you are using English language (from the module) for routing for that German language tag and it could not be right

Isn't it better if we use the tag language instead? I don't think anywhere in Joomla we use module language for routing like you are using in this PR.

Maybe I am wrong? (haven't tested the behavior yet, just comment base on code review only)

2022-05-23 18:22 UTC, roland-d commented on modules/mod_tags_popular/tmpl/cloud.php
> +			<a class="tag-name" style="font-size: <?php echo $fontsize . 'em'; ?>" href="<?php echo Route::_(RouteHelper::getTagRoute($item->tag_id . ':' . $item->alias, $module->language)); ?>">
I was not sure either, so I will follow you and changed the code to use the tag language.

2022-05-24 15:40 UTC, joomdonation reviewed
There are still few minor changes needed, then we can test the PR.

2022-05-24 15:40 UTC, joomdonation commented on libraries/src/Helper/ModuleHelper.php
> +		$query->select($db->quoteName(['m.id', 'm.title', 'm.module', 'm.position', 'm.content', 'm.showtitle', 'm.params', 'm.language', 'mm.menuid']))
The change here should be reverted.

2022-05-24 15:40 UTC, joomdonation commented on modules/mod_tags_popular/tmpl/default.php
> +		<a href="<?php echo Route::_(RouteHelper::getTagRoute($item->tag_id . ':' . $item->alias, $module->language)); ?>">
`$module->language` should be replaced with `$item->language`

2022-05-24 16:52 UTC, roland-d commented on modules/mod_tags_popular/tmpl/default.php
> +		<a href="<?php echo Route::_(RouteHelper::getTagRoute($item->tag_id . ':' . $item->alias, $module->language)); ?>">
@joomdonation Agree, changes pushed.

2022-05-24 16:52 UTC, roland-d commented on libraries/src/Helper/ModuleHelper.php
> +		$query->select($db->quoteName(['m.id', 'm.title', 'm.module', 'm.position', 'm.content', 'm.showtitle', 'm.params', 'm.language', 'mm.menuid']))
Change also pushed.

2022-05-24 17:03 UTC, joomdonation commented on modules/mod_tags_popular/tmpl/default.php
> +		<a href="<?php echo Route::_(RouteHelper::getTagRoute($item->tag_id . ':' . $item->alias, $module->language)); ?>">
Thanks @roland-d . It should be all OK now. I will perform real test on tomorrow and report my test result.

2022-05-25 14:09 UTC, joomdonation commented
@roland-d I spent sometime to test this PR today and it works good for me. The only thing left is that in `RouteHelper` class, we have `getTagsRoute()` method, I think we should add support for $language parameter, too. Could you please look at it? This method is not used in the core, but I think the code should be consistent. After that, I can mark my test success for the PR. Thanks.

2022-05-26 07:57 UTC, roland-d commented
@joomdonation I have added the language as option to the `getTagsRoute()` as well. I did not look at it before as I am not using it either :)

2022-05-26 08:00 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on 4f446c2fc862c4452e7735e219b921dd85605f64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37721">issues.joomla.org/tracker/joomla-cms/37721</a>.</sub>

2022-05-26 08:01 UTC, joomdonation commented
All good now, thanks @roland-d

2022-05-27 19:09 UTC, hakanara commented
I had the same issue for a very long time. I would like to thank to all the contributors. I have a question: Would this fix be affecting Joomla 3.10 as well in the upcoming release? Or only the 4.1?

2022-05-27 21:25 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 4f446c2fc862c4452e7735e219b921dd85605f64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37721">issues.joomla.org/tracker/joomla-cms/37721</a>.</sub>

2022-05-27 21:45 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37721">issues.joomla.org/tracker/joomla-cms/37721</a>.</sub>

2022-06-05 22:35 UTC, bembelimen commented
> @wilsonge There is no b/c break here because the default value mimics the old behavior. So by not specifying the language the function works like it currently does.

In 8.1 this breaks. No fix for a bugfix release. In my opinion something for 5.0 because of 8.1, but moving to 4.2 so you can decide.

2022-06-08 07:06 UTC, hakanara commented
I would like to ask one more time, will this fix be applied to 3.10 as well?

2022-06-09 05:38 UTC, laoneo commented
If possible, then the deprecated function should call the new function and not have duplicated code.

2022-06-09 05:54 UTC, roland-d commented
@laoneo Of course, good point. Code cleaned up.

2022-06-09 10:31 UTC, joomdonation commented
So the change is now backward-compatible. Do you want to have it in 4.1 @bembelimen ? Or should we re-test it for 4.2?

2022-06-10 06:48 UTC, laoneo commented
Back to pending as some code got changed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37721">issues.joomla.org/tracker/joomla-cms/37721</a>.</sub>

2022-06-11 05:12 UTC, joomdonation requested changes
There are some issues in the code need to be fixed.

2022-06-11 05:12 UTC, joomdonation commented on components/com_tags/src/Helper/RouteHelper.php
> +	public static function getComponentTagRoute(int $id, string $language = '*'): string
You cannot use `int` for `$id` parameter here because when we call this method, we pass value for this parameter as string (in this format `TAG_ID:TAG_ALIAS`). Force int data type here causes wrong tag URL generated:

- The right URL is http://localhost/jmt/index.php/en/list-all-tags-en/tag-2-en (tag-2-en is Tag Alias)
- The wrong URL (with the current code) is http://localhost/jmt/index.php/en/list-all-tags-en/3  (3 is ID of the tag)

2022-06-11 05:12 UTC, joomdonation commented on components/com_tags/src/Helper/RouteHelper.php
> +			'tag'      => [0],
Typo here, should be **tags**, not **tag**

2022-06-12 07:37 UTC, roland-d commented on components/com_tags/src/Helper/RouteHelper.php
> +			'tag'      => [0],
Thank you, fixed.

2022-06-12 07:37 UTC, roland-d commented on components/com_tags/src/Helper/RouteHelper.php
> +	public static function getComponentTagRoute(int $id, string $language = '*'): string
Thank you, fixed.

2022-06-12 08:09 UTC, joomdonation commented on components/com_tags/src/Helper/RouteHelper.php
> +			'tag'      => [$id],
Could you please change this to `'tag'      => [(int) $id],` like in the original code? Then all is fine.

2022-06-12 08:18 UTC, roland-d commented on components/com_tags/src/Helper/RouteHelper.php
> +			'tag'      => [$id],
I changed that but also removed the type casting in the `getTagRoute()` so the `$id` is passed just as-is.

2022-06-12 08:24 UTC, joomdonation commented on components/com_tags/src/Helper/RouteHelper.php
> +			'tag'      => [$id],
Ah, Yes. Luckily you did that :), otherwise, we would get issue override layouts use `getTagRoute()`

2022-06-12 08:30 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on 762ae51e21b88adaaa6e3da30e17e8b1e1fb85c5<br /><br />Works great now, thanks !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37721">issues.joomla.org/tracker/joomla-cms/37721</a>.</sub>

2022-06-19 05:12 UTC, joomdonation commented
@chmst Could you please re-test ? It's nice to have this issue fixed.

2022-06-20 19:13 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 7891e0ece7774ae48e8b432186a07d0459d3f78e<br /><br />👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37721">issues.joomla.org/tracker/joomla-cms/37721</a>.</sub>

2022-06-20 19:21 UTC, hakanara commented
I have I have opened [this same issue](https://github.com/joomla/joomla-cms/issues/31530) 1,5 years ago. I am still looking forward to a solution for this. But I have to use Joomla 3.10 for one more year for some specific reasons. Please create an update for Joomla 3.10 as well since you already know how to modify the code. Thank you for everyone who have contributed for the solution.

2022-06-20 20:17 UTC, merged

2022-06-20 20:17 UTC, wilsonge commented
Two good tests. Let's get this in. Thankyou!

2022-08-05 14:50 UTC, simbus82 commented
No one who answered @hakanara.
Multilanguage tags URL routing in Joomla 3.10 is broken like hell.
https://github.com/joomla/joomla-cms/issues/31530

Remember that Joomla 3.x today is the 75% of all Joomla installed.
![image](https://user-images.githubusercontent.com/1375730/183102330-206111e8-d2d0-475b-9983-7a2dfa7f815f.png)

2022-08-05 16:05 UTC, hakanara commented
Please hear us and create a solution for Joomla 3.10. Thank you for mentioning this @simbus82