[4.2] Convert joomla action log plugin to services
joomla/joomla-cms pull request #37788
Opened 2022-05-13 15:00 UTC by laoneo

### Summary of Changes
Converts the joomla action log plugin to services.

The action log component changes from https://github.com/joomla/joomla-cms/pull/37592 are included here too, otherwise we will have a conflict after merge.

@nikosdion you may want to have a look here too.

### Testing Instructions
- Enable the joomla action log plugin
- Save an article
- Go to /administrator/index.php?option=com_actionlogs&view=actionlogs

### Actual result BEFORE applying this Pull Request
Action log entry is written for an article create action.

### Expected result AFTER applying this Pull Request
Action log entry is written for an article create action.

2022-05-13 18:09 UTC, richard67 commented
@laoneo It has some CS errors: https://ci.joomla.org/joomla/joomla-cms/54000/1/6

2022-05-13 18:20 UTC, brianteeman commented on plugins/actionlog/joomla/services/provider.php
> + * @subpackage  System.cache
copy paste error

2022-05-14 02:05 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 02b0b6e7ac01e9c63e5c0991a22fbaf90884c336<br /><br />Tested successfully in Joomla 4.2.0-alpha3-dev of 13 May.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37788">issues.joomla.org/tracker/joomla-cms/37788</a>.</sub>

2022-05-14 08:43 UTC, sandewt commented on plugins/actionlog/joomla/src/Extension/Joomla.php
> +/**
linefeed + tab error

2022-05-15 06:10 UTC, sandewt commented on plugins/actionlog/joomla/src/Extension/Joomla.php
>  	/**
Add an empty line between lines 98 and 99

2022-05-15 17:15 UTC, laoneo commented on plugins/actionlog/joomla/src/Extension/Joomla.php
>  	/**
thanks!

2022-05-16 17:19 UTC, richard67 commented on plugins/actionlog/joomla/services/provider.php
> +					(array) PluginHelper::getPlugin('system', 'cache'),
```suggestion
					(array) PluginHelper::getPlugin('system', 'cache')
```
Its function parameters and not an array, so there should not be a comma after the last element like it would be if it was an array.

2022-05-16 18:02 UTC, sandewt commented on plugins/actionlog/joomla/src/Joomla.php
> + * @subpackage  System.actionlog
To be consistent:
`@subpackage  System.actionlog`
Should be:
`@subpackage Actionlog.joomla` or `@subpackage Actionlog.Joomla`

2022-05-16 18:02 UTC, sandewt commented on plugins/actionlog/joomla/services/provider.php
> + * @subpackage  System.Actionlog
To be consistent:
`@subpackage  System.actionlog`
Should be:
`@subpackage Actionlog.joomla` or `@subpackage Actionlog.Joomla`

2022-05-16 18:26 UTC, nikosdion commented
Sorry for the very long delay, I am refactoring Joomla's Two Factor Authentication.

Overall it works fine for me, I juts have one question. Since we are going into the trouble of converting the plugin, shouldn't we also convert it to use SubscriberInterface?

At some point in the future https://github.com/joomla/joomla-cms/pull/36578 will be merged in the core. Having the plugin use SubscriberInterface would make quick work of converting it once the concrete events classes are written (phase 2 of the work on that PR). It could even serve as a proof of the concept in the core.

Totally optional, just thinking out loud.

2022-05-16 18:49 UTC, laoneo commented
I guess when https://github.com/joomla/joomla-cms/pull/36578 got merged, then we can use the SubscriberInterface. Till then we have to use the legacy subscribing way. But SubscriberInterface is definitely the way to go.

2022-05-16 19:04 UTC, nikosdion commented
@laoneo You can already use SubscriberInterface 😉 See https://github.com/joomla/joomla-cms/blob/47d570f5596943be2f6b26e81623c59d3d9ecb7d/plugins/twofactorauth/totp/src/Extension/Totp.php

2022-05-17 07:41 UTC, Fedik commented on plugins/actionlog/joomla/joomla.xml
> +		<folder plugin="joomla">services</folder>
just `<folder>services</folder>`

2022-05-17 11:08 UTC, laoneo commented on plugins/actionlog/joomla/joomla.xml
> +		<folder plugin="joomla">services</folder>
You need the plugin name when it should be installable.

2022-05-17 11:55 UTC, Fedik commented on plugins/actionlog/joomla/joomla.xml
> +		<folder plugin="joomla">services</folder>
But then you have `<folder>src</folder>` without it.

2022-05-17 11:57 UTC, nikosdion commented on plugins/actionlog/joomla/joomla.xml
> +		<folder plugin="joomla">services</folder>
You only need one element (`<filename>` or `<folder>`) to have the `plugin` attribute. The installer looks for the first instance of that attribute in the `<files>` node's children to determine the name of the plugin. Same thing applies for modules.

2022-05-17 11:58 UTC, laoneo commented on plugins/actionlog/joomla/joomla.xml
> +		<folder plugin="joomla">services</folder>
One element needs the plugin attribute, before it was the joomla.php. Look out here https://github.com/akeeba/release-system/pull/191 for more details or here https://github.com/joomla/joomla-cms/pull/36042#issuecomment-968362963.

2022-05-17 12:06 UTC, laoneo commented
For now I would like to leave it with the current events to not break anything.

2022-05-17 15:54 UTC, Fedik commented on plugins/actionlog/joomla/joomla.xml
> +		<folder plugin="joomla">services</folder>
okay, that much strange then :smile:

2022-05-22 06:14 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 96dead5a1063749a61a130e70a71a8f5157f7c52<br /><br />Tested successfully in Joomla 4.2.0-alpha3-dev of 22 May in Wampserver 3.2.8 with PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37788">issues.joomla.org/tracker/joomla-cms/37788</a>.</sub>

2022-05-23 06:23 UTC, sandewt commented on plugins/actionlog/joomla/services/provider.php
> + * @subpackage  System.Actionlog
It''s not a 'system' plugin

2022-05-23 06:38 UTC, laoneo commented on plugins/actionlog/joomla/services/provider.php
> + * @subpackage  System.Actionlog
I'v changed it already

2022-05-23 07:52 UTC, sandewt commented on plugins/actionlog/joomla/services/provider.php
> + * @subpackage  System.Actionlog
Oops

2022-05-27 06:32 UTC, alikon requested changes

2022-05-27 06:32 UTC, alikon commented on plugins/actionlog/joomla/src/Joomla.php
> +			->where($db->quoteName('username') . ' = ' . $db->quote($response['username']));
please use prepared statement

2022-05-28 11:19 UTC, heelc29 commented on plugins/actionlog/joomla/src/Joomla.php
> +namespace Joomla\Plugin\Actionlog\Joomla;
Can you move it back to `Extension` https://github.com/joomla/joomla-cms/pull/37803#issuecomment-1128797627

2022-05-28 11:22 UTC, heelc29 requested changes

2022-05-28 11:22 UTC, heelc29 commented on plugins/actionlog/joomla/services/provider.php
> +					(array) PluginHelper::getPlugin('system', 'cache')
```suggestion
					(array) PluginHelper::getPlugin('actionlog', 'joomla')
```

2022-05-28 11:22 UTC, heelc29 commented on plugins/actionlog/joomla/services/provider.php
> +	/**
```suggestion
return new class implements ServiceProviderInterface
{
	/**
```

2022-05-30 06:53 UTC, laoneo commented on plugins/actionlog/joomla/src/Joomla.php
> +			->where($db->quoteName('username') . ' = ' . $db->quote($response['username']));
This should be done in it's own pr as this is only a variable rename.

2022-05-30 06:55 UTC, laoneo commented on plugins/actionlog/joomla/src/Joomla.php
> +namespace Joomla\Plugin\Actionlog\Joomla;
Done

2022-05-30 07:37 UTC, sandewt commented
https://github.com/joomla/joomla-cms/blob/a97b0f921433301d27de0414142e4b23326fa991/plugins/actionlog/joomla/joomla.xml#L1

Suggestion, lower case: `encoding="utf-8"`

(I don't know if this is related to this issue ?)

2022-05-30 07:58 UTC, laoneo commented
To which issue?

2022-05-30 08:09 UTC, sandewt commented
>To which issue?

I mean, change here too.

2022-05-30 09:08 UTC, heelc29 commented on plugins/actionlog/joomla/services/provider.php
> +use Joomla\Plugin\Actionlog\Joomla\Joomla\Extension;
```suggestion
use Joomla\Plugin\Actionlog\Joomla\Extension\Joomla;
```

2022-05-30 10:38 UTC, heelc29 commented
I have tested this item :white_check_mark: successfully on a878b871b73e104cf4e45f6ce43e3b37228f5a06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37788">issues.joomla.org/tracker/joomla-cms/37788</a>.</sub>

2022-05-30 10:58 UTC, laoneo commented
@sandewt changed it. Can you give this plugin also a test?

2022-05-30 11:26 UTC, sandewt commented on plugins/actionlog/joomla/services/provider.php
> +	 * @return  void
`@return  void`

Isn't this an object?

`@return  object`

2022-05-30 11:29 UTC, sandewt commented
> Can you give this plugin also a test?

I'm going to do it, but see my comment what I came across during testing.

2022-05-30 11:34 UTC, laoneo commented on plugins/actionlog/joomla/services/provider.php
> +	 * @return  void
This function doesn't return anything, it just sets a resource in the container.

2022-05-30 17:04 UTC, alikon commented
I have tested this item :white_check_mark: successfully on a878b871b73e104cf4e45f6ce43e3b37228f5a06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37788">issues.joomla.org/tracker/joomla-cms/37788</a>.</sub>

2022-05-30 17:04 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37788">issues.joomla.org/tracker/joomla-cms/37788</a>.</sub>

2022-05-30 17:29 UTC, sandewt commented
I have tested this item :white_check_mark: successfully on a878b871b73e104cf4e45f6ce43e3b37228f5a06<br /><br />Joomla! 4.2.0-alpha3-dev Development<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37788">issues.joomla.org/tracker/joomla-cms/37788</a>.</sub>

2022-05-30 19:27 UTC, merged

2022-05-30 19:27 UTC, roland-d commented
Thanks everybody