mplement 'requireon' attribute to form fields for conditional requiredness
joomla/joomla-cms pull request #37798
Opened 2022-05-15 10:16 UTC by stephan-ansems

Pull Request for a new Feature 

### Summary of Changes
Implementation for an new attribute `requireon` to the form field spec to that accepts conditional statements identical to that of the `showon` attribute. However the effect is to toggle the `required` attribute on form fields and show/hode the little star next to the label that indicates that the field is required.
Code changes: 
- small refactoring of FormHelper method `parseShowOnConditions` to `parseFieldConditions` 
- new javascript asset `requiron` to perform the client-side magic
- Addition of the `requireon` attribute and implementation in all places where the `showon` is also present

#### Why is this useful?
Some argue that having to toggle the requiredness of a field is a design flaw in the form, however I believe that it is not. For example a form to specify OAuth2 settings could have a dropdown to indicate the grant type. Depending on the grant type chosen, the form can change quite drastically. Some fields are not relevant for certain grant types and can be hidden, others are no longer required. The problem with only `showon` is that you can hide these fields, but a hidden field still remains required and form validation will not pass succesfully. 

### Testing Instructions
Create a form with a listfield with two options and a field that has the new attribute, for example this content:
```xml
<?xml version="1.0" encoding="utf-8"?>
  <field
      name="foo"
      type="list"
      >
      <option value="1">MANDATORY</option>
      <option value="0">OPTIONAL</option>
  </field>
  <field
      name="bar"
      type="text"
      requireon="foo:1"
  />
</form>
```
Open the form and change the selection of the `foo` field and see the `bar` field become mandory or optional.

### Actual result BEFORE applying this Pull Request
Any form field that uses the `requireon` attribute remain required or optional depending on value of the `required` attribute. Joomla ignores the extra attribute, but adding the attribute to fields before this feature is implemented makes no sense. 

### Expected result AFTER applying this Pull Request
Any form fields that have the `requireon` attribute will be conditionally required when the condition evaluates to true. The logic works the same as for the `showon` attribute.

### Documentation Changes Required
(https://docs.joomla.org/Form_field#Modal_form_field_types) can probably be documented in one fell swoop with the ShowOn property explanations.

2022-05-15 10:18 UTC, stephan-ansems commented
To any of the experienced Joomla developers, i'm learning how to do this and I appologize for things that are not according to guidelines or procedures. Please help me learn them.

2022-05-15 11:26 UTC, richard67 commented
@stephan-ansems I think renaming that public method is a b/c break and so maybe not a good idea.

It also seems to break the installation form, at least the automated test break when making a new installation.

Have you tested that, make a new Joomla installation with your changed code? Or in an existing installation, change something in Global Configuration in backend and try to save the changes?

2022-05-15 11:41 UTC, rdeutz commented on libraries/src/Form/FormHelper.php
> +		$conditionParts = preg_split('#(\[AND\]|\[OR\])#', $$conditions, -1, PREG_SPLIT_DELIM_CAPTURE);
$$ typo?

2022-05-15 11:44 UTC, dgrammatiko commented
@stephan-ansems out of curiosity: why didn't you extended the existing showOn functionality and duplicated the whole stack just for the extra attribute?

2022-05-15 11:46 UTC, rdeutz commented
> @stephan-ansems I think renaming that public method is a b/c break and so maybe not a good idea.
@richard67 is right, renaming makes sense but you need to add the old function calling the new function. The old function should be depreciated 5.0. That should fix the testing problem for now. But we need to change the tests and replace all the calls to the old function.

Good addition btw.

2022-05-15 19:07 UTC, stephan-ansems commented on libraries/src/Form/FormHelper.php
> +		$conditionParts = preg_split('#(\[AND\]|\[OR\])#', $$conditions, -1, PREG_SPLIT_DELIM_CAPTURE);
yes, not sure how that snuck in. It seemed to work for me when i tested it. It'll be fixed

2022-05-15 19:12 UTC, stephan-ansems commented
> @stephan-ansems out of curiosity: why didn't you extended the existing showOn functionality and duplicated the whole stack just for the extra attribute?

@dgrammatiko I don't see how i could do that. This seemed like the most obvious solution. Also I think that `requireon` and `showon` are not always linked, so hiding a field may influence the requiredness of it, but the reverse is not true.

2022-05-16 09:30 UTC, richard67 commented
@stephan-ansems If you think the PR is ready for being tested, it needs you to click the "Ready for review" button at the bottom of the PR on GitHub to remove the "Draft" status.

2022-05-16 09:34 UTC, richard67 commented on libraries/src/Form/FormField.php
> +			'required'       => (bool) $this->required ||(bool) $this->requireon,
```suggestion
			'required'       => (bool) $this->required || (bool) $this->requireon,
```
Just a small code style improvement.

2022-05-18 10:57 UTC, richard67 commented
@stephan-ansems It does not need to update your branch every time GitHub shows that the branch is not up to date. It needs to do that only when GitHub shows in addition that there are conflicting files, which is not the case here.

2023-05-02 16:42 UTC, HLeithner commented
This pull request has been automatically rebased to 5.0-dev.

2023-09-30 22:51 UTC, HLeithner commented
This pull request has been automatically rebased to 5.1-dev.

2024-04-24 09:09 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2024-07-18 12:57 UTC, Hackwar commented
Hey @stephan-ansems, could you update this PR and solve the file conflicts? I'd like to merge this into 5.2 and finally solve this. Sorry that this is taking so long.

2024-07-25 17:33 UTC, Hackwar commented
I've solved the file conflicts.

2024-07-25 17:44 UTC, brianteeman commented
> I've solved the file conflicts.

can you also fix the phpcs issues please

2024-07-25 20:07 UTC, zero-24 requested changes
PHP CS

2024-07-25 20:07 UTC, zero-24 commented on libraries/src/Form/FormHelper.php
>          $op          = '';
```suggestion
        $op             = '';
```

2024-07-25 20:07 UTC, zero-24 commented on libraries/src/Form/FormHelper.php
> +            $compareEqual     = strpos($conditionPart, '!:') === false;
```suggestion
            $compareEqual        = strpos($conditionPart, '!:') === false;
```

2024-07-25 20:07 UTC, zero-24 commented on libraries/src/Form/Field/ListField.php
>              $tmp['onclick']  = (string) $option['onclick'];
```suggestion
            $tmp['onclick']       = (string) $option['onclick'];
```

2024-07-25 20:07 UTC, zero-24 commented on libraries/src/Form/Field/ListField.php
>              $tmp['onchange'] = (string) $option['onchange'];
```suggestion
            $tmp['onchange']      = (string) $option['onchange'];
```

2024-07-25 20:07 UTC, zero-24 commented on libraries/src/Form/FormField.php
>              case 'description':
```suggestion
                // No break
            case 'description':
```

2024-07-25 20:07 UTC, zero-24 commented on libraries/src/Form/FormField.php
>              case 'required':
```suggestion
                // No break
            case 'required':
```

2024-07-25 20:07 UTC, zero-24 commented on libraries/src/Form/FormField.php
> +            $options['rel']          .= ' data-requireon=\'' .
```suggestion
            $options['rel'] .= ' data-requireon=\'' .
```

2024-07-25 21:07 UTC, zero-24 approved these changes
PHP CS is now ok

2024-07-25 21:09 UTC, brianteeman commented on build/media_source/system/js/requireon.es6.js
> + * @copyright  (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright  (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
```

its a new file

2024-07-26 07:36 UTC, Fedik commented
I am sorry, this PR should be closed.
It is hack around of the limitation of `showon` feature.

We better should look how to improve `showon` feature, than continue hacking around.

2024-08-02 08:22 UTC, closed without merging