[4.2] Convert token API auth plugin to services
joomla/joomla-cms pull request #37804
Opened 2022-05-15 18:17 UTC by laoneo

### Summary of Changes
Convert token API auth plugin to services.

### Testing Instructions
- Enable the token API auth plugin
- Save your user settings so a API token is generated
- Make an API request with bearer authentication with the generated API token, for example you can use curl or postman

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

2022-05-17 11:37 UTC, heelc29 commented on plugins/api-authentication/token/services/provider.php
> +					(array) PluginHelper::getPlugin('system', 'cache'),
```suggestion
					(array) PluginHelper::getPlugin('api-authentication', 'token'),
```

2022-05-18 11:28 UTC, heelc29 commented on plugins/api-authentication/token/services/provider.php
> +	/**
```suggestion
return new class implements ServiceProviderInterface
{
	/**
```

2022-05-18 11:29 UTC, heelc29 commented on plugins/api-authentication/token/services/provider.php
> +					new InputFilter()
```suggestion
					new InputFilter
```
https://ci.joomla.org/joomla/joomla-cms/54234/1/6

2022-05-20 06:42 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 633c2ce13f9c1b6510dfbe1324efe4992e78f9e1<br /><br />Tested successfully using Postman with Joomla 4.2.0-alpha3-dev of 20 May in Wampserver 3.2.8 and PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37804">issues.joomla.org/tracker/joomla-cms/37804</a>.</sub>

2022-05-20 09:00 UTC, heelc29 requested changes
to be identical with #37803

2022-05-20 09:00 UTC, heelc29 commented on plugins/api-authentication/token/services/provider.php
> +use Joomla\Plugin\APIAuthentication\Token\Extension\Token;
```suggestion
use Joomla\Plugin\ApiAuthentication\Token\Extension\Token;
```

2022-05-20 09:00 UTC, heelc29 commented on plugins/api-authentication/token/src/Extension/Token.php
> +namespace Joomla\Plugin\APIAuthentication\Token\Extension;
```suggestion
namespace Joomla\Plugin\ApiAuthentication\Token\Extension;
```

2022-05-20 09:00 UTC, heelc29 commented on plugins/api-authentication/token/token.xml
> +	<namespace path="src">Joomla\Plugin\APIAuthentication\Token</namespace>
```suggestion
	<namespace path="src">Joomla\Plugin\ApiAuthentication\Token</namespace>
```

2022-05-20 09:15 UTC, heelc29 requested changes

2022-05-20 09:15 UTC, heelc29 commented on plugins/api-authentication/token/src/Extension/Token.php
> +	 * @since  __DEPLOY_VERSION__
```suggestion
	 * @var    UserFactoryInterface
	 * @since  __DEPLOY_VERSION__
```

2022-05-20 09:15 UTC, heelc29 commented on plugins/api-authentication/token/src/Extension/Token.php
> +	 * @since  __DEPLOY_VERSION__
```suggestion
	 * @var    InputFilter
	 * @since  __DEPLOY_VERSION__
```

2022-05-20 09:15 UTC, heelc29 commented on plugins/api-authentication/token/src/Extension/Token.php
> +	 * @param   UserFactoryInterface  $userFactory  The user factory
```suggestion
	 * @param   DispatcherInterface   $dispatcher   The dispatcher
	 * @param   array                 $config       An optional associative array of configuration settings
	 * @param   UserFactoryInterface  $userFactory  The user factory
	 * @param   InputFilter           $filter       The input filter
```

2022-05-20 09:52 UTC, heelc29 reviewed
Should here a `\` added?

2022-05-20 09:52 UTC, heelc29 commented on administrator/components/com_plugins/src/Model/PluginModel.php
> +		if (is_array($cacheId))
```suggestion
		if (\is_array($cacheId))
```

2022-05-20 09:52 UTC, heelc29 commented on administrator/components/com_plugins/src/Model/PluginModel.php
> +			$return = $table->load(is_array($pk) ? $pk : array('extension_id' => $pk, 'type' => 'plugin'));
```suggestion
			$return = $table->load(\is_array($pk) ? $pk : ['extension_id' => $pk, 'type' => 'plugin']);
```

2022-05-20 09:52 UTC, heelc29 commented on plugins/api-authentication/token/src/Extension/Token.php
> +		if (!is_object($pluginObject) || !$pluginObject->enabled || !array_key_exists($param, $pluginObject->params))
```suggestion
		if (!\is_object($pluginObject) || !$pluginObject->enabled || !\array_key_exists($param, $pluginObject->params))
```

2022-05-20 11:14 UTC, heelc29 commented
I have tested this item :white_check_mark: successfully on aa76f6c15ef43b861be9a89d5bc2f7305f22a2bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37804">issues.joomla.org/tracker/joomla-cms/37804</a>.</sub>

2022-05-20 12:07 UTC, laoneo commented
@toivo can you test again as there were mainly code style stuff changed, but better be on the safe side. Thanks!

2022-05-20 16:36 UTC, eeshaanSA commented
I have tested this item :white_check_mark: successfully on aa76f6c15ef43b861be9a89d5bc2f7305f22a2bf<br /><br />followed testing instructions and tested successfully. Xampp used. PHP verison:  8.1.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37804">issues.joomla.org/tracker/joomla-cms/37804</a>.</sub>

2022-05-21 01:04 UTC, toivo commented
I have tested this item :white_check_mark: successfully on aa76f6c15ef43b861be9a89d5bc2f7305f22a2bf<br /><br />Tested successfully in Joomla 4.2.0-alpha3-dev of 20 May.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37804">issues.joomla.org/tracker/joomla-cms/37804</a>.</sub>

2022-05-21 01:05 UTC, toivo commented
@laoneo, worked all right with the latest dev version and a new Super User.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37804">issues.joomla.org/tracker/joomla-cms/37804</a>.</sub>

2022-05-21 06:12 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37804">issues.joomla.org/tracker/joomla-cms/37804</a>.</sub>

2022-05-21 19:01 UTC, merged

2022-05-21 19:01 UTC, roland-d commented
Thanks everybody