[4.2] Convert basic api auth plugin to services
joomla/joomla-cms pull request #37803
Opened 2022-05-15 17:44 UTC by laoneo

### Summary of Changes
Converts the basic api auth plugin to services.

### Testing Instructions
- Enable the basic api auth plugin
- Make an API request with basic authentication, for example you can use curl or postman

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

2022-05-16 11:20 UTC, heelc29 commented on plugins/api-authentication/basic/basic.xml
> +		<folder plugin="cache">services</folder>
```suggestion
		<folder plugin="basic">services</folder>
```

2022-05-17 11:36 UTC, heelc29 commented on plugins/api-authentication/basic/services/provider.php
> +					(array) PluginHelper::getPlugin('system', 'cache'),
```suggestion
					(array) PluginHelper::getPlugin('api-authentication', 'basic'),
```

2022-05-17 11:50 UTC, heelc29 commented
Can you please also correct the filenames of the language files in the manifest to: `plg_api-authentication_basic(.sys).ini` (wrong added in #23424 😅)

https://github.com/joomla/joomla-cms/blob/ee81859803672f1c6fee40a1553be3ae7fb47485/plugins/api-authentication/basic/basic.xml#L16-L17

2022-05-17 11:56 UTC, laoneo commented
Done

2022-05-17 12:07 UTC, heelc29 commented on plugins/api-authentication/basic/basic.xml
> +		<language tag="en-GB">language/en-GB/plg_authentication-api_basic.sys.ini</language>
```suggestion
		<language tag="en-GB">language/en-GB/plg_api-authentication_basic.ini</language>
		<language tag="en-GB">language/en-GB/plg_api-authentication_basic.sys.ini</language>
```
api before authentication (see administrator/language/en-GB/plg_api-authentication_basic.ini)

2022-05-17 12:08 UTC, heelc29 commented on plugins/api-authentication/basic/services/provider.php
> + * @subpackage  Authentication.joomla
```suggestion
 * @subpackage  Apiauthentication.basic
```
Also in Basic.php

2022-05-17 12:09 UTC, laoneo commented on plugins/api-authentication/basic/basic.xml
> +		<language tag="en-GB">language/en-GB/plg_authentication-api_basic.sys.ini</language>
:see_no_evil:

2022-05-17 12:15 UTC, heelc29 requested changes
cs

2022-05-17 12:15 UTC, heelc29 commented on plugins/api-authentication/basic/services/provider.php
> +	/**
```suggestion
return new class implements ServiceProviderInterface
{
	/**
```

2022-05-17 12:15 UTC, heelc29 commented on plugins/api-authentication/basic/src/Basic.php
> +	 * @since  __DEPLOY_VERSION__
```suggestion
	 * @var    UserFactoryInterface
	 * @since  __DEPLOY_VERSION__
```

2022-05-17 12:17 UTC, heelc29 commented
In other extensions the file in the `src` folder is in a subfolder `Extension`. Should it also?

2022-05-17 12:44 UTC, heelc29 commented
I have tested this item :white_check_mark: successfully on 94bbd50c0916719f101192a0572e0810abdc2897<br /><br />Thanks @laoneo<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37803">issues.joomla.org/tracker/joomla-cms/37803</a>.</sub>

2022-05-21 07:21 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 94bbd50c0916719f101192a0572e0810abdc2897<br /><br />Tested successfully in Joomla 4.2.0-alpha3-dev of 21 May in Wampserver 3.2.8 using PHP 8.0.15.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37803">issues.joomla.org/tracker/joomla-cms/37803</a>.</sub>

2022-05-21 07:42 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37803">issues.joomla.org/tracker/joomla-cms/37803</a>.</sub>

2022-05-21 18:18 UTC, merged

2022-05-21 18:19 UTC, roland-d commented
Thanks everybody