[4.1][regression] Correctly handle save2copy for menus
joomla/joomla-cms pull request #37813
Opened 2022-05-16 23:26 UTC by zero-24

Pull Request for Issue #37812

### Summary of Changes

Restore the existing behavior before the regression caused by https://github.com/joomla/joomla-cms/pull/37395 as well as fix the Issue from the original report

### Testing Instructions

- setup a 4.1.2 site
- create 2 menus
- create one menu items for the first menu
- open that menu item in edit mode
- change the menu setting to the seccond menu
- Use the "save2copy" feature.
- the change to the menu setting is ignored
- update to 4.1.3
- repeat the steps from above
- it works
- but try it without changing the assigned menu
- it fails as the alias exists already
- apply the patch
- confirm that both cases still work as expected
- try to only change the menu item title
- save2copy
- confirm that the alias number is not just increased but followed the change to the menu title
- try to only change the alias but keep the title
- save2copy
- confirm that the alias has been updated but not the title.

### Actual result BEFORE applying this Pull Request

Issues of "alias exists already" while with save2copy we have an "increment the ID" feature

### Expected result AFTER applying this Pull Request

The alias will be updated as expected any by using save2copy you should not get alias dubliceted issues.

### Documentation Changes Required

n.a

### Mentions

@toivo 
@bembelimen 

Involved within the PR which caused the regression:
@anmode
@chmst
@richard67
@vorayash
@Quy

2022-05-17 01:30 UTC, toivo commented
I have tested this item :white_check_mark: successfully on 096a742d0762a9e31940a12ae06099c634da7472<br /><br />Tested successfully in 4.1.2 upgraded to 4.1.3 and patched, using PHP 8.0.15.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37813">issues.joomla.org/tracker/joomla-cms/37813</a>.</sub>

2022-05-17 06:30 UTC, Webdongle commented
I have tested this item :white_check_mark: successfully on 096a742d0762a9e31940a12ae06099c634da7472<br /><br />Full success<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37813">issues.joomla.org/tracker/joomla-cms/37813</a>.</sub>

2022-05-17 06:56 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37813">issues.joomla.org/tracker/joomla-cms/37813</a>.</sub>

2022-05-18 12:01 UTC, laoneo requested changes

2022-05-18 12:01 UTC, laoneo commented on administrator/components/com_menus/src/Model/ItemModel.php
> +		if (Factory::getApplication()->input->get('task') === 'save2copy' && $data['id'] === 0)
This code here should be moved to a controller. The model is the wrong place. Please change that.

2022-05-18 15:07 UTC, bembelimen commented on administrator/components/com_menus/src/Model/ItemModel.php
> +		if (Factory::getApplication()->input->get('task') === 'save2copy' && $data['id'] === 0)
It's like currently everywhere in Joomla!, so I'm ok to merge (beside that I think, we should improve this code everywhere.)

2022-05-18 15:08 UTC, merged

2022-05-18 15:08 UTC, bembelimen commented
Thx