Package filter in the Extensions: Manage page
joomla/joomla-cms pull request #37838
Opened 2022-05-20 12:40 UTC by nikosdion

### Summary of Changes

Adds a Package filter in the Extensions: Manage page.

### Testing Instructions

Go to System, Manage, Extensions

### Actual result BEFORE applying this Pull Request

Filtering the list of extensions by the extension package ID they belong to is not possible.

### Expected result AFTER applying this Pull Request

You have a Package dropdown filter. Choosing a package shows you that package extension and all extensions Joomla knows belong to that package (based on the recorded package_id in the database).

### Documentation Changes Required

You need to document the Package filter:

* **Package**. Displays only the selected "package" type extension and all extensions which belong to it. Note: You should only uninstall the "package" type extension to prevent extension and core Joomla update problems.

### Translation Changes Required

Two translation keys were added

### Reasoning for this PR

It is very important that users only ever try to uninstall the "package" extension, not the individual extensions a package contains. Failing to do so will cause all sorts of problems:

* Trying to uninstall the package extension displays warnings about missing extensions which cannot be uninstalled.
* Some packages fail to uninstall because their installation scripts expect one or more of the included extensions to be present when the package uninstallation takes place.
* Removing all included extensions but not the package itself will find updates. Installing the updates reinstalls the missing extensions which can be confusing and disorienting for the user.
* Removing some of the extensions included in a package, for example some plugins, may cause the other extensions to fail in unpredictable ways.

Right now the only indication that an extension is part of a package is the meaningless Package ID column. Ask 100 users what that is for and 99 will have no idea.

Even worse, those of us who do know what it is cannot filter by a package ID, making it extremely hard to locate all extensions which belong to a package. We would have to search for the package name, note down the package ID, clear the filter, sort the list by package ID, start going through the pagination until we find the package ID in question in the rightmost column and carefully examine which extensions it contains. This is a very Soviet user experience, the only thing missing are the people in long coats asking us to please follow them to the back room for questioning.

With a filter like that it's easy to pinpoint the extensions included in a package, complete with the package itself. This makes management far easier **on real world sites** (default installations don't really have any packages, rendering this a moot point — but almost nobody runs Joomla like that in the real world).

2022-05-20 14:22 UTC, Kostelano commented on administrator/components/com_installer/forms/filter_manage.xml
> +			desc="COM_INSTALLER_MANAGE_FILTER_PACKAGE_ID_DESC"
```suggestion
			description="COM_INSTALLER_MANAGE_FILTER_PACKAGE_ID_DESC"
```

2022-05-20 14:35 UTC, nikosdion commented on administrator/components/com_installer/forms/filter_manage.xml
> +			desc="COM_INSTALLER_MANAGE_FILTER_PACKAGE_ID_DESC"
Whoops! Thanks

2022-05-21 01:47 UTC, heelc29 requested changes

2022-05-21 01:47 UTC, heelc29 commented on administrator/components/com_installer/src/Field/PackageField.php
> +
```suggestion
```

2022-05-21 01:47 UTC, heelc29 commented on administrator/components/com_installer/src/Helper/InstallerHelper.php
> +		$db         = Factory::getContainer()->get('DatabaseDriver');
```suggestion
		$db         = Factory::getContainer()->get(DatabaseDriver::class);
```

2022-05-21 01:47 UTC, heelc29 commented on administrator/components/com_installer/src/Model/ManageModel.php
> +				->bind(':package_id_2', $packageId, ParameterType::INTEGER);
```suggestion
			$query->where(
				'((' . $db->quoteName('package_id') . ' = :packageId1) OR '
				. '(' . $db->quoteName('extension_id') . ' = :packageId2))'
			)
				->bind([':packageId1',':packageId2'], $packageId, ParameterType::INTEGER);
```

2022-05-21 01:47 UTC, heelc29 commented on administrator/components/com_installer/src/Field/PackageField.php
> +		return array_merge($options, parent::getOptions());
```suggestion
		return array_merge(parent::getOptions(), $options);
```
![image](https://user-images.githubusercontent.com/66922325/169629535-cad4d8d2-c3f6-4c60-8cea-3019f19a0d4f.png)

2022-05-21 01:47 UTC, heelc29 commented on administrator/components/com_installer/src/Helper/InstallerHelper.php
> +			)
```suggestion
			->select(
				$db->quoteName(
					[
						'extension_id',
						'name',
						'element',
					]
				)
			)
```

2022-05-21 07:18 UTC, nikosdion commented on administrator/components/com_installer/src/Helper/InstallerHelper.php
> +		$db         = Factory::getContainer()->get('DatabaseDriver');
OK, I am accepting that, it makes sense. That said, you should do a PR to Joomla itself to change how it fetches the DatabaseDriver from the container. There are far more hits of get('DatabaseDriver') than get(DatabaseDriver::class). It made me think that the _intention_ was to use the hardcoded string.

2022-05-21 07:20 UTC, nikosdion commented on administrator/components/com_installer/src/Field/PackageField.php
> +		return array_merge($options, parent::getOptions());
I am not going to accept that on the grounds of maintaining consistency with the other filter fields of com_users and Joomla in general. Joomla puts the no selection option first on the list. Regardless of our personal preference, that's how Joomla does it, that's how we have to do it in our PRs.

2022-05-21 07:26 UTC, heelc29 commented on administrator/components/com_installer/src/Field/PackageField.php
> +		return array_merge($options, parent::getOptions());
Sorry, the screenshot is before the suggested change 😅

Here is for example the FolderField:
https://github.com/joomla/joomla-cms/blob/444965e0b7d5f0e393691d86d9f634989ebad383/administrator/components/com_installer/src/Field/FolderField.php#L43

2022-05-21 07:29 UTC, nikosdion commented on administrator/components/com_installer/src/Field/PackageField.php
> +		return array_merge($options, parent::getOptions());
Ah, that makes more sense to me now 😄 OK, I will commit this change.

2022-05-21 07:43 UTC, heelc29 commented on administrator/language/en-GB/com_installer.ini
> +COM_INSTALLER_VALUE_PACKAGE_ID_SELECT="- Package -"
```suggestion
COM_INSTALLER_VALUE_PACKAGE_ID_SELECT="- Select Package -"
```
![image](https://user-images.githubusercontent.com/66922325/169641494-2cf0d62a-7ff2-420b-8804-0d1f9c30eaa3.png)

2022-05-21 14:01 UTC, SumCompanyInc commented
I have tested this item :white_check_mark: successfully on 7473cca7b59cc2990798ee9c0b8cf08b4c6a28d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37838">issues.joomla.org/tracker/joomla-cms/37838</a>.</sub>

2022-05-21 19:23 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 7473cca7b59cc2990798ee9c0b8cf08b4c6a28d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37838">issues.joomla.org/tracker/joomla-cms/37838</a>.</sub>

2022-05-21 19:23 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37838">issues.joomla.org/tracker/joomla-cms/37838</a>.</sub>

2022-06-05 22:47 UTC, bembelimen commented
Nice addition, but I will move to 4.2 and ping @roland-d to merge is asap.

2022-06-06 06:06 UTC, nikosdion commented
@bembelimen No problem and thank you!

2022-06-06 16:56 UTC, merged

2022-06-06 16:56 UTC, roland-d commented
Thanks everybody