[4.2]Create a new example plugin
joomla/joomla-cms pull request #37842
Opened 2022-05-21 07:27 UTC by rdeutz

New feature

Thanks to @brianteeman for the idea.

### Summary
New task plugin to check in all checked  out items. 

### Testing Instructions
* Apply patch
* Check out some items
* Create a new task in system/Scheduled Tasks
* Select Global Checkin
* Set Execution Rule to Manual Execution
* Set a Title
* Save
* You should see something like this

<img width="1348" alt="grafik" src="https://user-images.githubusercontent.com/467356/169640897-cebb8a65-6e1e-4bb7-ad1a-784525dd1e5e.png">

* Click on Run Task
* Go Back to the checked out items, they should be checked in

### Documentation Changes Required
Documentation needs to be updated

2022-05-21 07:31 UTC, brianteeman commented on administrator/language/en-GB/plg_task_checkin.ini
> +; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-05-21 07:31 UTC, brianteeman commented on administrator/language/en-GB/plg_task_checkin.sys.ini
> +; (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-05-21 07:31 UTC, brianteeman commented on plugins/task/checkin/checkin.php
> + * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-05-21 07:33 UTC, brianteeman commented on plugins/task/checkin/checkin.php
> + * @since  4.1.0
This is a new plugin and it will not be introduced until 4.2 (I hope) so this should be __DEPLOY_VERSION__

please review all othr @since etc

2022-05-21 07:56 UTC, Kostelano commented on plugins/task/checkin/checkin.xml
> +<extension version="4.2" type="plugin" group="task" method="upgrade">
```suggestion
<extension type="plugin" group="task" method="upgrade">
```

Version is not needed. It is present only in the scheduler plugins, it must also be removed there.

2022-05-21 08:25 UTC, heelc29 requested changes

2022-05-21 08:25 UTC, heelc29 commented on administrator/language/en-GB/plg_task_checkin.ini
> +
```suggestion
```

2022-05-21 08:25 UTC, heelc29 commented on plugins/task/checkin/checkin.php
> +			'onExecuteTask'        => 'standardRoutineHandler'
```suggestion
			'onTaskOptionsList' => 'advertiseRoutines',
			'onExecuteTask'     => 'standardRoutineHandler'
```

2022-05-21 08:25 UTC, heelc29 commented on plugins/task/checkin/checkin.php
> +		$results = array();
```suggestion
		$results = [];
```

2022-05-21 08:25 UTC, heelc29 commented on plugins/task/checkin/checkin.xml
> +	<languages>
```suggestion
	<description>PLG_TASK_CHECKIN_XML_DESCRIPTION</description>
	<files>
		<filename plugin="checkin">checkin.php</filename>
	</files>
	<languages>
```

2022-05-21 08:34 UTC, HLeithner commented
Nice plugin but blindly checking in all it's seems wrong to me. Can we get a parameter which allows us to configure an expire timeframe?

Something lime "Minutes to expire" default 60?

2022-05-21 09:22 UTC, richard67 commented
> Nice plugin but blindly checking in all it's seems wrong to me. Can we get a parameter which allows us to configure an expire timeframe?
> 
> Something lime "Minutes to expire" default 60?

I just wanted to say the same.

2022-05-21 11:36 UTC, Kostelano commented on plugins/task/checkin/checkin.xml
> +	<version>4.2</version>
```suggestion
	<version>4.2.0</version>
```

2022-05-21 14:33 UTC, brianteeman commented
> > Nice plugin but blindly checking in all it's seems wrong to me. Can we get a parameter which allows us to configure an expire timeframe?
> > 
> > Something lime "Minutes to expire" default 60?
> 
> I just wanted to say the same.

Except the core component does it blindly as well

2022-05-21 14:43 UTC, laoneo commented
Can you please use the modern way with a service provider.

2022-05-21 15:48 UTC, richard67 commented
> > > Nice plugin but blindly checking in all it's seems wrong to me. Can we get a parameter which allows us to configure an expire timeframe?
> > > Something lime "Minutes to expire" default 60?
> > 
> > 
> > I just wanted to say the same.
> 
> Except the core component does it blindly as well

The core component is change controlled by a human while a scheduler task runs unattended.

2022-05-21 16:15 UTC, rdeutz commented
Changed so that you can set a delay time.

2022-05-21 16:34 UTC, richard67 commented on plugins/task/checkin/checkin.php
> +			;
```suggestion
				->set($this->db->quoteName('checked_out_time') . ' = NULL');
```
Fix PHP CS check failing in Drone.

2022-05-22 13:14 UTC, rdeutz commented
needs a bit more time fighting with the service provider

2022-05-23 09:13 UTC, heelc29 requested changes

2022-05-23 09:13 UTC, heelc29 commented on plugins/task/checkin/src/checkin.xml
> +		<filename plugin="checkin">checkin.php</filename>
```suggestion
		<folder plugin="checkin">services</folder>
		<folder>src</folder>
```

2022-05-23 09:13 UTC, heelc29 commented on plugins/task/checkin/services/provider.php
> + * @subpackage  System.cache
```suggestion
 * @subpackage  Task.Checkin
```

2022-05-23 09:13 UTC, heelc29 commented on plugins/task/checkin/services/provider.php
> +				$dispatcher             = $container->get(DispatcherInterface::class);
```suggestion
				$plugin     = PluginHelper::getPlugin('task', 'checkin');
				$dispatcher = $container->get(DispatcherInterface::class);
```

2022-05-23 09:13 UTC, heelc29 commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @since 4.1.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2022-05-23 09:15 UTC, richard67 commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @since 4.1.0
@heelc29 I think this suggestion here is wrong because the file has been created in 4.1.0 and with this PR here it's only moved around.

2022-05-23 09:17 UTC, richard67 commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @since 4.1.0
Ah, no, silly me. forget my previous comment.

2022-05-23 09:18 UTC, heelc29 commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @since 4.1.0
@richard67 This is a new plugin, isn't id?

2022-05-23 09:20 UTC, richard67 commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @since 4.1.0
@heelc29 Yes, I've noticed meanwhile ... I had another PR in mind.

2022-05-23 09:20 UTC, heelc29 commented on plugins/task/checkin/src/Extension/Checkin.php
> +				$delayTime = JDate::getInstance()->sub(new DateInterval('PT1H'));
Use `Joomla\CMS\Date\Date`
The Interval is fixed and field `delay` is not used

2022-05-23 09:23 UTC, laoneo commented on plugins/task/checkin/src/Extension/Checkin.php
> +				$delayTime = JDate::getInstance()->sub(new DateInterval('PT1H'));
Can this here be changed to `(new \DateTime())->sub(new DateInterval('PT1H'));` or do we have a timezone issue as the CMS Date takes into account the timezone of the current user?

2022-05-23 12:38 UTC, rdeutz commented on plugins/task/checkin/src/Extension/Checkin.php
> +				$delayTime = JDate::getInstance()->sub(new DateInterval('PT1H'));
timezone should not be something we have to respect

2022-05-23 12:38 UTC, rdeutz commented on plugins/task/checkin/src/Extension/Checkin.php
> +				$delayTime = JDate::getInstance()->sub(new DateInterval('PT1H'));
used Allons suggestion

2022-05-23 12:53 UTC, laoneo commented on plugins/task/checkin/src/Extension/Checkin.php
> +				$delayTime = JDate::getInstance()->sub(new DateInterval('PT1H'));
Then I would go with native DateTime

2022-05-23 12:54 UTC, laoneo approved these changes

2022-05-23 12:55 UTC, richard67 commented
PHPCS failing in drone: https://ci.joomla.org/joomla/joomla-cms/54464/1/6

2022-05-23 12:56 UTC, laoneo commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @var    ApiApplication
This here is probably a CMSApplicationInterface

2022-05-23 13:00 UTC, laoneo commented on plugins/task/checkin/src/Extension/Checkin.php
> +		$delay = (int) $event->getArgument('params')->delay ?? 1;
Will this here not throw a warning when `$event->getArgument('params')` returns null, becuase of the cast?

2022-05-23 14:30 UTC, richard67 commented on plugins/task/checkin/src/Extension/Checkin.php
> +				$date = new \DateTime();
```suggestion
				$date = new \DateTime;
```
Fix PHPCS failing in drone.

@rdeutz Your previous CS fix did not really fix it, see the error log in drone:
```
FILE: /********/src/plugins/task/checkin/src/Extension/Checkin.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 124 | ERROR | [x] Instanciating new class without parameters does
     |       |     not require brackets.
     |       |     (Joomla.Classes.InstantiateNewClasses.NewClass)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

2022-05-23 14:35 UTC, rdeutz commented on plugins/task/checkin/src/Extension/Checkin.php
> +		$delay = (int) $event->getArgument('params')->delay ?? 1;
Do we have any documentation for this, I borred this from Token plugin

2022-05-23 14:36 UTC, rdeutz commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @var    ApiApplication
Do we have any documentation for this, I borred this from Token plugin

2022-05-23 14:41 UTC, rdeutz commented on plugins/task/checkin/src/Extension/Checkin.php
> +		$delay = (int) $event->getArgument('params')->delay ?? 1;
$event->getArgument('params') shoud be set

2022-05-30 10:53 UTC, laoneo commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @var    ApiApplication
It is wrong on the token plugin as well. Target is to use whenever possible CMSApplicationInterface.

2022-06-02 12:04 UTC, rdeutz commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @var    ApiApplication
if you can give me a hint how I am going to do it

2022-06-02 12:25 UTC, laoneo commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @var    ApiApplication
```suggestion
	 * @var    CMSApplicationInterface
```

2022-06-02 12:26 UTC, laoneo commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @var    ApiApplication
Only the doc block class is wrong

2022-06-04 10:55 UTC, richard67 requested changes

2022-06-04 10:55 UTC, richard67 commented on plugins/task/checkin/services/provider.php
> +				$checkin = new Checkin (
```suggestion
				$checkin = new Checkin(
```
Fix the PHP code style check failing in Drone.

2022-06-04 15:05 UTC, richard67 commented
@rdeutz For the SQL and the ExtensionHelper see https://github.com/rdeutz/joomla-cms/pull/16 . But please also apply the changes suggested here in review comments.

2022-06-04 15:18 UTC, richard67 approved these changes

2022-06-04 15:23 UTC, heelc29 commented on plugins/task/checkin/src/Extension/Checkin.php
> +use Joomla\CMS\Application\ApiApplication;
```suggestion
use Joomla\CMS\Application\CMSApplicationInterface;
```

2022-06-05 17:08 UTC, heelc29 requested changes

2022-06-05 17:08 UTC, heelc29 commented on plugins/task/checkin/src/Extension/Checkin.php
> +			'onContentPrepareForm' => 'enhanceTaskItemForm',
```suggestion
			'onTaskOptionsList'    => 'advertiseRoutines',
			'onExecuteTask'        => 'standardRoutineHandler',
			'onContentPrepareForm' => 'enhanceTaskItemForm',
```

2022-06-05 17:08 UTC, heelc29 commented on plugins/task/checkin/src/Extension/Checkin.php
> +	 * @since __DEPLOY_VERSION__
```suggestion
	 * @param   ExecuteTaskEvent  $event  The onExecuteTask event
	 *
	 * @return  integer  The exit code
	 *
	 * @since   __DEPLOY_VERSION__
```

2022-06-05 17:08 UTC, heelc29 commented on administrator/language/en-GB/plg_task_checkin.ini
> +PLG_TASK_CHECKIN_DELAY_LABEL="Checkin before delay in hours"
alpha sort
```suggestion
PLG_TASK_CHECKIN="Task - Check-in"
PLG_TASK_CHECKIN_DELAY_LABEL="Checkin before delay in hours"
PLG_TASK_CHECKIN_DESC="Check in checked out items."
PLG_TASK_CHECKIN_TITLE="Global Check-in"
PLG_TASK_CHECKIN_XML_DESCRIPTION="Plugin to check in checked out items."
```

2022-06-06 10:58 UTC, richard67 commented on plugins/task/checkin/services/provider.php
> +					(array) $plugin,
```suggestion
					(array) $plugin
```
This should fix the syntax error in the system tests at login to the backend after the new installation.
It's a funxtion call here, not an array definition, so we should not have a comma after the last parameter like we would have it in an array after the last value.

2022-06-06 14:11 UTC, richard67 commented on plugins/task/checkin/src/Extension/Checkin.php
> +					$db->quoteName('checked_out_time') . ' < ' . $db->quote($delayTime->format('c'))
In database the checked_out_time is in UTC, but `$delayTime->format('c')` provides a time in the server time zone, here "Europe/Berlin" = UTC+2, so I have to adjust a delay time of 3 hours to get items which I just have checked out not checked in by the plugin. It needs UTC time in the WHERE clause of the query.

2022-06-06 14:36 UTC, richard67 commented on plugins/task/checkin/src/Extension/Checkin.php
> +					$db->quoteName('checked_out_time') . ' < ' . $db->quote($delayTime->format('c'))
```suggestion
				$delayTime = Factory::getDate('now', 'UTC')->sub(new \DateInterval('PT' . $delay . 'H'))->toSql();
				$query->where(
					$db->quoteName('checked_out_time') . ' < ' . $db->quote($delayTime)
```
And add a `use Joomla\CMS\Factory;` statement at the top of the file at line 17.

Reason: In database the checked_out_time is in UTC, but `$delayTime->format('c')` provides a time in the server time zone, here "Europe/Berlin" = UTC+2, so I have to adjust a delay time of 3 hours to get items which I just have checked out not checked in by the plugin. It needs UTC time in the WHERE clause of the query.

And please update your testing instructions so they mention the delay time.

2022-06-08 07:25 UTC, laoneo commented on plugins/task/checkin/src/Extension/forms/checkin_params.xml
> +<?xml version="1.0" encoding="utf-8" ?>
As #37954 got merged, can you move the forms folder to the root of the plugin.

2022-06-11 09:45 UTC, richard67 commented on plugins/task/checkin/src/Extension/Checkin.php
> +use Joomla\CMS\Plugin\CMSPlugin;
```suggestion
use Joomla\CMS\Factory;
use Joomla\CMS\Plugin\CMSPlugin;
```
Was mentioned in my previous review comment that this should be added, too.

2022-06-11 10:23 UTC, richard67 commented on plugins/task/checkin/src/Extension/forms/checkin_params.xml
> +<?xml version="1.0" encoding="utf-8" ?>
@laoneo Maybe it helps if you make a PR for @rdeutz 's branch of this PR?

2022-09-26 22:09 UTC, woluweb commented
Hi there.
What is the status of this PR? What is preventing it from being merged?
It would indeed be interesting to have more useful / practical examples of working Tasks :)

2022-11-27 20:01 UTC, zero-24 commented
Without knowing that this PR had be proposed as core plugin already I have published an extension called plg_task_checkin: https://github.com/zero-24/plg_task_checkin I have also been asked to contribute it back as plg_task_globalcheckin (https://github.com/joomla/joomla-cms/pull/39323). I have closed said PR so this PR can be taken but I would like to ask to rename the core plugin to plg_task_globalcheckin to not conflict with the now published to the live extension.
Thanks :)

2023-05-08 15:03 UTC, HLeithner commented
This pull request has been automatically rebased to 5.0-dev. No new features will be merged into Joomla! 4.3 series. Joomla! 4.4 series is a bridge release to make migration from Joomla! 4 to 5 as smooth as possible.

2023-06-10 07:48 UTC, HLeithner commented
@rdeutz can you please update this pr and automatically create a task for new installations please? I would like to have this in 5.0

2023-06-23 08:09 UTC, richard67 commented on installation/sql/mysql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
```suggestion
(0, 'plg_task_checkfiles', 'plugin', 'checkfiles', 'task', 0, 1, 1, 0, 1, '', '{}', '', 1, 0),
(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
(0, 'plg_task_requests', 'plugin', 'requests', 'task', 0, 1, 1, 0, 1, '', '{}', '', 3, 0),
(0, 'plg_task_sitestatus', 'plugin', 'sitestatus', 'task', 0, 1, 1, 0, 1, '', '{}', '', 4, 0),
```
Alpha-order (the order number is already 2 as it should be)

2023-06-23 08:10 UTC, richard67 commented on installation/sql/postgresql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
```suggestion
(0, 'plg_task_checkfiles', 'plugin', 'checkfiles', 'task', 0, 1, 1, 0, 1, '', '{}', '', 1, 0),
(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
(0, 'plg_task_requests', 'plugin', 'requests', 'task', 0, 1, 1, 0, 1, '', '{}', '', 3, 0),
(0, 'plg_task_sitestatus', 'plugin', 'sitestatus', 'task', 0, 1, 1, 0, 1, '', '{}', '', 4, 0),
```
Alpha-order (the order number is already 2 as it should be)

2023-06-23 08:14 UTC, richard67 commented on installation/sql/mysql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
Other question: Shall it really be named "plg_task_globalcheckin"? If so, file names and language string key and so on have to be adjusted to that. Or change the name back to like it was before the last commit, "plg_task_checkin".

2023-06-23 08:14 UTC, richard67 commented on installation/sql/postgresql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
Other question: Shall it really be named "plg_task_globalcheckin"? If so, file names and language string key and so on have to be adjusted to that. Or change the name back to like it was before the last commit, "plg_task_checkin".

2023-06-23 09:17 UTC, rdeutz commented on installation/sql/postgresql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
name will be changed as requested by Tobias

2023-06-23 09:18 UTC, richard67 commented on installation/sql/postgresql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
Then you have to rename files and folders and language keys.

2023-06-23 09:20 UTC, richard67 commented on libraries/src/Extension/ExtensionHelper.php
> +        ['plugin', 'globalcheckin', 'task', 0],
```suggestion
        ['plugin', 'checkfiles', 'task', 0],
        ['plugin', 'globalcheckin', 'task', 0],
        ['plugin', 'requests', 'task', 0],
        ['plugin', 'sitestatus', 'task', 0],
```
Alpha-ordering + code style fix (no white space at end of line)

2023-06-23 11:05 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-06-04.sql
> +(0, 'plg_task_checkin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 5, 0);
```suggestion
(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 5, 0);

```

2023-06-23 11:06 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.2.0-2022-06-04.sql
> +(0, 'plg_task_checkin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 5, 0);
```suggestion
(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 5, 0);

```

2023-06-23 11:07 UTC, richard67 commented on installation/sql/mysql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
```suggestion
(0, 'plg_task_globalcheckin', 'plugin', 'globalcheckin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
```

2023-06-23 11:07 UTC, richard67 commented on installation/sql/postgresql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
```suggestion
(0, 'plg_task_globalcheckin', 'plugin', 'globalcheckin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
```

2023-06-23 12:02 UTC, rdeutz commented on installation/sql/postgresql/base.sql
> +(0, 'plg_task_globalcheckin', 'plugin', 'checkin', 'task', 0, 1, 1, 0, 0, '', '{}', '', 2, 0),
Thanks I already noticed that it is not working when I install joomla

2023-06-23 12:03 UTC, rdeutz commented
@richard67 Do we need to rename the sql files?

2023-06-23 12:06 UTC, richard67 commented
> @richard67 Do we need to rename the sql files?

Yes, e.g. to "5.0.0-2023-06-23.sql" (or anything else with 5.0.0 and a date younger than 2023-03-17).

2023-06-23 12:18 UTC, rdeutz commented
> Yes, e.g. to "5.0.0-2023-06-23.sql" (or anything else with 5.0.0 and a date younger than 2023-03-17).

Younger? 5.0.0-2023-06-23.sql is older as 2023-03-17, I am confused

2023-06-23 12:19 UTC, richard67 commented
> > Yes, e.g. to "5.0.0-2023-06-23.sql" (or anything else with 5.0.0 and a date younger than 2023-03-17).
> 
> Younger? 5.0.0-2023-06-23.sql is older as 2023-03-17, I am confused

No. June 23 is newer than March 17, or not?

2023-06-23 12:24 UTC, rdeutz commented
I renamed the files. Thanks @richard67 

This is now ready to test.

2023-06-23 12:32 UTC, richard67 commented
@rdeutz The magic with the ISO date format "YYYY-MM-DD" is that alphabetical order is also order by time.

2023-06-23 16:47 UTC, alikon commented
there are no prebuild + pr download package for 5.0-dev
![image](https://github.com/joomla/joomla-cms/assets/181681/22817c2b-5767-42bf-ba5a-f3e0fdbb33c9)

as for 4.4-dev
![image](https://github.com/joomla/joomla-cms/assets/181681/3d62cfe7-9def-4edd-ac5e-20a68bc23ae5)

can someone please check?

2023-06-23 16:53 UTC, brianteeman commented on plugins/task/globalcheckin/services/provider.php
> + * @subpackage  Task.Checkin
```suggestion
 * @subpackage  Task.Globalcheckin
```

2023-06-23 16:54 UTC, brianteeman commented on plugins/task/globalcheckin/src/Extension/Globalcheckin.php
> + * @subpackage  Task.Checkin
```suggestion
 * @subpackage  Task.Globalcheckin
```

2023-06-23 16:54 UTC, brianteeman commented on plugins/task/globalcheckin/src/Extension/Globalcheckin.php
> + * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
```

2023-06-23 16:54 UTC, brianteeman commented on plugins/task/globalcheckin/src/Extension/Globalcheckin.php
> + * Task plugin with routines to check in check out item.
```suggestion
 * Task plugin with routines to check in a checked out item.
```

2023-06-23 16:55 UTC, brianteeman commented on plugins/task/globalcheckin/src/Extension/Globalcheckin.php
> +     * Standard routine method for the checkin routine.
```suggestion
     * Standard method for the checkin routine.
```

??

2023-06-23 16:58 UTC, brianteeman commented on administrator/language/en-GB/plg_task_globalcheckin.sys.ini
> +; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
; (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
```

2023-06-23 17:00 UTC, brianteeman commented on administrator/language/en-GB/plg_task_globalcheckin.ini
> +PLG_TASK_GLOBALCHECKIN_DELAY_LABEL="Checkin before delay in hours"
Thi string is not correct but I can't correct it as I am not sure what the delay is. Is it the ammount of time something must have been checked out before this plugin will check it in?

2023-07-13 10:59 UTC, rdeutz commented on administrator/language/en-GB/plg_task_globalcheckin.ini
> +PLG_TASK_GLOBALCHECKIN_DELAY_LABEL="Checkin before delay in hours"
Exactly, it is the time something must be checked out before the plugin checks it in.

2023-07-26 15:57 UTC, richard67 commented
Meanwhile the newest update SQL script in 5.0-dev is "5.0.0-2023-07-25.sql" so the scripts "5.0.0-2023-06-23.sql" in this PR need to be renamed to something newer that that, e.g. to "5.0.0-2023-07-26.sql".

2023-07-26 19:13 UTC, brianteeman commented on plugins/task/globalcheckin/services/provider.php
> + * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
```

2023-07-26 19:17 UTC, brianteeman commented on administrator/language/en-GB/plg_task_globalcheckin.ini
> +PLG_TASK_GLOBALCHECKIN_DELAY_LABEL="Checkin before delay in hours"
```suggestion
PLG_TASK_GLOBALCHECKIN_DELAY_LABEL=""Minimum Period Before Checkin (hours)"
```

2023-07-27 06:40 UTC, HLeithner commented on administrator/language/en-GB/plg_task_globalcheckin.ini
> +PLG_TASK_GLOBALCHECKIN_DELAY_LABEL="Checkin before delay in hours"
2 quotes at the beginning are wrong

2023-07-27 06:47 UTC, brianteeman commented on administrator/language/en-GB/plg_task_globalcheckin.ini
> +PLG_TASK_GLOBALCHECKIN_DELAY_LABEL="Checkin before delay in hours"
oops

2023-08-26 09:13 UTC, richard67 commented
@rdeutz It needs to rename the update SQL scripts again because meanwhile we have some with a higher schema version (base name) in the repo so yours would not run on an update. I suggest to rename them to "5.0.0-2023-08-27.sql" because there are other PR's proposed which will already use "5.0.0-2023-08-22.sql" to "5.0.0-2023-08-26.sql".

2023-08-26 09:21 UTC, rdeutz commented
@richard67 done, with a bit luck some tests today and we can merge this

2023-08-26 09:23 UTC, richard67 commented
> @richard67 done, with a bit luck some tests today and we can merge this

@rdeutz Thanks.

2023-08-26 10:43 UTC, webgras commented
I have tested this item :white_check_mark: successfully on 6b3e80e5ad1a97ce91cd0cd310f21604134e6fd0<br /><br />also check articles on two different times

tested on J 5.0.0-beta1-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37842">issues.joomla.org/tracker/joomla-cms/37842</a>.</sub>

2023-08-26 11:00 UTC, heelc29 commented on plugins/task/globalcheckin/forms/globalcheckin_params.xml
> +<?xml version="1.0" encoding="utf-8" ?>
```suggestion
<?xml version="1.0" encoding="UTF-8" ?>
```

2023-08-26 11:00 UTC, heelc29 commented on plugins/task/globalcheckin/globalcheckin.xml
> +<?xml version="1.0" encoding="utf-8" ?>
```suggestion
<?xml version="1.0" encoding="UTF-8" ?>
```

2023-08-26 11:01 UTC, heelc29 commented on plugins/task/globalcheckin/src/Extension/Globalcheckin.php
> +    protected $app;
use $this->getApplication()

2023-08-26 11:21 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 6b3e80e5ad1a97ce91cd0cd310f21604134e6fd0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37842">issues.joomla.org/tracker/joomla-cms/37842</a>.</sub>

2023-08-26 11:27 UTC, alikon commented
some kind of cache issue
btw i'm fully confortable with this pr
waiting for the last mile
i'll redo my test

2023-08-26 12:55 UTC, richard67 commented
@alikon @webgras Could you test again with the latest changes? Thanks in advance.

2023-08-26 13:14 UTC, heelc29 commented on plugins/task/globalcheckin/src/Extension/Globalcheckin.php
> +use Joomla\CMS\Application\CMSApplicationInterface;
```suggestion
```
phpcs error

2023-08-26 13:46 UTC, heelc29 commented
I have tested this item :white_check_mark: successfully on 6b3e80e5ad1a97ce91cd0cd310f21604134e6fd0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37842">issues.joomla.org/tracker/joomla-cms/37842</a>.</sub>

2023-08-26 13:51 UTC, webgras commented
I have tested this item :white_check_mark: successfully on 6b3e80e5ad1a97ce91cd0cd310f21604134e6fd0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37842">issues.joomla.org/tracker/joomla-cms/37842</a>.</sub>

2023-08-26 13:52 UTC, merged

2023-08-26 13:52 UTC, HLeithner commented
finally thanks all

2023-08-26 13:58 UTC, rdeutz commented
Thanks to all who helped to get this done