[4.2] task start scheduler on friend site via webcron
joomla/joomla-cms pull request #37878
Opened 2022-05-24 14:26 UTC by alikon

### Summary of Changes
Added a new task to start the scheduler on a friend site via Webcron

### Testing Instructions

apply pr  (on site A)
discover extension and install the new task plugin
enable the  plugin

(on site B) site suppose that doesn't have crontab
enable the webcron
![image](https://user-images.githubusercontent.com/181681/170050394-c6bd0685-ff71-4ccf-bde6-b8e1dc5fc53e.png)
copy the link
enable some task  ie (sleep) for example

on site (A)
create a new task WebCronStarter
![image](https://user-images.githubusercontent.com/181681/170050844-b855dfbd-3608-42cf-89d1-2fd5307ec8c6.png)
and paste the URL copied before from (site B)
run the scheduler from cli for example 
` php cli/joomla.php scheduler:run`

(on site B) 
check that the task have been executed

### Actual result BEFORE applying this Pull Request
N/A

### Expected result AFTER applying this Pull Request
you can schedule a task to start the scheduler on a friend site via webcron

### Documentation Changes Required

2022-05-24 15:33 UTC, Kostelano commented on plugins/task/webcronstart/webcronstart.xml
> +	<version>4.0.0</version>
```suggestion
	<copyright>(C) 2022 Open Source Matters, Inc.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<authorEmail>admin@joomla.org</authorEmail>
	<authorUrl>www.joomla.org</authorUrl>
	<version>4.2.0</version>

```

2022-05-24 15:35 UTC, Kostelano commented on plugins/task/webcronstart/webcronstart.xml
> +	<copyright>(C) 2020 Open Source Matters, Inc.</copyright>
```suggestion
	<copyright>(C) 2022 Open Source Matters, Inc.</copyright>
```

2022-05-24 15:35 UTC, Kostelano commented on plugins/task/webcronstart/webcronstart.xml
> +	<version>4.0.0</version>
```suggestion
	<version>4.2.0</version>
```

2022-05-24 17:04 UTC, richard67 commented
I can not see any SQL script changes in this PR to add the new plugin to the extensions table, neither in base.sql for new installation nor in a new update SQL script for updates.

2022-05-24 17:08 UTC, alikon commented
i'll add...
but as it is , is testable,  just discover

2022-05-24 17:12 UTC, richard67 commented
> i'll add...
> but as it is , is testable, just discover

Yes, it is testable in this state … but not mergeable ;-)

2022-05-24 18:56 UTC, richard67 commented
@alikon Regarding the update SQL scripts please look up in other update SQL scripts of the 4.2-dev branch how we add extensions, especially regarding the new INSERT IGNORE (MySQL) or ON CONFLICT DO NOTHING (PostgreSQL) which was introduced with PR #37156 , and also regarding columns which we do not use in update SQL scripts when inserting extensions.

2022-05-24 19:03 UTC, richard67 commented
@alikon In addition, make sure to use the right “ordering” values in the I sent statements in the update SQL script. The values should be the same as in base.sql, but currently they are different in your PR (16 in the update SQL versus 5 in base.sql).

2022-05-24 19:13 UTC, alikon commented
@richard67 frankly speaking i don't think... those are _"strictly"_ needed. 
anyway  feel free to enhance it, this pr is open

p.s
for the `ordering` field what I should do ?

2022-05-24 19:18 UTC, richard67 commented
> @richard67 frankly speaking i don't think... those are _"strictly"_ needed. anyway feel free to enhance it, this pr is open

In my PR to which I referred to it is explained in detail why they were added, and it should not be a big thing for you to add that here, too. I am off my desk today and limited to mobile so I won’t be able to make a PR.

> p.s for the `ordering` field what I should do ?

Use value 5 and not 16 in the update SQL script.

2022-05-24 19:21 UTC, richard67 commented
> @richard67 frankly speaking i don't think... those are _"strictly"_ needed. anyway feel free to enhance it, this pr is open

@alikon I just see I was wrong, we do not need INSERT IGNORE here, it was for other cases where we used IDs. Sorry for the confusion.

2022-05-24 19:30 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-05-24.sql
> +(0, 'plg_task_webcronstart', 'plugin', 'webcronstart', 'task', 0, 1, 1, 0, 0, '', '{}', '', 16, 0);
```suggestion
(0, 'plg_task_webcronstart', 'plugin', 'webcronstart', 'task', 0, 1, 1, 0, 0, '', '{}', '', 5, 0);
```

2022-05-24 19:31 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.2.0-2022-05-24.sql
> +(0, 'plg_task_webcronstart', 'plugin', 'webcronstart', 'task', 0, 1, 1, 0, 0, '', '{}', '', 16, 0);
```suggestion
(0, 'plg_task_webcronstart', 'plugin', 'webcronstart', 'task', 0, 1, 1, 0, 0, '', '{}', '', 5, 0);
```

2022-05-25 06:28 UTC, alikon commented on administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-05-24.sql
> +(0, 'plg_task_webcronstart', 'plugin', 'webcronstart', 'task', 0, 1, 1, 0, 0, '', '{}', '', 16, 0);
why 5 ??
https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/components/com_admin/sql/updates/postgresql/4.1.0-2021-11-20.sql#L47-L53
```sql
-- Add plugins to "#__extensions"
INSERT INTO "#__extensions" ("package_id", "name", "type", "element", "folder", "client_id", "enabled", "access", "protected", "locked", "manifest_cache", "params", "custom_data", "ordering", "state") VALUES
(0, 'plg_system_schedulerunner', 'plugin', 'schedulerunner', 'system', 0, 1, 1, 0, 0, '', '{}', '', 15, 0),
(0, 'plg_system_tasknotification', 'plugin', 'tasknotification', 'system', 0, 1, 1, 0, 1, '', '', '', 22, 0),
(0, 'plg_task_checkfiles', 'plugin', 'checkfiles', 'task', 0, 1, 1, 0, 0, '', '{}', '', 15, 0),
(0, 'plg_task_demotasks', 'plugin', 'demotasks', 'task', 0, 1, 1, 0, 0, '', '{}', '', 15, 0),
(0, 'plg_task_requests', 'plugin', 'requests', 'task', 0, 1, 1, 0, 0, '', '{}', '', 15, 0),
(0, 'plg_task_sitestatus', 'plugin', 'sitestatus', 'task', 0, 1, 1, 0, 0, '', '{}', '', 15, 0);
```

i've choosed  16 cause is bigger than 15

2022-05-25 06:40 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-05-24.sql
> +(0, 'plg_task_webcronstart', 'plugin', 'webcronstart', 'task', 0, 1, 1, 0, 0, '', '{}', '', 16, 0);
Hmm ... in base.sql all task scheduler plugins seem to have values 0 to 5. No idea why it was done differently in that update SQL script. Maybe someone else has an idea.

2022-05-25 06:47 UTC, toivo commented
After site A has the PR applied and the New Task plugin enabled the site crashes - JROOT\plugins\task\webcronstart\services\provider.php:49
An error has occurred.
0 syntax error, unexpected end of file, expecting ";"
#Fields: datetime	priority clientip	category	message
2022-05-25T06:35:59+00:00	CRITICAL 127.0.0.1	error	Uncaught Throwable of type ParseError thrown with message "syntax error, unexpected end of file, expecting ";"". Stack trace: #0 [ROOT]\libraries\src\Extension\ExtensionManagerTrait.php(94): Joomla\CMS\Application\CMSApplication->loadExtension('Joomla\\CMS\\Exte...', 'webcronstart:ta...', '[ROOT]...')

Did the following to get back to the back end:
- removed blank link 49
- changed line 48 from } to };<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37878">issues.joomla.org/tracker/joomla-cms/37878</a>.</sub>

2022-05-25 06:59 UTC, alikon commented
good spot fixed

2022-05-25 09:20 UTC, toivo commented
I have tested this item :white_check_mark: successfully on f9a26af57e07af9b878a638a1fa351c27bec8263<br /><br />Tested successfully on two 4.2.0-beta1-dev of 25 May.  The **PR#37868] - [4.1] Fix generate web cron key** was applied first in site B.  Added to the CLI command the following arguments:  **--id 1 --verbose** and received a normal response to the command prompt.  Without **--id 1** received the message _"No tasks due!"_<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37878">issues.joomla.org/tracker/joomla-cms/37878</a>.</sub>

2022-05-25 09:28 UTC, heelc29 requested changes

2022-05-25 09:28 UTC, heelc29 commented on plugins/task/webcronstart/src/extension/Webcronstart.php
> +	 * @since 4.1.0
```suggestion
	 * @since __DEPLOY_VERSION__
```

2022-05-25 09:28 UTC, heelc29 commented on plugins/task/webcronstart/src/extension/forms/start_parameters.xml
> +					required="true"
```suggestion
				name="url"
				type="text"
				label="PLG_TASK_WEBCRONSTART_URL_LABEL"
				description="PLG_TASK_WEBCRONSTART_URL_DESC"
				required="true"
```

2022-05-25 09:28 UTC, heelc29 commented on plugins/task/webcronstart/webcronstart.xml
> +</extension>
add EOF

2022-05-25 09:28 UTC, heelc29 commented on administrator/language/en-GB/plg_task_webcronstart.ini
> +PLG_TASK_WEBCRONSTART_DESC="Starts the WebCron service for the friend site."
Please alphasort and add EOF

2022-05-25 09:28 UTC, heelc29 commented on administrator/language/en-GB/plg_task_webcronstart.sys.ini
> +PLG_TASK_WEBCRONSTART_XML_DESCRIPTION="Start the webcron service for the friend site."
add EOF

2022-05-25 09:28 UTC, heelc29 commented on plugins/task/webcronstart/src/extension/Webcronstart.php
> +			$response = HttpFactory::getHttp($options)->get($params->url, [], 300);
timeout parameter is not used here

2022-05-25 09:40 UTC, laoneo commented
I can't imagine a use case for a CMS where a remote web cron task should be executed on a regular basis. It is a CMS and not an administration panel. If it would be some kind of web hock feature for actions like an article save or user create, then ok. This plugin would be a perfect fit for the JED, but not for the core.

2022-05-25 09:58 UTC, richard67 commented
@alikon Currently api and system tests are failing with loging in to backend after having made a new installation. The screenshot made from the failed login shows a `syntax error, unexpected ')'`, unfortunately not with file and line number: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.2-dev/37878/system-tests/54571/InstallCest.configureJoomla.mysql.fail.png . I suggest you test that, make a new installation with your branch and then login to backend.

2022-05-25 10:36 UTC, bembelimen commented
Just wondering, where is the difference to the "Get-Request" Task, which is already in the system?

2022-05-25 11:33 UTC, closed without merging