Multi-Factor Authentication (replaces Two Factor Authentication)
joomla/joomla-cms pull request #37912
Opened 2022-05-27 15:36 UTC by nikosdion

# Improved Two Factor Authentication

Replaces #37811 

## ATTENTION TESTERS

This PR replaces plugins and has changes in the JavaScript. If you are not using a prebuilt package you need to do the following:

* Run `composer install`
* Run `npm ci`
* Delete the file `administrator/cache/autoload_psr4.php`

## Executive Summary

This PR implements Multi-Factor Authentication (MFA) using a “Captive Login” approach. 

Unlike the temporary Two Factor Authentication solution that was supposed to last for a maximum of one year and we've been using until today (nine years later...), it does NOT require you to enter your Security Code with your login information (e.g. username and password). In fact, there is no longer a Security Code field at all in the login module or page. Instead, you login using whichever login method you want to use. Then you enter the “captive login” mode in Joomla where you can only interact with a subset of com_users: you can proceed with MFA validation, choose a different MFA method or log out. Non-HTML views are forbidden.

Tagging @SniperSister @richard67 who were involved in the original discussion in the context of improving Joomla's security, @zero-24 @bembelimen @roland-d @HLeithner as the current and future release leads that need to be in the loop, @Kostelano and @heelc29 who participated in the previous PR.

## Extra features implemented and considerations made

I implemented a few extra features to the old TFA since I already had the code for them and it'd be a waste to remove it only for someone else to try and replicate them in the future. I also tried to be very considerate of the security of the solution, keeping it in a fine balance with practicality. Without further ado, here's what I did.

**Multiple MFA methods per user**. There is no good reason why a user shouldn't have multiple MFA methods. In fact, it is a better approach e.g. having two WebAuthn keys (main and backup) and a classic six-digit code for use in an older smartphone which doesn't support WebAuthn dongles. This makes MFA more usable and more resilient to accidents that lock people out of their site.

**Default method**. If you have multiple authentication methods you don't want to stop and think which method you will be using to authenticate today, especially since you're likely to use the same method 99% of the time. Therefore you can pick which method will be your default. You can NOT use emergency codes as the default method to reduce the probability of silly mistakes.

**Methods batching**. Let's say you set up three WebAuthn authenticators. When you log in you want to see a single page asking you for a WebAuthn login, not having to click to select _which_ WebAuthn authenticator you will be using (reduces the PICNIC errors — Problem In Chair, Not In Computer). I call that method batching because you can batch process all instances of a MFA method using a single input. WebAuthn and YubiKey let you set up multiple instances of that method so, indeed, they support method batching. Regular Authentication Code and Authentication Code by Email only allow a single instance so they don't. As simple as that.

**Automatic migration of legacy data**. To support multiple MFA methods per user we moved the MFA data from the two `#__users` columns (`otpKey` and `otep`) to its own table (`#__user_tfa`). Any already set up legacy TFA method is automatically migrated _upon first login_. This means that MFA will migrate cleanly even on sites with hundreds of thousands of users, something which would NOT be the case had we performed the migration during update (we'd timeout as we have to load each record individually, decrypt it, convert it, re-encrypt it and save it). **Important:** Until a user goes through a login you will NOT see their TFA/MFA status or configuration settings in com_users in the backend.

**Data is encrypted**. As alluded above, the MFA configuration data is _still_ encrypted using AES-256 using a key derived from the site's `secret`. Therefore a simple SQLi vuln in any extension won't divulge the secrets for MFA.

**New MFA methods**. You can now use Authentication Code by Email and WebAuth on top of the existing Authentication Code and YubiKey methods. The former sends you a 6-digit code to your email and can also be set up to be forcibly enabled for anyone (to provide a viable backup if your users are not very tech savvy). The latter supports Windows Hello and Android, bringing in the improvements from my other PR (#37675).

**Forced MFA and Forbidden MFA groups**. You can optionally set up certain user groups to have MFA forcibly enabled and other groups to have MFA forcibly denied. The former will have to set up MFA and use it to continue using the site. The latter will never be asked to go through MFA, even if they had previously enabled it, nor will they see the MFA configuration section in `com_users`.

**Onboarding to drive adoption**. You can optionally have users (who do not belong in the forbidden MFA groups!) be automatically shown an onboarding page if they log in and they have not yet enabled MFA. They can set up MFA, go to a different page or forever dismiss the onboarding page. You can also customise the onboarding URL, e.g. if you want to display your own article instead of showing the default MFA setup page. According to my experience this increases MFA adoption by a factor of ten. Note that onboarding is DISABLED by default; we don't want people coming at us with torches and pitchforks for ruining their site's login experience.

**Super Users cannot edit other Super Users**. As a Super User you cannot touch another Super User's MFA settings at all. Consequently, if you mess up your MFA as a Super User you need to do some database editing. There's only so much we can do.

**Administrators can only remove TFA options for other users**. As a privileged user you can only remove MFA options from other (non-Super Users) user accounts, or disable their MFA completely. You cannot edit their TFA configuration or enrol new MFA methods.

**Single click disable**. The MFA configuration interface includes a Turn Off button which disables MFA completely for your user account. This is useful if you lost access to all MFA methods, you have used an emergency code and you just want to turn the darned thing off until you sort out your other problems.

**Post-installation message**. The old PIM for MFA has been removed and a new one has taken its place.

**Module positions customisation in the captive page**. You can choose which module positions to display in the captive MFA page. This lets you display, for example, your site's header and footer to give users a better visual experience.

**No MFA on silent logins**. By default, MFA is disabled on silent logins. You can toggle that as well as customise which login methods are to be considered a "silent" log in. By default these are the Cookie Authentication (remember me) and Passwordless (WebAuthn). The latter needs some explaining. WebAuthn is phishing-resistant and insanely secure — we only ever store a public key in the database, even if it's stolen it cannot be used to log you in (a stolen password hash can be brute forced MUCH more easily, _by several orders of magnitude_). This means that WebAuthn is strong enough to NOT require Multi-factor Authentication. That's the whole point of WebAuthn; replace usernames and passwords and the need for multifactor authentication with _One Authentication Method To Rule Them All And In Security Bind Them_.

## Implementation notes

This PR is based on my past work on Akeeba LoginGuard, in active development since 2016. Back in late 2013 when I contributed the Two Factor Authentication feature we had agreed that entering the security code with the username and password was a bad idea but we only intended it as a _temporary_ solution until Joomla 4.0 would be released in late-2014 to early-2015. Obviously the release plan changed and we got stuck with  [...]

2022-05-27 17:25 UTC, Kostelano commented
Enable all 5 plugins. Create one of the methods for yourself. Then disable all plugins (if you disable only the configured method - the problem does not reproduce), log out and try to log in.

`Warning: Invalid argument supplied for foreach() in C:\OpenServer\domains\joomla4\administrator\components\com_users\src\Helper\Mfa.php on line 159`

![Screenshot_1](https://user-images.githubusercontent.com/8440661/170759264-a9d6589a-4f9a-4279-95e7-0add741ce88e.png)

2022-05-27 17:34 UTC, Kostelano commented
The OTP alert is not full width, although all other alerts are full width. Look at the adjacent tabs in the profile settings or, for example, at the entrance, when we are redirected to the MFA information page.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/170761941-089acac2-7fe8-4aae-a697-25ee3ced9d04.png)


Also, I noticed that you increased the header size with fs-3. It catches the eye. My humble opinion - without this class it was better.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/170761902-c6a3c99e-8772-4b63-90c8-62aa2c5742fb.png)

2022-05-27 18:06 UTC, Kostelano commented on administrator/language/en-GB/joomla.ini
> +JENFORCE_2FA_REDIRECT_MESSAGE="You were redirected because you are required to set up Multi-factor Authentication to continue."
All 4 lines from this file are modified but not used. At all. Can we move them to the end of the file, similar to how you implemented it in [com_users.ini](https://github.com/joomla/joomla-cms/pull/37912/files#diff-87c3c7e012232ff9aaf5c040299faef09d255e6daee4e78fcbed00c4126cb315R442)?

Given that they are old and that a decision has been made to save these lines and NOT change them, then you need to return them to TFA again.

The same goes for the front **joomla.ini**.

2022-05-27 18:35 UTC, brianteeman commented
## Captive login as manager
![image](https://user-images.githubusercontent.com/1296369/170770350-564ce9b1-680c-4980-a889-063968ce2fd0.png)

This is caused because the manager does not have access to the administrator interface of com_users. It doesnt make a huge ammount of sense to change the permission so I think there needs to be a different way.

2022-05-27 18:39 UTC, nikosdion commented on administrator/language/en-GB/joomla.ini
> +JENFORCE_2FA_REDIRECT_MESSAGE="You were redirected because you are required to set up Multi-factor Authentication to continue."
I am reverting the wording but I am not changing the order of the strings in the joomla.ini files though, or cleaning up strings unrelated to this PR. Basically, I don't want to touch the “library” language file at all. The release lead should do that. Touching that file opens a whole can of worms about backwards compatibility. Just nope. I am not dealing with that; it's above my pay grade 😆

2022-05-27 18:42 UTC, nikosdion commented
@Kostelano I addressed your feedback.

@brianteeman Sigh... This is why I wanted to have this as a different component but the production leadership insisted on having it a com_users feature. Let me think how to do this in a way that doesn't introduce any security issues.

2022-05-27 18:46 UTC, roland-d commented
@nikosdion Perhaps we should reconsider and make this a separate component. I really do not think it is a good idea to give users access to com_users to setup their MFA. I have posted it in the production team.

2022-05-27 18:50 UTC, nikosdion commented
@roland-d We are in it too deep to change the overall structure. Don't worry, mate, I know how to do it. I have done the same in Akeeba Ticket System where the same component can be used by end users with no administrative privileges and support ticket managers with administrative privileges. Half of what we need is _already_ in the Controllers I wrote. The other half is adding exceptions in the Dispatcher for the MFA-specific views. Since all tasks of all MFA views do their own access control we're good. Defensive coding by default pays off when issues like that arise.

In other words don't worry, my healthy dose of security paranoia is about to pay off dividends.

2022-05-27 19:01 UTC, nikosdion commented
@brianteeman @roland-d There you go. Managers and any backend user without core.manage on com_users can now use the MFA sub-feature of com_users to manage their own MFA and nothing else.

If you're wondering how having access to manage.delete, for example, doesn't allow managers to delete the MFA of other users: the ManageController::delete calls assertCanEdit which calls Mfa::canEditUser. The latter will only return true if you are editing your own MFA **or** if you are a Super User and who you are editing is NOT a Super User.

2022-05-27 19:33 UTC, brianteeman commented
Sorry that doesnt work. 

![403](https://user-images.githubusercontent.com/1296369/170778273-3599fc25-0efa-460d-a84d-b569cf07492f.gif)

2022-05-27 19:40 UTC, Kostelano commented
It might be better to use the classic prompt below the field so that it doesn't differ from other Joomla options.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/170779055-ee5f063a-1176-4b20-a8c2-d205ac604b5c.png)

2022-05-27 19:43 UTC, Kostelano commented
There is a disproportion in badges for admin/front templates. Consider reducing the badge in the front.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/170779533-60231fe0-361f-4565-9c7e-f5cf28a157b3.png)

2022-05-27 20:23 UTC, nikosdion commented
@brianteeman It worked, I just forgot to remove the Back button. Try now, it's fixed.

2022-05-27 20:32 UTC, brianteeman commented
> @brianteeman It worked, I just forgot to remove the Back button. Try now, it's fixed.

almost but not quite

![4032](https://user-images.githubusercontent.com/1296369/170785583-7d3c7a95-dc31-4f86-b923-014286757ddf.gif)

2022-05-27 20:57 UTC, nikosdion commented
@brianteeman Back button terminated with extreme prejudice.

@Kostelano The only thing that cannot be fixed is the font size in the frontend. Unfortunately, these minimum font sizes are hardcoded in Cassiopeia's SCSS. Having tried to fix that and being told to adjust it in my browser (a. it's outright impossible in Safari and b. with the rest of the web using 0.9rem as the base font size it means the rest of the web becomes _teensy tiny_) all I can tell you is that I can't fix it. If you want you can submit a separate PR to Joomla to address the font sizes but if I were you I'd think twice before deciding to die on that particular hill.

2022-05-27 21:06 UTC, brianteeman commented
> @brianteeman Back button terminated with extreme prejudice.

that seems to have resolved that in the admin

2022-05-27 21:14 UTC, brianteeman commented
Next problem

In the list view of users the column showing MFA is wrong. Below you can see that the super user does not have MFA enabled and the manager does have MFA enabled but the list view says otherwise

![4033](https://user-images.githubusercontent.com/1296369/170790253-47244901-23d4-4824-aef5-2ed60467dfe8.gif)

2022-05-27 21:25 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/170791119-82f0e8ad-b66d-4a1a-97e4-3e585e267452.png)

when you read this as one sentence then it is correct to write "Backup Codes let you ...
When you read this as two sentences then it should be "Backup Codes. Lets you ...

As this is a title followed by a sentence I would change it to the second

2022-05-27 21:34 UTC, brianteeman commented
### Post Installation messages
Something is going wrong as I can see there is aa query to remove the tfa message and to add a mfa message - but thats not happening

![4034](https://user-images.githubusercontent.com/1296369/170791986-9ec31c71-deab-483f-91c7-0f69633e056e.gif)

![image](https://user-images.githubusercontent.com/1296369/170791995-427f5bab-157e-4c1d-9329-1651a3c313b2.png)

2022-05-27 21:36 UTC, Kostelano commented
@brianteeman disable all MFA plugins

2022-05-27 21:37 UTC, brianteeman commented
> @brianteeman disable all MFA plugins

its a clean install

2022-05-27 21:42 UTC, Kostelano commented
If you enable the Onboard new users parameter in the user settings, then enter the site in the frontend, we get to the page with information about the MFA. Here we will add a method, after confirmation we will get to the page where the heading `Your Multi-factor Authentication method` will be. It only appears here (if we are talking about the front). It seems to me that it is superfluous and I propose to remove it. When editing a profile, this header is not there; in the admin panel in the profile, it is also not there.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/170792730-3108f13e-cf1e-45d8-a6a6-bb8a6316232d.png)

2022-05-27 21:44 UTC, Kostelano commented
> its a clean install

Yes, that's how it works. And it worked with TFA. If at least 1 plugin was enabled, no message was displayed. Since we have 4 plugins enabled in a clean install, no message is displayed.

It probably still needed to be displayed to inform users, but in general the behavior has not changed since the introduction of TFA.

2022-05-27 22:37 UTC, brianteeman commented
> > its a clean install
> 
> Yes, that's how it works. And it worked with TFA. If at least 1 plugin was enabled, no message was displayed. Since we have 4 plugins enabled in a clean install, no message is displayed.
> 
> It probably still needed to be displayed to inform users, but in general the behavior has not changed since the introduction of TFA.

That's a bug then as its not a "post-installation" message if there is a condition (no mfa plugins enabled) that cannot be met

https://github.com/joomla/joomla-cms/blob/e4adef5dd19612b148cc7be38abcf4974df85fd5/administrator/components/com_users/postinstall/multifactorauth.php#L18-L20

As they are enabled already on a clean install this can only ever be displayed on an update. 

I agree that displaying the action can be conditional but not the message itself.

2022-05-28 06:41 UTC, brianteeman commented
## Enforce MFA
- Set Enforce Multi-factor Authentication to manager
- Set Onboard  new users to yes
- Create a new manager and try to login to the admin

### Expected behaviour
Onboard page without any possibility to proceed without setting up MFA

### Actual Behaviour
Onboard page with modules and possibility to proceed and do anything a manager can do

2022-05-28 07:10 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +			<option value="">JGLOBAL_USE_GLOBAL</option>
```suggestion
			<option value="">JOPTION_USE_DEFAULT</option>
```

There is no such thing as a global style. There isa dfault style. Description also needs updating to take this into account

2022-05-28 07:12 UTC, brianteeman commented on administrator/components/com_users/config.xml
> +			size="7"
Atum ignores size. it has been removed for all admin forms

2022-05-28 07:17 UTC, brianteeman commented
### Input validation and filters
I thought, and I can be wrong, that all inputs in forms are supposed to have filters and/or validation on th input

2022-05-28 08:10 UTC, nikosdion commented
I am not at the office but I can tell Brian about all of his wrong assumptions. 

Post-installation. Read the previous PR’s discussion and this PR’s description. Think hard about migrating vs new installation and you will see why what you say is daft. I am not going in circles about something already discussed and resolved. 

Onboarding. You conflate onboarding with forced use of MFA. THESE ARE TWO DIFFERENT FEATURES. Feedback ignored as nonsensical non-issue. 

MFA status. Works for me but I’ll check again on Monday. 

Please use your brain, Brian. THINK before you comment.

2022-05-28 08:27 UTC, brianteeman commented
Respectfully please check more carefully what I have said

2022-05-28 08:30 UTC, brianteeman commented
Not going to waste any more time testing this

2022-05-28 12:27 UTC, heelc29 commented on installation/sql/postgresql/supports.sql
> +SELECT "extension_id", 'PLG_MULTIFACTORAUTH_TOTP_POSTINSTALL_TITLE', 'PLG_MULTIFACTORAUTH_TOTP_POSTINSTALL_BODY', 'PLG_MULTIFACTORAUTH_TOTP_POSTINSTALL_ACTION', 'plg_multifactorauth_totp', 1, 'action
Remove old postinstall message for new PostgreSQL installation

2022-05-28 12:42 UTC, heelc29 commented on libraries/src/Event/MultiFactor/Callback.php
> +			throw new DomainException(sprintf("Argument 'methhod' of event %s must be a non-empty string.", $this->name));
```suggestion
			throw new DomainException(sprintf("Argument 'method' of event %s must be a non-empty string.", $this->name));
```

Can you also have a look at the consistent use of single/double quotes and punctuation at the end of the sentence?

2022-05-28 12:42 UTC, heelc29 commented on libraries/src/Event/MultiFactor/NotifyActionLog.php
> + * @license        GNU General Public License version 2 or later; see LICENSE
```suggestion
 * @copyright  (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
 * @license    GNU General Public License version 2 or later; see LICENSE
```

2022-05-28 12:42 UTC, heelc29 commented on libraries/src/Event/MultiFactor/SaveSetup.php
> + * @license        GNU General Public License version 2 or later; see LICENSE
```suggestion
 * @copyright  (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
 * @license    GNU General Public License version 2 or later; see LICENSE
```

2022-05-28 13:05 UTC, heelc29 reviewed
I think `$cookieLogin` makes no sense here

2022-05-28 13:05 UTC, heelc29 commented on components/com_users/tmpl/login/default.php
> +/** @var \Joomla\Component\Users\Site\View\Login\HtmlView $cookieLogin */
```suggestion
/** @var \Joomla\Component\Users\Site\View\Login\HtmlView $this */
```

2022-05-28 13:05 UTC, heelc29 commented on components/com_users/tmpl/login/default_login.php
> +/** @var \Joomla\Component\Users\Site\View\Login\HtmlView $cookieLogin */
```suggestion
/** @var \Joomla\Component\Users\Site\View\Login\HtmlView $this */
```

2022-05-28 13:05 UTC, heelc29 commented on components/com_users/tmpl/login/default_logout.php
> +/** @var \Joomla\Component\Users\Site\View\Login\HtmlView $cookieLogin */
```suggestion
/** @var \Joomla\Component\Users\Site\View\Login\HtmlView $this */
```

2022-05-28 13:37 UTC, heelc29 commented on plugins/user/joomla/joomla.php
>  use Joomla\Registry\Registry;
New imports are not used

2022-05-28 13:37 UTC, heelc29 commented on plugins/user/joomla/joomla.php
> +		if (!($this->app->isClient('administrator')) && !($this->app->isClient('site')))
```suggestion
		if ($this->app->isClient('administrator') || $this->app->isClient('site'))
```
Is that easier?

2022-05-28 14:15 UTC, heelc29 requested changes

2022-05-28 14:15 UTC, heelc29 commented on plugins/multifactorauth/email/src/Extension/Email.php
> +			catch (\RuntimeException $exception)
```suggestion
			catch (RuntimeException $exception)
```
`RuntimeException` is imported

2022-05-28 14:15 UTC, heelc29 commented on plugins/multifactorauth/email/src/Extension/Email.php
> + * @license         GNU General Public License version 2 or later; see LICENSE.txt
```suggestion
 * @package     Joomla.Plugin
 * @subpackage  Multifactorauth.email
 *
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
```

2022-05-29 01:13 UTC, heelc29 commented on plugins/multifactorauth/email/src/Extension/Email.php
> + * @license     GNU General Public License version 2 or later; see LICENSE.txt
```suggestion
 * @package     Joomla.Plugin
 * @subpackage  Multifactorauth.email
 *
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
```

2022-05-29 01:13 UTC, heelc29 commented on components/com_users/tmpl/login/default_login.php
> +/** @var \Joomla\Component\Users\Site\View\Login\HtmlView $cookieLogin */
@nikosdion Is there a reason why not change to `$this`.

2022-05-29 01:13 UTC, heelc29 commented on libraries/src/Event/MultiFactor/Callback.php
> +			throw new DomainException(sprintf("Argument 'method' of event %s must be a non-empty string.", $this->name));
Here you use double quotes ... in the other events you use single quotes and escape the quotes around the argument name.

2022-05-29 01:13 UTC, heelc29 commented on installation/sql/postgresql/supports.sql
> +FROM "#__extensions" WHERE "name" = 'files_joomla';
Sorry, I think I didn't express myself very clearly. The lines 284-286 should be removed (old postinstall message for TFA). The new one (for MFA) is added in lines 295-296.

2022-05-29 07:09 UTC, nikosdion commented on libraries/src/Event/MultiFactor/Callback.php
> +			throw new DomainException(sprintf("Argument 'method' of event %s must be a non-empty string.", $this->name));
There is no code style for strings so either works just fine. I don't see the point of making a change for change's sake?

2022-05-29 07:54 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/170858096-710502f2-cf1c-4f16-83d0-8644a2a0e879.png)

![image](https://user-images.githubusercontent.com/1296369/170858110-b9e457a2-149a-4262-abc8-aeab21808fc0.png)

The label is for _com-users-method-edit-code_
The input is _com-users-method-code_

They must be the same

2022-05-29 08:08 UTC, brianteeman commented
## Backup Codes

When you add MFA to your account AND you have all the plugins enabled then its a long list. ✔️
After adding your first method an additional option is displayed for backup codes ✔️

Quite rightly you're highlighting this etc as its so essential for a user to do ✔️

The problem is that it is too easy not to see that backup codes have been added to the page. Possible solution woulf be to add backup codes to the top of the list and not the end of the lis.

### Demo cassiopeia
![4205](https://user-images.githubusercontent.com/1296369/170858595-e5ba3b06-ab9b-4c87-8c42-8518f85fae34.gif)

2022-05-29 08:13 UTC, brianteeman commented
## Onboard new users 403 on logout

403 when logging out from the onboarding page without setting up any MFA

![4307](https://user-images.githubusercontent.com/1296369/170858749-823799df-2e0f-4386-8e64-a943e596a527.gif)

2022-05-29 08:27 UTC, brianteeman commented
### Display User Profile

If you have a menu item to display the user profile it is displayed with the basic details and the status of any webauthn . Should it not also show if any MFA are configured?

![image](https://user-images.githubusercontent.com/1296369/170859175-3a4c425a-494d-4077-92fc-18cbc4279944.png)

2022-05-29 08:30 UTC, nikosdion commented
> 403 when logging out from the onboarding page without setting up any MFA

That's the unfortunate way of how the Joomla logout button works. When you log out you are redirected to the same URL you were before unless the login module is set up with a logout redirection URL. If there was no redirection URL and you were viewing any access-restricted page you get a 403 error.

The same thing will happen if you are editing your user profile or viewing an access-restricted article and click on the Logout button — and that's before this PR is applied; it even happens on Joomla 3.

There are two possible ways to handle this issue:

1. The One True Joomla Way: consider it normal, do nothing and move on. That's what I did as that's how the rest of Joomla works.
2. Instead of returning a 403 when there is an access error redirect the user to the home page of the site. However, this would make the MFA feature work in a way that's different than the rest of Joomla.

Therefore I am inclined to leave it as-is. The One True Joomla Way solution is for the site owner to set up a logout redirect URL for the login module.

2022-05-29 08:36 UTC, nikosdion commented
> Should it not also show if any MFA are configured?

It never did with TFA. I am keeping it the same.

I would say that it shouldn't even show the WebAuthn information. There is no point showing login-related detailed information in the profile display. These only make sense when editing the profile. If at some point user profiles become public — there is a much-needed use case in real world sites which now have to install “social web” solutions even if all they need is a public profile display — the login information should most definitely not be part of the public profile.

As for WebAuthn, if I recall correctly, the context sent when viewing and when editing the profile is the same therefore the WebAuthn system plugin cannot know when NOT to add its fields. That's why all it can do is add an HTMLHelper hook to render its field differently than when editing the profile. That hook is called too late in the process to let WebAuthn remove its fields from the user profile form.

If you have found a reliable way for WebAuthn not to show itself when viewing a profile please do a PR and tag me.

2022-05-29 08:57 UTC, roland-d commented
I have been testing it a little as well, it is looking good :+1:

A few things I noticed:
- When you have no mail template (for whatever reason) there is no email sent but when you are setting up the `Code by email` it says that you have received an email. Should we check if the email template exists?
- When you remove the last active MFA method by clicking the delete button on the method, you still have backup codes. Should these be removed? They are removed if you click the `Turn off` on the top of the page.
- I find the `Add a new ..` buttons really big. Setting the button classes to `btn btn-secondary btn-sm` looks better I think.

2022-05-29 09:05 UTC, nikosdion commented
> When you have no mail template (for whatever reason) there is no email sent but when you are setting up the Code by email it says that you have received an email. Should we check if the email template exists?

How would you end up in such a situation? I mean, sure, I can catch that problem but I can't think of a way you end up like that without deliberately sabotaging your site.

> When you remove the last active MFA method by clicking the delete button on the method, you still have backup codes. Should these be removed? They are removed if you click the Turn off on the top of the page.

I know. I am trying to see if there is a reliable way to do it.

> I find the Add a new .. buttons really big. Setting the button classes to btn btn-secondary btn-sm looks better I think.

Okay. I'll change them.

2022-05-29 09:11 UTC, roland-d commented
> How would you end up in such a situation?

In my case the SQL query was not executed, simply because I forgot. The way users maintain their website anything is possible. I know it may be far-fetched, just wanted to put it out there.

2022-05-29 09:28 UTC, brianteeman commented
Re the 403 
That might have been the situation in the past - I dont remember - but its not the situation now. With sample data installed and you use the module log out button on a restricted page you are redirected to the login page with an error message. Not great but better than the 403. Try it and see

![4308](https://user-images.githubusercontent.com/1296369/170861221-8c663d97-1358-4674-89a7-0a2f891d10c5.gif)

2022-05-29 09:57 UTC, nikosdion commented
@roland-d Regarding the code by email, it makes more sense to send the email using the traditional way if the mail template is missing than failing. It prevents the user from getting locked out or having to make a DB query every time we evaluate MFA to see if we should use the Code by Email feature. Everything else I did.

@brianteeman OK, I am not redirecting to the login page.

2022-05-29 10:28 UTC, brianteeman commented
> If you have found a reliable way for WebAuthn not to show itself when viewing a profile please do a PR and tag me.

Seemed too easy. Did I miss something #37921

2022-05-30 07:32 UTC, roland-d commented
@nikosdion Fair point we don't want to check the existence of a mail template. It is not an issue for just this PR but the mail templates in general, so I would just leave it as it is.

2022-05-30 08:28 UTC, brianteeman commented
I still dont like the way the button is split onto two rows like this

![image](https://user-images.githubusercontent.com/1296369/170950846-770668c3-e941-4c62-aab2-22697596d8dc.png)

Please reconsider my pr https://github.com/nikosdion/joomla-cms/pull/8

2022-05-30 08:30 UTC, brianteeman commented
## Email by code

The input field is of type number which means it displays a spinner and a screen reader will do things like announcing the min and max values and the step (even if you dont explicitly set them)

I would probably change that to
`<input type="text" pattern="{0,9}" maxlength="6" inputmode="numeric">`

_note the inputmode is for mobile devices_

2022-05-30 08:31 UTC, brianteeman commented
Authenticator app - debug?


>  Please check your authenticator app setup, and make sure that the time and time zone on your device is set correctly.

Tried multiple authenticator apps on my phone and each time the verifcation code is rejected. The time and time zone on my phone are set correctly (its done automatically)

Any suggestions how to debug this further

2022-05-30 08:40 UTC, nikosdion commented
@roland-d 
> It is not an issue for just this PR but the mail templates in general, so I would just leave it as it is.

I agree. I found the same issue with my software. My solution was to have an Email Templates page in my extensions which can be used to add missing templates or reset email templates to default. Maybe Joomla could do the same, albeit it would require having the email templates in a third place apart from the two SQL files per DB server type.

@brianteeman 

> I still dont like the way the button is split onto two rows like this

I have a better solution than your PR already written — and an even better one I thought about last night. I'll do that today.

> Tried multiple authenticator apps on my phone and each time the verifcation code is rejected. The time and time zone on my phone are set correctly (its done automatically)

Check the timezone in your php.ini and the server timezone in your global configuration. These would be used to convert the date and time reported by the system clock to the UNIX timestamp used by Joomla's TOTP class. Remember that I have not changed the TOTP implementation in this PR; I am using the one already in Joomla since 3.2.

2022-05-30 08:42 UTC, nikosdion commented
@brianteeman 

> The input field is of type number which means it displays a spinner and a screen reader will do things like announcing the min and max values and the step (even if you dont explicitly set them)

I cannot get a screen reader to announce a min/max value if one is not set. It does announce it as a spinner. Which screen reader are you using? I am trying to understand the nature of the problem so whatever I do to solve it is not a blind change (no pun intended).

2022-05-30 09:15 UTC, brianteeman commented
This is a summary of how the different screen readers respond to a input type=number field https://a11ysupport.io/tests/tech__html__input__input-number

As you can see the behaviour I described is from windows narrator, which as reported by the webaim survey was used by 36.8% of respondents and is increasing year on year

2022-05-30 09:17 UTC, brianteeman commented
>> I still dont like the way the button is split onto two rows like this

> I have a better solution than your PR already written — and an even better one I thought about last night. I'll do that today.

I dont care how it is fixed just that it is. My pr was the minimal change to achieve the aim. It was not how I would have created it from scratch.

2022-05-30 09:18 UTC, brianteeman commented
> > Tried multiple authenticator apps on my phone and each time the verifcation code is rejected. The time and time zone on my phone are set correctly (its done automatically)

> Check the timezone in your php.ini and the server timezone in your global configuration. These would be used to convert the date and time reported by the system clock to the UNIX timestamp used by Joomla's TOTP class. Remember that I have not changed the TOTP implementation in this PR; I am using the one already in Joomla since 3.2.

I suspect thats the case as well BUT the error message only refers to my authenticator device time and nothing about server time. Hence the confusion/query

2022-05-30 09:37 UTC, nikosdion commented
> the behaviour I described is from windows narrator

Thank you! This helps a lot. That's what I was asking for in the previous PR :)

> I suspect thats the case as well BUT the error message only refers to my authenticator device time and nothing about server time. Hence the confusion/query

As you've said before, error messages cannot be full documentation. In most practical uses cases the php.ini is maintained by the host and has the correct timezone. The only practical problems we've seen in the last 12 years we've implemented TOTP — counting all the way to when Admin Tools Pro was the only way to add TFA to Joomla — was someone's device having the wrong timezone. The number of people who _manually_ set the time every six months on their mobile phone is staggering. I didn't believe it either.

> It was not how I would have created it from scratch.

I know. You would have each authenticator render its own HTML page which is how Joomla tends to do things — same reason the old TFA was implemented like that — but is unmaintainable if you have more than one authenticator, or you're using a template other than Joomla's default, or you're using a non-core authenticator.

The solution I am going to implement will remove (most of) the custom HTML from WebAuthn and can serve as a template for custom third party authenticators. 

This means that we'll only need to change things in one place _and one place only_ to change the layout of any authenticator and template, even non-core ones, to maintain a consistent experience. Doing that will also let me offer you the option to display the Validate, Log Out and Select Another Method buttons in the backend in the toolbar instead of the main page area which is another feedback point I have not forgotten about, thank you very much.

Your comment also demonstrates what is wrong with Joomla contributions the past few years. There are people who are site integrators / instructors and people who are code architects. Each cohort is far removed from the other. The people who would straddle both cohorts have stopped contributing to Joomla.

What I am trying to do here is NOT tell you that I know everything and can get everything right the first time; that's impossible. I am trying to listen to everyone's feedback and come up with the best compromise which will provide a consistent, easily customisable interface for everyone without tonnes of busywork and at the same time have an architecture which isn't antithetical to progress and future improvements. These are all the areas the legacy TFA failed miserably. 

It naturally takes a lot of iterations to get there. To this end I prefer _constructive_ feedback than dismissive remarks, querulousness and self-pity, if you don't mind.

2022-05-30 10:12 UTC, brianteeman commented
yes it was the server time.

> What I am trying to do here is NOT tell you that I know everything

That is absolutely not how it comes across at all.

2022-05-30 11:48 UTC, nikosdion commented
> That is absolutely not how it comes across at all.

A good senior developer knows when to say “no” and explains why. That's what I do. I am sorry that you don't try to understand the “why” after having it explained to you. Maybe if you talked to users and actually listened to them I wouldn't have to explain. Instead, you declare that you know best and when real world users complain you tell them they are stupid. It's funny how you're now doing what you were making fun of ten years ago.

Think about this. You are a mobile user. The only buttons you have are in the toolbar. You log into the site and you see the MFA code box. You enter the code and... what? It's completely non-obvious that you need to expand the TOOLBAR to click on the Send button. Of course I will object to that kind of interface and will look for a better solution.

You could have provided constructive feedback towards that end. All I got in return is “you're not trying to help” and ”It was not how I would have created it from scratch”. This is toxic, obviously false and completely stupid.

If I was here for a code dump I wouldn't be engaging with anyone. I'd have renamed com_loginguard to com_mfa and be done with it in an afternoon.

If you think you could have done it better from scratch: you had 9 ½ years. Where's your code?

Anyway, I don't care about your negativity and toxicity. I have figured out a way to do this **despite you** (and not thanks to you) so I will be doing it.

You need to address your behaviour. I don't give a rat's behind if you do that to me. The problem is you're doing that to _everybody_. That's not conducive to collaboration. If you're not part of the solution you're part of the problem.

2022-05-30 12:13 UTC, heelc29 reviewed
Is it better to use the icon class?

2022-05-30 12:13 UTC, heelc29 commented on plugins/multifactorauth/webauthn/tmpl/error.php
> +			<span class="fa fa-times-circle" aria-hidden="true"></span>
```suggestion
			<span class="icon-cancel-circle" aria-hidden="true"></span>
```

2022-05-30 12:13 UTC, heelc29 commented on plugins/multifactorauth/webauthn/tmpl/nothttps.php
> +			<span class="fa fa-times-circle" aria-hidden="true"></span>
```suggestion
			<span class="icon-cancel-circle" aria-hidden="true"></span>
```

2022-05-30 12:15 UTC, nikosdion commented on plugins/multifactorauth/webauthn/tmpl/error.php
> +			<span class="fa fa-times-circle" aria-hidden="true"></span>
This is related with the change I am working on right now. The answer is yes, it's better to use the `icon-` class as it's more likely to be overridden in 3PD templates. Unless, of course, Joomla decides to forego these custom classes in 5.x, but there's no such indication yet.

2022-05-30 12:34 UTC, heelc29 commented
I have two MFA methods set up: Totp (default) and Email.

After deleting Totp, there is no longer a default method. 
![image](https://user-images.githubusercontent.com/66922325/170991298-ac075c20-af58-42a5-81ae-84cd54dbc444.png)

If I try to login, the backup codes are "default".
![image](https://user-images.githubusercontent.com/66922325/170991376-3b88bbd9-8117-4dac-b768-6c0205425f3b.png)

2022-05-30 17:06 UTC, nikosdion commented
@heelc29 I am trying to reproduce this but I can't. I am not sure if you are using the latest code, though. I made a change yesterday, if you remove the last MFA method the backup codes are also removed. Is it possible that you have an older version of the code which doesn't remove the backup codes in this case?

2022-05-30 21:03 UTC, heelc29 commented
> Is it possible that you have an older version of the code which doesn't remove the backup codes in this case?

I'm pretty sure I use c589be172a3bac94aa2a894bbc8ea407bc7504e8.
![image](https://user-images.githubusercontent.com/66922325/171058728-3b1d9c72-a224-4b68-88af-7ee9880e5360.png)

For information: I have **two** MFA methods set up and delete only **one** of them (the default one). So the second one (in my case the email option) still exists.
![image](https://user-images.githubusercontent.com/66922325/171058582-486c2e41-17e8-41ef-9b98-52e5dfc84752.png)

I can try it later again.

2022-05-31 07:50 UTC, nikosdion commented
@heelc29 Thank you for the clarification! I understand what you mean now, I was able to reproduce and solve it.

2022-05-31 09:28 UTC, brianteeman commented
great to see the toolbar now

small error on the back button here

![image](https://user-images.githubusercontent.com/1296369/171141101-f456da64-cebb-4d31-b6d5-01405ade6549.png)

I _think_ its missing the index.php

2022-05-31 09:36 UTC, brianteeman commented
on the page listing all the methods there are edit/delete buttons.

These link have identical text, although they point to different pages. Multiple links with the same text may cause confusion for people who use screen readers.

Suggestion would be to change them so that they say "Edit {method}" instead of just "edit"

2022-05-31 09:43 UTC, brianteeman commented
The toolbar back button is not rtl aware. All other instances of the back button in joomla change the direction of the arrow when in RTL. the code for this is something like
https://github.com/joomla/joomla-cms/blob/31b3b8980f251264ce070f9fbff9518fdb667397/administrator/components/com_joomlaupdate/src/View/Upload/HtmlView.php#L95-L96

2022-05-31 10:05 UTC, brianteeman commented
When you try to modify an existing yubikey you correctly do not see the Yubikey Identification input and see an appropriate message

> You have already set up your Yubikey (the one generating codes starting with ccccccdhuujj). You can only change its title from this page.

With the authenticator app method you still see the three setup methods and just the verificatioon input is missing and no information about it being setup already. I understand that it may be correct to still display the three setup methods as you might have a new app etc but should there be some explanatory text as well

2022-05-31 10:07 UTC, nikosdion commented
> I understand that it may be correct to still display the three setup methods as you might have a new app etc but should there be some explanatory text as well

I think it's self-explanatory? I didn't want to add another message to a long page. What would that message read anyway?

2022-05-31 10:31 UTC, Kostelano commented
Icons in the admin panel and on the front - in one place there is a white background, in the other there is not.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/171153724-68b0c1b6-91b8-4065-9ccf-701f207a3c36.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/171153730-3ff2564a-c3fe-491b-89d5-70dc32ed7b1b.png)

2022-05-31 10:33 UTC, Kostelano commented
Maybe we can remove mx-1...? Both in the front and in the admin panel.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/171154172-0afb5446-4319-4ea7-8794-c33dac806dfc.png)

2022-05-31 10:42 UTC, Kostelano commented
When you create a method - fields "in the standard Joomla format". When you log in - in another. I don't know if this is by design or a bug, but I would argue that the standard one-line approach is better and more familiar.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/171155726-606a3b2a-f9a3-4ce4-9617-d7cbf1a0dc2d.png)

2022-05-31 10:45 UTC, Kostelano commented
When we login and switch to one time password login, we don't have a description. Perhaps the line is present in the localization file, but is missing. Please check.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/171156223-dd147e08-ff67-4dcf-a73e-05c7498f39dd.png)

2022-05-31 10:47 UTC, brianteeman commented
> I think it's self-explanatory? 

obviously not as I was wondering why the field was not present

2022-05-31 12:08 UTC, nikosdion commented
> Icons in the admin panel and on the front - in one place there is a white background, in the other there is not.

It's the same `bg-light` in both cases. We need bg-light so the image does not disappear over bg-secondary and/or on templates where the default card background colour is not fully or almost fully white.

Cassiopeia and Atum are written by different people who chose to use different colours for bg-light and literally every other base colour in the template.

After this PR is merged you are welcome to file your own PR changing the bg-light colour in Cassiopeia. If you want to die on this hill I won't stop you — but I won't die on that hill myself. Implementing MFA in Joomla is orders of magnitude more important than adjusting the light background colour value in Joomla's default frontend template by ~3%.

> Maybe we can remove mx-1...? Both in the front and in the admin panel.

No. It was like that after I implemented your suggestion last time but _especially in the frontend_ it becomes confusing as there is no visual hierarchy to indicate that each MFA method belongs under the MFA header. They look like unrelated bits of information without the padding. Keep in mind that at least 90% of Joomla's target audience has no idea what MFA is and in need of a certain degree of handholding and gentle visual cues.

I will keep this little margin unless there is a UX study **backed by user testing** proving it wrong.

> When you create a method - fields "in the standard Joomla format". When you log in - in another. I don't know if this is by design or a bug, but I would argue that the standard one-line approach is better and more familiar.

This is by design. The decision was made after thinking about it and trying both approaches.

Horizontal forms (what you call "one line") is used to present multi-field forms in a more compact manner. This is not the case here; we only have one field.

Using a horizontal form layout looks out of place on large and extra large display sizes (display sizes per Bootstrap nomenclature): there's an ocean of whitespace. 

At the same time, it looks unnecessarily cramped on medium and below, especially when the label is longer and wraps. While you'd be hard pressed to see that with English, it becomes very visible if you translate to a more verbose language such as Greek. 

For example, the Authenticator Code plugin's label translates to «Κωδικός Επιβεβαίωσης Ταυτότητας» in Greek. This makes it wrap even on an 11" iPad, in portrait mode. I am not a designer but even I can tell that it's outright ridiculous having wrapped label text on a page that's mostly empty.

So, I am not changing that either.

> When we login and switch to one time password login, we don't have a description

That's a fair point. I will take a look into it.

@brianteeman 

> obviously not as I was wondering why the field was not present

I still need some text to put there as I have no idea what that text should read. 

Between the two of us only you have experienced the confusion and understand why this happened and what would prevent it. That's why I am asking _you_ for the text to put there. Can you please help?

2022-06-01 21:04 UTC, brianteeman commented
UPDATE resolved


is it a code or a password. would be best to use just one term

![image](https://user-images.githubusercontent.com/1296369/171501501-d389bc8f-ca98-4fde-80e5-0222180ced95.png)

![image](https://user-images.githubusercontent.com/1296369/171501511-20fe795f-6295-4d6f-849c-dff6cbfabe65.png)

2022-06-01 21:18 UTC, brianteeman commented on administrator/language/en-GB/plg_multifactorauth_webauthn.ini
> +PLG_MULTIFACTORAUTH_WEBAUTHN_LBL_INSTRUCTIONS="Use the &ldquo;%s&rdquo; button on this page to start the Web Authentication process. Then please follow the instructions give to you by your browser to
```suggestion
PLG_MULTIFACTORAUTH_WEBAUTHN_LBL_INSTRUCTIONS="Use the &ldquo;%s&rdquo; button on this page to start the Web Authentication process. Then please follow the instructions given to you by your browser to complete Web Authentication with your preferred Authenticator."
```
typo

2022-06-03 10:31 UTC, roland-d commented
@nikosdion Hey Nik, I wanted to ask where we are with this PR? Are there a lot more changes expected or are we nearly there?

2022-06-03 10:33 UTC, nikosdion commented
@roland-d Almost there. Just a lang string change per the discussion above. I will do that over the weekend. We're closing in on a 4.2 beta?

2022-06-03 18:03 UTC, roland-d commented
@nikosdion The first beta is on Tuesday June 7th. Ideally I am building the packages tomorrow :) If the lang string is the only issue, we should be able to make it. Thank you.

2022-06-03 18:08 UTC, nikosdion commented
@roland-d I fixed the lang strings (there were two of them). I think we can merge this PR as-is in the beta. Any fine-tuning, edge-polishing and yak-shaving can be implemented with other PRs against the 4.2-dev after it goes into beta. We won't have any language changes which is just about right for honouring the lang string beta freeze.

2022-06-03 18:19 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 82ef6a12e12e395b99717dce06a35b424040ec36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37912">issues.joomla.org/tracker/joomla-cms/37912</a>.</sub>

2022-06-03 18:22 UTC, richard67 commented
> @roland-d Any fine-tuning, edge-polishing and yak-shaving can be implemented with other PRs against the 4.2-dev after it goes into beta.

@nikosdion I’m pretty much interested in the yak shaving part :-) How do you keep the yaks calm?

2022-06-03 18:34 UTC, nikosdion commented
@richard67 Hm... Dunno about yaks, in my part of the world we have sheep. If you haven't had to stop your car for 10' because a herd of sheep is crossing the road you've not lived the rural life! Sheep are rather docile and will gladly take a shaving, especially when the weather gets hot as it tends to do over here around May. Before you ask, nope, I don't have the skills to shear sheep. My relationship with sheep extends to observing them grazing across the hill and using their digestive byproduct as fertiliser (excellent fertiliser for trees, but do it early in Spring when you can keep your windows closed, TRUST ME ON THAT).

2022-06-03 19:46 UTC, Kostelano commented
@nikosdion It seems that you planned to make a change to the issue https://github.com/joomla/joomla-cms/pull/37912#issuecomment-1141972256 (did not see the commit and can not check in reality on a PC).

2022-06-03 20:07 UTC, nikosdion commented
@Kostelano We can add this after the merge of this PR. We already have the language strings for this feature, it's just adding it to the output.

2022-06-03 20:08 UTC, Kostelano commented
I have tested this item :white_check_mark: successfully on 82ef6a12e12e395b99717dce06a35b424040ec36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37912">issues.joomla.org/tracker/joomla-cms/37912</a>.</sub>

2022-06-03 20:32 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37912">issues.joomla.org/tracker/joomla-cms/37912</a>.</sub>

2022-06-04 07:01 UTC, merged

2022-06-04 07:01 UTC, roland-d commented
Thanks everybody for this great feature.

2022-06-04 07:32 UTC, nikosdion commented
Thank you for the merge!

2022-06-04 07:39 UTC, richard67 commented
> @nikosdion It seems that you planned to make a change to the issue [#37912 (comment)](https://github.com/joomla/joomla-cms/pull/37912#issuecomment-1141972256) (did not see the commit and can not check in reality on a PC).

Who wants to make a PR? @Kostelano ? Or @nikosdion ?

2022-06-04 09:53 UTC, brianteeman commented
it si the same with other methods
![image](https://user-images.githubusercontent.com/1296369/171994277-323f5de7-8869-4479-bef7-e90edeaba184.png)

2022-06-04 15:41 UTC, heelc29 commented
@roland-d Please add `Language Change` label

2022-06-04 18:03 UTC, roland-d commented
Thank you @richard67

2022-06-10 17:19 UTC, Kostelano commented
@nikosdion, give me a couple of free minutes.

I can't figure out the parameter "Force Enable" for plugin **Authentication Code by Email**.

I carefully read the description, tried to implement the situation in this way: I created a user, created an authentication method for him (fixed password), then enabled the above parameter in plugin **Authentication Code by Email**. I'm trying to log in, I switch to an alternative method (suppose I forgot the fixed code and did not save the emergency passwords), but I do NOT have a "forced method" (authentication code by mail).

What am I doing wrong, or perhaps I misinterpreted the parameter description? Thank you in advance for your response.

> Should I automatically add the Authentication Code by Email as an option for all users? Useful to provide a fallback to users who have lost access to their main authenticator and haven't kept a copy of the backup codes at the expense of some degree of control and security.

2022-06-11 13:08 UTC, nikosdion commented
@Kostelano There were two missing lines not copied over from LoginGuard. Thank you for the heads up! I submitted https://github.com/joomla/joomla-cms/pull/38029 to fix that.

2022-06-30 15:48 UTC, Kostelano commented
I am not creating a bug because it does not pull on an error (probably), but I write here.

If we install some module separately, then with a high degree of probability we want to use it and it will still take its position in the template.

If we install a whole package, which may include a component/plugins/modules, then we won't necessarily use it all.

By default, the module occupies the `NONE `position. The same is immediately displayed in the parameters of the component users ---> MFA. Can we remove this position from the array of all positions for this reason?

@nikosdion 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/176720678-6be38a5a-ce39-44f0-a1e4-d0c73c7d8160.png)

2022-07-03 18:43 UTC, nikosdion commented
@Kostelano I disagree. Sometimes you may want to create a module in the None position to display it in an article which in itself is displayed by a module in another, published position. If you disallow the None module position to be selected in this multi-select control that article would appear without the referenced module.

Remember, this only controls which modules will be **loaded** by Joomla (in fact, all modules are loaded and modules in module positions NOT listed in this control are forcibly UNLOADED using some black magic fuckery I am doing). It does not really control which module positions _will be displayed_.

2022-09-06 14:57 UTC, basd82 commented
![screen shot 2022-09-06 at 14 56 44](https://issues.joomla.org/uploads/1/ca6ce434c6e151e2edb7386dac5e7073.png)
Hi
I have the problem the allowed frontend/backend module positiions stay empty here<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37912">issues.joomla.org/tracker/joomla-cms/37912</a>.</sub>

2022-09-06 15:27 UTC, brianteeman commented
@basd82 Please create a new issue.