com_fields - Fix deprecated warning in group model
joomla/joomla-cms pull request #37932
Opened 2022-05-30 17:54 UTC by chmst

Pull Request for Issue # .

### Summary of Changes
Fix warning 
Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in administrator\components\com_fields\src\Model\GroupModel.php on line 323

### Testing Instructions
Add a new field group in com_contacts (php 8.1.5)

### Actual result BEFORE applying this Pull Request
![grafik](https://user-images.githubusercontent.com/1035262/171040861-5817c3a1-1850-4bba-99dd-3ed4699dc267.png)

### Expected result AFTER applying this Pull Request
No deprecated warning

### Documentation Changes Required

2022-06-01 06:10 UTC, toivo commented
I have tested this item :white_check_mark: successfully on c94011d33791eb4c9f1893d0659fccdd654ccc47<br /><br />Tested successfully in Joomla 4.1.5-dev of 1 June in Wampserver 3.2.9 using PHP 8.1.6.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37932">issues.joomla.org/tracker/joomla-cms/37932</a>.</sub>

2022-06-01 06:23 UTC, alikon requested changes

2022-06-01 06:23 UTC, alikon commented on administrator/components/com_fields/src/Model/GroupModel.php
> -				$context = substr($app->getUserState('com_fields.groups.filter.context'), 4);
i think should be better
```php
$context = substr($app->getUserState('com_fields.groups.filter.context', ''), 4);
```

2022-06-01 06:40 UTC, chmst commented on administrator/components/com_fields/src/Model/GroupModel.php
> -				$context = substr($app->getUserState('com_fields.groups.filter.context'), 4);
thx

2022-06-01 06:41 UTC, chmst commented
@toivo could you please re-test?

2022-06-01 06:42 UTC, alikon commented
I have tested this item :white_check_mark: successfully on df2a42d4f06c5261876cef2fa642d49e1e19db32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37932">issues.joomla.org/tracker/joomla-cms/37932</a>.</sub>

2022-06-03 13:04 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on df2a42d4f06c5261876cef2fa642d49e1e19db32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37932">issues.joomla.org/tracker/joomla-cms/37932</a>.</sub>

2022-06-03 14:40 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37932">issues.joomla.org/tracker/joomla-cms/37932</a>.</sub>

2022-06-05 14:04 UTC, richard67 approved these changes

2022-06-05 19:52 UTC, merged

2022-06-05 19:52 UTC, bembelimen commented
Thx