Improved MVC events
joomla/joomla-cms pull request #37978
Opened 2022-06-04 08:22 UTC by Denitz

### Summary of Changes

1. `events_map` property moved from `FormModel` to `BaseDatabaseModel` because the property is shared by multiple inheritors.
2. All `eventClass` params of `AbstractEvent::create()` calls are shortened to use `Classname::class` notation instead of using string event classname (easier to find all event class usages vide IDE in 2022).
3. `onAfterDisplay` event can modify the output now.
4. New `ListQueryEvent` class and `onContentListQuery` event to modify the list query before executing.
5. New `AfterGetListEvent` class and `onContentAfterGetList` event to modify the list of items after load from database.

### Testing Instructions

1. Apply patch, try to play with custom events via your plugin, i.e.

```
		// All views return 'my custom HTML'
		public function onAfterDisplay(DisplayEvent $event)
		{
			$event->setArgument('source', 'my custom HTML');
		}

		// All lists are ordered by `a.id`
		public function onContentListQuery(DisplayEvent $event)
		{
			$event->getArgument('query')->order('a.id');
		}

		// All lists' titles are 'OK'
		public function onContentAfterGetList(AfterGetListEvent $event)
		{
			foreach($event->getArgument('list') as $item)
			{
				$item->title = 'OK';
			}
		}
```

### Actual result BEFORE applying this Pull Request

Core Joomla is barely extendable.

### Expected result AFTER applying this Pull Request

Core Joomla is extendable.

### Documentation Changes Required

No.

2022-06-04 08:30 UTC, brianteeman commented
Is this backwards compatible?

2022-06-04 10:26 UTC, nibra requested changes
Looks good so far; I don't immediately see any b/c breaks. However, this PR should be targeted at 4.2, as it introduces a new feature.

2022-06-04 10:26 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +	protected function afterGetList($list)
Why not private?

2022-06-04 10:26 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +	protected $event_list_query;
Follow naming conventions: `$eventListQuery`

2022-06-04 10:26 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +	protected $event_after_get_list;
Follow naming conventions: `$eventAfterGetList`

2022-06-04 10:26 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +		}
Use [null coalescing operator](https://www.php.net/manual/en/language.operators.comparison.php#example-121):

```php
$this->event_list_query = $config['event_list_query'] ?? $this->event_list_query ?? 'onContentListQuery';
```

2022-06-04 10:26 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +		}
Same here

2022-06-04 10:26 UTC, nibra commented on libraries/src/MVC/View/HtmlView.php
> +		echo $eventResult->getArgument('source');
This seems to fix a bug that has been undiscovered for a long time.

2022-06-04 10:26 UTC, nibra commented on administrator/components/com_installer/src/Model/InstallerModel.php
> +
Are you sure that you caught all occurances?

2022-06-04 10:28 UTC, Denitz commented on libraries/src/MVC/Model/ListModel.php
> +	protected function afterGetList($list)
`private` and `final` should be avoided in open source, 3rd-party developers can extend classes.

2022-06-04 10:29 UTC, Denitz commented on libraries/src/MVC/Model/ListModel.php
> +	protected $event_list_query;
Currently, all event names are snake-cased, it's better to keep the same style.

2022-06-04 10:29 UTC, Denitz commented on libraries/src/MVC/Model/ListModel.php
> +	protected $event_after_get_list;
Currently, all event names are snake-cased, it's better to keep the same style.

2022-06-04 10:29 UTC, Denitz commented on libraries/src/MVC/Model/ListModel.php
> +		}
I used the same code approach as all other core classes, better keep same.

2022-06-04 10:30 UTC, Denitz commented on libraries/src/MVC/Model/ListModel.php
> +		}
Same

2022-06-04 10:30 UTC, Denitz commented on libraries/src/MVC/View/HtmlView.php
> +		echo $eventResult->getArgument('source');
Show I change something?

2022-06-04 10:31 UTC, Denitz commented on administrator/components/com_installer/src/Model/InstallerModel.php
> +
Yes

2022-06-04 10:32 UTC, Denitz commented
> Is this backwards compatible?

@brianteeman Yes, it only adds the new functionality. I can add the same code in Joomla 3 but won't be accepted :)

2022-06-04 10:39 UTC, richard67 commented
@Denitz New functionality should go into 4.2, if backwards compatible. So this PR should be rebased to the 4.2-dev branch. Let us know if you need help with that.

After rebase, the PR might show unrelated changes on GitHub, but that will go away after the next update of the 4.2-dev branch with the latest changes on the 4.1-dev branch (so-called "upmerge") and after that an update of your branch for this PR to the latest 4.2-dev here.

2022-06-04 14:00 UTC, Denitz commented
@richard67 Rebased

2022-06-04 22:12 UTC, nibra requested changes

2022-06-04 22:12 UTC, nibra commented on administrator/components/com_installer/src/Controller/InstallController.php
>  		}
How is this related to this PR?

2022-06-04 22:12 UTC, nibra commented on administrator/components/com_installer/src/Model/InstallerModel.php
> +
Ok

2022-06-04 22:12 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +	protected $event_list_query;
Like `$listForbiddenList`? Nevertheless: Follow the required code style. It makes no sense to repeat failures from the past.

2022-06-04 22:12 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +	protected $event_after_get_list;
Same as above

2022-06-04 22:12 UTC, nibra commented on libraries/src/MVC/View/HtmlView.php
> +		echo $eventResult->getArgument('source');
`DispatcherInterface::dispatch()` does not have a return value, so `$eventResult` should be `null` in any case. However, plugins may change parameters provided by the event. Thus, `$result` has probably been changed by plugins, so `echo $result` would yield the expected result. `$eventResult` is not reliable, since it only could contain values different from `null`, if the Dispatcher violates the interface - which would be a bug.

2022-06-05 01:04 UTC, Quy commented on libraries/src/Event/Model/AfterGetListEvent.php
> +	public function __construct($name, array $arguments = array())
```suggestion
	public function __construct($name, array $arguments = [])
```

2022-06-05 01:04 UTC, Quy commented on libraries/src/Event/Model/ListQueryEvent.php
> +	public function __construct($name, array $arguments = array())
```suggestion
	public function __construct($name, array $arguments = [])
```

2022-06-05 02:00 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +		}
That old style was used in J3, because it was supposed to work with PHP5. That restriction has gone, so it can be done right now.

2022-06-05 06:01 UTC, Denitz commented on libraries/src/MVC/View/HtmlView.php
> +		echo $eventResult->getArgument('source');
Nope, `\Joomla\Event\DispatcherInterface::dispatch()` returns the event itself and it should! Even PSR-14 requires this, see https://github.com/php-fig/event-dispatcher/blob/aa4f89e91c423b516ff226c50dc83f824011c253/src/EventDispatcherInterface.php#L17

Another issue here:
`DisplayEvent` is immutable!
But we can change the argument via `$event->setArgument('source', $html)` but not via offset like `$event['source'] = $html;`
Is it expected behavior for immutable event?

2022-06-05 06:02 UTC, Denitz commented on libraries/src/MVC/Model/ListModel.php
> +	protected $event_list_query;
Done.

2022-06-05 06:17 UTC, Denitz commented
Drone fails because `xmlreader` is not installed for PHP 8.1, can somebody fix it?

2022-06-05 08:29 UTC, nibra commented on libraries/src/MVC/View/HtmlView.php
> +		echo $eventResult->getArgument('source');
You're right, I went into the trap and looked at `\Joomla\CMS\Dispatcher\DispatcherInterface`.

> But we can change the argument via `$event->setArgument('source', $html)`

That's obviously an oversight. The event is immutable. The event handler should create a new event with the desired values as a return object.

2022-06-05 08:33 UTC, richard67 commented on administrator/components/com_installer/src/Controller/InstallController.php
>  		}
Possibly one of the unrelated changes shown after branch rebase which are caused by the 4.2-dev branch being a commit behind the 4.1-dev branch. If this is the case, it was wrong to revert that change here in this PR.

2022-06-05 08:37 UTC, nibra commented on libraries/src/MVC/Model/ListModel.php
> +	protected function afterGetList($list)
> `private` and `final` should be avoided in open source

Surely not. Exactly because 3PD can extend the classes, both should be used wherever possible.
The purpose of this method is solely to apply the plugins to make the class extensible.
If the method is `protected`, this is an invitation for 3PD to destroy this functionality.

2022-06-05 08:54 UTC, richard67 commented on administrator/components/com_installer/src/Controller/InstallController.php
>  		}
Anyway it can be finally solved after the next upmerge from 4.1-dev to 4.2-dev and then the branch update here. We should leave this review comment open as reminder and set it to resolved when that has been done.

2022-06-05 08:55 UTC, richard67 commented
> Drone fails because `xmlreader` is not installed for PHP 8.1, can somebody fix it?

Have contacted maintainers to check.

2022-06-05 09:43 UTC, Denitz commented on libraries/src/MVC/View/HtmlView.php
> +		echo $eventResult->getArgument('source');
The purpose of event is to be able to modify output, I think we should use usual mutable event (DisplayEvent extends AbstractEvent) and view will return the event argument as I've already added, please confirm.

2022-06-05 21:29 UTC, nibra commented on libraries/src/MVC/View/HtmlView.php
> +		echo $eventResult->getArgument('source');
Keep the `echo $eventResult->getArgument('source');`, but let the event alone for now. There are currently considerations to improve the event system for Joomla 5. It's early enough to address that (mutable vs. immutable) once decisions are made for the improvements.

2022-06-06 05:32 UTC, Denitz commented on libraries/src/MVC/View/HtmlView.php
> +		echo $eventResult->getArgument('source');
OK.

2022-06-07 06:19 UTC, Denitz commented
Is it possible to restart drone?

2022-06-07 06:23 UTC, richard67 commented
> Is it possible to restart drone?

@Denitz I have done that recently a few times, but the tests fail all at the same step: Logging in to admin after a new installation. Have you tested this yourself, making a new installation with your PR applied, and then logging in to backend? I'll restart drone now but I do not really expect new results.

2022-06-07 09:23 UTC, richard67 commented on libraries/src/Event/Model/AfterGetListEvent.php
> +	 * list			\stdClass[]			Item list.
```suggestion
	 * subject  ListModelInterface  The model instance we are operating on.
	 * context  string              The model context.
	 * list     \stdClass[]         Item list.
```

2022-06-07 09:24 UTC, richard67 commented on libraries/src/Event/Model/ListQueryEvent.php
> +	 * query		QueryInterface		Database query.
```suggestion
	 * subject  ListModelInterface  The model instance we are operating on.
	 * context  string              The model context.
	 * query    QueryInterface      Database query.
```

2022-06-08 05:29 UTC, Denitz commented on administrator/components/com_installer/src/Controller/InstallController.php
>  		}
4.1-dev was merged via https://github.com/joomla/joomla-cms/commit/c297caa4c0b3368d7f89af44c2bec1b353c37619
I will try to update branch

2022-06-12 09:30 UTC, heelc29 commented on libraries/src/Event/Model/AfterGetListEvent.php
> + * @copyright  (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright  (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-06-12 09:30 UTC, heelc29 commented on libraries/src/Event/Model/ListQueryEvent.php
> + * @copyright  (C) 2020 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright  (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-06-12 09:30 UTC, heelc29 commented on libraries/src/MVC/Model/ListModel.php
> +		$this->eventAfterGetList = $config['eventAfterGetList'] ?? $this->eventAfterGetList ?? 'onContentAfterGetList';
```suggestion
		$this->eventListQuery    = $config['eventListQuery'] ?? $this->eventListQuery ?? 'onContentListQuery';
		$this->eventAfterGetList = $config['eventAfterGetList'] ?? $this->eventAfterGetList ?? 'onContentAfterGetList';
```

2022-06-12 09:30 UTC, heelc29 commented on libraries/src/MVC/Model/ListModel.php
> +			), $config['events_map']
```suggestion
			[
				'list_query'     => 'content',
				'after_get_list' => 'content',
			],
			$config['events_map']
```

2022-06-12 09:30 UTC, heelc29 commented on libraries/src/MVC/Model/ListModel.php
> +					'query' => $this->query,
```suggestion
					'subject' => $this,
					'context' => $this->context,
					'query'   => $this->query,
```

2022-06-12 09:30 UTC, heelc29 commented on libraries/src/MVC/Model/ListModel.php
> +				'list' => $list,
```suggestion
				'subject' => $this,
				'context' => $this->context,
				'list'    => $list,
```

2022-06-13 07:18 UTC, HLeithner commented
There is a reason why we don't have a listquery event because it creates more then it solves. This has discussed several times.

Also the modification of the result is questionable. Because we easily generate more problems then expected.

2022-06-13 07:33 UTC, laoneo commented on libraries/src/MVC/Model/BaseDatabaseModel.php
> +	protected $events_map;
Please revert this change as a class should not have properties which are not used by itself.

2022-06-13 07:33 UTC, laoneo commented on administrator/components/com_installer/src/Model/UpdateModel.php
> +			$result = $this->afterGetList($result);
Would that mean that every model which extends the listmodel and does overwrite the _getList function needs to call this.

2022-06-13 08:28 UTC, Denitz commented on administrator/components/com_installer/src/Model/UpdateModel.php
> +			$result = $this->afterGetList($result);
Ideally, it should if the model wants to apply the event.

2022-06-13 08:56 UTC, Denitz commented on libraries/src/MVC/Model/BaseDatabaseModel.php
> +	protected $events_map;
Reverted.

2022-06-13 09:52 UTC, HLeithner requested changes
Please remove the new Events for query manipulation, this has been discussed several times for more information look at https://github.com/joomla/joomla-cms/pull/26179

2022-06-14 08:43 UTC, Denitz commented
> Please remove the new Events for query manipulation, this has been discussed several times for more information look at #26179

Sorry and thanks for your time. The query manipulation was the main feature of this PR.

2022-06-14 09:22 UTC, laoneo commented
Would you mind to open a new pr which removes the hard codec class paths?

2022-06-15 11:02 UTC, Denitz commented
I removed onContentListQuery event, though I totally disagree.

2022-07-02 10:10 UTC, closed without merging