[6.1] Fix for missing Fulltext Image in Newsfeeds
joomla/joomla-cms pull request #38058
Opened 2022-06-14 14:39 UTC by AndySDH

As requested, Joomla 4.2 re-do of Pull Request #28195

### Summary of Changes

Originally Joomla RSS Newsfeeds were completely missing the image_intro and image_fulltext. This was partially fixed with this PR: https://github.com/joomla/joomla-cms/pull/11402

But that only introduced the image_intro, and forgot the image_fulltext.

So an article that had an image_fulltext would not use that image in the feed.

This PR simply adds the image_fulltext to the feed if the image_intro is empty, for both the category view and featured view.

2022-06-14 16:43 UTC, richard67 commented
@AndySDH Could you fix the code style errors reported by drone here https://ci.joomla.org/joomla/joomla-cms/55308/1/6 ? Thanks in advance.

2022-06-14 16:58 UTC, AndySDH commented
@richard67 Should be done :)

2022-06-14 17:20 UTC, richard67 commented
> @richard67 Should be done :)

@AndySDH Not really. There are still some complaints: https://ci.joomla.org/joomla/joomla-cms/55316/1/6

2022-06-14 17:29 UTC, AndySDH commented
New try

2022-06-14 17:38 UTC, richard67 commented
@AndySDH Still not ok: https://ci.joomla.org/joomla/joomla-cms/55320/1/6 .

2022-06-14 18:57 UTC, AndySDH commented
Well it's going in circles a bit. If I take out those spaces, the indentation will look off. I'm not sure that's a valid complaint there, not sure.

2022-06-14 19:06 UTC, richard67 commented
> Well it's going in circles a bit. If I take out those spaces, the indentation will look off. I'm not sure that's a valid complaint there, not sure.

@AndySDH It is a valid complaint. The indentation of the “=“ and the lines below do not need to be aligned. Furthermore the lines below should be indented with tabs. I would also suggest to put the operators “?” and “:” of the ternaries to the beginning of a line and not the end of the previous line. And I would indent the 2nd ternary by one tab more than the first one. Maybe check how it is done elsewhere.

2022-06-14 19:15 UTC, AndySDH commented
Thanks for the suggestions :) Should be good now hopefully.

2022-06-14 19:18 UTC, brianteeman commented on components/com_content/src/View/Featured/FeedView.php
> +					( !empty($obj->{'image_fulltext'})
```suggestion
					(!empty($obj->{'image_fulltext'})
```

2022-06-14 19:19 UTC, brianteeman commented on components/com_content/src/View/Category/FeedView.php
> +				( !empty($obj->{'image_fulltext'})
```suggestion
				(!empty($obj->{'image_fulltext'})
```

2022-06-15 14:24 UTC, laoneo commented on components/com_content/src/View/Category/FeedView.php
> +		$itemImage = !empty($obj->{'image_intro'})
Can you make this a bit simpler, very hard to read for an outsider.

2022-06-15 16:49 UTC, richard67 commented on components/com_content/src/View/Featured/FeedView.php
> +			} elseif (!empty($obj->{'image_fulltext'}))
```suggestion
			}
			elseif (!empty($obj->{'image_fulltext'}))
```
Fix code style errors reported by drone.

2022-06-15 16:50 UTC, richard67 commented on components/com_content/src/View/Category/FeedView.php
> +		} elseif (!empty($obj->{'image_fulltext'}))
```suggestion
		}
		elseif (!empty($obj->{'image_fulltext'}))
```
Fix code style errors reported by drone.

2022-06-20 07:11 UTC, laoneo approved these changes

2022-06-20 14:46 UTC, Quy commented on components/com_content/src/View/Category/FeedView.php
> +		if (!empty($obj->{'image_intro'}))
```suggestion
		if (!empty($obj->{'image_intro'}))
```

2022-06-20 14:46 UTC, Quy commented on components/com_content/src/View/Featured/FeedView.php
> +			if (!empty($obj->{'image_intro'}))
```suggestion
			if (!empty($obj->{'image_intro'}))
```

2022-06-20 14:48 UTC, Quy commented on components/com_content/src/View/Category/FeedView.php
> +			$item->description = '<p>' . HTMLHelper::_('image', $itemImage, $obj->image_intro_alt) . '</p>';
Shouldn't the `alt` value correspond to the image that is used?

2022-08-24 10:48 UTC, GixxerMKD commented
The images are completely missing from the tags rss feed, can somebody look into this?
If you create a menu item with tags (Menu Item Type: Tagged Items) and check the RSS feed it will contain no images, also the <category> contains the item title, not the category.

2022-08-24 10:58 UTC, Franzwohlkoenig commented
Solved with PR https://github.com/joomla/joomla-cms/pull/38312 .

2022-08-24 11:08 UTC, GixxerMKD commented
> @GixxerMKD Solved with PR #38312 .

Not same issue, this is the file in question:
components/com_tags/src/View/Tag/FeedView.php

no image for item and wrong code for category:
`($feeditem->category = $title;)`

2023-05-02 16:42 UTC, HLeithner commented
This pull request has been automatically rebased to 5.0-dev.

2023-06-17 14:34 UTC, AndySDH commented
Hello, I've updated the code with a cleaner and more simple approach.
Can this be reviewed and merged please?

2023-06-19 07:47 UTC, laoneo commented
@AndySDH this needs to go into 5.0 earliest. Please leave the base branch.

2023-06-19 20:20 UTC, AndySDH commented
@laoneo How comes? This is a minor new functionality, should be perfectly fine for a minor release like eg. 4.3 or 4.4.

2023-09-30 22:51 UTC, HLeithner commented
This pull request has been automatically rebased to 5.1-dev.

2023-10-02 11:37 UTC, AndySDH commented
Hello, this needs some tests please!

2024-02-24 16:01 UTC, stimpsonjcat commented
Confirmed this works. ✅
I created an article with only a full text image. Left the intro image blank. The feed now will show the full text image in the feed.

2024-02-24 16:02 UTC, stimpsonjcat commented
I have tested this item :white_check_mark: successfully on b2d557e9f55e63c93486808cb5d3e36adc39784e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38058">issues.joomla.org/tracker/joomla-cms/38058</a>.</sub>

2024-04-24 09:09 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2024-06-13 10:41 UTC, AndySDH commented
Hey there, can this please be merged?

2024-06-13 11:22 UTC, brianteeman commented
You need to fic the codestyle issues https://ci.joomla.org/joomla/joomla-cms/76705/1/7

2024-06-13 11:24 UTC, AndySDH commented
How do I fix? Didn't it use to be automatic with the click of a button? Can't see it anymore

2024-06-13 11:48 UTC, brianteeman commented
> How do I fix? Didn't it use to be automatic with the click of a button? Can't see it anymore

No you have to fix it in your branch and push the changes

2024-06-13 12:35 UTC, AndySDH commented
And what is the fix I need to make? I can't tell from the phpcs log, it's not very clear.

2024-06-13 13:01 UTC, brianteeman commented on components/com_content/src/View/Category/FeedView.php
> +		}
```suggestion
        } elseif (!empty($obj->image_fulltext)) {
            $item->description = '<p>' . HTMLHelper::_('image', $obj->image_fulltext, $obj->image_fulltext_alt) . '</p>';
        }
```
change the tabs to spaces

2024-06-13 13:13 UTC, AndySDH commented
Thank you, committed :)

2024-07-25 21:57 UTC, brianteeman commented
Could someone please retrigger drone so we can see what its failing on

2024-08-30 04:27 UTC, Quy commented on components/com_content/src/View/Category/FeedView.php
> +        $obj->image_fulltext_alt = $obj->image_fulltext_alt ?? '';
```suggestion
        $obj->image_intro_alt    = $obj->image_intro_alt ?? '';
        $obj->image_fulltext_alt = $obj->image_fulltext_alt ?? '';
```

2024-08-30 04:27 UTC, Quy commented on components/com_content/src/View/Featured/FeedView.php
> +            $obj->image_fulltext_alt = $obj->image_fulltext_alt ?? '';
```suggestion
            $obj->image_intro_alt    = $obj->image_intro_alt ?? '';
            $obj->image_fulltext_alt = $obj->image_fulltext_alt ?? '';
```

2024-08-30 06:38 UTC, fgsw commented
Using menu item type "Category Blog" for a feed works as described.

Using menu item type "Featured Articles" for a feed give ```The requested page can't be found.```:

<div class="card"><div class="card-body"><main><blockquote>
                            <span class="badge bg-secondary">0</span> No registered feed parser for type error.                        </blockquote>
                    </main>
                </div>
            </div>
                                        <div>
                    <h2 id="caption">Call Stack</h2>

| # | Function | Location
--- | --- | ---
1 | () | JROOT/libraries/src/Feed/FeedFactory.php:148
2 | Joomla\CMS\Feed\FeedFactory->_fetchFeedParser() | JROOT/libraries/src/Feed/FeedFactory.php:84
3 | Joomla\CMS\Feed\FeedFactory->getFeed() | JROOT/components/com_newsfeeds/src/View/Newsfeed/HtmlView.php:180
4 | Joomla\Component\Newsfeeds\Site\View\Newsfeed\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
5 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_newsfeeds/src/Controller/DisplayController.php:58
6 | Joomla\Component\Newsfeeds\Site\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:218
10 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:261
11 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
13 | require_once() | JROOT/index.php:32

</div>

Test System Information:

**PHP Built On** 	Darwin Air.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 x86_64
**Database Type** 	mysql
**Database Version** 	8.0.35
**Database Collation** 	utf8mb4_unicode_ci
**Database Connection Collation** 	utf8mb4_0900_ai_ci
**Database Connection Encryption** 	**None**
**Database Server Supports Connection Encryption** 	**Yes**
**PHP Version** 	8.3.8
**Web Server** 	Apache/2.4.58 (Unix) OpenSSL/1.1.1u mod_fastcgi/mod_fastcgi-SNAP-0910052141
**WebServer to PHP Interface** 	cgi-fcgi
**Joomla! Version** 	Joomla! 5.2.0-beta2-dev Development [ Uthabiti ] 23-July-2024 16:01 GMT
**Joomla Backward Compatibility Plugin** 	**Disabled**
**User Agent** 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0

2024-08-30 07:48 UTC, AndySDH commented
@fgsw Doesn't seem related to this PR. The file changed in this PR has nothing to do with the error trace you've shown.

2024-08-30 17:37 UTC, Quy commented on components/com_content/src/View/Category/FeedView.php
> +        $obj->image_intro_alt    = $obj->image_intro_alt ?? '';
If `$obj` is null, then the following error:

```
<?xml version="1.0" encoding="UTF-8"?>
<error>
	<code>0</code>
	<message>Attempt to assign property &quot;image_intro_alt&quot; on null</message>
</error>
```

Checking for the alt property should not be necessary so remove the check/assignment.

PS: The code is self explanatory so these comments don't provide additional information.

2024-08-31 06:07 UTC, fgsw commented
I have tested this item :white_check_mark: successfully on 03ec896f99c03a3932aecaa2aaa50e40afe32db0<br /><br />Prebuilt package used for test. First test by patchtester.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38058">issues.joomla.org/tracker/joomla-cms/38058</a>.</sub>

2024-09-02 08:53 UTC, HLeithner commented
This pull request has been automatically rebased to 5.3-dev.

2025-03-04 17:23 UTC, HLeithner commented
This pull request has been automatically rebased to 6.0-dev.

2025-06-04 07:29 UTC, Bodge-IT commented
@AndySDH, RM here, looking at this feature for 6.0 and we like it.  Could you check Quy's comment?  Thanks.

2025-06-04 08:07 UTC, AndySDH commented
@Bodge-IT Thanks, I fixed the error he mentioned.

2025-06-04 08:15 UTC, laoneo reviewed
The need to be namespaced

2025-06-04 08:15 UTC, laoneo commented on components/com_content/src/View/Category/FeedView.php
> +        $obj               = json_decode($item->images) ?? new stdClass();
```suggestion
        $obj               = json_decode($item->images) ?? new \stdClass();
```

2025-06-04 08:15 UTC, laoneo commented on components/com_content/src/View/Featured/FeedView.php
> +            $obj         = json_decode($row->images) ?? new stdClass();
```suggestion
            $obj         = json_decode($row->images) ?? new \stdClass();
```

2025-06-06 23:34 UTC, QuyTon commented on components/com_content/src/View/Category/FeedView.php
> +        $obj->image_intro_alt    = $obj->image_intro_alt ?? '';
Please consider moving these into their respective if statement section.

2025-06-12 07:02 UTC, Bodge-IT commented
@AndySDH can you look into Quy's change request?

2025-06-12 07:32 UTC, AndySDH commented
@Bodge-IT @QuyTon To be honest I'm not sure what he means. If he wants to make a change, he can make it himself. I'm a bit tired to continue making changes to this PR one small change at a time. This super small PR has been opened for 3 years (5 years if we count the original) and has 41 commits with all the requests. If @QuyTon wants to fix it, you can do it.

2025-06-12 09:22 UTC, Bodge-IT commented
Hi @AndySDH he's merely suggesting you consider moving the 2 lines setting properties inside the their respective ifs like:
```HTMLHelper::_('image', $obj->image_intro, $obj->image_intro_alt ?? '')```

2025-06-12 09:24 UTC, AndySDH commented
Make a commit suggestion with the code change and I can approve it. I'm not an expert coder

2025-06-12 10:31 UTC, Bodge-IT requested changes
This address Quyton's request but $obj being null mention by @Quy will still throw an error.  See my other change request.

2025-06-12 10:31 UTC, Bodge-IT commented on components/com_content/src/View/Category/FeedView.php
> +            $item->description = '<p>' . HTMLHelper::_('image', $obj->image_fulltext, $obj->image_fulltext_alt) . '</p>';
remove you check/set and mv it inside the if
```suggestion
        // Set feed image to image_intro or if that's empty, to image_fulltext
        if (!empty($obj->image_intro)) {
            $item->description = '<p>' . HTMLHelper::_('image', $obj->image_intro, $obj->image_intro_alt ?? '') . '</p>';
        } elseif (!empty($obj->image_fulltext)) {
            $item->description = '<p>' . HTMLHelper::_('image', $obj->image_fulltext, $obj->image_fulltext_alt ?? '') . '</p>';
```

2025-06-12 10:31 UTC, Bodge-IT commented on components/com_content/src/View/Featured/FeedView.php
> +                $description = '<p>' . HTMLHelper::_('image', $obj->image_fulltext, $obj->image_fulltext_alt) . '</p>';
Again..
```suggestion
            // Set feed image to image_intro or if that's empty, to image_fulltext
            if (!empty($obj->image_intro)) {
                $description = '<p>' . HTMLHelper::_('image', $obj->image_intro, $obj->image_intro_alt ?? '') . '</p>';
            } elseif (!empty($obj->image_fulltext)) {
                $description = '<p>' . HTMLHelper::_('image', $obj->image_fulltext, $obj->image_fulltext_alt ?? '') . '</p>';
```

2025-06-12 10:37 UTC, Bodge-IT reviewed
This should ensure $obj is never null.  Please review.

2025-06-12 10:37 UTC, Bodge-IT commented on components/com_content/src/View/Category/FeedView.php
> +        $obj               = json_decode($item->images) ?? new \stdClass();
You marked Quy's comment about error as resolved but it wasn't...
```suggestion
        $obj               = json_decode($item->images ?? '{}');
```

2025-06-12 10:37 UTC, Bodge-IT commented on components/com_content/src/View/Featured/FeedView.php
> +            $obj         = json_decode($row->images) ?? new \stdClass();
here too...
```suggestion
            $obj = json_decode($row->image ?? '{}');
```

2025-06-13 18:00 UTC, AndySDH commented
Thanks a lot, I committed all the suggestions. Hopefully it's good now!

2025-06-16 13:54 UTC, Bodge-IT commented
Thanks @AndySDHm, We'll get it tested...ASP

2025-07-15 20:08 UTC, Bodge-IT approved these changes

2025-07-15 20:09 UTC, Bodge-IT approved these changes

2025-07-15 20:09 UTC, Bodge-IT approved these changes

2025-07-16 00:17 UTC, exlemor commented
@Bodge-IT  am I doing something wrong, when I test this, the resulting output includes:

<p><img src="https://www.mood-lights.com/_j600//_j600/images/banners/banner.jpg" alt="" width="512" height="512" loading="lazy"></p>

while it should be:

<p><img src="https://www.mood-lights.com/_j600/images/banners/banner.jpg" alt="" width="512" height="512" loading="lazy"></p> to be able to display correctly??

2025-07-23 09:02 UTC, Bodge-IT commented
No you're not doing anything wrong, it's adding the basedir in there.  Is for me too but mine is just "/"

2025-07-23 09:07 UTC, brianteeman commented
@Bodge-IT @exlemor is it also doing this for the introtext image

2025-07-30 07:52 UTC, Bodge-IT commented
> is it

Sry @brianteeman I read that as 'it is'
... yes, it is doing for both.

2025-08-08 17:02 UTC, Bodge-IT commented
Hi @AndySDH we're still looking to get this in 6.0.  Having looked at the issue detailed by @exlemor above, we need the basedir excluded from the path in your code.  Could you review please?

2025-08-08 17:51 UTC, AndySDH commented
@Bodge-IT Not sure how to do that. If somebody can take over and do it that would be great.

2025-08-08 18:42 UTC, brianteeman commented
it probably needs you to add Uri::root(true) 

`$item->description = '<p>' . Uri::root(true) . '/' . HTMLHelper::_('image', $obj->image_intro, $obj->image_intro_alt ?? '')`

_not at my pc so cant check it but it should be something like that_

2026-01-30 09:05 UTC, vishalchincholi1 commented
I have tested this item :white_check_mark: successfully on 03ec896f99c03a3932aecaa2aaa50e40afe32db0<br /><br />Test Script: Logic verification for FeedView.php fallback mechanism
[TEST 1] Scenario: Intro Image Present, Fulltext Empty
   STATUS: PASS
   Info: Correctly used Intro Image.
[TEST 2] Scenario: Intro Image Empty, Fulltext Present (The Fix)
   STATUS: PASS
   Info: Correctly fell back to Fulltext Image.
[TEST 3] Scenario: Both Images Present
   STATUS: PASS
   Info: Correctly prioritized Intro Image.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38058">issues.joomla.org/tracker/joomla-cms/38058</a>.</sub>

2026-01-30 11:15 UTC, kkbiswal commented
I have tested this item :white_check_mark: successfully on 03ec896f99c03a3932aecaa2aaa50e40afe32db0<br /><br />Tested with 962b2c1fdc and confirmed the fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38058">issues.joomla.org/tracker/joomla-cms/38058</a>.</sub>

2026-04-15 09:13 UTC, bembelimen commented
Sorry my fault, missed this PR when deleting the branch.

2026-05-08 11:00 UTC, brianteeman commented
I can confirm that this PR does what it says but I am not convinced it is correct.

If I have a page of featured articles that only have full_image then there are no images on the page and that is what I would expect the rss feed to represent

With this PR the rss feed will now include the full_image of each article even thought they are not on the page

2026-06-24 17:12 UTC, HLeithner commented
Thanks for your time creating this pr, but I have to inform you that maintainer decided on 24.06.2026 to reject this as not wanted.

2026-06-24 17:12 UTC, closed without merging

2026-09-16 08:45 UTC, AndySDH commented
> I can confirm that this PR does what it says but I am not convinced it is correct.
> 
> If I have a page of featured articles that only have full_image then there are no images on the page and that is what I would expect the rss feed to represent
> 
> With this PR the rss feed will now include the full_image of each article even thought they are not on the page

Sorry but I have to re-open this and disagree with this.

A RSS feed is a feed to be used externally by other sites to fetch your articles. So each entry in the RSS feed should send the image associated to each article, which can be the Full Article Image if the Intro Image is empty. It doesn't matter if in your own category blog page you don't show images in the article listing. The feed you send to external sites should include a representative image for the article.

PS: Also, the fact that you have no images of a category/featured blog page, it's your experience. On my sites, for example, I have a template override where I do show the full article image in category blog listing in case the intro image is empty.

2026-09-16 08:45 UTC, AndySDH commented
> Thanks for your time creating this pr, but I have to inform you that maintainer decided on 24.06.2026 to reject this as not wanted.

I disagree with this decision, it makes no sense to me, see my reply above.