[4.2] Convert the checkfiles plugin to service provider
joomla/joomla-cms pull request #38072
Opened 2022-06-16 07:06 UTC by laoneo

### Summary of Changes
Converts the checkfiles plugin to service provider and adds some unit tests. This pr is based on #38060, so please test that one first.

### Testing Instructions
- Create a folder in images with the name test and upload there a big image from unsplash or so which is bigger than 1080 pixels
- Go to the task scheduler back end list
- Click on new "Image Size Check"
- Select the test image in the task parameters
- Save the task and close the form
- Run the task by clicking on "Run Test" button

### Actual result BEFORE applying this Pull Request
The image in the test folder has a width or height of 1080 pixels.

### Expected result AFTER applying this Pull Request
The image in the test folder has a width or height of 1080 pixels.

2022-06-18 12:39 UTC, richard67 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +        imagedestroy($image);
```suggestion
		$image = imagecreate(200, 200);
        imagecolorallocate($image, 255, 255, 0);
        imagepng($image, __DIR__ . '/tmp/test.png');
        imagedestroy($image);
```
```suggestion
		$image = imagecreate(200, 200);
		imagecolorallocate($image, 255, 255, 0);
		imagepng($image, __DIR__ . '/tmp/test.png');
		imagedestroy($image);
```
@laoneo You really should adjust your editor so you can see what is a tab and what are spaces, and switch off any auto indentation features. I found this place here now where a mix was used. I haven't checked at other places of this PR. Please do so.

2022-06-18 12:41 UTC, richard67 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +    {
```suggestion
	public function setUp(): void
	{
```

2022-06-18 12:41 UTC, richard67 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +    }
```suggestion
	}
```

2022-06-18 12:42 UTC, richard67 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +    }
```suggestion
	public function tearDown(): void
	{
		if (is_dir(__DIR__ . '/tmp'))
		{
			Folder::delete(__DIR__ . '/tmp');
		}
	}
```

2022-06-21 18:09 UTC, heelc29 requested changes

2022-06-21 18:09 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +namespace Joomla\Tests\Unit\Plugin\Task\Requests\Extension;
```suggestion
namespace Joomla\Tests\Unit\Plugin\Task\Checkfiles\Extension;
```

2022-06-21 18:09 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +class RequestsPluginTest extends UnitTestCase
```suggestion
class CheckfilesPluginTest extends UnitTestCase
```

2022-06-21 18:09 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> + * Test class for Requests plugin
```suggestion
 * Test class for Checkfiles plugin
```

2022-06-21 18:09 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> + * @subpackage  Requests
```suggestion
 * @subpackage  Checkfiles
```

2022-06-21 18:09 UTC, heelc29 commented on plugins/task/checkfiles/checkfiles.xml
> +		<folder plugin="requests">services</folder>
```suggestion
		<folder plugin="checkfiles">services</folder>
```

2022-06-21 18:12 UTC, heelc29 commented on plugins/task/checkfiles/src/Extension/Checkfiles.php
> +	 * @param   string               $rootDirectory  The root directory to lok for images
```suggestion
	 * @param   string               $rootDirectory  The root directory to look for images
```

2022-06-22 15:43 UTC, alikon commented
I have tested this item :white_check_mark: successfully on db97381661de915288cb4d52ec6b2ed36caa2507<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38072">issues.joomla.org/tracker/joomla-cms/38072</a>.</sub>

2022-06-27 20:25 UTC, HLeithner commented
> A new pull request has been created automatically to convert this PR to the PSR-12 coding standard. The pr can be found at [Digital-Peak#24](https://github.com/Digital-Peak/joomla-cms/pull/24)

there was a merge error on this pull request please check if worked correctly

2022-06-28 06:11 UTC, laoneo commented
I had to redo this pr, @heelc29 can you have a look again if I missed something. Thanks!

2022-06-29 17:40 UTC, heelc29 reviewed
the same changes 😅

2022-06-29 17:40 UTC, heelc29 commented on plugins/task/checkfiles/checkfiles.xml
> +		<folder plugin="requests">services</folder>
```suggestion
		<folder plugin="checkfiles">services</folder>
```

2022-06-29 17:40 UTC, heelc29 commented on plugins/task/checkfiles/src/Extension/Checkfiles.php
> +     * @param   string               $rootDirectory  The root directory to lok for images
```suggestion
     * @param   string               $rootDirectory  The root directory to look for images
```

2022-06-29 17:40 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +namespace Joomla\Tests\Unit\Plugin\Task\Requests\Extension;
```suggestion
namespace Joomla\Tests\Unit\Plugin\Task\Checkfiles\Extension;
```

2022-06-29 17:40 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> + * Test class for Requests plugin
```suggestion
 * Test class for Checkfiles plugin
```

2022-06-29 17:40 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> + * @subpackage  Requests
```suggestion
 * @subpackage  Checkfiles
```

2022-06-29 18:13 UTC, laoneo commented
I know, somehow thebpsr change screwed up the pr and I had to redo it from an old stage. Sorry for that and thanks for your help.

2022-06-30 16:51 UTC, heelc29 reviewed
several cs errors
https://ci.joomla.org/joomla/joomla-cms/56095/1/6

2022-06-30 16:51 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +/**
```suggestion
<?php

/**
```

2022-06-30 16:51 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +        {
```suggestion
        if (!is_dir(__DIR__ . '/tmp')) {
```

2022-06-30 16:51 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +        {
```suggestion
        if (is_dir(__DIR__ . '/tmp')) {
```

2022-06-30 16:51 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +        $plugin = new Checkfiles(new Dispatcher, [], __DIR__);
```suggestion
        $plugin = new Checkfiles(new Dispatcher(), [], __DIR__);
```

2022-06-30 16:51 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +        $plugin = new Checkfiles(new Dispatcher, [], __DIR__);
```suggestion
        $plugin = new Checkfiles(new Dispatcher(), [], __DIR__);
```

2022-06-30 16:51 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +        $plugin = new Checkfiles(new Dispatcher, [], __DIR__);
```suggestion
        $plugin = new Checkfiles(new Dispatcher(), [], __DIR__);
```

2022-06-30 16:51 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +        $plugin = new Checkfiles(new Dispatcher, [], __DIR__);
```suggestion
        $plugin = new Checkfiles(new Dispatcher(), [], __DIR__);
```

2022-06-30 16:51 UTC, heelc29 commented on tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
> +        copy(__DIR__ . '/tmp/test.png',__DIR__ . '/tmp/test1.png');
```suggestion
        copy(__DIR__ . '/tmp/test.png', __DIR__ . '/tmp/test1.png');
```

2022-07-03 08:06 UTC, roland-d requested changes

2022-07-03 08:06 UTC, roland-d commented on plugins/task/checkfiles/src/Extension/Checkfiles.php
> +            $this->logTask($this->translate('PLG_TASK_CHECK_FILES_LOG_RESIZING_IMAGE', $width, $height, $newWidth, $newHeight, $imageFilename));
@laoneo This should be reverted as the `translate()` function no longer exists.

2022-07-03 08:06 UTC, roland-d commented on plugins/task/checkfiles/src/Extension/Checkfiles.php
> +            $this->logTask($this->translate('PLG_TASK_CHECK_FILES_LOG_IMAGE_PATH_NA'), 'warning');
@laoneo This should be reverted as the translate() function no longer exists.

2022-07-03 08:06 UTC, roland-d commented on plugins/task/checkfiles/src/Extension/Checkfiles.php
> +                $this->logTask($this->translate('PLG_TASK_CHECK_FILES_LOG_RESIZE_FAIL'), 'error');
@laoneo This should be reverted as the translate() function no longer exists.

2022-07-03 08:06 UTC, roland-d commented on plugins/task/checkfiles/src/Extension/Checkfiles.php
> +                $this->logTask($this->translate('PLG_TASK_CHECK_FILES_LOG_IMAGE_SAVE_FAIL'), 'error');
@laoneo This should be reverted as the translate() function no longer exists.

2022-07-03 08:18 UTC, laoneo commented on plugins/task/checkfiles/src/Extension/Checkfiles.php
> +            $this->logTask($this->translate('PLG_TASK_CHECK_FILES_LOG_RESIZING_IMAGE', $width, $height, $newWidth, $newHeight, $imageFilename));
done

2022-07-03 12:01 UTC, roland-d approved these changes

2022-07-03 12:01 UTC, merged

2022-07-03 12:01 UTC, roland-d commented
Thank you