[4.2][cli] cache:clean
joomla/joomla-cms pull request #38091
Opened 2022-06-19 07:14 UTC by alikon

Pull Request for Issue #37646 .

### Summary of Changes
- added `expired` argument

### Testing Instructions
run `php cli/joomla.php cache:clean`
or
run `php cli/joomla.php cache:clean expired`

check the cache in the admin or cache storage

### Actual result BEFORE applying this Pull Request

cache not cleaned

### Expected result AFTER applying this Pull Request

cache cleaned

### Documentation Changes Required

2022-06-19 07:38 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/174470798-74b70902-e50c-4c46-8298-829527ff7feb.png)

2022-06-19 07:39 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/174470809-e085dac3-05e7-43a0-a308-d47b9d8234e8.png)

2022-06-19 08:33 UTC, alikon commented
fixed

2022-06-19 08:46 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/174473092-5f4415da-6bfc-4c62-a353-55e8e1f989bf.png)

2022-06-19 08:49 UTC, alikon commented
i'll check later on a fresh 4.2-dev 
i suppose this happen even without this pr....

2022-06-20 07:04 UTC, alikon commented
checked with last 4.2-dev  and it's working fine

2022-06-20 07:09 UTC, laoneo requested changes

2022-06-20 07:09 UTC, laoneo commented on libraries/src/Console/CleanCacheCommand.php
> +		$cache = Factory::getApplication()->bootComponent('com_cache')->getMVCFactory();
Can you use here `$this->getApplication()`

2022-06-20 07:16 UTC, alikon commented on libraries/src/Console/CleanCacheCommand.php
> +		$cache = Factory::getApplication()->bootComponent('com_cache')->getMVCFactory();
done

2022-06-20 07:17 UTC, laoneo approved these changes

2022-06-20 08:26 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on c59d594bfb79a0b9f66145ba531497612656e624<br /><br />no idea why it didnt work before (although I suspect it was me) but it is working now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38091">issues.joomla.org/tracker/joomla-cms/38091</a>.</sub>

2022-06-20 18:50 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on c59d594bfb79a0b9f66145ba531497612656e624<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38091">issues.joomla.org/tracker/joomla-cms/38091</a>.</sub>

2022-06-20 18:51 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38091">issues.joomla.org/tracker/joomla-cms/38091</a>.</sub>

2022-06-20 19:04 UTC, merged