Joomla.enqueueRequest and Request promise
joomla/joomla-cms pull request #38172
Opened 2022-06-28 15:49 UTC by Fedik

### Summary of Changes

This is redo #38019 and #38030

The PR allow `Joomla.request` to return a Promise.
And add `Joomla.enqueueRequest` method to allow run the requests in sequence.

It is better if it will be tested and accepted before 4.2 release.

### Testing Instructions

Please follow #38019 
Because it a redo of that PR, make sure tha it still works as there described.

### Documentation Changes Required

Need update `Joomla.request` docs if we have one, and docs for `Joomla.enqueueRequest`

bip bip @nikosdion, so it actualy possible :wink:

2022-06-28 17:25 UTC, nikosdion commented
Sorry, it was dinner time over here. Let me create a testing environment for this and I'll get back to you.

2022-06-28 17:48 UTC, nikosdion requested changes
It works well in principle. I only have some nitpicking to do about duplicated code which is easily addressed.

2022-06-28 17:48 UTC, nikosdion commented on build/media_source/system/js/core.es6.js
> +      console.error(error);
Why did you remove the check for `window.console`?

2022-06-28 17:48 UTC, nikosdion commented on build/media_source/plg_quickicon_overridecheck/js/overridecheck.es6.js
> +            update('danger', Joomla.Text._('PLG_QUICKICON_OVERRIDECHECK_ERROR'), '');
Don't duplicate code. Just throw. If the handler throws then the execution moves to the rejection handler (the catch()).

2022-06-28 17:48 UTC, nikosdion commented on build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
> +      } catch (e) {
You do not need to catch here. If the handler throws then the execution moves to the rejection handler (the catch()).

2022-06-28 17:52 UTC, Fedik commented on build/media_source/system/js/core.es6.js
> +      console.error(error);
it was some stuf for IE, do you think it make any sense currently?

2022-06-28 17:53 UTC, Fedik commented on build/media_source/plg_quickicon_overridecheck/js/overridecheck.es6.js
> +            update('danger', Joomla.Text._('PLG_QUICKICON_OVERRIDECHECK_ERROR'), '');
it was original code like that, I just moved onSuccess to .then(), and onError to .catch()
Will look, to remove

2022-06-28 17:54 UTC, Fedik commented on build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
> +      } catch (e) {
yeah, that probably original code was like that :)

2022-06-28 17:55 UTC, nikosdion commented on build/media_source/system/js/core.es6.js
> +      console.error(error);
Probably not. I couldn't find a browser which would break with console statements. I agree that since it was IE-only and IE is dead we can remove it.

2022-06-28 17:55 UTC, Fedik commented
I will fix that thing one of next days

2022-06-28 17:55 UTC, nikosdion commented on build/media_source/plg_quickicon_overridecheck/js/overridecheck.es6.js
> +            update('danger', Joomla.Text._('PLG_QUICKICON_OVERRIDECHECK_ERROR'), '');
Yeah, I know :) Now with promises we can make the code a bit more economical.

2022-06-29 08:29 UTC, Fedik commented
Should be good now

2022-07-05 15:41 UTC, martin-zw commented
I have tested this item :white_check_mark: successfully on 6613b2a40f4f1de79764696feda5f3391e4ed370<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38172">issues.joomla.org/tracker/joomla-cms/38172</a>.</sub>

2022-07-06 08:48 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 6613b2a40f4f1de79764696feda5f3391e4ed370<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38172">issues.joomla.org/tracker/joomla-cms/38172</a>.</sub>

2022-07-06 16:32 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38172">issues.joomla.org/tracker/joomla-cms/38172</a>.</sub>

2022-07-08 11:53 UTC, Fedik commented
@roland-d I have set  it RB because if we do not merge it before 4.2 release then it cannot be merged untill 5.x

2022-07-11 11:43 UTC, merged

2022-07-11 11:43 UTC, roland-d commented
Thanks everybody

2023-01-19 09:48 UTC, jobrusche commented
This is still an issue in Joomla! 4.2.6

2023-01-19 09:56 UTC, brianteeman commented
Please open a new issue with more details - few people see comments on merged pull requests. You can include a reference to this Pull Request if it is relevant in your new issue