[4.3] Use the Web Asset Manager
joomla/joomla-cms pull request #38328
Opened 2022-07-26 13:57 UTC by brianteeman

As all the htmlhelper behviors are deprecated this PR continues the work to remove their usage in core.

We should not be using deprecated code.

2022-07-26 14:16 UTC, Quy commented on administrator/components/com_redirect/layouts/toolbar/batch.php
>  use Joomla\CMS\HTML\HTMLHelper;
Please remove.

2022-10-22 09:08 UTC, HLeithner requested changes
* layouts don't have a `$app`
* tmpl files should use the local supplied `document` 
* modules are not in a `Object` scope

2022-10-22 09:08 UTC, HLeithner commented on administrator/components/com_categories/tmpl/categories/modal.php
> +$wa = $app->getDocument()->getWebAssetManager();
```suggestion
$wa = $this->document->getWebAssetManager();
```

2022-10-22 09:08 UTC, HLeithner commented on administrator/components/com_messages/tmpl/message/default.php
> +$wa = $app->getDocument()->getWebAssetManager();
```suggestion
$wa = $this->document->getWebAssetManager();
```

2022-10-22 09:08 UTC, HLeithner commented on administrator/components/com_newsfeeds/tmpl/newsfeeds/modal.php
> +$wa = $app->getDocument()->getWebAssetManager();
```suggestion
$wa = $this->document->getWebAssetManager();
```

2022-10-22 09:08 UTC, HLeithner commented on administrator/components/com_redirect/layouts/toolbar/batch.php
> +$wa = $app->getDocument()->getWebAssetManager();
```suggestion
$wa = \Joomla\CMS\Factory\Factory::getApplication()->getDocument()->getWebAssetManager();
```

2022-10-22 09:08 UTC, HLeithner commented on layouts/joomla/sidebars/submenu.php
> +$wa = $app->getDocument()->getWebAssetManager();
```suggestion
$wa = \Joomla\CMS\Factory\Factory::getApplication()->getDocument()->getWebAssetManager();
```

2022-10-22 09:08 UTC, HLeithner commented on layouts/joomla/toolbar/batch.php
> +$wa = $app->getDocument()->getWebAssetManager();
```suggestion
$wa = \Joomla\CMS\Factory\Factory::getApplication()->getDocument()->getWebAssetManager();
```

2022-10-22 09:08 UTC, HLeithner commented on modules/mod_login/tmpl/default_logout.php
> +$wa = $this->document->getWebAssetManager();
```suggestion
$wa = \Joomla\CMS\Factory\Factory::getApplication()->getDocument()->getWebAssetManager();
```

2022-10-22 11:29 UTC, brianteeman commented
@HLeithner I have merged your suggestions - thanks

I should point out that many existing modules and layouts will need correcting

2022-10-22 15:30 UTC, HLeithner commented
> @HLeithner I have merged your suggestions - thanks
> 
> I should point out that many existing modules and layouts will need correcting

possible. for layouts we should change LayoutFile object to supply $document at some point in time. It's not set yet if we like to provide $document or as meta object holding $document and maybe other object like webassetmanager directly.

but for the moment we load the document from the factory

2022-11-01 12:03 UTC, brianteeman commented
@hleithner I believe I have resolved all your requested changes. Please can you mark them as complete

2022-11-01 12:39 UTC, HLeithner approved these changes
thanks

2023-01-24 16:49 UTC, Quy commented on modules/mod_login/tmpl/default_logout.php
> +$wa = \Joomla\CMS\Factory\Factory::getApplication()->getDocument()->getWebAssetManager();
```suggestion
$wa = \Joomla\CMS\Factory::getApplication()->getDocument()->getWebAssetManager();
```

2023-01-24 16:49 UTC, Quy commented on layouts/joomla/toolbar/batch.php
> +$wa = \Joomla\CMS\Factory\Factory::getApplication()->getDocument()->getWebAssetManager();
```suggestion
$wa = \Joomla\CMS\Factory::getApplication()->getDocument()->getWebAssetManager();
```

2023-01-24 16:49 UTC, Quy commented on layouts/joomla/sidebars/submenu.php
> +$wa = \Joomla\CMS\Factory\Factory::getApplication()->getDocument()->getWebAssetManager();
```suggestion
$wa = \Joomla\CMS\Factory::getApplication()->getDocument()->getWebAssetManager();
```

2023-01-28 09:54 UTC, Fedik commented
I have tested this item :white_check_mark: successfully on ebe6f9424c5c32d89bf9238cbb74271cdfc91880<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38328">issues.joomla.org/tracker/joomla-cms/38328</a>.</sub>

2023-01-28 16:03 UTC, Quy commented
I have tested this item :white_check_mark: successfully on ebe6f9424c5c32d89bf9238cbb74271cdfc91880<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38328">issues.joomla.org/tracker/joomla-cms/38328</a>.</sub>

2023-01-28 16:04 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38328">issues.joomla.org/tracker/joomla-cms/38328</a>.</sub>

2023-01-28 20:27 UTC, merged

2023-01-28 20:27 UTC, obuisard commented
Thank you Brian @brianteeman for the cleanup!

2023-01-28 20:59 UTC, brianteeman commented
thx