[4][com_finder] error when gather statistic enabled
joomla/joomla-cms pull request #38373
Opened 2022-08-02 10:10 UTC by alikon

Pull Request for Issue #38370 .

### Summary of Changes

### Testing Instructions

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Documentation Changes Required

2022-08-02 10:23 UTC, Kostelano commented
Yes, it works for [my error](https://github.com/joomla/joomla-cms/issues/38370#issue-1325456406) too.

2022-08-02 14:54 UTC, Kostelano commented
Will the PR be marked as ready? Or are you looking for another way to solve the problem?

2022-08-02 16:51 UTC, alikon commented
i really would like to hear from the _**thumbs down superstar**_, maybe he/she/it could explain what's wrong here and maybe give us a proper fix
anyway i'm digressing
that's my quick & dirty fix,
if you don't like it @SharkyKZ please propose yours

2022-08-02 16:58 UTC, brianteeman commented
You are removing the sanitization on the query

2022-08-08 08:47 UTC, Kostelano commented
I have tested this item :white_check_mark: successfully on eb8aa81539492bdf7840b387f8ff4053fbc7184e<br /><br />I'm posting a successful test as it works. Even if at the moment there is no better solution.

This needs to be fixed, otherwise users using the "Gather Search Statistics" option will be pleasantly surprised. I don't know how a release blocker is defined, but it looks like it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38373">issues.joomla.org/tracker/joomla-cms/38373</a>.</sub>

2022-08-16 21:06 UTC, Kostelano commented
It is strange that they did not pay attention to this. In addition to @WeibelMarc's appeal, there is another one on the [Russian-language forum](https://joomlaforum.ru/index.php/topic,358468.msg1834552.html#msg1834552).

2022-08-17 12:31 UTC, roland-d requested changes

2022-08-17 12:31 UTC, roland-d commented on components/com_finder/src/Helper/FinderHelper.php
>          $temp->input = trim(strtolower($searchquery->input));
@alikon To bring sanitation back I think we can add `(string)` before the `$searchquery->input` so the line reads:

`$temp->input = trim(strtolower((string) $searchquery->input));`

2022-08-17 15:07 UTC, alikon commented on components/com_finder/src/Helper/FinderHelper.php
>          $temp->input = trim(strtolower($searchquery->input));
done

2022-08-17 16:52 UTC, Kostelano commented
I have tested this item :white_check_mark: successfully on 11fbfbd0b7c97c493cdf21b0177156cc5911d31a<br /><br />After the changes everything works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38373">issues.joomla.org/tracker/joomla-cms/38373</a>.</sub>

2022-08-17 17:39 UTC, bayareajenn commented
I have tested this item :white_check_mark: successfully on 11fbfbd0b7c97c493cdf21b0177156cc5911d31a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38373">issues.joomla.org/tracker/joomla-cms/38373</a>.</sub>

2022-08-17 17:40 UTC, roland-d approved these changes

2022-08-17 18:36 UTC, merged

2022-08-17 18:37 UTC, roland-d commented
Thanks everybody