Template Overrides message on update
joomla/joomla-cms pull request #38449
Opened 2022-08-12 16:26 UTC by brianteeman

Pull Request for Issue #35381  .

### Summary of Changes
After an update a message may be displayed indicating that there are template overrides to check. This PR adds a link to the message

![image](https://user-images.githubusercontent.com/1296369/184401824-60b103d1-fe6b-41be-89c5-6acd1f18e179.png)

2022-08-12 16:53 UTC, Kostelano commented on administrator/language/en-GB/plg_installer_override.ini
> +PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED_1="A file that you have an override for in your template has been updated and you should %s review those changes."
```suggestion
PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED="%1$s files that you have an override for in your template have been updated and you should <a href=\"%2$s\">review those changes</a>."
PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED_1="A file that you have an override for in your template has been updated and you should <a href=\"%2$s\">review those changes</a>."
```

For situations where we have changed 1, 11, 21, etc. file, this cannot work, because you are passing 1 variable in the line - this is the number of files.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/184406493-b86c31cf-5978-410e-a9b9-cffdc1977fbc.png)

We have to use `%1$s` and `%2$s` here.

In addition, the localization string is malformed, the link tags are needed.

After the changes everything is ok:

![Screenshot_2](https://user-images.githubusercontent.com/8440661/184406612-97e4a8c6-30c3-4967-a81c-428a78a3e13a.png)

2022-08-13 08:57 UTC, Kostelano commented
I have tested this item :white_check_mark: successfully on 0605649dca4f2c7a9a8cf4b9edc4f90d01c376d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38449">issues.joomla.org/tracker/joomla-cms/38449</a>.</sub>

2022-08-13 21:23 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 0605649dca4f2c7a9a8cf4b9edc4f90d01c376d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38449">issues.joomla.org/tracker/joomla-cms/38449</a>.</sub>

2022-08-13 22:46 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38449">issues.joomla.org/tracker/joomla-cms/38449</a>.</sub>

2022-08-18 17:12 UTC, heelc29 requested changes

2022-08-18 17:12 UTC, heelc29 commented on administrator/language/en-GB/plg_installer_override.ini
> +
Is there a reason for the blank line?
```suggestion
```

2022-08-18 17:15 UTC, brianteeman commented on administrator/language/en-GB/plg_installer_override.ini
> +
No none at all - suprised no one noticed it before

2022-08-31 22:11 UTC, merged

2022-08-31 22:11 UTC, roland-d commented
Thank you

2022-08-31 22:12 UTC, brianteeman commented
thanks