Template Override Actions
joomla/joomla-cms pull request #38447
Opened 2022-08-12 16:01 UTC by brianteeman

There was a button to remove a record but not to mark it as checked or unchecked. You had to do each one individually by clicking on the icon. 

This PR lets you select as many records as you want and then use the button to change all the selected records. This is based on user feedback who complained that there was no way to bulk mark records.

## Before

https://user-images.githubusercontent.com/1296369/184396145-d0ba2493-44c8-4842-9d04-aa709dd046cc.mp4

## After

https://user-images.githubusercontent.com/1296369/184395914-92c4d4e0-f55d-4dca-b165-3c2b398cc64d.mp4

2022-08-12 16:26 UTC, Kostelano commented
I have tested this item :white_check_mark: successfully on 0af4b6513c2a8fe91cef3527af1532e7e9507237<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38447">issues.joomla.org/tracker/joomla-cms/38447</a>.</sub>

2022-08-12 16:43 UTC, brianteeman commented
If someone could help with the drone error I would aappreciate it as I dont understand it.

2022-08-12 18:07 UTC, richard67 commented
> If someone could help with the drone error I would aappreciate it as I dont understand it.

@brianteeman The file contains a class definition and also executed code outside the class here: https://github.com/joomla/joomla-cms/blob/a2860fe076d0dae02bae4aa89996b83605c8e5e1/administrator/components/com_templates/src/View/Template/HtmlView.php#L26 . Could you move that code to somewhere inside the class?

2022-08-13 18:58 UTC, Kostelano commented
I have tested this item :white_check_mark: successfully on 2b6b9f0b2f0da49e2426ed8d77f613545e7668d4<br /><br />Probably needs a retest.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38447">issues.joomla.org/tracker/joomla-cms/38447</a>.</sub>

2022-08-14 07:25 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 2b6b9f0b2f0da49e2426ed8d77f613545e7668d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38447">issues.joomla.org/tracker/joomla-cms/38447</a>.</sub>

2022-08-14 08:24 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38447">issues.joomla.org/tracker/joomla-cms/38447</a>.</sub>

2022-08-18 17:09 UTC, heelc29 requested changes

2022-08-18 17:09 UTC, heelc29 commented on administrator/components/com_templates/src/View/Template/HtmlView.php
> +            ->listCheck(true);
The indentation should be increased here?
```suggestion
            $dropdown = $bar->dropdownButton('override-group')
                ->text('COM_TEMPLATES_BUTTON_CHECK')
                ->toggleSplit(false)
                ->icon('icon-ellipsis-h')
                ->buttonClass('btn btn-action')
                ->form('updateForm')
                ->listCheck(true);
```

2022-08-31 22:15 UTC, roland-d commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_N_OVERRIDE_UNCHECKED="%d records unchecked."
Should this say `%d records marked as unchecked`? To be in line with the text used to mark a record or you cannot unmark something :thinking:

2022-08-31 22:16 UTC, roland-d commented on administrator/components/com_templates/src/View/Template/HtmlView.php
> +            ->listCheck(true);
I think the calls should be indented like the rest as seen below.

2022-08-31 22:17 UTC, brianteeman commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_N_OVERRIDE_UNCHECKED="%d records unchecked."
its fine as it is

2022-08-31 22:17 UTC, brianteeman commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_N_OVERRIDE_UNCHECKED="%d records unchecked."
oh wait - sorry I see what you mean

2022-08-31 22:19 UTC, brianteeman commented on administrator/language/en-GB/com_templates.ini
> +COM_TEMPLATES_N_OVERRIDE_UNCHECKED="%d records unchecked."
i've changed the other one. "marked" is a redundant word here.

2022-08-31 22:20 UTC, brianteeman commented on administrator/components/com_templates/src/View/Template/HtmlView.php
> +            ->listCheck(true);
have merged the change but again the automated codestyle checker should have picked this up.

2022-08-31 22:22 UTC, merged

2022-08-31 22:22 UTC, roland-d commented
Thank you

2022-09-01 07:28 UTC, brianteeman commented
thanks