[4.2] Do not set a width of 0 in media thumbnails
joomla/joomla-cms pull request #38535
Opened 2022-08-19 13:36 UTC by laoneo

### Summary of Changes
Since #36930 the thumbnail image of a media item is an image HTML element. When the width and height are 0, then the image is rendered with 0 width/height and invisible. Instead of the attributes should be ignored. This pr adds no attribute when width and height are not available and sets loading not to lazy.

### Testing Instructions
- Remove the lines 342 and 343 in plugins/filesystem/local/src/Adapter/LocalAdapter.php
- Open the media manager in the back end

### Actual result BEFORE applying this Pull Request
No preview image is shown.

### Expected result AFTER applying this Pull Request
A preview image is shown with no width/height/loading attribute.

2022-08-19 14:22 UTC, dgrammatiko requested changes

2022-08-19 14:22 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/items/image.vue
> +          :loading="loading"
```suggestion
          :loading="eager"
```

the loading attribute could be either `eager ` or `lazy`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading

2022-08-20 21:54 UTC, brianteeman commented
After rebuilding the media manager I can confirm this works

BUT - in what scenario would the image ever have a height/width of 0?

2022-08-21 05:37 UTC, laoneo commented
When you fetch data from an external service like FTP, then there is no image information. Since 4.1 a width/height attribute is required as int value, the adapter has to return at least 0. You can try it with the [free version of DPMedia](https://joomla.digital-peak.com/download/dpmedia/dpmedia-1.5.0) and the FTP adapter.

2022-08-21 06:07 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 4c87bcb9e05f18e88d0b4a927e2c0720b46a439d<br /><br />Thanks for explaining the use case<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38535">issues.joomla.org/tracker/joomla-cms/38535</a>.</sub>

2022-08-21 09:29 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 4c87bcb9e05f18e88d0b4a927e2c0720b46a439d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38535">issues.joomla.org/tracker/joomla-cms/38535</a>.</sub>

2022-08-21 10:53 UTC, richard67 commented on administrator/components/com_media/resources/scripts/components/browser/items/image.vue
> +      return this.item.width > 0 ? 'lazy' : null;
Would it make sense here to check also for the height, so both height and width need to be greater than zero for setting the lazy attribute?

2022-08-21 10:55 UTC, richard67 commented on administrator/components/com_media/resources/scripts/components/browser/items/image.vue
> +      return this.item.width > 0 ? 'lazy' : null;
That’s just a question, not a suggestion.

2022-08-21 10:57 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38535">issues.joomla.org/tracker/joomla-cms/38535</a>.</sub>

2022-08-22 06:15 UTC, laoneo commented on administrator/components/com_media/resources/scripts/components/browser/items/image.vue
> +      return this.item.width > 0 ? 'lazy' : null;
This would probably be very rare cases. We can do that in a followup pr, for me it is important to have this one merged as quick as possible as it is urgent.

2022-09-02 19:14 UTC, merged

2022-09-02 19:14 UTC, roland-d commented
Thank you