Use ellipsis - part 1
joomla/joomla-cms pull request #38638
Opened 2022-08-30 08:20 UTC by brianteeman

Following the style guide and accessibility recommendations this PR changes the use of ... (dot dot dot) to the html entity for an ellipsis.

For example some screenreaders will announce the three dots eg read more dot dot dot but with an ellipsis they pause and do not say dot dot dot

This PR is only for the language strings. A further PR will follow to address truncation

PARTIAL Pull Request for Issue #38630

2022-08-30 08:23 UTC, tecpromotion commented on administrator/language/en-GB/joomla.ini
> +JGLOBAL_SHOW_READMORE_DESC="If set to Show, the Read more &hellip;Link will show if Main text has been provided for the Article."
```suggestion
JGLOBAL_SHOW_READMORE_DESC="If set to Show, the Read more &hellip; Link will show if Main text has been provided for the Article."
```

2022-08-30 08:24 UTC, tecpromotion commented on api/language/en-GB/joomla.ini
> +JGLOBAL_SHOW_READMORE_DESC="If set to Show, the Read more &hellip;Link will show if Main text has been provided for the Article."
```suggestion
JGLOBAL_SHOW_READMORE_DESC="If set to Show, the Read more &hellip; link will show if Main text has been provided for the Article."
```

2022-08-30 08:25 UTC, tecpromotion requested changes
Maybe this should be separated. Already hyphenated and lowercase elsewhere.

2022-08-30 08:28 UTC, brianteeman commented on administrator/language/en-GB/joomla.ini
> +JGLOBAL_SHOW_READMORE_DESC="If set to Show, the Read more &hellip;Link will show if Main text has been provided for the Article."
good spot they should never have been capitalised

2022-08-30 08:29 UTC, brianteeman commented
> Maybe this should be separated. Already hyphenated and lowercase elsewhere.

Sorry I dont understand what you are saying - maybe I need more coffee

2022-08-30 19:37 UTC, tecpromotion approved these changes
Thanks @brianteeman

2022-08-30 19:37 UTC, tecpromotion commented
I have tested this item :white_check_mark: successfully on 56ac93c9a7f00fd5d2e6e20fb4e6c5d734ca0dae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38638">issues.joomla.org/tracker/joomla-cms/38638</a>.</sub>

2022-08-30 20:05 UTC, N6REJ commented
@brianteeman docs will need to be updated as it specifically states "three periods"

2022-08-30 20:11 UTC, brianteeman commented
Where? Search didn't find any. https://docs.joomla.org/index.php?title=Special:Search&profile=default&search=%22three%20periods%22&fulltext=1

2022-08-30 21:24 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 56ac93c9a7f00fd5d2e6e20fb4e6c5d734ca0dae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38638">issues.joomla.org/tracker/joomla-cms/38638</a>.</sub>

2022-08-30 21:25 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38638">issues.joomla.org/tracker/joomla-cms/38638</a>.</sub>

2022-08-30 21:25 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38638">issues.joomla.org/tracker/joomla-cms/38638</a>.</sub>

2022-08-31 02:15 UTC, N6REJ commented
@brianteeman https://developer.joomla.org/en-gb-user-interface-text-guidelines/punctuation.html
```
An ellipsis is a set of three periods ( ... ) indicating an omission. The group of periods should have a single space on either side. Unless it is at the end of a string where there is no space or period after.
Example

Read more ...
Create some text ... add some pictures.
```
Notice it says "three periods"

2022-08-31 07:10 UTC, brianteeman commented
@N6REJ thanks - the docs have been updated just waiting for a merge

2022-08-31 20:34 UTC, merged

2022-08-31 20:34 UTC, roland-d commented
Thank you

2022-08-31 20:47 UTC, brianteeman commented
thanks

2022-09-06 20:53 UTC, Razzo1987 commented
Also in [COM_MEDIA_SEARCH ](https://github.com/joomla/joomla-cms/blob/835d9860c55a84b0275927b520ac0f604e4b92d1/language/en-GB/com_media.ini#L101)

2022-09-06 21:07 UTC, brianteeman commented
@Razzo1987 thanks - see #38710

2022-09-07 06:13 UTC, HLeithner commented
Whats the reason why you use the html encoding & hellip ; instead of the utf8 character … ?

2022-09-07 06:46 UTC, brianteeman commented
Clarity.

2022-09-07 07:56 UTC, HLeithner commented
can we please change this because this would not work in cli script or non-browser context, afaik is that we try to avoid html encoding in language files and use utf8 directly (it's done for easy writing)

2022-09-07 08:06 UTC, brianteeman commented
No I will not change it and we have plenty of html in our strings. 

&hellip is easier to type and visually an editor will not mistakenly type ... when they mean …

As already explained we must use an ellipsis for accessibility and changing to use the utf8 … from the ... will not help as translators etc will not SEE that they are different and will continue to type ... especially as its much easier to type ... than it is to look up the utf8 character. It's certainly easier for me to type &hellip than it is to open a character map and locate the utf8 map and then locate the ellipsis and insert it into a document

2022-09-07 08:15 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/188826821-3330db6e-7d4b-4846-8737-b157263a3729.png)

which of those is the real ellipsis

2022-09-07 09:18 UTC, HLeithner commented
That one which also works outside of a webbrowser.

2022-09-07 09:19 UTC, HLeithner commented
OK so the Unicode consortium are all idiots and we should go back to ascii and HTML encoding. Makes sense to me.

2022-09-07 09:25 UTC, HLeithner commented
forget the "idiots", I already argument like other people in this tracker and that makes it sick. People are doing anyway what they want to do so I should not take this personally and look at my health.

2022-09-07 09:30 UTC, brianteeman commented
I know many of the unicode consortium, spoken at their conference twice, nice people. However, unfortunately, much of their work is not accessible at all or more accurately is misused and is therefore not accessible.

2022-09-07 09:59 UTC, brianteeman commented
No one was forced to merge this

2022-09-08 03:30 UTC, N6REJ commented
is it possible to add the &hellip; to tiny as I'm darn sure never going to remember that and I use ... almost hourly

2022-09-08 06:30 UTC, brianteeman commented
What does that have to do with changing language strings?