[4.3] NPM build tools cleanup/Perf fixes
joomla/joomla-cms pull request #38663
Opened 2022-09-01 10:12 UTC by dgrammatiko

Pull Request for Issue # .

### Summary of Changes
- remove some I/O operations on both the JS and SCSS minification (eg use the code output directly)
- Switch for Sass to Sass-embedded

About SASS-EMBEDDED: This package is an alternative to the [sass](https://www.npmjs.com/package/sass) package. It supports the same JS API as sass and is maintained by the same team, but where the sass package is pure JavaScript, sass-embedded is instead a JavaScript wrapper around a native Dart executable. This means sass-embedded will generally be much faster especially for large Sass compilations, but it can only be installed on the platforms that Dart supports: Windows, Mac OS, and Linux. [npmjs](https://www.npmjs.com/package/sass-embedded)

### Testing Instructions
On a fresh installation of Joomla (ie `git clone`) do the composer install and then the npm install. Copy the media folder somewhere in your hardisk. (check the time needed)
Now clone this PR and do both the composer and npm installations. Once done do a folder compare of the current media folder against the folder that you saved in the previous step. You should have the same files. Check the template.css for both the core templates to ensure that the file contents are the same.

Compare the times and do a brief check that both front end and back still work as expected

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request
It should a bit faster due to less I/O operations and the sass-embedded is the recommended compiler for speed

### Documentation Changes Required

NO

This PR replaces #38225 and https://github.com/joomla/joomla-cms/pull/36919

Note to anyone that will merge this: you probably need at least a successful test both from windows and macOS env (assuming that the linux env from the automated tests can be accepted as one for the Linuxes)

@HLeithner have this merged before trying out more exotic solutions

2022-09-01 14:10 UTC, richard67 commented
@dgrammatiko The JS linter complains: https://ci.joomla.org/joomla/joomla-cms/57462/1/26

2022-09-02 13:48 UTC, Hackwar requested changes
Thank you for this improvement. The speedup looks pretty good and definitely not insignificant. I'd like us to soon implement a cache for the different files as well, but that is another step. Please have a look at the other comments.

2022-09-02 13:48 UTC, Hackwar commented on .drone.yml
> +    image: node:18-bullseye-slim
I understand the intention, but generally we would want to run our builds with our minimum requirements. That hopefully shows us when something doesn't work in our minimum version. I understand that we want to use the newer version with more performance improvements, but unless the project decides otherwise, we should stick to that.

That said, there are arguments for raising these min requirements in even a patch version for in this case dev tools like this. If you really want to have this on version 18, let us please discuss this in the production team. In any case, this version should be equal to the min version in the package.json. So we should change it there as well if we change it here.

2022-09-02 13:48 UTC, Hackwar commented on package.json
> +    "sass-embedded": "1.54.4",
I know why you are doing this, but right now we've set renovatebot to only update the lock file and not to update the version in the package.json or to fix the version in there. So please allow this to be updated in the lock file based on semver.

2022-09-02 13:58 UTC, dgrammatiko commented on package.json
> +    "sass-embedded": "1.54.4",
I've written before that the only source of truth should be package.json. The lock file is there only to cache the resolution of the internal dependencies of each package. Also keep in mind that the actual build tools **use** the version for multiple processes:
- code mirror XML update
- tinyMCE XML update
- append the version for each package in the asset.joomla.json

This process already failed multiple time, the last one https://github.com/joomla/joomla-cms/pull/38614

So, all it takes is to ask renovate to PIN the dependencies and then let it manage them according to your rules. It's the same result but the source of truth will be the package.json and would be immediately obvious which version is used per package.

2022-09-02 14:00 UTC, dgrammatiko commented on .drone.yml
> +    image: node:18-bullseye-slim
Fair enough, changed

2022-09-02 14:02 UTC, dgrammatiko commented on package.json
> +    "sass-embedded": "1.54.4",
Changed but would be nice to reconsider your approach and pin the dependencies so it's more obvious...

2022-09-03 08:14 UTC, Hackwar commented on package.json
> +    "sass-embedded": "1.54.4",
Ok, I'll look into this further and see if we change this. So far I only implemented the behavior we had so far. Depending on how renovatebot behaves, it might be worth to change that.

2022-09-03 14:33 UTC, dgrammatiko commented on package.json
> +    "sass-embedded": "1.54.4",
Fwiw my blog has pinned dependencies and renovate works like a charm. Here is the PR from the bot to pin the devs: https://github.com/dgrammatiko/site/pull/2  I think that if you just remove the `:preserveSemverRanges` from the renovate config the bot will automatically pin the dependencies.
My point is that it **should** be obvious what version of each of the dependencies is used. right now someone needs to dig in the lock file (if they even know that it's the file that holds the actual version number) and worst than that a release could have an untested version because the at packaging of the CMS the range allows to use a newer version. The last one is really bad, especially if you consider that it would go unnoticed as there's no feedback on the process...

2022-10-19 10:02 UTC, dgrammatiko commented
@HLeithner @Hackwar is there any interest for this one or should I close it?

2022-10-19 11:07 UTC, Hackwar commented
Yes, there is interest. However I think we wont apply this to 4.2, so I would ask you to rebase this to 4.3-dev and update this branch to the latest changes from that base branch. I hope that we can merge this over this weekend.

2022-10-19 11:09 UTC, Hackwar commented
I changed the base branch. Please resolve the conflicts and update the branch to the latest changes.

2022-10-19 14:46 UTC, dgrammatiko commented
@Hackwar done, could someone bless drone here?

2022-10-20 14:34 UTC, Hackwar commented
I send you a PR to sign the drone.yml file

2022-10-20 14:34 UTC, Hackwar approved these changes

2022-10-21 08:46 UTC, merged

2022-10-21 08:46 UTC, HLeithner commented
thanks

2022-10-21 08:47 UTC, Hackwar commented
🎉