[J4] New module - Category Tags
joomla/joomla-cms pull request #38741
Opened 2022-09-12 09:21 UTC by korenevskiy

### Actual result BEFORE applying this Pull Request
Previously, the display was very restrictive. Tag links opened the tag component. But the problem is that the Tag Component does not have a mode for displaying articles as a blog. At the same time, the display of the list of materials of one tag must be made additional layout.

### Expected result AFTER applying this Pull Request
The new module allows you to display tags in the form of a tree, This will allow you to use tags to display as a catalog of categories. Every developer faces a problem when an article needs to be placed in 2(3) different categories at once. For example, an article can simultaneously contain future news, as well as an article can contain information about the PHP language, as well as contain information about gifts. By opening the module tag link, a list of blog materials will be displayed.

While deleting the material tag, the material link remains the same. But if we moved an article from one category to another, the article link would change. Now the article link will remain the same, and tags can be used instead of categories.

2022-09-12 09:31 UTC, brianteeman commented
you dont need to include the russian language files

2022-09-12 09:32 UTC, brianteeman commented
and is the file translate.php part of this module?

2022-09-12 10:21 UTC, korenevskiy commented
> and is the file translate.php part of this module?

No, but this file serves as a translation for testing. I would prefer to delete it after finding the errors.

2022-09-12 16:32 UTC, korenevskiy commented
Please help. Save me. I am correcting errors, but the validator shows imaginary errors. I have already deleted spaces and hyphenations, and then did it again, but errors remain. 
### Help me fix the errors!!!!!

2022-09-12 16:45 UTC, alikon commented
if you look at https://ci.joomla.org/joomla/joomla-cms/57815/1/6 there is a detailed report on what drone complain about CS
![image](https://user-images.githubusercontent.com/181681/189709975-dee7912b-214c-4cfb-a736-a6fc5329a990.png)

hope that helps

imho shouldn't be a core but a 3dp module

2022-09-12 16:57 UTC, korenevskiy commented
@alikon  
Yes, I have been looking into this report from the very beginning. I have already removed 80% of the errors. 
But I can't fix the remaining errors. You will see for yourself the code and the error in the report. I do not understand that there is an error in an empty place. 
After that, I correct the errors as indicated in the report, and in the new report the requirement to remove the added space back. Ie, first the report asks to add a space, and in the next report asks to remove the space back. 

Maybe I don't understand something?

2022-09-12 17:06 UTC, brianteeman commented
I would suggest not to worry for now about code style and first to get people to check what the module does and if it is something for core. _(there are lots of other style issues that drone didnt find)_

2022-09-12 17:09 UTC, alikon commented
joomla recently switched from own cosdestyle to PSR-12 https://www.php-fig.org/psr/psr-12/
so maybe this is the main source of confusion
i've made a silly pr to your branch  to fix  only the 1st drone report 
check it maybe it will let you to reduce the cs complains

2022-09-12 19:19 UTC, korenevskiy commented
> so maybe this is the main source of confusion

@alikon 
You're right, the problem was in the curly brace after the condition. But in the error report, it is NOT stated that the problem is curly brace. The report just says about the brace. And since the curly brace is on another line, that implies a parenthesis, as well as the error is indicated in the absence of a space. The error in the report does not indicate the cause of the error at all.

**Thank you for your help, now I will know about the new code format.**

2022-09-12 19:50 UTC, korenevskiy commented
`modules/mod_category_tags/tmpl/_childs.php (line 1)`
@alikon 
I have fixed all the errors, there is one more error that I cannot remove. Please help me fix it. The parser swears that the line break "\r\n" is used instead of "\n". No matter how much I would try to fix the transfer, the error remains in the code.

2022-09-12 20:17 UTC, richard67 commented
@korenevskiy Regarding naming of files and variables: The plural of "child" in English language is "children", not "childs".

2022-09-12 20:19 UTC, richard67 commented
> `modules/mod_category_tags/tmpl/_childs.php (line 1)` @alikon I have fixed all the errors, there is one more error that I cannot remove. Please help me fix it. The parser swears that the line break "\r\n" is used instead of "\n". No matter how much I would try to fix the transfer, the error remains in the code.

@korenevskiy You could use a good editor like notepad++ which can show you what kind of line feeds are in the file (Unix like it should be, or Windows like the PHP CS check complains about).

2022-09-13 11:34 UTC, Kostelano requested changes

2022-09-13 11:34 UTC, Kostelano commented on modules/mod_category_tags/mod_category_tags.php
> + * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-09-13 11:34 UTC, Kostelano commented on modules/mod_category_tags/mod_category_tags.xml
> +	<version>4.0.0</version>
```suggestion
	<creationDate>2022-09</creationDate>
	<copyright>(C) 2022 Open Source Matters, Inc.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<authorEmail>admin@joomla.org</authorEmail>
	<authorUrl>www.joomla.org</authorUrl>
	<version>__DEPLOY_VERSION__</version>
```

2022-09-13 11:34 UTC, Kostelano commented on language/en-GB/mod_category_tags.ini
> +MOD_CATEGORY_TAGS_FIELD_DISPLAY_TREE_LABEL ="Show tree"
```suggestion
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_CATEGORY_TAGS="Category - Tags"
MOD_CATEGORY_TAGS_FIELD_ALL_TIME="All time"
MOD_CATEGORY_TAGS_FIELD_DISPLAY_COUNT_LABEL="Display Number of Items"
MOD_CATEGORY_TAGS_FIELD_LAST_DAY="Last day"
MOD_CATEGORY_TAGS_FIELD_LAST_HOUR="Last hour"
MOD_CATEGORY_TAGS_FIELD_LAST_MONTH="Last month"
MOD_CATEGORY_TAGS_FIELD_LAST_WEEK="Last week"
MOD_CATEGORY_TAGS_FIELD_LAST_YEAR="Last year"
MOD_CATEGORY_TAGS_FIELD_MAXSIZE_DESC="The maximum font size used for the tags, proportional to the site's default font size (eg \"2\" means 200% of the default size)."
MOD_CATEGORY_TAGS_FIELD_MAXSIZE_LABEL="Maximum Font Size"
MOD_CATEGORY_TAGS_FIELD_MINSIZE_DESC="The minimum font size used for the tags, proportional to the site's default font size (eg \"2\" means 200% of the default size)."
MOD_CATEGORY_TAGS_FIELD_MINSIZE_LABEL="Minimum Font Size"
MOD_CATEGORY_TAGS_FIELD_NO_RESULTS_LABEL="Show \"No results\" text"
MOD_CATEGORY_TAGS_FIELD_NO_RESULTS_TEXT="No results message"
MOD_CATEGORY_TAGS_NO_ITEMS_FOUND="No Tags found."
MOD_CATEGORY_TAGS_FIELD_ORDER_VALUE_COUNT="Number of Items"
MOD_CATEGORY_TAGS_FIELD_ORDER_VALUE_LABEL="Order"
MOD_CATEGORY_TAGS_FIELD_ORDER_VALUE_RANDOM="Random"
MOD_CATEGORY_TAGS_FIELD_ORDER_VALUE_TITLE="Title"
MOD_CATEGORY_TAGS_FIELD_TIMEFRAME_LABEL="Time Period"
MOD_CATEGORY_TAGS_FIELD_DISPLAY_TREE_LABEL="Show tree"
```

2022-09-13 11:34 UTC, Kostelano commented on language/en-GB/mod_category_tags.sys.ini
> +MOD_CATEGORY_TAGS="Category - tags"
```suggestion
; (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_CATEGORY_TAGS="Category - Tags"
```

2022-09-13 11:34 UTC, Kostelano commented on modules/mod_category_tags/src/Helper/CategoryTagsHelper.php
> + * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-09-13 11:34 UTC, Kostelano commented on modules/mod_category_tags/tmpl/_childs.php
> + * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>

```

2022-09-13 11:34 UTC, Kostelano commented on modules/mod_category_tags/tmpl/cloud.php
> + * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-09-13 11:34 UTC, Kostelano commented on modules/mod_category_tags/tmpl/default.php
> + * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
```

2022-09-13 11:36 UTC, Kostelano commented on modules/mod_category_tags/language/en-GB/mod_category_tags.ini
> +; Joomla! Project
This file and the "language" directory must be deleted, no localization files are stored in the modules directory.

2022-09-13 12:27 UTC, korenevskiy commented on modules/mod_category_tags/mod_category_tags.xml
> +	<version>4.0.0</version>
Why do we need to write the date not in SQL format?

2022-09-13 13:11 UTC, Kostelano commented on modules/mod_category_tags/mod_category_tags.xml
> +	<version>4.0.0</version>
[Joomla recently switched to this date format](https://github.com/joomla/joomla-cms/pull/27162). You can check in any module.

2022-09-13 13:16 UTC, brianteeman commented on modules/mod_category_tags/mod_category_tags.xml
> +				>
Please fix the indentation here and in all similar areas.

2022-09-13 13:17 UTC, brianteeman commented on modules/mod_category_tags/mod_category_tags.xml
> +					type="translate"/>
???

2022-09-13 13:18 UTC, brianteeman commented on modules/mod_category_tags/mod_category_tags.xml
> +					label="MOD_CATEGORY_TAGS_FIELD_DISPLAY_TREE_LABEL"
name
type
label
layout

please fix this ordering here and in all similar areas

2022-09-13 13:19 UTC, brianteeman commented on modules/mod_category_tags/mod_category_tags.xml
> +					filter="integer"
filter="boolean"

2022-09-13 13:20 UTC, Kostelano commented
By the way, replace the branch with 4.3.

2022-09-13 18:23 UTC, korenevskiy commented on modules/mod_category_tags/mod_category_tags.xml
> +	<version>4.0.0</version>
> [Joomla recently switched to this date format](https://github.com/joomla/joomla-cms/pull/27162). You can check in any module.

This is a big mistake of all modules. An XML file is a data file just like SQL is designed for data. The XML file is not a text document. We store data in SQL in ISO format. Maybe we will store data in SQL in the "Mov 2022" format?

2022-09-13 18:36 UTC, Kostelano commented on modules/mod_category_tags/mod_category_tags.xml
> +	<version>4.0.0</version>
I proposed a correction based on the previously adopted PR (for compliance). But most likely you are right and this is a mistake. There is already at least an https://github.com/joomla/joomla-cms/issues/38552 on this topic.

2022-09-13 18:39 UTC, Kostelano commented on modules/mod_category_tags/mod_category_tags.xml
> +	<version>4.0.0</version>
I have edited the change request. The date will need to be discussed with the release leaders.

2022-09-13 19:25 UTC, korenevskiy commented
Dear colleagues. I have created a new PR for branch 4.3. I am not able to transfer PR to a new branch. I decided to create anew. Here's a new PR https://github.com/joomla/joomla-cms/pull/38752

@brianteeman , @Kostelano  , @chmst  , @alikon  ,  @richard67  , @laoneo  , @rdeutz  , @Hackwar  , @wilsonge  , @zero-24  , @bembelimen , @joomdonation  , @obuisard  , @HLeithner  , @heelc29  , @sonvnn @webuniverse

2022-09-13 19:28 UTC, closed without merging

2022-09-13 19:29 UTC, korenevskiy commented on modules/mod_category_tags/mod_category_tags.xml
> +					filter="integer"
in new PR changed

2022-09-13 19:29 UTC, korenevskiy commented on modules/mod_category_tags/mod_category_tags.xml
> +					label="MOD_CATEGORY_TAGS_FIELD_DISPLAY_TREE_LABEL"
in new PR changed

2022-09-13 19:45 UTC, korenevskiy commented on modules/mod_category_tags/mod_category_tags.xml
> +	<version>4.0.0</version>
> There is already at least an #38552 on this topic.

Thank you, I indicated there in the message that XML is a data format.