[4.3] Local adapter thumbnails (PR 36552 clone)
joomla/joomla-cms pull request #38805
Opened 2022-09-22 00:47 UTC by obuisard

This is a clone of #36552 adapted for 4.3: 
Generate thumbs for the Media manager.

2022-09-24 16:43 UTC, obuisard commented
tests/Codeception/api/com_media/MediaCest.php needs to be updated and fails at this point.

2022-10-11 16:03 UTC, dgrammatiko commented
Hey, @obuisard I can't reply on #38722 as Nik has blocked me so I'll write my comment here:
- when I asked you to resurrect this PR I meant to fork it and patch the things that other were asking me to change in the original PR and also fix the failing tests
- - https://github.com/joomla/joomla-cms/pull/36552#pullrequestreview-854742766
- - https://github.com/joomla/joomla-cms/pull/36552#pullrequestreview-854741791
- - https://github.com/joomla/joomla-cms/pull/36552#discussion_r786233867
- About the other PR: the approach on that PR is wrong in the sense that you need a data structure that holds all related info per supported media file (mime type, has preview, allows edit, etc). If the project ends up with different inputs for each of all these *required* data you end up with countless inputs which makes the app really hard to configure and finally use it to its full extend. Mind that since Media manager supports audio and video and other types at some point you might want to provide edit for those (I had a trim plugin for audio and video). Also one more thing: uploads should only allowed if there is a known and matching mime type, the idea that in 2022 people rely on extensions for uploads is a huge security problem. A simple composer require is all it takes: https://packagist.org/packages/league/mime-type-detection to start making things right...

2022-10-11 16:38 UTC, obuisard commented
Thank you Dimitris @dgrammatiko. I did address the first review, fixed formatting and tested the code successfully. 

As far as the tests are concerned, a solution would be to remove testUpdateFileWithoutAdapter all together, but I would appreciate someone's expertise on this.

2022-10-11 17:44 UTC, dgrammatiko commented
> a solution would be to remove testUpdateFileWithoutAdapter all together,

@laoneo could you advise here?

2022-10-17 19:37 UTC, laoneo commented
Removing the test is a bad idea. Better to set the default to 0, so no thumbs will be generated and the admin has to activate it. If it is on by default, then after the update all thumbnails are generated without notice, which can lead to resource issues on large sites.

2022-10-26 21:26 UTC, obuisard commented
I have modified the code to make the thumbnail creation 0 by default. It does solve issues with tests. Thank you @laoneo for the suggestion.

2022-11-08 05:43 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on 53bc63a377dfc6b2bb4ddcb040ac284aa49c6e07<br /><br />Everything looks good after applying the PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38805">issues.joomla.org/tracker/joomla-cms/38805</a>.</sub>

2022-11-08 06:17 UTC, N6REJ commented
I have tested this item :white_check_mark: successfully on 53bc63a377dfc6b2bb4ddcb040ac284aa49c6e07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38805">issues.joomla.org/tracker/joomla-cms/38805</a>.</sub>

2022-11-08 06:18 UTC, N6REJ commented
RTC

2022-11-08 16:03 UTC, obuisard commented
First comment on this PR was edited by the bot, removing information.
Thank you to @dgrammatiko for this work, it's a big step into improving the performance of the media manager.
For information, turning on thumbnails can be found in the Filesystem 'Local' plugin.

![image](https://user-images.githubusercontent.com/5964177/200614905-41144849-e8e2-45d9-b950-3df0a9747f17.png)

2022-11-10 08:48 UTC, laoneo commented on libraries/src/Image/Image.php
> +    public function createThumbs($thumbSizes, $creationMethod = self::SCALE_INSIDE, $thumbsFolder = null)
I forgot, here you need to add a deprecated statement and make a pr for the manual.

2022-11-10 08:48 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +    public function delete(string $path): void
```suggestion
    public function delete(string $path)
```
Just to be on the safe side, when somebody extends the LocalAdapter delete function.

2022-11-10 08:48 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +    private function getLocalThumbPaths(string $path): array
Can this be renamed to `getLocalThumbnailPaths` so it is better understandable and more inline with the change in the image class?

2022-11-10 08:48 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +    private function getThumb(string $path): string
Can this be renamed to `getThumbnail` so it is better understandable and more inline with the change in the image class?

2022-11-10 08:48 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +    private function createThumb(string $path, string $thumbPath): bool
Can this be renamed to `createThumbnail` so it is better understandable and more inline with the change in the image class?

2022-11-10 08:48 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +    private $thumbs = false;
Can this be renamed to `thumbnails` so it is better understandable and more inline with the change in the image class?

2022-11-10 08:48 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +    private $thumbSize = [200, 200];
Can this be renamed to `thumbnailSize` so it is better understandable and more inline with the change in the image class?

2022-11-10 08:49 UTC, laoneo commented on administrator/language/en-GB/plg_filesystem_local.ini
> +PLG_FILESYSTEM_LOCAL_DIRECTORIES_DIRECTORY_THUMBS_LABEL="Create thumbnails"
Must here no every word start with upper case? And please write here also PLG_FILESYSTEM_LOCAL_DIRECTORIES_DIRECTORY_THUMBNAILS_LABEL.

2022-11-10 17:45 UTC, obuisard commented on administrator/language/en-GB/plg_filesystem_local.ini
> +PLG_FILESYSTEM_LOCAL_DIRECTORIES_DIRECTORY_THUMBS_LABEL="Create thumbnails"
Agree

2022-11-10 18:35 UTC, dgrammatiko requested changes

2022-11-10 18:35 UTC, dgrammatiko commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +     * - thumbnail_path     The thumbnail path of file, when available
You CANNOT do that without breaking B/C: The `thumb_path` is used here: https://github.com/joomla/joomla-cms/blob/9cbe6cb5b204705a2a66b7b774160d78eb783a01/build/media_source/system/js/fields/joomla-media-select.w-c.es6.js#L132

2022-11-10 18:36 UTC, richard67 commented
Back to pending because changes were made and more changes were requested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38805">issues.joomla.org/tracker/joomla-cms/38805</a>.</sub>

2022-11-10 18:36 UTC, dgrammatiko commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +                $obj->thumbnail_path = $this->thumbnails ? $this->getThumbnail($path) : $this->getUrl($obj->path);
Same here

2022-11-10 18:38 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +     * - thumbnail_path     The thumbnail path of file, when available
Yes you are right, sorry @obuisard , I was wrong here.

2022-11-10 18:39 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +                $obj->thumbnail_path = $this->thumbnails ? $this->getThumbnail($path) : $this->getUrl($obj->path);
Again you are right!! Thanks for checking.

2022-11-10 18:49 UTC, obuisard commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +                $obj->thumbnail_path = $this->thumbnails ? $this->getThumbnail($path) : $this->getUrl($obj->path);
Yep! Thank you both for the review, I have checked the file again

2022-11-10 18:50 UTC, obuisard commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +     * - thumbnail_path     The thumbnail path of file, when available
Yes, I have figured it out while testing it. Thank you both.

2022-11-10 20:00 UTC, obuisard commented on libraries/src/Image/Image.php
> +    public function createThumbs($thumbSizes, $creationMethod = self::SCALE_INSIDE, $thumbsFolder = null)
I have added @deprecated, not sure if 5.0, 6.0 or 7.0...

2022-11-10 20:23 UTC, laoneo commented on libraries/src/Image/Image.php
> +    public function createThumbs($thumbSizes, $creationMethod = self::SCALE_INSIDE, $thumbsFolder = null)
Must be 6.0. A pr similar to [this](https://github.com/joomla/Manual/pull/50) one is required as well in the manual.

2023-01-19 01:23 UTC, obuisard commented
Troy @N6REJ and Jacob @jwaisner, would you mind re-testing this so we can merge it? Thank you so much!

2023-01-19 02:08 UTC, jwaisner commented
I have tested this item :white_check_mark: successfully on d82abd9fed569dccc9e8772486ae20137d4fd510<br /><br />Everything retested well. No issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38805">issues.joomla.org/tracker/joomla-cms/38805</a>.</sub>

2023-01-19 03:40 UTC, N6REJ commented
I have tested this item :red_circle: unsuccessfully on d82abd9fed569dccc9e8772486ae20137d4fd510<br /><br />in my test the images were already thumbnailed without the PR.  This was " The currently installed Joomla! version is "‎4.3.0-dev"‎4.3.0-dev"
with the latest composer & npm.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38805">issues.joomla.org/tracker/joomla-cms/38805</a>.</sub>

2023-01-19 17:34 UTC, obuisard commented
> in my test the images were already thumbnailed without the PR. 

That's strange. The thumbnails created with the PR should be 200x200.

2023-01-19 17:38 UTC, dgrammatiko commented
@obuisard what @N6REJ is showcasing is the SIZE of the container DIV, not the size of the image. To get the size of the image open the browser tools, select the image in the elements tab and in the console type `$0.naturalWidth` (or naturalHeight for the height). False alarm...

2023-01-19 17:40 UTC, obuisard commented
> @obuisard what @N6REJ is showcasing is the SIZE of the container DIV, not the size of the image. To get the size of the image open the browser tools, select the image in the elements tab and in the console type `$0.naturalWidth` (or naturalHeight for the height). False alarm...

Oh good catch Dimitris @dgrammatiko! @N6REJ can you double-check? Thank you!

2023-01-19 18:17 UTC, Quy commented
Blurry quality:
![38805-blurry-quality](https://user-images.githubusercontent.com/368084/213527044-ab0984a2-3fb6-4da5-978a-2537f612c6ab.jpg)

Before PR:
![38805-gif-before](https://user-images.githubusercontent.com/368084/213527091-0c91ad2a-46ae-46a3-bda5-7bbd1130b156.jpg)

After PR:
![38805-gif-after](https://user-images.githubusercontent.com/368084/213527124-e425e96e-c0b8-4724-a116-69cfa768eb60.jpg)

2023-01-19 20:28 UTC, obuisard commented
Thank you, Troy @N6REJ for reporting those issues. 
The image quality and handling of transparency for GIFs is unrelated to this PR, but improvements need to be made to the image library itself. Something for another PR...

2023-01-20 00:07 UTC, N6REJ commented
I have tested this item :white_check_mark: successfully on d82abd9fed569dccc9e8772486ae20137d4fd510<br /><br />retested as instructed.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38805">issues.joomla.org/tracker/joomla-cms/38805</a>.</sub>

2023-01-20 00:50 UTC, merged

2023-01-20 00:51 UTC, obuisard commented
A big thank you to Dimitris @dgrammatiko and the testers !

2023-01-20 04:04 UTC, carlitorweb commented
**Documentation added** :heavy_check_mark:

2023-01-20 10:15 UTC, dgrammatiko commented
@obuisard I haven't checked but is the thumbnails functionality bypasses the svg files? If not it needs to do so, the thumbs helper expects only files that the Image class can handle. I'll try to check the next days if I get some free time

2023-01-20 15:30 UTC, obuisard commented
> @obuisard I haven't checked but is the thumbnails functionality bypasses the svg files? If not it needs to do so, the thumbs helper expects only files that the Image class can handle. I'll try to check the next days if I get some free time

@dgrammatiko I have checked SVG and image thumbnail creation and both work well together

2023-01-20 20:48 UTC, N6REJ commented
it's sad that we are using GD instead of imagemagick.

2023-01-20 21:24 UTC, obuisard commented
> it's sad that we are using GD instead of imagemagick.

I know, but GD is more widely installed than imagick. It would be great to offer the use of either one of those graphic libraries in Joomla.

2023-01-20 21:28 UTC, dgrammatiko commented
You'll be surprised but GD (PHP 8.1+) is (median) faster than imagick. How do I know? I keep testing these for [responsive-images](https://responsive-images.dgrammatiko.dev)

2023-01-21 03:58 UTC, N6REJ commented
@dgrammatiko faster but I thouight imagick quality was far higher?