Deprecation message in PHP 8.1, clearer code
joomla/joomla-cms pull request #39003
Opened 2022-10-20 15:04 UTC by MacJoom

### Summary of Changes
- Avoid deprecation message in PHP 8.1
- clearer code
### Testing Instructions
Setup a custom module
Setup an article with a {loadmodule costum}

Turn on all PHP Warnings
display_errors = On
error_reporting = E_ALL | E_STRICT

### Actual result BEFORE applying this Pull Request

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/clients/client2/web14/web/joomla-cms/plugins/content/loadmodule/loadmodule.php on line 115

### Expected result AFTER applying this Pull Request

No warning anymore

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2022-10-20 17:57 UTC, richard67 commented on plugins/content/loadmodule/loadmodule.php
> +                    $title   = "";
Please use single quotes and not double quotes here. We use double quotes only when necessary or helpful, e.g. when having a „\n“ in the string. But here we don’t have that so we should use single quotes.

2022-10-20 19:03 UTC, MacJoom commented on plugins/content/loadmodule/loadmodule.php
> +                    $title   = "";
OK - understood - will change this

2022-10-20 20:37 UTC, Quy commented on plugins/content/loadmodule/loadmodule.php
> +                    $title   = '';
```suggestion
                // First parameter is the module, will be prefixed with mod_ later
                $module = trim($matchesmodlist[0]);
                // Second parameter is the title
                if (array_key_exists(1, $matchesmodlist)) {
                    $title = htmlspecialchars_decode(trim($matchesmodlist[1]));
                } else {
                    $title = '';
```

2022-10-21 08:19 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 992ef0522530f329467da90219a7606bcf64121d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39003">issues.joomla.org/tracker/joomla-cms/39003</a>.</sub>

2022-10-21 09:07 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 992ef0522530f329467da90219a7606bcf64121d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39003">issues.joomla.org/tracker/joomla-cms/39003</a>.</sub>

2022-10-21 09:08 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39003">issues.joomla.org/tracker/joomla-cms/39003</a>.</sub>

2022-10-22 15:04 UTC, HLeithner requested changes
We try to avoid else where easily possible.

2022-10-22 15:04 UTC, HLeithner commented on plugins/content/loadmodule/loadmodule.php
>                  }
```suggestion
                // First parameter is the module, will be prefixed with mod_ later
                $module = trim($matchesmodlist[0]);
                $title = '';

                // Second parameter is the title
                if (array_key_exists(1, $matchesmodlist)) {
                    $title = htmlspecialchars_decode(trim($matchesmodlist[1]));
                }

```

2022-10-22 15:04 UTC, HLeithner commented on plugins/content/loadmodule/loadmodule.php
>                  }
```suggestion
                $stylemod = '';
                if (array_key_exists(2, $matchesmodlist)) {
                    $stylemod = trim($matchesmodlist[2]);
                }
```

2022-10-23 09:38 UTC, bembelimen commented
Remove RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39003">issues.joomla.org/tracker/joomla-cms/39003</a>.</sub>

2022-10-23 18:59 UTC, Quy commented on plugins/content/loadmodule/loadmodule.php
>                  }
```suggestion
                $title = '';
                if (array_key_exists(1, $matchesmodlist)) {
                    $title = htmlspecialchars_decode(trim($matchesmodlist[1]));
                }
```

2023-01-12 14:18 UTC, laoneo commented
@HLeithner can you approve when the code is ok, then people can test it again?

2023-01-12 14:40 UTC, HLeithner requested changes

2023-01-12 14:40 UTC, HLeithner commented on plugins/content/loadmodule/loadmodule.php
> +                // Third paramater is the module style, (fallback is the plugin default set earlier).
```suggestion

                // Third paramater is the module style, (fallback is the plugin default set earlier).
```

2023-01-12 14:40 UTC, HLeithner commented on plugins/content/loadmodule/loadmodule.php
> +                // Second parameter is the title
```suggestion

                // Second parameter is the title
```

2023-01-12 14:40 UTC, HLeithner commented on plugins/content/loadmodule/loadmodule.php
> +                if (array_key_exists(1, $matchesmodlist)) {
```suggestion

                if (array_key_exists(1, $matchesmodlist)) {
```

2023-01-12 14:42 UTC, HLeithner requested changes

2023-01-12 14:42 UTC, HLeithner commented on plugins/content/loadmodule/loadmodule.php
> +                // Second parameter is the title
```suggestion
                $module = trim($matchesmodlist[0]);

                // Second parameter is the title
```

2023-01-12 14:42 UTC, HLeithner commented on plugins/content/loadmodule/loadmodule.php
> +                if (array_key_exists(2, $matchesmodlist)) {
```suggestion
                $stylemod = '';

                if (array_key_exists(2, $matchesmodlist)) {
```

2023-01-12 14:44 UTC, HLeithner approved these changes
I added some blank lines which we have normally before comments and if statements. Rest looks good for me now.

2023-01-12 21:20 UTC, carlitorweb commented
I have tested this item :white_check_mark: successfully on 6b93585871e98a1baca8fe82e4b6be70f91d2245<br /><br />**Just a note:** In 8.2 do not show this deprecated message without this PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39003">issues.joomla.org/tracker/joomla-cms/39003</a>.</sub>

2023-01-13 00:54 UTC, brianteeman commented on plugins/content/loadmodule/loadmodule.php
> +                // Third paramater is the module style, (fallback is the plugin default set earlier).
```suggestion
                // Third parameter is the module style, (fallback is the plugin default set earlier).
```

spelling

2023-01-23 17:43 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 935c0ec0289c4895ec63b03aa0a906603e5c9d8f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39003">issues.joomla.org/tracker/joomla-cms/39003</a>.</sub>

2023-01-23 17:44 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39003">issues.joomla.org/tracker/joomla-cms/39003</a>.</sub>

2023-02-03 21:49 UTC, merged

2023-02-03 21:51 UTC, fancyFranci commented
Looks good. Thank you!