[4.3] Fixing php compatibility issues 3
joomla/joomla-cms pull request #39058
Opened 2022-10-24 09:07 UTC by Hackwar

### Summary of Changes
This is one of several PRs to separate out the fixes from #38471. The `mbstring.func_overload` feature was deprectaed in PHP 7.2 and removed in PHP 8.0.

### Testing Instructions
Codereview

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

2022-10-24 11:35 UTC, brianteeman commented
as enforced by @hleithner you cannot remove the language strings. you can only mark them as deprecated

2022-10-24 12:35 UTC, HLeithner commented
based on the b/c policy, please deprecate and remove with 5.0 pr and add a documentation for this please

2022-10-24 13:23 UTC, Hackwar commented
Done. here is the documentation PR: https://github.com/joomla/Manual/pull/54

2022-10-24 23:35 UTC, wilsonge requested changes
I think removing the check is wrong for valid PHP Versions (i.e. anything pre-php 8.0 - just because the string is deprecated doesn't mean people may have it set to undesirable values). I think we should just wrap it in a version check statement rather than remove it.

2022-10-25 06:47 UTC, HLeithner commented
> I think removing the check is wrong for valid PHP Versions (i.e. anything pre-php 8.0 - just because the string is deprecated doesn't mean people may have it set to undesirable values). I think we should just wrap it in a version check statement rather than remove it.

if it set in a php version that it doesn't support we don't need to care right? But in this case we support php 7.2 which also support mbstring.func_overload right? so I would rebase this pr on 5.0 problem solved.

2022-10-25 08:36 UTC, wilsonge commented
That's fine too. But I think @Hackwar wanted to add the phpcs compat checking in now. And if it's removed in 8.0 a version check to not show unnecessary info is fine imo from a minor version

2022-10-25 13:47 UTC, HLeithner commented
> That's fine too. But I think @Hackwar wanted to add the phpcs compat checking in now. And if it's removed in 8.0 a version check to not show unnecessary info is fine imo from a minor version

in this case it makes more sense to wrap the code in a phpcs ignore block and add a deprecation notice

2023-03-06 11:58 UTC, wilsonge requested changes
Minor things but fine

2023-03-06 11:58 UTC, wilsonge commented on administrator/language/en-GB/com_joomlaupdate.ini
> +; Deprecated, will be removed with 5.0
Either remove or change version (same with the rest of the strings)

2023-03-07 22:27 UTC, merged

2023-03-07 22:27 UTC, HLeithner commented
thanks