[4.2] Convert missing files to PSR-12 code style
joomla/joomla-cms pull request #39197
Opened 2022-11-12 08:35 UTC by heelc29

Pull Request for Issue #38754 and #38786 .

### Summary of Changes

Note that not all files were converted to the PSR-12 codestyle during PR #37686 eg:
- administrator/components/com_actionlogs/src/View/Action`logs/`HtmlView.php
- administrator/components/com_admin/src/Service/HTML/`Configuration.php`
- administrator/components/com_cache/tmpl/`cache/`default.php
- administrator/components/com_media/tmpl/`media/`default.php
- api/components/com_`media/`src/Model/MediaModel.php
- layouts/joomla/form/field/`media/`accessiblemedia.php
- libraries/src/`Cache/`Cache.php
- libraries/src/Component/Router/RouterView`Configuration.php`
- plugins/fields/`media/`media.php
- plugins/privacy/action`logs/`actionlogs.php
- plugins/system/`cache/`src/Extension/Cache.php
- plugins/webservices/`media/`media.php

These files are therefore not checked by Drone now. This is due to an overly open exclude list (marked in list above).

### Testing Instructions

- Drone works
- Code Review
- Install Joomla

### Actual result BEFORE applying this Pull Request

2648 files are checked by `phpcs`

### Expected result AFTER applying this Pull Request

2743 files are checked by `phpcs`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

cc @HLeithner

2022-11-12 14:18 UTC, richard67 commented
@heelc29 Regarding the testing instructions: "Install Joomla" is not necessary. That is included already in the "Drone works". The API and system tests include making a new installation on diverse environments, so if these pass, installation works. But it could make sense to let people run the PHPCS tests locally in their environment with `./libraries/vendor/bin/phpcs --extensions=php -p --standard=ruleset.xml .` and check that this works.

2022-11-12 14:23 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 0de1eff0ae04f780747d5061e08708390657b020<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39197">issues.joomla.org/tracker/joomla-cms/39197</a>.</sub>

2022-11-13 14:22 UTC, heelc29 commented
@richard67 

> Regarding the testing instructions: "Install Joomla" is not necessary

Just copied from PR #37686 - but only a part of it 😅

> But it could make sense to let people run the PHPCS tests locally in their environment

This is not always possible because I have problems with the EOL in my **win** environment:
![image](https://user-images.githubusercontent.com/66922325/201526628-257bcabb-b78f-440b-bfc3-a6377989ad0d.png)

2022-11-13 14:24 UTC, brianteeman commented
@heelc29 there is usually a setting in your git client that will resolve that

2022-11-13 14:24 UTC, richard67 commented
@heelc29 Why have you updated your branch without any need? It resets the counter for human tests and I manually have to add the test result again in the issue tracker. That causes unnecessary work and may cause the one or other PR with 2 good test results being overlooked.

2022-11-13 14:30 UTC, heelc29 commented
> @heelc29 there is usually a setting in your git client that will resolve that

@brianteeman I use GitHub Desktop with default settings ... mmmh so I can't be sure that everyone else has changed it at their git client

2022-11-13 14:31 UTC, heelc29 commented
> @heelc29 Why have you updated your branch without any need? It resets the counter for human tests and I manually have to add the test result again in the issue tracker. That causes unnecessary work and may cause the one or other PR with 2 good test results being overlooked.

@richard67 I thought to make sure there are no conflicts or new code style errors from the changed ruleset.

2022-11-13 15:12 UTC, brianteeman commented
> . mmmh so I can't be sure that everyone else has changed it at their git client

Thats irrelevant. Just follow https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

2022-11-14 08:24 UTC, laoneo commented on build/psr12/ruleset.xml
> +        <exclude-pattern type="relative">tests/</exclude-pattern>
Why do you exclude here tests?

2022-11-14 14:30 UTC, heelc29 commented on build/psr12/ruleset.xml
> +        <exclude-pattern type="relative">tests/</exclude-pattern>
I just copied the root folder's ruleset, which was adjusted with PR #38161.

2023-01-15 12:02 UTC, heelc29 commented
Conflicts resolved in:
- administrator/components/com_actionlogs/tmpl/actionlogs/default.php
- libraries/src/Cache/Cache.php
- libraries/src/Cache/CacheController.php
- libraries/src/Cache/CacheStorage.php
- libraries/src/Cache/Controller/CallbackController.php
- libraries/src/Cache/Storage/FileStorage.php
- libraries/src/Cache/Storage/MemcachedStorage.php
- libraries/src/Cache/Storage/RedisStorage.php
- plugins/privacy/actionlogs/actionlogs.php
- plugins/system/actionlogs/actionlogs.php

2023-01-15 16:14 UTC, HLeithner requested changes
sorry that this took so long, can you change the target branch to 4.3 pleasE?

2023-01-15 16:14 UTC, HLeithner commented on administrator/components/com_cache/tmpl/cache/default.php
> +                    <table class="table">
can you revert the changing to the template file, we don't have a clear psr policy for mixed html/php files

2023-01-16 16:56 UTC, heelc29 commented
> sorry that this took so long, can you change the target branch to 4.3 pleasE?

@HLeithner Sure, but I will wait for the next upmerge, there are many conflicts at the moment:
_[4.3] Change application input access to getInput_ #39029 vs. _Changes the code base to short array syntax_ #39616
And a tricky one too in `libraries/namespacemap.php` which I don't want to resolve. Take care here @obuisard ;)
_[4.2] Fix library autoloading_ #39348 vs. _Add namespace support to templates_ #39011

2023-01-16 17:06 UTC, heelc29 commented on administrator/components/com_cache/tmpl/cache/default.php
> +                    <table class="table">
@HLeithner If I use the current file of the 4.2-dev branch I will get following errors:
![image](https://user-images.githubusercontent.com/66922325/212732368-e2c5a626-7463-4064-9a45-0b92873228f8.png)

If I should revert the changes, I have to add this file to ignore list to get drone phpcs happy (again). Should I do this?

2023-01-16 17:08 UTC, HLeithner commented on administrator/components/com_cache/tmpl/cache/default.php
> +                    <table class="table">
in this case keep it

2023-01-16 17:56 UTC, heelc29 commented on administrator/components/com_cache/tmpl/cache/default.php
> +                    <table class="table">
Ok

2023-01-21 13:01 UTC, heelc29 commented
> sorry that this took so long, can you change the target branch to 4.3 pleasE?

@HLeithner done

2023-01-21 15:10 UTC, HLeithner approved these changes
Thanks

2023-01-27 14:15 UTC, merged