[5.0]New method BaseController->prepareViewModel() to set the View Models,
joomla/joomla-cms pull request #39447
Opened 2022-12-18 20:09 UTC by framontb

### Summary of Changes

Changes to ease the use of multiple models in one view for custom (or core) components in Joomla 4.

By moving just three lines of code from `BaseController->display()` 
to a new method `BaseController->setViewModel($view)`,
you can easily assign the models you want to any of your views. 

Everything works exactly the same. The method is called at the same point the lines were before.
But the diference is: 
* now you can overwrite the new method in the `DisplayController` of your custom component like this:

```PHP
    public function display($cachable = false, $urlparams = [])
    {
         return parent::display();
    }

    protected function prepareViewModel($view)
    {
        parent::prepareViewModel($view);

        $viewName = $view->getName();

        // Push the Second model into the Foos view
        if ($viewName == strtolower("Foos") && ($model = $this->getModel('Second'))) {
            $view->setModel($model);
        }

        // Push the Third model into the Foos view
        if ($viewName == strtolower("Foos") && ($model = $this->getModel('Third'))) {
            $view->setModel($model);
        }
    }
    }
```
Here you see that you don't need to touch your `DisplayController->display()` method to assign the models.
Nor call to Factories. All you need is already in the `DisplayController` with minimum code.
You only overwrite the `DisplayController->setViewModel()`, call the parent (that assigns the default model as usual),
and assigns a couple of new models to the "Foos" view.

Now you only have to call it properly and easily in your view, like this:
```PHP
	public function display($tpl = null)
	{
            $this->msg  = $this->get('Msg');
            $this->msg2 = $this->get('Msg', 'Second');
            $this->msg3 = $this->get('Msg', 'Third');
        
	    return parent::display($tpl);
	}
```
Here you see how to call the methods of the Second and Third Model.

Just like it is described here: [Using multiple models in an MVC component](https://docs.joomla.org/Using_multiple_models_in_an_MVC_component)
Only now, you don't need to care about custom `display()` methods in your views.
The default `display()` works perfectly fine.

### Testing Instructions

I developed this little [Component com_foos](https://github.com/framontb/joomla42_test_setViewModels) to test the changes.
You only need to apply the changes to your Joomla 5 installation and install the component as usual.

### Actual result BEFORE applying this Pull Request

Break MVC model to call several models for one view, using factories called in helpers,
or need to rewrite your own `DisplayController->display()`.

See [Ease the use of multiple models in one view](https://github.com/joomla/joomla-cms/pull/39327)

### Expected result AFTER applying this Pull Request

If you pick in the **Backend** > Component > COM_FOOS menu link, you will see:

```
Hello Foo from the model: DEFAULT
Hello FOOS from the ADMINISTRATOR model: SECOND
Hello FOOS from the ADMINISTRATOR model: THIRD
```

Each one of this messages, coming from a different model attached to the Foos View.

If you create a menu link in the FronEnd of the testing site, for the com_foos component as usual, you will see:

```
Hello FOO from the SITE model: DEFAULT
Hello FOO from the SITE model: SECOND
Hello FOOS from the ADMINISTRATOR model: THIRD
```

Each one of this messages, coming from a different model attached to the Foo View.

Note that the THIRD model is a backend model. You can assign it exactly the same way.

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: Not specified yet
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2022-12-19 09:50 UTC, SharkyKZ commented
As discussed in the previous PR, this should go into 4.3.

2023-01-11 10:12 UTC, laoneo requested changes

2023-01-11 10:12 UTC, laoneo commented on libraries/src/MVC/Controller/BaseController.php
> +    protected function prepareViewModel($view)
Can you type hint the $view prperty with ViewInterface and add a getName function to the interface?

2023-01-11 10:12 UTC, laoneo commented on libraries/src/MVC/Controller/BaseController.php
> +        if ($model = $this->getModel($viewName, '', array('base_path' => $this->basePath))) {
Can you add here a check if the method exists `setModel` in the $view object.

2023-01-11 10:16 UTC, laoneo commented
@framontb sorry for the delay answering here. Can you add the comments and then we are ready to go.

2023-01-11 20:47 UTC, framontb commented on libraries/src/MVC/Controller/BaseController.php
> +    protected function prepareViewModel($view)
Yep, tomorrow I will do it.

2023-01-11 20:47 UTC, framontb commented on libraries/src/MVC/Controller/BaseController.php
> +        if ($model = $this->getModel($viewName, '', array('base_path' => $this->basePath))) {
Yep, tomorrow I will do it.

2023-01-12 23:41 UTC, framontb commented
@laoneo I think the requested changes are done.

2023-01-12 23:50 UTC, HLeithner commented
Wouldn't make sense to check the view if it has the interface before calling the prepare function?

2023-01-12 23:57 UTC, framontb commented
> Wouldn't make sense to check the view if it has the interface before calling the prepare function?

Don't know, but the `$view = $this->getView()` call returns a ViewInterface (says the DocBlocK):
```php
     * @return  ViewInterface  Reference to the view or an error.
     *
...
     */
    public function getView($name = '', $type = '', $prefix = '', $config = array())
```

2023-01-13 06:26 UTC, HLeithner commented
OK then it's not needed

2023-01-13 07:04 UTC, laoneo commented on libraries/src/MVC/Controller/BaseController.php
> +        }
```suggestion
        }

```

2023-01-13 07:06 UTC, laoneo approved these changes

2023-01-13 07:17 UTC, merged

2023-01-13 07:17 UTC, laoneo commented
Thank you very much for your contribution!