GitHub Issue #31340
joomla/joomla-cms pull request #39518
Opened 2022-12-28 19:32 UTC by rajputanuj31

# GitHub Issue #31340

Added message for no media files-
If no media files in Media then message no media files will be displayed to user if user clicked on checkbox

2022-12-28 20:25 UTC, brianteeman commented
this is only good for english

2022-12-28 21:26 UTC, richard67 commented
@rajputanuj31 Joomla has to work with other languages than English, too, so we can't use a hardcoded English text here.

2022-12-28 21:49 UTC, chmst commented
@rajputanuj31 thanks for your contribution! Skills in vue.js are very appreciated.
Joomla is a huge system and of course you cannot know everything - but you can learn,
If you are interested in GSoC 2023, join us on mattermost  https://joomlacommunity.cloud.mattermost.com/main/channels/gsoc2023

2022-12-29 01:11 UTC, dgrammatiko commented
Please check how to use the if/else conditionals on the html part of the vue file. You **don't** have to create elements manually as vue has a simpler way for that...

2023-01-16 19:51 UTC, fancyFranci commented
Great to see that you worked on the issue and want to contribute your result!
Every pull request needs 2 successful user tests. To have a higher chance to get those tests: Please have a look on the descriptions of other pull requests here and how they are structured. "Summary of Changes", "Testing Instructions", before and after applying the patch etc. Add this structure to your PR description as well and you will make it easier for others to test your changes. Screenshots are very helpful too.

2023-01-16 20:00 UTC, fancyFranci commented on administrator/components/com_media/resources/scripts/components/toolbar/toolbar.vue
> +      let msg = 'No Media Files';
Instead of hardcode the message, see how we use `Joomla.Text` in other js scripts. All our messages are stored in ini files like `language\en-GB\com_media.ini`. To get texts from these files into the Text object you need to load them on the php side, This could be here `administrator\components\com_media\tmpl\media\default_texts.php`

2023-01-22 11:42 UTC, dgrammatiko requested changes

2023-01-22 11:42 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +    },
```suggestion
    isEmpty() {
      const directories = this.$store.getters.getSelectedDirectoryDirectories;
      const files = this.$store.getters.getSelectedDirectoryFiles;
      return [...directories, ...files].length ? false : true;
    },
```

Also change line 14 to `<h4 v-if="isEmpty">`

2023-01-22 12:02 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +    },
I have made the changes you have suggested thank you so much.

2023-01-22 12:06 UTC, Quy commented on language/en-GB/com_media.ini
> +COM_MEDIA_NO_MEDIA_FOUND="No Media Added"
Please sort key in alpha order.

2023-01-22 12:58 UTC, richard67 commented on language/en-GB/com_media.ini
> +
```suggestion
```
Revert the new line at the end of file.

2023-01-22 13:00 UTC, dgrammatiko commented on language/en-GB/com_media.ini
> +COM_MEDIA_NO_MEDIA_FOUND="No Media Added"
```suggestion
COM_MEDIA_NO_MEDIA_FOUND="No Media Found"
```

For consistency please use the same verb as on the previous line

2023-01-22 13:12 UTC, dgrammatiko commented
@rajputanuj31 please run `npm run lint:js -- --fix` to fix the codestyle, nice work!

2023-01-22 13:21 UTC, richard67 commented
> @rajputanuj31 please run `npm run lint:js -- --fix` to fix the codestyle, nice work!

Would be even better if @rajputanuj31 would follow @fancyFranci ' [recommendation above](https://github.com/joomla/joomla-cms/pull/39518#issuecomment-1384488844) and change the title to something meaningful, add some description and finally some testing instructions.

2023-01-22 13:32 UTC, Quy commented on administrator/components/com_media/tmpl/media/default_texts.php
> +Text::script('COM_MEDIA_NO_MEDIA_FOUND', true);
Please alpha sort.

2023-01-22 14:20 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +    },
```suggestion
        isEmpty() {
      return ![...this.$store.getters.getSelectedDirectoryDirectories, ...this.$store.getters.getSelectedDirectoryFiles].length;
    },
```

2023-01-22 14:59 UTC, richard67 commented
@rajputanuj31 You have to add the new string also to the administrator language file below this line here: https://github.com/joomla/joomla-cms/blob/8c485ae108e40268ee546c0911e2fb7eec18bd6e/administrator/language/en-GB/com_media.ini#L82 . Otherwise you see "COM_MEDIA_NO_MEDIA_FOUND" instead of "No Media Found" when using the Media Manager in backend (administrator).

2023-01-22 16:03 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on ccd85190d4ab57801a8df0179cebd614cb806d10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39518">issues.joomla.org/tracker/joomla-cms/39518</a>.</sub>

2023-01-22 21:29 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on ccd85190d4ab57801a8df0179cebd614cb806d10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39518">issues.joomla.org/tracker/joomla-cms/39518</a>.</sub>

2023-01-22 21:31 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39518">issues.joomla.org/tracker/joomla-cms/39518</a>.</sub>

2023-01-26 22:55 UTC, dgrammatiko commented
I have tested this item :red_circle: unsuccessfully on ccd85190d4ab57801a8df0179cebd614cb806d10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39518">issues.joomla.org/tracker/joomla-cms/39518</a>.</sub>

2023-01-26 22:58 UTC, dgrammatiko commented
@richard67 please remove the RTC flag here. This still needs:
- better css
- be aware of the loading state (ie not display until fetching of the data is complete)
- tweaks on the list view

For the first 2 the code exists in https://github.com/joomla/joomla-cms/pull/39709 the 3rd one needs some tweaks on the relative component

2023-01-27 12:42 UTC, rajputanuj31 commented
@dgrammatiko since the base branch has been changed and there are lot of conflicts. I am unable to understand what should I do. Please guide me a bit.

2023-01-27 19:13 UTC, rajputanuj31 commented
Created New PR:#39731

2023-01-27 19:13 UTC, closed without merging