Convert mod_articles_category to new structure
joomla/joomla-cms pull request #39527
Opened 2022-12-30 19:33 UTC by carlitorweb

### Summary of Changes
This PR converts mod_articles_category to the new structure

### Testing Instructions
- Use Joomla 4.3
- Create an instance of the module Articles Category. Note how it works.
- Apply patch
- Delete administrator/cache/autoload_psr4.php
- Refresh the page, make sure the module still displays the same as before.

2022-12-30 20:53 UTC, richard67 commented
@carlitorweb Unfortunately you have made the moving of the file and the changes inside the moved file with the same one commit, so GitHub does not show a moved and changed file but a deleted and a new file, so the history got lost. To avoid that, moving a file and changing its content have to be made with 2 separate commits. It’s not a big problem, but please remember that for future PR‘s.

2022-12-30 21:57 UTC, carlitorweb commented
> @carlitorweb Unfortunately you have made the moving of the file and the changes inside the moved file with the same one commit, so GitHub does not show a moved and changed file but a deleted and a new file, so the history got lost. To avoid that, moving a file and changing its content have to be made with 2 separate commits. It’s not a big problem, but please remember that for future PR‘s.

Copy that. Really not notice this when doing the changes, sorry. If is neccessary I can do all again, not problem.

2022-12-30 22:00 UTC, richard67 commented
> If is neccessary I can do all again, not problem.

@carlitorweb Not necessary. All ok.

2022-12-31 10:28 UTC, laoneo approved these changes

2022-12-31 10:29 UTC, laoneo commented
@richard67 sometimes, even when you rename a file and do a lot of changes, git is not able to detect the rename.

@carlitorweb thank you very much, now we need the two tests to get it merged.

2022-12-31 15:35 UTC, carlitorweb commented
@laoneo you are welcome, glad to help. I will continue with the rest.

2022-12-31 23:28 UTC, ReLater commented
I don't know how "hungry" `$db = $this->getDatabase();`, but as far as I see `$db` ist only used once. Maybe it's more efficient to move `this->getDatabase` down?

```
                case 'random':
                    $articlesModel->setState('list.ordering', $this->getDatabase()->getQuery(true)->rand());
                    break;
```

2023-03-21 07:12 UTC, laoneo commented
Would it be possible to write also a system test for this module, similar as we did in #40092? If you need help how to get started with system tests, you can find some information [here](https://github.com/joomla/joomla-cms/tree/4.4-dev/tests/System).

2023-03-21 07:17 UTC, laoneo commented
Can you also fix the code style issues?

2023-03-22 15:58 UTC, joomdonation commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        return (new self())->getArticles($params, $app);
Here we have a problem: The class expect `module` and `input` provided in `$config` array, but you do not provide these elements while creating the object. So if someone call this static method, they will get fatal error.

2023-03-27 20:03 UTC, carlitorweb commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        return (new self())->getArticles($params, $app);
That is correct. Checking, there is not way I can pass the `module` object from there...

For the `input` with adding to the class constructor
`array_key_exists('input', $config) ? $config['input'] : Factory::getApplication()->getInput();`
Is enough.

2023-03-27 20:06 UTC, carlitorweb commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        return (new self())->getArticles($params, $app);
The `module` oject is used only creating the cache key
`$cacheKey = md5(serialize([$moduleParams->toString(), $this->module->module, $this->module->id]));`

2023-03-28 06:14 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        $cache = Factory::getContainer()->get(CacheControllerFactoryInterface::class)
This should be injected.

2023-03-28 06:14 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +    public static function cleanIntrotext(string $introtext): string
If some extensions did extend this class, then they will break with these changes as signature changes will lead to a fatal error in PHP 8.

2023-03-28 13:32 UTC, carlitorweb commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +    public static function cleanIntrotext(string $introtext): string
Yes, this is my mistake. The phpstorm was complaining here, and after commit I saw the mistake. Will fix it with next commit

2023-03-28 13:52 UTC, carlitorweb commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        $cache = Factory::getContainer()->get(CacheControllerFactoryInterface::class)
I revert this

2023-03-28 13:53 UTC, carlitorweb commented
@laoneo done, please check if is okay

After fix the others similar PRs I did, I will do what you mention about system test

2023-03-28 13:54 UTC, laoneo commented
As less functionality you change as better as the module should basically get converted only to the new structure. New features should be done in a separate pr on the 5.0-dev branch.

2023-03-29 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        $this->input  = array_key_exists('input', $config)
Why is this needed?

2023-03-29 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +                                    $articleModel = $mvcContentFactory->createModel(
We accept a line length of 150 characters, why do you put them on multiple lines?

2023-03-29 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        if ($groupBy !== 'none') {
Why did you add new group by logic?

2023-03-29 17:54 UTC, carlitorweb commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        if ($groupBy !== 'none') {
This is part of the code of the deleted file https://github.com/joomla/joomla-cms/blob/5b7fa70aeb8e9b1bcbf77988d99aa810e1b4f018/modules/mod_articles_category/mod_articles_category.php#L60-L80

2023-03-29 17:58 UTC, carlitorweb commented
@laoneo I added the cy test

2023-03-30 06:12 UTC, laoneo requested changes

2023-03-30 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> + * @since __DEPLOY_VERSION__
Can you revert this

2023-03-30 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        $active_article_id = $view === 'article' ? $input->getInt('id') : '';
Make the variable camelCase

2023-03-30 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +    public static function _cleanIntrotext(string $introtext): string
Also remove here the type hinting

2023-03-30 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +    public static function truncate(string $html, int $maxLength = 0): string
Remove here the type hinting

2023-03-30 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +    public static function groupBy(array $list, string $fieldName, string $direction, $fieldNameToKeep = null): array
Remove here the type hinting

2023-03-30 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +    public static function groupByDate(
Remove here the type hinting

2023-03-30 06:12 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +    public static function groupByTags(array $list, string $direction = 'ksort'): array
Remove here the type hinting

2023-03-30 06:12 UTC, laoneo commented
> @laoneo I added the cy test. I runned it, and it work. Let me kown if is okay like this for do it for the others PR

Nice, thank you very much!

2023-03-30 13:04 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +     * @param string $introtext introtext to sanitize
If I'm not wrong, then all these changes in existing doc blocks should be reverted as they do not follow our coding standard, described here https://developer.joomla.org/coding-standards/docblocks.html.

2023-03-30 13:11 UTC, carlitorweb commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +     * @param string $introtext introtext to sanitize
phpcs should complaint about this? if yes, is not doing for me on this...I will change it. Big note for me for next PRs about this experience changing all this, I think I gave you more work than doing the code yourself...

2023-03-30 14:44 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +     * @param string $introtext introtext to sanitize
PHPCS is not configured to this extent that it is checking the doc blocks.
No problem about the workload, I'm happy that you are willing to help. Pretty sure when I start working on documentation it will be the opposite.

2023-03-30 14:45 UTC, laoneo approved these changes

2023-03-30 14:52 UTC, joomdonation commented
Look like the cache implementation in this module is completely removed in this PR ?

2023-03-30 14:59 UTC, laoneo commented
It doesn't make sense to use a separate cache in a module as we have caching in the core which caches all modules.

2023-03-30 21:31 UTC, carlitorweb commented
> It doesn't make sense to use a separate cache in a module as we have caching in the core which caches all modules.

Just curious, even 3rd party modules are cached?

2023-03-31 06:22 UTC, laoneo commented
Yes, when the module has a cache option, then it caches automatically according to the global cache option https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Document/Renderer/Html/ModuleRenderer.php#L83.

2023-03-31 15:20 UTC, joomdonation commented
> It doesn't make sense to use a separate cache in a module as we have caching in the core which caches all modules

@laoneo We will have to be careful with this change. This module has **Mode** parameter. If set to Dynamic, Id of category will be get directly from request. If we use default cache from `ModuleRenderer`, the cachemode is static, cache key is not aware of this dynamic Category ID change and I think it won't work as expected.

In short, we will have to test and make sure it works properly when **Mode** parameter of the module set to **Dynamic**.

2023-03-31 15:26 UTC, laoneo commented
Thats why I would change as less logic as possible, because this pr is about converting and not somezhing else.

2023-03-31 15:29 UTC, joomdonation commented
But this PR is not just converting to new structure, it also changes how it works and could be dangerous.

2023-03-31 15:35 UTC, carlitorweb commented
I will close the PR. Then make a new one later changing only the structure. Apologies for the problems.

2023-03-31 15:53 UTC, joomdonation commented
@carlitorweb Thanks for working on this. This module, unfortunately, harder to convert than others which do not use Cache.

2023-03-31 15:57 UTC, carlitorweb commented
No, you are right. The cache will not work. I just remember I made a module for a project using the cache as I was doing here getting the article ID from a request, and I needed include the article ID in the cachekey for make it work properly.

Just saw the opportunity to try to change the module a bit, and I toke it. Anyway, is experience I got for others PR - not change nothing is not necessary to change.

2023-03-31 16:11 UTC, joomdonation commented
> Just saw the opportunity to try to change the module a bit, and I toke it

Better do it in separate PR so that it is easier to review :).

2023-04-01 07:29 UTC, laoneo commented
I would like to add this pr. Can you not just revert th3 breaking changes and reopen?

2023-04-01 20:17 UTC, carlitorweb commented
@laoneo here, I revert the helper and also added the group option you can find in https://github.com/joomla/joomla-cms/blob/338a9402a2702fa5d30bd16acf61138558bcf18f/modules/mod_articles_category/mod_articles_category.php

There is also the cache part but I did not included because not sure if is needed with what you wrote before about _we have caching in the core which caches all modules_. Remember, for the cache work properly in this module, in case of the dynamic mode need to know the article ID.

2023-04-02 00:59 UTC, joomdonation commented
> There is also the cache part but I did not included because not sure if is needed with what you wrote before about we have caching in the core which caches all modules

Just for information, yesterday, I tested a different PR related to cache and now I understand this better. This module has **owncache** parameter, not **cache** like other modules. So on the said line of code https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Document/Renderer/Html/ModuleRenderer.php#L83, `$params->get('cache', 0) == 1` returns false, it is not being cached by automatically by `ModuleRenderer` , and implement cache logic by it own

So we could not remove cache logic in this module. The same is applied to other modules which has **owncache** parameter. For these modules, it's output depends on certain variables from request, so it could not use static cache implementation from `ModuleRenderer`

2023-04-03 07:37 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> -        if (!\is_array($list)) {
Why did you remove this? It is a public function and should work as before.

2023-04-03 07:37 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        }
Is this new functionality or where does the logic come from?

2023-04-03 12:36 UTC, carlitorweb commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        }
https://github.com/joomla/joomla-cms/blob/83079a66ad5c2a6446b6d6ffd4a130ee65801d86/modules/mod_articles_category/mod_articles_category.php#L56-L80

2023-04-03 12:38 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        }
Please revert this to the switch as match is [PHP 8 only](https://www.php.net/manual/en/control-structures.match.php).

2023-04-03 12:39 UTC, laoneo commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        }
I mean change it in the helper as this is the correct place where it belongs to.

2023-04-03 12:39 UTC, carlitorweb commented on modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
> +        }
Okay

2023-04-03 14:04 UTC, merged

2023-04-03 14:07 UTC, joomdonation commented
@laoneo Not sure why you merge this? The module cache feature is lost completely by this PR.

2023-04-03 14:13 UTC, laoneo commented
He reverted the cache code so the helper is as before. Why should something get lost now?

2023-04-03 14:15 UTC, carlitorweb commented
> He reverted the cache code so the helper is as before. Why should something get lost now?

We meant this in our previous comments:

https://github.com/joomla/joomla-cms/blob/83079a66ad5c2a6446b6d6ffd4a130ee65801d86/modules/mod_articles_category/mod_articles_category.php#L22-L53

2023-04-03 14:45 UTC, laoneo commented
Can you test #40316?

2023-04-03 14:48 UTC, carlitorweb commented
> Can you test #40316?

I already did, is what I had wrote in case you said we needed include this