Convert mod_articles_popular to new structure
joomla/joomla-cms pull request #39539
Opened 2023-01-02 05:27 UTC by carlitorweb

### Summary of Changes
This PR converts mod_articles_popular to the new structure

### Testing Instructions
- Use Joomla 4.3
- Create an instance of the module Articles - Most Read. Note how it works.
- Apply patch
- Delete administrator/cache/autoload_psr4.php
- Refresh the page, make sure the module still displays the same as before.

2023-01-03 18:04 UTC, carlitorweb commented
@chmst I using the wrong branch?

2023-01-03 20:18 UTC, chmst commented
@carlitorweb my apologies, was not intended to remove the label.

2023-01-06 09:56 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 130e77bb6c9c109670b12327bfafd4d55699e3cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39539">issues.joomla.org/tracker/joomla-cms/39539</a>.</sub>

2023-01-09 15:43 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 130e77bb6c9c109670b12327bfafd4d55699e3cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39539">issues.joomla.org/tracker/joomla-cms/39539</a>.</sub>

2023-01-09 20:28 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39539">issues.joomla.org/tracker/joomla-cms/39539</a>.</sub>

2023-01-10 06:39 UTC, laoneo requested changes

2023-01-10 06:39 UTC, laoneo commented on modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php
> +    protected static function prepareItem($item, $params): object
```suggestion
    private function prepareItem($item, $params): object
```

2023-01-10 06:39 UTC, laoneo commented on modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php
> +                $items[] = static::prepareItem($item, $itemParams);
```suggestion
                $items[] = $this->prepareItem($item, $itemParams);
```

2023-01-10 06:40 UTC, laoneo commented
I would like to avoid static functions, so I made some suggestions. Can you please review them @carlitorweb ?

2023-01-10 12:19 UTC, carlitorweb commented
@laoneo understood. I will change it for other PRs too.

2023-01-10 18:03 UTC, Quy commented on modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php
> +        $cacheKey = md5(serialize(array ($moduleParams->toString(), $this->module->module, $this->module->id)));
```suggestion
        $cacheKey = md5(serialize([$moduleParams->toString(), $this->module->module, $this->module->id]));
```

2023-01-12 08:15 UTC, laoneo approved these changes

2023-01-12 08:16 UTC, laoneo commented
Can we get here just one more test to ensure the recent cosmetic changes are correct?

2023-01-12 16:02 UTC, merged

2023-01-12 16:02 UTC, HLeithner commented
thanks