Using MailTemplate to create new Template record #39480
joomla/joomla-cms pull request #39540
Opened 2023-01-02 06:33 UTC by Kaushik1216

Pull Request for Issue [#39480.](https://github.com/joomla/joomla-cms/issues/39480)

### Summary of Changes
Add extension parameter in createTemplate static function.So that a new record will insert into database after creating email template.

### Testing Instructions
Just make same change as in this PR and create a mail-template and see mail-template after saving in database.

### Actual result BEFORE applying this Pull Request
After creating mail-template a new record not inserted into database in mail template table

### Expected result AFTER applying this Pull Request
After this changes on creating mail-template a new record inserted into database in main template table.

### Link to documentations
Please select:
- [ok] No documentation changes for docs.joomla.org needed

- [ok] No documentation changes for manual.joomla.org needed

2023-01-02 07:16 UTC, richard67 commented
@Kaushik1216 Please fix the code style (PHPCS) errors reported here: https://ci.joomla.org/joomla/joomla-cms/60462/1/6 . Thanks in advance.

2023-01-02 07:31 UTC, Fedik commented
Sorry, but this almost the same as we have here #37898, also the first one #37898 will be slightly better.

2023-01-02 07:47 UTC, Kaushik1216 commented
> Sorry, but this almost the same as we have here #37898, also the first one #37898 will be slightly better.

yes,you are right @Fedik .As I am beginner in joomla-cms contribution so I have less idea about improving code .So please tell me any improvement to this issue if you have !

2023-01-02 13:48 UTC, ReLater commented
@Kaushik1216 

> As I am beginner in joomla-cms contribution so I have less idea about improving code .So please tell me any improvement to this issue if you have !

The first fix that is needed in your branch:
- A new method parameter `$extension` is not allowed at the moment. Remove it!

The second is:
- Get `$template->extension` by using the `$key`!

`$template->extension = explode('.', $key)[0];`

But please be aware that I only collected the comments of others here.

2023-01-02 14:16 UTC, Kaushik1216 commented
> @Kaushik1216
> 
> > As I am beginner in joomla-cms contribution so I have less idea about improving code .So please tell me any improvement to this issue if you have !
> 
> The first fix that is needed in your branch at https://github.com/Kaushik1216/joomla-cms/blob/4.2-dev/libraries/src/Mail/MailTemplate.php#L388:
> 
> * A new method parameter `$extension` is not allowed at the moment. Remove it!
> 
> The second is:
> 
> * Get `$template->extension` by using the `$key`!
> 
> `$template->extension = explode('.', $key)[0];`
> 
> But please be aware that I only collected the comments of others here; concerning backwards compatibility.

this also working .Should I change this in my PR ?

2023-01-02 14:26 UTC, richard67 commented
> this also working .Should I change this in my PR ?

@Kaushik1216 There is an older PR for the same thing, as already discussed. The same proposal has been made to the author of that PR, see https://github.com/joomla/joomla-cms/pull/37898#issuecomment-1366069881 . If he does not want to change his PR, then feel free to take over and continue with yours. But if he will make that change, we will use his PR because he was first.

In general it is not very friendly just to take over the work from another PR if the author hasn't abandoned his PR, and it's also not very effective if several people are doing the same (or nearly the same) for the same issue.

2023-01-04 04:38 UTC, garkell commented
Tested the
`$template->extension = explode('.', $key)[0];`
But we still need to remove the tags array() wrap because we are sending an assoc array as the parameter.  So line 401 needs to be 
`$params->tags = $tags;`

2023-01-09 14:33 UTC, Kaushik1216 commented
should we wait more for other person to response ? As It is inactive for long time

2023-01-11 06:59 UTC, garkell commented
I tested this from the perspective of including the extension element in the database but there is still the problem of the tags being set as an array when an array is passed as a parameter, or am I missing something?  If I use the existing code with this change included the tags passed as an array and then encased as an array so I think Line 401 should be changed from 
        `$params->tags = array($tags);`
to 
        `$params->tags = $tags;`
Apologies if I've missed something due to my inexperience.  Cheers.

2023-01-11 13:43 UTC, ReLater commented
@garkell 
I don't disagree, I'm just irritated. In the docBlock I see:

`@param array $tags Associative array of tags to replace`

In your example code on https://github.com/joomla/joomla-cms/issues/39480#issue-1509013537

you pass over `array("name","sitename","link_text")` which isn't an ASSOCIATIVE(!) array as far as I know. So, the DocBlock must be corrected, too? When I look into the database it looks like that.

2023-01-11 13:53 UTC, ReLater commented
@Kaushik1216 

> should we wait more for other person to response ? As It is inactive for long time

You don't have to wait and can prepare your pr for tests but you should be aware that if @rigin continues his pr any time soon (we should understand that some people on earth have more serious problems at the moment) that yours will be closed.

2023-02-12 18:08 UTC, ReLater commented
@Kaushik1216
I think, after one month of waiting you can continue here if you still want to.

But be aware that I'm only a contributor like you. I have nothing to decide here ;-)

2023-02-13 19:05 UTC, Kaushik1216 commented
@ReLater  Can U please test this PR I have remove extra parmeter .Thank in advance

2023-02-17 00:23 UTC, garkell requested changes
Line 402 still has the passed parameter of an array enclosed in an array so the parameters end up being double arrayed if that makes sense.  All the core parameters are like:
{"tags":["sitename","name","email","subject","body","url","customfields"]}
BUT when using the below code to load the array of tag parameters the contents would end up like:
{"tags":[["sitename","name","email","subject","body","url","customfields"]]}
So on line 402, remove the array brackets so that it is just:
$params->tags = $tags;
And for completeness update the comment on Line 383 to be:
@param   array   $tags      Array of tags to replace
NOT an Associative array.
The extension change works perfectly.  Thanks.

2023-02-17 00:23 UTC, garkell commented on libraries/src/Mail/MailTemplate.php
>       * @param   array   $tags      Associative array of tags to replace
This parameter comment needs to be changed to: 
Array of tags to replace

2023-02-17 00:23 UTC, garkell commented on libraries/src/Mail/MailTemplate.php
> +        $template->extension = $extension;
This line should be changed to:
$template->extension = explode('.', $key)[0];

2023-02-17 00:23 UTC, garkell commented on libraries/src/Mail/MailTemplate.php
> +    public static function createTemplate($key, $subject, $body, $tags, $extension, $htmlbody = '')
Remove the parameter of $extension as the element is covered in the $key

2023-02-17 00:23 UTC, garkell commented on libraries/src/Mail/MailTemplate.php
>          $params->tags = array($tags);
This line should remove the array wrapper from $tags as it is passed in as an array, change to:
$params->tags = $tags;

2023-02-17 00:23 UTC, garkell commented on libraries/src/Mail/MailTemplate.php
>       * @param   array   $tags      Associative array of tags to replace
Line 402 still has the passed parameter of an array enclosed in an array so the parameters end up being double arrayed if that makes sense.  All the core parameters are like:
{"tags":["sitename","name","email","subject","body","url","customfields"]}
BUT when using the below code to load the array of tag parameters the contents would end up like:
{"tags":[["sitename","name","email","subject","body","url","customfields"]]}
So on line 402, remove the array brackets so that it is just:
$params->tags = $tags;
And for completeness update the comment on Line 383 to be:
@param   array   $tags      Array of tags to replace
NOT an Associative array.
The extension change works perfectly.  Thanks.

2023-02-17 08:42 UTC, Kaushik1216 commented on libraries/src/Mail/MailTemplate.php
>       * @param   array   $tags      Associative array of tags to replace
I think this can be done by maintainers if the think so

2023-03-11 14:25 UTC, Fedik commented on libraries/src/Mail/MailTemplate.php
> +        $template->extension = explode('.', $key)[0];
Please add checking that the dot is exists, and explode only to 2 segments:
```php
$template->extension = str_contains($key, '.') ? explode('.', $key, 2)[0] : '';
```
Thanks.

2023-03-11 14:42 UTC, Kaushik1216 commented on libraries/src/Mail/MailTemplate.php
> +        $template->extension = explode('.', $key)[0];
done please test it

2023-03-11 14:55 UTC, Quy commented on libraries/src/Mail/MailTemplate.php
> -     *
Please undo deletion.

2023-03-11 16:36 UTC, Quy commented on libraries/src/Mail/MailTemplate.php
> +     *
```suggestion
     *
```

2023-03-11 17:11 UTC, Kaushik1216 commented
@Quy  @Fedik Please test it

2023-03-12 09:06 UTC, Fedik commented
It almost works.

Please also fix the Tags, change this:
```php
$params->tags          = [$tags];
```
to
```php
$params->tags          = (array) $tags;
```

In both `createTemplate` and `updateTemplate` methods.

2023-03-12 10:04 UTC, Kaushik1216 commented
> It almost works.
> 
> Please also fix the Tags, change this:
> 
> ```
> $params->tags          = [$tags];
> ```
> 
> to
> 
> ```
> $params->tags          = (array) $tags;
> ```
> 
> In both `createTemplate` and `updateTemplate` methods.

done

2023-03-12 10:06 UTC, Fedik commented
I have tested this item :white_check_mark: successfully on 6565c8529914d8cb58fc23a0b96784cfb5cf9f90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39540">issues.joomla.org/tracker/joomla-cms/39540</a>.</sub>

2023-03-14 06:33 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 6565c8529914d8cb58fc23a0b96784cfb5cf9f90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39540">issues.joomla.org/tracker/joomla-cms/39540</a>.</sub>

2023-03-14 07:21 UTC, alikon commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39540">issues.joomla.org/tracker/joomla-cms/39540</a>.</sub>

2023-03-25 08:43 UTC, Kaushik1216 commented
Please Merge this PR !

2023-03-25 15:07 UTC, chmst commented
@Kaushik1216 Congrats for your  PR set to  RTC :) 
Please be patient -  release managers decide when a PR can be merged, following their version planning.

2023-05-02 16:29 UTC, HLeithner commented
This pull request has been automatically rebased to 4.3-dev.

2023-05-06 21:51 UTC, merged

2023-05-06 21:52 UTC, obuisard commented
The fix is in! Thank you @Kaushik1216 for the PR