php 8.2 -  dynamic property Deprecated
joomla/joomla-cms pull request #39620
Opened 2023-01-13 08:14 UTC by alikon

Pull Request for Issue php 8.2 -  dynamic property Deprecated

### Summary of Changes
declared property

### Testing Instructions
open frontend with php 8.2 with Error Reporting = maximum

### Actual result BEFORE applying this Pull Request
Deprecated: Creation of dynamic property Joomla\CMS\User\User::$aid is deprecated in /shared/httpd/dev4/joomla-cms/libraries/src/User/User.php on line 871

### Expected result AFTER applying this Pull Request
no more deprecation

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-01-13 08:34 UTC, laoneo requested changes

2023-01-13 08:34 UTC, laoneo commented on libraries/src/User/User.php
> +     * aid
This here needs a better text

2023-01-13 09:01 UTC, alikon commented on libraries/src/User/User.php
> +     * aid
done asset id

2023-01-13 09:17 UTC, laoneo commented on libraries/src/User/User.php
> +     * asset id
```suggestion
     * The asset id
```

2023-01-13 09:18 UTC, laoneo approved these changes

2023-01-13 09:18 UTC, laoneo commented on libraries/src/User/User.php
> +     /**
```suggestion
    /**
```

2023-01-13 10:08 UTC, joomdonation commented on libraries/src/User/User.php
> +     * The asset id
This is not asset id. It could be called access level id (0: Public, 1: Registered, 2: Special). Guess it was used in Joomla 1.5 or earlier (before we have Viewing Access Level management ?). We do not use it now, so maybe the property should be deprecated and removed in Joomla 5 or 6. See https://groups.google.com/g/joomla-dev-general/c/mdZnTwgF67c?pli=1 for details discussion .

2023-01-13 10:28 UTC, laoneo commented on libraries/src/User/User.php
> +     * The asset id
As I was testing it, I was actually looking for references, but couldn't find one. So I assumed it is not used anymore. But we can only deprecate it in 4.3, because of our policy.
Can you make a suggestion for the new doc text?

2023-01-13 10:34 UTC, joomdonation commented on libraries/src/User/User.php
> +     * The asset id
For now, I think it could be "The access level id". Then we can deprecate it in 4.3.

2023-01-13 11:08 UTC, alikon commented on libraries/src/User/User.php
> +     * The asset id
done

2023-01-13 12:30 UTC, wilsonge approved these changes

2023-01-13 14:02 UTC, laoneo commented
I have tested this item :white_check_mark: successfully on 5e3bffc253ae30d4bd697aeda12a53aa378cc29d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39620">issues.joomla.org/tracker/joomla-cms/39620</a>.</sub>

2023-01-13 14:49 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on 5e3bffc253ae30d4bd697aeda12a53aa378cc29d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39620">issues.joomla.org/tracker/joomla-cms/39620</a>.</sub>

2023-01-13 14:49 UTC, joomdonation commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39620">issues.joomla.org/tracker/joomla-cms/39620</a>.</sub>

2023-01-14 10:24 UTC, merged

2023-01-14 10:24 UTC, roland-d commented
Thank you