Converts tinymce to service providers
joomla/joomla-cms pull request #39625
Opened 2023-01-13 16:47 UTC by laoneo

### Summary of Changes
Converts the tinymce editor to service providers.

### Testing Instructions
Edit an article.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-01-13 16:52 UTC, dgrammatiko commented
@laoneo thank you for the one! I'll test it in a bit

2023-01-13 16:58 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 53b65edf57c6c45ed46fb173747452ec2d674c00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39625">issues.joomla.org/tracker/joomla-cms/39625</a>.</sub>

2023-01-13 17:01 UTC, dgrammatiko requested changes

2023-01-13 17:01 UTC, dgrammatiko commented on plugins/editors/tinymce/src/Field/TinymcebuilderField.php
> +use Joomla\Plugin\Content\Contact\Extension\TinyMCE;
```suggestion
use Joomla\Plugin\Editors\TinyMCE\Extension\TinyMCE;
```

2023-01-13 17:02 UTC, dgrammatiko commented
I have tested this item :red_circle: unsuccessfully on 53b65edf57c6c45ed46fb173747452ec2d674c00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39625">issues.joomla.org/tracker/joomla-cms/39625</a>.</sub>

2023-01-13 17:11 UTC, laoneo commented
I'v uploaded a fix, it should work now. Strange thing was that it loaded without that change for me

2023-01-13 17:22 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 53b65edf57c6c45ed46fb173747452ec2d674c00<br /><br />Tip for the nest tester: delete the file `administrator/cache/autoload_psr4.php` prior testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39625">issues.joomla.org/tracker/joomla-cms/39625</a>.</sub>

2023-01-15 13:08 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 15e3454eb60342590bc7850b61fc36c492c0293c<br /><br />Based on the test instructions I am marking this as a successful test. Can't really comment on the code changes themselves<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39625">issues.joomla.org/tracker/joomla-cms/39625</a>.</sub>

2023-01-15 13:22 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 15e3454eb60342590bc7850b61fc36c492c0293c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39625">issues.joomla.org/tracker/joomla-cms/39625</a>.</sub>

2023-01-15 13:37 UTC, Quy commented on libraries/src/Editor/Editor.php
> -        $params = new Registry($plugin->params);
Remove import.

2023-01-15 15:09 UTC, laoneo commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39625">issues.joomla.org/tracker/joomla-cms/39625</a>.</sub>

2023-01-15 16:56 UTC, merged

2023-01-15 16:56 UTC, obuisard commented
Thank you Allon @laoneo!