Converts local filesystem plugin to service providers
joomla/joomla-cms pull request #39642
Opened 2023-01-16 07:17 UTC by laoneo

### Summary of Changes
Converts local filesystem plugin to service providers.

### Testing Instructions
Open the media manager.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-01-16 15:16 UTC, richard67 commented
@laoneo Unit tests are failing: https://ci.joomla.org/joomla/joomla-cms/60934/1/11 . I think it **_could_** be related to this PR.

2023-01-19 09:06 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on d080d1e62fd13b92a1afe0e510825933c7774472<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39642">issues.joomla.org/tracker/joomla-cms/39642</a>.</sub>

2023-01-22 12:53 UTC, dgrammatiko requested changes

2023-01-22 12:53 UTC, dgrammatiko commented on plugins/filesystem/local/src/Extension/Local.php
> +        $directories = $this->params->get('directories', '[{"directory": "images"}]');
```suggestion
        $directories = $this->params->get('directories', '[{"directory": "images", "thumbs": 0}]');
```

2023-01-23 10:43 UTC, dgrammatiko commented on plugins/filesystem/local/src/Extension/Local.php
> +                $adapter = new LocalAdapter($directoryPath, $directoryEntity->directory);
```suggestion
          if (!isset($directoryEntity->thumbs)) {
                     $directoryEntity->thumbs = 0;
                 }

                 $adapter = new LocalAdapter(
                     $directoryPath,
                     $directoryEntity->directory,
                     $directoryEntity->thumbs,
                     [200, 200]
                 );
```

2023-01-31 14:27 UTC, Quy commented on plugins/filesystem/local/services/provider.php
> +                $plugin     = new Local(
```suggestion
                $plugin = new Local(
```

2023-02-17 12:16 UTC, MacJoom commented
I have tested this item :white_check_mark: successfully on 085fe56197ca8f1db4a47ea15e103d8e31e15e43<br /><br />I cannot track any differences between 4.3-dev and this PR (PHP 8.1 - tested with a clone of the Digital-Peak repository)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39642">issues.joomla.org/tracker/joomla-cms/39642</a>.</sub>

2023-02-17 12:17 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 085fe56197ca8f1db4a47ea15e103d8e31e15e43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39642">issues.joomla.org/tracker/joomla-cms/39642</a>.</sub>

2023-02-17 12:23 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39642">issues.joomla.org/tracker/joomla-cms/39642</a>.</sub>

2023-02-17 17:25 UTC, merged

2023-02-17 17:26 UTC, obuisard commented
Thank you Allon @laoneo for the PR.