[RFC] Make captcha plugins use plugin events
joomla/joomla-cms pull request #39657
Opened 2023-01-17 10:16 UTC by Fedik

Pull Request for Issue #28800 .

### Summary of Changes

The patch improve Cpatcha plugins.
Now it can use a **real events,** and people stop confusing `onDisplay` (etc) callback with event.

**How this work.**
Here added a new event `onCaptchaSetup` and an Interface for `CaptchaProvider` class.
While this event the plugin should register own `CaptchaProvider` class in `CaptchaRegistry`.
The system will retrieve the requested cpatcha type from that registry and call required methods, that defined by `CaptchaProviderInterface` 

This is fully backward compatible.

Looking for feedback. 
If all good we can do the same for Editor and its Buttons.

*Techicaly now one plugin can provide multiple captcha, however for now the global configuration done per plugin.
But this can be extended in future, when need.*

### Testing Instructions

Apply patch, remove `administrator/cache/autoload_psr4.php`
Enable `recaptcha_invisible` and make sure it works.

Testing B/C:
Enable older `recaptcha` and make sure it works.

### Actual result BEFORE applying this Pull Request
All works

### Expected result AFTER applying this Pull Request
All works

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: IDK
- [ ] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: TBD
- [ ] No documentation changes for manual.joomla.org needed

2023-01-17 10:19 UTC, dgrammatiko commented
@Fedik could you also move the captcha plugin to service providers, like https://github.com/joomla/joomla-cms/pull/39639

2023-01-17 10:24 UTC, Fedik commented
Sure, will update later.

2023-01-17 10:25 UTC, laoneo commented
> @Fedik could you also move the captcha plugin to service providers, like #39639

I would do this in a separate pr to not block each other.

2023-01-17 10:26 UTC, dgrammatiko commented
> Sure, will update later.

Probably leave that for another PR. I'm waiting for the Editors, EditorsXtd version

2023-02-20 12:08 UTC, dgrammatiko requested changes

2023-02-20 12:08 UTC, dgrammatiko commented on plugins/captcha/recaptcha_invisible/src/Extension/InvisibleReCaptcha.php
> +        );
```suggestion
        $result[] = [
            Text::_('PLG_CAPTCHA_RECAPTCHA_INVISIBLE') => [
                Text::_('PLG_RECAPTCHA_INVISIBLE_PRIVACY_CAPABILITY_IP_ADDRESS'),
            ],
        ];
```

2023-02-20 12:14 UTC, laoneo commented
Why do you don't you just use plugin events and plugins, instead of having a registry, etc.? From my understanding I just want to dispatch an event and the result contains the captcha. Why all these extra classes? I would also remove the Captcha class as it is only an unnecessary static singleton.

2023-02-20 12:29 UTC, Fedik commented
> Why do you don't you just use plugin events and plugins

That what I am doing

>  From my understanding I just want to dispatch an event and the result contains the captcha.

No, that wrong. You cannot have it in that way, the event will be displatched for ALL installed captcha.

>  I would also deprecate the Captcha

This class to "rule them all", cannot be trashed.

2023-02-20 12:34 UTC, dgrammatiko commented
@laoneo the registry concept is the correct approach not only for the Captcha but also for the Editor and the Auth plugins. All these plugins, as they are right now, dispatching events within an event which architecturally is wrong. What @Fedik is doing here is normalising to single event (if I understand the code correctly, haven't step through though) which is the right thing

2023-02-20 12:50 UTC, laoneo commented
So it means you can never have multiple captchas on one site?

2023-02-20 12:59 UTC, dgrammatiko commented
> So it means you can never have multiple captchas on one site?

No, you should be able to, as you can have multiple Editors, etc. The issue that Fedik is fixing here is that all these plugins basically used to be direct callbacks up to 3.x. J4 everything was converted to events but in reality the events were wrappers to the same methods (eg Editor->init()). The registry acts as event delegation, which imo is a good approach and a solid concept that will lead to less buggy code

2023-02-20 13:01 UTC, Fedik commented
hmhm, please look the code. That to much to explain :wink: 

You can have many captcha, and many differen captchas on same page.

But you cannot use `onDisplay` event. Please follow linked issue.

2023-02-20 13:34 UTC, Fedik commented
> I would also deprecate the Captcha

On second thought, maybe we could, and use Registry directly. 
But we do not have a clear way to access a "shared" class instance.
```php
$registry = Factory::getContainer()->get(CaptchaRegistry::class);
$captcha = $registry->get('potato_captcha');

echo $captcha->display();
```
So maybe in joomla 8 :wink:
Look on the Captcha class as a comfortable helper.

2023-03-30 06:14 UTC, laoneo commented
I guess it is better to rebase this pr to the 5.0-dev branch, as it will get more attention for new features. Thanks for understanding.

2023-08-21 07:45 UTC, merged

2023-08-21 07:45 UTC, HLeithner commented
thanks