Update md5 Deprecation
joomla/joomla-cms pull request #39720
Opened 2023-01-26 18:30 UTC by harsitagarwalla187

Pull Request for Issue #39701.

### Summary of Changes
Updated md5() from passing null to parameter.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-01-27 07:48 UTC, laoneo commented
The second argument of md5 is a boolean and not a string. Why do you add a string here?

2023-01-27 08:10 UTC, alikon requested changes

2023-01-27 08:10 UTC, alikon commented on libraries/src/Cache/CacheStorage.php
> +        $this->_hash        = md5($app->get('secret'), '');
should be something like
`md5($app->get('secret', ''));`

2023-01-27 08:10 UTC, alikon commented on libraries/src/Cache/CacheStorage.php
> +        $this->_application = $options['application'] ?? md5(JPATH_CONFIGURATION, '');
this is wrong

2023-01-27 08:10 UTC, alikon commented on libraries/src/Cache/CacheStorage.php
> +        $name          = md5($this->_application . '-' . $id . '-' . $this->_language, '');
this is wrong

2023-01-30 03:14 UTC, harsitagarwalla187 commented
@alikon Please have a look. I have made the changes.

2023-01-30 07:12 UTC, laoneo approved these changes

2023-01-30 07:31 UTC, alikon approved these changes

2023-01-31 10:39 UTC, laoneo commented
I have tested this item :white_check_mark: successfully on 633cc2179e9a48353a550b78c7cd8f22551b94e6<br /><br />Tested with null as secret in configuration. Not sure how this can happen, but the fix works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39720">issues.joomla.org/tracker/joomla-cms/39720</a>.</sub>

2023-01-31 16:04 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 633cc2179e9a48353a550b78c7cd8f22551b94e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39720">issues.joomla.org/tracker/joomla-cms/39720</a>.</sub>

2023-01-31 16:04 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39720">issues.joomla.org/tracker/joomla-cms/39720</a>.</sub>

2023-02-04 09:57 UTC, merged

2023-02-04 09:57 UTC, fancyFranci commented
Thank you!