[4.3] Show message "No Media Found" for empty folder in Media Manager
joomla/joomla-cms pull request #39731
Opened 2023-01-27 19:12 UTC by rajputanuj31

Pull Request for Issue #31340

### Summary of Changes
copied changes from previous PR #39518

### Testing Instructions
Create a new folder in Media and open it (No files should be present)

### Expected Result Before PR
No message

### Expected Result After PR
A message "No Media Found" will be displayed

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-01-27 19:21 UTC, dgrammatiko requested changes

2023-01-27 19:21 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +      return ![...this.$store.getters.getSelectedDirectoryDirectories, ...this.$store.getters.getSelectedDirectoryFiles].length;
```suggestion
      return ![...this.$store.getters.getSelectedDirectoryDirectories, ...this.$store.getters.getSelectedDirectoryFiles].length
      && !this.$store.state.isLoading;
```

The compute `isEmpty` should be aware of the loading state and should not render if the data is not loaded

2023-01-27 19:26 UTC, dgrammatiko commented
@rajputanuj31 change https://github.com/joomla/joomla-cms/blob/cc4bdae6b7224d16c7aec31898fe9079e1407fd2/administrator/components/com_media/resources/scripts/components/browser/browser.vue#L20 to

```
v-if="listView === 'table' && !isEmpty"
```

change https://github.com/joomla/joomla-cms/blob/cc4bdae6b7224d16c7aec31898fe9079e1407fd2/administrator/components/com_media/resources/scripts/components/browser/browser.vue#L73 to

```
v-else-if="listView === 'grid'  && !isEmpty"
```

Also instead of 

```
<h4 v-if="isEmpty">
   {{ translate("COM_MEDIA_NO_MEDIA_FOUND") }}
 </h4>
```

we need something more to be inline with the other empty state pages, ie
![Screenshot 2023-01-27 at 20 26 03](https://user-images.githubusercontent.com/3889375/215179583-1cadf64c-13aa-4c4f-b43a-4213f32846d6.png)

2023-01-28 06:10 UTC, laoneo commented
A message is ok for now. We can do a followup with a more enhanced screen.

2023-01-28 06:20 UTC, rajputanuj31 commented
> A message is ok for now. We can do a followup with a more enhanced screen.

I have almost completed it, will make a commit soon.

2023-01-28 08:00 UTC, rajputanuj31 commented
Hey @dgrammatiko , @laoneo  Is this fine? also where can I find related documentation for this issue.

![mediano](https://user-images.githubusercontent.com/115709571/215254473-1736878f-ee34-48d8-bde4-3ef7fb3376d4.jpg)

2023-01-28 10:54 UTC, laoneo commented
Is this screen visible then for every folder which is empty? It can be that there is no documentation for it.

2023-01-28 11:01 UTC, rajputanuj31 commented
> Is this screen visible then for every folder which is empty? It can be that there is no documentation for it.

Yes it visible for every empty folders. Since no documentation for this issue so I will remove the **`Learn More`** link.

2023-01-28 11:07 UTC, dgrammatiko commented
@rajputanuj31 sorry I miss guided you. What I meant was to refactor the drop state of the drag and drop to resemble the empty state for other components in Joomla. It doesn't have to be one to one the empty state of the other components
 
![Screenshot 2023-01-28 at 12 03 41 (2)](https://user-images.githubusercontent.com/3889375/215263252-09a9a104-6fe4-4f76-8649-6385deeab44c.png)

2023-01-28 11:09 UTC, dgrammatiko commented
@rajputanuj31 also please apply the requested changes above. Thanks

2023-01-28 13:08 UTC, rajputanuj31 commented
> @rajputanuj31 also please apply the requested changes above. Thanks

Here are the changes you've asked for.
<img width="864" alt="image" src="https://user-images.githubusercontent.com/115709571/215267926-550767f0-4bc3-4664-8d85-6f10a6c22518.png">
Does this look good?

2023-01-28 21:36 UTC, Quy commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        v-else-if="listView === 'grid'  && !isEmpty"
```suggestion
        v-else-if="listView === 'grid' && !isEmpty"
```

2023-01-29 14:27 UTC, rajputanuj31 commented
@dgrammatiko , @Quy , @laoneo please review my changes. Is there any more changes I need to make.

2023-01-29 15:05 UTC, dgrammatiko commented
@rajputanuj31 personally I would go of something like

```
    <div
      v-if="isEmpty"
      class="text-center"
      style="display: grid; justify-content: center; align-content: center; height: 100%; margin-top: -1rem; color: var(--gray-200);"
    >
      <span
        class="fa-8x icon-cloud-upload upload-icon"
        aria-hidden="true"
      />
      <p>{{ translate("COM_MEDIA_DROP_FILE") }}</p>
    </div>
```
needs also 

```js
    /* The styles for the media-browser element */
    mediaBrowserStyles() {
      return {
        width: this.$store.state.showInfoBar ? '75%' : '100%',
        height: '100%',
      };
    },
```

Which results to a lighter icon/text and the icon and text are in the same position as the drag background.
Normal
![Screenshot 2023-01-29 at 16 02 53](https://user-images.githubusercontent.com/3889375/215335290-37a67cd0-84e3-48dd-b63d-9d952b6e874a.png)

On drag
![Screenshot 2023-01-29 at 16 03 02 2](https://user-images.githubusercontent.com/3889375/215335311-47d5423c-6e99-4ad1-a340-88e2060a47d3.png)

2023-01-29 16:48 UTC, rajputanuj31 commented
@dgrammatiko after applying your changes icon remains at top but I made some changes using css those I am commiting
<img width="898" alt="image" src="https://user-images.githubusercontent.com/115709571/215339619-17a2202b-2c53-4d13-bbe0-229df232a021.png">

2023-01-29 16:50 UTC, dgrammatiko commented
@rajputanuj31 did you replace also the `mediaBrowserStyles()` as I wrote above?

2023-01-29 16:51 UTC, rajputanuj31 commented
> @rajputanuj31 did you replace also the `mediaBrowserStyles()` as I wrote above?

yes

2023-01-29 16:53 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
>          width: this.$store.state.showInfoBar ? '75%' : '100%',
Add `height: '100%',` after line 127, then use the code snippet I provided and the icon will be correctly centered

2023-01-30 07:21 UTC, laoneo commented
Now we have a conflict here. Can you please check them, I guess the indentation of the tags has changed.

2023-01-30 11:08 UTC, closed without merging