Fixes various code style issues and integrate PHP CS Fixer into drone
joomla/joomla-cms pull request #39745
Opened 2023-01-30 10:10 UTC by laoneo

### Summary of Changes
The https://github.com/PHP-CS-Fixer/PHP-CS-Fixer project is another code style fixer for PHP which we have a config for since #10992 but actually never used. This pr integrates it into drone and fixes the code base, primarily adding a trailing comma on multiline arrays where phpcs has a [big weakness](https://github.com/squizlabs/PHP_CodeSniffer/issues/582).

On the other side the PHP CS Fixer [can't properly handle files where HTML syntax is mixed with PHP code](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3702#issuecomment-396717120), so it makes sense to use both projects in our CI pipeline.

This can be merged by review.

2023-01-30 10:16 UTC, HLeithner commented on administrator/templates/atum/error_login.php
> +                                        <?php // Reset the main error object to the base error?>
That looks odd

2023-01-30 10:27 UTC, laoneo commented on administrator/templates/atum/error_login.php
> +                                        <?php // Reset the main error object to the base error?>
Comes from https://cs.symfony.com/doc/rules/comment/no_trailing_whitespace_in_comment.html

2023-01-30 10:35 UTC, laoneo commented on administrator/templates/atum/error_login.php
> +                                        <?php // Reset the main error object to the base error?>
I'm excluding also layout files now

2023-01-30 22:49 UTC, HLeithner requested changes
I did a full code review on all files but only for  real changes not for linebreaks and spaces. The PR looks ok except the 10 mentioned lines.

2023-01-30 22:49 UTC, HLeithner commented on administrator/components/com_config/src/Controller/ComponentController.php
> +                // no break
hmm comments get changed to lower case? this is wrong we always start uppercase in comments

2023-01-30 22:49 UTC, HLeithner commented on administrator/components/com_content/src/Controller/ArticleController.php
> +                'link' => $link, ]);
I'm suprised that this works for phpcs

2023-01-30 22:49 UTC, HLeithner commented on administrator/components/com_users/src/Model/UsersModel.php
> +                // no break
shouldn't be lowercase

2023-01-30 22:49 UTC, HLeithner commented on components/com_contact/src/Controller/DisplayController.php
> +            'lang'                => 'CMD', ];
this array is strange also the ending ] is not on a new line

2023-01-30 22:49 UTC, HLeithner commented on components/com_newsfeeds/src/Controller/DisplayController.php
> +                                'filter_order' => 'CMD', 'filter_order_Dir' => 'CMD', 'lang' => 'CMD', ];
looks odd

2023-01-30 22:49 UTC, HLeithner commented on libraries/src/Form/Field/TransitionField.php
> +            HTMLHelper::_('select.option', '', Text::_($workflowName)), ]];
multiline array seems to be a strange definition...

2023-01-30 22:49 UTC, HLeithner commented on libraries/src/Form/FormField.php
> +                // no break
uppercase

2023-01-30 22:49 UTC, HLeithner commented on libraries/src/Form/FormField.php
> +                // no break
Uppercase

2023-01-30 22:49 UTC, HLeithner commented on tests/Unit/Libraries/Cms/Object/CMSObjectTest.php
> +            'property2'         => 5, ]);
Looks broken

2023-01-30 22:49 UTC, HLeithner commented on tests/Unit/Libraries/Cms/Uri/UriTest.php
> +            'v' => 45, ];
looks odd

2023-01-31 08:03 UTC, laoneo commented on administrator/components/com_config/src/Controller/ComponentController.php
> +                // no break
Fixed with hardcoded no break comment in the cs config

2023-01-31 08:05 UTC, laoneo commented on administrator/components/com_content/src/Controller/ArticleController.php
> +                'link' => $link, ]);
Corrected it in last commit, but this was also not detected by the CS fixer like in the display controllers

2023-01-31 08:05 UTC, laoneo commented on administrator/components/com_users/src/Model/UsersModel.php
> +                // no break
See comment above

2023-01-31 08:05 UTC, laoneo commented on components/com_contact/src/Controller/DisplayController.php
> +            'lang'                => 'CMD', ];
Yes I know, but both fixers are accepting it

2023-01-31 08:06 UTC, laoneo commented on components/com_newsfeeds/src/Controller/DisplayController.php
> +                                'filter_order' => 'CMD', 'filter_order_Dir' => 'CMD', 'lang' => 'CMD', ];
Same as above

2023-01-31 08:07 UTC, laoneo commented on libraries/src/Form/Field/TransitionField.php
> +            HTMLHelper::_('select.option', '', Text::_($workflowName)), ]];
It's correct, it is on multiple lines, but fixed it manually

2023-01-31 08:07 UTC, laoneo commented on libraries/src/Form/FormField.php
> +                // no break
See comment above

2023-01-31 08:07 UTC, laoneo commented on libraries/src/Form/FormField.php
> +                // no break
See comment above

2023-01-31 08:07 UTC, laoneo commented on tests/Unit/Libraries/Cms/Object/CMSObjectTest.php
> +            'property2'         => 5, ]);
Put the closing on a new line

2023-01-31 08:07 UTC, laoneo commented on tests/Unit/Libraries/Cms/Uri/UriTest.php
> +            'v' => 45, ];
Same as above

2023-01-31 10:20 UTC, merged

2023-01-31 10:20 UTC, HLeithner commented
Thanks