Closing create modal
joomla/joomla-cms pull request #39793
Opened 2023-02-05 09:13 UTC by Kaushik1216

Pull Request for Issue # .39263

### Summary of Changes
Closing Create folder Modal On error while creating folder

### Testing Instructions
Create a folder as mention in issue like folder with name ( joomla..... )

### Actual result BEFORE applying this Pull Request

The create modal not closed to show error in case of error occuring while creating folder

### Expected result AFTER applying this Pull Request

create modal closed to show error

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-02-05 17:41 UTC, dgrammatiko commented
@Kaushik1216 around 10 lines before the line you've added there are couple of todos that should point you to the needed changes.
Essentially what your code is doing is closing the modal always although we should keep the modal open when there's an error, mark the field as invalid and also render (inside the modal) the error message. In short you're changing the workflow here and introducing more clicks to complete a task if there's an error.

2023-02-06 05:13 UTC, Kaushik1216 commented
@dgrammatiko yes you are right ,so what can be best way to solve this issue .One way I think is ,when undesire folder name come,input field should become red and some text like invalid folder name above input field can be shown.

2023-02-11 13:41 UTC, Kaushik1216 commented
@dgrammatiko  Please check this changes this  will do as follow .

https://user-images.githubusercontent.com/100058812/218261098-3c7dbf15-f020-4605-8e28-782acf19b5ef.mp4

2023-02-11 13:53 UTC, dgrammatiko commented
> Please check this changes this will do as follow .

There are many more cases that Joomla (the PHP side) will not accept a name as valid, so somehow you need to check for all these.

2023-02-11 13:58 UTC, Kaushik1216 commented
> > Please check this changes this will do as follow .
> 
> There are many more cases that Joomla (the PHP side) will not accept a name as valid, so somehow you need to check for all these.

Ok ,then please provide me those cases I will do similiar things for all cases

2023-02-11 13:59 UTC, dgrammatiko commented
> Ok ,then please provide me those cases I will do similiar things for all cases

Dude if I have to do the research then I could as well do the PR...

2023-02-11 14:21 UTC, Kaushik1216 commented
> > Ok ,then please provide me those cases I will do similiar things for all cases
> 
> Dude if I have to do the research then I could as well do the PR...

Hmm, Ok then I will do research and find some more constraint

2023-02-12 09:11 UTC, Kaushik1216 commented
Error show if fiolder name already exist in directory as folder or file name

error show as follows

![1createfolderfileexisterror](https://user-images.githubusercontent.com/100058812/218302352-aad6f513-5a48-42f5-b54f-429b8d37fe4c.png)

2023-02-12 09:12 UTC, Kaushik1216 commented
@dgrammatiko  Is I am doing right for multiple case handling ?

2023-02-14 08:42 UTC, Kaushik1216 commented
AS I notice php side only accept folder name which contain only Alphanumeric,underscore(_) ,period ( . ) and hyphen ( - ).
if you include any other charachater other than this php remove all other character from folder name .
Problem is that if you have a folder name for example ss and you attempt to try create folder with name s@s then you not get any error and folder also not created because php remove @ from folder name and ss result new folder name which is already present their and bad thing is that user also get a success msg Folder created .

2023-02-14 08:45 UTC, Kaushik1216 commented
the only one error That I think should come from php side is when user not install INTL and ICONV php extension and writing non ascii character in folder name should we close modal for this error ?

2023-02-17 12:36 UTC, dgrammatiko requested changes

2023-02-17 12:36 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/modals/create-folder-modal.vue
> +      const directories = this.$store.getters.getSelectedDirectoryDirectories
If you have to add an eslint flag to overcome the no side effects that’s a very good indication that the code is problematic! Basically DO NOT mutate items is the clue here!

2023-02-17 12:38 UTC, dgrammatiko commented
Please rebase this to 4.3!

2023-02-17 12:41 UTC, dgrammatiko commented
Lastly the media manager has the concept of adapters, ie supporting different online storage solutions (Amazon s3, Dropbox, etc). Therefore the checks here should cover all these options…

2023-02-17 13:39 UTC, Kaushik1216 commented on administrator/components/com_media/resources/scripts/components/modals/create-folder-modal.vue
> +      const directories = this.$store.getters.getSelectedDirectoryDirectories
got it

2023-02-17 13:42 UTC, Kaushik1216 commented
> Please rebase this to 4.3!

I think rebaseing this pr with 4.3 will increse work more that also occure in my no search result pr .
So I am creating new Pr for 4.3 branch .Should I closed it then ?

2023-02-17 14:21 UTC, Kaushik1216 commented
closing by creating another Pr #39878 please refer this

2023-02-17 14:21 UTC, closed without merging