No search result found msg in media
joomla/joomla-cms pull request #39819
Opened 2023-02-07 20:36 UTC by Kaushik1216

Pull Request for Issue # .
### Help Needed !
I do not know how add language variable in joomla .So I just used put any other language .I want **COM_MEDIA_NO_SEARCH_RESULT="Info No Matching Results "** add on language that is used to display when no result found.I try by putting this line in com_media.ini in adminstartor language file but unable to access it in browser.vue ,Please Guide me then I will make chages in this pr for desire output.
Thanks in advanced
### Summary of Changes

ADD a messge that will display when no result found on searching in media manager

### Testing Instructions

Search in media manager

### Actual result BEFORE applying this Pull Request
No message shown if no result match .

### Expected result AFTER applying this Pull Request
A message will shown if result not match with search

https://user-images.githubusercontent.com/100058812/217358884-21b1d8f0-b96c-451a-8b51-c88b9b9723c9.mp4

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-02-08 07:34 UTC, rajputanuj31 commented
To add add language variable in joomla you have to add your text in 3 files. 
`administrator/components/com_media/tmpl/media/default_texts.php`
`administrator/language/en-GB/com_media.ini`
`language/en-GB/com_media.ini`
Add your text in alpha oreder.

2023-02-08 09:59 UTC, Kaushik1216 commented
Now  msg is change to this 

![search](https://user-images.githubusercontent.com/100058812/217497099-e523e737-9b2d-48ae-b606-688b58d836bf.png)

But unable to understand drone ci error check if anyone understand please tell me

2023-02-08 12:47 UTC, dgrammatiko commented
@Kaushik1216 please rebase your PR on 4.3-dev as it's a new feature and also in the 4.3-dev branch there are more changes that will collide with anything you're doing here and make it very hard hard to up merge the changes.

2023-02-08 17:23 UTC, sandewt commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +       <div
Have you looked here for some inspiration yet?

https://github.com/joomla/joomla-cms/blob/763dc9c35ac2d2e757bf9a4bbcad4ba3d988e755/administrator/components/com_actionlogs/tmpl/actionlogs/default.php#L38-L41

2023-02-08 18:21 UTC, Kaushik1216 commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +       <div
NO .I just look others translate in browser.vue

2023-02-08 19:09 UTC, Kaushik1216 commented
@dgrammatiko Sorry but I don't know how  to rebase my PR to 4.3 because my fork not have 4.3 branch
What I can do then?

2023-02-08 19:20 UTC, dgrammatiko commented
Next to the title of the PR there's an Edit button. When you click it there's an option to change the base Branch, select 4.3-dev. Then in your local setup just fetch/pull and you're good to go. Probably things need to be changed as the components have already differences...

2023-02-09 10:18 UTC, sandewt commented
The following error message appears when I try to apply the patch:

![com_medioa-zoeken](https://user-images.githubusercontent.com/9271775/217783981-c5304fc8-56e6-4e50-8949-deaa626c303f.png)

2023-02-09 10:22 UTC, brianteeman commented
@sandewt you can't use the patchtester component for this

2023-02-09 10:25 UTC, dgrammatiko commented
The PR at the current state is wrong as it is undoing most of the changes in the 4.3 branch...
@Kaushik1216 please restore the 4.3-dev browser.vue from here: https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_media/resources/scripts/components/browser/browser.vue and then add the changes on top of that.

2023-02-09 13:28 UTC, Kaushik1216 commented
@dgrammatiko I resolve conflict .Please check why build Check is falling

2023-02-09 13:36 UTC, dgrammatiko commented
Run `npm run lint:js` and you will see what's wrong. Also read https://github.com/joomla/joomla-cms/tree/4.2-dev/build

2023-02-09 14:11 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +template>
```suggestion
<template>
```

2023-02-09 14:14 UTC, Kaushik1216 commented
This is what I am getting

![errormedia](https://user-images.githubusercontent.com/100058812/217836837-d89154bf-7981-4f73-ad3c-2742fc2e2e80.png)

2023-02-09 14:19 UTC, sandewt commented on administrator/components/com_media/src/Controller/ApiController.php
> +            // A folder needs to be created
Have you added this code? Seems to be from another issue.

2023-02-09 14:20 UTC, dgrammatiko commented
@Kaushik1216 delete your node_modules folder and then run `npm install`

2023-02-09 14:27 UTC, Kaushik1216 commented on administrator/components/com_media/src/Controller/ApiController.php
> +            // A folder needs to be created
no I don't add it's alredy their

2023-02-09 14:28 UTC, dgrammatiko commented on administrator/components/com_media/src/Controller/ApiController.php
> +            // A folder needs to be created
You have to revert ALL these changes!

2023-02-09 14:39 UTC, Kaushik1216 commented
> @Kaushik1216 delete your node_modules folder and then run `npm install`
> 
> Also you need to revert the changes on all the unrelated files
> 
> And finally you have to restore all the deleted empty lines in the browser.vue

thx by doing npm install all error resolve ? And other than browser.vue I just  add spaces in some line which is shown by build ci  joomla-cms/administrator/components/com_media/resources/scripts/components/browser/table/table.vue

2023-02-09 14:43 UTC, dgrammatiko requested changes

2023-02-09 14:43 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        <div
This will never be reached as in line 49 you have `v-if="(listView === 'grid' && !isEmpty && !isEmptySearch)"` which means that the parent div will never be rendered for non empty search! So just delete it.

2023-02-09 14:44 UTC, dgrammatiko requested changes

2023-02-09 14:44 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +      class="w-75 text-dark p-2 m-4"
Change the class to `class="alert alert-info"` and remove the inline style in the line below

2023-02-09 14:46 UTC, dgrammatiko requested changes

2023-02-09 14:46 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +      </span>
```suggestion
      <span class="fa fa-info-circle m-2"
          aria-hidden="true"
        />
      <p class="ms-2">{{ translate('COM_MEDIA_NO_SEARCH_RESULT') }}</p>
```

2023-02-09 14:49 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:49 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:49 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:49 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:49 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:49 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> -
Restore the empty line

2023-02-09 14:51 UTC, dgrammatiko commented on administrator/components/com_menus/src/Model/MenusModel.php
> +     * @since   4.2.0
Revert

2023-02-09 14:51 UTC, dgrammatiko commented on libraries/src/Cache/CacheStorage.php
> +        $this->_hash        = md5($app->get('secret', ''));
Revert

2023-02-09 14:51 UTC, dgrammatiko commented on libraries/src/Filesystem/File.php
> +            Log::add(Text::sprintf('JLIB_FILESYSTEM_ERROR_FILE_FIND_COPY', __METHOD__, $src), Log::WARNING, 'jerror');
Revert

2023-02-09 14:51 UTC, dgrammatiko commented on libraries/src/Form/Field/ModuleorderField.php
> +     * @since  4.2.7
Revert

2023-02-09 14:51 UTC, dgrammatiko commented on modules/mod_login/tmpl/default.php
> +                    <input type="checkbox" name="remember" class="form-check-input" value="yes" id="form-login-input-remember-<?php echo $module->id; ?>">
Revert

2023-02-09 19:22 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        <div
Why do you have to repeat this twice? You have this rendered a few lines above already

2023-02-09 19:34 UTC, Kaushik1216 commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        <div
sorry I just add this line seprate for both grid and table .Now I understand what you are telling in conversion .

2023-02-09 19:56 UTC, dgrammatiko requested changes

2023-02-09 19:56 UTC, dgrammatiko commented on modules/mod_login/tmpl/default.php
> +                        <label class="form-check-label">
Remove the extra spaces here

2023-02-09 19:56 UTC, dgrammatiko commented on modules/mod_login/tmpl/default.php
> +                            <input type="checkbox" name="remember" class="form-check-input" value="yes">
Remove the extra spaces here

2023-02-15 21:09 UTC, Quy commented
Please fix markup.

In Media:
![39819-media](https://user-images.githubusercontent.com/368084/219162079-cd8f6064-b63b-48e2-98f3-51021c7d3b68.jpg)

In Articles:
![39819-article](https://user-images.githubusercontent.com/368084/219162141-46bd4b49-6dc9-4d56-b9da-c89bd45330c6.jpg)

2023-02-16 06:42 UTC, sandewt commented on modules/mod_login/tmpl/default.php
> +                            <input type="checkbox" name="remember" class="form-check-input" value="yes">
Is this correct? What does `mod_login` have to do with `com_media`?

2023-02-16 12:05 UTC, Kaushik1216 commented
> Match markup.
> 
> https://github.com/joomla/joomla-cms/blob/23de0b11d843747a6a747083a4294c7f59a58fa3/administrator/components/com_content/tmpl/articles/default.php#L80-L83
> 
> In Media: ![39819-media](https://user-images.githubusercontent.com/368084/219162079-cd8f6064-b63b-48e2-98f3-51021c7d3b68.jpg)
> 
> In Articles: ![39819-article](https://user-images.githubusercontent.com/368084/219162141-46bd4b49-6dc9-4d56-b9da-c89bd45330c6.jpg)

Thanks for testing ,I made change in pr please check again .

2023-02-16 12:53 UTC, sandewt commented
> Thanks for testing ,I made change in pr please check again .

No possible yet: npm ERR!

2023-02-16 13:20 UTC, Kaushik1216 commented
> > Thanks for testing ,I made change in pr please check again .
> 
> No possible yet: npm ERR!



> @Kaushik1216 delete your node_modules folder and then run `npm install`
> 
> Also you need to revert the changes on all the unrelated files
> 
> And finally you have to restore all the deleted empty lines in the browser.vue



> > Thanks for testing ,I made change in pr please check again .
> 
> No possible yet: npm ERR!

try by deleting nodemodules and run npm installl as suggest by @dgrammatiko  above

2023-02-16 13:23 UTC, dgrammatiko commented
@Kaushik1216 no, deleting the node_modules is not the case. Your PR at the end of this page says that:

`This branch is out-of-date with the base branch`

You have to update the the base branch, google it

2023-02-16 13:56 UTC, Kaushik1216 commented
branch updated

2023-02-16 14:08 UTC, sandewt commented
> branch updated

Sorry, still npm ERR!

2023-02-16 14:20 UTC, Kaushik1216 commented
@Quy can you please test again if you also faced same npm error than error comes from my side and vice versa

2023-02-16 16:07 UTC, Quy commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('COM_MEDIA_NO_SEARCH_RESULT') }}
Use `JGLOBAL_NO_MATCHING_RESULTS`, thus, no need to add a new language string.

2023-02-16 16:07 UTC, Quy commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +          aria-hidden="true"
```suggestion
        class="fa fa-info-circle"
        aria-hidden="true"
```

2023-02-16 16:30 UTC, Kaushik1216 commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('COM_MEDIA_NO_SEARCH_RESULT') }}
done

2023-02-16 16:30 UTC, Kaushik1216 commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +          aria-hidden="true"
done

2023-02-16 16:53 UTC, sandewt commented
@Kaushik1216 

This branch is (still) out-of-date with the base branch

2023-02-16 19:41 UTC, Kaushik1216 commented
@Quy  @sandewt  I don't know why build is killing in this pr I create another Pr #39872   for this feature

2023-02-16 19:50 UTC, Kaushik1216 commented
> @Quy @sandewt I don't know why build is killing in this pr I create another Pr #39872 for this feature

please test it thanks is advance

2023-02-17 04:26 UTC, Kaushik1216 commented
closing as another pr created

2023-02-17 04:26 UTC, closed without merging