[4.3]Corrected different multi-select behavior in media manager.
joomla/joomla-cms pull request #39824
Opened 2023-02-08 17:45 UTC by rajputanuj31

Summary of Changes
Multi select without using shift key

### Testing Instructions
Open Media
Try to Select media manager files.

### Actual result BEFORE applying this Pull Request
You can not select multiple items without holding the shift key.

### Expected result AFTER applying this Pull Request
You can select multiple items by holding `ctrl key` & clicking on items.
You can also select all files between two selected files by holding `shift key`.

2023-02-08 17:56 UTC, richard67 commented
@rajputanuj31 When you create a PR, why do you delete stuff which is prepared in the description, like e.g. the "Pull request for issue #..." at the top, or the section about documentation, which requires the right check boxes to be checked? We do not have that stuff for nothing in our pull request description template. So please add the `Pull Request for issue #33637 ` to the top so we know for which issue the pull request is made, and add back the documentation section and check the right check boxes. Thanks in advance.

2023-02-08 18:00 UTC, brianteeman commented
There are unrelated files in this commit :(

2023-02-08 18:37 UTC, rajputanuj31 commented
> There are unrelated files in this pull request :(

Fixed.

2023-02-09 10:20 UTC, dgrammatiko requested changes

2023-02-09 10:20 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
> +        if ((event.shiftKey || event.keyCode === 13)) {
Move both `startIndex` and `endIndex` here.
Also rename the variables to `startIndex` `currentIndex`

Would be nice to refactor the `for` to `forEach`, eg 

```js
this.$store.getters.getSelectedDirectoryContents. slice(someIndex).forEach((idx) => this.$store.commit(types.SELECT_BROWSER_ITEM, this.$store.getters.getSelectedDirectoryContents[idx]));

```

Check MDN slice() https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
and forEach() https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2023-02-09 12:24 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
> +        if ((event.shiftKey || event.keyCode === 13)) {
@dgrammatiko I have made changes as you suggested. Please review it.

2023-02-09 12:46 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
>          } else if ((event.ctrlKey || event.keyCode === 17)) {
One more thing, MacOS should use the `MetaKey`. You could use the code from my PR #39679, eg:

```
else if (event[/Mac|Mac OS|MacIntel/gi.test(window.navigator.userAgent) ? 'metaKey ' : 'ctrlKey'] || event.keyCode === 17) {
``

2023-02-09 13:04 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
>          } else if ((event.ctrlKey || event.keyCode === 17)) {
Should I have to do same for `shift key` In Line 152. or only for `ctrl key`??

2023-02-09 13:05 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
>          } else if ((event.ctrlKey || event.keyCode === 17)) {
Shift is the same on both platforms, so no

2023-02-09 13:14 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
>          } else if ((event.ctrlKey || event.keyCode === 17)) {
Ok thanks. I have made changes.

2023-02-09 15:04 UTC, dgrammatiko approved these changes

2023-02-09 15:08 UTC, dgrammatiko commented
@rajputanuj31 can you check if the `rtl` languages need any adjustment? Other than that this seems ready for some testing

2023-02-09 15:27 UTC, rajputanuj31 commented
> @rajputanuj31 can you check if the `rtl` languages need any adjustment? Other than that this seems ready for some testing

it's working fine.

2023-02-10 07:39 UTC, laoneo commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
> +        if ((event.shiftKey || event.keyCode === 13)) {
Please remove the double ((

2023-02-10 07:40 UTC, laoneo commented
Please add some inline comments, so we can follow your code. Actually it is hard to understand what exactly is going on with all these if else conditions. I would also recommend that you do early return instead of so many else statements.

2023-02-10 08:39 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
> +        if ((event.shiftKey || event.keyCode === 13)) {
Fixed.

2023-02-10 08:59 UTC, brianteeman commented
I have tested this and it works perfectly apart from on the first page which is very weird. 

In this video I am shift clicking on the last image and then on the image before it and you will see that a third image is also selected. I can't replicate that on any other screen.

![shift](https://user-images.githubusercontent.com/1296369/218047937-d0e871f2-18c5-45cd-abc0-db348916e401.gif)

![shift2](https://user-images.githubusercontent.com/1296369/218048239-61a454e6-568f-46de-8ce9-1aa2f8ee7001.gif)

2023-02-10 09:10 UTC, rajputanuj31 commented
> I have tested this and it works perfectly apart from on the first page which is very weird.
> 
> In this video I am shift clicking on the last image and then on the image before it and you will see that a third image is also selected. I can't replicate that on any other screen.

@brianteeman It's working perfectly in my local machine. what should I do now?

2023-02-10 09:11 UTC, brianteeman commented
do you have exactly the same images as I have?

2023-02-10 09:12 UTC, rajputanuj31 commented
> do you have exactly the same images as I have?

Yes I do have the same images.

2023-02-10 09:19 UTC, brianteeman commented
> > do you have exactly the same images as I have?
> 
> Yes I do have the same images.

all three?

2023-02-10 09:26 UTC, rajputanuj31 commented
> > > do you have exactly the same images as I have?
> > 
> > 
> > Yes I do have the same images.
> 
> all three?

Yes now I am also facing the same issue. I am trying to debug it.

2023-02-10 10:06 UTC, rajputanuj31 commented
@brianteeman @dgrammatiko @laoneo I found the reason for this behavior.
In Joomla media items storing index is different from index of item's being shown on browser section.
When an image or dir. name is starting with capital letter then it's storing index in array is different from what it's being displayed.
<img width="903" alt="image" src="https://user-images.githubusercontent.com/115709571/218062939-d1da25fb-2b65-4a20-9267-0c8c519b71f2.png">
Carefully observe the index of `Photo.jpg` is stored as index of `4` but it's being displayed as if it is `5th` index.
How do I get the Index's of the items being viewed in browser????

2023-02-10 10:21 UTC, dgrammatiko commented
> How do I get the Index's of the items being viewed in browser????

I intentionally renamed the `items` to `localItems` to make it obvious that the items in the browser component are localised, eg reordered. In short use the `localItems`: https://github.com/joomla/joomla-cms/blob/7f7e2324b62562b8872142cc68d6422a30a2dd62/administrator/components/com_media/resources/scripts/components/browser/browser.vue#L112

2023-02-10 13:24 UTC, rajputanuj31 commented
@brianteeman @dgrammatiko @laoneo I have made some changes Please review it.

2023-02-10 13:35 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 005b0d66c22d32be522081167351a9fe190f717e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39824">issues.joomla.org/tracker/joomla-cms/39824</a>.</sub>

2023-02-10 13:53 UTC, dgrammatiko commented
@rajputanuj31 could you do a small refactoring here since we have the same code in 2 files.

Create a new file `administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js`


<details>
<summary>with contents: </summary>

```js
export default {
  /**
   * Handle the click event
   * @param event
   * @param ctx  the context
   */
  onItemClick: (event, ctx) => {
    if (ctx.item.path && ctx.item.type === 'file') {
      window.parent.document.dispatchEvent(
        new CustomEvent('onMediaFileSelected', {
          bubbles: true,
          cancelable: false,
          detail: {
            path: ctx.item.path,
            thumb: ctx.item.thumb,
            fileType: ctx.item.mime_type ? ctx.item.mime_type : false,
            extension: ctx.item.extension ? ctx.item.extension : false,
            width: ctx.item.width ? ctx.item.width : 0,
            height: ctx.item.height ? ctx.item.height : 0,
          },
        }),
      );
    }

    if (ctx.item.type === 'dir') {
      window.parent.document.dispatchEvent(
        new CustomEvent('onMediaFileSelected', {
          bubbles: true,
          cancelable: false,
          detail: {},
        }),
      );
    }

    // Handle clicks when the item was not selected
    if (!ctx.isSelected()) {
      // Handle clicks when shift key was pressed
      if (event.shiftKey || event.keyCode === 13) {
        const currentIndex = ctx.localItems.indexOf(ctx.$store.state.selectedItems[0]);
        const endindex = ctx.localItems.indexOf(ctx.item);
        // Handle selections from up to down
        if (currentIndex < endindex) {
          ctx.localItems.slice(currentIndex, endindex + 1)
            .forEach((element) => ctx.$store.commit(types.SELECT_BROWSER_ITEM, element));
        // Handle selections from down to up
        } else {
          ctx.localItems.slice(endindex, currentIndex)
            .forEach((element) => ctx.$store.commit(types.SELECT_BROWSER_ITEM, element));
        }
        // Handle clicks when ctrl key was pressed
      } else if (event[/Mac|Mac OS|MacIntel/gi.test(window.navigator.userAgent) ? 'metaKey ' : 'ctrlKey'] || event.keyCode === 17) {
        ctx.$store.commit(types.SELECT_BROWSER_ITEM, ctx.item);
      } else {
        ctx.$store.commit(types.UNSELECT_ALL_BROWSER_ITEMS);
        ctx.$store.commit(types.SELECT_BROWSER_ITEM, ctx.item);
      }
      return;
    }
    ctx.$store.dispatch('toggleBrowserItemSelect', ctx.item);
    window.parent.document.dispatchEvent(
      new CustomEvent('onMediaFileSelected', {
        bubbles: true,
        cancelable: false,
        detail: {},
      }),
    );

    // If more than one item was selected and the user clicks again on the selected item,
    // he most probably wants to unselect all other items.
    if (ctx.$store.state.selectedItems.length > 1) {
      ctx.$store.commit(types.UNSELECT_ALL_BROWSER_ITEMS);
      ctx.$store.commit(types.SELECT_BROWSER_ITEM, ctx.item);
    }
  },
}
```

</details>

Then change the `handleClick` method in the item https://github.com/joomla/joomla-cms/pull/39824/files#diff-68de052c5527b63cd4fa16f4872cdeca97b20ac05389de587af9c8b14a698d50R126-R193 and 'onClick' in the row https://github.com/joomla/joomla-cms/pull/39824/files#diff-e3f0552dc23736cd5bd70c04dab063ad0c26e284be8542e0dad16b04d4c5da21R104-R162 to

```js
    handleClick(event, item) {
      return onItemClick(event, item);
    },
```

and 

```js
    onClick(event, item) {
      return onItemClick(event, item);
    },
```
respectively. You need to import the `onItemClick` as usual: `import { onItemClick } from '../utils/utils.es6.js';`

2023-02-10 14:06 UTC, rajputanuj31 commented
@dgrammatiko Please have a look.

2023-02-10 14:08 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
>       */
Add a `* @param ctx  the current context`

2023-02-10 14:08 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/table/row.vue
>       */
Add a * @param ctx  the current context

2023-02-10 14:09 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +}
Add an empty line at the end of the file

2023-02-10 14:10 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/table/row.vue
> +import { onItemClick } from '../utils/utils.es6.js';
This should be `import { onItemClick } from '../../utils/utils.es6.js';` ?

2023-02-10 14:38 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/table/row.vue
> +import { onItemClick } from '../utils/utils.es6.js';
I think this is correct.

2023-02-10 14:39 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +}
done

2023-02-10 15:15 UTC, rajputanuj31 commented
@dgrammatiko I have made all changes as you suggest. Is everything looks fine??

2023-02-10 15:16 UTC, dgrammatiko commented
> Is everything looks fine??

Nope, the build is broken, check the npm part on the CI: https://ci.joomla.org/joomla/joomla-cms/61729

2023-02-10 15:32 UTC, rajputanuj31 commented
@dgrammatiko I found these errors when I run `npm run lint:js -- --fix`
<img width="647" alt="image" src="https://user-images.githubusercontent.com/115709571/218130798-391e2d93-f8fe-419e-baa4-b4f682b603af.png">

2023-02-10 15:50 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +import * as types from '../../../store/mutation-types.es6';
The contents should be:

```js
import * as types from '../../../store/mutation-types.es6';

/**
 * Handle the click event
 * @param event
 * @param ctx  the context
 */
export default function onItemClick(event, ctx) {
  if (ctx.item.path && ctx.item.type === 'file') {
    window.parent.document.dispatchEvent(
      new CustomEvent('onMediaFileSelected', {
        bubbles: true,
        cancelable: false,
        detail: {
          path: ctx.item.path,
          thumb: ctx.item.thumb,
          fileType: ctx.item.mime_type ? ctx.item.mime_type : false,
          extension: ctx.item.extension ? ctx.item.extension : false,
          width: ctx.item.width ? ctx.item.width : 0,
          height: ctx.item.height ? ctx.item.height : 0,
        },
      }),
    );
  }

  if (ctx.item.type === 'dir') {
    window.parent.document.dispatchEvent(
      new CustomEvent('onMediaFileSelected', {
        bubbles: true,
        cancelable: false,
        detail: {},
      }),
    );
  }

  // Handle clicks when the item was not selected
  if (!ctx.isSelected()) {
    // Handle clicks when shift key was pressed
    if (event.shiftKey || event.keyCode === 13) {
      const currentIndex = ctx.localItems.indexOf(ctx.$store.state.selectedItems[0]);
      const endindex = ctx.localItems.indexOf(ctx.item);
      // Handle selections from up to down
      if (currentIndex < endindex) {
        ctx.localItems.slice(currentIndex, endindex + 1)
          .forEach((element) => ctx.$store.commit(types.SELECT_BROWSER_ITEM, element));
      // Handle selections from down to up
      } else {
        ctx.localItems.slice(endindex, currentIndex)
          .forEach((element) => ctx.$store.commit(types.SELECT_BROWSER_ITEM, element));
      }
      // Handle clicks when ctrl key was pressed
    } else if (event[/Mac|Mac OS|MacIntel/gi.test(window.navigator.userAgent) ? 'metaKey' : 'ctrlKey'] || event.keyCode === 17) {
      ctx.$store.commit(types.SELECT_BROWSER_ITEM, ctx.item);
    } else {
      ctx.$store.commit(types.UNSELECT_ALL_BROWSER_ITEMS);
      ctx.$store.commit(types.SELECT_BROWSER_ITEM, ctx.item);
    }
    return;
  }
  ctx.$store.dispatch('toggleBrowserItemSelect', ctx.item);
  window.parent.document.dispatchEvent(
    new CustomEvent('onMediaFileSelected', {
      bubbles: true,
      cancelable: false,
      detail: {},
    }),
  );

  // If more than one item was selected and the user clicks again on the selected item,
  // he most probably wants to unselect all other items.
  if (ctx.$store.state.selectedItems.length > 1) {
    ctx.$store.commit(types.UNSELECT_ALL_BROWSER_ITEMS);
    ctx.$store.commit(types.SELECT_BROWSER_ITEM, ctx.item);
  }
}

```

2023-02-10 15:51 UTC, dgrammatiko requested changes

2023-02-10 15:51 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/table/row.vue
> +    onClick(event, item) {
```suggestion
    onClick(event) {
```

2023-02-10 15:51 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/table/row.vue
> +      return onItemClick(event, item);
```suggestion
      return onItemClick(event, this);
```

2023-02-10 15:51 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
> +    handleClick(event, item) {
```suggestion
    handleClick(event) {
```

2023-02-10 15:51 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
> +      return onItemClick(event, item);
```suggestion
      return onItemClick(event, this);
```

2023-02-10 16:01 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +import * as types from '../../../store/mutation-types.es6';
Done

2023-02-10 16:09 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/table/row.vue
> +     * @param ctx the current context
```suggestion
```

2023-02-10 16:09 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
> +     * @param ctx the current context
```suggestion
```

2023-02-10 16:26 UTC, rajputanuj31 commented
@brianteeman @dgrammatiko Please test it. On my local machine it's working perfectly.

2023-02-11 10:14 UTC, rajputanuj31 commented
@dgrammatiko Please have a look. Is now everything looks correct?

2023-02-16 22:28 UTC, dgrammatiko approved these changes

2023-02-16 22:29 UTC, dgrammatiko commented
@laoneo could you also review this one?

2023-02-17 05:46 UTC, laoneo commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +  if (!ctx.isSelected()) {
This whole block needs to be simplified. It can be done when the conditions are inverted. I was thinking something like (please double check if the conditions are still correct, as I didn't test it):

```
  if (!ctx.isSelected()) {
    // Handle clicks when ctrl key was pressed
    if (event[/Mac|Mac OS|MacIntel/gi.test(window.navigator.userAgent) ? 'metaKey' : 'ctrlKey'] || event.keyCode === 17) {
      ctx.$store.commit(types.SELECT_BROWSER_ITEM, ctx.item);

      return;
    }

    // Handle clicks when shift key was pressed
    if (!event.shiftKey && event.keyCode !== 13) {
      ctx.$store.commit(types.UNSELECT_ALL_BROWSER_ITEMS);
      ctx.$store.commit(types.SELECT_BROWSER_ITEM, ctx.item);

      return;
    }

    const currentIndex = ctx.localItems.indexOf(ctx.$store.state.selectedItems[0]);
    const endIndex = ctx.localItems.indexOf(ctx.item);
    // Handle selections from up to down
    if (currentIndex < endIndex) {
      ctx.localItems.slice(currentIndex, endIndex + 1).forEach((element) => ctx.$store.commit(types.SELECT_BROWSER_ITEM, element));

      return;
    }

    // Handle selections from down to up
    ctx.localItems.slice(endIndex, currentIndex).forEach((element) => ctx.$store.commit(types.SELECT_BROWSER_ITEM, element));

    return;
  }
```

2023-02-17 11:03 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +  if (!ctx.isSelected()) {
@laoneo I have made changes as you suggested. In my local machine it's working fine.
Please Review it.

2023-02-17 11:31 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +  }
```suggestion
  }

```

2023-02-17 12:03 UTC, laoneo commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +  if (!ctx.isSelected()) {
I hope you did understand the changes. What is better now?

2023-02-17 12:09 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +  if (!ctx.isSelected()) {
Yes the new one is better, it's easy to understand.
thanks for the recommending changes.

2023-02-17 12:12 UTC, rajputanuj31 commented on administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js
> +  if (!ctx.isSelected()) {
Also less number of `if-else` conditions.

2023-02-17 17:48 UTC, rajputanuj31 commented
@dgrammatiko @laoneo @brianteeman please test the PR.

2023-06-15 05:22 UTC, rajputanuj31 commented
Hey @laoneo @dgrammatiko @brianteeman @Hackwar I think this PR is ready so please test it. If PR is not ready please leave a comment.

2023-09-15 06:29 UTC, ceford commented
I have tested this item :red_circle: unsuccessfully on f9713277467ede118677915a0a3270bf1d0dc3d2<br /><br />There is something wrong here. I applied the patch and ran npm ci (and even npm install). I am using Firefox on a Mac with 5.0.0-beta2-dev and I see no difference in the behaviour with the patch installed and hard page reload. The Ctrl key has no effect. I checked the code to see that all the patches were applied. On Mac/Firefox the Ctrl key brings up a browser dialog (Back, Reload, etc). I could not find a combination of keys that select/deselect an image that does not deselect previously selected images.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39824">issues.joomla.org/tracker/joomla-cms/39824</a>.</sub>

2023-10-05 10:12 UTC, HLeithner commented
@rajputanuj31 can you look at the response by @ceford please?

2023-10-05 12:55 UTC, rajputanuj31 commented
> @rajputanuj31 can you look at the response by @ceford please?

Its working perfectly in my local machine.
[Screencast from 05-10-23 06:23:07 PM IST.webm](https://github.com/joomla/joomla-cms/assets/115709571/7b32139e-e6ef-4259-bb61-e469ef1614c9)

2023-10-05 12:58 UTC, dgrammatiko commented
Mac ctrl (in this context) is the apple button (command)

2024-06-09 19:53 UTC, webmasterab commented
I tested it and it didn't pass.
See video.
Windows PC 
Chrome latest version
CTRL pressed

https://github.com/joomla/joomla-cms/assets/8011751/7ebbc3c2-bc19-4bd7-b227-701bb4ae0697

2024-08-29 10:37 UTC, fgsw commented
No prebuilt packages are available to test.

2024-08-29 10:40 UTC, Hackwar commented
In about 10 minutes the packages should be available again.

2024-08-29 11:48 UTC, fgsw commented
I have tested this item :white_check_mark: successfully on b86e7d42b9e9095d38a2e0cc3125b33bc3176702<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39824">issues.joomla.org/tracker/joomla-cms/39824</a>.</sub>

2024-09-02 08:28 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2024-09-02 08:38 UTC, dgrammatiko commented
Note for maintainers: this PR needs update so it won't revert https://github.com/joomla/joomla-cms/pull/43859

basically adding `name: ctx.item.name,` should be enough after line 15 in 
[administrator/components/com_media/resources/scripts/components/browser/utils/utils.es6.js](https://github.com/joomla/joomla-cms/pull/39824#diff-c7d098720d69ce50b6c34541fc7733f480130c89602939ac79999c0d1324c102)

2024-11-22 18:39 UTC, Hackwar commented
@rajputanuj31 I know this is taking awfully long, but could you please solve the conflicts and check the comment from @dgrammatiko? I'll try to then find testers to finally get this into 5.2.

2025-01-16 09:22 UTC, Hackwar commented
@rajputanuj31 Any news on this one?

2025-01-18 15:14 UTC, richard67 commented
Closing in favour of PR #44747 .

@rajputanuj31 Thanks for working on this PR here. You will be credited as co-author of the new PR.

2025-01-18 15:14 UTC, closed without merging