[4.3]No search result found msg in media new
joomla/joomla-cms pull request #39872
Opened 2023-02-16 19:23 UTC by Kaushik1216

**Newfeature**

Alternate pr for pr [https://github.com/joomla/joomla-cms/pull/39819](url)

Summary of Changes
ADD a messge that will display when no result found on searching in media manager

Testing Instructions
Search in media manager

Actual result BEFORE applying this Pull Request
No message shown if no result match .

Expected result AFTER applying this Pull Request
A message will shown if result not match with search

2023-02-16 19:42 UTC, Kaushik1216 commented
@dgrammatiko please check why build it's falling Is it this from my side or what ?

2023-02-16 20:25 UTC, richard67 commented
@Kaushik1216 Does this replace your other PR #39819 ? If yes, then please close the other one. There should be a button on GitHub at the bottom of that PR to close it.

2023-02-17 07:41 UTC, sandewt commented
I have tested this item :red_circle: unsuccessfully on 23e33263369aff78e9c0d9485b1ad3ab0006709e<br /><br />See comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39872">issues.joomla.org/tracker/joomla-cms/39872</a>.</sub>

2023-02-17 07:47 UTC, sandewt commented
You are almost there :smile:

![issue_39470](https://user-images.githubusercontent.com/9271775/219581478-c10fc759-511f-4827-b60d-d8270c43fa1a.png)

Match source code (markup)

```
<div class="alert alert-info"> 
     <span class="icon-info-circle" aria-hidden="true"></span><span class="visually-hidden"><?php echo Text::_('INFO'); ?></span> 
     <?php echo Text::_('JGLOBAL_NO_MATCHING_RESULTS'); ?> 
 </div> 
```

2023-02-17 08:24 UTC, Kaushik1216 commented
> <?php echo Text::_('JGLOBAL_NO_MATCHING_RESULTS'); ?>

we can not write php inside vue file it showing error

This is working fine see below :


https://user-images.githubusercontent.com/100058812/219591084-d994dfb6-c135-4893-a635-a00be21d4298.mp4




Please test it on local system and run npm ci in CLI to compile js

2023-02-17 10:05 UTC, sandewt commented
> This is working fine see below :

Indeed, but....
The idea is that the source code should match, look like this. For example, use the F12 key in FireFox to view the code.

![issue_39470-2](https://user-images.githubusercontent.com/9271775/219613440-f6877083-b6f1-4611-9eef-a25450500fc5.png)

Also see: https://github.com/joomla/joomla-cms/pull/39819#issuecomment-1432036463

2023-02-17 10:25 UTC, richard67 commented on templates/cassiopeia_ddd/templateDetails.xml
> +<?xml version="1.0" encoding="utf-8"?>
Please revert this file from your template override!

2023-02-17 10:29 UTC, sandewt commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        Info
`Info`
should be
`{{ translate('INFO') }}`

2023-02-17 10:31 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        Info
There's a `Notice` translated string that you could use here: [Text::script('NOTICE');](https://github.com/joomla/joomla-cms/blob/ac2658e7981378f9e88dca5a1673c5ed28a0d5b7/layouts/joomla/system/message.php#L36)

2023-02-17 10:49 UTC, Kaushik1216 commented on templates/cassiopeia_ddd/templateDetails.xml
> +<?xml version="1.0" encoding="utf-8"?>
thank you it's just come by mistake

2023-02-17 10:50 UTC, Kaushik1216 commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        Info
ok got it thank you

2023-02-17 10:51 UTC, dgrammatiko requested changes

2023-02-17 10:51 UTC, dgrammatiko commented on administrator/components/com_media/tmpl/media/default_texts.php
> +    'NOTICE',
This is already available you don't have to reload it. Please remove it

2023-02-17 10:51 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('NOTICE') }}
The translation string already exists in the Joomla.Text registry, so in this case you have to use ` {{ Joomla.Text._('NOTICE') }}`

2023-02-17 10:53 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('NOTICE') }}
Edit: it might even work with ` {{ translate('NOTICE') }} ` as the translate is a proxy to `Joomla.Text._()` iirc

2023-02-17 11:11 UTC, Kaushik1216 commented on administrator/components/com_media/tmpl/media/default_texts.php
> +    'NOTICE',
done

2023-02-17 11:13 UTC, Kaushik1216 commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('NOTICE') }}
I think we should write {{ translate('NOTICE') }} as it's working .On writing  {{ Joomla.Text._('NOTICE') }} this msg  disapper Don't know why

2023-02-17 11:59 UTC, sandewt commented
I should expect here a closing tag? But see that it is not used in other places in this file.
Please your opinion @dgrammatiko 

Line 39 - 

Correct ?
```
<span
    class="icon-info-circle"
    aria-hidden="true"
/>
```  
Or is this desired ?
```	  
<span
    class="icon-info-circle"
    aria-hidden="true"
>
</span>
```

2023-02-17 12:05 UTC, dgrammatiko commented
> I would expect here a closing tag? But see that it is not used in other places in this file.

This is a `.vue` file and there's a special way that HTML elements are treated (similar to React's JSX). This is fine and actually if you write it as 
```
<span
    class="icon-info-circle"
    aria-hidden="true"
>
</span>
```

you will get a notice from the linter

2023-02-17 12:17 UTC, Kaushik1216 commented
@dgrammatiko @sandewt please test now

2023-02-17 17:59 UTC, Quy commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('NOTICE') }}
It should be `Info`.

2023-02-17 18:04 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('NOTICE') }}
https://github.com/joomla/joomla-cms/pull/39872#discussion_r1109593343

2023-02-17 18:20 UTC, Quy commented
Please fix spacing.

![39872-media](https://user-images.githubusercontent.com/368084/219748066-809e36bd-aa36-4ddf-8833-d86f2c24c1ab.jpg)

2023-02-17 18:21 UTC, Quy commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('NOTICE') }}
`Info` is to be consistent elsewhere.

2023-02-17 18:23 UTC, dgrammatiko commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        {{ translate('NOTICE') }}
Ok, but needs to be added in the messages (the link I shared)

2023-02-17 20:45 UTC, Kaushik1216 commented
> Please fix spacing.
> 
> ![39872-media](https://user-images.githubusercontent.com/368084/219748066-809e36bd-aa36-4ddf-8833-d86f2c24c1ab.jpg)

is this fine ? if yes I will made change in pr.

![searchmsg](https://user-images.githubusercontent.com/100058812/219789192-b158c1e5-a28e-49ad-81ce-c208aebc7787.png)

2023-02-17 21:26 UTC, Quy commented
Yes except the following:

![39872-spacing](https://user-images.githubusercontent.com/368084/219796798-d7c5b304-4cb9-4472-90b9-00f6e725f805.png)

2023-02-18 05:23 UTC, Kaushik1216 commented
> Yes except the following:
> 
> ![39872-spacing](https://user-images.githubusercontent.com/368084/219796798-d7c5b304-4cb9-4472-90b9-00f6e725f805.png)

Now I think fine 

![1asearch](https://user-images.githubusercontent.com/100058812/219842685-2b6108fd-3f98-452b-abe1-bc6224c86353.png)

But for it I have to write inline css .At later we can remove all incline css from this file

2023-02-18 06:04 UTC, Kaushik1216 commented
@Quy @sandewt please test it again

2023-02-18 08:55 UTC, sandewt commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        class="alert alert-info ms-3 me-3"
Just a little less code for the same result:
`class="alert alert-info m-3"`

2023-02-18 09:50 UTC, Kaushik1216 commented on administrator/components/com_media/resources/scripts/components/browser/browser.vue
> +        class="alert alert-info ms-3 me-3"
thank you it work

2023-02-18 11:26 UTC, sandewt commented
> Ok, but needs to be added in the messages (the link I shared)

https://github.com/joomla/joomla-cms/pull/39872#discussion_r1110180905

Resolved ?

2023-02-18 11:38 UTC, Kaushik1216 commented
> > Ok, but needs to be added in the messages (the link I shared)
> 
> [#39872 (comment)](https://github.com/joomla/joomla-cms/pull/39872#discussion_r1110180905)
> 
> Resolved ?

yes @dgrammatiko said me that I can use this string .

2023-02-18 12:40 UTC, Kaushik1216 commented
can anyone tell me  why build is falling ? in my system it's working fine

2023-02-22 10:05 UTC, laoneo commented
Can you revert the lock file?

2023-02-22 12:30 UTC, Kaushik1216 commented
@laoneo @dgrammatiko @sandewt  I have revert changes in lock please test this PR

2023-02-24 09:25 UTC, sandewt commented
I have tested successfully, but:
I have not done a .vue code review. That's not my expertise.
That's why I haven't set a flag yet.

2023-02-24 09:49 UTC, dgrammatiko commented
@sandewt the Vue file is fine, mark your test as successful

2023-02-24 09:58 UTC, sandewt commented
I have tested this item :white_check_mark: successfully on 9fbd0281cc10f810ca0f049871dac3aeff61be0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39872">issues.joomla.org/tracker/joomla-cms/39872</a>.</sub>

2023-02-24 09:58 UTC, sandewt commented
> the Vue file is fine, mark your test as successful

Done<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39872">issues.joomla.org/tracker/joomla-cms/39872</a>.</sub>

2023-02-24 16:10 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 9fbd0281cc10f810ca0f049871dac3aeff61be0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39872">issues.joomla.org/tracker/joomla-cms/39872</a>.</sub>

2023-02-24 16:10 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39872">issues.joomla.org/tracker/joomla-cms/39872</a>.</sub>

2023-02-24 16:24 UTC, sandewt commented
Thanks all

2023-02-24 22:30 UTC, merged

2023-02-24 22:30 UTC, obuisard commented
Thank you @Kaushik1216 for the PR!