GSoC’22 project: Guided Tours
joomla/joomla-cms pull request #39902
Opened 2023-02-21 04:04 UTC by obuisard

This PR gives Joomla users the ability to complete walk-throughs (or tours) to better understand the interface they are learning to use. 

The Guided Tours component comes with views for the creation of tours and their associated steps.
It also offers a list of already-made tours for basic Joomla functionality.

Third party extensions developers will be able to create tours of their own for their users and website designers will be able to provide their clients with the help they need. 

This Google Summer of Code project was assigned to Khushi Rauniyar @khu5h1 and other contributors helped her to the finish line.

Many thanks to Khushi and her mentors, Benjamin @bembelimen for advice and code guidance, Brian @brianteeman for the thorough testing, the teams who tested and everyone who helped in the project (a special thank you to Aaron @aze088 for jumping in).  

### Testing Instructions

- To start a tour, select a tour in 'Take a tour'.

![image](https://user-images.githubusercontent.com/5964177/220242200-db6280e5-e925-4729-bf7f-eab0ee994ed3.png)
 
- To create tours, go to System -> Manage -> Guided Tours.

![image](https://user-images.githubusercontent.com/5964177/220242429-03f13c3a-4052-466b-a8a5-25e781d0d3ed.png)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-02-21 08:23 UTC, joomdonation reviewed
There are some issues with the code base on my quick review

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Controller/StepController.php
> +    public function cancel($key = null)
I think this could be removed. The override here does not have any different behavior than the default implementation.

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Controller/StepsController.php
> +    public function display($cachable = false, $urlparams = [])
The code here need to be moved to `display` method of `DisplayController`. An admin controller should not have display method. In short, the code here won't be executed

Also, similar check need to be implemented for `tour` view.

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Controller/ToursController.php
> +        $this->setRedirect('index.php?option=com_guidedtours&view=tours' . $this->getRedirectToListAppend());
To be consistent, the URL here should be passed into `Route::_` call.

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +    public static function setStepLanguage(int $id, string $language = '*'): string
I feel a bit strange when an update db operation is implemented here. Shouldn't this logic implemented in model @laoneo ?

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +    public function getTable($name = '', $prefix = '', $options = [])
The override for `getTable` method is wrongly implemented here. Please remove it or just change it to:

```php
    public function getTable($type = 'Step', $prefix = 'Administrator', $config = [])
    {
        return parent::getTable($type, $prefix, $config);
    }
```

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +            !Factory::getUser()->authorise('core.delete', $component . '.state.' . (int) $record->id)
Use `$this->getCurrentUser()` to get current user object instead of using `Factory::getUser()`

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        $user       = $app->getIdentity();
This `$user` variable is not used in this method

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        $parts = explode('.', $tour->extension);
This `$parts` variable is not used in this method

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        $extension = $app->getUserStateFromRequest('com_guidedtours.step.filter.extension', 'extension', null, 'cmd');
The `$extension` variable is not used in this method

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +                if ($table->load($pk) && $table->default) {
Looking at **guidedtour_steps** table, I don't see default field. So not sure what `$table->default` refer to here?

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +                    $app->enqueueMessage(Text::_('COM_WORKFLOW_MSG_DISABLE_DEFAULT'), 'error');
COM_WORKFLOW ?

2023-02-21 08:23 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepsModel.php
> +    protected function getEmptyStateQuery()
The code here could be simplified to:

```
protected function getEmptyStateQuery()
    {
		$query = parent::getEmptyStateQuery();
		
	        $tour_id = $this->getState('filter.tour_id');
	    
		if ($tour_id) {
		    $db = $this->getDatabase();
		    $tour_id = (int) $tour_id;
		    $query->where($db->quoteName('a.tour_id') . ' = :tour_id')
			    ->bind(':tour_id', $tour_id, ParameterType::INTEGER);
	    }
		
        return $query;
    }
```

Further more, I would camel case for variable name, so `$tourId` instead of `$tour_id`.

2023-02-21 08:41 UTC, brianteeman commented on administrator/components/com_guidedtours/forms/filter_tours.xml
> +		>
```suggestion
			>
```

2023-02-21 08:43 UTC, chmst commented
Tour works on fresh installation of the full package, but not after update with the update package. In the updated version, only the component is available, but no "Take the tour" buttons.

2023-02-21 08:53 UTC, chmst commented on administrator/components/com_guidedtours/forms/step.xml
> +		filter="JComponentHelper::filterText"
Get rid of JComponentHelper and use ComponentHelper now?

2023-02-21 09:11 UTC, joomdonation commented on administrator/components/com_guidedtours/forms/step.xml
> +		filter="JComponentHelper::filterText"
If you want to do that, you would need to use full class name

```xml
filter="Joomla\CMS\Component\ComponentHelper::filterText"
```

2023-02-21 09:21 UTC, Kostelano commented on administrator/language/en-GB/com_guidedtours.ini
> +COM_GUIDEDTOURS_BASIC_STEP="Basic Step"
```suggestion
COM_GUIDEDTOURS_BASIC_STEP="Basic Step"
COM_GUIDEDTOURS_CONFIGURATION="Guided Tours: Options"
```

Missed.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/220302680-70cc8c45-2066-4d12-912d-f7e9caa82fd3.png)

2023-02-21 09:24 UTC, brianteeman commented
As stated before.
if you are not using tinymce then any tour that was using it as an identifier is broken


if you update the tours to use a target of .adminform instead of .tox-edit-area__iframe then the tours will be editor agnostic

2023-02-21 09:31 UTC, brianteeman commented
the value of the checkedout field in _guidedtours should be null and not 0

otherwise on a clean install you have 11 items to checkin

![image](https://user-images.githubusercontent.com/1296369/220305165-51b45828-d631-4419-8b76-0dc0229b653b.png)

2023-02-21 09:52 UTC, brianteeman commented
As stated before this is unusable if you are just using a keyboard resulting in this being completely inaccessible. You can test this for yourself by taking the banner tour just using the keyboard and see if you can not only move forward through the tour but also move backwards

2023-02-21 12:55 UTC, dgrammatiko commented
Nice intro:

<img width="791" alt="Screenshot 2023-02-21 at 13 55 10" src="https://user-images.githubusercontent.com/3889375/220350330-53d9bdb1-6afe-43f8-8867-a1b2b25f4af9.png">

2023-02-21 13:03 UTC, alikon commented
imho this should'nt be shipped with the core, better there should be an option to install it on installation phase

2023-02-21 13:34 UTC, dgrammatiko commented
@obuisard please check and merge https://github.com/obuisard/joomla-cms/pull/6

2023-02-21 13:42 UTC, laoneo commented
Why is here a system plugin needed? I don't think that it is wise to have a system plugin enabled which is executed on all pages for a use case which is used only for newcomers.

Honestly I share the idea of @alikon to have this feature installable on demand. It doesn't mean that the "Take the tour" button doesn't have to be there, but it should install the extension only when actually needed.

2023-02-21 14:10 UTC, dgrammatiko commented
> As stated before this is unusable if you are just using a keyboard resulting in this being completely inaccessible.

When I did the [first implementation](https://github.com/joomla/40-backend-template/pull/247) I had left a comment on the keyboard accessibility: https://github.com/joomla/40-backend-template/pull/247#issuecomment-263126692 which should give a good entry point on how to fix the issue

2023-02-21 15:55 UTC, coolcat-creations commented
I like the idea to enable it on install (as a check) Also the sample Data module should only be installed if someone checks " I am a first time user" or so.

2023-02-21 16:14 UTC, brianteeman commented
When or if it's installed is a pointless decision for me as we must first decide if it's acceptable to add a completely inaccessible extension

2023-02-21 17:11 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepsModel.php
> +    protected function getEmptyStateQuery()
Thank you, great suggestions!

2023-02-21 17:16 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +                if ($table->load($pk) && $table->default) {
This function is useless.

2023-02-21 17:20 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +    public function getTable($name = '', $prefix = '', $options = [])
Thank you!

2023-02-21 17:37 UTC, Quy commented on administrator/components/com_guidedtours/forms/step.xml
> +        >
```suggestion
        	>
```

2023-02-21 17:41 UTC, obuisard commented on administrator/components/com_guidedtours/src/Controller/ToursController.php
> +        $this->setRedirect('index.php?option=com_guidedtours&view=tours' . $this->getRedirectToListAppend());
Agreed

2023-02-21 17:43 UTC, obuisard commented on administrator/components/com_guidedtours/forms/step.xml
> +		filter="JComponentHelper::filterText"
This should be done everywhere in the core I believe.

2023-02-21 17:47 UTC, obuisard commented
> imho this should'nt be shipped with the core, better there should be an option to install it on installation phase

Keeping 'Guided Tours' in the core allows third party developers to have their extensions shipped with tours and be usable by their new users. The tours are not only for the Joomla newbies.

2023-02-21 17:49 UTC, brianteeman commented on administrator/components/com_guidedtours/forms/step.xml
> +		filter="JComponentHelper::filterText"
yes - but definitely beyond the scope of this PR

2023-02-21 17:56 UTC, obuisard commented
> the value of the checkedout field in _guidedtours should be null and not 0
> 
> otherwise on a clean install you have 11 items to checkin
> 
> ![image](https://user-images.githubusercontent.com/1296369/220305165-51b45828-d631-4419-8b76-0dc0229b653b.png)

Great point. Will change that.

2023-02-21 17:58 UTC, obuisard commented
> In the updated version, only the component is available, but no "Take the tour" buttons.

It is missing, indeed.

2023-02-21 18:30 UTC, alikon commented
> Keeping 'Guided Tours' in the core allows third party developers to have their extensions shipped with tours and be usable by their new users. The tours are not only for the Joomla newbies.

this doesn't necessaily mean that we must "bloat" the core with such kind of stuff

i still think that this feature should be opt-in and not in the core as a default

2023-02-22 06:50 UTC, laoneo commented
How can an extension developer integrate then tours? When not through a plugin, then I doubt it is the right approach.

2023-02-22 10:57 UTC, wilsonge commented
> When or if it's installed is a pointless decision for me as we must first decide if it's acceptable to add a completely inaccessible extension

Per the a11y policy we published anything in the backend has to be accessible (ref: https://www.joomla.org/accessibility-statement.html) so no this can't be merged without a11y support.

> Why is here a system plugin needed? I don't think that it is wise to have a system plugin enabled which is executed on all pages for a use case which is used only for newcomers.

I don't think the fact it's only for newcomers is the issue. Don't forget there are very legit use cases for inducting administrators to a site that has long existed (think about the onboarding of new content creators for a blog or something similar). I'd argue there's a good reason for this to be installed for much longer than just first Joomla install

Having said that I also agree for what this is doing system plugin is overkill. I think this can be a dedicated plugin group for extensions to integrate with and we can import that group only in `AdministratorApplication` to ensure that there aren't any calls to it from the other apps (this will also help with some sanity checks). Open question as to whether it is safe to believe that we are only gong to be running this in the admin (because on certain sites like joomla CRM/elearning extensions there might be use cases for this in the frontend??)

2023-02-22 11:21 UTC, wilsonge commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +    public static function setStepLanguage(int $id, string $language = '*'): string
Yes. Although I can't even see anything calling this method?

2023-02-22 11:59 UTC, brianteeman commented
I am aware that sosme people don't see it as important but this is what our accessibility statement says.

> With Joomla! 4, we conform with the Worldwide Web Consortium (W3C) guidelines: WCAG 2.1 and ATAG 2.0. The Joomla Backend ensures full accessibility. Every person, with or without disability, can use Joomla to create, administer and maintain accessible sites. We give you the tools, the rest is up to you!

2023-02-23 17:52 UTC, obuisard commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +    public static function setStepLanguage(int $id, string $language = '*'): string
When a tour is saved, all the steps are updated with the correct language. That is where is is used (TourModel - save)

2023-02-23 17:53 UTC, obuisard commented on administrator/components/com_guidedtours/forms/step.xml
> +		filter="JComponentHelper::filterText"
Thanks! I will leave until the whole core is updated at once

2023-02-23 18:38 UTC, dgrammatiko requested changes

2023-02-23 18:38 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/scss/guidedtours.scss
> + @import '../../../../node_modules/shepherd.js/dist/css/shepherd';
```suggestion
@import "../../../../node_modules/shepherd.js/dist/css/shepherd";
```

Fixes the linter issues

2023-02-23 18:40 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +            tabIndex++;
This won't fly with the linter

2023-02-23 18:41 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +            tabIndex++;
Ok, I will see what I can do to make it better

2023-02-23 18:47 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +            tabIndex++;
The original code was 

```js
let tabIndex = 0;

target.tabIndex = ++tabIndex
```

which should be the same as:

```js
let tabIndex = 0;

tabIndex += 1;
target.tabIndex = tabIndex;
```

2023-02-23 19:01 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +            tabIndex++;
Yes, I need to increment the tab index so that the target gets the first index, then the other buttons and I want the increment to be logical: 1 -> 2 -> 3. That what was meant in the original code.

2023-02-23 19:52 UTC, brianteeman commented
Tried to test after the latest changes but unable to do so as the Take a tour button doesnt do anything

2023-02-23 19:56 UTC, dgrammatiko commented
> Tried to test after the latest changes but unable to do so as the Take a tour button doesnt do anything

Did you use the generated package? It seems that the Download action is in a pending status

2023-02-23 20:13 UTC, obuisard commented
> Tried to test after the latest changes but unable to do so as the Take a tour button doesnt do anything

Thank you both, checking this issue.

2023-02-23 20:32 UTC, brianteeman commented
> > Tried to test after the latest changes but unable to do so as the Take a tour button doesnt do anything
> 
> Did you use the generated package? It seems that the Download action is in a pending status

always git pull and npm i to avoid issues

2023-02-23 20:34 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> -
@obuisard are you sure this is not used?

2023-02-23 20:36 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> -
Yes :-)

2023-02-23 20:37 UTC, obuisard commented
> > > Tried to test after the latest changes but unable to do so as the Take a tour button doesnt do anything
> > 
> > 
> > Did you use the generated package? It seems that the Download action is in a pending status
> 
> always git pull and npm i to avoid issues

I installed the latest packages and tours start properly. Can you double check Dimitris @dgrammatiko ? Everything works for me on this new install.

2023-02-23 20:44 UTC, brianteeman commented
just realised its on the home dashboard its not opening

2023-02-23 20:47 UTC, brianteeman commented
Found the problem. The module is not loading the bootstrap dropdown and is reliant on other modules to load the js

2023-02-23 20:48 UTC, brianteeman commented
https://github.com/joomla-projects/gsoc22_guided-tour/pull/43#issuecomment-1424822580

2023-02-23 21:05 UTC, brianteeman commented
With the recent changes there are nnow the following problems when using the keyboard

Using the menu tour
Step 3 - the first with an input
If you tab past the input you get to the close icon. Subsequent tab takes you out of the tour
Shift tab will take you back to the close but you can not go back to the input
and you still cant go forward to the next button because it is disabled. 
There is no indicator that the button is disabled

Step 4 is the same :(

2023-02-23 21:05 UTC, obuisard commented
> Found the problem. The module is not loading the bootstrap dropdown and is reliant on other modules to load the js

I lost it during refactoring... I put it back. Great catch Brian @brianteeman.

2023-02-23 21:10 UTC, brianteeman commented on administrator/modules/mod_guidedtours/tmpl/default.php
> +HTMLHelper::_('bootstrap.dropdown', '.dropdown-toggle');
please use the web asset manager

2023-02-23 21:10 UTC, obuisard commented
> With the recent changes there are nnow the following problems when using the keyboard
> 
> Using the menu tour Step 3 - the first with an input If you tab past the input you get to the close icon. Subsequent tab takes you out of the tour Shift tab will take you back to the close but you can not go back to the input and you still cant go forward to the next button because it is disabled. There is no indicator that the button is disabled
> 
> Step 4 is the same :(

Still have to work on that.

As far as the button's disabled state not being visible, I found out what it is: the template only changes the aspect of the button if the class .disabled is used and does not take into account the attribute disabled. I can fix the code to add the disabled class but to me, the template should be handling it.

2023-02-23 21:18 UTC, obuisard commented on administrator/modules/mod_guidedtours/tmpl/default.php
> +HTMLHelper::_('bootstrap.dropdown', '.dropdown-toggle');
The web asset manager is used in HTMLHelper::_('bootstrap.dropdown', '.dropdown-toggle');. However using the web asset manager directly won't cache .dropdown-toggle. HTMLHelper for dropdowns is used throughout the core for that reason (I believe).

2023-02-23 21:43 UTC, dgrammatiko commented on administrator/modules/mod_guidedtours/tmpl/default.php
> +HTMLHelper::_('bootstrap.dropdown', '.dropdown-toggle');
@obuisard you don't need the class part in this case as the button has the `data-bs-toggle="dropdown"` which triggers the same functionality. The HTMLHelper should ONLY be used if you need to pass some custom options for the JS (like no modal backdrop, etc) otherwise it should NEVER be used, the web assets should be the default.

2023-02-23 22:09 UTC, Quy commented on administrator/language/en-GB/com_guidedtours.ini
> +COM_GUIDEDTOURS_STEP_TYPE_DESC="Select the type which you want to select for the tour."
Explain types or remove as it provides no additional tip/help.

2023-02-23 22:10 UTC, Quy commented on administrator/language/en-GB/com_guidedtours.ini
> +COM_GUIDEDTOURS_TYPE_INTERACTIVE_STEP_DESC="Select the type of interactive step."
Explain types or remove as it provides no additional tip/help.

2023-02-23 22:12 UTC, Quy commented on administrator/components/com_guidedtours/forms/tour.xml
> +	    >
```suggestion
		>
```

2023-02-23 22:12 UTC, Quy commented on administrator/components/com_guidedtours/forms/tour.xml
> +	    >
```suggestion
		>
```

2023-02-23 23:35 UTC, obuisard commented on administrator/modules/mod_guidedtours/tmpl/default.php
> +HTMLHelper::_('bootstrap.dropdown', '.dropdown-toggle');
Ok, understood. This has to be done all over the core, then as well.

2023-02-23 23:46 UTC, obuisard commented on administrator/language/en-GB/com_guidedtours.ini
> +COM_GUIDEDTOURS_STEP_TYPE_DESC="Select the type which you want to select for the tour."
You are right, I have provided a better explanation.

2023-02-23 23:49 UTC, Quy commented
Please check the responsiveness of columns on mobile.

![39902-responsive-columns](https://user-images.githubusercontent.com/368084/221057415-0855f738-25c8-4086-82c5-89b19154ee2d.png)

2023-02-23 23:55 UTC, obuisard commented
> Please check the responsiveness of columns on mobile.
> 
> ![39902-responsive-columns](https://user-images.githubusercontent.com/368084/221057415-0855f738-25c8-4086-82c5-89b19154ee2d.png)

I don't have that behavior, strange...

2023-02-24 00:10 UTC, Quy commented
Make sure to reload the page. You should not see the `7/7 Columns`.

2023-02-24 01:04 UTC, obuisard commented
> Make sure to reload the page. You should not see the `7/7 Columns`.

Fixed. Thanks!

2023-02-24 16:50 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/tours/default.php
> +                    <th scope="col">
```suggestion
                    <th scope="col" class="d-none d-md-table-cell">
```

2023-02-24 16:50 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/tours/default.php
> +                        <td class="">
```suggestion
                        <td class="d-none d-md-table-cell">
```

2023-02-24 17:01 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/steps/default.php
> +                    <th scope="col">
```suggestion
                    <th scope="col" class="d-none d-md-table-cell">
                        <?php echo Text::_('COM_GUIDEDTOURS_DESCRIPTION'); ?>
                    </th>
                    <th scope="col" class="d-none d-md-table-cell">
```

2023-02-24 17:01 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/steps/default.php
> +                        <td>
```suggestion
                        <td class="d-none d-md-table-cell">
                            <?php echo StringHelper::truncate($item->description, 200, true, false); ?>
                        </td>

                        <!-- Step Type -->
                        <td class="d-none d-md-table-cell">
```

2023-02-25 00:10 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/steps/default.php
> +        echo LayoutHelper::render('joomla.searchtools.default', array('view' => $this));
```suggestion
        echo LayoutHelper::render('joomla.searchtools.default', ['view' => $this]);
```

2023-02-25 00:10 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/tours/default.php
> +        echo LayoutHelper::render('joomla.searchtools.default', array('view' => $this));
```suggestion
        echo LayoutHelper::render('joomla.searchtools.default', ['view' => $this]);
```

2023-02-25 00:11 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/tours/default.php
> +                </span><span class="visually-hidden"><?php echo Text::_('INFO'); ?></span>
```suggestion
                <span class="icon-info-circle" aria-hidden="true"></span>
                <span class="visually-hidden"><?php echo Text::_('INFO'); ?></span>
```

2023-02-27 17:48 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/steps/default.php
> +                    <th scope="col" class="w-1 text-center d-none d-md-table-cell">
```suggestion
                    <th scope="col" class="w-1 text-center">
```

2023-02-27 18:38 UTC, Quy commented
Add spacing.

![39902-spacing](https://user-images.githubusercontent.com/368084/221653227-7f4888bb-42cb-4230-9866-dd8808631ea5.png)

2023-02-27 18:53 UTC, brianteeman commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +        // Possibility to use coma-separated selectors.
```suggestion
        // Possibility to use comma-separated selectors.
```

2023-02-27 18:53 UTC, brianteeman commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +              // Make sure TinyMCE is accessible by using the source edition
edition ??

2023-02-27 19:04 UTC, brianteeman commented
The changes for modified editor targets does NOT work when codemirror is the editor
https://github.com/joomla/joomla-cms/pull/39902/commits/dbb10191bc859b669720267104a96dda79f221ae

There was a reason that I submitted a pull request two weeks ago with specific code that was tested and worked when all three of the default editor settings was used https://github.com/joomla-projects/gsoc22_guided-tour/pull/95

2023-02-27 19:07 UTC, obuisard commented
> The changes for modified editor targets does NOT work when codemirror is the editor [dbb1019](https://github.com/joomla/joomla-cms/commit/dbb10191bc859b669720267104a96dda79f221ae)
> 
> There was a reason that I submitted a pull request two weeks ago with specific code that was tested and worked when all three of the default editor settings was used [joomla-projects/gsoc22_guided-tour#95](https://github.com/joomla-projects/gsoc22_guided-tour/pull/95)

Except that the fix suggested was not accessible. It broke the flow. So although an interesting suggestion, it is not a viable solution.
Who in his right mind would use codemirror to edit an article?

Finally, the solution provided could not work in all cases. .adminform is not used everywhere, some forms use other names and some forms don't even have a class to hold on (the core code is not always consistent).

2023-02-27 19:14 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +              // Make sure TinyMCE is accessible by using the source edition
The source editor is used when entering data in the TinyMCE editor to keep the tour accessible.

2023-02-27 19:17 UTC, brianteeman commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +              // Make sure TinyMCE is accessible by using the source edition
so the word is "editor" not "edition"

2023-02-27 19:18 UTC, brianteeman commented
The code provided worked perfectly for all the cases it was used in. The code you have used does not.

And yes lots of people use codemirror for content

2023-02-27 19:24 UTC, brianteeman commented
> Finally, the solution provided could not work in all cases. .adminform is not used everywhere, some forms use other names and some forms don't even have a class to hold on (the core code is not always consistent).

if .adminform is not used everywhere then thats not a problem. each step uses its own target - just use the correct one and then it will do. 

the code in this pr right now doesn;'t work in all cases either.

If there is a form that doesnt have a class or id then there is something seriously wrong with that form and I am amazed that it would actually work. In other words - please show an example so it can be fixed as its a serious bug.

I was not able to replicate the claimed break in flow - please provide an example for my education.

2023-02-27 19:36 UTC, brianteeman commented
Not spotted this error before when using the back button

https://user-images.githubusercontent.com/1296369/221665058-2aa950c8-12f9-4e1f-bd7b-668fb0440f51.mp4

2023-02-27 19:39 UTC, obuisard commented
> The code provided worked perfectly for all the cases it was used in. The code you have used does not.
> 
> And yes lots of people use codemirror for content

Sorry to contradict, no it did not work with the guided tour for tags, for instance. There is no adminform class on that page. Or any class.

The tags edit page:
![image](https://user-images.githubusercontent.com/5964177/221663879-74699202-4752-4032-900e-700fad1308db.png)

The article edit page:
![image](https://user-images.githubusercontent.com/5964177/221664005-85f51299-6eef-4097-975e-efb18ec7d7df.png)

By the way, bad chose of class here: the form on that page already uses that name.

> if .adminform is not used everywhere then thats not a problem. each step uses its own target - just use the correct one and then it will do.

Indeed, it's not a problem, we can use any class for pages that are scanned by guided tours.

> the code in this pr right now doesn;'t work in all cases either.

It does not break the flow. If someone uses CodeMirror, the guided tours does not break (loss of focus, for instance, or popup at the wrong place), text can't be added and the step becomes just informative. Once again, using codeMirror to create articles (for instance) is unlikely to happen anyway.

> If there is a form that doesnt have a class or id then there is something seriously wrong with that form and I am amazed that it would actually work. In other words - please show an example so it can be fixed as its a serious bug.

Forms do work. They all have ids.

2023-02-27 19:40 UTC, brianteeman commented
>  Once again, using codeMirror to create articles (for instance) is unlikely to happen anyway.

Simply not true and irrelevant. I used codemirror on my blog for years because it was more keyboard friendly than using tinymce and I liked the code highlighting

2023-02-27 19:46 UTC, brianteeman commented
This is a fun one. If for whatever reason you quit joomla in the middle of a tour without formaly closing the tour then it continues as soon as you log back in/


https://user-images.githubusercontent.com/1296369/221666895-68d5ed7a-70c6-41e3-9a99-982d0360ea52.mp4

2023-02-27 19:50 UTC, obuisard commented
> Not spotted this error before when using the back button
> 
> the url after the error is /administrator/null

Thank you, I was able to reproduce it. Looking into it. Should be fixed from my last commit.

2023-02-27 19:52 UTC, obuisard commented
> This is a fun one. If for whatever reason you quit joomla in the middle of a tour without formaly closing the tour then it continues as soon as you log back in/

That's because the session storage has not been cleared

2023-02-27 20:07 UTC, brianteeman commented
> > This is a fun one. If for whatever reason you quit joomla in the middle of a tour without formaly closing the tour then it continues as soon as you log back in/
> 
> That's because the session storage has not been cleared

If the session times out then you get this weird behaviour making it hard (and not accessible) to log back in


https://user-images.githubusercontent.com/1296369/221672002-d31badba-487e-4db0-b416-070bacae633f.mp4

2023-02-27 21:10 UTC, obuisard commented
> 



> Add spacing.
> 
> ![39902-spacing](https://user-images.githubusercontent.com/368084/221653227-7f4888bb-42cb-4230-9866-dd8808631ea5.png)

Addressed :-)

2023-02-28 16:06 UTC, Quy commented
Exits at this step with the following in console:

> Uncaught (in promise) DOMException: Document.querySelector: 'joomla-field-fancy-select:has(#jform_catid) .choices' is not a valid selector

![39902-status](https://user-images.githubusercontent.com/368084/221910124-c7eb3ed4-15bd-4c99-8fca-f2c75338014d.png)

2023-02-28 16:52 UTC, obuisard commented
> Exits at this step with the following in console:
> 
> > Uncaught (in promise) DOMException: Document.querySelector: 'joomla-field-fancy-select:has(#jform_catid) .choices' is not a valid selector
> 

You may be using a browser that does not support `:has`

2023-02-28 18:09 UTC, Quy commented
Using the latest version of Windows Firefox 110.0.1.

2023-02-28 18:11 UTC, brianteeman commented
Firefox does not support :has so it can not be used by Joomla according to our browser support policy

![image](https://user-images.githubusercontent.com/1296369/221942587-795c0a70-a0a0-48a8-8825-38cadbb70926.png)

2023-02-28 20:03 UTC, Quy commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONGRATULATIONS_DESCRIPTION="<p>You have successfully created your first guided tour! You now have to create steps for the tour.</p>"
Please remove `successfully`. See #14607.

2023-02-28 20:25 UTC, obuisard commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONGRATULATIONS_DESCRIPTION="<p>You have successfully created your first guided tour! You now have to create steps for the tour.</p>"
I see what you mean, I will remove those

2023-02-28 20:26 UTC, obuisard commented
> Using the latest version of Windows Firefox 110.0.1.

There was a missing catch statement in the promise. Now, an invalid selector is bypassed gracefully and the tour keeps going.

2023-02-28 21:08 UTC, Quy commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_CONGRATULATIONS_DESCRIPTION="<p>You have created a news feed!</p>"
```suggestion
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_CONGRATULATIONS_TITLE="Congratulations!"
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_CONGRATULATIONS_DESCRIPTION="<p>You have created a news feed!</p>"
```
Maybe remove the second `!` since it is already in the title.

2023-02-28 23:45 UTC, obuisard commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_CONGRATULATIONS_DESCRIPTION="<p>You have created a news feed!</p>"
Makes sense

2023-03-01 00:08 UTC, Quy commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_DESCRIPTION="<p>This tour will show you how you can create a guided tour for the Joomla backend.</p>"
```suggestion
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_DESCRIPTION="<p>This tour will show you how you can create a guided tour for the Joomla backend.</p>"
```
It is better to not include markup `<p>`. In this case it does not affect display.

2023-03-01 00:39 UTC, obuisard commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_DESCRIPTION="<p>This tour will show you how you can create a guided tour for the Joomla backend.</p>"
We don't seen it in the initial language files, agreed.

2023-03-01 01:13 UTC, Quy commented on administrator/modules/mod_guidedtours/tmpl/default.php
> +use Joomla\CMS\Factory;
```suggestion
```

2023-03-01 01:17 UTC, Quy commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_.DESCRIPTION="This tour will show you how you can create a guided tour for the Joomla backend."
```suggestion
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_DESCRIPTION="This tour will show you how you can create a guided tour for the Joomla backend."
```
Fix all instances.

2023-03-01 01:21 UTC, Quy commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_.DESCRIPTION="This tour will show you how you can create a guided tour for the Joomla backend."
Also keys should be sorted in alpha order and no blank lines.

2023-03-01 01:45 UTC, obuisard commented on administrator/language/en-GB/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_.DESCRIPTION="This tour will show you how you can create a guided tour for the Joomla backend."
That will make it very hard to fix the steps when needed so I will keep the file as is until release

2023-03-01 04:16 UTC, obuisard commented
> If the session times out then you get this weird behaviour making it hard (and not accessible) to log back in

Addressed. 
No tour ever loads on the login screen anymore. 
However, the session storage has not been cleared after login, so the tour will resume (the session storage does not clear as long as we remain in the same window/tab). Should we clear the session storage upon login (as a general rule)?

2023-03-01 16:20 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +  for (let index = ind; index < len; index++) {
```suggestion
  for (let index = ind; index < len; index += 1) {
```

2023-03-01 16:20 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +  for (let index = ind; index < len; index++) {
Also remove the eslint disable above

2023-03-01 16:22 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +      .catch((error) => console.error(error));
```suggestion
      .catch((error) => {
        throw new Error(error)
      });
```

Also remove the eslint disable above

2023-03-01 16:40 UTC, Quy commented on administrator/components/com_guidedtours/forms/filter_steps.xml
> +			description="COM_GUIDEDTOURS_STEP_FILTER_SEARCH_DESC"
```suggestion
			name="search"
			type="text"
			label="COM_GUIDEDTOURS_STEP_FILTER_SEARCH_LABEL"
			description="COM_GUIDEDTOURS_STEP_FILTER_SEARCH_DESC"
			inputmode="search"
```

2023-03-01 16:40 UTC, Quy commented on administrator/components/com_guidedtours/forms/step.xml
> +		description="COM_GUIDEDTOURS_STEP_POSITION_DESC"
```suggestion
		name="position"
		type="list"
		label="COM_GUIDEDTOURS_STEP_POSITION_LABEL"
		description="COM_GUIDEDTOURS_STEP_POSITION_DESC"
		default="center"
```

2023-03-01 16:41 UTC, Quy commented on administrator/components/com_guidedtours/forms/step.xml
> +		description="COM_GUIDEDTOURS_STEP_TYPE_DESC"
```suggestion
		name="type"
		type="list"
		label="COM_GUIDEDTOURS_STEP_TYPE_LABEL"
		description="COM_GUIDEDTOURS_STEP_TYPE_DESC"
		default="0"
```

2023-03-01 16:42 UTC, Quy commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +            return "*";
```suggestion
            return '*';
```

2023-03-01 17:08 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +  for (let index = ind; index < len; index++) {
Thank you Dimitris!

2023-03-01 17:09 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +      .catch((error) => console.error(error));
Thanks!

2023-03-01 17:09 UTC, obuisard commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +            return "*";
I don't always say it, but thank you so much for your thorough recommendations @Quy

2023-03-01 17:12 UTC, Quy commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +            return "*";
You are very welcome!

2023-03-01 22:32 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +              // Make sure TinyMCE is accessible by using the source edition
Yes, thanks!

2023-03-01 22:35 UTC, obuisard commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +    public static function setStepLanguage(int $id, string $language = '*'): string
setStepLanguage is used in TourModel to update steps with the tour's language

2023-03-01 23:32 UTC, obuisard commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +    public static function setStepLanguage(int $id, string $language = '*'): string
I see queries all over helper files in the core. What makes a query acceptable in a helper in some cases and not in others? Any rule in particular that needs to be followed or is it just a matter of preference?

2023-03-02 16:50 UTC, Quy commented on administrator/components/com_guidedtours/access.xml
> +<?xml version="1.0" encoding="utf-8" ?>
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
```
See #39951

2023-03-02 17:09 UTC, Quy commented on administrator/components/com_guidedtours/src/Controller/DisplayController.php
> +        if ($view == 'step' && $layout == 'edit' && !$this->checkEditId('com_guidedtours.edit.step', $id)) {
```suggestion
        if ($view === 'tour' && $layout === 'edit' && !$this->checkEditId('com_guidedtours.edit.tour', $id)) {
            $this->setMessage(Text::sprintf('JLIB_APPLICATION_ERROR_UNHELD_ID', $id), 'error');
            $this->setRedirect(Route::_('index.php?option=com_guidedtour&view=tours', false));

            return false;
        }

        if ($view === 'step' && $layout === 'edit' && !$this->checkEditId('com_guidedtours.edit.step', $id)) {
```

2023-03-02 17:14 UTC, Quy commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        $pk  = (isset($data[$key])) ? $data[$key] : (int) $this->getState($this->getName() . '.id');
```suggestion
        $pk  = isset($data[$key]) ? $data[$key] : (int) $this->getState($this->getName() . '.id');
```

2023-03-02 17:17 UTC, Quy commented on administrator/components/com_guidedtours/src/Model/StepsModel.php
> +            $tourId = (int)$tourId;
```suggestion
            $tourId = (int) $tourId;
```

2023-03-02 17:27 UTC, brianteeman commented on administrator/components/com_guidedtours/forms/step.xml
> +        	>
```suggestion
        >
```

2023-03-02 17:27 UTC, obuisard commented on administrator/components/com_guidedtours/access.xml
> +<?xml version="1.0" encoding="utf-8" ?>
Thanks, changes are made throughout

2023-03-02 17:29 UTC, brianteeman commented on administrator/components/com_guidedtours/forms/tour.xml
> +
```suggestion

```

2023-03-02 17:32 UTC, Quy commented on administrator/components/com_guidedtours/forms/step.xml
> +        >
Please revert.

2023-03-02 17:33 UTC, brianteeman commented on administrator/components/com_guidedtours/src/Model/ToursModel.php
> +
```suggestion

```

2023-03-02 17:46 UTC, brianteeman commented on package.json
> +    "rtlcss": "^3.5.0",
why is this being added here? It is already a devDependency and I dont see it being used outside of the dev scripts

2023-03-02 17:58 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/steps/default.php
> +                                       value="<?php echo $item->ordering; ?>">
```suggestion
                            <span class="sortable-handler <?php echo $iconClass; ?>">
                                <span class="icon-ellipsis-v" aria-hidden="true"></span>
                            </span>

                            <?php if ($canChange && $saveOrder) : ?>
                                <input type="text" class="hidden text-area-order" name="order[]" size="5" value="<?php echo $item->ordering; ?>">
```

2023-03-02 17:59 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/tours/default.php
> +                                       name="order[]" size="5" value="<?php echo $item->ordering; ?>">
```suggestion
                            <span class="sortable-handler <?php echo $iconClass; ?>">
                                <span class="icon-ellipsis-v" aria-hidden="true"></span>
                            </span>

                            <?php if ($canChange && $saveOrder) : ?>
                                <input type="text" class="hidden text-area-order" name="order[]" size="5" value="<?php echo $item->ordering; ?>">
```

2023-03-02 18:01 UTC, Quy commented on administrator/components/com_guidedtours/tmpl/tours/default.php
> +                               href="index.php?option=com_guidedtours&view=steps&tour_id=<?php echo $item->id; ?>">
```suggestion
                            <a class="btn btn-info" href="index.php?option=com_guidedtours&view=steps&tour_id=<?php echo $item->id; ?>">
```

2023-03-02 18:52 UTC, obuisard commented
Brian @brianteeman, as far as tabbing/speech is concerned, what is your take on the version we have so far? The previous implementation was creating too many problems and was replaced. There is no longer any removal/shuffle around of tabindex so that the flow remains intact. On blur, a 'target' gives back the focus to the modal, which allows the user to go back to the modal and step through it. There are couple issues we discovered that I will address soon: the focus box around buttons and the '1/3' which should read as 'step 1 of 3'.

2023-03-02 18:54 UTC, obuisard commented on administrator/components/com_guidedtours/tmpl/steps/default.php
> +                                       value="<?php echo $item->ordering; ?>">
Thanks!

2023-03-02 19:01 UTC, brianteeman commented
will review again shortly. I had spotted the step 1 of 3 thing but didnt mention it as there were bigger accessibility issues to address first

2023-03-02 19:18 UTC, brianteeman commented
If the editor is not tinymce then there are js errors during the tour when it gets to the text area
![image](https://user-images.githubusercontent.com/1296369/222529512-2da5ce24-8ccc-490e-b71f-64b12cd1d670.png)

2023-03-02 19:32 UTC, brianteeman commented
video and audio recording


https://user-images.githubusercontent.com/1296369/222533002-0ee84954-05d1-4134-ab4a-f952470ebef5.mp4

2023-03-02 19:32 UTC, obuisard commented
> If the editor is not tinymce then there are js errors during the tour when it gets to the text area.

This happens when a target is not found. This is thrown by Shepherd and when that happens, the script acts as if no target was set and the position is centered.

2023-03-02 19:37 UTC, brianteeman commented
> > If the editor is not tinymce then there are js errors during the tour when it gets to the text area.
> 
> This happens when a target is not found. This is thrown by Shepherd and when that happens, the script acts as if no target was set and the position is centered.

No script should be outputting an error

2023-03-02 19:38 UTC, brianteeman commented
The visual styling on the "back" button is only being applied when you go backwards. Going forwards there is no styling. See video with keystrokes (no audio)


https://user-images.githubusercontent.com/1296369/222534305-0b1bd0c1-32ad-476a-973b-1fdc1c601ae5.mp4

2023-03-02 19:41 UTC, brianteeman commented
I might be mistaken but I am sure that I recall that the guided tours button was available at all times. It now seems to not be available in the one place that I would want to use it - the form edit - and I have to return to a list view to find a tour

2023-03-02 19:43 UTC, obuisard commented
> I might be mistaken but I am sure that I recall that the guided tours button was available at all times. It now seems to not be available in the one place that I would want to use it - the form edit - and I have to return to a list view to find a tour

The button 'take a tour' (like all buttons in the status bar) should not be there if you are in a middle of editing an article, for instance. Or do you think we should make an exception?

2023-03-02 19:48 UTC, brianteeman commented
> > I might be mistaken but I am sure that I recall that the guided tours button was available at all times. It now seems to not be available in the one place that I would want to use it - the form edit - and I have to return to a list view to find a tour
> 
> The button 'take a tour' (like all buttons in the status bar) should not be there if you are in a middle of editing an article, for instance. Or do you think we should make an exception?

Thats a usability / ux question. All I know is that the one place I want to take a tour is when I open an edit form

2023-03-02 19:49 UTC, brianteeman commented
There is a maximum width set for a shepherd-element of 400px but this breaks if you have included an image etc that is wider than 400px

![image](https://user-images.githubusercontent.com/1296369/222536715-7b9ffe7b-bc19-4903-8b12-bc0b15535a01.png)

![image](https://user-images.githubusercontent.com/1296369/222536800-ef390057-f9f7-4838-8854-6edb8f766c3a.png)

2023-03-02 20:01 UTC, brianteeman commented
The modal showing "all tours" is only using colour to indicate visually that something is a link. You should always use at least two visual indicators. Visually there is no way to know that anythign in this screenshot is a link.

![image](https://user-images.githubusercontent.com/1296369/222539055-ae5ad368-2dc3-43c4-882a-310c098ca865.png)

You can also see in the screenshot the page below the modal is a dashboard of links and that in this case the links all have a visual styling of colour AND underline

2023-03-02 20:23 UTC, brianteeman commented
have you tried it on a mobile device? its not usable as you cannot get to the new button

![image](https://user-images.githubusercontent.com/1296369/222543429-9d9e91ca-33ed-410b-8fc8-3c0c55804447.png)

2023-03-02 20:59 UTC, obuisard commented
> have you tried it on a mobile device? its not usable as you cannot get to the new button

Yes. We hide elements in the interface on mobile. That complicates things... 
I was thinking tours should only be available on screens larger than 576px.

2023-03-03 01:25 UTC, obuisard commented on package.json
> +    "rtlcss": "^3.5.0",
Removed. Was a left over after changes made. Thanks!

2023-03-03 01:26 UTC, obuisard commented on administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
> +    public static function setStepLanguage(int $id, string $language = '*'): string
Get tour title and language removed from helper.

2023-03-03 07:10 UTC, brianteeman commented
https://github.com/joomla/joomla-cms/pull/39902/files#r1123503070

You misunderstood the comment. It was referring to rtlcss not to shepherd

2023-03-03 07:30 UTC, brianteeman commented
I cant work out the exact scenario or reasoning for adding aria-live assertive https://github.com/joomla/joomla-cms/commit/9922d1df6c6e0902441a6782eb0b3a7b0b3ff92f

But you have to be very careful wth aria-live and dynamic changes or it doesn't work as expected if at all

2023-03-03 07:37 UTC, brianteeman commented
Tab should move forward
Shift tab should move backward

It looks to me as if a recent change has made shift tab work the same as tab. This is not expected behaviour

2023-03-03 13:55 UTC, obuisard commented
> https://github.com/joomla/joomla-cms/pull/39902/files#r1123503070
> 
> You misunderstood the comment. It was referring to rtlcss not to shepherd

Honest mistake, you did not mention what you were talking about :-) Thank you for clarifying.

2023-03-03 13:57 UTC, obuisard commented
> I cant work out the exact scenario or reasoning for adding aria-live assertive [9922d1d](https://github.com/joomla/joomla-cms/commit/9922d1df6c6e0902441a6782eb0b3a7b0b3ff92f)
> 
> But you have to be very careful wth aria-live and dynamic changes or it doesn't work as expected if at all

In my tests (Windows narrator) and after much reading, it prevents the screen reader to read the page information rather than the step after a page refresh.

2023-03-03 13:58 UTC, obuisard commented
> Tab should move forward Shift tab should move backward
> 
> It looks to me as if a recent change has made shift tab work the same as tab. This is not expected behaviour

I have made no such change. There is no code in Guided Tours that changes keys behavior anymore. I can't speak for the Shepherd script, I did not check.

2023-03-03 13:59 UTC, brianteeman commented
> > You misunderstood the comment. It was referring to rtlcss not to shepherd

> Honest mistake, you did not mention what you were talking about :-) Thank you for clarifying.

The comment was just on the one line but guess it can look odd in the gh ui

2023-03-03 13:59 UTC, brianteeman commented
> > Tab should move forward Shift tab should move backward
> > It looks to me as if a recent change has made shift tab work the same as tab. This is not expected behaviour
> 
> I have made no such change. There is no code in Guided Tours that changes keys behavior anymore. I can't speak for the Shepherd script, I did not check.

I did check Shepherd and it works correctly there

2023-03-03 14:04 UTC, brianteeman commented
> > I cant work out the exact scenario or reasoning for adding aria-live assertive [9922d1d](https://github.com/joomla/joomla-cms/commit/9922d1df6c6e0902441a6782eb0b3a7b0b3ff92f)
> > But you have to be very careful wth aria-live and dynamic changes or it doesn't work as expected if at all
> 
> In my tests (Windows narrator) and after much reading, it prevents the screen reader to read the page information rather than the step after a page refresh.

ok so a couple of things. 
1. If it is going to a new page then it should read the page information. Otherwise the unsighted user will not know that the page has changed
2. aria-live is a bit quirky. The intended use is for there to be an area on the page on load that is marked as an aria-live region and then if the content in that region changes then it is announced. polite=> announce as soon as you finish announcing the current thing. assertive=> interupt and announce now. The region must be on the page on load - it can not be injected later. You can only inject a message into the region

2023-03-03 14:22 UTC, brianteeman commented
Smart Search Filter Tour

![image](https://user-images.githubusercontent.com/1296369/222744213-f3507916-3883-43da-896b-73afd2e33fd3.png)

I am not that familiar with this to be honest but I think this should be something more like
Select Options
Select the options for the smart filter here

2023-03-03 14:28 UTC, brianteeman commented
Create a user tour
![image](https://user-images.githubusercontent.com/1296369/222745022-7c8506f6-649b-4e9d-83dd-a5cd610e5dcc.png)

If a password is not entered here then a password will be generated for the user and emailed to them

(you cant go to the next step if you dont enter a password)

Not suprisingly there is nothing in the tour to determine if the password matches the requirements etc. As a result when you try to complete the tour (save and close) you cannot but you cannot see why as the error is obscured.
![image](https://user-images.githubusercontent.com/1296369/222746076-711f235e-2a54-4528-87fa-1b3569cbad00.png)

2023-03-03 14:29 UTC, obuisard commented
> Smart Search Filter Tour
> 
> ![image](https://user-images.githubusercontent.com/1296369/222744213-f3507916-3883-43da-896b-73afd2e33fd3.png)
> 
> I am not that familiar with this to be honest but I think this should be something more like Select Options Select the options for the smart filter here

Agree. We will review all tours and make them more 'useful' and even create more useful ones. Focus was made on the guided tours functionality and accessibility first to have a solid basis, which we can build on.

2023-03-03 16:46 UTC, joomdonation reviewed
Base on my code review (I'm unsure if it is 100% valid), there are still some issues with the code need to be addressed.

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        if (empty($record->id) || $record->published != -2) {
This should be moved to top of method so that we return early when conditions meet.

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        if (!$this->getCurrentUser()->authorise('core.delete', $component . '.state.' . (int) $record->id)) {
The permission check here looks strange to me. Seems it is copied base on code of com_workflow and it is not right here. The logic could be simple like below:

- If there is tour_id for this step (which should be always), check delete permission of that tour
- If tour_id is empty for whatever result, check delete permission from the component

The code of this whole method could be re-written like below

```php
protected function canDelete($record)
{
	if (empty($record->id) || $record->published != -2) {
		return false;
	}
	
	if ($record->tour_id) {
		return $this->getCurrentUser()->authorise('core.delete', 'com_guidedtours.tour.'.$record->tour_id );
	}

	return parent::canDelete($record);
}
```

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        $tourID     = $app->getUserStateFromRequest($context . '.filter.tour_id', 'tour_id', 0, 'int');
This should always be submitted from form, so I don't understand why we need to get tourId from session here?

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +    protected function canEditState($record)
Same for delete permission check. Since we do not have permission defined for step, it should inherit permission check of the tour it belong to. The code could be something like:

```php
$app             = Factory::getApplication();
$context         = $this->option . '.' . $this->name;
$tourID          = $app->getUserStateFromRequest($context . '.filter.tour_id', 'tour_id', 0, 'int');
$record->tour_id = $tourID;

// Check for existing tour.
if (!empty($record->tour_id))
{
	return $this->getCurrentUser()->authorise('core.delete', 'com_guidedtours.tour.' . $record->tour_id);
}

return parent::canEditState($record);
```

I also under if we need to set $record->tour_id here. I have the feeling that it should not be here, but have to check it more. So in the simplest case, the code could be just:

```php
// Check for existing tour.
if (!empty($record->tour_id))
{
	return $this->getCurrentUser()->authorise('core.delete', 'com_guidedtours.tour.' . $record->tour_id);
}

return parent::canEditState($record);
```

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +                $result->language = $tourLanguage;
Why don't you set data for tour_id here? Look like below like is missing. Then you won't have to get tourID from session in edit step layout anymore
```php
$result->tour_id = $tourID;
```

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepsModel.php
> +    protected function getReorderConditions($table)
Unless I miss something, this method should not belong to list model. Normally, it should belong to an admin model instead (have to check it again to see if it is still needed in admin model or it could just be removed)

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/src/Model/StepsModel.php
> +    public function getTable($type = 'Step', $prefix = 'Administrator', $config = [])
Is the method really needed here?

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/tmpl/step/edit.php
> +$tour_id = $app->getUserState('com_guidedtours.tour_id');
I'm unsure it's right to get $tourId like that. If the getItem from Step model properly implemented, we should should have the tour id by accessing to $this->item->tour_id already.

2023-03-03 16:46 UTC, joomdonation commented on administrator/components/com_guidedtours/tmpl/step/edit.php
> +    <input type="hidden" name="tour_id" value="<?php echo $tour_id; ?>">
As we have tour_id as a hidden field in the form, instead of writing hidden input manually like this, better use :

```php
<?php echo $this->form->getInput('tour_id'); ?>
```

2023-03-03 16:57 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        if (empty($record->id) || $record->published != -2) {
Good catch

2023-03-03 17:02 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        if (!$this->getCurrentUser()->authorise('core.delete', $component . '.state.' . (int) $record->id)) {
Yeah, much better

2023-03-03 17:04 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +        $tourID     = $app->getUserStateFromRequest($context . '.filter.tour_id', 'tour_id', 0, 'int');
For new steps, I believe

2023-03-03 17:08 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +    protected function canEditState($record)
I suppose you meant to set core.edit.state and not core.delete here

2023-03-03 17:16 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepsModel.php
> +    public function getTable($type = 'Step', $prefix = 'Administrator', $config = [])
Yes, I believe, to set the Step table name

2023-03-03 17:38 UTC, obuisard commented on administrator/components/com_guidedtours/tmpl/step/edit.php
> +    <input type="hidden" name="tour_id" value="<?php echo $tour_id; ?>">
Ok!

2023-03-03 17:43 UTC, brianteeman commented
i assume you realise that it doesnt support workflows

2023-03-03 17:55 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepModel.php
> +                $result->language = $tourLanguage;
Agree

2023-03-03 17:55 UTC, obuisard commented on administrator/components/com_guidedtours/tmpl/step/edit.php
> +$tour_id = $app->getUserState('com_guidedtours.tour_id');
Agreed

2023-03-03 18:00 UTC, obuisard commented on administrator/components/com_guidedtours/src/Model/StepsModel.php
> +    protected function getReorderConditions($table)
It's not present in the ListModel so should not be here.

2023-03-03 22:54 UTC, sdwjoomla commented
Great job everyone. Thank you for your hard work.

2023-03-03 22:56 UTC, merged

2023-03-03 23:11 UTC, brianteeman commented
:(

2023-03-03 23:12 UTC, brianteeman commented
This is a great component but it is not ready to be released and is still not accessible

2023-03-05 10:47 UTC, alikon commented
and my question too is why ?

2023-03-05 10:49 UTC, alikon commented
there are no successfull test & and for a big pr like this 1 it should be the minimum requirements

2023-03-23 07:29 UTC, tecpromotion commented
@obuisard language badge is missing. GitHub Actions are therefore not running.

2023-03-23 14:01 UTC, obuisard commented
Hi Stefan @tecpromotion, is there anything needed from me for translations? I have added the label (sorry it was missing).