[4.3][Guided Tours] Administrator console unresponsive when CSS selector is invalid
joomla/joomla-cms pull request #40054
Opened 2023-03-09 03:03 UTC by obuisard

When someone creating a tour enters a selector that is not valid, the tour does not start, produces an error in the browser console, nothing happens but the tour keeps trying to start until the user logs out. The user receives no feedback, unless he/her is aware of the browser console.

### Summary of Changes

We already caught the error but the session storage was not cleared.
This PR clears the storage on error and produces an error message for the user.

### Testing Instructions

Create a step on edit a step in a tour. Enter an invalid target, for instance `#1_tada`. This selector is invalid because it starts with a number.
Start the tour. you should see the error message:

![image](https://user-images.githubusercontent.com/5964177/223905091-8244dd0d-e6ba-4a3f-97b7-60e2fa81a51b.png)

### Actual result BEFORE applying this Pull Request

The tour does not start, there is no user feedback and the user needs to logout to recover.

### Expected result AFTER applying this Pull Request

The tour does not start, the administrator console is unaffected, a message pops up explaining that the tour cannot run and the user can resume activities.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-03-09 09:53 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 99b66de2c7e9009b29b34050cd6d405a2c8efc6c<br /><br />not a fan of the tone of the message but can confirm that it does what it says<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40054">issues.joomla.org/tracker/joomla-cms/40054</a>.</sub>

2023-03-09 10:12 UTC, laoneo commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +        console.log(`Exception error - ${error.message} - Tour stopped`);
Thanks you for the pull request. Unfortunately I don't think so we should log to the console of the browser. Do we do than nowadays?

2023-03-09 10:49 UTC, Fedik commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +        console.log(`Exception error - ${error.message} - Tour stopped`);
This is okay, to help to find a real reason of error.
But please log it without decoration. Make it:
```javascript
console.error(error);
```

2023-03-09 12:39 UTC, dgrammatiko requested changes

2023-03-09 12:39 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +        console.log(`Exception error - ${error.message} - Tour stopped`);
What Allon said, use `throw new Error('Error message')`

2023-03-09 15:51 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +        console.log(`Exception error - ${error.message} - Tour stopped`);
Thanks

2023-03-09 15:54 UTC, dgrammatiko commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +        throw new Error(error);
After the throw nothing else is executed, thus this line needs to move to 396 after `Joomla.renderMessages(messages);`

2023-03-09 16:17 UTC, obuisard commented on build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
> +        throw new Error(error);
You're right, I was not thinking...

2023-03-10 10:54 UTC, khu5h1 commented
I have tested this item :white_check_mark: successfully on c197ca8c0aff65680ffa3bb3ba3c4831bc6ec7e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40054">issues.joomla.org/tracker/joomla-cms/40054</a>.</sub>

2023-03-10 18:03 UTC, Quy commented
I have tested this item :white_check_mark: successfully on c197ca8c0aff65680ffa3bb3ba3c4831bc6ec7e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40054">issues.joomla.org/tracker/joomla-cms/40054</a>.</sub>

2023-03-10 18:03 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40054">issues.joomla.org/tracker/joomla-cms/40054</a>.</sub>

2023-03-12 04:26 UTC, merged