[4.4] Converting from File::exists() to is_file()
joomla/joomla-cms pull request #40113
Opened 2023-03-14 11:37 UTC by Hackwar

### Summary of Changes
In the process of deprecating the CMS Filesystem package, this PR replaces all cases of `File::exists()` with `is_file()`. `File::exists()` is a wrapper for `is_file(Path::clean($path))`, so by removing it, we are removing the `Path::clean($path)`. However, as far as I can see, we either have a safely secure path anyway or it is already wrapped with `Path::clean()`. Where it isn't wrapped, it actually is hardly usefull, because we do a `File::exists($path)` and shortly after use the original value of $path to include that file. Long story short, I think this is a safe change.
I still would like the @joomla/security-leads to have a look at this.

### Testing Instructions
After applying this, nothing should have changed. Thus, a codereview would probably make the most sense here.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

2023-03-14 11:57 UTC, HLeithner requested changes
tbh I have not the feeling that you checked every call if it's save to use simple is_file now without cleaning the path.

2023-03-14 11:57 UTC, HLeithner commented on plugins/system/tasknotification/tasknotification.php
>                          && is_file($attachment)
I Like this change ;-)

2023-03-14 11:57 UTC, HLeithner commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> -            if (!File::exists($localPath)) {
This change seems not so useful isn't it?

2023-03-14 11:57 UTC, laoneo commented on plugins/system/tasknotification/tasknotification.php
> +                        && is_file($attachment)
I guess this can be removed as it is identical to the line below.

2023-03-14 11:57 UTC, laoneo commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +            if (!is_file($localPath)) {
This one doesn't make sense anymore as it makes the opposite check above.

2023-03-14 12:00 UTC, wilsonge commented on plugins/system/tasknotification/tasknotification.php
> +        if (!is_file($formFile)) {
We might still need to run this through clean? check will validate we're not outside the root fs but we're now back to dealing with the unsanitised object and potentially on windows i guess we might have / vs \ issues which clean overcomes.

2023-03-14 12:02 UTC, Hackwar commented on plugins/system/tasknotification/tasknotification.php
> +        if (!is_file($formFile)) {
PHP manages the \ / issue itself already. Which is why we removed all the DS stuff in the past.

2023-03-14 12:15 UTC, Hackwar commented on plugins/system/tasknotification/tasknotification.php
>                          && is_file($attachment)
I removed that line.

2023-03-14 12:16 UTC, Hackwar commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> -            if (!File::exists($localPath)) {
I removed that block.

2023-03-14 12:16 UTC, Hackwar commented on plugins/system/tasknotification/tasknotification.php
> +                        && is_file($attachment)
Done.

2023-03-14 12:16 UTC, Hackwar commented on plugins/filesystem/local/src/Adapter/LocalAdapter.php
> +            if (!is_file($localPath)) {
Removed the whole block.

2023-03-14 12:17 UTC, Hackwar commented
> tbh I have not the feeling that you checked every call if it's save to use simple is_file now without cleaning the path.

I admit, I did not check these cases, but only checked when the variable was last written to.

2023-03-14 12:56 UTC, laoneo commented
Are there any occurrences of `File::exists` left in the core? If not, then I would add the deprecation message right into this pr.

2023-03-14 12:58 UTC, Hackwar commented
No, all occurences have been handled with this. But I would really like to keep the deprecation messages in one PR, among other things because it means I only have to make one PR to the manual repository. If you want me to make 40 PRs to deprecate each method individually, then I would rather defer all that work to you.

2023-03-14 13:03 UTC, laoneo commented
You can make one pr in the manual and then reference it from each of these subsequent pr's. Would that be ok?

2023-03-14 13:10 UTC, Hackwar commented
Not really, because it would mean that I would have to update #40111 several times for each case where a method was deprecated individually. I also would not simply close #40111, because there are several methods and whole classes which we aren't using at all in core. And it means dozens of PRs poluting our history with something being deprecated here and then something there. And if we don't get all existing code converted in time for 4.4, we wouldn't be able to remove it all in 6.0, just because deprecation is supposed to be done in time with migration of the core. I'm not saying that I wouldn't be able to write all that code in time, but considering that I'm waiting for 2.5 years now for people to test the install progress bar, I have zero confidence in that necessary PRs would be merged in time.

2023-03-14 13:14 UTC, laoneo commented
Ok, then leave it as it is.

2023-03-15 06:15 UTC, SniperSister commented
> I still would like the https://github.com/orgs/joomla/teams/security-leads to have a look at this.

Looks ok from the security side of things

2023-03-15 12:21 UTC, Hackwar commented on plugins/system/tasknotification/tasknotification.php
> +        if (!is_file($formFile)) {
Cleaned it.

2023-03-15 12:24 UTC, Hackwar commented
All changes have been applied. Ready to test/codereview/merge. 😃

2023-03-15 15:22 UTC, HLeithner approved these changes

2023-03-15 16:25 UTC, merged

2023-03-15 16:25 UTC, laoneo commented
Thanks!