[RFC] Joomla Popup script. Free, without CC and registration
joomla/joomla-cms pull request #40150
Opened 2023-03-18 14:22 UTC by Fedik

### Summary of Changes

This is implementation of own popup/modal/dialog independend from bootstrap and other traps.
As continue of https://github.com/joomla/joomla-cms/discussions/32473 discussion.

At current point of time the PR provides only popup implementation, the script should be ready to use.
And the integration will come.

I made it for 4.x to be able easily test on "production" codebase. However main target (If I ever finish it) probably > 5.x. 

The PR does not provide a separate stylesheet for popup, the styling should be done within template (example can find in _modal.scss of this PR).
(At bare it use native dialog styling)

### What and why is Joomla Popup

The script allow to create a popup/dialog programaticaly, that in oposite to current Bootstrap implementation, when modal should be prerendered in HTML. This allows more simple integration on client side without involving server side.

It basicaly a wrapper around native `dialog` element.

Joomla Popup script allows to display dialog with following content: 
- `inline` - text or html content;
- `iframe` - embed/remote content, in iframe;
- `ajax` - same as `inline` but the content loaded through ajax request;
- `image` - image lightbox;

Also it provides helper methods for `alert()` and `confirm()` dialogs.
Provides helper to bind page button/anchor to show the popup, for basic stuff, without extra js needed.

### Usage examples

```javascript
// Inline popup
let popup = new JoomlaPopup({
  textHeader: 'The header',
  popupContent: '<p class="p-3">Popup content text</p>',
});
popup.show();

// IFrame
let popup = new JoomlaPopup({
  popupType: 'iframe',
  textHeader: 'The header',
  src: 'index.php?option=com_content&view=articles&tmpl=component&layout=modal',
});
popup.show();

// Ajax
let popup = new JoomlaPopup({
  popupType: 'ajax',
  textHeader: 'The header',
  src: 'index.php?option=com_content&view=articles&tmpl=component&layout=modal',
});
popup.show();

// Image
let popup = new JoomlaPopup({
  popupType: 'image',
  src: '../images/headers/walden-pond.jpg',
});
popup.show();

```

Any property can be set as instance property or in class constructor. This two is equal:

```javascript
// Proprty in class constructor
let popup = new JoomlaPopup({
  textHeader: 'The header',
  popupContent: '<p class="p-3">Popup content text</p>',
});

// Proprty in to class instance
let popup = new JoomlaPopup();
popup.textHeader = 'The header';
popup.popupContent = '<p class="p-3">Popup content text</p>';
```

Other options:
```javascript
// Optional sizing:
popup.width = '80vw';
popup.height = '80vh';

// Definig your own buttons:
popup.popupButtons = [
  { label: 'Yes', onClick: () => popup.close() },
  { label: 'No', onClick: () => popup.close(), className: 'btn btn-outline-danger ms-2' },
];
```

#### Alert and Confirm usage:
```javascript
// Alert
JoomlaPopup.alert('Chase ball of string eat plants, meow')
  .then(() => { 
    console.log('All done'); 
  });

// Confirmation
JoomlaPopup.confirm('Cheese on toast airedale the big cheese?')
  .then((result) => { 
    console.log(result ? 'Okay' : 'Not okay'); 
  });
```

#### Binding button/anchor for basic stuff

```html
<button class="btn btn-primary" type="button"
    data-joomla-popup='{"popupType": "iframe", "width":"80vw", "height": "80vh", "src":"index.php?option=com_content&view=articles&tmpl=component&layout=modal"}'>Click</button>

<button class="btn btn-primary" type="button"
    data-joomla-popup='{"popupType": "inline", "popupContent":"#popupText", "width": "fit-content", "height": "fit-content"}'>Click</button>

<a href="index.php?option=com_content&view=articles&tmpl=component&layout=modal"
  data-joomla-popup class="btn btn-outline-primary">Click</a>
<a href="#popupText" data-joomla-popup class="btn btn-outline-primary">Click</a>

<template id="popupText"><p class="p-3">Popup content text</p></template>
```

### Testing Instructions

Can test any of examples above.
Apply patch, run `npm install`.
Then add `$wa->useScript('popup');` in to index.php of the admin template.
And one of example js/html wherever you want. Eg. in to index.php (will show 2 popup on load):

```html
<script type="module">
JoomlaPopup.alert('Chase ball of string eat plants, meow')
  .then(() => { 
    console.log('All done'); 
  });

JoomlaPopup.confirm('Cheese on toast airedale the big cheese?')
  .then((result) => { 
    console.log(result ? 'Okay' : 'Not okay'); 
  });
</script>
```

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: TBD
- [ ] Pull Request link for manual.joomla.org: TBD

### Issues for reference

- #32473
- #39344
- #39964
- #39449 
- #39609
- #39416

@dgrammatiko I have stole some of your ideas from #39344, I hope you will not sue me :)

2023-03-18 14:31 UTC, dgrammatiko commented on build/media_source/system/js/joomla-popup.w-c.es6.js
> +        this.popupTmplB.insertAdjacentHTML('afterbegin', this.popupContent);
I'm not in favour of this. I would prefer 
```js
this.popupTmplB.insertAdjacentElement('afterbegin', this.popupContent);
```

2023-03-18 14:32 UTC, dgrammatiko commented on build/media_source/system/js/joomla-popup.w-c.es6.js
> +            this.popupTmplB.insertAdjacentHTML('afterbegin', text);
Same here, `insertAdjacentElement` should be better

2023-03-18 14:37 UTC, dgrammatiko commented
LGTM

I left couple of comments on `insertAdjacentHTML` but also before this goes to production it needs the dialog polyfill, you can copy over the code from https://github.com/dgrammatiko/joomla-modal/blob/main/src/index.js and add the package in the package.json (https://github.com/GoogleChrome/dialog-polyfill)

2023-03-18 14:41 UTC, Fedik commented on build/media_source/system/js/joomla-popup.w-c.es6.js
> +        this.popupTmplB.insertAdjacentHTML('afterbegin', this.popupContent);
It willl not work for string,
either `el.innerHTML = 'potato'` or `el.insertAdjacentHTML ('afterbegin', 'potato')`;

2023-03-18 14:43 UTC, Fedik commented
> also before this goes to production it needs the dialog polyfill,

At time when it will happen, we will be no need polifill :smile: 
Well, yeah sure, can be added, but as last thing here, not really important for now.

2023-03-18 14:44 UTC, dgrammatiko commented on build/media_source/system/js/joomla-popup.w-c.es6.js
> +        this.popupTmplB.insertAdjacentHTML('afterbegin', this.popupContent);
There's [`setHTML`](https://web.dev/sanitizer/) which is safe but maybe for the time (it's not supported across browsers) use the `Joomla.sanitize` or whatever is the name of that method

2023-03-18 14:47 UTC, Fedik commented on build/media_source/system/js/joomla-popup.w-c.es6.js
> +        this.popupTmplB.insertAdjacentHTML('afterbegin', this.popupContent);
The idea that it already should be done, outside of this script.

2023-03-18 14:49 UTC, dgrammatiko commented
> Well, yeah sure, can be added, but as last thing here, not really important for now

Sure, so apart the innerHML part everything else are spot on on what we had discussed. Maybe the anchor shouldn't be included, for a11y reasons, ie: the dialog should be opened from a button but that's bikeshedding that someone else should do.

I will try to play a bit with it tomorrow but I think it's already in very good shape

2023-03-18 15:03 UTC, dgrammatiko commented
@Fedik one little change: could you rename this to `JoomlaDialog` and all the instances of `popup` to `dialog`? The reason is that later this year the platform will have (already on chrome) the [`popover`](https://github.com/w3ctag/design-reviews/issues/743) so this should be easily distinguishable

2023-03-18 15:11 UTC, Fedik commented
I see, makes sense, yes I will rename

2023-03-18 15:22 UTC, Fedik commented on build/media_source/system/js/joomla-popup.w-c.es6.js
> +        this.popupTmplB.insertAdjacentHTML('afterbegin', this.popupContent);
hmhm, okay, I will add Joomla.sanitize here (and ajax).

2023-03-19 14:48 UTC, dgrammatiko requested changes

2023-03-19 14:48 UTC, dgrammatiko commented on build/media_source/system/js/joomla-dialog.w-c.es6.js
> +    this.dialog.showModal();
```suggestion
    this.dialog.showModal();
    Joomla.Modal.setCurrent(this);
```

2023-03-19 14:48 UTC, dgrammatiko commented on build/media_source/system/js/joomla-dialog.w-c.es6.js
> +    this.dialog.close();
```suggestion
    this.dialog.close();
    Joomla.Modal.setCurrent(null);
```

2023-03-20 08:37 UTC, Fedik commented on build/media_source/system/js/joomla-dialog.w-c.es6.js
> +    this.dialog.showModal();
I would leave it for the script which will use it. 
It is not reliable to do it here, example when you open multiple dialogs.

2023-03-20 10:03 UTC, dgrammatiko commented
@laoneo could we have a decision for 4.4 here? This PR will unlock the fixes needed all around the broken repeatables, modal fields, etc
There's an actual implementation for the fields User and Media here: https://github.com/joomla/joomla-cms/pull/40152

2023-03-20 10:11 UTC, laoneo commented
@dgrammatiko what for a decisions you expect? If this can go into 4.4? As @Fedik already mentioned in the pr description, this should finally be merged into 5.0 as 4.4 will not get any new features.

2023-03-20 10:14 UTC, dgrammatiko commented
So 4.3 was the last minor that had new features? Well, 🤬

2023-03-20 10:14 UTC, laoneo commented
What is the problem to ship it with 5.0? They will be released at the same time.

2023-03-20 10:16 UTC, dgrammatiko commented
> What is the problem to ship it with 5.0? They will be released at the same time.

I guess some dev will be complaining, like the did with the WAM, that they need 2 different code snippets in order to support both v4 and v5...

2023-03-20 10:21 UTC, laoneo commented
As long as the old way still works, they should then use that. And yes, when they want the new dialog/popup/modal, then they need to have different code which is dependent on the Joomla version. I don't see this as a big issue.

2023-03-20 10:30 UTC, dgrammatiko commented
> As long as the old way still works, they should then use that.

The old way (bootstrap) works but devs SHOULD NOT use them for fields, editor buttons, etc that are already broken right now because this approach is doing SSR (Server Side Rendering) of the modals which are incompatible with repeatable fields. Same goes for the category fields for different reason. My point is that the script should be introduced in the 4.x so the transition would be easier...

2023-03-20 12:49 UTC, Fedik commented
I think 5.x+ is fine, maybe we will get some better ideas untill then. 
And I would like to finish #40082 before this, and try different approaches for (cross)editor buttons.

2023-03-20 12:55 UTC, dgrammatiko commented
> And I would like to finish https://github.com/joomla/joomla-cms/pull/40082 before this, and try different approaches for (cross)editor buttons.

I was thinking doing the first implementation with the buttons based on this PR and the #40082 but it needs also extending the `Joomla.editors` to have something like 

```js
Joomla.editors = {
  instances: {},
  buttonsCallbacks: {
    ['plg_editors-buttons_readmore']: () => { /* the code for the callback */ },
  },
}
```

2023-03-20 13:08 UTC, Fedik commented
I thinking about something generic, that can handle basic stuf without extra coding, and allow to be extended when needed.

2023-03-20 13:18 UTC, dgrammatiko commented
> I thinking about something generic, that can handle basic stuf without extra coding, and allow to be extended when needed.

My idea for the editor buttons was:
- create a new plugin group, ie `editor-buttons` and for J4/5 check both, with J6 only `editor-buttons` would exist
- The plugin instead of returning a php object (CMSObject) would just register the buttons in the `Joomla.editors` as a JS object { name, icon, etc }
- The plugin would register the `onClick` function on the `Joomla.editors`
- The plugin would also return true on the PHP side if the plugin is enabled on the particular instance of the editor
- The editor should render (client side) the buttons and bind either the modal or the onClick

This way on every repeatable instance the buttons will work as expected (the editor init function has the responsibility to handle those, ie: tiny will render them inside a toolbar but others could/would render them bellow the editing area)

2023-03-20 13:54 UTC, laoneo commented
Didn't look to deep into the code, but is it possible to adapt the output of a modal with a template override as you can do now with the BS ones?

2023-03-20 13:57 UTC, Fedik commented
> Didn't look to deep into the code, but is it possible to adapt the output of a modal with a template override as you can do now with the BS ones?

It does not depend from server layout anymore. Pure "client side", almost.

2023-03-20 13:59 UTC, dgrammatiko commented
> is it possible to adapt the output of a modal with a template override as you can do now with the BS ones?


You could use a `<template>` element with some HTML and have the modal initiator script pick the parts (Header, body, footer) and use them. The problem with all the Fields but also with other parts of the CMS is that you end up with repeated HTML fragments. There was once a PR that could solve this with a `deferred` renderer https://github.com/joomla/joomla-cms/pull/37330

2023-03-20 14:24 UTC, laoneo commented
> It does not depend from server layout anymore.

This does mean, it doesn't follow our current way of doing, that output is generated in a specific layout file. I'm not sure if all people will be happy with this. Just want to point that out. I'm not against the new approach, but it should then be documented somehow.

2023-03-20 15:58 UTC, dgrammatiko commented
> I'm not sure if all people will be happy with this. Just want to point that out.

They can still use BS Modal this PR is NOT replacing the BS Modal script, the latter is still available.
For highly interactive elements (Fields, repeatable, etc) the pre-rendered html just doesn't scale/work so it needs to be abandoned and switch to client side rendering (btw the media manager has also 0 lines of php layouts and there are other instances, so the assumption that Joomla\s current way is exclusive SSR is a lie). On the other hand the project could keep everything broken because people think that it's a heresy to have client side rendered elements...

2023-03-30 06:14 UTC, laoneo commented
I guess it is better to rebase this pr to the 5.0-dev branch, as it will get more attention for new features. Thanks for understanding.

2023-04-07 13:08 UTC, HLeithner commented
@Fedik can you rewrite/change a joomla action (maybe com_content modal select field) so I can have a better feeling how this works with the joomla code base?

I expect you only have to change the layout of the field right?

2023-04-07 13:13 UTC, dgrammatiko commented
@HLeithner try this https://github.com/joomla/joomla-cms/pull/40152

2023-04-07 13:17 UTC, HLeithner commented
> @HLeithner try this #40152

this looks really complex for using a simple popup/modal?!

2023-04-07 13:45 UTC, dgrammatiko commented
> this looks really complex for using a simple popup/modal?!

@HLeithner not really, these 2 fields have a dependency on the BS Modal as of 4.3.0. The changes to convert them to the new one are not complex but maybe this is not the easiest example. The easiest example would be some toolbar popup button, where the code would be significantly less or some of the move/copy buttons (eg banners, articles, etc). I'm quite busy atm to code such an example, but for what is worth, this approach of the modals has my support (it's an iteration/improvement of my exploratory [PR](https://github.com/joomla/joomla-cms/pull/39344) and according to the specs that were set in the [discussion](https://github.com/joomla/joomla-cms/discussions/32473)). In sort it's a step forward, it eliminates a number of existing XSS and it's a better fit for the project as it's tailored to the actual needs...

2023-04-07 13:47 UTC, Fedik commented
If you remamber `SqueezeBox` from < joomla 2.5, that will be similar.

> I expect you only have to change the layout of the field right?

For basic stuff yes.
But, for make it "good" there also will be need some JS changes. 

That one #40202 based on current pr, it uses new popup for all XTD buttons (except media).

https://github.com/joomla/joomla-cms/blob/8402b8ff1f6202de434012f0bbef8db1c7bebc93/build/media_source/system/js/editors.es6.js#L361-L379

This is shared "modal" action, for XTD buttons, that replaces `layouts/joomla/editors/buttons/modal.php` which rendered for every modal button.

2023-04-07 13:54 UTC, Fedik commented
>  rewrite/change a joomla action (maybe com_content modal select field) 

com_content "modal select" field is pretty complex field, 
that is heavily coupled with horror inside `media/system/js/fields/modal-fields.js`
Would be a bad example :smile: 

This will probably require multiple steps for updated that.

2023-04-07 13:56 UTC, dgrammatiko commented
> This will probably require multiple steps for updated that.

It can be in one step but the PHP side of the code introduces B/C breaks: https://github.com/joomla/joomla-cms/pull/39351

2023-04-07 17:36 UTC, Fedik commented
@HLeithner Here is simpliest example that I found :) 
 https://github.com/joomla/joomla-cms/compare/5.0-dev...Fedik:joomla-cms:popup-guidedtour-viewall

Replacing modal "Show all tours".

2023-04-10 14:08 UTC, Fedik commented
@HLeithner there I tried more simple example #40359 :)

2023-04-10 14:20 UTC, HLeithner commented
thanks, I tried this pr and on the second click it was broken (guidedtour branch) ;-) you can't open a popup again.
Also in the guided tour plugin you removed the code that handles the tab-path out of modal

2023-04-10 14:34 UTC, Fedik commented
>  you can't open a popup again

Yes there was a bug in Dialog script, I have fixed that, in one of last commits here. You probably have to re-run 'npm' on new changes.

> Also in the guided tour plugin you removed the code that handles the tab-path out of modal

We do not need it anymore with Dialog, just try, the "tab" should work as usual.

2023-04-23 10:45 UTC, Fedik commented
@HLeithner there #40462 a prototype what I have in mind for Modal_Article field (similar will be for Category, Menu and other Modal_x)

2023-05-06 09:06 UTC, brianteeman commented
_every time I see this pr I wonder why we have an RFC about Credit Cards_

2023-05-06 09:09 UTC, HLeithner commented
> _every time I see this pr I wonder why we have an RFC about Credit Cards_

pretty sure we need credit card support

2023-05-11 04:51 UTC, Flowman commented
Sorry to be late to the party. Is there a reason why we don't use the new dialog html element? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

2023-06-19 12:40 UTC, brianteeman commented
From what I can tell this works as per the instructions

2023-07-02 09:00 UTC, Fedik commented
> Is there a reason why we don't use the new dialog html element?

What do you suggest?

2023-08-11 11:12 UTC, HLeithner commented
One question, shouldn't this be part of our Joomla Super Global Object/Namespace instead of the JoomlaDialog -> joomla.dialog?

2023-08-11 11:34 UTC, dgrammatiko commented
> One question, shouldn't this be part of our Joomla Super Global Object/Namespace instead of the JoomlaDialog -> joomla.dialog?

Actually the custom element should be exported (without being registered in the registry) and then whatever script needs the modal should import the script (using the importmaps) and have some code (pseudo) like:

```js
import JoomlaDialog from 'Joomla-dialog';

if (!customElements.get('joomla-dialog')) {
  customElements.define('joomla-dialog', JoomlaDialog);
}

// code specific to the script...

```

2023-08-11 12:14 UTC, Fedik commented
> JoomlaDialog -> joomla.dialog

JoomlaDialog is a class that represent a custom element in DOM, there no point to place it under Joomla.
It may live without Joomla very well (under some conditions).

It kind of `<img>`:
```javascript
const img = new Image;
img.src = 'blabla.png';
```
But for `<joomla-dialog>`

> Actually the custom element should be exported

I thought about it, but would keep it as 1 file, for now. 
We can split it at any time, if there will be a real demand.

2023-08-11 12:18 UTC, dgrammatiko commented
@Fedik re checking the code what I meant was:
- keep it as one file
- replace `window.JoomlaDialog = JoomlaDialog;` with `export default JoomlaDialog;`
- add the script also as an importmap

So any other script that needs to construct a dialog will do:
```js
import JoomlaDialog from 'Joomla-dialog';

const myDialog = new JoomlaDialog(someConfig);

// the rest...

```

2023-08-11 12:23 UTC, Fedik commented
hmhm, yeah that can work.
I just not sure if doing a registration of anything in DOM while doing import is a good idea.

2023-08-11 12:25 UTC, Fedik commented
I will do some tests, and probably will update the PR

2023-08-14 15:27 UTC, Fedik commented
Okay, I made it as a module:
```javascript
import JoomlaDialog from 'joomla.dialog';

const dialog = new JoomlaDialog();
dialog.textHeader = 'The header';
dialog.popupContent = '<strong>blabla very strong text</strong>';
dialog.show();
```

Any other sugestions/wishes before I update Manual PR?

2023-08-14 17:43 UTC, HLeithner commented
2 things would be great.

1. A css for frontend independen from the template because it's use less now in frontend
2. footerText adding text or html to the left side of the footer (like the legend for codemirror)
3. Maybe a backdrop?

I tested it and it works as expected.

2023-08-15 10:06 UTC, HLeithner commented
hmm, I thought more on a css file I can use in my own frontend template as base and not only cassiopia, what do you thing?

2023-08-15 10:26 UTC, Fedik commented
By default it use a browser default styling for dialog.
I have fixed iframe sizing, now it pretty usable without extra css.

Backdrop also there, it is browser default.

About footerText. I not very want to overload with features, and keep it simple.
However it still possible to customize:
```javascript
const dialog = new JoomlaDialog();
dialog.textHeader = 'The header';
dialog.popupContent = '<strong>blabla very strong text</strong>';
// Customise footer
dialog.getFooter().insertAdjacentElement('afterbegin', (() => {
  const el = document.createElement('div');
  el.innerText = 'Footer text';
  return el;
})());
dialog.getFooter().classList.remove('empty');
dialog.show();
```

2023-08-21 07:43 UTC, merged

2023-08-21 07:44 UTC, HLeithner commented
thanks, I think it's a starting point, even if I would add a css which is (or could be) part of the webasset with a nicer styling

2023-11-04 18:08 UTC, coolcat-creations commented
Does this issue have something to do with this topic here?

https://github.com/joomla/joomla-cms/issues/42291<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40150">issues.joomla.org/tracker/joomla-cms/40150</a>.</sub>

2024-07-23 10:08 UTC, dgrammatiko commented on build/media_source/system/js/joomla-dialog.w-c.es6.js
> +      this.dispatchEvent(new CustomEvent('joomla-dialog:load'));
@Fedik is there a reason that this event doesn't bubble?

2024-07-23 11:06 UTC, Fedik commented on build/media_source/system/js/joomla-dialog.w-c.es6.js
> +      this.dispatchEvent(new CustomEvent('joomla-dialog:load'));
Yes, same as for native `load` event, the load event does not buble. https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event

> Note: All events named load will not propagate to Window ...

2024-07-23 11:13 UTC, dgrammatiko commented on build/media_source/system/js/joomla-dialog.w-c.es6.js
> +      this.dispatchEvent(new CustomEvent('joomla-dialog:load'));
I mean the custom event `joomla-dialog:load`, not the `load`...

2024-07-23 12:01 UTC, Fedik commented on build/media_source/system/js/joomla-dialog.w-c.es6.js
> +      this.dispatchEvent(new CustomEvent('joomla-dialog:load'));
Yes, I know, but I wanted to keep it as other "load" doing

2024-09-19 09:22 UTC, Frank-MandarinFish commented
Hey, since JoomlaDialog is now a module script I think it would be useful to have a little section in the manual that shows how this class can be used in "classic" non-module script, as the import function can only be called from another module script. The current manual gives the impression you can use the JoomlaDialog class in any script.

For example static:
<script type="module">
    import JoomlaDialog from "joomla.dialog";
    window.JoomlaDialog = JoomlaDialog;    
</script>

Or dynamic:
async function run() {
  const JoomlaDialog = await import('joomla-dialog.js');
  dialog = new JoomlaDialog();
}
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40150">issues.joomla.org/tracker/joomla-cms/40150</a>.</sub>

2024-09-21 10:03 UTC, fgsw commented
> I think it would be useful to have a little section in the manual

@Frank-MandarinFish As far as i know everybody can contribute to the [manual](https://manual.joomla.org/)