Convert media action plugins to service provider
joomla/joomla-cms pull request #40169
Opened 2023-03-22 12:30 UTC by laoneo

### Summary of Changes
Converts the media action plugins to service providers.

### Testing Instructions
Edit an image in the media manager.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-03-22 14:15 UTC, sandewt commented on plugins/media-action/resize/services/provider.php
> +    public function register(Container $container)
In case of the plugin PageNavigation I added here : `void`

`public function register(Container $container): void`

2023-03-22 15:11 UTC, laoneo commented on plugins/media-action/resize/services/provider.php
> +    public function register(Container $container)
I never did, but did it now. Can you make a pr which changes all the other places, which don't have that?

2023-03-22 15:25 UTC, sandewt commented on plugins/media-action/crop/services/provider.php
> +     * @since
add `__DEPLOY_VERSION__`  (3 x)

2023-03-22 19:47 UTC, laoneo commented on plugins/media-action/crop/services/provider.php
> +     * @since
added, thanks!

2023-03-23 09:46 UTC, sandewt commented
Incredibly powerful result with a system test. That's why I show the result here.

 How to get started with system tests can be found in this article https://github.com/joomla/joomla-cms/blob/4.4-dev/tests/System/README.md.

![issue_40169](https://user-images.githubusercontent.com/9271775/227163159-63ed1bd3-5371-4a8c-b7a8-d13a2874efab.png)

2023-03-24 15:34 UTC, MacJoom commented
I have tested this item :white_check_mark: successfully on 6ecde3f13a1a44097c98dc314ec0820b06c17ad9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40169">issues.joomla.org/tracker/joomla-cms/40169</a>.</sub>

2023-04-01 07:46 UTC, heelc29 commented on plugins/media-action/resize/src/Extension/Resize.php
> +        if ($imgObject->getWidth() < $this->params->get('batch_width', 0) && $imgObject->getHeight() < $this->params->get('batch_height', 0)) {
Is there a reason for this codestyle change?

2023-04-01 07:59 UTC, laoneo commented on plugins/media-action/resize/src/Extension/Resize.php
> +        if ($imgObject->getWidth() < $this->params->get('batch_width', 0) && $imgObject->getHeight() < $this->params->get('batch_height', 0)) {
Easier to read

2023-04-01 08:07 UTC, heelc29 commented on plugins/media-action/resize/src/Extension/Resize.php
> +        if ($imgObject->getWidth() < $this->params->get('batch_width', 0) && $imgObject->getHeight() < $this->params->get('batch_height', 0)) {
Ok

2023-04-01 08:13 UTC, heelc29 requested changes
not necessary

2023-04-01 08:13 UTC, heelc29 commented on tests/System/integration/plugins/media-action/crop/CropPlugin.cy.js
> +    cy.doAdministratorLogin(Cypress.env('username'), Cypress.env('password'));
```suggestion
    cy.doAdministratorLogin();
```

2023-04-01 08:13 UTC, heelc29 commented on tests/System/integration/plugins/media-action/resize/ResizePlugin.cy.js
> +    cy.doAdministratorLogin(Cypress.env('username'), Cypress.env('password'));
```suggestion
    cy.doAdministratorLogin();
```

2023-04-01 08:13 UTC, heelc29 commented on tests/System/integration/plugins/media-action/rotate/RotatePlugin.cy.js
> +    cy.doAdministratorLogin(Cypress.env('username'), Cypress.env('password'));
```suggestion
    cy.doAdministratorLogin();
```

2023-04-01 08:36 UTC, laoneo commented on tests/System/integration/plugins/media-action/crop/CropPlugin.cy.js
> +    cy.doAdministratorLogin(Cypress.env('username'), Cypress.env('password'));
Is not needed anymore, it takes the config from the env anyway.

2023-04-01 08:36 UTC, laoneo commented on tests/System/integration/plugins/media-action/resize/ResizePlugin.cy.js
> +    cy.doAdministratorLogin(Cypress.env('username'), Cypress.env('password'));
Is not needed anymore, it takes the config from the env anyway.

2023-04-01 08:36 UTC, laoneo commented on tests/System/integration/plugins/media-action/rotate/RotatePlugin.cy.js
> +    cy.doAdministratorLogin(Cypress.env('username'), Cypress.env('password'));
Is not needed anymore, it takes the config from the env anyway.

2023-04-01 13:55 UTC, heelc29 commented
I have tested this item :white_check_mark: successfully on 739a92fcbce38e8a16836a0595434c08ba539418<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40169">issues.joomla.org/tracker/joomla-cms/40169</a>.</sub>

2023-04-02 15:17 UTC, joomdonation commented on plugins/media-action/resize/src/Extension/Resize.php
> +        if ($imgObject->getWidth() < $this->params->get('batch_width', 0) && $imgObject->getHeight() < $this->params->get('batch_height', 0)) {
Master of taste for me, the original code is easier to read .

2023-04-02 15:18 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on 739a92fcbce38e8a16836a0595434c08ba539418<br /><br />Code review. Tried various actions from these converted plugins and it is still working OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40169">issues.joomla.org/tracker/joomla-cms/40169</a>.</sub>

2023-04-02 15:19 UTC, joomdonation commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40169">issues.joomla.org/tracker/joomla-cms/40169</a>.</sub>

2023-04-03 18:32 UTC, merged