Allow articles with missing workflow data
joomla/joomla-cms pull request #40176
Opened 2023-03-23 06:03 UTC by Denitz

### Summary of Changes

We need to fix these problems:

1. Articles imported into `#__content` table are not displayed in backend because current `ArticlesModel` has a weird `INNER JOIN` on `#__workflow_associations` table which can not contain the data for the articles imported manually.
2. With enabled workflow feature, the article association in `#__workflow_associations` table is not automatically re-created on article save.
3. I am sure that most of Joomla users are not using workflows, hence we need to use `#__workflow_XXX` tables only on demand. Similar like for associations.
4. It will de-couple articles from #__workflow tables because we don't need this relationship if workflows are not used. Imho, the normal idea was to add `workflow_stage_id` column into `#__content table` and don't create `#__workflow_associations` which contains the mixed data from multiple extensions and makes a spaghetti in the database. Anyway, it's not the topic for this PR.

### Testing Instructions

Import articles into #__content table directly.

These articles are not displayed in backend with/without workflow enabled.

Enable workflow and try to edit such article directly via ID in URL, save article - still no displayed.

### Actual result BEFORE applying this Pull Request

No articles are displayed in backend.
No items are re-created in #__workflow_associations after article save with enabled workflow feature.

### Expected result AFTER applying this Pull Request

All fine.

2023-03-23 06:22 UTC, brianteeman commented
The problem is with the import script being used not with the core code. This pr is obviously wrong

2023-03-23 07:06 UTC, Denitz commented
@brianteeman I would totally disagree, what for do we need this extra dependency on `#__workflow_associations` table even if we don't use workflows?

2023-03-23 07:08 UTC, brianteeman commented
You have a j3 site with a thousand articles. You upgrade to j4 and decide to use workflows. With this PR you can not do that  unless you open and save all thousand articles

2023-03-23 07:11 UTC, Denitz commented
No.

This PR doesn't affect this case. It doesn't block creation of `#__workflow_associations` records for articles if workflow is disabled. It works event better and auto-creates missing records to minimize possible data loss.

2023-03-23 07:14 UTC, brianteeman commented
How does it auto-create the missing record without the article being opened and saved again?

Honestly just fix the script you are using to import the articles

2023-03-23 07:27 UTC, Denitz commented
Two purposes:
1. Don't load workflows data if workflows are not enabled.
2. Auto-create missing workflow association on save of existing article.
It helps to fix the possible issues with inconsistent database data. Otherwise, if article record is missed in `#__workflow_associations`, the user won't even see this article in backend.

Maybe we also need to always have records in `#__content_rating` table for all articles and INNER JOIN on it?

2023-03-23 07:39 UTC, brianteeman commented
Exactly as I said. You cannot use workflow unless you open and save again all thousand articles

2023-03-23 08:07 UTC, Denitz commented
At least I will be to do it.

2023-10-18 17:20 UTC, wilsonge commented
I think the conditional join in the articles model is fine - that's how things already work for other extensions like voting and associations.

The part in default.php is also totally fine

I think the problem is in the workflow trait. This could be triggered in the frontend and be run on unlimited sites. I really don't think this is the right place to have it if you want to create associations. It's no different to the fact we don't magically create assets either. I'd remove it from here and it's fine. If we don't remove it I'm against this being merged in the current form. I'd be happy enough if it was some sort of backend status check.

2023-10-18 17:55 UTC, bembelimen commented
Nice improvements.

Still I agree with @wilsonge here, we should not try to fix workflow associations when opening the article (read: the changes in the trait should not be done) but have a way to recover from a e.g. "broken" import without associations. All the other fixes are good, but could you (@Denitz ) enhance this PR to use the database repair to fix associations? (This could later be enhanced to also fix menus, categories, asset structures).

2024-04-24 09:08 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2024-09-02 08:52 UTC, HLeithner commented
This pull request has been automatically rebased to 5.3-dev.

2024-09-15 13:26 UTC, richard67 commented
System tests are failing with PHP warning:
`Undefined property: stdClass::$stage_title in /tests/www/cmysql/administrator/components/com_content/tmpl/articles/default.php
 on line 169`. That could be caused by the changes of this PR in the articles model.

2024-09-15 13:43 UTC, brianteeman commented
@richard67 as stated by others the failing system tests are the least of the issue with this PR

2024-09-15 13:52 UTC, richard67 commented
> @richard67 as stated by others the failing system tests are the least of the issue with this PR

@brianteeman Sure. I just wanted to document them here.

2024-09-15 15:36 UTC, Denitz commented
> Undefined property: stdClass::$stage_title in /tests/www/cmysql/administrator/components/com_content/tmpl/articles/default.php on line 169

Fixed.

2025-03-04 17:22 UTC, HLeithner commented
This pull request has been automatically rebased to 6.0-dev.

2025-06-29 13:42 UTC, richard67 commented
See PR #45660 for an alternative solution.

2025-06-29 16:44 UTC, bembelimen requested changes
This PR is a clear no. Associations needs to be created when articles are saved while workflow is diabled.

2025-07-03 12:18 UTC, Denitz commented
Closed in favour of #45660

2025-07-03 12:18 UTC, closed without merging