Convert privacy plugins to service provider
joomla/joomla-cms pull request #40174
Opened 2023-03-22 19:56 UTC by laoneo

### Summary of Changes
Converts the media action plugins to service providers.

### Testing Instructions
Create some contacts and assign a user to them, then make an export request and export the contact data. Same for content.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-03-26 10:57 UTC, heelc29 requested changes

2023-03-26 10:57 UTC, heelc29 commented on plugins/privacy/contact/services/provider.php
> +use Joomla\Plugin\Content\Contact\Extension\Contact;
```suggestion
use Joomla\Plugin\Privacy\Contact\Extension\Contact;
```

2023-03-26 10:57 UTC, heelc29 commented on plugins/privacy/content/services/provider.php
> +use Joomla\Plugin\Content\Contact\Extension\Contact;
```suggestion
use Joomla\Plugin\Privacy\Content\Extension\Content;
```

2023-03-26 10:57 UTC, heelc29 commented on plugins/privacy/content/services/provider.php
> +                $plugin     = new Contact(
```suggestion
                $plugin     = new Content(
```

2023-03-26 10:57 UTC, heelc29 commented on plugins/privacy/message/services/provider.php
> +use Joomla\Plugin\Privacy\Content\Extension\Message;
```suggestion
use Joomla\Plugin\Privacy\Message\Extension\Message;
```

2023-03-26 10:57 UTC, heelc29 commented on plugins/privacy/message/src/Extension/Message.php
> +namespace Joomla\Plugin\Privacy\Content\Extension;
```suggestion
namespace Joomla\Plugin\Privacy\Message\Extension;
```

2023-03-26 11:01 UTC, heelc29 commented on administrator/components/com_privacy/src/Plugin/PrivacyPlugin.php
> +     * @deprecated  __DEPLOY_VERSION__ will be removed in 6.0 use $this->getDatabase() instead
documentation changes for manual.joomla.org needed?

2023-03-26 11:47 UTC, heelc29 commented
I have tested this item :red_circle: unsuccessfully on 8110a9d2856a04a697b0bf44ea5742d58b4e14db<br /><br />During export data `Class "Joomla\Plugin\Privacy\User\Extension\UserPlugin" not found`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40174">issues.joomla.org/tracker/joomla-cms/40174</a>.</sub>

2023-03-26 11:57 UTC, heelc29 commented on plugins/privacy/user/src/Extension/User.php
>  use Joomla\CMS\User\User;
Is it possible to use `Joomla\CMS\User\User` with an alias, so the class of the plugin can be `User` (`Joomla\Plugin\Privacy\User\Extension\User`)?

2023-03-26 13:54 UTC, laoneo commented on plugins/privacy/user/src/Extension/User.php
>  use Joomla\CMS\User\User;
It was easier to do it that way 😁

2023-03-26 14:17 UTC, heelc29 commented on plugins/privacy/user/src/Extension/User.php
>  use Joomla\CMS\User\User;
But then the file must be renamed ... `User.php` to `UserPlugin.php`

2023-03-26 15:38 UTC, laoneo commented on plugins/privacy/user/src/Extension/User.php
>  use Joomla\CMS\User\User;
Yes sure, should not do pr's when I'm on traveling :-)

2023-03-26 15:38 UTC, laoneo commented on plugins/privacy/user/src/Extension/User.php
>  use Joomla\CMS\User\User;
renamed

2023-03-26 16:25 UTC, heelc29 commented
I have tested this item :white_check_mark: successfully on 30f40286832433a94bc35d5720faf9e98320040c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40174">issues.joomla.org/tracker/joomla-cms/40174</a>.</sub>

2023-03-28 15:20 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on 30f40286832433a94bc35d5720faf9e98320040c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40174">issues.joomla.org/tracker/joomla-cms/40174</a>.</sub>

2023-03-28 15:21 UTC, joomdonation commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40174">issues.joomla.org/tracker/joomla-cms/40174</a>.</sub>

2023-03-30 06:00 UTC, laoneo commented on administrator/components/com_privacy/src/Plugin/PrivacyPlugin.php
> +     * @deprecated  __DEPLOY_VERSION__ will be removed in 6.0 use $this->getDatabase() instead
True, check https://github.com/joomla/Manual/pull/94.

2023-03-30 08:30 UTC, merged