Convert user plugins to service provider
joomla/joomla-cms pull request #40180
Opened 2023-03-23 17:20 UTC by laoneo

### Summary of Changes
Converts the user plugins to service providers.

### Testing Instructions
- Enable all user plugins
- Create a contact
- Enable registration
- Create a new user on the front end with some contact fields

### Actual result BEFORE applying this Pull Request
User is created with some extra fields like address.

### Expected result AFTER applying this Pull Request
User is created with some extra fields like address.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-03-25 13:15 UTC, heelc29 requested changes

2023-03-25 13:15 UTC, heelc29 commented on plugins/user/contactcreator/services/provider.php
> +     * @since   _DEPLOY_VERSION__
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-03-25 13:15 UTC, heelc29 commented on plugins/user/joomla/services/provider.php
> +     * @since   _DEPLOY_VERSION__
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-03-25 13:15 UTC, heelc29 commented on plugins/user/profile/services/provider.php
> +     * @since   _DEPLOY_VERSION__
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-03-25 13:15 UTC, heelc29 commented on plugins/user/terms/services/provider.php
> +     * @since   _DEPLOY_VERSION__
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-03-25 13:15 UTC, heelc29 commented on plugins/user/token/services/provider.php
> +     * @since   _DEPLOY_VERSION__
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-03-25 13:15 UTC, heelc29 commented on plugins/user/joomla/src/Extension/Joomla.php
> +            $this->getDatabase()->setQuery(
```suggestion
            $db->setQuery(
```
Why do you not use here `$db`?

2023-03-25 13:15 UTC, heelc29 commented on plugins/user/contactcreator/src/Extension/ContactCreator.php
>      protected function getContactTable()
Should the functions (getContactTable and generateAliasAndName) `private`?

2023-03-25 13:15 UTC, heelc29 commented on plugins/user/joomla/src/Extension/Joomla.php
>          // If _getUser returned an error, then pass it back.
```suggestion
        // If getUser returned an error, then pass it back.
```

2023-03-25 15:17 UTC, heelc29 commented
I have tested this item :red_circle: unsuccessfully on 75e4c3d4e4d3dcc9f4cb92362813d9214ff9836e<br /><br />Mail to new user is not translated
![image](https://user-images.githubusercontent.com/66922325/227725957-a8f22a81-ff61-4036-b1a8-210add9fc9a0.png)
when frontend language of new user is not equal to administrators language
![image](https://user-images.githubusercontent.com/66922325/227725976-0fbf5d27-67ce-485f-86f0-b0f38bbc21da.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40180">issues.joomla.org/tracker/joomla-cms/40180</a>.</sub>

2023-03-25 16:15 UTC, heelc29 commented on plugins/user/profile/src/Extension/Profile.php
> +            //$form->removeGroup('profile');
Why you disabled this here?

2023-03-25 19:47 UTC, laoneo commented on plugins/user/profile/src/Extension/Profile.php
> +            //$form->removeGroup('profile');
I accidentally commited it as I was debugging something. Thanks for the hint.

2023-03-25 19:48 UTC, laoneo commented
@heelc29 does this not happen on 4.3-dev?

2023-03-25 20:19 UTC, heelc29 commented
> @heelc29 does this not happen on 4.3-dev?

No, without this PR it's working.

2023-03-26 05:46 UTC, joomdonation commented
@laoneo See https://github.com/Digital-Peak/joomla-cms/pull/28 , it will fix the email issue.

2023-03-26 15:17 UTC, heelc29 commented on plugins/user/joomla/src/Extension/Joomla.php
>          /**
```suggestion
        /**
```
remove two (of three) blank lines

2023-03-26 15:32 UTC, heelc29 commented
I have tested this item :white_check_mark: successfully on 92bc582d546be26257020720dc18bc4e05065bf0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40180">issues.joomla.org/tracker/joomla-cms/40180</a>.</sub>

2023-03-26 16:04 UTC, heelc29 commented
I have tested this item :white_check_mark: successfully on 48241fae8b4eff6e7d760bfd6dcf8aaf5396291b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40180">issues.joomla.org/tracker/joomla-cms/40180</a>.</sub>

2023-03-28 14:59 UTC, joomdonation commented
I have tested this item :white_check_mark: successfully on fcfd5c84e944c1f118967379a191096cc59363d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40180">issues.joomla.org/tracker/joomla-cms/40180</a>.</sub>

2023-03-28 14:59 UTC, joomdonation commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40180">issues.joomla.org/tracker/joomla-cms/40180</a>.</sub>

2023-03-29 17:07 UTC, merged