[4.3][Guided Tours] Fixed missing field in Banners Tour
joomla/joomla-cms pull request #40258
Opened 2023-03-30 20:55 UTC by khu5h1

Pull Request for Issue #40210 .

### Summary of Changes
Fixed missing field in Banners Tour.

### Actual result BEFORE applying this Pull Request
When we go through the tutorial on how to create a banner, there are skipping fields, some of which are required.

### Expected result AFTER applying this Pull Request
Now, it does not skip the fields and targets the entire details.

![image](https://user-images.githubusercontent.com/60094678/228961973-5ea5d519-b342-4e15-a875-87c13e9bc26b.PNG)

2023-03-30 21:45 UTC, richard67 requested changes

2023-03-30 21:45 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-31.sql
> +WHERE `target` = '#jform_description,#jform_description_ifr' AND `id` = 63;
Shouldn't also the title and the description be changed here and not only the target? In the other SQL scripts you change the language strings used for the target and the description, but here you don't to it when updating a 4.3.0-beta4 or 4.30-rc1.

2023-03-30 21:45 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-31.sql
> +WHERE "target" = '#jform_description,#jform_description_ifr' AND "id" = 63;
Shouldn't also the title and the description be changed here and not only the target? In the other SQL scripts you change the language strings used for the target and the description, but here you don't to it when updating a 4.3.0-beta4 or 4.30-rc1.

In addition, please update a line feed to the end of the file.

2023-03-30 21:45 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-31.sql
> +WHERE `target` = '#jform_description,#jform_description_ifr' AND `id` = 63;
In addition, please update a line feed to the end of the file.

2023-03-30 21:52 UTC, khu5h1 commented on administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-31.sql
> +WHERE `target` = '#jform_description,#jform_description_ifr' AND `id` = 63;
@richard67 Yes, the title and description should also be changed. Will do the changes. Thanks!

2023-04-01 14:51 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-31.sql
> +WHERE `target` = '#jform_description,#jform_description_ifr' AND `id` = 63;
```suggestion
UPDATE `#__guidedtour_steps`
SET `title` = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_TITLE', `description` = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_DESCRIPTION', `target` = '.col-lg-9'
WHERE `id` = 63;
```

2023-04-01 14:53 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-31.sql
> +WHERE "target" = '#jform_description,#jform_description_ifr' AND "id" = 63;
```suggestion
UPDATE "#__guidedtour_steps"
SET "title" = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_TITLE', "description" = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_DESCRIPTION', "target" = '.col-lg-9'
WHERE "id" = 63;

```

2023-04-01 14:55 UTC, richard67 commented
@khu5h1 Please do it like I suggest, update the values with one common update statement and use only the ID in the WHERE clause:

```
UPDATE `#__guidedtour_steps`
SET `title` = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_TITLE', `description` = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_DESCRIPTION', `target` = '.col-lg-9'
WHERE `id` = 63;

```

2023-04-01 14:56 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-31.sql
> +WHERE `target` = '#jform_description,#jform_description_ifr' AND `id` = 63;
Please do it in the way I just suggested.

2023-04-01 14:56 UTC, khu5h1 commented
@richard67 sure, updating the changes.

2023-04-01 15:00 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-31.sql
> +WHERE `id` = 63;
```suggestion
UPDATE `#__guidedtour_steps`
SET `title` = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_TITLE', `description` = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_DESCRIPTION', `target` = '.col-lg-9'
WHERE `id` = 63;

```

2023-04-01 15:01 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-31.sql
> +WHERE "id" = 63;
```suggestion
UPDATE "#__guidedtour_steps"
SET "title" = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_TITLE', "description" = 'COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_DESCRIPTION', "target" = '.col-lg-9'
WHERE "id" = 63;

```

2023-04-01 15:01 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-31.sql
> +WHERE `id` = 63;
Add empty line to the end.

2023-04-01 15:01 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-31.sql
> +WHERE "id" = 63;
Add empty line to the end.

2023-04-01 15:03 UTC, richard67 approved these changes

2023-04-01 15:20 UTC, Kostelano commented
I have tested this item :white_check_mark: successfully on 1e366a789c07c12e8f903a9d82d62659a9ce5765<br /><br />It's all right now, thanks. A little generalized (large) field with details, but it's better than it was ;).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40258">issues.joomla.org/tracker/joomla-cms/40258</a>.</sub>

2023-04-01 16:01 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 1e366a789c07c12e8f903a9d82d62659a9ce5765<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40258">issues.joomla.org/tracker/joomla-cms/40258</a>.</sub>

2023-04-01 16:01 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40258">issues.joomla.org/tracker/joomla-cms/40258</a>.</sub>

2023-05-05 03:17 UTC, merged

2023-05-05 03:18 UTC, sdwjoomla commented
Thanks khu5h1