[4] GET request scheduled task plugin - Authorization 401
joomla/joomla-cms pull request #40508
Opened 2023-04-30 07:32 UTC by alikon

Pull Request for Issue # .

### Summary of Changes
fix header for Authorization

### Testing Instructions

- create a GET request  scheduled task plugin
- fill a request URL
- enable Authorization
- fill the key
- run the task

### Actual result BEFORE applying this Pull Request
401

### Expected result AFTER applying this Pull Request
200

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-04-30 07:42 UTC, richard67 commented
@alikon I think you have to adapt the expected result of the unit tests (file `tests/Unit/Plugin/Task/Requests/Extension/RequestsPluginTest.php` line 242) to your change, see https://ci.joomla.org/joomla/joomla-cms/65072/1/11 .

2023-04-30 08:06 UTC, richard67 requested changes

2023-04-30 08:06 UTC, richard67 commented on tests/Unit/Plugin/Task/Requests/Extension/RequestsPluginTest.php
> +        $this->assertEquals(['Authorization' => ' basic 123'], $transport->headers);
```suggestion
        $this->assertEquals(['Authorization' => 'basic 123'], $transport->headers);
```
Fix failing unit test.

2023-04-30 08:08 UTC, alikon commented on tests/Unit/Plugin/Task/Requests/Extension/RequestsPluginTest.php
> +        $this->assertEquals(['Authorization' => ' basic 123'], $transport->headers);
oops

2023-04-30 08:08 UTC, richard67 approved these changes

2023-04-30 08:25 UTC, richard67 commented
Unit tests are passing. Failing system tests in drone are not related to this PR. I will restart later to see if they succeed.

2023-04-30 08:34 UTC, richard67 commented
@alikon In the testing instructions you wrote:

> create a GET request scheduled task plugin

But I think it just needs to create a task, not write an own plugin, is that right?

2023-04-30 08:38 UTC, alikon commented
yes

2023-04-30 08:54 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 759f44395261a2a985fa183ad435e354eb4904a7<br /><br />I have used a hack for testing with Basic authentication, which is not available in the dropdown for the authentication type. So I have set in database in the task's params the "authType" to "Basic" and the "authKey" to the bease64 encoded combination of user name and password separated by a colon. This worked, i.e. without the PR applied I got a 401 and with the PR applied a 200.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40508">issues.joomla.org/tracker/joomla-cms/40508</a>.</sub>

2023-08-08 22:53 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 759f44395261a2a985fa183ad435e354eb4904a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40508">issues.joomla.org/tracker/joomla-cms/40508</a>.</sub>

2023-08-08 22:53 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40508">issues.joomla.org/tracker/joomla-cms/40508</a>.</sub>

2023-08-09 01:12 UTC, merged

2023-08-09 01:12 UTC, obuisard commented
Thank you Nicola @alikon for the PR!