[4] PHP 8.1 - FTP Extension
joomla/joomla-cms pull request #40501
Opened 2023-04-28 15:37 UTC by alikon

Pull Request for Issue  #40438.

### Summary of Changes

Existing code that relied on is_resource function now needs to account for the new FTP\Connection class objects in PHP 8.1.

### Testing Instructions
see #40438.

### Actual result BEFORE applying this Pull Request
fail

### Expected result AFTER applying this Pull Request
works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-04-28 20:47 UTC, Hackwar commented
Can't we just remove it?...

2023-04-28 20:55 UTC, brianteeman commented
As stated in the issue report it is being used.

2023-05-04 14:01 UTC, stell commented
FTP is still being used by most of europes real estate business.
When trying this fix under PHP 8.1 i get 
`0 ftp_login(): Argument #1 ($ftp) must be of type FTP\Connection, null given`
here: https://github.com/joomla/joomla-cms/blob/91219036dec6f639eacb4a1d3b9cc208b03105b9/libraries/src/Client/FtpClient.php#L364
Same setup as PHP 8.0 without the issue

2023-07-04 13:26 UTC, stell requested changes
Failed `$this->_conn` returns NULL.
changing 
`$this->_conn !== false`
to 
`($this->_conn != false)`
or simply
`if ($this->_conn)` and `return $this->_conn`
fixes the current issue.

2023-07-04 14:11 UTC, alikon commented
feel free to do a pr  yourself @stell  or send a pr to this branch https://github.com/alikon/joomla-cms/tree/patch-4

2023-07-04 15:15 UTC, alikon commented
closing in favour of #41111

2023-07-04 15:15 UTC, closed without merging