End of support plugin
joomla/joomla-cms pull request #40556
Opened 2023-05-07 13:41 UTC by mfleeson

Pull Request for Issue # .

### Summary of Changes
Rewriting the 3.10 End of Service Notification and placing it into Joomla 4 coding structure and style. 
Simplified the language definitions to not be hardcoded for 3 to 4
Currently using const EOS_DATE = '2023-10-25'; in file plugins/quickicon/eos/src/Extension/Eos.php The correct date should be 2025-10-25 but then the notification does not appear. 
Dimitris converted the jQuery code into working javascript for closing the notification and also calling the com_ajax so the hide me is stored in the plugin parameters.

### Testing Instructions
Build. 
Check plg_quickicon_eos is enabled. 
View Home Dashboard in the back end.

### Actual result BEFORE applying this Pull Request
No notification is displayed

### Expected result AFTER applying this Pull Request
A notification is displayed

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-05-07 15:09 UTC, dgrammatiko requested changes

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/language/en-GB/plg_quickicon_eos.ini
> +; Joomla! Project
This file needs to be moved at `administrator/language/en-GB`

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/language/en-GB/plg_quickicon_eos.sys.ini
> +; Joomla! Project
This file needs to be moved at `administrator/language/en-GB`

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/services/provider.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> + * @since  4.0.0
```suggestion
 * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since  4.0.0
```suggestion
     * @since  __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since  4.0.0
```suggestion
     * @since  __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since  4.0.0
```suggestion
     * @since  __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since  4.0.0
```suggestion
     * @since  __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:09 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since   4.0.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2023-05-07 15:22 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +<?xml version="1.0" encoding="utf-8"?>
uppercase
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
```

2023-05-07 15:25 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +    		<folder>language</folder>
Expired
```    		
<folder>language</folder>
```

2023-05-07 15:46 UTC, mfleeson commented
All requested changes have been made. Thanks.

2023-05-07 15:47 UTC, dgrammatiko commented on plugins/quickicon/eos/eos.php
>  <?php
This file is not needed anymore

2023-05-07 15:52 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +	</files>
These are still needed:
```
<languages>
		<language tag="en-GB">language/en-GB/plg_quickicon_eos.ini</language>
		<language tag="en-GB">language/en-GB/plg_quickicon_eos.sys.ini</language>
</languages>
```

2023-05-07 16:25 UTC, mfleeson commented on plugins/quickicon/eos/eos.xml
> +	</files>
Dimitris said to move those files to administrator/language/en-GB. So do I need them in the plugins/quickicon/eos folder?

2023-05-07 16:25 UTC, mfleeson commented on plugins/quickicon/eos/eos.php
>  <?php
Deleted it.

2023-05-07 17:15 UTC, mfleeson commented on plugins/quickicon/eos/eos.xml
> +	</files>
Added back into eos.xml

2023-05-07 17:17 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +	</files>
> So do I need them in the plugins/quickicon/eos folder?

Yes, in the .xml file.

You will find examples in this folder: https://github.com/mfleeson/joomla-cms/tree/End-of-Support-Plugin/plugins/quickicon

2023-05-07 17:23 UTC, heelc29 commented on plugins/quickicon/eos/eos.xml
> +				/>
```suggestion
				<field
					name="last_snoozed_id"
					type="hidden"
				/>
```

2023-05-07 17:23 UTC, heelc29 commented on plugins/quickicon/eos/services/provider.php
> + */
```suggestion
/**
 * @package     Joomla.Plugin
 * @subpackage  Quickicon.eos
 *
 * @copyright   (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
```
format
phpcs should not be necessary

2023-05-07 17:23 UTC, heelc29 commented on plugins/quickicon/eos/services/provider.php
> +        });
```suggestion
        $container->set(
            PluginInterface::class,
            function (Container $container) {
                $dispatcher = $container->get(DispatcherInterface::class);
                $plugin     = new Eos(
                    $dispatcher,
                    Factory::getApplication()->getDocument(),
                    (array) PluginHelper::getPlugin('quickicon', 'eos')
                );
                $plugin->setApplication(Factory::getApplication());
                $plugin->setDatabase($container->get(DatabaseInterface::class));

                return $plugin;
            }
        );
```
format like other plugins

2023-05-07 17:23 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> + */
```suggestion
/**
 * @package     Joomla.Plugin
 * @subpackage  Quickicon.eos
 *
 * @copyright   (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
```
format
file has namespace

2023-05-07 17:33 UTC, mfleeson commented on plugins/quickicon/eos/eos.xml
> +				/>
Thanks. In phpstorm it only shows as one tab so i checked in github and edited it back to 1 tab,

2023-05-07 17:34 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> + */
Removed @phpcs, and added back in blank line that was taken out when trying to debug a phpcs error!

2023-05-07 17:34 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>This version of Joomla has entered security only mode. Support ends %1$s. Start <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">plan
Joomla 4?

2023-05-07 17:34 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS="Quick Icon - Joomla End Of Support Notification"
```suggestion
PLG_QUICKICON_EOS="Quick Icon - Joomla! End Of Support Notification"
```
to be in sync with sys file

2023-05-07 17:37 UTC, mfleeson commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>This version of Joomla has entered security only mode. Support ends %1$s. Start <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">plan
I did say in Mattermost that the message text needed changing. Especially the documentation links.

2023-05-07 17:39 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> + * @since __DEPLOY_VERSION__
Do not use `__DEPLOY_VERSION__` everywhere here, but leave the original date if necessary.
Take a look at this file as an example: https://github.com/mfleeson/joomla-cms/blob/End-of-Support-Plugin/plugins/quickicon/phpversioncheck/src/Extension/PhpVersionCheck.php

2023-05-07 17:45 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    private array|bool $currentMessage = [];
```suggestion
    private $currentMessage = [];
```
not allowed in PHP7

2023-05-07 17:45 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    private function getMessageInfo(int $monthsUntilEOS, int $inverted): bool|array
```suggestion
    private function getMessageInfo(int $monthsUntilEOS, int $inverted)
```
not allowed in PHP7

2023-05-07 17:45 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                } catch (Exception) {
```suggestion
                } catch (Exception $e) {
```
not allowed in PHP7

2023-05-07 17:45 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        } catch (Exception) {
```suggestion
        } catch (Exception $e) {
```
not allowed in PHP7

2023-05-07 17:45 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        } catch (Exception) {
```suggestion
        } catch (Exception $e) {
```
not allowed in PHP7

2023-05-07 17:45 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        } catch (Exception) {
```suggestion
        } catch (Exception $e) {
```
not allowed in PHP7

2023-05-07 17:48 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> + * @since __DEPLOY_VERSION__
ok. so just at the header and then fixed to 4.4.0 as thats when it will release?

2023-05-07 17:50 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    private array|bool $currentMessage = [];
All my JED 4 coding has been in php 8 and 8.1. PHPStorm recommended these. I've removed them.

2023-05-07 17:51 UTC, richard67 commented
Complete SQL stuff for new installations and updates is missing, and the plugin is also missing in the extensions helper.

2023-05-07 17:56 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_INFO_01="<p>The latest version of Joomla has arrived! Find out all that it has to offer you. Check the landing page for <a href=\"%2$s\" target=\"_blank\" rel=\"noopener nor
```suggestion
PLG_QUICKICON_EOS_MESSAGE_INFO_01="<p>The latest version of Joomla has arrived! Find out all that it has to offer you. Check the landing page for <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">its features</a> and improvements.</p>"
```
![image](https://user-images.githubusercontent.com/66922325/236694269-d981748d-7abd-4a2b-87d8-fbfdaf7ac52f.png)

2023-05-07 17:56 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_INFO_02="<p>When is the time to migrate to the next version? Once the extensions your site needs are compatible. Learn <a href=\"%2$s\" target=\"_blank\" rel=\"noopener nore
```suggestion
PLG_QUICKICON_EOS_MESSAGE_INFO_02="<p>When is the time to migrate to the next version? Once the extensions your site needs are compatible. Learn <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">how to use the Pre-Update Checker</a>.</p>"
```

![image](https://user-images.githubusercontent.com/66922325/236694363-02b66838-06ef-4e9d-a4de-75ee0be8af15.png)

2023-05-07 17:57 UTC, mfleeson commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_INFO_01="<p>The latest version of Joomla has arrived! Find out all that it has to offer you. Check the landing page for <a href=\"%2$s\" target=\"_blank\" rel=\"noopener nor
I did wonder about that. It was lifted straight from 3.10

2023-05-07 18:00 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>This version of Joomla has entered security only mode. Support ends %1$s. Start <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">plan
Ok, because all other strings about Joomla 3.10 and 4 were replaced ...

2023-05-07 18:04 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_INFO_01="<p>The latest version of Joomla has arrived! Find out all that it has to offer you. Check the landing page for <a href=\"%2$s\" target=\"_blank\" rel=\"noopener nor
Maybe its new in Joomla 4 🤔
https://github.com/joomla/joomla-cms/blob/be4f48dd66da1dce0d2a1a9acb325cce1d1ebb06/build/media_source/templates/administrator/atum/scss/blocks/_global.scss#L178-L185

2023-05-07 18:04 UTC, mfleeson commented
Richard has informed me I need to include it in the extensions table and the ExtensionHelper so I'll take a look at that tomorrow and then rerequest the PR.

2023-05-07 18:05 UTC, heelc29 reviewed
since commit 0572c8b8f115a948e5084f7598c199f90567458a

2023-05-07 18:05 UTC, heelc29 commented on plugins/quickicon/eos/services/provider.php
> +                $plugin->setDatabase($container->get(DatabaseInterface::class));
```suggestion
```

2023-05-07 18:05 UTC, heelc29 commented on plugins/quickicon/eos/services/provider.php
> +use Joomla\Database\DatabaseInterface;
```suggestion
```

2023-05-07 18:10 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> +use Joomla\Database\DatabaseInterface;
That's already been removed.

2023-05-07 18:11 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> +use Joomla\Database\DatabaseInterface;
https://github.com/mfleeson/joomla-cms/commit/0572c8b8f115a948e5084f7598c199f90567458a

2023-05-07 18:19 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>This version of Joomla has entered security only mode. Support ends %1$s. Start <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">plan
```suggestion
PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>This version of Joomla has entered security only mode. Support ends %1$s. Start <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">planning to migrate</a> to the next version of Joomla today.</p>"
```
![image](https://user-images.githubusercontent.com/66922325/236695004-f3f09742-bdf9-4890-a975-6e0103e48071.png)

2023-05-07 18:19 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING="<p>Support ends on %1$s for this version of Joomla. <span class=\"icon-new-tab\"></span><a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\
```suggestion
PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING="<p>Support ends on %1$s for this version of Joomla. <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Migrate to the latest version of Joomla</a> as soon as possible.</p>"
```
![image](https://user-images.githubusercontent.com/66922325/236695062-4672849d-8e90-4886-a269-5e45ea501633.png)

2023-05-07 18:19 UTC, heelc29 commented on plugins/quickicon/eos/services/provider.php
> +use Joomla\Database\DatabaseInterface;
Only from extension file but not from provider, so no it's broken
![image](https://user-images.githubusercontent.com/66922325/236695213-0f3c1f3e-8730-4ebf-b502-d7a8e43e611a.png)

2023-05-07 18:19 UTC, heelc29 commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_ERROR_SUPPORT_ENDED="<p>Support has ended for your version of Joomla. <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Migrate to the next version</a> <span cl
```suggestion
PLG_QUICKICON_EOS_MESSAGE_ERROR_SUPPORT_ENDED="<p>Support has ended for your version of Joomla. <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Migrate to the next version</a> as soon as possible.</p>"
```
![image](https://user-images.githubusercontent.com/66922325/236695278-bb61c03d-e315-46f8-a759-18ba2298a9a9.png)

2023-05-07 18:19 UTC, heelc29 commented on plugins/quickicon/eos/services/provider.php
> +use Joomla\Database\DatabaseInterface;
But database is still used here:
https://github.com/joomla/joomla-cms/blob/369c3a383d43e4ff44ccfd2c4b2f772c25055302/plugins/quickicon/eos/src/Extension/Eos.php#L288

2023-05-07 18:20 UTC, heelc29 commented on plugins/quickicon/eos/services/provider.php
> +use Joomla\Database\DatabaseInterface;
Only form extension file but not from provider, so not it's broken
![image](https://user-images.githubusercontent.com/66922325/236695468-27973650-b862-4e48-a5d3-cdf734abd410.png)

but the database is used here
https://github.com/joomla/joomla-cms/blob/369c3a383d43e4ff44ccfd2c4b2f772c25055302/plugins/quickicon/eos/src/Extension/Eos.php#L288

2023-05-07 18:24 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    public function onGetIcons(string $context): array
Maybe check the context?
![image](https://user-images.githubusercontent.com/66922325/236695646-b96210f0-48fd-4431-9c5a-2009a7d71fca.png)

2023-05-07 18:26 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    private Document $document;
Document is available from application ... so is the extra variable (in constructor) necessary?
https://github.com/joomla/joomla-cms/blob/be4f48dd66da1dce0d2a1a9acb325cce1d1ebb06/libraries/src/Factory.php#L324C24-L326

2023-05-07 19:18 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> + * @since __DEPLOY_VERSION__
> ok. so just at the header and then fixed to 4.4.0 as thats when it will release?

No, I didn't mean it that way.

For example, if the constante / function / method has been used before in J3.10, the version remains unchanged.

See line 104 - 106:
```
* @since   3.10.0
*/
private function getMessageInfo($monthsUntilEOS, $inverted)
{
```
So not: `@since   4.4.0`

2023-05-07 19:26 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +// phpcs:enable PSR1.Files.SideEffects
Use:
```
// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;
// phpcs:enable PSR1.Files.SideEffects
```

2023-05-07 22:12 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    private Document $document;
Currently the code passes Document from provider.php on line 40. This is based on the existing plugins/quickicon/joomlaupdate/servers/provider.php Should this be different?

2023-05-07 22:13 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +// phpcs:enable PSR1.Files.SideEffects
Not sure why phpstorm added a blank line after defined, have added a \ to defined.

2023-05-07 22:15 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +// phpcs:enable PSR1.Files.SideEffects
though the example i was using joomlaupdate\services\provider.php does not have a \ before the defined

2023-05-07 22:15 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +// phpcs:enable PSR1.Files.SideEffects
and neither does phpversioncheck

2023-05-08 05:36 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +// phpcs:enable PSR1.Files.SideEffects
_I usually look at what is most common within Joomla to be consistent._ The results of PHPStorm sometimes deviate. When in doubt, delve into history. If necessary, ask a question about, in the hope a get an answer. Or finally enter it as a new issue. 

It is a continuous learning process for me. :sweat_smile:

2023-05-08 17:48 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> + * @since __DEPLOY_VERSION__
@mfleeson 

Sorry, I wasn't clear with my comment.
Anything **new** will be `__DEPLOY_VERSION__` and NOT `4.4.0`

2023-05-08 17:49 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.4.0-2023-05-08.sql
> +	(0, "plg_quickicon_eos", "plugin", "eos", "quickicon", 0, 1, 1, 0, 1, "", "", "", 7, 0);
```suggestion
	(0, 'plg_quickicon_eos', 'plugin', 'eos', 'quickicon', 0, 1, 1, 0, 1, '', '', '', 7, 0);
```
Only name quotes are double quotes in PostgreSQL, string quotes are single quotes like in MySQL.

2023-05-08 17:56 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.4.0-2023-05-08.sql
> +	(0, "plg_quickicon_eos", "plugin", "eos", "quickicon", 0, 1, 1, 0, 1, "", "", "", 7, 0);
P.S.: That's not just code style, it's a syntax error.

2023-05-08 18:01 UTC, mfleeson commented on administrator/components/com_admin/sql/updates/postgresql/4.4.0-2023-05-08.sql
> +	(0, "plg_quickicon_eos", "plugin", "eos", "quickicon", 0, 1, 1, 0, 1, "", "", "", 7, 0);
Thanks. Not worked with Postgres for about 25 years.

2023-05-08 20:05 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +	<version>4.0.0</version>
I think this should be `<version>3.10.0</version>` wich corresponds to the original eos.xml file.
But I doubt. Maybe someone else has advice?

2023-05-08 20:13 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +	<version>4.0.0</version>
PS. The eos.php file also has references to 3.10.0

2023-05-08 20:16 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +\defined('_JEXEC') || die;
Common is: _or_
```suggestion
\defined('_JEXEC') or die;
```

2023-05-08 21:51 UTC, mfleeson commented on plugins/quickicon/eos/eos.xml
> +	<version>4.0.0</version>
Although the base code is from 3.10 the whole codebase was restructured to use 4.x standards so technically this code is at least 4.x based. Some of the functions were left using the 3.10 logic but still were moved to 4.x.

2023-05-09 06:11 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +	<version>4.0.0</version>
> Although the base code is from 3.10 the whole codebase was restructured to use 4.x standards so technically this code is at least 4.x based. Some of the functions were left using the 3.10 logic but still were moved to 4.x.

I already understood this, hence my comment.
All the functions (functionality) were left using the 3.10.0, then refer to 3.10.0. As far as I understood.

Ping @laoneo

2023-05-09 09:14 UTC, richard67 commented on plugins/quickicon/eos/eos.xml
> +	<version>4.0.0</version>
The code was removed from the 4.0-dev branch once, so the plugin introduced here is something new, even if the code is based on the old one from 3.10-dev. The old one was named "plg_quickicon_eos310" and is uninstalled when updating to J4.x, see https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_admin/script.php#L491 . So all code here should get the `__DEPLOY_VERSION__` (or 4.4.0 in the XML), there should no "since" tag or so be left from 3.10.

2023-05-09 09:48 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +	<version>4.0.0</version>
@richard67 

Thank you for your clear and complete explanation. I totally agree with it. 👍

2023-05-09 10:08 UTC, dgrammatiko commented on plugins/quickicon/eos/eos.xml
> +	<version>4.0.0</version>
Funny part I had raised suggestions for all of them (ie: https://github.com/joomla/joomla-cms/pull/40556#discussion_r1186869206) but probably a forced pushed reverted all of them

2023-05-09 10:12 UTC, sandewt commented on plugins/quickicon/eos/eos.xml
> +	<version>4.0.0</version>
> Funny part I had raised suggestions for all of them (ie: https://github.com/joomla/joomla-cms/pull/40556#discussion_r1186869206) but probably a forced pushed reverted all of them

MEA culpa

2023-05-09 16:05 UTC, closed without merging

2023-05-09 16:06 UTC, richard67 commented
Why closed PR and deleted branch?

2023-05-09 16:27 UTC, mfleeson commented
I'm sorry I didn't realise it had done that. I thought I was working on my local fork. I was trying to get all of the files back into one place. I didn't delete the branch, just renamed it as I realised it was based on 4.3 and not 4.4. So I created a new fork based on 4.4 and have used a comparison to put all of the code into the new fork. I was going to make sure it adheres to all of these comments and then push that. Git is still very much a black art to me.

2023-05-09 16:30 UTC, richard67 commented
Then I think you have to make a new PR with the renamed branch. If you do that, please refer to this PR here in the description of the new PR so people can find previous discussions.

2023-05-09 16:46 UTC, mfleeson commented
The new PR is https://github.com/joomla/joomla-cms/pull/40563

2023-05-09 16:55 UTC, sandewt commented
@MacJoom 

> Git is still very much a black art to me.

Maybe _Github Destop_ is a good alternative. I read there "Focus on what matters instead of fighting with Git." 

I recently started using this program (on Windows) for my own github repositories to gain experience with it. It works quite simple.

2023-05-09 17:11 UTC, mfleeson commented
I was using github desktop, that's the scary thing but it wasnt updating with other peoples changes so it totally overwrote Dimitri's javascript code. I think I've got it all back in hand now and am going to try and create a new PR for 4.4

The new PR is https://github.com/joomla/joomla-cms/pull/40565

2023-05-09 17:15 UTC, sandewt commented
> I was using github desktop, that's the scary thing but it wasnt updating with other peoples changes so it totally overwrote Dimitri's javascript code.

Thanks for the info. Good to know.