[5] add2scheduler-privacyconsents
joomla/joomla-cms pull request #40553
Opened 2023-05-07 07:31 UTC by alikon

### Summary of Changes

- add the plg_system_privacyconsents feature  "Delete the expired privacy consents" to a proper scheduled task plugin
- add the plg_system_privacyconsents feature "Remind for privacy consents near to expire" to a proper scheduled task plugin

### Testing Instructions

- apply the pr
- System - Extensions: Discover
- publish the new plugin
- disable the expiration feature of plg_system_privacyconsents
- System - Scheduled Tasks and create a new task
- Create a task Remind and/or Expiration  set paramenters and run it

### Actual result BEFORE applying this Pull Request

the feature are available with system plugin

### Expected result AFTER applying this Pull Request

the 2 task are available as a scheduled tasks

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-05-07 08:54 UTC, sandewt commented on plugins/task/privacyconsent/privacyconsent.xml
> +	<version>4.4</version>
```suggestion
	<version>5.0</version>
```

2023-05-07 11:01 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +
```suggestion

```
PHPCS no 2 consecutive empty lines.

2023-05-07 11:02 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +     * @var boolean
```suggestion
     * @var boolean

```
PHPCS empty line needed.

2023-05-07 11:06 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +// phpcs:disable PSR1.Files.SideEffects
```suggestion

// phpcs:disable PSR1.Files.SideEffects
```
Seems something went wrong with my previous suggestion. Only 1 of the 2 empty lined needed to be removed. Now adding one back.

2023-05-07 11:07 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +        $query  = $db->getQuery(true);
```suggestion
        $now    = Factory::getDate()->toSql();
        $period = '-' . ($expire - $remind);
        $db     = $this->getDatabase();
        $query  = $db->getQuery(true);
```

2023-05-07 11:23 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +        }
```suggestion
        // Do not process further if no expired consents found
        if (empty($users)) {
            return Status::OK;
        }
```
PHPCS

2023-05-07 11:25 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +     *
```suggestion
     *
```
PHPCS

2023-05-08 19:41 UTC, sandewt commented on plugins/task/privacyconsent/privacyconsent.xml
> +	<version>5.0</version>
I think this is better:
```suggestion
	<version>5.0.0</version>
```

2023-06-10 07:40 UTC, HLeithner requested changes, later dismissed
Thanks for this PR, can you please remove the functionallity from the plg_system_privacyconsents plugin please.

2023-06-10 07:40 UTC, HLeithner commented on plugins/task/privacyconsent/forms/invalidateForm.xml
> +					name="consentexpiration"
can we get a better name here which include that we talk about days. Took me some time to find out that we talk about days here. It's only mentioned in the description.

2023-06-10 07:40 UTC, HLeithner commented on plugins/task/privacyconsent/forms/remindForm.xml
> +					name="consentexpiration"
Same as invalidateForm.xml

2023-06-10 07:46 UTC, alikon commented on plugins/task/privacyconsent/forms/invalidateForm.xml
> +					name="consentexpiration"
i'm open to any suggestion for a better name

2023-06-10 07:46 UTC, alikon commented on plugins/task/privacyconsent/forms/remindForm.xml
> +					name="consentexpiration"
any suggestion for a better name  are welcome

2023-06-10 10:49 UTC, sandewt commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +use PHPMailer\PHPMailer\Exception as phpmailerException;
Missing:
`use RuntimeException;`

2023-06-10 10:50 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +use PHPMailer\PHPMailer\Exception as phpmailerException;
@sandewt That's not necessary as the code uses `\RuntimeException` from the global namespace.

2023-06-10 11:00 UTC, sandewt commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +use PHPMailer\PHPMailer\Exception as phpmailerException;
Thanks, learned something again. 👍 
The Joomla code is very inconsistent in that regard and put me on the wrong track.

2023-06-10 11:03 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +use PHPMailer\PHPMailer\Exception as phpmailerException;
Well in namespaced files we use the global namespace, i.e. prepend build_in PHP methods and exception types with a backslash, e.g. `\is_file`, `\version_compare`, ..., `\RuntimeException`, but in not namespaced files like e.g. layouts we can't do that.

2023-06-10 11:21 UTC, sandewt commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +use PHPMailer\PHPMailer\Exception as phpmailerException;
Thanks for the additional info.

2023-06-10 12:17 UTC, HLeithner commented on plugins/task/privacyconsent/forms/invalidateForm.xml
> +					name="consentexpiration"
consentexpirationdays

2023-06-10 12:17 UTC, HLeithner commented on plugins/task/privacyconsent/forms/remindForm.xml
> +					name="consentexpiration"
consentexpirationdays

2023-06-11 12:41 UTC, richard67 commented
@alikon What is missing is the SQL changes in base.sql to add the new task plugin to the extensions table (if possible with reasonable default params) and an update SQL script for doing the same. Use the newest present update SQL which does an insert into the extensions table as example, and give the files the right name, e.g. "5.0.0-2023-06-12.sql". The new plugin needs also to be added to the extensions helper.

2023-06-11 15:59 UTC, sandewt commented on plugins/task/privacyconsent/services/provider.php
> + * @subpackage  Task.PrivacyConsent
Most common to use lowercase letters here.
```suggestion
 * @subpackage  Task.privacyconsent
```

2023-06-11 16:01 UTC, sandewt commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> + * @subpackage  Task.PrivacyConsent
Most common to use lowercase letters here.
```suggestion
 * @subpackage  Task.privacyconsent
```

2023-06-13 08:05 UTC, richard67 commented
@alikon Why do you remove the privacyconsent plugin with your latest commit? As far as I can see it should not be removed completely because your PR here only replaces a part of its functionality. With your other PR for the logrotation it is different: There you can remove the old plugin because your new PR replaces that completely. But here that's not the case, or am I missing something?

2023-06-13 08:22 UTC, alikon commented
this replaces all the functionalities of privacyconsent

2023-06-13 08:26 UTC, HLeithner commented
> this replaces all the functionalities of privacyconsent

no it doesn't, please have a look at the plugin you deleted and all it events it has.

2023-06-13 08:32 UTC, alikon commented
you both  are right sorry

2023-06-13 10:50 UTC, alikon commented on plugins/task/privacyconsent/forms/invalidateForm.xml
> +					name="consentexpiration"
renamed

2023-06-13 10:50 UTC, alikon commented on plugins/task/privacyconsent/forms/remindForm.xml
> +					name="consentexpiration"
renamed

2023-06-13 13:42 UTC, richard67 commented
@alikon Does it need to remove some obsolete configuration parameters from the "plugins/system/privacyconsent/privacyconsent.xml" file?

2023-06-13 14:00 UTC, alikon commented
yes done

2023-06-13 14:05 UTC, richard67 commented
@alikon We have 2 fields with name="consentexpirationdays" and label="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_LABEL" and description="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_DESC", one in file "plugins/task/privacyconsent/forms/invalidateForm.xml" and the other one in file "plugins/task/privacyconsent/forms/remindForm.xml". Is that right?

2023-06-13 14:06 UTC, richard67 commented
@alikon What's also not clear to me is what replaces the old "cachetimeout" parameter.

2023-06-13 14:20 UTC, alikon commented
> @alikon What's also not clear to me is what replaces the old "cachetimeout" parameter.

It has been replaced  by Execution Rule / interval /cron expression

2023-06-13 14:32 UTC, alikon commented
> @alikon We have 2 fields with name="consentexpirationdays" and label="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_LABEL" and description="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_DESC", one in file "plugins/task/privacyconsent/forms/invalidateForm.xml" and the other one in file "plugins/task/privacyconsent/forms/remindForm.xml". Is that right?


i think so, cause 1 is for delete expired consents and the other 1 is for remind about near to expire consent

2023-06-13 14:38 UTC, richard67 commented
> > @alikon We have 2 fields with name="consentexpirationdays" and label="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_LABEL" and description="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_DESC", one in file "plugins/task/privacyconsent/forms/invalidateForm.xml" and the other one in file "plugins/task/privacyconsent/forms/remindForm.xml". Is that right?
> 
> i think so, cause 1 is for delete expired consents and the other 1 is for remind about near to expire consent

@alikon How can these 2 parameters with the same name then be distinguished? Have you tried to save the configuration of your new plugin with 2 different values for these parameters and then checked the value of the `params` column of the record of your new plugin in the `#__extensions` table in database? If so, and everything works, could we provide the initial value for that column in the base.sql for new installations as well as in the update SQL when we add the new plugin on update?

2023-06-13 14:55 UTC, alikon commented
> How can these 2 parameters with the same name then be distinguished?

@richard67  consider that these are 2 separate task event  let me share a screen:

for expiration
![image](https://github.com/joomla/joomla-cms/assets/181681/ba99c0bf-781a-4733-bd0c-d5b44f5097aa)

and for remind

![image](https://github.com/joomla/joomla-cms/assets/181681/21b24002-1c7e-4c6c-b806-4a57324e40fb)

2023-06-13 15:04 UTC, richard67 commented
@alikon I see. You have different tasks. But it seems you are not adding these tasks when making a new installation or an update, i.e. no insert into the `#__scheduler_tasks` table. So how does it work? Do these tasks have to be created manually?

2023-06-13 15:10 UTC, alikon commented
this must be discussed imho, so i've left out for the moment

2023-06-13 15:14 UTC, richard67 commented
> this must be discussed imho, so i've left out for the moment

@alikon What has to be discussed is the migration of existing settings from the old plugin to the new plugin, which might include updating the previously created new tasks. But the tasks should be created already in the extensions.sql for new installations when the corresponding functionality before this PR here was enabled for new installations, and it should also be done in the update SQL when privacy consents were enabled on update when we had introduced them once in past.

2023-06-13 15:18 UTC, richard67 commented
@alikon And still I don't understand why we have to set the "Expiration" parameter in both tasks. What happens if I set them differently? I.e. the expiration will happen after 180 days and the reminder will be based on an expiration after 360 days? That would not really make sense, would it?

2023-06-13 15:19 UTC, sandewt commented on plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
>  use RuntimeException;
use statement expires, no longer needed
```
use RuntimeException; 
```

2023-06-13 17:12 UTC, alikon commented
@richard67 

>  But the tasks should be created already in the extensions.sql for new installations


i'm would like to not set anything  for plugins (scheduled task) on new installations, but that's my personal opinion, that should be  an informed action by the admin

> why we have to set the "Expiration" parameter in both tasks

good valid point

i'll convert to draft for now ... it needs more care for sure

2023-06-25 06:22 UTC, alikon commented
ready for review

2023-06-25 08:03 UTC, richard67 commented on libraries/src/Extension/ExtensionHelper.php
> +        ['plugin', 'privacyconsent', 'task', 0],
```suggestion
        ['plugin', 'checkfiles', 'task', 0],
        ['plugin', 'privacyconsent', 'task', 0],
        ['plugin', 'requests', 'task', 0],
        ['plugin', 'sitestatus', 'task', 0],
```
Alpha-ordering

2023-06-25 08:16 UTC, richard67 commented
> ready for review

@alikon I think it needs a migration of parameters on update when people have the old privacy consent system plugin enabled.

In opposite to other PRs for migrating stuff to tasks we do not have to delete the old plugin here, so the migration of parameters cannot be done with the "uninstallExtensions" method, it has to be called in the "postflight" method like we already do it for the migration of the TinyMCE editor plugin's options.

I.e. create a new function, e.g. "migratePrivacyconsentConfiguration", and call that in "postflight" in the same way as we call the "migrateTinymceConfiguration" function, i.e. add following code after here https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L948 :

```
        if (!$this->migratePrivacyconsentConfiguration()) {
            return false;
        }
```

The migration should check the "enabled" status of the old plugin and only migrate something if that status is 1 (enabled).

2023-06-25 08:26 UTC, alikon commented
missed that one https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L944 

👍

2023-06-25 08:32 UTC, richard67 commented
> missed that one https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L944

@alikon It will also need to change the version number here https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L940 to 5.0.1, similar as we did here https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L216-L219 , and adapt the comment to that here https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L944 . Otherwise the migration would not run when updating from a 5.0.0-alpha1 or alpha2.

2023-06-25 09:06 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +     *
```suggestion
     *
```
Fix PHPCS.

2023-06-25 09:08 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +     *
```suggestion
     *
```
Fix PHPCS.

2023-06-25 09:09 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +        if (($this->invalidateExpiredConsents($expire) === Status::OK) &&
```suggestion
        if (($this->invalidateExpiredConsents($expire) === Status::OK) &&
```
Fix PHPCS.

2023-06-25 09:10 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +
```suggestion
```
Fix PHPCS.

2023-06-25 09:10 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +     *
```suggestion
     *
```
Fix PHPCS.

2023-06-25 09:11 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +        $query  = $db->getQuery(true);
```suggestion
        $now      = Factory::getDate()->toSql();
        $period   = '-' . ($expire - $remind);
        $db       = $this->getDatabase();
        $query    = $db->getQuery(true);
```
Fix PHPCS.

2023-06-25 09:15 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +        }
```suggestion
        // Do not process further if no expired consents found
        if (empty($users)) {
            return Status::OK;
        }
```
Fix PHPCS (last one, I think).

2023-06-25 11:01 UTC, richard67 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +            ($this->remindExpiringConsents($expire, $remind) === Status::OK)) {
```suggestion
        if (
            $this->invalidateExpiredConsents($expire) === Status::OK
            && $this->remindExpiringConsents($expire, $remind) === Status::OK
        ) {
```
Fix PHPCS, hopefully the last one, and remove unnecessary brackets.

2023-06-26 17:32 UTC, alikon commented
> ...Otherwise the migration would not run when updating from a 5.0.0-alpha1 or alpha2.
Not sure if we should do it with this PR here or if I should do it with a separate PR.

 as long as we don't have certainty when and if it will be merged....a later pr maybe

2023-07-02 12:13 UTC, richard67 commented
@alikon I've allowed myself to update your branch to latest 5.0-dev and fix the conflict. Please pull the changes before you continue to work on your local clone.

2023-07-02 13:10 UTC, richard67 commented
> Thanks for this PR, can you please remove the functionallity from the plg_system_privacyconsents plugin please.

@HLeithner As far as I can see, this has been implemented now. Could you approve the change or dismiss your review so that GitHub doesn't show it anymore as unresolved conversation? Thanks in advance.

2023-07-24 15:01 UTC, richard67 commented
@alikon Could you rename the update SQL scripts to something newer than "5.0.0-2023-07-12.sql" (= newest update SQL right now in the 5.0-dev branch), e.g. to "5.0.0-2023-07-25.sql"? Thanks in advance.

2023-08-07 17:00 UTC, heelc29 commented on administrator/components/com_admin/script.php
> +        }
move to `uninstallExtensions`

2023-08-07 17:05 UTC, richard67 commented on administrator/components/com_admin/script.php
> +        }
@heelc29 Why? The old plugin is not removed.

2023-08-07 17:06 UTC, heelc29 commented on administrator/components/com_admin/script.php
> +        }
Yes I saw later 😅

2023-08-07 19:05 UTC, alikon commented on administrator/components/com_admin/script.php
> +        }
np

2023-08-25 09:52 UTC, richard67 commented
@alikon It needs again to rename the update SQL scripts, this time to something newer than "5.0.0-2023-08-21.sql". I suggest to use "5.0.0-2023-08-23.sql" for this PR here.

2023-08-26 05:44 UTC, alikon commented
done

2023-08-26 15:44 UTC, heelc29 commented on administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-08-23.sql
> +INSERT INTO `#__mail_templates` (`template_id`, `extension`, `language`, `subject`, `body`, `htmlbody`, `attachments`, `params`) VALUES
Delete old mail template `plg_system_privacyconsent.request.reminder`

2023-08-26 15:44 UTC, heelc29 commented on administrator/components/com_admin/sql/updates/postgresql/5.0.0-2023-08-23.sql
> +('plg_task_privacyconsent.request.reminder', '', 'PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_SUBJECT', 'PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_BODY', '', '', '{"tags":["sitename","url","tokenurl","formurl","
Delete old mail template `plg_system_privacyconsent.request.reminder`

2023-08-26 15:44 UTC, heelc29 commented
Task for new installations is missing

2023-08-26 15:46 UTC, heelc29 commented on administrator/language/en-GB/plg_task_privacyconsent.ini
mark the moved language strings deprecated in `plg_system_privacyconsent.ini`

2023-08-26 15:48 UTC, richard67 commented
> Task for new installations is missing

@heelc29 I think that's not needed because on a new installation of J5 without this PR, the privacy consent is disabled as far as I know, and we should keep the functionality and not create a task on a new install. When updating it depends on the previous enabled status of the privacyconsent plugin if we create a new task or not. Other PRs where something is replaced which would be enabled on a new install will create also a task for new installations. But that's not the case here.

2023-08-26 15:51 UTC, richard67 commented
@alikon I've solved the merge conflict caused by the recently merged globalcheckin task plugin, so before you continue to work locally on your branch you have to pull the changes from remote.

2023-08-26 15:51 UTC, heelc29 commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +                Text::sprintf('PLG_TASK_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_MESSAGE', Factory::getUser($user->user_id)->username)
use `UserFactory`

2023-08-28 07:02 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/5.0.0-2023-08-23.sql
> +('plg_task_privacyconsent.request.reminder', '', 'PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_SUBJECT', 'PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_BODY', '', '', '{"tags":["sitename","url","tokenurl","formurl","
done

2023-08-28 07:02 UTC, alikon commented on administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-08-23.sql
> +INSERT INTO `#__mail_templates` (`template_id`, `extension`, `language`, `subject`, `body`, `htmlbody`, `attachments`, `params`) VALUES
done

2023-08-28 07:03 UTC, alikon commented on plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
> +                Text::sprintf('PLG_TASK_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_MESSAGE', Factory::getUser($user->user_id)->username)
done

2023-09-01 13:22 UTC, richard67 commented on plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
>  use RuntimeException;
Is meanwhile solved as far as I can see.

2023-09-01 13:30 UTC, richard67 commented on administrator/language/en-GB/plg_task_privacyconsent.ini
Done with commit https://github.com/joomla/joomla-cms/pull/40553/commits/87940ee73c380b3b11a0b57988ef25b42cc020dc .

2023-09-01 14:22 UTC, richard67 commented on administrator/components/com_admin/script.php
> +        /** @var SchedulerComponent $component */
```suggestion
        $params = json_decode($row->params, true);

        // If consent expiration was disbled there is nothing to migrate
        if (!$params->get('enabled', 0)) {
            return;
        }

        /** @var SchedulerComponent $component */
```

2023-09-01 14:29 UTC, richard67 commented on administrator/components/com_admin/script.php
> +        $params = json_decode($row->params, true);
```suggestion
        $params = new Registry($row->params);
```

2023-09-01 14:34 UTC, richard67 commented on administrator/components/com_admin/script.php
> +            return;
```suggestion
            return true;
```

2023-09-01 14:55 UTC, richard67 commented on administrator/components/com_admin/script.php
> +                'interval-hours' => $params->get('cachetimeout', 6),
```suggestion
                'interval-hours' => $params->get('cachetimeout', 6),
```
@alikon Hmm, the old cachetimeout of the system plugin is given in days, not in hours. Are you sure this is right, using the value wihout modification for the interval-hours of the task?

2023-09-01 14:59 UTC, richard67 commented on administrator/components/com_admin/script.php
> +                'interval-hours' => $params->get('cachetimeout', 6),
And the default value was 30 in the system plugin.

2023-09-01 15:06 UTC, richard67 commented on administrator/components/com_admin/script.php
> +                'interval-hours' => $params->get('cachetimeout', 6),
An easy fix could be to use 24 hour, hard-coded, like in your other PR #41064 .

2023-09-01 15:09 UTC, richard67 commented on administrator/components/com_admin/script.php
> +                'interval-hours' => $params->get('cachetimeout', 6),
I will propose a fix.

2023-09-01 15:11 UTC, richard67 commented on administrator/components/com_admin/script.php
> +            ],
```suggestion
            'execution_rules' => [
                'rule-type'     => 'interval-days',
                'interval-days' =>  $params->get('cachetimeout', 30),
                'exec-time'     => gmdate("H:i", $params->get('lastrun', 0)),
                'exec-day'      => gmdate('d'),
            ],
```
Cachetimeout was given in days in the system plugin, and default was 30.

2023-09-01 15:26 UTC, richard67 commented
@alikon I've allowed myself to update the branch and apply some review changes. Now I think it needs better testing instructions. I suggest something as follows for this PR here, and will later make suggestions also for the other 4 PRs. Feel free to just copy it and paste into the descriptions of the PRs, or modify them as you want.

### Testing Instructions

#### New installation

Make a new installation with this PR applied.

Check if there is an enabled task scheduler plugin "Task - Privacy Consents".

Check if there is any scheduled task using that plugin.

#### Update

On a Joomla 4.4-dev version or 4.4.0 alpha 4, note the endabled status and the configuration parameters in the "Expiration" fieldset of the of the "System - Privacy Consent" plugin.

Now either disable that plugin or enable it and optionally change some of the configuration parameters in the "Expiration" fieldset to a value different to the default.

Update to the patched package or custom update URL created by Drone for this PR.

Check if the "Expiration" fieldset of the "System - Privacy Consent" plugin has been removed.

Check if there is a task scheduler plugin "Task - Privacy Consents".

Check enabled status and configuration parameters of that plugin.

Check if there is a scheduled task "PrivacyConsent" using that plugin. If so, check the configuration parameters, too.

Repeat the previous steps with different endabled status of the "System - Privacy Consent" plugin and - if enabled - different configuration parameters in the "Expiration" fieldset of that plugin.

### Actual result BEFORE applying this Pull Request

Reminders on and deletion of expired consents are done with the "System - Privacy Consent" plugin.

### Expected result AFTER applying this Pull Request

#### New installation

The "Task - Privacy Consents" plugin is enabled.

There is no scheduled task using that plugin because on a new installation the "System - Privacy Consent" is disabled.

#### Update

The "Expiration" fieldset has been removed from the configuration parameters of the "System - Privacy Consent" plugin by the update.

A new task scheduler plugin "Task - Privacy Consents" has been created and is enabled.

If the "System - Privacy Consent" plugin was enabled and field "Enabled" was set to "Yes" in the "Expiration" fieldset of that plugin before the update, a new scheduled task "PrivacyConsent" has been created and is enabled.

The task executes every n days, with n being the "Periodic check (days)" value which was set in the "Expiration" fieldset of the system plugin before the update, default 30.

The configuration parameters "Expiration" and "Remind" of that task are set to the same values as the same parameters in the in the "Expiration" fieldset of the old system plugin.

If the old "System - Privacy Consent" plugin was disabled or field "Enabled" was set to "No" in the "Expiration" fieldset of that plugin before the update, there is no task for that plugin.

2023-09-01 17:25 UTC, richard67 commented on administrator/components/com_admin/script.php
> +        if (!$row->enabled) {
```suggestion
        // If not existing or disbled there is nothing to migrate
        if (!$row || !$row->enabled) {
```

2023-09-01 20:24 UTC, sandewt commented
https://github.com/joomla/joomla-cms/blob/50bf3d68dd8872baba2e734084645a368be52a0f/administrator/components/com_admin/script.php#L279

Remove backslash:
```
} catch (Exception $e) {
```

2023-09-02 09:23 UTC, richard67 commented on administrator/components/com_admin/script.php
> +                'exec-time'     => gmdate("H:i", $params->get('lastrun', 0)),
```suggestion
                'exec-time'     => gmdate('H:i', $params->get('lastrun', 0)),
```

2023-09-02 10:35 UTC, richard67 commented
> \Exception

@sandewt That should be fixed with a separate PR because this code was not added by the PR here. It was my mistake btw. because it was me who once had added that function. Do you want to make a PR for a fix? Otherwise I will do later. But it has a low priority for me as it's just a code style thing more or less. Both works.

2023-09-02 10:40 UTC, richard67 commented on plugins/task/privacyconsent/services/provider.php
> +                    (array) PluginHelper::getPlugin('task', 'privacyconsent')
```suggestion
                $plugin = new PrivacyConsent(
                    $container->get(DispatcherInterface::class),
                    (array) PluginHelper::getPlugin('task', 'privacyconsent')
```

2023-09-02 10:41 UTC, richard67 commented on plugins/task/privacyconsent/services/provider.php
> +                    (array) PluginHelper::getPlugin('task', 'privacyconsent')
See #40746 - thanks @heelc29 for the hint in the other PR.

2023-09-02 11:37 UTC, sandewt commented
> @sandewt That should be fixed with a separate PR because this code was not added by the PR here.

Done, see pr #41547

2023-09-02 15:57 UTC, richard67 commented
@heelc29 The PR is ready for testing. Code style error is not related to the PR but to the current 5.0-dev branch. Could you test this one, too? Testing instructions can be found in the description of this PR. Thanks in advance.

2023-09-03 10:11 UTC, richard67 commented on administrator/components/com_admin/script.php
> +                'exec-time'     => gmdate('H:i', $params->get('lastrun', 0)),
```suggestion
                'exec-time'     => gmdate('H:i', $params->get('lastrun', time())),
```

2023-09-03 13:40 UTC, richard67 commented on plugins/task/privacyconsent/forms/privacyconsentForm.xml
> +					description="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATION_DESC"
```suggestion
					label="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_LABEL"
					description="PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_DESC"
```

2023-09-03 14:05 UTC, merged

2023-09-04 17:11 UTC, alikon commented
thank you all for your help

2023-09-04 17:25 UTC, heelc29 commented
@richard67 Should some content of '#__privacy_consents' updated (content of subject) during upgrade to J5?

https://github.com/joomla/joomla-cms/blob/087821fbc2535f84805bf8a4588536c5cd60a7c8/plugins/task/privacyconsent/src/Extension/PrivacyConsent.php#L127-L132

2023-09-04 17:29 UTC, richard67 commented
> @richard67 Should some content of '#__privacy_consents' updated (content of subject) during upgrade to J5?
> 
> https://github.com/joomla/joomla-cms/blob/087821fbc2535f84805bf8a4588536c5cd60a7c8/plugins/task/privacyconsent/src/Extension/PrivacyConsent.php#L127-L132

Possibly. Can't check now. But the query looks as if it would fail for the old consents created with the old subject. Maybe it would be easier to extend this query so it checks for both subjects (language strings)?

2023-09-04 17:53 UTC, richard67 commented
I've asked the other maintainers to check that.

2023-09-04 18:24 UTC, richard67 commented
@alikon Could you check the above comments and advise?

2023-09-04 18:41 UTC, alikon commented
could be a solution to add an update to the `'#__privacy_consents' ` table on administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-09-02.sql

2023-09-04 18:43 UTC, richard67 commented
> could be a solution to add an update to the `'#__privacy_consents' ` table on administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-09-02.sql

I think yes. Can you do that?

2023-09-04 18:44 UTC, alikon commented
yes i'll do

2023-09-04 18:47 UTC, richard67 commented
@alikon But I am not really sure. There is still t

2023-09-04 18:56 UTC, alikon commented
i'll check it better but no more `PLG_SYSTEM_PRIVACYCONSENT_SUBJECT` so far 
so an update in the update script should do the work

2023-09-04 19:00 UTC, richard67 commented
> i'll check it better but no more `PLG_SYSTEM_PRIVACYCONSENT_SUBJECT` so far
> so an update in the update script should do the work

@alikon I saw some code of the system plugin still using that string. So please double check. And if you make a PR please provide some testing instructions. I am too tired now already.

2023-09-04 19:07 UTC, alikon commented
wrong grep or on the wrong barnch 😇 
i'll check it better

2023-09-04 19:16 UTC, richard67 commented
@alikon If the fix will not make it into beta 1 tomorrow, it should be in a new update SQL script.

2023-09-05 07:38 UTC, richard67 commented
@alikon I could find the string `PLG_SYSTEM_PRIVACYCONSENT_SUBJECT` being used in the `onUserAfterSave` method of the system plugin here:

https://github.com/joomla/joomla-cms/blob/5.0-dev/plugins/system/privacyconsent/src/Extension/PrivacyConsent.php#L176-L188

It inserts a record with subject `PLG_SYSTEM_PRIVACYCONSENT_SUBJECT` into the `#__privacy_consents` table when the user's privacy consent confirmation is saved.

And here in the `isUserConsented` method it selects the count of records for a user with the same subject and state 1 to check if a user has consented:

https://github.com/joomla/joomla-cms/blob/5.0-dev/plugins/system/privacyconsent/src/Extension/PrivacyConsent.php#L384-L392

The new task scheduler plugin sends the remainder mails with the mail template. This uses `PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_SUBJECT` as subject for the emails. That subject is not related to the subject in the `#__privacy_consents` table.

The `PLG_TASK_PRIVACYCONSENT_SUBJECT` is only used by the new task scheduler plugin as where condition when querying the database for expired consent or for consent which will expire so a reminder mail has to be sent.

So I think the right fix will be to change the query in the task scheduler plugin to use `PLG_SYSTEM_PRIVACYCONSENT_SUBJECT`, and the language string `PLG_TASK_PRIVACYCONSENT_SUBJECT` can be removed if it is not used anymore after that change.

Do you agree?

@heelc29 Thanks for checking. What do you think? Am I missing something?

2023-09-05 08:36 UTC, richard67 commented
@alikon @heelc29 Please check #41597 . Thanks in advance.

2023-09-05 18:13 UTC, alikon commented
👍  good team working