End of Support Plugin for Joomla 4.4 (based on previous PR #40556)
joomla/joomla-cms pull request #40565
Opened 2023-05-09 17:10 UTC by mfleeson

Pull Request for Issue # .

Originally this code was monitored and checked in https://github.com/joomla/joomla-cms/pull/40556
I messed up my local installation and then managed to close the original PR when I renamed the branch. Mea Culpa. My apologies.

### Summary of Changes

Rewriting the 3.10 End of Service Notification and placing it into Joomla 4 coding structure and style.
Simplified the language definitions to not be hardcoded for 3 to 4
Currently using const EOS_DATE = '2023-10-25'; in file plugins/quickicon/eos/src/Extension/Eos.php The correct date should be 2025-10-25 but then the notification does not appear.
Dimitris converted the jQuery code into working javascript for closing the notification and also calling the com_ajax so the hide me is stored in the plugin parameters.

### Testing Instructions

Build.
Check plg_quickicon_eos is enabled.
View Home Dashboard in the back end.

### Actual result BEFORE applying this Pull Request

No notification is displayed

### Expected result AFTER applying this Pull Request

A notification is displayed

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-05-09 17:35 UTC, alikon commented
> I messed up my local installation

@mfleeson: me ? quite often too 😃

2023-05-09 17:42 UTC, mfleeson commented
Build is failing due to a missing , in the base.sql file and when that's manually corrected the announcement is displayed and closes. But does not appear to call the ajax to write back to the database. Need to investigate further now I have a working 4.4 site.

2023-05-09 19:06 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +            'onGetIcons' => 'getEndOfServiceNotification',
```suggestion
            'onGetIcons' => 'getEndOfServiceNotification',
            'onAjaxEos'  => 'onAjaxEos',
```
`onAjaxEos` event necessary

2023-05-09 19:06 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        }
try/catch necessary?
what about the exit?

2023-05-09 19:06 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    public function getEndOfServiceNotification(QuickIconsEvent $event)
```suggestion
    public function getEndOfServiceNotification(QuickIconsEvent $event): void
```

2023-05-09 19:06 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        $query = $db->getQuery(true)->update($db->quoteName('#__extensions'))->set($db->quoteName('params') . ' = ' . $db->quote($this->params->toString('JSON')))->where($db->quoteName('type') . ' =
```suggestion
        $params = $this->params->toString('JSON');
        $db     = $this->getDatabase();
        $query  = $db->getQuery(true)
            ->update($db->quoteName('#__extensions'))
            ->set($db->quoteName('params') . ' = :params')
            ->where($db->quoteName('type') . ' = ' . $db->quote('plugin'))
            ->where($db->quoteName('folder') . ' = ' . $db->quote('quickicon'))
            ->where($db->quoteName('element') . ' = ' . $db->quote('eos'))
            ->bind(':params', $params);
```
use `$this->getDatabase()`
use `->bind()`
code style (line length)

2023-05-09 19:06 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        }
```suggestion
        if (!$this->getApplication()->isClient('administrator')) {
            return false;
        }

        if ($this->getApplication()->getIdentity()->guest) {
            return false;
        }

        if ($this->document->getType() !== 'html') {
            return false;
        }

        if ($this->getApplication()->getInput()->getCmd('tmpl', 'index') === 'component') {
            return false;
        }

        if ($this->getApplication()->getInput()->get('option') !== 'com_cpanel') {
            return false;
        }
```
use `$this->getApplication()`
use `$this->getApplication()->getInput`; input property is deprecated
code style (line length)

2023-05-09 19:06 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        return Factory::getApplication()->getIdentity()->authorise('core.login.admin');
```suggestion
        return $this->getApplication()->getIdentity()->authorise('core.login.admin');
```
use `$this->getApplication()`

2023-05-09 21:51 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        }
I'm not sure. it can throw an error if does not exist but we know it does so probably could be removed

2023-05-09 22:00 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        }
I'll remove it for testing

2023-05-10 06:36 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        }
@heelc29 

```
if ($this->document->getType() !== 'html') {
    return false;
 }
```
Why not using?
```
if $this->getApplication()->getDocument()->getType() !== 'html') {
    return false;
}
```

2023-05-10 06:44 UTC, laoneo commented on plugins/quickicon/eos/services/provider.php
> + * @package                 Joomla.Plugin
Can you make this doc block the same as in other files.

2023-05-10 06:44 UTC, laoneo commented on plugins/quickicon/eos/services/provider.php
> + * @subpackage              Quickicon.Eos
```suggestion
 * @subpackage              Quickicon.eos
```

2023-05-10 06:44 UTC, laoneo commented on plugins/quickicon/eos/services/provider.php
> +    public function register(Container $container)
```suggestion
    public function register(Container $container): void
```

2023-05-10 06:44 UTC, laoneo commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        try {
Remove this try catch

2023-05-10 06:44 UTC, laoneo commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                    $options         = ['defaultgroup' => $group, 'cachebase' => $client_id ? JPATH_ADMINISTRATOR . '/cache' : $this->getApplication()->get('cache_path', JPATH_SITE . '/cache')];
Why not just use the default cache path?

2023-05-10 06:45 UTC, laoneo commented
Please do not catch all the exceptions better to propagate them to the client.

2023-05-10 06:56 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        if ($this->document->getType() !== 'html') {
See, my comment https://github.com/joomla/joomla-cms/pull/40565#discussion_r1189419610

2023-05-10 07:11 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        }
@sandewt I ask already in the old PR https://github.com/joomla/joomla-cms/pull/40556#discussion_r1186895348

This comment was only about code style 😀

2023-05-10 08:56 UTC, mfleeson commented
I've come to the code this morning knowng that a lot of the changes being requested have been made and git tells me my fork which is based 4.4 is behind. It offered sync the fork which i clicked and it synced it with 4.3! so now it's saying i'm 140 commits ahead of 4.3. I don't understand how even though I created the fork on 4.4 and it worked fine yesterday it's now all gone back to 4.3. And I'm not sure how to get my fork back to 4.4 so I can make these last few uploads. Hope someone can help.

2023-05-10 08:59 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> + * @package                 Joomla.Plugin
I've fixed it in my local version. Just need to get the PR to update.

2023-05-10 09:02 UTC, mfleeson commented
Overnight this PR has aquired extra files which are not part of my commit. When I try and remove them from the PR I get Looks like something went wrong!

We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

2023-05-10 09:23 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        try {
Again, my code doesnt have the try / catch. Not sure why its still showing up in your review.

2023-05-10 09:25 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                    $options         = ['defaultgroup' => $group, 'cachebase' => $client_id ? JPATH_ADMINISTRATOR . '/cache' : $this->getApplication()->get('cache_path', JPATH_SITE . '/cache')];
Good point, code was taken from 3.10. Have changed to JPATH_CACHE

2023-05-10 09:27 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        if ($this->document->getType() !== 'html') {
phpstorm warns about polyphonic calls if I use if $this->getApplication()->getDocument()->getType() !== 'html') { instead of $this->document. Hence why I used $this->document. Happy to change it.

2023-05-10 09:45 UTC, mfleeson commented
It just gets better, I have the definitive code but it wont let me push it and gives the error "remote: fatal: bad tree object fa00be88a9b5283659b312b36877286b9c8f1f08        remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header"

2023-05-10 09:52 UTC, mfleeson commented
Here's the final code - https://drive.google.com/file/d/1pOdbTct0oFA82X0A2sIHTfgWIeRHTRaY/view?usp=share_link

2023-05-10 10:56 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        if ($this->document->getType() !== 'html') {
Understandably, this may be a new issue for the tracker to get clarity on this.

2023-05-10 10:58 UTC, laoneo commented
I think it should be back to normal, merged 4.3 into 4.4 and updated this pr.

2023-05-10 11:19 UTC, mfleeson commented
Once this has built a package, I will download and test it all again and then upload any final changes.

2023-05-10 11:26 UTC, dgrammatiko requested changes

2023-05-10 11:26 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    public function __construct($subject, Document $document, array $config = [])
Can we eliminate the constructor as it's a bad practice to do work here (degrades performance). The alternative is to have a private static boolean ie `private static $messagesInitialized = false;` and a 
```php
private function setMessage()
{
        $diff                 = Factory::getDate()->diff(Factory::getDate(Eos::EOS_DATE));
        $monthsUntilEOS       = floor($diff->days / 30.417);
        $message              = $this->getMessageInfo($monthsUntilEOS, $diff->invert);
        $this->currentMessage = $message;
        return $message;
}
```

Then change line 138 to 

```php
 if (!$this->messagesInitialized && $this->setMessage !== '') {
```

and line 385 to 

```php
 if (!$this->messagesInitialized && $this->setMessage !== '') {
```

Also remove the $document and use directly `$this->getApplication()->getDocument()`

2023-05-10 11:36 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    public function __construct($subject, Document $document, array $config = [])
I based the code on the quickicon/joomlaupdate. If we change this to not use __construct should we then change that for all of the other quickicons?

2023-05-10 12:28 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> + * @subpackage     quickicon.eos
```suggestion
 * @subpackage     Quickicon.eos
```

2023-05-10 12:39 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +// phpcs:enable PSR1.Files.SideEffects
Can you move this block down (below use) as with other files?

2023-05-10 12:42 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +// phpcs:enable PSR1.Files.SideEffects
Done in latest update

2023-05-10 12:42 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> + * @subpackage     quickicon.eos
Done in latest update

2023-05-10 12:43 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    public function __construct($subject, Document $document, array $config = [])
Done in latest update

2023-05-10 13:07 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @return array|bool
```suggestion
     * @return array
```

2023-05-10 13:09 UTC, dgrammatiko approved these changes

2023-05-10 13:10 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on 578147213e435fab450c81404a83838b436ce6bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40565">issues.joomla.org/tracker/joomla-cms/40565</a>.</sub>

2023-05-10 13:52 UTC, dgrammatiko commented
@mfleeson check https://github.com/mfleeson/joomla-cms/pull/2

2023-05-10 16:18 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @return array|bool
Because function getMessageInfo can return a boolean or an array depending on whether the message should be displayed is why setMessage which returns the value from that function is also array|bool

2023-05-10 17:51 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        return false;
```suggestion
        return[];
```

Oops missed this

2023-05-10 17:51 UTC, dgrammatiko commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @return  array|bool  An array with the message to be displayed or false
```suggestion
     * @return  array An array with the message to be displayed or false
```

2023-05-10 17:57 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @return array|bool
Sorry. You're right, I was looking at the wrong variable.

2023-05-11 06:15 UTC, sandewt commented on plugins/quickicon/eos/services/provider.php
> + * @license                 GNU General Public License version 2 or later; see LICENSE.txt
Spaces:
```suggestion
 * @package      Joomla.Plugin
 * @subpackage   Quickicon.eos
 *
 * @copyright    (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
 * @license      GNU General Public License version 2 or later; see LICENSE.txt
```

2023-05-11 06:15 UTC, sandewt commented on plugins/quickicon/eos/services/provider.php
> +\defined('_JEXEC') or die;
```suggestion
defined('_JEXEC') or die;
```

2023-05-11 06:15 UTC, sandewt commented on plugins/quickicon/eos/services/provider.php
> +     * @since __DEPLOY_VERSION__
Space:
```suggestion
     * @since  __DEPLOY_VERSION__
```

2023-05-11 06:16 UTC, sandewt commented on plugins/quickicon/eos/services/provider.php
> +                    (array)PluginHelper::getPlugin('quickicon', 'eos')
Space:
```suggestion
                    (array) PluginHelper::getPlugin('quickicon', 'eos')
```

2023-05-11 06:18 UTC, sandewt commented on plugins/quickicon/eos/services/provider.php
> +                $plugin->setApplication(Factory::getApplication());
> Can you make this doc block the same as in other files.
```suggestion
                $plugin->setApplication(Factory::getApplication());
                $plugin->setDatabase($container->get(DatabaseInterface::class));
```

2023-05-11 11:17 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> + * @license                 GNU General Public License version 2 or later; see LICENSE.txt
This is so odd. I copy/pasted from JoomlaUpdate to get the spacing correct but it didn't commit. Accepting this suggestion to make sure it sticks.

2023-05-11 11:38 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> +                $plugin->setApplication(Factory::getApplication());
Fixed in latest upload

2023-05-11 11:38 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> +                    (array)PluginHelper::getPlugin('quickicon', 'eos')
Fixed in latest upload

2023-05-11 11:38 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> +     * @since __DEPLOY_VERSION__
Fixed in latest upload

2023-05-11 11:38 UTC, mfleeson commented on plugins/quickicon/eos/services/provider.php
> +\defined('_JEXEC') or die;
Fixed in latest upload

2023-05-11 12:32 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since __DEPLOY_VERSION__
Move `__DEPLOY_VERSION__` up (here 1 space) for a nice alignment. This also applies to others.

```suggestion
     * @var    bool
     * @since  __DEPLOY_VERSION__
```

2023-05-12 11:53 UTC, basd82 commented
I have tested this item :white_check_mark: successfully on fe52b52969bf99026c7b5fdcdc2f1fc86ab283f0<br /><br />In the testing i had to discover the plugin first, enabled plugin
then did the test and it was a suc6

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40565">issues.joomla.org/tracker/joomla-cms/40565</a>.</sub>

2023-05-12 13:00 UTC, mfleeson commented
I tested this using the drone/package produced and a clean install. The plugin was enabled and displayed and functioned correctly.
I am not sure why drone is failing.
It says Disk full - please upload later (failing artifacts-system-tests and phpmin-system-mysql)

2023-05-12 13:15 UTC, dgrammatiko commented
I have tested this item :white_check_mark: successfully on fe52b52969bf99026c7b5fdcdc2f1fc86ab283f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40565">issues.joomla.org/tracker/joomla-cms/40565</a>.</sub>

2023-05-12 14:43 UTC, richard67 commented
I will wait with setting RTC as the system tests are still failing at making a new installation, and I don't know yet if that is related to this PR or now. I will test later today making a new installation to see what goes wrong. The SQL looks ok to me now after the last changes, but maybe I'm blind or it's something else.

Will update the branch now and restore the test count to see if we are lucky this time.

2023-05-12 14:50 UTC, richard67 commented
@mfleeson Due to the branch update you just have made, the test count in the issue tracker was invalidated. I just have restored the count so the previous human tests are counted.

Normally when you made a PR and it has 2 good human tests, you should avoid unnecessary branch updates in order to not invalidate the counter.

This time it was ok because I think you want to see if system tests are passing. If that will not be the case, you or someone else or me should make a new installation with the installation package created with the branch of that PR by drone.

By the way drone might have a problem now due to a full hard disk. People are already working on it.

2023-05-12 16:29 UTC, heelc29 commented
Should the plugin added to `coreExtensions` in [ExtensionHelper.php](https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Extension/ExtensionHelper.php)?

2023-05-12 16:40 UTC, richard67 commented
> Should the plugin added to `coreExtensions` in [ExtensionHelper.php](https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Extension/ExtensionHelper.php)?

Yes, and in the previous PR this was the case after my review: https://github.com/joomla/joomla-cms/pull/40556/files#diff-45688fa5398ae3d4bab3daa80bc4d2ea4785370233b82a7326f9676f965ec9eb

But in this PR here it's missing again.

@mfleeson Please add it to the ExtensionHelper.php.

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @throws Exception
```suggestion
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @throws Exception
```suggestion
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    *
```suggestion
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @throws Exception
```suggestion
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @throws Exception
```suggestion
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        }
```suggestion
        if ($event->getContext() !== $this->params->get('context', 'update_quickicon') || !$this->shouldDisplayMessage() || !$this->messagesInitialized && $this::setMessage() == []) {
            return;
        }

        $this->loadLanguage();
```
only load language files when necessary

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    protected $autoloadLanguage = true;
```suggestion
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    protected $autoloadLanguage = true;
```suggestion
```
only load language files when necessary

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        if ($event->getContext() !== $this->params->get('context', 'update_quickicon') || !$this->shouldDisplayMessage() || !$this->messagesInitialized && $this::setMessage() == []) {
```suggestion
        if ($event->getContext() !== $this->params->get('context', 'update_quickicon') || !$this->shouldDisplayMessage() || !$this->messagesInitialized && $this->setMessage() == []) {
```
why use _Scope Resolution Operator_?

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     *
```suggestion
     * setMessage
     *
```
comment?

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @since  1.0
```suggestion
     * @since  __DEPLOY_VERSION__
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    private function setMessage()
```suggestion
    private function setMessage(): array
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @return  array|bool  An array with the message to be displayed or false
@mfleeson has not yet been implemented

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    public const EOS_DATE = '2023-10-25';
Should there a public access?

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +
```suggestion
```

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    }
this method is not used

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                'image'         => 'minus-circle',
`image` is not used

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                'class' => 'success',
always `success` also after EOS?

2023-05-12 17:17 UTC, heelc29 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    private function getMessageInfo(int $monthsUntilEOS, int $inverted)
```suggestion
    private function getMessageInfo(int $monthsUntilEOS, int $inverted): array
```

2023-05-12 23:14 UTC, mfleeson commented
> > Should the plugin added to `coreExtensions` in [ExtensionHelper.php](https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Extension/ExtensionHelper.php)?
> 
> Yes, and in the previous PR this was the case after my review: https://github.com/joomla/joomla-cms/pull/40556/files#diff-45688fa5398ae3d4bab3daa80bc4d2ea4785370233b82a7326f9676f965ec9eb
> 
> But in this PR here it's missing again.
> 
> @mfleeson Please add it to the ExtensionHelper.php.

What is going on? In my code and what I uploaded I added this to ExtensionsHelper but now its not there?

2023-05-13 11:19 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @throws Exception
I have restored all of the code to the correct final version which had most of these fixes in place.

2023-05-13 11:19 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @throws Exception
I have restored all of the code to the correct final version which had most of these fixes in place.

2023-05-13 11:20 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    *
i have removed this function as Dimitri's modification stopped it being used.

2023-05-13 11:20 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     * @throws Exception
I have restored all of the code to the correct final version which had most of these fixes in place.

2023-05-13 11:21 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    }
I have removed this function after Dimitris modification stopped using it.

2023-05-13 11:38 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                'class' => 'success',
I've changed this back to use the status from the Message structure.

2023-05-13 11:39 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                'image'         => 'minus-circle',
I was waiting on configuraton data from Phil + Jenn. I've changed code to use image and that can then be changed in future.

2023-05-13 11:42 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    public const EOS_DATE = '2023-10-25';
Changed to private

2023-05-13 11:43 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +    protected $autoloadLanguage = true;
@richard67 Please can you confirm this change? I was told to make the eos match all of the other quickicons which autoload there language.

2023-05-13 11:45 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        if ($event->getContext() !== $this->params->get('context', 'update_quickicon') || !$this->shouldDisplayMessage() || !$this->messagesInitialized && $this::setMessage() == []) {
Because phpstorm says it's not defined except as a :: function

2023-05-13 11:47 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +     *
sorted.

2023-05-14 10:23 UTC, richard67 commented
@mfleeson There are still some unresolved review comments by @heelc29 . Unfortunately they are hidden by default when you check the conversation comments here, and you have to use a "load more ..." button which is not easy to find. But you can see them when you go to the changed file here on GitHub: https://github.com/joomla/joomla-cms/pull/40565/files#diff-43fd4a40d7409ad1e608154c3e900ae13a92340cf68d97225fccdcc9e300c008 . Could you check them? Thanks in advance.

2023-05-14 11:08 UTC, mfleeson commented
@richard67 I left those changes and tagged you for your input/review. He is suggesting changing the code so that language definitions load if the plugin actually needs to display. As I was told to keep this code as close to the core examples it currently autoloads the definitions so I wanted a 'senior' opinion on whether to implement his changes or not.

2023-05-14 11:15 UTC, richard67 commented
@mfleeson I think I know why the system tests are failing.

The good news: The installation test does not fail due to an SQL error. The installation succeeds when making a new installation with this branch.

But as described in the description of this PR, the EOS date has not been changed so it is still "2023-10-25", and so the message is shown:

![2023-05-14_j4 4_pr-40565_1](https://github.com/joomla/joomla-cms/assets/7413183/d0f6a270-312b-481a-8eeb-b1d3ee7a6948)

This causes the system test to fail because it does not find the button in the statistics message.

@laoneo Could you advise regarding the system tests? Should they be adjusted for the case that the message is shown, otherwise they will stop to work when 4.4 will have reached the time when the message is shown? If so, then @mfleeson should maybe wait with adjusting the EOS date in this PR to the right one so we could first see if the modification of the tests works for that case. And could you advise regarding the necessary change of the system tests?

@mfleeson When the previous question regarding the system tests is clarified and the tests have been adjusted, if necessary, then you should set the EOS date in this PR to the right one and add something to the testing instructions how testers can modify the file to get it shown again, so that we have system tests passing again before people test.

2023-05-14 11:17 UTC, richard67 commented
> @richard67 I left those changes and tagged you for your input/review. He is suggesting changing the code so that language definitions load if the plugin actually needs to display. As I was told to keep this code as close to the core examples it currently autoloads the definitions so I wanted a 'senior' opinion on whether to implement his changes or not.

@mfleeson There were also other review comments, not only those about the language loading, and for the language loading I am not really the right guy to decide how it should be done.

2023-05-14 11:33 UTC, richard67 commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        if ($event->getContext() !== $this->params->get('context', 'update_quickicon') || !$this->shouldDisplayMessage() || !$this->messagesInitialized && $this::setMessage() == []) {
But in line 287 below you use `$this->setMessage()`. Shouldn't phpstorm have complained there, too? I think `$this->setMessage()` should work here.

2023-05-14 11:59 UTC, dgrammatiko commented
@mfleeson to fix the failing tests change this line 

https://github.com/joomla/joomla-cms/blob/5770ed6d07d9d6c27605f26212ff5a6b408bf078/build/media_source/plg_system_stats/js/stats-message.es6.js#L75

to

```js
messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
```

2023-05-14 17:01 UTC, dgrammatiko commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
I guess the problem is not the order of the alerts but a timing issue. The tests need either some sleep or similar code to wait for the message to render

2023-05-14 17:04 UTC, mfleeson commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
Not sure, it threw the error because of the comments. Removed them and testing again.

2023-05-14 17:19 UTC, richard67 commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
System test is still failing so I think @dgrammatiko is right.

2023-05-14 17:32 UTC, dgrammatiko commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
There's a PR: https://github.com/joomla-projects/joomla-cypress/pull/5 but it's on another repo so to test it you need to change the package.json to point at the git of the PR

2023-05-15 06:57 UTC, laoneo commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
Don't worry too much about the system test, we can fix it later.

2023-05-15 07:05 UTC, laoneo commented
Thank you very much to all the testers and reviewers here, and especially @mfleeson for your great work. Just a short reminder. We will ship the first alpha on 30 May. So it would be cool to heave it ready in a proper state by the end of this week. Then we have enough time to iron out some bugs till the shipping date.

2023-05-15 08:52 UTC, mfleeson commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
Thanks. My understanding of the status of this plugin is I am waiting for Jenn for the wording they want which was going on the agenda for the Team Leads and then for the date to be restored to 2025

2023-05-15 13:07 UTC, richard67 commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
> Don't worry too much about the system test, we can fix them later.

@laoneo Should the change in the build/media_source/plg_system_stats/js/stats-message.es6.js be reverted?

2023-05-15 13:09 UTC, richard67 commented
> Thank you very much to all the testers and reviewers here, and especially @mfleeson for your great work. Just a short reminder. We will ship the first alpha on 30 May. So it would be cool to heave it ready in a proper state by the end of this week. Then we have enough time to iron out some bugs till the shipping date.

@laoneo @mfleeson It still needs to change the EOS date to the right value here: https://github.com/joomla/joomla-cms/pull/40565/files#diff-43fd4a40d7409ad1e608154c3e900ae13a92340cf68d97225fccdcc9e300c008R42 . We can't leave it like it is because the value '2023-10-25' was just for testing purpose.

2023-05-15 13:12 UTC, laoneo commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
If it was done only to make the tests pass, then yes.

2023-05-15 13:14 UTC, richard67 commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('afterbegin', Joomla.sanitizeHtml(json.html, allowed));
Yes, that's the case, it was only for making the system tests pass, and it did not help. @mfleeson Could you revert the changes in build/media_source/plg_system_stats/js/stats-message.es6.js ? Thanks in advance.

2023-05-15 14:03 UTC, dgrammatiko commented
On top of what @richard67 wrote above there's https://github.com/joomla/joomla-cms/pull/40599 which fixes the tests (the last 2-3 commits). I guess @laoneo should decide if he wants the tests fixed with this PR or in another.

2023-05-15 14:11 UTC, laoneo commented
All I wanted to point out was that the failing tests should not hold back the progress of this pr. If they can get fixed it is even better.

2023-05-15 15:18 UTC, sandewt commented
When you click on the image with the text, a link will open in the same screen. It would be nicer to open the documentation in another screen (target="_blank"), like in the J3 plugin.
I don't see immediately a solution when I look at the code. Because J4 is something different.
![Schermafbeelding 2023-05-15 165230](https://github.com/joomla/joomla-cms/assets/9271775/f1838654-fc2a-4c65-8a82-4bba89113a13)
An adjustment is not in a hurry at the moment. Can always do so later if we think this should be done.

2023-05-15 15:19 UTC, richard67 commented
@sandewt Yes, I've noticed that, too. It might be out of the scope of this PR here to fix that because it seems to be a general thing with the quickicons in J4.

2023-05-15 15:30 UTC, dgrammatiko commented
FWIW https://github.com/joomla/joomla-cms/pull/40602 should fix the failing tests so only the date should be changed here. @laoneo check the #40602

2023-05-22 14:27 UTC, MacJoom commented
@mfleeson Thank you for your work - could you please change the date to correct value in 2025?

2023-05-24 11:36 UTC, dgrammatiko commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('beforeend', Joomla.sanitizeHtml(json.html, allowed));
Why?

2023-05-24 11:36 UTC, MacJoom commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('beforeend', Joomla.sanitizeHtml(json.html, allowed));
Because of the discussion - the changes should be reverted.

2023-05-24 11:37 UTC, MacJoom commented on build/media_source/plg_system_stats/js/stats-message.es6.js
> +            messageContainer.insertAdjacentHTML('beforeend', Joomla.sanitizeHtml(json.html, allowed));
Or not ?

2023-05-24 12:20 UTC, merged

2023-05-24 12:37 UTC, sandewt commented
> [Update Eos.php - set hardcoded date to 2025-10-25](https://github.com/joomla/joomla-cms/pull/40565/commits/78f1be70f71a81581f5e06d15b442a4b1c947283)

Something is wrong here, the date is not correct according to the roadmap.

2023-05-24 13:24 UTC, mfleeson commented
The reason I hadn't set the final date was because it was being discussed at a recent meeting. Also the text definitions still need to be updated once finalised. Please reopen my branch. The current date from https://developer.joomla.org/roadmap.html is 17th October 2025 for end of support for J4.X

2023-06-27 19:44 UTC, heelc29 commented
@MacJoom Could you please add the milestone for J4.4?