Fix for TypeError: count() when running PHP 8.x
joomla/joomla-cms pull request #40610
Opened 2023-05-16 17:40 UTC by MacJoom

The error occurs when doing webservices API  POST call to /fields/groups/contacts/contact or /fields/groups/content/articles

Pull Request for Issue # .

### Summary of Changes

Is_array test before doing count()

### Testing Instructions

Code review -

or do test the webservices test with Postman and the collection from here: 
https://github.com/alexandreelise/j4x-api-collection

### Actual result BEFORE applying this Pull Request

TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/clients/client2/web3/web/joomla-cms/administrator/components/com_fields/src/Model/GroupModel.php:247 etc.

### Expected result AFTER applying this Pull Request

No Error, Item is added 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x ] No documentation changes for manual.joomla.org needed

2023-05-16 20:23 UTC, wilsonge requested changes
Something looks wrong here. We call count within that function (unless we return null from the early bail https://github.com/joomla/joomla-cms/blob/7c3f3ef074ddf128dddf8d17839c105622b2c072/administrator/components/com_fields/src/Helper/FieldsHelper.php#L65)

But in that case we should be checking for parts being null. because getting the 0th element on the line 244 of null also makes no sense

2023-05-16 20:39 UTC, MacJoom commented
Yes OK - then we do not need to a count again. I was just focusing on the part throwing the error...

2023-05-19 13:17 UTC, alikon commented
i've got a different error  with postman without your PR

PHP Warning:  Trying to access array offset on value of type null in `/joomla-cms/administrator/components/com_fields/src/Model/GroupModel.php on line 244`

![image](https://github.com/joomla/joomla-cms/assets/181681/3b14456a-f48b-400e-8468-134c5ff24b39)

2023-05-19 13:23 UTC, alikon commented
btw applying the pr no more error

![image](https://github.com/joomla/joomla-cms/assets/181681/1164bd44-fcb3-4c0c-abbf-98b5197a94a9)

2023-05-19 13:27 UTC, alikon commented
tested `fields/groups/contacts/contact` too

2023-05-19 13:27 UTC, alikon commented
I have tested this item :white_check_mark: successfully on 0110c19164f556a17aa13287cd6ebfcfdda22f51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40610">issues.joomla.org/tracker/joomla-cms/40610</a>.</sub>

2023-05-21 20:41 UTC, richard67 commented
@wilsonge Could you check and if ok add an approval with the review button so GitHub doesn’t show the unresolved review anymore? As far as I can see @MacJoom has solved your concerns.

2023-05-22 11:50 UTC, wilsonge approved these changes

2023-05-22 12:56 UTC, laoneo commented
The change looks ok, but I'm wondering why the context there is null?

2023-05-23 16:00 UTC, wilsonge commented on administrator/components/com_fields/src/Model/GroupModel.php
> +        //$parts is null if there are not two parts, early return
```suggestion
        // If we don't have a valid context then return early
```

2023-07-20 14:05 UTC, merged

2023-07-20 14:05 UTC, obuisard commented
Thank you Martin @MacJoom for the PR!