Replace hard coded img element by JLayout joomla.html.image and DRY
joomla/joomla-cms pull request #40618
Opened 2023-05-17 10:47 UTC by hans2103

Pull Request for no Issue

### Summary of Changes

This PR will change the hard coded `<img src=""...` inside the default view of mod_banners by a call to JLayout joomla.html.image and keeps it DRY.

### Testing Instructions

- Joomla 5 with testing sample data. (adjust mod_banners config and unset the chosen client, otherwise you don't see images... https://github.com/joomla/joomla-cms/issues/40616)
- Go to frontend index.php/banners 

### Actual result BEFORE applying this Pull Request

You will see a banner image on the page. 

### Expected result AFTER applying this Pull Request

You will see a banner image on the page.  The same as BEFORE. The HTML output is also the same as BEFORE. 
The only difference is that it is rendered by JLayout which allows users to create an override. 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-05-17 10:53 UTC, dgrammatiko commented on modules/mod_banners/tmpl/default.php
> +                    'alt' => htmlspecialchars($alt, ENT_QUOTES, 'UTF-8')
The `alt` is escaped in the Layout so you could pass it directly here

2023-05-17 11:42 UTC, hans2103 commented on modules/mod_banners/tmpl/default.php
> +                    'alt' => htmlspecialchars($alt, ENT_QUOTES, 'UTF-8')
adjusted my PR

2023-05-17 12:00 UTC, brianteeman commented on modules/mod_banners/tmpl/default.php
>                  <?php $alt = $alt ?: Text::_('MOD_BANNERS_BANNER'); ?>
Does this line ever get reached. Surely the previous condition is always matched

2023-05-17 12:03 UTC, hans2103 commented on modules/mod_banners/tmpl/default.php
>                  <?php $alt = $alt ?: Text::_('MOD_BANNERS_BANNER'); ?>
I was wondering the same thing. I think that is out of scope of this PR and adjusting / removing the line should be in another PR. Agree?

2023-05-17 12:03 UTC, brianteeman commented on modules/mod_banners/tmpl/default.php
>                  <?php $alt = $alt ?: Text::_('MOD_BANNERS_BANNER'); ?>
yes I realised that after typing it ;)

2023-05-17 12:04 UTC, hans2103 commented on modules/mod_banners/tmpl/default.php
>                  <?php $alt = $alt ?: Text::_('MOD_BANNERS_BANNER'); ?>
should be something like below I guess

```
$alt = $item->params->get('alt', $item->name); 
```

2023-05-17 12:05 UTC, hans2103 commented on modules/mod_banners/tmpl/default.php
>                  <?php $alt = $alt ?: Text::_('MOD_BANNERS_BANNER'); ?>
but... that's up to another PR. ;-)

2023-05-17 18:10 UTC, wojtekLs commented on modules/mod_banners/tmpl/default.php
> +                <?php $imageAttributes = [
why there are multiple `php` block there?

2023-05-17 18:11 UTC, wojtekLs commented on modules/mod_banners/tmpl/default.php
> +                            <?php echo $image; ?>
LGTM :)

2023-05-17 18:12 UTC, wojtekLs requested changes
Please merge multiple `php` blocks into one. Same goes with `if` statements.

2023-05-17 18:47 UTC, richard67 commented on modules/mod_banners/tmpl/default.php
> +                <?php $imageAttributes = [
Because we do it like that in our layouts so we have an HTML code style with small PHP blocks.

2023-05-17 18:48 UTC, richard67 commented
> Please merge multiple `php` blocks into one. Same goes with `if` statements.

Maybe you should first study our code style before making recommendations as if you were a long term contributor.

2023-05-18 11:30 UTC, dgrammatiko approved these changes

2023-05-23 11:58 UTC, chmst approved these changes

2023-05-23 11:59 UTC, chmst commented
Looks good to me. The $alt seems to be not correct. but this is not in scope of this PR.

2023-05-24 17:15 UTC, richard67 commented
> > code style
> 
> @richard67 No man. Having formalized code style doesnt mean that its good code style. Nor does it mean that it should be blindly followed.

@wojtekLs Better than following your comments which are completely useless since you talk about stuff of which you have no knowledge, e.g. our rules.

2023-05-24 17:22 UTC, richard67 commented
https://developer.joomla.org/coding-standards/php-code.html

> Mixed language usage (e.g. at the layout files)
>
> For layout files and all files where we use a mix of PHP and HTML (all PHP files in the view/tmpl and layout folder) we additionally wrap every line into a <?php ... ?> block and use the alternative syntax for control structures. This should make the code easier to read and make it easier to move blocks around without creating fatal errors due to missing <?php ... ?> tags.

@wojtekLs I haven't made these rules. For changing these rules it needs a decision by the production department. We all know that, only you insist on violating these rules because you comment here without having made yourself familiar with our rules.

2023-05-24 19:21 UTC, brianteeman commented
Why do we have to put to with this troll

2023-05-24 21:22 UTC, hans2103 commented
Please, can we get the focus on the PR again? The discussion about code styling is out of scope for this issue.
Thank you

2023-06-03 15:07 UTC, Quy commented on modules/mod_banners/tmpl/default.php
> +                } ?>
```suggestion
                <?php if (!empty($item->params->get('width'))) : ?>
                    <?php $imageAttributes['width'] = $item->params->get('width'); ?>
                <?php endif; ?>
                <?php if (!empty($item->params->get('height'))) : ?>
                    <?php $imageAttributes['height'] = $item->params->get('height'); ?>
                <?php endif; ?>
```

2023-07-03 20:27 UTC, Quy commented
The width/height settings are ignored.

Before PR:
```
<img
                                src="http://localhost/Joomla_5.0.0-alpha2-Alpha-Full_Package/images/banners/shop-ad-books.jpg#joomlaImage://local-images/banners/shop-ad-books.jpg?width=468&height=60"
                                alt="Banner"
                                width="50"                                height="50"                            >
```

After PR:
```
<img src="http://localhost/Joomla_5.0.0-alpha2-Alpha-Full_Package/images/banners/shop-ad-books.jpg" alt="Banner" width="468" height="60" loading="lazy">
```

2023-09-30 22:50 UTC, HLeithner commented
This pull request has been automatically rebased to 5.1-dev.

2023-10-01 13:20 UTC, wojtekLs commented
@HLeithner reasons?

2023-10-01 13:35 UTC, HLeithner commented
all pull requests have been rebased because the new branch for Joomla 5.1 has been created. since Joomla 5.0 don't get any new features from this point we we automatically rebase Pull requests with the label feature to the next minor branch. and bugs to the olders supported branch (in this case 4.4)

2023-10-11 08:06 UTC, hans2103 commented
> The width/height settings are ignored.
> 
> Before PR:
> 
> ```
> <img
>                                 src="http://localhost/Joomla_5.0.0-alpha2-Alpha-Full_Package/images/banners/shop-ad-books.jpg#joomlaImage://local-images/banners/shop-ad-books.jpg?width=468&height=60"
>                                 alt="Banner"
>                                 width="50"                                height="50"                            >
> ```
> 
> After PR:
> 
> ```
> <img src="http://localhost/Joomla_5.0.0-alpha2-Alpha-Full_Package/images/banners/shop-ad-books.jpg" alt="Banner" width="468" height="60" loading="lazy">
> ```

are they? The attributes `width` and `height` are still there.

2023-12-13 14:47 UTC, hans2103 commented
please close this PR as it is replaced by https://github.com/joomla/joomla-cms/pull/42508

2023-12-13 14:47 UTC, closed without merging