EOS - Plugin Disabling Quick Icon Display and adding correct text definitions
joomla/joomla-cms pull request #40774
Opened 2023-06-15 09:34 UTC by mfleeson

Disabling Quick Icon Display and adding correct text definitions and Joomla 5 links

Pull Request for Issue # .

### Summary of Changes
Changed announcement texts to approved wording
Changed links to Joomla 5
Commented out QuickIcon display code

### Testing Instructions
Edit Line 42 'private const EOS_DATE = '2025-10-17'; and change 2025 to 2023

### Actual result BEFORE applying this Pull Request

As well as the banner appearing a quickicon in the box near Joomla Update would appear

### Expected result AFTER applying this Pull Request

The quickicon no longer appears

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-06-15 10:40 UTC, zero-24 requested changes, later dismissed
Hi please add back the `Special:MyLanguage` to the docs URLs. This allows docs.joomla.org to redirect to an translated page when that is avaible.

2023-06-15 11:26 UTC, zero-24 commented
Thanks

2023-06-15 13:04 UTC, laoneo commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                  ->update($db->quoteName('#__extensions'))
Please revert that change, we intend only one tab.

2023-06-15 13:04 UTC, laoneo commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        /*$result[] = [
Please remove all the commented code, we have a history in git, so we can always revert to the old state.

2023-06-15 13:04 UTC, laoneo commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS="Quick Icon - Joomla 4.4 End Of Support Notification"
Should the work Joomla not have an ! at the end?

2023-06-15 13:06 UTC, mfleeson commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS="Quick Icon - Joomla 4.4 End Of Support Notification"
The string was supplied by Jen Gress reporting back from the team deciding on the wording for this. I'll check.

2023-06-15 13:57 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +                  ->update($db->quoteName('#__extensions'))
Done

2023-06-15 13:57 UTC, mfleeson commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS="Quick Icon - Joomla 4.4 End Of Support Notification"
Checked with Jen and documention. Changed all references of Joomla to Joomla! in the language strings

2023-06-15 13:58 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> +        /*$result[] = [
Done

2023-06-15 14:08 UTC, brianteeman commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS="Quick Icon - Joomla 4.4 End Of Support Notification"
Please see the style guide for this https://manual.joomla.org/docs/user-interface-text/joomla_name_usage

2023-06-15 14:27 UTC, mfleeson commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS="Quick Icon - Joomla 4.4 End Of Support Notification"
Thanks Brian, I will remove the ! after the Joomla name in the language strings.
Relevent section in Brian's link: Rule: No Bang!
References to Joomla in language strings should not include the exclamation point unless it is at the end of a sentence that is intended to be exclamatory.

2023-06-15 14:29 UTC, mfleeson commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS="Quick Icon - Joomla 4.4 End Of Support Notification"
Fixed

2023-06-20 11:24 UTC, sandewt commented
Why this icon twice? That makes it messy.

![issue-40774](https://github.com/joomla/joomla-cms/assets/9271775/b16a95f3-ba58-497f-8c9f-045151d52e16)

2023-06-20 11:26 UTC, brianteeman commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_ERROR_SUPPORT_ENDED="<p>Support has ended for your version of Joomla 4.4. <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Upgrade to Joomla 5</a> <span class=
```suggestion
PLG_QUICKICON_EOS_MESSAGE_ERROR_SUPPORT_ENDED="<p>Support has ended for your version of Joomla 4.4. <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Upgrade to Joomla 5</a> as soon as possible.</p>"
```

2023-06-20 11:27 UTC, brianteeman commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_INFO_01="<p>Joomla 5 has arrived! Find out all that Joomla 5 has to offer you. Check the landing page for <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Joom
```suggestion
PLG_QUICKICON_EOS_MESSAGE_INFO_01="<p>Joomla 5 has arrived! Find out all that Joomla 5 has to offer you. Check the landing page for <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Joomla 5 features</a> and improvements.</p>"
```

2023-06-20 11:27 UTC, brianteeman commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_INFO_02="<p>When is the time to upgrade to Joomla 5? Once the extensions your site needs are compatible. Learn <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\"
```suggestion
PLG_QUICKICON_EOS_MESSAGE_INFO_02="<p>When is the time to upgrade to Joomla 5? Once the extensions your site needs are compatible. Learn <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">how to use the Pre-Update Checker</a>.</p>"
```

2023-06-20 11:27 UTC, brianteeman commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>Joomla 4.4 has entered security only mode. Support ends %1$s. Start <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">planning to upgr
```suggestion
PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>Joomla 4.4 has entered security only mode. Support ends %1$s. Start <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">planning to upgrade</a> to Joomla 5 today.</p>"
```

2023-06-20 11:28 UTC, brianteeman commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY_SHORT="Joomla 4.4 to end support on %1$s. <span class=\"icon-new-tab\"></span>"
```suggestion
PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY_SHORT="Joomla 4.4 to end support on %1$s."
```

2023-06-20 11:28 UTC, brianteeman commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING="<p>Support ends on %1$s for Joomla 4.4 <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Upgrade to Joomla 5</a> <span class=\"icon-new-
```suggestion
PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING="<p>Support ends on %1$s for Joomla 4.4 <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Upgrade to Joomla 5</a> as soon as possible.</p>"
```

2023-06-20 11:28 UTC, brianteeman commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING_SHORT="End of support for Joomla 4.4 on %1$s. <span class=\"icon-new-tab\"></span>"
```suggestion
PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING_SHORT="End of support for Joomla 4.4 on %1$s."
```

2023-06-20 11:29 UTC, brianteeman commented
> Why this icon twice? That makes it messy.
>

Because the code is wrong :)

2023-06-20 12:28 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
>                  'snoozable'     => false,
The following variables have become obsolete: quickiconText, image, groupText.
See also the code elsewhere in this file.

2023-06-21 14:20 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
>                  'snoozable'     => false,
These fields were in use before the requirements changed and the quickicon display code was removed. Removed now.

2023-06-21 14:21 UTC, mfleeson commented on administrator/language/en-GB/plg_quickicon_eos.ini
> +PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING_SHORT="End of support for Joomla 4.4 on %1$s. <span class=\"icon-new-tab\"></span>"
Thanks Brian, Not sure how but language definitions wound back. I have uploaded the correct versions from my test server.

2023-06-21 15:42 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
>                  'snoozable'     => false,
Don't forget to remove the associated language strings.

2023-06-21 15:44 UTC, sandewt commented on plugins/quickicon/eos/src/Extension/Eos.php
> -        );
Line 132-136: Is this functionality still necessary?

2023-06-22 08:48 UTC, mfleeson commented on plugins/quickicon/eos/src/Extension/Eos.php
> -        );
That code has been removed along with line 132.

2023-06-22 11:21 UTC, sandewt commented
> Disabling Quick Icon Display ...

You removed the quickicon functionality. The plugin is still called `<name>plg_quickicon_eos</name>` and `group="quickicon"`

The naming of this plugin no longer corresponds to what the plugin shows. Is the naming still correct? Is there possibly a better alternative?

2023-06-22 11:28 UTC, laoneo commented
This plugin works now in a similar way as the php EOS plugin. So for now it is ok to have it in the quickicon group. On some point we need to move it to a new group.

2023-06-23 06:27 UTC, webgras commented
I have tested this item :white_check_mark: successfully on fda8a6cea0bb181969aef5e2ef463eab408aa9f8<br /><br />Banner works fine, tested all the dates.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40774">issues.joomla.org/tracker/joomla-cms/40774</a>.</sub>

2023-06-23 09:25 UTC, MacJoom commented
@zero-24 is the change OK?

2023-06-23 15:18 UTC, bayareajenn commented
Hi! Thanks for your work!
I've got a few things:

**1. in eos.php:**
line 217, 231, 245: link should be https://docs.joomla.org/Special:MyLanguage/Joomla_4.4.x_to_5.x_Planning_and_Upgrade_Step_by_Step
line 273: link should go to https://joomla.org/5
_Will you please fix those links?_

**2. in the language strings:**
line 10 PLG_QUICKICON_EOS_MESSAGE_ERROR_SUPPORT_ENDED="<p>Support has ended for your version of Joomla. <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Migrate to the next version</a> as soon as possible.</p>"
_Will you please change the word "migrate" to "upgrade"?_

line 14 PLG_QUICKICON_EOS_MESSAGE_INFO_02="<p>When is the time to migrate to the next version? Once the extensions your site needs are compatible. Learn <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">how to use the Pre-Update Checker</a>. </p>"
_Will you please change the word "migrate" to "upgrade"?_

line 16 PLG_QUICKICON_EOS_MESSAGE_WARNING_SECURITY_ONLY="<p>This version of Joomla has entered security only mode. Support ends %1$s. Start <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">planning to migrate</a> to the next version of Joomla today.</p>"
_Will you please change the word "migrate to "upgrade"?_

line 18 PLG_QUICKICON_EOS_MESSAGE_WARNING_SUPPORT_ENDING="<p>Support ends on %1$s for this version of Joomla. <a href=\"%2$s\" target=\"_blank\" rel=\"noopener noreferrer\">Migrate to the latest version of Joomla</a> as soon as possible.</p>" 
_Will you please change the word "Migrate" to "Upgrade"?_

Ok, I think that's it :) Thank YOU!!

2023-06-23 18:53 UTC, sandewt commented
@bayareajenn It is more effective to click on the relevant line in the code and add the suggestion.

![issue_4074](https://github.com/joomla/joomla-cms/assets/9271775/42ac109e-af27-4b4a-b13b-ec09812cbe7e)

2023-06-23 19:03 UTC, bayareajenn commented
> @bayareajenn It is more effective to click on the relevant line in the code and add the suggestion.
> 
> ![issue_4074](https://user-images.githubusercontent.com/9271775/248355396-42ac109e-af27-4b4a-b13b-ec09812cbe7e.png)

Yes, I'm sure it is. Sadly, I don't know how. I don't really know how to use github. I was in the code in the site. I didn't even think of going to the code in the PR. I'm not a developer. I apologise. The formatting went to poo even worse once I commented.

2023-06-23 19:31 UTC, sandewt commented
> Yes, I'm sure it is. Sadly, I don't know how. I don't really know how to use github......

Very understandable.

Click on the link, as indicated below with the red arrow at the top of this page.
You will then arrive at the relevant files.
And follow the instructions I indicated above.

![issue_4074-2](https://github.com/joomla/joomla-cms/assets/9271775/ed894b72-d8c4-4b1d-8ff6-67baac85acaf)

2023-06-23 19:36 UTC, bayareajenn commented
> > Yes, I'm sure it is. Sadly, I don't know how. I don't really know how to use github......
> 
> Very understandable.
> 
> Click on the link, as indicated below with the red arrow at the top of this page. You will then arrive at the relevant files. And follow the instructions I indicated above.
> 
> ![issue_4074-2](https://user-images.githubusercontent.com/9271775/248373762-ed894b72-d8c4-4b1d-8ff6-67baac85acaf.png)

Yes, I kinda got it and started adding them. Then realised that the nightly I was working off of is different from the files in here. So now I'm just thoroughly confused. I'm now unsure of what is correct and what isn't. So I'll sleep on it and work with the team. Thank you for teaching me @sandewt. I will get better over time.

2023-06-24 08:39 UTC, mfleeson commented
Hi Everyone. The version Jenn downloaded was the previous version before this PR. I have checked and these files are the correct ones with the correct language definitions and links.

2023-06-24 11:21 UTC, merged