Use the current user function in view instead of from the app
joomla/joomla-cms pull request #41059
Opened 2023-06-26 19:47 UTC by laoneo

### Summary of Changes
Uses the current user from the view in classes and template files.

### Testing Instructions
Open any view from a touched file and check if there is no error.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-06-28 08:41 UTC, HLeithner requested changes

2023-06-28 08:41 UTC, HLeithner commented on administrator/modules/mod_submenu/tmpl/default.php
> +$user = \Joomla\CMS\$this->getCurrentUser();
```suggestion
$user = $this->getCurrentUser();
```

2023-06-28 08:41 UTC, HLeithner commented on administrator/components/com_users/src/Model/MethodModel.php
> +            $user = $this->getCurrentUser() ?: Factory::getApplication()->getIdentity();
```suggestion
            $user = $this->getCurrentUser();
```
getCurrentUser automatically falls back to the application

2023-08-21 06:31 UTC, merged

2023-08-21 06:31 UTC, HLeithner commented
Thanks

2023-08-21 08:37 UTC, brianteeman commented
and this is why we shouldnt merge untested code see #41414