Bootstrap 5.3
joomla/joomla-cms pull request #41101
Opened 2023-07-02 09:43 UTC by wilsonge

### Summary of Changes
Upgrades to bootstrap 5.3. This isn't 100% b/c but its as b/c as I can make it. The biggest issue is that bootstrap introduced a `--link-color` parameter that a) causes various parts of our code to not compile and b) does the same thing as our `template-link-color`/`casseopia-color-link` EVs. I've tried to migrate our usage to the new BS variable - but also keep us setting the old variables for templates that depend on them.

Note as this is a first pass I'm deliberately disabling dark mode support *for now*. This should be enabled but will require another pass over our SCSS and I'd rather just get the dependency upgrade in for now before enabling the shiny new features.

### Testing Instructions
Check core loads and styling works as expected in both frontend and backend. If you have any extensions to hand ideally check that their styling also continue to work.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-07-02 10:06 UTC, brianteeman commented
re the changes in the cassiopeia php files for the atum variables. They are not needed as they are no used - see #41054

2023-07-02 10:21 UTC, dgrammatiko requested changes

2023-07-02 10:21 UTC, dgrammatiko commented on administrator/templates/atum/error_login.php
> +		--link-color: ' . $this->params->get('link-color', '#2a69b8') . ';
That WILL NOT work. Adjacent to the link color there’s also a link-color-rgb which should also be set…

2023-07-03 12:13 UTC, dgrammatiko commented on administrator/templates/atum/error_login.php
> +		--link-color: ' . $this->params->get('link-color', '#2a69b8') . ';
George at a minimum you need to override these:
<img width="599" alt="Screenshot 2023-07-03 at 14 07 39" src="https://github.com/joomla/joomla-cms/assets/3889375/55cdf82b-c16f-4862-b70b-973b871aaca0">

<img width="789" alt="Screenshot 2023-07-03 at 14 07 56" src="https://github.com/joomla/joomla-cms/assets/3889375/ee9e7fb4-3a39-47cd-bf1a-41b28284d3ef">

<img width="940" alt="Screenshot 2023-07-03 at 14 08 09" src="https://github.com/joomla/joomla-cms/assets/3889375/6ee8025c-05be-47a9-a61e-c76d2b9394e1">

FWIW there might be more -rgb colours that need some sort of hack. This one was the one I remembered without rechecking the final bootstrap.css and also because the links (the hover state) will be erratic in so many bootstrap components (tabs, accordion, button.link, etc...)

2023-07-12 15:50 UTC, HLeithner commented
can we get some progress here please I would like to have this merged so george can continue with the bs5.3 integration in to j5

2023-07-17 22:54 UTC, wilsonge commented on administrator/templates/atum/error_login.php
> +		--link-color: ' . $this->params->get('link-color', '#2a69b8') . ';
Should be fixed?

2023-07-21 10:47 UTC, MacJoom commented on administrator/templates/atum/error_login.php
> +		--link-color: ' . $this->params->get('link-color', '#2a69b8') . ';
@dgrammatiko - is the fix OK?

2023-07-21 15:49 UTC, dgrammatiko commented on administrator/templates/atum/error_login.php
> +		--link-color: ' . $this->params->get('link-color', '#2a69b8') . ';
LGTM

2023-07-21 16:37 UTC, Quy commented
Edit an article.
See no borders.

![41101-borders](https://github.com/joomla/joomla-cms/assets/368084/5ffd97c5-9100-46d7-8f30-551255d85434)

2023-07-21 16:40 UTC, dgrammatiko commented
> See no borders.

@wilsonge diff the choices.css from https://github.com/dgrammatiko/muta/blob/main/media_source/templates/administrator/muta/scss/vendor/choicesjs/choices.scss

2023-07-21 21:17 UTC, HLeithner commented
> > See no borders.
> 
> @wilsonge diff the choices.css from https://github.com/dgrammatiko/muta/blob/main/media_source/templates/administrator/muta/scss/vendor/choicesjs/choices.scss
> 
> probably these lines: https://github.com/dgrammatiko/muta/blob/36a98876000064ec3396ede9d739b4f757c14183/media_source/templates/administrator/muta/scss/vendor/choicesjs/choices.scss#L402

this is also in the current version? or should it be removed?

2023-07-21 23:34 UTC, Quy commented
Color is lighter than before.

![41101-checkbox](https://github.com/joomla/joomla-cms/assets/368084/d15961d1-1e35-4b64-b452-2e2551c55050)

2023-07-22 10:22 UTC, MacJoom commented
@wilsonge can you fix the conflicts? Thank you

2023-07-22 13:39 UTC, wilsonge commented
The borders is because it’s not pulling through the prefix variable and using the css variables with the -bs prefix. Not really sure why right now (I mean even after moving the prefix declaration into the variables.scss from the template file so it’s actually imported)

2023-07-22 14:15 UTC, dgrammatiko commented
@wilsonge the border is defined here: https://github.com/twbs/bootstrap/blob/8fcfce1ebd988fd4e5ed2f51acaa5c49e6b301c9/scss/_variables.scss#L904

and the select tags use it here: https://github.com/twbs/bootstrap/blob/8fcfce1ebd988fd4e5ed2f51acaa5c49e6b301c9/scss/_variables.scss#L1020

Try to move the input section before the select section: this https://github.com/joomla/joomla-cms/blob/217b967c1651ed64ab4dda333d1a34beec71bc10/build/media_source/templates/administrator/atum/scss/_variables.scss#L242-L251 goes after (or before) https://github.com/joomla/joomla-cms/blob/217b967c1651ed64ab4dda333d1a34beec71bc10/build/media_source/templates/administrator/atum/scss/_variables.scss#L212

Also it might need a fallback value as all the `--template-*` are defined after the template.css has been loaded (using a style tag). I might be wrong tho...

2023-07-22 15:38 UTC, MacJoom commented
I would like to have this one in the 4.4 alpha 3. Is it possible?

2023-07-22 17:21 UTC, wilsonge commented
I will try and fix this evening but I need to figure out the root cause. My recommendation is you merge it anyhow if it’s just choices borders that have a problem and I’ll commit to having a fix early next week. Even if it’s post alpha release we can just add it as a known issue to the release notes. Better to get people testing with it listed as known than to delay general testing another few weeks

2023-07-22 18:00 UTC, MacJoom commented
Thank you

2023-07-22 22:43 UTC, wilsonge commented
OK So the missing border on choices is fixed. The color change on the checkboxes is just part of the dark mode changes they made (yes I know we aren't using dark mode but the border changed as part of that PR)

2023-07-23 09:49 UTC, merged

2023-07-23 09:50 UTC, MacJoom commented
Thanks to @wilsonge and all reviewers

2023-10-15 08:24 UTC, richard67 commented on templates/cassiopeia/index.php
> +		--template-link-color: var(--link-color);
@wilsonge Here we have `--template-link-color: var(--link-color);`, but in component.php, error.php and offline.php we have `--link-color: var(--link-color);`. Why is it different, and if it's a mistake, which one is right?

2023-10-18 18:02 UTC, wilsonge commented on templates/cassiopeia/index.php
> +		--template-link-color: var(--link-color);
I don't know :D I think I wanted to map template-link-color to link-color for b/c for existing params - but i'm not 100% now.

2023-10-18 18:16 UTC, richard67 commented on templates/cassiopeia/index.php
> +		--template-link-color: var(--link-color);
I will see if I make a PR to change the `--link-color: var(--link-color);` to `--template-link-color: var(--link-color);` in files component.php, error.php and offline.php. I think that would be right but I have to test it.