Text::script should update existing script strings
joomla/joomla-cms pull request #41543
Opened 2023-09-01 15:57 UTC by Fedik

Pull Request for Issue #41516 .

### Summary of Changes

The `HTMLDocument::setHeadData` restores `scriptOptions` correctly, hovewer any further call of `Text::script` override previously restored strings.
The PR fixing it, also deprecates scriptStrings method.

### Testing Instructions
Please follow #41516 .
Or add :
```php
Text::script('JYES');
$this->document->addScriptOptions('yes', 'Yes');
$this->document->getWebAssetManager()
    ->addInlineScript('console.log(Joomla.getOptions("yes", "nope") + " " + Joomla.Text._("JYES", "Nope"))', [], ['type' => 'module']);
```
After this line https://github.com/joomla/joomla-cms/blob/1e7527b60ec42032abe7bfb9c000bacf38f65845/components/com_content/src/View/Article/HtmlView.php#L242
Enable "Conservative caching"
Open any Article view.
Check browser console.

### Actual result BEFORE applying this Pull Request
First request: `Yes Yes`
All following requests: `Yes Nope`

### Expected result AFTER applying this Pull Request
There a log `Yes Yes`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: 
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: 
- [x] No documentation changes for manual.joomla.org needed

2023-09-25 08:00 UTC, ceford commented
I have tested this item :white_check_mark: successfully on 42b0d7aa43360b18e7bb4f32956b92ed0852ecfc<br /><br />On this one I did not realise at first that I needed to look in the Console Logs which is not selected by default.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41543">issues.joomla.org/tracker/joomla-cms/41543</a>.</sub>

2023-09-30 22:43 UTC, HLeithner commented
This pull request has been automatically rebased to 4.4-dev.

2023-11-14 18:33 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 42b0d7aa43360b18e7bb4f32956b92ed0852ecfc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41543">issues.joomla.org/tracker/joomla-cms/41543</a>.</sub>

2023-11-14 18:45 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41543">issues.joomla.org/tracker/joomla-cms/41543</a>.</sub>

2023-11-15 07:06 UTC, laoneo requested changes

2023-11-15 07:06 UTC, laoneo commented on libraries/src/Language/Text.php
> +     * @deprecated 4.0 will be removed in 6.0. Without replacement.
Deprecation's can only be done in minor releases.

2023-11-15 09:05 UTC, Fedik commented on libraries/src/Language/Text.php
> +     * @deprecated 4.0 will be removed in 6.0. Without replacement.
How else it should be deprecated when PR stay open for months? ;)

2023-11-15 09:34 UTC, laoneo approved these changes

2023-11-15 09:34 UTC, merged

2023-11-15 09:35 UTC, laoneo commented
Thanks!