5.0 Self-class referencing
joomla/joomla-cms pull request #41664
Opened 2023-09-08 07:02 UTC by Denitz

### Summary of Changes

Use self instead of self class name.

### Testing Instructions

Apply patch.

### Actual result BEFORE applying this Pull Request

Complex code.

### Expected result AFTER applying this Pull Request

Nice code.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-09-12 15:19 UTC, HLeithner commented
This change is not so easy because it really depends what you want, using self would mean the defined object but the question is if static would be better in some cases if the class gets extended. So that pr is not a no brainier and needs some time to evaluate each replacement case

2023-09-30 22:49 UTC, HLeithner commented
This pull request has been automatically rebased to 5.1-dev.

2024-04-24 09:08 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2024-07-22 20:08 UTC, Hackwar requested changes
The last 2 files seem fine with me, but the first 4 seem more restrictive than before. Even though I don't expect anyone to extend from Rule and Rules.

2024-07-22 20:08 UTC, Hackwar commented on libraries/src/Access/Rule.php
> +        if ($identities instanceof self) {
Isn't that actually limiting this further? I mean, with the original code you should be able to use any object which inherits from Rule, while the newer code would mean only identities of the objects class would be able to be merged?

2024-07-22 20:08 UTC, Hackwar commented on libraries/src/Access/Rules.php
> +        } elseif ($actions instanceof self) {
Same as above. Seems to be more restrictive...

2024-07-22 20:08 UTC, Hackwar commented on libraries/src/Log/Log.php
> +            static::$instance =& $instance;
See above.

2024-07-22 20:08 UTC, Hackwar commented on libraries/src/Table/Table.php
> +        if (isset($this) && ($this instanceof self) && \is_null($against)) {
And another one.

2024-09-02 08:52 UTC, HLeithner commented
This pull request has been automatically rebased to 5.3-dev.

2025-03-04 17:21 UTC, HLeithner commented
This pull request has been automatically rebased to 6.0-dev.

2025-07-11 05:45 UTC, Denitz commented on libraries/src/Access/Rule.php
> +        if ($identities instanceof self) {
@Hackwar `instanceof` checks for inherited classes as well, not a problem.
See https://3v4l.org/lgQfT

2025-07-11 05:45 UTC, Denitz commented on libraries/src/Access/Rules.php
> +        } elseif ($actions instanceof self) {
@Hackwar See comment above.

2025-07-11 05:45 UTC, Denitz commented on libraries/src/Log/Log.php
> +            static::$instance =& $instance;
@Hackwar See comment above.

2025-07-11 05:45 UTC, Denitz commented on libraries/src/Table/Table.php
> +        if (isset($this) && ($this instanceof self) && \is_null($against)) {
@Hackwar See comment above.

2025-08-31 11:59 UTC, HLeithner commented
This pull request has been automatically rebased to 6.1-dev.

2025-09-12 15:10 UTC, closed without merging