[4.4] translation description text static error pages
joomla/joomla-cms pull request #42030
Opened 2023-10-03 15:59 UTC by heelc29

replaces #42023 for J4.4-dev

### Summary of Changes

update innerHTML of #descText1 element (translation)

### Testing Instructions

produce an error page are open any static error page (html) directly
eg. `domain.tl/includes/incompatible.html`
switch language

### Actual result BEFORE applying this Pull Request

description text is always english
![image](https://github.com/joomla/joomla-cms/assets/66922325/e21016ee-5a20-431a-9926-a9669bb4943d)

### Expected result AFTER applying this Pull Request

description is translated
![image](https://github.com/joomla/joomla-cms/assets/66922325/794745b8-b6b4-4e62-a12a-eb8e0d5b3bfa)

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

2023-10-05 16:00 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on 865a9010cff6bf0cdbbd1c11e0e7e75701fa72bd<br /><br />I've used the following methods to get the different html error pages and then changed the language a few times to different values.

### build_incomplete.html

On a clean branch without having run `composer install` and `npm ci`, go to the site's URL.

### incompatible.html

After having run `composer install` and `npm ci` but before installing Joomla, edit file `installation/index.php` file and change `define('JOOMLA_MINIMUM_PHP', '7.2.5');` to e.g. `define('JOOMLA_MINIMUM_PHP', '9.2.5');`.

Then go to the site's URL.

### fatal-error.html

After successful installation, delete all Joomla tables in the database of this site e.g. with phpMyAdmin and then go to the site's URL.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42030">issues.joomla.org/tracker/joomla-cms/42030</a>.</sub>

2023-10-09 18:01 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 865a9010cff6bf0cdbbd1c11e0e7e75701fa72bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42030">issues.joomla.org/tracker/joomla-cms/42030</a>.</sub>

2023-10-09 18:01 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42030">issues.joomla.org/tracker/joomla-cms/42030</a>.</sub>

2023-10-31 09:55 UTC, laoneo requested changes

2023-10-31 09:55 UTC, laoneo commented on build/warning_page/template.js
>          if (ref) {
Can you invert here the condition and return early?

2023-11-04 17:45 UTC, heelc29 commented on build/warning_page/template.js
>          if (ref) {
Done. There is no modification in the generated files due minify command in build tools.
https://github.com/joomla/joomla-cms/blob/a390ec1e8aaafc22a67aca4ce5d418646d7c9e70/build/build-modules-js/error-pages.es6.js#L41

2023-11-06 07:12 UTC, laoneo commented on build/warning_page/template.js
> +        var meta = document.querySelector('[http-equiv="Content-Language"]');
Do we need here to do "var meta" again as it is already done above?

2023-11-13 09:32 UTC, laoneo commented
Can you fix the conflicts and respond to my question? Would love to see this one in 4.4.1.

2023-11-13 17:16 UTC, heelc29 commented on build/warning_page/template.js
> +        var meta = document.querySelector('[http-equiv="Content-Language"]');
Yes I think so. I moved it only from line 51:
![image](https://github.com/joomla/joomla-cms/assets/66922325/624d1f00-8b72-46a1-a640-6f92c9aa5a8d)

If I remove it it produce an js error:
![image](https://github.com/joomla/joomla-cms/assets/66922325/f6a270c8-3b67-4dd7-9959-69acfca2f233)

2023-11-13 17:17 UTC, heelc29 commented
> Can you fix the conflicts and respond to my question?

Done

2023-11-15 07:02 UTC, laoneo commented on build/warning_page/template.js
> +        var meta = document.querySelector('[http-equiv="Content-Language"]');
Thanks!

2023-11-15 07:02 UTC, laoneo approved these changes

2023-11-15 07:03 UTC, merged

2023-11-15 07:03 UTC, laoneo commented
Thanks!