[5.1] Deprecate app/db properties in ActionLogPlugin
joomla/joomla-cms pull request #42090
Opened 2023-10-08 10:18 UTC by heelc29

### Summary of Changes

deprecate `$app` and `$db` property in ActionLogPlugin and their possible use replaced

I'm not sure about the horizon (J6.0 or J7.0) of the removal of the properties

### Testing Instructions

check action logs are still working

### Actual result BEFORE applying this Pull Request

deprecation messages are logged
https://github.com/joomla/joomla-cms/blob/bd79fd38124282927c50ce94bfa83150095f5a42/libraries/src/Plugin/CMSPlugin.php#L138
https://github.com/joomla/joomla-cms/blob/bd79fd38124282927c50ce94bfa83150095f5a42/libraries/src/Plugin/CMSPlugin.php#L148

### Expected result AFTER applying this Pull Request

deprecation messages are still logged, but properties are no longer used and now themselves deprecated

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2023-10-08 13:06 UTC, laoneo commented
If you do it in 5.0,then the removal must be 7.0.

2023-10-08 17:52 UTC, heelc29 commented
So the code to set the properties (in CMSPlugin) is not removed before 7.0?

2023-11-23 08:08 UTC, HLeithner commented on administrator/components/com_actionlogs/src/Plugin/ActionLogPlugin.php
> +        $user = $this->getApplication()->getIdentity();
I would suggest to create a local $app variable here since the function is called twice.

2023-11-23 08:09 UTC, HLeithner commented
> So the code to set the properties (in CMSPlugin) is not removed before 7.0?

yes next+1 major version

2023-11-23 08:11 UTC, HLeithner commented
also can you please create a deprecation entry in https://manual.joomla.org/migrations/50-51/new-deprecations

2023-12-18 14:30 UTC, heelc29 commented on administrator/components/com_actionlogs/src/Plugin/ActionLogPlugin.php
> +        $user = $this->getApplication()->getIdentity();
Done

2023-12-18 14:42 UTC, heelc29 commented
> also can you please create a deprecation entry in https://manual.joomla.org/migrations/50-51/new-deprecations

Done. https://github.com/joomla/Manual/pull/210

2023-12-19 07:26 UTC, laoneo commented
> So the code to set the properties (in CMSPlugin) is not removed before 7.0?

If we will do that, then we still can copy the code to this class to support the properties till 7.0. But I doubt that we go to remove the code in CMSPlugin in 7.0.

2024-01-21 10:36 UTC, HLeithner commented
@laoneo there is no reason to not merge this right?

2024-01-27 12:16 UTC, laoneo commented on administrator/components/com_actionlogs/src/Plugin/ActionLogPlugin.php
> +        $app  = $this->getApplication();
Here is a fallback needed, when getApplication returns null, to use $this->app, otherwise you force all plugins, which do extend from this class, to inject the application, especially when they use the legacy architecture, then we have a problem. This would be a rather hard BC break.

2024-01-27 12:17 UTC, laoneo requested changes

2024-01-27 12:17 UTC, laoneo commented on administrator/components/com_actionlogs/src/Plugin/ActionLogPlugin.php
> +        $app  = $this->getApplication();
```suggestion
        $app  = $this->getApplication() ?: $this->app;
```
Here is a fallback needed, when getApplication returns null, to use $this->app, otherwise you force all plugins, which do extend from this class, to inject the application, especially when they use the legacy architecture, then we have a problem. This would be a rather hard BC break.

2024-01-29 06:49 UTC, laoneo approved these changes

2024-03-04 11:58 UTC, bembelimen commented
I have tested this item :white_check_mark: successfully on 4fbb778e57b4ede2f33da8b30f92535a25c909d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42090">issues.joomla.org/tracker/joomla-cms/42090</a>.</sub>

2024-03-04 12:12 UTC, laoneo commented
I have tested this item :white_check_mark: successfully on 4fbb778e57b4ede2f33da8b30f92535a25c909d7<br /><br />Tested with the action log plugin of DPCalendar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42090">issues.joomla.org/tracker/joomla-cms/42090</a>.</sub>

2024-03-04 12:44 UTC, merged

2024-03-04 12:44 UTC, LadySolveig commented
Thank you  @heelc29