Access level registered for  com_user
joomla/joomla-cms pull request #42254
Opened 2023-10-31 08:53 UTC by chmst

Pull Request for Issue #28804 .

### Summary of Changes
Remove rendering status modules from login, Set accesslevel "registered" for mod menu

### Testing Instructions
Grant access to the backend for a usergroup which has not viewlevel "special", for example to usergroup registered.
These user then can loign to the backend.

### Actual result BEFORE applying this Pull Request
He cannot log out

### Expected result AFTER applying this Pull Request
The mod_user is active, the user can log_out.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-10-31 08:58 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/4.4.0-2023-10-31.sql
> +UPDATE `#__modules` SET `access` = '2' WHERE `module` = 'mod_user' AND `client_id` = 1;
```suggestion
UPDATE `#__modules` SET `access` = 2 WHERE `module` = 'mod_user' AND `client_id` = 1;
```
Don't use strings for integer values.

2023-10-31 08:58 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/4.4.0-2023-10-31.sql
> + UPDATE "#__modules" SET "access" = '2' WHERE "module" = 'mod_user' AND "client_id" = 1;
```suggestion
 UPDATE "#__modules" SET "access" = 2 WHERE "module" = 'mod_user' AND "client_id" = 1;
```
Don't use strings for integer values.

2023-10-31 12:48 UTC, brianteeman commented
Is it intended top remove the link to the frontend of the site from the login page?

2023-11-23 08:14 UTC, HLeithner commented
I think we can't hard code access level ids in sql statements (there is no guarantee that 2 === registered)

2023-11-23 08:15 UTC, HLeithner requested changes
as said above sql updates can't use hardcoded access levels

2024-04-20 13:01 UTC, carlitorweb commented
Should not be enough for this module to appear that the user have access to the administrator? How I see it, this module do not need to proccess any access level to see if he can or not show up in that position. If you log in, you need a way to log out and you don't need an access level to define it.

2024-11-15 13:20 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2025-01-16 08:44 UTC, Hackwar commented
Any news on this one?

2025-04-15 16:16 UTC, HLeithner commented
This pull request has been automatically rebased to 5.3-dev.

2025-08-28 10:16 UTC, brianteeman commented
The only way I can think of to ensure that the logout is present is to render the module directly in the admin template with a check that the user has core.admin permissions and not to use the viewlevel permissions.

2025-10-15 17:05 UTC, HLeithner commented
This pull request has been automatically rebased to 5.4-dev.

2025-11-02 19:27 UTC, richard67 commented
> as said above sql updates can't use hardcoded access levels

Besides this, the update SQL scripts would need to be renamed due to the rebase to 5.4-dev. But I think they better are removed as I see no way to find out the right access level with an SQL query for all possible cases of access level modifications which might have been done on a site.

2026-02-01 10:08 UTC, closed without merging