Fix table multiselect
joomla/joomla-cms pull request #42330
Opened 2023-11-10 14:45 UTC by Fedik

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/25500 .

### Summary of Changes

Fix table multiselect with Shift key

### Testing Instructions

Run `npm install`
Go to administrator Artcles list, and try to select rows in table: one by one, and with use of Shift

### Actual result BEFORE applying this Pull Request
one by one: works
with use of Shift: does not work

### Expected result AFTER applying this Pull Request
one by one: works
with use of Shift: works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2023-11-10 15:14 UTC, dgrammatiko requested changes

2023-11-10 15:14 UTC, dgrammatiko commented on build/media_source/system/js/multiselect.es6.js
> +document.addEventListener('DOMContentLoaded', () => onBoot(document));
@Fedik since this is a `type=module` you don't need the event here:

```suggestion
onBoot(document);
```

2023-11-10 15:20 UTC, Fedik commented on build/media_source/system/js/multiselect.es6.js
> +document.addEventListener('DOMContentLoaded', () => onBoot(document));
Yeap, but I will keep it ;)

2023-11-10 15:22 UTC, dgrammatiko commented on build/media_source/system/js/multiselect.es6.js
> +document.addEventListener('DOMContentLoaded', () => onBoot(document));
The `DOMContentLoaded` event is a performance issue and it's best to not be used anymore...
That goes for all the JS scripts...

2023-11-10 15:27 UTC, Fedik commented on build/media_source/system/js/multiselect.es6.js
> +document.addEventListener('DOMContentLoaded', () => onBoot(document));
It just a listener, there still a timing diference betwen use or not use it.
For this script is fine as it is.

2023-11-11 08:23 UTC, Fedik commented on build/media_source/system/js/multiselect.es6.js
> +document.addEventListener('DOMContentLoaded', () => onBoot(document));
Okay, it does not hurt anyway :)

2023-11-11 09:09 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 06603abce8ec14890286345b233cc69d106a8bcc<br /><br />Thanks for fixing this 4 year old bug<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42330">issues.joomla.org/tracker/joomla-cms/42330</a>.</sub>

2023-11-11 12:47 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 06603abce8ec14890286345b233cc69d106a8bcc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42330">issues.joomla.org/tracker/joomla-cms/42330</a>.</sub>

2023-11-11 12:52 UTC, alikon commented
RTC
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42330">issues.joomla.org/tracker/joomla-cms/42330</a>.</sub>

2023-11-13 08:43 UTC, merged

2023-11-13 08:43 UTC, laoneo commented
Thanks!