[5.1] SEF: Implementing index.php behavior
joomla/joomla-cms pull request #42704
Opened 2024-01-23 19:32 UTC by Hackwar

### Summary of Changes
Joomla has been improving its SEO performance constantly and one issue which is still open is the behavior of `index.php` in URLs. In some rare cases, the URL might end with `index.php`, even though that is not needed anymore, resulting in duplicate content, since the same URL without `index.php` gets the same result. A common case is the URL for the homepage, which often enough contains that reference.

This PR introduces 2 new settings in the SEF system plugin. The first lets you enable the removal of the index.php as last part of the path of the URL. This setting only takes effect if URL rewriting is enabled. The second option allows to enforce the removal of the index.php by redirecting incoming GET requests with index.php as last part of the URL path to the same URL without that index.php part.

This PR depends on #42692.

I'd like to thank [ithelps Digital](https://www.ithelps-digital.com/) for sponsoring this feature.

### Testing Instructions
Unfortunately for testing, core Joomla does not produce such URLs anymore, so we need to do some trickery to trigger the problem.
1. Apply the PR
2. Edit libraries/src/Router/SiteRouter.php and change line 466 to `$uri->setPath($uri->getPath() . '/' . $tmp . 'index.php');`
3. Look at your URLs in the frontend and see the added `index.php`
4. Enable both options in the SEF system plugin.
5. See the `index.php` vanished in the frontend.
6. Open your sites homepage with an added `index.php`
7. See that you are redirected to the same page but without the suffix.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2024-01-23 20:55 UTC, brianteeman commented
1. Instead of adding another option which a large % of users will never use why not simply do this in the htaccess.
2. the description is confusing "Remove unneeded index.php from URLs" because it sounds the same as the existing option which removes index.php
3. If accepted dont you need to update the installation and the configuration.php.dist
4. What happened to the requirement for all new "features" to be accompanied with documentation

2024-01-23 21:37 UTC, Hackwar commented
To the other points: see other PR

To 2.: I will reword that.

2024-01-24 17:50 UTC, Quy commented on administrator/language/en-GB/plg_system_sef.ini
> +PLG_SEF_INDEXPHP_REDIRECT_LABEL="Redirect unnecessary index.php URLs"
```suggestion
PLG_SEF_INDEXPHP_LABEL="Remove index.php from URLs"
PLG_SEF_INDEXPHP_REDIRECT_LABEL="Redirect index.php URLs"
```

2024-01-24 22:33 UTC, brianteeman commented
I'm misunderstanding something

Why would you have the first option enabled but **not** have the second option enabled

2024-01-24 22:41 UTC, Hackwar commented
The first option modifies how URLs are created. The second one modifies how URLs are parsed. Since people are doing awful things in routing, we can't be sure that their changes don't break this feature, this the 2 options can be enabled separately.

2024-01-24 22:53 UTC, brianteeman commented
Honestly I cant see the value for core of adding 4 extra options (this PR and the other one) to address issues in other peoples code. Thats a maintainability nightmare and a usability issue for all those people that wonder what these options do etc. If, as you say, core does not create these urls then it should be for the extension dev to fix their own problem. And if they wont the site owner can easily create an htaccess rule.

2024-01-29 21:01 UTC, ot2sen commented
Brian got quite a few valid points here. Why?
The instruction for test even tells why not. "Unfortunately for testing, core Joomla does not produce such URLs anymore, so we need to do some trickery to trigger the problem." Then why is it a core issue?

Wouldn´t it better go into a checking feature for the official extension JED Checker, for it to teach third-party devs how not to do awful things in routing? IE, do this and you won´t get approved for fame and showcase. Fix it and get in.
https://extensions.joomla.org/extension/jedchecker/

2024-01-30 09:31 UTC, Hackwar commented
And at the same time, our users are complaining about sub-par behavior of Joomla. So, should we shift the blame and force users to be stuck in that situation or provide a solution for now to get around that?

I'm happy to add this to the JED checker as soon as you solved the Halting problem.

2024-01-30 09:45 UTC, brianteeman commented
Adding more options is never a solution. Those same users will still complain as they dont know about the options (unless they ask). If its such a real problem (I have no idea) then make the changes without options

2024-01-30 10:30 UTC, brianteeman commented
Confusing with the existing option

![image](https://github.com/joomla/joomla-cms/assets/1296369/bf427e89-d401-454f-a508-201c0caaf571)

2024-01-31 18:47 UTC, wilsonge commented on plugins/system/sef/src/Extension/Sef.php
> +        if ($_SERVER['REQUEST_METHOD'] != 'GET') {
```suggestion
        if ($this->app->getInput()->getMethod() != 'GET') {
```

If i remember right this is the same thing but properly using the Input abstraction

2024-02-10 10:59 UTC, Hackwar commented on plugins/system/sef/src/Extension/Sef.php
> +        if ($_SERVER['REQUEST_METHOD'] != 'GET') {
I'm going to trust you on this one.

2024-02-10 11:12 UTC, Hackwar commented
I changed the feature and description above.

2024-02-13 08:49 UTC, SniperSister commented
I have tested this item :white_check_mark: successfully on 4e471b01f9f282ebd85afe86e69b44014a1e5112<br /><br />Works as described!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42704">issues.joomla.org/tracker/joomla-cms/42704</a>.</sub>

2024-02-14 09:00 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 4e471b01f9f282ebd85afe86e69b44014a1e5112<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42704">issues.joomla.org/tracker/joomla-cms/42704</a>.</sub>

2024-02-14 10:51 UTC, richard67 commented
Setting RTC as it has 2 good tests, but setting also the RMDG (release manager decision queue) label because this PR is subject of discussion among maintainers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42704">issues.joomla.org/tracker/joomla-cms/42704</a>.</sub>

2024-02-14 13:16 UTC, Quy commented on plugins/system/sef/src/Extension/Sef.php
> +        }
```suggestion
            is_a($event->getRouter(), SiteRouter::class)
            && $this->app->get('sef_rewrite')
            && $this->params->get('indexphp')
        ) {
            // Enforce removing index.php with a redirect
            $event->getRouter()->attachParseRule([$this, 'removeIndexphp'], SiteRouter::PROCESS_BEFORE);
        }
```

2024-02-14 13:17 UTC, Quy commented on plugins/system/sef/sef.xml
> +				>
```suggestion
					>
```

2024-02-14 18:46 UTC, HLeithner requested changes

2024-02-14 18:46 UTC, HLeithner commented on plugins/system/sef/src/Extension/Sef.php
> +        if ($this->app->getInput()->getMethod() != 'GET') {
```suggestion
        if ($this->app->getInput()->getMethod() !== 'GET') {
```

2024-02-14 18:46 UTC, HLeithner commented on plugins/system/sef/src/Extension/Sef.php
> +        if (substr($origUri->getPath(), -9) == 'index.php') {
```suggestion
        if (substr($origUri->getPath(), -9) === 'index.php') {
```

2024-02-14 18:46 UTC, HLeithner commented on plugins/system/sef/src/Extension/Sef.php
> +        if (substr($origUri->getPath(), \strlen(Uri::base(true)), 11) == '/index.php/') {
```suggestion
        if (substr($origUri->getPath(), \strlen(Uri::base(true)), 11) === '/index.php/') {
```

2024-02-14 18:49 UTC, richard67 commented
Code style fixes and strict comparison should be done. After that, I think it just needs a review but not new human tests.

2024-02-20 09:47 UTC, Hackwar commented
After some discussions, we decided to switch this to use 301 redirects instead of 303s.

2024-02-20 11:38 UTC, richard67 commented
Back to pending as there have been made changes.
@SniperSister @viocassel Could you test again? Thanks in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42704">issues.joomla.org/tracker/joomla-cms/42704</a>.</sub>

2024-02-20 12:03 UTC, SniperSister commented
I have tested this item :white_check_mark: successfully on c35a3a0252205465fc9a14bd30a9b61c8d41e58e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42704">issues.joomla.org/tracker/joomla-cms/42704</a>.</sub>

2024-02-20 12:26 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on c35a3a0252205465fc9a14bd30a9b61c8d41e58e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42704">issues.joomla.org/tracker/joomla-cms/42704</a>.</sub>

2024-02-20 12:46 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42704">issues.joomla.org/tracker/joomla-cms/42704</a>.</sub>

2024-02-24 11:20 UTC, Hackwar commented
Link to documentation has been added.

2024-02-29 15:46 UTC, merged

2024-02-29 15:46 UTC, bembelimen commented
Thx