[5.1] Rewrite treeselect in vanilla JS
joomla/joomla-cms pull request #42776
Opened 2024-02-08 05:32 UTC by C-Lodder

### Summary of Changes

This PR removes the jQuery dependency for the treeselect Javascript.

Also uses a `<div>` for the dropdown heading, as opposed to a `<h1>`.

### Testing Instructions

1. Go to edit any module in the Module Manager.
2. Navigate to the "Menu Assignment" tab
3. Select "Only on the pages selected"
4. Play around with all the treeselect options (expanding, collapsing, checking, unchecking, etc)

2024-02-08 07:58 UTC, fgsw commented
I have tested this item :white_check_mark: successfully on 29ae5d3b5539d7d2e7b3c206366981edd7d5cd49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42776">issues.joomla.org/tracker/joomla-cms/42776</a>.</sub>

2024-02-08 09:15 UTC, dgrammatiko requested changes

2024-02-08 09:15 UTC, dgrammatiko commented on build/media_source/system/js/treeselectmenu.es6.js
> +const direction = (document.dir !== undefined) ? document.dir : document.getElementsByTagName('html')[0].getAttribute('dir');
```suggestion
const direction = (document.dir !== undefined) ? document.dir : document.documentElement.dir;
```

2024-02-12 11:47 UTC, Fedik commented
I have tested this item :white_check_mark: successfully on 4f775be8a236528adfa311277ad213015c074f27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42776">issues.joomla.org/tracker/joomla-cms/42776</a>.</sub>

2024-02-12 11:47 UTC, Fedik commented
r2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42776">issues.joomla.org/tracker/joomla-cms/42776</a>.</sub>

2024-02-25 23:11 UTC, LadySolveig commented
Thank you for your work @C-Lodder I tested this and as soon as an individual menu item has been manually selected/deselected, the dropdown next to it for the entire menu for "selecting/deselecting" all menu items no longer has any effect on the previously manually changed entry. 
Only again after the complete page refresh.
However, this error already exists in the old version.
Could you please take a look here?

2024-02-26 05:50 UTC, C-Lodder commented
@LadySolveig Can do, but the toolbar in the edit view is missing. I this a known bug with the recent upmerge?

2024-02-26 07:10 UTC, Fedik commented
> but the toolbar in the edit view is missing

Clear the cache for autoload_psr4.php

2024-02-26 09:02 UTC, C-Lodder commented
@LadySolveig Good catch. Fixed now

2024-02-26 09:48 UTC, LadySolveig commented
Thank you @C-Lodder for your quick response and the fix. 
I'm very happy that you were able to fix this bug that has been around for a while!

2024-02-26 10:06 UTC, merged

2024-02-26 10:07 UTC, LadySolveig commented
Thank you for your work @C-Lodder and also to the testers and support @fgsw @Fedik @dgrammatiko