avif/webp
joomla/joomla-cms pull request #43295
Opened 2024-04-18 07:41 UTC by dgrammatiko

Pull Request for Issue # .

### Summary of Changes

- add webp and avif support for edit images in the media manager
- add missing avif support in the `Image` class
- add support for webp/avif in the resize plugin

### Testing Instructions

### Actual result BEFORE applying this Pull Request

### Expected result AFTER applying this Pull Request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2024-04-19 00:30 UTC, Quy commented on plugins/media-action/resize/src/Extension/Resize.php
> +        }
```suggestion
        if (strtolower($item->extension) === 'avif') {
            return;
        }

        $imgObject = new Image(imagecreatefromstring($item->data));
```

2024-04-19 16:37 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 6f7b7cbaf4628f766ac91a8f8702d8d3a472f178<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43295">issues.joomla.org/tracker/joomla-cms/43295</a>.</sub>

2024-04-19 22:28 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 6f7b7cbaf4628f766ac91a8f8702d8d3a472f178<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43295">issues.joomla.org/tracker/joomla-cms/43295</a>.</sub>

2024-04-19 23:13 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43295">issues.joomla.org/tracker/joomla-cms/43295</a>.</sub>

2024-04-20 06:32 UTC, dgrammatiko commented
Can we remove the RTC. Turns out that PHP docs were wrong https://github.com/php/php-src/issues/14010

Please test again with:

- Delete the files. Edit the Media Action plugin resize with some values (ie 800 and 500)  and check that the images on upload are getting resized.

2024-04-20 09:30 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 84874f655113ae9e8fcd6a4d84ab6a17be1edfc8<br /><br />👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43295">issues.joomla.org/tracker/joomla-cms/43295</a>.</sub>

2024-04-20 11:38 UTC, richard67 commented
Back to pending. @Quy Could you test again? Thanks in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43295">issues.joomla.org/tracker/joomla-cms/43295</a>.</sub>

2024-04-20 16:01 UTC, brianteeman commented
It was commented elsewhere that this PR would also resolve an issue with files named JPG as opposed to jpg.

Sorry to say this pr makes no difference

2024-04-20 16:09 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 84874f655113ae9e8fcd6a4d84ab6a17be1edfc8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43295">issues.joomla.org/tracker/joomla-cms/43295</a>.</sub>

2024-04-20 16:09 UTC, Quy commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43295">issues.joomla.org/tracker/joomla-cms/43295</a>.</sub>

2024-04-24 09:06 UTC, HLeithner commented
This pull request has been automatically rebased to 5.2-dev.

2024-04-24 09:24 UTC, dgrammatiko commented
@HLeithner why did you moved this one to 5.2? This is a bug fix nothing new here...

2024-04-24 09:32 UTC, HLeithner commented
I only had quick look and just classified it as feature since nobody else looked at it. If I'm wrong no problem can be changed back as long as nobody update the branch.

2024-04-24 09:37 UTC, dgrammatiko commented
AVIF support was added with https://github.com/joomla/joomla-cms/pull/41381 but George missed some parts. This PR just adds them, it doesn't have to wait for 6 months

2024-04-24 10:02 UTC, HLeithner commented
switched back to 5.1 thanks

2024-05-11 11:01 UTC, LadySolveig requested changes

2024-05-11 11:01 UTC, LadySolveig commented on plugins/media-action/resize/src/Extension/Resize.php
> +        if (!\in_array(strtolower($item->extension), ['jpg', 'jpeg', 'png', 'gif', 'webp', 'avif'])) {
```suggestion
        if (!\in_array(strtolower($item->extension), ['jpg', 'jpeg', 'png', 'gif', 'webp'])) {
```

2024-05-11 11:01 UTC, LadySolveig commented on plugins/media-action/resize/src/Extension/Resize.php
> +                break;
```suggestion
```

2024-05-11 11:01 UTC, LadySolveig commented on plugins/media-action/resize/src/Extension/Resize.php
> +                break;
My suggestion would be to remove this here and open a new PR to add it as soon as it is also supported by PHP. Otherwise, with the resize plugin active, no avif images can be uploaded at all and there is only the error output in the console.

```
Warning:  imagecreatefromstring(): No AVIF support in this PHP build in 
/var/www/html/plugins/media-action/resize/src/Extension/Resize.php on line 53
{"success":false,"message":"No valid image was loaded.","messages":null,"data":null}
```

2024-05-11 11:13 UTC, dgrammatiko commented on plugins/media-action/resize/src/Extension/Resize.php
> +                break;
What was the php version? Avif is supported from 8.1

2024-05-11 15:44 UTC, LadySolveig commented on plugins/media-action/resize/src/Extension/Resize.php
> +                break;
![grafik](https://github.com/jo
That's weird, webp works well and apart from the resize plugin, avif also works without any problems. But with media resize I get the error from above with avif and upload is broken.

2024-05-11 15:47 UTC, LadySolveig commented on plugins/media-action/resize/src/Extension/Resize.php
> +                break;
Oh wait ... think I found my problem GD library Version 2.3.3 should fit, but seems no avif support enabled.

2024-05-11 17:47 UTC, LadySolveig commented on plugins/media-action/resize/src/Extension/Resize.php
> +                break;
Could we perhaps add something like this
```
        if (strtolower($item->extension) === 'avif' && !\function_exists('imageavif')) {
            // AVIF support not available.
            return;
        }
```
This would at least prevent breaking the upload for avif media if the provider does not yet support Avif and you could still use it for the other formats, as we do not have detailed options per format in the plugin itself.

2024-05-13 15:06 UTC, dgrammatiko commented on plugins/media-action/resize/src/Extension/Resize.php
> +                break;
This makes sense and I pushed the code

2024-05-14 06:52 UTC, merged

2024-05-14 06:52 UTC, bembelimen commented
Thx