[5.2] Cleanup of return types for phpstan
joomla/joomla-cms pull request #43350
Opened 2024-04-24 20:09 UTC by Hackwar

### Summary of Changes
This cleans up a few false return statements.

### Testing Instructions
Codereview

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

2024-04-25 09:59 UTC, HLeithner requested changes

2024-04-25 09:59 UTC, HLeithner commented on administrator/components/com_languages/src/Model/OverridesModel.php
> -     * @return  boolean  result of operation
Thats wrong, in case of an exception

2024-04-25 09:59 UTC, HLeithner commented on administrator/components/com_modules/src/Controller/ModuleController.php
> -     * @return  string  The data for the Ajax request.
we return an empty string in case of an exception.  please be a bit more careful with such changes.

2024-04-25 10:04 UTC, Hackwar commented on administrator/components/com_modules/src/Controller/ModuleController.php
> -     * @return  string  The data for the Ajax request.
The empty string has been removed.

2024-04-29 12:11 UTC, Hackwar commented on administrator/components/com_languages/src/Model/OverridesModel.php
> -     * @return  boolean  result of operation
Changed

2024-05-29 17:24 UTC, richard67 approved these changes

2024-05-29 17:31 UTC, merged