[5.1] Remove unused cassiopeia inline event handler
joomla/joomla-cms pull request #43586
Opened 2024-05-31 20:15 UTC by SniperSister

### Summary of Changes
The current Cassiopeia version has an inline onload event handler for the fontscheme.current css file. The inline event handler produces a warning in strict CSP mode and is redundant, as the lazy-loading functionality (that was the purpose of the handler) is handled in the template.js and trigger by the rel="lazy-stylesheet" attribute.

### Testing Instructions
Configure the "roboto (local)" font as font in cassiopeia, verify that it's loaded by the browser using the browser dev tools.

### Actual result BEFORE applying this Pull Request
* CSS file loaded

### Expected result AFTER applying this Pull Request
* CSS file loaded

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2024-05-31 21:59 UTC, brianteeman commented
Please provide more test instructions and what is expected to be seen in the generated source

Maybe I am looking at this wrong but before this PR I see

`<link href="/media/templates/site/cassiopeia/css/global/fonts-local_roboto.min.css?8eef51" rel="stylesheet" media="all" onload="this.media='all'">`

With the PR applied I see

`<link href="/media/templates/site/cassiopeia/css/global/fonts-local_roboto.min.css?447e02" rel="stylesheet" media="all" onload="this.media='all'">`

2024-05-31 22:07 UTC, brianteeman commented
Also does the same change need to be made in 
`templates\cassiopeia\component.php`
`templates\cassiopeia\error.php`

2024-06-01 05:12 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['media' => 'print', 'rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
```suggestion
        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
```

the media part is not needed anymore and if left will never load the fonts for the normal use ie displaying the site on a screen.

2024-06-01 05:13 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['media' => 'print', 'rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
Also please change the same parts at line 73

2024-06-01 09:07 UTC, dgrammatiko requested changes
@SniperSister please remove all the `'media' => 'print'`

2024-06-01 09:07 UTC, dgrammatiko commented on templates/cassiopeia/component.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['media' => 'print', 'rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
```suggestion
        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
```

2024-06-01 09:07 UTC, dgrammatiko commented on templates/cassiopeia/component.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, ['version' => 'auto'], ['media' => 'print', 'rel' => 'lazy-stylesheet']);
```suggestion
        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, ['version' => 'auto'], ['rel' => 'lazy-stylesheet']);
```

2024-06-01 09:07 UTC, dgrammatiko commented on templates/cassiopeia/error.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['media' => 'print', 'rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
```suggestion
        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
```

2024-06-01 09:07 UTC, dgrammatiko commented on templates/cassiopeia/error.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, ['version' => 'auto'], ['media' => 'print', 'rel' => 'lazy-stylesheet']);
```suggestion
        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, ['version' => 'auto'], ['rel' => 'lazy-stylesheet']);
```

2024-06-01 09:07 UTC, dgrammatiko commented on templates/cassiopeia/index.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, ['version' => 'auto'], ['media' => 'print', 'rel' => 'lazy-stylesheet']);
```suggestion
        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, ['version' => 'auto'], ['rel' => 'lazy-stylesheet']);
```

2024-06-01 09:07 UTC, dgrammatiko commented on templates/cassiopeia/offline.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['media' => 'print', 'rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
```suggestion
        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, [], ['rel' => 'lazy-stylesheet', 'crossorigin' => 'anonymous']);
```

2024-06-01 09:07 UTC, dgrammatiko commented on templates/cassiopeia/offline.php
> +        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, ['version' => 'auto'], ['media' => 'print', 'rel' => 'lazy-stylesheet']);
```suggestion
        $wa->registerAndUseStyle('fontscheme.current', $paramsFontScheme, ['version' => 'auto'], ['rel' => 'lazy-stylesheet']);
```

2024-06-01 09:13 UTC, SniperSister commented
Lesson learned: don't commit while listening to JDay presentations ;) 

Sorry guys, now all required changes (removal of inline handler, removal of unused media attribute) have been performed in all relevant files and locations.

2024-06-01 12:10 UTC, brianteeman commented
As stated before please provide more detailed test instructions. How can a tester replicate the error etc

2024-06-01 12:21 UTC, SniperSister commented
> As stated before please provide more detailed test instructions. How can a tester replicate the error etc

Done!

2024-06-01 13:19 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on f3bbd2d7eb6f814d8effb6327f4db26fbdcfcfe7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43586">issues.joomla.org/tracker/joomla-cms/43586</a>.</sub>

2024-06-02 12:33 UTC, richard67 commented
@SniperSister Shouldn't it be fixed in 4.4-dev, too (or only there and later be merged up to 5.1-dev)? If it's a bug fix we should to it also in 4.4-dev, and if it's a new feature (what I don't think) it should to into 5.2-dev.

2024-06-02 19:40 UTC, dautrich commented
I have tested this item :white_check_mark: successfully on f3bbd2d7eb6f814d8effb6327f4db26fbdcfcfe7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43586">issues.joomla.org/tracker/joomla-cms/43586</a>.</sub>

2024-06-02 19:49 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43586">issues.joomla.org/tracker/joomla-cms/43586</a>.</sub>

2024-06-03 06:24 UTC, SniperSister commented
> Shouldn't it be fixed in 4.4-dev, too (or only there and later be merged up to 5.1-dev)?

@richard67 fair comment. I have rebased the PR as suggested!

2024-06-14 17:52 UTC, merged

2024-06-14 17:52 UTC, MacJoom commented
Thank you!