[5.2][Events] Use event classes for System plugins
joomla/joomla-cms pull request #43637
Opened 2024-06-08 16:45 UTC by Fedik

### Summary of Changes

Update `system` plugins to use `SubscriberInterface` and event classes.

### Testing Instructions

Check following `system` plugins should work as before:
```
accessibility
actionlogs
fields
highlight
jooa11y
```

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/177
- [ ] No documentation changes for manual.joomla.org needed

2024-06-09 12:10 UTC, richard67 commented
@Fedik System tests are failing in Drone when trying to delete a user and waiting for the content "User deleted." appearing in the in the system-message-container div.

2024-09-02 08:51 UTC, HLeithner commented
This pull request has been automatically rebased to 5.3-dev.

2025-02-05 09:52 UTC, joomdonation requested changes
Some changes are needed. Some changes are nice to have

2025-02-05 09:52 UTC, joomdonation commented on plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
> +        $form = $event->getForm();
At the end of this method, there is return true; statement needs to be returned to avoid fatal error.

2025-02-05 09:52 UTC, joomdonation commented on plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
> +    public function onAfterRoute(): void
You forgot to add $event parameter in the method ?

2025-02-05 09:52 UTC, joomdonation commented on plugins/system/remember/src/Extension/Remember.php
>          if (!$this->getApplication()->isClient('site')) {
Shouldn't we get $application directly from $event object here ?

2025-02-05 09:52 UTC, joomdonation commented on plugins/system/skipto/src/Extension/Skipto.php
> +    public function onAfterDispatch(AfterDispatchEvent $event): void
Inside the method, we are using $application object passed from service provider. Better get it directly from $event object and remove the code which pass application from plugin service provider.

2025-02-05 09:56 UTC, joomdonation commented on plugins/system/stats/src/Extension/Stats.php
> +        $event->updateEventResult(json_encode(['sent' => (int) $this->sendStats()]));
Someone understands how this plugin works please review and make sure the change is valid. This is something I'm unsure because I do not get how the data is used yet.

2025-02-05 12:26 UTC, Fedik commented on plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
> +        $form = $event->getForm();
changed

2025-02-05 12:26 UTC, Fedik commented on plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
> +    public function onAfterRoute(): void
added

2025-02-05 12:27 UTC, Fedik commented on plugins/system/remember/src/Extension/Remember.php
>          if (!$this->getApplication()->isClient('site')) {
Other event is this plugin cannot do it, only application event provides an application instance.
I keep it consistent with other events in this plugin.

2025-02-05 12:27 UTC, Fedik commented on plugins/system/skipto/src/Extension/Skipto.php
> +    public function onAfterDispatch(AfterDispatchEvent $event): void
changed

2025-02-05 12:30 UTC, Fedik commented on plugins/system/stats/src/Extension/Stats.php
> +        $event->updateEventResult(json_encode(['sent' => (int) $this->sendStats()]));
That is basicaly set json string to the output, instead of `echo` and `die()`.
The ajax request is in format=raw here.

2025-02-05 14:43 UTC, joomdonation reviewed
Just some other small changes and we should be fine. Thanks !

2025-02-05 14:43 UTC, joomdonation commented on plugins/system/accessibility/src/Extension/Accessibility.php
> +        $direction = $app->getLanguage()->isRtl() ? 'right' : 'left';
Could you introduce local $language variable here, and update the code in this method to use this variable instead? The code from line 89 to 102 repeating uses `$this->getApplication()->getLanguage()`, it should be replaced with $language variable.

After doing that, we can also remove `$plugin->setApplication(Factory::getApplication());` from service provider file of the plugin

2025-02-05 14:43 UTC, joomdonation commented on plugins/system/jooa11y/src/Extension/Jooa11y.php
> +    public function addJooa11y($event)
Shouldn't we add type hinting for $event parameter here?

2025-02-05 14:52 UTC, Fedik commented on plugins/system/accessibility/src/Extension/Accessibility.php
> +        $direction = $app->getLanguage()->isRtl() ? 'right' : 'left';
I keep it as it is, the whole thing need to be updated to use `Text::_()` anyway.

2025-02-05 14:56 UTC, Fedik commented on plugins/system/accessibility/src/Extension/Accessibility.php
> +        $direction = $app->getLanguage()->isRtl() ? 'right' : 'left';
Hm, or maybe not

2025-02-05 15:01 UTC, joomdonation commented on plugins/system/accessibility/src/Extension/Accessibility.php
> +        $direction = $app->getLanguage()->isRtl() ? 'right' : 'left';
At least $this->getApplication() in the mentioned code should be replaced by $app or I do not see something here?

2025-02-05 15:02 UTC, Fedik commented on plugins/system/accessibility/src/Extension/Accessibility.php
> +        $direction = $app->getLanguage()->isRtl() ? 'right' : 'left';
well, yea, I will ignore it here, that language things is annoying, I don't want to deal with it here.
I will let someone else to figure out it later.

2025-02-05 15:02 UTC, Fedik commented on plugins/system/jooa11y/src/Extension/Jooa11y.php
> +    public function addJooa11y($event)
changed

2025-02-05 15:04 UTC, Fedik commented on plugins/system/accessibility/src/Extension/Accessibility.php
> +        $direction = $app->getLanguage()->isRtl() ? 'right' : 'left';
> At least $this->getApplication() in the mentioned code should be replaced by $app

changed

2025-02-05 15:06 UTC, joomdonation commented
Thanks, all good now from my code review and basic test.

2025-02-05 16:03 UTC, merged