[5.1] Add update channel reset to Joomla Update Component
joomla/joomla-cms pull request #43717
Opened 2024-06-28 10:46 UTC by richard67

Pull Request for Issue #43591 .

Alternative to PR #43695 .

### Summary of Changes

This pull request (PR) adds a function to the Joomla Update Component to automatically reset the update source (update channel) to "Default" in the component's options at the end of each CMS core update when it was set to "Joomla Next" before the update.

It is equal to part 1 of PR #43695 and can be used instead of that PR when it turns out (needs to be tested by maintainers) that the update to the upcoming 5.1.2 can be offered on the "Default" source (channel "5.x" for TUF) as well as (with a different zip file name) on the "Joomla Next" source (channel "6.x" for TUF) so that it does not need a separate extra update of the Joomla Update Component to reset the update source in order to find the core update after that, which was part 2 of the other PR.

The reset after each update provided with part 1 of the other PR or with this PR here makes still sense, except if we want to provide updates on both channels in parallel also in the future and not only this one time to fix the issue.

Find more details in the description of the other PR #43695 .

### Testing Instructions

Update the CMS core by uploading in the Joomla Update Component the patched zip package created by Drone for this PR.

You can download that package here: __Link will be added soon__

Do several tests with different starting conditions regarding the update source set in the Joomla Update Component's options:
- Test with update source = "Joomla Next" before the update.
- Test with any other update source, i.e. "Default" or "Custom URL".

When using "Custom URL" you can use the custom URL created by Drone for this PR instead of uploading the package. You can find that custom URL at the same place where you could find the patched package.

In addition, do the same different tests using the following patched package for upload: __Link will be added soon__

The patched package provokes a database error for checking what happens when the reset of the update source fails. It can also be used to check that the reset does not take place when the update source is not "Joomla Next" before the update.

It does not need to fall back to the same starting conditions after each test, you can just upload the package again in the update component. But you should use a new browser session after each test.

### Actual result BEFORE applying this Pull Request

When you are still on the "Joomla Next" update channel after an update from 4.4 to 5.1, there will not be any update found for the CMS core until 6.0.0-alpha1 will be released, and then only updates to 6.0 releases will be found, so you will miss any further updates for 5.1 until that time has come.

There is no notification about that and no automatic reset after the update.

### Expected result AFTER applying this Pull Request

When having the update source (update channel) set to "Joomla Next" in the Joomla Update Component's options before that update, the update source is rest to "Default" at the end of the update, and a success message is shown about that:
![test-core-update-reset-ok](https://github.com/joomla/joomla-cms/assets/7413183/f1849213-4b6e-4e7f-8b7d-2539be9b7c8b)

When under the same conditions an error happens with that reset, e.g. due to a database problem, the usual error layout is shown with all details, and in addition a warning message is shown at the top, telling the user to manually reset the update source:
![test-core-update-reset-error](https://github.com/joomla/joomla-cms/assets/7413183/452f0bbf-bba4-46a1-9fe4-0d6bc89d7782)

In this case the Joomla Update log `administrator/logs/joomla_update.php` contains details like for other errors:
```
2024-06-22T16:44:16+00:00	INFO 192.168.98.1	update	Test logging
2024-06-22T16:44:16+00:00	INFO 192.168.98.1	update	Uploading update file
2024-06-22T16:44:18+00:00	INFO 192.168.98.1	update	File [ROOT][TMP]/juRNnKH5 downloaded.
2024-06-22T16:44:18+00:00	INFO 192.168.98.1	update	Starting installation of new version.
2024-06-22T16:44:25+00:00	INFO 192.168.98.1	update	Finalising installation.
2024-06-22T16:44:26+00:00	INFO 192.168.98.1	update	Start of SQL updates.
2024-06-22T16:44:26+00:00	INFO 192.168.98.1	update	The current database version (schema) is 5.1.1-2024-04-18.
2024-06-22T16:44:26+00:00	INFO 192.168.98.1	update	End of SQL updates.
2024-06-22T16:44:26+00:00	INFO 192.168.98.1	update	Uninstalling extensions
2024-06-22T16:44:26+00:00	INFO 192.168.98.1	update	Deleting removed files and folders.
2024-06-22T16:44:26+00:00	ERROR 192.168.98.1	update	An error has occurred while running "resetUpdateSource". Code: 1054. Message: Unknown column 'paramsx' in 'field list'.
2024-06-22T16:44:26+00:00	INFO 192.168.98.1	update	Cleaning up after installation.
2024-06-22T16:44:26+00:00	INFO 192.168.98.1	update	Update to version 5.1.2-dev is complete.
```

When the update source is not "Joomla Next" so it is "Default" or "Custom URL", the update source is not changed, and the update of the CMS core works as it does without this PR:
![test-core-update-no-reset](https://github.com/joomla/joomla-cms/assets/7413183/b20b2aa6-1b41-443d-8a76-3b79c269cd1e)

### Link to documentations
Please select:
- [X] No documentation changes for docs.joomla.org needed

- [X] No documentation changes for manual.joomla.org needed

2024-06-28 15:58 UTC, brianteeman commented
If we can offer the updates in the same way as before then do we really need to even update the update component?

2024-06-28 16:02 UTC, richard67 commented
> If we can offer the updates in the same way as before then do we really need to even update the update component?

@brianteeman Like I wrote in the description:

> The reset after each update provided with part 1 of the other PR or with this PR here makes still sense, except if we want to provide updates on both channels in parallel also in the future and not only this one time to fix the issue.

2024-06-28 16:08 UTC, brianteeman commented
> The reset after each update provided with part 1 of the other PR or with this PR here makes still sense, except if we want to provide updates on both channels in parallel also in the future and not only this one time to fix the issue.

that doesnt answer my question. never mind. i obviously speak a different language to everyone else and cannot express myself

2024-06-28 16:12 UTC, richard67 commented
@brianteeman It does answer your question. When updates will always be provided on both channels then this PR is not necessary. But I doubt that will be the case, I think it will be only done this time. Anyway that’s not my decision.

2024-06-28 16:13 UTC, richard67 commented
P.S. And as described, this PR here doesn’t include the part from the other PR which requires the extra component update.

2024-06-28 16:16 UTC, brianteeman commented
> @brianteeman It does answer your question. When updates will always be provided on both channels then this PR is not necessary. But I doubt that will be the case, I think it will be only done this time. Anyway that’s not my decision.

Why not - it has been that way for ages and if it has now been established that it can be done that way again why change. I just dont see the reason for the change.

I am on holiday now so cant check but what happens when you update from the cli

2024-06-28 16:20 UTC, richard67 commented
@brianteeman Sorry, you were right, I misunderstood your question first.

> Why not - it has been that way for ages and if it has now been established that it can be done that way again why change. I just dont see the reason for the change.

Yes, that would be the best. But it might require some additional work for those who deploy the updates to TUF - I am not involved in that so I don’t know if that is the way to go.

> I am on holiday now so cant check but what happens when you update from the cli

I haven’t checked that either so it would be good if someone could check.

2024-06-30 08:35 UTC, brianteeman commented
I am having some issues testing this but so far I have observed that the error page is 
`administrator/index.php?option=com_joomlaupdate&view=joomlaupdate&layout=complete&tmpl=component`

This produces a "naked" page
![image](https://github.com/joomla/joomla-cms/assets/1296369/7de1529c-c601-45f2-9308-90f68318e96e)

Should the error page url not be
`administrator/index.php?option=com_joomlaupdate&view=joomlaupdate&layout=complete`

So that you get a fully styled page
![image](https://github.com/joomla/joomla-cms/assets/1296369/a271aaeb-a755-4a20-acb3-16a21b0f5784)

2024-06-30 09:06 UTC, richard67 commented
@brianteeman That in case of error the component layout is used is nothing new from my PR. It was once introduced by Fedir when he improved error reporting and logging of the update component.

2024-07-02 12:06 UTC, HLeithner commented
to test the update with the update server please change the 115 line in
administrator/components/com_joomlaupdate/src/Model/UpdateModel.php  
from
$updateURL = 'https://update.joomla.org/cms/'; 
to
$updateURL = 'https://update.joomla.org/alpha/'; 

then change the channel in the update component options form stable to next

(with stable and next channel) you should get version 5.1.2 stable offered for version 5.1.0 and 5.1.1

this might only work today till the original update server does an timestamp update and the updater might refuse an outdated / different update information depending on the status of the data cached.

2024-07-02 12:07 UTC, HLeithner commented
I have tested this item :white_check_mark: successfully on 45e1091c3bf47375c63a410c38f6d0b5398d502d<br /><br />works with tuf alpha update from 5.1.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43717">issues.joomla.org/tracker/joomla-cms/43717</a>.</sub>

2024-07-02 12:28 UTC, brianteeman commented
I have tested this item :red_circle: unsuccessfully on 45e1091c3bf47375c63a410c38f6d0b5398d502d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43717">issues.joomla.org/tracker/joomla-cms/43717</a>.</sub>

2024-07-02 12:30 UTC, brianteeman commented
I set the channel to Next
I edited the file as per @HLeithner instructions
I performed the update.

![image](https://github.com/joomla/joomla-cms/assets/1296369/e410bcb3-01ac-4de8-8412-09f596878abe)

2024-07-02 12:32 UTC, HLeithner commented
which version was the installed one?

2024-07-02 12:34 UTC, brianteeman commented
> which version was the installed one?

```
2024-07-02T12:27:13+00:00	INFO 127.0.0.1	update	Test logging
2024-07-02T12:27:13+00:00	INFO 127.0.0.1	update	Update started by user admin (132). Old version is 5.1.2-dev+pr.43717.
2024-07-02T12:27:15+00:00	INFO 127.0.0.1	update	Downloading update file from https://artifacts.joomla.org/drone/joomla/joomla-cms/5.1-dev/43717/downloads/76941/Joomla_5.1.2-dev+pr.43717-Development-Update_Package.zip.
2024-07-02T12:27:21+00:00	INFO 127.0.0.1	update	File Joomla_5.1.2-dev+pr.43717-Development-Update_Package.zip downloaded.
2024-07-02T12:27:21+00:00	INFO 127.0.0.1	update	Starting installation of new version.
2024-07-02T12:27:39+00:00	INFO 127.0.0.1	update	Finalising installation.
2024-07-02T12:27:39+00:00	INFO 127.0.0.1	update	Start of SQL updates.
2024-07-02T12:27:39+00:00	INFO 127.0.0.1	update	The current database version (schema) is 5.1.1-2024-04-18.
2024-07-02T12:27:39+00:00	INFO 127.0.0.1	update	End of SQL updates.
2024-07-02T12:27:39+00:00	INFO 127.0.0.1	update	Uninstalling extensions
2024-07-02T12:27:39+00:00	INFO 127.0.0.1	update	Deleting removed files and folders.
2024-07-02T12:27:40+00:00	INFO 127.0.0.1	update	Cleaning up after installation.
2024-07-02T12:27:40+00:00	INFO 127.0.0.1	update	Update to version 5.1.2-dev+pr.43717 is complete.
```

2024-07-02 12:35 UTC, HLeithner commented
strange are you sure this wasn't an error message form before?

2024-07-02 12:37 UTC, brianteeman commented
I do however ask again that as you have demonstrated that the Joomla Next channel can show the next joomla 5 release why do we need to have this PR to change to the Stable channel AND if production insists that this change must be done then it is incomplete as the language string below will now give incorrect information

COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (5.x) and you will also be notified when the future major release (6.x) will be available. Before upgrading to 6.x you'll need to assess its compatibility with your environment."

2024-07-02 12:38 UTC, brianteeman commented
> strange are you sure this wasn't an error message form before?

I am sure that the joomla update component was not displaying any error messages before I did the update

2024-07-02 12:41 UTC, richard67 commented
@brianteeman According to Harald’s instructions you fist have to change the URL in the PHP file and then change the channel from Default to Next. You have done it in the opposite order.

2024-07-02 12:43 UTC, brianteeman commented
https://github.com/joomla/joomla-cms/assets/1296369/8700ae6e-cb27-434a-8cd0-d6ae8f84ae07

2024-07-02 12:44 UTC, brianteeman commented
> @brianteeman According to Harald’s instructions you fist have to change the URL in the PHP file and then change the channel from Default to Next. You have done it in the opposite order.

i cant see how that can have any impact at all

2024-07-02 12:46 UTC, HLeithner commented
ah ok that's expected and is a warning provided by tuf, after the update it checks the "main" update server which only provides an older version and it doesn't allow a downdate.

2024-07-02 12:50 UTC, brianteeman commented
> > I am on holiday now so cant check but what happens when you update from the cli
> 
> I haven’t checked that either so it would be good if someone could check.

the channel is not changed from next to default when the cli is used to update


https://github.com/joomla/joomla-cms/assets/1296369/04cdc606-265f-4fc9-9331-2de8d89cf78d

2024-07-02 12:56 UTC, richard67 commented
Yes, for the CLI it needs to add that, too. But I can’t do that before weekend.

2024-07-02 12:56 UTC, brianteeman commented
The update logs show that the final two steps of the update are not completed when using the cli

```
2024-07-02T12:42:31+00:00	INFO 127.0.0.1	update	The current database version (schema) is 5.1.1-2024-04-18.
2024-07-02T12:42:31+00:00	INFO 127.0.0.1	update	End of SQL updates.
2024-07-02T12:42:31+00:00	INFO 127.0.0.1	update	Uninstalling extensions
2024-07-02T12:42:31+00:00	INFO 127.0.0.1	update	Deleting removed files and folders.
2024-07-02T12:42:31+00:00	INFO 127.0.0.1	update	Cleaning up after installation.
2024-07-02T12:42:31+00:00	INFO 127.0.0.1	update	Update to version 5.1.2-dev+pr.43717 is complete.
```

CLI
```
2024-07-02T12:48:50+00:00	INFO -	update	The current database version (schema) is 5.1.1-2024-04-18.
2024-07-02T12:48:50+00:00	INFO -	update	End of SQL updates.
2024-07-02T12:48:50+00:00	INFO -	update	Uninstalling extensions
2024-07-02T12:48:50+00:00	INFO -	update	Deleting removed files and folders.
```

2024-07-02 12:57 UTC, brianteeman commented
> Yes, for the CLI it needs to add that, too. But I can’t do that before weekend.

i still do not see why any of this is needed

2024-07-02 13:09 UTC, HLeithner commented
> > Yes, for the CLI it needs to add that, too. But I can’t do that before weekend.
> 
> i still do not see why any of this is needed

because it makes no sense, if you update from 4.4 to 5.4 it needs to be a decision by you that you want to update to 6.0 and doesn't do this by accident. Also thinking of the future with auto updates this is something we have to consider if we like to automatically update 6.4 to 7.0 oder keep it at 6.4 series till it's eol or the user manually switch to next.

2024-07-02 13:12 UTC, richard67 commented
> i still do not see why any of this is needed

Well that’s a matter of the deployment process for TUF updates, how complicated it is to deploy the same update for both channels not only this one time but also in future. I am not familiar with that process. Maybe @HLeithner can answer that.

2024-07-02 13:16 UTC, brianteeman commented
> because it makes no sense, if you update from 4.4 to 5.4 it needs to be a decision by you that you want to update to 6.0 and doesn't do this by accident.

If it makes no sense then why has it always been this way?

2024-07-02 13:18 UTC, brianteeman commented
But if you insist that its wrong and that the arbitrary change that was made without a PR or open discussion is correct then this PR only partially fixes the consequences of that change. This is why we have pull requests so that changes can be properly reviewed and not made silently in this way

2024-07-02 13:22 UTC, HLeithner commented
> > because it makes no sense, if you update from 4.4 to 5.4 it needs to be a decision by you that you want to update to 6.0 and doesn't do this by accident.
> 
> If it makes no sense then why has it always been this way?

Don't know wasn't here at the time of introduction.

2024-07-02 13:26 UTC, HLeithner commented
> But if you insist that its wrong and that the arbitrary change that was made without a PR or open discussion is correct then this PR only partially fixes the consequences of that change. This is why we have pull requests so that changes can be properly reviewed and not made silently in this way

Our Tuf implementation can't handle 2 channels at this time (channel needs to be a regex for example).

2024-07-02 13:51 UTC, brianteeman commented
So because of a limitation in the implementation of TUF we have a breaking change that was made without **discussion** or **documentation** and was **not** complete. Seems its one rule for some people's pull requests and something completely different for others. Clearly there are two tiers of contributors. Those how do what they want and those who have to jump through hoops to fix a bug. I have noted that and won't waste my time any further

2024-07-02 14:10 UTC, HLeithner commented
stop blaming me thanks wasn't my fault or decision, I'm just finding a work around.

2024-07-02 15:28 UTC, LadySolveig commented
As I understand it, the "Next" update channel should primarily be a security mechanism to prevent accidental updates to the next major version.
All the time we had an "opt-out", so the user was responsible for remembering to reset the channel manually after the major update. 
Otherwise, the additional security of the "Next" update channel would no longer apply in future anyway.

Regardless of whether it can now be implemented with TUF or not - does the "Next" channel even make sense in this scenario?
What am I missing here?
If I have understood you correctly, you would like to stay with the opt-out @brianteeman

In the long run, and considering that TUF was supposed to pave the way for secure automatic updates, this could actually lead to unwanted major updates at some point.

Maybe I just can't see the disadvantage of switching between opt-in and the previous opt-out.
Would you like to briefly explain what disadvantage you see?

2024-07-02 17:17 UTC, brianteeman commented
> stop blaming me thanks wasn't my fault or decision, I'm just finding a work around.

at no point have i said it was you or your decision. My entire point is that we should not need this "work around"

2024-07-02 17:31 UTC, alikon commented
for what it worths, the TUF has been merged , too much "_fast and happily_", despite the warnings from some, in the other hand it is a good improvment, so let's fix it,  and do a step in the future

2024-07-02 17:48 UTC, brianteeman commented
> for what it worths, the TUF has been merged , too much "_fast and happily_", despite the warnings from some, in the other hand it is a good improvment, so let's fix it, and do a step in the future

cant fix what we dont know

2024-07-06 09:16 UTC, richard67 commented
I've just added the update source reset for the CLI update and will provide testing instructions and screenshots with expected results soon.

However, I think about making a further change.

Currently both the "normal" update as well as the CLI update use the `collectError` method of the update model when some database error happens so the update source reset fails to make sure that the reason for the error is logged in the log file and later shown with the result. The result then says the update has finished with errors and one should check the log file.

But when that was the only error, the update did not really fail. So the user could be confused and think his site is broken when it not really is.

So maybe I should change that to not using the `collectError` method so the user can see the update was successful, and only the warning message is shown in that case which tells what to do, and maybe I find a way to log a warning with details in the log file.

2024-07-06 13:12 UTC, richard67 commented
I will provide an update later. Changing to draft meanwhile.

2024-07-06 16:02 UTC, richard67 commented
Ready for testing again.

2024-07-06 16:09 UTC, brianteeman commented
Without an additional change to COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT this PR is incomplete

2024-07-06 16:32 UTC, richard67 commented
> Without an additional change to COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT this PR is incomplete

@brianteeman Done. Wrong information removed from the language string.

2024-07-06 16:38 UTC, richard67 commented
Hmm, in the backend the warning which is shown when the reset fails has the right colour, but it maybe has the wrong icon (check mark).

@brianteeman Should it be something else? Do you know which one?

2024-07-06 18:22 UTC, tecpromotion commented on administrator/language/en-GB/com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_UPDATE_CHANGE_UPDATE_SOURCE_FAILED="Failed to reset the update channel from \"%1$s\" to \"%2$s\". Please change it in the Joomla Update Component's options so you don't miss future u
```suggestion
COM_JOOMLAUPDATE_UPDATE_CHANGE_UPDATE_SOURCE_FAILED="Failed to reset the update channel from \"%1$s\" to \"%2$s\". Please change this in the options of the Joomla update component so that you do not miss future updates."
```

2024-07-06 18:23 UTC, tecpromotion requested changes
That sounded very clumsy.
@brianteeman can you please take another look at it.Thank you.

2024-07-07 09:34 UTC, richard67 commented
@brianteeman Could you check @tecpromotion 's suggested change on the language string? Would be good to have a native speaker instead of 2 Germans 😄

2024-07-07 09:38 UTC, richard67 commented on administrator/language/en-GB/com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_UPDATE_CHANGE_UPDATE_SOURCE_FAILED="Failed to reset the update channel from \"%1$s\" to \"%2$s\". Please change it in the Joomla Update Component's options so you don't miss future u
Hoping for a native speaker to have a look on it. Maybe that sentence can be improved further.

2024-07-07 10:03 UTC, brianteeman commented on administrator/language/en-GB/com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_UPDATE_CHANGE_UPDATE_SOURCE_FAILED="Failed to reset the update channel from \"%1$s\" to \"%2$s\". Please change it in the Joomla Update Component's options so you don't miss future u
The original is fine by me.
The suggestion is also fine

2024-07-07 10:07 UTC, brianteeman commented
> @brianteeman Could you check @tecpromotion 's suggested change on the language string? Would be good to have a native speaker instead of 2 Germans 😄

done

2024-07-07 10:07 UTC, richard67 commented
Thanks

2024-07-07 10:09 UTC, brianteeman commented
The more I look at this the more I see it as the wrong thing to do.

2024-07-07 10:14 UTC, brianteeman commented on administrator/language/en-GB/com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you will be notified when the future major release (6.x) will be available. Before
The more I look at this PR the more I am against this changed behaviour. This language string is a perfect example of that as it also needs to say that you will NOT receive any further update notifications for joomla 5.x.

2024-07-07 10:27 UTC, richard67 commented
> The more I look at this the more I see it as the wrong thing to do.

@brianteeman I understand your point.

To all readers: Personally I would also prefer if things could work like in past before the change to TUF so it would not need this PR at all.

I was asked by other maintainers if I can make a pull request like this one now, and that's what I did. But I'm not the one to decide which was it should go.

2024-07-07 10:31 UTC, richard67 commented on administrator/language/en-GB/com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you will be notified when the future major release (6.x) will be available. Before
I understand your point, see my other new comment in the main thread. In the mean time I can add to this language string the information that one will NOT receive any further update notifications for Joomla 5.x.

2024-07-07 10:55 UTC, richard67 commented on administrator/language/en-GB/com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you will be notified when the future major release (6.x) will be available. Before
I've added a sentence to that string. See updated screenshot in the test instruction results.

2024-07-07 10:56 UTC, richard67 commented on administrator/language/en-GB/com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_UPDATE_CHANGE_UPDATE_SOURCE_FAILED="Failed to reset the update channel from \"%1$s\" to \"%2$s\". Please change it in the Joomla Update Component's options so you don't miss future u
Well, let release managers decide. They can apply the suggested change with a click on a button.

2024-07-07 15:49 UTC, brianteeman commented
> > The more I look at this the more I see it as the wrong thing to do.
> 
> @brianteeman I understand your point.
> 
> To all readers: Personally I would also prefer if things could work like in past before the change to TUF so it would not need this PR at all.
> 
> I was asked by other maintainers if I can make a pull request like this one now, and that's what I did. But I'm not the one to decide which way it should go.

Surprised the maintainers didnt also ask the people who forced these changes to also look at fixing it.

2024-07-07 18:36 UTC, richard67 commented
> Surprised the maintainers didnt also ask the people who forced these changes to also look at fixing it.

@brianteeman Sometimes people are busy with private life or job and don't have enough time when needed, so I stepped in to help.

2024-07-07 19:10 UTC, brianteeman commented
I need to write more clearly. 

This is a major issue that has a serious impact. There is no urgent need to make a release so better to spend the time to make the correct fix than settle on something we both agree is not an ideal solution.

2024-07-07 21:43 UTC, LadySolveig commented
Thank you @richard67 for your work!
For me, additional security through the Next Channel only makes sense if it is a conscious decision that I make as a user before the update and not months before and possibly forgotten again by the next major update. This PR ensures that no permanent workaround of the TUF updates is necessary and provides additional security for the end user.
Improvements are always welcome if they still need to be made.

2024-07-07 21:45 UTC, merged

2024-07-07 21:48 UTC, LadySolveig commented
Thank you @richard67 and also for suggestions, review and testing to all involved!

2024-07-08 05:07 UTC, brianteeman commented
I have no idea at all what you are referring to when you say security

2024-07-08 09:57 UTC, brianteeman commented
Why was this merged without a single successful test

![image](https://github.com/joomla/joomla-cms/assets/1296369/83549462-1db0-4af4-b21e-db587a372722)