Articles Module
joomla/joomla-cms pull request #43738
Opened 2024-07-03 12:24 UTC by drmenzelit

Pull Request for Issue #43404  .

### Summary of Changes
This PR is a follow-up of #43610 that was closed some days ago.

I did several changes to the code, added some parameters (for layout) and functions (include specific articles by ID) and created a CSS file to control the layout. After this get merged additional changes in the CSS from Cassiopeia can be done.

### Testing Instructions

I you don't directly install the PR package, you will need to run npm (npm run build:css) to get the CSS file.

With this module you can replace the existing mod_articles_xx. All you need is to play with the parameters.

Articles - Archived -> Filter Archived Articles only
Articles - Category -> Select category, play with parameter, use filter, group them, etc.
Articles - Latest -> Change ordering to newest first
Articles - Most Read -> Change ordering to hits
Articles - Newsflash -> Select category, play with parameter, use filter, group them, etc.

### Expected result AFTER applying this Pull Request

![Screenshot 2024-07-03 at 12-13-02 Typography](https://github.com/joomla/joomla-cms/assets/9153168/81435c0b-10a5-4a0b-a6a2-26866edca42d)

![Screenshot 2024-07-03 at 12-13-22 Home](https://github.com/joomla/joomla-cms/assets/9153168/15fb95e6-e88e-479c-a134-c0862d38c142)

![Screenshot 2024-07-03 at 12-14-06 Home](https://github.com/joomla/joomla-cms/assets/9153168/2e7adc77-bdb9-4a7b-8916-702c8b9552ba)

![Screenshot 2024-07-03 at 13-37-26 Typography](https://github.com/joomla/joomla-cms/assets/9153168/d8dfdecb-1bc1-48b8-a48f-52ec28890c4e)

![Screenshot 2024-07-03 at 12-11-24 Joomla](https://github.com/joomla/joomla-cms/assets/9153168/3793e7f2-3d22-4a5a-8b40-fdfca2e89f4a)

![Screenshot 2024-07-03 at 12-12-04 Joomla](https://github.com/joomla/joomla-cms/assets/9153168/87e02f3d-258d-4e5f-9be4-181045207179)

![Screenshot 2024-07-03 at 12-12-31 Typography](https://github.com/joomla/joomla-cms/assets/9153168/ccddbca1-c35e-438a-8bbf-f568c82de29a)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2024-07-03 13:16 UTC, brianteeman commented on language/en-GB/mod_articles.ini
> +MOD_ARTICLES_FIELD_LINKCARD_DESC="The whole article will be clickable"
Please use select not click. You cannot click with a touch or voice interface

2024-07-03 13:16 UTC, brianteeman commented on language/en-GB/mod_articles.ini
> +MOD_ARTICLES_FIELD_INFOLAYOUT_DESC="Layout for the Articles Info (Date, Hits, Category, Author)"
please review _DESC strings so that they follow the styleguide and are complete sentences ending with a period.

2024-07-03 13:17 UTC, brianteeman commented on modules/mod_articles/mod_articles.xml
> +	<copyright>(C) 2010 Open Source Matters, Inc.</copyright>
```suggestion
	<copyright>(C) 2024 Open Source Matters, Inc.</copyright>
```

2024-07-03 13:18 UTC, brianteeman commented on modules/mod_articles/mod_articles.xml
> +	<version>5.0.0</version>
```suggestion
	<version>5.2.0</version>
```

2024-07-03 13:19 UTC, brianteeman commented on modules/mod_articles/mod_articles.xml
> +					default="1"
please follow styleguide and order name., type, label, description

2024-07-03 13:20 UTC, drmenzelit commented on language/en-GB/mod_articles.ini
> +MOD_ARTICLES_FIELD_LINKCARD_DESC="The whole article will be clickable"
Selectable sounds weird .. maybe "The whole article will be linked." ?

2024-07-03 13:50 UTC, brianteeman commented
Layout horizontal only works in some module positions. Is this intentional? Took me a while to work out why i couldnt get the columns to work

2024-07-03 13:56 UTC, drmenzelit commented
> Layout horizontal only works in some module positions. Is this intentional? Took me a while to work out why i couldnt get the columns to work

No, no intentional at all... But the number of columns is related to the width of the container (maybe something for the description of the field). For example you can set 3 columns and in main-bottom you will get 2, because the container is smaller than 992px

2024-07-03 14:24 UTC, brianteeman commented
The label "card style" confused me - I thought it referred to placing a border around the article. Not that it made the entire article a link,

When Card style is enable you should not be able to make the category a link as it will never work.

Same is true for the tags

2024-07-03 14:26 UTC, brianteeman commented
Articles Info Layout

I think it makes more sense to describe this as single line and multiline as opposed to horizontal and vertical

2024-07-03 14:31 UTC, drmenzelit commented
> I think it makes more sense to describe this as single line and multiline as opposed to horizontal and vertical

Good idea! Thank you

2024-07-03 14:34 UTC, brianteeman commented
No matter what options you chose it is always output as a list. When you just have the article titles that makes sense but I dont believe it is correct to display articles with content in this way and it should be a div. We dont display a content blog view as a list

2024-07-03 14:36 UTC, drmenzelit commented
> The label "card style" confused me - I thought it referred to placing a border around the article. Not that it made the entire article a link,

I understand card style as a combination of the two things. I was not sure, if it is good to put so much css on the module itself and better do it in Cassiopeia (as is now in the case of mod_articles_newsflash).
> 
> When Card style is enable you should not be able to make the category a link as it will never work.
> 
> Same is true for the tags

That is true ... Maybe it will be better to remove the possibility to display category and tags if card style is selected ... It is always difficult to get all ideas working well (and I have a lot of other ideas ;-) )

2024-07-03 14:38 UTC, drmenzelit commented
> No matter what options you chose it is always output as a list. When you just have the article titles that makes sense but I dont believe it is correct to display articles with content in this way and it should be a div. We dont display a content blog view as a list

I was following a tutorial for accessible cards: https://gehirngerecht.digital/barrierefreie-cards-erstellen-schritt-fuer-schritt-anleitung/
They write: "A list is an advantage for screen readers because, among other things, it tells them how many elements to expect. "

2024-07-03 15:40 UTC, brianteeman commented
> They write: "A list is an advantage for screen readers because, among other things, it tells them how many elements to expect.

That's true but it would also be true for all the blog article views. For me it is an abuse of the list semantics

2024-07-03 16:09 UTC, brianteeman commented
Show Introtext
![image](https://github.com/joomla/joomla-cms/assets/1296369/8893c135-7917-4835-9679-79d2fa846602)

I suggest making this default to Show. Otherwise it is very confusing when you change Titles Only to No and you still dont see the introtext
![image](https://github.com/joomla/joomla-cms/assets/1296369/7de64746-bb36-4465-8d30-a56ad0e3f5a0)

2024-07-03 16:15 UTC, brianteeman commented
Articles Info Layout showon syntax is not correct 

`showon="title_only:0[AND]show_date:1[OR]show_category:1[OR]show_hits:1[OR]show_author:1"`

It should not be displayed when title only = 1

![image](https://github.com/joomla/joomla-cms/assets/1296369/2991b555-64a2-4bef-a1c2-b358ae4b6d59)

2024-07-05 19:05 UTC, chmst commented
I suggest some descriptions for paramsThere are params 

"..... filtering type" with selection inclusive / exclusive. 

This is not self explaining, I have to check the code for unterstanding. Maybe due to language gap?

2024-07-05 21:48 UTC, brianteeman commented
> When we started with J4, we had the rule that labels on switches should be only yes/no or show/hide. There were only a few rare exceptions, for example the user state. In this module we have more exceptions. Woudn't it be better to make a selection dropdown if alternatives are other that yes/no or show/hide?

agreed

2024-07-06 09:02 UTC, drmenzelit commented
> When we started with J4, we had the rule that labels on switches should be only yes/no or show/hide.

Oh, I didn't know (or I forgot it). I will change to select lists.

2024-07-06 09:29 UTC, chmst commented
> Oh, I didn't know (or I forgot it).

Never mind. There was no document or written rule, only discussions. Because with switches the user cannot see the possible options.
We could add this as "best practice rule" to the manual.

2024-07-07 11:17 UTC, brianteeman commented on language/en-GB/mod_articles.ini
> +MOD_ARTICLES_FIELD_SHOWCHILDCATEGORYARTICLES_DESC="Include or exclude artucles in the child cetegories of the selected ones."
```suggestion
MOD_ARTICLES_FIELD_SHOWCHILDCATEGORYARTICLES_DESC="Include or exclude articles in the child categories of the selected ones."
```

spelling corrections

2024-07-07 11:19 UTC, brianteeman commented
The article info data should be presented using the description element just as it is in the content component and not as a regular list element

2024-07-07 11:28 UTC, drmenzelit commented
> The article info data should be presented using the description element just as it is in the content component and not as a regular list element

A description list needs <dt> and <dd> and at the moment we are only displaying the descripton but not the term. 

- Option 1: always display the term
- Option 2: always make the term "visually hidden"
- Option 3: add a parameter show / hide term

2024-07-07 11:57 UTC, brianteeman commented
well it should be the same as with an article

2024-07-07 17:32 UTC, chmst commented
I like the choice linline / vertical for the info-data elements - and would like to have this also for articles. 

Could we make that like in my PR, https://github.com/joomla/joomla-cms/pull/43729
with a visually hidden <dl><dt> label AND the inline / vertical display for <dd>?

2024-07-22 21:47 UTC, Hackwar commented
Can you help me get up to speed? I don't yet know the status of this PR. What still needs to be done? What is missing? Where do you need help?

Looking at this right now, I would like to have this in the testing sampledata and if this is supposed to be the future, then we should directly replace all cases of the old modules in our sampledata plugins with this new plugin and ideally you shouldn't see the difference...

2024-07-22 21:49 UTC, brianteeman commented
> Can you help me get up to speed? I don't yet know the status of this PR. What still needs to be done? What is missing? Where do you need help?
> 
> Looking at this right now, I would like to have this in the testing sampledata and if this is supposed to be the future, then we should directly replace all cases of the old modules in our sampledata plugins with this new plugin and ideally you shouldn't see the difference...

this is supposed to exist in parallel with the other content modules - otherwise we are in migration hell

2024-07-22 21:55 UTC, Hackwar commented
We've had these modules for at least 10 years, most likely even since Mambo times, so of course we wont be dropping them like hot potatoes. I don't see them being replaced anytime soon, so at least until the end of 8.x I would expect the old ones to be safe. However, that still doesn't mean that we shouldn't be encouraging people to use the new module instead of the old ones. If the new module is only supposed to be used in parallel with the old ones, but feature-wise is identical, then we don't need this module. We think that this new module should be the future for com_content modules, so we should advertise it in our core product by using it as a direct replacement for the old ones in our sampledata.

2024-07-22 22:34 UTC, brianteeman commented
its easy to update the sample data - shouldnt take more than a few minutes

2024-08-08 09:35 UTC, drmenzelit commented
I have modified the Blog Sample Data to display the new module instead of the old ones. The Testing Sample Data need a complete restructuring and I'm not sure if I'm able to do that.

2024-08-08 16:14 UTC, HDInfautre commented
Hello
about installing a PR
I installed this PR with the 2nd method by downloading https://artifacts.joomla.org/drone/j...te_Package.zip then doing the manual update which asks me to identify myself on the site.
I had already tried by copying the update url and putting development version without success
So I easily went from the test version joomla 5.2alpha3 to this version joomla 5.2alpha3+PR new module
It's easier than going through the component whose options I got lost in by using it once a year.

For the future, I have 2 questions,
a) when I install another more recent version, if this pr is not included, what I did will be overwritten?
b) if I put another joomla 5.2x + PR, it will not overwrite and a priori should not interfere?

About the module
Good to know you must set display options correctly" otherwise there is no display
I appreciate
* the presentation on the same line. I imagine that after the templates including astroid will be able to create a nice layout :-)
* the fact of clicking on a block

Afterwards I have 2 questions
c) it seems that the images are not rendered! yet I put 2 nice images in the content of the text.
Well it is less important for me because I systematically use the Tassos custom field images which will probably never be taken natively in this module
d) I have not seen any repercussions of modifying the parameter: "Articles Info Layout​"

Sorry if my bad English is poorly translated.

2024-08-08 16:31 UTC, drmenzelit commented
@HDInfautre sorry I don't understand your problems / questions about the installation ...

Article Info Layout = Multiline
![grafik](https://github.com/user-attachments/assets/5e769b1a-4ce0-459c-848f-ea305344baaf)

Article Info Layout = Single Line
![grafik](https://github.com/user-attachments/assets/f548d6c6-5bab-40e0-af04-c8f71ee24b63)

Article image: first image is intro image, secon one is an image inside the article (before the read more)
![grafik](https://github.com/user-attachments/assets/6142c78d-1fde-42c9-aaeb-09fd8750a9c2)

I have no idea what Astroid framework will do with this module ...

2024-08-08 16:49 UTC, HDInfautre commented
HI
hanks for this very quick response :-)
I'm giving up my positive remarks or on astroid.
I'm just focusing on the remarks
c) it seems that the images are not rendered!
https://j5test-seul.88h.ovh/index.php/test-mod yet I put 2 beautiful images in the text content.
Well it's less important for me because I systematically use the Tassos custom field images which will probably never be taken natively in this module
d) I have not seen any repercussions of modifying the parameter: "Articles Info Layout​"

After possibly on the questions concerning the post-patch updates if it's understandable!?

2024-08-08 17:01 UTC, brianteeman commented
Make sure this setting is set to show
![image](https://github.com/user-attachments/assets/001e6d29-fecf-4516-b056-e9edc872e21d)

2024-08-08 17:02 UTC, drmenzelit commented
The images are not rendered because you have set a character limit for the introtext ... For my understanding that is correct, but maybe I need to change the visibility of the "Show Article Images" parameter...

You are showing only one element (category) from the article info that is why you don't see any difference between multiline and single line, try displaying the author too

2024-08-08 17:32 UTC, HDInfautre commented
HI
hanks for this very quick response :-)
I'm giving up my positive remarks or on astroid.
I'm just focusing on the remarks
c) it seems that the images are not rendered!
https://j5test-seul.88h.ovh/index.php/test-mod yet I put 2 beautiful images in the text content.
Well it's less important for me because I systematically use the Tassos custom field images which will probably never be taken natively in this module
d) I have not seen any repercussions of modifying the parameter: "Articles Info Layout​"

After possibly on the questions concerning the post-patch updates if it's understandable!?

> The images are not rendered because you have set a character limit for the introtext ... For my understanding that is correct, but maybe I need to change the visibility of the "Show Article Images" parameter...
> 
> You are showing only one element (category) from the article info that is why you don't see any difference between multiline and single line, try displaying the author too

Hi
thanks for the follow-up
The image is at the beginning of the text
I checked what seems right to me.

I can give access if necessary.
![scrnli_08_08_2024 19-30-46](https://github.com/user-attachments/assets/99ac3fa0-2708-4ae6-9ea6-dc2f195c0997)
![Capture d’écran du 2024-08-08 19-30-16](https://github.com/user-attachments/assets/a0e85d40-3bd4-4312-8cb5-ce17e987771e)

2024-08-08 17:35 UTC, drmenzelit commented
Again: if you set a limit for the introtext the article images will not be rendered. I commited a new version of the module, I changed the parameter, "Show Article Images" will only be displayed if the introtext limit is set to 0 (not truncated)

2024-08-08 18:03 UTC, HDInfautre commented
> Again: if you set a limit for the introtext the article images will not be rendered. I commited a new version of the module, I changed the parameter, "Show Article Images" will only be displayed if the introtext limit is set to 0 (not truncated)

OK, sorry, I misunderstood.
It works as expected, but as you can see from the result https://j5test-seul.88h.ovh/index.php/test-mod , I think people will prefer to have an image AND reduced text :-)
Otherwise I imagine you'd have to overload the image, which I'm not sure is possible for many people.
I'll be able to do it myself, because you're not going to support images in a custom field anyway?
Regards

2024-08-08 18:24 UTC, drmenzelit commented
You should use intro or full image from the article
And no, we can't support custom fields in the module, for that you will need an override

2024-08-09 10:44 UTC, HDInfautre commented
Hi
do you plan to put "deprecated" in the name of the old modules to avoid that people continue to use the old modules!?

2024-08-09 10:50 UTC, brianteeman commented
> Hi do you plan to put "deprecated" in the name of the old modules to avoid that people continue to use the old modules!?

why would you want to do that

2024-08-09 10:57 UTC, HDInfautre commented
> why would you want to do that

Hey I expressed myself badly!?
The new module replaces the old ones in a much better way. The idea is that people after the release of Joomla 5.2 are encouraged to use the new module :-) and this sends a signal to people who pass by. I see this in Joomla extensions (Tassos) as well as other computer software

But of course, the old sites would use them for years and years

2024-08-16 10:13 UTC, coolcat-creations commented
So soooo happy that https://github.com/joomla/joomla-cms/issues/18455 is finally to become reality  :-) Thank you so much @drmenzelit

2024-08-16 16:39 UTC, brianteeman commented on language/en-GB/mod_articles.ini
> +MOD_ARTICLES_FIELD_LAYOUT_DESC="Display articles vertical or horizontal."
The correct english for this would be "Display articles vertically or horizontally."

But I think it _might_ be simpler english to write
```suggestion
MOD_ARTICLES_FIELD_LAYOUT_DESC="Display articles vertical or horizontal."
```

```suggestion
MOD_ARTICLES_FIELD_LAYOUT_DESC="Vertical or horizontal display of articles."
```

2024-08-16 16:53 UTC, brianteeman reviewed
I just spent ages trying to woek out why the module was not displaying anything. The problem was that everything in the display options is defaulted to OFF.

Someone once told me that default settings should be the "most frequent" or "most useful" settings so that you can get "it working" quickly and fine tune the options later.

Can I suggest that the default settings for the following are set to show and not hide.

- item_title
- show_introtext
- show_readmore

Or at least something so that when you first try the module it actually displays something

2024-08-17 13:32 UTC, drmenzelit commented
Oh, I think I did a mistake in some commit ... the display options should be set to "Title Only (lists) = Yes". I corrected it now.

2024-08-18 12:31 UTC, JeffOnWire commented
Hey there,

I'm working on documentation for this module. While testing I am noticing that when the Display Option _Show Intro/Full Image_ is set to show an image, and the article has an image but no caption for that image, an error message appears at the top of the module. 

For example, this _Cradle Mountain_ article has no caption defined for either its intro or full image:

<p><img src="https://github.com/user-attachments/assets/3802d6cc-867a-4257-b0eb-017d017630cb" width="75%" />
</p>

<p><img src="https://github.com/user-attachments/assets/f7c96135-05e4-4e27-b5b1-5017bf5023c8" width="75%" />
</p>

<p><img src="https://github.com/user-attachments/assets/22d89db3-dfcb-4d55-afd0-9ce3715a46d2" width="75%" />
</p>

2024-08-19 11:26 UTC, drmenzelit commented
@JeffOnWire I can't reproduce the warnings. Can you please check the content of lines 281 and 288?

2024-08-19 15:04 UTC, HDInfautre commented
I have tested this item :white_check_mark: successfully on 56845d4ea33bf89d5eb7b27c57a735a83bddc555<br /><br />Hi
Already successfully tested with alpha3 following my comments on github.
I've just re-tested the package with the latest version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43738">issues.joomla.org/tracker/joomla-cms/43738</a>.</sub>

2024-08-20 05:20 UTC, fgsw commented
> With this module you can replace the existing mod_articles_xx.

This mean the 5 Article Modules you listed below? I tried to show related Articles but didn't get it to work.

2024-08-20 05:59 UTC, drmenzelit commented
@fgsw yes, only the listed ones. Articles Related is still an own module.

2024-08-20 06:32 UTC, exlemor commented
I have tested this item :white_check_mark: successfully on 56845d4ea33bf89d5eb7b27c57a735a83bddc555<br /><br />I have successfully tested this. 

I will add these comments:

a. if I set the Category Filtering Type to Exclusive and I do NOT select a Category, I get results? 
(i.e. I would have expected an error saying that I had not selected a category) - Viviana explained that this is taken from mod_articles_category and there is no error telling you you need to select a category but to me it feels inconsistent with the rest of Joomla so many in the future that could happen.


b. If you choose under Filtering Options: Archived Articles --> Only and you don't happen to have any the Module completely disappears vs showing the Module with a statement like: No articles to display. As per Viviana, the same behavior as the current Archived Articles module but again, it doesn't feel homogeneous will Joomla as a whole - hopefully in the future it will be updated/more homogeneous.


This is a GREAT module - great work by Viviana and Brian (and whomever else helped if anyone did), but as it has so many options, capabilities, it is a bit daunting so great documentation (or possibly additionally a Guided Tour as well) will be needed to make it easiest for users and to guarantee (wide) adoption.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43738">issues.joomla.org/tracker/joomla-cms/43738</a>.</sub>

2024-08-20 07:39 UTC, fgsw commented
> Articles Related is still an own module.

Thanks for the answer. Your PR makes Joomla easier to use.

2024-08-20 08:52 UTC, richard67 commented
I've restored the previous human test results in the issue tracker as the change which invalidated the test count was just a rename of the update SQL script for PostgreSQL, which does not have any functional impact as that is the only 5.2 update SQL yet so it would have run despite of the wrong year in the file name.

=> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43738">issues.joomla.org/tracker/joomla-cms/43738</a>.</sub>

2024-08-20 20:30 UTC, JeffOnWire commented
@drmenzelit After further testing this is maybe not an issue that requires attention. I am able to _fix_ the problem by opening an article for edit, then saving it without making any changes. Possibly the issue is related to sample data? (Perhaps the sample data has a null value for the captions, or the captions property is not initially defined in the database. Opening the article in the editor and saving it maybe updates the property in the database in a way that fixes the problem—if that makes any sense).

2024-08-20 20:35 UTC, brianteeman commented
@JeffOnWire thats a bug - you should not need to do that - although I do understand why that works

2024-08-20 20:39 UTC, JeffOnWire commented
@exlemor Notes that the Articles module disappears completely when there is no content, and this happens also with the Articles - Archive module. I noticed this as well and agree these modules should always appear with a "no articles to display" message.

2024-08-20 20:40 UTC, chmst commented
Yes that's a bug in the sample data plugin. Please @JeffOnWire could you open the issue tracker and mark the test as "not successful"? Then it is no longer Ready To Commit (RTC) and @drmenzelit can work on it. Thank you for testing so carefully :)

2024-08-20 20:42 UTC, richard67 commented
Back to pending due to previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43738">issues.joomla.org/tracker/joomla-cms/43738</a>.</sub>

2024-08-20 20:43 UTC, richard67 commented
> Yes that's a bug in the sample data plugin. Please @JeffOnWire could you open the issue tracker and mark the test as "not successful"? Then it is no longer Ready To Commit (RTC) and @drmenzelit can work on it. Thank you for testing so carefully :)

I've already removed RTC.

2024-08-20 21:12 UTC, JeffOnWire commented
Here's what I've done just now to recreate the issue.

Saved _configuration.php_ then removed it from the root.
Created a new database.
Opened the site in a browser and configured the site using the new database.
Logged in as admin.
From the administrator dashboard I see a _Sample Data_ module. 
Click on the first option to install _Testing Sample Data_
Install the _Articles_ module and configure:

- Title: Articles Module Test
- Position: sidebar-right
- Article IDs to Include: 11 and 25
- Display Options > Show Intro/Full Image: Intro Image

And then viewing the homepage I see the errors:

![2024-08-20_14-08-55](https://github.com/user-attachments/assets/d3dc1977-9981-40f6-8afb-c4cbb8213cb6)

2024-08-21 06:25 UTC, drmenzelit commented
> I have modified the Blog Sample Data to display the new module instead of the old ones. The Testing Sample Data need a complete restructuring and I'm not sure if I'm able to do that.

As I wrote before, I did not touched the Testing Sample Data Plugin and I'm not able to rewrite it.

I will try to reproduce the warnings, but if the problem comes from the Testing Sample Data Plugin, then someone else has to repair it.

2024-08-21 06:41 UTC, drmenzelit commented
The bug with the caption is related with the Testing Sample Data and not with this PR. The same problem appears with an Articles Newsflash module on a site with installed sample data
![grafik](https://github.com/user-attachments/assets/52bcf3a0-c744-405a-8697-3b92498aa0aa)

2024-08-21 07:19 UTC, chmst commented
Testing sample data are not in scope for this PR, but we don't know if older content has empty values in images.

2024-08-21 07:22 UTC, drmenzelit commented
I modified the query to catch the possibility of a wrong set image caption. @HDInfautre , @exlemor , @JeffOnWire I will appreciate a new test from you :-)

2024-08-21 17:31 UTC, JeffOnWire commented
@drmenzelit The error is gone. Everything looks fine to me.

2024-08-21 17:54 UTC, drmenzelit commented
@JeffOnWire can you please mark your test in the issue tracker? Thanks

2024-08-21 23:37 UTC, JeffOnWire commented
I have tested this item :white_check_mark: successfully on 56845d4ea33bf89d5eb7b27c57a735a83bddc555<br /><br />The error messages I received before no longer appear. Module is working correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43738">issues.joomla.org/tracker/joomla-cms/43738</a>.</sub>

2024-08-23 22:21 UTC, JeffOnWire commented
When I set the Filter Options to show featured articles, and set the Display Options to show Introtext (with  _Introtext Limit (Characters)_  set to 100 characters), the featured articles are displayed with all the article text (or up to the _Read More_ placeholder if the article has one). Should the amount of text for featured articles be restricted to _Introtext Limit (Characters)_ like any other article?

2024-08-24 08:55 UTC, RickR2H commented
> When I set the Filter Options to show featured articles, and set the Display Options to show Introtext (with _Introtext Limit (Characters)_ set to 100 characters), the featured articles are displayed with all the article text (or up to the _Read More_ placeholder if the article has one). Should the amount of text for featured articles be restricted to _Introtext Limit (Characters)_ like any other article?

I could not reproduce this issue. Please check again and make sure you tell us how to reproduce this, so we can check/fix any issues.

2024-08-24 08:56 UTC, RickR2H commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43738">issues.joomla.org/tracker/joomla-cms/43738</a>.</sub>

2024-08-24 08:57 UTC, brianteeman commented
@RickR2H this should not be RTC until @JeffOnWire responds to your question

2024-08-24 11:54 UTC, RickR2H commented
@brianteeman I later noticed that @JeffOnWire tested successfully. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43738">issues.joomla.org/tracker/joomla-cms/43738</a>.</sub>

2024-08-24 14:33 UTC, bembelimen requested changes, later dismissed
I hope this great idea will make it into 5.2, but I also think there is some improvements needed before we can add it. For example we should not add old rich snippets elements. I also think the layout should be a bit cleaned out (I ~~will create~~ created a PR for this against your branch @drmenzelit https://github.com/drmenzelit/joomla-cms/pull/38)

2024-08-24 19:18 UTC, drmenzelit commented
Merged the changes done by @bembelimen (thank you for cleaning the code) and corrected an error in the logic of displaying article imagas that was interfering with the truncation of the intro text.

2024-08-24 19:25 UTC, richard67 commented
@drmenzelit Could you fix PHPCS errors reported here https://ci.joomla.org/joomla/joomla-cms/78353/1/7 ? Thanks in advance.

2024-08-24 19:29 UTC, drmenzelit commented
@richard67 I was on it, done ... I hope ;-)

2024-08-26 17:44 UTC, pcombet-adosis commented
Hello,
tested in Multilanguage environment (FR/ENG), very interesting feature. Works well. One notice : "Article IDs to Exclude" - I did not manage how to separate the differents articles, tested, comma (,), dash (-) ... until I saw the multiline icon to show it needs a carriage return. It would be nice just to add an info at the RollOver on the "Article IDs to Exclude" text which would say "article ID separated by a carriage return" . 
Best 
Philippe

2024-08-26 17:45 UTC, pcombet-adosis commented
I have tested this item :white_check_mark: successfully on 56845d4ea33bf89d5eb7b27c57a735a83bddc555<br /><br />Hello,
tested in Multilanguage environment (FR/ENG), very interesting feature. Works well. One notice : "Article IDs to Exclude" - I did not manage how to separate the differents articles, tested, comma (,), dash (-) ... until I saw the multiline icon to show it needs a carriage return. It would be nice just to add an info at the RollOver on the "Article IDs to Exclude" text which would say "article ID separated by a carriage return" . 
Best 
Philippe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43738">issues.joomla.org/tracker/joomla-cms/43738</a>.</sub>

2024-08-27 15:46 UTC, JeffOnWire commented
@RickR2H I tested this morning and was unable to recreate the introtext issue I raised on August 23. I have no issues. Everything looks fine.

2024-08-27 21:49 UTC, JeffOnWire commented
I'm working with Ordering Options today and may have another issue—order by alias seems to be ordering by title. Here's my setup:

Removed configuration.php from the root.
Created a new database, configured Joomla and logged in as admin.
From the administrator dashboard I see a Sample Data module. Installed _Testing Sample Data_
Created two new user accounts, for Arthur Able and Peter Petra.
Went to Content > Articles, sorted by ID ascending and edited articles with ID 1-6

- Administrator Components (ID 1): Created by = Arthur Able; leave alias blank
- Archive Module (ID 2): Alias = Barbara Brown
- Article Categories Module (ID 3): Created by = Peter Petra; leave alias blank
- Articles Category Module (ID 4): Alias = Eddie Earnest
- Authentication (ID 5): No change (created by you); leave alias blank
- Australian Parks (ID 6): Alias = Helen Hurry

Install the Articles module and configure:

    Title: Articles Module Test
    Articles to Display: 6
    Position: sidebar-right
    Article IDs to Include: 1,2,3,4,5,6 on separate lines
    
    Display Options: Title Only = No; Author: Show

    Ordering Options: Alias Ascending (and switched back and forth between Ascending and Descending while testing)

I'm observing that the articles are always ordered by Title, regardless of the Author or Alias value.

### Question about how Author and Alias

In _Display Options_ we have **Author** (which will display the _Created by Alias_ if defined in the article, otherwise it displays the _Created by_ user), but in _Ordering Options_ we have **Alias**, which I'm assuming would function in a similar way...ordering by either _Created by_ or _Created by Alias_. Should these be labeled the same, either Author or Alias, to be consistent?

### Finish Publishing Date

In _Ordering Options_ we have the option to order by _Finish Publishing Date_ but there is no display option for the finish publishing date. Should there be?

2024-08-28 09:50 UTC, drmenzelit commented
@JeffOnWire I think there is a misunderstanding of Alias ... Alias refers to the alias of the article, this one on the right:
![grafik](https://github.com/user-attachments/assets/42d92c6b-4d9b-43b7-85d2-68a4919ccbf9)

2024-08-28 15:11 UTC, JeffOnWire commented
@drmenzelit Ah, thank you.

2024-08-30 19:39 UTC, Hackwar commented
Thank you @drmenzelit for this great feature!

2024-08-30 19:58 UTC, merged

2024-09-16 09:52 UTC, Kostelano commented
@drmenzelit 

Hi! Category as a link is never shown as a parameter because:

`showon="title_only:0[AND]show_category:1[AND]card_link:0"`

This (card_link:0) needs to be removed or revised.

2024-09-16 10:07 UTC, drmenzelit commented
@Kostelano thank you for the hint, we removed some parameters on the last version of the module before the merge and it seems we forgot to chech this one. We will correct it.