[5.1] Update bump script also to update package-lock.json
joomla/joomla-cms pull request #43801
Opened 2024-07-17 17:16 UTC by HLeithner

Pull Request for Issue #43743 .

### Summary of Changes
Also update the package-lock.json on version bump

### Testing Instructions
php build/bump.php -v 5.2.3

### Actual result BEFORE applying this Pull Request
package.json is updated
package-lock.json is not updated

### Expected result AFTER applying this Pull Request
package.json is updated
package-lock.json is updated

2024-07-17 17:19 UTC, LadySolveig commented
Thanks @HLeithner

2024-07-17 17:45 UTC, Quy commented on build/bump.php
> +foreach($packageJsonFiles as $packageJsonFile) {
```suggestion
foreach ($packageJsonFiles as $packageJsonFile) {
```

2024-07-17 17:50 UTC, richard67 commented
I have tested this item :white_check_mark: successfully on eba833dc71b78d0809b571ed96341074465e970a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43801">issues.joomla.org/tracker/joomla-cms/43801</a>.</sub>

2024-07-17 17:59 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on eba833dc71b78d0809b571ed96341074465e970a<br /><br />by code review



Thanks!!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43801">issues.joomla.org/tracker/joomla-cms/43801</a>.</sub>

2024-07-17 18:03 UTC, brianteeman commented
(I got a php fatal error on line 313 BUT i ran it on windows and I seem to recall the script will not run on windows and that part of the file is not part of this PR and the parts in this PR all completed correctly)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43801">issues.joomla.org/tracker/joomla-cms/43801</a>.</sub>

2024-07-17 18:05 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43801">issues.joomla.org/tracker/joomla-cms/43801</a>.</sub>

2024-07-17 18:05 UTC, HLeithner commented
I tested it and it worked on linux, also line 313 is only a preg_replace so shouldn't fail

2024-07-17 18:08 UTC, LadySolveig commented
Thank you @brianteeman and @richard67 for testing!

2024-07-17 19:11 UTC, dgrammatiko requested changes

2024-07-17 19:11 UTC, dgrammatiko commented on build/bump.php
> +        file_put_contents($rootPath . $packageJsonFile, str_replace('    ', '  ', json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)));
```suggestion
        file_put_contents($rootPath . $packageJsonFile, str_replace('    ', '  ', json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) . '/n');
```

The Code Style for JS/JSON requires an empty line at the end of the file

2024-07-17 19:17 UTC, richard67 commented on build/bump.php
> +        file_put_contents($rootPath . $packageJsonFile, str_replace('    ', '  ', json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)));
That’s right.

2024-07-18 06:01 UTC, LadySolveig commented
Thanks @dgrammatiko

2024-07-18 09:16 UTC, dgrammatiko requested changes

2024-07-18 09:16 UTC, dgrammatiko commented on build/bump.php
> +        file_put_contents($rootPath . $packageJsonFile, str_replace('    ', '  ', json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) . '/n');
```suggestion
        file_put_contents($rootPath . $packageJsonFile, str_replace('    ', '  ', json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) . "\n");
```

2024-07-18 09:16 UTC, dgrammatiko commented on build/bump.php
> +        file_put_contents($rootPath . $packageJsonFile, str_replace('    ', '  ', json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) . '/n');
Oops I've messed it up, now should be fine

2024-07-18 09:18 UTC, LadySolveig commented on build/bump.php
> +        file_put_contents($rootPath . $packageJsonFile, str_replace('    ', '  ', json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) . '/n');
Thanks

2024-07-18 10:05 UTC, merged