[5.2] [WIP] Feat: Introduce Mail Template Layout
joomla/joomla-cms pull request #43829
Opened 2024-07-23 10:05 UTC by LadySolveig

Pull Request for Issue #39492  .

### Summary of Changes

_Work in progress_

The functionality for displaying the logo and sending it as an inline attachment depends on this fix #43828 

Add support for mail template layouts as a parent wrapper around the existing mail templates.

- ✅  A new default responsive mail template **layout** file `mailtemplate.php` for rendering mail content with sitename in footer and optional logo.
- ✅  A new form field `MailtemplateLayoutField` to list available mail template layouts (overrides) from (frontend) templates.
- ✅  Updates to `MailTemplate` class to handle layout data and render email content using the specified layout.
- ✅   Configuration options in `config.xml` to enable/disable HTML layout and select a mail template layout globally.
- ✅   Form updates in `template.xml` to include options for disabling HTML layout and selecting a mail template layout individual for each template.
- ✅ Adjustments in `TemplateModel` to remove HTML layout fields when the mail style is set to plaintext.

#### Global Configuration -> Mail Templates

![grafik](https://github.com/user-attachments/assets/7fae2906-2989-41de-9473-aec4d655bb02)

####  Individual settings for each template

![grafik](https://github.com/user-attachments/assets/071fa241-93fc-4b99-b318-2c090638a201)

### Testing Instructions

_work in progress_

### Actual result BEFORE applying this Pull Request

![grafik](https://github.com/user-attachments/assets/98695491-0f2a-49c9-a5f5-f0d94d67274a)

### Expected result AFTER applying this Pull Request

![grafik](https://github.com/user-attachments/assets/e2a5b35b-7e22-465e-8ef7-262043311cc1)

### Link to documentations
Please select:
- [X] Documentation link for docs.joomla.org: <work in progress>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2024-07-23 10:28 UTC, brianteeman commented on administrator/components/com_mails/config.xml
> +			showon="mail_style:html[OR]mail_style:both[AND]disable_htmllayout:1"
```suggestion
		<field
			name="mail_logoFile"
			type="media"
			label="COM_CONFIG_FIELD_MAILTEMPLATE_LOGOFILE_LABEL"
			schemes="http,https,ftp,ftps,data,file"
			validate="url"
			relative="true"
			default=""
			showon="mail_style:html[OR]mail_style:both[AND]disable_htmllayout:1"
```

2024-07-23 10:29 UTC, LadySolveig commented on administrator/components/com_mails/config.xml
> +			showon="mail_style:html[OR]mail_style:both[AND]disable_htmllayout:1"
Thanks!

2024-07-23 10:40 UTC, brianteeman commented
Can I suggest changing this
![image](https://github.com/user-attachments/assets/9113d1ba-08b8-4600-9c30-cd3c20a79158)

to
![image](https://github.com/user-attachments/assets/69412038-f3e2-4d15-8dbb-c63876a8dfbb)

2024-07-23 10:44 UTC, LadySolveig commented
@brianteeman if you want to change it by review in the language files I can commit directly :)

2024-07-23 10:49 UTC, brianteeman commented on layouts/joomla/mail/mailtemplate.php
> +                                    <p style="margin:0;font-size:14px;line-height:20px;">&reg; <?php echo isset($extraData['siteName']) ? $extraData['siteName'] . ' ' : ''; ?><?php echo date("Y"); ?>
```suggestion
                                    <p style="margin:0;font-size:14px;line-height:20px;">&copy; <?php echo isset($extraData['siteName']) ? $extraData['siteName'] . ' ' : ''; ?><?php echo date("Y"); ?>
```

2024-07-23 10:56 UTC, brianteeman commented on administrator/language/en-GB/com_config.ini
> +COM_CONFIG_FIELD_MAILTEMPLATE_LAYOUT_LABEL="Mail Template Layout"
```suggestion
COM_CONFIG_FIELD_MAILTEMPLATE_LAYOUT_LABEL="Layout"
```

2024-07-23 10:56 UTC, brianteeman commented on administrator/language/en-GB/com_config.ini
> +COM_CONFIG_FIELD_MAILTEMPLATE_LAYOUT_OFF_LABEL="Disable Mail Template Layout"
```suggestion
COM_CONFIG_FIELD_MAILTEMPLATE_LAYOUT_OFF_LABEL="Mail Template Layout"
```

2024-07-23 10:57 UTC, brianteeman commented on administrator/language/en-GB/com_mails.ini
> +COM_MAILS_FIELD_HTML_LAYOUT_LABEL="Mail Template Layout"
```suggestion
COM_MAILS_FIELD_HTML_LAYOUT_LABEL="Layout"
```

2024-07-23 10:57 UTC, brianteeman commented on administrator/language/en-GB/com_mails.ini
> +COM_MAILS_FIELD_HTML_LAYOUT_OFF_LABEL="Disable Mail Template Layout"
```suggestion
COM_MAILS_FIELD_HTML_LAYOUT_OFF_LABEL="Mail Template Layout"
```

2024-07-23 10:58 UTC, LadySolveig commented on administrator/language/en-GB/com_config.ini
> +COM_CONFIG_FIELD_MAILTEMPLATE_LAYOUT_LABEL="Mail Template Layout"
Thank you 👍🏼

2024-07-23 11:10 UTC, brianteeman commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="en" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#00000008;height:100%;">
this should be using the lang of the email and not lang="en"

2024-07-23 11:12 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="en" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#00000008;height:100%;">
Nice catch - you are absolutely right. This should be dynamic. I create a fix for this.

2024-07-23 11:22 UTC, brianteeman commented
I am really happy to see this. It's the missing link to truly make branded html mails.

Basic functionality all works great.

2024-07-23 11:47 UTC, brianteeman commented on layouts/joomla/mail/mailtemplate.php
> +                                    <br><a title="<?php echo $siteUrl;?>" href="<?php echo $siteUrl; ?>" style="color:#cccccc;text-decoration:underline;"><?php echo substr_replace($siteUrl, 'www.', 0
What is the purpose of enforcing www on the presentation of the site url. Not all sites use www especially subdomains

2024-07-23 11:54 UTC, brianteeman commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="en" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#00000008;height:100%;">
aria-roledescription="email"

Where did this come from - as far as I can see there is no aria role of email (https://www.w3.org/TR/wai-aria-1.1/#role_definitions) as a result this is invalid markup

2024-07-23 12:05 UTC, brianteeman commented
When per template email setting is set to NO then I would not expect to see the layout options per email - is that an error/bug

When per template email setting is set to YES I have the option to enable the layout and select a layout but I cannot select an image - is that an error/bug or by design. I am hoping its an error/bug as I would use log as an image header

2024-07-23 12:20 UTC, HLeithner commented on layouts/joomla/mail/mailtemplate.php
> +                                    <br><a title="<?php echo $siteUrl;?>" href="<?php echo $siteUrl; ?>" style="color:#cccccc;text-decoration:underline;"><?php echo substr_replace($siteUrl, 'www.', 0
it's the other way around, reducing the length of the visible link by removing the www. if it exists. Like it I would have done it easier including the schema but also ok (remove https://www. from https://google.com)

2024-07-23 12:21 UTC, brianteeman commented on layouts/joomla/mail/mailtemplate.php
> + * @subpackage  com_mails
```suggestion
 * @subpackage  Layout
```

that's how all the other layouts are documented

2024-07-23 12:26 UTC, brianteeman commented on layouts/joomla/mail/mailtemplate.php
> +                                    <br><a title="<?php echo $siteUrl;?>" href="<?php echo $siteUrl; ?>" style="color:#cccccc;text-decoration:underline;"><?php echo substr_replace($siteUrl, 'www.', 0
That might have been the intent but its not what happens

![image](https://github.com/user-attachments/assets/a3d06771-590f-4e82-8ee7-60ec471ea631)

The substr_replace($siteUrl, 'www.', 0, strlen(Uri::getInstance()->toString(['scheme']))) function replaces the first occurrence of the URL's scheme (i.e., "http://" or "https://") with "www."

2024-07-23 12:54 UTC, Fedik commented
Tanks @LadySolveig . That it is very good feature.

Some thoughts for future.
What also would be cool, is to have an API to add inline images more freely, before layout rendering (or within the layout).
Kind of:
```php
$mailTemplate->embedImages([
  'header-image' => 'path/to/image.jpg', 
  'logo-image' => 'path/to/logo.jpg'
]);
```
```html
// Then in layout:
<img src="cid:header-image" alt="inline image"/>
<img src="cid:logo-image" alt="logo image"/>
```
But I not sure how to correctly interconnect it.

Do not code it here, just ideas for future.  :wink:

2024-07-23 12:54 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="en" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#00000008;height:100%;">
> aria-roledescription="email"

I think that's a misunderstanding. The aria role is `article`, only the aria-roledescription is email.

https://www.digitala11y.com/aria-roledescriptionproperties/

But I know that you are very well informed in this area. Would you want to remove it?
What do you think @chmst  - I would also be interested in your opinion on this?

2024-07-23 12:59 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +                                    <br><a title="<?php echo $siteUrl;?>" href="<?php echo $siteUrl; ?>" style="color:#cccccc;text-decoration:underline;"><?php echo substr_replace($siteUrl, 'www.', 0
I'll be honest it just looked nicer than http:// 😄 , but of course you're right, technically it's just wrong. And I should put my personal preference in my own override rather than in the layout here. Changed 👍🏼

2024-07-23 13:06 UTC, Fedik commented on libraries/src/Mail/MailTemplate.php
> +                        $this->mailer->addAttachment($logo, basename($logo), 'base64', mime_content_type($logo), 'inline');
Can also use dedicated method for this: `$this->mailer->addEmbeddedImage($path, $cid)`

2024-07-23 13:09 UTC, LadySolveig commented on libraries/src/Mail/MailTemplate.php
> +                        $this->mailer->addAttachment($logo, basename($logo), 'base64', mime_content_type($logo), 'inline');
Very nice 💚 I put it on my list and make a new PR

2024-07-23 13:12 UTC, Fedik commented on libraries/src/Mail/MailTemplate.php
> +                        $this->mailer->addAttachment($logo, basename($logo), 'base64', mime_content_type($logo), 'inline');
And I think, for the logo we better use fixed `cid`, kind of `site-logo`, 
it will be safer and esier than use of file name.

2024-07-23 14:34 UTC, zero-24 commented on administrator/components/com_mails/config.xml
> +		addfieldprefix="Joomla\Component\Mails\Administrator\Field" >
```suggestion
		addfieldprefix="Joomla\Component\Mails\Administrator\Field">
```

2024-07-23 14:34 UTC, zero-24 commented on administrator/components/com_mails/src/Field/MailtemplateLayoutField.php
> +        // $extension = explode('.', $this->form->getValue('context'));
Is there a need to keep commented code

2024-07-23 14:34 UTC, zero-24 commented on layouts/joomla/mail/mailtemplate.php
> +                    <td align="center" style="vertical-align:baseline; padding:30px 0">
I suspect its the outlook thing here but are that inline styles here in this file actually required?

2024-07-23 14:34 UTC, zero-24 commented on layouts/joomla/mail/mailtemplate.php
> +                        <table role="presentation" style="width:94%;max-width:630px;border:none;border-spacing:0;text-align:left;font-family:Arial,sans-serif;font-size:16px;line-height:22px;color:#36
Fore example font family is quite selective shouldt we let that be down to the client who displays the item? Similiar with width: 94% or max-width etc etc.

2024-07-23 14:34 UTC, zero-24 commented on libraries/src/Mail/MailTemplate.php
> +        $htmlBody  = $useLayout ? Text::_($mail->htmlbody) : $this->replaceTags(Text::_($mail->htmlbody), $this->data);
On a first look it seams that the replacement of variables would not work anymore with that change? Or whats the need for the change here?

2024-07-23 14:34 UTC, zero-24 commented on libraries/src/Mail/MailTemplate.php
> +                // Wrap the default Joomla mail template around the HTML body
```suggestion

                // Wrap the default Joomla mail template around the HTML body
```

2024-07-23 14:34 UTC, zero-24 commented on libraries/src/Mail/MailTemplate.php
> +                $layoutFile   = new FileLayout('joomla.mail.' . $layout, null, ['client' => 'site']);
```suggestion
                $layoutFile  = new FileLayout('joomla.mail.' . $layout, null, ['client' => 'site']);
```

2024-07-23 14:34 UTC, zero-24 commented on libraries/src/Mail/MailTemplate.php
> +                // Set the default template search path
```suggestion

                // Set the default template search path
```

2024-07-23 14:34 UTC, zero-24 commented on libraries/src/Mail/MailTemplate.php
> +                $htmlBody  = $this->replaceTags(Text::_($htmlBody), $this->data);
```suggestion
                $htmlBody = $this->replaceTags(Text::_($htmlBody), $this->data);
```

2024-07-23 14:42 UTC, LadySolveig commented on libraries/src/Mail/MailTemplate.php
> +        $htmlBody  = $useLayout ? Text::_($mail->htmlbody) : $this->replaceTags(Text::_($mail->htmlbody), $this->data);
That you can also use specific tags in your overrides and they will be replaced after rendering the layout. Useful if you have a specific template override for an email.
But otherwise it doesn't hurt too.
The replacement in this case is in line 332

2024-07-23 14:43 UTC, Fedik commented on layouts/joomla/mail/mailtemplate.php
> +                    <td align="center" style="vertical-align:baseline; padding:30px 0">
Unfortunately, in many case it is only way to make something working in email :wink:

2024-07-23 14:46 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +                    <td align="center" style="vertical-align:baseline; padding:30px 0">
To my knowledge Gmail still strips the style tags. So it is safer to have it inline in Mails.

https://www.emailonacid.com/blog/article/email-development/12_things_you_must_know_when_developing_for_gmail_and_gmail_mobile_apps-2/

2024-07-23 14:50 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +                        <table role="presentation" style="width:94%;max-width:630px;border:none;border-spacing:0;text-align:left;font-family:Arial,sans-serif;font-size:16px;line-height:22px;color:#36
If you remove the width, it is not responsive anymore. At the moment, 600px is the standard width that is currently considered best practice in email marketing.

2024-07-23 14:58 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +                        <table role="presentation" style="width:94%;max-width:630px;border:none;border-spacing:0;text-align:left;font-family:Arial,sans-serif;font-size:16px;line-height:22px;color:#36
If I remove the default font (Websafe - Arial) here, it will be displayed differently on each client.
Then we are again far away from a layout that is uniformly displayed on every device.
That would be similar to delivering Cassiopeia without a default font.

I completely agree with you that this is of course very individual, but there is the option of overriding in your template. 

I would like to offer a good standard for those who don't want to do it themselves and perhaps have no idea of the differences and pitfalls when creating an HTML email.

2024-07-23 15:01 UTC, Fedik commented on layouts/joomla/mail/mailtemplate.php
> +                        <table role="presentation" style="width:94%;max-width:630px;border:none;border-spacing:0;text-align:left;font-family:Arial,sans-serif;font-size:16px;line-height:22px;color:#36
@zero-24 It is common practice in the world of the email templating.
Some devs goes much further and doing it for evry `<td>`.

Email clients is diferent from real Browsers  very much.
We cannot escape from inline styles, and hacky css tricks.

2024-07-23 15:04 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +                        <table role="presentation" style="width:94%;max-width:630px;border:none;border-spacing:0;text-align:left;font-family:Arial,sans-serif;font-size:16px;line-height:22px;color:#36
I don't like it either, but unfortunately it is necessary.

2024-07-23 15:39 UTC, coolcat-creations commented
Awesome, can one create a signature somewhere and embed it in the mail template?
Thank you!!!

2024-07-23 16:00 UTC, brianteeman commented
> Awesome, can one create a signature somewhere and embed it in the mail template? Thank you!!!

You would need to create your own mail template for that

2024-07-23 16:02 UTC, coolcat-creations commented
Maybe this: ® Joomla mail 2024
www.localhost/mail/ is a language string and could be used?
I will check it out as soon as possible.

2024-07-23 16:03 UTC, brianteeman commented
To answer comments about the html and inline styles used. @LadySolveig is absolutely correct html in email is stuck back in the 90's. I ran the generated email through a checker (mailtrap.io) 

![image](https://github.com/user-attachments/assets/78ab8b0b-9c4f-4808-8c6d-4f542b1f3d31)

2024-07-23 16:05 UTC, LadySolveig commented
Thank you for the additional check @brianteeman 
I will address your other comment later this evening and give an update 👍🏼

2024-07-23 16:05 UTC, brianteeman commented
> Maybe this: ® Joomla mail 2024 [www.localhost/mail/](http://www.localhost/mail/) is a language string and could be used? I will check it out as soon as possible.

it is not a string. As already stated you would need to create a layout

2024-07-23 16:06 UTC, LadySolveig commented
@coolcat-creations you can create a complete layout override in your frontend template for this purpose 👍🏼

2024-07-23 16:08 UTC, coolcat-creations commented
love it!

2024-07-23 18:15 UTC, zero-24 commented on layouts/joomla/mail/mailtemplate.php
> +                        <table role="presentation" style="width:94%;max-width:630px;border:none;border-spacing:0;text-align:left;font-family:Arial,sans-serif;font-size:16px;line-height:22px;color:#36
Ok thanks. Didnt knew all the details only that it is a mess. Thanks for checking up on that. 👍

2024-07-24 08:04 UTC, webnet-assmann commented
I have tested this item :white_check_mark: successfully on abe2893fbcdc23f42f15d70cb3cb15f5ec4c1aea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43829">issues.joomla.org/tracker/joomla-cms/43829</a>.</sub>

2024-07-24 18:46 UTC, sayfrndship1234 commented
great effort !

2024-07-25 11:42 UTC, LadySolveig commented
@brianteeman I am looking forward to your feedback :)

I have now reworked and hopefully incorporated the use case you described as practicably as possible.
(Short note: My changes are partly dependent on this PR #43842, so that only the fields that are relevant are displayed - whenever possible - and there is as little confusion as possible due to the additional options.

## Scenario 1

Per Template Settings are `disabled` in the Global Configuration:
- no additonal options in template edit view and the global settings are used.

![grafik](https://github.com/user-attachments/assets/8d229454-7e23-435b-8cd3-46b79a309ed6)

![grafik](https://github.com/user-attachments/assets/0b2d7ba2-dd88-44e4-bf8d-ec726e712018)

## Scenario 2

Per Template Settings are `enabled` in the Global Configuration:
- additonal options in template edit view with default settings to use the global options
- option to disable the sending of the logofile as an attachment. (If no logo is selected in the global configuration, it will not be sent anyway)
- separated from the `Mail Settings` switcher:

As I noticed during testing that PHP Mail is always entered for the Mailer option when it `Mail Settings` is activated (completely independent of the settings in the global configuration).
I don't find it particularly user-friendly if I “only” want to change the layout and then have to check the mailer settings also per template. I consider this to be a major potential source of errors in this context.
But I am open to objections and other views here.

![grafik](https://github.com/user-attachments/assets/5332b25d-1ed2-42f0-bb2a-361c1d44c237)

![grafik](https://github.com/user-attachments/assets/30fcfed4-8a9d-4631-bd96-a7bfbc0c64f6)

2024-07-25 11:50 UTC, brianteeman commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="en" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#00000008;height:100%;">
as you have set the lang on the parent html element you can remove it from here - unless the daft email formatting conditions require it here as well in which case please make it dynamic

2024-07-25 12:00 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="en" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#00000008;height:100%;">
Thank you!

2024-07-25 13:58 UTC, Quy commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="<?php echo (isset($extraData['lang'])) ?  $extraData['lang'] : 'en' ?>" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-t
```suggestion
        <div role="article" aria-roledescription="email" lang="<?php echo isset($extraData['lang']) ?  $extraData['lang'] : 'en'; ?>" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#00000008;height:100%;">
```

2024-07-25 13:59 UTC, Quy commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="<?php echo (isset($extraData['lang'])) ?  $extraData['lang'] : 'en' ?>" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-t
```suggestion
        <div role="article" aria-roledescription="email" lang="<?php echo isset($extraData['lang']) ? $extraData['lang'] : 'en'; ?>" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#00000008;height:100%;">
```

2024-07-25 14:01 UTC, LadySolveig commented on layouts/joomla/mail/mailtemplate.php
> +        <div role="article" aria-roledescription="email" lang="<?php echo (isset($extraData['lang'])) ?  $extraData['lang'] : 'en' ?>" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-t
Thank you @Quy I decided to remove this completely cause it is not really necessary.

2024-07-25 14:24 UTC, Fedik commented on libraries/src/Mail/MailTemplate.php
> +                    $logo = Path::check(JPATH_ROOT . '/' . HTMLHelper::cleanImageURL($logo)->url);
Please HtmlHelper as `HTMLHelper::_()`: 
```php
HTMLHelper::_('cleanImageURL', $logo)->url;
```

2024-07-25 15:54 UTC, bembelimen commented
I have tested this item :white_check_mark: successfully on 1e2cb33de6bd104cd7b813f848b2e67323d48b7d<br /><br />Also tested with child-template overrides. Works great. Thanks for the PR!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43829">issues.joomla.org/tracker/joomla-cms/43829</a>.</sub>

2024-07-25 16:03 UTC, LadySolveig commented
If you have time, I can ask you to repeat your test again. I have revised the testing instuctions and the PR once again. @webnet-assmann Thank you 💚

2024-07-25 16:04 UTC, brianteeman commented
Why is it that when per template is enabled I can only chose the layout and enable/disable the logo. Why can I not change the logo

2024-07-25 16:11 UTC, LadySolveig commented
I thought of a single place for the logo brand. and only for the deactivation so that it is not attached if the logo is not present in the template override.

Would prefer to create a follow up PR for this additional option in conjunction with @Fedik  suggestion for an Image API here https://github.com/joomla/joomla-cms/pull/43829#issuecomment-2245172520

2024-07-25 16:16 UTC, brianteeman commented
If I can change the mail template I should also be able to change the image file. For example the dimensions of the image file might not be appropriate for every template but there are many reasons to want to change the image used. Am I missing some reasoning that explains why I woudl not want to do that

2024-07-25 16:32 UTC, LadySolveig commented
It was a really good point that it is possible to have an override without an image, and then the image shouldn't be attached either.
As in your example, outputting the log in the header.
But changing the image per template is an improvement that is outside the scope of this PR.

As mentioned, that would be a good improvement for an additional PR, as also adding an API for the inline attachments.

2024-07-25 16:47 UTC, brianteeman commented
I dont understand your logic for not allowing the image to be changed. To me it devalues the usefulness of having per mail layouts but I am not going to block it

2024-07-25 17:11 UTC, coolcat-creations commented
how about solving the image "issue" like that, that the image must be always in a path with the template name? I totally see the need for different logos on several sites.

2024-07-25 17:14 UTC, bembelimen commented
Why then not just making a PR when this is merged?

2024-07-25 17:15 UTC, coolcat-creations commented
> Why then not just making a PR when this is merged?

That would be fine too — otherwise the feature is lost in discussion.

2024-07-25 17:55 UTC, brianteeman commented
I have tested this item :white_check_mark: successfully on 1e2cb33de6bd104cd7b813f848b2e67323d48b7d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43829">issues.joomla.org/tracker/joomla-cms/43829</a>.</sub>

2024-07-25 18:35 UTC, chmst commented
I have tested this item :white_check_mark: successfully on 1e2cb33de6bd104cd7b813f848b2e67323d48b7d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43829">issues.joomla.org/tracker/joomla-cms/43829</a>.</sub>

2024-07-25 18:40 UTC, chmst commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43829">issues.joomla.org/tracker/joomla-cms/43829</a>.</sub>

2024-07-25 22:16 UTC, exlemor commented
I have tested this item :white_check_mark: successfully on 1e2cb33de6bd104cd7b813f848b2e67323d48b7d<br /><br />I was able to test this successfully.

As discussed with Martina, I should note that Scenarios 1-5, I had my Mailer set to PHP Mail and they worked fine, Scenario 6 gave an Could not instantiate mail function but when I switched the mailer to Sendmail that scenario worked. Scenario 7 worked on PHP Mail.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43829">issues.joomla.org/tracker/joomla-cms/43829</a>.</sub>

2024-07-26 07:53 UTC, HLeithner requested changes
question in general, why do we need a layout.php file and not use the mail template component it self and save the base html layout in the database so people can adapt it easily at the place where all other mail layouts are stored?

2024-07-26 07:53 UTC, HLeithner commented on administrator/components/com_mails/src/Field/MailtemplateLayoutField.php
> +            ->where('enabled = 1');
quoteName missing

2024-07-26 07:53 UTC, HLeithner commented on libraries/src/Mail/MailTemplate.php
> +                }
just as side note, phpmailer can automatically attach images as inline files from html body

2024-07-26 07:53 UTC, HLeithner commented on libraries/src/Mail/MailTemplate.php
> +                $htmlBody = $layoutFile->render(['mail' => $htmlBody, 'extra' => $this->layoutTemplateData], null);
I miss the $mailer object in the layout, i would allow adding own stuff like attachments and additional emails much easier.

2024-07-26 08:01 UTC, Fedik commented
> save the base html layout in the database so people can adapt it easily 

No please, it is like saving index.php of the main template in database.
It will be huge and unpractical.

2024-07-26 08:15 UTC, HLeithner commented
> > save the base html layout in the database so people can adapt it easily
> 
> No please, it is like saving index.php of the main template in database. It will be huge and unpractical.

tbh, we need to be more user friendly for end users and they are unable (or don't want to) to touch php documents.
In the provided layout is nothing fancy that needs php.

2024-07-26 08:19 UTC, Fedik commented
This kind of thing is for "advanced user", it is not average HTML that can be edited in TinyMCE.
However the layout can be provided as part of the site template (by template developers), and it can be edited as any other template file.

2024-07-26 08:24 UTC, Fedik commented on libraries/src/Mail/MailTemplate.php
> +                $htmlBody = $layoutFile->render(['mail' => $htmlBody, 'extra' => $this->layoutTemplateData], null);
I also thought about it. But I think it should not be allowed. 
Because it breaks whole concept of layout system.
The layout is the "end-point", just rendering, nothing more.

2024-07-26 08:26 UTC, Fedik commented on libraries/src/Mail/MailTemplate.php
> +                }
That is interesting, that could help a loot. Have a link to some example?

2024-07-26 08:35 UTC, LadySolveig commented
@HLeithner Is that what you mean by user friendly if I have to remember to adapt several templates (for each language one) individually in backend just because I want to change a mail from address for a single use case (MailTemplate), for example? ;)

2024-07-26 08:41 UTC, HLeithner commented
yeah don't care anyway please just fix the broken database query thanks

2024-07-26 09:02 UTC, brianteeman commented
I suspect most people will just be happy to have real html emails with the default layout - I know I am

2024-07-26 09:34 UTC, LadySolveig commented on administrator/components/com_mails/src/Field/MailtemplateLayoutField.php
> +            ->where('enabled = 1');
Thanks - additional #43851

2024-07-26 09:42 UTC, LadySolveig commented on libraries/src/Mail/MailTemplate.php
> +                $htmlBody = $layoutFile->render(['mail' => $htmlBody, 'extra' => $this->layoutTemplateData], null);
Is there a particular reason why you don't want to use the `onMailBeforeRendering` event for this? 
I don't see a problem here to add additional attachments and also additional data via addLayoutTemplateData. Or am I missing something here?
I don't know if I really want more logic in a layout than it needs.

2024-07-26 09:42 UTC, HLeithner commented on libraries/src/Mail/MailTemplate.php
> +                }
I only checked the phpmailer source code (I used this before so I know it's working) it only take relative urls

2024-07-26 09:44 UTC, HLeithner commented on libraries/src/Mail/MailTemplate.php
> +                $htmlBody = $layoutFile->render(['mail' => $htmlBody, 'extra' => $this->layoutTemplateData], null);
maybe it's not needed because an event exists, on the other side I use this in the template for setting the subject for example but that's a shop system that might be too complex situation.

2024-07-26 09:56 UTC, LadySolveig commented on administrator/components/com_mails/src/Field/MailtemplateLayoutField.php
> +            ->where('enabled = 1');
could you please resolve if it is ok for you now? or should I change something else?

2024-07-26 14:29 UTC, HLeithner approved these changes
thx

2024-07-26 20:27 UTC, Hackwar commented
I'm merging this even though since this was set to RTC, additional changes were made. However those changes were basically codestyle fixes and have been reviewed by me.

Thank you for your contribution @LadySolveig! This will be a great feature.

2024-07-26 21:14 UTC, merged

2024-10-07 13:31 UTC, rbuelund commented
I have tried the new main template feature, but I cannot seem to find the posibility for an override of the layout in the Cassiopeia template ?? Where should that be ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43829">issues.joomla.org/tracker/joomla-cms/43829</a>.</sub>

2024-10-07 13:55 UTC, LadySolveig commented
![grafik](https://github.com/user-attachments/assets/b2493a97-13c3-418b-b254-ac1b933ea320)
@rbuelund you can create an override directly in the backend in Cassiopeia. Use Layouts -> joomla -> mail.

2024-10-07 13:59 UTC, rbuelund commented
Ahh sorry - found it now.