[5.3] DRAFT Numbers custom fields plugin
joomla/joomla-cms pull request #43974
Opened 2024-08-24 15:18 UTC by TLWebdesign

I'm trying to create a new custom fields plugin for the standard Joomla Form Field Number. We have it for Integer and i'd like to have the same for the number field. That way w'll also gain ability to use floats. 
 
 I'm not there yet and i need help! Thats why i created this Draft PR. Hoping smarter people like here will be willing to guide me as to whats missing still. 
 
 I'm having the issue where the view of the custom field in an e.g. article is generating a list field. How and where do i fix this? It should generate a numbers field.
 
 I know i still need to add the sql but i first like to get the main code working correctly.  
 
### Summary of Changes
Extra plugin added

### Testing Instructions
You can discover the extension and then use it in custom fields. It's called numbers. 

### Actual result BEFORE applying this Pull Request
No numbers custom field available.

### Expected result AFTER applying this Pull Request
Numbers custom field available and working.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2024-08-24 17:26 UTC, brianteeman commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_INTEGER_LABEL="Number (%s)"
```suggestion
PLG_FIELDS_NUMBER_LABEL="Number (%s)"
```

2024-08-24 17:26 UTC, brianteeman commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_INTEGER_PARAMS_FIRST_LABEL="Min"
```suggestion
PLG_FIELDS_NUMBER_PARAMS_FIRST_LABEL="Min"
```

2024-08-24 17:26 UTC, brianteeman commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_INTEGER_PARAMS_LAST_LABEL="Max"
```suggestion
PLG_FIELDS_NUMBER_PARAMS_LAST_LABEL="Max"
```

2024-08-24 17:27 UTC, brianteeman commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_INTEGER_PARAMS_MULTIPLE_LABEL="Multiple"
```suggestion
PLG_FIELDS_NUMBER_PARAMS_MULTIPLE_LABEL="Multiple"
```

2024-08-24 17:27 UTC, brianteeman commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_INTEGER_PARAMS_STEP_LABEL="Step Increment"
```suggestion
PLG_FIELDS_NUMBER_PARAMS_STEP_LABEL="Step Increment"
```

2024-08-24 17:27 UTC, brianteeman commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_INTEGER_XML_DESCRIPTION="This plugin lets you create new fields of type 'number' in any extensions where custom fields are supported."
```suggestion
PLG_FIELDS_NUMBER_XML_DESCRIPTION="This plugin lets you create new fields of type 'number' in any extensions where custom fields are supported."
```

2024-08-24 17:27 UTC, brianteeman commented on plugins/fields/number/number.xml
> +
```suggestion
```

2024-08-24 17:28 UTC, brianteeman commented on plugins/fields/number/number.xml
> +
```suggestion
```

2024-08-24 17:29 UTC, brianteeman commented on plugins/fields/number/services/provider.php
> +     * @since   4.3.0
```suggestion
     * @since   __DEPLOY_VERSION__
```

2024-08-24 17:29 UTC, brianteeman commented on plugins/fields/number/src/Extension/Number.php
> + * @since  5.3.0
```suggestion
 * @since  __DEPLOY_VERSION__
```

2024-08-24 17:36 UTC, TLWebdesign commented
@brianteeman Thanks for reviewing and fixing my mistakes.

2024-08-24 20:44 UTC, brianteeman commented on plugins/fields/number/src/Extension/Number.php
> + * @copyright   (C) 2017 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
```

2024-08-24 20:44 UTC, brianteeman commented on plugins/fields/number/services/provider.php
> + * @copyright   (C) 2023 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
```

2024-08-24 20:45 UTC, brianteeman commented on plugins/fields/number/tmpl/number.php
> + * @copyright   (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright   (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
```

2024-08-25 18:40 UTC, TLWebdesign commented
So the wall i'm hitting now is that i can't figure out how the display of the custom field in an "article edit view" is set or adjusted. Looking at for instance the integer custom field it sort of automagically seems to work. Because i can't seem to find a reference anywhere in the plugin folder itself. 

Could someone point me in the right direction here?

2024-08-25 19:41 UTC, Quy commented on plugins/fields/number/tmpl/number.php
> +    $value = isset($min) ? $min : $value;
```suggestion
    $value = $min ?? '';
```

2024-08-27 09:06 UTC, sandewt commented
> I'm not there yet and i need help!

There is still some work to be done regarding the databases and the installation, see e.g.:

https://github.com/TLWebdesign/joomla-cms/blob/f9dec464683f19d5efe9699ee8745d703cea7250/installation/sql/mysql/base.sql#L296

A nice example of another plugin can be found here:
[https://github.com/joomla/joomla-cms/pull/42777/files](https://github.com/joomla/joomla-cms/pull/42777/files)

2024-09-02 08:50 UTC, HLeithner commented
This pull request has been automatically rebased to 5.3-dev.

2025-02-22 06:09 UTC, suvarnakale commented
I have tested this item :red_circle: unsuccessfully on 3d8f2bc98eda99bad39f434aba21c0f8ce8f10ba<br /><br />I have tested this item and it is not working as expected. 

For more information - On discover number field plugin is available and installable. But after onstallation, in standard joomla form the number field is not available. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43974">issues.joomla.org/tracker/joomla-cms/43974</a>.</sub>

2025-02-22 06:39 UTC, shindebalu commented
I have tested this item :red_circle: unsuccessfully on 3d8f2bc98eda99bad39f434aba21c0f8ce8f10ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43974">issues.joomla.org/tracker/joomla-cms/43974</a>.</sub>

2025-02-22 06:44 UTC, fgsw commented
@shindebalu Can you please provide the resons for your test result? Also notice that this Pull Request is a draft.

2025-03-04 17:20 UTC, HLeithner commented
This pull request has been automatically rebased to 6.0-dev.

2025-03-14 18:56 UTC, TLWebdesign commented
I think this one is ready for review. I was wondering tho;

Does anyone think it would be a good idea to implement more layouts or an option to format the number like for instance a currency? Or would that be too much and we should stick to default behaviour of the same core field type? 

I'm asking because i have a use case where i want to use this field to display prices. Would be nice if i could set the number formatting in the field settings.

2025-03-14 19:28 UTC, brianteeman commented
> Does anyone think it would be a good idea to implement more layouts or an option to format the number like for instance a currency?

like the integer field? 
![image](https://github.com/user-attachments/assets/566b41f1-e12b-4d77-8ed5-0363acfc59dc)

2025-03-15 00:22 UTC, TLWebdesign commented
> like the integer field? 

No i was thinking using https://www.php.net/manual/en/numberformatter.formatcurrency.php and either get locale from the default language or have a list of locales to select from in a dropdown list? The last one would be the "lightest" on rendering is my guess. you could also add an option for the number of fraction digits.

Or just a regular number_format and have 3 settings for currency, thousand seperator and decimal operator.

2025-03-24 14:08 UTC, TLWebdesign commented on installation/sql/postgresql/base.sql
@brianteeman Should i reorder the rest of the plugins on new install or should i add it to the bottom? I'm also doing other plugins as you read on mattermost and now it's conflicting with the order. What is the preferred way to deal with this?

2025-03-24 14:34 UTC, fgsw commented on administrator/language/en-GB/plg_fields_number.ini
Please alphasort language constants.

2025-03-24 14:36 UTC, fgsw requested changes
Please alphasort language constants.

2025-03-24 14:37 UTC, fgsw commented on administrator/language/en-GB/plg_fields_number.ini
Please alphasort language constants.

2025-03-24 14:50 UTC, TLWebdesign commented on administrator/language/en-GB/plg_fields_number.ini
OK i think i did it correctly now.

2025-03-24 15:20 UTC, QuyTon commented on plugins/fields/number/number.xml
> +				>
```suggestion
					>
```
Please repeat with other instances.

2025-03-24 16:50 UTC, TLWebdesign commented on plugins/fields/number/number.xml
> +				>
Thanks for taking time to review. I changed all occurences like you mentioned

2025-03-25 02:58 UTC, QuyTon commented on plugins/fields/number/params/number.xml
> +				name="decimals"
Please sort in this order: name, type, label, description

2025-03-25 03:10 UTC, QuyTon commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_CURRENCY_DESC="Format the number as currency?"
The description is basically the same without additional info as the label so I would remove it.

2025-03-25 03:10 UTC, QuyTon commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_CURRENCY_LABEL="Format as currency"
```suggestion
PLG_FIELDS_NUMBER_PARAMS_CURRENCY_LABEL="Format as Currency"
```

2025-03-25 03:11 UTC, QuyTon commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_DECIMALS_LABEL="Decimals"
```suggestion
PLG_FIELDS_NUMBER_PARAMS_DECIMALS_LABEL="Number of Decimals"
```

2025-03-25 03:15 UTC, QuyTon commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_SYMBOL_DESC="Symbol to put in front or after the number"
This description may not be necessary.

2025-03-25 08:49 UTC, TLWebdesign commented on plugins/fields/number/params/number.xml
> +				name="decimals"
Ok, done! Thanks

2025-03-25 08:54 UTC, TLWebdesign commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_SYMBOL_DESC="Symbol to put in front or after the number"
Which one/ I see 2 descriptions there line 20 or 22?

2025-03-25 08:54 UTC, TLWebdesign commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_CURRENCY_DESC="Format the number as currency?"
OK i removed it.

2025-04-01 11:16 UTC, TLWebdesign commented on installation/sql/postgresql/base.sql
@QuyTon could you maybe answer above question or tag someone who could answer this?

2025-04-05 05:52 UTC, QuyTon commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_SYMBOL_DESC="Symbol to put in front or after the number"
PLG_FIELDS_NUMBER_PARAMS_POSITION_DESC
PLG_FIELDS_NUMBER_PARAMS_SYMBOL_DESC

2025-04-05 05:53 UTC, QuyTon commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_MIN_DESC="This value is the lowest that can be chosen (only limits the up/down arrows)"
```suggestion
PLG_FIELDS_NUMBER_PARAMS_MAX_DESC="Maximum value that can be chosen (only limits the up/down arrows)."
PLG_FIELDS_NUMBER_PARAMS_MAX_LABEL="Max"
PLG_FIELDS_NUMBER_PARAMS_MIN_DESC="Minimum value that can be chosen (only limits the up/down arrows)."
```

2025-04-05 05:56 UTC, QuyTon commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_MIN_LABEL="Min"
```suggestion
PLG_FIELDS_NUMBER_PARAMS_MAX_DESC="Maximum value that can be chosen (only limits the up/down arrows)."
PLG_FIELDS_NUMBER_PARAMS_MAX_LABEL="Maximum"
PLG_FIELDS_NUMBER_PARAMS_MIN_DESC="Minimum value that can be chosen (only limits the up/down arrows)."
PLG_FIELDS_NUMBER_PARAMS_MIN_LABEL="Minimum"
```

2025-06-02 18:55 UTC, TLWebdesign commented on installation/sql/postgresql/base.sql
Got the info from brian so i'm closing this conversation as resolved and will update the pr as per the best practice.

2025-08-15 16:29 UTC, Bodge-IT approved these changes
Github shows 1 change request still outstanding but I've checked all these and they all seem resolved.

2025-08-15 17:21 UTC, exlemor commented
@TLWebdesign - I tested this PR, it needs at least 1 fix before I can mark it successful.

When Toggling in the back-end the Toggle Inline Help, the last field Number of Decimals has a language-string instead of text:
PLG_FIELDS_NUMBER_PARAMS_DECIMALS_DESC

ALSO, seeing that the minimum has no bearing on Saving a field with a lower number, it would be good to update the text of the Minimum field: Minimum value that can be chosen (only limits the up/down arrows). to be clearer...

Something like: User can enter any value and a minimum value that can be chosen that limits the up/down arrows.
(or whatever you prefer)

When I set my Minimum to 100000, and saved my field with 5000, it let me save with no warning (even though the minimum was 100000) but then when I used the arrows, it jumped to 100000 - this is perhaps intended but needs clearer info.

2025-08-15 18:25 UTC, brianteeman commented
Please review all the _desc strings to see if they are really needed. 

For example isnt this just obvious from the label and the field options
PLG_FIELDS_NUMBER_PARAMS_POSITION_DESC="Place the symbol before or after number"

2025-08-15 18:34 UTC, TLWebdesign commented
> Please review all the _desc strings to see if they are really needed.

Ok thanks for having a look, i removed your suggestion and another one.

2025-08-15 18:36 UTC, TLWebdesign commented
> @TLWebdesign - I tested this PR, it needs at least 1 fix before I can mark it successful.
> 
> When Toggling in the back-end the Toggle Inline Help, the last field Number of Decimals has a language-string instead of text: PLG_FIELDS_NUMBER_PARAMS_DECIMALS_DESC
> 
> ALSO, seeing that the minimum has no bearing on Saving a field with a lower number, it would be good to update the text of the Minimum field: Minimum value that can be chosen (only limits the up/down arrows). to be clearer...
> 
> Something like: User can enter any value and a minimum value that can be chosen that limits the up/down arrows. (or whatever you prefer)
> 
> When I set my Minimum to 100000, and saved my field with 5000, it let me save with no warning (even though the minimum was 100000) but then when I used the arrows, it jumped to 100000 - this is perhaps intended but needs clearer info.

The missing language string is fixed. the desc shouldn't be on this field but it was left in the form definition. 

For the language, it already states this in the description the same way as the official documentation does. So i'd like to just keep it consistent with that.

2025-08-15 20:11 UTC, exlemor commented
I have tested this item :white_check_mark: successfully on b89199b5bdb6a61a1a36d7521e411b72f1ebf515<br /><br />I have tested this successfully! Thanks @TLWebdesign for the fixes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43974">issues.joomla.org/tracker/joomla-cms/43974</a>.</sub>

2025-08-16 08:44 UTC, brianteeman commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_STEP_DESC="If a user click up/down arrow current value will change by this attribute (this attribute value will be added or subtracted to current field value)"
is this really needed?

If you think it is then please follow the guide and end the sentence with a period

2025-08-16 09:14 UTC, TLWebdesign commented on administrator/language/en-GB/plg_fields_number.ini
> +PLG_FIELDS_NUMBER_PARAMS_STEP_DESC="If a user click up/down arrow current value will change by this attribute (this attribute value will be added or subtracted to current field value)"
Hmm figured it would not hurt. But really needed. probably not, so i removed it 👍

2025-08-16 14:02 UTC, exlemor commented
I have tested this item :white_check_mark: successfully on 8e8f3e2c1c2e0054047e9f85a74e69c209fc52b4<br /><br />I have re-tested this successfully. Thanks @TLWebdesign <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43974">issues.joomla.org/tracker/joomla-cms/43974</a>.</sub>

2025-08-16 14:56 UTC, LadySolveig commented
I have tested this item :white_check_mark: successfully on 8e8f3e2c1c2e0054047e9f85a74e69c209fc52b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43974">issues.joomla.org/tracker/joomla-cms/43974</a>.</sub>

2025-08-16 16:06 UTC, richard67 commented
@TLWebdesign Could you rename the update SQL scripts to something newer than "6.0.0-2025-08-02.sql", e.g. "6.0.0-2025-08-17.sql? Thanks in advance.

2025-08-16 16:10 UTC, richard67 commented
P.S. If the name of the new update SQL script is not newer than the latest present one when compared with PHP version compare, it will not run when updating e.g. from 6.0.0-alpha3.

2025-08-16 16:16 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/6.0.0-2024-08-24.sql
> +(0, 'plg_fields_number', 'plugin', 'number', 'fields', 0, 1, 1, 0, 1, '', '{"min":"1.0","max":"100.0","step":"0.1","currency":"0","position":"0","decimals":"2"}', '', 17, 0);
```suggestion
(0, 'plg_fields_number', 'plugin', 'number', 'fields', 0, 1, 1, 0, 1, '', '{"min":"1.0","max":"100.0","step":"0.1","currency":"0","position":"0","decimals":"2"}', '', -1, 0);
```
New plugins should be installed on update with order number -1 so they are shown at the top.

2025-08-16 16:16 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/6.0.0-2024-08-24.sql
> +(0, 'plg_fields_number', 'plugin', 'number', 'fields', 0, 1, 1, 0, 1, '', '{"min":"1.0","max":"100.0","step":"0.1","currency":"0","position":"0","decimals":"2"}', '', 17, 0);
And the script has to be renamed, see my other comment in the main thread.

2025-08-16 16:17 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/6.0.0-2024-08-24.sql
> +(0, 'plg_fields_number', 'plugin', 'number', 'fields', 0, 1, 1, 0, 1, '', '{"min":"1.0","max":"100.0","step":"0.1","currency":"0","position":"0","decimals":"2"}', '', 17, 0);
```suggestion
(0, 'plg_fields_number', 'plugin', 'number', 'fields', 0, 1, 1, 0, 1, '', '{"min":"1.0","max":"100.0","step":"0.1","currency":"0","position":"0","decimals":"2"}', '', -1, 0);
```
New plugins should be installed on update with order number -1 so they are shown at the top.

2025-08-16 16:42 UTC, TLWebdesign commented on administrator/components/com_admin/sql/updates/mysql/6.0.0-2024-08-24.sql
> +(0, 'plg_fields_number', 'plugin', 'number', 'fields', 0, 1, 1, 0, 1, '', '{"min":"1.0","max":"100.0","step":"0.1","currency":"0","position":"0","decimals":"2"}', '', 17, 0);
ok name is changed. Thansk for looking at this.

2025-08-16 16:46 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/6.0.0-2024-08-24.sql
> +(0, 'plg_fields_number', 'plugin', 'number', 'fields', 0, 1, 1, 0, 1, '', '{"min":"1.0","max":"100.0","step":"0.1","currency":"0","position":"0","decimals":"2"}', '', 17, 0);
No, the name is not changes. Please check again it is 2024!!!

2025-08-16 16:49 UTC, TLWebdesign commented on administrator/components/com_admin/sql/updates/mysql/6.0.0-2024-08-24.sql
> +(0, 'plg_fields_number', 'plugin', 'number', 'fields', 0, 1, 1, 0, 1, '', '{"min":"1.0","max":"100.0","step":"0.1","currency":"0","position":"0","decimals":"2"}', '', 17, 0);
Sorry thought i pushed the change. At the ER with my kid atm waiting. Things are a bit hectic.

2025-08-16 16:53 UTC, exlemor commented
I have tested this item :white_check_mark: successfully on 3044c1576f08bd473c38b3b23ac6818c65904688<br /><br />I have re-tested this successfully. Thanks @TLWebdesign <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43974">issues.joomla.org/tracker/joomla-cms/43974</a>.</sub>

2025-08-16 16:53 UTC, richard67 commented
Filenames "6.0.0-2024-08-24.sql" are still wrong. Please rename to "6.0.0-2025-08-17.sql". Mind also the year!

2025-08-16 16:53 UTC, richard67 commented
Sorry, wrong button.

2025-08-16 16:57 UTC, richard67 commented
@exlemor Have you also tested updating from 6.0.0-alpha3? Then you would have noticed that the field will not be added on update due to the wrong update SQL script name.

For PRs which add new update SQL scripts updating should always be part of the test.

@TLWebdesign Maybe you should update the testing instructions accordingly.

2025-08-16 17:04 UTC, richard67 commented
Filenames "6.0.0-2024-08-24.sql" are still wrong. Please rename to "6.0.0-2025-08-17.sql". Mind also the year!

2025-08-16 17:09 UTC, TLWebdesign commented
> Filenames "6.0.0-2024-08-24.sql" are still wrong. Please rename to "6.0.0-2025-08-17.sql". Mind also the year!

sorry in the rush to get going here i didn't wait long enough for my laptop to commit the renaming. but i see it is done now. Thanks for your help

2025-08-16 17:10 UTC, richard67 commented
I will set RTC as it had 2 tests.

@Bodge-IT @softforge When this and the other one with the other field gets merged before beta 1, then we (or you) have to test if updating still works on MySQL and PostgreSQL. I will try to find time for that tomorrow morning, at least for the PostgreSQL part.

2025-08-16 17:12 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43974">issues.joomla.org/tracker/joomla-cms/43974</a>.</sub>

2025-08-16 17:27 UTC, richard67 commented
I will solve the conflicts in the base.sql now.

2025-08-16 17:30 UTC, richard67 commented
Done.

2025-08-16 18:09 UTC, merged

2025-08-16 18:11 UTC, Bodge-IT commented
Thanks @TLWebdesign, well done.  Thanks for all the tests