[5.3] Refactoring views to directly call models (installation & API)
joomla/joomla-cms pull request #44169
Opened 2024-09-30 12:53 UTC by Hackwar

### Summary of Changes
This PR refactors the views to get the model object and then directly call the methods of the model instead of going through the `View::get()` indirection. This refactors the views of the Joomla installation and of the web API.

### Testing Instructions
Everything should work the same.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

2024-10-01 09:48 UTC, HLeithner requested changes

2024-10-01 09:48 UTC, HLeithner commented on api/components/com_config/src/View/Component/JsonapiView.php
> +            $component = ComponentHelper::getComponent($this->component_name);
Can you please define the variable here as "public" or find a better solution?
because `component_name` is set by the controller with the `LegacyPropertyManagementTrait::set` method, which sets the property dynamic, as alternative a `setComponentName()` is needed which sets a protected/private property.

2024-10-01 10:31 UTC, Hackwar commented on api/components/com_config/src/View/Component/JsonapiView.php
> +            $component = ComponentHelper::getComponent($this->component_name);
So, after all this refactoring we still have some cases where set and get are used outside of the HtmlView.php files. To me that is another PR. Quite frankly, in this case I would rather revert this line and do that in another PR as well to not delay merging the rest. Would that be okay?

2024-10-01 17:13 UTC, Quy commented on installation/src/View/DefaultView.php
> +        $model      = $this->getModel();
```suggestion
        $model = $this->getModel();
```

2024-10-02 10:06 UTC, rdeutz commented on api/components/com_config/src/View/Component/JsonapiView.php
> +            $component = ComponentHelper::getComponent($this->component_name);
revert is fine by me

2024-10-02 10:06 UTC, rdeutz approved these changes

2024-10-03 21:18 UTC, Hackwar commented on api/components/com_config/src/View/Component/JsonapiView.php
> +            $component = ComponentHelper::getComponent($this->component_name);
Done.

2024-10-10 05:36 UTC, laoneo commented
@HLeithner can you have another look here and approve as it can't be merged right now.

2024-10-10 08:17 UTC, HLeithner approved these changes

2024-10-10 08:18 UTC, merged