atum light mode - Fix modal window link color
joomla/joomla-cms pull request #44176
Opened 2024-10-01 12:51 UTC by RickR2H

Pull Request for Issue # .

### Summary of Changes
With the browser in dark modus, In the backend (Atum template) the links have the wrong color when the template is toggled to the light modus. The reason is that in the component.php only the dark color scheme colors are loaded if the browser is is dark mode. My fix will make sure that the correct colors are used, depending or the color scheme selected.

### Testing Instructions
Set the browser you are using in dark mode.
In the backend from Joomla select from the User Menu in the top right the link: Light/Dark Mode, and switch the template to light mode.
Open a modal. This can be done by opening an article and selecting the Created By button in the Publishing tab.
![image](https://github.com/user-attachments/assets/5d55f192-fb24-40f9-a8b0-29e50c134b4b)

### Actual result BEFORE applying this Pull Request
The link is to light which is a accessibility issue.
![image](https://github.com/user-attachments/assets/0d286291-6bcc-479d-ab37-f091a06db0c4)

### Expected result AFTER applying this Pull Request
The link has the correct color.
![image](https://github.com/user-attachments/assets/45f338f5-fac2-42f2-a2fd-13b897bd1125)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2024-10-01 14:57 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on 61500560b6faf9d79d8c2e400cdaabc0363f118f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44176">issues.joomla.org/tracker/joomla-cms/44176</a>.</sub>

2024-10-01 15:30 UTC, brianteeman commented
Please also check #43708

2024-10-01 17:39 UTC, richard67 commented
@RickR2H Adding the `// phpcs:disable PSR1.Files.SideEffects` hasn't helped. I think the issue is not the `defined('_JEXEC') or die;` but the function definition here: https://github.com/joomla/joomla-cms/pull/44176/files#diff-3538b524e6cf4f442f5ca0631475c0ef2b867edbcb23a24b5deb2248c428e252R35-R42 . Maybe it needs to wrap that with `// phpcs:disable PSR1.Files.SideEffects` and `// phpcs:enable PSR1.Files.SideEffects`?

2024-10-02 04:22 UTC, fgsw commented
@RickR2H Can you add ```[5.2]``` to the title so user don't have to open the Pull Request to know which branche it is for?

2024-10-02 04:51 UTC, richard67 commented
I‘ve restored the previous human test result as the changes after that were only hints for PHPCS.

2024-10-02 04:53 UTC, richard67 commented
@RickR2H Please don’t do unnecessary branch Updates if there are no conflicts as the branch update invalidates the human test counter and I cannot watch your PR all day long to restore the tests.

2024-10-02 06:58 UTC, dgrammatiko requested changes

2024-10-02 06:58 UTC, dgrammatiko commented on administrator/templates/atum/component.php
> +// phpcs:disable PSR1.Files.SideEffects
If you move the function before line 29 you probably don't need to disable the checker. You're using a function before declaring it (JS has hoisting but I don't think PHP does thus my comment)

2024-10-02 08:07 UTC, RickR2H commented on administrator/templates/atum/component.php
> +// phpcs:disable PSR1.Files.SideEffects
Will try that. Thanks!

2024-10-02 09:34 UTC, RickR2H commented
@dgrammatiko @richard67 I can't get drone to behave... Any tips?

2024-10-02 13:10 UTC, richard67 commented
> @dgrammatiko @richard67 I can't get drone to behave... Any tips?

With the previous version with my proposal it was ok. So I suggest to wrap the method again into the `// phpcs:disable PSR1.Files.SideEffects` and `// phpcs:enable PSR1.Files.SideEffects`.

2024-10-02 13:26 UTC, richard67 commented on administrator/templates/atum/component.php
> +
I wouldn't move that function back down to after the place where it's called first time like you did with your latest commit.

2024-10-02 13:30 UTC, dgrammatiko commented on administrator/templates/atum/component.php
> +
PHP is fine assigning a function to a variable? if so try that

2024-10-03 09:18 UTC, RickR2H commented on administrator/templates/atum/component.php
> +
Looks like drone is okay now. If you all don't mind, I'll like to keep it as is for now.

2024-10-06 09:10 UTC, fgsw commented
I have tested this item :white_check_mark: successfully on c21bf325d7b6ce7e8d0f8dcaa573402b61bbebea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44176">issues.joomla.org/tracker/joomla-cms/44176</a>.</sub>

2024-10-06 09:40 UTC, richard67 commented on administrator/templates/atum/component.php
> +// phpcs:enable PSR1.Files.SideEffects
```suggestion
defined('_JEXEC') or die;
```
PHPCS would also be happy without that.

2024-10-06 09:43 UTC, richard67 commented on administrator/templates/atum/component.php
> +$linkColorDarkHvr = sprintf("%d, %d, %d", $lighterRd, $lighterGd, $lighterBd);
```suggestion

$adjustColorLightness = function ($r, $g, $b, $percent) {
    $adjust = function ($color) use ($percent) {
        $newColor = $color + ($color * $percent / 100);
        return min(max(0, $newColor), 255);
    };
    return [$adjust($r), $adjust($g), $adjust($b)];
}

list($lighterRd, $lighterGd, $lighterBd) = $adjustColorLightness($rd, $gd, $bd, 10);
$linkColorDarkHvr = sprintf("%d, %d, %d", $lighterRd, $lighterGd, $lighterBd);
```
In this way PHPCS would accept it without the `// phpcs:disable PSR1.Files.SideEffects`.

2024-10-06 10:37 UTC, richard67 commented on administrator/templates/atum/component.php
> +$linkColorDarkHvr = sprintf("%d, %d, %d", $lighterRd, $lighterGd, $lighterBd);
P.S.: I've tested my 2 suggestions here and they work, and both our PHPCS checkers are happy with it, too.

2024-10-07 15:55 UTC, ChristineWk commented
I have tested this item :white_check_mark: successfully on c21bf325d7b6ce7e8d0f8dcaa573402b61bbebea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44176">issues.joomla.org/tracker/joomla-cms/44176</a>.</sub>

2024-10-07 16:33 UTC, richard67 commented
@RickR2H Could you check my 2 suggestions for how to get rid of these PHPCS hints? It would not need new human tests if you apply them.

2024-10-08 08:12 UTC, RickR2H commented on administrator/templates/atum/component.php
> +// phpcs:enable PSR1.Files.SideEffects
Removed the tags

2024-10-08 08:13 UTC, C-Lodder commented
Why use PHP to manipulate CSS colours, when this can be acheived in native CSS with 1 line of code?

2024-10-08 13:31 UTC, dgrammatiko commented
> Why use PHP to manipulate CSS colours, when this can be acheived in native CSS with 1 line of code?

Because BS is using a css var of type `number, number, number` : 
https://github.com/twbs/bootstrap/blob/fee9dc2438736a02405412e10ea8445dd9aeac1e/dist/css/bootstrap.css#L40-L47

2024-10-08 13:39 UTC, richard67 commented
I've restored the previous human test results in the issue tracker as the commits which have invalidated the test count were only related to making PHPCS happy. In addition I have tested that the PR still works with the last change to an anonymous function.

2024-10-08 13:40 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44176">issues.joomla.org/tracker/joomla-cms/44176</a>.</sub>

2024-10-08 14:11 UTC, C-Lodder commented
@dgrammatiko https://jsfiddle.net/e5arm7db ?

2024-10-08 14:15 UTC, RickR2H commented
> @dgrammatiko https://jsfiddle.net/e5arm7db ?

Could be a nice option to replace the current functions. More clean! For now the the colors nor loading issues is fixed. This is a nice option to add with a new PR. Some logic is used in the index.php

2024-10-08 14:20 UTC, dgrammatiko commented
July 2024 might be too soon:
https://caniuse.com/css-relative-colors
<img width="966" alt="Screenshot 2024-10-08 at 5 13 54 PM" src="https://github.com/user-attachments/assets/c9383c9e-8cd0-4b6f-a667-fca5078f8272">

Anyways if the maintainers are ok with it, go for it, it's not my call. I just pointed that the BS requires a weird value and that the relative color from is a new addition 🤷‍♂️

2024-10-13 11:46 UTC, richard67 commented
@RickR2H To be honest, to me the hover colour seems to be inconsistent now when comparing dark mode and light mode.

In light mode it is still black with your PR, so when changing to dark mode I would expect it to be white.

Or vice versa, when coming from dark mode where it is light blue with your PR, and changing to light mode, I would expect it to be some other kind of blue but not black.

But maybe that's just me.

2024-10-15 12:12 UTC, RickR2H commented
I guess there will be a better solution. I have no clue why the values have to calculated. We can make then fixed variables which is a better option. Probably is has to do with the backend colors...

2024-10-15 12:34 UTC, dgrammatiko commented
> I have no clue why the values have to calculated.

The blame here goes to Bootstrap, they store the rgb values as a coma separated val: `--bs-dark-rgb: 33, 37, 41;` https://github.com/twbs/bootstrap/blob/fee9dc2438736a02405412e10ea8445dd9aeac1e/dist/css/bootstrap.css#L40-L47

> Probably is has to do with the backend colors...

Nope, search the bs css and you'll see how these values are used

> I guess there will be a better solution.

What Charlie suggested but the browser support is only few months...

2024-10-30 18:30 UTC, wilsonge commented
This is consistent with index.php so I'd merge this if it fixes the bug - then at least if we ever change to @C-Lodder 's way in the future (j6 or whatever) then we can do it consistently. Only thing I'd suggest is that we have this the error_login.php and error_full.php too so we have the same set of css variables in all 3 files.

2024-11-07 08:30 UTC, merged

2024-11-07 08:35 UTC, pe7er commented
Thanks @RickR2H !

2024-11-07 08:42 UTC, dgrammatiko commented
> Only thing I'd suggest is that we have this the error_login.php and error_full.php too so we have the same set of css variables in all 3 files.

@RickR2H please do another PR with the same code covering the other 2 files @wilsonge mentioned. Thanks