Fix password toggle in dynamic subform field
joomla/joomla-cms pull request #44362
Opened 2024-10-27 17:33 UTC by MatMyfta

Pull Request for Issue #43240 .

### Summary of Changes

Implemented a new DOM change event that activates the password toggle (show/hide) functionality, allowing it to operate effectively for both dynamic and static form fields.

### Testing Instructions

described in the issue.

### Actual result BEFORE applying this Pull Request

described in the issue.

### Expected result AFTER applying this Pull Request

The password toggle function now operates as expected, enabling correct visibility control for password fields in dynamic subforms.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2024-10-28 06:45 UTC, dgrammatiko requested changes

2024-10-28 06:45 UTC, dgrammatiko commented on build/media_source/system/js/fields/passwordview.es6.js
> +  document.addEventListener('domChanged', () => {
You don't have to setup a mutation observer here, as the repeatable form field has it's own event: https://github.com/joomla/joomla-cms/blob/2d4547ea621e84408cbae8e20db9b05e192ca34f/build/media_source/system/js/fields/color-field-adv-init.es5.js#L33-L36

2024-10-28 14:15 UTC, MatMyfta commented on build/media_source/system/js/fields/passwordview.es6.js
> +  document.addEventListener('domChanged', () => {
Thank you for the feedback.
I have tested the code using this event and works. 

I'm  updating now.

2024-10-28 14:15 UTC, dgrammatiko commented on build/media_source/system/js/fields/passwordview.es6.js
> +  document.addEventListener('joomla:updated', () => {
Assign the function directly 
```
document.addEventListener('joomla:updated', togglePassword);
```

2024-11-07 13:51 UTC, Quy commented
I have tested this item :white_check_mark: successfully on 8aacd6f2e797f2741676db243f8140980030f259<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44362">issues.joomla.org/tracker/joomla-cms/44362</a>.</sub>

2024-11-10 12:26 UTC, viocassel commented
I have tested this item :white_check_mark: successfully on 8aacd6f2e797f2741676db243f8140980030f259<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44362">issues.joomla.org/tracker/joomla-cms/44362</a>.</sub>

2024-11-10 20:58 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44362">issues.joomla.org/tracker/joomla-cms/44362</a>.</sub>

2024-11-14 08:21 UTC, merged

2024-11-14 08:21 UTC, Hackwar commented
Thank you for your contribution!

2024-11-27 10:41 UTC, brianteeman commented
Just in case someone else comes across this - you may need to re-create any mod_logged overrides - i did

2024-11-28 16:00 UTC, brianteeman commented
I see now that this also breaks global config.