[5.3] Replace InstallerScript class with a trait
joomla/joomla-cms pull request #44381
Opened 2024-10-30 21:34 UTC by bembelimen

### Summary of Changes
This implements a trait to be used in combination with the [InstallerScriptInterface](https://github.com/joomla/joomla-cms/blob/5.3-dev/libraries/src/Installer/InstallerScriptInterface.php)

### Testing Instructions
I have no real idea, how to test it. You need an Extension using a install script with the InstallerScriptInterface. Using this trait should resolve the interface and give you some additional options like:

you can set
- a minimum PHP version which is required
- a minimum Joomla! version which is required
- files to be removed
- creating a dashboard menu onthefly

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

2024-10-31 07:06 UTC, laoneo commented on libraries/src/Installer/InstallerScriptTrait.php
> +    protected function addDashboardMenu(string $dashboard, string $preset)
If you create a module, then the function name should probably be changed.

2024-10-31 07:06 UTC, laoneo commented on libraries/src/Installer/InstallerScriptTrait.php
> +        $manifestPath = $this->getPath($pathname) . '/' . $this->getPath('manifest');
Needs an abstract function getPath.

2024-10-31 07:06 UTC, laoneo commented on libraries/src/Installer/InstallerScriptTrait.php
> +            Factory::getApplication()->enqueueMessage(Text::sprintf('JLIB_INSTALLER_ERROR_COMP_INSTALL_FAILED_TO_CREATE_DASHBOARD', $model->getError()));
Would be nice to have a set/getApplication function instead using the one from the factory.

2024-10-31 07:07 UTC, laoneo commented
In general I'm not sure if the trait is the right approach. I would prefer a base class.

2024-10-31 08:44 UTC, bembelimen commented on libraries/src/Installer/InstallerScriptTrait.php
> +        $manifestPath = $this->getPath($pathname) . '/' . $this->getPath('manifest');
Fixed, thanks!

2024-11-01 10:16 UTC, wilsonge commented
What's the value of deprecating and forcing people to move. I mean I'm not fussed whether we use a base class or a trait to be honest - but I don't see the value of just deprecating and moving to the other one forcing code changes for next to no benefit.

2024-11-04 07:16 UTC, HLeithner commented
I miss an interface for this trait and I would replace the string type with an enum.

I think the goal is to get type safety with out b/c break.

2024-11-04 08:11 UTC, laoneo commented
The [interface exists](https://github.com/joomla/joomla-cms/blob/5.2-dev/libraries/src/Installer/InstallerScriptInterface.php) already, but I couldn't change the InstallerClass without braking bc at the time I made it.

2025-03-03 11:06 UTC, bembelimen commented on libraries/src/Installer/InstallerScriptTrait.php
> +    protected function addDashboardMenu(string $dashboard, string $preset)
Done, thx

2025-03-04 17:19 UTC, HLeithner commented
This pull request has been automatically rebased to 6.0-dev.

2025-04-18 13:31 UTC, bembelimen commented
> The [interface exists](https://github.com/joomla/joomla-cms/blob/5.2-dev/libraries/src/Installer/InstallerScriptInterface.php) already, but I couldn't change the InstallerClass without braking bc at the time I made it.

Hi @laoneo any suggestion how to do this in the trait without causing a lot of hassle for the developer? I guess we have no applicationaware trait yet... If you have a good idea, feel free to create a PR against the branch to improve.

2025-04-18 13:31 UTC, bembelimen commented on libraries/src/Installer/InstallerScriptTrait.php
> +            Factory::getApplication()->enqueueMessage(Text::sprintf('JLIB_INSTALLER_ERROR_COMP_INSTALL_FAILED_TO_CREATE_DASHBOARD', $model->getError()));
Hi @laoneo any suggestion how to do this in the trait without causing a lot of hassle for the developer? I guess we have no applicationaware trait yet... If you have a good idea, feel free to create a PR against the branch to improve.

2025-04-26 09:47 UTC, HLeithner requested changes, later dismissed
I made some annotations maybe can comment on them.

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +        return $this->customPreflight($type, $adapter);
I wouldn't do this at all. I would suggest to use trait method rename function instead.

https://3v4l.org/UuJal

```suggestion
        return true;
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +        return $this->customPostflight($type, $adapter);
same as above

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +            Factory::getApplication()->enqueueMessage(Text::sprintf('JLIB_INSTALLER_ERROR_COMP_INSTALL_FAILED_TO_CREATE_DASHBOARD', $model->getError()));
you already use $this->getApplication() in line 331 above.

In my installer script I get the application from the container and set it in the constructor, but I didn't find out where it is set by a quick review.

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +    protected $extension;
```suggestion
    protected string $extension;
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +    protected $minimumPhp;
```suggestion
    protected string $minimumPhp;
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +    protected $minimumJoomla;
```suggestion
    protected string $minimumJoomla;
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +    protected $allowDowngrades = false;
```suggestion
    protected bool $allowDowngrades = false;
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +    protected $deleteFiles = [];
```suggestion
    protected array $deleteFiles = [];
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +    protected $deleteFolders = [];
```suggestion
    protected array $deleteFolders = [];
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +    private $application;
```suggestion
    private CMSApplicationInterface $application;
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +            Factory::getApplication()->enqueueMessage(Text::sprintf('JLIB_INSTALLER_ERROR_COMP_INSTALL_FAILED_TO_CREATE_DASHBOARD', $model->getError()));
```suggestion
            $this->getApplication()->enqueueMessage(Text::sprintf('JLIB_INSTALLER_ERROR_COMP_INSTALL_FAILED_TO_CREATE_DASHBOARD', $model->getError()));
```

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +                if (is_dir(Path::check(JPATH_ROOT . $folder)) && !Folder::delete(JPATH_ROOT . $folder)) {
Folder::delete throw a FilesystemException exception which is not handled here.

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +                if (is_file(Path::check(JPATH_ROOT . $file)) && !File::delete(JPATH_ROOT . $file)) {
File::delete throw a FilesystemException exception which is not handled here.

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +        $module['access'] = (int) Factory::getApplication()->get('access', 1);
```suggestion
        $module['access'] = (int) $this->getApplication()->get('access', 1);
```
maybe refactory to a local $app variable?

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +        }
I'm missing database require checks. Should we add them?
mysql, maria, postgres

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +
```suggestion
```
remove this and use "trait method as" feature

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +    }
```suggestion
```

remove this and use "trait method as" feature

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +use Joomla\CMS\Factory;
```suggestion
```

can be removed when not longer needed

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +        $client = ApplicationHelper::getClientInfo(1);
```suggestion
        $client = ApplicationHelper::getClientInfo('administrator', true);
```

no magic numbers please, also I think we should introduce a `ApplcationEnum` (out of scope for this PR)

2025-04-26 09:47 UTC, HLeithner commented on libraries/src/Installer/InstallerScriptTrait.php
> +        $pathname = 'extension_' . ($client ? $client->name : 'root');
can ist be possible that client returns a null object? I mean we use a constant above.

2025-04-26 16:04 UTC, bembelimen commented on libraries/src/Installer/InstallerScriptTrait.php
> +        return $this->customPostflight($type, $adapter);
```suggestion
```

2025-04-26 16:05 UTC, bembelimen commented on libraries/src/Installer/InstallerScriptTrait.php
> +            Factory::getApplication()->enqueueMessage(Text::sprintf('JLIB_INSTALLER_ERROR_COMP_INSTALL_FAILED_TO_CREATE_DASHBOARD', $model->getError()));
```suggestion
            $this->getApplication()->enqueueMessage(Text::sprintf('JLIB_INSTALLER_ERROR_COMP_INSTALL_FAILED_TO_CREATE_DASHBOARD', $model->getError()));
```

2025-04-26 16:06 UTC, bembelimen commented on libraries/src/Installer/InstallerScriptTrait.php
> +    }
```suggestion
        $this->removeFiles();
        
        return true;
    }
```

2025-08-16 14:38 UTC, softforge commented on libraries/src/Installer/InstallerScriptTrait.php
> +        }
Would that be a problem if there are none standard drivers? I would say its a no , because it could be that there are individual drivers which are mysqli compatible, they would be excluded

2025-08-16 14:41 UTC, softforge commented on libraries/src/Installer/InstallerScriptTrait.php
> +                if (is_file(Path::check(JPATH_ROOT . $file)) && !File::delete(JPATH_ROOT . $file)) {
The original script doesn't either: https://github.com/joomla/joomla-cms/blob/f5ed7d2150bfc0ebb41c76f1a3061c5a21c0fcc9/libraries/src/Installer/InstallerScript.php#L321So its not changing behaviour

2025-08-16 14:43 UTC, softforge commented on libraries/src/Installer/InstallerScriptTrait.php
> +                if (is_dir(Path::check(JPATH_ROOT . $folder)) && !Folder::delete(JPATH_ROOT . $folder)) {
Same as above, the original doesnt so Im not sure we can block for that reason, but worth noting and seeing if this can be improved

2025-08-16 14:46 UTC, brianteeman commented on libraries/src/Installer/InstallerScriptTrait.php
> + * @copyright  (C) 2024 Open Source Matters, Inc. <https://www.joomla.org>
```suggestion
 * @copyright  (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
```

2025-08-16 14:49 UTC, brianteeman commented
Shouldn't there be the option to set dB requirements

2025-08-16 14:57 UTC, softforge commented
> Shouldn't there be the option to set dB requirements

It's not in the original, but it would be a nice improvement

2025-08-16 15:10 UTC, merged

2025-08-16 15:11 UTC, softforge commented
Thank you for the work on this, and for the testers adn reviewers who pointed out some improvements that can be made