[5.3] Fix author not being updated in Tagged Item upon saving article
joomla/joomla-cms pull request #44571
Opened 2024-12-03 13:10 UTC by janschoenherr

Currently, when saving an article, the `core_created_user_id` and `core_created_by_alias` fields are not updated in the corresponding entry in the `#__ucm_content` table.

### Summary of Changes

Add both fields to the fields_mapping column in the `#__content_types` table for articles.

### Testing Instructions

Change the author (Created By) of an article. Take a look at the corresponding entry in the `#__ucm_content` table.

### Actual result BEFORE applying this Pull Request

`core_created_user_id` and `core_created_by_alias` are not updated.

### Expected result AFTER applying this Pull Request

`core_created_user_id` and `core_created_by_alias` are updated.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

2024-12-03 13:51 UTC, brianteeman commented
Does this also need an update sql? Otherwise the changes will only be for new installs

2024-12-03 14:29 UTC, janschoenherr commented
You are probably right. I will check it out.

2024-12-03 14:53 UTC, janschoenherr commented
I added the update sql files. I am not sure about the postgresql syntax. Can someone confirm, that it works?

2024-12-04 07:55 UTC, fgsw commented
I have tested this item :white_check_mark: successfully on 34893cfde0a0725fe98eac70030dcd28abc9ac0f<br /><br />Test by using Prebuilt package at mono- and multilanguage Site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44571">issues.joomla.org/tracker/joomla-cms/44571</a>.</sub>

2025-01-23 12:45 UTC, richard67 commented
@janschoenherr Could you rename your update SQL script? Currently they are named "5.3.0-2024-12-03.sql", but meanwhile we have something newer with "5.3.0-2024-12-19.sql" in the 5.3-dev branch, so your scripts should have a newer date than that, at least "5.3.0-2024-12-20.sql", but maybe better take the date of today and use "5.3.0-2025-01-23.sql".

Thanks in advance.

2025-01-23 15:20 UTC, janschoenherr commented
> @janschoenherr Could you rename your update SQL script? Currently they are named "5.3.0-2024-12-03.sql", but meanwhile we have something newer with "5.3.0-2024-12-19.sql" in the 5.3-dev branch, so your scripts should have a newer date than that, at least "5.3.0-2024-12-20.sql", but maybe better take the date of today and use "5.3.0-2025-01-23.sql".
> 
> Thanks in advance.

✅

2025-01-25 13:00 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/5.3.0-2025-01-23.sql
> +WHERE "type_alias" = 'com_content';
```suggestion
WHERE "type_alias" = 'com_content.article';

```

2025-01-25 13:09 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/5.3.0-2025-01-23.sql
> +WHERE "type_alias" = 'com_content';
Unfortunately the complete statement produces an error `multiple assignments to same column "field_mappings"` on PostgreSQL because the same column shall be modified 2 times with the same SQL. On MySQL there is no syntax error, but the same applies also there: We can modify the column with one single call to JSON_SET or jsonb_set by providing the path and value pairs in an array.

See https://dev.mysql.com/doc/refman/8.4/en/json-modification-functions.html#function_json-set and https://www.postgresql.org/docs/17/functions-json.html . I might provide a change suggestion for that later.

2025-01-25 13:13 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/5.3.0-2025-01-23.sql
> +WHERE "type_alias" = 'com_content';
Or maybe better: We split the update statements up into 2, one for each path value pair. I will make a change suggestion for each update SQL file.

2025-01-25 13:15 UTC, richard67 commented on administrator/components/com_admin/sql/updates/mysql/5.3.0-2025-01-23.sql
> +WHERE `type_alias` = 'com_content.article';
```suggestion
UPDATE `#__content_types`
SET `field_mappings` = JSON_SET(`field_mappings`, '$.common.core_created_user_id', 'created_by'),
WHERE `type_alias` = 'com_content.article';

UPDATE `#__content_types`
SET `field_mappings` = JSON_SET(`field_mappings`, '$.common.core_created_by_alias', 'created_by_alias')
WHERE `type_alias` = 'com_content.article';
```
We should use separate update stamenets for each modification to avoid issues and to be in synch with PostgreSQL where we have to do that to avoid an SQL error.

2025-01-25 13:18 UTC, richard67 commented on administrator/components/com_admin/sql/updates/postgresql/5.3.0-2025-01-23.sql
> +WHERE "type_alias" = 'com_content';
```suggestion
UPDATE "#__content_types"
SET "field_mappings" = jsonb_set("field_mappings"::jsonb, '{common, core_created_user_id}' , '"created_by"', true)
WHERE "type_alias" = 'com_content';

UPDATE "#__content_types"
SET "field_mappings" = jsonb_set("field_mappings"::jsonb, '{common, core_created_by_alias}' , '"created_by_alias"', true)
WHERE "type_alias" = 'com_content';
```
We should use separate update statements for each modification to avoid an SQL error `multiple assignments to same column "field_mappings"`.

2025-01-25 13:28 UTC, richard67 requested changes
See my suggested changes for the update SQL scripts.

2025-01-27 11:04 UTC, richard67 approved these changes

2025-05-04 05:18 UTC, fgsw commented
Prebuilt packages are not available for download.

2025-05-04 05:43 UTC, fgsw commented
Something wrong in prebuilt packages:

![Untitled](https://github.com/user-attachments/assets/3d7d8876-c9cd-4693-af05-7203f3deaff0)

2025-08-12 11:21 UTC, Sulpher commented
As a user I'd like to leave a small comment: this feature is needed for correct using Tags layout in Yootheme Pro page builder. E.g. there is a menu item 'Compact list of tagged items' and it would be very useful to display a name of a user assigned to the article as the author despite the fact the original content was created by admin. 

Here is what we can get on blog category page using user fields (avatar):
<img width="1397" height="865" alt="2025-08-10-09-59-26" src="https://github.com/user-attachments/assets/97bb5301-e011-416d-a887-2dbffa94f9cc" />
There are different authors assigned to the articles and their avatars.

And here is what we get on tagged items page:
<img width="1362" height="659" alt="2025-08-10-09-59-33" src="https://github.com/user-attachments/assets/8fb8cd9e-eb79-4af5-9170-37a851f3588b" />
Original author who created the articles.

This PR could help in such situation for many users and I hope this PR will be noticed someday and accepted.
Thanks for attention.

2025-08-12 11:34 UTC, richard67 commented
@Sulpher I've updated this PR so it is ready for testing again. If you want to bring it forward, please test it and submit the test result in the issue tracker here by using the blue "Text this" button at the top-left corner.

A test should be to make a new installation with this PR to see if the changes in the base.sql are right, and another test should be made to update an existing 5.3.x to the patched package created by Drone for this PR to see if the update SQL script is run and has no errors.

Thanks in advance.

2025-08-12 11:35 UTC, richard67 commented
P.S. It might come too late for the upcoming 5.3.3 as this is already in preparation, but it still makes sense to bring it forward so it can go into 5.3.4.

2025-08-12 11:38 UTC, richard67 commented
@janschoenherr I've allowed myself to update the branch of this PR so new packages are created by Drone for testers, rename the update SQL scripts so that they run when updating from a current 5.3.x, and add instructions for new installation and update to the testing instructions. So the PR is ready for testing. Let's hope we find testers. Thanks a lot for your patience.

2025-08-23 19:35 UTC, SumCompanyInc commented
I have tested this item :white_check_mark: successfully on 83b58e47d8db56bf0ba082e3d5a405132dcd7414<br /><br />i've got this working!

thank you @janschoenherr and everyone progressing the advancement of this!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44571">issues.joomla.org/tracker/joomla-cms/44571</a>.</sub>

2025-08-28 15:32 UTC, rbuelund commented
Can somebody tell me how can I download the patched files (or an installable package with the patched files) so that I can test it on a fresh install ? Would like to help test on this, but did not try this on the pbf.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44571">issues.joomla.org/tracker/joomla-cms/44571</a>.</sub>

2025-08-28 15:34 UTC, richard67 commented
> Can somebody tell me how can I download the patched files (or an installable package with the patched files) so that I can test it on a fresh install ? Would like to help test on this, but did not try this on the pbf.

@rbuelund https://artifacts.joomla.org/drone/joomla/joomla-cms/5.3-dev/44571/downloads/87384/

2025-08-28 15:50 UTC, rbuelund commented
Hmmm - what am I doing wron here. I installed the Joomla_5.3.4-dev+pr.44571-Development-Full_Package.zip - created another user, and created an article. looked in the ucm_content table - empty ? Changed "Created by" of the article - ucm_content still empty ? Is there missing something in the test instructions ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44571">issues.joomla.org/tracker/joomla-cms/44571</a>.</sub>

2025-09-19 06:28 UTC, tecpromotion commented
@richard67 This needs to be adjusted again so that we use the correct SQL file, then I would also like to have it in 5.3. Thanks for your help.

2025-09-19 07:31 UTC, richard67 commented
> @richard67 This needs to be adjusted again so that we use the correct SQL file, then I would also like to have it in 5.3. Thanks for your help.

@tecpromotion The date part would be ok, but the version part is of course wrong. Will fix it in a minute or two.

2025-09-19 07:35 UTC, Sulpher commented
@richard67, thank you very much for your fix. You made this and asked me to test, but I do not know how to test these changes.  
You mentioned a link: https://artifacts.joomla.org/drone/joomla/joomla-cms/5.3-dev/44571/downloads/87384/
but it gives 404 error.

2025-09-19 07:39 UTC, richard67 commented
@tecpromotion Done.

2025-09-19 07:49 UTC, richard67 commented
> @richard67, thank you very much for your fix. You made this and asked me to test, but I do not know how to test these changes. You mentioned a link: https://artifacts.joomla.org/drone/joomla/joomla-cms/5.3-dev/44571/downloads/87384/ but it gives 404 error.

@Sulpher The download link can be found at the bottom of the PR in the CI checks. It changes with every new build (branch update). After some time old downloads are deleted that's why you got the 404. The current link now after I have triggered a new build is https://artifacts.joomla.org/drone/joomla/joomla-cms/5.3-dev/44571/downloads/88090/ .

There you can find a download links to installation and update zip packages and a custom URL for using as custom update source in the Joomla Update component.

You can either make a new installation with the installation package, or (better because this would also test the SQL update) update a 5.3.3 (testing site) to this PR by either using the custom update URL for live update or the update package for upload & update and then test the PR.

2025-09-19 13:03 UTC, Sulpher commented
@richard67 thank you very much for the explanation and link. I've downloaded that version you've gave a link on and reproduced the task. All works fine now!

<img width="1130" height="282" alt="изображение" src="https://github.com/user-attachments/assets/09bad5b5-aa47-4860-8fb2-68e12d5054ff" />

Apart from Admin there are Venus and Earth - names of other users whom the articles were assigned to while the article was created by Admin.

I'm confirming the patch works now. Thank you

2025-09-19 13:06 UTC, richard67 commented
@Sulpher Please go to the issue tracker here https://issues.joomla.org/tracker/joomla-cms/44571 and mark your test result by using the blue "Test this" button at the top left corner, selecting your test result (success) and finally using the submit button. Thanks in advance.

2025-09-19 13:12 UTC, Sulpher commented
I have tested this item :white_check_mark: successfully on fee6cfac22d5e9c3673d843c27c14ca2b91570d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44571">issues.joomla.org/tracker/joomla-cms/44571</a>.</sub>

2025-09-19 13:15 UTC, Sulpher commented
> @Sulpher Please go to the issue tracker here https://issues.joomla.org/tracker/joomla-cms/44571 and mark your test result by using the blue "Test this" button at the top left corner, selecting your test result (success) and finally using the submit button. Thanks in advance.
Done.
Richard, thank you for giving a hand with the issue testing.

2025-09-19 13:16 UTC, richard67 commented
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44571">issues.joomla.org/tracker/joomla-cms/44571</a>.</sub>

2025-09-20 09:03 UTC, merged

2025-09-20 09:06 UTC, LadySolveig commented
Thank you @janschoenherr for the fix and also for testing and and the great support @richard67 @Sulpher @SumCompanyInc @tecpromotion @rbuelund @brianteeman