Make Invalid Token warnings more user friendly
joomla/joomla-cms pull request #8445
Opened 2015-11-16 10:25 UTC by izharaazmi

The session token validation implementation currently gives an empty white screen with "Invalid token" text. This is total uninformative to a normal user.

This update implicitly redirects to the previous page if the token is not valid. To prevent implicit redirect pass `false` as the second argument to  `JSession::validateToken()`

To make use of this method we need to replace any occurrence of  `JSession::checkToken('post') or jexit(JText::_('JINVALID_TOKEN'));` with `JSession::validateToken('post');`
Example is set up in com_users > login method.

2015-11-16 10:29 UTC, izharaazmi commented
I was making the changes in the `checkToken` method itself. But made this a separate method for clarity. 

The other similar discussion on this topic is ongoing in the PR #8416.

2015-11-16 10:46 UTC, izharaazmi commented
Another idea is to allow passing the second argument to `JSession::validateToken($method, $redirect)` as:

Value of `$redirect` | Behaviour
--------- | ----------------
`true`  | Redirect to the referrer page (default value)
`false` | No redirect, just return false if token is invalid
Custom URL String | redirect to this specific url if token is invalid

2015-12-04 16:06 UTC, izharaazmi commented
I was recently thinking about this method getting influenced by

> ...  it is the wrong way and against design principles: JSession is a specialised class for sessionhandling and not about redirection handling ... https://github.com/joomla/joomla-cms/pull/8416#issuecomment-156991525

I see most of these checks are done in controllers and all (almost) are inherited from `JControllerLegacy`. Would that be an appropriate location to move this method `validateToken`, however I like the name `checkToken` more.
So that we can do the check like:

```php
$this->checkToken('post', true); // checkToken($method, $redirect)
```
Then gradually update the core components to use this test by test.

2015-12-19 13:55 UTC, peterpeter commented
Better.

But you don't have to move your new method, just use the allready existing ones from JControllerLegacy instead:
You just have to change
```php
JSession::checkToken('post') or jexit(JText::_('JINVALID_TOKEN'));
```
to
```php
JSession::checkToken('post') or $this->setRedirect($url, JText::_('JINVALID_TOKEN'))->redirect();
```
with the right url and your improved message.

Your solution is still a code- (and test-) duplication.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/joomla-cms/8445</a>.</sub>

2015-12-19 14:15 UTC, izharaazmi commented
@peterpeter I almost agree. But to me the code does not appear to be any duplication. It internally uses the already existing method. The extra method introduced is just to provide the ability to auto calculate the REFERER page url for redirection. If that is not needed then of course we can follow what you suggested. But I think it could be useful.

2016-04-15 12:47 UTC, henkrijneveld commented
I agree this is a real problem, but in current state untestable (we do not have a solution). Please elaborate, because it is a good idea to solve this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/joomla-cms/8445</a>.</sub>

2016-06-24 21:10 UTC, roland-d commented
Hello @izharaazmi 

Thank you for your contribution.

The last comment here was on April 15th. Can you update this PR so it is testable?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/joomla-cms/8445</a>.</sub>

2016-06-26 09:41 UTC, izharaazmi commented
I have made the necessary changes in the front-end components. Please see https://github.com/joomla/joomla-cms/pull/8445#issue-117092548 for updated notes.

I hope it is now testable for the front-end. I'll preferably do backend implementation as a separate PR if this is approved.

2016-07-12 12:19 UTC, hardiktailored commented
I have tested this item :red_circle: unsuccessfully on 4b630b05e3816591a4b8d29f5b205d8e5907887c<br /><br />I found issue, after applying patch and I modified token of login form presented on sidebar. It redirects to blank screen, Network tab shows "500 Internal Server Error". Before applying patch "The most recent request was denied because it contained an invalid security token. Please refresh the page and try again." message was appearing on screen.

For the other inner pages warning message "The security token did not match. The request was aborted to prevent any security breach. Please try again." appears after applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/joomla-cms/8445</a>.</sub>

2016-07-12 12:24 UTC, hardiktailored commented
Check the warning message after patch applied(All pages except login form problem mentioned above):
![screen shot 2016-07-12 at 07 20 46](https://issues.joomla.org/uploads/1/a217779b09ab2c19d05241cc76b72590.png)

Before applying patch (for all screens):
![screen shot 2016-07-12 at 07 23 01](https://issues.joomla.org/uploads/1/484266fe08698d14e9b465d1d45510b3.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/joomla-cms/8445</a>.</sub>

2016-08-23 06:47 UTC, izharaazmi commented
@hardiktailored I tested it again and it worked fine. I may be missing something... can you please explain the issue a little more?

2016-09-05 05:41 UTC, AnishaTailored commented
I have tested this item :red_circle: unsuccessfully on 4b630b05e3816591a4b8d29f5b205d8e5907887c<br /><br />I have also found the issue after applying this patch (using the patchtester component) same as @hardiktailored, when I login (after modifying the token from DOM), I get the following error "
Fatal error: Call to undefined method JSession::validateToken() in components/com_users/controllers/user.php on line 30".

Before applying the patch login function has JSession::checkToken('post') or jexit(JText::_('JINVALID_TOKEN')); instead of JSession::validateToken('post');
I have checked for other forms (registration, reset password, remind username, edit profile etc.), they are working fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/joomla-cms/8445</a>.</sub>

2016-09-05 09:01 UTC, izharaazmi commented
@AnishaTailored Thanks for explaining the issue in detail. I found that in my previous commit I had missed changing one occurrence of `validateToken` that was causing failures. 

I've fixed it now, please test this again.

2016-09-05 09:16 UTC, AnishaTailored commented
I have tested this item :white_check_mark: successfully on 39a5a50ca35e2a386a40c89b9bada463f84a8394<br /><br />Now it works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/joomla-cms/8445</a>.</sub>

2016-09-05 10:07 UTC, izharaazmi commented
@hardiktailored Can you test this again please.

2016-09-05 10:09 UTC, andrepereiradasilva commented on libraries/legacy/controller/legacy.php
> +	 * @since   3.6.0
please use `__DEPLOY_VERSION__`

2016-09-05 13:43 UTC, izharaazmi commented on libraries/legacy/controller/legacy.php
> +	 * @since   3.6.0
Thanks. Done.

2016-09-22 15:41 UTC, Devportobello commented on components/com_users/controllers/user.php
> +		// $this->checkToken('post');
comment ?

2016-09-22 15:42 UTC, Devportobello requested changes

2016-09-29 13:49 UTC, izharaazmi commented on components/com_users/controllers/user.php
> +		// $this->checkToken('post');
I did that because I don't see any code in that function. I don't understand why that method is kept there.

2016-11-04 13:38 UTC, hvdmeer commented
I have tested this item :white_check_mark: successfully on b05765dc853b023620774c92bdafe950481c2f56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/tracker/joomla-cms/8445</a>.</sub>

2016-11-04 14:06 UTC, renekreijveld commented
I have tested this item :white_check_mark: successfully on b05765dc853b023620774c92bdafe950481c2f56<br /><br />Tested with modification of the token through Firebug. After patch installation better message in a alert.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8445">issues.joomla.org/tracker/joomla-cms/8445</a>.</sub>

2016-11-04 21:18 UTC, zero-24 commented
Please resolve the merge conflicts.

@rdeutz or @wilsonge please review and take a final decision here.

2016-11-05 07:17 UTC, izharaazmi commented
I was resolving the conflict, then I saw the missing `register` method the controller. Little investigation led me to https://github.com/joomla/joomla-cms/commit/bae1d43938c878480cfd73671e4945211538fdcf#diff-f820ef502f338b5be5a00aac838e756fL287. I could not find the exact PR which actually made this change. On 3.7.x branch this method still exists. Somebody guide me at this please!

2016-11-05 07:20 UTC, zero-24 commented
This is removed in 3.6.4 to avoid registations over the wrong way. 3.7.0-dev branch is not updated with this change as staging is now 3.7.-dev

2016-11-05 07:22 UTC, izharaazmi commented
Won't it break b/c for components redirecting/submitting to that task for registration?

2016-11-05 07:27 UTC, zero-24 commented
Yes. But it was the decision of the JSST to remove that method as it is not used anymore and was never correctly implemented.

2016-11-05 07:42 UTC, izharaazmi commented
@zero-24 Thanks for clarification. I have updated my branch to latest staging hence resolved the conflicts.

2016-11-05 10:11 UTC, merged

2016-11-05 10:15 UTC, izharaazmi commented
Thanks everybody for making this to this point 👍 

I think this should followed up by some documentation update. Please advise where can I do that.

2016-11-05 11:05 UTC, andrepereiradasilva commented
@izharaazmi can you do the same for all other token dies (where applies) so we have a consistent core?

There a lot of `JSession::checkToken('xxxxx') or die(JText::_('JINVALID_TOKEN'));`
```
egrep -R "JSession::checkToken" /var/www/html/joomla-staging/ | awk '{print $1}'
```

2016-11-05 11:17 UTC, izharaazmi commented
@andrepereiradasilva Sure, hope to see it this Monday! Btw, I'm having 152 occurrences. Please do let me know if you find more.

2016-11-05 13:51 UTC, PhilETaylor commented
This is also the kind of function that would benefit from some UnitTests so that it can be tested with different sessions and referers...

2016-11-07 06:21 UTC, izharaazmi commented
@andrepereiradasilva I have made the required changes. Please test the other PR at your convenience.