Bug in Joomla 3.4x Banner Manager > Tracks. Shows hourly counts instead of daily counts.
joomla/joomla-cms pull request #8825
Opened 2016-01-02 19:11 UTC by wojsmol

fix for https://github.com/joomla/joomla-cms/issues/6617#issuecomment-88164989

Original issue description

> Okay, but what about question 2 of my post?
> I'm not a Joomla expert but this seems to not be working the way the Joomla Help screen explains it should.
> 
> 2) The Banner Manager > Tracks screen keeps adding new rows of info every HOUR instead of DAILY for each Banner. Shouldn't it only list each Banner's impressions once per day instead of every hour of every day?
> The hourly impression tracking creates tons of pages in the Tracks screens over time. I would think that would be a waste of database space and unnecessary Tracks screens.
> 
> I have attached 3 screenshots of my Joomla 3.4x settings related to the Client and Banner Tracking.
> I apologize if this is not a bug but let me know if I should instead post this as a question on the Joomla.org forum instead of GitHub.

2016-01-27 12:19 UTC, waader commented
I tested this successfully, but I would not consider this a bug. I agree that hourly records are a bit excessive but this a known behaviour for a long time, see for example here: http://www.inmotionhosting.com/support/edu/joomla-3/banners/tracking

Also on an existing installation with activated tracking you would get mixed (hourly, daily) records which isn´t desirable. A neat solution could be another parameter - there aren´t that many for this component - that let´s you switch to daily records.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-01-27 12:30 UTC, brianteeman commented
it is a bug if we call it daily when it is in fact hourly

On 27 January 2016 at 12:19, waader <notifications@github.com> wrote:

> I tested this successfully, but I would not consider this a bug. I agree
> that hourly records are a bit excessive but this a known behaviour for a
> long time, see for example here:
> http://www.inmotionhosting.com/support/edu/joomla-3/banners/tracking
>
> Also on an existing installation with activated tracking you would get
> mixed (hourly, daily) records which isn´t desirable. A neat solution could
> be another parameter - there aren´t that many for this component - that
> let´s you switch to daily records.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/8825
> <https://issues.joomla.org/tracker/joomla-cms/8825>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8825#issuecomment-175590358>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

2016-01-27 12:42 UTC, waader commented
You probably mean the description in the mentioned help text. As I get no help text at all I searched via google and found that this behaviour is known for a long time. So in this case I would say, correct the help text. Anyway.

2016-01-27 13:00 UTC, brianteeman commented
To me the code is wrong not the text

On 27 January 2016 at 12:42, waader <notifications@github.com> wrote:

> You probably mean the description in the mentioned help text. As I get no
> help text at all I searched via google and found that this behaviour is
> known for a long time. So in this case I would say, correct the help text.
> Anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8825#issuecomment-175600019>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

2016-04-15 11:21 UTC, waader commented
I have tested this item :white_check_mark: successfully on 139d644a15203fdbf54076110e5dded4fe47fcc7<br /><br />Does what it says but I see no issue here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-06-28 14:29 UTC, conconnl commented
It would be a nice addition if you could choose between Hourly or Daily through the settings.
If you just change the code, existing environments will start working differently.
When you create a configuration option for it and keep the default the same you won't change existing websites.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-06-28 15:10 UTC, wojsmol commented
just a rebase to current staging.

2016-06-28 17:08 UTC, wojsmol commented
@brianteeman Plese check new language strings

2016-06-28 17:09 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_banners.ini
> +COM_BANNERS_FIELD_TRACKFREQUENCY_DESC="Select the frequency with which you want to create new entries in the tracking view"
Add a . period at the end of the sentence

2016-06-28 17:09 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_banners.ini
> +COM_BANNERS_FIELD_TRACKFREQUENCY_LABEL="Track frequency"
Capitalise frequency please

2016-06-28 17:10 UTC, brianteeman commented
Lol I was just commenting on the strings when I got the email :)

2016-06-28 17:41 UTC, wojsmol commented
@conconnl @waader Please test now

2016-06-28 19:06 UTC, zero-24 commented on components/com_banners/models/banner.php
> +			$track_frequency = $params->get('$track_frequency', 'hourly');
>$params->get('$track_frequency', 'hourly');

I guess the extra $ here is a misstake? As it can't work with it included as the param name is without $ ;)

2016-06-28 19:07 UTC, zero-24 commented on components/com_banners/models/banners.php
> +		$track_frequency = $params->get('$track_frequency', 'hourly');
same here with the extra $ ;)

2016-06-28 19:09 UTC, zero-24 commented on components/com_banners/models/banner.php
>  			$trackDate = JFactory::getDate()->format('Y-m-d');
this can't work because we set it to `'Y-m-d H'` in line 81 and override it everytime with `'Y-m-d'` in line 84.

I think moving the line 84 above the if can fix the issue:

```
$trackDate = JFactory::getDate()->format('Y-m-d');

 if ($track_frequency == 'hourly')
 {
 	$trackDate = JFactory::getDate()->format('Y-m-d H');
 }
```

2016-06-28 19:10 UTC, wojsmol commented on components/com_banners/models/banner.php
> +			$track_frequency = $params->get('$track_frequency', 'hourly');
copy/paste error, give me a minute

2016-06-28 19:10 UTC, zero-24 commented on components/com_banners/models/banners.php
>  		$trackDate = JFactory::getDate()->format('Y-m-d');
same here i think we should move as above ;)

2016-06-28 19:13 UTC, zero-24 commented
my seccond comment still applys ;)

 this can't work because we set it to `'Y-m-d H'` in line 81 and override it everytime with `'Y-m-d'` in line 84.

I think moving the line 84 above the if can fix the issue:

```
$trackDate = JFactory::getDate()->format('Y-m-d');

 if ($track_frequency == 'hourly')
 {
 	$trackDate = JFactory::getDate()->format('Y-m-d H');
 }
```

2016-06-28 19:24 UTC, wojsmol commented
@zero-24 Thans for comments

2016-06-28 20:05 UTC, zero-24 commented
Looks better thanks :+1:

2016-06-29 22:40 UTC, conconnl commented
@wojsmol I Tested this correctly, but I'm seeing one inconsistency.
<img width="527" alt="screen shot 2016-06-30 at 00 36 21" src="https://cloud.githubusercontent.com/assets/11913918/16471126/0b3196f6-3e5b-11e6-8587-e8dc937436b7.png">

The text states: "These settings apply for all clients unless they are changed for a specific client. "
But the "Track Frequency" is not configurable on client level.
Maybe you can add this to the Client part and then everything is perfect.

2016-06-30 17:53 UTC, conconnl commented
@wojsmol The track frequency at client level does not work, it keeps jumping back to hourly.
Instead of the selected setting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-07-01 03:45 UTC, wojsmol commented
After applying the patch run the database fix in Extensions> Manage> Database.

2016-07-01 12:34 UTC, conconnl commented
I have tested this item :white_check_mark: successfully on ca1e68b630b9cb1a01cc30e124a997af724315b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-07-01 12:35 UTC, conconnl commented
@wojsmol it works perfectly now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-07-01 19:28 UTC, wojsmol commented
@waader @alikon Plese test in postgresql and sqlazure if passible.

2016-08-01 11:27 UTC, toxic2302 commented
I have tested this item :white_check_mark: successfully on ec75c7ae2a0bb055ebe252274ecca349c39cc29f<br /><br />After I have installed the patch and fixed the database I'm able to see the track frequency option.
On the client level of the banner I checked the daily option and it doesn't switch to hourly. I have tested with a mysql database.

So in my opinion it works correctly.

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-08-02 12:10 UTC, florian1995 commented
I have tested this item :white_check_mark: successfully on ec75c7ae2a0bb055ebe252274ecca349c39cc29f<br /><br />I applied the patch and got the track frequency option wich works correctly.
I had done the database fix and can change between daily and hour now.
Using MySQL.
Tested@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-08-02 12:34 UTC, roland-d commented
@waader @alikon requesting if you can test in postgresql and sqlazure if possible. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/joomla-cms/8825</a>.</sub>

2016-08-16 02:07 UTC, wojsmol commented
rebase after https://github.com/joomla/joomla-cms/pull/11619

2016-11-04 12:34 UTC, renekreijveld commented
I have tested this item :white_check_mark: successfully on 7428d3b7388bfa76033e70961545cfba815d1a8d<br /><br />Installed the patch and could set the Track Frequency option to Hourly or Daily. I set the option to Hourly. In the Banner edit form I can set the Track Frequency to Hourly or Daily. In the Client edit form I can also set the Track Frequency to Hourly or Daily.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/tracker/joomla-cms/8825</a>.</sub>

2016-11-04 14:40 UTC, superknutsel commented
I have tested this item :white_check_mark: successfully on 7428d3b7388bfa76033e70961545cfba815d1a8d<br /><br />Tested both options (hourly and daily) and it works like expected after the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/tracker/joomla-cms/8825</a>.</sub>

2016-11-04 15:49 UTC, slibbe commented
I have tested this item :red_circle: unsuccessfully on 7428d3b7388bfa76033e70961545cfba815d1a8d<br /><br />Tested this one with PostgreSQL. Getting several errors, not only related to this issue. Needs a more thorough review. 

If needed I can test more on PostgreSQL. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/tracker/joomla-cms/8825</a>.</sub>

2016-11-05 17:42 UTC, wojsmol commented
@slibbe Could I ask you to provide errors for PostgreSQL associated with this PR?

2016-11-06 11:21 UTC, alikon commented
@slibbe  can you report on a new issue what error you get using banner with postgresql if they are not related to this pr

2016-11-06 14:58 UTC, wojsmol commented
@alikon Can you test this PR on postgresql?

2017-04-07 15:14 UTC, waader commented
@wojsmol If you could sync this patch I will test on postgresql and mssql.

2017-04-08 20:21 UTC, wojsmol commented
@waader PR is rebased to staging

2017-04-10 09:59 UTC, waader commented
With postgres I get a syntax error for type timestamp with this query:

UPDATE #__banner_tracks SET "count" = ("count" + 1) WHERE track_type=1 AND banner_id=4 AND track_date='2017-04-10 09'

2017-04-10 11:48 UTC, wojsmol commented
@waader Do you have any idea how to solve this problem? I have no experience with postgres.

2017-04-30 07:06 UTC, wojsmol commented
cc @alikon see error reported by @waader  any idea?

2017-04-30 08:35 UTC, alikon commented
you should use `CAST()` to  the correct timestamp type

2017-04-30 08:42 UTC, wojsmol commented
@alikon Plese send PR with appropriate changes.

2017-05-02 02:03 UTC, wojsmol commented
@alikon Please send a PR with appropriate changes to me branch.

2018-07-22 19:24 UTC, roland-d commented
@alikon Can you help here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/tracker/joomla-cms/8825</a>.</sub>

2018-08-02 07:50 UTC, franz-wohlkoenig commented
gently Reminder @alikon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/tracker/joomla-cms/8825</a>.</sub>

2018-08-02 07:55 UTC, wojsmol commented
or @csthomas maybe?

2018-08-02 08:43 UTC, alikon commented
the issue is to use a date to compare a timestamp field as reported 1 year and plus ago by @waader https://github.com/joomla/joomla-cms/pull/8825#issuecomment-292904453
see here https://github.com/joomla/joomla-cms/pull/8825/files#diff-4140a4b988c67c2915e88362dd9815ceR79 ,  so provide the correct data type or compare the same data type  before issuing a comparison, this should be a normal rule not  a postgresql rule only

2018-08-06 22:18 UTC, csthomas commented
I only did a code review. 

IMO all lines `$trackDate = JFactory::getDate()->format('Y-m-d H');` should be replaced by something like `$trackDate = JFactory::getDate()->format('Y-m-d H:00:00');` and the same for `$trackDate = JFactory::getDate()->format('Y-m-d');` should be replaced by `$trackDate = JFactory::getDate()->format('Y-m-d 00:00:00');`.

Then all values should be OK.

Another issue is that there is no time zone and everything will be calculated in UTC.

2018-08-08 13:08 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_banners.ini
> +COM_BANNERS_FIELD_TRACKCLICK_DESC="Record the number of clicks on the banners on a daily or hourly basis."
Remove 
"on a daily or hourly basis."

2018-08-08 13:09 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_banners.ini
> +COM_BANNERS_FIELD_TRACKIMPRESSION_DESC="Record the impressions (views) of the banners on a daily or hourly basis."
Remove 
"on a daily or hourly basis."

2018-08-08 13:09 UTC, brianteeman commented on administrator/language/en-GB/en-GB.com_banners.ini
> +COM_BANNERS_FIELD_TRACKFREQUENCY_DESC="Select the frequency with which you want to create new entries in the tracking view."
Change to
Select to update hourly or daily.

2018-08-08 13:10 UTC, brianteeman requested changes
Update the strings please as commented

2018-08-08 13:30 UTC, Quy commented on components/com_banners/models/banner.php
> +			$trackDate = JFactory::getDate()->format('Y-m-d 00:00:00');.
Remove period.

2018-08-08 13:30 UTC, Quy commented on components/com_banners/models/banners.php
> +		$trackDate = JFactory::getDate()->format('Y-m-d 00:00:00');.
Remove period.

2018-08-24 12:00 UTC, franz-wohlkoenig commented
@wojsmol should this Pull Request test again or is it waiting for something else?

2018-08-24 12:11 UTC, wojsmol commented
@franz-wohlkoenig PR is ready for testing.
@brianteeman Please accept language strings.

2018-08-24 12:13 UTC, franz-wohlkoenig commented
@wojsmol will test.

2018-08-24 12:15 UTC, brianteeman commented
@wojsmol I requested changes 16 days ago

2018-08-24 12:17 UTC, wojsmol commented
@brianteeman Please see https://github.com/joomla/joomla-cms/pull/8825/commits/5ff5f0ee402820efef8339df9b735109fe41aac1 :smile:

2018-08-24 12:21 UTC, brianteeman commented
![image](https://user-images.githubusercontent.com/1296369/44584323-74252f00-a7a0-11e8-8eaf-53cb21652702.png)

2018-08-24 12:31 UTC, alikon requested changes

2018-08-24 12:31 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/3.6.0-2016-07-01.sql
> +ALTER TABLE "#__banners" ADD COLUMN "track_frequency" VARCHAR(6) NOT NULL DEFAULT 'hourly' AFTER "track_impressions";
There is no AFTER syntax on postgresql  nor in mssql AFAIK

2018-08-24 13:43 UTC, wojsmol commented
@brianteeman Fixed in latest commit.

2018-08-24 13:46 UTC, brianteeman approved these changes
language changes are ok

2018-08-24 13:49 UTC, wojsmol commented on administrator/components/com_admin/sql/updates/postgresql/3.6.0-2016-07-01.sql
> +ALTER TABLE "#__banners" ADD COLUMN "track_frequency" VARCHAR(6) NOT NULL DEFAULT 'hourly' AFTER "track_impressions";
For mysql there is - see https://dev.mysql.com/doc/refman/5.6/en/alter-table.html. I will fix postgres file in few minutes.

2018-08-24 14:27 UTC, alikon commented on administrator/components/com_admin/sql/updates/postgresql/3.6.0-2016-07-01.sql
> +ALTER TABLE "#__banners" ADD COLUMN "track_frequency" VARCHAR(6) NOT NULL DEFAULT 'hourly' AFTER "track_impressions";
tbh the column order does not matter for storage or querying, so, btw, my comment was also about  mssql/azure https://github.com/joomla/joomla-cms/pull/8825/files/19db8a7bbd0ec9a9246ff5fc9bc552be00fcf43b#diff-9c245b9c7291e18f677e37f290a3edaeR1

2018-08-24 14:29 UTC, alikon requested changes
https://github.com/joomla/joomla-cms/pull/8825/files/19db8a7bbd0ec9a9246ff5fc9bc552be00fcf43b#r212646464

2018-08-24 15:53 UTC, wojsmol commented
@alikon AFTER removed in https://github.com/joomla/joomla-cms/pull/8825/commits/4e3bc264c0a969b02d6040c7fb79219e0ede37ef

2018-08-24 15:57 UTC, alikon commented
@wojsmol thanks

2018-08-25 07:13 UTC, franz-wohlkoenig commented
@wojsmol to be sure what to test can you give please Test Instructions?

2018-09-19 16:38 UTC, twister65 commented
I have tested this item :red_circle: unsuccessfully on 4e3bc264c0a969b02d6040c7fb79219e0ede37ef<br /><br />Using PostgreSQL (PDO).
Can't see banners tracks.
No Matching Results.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8825">issues.joomla.org/tracker/joomla-cms/8825</a>.</sub>

2019-04-22 09:13 UTC, twister65 commented
Please see the attached file to allow banner and client settings for impressions:
[diff_banners.txt](https://github.com/joomla/joomla-cms/files/3102856/diff_banners.txt)
It also fixes client track impressions parameter.

Please see the attached file to allow banner and client settings for clicks:
[diff_banner.txt](https://github.com/joomla/joomla-cms/files/3102857/diff_banner.txt)
It also fixes client track clicks parameter.

2019-04-24 18:00 UTC, twister65 commented
Fixes to read the track_frequency parameter of the component (banner and client):
[banner_patch.txt](https://github.com/joomla/joomla-cms/files/3113616/banner_patch.txt)
[banners_patch.txt](https://github.com/joomla/joomla-cms/files/3113617/banners_patch.txt)

2019-06-29 21:47 UTC, HLeithner commented
This is the oldest PR we have and sadly it started with a bug fix and is now a new feature.

Our policy says no new features in patch levels and no new feature in combat version 3.10. I don't know why this PR hasn't merged before but now I would like to ask you @wojsmol to rebase this PR on J4.

This would be really great, thx. In the meantime I close this PR.

2019-06-29 21:47 UTC, closed without merging