Update media.php - Eclipse throughs Error, beautify
joomla/joomla-cms pull request #9753
Opened 2016-04-06 10:42 UTC by tkuschel

Pull Request for Issue # .

#### Summary of Changes

#### Testing Instructions

* With Eclipse IDE, it through an error and a notice too
* No need to escape apostrophs, and no concatenation in php
* Opening and Closing <div> will be found 
since 3.5.0/3.5.1

2016-11-13 06:55 UTC, roland-d commented on layouts/joomla/form/field/media.php
>   <?php echo JText::_('JLIB_FORM_BUTTON_SELECT'); ?></a><a class="btn hasTooltip" title="<?php echo JText::_('JLIB_FORM_BUTTON_CLEAR'); ?>" href="#" onclick="jInsertFieldValue('', '<?php echo $id; ?>'
Can you reformat this line to codestyle as well? Lines should be a maximum of 150 characters max and each PHP statement should be on a line of it's own. Thank you.

2017-02-25 09:08 UTC, RonakParmar commented
@tkuschel Please fix mentioned comment in PR and at the end there is an error of "No newline at end of file", fix this too.
So we can test it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9753">issues.joomla.org/tracker/joomla-cms/9753</a>.</sub>

2017-02-27 08:03 UTC, tkuschel commented
I've merged this PR to the staging and did fix the mentioned comments above. I'm a little confused about "No newline at end of file", because in the actual Joomla coding standard, you'll find a "Files should always end with a blank new line." see 3rd paragraph in https://developer.joomla.org/coding-standards/php-code.html

2017-02-27 16:56 UTC, zero-24 requested changes
Please remove the extra spaces in line 170. Thanks

2017-02-27 20:05 UTC, tkuschel commented
@zero-24 : I already deleted the spaces on line 170, with the second update today. Please check again https://github.com/joomla/joomla-cms/pull/9753/commits/3649bb1fe6806f81f4ceb5385e4a06b88a0752c2

2017-03-03 16:08 UTC, tkuschel commented
@zero-24 please test again, I already did your requested changes, thank you.

2017-03-03 16:11 UTC, tkuschel reviewed
already removed spaces at line 170

2017-03-03 18:05 UTC, zero-24 approved these changes
lgtm

2017-05-18 11:02 UTC, oe1tkt commented
This behavior still exists in Joomla 3.7.1

2017-08-21 10:00 UTC, Heggi93 commented
I have tested this item :red_circle: unsuccessfully on a40b01e4b1d688e7ab8c615c08e6391ae35a6322<br /><br />The warnings/errors mentioned above are not shown any more but there are some warnings which may create errors for some reasons. Every attribute of a \<div> should be distanced with a wide space from the others, e.g. in line 140 should be a space between _preview_img" and '. In line 141 is the same problem.

In common it is more comfortable to separate php and HTML-Code. Please avoid echo"\<div>...\</div>" or something like this. For example line 160-163 should stand in php-brackets instead of using echo. If this is not an option because you need the value of a php-variable you can use the shorter form of echo which is \<?= $variable ?>. Line 160 to 163 can look like:

?> 
\<div class="media-preview add-on" style="height:auto">
		\<?= ' ' . $previewImgEmpty ?>
		\<?= ' ' . $previewImg ?>
		\</div> 
\<?php

If you try to write your code like this, you'll see that errors will be found more easily because HTML is clearly separated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9753">issues.joomla.org/tracker/joomla-cms/9753</a>.</sub>

2017-08-21 10:17 UTC, brianteeman commented
@heggi93 please read the code style rules before giving that advice

2017-08-22 08:05 UTC, SamuelSchepp commented
I have tested this item :white_check_mark: successfully on a40b01e4b1d688e7ab8c615c08e6391ae35a6322<br /><br />Without patch:
phpcs: Generic.Files.LineLength.TooLong: Line exceeds 150 characters; contains 217 characters
phpcs: Generic.WhiteSpace.ScopeIndent.IncorrectExact: Line indented incorrectly; expected 1 tabs, found 0
phpcs: Generic.Files.EndFileNewline.NotFound: File must end with a newline character

With patch:
Warnings from above are resolved.
No phpcs or phpmd warnings.

But no merge possible. Tested via com_patchtester.
@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9753">issues.joomla.org/tracker/joomla-cms/9753</a>.</sub>

2017-10-26 12:30 UTC, franz-wohlkoenig commented
@Heggi93 can you please retest?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9753">issues.joomla.org/tracker/joomla-cms/9753</a>.</sub>

2017-10-26 13:04 UTC, infograf768 commented
There are obvious errors in this patch.

2017-10-26 13:13 UTC, franz-wohlkoenig commented
@infograf768 you mean conflicting Files?

2017-10-26 15:39 UTC, infograf768 commented on layouts/joomla/form/field/media.php
> +	rel="{handler: 'iframe', size: {x: 800, y: 500}}">
```
. $authorField) . '&amp;fieldid=' . $id . '&amp;folder=' . $folder) . '"'
. ' rel="{handler: \'iframe\', size: {x: 800, y: 500}}"'; ?>>
```
is correct, not what the patch does.

2017-10-26 15:40 UTC, infograf768 commented
Not only. See comment above.

2017-10-26 15:54 UTC, mbabker commented on layouts/joomla/form/field/media.php
> +	rel="{handler: 'iframe', size: {x: 800, y: 500}}">
It's the exact same thing.  The only difference is in where the closing PHP tag is and inherently what is processed through PHP versus what is "plain" HTML.

And to be honest, I think we make our HTML really difficult to read/follow because of how much we jump between PHP and HTML or try to use difficult to follow syntax.  If you really want to do this right, get rid of the ternary condition check and actually make this a legible HTML snippet.

```php
<?php
$modalLink = '';
if (!$readonly) {
    $modalLink = $link ?: 'index.php?option=com_media&amp;view=images&amp;tmpl=component&amp;asset=' . $asset . '&amp;author=' . $authorField) . '&amp;fieldid=' . $id . '&amp;folder=' . $folder;
}
?>
<a class="modal btn" title="<?php echo JText::_('JLIB_FORM_BUTTON_SELECT'); ?>" href="<?php echo $modalLink; ?>" rel="{handler: 'iframe', size: {x: 800, y: 500}}"><?php echo JText::_('JLIB_FORM_BUTTON_SELECT'); ?></a>

2018-05-08 22:31 UTC, brianteeman commented
It has been a year since the last update and there are conflicts. I am going to close this at this time - it can always be reopened if updated

2018-05-08 22:31 UTC, closed without merging